@NT = Nandipur<193><207>a
The pur<193><207>as†the mythological lore of Hinduism†contain a lot ç
of material on the subjects generally dealt with in the dharma·<193>stra ç
literature. They have been traditionally grouped under two heads: ç
The Mah<193>pur<193><207>as and the Upapur<193><207>as, each of them ç
being 18 in number.
The   Nandipur<193><207>a†also   called Nandapur<193><207>a†assigned ç
to the latter group, is probably lost now, though a large number of ç
its verses have been quoted inthe Kalpataru of Lak<218>m<200>dhara ç
(12th century <MS>A.D.<D>) and Apar<193>rka of Apar<193>ditya (also ç
of 12th century <MS>A.<|>D.<D>).
@EMERGENCY = Some of the interesting subjects dealt with in it are: ç
<193>rogyad<193>na by starting and running free hospitals; vidy<193>d<193>na ç
by running p<193><219>ha·<193>las or schools; abstention from meat-eating.
@EMERGENCY = This pur<193><207>a was probably composed during the ç
8th or the 9th century <MS>A.<|>D.<D>
@NT = Nandotsava
@EMERGENCY = <185>r<200> K<216><218><207>a was born on the midnight ç
of <185>r<193>va<207>a-k<216><218><207>a-a<218><219>am<200> (the eighth ç
day of the dark fortnight of the month of <185>r<193>va<207>a, generally ç
in August). He was immediately transported from the prison of Ka<221>sa, ç
the tyrant, to the house of Nanda, the chief ofthe cow-herds at Gokula. ç
The next dayknown as <185>r<200>k<216><218><207>a-jayant<200> or ç
simply Jayant<200>, was celebrated by Nanda with great joy and fervour. ç
Hence that day†the Jayant<200>†is also called `Nandotsava'.
@EMERGENCY = See also <MS>JANM°<186><187>AM®.<D>
@NT = nara, Nara
A human being is called `nara' since he is led into this world by ç
his karma (deserts of actions) done in the previous lives (n<216> ç
naye = to lead).
Nara is also the name of Lord Vi<218><207>u (vide Vi<218><207>usahasran<193>ma, ç
no. 246). It is interpreted as:
a)
@NK NO # = One who inspires a human being into actions and also gives ç
the fruits of the same;
b)
@NK NO # = One who is beyond death anddestruction (ra = k<218>aya ç
or destruction; na= not).
c)
@NK NO # = One who is changeless;
d)
@NK NO # = One who destroys the miseries of human beings.
See also <MS>NARA-N°R°YAØA<D>.
@NT = narabali
@N1 = (`human sacrifice')
The word `Puru<218>amedha' (`sacrificing a human being') occurs in ç
°pastamba <185>rautas<220>tras (20.24, 25) and Baudh<193>yana <185>rautas<220>tras ç
(24.11). It is a type of Somay<193>ga spread over five days.
Whether a puru<218>a (human being) was actually sacrificed or whether ç
the whole act had been symbolical, is difficult to ascertain.
There are references to narabali in the <185>atapatha Br<193>hma<207>a ç
(1.2.3,6) and the Taittir<200>ya Sa<221>hit<193> (2.2.2,4) also.
According to one view, since a large quantity of human and animal ç
bones were recovered at the site of excavations at Kau·<193>mbi (the ç
modern Kosam, about 50 kms. [31 miles] to the east of Allahabad in ç
Uttar Pradesh) including an ancient altar, this sacrifice must have ç
existed.
According to other scholars, the rite was only symbolical. After the ç
paryagnikara<207>a rite†wherein the <193>gn<200>dhra priest goes round ç
the human beings and the animals with a lighted torch†the human beings ç
are released and only goats are sacrificed (vide P. V. Kane, History ç
of Dharma·<193>stra Vol. 3, Poona, Bhandarkar Oriental Research Institute, ç
1946; pages 961-2).
In the pur<193><207>as we do come across the  practice  of  narabali  by  certain ç
aboriginal cults (vide Bh<193>gavata 5.9.15 to 17). The great spiritual ç
teacher <185>a<209>kara (<MS>A.<|>D.<D> 788-820) is said to have been ç
approached for sacrifice by the K<193>p<193>likas. He was later on ç
saved by his disciple Padmap<193>da.
We find a reference to Puru<218>amedha in the story of Hari·candra ç
as given in the Bh<193>gavata (9.7) wherein <185>una··epha was about ç
to be offered to Varu<207>a but was saved by his prayer to that deity.
The rite might have existed at least in the most aboriginal tribes.
@SPACE = 
@NT = N<193>rada
@SPACE1 = 
See <MS>N°RADA BHAKTIS<188>TRAS<D>.
@SPACE = 
@NT = N<193>rada Bhaktis<220>tras
@SPACE1 = 
The N<193>rada Bhaktis<220>tras is a well-known and popular work ç
on bhakti or devotion to God. Hence a fairly detailed account may ç
now be given here.
@S10N = THE IMPORTANCE OF HUMAN BIRTH
We see two classes of things†animate and inanimate†in the Lord's creation. ç
Among the animates there are two classes again†animals and human beings. ç
Only man possesses the intellect and consciousness to shape his life ç
and to think independently. That is why Purandara D<193>sa (<MS>A.D.<D> ç
1484-1564) said: ``Human birth is great, don't waste it, O crazy men!'' ç
It is mentioned in our mythological works that a soul will have passed ç
through eight million and four hundred thousand births before attaining ç
this invaluable human birth!
@SPACE = 
@S10N = ENQUIRY FOR TRUTH
@SPACE1 = 
After things like food, clothes and shelter needed for physical sustenance ç
and protection are met, the enquiry for Truth that has been in the ç
heart of every conscious person from the very beginning, gets aroused. ç
Birth and death, natural marvels, the bitter experiences of life†all ç
these make man introspective. ``Who amI? What wasI before I was ç
born? Where was I? Wherefrom, how and why have I come to this world? ç
What is death? Where do I go after death? Or, is death itself the ç
ultimate state? Do I become extinct then? Where did this world come ç
from? How and why was it created? Who created it? If there is a God ç
who is the creator and ruler of this world, what form has He? What ç
is the relationship between Him and this world, the other living things ç
and my own Self? What is the object of human life? How does one attain ç
it?''† Such  questions  as  these,  have  been troubling man since ç
time immemorial.
@SPACE = 
@S10N = THE VEDAS
@SPACE1 = 
Those great men who considered these questions with the seriousness ç
they deserve, dedicating their very lives to find out answers to these ç
questions, discovering solutions to them through austerity, meditation ç
and knowledge, and thereby havebecome the guiding spirits of later ç
generations,  are  called  `<216><218>is'  in  this country. The spiritual ç
knowledge that has come down to us from the <216><218>is is called ç
the `Vedas' or `<185>ruti'. We believe that these are not knowledge ç
discovered by the <216><218>is on their own, but are directly revealed ç
in their pure mind by the Lord Himself. This kind of belief exists ç
in the other important religions of the world too.
@S10N = VED°NTA
The essential aspect of these Vedas or <185>rutis are the Upani<218>ads. ç
It is customary to call them as `Ved<193>nta'. According to this Ved<193>nta, ç
the fundamental reality out of which the world has arisen is Brahman, ç
the Ultimate Self. It is real, conscious, infinite and blissful. This ç
creation has emerged from It, is supported by It, and gets dissolved ç
in It. We too are the everlasting consciousness, the Self, which is ç
birthless and deathless that transcends the body, mind and the senses. ç
The Ultimate Reality is in the heart of this creation, as well as ç
ourselves; at the same time, it is beyond all these and exists externally ç
too in its infinite nature. We groan under the revolving wheel of ç
birth and death because of `avidy<193>,' or ignorance, since we consider ç
that we are the body, the senses and such other things. This is what ç
is called `sa<221>s<193>ra.' Only when we, the `j<200>v<193>tmas,' ç
who are in bondage, become aware of Brahman, i.e., when we realize ç
It, shall we be free of this wheel of `sa<221>s<193>ra'; we then experience ç
the unceasing, everlasting bliss that is our own. We need to move ç
along the path of truth and righteousness to obtain this freedom. ç
We need to practise control of the senses. We need to love the Ultimate ç
Reality, the Innermost Self.
@S10N = THE SCHOOLS OF BHAKTI-VED°NTA
There are differences of approach among various Ved<193>nta traditions ç
about things such as the nature of the Ultimate Reality or the Innermost ç
Self, and, in the same way, the real nature of the j<200>v<193>tmas, ç
the relationship between the two, the nature of the world, the cause ç
for thebondage of the j<200>v<193>tmas, their path towards freedom ç
and the state of freedom. Somehow there is a general feeling that ç
`Ved<193>nta' means the non-dual Ved<193>nta of <185>a<209>kara only. ç
This is not correct. Many teachers who came after <185>a<209>kara, ç
and who  were  great  intellectuals,  great ascetics, great seers ç
and great devotees have subjected the Ved<193>nta of <185>a<209>kara ç
to incisive criticism and established their own Ved<193>nta traditions ç
on sound foundations. Among them, the most noteworthy are R<193>m<193>nuja ç
(<MS>A.<|>D.<D> 1017-1137), Madhva (<MS>A.<|>D.<D> 1238-1317), Nimb<193>rka ç
(12th cent. <MS>A.<|>D.<D>), Vallabha (<MS>A.<|>D.<D> 1473-1531) and ç
<185>r<200> K<216><218><207>a Caitanya (<MS>A.<|>D.<D> 1517-1582). ç
The common premise with which they start is that we can attain freedom ç
only through devotion to God and by the grace of God. Hence we can ç
call these schools as `The schools of Bhakti Ved<193>nta.'
@S10N = THE GROWTH OF THE CONCEPT OF BHAKTI
The feeling of devotion to God is very ancient. We see this in many ç
psalms of prayer in the <184>gveda Sa<221>hit<193> itself. For instance†`He ç
who surrenders himself to Vi<218><207>u who is the cause of the world, ç
the ever new, the lord of wealth, he who sings of  His  sublime  birth  and  actions,  he ç
attains Vi<218><207>u, who is of the nature of consciousness.' (1.156.3)
`O Indra, you are better than my father, you are greater than my brother ç
who cannot protect me. O Vasu, you and my mother are the same. Protect ç
me for my wealth.' (8.1.61)
Though we do not find the term `bhakti' in the ancient Upani<218>ads, ç
what the term means finds expression in many places. Consider the ç
following mantra found in Ka<219>hopani<218>ad (2.23) and Mu<207><195>a-kopani<218>ad ç
(3.24):
`This °tman is not attainable through lectures; He is not attainable ç
through intellect nor through much listening. He whom He chooses, ç
to him alone is (the Self) available. The Self reveals Himself to ç
such a worshipper.'
In another mantra of Ka<219>hopani<218>ad (2.20) also we see the ç
idea of the grace of God.
Especially in the <185>vet<193>·vataropani<218>ad (6.23; 6.18) such ç
terms as bhakti (devotion) and ·ara<207><193>gati (surrender) are ç
directly used:
`He who has devotion par excellence to the Lord and devotion of ç
the same kind to the guru, to that great man the subjects dealt with ç
here become clear; to that great man (the subjects dealt with here) ç
become clear.'
`He who created the four-faced Brahm<193> before the creation of the ç
world, and who enlightened him about the Vedas, He who lights the ç
Self and the intellect, I surrender to Him; I, who desire freedom.'
@SPACE1 = 
In this way, many aspects of devotion like love of God, grace of the ç
Lord, devotion to the guru and surrender, which appear in their nascent ç
form, grow to great heights by the age of the classics and mythologies. ç
Now, of course, abundant devotional literature is available. A few ç
of the most important works in this field may be mentioned at this ç
point: The Bhagavadg<200>t<193> of the Mah<193>bh<193>rata (Bh<200><218>maparva ç
25-42) and N<193>r<193>ya<207><200>ya (<185><193>ntiparva 322-351), ç
Vi<218><207>upur<193><207>a, Bh<193>gavata, <185><193><207><195>ilya ç
Bhaktis<220>tras, N<193>rada Bhaktis<220>tras, N<193>radap<193><210>car<193>tra, ç
Ahirbudhnya Sa<221>hit<193>, Bhaktiras<193>yana, Bhaktiras<193>m<216>ta ç
Sindhu and so on. Devotional literature is also found extensively ç
in the pur<193><207>as and the upapur<193><207>as also.Additionally, ç
plenty of devotional poems and songs are available in Indian languages.
@S10N = THE SCHOOL OF BHAKTI
We may now very broadly present the Bhakti School as enunciated in ç
the works of Bhakti Ved<193>nta. The Supreme Self (Param<193>tman) ç
is without attributes and formless, and at the same time, He has attributes ç
and forms too. These two are the true and equal aspects of the same ç
God; neither of them is superior to the other.
That he has attributes and forms means that he is the great ocean ç
of an infinitude of noble attributes; at the same time, he can manifest ç
himself before his devotees in every form they have adored him (vide ç
Bhagavadg<200>t<193> 4.11; 7.21). As he is omniscient and omnipotent, ç
this is not impossible for him at all. Sugar dolls are all made of ç
the same material†sugar; in the same way, he is the One Principle ç
that embodies itself into R<193>ma, K<216><218><207>a, N<193>r<193>ya<207>a, ç
<185>iva, Dev<200>, Ga<207>apati, Subrah-ma<207>ya and a host of other ç
gods and goddesses. He it is who revealed himself to the sages in ç
these various forms and has brought about the system of worship of ç
these gods and goddesses in this world. As the sea is permanently ç
in the form of ice-rocks in the polar regions, it is he himself who ç
resides in the forms of <185>iva and Vi<218><207>u in such worlds ç
as Kail<193>sa and Vaiku<207><219>ha. Nothing is impossible for him.
That he is attributeless does not mean that he lacks attributes; it ç
only means that he is one whose greatness is not limited or sullied ç
by his qualities. Or it means that he is not graspable by the three ç
gu<207>as of nature. Formless means that he has no particular form. ç
As he is within and outside everything, all forms and shapes are his ç
own. As he is of thenature of pure spirit, he can bestow his grace ç
on the worshippers of the attributeless and formless aspect also.
@SPACE1 = 
This Supreme Self can incarnate in the form of a human being for the ç
establishment of dharma (righteousness) in this world (See Bhagavadg<200>t<193> ç
4.6-9). Then his body†being unlike our bodies created by karma that ç
has already started giving its fruits†is divine, not created by the ç
matrix. He can incarnate even in that small body with his full power; ç
that is why, our worship and adoration of his incarnation would be ç
the same as our worship and adoration of him himself (See Ch<193>ndogyopani<218>ad ç
6.2.2). The reason for the worldliness or bondage of the j<200>v<193>tman ç
(the conditioned Self or soul) is due to the fact that he has no devotion ç
to the Supreme Self; because of this, he has been caught in the grip ç
of the power of illusion (m<193>y<193>) and suffers in the world (See ç
<185><193><207><195>ilya Bhaktis<220>tras 98.). Therefore, only ç
through devotion, because of which the Supreme Self showers grace, ç
can the limited Self attain his liberation. The J<210><193>nam<193>rga ç
(path of knowledge) which, by means of listening about and reflecting ç
on the Self that is beyond the limitation of the body and the senses, ç
and by deep meditation on that Self, helps attain self-realization ç
and liberation, is very difficult. The eightfold yoga (R<193>jayoga) ç
which involves control of the mind and senses also is a hard path. ç
Even the yoga of desireless work is also not easy. The yoga of devotion, ç
which consists of repetition of God's name and singing of songs of ç
his adoration, is the very natural and simple path to liberation in ç
this Kaliyuga (the Dark Age). This is the stand of the Bhakti Schools.
Everyone is eligible for this path of bhakti. Caste, community, gender, ç
education, innate ability* (sa<221>sk<193>ra)†none of these is an ç
impediment to move along thispath (See <185><193><207><195>ilya ç
Bhaktis<220>tras 78.). Guha, Nanda, Cokkamela, Ravid<193>s, Thirupp<193><207><193><202>v<193>r ç
and Ka<207><207>appa the hunter †these people were untouchables. Aj<193>mila, ç
Ratn<193>kara, Tho<207><195>aradippo<195>i °<202>v<193>r†these were ç
sinners. <185>abar<200>, R<193>dh<193>, M<200>r<193> and God<193> ç
were women. Kab<200>r, N<193>nak and Tuk<193>r<193>m had no bookish ç
knowledge. Therefore, what is required is only love for God; this ç
itself will help attain everything.
@SPACE1 = 
Bhakti has been defined in various ways in different texts. N<193>rada ç
P<193><210>car<193>tra says that devotion is that love which is directed ç
towards Vi<218><207>u alone and has no concern for any other thing. ç
Gop<193>lap<220>rvat<193>pan<200> Upani<218>ad mentions that renunciation ç
of this world and the next and total absorption in the Supreme Self ç
indeed is devotion. Bhaktiras<193>yana on the other hand, defines ç
devotion as the way in which the mind after getting purified and melted ç
through spiritual practices  (s<193>dhanas)  flows  incessantly towards ç
the Almighty. The Bh<193>gavata describes the yoga of devotion as ç
one in which the mind flows towards the Lord, as Ga<209>g<193> towards ç
the sea, once it hears the attributes of God. The <185><193><207><195>ilya ç
S<220>tras states that devotion is intense attachment to the Lord.
Bhakti  is  divided  into  different categories in these works: worldly, ç
scriptural (Vedic), and spiritual; physical, vocal and mental; t<193>masik, ç
r<193>jasik and s<193>ttvik and so on.
An important characteristic of the practice of devotion is to count ç
the beads according to a discipline, taking the mantra of God given ç
by a worthy guru through initiation and keeping in mind a form of ç
God which is to one's liking. It need not be emphasized that, as in ç
other kinds of spiritual practices, the followingof moral values, ç
the practice of detachment, the company of noble souls and so on, ç
are absolutely essential for this purpose.
These   bhakti   scriptures   have described the characteristics of ç
a devotee who has realized God. They, to a large extent, resemble ç
the characteristics of theliberated individual described in the Bhagavadg<200>t<193> ç
(See 2.54-72; 12.13-20; 14.21-26).
@S10N = N°RADA BHAKTIS<188>TRAS
Attention may now be given to the author of this book as well as the ç
work itself.
@S8ITAL = N°RADA, THE DIVINE SAGE
N<193>rada, who is well-known as the divine sage, is a very attractive ç
individual who  is  well-reputed  in  our  religious literature. 
The <216><218>is of the psalm `indrasute<218>u some<218>u' in the ç
<184>gveda Sa<221>hit<193> are N<193>rada and Ka<207>va. Again, ç
N<193>rada and Parvata are the <216><218>is to whom the psalms starting ç
with `sukh<193>ya <193> niv<200>data' have been revealed. We meet ç
N<193>rada, the seer of the mantras, in the Atharvaveda (5.19.9; ç
12.4.16) too. In the Bh<220>mavidy<193> of Ch<193>ndogyopani<218>ad, ç
N<193>rada is indicated as a disciple of Sanatkum<193>ra. In pur<193><207>as, ç
of course, he is seen in several places. In the Bh<193>gavata (1.5, ç
23-31; 1.6. 5-36), the story of N<193>rada has appeared in a sufficiently ç
detailed fashion. Born as the son of a ·<220>dra maid in the previous ç
life, as a five year old child he served some ascetics who came to ç
his place for c<193>turm<193>sya (spending the four months of the ç
rainy season in one place) and was initiated with the Lord's name ç
through them. On the death of his mother due to snake bite, he felt ç
sad and wandered about in a forest; there he sat under a tree and ç
had the vision of the Lord <185>r<200>hari in his heart. Then he heard ç
a voice which said to him that, that was all he would be able to get ç
in that life; it asked him to spend the rest of his life in singing ç
the Lord's name and remembering him. Hefollowed the instructions, ç
and, after shedding his body, was born as the spiritual son of Brahm<193> ç
and got the status of the divine sage.
There is a close relationship between Devar<218>i N<193>rada and S<193>maveda ç
as well as music. It was he who authored the musical treatise known ç
as Sa<209>g<200>tamakaranda. He is the inventor of the v<200><207><193> ç
(lute) too. While moving among the three worlds, he assists those ç
who are in distress. He preaches the knowledge of dharma. Sometimes, ç
he is supposed to correct and bring round people by encouraging them ç
to quarrel! It is N<193>rada who urged V<193>lm<200>ki to compose ç
R<193>m<193>ya<207>a and Vy<193>sa to write the Mah<193>bh<193>rata. ç
Again, it is he who preached the Bh<193>gavata-dharma to Prahl<193>da ç
while the latter was still in his mother's womb. <185>r<200> K<216><218><207>a ç
himself praises this great sage wholeheartedly (Mah<193>bh<193>rata†<185><193>ntiparva ç
230).
It is very difficult to determine whether this N<193>rada is a single ç
individual or separate personalities. According to information available ç
from various sources, his character may be described as follows: This ç
great personage reached the most exalted station in life from the ç
lowest, by self-effort as well as the grace of God and attained the ç
position of devar<218>i. Veda-mantras found expression through his ç
pure mind. A great ascetic, he led his life according to the principles ç
that he preached. He moved among the three worlds in order to propagate ç
the Lord'sname and preach devotion to God. Hundreds of people who ç
came in touch with him changed their course to the path of religion ç
and devotion.
@SPACE1 = 
The following are the works thought to be authored by N<193>rada: ç
N<193>rada Bhakti-s<220>tras, N<193>rada Sm<216>ti, N<193>rad<200>ya ç
<185>ik<218><193>, N<193>rada Parivr<193>jakopani<218>ad, N<193>rad<200>ya ç
Pur<193><207>a and N<193>rada P<193><210>car<193>tra.
@S8ITAL = WHAT IS A S<188>TRA?
N<193>rada Bhaktis<220>tras is, like similar books of ancient times, ç
in the form of s<220>tras. The following is the definition of a s<220>tra:
`Those who know s<220>tras consider a s<220>tra as that (a brief sentence) ç
which contains very few letters, gives rise to no doubt (has a clear ç
meaning), includes the essence of all related topics and does not ç
have any superfluous words.'
S<220>tra also means a thread. As various flowers are strung together ç
by a thread to make a garland, or, as a necklace in which several ç
beads are strung together, information in this area of knowledge is ç
collected from various sources and is arranged in the form of a compilation. ç
A s<220>tra that consists of very few letters can be easily memorized. ç
Perhaps because there was no script in those days, or, even if it ç
were there its use was not widespread, works of this kind were composed. ç
Gradually, when writing became more popular, the expert disciples ç
belonging to the particular schools wrote explanations of various ç
kinds like bh<193><218>ya, vy<193>khy<193>na, <219>ik<193>, <219>ippa<207>i ç
and v<216>tti on these s<220>tras. Had these commentaries not been ç
available today, many ancient books would have become a meaningless ç
jargon to us.
@S8ITAL = INTRODUCTION TO N°RADA BHAKTIS<188>TRAS
N<193>rada Bhaktis<220>tras is a brief work consisting only of 84 ç
s<220>tras. It is a collection of N<193>rada's preachings taken from ç
various sources and presenting them in the form of s<220>tras. The ç
author of this work is unknown. According to some scholars, this was ç
composed in 12th century <MS>A. D.<D> But this is not definite. There ç
is no commentary on it in Sanskrit, perhaps because its language is ç
simple, beautiful and direct; if there is any commentary, it is unknown.
This is simpler and easier than the <185><193><207><195>ilya Bhaktis<220>tras. ç
<185>a<207><195>ilya's is, like other philosophical treatises, a work ç
which is written in a terse language and contains arguments, for and ç
against. It does not contain much material that is necessary or useful ç
to the practitioners of devotion. In N<193>rada's work, on the other ç
hand, the main subject under discussion is the practice of devotion. ç
Not merely this, the readers are warned (s<220>s. 74-75) that they ç
should not indulge in disputations!
@S8ITAL = THE SUBJECT AS ENUNCIATED IN THE<R>ç
PHILOSOPHICAL WORKS
We may, in general, present the subjects dealt with in the philosophical ç
schools, especially those of Ved<193>nta, as follows: pram<193><207>a ç
(means of knowledge) and prameya (that which is to be known). Pratyak<218>a, ç
anum<193>na, <193>gama (direct experience, inference and scriptures)†these ç
three are the pram<193><207>as that are generally acceptable.
The   subjects   mentioned   under prameya are: ®·vara, j<200>va, ç
jagat (God, soul and the world), the aim of life, spiritual practices, ç
the nature of liberation and the characteristics of a liberated man.
If this work of N<193>rada is looked at from this viewpoint, we cannot ç
consider it as a work of devotional philosophy. There is nothing of ç
pram<193><207>a here. In the same way, nothing is mentioned about ç
the creation of the world and the nature of j<200>v<193>tman (limited ç
self).
It is with some difficulty that things like nature and characteristics ç
of God can be discovered in it. So too about the objective of life. ç
But there is a great deal of information regarding devotional practices, ç
the nature and features of devotion, and about the ideal devotee. ç
Hence, it willnot be wrong if it is called a treatise on devotional ç
practices. If experienced scholars could blend the philosophical principles ç
of the <185><193><207><195>ilya Bhaktis<220>tras and the spiritual ç
practices as found in the N<193>rada Bhaktis<220>tras and try to ç
compose a work of devotional philosophy, it would be a great service ç
rendered to Bh<193>gavata-dharma (or religion of devotion). Here is ç
an attempt to present the information about this work in a systematic ç
manner.
@S8ITAL = ®<185>VARA
The objective of human life is the realization of God. This God exists ç
in everyone's heart very close to us, the innermost self (s<220>. ç
2). He dislikes pride and egoism. Instead, he wants and likes humility ç
in his devotees (s<220>. 27). He is also called `Bhagav<193>n.' When ç
the devotees listen to his virtues, sing in praise of him and pray ç
to him, he receives these offerings and appears before them and blesses ç
them, because he is full of grace (s<220>s. 37, 38, 40, 80). When ç
once he appears before us, everything will have been achieved. What ç
N<193>rada has preached has also originally come from him (s<220>. ç
84).
@S8ITAL = BHAKTI
The easiest (s<220>. 58) and the best instrument (s<220>s. 25, 26, ç
30, 59, 60) to have God-realization is devotion. This is superior ç
to j<210><193>na (knowledge), yoga (meditation), karma (rituals) and ç
such other spiritual practices. This, indeed, is the result of all ç
these practices.
This bhakti may be divided into two aspects†par<193>bhakti and apar<193>bhakti. ç
Apar<193>-bhakti can be further divided into gau<207><200> bhakti ç
and mukhya bhakti. While par<193>bhakti is the aim, apar<193>bhakti ç
is the means to obtain it.
@S10 = Par<193>bhakti
Par<193>bhakti is the manifestation of the great bliss that results ç
from God- realization. It is of the nature of great love for God. ç
It is full of bliss like nectar; also, those who obtain this attain ç
immortality and liberation (s<220>s. 2, 3). Since this has been described ç
as of the nature of great love, could it not be considered as a form ç
of desire like worldly love? No, it is that which checks and destroys ç
all desires (s<220>. 7). When par<193>bhakti is aroused in the heart, ç
it may find expression inmany ways; for instance†particular attachment ç
to rites of worship, avidity to listen to stories about the Lord, ç
surrendering the fruit of all the work done, and great longing (s<220>. ç
16-19).
@S10 = Apar<193>bhakti
There are two stages in apar<193>bhakti. The initial one is gau<207><200>bhakti ç
and the higher one is mukhyabhakti or prem<193>-bhakti.
@S10 = Gau<207><200>bhakti
Gau<207><200>bhakti is of three kinds: s<193>ttvika, r<193>jasika ç
and t<193>masika; or <193>rta-bhakti, arth<193>rthibhakti and jij<210><193>subhakti ç
(s<220>. 56). Practice of this gau<207><200>bhakti is easy. It is ç
the natural love that residesin the heart and needs to be directed ç
towards the Lord and hence, it needs no proof. By practice, gradually ç
one can attain peace and great bliss (s<220>s. 58-60). This gau<207><200>-bhakti ç
appears in eleven different ways like, for example, to be greatly ç
attached to the noble virtues and greatness of God, to be engaged ç
in His worship and so on.
@S10 = Mukhyabhakti
The practice of gau<207><200>bhakti gradually leads us towards mukhyabhakti. ç
This is otherwise called prem<193>bhakti or ek<193>nta-bhakti. This ç
is the penultimate state of par<193>bhakti, the last but one step. ç
If one gets this, the manifestation of par<193>bhakti will not be ç
far away. This mukhyabhakti or prem<193>bhakti is experienced inside ç
the heart. But it cannot be described in words. This is like a dumb ç
person eating a tasty dish (s<220>s. 51-52). Though this is a rare ç
experience, it finds expression in advanced practitioners (s<220>. ç
53). The words and actions, the feelings and thoughts of that lucky ç
individual who has had this subtle experience, which is beyond the ç
three gu<207>as, devoid of all worldly desires andwhich is continuously ç
growing, are suffused with that love (s<220>s. 54, 55).
@S8ITAL = BHAKTIS°DHANA
Various kinds of instructions and guidance on devotional practices ç
are found aplenty in this work. The practitioner of devotion should ç
always give importance to the scriptures because they have originated ç
from the <216><218>is, munis and great men. If he does not give them ç
prominence, there is a possibility of his slipping off the track of ç
practice (s<220>s. 12, 13).
But the scriptures that the practitioners of devotion should give ç
the greatest importance to, are the devotional scriptures. He should ç
study them and reflect on them in his mind. He should perform those ç
duties preached in them which will help devotion to grow. There is ç
no point in arguing with others in this regard (s<220>s.74-76).
The devotee should renounce those duties†whether worldly or scriptural† ç
which come in the way of his practice and perform the rest with the ç
conviction that they are an offering to God (s<220>s. 8-11). As the ç
body is a valuable instrument to be used in the path of practice, ç
he should protect it well (s<220>. 14).
A great obstruction to spiritual life is the attraction towards sense ç
objects. Hence the devotee has, willy-nilly, to attempt to renounce ç
externally the pleasures born of sense objects and, in his own mind, ç
his attachment to them. An easy solution to this problem is continuous ç
prayer and remembrance as well as the company of great men and, thereby, ç
their grace (s<220>s. 35-42). It is as much necessary to renounce ç
the company of the wicked as cultivate the company of the great. In ç
the company of the wicked, there is every possibility  of  bad  sa<221>sk<193>ras  (mental ç
proclivities) like desire and anger in the devotee's mind rising up ç
(s<220>s. 43-45). Wicked company does not necessarily mean company ç
of wicked persons. The sense objects that help stimulate the mind ç
and give rise to desire, greed, atheism, enmity and anger are also ç
wicked company. We should not even listen to such things (s<220>. ç
63).
@SPACE1 = 
M<193>y<193> or illusion is the captivating power of God; to cross ç
it is very difficult. But, unless it is crossed, there can be no liberation. ç
With this purpose, the devotee should, apart from shunning the company ç
of the wicked and cultivating that of the noble, practise a few more ç
things. Praying to the Lord in solitude, surrendering histhoughts ç
about his security to God Himself, giving up actions born of desires ç
and offering the fruit of the rest of the things he does to God, to ç
free himself from the bondage of the world and so on†these are the ç
other practices (s<220>s. 46-50). When he obtains through these, an ç
unceasing devotion, he will not only cross m<193>y<193> with the grace ç
of God, but achieve the power to help others to cross it too.
The  devotee  surrenders  himself totally to the Lord. Hence he should ç
not bother about this world or the next. This does not mean that he ç
should give upworldly and scripturally prescribed actions. While ç
engaging himself in these actions, if he offers their fruit to the ç
Supreme Self, devotion gradually gets ripened (s<220>s. 61-62).
Desire, anger and such other passions are great obstacles on the path ç
of spiritual practice. It is, indeed, very arduous to fight them directly ç
and win. Hence, N<193>rada suggests a solution that is easy and shrewd, ç
to direct them towards the Lord Himself! The gopis turned their cravings ç
towards K<216><218><207>a and killed them; in the same way, we too ç
could destroy them (s<220>. 64).
@SPACE1 = 
The devotee who is engaged in this internal battle should incessantly ç
be praying to the Lord without wasting even a moment of his time. ç
As an aid and complement to this, he should practise non-violence, ç
truth, mercy and such other noble virtues (s<220>s. 77-79). If he ç
continues to pray to the Supreme Self in this way, the latter will ç
appear before the devotee very quickly and grant him His experience, ç
bliss and liberation.
@S8ITAL = THE CHARACTERISTICS OF A<R>ç
LIBERATED DEVOTEE
The man who attains liberation (i.e., par<193>bhakti) is a siddha-puru<218>a. ç
As he is ever-contented, he doesn't crave for anything. As he is totally ç
blissful, there is no trace of sorrow in him. As he sees his beloved ç
Supreme Self everywhere, he does not hate anyone. As, again, he is ç
contented always, he does not need to engage himself in any action ç
to satisfy his desires. Sometimes, he becomes rapt in par<193>bhakti ç
and like a bee that has sucked honey a little too much, he stands ç
lost in himself. When he is conscious, he experiences that sublime ç
love and sees the Lord everywhere. He listens only to things about ç
Him, he talks and thinks about Him alone. When he meets other devotees, ç
all of them converse about God alone, shedding blissful tears and ç
thus spend their time (s<220>.68). As he has surrendered to God everything ç
that belongs to him even afterhe has experienced par<193>bhakti, ç
this devotee will continue to engage himself in worldly and religious ç
activities in order to guide others. Scriptures and actions become ç
holier because of this (s<220>s. 4-6; 55, 61, 62, 68).
These devotees do not recognize anydifferences among themselves as ç
they belong to the `caste' of the devotees; that is, the `caste' of ç
God. They do not recognize differences even with others (s<220>. 72). ç
Such great devotees sanctify their families. They make holy pilgrim ç
centres holier when they visit them; not merely that, they make the ç
whole earth more sacred. Looking at them, manes and gods dance with ç
glee (s<220>s. 69-71).
@S10N = CONCLUSION
N<193>rada has not preached this devotional scripture merely with ç
his intellectual power. He obtained it directly from <185>iva-Mah<193>deva ç
Himself. There are very great men like Sanatkum<193>ra, Vy<193>sa, ç
<185>uka, <185><193><207><195>ilya, Bali, Hanum<193>n and Vibh<200><218>a<207>a ç
who belong to this great Bhakti-tradition. Forever they live in God. ç
Hence, with one mind they have spread broadcast their preachings, ç
unmindful of the frivolous criticism levelled against them by uncultured ç
people. Those who have complete faith and trust in this devotional ç
work and practise what is preached in it, will definitely attain the ç
Supreme Self dearest to their hearts.
@NT = N<193>rada-parivr<193>jaka-Upani<218>ad
@S10 = INTRODUCTION
Though classed among the minor Upani<218>ads, the N<193>radaparivr<193>jaka ç
Upani<218>ad†assigned to the Atharva Veda †is a fairly big work ç
dealing exclusively with sa<221>ny<193>sa or p<193>rivr<193>jya (monastic ç
life). It is one of the seventeen such works.
@EMERGENCY = There is only one Sanskrit commentary, by Upani<218>ad-brahmayogin.
It is divided into nine `upade·as' or chapters containing the teaching. ç
These upade·as comprise both verses in the anu<218><219>ubh metre ç
and sections in prose, the total being 298.
@EMERGENCY = A brief summary of the text may now be attempted here.
@S10 = First Chapter
The Upani<218>ad begins with the sages <185>aunaka and others approaching ç
the devar<218>i (divine-sage) N<193>rada and requesting him to explain ç
the means to mukti or salvation. In reply N<193>rada states that it ç
is the paramaha<221>sa-sa<221>ny<193>sin†the monk of the highest order†who ç
is constantly meditating on his own Self, that attains salvation. ç
However, before attaining this status, he has to undergo several preliminary ç
disciplines that include the study of the Vedas and other branches ç
oflearning form a competent teacher, marriage and duly discharging ç
the duties of the householder's life, acquiring the four means of ç
spiritual life (= s<193>dhanacatu<218><219>aya), renouncing the world ç
and taking to the life of the sa<221>ny<193>sin.
@S10 = Second Chapter
Then the sages ask him about the formalities and procedure needed ç
in adopting sa<221>ny<193>sa. Thinking that it is best to get the ç
answer to this query from Brahm<193> (the four-faced creator of the ç
world) himself, N<193>rada takes all these sages to Satyaloka (the ç
abode of Brahm<193>). After respectfully offering salutations to him, ç
N<193>rada requests him to explain the true nature of p<193>rivr<193>jya ç
or sa<221>ny<193>sa.
In reply, Brahm<193> states that a person should first undergo the ç
upanayana ceremony and study the Vedas as also acquire the knowledge ç
of other sciences needed to live in the world, for twelve years. For ç
the next twenty five years, he should live as a householder discharging ç
all the duties of that life. The subsequent twenty five years should ç
be spent as a v<193>naprastha with all the disciplines associated ç
with it. Then he should renounce everything and go away as a mendicant, ç
burning up of all desires and cultivating the four-fold discipline ç
of Ved<193>nta being the precondition to this stage of life. (See ç
<MS>S°DHANA-CATU<186><187>AYA.<D>)
@S10 = Third Chapter
In answer to the question by N<193>rada, as to who is fit to be initiated ç
into sa<221>ny<193>sa, Brahm<193> first rules out the following persons ç
as unfit even though they may be endowed with the spirit of renunciation: ç
eunuchs, sinners, physically disabled persons, libertines, children, ç
those who do not accept the authority of the Vedas and so on.
Then he mentions that a person who is about to die (= <193>tura) can ç
take sa<221>ny<193>sa if he has a strong desire, just by uttering ç
the prai<218>amantra (o<221> bh<220><199> sa<221>nyastam may<193> ç
etc.). In his case there is no need for the performance of the usual ç
rites associated with it.
After declaring that only the person fired with the spirit of intense ç
renunciation is fit for sa<221>ny<193>sa, he goes on to narrate vidvat-sa<221>ny<193>sa ç
(sa<221>ny<193>sa taken by a man of spiritual illumination).
A person of spiritual illumination generally has the following characteristics: ç
knowledge of Brahman; desirelessness and detachment; equanimity under ç
all circumstances; internal and external purity; peace of mind; devotion ç
to truth; contentment; absence of greed and hypocrisy; sinlessness.
Such a person is eminently fitted to become a vidvat-sa<221>ny<193>sin.
He is expected to possess only a minimum number of articles like kaup<200>na ç
(loin cloth), kanth<193> (cotton-rug made of cloth-pieces), da<207><195>a ç
(staff) and kama<207><195>alu (waterpot) needed for the maintenance ç
of the body. He should always move about all alone. Violation of these ç
rules will cast him into hell.
Next, a strict code of conduct is prescribed for the yati or the monk. ç
Some of them are: eschewing the ari<218>a<195>vargas (the six enemies ç
like lust, anger and soon); conquest of the senses; control of speech ç
and mind; avoiding honour and welcoming dishonour by the society; ç
forbearance; taking delight in the Self; studying the Upani<218>ads ç
and allied works; constant effort to conquer all attachment to the ç
physical body; living alone under trees and deserted places; not mixing ç
with others or talking to them about worldly matters: avoiding tasty ç
food.
P<193>rivr<193>jya or sa<221>ny<193>sa can be resorted to in the usual ç
order of the four <193>·ramas†brahmacarya, g<193>rhasthya, v<193>na-prastha ç
and sa<221>ny<193>sa†or from any stage, intense spirit of renunciation ç
being the only criterion.
Now, N<193>rada asks Brahm<193> whether the sa<221>ny<193>sin who ç
has no ·ikh<193> (tuft of hair) and yaj<210>opav<200>ta is a br<193>hma<207>a ç
at all, since they are essential for him. Brahm<193> replies that ç
for such a sa<221>ny<193>sin, Brahman (the Absolute) (or the constant ç
experience of Brahman) is everything, including all these insignias ç
of a br<193>hma<207>a.
@SPACE1 = 
The last part describes the state of an avadh<220>ta (the highest ç
sa<221>ny<193>sin who has shaken off all bonds and bondages) in a ç
vivid manner. Much of this description is a repetition of the earlier ç
statements. The sages who had attained this state are also mentioned. ç
They are: <185>vetaketu, <184>bhu, Nid<193>gha, <184><218>abha, Durv<193>sa, ç
Sa<221>vartaka, Datt<193>treya and Raivataka.
@S10 = Fourth Chapter
This chapter deals with three topics: the detailed code of conduct ç
prescribed for a normal sa<221>ny<193>sin; rites connected with taking ç
formal sa<221>ny<193>sa; and, some more details regarding the vidvat-sa<221>ny<193>sin ç
and the vividi<218><193>-sa<221>ny<193>sin (one who takes sa<221>ny<193>sa ç
as a mode of s<193>dhan<193> for mok<218>a or liberation).
Some of the steps involved in taking kramasa<221>ny<193>sa†sa<221>ny<193>sa ç
in the usual order of the four <193>·ramas† are as follows: pr<193>ya·cittas ç
(expiations for sins that might have been committed unknowingly); ç
·r<193>ddhas (ceremonies for satisfying the gods, sages, manes and ç
others); shaving the head and the face; sandhy<193> ritual and G<193>yatr<200>japa ç
(1000 times); final offerings into the Vedic fires if they had been ç
maintained; disposing off the Vedic fires after performing viraj<193>homa ç
(a special fire ritual, obligatory for those taking sa<221>ny<193>sa);  uttering  the  prai<218>amantra ç
(signifying total renunciation, using the vy<193>h<216>tis of G<193>yatr<200>mantra); ç
giving up the ·ikh<193> (tuft of hair) and the yaj<210>opav<200>ta ç
(sacred thread); approaching the guru and receiving the gerua cloth ç
as also the mah<193>- v<193>kya (See <MS>MAH°V°KYAS.<D>); retiring ç
from the world and going away as a mendicant.
This is followed by a short description of the vidvatsa<221>ny<193>sin, ç
who approaches a guru, receives the Pra<207>ava (Om) and the mah<193>v<193>kya. ç
Then he goes about completely naked, sustaining the body only on fruits ç
and water, ever enjoying the bliss of the <193>tman in his heart.
As regards the vividi<218><193>sa<221>ny<193>sin, more details are ç
provided as to how he has to formally accept it. Some of them are: ç
approaching a competent guru for sa<221>ny<193>sa; receiving the various ç
articles of sa<221>ny<193>sa like da<207><195>a (tall staff), kaup<200>na ç
(loin cloth), ·<193><219><200> (covering cloth) and kama<207><195>alu ç
(waterpot).
They should be received with appropriate Vedic mantras. Then he should ç
live his life as a sa<221>ny<193>sin as per the rules given in the ç
dharma·<193>stras.
@SPACE = 
@S10 = Fifth Chapter
@SPACE = 
In reply to further questioning by N<193>rada,  sa<221>ny<193>sa  of  four  types  is ç
described by the Pit<193>maha. They are: vair<193>gya-sa<221>ny<193>sa, ç
j<210><193>nasa<221>ny<193>sa, j<210><193>navair<193>gya-sa<221>ny<193>sa ç
and karma-sa<221>ny<193>sa.
One who renounces the world due to vair<193>gya (intense spirit of ç
renunciation) brought about by the pu<207>ya or the spiritual merit ç
of previous lives is a vair<193>gya-sa<221>ny<193>sin.
If a person embraces sa<221>ny<193>sa after realising ( = j<210><193>na ç
or knowledge) the true nature of the world and worldly life (as evanescent) ç
he is called a j<210><193>nasa<221>ny<193>sin.
When a combination of these two, brought about by the experiences ç
of the first three <193>·ramas, induces the person to take to sa<221>ny<193>sa, ç
he is a j<210><193>na-vair<193>gya- sa<221>ny<193>sin.
One who accepts the fourth <193>·rama (= sa<221>ny<193>sa) as a matter ç
of course, even though there is no vair<193>gya, is known as a karmasa<221>ny<193>sin.
This is then followed by a classification of the sa<221>ny<193>sins ç
into six varieties. They are: ku<219><200>caka, bah<220>daka, ha<221>sa, ç
parama-ha<221>sa, tur<200>y<193>t<200>ta and avadh<220>ta.
The kut<200>caka has the ·ikh<193> and the yaj<210>opav<200>ta intact. ç
The da<207><195>a (staff) and kama<207><195>alu (waterpot) are the ç
insignia he keeps. Kaup<200>na (loin-cloth) and kanth<193> (rug) are ç
his possessions. He serves his parents and teachers. He takes his ç
food from one and the same place (usually his own house). He also ç
wears the religious marks (pu<207><195>ra) on his forehead.
The bah<220>daka has all the characteristics of the ku<219><200>caka, ç
the only difference being that he begs his food from anumber of houses†this ç
is called m<193>dhukar<200>†instead of always taking it from one house.
The ha<221>sa has matted hair, applies tripu<207><195>ra (religious ç
mark) on his forehead, wears only a kaup<200>na and gets his bhik<218><193> ç
or alms from wherever it is got.
The paramaha<221>sa does not keep the ·ikh<193> and the yaj<210>opav<200>ta, ç
wears only a kaup<200>na, a ·<193><219><200> (upper cloth) and a da<207><195>a, ç
applies bhasma or sacred ash all over his body, begs for food from ç
a maximum of five houses (and that too at night only), eats from his ç
cupped hands (without using any vessel), and practises intense renunciation.
The tur<200>y<193>t<200>ta is naked, lives on any food got without ç
asking, or, may beg from three houses and treats his body as if it ç
is a corpse, since he is not conscious of it.
The avadh<220>ta, being above all rules and regulations, maintains ç
his body by alms from anyone who cares to give and is always immersed ç
in his own <193>tman or the Self.
@SPACE1 = 
If a person on the verge of (imminent) death takes <193>turasa<221>ny<193>sa ç
but survives later, he has to take formal sa<221>ny<193>sa in the ç
usual, traditional way.
Pit<193>maha (Brahm<193>) then goes on to describe the procedural ç
details of taking sa<221>ny<193>sa by these six kinds of ascetics.
Other topics touched upon in this section are: modes of accepting ç
bhik<218><193>; worlds attained by these ascetics after death; meditation ç
on Brahman; evil effects of failure to observe the monastic disciplines; ç
rules concerning begging for food and living places; details of conduct ç
concerning self-control; giving up all actions save those needed for ç
maintaining the body alive; extreme forbearance; and, trying to see ç
God in all beings.
@S10 = Sixth Chapter
N<193>rada now asks Brahm<193> how the vidvatsa<221>ny<193>sin, who ç
is constantly meditating on his own essential nature (as <193>tman), ç
becomes liberated. What is the up<193>ya or the means he adopts?
In answer, Brahm<193> states, in a highly symbolical language, how ç
the vidvat-sa<221>ny<193>sin looks upon his own body. For instance, ç
j<210><193>na (knowledge) is his body. Vair<193>gya (renunciation) ç
is the life-force. <185><193>nti (peace) and d<193>nti (self control) ç
are his eyes. Manas (mind is his face and so on.
Incidentally, how the j<200>va (the individual soul) moves about in ç
the various petals of the heart (the an<193>hatacakra) andthe results ç
he experiences are also described.
How to attain the tur<200>y<193>t<200>ta state (the state beyond the ç
fourth, of the j<200>v<193>tman or the individual soul) is the subject-matter ç
of the next section. The japa of the ha<221>samantra (See <MS>BRAHMA-VIDY° ç
UPANI<186>AD<D> and <MS>HA<189>SA.<D>) will ultimately lead to it. ç
Being bereft of body- consciousness he becomes Brahman.
Then comes a long description of the way, a sa<221>ny<193>sin should ç
live, not violating the norms of dharma (even though he may be a j<200>vanmukta), ç
to set an example before the world. Some of the rules mentioned here ç
are: conquest of all sense-organs; light food; constant meditation ç
on Brahman; not taking part in rituals; going for alms to the houses ç
after the members of the family have finished their food and so on.
However, it is also stated that such a vidvatsa<221>ny<193>sin is ç
beyond the realms of var<207>a and <193>·rama, and hence known as ç
`ativar<207><193>·ramin'.
This is followed once again, by the rules an aspirant for sa<221>ny<193>sa ç
and mok<218>a (a vividi<218><193>sa<221>ny<193>sin) is expected to ç
follow. Preliminary disciplines to be practised, approaching a competent ç
guru (teacher) and sincerely serving him for at least a year, after ç
which formal vows of sa<221>ny<193>sa may be taken from him are also ç
described. Some more general rules of conduct, applicable to him, ç
are given once again. The gist of these is self-control and renunciation ç
of all actions.
@S10 = Seventh Chapter
Being asked by N<193>rada once again about the rules a yati (sa<221>ny<193>sin) ç
has to follow in his life, Pit<193>maha expatiates on it. Summarised ç
briefly the rules are as follows: itinerant way of life for eight ç
months and staying in one place for four months during the rainy season, ç
but always alone; avoiding all actions that may harm other living ç
beings; accepting very simple food as alms, just to sustain the body; ç
eschewing all items of luxury as poison; shunning the places and persons ç
connected with the earlier (pre-monastic) life; burning up the six ç
passions (See <MS>ARI<186>A£VARGA.<D>); trying to see or visualise ç
his own <193>tman (the Self) in everyone and everything; meditating ç
on his own <193>tman or Self always, until the body falls after the ç
exhaustion of pr<193>rabdhakarma.
In the next ten paragraphs, some more directions regarding the life-style ç
of the six kinds of monks already mentioned, are dealt with. They ç
are: sn<193>na (bath); pu<207><195>ra (wearing of religious marks); ç
k<218>aura (shaving the head and beard); anna (food); ·<193><219><200> ç
(covering cloth); religious rites like arcana (worship); mantrajapa ç
(repetition of divine names or Vedic passages); repeating the Pra<207>ava ç
(Om); ·rava<207>a, manana  and  nididhy<193>sana  (hearing, reflecting ç
and meditating).
@S10 = Eighth Chapter
N<193>rada requests Brahm<193> to enlighten him about the sa<221>s<193>rat<193>raka, ç
the mantra that  takes  one  across  the  ocean  of transmigratory ç
existence. Consenting to do so. Brahm<193> talks in detail on the ç
Pra<207>ava or O<209>k<193>ra in all its aspects. Eight forms of Pra<207>ava ç
such as Anta<199>pra<207>ava, Vy<193>vah<193>rikapra<207>ava, °r<218>apra<207>ava ç
and so on, are described in great detail.
This is then followed by a method of meditation on Brahman who is ç
sarv<193>dh<193>ra (support of all), jyoti (light), sarve·vara (lord ç
of all), personification of all gods and scriptures.
The section ends with the description of the four states of consciousness ç
and the <193>tman associated with them, as found in the M<193><207><195><220>kya ç
Upani<218>ad.
@S10 = Ninth Chapter
This chapter describes the nature of Brahman, quoting verses from ç
some of the major Upani<218>ads, followed by the eulogy of realising ç
it. It is also declared that only a person of the highest moral calibre ç
can realise it.
One  who  knows  Brahman  as described here, will be liberated (soon ç
after the body falls).
The last part describes once again the parivr<193><195> (= sa<221>ny<193>sin) ç
who is a j<200>van- mukta (liberated even while living) and that he ç
does not return to mundane existence again.
@S10 = EPILOGUE
This is an important Upani<218>ad dealing with sa<221>ny<193>sa exhaustively ç
and is almost like a textbook for the sa<221>ny<193>sins.
@NT = N<193>radasm<216>ti
Whereas the Vedas and the Upa-ni<218>ads give the basic ideas of philosophy ç
and, occasionally, some instructions concerning personal ethics or ç
social conduct, the task of elaborating the latter has been fulfilled ç
admirably by the pur<193><207>as, sm<216>tis, dharma·<193>stras and ç
nibandhas (digests).
One of the more ancient sm<216>tis is the N<193>radasm<216>ti. Though ç
N<193>rada is a familiar figure in the mythological literature, the ç
author of this treatise may not be that sage. The work as available ç
now in print comprising 1028 verses has been assigned to the period ç
<MS>A.<|>D.<D> 100-300.
There are two commentaries on this work: one by Asah<193>ya (circa ç
<MS>A.<|>D.<D> 600-750) which is incomplete and the other by Bhavasv<193>min ç
(circa <MS>A.<|>D.<D> 700-1000).
N<193>radasm<216>ti follows the Manusm<216>ti closely.  However,  it  contains  greater ç
details and is arranged in a more systematic way.
Some of the subjects dealt with in this work may be listed as follows: ç
<216><207><193>d<193>na (recovery of debts); upanidhi (deposits and ç
lending);   datt<193>prad<193>nika   (gifts   and resumption thereof); ç
abhyupetya-a·u·r<220><218><193> (breach of contract of service); asv<193>mi- ç
vikraya (sale without ownership); samayasya-anap<193>-karma (violations ç
of the conventions  of  guilds);  s<200>m<193>bandha (settlement of ç
boundaries); d<193>yabh<193>ga (partition and inheritance); str<200>pu<221>sayoga ç
(marital relations); crimes and punishment. It is seen that almost ç
all these items belong to the field of vyavah<193>ra (social conduct).
N<193>rada, differing from Manu, allows niyoga (levirate), remarriage ç
of widows and gambling (but controlled by the State).
Later writers like Vi·var<220>pa (circa <MS>A.D.<D>750-1000), Medh<193>tithi ç
(<MS>A.<|>D.<D> 825-900) and Asah<193>ya have regarded N<193>radasm<216>ti ç
as an authoritative work.
@NT = N<193>rad<200>ya-pur<193><207>a
Though the Hindu pur<193><207>as are sometimes described as `Cock-and-bull-stories', ç
their main purpose is to inform and inspire the common masses to better ç
and ethically purer ways of life, both at the personal and at the ç
social levels.
There are two pur<193><207>as†both belonging to the Upapur<193><207>a ç
group†attributed to the divine sage N<193>rada: The B<216>han-n<193>rad<200>yapur<193><207>a ç
and the N<193>rad<200>yapur<193><207>a (also spelt as N<193>radapur<193><207>a).
The N<193>rad<200>yapur<193><207>a as available now, may not be ç
the same as the one referred to in the Matsya, the Skanda or the ç
Agni pur<193><207>as. Scholars generally assign it to the period ç
<MS>A.<|>D.<D> 700-1000. The first part (p<220>rvabh<193>ga) has 125 ç
chapters in four p<193>das or quarters. The second part (uttarabh<193>ga) ç
has 82 chapters.
The first part is sometimes identified with the B<216>han-n<193>rad<200>ya-pur<193><207>a.
The contents in brief are as follows: praise of Vi<218><207>u, and ç
bhakti or devotion; geography of Bh<193>ratavar<218>a (India); story ç
of Bhag<200>ratha bringing the Ga<209>g<193> river from heaven and ç
its greatness; a few vratas; var<207><193>·ramadharmas; p<193>takas ç
or sins; sad<193>c<193>ra or good conduct; ·r<193>ddha or obsequial ç
ceremonies.
The story of the king Rukm<193><209>gada who was a great devotee of ç
Vi<218><207>u and who meticulously observed the ek<193>da·<200> vrata ç
hasreceived a detailed treatment. (See <MS>RUKM°<177>GADA<D> for ç
details.)
See also <MS>B<184>HAN-N°RAD®YA-PUR°ØA.
@NT = Narahari T<200>rtha
@N1 = (<MS>A.<|>D.<D> 1250-1335)
Among the four chief disciples of Madhv<193>c<193>rya (<MS>A.<|>D.<D> ç
1238-1317), Narahari T<200>rtha was the third. Known as Sv<193>mi- ç
·<193>stri in his premonastic days, he was an officer of the kings ç
of Kali<209>ga (Orissa) of the Gajapati Dynasty. When Madhv<193>c<193>rya ç
visited the kingdom, it was Sv<193>mi·<193>stri† being the most learned ç
among the court pundits†who had to face him in philosoph-ical disputation. ç
Being vanquished by him, Sv<193>mi·<193>stri, as per the original ç
covenant, renounced the world and became a sa<221>-ny<193>sin-disciple ç
of Madhv<193>c<193>rya, assuming the monastic name `Narahari T<200>rtha.'
He stayed back in his place, obeying the injunctions of his guru. ç
When the royal dynasty was about to collapse due to the death of the ç
young king and the kingdom plunge into chaos, he assumed the reins ç
of the king and ruled very efficiently until the heir-apparent came ç
of age, to take over.
As per the desire of Madhv<193>c<193>rya, he secured the beautiful ç
images of S<200>t<193> and R<193>ma from the new king and returned ç
to U<195>upi to join his preceptor. It is said that Madhv<193>c<193>rya ç
worshipped the images for 80 days and then bequeathed the same to ç
Padman<193>bha T<200>rtha, the first of the four disciples. Narahari ç
T<200>rtha became the abbot after the demise of Padman<193>bha T<200>rtha, ç
in <MS>A.<|>D.<D> 1324.
Narahari T<200>rtha was a great scholar in Sanskrit and Dvaita Ved<193>nta ç
as also a poet in Kannada language. His songs in Kannada have the ç
a<209>kita (assumed title) `Raghupati,' though, sometimes, he has ç
used his real name itself (`N<216>hari,' `Narahari'). He wrote a <219>ippa<207><200> ç
(brief notes) on the Brahmas<220>trabh<193><218>ya of Madhv<193>c<193>rya. ç
He is reputed to have written an independent commentary on the Bhagavadg<200>t<193>. ç
Some of the other works referred  to  by  other  writers  as  his, ç
are: Karmanir<207>aya, Tattvadyota and Kha<207><195>anatraya.
@NT = naraka
@N1 = (`a world which is below;' `a world without joy')
It may appear strange†but it is true †that the humankind has, throughout ç
its chequered history on this planet of ours, believed in a Super ç
Power (call it `God' if you like) that rewards the good and punishes ç
the wicked. The good are those that faithfully follow the Law as given ç
in the Scriptures whereas the wicked are the transgressors. If the ç
good go to heaven to enjoy the fruits of their good deeds, the wicked ç
go to hell to pay through their nose, for all their heinous crimes, ç
by intense suffering.
In the <184>gveda (10.14.2) Yama and Varu<207>a are mentioned as ç
the deities supervising over the destinies of human beings after death.
The concepts of svarga (heaven) and naraka (hell) are often found ç
in the Upani<218>ads. For instance, svarga or svarga-loka is mentioned ç
in the following Upani<218>ads: Aitareya 4.6; B<216>had<193>ra<207>yaka ç
4.4.8; Ch<193>ndogya 3.13.6; Ka<219>ha 1.12.
Of course, here, `svarga' may not mean only a heaven from where there ç
is a fall after exhausting religious merit. It may, sometimes, mean ç
liberation also as in B<216>had<193>ra<207>yaka 4.4.8.
The word `naraka' has been defined as `going below' or `a place where ç
there is not the slightest trace of joy'.
The Nirukta (See <MS>NIRUKTA<D>.) quotes a part of a verse from ç
the <184>gveda (khila) (10.106.1) wherein the word `naraka' is ç
mentioned. By the time of the sm<216>tis and dharma·<193>stras the ç
concept was fairly well-developed.
By summing up the various ideas about naraka or hell, it can be said ç
that Yama (the god of death) rules from his capital city called `Sa<221>yaman<200>' ç
which is grand and beautiful. A part of his capital houses the various ç
narakas (torture-chambers?) to where the condemned sinners are sent.
@SPACE1 = 
The number of narakas ranges from seven to twenty-one. Later pur<193><207>as ç
have raised this number to 140 or even more!
