Some of the narakas are: Andhat<193>-misra (blinding darkness); T<193>misra ç
(darkness); Raurava (abounding in paths with heated surfaces); Mah<193>v<200>c<200> ç
(where one is submerged in surging waves); Tapana (as hot as fire); ç
K<193>kola (where one is preyed upon by crows); Loha·a<209>ku (piercing ç
one with iron nails); Asipatravana (where one is cut up by many sword ç
blades) and Kumbh<200>p<193>ka (putting the sinners into big pots ç
of boiling oil).
Special bodies are provided to the sinners (after death here) in narakas, ç
which cause terrible suffering but do not get destroyed!
See also <MS>P°T°LA<D> and <MS>SVARGA.
@NT = Narak<193>sura
He is said to have been born out of a drop of sweat that fell on the ç
earth (or Bh<220>dev<200>) from the body of Var<193>ha (Boar- incarnation ç
of Vi<218><207>u). Hence he was known as Bhaum<193>sura also.
Due to the prayer of Bh<220>dev<200>, Vi<218><207>u gave Narak<193>sura, ç
the weapon called Vai<218><207>av<193>stra. Becoming invincible by ç
the possession of this formidable weapon, Narak<193>sura became a ç
terror to the whole world. He took away the royal umbrella of Indra, ç
the ear-rings of Aditi (Indra's mother) as also many other things ç
from heaven.
When Indra placed his problems before <185>r<200> K<216><218><207>a ç
and begged for his intervention, the latter invaded Pr<193>g-jyoti<218>apura, ç
the capital of Narak<193>sura and killed him as also his chief assistant ç
Mur<193>sura. He then restored all the valuable things that the demon ç
had looted, to their rightful owners.
At the request of Bh<220>midev<200>, he gave protection to Bhagadatta, ç
son of Narak<193>sura, and crowned him as the king.
The day on which Narak<193>sura was killed, is observed as the Narakacaturda·<200> ç
festival.
@NT = Nara-N<193>r<193>ya<207>a
After the purpose of Narasi<221>ha-avat<193>ra was accomplished, Narasi<221>ha ç
split himself into two, the lion part becoming the sage N<193>r<193>ya<207>a ç
and the human part the sage Nara. Nara and N<193>r<193>ya<207>a then ç
retired to Badarik<193>·rama for performing austerities. When Indra ç
tried to seduce them through celestial nymphs, N<193>r<193>ya<207>a ç
produced the nymph <188>rva·<200> from his thigh (<220>ru = thigh) ç
who was more beautiful than all of them put together.
According to another version, these sages were sons of Dharma and ç
Ahi<221>s<193>. They performed severe austerities andsuccessfully ç
vanquished the demon Sahasrakavaca (one who has a thousand armours).
These sages were reborn later as <185>r<200>K<216><218><207>a and ç
Arjuna.
This story has an important lesson for us. Every one of us is a mixture ç
of the human and the divine elements. The anti-human and the anti-divine ç
demon is ever attempting to seduce us with his thousand wiles. To ç
successfully vanquish him,  we  need  to  perform  Tapas  or austerity.
Nara-N<193>r<193>ya<207>a is represented either as a single person ç
or as two persons. In the former case the icon may have twoor four ç
arms carrying the japam<193>l<193> (rosary) or the usual emblems of ç
Lord Vi<218><207>u. In the latter case, Nara may be shown as having ç
two heads and two arms and wearing  the  deer  skin.  N<193>r<193>ya<207>a  is ç
depicted with the usual four arms carrying the emblems ·a<209>kha, ç
cakra, padma and japam<193>l<193>. 
@NT = n<193>r<193>·a<221>·<200>g<193>th<193>
See <MS>G°TH°.<D>
@NT = Narasi<221>ha
@N1 = (`Man-lion [incarnation]')
See <MS>AVAT°RA<D> and <MS>DA<185>°VAT°RAS.<D>
Independent shrines of Narasi<221>ha are quite common in South India, ç
whereas he has small shrines or niches in the temples of Vi<218><207>u ç
in the North.
Iconographic descriptions of the deity are <|>provided<|>in <|>several<|><193>gama ç
<|>treatises like Vihagendrasa<221>hit<193>, P<193>dma-sa<221>hit<193>, ç
®·varasa<221>hit<193>, Par<193>·arasa<221>hit<193> and S<193>ttvatasa<221>hit<193>.
The forms delineated are too numerous to mention. Some of these are: ç
<193>s<200>na (seated); sth<193>naka (standing); y<193>naka (striding); ç
ugra (ferocious); varada (boon-giving); Lak<218>m<200>narasi<221>ha ç
(in the company of Lak<218>m<200>); Yog<193>narasi<221>ha (seated ç
in yoga); girija (emerging from a cave in a mountain) and so on.
The hands of the image may be two or four. In the latter case, the ç
two back-hands hold the ·a<209>kha (conch) and cakra (discus), the ç
other two being shownin the act of killing the demon Hira<207>yaka·ipu. ç
An entire Upani<218>ad†the N<216>si<221>hat<193>pin<200>, in two ç
parts†is devoted to his worship and meditation.
There are several authors of dharma-·<193>stra literature by this ç
name, but not much is known of them.
Some of them are: Narasi<221>ha, the author of °pastamba-g<216>hyas<220>tra-k<193>rik<193>- ç
v<216>tti (<MS>A.<|>D.<D> 1614); Narasi<221>hadeva, author of Durg<193>bhaktitara<209>gi<207><200> ç
(<MS>A.<|>D.<D> 1425-50); Narasi<221>h<%22>a<%0>V<193>japeyin, author ç
of Nity<193>c<193>ra- prad<200>pa and Narasi<221>ha Somay<193>jin,  author ç
of Vi<218><207>uprati<218><219>h<193>vidhidarpa<207>a.
Many of these works are still in the manuscript form and not printed.
@NT = Narasi<221>hapur<193><207>a
Hindu mythological literature, through the pur<193><207>as, the upapur<193><207>as ç
and allied works, has successfully kept up the fire and spirit of ç
Hinduism in the hearts of its adherents.
Among the upapur<193><207>as, the Nara-si<221>hapur<193><207>a†also ç
spelt as N<216>si<221>ha-pur<193><207>a†is considered not only as ç
a fairly ancient one but also important, especially from the standpoint ç
of the P<193><210>car<193>tra school of the Bh<193>gavata cult.
The original pur<193><207>a is supposed to have had 18,000 verses, ç
though the present printed version contains only 3400 verses spread ç
over 68 chapters. It is quite likely that the original might have ç
been lost and later compilers might have redacted it from the available ç
material since many of its verses have been quoted by several writers ç
of dharma·<193>stras. The extant edition might be assigned to the ç
period <MS>A.<|>D.<D> 900, though some scholars push it back to <MS>A.<|>D.<D> ç
400-500.
This pur<193><207>a, as its very name suggests, glorifies Narasi<221>ha ç
as a form of Vi<218><207>u. He is identical with N<193>r<193>ya<207>a, ç
the eternal Brahman.
Apart from the usual topics commonly dealt with in the pur<193><207>as, ç
it also dealswith the practice of yoga, worship of Narasi<221>ha, ç
genealogical lists of kings and some stories like the birth of A·vin<200>-kum<193>ras. ç
The chapters 57 to 61 are found to appear as an independent work bearing ç
the title H<193>r<200>tasa<221>hit<193> or Laghuh<193>r<200>ta-sm<216>ti.
@NT = N<193>r<193>ya<207>a
@N1 = (`One whose abode is<R>ç
[the primeval] waters')
See <MS>VI<186>ØU.<D>
@NT = n<193>r<193>ya<207>abali
@N1 = (`offering to [please] <R>ç
N<193>r<193>ya<207>a')
The Hindus believe that performing obsequial rites with proper offerings ç
will help the souls or spirits of dead persons in relieving their ç
sufferings and guiding them to the next destination. This becomes ç
all the more necessary if a person has met with an unnatural death ç
by suicide or accidents.
N<193>r<193>ya<207>abali is a rite connected with this. It is performed ç
generally on the eleventh day of the bright half of a month, and involves ç
the worship of Vi<218><207>u and Yama (the god of death). Ten pi<207><195>as ç
(rice-balls) are placed on the darbha (grass†Saccharum cylindricum ç
or Poa cynosuroides),  laved  with  honey.  The details of the rite ç
are similar to the ekoddi<218><219>a-·r<193>ddha.
According to some other works like the Antye<218><219>ipaddhati ç
of N<193>r<193>ya<207>abha<219><219>a (<MS>A.D.<D> 1513-1570?) five ç
kala·as (pitchers of water) are to be placed on a quantity of rice ç
spread over a leaf on which five images of Brahm<193>, Vi<218><207>u, ç
<185>iva, Yama and that of the dead person are to be drawn. Worship ç
is to be offered through certain mantras of the <184>gveda (e.g., ç
10.90). Ten pi<207><195>as are to be offered and then cast in a river.
See also <MS><185>R°DDHA.<D>
@NT = N<193>r<193>ya<207>a Bha<219><219><193>tiri
@N1 = (<MS>A.<|>D.<D> 1560-1625)
There can perhaps be no better example than that of N<193>r<193>ya<207>a ç
Bha<219><219><193>tiri to prove that a chance utterance from a great ç
soul can lift a person from the ridiculous to the sublime.
N<193>r<193>ya<207>a Bha<219><219><193>tiri is more well-known as ç
the author of the immortal epic poem N<193>r<193>ya<207><200>yam. ç
He was born at Meppatt<220>r (in the Kerala State) in <MS>A.<|>D.<D> ç
1560.  His  father  was  M<193>t<216>datta,  an orthodox br<193>hma<207>a ç
of great erudition, from a famous Namb<220>diri family.
During his early youth he appeared to be more a profligate than a ç
prodigy which he certainly was. A chance remark of reprobation from ç
Acyuta Pi·ara<195><200>, converted the young N<193>r<193>ya<207>a ç
Bha<219><219><193>tiri into a remorseful but earnest disciple of that ç
great man of profound learning and wisdom.
In course of time, N<193>r<193>ya<207>a became a pundit in his own ç
right. When his guru fell a victim to paralysis, N<193>r<193>ya<207>a, ç
being a devoted disciple, took upon himself that fell disease, thus ç
freeing his master from the same.
However, unable to bear the torments of that disease, he started visiting ç
the temple of Lord K<216><218><207>a at Guruv<193>y<220>r (near Trichur, ç
also in the Kerala State), by being carried to that place. For one ç
hundred days he prayed to the Lord, spontaneously composing 10 verses ç
each day, dealing with the da·<193>vat<193>ras or ten incarnations ç
of Lord Vi<218><207>u. On the last day he was totally freed from that ç
debilitating disease!
This work, now known as the N<193>r<193>ya<207><200>yam, is in ten ç
cantos, the total number of verses being 1036. They are in different ç
meters.
See <MS>N°R°YAØ®YAM<D> for details.
N<193>r<193>ya<207>a Bha<219><219><193>tiri was a great scholar in ç
several fields of traditional learning. Eighteen works are attributed ç
to him. Some of them are: N<193>r<193>ya<207><200>yam, M<193>nameyodaya, ç
Prakriy<193>sarvasva, A<218><219>am<200>camp<220>k<193>vya, Kail<193>sa·ailavar<207>ana, ç
R<193>makath<193>, R<193>jas<220>yaprabandha and Ahaly<193>·<193>pavimocana.
He had been appointed as the court pundit of the king Devan<193>r<193>ya<207>a ç
of Ambalapura.
@SPACE1 = 
He is said to have passed away at the ripe old-age of 106 in <MS>A.<|>D.<D> ç
1666, though some scholars do not subscribe to this view.
A devoted recitation of his N<193>r<193>ya-<207><200>yam is believed ç
to free one from diseases and bestow good health.
@NT = N<193>r<193>ya<207>a Guru
@N1 = (<MS>A.<|>D.<D> 1854-1928)
If a lotus plant that grows in quagmire can bring out a beautiful ç
blossom which is also fragrant, there is no reason why a great man ç
should not be born in a family belonging to a socially berated caste. ç
This is exactly what the highly venerated N<193>r<193>ya<207>a Guru ç
has shown to the world.
N<193>r<193>ya<207>a was born at the village Cemp<193>rajha<207><195>i ç
near Tiruvananthapuram (or Trivendrum), the capital of the Kerala ç
State in <MS>A.<|>D.<D> 1854. His parents were M<193>dan and Ku<219><219>i ç
Amma. They belonged to the ezhava caste (caste of the toddy-tappers, ç
considered untouchables). Being very intelligent he managed to get ç
a good education especially from a great teacher R<193>man  Pi<202><202>ai  °san  of  Karun<193>gapalli ç
village.
Though married as per the usual social customs, the death of his wife ç
soon after, made him roam about like a mendicant. He met two great ç
teachers† Ku<210>jan Pi<202><202>ai (Ce<219><219><193>mbi Sv<193>mi) ç
and Th<200>kk<193><195>u Ayy<193>vu†who helped him to attain scholarship ç
and proficiency in yoga.
Later, he settled down in a forest near the town Aruv<200>puram and ç
practised meditation and austerities. Attaining great inner peace ç
and realising the mission ofhis life, he established an <193>·rama ç
(monastery) there itself and started several social service activities.
His pure life and universal love transcending all social barriers ç
attracted a large number of persons who became his disciples and followers. ç
He also started building temples of <185>iva and training the priests ç
to worship there.
Thus N<193>r<193>ya<207>a became N<193>r<193>ya<207>a Guru by his ç
life and work.
He specially crusaded against ignorance and superstition, untouchability, ç
drinking, animal sacrifice as also cruelty to animals, caste-animosities ç
and a host of other unhealthy practices prevalent in the society.
Attracted by his personality and teachings many young persons joined ç
him, forming an organisation now known as <185>r<200> N<193>r<193>ya<207>aguru ç
Dharma Parip<193>lana Yogam (S.<|>N.<|>D.<|>P. Yogam).
N<193>r<193>ya<207>a Guru established in <MS>A.<|>D.<D> 1904 a Gurukul<193>·rama ç
at <185>ivagiri 48 kms. (30 miles) to the north of Tiruvanantha-puram ç
where poor children, irrespective of their caste were given good education, ç
including vocational training. He also started many more schools of ç
Sanskrit and English, as also an Advait<193>·rama at °<202>v<193>y ç
to teach universal brotherhood.
He took active part in what is now known as Vaikom Saty<193>graha, ç
to gain entry into the Hindu temples for the untouchable castes.
He has written quite a few books inMalay<193><202>am (his mother-tongue) ç
and Sanskrit, of which Brahmavidy<193>pa<210>cakam and Dar·anam<193>l<193> ç
are well-known.
@NT = N<193>r<193>ya<207>as<220>kta
@N1 = (`hymn to N<193>r<193>ya<207>a')
The Mah<193>n<193>r<193>ya<207>a Upani<218>ad forms the fourth section ç
of the Taittir<200>ya °ra<207>yaka. It is often considered as khila ç
or supplement to the Taittir<200>ya Upani<218>ad, which precedes ç
it. It contains four well-known Vedic s<220>ktas, of which the N<193>r<193>ya<207>as<220>kta ç
is the most important. It forms the thirteenth anuv<193>ka or section ç
and has twelve mantras or stanzas. It is generally used to offer flowers ç
at the end of a p<220>j<193> (ritualistic worship) or even chanted ç
on auspicious occasions.
@EMERGEN1 = It describes the greatness of N<193>r<193>-ya<207>a, the ç
Supreme God and how to meditate on him in one's heart.
@EMERGEN1 = A general translation of the same, verse by verse, is ç
as follows:
@S10 = Verse 1
This universe is truly the Divine Person only. Therefore it subsists ç
on him. He, the Divine Being, has countless heads and eyes. He is ç
the giver of joy to the universe. It is He who exists in the form ç
of the universe and is also the abode of all the human beings. He ç
is self-effulgent, imperishable and the final abode of all.
@S10 = Verse 2
He has transcended the universe. He is eternal. He is all-pervading, ç
refuge of all humanity and the destroyer of sins. This universe is ç
verily that Divine Person and on Him it subsists.
@S10 = Verse 3
He is the lord of this universe. He is the Self of all beings as also ç
the ruler. He is eternal, indestructible and ever auspicious. He has ç
entered into all beings as the in-dweller. He is supremely worthy ç
of being known (or realised). Though embodied in the universe (as ç
its original cause) he is also the goal of all, the highest refuge.
@S10 = Verse 4
N<193>r<193>ya<207>a is the Supreme Reality designated as Brahman. ç
He is the highest (Self). He is the Supreme Light. He is the infinite ç
Self. He is the excellent meditator and meditation.
@S10 = Verse 5
Whatever there is in this world, directly perceived or known through ç
the scriptures, N<193>r<193>ya<207>a has pervaded all that, both within ç
and without.
@S10 = Verse 6
One  should  meditate  upon  the Supreme, dwelling in the heart, who ç
is limitless, unchanging, omniscient, the giver of happiness to all, ç
as the goal of all striving. The place of His meditation is the ether ç
in the heart which is like an inverted lotus-bud.
@S10 = Verse 7
It should be known that the heart which is located at the distance ç
of a finger-span below the Adam's apple, and above the navel is the ç
great abode of the universe and, which is shining like a garland of ç
flames.
@S10 = Verse 8
Like the bud of a lotus, the heart issuspended in an inverted position, ç
surrounded by arteries. In it or near it, there is a narrow space ç
(called su<218>umn<193>). In it everything is supported.
@S10 = Verse 9
In the middle of that (su<218>umn<193>) remains  the  undecaying,  all-knowing, ç
omnifaced, great fire which has flames on every side. It enjoys the ç
food presented before it and assimilates it. Its rays are scattered ç
vertically and horizontally.
@S10 = Verse 10
It warms its own body from the foot to the head. In the centre of ç
that fire there abides a tongue of fire which is extremely fine (or ç
subtle).
@S10 = Verse 11
@EMERGENCY = It is dazzling like the flash of the lightning that appears ç
in the middle of a rain-bearing cloud, which is slender as the awn ç
of a paddy grain and which serves as a simile to illustrate subtlety.
@S10 = Verse 12
Param<193>tman (Supreme Self) dwells in the middle of that flame. ç
It is He who has become Brahm<193>, <185>iva, Indra and the Ak<218>ara ç
(Imperishable). It is He who is the Supreme Ruler.
In some texts there are two additional stanzas:
1.<+>He is <184>ta (the Cosmic Law), Satya (the Truth), the highest ç
Brahman, the dark and tawny Person who has absolute control over Himself. ç
He has strange and variegated eyes and is omniform. We meditate on ç
Him and bow down to Him.
2.<+>This is the famous N<193>r<193>ya<207>a g<193>yatr<200>: `We ç
know N<193>r<193>ya<207>a. We meditate on V<193>sudeva. May that Vi<218><207>u ç
inspire us!'
@EMERGEN1 = In sum, we can say that this is an excellent hymn, not ç
only for prayer but also for meditation.
@NT = N<193>r<193>ya<207>a Upani<218>ad
This is a short Upani<218>ad classed among the Minor Upani<218>ads ç
of the K<216><218><207>a Yajurveda. It has four kha<207><195>as ç
or sections, all in prose.
The first describes how N<193>r<193>ya<207>a, the Puru<218>a (Paramapuru<218>a, ç
the Supreme Person) desired to create the world of beings. From him ç
evolved the following objects and beings: pr<193><207>a (the vital ç
force); manas (mind); indriyas (the ten sense- organs); the pa<210>cabh<220>tas ç
(five elements); the gods Brahm<193>, Rudra and Indra; the nine Praj<193>patis ç
(like Dak<218>a); the twelve °dityas, the eleven Rudras and the eight ç
Vasus; and, lastly, all the Vedas. All these get manifested out of ç
N<193>r<193>ya<207>a, are activated by him during the life of the ç
created world, and then, get merged back in him at the end of the ç
cycle.
The second kha<207><195>a describes how N<193>r<193>ya<207>a is eternal ç
and how Brahm<193>, <185>iva, Indra, time in its three aspects, the ç
quarters, and all the directions are all different facets of N<193>r<193>ya<207>a. ç
N<193>r<193>ya<207>a who is without parts, without any imperfections ç
or changes or names, is absolutely pure and the one without a second. ç
One who knows him thus, becomes Vi<218><207>u Himself.
The third kha<207><195>a describes the well-known a<218><219><193>k<218>ar<200>mantra, ç
the mantra of eight letters of N<193>r<193>ya<207>a†o<221> namo n<193>r<193>ya<207><193>ya. ç
One who repeats this great mantra regularly as per the directions ç
of the guru (spiritual teacher), will transcend all dishonour and ç
will live long. He will also get wealth, cows and other objects of ç
desire while living here and go to Brahmaloka (the world of Brahm<193>) ç
after death. Later on, he will attain final liberation.
The last kha<207><195>a describes N<193>r<193>ya<207>a as Brahman, ç
the Puru<218>a (the all-pervading Being) who is of the nature of Pra<207>ava ç
(O<221>) comprising the three syllables a, u and m. The yogi who utters ç
this Pra<207>ava or the a<218><219><193>k<218>ar<200>mantra will be ç
liberated from the bondage of sa<221>s<193>ra (transmigration) and ç
attain the world called Vaiku<207><219>ha (the Abode of Vi<218><207>u).
This N<193>r<193>ya<207>a who is pure solidified consciousness resides ç
in the lotus of the heart. He is identified with Devak<200>putra-K<216><218><207>a, ç
who is dear to the knowers of Brahman or to whom the latter are dear. ç
He is also the dweller in the hearts of all beings, the un-caused ç
Cause of the universe.
The Upani<218>ad concludes with the eulogy that its study will destroy ç
all sins, will bestow the merit of reciting all the Vedas, ultimately ç
resulting in merging into N<193>r<193>ya<207>a Himself.
@NT = N<193>r<193>ya<207><200>
@N1 = (`the spouse or power of<R>ç
N<193>r<193>ya<207>a')
As the very name suggests, she isthe ·akti or female counterpart ç
of N<193>r<193>ya<207>a and hence Lak<218>m<200> herself. Iconographically ç
she is shown just like N<193>r<193>ya<207>a or Vi<218><207>u.
N<193>r<193>ya<207><200> is a well-known name of Durg<193> too. The ç
Dev<200>m<193>h<193>tmya contains a long hymn (17.1-35) on N<193>r<193>ya<207><200> ç
and is known as the N<193>r<193>ya<207><200>stuti. See <MS>DURG°<D> ç
for details.
N<193>r<193>ya<207><200> (or N<193>l<193>yan<200>) was also the name ç
of the sage Mudgala's wife, her other name being Indrasen<193>. It ç
was she who was reborn as Draupad<200> in her next birth (vide Mah<193>bh<193>rata, ç
°diparva, ch. 212).
@SPACE = 
@NT = N<193>r<193>ya<207><200>ya
@N1 = (`pertaining to N<193>r<193>ya<207>a')
@SPACE = 
The devotional cults of Hinduism have been divided into two main streams: ç
the <185>aiva (that of <185>iva; this includes the <185><193>kta or ç
the cult of the Divine Mother) and the Vai<218><207>ava (that of Vi<218><207>u), ç
(also known as the Bh<193>gavata cult).
One of the basic and very important texts†perhaps the oldest too†is ç
the N<193>r<193>ya<207><200>ya section of the Mah<193>bh<193>rata, ç
comprising the 18 chapters (chs. 334 to 351) of the <185><193>ntiparva ç
(the 12th book of the epic). The total number of verses† which sometimes ç
includes paragraphs and sentences in prose also†is 1310.
The entire section is devoted to the glorification of Lord N<193>r<193>ya<207>a, ç
his devotees, and the nature of devotion to be cultivated towards ç
him.
A brief summary of this section may now be attempted here:
@S10N = Chapter 1 (Ch. 334; 45 verses)
N<193>rada visits the Badarik<193>·rama where Nara and N<193>r<193>ya<207>a ç
(the twin sages) are performing severe austerities. In reply to N<193>rada's ç
question as to whom he was meditating upon and worshipping, the sage ç
N<193>r<193>ya<207>a replies that it was on the Supreme God (N<193>r<193>ya<207>a).
@S10N = Chapter 2 (Ch. 335; 55 verses)
As per the directions of the sage N<193>r<193>ya<207>a, N<193>rada ç
visits the <185>vetadv<200>pa, the island beyond the mountain Meru. ç
He is wonder-struck to see there, the multitude of devotees of Lord ç
N<193>r<193>ya<207>a, who were absolutely white in colour (·veta = ç
white) and were deeply immersed in meditation on him.
@S10N = Chapter 3 (Ch. 336; 65 verses)
The great sacrifice performed by the king Uparicara†a devotee of the ç
highest order†under the guidance of the sage B<216>haspati forms the ç
subject matter of this chapter.
@S10N = Chapter 4 (Ch. 337; 41 verses)
This chapter describes how the king Uparicara, though he had attained ç
heaven, fell from there since he permitted the immolation of a goat ç
in a sacrifice, thereby committing hi<221>s<193> (violence). He was ç
however saved by the Lord N<193>r<193>ya<207>a by the power of the ç
a<218><219><193>k<218>ar<200> (eight-lettered) mantra (= o<221> ç
namo n<193>r<193>ya<207><193>ya) which he was constantly repeating.
@S10N = Chapter 5 (Ch. 338; 200 names of the Lord)
This chapter contains a long hymn in prose, in praise of Lord N<193>r<193>ya<207>a, ç
by the sage N<193>rada while in the <185>vetadv<200>pa. It has 200 ç
epithets.
@S10N = Chapter 6 (Ch. 339; 141 verses)
Pleased by N<193>rada's devotional prayer, the Lord N<193>r<193>ya<207>a ç
appears before him in his Cosmic Form (Vi·var<220>pa) which was indescribably ç
beautiful and brilliant.
N<193>rada is advised by the Lord to serve the sages Nara and N<193>r<193>ya<207>a ç
of the Badarik<193>·rama.
There is also a brief description of the four Vy<220>has: V<193>sudeva, ç
Sa<209>kar<218>a<207>a, Pradyumna and Aniruddha. (See <MS>CATUR-VY<188>HAS<D> ç
for details.)
@S10N = Chapter 7 (Ch. 340; 119 verses)
This chapter is mainly devoted to the delineation of prav<216>ttidharma ç
(performance of one's duties as prescribed by the ·<193>stras or scriptures), ç
yaj<210>as or Vedic sacrifices being the main part of the same. Towards ç
the end, niv<216>ttidharma (path of knowledge and renunciation) is ç
also touched upon.
@S10N = Chapter 8 (Ch. 341; 51 verses)
The various names by which Lord K<216><218><207>a was praised are ç
described here along with their etymological meanings by K<216><218><207>a ç
himself to Arjuna. The identity of Brahm<193> and Rudra (<185>iva) ç
with N<193>r<193>ya<207>a (or K<216><218><207>a) has also been stressed.
@S10N = Chapter 9 (Ch. 342; 142 verses including prose paras)
This section is a combination of verses interspersed with prose passages. ç
It des-cribes s<216><218><219>i or creation, greatness of br<193>hma<207>as ç
(the wise spiritual persons), story of the sage Dadh<200>ci (See <MS>DADH®CI<D>.), ç
story of the king Nahu<218>a being cursed by the sage Agastya, creation ç
of the work Nirukta by the sage Y<193>ska, about the four Vedas ç
and fighting between Rudra and N<193>r<193>ya<207>a.
@S10N = Chapter 10 (Ch. 343; 66 verses)
In this chapter, the second visit ofthe sage N<193>rada to <185>vetadv<200>pa ç
and revisiting the sages Nara and N<193>r<193>ya<207>a are described.
@S10N = Chapter 11 (Ch. 344; 27 verses)
This  short  section  expounds  the nature of Lord V<193>sudeva, the ç
highest aspect of N<193>r<193>ya<207>a.
@S10N = Chapter 12 (Ch. 345; 28 verses)
The origin of ·r<193>ddha and tarpa<207>a (obsequial rites), attributed ç
to the Var<193>h<193>vat<193>ra (boar-incarnation of Vi<218><207>u) ç
is expounded here.
@S10N = Chapter 13 (Ch. 346; 22 verses)
This chapter is a eulogy of the merit one gets by listening to the ç
greatness of Lord N<193>r<193>ya<207>a.
@S10N = Chapter 14 (Ch. 347; 96 verses)
When the two demons Madhu and Kai<219>abha had stolen the Vedas, Vi<218><207>u ç
took the form of Hayagr<200>va (See <MS>HAYAGR®VA<D> for details.) ç
and recovered them. Later on he killed the demons also. This is the ç
gist of the contents of this chapter.
@S10N = Chapter 15 (Ch. 348; 88 verses)
This chapter describes how the S<193>tvatadharma  (or  Bh<193>gavatadharma, ç
religion of devotion towards Lord N<193>r<193>ya<207>a or Vi<218><207>u) ç
was taught by the Lord, but, forgotten again and again by the receivers. ç
To receive it and propagate it in the world, Brahm<193> had to take ç
seven births! This dharma of single-minded devotion taught in the ç
Upani<218>ads and the P<193><210>car<193>tra °gamas is superior ç
to the path of j<210><193>na (knowledge) and can be got only by God's ç
grace.
@S10N = Chapter 16 (Ch. 349; 74 verses)
The birth of the sage Vy<193>sa, first as the sage Ap<193>ntaratamas ç
and later as K<216><218><207>a-Dvaip<193>yana, is described here. ç
How he edited and divided the Vedas as alsohis encyclopedic knowledge ç
are also delineated. Another interesting point stressed here is that ç
all the five well-known philosophies contained in the metaphysical ç
systems of S<193><207>khya, Yoga, P<193><210>car<193>tra, Vedas and ç
P<193>·upata lead to the same goal viz., N<193>r<193>ya<207>a!
@S10N = Chapter 17 (Ch. 350; 27 verses)
This is a short chapter describing the meeting between Brahm<193> ç
the creator, and <185>iva, represented here as his son. The ensuing ç
conversation is continued in detail in the next chapter.
@S10N = Chapter 18 (Ch. 351; 23 verses)
This is also a short chapter.
It gives a beautiful description of Lord N<193>r<193>ya<207>a, not ç
only in the cosmic aspect†reminiscent of the one given in the Puru<218>as<220>kta ç
(<184>gveda 10.7.90)†but also as the antary<193>min (inner controller). ç
The four Vy<220>has are also referred to.
It is thus seen that this N<193>r<193>ya<207><200>ya section of ç
the Mah<193>bh<193>rata is specially devoted†as its very name indicates†to ç
the exposition of the glory of Lord N<193>r<193>ya<207>a.
N<193>r<193>ya<207><200>yam is also the name of an extremely elegant ç
poetical work on the K<216><218><207>a-theme, characterised by literary ç
grace and devotional fervour. N<193>r<193>ya<207>a Bha<219><219><193>tiri ç
(<MS>A.<|>D.<D> 1560-1625) of Meppatt<220>r in the Kerala State is ç
its illustrious author. (See <MS>N°R°YAØA BHA<187><187>°TIRI<D> for ç
details.)
This work is a faithful poetical condensation of the entire Bh<193>gavata. ç
Itis in one hundred da·akas (decades or cantos of ten stanzas), the ç
total number of verses †which are in various meters†being a little ç
more than one thousand (1036, to be exact).
The following table gives an idea as to how the story of the Bh<193>gavata ç
has been covered:
@Z_TBL_BEG = COLUMNS(4), DIMENSION(IN), COLWIDTHS(.5000,E1,.5000,E1), ç
HGUTTER(.0555), VGUTTER(.0555), KEEP(OFF)
@Z_TBL_BODY = CEN, TC2M, CEN, TC2M
Skandhas<R>ç
(of Bh<193>gavata), +, Da·akas<R>ç
(of N<193>r<193>ya<207>iyam), +
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE TEXT
, 1<R>ç
2<R>ç
3<R>ç
4<R>ç
5<R>ç
6<R>ç
7<R>ç
8<R>ç
9<R>ç
10<R>ç
11<R>ç
12, , 1-3<R>ç
4-7<R>ç
8-15<R>ç
16-19<R>ç
20,, 21<R>ç
22,, 23<R>ç
24,, 25<R>ç
26-32<R>ç
33-36<R>ç
37-90<R>ç
91-97<R>ç
98-100
@Z_TBL_END = 
(See <MS>BH°GAVATA<D> for the contents of the various skandhas.)
It has been considered a unique work in the Sanskrit language since ç
it combines in itself literary grace comparable to any well-known ç
masterpiece. As a hymn of rare devotional fervour, it can be classed ç
among the best of works in Sanskrit hymnology. Added to these two ç
is the exposition of Ved<193>nta philosophy with the dominance of ç
devotional sentiment.
Thus, it is a distinctive work in Sanskrit from every standpoint.
@NT = Narmad<193>
@N1 = (`giver of joy')
One of the seven sacred rivers of India, remembered daily at the time ç
of ritualistic worship, Narmad<193> is said to have been born out ç
of the sweat of Lord <185>iva when he was once engaged in tapas or ç
austerities. The goddess of this river was so charmingly beautiful ç
that she gave joy to one and all who saw her. Hence the name Narmad<193>.
Though not mentioned in the Vedas, it has been highly eulogised both ç
in the Mah<193>bh<193>rata and in the pur<193><207>as like the Matsya, ç
the K<220>rma and the Padma.
It has been called `Rev<193>' also, theother names being Somodbhav<193> ç
and Mekhalakanyak<193>.
It takes its birth in the mountains of Amaraka<207><219>aka (in Madhya ç
Pradesh), flows towards the west and joins the sea near the gulf of ç
Cambay (near Broach, the ancient Bh<216>gukaccha). Its total length ç
is 1282 kms. (796 miles). There is one water-falls of 24 metres (80 ç
feet) at Kapiladh<193>r<193> and of 12 metres (40 ft.) near Jabalpur.
There are many holy spots on the banks of this river like O<209>k<193>rn<193>th, ç
Karn<193>li, <185>uklat<200>rtha, Broach and so on. O<209>k<193>rn<193>th ç
is one of the twelve Jyotirli<207>gas and the temple is situated on ç
the island of M<193>ndh<193>t<193> inside the river. The emperor M<193>ndh<193>t<193> ç
of the solar race is said to have worshipped this li<209>ga. The island ç
itself is situated between the rivers Narmad<193> and K<193>ver<200> ç
(not the K<193>ver<200> of South India). It is here that <185>iva ç
is said to have destroyed the three cities, Tripura.
B<193><207>ali<209>gas of <185>iva are available in the river-bed ç
a few miles away from O<209>k<193>re·vara (See <MS>B°ØLIØGA<D> for ç
details.)
Where the tributary Or merges into Narmad<193>†the place being called ç
Chandod †Vy<193>sa is said to have performed auste-rities.
@SPACE1 = 
<185>r<193>ddhas (obsequial rites) done on the banks of the Narmad<193> ç
are said to yield inexhaustible results.
@NID = <+><+><+><+>Narmad<193>-parikrama is another sacred act sometimes ç
undertaken by devout pilgrims. It consists in walking from the confluence ç
at sea up to the source in Amaraka<207><219>aka and then return by ç
the other bank to the sea. This generally takes about two years.
In the <185>uklat<200>rtha, there are three ponds of Kavi, <185>ukla ç
and O<209>k<193>re·vara. A religious festival is held here every year ç
on the p<220>r<207>ima or full-moon day of K<193>rttika.
The Vi<218><207>upur<193><207>a (4.3) gives a mantra in praise of ç
Narmad<193> which dispels the poisons of serpents.
The water of Narmad<193> is considered so pure that even Ga<209>g<193> ç
(the goddess of that river) comes once a year as a black cow, bathes ç
in it, becomes white and then returns!
Temples of Kumbhe·vara Mah<193>deva, <185>ani (Saturn) and <185><220>rpa<207>e·vara ç
are the other holy places gracing its banks.
See also <MS>AMARAKAØ<187>AKA.<D>
@NT = Nars<200> Meht<193>
@N1 = (<MS>A.<|>D.<D> 1415-1481)
If  Vivek<193>nanda  (<MS>A. D.<D>  1863-1902) declared that he alone ç
lives who lives for others, he was probably echoing another great ç
saint who preceded him by four centuries, who sang thus: `He alone ç
is a Vai<218><207>ava†a man of God†who understands the sufferings ç
of others' (vide his song `Vai<218><207>ava janato...'). This was ç
Nars<200> Meht<193> (also spelt as `Naras<200> Mehat<193>'), the foremost ç
saint of Gujarat.
Born in <MS>A.<|>D.<D> 1415 as the second son of K<216><218><207>a ç
D<193>modar D<193>s and Lak<218>m<200>-gaur<200> (who were n<193>gara-brahma<207>as ç
by caste) at the village Tal<193>j<193> (near the modern town of Junagadh ç
in Gujarat), Narasi<221>har<193>m †that was his earlier name†was dumb ç
right from his childhood days. Having lost both the parents at the ç
age of five, he was brought up by his grandmother Jayakuvar<200>. ç
When he was eight years old, he was suddenly endowed with the power ç
of speech by a great saint, who made him utter the words `R<193>dh<193>-K<216><218><207>a!'
After the death of Jayakuvar<200>, the boy Narsi<221>har<193>m or ç
Nars<200> Meht<193>, had to be taken care of by his elder brother ç
Va<221>·<200>dhar and aunt Duritgaur<200>. As per the traditions of ç
the family, Va<221>·<200>dhar tried to get him educated and also got ç
him married to M<193><207>ikgaur<200>, a girl from a good family. ç
Nars<200> was blessed with two children†a boy and a girl†in course ç
of time. However, this shrew of an aunt made his life so miserable ç
that he, one night, leaving behind his own wife and two children escaped ç
to a deserted temple of Lord <185>iva on the outskirts of the town.
After seven days of fasting and intense prayer he was blessed with ç
the vision of Lord <185>iva who was instrumental in vouchsafing to ç
him an actual experience of participating in the R<193>sal<200>l<193> ç
dance of K<216><218><207>a with the gop<200>s! This changed his whole ç
life permanently and Lord K<216><218><207>a gave him the boon of remaining ç
as his eternal friend, guide and protector.
Nars<200> Meht<193> now started an entirely new life, a life rooted ç
in God, spending most of his time in composing and singing devotional ç
songs related to K<216><218><207>a, as also dancing in ecstasy.
@SPACE1 = 
True to his word, as promised in the Bhagavadg<200>t<193> (9.22), ç
K<216><218><207>a came to the rescue of Nars<200> many a time, when ç
evil- doers created serious problems. Some of the miraculous happenings ç
described in his traditional biographies are: supplying all the things ç
demanded of Nars<200> by the parents of his son-in-law; giving plenty ç
of money to a rich man who had brought a `demand draft' issued by ç
Nars<200>; getting garlanded by K<216><218><207>a himself in the temple, ç
by a garland of tulas<200> leaves, and so on.
Nars<200>'s son predeceased him. This, instead of making him dejected, ç
made him more happy since he could pray to his Lord even more intensely.
He gave up the body in great peace, during the year <MS>A.<|>D.<D> ç
1481.
His contribution to Gujarati literature in the form of beautiful songs ç
of devotion is considerable.
Some of his compositions are: <185>y<193>mald<193>sno Viv<193>h; ç
H<193>rm<193>l<193>; S<220>rat Sa<209>gr<193>m; Sud<193>m<193>carit; ç
R<193>sasahasrapad<200>; <185><216><209>g<193>rm<193>l<193>; Govind<193>gaman ç
and B<193>lal<200>l<193>.
He laid great stress on devotion to God and ignored caste restrictions. ç
Cultivation of firm faith in God and dependence on Him are his other ç
teachings.
@NT = N<193>sad<200>yas<220>kta
@N1 = (`the s<220>kta [beginning <R>ç
with the word] ``n<193>sad''<|>')
How exactly the creation of this world came about, this world of myriads ç
of mysteries and insoluble riddles, has been too knotty a problem ç
to be satisfactorily solved by the puny human intellect, which itself ç
is a product of the whole process! The effect cannot discover its ç
cause, even as we cannot see our own back.
However,  we  can  see  our  back provided we use two mirrors, one ç
at the back and the other in our front, properly adjusted. Similarly, ç
if we can judiciously use the knowledge of the <185>ruti (the Vedas) ç
to back up our intellect and be guided by the sayings and doings of ç
the <216><218>is, persons of intuitive or superconscious (spiritual) ç
experience, we can succeed in getting some glimpses of the secrets ç
of creation that will ultimately help us in reaching the final goal ç
of our life. Study of selected parts of the Vedas like the N<193>sad<200>yas<220>kta, ç
is a great aid in this endeavour of ours to attain perfection.
The N<193>sad<200>yas<220>kta is a part of the <184>gveda (10.129.1-7). ç
Praj<193>pati Parame<218><219>h<200> is said to be the <216><218>i ç
(sage) to whom it was revealed. Param<193>tm<193> (God, the Creator, ç
called `Bh<193>vav<216>ttam' by S<193>ya<207>a, the commentator) is ç
the devat<193> or the deity. Tri<218><219>ubh is the metre in which ç
it is composed.
This is a wonderful and highly poetic hymn that describes what existed ç
before creation and how creation came about.
@SPACE1 = 
The S<220>kta begins with an account ofwhat existed before creation. ç
Since Hinduism posits a cyclic theory of creation †s<216><218><219>i ç
(creation or evolution), sthiti (sustenance) and pralaya or laya (destruction ç
or involution), taking place eternally in that order† this description ç
applies to all cycles. That (or He) alone†the Brahman of the Upani<218>ads ç
or God of religion† existed, the One without a second, breathing (living) ç
by himself though without breath. There was deep blinding darkness ç
everywhere. However, that One, Brahman, through intense tapas†self-reflection ç
or profound thinking†became (through his own greatness or power) transformed ç
into this world. Actually, this desire to create arose in him due ç
to the `seed' in his mind, the unmanifested karmas of the beings carried ç
over from the previous cycle. The <216><218>is or sages possessing ç
transcendental or intuitive wisdom, had discovered this secret.
As Brahman willed the evolution of this world, the inanimate (various ç
objects) and the animate (the j<200>vas or the living beings) got ç
manifested, the latter being superior to the former.
This evolution went on continuously, producing not only the pa<210>cabh<220>tas ç
(the five primordial elements) but also the devas (gods who exercise ç
control over these).
However, this process†how the One became the many†remains a mystery ç
even to these devas, since they too came afterwards.
This Brahman, the Supreme Being, not only created this world (out ç
of his free will) but is also sustaining it.
If he does not do this, who else can?
The whole secret of creation is known only to him. If he cannot, who ç
else can?
This is the gist of the whole S<220>kta.
In this hymn we find a very advanced theory of creation which is developed ç
later in the Upani<218>ads also (vide Taittir<200>ya Upani<218>ad ç
3.7; Ch<193>ndogya Upani<218>ad 6.2.1; Mu<207><195>aka Upani<218>ad ç
1.1.9; Aitareya Upa-ni<218>ad 1.1.1 and so on).
It is interesting and even puzzling to note that the sage to whom ç
this S<220>kta was revealed, has used quite a few mutually contradictory ç
words and phrases. For instance, he says: There was then neither what ç
is (sat) nor what is not (asat)... There was no death (m<216>tyu) ç
and hence nothing immortal (am<216>ta). There was no night (r<193>tri) ç
nor day (ahan).
@SPACE1 = 
The only explanation that can be offered for the use of apparently ç
contradictory terms is that in the beginning there was only the One ç
(tat) and there was no second person or object when and when only ç
comparative statements are possible.
@NT = N<193>sik
Visiting places of pilgrimage as a part of religious duty imposed ç
by the scriptures of one's faith or for getting spiritual inspiration ç
is a universal phenomenon found in all the great religions of the ç
world.
Out of the several important places of pilgrimage listed by the pur<193><207>as ç
and the nibandhas (digests) N<193>sik is also one. It is a district ç
headquarters in Maha-rashtra and is 10 kms. (6.2 miles) from the Nasik ç
Road railway station.
It was probably known as N<193>sikya or Nava·ikhara in the olden days. ç
The first name might have been derived because of the cutting of the ç
nose (= n<193>sik<193>) and ears of <185><220>rpa<207>akh<193> by ç
Lak<218>ma<207>a at this place. Alternatively, since there are nine ç
peaks (= nava-·ikhara) of small mountains nearby, it might have been ç
christened `Nava·ikhara'.
It is sometimes called `Pa·cimak<193>·<200>' and the God<193>var<200> ç
river, the banks on which it is situated, named `Ga<209>g<193>' also.
N<193>sik is one of the four holy places where the great bathing festivals ç
and religious fairs known as `Kumbhamel<193>' are held. It takes place ç
when the planet B<216>haspati or Guru (Jupiter) enters the zodiacal ç
sign Si<221>ha (Leo), once in twelve years. A bath in the God<193>var<200> ç
during thisperiod†technically called `Pu<218>kara'† is considered ç
as extremely auspicious.
@SPACE1 = 
The God<193>var<200> river takes its birth in the Brahmagiri hill ç
near Tryambake·var, about 32 kms. (20 miles) from N<193>sik. The temple ç
of Tryambake·var contains one of the twelve Jyotirli<209>gas.
Pa<210>cava<219><200>, where R<193>ma, S<200>t<193> and Lak<218>ma<207>a ç
camped during their banishment from Ayodhy<193> and from where S<200>t<193> ç
was abducted by R<193>va<207>a is to the north of N<193>sik town. ç
This spot was known as Padmanagara in the K<216>tayuga, Trika<207><219>aka ç
in the Tret<193>yuga, Janasth<193>na in the Dv<193>parayuga and N<193>sika ç
in the Kaliyuga.
N<193>sik once abounded in temples most of which were destroyed by ç
Aurangazeb (<MS>A.D.<D> 1618-1707). Among these were the temples ç
of N<193>r<193>ya<207>a, Um<193>mahe·vara, R<193>ma, Kap<193>le·vara ç
and Mah<193>lak<218>m<200>. Most of the surviving temples were built ç
during the rule of the Pe<218>vas of Maharashtra.
The temple of Sundaran<193>r<193>ya<207>a is situated in the °ditw<193>rpe<219>, ç
facing east. There are three images†the image of N<193>r<193>ya<207>a ç
in black stone, 91.5 cms. (3 ft.) in height is at the centre, flanked ç
by two smaller images of <185>r<200>dev<200> and Bh<220>dev<200>†in ç
the shrine. The image of N<193>r<193>ya<207>a is so situated that ç
on the 20th or 21st March every year, the sun's rays at sunrise fall ç
on his feet.
The K<193>l<193>r<193>m temple (temple of R<193>ma with the image ç
in black stone) is another well-known structure frequented by the ç
pilgrims. It is built on a jagat<200> (platform) 87 metres (285 ft.) ç
by 32 metres (105 ft.). It was constructed in <MS>A.<|>D.<D> 1798. ç
There are two more temples, of N<193>r<193>ya<207>a and Bhadrak<193>l<200>, ç
which too are well-known.
Another temple at M<193>leg<193>se built by the king N<193>r<220> ç
<185>a<209>kar, has a nice bell cast in Portugal.
@SPACE1 = 
S<200>t<193>gumpha (or guh<193>) in Pa<210>cava<219><200> the cave ç
where S<200>t<193> is said to have been
