@NID = kept and protected, is another important spot visited by the ç
pilgrims. It contains the images of R<193>ma, S<200>t<193>, Lak<218>ma<207>a ç
and a li<209>ga of Pa<210>caratna Mah<193>deva.
There are a few, very old and tall Banyan trees that are believed ç
to have sprung up from the original trees (that were there when R<193>ma ç
arrived).
There are numerous bathing places and pools (known as ku<207><195>as) ç
between Govardhana (10 kms. or 6 miles to the west of N<193>sik) and ç
Tapovana (2.5 kms. or 1<P7W1><|><P9W1><$E 1/2 ><P7W1> <P255D>miles ç
to the south-west of N<193>sik). The R<193>maku<207><195>a near the ç
left bank of the God<193>var<200> where it turns towards the south, ç
is considered the holiest of these ku<207><195>as.
Near N<193>sik there are more than 20 Buddhist caves known as P<193><207><195>ule<207><193>-guh<193>s ç
where the bhikkus used to live during the rainy season.
Many <|>archaeological<|> finds <|>have<|> been discovered near N<193>sik, ç
belonging to the prehistoric eras, as also stone inscriptions of later ç
period (200 <MS>B.<|>C.<D> to <MS>A.<|>D.<D> 200).
See also <MS>GOD°VAR®.<D>
@NT = n<193>stika
@N1 = (`atheist')
A n<193>stika is one who says `It does not exist!' (na = not, asti ç
= exist). He does not believe in the existence of God, the soul, after-life, ç
heaven and hell†in fact all that cannot be experienced by the five ç
sense-organs.
See <MS>C°RV°KA-DAR<185>ANA.<D>
@NT = N<193>stika Dar·anas
Indian philosophical systems†known as Dar·anas†have been broadly grouped ç
under two categories: the <193>stika and the n<193>sitka.
All those systems which accept the authority of the Vedas are called ç
`<193>stika' whereas those that do not, are branded as `n<193>stika'. ç
The C<193>rv<193>ka, the Jaina and the Bauddha systems are classified ç
under the latter.
@NT = Na<219>ar<193>ja
@N1 = (`king of dance or dancers')
<185>iva, Dev<200> and Vi<218><207>u are the three aspects of the ç
Supreme Lord, most commonly worshipped by the Hindus even today.
Though <185>iva is generally worshipped in the temples in the aniconic ç
form, the li<209>ga, iconic forms are not uncommon. They are mostly ç
depicted on the walls and niches outside the sanctum.
These iconic forms are generally divided into eight categories (See ç
<MS><185>IVA<D> for details.) of which N<216>tta or T<193><207><195>ava ç
m<220>rtis are also one. Treatises on dancing describe 108 modes of ç
dancing, all attributed to <185>iva as the originator.
However, out of the nine modes more well-known and popular, the Na<219>ar<193>ja ç
aspect is the best.
The earliest use of the name `Na<219>ar<193>ja' appears in the K<193>rik<193>s ç
of Nandike·vara on the M<193>he·varas<220>tras of P<193><207>ini ç
(400 <MS>B.<|>C.<D>). There he mentions that <185>iva sounded his <195>amaru ç
(small sounding drum) fourteen times at the end of his dance, producing ç
fourteen sound-patterns †which are now called M<193>he·varas<220>tras ç
†like a i u<207> and so on, which form thebasic structure of entire ç
Sanskrit grammar.
The earliest idea of <185>iva as a dancer can be traced to the <185>ivas<220>tras ç
(3.9-11), a cardinal text of Kashmir <185>aivism.
The Na<219>ar<193>ja icon shows him with four hands and two legs, ç
in the posture of dancing. There is the <195>amaru (drum) in the upper ç
right hand and fire in the left. The lower right hand is in abhayamudr<193> ç
(pose of protection) and the left is pointing towards the uplifted ç
left foot. Theright foot is resting on the demon Apasm<193>ra-puru<218>a. ç
The whole image may be surrounded by a circle of blazing fire.
@SPACE1 = 
<185>iva's dance indicates a continuous process  of  creation,  preservation  and ç
destruction. The <195>amaru represents the principle of ·abda (sound) ç
and hence <193>k<193>·a (ether), which <|>proceeds immediately from ç
the °tman and is responsible for further creation or evolution. Fire ç
represents pralay<193>gni, the fire that destroys the world at the ç
time of dissolution of the world, and hence symbolises the process ç
of destruction. Thus <195>amaru and fire represent the continuous ç
cycle of creation, preservation and destruction. The other two hands ç
indicate that he who takes refuge at the feet of the Lord will have ç
nothing to fear. The Apasm<193>ra-puru<218>a (Apasm<193>ra = epilepsy) ç
symbolises ignorance which makes us lose our balance and consciousness. ç
He is trampled upon by the Lord for the good of the devotees who take ç
refuge.
@SPACE = 
@NT = N<193>tha Cult
@SPACE = 
The N<193>tha Cult, also known as the N<193>thapantha, is an esoteric ç
cult closely related to <185>aivism and Ha<219>hayoga. °din<193>tha, ç
Matsyendran<193>tha and Gorak<218>a-n<193>tha (or Gorakhn<193>th) ç
are the three, the most prominent, of the teachers.
The a<218><219><193><209>gayoga as taught by Pata<210>jali (200 <MS>B.<|>C.<D>) ç
along with certain practices of Ha<219>hayoga by which the s<193>dhaka ç
(spiritual aspirant) can rouse hisKu<207><195>alin<200> and get it ç
united in the sahasr<193>racakra with <185>iva, is the main mode of ç
spiritual practice. One who has achieved the goal, shakes off all ç
bonds and becomes an avadh<220>ta or a siddhayogi, ever immersed in ç
bliss.
Piercing of the earlobes and wearing big ear-rings (because of which ç
they are commonly known as k<193>npha<219>a yogis, `yogis with torn ç
earlobes') as also a woollen thread-like yaj<210>opav<200>ta (sacred ç
thread), holding a horn and smearing bhasma or holy ash all over the ç
body†these are some of the characteristic marks by which they can ç
be distinguished.
Their names†after initiation into the Order†generally end with the ç
word `n<193>tha'.
A disciple who desires to be initiated into this cult must have 36 ç
qualities some of which are: j<210><193>na (knowledge), viveka (discrimination), ç
santo<218>a (contentment), ·<200>la (pure character) and so on.
This cult seems to have spread in most parts of India and Nepal.
Dharman<193>th, a brother-disciple of Gorakhn<193>th, is said to have ç
spread it in the Kutch district of Gujarat.
See also<MS> GORAKHN°TH<D> and <MS>MATS- YENDRAN°THA.<D>
@NT = N<193>thamuni
@N1 = (<MS>A.<|>D.<D> 823-924)
<185>r<200>vai<218><207>avism is a sect of Vai<218><207>avism †the ç
religion and philosophy of the Vai<218><207>avas or worshippers of ç
Lord Vi<218><207>u† current mostly in South India, especially in the ç
States of Tamil Nadu, Karnataka and Andhra Pradesh.
The twelve °<202>v<193>rs and the three °c<193>ryas laid the foundation ç
for this sect. Among the <193>c<193>ryas, N<193>thamuni†also known ç
as Ra<209>gan<193>tha Muni and Ra<209>ga-n<193>th<193>c<193>rya†was ç
the first. He was the son of ®·varabha<219><219>a and T<193>maraiy<193><202>, ç
and was born in <MS>A.<|>D.<D> 823 at K<193><219><219>umann<193>r Koil ç
(or V<200>ran<193>r<193>ya<207>apura) in the district of South Arcot ç
(near Chidambaram, in Tamil Nadu).
He was a contemporary of the two°<202>v<193>rs: Madhurakavi °<202>v<193>r ç
and Namm<193><202>v<193>r. He is said to have been trained in yoga ç
by the latter.
It was he who collected all the four thousand Tami<202> hymns of the ç
°<202>v<193>rs†now known as Divyaprabandham or N<193>l<193>yira-prabandham†set ç
them to music and got them introduced in Vai<218><207>ava temples ç
as a part of the ritual system. He was ably assisted in this task ç
by his two highly talented nephews, Me<202>aiy<193>gatt<193><202>v<193>r ç
and Ma<207>av<193><202>apperum<193><202> Araiyar who were good musicians.
N<193>thamuni travelled all over the country, especially the pilgrim ç
centres devoted to Vi<218><207>u, and endeavoured to spread <185>r<200>vai<218><207>avism ç
there.
He was the first °c<193>rya (pontiff) of the <185>r<200>vai<218><207>ava ç
sect. He was also in charge of the administration of the Ra<209>gan<193>tha ç
Temple at <185>r<200>ra<209>gam.
He is said to have written three treatises. They are: Ny<193>yatattva, ç
Yoga- rahasya and Puru<218>anir<207>aya.
These works were the guide-books for the later <193>c<193>ryas like ç
Y<193>muna (<MS>A.<|>D.<D> 912-1042), R<193>m<193>nuja (<MS>A.<|>D.<D> ç
1017-1137) and Ved<193>nta De·ika (<MS>A.<|>D.<D> 1268-1369).
See also <MS>°<170>V°RS<D>, <MS>DIVYAPRABANDHAM<D> and <MS><185>R®VAI<186>ØAVISM.<D>
@NT = N<193><219>ya·<193>stra
@N1 = (`science of dramaturgy')
Drama, dance and music have been a very ancient and important aspect ç
of Hindu culture. These three together have been dealt with as a common ç
discipline under the name `n<193><219>ya·<193>stra'.
The earliest systematic treatment of this subject is contained in ç
the N<193><219>ya·<193>stra of Bharata who might have lived during ç
the 2nd or the 3rd century <MS>A.<|>D.<D> Nothing is known of him.
The work probably had 6000 ·lokas or verses distributed in 36 chapters. ç
It has a well-known commentary Abhinava- bh<193>rat<200> of Abhinavagupta ç
which, however, is available only in fragments. Other writers known ç
to have commented upon it are: Bha<219><219>an<193>yaka, Har<218>a, ç
K<200>rtidhara, Lolla<219>a, M<193>t<216>gupt<193>c<193>rya, <185>a<209>kuka ç
and Udbha<219>a.
None of these, however, is available now.
The main subject of this work is dramaturgy. Bharata names ten forms ç
of drama (Da·ar<220>paka). He also develops the theory of rasa in ç
poetics. Figures of speech like upam<193> (comparison or simile), ç
r<220>paka (metaphor), d<200>paka (enlightener) and yamaka (same word ç
with double meaning) are enumerated by him. He also narrates ten gu<207>as ç
(excellences), ten do<218>as (defects) and thirty six lak<218>a<207>as ç
(characteristics) of a poetical composition.
@NT = nauli
One of the <218>a<219>karmas (six purificatory acts), nauli consists ç
in moving the muscles of the belly forcibly from the left to the right, ç
in a wavy fashion. It removes dispep- sia and increases the power ç
of digestion.
However, it is to be learnt and practised under expert guidance.
See also <MS><186>A<187>KARMAS.
@NT = Navadurg<193>s
@N1 = (`the nine Durg<193>s')
Durg<193> is one of the most popular and widely worshipped aspects ç
of the Divine Mother, P<193>rvat<200>. She is†according to the famous ç
work Dev<200>m<193>h<193>tmya†the personification of the essence ç
and powers of all the gods.
Works on the Dev<200>-cult sometimes put forward several varieties ç
of Durg<193>. Nine of these are often grouped together and called ç
`Navadurg<193>s'.
According to the Kavacastotra of the Dev<200>m<193>h<193>tmya, ç
they are: <185>ailaputr<200>, Brahmac<193>ri<207><200>, Candragha<207><219><193>, ç
K<220><218>m<193><207><195><193>, Skandam<193>t<193>, K<193>ty<193>yan<200>, ç
K<193>lar<193>tr<200>, Mah<193>-gaur<200> and Siddhid<193>tr<200>.
As per the Brahm<193><207><195>apur<193><207>a, the list includes: ç
N<200>laka<207><219>h<200>, K<218>ema<209>kar<200>, Harasiddhi,   Vanadurg<193>,   Rudradurg<193>, ç
Agnidurg<193>, Jayadurg<193>, Vindhyav<193>sin<200> and Ripum<193>ridurg<193>.
Iconographically, the main deity is shown with 18 arms (or hands) ç
and the other eight with 16 hands. The various objects shown in the ç
hands are more or less the same as those of the main goddess. Some ç
of them are: ak<218>am<193>l<193> (rosary), khe<219>aka (shield), ç
kha<195>ga (sword), darpa<207>a (mirror), dhanus (bow), b<193><207>a ç
(arrow), dhvaja (banner), tarjan<200>-mudr<193> (pose of warning), ç
·akti (spear), mudgara (hatchet), ·<220>la (lance), cakra (discus), ç
·a<209>kha (conch) and so on.
These  different  aspects  may  be invoked for different purposes.
See also <MS>DEV®M°H°TMYA<D> and <MS>DURG°.<D>
@NT = Navadv<200>pa
@N1 = (`the new island')
This was the birthplace of <185>r<200>k<216><218><207>a Caitanya (<MS>A.<|>D.<D> ç
1486-1533) considered as a combined incarnation of R<193>dh<193> and ç
K<216><218><207>a. He was the founder and pioneer of Be<209>g<193>l ç
Vai<218><207>avism.
Navadv<200>pa has been identified with the modern Nadia. It is a small ç
town situated on the bank of the river Bh<193>g<200>rath<200> (Ga<209>g<193>) ç
at its confluence with the river Jal<193><209>g<200>.
It was a prominent seat of learning during the period <MS>A.<|>D.<D> ç
1198 to 1757, and produced many eminent logicians like Raghun<193>tha, ç
<185>iroma<207>i and others.
It was the capital of the kings of Sen dynasty.
@NT = Navagrahamakha
This is the same as Navagraha·<193>nti.
See <MS>NAVAGRAHA<185>°NTIS<D> for details.
@NT = Navagrahas
@N1 = (`nine planets')
Fo<%18>r<%0>thousands of years, people all over the world have believed ç
in the influence of the planets on human life and history. Logically ç
speaking, the creation of the planets precedes that of the living ç
beings. Hence, some sort of cause and effect relation must subsist ç
between these two. This seems to be the basis for this belief.
The Navagrahas or the nine planets are regarded by the Hindus as of ç
the greatest astrological significance and are believed to influence ç
the life of the individual as also the course of history.
As per the traditional list, the nine planets are Ravi or S<220>rya ç
(sun), Soma or Candra (moon), Ma<209>gala, Kuja or A<209>g<193>raka ç
(Mars), Budha (Mercury), B<216>haspati  or  Guru  (Jupiter),  <185>ukra ç
(Venus), <185>ani (Saturn), R<193>hu and Ketu. The seven days of the ç
week have derived their names from the first seven planets. R<193>hu ç
and Ketu are not planets but ascending and descending nodes of the ç
moon. Sometimes Ketu is depicted as the personification of comets ç
and meteors.
<185>ani, R<193>hu and Ketu are considered inauspicious, even positively ç
maleficent, and responsible for children's diseases. Hence they need ç
to be propitiated.
The nine planets are invariably found in every <185>aiva temple in ç
South India. In many North Indian temples they are depic- ted on the ç
lintels of doors, to protect the temple and all those who enter it. ç
They may also be housed in a separate Ma<207><195>apa (a small pavilion) ç
or at least a platform where the images of these nine Grahas are installed ç
in such a way that no two of them will face each other. It is sometimes ç
stated that the images of the planets are set up in the temples in ç
the order in which they are in zodiacal circle at the time of construction ç
of the temple.
@SPACE1 = 
The image of S<220>rya must always be placed in the centre of the ç
planets, facing east, with the other Grahas fixed round him, each ç
in a specified direction. He has two hands, holding a lotus in each. ç
His chariot has one wheel, is drawn by seven horses and has Aru<207>a ç
(deity of the dawn) as the charioteer.
Soma or Candra has only a face and two hands but no body. He is shown ç
holding white lotuses in his two hands. He rides on a two or three ç
wheeled chariot drawn by ten horses.
Ma<209>gala or Kuja has four hands, carrying the weapons mace and ç
javelin in two, showing the varada and abhaya mudr<193>s with the ç
other two. He rides on a ram.
Budha also has four hands, three of them wielding the weapons sword, ç
shield and mace. The last hand shows the varadamudr<193>. He rides ç
on a lion or a chariot drawn by four horses.
B<216>haspati being the Guru, is shown holding a book and a rosary ç
in his two hands. His chariot is golden and is driven by eight horses. ç

<185>ukra is also seated in a golden chariot drawn by eight horses ç
or in a silver one drawn by ten horses. He has two hands holding a ç
nidhi (= treasure) and a book. Sometimes he is shown with four hands ç
holding the staff, rosary and water-pot, the fourth exhibiting the ç
varadamudr<193>.
<185>ani rides in an iron chariot drawn by eight horses. He is more ç
often shown as riding on a vulture. A buffalo also may be his mount. ç
He holds the arrow, bow and javelin in three of his hands, the last ç
hand being in the varadamudr<193>.
@SPACE1 = 
R<193>hu is usually described as having only a face and Ketu is depicted ç
like a serpent's tail. Iconographical works, however, describe them ç
differently.
R<193>hu may be shown riding a black lion or as seated on a si<221>h<193>sana ç
(throne) or in a silver chariot drawn by eight horses. He may have ç
two hands, the right hand carrying a woollen blanket and a book, the ç
left hand being shown empty. If four hands are shown, they carry sword, ç
shield and lance, the fourth one being in varadamudr<193>.
Ketu has an ugly face and rides on a vulture. In his two arms he exhibits ç
a mace and the varadamudr<193> or abhayamudr<193>.
All the grahas have crowns and ear- rings. The eight grahas round ç
the Sun always face him.
The planets are sometimes described as having connection with the ç
incarnation of Lord Vi<218><207>u.
@NT = Navagraha·<193>ntis
@N1-1 = (`appeasement rites for the nine planets')
That the various planets circling round the sun in our solar system, ç
have an effect on the lives of the living beings here, is a belief ç
shared by many peoples of this earth, throughout the history of mankind. ç
A holistic approach, engendered by holistic sciences, is also lending ç
credence to such beliefs.
The Hindu scriptures have recognised this factor since the most ancient ç
times.If and when a particular planet is unfavourably placed, as ç
indicated by the horoscope of the person, certain religious rites ç
known as `·<193>ntis' have to be performed, to offset, or at least ç
minimise, these effects. Out of these, the Navagraha·<193>nti†also ç
called `Navagraha-makha'†is also one and has been considered as a ç
prak<216>ti or a model for other types of ·<193>ntis.
Sometimes the Navagraha·<193>nti, identified with Navagrahamakha, ç
is said to be of three types: ayutahoma, lak<218>ahoma and ko<219>ihoma, ç
wherein the oblations into the duly consecrated fire are ten thousand, ç
one lakh and one crore.
The Navagraha·<193>nti should be offered to the image of the nine ç
planets made out of nine different kinds of materials (like copper, ç
crystal, red sandalwood etc.) or to the pictures of the nine planets ç
drawn with sandalwood paste on a piece of cloth. The mantras used ç
in the rites are usually from the Vedas (e.g., <184>gveda 1.35.2; ç
V<193>jasaney<200> Sa<221>hit<193> 9.40; Taittir<200>ya Sa<221>hit<193> ç
4.7.13.5).
Homa to each planet is done with samidh (fuel sticks) anointed with ç
honey or ghee, the number being 108, or 28. The br<193>hma<207>a priests ç
performing the ·<193>nti must be suitably rewarded.
Special gifts are to be made when any planet is unfavourably placed. ç
The Navagraha·<193>nti itself can be performed at the beginning of ç
all auspicious or important occasions like the sa<221>sk<193>ras (sacraments), ç
going on a pilgrimage, before a battle and so on.
@SPACE = 
@NT = Navagva
@N1 = (`those who have completed it in nine [months]')
@SPACE = 
One of the Saptar<218>is or the Seven Sages is A<209>giras. Among ç
the descendants of A<209>giras†known as °<209>girasas†those who performed ç
a Sattray<193>ga (which normally needs twelve months to complete) ç
and attained what they wanted in nine months were called `Navagvas' ç
and those who got the results in ten months, were called `Da·agvas' ç
(vide <184>gveda 1.62.4).
Sometimes the Navagvas and the Da·agvas themselves are identified ç
with the Saptar<218>is.
They are supposed to live in the pit<216>loka (world of manes) and ç
accept the obsequial offerings.
@SPACE = 
@NT = nav<193>nna
@N1 = (`[ceremony of offering] cooked rice [from] the new crop')
@SPACE1 = 
@SPACE1 = 
Every act in a Hindu's life is, somehow or the other, to be connected ç
with God and religion. The `nav<193>nna' is one such.
When paddy is harvested, the rice got out of it should first be offered ç
to God and living beings before using it. This ceremony of offering ç
cooked rice is called `nav<193>nna' and is generally done in themonth ç
of Agrah<193>ya<207>a or M<193>rga·ira (December-January). Performance ç
of ·r<193>ddhas and feeding birds and animals are a part of this.
See also <MS>°GRAYAØA<D> and <MS> MAKARA-SA<177>KR°NTI.
@SPACE = 
@NT = Navar<193>tra
@N1 = (`[festival of] nine nights')
@SPACE1 = 
@SPACE1 = 
`Navar<193>tra' means a period of nine nights, or for that matter, ç
a period of nine days. Two Navar<193>tras are mentioned in the pur<193><207>as ç
and the dharma·<193>stras, as being highly auspicious for the worship ç
of <185>akti or the Divine Mother Durg<193>. They are: Vasantanavar<193>tra, ç
the first nine days in the Vasanta <216>tu or spring, from Caitra ç
·ukla pratipad up to navam<200>; <185>arannavar<193>tra, the first ç
nine days in the <185>arad<216>tu or autumn, from °·vayuja ·ukla pratipad ç
to navam<200>. However, in practice, the celebration of the former ç
has yielded its place almost completely to the latter.
Though this Navar<193>tra is celebrated all over the country in some ç
form or the other, it is the Durgotsava or the festival of Mother ç
Durg<193> that steals the show.
Celebration of the Navar<193>tra festival varies from place to place ç
in other parts of the country. In South India, goddess Sarasvat<200> ç
is worshipped on the saptam<200> day and Durg<193> on the a<218><219>am<200>. ç
The worship is done in the picture and not in clay images as in Bengal. ç
The navam<200> day, called `Mah<193>navam<200>', is celebrated as ç
°yudhap<220>j<193>, the instruments and implements that help us to ç
earn our livelihood being worshipped then. This is akin to the Vi·vakarmap<220>j<193> ç
performed in the North, during the month of Bh<193>drapada when Ravi ç
(the Sun) enters the zodiacal sign of Kany<193> (Virgo). In almost ç
all the homes, there will be display of dolls with decorations. This ç
is a special attraction for children.
In several parts of North India, especially in the Hindi belt, Navar<193>tra ç
is celebrated as R<193>mal<200>l<193>. Recitations from the R<193>m<193>ya<207>a, ç
enacting plays based on the several episodes of the epic and processions ç
culminating in the burning of the effigies of R<193>va<207>a, Kumbhakar<207>a ç
and Meghan<193>da on the da·am<200> day (also called Vijayada·am<200>) ç
are the salient features of these celebrations.
In the Mysore City of Karnataka, the Dasara festival celebrated during ç
the Navar<193>tra, has been very famous. It was a royal festival celebrated ç
by the Mah<193>r<193>j<193> (King) of Mysore, ending with a grand ç
procession on the Vijayada·am<200> day.
@SPACE1 = 
Now-a-days, an image of C<193>mu<207>-<195>e·var<200> (an aspect of ç
Durg<193>) is taken out in procession.
@NT = navat<193>la
@EMERGEN1 = See <MS>M<188>RTI<185>ILPA<185>°STRA<D>.
@NT = Navyany<193>ya
@EMERGENCY = The Ny<193>ya Dar·ana or the Ny<193>ya school of Hindu ç
philosophy has provided a strong basis and framework for Hindu logic.
A new school of Ny<193>ya philosophy under the name `Navyany<193>ya' ç
began with the writings of Ga<209>ge·a Up<193>dhy<193>ya (<MS>A.<|>D.<D> ç
1200) of Mithil<193> (in Bihar) and his successors. He wrote a work ç
called Tattva- cint<193>ma<207>i wherein he has dwelt with only ç
the four pram<193><207>as or means of knowledge, viz., pratyak<218>a ç
(direct perception), anu-m<193>na (inference), upam<193>na (comparison) ç
and ·abda (verbal testimony). He did not touch the prameya (objects ç
to be known) at all.
@EMERGENCY = Somehow this work of his attracted an  unusually  great  attention  of  the ç
scholars, first at Mithil<193> and later at Navadv<200>pa of Bengal.
@EMERGENCY = Raghun<193>tha <185>iroma<207>i (<MS>A.<|>D.<D> 1500), ç
Mathur<193> Bha<219><219><193>c<193>rya (<MS>A.<|>D.<D> 1580), Gad<193>-dhara ç
Bha<219><219><193>c<193>rya (<MS>A.<|>D.<D> 1650) and Jaga-d<200>·a ç
Bha<219><219><193>c<193>rya (<MS>A.<|>D.<|><D>1590) were the chief commentators ç
of this work of Ga<209>ge·a.
@EMERGENCY = Later on, several sub-commentaries on the commentary ç
of Raghun<193>tha <185>iroma<207>i arose, along with independent works ç
on the same object, thus enriching the Navya-ny<193>ya literature.
@EMERGENCY = The contribution of Navya-ny<193>ya was mainly in the ç
direction of developing a system of linguistic notations to specify ç
accurately and precisely, any concept. The other aspects of Ny<193>ya ç
Dar·ana were practically untouched.
See also <MS>GA<177>GE<185>A.<D>
@NT = N<193>yan<193>rs
@N1 = (`lords,' `servants of the Lord')
@EMERGENCY = The Bhakti Movement†the religious movement that upheld ç
the superiority of bhakti or devotion to God, as the simplest and ç
the easiest mode of s<193>dhan<193> or spiritual practice†saved Hinduism ç
from the labyrinth of Vedic rituals and the Hindu society from being ç
demographically wiped out.
@EMERGENCY = The °<202>v<193>rs (Vai<218><207>ava saints) and the ç
N<193>yan<193>rs (also spelt as `N<193>yanm<193>rs') (<185>aiva saints), ç
both belonging to the Tamil Nadu, were the leading lights of this ç
movement in South India, during the period 7th and 8th centuries <MS>A.<|>D.<D>
@EMERGENCY = The N<193>yan<193>rs are 63 in number. They came from ç
all castes and all levels of the Hindu society and included quite ç
a few women-saints too.
Their main contributions were: off-setting the effects and spread ç
of Jainism and Buddhism which had become more of a heretical movement ç
than of true ethics and spiritual values; vigorously propagating the ç
cult of devotion to God as <185>iva; transcending all social barriers ç
brought about by caste, wealth or power, through devotion to God as ç
the sole means of estimating the worth of a human being; and, development ç
of chaste Tamil literature.
@EMERGENCY = A comprehensive account of all the 63 N<193>yan<193>rs ç
is given in the celebrated Tamil  classic,  the  Periyapur<193><207>am ç
 of Sekkizh<193>r (12th century <MS>A.<|>D.<D>), which contains 4000 ç
verses.
@EMERGENCY = The more important and better known N<193>yan<193>rs ç
are: J<210><193>nasambandhar, Appar (or Tirun<193>vakkarasar). Sundara-m<220>rti ç
and Tirun<200>laka<207><219>har.
The philosophy and religion of the N<193>yan<193>rs was primarily ç
based on the <185>aivasiddh<193>nta.
The Tev<193>ram, compositions of Appar, Sundaram<220>rti and J<210><193>nasambandhar, ç
are chanted or sung in the <185>iva temples of Tamil Nadu even today.
The N<193>yan<193>rs advised their followers to give five kinds of ç
gifts: <193>h<193>ra (food), bhai<218>ajya (medical relief), abhaya ç
(protection from fears and dangers), ·<193>stra (religious instructions), ç
and d<193>na (presents of articles needed by the poor people).
In the R<193>jar<193>je·var<200> temple of Ta<210>j<193>-v<220>r, ç
there are relief figures depicting some incidents from the lives of ç
a few of these N<193>yan<193>rs. Their images are found in the Na<210>ju<207><195>e·vara ç
temple at Na<210>janag<220><195>u in the Mysore district of Karnataka.
@NT = Neo-Ved<193>nta
@N1 = (`new Ved<193>nta')
Ved<193>nta, the philosophy of the Prasth<193>natraya†the three basic ç
works viz., the Upani<218>ads, the Brahmas<220>tras and the Bhagavadg<200>t<193>†has ç
branched off into several sub-systems. The teachings of R<193>mak<216><218><207>a ç
and Vivek<193>nanda have tried to synthesise these systems into one ç
coherent philosophy. This is generally called `Neo-Ved<193>nta'.
See <MS>R°MAK<184><186>ØA<D> and <MS>VIVEK°NANDA<D>.
@NT = neti
Works on Ha<219>hayoga like the Ghera<207><195>a Sa<221>hit<193> ç
describe certain processes of cleansing the body internally, to make ç
it healthy and strong so that it becomes fit for s<193>dhan<193> or ç
spiritual practice. These are generally grouped under one title, the ç
`<186>a<219>karmas', or the `six processes'. Neti is one of them and ç
the third in the list.
It is performed by inserting a thin thread of soft cotton, about 6 ç
inches long, into the nostrils, passing it through and pulling it ç
out by the mouth (Ghera<207><195>a Sa<221>hit<193> 1.50).
Of course, this has to be done under expert supervision. 
See also <MS><186>A<187>KARMAS.<D>
@NT = netronm<200>lana
@N1 = (`opening the eyes')
See <MS>AK<186>IMOCANA.<D>
@NT = nibandhas
@N1 = (`digests')
See <MS>DHARMA<185>°STRAS.<D>
@NT = nidhana
@N1 = (`finale')
In Somay<193>gas like the Agni<218><219>oma, certain mantras of the ç
S<193>maveda†called `s<193>mans'†have to be chanted musically. Such ç
s<193>mans have five parts: prast<193>va, udg<200>tha, pratih<193>ra, ç
upadrava and nidhana. These are respectively chanted by the following ç
priests: prastot<216>, udg<193>t<216>, pratihart<216>, udg<193>t<216> ç
and all the three together.
Nidhana, the last, contains interjections like s<193>t, s<193>m, suv<193><199>, ç
i<195><193>, v<193>k and<193>.
A bundle of grass, a handful (= mu<218><219>i) in quantity, to be ç
spread on the vedi (sacrificial altar) is also called `nidhana'.
The common meaning of the word is `death'.
See also <MS>S°MAN.<D>
@NT = nidhikumbha
@N1 = (`pot of wealth')
Building a Hindu temple is not only a sacred act but also a complicated ç
affair. The most important part of it is the<218>a<195><193>dh<193>raprati<218><219>h<193> ç
(fixing up of six supports) inside the garbhag<216>ha or the sanctum.
The nidhikumbha (or nidhikala·a) is the second of these six and is ç
placed above the <193>dh<193>ra·il<193> (the base stone). It contains ç
several objects like nine precious stones, several metals and minerals, ç
herbs and soils, symbolising creation and prosperity.
See also <MS><186>A£°DH°RAPRATI<186><187>H°.
@NT = nididhy<193>sana
@N1 = (`meditation')
This is the term specially used in Ved<193>nta to signify meditation. ç
It has been defined as the stream of ideas of the same kind as Brahman ç
to the exclusion of allother ideas like those of the body. Ultimately ç
it leads to sam<193>dhi or total absorption in Brahman.
@NT = Nidr<193>, nidr<193>
@N1 = (`Goddess of sleep', `sleep')
The Pr<193>dh<193>nikarahasya (10), a supplementary text of the ç
Dev<200>m<193>h<193>tmya describes Nidr<193> as a goddess and an ç
aspect of Mah<193>k<193>l<200>. Iconographical works show her as a ç
lady reclining on a couch.
Some texts like the Lak<218>m<200>tantra state that Nidr<193> is ç
one of the four consorts of Vi<218><207>u, the other three being Lak<218>m<200>, ç
Pr<200>ti and Vidy<193>.
Other texts picture her as the wife of K<193>l<193>gnirudra, an aspect ç
of Rudra or <185>iva.
The word `nidr<193>' is most commonly interpreted as `sleep'. This ç
nidr<193> has two aspects: svapna (with dreams) and su<218>upti (dreamless ç
sleep or deepsleep).
Pata<210>jali (200 <MS>B.<|>C.<D>) defines nidr<193> (vide Yogas<220>tras ç
1.10) as the v<216>tti or the modification of mind dependent on tamas ç
(darkness or ignorance), which is responsible for the absence of the ç
waking (j<193>grat) and the dream (svapna) states. It is actually ç
deep (dreamless) sleep that is indicated here.
Nidr<193> is needed for the health of thebody. When the three dhatus ç
(basic humours of the body) are in a state of equilibrium, good health ç
is attained; and, sound sleep at the right time is an aid to this.
Whereas good sleep is denied to those who are stricken with poverty ç
or disease or to the immoral persons, it comes easily to healthy persons ç
as also who are pure in heart.
Yogic works describe that sleep overtakes a person when his mind enters ç
the medhy<193>n<193><195><200>, one of the several n<193><195><200>s ç
in the human body.
The M<193><207><195><220>kyak<193>rik<193> (3.44,<|>45) consi-ders ç
sleep†called `laya' here†as one of the four obstacles to sam<193>dhi.
The Su·rutasa<221>hit<193> (<185><193>r<200>rasth<193>na 4.32) ç
says that the h<216>dayapu<207><195>ar<200>ka (heart-lotus) closes ç
and hangs upside down during sleep.
A funny story in one of the pur<193><207>as reveals that R<193>ma ç
gave the boon to Nidr<193>, the goddess of sleep (after she left Kumbhakar<207>a ç
who was killed by R<193>ma) to reside in the hearts of those evil ç
persons who try to listen to R<193>m<193>n<193>ma or the pur<193><207>as, ç
and in lazy students not interested in the acquisition of knowledge!
@NT = nigada
@N1 = (`that which is uttered loudly')
The Vedic mantras used in y<193>gas or sacrifices are of four types: ç
<216>k, yajus, s<193>man and nigada.
The <216>ks are metrical compositions. The yajus are complete sentences ç
in prose. The s<193>mans are set to music and sung.
The nigadas†also called `prai<218>as'† are words addressed by one ç
priest (generally the adhvaryu) to another, loudly, calling on the ç
latter to do a certain thing.For example: `prok<218>a<207><200>r ç
<193>s<193>daya,' `Approach the vessel containing the holy waters.'
They are, in one sense, yajus, but distinguished from them; since ç
they are uttered loudly whereas the yajus mantras are recited softly.
@NT = nigama
@N1 = (`that by which [truth is known] clearly')
The word `nigama' has been used in several senses in the Hindu scriptures. ç
Since the highest Truth is known or understood properly (`nitar<193><221> ç
gacchanti anena') through the Vedas, they are known as `Nigama'. So ç
also are the sentences of command contained in them.
A definite conclusion established after countering all objections ç
is also called `nigama' or `nigamana' in the science of logic, which ç
is also, sometimes, named `nigama'.
In a more technical sense, the word `<193>gama' is used for those ç
t<193>ntrik works where Sad<193>·iva teaches Dev<200> and the word ç
`nigama' for the works wherein the Dev<200> teaches Sad<193>·iva.
@NT = nigamana
@N1 = (`final conclusion')
The theory of knowledge developed in the Ny<193>ya Dar·ana or the ç
Ny<193>ya philosophy has contributed considerably to Hindu systems ç
of logic.
@SPACE1 = 
While dealing with anum<193>na or inference, the second of the four ç
pram<193><207>as accepted by it, the Ny<193>ya philosophy puts forward ç
a five membered syllogism of which nigamana is the fifth. They are: ç
pratij<210><193> (first proposition asserting something); het<%22>u<%0>(reason); ç
ud<193>hara<207><%22>a<%0>(example); upanaya (application of the universal ç
to the particular case); nigamana (final conclusion, reasserting the ç
first proposition).
This can be made clear from the following illustration<|>:
@NO = 1.
@NOK = Devadatta is a mortal. (pratij<210><193>)
@NO = 2.
@NOK = Because he is a human being. (hetu)
@NO = 3.
@NOK = All human beings are mortal. Fo<%26>r<%0>e.g., A·oka, <185>r<200>har<218>a, ç
K<193>lid<193>sa, Tuk<193>ram and so on. (ud<193>hara<207>a)
@NO = 4.
@NOK = Devadatta is also a human being. (upanaya)
@NO = 5.
@NOK = Therefore he is mortal. (nigamana)
@NT = Nigam<193>nta De·ika
See <MS>VED°NTA DE<185>IKA.<D>
@NT = Nigha<207><219>u
@N1KERN = (`that which explains the words,' `dictionary')
Hindu religious tradition declares that all words†including the words ç
of our daily life and usage†have been derived from the Vedas. As the ç
volume of the Vedas grew through new revelations, there arose the ç
need for proper and correct understanding of the words and phrasesby ç
which the Vedic rituals could be performed properly. Then alone, the ç
results predicated could be attained.
This need led to the compilation of the Nigha<207><219>u or the ç
first Vedic Lexicon. This work commands the same respect astowards ç
the Vedas themselves. The compiler is not known.
@SPACE1 = 
Y<193>ska's commentary on it (800<MS><|>B.C.<D>)† known as the Nirukta†is ç
available even now.  Another  known  as  Nigha<207><219>u- nirvacana ç
by Devar<193>ja Yajvan (12th cent. <MS>A.D.<D>) is also available. ç
This work purports to supply additional material on the Nigha<207><219>u.
