The Nigha<207><219>u has five adhy<193>yas or chapters. The first ç
three are known as the Naigha<207><219>uka K<193><207><195>a, the ç
fourth as the Naigama K<193><207><195>a and the last as the Daivata ç
K<193><207><195>a.
The Naigha<207><219>uka K<193><207><195>a deals with synonyms, the ç
total numbers of words being 1341.
The Naigama K<193><207><195>a deals with homonyms (ekapadi) whose ç
number comes to 278.
The Daivata K<193><207><195>a deals with the names of deities in ç
the three regions<%20>:<%0>earth, sky and heaven. They total up to ç
151.
This takes the grand total of the words of the Nigha<207><219>u ç
to 1770.
The topics include: physical elements like the earth, water and air; ç
objects of nature like clouds, dawn, day and night; the human body ç
and its limbs; objects and qualities associated with people, such ç
as prosperity, anger and fighting; physical abstract  qualities  like  lightness  and ç
heaviness.
If the word `nigha<207><219>u' is understood in a more general way ç
as a `dictionary,' the  following  Sanskrit-Sanskrit  dictionaries ç
may be mentioned:
@SPACE1 = 
@NO = 1.
@NOK = Amarako·a of Amarasi<221>ha, also called N<193>mali<209>g<193>nu·<193>sana ç
(<MS>A.<|>D.<D> 500).
@NO = 2.
@NOK = Anek<193>rthasamuccaya of <185><193>·vata<R>ç
(6th cent. <MS>A.<|>D.<D>).
@NO = 3.
@NOK = Anek<193>rthadhvanima<210>jar<200> of<R>ç
Mah<193>k<218>apa<207>aka (<MS>A.<|>D.<D> 900).
@NO = 4.
@NOK = Vaijayant<200>ko·a of Y<193>davaprak<193>·a.<R>ç
(<MS>A.<|>D.<D> 1100).
@NO = 5.
@NOK = Abhidh<193>naratnam<193>l<193> of Hal<193>yudha<R>ç
(<MS>A.<|>D.<D> 950) more popularly known as the Hal<193>yudhako·a.
@NO = 6.
@NOK = N<193>n<193>rtha·abdako·a (Medin<200>ko·a) by Medin<200>kara ç
(<MS>A.<|>D.<D> 1100).
Nigha<207><219>us or dictionaries dealing with special topics like ç
botany and medicine were also composed in later times.
@NT = nigrahasth<193>na
@N1 = (`ground of defeat')
It means a ground of defeat in a debate. The two primary grounds of ç
such a defeat are: misunderstanding or wrong understanding; want of ç
understanding.
If any party in a debate fails to understand or misunderstands his ç
own or the other party's statement, as also its implication, he is ç
brought to the point at which he has to admit defeat. Shifting of ç
the original proposition or the use of fallacious arguments can lead ç
to defeat.
@NT = N<200>laka<207><219>ha
@N1 = (`one whose neck is blue')
In the paur<193><207>ic accounts of Samudra-mathana or the churning ç
of the ocean of milk, <185>iva is said to have gathered the poison ç
h<193>l<193>hala into his palm and drunk it. P<193>rvat<200>, his ç
spouse, pressed his throat so that the poison would not get into his ç
stomach and destroy the worlds there. This poison stuck in his throat ç
rendering his neck blue in colour. Hence <185>iva came to be known ç
as `N<200>laka<207><219>ha,' `one whose neck is blue'.
N<200>laka<207><219>ha is also the name of a <185>aiva scholar from ç
Maharashtra. He probably flourished in the middle of the 18th century. ç
About six works are attributed to him, of which his commentaries on ç
the Dev<200>bh<193>gavata and the K<193>ty<193>yan<200> Tantra ç
are well-known.
A few more N<200>laka<207><219>has have been known to the students ç
of the dharma-·<193>stras  as  authors  of  various  topics connected ç
with the same.
@NT = N<200>laka<207><219>ha Bha<219><219>a
See <MS>BHAGAVANTA-BH°SKARA.<D>
@NT = N<200>laka<207><219>ha Caturdhara
The Mah<193>bh<193>rata, one of the two great epics of Hinduism, ç
has a well-known commentary called Bh<193>ratabh<193>vad<200>pa ç
by N<200>laka<207><219>ha Caturdhara. He was a descendent of one Lak<218>ma<207><193>rya, ç
N<193>r<193>ya<207>a and Dh<200>re·a being two more distinguished ç
ancestors of his.
He probably lived around <MS>A.<|>D.<D> 1400.
@NT = N<200>laka<207><219>ha D<200>k<218>ita
A famous and versatile author who enriched Sanskrit literature, N<200>laka<207><219>ha ç
D<200>k<218>ita was the grandson of Acc<193>n D<200>k<218>iata who ç
was a brother of another genius, Appayya D<200>k<218>ita (<MS>A.<|>D.<D> ç
1520-1592). He lived in the 17th century.
Born as the son of N<193>r<193>ya<207>a D<200>k<218>ita and Bh<220>midev<200> ç
at A<195>ipala Agrah<193>ra near the modern K<193><210>c<200>puram ç
(in Tamil Nadu), he acquired stupendous scholarship in several branches ç
of learning like M<200>m<193><221>s<193>, Ved<193>nta, Vy<193>kara<207>a ç
(grammar) and <185>aivism.
His most famous work was N<200>la-ka<207><219>ha-vijaya-camp<220>. ç
Some of his other works are: <185>ivatattvarahasya, <185>ival<200>l<193>r-<207>ava,   Ga<209>g<193>vatara<207>a,   <185><193>ntivil<193>sa, ç
°nandas<193>garastava, Nalacarita and Vair<193>gya·ataka.
The  first  of  these  works  has expounded the Advaita Ved<193>nta ç
very well.
@NT = N<200>l<193>k<218>a-nakula
@N1 = (`the blue-eyed<R>ç
mongoose')
After the performance of the A·va-medha sacrifice, king Yudhi<218><219>hira, ç
the eldest of the P<193><207><195>avas, was puffed up with pride.
Suddenly, there appeared in the Y<193>ga·<193>l<193> (sacrificial ç
shed) a big mongoose with blue eyes, half of whose body had become ç
golden. It rolled on the ground where there were scattered grains ç
but seemed to be disappointed, since the other half too did not turn ç
golden as it had hoped for. Then it spoke, like a human being, disparagingly ç
of Yudhi<218><219>hira's so-called great sacrifice, comparing it with ç
the sacrifice with life of a whole br<193>hma<207>a family out of ç
hunger, after everyone of them gave away his or her share of food ç
to hungry souls who begged for the same. Accidental contact of the ç
body of the mongoose with a small portion of the left- over food in ç
the br<193>hma<207>a's house had turned that half of its body into ç
golden colour! Since that day the mongoose was trying to convert the ç
other half of its body also into golden colour by visiting places ç
where great sacrifices were being performed.
Naturally, Yudhi<218><219>hira was humbled.
See Mah<193>bh<193>rata (°·vamedhikaparva, Ch. 90).
@NT = N<200>lapur<193><207>a
If the number and the titles of the Mah<193>pur<193><207>as are fairly ç
well-settled, those of the Upapur<193><207>as are not.
One of the Upapur<193><207>as, not listed among the traditional ones, ç
but quoted by the writers of dharma·<193>stras is the N<200>la or ç
the N<200>lamatapur<193><207>a.
Though mentioned only in the R<193>ja-tara<209>gi<207><200> of Kalha<207>a ç
(12th cent. <MS>A.<|>D.<D>), it is a very interesting work, throwing ç
a lot of light on the various aspects of Kashmir, like  its  history,  legendary  lores  and ç
topography.
While dealing with the D<200>p<193>val<200> festival, it calls the ç
°·vina-am<193>v<193>sy<193> (the new-moon day of the month of °·vina, ç
in November) as `<185>ukhasuptik<193>' and gives a grand, detailed ç
description of its celebration. Fasting during the day, decorating ç
temples with a long series of oil lamps, dressing oneself in new clothes ç
and giving a good feast to the br<193>hma<207>as are the methods given ç
for celebrating this festival.
@NT = N<200><202><193>s<220>kta
This short s<220>kta appears in the Taittir<200>ya Sa<221>hit<193> ç
(4.4.12). It is on N<200><202><193>dev<200>, the third consort of ç
Vi<218><207>u. She is identified with Aditi, the mother of all gods.
She is the personification of karu<207><193> (compassion and grace) ç
of God. She is also the power that manifests through S<220>rya (the ç
Sun), Candra (the Moon) and Agni (the Fire).
A brief summary of the s<220>kta may now be given:
I take refuge in N<200><202><193>dev<200>. O goddess! Please speak!
O God, who is the supreme creator! That goddess who is the firm refuge ç
of the devotees, who is the consort of Vi<218><207>u, who is compassionate, ç
who is the mistress of the universe, the repository of all types of ç
strength and power, who is worshipped by the living beings in their ç
minds, who grants all the objects of enjoyment, may that deity give ç
us lordship and bless us with bliss.
May B<216>haspati (the guru of the gods), V<193>yu (the god of wind), ç
the pr<193><207>as (life forces) in the body, and N<200><202><193>dev<200> ç
who is the supporter of the quarters and the earth, who is the mistress ç
of the world and a consort of Vi<218><207>u, preach to us what is ç
good for us!
Iconographical works, following the P<193><210>car<193>tra tradition, ç
describe N<200><202><193> or N<200><202><193>dev<200> as dark-blue ç
in complexion, like the blue-lotus. She is clothed in blue garments ç
and richly bedecked with ornaments. In her four hands she holds two ç
lotuses in two, the other two exhibiting the abhaya and varada mudr<193>s, ç
mudr<193>s assuring freedom from fear and giving boons.
@NT = nimantra<207>a
@N1 = (`invitation')
See <MS>°MANTRAØA.<D>
@NT = Nimb<193>rka
@N1 = (12th cent. <MS>A.<|>D.<D>)
Nimb<193>rka was a well-known teacher of Ved<193>nta who advocated ç
a balanced combination of bhakti (devotion to God) and j<210><193>na ç
(knowledge) like R<193>m<193>nuja (<MS>A.D.<D> 1017-1137) and Madhva ç
(<MS>A.<|>D.<D> 1238-1317). Though his date of birth is not known, ç
he is known to have passed away in <MS>A.D.<D>1162.
He was born of Jagann<193>tha and Sarasvat<200>, a Telugu-speaking ç
couple who lived at Nimb<193>pura (now identified with Naidu Pattana) ç
in the Bellary district of Karnataka State. His original name was ç
Niyam<193>nanda. His followers consider him as the incarnation of ç
Sudar·ana (discus of Lord Vi<218><207>u).
According to one legend, he was given the name `Nimb<193>rka' by a ç
sa<221>ny<193>sin who accepted food in his house after sunset, thinking ç
it was still daytime, since Nimb<193>rka through his devotion and ç
prayers to Lord <185>r<200>k<216><218><207>a had created that illusion ç
through the Sudar·ana discus which shone in the western horizon like ç
the sun! The sa<221>ny<193>sin was able to see the sun (= arka) from ç
atop a nimba (neem) tree! After learning the truth, the sa<221>ny<193>sin ç
gave him this name (`Nimb<193>rka').
He migrated to V<216>nd<193>ban (in the Mathura district of Uttar ç
Pradesh) and lived the rest of his life there.
He had many disciples and followers, both ascetics and householders. ç
Out of them Harivy<193>sadeva (15th cent. <MS>A.<|>D.<D>) and Ke·ava ç
K<193>·m<200>rin were more well-known.
His magnum opus is Ved<193>ntap<193>rij<193>ta Kaustubha, a brief ç
and clear commentary on the Brahmas<220>tras. The Da·a·lok<200> ç
(alsocalled Siddh<193>ntaratna), a small work of ten verses expounding ç
the author's doctrine for the tyros, is also attributed to him.
Wearing of the gop<200>candana as two perpendicular lines on the forehead ç
with a dark dot in the centre as also carrying a rosary of tulas<200> ç
beads is the hallmark of Nimb<193>rka's followers.
His philosophy is now well-known as Dvait<193>dvaita.
See <MS>BRAHMAS<188>TRAS<D> (<MS>NIMB°RKA<D>) for details.
@NT = nimitta
@N1 = (`sign,' `indication')
In the most general sense, it means a `cause'. In the Ved<193>nta, ç
the two terms normally  used  are  `up<193>d<193>na-k<193>ra<207>a' ç
(material cause, like clay for the pot) and `nimitta-k<193>ra<207>a' ç
(efficient cause, like the potter).
In the paranormal sciences, the two words commonly used are `nimitta' ç
and `utp<193>ta'. Though both indicate portents, the latter stands ç
for the evil ones whereas the former stands for both good and evil.
Throbbing of a person's limbs like eye-brows or shoulders is an example ç
usually cited.
@NT = nimittak<193>ra<207>a
@N1 = (`efficient cause')
See <MS>NIMITTA.<D>
@NT = n<200>r<193>jana
@N1 = (`[waving of] water or light')
Ritualistic worship of God in and through an icon (either at home ç
or in a temple) is a common feature in Hinduism. The various upac<193>ras ç
(items of honour) are a part of this. They remind one of the way one ç
has to receive an important guest visiting one's house.
Such upac<193>ras may be five (pa<210>copa-c<193>ras), ten (da·opac<193>ras) ç
or sixteen (<218>o<195>a-·opac<193>ras). In all these, waving of a ç
lighted lamp called `n<200>r<193>jana,' is a must. It may be of burning ç
karp<220>ra (camphor) or cotton wicks dipped in ghee or oil, their ç
number being 3 or 5 or 7.
Some <193>gamas declare that by such waving of light, one's life and ç
happiness increase and all evil beings are driven out.
Sometimes, coloured water kept in a shallow plate is waved before ç
a sick person, to ward off the evil forces that might have caused ç
the disease. This is also called `n<200>r<193>jana' (n<200>ra = water).
@NT = nirayana
@N1 = (`neglecting the precession of the equinoxes')
An equinox is the point where the sun crosses the plane of the earth's ç
equator. There are two equinoxes: the vernal equinox (on March 21) ç
and the autumnal equinox (on September 22). On these two days, the ç
length or the duration of the day and the night are exactly equal.
In the traditional Hindu calendars (called `pa<210>c<193><209>gas') ç
the precession of the equinoxes (due to the wobbling movement of the ç
earth) is not taken into account. Hence this system of calculation ç
is known as nirayana whereas, if taken into account, it is called ç
s<193>yana.
Though the actual date of the vernal equinox at present is 21st March, ç
it is considered as 13th April ignoring the precession.
In order to remove this anomaly, the National Calendar (as recommended ç
by the Calendar Reform Committee) was adopted in 1957. March 22 was ç
reckoned as the 1st Caitra, <185>aka-era 1879. The duration of the ç
year adopted for calculations taking the ayana or precession into ç
account (hence `s<193>yana') was 365.2422 days.
@NT = nirb<200>jasam<193>dhi
@N1 = (`sam<193>dhi in which the seed of rebirth is destroyed')
This is a term specially used in the Yogas<220>tras (1.51) of Pata<210>jali ç
(200 <MS>B.<|>C.<D>).
The chief reason for sa<221>s<193>ra or transmigration is the impurity ç
of the mind. These impurities, through their sa<221>sk<193>ras or ç
tendencies carried over many births, impel the mind to constantly ç
rise in the form of v<216>ttis or modifications, preventing a vision ç
of the puru<218>a or the <193>tman who is asa<209>ga (detached) and ç
caitanya (pure consciousness), established in our hearts.
When the a<218><219><193><209>gayoga (yoga of eightgraded steps) ç
as recommended by Pata<210>jali <|>is <|>practised, <|>the<|> yogi<|> experiences ç
sam<193>dhi (superconscious state) wherein <216>tambharapraj<210><193> ç
(truth-bearing knowledge or wisdom)†which is practically the same ç
as <193>tmaj<210><193>na†arises. As this knowledge prevents and destroys ç
all other modifications of the mind (vide 1.48-50), nirb<200>jasam<193>dhi ç
(a sam<193>dhi wherein all karmas that would have caused rebirth are ç
destroyed at the root itself) results. Then the yogi becomes a mukta ç
or liberated.
@NT = nirgarbha
@N1 = (`without the womb [of the mantra]')
Pr<193><207><193>y<193>ma or control of the pr<193><207>ic energy ç
through the control of breath is an important aspect of the a<218><219><193><209>gayoga ç
of Pata<210>jali (200 <MS>B.<|>C.<D>). It has three steps: p<220>raka ç
(infilling of air into the lungs), kumbhaka (retention of breath) ç
and recaka (exhalation).
The kumbhaka has eight varieties of which the first is `sahita'. This ç
again is of two types: sagarbha and nirgarbha.
When the pr<193><207><193>y<193>ma is performed using the b<200>jamantra ç
(seed-letter prescribed for the same) it is called `sagarbha'. If ç
donewithout it, it is called `nirgarbha'. Kumbhaka being a part of ç
it, is also called by the same name.
See <MS>PR°Ø°Y°MA<D> for details.
@NT = Nir<200>·vara-s<193><209>khya
@N1-1 = (`the S<193><209>khya philo-sophy that does not accept ®·vara ç
or God')
The philosophies of S<193><209>khya and Yoga are generally studied ç
together. Whereas the former concentrates on the metaphysical side, ç
the latter pays the maximum attention to s<193>dhan<193> or spiritual ç
practice that ultimately leads to kaivalya or liberation.
Whereas the S<193><209>khya propounds 25 cosmic principles behind ç
creation, the Yoga accepts all of them and then adds ®·vara or God ç
as the 26th principle. Since the former school does not accept ®·vara ç
or God, it is called `Nir<200>·vara-s<193><209>khya' (nir= not). ç
The latter, as opposed to it, is termed `Se·vara-s<193><209>khya'.
See <MS>S°<177>KHYA DAR<185>ANA<D> and <MS>YOGA DAR<185>ANA<D> for ç
details.
@SPACE = 
@NT = nirm<193><207>acitta
@N1 = (`mind created [by the<R>ç
yogi]')
@SPACE1 = 
@SPACE1 = 
The Yogas<220>tras of Pata<210>jali (200 <MS>B.C.<D>) contains ç
some startling revelations, one of them being the `nirm<193><207>acitta' ç
(vide 4.4and5).
When a yogi is advanced very highly in the spiritual path, he discovers ç
through his intuitive inner eye, that he still hassome sa<210>citakarma ç
about to fructify as pr<193>rabdhakarma. This can delay his kai-valya ç
or liberation. Hence, using his special yogic powers he can create ç
simultaneously a few suitable bodies through which he can experience ç
and exhaust this karma. The citta or the mind in each of the bodies ç
thus created, is called `nirm<193><207>a-citta'.
Pata<210>jali makes it clear that though each of these nirm<193><207>acittas ç
acts differently through the different bodies to exhaust that karma, ç
the original or basic citta is that of the yogi, which controls them.
@SPACE = 
@NT = Nir<207>ayas<193>gara Press
@SPACE1 = 
@SPACE1 = 
The printing of the Hindu scriptural works in the devan<193>gar<200> ç
(Sanskrit) script has always been an arduous task. When the printing ç
presses were still in the early stages of development, much more care ç
was needed to get the final product right. The Nir<207>ayas<193>gara ç
Press is one printing press that deserved all praise.
Started in <MS>A.<|>D.<D> 1864, it was situated at the following address: ç
26-28, Kolbhat Street, Bombay-2. It was one of the oldest commercial ç
organisations of India, totally dedicated to the printing and publication ç
of Sanskrit books. Apart from the well-known Hindu scriptures it had ç
brought out the literary works also under the K<193>vyam<193>l<193> ç
series.
@SPACE = 
@NT = Nir<207>ayasindhu
@SPACE = 
The Nir<207>ayasindhu of Kamal<193>kara Bha<219><219>a (early part ç
of the 17th century) is an authoritative and voluminous work on the ç
dharma·<193>stras belonging to the class of nibandhas or digests.
Kamal<193>kara Bha<219><219>a was the son of R<193>mak<216><218><207>a ç
Bha<219><219>a and a grandson of N<193>r<193>ya<207>a Bha<219><219>a, ç
both of whom were also great scholars. Being a person of profound ç
erudition, Kamal<193>kara Bha<219><219>a authored several works†more ç
than twenty-two†of which, the Nir<207>ayasindhu is one and perhaps, ç
his master-piece. The other two works considered as equally famous ç
are: <185><220>drakamal<193>kara and Viv<193>dat<193><207><195>ava.
The Nir<207>ayasindhu is said to be an exposition of Kum<193>rila ç
Bha<219><219>a's (8th cent. <MS>A.<|>D.<D>) V<193>rttika on M<200>m<193><221>s<193>. ç
However it is an encyclopaedic work on the dharma-·<193>stra  subjects,  divided  into  three ç
paricchedas or sections.
A brief account of the contents may now be given:
On divisions of time and the right times for the performance of various ç
ritesand vratas; the various sa<221>sk<193>ras or sacraments; consecration ç
of images; auspicious times for various religious actions; ·r<193>ddha; ç
rites for sa<221>ny<193>sa.
It is interesting to note that the work describes the procedure for ç
sat<200> or self- immolation of a widow who willingly undertakes ç
it.
It is equally interesting and educative to learn from Kamal<193>kara's ç
another work, the <185><220>drakamal<193>kara, the various facilities ç
and freedom given to the ·<220>dras, the last of the four var<207>as ç
or castes, regarding the worship of gods, observance of vratas or ç
religious vows, allowing at least ten sa<221>sk<193>ras (sacraments), ç
the performance of the pa<210>camah<193>yaj<210>as (five daily sacrifices) ç
and many other socio-religious rites.
@NT = nirodha-sam<193>dhi
This is the same as <MS>NIRB®JA-SAM°DHI<D>. See the same for details.
@NT = Nir<216>ti
@N1 = (`[deity of] unfailing misfortune')
The word `Nir<216>ti' occurs for the first time in the <184>gveda ç
(10.165.1) as an evil spirit, as a personification of sin.
Jye<218><219>h<193>dev<200> or Alak<218>m<200> is also sometimes called ç
Nir<216>ti. (See <MS>ALAK<186>M®<D> for details.)
However, Nir<216>ti is more commonly pictured as the guardian deity ç
presiding over the south-western direction. He is one of the eight ç
dikp<193>lakas (guardian spirits of the quarters).
Iconographical works describe him as dark in colour, with a huge body ç
and matted hair. He has two hands carrying a sword and a shield. Ca<207><195>ik<193> ç
or R<193>k<218>ase·var<200> is his consort. He rides on a donkey.
Of course, there are other descriptions also.
An avak<200>r<207>in (a brahmac<193>ri who has violated the vow of ç
chastity) was expected to sacrifice an ass to appease Nir<216>ti as ç
an atonement for the sin.
There are other Nir<216>tis also mentioned in the pur<193><207>as.
He is one of the eleven Rudras.
As a woman, she is the wife of Adharma (unrighteousness). Bhaya (fear), ç
Mah<193>bhaya (great fear) and M<216>tyu (death) are her offsprings ç
(vide °diparva of the Mah<193>bh<193>rata, Ch. 67).
@NT = Nir<220><195>hapa·ubandha
Animal sacrifices were quite common during the days of Vedic yaj<210>as. ç
The Nir<220><195>hapa·ubandha was one such. It could be done as a ç
part of Somay<193>ga or even independently.
The procedure seems to have been reconstructed by the authors of the ç
·rauta-s<220>tras from the original material available in the Br<193>hma<207>as.
It was to be performed by an <193>hit<193>gni (one who had established ç
Vedic fires) either twice or once a year.
A he-goat was the animal prescribed for immolation, the deities being ç
Indra, Agni, S<220>rya and Praj<193>pati. Six priests were needed ç
for its performance.
See also <MS>VEDIC SACRIFICES.<D>
@NT = Nirukta
@N1 = (`etymology')
The Vedas are the basic scriptures of Hinduism. A correct understanding ç
of the same is necessary not only for knowing their philosophy but ç
also for the performance of the innumerable rites associated with ç
them.
To facilitate this, the Ved<193><209>gas or the six subsidiary limbs ç
of the Vedas were composed by competent <216><218>is or sages. The ç
Nirukta is one of them.
Actually, the Nirukta is a commentary on the Nigha<207><219>u, ç
a lexicon of Vedic words and terminology, of hoary antiquity.
Y<193>ska the author of this work lived probably during 800 <MS>B.<|>C.<D> ç
Hindu tradition however, pushes this date back to 2000 <MS>B.<|>C.<D>
Since the Nirukta is actually a gloss on the Nigha<207><219>u, ç
which itself is a kind of Vedic dictionary, it can be considered as ç
the earliest Vedabh<193><218>ya (commentary on the Vedas).
The Nirukta contains 14 adhy<193>yas or chapters. Leaving the last ç
two as pari·i<218><219>a or appendices, the rest†the first twelve ç
chapters†is divided into p<220>rva<218>a<219>ka and uttara<218>a<219>ka, ç
each containing six chapters.
The first chapter is introductory.
The next five chapters (2 to 6) deal exhaustively with the Naigha<207><219>uka ç
and the Naigama K<193><207><195>as of the Nigha<207><219>u.
The seventh chapter, again, is an introduction to the subject of the ç
Daivata-k<193><207><195>a of the Nigha<207><219>u.
The next five chapters (8 to 12) give detailed etymologies and explanations ç
of the names of the Vedic deities.
The last two chapters (13 and 14) contain eulogies of the Vedic deities ç
and spiritual teachings and instructions.
@SPACE1 = 
The contents of the entire work may be summarised very briefly thus: ç
several points of Sanskrit grammar; the theory that all words are ç
derived from dh<193>tus or verbal roots; all mantras have specific ç
meanings and usages; the need to know the deity of the mantras; in ç
praise of those who know the meaning of the mantras; ways of deriving ç
the meanings of words; explanations of the words of the Nigha<207><219>u; ç
characteristics of a Vedic mantra; power of the mantras and the deities; ç
meditating on the forms of the deities; definitions of the deities ç
of the earth, heaven and intervening space and so on.
The Nirukta throws a lot of light onthe contemporary life of the ç
society. Sanskrit was the spoken language. There were earlier treatises ç
on this subject as also grammar. The sweep of the subjects dealt with ç
or referred to, reveals the wide and deep scholarship of the author ç
Y<193>ska. He supported the theory that all words were derived from ç
verbal roots and has proved it in a highly scientific and systematic ç
manner.
There are two commentaries on the Nirukta, one by Durg<193>c<193>rya ç
(before <MS>A.<|>D.<D> 1200) and the other by two scholars, Skandasv<193>min ç
and Mahe·vara who lived sometime during the period <MS>A.<|>D.<D> 1060 ç
and <MS>A.<|>D.<D> 1350.
See also <MS>NIGHAØ<187>U.<D>
@NT = nirup<193>dhika
@N1 = (`without up<193>dhis [or<R>ç
limiting adjuncts]')
An Up<193>dhi, normally translated as a `limiting adjunct', is an ç
object that makes another object appear to be different from what ç
it actually is, though neither of them really affects each other. ç
For instance, when a red hibiscus flower is kept near a transparent ç
crystal, this crystal appears red, though in reality, it is not! ç
So, the hibiscus flower is an up<193>dhi for the crystal.
Similarly the <193>tman (the soul or the Self) inside the body appears ç
to be bound by the limitations or characteristics of the body-mind ç
complex which is its up<193>dhi.
Also, Brahman (God, the Absolute), appears as responsible for the ç
creation, sustenance and destruction of this world, though He is not.
In reality, in both these cases, neither the <193>tman nor Brahman ç
is affected by the up<193>dhis of the body-mind complex or the world ç
appearance. Hence they are called `nirup<193>dhika,' `without the ç
up<193>dhis' or `unaffected by the up<193>dhis'.
@SPACE = 
@NT = nirv<193><207>a
@N1 = (`blowing out')
See <MS>MOK<186>A.
@SPACE = 
@NT = nirvic<193>rasam<193>patti
@N1-1 = (`sam<193>dhi [on subtle objects] without discrimination')
The words sam<193>patti and sam<193>dhi mean the same thing: attaining ç
(mentally) the object of concentration, or perfect concentration on ç
the object of concentration.
While dealing with sam<193>patti, the Yogas<220>tras (1.42-44), ç
has mentioned four types of them: savitarka and nirvitarka; savic<193>ra ç
and nirvic<193>ra.
Out of the a<218><219><193><209>gas or eight steps described by the ç
Yogas<220>tras, the last three†dh<193>ra<207><193>, dhy<193>na and ç
sam<193>dhi†are clubbed together and given the technical name `sa<221>yama' ç
(vide 3.4).
When sa<221>yama is practised on the subtle elements of the object ç
comprising it and only the subtle object of concentration shines before ç
the mind's eye, all other processes being completely transcended, ç
it is called `nirvic<193>ra sam<193>patti'.
@SPACE = 
@NT = nirvikalpaka
@N1 = (`without distinctions')
Sam<193>dhi  or  total  absorption  in Brahman is of two kinds: savikalpaka ç
and nirvikalpaka. Vikalpa means distinctions, the consciousness of ç
the many like `me' and `Brahman' and the world. In the savikalpaka ç
sam<193>dhi the consciousness of one's own personality as distinct ç
from Brahman, persists, however attenuated itmay be. In the nirvikalpaka ç
state, however, all awareness of multiplicity including that of oneself ç
asdistinct from Brahman, is completely dissolved.
@SPACE = 
@NT = nirvikalpa-sam<193>dhi
See <MS>NIRVIKALPAKA.
@SPACE = 
@NT = nirvi·e<218>a
@N1 = (`that which is without special characteristics')
@SPACE1 = 
@SPACE1 = 
The nature of the highest Reality, generally designated by the word ç
`Brahman' in the Upani<218>ads, is an important point of discussion ç
in the Ved<193>nta philo-sophy, considered as the crest-jewel of Indian ç
philosophical systems.
According to the Advaita Ved<193>nta, Brahman has two lak<218>a<207>as ç
or characteristics; ta<219>asthalak<218>a<207>a (accidental characteristic) ç
and svar<220>palak<218>a<207>a (intrinsic characteristic).
When  Brahman  is  described  as responsible for the creation or evolution ç
of this world (vide the Brahmas<220>tras 1.1.2) it is the first ç
lak<218>a<207>a that has been indicated. This is only an indirect ç
way of pointing towards it.
However, in its own intrinsic nature it is described as `nirvi·e<218>a-cinm<193>tra-svar<220>pa'.
It is pure consciousness without any vi·e<218>as or qualities. It ç
is this essential nature of Brahman that is indicated by the word ç
`nir-vi·e<218>a' (= without specific qualities). Another word used ç
in the same sense is `nirgu<207>a' (vide <185>vet<193>·vatara Upani<218>ad ç
6.11).
See  also  <MS>SVAR<188>PALAK<186>AØA<D>  and <MS>TA<187>ASTHALAK<186>AØA.
@NT = nirvitarkasam<193>patti
See <MS>SAVIC°RASAM°PATTI.<D>
@NT = ni<218><193>da
@N1 = (`one who sits [or lives on the outskirts of a village]')
Though the fourfold division of the Hindu society, designated as the ç
var<207>a- system, is very ancient, mixing up of the var<207>as (var<207>asa<209>kara) ç
either within the ambit of the sacrament of marriage or outside it, ç
was a real and continuing phenomenon. This gave rise to many new castes ç
and subcastes. The ni<218><193>da is one such.
Ni<218><193>das were the offsprings of a br<193>hma<207>a male from ç
a ·<220>dra woman. They were considered to be outside the pale of ç
the four castes.
They are often described as dark in colour with reddish eyes and living ç
by hunting wild animals.
The R<193>m<193>ya<207>a (Ayodhy<193>k<193><207><195>a 50.33; ç
52.77-92) mentions that Guha who was the chieftain of the ni<218><193>das, ç
helped R<193>ma to cross the Ga<209>g<193> river. Later he took Bharata ç
to meet R<193>ma (ibid 89.12-19).
In music, ni<218><193>da (ni) is the seventh note. It is supposed ç
to come out of the region of lal<193><219>a (forehead) and resemble ç
the sound of an elephant.
@NT = ni<218><193>dasthapati
Every society has its own rules to regulate the lives of its members ç
both at the personal and at the social levels. As the society evolves ç
in its civilisation and culture, these rules also, often, undergo ç
change.
Evolution of yaj<210>as and y<193>gas (Vedic sacrifices) gradually ç
needed the involvement of more and more people including those from ç
the lower var<207>as or castes. In return for their valuable services, ç
some of them like the rathak<193>ras and ni<218><193>das, had to be ç
accorded certain privileges.
So, in course of time, the rathak<193>ras (`makers of chariots,' the ç
carpenters) and the ni<218><193>dasthapati (chieftain of the ni<218><193>das)  were  given  the  privilege  of ç
undergoing the sacrament of upanayana and keeping the Vedic fires ç
in which they could offer oblations. They were permitted to perform ç
Raudrai<218><219>i, Agnihotra and theDar·ap<220>r<207>am<193>sa sacrifices ç
(vide Saty<193><218><193><195>ha Kalpas<220>tras 3.1).
@NT = ni<218>edha
@N1 = (`prohibition')
Vidhis (injunctions) and ni<218>edhas or prati<218>edhas (prohibitions) ç
are common in Vedic rituals. They are also seen in the dharma·<193>stras.
If a vidhi ordains a person to do something which will benefit him, ç
a ni<218>edha prohibits him from doing something which will harm him. ç
Such ni<218>edhas are indicated by the negative particle `na<210>'.
For instance: `na an<216>ta<221> vadet, na m<193><221>sam a·n<200>y<193>t,' ç
`One should not speak what is false, nor eat flesh' (Taittir<200>ya ç
Sa<221>hit<193> 2.5.5.6).
Here uttering falsehood and eating flesh have been prohibited.
In the dharma·<193>stra works, the particle `na<210>' (`not') is used ç
in the sense of paryud<193>sa or exception. For instance, a sn<193>taka ç
(one who has just finished Vedicstudies) should not say anything ç
to another which hurts him unless there is a specific reason. It does ç
not altogether prohibit speaking an unpleasant thing, if and when ç
necessary, as in the case of a parent chastising an erring son.
In some cases there may be two negatives or ni<218>edhas opposed to ç
each other causing confusion. Then one has the choice to accept one ç
and reject the other subject to certain conditions.
@NT = ni<218>eka
@N1 = It is the same as garbh<193>dh<193>na (`inseminating'), one ç
of the sixteen sa<221>sk<193>ras.
See <MS><186>O£A<185>ASA<189>SK°RAS.<D>
@NT = ni<218>iddhakarma
@N1 = (`prohibited actions')
See <MS>K°MYAKARMA.<D>
@NT = ni<218>ka
Using  coins  as  money  was  not unknown in ancient India. Suvar<207>a, ç
·atam<193>na and ni<218>ka are some of the words used to indicate ç
these.
The  word  `ni<218>ka'  occurs  in  the Atharvaveda (5.14.3) and ç
refers to a necklace of ni<218>ka (may be a gold-coin or a thin plate ç
of gold).
The <184>gveda (2.33.10) refers to Rudra as wearing a `Vi·var<220>pani<218>ka' ç
(golden pieces stamped with various figures).
The following table can give an idea of the ni<218>ka by weight:
Weight of 5 liquorice seeds = 1 m<193><218>a
16 m<193><218>as = 1 suvar<207>a
108 suvar<207>as = 1 ni<218>ka.
`D<200>n<193>ra' seems to be another name used for ni<218>ka.
@NT = ni<218>k<193>makarma
See <MS>KARMAYOGA.<D>
@NT = ni<218>krama<207>a
@N1 = (`going out,' `taking [the baby] outside the house')
@SPACE = 
The entire life of a Hindu is closely connected with religious rites ç
and cere- monies, in some form or the other. The <186>o<195>a·a-sa<221>sk<193>ras  (sixteen  sacraments) ç
reflect this basic attitude.
The ni<218>krama<207>a (or upani<218>krama<207>a) is one of the minor ç
sa<221>sk<193>ras and is performed by taking the new-born baby out ç
of the house in the open and exposing it to the sunlight. It may be ç
done either on the twelfth day or in the fourth month.
Worshipping the sun by the father of the baby with an offering prepared ç
out of milk and presenting the baby to the sun with some Vedic mantras ç
(<184>gveda 1.50.1) is an important part of this ritual.
Some g<216>hyas<220>tras prescribe the performance of a homa also.
In some works like those of Gobhila and Kh<193>dira, only candradar·ana ç
(showing the moon on a full-moon day) to the baby is mentioned.
@SPACE = 
@NT = ni<218>patti-avasth<193>
@N1-1 = (`state of consummation [of pr<193><207><193>y<193>ma]')
@SPACE = 
Pr<193><207><193>y<193>ma is a part of yogic practices. It helps in ç
controlling the mind and restoring the humours to a balanced state ç
to regain health, by a systematic control of breath.
It has four states out of which the ni<218>patti-avasth<193> is the ç
last. It is the consummation of pr<193><207><193>y<193>ma coinciding ç
with the j<200>vanmukti state.
The actual methods have to be learnt from a competent teacher.
See also <MS>PR°Ø°Y°MA.
