@H = V
@NT = Vaitara<207><200>
@N1 = (`that which gives [punishment to the sinners]')
The journey of the bound soul, the j<200>v<193>tman still in bondage, ç
after death, has been described by the Hindu scriptures in picturesque ç
ways.
Those who have led highly immoral lives and committed abominable sins† ç
called mah<193>p<193>takas<192>are severely punished even on the way ç
to Yamaloka, the world of Yama, the god of death.
Apart from the various troubles to which they are subjected first, ç
they are forced to cross the horrible river called Vaitara<207><200>, ç
just before entering Yama's kingdom.
This putrid river of blood, bones, puss and all unwanted things which ç
is of hundred yojanas (800 miles or 1287 kilometers) suffocates these ç
evil ones causing intense suffering.
A detailed description of this journey and the river is found in the ç
Pretakalpa section of the Uttarakha<207><195>a of the Garu<195>apur<193><207>a.
Donating a milch-cow before death and certain holy rites described ç
in the scriptures performed after death, can help the soul to cross ç
the Vaitara<207><200> easily without any suffering.
@NT = Varamah<193>lak<218>m<200>vrata
This is a regional vrata (religious festival) for women, commonly ç
performed in South India, especially in Karnataka.
It is observed on a Friday prior to <185>r<193>va<207>a P<220>r<207>im<193>. ç
Only married women whose husbands are living, are entitled to do this. ç
Worship of Mah<193>lak<218>m<200>, the goddess of wealth and prosperity, ç
invoked in a kala·a established on a ma<207><195>ala (sacred diagram) ç
is the main item. A doraka (thread) is also offered in p<220>j<193> ç
and later worn on the right hand. Gifts to other married women should ç
be done at the end. As usual, the health and longevity of the husband, ç
progeny and wealth are the results assured by this vrata.
@NT = V<193>sav<193>mb<193>, V<193>sav<200>
See <MS>KANYAK°PARAME<185>VAR®<D>.
@NT = Vi·vakarm<193>
@N1 = (`the creator of all')
A god of Vedic fame, Vi·vakarman is regarded as the primordial architect ç
and sculptor. He is the progenitor of all the architects, painters, ç
sculptors and artisans of the world.
He was the son of Prabh<193>sa (one of the eight Vasus) (See <MS>A<186><187>AVASUS<D>) ç
and Yogasiddh<193> (vide Mah<193>bh<193>rata, °diparva, Ch. 62).
When he completed his education atthe gurukula (See<MS> GURUKULA.<D>) ç
the guruand his wife put before him some impossible demands such ç
as an eternally new  house,  indestructible  household articles and ç
so on, as gurudak<218>i<207><193> (fees).
Seeing no other way, he went to K<193>·<200> and performed severe ç
austerities. Pleased with this, Lord <185>iva appeared before him ç
and gave him extraordinary power to create things. He thus became ç
an expert in all fields of arts and crafts.
He was the first of the major masters of arts and sciences. Out of ç
the eighteen teachers of architecture, he ranks as the fourth, the ç
other three being Bh<216>gu, Atri, and Vasi<218><219>ha.
Some of the works dealing with architecture attributed to him are: ç
Vi·va-karma-prak<193>·a; Vi·vakarma-v<193>stu; Vi·va-karma·ilpa; ç
Vi·vakarmamata; Vi·va- karmasa<221>hit<193> and Vi·vakarm<200>ya.
According to the well-known work M<193>nas<193>ra (21.5-9) the creator ç
Brahm<193> produced the following four sages from his four faces: ç
Vi·vakarman, Maya, Tva<218><219><216> and Manu. They were responsible ç
for fourclasses of artisans: sthapati (master architect); s<220>tragr<193>h<200> ç
(designer); vardhak<200> (painter, carpenter) and tak<218>aka (sculptor).
Vi·vakarman is described as seated upon a throne surrounded by sages ç
and gods. He has five faces, fifteen eyes and ten hands. He has ja<219><193>muku<219>a ç
(crown of matted hair) on his head. His body is of golden colour. ç
He carries in his hands several implements of artisans like chisel, ç
axe and so on.
According to another version, he has four hands, holding kama<207><195>alu ç
(water pot), pustaka (book), p<193>·a, (noose) and craftsman's tools.
Vi·vakarmap<220>j<193> (worship of Vi·va-karm<193>) is observed on ç
the Kany<193>-sa<209>kr<193>nti day, which falls on September 17 since ç
it follows the Sauram<193>na or solar calendar. It was on this day ç
that the forefathers of the present Vi·vakarma caste invented the ç
plough and gifted it to humanity. The plough represents both the artisan ç
trade as also agriculture.
It is observed as the jayanti (birthday) of the god or sage Vi·vakarm<193>.
The worship is offered to a clay image (as in the case of Ga<207>apati) ç
and later it is immersed in a river or a tank.
On the day of worship, all the tools and implements are washed, kept ç
at the feet of the image and decorated.
@NT = Vi<218>vaksena
@N1 = (`one [who is] surrounded on all sides by the army')
In the well-known hymn, the Vi<218><207>u-sahasran<193>ma, this ç
word has been used as one of the names of Vi<218><207>u (name 125).
When Vi<218><207>u is in the battle-field, fighting with the sen<193> ç
or army of the asuras or demons, they are so terrified that they run ç
helter-skelter (= vi<218>vak). Hence he is called `Vi<218>vaksena'.
In the P<193><210>car<193>tra literature of Vai<218><207>avism, Vi<218>vaksena ç
is described as the commander of the minor deities surrounding Vi<218><207>u ç
and hence called ``Ga<207>apati''. He is the equivalent of Ga<207>apati ç
or Vin<193>yaka of <185>aivism.
According to one version he was the son of Varu<207>a and Suvarcal<193>. ç
He pleased Lord Vi<218><207>u by severe austerities spread over twelve ç
years. Gratified with his devotion, Vi<218><207>u made him the sen<193>pati ç
or the commander of his forces.
In the <185>r<200>vai<218><207>ava line of teachers, he occupies the ç
third place, just after Vi<218><207>u and Lak<218>m<200>. His image ç
is installed in all the Vi<218><207>u temples of this sect. He is ç
said to be the custodian of the nirm<193>lya or flowers used by the ç
main deity Vi<218><207>u.
Iconographical works describe him as almost similar to Vi<218><207>u ç
but without the ·r<200>vatsa mark on the chest. He holds the·a<209>kha ç
(conch), cakra (discus), and gad<193> (mace) in three hands, the fourth ç
exhibiting the tarjan<200>mudr<193> (pose of threatening [the evil-doers]).
He may be shown as seated upon a throne. His consort is Jay<193>, ç
also called V<193>r<193>h<200>.
@NT = Vy<193>sap<220>r<207>im<193>
See <MS>GURUP<188>RØIM°<D>.
@END = <R>ç

