@H = Y
@NT = Yogin<200>h<216>daya
@SPACE = 
This is one of the important texts of the tantra group of literature.
@SPACE1 = 
The tantras are sometimes classified into two varieties: The nigama ç
and the <193>gama. In the former, it is the Dev<200> (the Divine Mother) ç
who is the teacher and <185>iva, the disciple. In the latter however, ç
the roles are reversed.
@SPACE1 = 
In this work it is <185>iva who teaches the esoteric truths to the ç
Dev<200>.
@SPACE1 = 
It has 377 ·lokas (verses in the anu<218><219>ubh metre) spread over ç
3 pa<219>alas or chapters.
@SPACE1 = 
There are two Sanskrit commen- taries:  Setubandha  by  Bh<193>skarar<193>ya- ç
makhin  or  Bh<193>sur<193>nandan<193>tha  (17th century <MS>A.D.<D>);
@SPACE1 = 
D<200>pik<193> by Am<216>t<193>nandan<193>tha.
@SPACE1 = 
Bh<193>skarar<193>ya<199>a-makhin treats this work as the last part ç
of another well-known work (its last three chapters, 6th to 8th), ç
the Nity<193><218>o<195>a·ik<193>r<207>ava, also called V<193>make·varatantra.
@SPACE1 = 
A brief summary of the work may now be given here:
@SPACE = 
@S10N = First Pa<219>ala<R>ç
(Cakrasa<209>ketanir<220>pa<207>am†verses 86)
This esoteric wisdom can be given to an aspirant only after testing ç
him for at least six months. It should never be imparted to disciples ç
of other gurus, or atheists or lazy persons.
This is then followed by a detailed description of the <185>r<200>cakra. ç
(See <MS><185>R®CAKRA<D>.)
It is interesting to note that the nine parts of the <185>r<200>cakra ç
are given different names such as Sarv<193>nandamayacakra, Sarvarak<218><193>karacakra, ç
Trailokyamohanacakra and so on, by worshipping which, specified results ç
may be obtained.
@SPACE = 
@S10N = Second Pa<219>ala<R>ç
(Mantrasa<209>ketanir<220>pa<207>am†verses 85)
In the beginning, nine ny<193>sas (puri-ficatory processes) of various ç
limbs with appropriate vidy<193>s or mantras like kara·uddhividy<193> ç
for the extremities of the feet etc., are described.
The s<193>dhaka is then advised to think of the various aspects of ç
the Dev<200> like Tripur<193>, Tripure·var<200> and so on in the various ç
cakras of the body like the well- known six cakras (<193>dh<193>ra, ç
sv<193>dhi<218><219>h<193>na etc.).
Six kinds of meanings of mantras are possible. They are: bh<193>v<193>rtha ç
(meaning as revealed by the letters of the mantra); samprad<193>y<193>rtha ç
(meaning according to the tradition, received from the guru or preceptor); ç
nigarbh<193>rtha (knowledge of the unity of the deity, the guru and ç
oneself) kaulik<193>rtha (knowledge of the unity of the <185>r<200>cakra, ç
the Divine Mother, the mantra, the guru and one's Self); rahasy<193>rtha ç
(knowledge of the identity of the ku<207><195>alin<200> and the mantra); ç
mah<193>tattv<193>rtha (knowledge of the unity of the j<200>v<193>tman ç
with <185>iva).
The section closes with the eulogy of guru's grace, by which alone ç
all this knowledge can be got.
@S10N = Third Pa<219>ala<R>ç
(P<220>j<193>sa<209>ketanir<220>pa<207>a†206 verses)
This pa<219>ala is devoted mainly to various steps connected with ç
p<220>j<193> or ritualistic worship.
@SPACE1 = 
P<220>j<193> is described as of three types: par<193>p<220>j<193>, ç
apar<193>p<220>j<193> and par<193>-apar<193>-p<220>j<193>.
@SPACE1 = 
In par<193>p<220>ja one has to think of the identity of the guru, ç
the dev<200> in the heart and one's <193>tman. Apar<193>p<220>j<193> ç
is the regular ritualistic worship of the <185>r<200>cakra. The par<193>-apar<193>-p<220>j<193> ç
is a mixture of these two steps.
The text then describes various ny<193>sa<%32>s<%0>(ritual purification ç
of limbs) including the ny<193>sa of <185>r<200>cakra.
The other topics dealt with are: removal of obstacles, worship of ç
S<220>rya and other planets, worship of the sandals of guru, p<220>j<193> ç
of <185>r<200>cakra in detail, method of japa, tarpa<207>a (satiating ç
with water) and concluding the whole worship.
The treatise ends with the strict instruction that this knowledge ç
should never be imparted to unworthy persons.
@NT = Yogin<200> Tantra
@EMERGEN1 = This is a voluminous work of two Kha<207><195>as or sections, ç
belonging to the tantra-group. It has 2795 verses distribu-ted among ç
27 sargas or chapters. The first Kha<207><195>a or section contains ç
19 sargas (and 1291 verses) whereas the second Kha<207><195>a has ç
8 sargas plus a pari·i<218><219>a (appendix) (1504 verses).
@EMERGEN1 = A very brief account of the contents only can be given ç
here:
@SB = <BIJ8>First Kha<207><195>a<DJ0>
@S10N = Sarga 1 (56 Verses)
@NID = <+><+><+>Greatness of the guru in spiritual life.
@S10N = Sarga 2 (74 Verses)
Various types of japam<193>l<193>s prepared out of ·ankha (conch) ç
or ma<207>i (pearl), the number of beads as also the results of using ç
them; some details connected with japa (repetition of the mantra) ç
such as suitable time and place; on the Mother K<193>l<200> and the ç
greatness of K<193>·<200>.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@S10N = Sarga 3 (66 Verses)
Details about preparing a kavaca (esoteric diagram with a mantra inscribed ç
on a suitable material), by wearing which diseases can be averted ç
and other persons can be mesmerised.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@S10N = Sarga 4 (74 Verses)
Details of <218>a<219>karmas of V<193>m<193>c<193>ra cults. (See <MS><186>A<187>KARMAS.<D>)
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@S10N = Sarga 5 (77 Verses)
How Lak<218>m<200> became a bilva tree (Aegle marmelos), worshipped ç
the <185>iva-li<209>ga and got a place on the chest ofVi<218><207>u.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@S10N = Sarga 6 (73 Verses)
Description of two types of s<193>dhakas, the `divya' and the `v<200>ra'; ç
pa<210>camak<193>ras (the five `m's.) (See under <MS>TANTRAS<D>.)
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@S10N = Sarga 7 (61 Verses)
Svapn<193>vat<200>-vidy<193>  (repetition  of  a special mantra 108 ç
times per day for 4years by which one gets a vision of the goddess); ç
m<216>tasa<210>j<200>vin<200>vidy<193> (the mantra by which a dead ç
person can be revived).
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@S10N = Sarga 8 (72 Verses)
Manifestation of K<193>l<200> from Mother P<193>rvat<200>.
@S10N = Sarga 9 (75 Verses)
K<193>l<200> assigns duties to Brahm<193>, Vi<218><207>u and <185>iva.
@S10N = Sarga 10 (63 Verses)
K<193>l<200> infills Vi<218><207>u, Brahm<193> and <185>iva with icch<193>·akti, ç
kriy<193>·akti and j<210><193>na·akti respectively.
@S10N = Sarga 11 (69 Verses)
`K<193>l<200>vidy<193>' described in detail with the mantra, p<220>j<193> ç
(worship), havana or homa, dhy<193>na (meditation) and other details.
@S10N = Sarga 12 (74 Verses)
The greatness and importance of thefamous pilgrim centre K<193>m<193>khy<193> ç
in Assam.
@S10N = Sarga 13 (61 Verses)
On karma and its fruits; the inevitability of karma.
@S10N = Sarga 14 (81 Verses)
About the non-Vedic races like yavanas, saumaras and mlecchas as also ç
their mutual conflicts.
@S10N = Sarga 15 (67 Verses)
Killing of the demon Ke·i by K<193>l<200>; the greatness of the hill ç
Govardhana.
@S10N = Sarga 16 (59 Verses)
Destruction of Tripur<193>sura; liberation of those who die at K<193>·<200>.
@S10N = Sarga 17 (53 Verses)
Destruction of the demon Kol<193>sura by K<193>l<200>; significance ç
and practice of `Kum<193>r<200>p<220>j<193>' (worshipping K<193>l<200> ç
through a Kum<193>r<200> or young girl).
@S10N = Sarga 18 (55 Verses)
@SPACE1 = 
@SPACE1 = 
Birth of the river Ga<209>g<193> and its greatness eulogised.
@SPACE = 
@S10N = Sarga 19 (81 Verses)
@SPACE1 = 
@SPACE1 = 
Kar<193>la Bhairava gets transformed into Krodha Bhairava.
@SPACE = 
@SB = <R>ç
Second Kha<207><195>a
@S10N = Sarga 1 (60 Verses)
@SPACE1 = 
@SPACE1 = 
Names of some <185>aktip<200><219>has like K<193>mar<220>pa and J<193>landhara ç
as also the minor places associated with the Dev<200>.
@SPACE = 
@S10N = Sarga 2 (68 Verses)
@SPACE1 = 
@SPACE1 = 
Some details connected with t<200>rthay<193>tr<193> or pilgrimage ç
like suitable dates.
@SPACE = 
@S10N = Sarga 3 (77 Verses)
@SPACE1 = 
@SPACE1 = 
Some places of pilgrimage and their importance.
@SPACE = 
@S10N = Sarga 4 (138 Verses)
@SPACE1 = 
@SPACE1 = 
Different pilgrim centres associated with <185>iva and the names of ç
his several aspects.
@SPACE = 
@S10N = Sarga 5 (342 Verses)
@SPACE1 = 
@SPACE1 = 
This long section deals mainly with the ceremonial offering of pi<207><195>as ç
(rice-balls) during ·r<193>ddha ceremonies.
@SPACE = 
@S10N = Sarga 6 (187 Verses)
@SPACE1 = 
@SPACE1 = 
Ritual  methods  of  taking  bath, worship of deities, giving gifts ç
etc., in places of pilgrimage.
@S10N = Sarga 7 (242 Verses)
The method of dev<200>p<220>j<193> or worship of the Divine Mother ç
is described in detail along with the fruits thereof.
@S10N = Sarga 8 (123 Verses)
This contains detailed descriptions of various places of pilgrimage ç
as also the religious rites to be conducted there.
@S10N = Pari·i<218><219>a (Appendix) (264 verses)
A few more places of pilgrimage, but less known are mentioned here.
@END = <R>ç
<R>ç

