@H = S
@NT = <185>aktip<200><219>has
@N1 = (`Seats of Mother (cult<%6>)'<%0><|>)
See under <MS>TANTRAS<D>.
@NT = Samay<193>c<193>ra Tantra
The Samay<193>c<193>ra Tantra is considered as an important work ç
among the 64 tantras. Spread over 281 verses in the anu<218><219>ubh ç
metre it deals with all aspects of tantra literature, though briefly.
Practices of v<193>m<193>c<193>ra (See under <MS>TANTRAS<D>.) find ç
a prominent place.
The word `samay<193>c<193>ra' refers to the system of worship and ç
allied details, as applied to a specified deity.
It also means the Dev<200> or the Divine Mother.
Some of the topics dealt with in thiswork may now be described briefly: ç
materials to be used in worship as also those which can be consumed ç
after offering; various times of the day suitable for different rites ç
with specific results like ·<193>ntikarmas (rites for peace) or va·ya-karma ç
(getting others under one's control) and so on; the various <193>sanas ç
or postures to be adopted according to the results desired, like padm<193>sana ç
in peace-rites; certain aspects of the theory involving the books ç
and deities of this school; certain types of m<193>l<193>s (rosaries) ç
and the results of using them; various types of <193>sanas or seats ç
and the results of their use as for instance the tiger-skin being ç
used if one wants mok<218>a (liberation); descriptions of places suitable ç
for the performance of japa (repetition of mantra); classification ç
of mantras as pu<221> (male), str<200> (female) and napu<221>saka ç
(neuter); two types of practices, v<193>m<193>c<193>ra and dak<218>i<207><193>cara ç
(the left-hand  and  the  right-hand  paths); qualities of a guru ç
or teacher and the ·i<218>ya or disciple; various articles needed ç
for p<220>j<193> especially the ones known as pa<210>camak<193>ras ç
(See <MS>TANTRAS<D>.); description of p<200><219>has or seats suitable ç
for the performance of japa, they being the <185>akti-p<200><219>has, ç
places hallowed by the body-parts of Sat<200>†D<193>k<218><193>ya<207><200> ç
(See <MS>TANTRAS<D>); giving of balis (ceremonial offerings) to various ç
deities; certain mantras concerning the various aspects of <185>iva ç
like Aghora; and methods of purifying mantras known as mantrasa<221>sk<193>ra ç
(See <MS>MANTRASA<189>SK°RA<D> for details).
Though a small work, it contains a lot of information about the practical ç
aspects of tantras, more attention being given to the v<193>m<193>c<193>ra ç
practices.
@NT = Sanskrit<|>Commission, Repor<%6>t<%0><|>of The.
@SB = Introduction
Sa<221>sk<216>ta or the Sanskrit language has always been held in ç
high veneration by the Hindus, so much so that it has been christened ç
as `Devabh<193><218><193>' (`language of the gods'). The gods in heaven ç
are veryhandsome. The Sanskrit language is supremely elegant. The ç
gods in heaven are eternally young and vigorous. The Sanskrit language, ç
even now, is eternally fresh and delightfully vibrant.
Like all things in life, Sanskrit too has had its glorious periods ç
and spells of hibernation.
However, when India got political independence and its own government ç
there was a new upsurge of the national spirit enlivening every aspect ç
of Indian life. The Sanskrit language which had held the Hindu nation ç
together by its inspiring literature†whether sacred or secular† and ç
the resultant culture, could no longer remain insulated from this ç
new-found spirit.
@SPACE1 = 
Due to the patriotic zeal of some wiseand sagacious leaders, both ç
in the government and outside it, <%12>`<%0>The Sanskrit Commission'  was  constituted  by  the ç
Government of India on the 1st October 1956 with Dr. Suniti Kumar ç
Chatterji aneminent scholar and linguist, as thechairman, and seven ç
distinguished professors and savants as members.
@SPACE = 
The terms of reference were:
@SPACE1 = 
@SPACE1 = 
1. to undertake a survey of the existing facilities for Sanskrit Education ç
in Universities and non-University institutions and to make proposals ç
for promoting the study of Sanskrit, including research; and
@SPACE1 = 
2. to examine the traditional system of Sanskrit Education in order ç
to find out what features from it could be usefully incorporated into ç
the modern system.
@SPACE1 = 
@SPACE1 = 
The  commission  established  its Secretariat at Poona (now Pune) ç
on the 1st November 1956.
@SPACE1 = 
It issued a detailed questionnaire† both in English and in Sanskrit†comprising ç
33 major questions, each containing several subquestions (85 in all) ç
covering all conceivable aspects of Sanskrit education and culture.
@SPACE1 = 
@SPACE1 = 
Apart from questions of a general nature, other aspects included in ç
the questionnaire were:
a.
@NK = Sanskrit Education†The Modern as well as the Traditional Systems;
b.
@NK = Sanskrit Research;
c.
@NK = Organisation and Administration of Sanskrit Studies and Education.
Apart from distinguished scholars and professors of Sanskrit, the ç
questionnaire was answered by a large number of persons from various ç
walks of life who were deeply interested in the spread of the language. ç
Nearly 1200 replies were received†about 470 being in Sanskrit† which ç
were analysed, the analyses themselves running into 2653 typed pages.
The Commission took the trouble ofcollecting all the reports of various ç
committees†eleven, to be more specific† appointed in the earlier years ç
by several State governments on the same subject of Sanskrit Education ç
and studied them.
Members of the Commission toured the country extensively, visited ç
most of the institutions connected with Sanskrit language and culture, ç
and interviewed hundreds of interested persons to elicit their opinions.
The final Report running into 300 pages (size: ??? ) was submitted ç
to the Government on 30th November 1957.
It  consists  of  12  chapters  and 9detailed appendices.
@SPACE = 
@SB = A Brief Summary of the Report
@S10N = Chapter 1†Introduction
Apart from giving the details regarding the appointment of this Commission, ç
reference is made to the work of two Educational Commissions and the ç
Official Language Commission, all of which have touched upon the topic ç
of Sanskrit education. Various Sanskrit Reorganisation Commissions ç
appointed earlier by several State governments and Public Bodies have ç
also been referred to.
@S10N = Chapter 2†Historical Retrospect
This chapter gives a historical survey of Sanskrit studies in India, ç
especially after the taking over of the country by the British. Whereas ç
the old P<193><219>ha·<193>l<193> system, the traditional system, ç
continued to survive, a new system, that of Colleges and  Universities  offering  courses  in ç
Sanskrit, also developed side by side. The growth of institutions ç
and activities on both these fronts over the last 150 years has been ç
described here.
@S10N = Chapter 3†The Present Situation
Activities of the P<193><219>ha·<193>l<193>s, Secondary Schools, Colleges, ç
Universities and Research  Institutions  as  also  various public ç
movements devoted to the promotion of Sanskrit in some form or the ç
other, have been reviewed here.
@S10N = Chapter 4†<|>Sanskrit and the<R>ç
Aspirations of Independent India
Realising the hopes and aspirations of the people of independent and ç
resurgent India,  this  chapter  discusses  various topics, opening ç
the case for Sanskrit. Some of them are: The importance of Sanskrit ç
in Indian History and Culture; Sanskrit studies and Humanities; intrinsic ç
worth and significance of Sanskrit literature for the full development ç
of human personality; Sanskrit as a binding force both at the national ç
and international levels; Sanskrit still a living force and a perennial ç
source for the sustenance of the various regional languages; must ç
be a part of general scheme of Indian education; should be accorded ç
special treatment.
@S10N = Chapter 5†Sanskrit Education
Sanskrit must be made one of the compulsory subjects in general education ç
as a part of the curriculum in the Secondary Schools. The specialised ç
studyin the P<193><219>ha·<193>l<193>s, in the modern Colleges and ç
Universities should be better organised. As a part of this subject, ç
the merits and drawbacks of the two systems are discussed as also ç
how the two can be integrated.
It has been pointed out here how Sanskrit has to be treated as a complement ç
to the higher study of modern Indian languages as also Indian Philosophy ç
and Indology.
@S10N = Chapter 6†Teaching of Sanskrit
Methods of teaching Sanskrit, both ancient and modern, have been described ç
here. The need to evolve suitable methods to teach it at different ç
levels as also thenecessary reforms in the system of examination ç
have been suggested.
@S10N = Chapter 7†Sanskrit Research
This chapter deals with Sanskrit Research in all its aspects. The ç
topics discussed are as follows: significance of research  for  the  growth  of  Sanskrit ç
studies;  research  in  the  Universities; research  scholarships  and  fellowships; ç
adjudication of research theses; neglected subjects; research projects ç
and research publications;  seminars;  Journals  and Bibliographies; ç
Research Institutions; All India Oriental Conference; a scheme for ç
a Central Institute of Indology.
@S10N = Chapter 8†Manuscripts
The question of Sanskrit Manuscripts has  been  tackled  here†their  search, ç
collection, preservation, cataloguing, study and publication.
It is advised to set up a Central Manuscripts library.
@S10N = Chapter 9†Sanskrit University
The question of setting up a Sanskrit University under the Central ç
Government has been suggested as also a Central Board of Sanskrit ç
Studies. States also can be encouraged to start similar Universities.
@S10N = Chapter 10†<R>ç
Other Questions concerning Sanskrit
The  following  topics  have  been discussed in this section: Sanskrit ç
and Religious Education; the use of regional scripts for Sanskrit; ç
Technical Termino-logy; Sanskrit as an Official Language of the Indian ç
Union; State honours and patronage for Sanskrit Scholars; encou-ragement ç
of Sanskrit through Ma<219>has and temples; Vedap<193><219>ha, Pur<193><207>ap<193><219>ha ç
and Paurohitya; technical disciplines like °yurveda, Jyauti<218>a ç
and <185>ilpa; Sanskrit journals; popularisation of Sanskrit by various ç
means; cheap editions of Sanskrit classics with translations in regional ç
languages and English.
@S10N = Chapter 11<%10>†<MI%0>Administration and	Organisation<R>ç
of Sanskrit Education and Research
The chief point that has been stressed is that the resources available ç
through various Trusts and Endowments should be pooled and utilised ç
for the promotion of Sanskrit.
@S10N = Chapter 12†Conspectus<|>and<|>Recommendations
This section gives a brief summary of  all  the  chapters  followed  by  the ç
Recommendations of the Commission.
@SB = Recommendations
@NID = <+><+><+><+>The Recommendations are categorised under the following ç
headings:
1. Sanskrit Education;
2. Sanskrit Research;
3. Manuscripts;
4. Sanskrit Universities;
5. General;
6. Administration and Organisation.
@S10N = 1.	Sanskrit Education
Sanskrit should be made a compulsory subject in the Secondary School ç
Curriculum.
The three Language Formula should be amended as follows:
a.
@NK = The Mother Tongue (or the regional Language<%16>)<%0>;
b.
@NK = English;
c.
@NK = Sanskrit (or a classical language as equivalent to Sanskrit).
The traditional P<193><219>ha·<193>l<193> system should be continued ç
and preserved. It should be reorganised so as to include some modern ç
subjects like the mother-tongue, English, General Science, Mathematics ç
and Social Studies including Ancient Indian History and Culture.
The Pandit-Teachers should undergo a course of Teachers' Training.
The remodelled Sanskrit High Schools or remodelled P<193><219>ha·<193>l<193>s ç
should lead to Sanskrit Colleges.
The Pandit-Teachers should be treated as equal to Graduate-Teachers ç
in all respects.
In the College course leading up to the Graduate and Post-graduate ç
Degrees there should be a provision for the study of Sanskrit under ç
general as well as special subjects.
The  P<193><219>ha·<193>l<193>  system  and  the University systems ç
should be retained as separate units, but gradually reformed tobring ç
about greater measure of co- operation between them.
The P<193><219>ha·<193>l<193> Pandits should be employed to teach ç
in the modern Colleges and the professors of the latter, in the P<193><219>ha·<193>l<193>s, ç
for the betterment of both the systems.
In the Degree and Post-graduate courses in Indian languages and Humanities, ç
Sanskrit also should be one subject.
There should be an investigation into the methods of teaching Sanskrit ç
to different categories of students, Indian and foreign.
The P<193><219>ha·<193>l<193> System has to be reformed by having ç
Sanskrit as the medium of instruction, at least at the higher level, ç
by introducing some subjects connected with Western thought and also ç
by adding suitable extra-curricular activities. The examination system ç
too needs drastic change. Oral examination of the old <185><193>str<193>rtha ç
type (discussion and disputation on holy texts) should be a part of ç
this new system of testing.
@S10N = 2.	Sanskrit Research
P<193><219>ha·<193>l<193> Pandits too should be giventhe same facilities ç
for Research in the Universities and Colleges.
@SPACE1 = 
@SPACE1 = 
High-grade Sanskrit Colleges with reputed Pandits on their staffs ç
and well-equipped libraries should be recognised by the Universities ç
for Research.
@SPACE1 = 
@SPACE1 = 
Critically editing and publishing rare manuscripts, starting of Research ç
Journals in Sanskrit, opening of Research Departments for different ç
<185><193>stras should be encouraged.
@SPACE1 = 
New Research Degrees like M.Litt., and D.Litt., should be introduced, ç
both having viva voce tests. Attention should be paid to the many ç
neglected fields demanding investigation by Research scholars. For ç
instance: Vedic Rituals; Kalpas<220>tras; <185>ilpa (Sculpturing); ç
Jyauti<218>a (Astronomy);   Iconography;   Sa<209>g<200>ta (Music); ç
N<193><219>ya (Dancing).
@SPACE1 = 
@SPACE1 = 
Greater facilities should be offered for the publication of the results ç
of Research.
@SPACE1 = 
@SPACE1 = 
Manuscript libraries should be helped to bring out inventories and ç
even publications of the rare works.
@SPACE1 = 
@SPACE1 = 
Non-official Sanskrit and Indological Institutes in the country should ç
be brought under a comprehensive scheme of co- ordination and assisted ç
with liberal grants. A Central Institute of Indology should be established, ç
its core-section being devoted to Sanskrit.
@SPACE1 = 
@SPACE1 = 
The All-India Oriental Conference should be placed on a permanent ç
basis with adequate financial assistance. It should be encouraged ç
to invite scholars from other Asian Countries.
@SPACE1 = 
@SPACE1 = 
Suitable Prizes and Awards should be instituted for Sanskrit and Indological ç
work.
@S10N = 3.	Manuscripts
@SPACE1 = 
@SPACE1 = 
A Central Manuscripts Survey should be established with branches in ç
different regions of the country. Its work should consist of Search, ç
Survey, Collection, Safeguard, Cataloguing and Publication of the ç
Manuscripts of Sanskrit and allied works.
The flow of manuscripts to foreign countries must be prevented by ç
all means.
The Manuscript Libraries should givefacilities to bona fide scholars ç
and institutions to consult or borrow them.
@SPACE = 
@S10N = 4.	Sanskrit Universities
Sanskrit  Universities  should  be established in different areas ç
to tone up and upgrade the traditional system of Sanskrit Education. ç
They should be the apex of the reorganised P<193><219>ha·<193>l<193> ç
system. They should co-ordinate the working of the P<193><219>ha·<193>l<193>s ç
and Sanskrit Colleges. They should also function as Centres of Higher ç
Learning and Research in Sanskrit.
All the Sanskrit Universities should be under the aegis of the Central ç
Sanskrit Board, which must be a Statutory Body.
They should adopt Sanskrit medium at all levels, academic as well ç
as non- academic. They should also produce books in Sanskrit embodying ç
modern knowledge.
The Central Government should givea lead by establishing a centrally ç
administered Sanskrit University, preferably in South India.
@SPACE = 
@S10N = 5.	General
Sanskrit should be declared as an Additional Official Language.
Sanskrit should be officially used on all ceremonial occasions.
The infinite resources of Sanskrit literature like the Subh<193><218>itas ç
should be utilised in Schools and Colleges for moral instruction.
Efforts should be made to teach a Uniform  Standard  Pronunciation  of ç
Sanskrit in all parts of the country, by employing qualified readers ç
and teachers in areas where it is defective.
A comprehensive English-Sanskrit Dictionary of Scientific and Technical ç
Terms should be compiled with the help of suitable experts.
Personnel recruited for the Indian Administrative and Foreign Services ç
should be given opportunities through special courses of lectures ç
to acquire adequate knowledge of Sanskrit thought and Indian Culture. ç
Same policy can be adopted with regard to Indian students going abroad ç
for higher studies.
Indian Embassies abroad must haveCultural Attach<F14>Ç<F255>s possessing ç
special competence in Sanskrit Language, Literature and Culture.
Special attention should be made to preserve the Oral Tradition of ç
the different Vedas and their recensions as current in different parts ç
of India; and especially the S<193>maveda. Tape-recordings can be ç
made through the All India Radio*.
Steps should be taken to train the required personnel for the exposition ç
of Itih<193>sa-Pur<193><207>a. P<193><219>ha·<193>l<193>s should introduce ç
this also among their regular courses.
Gifted exponents of the R<193>m<193>ya<207>a, the Mah<193>bh<193>rata, ç
the G<200>t<193> and the pur<193><207>as should be employed in Community ç
Projects and National Extension Service Schemes to spread our culture ç
among the masses.
Courses in Paurohitya and Karma-k<193><207><195>a must be introduced ç
in the P<193><219>ha·<193>l<193>s.
Students  of  modern  science  and technology should be made familiar ç
with the developments made in our ancient and medieval periods as ç
per the standard works produced then.
Sanskrit should be popularised by adopting suitable measures. Some ç
of themare: organisation of private classes; producing Popular Sanskrit ç
booklets and selections with translations; celebration ofdays in ç
commemoration of important Sanskrit writers and works; simplification ç
of the methods of teaching Sanskrit; Sanskrit Literary Conferences; ç
promotion of Sanskrit debates and original writings in Sanskrit; competitions ç
in short stories, plays etc., in Sanskrit; musical recitals ofSanskrit ç
classics; enacting Sanskrit Dramas.
Important Sanskrit texts which are no longer available, should be ç
brought out in new editions by the Sahitya Akademi and other bodies.
@S10N = 6.	Administration and Organisation
A number of Trusts and Endowments formed for the promotion of Sanskrit ç
and allied purposes, now lying dormant, should be unearthed and be ç
put to use to implement the various proposals given in this report.
A Central Sanskrit Board should be constituted and run on the lines ç
of the University Grants Commission. It should concern itself mainly ç
with P<193><219>ha·<193>l<193> education and privately organised Research ç
Institutes in the country, by helping them in all possible manners. ç
It should be vested with the authority to sanction the starting of ç
Sanskrit Universities, to recognise them as statutory bodies, to give ç
them suitable grants and generally to control their working. It should ç
also co-operate with the Central Institute of Indology and the Central ç
Manuscripts Survey.
@SPACE1 = 
@SPACE1 = 
A separate Ministry of Culture should be created in the Central Government ç
andplace all cultural affairs, (now spread over various departments ç
or ministries) under it.
@SPACE1 = 
@SPACE1 = 
In the National Plans adopted by the Government, substantial amounts ç
should be set apart for the development and promotion of Sanskrit ç
on the lines set forth in this Report.
@SPACE = 
@SPACE = 
@SB = Epilogue
@SPACE1 = 
@SPACE1 = 
Since the dawn of political indepen-dence, several Commissions have ç
been constituted both by the Central and the State Governments, concerning ç
various issues facing the country. However, eventhough those Commissions ç
with distinguished persons had given very valuable reports, not many ç
of the recommendations have been implemented due to various factors ç
including narrow political conside-rations. Unfortunately, most of ç
the recommendations of this Report also have remained till now, on ç
paper only. It needs true patriotism and statesmanship to appreciate ç
and implement this magnificent Report, magnificent in the truest sense ç
of the term.
@NT = <185><193>ntimantras
@N1 = (`peace-chants')
@SB = Introduction
The <185><193>ntimantras are certain hymns chosen from the Vedic literature. ç
They are generally chanted at the beginning and end of Vedic studies, ç
during certain ceremonies called ·<193>ntikarmas (propitiatory rites), ç
while doing abhi<218>eka (bathing the image) in worship and in certain ç
vratas (religious vows and observances).
@SPACE1 = 
The number of such mantras as available now is fourteen. Sometimes ç
ten mantras from this are separated and designated as Da·a·<193>ntis.
@SPACE1 = 
All the mantras end with the words O<221> ·<193>nti<199> ·<193>nti<199> ç
·<193>nti<199>.
@SPACE1 = 
The word O<221> when split into its three syllables†a, u and ç
m†gives this meaning: Brahman is different from all that we know. ç
It is the very best. It is of the nature of knowledge.
@SPACE1 = 
Similarly, the word ·<193>nti<199> when split into ·a, anta ç
and i gives the meaning that Brahman or God is the acme of knowledge ç
and bliss.
@SPACE1 = 
These <185><193>ntimantras may now be dealt withhere:
@SPACE = 
@N-1 = 1.
@SANK = DeeW me<$!N><F48>a<F255><$!N>n vee<$!N><F48>b<F255><$!N>JeJeleg~ me<$!N><F48>a<F255><$!N>n ç
veew<$!N><F48>j <F255><$!N>Yegveke<172>leg~ me<$!N><F48>a<F255><$!N>n Jeer<$!N><F48>a<F255><$!N>ìeÖ<$!N><F48>j ç
<F255><$!N>ke†jJeeJenw~ les<$!N><F48>a<F255><$!N>pe<$!N><F48>a<F255><$!N>efmJevee<$!N><F48>a<F255><$!N>JeOeer<$!N><F48>j<F255><$!N>lecemleg<$!N><F48W1>l<F255D><$!N> ç
cee efJe<$!N><F48>b<F255><$!N>ef<188>- <<ee<$!N><F48>a<F255><$!N>Jenw<$!N><F48>k<F255><158> ç
DeeW Meeefvle<F48W1><$!N><F48W1>a<F255D><203> <$!N>Meeefvle<F48W1>a<F255D><203> <$!N>Meeefvl<F48W1>b<F255D>e<203><158><$!SD><$!PFE48>
@PI-1 = o<221> <F49P12M>a<F255P255D>saha n<F49P12M>b<F255P255D><193>vavatu<F49P12M>e<F255P255D> ç
<F49P12M>a<F255P255D>saha n<F49P12M>b<F255P255D>au bhunaktu<F49P12M>e<F255P255D> <F49P12M>a<F255P255D>saha ç
<F49P12M>a<F255P255D>v<200>ry<F49P12M>b<F255P255D>a<221> karav<193>vahai<F49P12M>e<F255P255D> ç
<F49P12M>a<F255P255D>te<F49P12M>a<F255P255D>jasvi<F49P12M>a<F255P255D>n<193>vad<F49P12MJ251>b<F255P255DJ0>h<200>tamas<F49P12M>a<F255P255D>tu ç
m<193> <F49P12M>b<F255P255D>vidvi- <F49P12M>a<F255P255D><218><193>vah<F49P12M>c<F255P255D>ai<F49P12M>f<F255P255D> ç
o<221> ·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P13M>b<F255P255D>ti<199><F49P12M>f<F255P255D><$!SD><$!SD><F49P12M>
@IN2 = <+><+><+>``May He protect us both together; may He nourish us ç
both together; may we work conjointly with great energy; may our studybe ç
vigorous and effective; may we not hate any.''
@SPACE = 
This is undoubtedly the most popular and oft-repeated ·<193>ntimantra.
It belongs to the K<216><218><207>a Yajurveda.
The word ·<193>nti<199> is repeated thrice, thereby praying for ç
peace in oneself, in the environment and in the forces that act on ç
both.
It should be noted that the teacher and the disciple are praying together ç
for protection, nourishment and good mutual relationship. Also, that ç
their conjoint study should become effective in their lives.
@N-1 = 2.
@SANK = <$!SD><$!PFE48><$!SD>DeeW <$!N>Meb vees<$!N><F48>b <F255><$!N>efce<$!N><F48>a<F255><$!N>$e<203> ç
Meb Jeâ<$!N><F48>b<F255><$!N>Ce<203>~ Meb vees<$!N><F48>b <F255><$!N>YeJelJeìe&<$!N><F48>a<F255><$!N>cee~ ç
Meb ve<$!N><F48>a <F255><$!N>Fv<202>es<$!N><F48>a <F255><$!N>ye=n<$!N><F48>a<F255><$!N>mheefl<F48W1>b<F255D>e<203><$!N>~ ç
Meb vees<$!N><F48>a <F255><$!N>efJe<<Ceg<$!N><F48>b<F255><$!N>ââåe†<$!N><F48>a<F255><$!N>ce<203>~ ç
vecees<$!N><F48>a <F255><$!N>yeî<207>e<$!N><F48>b<F255><$!N>Ces~ vece<$!N><F48>b<F255><$!N>mles ç
Jeeìees~ lJeces<$!N><F48>a<F255><$!N>Je <178>e<$!N><F48>a<F255><$!N>lìe#eb<$!N><F48>a ç
<F255><$!N>yeî<207>ee<$!N><F48>b<F255><$!N>efme~ lJeeces<$!N><F48>a<F255><$!N>Je <178>e<$!N><F48>a<F255><$!N>lìe#eb<$!N><F48>a ç
<F255><$!N>yeî<207>e<$!N><F48>b <F255><$!N>Jeefo<<ìeeefce~ $e+<$!N><F48>a<F255><$!N>leb ç
Je<$!N><F48>b<F255><$!N>efo<<ìeeefce~ me<$!N><F48>a<F255><$!N>lìeb Je<$!N><F48>b<F255><$!N>efo<<ìeeefce~ ç
levceece<$!N><F48>b<F255><$!N>Jeleg~ le<188><$!N><F48>a<F255><$!N>ke<172>leej<$!N><F48>b<F255><$!N>ceJeleg~ ç
DeJe<$!N><F48>b<F255><$!N>leg<$!N><F48>l <F255><$!N>ceeced~ DeJe<$!N><F48>b<F255><$!N>leg ç
Je<$!N><F48>a<F255><$!N>ke<172>leejced<$!N><F48>c<F255><$!SD><158> DeeW Meeefvle<F48W1><$!N><F48W1>a<F255D><203> ç
<$!N>Meeefvle<F48W1>a<F255D><203> <$!N>Meeefvl<F48W1>b<F255D>e<203><158>
@PI-1 = o<221> ·a<221> <F49P12M>b<F255P255D>no <F49P12M>a<F255P255D>mitra<199> ·a<221> ç
va<F49P12M>b<F255P255D>ru<207>a<199><F49P12M>e<F255P255D> ·a<221> <F49P12M>b<F255P255D>no ç
bhavatvar<F49P12M>a<F255P255D>yam<193><F49P12M>e<F255P255D> ·a<221> <F49P12M>a<F255P255D>na ç
in<F49P12M>a<F255P255D>dro b<216><F49P12M>a<F255P255D>haspat<F49P12M>b<F255P255D>i<199><F49P12M>e<F255P255D> ç
·a<221> <F49P12M>a<F255P255D>no vi<218><F49P12M>b<F255P255D><207>ururuk<F49P12M>a<F255P255D>rama<199><F49P12M>e<F255P255D> ç
na<F49P12M>a<F255P255D>mo bra<F49P12MJ252>b<F255P255DJ0>hma<207>e<F49P12M>e<F255P255D> ç
na<F49P12M>b<F255P255D>maste v<193>yo<F49P12M>e<F255P255D> tva<F49P12M>a<F255P255D>meva ç
p<F49P12M>a<F255P255D>ratyak<F49P12M>a<F255P255D><218>a<221> bra<F49P12MJ252>b<F255P255DJ0>hm<193>si<F49P12M>e<F255P255D> ç
tv<193><F49P12M>a<F255P255D>meva <F49P12M>a<F255P255D>pratyak<F49P12M>a<F255P255D><218>a<221> ç
bra<F49P12MJ252>b<F255P255DJ0>hma vadi<218>y<193>mi<F49P12M>e<F255P255D> <F49P12M>a<F255P255D><216>ta<221> ç
<F49P12M>b<F255P255D>vadi<218>y<193>mi<F49P12M>e<F255P255D> <F49P12M>a<F255P255D>satya<221> ç
<F49P12M>b<F255P255D>vadi<218>y<193>mi<F49P12M>e<F255P255D> tanm<193><F49P12M>b<F255P255D>mavatu<F49P12M>e<F255P255D> ç
tad<F49P12M>a<F255P255D>vakt<193><F49P12M>b<F255P255D>ramavatu<F49P12M>e<F255P255D> a<F49P12M>b<F255P255D>va<F49P12M>a<F255P255D>tu ç
m<193>m<F49P12M>e<F255P255D> a<F49P12M>b<F255P255D>vatu <F49P12M>a<F255P255D>vakt<193>ra<F49P12M>c<F255P255D>m<F49P12M>f<F255P255D> ç
o<221>·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P13M>b<F255P255D>ti<199><F49P12M>f
@SPACE1 = 
@IN2 = <+><+><+>``May Mitra (the sun) be propitious to us; may Varu<207>a ç
be propitious to us. May Aryam<193>n (a form of the sun) be propitious ç
to us; may Indra and B<216>haspati be propitious to us. May Vi<218><207>u ç
of giant steps, be propitious to us.
@SPACE1 = 
@IN2 = <+><+><+>``Salutation to Brahm<193>. Salutation to thee, O V<193>yu, ç
Thou indeed art the perceptible Brahman. Of thee indeed, the perceptible ç
Brahman, will I speak. I will speak of the right. Iwill speak of ç
the true; may that protect me. May that protect the speaker. Let that ç
protect me. Let that protect the speaker.''
@SPACE1 = 
@SPACE = 
This also is a popular mantra. It forms the very first stanza of the ç
Taittir<200>ya Upani<218>ad. The first part of the mantra appears ç
in the <184>gveda (1.90.9) also.
@SPACE1 = 
Indra, Mitra, Varu<207>a, B<216>haspati, Vi<218><207>u and Aryam<193> ç
are the deities presiding over cosmic powers and the corres-ponding ç
functions of the human body. For instance, Aryam<193> controls the ç
sun and thehuman eye. The other deities likeB<216>haspati who controls ç
speech and intellect, Indra who controls strength ofbody are also ç
being mentioned and propitiated. If they are pleased, the body-mind ç
complex will be in good condition and knowledge will be gained effectively.
@SPACE1 = 
@SPACE = 
@N-1 = 3.
@SANK = Deesced<158> Ye<$!N><F48>a<F255><$!N><202>b ke†Cex<$!N><F48>j<F255><$!N>efYe<203> ç
Me=Ceg<$!N><F48>l<F255><$!N>ìeece<$!N><F48>b <F255><$!N>osJee<203>~ Ye<$!N><F48>a<F255><$!N><202>b ç
he<$!N><F48>b<F255><$!N>Mìescee<$!N><F48>a<F255><$!N>#eefYe<$!N><F48>a<F255><$!N>ìe&pe<$!N><F48>b<F255><$!N>$ee<203>~ ç
efmLe<$!N><F48>a<F255><$!N>jwjíw<$!N><F48>k<F255><$!N>mleg<196>g<$!N><F48>l<F255><$!N>Jeeiedb ç
me<$!N><F48>b<F255><$!N>mle<$!N><F48>a<F255><$!N>- vetefYe<F48W1>b<F255D><203><$!N><$!N>~ ç
JìeMes<$!N><F48>b<F255><$!N>ce os<$!N><F48>a<F255><$!N>Jeefn<$!N><F48>b<F255><$!N>leb<$!N><F48>a ç
<F255><$!N>ìeoeìeg<F48W1>b<F255D><203><158> <$!SD>mJe<$!N><F48>a<F255><$!N>efmle ve<$!N><F48>a ç
<F255><$!N>Fv<202>es<$!N><F48>b <F255><$!N>Je=<$!N><F48>l<F255><$!N><183><190>e<$!N><F48>b<F255><$!N>Jee<203>~ ç
mJe<$!N><F48>a<F255><$!N>efmle ve<F48W1>b<F255D><203><$!N> <$!N>het<$!N><F48>l<F255><$!N><<ee ç
efJe<$!N><F48>a<F255><$!N><201>eJes<$!N><F48>b<F255><$!N>oe<203>~ mJe<$!N><F48>a<F255><$!N>efmle ç
ve<$!N><F48>a<F255><$!N>mlee#ìe<F48W1>a<F255D>es&<$!N><F48> <F255><$!N>Deefj<$!N><F48>b<F255><$!N><196>vesefce<203>~ ç
mJe<$!N><F48>a<F255><$!N>efmle vees<$!N><F48>a <F255><$!N>ye=n<$!N><F48>a<F255><$!N>mheefle<$!N><F48>b<F255><$!N>o&Oeeleg<158> ç
DeeW Meeefvle<F48W1><$!N><F48W1>a<F255D><203> <$!N>Meeefvle<F48W1>a<F255D><203> <$!N>Meeefvl<F48W1>b<F255D>e<203><158>
@PI-1 = <$!SK><$!SK><$!PFE48><$!SD>o<221> <F49P12M>a<F255P255D>bhadra<221> ç
kar<F49P12M>b<F255P255D><207>ebhi··<216><F49P12M>a<F255P255D><207>uy<193><F49P12M>b<F255P255D>ma ç
dev<193><199><F49P12M>e<F255P255D> <F49P12M>a<F255P255D>bhadra<221> <F49P12M>b<F255P255D>pa·ye<F49P12M>a<F255P255D>m<193>k<218>a<F49P12M>a<F255P255D>bhirya- ç
<F49P12M>b<F255P255D>jatr<193><199><F49P12M>e<F255P255D> <F49P12M>a<F255P255D>sthiraira<209><F49P12M>c<F255P255D>ga<200>stu<218><F49P12M>a<F255P255D><219>uv<193>g<221>- ç
<F49P12M>b<F255P255D>sa<F49P12M>a<F255P255D>stan<220>b<F49P12MJ252>b<F255P255DJ0>hi<199><F49P12M>e<F255P255D> ç
vya<F49P12W1J251>b<F255P255DJ0>·ema <F49P12M>a<F255P255D>deva<F49P12MJ252>b<F255P255DJ0>hi<F49P12M>a<F255P255D>ta<221> ç
yad<193><F49P12M>b<F255P255D>yu<199><F49P12M>f<F255P255D> <F49P12M>a<F255P255D>svasti <F49P12M>a<F255P255D>na ç
in<F49P12MJ252>b<F255P255DJ0>dro <F49P12M>a<F255P255D>v<216>ddha- <F49P12MJ252>b<F255P255DJ0>·rav<193><199><F49P12M>e<F255P255D> ç
<F49P12M>a<F255P255D>svasti <F49P12M>b<F255P255D>na<199> <F49P12M>a<F255P255D>p<220><218><193> ç
<F49P12M>a<F255P255D>vi·va<F49P12M>b<F255P255D>ved<193><199><F49P12M>e<F255P255D> <F49P12M>a<F255P255D>svasti ç
<F49P12M>a<F255P255D>nast<193>r<F49P12M>a<F255P255D>k<218>yo a<F49P12M>b<F255P255D>ri<218><219>anemi<199><F49P12M>e<F255P255D> ç
<F49P12M>a<F255P255D>svasti <F49P12M>a<F255P255D>no b<216><F49P12M>a<F255P255D>haspa<F49P12M>b<F255P255D>tirdadh<193>tu<F49P12M>f<F255P255D> ç
o<221> ·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P13M>b<F255P255D>ti<199><F49P12M>f<+>
@SPACE = <+><+>
@IN2 = <+><+><+>``May we, O gods, hear what is auspicious with our ears. ç
O ye, who are worthy of worship, may we see with our eyes what is ç
auspicious. May we enjoy the life allotted to us by the gods, offering ç
praise, with our bodies strong of limb.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@IN2 = <+><+><+>``May Indra, of great fame, bestow prosperity on us. ç
May P<220><218>an, the knower of all, bestow prosperity on us. May ç
T<193>rk<218>ya, of unobstructed path, bestow prosperity on us. May ç
B<216>haspati bestow prosperity on us.''
@SPACE = 
@SPACE1 = 
This ·<193>ntimantra belongs to the Atharvaveda.
@SPACE1 = 
@SPACE1 = 
The very tone and tenor of this mantra shows that the Vedic <216><218>is ç
were not melancholic defeatists but wanted to lead a full life, with ç
all the vigour at their command.
Only when the limbs and the senses are strong, and the duration of ç
life is long, one can achieve great things in life.
For this, the grace of the various cosmic deities is also needed. ç
Hence the prayer to them.
@N-1 = 4.
@SANK = DeeW leé<205>b<$!N><F48>a<F255><$!N>ìeesjeJe=<$!N><F48>b<F255><$!N>Ceercens~ ç
iee<$!N><F48>a<F255><$!N>legb ìe<$!N><F48>a<F255><$!N>%eeìe<$!N><F48>b<F255><$!N>~ iee<$!N><F48>a<F255><$!N>legb ç
ìe<$!N><F48>a<F255><$!N>%ehe<$!N><F48>b<F255><$!N>leìes~ owJeer<$!N><F48>k <F255><$!N>mJe<$!N><F48>a<F255><$!N>efmlej<$!N><F48>b<F255><$!N>mleg ç
ve<203>~ mJe<$!N><F48>a<F255><$!N>efmle- cee&veg<$!N><F48>b<F255><$!N><<esYìe<203>~ ç
T<$!N><F48>a<F255><$!N>OJeÖ efpe<$!N><F48>b<F255><$!N>ieeleg Yes<<e<$!N><F48>a<F255><$!N>peced~ ç
Meb vees<$!N><F48>b <F255><$!N>Demleg ef<188><$!N><F48>a<F255><$!N>heos<$!N><F48>c<F255><$!N>~ ç
Meb éeleg<$!N><F48>b<F255><$!N><<heos<158> DeeW Meeefvle<F48W1><$!N><F48W1>a<F255D><203> ç
<$!N>Meeefvle<F48W1>a<F255D><203> <$!N>Meeefvl<F48W1>b<F255D>e<203><158>
@PI-1 = o<221> tac<F49P12M>a<F255P255D>cha<221>yor<193><F49P12M>b<F255P255D>v<216><207><200>mahe<F49P12M>e<F255P255D> ç
<F49P12M>a<F255P255D>g<193>tu<221> <F49P12M>a<F255P255D>yaj<210><193><F49P12M>b<F255P255D>ya<F49P12M>e<F255P255D> ç
<F49P12M>a<F255P255D>g<193>tu<221> <F49P12M>a<F255P255D>yaj<210>a<F49P12M>b<F255P255D>pataye<F49P12M>e<F255P255D> ç
dai<F49P12M>c<F255P255D>v<200> <F49P12M>a<F255P255D>svasti<F49P12M>b<F255P255D>rastu na<199><F49P12M>e<F255P255D> ç
<F49P12M>a<F255P255D>svastirm<193><F49P12M>b<F255P255D>nu- <218>ebhya<199><F49P12M>e<F255P255D> ç
<F49P12M>a<F255P255D><220>rdhva<221> <F49P12W1J247>b<F255P255DJ0>jig<193>tu bhe<F49P12M>a<F255P255D><218>ajam<F49P12M>e<F255P255D> ç
·a<221> <F49P12M>b<F255P255D>no astu <F49P12M>a<F255P255D>dvipa<F49P12W1J247>c<F255P255DJ0>de<F49P12M>e<F255P255D> ç
·a<221> ca<F49P12M>b<F255P255D>tu<218>pade<F49P12M>f<F255P255D> o<221> ·<193>n<F49P12M>a<F255P255D>ti<199> ç
·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P13M>b<F255P255D>ti<199><F49P12M>f<F255P255D><$!SD><$!PFE48><$!SD><$!SD>
@IN2 = <+><+><+>``We pray to God who can destroy our sorrows and grant ç
us happiness. We also pray that the doer of sacrifice gets the very ç
best fruits from the sacrifice. Let us get divine auspiciousness. ç
Let all the human beings also get auspiciousness. In future also, ç
let all our troubles be remedied. Let all human beings attain happiness. ç
Let all our animals attain happiness.''
@SPACE = 
@SPACE = 
This ·<193>ntimantra is chanted at the beginning and at the end of ç
the famous Puru<218>as<220>kta.
It is used during abhi<218>eka (bathing the image in ritualistic worship) ç
as also in the Sandhy<193> ritual for praying to the Sun in the standing ç
posture (upasth<193>na).
The first sentence of the text is sometimes interpreted as follows: ç
``I choose to perform (and pray to the fire) the °ru<207>aketuka ritual ç
to get rid of all diseases brought about by karma, now or in the future.''
@SPACE = 
@N-1 = 5.
@SANK = DeeW vecees<$!N><F48>a <F255><$!N>yeî<207>e<$!N><F48>b<F255><$!N>Ces<$!N><F48>a ç
<F255><$!N>vecees<$!N><F48>b <F255><$!N>DemlJe<$!N><F48>a<F255><$!N>iveìes<$!N><F48>a <F255><$!N>vece<F48W1>b<F255D><203> ç
<$!N>he=efLe<$!N><F48>a<F255><$!N>Jìew vece<$!N><F48>a <F255><$!N>Dees<<e<$!N><F48>b<F255><$!N>OeerYìe<203>~ ç
vecees<$!N><F48>b <F255><$!N>Jee<$!N><F48>a<F255><$!N>ées vecees<$!N><F48>b <F255><$!N>Jee<$!N><F48>a<F255><$!N>éemhele<$!N><F48>b<F255><$!N>ìes<$!N><F48>a ç
<F255><$!N>vecees<$!N><F48>a <F255><$!N>efJe<<Ce<$!N><F48>b<F255><$!N>Jes ye=n<$!N><F48>a<F255><$!N>les ç
ke†<$!N><F48>b<F255><$!N>jesefce<158> DeeW Meeefvle<F48W1><$!N><F48W1>a<F255D><203> ç
<$!N>Meeefvle<F48W1>a<F255D><203> <$!N>Meeefvl<F48W1>b<F255D>e<203><158>
@PI-1 = <$!SD><$!PFE48>o<221> na<F49P12M>a<F255P255D>mo bra<F49P12MJ252>b<F255P255DJ0>hma<F49P12M>a<F255P255D><207>e ç
na<F49P12M>b<F255P255D>mo a<F49P12M>a<F255P255D>stvagna<F49P12M>a<F255P255D>ye na<F49P12M>b<F255P255D>ma<199> ç
p<216><F49P12M>a<F255P255D>thivyai na<F49P12M>a<F255P255D>ma o<F49P12M>b<F255P255D><218>adh<200>bhya<199><F49P12M>e<F255P255D> ç
na<F49P12M>b<F255P255D>mo <F49P12M>a<F255P255D>v<193>ce na<F49P12M>b<F255P255D>mo <F49P12M>a<F255P255D>v<193>caspa<F49P12M>b<F255P255D>ta<F49P12M>a<F255P255D>ye ç
na<F49P12M>a<F255P255D>mo vi<218><F49P12M>b<F255P255D><207>ave b<216><F49P12M>a<F255P255D>hate ç
<F49P12MJ252>b<F255P255DJ0>karomi<F49P12M>f<F255P255D> o<221> ·<193>n<F49P12M>a<F255P255D>ti<199> ç
·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P13M>b<F255P255D>ti<199><F49P12M>f
@SPACE = <$!SD>
@IN2 = <+><+><+>``Obeisance to the creator Brahm<193>. Obeisance to Agni ç
(the fire-god). Obeisance to the (Mother) Earth. Obeisance  to  plants,  trees  and ç
creepers. I bow down to the (organ of) speech and to the presiding ç
deity of speech. I(also) bow down to Vi<218><207>u the all-pervading ç
Cosmic Being.''
@SPACE = 
This is a prayer for grace, expressing one's gratefulness not only ç
to God but also to all thepowers of nature to which we are always ç
indebted.
Agni or fire (deity) is all important in Vedic rituals. It is he who ç
carries the offerings to the various gods.
The Earth, conceived as our mother, supports us.
Vegetation sustains our life.
The organ of speech and the power (the presiding deity) behind it ç
help us to acquire knowledge and perform the Vedic rituals.
And of course, God, the all-pervading Cosmic Being, is the very goal ç
of our life.
@N-1 = 6.
@SANK = Deesced F[e<$!N><F48>b <F255><$!N>osJe<$!N><F48>a<F255><$!N>ntce&veg<$!N><F48>b<F255><$!N>ìe&%e<$!N><F48>a<F255><$!N>veerye=&n<$!N><F48>a<F255><$!N>mheefle<$!N><F48>b<F255><$!N>âke<172>Leece<$!N><F48>a<F255><$!N>oeefve<$!N><F48>b ç
<F255><$!N>Meiedbefme<<e<$!N><F48>a<F255><$!N>ef<188><201>es<$!N><F48>b<F255><$!N>os<$!N><F48>a<F255><$!N>Jeemmet<$!N><F48>c<F255><$!N>ke<172>le<$!N><F48>a<F255><$!N>Jeeée<203><$!N><F48>a ç
<F255><$!N>he=efLe<$!N><F48>b<F255><$!N>efJe ceele<$!N><F48>a<F255><$!N>cee& cee<$!N><F48>b ç
<F255><$!N>efniedbmeer<$!N><F48>a<F255><$!N>ce&Oeg<$!N><F48>b <F255><$!N>ceefve<<ìes<$!N><F48>a ç
<F255><$!N>ceOeg<$!N><F48>b <F255><$!N>peefve<<ìes<$!N><F48>a <F255><$!N>ceOeg<$!N><F48>b ç
<F255><$!N>Je#ìeeefce<$!N><F48>a <F255><$!N>ceOeg<$!N><F48>b <F255><$!N>Jeefo<<ìeeefce<$!N><F48>a ç
<F255><$!N>ceOeg<$!N><F48>b<F255><$!N>celeeR os<$!N><F48>a<F255><$!N>JesYìees<$!N><F48>a ç
<F255><$!N>Jeeée<$!N><F48>b<F255><$!N>ceg<176>eemeiedb meg<190>et<F48W1>l<$!N><F48W1><F255D><<esCìeeb<$!N><F48>k ç
<F255><$!N>ceveg<$!N><F48>l<F255><$!N><<ìes<$!N><F48>k<F255><$!N>Yìe<$!N><F48>a<F255><$!N>mleb ç
cee<$!N><F48>b <F255><$!N>os<$!N><F48>a<F255><$!N>Jee De<$!N><F48>b<F255><$!N>Jevleg Mees<$!N><F48>a<F255><$!N>Yeeìew<$!N><F48>j ç
<F255><$!N>efhe<$!N><F48>a<F255><$!N>lejes<199>veg<$!N><F48>b<F255><$!N>ceovleg<158> ç
DeeW Meeefvle<F48W1><$!N><F48W1>a<F255D><203> <$!N>Meeefvle<F48W1>a<F255D><203> <$!N>Meeefvl<F48W1>b<F255D>e<203><158>
@PI-1 = o<221> i<F49P12MJ251>b<F255P255DJ0><195><193> de<F49P12M>a<F255P255D>vah<220>rma<F49P12M>b<F255P255D>nurya<F49P12M>a<F255P255D>j<210>an<200>r- ç
b<216><F49P12M>a<F255P255D>haspa<F49P12M>b<F255P255D>tirukth<193><F49P12M>a<F255P255D>mad<193><F49P12M>b<F255P255D>ni ç
·ag<221>si<F49P12M>a<F255P255D><218>a- dvi<F49P12W1J247>b<F255P255DJ0>·ve<F49P12M>a<F255P255D>dev<193><F49P12M>c<F255P255D>ss<220><F49P12M>a<F255P255D>ktav<193><F49P12M>a<F255P255D>ca<199> ç
p<216><F49P12W1J247>b<F255P255DJ0>thivi m<193>tarm<193> <F49P12M>b<F255P255D>ma ç
hig<221><F49P12M>a<F255P255D>s<200>rma<F49P12W1J247>b<F255P255DJ0>dhu mani<F49P12M>a<F255P255D><218>ye ç
ma<F49P12W1J251>b<F255P255DJ0>dhu jani<F49P12M>a<F255P255D><218>ye ma<F49P12W1J247>b<F255P255DJ0>dhu ç
vak<218>y<193><F49P12M>a<F255P255D>mi ma<F49P12W1J247>b<F255P255DJ0>dhu vadi<218>y<193><F49P12M>a<F255P255D>mi ç
ma<F49P12W1J247>b<F255P255DJ0>dhumat<200><221> <F49P12M>a<F255P255D>deve<F49P12M>a<F255P255D>bhyo ç
v<193><F49P12M>b<F255P255D>camudy<193>sag<221> ·u<F49P12M>a<F255P255D>·r<220>- <218>e<F49P12M>c<F255P255D><207>y<193><221> ç
ma<F49P12M>a<F255P255D>nu<F49P12M>c<F255P255D><218>ye<F49P12M>a<F255P255D>bhyasta<221> ç
<F49P12M>b<F255P255D>m<193> <F49P12M>a<F255P255D>dev<193> <F49P12M>b<F255P255D>avantu <F49P12M>a<F255P255D>·obh<193><F49P12M>b<F255P255D>yai ç
<F49P12M>a<F255P255D>pitaro'<F49P12M>b<F255P255D>numadantu<F49P12M>f<F255P255D> o<221> ç
·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P13M>b<F255P255D>ti<199><F49P12M>f<$!SD><F49P12M><$!SD><F49P12M>
@IN2 = <+><+><+>``Mother Veda invites the gods (for the sacrifice). The ç
Vedic mantras lead us to the performance of sacrifices. May God, the ç
lord of laudatory hymns, give us happiness (when we praise the deities ç
through hymns). May all the gods protect us by speaking to us with ç
words of blessings. O Mother Earth! Do not harm me! I meditate on ç
your benign form. Iwill compose sweet hymns (in praise of You). I ç
will utter sweet words, I will address others in sweet words. I will ç
offer sweet oblations with sweet words to gods presiding over the ç
rites. To men I will offer pleasant truths sweet to hear, not untruths. ç
So, may gods protect me who does what has been promised. May I shine ç
with fame. May the manes agree to this.''
The first part refers to the Vedic mantras which are used to invite ç
the gods and perform sacrifices.
The word B<216>haspati can refer to Brahma<207>aspati, the lord of ç
laudatory hymns.
It may also refer to God, the overseer of Vedic rituals.
`Vi·vedev<193><199>' may also refer to the group of ten deities who ç
are presiding over <216>ta or the cosmic law. Their sweet words act ç
as blessings upon us.
The  prayer  to  Mother  Earth  is because of the possibilities of ç
earthquake, floods, famine and other natural disasters.
Since the gods are propitious towards us, it is our duty to speak ç
sweetly, to praise them sweetly, to think of them with devotion.
It is also necessary to speak sweetly to fellow-human-beings.
So<|>also the proper performance of Vedic rites.
Hence the gods should protect me! And, the manes should appreciate ç
what Iam doing, with respect.
@N-1 = 7.<$!SD><$!PFE48><$!SD>
@SANK = Deesced ceOeg<$!N><F48>l<F255><$!N> Jeelee<$!N><F48>b <F255><$!N>$e+leeìe<$!N><F48>a<F255><$!N>les ç
ceOeg<$!N><F48>b<F255><$!N> #ejefvle<$!N><F48>a <F255><$!N>efmevOe<$!N><F48>b<F255><$!N>Je<203>~ ç
ceeOJeer<$!N><F48>k<F255><$!N>ve&<203> meb<$!N><F48>a<F255><$!N>lJees<<e<$!N><F48>b<F255><$!N>Oeer<203><158> ç
ceOeg<$!N><F48>l<F255><$!N> veke<172>le<$!N><F48>b<F255><$!N>ceg<$!N><F48>l<F255><$!N>lees<<emeer<$!N><F48>a ç
<F255><$!N>ceOeg<$!N><F48>b<F255><$!N>ce<$!N><F48>a<F255><$!N>lheee|Le<F48W1>j<F255D><$!N>Je<F48W1>a<F255D>iedb<$!N><F48W1>a<F255D> ç
jpe<F48W1>b<F255D><203><$!N><$!N>~ ceOeg<$!N><F48>l <F255><$!N><176>eewj<$!N><F48>b<F255><$!N>mleg ç
ve<203> efhe<$!N><F48>a<F255><$!N>lee<158> ceOeg<$!N><F48>b<F255><$!N>ceeVees<$!N><F48>a ç
<F255><$!N>Jeve<$!N><F48>a<F255><$!N>mheefle<$!N><F48>a<F255><$!N>ce&Oeg<$!N><F48>b<F255><$!N>ceeiedb ç
Demleg<$!N><F48>l <F255><$!N>metìe&<F48W1>j<F255D><203><$!N><$!N>~ ceeOJeer<$!N><F48>a<F255><$!N>iee&Jees<$!N><F48>b ç
<F255><$!N>YeJevleg ve<203><158> DeeW Meeefvle<F48W1><$!N><F48W1>a<F255D><203> <$!N>Meeefvle<F48W1>a<F255D><203> ç
<$!N>Meeefvl<F48W1>b<F255D>e<203><158><$!SD><$!SD>
@PI-1 = om ma<F49P12W1J247>a<F255P255DJ0>dhu v<193><F49P12M>b<F255P255D>t<193> <216>t<193><F49P12MJ251>a<F255P255DJ0>yate ç
ma<F49P12W1J247>b<F255P255DJ0>dhu k<218>aran<F49P12MJ251>a<F255P255DJ0>ti sin<F49P12W1J247>b<F255P255DJ0>dhava<199><F49P12M>e<F255P255D> ç
m<193><F49P12W1J247>c<F255P255DJ0>dhv<200>rna<199> <F49P12W1>a<F255P255D>santvo<F49P12M>b<F255P255D><218>adh<200><199><F49P12M>e<F255P255D> ç
ma<F49P12M>a<F255P255D>dhuna<F49P12W1J247>b<F255P255DJ0>kta<F49P12M>a<F255P255D>muto<218>as<200> ç
ma<F49P12W1J247>b<F255P255DJ0>dhu<F49P12M>a<F255P255D>matp<193>r<F49P12M>b<F255P255D>thi<F49P12M>a<F255P255D>va<F49P12M>a<F255P255D>g<221> ç
ra<F49P12J247>b<F255P255J0>ja<199><F49P12M>e<F255P255D> ma<F49P12M>a<F255P255D>dhu dyau<F49P12M>b<F255P255D>rastu ç
na<199> <F49P12M>a<F255P255D>pit<193><F49P12M>e<F255P255D> ma<F49P12J247>b<F255P255J0>dhum<193><F49P12M>a<F255P255D>nno ç
va<F49P12M>a<F255P255D>naspa<F49P12M>a<F255P255D>tirma<F49P12W1J247>b<F255P255DJ0>dhum<193>g<221> ç
a<F49P12M>a<F255P255D>stu s<220>r<F49P12M>b<F255P255D>ya<199><F49P12M>e<F255P255D> m<193><F49P12M>a<F255P255D>dhv<200>rg<193><F49P12M>b<F255P255D>vo ç
bhavanti na<199><F49P12M>f<F255P255D> o<221> ·<193>n<F49P12M>a<F255P255D>ti<199> ç
·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P13M>b<F255P255D>ti<199><F49P12M>f
@IN2 = <+><+><+>`<%12>`<%0>To us, who are the devotees of the Supreme ç
Truth, let the wind blow sweetly. Let the rivers run sweetly. Let ç
the herbs be to us sweet and beneficial. Let there be sweetness in ç
day and night. Let the particles of earth be sweetness-bearing. Let ç
heaven, our father, be sweet to us. Let the fruit-bearing trees be ç
sweet to us. Let the sun be sweet and beneficial to us. Let the cows ç
be sweetness-bearing to us.''
@SPACE = 
This mantra forms a part of the famous Trisupar<207>amantra (Mah<193>-n<193>r<193>ya<207>a  Upani<218>ad  38.4-6).  Just  as ç
Supar<207>a  or  Garu<195>a  protects  am<216>ta (ambrosia) these ç
mantras protect immortality for us.
These,  known  as  Madhumantras occur in the Taittir<200>ya Sa<221>hit<193> ç
(4.2.9) also.
The total idea seems to be that the whole world should be sweet or ç
comfortable for us.
According to one tradition, this mantra is chanted before taking food.
@N-1 = 8.
@SANK = DeeW vecees<$!N><F48>b <F255><$!N>Jee<$!N><F48>a<F255><$!N>ées ìeeéees<$!N><F48>b<F255><$!N>efo<$!N><F48>a<F255><$!N>lee ç
ìeeéeeveg<$!N><F48>b<F255><$!N>efolee<$!N><F48>a <F255><$!N>lemìew<$!N><F48>j <F255><$!N>Jee<$!N><F48>a<F255><$!N>ées ç
vecees<$!N><F48>a <F255><$!N>vecees<$!N><F48>b <F255><$!N>Jee<$!N><F48>a<F255><$!N>ées ç
vecees<$!N><F48>b <F255><$!N>Jee<$!N><F48>a<F255><$!N>éemhele<$!N><F48>b<F255><$!N>ìes<$!N><F48>a ç
<F255><$!N>vece<$!N><F48>a <F255><$!N>$e+ef<<e<$!N><F48>b<F255><$!N>Yìees cev$e<$!N><F48>a<F255><$!N>ke=†odYìees<$!N><F48>a ç
<F255><$!N>cev$e<$!N><F48>b<F255><$!N>heefleYìees<$!N><F48>a <F255><$!N>ceeceece=<<e<$!N><F48>b<F255><$!N>ìees ç
cev$e<$!N><F48>a<F255><$!N>ke=†lees<$!N><F48>b <F255><$!N>cev$e<$!N><F48>a<F255><$!N>hele<$!N><F48>b<F255><$!N>ìe<203><$!N><F48>a ç
<F255><$!N>heje<$!N><F48>b<F255><$!N>og<$!N><F48>l<F255><$!N>cee&nce=<<eer<$!N><F48>c<F255><$!N>vcev$e<$!N><F48>a<F255><$!N>ke=†lees<F48W1>b<F255D> ç
cev$e<$!N><F48>a<F255><$!N>heleer<$!N><F48>a<F255><$!N>ved heje<$!N><F48>b<F255><$!N>oeb ç
Jew<201>eos<$!N><F48>a<F255><$!N>JeeR Jeeée<$!N><F48>b<F255><$!N>ceg<176>eemeiedb ç
efMe<$!N><F48>a<F255><$!N>Jeeceo<$!N><F48>b<F255><$!N>mleeb<$!N><F48>a <F255><$!N>peg<196>eb<$!N><F48>k ç
<F255><$!N>os<$!N><F48>a<F255><$!N>JesYìe<203><$!N><F48>a <F255><$!N>Mece&<$!N><F48>j <F255><$!N>ces<$!N><F48>a ç
<F255><$!N><176>eewMMece&<$!N><F48>j <F255><$!N>he=efLe<$!N><F48>a<F255><$!N>Jeer Mece&<$!N><F48>a ç
<F255><$!N>efJe<201>e<$!N><F48>b<F255><$!N>efce<$!N><F48>a<F255><$!N>ob peie<$!N><F48>b<F255><$!N>led<$!N><F48>e ç
<F255><$!N>Mece&<$!N><F48>j <F255><$!N>ée<$!N><F48>a<F255><$!N>v<202>ùe<$!N><F48>a <F255><$!N>metìe&<$!N><F48>j<F255><$!N>ùe<$!N><F48>a ç
<F255><$!N>Mece&<$!N><F48>j <F255><$!N>yeî<207>e<178>epeehe<$!N><F48>a<F255><$!N>leer<158>
@SAN = <+><+><+><$!SD>Yet<$!N><F48>l<F255><$!N>leb Je<$!N><F48>b<F255><$!N>efo<<ìes<$!N><F48>a ç
<F255><$!N>YegJe<$!N><F48>b<F255><$!N>veb Jeefo<<ìes<$!N><F48>a <F255><$!N>lespees<$!N><F48>b ç
<F255><$!N>Jeefo<<ìes<$!N><F48>a <F255><$!N>ìeMees<$!N><F48>b <F255><$!N>Jeefo<<ìes<$!N><F48>a ç
<F255><$!N>lehees<$!N><F48>b <F255><$!N>Jeefo<<ìes<$!N><F48>a <F255><$!N>yeî<207>e<$!N><F48>b ç
<F255><$!N>Jeefo<<ìes me<$!N><F48>a<F255><$!N>lìeb Je<$!N><F48>b<F255><$!N>efo<<ìes<$!N><F48>a ç
<F255><$!N>lemcee<$!N><F48>b <F255><$!N>De<$!N><F48>a<F255><$!N>nefce<$!N><F48>a<F255><$!N>oceg<$!N><F48>b<F255><$!N>he<$!N><F48>a<F255><$!N>mlej<$!N><F48>b<F255><$!N>Ce<$!N><F48>a<F255><$!N>ceghe<$!N><F48>b<F255><$!N>mle=Ce ç
Ghe<$!N><F48>a<F255><$!N>mlej<$!N><F48>b<F255><$!N>Ceb ces <178>e<$!N><F48>a<F255><$!N>peeìew<$!N><F48>j ç
<F255><$!N>heMet<$!N><F48>l<F255><$!N>veeb Yet<$!N><F48>b<F255><$!N>ìeeoghe<$!N><F48>a<F255><$!N>mlej<$!N><F48>b<F255><$!N>Cece<$!N><F48>a<F255><$!N>nb ç
<178>e<$!N><F48>a<F255><$!N>peeìew<$!N><F48>j <F255><$!N>heMet<$!N><F48>l<F255><$!N>veeb ç
Yet<$!N><F48>b<F255><$!N>ìeemeb<$!N><F48>a <F255><$!N><178>eeCee<$!N><F48>b<F255><$!N>heeveew ç
ce=<$!N><F48>a<F255><$!N>lìeescee&<$!N><F48>j<F255><$!N>heeleb<$!N><F48>a <F255><$!N><178>eeCee<$!N><F48>b<F255><$!N>heeveew<$!N><F48>a ç
<F255><$!N>cee cee<$!N><F48>b <F255><$!N>neefme<196>b<$!N><F48>a <F255><$!N>ceOeg<$!N><F48>b ç
<F255><$!N>ceefve<<ìes<$!N><F48>a <F255><$!N>ceOeg<$!N><F48>b <F255><$!N>peefve<<ìes<$!N><F48>a ç
<F255><$!N>ceOeg<$!N><F48>b <F255><$!N>Je#ìeeefce<$!N><F48>a <F255><$!N>ceOeg<$!N><F48>b ç
<F255><$!N>Jeefo<<ìeeefce<$!N><F48>a <F255><$!N>ceOeg<$!N><F48>b<F255><$!N>celeeR os<$!N><F48>a<F255><$!N>JesYìees<$!N><F48>a ç
<F255><$!N>Jeeée<$!N><F48>b<F255><$!N>ceg<176>eemeiedb Meg<190>et<$!N><F48>l<F255><$!N><<esCìeeb<$!N><F48>k ç
<F255><$!N>ceveg<$!N><F48>l<F255><$!N><<ìes<$!N><F48>c<F255><$!N>Yìe<$!N><F48>a<F255><$!N>mleb ç
cee<$!N><F48>b <F255><$!N>os<$!N><F48>a<F255><$!N>Jee De<$!N><F48>b<F255><$!N>Jevleg Mees<$!N><F48>a<F255><$!N>Yeeìew<$!N><F48>j ç
<F255><$!N>efhe<$!N><F48>a<F255><$!N>lejes<199>veg<$!N><F48>b<F255><$!N>ceovleg<158> ç
DeeW Meeefvle<F48W1><$!N><F48W1>a<F255D><203> <$!N>Meeefvle<F48W1>a<F255D><203> <$!N>Meeefvl<F48W1>b<F255D>e<203><158>
@PI-1 = o<221> na<F49P12M>b<F255P255D>mo <F49P12M>a<F255P255D>v<193>ce y<193><F49P12M>b<F255P255D>co<F49P12M>a<F255P255D>dit<193> ç
y<193>c<193><F49P12M>b<F255P255D>nudi<F49P12M>a<F255P255D>t<193> ta<F49P12M>b<F255P255D>syai ç
<F49P12M>a<F255P255D>v<193>ce na<F49P12M>a<F255P255D>mo na<F49P12M>b<F255P255D>mo <F49P12M>a<F255P255D>v<193>ce ç
na<F49P12M>b<F255P255D>mo <F49P12M>a<F255P255D>v<193>caspa<F49P12M>b<F255P255D>ta<F49P12M>a<F255P255D>ye ç
na<F49P12M>a<F255P255D>ma <216><F49P12M>b<F255P255D><218>ibhyo man<F49P12M>a<F255P255D>tra- ç
k<216><F49P12M>a<F255P255D>dbhyo man<F49P12M>b<F255P255D>trapati<F49P12M>a<F255P255D>bhyo ç
m<193>m<193>- m<216><F49P12M>b<F255P255D><218>ayo man<F49P12M>a<F255P255D>trak<216><F49P12M>b<F255P255D>to ç
man<F49P12M>a<F255P255D>trapa<F49P12M>b<F255P255D>ta<F49P12M>a<F255P255D>ya<199> pa<F49P12M>b<F255P255D>r<193><F49P12M>a<F255P255D>durm<193>ham<216><F49P12M>c<F255P255D><218><200>nman<F49P12M>a<F255P255D>trak<216><F49P12M>b<F255P255D>to ç
man<F49P12M>a<F255P255D>trapa<F49P12M>a<F255P255D>t<200>n pa<F49P12M>b<F255P255D>r<193>d<193><221> ç
vai·va<F49P12M>a<F255P255D>dev<200><221> v<193><F49P12M>b<F255P255D>camudy<193>sag<221> ç
<F49P12M>a<F255P255D>·iv<193>ma<F49P12M>b<F255P255D>da<F49P12M>a<F255P255D>st<193><221> ç
ju<F49P12M>c<F255P255D><218><219><193><221> <F49P12M>a<F255P255D>deve<F49P12M>a<F255P255D>bhya<199> ç
·ar<F49P12M>b<F255P255D>ma <F49P12M>a<F255P255D>me dyau··ar<F49P12M>b<F255P255D>ma p<216><F49P12M>a<F255P255D>thiv<200> ç
·ar<F49P12M>a<F255P255D>ma vi<F49P12MJ251>b<F255P255DJ0>·va- <F49P12M>a<F255P255D>mida<221> ç
ja<F49P12M>b<F255P255D>gat<F49P12M>e<F255P255D> ·ar<F49P12M>b<F255P255D>ma <F49P12M>a<F255P255D>candra<F49P12M>a<F255P255D>·ca ç
s<220>r<F49P12M>b<F255P255D>ya<F49P12M>a<F255P255D>·ca ·ar<F49P12M>b<F255P255D>ma brahmapraj<193><F49P12M>a<F255P255D>pat<200><F49P12M>f<F255P255D> ç
<F49P12M>a<F255P255D>bh<220>ta<221> <F49P12M>b<F255P255D>vadi<F49P12M>a<F255P255D><218>ye ç
bhu<F49P12M>b<F255P255D>vana<221> vadi<F49P12M>a<F255P255D><218>ye te<F49P12M>b<F255P255D>jo ç
vadi<F49P12M>a<F255P255D><218>ye ya<F49P12M>b<F255P255D>·o vadi<F49P12M>a<F255P255D><218>ye ç
ta<F49P12M>b<F255P255D>po vadi<F49P12M>a<F255P255D><218>ye bra<F49P12MJ251>b<F255P255DJ0>hma ç
vadi<218>ye <F49P12M>a<F255P255D>satya<221> <F49P12M>b<F255P255D>vadi<F49P12M>a<F255P255D><218>ye ç
ta<F49P12M>b<F255P255D>sm<193> <F49P12M>a<F255P255D>aha<F49P12M>a<F255P255D>mida<F49P12M>b<F255P255D>mu<F49P12M>a<F255P255D>pasta<F49P12M>b<F255P255D>ra<F49P12M>a<F255P255D><207>amu<F49P12M>b<F255P255D>pa- ç
st<216><207>a u<F49P12M>a<F255P255D>pasta<F49P12M>b<F255P255D>ra<207>a<221> me <F49P12M>a<F255P255D>praj<193><F49P12M>b<F255P255D>yai ç
pa<F49P12M>a<F255P255D>·<220>n<193><221> <F49P12M>b<F255P255D>bh<220>y<193>du<F49P12MJ250>a<F255P255DJ0>pasta<F49P12M>b<F255P255D>ra<207>a<F49P12M>a<F255P255D>maha<221> ç
<F49P12M>a<F255P255D>praj<193><F49P12M>b<F255P255D>yai pa<F49P12M>a<F255P255D>·<220>n<193><221> ç
<F49P12MJ251>b<F255P255DJ0>bh<220>y<193><F49P12M>a<F255P255D>sa<221> pr<193><F49P12M>b<F255P255D><207><193>- ç
p<193>nau <F49P12M>a<F255P255D>m<216>tyor<F49P12M>b<F255P255D>m<193>p<193><F49P12M>a<F255P255D>ta<221> ç
pr<193><F49P12M>b<F255P255D><207><193>p<193><F49P12M>a<F255P255D>nau m<193> <F49P12M>b<F255P255D>m<193> ç
h<193>si<F49P12M>a<F255P255D><218><219>a<221> ma<F49P12W1J247>b<F255P255DJ0>dhu ç
mani<F49P12M>a<F255P255D><218>ye ma<F49P12W1J247>b<F255P255DJ0>dhu jani<F49P12M>a<F255P255D><218>ye ç
ma<F49P12W1J247>b<F255P255DJ0>dhu vak<218>y<193><F49P12M>a<F255P255D>mi ma<F49P12W1J247>b<F255P255DJ0>dhu ç
vadi<218>y<193><F49P12M>a<F255P255D>mi ma<F49P12W1J247>b<F255P255DJ0>dhumat<200><221> ç
<F49P12M>a<F255P255D>deve<F49P12M>a<F255P255D>bhyo v<193><F49P12M>b<F255P255D>camudy<193>sag<221> ç
·u<F49P12M>a<F255P255D>·r<220>- <218>e<F49P12M>c<F255P255D><207>y<193><221> ma<F49P12M>a<F255P255D>nu<F49P12M>c<F255P255D><218>yebhyasta<221> ç
<F49P12M>b<F255P255D>m<193> <F49P12M>a<F255P255D>dev<193> <F49P12M>b<F255P255D>avantu <F49P12M>a<F255P255D>·obh<193><F49P12M>b<F255P255D>yai ç
<F49P12M>a<F255P255D>pitaro'<F49P12M>b<F255P255D>numadantu<F49P12M>f<F255P255D> o<221> ç
·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P13M>b<F255P255D>ti<199><F49P12M>f<$!PFE48><F49P12M><$!SD><F49P12M>
@SPACE = 
@SPACE = 
@IN2 = <+><+><+>``Obeisance to the manifested speech. Obeisance to the ç
unmanifested speech. Obeisance to V<193>caspati (the lord of speech). ç
Obeisance to thesages who discovered the Veda- mantras and to those ç
who protected them. Let not these sages who discovered and protected ç
the mantras disown me! Similarly, may I<|>not disown these sages who ç
have discovered and protected the mantras. Iwill utter pleasant words ç
which are auspicious to all the gods. May the paradise bring us happiness. ç
So also this earth and the whole world. May the sun and the moon bring ç
us happiness. May Brahm<193> and the Praj<193>patis also bring us ç
happiness. Iwill speak what is good for the animals and for the worlds. ç
Iwill speak those words which can bring light, honour and austerity. ç
Again, Iwill speak what is in the Vedas and what is the truth. To ç
acquire knowledge I will perform this virtuous act. May my virtuous ç
act become a support for human beings and animals. O pr<193><207>a ç
and ap<193>na v<193>yus! Protect me from death. O deities presiding ç
over pr<193><207>a and ap<193>na, do not abandon me! I meditate on ç
your benign form. I will compose sweet hymns (in praise of You). I ç
will utter sweet words. I will address others in sweet words. I will ç
offer sweet oblations with sweet words to gods presiding over the ç
rites. To men Iwill offer pleasant truths sweet to hear, not untruths. ç
So, may gods protect me who does what has been promised. MayIshine ç
with fame. May the manes agree to this.''
This long ·<193>ntimantra is one of the mantras listed in the Da·a·<193>nti ç
group.
The last part is identical with the last part of the sixth ·<193>ntimantra ç
given here (i<195><193> devah<220><199>....).
Homage is being paid to speech in general, to the supervising deities ç
of speech, and to the sages who discovered and transmitted the Vedic ç
mantras.
Brahm<193>, the creator and the Praj<193>-patis, the subsidiary lords ç
of further creation have been propitiated for our happiness.
The  narrator  is  promising  the concerned persons that he will speak ç
words which are true, beneficial to all beings and which are full ç
of light and knowledge.
It ends with a prayer for protection against death.
@N-1 = 9.
@SANK = <$!SD>DeeW ìeM<205>vo<$!N><F48>b<F255><$!N>meece=<<e<$!N><F48>a<F255><$!N>Yees ç
efJe<$!N><F48>a<F255><$!N><201>eä<$!N><F48>b<F255><$!N>he<203>~ <205>voes<$!N><F48>a<F255><$!N>Yìees<199>- ç
Oìe<$!N><F48>a<F255><$!N>ce=lee<$!N><F48>c<F255>Lmecye<$!N><F48>a<F255><$!N>YetJe<$!N><F48>b<F255><$!N>~ ç
me cesv<202>es<$!N><F48>b <F255><$!N>ces<$!N><F48>a<F255><$!N>Oeìee<$!N><F48>c <F255><$!N>mhe=Ceesleg~ ç
De<$!N><F48>a<F255><$!N>ce=le<$!N><F48>b<F255><$!N>mìe osJe<$!N><F48>a<F255><$!N>Oeej<$!N><F48>b<F255><$!N>Cees ç
Yetìeemeced~ Mejer<$!N><F48>b<F255><$!N>jb ces<$!N><F48>a <F255><$!N>efJeée<$!N><F48>b<F255><$!N><<e&Ceced~ ç
efpe<$!N><F48>a<F255><$!N>õe ces<$!N><F48>a <F255><$!N>ceOeg<$!N><F48>b<F255><$!N>ce<170>ecee~ ç
ke†Cee&<$!N><F48>k<F255><$!N>Yìeeb<$!N><F48>a <F255><$!N>Yetefj<$!N><F48>a<F255><$!N>efJe<190>eg<$!N><F48>b<F255><$!N>Jeced~ ç
yeî<207>e<$!N><F48>b<F255><$!N>Ce<203> ke†es<$!N><F48>a<F255><$!N>Mees<$!N><F48>b<F255><$!N><199>efme ç
<$!N><$!N>ces<F48W1>a<F255D>Oeìee<199>- efhe<$!N><F48>b<F255><$!N>efnle<203>~ <190>eg<$!N><F48>l<F255><$!N>leb ç
ces<$!N><F48>b <F255><$!N>ieesheeìe<158> DeeW Meeefvle<F48W1><$!N><F48W1>a<F255D><203> ç
<$!N>Meeefvle<F48W1>a<F255D><203> <$!N>Meeefvl<F48W1>b<F255D>e<203><158>
@PI-1 = o<221> ya·chan<F49P12M>b<F255P255D>das<193>m<216><F49P12M>a<F255P255D><218>abho ç
<F49P12M>a<F255P255D>vi·va<F49P12M>b<F255P255D>r<220>pa<199><F49P12M>e<F255P255D> chan<F49P12M>a<F255P255D>dobhyo'<F49P12M>a<F255P255D>dhyam<216><F49P12M>c<F255P255D>t<193>thsa<221><F49P12M>a<F255P255D>babh<220><F49P12M>b<F255P255D>va<F49P12M>e<F255P255D> ç
sa men<F49P12J247>b<F255P255J0>dro <F49P12M>a<F255P255D>medha<F49P12M>c<F255P255D>y<193> ç
sp<216><207>otu<F49P12M>e<F255P255D> <F49P12M>a<F255P255D>am<216><F49P12M>b<F255P255D>tasya ç
de<F49P12M>a<F255P255D>vadh<193><F49P12M>b<F255P255D>ra<207>o bh<220>y<193>sam<F49P12M>e<F255P255D> ç
·a<F49P12M>b<F255P255D>r<200>ra<221> <F49P12M>a<F255P255D>me vi<F49P12M>b<F255P255D>car<218>a<207>am<F49P12M>e<F255P255D> ç
<F49P12M>a<F255P255D>jihv<193> <F49P12M>a<F255P255D>me ma<F49P12M>b<F255P255D>dhumattam<193><F49P12M>e<F255P255D> ç
kar<F49P12M>c<F255P255D><207><193><F49P12M>a<F255P255D>bhy<193><221> bh<220><F49P12M>a<F255P255D>ri- ç
vi<F49P12W1J247>b<F255P255DJ0>·ruvam<F49P12M>e<F255P255D> bra<F49P12MJ251>b<F255P255DJ0>hma<207>a<199> ç
<F49P12M>a<F255P255D>ko<F49P12W1J247>b<F255P255DJ0>·o'si <F49P12M>a<F255P255D>medhay<193><F49P12M>b<F255P255D>pihita<199><F49P12M>e<F255P255D> ç
<F49P12M>a<F255P255D>·ruta<221> <F49P12M>b<F255P255D>me gop<193>ya<F49P12M>f<F255P255D> ç
o<221> ·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P13M>b<F255P255D>ti<199><F49P12M>f
@SPACE1 = 
@IN2 = <+><+><+>``May that Indra (or Parame·vara) who is the greatest ç
in the Vedic hymns, who is of all forms, who has sprung into being ç
from immortal hymns,  may  he  cheer  me  with intelligence. O God, ç
May I be the possessor of immortality.
@IN2 = <+><+><+>``May my body be very vigorous. May my tongue be exceedingly ç
sweet. May I hear abundantly with my ears. Thou art the sheath of ç
Brahman, veiled by intelligence. Protect for me, what I have heard.''
@SPACE1 = 
@SPACE1 = 
This is a prayer to be repeated by anyone who is desirous of good ç
health and retentive power of mind. It appears in the Taittir<200>ya ç
Upani<218>ad (1.4). It is chanted as a ·<193>ntimantra also.
Pra<207>ava or O<209>k<193>ra has been praised here as representing ç
Parame·vara or God Himself. It is the best symbol for meditation on ç
God.
Since the body, the senses and the mind arethe means for <193>tmaj<210><193>na ç
or knowledge of the <193>tman, a prayer is addressed to God for strengthening ç
them.
The last part of the prayer is for protecting the spiritual wisdom ç
gained by listening to it from the Vedas.
@N-1 = 10.
@SANK = DeeW Jee*dces<F48>l <F255><$!N>ceve<$!N><F48>b<F255><$!N>efme<$!N><F48>a <F255><$!N><178>eefle<$!N><F48>b<F255><$!N>ef<223>lee<$!N><F48>a ç
<F255><$!N>cevees<$!N><F48>k <F255><$!N>ces<$!N><F48>a <F255><$!N>Jeeefée<$!N><F48>a <F255><$!N><178>eefle<$!N><F48>b<F255><$!N>ef<223>lecee<$!N><F48>a<F255><$!N>efJeje<$!N><F48>a<F255><$!N>Jeerce&<$!N><F48>j ç
<F255><$!N>SefOe; Jes<$!N><F48>a<F255><$!N>omìe ce<$!N><F48>a <F255><$!N>Dee<$!N><$!N>Ceer<F48W1>k<F255D>mLe<203>; ç
<190>eg<$!N><F48>l<F255><$!N>leb ces<$!N><F48>a <F255><$!N>cee <178>ene<$!N><F48>c<F255><$!N>meerj<$!N><F48>a<F255><$!N>vesvee<$!N><F48>a<F255><$!N>Oeerles<$!N><F48>c<F255><$!N>veenes- ç
je<$!N><F48>a<F255><$!N>$eeved mevo<$!N><F48>b<F255><$!N>Oeecìe=<$!N><F48>a<F255><$!N>leb ç
Je<$!N><F48>b<F255><$!N>efo<<ìeeefce me<$!N><F48>a<F255><$!N>lìeb Je<$!N><F48>b<F255><$!N>efo<<ìeeefce<$!N><F48>a<F255>;<F48> ç
<F255><$!N>levceece<$!N><F48>b<F255><$!N>Jeleg<$!N><F48>l <F255><$!N>le<188><$!N><F48>a<F255><$!N>ke<172>leej<$!N><F48>b<F255><$!N>ceJe<$!N><F48>a<F255><$!N>lJeJe<$!N><F48>b<F255><$!N>leg<$!N><F48>l ç
<F255><$!N>ceeceJe<$!N><F48>b<F255><$!N>leg Je<$!N><F48>a<F255><$!N>ke<172>leej<$!N><F48>a<F255><$!N>ceJe<$!N><F48>b<F255><$!N>leg ç
Je<$!N><F48>a<F255><$!N>ke<172>leejced<$!N><F48>c<F255><158> DeeW Meeefvle<F48W1><$!N><F48W1>a<F255D><203> ç
<$!N>Meeefvle<F48W1>a<F255D><203> <$!N>Meeefvl<F48W1>b<F255D>e<203><158>
@PI-1 = o<221> v<193><209><F49P12M>a<F255P255D>me ma<F49P12M>b<F255P255D>na<F49P12M>a<F255P255D>si ç
pra<F49P12W1J251>b<F255P255DJ0>ti<218><219>hi<F49P12M>a<F255P255D>t<193> ma<F49P12M>c<F255P255D>no ç
<F49P12M>a<F255P255D>me v<193><F49P12M>a<F255P255D>ci pra<F49P12M>b<F255P255D>ti<218><219>hita<F49P12M>a<F255P255D>m<193>vi<F49P12M>a<F255P255D>r<193>v<200>r<F49P12M>b<F255P255D>ma ç
edhi; <F49P12M>a<F255P255D>vedasya <F49P12M>a<F255P255D>ma <193><F49P12M>c<F255P255D><207><200>stha<199>; ç
<F49P12M>a<F255P255D>·ruta<221> <F49P12M>a<F255P255D>me m<193> pra<F49P12MJ247>c<F255P255DJ0>h<193>s<200><F49P12M>a<F255P255D>rane<F49P12M>a<F255P255D>n<193>dh<200><F49P12W1J247>c<F255P255DJ0>ten<193>ho<F49P12M>a<F255P255D>r<193>tr<193><%26>n<%0>san<F49P12W1J247>b<F255P255DJ0>da ç
dh<193><F49P12M>a<F255P255D>my<216>ta<221> <F49P12M>b<F255P255D>vadi<218>y<193>mi ç
<F49P12M>a<F255P255D>satya<221> <F49P12M>b<F255P255D>vadi<218>y<193><F49P12M>a<F255P255D>mi<%26>;<%0>tanm<193><F49P12M>b<F255P255D>mava<F49P12M>a<F255P255D>tu ç
ta<F49P12M>a<F255P255D>dvakt<193><F49P12M>b<F255P255D>ra- ma<F49P12M>a<F255P255D>vatva<F49P12M>b<F255P255D>va<F49P12M>a<F255P255D>tu ç
m<193>ma<F49P12M>b<F255P255D>vatu <F49P12M>a<F255P255D>vakt<193><F49P12M>a<F255P255D>ra- ç
ma<F49P12M>b<F255P255D>vatu <F49P12M>a<F255P255D>vakt<193>ra<F49P12M>c<F255P255D>m<F49P12M>f<F255P255D> ç
o<221> ·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P13M>b<F255P255D>ti<199><F49P12M>f<F255P255D><$!SD><$!PFE48><$!SD>
@IN2 = <+><+><+>``May my speech be well-esta-blished in my mind. May ç
my mind be well-established in my speech. Oself-manifested Brahman! ç
Reveal yourself to me. (O speech and mind!) Bring the meaning and ç
substance of the Vedas to me. Let not the Vedas I have heard and learnt ç
abandon me. I will unite the day and the night with my Vedic studies. ç
I will speak <216>ta (the right). I will speak satya (the truth). ç
May Brahman protect me! May It protect my teacher!''
This ·<193>ntimantra is allotted to the <184>gveda. In some texts ç
it forms the last part of the Aitareya Upani<218>ad.
Ideas should be expressed through speech after deep thinking, after ç
being convinced that they are satya or true.
Since Brahman is self-effulgent the prayer addressed to It is for ç
removing the veil of ignorance.
If the Vedas learnt from the guru should be retained in the mind, ç
the presiding deities of speech and mind should be propitious. Hence ç
the prayer to them.
`Uniting day and night' with Vedic studies means that the study of ç
the Vedas should be continuous, without any break.
<184>ta is correct understanding based on the study of the scriptures. ç
Satya is giving expression to it by speech and action.
Protection by Brahman is needed both by the teacher (to teach properly) ç
and by the student (to understand correctly).
@N-1 = 11.
@SANK = <$!SD>DeeW éej<$!N><F48>b<F255><$!N>Ceb he<$!N><F48>a<F255><$!N>efJe$eb<$!N><F48>a ç
<F255><$!N>efJele<$!N><F48>b<F255><$!N>leb hegje<$!N><F48>a<F255><$!N>Ceb ìesve<$!N><F48>b ç
<F255><$!N>het<$!N><F48>l<F255><$!N>lemlej<$!N><F48>b<F255><$!N>efle og<<ke=†<$!N><F48>l<F255><$!N>leeefve<$!N><F48>b<F255><$!N>~ ç
lesve<$!N><F48>b <F255><$!N>he<$!N><F48>a<F255><$!N>efJe$es<$!N><F48>b<F255><$!N>Ce Meg<$!N><F48>l<F255><$!N><183>sve<$!N><F48>b ç
<F255><$!N>het<$!N><F48>l<F255><$!N>lee Deefle<$!N><F48>b <F255><$!N>hee<$!N><F48>a<F255><$!N>hceeve<$!N><F48>a<F255><$!N>ceje<$!N><F48>b<F255><$!N>eEle ç
lejsce<158> DeeWMeeefvle<F48W1><$!N><F48W1>a<F255D><203> <$!N>Meeefvle<F48W1>a<F255D><203> ç
<$!N>Meeefvl<F48W1>b<F255D>e<203><158>
@PI-1 = o<221> ca<F49P12M>b<F255P255D>ra<207>a<221> <F49P12MJ251>a<F255P255DJ0>pavi<F49P12MJ251>a<F255P255DJ0>tra<221> ç
vi<F49P12M>b<F255P255D>tata<221> pu<F49P12M>a<F255P255D>r<193><207>a<221> ye<F49P12M>b<F255P255D>na ç
<F49P12M>a<F255P255D>p<220>tasta<F49P12M>b<F255P255D>rati du<F49P12M>a<F255P255D><218>k<216>t<193><F49P12M>b<F255P255D>ni<F49P12M>e<F255P255D> ç
te<F49P12M>b<F255P255D>na <F49P12M>a<F255P255D>pavi<F49P12M>b<F255P255D>tre<207>a <F49P12M>a<F255P255D>·uddhe<F49P12M>b<F255P255D>na ç
<F49P12M>a<F255P255D>p<220>t<193> a<F49P12M>b<F255P255D>ti <F49P12M>a<F255P255D>p<193>pm<193><F49P12M>a<F255P255D>nama<F49P12M>b<F255P255D>r<193>ti<221> ç
tarema<F49P12M>f<F255P255D> o<221> ·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P12M>a<F255P255D>ti<199> ç
·<193>n<F49P13M>b<F255P255D>ti<199><F49P12M>f
@SPACE = 
@IN2 = <+><+><+>``He who is rendered holy by the ancient, widespread, ç
sanctifying feet (or by virtuous conduct) crosses over evil deeds ç
and their effects. Having been rendered holy by that naturally pure ç
and purifying feet of the Lord (or conduct), may we overcome our enemies, ç
the sins.''
@SPACE = 
This mantra occurs in the Mah<193>n<193>r<193>ya<207>a Upani<218>ad ç
(1.51) and also in the Taittir<200>ya Br<193>hma<207>a (3.12.3).
When a dvija (the twice-born) takes bath in a river or tank, he should ç
stand in knee-deep water, repeat this mantra and then take bath.
It is repeated at the time of washing the feet of br<193>hma<207>as ç
on special occasions.
In  the  M<193>dhva  tradition,  it  is repeated at the time of wearing ç
the mudr<193>s (religions marks) after bath. Here, the word `cara<207>a' ç
is taken to mean the Sudar·ana discus of Lord Vi<218><207>u.
`Cara<207>a' represents the feet of Mah<193>vi<218><207>u as Trivikrama, ç
from which emerged the river Ga<209>g<193>. Hence its remembrance ç
or worship helps us to be purified and to cross over sins.
The word `cara<207>a' can also mean `·<193>str<200>ya-<193>cara<207>a',  virtuous  conduct  as ç
ordained by the scriptures. This too helps us to overcome sins.
@N-1 = 12.
@SANK = <$!SD>Deesced Deehìeeìevleg ceceeíeefve Jeeked†<_><178>eeCeùe#eg<203> ç
<190>ees$eceLees yeueefceefv<202>ìeeefCe ée meJee&efCe~ meJeÖ ç
yeî<207>eewheefve<<eoced~ ceenb yeî<207>e efvejekeg†ìee&ced~ ç
cee cee yeî<207>e efvejeke†jesled~ Deefvejeke†jCecemleg Deefveje- ç
ke†jCeb ces<199>mleg~ leoelceefve efvejles ìe Gheefve<<elmeg Oecee&<203>, ç
les ceefìe mevleg les ceefìe mevleg<158> DeeW Meeefvle<F48W1><$!N><F48W1>a<F255D><203> ç
<$!N>Meeefvle<F48W1>a<F255D><203> <$!N>Meeefvl<F48W1>b<F255D>e<203><158>
@PI-1 = om <193>py<193>yantu mam<193><209>g<193>ni v<193>kpr<193><207>a- ç
·cak<218>u<199> ·rotramatho balamindriy<193><207>i ca sarv<193>ni<F49P12M>e<F255P255D> ç
sarva<221> brahmaupa- ni<218>adam<F49P12M>e<F255P255D> m<193>ha<221> brahma ç
nir<193>- kury<193>m<F49P12M>e<F255P255D> m<193> m<193> brahma nir<193>karot<F49P12M>e<F255P255D> ç
anir<193>kara<207>amastu anir<193>kara<207>a<221> me'stu<F49P12M>e<F255P255D> ç
tad<193>tmani nirate ya upani<218>atsu dharm<193><199>, te mayi santu ç
te mayi santu<F49P12M>f<F255P255D> o<221> ·<193>n<F49P12M>a<F255P255D>ti<199> ·<193>n<F49P12M>a<F255P255D>ti<199> ç
·<193>n<F49P13M>b<F255P255D>ti<199><F49P12M>f
@SPACE = 
@SPACE = 
@IN2 = <+><+><+>``May my limbs grow vigorous, my speech, breath, eye, ç
ear as also my strength and all my senses.
@SPACE = 
@IN2 = <+><+><+>``All is the Brahman of the Upani<218>ads. May I never ç
disregard Brahman.  May  Brahman  never disregard me. May there be ç
no disregarding at all. May there be no disregarding of me.
@SPACE = 
@IN2 = <+><+><+>``Let those truths which are (set forth) in the Upani<218>ads ç
reside in me (who is) dedicated to the <193>tman (the Sel<%18>f<%0>).''
@SPACE = 
This ·<193>ntimantra belongs to the S<193>maveda. It is chanted ç
at the beginning of Kenopani<218>ad and Ch<193>ndogya Upani<218>ad.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
It has three parts. The first part is a prayer for the growth and ç
sustenance of the body in all its aspects. The body being the chief ç
instrument for achieving anything in life, should be kept in excellent ç
condition.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
It may be remembered that the ·<193>ntimantra `bhadra<221> kar<207>ebhi<199>' ç
(vide 3) also stresses the same idea.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
The second part stresses the importance of realising Brahman (the ç
Highest Truth) as taught by the Upani<218>ads. For this, there must ç
be a devotion towards It and favourable response from It. This has, ç
therefore, been stressed.
The last part is an earnest prayer for the firm establishment of the ç
truths taught in the Upani<218>ads, in one's own life.
For this, the s<193>dhaka or the aspirant should be devoted to the ç
°tman, same as Brahman, as the inner controller in the heart.
@N-1 = 13.
@SANK = DeeW De<$!N><F48>a<F255><$!N>melees cee me<$!N><F48>a<F255><$!N>£ceìe~ le<$!N><F48>a<F255><$!N>cemees ç
cee pìees<$!N><F48>a<F255><$!N>efleie&ceìe~ ce=lìees<$!N><F48>a<F255><$!N>cee&<199>ce=<$!N><F48>l<F255><$!N>leb ç
ieceìe<158> DeeW Mee<$!N><F48>a<F255><$!N>efvle<203> Mee<$!N><F48>a<F255><$!N>efvle<203> ç
Mee<$!N><F48>a<F255><$!N>efvle<203><158>
@PI-1 = om <F49P12M>a<F255P255D>asato m<193> <F49P12M>a<F255P255D>sadgamaya<F49P12M>e<F255P255D> ç
<F49P12M>a<F255P255D>tamaso m<193> <F49P12M>a<F255P255D>jyotirgamaya<F49P12M>e<F255P255D> ç
m<216><F49P12M>a<F255P255D>tyorm<193>'<F49P12M>a<F255P255D>m<216>ta<221> gamaya<F49P12M>f<F255P255D> ç
o<221><F49P12M>a<F255P255D>·<193>nti<199> <F49P12M>a<F255P255D>·<193>nti<199> <F49P12M>a<F255P255D>·<193>nti<199><F49P12M>f<F255P255D><$!SD><$!PFE48><$!SD><$!SD>
@SPACE = 
@IN2 = <+><+><+>``Lead me from the unreal to the Real. Lead me from darkness ç
to light. Lead me from death to immortality.''
@SPACE = 
This is a popular and oft-quoted ·<193>ntimantra.
Actually, it forms a part of a bigger mantra in the B<216>had<193>ra<207>yaka ç
Upani<218>ad (1.3.28).
The `unreal' (asat) means j<210><193>na (knowledge) and karma (actions) ç
which arise according to our lower nature. The `real' means the same, ç
but sanctioned by the scriptures and hence pure.
`Darkness' (tamas) means ignorance which covers or hides the truth. ç
`Light' (jyotis) means knowledge which uncovers our real divine nature.
`Death' (m<216>tyu) is what the unreal and darkness will ultimately ç
lead to. `Immortality' is the final goal of life.
@N-1 = 14.
@SANK = <$!SD>DeeW hetCe&<$!N><F48>a<F255><$!N>ceo<F48W1><$!N><F48W1>a<F255D><203> ç
<$!N>hetCe&<$!N><F48>a<F255><$!N>efceob<$!N><F48>a <F255><$!N>hetCee&<$!N><F48>a<F255><$!N>led ç
hetCe&<$!N><F48>a<F255><$!N>cego<$!N><F48>a<F255><$!N>éìeles<$!N><F48>e <F255><$!N>hetCe&<$!N><F48>a<F255><$!N>mìe ç
hetCe&<$!N><F48>a<F255><$!N>ceeoe<$!N><F48>a<F255><$!N>ìe hetCe&<$!N><F48>a<F255><$!N>cesJeeJeefMe<$!N><F48>a<F255><$!N><<ìeles<158> ç
DeeW Mee<$!N><F48>a<F255><$!N>efvle<203> Mee<$!N><F48>a<F255><$!N>efvle<203> Mee<F48W1><$!N><F48W1>a<$!N><F48W1><F255D>efvle<203><158><$!SD>
@PI-1 = o<221> p<220>r<F49P12M>a<F255P255D><207>ama<F49P12M>a<F255P255D>da<199> ç
p<220>r<F49P12M>a<F255P255D><207>ami<F49P12M>a<F255P255D>da<221> p<220>r<F49P12M>a<F255P255D><207><193>t ç
p<220>r<F49P12M>a<F255P255D><207>amu<F49P12M>a<F255P255D>dacyate<F49P12M>e<F255P255D> p<220>r<F49P12M>a<F255P255D><207>asya ç
p<220>r<F49P12M>a<F255P255D><207>am<193><F49P12M>a<F255P255D>d<193>ya p<220>r<F49P12M>a<F255P255D><207>amev<193>va<F49P12M>a<F255P255D>·i<218>yate<F49P12M>f<F255P255D> ç
o<221> <F49P12M>a<F255P255D>·<193>nti<199> <F49P12M>a<F255P255D>·<193>nti<199> <F49P12M>a<F255P255D>·<193>nti<199><F49P12M>f
@SPACE1 = 
@IN2 = ``That (Brahman) is full. This (universe) is full. (From Brahman ç
which is) full, (this universe which is) full, has emanated. Taking ç
the full from the full, full itself remains.''
@SPACE1 = 
This ·<193>ntimantra belongs to the <185>ukla Yajurveda.
It is quite enigmatic.
According to the Advaita Ved<193>nta, this universe is only a false ç
appearance in Brahman due to ignorance, even as a snake is seen in ç
a rope in semi-darkness.
When the rope is seen as rope in full light, it is `full'.
When the snake is seen in semidarkness, it is also `full'.
After the illusion of the snake is dispelled by bright light, the ç
rope again appears as `full'.
Since Brahman is both transcendent and immanent, the birth or the ç
creation of the universe does not in any manner affect the integrity ç
of Brahman.
This mantra is often used at the end of rites and rituals signifying ç
the completion of the same.
@SB = Epilogue
As already indicated in the beginning, each ·<193>ntimantra ends with ç
the words `(O<221>) ·<193>nti<199>', being repeated three times.
@IN2 = The number three may represent:
@IN2 = The three states of consciousness†<R>ç
<+><+><+><+>waking, dream and deep sleep;
@IN2 = the three periods of time†<R>ç
<+><+><+><+>past, present and future;
@IN2 = the three worlds†<R>ç
<+><+><+><+>earth, sky and heaven;
@IN2 = the three gu<207>as†<R>ç
<+><+><+><+>sattva, rajas and tamas;
@IN2 = the three Vedas†<R>ç
<+><+><+><+><184>g, Yajus and S<193>ma.
Hence repeating the word `·<193>nti<199>' three times is said to invoke ç
peace in all these triads.
@NT = <185><193>rad<193> script
Like the Br<193>hm<200> and the Kharo<218><219>h<200> scripts, the ç
<185><193>rad<193> script also is an ancient script that existed in ç
the Indian subconti-nent. It evolved from the Br<193>hm<200> script, ç
probably around the eighth century <MS>A.<|>D.<D>, in the north western ç
part like Dardistan, Kashmir, Jammu, Ladakh and Himachal Pradesh.
Alberuni (<MS>A.<|>D.<D> 970-1039), the Muslim traveller and historian, ç
has referred to this script as `Siddham<193>t<216>k<193>'.
It was the most popular script for several centuries extensively pervading ç
the areas of north-western India. The entire repertoire  of  extant  manuscripts  of ç
Sanskrit  and  old  Kashmiri  texts  of historical significance are ç
in this script. So also the several epigraphic records discovered ç
so far in this region.
The first printed edition of the famous work R<193>jatara<209>gi<207><200> ç
of Kalha<207>a (12th century <MS>A.<|>D.<D>) edited by Mark Aurel Stein ç
(<MS>A.<|>D.<D> 1862-1943) was based on a <185><193>rad<193> manuscript. ç
He also catalogued a large number of Sanskrit works in <185><193>rad<193> ç
script from the Raghunath Temple Library (inJammu).
This script was in vogue till the 13th Century <MS>A.<|>D.<D> It was ç
gradually replaced by its own evolution, the Deva·e<218>a, which again ç
gave rise to the modern Gurumukhi script.
The script still survives in the older generation of Pandits of Kashmir.
@NT = <185><193>rad<193> Temple
@N1 = (of Kashmir)
The <185><193>rad<193> Temple of Kashmir†now in Pakistan<192>occupied ç
Kashmir and in ruins†is an ancient temple highly revered for several ç
centuries. <185>a<209>kar<193>c<193>rya (<MS>A.<|>D.<D> 780-820) is ç
said to have visited it and occupied  the  Sarvaj<210>ap<200><219>ha  (the  seat ç
reserved for the best of scholars in ancient learning). Kalha<207>a ç
(12th century <MS>A.<|>D.<D>) in his  R<193>jatara<209>gi<207>i  (<MS>A.<|>D.<D> ç
1148)  clearly mentions the existence of the <185><193>rad<193>dev<200> ç
temple as also its geographic location. Alberuni (<MS>A.<|>D.<D> 973-1039) ç
states in his famous work Tarikh-ul-Hind that the <185><193>rad<193> ç
Temple had a wooden image of the goddess.
According to an ancient mythological work, the <185><193>rad<193>m<193>h<193>tmya, ç
the sage <185><193><207><195>ilya issaid to have established it in ç
the place where he had had a vision of the deity.
The dilapidated temple lies at the confluence of the rivers Madhumati ç
and Kishenganga, on the right bank of the former. This place is about ç
112 kms. (70 miles) from Srinagar, the summer capital of the Jammu-Kashmir ç
State. It is situated at a height of 3350 metres (11,000 ft.), above ç
the sea level. The quadrangle measures 43 metres (142 ft.) by 29 metres ç
(95 ft.). This is surrounded by an outer wall 3.3 metres (11 ft.) ç
in height and 1.8 metres (6 ft.) thick. The approach is by a staircase, ç
2.7 metres (9 ft.) wide and 63 steps in number.
The temple occupies the centre of the court. It is 6.7 metre (33 ft.) ç
square and is perfectly plane. It was once (in <MS>A.<|>D.<D> 1873) ç
covered by a low shingle roof.
The sanctum is actually the spot where the Divine Mother <185><193>rad<193> ç
revealed herself to the sage <185><193><207><195>ilya. It is a stone ç
slab measuring 2.1 metres (7 ft.) by 1.8 metre (6 ft.) and 15 cms. ç
(6") thick covering a ku<207><195>a or small spring cavity, from where ç
the goddess had risen and finally vanished into.
On the <185>ukla-a<218><219>am<200> day (eighth day of the bright ç
fortnight) of every lunar month, the image that existed in the sanctum ç
till the 15th century <MS>A.<|>D.<D> used to exhibit some miracles.
During its heydays, a big annual festival with special p<220>j<193> ç
and homa usedtobe held at the temple during theGa<209>g<193><218><219>am<200> ç
day (Bh<193>drapada-·ukla- a<218><219>am<200>?).
The temple being a centre of learning probably had a big library attached ç
to it.
@NT = Sarasvat<200>p<220>j<193>
@N1 = (`worship of the goddess Sarasvat<200>')
Sarasvat<200>, the goddess of learning, is an extremely popular deity ç
with the students. (See <MS>SARASVAT®<D> for details.)
Her p<220>j<193> or festival of worship is celebrated in three different ç
traditions:
In Karnataka and Andhra Pradesh it is celebrated on thesaptam<200> ç
day during the Navar<193>tri festival (See <MS>NAVAR°TRA<D>.) (°·vayuja ç
·uddha saptam<200>, the seventh day of the bright fortnight in the ç
monthof°·vayuja or °·vina, generally in October).
Worship is offered to a picture or to an image (if available), fully ç
decorated. Books, writing materials and musical instruments are kept ç
at her feet. They will not be used for the day.
In Kerala, the worship is offered for three days (a<218><219>am<200>, ç
navam<200> and Vijaya-da·am<200>) of the Navar<193>tra festival.
Ak<218>ar<193>bhy<193>sa (initiation for writing) for little children ç
is performed on the Vijayada·am<200> day (See <MS>VIDY°RAMBHA<D>.).
In Tamil Nadu, it is done on the Mah<193>navam<200> or the ninth day ç
during theNavar<193>tra festival, coinciding with °yudhap<220>j<193>.
In Bengal, as also in Bihar, Orissa and Assam, the p<220>j<193> is ç
performed on the Vasantapa<210>cam<200> (also known as <185>r<200>pa<210>cam<200>) ç
day (M<193>gha-·ukla-pa<210>cam<200>, the fifth day of the bright ç
fortnight of the lunar month of M<193>gha, generally in February) ç
in clay image. Books are placed at the feet of the image and an elaborate ç
worship is performed. Later, the clay image is ceremonially immersed ç
in a lake or a river.
This day in considered as extremely auspicious for Ak<218>ar<193>bhy<193>sa ç
for children.
See also <MS>VIDY°RAMBHA<D>.
@NT = Svar<207>agaur<200>vrata
The Svar<207>agaur<200>vrata is observed on the Bh<193>drapada ·ukla ç
t<216>t<200>y<193> day. It is mostly confined to the women of the ç
Karnataka region. It is believed that Gaur<200> or P<193>rvat<200> ç
comes to her parent's house on this day and that Ga<207>e·a comes ç
there the next day to escort her back!
Gaur<200> is worshipped in a clay image or a kala·a installed in a ç
ma<207><195>apa (asmall pavilion). The married women who observe ç
it, fast for the day and offer worship with 16 upac<193>ras. They ç
pray for health, sons, wealth and longevity of their husbands. At ç
the end they have to do udy<193>pana by donating 16 baskets each filled ç
with sixteen edibles and covered with a cloth, to br<193>hma<207>a ç
ladies and their husbands.
@END = <R>ç

