@H = K
@NT = K<193>kabhu<218>u<207><195>i
K<193>kabhu<218>u<207><195>i is an old wise sage in the form of a ç
crow.
The incident of his teaching the story of <185>r<200> R<193>ma in ç
brief, to Garu<195>a, the eagle-mount of Vi<218><207>u, is recorded ç
in the R<193>macaritam<193>nasa (Uttarak<193><207><195>a, dohas ç
64 to 68) of Tulas<200>d<193>sa (<MS>A.<|>D.<D> 1496-1622).
When R<193>ma and Lak<218>ma<207>a were bound by the N<193>gap<193>·a ç
(weapon of snakes that binds) of Indrajit and became unconscious, ç
Garu<195>a arrived and saved them (vide the R<193>m<193>ya<207>a ç
of V<193>lm<200>ki, Yuddha-k<193><207><195>a, Chs. 45 to 50).
Seeing R<193>ma in that pathetic condition, Garu<195>a started doubting ç
his divinity. To clear this, he went to the sage N<193>rada who directed ç
him to Brahm<193>, the creator, Brahm<193> in turn sent him to <185>iva ç
who again advised him to go to the sage K<193>kabhu<218>u<207><195>i.
K<193>kabhu<218>u<207><195>i received him with warmth and affection, ç
and made him to listen to the story of R<193>ma which he was about ç
to narrate to the birds that had gathered there. By devotedly listening ç
to the story, Garu<195>a's doubts were cleared and his faith in R<193>ma ç
was restored.
Later K<193>kabhu<218>u<207><195>i also describes his adventures as ç
a baby crow with the child R<193>ma.
@NT = K<193>l<200>gh<193><219> Temple
The city of Calcutta (now Kolkata) was originally a small place called ç
K<193>l<200>k<193>ta (land belonging to K<193>l<200>), containing ç
an ancient shrine of Mother K<193>l<200>.
This temple, now known as the K<193>l<200>gh<193><219> temple, is ç
a landmark in thecity, visited by thousands of people everyday.
There are several stories as to how this original shrine situated ç
in a jungle, was discovered.
A br<193>hma<207>a bathing in the river Bh<193>g<200>rath<200> (Ga<209>g<193>) ç
saw a ray of light emerging out of water in a particular spot. Diving ç
there, he discovered a piece of stone carved like a human toe. Later ç
in the night he dreamed that, that was the toe of the goddess Sat<200> ç
D<193>k<218><193>ya<207><200> (P<193>rvat<200>).
According to the tradition regarding the creation of <185>aktip<200><219>has ç
(places sacred to <185>akti or the Divine Mother P<193>rvat<200>) ç
this place is considered the second one where the toe of Sat<200> ç
D<193>k<218><193>ya<207><200> fell. (See under <MS>TANTRAS<D> for ç
details.)
The br<193>hma<207>a also discovered a <185>ivali<209>ga in the nearby ç
area. He established the stone image of the toe there and started ç
worshipping them.
@NID = <+><+><|>(This <185>ivali<209>ga is called Nakule·vara.)
It is round these icons that gradually a big temple developed due ç
to the efforts of devotees.
A few other stories connected with this temple may be summarised as ç
follows:
1. Santosh Roy Choudhury of the famous Sabar<207>a Roy Choudhury family ç
discovered this image in a jungle following the sound of a conch which ç
he accidentally heard one day while passing by. It was he who first ç
started to build a temple for it and to worship it. It was his son ç
Ram Lal and nephew Rajiv who completed the construction of the temple ç
in <MS>A.<|>D.<D> 1809.
2. Keshav Roy Choudhury, another scion of the Sabar<207>a family, ç
discovered the image through a dream revelation. He brought it out ç
and built a small temple for it. The present temple was built later ç
by Rajiv Lochan Roy.
3.<+>Some  K<193>p<193>likas  (See  under <MS><185>AIVISM<D>.) discovered ç
the image in a forest and fixed it there itself.
4.<+>Caura<209>gi Giri, a sa<221>ny<193>sin of the Da·an<193>m<200> ç
Order, discovered the image and had it consecrated in a temple.
There is a reference to one Bhuvane·vara Brahmac<193>ri who was the ç
priest of this temple in <MS>A.<|>D.<D> 1550, thereby confirming the ç
existence of the temple even by that time. He had allowed the fixing ç
of <185><193>lagr<193>mas in the temple which can be seen even now.
The K<193>l<200>gh<193><219> temple is situated on the bank of the ç
river Bh<193>g<200>rath<200> (or Ga<209>g<193>).
The image of Mother K<193>l<200> is made of Ko<218><219>i stone which ç
is black in colour. The hands of Mother K<193>l<200> are adorned with ç
golden bangles and bracelets. Her nose-ring also is of gold. She holds ç
a silver sword in one hand and a severed head in the other. She wears ç
a garland of human heads made of gold and silver. Her teeth and tongue ç
too are covered with gold.
She wears a golden crown above which there is a golden umbrella. The ç
whole body is covered with cloths and numerous flower garlands adorn ç
her neck. Lord <185>iva is lying prostrate at her feet. His image ç
is also covered with silver.
The Nakule·var <185>iva temple (built in <MS>A.<|>D.<D> 1805) is in ç
front of the K<193>l<200> temple.
The n<193><219>mandir (assembly hall or pavilion) has an image of ç
Lord K<216><218><207>a as V<193>sudeva. It is offered vegetarian food.
Sacrifice of goats to Mother K<193>l<200> is very common.
Many poor people are fed everyday.
See also <MS>K°L®<D>.
@NT = K<193>rttikai-d<200>pam
@N1 = (`beacon light [lit on K<193>rttika p<220>r<207>im<193>])
The  K<193>rttikai-d<200>pam  festival  is observed on the p<220>r<207>im<193> ç
(full-moon) day of  the  month  of  K<193>rttika  (October<|>/ November) ç
mostly in Tamil Nadu. Lord <185>iva is said to have manifested himself ç
in the form of the Aru<207>agiri or Aru<207><193>cala hill (at Tiruva<207><207><193>malai, ç
hallowed by the recent memories of Rama<207>a Mahar<218>i [<MS>A.D.<D>1879-1950]) ç
on this day. A huge beacon is lit on the hill on this day which is ç
witnessed and worshipped by thousands of devotees. It burns for several ç
days.
@SPACE = 
@NT = Kriy<193>s<193>ra
@SPACE = 
This is a work of the tantra group dealing with the construction of ç
temples as also the rituals, including the consecration of the idols. ç
Ravi, the son of Subrahma<207>ya (belonging to Kerala) is the author ç
of this work. It was probably composed during the 10th century <MS>A.<|>D.<D>
The work is spread over 69 pa<219>alas or sections and is in the ·loka ç
metre, the total number of verses being 3498.
The author seems to have been guided by the V<193>tul<193>gama while ç
composing his work.
The work deals with the following deities: Vi<218><207>u; <185>iva; ç
Har<200>·a or <185>a<209>kara-n<193>r<193>ya<207>a; Durg<193>; Skanda; ç
Ga<207>apati and <185><193>st<193>.
The various steps involved in the construction of a temple and consecration ç
of the image are common to all these deities.
The more important ones are as follows: guruvara<207>a (choosing the ç
chief priest);  bh<220>par<200>k<218><193>  (testing  the  soil); ç
laying of the prathama-i<218><219>ik<193>s (first bricks); r<193>k<218>oghnahoma ç
(homa for driving away the evil spirits); V<193>stuy<193>ga (sacrifice ç
to please the V<193>stu-puru<218>a or the deity of the site); <218>a<195><193>dh<193>ra ç
prati<218><219>h<193> (See <MS><186>A£°DH°RAPRATI<186><187>H°<D>); ç
rites of purification of the idol; a<218><219>abandha and prati<218><219>h<193> ç
(fixing the image with the special pasteand consecration of the image); ç
pr<193>ya·cittahoma (expiatory rites to offset the effects of procedural ç
mistakes); p<220>j<193>s and utsavas (worship of the deity and celebration ç
of special days); d<193>nas (giving gifts to participants and poor ç
people); honouring the chief priest.
@SPACE1 = 
Towards the end, details about the construction of go·<193>l<193> ç
(cow-shed) with an image of K<216><218><207>a as Govinda (protector ç
of cows) and the temple or temples for theM<193>t<216>k<193>s (Saptam<193>t<216>k<193>s ç
or the seven goddesses) are also given.
@NT = Kul<193>r<207>ava Tantra
The Kul<193>r<207>ava Tantra is an important work of the Kaula school. ç
(See <MS>TANTRAS<D>.) As per the colophon given at the end of each ç
chapter (called as `ull<193>sa' here) it is a part of a much bigger ç
work, the <188>rdhv<193>mny<193>ya Tantra, comprising 1,25,000 verses. ç
However, this work has not so for been discovered. For all practical ç
purposes this can be considered as an independent work having 2060 ç
verses spread over 17 ull<193>sas or chapters.
The speciality of this work is that it offers a symbolic and spiritual ç
interpretation of some V<193>m<193>c<193>ra practices like the five ç
`ma-k<193>ras'. (See under <MS>TANTRAS<D>.)
A brief summary or synopsis of the contents may now be attempted here:
@S10N = First<|>Ull<193>sa<|>(J<200>vasthitikathanam†121 Verses)
In this section there is a detailed analysis of the state of the j<200>v<193>tman ç
or the individual soul.
Human birth is the greatest. One who does not seek liberation even ç
after getting this birth is an <193>tmagh<193>taka (self-killer).
Body being the instrument of s<193>dhana, should be protected by all ç
means.
It is tattvaj<210><193>na (knowledge of the Reality) that gives liberation. ç
Hence one should try to get it by taking refuge in a guru or spiritual ç
teacher.
@S10N = Second Ull<193>sa<R>ç
(Kulam<193>h<193>tmyakathanam†142 verses)
`Kula' means the Dev<200> or the Divine Mother. Hence Kuladharma is ç
the art andscience of up<193>san<193> (meditation and worship) on ç
the Dev<200>. This section deals mainly with Kuladharma.
The six dar·anas (systems of philo-sophy) are actually parts of this ç
Kula-dharma.
How the pa<210>camak<193>ras have been misused by the ignorant and ç
evil persons is described here.
@S10N = Third Ull<193>sa (<185>r<200>pr<193>s<193>da-par<193>mantra-<R>ç
                 kathanam†117 verses)
This chapter deals with the parapras<193>damantra, viz., `ha<221>sa<199>' ç
which is the great cosmic breath.
The method of pura·cara<207>a (repetition of a mantra in a ceremonial ç
way) of the ha<221>samantra is also described.
@S10N = Fourth Ull<193>sa (Mah<193><218>o<195>h<193>ny<193>sakathanam†<R>ç
               130 verses)
<186>o<195>h<193>ny<193>sa or <186>o<195><193>ny<193>sa means six ç
ways of touching the various parts of the body in ritualistic practices. ç
It is described here in great detail.
The following six ny<193>sas are of greatimportance: Prapa<210>cany<193>sa ç
(ny<193>sa involving various parts of this world like islands, oceans ç
and mountains as related to 16 aspects of the goddess Lak<218>m<200>); ç
Bhuvanany<193>sa (ny<193>sa involving the 14lokas or worlds like ç
atala, vitala and associated with the goddesses at the centres or ç
cakras like m<220>l<193>dh<193>ra, sv<193>dhi<218><219>h<193>na and ç
so on); M<220>rtiny<193>sa (ny<193>sa involving 16 aspects of Vi<218><207>u ç
like Ke·ava and N<193>r<193>ya<207>a, and associated with 16 ·aktis ç
or goddesses of letters like a, <193>, i, <200>, and so on, called ç
Ak<218>ara·akti, °dy<193>, I<218><219>ak<193> etc.); Mantrany<193>sa ç
(ny<193>sa involving all the letters of the alphabet from a to k<218>a, ç
and associated with the sixteen goddesses like Eka-k<220><219>a-<200>·var<200>, ç
each of them being considered as the presiding deity of the mantras); ç
Daivat<193>ny<193>sa (ny<193>sa involving goddesses like Niv<216>tti-amb<193>, ç
prati<218><219>h<193>-amb<193> and so on, the parts of the body touched ç
being the right toe, going round all the parts on the right side, ç
changing over to the left and ending with the left toe); M<193>t<216>k<193>ny<193>sa ç
(ny<193>sa involving the m<193>t<216>k<193>s or letters of the alphabet ç
[with anusv<193>ra] arranged in a particular order and associated ç
with a <185>akti and her Bhairava).
@SPACE = 
@S10N = Fifth Ull<193>sa<R>ç
(Kulam<193>h<193>tmyakathanam†114 verses)
While extolling the greatness of the Kaulam<193>rga, it also gives ç
many details such as the vessels needed in the rituals, various types ç
of wine, meat, fish and other items.
An important point to be noticed is the esoteric interpretation of ç
the five ``ma''-k<193>ras and the severe condemnation of observing ç
them in the gross physical sense.
@SPACE = 
@S10N = Sixth Ull<193>sa (Dravyasa<221>sk<193>ravidh<193>nam†102 ç
verses)
It describes the characteristics of the worshipper, of the suitable ç
place, pa<210>ca·uddhi or five types of purification, drawing of the ç
ma<207><195>ala (sacred diagram), vessels needed for worship, various ç
kal<193>s,inviting the Dev<200> (goddess) and worshipping her, mantra ç
and yantra of the goddess and meditation on the gurus (teachers) of ç
the tradition.
@SPACE = 
@S10N = Seventh Ull<193>sa (Ba<219>uka·akty<193>dip<220>j<193>vidh<193>nam†104 ç
verses)
Offering a bali to the deity Ba<219>uka† described as Dev<200>putra ç
or son of the Dev<200>, the Divine Mother†is stated first, with a ç
long mantra.
Then is described the <193>rati (waving of light) with a specially ç
prepared lamp called `Kulad<200>pa'.
The names of eight Kula·aktis and of eight Akula·aktis are also given.
A long mantra of 73 letters to be used at the end of the p<220>j<193> ç
of the Dev<200> is also described.
Some rules connected with the ceremonial drinking of madya or wine ç
are stated towards the end.
@S10N = Eighth Ull<193>sa (Tattvatritayap<193>n<193>dibheda-<R>ç
                   kathanam†111 verses)
This section deals with the cakra or various forms of seating as also ç
several kinds of ull<193>sas or bliss.
@S10N = Ninth Ull<193>sa (Yogasa<221>sth<193>pana-<R>ç
                   kathanam†134 verses)
This  chapter  deals  with  various aspects of yoga like the characteristics ç
of a yogi, nature of sam<193>dhi and j<200>vanmukti (liberation while ç
still living) as also brahmaj<210><193>na (knowledge of Brahman).
The text declares that there is no difference between the j<200>va ç
and Param<193>tman.
It also describes the four states of a s<193>dhaka (novice), the need ç
to observe the var<207><193>·rama dharmas, karmayoga and other related ç
subjects.
@S10N = Tenth Ull<193>sa (Vi·e<218>adivas<193>rcanavidh<193>na†<R>ç
                             114 verses)
As the little indicates, this ull<193>sa is dedicated to arcana or ç
p<220>j<193> (worship) of various kinds.
The worship is to be offered on special days like the birthdays of ç
the guru, of great men, auspicious days like the eighth, fourteenth ç
and the fifteenth days of the dark fortnight and so on.
Daily  worship  of  the  deity  is considered the best.
All worship has to be planned and performed according to one's resources, ç
faith and suitability of time.
There are also simple descriptions of the worship of nine kum<193>r<200>s ç
(girls before puberty), nine yuvat<200>s (young women) and nine couples ç
(viz., Gaur<200>-<185>iva, Ram<193>- Vi<218><207>u, V<193><207><200>-Brahm<193>, ç
<185>ac<200>-Indra and so on).
Mention is also made of the worship of the yogin<200>s (See <MS>YOGIN®S<D>.) ç
for getting relief from diseases, difficulties in life and offsetting ç
the evil effects from bad persons.
@SPACE = <R>ç

@NT = Kumbh<193>bhi<218>eka
@N1 = (`pouring [water] from a [consecrated] pot')
@SPACE = 
Kumbh<193>bhi<218>eka is the ceremonial act of pouring the water from ç
a duly consecrated pot, on to the pinial (kala·a) of a Hindu temple.
Generally, several pots with waterand certain prescribed materials, ç
are established inside the sanctum. After a simple worship, the presence ç
of the chief deity of the temple is invoked into these pots. Either ç
all the pots or one bigger pot containing a little of the water of ç
every pot, is carried to the top of the temple tower and emptied over ç
the pinial. This is done from a specially built platform of wooden ç
poles so that one need not step upon the tower.
By this act, the presence of the main deity is transferred to the ç
pinial also.
Any one going at a distant place, unable to visit the temple, can ç
get the merit of seeing the main deity just by bowing down to the ç
consecrated pinial.
@NT = K<220><218>m<193><207><195>ahoma
@N1 = (`oblations [into the fire to offset the evils of] sins')
Man is prone to committing sins (See<MS>P°TAKA<D> for details.) knowingly ç
or unknowingly. When he realises it and repents for it he may think ç
of somewaysand means of offsetting their consequences. Such means ç
are called pr<193>ya·cittas. The K<220><218>m<193><207><195>ahoma ç
is one such, of Vedic origin.
Oblations of <193>jya (ghee) are offered into a duly consecrated fire ç
with the 53 mantras (forming the pra·nas [sections] 3, 4, 5, and 6 ç
of the Taittir<200>ya °ra<207>yaka) known as K<220><218>m<193><207><195>a-mantras. ç
Agni, the fire-god, is the deity to whom prayers are addressed and ç
offerings are made.
Out of the several sins expressly mentioned here, a few may be cited: ç
killing an embryo; prohibited sexual relationships; telling lies; ç
humiliating others out of arrogance; cheating; violence against one's  own  parents;  damaging  nature; ç
secretly committed sins and so on.
The person who wants to perform this homa can do it himself directly ç
or through a competent priest. Shaving thehead, fasting, not consuming ç
meat, observing celibacy, sleeping on the ground†these are the disciplines ç
to be observed before performing it. This is called  `d<200>k<218><193>'.  This  d<200>k<218><193>  may  be ç
observed from one year up to three days prior to the performance of ç
the homa.
The K<220><218>m<193><207><195>ahoma has to be performed at the beginning ç
of every rite that involves a homa such as pu<221>savana, c<220><195><193>kara<207>a, ç
upanayana and viv<193>ha. (See under each title for details.) It has ç
to be done before the performance of other homas also, like Ga<207>apathi-homa ç
and Rudrahoma.
@END = <R>ç
<R>ç

