@H = T
@NT = Tantrasamuccaya
@SPACE1 = 
@SPACE1 = 
It is a well-known work dealing mainly with temples and temple-rituals. ç
Actually, it is a compendium which has brought together in one place, ç
all the essential aspects of the subject from various authoritative ç
sources.
@SPACE1 = 
The author is N<193>r<193>ya<207>an Namp<220>tiri (or Namb<220>diri) ç
belonging to an illustrious house of Namp<220>tiri br<193>hma<207>as ç
called Cenn<193>s. He lived in the 15th Century <MS>A.D.<D>, the year ç
of birth being <MS>A.<|>D.<D> 1427.
@SPACE1 = 
The work is in 12 pa<219>alas or chapters and has 1801 stanzas in ç
different metres. <185>a<209>kara, the son of the author, has written ç
a commentary called Vimar·in<200>.
@SPACE1 = 
Two  more  works,  the  Dev<193>laya- candrik<193> and M<193>nava-v<193>stu-lak<218>a<207>a, ç
are also attributed to him.
@SPACE1 = 
A brief account of the contents of the work may now be given here:
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@S10N = First Pa<219>ala (137 verses)
Selection of a guru; selection of a suitable site for the construction ç
of the temple; V<193>stubali rite; depositing the nidhikumbha  (See  <MS>NIDHIKUMBHA<D>  for ç
details.); laying of the bricks; placing of the foundation stone; ç
selection of suitable granite for the construction.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@S10N = Second Pa<219>ala (150 verses)
Characteristics  of  the  Pr<193>s<193>da  or the temple proper; its ç
measurements; detailsofconstruction; about the idol and its pedestal; ç
types of idols and their measurements; balip<200><219>has; pa<210>capr<193>k<193>ras ç
or the five surrounding walls.
@SPACE = 
@S10N = Third Pa<219>ala (83 verses)
Purification of the site; sowing of the seeds to test the suitability ç
of the site; preparation of the idol; ceremonies for purifying the ç
temple premises; ceremonial placing of the idol in water and related ç
rituals.
@SPACE = 
@S10N = Fourth Pa<219>ala (116 verses)
Purification  of  the  ma<207><195>apas  or temple halls; offering ç
oblations to minor deities; purification of the spot where the kala·as ç
(ceremonial pots of water) are kept; kindling of the sacred fire; ç
worship of the bed to place the idol horizontally before installing ç
it; bathing the idol with the waters of the kala·as.
@SPACE = 
@S10N = Fifth Pa<219>ala (148 verses)
Purification of the preceptor and spiritually converting his body ç
into a bodyof fire; ceremonially placing the ak<218>aras or var<207>as ç
(letters of the alphabet) on the various parts of the body of the ç
preceptor; oblations into the sacrificial firein connection with ç
the ceremony of installation.
@SPACE = 
@S10N = Sixth Pa<219>ala (141 verses)
Consecration of the idol; depositing of the precious stones in the ç
hole below the seat of the idol; fixing the idol to the seat with ç
the specially prepared gum-paste called a<218><219>abandha; installation ç
of the Saptam<193>t<216>k<193>s (`seven mothers'); installation of ç
the balip<200><219>ha and dhvajastambha (flag staff); purification ç
of the deity.
@S10N = Seventh Pa<219>ala (142 verses)
Details of the daily services; meditation of various kinds; worship ç
of the deity with sixteen items (called <218>o<195>a·opac<193>ra-p<220>j<193>).
@S10N = Eighth Pa<219>ala (197 verses)
Preparation  of  kala·as  with  25 articles and water as also their ç
purification; kala·as for different deities like <185>iva, Durg<193>, ç
Ga<207>apati, Subrahma<207>ya, <185><193>st<193> and <185>a<209>karan<193>r<193>ya<207>a.
@S10N = Ninth Pa<219>ala (240 verses)
Conduct of festivals; erection of the flagstaff; oblations to the ç
bh<220>tas (spirits) and the deity; propitiation of the Sapta-m<193>t<216>k<193>s;  putting  the  deity  to  sleep; ç
procession of the utsavam<220>rti.
@S10N = Tenth Pa<219>ala (106 verses)
Expiations of various kinds to offset the effects of improper performance ç
of daily rituals; purification of the idol called `catu··uddhi'.
@S10N = Eleventh Pa<219>ala (124 verses)
Rituals connected with the renovation or reconstruction of the temple ç
structure; of the idol, the pedestal etc., refixing the idol with ç
the a<218><219>abandha paste.
@S10N = Twelfth Pa<219>ala (217 verses)
Miscellaneous topics; additional rituals; hand-poses for rites; specifications ç
formaking sacrificial utensils; yantras or diagrams for worship; ç
some mantras of deities and their use.
Though the work contains many details of temple rituals and associated ç
subjects, only a very brief account has been presented here.
@NT = Tirucend<220>r
Tirucend<220>r is one of the six pilgrim centres with a beautiful ç
temple of Lord Muruga or Subrahma<207>ya. It is situated at a distance ç
of 55 kms. (34 miles) from Tirunelveli, the district headquarters ç
in Tamil Nadu.
Though all the temples of Subrahma<207>ya are generally built on the ç
top of hillocks, this one is an exception built on seashore.
As per the local legends, Subrah-ma<207>ya the commander-in-chief ç
of the gods, made this place his base camp to fight the dreaded demon ç
Surapadman. After a fight which lasted for six days, he killed the ç
demon on the sixth day. The victory was celebrated on the seventh ç
day.
While camping here, since Subrah-ma<207>ya was eager to worship his ç
father <185>iva, Maya the celestial architect, built this temple for ç
him. This is the origin of this temple.
Considered as a very ancient temple it must have undergone several ç
additions and alterations, over the last thousand years.
The temple is situated so close to the sea that waves from the Gulf ç
of Mannar constantly strike the eastern wall of the temple.
The front adjunct to the temple known  as  <186>a<207>mugavil<193>sam  has  124 ç
columns spread over an area of 36 metres (120 feet) by 26 metres (86 ç
feet).
The R<193>jagopuram (main tower) is onthe west instead of the east. ç
It is 42metres (137 feet) high and 27 metres (90 feet) wide.
The bathing ghat is said to contain nine t<200>rthas (holy waters) ç
which can purify the devotees who take bath in it.
A little away from the temple, on the seashore there is a small well ç
inside another which has crystal clear water. It is reputed to have ç
been specially created by Lord Muruga to appease the thirst of his ç
soldiers.
The major festivals celebrated at the temple campus are:
@Z_TBL_BEG = COLUMNS(2), DIMENSION(IN), COLWIDTHS(1.4167,E1), ABOVE(.0417), ç
BELOW(.0278), VGUTTER(.0833), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT
Vaik<193>si Visagam, in May-June
°vani festival, in August-September
Skanda festival, for seven days in<R>ç
October-November
and M<193>si festival, for 12 days in<R>ç
	February-March.
@Z_TBL_END = 
There are ten sub-temples in the nearby areas, the Ve<209>ka<219><193>calapati ç
temple at Arumigu being the more popular one.
The temple administration is running an orphanage with 125 children.
Out of the few inscriptions in the campus, the one of 9th century ç
<MS>A.<|>D.<D> is the earliest.
@NT = Tirunallar
One of the nine planetary deities, <185>ani or <185>anai·cara, is ç
more feared than loved since he is the lord of afflictions. Though ç
separate temples dedicated to him are not very common, we have one ç
at Tirunallar, just 5 kms. (3 miles) to the west of the town Karaikal ç
in the Puduchery (or Pondicherry) State.
It is actually a minor temple in the complex of the bigger <185>iva ç
temple called Darbh<193>ra<207>ye·vara Temple situated on the south ç
bank of K<193>ver<200>.
According to the local legends the <185>ivali<209>ga was discovered ç
in a forest covered with the darbha grass (Poa-cyno- suriodes) by ç
Brahm<193> the creator himself. Feeling happy about it he mentally ç
worshipped it and built a temple round it decorating it with navaratnas ç
(nine gems). The temple has therefore came to be known as Darbh<193>ra<207>ye·vara ç
Temple.
Using his da<207><195>a (holy stick) he dug a tank, known as Brahmada<207><195>a-t<200>rtham. ç
Thereafter Indra and other deities also created such holy tanks.
@SPACE1 = 
Darbh<193>ra<207>ye·vara is the main deity of the temple. The other ç
deities are Pr<193><207><193>mbik<193>, Ty<193>gar<193>ja, N<200>lotpal<193>mbik<193> ç
and Vin<193>yaka.
@SPACE1 = 
The <185>anai·cara temple is just outside, the image being in a niche.
@SPACE1 = 
King Na<202>a who was under the malefic influence of <185>ani, worshipped ç
this <185>iva and got rid of all of his troubles. Hence he stayed ç
here for some time and dug a tank which now bears his name as Na<202>at<200>rtham. ç
The deity itself got the name Nallar and Nallatra ®·ar.
@SPACE1 = 
Later he worshipped <185>ani also and received his blessings. This ç
<185>ani henceforward became very famous and started attracting a ç
large number of devotees.
@SPACE1 = 
The image is black in colour with one hand showing abhayamudr<193> ç
(assuring protection) which is rather rare. There is a golden crow ç
which is his mount.
@SPACE1 = 
Five p<220>jas are performed everyday to this deity. Saturday is considered ç
as a sacred day to worship him.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
The festivals normally celebrated are:
@Z_TBL_BEG = COLUMNS(2), DIMENSION(IN), COLWIDTHS(1.4492,E1), ABOVE(.0555), ç
BELOW(.0555), VGUTTER(.0555), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT
°dip<220>ram; Ambu;<R>ç
<+><+>Brahmotsava and<R>ç
<+><+>Rathotsava, (April-May for<R>ç
<+><+><+><+><+><+><+><+><+><+><|>18 days)
Navar<193>trikolu,, <+><+><185>ivar<193>tri, (February-March)
Vin<193>yakacaturth<200>, (September)
@Z_TBL_END = 
A very important festival is held for two days whenever the planet ç
<185>ani leaves one r<193>·i (zodiacal sign) and enters the next, ç
which will last for 2 1/2 years. This is called <185>anipey<193>rci. ç
During this festival lakhs of devotees gather at this temple.
@NT = Tripur<193>r<207>ava Tantra
This is considered as an important work of the tantra-group. It is ç
stated to be a condensed version of a much bigger original work. It ç
has 1636 ·lokas or verses spread over 21 tara<209>gas or chapters ç
and is in the form of a dialogue between the Dev<200> (P<193>rvat<200>) ç
and ®·vara or <185>iva.
A brief synopsis of the contents of the work may now be attempted ç
here:
@S10N = Tara<209>ga 1 (211 ·lokas)
This tara<209>ga deals with the details connected with Tripur<193>d<200>k<218><193> ç
such as the qualities of the guru and the disciple, settling the date ç
and time considered as auspicious, worship of the <185>r<200>cakra, ç
homa, imparting the pa<210>cada·<193>k<218>ar<200> mantra (see <MS>PA<178>CADA<185>°K<186>AR® ç
MANTRA<D> and <MS><185>R®VIDY°<D>.) and p<220>r<207><193>bhi<218>eka ç
(final ritual bath).
@S10N = Tara<209>ga 2 (105 ·lokas)
This section delineates the topics like <218>a<219>cakrabheda (See ç
<MS>CAKRAS<D>.), four types of pr<193><207><193>y<193>ma, method of ç
ajap<193>japa (See <MS>AJAP°JAPA<D>.) and some aspects of worship.
@S10N = Tara<209>ga 3 (147 ·lokas)
This chapter starts with the rites connected with the entering of ç
the p<220>j<193>mandira or the main shrine. It is then followed by ç
the descriptions of the details of p<220>j<193> or worship.
Ny<193>sas (ritual purification of limbs) connected with the <218>o<195>a·<200> ç
and the pa<210>cada·<193>k<218>ar<200> mantras (See <MS><185>R®VIDY°<D>.) ç
as also other ny<193>sas are described next.
@S10N = Tara<209>ga 4 (90 ·lokas)
Drawing of the <185>r<200>cakra on metal plates of gold, silver and ç
certain other materials is described here. Worship of <185>iva-·<193>lagrama ç
and li<209>gas got in the Narmad<193> river is highly beneficial and ç
hence eulogised.
@S10N = Tara<209>ga 5 (32 ·lokas)
This section is mainly concerned with p<200><219>hap<220>j<193> or ç
the worship of the small table on which the <185>r<200>cakra is kept. ç
Several deities are established ceremonially on it with the appropriate ç
mantras.
@S10N = Tara<209>ga 6 (60 ·lokas)
This chapter describes the <193>v<193>hana or inviting and instilling ç
the goddess in the <185>r<200>cakra. Three types of p<220>j<193>†par<193>, ç
apar<193> and mi·ra†are also stated.
@S10N = Tara<209>ga 7 (36 ·lokas)
Worship of two cakras†Sarv<193>·<193>-parip<220>ra<207>a and Sarvsa<221>k<218>obha<207>a†is ç
set out here. They are two of the nine cakras or yantras of the <185>r<200>cakra.
@S10N = Tara<209>ga 8 (36 ·lokas)
This tara<209>ga gives the details of theworship of the deities like ç
Ga<207>e·a, the Navagrahas, nak<218>atras (asterisms), goddesses like ç
the <195><193>kin<200>s and yogin<200>s, as also K<193>me·var<200>, ç
Bhagam<193>lin<200>, Vajre·var<200> and Mah<193>tripurasundar<200>.
@S10N = Tara<209>ga 9 (48 ·lokas)
The topics discussed here are: establishment of the vessels for arghya†both ç
s<193>m<193>nya (general) and vi·e<218>a (special)†, for kala·a as ç
also the metals to be used in their preparation. Related rites are ç
also described.
@S10N = Tara<209>ga 10 (65 ·lokas)
This section deals mainly with the pa<210>camak<193>ras or the five ç
M's (See under <MS>TANTRAS<D>.).
@S10N = Tara<209>ga 11 (57 ·lokas)
@EMERGEN1 = Various kal<193>s (aspects of Mother goddess in a minor ç
form) grouped under Agnikal<193>, S<220>ryakal<193> and Somakal<193>, ç
are described here.
@S10N = Tara<209>ga 12 (32 ·lokas)
@EMERGEN1 = P<220>j<193> (ritualistic worship) and homa (worship through ç
fire) of various kinds are the subject matter here.
@S10N = Tara<209>ga 13 (69 ·lokas)
@EMERGEN1 = This tara<209>ga deals with the final stages of p<220>j<193> ç
and disposal of things connected with it.
@S10N = Tara<209>ga 14 (103 ·lokas)
@EMERGENCY = This section contains many details connected with the ç
kaulam<193>rga or kaul<193>c<193>ra†the left handed path of tantras ç
†such as ma<207><195>alaprave·a (entering the sacred spot), p<220>j<193> ç
to elders like one's guru,four kinds of s<193>dhakas†uttama, madhyama, ç
adhama and adham<193>dhama †continuous practice of the disciplines ç
taught, condemnation of religious suicide, deep faith in the guru ç
and the ·<193>stras and so on.
@S10N = Tara<209>ga 15 (47 ·lokas)
@EMERGEN1 = Mudr<193>s or poses of fingers and hands are the subject ç
matter here.
@EMERGENCY = Thirteen mudras, to be shown before Lalit<193>-Tripurasundar<200> ç
are described in detail. Some of them are: sa<209>k<218>obhi<207><200>, ç
vidr<193>vi<207><200>, <193>kar<218>a<207><200>, va·a<209>kar<200>, ç
p<193>·amudr<193>, a<209>ku·amudr<193> and so on.
@EMERGEN1 = Some other mudr<193>s used in p<220>j<193>†like dhenumudr<193> ç
or t<193>rk<218>yamudr<193>†are also given.
@S10N = Tara<209>ga 16 (20 ·lokas)
@SPACE1 = 
@SPACE1 = 
Shortened forms of p<220>j<193> are prescribed here for the benefit ç
of those whoare unable to do the whole p<220>j<193> duetovarious ç
factors including lack of intelligence.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@S10N = Tara<209>ga 17 (61 ·lokas)
@SPACE1 = 
@SPACE1 = 
P<220>j<193> is of two kinds: nitya (daily) and naimittika (occasional). ç
Those who cannot do the first, can take recourse to the second. It ç
may be done once a month or once in six months. In extreme cases, ç
it may be got done through the guru or anyone else. This, as also ç
some other special p<220>j<193>s to be done during Navar<193>tra, ç
are described here.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@S10N = Tara<209>ga 18 (76 ·lokas)
@SPACE1 = 
@SPACE1 = 
This tara<209>ga is mainly devoted to the exposition of the famous ç
Kha<195>ga-m<193>l<193>stotra. First, the preliminaries like <216><218>i ç
(sage), chandas (metre), devat<193> (the deity) and viniyoga (utility) ç
are stated. Though the original hymn is in a long metre, da<207><195>aka ç
by name, here the same is stated in the anu<218><219>ubh or ·loka ç
metre.
The Kha<195>gam<193>l<193> hymn has several names of the goddess. ç
The methods of using them in p<220>j<193>, homa and tarpa<207>a (oblations ç
of water) are also indicated.
@S10N = Tara<209>ga 19 (243 ·lokas)
This section starts with a detailed description of the Rahoy<193>ga, ç
a y<193>ga to Dev<200> to be done in seclusion. It can be performed ç
only by those who are initiated into the worship of the dev<200>. ç
The benefits that accrue to its performer as also themethods of remedying ç
the defects thatmight have crept in during the performance are also ç
described.
@S10N = Tara<209>ga 20 (80 ·lokas)
This section gives the mantras of the Atharvaveda used in the Rahoy<193>ga. ç
This is followed by a description of the p<220>j<193> to <185>r<200>cakra ç
with the mantras of the well-known <185>r<200>s<220>kta.
It ends with mentioning the various fruits or results of using different ç
materials like bilva leaves or flowers or cereals in homa.
@S10N = Tara<209>ga 21 (18 ·lokas)
This last tara<209>ga states the different fruits that a person can ç
get by the recitation of the <185>r<200>s<220>kta, which has also ç
been called Tripur<193>s<220>kta here.
@END = <R>ç

