@H = D
@NT = £<193>mara Tantra
@SPACE = 
In the £<193>mara class of tantras, <185>iva as Unmatta Bhairava teaches ç
P<193>rvat<200> as Unmatta Bhairav<200> who starts the work with various ç
questions.
@SPACE1 = 
The  work  mentions  8  Unmatta Bhairavas like Kap<193>li Bhairava, ç
Sa<221>h<193>ra Bhairava and Krodha Bhairava.
@SPACE1 = 
It has six paricchedas or chapters plus a chapter called Ma<209>gal<193>cara<207>a. ç
The whole work is in the ·loka (anu<218><219>ubh) metre, except for ç
the mantras which are in prose.
@SPACE1 = 
@SPACE1 = 
It  is  a  work  of  the  V<193>m<193>c<193>ra tantra group dealing ç
with what is called `<186>a<219>karmas'. They are: stambhana (arresting  all  movement);  mohana  (creating ç
delusions); ucc<193><219>ana (driving away); vidve<218>a<207>a (creating ç
enmity); va·<200>kara<207>a (enslaving); m<193>ra<207>a (killing).
@SPACE1 = 
Under each of the <186>a<219>karmas, many details are given.
@SPACE1 = 
For instance:
@SPACE1 = 
Under va·<200>kara<207>a: how to control the king, a wicked woman, ç
one's own husband.
@SPACE1 = 
Under stambhana: how to stop a ship, a fire, an enemy.
@SPACE1 = 
Under m<193>ra<207>a: how to kill the horse of the enemy, to destroy ç
the clothes of a washerman, to destroy the milk of the milk-vendor ç
and so on.
@SPACE1 = 
The various mantras to be used in such acts, as also the rites connected ç
with them, are also given.
@SPACE1 = 
However, no one should attempt them without valid reasons acceptable ç
to dharma. And, they can be done only under expert guidance.
@NT = Da·a·<193>ntis
@N1 = (`ten propitiatory hymns')
<185><193>ntimantras are propitiatory Vedic chants or hymns used on ç
several occasions including during Vedic studies.
Ten such ·<193>ntimantras are sometimes grouped together and are technically ç
designated as `Da·a·<193>ntaya<199>'.
The  following  are  those  listed underit:
@N = <+>1.
@NK = bhadra<221> kar<207>ebhi<199>....
@N = <+>2.
@NK = namo brahma<207>e....
@N = <+>3.
@NK = namo v<193>ce....
@N = <+>4.
@NK = ·a<221> no v<193>ta<199> pavat<193>m....
@N = <+>5.
@NK = sa<221> tv<193> si<210>c<193>mi....
@N = <+>6.
@NK = ·a<221> no mitra<199>....
@N = <+>7.
@NK = tac-cha<221>yor<193>v<216><207><200>mahe....
@N = <+>8.
@NK = saha n<193>vavatu....
@N = <+>9.
@NK = v<193><209> me manasi....
@N = 10.
@NK = p<220>r<207>amada<199>....
All these, except the fourth and thefifth, have been dealt with under ç
`<185><193>ntimantras'. (See <MS><185>°NTIMANTRAS<D>.)
The fifth mantra†sa<221> tv<193> si<210>c<193>mi.... † is actually ç
from the Taittir<200>ya Sa<221>hit<193> (1.6.1). It is used to address ç
the ghee that has been spilled over in a sacrifice. Simultaneously ç
a wish is expressed to obtain longevity and sons as also wealth.
Here it is listed as a ·<193>nti mantra.
The fourth mantra is a very long passage with verses selected from ç
various sections of the Vedas. The ideas contained in it are also ç
many and varied.
The Da·a·<193>ntis are often chanted in full  on  special  occasions  involving ç
important rituals.
@SPACE1 = 
See also <MS><185>°NTIMANTRAS<D>.
@SPACE = 
@NT = Datt<193>treya Tantra
This is a minor work belonging to the V<193>m<193>cara group of tantras.
@SPACE = 
It has 24 pa<219>alas or chapters and contains 395 verses.
@SPACE = 
The topics dealt with are as follows:
@SPACE = 
M<193>ra<207>a  (getting  an  undesirable person or an enemy killed); ç
mohana (deluding any person); stambhana (arresting the movement of ç
any living being or stopping the working of any object like fire); ç
vidve<218>a<207>a (bringing about enmity between persons previously ç
well-disposed); ucc<193><219>ana (driving away anyone from his place); ç
sarvajanava·<200>kara<207>a (controlling the  minds  of  all  persons);  <193>kar<218>ana ç
(attracting  anyone  towards  oneself); indraj<193>la (several modes ç
of magic); yak<218>i<207><200>s<193>dhan<193> (rites aimed at pleasing ç
the 14 Yak<218>i<207><200>s or minor goddesses); ras<193>yanaprayoga ç
(science of converting base metals into gold or alchemy); k<193>laj<210><193>na ç
(methods of knowing the exact time of one's or others' death); an<193>h<193>ra-yoga ç
(specially prepared medicines that help in overcoming hunger and thirst); ç
nidhidar·ana (discovering hidden wealth through psychic insight); ç
vandhy<193>putravat<200>kara<207>am (certain specially prepared potions ç
by drinking which, a barren woman can conceive); m<216>tavats<193>j<200>vana ç
(helping a women who is losing children, to give birth to long living ç
ones); jayasa<221>v<193>da (rite that helps one to win in debates); ç
v<193>j<200>kara<207>a (means of increasing virility); bh<220>tagrah<193>diniv<193>ra<207>a ç
(driving away the evil spirits).
The text gives the mantras needed for each of the rites and all the ç
other instructions necessary.
Readers of such texts are warned not to practise any of the rites ç
without the guidance of the experts.
@NT = Devan<193>gar<200>
This is the script in which the Sanskrit, Hind<200> and Mar<193><219>h<200> ç
languages are written at present. It is also the official script of ç
the Indian Union.
As far as the origin of the name is considered, it is sometimes conjectured ç
that it might have come from the N<193>gara br<193>hma<207>as of Gujarat.
According to the modern scholars of philology, this is the original ç
script from which many Indian language scripts have been derived. ç
This is clear in the case of Pu<210>j<193>b<200>, Be<209>g<193>l<200>, ç
Ass<193>mese and Gujar<193>t<200> scripts.
The old manuscripts written in Kanna<195>a, Grantha and Nandin<193>gar<200> ç
show the script as influenced by Devan<193>gar<200>.
@SPACE1 = 
The  Br<193>hm<200>  script  has  been considered as the original ç
from which eventhe Devan<193>gar<200> has been derived. (See <MS>BR°HM®<D> ç
for details.) It might have evolved gradually from A·oka's (272-232 ç
<MS>B.<|>C.<D>) time upto <MS>A.<|>D.<D> 800.
@SPACE1 = 
Sometimes, the script as found after <MS>A.<|>D.<D> 1000 in North India ç
is called Devan<193>gar<200> and that in South India as Nandin<193>gar<200>.
@NT = Dhanurveda Sa<221>hit<193>
This is a late work assigned to the 17th Century <MS>A.<|>D.<D> Taught ç
by the sage Vasi<218><219>ha to the sage Vi·v<193>mitra, it is said ç
to be a condensed version of the teaching given by Lord Sad<193>·iva ç
to Para·ur<193>ma, a partial incarnation of Vi<218><207>u. It consists ç
of 271 verses in the anu<218><219>ubh meter with a sprinkling of prose ç
passages.
Though the work concentrates mainly on archery, certain aspects of ç
military science are also dealt with.
The following is a brief account of the subjects dealt with: methods ç
of teaching archery; characteristics of the teacher; shooting techniques; ç
details of bows andarrows; aiming techniques; astras or weapons charged ç
by mantras; use of medicines and charms; strategies of war; help of ç
astrology; vy<220>has or battle-arrays; training the infantry; training ç
of the horses and elephants; techniques of driving chariots; selection ç
of the commander- in-chief; persons not to be killed during a battle.
The work mentions the names of over a hundred weapons used during ç
the ancient days.
See <MS>DHANURVEDA<D> for other details.
@NT = Dhanvantari Jayant<200>
In some regions of India like Gujarat (including  Saurashtra)  the  D<200>p<193>val<200> ç
festival begins on the Trayoda·<200> of °·vayuja (°·vina) K<216><218><207>apak<218>a ç
itself. This is observed as the Jayant<200> (birthday) of Dhanvantari, ç
the physician of the gods, the first physician in creation, an incarnation ç
of Vi<218><207>u. Since he brought the am<216>takala·a or the pot ç
of ambrosia out of the milky ocean, by drinking which, devas or gods ç
became amartya or immortal, it is but proper that the day of his appearance ç
is celebrated in his honour for overcoming death†at least accidental ç
or untimely death†and getting health and longevity. Since this needs ç
the cooperation from Yama, the god of death, a lighted lamp is kept ç
at the main gate of the house in the evening, in his honour. Pleased ç
by that, he will not enter that house nor send his merciless assistants!
Fasting during the day and feasting in the night after lighting lamps ç
is a special feature of this festival. Also, each member of the family ç
is advised to purchase a new vessel and put it at the place of worship, ç
to be used later during the D<200>p<193>val<200> days. Keeping the ç
whole house clean and polishing of all the vessels is another feature ç
noticed on this day. It is also called Dhanteras in North India.
@END = <R>ç

