@H = R
@NT = Raghun<193>thj<200> Temple
Situated in Jammu city, the winter capital of Jammu and Kashmir State, ç
the Raghun<193>thj<200> Temple is the biggest temple complex of North ç
India. It is actually a group of 13 temples, the 14th one†of Na<219>ar<193>ja†having ç
been added recently.
Inspired by and as directed by his guru, R<193>mad<193>sa Bair<193>g<200>, ç
Mah<193>r<193>j<193> Gulab Si<221>ha (Gulab Singh) the then king got ç
the foundation stone laid in <MS>A.<|>D.<D> 1856. The temple complex ç
was completed by his son, the next king, Mah<193>r<193>j<193> Ra<207>ab<200>ra ç
Si<221>ha (Ranbir Singh) in <MS>A.<|>D.<D> 1860.
The sanctum of the main temple contains three beautiful marble images ç
of <185>r<200> R<193>ma, S<200>t<193> and Lak<218>ma<207>a established ç
on high si<221>h<193>sana or throne. R<193>ma's image is darkish in ç
colour, the other two being white. The images are shown withthe hand-pose ç
indicating ma<209>gala or auspiciousness.
Three of the interior walls are covered with gold sheets. The huge ç
temple has seven ·ikharas or spires, each belonging to one deity or ç
shrine. Subsidiary shrines are dedicated to various incarnations of ç
Vi<218><207>u. There is a shrine for S<220>rya or Sun-god also. A ç
large image of Hanum<193>n adorns the entrance.
The complex contain<%24>s<%0>eight enclosures called `ah<193>t<193>s', ç
each having a different name. Of them four named after the four Vedas†e.g.,  Ah<193>t<193>  <184>gveda†are  more ç
important. They contain a large number of images of gods and goddesses ç
as also of `Vibh<200><218>a<207>a, Sugr<200>va, Vi·v<193>mitra, V<193>lm<200>ki ç
and others.
@EMERGEN1 = A very large number of <185>ivali<209>gas and s<193>lagr<193>mas ç
are also found located in these enclosures.
@EMERGEN1 = Behind the temple there is a huge tank covered over with ç
an umbrella-like roof. The water of this tank is used for purposes ç
of p<220>j<193> and other rituals.
Mah<193>r<193>j<193> Ra<207>ab<200>ra Si<221>ha had established  a  Sa<221>sk<216>ta  Mah<193>vidy<193>laya ç
(Sanskrit College) which has now been taken over by the Central Government ç
and renamed `<185>r<200> Ra<207>ab<200>r Kendr<200>ya Sa<221>sk<216>ta ç
Vidy<193>p<200><219>ha'. It runs a P<193><219>ha·<193>l<193> for teaching ç
Sanskrit and various other traditional subjects like Jyauti<218>a ç
(Astro-logy) and Karmak<193><207><195>a (Vedic rituals) leading to ç
diplomas and degrees.
@EMERGEN1 = The temple has a big library containing many valuable ç
Sanskrit manuscripts.
@EMERGEN1 = The important festivals celebrated include R<193>manavam<200>, ç
Janm<193><218><219>am<200> and Vijayada·am<200>.
Music  programmes  are  organised during some festival days like Hol<200> ç
and Vasantapa<210>cam<200>.
@EMERGEN1 = Religious discourses are almost a daily affair.
