@H = I
@NT = I<195>agu<210>ji
@SPACE = 
Ga<207>apati or Ga<207>e·a is one of the most popular deities of Hindu ç
religion. According to the Hindu scriptures he along with his mother ç
Durg<193>†is the god to be worshipped in this age for quick results!
In India, there are eight Ga<207>apati temples in eight places known ç
as siddhiprada-k<218>etras (places of pilgrimage giving quick results ç
for prayers). The Ga<207>apati temple at I<195>agu<210>ji in Northern ç
Karnataka is one such.
The small town of I<195>agu<210>ji is situated at a distance of 12 ç
kms. (8 miles) from the bigger coastal town of Honnavara on the banks ç
of <185>ar<193>vat<200> river of the world famous Jog-falls.
The temple town was originally known as I<195><193>-ku<210>ju, meaning ç
``a forest on the left side (of the river).'' This name gradually ç
became I<195>agu<210>ji.
As per the stha<202>apur<193><207>a or local legend, the V<193>lakhilyas, ç
the diminutive sages, were doing tapas (austerities) here. But they ç
were frequently troubled by herds of elephants. So they requested ç
the sage N<193>rada to help them, by bringing Ga<207>apati from Kail<193>sa. ç
Since the boy Ga<207>apati was fond of pa<210>cakajj<193>ya (a kind ç
of sweet prepared out of five ingredients), N<193>rada managed to ç
bring him to the forest of I<195>agu<210>ji by tempting him with that ç
sweet. As he finally agreed to stay there permanently, a beautiful ç
image was prepared by the divine sculptor Vi·vakarma into which he ç
entered through his spiritual power. And, a temple was built round ç
it. All the gods also started living here in their subtle bodies.
Round the temple, Vi<218><207>u, <185>iva and Brahm<193> created three ç
t<200>rthas or holy water wells, known as Cakrat<200>rtha, <185><220>lat<200>rtha ç
and Kama<207><195>alut<200>rtha which exist even today.
The image is a rare one in the standing posture, with only two hands, ç
holding a lotus and a modaka (a sweetmeat). There is only one more ç
similar image at Gokar<207>a.
The temple is a beautiful structure with the ka<202>a·a (pineal) on ç
the gopuram being gold-plated.
The  main  festivals  are  Ga<207>e·a- caturth<200>   (Bh<193>drapada-·ukla-caturth<200>, ç
generally in September) and Sa<209>ka<218><219>a- caturth<200> (caturth<200> ç
of k<216><218><207>apak<218>a or dark fortnight of every month). If ç
the latter happens to come on Tuesday, it is called A<209>g<193>rakacaturth<200> ç
and is observed in a special way. The rathotsava or temple- car-festival ç
is held during Rathasaptam<200> (generally in February).
Attached to the temple there is aSa<221>sk<216>tap<193><219>ha·<193>l<193> ç
(Sanskrit School) running a course spread over five years. The students ç
are provided free board and lodging.
I<195>agu<210>ji is famous for the art of yak<218>ag<193>na (a type ç
of folk-drama), this Ga<207>apati being the presiding deity for that ç
art.
@NT = International Society for KrishnaConsciousness
Abbreviated as ISKCON, this is a recent Hindu Religious movement started ç
by Bhaktivedanta Swami Prabhupada (<MS>A.D.<D> 1896-1977) in <MS>A.<|>D.<D> ç
1966 in the United States of America (at New York). Known as Abhay ç
Charan De in his premonastic days, he met his guru Bhaktisiddhanta ç
Thakur in <MS>A.<|>D.<D> 1922 at Kolkata and received spiritual initiation ç
from him in <MS>A.<|>D.<D> 1932. Being spiritually inclined and fed ç
up with family life he accepted the monastic vows in <MS>A.<|>D.<D> ç
1959 at V<216>nd<193>ban (in Uttar Pradesh). Henceforward he came ç
to be known as Bhaktived<193>nta Sv<193>mi Prabhup<193>da, but more ç
commonly as <185>r<200>la Prabhup<193>da.
He has many books to his credit, the translations of the Bhagavadg<200>t<193> ç
and the Bh<193>gavata being his best works.
He was responsible in building a magnificent temple of K<216><218><207>a-Balar<193>ma ç
at V<216>nd<193>ban and a holy city called M<193>y<193>pur in West ç
Bengal.
When he started the ISKCON movement he kept before it seven ideals. ç
Some of them are: to systematically propagate spiritual knowledge ç
to the society at large; to spread the idea that K<216><218><207>a ç
is the God as revealed in the Bhagavadg<200>t<193> and the Bh<193>gavata; ç
to teach and encourage the sa<209>k<200>rtana movement (community ç
singing of bhajans); to publish books and periodicals on the theme ç
and philosophy of the movement.
This whole movement is based on the life and message of <185>r<200>k<216><218><207>a ç
Caitanya (<MS>A.<|>D.<D> 1486-1533) and the Gau<195><200>ya Vai<218><207>ava ç
tradition of Bengal.
Because of the great stress laid on the repetition of the famous mantra ç
hare k<216><218><207>a hare k<216><218><207>a k<216><218><207>a k<216><218><207>a ç
hare hare; hare r<193>ma hare r<193>ma r<193>ma r<193>ma harehare ç
(Kalisantara<207>a Upani<218>ad-1), The organisation has come to ç
be known as ``The Hare Krishna Movement''.
Devotees wanting to accept formal initiation into the chanting of ç
this holy mantra are expected to observe certain vows  like  abstaining  from  drinking, ç
gambling, eating meat and illicit sexual relationships.
The movement claims to have 350 centres spread all over the world. ç
Apart from huge temples dedicated to K<216><218><207>a, the  movement  sometimes  undertakes ç
social welfare programmes also.
There   is   a   Governing   Body Commission (GBC) formed in <MS>A.<|>D.<D> ç
1970 to guide the organisation.
The Bhaktivedanta Book Trust (BBT) established in <MS>A.<|>D.<D> 1972 ç
has brought out several volumes of the founder's books over the last ç
few years as also magazines in several languages.
@NT = ®·<193>na-·ivaguru-deva-paddhati
@SB = Introduction
Also known as Tantrapaddhati, this is an important work of the tantra-group, ç
almost encyclopaedic in character. Apart from the general topics dealt ç
with in the tantra-literature like mantras, it covers several aspects ç
of subjects treated in the <193>gamas such as temples, iconography ç
and ritualistic worship.
@EMERGEN1 = It is a voluminous work in 18,000 verses in various metres. ç
They are spread over in four p<193>das or sections, each having several ç
pa<219>alas or chapters, the total number being 119.
@EMERGEN1 = The following table gives an idea of the work:
1.<+>S<193>m<193>nyap<193>da†pa<219>alas 1 to 14;
2.<+>Mantrap<193>da†pa<219>alas 15 to 52;
3.<+>Kriy<193>p<193>da†pa<219>alas 1 to 30;
<+><+><|>Kriy<193>p<193>da (contd.)<R>ç
                †pa<219>alas 31 to 64;
4.<+>Yogap<193>da†pa<219>alas 1 to 3
@EMERGEN1 = The first two p<193>das are called P<220>rv<193>rdha ç
and the last two as Uttar<193>rdha.
@SB = The Author
At the end of the very first pa<219>ala, in the colophon, the author ç
has mentioned his name as `®·<193>na·ivagurudevami·ra'. Some scholars ç
believe, based on the surname `Mi·ra', that he belonged to the country ç
of Mithil<193> (Janakpur in Uttar Pradesh). However, the overwhelming ç
view is that he belonged to the Kerala State.
@EMERGEN1 = There are others who consider him as the guru of L<200>l<193>·uka ç
(before 15th century) the author of the famous work K<216><218><207>akar<207><193>m<216>ta.
@EMERGEN1 = This much can be said that he belonged to a long line ç
of <185>iva-yogis who were very influential during the period 9th ç
to the 11th centuries <MS>A.<|>D.<D>
As regards the title of the text, two more have been suggested. They ç
are:
Tantras<193>ra paddhati and Siddh<193>nta-s<193>ra. They, however, ç
seem to suggest the nature of the work rather than a regular title.
@SB = Source Material
The author has quoted 15 earlier writers and 60 works that were current ç
during his times, as authorities.
Some of the authors are: °ryabha<219>a, Gautama, Pata<210>jali, Par<193>·ara, ç
Bhojar<193>ja, Maya and Vasi<218><219>ha.
The list of 60 works includes many tantras and <193>gamas like Prapa<210>cas<193>ra ç
and Ajit<193>gama as also the Bhagavadg<200>t<193> and pur<193><207>as ç
like the K<220>rma.
Prayogama<210>jar<200> (or Ma<210>jar<%16><200><D%0>) of Ravi and ç
Tattvaprak<193>·a of Bhojadeva have been quoted more often than ç
the others.
@EMERGEN1 = From the list of works quoted, one can guess that the ç
author was well conversant not only with the <185>aiv<193>gamas bu<%32>t<%0>also ç
with several other fields of knowledge such as Jyauti<218>a, °yurveda, ç
Dharma-·<193>stras, various Sm<216>tis, Vy<193>kara<207>a and Yoga.
@EMERGEN1 = It may not be out of place if it is pointed out that the ç
fragrance of the t<193>ntrik and ritualistic aspects of Kerala temples ç
is reflected in this work for obvious reasons.
@SPACE1 = 
@S10N = A BRIEF SUMMARY OF THE WORK
@SB = 1.	S<193>m<193>nyap<193>da
@S10N = Pa<219>ala 1 (91 verses)
This is an introductory section. Definition of the term `mantra' and ç
evolution of the 50 letters of the alphabet as the basic units is ç
the subject.
@S10N = Pa<219>ala 2 (133 verses)
Several concepts like ·aktis and kal<193>s commonly dealt with in ç
the tantras are enumerated here.
@S10N = Pa<219>ala 3 (92 verses)
It describes how each of the letters of the alphabet inscribed in ç
a yantra (mystical diagram) has its own form and colour, a knowledge ç
of which is absolutely necessary.
@S10N = Pa<219>ala 4 (40 verses)
@EMERGEN1 = It deals with the general classification of mantras as ç
str<200> (feminine), pum<193>n (masculine) and <218>a<207><195>a (neuter) ç
and the appropriate endings like sv<193>h<193>, and nama<199>.
@S10N = Pa<219>ala 5 (81 verses)
Six ways of using a mantra in japa† like pallava, yoga and sampu<219>aka†are ç
described here.
@S10N = Pa<219>ala 6 (160 verses)
This deals with varieties of agni-ku<207><195>as (scrificial pits) ç
and ma<207><195>alas (esoteric diagrams). The shapes described are ç
identical for both purposes.
@S10N = Pa<219>ala 7 (37 verses)
Sacrificial vessels like sruk and sruva are described here.
@S10N = Pa<219>ala 8 (129 verses)
Three kinds of p<220>j<193> or ritualistic worship of gods and the ç
various steps involved as <193>v<193>hana (inviting), arghya and p<193>dya ç
(water for washing the hands and feet) are explained in detail.
@S10N = Pa<219>ala 9 (188 verses)
Bath in water with Vedic mantras and by smearing with bhasma or holy ç
ash†this is called <193>gneyasn<193>na (bath by fire)†are described ç
here.
@S10N = Pa<219>ala 10 (41 verses)
Certain purificatory processes involving the five elements of the ç
body through pr<193><207><193>y<193>ma and some internal meditations ç
are given here.
@S10N = Pa<219>ala 11 (71 verses)
This pa<219>ala deals with V<193>stup<220>j<193> and the worship of ç
the V<193>stupuru<218>a (the deity supporting the building to be built ç
on the site chosen for a temple or a house).
@S10N = Pa<219>ala 12 (46 verses)
A<209>kur<193>rpa<207>a or sowing of some seeds in the site chosen ç
for construction is the subject discussed here.
@S10N = Pa<219>ala 13 (76 verses)
This section is devoted to describing the various processes involved ç
in Mantra-d<200>k<218><193> or ceremonially imparting a mantra to ç
a worthy disciple.
@S10N = Pa<219>ala 14 (264 verses)
This pa<219>ala deals with 32 kinds of Vedic fires. Similarly <185>aiva, ç
Vai<218><207>ava andK<193>mya fire-rituals also have been portrayed ç
here.
Thus ends the S<193>m<193>nyap<193>da here.
@SPACE = 
@SB = 2.	Mantrap<193>da
@S10N = Pa<219>ala 15 (136 verses)
This chapter is concerned with <185>iva transformed as Ga<207>apati<192>called ç
Prapa<210>ca- ga<207>apati†and manifesting in six forms such as °moda ç
and Pramoda, along with the respective consorts like Siddhi and K<193>nti. ç
Offerings of flowers, fruits and the sweet modaka are also mentioned.
@S10N = Pa<219>ala 16 (127 verses)
This describes the following aspectsof Ga<207>apati: Mah<193>ga<207>apati, ç
Siddhivin<193>yaka, K<218>ipraga<207>apati and Ucchi<218><219>aga<207>apati.
The benefits of worshipping these are also given.
@S10N = Pa<219>ala 17 (98 verses)
Goddess P<193>rvat<200> as Tripur<193>, meditation on her form, her ç
mantra and cakra (yantra) and the benefits of her worship are delineated ç
here.
@S10N = Pa<219>ala 18 (50 verses)
V<193>g<200>·var<200> in her three forms, viz., Ha<221>sav<193>g<200>·var<200>, ç
Da·<193>k<218>ar<200> V<193>g<200>·var<200> and Siddhav<193>g<200>·var<200>, ç
is the subject discussed here.
@S10N = Pa<219>ala 19 (93 verses)
Called as <185>r<200>h<216>dayam, this chapter deals with the mantra ç
of Lak<218>m<200> which must be received from a preceptor.
The author has dealt with the subject in 34 different metres.
@S10N = Pa<219>ala 20 (38 verses)
This section too is dedicated to the goddess Lak<218>m<200>.
Metres used are 28.
@S10N = Pa<219>ala 21 (166 verses)
Christened as <185>aktipa<219>ala this section deals with the different ç
modes of worship of Dev<200> or <185>akti ranging from the pleasant ç
to horrible forms.
The number of metres used is 30.
@S10N = Pa<219>ala 22 (80 verses)
Goddess Tvarit<193> (like a hunter-woman) is the deity described here.
Ten metres are used in this section.
@S10N = Pa<219>ala 23 (77 verses)
Different aspects of Mother-goddess like Nityaklinn<193> and Vajraprast<193>ri<207><200> ç
as also Gaur<200> are described here.
Number of metres used is 19.
@S10N = Pa<219>ala 24 (85 verses)
Since it covers the worship of five aspects of the goddess Durg<193> ç
it is called Pa<210>cadurg<193>-pa<219>ala.
Meters used are 10 in number.
@S10N = Pa<219>ala 25 (87 verses)
Two aspects of the Divine Mother, Vanadurg<193> and <185><220>lin<200> ç
are dealt with here.
Twelve metres have been used.
@S10N = Pa<219>ala 26 (128 verses)
Special mantras like Bh<220>h<216>daya, some more aspects of the ç
goddess like Tripu<219><193> and Annap<220>r<207><193> as also the ç
rites to propitiate them are described here.
Eight metres have been used here.
@S10N = Pa<219>ala 27 (115 verses)
This pa<219>ala, devoted to S<220>rya, the Sun god gives his mudr<193>s, ç
mantras and modes of worship.
@S10N = Pa<219>ala 28 (164 verses)
Six <185>aivamantras (mantras of <185>iva) are given here.
@S10N = Pa<219>ala 29 (101 verses)
@NID = <+><+><|>This section gives the mantras concerning the three aspects ç
of <185>iva, viz., M<216>tyu<210>- jaya, Tryambaka and Dak<218>i<207><193>m<220>rti.
@S10N = Pa<219>ala 30 (127 verses)
The Aghoramantra and the Aghora-·astra of <185>iva, are described ç
here. They are effective in curing the diseases of human beings and ç
animals.
@SPACE1 = 
@S10N = Pa<219>ala 31 (150 verses)
Some mantras of <185>iva and several conceptions of Subrahma<207>ya ç
are dealt with here.
@SPACE1 = 
@S10N = Pa<219>ala 32 (160 verses)
This pa<219>ala contains the mantras of several deities such as <185><193>st<193>, ç
K<218>etrap<193>la, Ca<207><195>e·vara, Indra and some Yak<218>as, ç
as also the results obtained by propitiating these.
@SPACE1 = 
@S10N = Pa<219>ala 33 (132 verses)
The A<218><219><193>k<218>ar<200>mantra, the most effective of all ç
the Vai<218><207>ava mantras, is given here.
@SPACE1 = 
@S10N = Pa<219>ala 34 (92 verses)
<185>r<200>kar<193><218><219><193>k<218>aramantra of Vi<218><207>u ç
and Gop<193>lakamantra of K<216><207><193> are described here.
@SPACE1 = 
@S10N = Pa<219>ala 35 (180 verses)
This section is devoted to N<216>hari or Narasi<221>ha and his mantra.
@SPACE1 = 
@S10N = Pa<219>ala 36 (43 verses)
Two mantras of Var<193>ha (the boar incarnation), the Mah<193>var<193>ha ç
and the Var<193>haik<193>k<218>ara are given here.
@S10N = Pa<219>ala 37 (108 verses)
The superhuman form of Sudar·ana (the disc of Vi<218><207>u) and his ç
mantra as also the yantra are dealt with here.
@S10N = Pa<219>ala 38 (101 verses)
The Trailokyamohanamantra pertaining to V<193>mana (the dwarf incarnation ç
ofVi<218><207>u) and the associated rites are described here.
@S10N = Pa<219>ala 39 (166 verses)
@EMERGEN1 = Mantras to be used for curing a person bitten by snakes ç
are described here.
@S10N = Pa<219>ala 40 (174 verses)
Treatment for the poison injected by different creatures like serpents, ç
scorpions, rats, spiders and mad dogs is given here showing the knowledge ç
of toxicology of the author.
@S10N = Pa<219>ala 41 (111 verses)
Treatment of children afflicted by evil spirits or diseases like convulsions ç
is described here.
@S10N = Pa<219>ala 42 (36 verses)
@EMERGEN1 = This section deals with grahace<218><219><193> or seizure ç
by demonic forces which are 18in number and the remedial measures.
@S10N = Pa<219>ala 43 (91 verses)
Bh<220>tab<193>dh<193> or demoniac possession and its remedies using ç
special mantras like Kha<195>gar<193>va<207>a, <185><220>lin<200> ç
and Vanadurg<193> are delineated here.
@S10N = Pa<219>ala 44 (24 verses)
@EMERGEN1 = Apasm<193>ra or epilepsy and its cure by certain medicines ç
is described here.
@S10N = Pa<219>ala 45 (207 verses)
Fevers of eight kinds†classified asVai<218><207>ava or <185>aiva!†and ç
some other common diseases are dealt with in this section along with ç
the remedial mantras and medicines.
@S10N = Pa<219>ala 46 (148 verses)
@EMERGEN1 = Diseases of the eye, nose, throat, ear, head etc., are ç
the topics discussed here.
@S10N = Pa<219>ala 47 (130 verses)
<186>a<219>karmas†See <MS><186>A<187>KARMAS<D>.†or the six sorcerous ç
rites and Yama-mantra are described here. They should be used only ç
against the criminals and enemies of the society.
@S10N = Pa<219>ala 48 (105 verses)
Subjugation by enchantment, called <193>k<216><218><219>i, with Lava<207>amantra ç
is the subject of this pa<219>ala.
@S10N = Pa<219>ala 49 (15 verses)
@EMERGEN1 = This small section deals with the diseases of cows and ç
their cure with medicines as also mantras.
@S10N = Pa<219>ala 50 (51 verses)
@EMERGEN1 = Preparation of certain substances like asafoetida and ç
camphor oil is described here.
@S10N = Pa<219>ala 51 (75 verses)
Amusement by creating delusions and jugglery are the subject matter.
@S10N = Pa<219>ala 52 (163 verses)
@EMERGEN1 = Methods of knowing about victory in a battle through the ç
auguries connected with five birds and the rites to be performed to ç
ensure victory are given here.
@SPACE = 
@SB = 3.	Kriy<193>p<193>da
@S10N = Pa<219>ala 1 (161 verses)
@EMERGEN1 = This pa<219>ala deals with four topics: <185>ivasadbh<193>va ç
(existence of <185>iva); °gama-pr<193>m<193><207>ya (authenticity ç
of the <193>gamas); Tattvam<193>t<216>k<193> (letters of the alphabet ç
asaspects of the Divine Mother; and Vastunirde·a (36 tattvas or fundamental ç
principles of <185>aiv<193>gamas).
@S10N = Pa<219>ala 2 (40 verses)
This section discusses the six well-known categories of the <185>aiv<193>gamas ç
and criticises the views of other schools.
@S10N = Pa<219>ala 3 (127 verses)
The nityakarma or the daily routine of a religious man is discussed ç
here in great detail.
@S10N = Pa<219>ala 4 (43 verses)
This describes the purification of the body by sn<193>na or bath and ç
that of the mind by yoga.
@S10N = Pa<219>ala 5 (140 verses)
This pa<219>ala deals with the upac<193>ras or modes of ritualistic ç
worship of deities which may be 16 or 10 or 5
@S10N = Pa<219>ala 6 (131 verses)
The six major aspects of a t<193>ntrik rite are described here. They ç
are: mantra (sacred formula); mudr<193> (poses of fingers and hand); ç
ku<207><195>a (pit for establishing the sacred fire); ma<207><195>ala ç
(esoteric diagram); dravya (specific substances to be used in the ç
rite); and the s<193>dhaka (performer of the rite).
@S10N = Pa<219>ala 7 (18 verses)
Several mudr<193>s or poses of fingers and hand are stated here.
@S10N = Pa<219>ala 8 (133 verses)
Ku<207><195>as (sacrificial pits) of various types and ma<207><195>alas ç
(esoteric diagrams) of various colours are given in great detail in ç
this section.
@S10N = Pa<219>ala 9 (29 verses)
Details of the vessels and materials used in sacrifices, such as sruk ç
and sruva (wooden spoons), ara<207>is (wooden pieces for producing ç
fire), idhma (fuel-sticks) are provided here.
@SPACE1 = 
@S10N = Pa<219>ala 10 (51 verses)
The subject of this pa<219>ala is d<200>k<218><193> (taking certain ç
vows on an auspicious day) before beginning a rite. A<209>kur<193>rpa<207>a ç
(sowing of certain seeds for the protection of the rite) (See <MS>A<177>KUR°RPAØA<D> ç
for details.) which is an important aspect of many religious rites ç
is also described here.
@SPACE1 = 
@S10N = Pa<219>ala 11 (20 verses)
Qualities of the <193>c<193>rya (chief priest) who can officiate in ç
the rites, as also of his disciples or assistants are enumerated here.
@SPACE1 = 
@S10N = Pa<219>ala 12 (104 verses)
Attendant deities like Navagrahas, Ga<207>apati, Dv<193>rap<193>las ç
and Saptam<193>t<216>k<193>s† their forms and worship†are the subject ç
matter here.
@SPACE1 = 
@S10N = Pa<219>ala 13 (172 verses)
The rituals for the worship of <185>iva are elaborated in this pa<219>ala.
@SPACE1 = 
@S10N = Pa<219>ala 14 (32 verses)
Worship of <185>iva with five faces† called Pa<210>c<193>vara<207>a†is ç
the main topic discussed here.
@SPACE1 = 
@S10N = Pa<219>ala 15
This pa<219>ala is in prose. It enumerates the proceedings of the ç
daily sacrifice to be performed according to the <185>aiv<193>gamas.
@S10N = Pa<219>ala 16 (81 verses)
<185>ivad<200>k<218><193> has two aspects: Sab<200>ja and Nirb<200>ja. ç
The latter meant for ordinary persons, has four varieties. This has ç
been discussed here.
@S10N = Pa<219>ala 17 (231 verses)
Six adhv<193>s or paths such as Tattva, Var<207>a and Mantra are described ç
in detail for the benefit of the priest. Each of these has several ç
subdivisions.
@S10N = Pa<219>ala 18 (134 verses)
Nirv<193><207>ad<200>k<218><193> to be given by the preceptor to a ç
worthy disciple is explained here in great detail. A considerable ç
part of this section is in prose.
@S10N = Pa<219>ala 19 (90 verses)
S<193>dhakad<200>k<218><193>†s<193>dhaka means the priest here†the ç
ceremonial vow to be taken by the priest of the sacrifice is described ç
here with all the details, both in verses and in prose.
@S10N = Pa<219>ala 20 (38 verses)
This short section deals with the pr<193>ya·cittas or expiatory rites ç
to ward off the evil effects of mistakes committed in the performance ç
of the rites.
@S10N = Pa<219>ala 21 (127 verses)
Pavitr<193>ropa<207>a, investing the image in the sanctum of the temple, ç
with the yaj<210>opav<200>ta or the sacred thread, once a year is ç
the subject discussed here.
@S10N = Pa<219>ala 22 (71 verses)
Worship of the creeper damana (artemisia indica) during Vasanta ç
or the spring season is described here. It is said to please <185>iva.
@S10N = Pa<219>ala 23 (41 verses)
For performing sacrifices and constructing temples, the land should ç
becarefully selected as per the rules prescribed by competent authorities. ç
That is being explained here.
@S10N = Pa<219>ala 24 (35 verses)
As a prelude to architectural designs the author introduces certain ç
measurements in this chapter, based on the shadow of a <185>a<209>ku ç
or gnomon. This is called `<185>a<209>kucch<193>y<193>'.
@S10N = Pa<219>ala 25 (85 verses)
Technical terms for the measurement of lands as also the definition ç
of places like villages, towns and cities etc., are discussed and ç
stated here.
@S10N = Pa<219>ala 26 (126 verses)
Selecting a suitable land for building a temple and making it ready ç
is described here.
@S10N = Pa<219>ala 27 (105 verses)
V<193>stup<220>j<193> (worship of the V<193>stupuru<218>a), i<218><219>ak<193>ny<193>sa ç
(installation of bricks) and fixing the place for the garbhag<216>ha ç
(sanctum) are the topics dealt with in this pa<219>ala.
@S10N = Pa<219>ala 28 (145 verses)
The description and enumeration of temples and dwellings of men is ç
the chief topic of this section wherein 52 varieties of temples and ç
46 varieties of dwellings for men have been described.
@S10N = Pa<219>ala 29 (217 verses)
The same topic of the previous pa<219>ala is continued here, giving ç
details.
@S10N = Pa<219>ala 30 (79 verses)
Several types of structures for the dwelling of human beings are described ç
here. Multi-storeyed buildings (from 3 storeys up to 12) also can ç
be built. However, buildings higher than 100 hastas (about 150 feet) ç
are not safe and hence should not be attempted.
@S10N = Pa<219>ala 31 (149 verses)
This chapter is devoted to the enume-ration and description of the ç
different parts of a temple like base, pillars, rafters, beams and ç
doors. Several varieties of each are also mentioned based upon the ç
works of Maya and Par<193>·ara.
@S10N = Pa<219>ala 32 (124 verses)
Several architectural details of the temple structure are given here. ç
Construction of a big water tank for the benefit of weary travellers ç
is also dealt with.
@S10N = Pa<219>ala 33 (101 verses)
Six types of materials like granite, wood and baked bricks, needed ç
for the construction of temples and palaces are dealt with in detail.
@S10N = Pa<219>ala 34 (94 verses)
This pa<219>ala discusses the topic of the selection of a well-qualified ç
sthapati or architect and the fixing of the pinnacle (st<220>p<200> ç
and kumbha) under his guidance. Other topics delineated are the installation ç
of the idol on an auspicious day and allied subjects.
@S10N = Pa<219>ala 35 (120 verses)
Repair of damaged parts of a temple, places of minor deities and details ç
of the gopura (ornamental tower in front of the main gate) are the ç
subjects dealt with here.
@S10N = Pa<219>ala 36 (80 verses)
Types of idols†without form, with definite forms and with a partial ç
form as also the materials used to make them are described here.
@S10N = Pa<219>ala 37 (82 verses)
This section describes the selection of granite by applying various ç
methods of testing.
@S10N = Pa<219>ala 38 (59 verses)
Measurements  and  others  details connected with the preparation ç
of idols are taken up here. The three forms of temple architecture ç
viz., N<193>gara, Dr<193>vi<195>a and Vesara are also discussed.
@S10N = Pa<219>ala 39 (105 verses)
Twelve varieties of p<200><219>has or bases of images are described ç
in this pa<219>ala.
@S10N = Pa<219>ala 40 (38 verses)
Idols made of different materials, prepared according to the specifications ç
of <185>aiv<193>gamas, form the subject matter.
@S10N = Pa<219>ala 41 (131 verses)
Idols of three types†acala (fixed), cala (movable) and cal<193>cala ç
(movable and fixed)†are discussed here. Details of measurements of ç
the images of male deities are also given.
@S10N = Pa<219>ala 42 (84 verses)
Measurements concerning the idols of female deities are given in this ç
pa<219>ala.
@S10N = Pa<219>ala 43 (118 verses)
In this section 16 forms of <185>iva associated with P<193>rvat<200> ç
and Skanda, and other aspects, are described along with the weapons ç
and the mount Nandi.
@S10N = Pa<219>ala 44 (28 verses)
Purificatory rites in a temple after the installation ceremony are ç
the main topic discussed.
@S10N = Pa<219>ala 45 (117 verses)
Rites connected with the installation of the idol, including refixing ç
after repair works are detailed here.
@S10N = Pa<219>ala 46 (109 verses)
Infusing life into the image after ceremonially bathing it with waters ç
drawn from several sacred rivers is the main subject dealt with here.
@S10N = Pa<219>ala 47 (134 verses)
Rites in connection with the installa-tion are detailed again in this ç
section.
@S10N = Pa<219>ala 48 (107 verses)
Nityotsava or the daily rituals of the temples is the main topic here. ç
Annual festivals are also discussed.
@S10N = Pa<219>ala 49 (238 verses)
Observance of occasional festivals as also dhvaj<193>roha<207>a (hoisting ç
the temple flag) are described in this pa<219>ala.
@S10N = Pa<219>ala 50 (368 verses)
This long chapter deals mainly with the bathing of the image with ç
sanctified water from numerous pots, the number of pots varying from ç
9 up to 1008.
@S10N = Pa<219>ala 51 (71 verses)
Installation of the idols of gods like S<220>rya, Ga<207>apati, Skanda, ç
Durg<193> and others is the topic of this pa<219>ala. The worship ç
of S<220>rya is dealt with in great detail.
@SPACE1 = 
@S10N = Pa<219>ala 52 (46 verses)
This  chapter  is  devoted  to  the installation and worship of Vighne·vara ç
or Ga<207>e·a.
@SPACE1 = 
@S10N = Pa<219>ala 53 (93 verses)
Installation and worship of Skanda is the topic here.
@SPACE1 = 
@S10N = Pa<219>ala 54 (148 verses)
Installation of Haran<193>r<193>ya<207>a or <185>a<209>karan<193>r<193>ya<207>a ç
and his worship are described here.
@SPACE1 = 
@S10N = Pa<219>ala 55 (91 verses)
This section is devoted to the installa-tion and worship of Mother ç
Durg<193>.
@SPACE1 = 
@S10N = Pa<219>ala 56 (101 verses)
Gaur<200> is the goddess whose installation and worship are discussed ç
here.
@SPACE1 = 
@S10N = Pa<219>ala 57 (87 verses)
Goddess Sarasvat<200> is the main topic of this chapter.
@SPACE1 = 
@S10N = Pa<219>ala 58 (84 verses)
<185><193>st<193> or Bh<220>tan<193>tha is the topic discussed here. ç
Measurements of the idol, details of the weapons and his eight aspects ç
like Gopt<193>, Pi<209>gala and V<200>rasena are also described.
@S10N = Pa<219>ala 59 (168 verses)
The Saptam<193>t<216>k<193>s (Seven Divine Mothers) such as Br<193>hm<200>, ç
M<193>he·var<200> andKaum<193>r<200> as also V<200>rabhadra and Vighne·vara,  always  go  together  in ç
temples. Their installation and associated rituals have been described ç
here.
@S10N = Pa<219>ala 60 (85 verses)
Every temple must have a K<218>etrap<193>la to protect the sanctum. ç
His installation and other details are given here.
@S10N = Pa<219>ala 61 (56 verses)
The method of offering food to the deity in a temple prepared out ç
of grains after  the  harvest  is  described  here. Festival of lamps ç
conducted during special occasions is also narrated.
@S10N = Pa<219>ala 62 (94 verses)
Antye<218><219>i or funeral rites are described here in great detail.
Large portions of this section are in prose and poetry, but un-numbered.
@S10N = Pa<219>ala 63 (101 verses)
Pr<193>ya·cittas or expiatory rites are the main topic discussed here.
@S10N = Pa<219>ala 64 (52 verses)
Renovation of the idols, shrines and other structures forms the main ç
topic.
Thus ends the Kriy<193>p<193>da here.
@SPACE = 
@SB = 4.	Yogap<193>da
@S10N = Pa<219>ala 1 (55 verses)
In this pa<219>ala characteristics of Yoga †the means to mok<218>a ç
or liberation†with vair<193>gya or the spirit of renunciation as the ç
chief means, are described.
This Yogap<193>da is the shortest and has just 3 pa<219>alas.
@S10N = Pa<219>ala 2 (87 verses)
The concept of Yoga, based on the Yogas<220>tras of Pata<210>jali, ç
is explained here including the first four steps of the eight-limbed ç
Yoga.
@S10N = Pa<219>ala 3 (96 verses)
Starting again with pr<193><207><193>y<193>ma the last four steps ç
have been covered here.
@SPACE = 
@SB = Epilogue
The original work in Devan<193>gar<200> script, based on three manuscripts, ç
was first edited and published by T. Ga<207>apati <185><193>stri in ç
<MS>A.<|>D.<D> 1920 from Trivandrum (now Tiruvananthapuram). Due to ç
the defects in the manuscripts, a small part of the text has been ç
lost. Quite a large portion is in prose. This part as also many verses ç
have not been numbered. Hence it can be said that the work contains ç
more material than the 18,000 verses mentioned earlier.
The style of the work is simple and elegant. The material presented ç
is very vast and covers several fields of ancient and medieval knowledge.
Though some portions seem to reflect the culture of Kerala region ç
of India more, the relevance of the work as a whole to the field of ç
Hindu rituals cannot be questioned.
It is a treat for the scholars of Indology in general and to the Hindu ç
priestly class in particular.
See also <MS>HINDU TEMPLES<D>, <MS>M<188>RTI<185>ILPA-<185>°STRA<D> ç
and <MS>TANTRAS<D>.
@END = <R>ç

