@H = A
@NT = Ahobilam Temples
@SPACE = 
Ahobilam is a rare k<218>etra or place of pilgrimage, specially devoted ç
to the god Narasi<221>ha.
It is situated near the Rudravaram village in the Nallamalai range ç
of hills ofAndhra Pradesh. The distance from Kadapa (or Cuddapah) ç
is 112 kms. (70miles).
It has two main temples, called in the local language (Telugu) as ç
`Diguva Ahobilam' and `Yeguva Ahobilam'.
According to the local legends this hill was once the palace of the ç
demon king Hira<207>yaka·ipu, wherein, Lord Vi<218><207>u emerged ç
out of a pillar in the form of Narasi<221>ha (man-lion) and killed ç
him. It is this palace that gradually became a hill over thousands ç
of years.
Great  sages  like  Vasi<218><219>ha  and Gobhila as also Garu<195>a ç
(the Eagle-mount of Vi<218><207>u) are said to have worshipped the ç
Lord Narasi<221>ha here.
At Yeguva Ahobilam, above the hill, the shrine is small. It is situated ç
in the valley of two high hills and on the bank of the river Bhavan<193>·in<200>. ç
The Svayambh<220> or self-manifested image of Narasi<221>ha is in ç
a small rock-cut cave (or rather a hollow). By its side there is another ç
small cave housing the image Lak<218>m<200>, locally known as Ce<210>cu ç
(Chenchu). The story goes that after Narasi<221>ha killed Hira<207>yaka·ipu ç
he continued to stay there forgetting his spouse Lak<218>m<200> who ç
was languishing in Vaiku<207><219>ha. So Lak<218><221>i managed to ç
be born as the beautiful daughter of the chief of the Chenchu tribe ç
(a tribe living in hills and forests). In her youth, she was seen ç
by Narasi<221>ha who fell in love with her and married her.
The image of Narasi<221>ha has ten b<193>hus or arms. Six arms are ç
engaged in killing the demon. Two are holding the ·a<209>kha (conch) ç
and cakra (discus). The last two are wearing divine weapons. Athis ç
feet is standing the boy-devotee Prahl<193>da.
The temple complex is fairly big. There are quite a few ma<207><195>apas ç
(pillared structures) out of which one is known as `N<220>ruk<193><202><202>a-ma<207><195>apamu' ç
(the `hundred pillered ma<207><195>pa'). Water of the Bhava-n<193>·in<200> ç
river is led into the temple kitchen through pipe-like devices in ç
the rock.
Near this temple, upon one of the precipitous sides of a deep and ç
dangerous ravine, is an iron pillar. If barren women can manage to ç
go round it, they are believed to be blessed with children in course ç
of time.
This temple is said to have been visited by R<193>m<193>nuja (<MS>A.<|>D.<D> ç
1017-1137), Ved<193>nta De·ika (<MS>A.<|>D.<D> 1268-1369) and <185>r<200> ç
K<216><218><207>a Caitanya (<MS>A.<|>D.<D> 1486-1533)
Tiruma<209>gai °<202>v<193>r (8th cent. <MS>A.<|>D.<D>) also visited ç
this temple as can be surmised by the reference to it in his poems.
The sixth pontiff of the Ahobila Ma<219>ha (See <MS>AHOBILA MA<187>HA<D> ç
for details.), Par<193><209>ku·a Yat<200>ndra, is reputed to have ç
had the vision of the deity here and disappered into the cave.
There are nine temples of Narasi<221>ha spread over the entire region. ç
Hence it is called `Nava-N<193>rasi<221>ha-k<218>etra'.
Out of these, three are situated at (Diguva Abohilam) the foot of ç
the hills. They are: Bh<193>rgava Narasi<221>ha; Yog<193>nanda Narasi<221>ha, ç
and Chatrapa<219>a Narasi<221>ha.
The other six, above the hills, are: K<193>ra<210>ja Narasi<221>ha; ç
Abohila Narasi<221>ha (the main deity); Kro<195><193>k<193>ra (or ç
Var<193>ha) Narasi<221>ha; M<193>lola Narasi<221>ha; Jv<193>l<193> ç
Narasi<221>ha; P<193>vana Narasi<221>ha.
Apart from these nine deities, there is the tenth deity known as `Prahl<193>da-Varada-Narasi<221>ha'. ç
This is the god at the main temple in Diguva Ahobilam.
The small river Bhavan<193>·in<200>, consi-dered as equal to Ga<209>g<193>, ç
flows on thesehills. This is said to be the river in which Lord Narasi<221>ha ç
washed hisblood-stained hands after killing the demon Hira<207>yaka·ipu.
Thirteen rivulets, all being tributaries of Bhavan<193>·in<200>, are ç
also found on the hills. Some of them are: Narasi<221>ha-t<200>rtha; ç
R<193>mat<200>rtha; <185>a<209>karat<200>rtha; Var<193>hat<200>rtha ç
and Bhairavat<200>rtha.
The Diguva Ahobilam temple was ransacked by muslim marauders in <MS>A.<|>D.<D> ç
1577. Two generals of the Vijayanagar Empire came here, drove away ç
the enemies and restored the original glory. In memory of this victory, ç
a stone pillar called `Jayastambha' was erected in front of the temple ç
which can be seen even today.
About 20 inscriptions dating from the14th to the 16th centuries have ç
been found here.
The main festivals celebrated in the temples are: Brahmostsava (the ç
annual festival); Narasi<221>ha Jayant<200>; Dasar<193>.
There is also another festival called `Parvata-festival'. During this ç
period the Utsava-m<220>rti (festival image) is taken round the nearby ç
villages (about 50) for 45 days. This is an occasion of great joy ç
and mirth for the village folks.
See also <MS>NARASI<189>HA<D>.
@SPACE1 = 
@NT = Ambuv<193>c<200>
@N1 = (`expecting rains')
Mother Earth (Bh<220>dev<200> or Dhara<207><200>) when expecting the ç
rains (i.e. just before the starting of the rainy season), is called ç
`Ambuv<193>c<200>'. It is also the name of the fertility rite normally ç
observed in Bengal. During this period of four days†°<218><193><195>ha ç
k<216><218><207>a da·am<200> to trayoda·<200> (June/July)†the Mother ç
Earth is said to be unclean and hence no ploughing or sowing or any ç
other type of farm work is done.
@SPACE1 = 
@NT = Antary<193>ga
@N1 = (`internal worship)
See under <MS>TANTRAS<D>.
@SPACE1 = 
@NT = Aru<207>apra·na
@N1 = (`the section connected with Aru<207>a [or Sun]')
This is a famous and popular Vedic passage forming the first prap<193><219>haka ç
(Chapter) of the Taittir<200>ya °ra<207>yaka. Since it is mainly ç
devoted to Aru<207>a or the Sun god, it has been named Aru<207>apra·na ç
(or Aru<207>opani<218>ad). It is used extensively in all rituals ç
and religious rites connected with S<220>rya or the Sun-god on occasions ç
such as Makarasa<207>kr<193>nti, Rathasaptam<200> and  the  month  of  M<193>gha  (January- ç
February).
It is a very long passage involving a variety of subjects. It has ç
32 anuv<193>kas (sections) each anuv<193>ka containing some ka<207><195>ik<193>s ç
(short or long mantras in prose), the total of the latter being 130.
A very brief summary of these anuv<193>kas can now be given:
@S10N = Anuv<193>ka 1 (3 ka<207>dik<193>s)
This Anuv<193>ka is devoted entirely to praising and praying to the ç
deities of waters.
May the deities Agni, V<193>yu and S<220>rya bring to me the sacred ç
rivers†Ga<209>g<193> Yamun<193> and others.
May the deities of waters give me many sons.
May they destroy all my diseases and troubles.
May the earth protect me.
@SPACE = 
@S10N = Anuv<193>ka 2 (4 ka<207>dik<193>s)
Four ways of gaining knowledge are stated first.
The concept and the various divisions of time based on the movement ç
of the sun are described next. Time personified as K<193>lapuru<218>a ç
(Cosmic Person of eternity) is portrayed beautifully.
However, time at the mundane level as related to sacrifices is dear ç
to men.
@S10N = Anuv<193>ka 3 (4 ka<207>dik<193>s)
This section deals with the <216>tus or seasons.
The terms mentioned here are:
@Z_TBL_BEG = COLUMNS(4), DIMENSION(IN), COLWIDTHS(.3333,.9750,.1667,E1), ç
ABOVE(.0139), BELOW(.1111), HGUTTER(.0555), VGUTTER(.0042), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE TEXT
, muh<220>rta, :, 48 minutes.
, 30 muh<220>rtas, , aho-r<193>tra,, day and<R>ç
<+><+><+><+><+><+><+>night,, dina.
, m<193>sa, :, 30 dinas.
, <216>tu, :, 2 m<193>sas.
@Z_TBL_END = 
The three well-known <216>tus described here are:
@Z_TBL_BEG = COLUMNS(4), DIMENSION(IN), COLWIDTHS(.3333,.9167,.2500,E1), ç
ABOVE(.0278), BELOW(.0417), HGUTTER(.0555), VGUTTER(.0083), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE TEXT
, Vasanta-<216>tu, †, Spring
, Gr<200><218>ma-<216>tu, †, Summer
, Var<218>a-<216>tu, †, Rainy season
@Z_TBL_END = 
Their   characteristics   also   are described.
@S10N = Anuv<193>ka 4 (3 ka<207>dik<193>s)
The next three <216>tus are described here. They are:
@Z_TBL_BEG = COLUMNS(4), DIMENSION(IN), COLWIDTHS(.3333,.9167,.2500,E1), ç
ABOVE(.0278), BELOW(.0417), HGUTTER(.0555), VGUTTER(.0083), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE TEXT
, <185>arad-<216>tu, †, Autumn
, Hemanta-<216>tu, †, Early winter
, <185>i·ira-<216>tu, †, Winter
@Z_TBL_END = 
In the last <216>tu, people suffer due to scarcity of water.
@S10N = Anuv<193>ka 5 (2 ka<207>dik<193>s)
This describes the greatness of the gods known as `Vi·vedevas'.
@S10N = Anuv<193>ka 6 (3 ka<207>dik<193>s)
It first describes the effect of the <185>i·ira-<216>tu (winter) wherein ç
people pay attention to keeping themselves warm, above all other things.
Then it declares that those who perform the rituals prescribed for ç
each of these <216>tus (or seasons) will attain greatness here and ç
become one with S<220>rya after death.
@S10N = Anuv<193>ka 7 (6 ka<207>dik<193>s)
There are seven S<220>ryas or Sun-gods. They are: °roga, Bhr<193>ja, ç
Pa<219>ara, Pata<209>ga, Svar<207>ara, Jyoti<218><200>m<193>n and ç
Vibh<193>sa.
The sage Ka·yapa who lives on the Meru mountain is considered the ç
eighth S<220>rya from whom the seven S<220>ryas get their power to ç
shine.
Out of these, °roga gives light and heat to us, of this world.
The others give light to the upper and the lower worlds.
These seven S<220>ryas are satiated by the offerings given by the ç
sacrificer and give him whatever he needs and wants.
@S10N = Anuv<193>ka 8 (8 ka<207>dik<193>s)
The earth and the sky are supported by Vi<218><207>u. They give to ç
the human beings and animals the food that is needed.
M<216>tyu or death is of four types: para(highest), avama (lowest), ç
madhyama (middling) and catu (the fourth).
S<220>rya  is  para-m<216>tyu.  V<193>yu  is madhyama-m<216>tyu. J<193><219>har<193>gni ç
(digestive power) is avama-m<216>tyu. And, Candra (the Moon) is catu ç
or the fourth m<216>tyu.
These m<216>tyus or deaths are ordained upon people according to their ç
karmas.
There is an interesting description of the various punishments given ç
to the sinners.
@S10N = Anuv<193>ka 9 (7 ka<207>dik<193>s)
This anuv<193>ka describes that there are eight Agnis, eleven V<193>yus, ç
and eleven Gandharvas.
This is followed by a prayer to Gaur<200>, the White One, viz., Sarasvat<200>, ç
the goddess of speech.
All the gods worship Ak<218>ara, the indestructible Brahman. They ç
appointed the sage Jamadagni as the protector of this science of meditation ç
on Ak<218>ara. He created the mantras in metres like g<193>yatr<200> ç
through which he spread the knowledge of Ak<218>ara.
The section ends with a well-known ·<193>ntimantra `taccha<221>yor<193>v<216><207><200>mahe...'
@S10N = Anuv<193>ka 10 (7 ka<207>dik<193>s)
Major part of this anuv<193>ka is devoted to the praise of the A·vins, ç
the twin deities.
@S10N = Anuv<193>ka 11 (8 ka<207>dik<193>s)
Holy <216><218>is perform sacrifices like the Somay<193>ga which please ç
God Varu<207>a who gives plenty of rains. Soma juice, the main ingredient, ç
is therefore eulogised here.
Next, there is the statement that those who did tapas to attain higher ç
states were reborn as great sages like Vasi<218><219>ha, Atri, Mar<200>ca ç
and Agastya.
The famous G<193>yatr<200>mantra is a part of this Anuv<193>ka.
Then there is a beautiful description of Param<193>tman as the origin ç
and inspirer of all.
The next section declares that womenwho have attained the °tman are ç
really men whereas the ignorant men are women only!
Next, this world is compared to an inverted tree, as described in ç
the Upani<218>ads. One who realises its ephemeral nature is not afraid ç
of death.
Then comes a short description of the <193>tmaj<210><193>ni, man of ç
realisation.
It ends with a special prayer to Agni and V<193>yu, the gods of fire ç
and wind, to accept the offerings in the sacrifice.
@S10N = Anuv<193>ka 12 (5 ka<207>dik<193>s)
This Anuv<193>ka is mainly devoted to praising Indra, inviting him ç
to the sacrifice to accept the oblations and cause rain through the ç
clouds.
@SPACE = 
@S10N = Anuv<193>ka 13 (3 ka<207><195>ik<193>s)
It begins with the prayer of the sage to Mother Earth and the Sky ç
(Antarik<218>a). He declares that by knowing these, one has no death.
This is followed by a short story of Aditi, the mother of gods. Her ç
eighth issue†in the form of an egg†was born `dead' and so she abandoned ç
it. It is this `dead-egg' that became the Sun, who is hence called ç
`M<193>rtt<193><207><195>a'.
There is a strong belief that these mantras of this Anuv<193>ka should ç
not be heard by pregnant women since it may cause abortion!
@SPACE = 
@S10N = Anuv<193>ka 14 (4 ka<207><195>ik<193>s)
The Sun, causing the various units of time like ahan or day, <216>tus ç
or seasons, sa<221>vatsara or year, takes away our life as also our ç
sons and animals. Hence a prayer is offered to him not to do it! Similar ç
prayer is offered to the nak<218>atras or stars also.
@SPACE = 
@S10N = Anuv<193>ka 15 (1 ka<207><195>ik<193>)
By meditating on the different aspects of °ditya or the Sun I can ç
also shine like them. This is what the <216><218>i is telling.
These aspects are: eight Vasus; eleven Rudras; twelve °dityas; those ç
who speak truth always; the Maruts or wind gods; the <184>bhus (a ç
class of shining gods); the Vi·vedevas; the Sa<221>vatsara (the year).
@S10N = Anuv<193>ka 16 (1 ka<207><195>ik<193>)
The  <216><218>i  declares  `Being  in  the company of the eight S<220>ryas†°roga, ç
Bhr<193>ja, Pa<219>ara, Pata<209>ga, Svar<207>ara, Jyoti<218><200>mata, ç
Vibh<193>sa and Ka·yapa†I am also shining like them!'
Then he prays: `Like the relationship between S<220>rya and waters, ç
let our†my and wife's†relationship too be unbroken!' This last prayer ç
is spread over the anuv<193>kas 14 to 18.
@SPACE = 
@S10N = Anuv<193>ka 17 (2 ka<207><195>ik<193>s)
V<193>yus or the Wind-gods manifest themselves in eleven pairs (along ç
with their spouses).
Some of these are: Prabhr<193>jam<193>n<193>, Prabhr<193>jam<193>n<200>; ç
Vyavad<193>t<193>, Vyavad<193>t<200>; V<193>suki-vaidyut<193>, V<193>suki-vaidyut<200> ç
and soon.
The <216><218>i says that he shines in their places through his tejas ç
(svatejas) or brilliance.
@SPACE = 
@S10N = Anuv<193>ka 18 (1 ka<207><195>ik<193>)
There  is  Agni  in  all  the  eight quarters. Identifying himself ç
with each, the sage says he too shines brilliantly. Prayer for strengthening ç
the bonds of his marriage is also offered.
@SPACE = 
@S10N = Anuv<193>ka 19 (1 ka<207><195>ik<193>)
There are four narakas or hells in the four intermediate directions. ç
They are: Visarp<200> in <193>gneya or south-east; Avisarap<200> in ç
Nair<216>tya or south-west; Vi<218><193>d<200> in <200>·<193>nyaor ç
north-east; and Uttar<193>para in north-west.
`Please protect us from falling into these hells!'†says the <216><218>i.
@S10N = Anuv<193>ka 20 (1 ka<207><195>ik<193>)
This is a prayer to the various deities like Indragho<218>as, Vasus, ç
Manojavases, Pracet<193>s, Rudras, Vi·vakarm<193>, °dityas, Tva<218><219><193>, ç
R<220>pas to protect the beings in their respective regions.
@SPACE = 
@S10N = Anuv<193>ka 21 (3 ka<207><195>ik<193>s)
This is practically a repetition of the first anuv<193>ka.
The famous ·<193>ntimantra (peace-hymn) `o<221> bhadra<221> kar<207>ebhi<199>...' ç
is added here.
The <216><218>is known as Ketuga<207>as, V<193>tara·an<193>s and Sam<193>hit<193>sas ç
are requested to serve or pray to the Jaladevat<193>s or the deities ç
of waters.
@SPACE = 
@S10N = Anuv<193>ka 22 (7 ka<207><195>ik<193>s)
This is the well-known Mantrapu<218>pa. See <MS>MANTRAPU<186>PA<D> ç
for details.
The last part deals with the creation of the worlds, the Sun and the ç
soma juice. It also describes the setting up of the sacrificial fire ç
known as `°ru<207>aketuk<193>gni' in which Agnihotra, Dar·ap<220>r<207>am<193>sa, ç
Pa·ubandha and C<193>turm<193>sya Y<193>gas are performed.
@SPACE = 
@S10N = Anuv<193>ka 23 (9 ka<207><195>ik<193>s)
The process of creation of the world by Praj<193>pati (the Creator) ç
from <193>pas or primeval waters is described first, as also the birth ç
of some sages like Aru<207>as and Ketus from his body.
Suddenly there appeared Brahman in the form of a Cosmic Tortoise who ç
completed the process by creating the °ditya (the Sun), Agni (the ç
fire), V<193>yu (the wind and Indra (the king of gods). The quarters ç
as also a number of other beings were also produced by Him. Then he ç
entered into his own creation. Hence the whole creation is Brahman ç
Himself. One who realises this enters into Brahman or becomes Brahman.
@SPACE = 
@S10N = Anuv<193>ka 24 (4 ka<207><195>ik<193>s)
There are four sources of water in nature. They are: megha (clouds); ç
vidyut (lightning); tu<218><193>ra (fog); v<216><218><219>i (rains).
There are other sources of water on earth. The water from these sources ç
is used in the °ru<207>aketuka sacrifice as follows: Water collected ç
from rain is kept in a container to the east of the sacrificial altar. ç
Well-water is kept in the south. Water collected from small tanks ç
is kept in the west. River water is collected and sprinkled in the ç
direction of north. Water stored in the house in vessels is placed ç
in the middle of the altar. Water from small pits is also collected ç
and sprinkled on the bricks of the altar.
The section ends with the beneficiary results of °ru<207>aketuka sacrifice.
@SPACE = 
@S10N = Anuv<193>ka 25 (3 ka<207><195>ik<193>s)
This section describes the method of preparing an altar for the five ç
Vedic fires. Digging a pit, filling it partly with water, spreading ç
a lotus leaf and placing its stems and flowers and bricks over it, ç
the altar is to be built.
@SPACE = 
@S10N = Anuv<193>ka 26 (7 ka<207><195>ik<193>s)
There are five fires: S<193>vitra, N<193>ciketa, C<193>turhotriya, ç
Vai·vas<216>ja and Up<193>nuvakya.  The  sacrificer  can  offer oblations ç
into these fires separately as per the desire he wants to be fulfilled ç
such as getting children, acquiring cows, rains, health and destroying ç
the enemies.
The Anuv<193>ka warns human beings not to dirty water nor eat animals ç
living in water like tortoise.
@S10N = Anuv<193>ka 27 (6 ka<207><195>ik<193>s)
Worshipping the °ru<207>aketuk<193>gni and offering oblations into ç
it as per the rules of the sacrifices can produce various results. ç
Some of them are: Freedom from the effects of even mortal sins; attaining ç
long life and heaven; realising Brahman; driving away evil spirits; ç
destroying inauspiciousness.
It also urges human beings to forsake the terrible attachment to the ç
body.
@S10N = Anuv<193>ka 28 (1 ka<207><195>ik<193>)
This is a prayer to Agni to drive away all the evil spirits, including ç
their mother V<193>cy<193> (or Ama<209>gala).
@S10N = Anuv<193>ka 29 (1 ka<207><195>ik<193>)
At the instance of the yajam<193>na (the sacrificer), the <216>tviks ç
(priests) offer a prayer to Parjanya, the rain-god, so that people ç
can have plenty of rain.
@S10N = Anuv<193>ka 30 (1 ka<207><195>ik<193>)
This  contains  a  prayer  for  the protection and increase of virility.
@S10N = Anuv<193>ka 31 (6 ka<207><195>ik<193>s)
The first part contains a prayer to Kubera-Vai·rava<207>a inviting ç
him to the sacrifice. The second part contains some rituals like giving ç
bali (sacrificial offering).
This part of the Veda should never be imparted to anyone who is forgetful ç
and callous.
@S10N = Anuv<193>ka 32 (3 ka<207><195>ik<193>s)
@SPACE = 
One who wants to perform the °ru<207>a-ketuka sacrifice should observe ç
certain rules and austerities for one year or at least two months.
He has to bathe three times a day. He should beg for food and eat ç
only once in the day. He has to offer sticks of audumbara wood (Ficus ç
racemosa) in the homa with mantras addressed to eleven deities such ç
as Agni, V<193>yu, S<220>rya, Brahm<193> and others with the syllable ç
sv<193>h<193>. Homa should be offered to the <216><218>is known as ç
Aru<207>as.
Sv<193>dhy<193>ya or Vedic studies should be kept up in the forest.
One who observes all these, becomes a tapasv<200> (sage) and a pu<207>ya ç
(auspicious person).
@SPACE = 
@NT = °yu<218>yas<220>kta
@N1 = (`the hymn [that bestows] longevity')
The desire to live long is but natural to every human being. Some ç
of the Hindureligious works have prescribed theperformance of a ç
havana or homa withappropriate Vedic mantras, aimed at increasing ç
the duration of life. One such is found in the Bodh<193>yana-g<216>hyas<220>tras ç
(3.7). The mantras given there go by the name °yu<218>yas<220>kta. ç
It is also sometimes, called the Gh<216>tas<220>kta since gh<216>ta ç
or ghee (clarified butter) is used as oblation with every mantra.
@SPACE = 
Though the mantras are obviously of Vedic origin, the source has not ç
been traced.
@SPACE = 
The S<220>kta has nine mantras. At the time of offering ghee they ç
are uttered, adding the well-known word `sv<193>h<193>' at the end.
A brief summary of the hymn may now be attempted here:
1. May the Supreme Brahman, who, in the form of <185>iva, the wearer ç
of elephant skin and the wielder of the bow Pin<193>ka, who nipped ç
off a head of Brahm<193> (the creator), who is also known as ®·<193>na ç
(the ruler), give us long life! To him we offer this oblation of ghee!
2. May the brilliantly shining Sun, with hot rays, who rose from the ç
middle of the ocean, may he destroy our terrible bonds of death and ç
accept our offering of ghee to increase the duration of our life.
3. Brahman the Light, deposited the watery embryo in the womb of the ç
five elements. It is brilliantly shining. It is adorable. May we make ç
it grow by offering oblations of ghee, so that the duration of our ç
life increases.
4. Lak<218>m<200> the goddess of wealth, is full of vitality. She ç
is the Mother Earth. She is also called <186>a<218><219>h<200> and ç
Indrasen<193>. She, the best deity, as knowledge, reminds us of Brahman. ç
Let us satiate her, in this yaj<210>a or sacrifice by offering oblations ç
of ghee.
5. May these multitudes of goddesses, who are the daughters of Dak<218>a-praj<193>pati, ç
who are sisters, who are responsible for the entire creation, who, ç
with their special forms, are pervading the world, along with their ç
husbands and offsprings, may they accept our oblations of ghee and ç
increase our life-span.
6.<+>There are hosts of ancient divine beings. They are capable of ç
cutting away the lives of living beings. May they destroy our powerful ç
enemies! We offer many oblations of ghee to them so that they do not ç
harm or destroy our offspring as also our heroes.
7.<+>He who was the sole cause of creating the world in the beginning, ç
he from whom the protector (Indra) of this world emerged, he to whom ç
this world will return at the time of dissolution, may he accept our ç
offerings of ghee to increase our life-span.
8.<+>To increase our longevity and feel eternally happy let us offer ç
oblations of ghee to the following deities: Vasus (8), Rudras (11), ç
°dityas (12), Maruts (21), S<193>dhy<193>s, <184>bhus, Yak<218>as, ç
Gandharvas, Pit<216>s, Vi·vedevas (10), Bh<216>gus, Sarpas (Serpents) ç
and A<209>girasas.
9.<+>O Vi<218><207>u, who is our ultimate abode, who forgives all our ç
misdeeds, please give us happiness! Your votaries offer to you a series ç
of sweet oblations without any break and happily.
@END = 
