@NID = Saptak<193><207><195>a R<193>m<193>ya<207>a of Sarala D<193>s ç
(in Oriya), the R<193>m<193>ya<207>a of M<193>dhava Kandali (in ç
Assamese), the Torave R<193>m<193>ya<207>a of Narahari (in Kannada) ç
are some of the more  well-known  R<193>m<193>ya<207>as  in  the ç
vernaculars.
@SB = 12.	R<193>m<193>ya<207>as outside India
The story of R<193>ma, either in its original form as depicted by ç
V<193>lm<200>ki or in a metamorphosed form, has travelled widely outside ç
India, to Tibet and Eastern Turkestan, to South East Asian countries, ç
Japan and even Mongolia. The following list of works†by no means exhaustive† ç
gives an idea of this movement:
@Z_TBL_BEG = COLUMNS(2), DIMENSION(IN), COLWIDTHS(E1,.8333), ABOVE(.0833), ç
VGUTTER(.0278), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT
R<193>m<193>ya<207>a Kakawin, (Javanese)
Hikayat Seri R<193>ma, (Malaysian)
R<193>makien, (Thai)
Pha Lak Pha Lam and<R>ç
<+><+><+><+>Khvay Thuaraphi, (Laos)
Hobutsushu, (Japanese)
R<193>m<193>·vamedha, (Nepali)
J<193>nak<200>hara<207>a, (Sinhalese)
@Z_TBL_END = 
@SB = 13.	Conclusion
If the worth of a literary composition has to be judged by the effect ç
it has had on a whole generation, the R<193>m<193>ya<207>a of °dikavi ç
V<193>lm<200>ki stands out as supreme since it has influenced and ç
is continuing to do so even now, generation after generation. Its ç
tremendous impact on our religion, social values, literature, music, ç
drama, dance, painting and sculpture†in fact, on all aspects of ç
our life†is very palpable.
It has given us an ideal man who stood for satya and dharma come what ç
may. It has given us an ideal woman, the paragon of feminine grace ç
and virtues. It has shown us an ideal family system where everyone ç
thought of the welfare of everyone else first. It has given us the ç
models of ideal brothers, ideal friends and ideal servants who spared ç
no effort to bring comfort to the loved ones. It has put before us ç
an ideal State. In other words, it has placed before us enough ideas ç
and ideals to inspire us, to rise from the human level to divine heights. ç
If this spirit is imbibed, a study of this scripture will be immensely ç
profitable.
@SPACE = 
@NT = R<193>me·varam
@SPACE = 
Pilgrimage to holy places is an integral part of Hinduism in practice. ç
A devout Hindu undertakes the pilgrimage not only because it is a ç
commandment of the scriptures, but also to purify himself and earn ç
pu<207>ya (religious merit).
R<193>me·varam has been one of the four most important pilgrim centres†the ç
other three being Badar<200>n<193>tha, Dv<193>rak<193> and Pur<200> ç
or Jagann<193>tha Pur<200>†as also one of the twelve jyotirli<209>gas ç
(See <MS>JYOTIRLI<177>GAS.<D>) which every Hindu used to aspire after ç
visiting, at least once in his lifetime.
The place gets its importance solely due to the legend that <185>r<200> ç
R<193>ma, while returning from La<209>k<193>, along with S<200>t<193> ç
and Lak<218>ma<207>a, established a <185>ivali<209>ga here and personally ç
worshipped it. (See <MS>R°MALI<177>GA<D> for details.)
The town of R<193>me·varam is situated on a small island which is ç
in the shape of a ·a<209>kha (conch), 55 kms. (34 miles) by 12 kms. ç
(7 1/2 miles), between the Palk Strait and the Gulf of Mannar. It ç
is connected with the main land (the small town of Ma<207><195>apam) ç
by a railway and a road bridge, one kilometer long.
The major attraction of this place is the famous temple of R<193>man<193>tha ç
(or R<193>man<193>thasv<193>min), the <185>iva temple founded by <185>r<200> ç
R<193>ma himself.
The present structure, which is of massive proportions, has taken ç
several centuries to take this shape. Even a king of Sri Lanka, apart ç
from the local kings, is said to have contributed to its growth and ç
development.
The main temple, situated at a distance of 200 metres (660 feet) from ç
the sea covers an area of about six hectares (15 acres).
The speciality of this temple is its huge outermost corridor, rectangular ç
in shape. Its total length is 1220 metres (3700 feet), the width of ç
the path being 5.7 metres (19 feet) and the average inner height 9 ç
metres (30 feet).
There are about 4000 pillars, each 3.7 metres (12 feet) high. All ç
are located on platforms 1.5 metres (5 feet) in height.
Images and motifs are in the Dravidian  style  and  are  extremely ç
beautiful.
The stone slabs used for the roof are 13 metres (42 feet) in length!
Out of the four gopurams (towers), the eastern one rises to a height ç
of 42 metres (138 feet) and the western one, to 26 metres (85 feet). ç
Both are embellished with miniature figures. The other two gopurams ç
are incomplete.
As one enters the temple from the main entrance in the east one comes ç
across a huge Nandi (the bull-mount of <185>iva).
@SPACE1 = 
The principal sanctum contains the main li<209>ga known as R<193>man<193>tha ç
(Lord of R<193>ma). This is supposed to have been prepared by S<200>t<193> ç
herself.
On its left is the shrine of P<193>rvat<200> (known as Parvatavardhin<200>).
Near the main shrine are also located two subsidiary shrines dedicated ç
to Vi·vali<209>ga (the li<209>ga brought by Hanum<193>n) and Vi·<193>l<193>k<218><200> ç
(an aspect of P<193>rvat<200>).
Behind the R<193>man<193>tha shrine is another small shrine dedicated ç
to Vi<218><207>u, known as Setum<193>dhava.
In the campus, there are 24 t<200>rthas (holy  tanks)  where  the  pilgrims  are ç
expected to bathe, before visiting the main shrine. The first one, ç
as we enter from the western entrance, is the M<193>dhava-t<200>rtha ç
which looks like a small lake. The Setum<193>dhava temple is by its ç
side. Most of the other t<200>rthas are like small wells from which ç
water has to be drawn, for bathing.
Each of these t<200>rthas is said to possess some special power to ç
destroy sins or bestow extraordinary benefits here or hereafter.
About 200 metres (650 feet) to the east of the temple, the sea is ç
called Agnit<200>rtha where the pilgrims bathe before entering the ç
main temple.
@SPACE1 = 
The footprints of <185>r<200> R<193>ma are enshrined in a small shrine ç
called Gandha-m<193>dana on a hillock, about 2.5 kms. (1.5 miles) ç
to the west of the main temple.
The Koda<207><195>ar<193>ma temple, situated at a distance of 8 kms. ç
(5 miles) from R<193>me·varam towards Dhanu<218>ko<219>i, contains ç
the images of R<193>ma, S<200>t<193>, Lak<218>ma<207>a, Hanum<193>n ç
and Vibh<200><218>a<207>a. This is said to be the place where Vibh<200><218>a<207>a ç
surrendered to R<193>ma.
Dhanu<218>ko<219>i situated at a distance of 20 kms. (12 miles) to ç
the southwest of R<193>me·varam is another important pilgrim centre. ç
This is the place where <185>r<200> R<193>ma, using his dhanus or ç
bow partly destroyed the bridge he had got built by the monkey army, ç
at the request of Vibh<200><218>a<207>a who did not want his enemies ç
to invade La<209>k<193> in future!
It is actually the confluence of the two seas, the Bay of Bengal and ç
the Indian Ocean.
The pilgrims used to perform ·r<193>ddhas  (obsequial  ceremonies)  here. ç
During the cyclone of <MS>A.<|>D.<D> 1964, much of this place was devastated.
A few of the other holy places near R<193>me·varam†all connected with ç
<185>r<200> R<193>ma†are:
@NOX = a)
@NOK = Darbha·ayanam  where  <185>r<200>  R<193>ma observed penance ç
to please god Varu<207>a.
@NOX = b)
@NOK = °di-jagann<193>tha temple, which the king Da·aratha, along ç
with his wives, visited and prayed for worthy sons.
@NOX = c)
@NOK = Dev<200> Pattanam on the sea-coast, containing nine stone pillars ç
representing the nine planets which <185>r<200> R<193>ma worshipped ç
for success in his mission.
@NOX = d)
@NOK = Ja<219><193>t<200>rtha where <185>r<200> R<193>ma washed his ç
hair to get rid of the sin he might have incurred in the battle at ç
La<209>k<193>.
@SPACE = 
The chief festivals celebrated at the R<193>man<193>tha temple are: ç
Mah<193>·ivar<193>tri (during February-March); R<193>mali<209>ga-prati<218><219>h<193> ç
(the day of establishing the li<209>ga by <185>r<200> R<193>ma, usually ç
for three days in June); and, the Tirukaly<193><207>am festival (the ç
day of marriage of P<193>rvat<200> and <185>iva) in July, lasting ç
for seventeen days.
An important, or even unique feature of this temple is its very rich ç
array of diamond and golden jewellery accumulated over the centuries, ç
due to the munificent offerings of the devotees.
In the olden days devout Hindus always cherished a strong desire to ç
visit K<193>·<200>, bring the Ga<209>g<193> water from there, and ç
bathe the <185>ivalil<209>ga at R<193>me·varam with it.
@NT = R<193>mottarat<193>pan<200>ya Upani<218>ad
This Upani<218>ad is a continuation of the P<220>rvat<193>pan<200>ya ç
Upani<218>ad. Here, R<193>ma is  described  as  nirvi·e<218>a  Brahman ç
(Brahman without attributes), whereas in the former he is described ç
as savi·e<218>a (with attributes) to facilitate meditation by devotees.
The whole text which is in the form of a dialogue between the sage ç
Y<193>j<210>a- valkya and some sages like B<216>haspati, Bharadv<193>ja ç
and Atri, contains 121 verses, including passages in prose, spread ç
over five kha<207><195>as or chapters.
The first kha<207><195>a with three passages, describes the importance ç
of Kuruk<218>etra and Avimukta (same as K<193>·<200> or V<193>r<193><207>as<200>), ç
their sacredness and their identity with the space in between the ç
eyebrows inside us.
The belief that <185>iva utters the t<193>raka-mantra (``R<193>ma'') ç
into the ears of the dying persons is alluded to.
The second kha<207><195>a with 19 verses and prose sections, deals ç
with the power of the R<193>ma-<218>a<195>ak<218>ara-mantra (= r<193><221> ç
r<193>m<193>ya nama<199>) as t<193>raka or endowed with liberatingpower ç
and is compared with O<209>k<193>ra or Pra<207>ava. That a s<193>dhaka ç
who repeats it daily is freed from all sins, is also stated.
There is also an interesting description of the Pra<207>ava as representing ç
R<193>ma, Lak<218>ma<207>a, Bharata, <185>atrughna as also S<200>t<193>.
Seven mantras (1 to 7) of the M<193><207><195><220>kya Upani<218>ad ç
find a place in this section.
The third kha<207><195>a (16 passages) starts by stating that the ç
°tman who is infinite bliss is realised by meditating on it in the ç
space between the eyebrows, above the nose.
It then describes how <185>iva performed austerities like japa (repetition ç
of R<193>ma's name), arcana (worship) and homa (oblations into a duly ç
consecrated fire) to please R<193>ma and how R<193>ma appeared before ç
him and granted him his desire that all those who die (including animals ç
or even worms) on the Ma<207>ikar<207>ik<193>-gh<193><219> on the ç
bank of the river Ga<209>g<193> in K<193>·<200> should get liberation. ç
For this, <185>iva had only to utter R<193>mamantra in the ear of ç
the dead being.
The fourth kha<207><195>a with 49 paras and verses, deals with a number ç
of mantras (each with 40 letters), partly resembling the G<193>yatr<200>mantra.
The fifth or the last kha<207><195>a with 34 verses and paras, describes ç
the greatness of the R<193>ma<218>a<195>ak<218>ara-mantra, eulogising ç
it in 24 verses as far superior to other mantras, of deities like ç
Ga<207>apati, <185>iva, Dev<200> and even Vi<218><207>u!
@NT = Ra<209>gan<193>tha
Ra<209>gan<193>tha, along with Varadar<193>ja of K<193><210>c<200>puram ç
and Ve<209>ka<219>e·a of Tirupati, is the most popular aspect of Vi<218><207>u ç
worshipped in South India. The well-known temple at <185>r<200>ra<209>gam ç
in Tamil Nadu is the very heart of the <185>r<200>vai<218><207>ava ç
cult. This temple†at least the original icon†is said to have been ç
born out of the ocean and given by <185>r<200> R<193>ma to Vibh<200><218>a<207>a. ç
While carrying it from Ayodhy<193> to La<209>k<193>, Vibh<200><218>a<207>a ç
placed it on the ground at the present site, in order to rest a while. ç
Unfortunately for him (and fortunately for others!) it got firmly ç
fixed there!
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
The image is of the Yoga·ayana type (lying on the serpent-bed in Yoga) ç
with only two hands, the right hand apparently supporting the head ç
while the left rests on the serpent-bed.
The lotus with Brahm<193>, the °yudha-puru<218>as (the weapons in ç
human form), the demons Madhu and Kai<219>abha who were killed by ç
him, as also some sages like Bh<216>gu and M<193>rka<207><195>eya ç
are often depicted along with the Lord.
Similar Yoga·ayana images are foundin <185>r<200>ra<209>gapa<219>na ç
of Karnataka and Tiruvanantapuram of Kerala where it is known as Padman<193>bha ç
or Ananta·ayana.
@NT = R<193><207><200> R<193>sama<207>i
@N1 = (<MS>A.<|>D.<D> 1793-1861)
R<193><207><200> R<193>sama<207>i was the intrepid lady who prepared ç
the stage for the unfoldment of the wonderful drama of R<193>mak<216><218><207>a's ç
life.
Born in September 1793, to humble parents in the village Kon<193>, ç
she was married at the age of ten to R<193>jcandra, the younger son ç
of a very rich land-lord, residing at Calcutta. The already rich family ç
of R<193>jcandra became richer by the entry of the lucky girl. With ç
her abundant courage and commonsense, she was of great help to her ç
husband in managing his estates.
When R<193>jcandra died prematurely, the R<193><207><200> took over ç
the entire property herself and managed it very well with the assistance ç
of her able son-in-law, Mathur<193>-n<193>th Bi·v<193>s (<MS>A.<|>D.<D> ç
1817-1871).
On many occasions she gave a tough fight not only to the East India ç
Company which was ruling Bengal at that time, but also to other rich ç
landlords who were exploiting the poor.
It was she who built the temple campus at Dak<218>i<207>e·var after ç
being commanded to do so by the Mother K<193>l<200> herself.
Her close contact with R<193>mak<216><218><207>a convinced her of ç
his being an incarnation. His unique solution to the problem of the ç
broken image of R<193>dh<193>k<193>nta (K<216><218><207>a) made her ç
discover his true greatness.
She passed out of the earthly frame into eternity on the 19th February ç
1861 with the name of the Divine Mother on her lips.
@SPACE = 
@NT = Rantideva
@SPACE = 
Sacrificing oneself for the good of others has always been considered ç
as a great virtue in Hinduism. One of the greatest examples found ç
in the epics and the pur<193><207>as is that of the king Rantideva. ç
He was the son of Sa<209>k<216>ti and belonged to the Candrava<221>·a ç
(the lunar race). He had performed many y<193>gas or Vedic sacrifices.
He was once doing severe austerities in a forest along with his family. ç
As a part of this, he fasted for 48 days. On the 49th day he received ç
divine food, just enough for him and his family.
As the family was getting ready to partake of the food, a few hungry ç
guests came one after another. Rantideva gave away all the food, including ç
the meagre drinking water.
These guests who were actually theTrim<220>rtis (Brahm<193>, Vi<218><207>u ç
and <185>iva) appeared before him. Rantideva honoured them with devoted ç
obeisance but never asked for any boon! The gods then granted him ç
and his family highest spiritual wisdom (vide Bh<193>gavata 9.21).
According to the Mah<193>bh<193>rata (Dro<207>aparva 67), the ç
king Rantideva was very fond of feeding guests sumptuously and offering ç
them gifts liberally.
See also <MS>CARMAØVAT®.<D>
@NT = rasa
@N1 = (`that which is tasted')
One of the most extensively used words, it has 24 different meanings ç
and senses.
In general, it means the essence or core-part of anything.
In the dar·anas (Hindu philosophical systems) it stands for the subtle ç
element water (`rasatanm<193>tra').
In the °yurveda and allied health sciences, it stands for mercury.
In the culinary arts, it represents six different kinds of tastes: ç
sweet, sour, saltish, hot (as that of pepper or chillies), bitter ç
and astringent.
In poetics, it stands for the navarasas or nine kinds of sentiments ç
or emotions. They are: the amorous, the heroic, the wondrous, the ç
ridiculous, as also the sentiments of compassion, humour, fear, horror ç
and loathesomeness.
The Taittir<200>yopani<218>ad (2.7) calls Brahman as rasa.
@NT = R<193>sal<200>l<193>
The group-dance that K<216><218><207>a performed with the gop<200>s ç
of V<216>nd<193>vana is known as R<193>sakr<200><195><193> or R<193>sal<200>l<193>. ç
It has been described in detail in the Bh<193>gavata (10.29-33). ç
These five chapters are generally called R<193>sapa<210>c<193>dhy<193>y<200>.
This important episode has been described in the Vi<218><207>upur<193><207>a ç
(5.13,14-62) and the Hariva<221>·a (Vi<218><207>uparva 20.18-35) ç
also, though more briefly.
K<216><218><207>a started playing some tantalising tunes on his flute ç
one night during autumn, sitting on the bank of the river Yamun<193>. ç
The music was so enchanting that all the gop<200>s of V<216>nd<193>vana ç
were irresistibly drawn to him. They hurried to him and gathered round ç
him.
As if he did not know why they had come, K<216><218><207>a nonchalantly ç
advised them to return to their homes, to which they refused.
Understanding their single-minded devotion and desire, K<216><218><207>a ç
played amorous sports with them for some time. When the gop<200>s ç
became inebriated with pride† because they had the great K<216><218><207>a ç
himself for their lover†he suddenly disappeared from their midst by ç
his inscrutable m<193>y<193> power.
The gop<200>s were now smitten with intense remorse and started madly ç
loitering in the forest region there in search of him. When they failed ç
to trace him, they assembled in one place and started praying, pouring ç
out the anguish that was burning their whole being. This part of the ç
Bh<193>gavata (10-31) is well-known as the Gop<200>g<200>t<193> ç
or Gopik<193>g<200>t<193>. It is full of the pathos of the intense ç
pain of separation of the beloved from the lover.
Moved by their piteous cries K<216><218>na reappeared in their midst ç
and danced the R<193>sal<200>l<193> (dance), multiplying himself to ç
be with each of the gop<200>s. Thus spending the whole night happily ç
with him, they, most unwillingly, returned home at daybreak.
Even though the gop<200>s had spent the whole night with K<216><218><207>a, ç
their husbands found them†due to his m<193>y<193>†to be with them ç
all the while! (vide Bh<193>gavata 10.33.38).
See also <MS>BH°GAVATA<D>, <MS>GOP®G®T°<D> and <MS>K<184><186>ØA.<D>
@NT = R<193>sama<207>i
See <MS>R°Ø® R°SAMAØI.<D>
@NT = Ras<193>tala
@N1 = (`That which is below the earth')
The Mah<193>bh<193>rata as also some of the pur<193><207>as contain ç
interesting descriptions of this universe. If there are six lokas ç
or worlds above the earth ending in Satyaloka or Brahmaloka, there ç
are seven, below the earth also. `P<193>t<193>la' is the general name ç
given to these worlds.
The seven p<193>t<193>las are: Atala, Vitala, Nitala, Gabhastim<193>n, ç
Mah<193>tala, Sutala and P<193>t<193>la (Vi<218><207>upur<193><207>a ç
2.5.2 and 3).
According to the Bh<193>gavata (5.24.5) Ras<193>tala is the fourth ç
in the series.
The Garu<195>apur<193><207>a (15.56,57) lists Ras<193>tala as the ç
sixth of these nether worlds.
If the various descriptions of Ras<193>tala given in these works are ç
summarised, the following picture of this world emerges: Ras<193>tala ç
is the fourth or the sixth of the p<193>t<193>las and the abode of ç
Ananta or <185>e<218>an<193>ga, the thousand-hooded serpent on whom ç
Mah<193>vi<218><207>u is reclining.
Mah<193>vi<218><207>u in his Var<193>ha (Boar) incarnation killed ç
the demons by entering the Ras<193>tala-loka. It was also here that ç
he killed the demons Madhu and Kai<219>abha, taking the Hayagr<200>va ç
form (with a horse's head on a human frame).
Surabhi or K<193>madhenu, the celestial cow lives here with her offsprings. ç
There is an ocean of milk here.
This world is more comfortable to live in than even N<193>galoka (world ç
of serpents) or Svarga (heaven)!
@NT = Rasavidy<193>
@N1 = (`science of chemicals,'<R>ç
`alchemy')
Certain desires like making the physical body not only strong and ç
healthy but also live eternally, seem to be inherent in the human ç
psyche. So also the desire (or greed?) to convert base metals into ç
gold.
Some sections of the scientists and doctors of ancient and medieval ç
India seem to have believed that mercury, sulphur and mica possessed ç
certain extraordinary qualities which were only to rediscovered. This ç
gradually developed into a new branch of science called Rasavidy<193>.
Gorakhn<193>th (11th century <MS>A.<|>D.<D>), N<193>g<193>rjuna (6th ç
century <MS>A.<|>D.<D>) and a few others were considered to be experts ç
in this field of science.
A branch of Hindu philosophy, known as Rase·vara Dar·ana has been ç
built round this doctrine. It propagates the theory that rasa (mercury) ç
and abhraka (mica) produced from the divine bodies of <185>iva and ç
P<193>rvat<200>, when mixed properly, can destroy death and poverty.
Govinda Bhagavatp<193>da (the guru of <185>a<209>kara) has been cited ç
as one of its ancient teachers.
This Rase·vara Dar·ana is a minor school under <185>aivism.
@SPACE = 
@NT = Rase·vara Dar·ana
@SPACE1 = 
See <MS>RASAVIDY°.
@SPACE = 
@NT = Rashtriya Swayamsevak Sangh
@SPACE1 = 
This is a well-known socio-cultural organization of Modern India. ç
It is popularly known as the R.S.S. Started in <MS>A.<|>D.<D> 1925 ç
by Dr. Keshav Baliram Hedgewar (<MS>A.<|>D.<D> 1889-1940), it aims ç
at the creation of a non-political corps of volunteers totally dedicated ç
to the service of the motherland, India, fondly pictured as Bh<193>ratam<193>t<193>.
It has its headquarters at Nagpur in the Maharashtra State.
Though Dr. Hedgewar was a medical doctor, he devoted all his time ç
to building up the organization.
It was during the period of his successor, M. S. Golwalkar (<MS>A.<|>D.<D> ç
1906-1973)†more popularly known as Guruji† that the organization grew ç
to phenomenal proportions. A saintly figure with an impeccable life, ç
he was also instrumental in getting several other organizations started ç
and stabilised.
The ·<193>kh<193> (a small local branch) is the fundamental unit of ç
the organization with a standard pattern, routine and discipline. ç
Great attention is paid here to physical fitness, cultivation of patriotism ç
and high social values. It is specially impressed upon the members ç
to look upon the whole society as one family.
The  organization  has  undertaken several service activities. It ç
has totally dedicated itself to offer succour and helpto the country ç
during national emergencies.
@SPACE1 = 
In the social field, it has taken up several programmes aimed at bringing ç
about greater unity among the Hindus as follows: abolition of the ç
practice of untouchability; elimination of caste animosities and forging ç
unity among all the castes; teaching simple techniques of yoga; encourage ç
the learning of Sanskrit language; reconversion into Hinduism of those ç
who had left due to various reasons.
A monumental achievement of theR.S.S is the active assistance and ç
cooperation in the construction of the Vivek<193>nanda Temple on the ç
Rock†now well-known as the Vivek<193>nanda Rock† during the period ç
<MS>A.<|>D.<D> 1963-1970. It is situated in the sea at the southernmost ç
tip of India.
The organization is sustained by public contributions and contributions ç
by the swayamsevaks (members of the R.S.S.) during the Gurup<220>r<207>im<193> ç
day (full-moon day in the month of °<218><193><195>ha, generally in ç
July). This is called Gurudak<218>i<207><193> celebrations.
The <|>leaders<|> of <|>the R.S.S.<|> have inspired and guided several ç
other organizations and movements. Some of them are:Vishwa Hindu ç
Parishad (See <MS>VISHWA HINDU PARISHAD<D> for details.); Akhil Bharatiya ç
Vidyarthi Parishad (ABVP, the largest organization of students); Bharatiya ç
Mazdoor Sangh (BMS, the largest labour movement in India); Vidya Bharati ç
(which runs schools all over India); Vanavasi Kalyan Ashram (serving ç
people in remote areas like forests and mountains); SewaBharati (conducting ç
several service projects).
During its existence of over eighty years, the R.S.S. has faced stiff ç
opposition as also incarceration at the hands of some sections of ç
the society and the governments of the day. However it has successfully ç
withstood the fiery ordeals and is growing steadily in strength.
@NT = r<193>·i
See <MS>JYAUTI<186>A.<D>
@NT = ratha
@N1 = (`that which delights,' `chariot')
The ratha or the chariot†a carriage with two wheels and drawn by two ç
or more horses†was quite common even during the times of the <184>gveda ç
(vide 1.20.3; 3.15.5; 6.75 and so on). It was usedwidely not only ç
as a means of transportation but also in wars. Fabricating rathas ç
was a highly specialised job assigned to the rathak<193>ras. The Vi<218><207>u-dharmottarapur<193><207>a ç
gives many details regarding the manufacture of rathas. Descriptions ç
of the various kinds of rathas of the different deities, symbolical ç
interpretations based on them, interesting accounts of expert s<193>rathis ç
or charioteers like Aru<207>a and M<193>tali are often found in the ç
epics and the pur<193><207>as.
Works like the M<193>nas<193>ra, the <185>ilparatn<193>kara and ç
the Rudrav<193>stu give details about their design and building ç
as also the materials suitable for making them. Different kinds of ç
rathas such as pu<218>paratha, vim<193>naratha, somyaratha and gandharvaratha ç
are also mentioned.
The number of wheels also varies† from two to ten†depending on the ç
use for which they are made.
They were normally drawn by horses, especially<|>in wars or chariot-sports ç
(including races). For transporting goods, even bullocks were harnessed.
Nowadays, the word `ratha' is almost exclusively used to indicate ç
the wooden chariots used in most of the temples, which are taken out ç
on festive occasions. Such occasions are called Rathotsavas. They ç
are annual events, the days chosen being the day of consecration of ç
the temple or of the installation of the main icon. These rathas are ç
generally prepared out of the wood called tini·a (Dalbergia onjeinensis). ç
They are often made artistically with lovely carvings.
@SPACE1 = 
There are elaborate rituals connected with the rathotsava, such as ç
worshipping the ratha first, placing the deity on it, drawing it along ç
the route fixed for its movement, taking the deity out at the end, ç
and conducting it back to its shed.
The ratha symbolises the mount Meru, the wheels stand for the sun ç
and moon, the images of the four horses carved on wood, for the four ç
Vedas, and, the charioteer represents the creator Brahm<193>.
The word ratha may also stand for a variety of temple architecture ç
as seen in the rathas of Mah<193>balipuram. (See <MS>MAH°BALIPURAM<D> ç
for details.)
@NT = rathak<193>ra
@N1 = (`one who builds a ratha<R>ç
[chariot]')
A rathak<193>ra is actually a carpenter who has specialised in the ç
art of preparing rathas or chariots. He has been mentioned as ta<218><219><193> ç
or tva<218><219><193> even in the <184>gveda (vide 1.61.4; 8.102.8).
Since his services were essential in the performance of Vedic sacrifices, ç
he was given the status almost equal to that of a dvija (the twice-born, ç
the first three castes). Hence, he could undergo the upanayana rite ç
and even establish the Vedic fires.
Apart from the making of chariots, he could also live by taming horses, ç
driving carts and building houses.
Gradually his status declined to that of a ·<220>dra, thanks to the ç
rigidity of the caste system of later periods.
@NT = Rathantaras<193>ma
See <MS>S°MAN.
@NT = Rathasaptam<200>
Those  desirous  of  freedom  from diseases and a robust health are ç
advised to worship Bh<193>skara or S<220>rya, the sun. Rathasaptam<200> ç
which falls on M<193>gha ·ukla saptam<200> (in February) is a vrata ç
dedicated to the worship of the sun, to get that or fulfilment of ç
any other desire. It consists of worship of the sun seated in a chariot† ç
usually  in  image†with  saffron  and flowers, fasting for the whole ç
day, keeping vigil the whole night with devotional songs and music. ç
After bath next morning, gifts should be made to the guru (preceptor) ç
and others.
Rathasaptam<200>†also called Acala- saptam<200>†is the day on which ç
Vaivasvata-manvantara started, on which the sun was born and also ç
the day on which he started going northward (uttar<193>ya<207>a).
@SPACE = 
@NT = Rathay<193>tr<193>
@N1 = (`moving the chariot')
@SPACE = 
The Rathay<193>tr<193> festival (°<218><193><195>ha ·ukla dvit<200>y<193>) ç
of Lord Jagann<193>tha at Pur<200> (in Orissa) is a world-renowned ç
event drawing lakhs of people every year.
Pur<200> or Jagann<193>thapur<200> is one of the four `dh<193>mas' ç
(important places of pilgrimage situated in the four cardinal directions ç
of India), the other three being Badar<200> in the north (Uttar Pradesh), ç
Dv<193>rak<193> in the west (Gujarat) and R<193>me·varam in the south ç
(Tamil Nadu). Known as the `Puru<218>ottama-k<218>etra' in the ancient ç
days, the present temple of Lord Jagann<193>tha is said to have been ç
built by the king Indra- dyumna. The temple with the wooden images ç
of <185>r<200> K<216><218><207>a (Jagann<193>tha), Bala-bhadra (Balar<193>ma, ç
K<216><218><207>a's elder brother) and Subhadr<193> (K<216><218><207>a's ç
younger sister) must have been in existence for over 1300 years. The ç
wooden images are replaced periodically with new ones, the `relics' ç
inside the old ones being transferred to the new ones, before the ç
former are disposed of according to the directions given in the concerned ç
scriptures.
The Pur<200> Jagann<193>tha temple is, perhaps, the only temple in ç
India where the m<220>lavigrahas (original icons) themselves are shifted ç
on to the rathas (chariots) for the rathotsava (chariot festival). ç
In all other temples, there are separate icons, called `utsavam<220>rtis', ç
which are used for the rathotsava.
In the Rathay<193>tr<193> festival three rathas are used: One for ç
Jagann<193>tha, called Nandigho<218>a, 13.5 metres (45 ft.) in height, ç
with 16 wheels of 2.1 metres (7ft.) diameter; the second for Balar<193>ma, ç
called T<193>ladhvaja, 13.2 metres (44 ft.) in heightwith 14 wheels; ç
and the third for Subhadr<193>, called Dev<200>ratha or Darpa-dalana, ç
12.9 metres (43 ft.) in height and with 12 wheels.
After the ceremonial installation of the deities inside the chariots, ç
it is the privilege of the king of Pur<200> (a descendant of Anantavarma ç
[<MS>A.<|>D.<D> 1075-1150<W1%10>]<D%0>) to sweep the chariot of the ç
Lord and pay his homage. Then lakhs of devotees join in the pulling ç
by big ropes, with shouts of `Jagann<193>thak<200> jay,' `Balabhadrak<200> ç
jay' and Subhadr<193>k<200> jay'. The procession stops at Gu<207><195><200>c<193>b<193>r<200>, ç
the garden house of the deities. After a stay of seven days, the images ç
are brought back to the main temple on the da·am<200> day.
The  Rathay<193>tr<193>  (travel  by  the chariot) may be a ritual ç
re-enactment of the journey of Subhadr<193>, escorted by K<216><218><207>a ç
and Balar<193>ma, to Dv<193>rak<193>. As per the mythological lore, ç
Subhadr<193> expressed a desire to see the newly constructed city ç
of Dv<193>rak<193>; and was accordingly taken there by her brothers.
@NT = rathotsava
@N1 = (`festival of the [temple]<R>ç
chariot')
The biggest festival organised in anytemple is called `brahmotsava'. ç
It is generally spread over a number of days. The rathotsava is an ç
important part of this festival and is usually held two days before ç
the conclusion of all the ceremonies.
The ratha (temple-car or chariot) is a replica of the temple. It is ç
richly decorated along with the utsavam<220>rti (processional image) ç
and taken round the important streets of the town. It is halted in ç
certain specified places so that the common people can offer their ç
worship almost at their door-step.
The ratha is drawn by the devotees, no distinction being made of caste ç
or creed.
Of course, there are a number of religious rites connected with the ç
rathotsava, which should be observed scrupulously.
@NT = Rati
@N1 = (`[one who gives] enjoyment or<R>ç
pleasure')
One of the specialities or peculiarities of Hinduism is that every ç
aspect of life† good or not-so-good†is deified or has a presiding ç
deity or spirit. If k<193>ma or desire in general and sexual love ç
in particular has been deified as K<193>madeva (also known as Ana<209>ga, ç
Madana and Manmatha), his feminine counterpart or consort is Rati.
The pur<193><207>as describe her as one of the daughters of Dak<218>a-praj<193>pati ç
and married to K<193>ma, son of another Praj<193>pati, called Dharma.
Pr<200>ti is her co-wife.
In sculptures and paintings she isshown in the company of K<193>ma ç
or Manmatha.
When sculptured independently sheis shown as exceedingly beautiful, ç
bedecked with several jewels and ornaments and in a dancing pose.
She may also be shown as riding a parrot, holding in her two hands ç
the sugarcane stalk as the bow and five kinds of flower-darts.
Other objects shown in her hands are: v<200><207><193> (lute), da<207><195>a ç
(staff) and ak<218>as<220>tra (rosary).
According to the Bh<193>gavata (10.55) and the Vi<218><207>upur<193><207>a ç
(5.27) she was reborn as M<193>y<193>vat<200>, a wife of the demon ç
<185>ambara, but was reunited with her husband Manmatha, now reborn ç
as Pradyumna, the son of K<216><218><207>a and Rukmi<207><200>.
See also <MS>K°MA<D> and <MS>MANMATHA.<D>
@NT = ratnap<193>tra
@N1 = (`bowl of precious stones')
The many deities described in the Hindu mythological works have provided ç
Hindu Iconography with plenty of material to describe and to work ç
upon.
Apart from their dresses and ornaments, these deities hold several ç
things in their hands. One of these is the ratna- p<193>tra. It is ç
actually a golden bowl (p<193>tra) studded with ratnas or precious ç
stones.
The deities in whose hands this is shown are: Annap<220>r<207><193>, ç
Kubera, and Ga<207>e·a.
Annap<220>r<207><193>'s bowl is filled with food whereas it is full ç
of jewels in the hands of the other two deities.
@NT = Ratnaprabh<193>
The Brahmas<220>tras is the main and basic treatise on Ved<193>nta ç
philosophy. It is based entirely on the major Upani<218>ads.
Being in the form of terse s<220>tras or laconic aphorisms, it cannot ç
be understood withoutthe help of a bh<193><218>ya or a commentary. ç
All the three <193>c<193>ryas (teachers) of the major systems of Ved<193>nta ç
have written bh<193><218>yas on it, the one by <185>a<209>kara (<MS>A.<|>D.<D> ç
788-820) being the earliest.
On <185>a<209>kara's Brahmas<220>trabh<193><218>ya three subcommentaries, ç
known generally as <219><200>k<193>s, are famous. They are Bh<193>mat<200> ç
of V<193>caspati (9th century <MS>A.<|>D.<D>), Ny<193>ya-nir<207>aya ç
of °nandagiri (<MS>A.<|>D.<D> 1260) and Ratnaprabh<193> of R<193>m<193>nanda ç
(17th century <MS>A.<|>D.<D>).
The Ratnaprabh<193> is the simplest of the three and often contains ç
the essence of the other two <219><200>k<193>s.
It is also called, sometimes, Bh<193><218>ya-ratnaprabh<193>. If ç
the bh<193><218>ya of <185>a<209>kara is the ratna or diamond, this ç
<219><200>k<193> is its prabh<193> or light, since it manifests that ç
`light' through its explanations.
See also <MS>BRAHMAS<188>TRAS.<D>
@NT = R<193>tri
@N1 = (`One who gives [rest or happiness]')
The benevolent goddess ruling over night, she is the sister of U<218>as ç
(dawn). She is of <184>gvedic antiquity. She is described as wearing ç
black robes studded with glittering stars.
She is invoked for warding off the threat of darkness (like robbers, ç
reptiles, wild animals and wicked spirits).
See also <MS>R°TRIS<188>KTA.<D>
@NT = R<193>tris<220>kta
@N1 = (`the hymn addressed to the [goddess] R<193>tri')
S<220>ktas are certain special groups of Vedic mantras. They may be ç
used either for certain rites and rituals or as prayer.
The R<193>tris<220>kta of the <184>gveda (10.127.1-8) is one such ç
well-known piece.
Though it has only eight <216>ks or mantras, its use in rituals often ç
includes 13 more verses called khila or pari·i<218><219>a (additional) ç
mantras which too are considered as of hoary antiquity. Then comes ç
another group of 12 verses which are the phala·ruti (eulogy of the ç
hymn itself that describes the various benefits one gets by reciting ç
or using it).
A brief summary of this s<220>kta may now be given:
As she arrives, R<193>tr<200> (the presiding goddess of the night) ç
sees or observes every place through her beautiful and bright eyes ç
(= the stars). She, the immortal goddess, has filled the whole earth ç
and the sky with darkness, enlivening it however, with the light of ç
her stars. After some time she departs, making way for her sister, ç
U<218>as (the dawn). Darkness too is withdrawn.
Even as the birds rest in their nests in the night, we too will safely ç
spend the night in our houses. May she, the goddess of night, be pleased ç
with us! Is it not a fact that as soon as night approaches, all people ç
return to their homes, the cows and the horses to their sheds and ç
the birds to their nests?
O goddess of the night, please accept this hymn of praise, like an ç
oblation of ghee given in a sacrifice!
@SPACE = 
The 13 verses of the khila section that follow, describe her form ç
and beauty. They also contain prayers for protection against the dangers ç
of wars, of enemies, of fire, of robbers and of the evil effects of ç
malefic planets.
The 12 verses that come next describe how to worship the goddess using ç
these verses†by reciting them and offering milk and sandal-paste.
The results of this recitation and worship are also given. Some of ç
them are: attaining fame in the three worlds; being blessed with a ç
worthy son and wealth; a blind person regaining eyesight; a person ç
suffering from diseases being cured of them; and, getting whatever ç
one desires.
This R<193>tris<220>kta is chanted as a part of the ceremonial recitation ç
of the famous Ca<207><195><200> or Durg<193>sapta·at<200> also.
@NT = Raudr<200>
@N1 = (`the terrible goddess')
An aspect of the goddess P<193>rvat<200>, she is the feminine counterpart ç
or consort of <185>iva as Rudra (= the Terrible). She is alsocalled ç
Caramamu<207><195><193>, C<193>mu<207><195><193>, Mah<193>m<193>y<193>, ç
Sarvabh<220>ta-mah<193>raudr<200> and K<193>lar<193>tr<200>.
The demon Durga, the son of Ruru, had obtained a boon that he could ç
never be killed by male beings. Unable to bear his atrocities, all ç
the gods approached Brahm<193>, the creator for succour. On his request ç
Raudr<200> killed Durga.
She is also described as one of the eight forms of Par<193>·akti (P<193>rvat<200> ç
as the Supreme Power) like V<193>m<193>, Jye<218><219>h<193>, K<193>l<200> ç
and so on. She is the personified aspect of fire element in creation.
Iconographical works picture her as black in complexion, clad in red ç
garments.
@NT = Raurava
See <MS>NARAKA.<D>
@NT = R<193>va<207>a
@N1 = (`one who [shook the worlds through his] roaring')
See <MS>R°M°YAØA.
@NT = <184>bhus
@N1 = (`those who shine brilliantly')
The <184>bhus are a class of gods often mentioned in the <184>gveda ç
(1.20; 1.161.6; 4.33.3; 4.34.1). Originally they were human beings, ç
raised later on to devatva or godhood because of their extraordinarily ç
good deeds.
Sudhanv<193> was a <216><218>i (sage) born in the lineage of the great ç
<216><218>i A<209>gir<193>. He had three sons: <184>bhu, Vibhu and ç
V<193>ja. (All the three came to be known as <184>bhus.) By performing ç
good deeds and helping the gods in heaven they became dear to these ç
gods. Being disciples of Tva<218><219><193> (the divine carpenter ç
or technician) they too had become experts in the technical field. ç
It was they who built a chariot for Indra and a camasa (vessel for ç
drinking the soma juice) for Agni. They also created by their mental ç
powers two excellent horses for Indra's chariot. They successfully ç
restored youth to their own parents. By following the path of truth, ç
they shone brilliantly and were endowed with tremendous powers to ç
achieve whatever they wanted. That is why they were raised to the ç
level of gods and were given a share in the offerings by Praj<193>pati ç
himself.
They receive the soma juice during the t<216>t<200>yasavana (third ç
pressing done in the evening) in the Somay<193>gas.
@NT = <216>c, <216>k
A mantra of the <184>gveda is known as a <216>c or <216>k. It is ç
generally defined as a stanza set to metrical norms and conveying ç
some definite meaning. P<193>das (lines) and m<193>tr<193>s (syllabic ç
instants) are the regulating principles.
@NT = <184>c<200>ka
<184>c<200>ka was a great <216><218>i (sage) endowed with special ç
powers. He was the son of Aurva and the grandson of Bh<216>gu, both ç
of whom were also well-known.
His wife was Satyavat<200>, the daughter of the king G<193>dhi.
Pleased with her devoted service, <184>c<200>ka once asked her to ç
pray for any boon she liked. She requested him that a son be born ç
to her and that her mother too should be blessed with a worthy son. ç
<184>c<200>kagave both of them sanctified caru (porridge) to be consumed, ç
along with some special instructions. The ladies however, made a mistake ç
and followed the instructions in the opposite order!
As a result, <184>c<200>ka informed them that Satyavat<200>'s son ç
would be a k<218>attriya whereas her mother would give birth to a ç
son who would ultimately become a br<193>hma<207>a.
@SPACE1 = 
However, on her pleading, he granted the boon that her son would be ç
a br<193>h- ma<207>a while the grandson would become a k<218>attriya.
Accordingly  her  son  Jamadagni remained a br<193>hma<207>a sage ç
and his son,Para·ur<193>ma, became a k<218>attriya by temperament ç
and actions.
@SPACE1 = 
G<193>dhi's son was Kau·ika who became Vi·v<193>mitra (a brahmar<218>i, ç
a great br<193>hma<207>a-sage)  by  practising  severe austerities.
@NT = <216>ddhi
@N1 = (`plenitude')
Anything that helps one to increase his power or greatness or influence ç
over others is a <216>ddhi.
Different works list the <216>ddhis in different ways. They may be ç
seven or eight in number.
The seven <216>ddhis are: buddhi (intellect), tapas (austerity), vikriy<193> ç
(change), au<218>adhi  (medicines  and  drugs),  rasa (essence, juice), ç
bala (strength) and ak<218><200><207>a (not declining). If k<218>iti ç
(land) is added, it becomes eight.
Each one of these is further sub- divided into eight aspects. The ç
<216>ddhis then come to a very large number. Many of these are extraordinary ç
psychic powers, often included under the term siddhi also.
<184>ddhi and Siddhi are sometimes described as the two wives of Ga<207>apati. ç
(See <MS>GAØAPATI<D> also.)
@NT = recaka
@N1 = (`exhalation')
See <MS>PR°Ø°Y°MA.<D>
@NT = Re<207>uk<193>
Re<207>uk<193> was the foster daughter of the king Prasenajit. He ç
had found her as a baby-girl lying on a lotus flower.
