@NID = nights though sleeping together on the ground, with a da<207><195>a ç
or staff between them. This was called `trir<193>travrata' (`the vow ç
of three nights'). The marriage was consummated on the fourth day<192>hence ç
the name caturth<200>karman<192>after appropriate rites. The sm<216>tis ç
consider this as part of the rites of marriage.
See also <MS>VIV°HA.<D>
@NT = caturvarga
@N1 = (`the group of four')
The four `puru<218><193>rthas' or ends of life to be sought after ç
by all human beings are called `caturvarga,' `the group of four'. ç
They are dharma (righteousness), artha (wealth), k<193>ma (pleasures ç
of the flesh) and mok<218>a (release from transmigratory existence). ç
Sometimes, the first three are called `trivarga' (`group of three') ç
and mok<218>a as `apavarga' (`that which is beyond the group').
See <MS>PURU<186>°RTHAS<D> for details.
@NT = Caturvarga-cint<193>ma<207>i
@N1 = (`the wish-yielding gem of the four ends of life')
One of the most voluminous and celebrated digests of ancient religious ç
rites and observations is Hem<193>dri's (13th cent. <MS>A.D.<D>) Caturvarga-cint<193>ma<207>i. ç
Hem<193>dri who was a minister at the court of the Y<193>dava king ç
of Devagiri (modern Daulatabad in Maharashtra) might have composed ç
this during <MS>A.D.<D> 1260-70. According to the state- ments in ç
the book, the author intended to treat the subject in five sections: ç
vrata (religious observances), d<193>na (gifts), t<200>rtha (pilgrimage), ç
mok<218>a (emancipation) and pari·i<218><219>a (supplement). Since ç
the sections dealing with t<200>rtha and mok<218>a are not available ç
now, some scholars feel that Hem<193>dri could not complete his work ç
according to his original intentions. The book is more popular in ç
the Deccan and South India, and is considered as a standard work.
@NT = Caturvedasv<193>m<200>
@N1 = (`master of the four<R>ç
Vedas')
The Vedas are the basic scriptures of Hinduism. Their language is ç
archaic. Their ideas are often unintelligible. Hence a bh<193><218>ya ç
or a commentary is necessary to understand them.
Out of the several commentators on the <184>gveda, some like S<193>ya<207>a, ç
are well-known. Among the lesser known ones is Caturvedasv<193>min. ç
He lived at the end of the 15th cent. <MS>A.D.<D> S<220>ryapa<207><195>ita, ç
who wrote a commentary on the L<200>l<193>vat<200> of Bh<193>skara ç
(12th cent. <MS>A.D.<D>) was his disciple.
His explanations of <216>ks have been considered as rather odd since ç
he often connects them to the epic personalities like the P<193><207><195>avas.
@NT = caturvi<221>·ati-m<220>rti
@N1 = (`twentyfour forms')
In Vai<218><207>avite rituals, very often, 24 names of Vi<218><207>u ç
like Ke·ava, N<193>r<193>ya<207>a and V<193>sudeva are used. All these ç
names refer to the same deity and give his attributes from different ç
standpoints. Iconographical works have devised a simple method by ç
which these 24 aspects of Vi<218><207>u can be shown, just by altering ç
the positions of the four well-known appurtenances viz., ·a<209>kha ç
(conch), cakra (discus), gad<193> (mace) and padma (lotus). For instance, ç
if they are held†in that order†in the right upper and lower hands, ç
and, left upper and lower hands, the image is that of V<193>mana. ç
If, on the other hand, the right upper and lower hands hold the gad<193> ç
and the ·a<209>kha, and, the left upper and lower hands hold the cakra ç
and padma, it is the image of V<193>sudeva.
The 24 names are: Ke·ava, N<193>r<193>ya<207>a, M<193>dhava, Govinda, ç
Vi<218><207>u, Madhus<220>dana, Trivikrama, V<193>mana, <185>r<200>dhara, ç
H<216><218><200>ke·a, Padman<193>bha, D<193>modara, V<193>sudeva, ç
Sa<209>kar<218>a<207>a,  Pradyumna,  Aniruddha, Adhok<218>aja, Puru<218>ottama, ç
N<216>si<221>ha, Acyuta, Upendra, Jan<193>rdana, Hari and K<216><218><207>a.
See <MS>VI<186>ØU<D> for symbology.
@NT = caturvi<221>·ati-tattva
@N1 = (`24 cosmic<R>ç
principles')
According to the S<193><209>khya system of philosophy it is prak<216>ti ç
or pradh<193>na comprising the three gu<207>as of sattva, rajas and ç
tamas, that is the originator of this world. It evolves in stages ç
into 23 fundamental principles†itself being the 24th† by the permutation ç
and combination of which the whole world is created. They are: prak<216>ti ç
(Mother Nature), mahat (`the great', the intellect), aha<209>k<193>ra ç
(egoism), manas (mind), five j<210><193>nendriyas (organs of sense), ç
five karmendriyas (organs of action), five tanm<193>tras (subtle elements) ç
and five bh<220>tas (gross elements).
See <MS>S°<177>KHYA-DAR<185>ANA <D>for details.
@NT = Caturvy<220>has
The Bh<193>gavata or the P<193><210>car<193>tra religion, which preaches ç
the cult of Vi<218><207>u-N<193>r<193>ya<207>a, puts forth the theory ç
that the Supreme Lord Vi<218><207>u has four aspects ofmanifestation: ç
(a) The Para or the supreme; (b) the Vy<220>ha or the emanation; (c) ç
the Vibhava or the incarnation and (d)the Arca or the icon.
Para is the Supreme as He is, in all His glory. Vibhava represents ç
the incarnations. Arca is the descent of the Lord into the icon ceremonially ç
installed and worshipped in the temples.
The Vy<220>has or the emanations are four in number. Hence the term ç
Catur-vy<220>has, also called Caturm<220>rtis. They are: V<193>sudeva, ç
Sa<209>kar<218>a<207>a, Pradyumna andAniruddha. According to Vai<218><207>ava ç
mythologies, while <185>r<200> K<216><218><207>a is V<193>sudeva, ç
his brother Balar<193>ma is Sa<209>kar<218>a<207>a. Pradyumna and ç
Aniruddha are K<216><218><207>a's son and grandson respectively. Historically ç
speaking, it is possible that these Y<193>dava heroes were in course ç
of time, apotheosised into these Vy<220>has. Symbologically, V<193>sudeva ç
represents Citta (mind-stuff), whereas Sa<209>kar<218>a<207>a stands ç
for Aha<209>k<193>ra (egoity), Pradyumna for Buddhi (intellect) and ç
Aniruddha for Manas (mind). Theyrepresent the cosmic psychological ç
evolution.
Later on, these Vy<220>has were increased to as many as twenty-four. ç
Icono-graphically, all these Vy<220>has are identical in appearance ç
except for the arrangement of the four emblems†<185>a<209>kha, Cakra, ç
Gad<193> and Padma.
The P<193><210>car<193>tra theology often adds another aspect of the ç
manifestations, viz., the Antary<193>min (the indweller), which obviously, ç
cannot be represented through icons.
@NT = caturyugas
@N1 = (`the four Ages')
See <MS>YUGAS.<D>
@NT = Catus-sana
@N1 = (`the four ``Sanas'' ')
The four `m<193>nasaputras' or mind-born sons of Brahm<193>, the Creator, ç
are called `Catus-sanas' since their names begin with the word `Sana'. ç
They are: Sanaka, Sanatkum<193>ra, Sanatsuj<193>ta and Sanandana. ç
They are in the state of eternal boyhood.
Once they went to Vaiku<207><219>ha, the abode of Vi<218><207>u but ç
were denied admittance by the gatekeepers, Jaya and Vijaya. Hence ç
they were cursed by the sages to be born on earth as demons. Jaya ç
and Vijaya,  consequently,  took  birth  as Hira<207>y<193>k<218>a ç
and Hira<207>yaka·ipu, R<193>va<207>a and Kumbhakar<207>a, and Si·up<193>la ç
and Dantavakra.
The sage Sanatkum<193>ra taught the greatness of Vi<218><207>u to ç
V<216>tra (the demon enemy of Indra) and spiritual wisdom to N<193>rada, ç
another great sage. Sanatsuj<193>ta taught spiritual truths to Dh<216>tar<193><218><219>ra, ç
the blind king and father of the Kauravas like Duryodhana. Sanaka ç
is said to be an eternal companion of Lord Vi<218><207>u. Sanandana ç
is accepted as an ancient teacher of S<193><209>khya, more ancient ç
than even Kapila.
@NT = caula
See <MS>C<188>£°KARAØA.<D>
@NT = caur<200>
See <MS>C°MARA.<D>
@NT = Cau<218>a<219> Yogin<200> Temples
@N1 = (`temples of 64 yoginis')
Yogin<200>s are minor goddesses, aspects of <185>akti or Durg<193>. ç
They are often the gramadevat<193>s or village deities supposed to ç
protect the people of the village when propitiated, or, bring evil ç
and disaster when offended. Their number is variously stated as 8, ç
60, 64 or even 65.
The  Cau<218>a<219>  Yogin<200>  Temples  are temples of that class ç
where these deities are placed in niches on a circular or rectangular ç
wall with a temple in the centre for the main deity.
Such temples, most of which were built between the 9th and 12th centuries, ç
are found in Bheraghat near Jabalpur (Madhya Pradesh), Ranipur Jhorial ç
near Patna (Bihar), Dudhati near Jhansi (Uttar Pradesh) and Khajuraho ç
(Madhya Pradesh). The only temple outside Central India is found near ç
Coimbatore in Tamil Nadu.
@NT = Cauvery
See <MS>K°VER®.
@SPACE = 
@NT = Cave Temples
@SPACE = 
Artificial caves excavated for religious purposes date from the time ç
of A·oka. Three phases of development of rock-cut architecture are ç
listed by Indologists: the first phase from the 2nd cent. <MS>B.C.<D> ç
to the 2nd cent. <MS>A.D.<D>; the second phase from the 5th to the ç
7th cent. <MS>A.D.<D>; the third phase from the 7th to the 10th cent. ç
<MS>A.D.<D>
The two caves of Barabar Hill near Gay<193> in Bihar, dedicated by ç
A·oka to the °j<200>vika monks, the cave at Karli and someBuddhist ç
caves at Ajanta (both in Maharashtra), as also the Jaina caves at ç
Udayagiri and Kha<207><195>agiri (Orissa) belong to the first phase. ç
Many caves at Ellora (Maharashtra) come under the second phase. The ç
Hindu and Jaina temples at Ellora, Elephanta and Salsette islands ç
near Mumbai (all in Maharashtra) belong to the third phase.
Out of about 1200 rock-cut caves discovered (in India), nearly 900 ç
are Buddhist, 200 are Jaina and the rest Hindu. Of the Buddhist caves, ç
those at Ajanta, Ellora, Karli and Nasik (all in Maharashtra) are ç
celebrated. Among the Jaina caves, those at Ellora are note- worthy. ç
The Hindu rock-cut temples at Ellora,  Elephanta  and  B<193>d<193>mi  (in ç
Karnataka) are equally famous. The Rathas of Mah<193>balipuram (Tamil ç
Nadu) and the temple of Kail<193>san<193>tha at Ellora, though not ç
cave temples, come under the general group of rock-cut temples and ç
are unrivalled.
The cave temples of the early phase, all Buddhist, generally have ç
caitya halls and a st<220>pa in them. They are vaulted rectangular ç
halls with an apsidal and containing a st<220>pa. Among them there ç
are also vih<193>ras or Buddhist monasteries with not only living ç
rooms but also a shrine-cell with an image of the Buddha cut out of ç
the rock in the rear wall.
The Hindu cave temples generally exhibit the same plan and pattern, ç
and elements of architecture which were well-developed in later years ç
in the regular temples built above the ground.
@NT = chala
@N1 = (`quibble')
The Ny<193>yas<220>tras of Gautama (4th cent. <MS>B.C.<D>), the ç
basic text of logical realism and one of the six systems of Hindu ç
philosophical thought, delineates 16 topics out of which nearly half ç
deal with logic. `Chala' is one of them. Usually translated as `quibble,' ç
it is one of the devices adopted by an opponent to conquer the exponent, ç
by deliberately misinterpreting his statement. For instance, when ç
the exponent says,  `The  boy  is  ``navakambala''<|>' (possessed ç
of a new blanket), the opponent can, unfairly, object, saying that, ç
`The boy is not possessing nine blankets' since `nava' means `new' ç
as well as `nine'. This is `chala'.
See also <MS>NY°YA-DAR<185>ANA.
@SPACE = 
@NT = Chandas
@N1 = (`that which exhilarates')
@SPACE = 
One of the names by which the Vedas are called, is `chandas,' `that ç
which exhilarates' or `that which gives a (protective) covering'. ç
More commonly, however, it denotes the metres in poetry. Vedic prosody ç
called `Chandas,' or `Chanda·-·<193>stra,' is considered as one of ç
the six `Ved<193><209>gas' or `limbs of the Veda' (subsidiary disciplines ç
pertaining to the field of Vedic studies), without a study of which, ç
it will be impossible to understand the Vedas proper. Before reciting ç
the Vedic mantras (chants or hymns) it is obligatory to pay one's ç
respect to the <216><218>i (sage through whom the mantra was revealed), ç
the devat<193> (the deityto whom it is addressed) and the chandas ç
(the metre in which the mantra is composed).
The earliest of the extant works on Vedic prosody is the Chandas-s<220>tra ç
by Pi<209>gala (2nd cent. <MS>B.C.<D>) which is in the formof s<220>tras ç
or aphorisms spread over eight chapters. Eleven major and many more ç
minor metres have been dealt with in this work. G<193>yatr<200>, u<218><207>ik, ç
anu<218><219>up, tri<218><219>up, jagat<200>, b<216>hat<200> and pa<209>kti ç
are the more common ones among them. Usually each metre consists of ç
one to five p<193>das or `feet' and each p<193>da should consist of ç
a specific number of letters. For instance, the famous g<193>yatr<200> ç
metre consists of three p<193>das and eight letters per p<193>da. ç
The various metres found in classical Sanskrit literature were gradually ç
evolved from the Vedic metres.
It was believed that the use of certain metres was conducive to the ç
attainment of power or could bring about harm to the enemies.
@NT = Chandas-·<193>stra, Chandas-s<220>tra
See <MS>CHANDAS<D>.
@NT = Chandoga-pari·i<218><219>a
Out of the six subsidiary works known as `Ved<193><209>gas' (`limbs ç
of the Vedas') the kalpas<220>tras deal mainly with sacri- ficial ç
rites. (See <MS>KALPAS<188>TRAS<D>.) To fill up the gaps as it were ç
and to expound details not mentioned in these works, but needed for ç
the meticulous performance of the sacrificial rites, some compendiums ç
were composed and they were called `pari·i<218><219>as' (`what is ç
left over,' appendix). Gobhila-sa<209>graha-pari·i<218><219>a  is  one  such  work ç
related to the S<193>maveda. Based on this work, K<193>ty<193>yana ç
(4th to 6th cent. <MS>A.D.<D>) wrote a work called Karmaprad<200>pa. ç
This work is known by several other names such as `S<193>mag<216>hya,' ç
`Ch<193>ndogyapari·i<218><219>a,' `Chandogapari·i<218><219>a' and ç
also, `Gobhila-sm<216>ti.' It contains about 500 verses.
This work deals with the topics of wearing the sacred thread, worship ç
of Ga<207>e·a and other deities, ·r<193>ddha (obsequial rites), consecration ç
of sacred fires, sandhy<193> ritual, the five daily sacrifices, rules ç
of personal cleanliness and cere- monial purity, duties of a wife ç
and so on.
@NT = Ch<193>ndogya Upani<218>ad
@S10 = Introduction
Among the six traditional systems of Hindu philosophy known as <186>a<195>-dar·anas, ç
the Ved<193>nta system, undoubtedly, gets the pride of place. This ç
system, which is very much alive even in the modern times and quite ç
popular, is based entirely on the Upani<218>ads, the predominantly ç
philosophical sections of the Vedas. The Ch<193>ndogya Upani<218>ad ç
is one of the ten Upani<218>ads considered to be ancient and authoritative, ç
and on which <185>a<209>kara (<MS>A.<|>D.<D> 788-820) has written a ç
voluminous commentary. Its importance can be judged from the fact ç
that the work Brahmas<220>tras has drawn heavily upon it, for topics ç
of discussion.
Though the word `chandas' (`that which exhilarates') is one of the ç
names of the Vedas in general, it is more particularly applied to ç
the S<193>maveda, the third of the four Vedas wherein the mantras, ç
known as `s<193>mans,' are set to music and sung. Those who have specialized ç
in thesinging of these s<193>mans, are called `Chandogas' and the ç
Br<193>hma<207>a (liturgical section) pertaining to them is designated ç
as Ch<193>ndogya Br<193>hma<207>a, which itself forms a part of ç
the T<193><207><195>ya branch of the S<193>maveda. This Br<193>hma<207>a ç
contains ten prap<193><219>hakas or sections out of which thefirst ç
two form the Mantra Br<193>hma<207>a and the rest, Ch<193>ndogya ç
Upani<218>ad. Itcomprises eight chapters and each is subdivided  into  `kha<207><195>as'  or  sections ç
(totalnumber of kha<207><195>as being 154) and contains 628 ka<207><195>ik<193>s ç
or mantras, all in prose.
@SPACE = 
@S10 = First Chapter
@SPACE = 
The speciality of this Upani<218>ad is that it describes a number ç
of `up<193>san<193>s' or `vidy<193>s' or meditations, based generally ç
on Vedic rituals. Since the average spiritual aspirant has devoted ç
the major part of his life to the performance of these rituals, it ç
will be rather difficult for him to take to meditation on God straight ç
away. Hence heis led to it gradually by a series of graded meditations ç
on the rituals, each of the parts being substituted by appropriate ç
symbols that elevate the whole process to spiritual levels. The entire ç
first chapter is devoted to one such meditation, that on the `udg<200>tha,' ç
the principal part of a s<193>man chant. Since the udg<200>tha invariably ç
starts with O<221> and O<221> is the best symbol of Param<193>tman, ç
the Supreme Self or God, the Upani<218>ad begins with its up<193>san<193>. ç
The second section, with the help of an ancient anecdote, stresses ç
the importance of meditation on the udg<200>tha as identified with ç
the mukhyapr<193><207>a, the primary life force within the body, which ç
at the cosmic level, has manifested itself as the sun. Meditation ç
on O<221> in various aspects is continued till the 7th section. The ç
twelfth section gives an amusing incident of dogs singing udg<200>tha ç
(hence called `·auva-udg<200>tha,' ·auva = related to dogs) for obtaining ç
food. <185>a<209>kara opines that some supernatural deities  assuming  the  forms  of  dogs ç
revealed this udg<200>tha to the sage Baka-D<193>lbhya, and it helps ç
a hungry person in securing food.
@S10 = Second Chapter
If the first chapter concentrated on prescribing meditation on the ç
different parts or limbs of the s<193>man, the second chapter is devoted ç
to meditations on the whole s<193>man. Sections 2 to 10 deal mainly ç
with such meditations. Sections 11 to 21 deal with the meditations ç
on certain special s<193>mans like the g<193>yatras<193>man, rathantara-s<193>man, ç
revat<200>s<193>man and so on. The twenty-third section, which mentions ç
about the four <193>·ramas or stages of life, deals with the result ç
of meditating purely on O<221>, which is the attainment of immortality.
@SPACE = 
@S10 = Third Chapter
@SPACE1 = 
The first eleven sections of the third chapter deal with the meditation ç
on the °ditya or the sun, who is the personification of the results ç
of all sacrifices, as also the karmas of all beings. The whole series ç
of meditations are called Madhu-vidy<193>, since °ditya has been ç
compared to `madhu' or honey. Sections 12 and 13 deal with meditation ç
on Brahman through the g<193>yatr<200> since that is the best among ç
the Vedic metres. Meditation on Brahman in the space or ether of the ç
heart, which is identical with the space or ether outside has also ç
been described. The 14th section gives the famous <185><193><207><195>ilyavidy<193>. ç
It prescribes meditation on the °tman in the lotus of one's heart, ç
but as identified with Brahman, called here as `tajjal<193>n.' This ç
leads to the attainment of Brahman, after the fall of the body. Sections ç
15 and 16 deal with Ko·avidy<193> for the longevity of one's son ç
and Puru<218>avidy<193> for one's own longevity. The sage Mahid<193>sa ç
Aitareya who discovered the latter vidy<193> is said to have lived ç
for 116 years.
@SPACE = 
@SPACE = 
@S10 = Fourth Chapter
@SPACE = 
The fourth chapter describes four important vidy<193>s: Sa<221>vargavidy<193>, ç
<186>o<195>a·a-kalavidy<193>, Upakosalavidy<193> and Ak<218>i-puru<218>avidy<193>. ç
J<193>na·ruti Pautr<193>ya<207>a, a king well-known for his generosity, ç
comes to know of the spiritual eminence of the sage Raikva through ç
the accidental hearing of a conversation between two swans flying ç
over his palace. After a thorough search he discovers Raikva resting ç
in the shade under a cart. Honouring him suitably with presents, the ç
king seeks spiritual wisdom from him. Raikva teaches him to meditate ç
upon V<193>yu (cosmic wind) outside and the mukhya-pr<193><207>a (chief ç
life-force) inside, as `sa<221>varga,' i.e., one which absorbs and ç
dissolves everything within itself. `Sa<221>varga' is Praj<193>pati, ç
the Self of all gods. This is the subject-matter of the first three ç
sections. The touching story of the young boy Satyak<193>ma J<193>b<193>la ç
and the <186>o<195>a·akalavidy<193> he received directly from supernatural ç
deities has been described in sections 4 to 9. Meditation on Brahman, ç
the final cause of this world, through meditation on its 16 `kalas' ç
or parts or aspects, is the subject matter of this particular vidy<193>. ç
Sections 10 to 14 deal with the story of Upakosala, a disciple of ç
Satyak<193>ma and his obtaining knowledge of Brahman from the three ç
sacred fires in the house of his guru. This has been called Upakosalavidy<193>. ç
The fires taught that pr<193><207>a or the chief life-force, manifesting ç
in the heart as bliss, is Brahman. The teacher Satyak<193>ma completed ç
their teaching by imparting the knowledge of the `ak<218>ipuru<218>a,' ç
the power behind the senses, the <193>tman. One who realizes this ç
<193>tman goes to the abode of Brahman after death and does not return ç
to transmi- gratory existence.
@S10 = Fifth Chapter
@EMERGENCY = The fifth chapter puts before us three kinds of destination ç
for a soul after the death of the body: (1) Those practising Pa<210>c<193>gnividy<193> ç
(`meditation on the five fires') and similar other up<193>san<193>s ç
will go by the `arcir<193>di-m<193>rga' or the path of light, to Brahmaloka, ç
the abode of Brahman and will not return to transmigratory worlds. ç
(2) Those who perform only rituals without enlightenment will travel ç
by the `dh<220>m<193>di-m<193>rga,' the path of smoke, and attain ç
the worlds like pit<216>loka or the world of manes, from which they ç
return to the human world after some time. (3) Those who lead a beastly ç
life without practising either up<193>san<193>s or ritualistic karmas, ç
will constantly go through the rounds of birth and death.
The first two sections prescribe meditation on the mukhya-pr<193><207>a, ç
the chief life- force, after establishing its superiority over other ç
pr<193><207>as (the sense-organs) through an anecdote. Sections 3 ç
to 10 deal with the famous Pa<210>c<193>gnividy<193> (`the doctrine ç
of the five fires') and eschatology. Young <185>vetaketu, puffed up ç
with the pride of learning, goes to the court of the king Prav<193>ha<207>a ç
Jaivali, with a view to establishing the superiority of his learning ç
but is rebuffed by the king who knew better. He returns crestfallen ç
and angry to his father,  the  sage  Gautama.  Gautama approaches ç
the king Prav<193>ha<207>a Jaivali in all humility and requests him ç
to teach the Pa<210>c<193>gnividy<193> about which he had questioned ç
<185>vetaketu earlier. In this vidy<193>, heavenly world, rains, earth, ç
man and woman are to be contemplated upon as fire into which oblations ç
of faith, subtle body (of the sacrificer), rain, food and semen are ç
poured, the final oblation being responsible for the rebirth of the ç
sacrificer. Those who know this science go to the world of Brahman ç
after death and will not return here. The rest of the chapter (sections ç
11 to 24) deals with the Vai·v<193>naravidy<193>. Six sages under ç
the leadership of Udd<193>laka °ru<207>i obtain this vidy<193> from ç
the king A·vapati Kaikeya who was an adept in it. Vai·v<193>nara °tman ç
is ®·vara or the Cosmic Being, pervading the universe. He is also ç
inside us as the chief life-force, mukhya-pr<193><207>a. Hence the ç
act of eating food should be contemplated upon as Agnihotra sacrifice. ç
One who achieves perfection in this will become identified with the ç
Cosmic Being. This is the gist of this vidy<193>.
@S10 = Sixth Chapter
The last three chapters<192>6th, 7th and 8th<192>contain the quintessence ç
of the Ved<193>nta philosophy. The whole of the sixth chapter is devoted ç
to a delineation of the Sadvidy<193>, knowledge and meditation pertaining ç
to Sat (the eternal Truth) or Brahman. It is in the form of a dialogue ç
between the son <185>vetaketu and his father Udd<193>laka °ru<207>i. ç
When <185>vetaketu returns home after completing a twelve-year course ç
in Vedic studies, the father Udd<193>laka °ru<207>i notices his conceit ç
born of that learning and questions him whether he has known that ç
by knowing which everything will be known. However, the boy had not ç
known it and so requests his father himself to teach it to him. Citing ç
the examples of clay, gold and iron, and their products (like pot, ç
ornament and nail-cutter) the father first draws the attention of ç
his son to the identity between the cause and its effects, pointing ç
out that names and forms are unreal, the substance alone being real. ç
Applying this principle, he states that before creation, Sat (the ç
eternal Truth) alone existed and that Sat evolved into this world ç
of names and forms through the three primary elements: tejas (fire), ç
ap (water) and anna (earth). All objects of creation including the ç
bodies of living beings, have come out of these elements through permutation ç
and combination. This is the gist of the teachings of the first seven ç
sections. Sections 8 to 10 deal with the merging of the individual ç
self,the j<200>va, into Sat during the state of deep sleep. However, ç
since ignorance persists, he comes back to his original state. The ç
same logic applies in the case of rebirth after death also. But, those ç
who attain knowledge will get liberated. The famous Ved<193>ntic dictum ç
tat tvam asi, `That thou art', appears for the first time in the ç
eighth section and is repeated later, nine times. Sections 12 and ç
13 teach that Sat, the primary Cause of the universe, is too subtle ç
to be perceived even as the seed of the banyan tree in which the whole ç
tree exists in an involved state. But it pervades the entire creation ç
like the lump of salt dissolved in a jar of water. To know this Sat, ç
the help of a teacher, guru or guide,is necessary. It is like a blindfolded ç
traveller, let off in a forest by robbers, finding his way out with ç
the help of a kind soul. This is the teaching of the 14th section. ç
Though the mode of death is similar to the ignorant as well as the ç
enlightened souls, the latter will not transmigrate whereas the former ç
do. This is explained in the last two sections with the help of an ç
anecdote of the police catching a thief. The purport of the whole ç
chapter seems to be to teach the identity of the j<200>v<193>tman ç
or the individual self with Brahman, the Cosmic Soul.
@SPACE = 
@S10 = Seventh Chapter
@SPACE = 
The seventh chapter teaches Bh<220>ma-vidy<193>, knowledge of the ç
Infinite. N<193>rada, though himself a great sage and a man of considerable ç
erudition, approaches the distinguished sage Sanatkum<193>ra with ç
a heavy heart seeking peace and joy. Sanatkum<193>ra takes him step ç
by step through meditations on fifteen objects like name, speech, ç
mind and so on, to Bh<220>man, the Infinite. The Bh<220>man which ç
is everywhere, which is established in its own glory, by knowing which ç
there is nothing else to be known, is the Self of all beings. One ç
who realizes it, becomes `svar<193><219>.' Like a king, he will have ç
full freedom in all the worlds. To obtain this knowledge, purity of ç
mind got through purity of food and purity of sense-experience, is ç
necessary. It is only a pure mind that can retain and realize spiritual ç
truths.
@SPACE = 
@S10 = Eighth Chapter
@SPACE = 
It is rather difficult to comprehend and contemplate upon Brahman ç
without qualities, described as Sat and Bh<220>man. It is easier to ç
meditate upon the sagu<207>a or  qualified  aspect  of  Brahman,  as ç
possessing of blessed qualities. The eighth chapter prescribes such ç
a meditation on Brahman in the region of one's heart, as also related ç
disciplines like brahmacarya. The first two sections deal with Dahara-vidy<193>, ç
meditation on Brahman in the `dahar<193>k<193>·a,' the little space ç
in the region of the heart. This <193>k<193>·a or space in the heart ç
is itself Brahman. It is not limited to that spatial area nor does ç
it get destroyed with the destruction of the body. One who realizes ç
this obtains whatever he wants, in whichever world he contemplates. ç
The next three sections extol and prescribe brahmacarya or celibacy ç
and other related disciplines, for realizing the °tman-Brahman, who ç
like a dyke is protecting all the worlds. The sixth section describes ç
the various n<193><195><200>s or passages for the flow of pr<193><207>ic ç
energy and how the soul of a man of knowledge, at the time of death, ç
enters into su<218>umn<193> n<193><195><200>, departs through the ç
aperture in the top of the head and reaches Brahmaloka, the abode ç
of Brahman, from which there is no return. Sections 7 to 12 deal with ç
the teachings of Praj<193>pati to Indra and Virocana. Hearing from ç
Praj<193>pati, the father of creation, that one who realizes the <193>tman, ç
the Self, who is sinless and beyond all limitations like hunger and ç
thirst, old-age and death, Indra the king of gods and Virocana the ç
king of demons decided to get that knowledge of the <193>tman. Afterundergoing ç
brahmacarya (disciplines necessary for spiritual studies) for 32 years, ç
they both approached him for the teaching. When Praj<193>pati said, ç
that the `person seen in the eye' is the <193>tman, Virocana understood ç
it as the reflection seen in the eyeball, which again is the body. ç
Fully satisfied with this understanding that the body is itself the ç
<193>tman, he returned to his tribe and taught it to them. Indra too ç
took it that way; but very soon he got doubts since the body which ç
is seen in the reflection, is subject to mutilation, disease and death, ç
whereas the <193>tman is not. He returned and expressed his doubts ç
when Praj<193>pati instructed him, after a further period of brahmacarya ç
for 32 years, that the `person who moves about in the dream is the ç
<193>tman.' When Indra discovered the limitations of this teaching ç
as also of the next that `the person in dreamless sleep is the <193>tman,' ç
he was truly instructed (after further periods of brahmacarya totalling ç
in all, 101 years) that the <193>tman is the `seer' behind the eyes ç
and all other sense organs, is the witness of all the states and is ç
the immortal spirit different from the mortal body. The last section ç
gives the list of teachers of spiritual wisdom. It also adds that ç
one who leads a life in accordance with dharma and meditates on Brahman ç
in the heart, will reach Brahma-loka after death and will not return.
@S10 = Epilogue
Apart from the fact that this Upani<218>ad is the second longest and ç
one of the more ancient ones, it throws an interesting light on contemporary ç
history and customs. It mentions many geographical names like P<193><210>c<193>la, ç
Kuru, Naimi<218>a, G<193>ndh<193>ra and Kekaya. References to many ç
sciences and arts, villages and towns, buildings and parts of buildings, ç
tools of iron and other implements, different kinds of articles of ç
food and drink, musical instruments, minerals and metals mentioned  by  name,  carts  and  chariots, ç
keepers of cows and horses, kingsand law-enforcing agencies, several ç
calendaric terms<192>all these indicate a fair degree of civilization. ç
Family life was highly valued and social life was generally peaceful. ç
Truth and righteousness were given the pride of place. For acquiring ç
knowledge from competent teachers no sacrifice was considered too ç
great. The teachers also enforced discipline strictly. Though ritua-listic ç
religion was very much in vogue, philosophical inquiry was considered ç
a superior pursuit.
Thus, the Ch<193>ndogya Upani<218>ad is a unique text of the Ved<193>nta ç
system giving an insight into a philosophical inquiry of the highest ç
kind.
See also <MS>UPANI<186>ADS <D>and<MS> VIDY°S<D>.
@NT = Ch<193>y<193>
@N1 = (`shadow')
Sometimes, the Hindu mythological lore gives us very interesting stories. ç
The story of Sa<221>j<210><193> and Ch<193>y<193> is one such.
Sa<221>j<210><193>, the daughter of Tva<218><219><216>, had been married ç
to S<220>rya, the sun-god. Unable to bear the heat and brilliance ç
of her husband, Sa<221>j<210><193> created her double, Ch<193>y<193>, ç
and left her in S<220>rya's palace and disappeared. S<220>rya lived ç
with Ch<193>y<193> under the impression that she was Sa<221>j<210><193> ç
herself. Ch<193>y<193> bore him two sons and a daughter: S<193>var<207>i ç
Manu, <185>anai·cara (or the planet <185>ani) and Tapat<200> (the ç
goddess of the river Tapti, in Madhya Pradesh).
See also <MS>SA<189>J<178>°<D> and <MS>S<188>RYA.<D>
@NT = child-marriage
Child-marriage has often been a subject of criticism against the Hindu ç
society. But child-marriage was not a peculiar phenomenon of the Hindu ç
society alone. It existed even in England during the middle of the ç
16th century.
During the times of the <184>gveda, it was unheard of. Till <MS>A.D.<D> ç
200, marriage of girls just before or after puberty was the rule. ç
Girls could be married even up to or after three years, after puberty. ç
If the parents did not get them married even then, the grown-up girls ç
had the freedom to choose their husbands (vide Manusm<216>ti 9.89-90).
However, the situation changed after <MS>A.<|>D.<D> 200 and child-marriages ç
became more a rule than an exception. Some scholars opine that the ç
rise of the institution of Buddhist nuns by about this period and ç
the laxity of morals among the nuns forced the Hindu society to adopt ç
child-marriage as a counter measure. The age of girls for marriage ç
was usually 6 to 8 years, an equivalent of the age of the boys for ç
upanayana (the ceremony of investiture with the sacred thread).
These child-marriages were however mere sacraments of betrothal and ç
the child couple continued to live with their parents. Consummation  took  place  only  after ç
puberty.
During  those  days,  joint  family system was very much in vogue. ç
The child couples were received into the big family with love and ç
affection. Hence there were practically no problems of psychological ç
adjustment on either side.
It cannot of course be denied that things were often taken to ridiculous ç
lengths, resulting sometimes in the cruel problem of child widows.
@SPACE1 = 
It will be of interest to note here that all the rules of the dharma·<193>stras ç
regarding child-marriage were only for the br<193>hma<207>as and did ç
not affect the other sections of the Hindu society.
See also <MS>VIV°HA.<D>
@NT = Chinnamast<193>
@N1 = (`one with a severed head')
The tantras, religio-philosophical texts devoted to the cult of worship ç
of God as the Divine Mother, speak of ten aspects of <185>akti (power ç
of God, deified as his female consort) called `Da·amah<193>-vidy<193>s'. ç
Out of these ten, `Chinnamast<193>' is the sixth in the series.
She is generally depicted as a goddess holding her own severed head ç
in hand, which drinks the blood gushing out of her own body. She represents ç
the continued state of self-sustenance of the created world in which ç
are seen continuous self-destruction and self-renewal, in a cyclic ç
order.
The   Buddhist   t<193>ntrik   goddess Vajrayogin<200> is iconographically ç
similar to Chinnamast<193>.
See <MS>DA<185>AMAH°VIDY°S<D> and <MS>TANTRAS.
@NT = Chowkhamba Sanskrit Series Office
One of the biggest publishing houses of books on Indology, this firm ç
was established in <MS>A.<|>D.<D> 1892 at V<193>r<193><207>as<200> ç
by B<193>bu Harid<193>s Gupta (<MS>A.<|>D.<D> 1868-1908). It was named ç
Chowkhamba Sanskrit Series Office.
As per the avowed purpose, it started publishing rare Sanskrit manuscripts ç
to meet the demands of the scholarly world. This helped in the rejuvenation ç
of Sanskrit studies including interest in research work.
It  has  maintained  an  unbroken schedule of publications over the ç
years. It has to its credit more than a dozen series such as:
@NID = Chowkhamba Sanskrit Series (<MS>A.<|>D.<D> 1898)
@NID = K<193>·<200> Sanskrit Series (<MS>A.<|>D.<D> 1915)
@NID = Harid<193>s Sanskrit Series (<MS>A.<|>D.<D> 1927)
In <MS>A.<|>D.<D> 1954, three new series were added on °yurveda, R<193><218><219>rabh<193><218><193> ç
(Hindi) and Sanskrit.
The subjects so far covered include the Vedas, Upani<218>ads, pur<193><207>as, ç
dharma-·<193>stras, astrology, <193>yurveda, grammar, history and ç
philosophy.
Hindi and English translations of such works have also been brought ç
out.
One of the biggest achievements has been the bringing out a new impression ç
of V<193>caspatyam, a Sanskrit-Sanskrit dictionary in five volumes ç
in <MS>A.<|>D.<D> 1992.
@NT = cicchakti
@N1 = (`sentient power')
The bhakti schools of Ved<193>nta as those propounded by Nimb<193>rka ç
(14th cent.<MS> A.<|>D.<D>), Vallabha (<MS>A.<|>D.<D> 1473-1531), Caitanya ç
(<MS>A.<|>D.<D> 1485-1533) and <185>r<200>ka<207><219>ha (13th cent.<MS>A.<|>D.<D>) ç
have tried to reconcile the existence side by side, of the cit or ç
conscious and the acit or unconscious aspects of creation within the ç
broad framework of advaita or non-dualism. According to these schools, ç
Brahman, the Absolute or God, has two aspects of power: cit-·akti ç
(also cicchakti) or the sentient power and the acit-·akti (also acicchakti) ç
or the insentient power.
God in his own nature, is absolutely formless pure consciousness. ç
By cicchakti or the sentient power he holds the individual souls within ç
him. By acicchakti or the insentient power he spreads out the material ç
world and connects it with the former for their diverse experiences.
Cicchakti (sometimes called `svar<220>pa-·<193>kti' or `antara<209>ga·akti') ç
again, is said to have three aspects†sandhin<200>, sa<221>vit and ç
hl<193>din<200>†corresponding respectively to the sat, cit and <193>nanda ç
aspects of God. By sandhin<200> God upholds his own existence and ç
that of others. By sa<221>vit he knows and makes others know. By hl<193>din<200>, ç
he enjoys and makes others enjoy bliss.
See also <MS>ACICCHAKTI.
@SPACE = 
@NT = cid<193>k<193>·a
@N1 = (`space or ether of<R>ç
consciousness')
@SPACE = 
The Upani<218>ads describe <193>k<193>·a (generally translated as ç
space or ether) as the body of Brahman, the Absolute. This <193>k<193>·a ç
is also, sometimes, identified with bliss. However, the <193>k<193>·a, ç
in these statements should not be confused with the `bh<220>t<193>k<193>·a,' ç
or elemental <193>k<193>·a, but must be understood as `cid<193>k<193>·a,' ç
or plane of consciousness. Some <185>aiva philosophers like <185>r<200>ka<207><219>ha ç
(13th cent. <MS>A.<|>D.<D>) consider it as the ultimate material principle ç
(`par<193>prak<216>ti'),  the  same  as  ultimate energy. It is the ç
energy of consciousness, otherwise called cicchakti also. It is the ç
original force of life that manifests itself in the activities of ç
life. All kinds of life functions and all experiences of pleasure ç
are based on the lower or higher level of this cid<193>k<193>·a.
See also <MS>CICCHAKTI.<D>
@SPACE = 
@NT = Cidambaram
@N1 = (`ether of consciousness')
@SPACE = 
Pilgrimage to holy places has become a part of a Hindu's life. Such ç
places are generally associated with avat<193>ra-puru<218>as (incarnations ç
of God), <216><218>is (sages) or other holy persons. And, they are ç
mostly situated in places of great natural beauty conducive to spiritual ç
pursuits.
One of the most famous places of pilgrimage in South India which draws ç
thousands of votaries even from Sri Lanka, is Cidambaram (Chidambaram), ç
called `Tillai' in Tamil. It is about 230 kms. (150 miles) to the ç
south-west of Madras city and is situated in the south Arcot district ç
of Tamil Nadu. It is one of the `pa<210>ca-li<209>gas' (emblems of ç
<185>iva representing the five elements) and houses the `<193>k<193>·ali<209>ga' ç
(`emblem of the ether principle'). The original icon of the famous ç
Na<219>ar<193>ja (See <MS>NA<187>AR°JA.<D>), made of gold, is kept ç
in the `Kanaka Sabh<193>' (`golden hall'), one of the five spacious ç
halls in the temple complex. The hall itself gets its name due to ç
the fact of its roof being covered with golden plates. (kanaka = gold).
@SPACE1 = 
Most of the places of Hindu pilgrimage have a `sthalapur<193><207>a,' ç
a local legend, explaining the significance of the place andits holy ç
associations. As per the local legend of Cidambaram, this is the place ç
where <185>iva defeated Bhadrak<193>l<200> in a dance contest and ç
blessed his devotees, the sages Pata<210>jali (incarnation of the ç
serpent deity °di·e<218>a) and Vy<193>ghrapada. Local tradition holds ç
the temple to be about 2000 years old.
Sprawling over an area of 13 hectares (32 acres), the Na<219>ar<193>ja ç
temple complex stands on an alluvial plain between two rivers. Built ç
entirely of dressed granite† though no granite has been found within ç
a radius of about 77 kms. (50 miles)†it is surrounded by nine meter ç
(30 ft.) high boundary walls. There are several gopurams or gateways, ç
one facing the east rising in nine tiers, being the most beautiful. ç
It is exquisitely decorated with friezes depicting scenes from Hindu ç
mytho- logy. Two of the gopurams attached to the inner wall of the ç
main temple exhibit 108 poses of dance taught in the n<193><219>ya·<193>stra ç
or the science of dance. There are several subsidiary temples in the ç
complex, dedicated to <185>ivak<193>m<200> (P<193>rvat<200>, the consort ç
of <185>iva), Govindar<193>ja (Vi<218><207>u), Pu<207><195>ar<200>kavall<200> ç
(Lak<218>m<200>) and Ga<207>e·a. The icon of Ga<207>e·a here is said ç
to be the largest in size, in the whole of India. There is also the ç
main temple tank called `<185>ivaga<209>g<193>' measuring 45 m. by ç
30 m. (150' by 100') with steps all round. The thousand pillared hall ç
near this tank is associated with Sekkizhar (11th cent. <MS>A.<|>D.<D>) ç
who is said to have composed his monumental work Peria-pur<193><207>am ç
(`the Great Mythology' containing the biographies of <185>aivite saints ç
of Tamil Nadu) here.
To the right of the icon of Na<219>ar<193>ja, on the background wall, ç
there is a yantra (geometrical symbol of the deity) adorned with golden ç
necklaces. This is the place of the `<193>k<193>·ali<209>ga' and is ç
known as `cidambara-rahasya,' the `secret' of Cidambaram. It is kept ç
covered by a screen which is pushed aside twice a day for facilitating ç
the devotees to view it.
@SPACE1 = 
Though built in stages by several kings like Kulottu<209>ga II (<MS>A.<|>D.<D> ç
1135-1150), Sundara P<193><207><195>ya II (c. 1250), and K<216><218><207>a-devar<193>ya ç
(<MS>A.D.<D> 1509-1529), the architectural harmony has been maintained ç
and it is of the Co<202>a style. In fact, the deity was the family ç
God of the Co<202>a dynasty.
The biggest festival at the Cidambaram temple is `Tiruv<193>dirai' ç
which falls during December-January. Since it is a <185>iva temple, ç
Mah<193>·ivar<193>tri is of course, celebrated in a grand manner.
@NT = cikits<193>
@N1 = (`desire to get rid of disease')
°yurveda, the science of health and longevity, is an ancient discipline. ç
It purports to treat, not the disease as such, but the patient himself. ç
In the process of making the patient recover his health and enabling ç
him to live long, curative treatment is only one of the steps.
Out of the `a<218><219><193><209>gas' or eight limbs of this science, ç
`cikits<193>' or treatment of the disease, forms the sixth. It has ç
four p<193>das or quarters: vaidya (the physician), au<218>adha (the ç
medicine), paric<193>raka (the nurse) and rogi (the patient).
The vaidya should be an adept in this science, not only in theory ç
but also in practice. He should be devoted to his profession and of ç
righteous conduct.
The au<218>adha must be prepared by the vaidya himself after proper ç
examination of the patient and diagnosis, with the right kind of materials.
The paric<193>raka must be meticulous, hardworking and sympathetic ç
towards the patient.
The rogi should obey the commands of the physician and cooperate strictly ç
with the paric<193>raka.
If these conditions are fulfilled, treatment will be effective.
See also <MS>°YURVEDA.<D>
@NT = c<200>n<193>c<193>ra
@N1 = (`practice obtaining in C<200>n<193>')
See <MS>V°M°C°RA.<D>
@NT = cinmudr<193>
@N1 = (`hand-pose indicating<R>ç
knowledge')
Icons of deities, sages and saints, sculptured as per the rules given ç
in the standard works of iconography, usually havecertain hand-poses ç
called `hasta' or `mudr<193>', indicating certain specific ideas or ç
sentiments. One such pose, the `cinmudr<193>,' is sculptured on images ç
in the posture  of  imparting  knowledge.  For instance: Dak<218>i<207><193>m<220>rti ç
aspect of <185>iva and °di·a<209>kara. In this pose the tips of the ç
thumb and the forefinger, usually of the right hand, are joined to ç
form a circle while the other fingers are kept open and stretched. ç
The whole palm faces outwards.
This mudr<193> is also called `vy<193>khy<193>na or sande·a' mudr<193>.
See <MS>MUDR°S.
@NT = Cint<193>ma<207>i
@N1 = (`thought-gem')
@SPACE = 
The pur<193><207>as describe this supernatural gem, the possessor ç
of which is said to obtain whatever he wishes for (ma<207>i = gem; ç
cint<193> = thought, wish).
In devotional literature, God is des-cribed as Cint<193>ma<207>i for ç
the same reason.
In astrology, a particular combination of planets heralding an auspicious ç
time for travelling is called cint<193>ma<207>i.
In Buddhist symbology, it stands for the mind.
@SPACE = 
@NT = ciraj<200>vins
@N1 = (`those who live eternally')
@SPACE = 
The Hindu epics and pur<193><207>as have listed seven persons as `ciraj<200>vins' ç
or ever-living. They are: A·vatth<193>ma (the son of preceptor Dro<207>a), ç
Bali (the king of p<193>t<193>la or the nether world), Hanum<193>n ç
(the monkey-devotee of R<193>ma), K<216>pa (a br<193>hma<207>a warrior ç
mentioned in the Mah<193>bh<193>rata), Para·ur<193>ma (the sage ç
turned killer of the evil k<218>attriyas), Vibh<200><218>a<207>a (youngest ç
brother of R<193>va<207>a, the king of La<209>k<193>) and Vy<193>sa ç
(the sage and author of the epic Mah<193>bh<193>rata and the pur<193><207>as).
To this list should be added the name of M<193>rka<207><195>eya, the ç
sage who conquered death through his devotion to <185>iva.
Due to various reasons as depicted in their stories they obtained ç
the boon of living for ever on this earth, though in a subtle body.
@SPACE = 
@NT = cit
@N1 = (`consciousness')
@SPACE = 
According to the philosophy of R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137), ç
known as Vi·i<218><219><193>dvaita (qualified monism), Brahman, ®·vara ç
or God possesses in himself two modes or aspects†the `cit' or the ç
sentient part and the `acit' or the insentient part†using which he ç
brings about creation. The innumerable j<200>vas or individual souls ç
endowed with consciousness constitute the `cit' whereas `prak<216>ti' ç
or insentient nature constitutes `acit'.
The word `cit' is also used in other systems of Indian philosophy ç
to indicate the soul and consciousness.
See also <MS>ACIT<D> and <MS>VI<185>I<186><187>°DVAITA- VED°NTA-DAR<185>ANA.
@SPACE = 
@NT = citi, citi·akti
@N1 = (`consciousness,' `conscious power')
@SPACE = 
The Yoga system of philosophy, as systematized by Pata<210>jali (200 ç
<MS>B.<|>C.<D>) posits three fundamental principles: puru<218>a or ç
the individual soul, prak<216>ti or insentient nature and ®·vara or ç
God. Among these, puru<218>a is also called by other names such as ç
dra<218><219><193> (the seer), citi (consciousness) and citi·akti ç
(conscious power). His essential nature is pure consciousness; hence ç
the name.
See also <MS>PURU<186>A.<D>
@NT = Citragupta
@N1 = (`secret picture')
All the deeds of human beings, whether good or bad, are supposed to ç
be recorded by Citragupta, the scribe of Yama, the god of death. According ç
to one version, he wasoriginally a king of the S<220>ryava<221>·a ç
(descended from the Sun) who had attained omniscience through the ç
worship of S<220>rya. He was hence taken away by Yama and appointed ç
as a scribe in his world. As per another version, he emanated out ç
of the body of Brahm<193> when he was in deep meditation. Brahm<193> ç
himself taught him the knowledge of the hidden and subtle things. ç
He was later on chosen to be the scribe of Yama. He is regarded as ç
the progenitor of the caste `k<193>yastha' and had nine sons. The ç
names of these sons (eg., Bha<219><219>a, N<193>gara, Amba<218><219>ha ç
etc.) are also caste names and hence considered as the progenitors ç
of those castes.
Contrary  to  common  conception, Citragupta is a single person and ç
not two.
Iconographical works depict him as red in colour and place his image ç
to the right of Yama. He is invariably shown with a stylus and a palm ç
leaf in his hands, the paraphernalia of a scribe.
Citragupta is worshipped, especially by the k<193>yasthas (a particular ç
caste), on Yamadvit<200>y<193> day (second day of bright half of the ç
month K<193>rttika, usually in November). On this day sisters invite ç
their brothers for a feast and offer presents.
See also <MS>YAMA.<D>
@NT = Citrak<220><219>a
@N1 = (`variegated peak')
@SPACE = 
@SPACE = 
Citrak<220><219>a is one of the holy places associated with <185>r<200> ç
R<193>ma and an important pilgrimage centre. It is situated in the ç
Banda district of Uttar Pradesh, about 140 kms. (87 miles) from the ç
city of Allahabad.
According to the R<193>m<193>ya<207>a of V<193>lm<200>ki, after ç
being banished from Ayodhy<193>, <185>r<200> R<193>ma, S<200>t<193> ç
and Lak<218>ma<207>a came here and lived for a few days. It was here ç
that Bharata (the brother for whose sake <185>r<200> R<193>ma had ç
to give up the kingdom) met him to persuade him to go back to Ayodhy<193>; ç
and failing in the mission, returned with the p<193>duk<193>s (wooden ç
sandals) of <185>r<200> R<193>ma.
The poet-saint Tuls<200>d<193>s (16th cent. <MS>A.D.<D>) is said to ç
have had a vision of <185>riR<193>ma here.
Citrak<220><219>a and the village S<200>t<193>pur are situated on ç
the left bank of the river Mand<193>kin<200>, also called Payo<218><207><200> ç
or Payasvin<200>. It is a very picturesque place with the K<193>madgiri ç
hill and a forest associated with it. It is customary for the pilgrims ç
to go round the hill. This is called `parikrama'.
Other notable places are: R<193>mgh<193><219> andJ<193>nak<200>gha<219> ç
(where <185>r<200> R<193>ma and S<200>t<193> used to bathe); Spha<219>ika·il<193> ç
(where <185>r<200> R<193>ma is said to have slept on the lap of S<200>t<193> ç
when the demon K<193>k<193>sura hurt her); Bharatak<220>pa (the well ç
into which Bharata poured all the sacred waters collected for <185>r<200> ç
R<193>ma's coronation, but which could not be used); Gupta-god<193>var<200> ç
(a stream inside a cave); Atri °·rama, also called Anas<220>y<193>ji, ç
the hermitage of the sage couple, Atri and Anas<220>y<193>.
Huge crowds gather here on <185>r<200>r<193>manavam<200> (birthday ç
of <185>r<200> R<193>ma, usually in April) and D<200>p<193>val<200> ç
or Diwali (usually in November) days.
Other holy places in the vicinity of Citrak<220><219>a are the hermitages ç
of V<193>lm<200>ki, <185>arabha<209>ga and Sut<200>k<218><207>a.
@NT = Citr<193><209>gad<193>
Daughter of the king Citrav<193>hana (also known as Malayadhvaja) ç
she was one of the wives of Arjuna, the great P<193><207><195>ava ç
hero of the Mah<193>bh<193>rata. She bore him an equally heroic ç
son, named Babhruv<193>hana. When Arjuna was on a conquering expedition, ç
following the horse of the A·vamedha sacrifice, he was challenged ç
and killed by Babhruv<193>hana who did not know him as his father, ç
since Babhruv<193>hana had lived away from him even from childhood ç
days and had no occasion to meet him. Citr<193><209>gad<193> however, ç
revived Arjuna to life with the help of Ul<220>p<200>, another wife ç
of Arjuna, belonging to the tribe of the N<193>gas.
See also <MS>ARJUNA.<D>
@NT = citr<193>p<220>r<207>im<193>
@N1 = (`full-moon day of Caitra')
The full-moon day in the month of Caitra (March-April) is said to ç
be sacred to Citragupta, the scribe of Yama. If the day happens to ç
be a Thursday, Saturday or Sunday, it is considered even more auspicious. ç
Special worship is offered to Citragupta on this day. In Tamil Nadu, ç
people believe that a bath in the river Citr<193> rising on the Ku<219><219>alam ç
hills in the Tirunelvelly district, on this day, is meritorious since ç
the river took its birth on this day. K<193><210>c<200>puram has a ç
temple of Citragupta, which seems to be the only temple of this deity ç
in the whole of South India.
See also <MS>CITRAGUPTA.
@SPACE = 
@NT = Citsukha, Citsukh<200>
@SPACE = 
Post-<185>a<209>kara literature on Advaita Ved<193>nta has grown enormously, ç
both in quantity and in quality as also subtlety. Citsukha is one ç
of the well-known writers of this period, on Advaita Ved<193>nta. ç
He lived in the early part of the thirteenth century. He was a pupil ç
of Gau<195>e·var<193>-c<193>rya, also known as J<210><193>nottama. ç
His works are: Bh<193><218>ya-bh<193>va-prak<193>·ik<193> (a commentary ç
on the Brahmas<220>trabh<193><218>ya of <185>a<209>kara); Abhipr<193>ya-prak<193>·ik<193> ç
(commentary on the Brahmasiddhi of Ma<207><195>ana); commentaries ç
on the Nai<218>karmyasiddhi of Sure·vara, Ny<193>yamakaranda of ç
°nanda-bodha and Kha<207><195>ana-kha<207><195>a-kh<193>dya of <185>r<200>har<218>a.
However his most important work isTattvaprad<200>pik<193>, commonly ç
known as Citsukh<200>. It is a unique work for two reasons: (1) ç
It effectively refutes the categories of the Ny<193>ya-Vai·e<218>ika ç
schools; (2) It establishes some of the fundamental points of <185>a<209>kara's ç
advaita by carrying out a subtle analysis and interpretation of them.
Citsukh<200> comprises four chapters. Thefirst chapter deals with ç
the Ved<193>ntic concepts like the <193>tman being self-luminous and ç
pure consciousness, nature of avidy<193> (nescience or ignorance), ç
mithy<193>tva (nature of falsity of the world), nature of illusions ç
and so on. The second chapter analyzes the various concepts and categories ç
of the Ny<193>ya and the Vai·e<218>ika systems  like  gu<207>a  (quality),  karma ç
(action), s<193>m<193>nya (generality), samav<193>ya (inherence) and ç
so on, and refutes them. The third chapter deals with the possibility ç
of realization of Brahman and the nature of mukti (liberation) through ç
j<210><193>na (know-ledge). The last chapter deals with the nature ç
of the ultimate state of liberation.
See also <MS>ADVAITA-VED°NTA-DAR<185>ANA.
@SPACE = 
@NT = citta
@N1 = (`that through which one knows')
@SPACE = 
`Citta' is one of the general names given  to  the  mind  in  the  Indian ç
philosophical systems. The word `manas' is of course more common. ç
However, since the Yoga system of Pata<210>jali has adopted this word ç
and treats of it in a technical and exhaustive manner, we will mainly ç
confine ourselves here to the treatment given in that system. As regards ç
the concept of mind in other systems of Indian philosophy, see <MS>MIND.<D>
Pata<210>jali (200 <MS>B.C.<D>) considers `citta' or mindstuff as ç
a physical material made up of the three gu<207>as of sattva, rajas ç
and tamas, but with a preponderance of sattva. (See <MS>GUØAS, RAJAS, ç
SATTVA<D> and <MS>TAMAS<D>.) It is capable of reflecting the power ç
of pure consciousness of the puru<218>a or the individual soul. It ç
is also capable of modifications. It is the modified citta with the ç
pure consciousness reflected in it that is responsible for cognition, ç
thinking,<|>doubts or drawing definite conclusions. Hence itis also ç
called by such names as anta<199>kara<207>a (the internal organ), ç
manas (the mind) and buddhi (the intellect). The modifications themselves ç
are called `cittav<216>ttis'. When these cittav<216>ttis are suppressed ç
(`niruddha') then, `yoga' results; that is, the puru<218>a or the ç
soul gets detached from the citta and is re-established in his own ç
glory. `Yoga' (union) is thus actually, `viyoga' (separation) from ç
the mindstuff.
The citta works at five levels, called `cittabh<220>mis.' They are: ç
k<218>ipta (restlessness), m<220><195>ha (torpidity), vik<218>ipta ç
(distraction), ek<193>gra (onepointedness) and niruddha (suppressed ç
or without modifications). Of course, it is only in the last two levels ç
that yoga is possible.
Pata<210>jali also postulates two `citta-dharmas' or characteristics, ç
for the citta. They are parid<216><218><219>a (the seen) and aparid<216><218><219>a ç
(the unseen). Means of know-ledge like direct perception which rouse ç
cittav<216>ttis  and  are  hence  discernible, belong to the former. ç
`Sa<221>sk<193>ras' or innate tendencies, `dharma' or effects of previous ç
actions inherent in the mind, ultimately resulting in happy and unhappy ç
experiences and a few other such qualities belong to the second.
Pata<210>jali also deals with some obstacles to yoga, called `antar<193>yas' ç
which cause `cittavik<218>epa' or distraction of mind. Vy<193>dhi ç
(disease), sty<193>na (mental laziness), sa<221>·aya (doubt), <193>lasya ç
(physical laziness), etc., are some of these obstacles.
To overcome these and get `citta-pras<193>dana' or peace of mind, ç
he recommends several steps like cultivating an attitude of friendship ç
towards the happy people and compassion towards those in difficulties.
While  dealing  with  the  psychic powers, Pata<210>jali mentions ç
`cittasa<221>vit' or full knowledge about the mind by meditating on ç
one's heart and attaining sam<193>dhi (perfect concentration) there.
@SPACE1 = 
See also <MS>AHA<177>K°RA,<D> <MS>ANTAßKARAØA, BUDDHI, MANAS<D> and ç
<MS>YOGA-DAR<185>ANA.<D>
@NT = citta-bh<220>mi, citta-dharma,<R>ç
citta-pras<193>dana, citta-sa<221>vit,<R>ç
citta-vik<218>epa and citta-v<216>tti
See <MS>CITTA.<D>
@NT = cognition
See <MS>J<178>°NA, MIND<D> and <MS>PRAM°.<D>
@NT = Cokh<193>me<202><193>
Untouchability (asp<216>·yat<193>) has been an ugly blot on the Hindu ç
society. As if to deliver a blow to such narrow concepts and practices, ç
many great saints have been born among these untouchables. They had ç
to be accepted and honoured by the elitist groups and castes by the ç
sheer power of their spiritual glory.
One such great saint was Cokh<193>me<202><193>. He lived in the thirteenth ç
century in the holy city of Pa<207><195>har<193>pura (in Maha- rashtra). ç
It was his wont to have a dip in the Bh<200>m<193> river early in ç
the morning, circumambulate the temple of P<193><207><195>ura<209>ga ç
(also called Vi<219><219>hala, an aspect of Vi<218><207>u or K<216><218><207>a) ç
from outside, bow down to the deity from the main gate and sing songs ç
in his praise, mostly composed by himself. The proud and prejudiced ç
priests tried their best to humiliate him and even harm him; but were ç
humbled in the end sincethe Lord was on his side. They were obliged ç
to accept his greatness and honour him.
As in the lives of many other saints, miracles are said to have happened ç
in hislife also. He died when the wall he was building, along with ç
other workmen, collapsed. His sam<193>dhi (grave) is still to be seen ç
at Pa<207><195>har<193>pura, opposite to that of N<193>mdev, another ç
great saint who was his contemporary. He has left some nice abha<209>gas ç
(devotional songs in Mar<193><219>hi language) in which he describes ç
his travails due to social prejudices and the acts of grace by God.
See <MS>ABHA<177>GAS<D> and <MS>N°MDEV.<D>
@NT = consciousness
See <MS>CAITANYA.<D>
@NT = conversion
The word `conversion' derived from the Latin root conversio, means ç
a change of direction, complete reorientation of one's personality, ç
towards God. It is a purely spiritual process of turning away from ç
the mammon and towards God. It has nothing to do with proselytism. ç
Identification with it is a later development.
Whether Hinduism has practised proselytization over the centuries ç
or not, is a moot point. Perhaps not, at least in the aggressive sense. ç
But there is enough evidence in the Hindu religious works indicating ç
a quiet absorption into its folds, of aliens like the `yavanas' and ç
`mlecchas,' considered to be barbaric or less civilized, whenever ç
they have willingly adopted the Hindu ways of life. This process has ç
gone on for almost two thousand years, often unnoticed.
But the problem which has often caused unrest in the Hindu society ç
is that of conversion of the Hindus into the Semitic  religions.  While  it  has  been ç
accepted that socio-economic factors have been largely responsible ç
for this, and efforts have been put in, to rectify the imbalances, ç
the mind of the Hindu reli-gious leaders has also been exercised over ç
their reconversion.
A study of the Hindu religious works, whether of the ancient Br<193>hma<207>as ç
or of the later dharma·<193>stras, shows that reconversion was not ç
an unknown pheno-menon. The sacrificial ceremonies called `vr<193>tya-stomas' ç
were aimed at purifying and bringing back the `vr<193>tyas' (renegades ç
as well as foreigners) into the °ryan fold. The Vi<218><207>u-dharmottara-pur<193><207>a ç
(<MS>A.D.<D> 500) and the Devalasm<216>ti (<MS>A.D.<D> 1000?) give ç
specific instructions for purifying and bringing back into the Hindu ç
fold, those who had been forcibly converted by the `mlecchas' (races ç
like the ·akas, yavanas and pahlavas). During the recent past Mahar<218>i ç
Day<193>nanda Sarasvat<200> (<MS>A.D.<D> 1824-1883) started the `·uddhi' ç
movement which became quite vigorous for some time.
Efforts at reconversion†often called `par<193>vartana' or the return ç
to the original fold†still continue. Standardization of the procedure ç
has also been attempted at. However, the real stumbling block in theprocess ç
has been the rehabilitation of the reconverted people, into the caste- ç
conscious Hindu society.
See also <MS>PAR°VARTANA<D> and <MS><185>UDDHI.
@SPACE = 
@NT = coronation
See <MS>ABHI<186>EKA <D>and<MS> ABHI<186>ECAN®YA.
@SPACE = 
@NT = cosmic mind
See <MS>HIRAØYAGARBHA.
@SPACE = 
@NT = cosmology
This world in which we live, move, and have our being as it were, ç
has been spurring the imagination of philosophers for millennia, about ç
its origin and evolution. It will be an interesting, nay, even fascinating, ç
experience to go through the various accounts of creation given in ç
the Hindu scriptures and philosophical works.
The <184>gveda had dealt with this subject in a few hymns but there ç
is no attempt at giving a cogent theory and well-reasoned philosophy. ç
Before s<216><218><219>i or creation, Deva or God alone existed. He ç
is our father. He desired to create. He manifested this world out ç
of himself and entered into it (vide <184>gveda 10.81.1; 10.5.7). ç
The famous Puru<218>as<220>kta (<184>gveda 10.90) describes the ç
whole creation as having come out of the Puru<218>a or primeval Being, ç
using the allegory of a sacrifice.
Allied Vedic works like the Br<193>hma<207>as hold similar views. ç
The Taitti-r<200>ya Br<193>hma<207>a by implication declares (2.8.9.7) ç
that the Deva is both the material and the efficient cause of this ç
universe. The words `Vi·vakarm<193>' (one, whose work this world is), ç
`Hira<207>yagarbha' (golden egg) and `Praj<193>pati' (lord of beings) ç
have also been used in this work to denote the Creator.
In some of the Vedic accounts of creation, primeval waters form the ç
first product from which subsequent creation takes place. We thus ç
see two streams of thought here: one advocating evolution of the world ç
from God and the other, creation by God. Accounts of creation usually ç
contain accounts of sustenance and dissolution (sthiti and pralaya) ç
also.
@SPACE1 = 
The Upani<218>ads which contain more specific references to creation, ç
generally follow the Vedic thought pattern. Before creation, Brahman, ç
also called °tman or Sat, alone existed. It desired to become many ç
and created tejas or fire, ap or water and anna or earth. They are ç
the three fundamental elements from which the whole creation came ç
out (vide Ch<193>ndogya Upani<218>ad 6.2). Some other Upani<218>ads ç
trace the evolution of the world from the °tman through the pa<210>cabh<220>tas ç
or five fundamental elements (vide Taittir<200>ya Upani<218>ad 2.1; ç
2.6) and others like the Pra·na (1.4), through the creation of matter ç
and spirit (rayi and pr<193><207>a). There are also accounts according ç
to which the individual souls have sprung from Brahman like sparks ç
from the fire (Mu<207><195>aka Upani<218>ad 2.1.1). The idea that ç
Brahman, having created the world, has entered into it and controls ç
it from within, is also advocated (Taittir<200>ya Upani<218>ad 2.6).
The epics and the pur<193><207>as give their own, variegated, accounts ç
of creation. In one pattern of descriptions, Vi<218><207>u or N<193>r<193>ya<207>a ç
brings forth Brahm<193> (the four-faced creator) who subsequently ç
creates the various worlds (numbering 3 or 7 or even 14) and their ç
denizens out of himself. In another set of descriptions, N<193>r<193>ya<207>a ç
creates a golden egg (Hira<207>yagarbha) which starts floating on ç
the primeval waters. He himself animates it, breaks it into two, forming ç
the earth and heaven. The Puru<218>a or Praj<193>pati that comes out ç
of it then creates all beings. The Creator dividing himself into two, ç
the male and the female principles, and their union giving rise to ç
the whole creation is also found in some descriptions. In fact this ç
theory is based on similar descriptions found in Upani<218>ads like ç
the B<216>had<193>-ra<207>yaka (1.4.2-4).
@SPACE1 = 
The <186>a<195>-dar·anas or the six philosophical systems, also discuss ç
this question and give their own theories. The Ny<193>ya and Vai·e<218>ika ç
schools state that ®·vara or God creates the world out of the eternal ç
substances like atoms, space, time, ether, mind and souls. He is also ç
responsible for the sustenance and dissolution of the world. The S<193><209>khya ç
and the Yoga systems posit the theory that prak<216>ti or primeval ç
nature (consisting of the three gu<207>as of sattva, rajas and tamas) ç
evolves by stages into this world due to the will of ®·vara (God) ç
and the presence of the puru<218>as or individual souls. This theory ç
is echoed in some of the pur<193><207>as also. The P<220>rva-m<200>m<193><221>s<193> ç
system considers the world and souls to be eternally there†neither ç
created nor destroyed†but regulated by karma (unseen effects of actions ç
done).
The Ved<193>nta system just organizes the philosophy of the Upani<218>ads. ç
The Advaita Ved<193>nta of <185>a<209>kara (<MS>A.<|>D.<D> 788-820) ç
considers the world as an illusory appearance in Brahman, the real ç
substratum. Though the general theory of creation given in the Upani<218>ads ç
is accepted, it is given only an empirical status. The theistic schools ç
of Ved<193>nta, of R<193>m<193>nuja (<MS>A.D.<D> 1017-1137) and of ç
Madhva (<MS>A.D.<D> 1197-1276) on the other hand, accept the reality ç
of creation and the created world.
@SPACE1 = 
It is thus seen that there are so many varieties and types of description ç
of the creation process that it is difficult to put forward any definite ç
theories. However, the thought pattern revealed in the <184>gveda ç
and developed in the Upani<218>ads may be treated as more authentic ç
and more universally accepted than others. Summarized briefly, it ç
states that God the Absolute, creates theworld out of himself, out ç
of his own will, sustains it and rules over it, and dissolves it at ç
the end of a cycle. This cycle of creation, sustenance and dissolution ç
goes on eternally.
The whole purpose of creation is to give the j<200>vas or the individual ç
souls in bondage, one more chance for redemption and liberation from ç
transmigration. This being the main theme of Hindu philosophy and ç
religion, it has not paid much attention to the details of the process ç
of creation.
@NT = cow
Belief in the sanctity of the cow has been a basic tenet in Hinduism ç
since the ancient days. Though sacrifice of a cow or a bull and eating ç
its flesh were present in the remote past, even by the time of the ç
<185>atapatha Br<193>hma<207>a its sacredness had been recognized ç
and eating its flesh prohibited. The <184>gveda calls the cow `aghny<193>' ç
(`not fit to be killed') and praises it highly (vide 4.1.6; 8.69.2). ç
The fact that the bull and the cow were the very centre of the agricultural ç
society of the Vedic °ryans and that milk and milk-products were used ç
in sacrificial rites, must havebeen largely responsible for this ç
prohibition.
The epics and the pur<193><207>as have showered high encomiums on ç
the cow and gifting it (`god<193>na'). Cows on earth have been described ç
as the `daughters' of the celestial cow `Surabhi' or `K<193>madhenu'. ç
All the gods are said to reside in its various limbs. The cow is considered ç
to be so pure that in certain religious rites, the performer has to ç
live and sleep in the cow-pen for a specified period. `Pa<210>cagavya' ç
(a mixture of the five products of a cow, viz., milk, curds, ghee, ç
dung and urine) is considered holy and is consumed during certain ç
religious rites, especially of an expiatory nature.
The earth has often been compared to a cow. In the mythological works, ç
whenever any serious trouble arises on earth, she is said to assume ç
the form of a cow and approach its saviour, either God or a great ç
king. P<216>thu, an incarnation of Vi<218><207>u and a great king, ç
is said to have `milked' the `cow' of this earth and obtained from ç
it, corn, vegetables and other items of food. (Hence<|> the<|> name ç
`p<216>thv<200>'† daughter of P<216>thu†for the earth.)
As part of the funeral rites, a cow is gifted away or let off. It ç
is called `anustara<207><200>' (`that which helps in crossing'). It ç
is believed to help the dead person cross the fetid river Vaitara<207><200>, ç
flowing between the human world and that of Yama, the god of death.
Association of Lord K<216><218><207>a with the cows is well-known ç
to all students of Hindu religious  literature.  This  has  further ç
enhanced their sanctity, especially in the minds of the masses.
The Brahmavaivartapur<193><207>a describes in great detail, the ç
`Goloka' (cow-heaven), the abode of Lord K<216><218><207>a, far above ç
theBrahmaloka (the abode of Brahm<193>) itself.
@NT = creation
See <MS>COSMOLOGY.
@NT = cremation
History reveals that the disposal of the bodies of the dead has been ç
practised by mankind in several ways: cremation, burial, consigning ç
it to water, leaving it on mountain tops or tree tops to be devoured ç
by animals and vultures, and embalming. Out of these the first two ç
have been most widely practised.
In India, cremation of dead bodies has been existing since very ancient ç
days. Bodiesof dvijas (`twice-born') (See <MS>DVIJA<D>.) who had ç
kept duly consecrated Vedic fires (such people were called `<193>hit<193>gnis') ç
were invariably cremated with the Vedic fires, the various wooden ç
sacrificial vessels and implements being placed on the various limbs ç
of the dead body, at the time of cremation. Those who had not kept ç
the Vedic fires were cremated with ordinary fire.  The  practice  of  dismembering  a ç
she-goat or a cow, technically called `anustara<207><200>'  and  keeping  its  various ç
severed parts on the dead body at the time of cremation was also there, ç
but was given up in later times. (The animal was let off or gifted ç
away.) The whole process of cremation was an elaborate ritual.
Dead bodies could be carried on the shoulders by the male relatives ç
or could be transported by a cart. According to one account, a great ç
deal of noise is to be made by means of instruments like the cymbols, ç
while carrying the dead body to the crematorium. Though weeping was ç
allowed during the time of cremation, it was prohibited after the ç
cremation was over.
@SPACE1 = 
During a period when transport and communication were difficult, people ç
who would go out travelling either for pilgrimage or for business ç
or for any other purpose, had to face many hardships. So, when someone ç
who went out, was heard to have died (and the body could not be recovered), ç
cremation used to be done to an effigy prepared out of pal<193>·a ç
(Butea frondosa) leaves, flour of barley and woollen thread. This ç
was called `<193>k<216>ti- dahana'  (`burning  the  effigy').  Such ç
cremation of an effigy was done to people who were not heard of for ç
twelve years or more also. If by chance they returned later, they ç
had to undergo all the sacraments like j<193>takarma, n<193>makara<207>a ç
etc.
The ashes and bones were collected after cremation<192>this was called ç
`asthi-sa<210>cayana'<192>and used to be either interred in a suitable ç
place or consigned to a sacred river or sea.
See also <MS>ANTYE<186><187>I.<D>
@NT = crime and punishment
The problem of crime and the system of punishment have existed right ç
from the days human beings began to live in organized societies. The ç
contribution of Hindu jurisprudence in this regard, through its great ç
saints like Gautama, °pastamba, Baudh<193>yana and Manu†all of whom ç
lived centuries before the Christian era†and a galaxy of other writers ç
right up to <MS>A.D.<D> 1000 or more, is consider-able, both in quantity ç
and quality.
One peculiar feature of this problem in India has been that social ç
life and religious life being inextricably mixed up, it often becomes ç
difficult to distinguish a crime from a sin or vice versa. Crimes ç
should be punished but sins are to be expiated. All crimes are sins, ç
but all sins are not crimes. Stealing is both a crime and a sin whereas ç
neglect of his duties by a Vedic student is a sin but not a crime. ç
A sin becomes a crime if it has social repercussions and impinges ç
on the solidarity of the social system.
@SPACE1 = 
The dharma·<193>stras (lawbooks guiding various aspects of socio-religious ç
life of the Hindus) recognize the equality before law. None who committed ç
a crime was exempt from punishment. Though details of punishments ç
for various crimes have been meticulously worked out, the primary ç
object was to protect the people of the society from the criminals ç
and deter the potential criminals from committing such crimes.
Trials used to be conducted directly by the king himself or by the ç
judges duly appointed by him. These judges had to be br<193>hma<207>as ç
of unimpeachable character. However, though the judges could pronounce ç
the sentence, it was for the king to execute the same.
The effect of the var<207>a-cum-caste system on punishments meted ç
out for thesame crime is clearly discernible in these writings. However, ç
two diametrically opposite schools are met with. If some award more ç
severe punishments to the members of the higher castes, since they ç
ought to know better, others give less. The argument in the latter ç
case is that being culturally more refined, they are psychologically ç
more sensitive, and even lesser punishment will have the desired effect. ç
After all, does not punishment entail a social stigma too? Even then, ç
punishment awarded to the ·<220>dras for listening to the Vedas or ç
trying to learn them†which was considered to be a great offence<192>was ç
extremely severe.
Whenever a criminal was punished, especially in the case of the higher ç
caste groups, the offender was also to expiate himself through appropriate ç
rites and discipline. This would render him fit for social intercourse ç
later. If this was not done,<W1%56><D%0>more severe punishments would ç
follow.
@SPACE1 = 
Cognizable offences listed in these lawbooks are legion: defamation, ç
stealing, robbery, usurpation, sexual crimes of various types and ç
degrees, treachery, physical assaults, murder, criminal abortion, ç
offences against the State through espionage and sabotage, and so ç
on.
Punishments were generally classified into four groups: v<193>gda<207><195>a ç
(censure), dhigda<207><195>a (severe rebuke), dhanada<207><195>a (fines) ç
and vadhada<207><195>a (corporal punishment). They could be awarded ç
separately or jointly. The first two were for light offences only. ç
Fines could be light or heavy, confiscation of property being the ç
last word. However, even in such cases, the main tools and implements ç
of workers, artisans, warriors, musicians etc., were not touched. ç
The king was prohibited from appropriating the confiscated property ç
to himself. Corporal punishment varied from simple flogging up to ç
dismemberment of limbs or death. Punishments to women and old people ç
or weaklings, were of lesser intensity. But, even br<193>hma<207>as ç
and women were put to death if found guilty of heinous crimes. Offences ç
of children below specified ages were not recognized. The  sins  of  their  wrongdoings  were ç
declared to go to their parents. Repeaters of crimes would invite ç
more and more severe punishments. Public disgrace through branding ç
and shaving, or parading in the public streets was also resorted to, ç
for certain crimes.
Viewing an offence as venial or mortal, varied from writer to writer ç
or even according to times. Chronologically speaking, earlier lawgivers ç
were more severe whereas the later ones were more lenient.
@SPACE1 = 
See<MS> P°TAKA<D> and <MS>PR°YA<185>CITTA<D> also.
@NT = c<220><195><193>kara<207>a
@N1 = (`making the tuft')
@NT = c<220><195><193>karma
@N1 = (`rite of preparing the tuft')
Also called `caula,' this is the eighth of the <218>o<195>a·a-sa<221>sk<193>ras ç
(sixteen sacraments) which every Hindu of the first three castes was ç
to undergo. It is actually the first tonsure of the child and hence ç
a religious act. It should be done after the child completes one year, ç
but before three years. The age-limit was gradually raised to seven ç
years. In the modern days it is often done just before the upanayana ç
(investiture with the sacred thread) ceremony.
This rite is to be performed on an auspicious day, when the moon is ç
in conjunction with the constellation Punarvasu, but avoiding the ç
ninth day of the lunar month. The principal act of this rite is the ç
cutting of the hair of the child by its father to the chanting of ç
appropriate Vedic mantras. (The barber will of course do the rest.) ç
Performance of homa (offerings in duly consecrated fire), feeding ç
the br<193>hma<207>as and receiving their blessings are the other ç
items of the rite. The hair that is cut off should be disposed off ç
in such a way that none will have any access to it (for e.g., burying ç
it in the cowpen, consigning it into a pond etc.).
The number and position of the ·ikh<193>s (tufts of hair) varied according ç
to the family traditions. It was generally kept at the eddyof hairs ç
on the top of the head. Works on °yurveda (the science of life and ç
longevity) state that the ·ikh<193> protects the vital artery on the ç
head and is conducive to long life.
This rite could be performed for girls also but without the Vedic ç
mantras. Even in<|>the modern days, the practice of removing the first ç
hair of the girl-child exists.
@NT = C<220><195><193>l<193>
C<220><195><193>l<193> was the queen of <185>ikhidhvaja of Ujjayin<200>. ç
Endowed with physical beauty and accomplishments in various arts and ç
sciences, she spent a happy life with her husband for a few years. ç
The process of aging set her thinking about what is really permanent ç
and unchanging in life. Through her own struggles she was able to ç
attain spiritual enlightenment and succeeded also in teaching the ç
same to her husband. The story is dealt with in detail in the Yogav<193>si<218><219>ha, ç
a version of R<193>m<193>ya<207>a, intended to teach extreme form ç
of Advaita Ved<193>nta.
@NT = Cyavana
@N1 = (`one who dropped down')
Cyavana was a great sage, the son of another great sage Bh<216>gu ç
and Pulom<193>. He got this name since he was aborted from the mother's ç
womb. When Pulom<193> was threatened by a demon and was hence struck ç
with fear, the baby dropped down. But the baby reduced the demon to ç
ashes just by staring at him!
Once, when Cyavana was sitting in meditation for many years at a stretch ç
and an anthill had grown over him, Sukany<193>, the young daughter ç
of the king <185>ary<193>ti, happened to come there. Out of curiosity ç
she pierced the holes in the anthill from which a strange light was ç
emanating. This struck the sage blind. As an expiation, the king had ç
to give Sukany<193> in marriage to the sage and she had to serve him. ç
She however gladly accepted her fate and sincerely served her husband. ç
Due to her power of chastity she was able to win the grace of A·vins ç
(twin deities, who are physicians of gods) who restored the youth ç
of the sage Cyavana. He, out of gratitude, got them the right of sharing ç
sacrificial offerings along with Indra and other gods.
@END = 
