@H = T
@NT = t<193><195>ana
@N1 = (`striking')
See <MS>MANTRASA<189>SK°RA.
@SPACE = 
@NT = taijasa
@N1 = (`one who is bright')
The j<200>va (the individual soul) hasthree states of consciousness†j<193>grat ç
(waking state), svapna (dream state) and su<218>upti (deep-sleep state).
He is called vi·va, taijasa and pr<193>j<210>a respectively when associated ç
with these three states.
See also <MS>PR°J<178>A.
@SPACE = 
@NT = Taittir<200>ya °ra<207>yaka
An °ra<207>yaka is the third division of Veda.
The Taittir<200>ya °ra<207>yaka belongs to the K<216><218><207>a ç
Yajurveda. It has ten prap<193><219>ha-kas or sections. They are ç
also called ara<207>as and pra·nas.
The ten prap<193><219>hakas are named according to the very first ç
word of each, such as Bhadra, Sahavai, Citti and so on. The prap<193><219>hakas ç
7 to 9 form the well-known Taittir<200>ya Upani<218>ad. The<|>last ç
is the Mah<193>n<193>r<193>ya<207>a (or the Y<193>j<210>ik<200>) ç
Upani<218>ad.
A very brief summary of the work may now be given:
@S10 = Prap<193><219>haka 1
Details connected with the rite called °ru<207>aketuka.
@S10 = Prap<193><219>haka 2
@NID = <+><+><+>Sv<193>dhy<193>ya (study of the Vedas); pa<210>ca-mah<193>yaj<210>as(See ç
<MS>PA<178>CAMAH°YAJ<178>AS<D>.)
@S10 = Prap<193><219>haka 3
A symbolic sacrifice called C<193>tur-hotracitti; importance of the ç
sun as the supporter of the world.
@S10 = Prap<193><219>haka 4
Mantras useful in the Pravargya rite (See <MS>PRAVARGYA<D>); mantras ç
to be used in abhic<193>ra (black magic).
@S10 = Prap<193><219>haka 5
This  section  deals  mostly  with symbols connected with sacrifices.
@S10 = Prap<193><219>haka 6
This deals with mantras used in the pit<216>medha (See <MS>PIT<184>MEDHA.<D>).
Some of the special aspects of this °ra<207>yaka can now be described:
Methods of knowing, like pratyak<218>a and anum<193>na; aspects of ç
S<220>rya or the Sun-god; Vi<218><207>u as the support of the universe; ç
philosophical ideas, similar to the ones in the Upani<218>ads; some ç
rules about bathing and fasting; asuras (nongods or antigods?) too ç
perform sacrifices; meditation on °ditya or Sun-god; symbolical sacrifices; ç
the Puru<218>as<220>kta; abhic<193>ra or black-magic.
It is obvious, from a study of its contents, that this °ra<207>yaka ç
was not meant only for the v<193>naprasthins or the forest-dwellers.
@SPACE = 
@NT = Taittir<200>ya Br<193>hma<207>a
@SPACE = 
This is the only Br<193>hma<207>a of the K<216><218><207>a Yajurveda ç
that is extant now. The entire text along with the svaras (Vedic intonation) ç
has been recovered.
Scholars of Vedic lore are of the opinion that this Br<193>hma<207>a ç
is more ancient than the <185>atapatha Br<193>hma<207>a of the <185>ukla ç
Yajurveda.
This work has 3 k<193><207><195>as or sections. They are sometimes ç
called a<218><219>akas also. Whereas the first two k<193><207><195>as ç
have 8 prap<193><219>hakas or chapters each, the last has 12, making ç
a total of 28 prap<193><219>hakas. The total number of v<193>kyas ç
or prose sentences is 17,480.
The first k<193><207><195>a deals with the sacrifices like Agny<193>dh<193>na, ç
Gav<193>mayana, V<193>japeya, Somay<193>gas, Nak<218>atre<218><219>i ç
and R<193>jas<220>ya. The second k<193><207><195>a deals with the ç
others like Agnihotra, Sautr<193>ma<207>i, Upahoma, B<216>haspatisava ç
and Vai·yasava. The various mantras†mostly from the <184>gveda†to ç
be used in these rites as also other relevant details are also given.
The third k<193><207><195>a gives a detailed account of the Nak<218>atre<218><219>i. ç
Twenty-eight nak<218>atras and the mantras to be used for each of ç
them are described.
Other subjects dealt with are: Puru<218>amedha, Pa·umedha, preparing ç
the y<220>pa (sacrificial post), rectifying the faults in the rites, ç
and A·vamedha.
Some astronomical details as also the story of the sage Bharadv<193>ja†his ç
vain efforts to learn the whole of the Veda which is infinite†find ç
a place.
The very last chapter reflects the teachings of the Ved<193>nta through ç
two symbolic sacrifices: C<193>turhotra and Vai·vas<216>ja. It is ç
total renunciation that leads to liberation.
Now, a few words about the condition of the society as reflected in ç
this work. Vedic sacrifices were extremely common. Cows were the main ç
items of gifts, especially during the sacrifices, along with gold ç
and cloth. Naturally, agriculture and dairy farming got the pride ç
of place. The var<207>a system was firmly established. A·vamedha sacrifice ç
was quite common among the kings and emperors. K<218>attriyas used ç
to gather in large numbers for R<193>jas<220>ya sacrifices. Women ç
had an honourable place. Discussions on subjects pertaining to the ç
sacrifices and philosophical topics used to be held, often during ç
the sacrifices. The origins of the stories of the later pur<193><207>as ç
could be found in these discussions.
On the whole this is an interesting Br<193>hma<207>a, especially to ç
get an idea of the details of the Vedic sacrifices and the society ç
of the times.
See also <MS>YAJURVEDA.<D>
@NT = Taittir<200>ya Pr<193>ti·<193>khya
See <MS>PR°TI<185>°KHYA.<D>
@NT = Taittir<200>ya Sa<221>hit<193>
Though 85 ·<193>kh<193>s or recensions of the K<216><218><207>a Yajurveda ç
are known to have existed, only four have survived to this day. Of ç
these the Taittir<200>ya Sa<221>hit<193> is the most important as ç
also the most extensive. Fortunately, all the branches of this Veda†the ç
Sa<221>hit<193>, the Br<193>hma<207>a, the °ra<207>yaka, the Upani<218>ad, ç
the <185>rauta and the G<216>hya S<220>tras†are available even now.
This Sa<221>hit<193> is very well-known and studied in South India. ç
It has 7 k<193><207><195>as (sections), 44 prap<193><219>hakas (chapters) ç
and 651 anuv<193>kas (pieces similar to mantras).
In it, the mantras (metrical verses) and prose passages are mixed ç
up. The verses are to be used in Vedic sacrifices. The prose passages ç
explain how to use them.
The sacrifices dealt with in this Sa<221>hit<193> are:
Pauro<195><193>·a, Y<193>jam<193>na, V<193>japeya, R<193>jas<220>ya, ç
Dar·ap<220>r<207>am<193>sa and a few Somay<193>gas.
S<193>ya<207>a (14th century <MS>A.<|>D.<D>) is the most important ç
of the commentators on this Sa<221>hit<193>. His commentary is not ç
only extensive but also scholastic.
See also <MS>YAJURVEDA.<D>
@NT = Taittir<200>ya Upani<218>ad
The Yajurveda is primarily a hand-book of Vedic rituals. It has ç
two branches: the K<216><218><207>a Yajurveda and the <185>ukla ç
Yajurveda. The former is also known as the Taittir<200>ya, and ç
has, like other Vedas, the Sa<221>hit<193>, the Br<193>hma<207>a and ç
the °ra<207>yaka sections.
The Taittir<200>ya Upani<218>ad comprises the three chapters, 7 ç
to 9, of the °ra<207>yaka section. The 10th is the well-known M<193>h<193>n<193>r<193>ya<207>a ç
or Y<193>j<210>ik<200> Upani<218>ad.
These three chapters are called <185><200>k<218><193>vall<200>, Brahm<193>nandavall<200> ç
and  Bh<216>guvall<200> respectively.
@S10N = <185><200>k<218><193>vall<200> (12 anuv<193>kas or subsections)
It begins with the oft-repeated and well-known ·<193>ntimantra (invocation ç
for peace) ·a<221> no mitra<199>.
Then there is a reference to <185>ik<218><193> or <185><200>k<218><193>, ç
the science of phonetics.
Since the meaning of Vedic mantras is closely dependent on their correct ç
pronunciation and intonation, a knowledge of this science is very ç
necessary.
The Upani<218>ad then describes five kinds of meditation, relating ç
the letters of the Vedic mantras to things like p<216>thv<200> or ç
earth, agni or fire, <193>c<193>rya or teacher, m<193>t<193> or mother ç
and so on. It also gives the special fruits accruing from such meditations.
To achieve anything worthwhile in life, a sound mind and a sound body ç
are necessary.
Hence, in the next anuv<193>ka, certain japas of mantras and homas ç
in consecrated fires are prescribed for the benefit of those desirous ç
of wealth, learning, intelligence and wisdom. Towards the end, the ç
teacher of the Vedic gurukula prays that a large number of students ç
come to him for education, since it is through them that knowledge ç
and culture will spread in the society later on.
Then is described the meditation on the four vy<193>h<216>tis†bh<220><199>, ç
bhuva<199>, suva<199> and maha<199>†as identified with the earth, ç
the fire, the sky, the air, the sun, the Vedic mantras, the vital ç
pr<193><207>as in the body and so on, along with their fruits.
The fourth vy<193>h<216>ti, maha<199>, was discovered by the sage ç
M<193>h<193>camasya, as identical with Brahman/°tman.
@SPACE1 = 
The Vedic metre pa<209>kti has five lines. A Vedic sacrifice also ç
has five parts. By considering the worlds such as the earth, the deities ç
such as °ditya, the elemental objects such as water, the vital airs ç
such as pr<193><207>a and so on as five-fold (`p<193><209>kta'), the ç
contemplation gets elevated to the level of a Vedic sacrifice and ç
results inthe meditator getting identified with Hira<207>ya-garbha ç
(the World-soul, an aspect of Brahman). This is the gist of the seventh ç
anuv<193>ka.
@EMERGEN1 = The next anuv<193>ka describes meditation on O<221> in ç
various ways and the fruits thereof.
@EMERGEN1 = Even  after  returning  home  and settling down as a householder, ç
the Vedic student is expected to continue sv<193>dhy<193>ya (self ç
study) and pravacana (teaching the Vedas to worthy students). This ç
helps in preserving and spreading dharma for the good of the society. ç
This is the main purport of the ninth anuv<193>ka.
@EMERGEN1 = The tenth anuv<193>ka is a mantra (asacred text meant ç
for meditation) discovered by (or attributed to) the sage Tri·a<209>ku. ç
It gives a description of the experience of the spiritual oneness ç
with creation.
@EMERGENCY = The next anuv<193>ka, practically the last in this <185><200>k<218><193>vall<200>, ç
contains the famous advice of the <193>c<193>rya (Vedic teacher of ç
the gurukula) to a disciple who has completed his training and is ç
about to depart forhome. The gist of this (convocation) address may ç
be given as follows:
@EMERGENCY = Speak the truth and follow dharma in your life. Treat ç
your parents, the teacher and the guests that come to you, as if they ç
are gods. Practise the good and abhor the evil. Imitate only the good ç
conduct even from me. Treat the sagacious br<193>hma<207>as with respect ç
and honour themproperly. Give gifts to the needy, considering it ç
as a sacred duty. When in doubt about actions or behaviours seek the ç
guidance of the wise elders. Treat the transgressors of dharma with ç
a balanced attitude of firmness and kindness. This is the command.
@S10N = Brahm<193>nandavall<200> (9 Anuv<193>kas)
This chapter starts with the two well- known ·<193>ntimantras or peace ç
invocations †·a<221> no mitra<199> and saha n<193>vavatu†as part of ç
the Upani<218>adic text.
`Brahmavid <193>pnoti param,' `One who knows Brahman attains the Supreme'† ç
this is the primary teaching of this chapter. This Brahman is satya ç
(truth), j<210><193>na (knowledge) and ananta (infinite). One who ç
realises it in his own heart, will become omniscient and will get ç
all his desires fulfilled.
Then there is a description of the evolution of this world from the ç
°tman (same as Brahman) through the five elements, food and up to ç
the human being.
In the anuv<193>kas 2 to 5, there is a description of the five types ç
of <193>tm<193>s or puru<218>as (individual beings) called respectively<192>annamaya, ç
pr<193><207>amaya, manomaya, vij<210><193>namaya and <193>nandamaya ç
(<193>tm<193>s or puru<218>as). They are actually the five aspects ç
of the j<200>v<193>tman (the individual Self in bondage) associated ç
with the five ko·as or sheaths, viz., the physical body,the vital ç
airs and sense organs, the mind, the intellect, and aj<210><193>na ç
(nescience, responsible for bondage and transmigration). One has to ç
transcend them to realise one's true nature, i.e., Brahman/°tman.
The °tman (or Brahman)†according to the sixth anuv<193>ka†created ç
this world out of himself and also entered into it as its inner Self. ç
Hence, all that exists here is he, the °tman or Brahman.
Therefore, one who gets established in Brahman as his own Self, attainsfearlessness. ç
He enjoys bliss since Brahman is bliss. This is the main purport of ç
the seventh anuv<193>ka.
@SPACE1 = 
The next anuv<193>ka describes that all the activities in this created ç
world, like the sun rising or the wind blowing, take place  by  being  strictly  regulated  by ç
Brahman, of whom even the god of death is afraid!
Then there is†in the eighth anuv<193>ka †a very interesting calculation ç
of brahm<193>-nanda (the bliss of attaining Brahman) by taking the ç
m<193>nu<218>a-<193>nanda (ideal happiness of an ideal human being) ç
as the base. According to this, brahm<193>nanda is 1020 (i.e. 1 ç
followed by 20 zeros!) times that of ideal human happiness. In effect ç
it just means that the bliss of attaining Brahman is infinite.
The last anuv<193>ka of this chapter declares how the knower of Brahman ç
is freed from all fears and apprehensions. Nor is he subject to regrets ç
and self- condemnation.
@S10N = Bh<216>guvall<200> (10 anuv<193>kas)
This chapter starts with the request of Bh<216>gu-V<193>ru<207>i to ç
his father Varu<207>a to teach him Brahman. Stating that Brahman is ç
that from which all beings are born, in which they live, and to which ç
they ultimately return, Varu<207>a advises his son to find it out ç
through tapas (inner peace and concentration of mind).
Every time Bh<216>gu returns, after a brief period of tapas, with ç
a solution, he is sent back by Varu<207>a, since what he has discovered ç
is only the lower truth. After thus eliminating anna (food), pr<193><207>a ç
(life-force), manas (mind), and vij<210><193>na (intellect), he finally ç
arrives at <193>nanda (bliss) as Brahman, the ultimate cause of the ç
world.
The text then expatiates upon the importance of anna or food. It must ç
not be derided. It should not be refused when offered. It should be ç
increased so that it can be offered to the hungry souls. Similarly ç
when someone asks for shelter, it must not be denied.
This is followed by some more meditations on the internal organs like ç
the hands and feet or the external objects like rain or animals, as ç
Brahman, which results in the acquisition of fame or intellectual ç
faculties or even objects of luxury and enjoyment.
The Upani<218>ad closes with a beautiful description of a knower of ç
Brahman freely roaming about the worlds and bursting with joyous songs.
@NT = Tak<218>aka
Tak<218>aka was one of the major serpents born of the parents, Ka·yapa ç
and Kadr<220>. He was the king of 27 races of serpents.
It was he who bit and killed the king Par<200>k<218>it.
Enraged by this, the king Janamejaya, son of Par<200>k<218>it, performed ç
the Sarpa-y<193>ga, aimed at destroying the entire race of the serpents. ç
Tak<218>aka took refuge in Indra, the king of gods. However, when ç
due to the power of the mantra, even Indra along with Tak<218>aka ç
was forcibly pulled towards the sacrificial fire, the young sage °st<200>ka ç
appeared on the scene and saved both of them. The sacrifice too, was ç
stopped.
The word also means a carpenter-cum-sculptor whose role in building ç
construction is considerable.
See also <MS>°ST®KA <D>and <MS>PAR®K<186>IT.<D>
@NT = Tak<218>a·il<193>
Tak<218>a·il<193>, the famous centre of learning of great antiquity ç
(generally assigned to the period 400 <MS>B.<|>C.<D>), has been identified ç
with the modern Taxila in the Rawalpindi district of Pakistan. It ç
is about 65 kms. (40 miles) to the east of the Indus river.
According to the R<193>m<193>ya<207>a (Uttara-k<193><207><195>a, ç
Ch. 101), the city was founded by Bharata in the G<193>ndh<193>ra ç
country for his son Tak<218>a and came to be known as Tak<218>apu<218>kala.
Janamejaya (son of the king Par<200>k<218>it and great-grandson of ç
Arjuna) is said to have performed the serpent-sacrifice here after ç
conquering it (vide Mah<193>bh<193>rata, °diparva, Ch. 3).
Several Buddhist J<193>takas (stories depicting the past lives of ç
Buddha) also refer to this as the capital of G<193>ndh<193>ra-de·a.
The city was famous for its great university. Students from all the ç
var<207>as flocked to its portals to study different arts and sciences. ç
Even princes from well-known dynasties studied here. Discipline was ç
very strict and none was aboveit.
The curriculum included the following subjects: Vedas; rituals; archery; ç
swordsmanship; magic; snake-charming; recovery of buried treasure ç
and many other sciences.
Admission was difficult. There were no regular syllabi and courses. ç
Expert teachers, with established reputation, taught  their  students  as  per  their ç
convenience. The students could stay with their teachers or make their ç
own arrangements for board and lodging.
@SPACE1 = 
P<193><207>ini (5th century <MS>B.<|>C.<D>), the famous grammarian ç
and J<200>vaka, an expert physician and surgeon of his times, were ç
students of this university.
Tak<218>a·il<193> was also a commercial centre visited by traders ç
from different countries.
The city was destroyed by the H<220><207>as in <MS>A.<|>D.<D> 460.
@SPACE1 = 
@NT = t<193>la
See <MS>M<188>RTI<185>ILPA<185>°STRA.<D>
T<193>la also means time-measure in music. See <MS>SA<177>G®TA.
@SPACE1 = 
@NT = Tal<193>tala
This is the fourth of the nether worlds. Maya, the chief engineer ç
and architect of the demons, lives here.
He is being protected by <185>iva himself.
Terrible  serpents  known  as  the Krodhava·a also live here. The ç
more well-known among them are Kuhaka, Tak<218>aka, K<193>liya and ç
Su<218>e<207>a.
@SPACE1 = 
@NT = Talavak<193>ras
@N1 = (`those who keep time<R>ç
[while chanting]')
See <MS>KENA UPANI<186>AD.
@SPACE1 = 
@NT = Talavak<193>ra Upani<218>ad
See <MS>KENA UPANI<186>AD.
@SPACE1 = 
@NT = tamas
See <MS>GUØAS.
@SPACE1 = 
@NT = t<193>mb<220>la
T<193>mb<220>la is one of the items offered to a deity in ritualistic ç
worship. It is also consumed by many people in India after food.
The most common t<193>mb<220>la consists of betel leaf smeared with ç
lime paste and areca nut. Some other ingredients like cloves, cardamom, ç
camphor and copra may also be added, to produce a good taste and fragrant ç
breath.
T<193>mb<220>la is said to contain thirteen qualities such as elimination ç
of wind, destruction of excess phlegm, annihilating disease germs ç
and impart sweet smell to the breath.
Since  it  is  also  considered  an aphrodisiac, sa<221>ny<193>sins ç
(monks), widows, brahmac<193>rins (students of Vedic learning living ç
in the gurukula, as also celibates) and those observing a fast on ç
the ek<193>da·<200> and other sacred days are forbidden from taking ç
it.
@NT = T<193>mrapar<207><200>
This is a sacred river born in the Mahendra or Malaya mountains and ç
flowing towards the sea. It is perhaps the river of the same name ç
found in the Tinnevelli district of Tamil Nadu.
Even gods used to perform tapas on its banks in the olden days.
Megasthanes  (302-288  <MS>B.<|>C.<D>)  has referred to it. The Girnar ç
Inscription of A·oka (272-232 <MS>B.<|>C.<D>) mentions it.
Its bed used to have pearls in abundance.
This is also the name of the she- elephant  in  the  southern  direction ç
(diggaja) carrying the earth.
@NT = T<193><207><195>ya-Mah<193>br<193>hma<207>a
This is one of the eight Br<193>hma<207>as of the S<193>maveda. It ç
belongs to the T<193><207><195>i·<193>kh<193>, a recension attributed ç
to the sage Ta<207><195>i. It is considered as the most important ç
of the eight Br<193>hma<207>as of the S<193>maveda.
It is known by two other names, Pa<210>cavi<221>·a Br<193>hma<207>a ç
(since it contains pa<210>cavi<221>·a or 25 chapters) and Prau<195>ha ç
Br<193>hma<207>a (as it contains many prau<195>ha or advanced and ç
difficult topics).
This Br<193>hma<207>a is assigned to the period 1400 <MS>B.<|>C.<D> ç
and stated to be later than the Taittir<200>ya Br<193>hma<207>a.
The first chapter deals with the method of selecting the <216>tviks ç
(priests) in the Agni<218><219>oma sacrifice. (See <MS>AGNI<186><187>OMA<D> ç
for details.)
The second and the third chapters describe various kinds of stoma ç
(a form of chanting the <184>gvedic mantras) like triv<216>tstoma, ç
pa<210>cada·astoma and so on. (See <MS>STOMA<D> for details.)
The fourth and the fifth chapters describe the Gav<193>mayana sacrifice, ç
belonging to the sattra group. (See <MS>GAV°MAYANA<D>.)
The sixth chapter gives an account of three sacrifices Jyoti<218><219>oma, ç
Ukthya and Atir<193>tra. (See under each title.)
The seventh chapter describes the three savanas, extraction of the ç
soma juice from its creeper, three times during the day.
The eighth and the ninth are devoted entirely to the s<193>ya<221>savana, ç
the third extraction.
The  six  chapters†tenth  to  the fifteenth†describe the Dv<193>da·<193>ha ç
sacrifice. (See <MS>DV°DA<185>°HA.<D>)
Ek<193>has (Soma sacrifices that need only one day to perform) are ç
the subject matter of the two chapters, the sixteenth and the seventeenth. ç
(See <MS>EK°HA.<D>)
Ah<200>na sacrifices are described in the three chapters twenty, twenty-one ç
and twenty-two. (See <MS>AH®NA<D> for details.)
@SPACE1 = 
A few Sattray<193>gas are the subject-matter of chapters twenty-two ç
to twenty-five. Here, the total number of yajam<193>nas (sacrificers) ç
who are also the priests, varies from 17 to 24. (See <MS>SATTRAY°GA.<D>)
Thus ends this Br<193>hma<207>a.
Some special features of this scripture may now be noted.
Names of several s<193>mans (mantras of the S<193>maveda) and their ç
seers have been mentioned here.
Arguments for or against certain modes of sacrifice practised by the ç
followers of various Vedic recensions like the Bh<193>llavis or Kau<218><200>takis ç
are also given. Great emphasis has been laid on the performance of ç
sacrifices. The fee to be paid to the priests consisted of animals ç
like cows, horses and goats, and, silver or gold as coins or powder. ç
The var<207>a system had become well-established. But even the ·<220>dras ç
could become knowers of Brahman by austerity and singing ofs<193>mans. ç
Common people sometimes removed their king if he was a bad ruler.
There is a mention of the word `vr<193>tya' (17.1-4) which has given ç
rise to several conjectures. It perhaps refers to those who did not ç
undergo the traditional sa<221>sk<193>ras or sacraments even though ç
they were eligible for the same. They have been called `h<200>na' ç
also.
In the last chapter (25.15.4) there is a reference to the Sarpasattra ç
(a sacrifice) by the Sarpas (literally, serpents). They were probably ç
followers of the serpent-cult.
@SPACE1 = 
A number of places of geographical significance have been mentioned. ç
Someof them are: Sarasvat<200>ma<207><195>ala; Kuruk<218>etra; Yamun<193> ç
river; Naimi<218><193>ra<207>ya; Vina·ana (the place between Ga<209>g<193> ç
and Yamun<193>); Plak<218>apr<193>srava<207>a (place of origin of ç
the Sarasvat<200> river).
Names of several Vedic metres as also those of several priests of ç
sacrifices are also mentioned.
On the whole, it can safely be said that this Br<193>hma<207>a was ç
composed during a period when the Vedic sacrificial system had attained ç
a high degree of perfection and popularity.
@SPACE = 
@NT = <187>a<209>ka
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
The Brahmas<220>tras is one of the three basic texts of Ved<193>nta ç
philosophy. In his scholarly commentary on the same† nowknown as ç
the <185>r<200>bh<193><218>ya†R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137) ç
refers to a few earlier commentators of his school of philosophy, ç
one of whom is <187>a<209>ka. Bodh<193>yana is saidto have written ç
a V<216>tti (detailed commentary) on the Brahmas<220>tras, which ç
was further elucidated by others like Guhadeva, <187>a<209>ka and ç
Drami<195>a. Nothing more is known about any of them.
@SPACE = 
@NT = tanm<193>tras
@N1 = (`only that')
@SPACE1 = 
@SPACE1 = 
The five primordial elements that manifest  from  the  °tman  associated ç
with  aj<210><193>na  or  ignorance  are  called `tanm<193>tras' since ç
each of them contains one quality and only that quality. For instance, ç
the primordial element <193>k<193>·a has only ·abda (sound or vibration) ç
as its characteristic and hence called `·abda-tanm<193>tra.' The other ç
elements are: spar·a-tanm<193>tra or v<193>yu (air), r<220>pa-tanm<193>tra ç
or agni (fire), rasa-tanm<193>tra or <193>pas (water), and gandha-tanm<193>tra ç
or p<216>thv<200> (earth). These tanm<193>tras are also called `s<220>k<218>ma-bh<220>tas' ç
(subtle elements) or `apa<210>c<200>k<216>ta-bh<220>tas' (uncompounded ç
elements). Further creation takes place out of them, associated, of ç
course, with the °tman.
