@NT = Tantras
@SB = 1.	Introduction
It is seen that every major religionof the world has a founder, a ç
scripture and a church. Hinduism is the solitary exception to this ç
general pattern. It does not have a single founder or a single book ç
or a single church, though in it greatreli-gious leaders, religious ç
books and religious monasteries or organisations are legion.
Although  the  Vedas  have  been accepted as the basic scriptures ç
by most of the sects, cults and groups of Hinduism, a number of other ç
religio-philosophical works have appeared over the centuries, many ç
of which have occupied cardinal positions in their cults or sects. ç
The <193>gamas and the tantras form an important category of literature ç
among these.
Originally, the word `tantra' seems to have meant any science or body ç
of knowledge. Gradually, however, it got restricted to a particular ç
class of literature, a literature primarily devoted to thecult of ç
<185>akti or the Divine Mother and containing an amalgam of religion, ç
philosophy,  esoteric  and  occult  rites, astronomy,  astrology,  medicine  and ç
prognostications. In this respect, the tantras resemble the pur<193><207>as. ç
Etymologically the word is derived from its two constituents†`tan,' ç
to spread; `trai,' to protect† and is supposed to mean any work that ç
spreads or dilates upon many matters liketattvas (fundamental principles) ç
and mantras (sacred words and syllables) and through that knowledge ç
affords protection to the votaries.
Whether the tantras have accepted the authority of the Vedas and hence ç
their subservience to them, or, have furrowed their own parallel and ç
independent path, is a moot point. If the stress on mok<218>a (freedom ç
from transmigratory existence) as also the place of honour accorded ç
to the var<207>a-<193>·rama-dharmas (duties based on castes and stations ç
in life) bespeaks oftheir allegiance to the Vedas, other practices ç
like the pa<210>ca-mak<193>ras or ·avas<193>dhan<193> (to be explained ç
later) smackof their close association with an aboriginal, non-Vedic, ç
society. It may, perhaps, be safer to assume that though they might ç
have originated as a parallel tradition distancing themselves from ç
the Vedic tradition, later teachers of the schools of tantra might ç
have endeavoured to bring them much closer to the latter, if not integrate ç
them into it.
@SB8.5 = 2.	T<193>ntric Literature
According to the t<193>ntric texts, the tantras are innumerable. Sometimes ç
they are stated to be 64. The number however, varies from scripture ç
to scripture.
There are several ways of classifying the t<193>ntric texts. According ç
to one tradition, the works in which Sad<193>·iva speaks to the Dev<200> ç
are called `<193>gamas' and those in which the Dev<200> speaks to ç
Sad<193>·iva or Mahe·vara, are<|>named<|>as `nigamas.' As per another ç
grouping, they are: dak<218>i<207>a, v<193>ma and madhyama. A third ç
method groups them into three: divya, kaula and v<193>ma.
A selected list of works that have been printed*, confining it only ç
to the Dev<200>-cult, may now be given:
®·<193>na-gurudeva-paddhati
K<193>makal<193>vil<193>sa
Kaul<193>val<200>nir<207>aya
Kulac<220><195><193>ma<207>i-tantra
Lalit<193>sahasran<193>ma
Mah<193>nirv<193><207>a-tantra
Mantramahodadhi
Nity<193><218>o<195>a·ik<193>r<207>ava
P<193>r<193>nandas<220>tra
Prapa<210>cas<193>ra
<185>aktisa<209>gama-tantra
<185><193>rad<193>tilaka
<186>a<219>cakranir<220>pa<207>a
Saundaryalahar<200>
Tantr<193>bhidh<193>na
Tantrar<193>jatantra
Varivasy<193>rahasya
@SPACE1 = 
@SPACE1 = 
Sometimes, mention is also made of two types of tantras, the Y<193>mala ç
and the £<193>mara.
The Y<193>mala group gets its name because it contains the secret ç
conversations between the deity and his consort, who form the couple ç
(y<193>mala = united, couple). `£<193>mara' means a goblin, an attendant ç
of <185>iva. It also means `wonder'. Hence that class of tantras attributed ç
to <185>iva and containing wondrous teachings is `£<193>maratantra'.
@SPACE = 
@SPACE = 
@NID = The Y<193>malatantras are:
@SPACE1 = 
@NID = <+><|>Brahmay<193>mala, Vi<218><207>uy<193>mala,<R>ç
<+><|>Rudray<193>mala, Lak<218>m<200>y<193>mala,<R>ç
<+><|>Um<193>y<193>mala, Skanday<193>mala,<R>ç
<+><|>Ga<207>e·ay<193>mala and °dityay<193>mala.
@SPACE = 
@SPACE = 
@NID = The £<193>maratantras are:
@SPACE1 = 
@NID = <+><|>Yoga<195><193>mara, <185>iva<195><193>mara, <R>ç
<+><|>Durg<193><195><193>mara, S<193>rasvata<195><193>mara, <R>ç
<+><|>Brahma<195><193>mara and Gandharva<195><193>mara.
@SPACE = 
There are a good number of other tantras also like Ma<210>ju·r<200>m<220>lakalpa ç
and Guhyasam<193>ja-tantra  belonging  to  the Buddhist tradition.
@SB = 3.	Contents of the Tantras in Brief
Though there are various kinds of <193>gamas and tantras, certain ç
features are common to them all. They avow allegiance to the Vedas, ç
and even claim to interpret them to the current age. However, unlike ç
the Vedas, their doors are open to all, irrespective of caste or sex.
The subjects generally dealt with by them are classed under four p<193>das ç
or steps. They are: J<210><193>nap<193>da, Yogap<193>da, Kriy<193>p<193>da ç
and Cary<193>p<193>da.
The J<210><193>nap<193>da gives the philosophy or the metaphysics ç
upon which the tantras are based. It is a combination of the Ved<193>ntic ç
and the S<193><209>khyan principles.
The Yogap<193>da deals with the s<193>dhan<193>s or spiritual disciplines ç
that help an individual aspirant to attain union with the Supreme ç
Self, which is the final goal of life.
Since an individual is a part and parcel of the society and since ç
his spiritual progress is closely allied with that of the society, ç
the tantras give to the society also a way of life, a religion, so ç
that both the individual and the society can progress in harmony with ç
each other. Towards this end, the tantras provide the institution ç
of community worship as in a temple or through a y<193>ga (sacrifice) ç
or through the sacred spots of pilgrimage. These are the topics described ç
in the Kriy<193>p<193>da, the third of the series of the four p<193>das.
@SPACE1 = 
Cary<193>p<193>da, the last, expounds the rituals and the modes ç
of s<193>dhan<193>s needed in an individual's life. A code of conduct ç
is also given for the benefit of the tyro as well as the adept.
A good number of other topics are also dealt with, which may be summarised ç
as follows: authenticity of the <193>gamas and the tantras based on ç
the Vedas; creation of the world; manifestation of vaikhar<200>-v<193>k ç
or the spoken word; on the letters of the alphabet; various rites ç
connected with d<200>k<218><193> or initiation like the V<193>stuy<193>ga; ç
categories of d<200>k<218><193>; on homa (fire ritual); various mantras ç
connected with various deities  of  the  Hindu  pantheon  like Sarasvat<200>, ç
<185>r<200> or Lak<218>m<200>, Bhuvane·var<200>, Durg<193>, Vi<218><207>u, ç
Ga<207>apati, <185>iva and so on;yantras or geometrical configurations ç
associated  with  those  deities;  yogic practices including the descriptions ç
of Ku<207><195>alin<200> and the various cakras or psychic centres ç
and so on.
@SB = 4.	Philosophy of the Tantras
The philosophy of the tantras seems to bean amalgamation and modification ç
of  the  principles  propounded  by  the S<193><209>khya and the Ved<193>nta ç
systems. Theprak<216>ti of S<193><209>khya is material and insentient ç
in nature. The m<193>y<193> of Ved<193>nta, especially of the Advaita ç
Ved<193>nta, is an `entity' that defies all descriptions. However, ç
the <185>akti of the tantras is a very real power of <185>iva, nay, ç
<185>iva himself in his dynamic aspect. All other qualities that are ç
predicated for prak<216>ti-m<193>y<193> like its being trigu<207><193>tmik<193> ç
(comprising the three gu<207>as†sattva, rajas and tamas) and the up<193>d<193>nak<193>ra<207>a ç
(material cause) of the world, hold good for the <185>akti of the ç
tantras also.
The ultimate Reality is one and only one. It is <185>iva or <185>akti ç
or <185>iva-<185>akti and is (`sa<221>vit') of the nature of pure ç
consciousness. The relationship between <185>iva and <185>akti is ç
like that of fire and its burning power or the word and its meaning. ç
They are two in one or one in two, always inseparable. In the inactive ç
state it is <185>iva and in the active state it is <185>akti. The ç
former is also called Nirgu<207>a- parame·vara (the Lord without attributes) ç
wherein  the  <185>akti  is  inherent  and dormant. When this <185>akti ç
starts awakening, Parame·vara becomes `Sagu<207>a.' The first evolute ç
of the process of creation is <185>akti. From <185>akti proceeds para-n<193>da ç
(the unmanifest sound or vibration which gives rise to para-bindu, ç
the higher bindu or point). From it proceed the apara-bindu (lower ç
bindu or point, identified with the <185>iva-principle), the b<200>ja ç
(identified with the <185>akti-principle) and the apara-n<193>da (the ç
lower sound or vibration) considered as the union of the <185>iva ç
and the <185>akti principles.
From b<200>ja or <185>akti (also called <185>abda-brahma, Par<193>·akti ç
or Paradevat<193>) proceed the 23 tattvas or cosmic principles, viz., ç
mahat, aha<209>k<193>ra, the ten indriyas and the mind, the five subtle ç
elements and the five gross elements like the earth, water etc. Together ç
with <185>akti, they are24.
@SPACE1 = 
From the apara-bindu, identified with <185>iva, proceed the five deities ç
viz., Sad<193>·iva, ®·<193>na, Rudra, Vi<218><207>u and Brahm<193>. ç
By adding seven more principles like puru<218>a (the individual soul) ç
and k<193>la (time), the total number of tattvas is raised to 36.
In the human body, <185>akti resides as the Ku<207><195>alin<200>, ç
the power resembling a coiled serpent at the m<220>l<193>dh<193>ra-cakra, ç
situated at the base of the spine. When roused through proper s<193>dhan<193>s ç
or spiritual exercises, it rises through five morecakras like the ç
sv<193>dhi<218><219>h<193>na and the an<193>hata, and, finally reaches ç
the sahasr<193>ra in the crown of the head, resembling a lotus of ç
a thousand petals. there it merges with <185>iva, resulting in mok<218>a ç
or liberation for that individual self.
The j<200>va or the individual soul is none other than <185>iva himself, ç
with his freedom covered over or limited by avidy<193> or nescience, ç
also called <193><207>ava-mala, the impurity that makes him appear ç
small. Through spiritual disciplines, the most important aspect of ç
which is up<193>san<193> or worship and meditation, on <185>akti as ç
Dev<200> or Divine Mother, he is liberated, attaining unity with the ç
Deity.
@SB = 5.	S<193>dhan<193>s as Depicted in the<R>ç
	Tantras
As in the six systems of Indian philosophy, in the tantras also, mok<218>a, ç
or liberation from transmigratory existence, is the ultimate goal ç
of life. The tantras have evolved an elaborate system of s<193>dhan<193>s ç
or spiritual practices that cover all aspects of the human personality ç
and life. Only a brief r<F20W1>Ç<F255D>sum<F20W1>Ç can be attempted here.
@S10N = GURU
The tantras categorically assert the need for taking d<200>k<218><193> ç
or initiation from a competent guru or teacher before starting one's ç
spiritual s<193>dhan<193>s.
A competent guru must be a person of pure parentage and great self-control. ç
He should know the true meaning and essence of the scriptures†the ç
Vedas, the <193>gamas and related scriptures. He should be an adept ç
in p<220>j<193> (worship), homa (pouring oblations into a duly consecrated ç
fire), dhy<193>na (meditation) and japa (repetition of the divine ç
name). A peaceful disposition and a thorough knowledge of yoga are ç
also necessary.
The tantras also warn against accepting false gurus, who feign erudition ç
and holiness, but are motivated by greed and baser instincts.
@S10N = <185>I<186>YA
The ·i<218>ya or the disciple too must possess certain minimum characteristics ç
which will entitle him to spiritual life.
He must be guileless, must aspire after the puru<218><193>rthas (goals ç
of human existence) and be fairly well-read in the Vedas. He should ç
be self-controlled and intelligent enough to understand the teachings ç
of the guru and the scriptures. He should be devoted to his parents, ç
discharge his duties well and avoid all pride of birth or wealth or ç
learning. He must be obedient to the guru and be prepared to sacrifice ç
everything for his sake.
The tantras declare that the guru must test a person before accepting ç
him as a disciple and vice versa.
@S10N = I<186><187>ADEVAT°
Though God the Supreme is one without a second, he can and does manifest ç
himself through various forms and emanations, all of which are non-different ç
from him, even as sugar-dolls are all sugar only. The particular form ç
a s<193>dhaka or a votary chooses is his `i<218><219>adevat<193>,' ç
`the deity dear to him'. He chooses that form for purposes of meditation ç
and worship. Thetantras advocate meditation on and worship of these ç
forms of God since it is much  easier  for  an  average  human being, ç
than contemplating on the Absolute without name and form.
Each of these devat<193>s has a mantra or even several mantras or ç
word-symbols, which have to be ceremonially received in d<200>k<218><193> ç
or initiation from a qualified guru.
@S10N = D®K<186>°
D<200>k<218><193> or initiation into spiritual life is so called because ç
it destroys (k<218>i = to destroy) the sins of the disciple and ç
gives (d<193> = to give) knowledge to him. It should be given on ç
a day and time considered to be holy as per the Hindu calendars. Days ç
of eclipses†especially of the moon†are deemed to be extremely holy.
Several  varieties  of  d<200>k<218><193>  are enumerated in the t<193>ntric ç
works. One of the more well-known categorisations is as follows: kriy<193>vat<200>, ç
var<207>amay<200>, kal<193>vat<200> and vedhamay<200>. The kriy<193>vat<200> ç
d<200>k<218><193> involves the performance of many rituals by the ç
guru. In var<207>amay<200> d<200>k<218><193>, the guru infuses the ç
spirit of the var<207>as or letters of the alphabet which are associated ç
with <185>akti or Dev<200>, in the different parts of the disciple's ç
body. In the kal<193>vat<200> d<200>k<218><193> the guru locates the ç
existence of kal<193>s or powers of the pa<210>cabh<220>tas like niv<216>ttikal<193> ç
or vidy<193>kal<193>, in the body of the disciple, meditates on them ç
and anoints him. In the vedhamay<200> d<200>k<218><193>, the guru ç
initiates the disciple only by the power of his thought.
Sometimes three more varieties are added: spar·ad<200>k<218><193> ç
(rousing the spiritual consciousness by spar·a or touch), v<193>gd<200>k<218><193> ç
(same by uttering the mantra into the ear of the disciple) and d<216>gd<200>k<218><193> ç
or c<193>k<218>u<218><200> d<200>k<218><193> (arousal of spiritual ç
consciousness by looking intently at the disciple).
D<200>k<218><193>, in a more technical sense, involves a number of ç
rituals like the worship of the V<193>stupuru<218>a (Cosmic Being) ç
and bali or sacrifice as also abhi<218>eka done by sprinkling holy ç
water on the disciple.
Its simplest form is `upade·a,' giving the mantra as also certain ç
rules and guidance.
@S10N = MANTRA
The central part of d<200>k<218><193> or upade·a is the imparting ç
of the mantra or the divine word by the guru to the disciple. Etymologically, ç
the word means that which protects (tra = to protect) the person ç
whoreflects (man = to reflect) upon it. `Protection' in the spiritual ç
sense means protecting from sa<221>s<193>ra or transmigratory existence ç
by giving mok<218>a or liberation. The mantras may have their source ç
in the Vedas or the pur<193><207>as or the tantras. Since the last ç
group of works deals primarily with the mantras, it is called as `mantra·<193>stra' ç
or `mantravidy<193>'.
A mantra, according to the tantras, is not just a letter of the alphabet ç
or a combination of such letters into a wordor a sentence signifying ç
a particular object.It is the sound symbol embodying the form, the ç
power and the consciousness of the supreme Brahman or its manifestations.
Before creation, Brahman or <185>iva is established in his own effulgence†hence ç
called `prak<193>·a'†and inactive. When he starts `vimar·a' or deliberating ç
in himself to create the world, there is a spanda or a throb, which ç
develops into n<193>da or vibration. This n<193>da gradually gains ç
in power and then gets concentrated to a bindu or a point. This bindu ç
which contains the <185>iva-<185>akti principle like a dicotyledonous ç
seed further evolves into <185>iva and <185>akti principles by the ç
union of which the whole universe comes into being.
@SPACE1 = 
As per this description of creation given in some tantras, all created ç
objects (called `artha') with `r<220>pa,' shape or form, and `n<193>ma' ç
or name have originated from the primeval n<193>da, which can now ç
be called `<185>abda-brahman.' Hence, it is quite reasonable to assume ç
that every mantra is an aspect of this primeval Word or <185>abda-brahman ç
and represents as its artha, a god or a goddess, which again, is a ç
manifestation or emanation of that Brahman. In other words, the mantra ç
contains in itself the form and the spirit of the deity, whose mantra ç
it is. This deity is revealed by the proper repetition of the mantra, ç
in course of time.
The tantras categorise the mantras as saura (solar) and saumya (lunar). ç
They may be masculine, feminine or neuter. The masculine and the neuter ç
mantras are called `mantra' whereas the feminine mantras are called ç
`vidy<193>'. Mantras ending with hu<221>, va<218>a<219> or pha<219> ç
are masculine, those ending with sv<193>h<193> or vau<218>a<219> are ç
feminine and those ending with nama<199> are neuter. The tantras christen ç
certain monosyllabic mantras like hr<200><221> or kl<200><221> as ç
b<200>jamantras or b<200>j<193>k<218>aras. Even as a seed evolves ç
in course of time into a mighty tree giving plenty of fruits, a b<200>jamantra  also  can  give†if  properly ç
repeated†the siddhi attributed to it, like the revelation of the deity ç
of that mantra.
A mantra, to be effective, should always be received from a qualified ç
guru in a proper way. The tantras describe various processes that ç
help in rousing the power of a mantra and make it effective. A few ç
of such processes are: mukha- ·odhana (purification of mouth), jihv<193>- ç
·odhana  (purification  of  the  tongue), a·aucabha<209>ga (destroying ç
the impurity of the mantra), nidr<193>bha<209>ga (awakening the mantra ç
from slumber) and so on.
They also recommend ten sa<221>sk<193>ras or ritual purificatory processes ç
like d<200>pan<200>, which consist in repeating the b<200>ja-mantra ç
seven times, preceded and followed by pra<207>ava (o<221>).
All these have to be learnt directly from a competent teacher and ç
should not be experimented with, by learning them from books.
@SPACE1 = 
A theory advocated by the tantras regarding the evolution of ·abda ç
or sound, and its corollary, v<193>k or speech, from the subtle unmanifest ç
state to the fully manifested state is worth mentioning here. When ç
a person speaks, four stages of evolution of speech are involved in ç
it. The speech is first rooted in the m<220>l<193>dh<193>racakra as ç
the unmanifest sound. It is then called `par<193>v<193>k'. When it ç
starts getting awakened and reaches the ma<207>ip<220>racakra at the ç
navel, it has just started showing subtle  vibrations.  It  is  now  called ç
`pa·yant<200>-v<193>k'.
On its further rising to the an<193>hatacakra in the region of the ç
heart, these vibrations have already assumed definite and clear thought-forms. ç
It is then called `madhyam<193>-v<193>k'. It now comes out as fully ç
articulated speech, the spoken word, called `vaikhar<200>-v<193>k'.
@S10N = JAPA
A mantra becomes effective only when its japa is done. That is, it ç
should be repeated a prescribed number of times as per the directions ç
of the guru.
Japa is of three types. It is `v<193>cika' or `ucca' when done audibly. ç
It is `up<193><221>·u' if done in whispering tones. If it is done ç
mentally, it is `m<193>nasa'. The last is considered as the most efficacious.
During japa, the counting of the number can be done either by hand ç
or by a japam<193>l<193> (rosary). The number recommended can vary. ç
For instance, it can be 10 or 12, 28 or 32 or 108, the last number ç
being the most widely recognised.
A human being is supposed to breathe 21,600 times in a day of 24 hours. ç
Leaving aside half this time for sleep, looking after the needs of ç
the body and contingencies, the breathing during the waking and active ç
state is 10,800 times. Actually the number 108 symbolically represents ç
this 10,800. In other words, a votary is expected to utter the mantra ç
with every breath and the number 108 is a reminder of that ideal.
@SPACE = 
@S10N = PURA<185>CARAØA
@SPACE = 
The tantras deal with pura·cara<207>a, an important topic closely ç
related to the japa of a mantra. The word literally means `performing ç
or carrying (cara<207>a) before (puras).' Various interpretations ç
have, however, been offered. Perfecting of the procedure of the m<220>lamantra ç
(the basic mantra of a deity) since it has to be practised before ç
the acts in which it is to be employed is called as `pura·cara<207>a' ç
by some works. According to others, the s<193>dhana pura·cara<207>a ç
is so called because the deity of the aspirant, pleased by his devoted ç
practice, moves (cara<207>a) before (puras) him.
Pura·cara<207>a has several constituent elements: dhy<193>na (meditation ç
on the form of the deity), p<220>j<193> (ritualistic worship), japa ç
of the mantra, homa (oblations intothe duly consecrated fire), tarpa<207>a ç
(satiating the deity with the ceremonial offering of water) and br<193>hma<207>a-bhojana ç
(feeding br<193>hma<207>as of good conduct). If any of these constituent ç
elements cannot be performed, it can be replaced by more japa of the ç
mantra as specified in the t<193>ntric works.
According to another method, repeating the mantra one thousand times ç
per day for eight days, starting it on a Tuesday and ending it on ç
the subsequent Tuesday is also pura·cara<207>a.
Some works recommend the repetition of the mantra 24 lakhs of times, ç
followed by an offering of 24 thousand oblations of p<193>yasa or ç
pudding into the duly consecrated fire. By this type of pura·cara<207>a, ç
the mantra becomes perfected and confers on the s<193>dhaka whatever ç
he desires.
The pura·cara<207>a of a mantra on the days of solar or lunar eclipse, ç
while standing in navel-deep water, is stated to be extremely efficacious.
Certain spots like a place of pilgrimage, the bank of a river, a cave ç
or a mountain-top, seashore or the precincts of a temple are recommended ç
as more suitable for the practice of pura·cara<207>a.
@SPACE1 = 
All t<193>ntric works emphasize that unless the mantra has been received ç
froma qualified guru in d<200>k<218><193> and the s<193>dhan<193> ç
is done under his guidance, neither  pura·cara<207>a  nor  even  japa ç
becomes effective.
@SPACE = 
@S10N = P<188>J°
@SPACE = 
P<220>j<193> or ritualistic worship of the deity is a very important ç
part of tantra-s<193>dhan<193>. It forms a part of pura·cara<207>a ç
also.
When a respected or a beloved guest arrives in a house, the master ç
of the house receives him warmly and offers him all that makes him ç
comfortable and happy. This is the spirit behind p<220>j<193> where ç
the guest is God himself.
In  any  p<220>j<193>,  the  preliminary processes include sa<209>kalpa ç
or religious resolve and ceremonial purification of all the items ç
involved in it as the <193>sana or seat, the vessels and the flowers. ç
Bh<220>t<193>pasara<207>a or driving away all the evil spirits that ç
may obstruct the p<220>j<193> is another important item. Pr<193><207><193>y<193>ma ç
or regulation of the mind through the control of breath, bh<220>ta·uddhi ç
or purifying the elements that compose the body of the worshipper, ç
ny<193>sas or placement of the fingers of the hand on the different ç
parts of the body with a view to purifying them,dhy<193>na or meditation ç
are the other important steps.
However, the cardinal part of p<220>j<193> is the `upac<193>ras' or ç
ways of ritual service. In the shortest mode of p<220>j<193> they ç
are five only: gandha (sandal paste), pu<218>pa (flowers), dh<220>pa ç
(incense), d<200>pa (lighted lamp) and naivedya (food). In more detailed ç
forms they are raised to ten or sixteen or even eighteen. Some of ç
them are: <193>v<193>hana (inviting the deity), p<193>dya and arghya ç
(water for washing feet and hands), sn<193>na(bath), vastra (cloth), ç
yaj<210>opav<200>ta (sacred thread), namask<193>ra (obeisance) and ç
visarjana or udv<193>sana (bidding adieu to the deity).
@SPACE = 
@S10N = HOMA
@SPACE = 
Homa or oblations of prescribed things like ghee into a duly consecrated ç
fire, can be done either independently or as a part of p<220>j<193> ç
or even pura·cara<207>a. Generally, a yantra or a geometrical drawing ç
representing the deity is drawn as directed, the sacrificial fuel ç
sticks arranged over it and the fire is ceremonially lit. After some ç
preliminary processes of purification, the deity, to appease whom ç
the homa is being done, is invoked into it and the various upac<193>ras ç
are offered. After the sa<209>kalpa or resolve, in which the purpose ç
and the manner of offering the oblations are stated, the oblations ç
arepoured into it with the appropriate mantra. The actual number ç
of oblations can be 8 or 28 or 32 or 108 or even 1008, as stated in ç
the sa<209>kalpa. The materials considered fit for offering are: ghee, ç
barley, cooked rice, flower, bilva (Aegle marmelos) leaves and a ç
few other prescribed things.
@SPACE = 
@S10N = YANTRA
@SPACE = 
The word `yantra' in its most general sense means an instrument by ç
which anything is accomplished. In worship, it is a diagram drawn ç
or engraved or painted on prescribed materials like metal, stone or ç
paper or even a leaf, that helps oneto subdue (yantra = niyantra<207>a ç
= subduing) his passions like lust and anger and gain greater concentration.
While a ma<207><195>ala, a geometrical figure drawn with coloured ç
powders, can be usedfor the worship of any deity, a yantra also called ç
`cakra', is specific only to a particular deity. Every deity of the ç
Hindu pantheon has its own yantra. If the deity is the soul, the yantra ç
is its body.
Apart from the geometrical drawing or pattern that is appropriate ç
to the deity,a yantra also contains its mantra, inscribed at the ç
proper place. The presence of the deity is invoked into the yantra ç
by worship, the procedure of which is very similar to that of a pratim<193> ç
or image. A yantra wherein the deity has been roused by duly worshipping ç
it, can then be used for any purpose†especially for the fulfilment ç
of one's desires†sanctioned by the t<193>ntric works.
@SPACE = 
@S10N = NY°SAS AND MUDR°S
@SPACE = 
Transformation of thought is transformation of being. If the various ç
parts of the s<193>dhaka's body are touched by his fingers and palms ç
with the appropriate mantras, that will induce the presence of the ç
deity in him, thereby transforming him and making him fit for the ç
ritual or the particular process of s<193>dhan<193>. This is the general ç
principle behind the ny<193>sas and mudr<193>s.
The word `ny<193>sa' comes from the root `nyas' (`to place'). It is ç
generally done by placing the tips of the fingers and the palm of ç
the right hand on the various parts of the body accompanied by parti-cular ç
mantras.
There are several ny<193>sas out of which a few†the more common ones†can ç
now be described.
J<200>vany<193>sa is that by which the s<193>dhaka establishes the ç
i<218><219>adevat<193> in the region of the heart and thus becomes ç
one with it.
Vy<193>pakany<193>sa, performed by passing the hands all over the ç
body from top to bottom, helps him to feel the presence of the deity ç
as pervading the whole body.
In m<193>t<216>k<193>ny<193>sa, which is done with the letters of ç
the alphabet, the various letters are placed mentally in the cakrasor ç
psychic centres of the body (antarm<193>t<216>k<193>-ny<193>sa) and ç
also in other limbs outside (bahirm<193>t<216>k<193>ny<193>sa) thereby ç
feeling the competence to know <185>abdabrahman in himself.
In p<200><219>hany<193>sa, the internal seat (p<200><219>ha = seat) ç
in the region of the heart, is made fit for the residence of the deity. ç
Sometimes, the word is interpreted as establishing the various <185>akti-p<200><219>has ç
(places of pilgrimage sacred to the Dev<200> or <185>akti, such as ç
K<193>mar<220>pa [in Assam] or J<193>landhara [in Haryana]) inside ç
one's own body in a subtle way.
In <216><218>y<193>diny<193>sa, the <216><218>i or the sage, the chandas ç
or the Vedic metre and the devat<193> or the deity are remembered ç
and homage is paid to them.
In karany<193>sa and a<209>gany<193>sa, the fingers of the two hands ç
(kara = hand) and the limbs of the body (a<209>ga = limb) like the ç
heart and the head, are sanctified to make them fit for worship and ç
meditation.
@SPACE1 = 
Like ny<193>sas, mudr<193>s also find an important place in the t<193>ntric ç
rituals. The word mudr<193> is interpreted as that which pleases the ç
deity and makes its heart melt out of compassion for the votary, and ç
hence grant his desires (mud = pleasure, drav = to melt, r<193> ç
= to give).
In a technical sense the term `mudr<193>' has several meanings:
@NO = 1)
@NOK = pose of hand as in dance or in p<220>j<193>;
@NO = 2)
@NOK = posture of the body as in Ha<219>hayoga;
@NO = 3)
@NOK = as one of the five mak<193>ras, it means various kinds of grains ç
mixed with ghee.
@NO = 4)
@NOK = a woman companion of the t<193>ntric s<193>dhaka.
@NID = <+><+><+><|>However, it is used widely in the sense of poses of ç
fingers or of hand or hands in relation to worship and meditation.
Some of the more common mudr<193>s are:
@NO = 1)
@NOK = °v<193>hanamudr<193> used to invite and welcome the deity in ç
p<220>j<193>.
@NO = 2)
@NOK = K<220>rmamudr<193> used in meditation on the deity.
@NO = 3)
@NOK = Avagu<207><219>hanamudr<193> and matsyamudr<193> used in offering ç
food in p<220>j<193> to the deity. So also the gr<193>samudr<193> ç
and pr<193><207><193>di-pa<210>ca-mudr<193>s.
Dhenumudr<193>, goyonimudr<193> and n<193>r<193>camudr<193> are some ç
of the other, more commonly used, mudr<193>s.
The number of mudr<193>s as given in the t<193>ntric works and even ç
pur<193><207>as, differsconsiderably. The number varies from 9 upto ç
108.
@S10N = KUØ£ALIN® AND CAKRAS
Brahman and <185>akti are like the two sides of the same coin. The ç
external world is the creation of <185>akti associated with Brahman. ç
Inside the bodies of human beings <185>akti takes the form of Ku<207><195>alin<200>.
Ku<207><195>alin<200> is the basic energy of the entire human being. ç
It is generally pictured as a coiled serpent (ku<207><195>ali = serpent) ç
lying asleep at the base of the spinal column, called as `<193>dh<193>racakra' ç
or `m<220>l<193>dh<193>racakra'. When it is roused by proper s<193>dhan<193>s ç
under the guidance of a competent guru, it passes through the brahma-n<193><195><200> ç
of the su<218>umn<193> canal, pierces through the various cakras, ç
ultimately reaching the sahasr<193>ra, where it gets united with <185>iva.
According to the works on tantra, there are three n<193><195><200>s ç
(canal-like structures for the flow of pr<193><207>ic energy) in the ç
region of the spinal column. In its centre passes the su<218>umn<193> ç
and to its right, the pi<209>gal<193>. The i<195><193> is on the left. ç
I<195><193> and pi<209>gal<193> are intertwined over the spinal column. ç
Inside the su<218>umn<193> is the vajri<207><200> n<193><195><200>. ç
Inside it is citri<207><200> and brahman<193>d<200> is the inmost. ç
While in the dormant state, the Ku<207><195>alin<200> lies at the ç
bottom of the m<220>l<193>dh<193>ra closing the brahman<193><195><200> ç
with its mouth.
@SPACE1 = 
The cakras are so called since they are circular in shape (cakra = ç
wheel or disc). They are actually psychic centres of consciousness ç
and power, situated in the s<220>k<218>ma·ar<200>ra or the subtle ç
body, corres-ponding to certain parts of the physical body. The <193>dh<193>racakra ç
or the m<220>l<193>dh<193>ra is situated at the base of the spine ç
behind the anus. The sv<193>dhi<218><219>h<193>na is at the root of ç
the sex-organ. The ma<207>ip<220>ra is at the navel. The an<193>hata ç
is at the region of theheart. The vi·uddha is at the throat. The ç
<193>j<210><193> is between the eyebrows. The sahasr<193>ra is in ç
the top of the head. These cakras are likened to lotuses, each with ç
a certain number of petals, colour and certain m<193>t<216>k<193>s ç
(letters of the alphabet as mantras) inscribed on them. The petals ç
are the n<193><195><200>s or subtle nerve channels, which surround ç
and function through each of these centres.
The table gives the details of cakras at a glance.
@SPACE1 = 
@SPACE1 = 
These  six  cakras  together  are collectively  called  `<218>a<219>cakras'  and  the ç
piercing act of the Ku<207><195>alin<200> is designated as `<218>a<219>cakrabheda'.
@SPACE1 = 
The sahasr<193>ra of thousand petals situated at the top of the head ç
is the seventh cakra and is the destination of Ku<207><195>alin<200>.
@SPACE1 = 
When the Ku<207><195>alin<200> is roused, the m<220>l<193>dh<193>ra ç
lotus rises up, and opens its petals. After the Kun<195>alin<200> ç
leaves it, it assumes its original position as a bud hanging  downwards.  This  procedure ç
applies to all the other cakras also. After reaching the sahasr<193>ra, ç
the Kun<195>alin<200> comes back to its original place. Repeated practice ç
of the Ku<207><195>alin<200>yoga will result in the flooding of all ç
the cakras with am<216>ta or nectar of bliss, ultimately resulting ç
in mukti or liberation.
@SB = 6.	Some Allied and Relevant Topics
The t<193>ntric literature encompasses a very vast area of subjects. ç
Differences exist not only on the relative importance of thesubjects ç
but also on the subjects themselves. An attempt will now be made to ç
present briefly at least some of the more commonly accepted concepts.
These works present seven types of <193>c<193>ra or modes of s<193>dhan<193> ç
as follows: Ved<193>c<193>ra, Vai<218><207>av<193>c<193>ra, <185>aiv<193>c<193>ra, ç
Dak<218>i<207><193>c<193>ra, V<193>m<193>c<193>ra, Siddh<193>nt<193>c<193>ra ç
and Kaul<193>cara. However, these seven are more commonly grouped ç
into two, the Dak<218>i<207><193>c<193>ra and the V<193>m<193>c<193>ra. ç
The words may mean the `right-hand path' and the `left-hand path;' ç
or, the `favourable path' and the `path involving v<193>m<193> or ç
woman.'
Worship of the deity Dak<218>i<207>ak<193>lik<193>, following the ç
Vedic modes of worship and s<193>dhan<193>, as also belief in the ç
var<207><193>·rama system, characterise the Dak<218>i<207><193>c<193>ra.
V<193>m<193>c<193>ra needs some explanation and elaboration. It is ç
called as `C<200>n<193>c<193>ra' also, since the sage Vasi<218><219>ha ç
is said to have introduced it after learning it from the Buddha in ç
C<200>nade·a (Tibet or China), where it was prevalent. Another name ç
commonly attributed to it is `Kaul<193>c<193>ra' or `Kaulam<193>rga'. ç
`Kula' means `<185>akti' and the name itself is derived from the fact ç
that the worship of <185>akti is predominant in this system of s<193>dhan<193>. ç
However, other interpretations are also offered for the word kula ç
and Kul<193>c<193>ra.
The pa<210>catattvas or pa<210>camak<193>ras viz., madya (wine), m<193><221>sa ç
(flesh), matsya (fish), mudr<193> (parched grain) and maithuna (coition) ç
are the most essential parts of this s<193>dhan<193> system. They ç
are meant for the s<193>dhakas of the v<200>ra-type (heroic type), ç
that too under the strict supervision of a competent guru. The v<200>ra-s<193>dhaka ç
is one who has risen to much higher levels of spiritual evolution ç
and hence has great self-control.
However, gross abuse of these five tattvas by the lowest of the s<193>dhakas, ç
of the pa·u-type (with unsublimated animal passions) has earned a ç
bad name for the whole system, aver some of the tantras. This has ç
led to some of them inventing harmless substitutes like coconut water ç
for madya, garlic for m<193><221>sa or brinjal for matsya and so on; ç
or even give highly symbolic interpretations (for e.g., madya= intoxicating ç
knowledge of God; maithuna= union of the Ku<207><195>alin<200> with ç
<185>iva and so on) to the same. Later writers have strongly condemned ç
these abuses and tried to restore the purity of the system.
@SPACE1 = 
A t<193>ntric s<193>dhaka has to rise from the level of the pa·u to ç
that of the v<200>ra and then to the divya (divine) state. If a v<200>ra-s<193>dhaka ç
has cultivated the divine virtues by great effort, they are most naturally ç
and effortlessly revealed in the divya-s<193>dhaka.
One who is an adept in the Kaul<193>c<193>ra and has reached the summit ç
of realization is called a `paramaha<221>sa' and he has transcended ç
all the rules of conduct normally prescribed for the lower s<193>dhakas ç
since he is able to see the divine <185>akti in all.
Another <193>c<193>ra that is often mentioned in the t<193>ntric works ç
is the Samay<193>c<193>ra, which is distinguished from the Dak<218>i<207><193>-c<193>ra, ç
the V<193>m<193>c<193>ra and Kaul<193>c<193>ra. In this tradition, ç
the Dev<200> is called `Samay<193>' and she personifies the very import ç
of the Vedic tradition. Hence Samay<193>c<193>ra is the conduct in ç
accord with the Vedic tradition and for all practical purposes, can ç
be identified with the Ved<193>c<193>ra listed among the seven <193>c<193>ras. ç
In this school, <185>iva and <185>akti are equally important. Stress ç
is laid on the antary<193>ga or internal worship and the rousing of ç
the Ku<207><195>alin<200> through successive stages of up<193>san<193> ç
or meditation. Worship of the <185>r<200>cakra or <185>r<200>yantra ç
is an important aspect of this school.
@SPACE1 = 
The <185>r<200>cakra is a yantra formed by five inverted triangles ç
and four straight triangles as also diagrams of several petals of ç
lotus, with a dot in the centre and some lines at the extremities. ç
It represents the Dev<200> and the gradual evolution of creation from ç
her, associated with <185>iva.
When the <185>r<200>cakra is built up in a three-dimensional form, ç
it is called `meru.' Worship of the meru is considered even better ç
than that of the yantra.
The Samay<193>c<193>ra is sometimes called the `K<193>dimata' also. ç
This takes us to another topic connected with the <185>r<200>cakra. ç
The worship of the <185>r<200>cakra is invariably associated with ç
<185>r<200>vidy<193>, initiation into which is a must for any s<193>dhaka ç
of the Samay<193>c<193>ra. `Vidy<193>' means `mantra'. `<185>r<200>vidy<193>' ç
means the mantra associated with the <185>r<200>cakra. It is also ç
called `pa<210>cada·<193>k<218>ar<200>mantra' since it contains pa<210>cada·a ç
or 15 letters. In the most common form, they are distributed into ç
three units of 5 letters, 6 letters and 4letters. In this, the very ç
first letter of the first unit is `ka.' Hence the Samay<193>c<193>ra ç
which lays great emphasis on the repetition and use of this mantra, ç
is called `K<193>di-mata', the school advocating the mantra beginning ç
(= <193>di) with ka. The sage Agastya is said to be the promulgator ç
of this school.
As against this, there is the `H<193>dimata,' the school attributed ç
to Lop<193>mudr<193> (wife of the sage Agastya) which stresses the ç
importance of another pa<210>cada·<193>k<218>ar<200> mantra that begins ç
with the letter `ha.'
The difference between the two versions of the pa<210>cada·<193>k<218>ar<200> ç
is in the number of effective letters used. Whereas the former has ç
seven letters, the latter has only five.
A <218>o<195>a·<193>k<218>ar<200>-mantra is also in vogue where the ç
sixteenth letter (<218>o<195>a·a = 16) is `·r<200><221>,' the other ç
15 letters being the same.
@SPACE1 = 
The Samaya tradition uses two morewords†antary<193>ga and bahiry<193>ga. ç
The latter consists of worshipping the <185>r<200>cakra in the traditional ç
Vedic way, with all the upac<193>ras or ingredients. The former is ç
meditation on the unity of the goddess and the <185>r<200>cakra, the ç
world and the <185>r<200>cakra, the body and the j<200>v<193>tman ç
as also the alphabet and the goddess.
One of the strangest, but abominable, t<193>ntric practices mentioned ç
in some of the works is the ·avas<193>dhan<193> or the ritual of the ç
corpse. The corpse of a healthy person who has just died is secured, ç
washed and anointed. The s<193>dhaka has to sit upon it and meditate ç
on the Dev<200> at midnight, on a new-moon day. If he survives the ç
terrible experiences, he will attain siddhi or command over every ç
aspect of life.
Some scholars believe that this ·avas<193>dhan<193> was a typical ç
and clumsy remnant of a primitive belief or ritual connected with ç
death and revival.
@SB = 7.	<185>aktip<200><219>has
There are several places of pilgrimage associated with <185>akti or ç
the Mother- goddess. They are called `<185>aktip<200><219>has,' seats ç
of power (p<200><219>ha = seat), associated with <185>akti. A ritual ç
visit to these places is said to confer great religious merit.
The number of such p<200><219>has seems to have grown gradually from ç
4 to 51 or even 108. However the number seems to have got fixed at ç
51 in course of time.
There is an interesting paur<193><207>ic legend behind the formation ç
of these <185>aktip<200><219>has. When Sat<200>-D<193>k<218><193>ya<207><200> ç
immolated herself in the sacrificial shed of Dak<218>a (her father)†since ç
he had humiliated her and her husband <185>iva†<185>iva carried away ç
her body. Being inconsolable he started roaming about the world, with ç
the dead body on his back. Then Vi<218><207>u, at the behest of the ç
gods, started cutting that body by his cakra or discus so that <185>iva ç
might overcome his infatuation. Wherever pieces of that body fell, ç
that place  became  a  place  of  pilgrimage associated with <185>akti, ç
a <185>aktip<200><219>ha.
Each of these 51 <185>aktip<200><219>has is associated with a letter ç
of the alphabet, a part of Sat<200>'s body, an aspect of the Dev<200>, ç
a corresponding aspect of <185>iva, identified with a modern place ç
in the present-day  India-Pakistan-Bangladesh region and a special ç
t<193>ntric attainment that can be got by s<193>dhan<193> there. For ç
instance, the K<193>·m<200>ra-p<200><219>ha (in the Amarn<193>th Cave) ç
is associated with the letter `u'. It is the place where Dev<200>'s ç
left ear (or neck) fell. Mah<193>m<193>y<193> is the goddess and Trisandhye·vara ç
is the god. Fulfilment of whatever mantra is repeated here, is the ç
attainment.
Some of the other famous <185>aktip<200><219>has are: Hi<209>gula ç
in Baluchistan (now in Pakistan); Karav<200>ra in Kolhapur (Maha-rashtra); ç
V<193>r<193><207>as<200> (in Uttar Pradesh); Jv<193>l<193>mukh<200>   (in   Punjab);   K<193>m<193>khy<193> ç
(in  Assam);  Janasth<193>na  (in  Nasik, Maharashtra); Prabh<193>sa ç
(Girnar hills in Gujarat); J<193>landhara (in Haryana); Kanya-k<193>·rama ç
(in Kany<193>kumar<200> temple, Tamil Nadu); Ujjayin<200> (in Rudras<193>gar, ç
Madhya Pradesh); K<193><210>c<200> (in <185>ivak<193><210>c<200>, ç
Tamil Nadu), Trisrot<193> (in West Bengal) and K<193>l<200>p<200><219>ha ç
(K<193>l<200>gh<193><219> temple of Calcutta).
@SB = 8.	Conclusion
The tantras are a neglected, or even misunderstood, branch of Hindu ç
scriptures. Whether they originated as an offshoot of the Vedic religion, ç
or were aparallel tradition developed by those opposed to the br<193>hminical ç
hierarchy, or were `imported' from China and Tibet, they have, without ç
doubt, enriched Hindu religion in all its aspects, especially in the ç
field of rituals and spiritual practices. Hence serious attempts should ç
be made to properly edit and publish many of these works which are ç
still lying in the manuscript form in the libraries of institutions ç
and individuals.
@NT = Tantrav<193>rttika
The P<220>rvam<200>m<193><221>s<193>s<220>tras of Jaimini (200 <MS>B.<|>C.<D>) ç
has 2700 s<220>tras spread over 12chapters containing 60 subsections. ç
The earliest and the most authoritative commentary on it is by <185>abarasv<193>min ç
(100<MS>B.<|>C.<D>) and is called <185><193>barabh<193><218>ya.
Kum<193>rilabha<219><219>a (8th century <MS>A.<|>D.<D>) wrote three ç
works in verses on this <185><193>barabh<193><218>ya, out of which ç
the Tantra-v<193>rttika is the second. It covers the portion 1.2 ç
to the end of chapter 3. It is quite voluminous.
See also <MS>KUM°RILA BHA<187><187>A<D> and <MS>M®M°<189>S°DAR<185>ANA.<D>
@NT = tapas
@N1 = (`that which causes suffering')
The word tapas comes from the root-verb `tap' (sant<193>pe, in the ç
sense of suffering). Hence it means any discipline that causes suffering ç
to the body-mind complex.
We find the word used even in the <184>gveda (10.154.2). There, ç
it is interpreted as penances like k<216>cchra and meditation on Hira<207>yagarbha. ç
(See <MS>K<184>CCHARA<D> and <MS>HIRAØYAGARBHA<D> for details.)
@SPACE1 = 
It is also used in the Upani<218>ads like the Ch<193>ndogya (5.10.1,<|>2) ç
and the Mu<207><195>aka (1.2.11) in the sense of performance of ç
one's duties and austerities.
Dharmas<220>tras like those of Gautama (19.15) equate it with a number ç
of observances <|>like<|> brahmacarya <|>(celibacy),
