@H = E
@NT = eclipse
See <MS>GRAHAØA.<D>
@NT = Education
@S10 = Introduction
The <$IUpanisad/s>Upani<218>ads aver that whatever good is done with ç
full knowledge and awareness becomes forceful and fruitful in life. ç
<$IBhartrhari>Bhart<216>hari, a well-known <$ISanskrit>Sanskrit poet, ç
compares a man without any education to a brute. <$IAlbert Einstein>Albert ç
Einstein (<MS>A.<|>D. <D>1879-1955) seems to concur with him when he ç
likens a man with a specialized knowledge, but lacking in values, ç
to a well-trained dog!
<$IVivekananda>Vivek<193>nanda, the great patriot-prophet of Modern ç
India, who could feel the pulse of the Indian nation, states that:
@SPACE = 
(a)
@NK = Education is the panacea for all our ills.
(b)
@NK = It is the manifestation of the perfection already in man.
(c)
@NK = It is the training by which the current and expression of will ç
are brought under control and become fruitful in life.
(d)
@NK = It is life-building, man-making, character-making assimilation ç
of ideas.
It is rather astonishing that many Western savants* have practically ç
echoed <$IVivekananda>Vivek<193>nanda's ideas though in different ç
words.
These can be briefly summarized as follows:
@SPACE = 
(a)
@NK = Education  should  teach  our children self-control, the art ç
of holding  one's  passions  and prejudices.
(b)
@NK = It should instil true and worthy motives, a profound religious ç
feeling and inspire the formation of a great character.
(c)
@NK = It should help us to understand the laws of <$IGod/s>God in ç
nature and to shape our lives to be in consonance with those laws.
(d)
@NK = It should pay much greater attention to the development of the ç
powers of the mind than mere learning of facts.
The ancient and medieval systems of education recognized all these ç
aspects whileformulating the policies guiding them. Accordingly all ç
fields of <$Ividya>vidy<193> or knowledge were divided into two broad ç
streams: the <$Iparavidya>par<193>vidy<193> (the higher know-ledge, ç
the spiritual wisdom) and the <$Iaparavidya>apar<193>vidy<193> (the ç
lower knowledge, the secular sciences). The latter is needed to live ç
a comfortable life here. The former helps one to be fully prepared ç
for the hereafter. Hence a balanced combination of both, is advocated ç
so that both <$Icivilization>civilization and <$Iculture>culture are ç
imparted.
It is very interesting to note that even an ancient <$IUpanisad/s>Upani<218>ad†the ç
<$IChandogya Upanisad>Ch<193>ndogya Upani<218>ad†assigned to the ç
period 4000 <MS>B.C.<D> to 2500 <MS>B.<|>C.<D>, mentions as many as ç
fifteen branches of knowledge apart from the four <$IVeda/s>Vedas! ç
Some of them are: <$Ivyakarana>Vy<193>kara<207>a (grammar), <$IPitrya>Pitrya ç
(science of obsequial rites), <$IGanita>Ga<207>ita (mathematics), ç
<$IDaiva>Daiva (knowledge of the portents), <$ITarka>Tarka (logic), ç
<$IEkayana>Ek<193>yana (ethics), <$IBhutavidya>Bh<220>tavidy<193> ç
(science of the spirits), <$IDhanurveda>Dhanurveda (martial arts and ç
sciences), <$Ijautisa>Jyauti<218>a (astronomy) and <$IDevajanavidya>Devajanavidy<193> ç
(the art of preparing perfumes, music, dancing and <$Isculpture>sculpture).
@SPACE = 
@S10 = Constituents of an Educational System
The three constituents of an educational system are: the teacher, ç
the student and the content as also the methods of education.
A spiritual teacher†generally called `<$Iguru>guru' or <$Iacarya>`<193>c<193>rya'1†was ç
expected to be a `<$ISrotriya>·rotriya' (learned in the <$IVeda/s>Vedas ç
and allied scriptures) and a `<$Ibrahmanistha>brahmani<218><219>ha' ç
(well- established in <$IBrahman>Brahman or <$IGod/s>God). As applied ç
to other fields of knowledge it could mean that he should be an expert ç
both in theory and in practice. An impeccable character, earnestness ç
to teach and a genuine love towards the student were the additional ç
qualities expected in him.
Eagerness to learn, humility, obedience to the teacher, self-control, ç
absence of laziness in the pursuit of knowledge and willingness to ç
do personal service to the teacher†these were the essential traits ç
astudent must possess, to qualify for admission.
@S10 = <$Igurukula/s>Gurukulas
@SPACE = 
The teachers kept their students in their own houses. When the number ç
of students became large, these houses would grow into institutions ç
called `<$Igurukula/s>gurukulas,' established by the society, the ç
kings and the rich endowing them with sufficient property and funds ç
so that they could provide quality education, free of cost, to all ç
the students.
As a result, these <$Igurukula/s>gurukulas or educational academies ç
grew to enormous dimensions†both in quality and quantity †thus fulfilling ç
the significance of their very names: <$Iguru>guru<|>=<|>enormous, kula<|>=<|>institution. ç
It was not uncommon to find as many as ten thousand students in some ç
of these bigger institutions. Not only out of necessity, but also ç
as a good practice,the senior and better qualified students were ç
made to teach the novices and also supervise over their life and discipline. ç
Though punishments for transgressions existed they were not very severe. ç
Incorrigible students were expelled to save the discipline and reputation ç
of the institution.
For imparting <$Iparavidya>par<193>vidy<193> or spiritual wisdom, ç
an earnest desire to learn and a willingness to undergo <$Itapas>tapas ç
or austerity were the only requirements. Neither <$Ivarna/s>var<207>a ç
nor <$Iasrama><193>·rama nor age seems to have mattered.
However,  for  the  study  of  the <$IVeda/s>Vedas and allied sciences ç
like the <$IVedangas>Ved<193><209>gas,2 some restrictions had been ç
imposed. It was open only to the dvijas (the `twice-born,' the members ç
of the first three castes) and that too after the boys had undergone ç
the <$Iupanayana>upanayana1 ceremony.
Now, some additional, but miscellaneous, information can be given ç
to get a more complete picture of the system over the centuries:
Scholarly disputations and philosophical discussions used to take ç
place even in the <$IVedic;period>Vedic period, in meetings generally ç
known as `<$Isamiti/s>samiti' or `<$Isamaja>sam<193>ja' or `<$Iparisad/s>pari<218>ad'.
<$IVaranasi>V<193>r<193><207>as<200> or <$IKasi>K<193>·<200> and <$ITaksasila>Tak<218>a·il<193> ç
were well-known as great centres of learning even from the 8th century ç
<MS>B.<|>C.<D> Some cities like <$IPataliputra>P<193><219>al<200>putra, ç
<$IVidisa>Vidi·<193> and <$IKancipuram>K<193><210>c<200>puram were  called  `<$Ighatikasthanas>gha<219>ik<193>sth<193>nas,'  centres ç
capable of measuring the scholarship of the savants. In such centres ç
there was provision to get training in 14 to 18 branches of learning.2 ç
Students were free to acquire a deep knowledge of their religion without ç
any hindrance from the followers of other religions.
The universities of <$ITaksasila>Tak<218>a·il<193> (400 <MS>B.C.<D>), ç
<$IVikramasila>Vikrama·il<193> (<MS>A.<|>D.<D> 800) and <$INalanda>N<193>land<193> ç
(<MS>A.D.<D><|>600) had attained phenomenal growth and fame. These ç
universities had several <$Imahapathasalas>mah<193>p<193><219>ha·<193>l<193>s ç
(colleges) and each of these again comprised several lecture halls. ç
There were three huge buildings housing big libraries of invaluable ç
manuscripts.
Admission tests were very strict and only 20% of the aspirants could ç
succeed in getting admission.
In the <$INalanda>N<193>land<193> University alone there were 8500 ç
students, taught by 1500 teachers  with  at  least  100  lectures ç
delivered per day. Professors like <$INagarjuna>N<193>g<193>rjuna, ç
<$IVasubandhu>Vasubandhu and <$IDinnaga>Di<209>n<193>ga were  internationally  reputed  scholars ç
attracting a large number of students from many foreign countries ç
like <$IChina>China, <$IJapan>Japan, <$IKorea>Korea,<$ITurkestan>Turkestan, ç
<$IBurma>Burma, G<193>ndh<193>ra (<$IAfghanisthan>Afghanisthan), <$ISumatra>Sum<193>tra ç
and <$IPersia>Persia. Though education was mostly residential and ç
free, students who could afford to pay, did so.
Among  the  residential  students <$IBuddhist;students>Buddhist nuns ç
were also there. However, according to <$IHiuen Tsang>Hiuen Tsang ç
(<MS>A.<|>D.<D> 600-664) and <$II-tsing>I-Tsing (<MS>A.<|>D.<D> 635-713), ç
not even a single instance of misconduct had been noticed or discovered, ç
thanks to the high degree of moral discipline kept up by the teachers ç
and the administrators.
Apart from these Buddhist universities, we learn from <$IKautilya>Kau<219>ilya ç
(300 <MS>B.<|>C.<D>) and others that there were industrial and vocational ç
training institutions too, impar-ting specialized training in those ç
branches.
From all these accounts we find that the educational system of the ç
ancient and medieval India was not only highly developed but also ç
capable of delivering to us a lesson or two even now.
@S10 = Script, Language and Literature
@SPACE1 = 
A passing reference may now be made to some allied topics like the ç
evolution of the script, language and literature. The art of writing ç
was known even during the <$IVedic;age>Vedic age though memorization ç
was preferred and encouraged. The two scripts†<$IBrahmi> Br<193>hm<200> ç
and <$IKharosthi>Kharo<218><219>h<200>†are known to have existed even ç
in600<MS>B.<|>C.<D> Both the <$Idevanagari>Devan<193>gar<200> and ç
some of the South Indian scripts are its evolutes. <$ITalapatra>T<193>lapatra ç
(palm-leaf), <$IBhurjapatra>Bh<220>rjapatra (birch-bark), wooden plates, ç
cloth (of cotton or silk), leather, stone and bricks were used for ç
writing.
Evidence is not lacking to conclude that <$ISanskrit>Sanskrit works ç
existed even as early as 600 to 100 <MS>B.<|>C.<D> Apart from the <$IVeda/s>Vedas, ç
the epics†the <$IRamayana>R<193>m<193>ya<207>a and the <$IMahabharata>Mah<193>-bh<193>rata†stand  out  as  monuments  of ç
exquisitely beautiful literature of a very highstandard. The ease ç
and facility with which the <$ISanskrit>Sanskrit language has been ç
used even in the composition of technical subjects bearing on liturgy, ç
medical and health sciences, ethics or linguistics, is astounding.
The <$IPrakrt>Pr<193>k<216>t language†a popular deri-vative of <$ISanskrit>Sanskrit†also ç
had been fairly well-developed even by 500 <MS>B.<|>C.<D>
The following table gives the approximate periods of the evolution ç
of the earliest literary works in other Indian languages:
@SPACE1 = 
@SPACE1 = 
@L3 = <$IAssamese>Assamese	:	<MS>A.<|>D.<D> 1300<R>ç
<$IBengali>Bengali	:	<MS>A.<|>D.<D> 1100<R>ç
<$IGujarati>Gujarati	:	<MS>A.<|>D.<D> 1000<R>ç
<$IHIndi>Hindi	:	<MS>A.<|>D.<D> 1000<R>ç
<$IKannada>Kannada	:	<MS>A.<|>D.<D> 100<R>ç
<$IKashmiri>Kashmiri	:	<MS>A.<|>D.<D> 1200<R>ç
<$IMalayalam>Malayalam	:	<MS>A.<|>D.<D> 900<R>ç
<$IMarathi>Marathi	:	<MS>A.<|>D.<D> 1000<R>ç
<$IOriya>Oriya	:	<MS>A.<|>D.<D> 700<R>ç
<$IPunjabi>Punjabi	:	<MS>A.<|>D.<D> 1000<R>ç
<$ITamil>Sindhi	:	<MS>A.<|>D.<D> 1000<R>ç
Tamil	:	600 <MS>B.<|>C.<D><R>ç
<$ITelugu>Telugu	:	200 <MS>B.<|>C.<D><R>ç
<$IUrdu>Urdu	:	<MS>A.<|>D.<D> 1300
A few important literary works in these languages composed during ç
the early and the medieval periods may now be cited:
Works of <$IHemasarasvati>Hemasarasvat<200>, <$IHarihara Vipra>Harihara ç
Vipra and <$ISankara Deva><185>a<209>kara Deva in <$IAssamese>Assamese; ç
the <$IMangala>Ma<209>gala and the <$IVijaya;literature in Bengali>Vijaya ç
literature in <$IBengali>Bengali; works of <$INarasi Mehta>Naras<200> ç
Meht<193> and <$IRamananda>R<193>m<193>nanda in <$IGujarati>Gujarati; ç
compositions of <$ITulasidas>Tulas<200>das, <$IMira>M<200>r<193>, ç
<$IVidyapati>Vidy<193>pati and <$IKabir>Kab<200>r in <$IHIndi>Hindi; ç
grammar and mythological literature of <$IKesiraja>Ke·ir<193>ja, <$IPampa>Pampa, ç
<$IRanna>Ranna and <$IHarihara>Harihara as also the religious literature ç
of the <$ISivasaranas><185>iva·ara<207>as and <$IHaridasas>Harid<193>sas ç
of <$IKannada>Kannada; works of <$IJnanesvar>J<210><193>ne·var, <$IEknath>Ekn<193>th, ç
<$ITukaram>Tuk<193>r<193>m and others in <$IMarathi>Marathi; <$Ipancasakhas>Pa<210>casakh<193>s' ç
works in <$IOriya>Oriya; the <$IGuru-Granth Sahib>Guru-Granth S<193>h<200>b ç
in <$IPunjabi>Punjabi; the <$IKural>Kura<202> of <$ITiruvalluvar>Tiruva<202><202>uvar, ç
the <$ITevarams>Tev<193>rams and the <$IDivyaprabandhams>Divyaprabandhams ç
of Tamil saints in <$ITamil>Tamil; the poetical works of <$ISrinatha><185>r<200>n<193>tha, ç
<$IPotana>Potana, <$IVemana>Vemana and <$IAnnamacarya>A<207><207>am<193>c<193>rya ç
in <$ITelugu>Telugu.
From all these, we can conclude that the Indian languages and literature ç
had attained considerable growth and refinement even by the middle ç
ages.
@NT = effigy, burning the
Burning  the  effigy  of  a  person religiously (this is called <193>k<216>tidahana) ç
has been recommended by the dharma·<193>stras in such cases where ç
there is enough evidence to believe that he might have died and neither ç
the body nor its parts were available for cremation.
An effigy is prepared out of pal<193>·a (Butea frondosa) stalks ç
and leaves, 360 in number. These stalks are used in the prescribed ç
manner such as 40 pieces for the head, 20 for the chest, 30 for the ç
abdomen and so on. If he had kept the Vedic fires, then, his sacrificial ç
vessels are also to be consigned to the fire as in a regular cremation ç
when the body is available.
In case the person were alive and returned, then, all the sa<221>sk<193>ras ç
or sacraments had to be repeated again including remarrying his own ç
wife.
@SPACE = 
@NT = ekabera
@N1 = (`solitary icon')
Temples of Vi<218><207>u are sometimes categorised into two groups: ç
ekabera temple and bahubera-temple.
In the former group of temples there will be only one (= eka) permanent ç
icon (= bera) and neither the goddesses (consorts) <185>r<200>dev<200> ç
and Bh<220>dev<200> nor the utsava-m<220>rti (processional icon) will ç
be present. All the items of worship are offered only to that single ç
icon.
The expression however, does not apply to the pariv<193>ra-devat<193>s ç
or attendant deities that may be installed in the appropriate places.
See also <MS>BERA.
@SPACE = 
@NT = ekabhakta
@N1 = (`[taking] food once')
@SPACE1 = 
Ek<193>da·<200>, the eleventh day of every pak<218>a or fortnight ç
of the lunar month, is to be observed as a vrata or religious rite, ç
the main part of it being fasting. This fasting can be of four types, ç
of which the `ekabhakta' is the first. It permits a person who is ç
observing ek<193>da·<200>, to eat only once (= eka) in 24 hours. The ç
normal time prescribed for this taking of food is a little after noon.
Ekabhakta can be observed as a vrata independent of ek<193>da·<200> ç
also. The Mah<193>-bh<193>rata dilates upon the rewards attained ç
by observing ekabhakta for one year from M<193>rga·<200>r<218>a (December) ç
to K<193>rttika (next November) (Anu·<193>sanaparva 107.13-126).
See also <MS>EK°DA<185>®<D> and <MS>NAKTA.
@SPACE = 
@NT = ekabhavika doctrine
@N1 = (`the doctrine <R>ç
[that many karmas] produce one birth')
@SPACE = 
The doctrine of karma and punarjanma (rebirth) has been widely accepted ç
by almost all the schools of Indian philosophy.
There is a long discussion of some of the details of this doctrine ç
in the Vy<193>sabh<193><218>ya on the Yogas<220>tras (2.73) of ç
Pata<210>jali (200 <MS>B.<|>C.<D>). It is here that this word `ekabhavika' ç
has been introduced and discussed. Literally, it means `producing ç
one birth'.
As regards residual karma producing rebirth, four alternatives are ç
put forth and only one is accepted as true, ruling out the other three. ç
The alternatives are:
1)
@NK = Does one karma produce one birth?
2)
@NK = Does one karma cause several births?
3)
@NK = Do several karmas result in several births?
4)
@NK = Do several karmas give rise to only one birth?
Since numberless karmas have accumulated from beginningless time, ç
accepting either of the first two alternatives will give rise to a ç
highly confusing situation and people will lose all faith in the karmas ç
prescribed by the ·<193>stras.
The third alternative too has to be ruled out since it is not possible ç
for a j<200>va (individual soul) to assume several births simultaneously.
Then, by pari·e<218>any<193>ya or the doctrine of elimination of the ç
alternatives, we have to accept only the last alternative as true.
Among the accumulated karmas, one major karma, along with several ç
minor karmas which are compatible with the major one, becomes ripe ç
at the time of death and causes the next birth, deciding its j<193>ti ç
(type), <193>yus (duration of life) and bhoga (experiences, good and ç
bad).
See also <MS>KARMA.
@NT = Ekacakranagara
This was a small town where the P<193><207><195>ava princes along ç
with their mother Kunt<200> lived for some time, after escaping from ç
the burning house made of lac. A fierce demon Bak<193>sura by name, ç
was living nearby. He used to attack this little town and would eat ç
up whomsoever he could lay his hands on. Then the people of the town ç
appealed to him not do so, but would themselves send a person everyday ç
as his food. When Kunt<200> came to know of this through her hosts, ç
whose turn it was to send a member of their family, she sent Bh<200>ma ç
instead. Bh<200>ma killed the demon thus ridding the town of the great ç
tormentor.
@NT = ekada<207><195>in
@N1 = (`One [who holds] a single staff<%-27><%8>'<%0>)
A da<207><195>a or a staff is an important insignia of a sa<221>ny<193>sin ç
(monk). Among such sa<221>ny<193>sins called `da<207><195>is', there ç
are two types: ekada<207><195>is and trida<207><195>is. The former ç
carry only one (eka = one) staff (of bamboo) where as the latter carry ç
three sticks tied together (tri = three) as one, to facilitate carrying.
The da<207><195>a stands for dama or self-control. If trida<207><195>a ç
stands for control over body, speech and mind, ekada<207><195>a stands ç
for control over the mind only, since that automatically leads to ç
the control of the other two also.
The paramaha<221>sa sa<221>ny<193>sins accept a da<207><195>a at the ç
time of taking sa<221>ny<193>sa, but break it and discard it in a ç
river, since they are supposed to have attained the highest state ç
wherein they do not need to carry such insignias.
@SPACE = 
@NT = Ekadanta
@N1 = (`One who has only one tusk')
@SPACE = 
Ga<207>e·a or Ga<207>apati, one of the most popular and widely worshipped ç
Hindu deity, has an elephant's head and a human body. Out of his two ç
tusks, one is full whereas the other is broken. It is because of this ç
that he is known as `Ekadanta'.
The story goes that he lost his tusk in his fight with Para·ur<193>ma.
Symbolically, the broken tusk stands for this impermanent, imperfect ç
world where as the full tusk stands for the perfect.
In iconographical works Ekadanta Ga<207>apati is shown as a special ç
aspect of Ga<207>apati, blue-black in colour and withfour arms. In ç
them he carries ku<219>h<193>ra (hammer), ak<218>am<193>l<193> (rosary), ç
la<195><195>u (sweet preparation) and danta (his own broken tusk).
See also <MS>GAØAPATI.<D>
@NT = ek<193>da·a-gurus
@N1 = (`eleven gurus')
In the Hindu religio-cultural tradition, the guru or teacher has an ç
important place. The word itself means `one who teaches the scriptures' ç
like the Vedas. However, it is used in a much wider sense indicating ç
anyone who deserves respect, like the spiritual preceptor.
The Devala Sm<216>ti lists the fallowing eleven persons (ek<193>da·a ç
= eleven) as gurus: <193>c<193>rya (Vedic teacher), father, elder ç
brother, king, maternal uncle, father- in-law, one who protects or ç
gives shelter, maternal grandfather, paternal grand- father, one who ç
is superior in caste and paternal uncle.
@NT = Ek<193>da·a-Rudras
@N1 = (`The group of eleven Rudras')
Though Rudra/<185>iva has been projected as one of the trinity, representing ç
the destructive aspect of God, there are also minor deities called ç
Rudras who are sometimes listed as eight and sometimes as eleven. ç
They may be ga<207>adevat<193>s, attendants of <185>iva.
The following are some of the deities common to the different lists ç
of eleven Rudras found in the epics and the pur<193><207>as: Ajaikap<193>t, ç
Ahirbudhnya, Pin<193>ki, Tryambaka, Hara, Apar<193>jita, V<216><218><193>kapi, ç
<185>ambhu, and others.
Almost all these names are those of Rudra/<185>iva himself.
@NT = ek<193>da·<200>
@N1 = (`the eleventh [day])
@SPACE1 = 
Even in the mind of an average ignorant Hindu, ek<193>da·<200> and ç
upav<193>sa (fasting) have practically become synonymous! Fasting ç
as a spiritual discipline† whether as an expiation for sins committed ç
or for gaining self-control†has been an age-old practice. When fasting ç
reduces the sway of the flesh over the mind, it is much easier to ç
control it and direct it towards God, so that it can `live near him'. ç
In fact, this is the literal meaning of the word `upav<193>sa' (upa ç
= near, v<193>sa= living).
Ek<193>da·<200> (eleventh day in both halves of the lunar month†·uklapak<218>a ç
and k<216><218><207>apak<218>a) can be observed just as a spiritual ç
discipline or as a `vrata' with all the concomitant rules. Again, ç
if observed as a vrata, it can be `nitya' (compulsory) or `k<193>mya' ç
(motivated by desires). In the former case only ·ukla ek<193>da·<200>s ç
need be observed. As a k<193>mya-vrata, it can be observed on both ç
the days.
Whenever it is undertaken as a vrata, apart from the fasting, sa<209>kalpa ç
(resolve), worship of Vi<218><207>u and j<193>gara<207>a (keeping ç
vigil in the night) become obligatory. It is interesting to note that ç
ek<193>da·<200> is also called ``Hariv<193>sara' (Hari's or Vi<218><207>u's ç
day) and only worship of Vi<218><207>u has been prescribed. In fact, ç
for the Vai<218><207>avas (those belonging to the cult of Vi<218><207>u) ç
it is compulsory! Since fasting and keeping vigil on the M<193>sa·ivar<193>tri ç
days (caturda·<200> of k<216><218><207>apak<218>a in every month) ç
was compulsory for the <185>aivas, they may have been omitted from ç
its purview.
@SPACE1 = 
The pur<193><207>as and the dharma·<193>stras, though they prohibit ç
the partaking of cooked food on ek<193>da·<200> days, have made many ç
concessions to the general human weakness towards food. If one eats ç
only once in the day around noon, it is called `ekabhukta;' if it ç
is only in the night, it is `nakta;' if the food is taken once a day, ç
only when it is got by chance, without begging for it, it is `ay<193>cita.' ç
The last, however, seems to apply only to pr<193>ya·-cittas or expiations ç
for sins.
In all, there are 24 ek<193>da·<200>s in a lunar year. They are given ç
different names as follows:
@SPACE = 
@L4 = <P8B>Month      Bright-fortnight   Dark-fortnight<R>ç
<P255D>Caitra	K<193>mad<193>	Var<220>thin<200><R>ç
Vai·<193>kha	Mohin<200>	Apar<193><R>ç
Jye<218><219>ha	Nirjal<193>	Yogin<200><R>ç
°<218><193><195>ha	<185>ayan<200>	K<193>mik<193><R>ç
<185>r<193>va<207>a	Putrad<193>	Aj<193><R>ç
Bh<193>drapada	Parivartin<200>	Indir<193><R>ç
°·vina	P<193>·<193><209>ku·<193>	Ram<193><R>ç
K<193>rttika	Prabodhin<200>	Utpatti<R>ç
Agrah<193>ya<207>a	Mok<218>ad<193>	Saphal<193><R>ç
<+>(M<193>rga·<200>r<218>a)<R>ç
Pau<218>a (Pu<218>ya)	Putrad<193>	<218>a<219>-til<193><R>ç
M<193>gha	Jay<193><|>or<|>Bh<200><218>m<193>	Vijay<193><R>ç
Ph<193>lguna	°malak<200>	P<193>pamocan<200>
@SPACE = 
@SPACE = 
Among these, however, °<218><193><195>ha ·ukla ek<193>da·<200> called ç
`<185>ayan<200>' and K<193>rttika ·ukla ek<193>da·<200> named as `Prabodhin<200>' ç
are important since Vi<218><207>u is supposed to sleep onthe <185>ayan<200> ç
day and wake up on the Prabodhin<200> day, as the very names indicate. ç
<185>ayan<200> is also called `Prathamaik<193>da·<200>'. A very big ç
festival is held at Pha<207><195>ar<193>pur of Maharashtra on this ç
day. Devotees (called V<193>rkar<200>s) come from different parts ç
and assemble in thousands to do bhajans (devotional singing).
The ek<193>da·<200> of M<193>rga·ira-·ukla-pak<218>a is observed as ç
G<200>t<193> Jayant<200>. It is on this day that <185>r<200> K<216><218><207>a ç
taught the Bhagavadg<200>t<193> to Arjuna on the battle-field of ç
Kuruk<218>etra, before the Mah<193>bh<193>rata war. Apart from fasting ç
and worship of the G<200>t<193>c<193>rya K<216><218><207>a, there ç
will be a ceremonial chanting of the text and some times, discourses ç
expounding the same.
The Pau<218>a-·ukla-ek<193>da·<200> is well-known as Vaiku<207><219>ha-ek<193>da·<200>. ç
On this day, thousands of people gather in Vi<218><207>u temples. ç
One of the main doors called `Vaiku<207><219>ha-dv<193>ra' which is ç
normally kept closed throughout the year, is thrown open on this day. ç
The devotees who pass through this door for the dar·an of the Lord ç
are believed to go to Vaiku<207><219>ha, the abode of Vi<218><207>u. ç
It is said that, long back, the devotee Rukm<193><209>gada who was ç
being forced by an ogress to break his ek<193>da·<200> fast, against ç
the norms of the vrata, was saved by Vi<218><207>u and was taken to ç
Vaiku<207><219>ha on this day. Hence the name. There is a very big ç
festival on this day at the Ra<209>gan<193>tha temple of <185>r<200>ra<209>gam ç
in Tamil Nadu, which goes on for 21 days.
@NT = Ek<193>da·in<200>
@N1 = (`that which is eleven times')
See <MS>ATIRUDRA.<D>
@NT = ekade·in
@N1 = (`One who upholds only one aspect')
In the Indian philosophical systems, when a statement is made by the ç
main proponent, objections against it are raised by others opposed ç
to that school. Such an objector usually takes one part (ekade·a= ç
one part) of the statement of the proponent and tries to criticise ç
it. Such an objector is called `ekade·in'. A more common word for ç
such an objector is `p<220>rvapak<218>in' (one who holds the prima ç
facie view).
@NT = ekadhana
In the Somay<193>gas (Vedic sacrifices using the juice of the soma ç
creeper for oblations) 3 to 11 earthen jugs are used to keep water ç
collected from a running stream, early in the morning, on the very ç
day of pressing the stalks for the juice. This is later mixed with ç
the soma juice. The earthen jug used for this purpose has been named ç
`ekadhana'. It is rather difficult to give its derivative meaning.
@NT = Ek<193>gnik<193><207><195>a
@N1 = (`section [dealing with a person having] one fire')
The Ved<193><209>gas or `limbs of the Vedas' are important subsidiary ç
works that help the student of the Vedas not only to understand them ç
but also perform correctly the various rites mentioned therein. The ç
Kalpas<220>tras are one of the six such Ved<193><209>gas.
The °pastamba Kalpas<220>tras is one of the oldest among the Kalpas<220>tras ç
and belongs to the K<216><218><207>a Yajurveda. The 25th and the ç
26th pra·nas or prap<193><219>hakas or sections of this work are together ç
called Ek<193>gnik<193><207><195>a or Mantrap<193><219>ha. Sometimes ç
it is shown as the 31st and the 32nd sections also. There is a well-known ç
commentary by Haradatta Mi·ra (<MS>A.<|>D.<D> 1100) on this Ek<193>gnik<193><207><195>a.
The word itself might have been derived from the fact that all the ç
rites and rituals dealt with here, concern an average householder ç
keeping one fire (=eka + agni), the g<193>rhapatya fire or the g<216>hy<193>gn<200>.
The  first  chapter  comprises  131 mantras spread over 18 kha<207><195>as ç
or sections; The second has 356 mantras in 22<|>kha<207><195>as. Almost ç
all the topics described here belong to the field of dharma·<193>stras. ç
They can be briefly stated as follows:
The sa<221>sk<193>ras or sacraments of viv<193>ha (marriage), upanayana ç
(investiture with the sacred thread and allied rites), sam<193>vartana ç
(graduation from the guru-kula), rites connected with a pregnant mother ç
and the new born child, rites connected with the building of a new ç
house, offering of cooked food prepared from the first agricultural ç
crop, ·r<193>ddhas (obsequial rites), various kinds of japa, several ç
religious rituals to offset the evils that befall one in life, other ç
rituals to get certain desires fulfilled and a few other minor rites.
See also <MS>°PASTAMBA.<D>
@NT = Ek<193>ha
@N1 = (`of one day's [duration]')
Any Soma sacrifice of one day's duration (eka = one, ahan = day) is ç
called `Ek<193>ha'. It is distinguished from Ah<200>na and Sattra ç
which are of longer duration. For instance, Agni<218><219>oma sacrifice, ç
which is a part of Jyoti<218><219>oma, is an Ek<193>ha. The main rite ç
of pressing soma juice is performed here in one day.
@NT = Ekaja<219><193>
@N1 = (`[The goddess] with a single braid of hair')
One of the aspects of the Dev<200> or the Divine Mother, Ekaja<219><193> ç
is another name for T<193>r<193>, also called `Ugrat<193>r<193>'. ç
She is so called since her ja<219><193> or braided hair sticks upright ç
on the head as a single unit (eka= single). She is the terrific aspect ç
of the Dev<200> that killed <185>umbha and Ni·umbha (vide K<193>lik<193> ç
pur<193><207>a Ch. 60).
She is probably the Hindu edition of a Buddhist goddess of the Vajray<193>na ç
school.
The works Mantramahodadhi and S<193>dhanam<193>l<193>  contain  details  of  her ç
mantra and procedure of worship.
See also <MS>UGRAT°R°.<D>
@NT = ekaj<200>vav<193>da
@N1 = (`the view [that there is only] one soul')
<185>a<209>kara (<MS>A.<|>D.<D> 788-820) gave only the main outlines ç
of Advaita philosophy in his writings. However, many gaps regarding ç
the nature of the j<200>va, nature and locus of avidy<193> and m<193>y<193>, ç
the need to accept a greater degree of reality for the world to facilitate ç
the practice of Ved<193>ntic s<193>dhan<193>s had to be filled up. ç
Later writers who dealt with these aspects developed various schools ç
of Advaita, generally known now as `Post-<185>a<209>kara Advaita'.
One such school is the `ekaj<200>vav<193>da' of Prak<193>·<193>nanda ç
(<MS>A.<|>D.<D> 15th/16th century) propounded in his famous work Ved<193>nta- ç
siddh<193>nta-mukt<193>val<200>. According to this theory there is ç
only one j<200>va (eka = one) bound by one avidy<193> (nescience). ç
Hence when his avidy<193> is destroyed, he is liberated. There is ç
none else in bondage, to be liberated, since the entire world and ç
all the other j<200>vas are only figments of his imagination brought ç
about by his avidy<193>!
This j<200>va is sometimes identified with Hira<207>yagarbha, the ç
world soul.
This school did not become popular. Only one writer of the later period, ç
J<210><193>nottama Bha<219><219><193>rka, has supported it in his ç
Vidy<193>·r<200>, a subcommentary on the Brahmas<220>tras.
See also <MS>D<184><186><187>I-S<184><186><187>I-V°DA.<D>
@NT = Ek<193>k<218>ara-Ga<207>apati
@N1 = (`Ga<207>apati<R>ç
[indicated by] one letter')
Ga<207>apati or Ga<207>e·a, the elephant faced deity, is one of the ç
most popular of the gods of Hinduism. His b<200>j<193>k<218>ara (theseed-letter ç
containing his power and essence) is `ga<221>'. That particular form ç
which is associated with this letter and hence is to be meditated ç
upon while repeating it, is called `Ek<193>k<218>ara-Ga<207>apati'. ç
It is one of the eight famous aspects recommended for attaining siddhis ç
or supernatural powers.
Ek<193>k<218>ara-Ga<207>apati is described as stout and dwarfish. ç
He is red in colourand is seated in padm<193>sana or lotus posture. ç
He carries b<200>j<193>p<220>ra (pomegranate), p<193>·a (lasso) and ç
a<209>ku·a (goad) in three hands, the fourth one showing the gesture ç
of varada (bestowing boons).
This form is specially worshipped to attain happiness in life.
See also <MS>GAØAPATI.<D>
@NT = Ek<193>k<218>arako·a
See <MS>M°TR°NIGHAØ<187>U<D>.
@NT = Ek<193>k<218>ara Upani<218>ad
This is a small minor Upani<218>ad in13 verses, assigned to the K<216><218><207>a ç
Yajurveda.
It deals with God or Brahman, the One (eka<|>=<|>one), who is ak<218>ara ç
or indestructible and is in the form of a laudatory hymn.
When the s<193>dhaka or the spiritual aspirant meditates upon <185>iva, ç
along with his consort Um<193>, in his sahasr<193>ra-cakra, at the ç
top of the head, and as one with him (<185>iva), he realises his identity ç
with <185>iva who is the One without a second, and the indestructible ç
(ak<218>ara) reality.
This Ek<193>k<218>ara or the Supreme God, is the creator of this world, ç
the lord of all beings and the primeval being. He is the protector ç
of the world. Though unborn, he is all-pervading. He is the fire and ç
again, he is the sacrifice.
He is Hira<207>yagarbha, the world-soul. He is the sun. He is Kum<193>ra ç
or Skanda (the commander of the gods). He is Indra, the wielder of ç
the thunderbolt. He is the desires of human beings as also the mantras ç
uttered in sacrificial rites to fulfil them. He is the incarnations ç
like the Var<193>ha (Boar). He is all the Vedas as also the deity ç
worshipped through the Vedic rites. He it is, again, who has manifested ç
himself as the eleven Rudras.
He is man, woman and child.
In fact there is nothing here that is not the Ek<193>k<218>ara.
One who knows him, the ancient Lordwho has become all, will attain ç
the highest state.
See also <MS>UPANI<186>ADS.<D>
@NT = Ekalavya
One of the boy-heroes of the Hindu epics who has made an indelible ç
impression upon the minds of one and all, not only for his excellence ç
in the science of archery but also for his gurubhakti† unquestioning ç
devotion to the teacher†is Ekalavya. He was the son of Hira<207>ya-dhanus, ç
the chieftain of the ni<218><193>das, a forest tribe.
When he approached Dro<207><193>c<193>rya, the unrivalled preceptor ç
of archery and military sciences, to be accepted as his disciple, ç
the request was rejected since Ekalavya was a ·<220>dra by caste and ç
since the military sciences were the preserve of the k<218>attriyas. ç
Undeterred, Ekalavya prepared a clay-image of Dro<207><193>c<193>rya, ç
kept it in the field of his practice and started training himself ç
before it, after duly worshipping it since he had mentally accepted ç
Dro<207><193>c<193>rya as his guru! The intensity of his devotion ç
to the guru and the relentless practice made him, very soon, an expert ç
archer.
One day, when the P<193><207><195>ava princes had come to the forest ç
for hunting, they found that one of their hunting dogs returned with ç
its mouth packed with seven arrows, unable to bark but absolutely ç
unharmed! When the P<193><207><195>ava princes discovered that it ç
was the hunter-boy Ekalavya's feat, they were dumbfounded. On learning ç
that Dro<207><193>c<193>rya was his `teacher', Arjuna became upset, ç
since the latter had promised to make him the greatest archer of his ç
times. Being in a fix, Dro<207><193>c<193>rya asked Ekalavya to give ç
his right thumb as his `fees'. Absolutely unmoved, the boy cut off ç
his right thumb and offered it at his feet! Thus Ekalavya lost his ç
supremacy in archery though he was still good at it, but gained a ç
permanent place in our history.
He is said to have challenged <185>r<200> K<216><218><207>a once for ç
a fight and died at his hands.
See also <MS>DROØ°C°RYA.<D>
@NT = ekali<209>ga
@N1 = (`[a place where there is] only one <185>ivali<209>ga')
Those who perform s<193>dhan<193>s are advised to do them in certain ç
places so that they could get the siddhis or results (especially psychic ç
powers) more quickly. One such place is called `ekali<209>ga' or `ekali<209>gak<218>etra'. ç
It is defined as a place where there is a <185>ivali<209>ga and no ç
other li<209>ga is found within a radius of five kro·as (24 kms. or ç
15 miles).
The word may stand for Kubera, the lord of wealth, also since he is ç
said tohave only one eye (li<209>ga<|>=<|>indriya, organ or eye).
In the state of Rajasthan, 19 Kilo- metres (12 miles) from the city ç
of Udaipur, there is a famous temple of Ekali<209>gaj<200>. The <185>ivali<209>ga ç
here has four faces on the four sides. This <185>ivali<209>ga was ç
the family deity of the rulers of the former princely State of Mewar. ç
There is a lake called Indras<193>gar nearby. Spread over the nearby ç
area, are the temples of £u<219>e·vara, Dh<193>re·vara, Ga<207>e·a, ç
Vanav<193>sin<200> and Lak<218>m<200> also.
@NT = Ek<193>mra-k<218>etra
@N1 = (`a place of pilgrimage with one mango tree')
K<193><210>c<200>puram or K<193><210>c<200> is one of the seven most ç
holy places of pilgrimage for Hindus.
Once P<193>rvat<200>, the divine spouse of <185>iva, incurred his ç
wrath and was cursed by him to become ugly. Later, after repentance, ç
<185>iva advised her to perform severe austerities to regain him. ç
She sat under a single mango tree (eka = one, <193>mra = mango tree), ç
regained her beautiful form by the grace of Vi<218><207>u and then ç
performed severe austerities as advised. Pleased with her, <185>iva ç
appeared and accepted her†now known as K<193>m<193>k<218><200>† once ç
again. Hence, this place†the modern K<193><210>c<200>puram†came to ç
be known as Ek<193>mrak<218>etra and the <185>iva in the temple there, ç
as Ek<193>mran<193>tha.
There is an ancient mango tree there with a small shrine below it ç
containing the image of P<193>rvat<200> in meditation
See <MS>K°<178>C®PURAM<D> for details.
@NT = ekamukhali<209>ga
@N1 = (`one-faced li<209>ga')
<185>iva, the god of dissolution of the Hindu Trinity, is worshipped ç
invariably in the form of a li<209>ga or an emblem of rounded surface. ç
(See <MS>LI<177>GA<D> for details.) One of the several varieties of ç
li<209>gas is the m<193>nu<218>ali<209>ga, a li<209>ga prepared by ç
human beings, as per the directions given in the °gamas like Ajit<193>gama ç
and Supra-bhed<193>gama.
In the mukhali<209>ga of this variety, one or more mukhas or faces ç
of <185>iva are carved on the p<220>j<193>bh<193>ga (the cylindrical ç
part seen above the ground). If there is only one mukha, it is then ç
called `ekamukhali<209>ga'. It is carved on the round p<220>j<193>bh<193>ga ç
facing the main door of the shrine, and occupying 120 degrees of space. ç
Its height should be more than one hasta or t<193>la but less than ç
five t<193>las.
See also <MS>MUKHALI<177>GA<D> and <MS>T°LAM°NA SYSTEM.<D>
@NT = ekanak<218>atra viv<193>ha
@N1 = (`marriage where <R>ç
the nak<218>atra or asterism is the same')
The Hindus consider marriage as a sa<221>sk<193>ra or a sacrament. ç
Hence it is much more a religious act than just a social contract.
A factor to be considered before fixing a marriage between a boy and ç
a girl is whether the horoscopes of the two are in consonance with ç
each other. One of the most important considerations is the nak<218>atra ç
of birth of the two. Generally, the nak<218>atras should be different. ç
If they are the same, then they should be of the auspicious type. ç
For instance, the nak<218>atras Rohi<207><200>, °rdr<193>, Makha, ç
Vi·<193>kha, Pu<218>ya, <185>r<193>va<207>a, Revat<200> and Uttar<193>bh<193>dr<193> ç
are considered highly auspicious. On theother hand, P<220>rv<193>bh<193>dra, ç
Dhani<218><219>h<193>, Punarvasu, K<216>ttik<193>, M<216>ga·ira, Citta, ç
Hasta, Uttara-phalgun<200>, Jye<218><219>h<193>, P<220>rv<193>-<218><193><195>h<193> ç
and Uttar<193><218><193><195>h<193> are considered prohibited and ç
hence, inauspicious. Even when marriage is performed between persons ç
having a permitted ekanak<218>atra, the p<193>das (quarters) should ç
be different.
Violation of these rules may result in evil consequences including ç
the death of one of the spouses.
See also <MS>VIV°HA.<D>
@NT = Ek<193>na<221>·<193>
@N1 = (`One who is without parts')
Ek<193>na<221>·<193> is a folk goddess who is identified with Durg<193>, ç
who was the daughter of Nanda and Ya·od<193>. It was she whowas exchanged ç
for baby K<216><218><207>a. She escaped from the clutches of the tyrant ç
Ka<221>sa, warned him of his approaching death and disappeared.
She is also described as the tribal divinity of the V<216><218><207>i ç
clan, of K<216><218><207>a-V<193>su- deva. She again, is pictured ç
as Subhadr<193>, the sister of Balar<193>ma and K<216><218><207>a.
Iconographical representations show her in the standing posture, with ç
two arms, one resting on the loins and the other holding a lotus.
@NT = Ekan<193>tha
@N1 = (<MS>A.<|>D.<D> 1533-1606)
If Hindu religion and culture have survived the onslaughts of the ç
turbulent vicissitudes in Indian history, it is not a little due to ç
its great saints, especially those of the bhakti cults. One such bright ç
star that arose in the firmament of western India, in Maharashtra, ç
was Ekan<193>tha (also spelt as Ekn<193>th). With a rare and balanced ç
combination of j<210><193>na (knowledge) and bhakti (devotion), he ç
was a true successor of another great saint of Maharashtra, Sant J<210><193>ne·vara ç
(13th century <MS>A.<|>D.<D>).
Born in the family of another holy man Bh<193>nud<193>sa (b. <MS>A.<|>D.<D> ç
1448), at Pai<219>ha<207>, Ekan<193>tha lost both his parents early ç
in life. He was brought up by his grand parents. Even in his childhood ç
days he had developed a great love and attraction for that inimitable ç
scripture of devotion to K<216><218><207>a, the Bh<193>gavata. Inspired ç
by an inner call heard at a nearby <185>iva temple, he ran away to ç
Devaga<195>h, without informing his guardians, and fell at the feet ç
of Jan<193>rdana Sv<193>m<200>, a renowned saint of his times. Jan<193>rdana ç
Sv<193>m<200> (<MS>A.<|>D.<D> 1504-1575) was the killed<193>r (officer ç
in-charge of the fort) of the Devaga<195>h fort. He was a worshipper ç
of Datt<193>treya (an aspect of Vi<218><207>u) and had had several ç
mystical experiences. He could intuit the greatness of Ekan<193>tha ç
and hence readily accepted him as his disciple. Under his able guidance, ç
Ekan<193>tha speedily progressed in his s<193>dhan<193>s or spiritual ç
practices. By the grace of his guru, he could even have visions of ç
Datt<193>treya.
@SPACE1 = 
When Jan<193>rdana took Ekan<193>tha on a pilgrimage, he commanded ç
him to translate the Sanskrit Bh<193>gavata into Mar<193><219>hi ç
verses. Ekan<193>tha undertook the great task with tremendous faith ç
and devotion and successfully completed it in course of time.
His grandparents at Pai<219>ha<207> somehow got wind of his whereabouts ç
and appealed to Jan<193>rdana to send him back to them. Jan<193>rdana ç
not only complied but also commanded Ekan<193>tha to marry and settle ç
down as a householder at Pai<219>ha<207> itself. Accordingly, Ekan<193>tha ç
married an extraordinarily pious girl Girij<193>b<193><200> by name, ç
and started living with his grandparents. Being very old, they passed ç
away peacefully soon after.
During his long stay at Pai<219>ha<207> he not only spread the message ç
of the Bh<193>gavata in the local language but also performed many ç
miracles which ultimately silenced his enemies, critics and cavillers. ç
Some of the miracles attributed to him are: being seen in more than ç
one place simultaneously, his dead ancestors appearing physically ç
to eat the food offered in the ·r<193>ddha, postponing the time of ç
death of K<216><218><207>ad<193>sa until he completed his literary ç
work on the R<193>m<193>ya<207>a, making the stone image of Nandi ç
(bull-mount of <185>iva) in a temple eat grass and so on.
He was also responsible for the renovation of the tomb of the saint ç
J<210><193>ne·vara at <193><202>and<200> near Pu<207>e or Poona.
He passed away in <MS>A.<|>D.<D> 1606.
@NT = ek<193>ntadharma
@N1 = (`a dharma [which has only] one end')
In  the  devotional  scriptures  of Hinduism (vide N<193>rada Bhaktis<220>tras ç
70), devotees of God, of the highest type, are called `ek<193>ntins'. ç
It means those devotees whose only end and aim of life is God (eka ç
= one, anta = end). Their devotion and consequent characteristics ç
manifested there of can be described as `ek<193>nta-dharma'.
Some of these are: shedding tears in the name of God, being overcome ç
by devotion; hearty conversations with other devotees on topics related ç
to God and spiritual disciplines; visiting places of pilgrimage; performing ç
scripture-ordained actions as a model for others; deep immersion in ç
the thoughts of God; not making any distinction based on caste, learning, ç
pedigree, wealth and so on, while dealing with others.
@NT = ek<193>ntin
See <MS>EK°NTADHARMA.<D>
@NT = Ekap<193>dam<220>rti
@N1 = (`image with one leg')
God has sometimes been described in the Hindu scriptures as Ekap<193>t ç
or Ekap<193>da<199> since the manifested universe is only a quarter ç
(p<193>da = quarter) of him. The word is applied to both <185>iva ç
and Vi<218><207>u. `Ajaikap<193>t' is one of the epithets of <185>iva, ç
used even in the <184>gveda (6.50.14; 10.64.4).
The Ekap<193>dam<220>rti is actually the iconographic representation ç
of the Vedic concept of <185>iva as Ajaikap<193>t. In this form he ç
has only one leg. He is described as luminous like a million suns, ç
three-eyed and four-armed, in which he carries <219>a<209>ka (chisel) ç
and M<216>ga (antelope). He is exhi-biting the abhaya as also the ç
varada mudr<193>s in the other two hands.
`Ekap<193>da'  (one  leg)  signifies  the Supreme Godhead as the sole ç
support of the whole universe.
@NT = Ek<193><218><219>ak<193>
@N1 = (`The eighth day<R>ç
par excellence')
Performance of certain rites for the benefit of departed ancestors ç
had been an ancient custom in Hinduism. The Ek<193><218><219>k<193> ç
rite is one such, performed on the 8th day of the dark fortnight, ç
especially in the month of M<193>gha (January-February).
See <MS>A<186><187>AK°<D> for details.
@NT = ekat<193>la
@N1 = (`of one t<193>la or span')
See <MS>T°LAM°NA SYSTEM<D> for details.
In iconography, this measure is used to prepare images of the lowest ç
class of spirits and kabandhas (headless torsos).
In classical Indian music, it is the name of a t<193>la or measure ç
of time comprising 12 m<193>tr<193>s or instants of time, divided ç
into four equal parts, each consisting of 3 m<193>tr<193>s. These ç
m<193>tr<193>s are represented by such letters as dh<200>, dh<193>, ç
na, t<216>ka and so on. These letters also indicate the places on ç
the percussion instrument where that particular beat is to be struck.
@NT = ekav<193>kyat<193>
@N1 = (`single sentence-ness')
@SPACE1 = 
While interpreting the various passages from the Vedas and the Upani<218>ads, ç
the ancient and medieval commentators have exercised great care. One ç
of the principles they have adopted in their commentaries and interpretations ç
is `ekav<193>kyat<193>'.
A v<193>kya or a sentence is not just an aggregate of words, grammatically ç
or syntactically connected. It should also convey sense. When the ç
sense is not complete and needs further clarification, which is given ç
in one or two or more sentences, all these sentences together will ç
then have `ekav<193>kyat<193>.'
For instance, take these sentences:
(1)
@NK = parvato vahnim<193>n (There is fire in the hill.)
(2)
@NK = dh<220>m<193>t (Because smoke is seen there.)
(3)
@NK = yatra yatra dh<220>ma<199>, tatra tatra vahni<199> (wherever ç
there is smoke, there is fire.)
There are three sentences here. Each one of them conveys a different ç
idea. But all the three put together produce a single knowledge in ç
our mind, viz., that there is fire on the hill. Thus there is ekav<193>kyat<193> ç
in all these three statements.
@NT = ek<193>yana
@N1 = (`single [or only] support')
This word has been used in the Upani<218>ads in two senses†in its ç
usual sense of `the only support' and in a technical sense, as `the ç
science of ethics'. In the Ch<193>ndogya Upani<218>ad (7.1.2, 4; ç
7.2.1) it has been used in the latter sense, whereas in the B<216>had<193>ra<207>yaka ç
Upani<218>ad (2.4.11 and 4.5.12) it is the former that is intended.
@SPACE1 = 
By tracing the origin of all objects to their immediate causes, the ç
Upani<218>ad comes to the conclusion that Brahman is the ultimate ç
cause and support†ek<193>yana †of the whole world.
@NT = ekoddi<218><219>a
@N1 = (`intended for one')
Performance of certain religious rites for the peace of the soul of ç
a dead person is an ancient custom in almost all religions and cultures ç
of the world. In Hinduism, such rites are called by the general term ç
`·r<193>ddha.'
Generally such ·r<193>ddhas are performed for the three (dead) paternal ç
ancestors of a person and are termed `p<193>rva<207>a·r<193>ddha.'
The ekoddi<218><219>a ·r<193>ddha, on the other hand, is performed ç
only for the benefit of one person, who has just passed away (eka= ç
one, uddi<218><219>a = intended for).
This rite is done throughout one year after death. After that, the ç
dead person attains the realm of his forefathers through the special ç
ritual of `sapi<207><195><200>-kara<207>a'. (See <MS>SAPIØ£®KARAØA<D> ç
for details.)
In this ·r<193>ddha there is no offering of cooked food or <193>jya ç
(ghee) to be offered into the fire (called agnaukara<207>a). There ç
is no invitation to the br<193>hma<207>as to represent the Vi·vedev<193>s. ç
The mantras uttered and the questions asked of the other br<193>hma<207>as ç
are also different.
An uneven number of Br<193>hma<207>as are fed on the eleventh day.
See also <MS><185>R°DDHA.<D>
@NT = Elephanta
It is an island situated about 11 kilometres (7 miles) from the Bombay ç
(now Mumbai) harbour to the north-east. Its circumference is about ç
7 kilometers (4<|><P7W1><$E1 over 2> <P255D>miles). Its original name ç
was <185>r<200>pur<200> or Gh<193>r<193>pur<200> and was attached ç
to the Konkan region of Maharashtra. It was under the political control ç
of several dynasties of kings like Western C<193><202>ukyas, C<193><202>ukyas ç
under Pulake·in II (<MS>A.<|>D.<D> 600), the Y<193>davas of Devagiri ç
and so on, before coming under British rule in <MS>A.<|>D.<D> 1774.
@SPACE = 
@SPACE = 
@SPACE = 
The island got its name due to the images of elephants†now missing†on ç
the steps of one of the temples there. It is famous for its archaeological ç
monuments, especially the six cave temples belonging to the <185>aiva ç
cults, assigned to the 8th century <MS>A.<|>D.<D>
The largest of these caves in solid rock faces north. It is 39 metres ç
(130 ft.) long. The width is also, approximately, the same. But there ç
are mukhama<207><219>apas† subsidiary halls†measuring 16 metres (54ft.) ç
by 5 metres (16<|><P7W1><$E 1 over 2 ><P255D> ft.) in the west, the ç
north and the east. The average height is 5 metres (16 to 17 ft.). ç
There is a small sanctum with a li<209>ga, towards the west. It also ç
has two figures of the dv<193>rap<193>lakas (gate-keepers).
The Elephanta caves contain a number of huge images (of the relief ç
type) of the <185>aiva cult. They are 3.6 to 5.4 metres (12 to 18 ç
ft.) in height. The most important of these images is that of Mahe·vara ç
<185>iva, also called `Trim<220>rti-<185>iva'. The main face represents ç
the Tatpuru<218>a or Mah<193>deva aspect of <185>iva. This face is ç
serene and beautiful. It has a ja<219><193>muku<219>a (hair dressed ç
up as a crown). The other two faces are those of Aghora or Bhairava ç
andV<193>madeva or Um<193>. The depiction of several†often contradictory†moods ç
in thesame image shows the excellence of workmanship. The whole image, ç
sculptured from the chest upwards, is inside a depression in the back ç
wall, 3 metres (10ft.) in depth and 6 metres (21 ft.) in width.
There are eight more images, all of <185>iva in his various aspects. ç
Some of them are: Na<219>ar<193>ja, <185>iva in meditation, R<193>va<207>a ç
shaking the Kail<193>sa mountain, <185>iva killing Andhak<193>sura ç
and Ardhan<193>r<200>·vara.
@NT = Ellora
Ellora†known earlier as E<202><220>ra has carved for itself a permanent ç
and enviable place in the archaeological map of India because of its ç
magnificent temple of Kail<193>san<193>tha (<185>iva). It is situated ç
on the bank of a small tributary of the God<193>var<200> river in ç
Maharashtra, at a distance of 64 kms. (40 miles) from Ajant<193> and ç
25 kms. (16 miles) from Aurangabad. There are 34 caves in all, containing ç
Hindu, (17 caves), Buddhist (12 caves) and Jain (5 caves) constructions ç
of various types like relief figures of mythological gods, Caitya ç
halls of prayer, living rooms for the bhik<218>us and so on.
@SPACE1 = 
It is the Kail<193>san<193>tha temple built by the R<193><218><219>rak<220><219>a ç
king, K<216><218><207>a I (<MS>A.<|>D.<D> 756-775) that is the chief ç
attraction of Ellora. It is a marvellous work of art, architecture ç
and building construction. The credit goes to the stone-cutters and ç
carvers. There is reason to believe that they first dug a deep three-sided ç
trench from above the hill to obtain a massive isolated block of rock ç
60 metres (197 ft.) long, 30 metres (98 ft.) wide and 30 metres high. ç
The temple was then fashioned from this rocky mass, working from the ç
top and the front, cuttingaway the rock, both externally and internally.
@SPACE = 
There are four parts in the temple: The main shrine, the entrance ç
gate to the West, a separate shrine for Nandi (<185>iva's mount) and ç
the cloisters surrounding the courtyard.
The temple stands on a lofty plinth 7.6 metres (25 ft.) high. The ç
friezes contain the figures of elephants and lions giving the impression ç
that they are carrying the whole temple on their backs. The vim<193>na ç
(tower) over the sanctum containing the li<209>ga, is 28.9 metres ç
(96 ft.) in height and is three-tiered. It is in the Pallava style ç
of temple architecture.
There is a hall (n<216>ttama<207><195>apa) of 16 pillars in front ç
of the sanctum. Next to it, connected by a bridge, is an elegant shrine ç
of Nandi, 6 metres (20 ft.) square. On either side of this shrine ç
there is a dhvajastambha (flag post), 15.5 metres (50ft.) high.
There is an imposing gateway at the front.
Around the base of the vim<193>na, there are five miniature shrines ç
which are now empty. They were probably meant for the Saptam<193>t<216>k<193>s, ç
Ga<207>e·a, Ca<207><195>a, Bhairava and P<193>rvat<200>.
Coming to the caves:
The 14th cave contains sculptures of <185>iva in the dancing pose ç
of T<193><207><195>ava, R<193>va<207>a, caught under the mount Kail<193>sa, ç
Lak<218>m<200>, Bhav<193>n<200>, Vi<218><207>u and Lak<218>m<200> ç
in Vaiku<207><219>ha, as also N<193>r<193>ya<207>a lying on serpent ç
<185>e<218>a.
The 16th cave, measuring 83 metres (276 ft.) by 46 metres (154 ft.) ç
is one of the finest cave temples of India, containing a large number ç
of sculptures depicting several incidents from the pur<193><207>as ç
dealing with <185>iva and P<193>rvat<200>.
The 17th cave, which measures 20 metres by 11 metres (64 ft. by 37 ç
ft.) is again devoted to <185>iva sculptures which include images ç
and figures of Vai<218><207>av<200>, Annap<220>r<207><193>,   P<193>rvat<200>,   Lak<218>m<200>   and ç
Sarasvat<200>.
The Buddhist caves, are mostly plain, without any ornamentation. The ç
3rd and the 4th caves contain sculptures of Buddha seated on a lotus-throne ç
or preaching sermons. The 12th cave contains an image of Buddha 3.5 ç
metres (11<|><P7W1><$E 1 over 2 > <P255D>ft.) high with other figures.
@SPACE1 = 
The 33rd cave is a Jaina shrine calledIndrasabh<193>. Other caves ç
contain the figures of T<200>rtha<209>karas, Gomma-<219>e·vara (32nd ç
cave) Yak<218>as and Yak<218>is.
Paintings of the Ajant<193> type†but inferior in quality†have been ç
discovered in cave no. 15 and have been assigned to the period 8th ç
century <MS>A.<|>D.<D> The most striking painting is that of Vi<218><207>u ç
and Lak<218>m<200> riding on the Garu<195>a and passing through the ç
clouds in the sky.
@NT = Epigraphica Indica
Epigraphs or inscriptions, especially those of a permanent nature ç
like stone edicts, are an important source of the history of a country. ç
Tracing them, collecting the texts of the same and translating them ç
into the current language is an arduous task. James Burgess (<MS>A.<|>D.<D> ç
1832-1916) who was the Director-General of Archaeology of the Government ç
of India took the lead and brought out the first issue of a journal ç
devoted to this, under the name Epigraphia Indica, in October 1888. ç
Bound volumes of such issues were brought out later in 1892 and 1894.
Originally, inscriptions in Sanskrit, Pr<193>k<216>t, the Dravidian ç
languages as also Arabic and Persian were brought out. Later on, it ç
was decided to drop the last two from the purview of the issues.
The well-known epigraphist Hultzch (<MS>A.<|>D.<D> 1857-1927) who was ç
the associate editor of this journal made some important changes in ç
it. As per his suggestion it was brought out once in three months. ç
One volume of eight such issues was published every two years. The ç
first seven issues contained the texts of the inscriptions and the ç
eighth, the index. The format too was changed.
@SPACE1 = 
The work has progressed fairly well. Till 1970, 36 volumes, containing ç
more than 15,000 pages of material, have been published.
Sten Konow (<MS>A.<|>D.<D> 1867-1948) was the last European editor. ç
After him many distinguished Indian scholars such as V.Venkiah, Hirananda ç
Sastry, K. N. Dixit, N. C. Chakravarthy and B. C. Chabra have worked ç
as editors.
Other scholars who have contributed to the journal's development include ç
John George Buhler (<MS>A.<|>D.<D> 1837-1898), Franz Kielhorn (<MS>A.<|>D.<D> ç
1840-1908), D. R. Bhandar-kar, R. D. Bannerji, R. C. Majumdar, C.R. ç
Krishnamacharlu and a host of others.
The journal, devoted entirely to the publication of inscriptions, ç
has made a name for itself in the annals of Indological research.
Epigraphia Karnatika started in <MS>A.D.<D> 1886 by Louis Rice ç
(<MS>A.<|>D.<D> 1837-1927) in Mysore, under the aegis of the then Maharaja ç
and Dewan also has carved out a distinguished place for itself.
@SPACE = 
@NT = e<218>a<207><193>traya
@N1 = (`three desires')
@SPACE = 
The Upani<218>ads, the crowning glory of Hindu Philosophy, often stress ç
the great importance of vair<193>gya or renunciation. Though this ç
is a negative aspect of s<193>dhan<193> (spiritual discipline), it ç
is of primary importance even as the cleaning of a cloth is necessary ç
before it is coloured.
The principal aspect of this vair<193>gya is e<218>a<207><193>trayaty<193>ga ç
or renunciation of three types of yearnings which are serious impediments ç
in the path of spiritual progress. The three desires†collectively ç
known as e<218>a<207><193>traya are: putrai<218>a<207><193> (the desire ç
for a son), vittai<218>a<207><193> (the desire for wealth) and lokai<218>a<207><193> ç
(the desire to attain heaven after death) (vide B<216>had<193>-ra<207>yaka ç
Upani<218>ad 3.5.1).
Since the first desire needs a wife for its fulfilment, it is also ç
called `j<193>yai<218>a<207><193>' or `d<193>rai<218>a<207><193>' ç
(desire for a wife).
Putrai<218>a<207><193> is aimed at discharging the debt called pit<216>-<216><207>a, ç
towards the forefathers, by the performance of obsequial rites like ç
·r<193>ddha. This will also prevent the person from going to hell ç
after death.
Vittai<218>a<207><193> helps one to perform the various Vedic sacrifices ç
by which one can get to heaven. This automatically satisfies lokai<218>a<207><193> ç
also.
However, all these three continue to bind the j<200>va or the individual ç
soul, to sa<221>s<193>ra or transmigratory existence. Hence the need ç
to give them up.
Medical treatises like those of Caraka (1400<MS> B.<|>C.<D>) replace ç
putrai<218>a<207><193> by pr<193><207>ai<218>a<207><193> (the desire ç
to live) in which case it is a good desire and hence need not be given ç
up.
@NT = Eschatology
@N1 = (`System of doctrines<R>ç
concerning death and after-life')
The Hindu scriptures do not consider death as the final end of life ç
and hence all the labours of a life properly lived, do not become ç
null and void. They teach that there is life after the death of ç
this physical body.
Hindu eschatology has four aspects. The first gives a prognostication ç
of the approach of death. The second gives the rites to be performed ç
by the dying person and/or his near relatives. The third deals with ç
the obsequies to be undertaken just after death and later, over a ç
period of time, up to one year. The fourth gives an account of what ç
happens to the j<200>va (soul) after death.
Some of the signs that indicate the approach of death as described ç
in the <185><193>ntiparva of the Mah<193>bh<193>rata as also in ç
the pur<193><207>as like the V<193>yupur<193><207>a, M<193>rka<207><195>eyapur<193><207>a ç
and Li<209>gapur<193><207>a are as follows: not being able to see ç
the star Arundhati or the pole-star or the full-moon; not seeing one's ç
own reflection in the eyeball of another; seeing the orb of the moon ç
with a hole in it; smelling hot obnoxious odour of a corpse even though ç
fragrant substances are brought near; loss of bodily heat; sudden ç
oozing of moisture from the left eye; not hearing the humming sound ç
in the ear, when the ears are closed with the fingers; not seeing ç
the light when the eyes are closed and pressed by the fingers; dreaming ç
of an ass or a tri·<220>la (trident) and so on.
As regards the second and third aspects, see <MS>ANTYE<186><187>I<D> ç
and <MS><185>R°DDHA<D> for details.
Now, coming to the fourth aspect, it is clearly guided by the theory ç
of karma and rebirth.
In the Upani<218>ads, three destinies are indicated for a dead person: ç
to be reborn again and again which entails a lot of suffering; to ç
go to pit<216>loka by the dh<220>m<193>dim<193>rga or pit<216>y<193>na; ç
to go to Brahmaloka by the arcir<193>dim<193>rga or Devay<193>na, ç
from which there is no return.
However, from the pit<216>loka, which is like svarga or heaven, there ç
is return to this world, after exhausting the fruits of all merit.
Those who have committed heinous crimes, called `mah<193>p<193>takas' ç
(like the murder of a br<193>hma<207>a or incest) go to abominable ç
hells like andhat<193>misra, raurava or kumbh<200>p<193>ka. The pur<193><207>as ç
enumerate as many as 32 such hells! They are probably different sections ç
in the torture chambers of Yama, the lord of death and the netherworld.
Those who have led a good life andhave performed meritorious deeds ç
as prescribed in the holy books, go to higher worlds such as svarga, ç
maharloka, janaloka and tapoloka to enjoy themselves.
In both these cases, the souls return to this world the bh<220>loka, ç
to continue the journey towards perfection.
@NT = Ethics
See <MS>DHARMA.
@END = <R>ç

