@NID = Yama lives there with his associates who praise him, to the ç
accompaniment of music of the flute.
According to the pur<193><207>as Yamaloka is a vast place surrounded ç
by four iron forts, with four main gates. There is a majestic auditorium ç
wherein many great kings of the past assemble.
Naraka or hell exists in one part of this world.
See also <MS>NARAKA<D> and <MS>YAMA<D>.
@NT = Yamasm<216>ti
Many writers of dharma·<193>stras have quoted several verses from ç
Yama or Yamasm<216>ti on various topics. Though no authentic work ç
of that title has been recovered, it is possible that a fairly big ç
work of that name existed. There are some printed editions published ç
by various agencies, but the number of verses is different from one ç
another, like 78 or 99 or 182. Some treatises called B<216>had-Yama ç
are also available in print.
The topics dealt with in these printed editions are: pr<193>ya·citta ç
(expiation for sins); ·uddhi (purification); ·r<193>ddha (obsequial ç
rites); lowest castes; partition; food and its pollution; crime and ç
punishment; litigation; some philosophical topics.
Many of the verses quoted by the authors of the dharma·<193>stras ç
are usually found in the printed edition of Manusm<216>ti.
@NT = Yamas<220>kta
The Yamas<220>kta is a part of the <184>gveda (10.14). It comprises ç
16 <216>ks or mantras. Yama, the god of death and dharma (righteousness), ç
is the <216><218>i or the sage to whom it was revealed. Yama, the ç
pit<216>s (manes) and S<193>rameyas (the two fierce dogs of Yama) ç
are the devat<193>s (divinities)  to  whom  the  s<220>kta  is addressed.
The first mantra urges the yajam<193>na (the sacrificer) to worship ç
(with oblations) Yama, who takes the souls of beings who have performed ç
good deeds, to higher worlds safely.
The second mantra praises Yama because he knows the paths by which ç
he takes us all.
The third mantra declares that the gods like Indra, Yama and B<216>haspati ç
are mutually benefited by the offerings given with the formulas†svadh<193> ç
and sv<193>h<193>†by the pit<216>s like A<209>girasas and <184>kvis.
The fourth mantra invites Yama to come along with the pit<216>s called ç
A<209>gir<193>s and make the sacrificer happy.
In the fifth mantra, Vivasv<193>n (the father of Yama) is also invited ç
for the same purpose.
After declaring that the pit<216>s†the Atharvas, the Bh<216>gus and ç
the Navagvas† are worthy of worship with the offerings of the soma ç
juice, the sixth mantra expresses the wish that we may deserve to ç
receive their grace and blessing.
If a yajam<193>na dies before the sacrifice is completed, the hot<216> ç
(priest of the <184>gveda) recites the seventh and the eighth mantras ç
wherein the preta (the spirit) of the dead person is advised to travel ç
by the `ancient path' and meet Yama as also Varu<207>a.
@SPACE1 = 
The ninth mantra commands the evil spirits in the cremation ground ç
to depart immediately since Yama has allotted this place to the dead ç
person.
The tenth mantra exhorts the spirit of the dead person to travel safely, ç
avoiding the two fierce dogs of Yama (S<193>rameyas).
At the same time, prayer is offered to Yama, in the eleventh mantra, ç
to see that his dogs protect this spirit.
The twelfth mantra describes how the two dogs of Yama move about in ç
this world, among persons who are about to die, to take them to Yama.
In the thirteenth mantra, there is anappeal or a direction to the ç
<216>tviks (concerned priests) to press the soma juice to be offered ç
to Yama.
In the fourteenth, the <216>tviks are requested to offer the oblation ç
of ghee to Yama so that he can grant a long life.
In the next, the fifteenth, mantra there is, once more, an appeal ç
to the <216>tviks to give sweet oblations of puro<195><193>·a to Yama. ç
Then obeisance is offered to the ancient <216><218>is.
The  last  mantra,  the  sixteenth, describes Yama as taking part ç
in three kinds of sacrifice†Jyoti<199>, Gau<199> and °yu<199> †and ç
also occupying six regions of creation to witness the doings of all ç
living beings. Some of these mantras are used in aparakarmas or the ç
rites performed after the death of a person.
@NT = Yamun<193>
@N1 = (`that which rests [in the Ga<209>g<193> river after merging]')
Yamun<193> (also spelt as Jamun<193> or Jumn<193>) is one of the most ç
sacred rivers of India, next only to Ga<209>g<193>. It has been mentioned ç
even in the <184>gveda along with Ga<209>g<193> (vide 10.75.5). ç
The king Sud<193>sa, with the help of the T<216>tsus, conquered the ç
ten kings on the bank of the river Yamun<193> (ibid 7.18.19). Kings ç
Bharata, Ambar<200><218>a and <185>antanu had performed several sacrifices ç
on its banks. The greatsage Agastya had performed severe austerities ç
on its bank.
@SPACE1 = 
In the epics and the pur<193><207>as it has been described as closely ç
connected with the boyhood days of Lord K<216><218><207>a, like the ç
R<193>sal<200>l<193> (See <MS>R°SAL®L°.<D>). When Vasudeva (K<216><218><207>a's  father)  carried  baby  K<216><218><207>a, ç
Yamun<193> is said to have split into two giving way, to facilitate ç
his going.
The river takes its birth in Yamunotr<200> in the Kalinda mountain, ç
a part of the Him<193>layan range (Hence it got the name K<193>lind<200>.). ç
After coursing through 1376 kilometres (854 miles) it joins the Ga<209>g<193>and ç
the invisible Sarasvat<200> at the Trive<207><200>-sa<209>gam of Pray<193>ga ç
(the modern Allahabad).
The M<193>ghamel<193> bathing festival that is held here every year ç
as also the Kumbhamel<193> held once in 12 years (during January-February), ç
attracts millions of devotees.
The river has several other names such as S<220>ryatanay<193> and ç
<185>amanasvas<193>.
The quantity of water and the flow of the river are more or less constant ç
through out the year. Several tributaries, melting of Him<193>layan ç
icebergs in summer and greater in-flow during the rainy season seem ç
to be the reason behind it.
Since the river often breaks into smaller streams which join it later, ç
several small islands are formed in it.
Delhi, the old part of the capital city, is situated on its banks. ç
V<216>nd<193>ban and Mathur<193>, the famous places of pilgrimage ç
†because of their association with K<216><218><207>a†are also on its ç
banks. R<193>j<193>pur, the birthplace of Tulas<200>d<193>s (<MS>A.<|>D.<D> ç
1532-1623) is also situated on its bank.
Waters of Yamun<193> appear rather black or dark in colour because ç
<185>iva, overcome by the intense sorrow over the loss of his wife ç
Sat<200>, is said to have jumped into this river once!
Yamun<193> is also the goddess or the presiding deity of the river. ç
She was the daughter of S<220>rya (the Sun-god) and Sa<221>j<210><193>dev<200>. ç
Yama, the god of death was her twin-brother. She is said to have invited ç
her brother Yama to her house on the K<193>rttika-·ukla-dvit<200>y<193> ç
day (during the D<200>p<193>val<200> festival, usually in November) ç
and  honoured  him  with  dinner  and presents. This day is known ç
as Yama-dvit<200>y<193> or Bhr<193>t<216>dvit<200>y<193>. On this ç
day sisters invite their brothers for sumptuous meals and exchange ç
presents. (Hence a bath in the Yamun<193> river on this day is considered ç
extremely auspicious.)
Iconographic works describe her as black in colour, standing upon ç
a black tortoise (k<216><218><207>akacchapa) and wearing a garland ç
of blue lotuses. She has two arms, the hands showing the varada and ç
the abhaya mudr<193>s (gestures of boon-giving and protection). Her ç
sculptured images are seen in the Udayagiri caves near Bhuvane·var ç
in Orissa as also the museum at Patna in Bihar.
Like Ga<209>g<193>, Yamun<193> also has been praised profusely as ç
Mother in the devotional songs composed by saints.
See also <MS>GA<177>G°<D>.
@NT = Y<193>mun<193>c<193>rya
@N1 = (<MS>A.<|>D.<D> 918-1038)
The foundation of the Vi·i<218><219><193>dvaita Ved<193>nta philosophy, ç
of which R<193>m<193>nuj<193>-c<193>rya (<MS>A.<|>D.<D> 1017-1137) ç
was the chief exponent, was laid by a succession of ten <193>c<193>ryas ç
or teachers before him. Of them N<193>thamuni (<MS>A.<|>D.<D> 823-924) ç
and Y<193>muna or Y<193>mun<193>c<193>rya were the most prominent ç
ones.
Y<193>muna†also known as °<202>avand<193>r† was born in <MS>A.<|>D.<D> ç
918 as the son of ®·varamuni, the son of N<193>thamuni. V<200>ran<193>r<193>ya<207>apura ç
(in Tamil Nadu) was the place where he lived. At the tender age of ç
twelve he is said to have conquered (in disputation) a great scholar ç
Akki °<202>v<193>r. Consequently  the  Co<202>a  king,  being immensely ç
pleased with him, gave him half the kingdom. He lived as a king enjoying ç
all the good things of life. However, at the age of 80 he took Sa<221>ny<193>sa ç
and settled down at <185>r<200>ra<209>gam, the famous place of pilgrimage ç
with its temple of Ra<209>gan<193>tha.
He worked hard to make the temple of <185>r<200>ra<209>gam the central ç
place of <185>r<200>vai<218><207>avism. (See <MS>SR®VAI<186>ØAVISM.<D>)
Though he had a great desire to make R<193>m<193>nuja his disciple, ç
to succeed him to the pontifical seat he was occupying, he passed ç
away before he could do so.
He had 21 disciples of whom the following five were the chief ones: ç
Mah<193>p<220>r<207>a, <185>r<200>·ailap<220>r<207>a, Go<218><219>h<200>p<220>r<207>a, ç
M<193>l<193>dhara and Varara<209>gan<193>yaka.
He wrote six works: Stotraratna; Catu··lok<200>; °gamapr<193>m<193><207>ya; ç
Siddhitraya; G<200>t<193>rthasa<209>graha; Mah<193>puru<218>anir<207>aya.
The first is a beautiful hymn on N<193>r<193>ya<207>a. The second ç
praises the role of his spouse Lak<218>m<200> in granting liberation ç
to the j<200>vas (the individual souls). In the third he proves that ç
the P<193><210>car<193>tra °gamas are as authoritative as the Vedas.
@SPACE1 = 
The Siddhitraya is his chief work on the philosophy of Vi·i<218><219>h<193>dvaita, ç
wherein he has tried to prove that Brahman and j<200>va are separate ç
entities, the relation between them being one of ·e<218>a (part) and ç
·e<218>in (whole).
In the G<200>t<193>rthasa<209>graha he has shown that it is N<193>r<193>ya<207>a-Parabrahma ç
that is attained through the three disciplines of karma (action), ç
j<210><193>na (knowledge) and bhakti (devotion). It is bhakti that ç
is the chief means.
In the last work†the Mah<193>puru<218>a-nir<207>aya†he has tried to ç
establish that the God described in the Upani<218>ads and the pur<193><207>as ç
is N<193>r<193>ya<207>a.
@NT = yantra
@N1 = (`that which holds and protects')
In Hindu ritualistic practices, yantras have an important place.
Originally, the word yantra meant a machine or a contrivance. But ç
in the t<193>ntrik literature it assumed an entirely different connotation. ç
It stood for a mystical diagram that would help the s<193>dhaka or ç
spiritual aspirant to control (yam = to control) his six passions ç
and thus protect him (tra = to protect).
A yantra is a geometrical diagram engraved on a plate of gold, silver ç
or copper. It may be drawn on a bh<220>rja leaf (a kind of birch) ç
also. It represents a deity. Different deities of the Hindu pantheon ç
have different yantras.
A yantra has to be consecrated first†this is called sa<221>sk<193>ra†with ç
appropriate rites. It can then be used in worship. During the worship ç
the yantra can be used along with the image of the deity or a kala·a ç
(sacred water-pot) into which the deity has been invoked.
In t<193>ntrik rites, the yantra was used for <218>a<219>karmas or ç
six kinds of results viz.,va·<200>kara<207>a (controlling a person), ç
stambhana (making one immobile), vidve<218>a<207>a (hating), ucc<193><219>ana ç
(expelling), m<193>ra<207>a (killing) and ·<193>ntikapau<218><219>ika ç
(for peace and nourishment).
A yantra drawn on bits of paper or bh<220>rja leaves or even thin ç
copper plates, and enclosed in metallic amulets, may be worn on the ç
arm or round the neck for specific purposes. They are then called ç
dh<193>ra<207>ayantras. However one should be careful to see that ç
they are not polluted by coming into contact with the earth or any ç
defiling object like a dead body. They will then lose their power.
The following table gives a brief account of the yantras of some deities ç
and their effects:
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(1.1250,.1942,E1), ç
ABOVE(.0417), BELOW(.0320), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
of Ga<207>apati, †, for conferring wealth and prosperity.
of Bhadrak<193>l<200>, †, for conferring know-ledge,, strength,<|>health.
of Sudar·ana, †, for relieving sickness and driving away evil spirits.
of <185>arabha, †, for curing epilepsy.
of Subrahma<207>ya, †, for expelling evil <R>ç
spirits.
of Hanum<193>n, †, for attaining strength,, safety in travel.
of C<193>mu<207><195><193>, †, to cause the death of enemies.
@Z_TBL_END = 
As regards the retention of the power induced in a yantra, the following ç
chart gives an idea:
@Z_TBL_BEG = COLUMNS(4), DIMENSION(IN), COLWIDTHS(.3333,1.3758,.1667,E1), ç
ABOVE(.0833), BELOW(.0555), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TL, TABLE TEXT, TL
, Yantra inscribed on, , Duration
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE TEXT
, gold plate, , whole life
, silver plate, , twenty years
, bh<220>rja leaves, , twelve years
, copper plate, , six years
@Z_TBL_END = 
See also <MS>TANTRAS<D>.
@NT = Y<193>ska
See <MS>NIRUKTA<D>.
@NT = Ya·od<193>
Ya·od<193> was the queen of Nanda, the chief of the cowherds of Gokula. ç
When she gave birth to a girl, the child was exchanged with K<216><218><207>a, ç
the eighth son of Devak<200>. Consequently K<216><218><207>a spent ç
his childhood and early boyhood days at Nanda's house thereby giving ç
Ya·od<193> the chance of his company and of enjoying his childish ç
pranks.
See <MS>NANDA<D>.
@NT = yati
It is one of the terms used to indicate a sa<221>ny<193>sin. (See ç
<MS>SA<189>NY°SA<D>.)
In prosody it indicates a break in the line, in any metre, to facilitate ç
easy pronunciation.
@NT = Yatidharmasa<209>graha
Though the sm<216>tis and the dharma-·<193>stra, as also the pur<193><207>as, ç
deal with theduties and responsibilities of persons belonging to ç
the four var<207>as (castes) and <193>·ramas (stages of life), there ç
are only a few works that deal exclusively with Yatidharma  or  sa<221>ny<193>sa.  The ç
 Yati- dharmasa<209>graha†also known by two more names, the Yatidharmaprak<193>·a ç
and the Yatidharmasamuccaya†of Vi·ve·vara-sarasvat<200> is perhaps ç
the best among such treatises. He was a disciple of Sarvaj<210>a-vi·ve·a ç
and lived earlier than <MS>A.<|>D.<D> 1600. Nothing more is known about ç
him.
Though the work is in prose, it has profusely quoted from the Upani<218>ads, ç
the pur<193><207>as and the sm<216>tis. Some of them are: B<216>had<193>ra<207>yaka ç
Upani<218>ad; J<193>b<193>la Upani<218>ad; Ka<219>ha Upani<218>ad; ç
Mu<207><195>aka Upani<218>ad; Bhagavadg<200>t<193>; Vi<218><207>upur<193><207>a; ç
Skandapur<193><207>a; Sm<216>tis of Atri, B<216>haspati, Dak<218>a, ç
Devala, Gobhila, Manu, Par<193>·ara, Y<193>j<210>avalkya and Yama.
@SPACE1 = 
The number of topics dealt with exceeds 90.
The more important ones from among them are as follows: when to take ç
sa<221>ny<193>sa; ·r<193>ddhas to be performed; certain rites to be ç
performed by the <193>hit<193>gni (one who is keeping the Vedic fires) ç
and others who have not; repetition of the prai<218>a mantra three ç
times, this being central to the whole process of taking sa<221>ny<193>sa; ç
accepting the external insignia of sa<221>ny<193>sa like doraka (girdle), ç
kaup<200>na (loin-cloth), wearing-cloth, kantha (quilt of rags) and ç
da<207><195>a (staff); approaching a competent guru (preceptor) to ç
acquire <193>tmaj<210><193>na (knowledge of the Self); receiving the ç
mah<193>v<193>kya (great Vedic sentence like tat tvam asi); the ç
few things of necessity that a yati or a sa<221>ny<193>sin can keep ç
for the maintenance of the body; code of conduct; service to the guru; ç
japa or repetition of pra<207>ava (O<221>) and Rudra (a Vedic passage); ç
up<193>san<193> (meditation) on the °tman/Brahman; a sa<221>ny<193>sin ç
has no karma (rituals) to perform; rules about ablutions, bath and ç
other daily activities; on bhik<218><193>cary<193> or begging; how ç
to observe the vows of c<193>turm<193>sya (ritual staying in a place ç
during the rainy season); method of  honouring  guest-sa<221>ny<193>sins,  the ç
processes called parya<209>kavidhi and yoga-pa<219><219>a; things ç
forbidden for a sa<221>ny<193>sin; pr<193>ya·cittas or expiations ç
for transgressions; m<193>dhukar<200>bhik<218><193> (collecting alms, ç
even as a bee collects honey, from not more than seven houses); sa<221>ny<193>sa ç
purifies him and his family; characteristics of a j<200>vanmukta, ç
the liberated soul.
@NT = Yatindramatad<200>pik<193>
This is the only standard and popular prakara<207>agrantha†elementary ç
textbook† of Vi·i<218><219><193>dvaita philosophy.
<185>r<200>niv<193>sad<193>sa, the author of this treatise, might ç
have lived in the 15th or the 16th century. He was the son of Govind<193>c<193>rya ç
and a disciple of Mah<193>c<193>rya. Being a staunch devotee of Lord ç
Ve<209>ka<219>e·a,  he  lived  in  Tirupati  (in Chittoor district ç
of Andhra Pradesh). Apart from this treatise, he is said to have written ç
a gloss on the <185>rutaprak<193>·ik<193> which itself is a commentary ç
by Sudar·anas<220>ri (<MS>A.<|>D.<D> 1200-1275) on the <185>r<200>bh<193><218>ya ç
of R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137).
He states that he consulted more than 20 standard books on this subject ç
and has tried to present their summary in an elementary form in this ç
work of his.
This work has one modern commentary called Prak<193>·a by V<193>sudeva·<193>stri ç
Abhya<209>kar.
The Yat<200>ndramatad<200>pik<193> is written in elegant prose and ç
has ten avat<193>ras or chapters.
The first chapter enumerates the different pad<193>rthas or categories, ç
first as pram<193><207>as (valid sources of knowledge) and prameyas ç
(objects known through them). It then gives their subdivisions. The ç
theory of satkhy<193>ti (`what is real alone is apprehended') is established ç
by rejecting other theories like akhy<193>ti and anirvacan<200>ya-khy<193>ti ç
(See <MS>KHY°TI<D> for details.). The concept of pratyak<218>a (direct ç
perception) is explained in detail.
The second chapter deals with anum<193>na or inference extensively. ç
Five hetv<193>bh<193>sas or fallacies of reasoning are explained. ç
Upamiti (analogy) and arth<193>patti (implication) are shown to be ç
included in anum<193>na itself.
The subject of the third chapter is ·abda pram<193><207>a or verbal ç
testimony. Apart from establishing that the Vedas are eternal and ç
have no human author, an attempt is made to prove that all words convey  the  sense  of  N<193>r<193>ya<207>a,  the ç
Supreme Lord.
The fourth chapter is the longest of all. Prak<216>ti or nature is ç
the main subject matter. The categories of the Ny<193>ya school of ç
philosophy are refuted and of the S<193><209>khya school accepted.
The fifth chapter is concerned with k<193>la or time. It is eternal ç
and all-pervasive. Other aspects of time described are the four yugas, ç
measurement of Brahm<193>'s time and life, the periods of Manus and ç
Indras as also the refutation of other views regarding time.
The next chapter, the sixth, enumerates the eternal, transcendental ç
attributes of pure sattva (called ·uddhasattva) which belongs both ç
to ®·vara and j<200>va. It is of ·uddhasattva that the bodies of ®·vara, ç
of the muktas or liberated souls and of the world known as Vaiku<207><219>ha ç
are made. At the end there is a nice description of Vaiku<207><219>ha.
@SPACE1 = 
The  seventh  chapter  deals  with dharmabh<220>taj<210><193>na or ç
attributive consciousness. It is always eternal and and all-pervasive ç
in respect of ®·vara and the nityas (eternal souls never in bondage). ç
With regard to the bound souls it is contracted or obscured. If and ç
when they attain liberation, it expands to infinity. Apart from describing ç
the three yogas of karma (action), j<210><193>na and bhakti (devotion), ç
the doctrines of bhakti and prapatti (self-surrender) are elaborated.
The subject of the eighth chapter is j<200>vas or individual souls. ç
Common characteristics of the j<200>va and ®·vara like self- consciousness ç
are described first. The true nature of the j<200>va is then elaborated. ç
There are infinite numbers of j<200>vas. They are unborn and eternal. ç
They are monadic in size with consciousness as the essential nature. ç
Different kinds of j<200>vas including the liberated ones and their ç
characteristics are described. Views of other schools like that of ç
the C<193>rv<193>kas and Buddhism about the j<200>va are refuted.
The next chapter†the ninth†is concerned with ®·vara or God. He is ç
described as the up<193>d<193>nak<193>ra<207>a (material cause), nimittak<193>ra<207>a   (efficient   cause)   and ç
sahak<193>rik<193>ra<207>a (co-operant cause) of the universe. The ç
theory of m<193>y<193> of the advaitins is refuted. Fivefold aspects ç
of ®·vara†para, vy<220>ha, vibhava, arc<193> and antary<193>min†are ç
elaborated.
(See <MS>ANTARY°MIN.<D>)
The tenth and the last chapter explains the adravyas (non-substance) ç
which are ten.
The work concludes by giving a long list of treatises†31 in number†dealing ç
with the Vi·i<218><219><193>dvaita philosophy from which the essence ç
of this work has been prepared.
@NT = y<193>tudh<193>na
@N1 = (`one who nourishes the<R>ç
demons')
This word has been used in the <184>gveda several times (vide ç
10.87). It hasbeen employed in the sense of an evilspirit that tries ç
to harm human beings.
Y<193>tudh<193>nas are fond of eating the flesh and drinking the blood ç
of human beings and domestic animals like horses. They can cause serious ç
diseases and evenlunacy. They are very active during evenings and ç
nights. They are specially fond of spoiling Vedic sacrifices.
However, the deity Agni is powerful enough to destroy them. Hence ç
prayers are specially offered to him (ibid. 10.87.3, 4, 5, 7).
@NT = yavamadhya
@N1 = (`the middle of a wheat grain')
@SPACE1 = 
See <MS>C°NDR°YAØA<D>.
@NT = yavanas
@SPACE1 = 
The word yavana or yona in the epics and the pur<193><207>as generally ç
stands for foreigners, especially the Greeks and the Muslims. They ç
are described as barbarous people (vide Mah<193>bh<193>rata, Vanaparva, ç
Ch. 188) who will rule in Kaliyuga.
Originally, perhaps, the word might have indicated the Ionians or ç
ancient Greeks.
According to the R<193>m<193>ya<207>a (B<193>la-k<193><207><195>a ç
55) the yavanas were produced from the hind part of the celestial ç
cow Nandin<200> to fight against the army of Vi·v<193>mitra.
The Mah<193>bh<193>rata in another place (°diparva 85.34) states ç
that the yavanas sprang from Turvasu, one of the sons of the king ç
Yay<193>ti.
The Matsyapur<193><207>a (114.11) considers the country of the yavanas ç
as a part of Bh<193>ratavar<218>a.
@NT = Yay<193>ti
@SPACE = 
Yay<193>ti has become famous in Ved<193>ntic literature for his statement ç
thatdesires can never be quenched by trying to satisfy them (vide ç
Mah<193>bh<193>rata, °diparva, 85.12).
He was a king of the Candrava<221>·a (lunar race), the son of another ç
celebrated king Nahu<218>a, and queen Viraj<193>. He had two wives, ç
Devay<193>n<200> and <185>armi<218><219>h<193>. Anu, Yadu, Turvasu, ç
Druhyu and P<220>ru were his five sons.
Once, due to the curse of the sage <185>ukr<193>c<193>rya, Yay<193>ti ç
lost his youth and became old. However the sage had also given him ç
the boon that he could exchange his old-age with the youth of a young ç
man. When Yay<193>ti requested his sons to exchange their youth, all ç
refused except P<220>ru. After enjoying all the pleasures of life ç
for many years Yay<193>ti found out the truth that lust could never ç
be satiated by enjoyment. He then gave back the youth to prince P<220>ru, ç
crowned him as the king and left for tapas.
@SPACE = 
@NT = Yoga
@SPACE = 
This word is used in several senses. When derived from the root `yuj ç
sam<193>dhau' it means perfect concentration of mind. If derived from ç
another root, `yujir yoge', it means `to unite'. Combining these twosenses ç
one can say that it stands for that art and science of concentration ç
of mind which helps the spiritual aspirant to ultimately unite his ç
individual soul (j<200>v<193>tman) with the Supreme Soul (Param<193>tman).
The Yogadar·ana of Pata<210>jali (200<MS>B.C.<D>) fits in with this ç
description. See <MS>YOGADAR<185>ANA<D> for details.
However, in general, this word isoften loosely used for any spiritual ç
discipline. A few of them are listed below, arranged in the alphabetical ç
order:
@SB8.5 = Abh<193>vayoga
The   Taittir<200>ya   Upani<218>ad   (2.1) describes the evolution ç
of the world from the °tman (same as Brahman), through the five elements ç
like the <193>k<193>·a (space, ether) right up to puru<218>a (human ç
being). In Abh<193>vayoga, the aspirant has to meditate on the reverse ç
process, merging each succeeding product in the preceding one, finally ç
arriving at the °tman-principle which is nirgu<207>a (without attributes) ç
and nir<193>k<193>ra (without forms) and is pure consciousness. In ç
this state of yoga, the whole world appearance has disappeared (abh<193>va ç
= nothingness) and only the °tman is experienced.
@SB8.5 = Amanaskayoga
This is the yoga in which the mind is prevented from rising in the ç
form of v<216>ttis (waves) and made absolutely still, whereby the ç
°tman is experienced. Certain disciplines  of  Ha<219>hayoga  like  the ç
khecar<200>mudr<193> (See <MS>KHECAR®MUDR°<D>.) have to be practised ç
first.
@SB8.5 = A<218><219><193><209>gayoga
The Yogadar·ana of Pata<210>jali (200<MS>B.C.<D>) is named A<218><219><193><209>gayoga ç
since it consists of eight limbs (a<218><219>a = eight; a<209>ga=limb ç
or steps). See <MS>YOGADAR<185>ANA<D> for details.
@SB8.5 = Bhaktiyoga
See <MS>BHAKTI<D> and <MS>BHAKTIYOGA<D>.
@SB8.5 = Bh<193>vayoga
After practising mantrajapa (repetition of the divine name) coupled ç
with pr<193><207><193>y<193>ma (control of breath) for quite some ç
time, if the japa is given up, leading to the direct experience of ç
the divine presence, it is Bh<193>vayoga.
@SB8.5 = Buddhiyoga
See <MS>BUDDHIYOGA<D>.
@SB8.5 = Dhy<193>nayoga
See <MS>DHY°NAYOGA<D>.
@SB8.5 = Ha<219>hayoga
See <MS>HA<187>HAYOGA<D>.
@SB8.5 = J<210><193>nayoga
See <MS>J<178>°NAYOGA<D>.
@SB8.5 = Karmayoga
See <MS>KARMAYOGA<D>.
@SB8.5 = Kriy<193>yoga
See <MS>KRIY°YOGA<D>.
@SB8.5 = Ku<207><195>alin<200>yoga
The yoga by which the ku<207><195>alin<200> power is taken up through ç
the six cakras right up to the seventh, is called Ku<207><195>alin<200>yoga.
See <MS>CAKRAS<D> and <MS>KUØ£ALIN®<D>.
@SB8.5 = Layayoga
This is another name for Ku<207><195>alin<200>-yoga.
@SB8.5 = Mah<193>yoga
This is the stage next to Abh<193>vayoga wherein the aspirant will ç
experience his oneness with <185>iva or God.
@SB8.5 = Mantrayoga
See <MS>MANTRAYOGA<D>.
@SB8.5 = N<193>dayoga
Brahman  is  all-pervading  pure consciousness. When he wills to create ç
the world (vide Ch<193>ndogya Upani<218>ad 6.2.1 and 3; Taittir<200>ya ç
Upani<218>ad 2.6; Aitareya Upani<218>ad 1.1) a spanda or n<193>da ç
(vibration or sound) appears in him. This will gradually evolve into ç
this multiplicity of the universe. That n<193>da is represented by ç
Pra<207>ava or O<221>. Meditation on this n<193>da ultimately leading ç
to the dissolution of the mind and arising of supreme know-ledge is ç
called N<193>dayoga.
@SB8.5 = R<193>jayoga
This is the same as the yoga taught by Pata<210>jali (200 <MS>B.<|>C.<D>). ç
See <MS>YOGADAR<185>ANA<D> for details.
@SB8.5 = <185>ivayoga
Achieving the unity of the j<200>v<193>tman (the individual soul) ç
with Param<193>tman is <185>ivayoga according to the scriptures of ç
<185>aivism. It has five steps: arcana (worship of the chosen deity); ç
anusandh<193>na (meditating on the form of the deity); bhakti (cultivation ç
of devotion); vidy<193> (receiving the mantra); vrata (strictly following ç
the disciplines imposed by the guru and the scriptures).
@SB8.5 = Spar·ayoga
When Mantrayoga is practised along with pr<193><207><193>y<193>ma, ç
it is called Spar·ayoga.
@SB8.5 = Tantrayoga
The  path  of  spiritual  discipline described in the works on tantras ç
consisting of <218>a<219>cakrabheda (piercing the six cakras) is called ç
Tantrayoga.
(See <MS>CAKRAS<D> for details.)
