@NT = yog<193>sanas
@N1 = (`postures [recommended by the science of] Yoga')
@SPACE = 
@SPACE1 = 
Yog<193>sanas are now extremely popular all over the world, mostly ç
as physical exercises. However they are much more than that. Coupled ç
with pr<193><207><193>y<193>ma (yogic technique of controlling the ç
pr<193><207>a or the basic life-force, through special breathing exercises) ç
they act at three levels: the physical body, the vital body and the ç
mind. When perfected they help the physical body  to  have  strength  and  stamina, ç
regulate the internal body-chemistry and assist in gaining control ç
over the mind.
@SPACE1 = 
°sana means a posture (of sitting or standing). According to one view, ç
by imitating the posture of an animal, one can get that animal's agility ç
or any other special capacity. That is why quite a few yog<193>sanas ç
are named after some animal or the other (as in Kukku<219><193>sana ç
or May<220>r<193>sana; kukku<219>a = cock; may<220>ra = peacock).
@SPACE1 = 
Though such yog<193>sanas can be innumerable, thirty-two have been ç
mentioned as more important by the Ghera<207><195>a Sa<221>hit<193> ç
(Chapter 2), a standard work of Ha<219>hayoga, more directly concerned ç
with the yog<193>sanas and pr<193><207><193>y<193>ma.
@SPACE1 = 
Yog<193>sanas have certain advantages over the gymnastic exercises. ç
They can be practised by all, irrespective of age or sex or health ç
conditions if specific instructions are followed. No external appliance ç
like dumb-bells or barbells or any other device is needed. The yogic ç
exercises reduce the toxins in the body instead of increasing them ç
as done by the other system.
@SPACE1 = 
Those who wish to practise yog<193>sanas are required to observe some ç
general rules. They are:
@NID = 1.
@NK-1 = Organs of evacuation should be empty before practising the ç
yog<193>sanas.
@NID = 2.
@NK-1 = It is better to do the yog<193>sanas after bath. Otherwise, ç
there must be a gap of at least 30 minutes for bath after doing them.
@NID = 3.
@NK-1 = Early morning is the best time for doing the yog<193>sanas.
@NID = 4.
@NK-1 = Drinking a glass of warm water before beginning will help.
@NID = 5.
@NK-1 = The place must be clean and airy. Ablanket should be spread ç
and the yog<193>sanas practised on it.
@NID = 6.
@NK-1 = Breathing must be done through the nostrils only.
@NID = 7.
@NK-1 = At the end, sweat should be dried by spreading it with the ç
bare hands and not with a cloth.
Those suffering from some diseases like hypertension should not practise ç
topsy-turvy postures.
Women are advised to avoid some yog<193>sanas  during  certain  periods  or ç
conditions.
Before beginning the regular practice of the yog<193>sanas, a few ç
preparatory exercises have to be done to loosen the joints and attain ç
flexibility. These include bending, rotating the arms, clenching the ç
hands and movements of the neck. Some exercises for the eyes also ç
are prescribed.
According to the Yogas<220>tras of Pata<210>jali (200 <MS>B.<|>C.<D>) ç
<193>sana is the third of the eight steps of yoga. He defines it as ç
that posture in which one can sit comfortably and steadily for a long ç
time, for meditation (vide 2.29, 46, 48). The works on Ha<219>hayoga ç
recommend the following <193>sanas for meditation: Bhadr<193>sana, ç
Padm<193>sana, Siddh<193>sana, Svastik<193>sana, Vajr<193>sana and ç
V<200>r<193>sana.
Out  of  the  several  yog<193>sanas currently in use, the following ç
sixteen are very common:
<+>1.<+>Ardhamatsyendr<193>sana
<+>2.<+>Baddhapadm<193>sana
<+>3.<+>Bhuja<209>g<193>sana
<+>4.<+>Dhanur<193>sana
<+>5.<+>Hal<193>sana
<+>6.<+>Matsy<193>sana
<+>7.<+>May<220>r<193>sana
<+>8.<+>Meruda<207><195><193>sana
<+>9.<+>Pa·cimott<193>n<193>sana
10.<+><185>alabh<193>sana
11.<+>Sarv<193><209>g<193>sana
12.<+><185>av<193>sana
13.<+>Si<221>h<193>sana
14.<+><185><200>r<218><193>sana
15.<+>Utthitadvip<193>d<193>sana
16.<+>Utthitatriko<207><193>sana
It is best to learn these yog<193>sanas directly from a competent ç
teacher. Though pictures and descriptions of them are often given ç
in standard works, there is always a chance of going wrong or even ç
getting into trouble.
When practised properly these yog<193>sanas have either cured or decreased ç
the effects of many ailments. In fact, quite a few have been designed ç
as cures for specific diseases.
@NT = Yogas<193>rasa<209>graha
@N1 = (`abridged edition of the essence of yogadar·ana')
The basic text of the Yogadar·ana or the Philosophy of Yoga is the ç
Yogas<220>tras of Pata<210>jali (200 <MS>B.<|>C.<D>). This work has ç
several commentaries, of which the Vy<193>sabh<193><218>ya is considered ç
the primary authority. Vij<210><193>nabhik<218>u (16th century <MS>A.D.<D>) ç
who has written a scholarly gloss on it, called the Yogav<193>rttika, ç
has beautifully summarised the entire work in this treatise, the Yogas<193>rasa<209>graha. ç
It is in simple prose, often interspersed with plenty of relevant ç
quotations culled from various authoritative texts.
There are four chapters called a<221>·as.
A brief synopsis of the contents may now be attempted.
@S10N = First Chapter (Yogasvar<220>pa or Nature of Yoga and its ç
Utility)
Five functions of the citta or the mind; nirodha defined as withdrawal ç
of the function of the mind; results of two kinds of sam<193>dhis ç
(perfect meditation), viz., cessation of pain and attainment of mok<218>a ç
or liberation; four kinds of sam<193>dhi, which are part of sampraj<210><193>tasam<193>dhi ç
(conscious  or  concrete  sam<193>dhi);  two kinds of asampraj<210><193>tasam<193>dhi ç
(abstract sam<193>dhi).
@S10N = Second Chapter<R>ç
(Yogas<193>dhana or Yogic Practices)
Abhy<193>sa (repeated efforts) and vair<193>gya (detachment) as primary ç
means to yoga; parikarmas or special practices that help in controlling ç
the mind; on kriy<193>yoga comprising tapas (austerity), sv<193>dhy<193>ya ç
(study of the scriptures) and <200>·varapra<207>idh<193>na (devotion ç
to God); five kle·as or troubles of the mind and their elimination; ç
the eight steps of meditation like yama, niyama and so on; importance ç
of the last three steps.
@S10N = Third Chapter (Yogasiddhis or Powers)
Dh<193>ra<207><193> (fixing the mind on the object of concentration), ç
dhy<193>na (continuous concentration) and sam<193>dhi (perfect meditation) ç
defined as sa<221>yama; various kinds of siddhis or powers arising ç
out of sa<221>yama on various objects.
@S10N = Fourth Chapter (Kaivalya or Liberation)
Kaivalya  (isolation  or  liberation) defined; reconciling the view ç
of Yoga system on liberation with the views of other schools; kaivalya ç
is cessation of all du<199>kha or sorrow; points of difference between ç
Yoga and S<193><209>khya philosophies; two new points†the Spho<219>a ç
and Manovaibhava (powers of the anta<199>kara<207>a or the internal ç
organ). (See <MS>SPHO<187>AV°DA<D>.)
This treatise has been considered one of the best books on the Yoga ç
philosophy of Pata<210>jali because of its clarity as also comprehensive ç
nature.
See also <MS>VIJ<178>°NABHIK<186>U<D>.
@NT = Yoga·ayanam<220>rti
This is one of the aspects of Vi<218><207>u shown as recumbent on ç
<185>e<218>a or °di·e<218>a as the couch. He is pale blue or blue ç
with an yellowish tinge. He has two arms. He is blissfully absorbed ç
in yoganidr<193> or yogic slumber.
@SPACE = 
@SPACE = 
He may be shown as surrounded by the sages Bh<216>gu and M<193>rka<207><195>eya ç
as also the <193>yudhas or weapons like ·a<209>kha (conch), cakra ç
(discus), gad<193> (mace) as personified deities. The two demons, ç
Madhu and Kai<219>abha, too are present.
@NT = Yoga·ikhopani<218>ad
@EMERGENCY = Though classed among the minor Upani<218>ads of the Yoga ç
group, this is a fairly long and exhaustive Upani<218>ad. It belongs ç
to the K<216><218><207>a Yajurveda. It is in the form of a dialogue ç
between Hira<207>yagarbha (the disciple) and <185>iva (the teacher).
@EMERGENCY = There are 390 verses in all, in the anu<218><219>ubh ç
metre spread over six adhy<193>yas or chapters.
The first adhy<193>ya (178 verses) deals with a large number of topics. ç
After describing some preliminaries common to Ved<193>ntic scriptures, ç
it deals exhaustively with quite a few topics of Ha<219>hayoga. The ç
following is a brief list of such topics: purification and refinement ç
of the mind through yoga; necessity of approaching a guru or spiritual ç
teacher who is an adept in pr<193><207><193>y<193>ma; arousing the ç
Ku<207><195>alin<200> power (See <MS>CAKRAS<D> and <MS>TANTRAS<D>.); ç
various kinds of pr<193><207><193>y<193>mas and bandhas (See <MS>MUDR°S<D> ç
and <MS>PR°Ø°Y°MAS<D>.); some yogas like Mantrayoga and Layayoga; ç
importance of abhy<193>sa or continuous practice; j<200>vanmukti or ç
liberation even while living.
@EMERGENCY = The second adhy<193>ya (22 verses) dealsmainly with ç
Pra<207>ava (O<209>k<193>ra) as the m<220>lamantra (fundamental esoteric ç
formula). It is interesting to note that devotion to the guru and ç
God are stressed as all-important in attaining the know-ledge of the ç
Supreme.
@EMERGENCY = The  third  adhy<193>ya  (25  verses) describes N<193>dabrahman ç
or Brahman as sound and its four forms viz., par<193>, pa·yanti, madhyam<193> ç
and vaikhar<200> (See <MS>PAR°<D> for details.).
The fourth adhy<193>ya (24 verses) puts forward the usual theories ç
of Advaita Ved<193>nta such as the non-existence of the j<200>va (individual ç
soul) as an independent reality, the world as unreal as the objects ç
seen in a dream and the body as a superimposition on the soul due ç
to aj<210><193>na or nescience.
The  fifth  adhy<193>ya  (62  verses) describes the body as the residence ç
of Vi<218><207>u, the all-pervading Supreme Lord. Then follows an ç
account of the six cakras like m<220>l<193>dh<193>ra. Other topics ç
portrayed are: rousing of the Ku<207><195>alin<200> power, khecar<200>mudr<193> ç
(See <MS>KHECAR®MUDR°<D>.), meditation on N<193>r<193>ya<207>a in ç
the sahasr<193>racakra, method of worshipping one's guru and indifference  towards  siddhis  or  yogic ç
powers.
The sixth, the last, adhy<193>ya (79 verses) deals with a few more ç
topics of Ha<219>hayoga and J<210><193>nayoga. They are: method of ç
meditation on the Ku<207><195>alin<200> power; description of the ç
su<218>umn<193>n<193><195><200>; meditations on the forms of Brahm<193> ç
in the six cakras; bondage and liberation depending on the mind being ç
active or still.
The Upani<218>ad ends with the warning that j<210><193>na (spiritual ç
wisdom as direct experience) can arise only by practice done according ç
to the instructions of a qualified guru.
@SPACE = 
@NT = Yogas<220>tras
@SPACE1 = 
See <MS>YOGADAR<185>ANA<D>.
@SPACE = 
@NT = Yogatattvopani<218>ad
@SPACE1 = 
The Upani<218>ads are normally divided into two groups: the major ç
and the minor. Out of the 120 or 125 Upani<218>ads available in print, ç
the well-known ten Upani<218>ads (from the ®·<193>vasyopani<218>ad ç
up to the B<216>had<193>ra<207>yakopani<218>ad) are considered the ç
major ones and the rest as minor. Among the latter, 20 Upani<218>ads ç
are classed as the Yoga Upani<218>ads since their subject matter is ç
mainly centred round yoga (R<193>jayoga and Ha<219>hayoga).
The Yogatattvopani<218>ad belongs to this group. It is assigned ç
to the K<216><218><207>a Yajurveda and has 142 verses without any ç
internal divisions as chapters.
The following is a brief synoptic summary of its contents:
Some general principles of Advaita Ved<193>nta; the four yogas viz., ç
R<193>jayoga, Mantrayoga, Ha<219>hayoga and Layayoga; the eight steps ç
of yoga; detailed treatment of pr<193><207><193>y<193>ma (See <MS>PR°Ø°Y°MA<D>.) ç
and a few bandhas (See <MS>MUDR°<D>.); meditation on Sagu<207>a and ç
Nirgu<207>a aspects of Brahman; some mudr<193>s like khecar<200>; ç
meditation on the Pra<207>ava in the lotus of the heart.
@SPACE = 
@NT = Yogav<193>rttika
@SPACE = 
On the Yogas<220>tras of Pata<210>jali (200 <MS>B.<|>C.<D>) there ç
is an ancient and original commentary known as the Vy<193>sabh<193><218>ya ç
by Vy<193>sa. On this, there are two well-known glosses: the Tattvavai·<193>rad<200> ç
of V<193>caspati Mi·ra (<MS>A.<|>D.<D> 850) and the Yoga-v<193>rttika ç
of Vij<210><193>nabhik<218>u (<MS>A.<|>D.<D> 1550).
The Yogav<193>rttika is a lucid explanation of the Vy<193>sabh<193><218>ya. ç
However it often differs from the views given in the Tattvavai·<193>rad<200>.
Vij<210><193>nabhik<218>u seems more inclined towards  bringing  the  S<193><209>khya-yoga ç
philosophy nearer to the traditional Ved<193>nta.
See also <MS>VIJ<178>°NABHIK<186>U<D>.
@NT = Yogav<193>si<218><219>ha
@SPACE = 
@SPACE = 
This is an extremely popular work, especially among the followers ç
of Advaita Ved<193>nta. It is an extensive philosophical poem spread ç
over six prakara<207>as or chapters containing nearly 32,000 verses, ç
(according to tradition) though the printed versions contain much ç
less (23,734 verses). It might have been composed during the 8th century ç
<MS>A.<|>D.<D> It is by an unknown author while tradition assigns it ç
to the sage V<193>lm<200>ki.
It is known by several other names such as Yogav<193>si<218><219>har<193>m<193>ya<207>a, ç
Mah<193>-r<193>m<193>ya<207>a and J<210><193>nav<193>si<218><219>ha ç
also.
It seems to have influenced several later works like Annap<220>r<207>a ç
Upani<218>ad, Mahopani<218>ad, the M<193>nasoll<193>sa of Sure·vara ç
(<MS>A.<|>D.<D> 800) on the Dak<218>i<207><193>m<220>rti-stotra of ç
<185>a<209>kara (<MS>A.<|>D.<D> 788-820) and the J<200>vanmuktiviveka  of  Vidy<193>ra<207>ya  (14th ç
century <MS>A.<|>D.<D>).
It has several commentaries. Some of them are: V<193>si<218><219>har<193>m<193>ya<207>acandrik<193> ç
by Advay<193>ra<207>ya; T<193>tparyaprak<193>·a of °nandabodhendrasarasvat<200>; ç
Padacandrik<193> by M<193>dhavasarasvat<200>.
A few summaries of the work are also available such as Laghuyogav<193>si<218><219>ha ç
of Gau<195>a Abhinanda (9th century <MS>A.<|>D.<D>) and  V<193>si<218><219>has<193>rag<220><195>h<193>rtha  by  R<193>m<193>- ç
nandat<200>rtha. These works again have their own commentaries written ç
by scholars.
The treatise begins in a dramatic manner containing stories within ç
stories, and ends with a long dialogue between the sage Vasi<218><219>ha ç
and R<193>ma, the son of king Da·aratha of Ayodhy<193>.
The first section called Vair<193>gya-prakara<207>a  describes  the  vair<193>gya  or ç
intense  dispassion  of  R<193>ma  due  to disillusionment with the ç
transitory nature of the world. At the request of the king Da·aratha, ç
the sage Vasi<218><219>ha tries to enlighten him. This is the setting ç
of the entire work.
Mumuk<218>uvyavah<193>raprakara<207>a, the second section, tells ç
R<193>ma that disillusionment  with  the  world,  because  it  is ç
evanescent, should lead to the dawn of wisdom. The conviction that ç
one is in bondage because one feels that the world is real and of ç
one's own ego as real should lead to the cultivation of the four qualities ç
of ·ama (tranquillity), vic<193>ra (rational investigation), santo<218>a ç
(contentment) and s<193>dhusa<209>gama (the company of the wise). ç
Here, the sage Vasi<218><219>ha stresses the importance of pauru<218>a ç
(self-effort) and that it can help overcome even the effect of past ç
karmas.
The next section called Utpatti-prakara<207>a deals with s<216><218><219>i ç
or creation. Vasi<218><219>ha  is  a  thoroughgoing  idealist. According ç
to him this world is a manifestation of the mind†the mind of Brahm<193> ç
(the creator) by his sa<209>kalpa or will. Even as the ocean alone ç
is real and not the waves, though they appear and disappear, it is ç
Brahman the ultimate Reality that is real and not the world.
An analysis of the three states of consciousness is resorted to, to ç
prove this point.
Since the world arises by the sa<209>kalpa (thought, desire) of Brahman, ç
itis experienced by all of us as the same,tinted, however, with ç
our own sa<209>kalpa.
@SPACE1 = 
The fourth section is called Sthiti-prakara<207>a. The world continues ç
to exist only so long as the sa<209>kalpa or desire is there. The ç
world-experience is maintained as long as the mind is active and outward-looking. ç
This is proved by taking the example of avasth<193>traya or the three ç
states of consciousness. It is v<193>san<193>s (inclinations and predispositions ç
of themind) that are responsible for the continuance of world-experience.
The fifth section is termed the Up<193>san<193>prakara<207>a, teaching ç
the art of calming the mind. This calming of the mind is similar to ç
the deep-sleep state. The techniques of destruction of the v<193>san<193>s ç
or v<193>san<193>k<218>aya are described here, leading to manon<193>·a†the ç
destruction of the tendencies in the mind to rise in the form of mental ç
waves. J<210><193>na orknowledge of the Self is the chief technique.
Nirv<193><207>aprakara<207>a is the last chapter. This is the longest ç
part and has two sections, the p<220>rv<193>rdha (earlier part) and ç
the uttar<193>rdha (later part). It has a number of stories and is ç
highly repetitious. Nirv<193><207>a or liberation is the realisation ç
of the identity of the Self with the Absolute or Brahman. Since bondage ç
arises by the false identification of the Self with the body, its ç
reversal through a critical inquiry leads to this liberation. Hence, ç
neither worship nor devotion to God will be of any use in this path!
@SPACE1 = 
Liberation is possible for everyone here and now. The liberated man, ç
called j<200>vanmukta†one who is free even while living†is a normal ç
person who continues to live in the world and fulfil all the duties ç
of his life. He is equanimous under all circumstances of life, never ç
attached to anything.
This treatise lays great stress on pauru<218>a or self-effort. The ç
subject of pr<193><207><193>y<193>ma (control of pr<193><207>a or ç
the life-force) is also dealt with in detail. Pr<193><207>a is essentially ç
of the form of spanda or vibration.
Seven stages of spiritual progress are also described. They are: prathama-bh<220>mik<193> ç
(study and association with saintly persons); vic<193>ra<207><193> ç
(critical thinking); asa<209>gabh<193>van<193> (dissociation from ç
all passions); vil<193>pan<200> (right understanding that the world-appearance ç
is false); ·uddhasa<221>vit-maya-<193>nandar<220>pa (a state of pure ç
knowledge and bliss); su<218>upta-sad<216>·asthiti (a state similar ç
to deep sleep, full of bliss); tury<193>t<200>ta (transcendental state ç
got after death).
@SPACE1 = 
The fifth is the state of the j<200>vanmukta.
As regards the s<193>dhanas or spiritual disciplines the Yogav<193>si<218><219>ha ç
advises the aspirant to study sacch<193>stras or right kind of scriptures ç
and cleanse the mind by getting rid of r<193>ga (attachment), dve<218>a(hatred), ç
tamas (ignorance), krodha (anger), mada (arrogance or pride) and m<193>tsarya ç
(jealousy).
Unlike <185>a<209>kara (<MS>A.<|>D.<D> 788-820), Vasi<218><219>ha declares ç
that a joint operation of karma (action) and j<210><193>na (knowledge) ç
is necessary for reaching the goal.
Great stress is also laid on v<193>san<193>-k<218>aya (destruction ç
of the root-inclinations) and  manon<193>·a  (destruction  of  the ç
tendencies in the mind that forcibly arise), with the help of tattvaj<210><193>na ç
(knowledge of the truth), the three practices always going together.
The  work  abounds  in  several interesting stories and analogies.
A few of them may be briefly set out here:
@SPACE1 = 
@NO = 1.
@NOK = On the advice of his father, the sage Vy<193>sa, <185>uka goes ç
to the king Janaka to learn about Brahman. Though severely tested, ç
he comes out successful and is taught by him.
@NO = 2.
@NOK = There is a long and interesting story of the king Padma and ç
his queen L<200>l<193> in the Utpattiprakara<207>a. The two were ç
very much attached to each other. The queen L<200>l<193> prays to ç
the goddess Sarasvat<200> and obtains the boon that when her husband ç
dies, his soul should continue to live within her room. Even though ç
the king Padma dies, his soul is confined to the room as promised ç
by the goddess. His various experiences are seen mysteriously by the ç
queen L<200>l<193>. Ulti-mately the soul of the king re-enters his ç
body. He is revived and lives happily.
@NO = 3.
@NOK = In an allegorical story, the human mind is described as a mad ç
man having a thousand hands and eyes. He constantly beats himself ç
and wanders in a dense forest. This shows the self-torturing nature ç
of the mind.
@NO = 4.
@NOK = A magician hypnotises a king. The king then experiences a long ç
series of events within a short period. This is just to show that ç
all things in this world are relative, including time and space.
@NO = 5.
@NOK = Through the story of the sage <185>ukr<193>c<193>rya, it is ç
shown how a j<200>va transmigrates due to intense desires and attachments.
@NO = 6.
@NOK = D<193>·<220>ra was a sage who was upset by his father's death. ç
He then tried to get peace of mind through austerities and performance ç
of sacrifices but failed. Finally he got it by meditation on the <193>tman ç
or the Self.
@NO = <+>7.
@NOK = Pu<207>ya and P<193>vana were brothers. The  former  was  an  enlightened ç
person whereas the latter was not. When their father died P<193>vana ç
wept bitterly. Pu<207>ya then revealed to him how he had had innumerable ç
fathers in various births and hence how it was futile to sorrow like ç
that.
@NO = <+>8.
@NOK = The king Prahl<193>da had neglected the duties of the State, ç
by constantly immersing himself in sam<193>dhi. Lord Vi<218><207>u ç
awakened him and advised him to perform his duties which were equally ç
important.
@NO = <+>9.
@NOK = G<193>dhi was a br<193>hma<207>a devotee of god Vi<218><207>u. ç
He worshipped Vi<218><207>u to know something about his M<193>y<193>-power. ç
Vi<218><207>u granted the boon. Once, when this devotee, while bathing ç
in a river, dipped his head in water, he had a vision of a wonderful ç
series of events involving himself and taking several years. When ç
he regained his normal state, he discovered through a traveller that ç
all these incidents were true and took place in a distant country.
@NO = 10.
@NOK = In the story of K<193>ka-bhu·u<207><195>a, the sage in the ç
form of a crow, Vasi<218><219>hais taught the science of pr<193><207><193>y<193>ma ç
by which one can live a very long life.
@SPACE1 = 
@NO = 11.
@NOK = A vet<193>la (the malevolent spirit of a dead man) used to ç
put difficult questions to human beings he met and would devour them ç
if they couldnot answer. He once met an enlightened king who answered ç
all the questions properly. So, he could not harm him at all!
@NO = 12.
@NOK = Bhag<200>ratha was a king who renounced everything to realise ç
Brahman. After realisation he was once requested by the people of ç
another country whose king had died, to be their king. He accepted ç
their offer and ruled wisely. This shows that a man of knowledge can ç
also be a man of action!
@NO = 13.
@NOK = The story of the king <185>ikhidhvaja of M<193>lva and his ç
queen C<220><195><193>l<193> is the longest of all. Hankering after ç
true happiness and peace they start practising spiritual disciplines. ç
C<220><195><193>l<193>, through  discriminative  knowledge, realises ç
the Self first. Her husband <185>ikhidhvaja does not succeed even ç
after severe austerities. C<220><195><193>l<193>, out of her love ç
and compassion for him, succeeds in making him realise the Self by ç
adopting some clever plans. She later tests him in various ways to ç
find out whether his realisation is true and steady. When she finds ç
him truly established in the highest knowledge of the Self, she brings ç
him back to the kingdom to rule over it like a perfectly free and ç
wise man.
@SPACE1 = 
@NO = 14.
@NOK = There was a very poor woodcutter. He used to go to a forest ç
in search of wood every day and supported his family by selling the ç
wood thus collected. By constantly striving to better his earnings, ç
he one day found the philosopher's stone. This solved his problem ç
permanently. This storyshows how constant efforts at perfection, ç
done according to the instructions of the teacher and the scriptures, ç
will surely succeed one day.
Incidentally, this wonderful work touches upon some other topics also. ç
It is opined that v<193>san<193>s are responsible to bring the soul ç
back to other lives. Hence, ·r<193>ddhas or obsequial ceremonies to ç
the dead are not of much use.
As regards ritualistic worship, it is <193>tmap<220>ja or worship ç
of the Self through bodha (understanding), s<193>mya (sense of equality ç
towards all) and ·ama (calmness of mind) that really matters. Other ç
ingredients which are helpful are: maitr<200> (friendliness towards ç
all); karu<207><193> (compassion towards the lowly and the suffering); ç
mudita (delight towards those who are happy) and upek<218><193> (conscious ç
indifference towards the evildoers).
M<220>rtip<220>j<193> or image-worship is considered equal to b<193>lakr<200><195><193> ç
or child-play.
On the whole, the Yogav<193>si<218><219>ha is a work that challenges ç
the intellect by its uncompromising logic and is, at the same time, ç
exhilarating by its beautiful poetry.
@NT = yogavidhi
@N1 = (`method of yoga')
This is a word that has been used only in the Ka<219>ha Upani<218>ad ç
(6.18).<MS>
This Upani<218>ad declares at the very end that Naciketas attained ç
Brahman after knowing from Yama, the god of death, the vidy<193> (spiritual ç
wisdom) and the yogavidhi (the method of yoga) in its complete form.
What is this yogavidhi? It is a discipline described earlier in the ç
verse 6.10. It consists of withdrawing the five organs of knowledge ç
from their external objects along with the mind, and make the intellect ç
steady (in Brahman).
However, it is not only Naciketas but anyone else too, who follows ç
this yogavidhi, that attains the deathless state.
@NT = yogavighnas
@N1 = (`hindrances to yoga')
Yogavighnas, obstacles and hind-rances to yoga (concentration and ç
meditation leading to God-realisation or libera- tion), are many and ç
varied. They have been listed by some works such as the <185>ivasa<221>hit<193> ç
(5.1 onwards), Yogaku<207><195>ali Upani<218><193>d (1.56 to 61) ç
and Yogatattva Upani<218>ad (30, 31).
They are: bhoga (enjoyment); dharma (ritualism); j<210><193>na (intellectual ç
knowledge); div<193>supti (sleeping during daytime); vi<218>am<193>sanado<218>a ç
(defects of <193>sanas); sa<221>·aya (doubts); pramattat<193> (conceit); ç
<193>lasya (laziness); nidr<193> (excessive sleep); bhr<193>nti (anomalous ç
understanding); str<200>laulya (sexuality); m<216>gat<216><218><207><193> ç
(illusory and vain desires).
The Yogas<220>tras of Pata<210>jali (200 <MS>B.C.<D>) has listed ç
nine obstacles called antar<193>yas and five more that create tensions ç
in the mind (vide 1.30 and 31). See <MS>ANTAR°YAS<D> for details.
@NT = Yoga-Y<193>j<210>avalkya
@N1 = or
@NTK = <R>ç
Yogi-Y<193>j<210>avalkya
This is a small work on Yoga attri-buted to the great sage Y<193>j<210>avalkya. ç
It has 506 verses spread over 12 chapters.
@SPACE1 = 
In an assembly of sages, G<193>rg<200> (considered the best among ç
the experts in the knowledge of Brahman) and Maitery<200> (Yaj<210>avalkya's ç
first wife, considered as the best among married women) were also ç
present. G<193>rg<200> prostrated herself before Y<193>j<210>avalkya ç
and requested him to teach the essence of yoga. The sage agreed and ç
expounded its eight limbs viz., yama (ten disciplines like ahi<221>s<193> ç
or non-violence), niyama (also ten disciplines like tapas or austerity), ç
<193>sana (bodily postures of eight kinds), pr<193><207><193>y<193>ma ç
(control of breath with appropriate mantras), praty<193>h<193>ra (withdrawal ç
of senses), dh<193>ra<207><193> (fixing the mind on the object of ç
concentration and is of five kinds), dhy<193>na (meditation) and sam<193>dhi ç
(superconscious experience).
Other important points stressed in this work are: performance of actions ç
enjoined by Vedic injunctions; posture for controlling the pr<193><207>ic ç
energy; rousing of the Ku<207><195>alin<200> power; appearance of ç
some psychic experiences indicating the progress in the path of yoga.
@NT = Yoge·var<200>
@N1 = (`queen of yogas')
Yoge·var<200> is an aspect of the Divine Mother. She is called so, ç
since she provides the benefits of yoga to the aspirants who are practising ç
it sincerely (vide Dev<200>-pur<193><207>a, Chapter 45). Yoga is ç
defined as the integrated approach of the mind and the senses towards ç
itself, by the <193>tman or the Self.
She is also called °di·akti (the Primeval Power) who emerged out of ç
the mouth (as light) of <185>iva during his encounter with the demon ç
Andhaka.
Sometimes she is counted as the eighth m<193>t<216>k<193>, after the ç
seven (Sapta-m<193>t<216>k<193>s).
She is identified with Raktac<193>mu<207><195><193> also. Iconographical ç
works describe her as dark in colour with three eyes and a long tongue. ç
She has ten hands and rides on a crow.
@SPACE1 = 
She is worshipped in the Maha-rashtra region as Ambeyogai or Joge·var<200>.
