@NT = yogi
@N1 = (`one who has attained concentration of mind')
In general, anyone who is practising any kind of the well-known yogas ç
(See <MS>YOGA<D> for details.) can be called a yogi.
The Vy<193>sabh<193><218>ya on the Yogas<220>tras (3.51) of Pata<210>jali ç
(200 <MS>B.<|>C.<D>) describes four kinds of yogis.
See <MS>PRATHAMAKALPIKA<D> for details.
@EMERGENCY = The Ha<219>hayogaprad<200>pik<193> (4.106-112), a standard ç
work on Ha<219>hayoga, describes in  detail  the  condition  of  a  yogi† ç
considered as mukta or emancipated† especially in sam<193>dhi (superconscious ç
state). He has transcended all dualities of mundane life.
@NT = yogin<200>s
@N1 = (`women with yogic powers,'<R>ç
`goddesses')
@EMERGENCY = In the t<193>ntrik practices, the male s<193>dhaka, called ç
a yogi, needs the help of a mate in certain occult rites. Such women, ç
ceremonially infilled with great powers, are designated as yogin<200>s.
@EMERGENCY = The word is also used to indicate the goddesses emanating ç
out of the effulgence of °di·akti or the Primeval Goddess. Their number ç
may be 8 or 62 or 64. Their names have been mentioned in some of the ç
pur<193><207>as and other works like the B<216>han-nandike·varapur<193><207>a, ç
Skandapur<193><207>a and the Mantramahodadhi.
A  few  of  these  names  may  be mentioned here: N<193>r<193>ya<207><200>, ç
<185><193>kambhar<200>, Bh<200>m<193>, Ca<207><195>agha<207><219><193>, ç
Bhadrak<193>l<200>, K<216><218><207>a-pi<209>gal<193>, Jalodar<200>, ç
<185><193>kin<200>, Kule·<200>, Nakul<200>, £<193>kin<200> and H<193>kin<200>.
During worship, sometimes, a group of eight yogin<200>s is selected. ç
They are: Ma<209>gal<193>, Pi<209>gal<193>, Dhany<193>, Bhr<193>mar<200>, ç
Bhadrik<193>, Ulk<193>, Siddh<193>, Sa<209>ka<219><193>.
According to another view, the yogin<200>s are divinities associated ç
with the eight vargas or groups of letters of the alphabets such as ç
a-varga, ka-varga and ca-varga.
@SPACE = 
@NT = yoktra
@N1 = (`that which binds,' `a rope')
@SPACE = 
As a technical term used in Vedic sacrifices, it indicates a cord ç
of mu<210>ja grass (Saccharum sara), having three strands. It is ç
tied round the waist of the patn<200> or the wife of the yajam<193>na ç
(sacrificer), either by the <193>gn<200>dhra priest or by the adhvaryu ç
priest or even by herself. This rite is called patn<200>sa<221>hanana. ç
This makes her ceremonially fit for the sacrifice. During this rite ç
she has to recite a mantra from the Taittir<200>ya Br<193>hma<207>a ç
(3.3.3).
A similar rope, called yoktrap<193>·a, is tied round the neck of the ç
bullock whichdraws the cart containing the soma creepers.
@SPACE = 
@NT = yuddha
@N1 = (`war')
@SPACE = 
Though ahi<221>s<193> or non-violence hasbeen declared as paramadharma ç
(highest virtue), the Hindu scriptures have not forgotten the need ç
for hi<221>s<193> (force, violence) while handling the criminals and ç
the enemies of the society.
The Mah<193>bh<193>rata (°diparva 174.45) unequivocally declares ç
that before thespiritual power of a br<193>hma<207>a, the military ç
might of a k<218>attriya pales into insignificance.
Normally a king is expected to rule over his own kingdom according ç
to dharma or righteousness and never interfere with the administration ç
of other kings.
However, if other kings are bent upon invading his kingdom or create ç
trouble, he is free to adopt all means at his disposal to thwart them, ç
including yuddha or war.
A king, while dealing with another king, especially if the latter ç
is irascible and ambitious, is advised to adopt in the beginning the ç
first three up<193>yas or means viz., s<193>ma (reconciliation), d<193>na ç
(mutual rewards) and bheda (divide and rule policy). If none of these ç
works, only then   can he resort to da<207><195>a or war.
In any war, during the ancient days, both the combatants were expected ç
to follow some standard ethical rules. The Mah<193>bh<193>rata (Bh<200><218>maparva ç
1.27-32), the R<193>m<193>ya<207>a (Yuddhak<193><207><195>a 18.27, ç
28), the Manusm<216>ti (7.90-93), the <185>ukran<200>ti (4.7.354-362) ç
and other works deal with these rules. A few of these may be stated ç
here: Fighting should be between equals, similarly equipped. One should ç
not kill anyone fighting with another or who is running away from ç
the battlefield or who pleads for mercy; so also one who has lost ç
his horse or chariot or weapons or stops fighting. Treacherous means ç
or poisoned weapons should never be used.
Though these rules are generally stated and accepted by most of the ç
writers of the dharma·<193>stras, Kau<219>ilya (300 <MS>B.<|>C.<D>) ç
of the Artha·<193>stra fame has his own, strong, views.
@SPACE1 = 
A powerful king with high ambitions naturally sets his eyes on the ç
expansion of his kingdom by conquering other kings. Such a one is ç
called vijig<200><218>u (`one desirous of conquering'). Kau<219>ilya ç
gives detailed instructions to such vijig<200><218>us.
The vijig<200><218>u king can recruit men from all the four var<207>as ç
for his armed forces, though the k<218>attriyas, due to their inherent ç
fighting spirit, form the core.
There should be a permanent, well-trained, standing army.
In addition, fighting forces should be raised during invasions or ç
emergencies by paying higher wages or getting them fromallies.
A well-planned army generally comprised four divisions†hence the name ç
catura<209>gadala†viz., infantry, cavalry, chariots and elephants. ç
There had to be practice of the fighting arts everyday except on declared ç
holidays.
This had to be ably supported by an armoury, stores containing food ç
articles and  other  essential  supplies  as  also medical and paramedical ç
staff.
Y<193>na or invasion had to be meticulously planned by the king with ç
the assistance of his ministers and others. Friends had to be mobilised ç
and enemies had to be neutralised. Espionage had to be strengthened. ç
A reliable regent (called ·<220>nyap<193>la) should be appointed to ç
take care of the kingdom during the king's absence.
Yuddha has been described as of three types: prak<193>·ayuddha (open ç
fight); k<220><219>ayuddha (concealed fighting or tactical warfare); ç
t<220><218><207><200><221>yuddha (silent fight or using  secret  agents  for  enticing  the ç
enemies).
The existence of naval forces is indicated by the words such as nimna-yodhin ç
(fighter in water).
@SPACE1 = 
Some of the other related topics dealt with in Kau<219>ilya's work ç
are: appointment of suitable officers in various grades; organisation ç
of skandhav<193>sa or camps during the war; formation of the forcesinto ç
several vy<220>has like da<207><195>a-vy<220>ha (staff-array), bhogavy<220>ha ç
(serpent-array), ma<207><195>ala vy<220>ha (circular-array) and so ç
on; placement of one-third or one-fourth of the mobilised troops to ç
protect the kingdom; extra troops for guarding the rear.
It may be interesting to note that the Artha·<193>stra mentions ç
several types of weapons and implements of war as follows: s<193><209>gr<193>mika ç
(weapons useful in the battle- field); daurgakarmika (weapons needed ç
for defending the fort); parapur<193>bhigh<193>tika (weapons needed ç
for battering down an enemy's fort).
@NID = <+><+><|>The implements are: yantra (machines); <193>yudha (weapons ç
proper); <193>vara<207>a (shields); upakara<207>a (other equipment).
A large number of machines are described, the principal purpose of ç
which appears to be to throw huge stones at the enemy troops.
The section on the armoury also mentions aindraj<193>likakarma (magical ç
rites)  and  aupani<218>adikakarma  (secret practices).
There is another classification of weapons used in war. According ç
to this, the weapons can be yantramukta (discharged from a contrivance ç
like a bow or a sling), p<193><207>imukta (thrown with the hand, such ç
as a stone or a discus), mukt<193>mukta (which can be used directly ç
or thrown like a spear), amukta (used by hand like a sword) and niyuddha ç
(wrestling).
@SPACE1 = 
The epics and the pur<193><207>as are replete with the names of several ç
astras like °gney<193>stra, Aindr<193>stra and Brahm<193>stra. They ç
are arrows discharged after infilling them with power through appropriate ç
mantras. This science called astravidy<193> had to be properly learnt ç
from a competent teacher.
@SPACE1 = 
When  a  king  conquers  another kingdom he is advised to install ç
the son or a suitable relative of the defeated king if he has been ç
killed. People of the conquered territory should be well taken care ç
of, without disturbing their religion, culture and way of life. This ç
is the best way to win them over.
Unethical practices including harassing the people of the enemy's ç
country was strictly forbidden.
See also <MS>R°JY°<177>GAS<D>.
@SPACE = 
@NT = Yuddhak<193><207><195>a
@SPACE = 
This is the sixth book of the famous epic R<193>m<193>ya<207>a of ç
V<193>lm<200>ki.
See <MS>R°M°YAØA<D> for details.
@SPACE = 
@NT = Yudhi<218><219>hira
@N1-1 = (`one who is steady in battle')
@SPACE = 
If there is anyone in the epic Mah<193>bh<193>rata who could be ç
compared with R<193>ma of the R<193>m<193>ya<207>a, as to the meticulous ç
observance of dharma or righteousness, it is undoubtedly Yudhi<218><219>hira. ç
That is why he was called Dharmar<193>ja (king of dharma) and Aj<193>ta·atru ç
(one who had no enemies). With perfect purity and equanimity of mind ç
he was free from the ari<218>a<195>vargas or the six enemies like ç
lust, greed or anger. His love and consideration for others was phenomenal. ç
So was his devotion to truth and justice. Yet, he was not timid or ç
chickenhearted. He was a great hero, steady in battle, as his very ç
name suggests.
Born as the eldest of the P<193><207><195>avas by the grace of Yamadharma, ç
he was educated†along with his four younger brothers†by two great ç
teachers, K<216>p<193>-c<193>rya and Dro<207><193>c<193>rya, under ç
the tutelage of Bh<200><218>ma, the grandsire.
When his father, the king P<193><207><195>u died, he was crowned as ç
yuvar<193>ja (the crown prince). This roused the jealousy and hatred ç
of his cousin Duryodhana who tried his best to destroy the P<193><207><195>avas ç
by all the foul means he could think of such as arson and poisoning.
After escaping from the combustible palace at V<193>ra<207><193>vata, ç
to where he had been cleverly sent by Duryodhana, Yudhi<218><219>ira ç
travelled to the capital of the king Drupada, along with his brothers ç
andmother Kunt<200>. He and his brothers disguised themselves as ç
br<193>hma<207>as and participated in the svaya<221>vara of Draupad<200>. ç
(See <MS>SVAYA<189>VARA.<D>) When Arjuna won the hand of Draupad<200> ç
in it, a quirk of fate made her the wife of all the P<193><207><195>avas.
Yudhi<218><219>hira returned to Hastin<193>pura, the capital, but ç
found to his dismay that Duryodhana had usurped the kingdom. By the ç
intervention of Bh<200><218>ma he got the Kh<193><207><195>ava forest ç
area to rule. With the help of his brothers he built up a flourishing ç
empire. Indraprastha was the new capital.
@SPACE1 = 
He performed the R<193>jas<220>ya sacrifice with great pomp and grandeur. ç
This further roused the envy and ire of Duryo-dhana. Taking advantage ç
of Yudhi<218><219>hira's weakness for the game of dice, he arranged ç
the same with high stakes. Yudhi<218><219>hira lost everything including ç
his brothers and Draupad<200> who was openly humiliated. Bythe intervention ç
of Dh<216>tar<193><218><219>ra, the blind king and father of Duryodhana, ç
the kingdom was restored to him.
However, Yudhi<218><219>hira was tricked into the game of dice once ç
more, lost it and was banished to the forest for twelve years, followed ç
by one year to be lived incognito. At the end of this period, when ç
he staked his claim for his share of thekingdom, Duryodhana flatly ç
refused, forcing the P<193><207><195>avas to fight.
Once the war was decided, Yudhi<218><219>hira, along with his brothers ç
and with the assistance of K<216><218><207>a fought bravely, decimated ç
the Kauravas under Duryodhana and became the king. He ruled benevolently ç
for thirty-six years.
He then crowned Par<200>k<218>it (grandson of Arjuna) as the king ç
and left for heaven along with his brothers and Draupad<200>, walking ç
all the way in the Him<193>layas. He alone reached heaven while all ç
the others fell on the way.
His sticking to the path of dharma, come what may, has made him a ç
model to be emulated for all time.
See also <MS>YAK<186>APRA<185>NA<D>.
@SPACE = 
@NT = yugadharma
@N1-1 = (`characteristics of the [four]<R>ç
yugas')
@SPACE = 
The pur<193><207>as often mention the four yugas†K<216>ta, Tret<193>, ç
Dv<193>para and Kali† which come and go in a cyclic order. They are ç
actually epochs differing from one another in their characteristic ç
features.
One of the simple, but nice, descriptions of such characteristics, ç
called yuga-dharmas, is found in the Par<193>·arasam<216>ti (circa ç
<MS>A.<|>D.<D> 100). It may be briefly summarised as follows:
In the K<216>tayuga, tapas or austerity was given the most important ç
place in life. The Manusm<216>ti was the standard work, the rules ç
of which were strictly followed. Since it was also called Satyayuga, ç
people would leave the country itself if they saw sinful deeds committed ç
anywhere. Even talking to a sinner was considered a sin. Curses uttered ç
by the people†since they were extremely pious† would take effect immediately. ç
Donors were so generous that they themselves would personally approach ç
the needy and give them what they wanted.
In the Tret<193>yuga there was slight deterioration in the standards ç
of ethical life. J<210><193>na or knowledge was considered all-important. ç
The Gautamadharmas<220>tras was the standard text followed. People ç
would desert their village itself if theysaw sinful deeds committed. ç
Even accidentally touching a sinner was itself considered a sin. A ç
curse uttered against anyone would act within ten days. Generous donors ç
would give gifts after calling or inviting the needy ones.
In the Dv<193>parayuga dharma declined further, to the tune of fifty ç
percent. Yaj<210>a (Vedic rituals) was the order of the day. The <185>a<209>kha-likhita-dharmas<220>tras ç
was the main authority for dharma. If in any family dharma was transgressed ç
even by one, the whole family was abandoned. Anyone accepting food ç
from a sinner was deemed to have sinned himself. Curses uttered would ç
take a month to become effective. Gifts used to be given after the ç
person begged for it.
@SPACE1 = 
The Kaliyuga was deemed to be the worst. Dharma would have decreased ç
to such an extent with only a quarter left behind. D<193>na or giving ç
gifts was the most important righteous act. The Par<193>·ara Sm<216>ti ç
was the standard holy text to be followed. If a sin were committed ç
by a person, only he had to be abandoned. Persons perpetrating sinful ç
deeds were considered depraved. Curses would take a year to become ç
effective. Gifts would be given only after extracting service.
In Kaliyuga, dharma and satya (truth) would be overcome by adharma ç
and an<216>ta (untruth). Servants would rule over kings and women ç
over men. Religious rites  like  Agnihotra  would  decline, honouring ç
elders would disappear and young girls give birth to babies! Thus ç
there would be an all-round decline of values.
@SPACE = 
@NT = yug<193>di
@N1 = (`beginning of an epoch')
@SPACE = 
The arrival of the New Year is a great event that is duly celebrated ç
by the people of all religions and cultures, all over the world. The ç
most widely accepted New Year's Day among the Hindus is the C<193>ndram<193>na ç
Yug<193>di, the first day of the bright half of the month of Caitra ç
(March-April). It is one of the 3<P8.5W1><$E 1/2 ><P255D> days considered ç
to be extremely auspicious, the others being Vijayada·am<200>, Balipratipad<193>, ç
and Ak<218>ayyat<216>t<200>y<193>. Brahm<193>, the Creator, is said ç
to have created this world on this day and the reckoning of time begun ç
from the sunrise of this day. Hence the name `yug<193>di' (beginning ç
of an era or epoch). Emperor <185><193>l<200>v<193>hana (circa <MS>A.<|>D.<D> ç
79) is believed to have been crowned on this day. Consequently this ç
era is called the <185>aka Era or the <185><193>l<200>v<193>hana <185>aka.
Pa·c<193>tt<193>pa or repentance for the evil deeds committed during ç
the past year, (whether knowingly or unknowingly), prayers for forgiveness, ç
performance of mah<193>·<193>nti rites to ward off all future evils ç
or misfortune, worship of the presiding deity of the year as indicated ç
by the day of the week on which the yug<193>di falls*, worship of ç
Brahm<193> the Creator with all the upac<193>ras (items showing honour), ç
worship to other deities, to units of time and nak<218>atras or asterisms ç
and finally to Vi<218><207>u†are the religious rites specially recommended. ç
Br<193>hma<207>as of learning and good character have to be honoured ç
on this day by feeding them with food and offering gifts of money, ç
water-pot and a copy of the new pa<210>c<193><209>ga (almanac). One ç
should also listen to the reading of that pa<210>c<193><209>ga by ç
the family priest.
Taking bath after anointing the body with oil (called `abhya<210>janasn<193>na' ç
or `oil-bath' in the Indian English), wearing new clothes, decorating ç
the house, eating a mixture of tender neem leaves and jaggery followed ç
by a sumptuous feast, giving presents to servants and dependents† ç
these are the social aspects of the celebration.
Listening to the forecasts given in the pa<210>c<193><209>ga can help ç
one to prepare himself for facing the untoward incidents or circumstances. ç
Eating the mixture of the bitter neem leaves along with the sweet ç
jaggery is supposed to be good for health and also an antidote for ç
the illnesses common in the spring season. Taken in a symbolic sense, ç
it can psychologically prepare one to be equanimous under all circumstances ç
of life, whether bringing pain or pleasure, since the new year may ç
not be much different from the previous one!
@SPACE1 = 
C<193>ndram<193>na Yug<193>di is observed widely as the New Year's ç
Day in Andhra Pradesh, Karnataka and Maharashtra. In some parts of ç
the country, especially in Maharashtra, a long bamboo is decorated ç
with a silk cloth and a silver or copper vessel is put over it. A ç
garland of sweets and neem leaves is tied at the upper end. This  is  called  `gu<195>hi.'  This  is  then ç
worshipped and hoisted on the terrace of the house. It is taken down ç
after sunset and the sweets and neem leaves are distributed among ç
all, especially the children, to be consumed as pras<193>da or consecrated ç
food. Because of this custom of raising the gu<195>hi on the pa<195>hv<193> ç
(or pratipad) day, the day (Yug<193>di) itself is christened as `Gu<195>hi ç
Pa<195>v<193>.' According to one belief, this is actually a flag-hoisting ç
ceremony to commemorate the killing of V<193>l<200>, the monkey chief ç
of Ki<218>kindh<193>, by <185>r<200> R<193>ma on this day.
Yug<193>di is also the first day of the nine-day festival†Vasantanavar<193>tra† ç
dedicated to the worship of the Divine Mother Durg<193>. Why there ç
are two Navar<193>tras, one in Vasanta <216>tu (spring) and the other ç
in <185>arad<216>tu (autumn), is a matter of conjecture. It is possible ç
that the two festivals became popular due to the fact of the spring ç
crops and the autumn crops being ready at these times. However, celebration ç
of the Vasantanavar<193>tra hasalmost been given up in favour of ç
<185>arannavar<193>tra.
The commencement of the New Year differs in some places. In Tamil ç
Nadu and Kerala, following the solar calendar, it starts generally ç
on the 14th April (first day of the month Cittirai). In Bengal, it ç
is `Pahal<193> Vai·<193>kh,' falling mostly on the 15th of April. ç
In other places like Gujarat it is on the Balip<193><195>yam<200> ç
day (K<193>rtt<200>ka ·ukla pratipad).
@SPACE = 
@NT = Yugapur<193><207>a
@SPACE = 
This forms the 113th chapter of thetreatise G<193>rg<200> Sa<221>hit<193>, ç
a work on astrology. It is sometimes called Skanda-pur<193><207>a†not ç
to be confused with the well-known bigger work†probably because it ç
begins with a question by Skanda to <185>iva. It is placed at 100 ç
<MS>B.<|>C.<D>
Couched in the style of the pur<193><207>as it deals mainly with the ç
characteristics of the four yugas†K<216>ta, Tret<193>, Dv<193>para ç
and Kali†that of Kaliyuga resembling closely with the one given in ç
the Vanaparva (Chapter 188, verses 30-64) of the epic Mah<193>bh<193>rata.
The attack on S<193>keta and P<193><219><193>l<200>putra by the kings ç
of P<193><210>c<193>la and Mathur<193> along with the Yavanas gets ç
a prominent place. The depredations of the enemy armies and destruction ç
of the civilian population make a dismal reading.
@NT = yugas
The concept of k<193>la or time as evolved by the Hindu scriptures ç
from the smallest unit to colossal limits is, to say the least, mind-boggling.
Nime<218>a, the time taken for winking the eyelids once, is taken ç
as the smallest unit.
The biggest unit, for the purpose of expounding the concept of yuga, ç
can be taken as one day of Brahm<193>, the four-faced creator. It ç
is called kalpa. In terms of human years it is 4.32 billion (4.32 ç
x 109)  years.
This kalpa includes 1000 mah<193>yugas. Each mah<193>yuga†also called ç
caturyuga† consists of the four well-known yugas: K<216>ta, Tret<193>, ç
Dv<193>para and Kali.
@SPACE1 = 
The following table gives an idea of these four yugas in terms of ç
divine andhuman years, the divine year being 360 times the human ç
year:
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(.9533,E1,.8875), ç
BELOW(.0833), VGUTTER(.0139), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
, <P8B>Divine Years<P255D>, <P8B>Human Years<P255D>
K<216>tayuga, <+><+><+><+>4800, <+><+><+>17,28,000
Tret<193>yuga, <+><+><+><+>3600, <+><+><+>12,96,000
Dv<193>parayuga, <+><+><+><+>2400, <+><+><+><+>8,64,000
Kaliyuga, <+><+><+><+>1200, <+><+><+><+>4,32,000
@Z_TBL_END = 
Each of these yugas is preceded by a short period called sandhy<193> ç
and followed by another, called sandhy<193><221>·a.
Thus, the K<216>tayuga is preceded by 400 divine years (sandhy<193>) ç
and followed by another 400 divine years (sandhy<193><221>·a). The  ç
figures  for  the  other  three  are 300<|>+<|>300; 200<|>+<|>200; 100<|>+<|>100.
The descriptions given so far are based on the ones commonly found ç
in the epics and the pur<193><207>as (vide Vi<218><207>upur<193><207>a ç
1.3; 6.3).
However, the meaning and concept seem to have undergone quite a few ç
changes in course of time. In the Ved<193><209>gajyauti<218>a (verse ç
5) it is a duration of five years. In the <184>gveda (3.26.3) it ç
means just a day or a very short period. In other places, the names ç
K<216>ta and so on have been used to indicate a number got by the ç
throw of dice. (vide Ch<193>ndogya Upani<218>ad 4.1.4.)
See also <MS>DV°PARAYUGA, K°LA, KALIYUGA, KALPA, K<184>TAYUGA, MANVANTARA, ç
TRET°YUGA<D>.
@NT = yukty<193>bh<193>sa
@N1 = (`semblance of reason')
In the Indian philosophical treatises, a quotation from a standard ç
text is taken up for discussion. A sa<221>·aya or doubt israised ç
about its correct meaning by mentioning two or more alternatives. ç
The opponent (called p<220>rvapak<218>in) supports one of the views ç
and gives his yuktis or arguments. The siddh<193>ntin (propounder ç
of the correct theory) refutes these arguments by showing that they ç
are only a semblance of arguments and not true. This is termed yukty<193>bh<193>sa. ç
The arguments of the siddh<193>ntin are called sadyukti or valid reason.
@NT = y<220>pa, y<220>pastambha
@N1 = (`sacrificial post')
Among the Vedic sacrifices, about thirty are classed as Pa·u or Pa·uy<193>gas, ç
wherein an animal is immolated. The post to which this animal is tied ç
is called y<220>pa or y<220>pastambha.
It is to be made of wood. The trees out of which they are prepared ç
are: pal<193>·a (Butea frondosa); khadira (Acacia catechu); bilva ç
(Aegle marmelos) and rauhitaka (Andersonia rohitaka).
Even for the selecting and the cutting of these trees, many rules ç
have been prescribed. Along with the carpenter and the wood-cutter, ç
the yajam<193>na (sacrificer) and the adhvaryu priest should also ç
be present.
The  standard  unit  of  y<220>pa's measurement is aratni, one-fifth ç
of the height of the yajam<193>na. The height of the y<220>pa varies ç
from 1 to 33 aratnis, depending on the type of the sacrifice. Usually ç
it is 3 or 4 aratnis.
The lowest part called upara is one-fifth of the total height and ç
is not chiselled. It is this part that is to be buried under ground.
The shape of the y<220>pa is octagonal, with one face being wider ç
than the other seven. This portion should face the sacrificial fire. ç
Its height is that of the yajam<193>na in the standing posture, with ç
or without the hands raised.
The girth of the y<220>pa is not fixed. Its top has a cap called ca<218><193>la, ç
made of the wood leftover, after preparing the y<220>pa proper.
@NT = yutasiddha
See <MS>AYUTASIDDHA<D>.
@END = 
