@NID = can <|>be <|>given <|>where <|>an<|> adravya <|>can be viewed both ç
as a substance and as an attribute. For example, though light is an ç
attribute of an effulgent object, it serves also as a substance, since ç
it is subject to contraction and diffusion, and possesses colour as ç
an attribute. Dharmabh<220>taj<210><193>na is another example.
See also <MS>DHARMABH<188>TAJ<178>°NA<D> and <MS>VI<185>I<186><187>°DVAITA ç
VED°NTA DAR<185>ANA.
@NT = ad<216><218><219>a
@N1 = (`the unseen')
Human efforts, however great, often end in failure or only in partial ç
success. The reason is that there is an unseen (ad<216><218><219>a) ç
power that is guiding human destinies. Success or failure depends ç
on the consonance or otherwise of this power with our efforts. This ç
belief in an unseen power is common to almost all the religious groups.
Most of the Hindu religious works use this word in the sense of `karma' ç
or fate (the consequence of actions, good or bad, done in the previous ç
lives). The word is sometimes used to indicate only merit, accruing ç
to the performer of good deeds. Some schools use it in the sense of ç
blind destiny also.
The P<220>rva-m<200>m<193><221>s<193> system however employs it in ç
a technical sense as equivalent to `ap<220>rva,' the unseen effect ç
of sacrificial rites producing the desired results <|>for the performer ç
in his future life.
Ad<216><218><219>a resides in the subtle body of the soul unfolding ç
its results at the appropriate time in future or in future life. Its ç
power is irresistible and incompre- hensible by ordinary consciousness.
@SPACE1 = 
See also <MS>AP<188>RVA<D> and <MS>KARMA<D>.
@NT = adultery
See <MS>VYABHIC°RA<D>.
@NT = Advait<193>c<193>rya
At a time when the common masses of India were oppressed by the fanatical ç
Muslim rulers on one side and the tyranny of the caste system on the ç
other, the Bhakti Movement (the Hindu spiritual renaissance through ç
bhakti or devotion to God) started and sustained by a galaxy of great ç
spiritual leaders from R<193>m<193>nuja to Caitanya (11th to 16th ç
centuries <F51320P10MSC1>A. D.<W1>) <F255P255DC255>came as a great saviour. ç
One of the important predecessors and a senior contemporary of Caitanya ç
was Advait<193>c<193>rya (16th Century <F51320P10MSC1>A. D.<W1>)<F255P255DC255> ç
also known as Advaita or Advaita Prabhu. Not much is known of him. ç
He was a resident of <185><193>ntipur and a disciple of M<193>dhavendra ç
Pur<200>. It was in his house that Caitanya met his mother <185>ac<200> ç
Dev<200> for the first time after taking to the monastic life, and ç
decided to stay at Pur<200> (Orissa) for the rest of his life in deference ç
to her wish.
Even before Vi·vambhar<192>that is how Caitanya was known in his premonastic ç
days<192>was acclaimed as a great devotee of K<216><218><207>a by ç
the contemporary Vai<218><207>ava leaders, Advait<193>c<193>rya had ç
had visions of him as an incarnation of K<216><218><207>a himself.
According to the theology developed by the later Caitanya school, ç
Advait<193>c<193>rya was an aspect of Vi<218><207>u.
@NT = Advaita-siddhi
@N1 = (`fulfilment of Advaita')
If Hindu philosophical systems have grown both in width and depth ç
revealing power and energy, it is not a little due to the freedom ç
of thought enjoyed by the various writers. It was perhaps <185>a<209>kara ç
(<MS>A.<|>D.<D> 788-820) the doyen of Advaita Ved<193>nta who initiated ç
and also gave a fillip to voluminous writing on abstruse philosophical ç
subjects. Criticism, defence and counter-criticism of his views by ç
sub- sequent writers gave rise to a phenomenal growth of Ved<193>nta ç
literature. When Vy<193>sa T<200>rtha, a pontiff of the M<193>dhva ç
school (15th-16th cent. <F51320P10MSC1>A.<|>D.<W1>) caused a jolt to Advaita ç
metaphysics by his well-known polemical work <F255P255MIC255>Ny<193>y<193>m<216>ta, ç
the Advaita tradition met his challenge through the Advaitasiddhi, ç
the most celebrated workof Madhus<220>dana Sarasvat<200> (16th cent. ç
<MS>A.<|>D.<D>).
The point of dispute between the two works is the definition of what ç
is true (satya) and what is false (mithy<193>). Any object is considered ç
as satya (true, real) only as long as it is not b<193>dhita (contradicted ç
or negated) by subsequent experience. All the criticisms of Ny<193>y<193>m<216>ta ç
against the five definitions of falsity given by the previous writers ç
on Advaita have been met by the Advaitasiddhi. The book also discusses ç
and supports many of the conflicting theories regarding the unity ç
or plurality of the selves, unity or plurality of avidy<193> (nescience), ç
Brahman or the j<200>va as the locus of avidy<193> thereby implying ç
that any of the theories can be resorted to in explaining the indeterminable ç
false world since the main interest of the advaitin is the one absolute ç
Brahman. The different theories of Advaita can be adopted by the different ç
aspirants according to their fitness (adhik<193>ra).
@SPACE1 = 
The work has three Sanskrit commen- taries of which Laghucandrik<193> ç
of Brahm<193>-nanda Sarasvat<200> is popular among the scholars.
See also <MS>ADVAITA VED°NTA DAR<185>ANA, MADHUS<188>DANA SARASVAT®, ç
NY°Y°M<184>TA<D> and <MS>VY°SAT®RTHA<D>.
@NT = Advaita Ved<193>nta Dar·ana
@N1 = (`Non-dual Ved<193>nta System')
@S10 = PREAMBLE
Man is often described as a rational animal. Once the animal in him ç
is reasonably satisfied by the provision of basic biological and some ç
psychological needs, the rational part gets an opportunity to evolve ç
to higher levels. Philosophy including metaphysics is one of the highest ç
aspects of this evolution.
@S10 = DAR<185>ANAS
The Indian philosophical systems have developed not only as a result ç
of intellectual speculation but also of mystical intuition. Hence ç
the name `dar·ana' (lit., `seeing'), usually applied to them. The ç
topics most commonly discussed by these dar·anas are generally four: ç
(a) nature of the physical world, its origin and evolution; (b)nature ç
of man and other living beings; (c) existence of God, his nature and ç
attributes; (d) the goal of human life and the way of attaining it.
Different standpoints and differing views of these topics of discussion ç
have naturally led to a variety of schools. These schools are broadly ç
divided into two classes: the <193>stika and the n<193>stika. The ç
former accept the authority of the Vedas whereas the latter do not.
@S10 = VED°NTA DAR<185>ANA
The Ved<193>nta Dar·ana is the last of the former schools but has ç
gained themost important place among them. Ajudicious combination ç
of reasoning and acceptance of the authority of the Vedas as also ç
a long unbroken tradition are responsible for its gaining the pre-eminent ç
place.
Though the `prasth<193>natraya' (`the three great paths') viz., the ç
Upani<218>ads, the Brahmas<220>tras and the Bhagavadg<200>t<193>, ç
are the basis of the Ved<193>nta Dar·ana, it is the Brahmas<220>tras ç
(also called Ved<193>nta-s<220>tras and <185><193>r<200>rakas<220>tras) ç
of B<193>dar<193>ya<207>a-Vy<193>sa that occupies the key position. ç
The s<220>tras (aphorisms) being quite terse and often ambiguous have ç
naturally led to widely differing interpretations, resulting in the ç
three well-known systems of Ved<193>nta viz., Advaita, Vi·i<218><219><193>dvaita ç
and Dvaita.
The word `Ved<193>nta' itself means the `end or the essence of the ç
Vedas.' It is the Upani<218>ads that mainly comprise the Ved<193>nta ç
since they normally form the last part of the Vedic literature and ç
contain the quintessence of their teachings.
@S10 = ADVAITA VED°NTA
The Advaita Ved<193>nta Dar·ana owesits systematisation as a formidable ç
doctrine, to Gau<195>ap<193>da (7th-8th cent. <F51320P10MSC1>A.D.<W1>) who ç
wrote his famous K<193>rik<193>s on the <F255P255MIC255>M<193><207><195><220>kyopani<218>ad ç
and <185>a<209>kara (<F51320MS>A.<|>D.<W1> 788-820). <185>a<209>kara's commentaries ç
on the prasth<193>natraya as also a few independent treatises form ç
the bedrock on which the later Advaitins built their edifices.
`Advaita' means `non-dual', `one without a second'. The system derives ç
this nomenclature from the fact that it recognises Brahman (the Absolute) ç
as the only reality and denies permanent reality to the world as also ç
to the individual souls.
The entire edifice of Advaita metaphysics is built upon the foundation ç
that Brahman is the only reality, `brahma satyam'. This premise is ç
based firmly on the famous Upani<218>adic statement `sadeva somya ç
idamagra <193>s<200>t, ekamev<193>dvit<200>yam.' `Dear (<185>vetaketu), ç
in the beginning (before creation) <|>Reality <|>(or <|>Brahman) <|>alone ç
existed, the one without a second' (Ch<193>ndogya Upani<218>ad 6.2.1). ç
However, the world of multiplicity is a matter of our day-to-day experience. ç
Hence it becomes necessary to offer an explanation as to how Brahman, ç
the one without a second, appears as this world of multiple names ç
and forms. The explanation offered by Advaita is `Anirvacan<200>yakhy<193>ti,' ç
its theory of erroneous cognition, which defies logic. (For other ç
theories about erroneous cognition see <MS>KHY°TIS<D>.) Perceiving ç
silver in nacre in moonlight or snake in rope in insufficient light ç
are stock examples given by the Advaitins. In both cases there is ç
an erroneous perception brought about by the impressions of silver ç
and snake from an earlier idea of the same, now superimposed upon ç
nacre and rope under conditions favourable to the error. This superimposition ç
called `adhy<193>sa' or `adhy<193>ropa', is responsible for the mithy<193>j<210><193>na ç
(false knowledge) that the object perceived is silver or snake.
@SPACE1 = 
The silver or the snake perceived is neither `sat' (real) nor `asat' ç
(unreal). It is not asat or unreal like `the son of a barren woman' ç
since it is actually perceived. Neither is it sat or real since it ç
disappears as soon as the substratum (the nacre and the rope) is perceived ç
as it is. To explain such a peculiar phenomenon <185>a<209>kara creates, ç
out of logical necessity, a third type of perceived objects which ç
is `sad-asad-vilak<218>a<207>a' (different from both the real and ç
the unreal). The `khy<193>ti' or the cognition itself is described ç
as `anirvacan<200>ya,' incapable of any precise definition or description.
The basic cause of this erroneous perception is termed `aj<210><193>na' ç
or `avidy<193>' (ignorance) which is said to be bh<193>var<220>pa ç
(existent) and is endowed with two ·aktis or powers viz., `<193>vara<207>a·akti' ç
(veiling power) and `vik<218>epa·akti' (transforming power). It veils ç
the true nature of nacre and rope and shows up silver and snake in ç
their place by apparently transforming them. Such an apparently transformed ç
object is called a `vivarta' of the original and the theory that propounds ç
this is known as `Vivartav<193>da.'
Since this avidy<193> does not make the nacre and the rope completely ç
disappear from view, but only makes them appear as something else, ç
it is described as bh<193>var<220>pa or existent.
An attempt may now be made to explain how this world of duality has ç
evolved out of the non-dual Reality called Brahman in the Upani<218>ads. ç
The world of duality can be broadly divided into `d<216>k' (the seer) ç
and `d<216>·ya' (the seen). Both these again are divided into the ç
innumerable living beings (j<200>v<193>s) and the countless objects ç
of creation. How does Brahman the Absolute, the One without a second, ç
the indivisible Reality, appear divided into innumerable beings on ç
the one side and countless objects on the other? It is avidy<193> ç
that causes the one °tman (the Self)<192> incidentally, the Upani<218>ads ç
use both words, °tman and Brahman, to indicate the same Reality<192>appear ç
as many j<200>vas and it is m<193>y<193> that causes the world of ç
phenomena. M<193>y<193> is avidy<193> at the cosmic level.
<185>a<209>kara accepts three degrees of reality. The first, known ç
as `pr<193>tibh<193>sika-satya' (apparent truth, illusory appearance) ç
is illustrated in the wrong perception of silver in nacre or snake ç
in rope. The second, called `vy<193>vah<193>rika-satya' is illustrated ç
by this world of our day-to-day experience. This world-appearance ç
has a much higher degree of reality and lasts till one gets <193>tmaj<210><193>na ç
or brahmaj<210><193>na, realization of the Truth, °tman-Brahman. It ç
is satya or true for all purposes of vyavah<193>ra i.e., day-to-day ç
existence or practical life. The third, designated as `p<193>ram<193>rthika-satya,' ç
is the highest Truth and the only truth that really exists. It is ç
Brahman or °tman, which is nirgu<207>a (without attributes) and nir<193>k<193>ra ç
(without forms), hence incapable of being described except in a negative ç
way (`neti,' `neti'†`not this, not this').
Brahman associated with m<193>y<193> is Sagu<207>a Brahman (Brahman ç
with attri-butes) or ®·vara (Lord of creation, God). It is this aspect ç
of Brahman that is responsible for creation, preservation and destruction ç
of the world. As for the actual order of evolution of the created ç
world, the descriptions given in the Upani<218>ads are accepted.
For <185>a<209>kara who holds that the world process is only a `vivarta' ç
(illusory appearance) due to adhy<193>sa (superimposition) on Brahman, ç
the very attempt to describe the various steps of evolution is a futile ç
exercise.  However,  since  the  ·ruti (revealed scripture, the Upani<218>ads) ç
has done so, a place of honour must somehow be accorded to it. Hence ç
he characterises such descriptions as giving the `ta<219>astha-lak<218>a<207>a' ç
(accidental or casual charac- teristics) of Brahman helping us to ç
be directed towards it, even as the branch of a tree helps us to locate ç
the crescent in the sky. On the other hand Brahman as it is, can be ç
comprehended only through its `svar<220>palak<218>a<207>a' (integral ç
or essential characteristics), which is `sat-cit-<193>nanda.' `Sat' ç
(eternal reality), `cit' (pure consciousness), and `<193>nanda' (unalloyed ç
bliss) are not really its characteristics but its very essence.
This Brahman or °tman which is sat-cit-<193>nanda, has inexplicably ç
got itself involved in the body-mind complex, the involvement being ç
due to avidy<193>. Since the origin of this involvement can never ç
be logically or satisfactorily explained, avidy<193> is stated to ç
be an<193>di or beginningless. The involved <193>tman is designated ç
as `j<200>va.'
This j<200>va, the <193>tman in bondage, has five ko·as or sheaths ç
(For details see <MS>PA<178>CAKO<185>AS.),<D> three ·ar<200>ras or ç
bodies (See <MS>STH<188>LA<185>AR®RA, S<188>K<186>MA<185>AR®RA<D> ç
and <MS>K°RAØA-<185>AR®RA<D>.), performs actions motivated by desires, ç
experiences pleasure and pain due to karma and undergoes transmigration ç
(See <MS>KARMA<D> and <MS>PUNARJANMA.<D>) until libera- tion. <185>a<209>kara ç
declares that this j<200>va, when shorn of its up<193>dhis or limiting ç
adjuncts like the body and the mind, is identical with Brahman, since ç
its essential nature also is sat-cit-<193>nanda.
The main trouble with the <193>tman become j<200>va is the t<193>d<193>tmya ç
or false identification with the mind and the body brought about by ç
adhy<193>ropa or adhy<193>sa (superimposition). Hence the only way ç
of remedying it is by apav<193>da or desuper-imposition, denying this ç
identification. For this, one has first to prepare oneself by the ç
preliminary fourfold discipline or s<193>dhana-catu<218><219>aya viz., ç
viveka (discrimination between the eternal and the non-eternal), vair<193>gya ç
(dispassion), ·am<193>di- <218>a<219>ka (cultivation of the six virtues ç
like self-control) and mumuk<218>utva (desire for liberation). (For ç
details see <MS>S°DHANA-CATU<186><187>AYA<D>.) Then one has to approach ç
a competent guru (spiritual preceptor) and learn the truth from him ç
by ·rava<207>a (hearing), manana (reflection) and nidi-dhy<193>sana  (contemplation).  The  most ç
important part of the guru's teaching will be in the form of `mah<193>v<193>kyas' ç
(great sentences) like `tat tvam asi' (That thouart') or `aha<221> ç
brahm<193>smi' (`I am Brahman'). (See <MS>MAH°V°KYAS<D> for details.) ç
<185>rava<207>a and manana produce the deep-rooted conviction that ç
one is the spirit. Hence in nididhy<193>sana, desuperimposition in ç
the form of `I am not the body, nor the sense-organs, nor the mind, ç
nor even the ego' and so on, can be practised leading ultimately to ç
the realization that one is the <193>tman. This realization resulting ç
in mukti or liberation can be had even while one is living in this ç
body. It is known as `j<200>vanmukti.' He will attain `videhamukti' ç
after the body falls off, the continuance of the body between the ç
two states being due to pr<193>rabdha-karma. (See <MS>PR°RABDHA KARMA<D>.)
Mukti or liberation from transmigration is not the gaining of a new ç
state but recognising the already existing original state.
Two kinds of mukti<192>j<200>vanmukti and videhamukti<192>are envisaged ç
in the Advaitic works. The Vivara<207>a school upholds the theory ç
that mukti is simultaneous with j<210><193>na. Hence j<200>vanmukti ç
is not only possible, but the only mukti that can be recognised. Continuance ç
of the body for some more time, due to pr<193>rabdha karma, has no ç
effect upon j<210><193>na. On the other hand, the Bh<193>mat<200> ç
school holds that even after j<210><193>na, if the body continues ç
due to pr<193>rabdha karma, this imposes a limitation thereby implying ç
the existence of a trace of avidy<193>. The death of the body puts ç
an end even to this trace of avidy<193>, and real mukti is obtained ç
then. Since this comes after the death of the body, it is called `videhamukti.'
A favourite topic of discussion that frequently crops up in Advaita ç
metaphysical works is the locus of avidy<193>. Since Brahman is the ç
only reality that exists, it alone is the <193>·raya (locus) as also ç
the vi<218>aya (object) of avidy<193>. This is one school. Sure·vara ç
andPadmap<193>da are the main protagonists of this school. According ç
to them avidy<193> is one only.
Since Brahman is pure consciousness, avidy<193> can never exist in ç
it nor act on it. This is the opposing school propagated by V<193>caspati ç
Mi·ra. For him, the j<200>vas are the loci of avidy<193> and there ç
is one avidy<193> for every j<200>va.
@S10 = POST-<185>A<177>KARA ADVAITA
Though <185>a<209>kara wrote profusely, clearly enunciating the main ç
doctrines of his school, there are certain places in his writings ç
wherein the important aspects of certain doctrines are either vague ç
or are capable of more than one interpretation. This has naturally, ç
resulted in the growthof quite a voluminous post-<185>a<209>kara ç
Advaita literature leading to different prasth<193>nas or schools ç
of thought. The `V<193>rttika-prasth<193>na' of Sure·vara (9th cent. ç
<MS>A. D.<D>) comes first in the series. This school getsits designation ç
from the exposition contained in the `v<193>rttik<193>s' or commentaries ç
in verse of Sure·vara on <185>a<209>kara's bh<193><218>yas on the ç
B<216>had<193>ra<207>yaka and the Taittir<200>ya Upani<218>ads. ç
According to this school, Brahman is the material cause of this world, ç
and not m<193>y<193>. The locus of avidy<193> is Brahman and not the ç
j<200>vas. Avidy<193> is one only and not many. The mah<193>v<193>kyas ç
or the great Vedic dictums are capable of producing immediate cognition ç
of the Self as Brahman. Hence dhy<193>n<193>bhy<193>sa or practice ç
of meditation on the meaning of those dictums is not necessary. The ç
j<200>vas are but <193>bh<193>sas or appearances of Brahman in the ç
individual minds. (This has earned the theory, the designation of ç
`<193>bh<193>sav<193>da' as opposed to `pratibimbav<193>da' and `avaccheda-v<193>da' ç
of other schools.)
@SPACE1 = 
The `Vivara<207>aprasth<193>na' of Padma-p<193>da (9th cent. <F51320P10MSC1>A.<|>D.<W1>) ç
and Prak<193>·<193>tman (<MS>A.D.<W1>1220) comes next. The name ç
is derived  from  the  work  <F255P255MIC255>Pa<210>cap<193>dik<193>- ç
vivara<207>a of the latter, it being a voluminous commentary on the ç
Pa<210>cap<193>dik<193> of Padmap<193>da, which itself is a commentary ç
on <185>a<207>kara's Brahmas<220>tra-bh<193>sya. Though this name ç
suggests that it covers five p<193>das or sections of the Brahmas<220>tras, ç
only the commentary on the first four s<220>tras is now available. ç
The chief doctrines of this school are: Avidy<193> is a ja<195><193>tmik<193> ç
·akti (a force of material nature) and is the material cause of this ç
world. It is bh<193>var<220>pa, a positive entity but not real. M<193>y<193>, ç
prak<216>ti, avyakta, avy<193>k<216>ta, tamas, ·akti etc., are all ç
its synonyms. It is called avidy<193> when <193>vara<207>a power is ç
predominant and m<193>y<193> when vik<218>epa power becomes dominant. ç
Alternatively, it is m<193>y<193> at the cosmic level and avidy<193> ç
at the individual level. Avidy<193> rests on Brahman but acts on the ç
j<200>vas. The j<200>v<193>s are pratibimbas or reflections of Brahman ç
in the anta<199>kara<207>a (mind). The reflected images have no reality ç
other than that of the original (bimba) brahman. This theory is called ç
`pratibimbav<193>da' and contrasted with `<193>bh<193>sav<193>da'.
@SPACE1 = 
The `Bh<193>mat<200>prasth<193>na' of V<193>caspati Mi·ra (<F51320P10MSC1>A. ç
D.<W1> 840) is the third and the last of these major schools. <F255P255MIC255>Bh<193>mat<200> ç
is his celebrated commentary on the <185><193><209>kara-bh<193><218>ya ç
of Brahmas<220>tras. This school is built round the Bh<193>mat<200> ç
along with its subsidiary commentaries Kalpataru of Amal<193>nanda ç
(13th cent <F51320MS>A. D.<W1>). and <F255MI>Parimal<193> of Appayya D<200>k<218>ita ç
(16th cent <F51320MS>A. D.<W1>) The views of this school can be briefly ç
summarised as follows: Brahman is the material cause of the world, ç
not as the locus of avidy<193> but as the object of avidy<193>s supported ç
by the j<200>vas. M<193>y<193> is only an accessory cause. Avidy<193> ç
cannot abide in Brahman. It abides in the j<200>vas and is plural ç
since the j<200>vas are plural. V<193>caspati advocates two varieties ç
of avidy<193>: the m<220>l<193>vidy<193> or k<193>ra<207><193>vidy<193> ç
(primal nescience); the t<220>l<193>vidy<193> or k<193>ry<193>vidy<193> ç
(derivative nescience). It is the latter that is responsible for bhrama-sa<221>sk<193>ras ç
or error impressions. Also, V<193>caspati appears more inclined towards ç
the `avacchedav<193>da' or the theory of limitation with regard to ç
the appearance of the j<200>vas. Just as a pot limits the infinite ç
sky in itself, avidy<193> of the individual limits Brahman and makes ç
it appear like a j<200>va. Another point of importance in this school ç
is that the mah<193>v<193>kyas do not produce anubhava (immediate ç
cognition). It is the mind seasoned by meditation that gives such ç
experience.
Mention may also be made here of `d<216><218><219>is<216><218><219>i-v<193>da' ç
which advocates that the world is created simultaneously with its ç
perceptions, and, `ekaj<200>vav<193>da,' which propounds that there ç
is only one j<200>va which is in bondage and when it gets liberation, ç
everything else disappears. Prak<193>·<193>nanda (15th-16th cent. ç
<MS>A.<|>D.<D>) is the chief exponent of these schools.
Advaita was subjected to continuous criticism by other Ved<193>ntic ç
schools as also the Buddhists and hence the growth of polemical literature ç
became inevitable. Mention must be made of two most important works ç
of this type: The Kha<207><195>ana-kha<207><195>a-kh<193>dya of ç
<185>r<200>har<218>a (12th cent. <F51320MS>A.D.<W1>) and the <F255MI>Advaitasiddhi ç
of Madhus<220>dana Sarasvat<200> (16th cent. <F51320MS>A. D.<W1>).
@S10 = CONCLUSION
It should be said to the credit of Advaita Ved<193>nta that even now ç
it is attracting the respectful attention from scholars  of  the  highest  calibre,  both ç
Eastern and Western.
@S10 = <P8W1I>NOTE<|>:<P255D>
@BT9 = The number of connected topics is too large to be mentioned ç
separately for cross reference. The reader can look for them under ç
the respective titles as he comes across them in thisessay.
@NT = Advayat<193>raka Upani<218>ad
It is a minor Upani<218>ad belonging to the <185>ukla Yajurveda ç
and classed among the `Yoga-Upani<218>ads,' Upani<218>ads that dealwith ç
yogic meditations and other processes. Except for the last part which ç
is in verses (14 to 18), the whole Upani<218>ad is in elegant prose.
It has been called `Advayat<193>raka' since it deals with Brahman, ç
the one without a second (`advaya'), which takes us beyond (`t<193>raka') ç
sa<221>s<193>ra or transmigratory existence.
The Upani<218>ad begins with the statement that it has to be taught ç
to one who is struggling to meditate upon Brahman, the Absolute, (`yati,' ç
`one who struggles') who has practised self-control (`jitendriya') ç
and who has cultivated the six virtues like peace (`·am<193>di<218>a<219>ka'). ç
Then it describes that one who meditates upon light in between the ç
eyebrows as Brahman attains to It. After negating the difference between ç
thej<200>v<193>tman (individual self) and ®·vara (Supreme Soul) as ç
brought about by the limiting adjuncts like m<193>y<193>, it goes ç
on to describe a yogic meditation for attaining Brahman, the Absolute.
@SPACE1 = 
The su<218>umn<193>-n<193><195><200> (a tube-like structure meant ç
for the passage of the ku<207><195>alin<200>) (See <MS>KUØ£ALIN®<D>.) ç
is situated in the middle of the body, stretching from the mul<193>dh<193>ra ç
plexus at the root of the spinal column, up to the brahmarandhra or ç
the aperture in the crown of the head. It shines like the sun or the ç
moon. The Ku<207><195>alin<200> which is fine like the thread in the ç
lotus stalk, is inside this su<218>umn<193> and is shining like millions ç
of lightnings. By closing the ears and meditating on the sound within ç
and the blue light within, between the eyes, and witnessing it, one ç
gets infinite happiness. This is meditation on the `inside.'
The<|> Upani<218>ad<|> then <|>proceeds <|>to describe the process of ç
meditation on two points, `outside' and `in between' the `inside' ç
and the `outside.' The first consists in fixing the gaze and the mind ç
at any point in front of the nose, 4, 6, 8, 10 or 12 a<209>gulas (an ç
a<209>gula is roughly about an inch) in distance, seeing it as of ç
blue-yellow colour. The latter consists of meditating on the `<193>k<193>·a' ç
or ether/space, near the tip of the nose but beyond it, and as being ç
bright like the full sun of the morning or fire with leaping tongues. ç
In both cases this light becomes a symbol for Brahman.
Then comes the description of `t<193>rakayoga,' meditation on the ç
light in the head, by reversing the mental light into the area between ç
the eye brows, inside the head but towards the crown. Such meditation ç
can give the supernatural `a<218><219>asiddhis' or `eight powers.'
Last comes the <185><193>mbhav<200>mudr<193>. Itis the same as meditation ç
already described, but, with the eyes without being closed or opened.
The Upani<218>ad ends with a description of the qualifications of ç
the guru fit to teach such yoga.
See also <MS><185>°MBHAV®MUDR°<D> and <MS>UPA-NI<186>ADS<D>.
@NT = °gaman<200>
@N1 = (`welcome' [songs])
<185>r<200> Durg<193>p<220>j<193> is one of the major festivals of ç
the Hindus celebrated on a grand scale in Bengal, Orissa, Bihar andAssam. ç
Beautiful clay images are ceremonially installed during the period ç
of nine days (1st to 9th in the month of °·vina, ·uklapak<218>a or ç
bright half) (October) and elaborate worship performed. `°gaman<200>' ç
is the name given to a particular type of songs generally sung on ç
this occasion as part of the `K<193>l<200>k<200>rtan' programmes.
<185>r<200> Durg<193> is actually P<193>rvat<200> or Um<193>, the ç
beloved daughter of queen Men<193> and king Girir<193>ja (the king ç
of Him<193>layas), given in marriage to Lord <185>iva. It is long ç
since the daughter has visited the house of her parents. The parents, ç
especially the mother Men<193>, are anxious about her welfare since ç
rumours have reached their ears that their daughter is languishing ç
in her husband's house owing to his poverty and queer ways of life. ç
The °gaman<200> songs depict their concern and anxiety for their daughter ç
and anger towards their son-in-law. They are full of tenderness of ç
the mother's love for the daughter. Solicitude for the welfare of ç
Um<193>, disgust with <185>iva's way of life<192>especially his living ç
in the cremation grounds, besmearing his body with ashes and begging ç
his food<192>consequent anger expressing itself in a resolve not to ç
send her back to her husband's house and even a grim determination ç
to fight a wordy duel with him if he presses for her return<192>these ç
are some of the sentiments frequently found in these songs. R<193>mpras<193>d, ç
Kamal<193>k<193>nta and D<193>·arathi are some of the well-known mystic ç
poets who have composed these songs.
@NT = °gam<193>nta <185>aivism
See <MS>P°<185>UPATA DAR<185>ANA<D>.
@NT = <193>gamas
@N1 = (`sacred books which teach the Truth from all aspects')
°gamas are a certain class of Hindu religious literature which practically ç
form the basis of Hindu religious practices of thepost-Vedic era. ç
Literally, the word means `that which teaches Truth from all aspects,' ç
<193> samant<193>t gamayati, and hence can denote the Vedas, or ç
for that matter, any sacred book. But in practice it is used in a ç
more restricted sense to indicate the above-mentioned class of literature.
Though the <193>gamas are definitely post-Vedic since they deal elaborately ç
with the deities <185>iva, <185>akti and Vi<218><207>u, their temples ç
and rituals, it is rather difficult to fix their chronological origin ç
and development. It can be definitely stated that some of the <193>gamas ç
devoted to the cult of Vi<218><207>u were already in existence by ç
the time of the Mah<193>bh<193>rata. The development of various ç
<193>gamas might have continued till the 8th cent. <F51320P10MSC1>A. D.<W1>
A typical <193>gama is generally divided into four parts known as ç
`p<193>das.' In the Vidy<193>p<193>da or J<210><193>nap<193>da philosophical ç
and metaphysical subjects are discussed. In the Yogap<193>da details ç
of yogic practices required to purify the body and mind are given. ç
In the Kriy<193>p<193>da, which is usually voluminous,  temple  architecture  and ç
iconography are dealt with. In the Cary<193>p<193>da, the details ç
of spiritual sacraments as also the code of conduct expected of a ç
novice are delineated.
@SPACE1 = 
According to the deity propitiated, the <193>gamas are divided into ç
three broad groups: <185>aiv<193>gamas, <185><193>kt<193>gamas and ç
Vai<218><207>av<193>gamas. The twenty eight °gamas starting with K<193>mik<193>gama ç
and ending with V<193>tul<193>gama comprise the <185>aiv<193>- gamas. ç
<|>According <|>to <|>them,<|> <185>iva<|> the Supreme God is `pati' (the ç
Lord), the j<200>vas or individual souls are `pa·u' (animal in bondage) ç
and the three kinds of malas or impurities (<193><207>avamala, k<193>rmikamala ç
and m<193>y<193>mala) comprise the `p<193>·a' (rope) by which the ç
j<200>vas are bound. It is by the grace of <185>iva, the Pa·upati, ç
that the pa·us are able to getrid of their p<193>·as and get mok<218>a ç
or liberation.
The <185><193>kt<193>gamas, also known as tantras, are legion in number. ç
They follow the <185>aiv<193>gamas very closely, the only exception ç
being that <185>akti or Dev<200> (Power or consort of <185>iva) gets ç
the supreme place. The t<193>ntric discipline has become divided into ç
dak<218>i<207><193>c<193>ra (the right-hand path), also known as `samaya,' ç
and v<193>m<193>c<193>ra (the left-hand path), also called `kaula.' ç
The former conforms to the decent and accepted norms of spiritual ç
practice whereas the latter seems to advocate the theory that even ç
aberrations can be sublimated to the level of the spiritual practice ç
resulting in the experience of the same supreme Truth.
The Vai<218><207>av<193>gamas, also called Sa<221>hit<193>s, are divided ç
into the Vaikh<193>nasa and the P<193><210>car<193>tra schools. ç
Both teach that Vi<218><207>u is the highest Truth and stress the ç
importance of worship in temples.
Jainism also has its <193>gamas written in the Ardham<193>gadhi language, ç
and is divided into two: <185>rut<193><209>gas and Up<193><209>gas.
See also <MS>DAK<186>IØ°C°RA, KAULA-M°RGA, P°<178>CAR°TR°GAMAS,  <185>AIV°GAMAS,  <185>°KT°- ç
GAMAS, SAMAYAMATA, TANTRAS, VAIKH°-NAS°GAMA <D>and<MS> V°M°C°RA<D>.
@NT = <193>g<193>m<200>-karma
@N1 = (`the future karma')
Belief in karma and punarjanma (reincarnation) is one of the fundamental ç
dogmas of Hinduism, Jainism, Buddhism and Sikhism. Karma or action, ç
good or bad, must have its effect. °g<193>m<200>-karma is the karma ç
that is being done now or that will be done in future (before death) ç
which will produce its results later.
For details see <MS>KARMA<D>.
@NT = Agastya
@N1 = (`One who stunted the growth of the mountain Vindhya')
Agastya is one of the most famous <216><218>is(sages or seers) frequently ç
met with in Hindu religious lore. He is the seer of several <184>gvedic ç
mantras (<184>gveda Sa<221>hit<193> 1.166 to 191). He is a brahmar<218>i, ç
the sonof Pulastya and Havirbhuk. Sage Agnive·ya is his disciple.
@SPACE = 
@SPACE = 
@SPACE = 
According to another version he was the son of Mitra and Varu<207>a, ç
and was born in a kumbha or jar. Hence the names Kumbhaja, Kumbhodbhava, ç
Kala·<200>suta and so on. Vasi<218><219>ha was his brother. He married ç
Lop<193>mudr<193> (also known as K<193>ver<200>), the princess of ç
Vidarbha and begot a son D<216><195>h<193>sya, also known as Idhmav<193>ha. ç
A man of vast knowledge and severe austerity he is said to have destroyed ç
the demons Ilvala and V<193>t<193>pi, stunted  the  growth  of  the  Vindhya ç
mountain which was growing recklessly, obstructing the light of the ç
sun, drunk the waters of the ocean to expose the demons K<193>lakeyas ç
who were killed by the gods, to have been honoured by R<193>ma when ç
he was living in the Da<207><195>ak<193>ra<207>ya and to whom he gave ç
divine weapons and also taught the °dityah<216>daya-hymn later and ç
brought about reconciliation between Indra and the Maruts.
@SPACE1 = 
Though Agastya is not enumerated among the Saptar<218>is (the seven ç
great sages), he is included among the progenitors of `gotra' geneology. ç
He has been accorded a stellar status and identified with Canopus, ç
the brightest star in the sky of southern India.
In the annals of Tamil religious lore and literature, Agastya is the ç
accredited originator of the Tamil language, the author of the maiden ç
grammar of that language and the first president of the first organization ç
of Tamil litterateurs. He is also credited with the authorship of ç
several works on medicine, mysticism and magic. One work called Agastya ç
Sa<221>hit<193> which deals with ritualistic worship is available. ç
It is part of P<193><210>car<193>tra literature. He is said to have ç
visited several South East Asian countries like Borneo, Siam and Cambodia.
The word `Agastya' might have been a title. Several Agastyas may have ç
been involved in these stories, syncretised into one.
An Agasty<193>·rama, a hermitage of Agastya, has been mentioned in ç
the R<193>m<193>ya<207>a. <|>This <|>has <|>been<|> sometimes identified ç
with Agastyapur<200>, east of Nasik in Maharashtra state.
The Vanaparva of Mah<193>bh<193>rata (88.13) mentions an Agastyat<200>rtha ç
in the P<193><207><195>ya country as an important place of pilgrimage.
Seeing the star Agastya or Canopus when the sun is in the middle of ç
Kany<193> or Virgo and worshipping him at night is mentioned as a ç
vrata (religious rite).
See also <MS>°DITYAH<184>DAYA, GOTRA and LOP°MUDR°<D>.
@NT = aghamar<218>a<207>a
@N1 = (`destroyer of sins')
Every religion has its rituals. We have plenty of them in Hinduism. ç
Sandhy<193> or sandhy<193>karma or sandhy<193>vandana is a fundamental ç
Vedic ritual obligatory on all the dvijas (the `twice born,' viz., ç
the br<193>hma<207>as, the k<218>attriyas and the vai·yas). It is ç
essentially an up<193>san<193> (meditation, spiritual practice) and ç
has several steps designed to elevate the mind to levels of meditation ç
and mysticism. Aghamar<218>a<207>a is one such step in the process. ç
It consists of taking a few drops of water in the right hand shaped ç
like the gokar<207>a (the ear of a cow), holding it near the nose ç
and breathing out from the nose on the water (with the idea of driving ç
away sin from oneself) to the accompaniment of the three <184>gvedic ç
verses beginning with `<216>ta<221> ca' (vide <184>gveda Sa<221>hit<193> ç
10.190. 1-3), and throwing away the water to one's left on the ground. ç
Though the subject matter of these mantras is creation and the Creator, ç
the mantras themselves are reputed to be `aghamar<218>ana' or sin-effacing. ç
These mantras can also be repeated during bath and as an expiation ç
of sins.
The mantras beginning with `hira<207>ya-·<216><209>ga<221> varu<207>a<221> ç
prapadye' and ending with `<193>kr<193>ntsamudra<199>' which form ç
part of the Mah<193>n<193>r<193>ya<207>a Upani<218>ad (55-70) are ç
known as Aghamar<218>a<207>as<220>kta. The three <216>ks of the ç
aghamar<218>a<207>a ritual (`<216>ta<221> ca') are also included in ç
this. This Aghamar<218>a<207>as<220>kta is normally recited while ç
taking bath in ponds or rivers. It is accredited with the power of ç
destroying all sins, whether ordinary ones like the one incurred by ç
eating the food given by evil ones or heinous ones like committing ç
adultery and murder of the embryo.
@NT = Aghamar<218>a<207>as<220>kta
@N1 = (`the  hymn  that destroys sins')
It is natural for human beings to commit sins, either knowingly or ç
unknowingly. Very often they realise their mistakes and even repent ç
for them. As knowers of human psychology, the <216><218>is (sages) ç
of yore have prescribed certain religio-spiritual rituals that help ç
in the eradication of sins.
The Aghamar<218>a<207>as<220>kta is one such Vedic hymn (of prayer) ç
prescribed for this purpose.
It forms an integral part of the Mah<193>n<193>r<193>ya<207>a Upani<218>ad ç
(Anuv<193>ka 1, mantras 55-70).
Water is a great purifying agent and should therefore be considered ç
as an aspect of the Divine. Varu<207>a is the presiding deity of water.
This s<220>kta has to be chanted before taking bath in a river or ç
lake or tank.
The gist of the whole s<220>kta can be stated as follows:
I take refuge in Varu<207>a. Pardon me for having accepted gifts from ç
unworthy persons.
May Indra, Varu<207>a, B<216>haspati and Savit<193> destroy the sins ç
committed by me. My salutations to them.
Through the power of this mantra, let all the impurities in this water ç
(where I am to bathe now) be destroyed. May Varu<207>a purify me.
I invite the seven sacred rivers† Ga<209>g<193>, <|>Yamun<193>, <|>Sarasvat<200>,<|> ç
God<193>var<200>, Narmad<193>,  Sindh<220>  and  Kaver<200>†to  be ç
present here in this water.
May Varu<207>a, capable of effacing all sins, purify all the beings ç
dwelling on the earth, in the atmospheric region and in heaven. Similarly ç
may the Vasus also purify us.
I am the Supreme Light which projected itself as the universe. I am ç
the same light that shines as the inmost essence of all that exists.
Varu<207>a, the regent of waters and effacer of sins, absolves the ç
sinners of all types.
Though I am the ground of sins and am made to weep, wise men can favour ç
me by destroying my sins.
The Supreme Lord is infinite like the limitless ocean. He dwells in ç
the hearts of devotees. He delights the individual souls by guiding ç
them and offering the fruits of their action.
@SPACE = 
@NT = Aghamar<218>a<207>a-vrata
@N1 = (`a religious rite [prescribed for] destroying sins')
No man, however careful, can avoid sins of omission and commission ç
in life. Recognizing this fact, the Hindu dharma-·<193>stras have ç
provided for pr<193>ya·cittas (expiations) by performing which, these ç
sins can be obviated, or at least, their effects can be minimised. ç
Aghamar<218>a<207>a-vrata is such a pr<193>ya·citta prescribed by ç
even the most ancient dharma·<193>stra works like those of Gautama, ç
Baudh<193>yana, Manu and Y<193>j<210>avalkya, as an omnibus penance ç
for all types of sins.
The person performing it must fast for three days, recite the Aghamar<218>a<207>a-s<220>kta ç
three times every day at the time of bath, standing in the water of ç
a river or tank or pond, spend the days standing and nights, sitting. ç
At the end of the vrata he should gift a milch-cow. This penance is ç
said to be equal in sanctification to the avabh<216>thasn<193>na (ceremonial ç
bath) taken at the end of an A·vamedha sacrifice.
See also <MS>AGHAMAR<186>AØAS<188>KTA<D> (under <MS>AGHAMAR<186>AØA), ç
P°PA<D> and<MS> PR°YA<185>CITTA<D>.
@SPACE = 
@NT = aghodaka
@N1 = (`water libation during the<R>ç
period of impurity')
Belief in the survival of the soul after death and the need to bring ç
peace to the soul in a spirit body through appropriate obsequial rites ç
are common to many religions. Hinduism goes to the extent of considering ç
antye<218><219>i or death-rites to be performed immediately after ç
the death of a person, a `sa<221>sk<193>ra,' a rite that purifies ç
and uplifts the soul. As part of this ceremony, water libation (udaka) ç
is offered for the benefit of the deceased during the period of ceremonial ç
impurity (agha). There are differences of opinion among the dharma·<193>stra ç
writers with regard to thenumber and duration of these water libations.
A near relative (called sapi<207><195>a) of the deceased, should take ç
water mixed with sesame in the a<210>jali (joined palms) and offer ç
it facing south, with appropriate mantras. It should be offered thrice ç
a day for eleven days from the day of death.
`Udakakriy<193>' and `udakad<193>na' are the other names used for ç
this rite.
See also <MS>ANTYE<186><187>I<D>.
@SPACE = 
@NT = Aghora
@N1 = (`not terrible')
<185>iva is a deity of the Hindu Trinity and is responsible for the ç
laya or pralaya, dissolution, of the universe. One of the names, by ç
which he is well-known, is Pa<210>c<193>nana or Pa<210>camukha, `the ç
five faced one'. These five faces are actually five aspects of his ç
manifestation. `Aghora' is one of these five. Facing south and rulingover ç
the element agni (fire), Aghora stands for the power that absorbs ç
and renovates the universe.
Iconographically, he is shown with a terrific face and eight hands ç
holding ·<220>la (spear), <195>amaru (drum), p<193>·a (noose), kap<193>la ç
(skull-cup), da<207><195>a (staff), c<193>pa (bow), b<193><207>a (arrow) ç
and asi (sword). The neck is blue and the rest of the body is black. ç
The body is either naked or clad in the hides of elephant and lion. ç
Snakes and scorpions form the ornaments.
Since his terrible form frightens away all the sufferings of his devotees, ç
who have taken refuge in him, he is `Aghora,' the `not terrible' to ç
them.
The mantra beginning with the words `aghorebhyo' in the Mah<193>n<193>r<193>ya<207>a ç
Upani<218>ad (19.1) is known as `aghora- mantra' and is one of the ç
five mantras well-known  as  `pa<210>cabrahma-mantras' employed in ç
the worship and meditation of Mah<193>deva <185>iva visualised as ç
having five faces.
These mantras are normally prescribed for japa to a person who desires ç
divine illumination.
@NT = Aghora-panth<200>
@N1 = (`a follower of Aghori school [of <185>aivism]')
Aghorapanthis are the ascetics of a queer <185>aiva order, who worship ç
<185>iva as `aghora' (`the non-terrible'). The origin of this sect ç
which revels in abominable practices like cannibalism, eating from ç
a human skull, besmearing with ashes from funeral pyres and a generous ç
helping of spirituous liquors, is rather obscure. May be, they represent ç
the remnants of some aboriginal non-°ryan religious cults which were ç
absorbed into Hinduism in course of time. The few surviving members ç
of the sect are to be found mostly in Bihar, Bengal, Rajasthan and ç
Assam. Owing to the natural abhorrence of people towards such  sects,  their  number  has  fast ç
dwindled.
See also <MS>K°P°LIKAS<D>.
@NT = Aghora <185>iv<193>c<193>rya
<185>aivism is a very ancient branch of Hindu religion. Rooted in ç
the Vedas and <193>gamas, it has been developed into a formidable ç
religio-philosophical system by a galaxy of mystics and writers. An ç
important teacher often quoted especially by the V<200>ra·aiva writers ç
is Aghora <185>iv<193>c<193>rya, a pontiff of the °mardaka monastery ç
at Cidambaram (Tamil Nadu) who probably lived in the 11th-12th cent. ç
<MS>A.<|>D.<D> Tattva-prak<193>·a of king Bhoja of Dh<193>r<193> ç
is said to be a fundamental work on <185>aivism.Aghora <185>iv<193>c<193>rya ç
is reputed to have written a detailed commentary on this work, refuting ç
the highly monistic interpretations of an earlier commentator <185>r<200>kum<193>ra. ç
Another work usually attribu-ted to him is M<216>gendr<193>gama-v<216>tti-dipik<193>, ç
a commentary on the famous <185>aiv<193>gama, M<216>gendr<193>gama. ç
He is credited with the authorship of several other works also like ç
Aghora-·ivapaddhati, Tattvasa<209>graha, Mahotsavanidhi and so on.
@NT = agnaukara<207>a
@N1 = (`making one with fire')
P<193>rva<207>a·r<193>ddha is an important rite performed during `parvans' ç
i.e., am<193>v<193>sy<193>s or new moon days with a view to propitiating ç
the departed forefathers, up to the third generation. On such days, ç
worthy br<193>hma<207>as are invited for dinner. A portion of the ç
food prepared for the same is taken out in a vessel and seven <193>hutis ç
or libations are cast into the homa fire with seven appropriate mantras. ç
Two offerings each are made for the father, the grand-father and the ç
great-grand- father and one for all the other pit<216>s (forefathers) ç
combined. This rite is known as agnaukara<207>a.
See  also  <MS>P°RVAØA<185>R°DDHA<D>  and<MS> <185>R°DDHA<D>.
@NT = <193>gneya-k<216>cchra
@N1-1 = (`k<216>cchra connected with Agni')
Sins of omission and commission are inevitable in the life of a man ç
however careful he may be. The law of karma being inexorable he is ç
obliged to suffer their consequences. But none wants to suffer, and ç
if given the chance to escape, will try for the same. With the full ç
understanding of human nature and with a view to giving a chance for ç
redemption to those who genuinely repent, the Hindu dharma-·<193>stras ç
have devised elaborate pr<193>ya·cittas or expiations for sins. K<216>cchra<192>literally ç
`that which causes suffering'†is a general word used for several penances ç
out of which <193>gneya-k<216>cchra is a variety. The main part of ç
the discipline in this expiation is that the person performing it ç
should subsist only on sesame (tila) for twelve days. Agni will be ç
pleased by it and all the difficulties of the performer will be removed.
@NT = <193>gney<200>-dh<193>ra<207><193>
@N1 = (`fixing the mind on the fire principle')
Conquest of self gives mastery over the whole world. Conquest of the ç
mind leads to the conquest of the self. Works on yoga portray the ç
various age-old techniques for controlling the mind. Pa<210>ca-dh<193>ra<207><193>s, ç
five kinds of fixing the mind on prescribed subtle principles, is ç
one such method described in a well-known work on Ha<219>hayoga viz., ç
Ghera<207><195>a Sa<221>hit<193>.
The fire principle is situated at the navel, in the form of a red ç
effulgent triangle. Its presiding deity is Rudra. Fixing the pr<193><207>a ç
along with the mind on this fire principle at the navel for a period ç
of five gha<219>is (i.e., 2 hours) is known as `<193>gney<200>-dh<193>ra<207><193>.' ç
Destruction of the fear of death is the result achieved.
@NT = Agni
@N1 = (`fire')
According to the Hindu scriptures, every elemental force is presided ç
over by a deity. The presiding deity of tejas, fire and heat, is Agni.
The religion of the Vedas being mainly centred round sacrificial rites, ç
Agni the god of fire naturally gets the pride of place in the Vedic ç
hymns. A large number of them are devoted to describing and praising ç
him. He is often eulogised as the Supreme God, the creator, the sustainer ç
and the all-pervading cosmic spirit. All the other gods are his different ç
manifestations. He manifests himself as fire (agni) on this earth, ç
as lightning and air (Indra and V<193>yu) in the sky and as the sun ç
(S<220>rya) in the heavens. He acts as a mediator <|>between<|> men<|> ç
and <|>gods<|> by carrying the sacrificial offerings of men to gods. ç
He is all-knowing and all-powerful. He is all-merciful too. Though ç
an immortal he lives among the mortals, in every house. He protects ç
them by dispelling their difficulties and fulfils their wishes. Without ç
him, the world can never sustain itself.
@SPACE1 = 
@SPACE = 
In the epics and the pur<193><207>as he is said to have been born ç
out of the face of the Vir<193><219> Puru<218>a (Cosmic Being), married ç
Sv<193>h<193>, the daughter of Dak<218>a, consumed the Kh<193><207><195>ava ç
forest with the help of Arjuna whom he rewarded with gifts of divine ç
weapons like the bow G<193><207><195><200>va, helped Indra to be relieved ç
of a part ofhis sin of brahmahaty<193> (killing a br<193>hma<207>a) ç
and restored S<200>t<193> to R<193>ma after she had entered the fire ç
to prove her chastity.
Iconographically, Agni is represented as an old man with a red body. ç
He has two heads, a big belly and six eyes, seven arms in which he ç
holds objects like the spoon, ladle, fan etc., seven tongues, four ç
horns and three legs. He has braided hair, wears red garments as also ç
the yaj<210>opa-v<200>ta (sacred thread). He is attended on either ç
side by his two consorts, Sv<193>h<193> and Svadh<193>. The smoke ç
is his banner and the ram his mount. Obviously this is an anthropomorphic ç
representation of the sacrificial fire.
As sacrificial fire, Agni has five aspects known as Pa<210>c<193>gni: ç
g<193>rhapatya, <193>havan<200>ya, dak<218>i<207><193> (or anv<193>h<193>ryapacana), ç
sabhya and <193>vasathya.
See also <MS>PA<178>C°GNI<D>.
@NT = agnicayana
@N1 = (`piling the fire')
According to the ancient Hindu reli-gious texts like the Bhagavadg<200>t<193> ç
(3.10, 11) Praj<193>pati (the Creator) gave the yaj<210>a (system ç
of sacrifices) as the link between the human beings and the deities ç
(devas) of the cosmic regions. Human beings were advised to propitiate ç
these deities through various yaj<210>as and the deities in turn would ç
respond by bestowing upon them their needs.
Vedic sacrifices which were simple fire rituals during the Sa<221>hit<193> ç
period were gradually developed, by the period of the Br<193>hma<207>as, ç
into a bewildering variety of rites and ceremonies with a labyrinth ç
of details. One of the complicated sacrifices is the Somay<193>ga ç
of which agnicayana forms an integral part. However this rite is not ç
compulsory even in Somay<193>ga. <|>Literally<|> the <|>word<|> means ç
`piling the fire' but in practice it refers to the rite of building ç
up the altar on which the sacrificial fire (<193>havan<200>ya) will ç
be lighted.
The <185>atapatha Br<193>hma<207>a (k<193><207><195>as 6 to 10) ç
of the <185>ukla Yajurveda, which is the basic authority on this ç
rite, represents it as a human imitation of the construction of the ç
cosmic world of Praj<193>pati.
Detailed instructions are given for the manufacture of the various ç
kinds of bricks, of different shapes and sizes, and for the building ç
up of the altar in several layers and of prescribed shapes. The most ç
common shapes are those of supar<207>a (eagle), ·yena (hawk) and dro<207>a ç
(trough). As many as 10,800 bricks are needed to complete the construction ç
of the altar. Athorough knowledge of geometry is necessary on the ç
part of the priests who guide and direct the construction. The bricks ç
are usually laid in five layers, the 1st, the 3rd and the 5th being ç
of the samepattern while the 2nd and 4th are different.
Measuring the ground on which the altar is built, ploughing and sowing ç
it with several seeds, interring the heads of five animals or their ç
golden images and the golden image of the sacrificer as also a living ç
tortoise into the altar that is being built are some of the details ç
mentioned in the liturgical works.
The piling of the altar could be completed in one year (8 months for ç
the first four layers and 4 months for the last) or only in five consecutive ç
days.
@SPACE1 = 
The `Agnicit,' i.e., the person who performs<|> agnicayana,<|> is<|> ç
expected<|> to observe certain vows during this period. He is permitted ç
to do `puna·citi' (doing agnicayana once again) if he does not prosper ç
in the year after performing it.
To obviate the effects of the sins of omission <|>and<|> commission<|> ç
during<|> the agnicayana  rite,  several  pr<193>ya·cittas (expiations) ç
are prescribed.
The esoteric doctrine of agnicayana is said to have originated with ç
Praj<193>pati himself and come down through a succession of teachers ç
from Tura K<193>va<218>eya to <185><193><207><195>ilya.
See  also  <MS>SOMAY°GA<D>  and  <MS>VEDIC SACRIFICES<D>.
@NT = <193>gn<200>dhra
@N1 = (`one who kindles the fire')
No Vedic sacrifice can be conducted without the help and guidance ç
of priests. Liturgical works on sacrifices enumerate four chief priests<192>hot<216>, ç
adhvaryu, udg<193>t<216> and brahm<193><192>each of whom is assisted ç
by a maximum of three more. °gn<200>dhra, also called <193>gn<200>dh, ç
is an important priest who is the assistant of brahm<193> but has ç
much to do with the adhvaryu also. As the very name indicates, he ç
is the person who lights the sacrificial fire and tends it. It is ç
also his responsibility to ensure its proper distribution  among  the  various  vedis ç
(altars). Apart from this, his chief function is to respond to the ç
<193>·rava<207>a-call of the adhvaryu with words such as `astu ·rau<218>a<219>.' ç
He is also given the duty of seeing that everything is in order before ç
invoking the deities. As an insignia of this authority, he holds the ç
wooden sword called sphya.
See also <MS><184>TVIKS<D>.
@NT = Agnihotra
@N1 = (`in which libations are poured into agni')
Yaj<210>a or sacrifice links the human beings with divine beings. ç
When these divinities or devat<193>s are propitiated through yaj<210>as, ç
they reward the performers with whatever they desire for (vide Bhagavadg<200>t<193> ç
3.10-12).
These yaj<210>as may be nitya (obligatory, performed daily), naimittika ç
(occasional) or k<193>mya (motivated). Again, depending upon the materials ç
used they may be classified as p<193>ka-yaj<210>a, havir- yaj<210>a ç
and somay<193>ga. If cooked food is offered in p<193>kayaj<210>a and ç
soma juice in somay<193>gas,  milk  and  ghee  are  the materials ç
normally used in haviryaj<210>a.
Agnihotra is one of the most common and important sacrifices which ç
is classed among the haviryaj<210>as and considered to be nitya.
It is performed more as a daily worship than for the fulfilment of ç
any specific desire. It should be started from the very evening of ç
the day on which agny<193>dh<193>na (establishing the Vedic fire ceremonially) ç
is done. It is obligatory to perform it daily till death or old-age ç
or sa<221>ny<193>sa. All the dvijas (the `twice-born,' the men of ç
the first three var<207>as) are entitled to its performance. It must ç
be done twice daily at dawn and dusk, along with the wife. Wife, son ç
or pupil can perform it on his behalf in emergencies.
The main part of the rite consists in heating and offering cow's milk ç
in a ladle into the g<193>rhapatya fire with appropriate mantras. ç
S<220>rya (sun) and Praj<193>pati are the deities to whom offerings ç
are made in morning and Agni and Praj<193>pati, in the evening.
@SPACE1 = 
Instead of with milk, the rite may be performed with gruel, cooked ç
rice, ghee or curds when specific fruits or results are desired for.
The performer of Agnihotra is obliged to rear a cow. The milk vessel ç
which must be an earthen pot with a straight brim is called `agnihotra-sth<193>l<200>' ç
and the ladle `agnihotrahava<207><200>.'
If and when the yajam<193>na (performer of the sacrifice) goes on ç
a pilgrimage along with his wife, he can carry the g<193>rhapatya ç
fire with him or can ceremonially put it out and perform punar<193>dh<193>na ç
(re-establishing the fire) on his return.
When he dies, the various wooden implements used by him for Agnihotra ç
should be kept on various parts of his body as prescribed and the ç
body cremated with the g<193>rhapatya fire.
See also <MS>HAVIRYAJ<178>A<D> and <MS>YAJ<178>A.<D>
@SPACE = 
@NT = agnik<218>etra
@N1 = (`site of fire)
In Vedic sacrifices called Somay<193>ga the adhvaryu (the chief and ç
active priest)builds a `mah<193>vedi' (`the great altar') on the ç
eastern side of which the agnik<218>etra, the site of fire, is constructed ç
in the form of a ·yena (hawk). Taking thesacrificer's height as the ç
measuring unit, the agnik<218>etra is to be 4 units in length and ç
3units in breadth. However, in certain cases like the A·vamedha sacrifice, ç
this size can be doubled or even trebled.
See also <MS>MAH°VEDI<D>.
@SPACE = 
@NT = agnipr<193>k<193>ra
@N1 = (`wall of fire')
Ritualistic worship gives a concrete shape to abstract philosophical ç
principles and basic convictions born out of them. Also, it elevates ç
the mind of the worshipper to higher levels of spiritual experience ç
and provides emotional satisfaction.
Several steps are prescribed in the process of worship. Some of these ç
are just preliminaries which help in preparing the mind of the worshipper. ç
`Agnipr<193>k<193>ra' is one such in which an imaginary wall of fire ç
is erected round the worshipper by drawing three lines in the air ç
about him with the right index finger or by sprinkling water all round. ç
This is done with the recital of mantras like `ra<221>' or `sahasr<193>ra ç
hu<221> pha<219>.' This wall of fire is believed to act like a fort ç
preventing evil spirits or passions from attacking the worshipper.
See also <MS>P<188>J°<D>.
@SPACE1 = 
@NT = Agnipur<193><207>a
@SPACE1 = 
Popular Hinduism is firmly based on the pur<193><207>as. They have ç
played an un- enviable part in preserving Hindu religion and culture, ç
especially among the masses. The original stuff of the pur<193><207>as ç
is as old as the Vedas though the extant pur<193><207>as are later ç
productions showing unmistakable signs of compilation, evolution or ç
even manipulation. Some scholars feel that the pur<193><207>as contain ç
much historical material also.
Pur<193><207>as are narratives of ancient events, `pur<193> bhava<221> ç
pur<193><207>am'. Though a pur<193><207>a is said to have pa<210>calak<218>a<207>as ç
(five characteristics) like the accounts of creation, dissolution, ç
and geneology of kings, rarely do the pur<193><207>as conform to this ç
pattern. They are practically encyclopaedic in character dealing with ç
every topic under the sun.
Tradition ascribes the authorship of all the pur<193><207>as to Vedavy<193>sa ç
and divides them into two groups of Mah<193>pur<193><207>as (thegreat ç
or the major ones) and the Upapur<193><207>as, (the small or the minor ç
ones) each containing 18 works. Agnipur<193><207>a is usually classed ç
as the eighth among the Mah<193>pur<193><207>as.
@SPACE1 = 
Whether the extant Agnipur<193><207>a, now available in print, is ç
the original or a pur<193><207>a by name Vahnipur<193><207>a (vahni ç
= agni) whose manuscript has been discovered, is the original, has ç
been a subject of scholarly disputation. Though scholars like Prof. ç
R. C. Hazra are inclined to accord the latter, the status of the genuine ç
or original pur<193><207>a, it has gone into oblivion for the obvious ç
reason that the former has met the needs of the people to a much greater ç
extent.
This Agnipur<193><207>a might have taken the present shape during ç
the period <F51320MS>A. D.<W1> 700-1100. It contains nearly 12,000 verses ç
spread over 383 chapters. It is obviously a Vai<218><207>ava work ç
of an all comprehensive character containing almost everything of ç
general interest.
The following are some of the topics dealt with in this work: incarnations ç
of God, creation, worship of Lord Vi<218><207>u and Agni, initiation, ç
methods of building a temple, characteristics of ·<193>lagr<193>ma ç
stones and their worship, consecration of the deity in a newly built ç
temple, greatness of places of pilgrimage and holy rivers like Ga<209>g<193>, ç
descriptions of the various worlds, amulets, mystic formulae, medicines, ç
duties of men of the various <193>·ramas (stages of life), expiations ç
for sins, descriptions of hells, sandhy<193> ritual and G<193>yatr<200>, ç
consecration of a king and his duties, characteristics of precious ç
stones, the science of archery, prosody, literature and greatness ç
of this pur<193><207>a.
See also <MS>PUR°ØAS<D>.
@NT = agnis<193>ra
@N1 = (`the essence of fire')
@SPACE = 
Works on Ha<219>hayoga like Ghera<207><195>a Sa<221>hit<193> describe ç
`<186>a<219>karmas' or six purifi- catory techniques for cleansing ç
the body. `Dhauti' the first of these is of four kinds: antardhauti, ç
dantadhauti, h<216>d-dhauti and m<220>la·odhana. Antardhauti, the ç
first of these is again of four varieties, viz., v<193>tas<193>ra, ç
v<193>ris<193>ra, v<193>hnis<193>ra or agnis<193>ra, and bahi<218>k<216>ta.
Agni or vahni represents the `fire' of the digestive system (often ç
called j<193><219>har<193>gni or vai·v<193>nar<193>gni), the capacity ç
of digestion and assimilation. The health and strength of the body ç
depends on the proper functioning of the digestive system. Agnis<193>ra-dhauti ç
is prescribed for the removal of functional disorders and even organic ç
defects of this system.
The process consists in `pressing the navel knot a hundred times against ç
the spinal cord' by breathing out and contracting the abdominal muscles. ç
This is said to result in the body acquiring a divine lustre and vital ç
energy.
As in all other Ha<219>hayogic exercises, this also should be practised ç
under the direct guidance of a guru.
See also <MS>DHAUTI <D>and<MS> <186>A<187>KARMAS<D>.
@SPACE = 
@NT = agn<200><218>oma-pra<207>ayana
@N1 = (`leading agni and soma')
Of all the Vedic sacrifices, Somay<193>ga is, perhaps, one of the ç
most complicated. A separate altar called mah<193>vedi is to be erected ç
for the conduct of the Soma groupof sacrifices. Since the yajam<193>na ç
or sacrificer has already a vih<193>ra (an old and permanent shed ç
containing the threefires g<193>rhapatya, <193>havan<200>ya and dak<218>i<207><193>gni), ç
the fire for the new sacrifices has to be carried from the vih<193>ra ç
to the mah<193>vedi. This is done as a part of the whole ritual.
Taking out the agni (fire) from the old <193>havan<200>ya in the vih<193>ra, ç
as also the soma stalks from which soma juice is to be extracted for ç
the Somay<193>ga in a ceremonial procession is called `agn<200><218>oma-pra<207>ayana.' ç
This is done on the day before the suty<193> (day of extraction of ç
soma juice). The adhvaryu carries the fire on clay, the yajam<193>na ç
and patn<200> along with their sons and grandsons following him, one ç
behind the other, in a long procession. Soma stalks as also all the ç
vessels needed in the sacrifice are brought in a cart and deposited ç
in their respective places. The fire is deposited and kindled in his ç
pit by the <193>gn<200>dhra priest.
See also <MS>AGNI<186><187>OMA<D> and<MS> SOMAY°GA<D>.
@SPACE = 
@SPACE = 
@NT = Agni<218><219>oma
@N1 = (`praise of Agni')
@SPACE = 
The system of sacrifices (yaj<210>as and y<193>gas) forms the link ç
between men and gods. Men propitiate gods through them and gods respond ç
by bestowing upon men what they want. This is the doctrine propounded ç
in the Hindu scriptures like the Bhagavadg<200>t<193> (3.10-12).
Somay<193>ga is a general name for those sacrifices in which libations ç
of the soma juice are offered in the duly consecrated fire. Agni<218><219>oma ç
is a typical Somay<193>ga, forming the prak<216>ti or model for other ç
Soma sacrifices. It is such an integral part of another well-known ç
sacrifice, Jyoti-<218><219>oma, that these two are often identified. ç
Literally the word `Agni<218><219>oma' means `praise of Agni' and ç
the rite derives its name from the hymns called stoma (a group of ç
three <216>ks) which are chanted in praise of Agni towards the end ç
of the rite.
On the first day, somaprav<193>kas or heralds of Soma sacrifice are ç
sent out to invite priests. Choosing the priests, d<200>k<218><193> ç
(initiatory rites) of the sacrificer including another small sacrifice ç
called D<200>k<218>a<207><200>y<193>-i<218><219>i and construction ç
of bamboo sheds are the other rites to be performed.
On  the  second  day  apart  from purchasing  the  soma  creepers  and ç
`welcoming' them ceremonially, two more rites called pravargya and ç
upasad are performed.  (For  details  see  <MS>PRAVARGYA<D> and <MS>UPASAD.<D>)
On the third day, pravargya and upasad rites are repeated followed ç
by the construction of mah<193>vedi and uttaravedi (altars for performing ç
the sacrifices).
On the fourth day, after once again performing pravargya and upasad ç
rites, fire is ceremonially transferred from theold and permanent ç
sacrificial shed to the new. This is known as agn<200><218>oma-pra<207>ayana. ç
(See<MS>AGN®<186>OMA-PRAØAYANA<D> for details.) An animal sacrifice ç
(pa·u-bandha) is also performed.
On the fifth and the last day called `suty<193>,' the soma juice is ç
extracted cere- monially three times and offered. The first called ç
pr<193>tassavana is done in the morning. The second, m<193>dhyandina-savana ç
is done at noon. At the end of this, sacrificial fees are distributed. ç
Soon after this, begins the third pressing called t<216>t<200>y<193>. ç
At the end of the sacrifice, all those directly involved  in  it  have  avabh<216>tha-sn<193>na ç
(ceremonial bath marking the conclusion of the sacrifice).
@SPACE1 = 
See also <MS>JYOTI<186><187>OMA<D>.
@NT = Agnive·a
See <MS>°YURVEDA<D> and <MS>CARAKA-SA<189>HIT°<D>.
@NT = agny<193>dh<193>na
@N1 = (`producing the fire')
During the Vedic period, the perfor-mance of sacrifices was very common. ç
It was believed that one could get whatever one  desired  through  the  appropriate ç
sacrifices. Only men belonging to the first three castes, viz., the ç
br<193>hma<207>as, the k<218>attriyas and the vai·yas, were eligible ç
for establishing the Vedic fires and performing these sacrifices. ç
Certain classes of ·<220>dras like the rathak<193>ras (carpenters) ç
were also considered eligible. Even such persons had to establish ç
the fires in a ceremonial way following the prescribed procedure. ç
One who established the fires came to be known as an <193>hit<193>gni.
Agny<193>dh<193>na, also known as agny<193>-dheya (or simply <193>dh<193>na ç
or <193>dheya) was this prescribed rite. Literally it means placing ç
of burning coals for the generation of the g<193>rhapatya fire.
Only a married adult could establish the Vedic fires. He could do ç
it on any day he felt the desire or had to do it only in certain seasons ç
and on certain astronomically suitable days, nak<218>atras or stars ç
or asterisms being the determining factor.
The actual rite was spread over two days though preparation of the ç
ara<207>is (pieces of wood used in producing fire by attrition) and ç
other implements would start much earlier.
The first day known as upavasatha is devoted by the yajam<193>na (sacrificer) ç
to preliminaries like choosing the priests (<216>tvigvara<207>a), ç
offering them madhuparka (For details see <MS>MADHUPARKA.<D>), preparing ç
the sacrificial ground, having a shave and so on. Preparation and ç
consumption of the brahmaudana (cooked rice meant for the priests) ç
is another rite, performed by the adhvaryu. (See <MS>ADHVARYU<D>.)
After the first night and just before dawn the next day, fire is produced ç
by the attrition of the two ara<207>is by the adhvaryu. Singing of ç
s<193>mans at this time by the udg<193>t<216> (priest of S<193>maveda) ç
is a special feature. G<193>rhapatya fire in the hearth meant for ç
it is the first to be set up. The <193>havan<200>ya fire is produced ç
from the g<193>rhapatya by the adhvaryu. The dak<218>i<207><193>gni ç
is set up by the priest <193>gn<200>dhra (one of the assistant priests) ç
(See <MS>°GN®DHRA<D> for details.) either directly by the attrition ç
of the ara<207>is or from the g<193>rhapatya.
Establishing of the other two fires, sabhya and <193>vasathya, is ç
optional.
After setting up the fires, various kinds of grains and fuel sticks ç
are offered to them.
See also <MS>PA<178>C°GNI<D>.
@NT = agny<193>dheya
@N1 = (`producing the fire')
See <MS>AGNY°DH°NA<D>.
@NT = agrah<193>ra
@N1 = (`grant given to br<193>hma<207>as')
Since the most ancient times br<193>hma<207>as<192>men of learning, ç
austerity and character<192>have commanded the respect of the Hindu ç
society. Kings used to vie with one another in granting land, cows ç
and wealth to them for their personal use. Villages or lands (parts ç
of villages) given to them for their maintenance have been known as ç
`agrah<193>ra.' People living in such agrah<193>ras were called `mah<193>janas.' ç
They were exempted by the kings from payment of taxes and also punishment ç
for lapses in behaviour unless they were of a serious nature like ç
treason, murder etc. The mah<193>janas themselves regulated the conduct ç
of the inhabitants of the agrah<193>ra.
Agrah<193>ras were intended to be centres of learning and the mah<193>janas ç
were expected to be models of conduct.
@NT = <193>grah<193>ya<207><200>
@N1 = (`related to agrah<193>ya<207>a')
The month M<193>rga·<200>r<218>a, the 9th month of the Hindu calendar ç
year (corres- ponding to November-December) is called Agrah<193>ya<207>a  (`beginning  of  the  year'). ç
According to the writings of the foreign travellers visiting this ç
country like Al Beruni (<F51320P10MSC1>A. D.<W1> 1030) and borne out by ç
the internal evidence in the <F255P255MIC255>Mah<193>bh<193>rata (Anu·<193>sanaparva  106.17-30)  the  year ç
began with M<193>rga·<200>r<218>a. Hence the name Agrah<193>ya<207>a. ç
The rite performed on the full-moon day of this month is called `<193>grah<193>ya<207><200>.'
An important part of this rite is pratyavaroha<207>a (`descending ç
again') signifying the ceremonial descent of the entire family from ç
a high cot or, couch which was being used from the month of <185>r<193>va<207>a ç
(corresponding to July-August) for fear ofsnakes. Hence this is sometimes ç
considered a part of the snake rite.
After uttering the prescribed mantras (which contain prayers to snakes ç
not to harm the family) and offering p<193>yasam (milk-rice pudding) ç
to them, the entire family comes down the high cot and sleeps on the ç
bed of straw or grass newly prepared.
On this occasion the house is usually replastered and painted, if ç
not renovated.
In some works pratyavaroha<207>a is mentioned as a separate rite to ç
be performed at the beginning of each of the six seasons.
@SPACE = 
@NT = °graya<207>a
@N1 = (`offering of first fruits')
It was a custom among the ancient Hindus to offer newly harvested ç
grains to the Vedic deities before consuming them. °graya<207>a is ç
an agricultural rite of the i<218><219>i type (See <MS>I<186><187>I<D> ç
for details.) which an <193>hit<193>gni (one who has ceremonially ç
established the Vedic fires) should perform, before making use of ç
the newly harvested grains. The rite was considered necessary only ç
with regard to vr<200>hi (rice), yava (barley) and ·y<193>m<193>ka ç
(a kind of yellow grain, Panicum frumentaceum) and not for other ç
grains, vegetables or fruits. Oblations of cooked food are offeredto ç
the deities like Indra and Agni. A lump of the cooked food should ç
be thrown on the top of the dwelling house. The sacrificer should ç
also eat a mouthful of the grain.
Even those who have not established the Vedic fires can perform °graya<207>a ç
in the aup<193>san<193>gni (domestic fire lighted at the time of marriage) ç
with an extra oblation to Agni-svi<218><219>ak<216>t.
This rite is also called Navayaj<210>a or Navasasye<218><219>i.
@SPACE = 
@NT = Ahaly<193>
Ahaly<193>, the wife of the sage Gautama and mother of another sage ç
<185>at<193>nanda, is<|> a well-known character in Hindu mythology. ç
She is said to have been born out of creator Brahm<193>'s mind as ç
the very personification of feminine grace and beauty and given in ç
marriage to the mahar<218>i Gautama. Infatuated by her beauty, Indra ç
the king of gods impersonated Gautama and seduced her. Consequently ç
she was cursed by the sage Gautama to remain invisible for a thousand ç
years sustaining herself only on air and wallowing in ash. She was ç
redeemed by R<193>ma, the son of Da·aratha and restored to Gautama.
Some works like the Adhy<193>tma R<193>m<193>ya<207>a say that she ç
was converted into a stone. This version seems to be more popular.
When Utta<209>ka (or Uda<209>ka), a disciple of Gautama, offered to ç
fulfil any of her desires as his gurudak<218>i<207><193> (fees due ç
to the preceptor) she asked for the ku<207><195>alas (ear-ornaments) ç
of queen Madayant<200> (wife of the king Saud<193>sa). Utta<209>ka ç
secured them <|>successfully, <|>though <|>with <|>great difficulty.
See also <MS>GAUTAMA<D>.
@NT = Ahaly<193>b<193><200> Ho<202>kar
@N1 = (<MS>A.<|>D.<D> 1735-1795)
One of the few Hindu rulers of the medieval period, who did much for ç
the protection of Hinduism and preservation of Hindu temples was Ahaly<193>b<193><200> ç
Ho<202>kar, the queen of Indore.
@SPACE = 
@SPACE = 
Though born in a poor family of farmers, she was married to Kha<207><195>e ç
R<193>o, the son of Mallh<193>r R<193>o Ho<202>kar of Indore. When ç
her husband died in a battle, she boldly took over the administration ç
in <MS>A.D.<D>1765 and ruled with great efficiency till her demise ç
in <MS>A.<|>D.<D> 1795. She was responsible for the protection of the ç
original <185>ivali<209>gas of Soman<193>tha and K<193>·<200> temples ç
by building separate temples for the same. She improved or renovated ç
many temples in North India and also built rest-houses for pilgrims ç
in the places of pilgrimage. The modern city of Indore owes its development ç
mainly to her.
@NT = aha<209>k<193>ra
@N1 = (`egoism')
Aha<209>k<193>ra is that which produces abhim<193>na, the sense of ç
`I' and `mine.' According to S<193><209>khyan metaphysics, a large ç
part of which is accepted by Ved<193>nta, aha<209>k<193>ra is the ç
principle of individuation that arises after mahat or buddhi in the ç
process of evolution from prak<216>ti (nature). It is regarded as ç
a substance since it is the material cause of other substances like ç
the mind or the sense-organs. Through its action the different puru<218>as ç
(individual selves) become endowed each with a separate mental background. ç
These puru<218>as identify themselves with the acts of prak<216>ti ç
through aha<209>k<193>ra.
At the individual level it makes the puru<218>a feel that he is receiving ç
the sensations through the senses and the mind, and deciding about ç
appropriate action, through the intellect.
At the cosmic level, the five senses of cognition (j<210><193>nendriyas), ç
the five organs of action (karmendriyas), the mind (manas) and the ç
five subtle elements like the earth (tanm<193>tras) are produced out ç
of aha<209>k<193>ra.
In some works of Ved<193>nta, aha<209>k<193>ra is considered as a ç
function of anta<199>kara<207>a (internal instrument or mind), responsible ç
for ego-sense and possessiveness.
Aha<209>k<193>ra as egoism or self-conceit is considered as a great ç
obstacle in spiritual life and the cultivation of humility is prescribed ç
as its antidote.
See also <MS>S°<177>KHYA DAR<185>ANA<D>.
@NT = <193>h<193>ra
@N1 = (`What is taken in,' `food')
@NT = <193>h<193>ra·uddhi
@N1 = (`purity of food')
Hindu scriptural works declare that there is a close relationship ç
between the body and the mind. In fact it is the mind, as the repository ç
of karma, that creates thefuture body since it survives the death ç
of the physical bodies till the attainment of mok<218>a (liberation). ç
Hence the body and the mind act and react on each other. In this context ç
<193>h<193>ra or food assumes great importance. The quality of food ç
affects the quality of mind. In fact the Ch<193>ndogya Upani<218>ad ç
(7.26.2) goes to the extent of declaring that purity of food leads ç
to purity of mind which results in the excellent retention in memory ç
of all that is heard and studied from the preceptor. The resultant ç
wisdom leads to freedom from all bonds.This is because the subtle ç
part of the food that is eaten sustains the mind whereas the gross ç
part of it nourishes the body.
°h<193>ra is classified into three groups:
@SPACE1 = 
s<193>ttvika, r<193>jasika and t<193>masika (vide Bhagavadg<200>t<193> ç
17.7-10). S<193>ttvika food contributes to longevity, health, strength ç
and happiness. R<193>jasika food generates passion leading to sorrow ç
and suffering. T<193>masika food produces dullness, indolence and ç
drownsiness.
The various scriptural works mention long lists of food articles coming ç
under these three categories.
There are regulations with regard to the quantity of food to be eaten ç
and elaborate rules regarding the time, place and also company in ç
which it should be taken.
Moderation in eating is always the rule. Hindu medical works recommend ç
that half the stomach should be filled with solid food and a quarter ç
with water leaving the rest of the space for the movement of air.
One is advised to avoid partaking of food before performing spiritual ç
practices. Solar and lunar eclipses are believed to have very adverse ç
effects on food and hence  one  should  not  eat  during eclipses.
Places to be avoided for eating include temples, public places, moving ç
animals and vehicles.
@SPACE1 = 
Impurity (do<218>a) can accrue to food on three counts: j<193>tido<218>a, ç
nimittado<218>a and <193>·rayado<218>a. Garlic or cabbage for instance, ç
is impure by its very species (j<193>ti) and hence must be avoided. ç
Nimittado<218>a comes by external impurities like dust or hair as ç
also an insanitary handling of food. This can be obviated by strictly ç
observing the rules of health and sanitation. Foods cooked, touched ç
or handled by persons of questionable character become contaminated ç
by their evil psychic vibrations which can be transmitted to those ç
who consume them. This type of impurity is called <193>·rayado<218>a, ç
do<218>a or defect arising as a result of <193>·raya or repository. ç
Offering the food to God before eating destroys this impurity.
