Taking its birth on the Indo-Tibetan border of Uttar Pradesh, it is ç
joined by Nand<193>kin<200> at Nandapray<193>ga, by Pi<207><195>ar ç
at Kar<207>apray<193>ga and Mand<193>kin<200> at Rudrapray<193>ga. ç
It joins Bh<193>g<200>rath<200> at Devapray<193>ga. Here-after the ç
rivers merged together go by the name Ga<209>g<193>. The famous Vi<218><207>u ç
temple at Badar<200>n<193>tha is situated on the bank of Alakanand<193>.
See also <MS>GA<177>G°<D>.
@NT = Alakhn<193>m<200>s
@N1 = (`those who take the name of the Unseen')
Vedic monasticism as expounded in the dharma·<193>stras was practically ç
reserved for the `dvijas' or the `twice-born,' members of the first ç
three castes. Spiritual aspiration, especially the desire for mok<218>a ç
or liberation, being common to all human beings, persons from outside ç
these three caste groups too have evolved their own way of monastic ç
life and monastic orders. One of the many such groups is the `Alakhn<193>m<200>s,' ç
also called `Alakhg<200>rs' and `Alakhiyas.' The word `alakh' is a ç
corrupted Hindi form of the Sanskrit word `alak<218>ya,' the `unseen.' ç
So, the `Alakhn<193>m<200>s' are those who take the name of the `Unseen,' ç
the Supreme Brahman. They believe only in God without form.
This sect is said to have been started by one L<193>l or L<193>lg<200>r, ç
a saint of the cam<193>r (shoemaker) caste. It is not known when he ç
lived.
Members of this sect are confined mostly to Bikanir in Rajasthan State. ç
They wear a long blanket coat and a conicalcap. While begging for ç
alms or greeting one another they cry out `Alakh kaho,' `Speak of ç
the Unseen.' They are gentle by nature and practise non-violence, ç
catholicity and purity. They do not recognize caste system and disfavour ç
visiting temples.
@NT = Alak<218>m<200>
@N1 = (`goddess of misfortune')
The created universe, having been projected out of God and sustained ç
by Him, is naturally identified with Him. Hence evil is as much God ç
as good is. It is another aspect, a reverse aspect as it were. This ç
is a bold assertion made by Hinduism.
If Lak<218>m<200> is the goddess of wealth beauty and splendour, Alak<218>m<200>, ç
her opposite number, is misfortune personified. According to mythological ç
accounts she was also born during samudramathana (`churning <|>of <|>the ç
<|>ocean').<|> Since <|>she appeared earlier than Lak<218>m<200>, she ç
is also called `Jye<218><219>h<193>' (the elder one). A sage Dussaha<|> ç
(`the <|>unbearable') <|>by <|>name, married her. According to another ç
version it was the sage Kapila. Adharma (unrighteousness) was their ç
offspring.
Alak<218>m<200> is usually shown as an old hag riding a donkey. She ç
has a broom in her hand. A crow adorns her banner. Her image finds ç
a place in some temples. When propitiated, she can dispel evil and ç
grant prosperity.
She is sometimes identified with Lak<218>m<200> herself.
Being a part and parcel of this creation and hence of our life, misfortune ç
is no less divinely ordained than fortune. It is perhaps to teach ç
this great fact of life that even misfortune is deified.
@NT = Alampur
Alampur is a village on the bank of the Tu<209>gabhadr<193> River ç
in the Mahaboobnagar district of Andhra Pradesh. The village is renowned ç
for the Nava-Brahm<193> temples (also known as Svarga-Brahm<193> temples) ç
built in the 7th century <F51320P10MSC1>A. D.<W1> Some of them are located ç
within the same pr<193>k<193>ra (outer wall). All are in the vesara ç
style, a combination of the n<193>gara and dr<193>vi<195>a styles, ç
though the former aspect is more prominent. They appear to be the ç
prototypes of the temples developed fullyat Aiho<202>e and B<193>d<193>mi ç
now situated in the Karnataka State.
Alampur has sometimes been called Dak<218>i<207>a K<193>·<200>.
See also <MS>AIHO<170>E, B°D°MI, DR°VI£A, N°GARA<D> and <MS>VESARA<D>.
@NT = °<202>and<200>
A small town of the Maharashtra State, about 23 kms. (15 miles) from ç
the city of Pune (Poona), it has acquired the status of a pilgrimage ç
centre by its association with the greatest saint of Maharashtra, ç
Sant J<210><193>ne·var or J<210><193>na-deva. The saint was born in ç
<F51320P10MSC1>A.<|>D.<W1> 1271 here; and again it was here that he gave ç
up the body in yoga in <F255P255MSC255>A. D<D>. 1296. Thousands of devotees ç
still believe that he lives in his subtle body in the cave where he ç
went into sam<193>dhi.
Every year, on the eleventh day of the dark half of K<193>rtt<200>ka ç
(November<192> December), the day on which J<210><193>ne·var is said ç
to have attained sam<193>dhi, there will be a huge congregation of ç
devotees here to get his blessings.
See also <MS>J<178>°NE<185>VARA<D>.
@NT = ala<209>k<193>ra
@N1 = (`embellishment')
The word, derived from the root `k<216>' (`to do') along with the ç
prefix `alam' (`enough', `sufficient') means something that makes ç
a thing more complete, a dress or an ornament. But it has acquired ç
a more technical sense in the field of Sanskrit literature, viz., ç
`figure of speech.' The science that deals with this subject has been ç
designated as `Ala<209>k<193>ra·<193>stra.'
See <MS>ALA<177>K°RA-<185>°STRA<D>.
@NT = Ala<209>k<193>ra-·<193>stra
@N1 = (`science of figure of speech')
The Sanskrit language and Sanskrit literature have become an inalienable ç
part of Hindu religion and culture. Even the earliest recorded specimens ç
of Sanskrit literature have manifested the art of graceful speech. ç
Several hymns of the <184>gveda may be looked upon as genuine specimens ç
of fine poetry. Various rhetorical devices now known as upam<193> ç
(simile), r<220>paka (metaphor) or ati·ayokti (hyperbole) find anapt ç
expression there in a natural way. The R<193>m<193>ya<207>a and ç
the Mah<193>bh<193>rata, though they are monumental works of wisdom ç
and imagination, are also works exhibiting rare poetical skill.
Ala<209>k<193>ra·<193>stra as a regular, independent, subject might ç
not have existedin more ancient times. The first systematization ç
started perhaps with the N<193><219>ya-·<193>stra of Bharata who ç
might have existed some time during the period 200 <F51320MS>B.C.<W1><192><MS>A.D.<W1> ç
400. Though primarily a work on dramaturgy, the origins of systematization ç
of poetics<|>as a science can be discovered here. However, it is Bh<193>maha ç
and Da<207><195>in (6th cent. <MS>A.D.<W1>), V<193>mana and Udbha<219>a ç
(8th cent. <MS>A.<|>D.<W1>), Rudra<219>a and °nandavardhana (9th<|>cent. ç
<MS>A.<|>D.<F255D>), Ab<F51320W1>hinavagupta, K<218>emendra and Mamma<219>a (11th ç
cent. <MS>A.<|>D.<W1>) that have enriched the literature on poetics ç
through their prolific writings of superb quality.
The subject of ala<209>k<193>ra was viewed from different angles by ç
different authors. This gave rise to eight samprad<193>yas or schools: ç
r<200>ti, gu<207>a, ala<209>k<193>ra, vakrokti, rasa, dhvani, anum<193>na ç
and aucitya.
R<200>ti is the way of writing. Though three r<200>tis were originally ç
recognized, they ultimately rose to six. The names given to them such ç
as Vaidarbh<200>, Gau<195><200> or M<193>gadh<200> suggest that they ç
were prevalent in particular regions. Da<207><195>in and V<193>mana ç
were the forerunners of this school.
Gu<207>a or quality may concern either the ·abda (word) or the artha ç
(meaning). It is very similar to the R<200>ti school. Originally enumerated ç
as three, it gradually rose to ten. However this school got merged ç
into the Ala<209>k<193>ra school. V<193>mana was the chief exponent ç
of this Gu<207>a school.
Ala<209>k<193>ra is literary embellishment. It may be of ·abda (word ç
or sound) or artha (sense). The ala<209>k<193>ras rose from 38 in ç
the early period to 200 in later days. Da<207><195>in and Bh<193>maha ç
were the main propagators of this school.
@SPACE1 = 
Vakrokti is equivocation. It is a mode of expression so that the listener ç
conceives of a meaning different from that intended by the speaker ç
or writer. Bh<193>maha and Kuntaka (11th cent. <F51320P10MSC1>A. D.<W1>) ç
were the chief advocates of this school.
Rasa is mood or sentiment, a genera- lized resultant emotion in the ç
spectator or reader. Nine rasas, often called `navarasas,' have been ç
advocated by the writers on prosody and dramatics. Bharata was the ç
earliest exponent of the Rasa school followed by Udbha<219>a and others.
Dhvani is suggestion. The theory ofdhvani was introduced by °nanda- ç
vardhana.
Anum<193>na refers to a sentiment that has to be inferred and experienced. ç
<185>a<209>kula (9th cent <F51320P10MSC1>A. D.<W1>) was the founder of this ç
school.
Aucitya means propriety. This school was propounded by K<218>emendra.
@IN2 = Bharata's N<193><219>ya·<193>stra,<R>ç
Bh<193>maha's K<193>vy<193>la<209>k<193>ra,<R>ç
Da<207><195>in's  K<193>vy<193>dar·a,<R>ç
Udbha<219>a's K<193>vy<193>la<209>k<193>ra-sa<209>graha, <R>ç
Rudra<219>a's K<193>vy<193>la<209>k<193>ra,<R>ç
°nandavardhana's Dhvany<193>loka and<R>ç
Mamma<219>a's K<193>vya-prak<193>·a
@NID = are some of the standard works of Ala<209>k<193>ra-·<193>stra.
@NT = <193>lasya
@N1 = (`lassitude')
°lasya or laziness is the worst enemy of man. When even material well-being ç
is blocked by it, how can the lazy one hope for spiritual progress? ç
That is why Pata<210>jali,the great teacher of Yoga, has listed it ç
as an antar<193>ya or obstacle in the path of yoga (vide Yogas<220>tras ç
1.30). Since it is caused by an excess of tamas (dark element among ç
the gu<207>as), it is to be overcome by rajas (activity) and sattva ç
(dynamic goodness).
Su·ruta, the great teacher of °yur-veda (Hindu system of medicine ç
and surgery), considers <193>lasya as a condition which<|> inclines ç
a man more towards pleasure and less towards work, though capable ç
(vide Su·ruta Sa<221>hit<193>, <185><193>r<200>rasth<193>na, 4.51).
@NT = al<193>ta·<193>nti
@N1 = (`stilling the firebrand')
When an al<193>ta or a firebrand is moved quickly in circles or in ç
any other way, it creates the illusion of circles or lines of fire. ç
When the movement is stopped, the illusions also disappear. They were ç
never produced by the firebrand in motion and hence never dissolve ç
back into it when at rest.
This is a typical example used by the Buddhist school known as Vij<210><193>nav<193>da ç
and successfully adopted by the famous Advaitin Gau<195>ap<193>da ç
(500 <F51320MS>A. D.<W1>). According to the Vij<210><193>nav<193>dins, vij<210><193>na ç
or mind, conjures up the external world which has no reality of its ç
own. The mind with a series of succession of ideas is the only reality. ç
The external world appears to be real even as the circle of fire appears ç
to be.
Gau<195>ap<193>da uses the same analogy to a different purpose. It ç
is consciousness (or <193>tman) that appears in manifold forms due ç
to m<193>y<193>. In reality these do not come out of it, nor do they ç
return to it, for they do not exist (vide M<193><207><195><220>kya ç
K<193>rik<193> on M<193><207><195><220>kya Upani<218>ad, 4.47-52). ç
The sole reality is the unchanging pure consciousness, ·uddha-vij<210>aptim<193>tra. ç
This section of his K<193>rik<193>s (the 4th) is named as Al<193>ta·<193>nti-prakara<207>a.
The analogy of al<193>tacakra (firebrand moved in circles) is pre-Buddhist ç
and is found in the Maitr<193>ya<207><200> Upani<218>ad 4.24.
@NT = alaukika-up<193>ya
@N1 = (`supernatural method or means')
Man entertains numerous desires. He can successfully fulfil only a ç
few of them by his own efforts through normal means. As long as the ç
unfulfilled desires fill his heart he cannot have peace. Here comes ç
the role of the ·ruti or the Vedas which prescribe certain specific ç
rituals to obtain specific objects of desire by divine grace.These ç
are the alaukika-up<193>yas or supernatural means, by resorting to ç
which he can satisfy his desires legitimately.
These include the <185>yena-y<193>ga or means for the destruction ç
of the enemy. But the use of these methods is forbidden by the ·ruti ç
itself and one has to be guided by its instructions. In this respect ç
·ruti is said to be like a light illuminating equally the path to ç
be chosen and the thorn to be avoided. The choice is left to the person ç
for whom guidance to choose properly has also been provided.
@NT = <193>laya-vij<210><193>na
@N1 = (`consciousness, the home of impression')
Is the external world perceived throughthe senses real or unreal? ç
If real, what is its nature? If unreal, what then, is the reality? ç
These are the questions often raised and discussed by the Indian philosophical ç
systems. The Vij<210><193>nav<193>da school of Buddhism (also called ç
the Yog<193>c<193>ra school) denies reality to the external world ç
and considers it as ideas or states of the internal vij<210><193>na ç
(consciousness or mind), which alone is real. This vij<210><193>na ç
is the <193>laya or abode of all impressions. Hence the name `<193>laya-vij<210><193>na.' ç
It is the potential mind similar to the <193>tman of other systems. ç
However it is considered not as an unchanging substance, but as a ç
stream of continuously changing states. Through proper culture it ç
can gradually stop the arising of the undesirable mental states and ç
develop into the ideal state of nirv<193><207>a (emancipation).
See also <MS>VIJ<178>°NAV°DA<D> and <MS>YOG°C°RA<D>.
@NT = <193>l<200><195>h<193>sana
Works on Hindu iconography describe several <193>sanas or postures ç
for the images. °l<200><195>h<193>sana is one of them. In this posture, ç
usually adopted in war or aggression, the left leg is bent at the ç
knee and the right leg straight but slanting at an angle to the back. ç
It is considered a standing posture.  Fierce  aspects  of  <185>iva  like ç
Andhak<193>sura-mardana-m<220>rti and of Vi<218><207>u like Narasi<221>ha ç
are shown in this posture.
@SPACE = 
@NT = ali<209>ga
@N1 = (`without sign')
The S<193><209>khya system of Indian Philo-sophy posits pradh<193>na ç
or prak<216>ti (nature, matrix of all created objects) as one of the ç
two fundamental realities, the other reality being puru<218>a (soul). ç
Ali<209>ga is one of the synonyms of this prak<216>ti. Etymologically ç
the word `li<209>ga' signifies a characte- ristic mark or an object ç
that dissolves back in its cause. `Ali<209>ga' therefore is that which ç
is the opposite of `li<209>ga'. Prak<216>ti or primordial nature with ç
its three constituent gu<207>as in a state of perfect equilibrium ç
is so subtle, that there is absolutely no manifest sign by which it ç
can be perceived. It can only be inferred. Hence it is called `avyakta' ç
(the unmanifest) and `ali<209>ga' (without characteristic signs). ç
Being the original cause and the substratum of dissolution of all ç
its products, it has no dissolution itself. Even in this sense it ç
is `ali<209>ga.'
For further details see <MS>PRADH°NA <D>and <MS>PRAK<184>TI.
See also <MS>S°NKHYADAR<185>ANA<D>.
The word is used in some of the Upani<218>ads (vide Ka<219>ha ç
6.8 and Maitr<193>ya<207><200> 6.31, 35; 7.2) to indicate °tman ç
or Brahman since the latter has no li<209>gas or signs by which it ç
can be perceived by the senses or even the mind.
@NT = Allama Prabhu
@SPACE = 
@SPACE = 
Allama Prabhu (12th cent. <F51320P10MSC1>A. D.<W1>) is perhaps the most ç
important leader of theV<200>ra·aiva (<185>aivism of Karnataka) Movement ç
along with Basave·vara. Born in Ba<202><202>ig<193>vi (in the Shimoga ç
dt. of Karna-taka) of the pious parents Niraha<209>k<193>ra and Suj<210><193>ni, ç
he showed extraordinary spiritual wisdom and maturity even as a child. ç
According to one biographer Harihara, he was married in his youth ç
to one K<193>malat<193>, but renounced the world when she died at ç
a young age. Another incident mentioned is his `conquest of M<193>y<193>,' ç
M<193>y<193> being a princess who fell in love with him. He successfully ç
resisted her advances and continued his onward spiritual journey. ç
It is perhaps this experience that is at the root of his vacana (lyrical ç
prose composition) `m<193>y<193> is not in woman, but in the eye that ç
beholds her.' His intense desire to get enlightenment took him to ç
a highlycompetent guru (spiritual teacher) Animi<218>ayya sitting ç
in a guh<193> (cave). It was by his grace that he was filled with ç
<185>iva-consciousness and bliss. Hence he has used the pen-name `Guhe·vara' ç
in his compositions.
He is said to have enlightened Gorakhn<193>th (another famous medieval ç
saint) and many ·iva·ara<207>as (V<200>ra·aiva saints) like Basava, ç
Siddhar<193>ma, Mukt<193>yakka, Akka Mah<193>dev<200>, Goggayya and ç
others.
His vacanas are a class by themselves and have successfully expressed ç
deep spiritual experiences through wonderful similes.
See also <MS>AKKAMAH°DEV®, LI<177>G°YATA<D> <MS>MOVEMENT<D> and <MS>V®RA<185>AIVISM<D>.
@NT = °<202>v<193>rs
@N1 = (`those who are immersed in the love of God')
<185>r<200>vai<218><207>avism, the religion, and Vi·i<218><219><193>dvaita ç
Ved<193>nta, its philosophy, are of hoary antiquity. If the philosophy ç
is traced to the Upani<218>ads, the religion is traced to Lord N<193>r<193>ya<207>a ç
Himself. However, that <185>r<200>vai<218><207>avism is basically ç
the Bh<193>gavata religion rooted in the Vai<218><207>avite scriptures ç
like the N<193>r<193>ya<207><200>ya section of the Mah<193>bh<193>rata, ç
Vi<218><207>upur<193><207>a, Bh<193>gavata and the P<193><210>car<193>tra ç
works is conceded. The °<202>v<193>rs are important, even pioneering, ç
leaders of this religious cult.
@EMERGENCY = Literally, the word `<193><202>v<193>r' means `one who ç
is immersed deeply' (in God). The <185>r<200>vai<218><207>ava tradition ç
recognizes twelve such °<202>v<193>rs. All of them belonged to Tamil ç
Nadu and lived during the Pallava period (7th to 9th cent. <F51320P10MSC1>A. ç
D.<W1>).
@EMERGENCY = The first three °<202>v<193>rs†Poygai, P<220>dam (Bh<220>ta) ç
and Pey†were contemporaries. Since they spent most of their time laughing ç
and singing, weeping or dancing, people considered them as spirits ç
or mad beings. The work Tiruvand<193>di, of 300 verses, is jointly ç
ascribed to them.
Tiruma<202>i·ai, the fourth was an abandoned child brought up by a ç
hunter couple. His two works N<193>nmukhan Tiruvand<193>di and Tiruccandaviruttam ç
are a fine combi-nation of devotional fervour as well as metaphysical ç
acumen.
@EMERGENCY = The next was Kula·ekhara, the king of Travancore, who ç
was never affected by wealth, pleasures or power but always lived ç
as a true servant of God. His exqui- site Sanskrit hymn, the Mukundam<193>l<193>, ç
is considered a rare combination of devotion and poetic beauty. Perum<193><202> ç
Tirumo<202>i is his other work (in Tamil).
Periy<193><202>v<193>r or Vi<218><207>ucitta, an orthodox br<193>hma<207>a ç
is the sixth in the series. A resident of <185>r<200>vi<202><202>iputt<220>r, ç
famous for its temple dedicated to child <185>r<200> K<216><218><207>a ç
(known as Va<219>apatra·<193>yin, `one who is lying on the Banyan ç
leaf<|>') he delighted in spending most of his time in gathering flowers ç
and preparing garlands for the Lord. He loved the Lord with a motherly ç
heart like Ya·od<193>. His famous work, the Tirupall<193><207><195>u, ç
gives a fine description of the Lord going in a procession. However, ç
the verses also contain prayers for the protec- tion of the Lord's ç
beauty! A study of the works of the °<202>v<193>rs (called N<193>l<193>yira ç
Prabandham) is invariably prefaced by Tirupall<193><207><195>u ç
and also concluded with it. Tirumo<202>i, the other work of Periy<193><202>v<193>r, ç
contains a good description of the childish pranks of Lord <185>r<200> ç
K<216><218><207>a as seen by mother Ya·od<193>.
°<207><195><193><202> (also known as God<193>dev<200>) the seventh, ç
was the adopted daughter of Periy<193><202>v<193>r. She is the only ç
woman among the °<202>v<193>rs. Tradition considers her as the avat<193>ra ç
(incarnation) of Lak<218>m<200> or Bh<220>dev<200>. Refusing to wed ç
any man, she led the life of a lover of the Lord, likethe gop<200>s ç
of V<216>nd<193>van. Her work Tirupp<193>vai consisting of 30 p<193>·uras ç
or verses is extremely popular among the <185>r<200>vai<218><207>a-vas. ç
Even today it is sung and discoursed upon regularly during the month ç
of Dhanu<218> (when the sun enters the Zodiacal sign of Sagittarius). ç
N<193>cciy<193>r Tirumo<202>i is her other work. She is said to ç
have disappeared into the image of Lord Ra<209>gan<193>tha at <185>r<200>ra<209>gam ç
(Tamil Nadu).
@SPACE1 = 
The eighth, To<207><195>ara<195>ippo<195>i °<202>v<193>r, is a glorious ç
example of a fallen soul redeemed by repentance and service to the ç
holy ones. Known as Vipran<193>r<193>ya<207>a, an orthodox br<193>hma<207>a ç
pu<207><195>it, he was enticed into evil ways of life by a courtesan. ç
When she deserted him he woke up to the great tragedy. By serving ç
the devotees of God and considering himself as the dust of their feet ç
(that is the meaning of the word `to<207><195>ara-a<195>i-ppo<195>i') ç
he gradually purified himself and rose to supreme heights of devotion. ç
Tirupa<202><202>iye<202>ucci and Tirum<193>lai are the works attributed ç
to him.
@SPACE1 = 
Tirupp<193><207>i, the ninth °<202>v<193>r, was a pariah who lived ç
in a hut near the <185>r<200>ra<209>gam temple. He was a musician ç
saint. It is said that Lord Ra<209>gan<193>tha commanded the chief ç
priest to carry this saint on his shoulders into the sanctum sanctorum ç
where he merged with Him. Amalan<193>dippir<193>n was composed by ç
him.
Tiruma<209>gai °<202>v<193>r, the next in the series, was a highway ç
robber turned a saint. Six works beginning with Periya Tirumo<202>i ç
are attributed to him. He is said to have excelled in four types of ç
poetic composition.
Madhurakavi °<202>v<193>r and Namm<193><202>v<193>r were contemporaries ç
and their lives were interwoven. The former, a br<193>hma<207>a, accepted ç
the latter, though of low caste,as his spiritual preceptor. Namm<193><202>v<193>r, ç
also called M<193>ran, Par<193><209>ku·ar or <185>a<219>hakopar, is ç
regarded as the greatest of all the °<202>v<193>rs. His four works ç
are: Tiruviruttam, Tiruv<193>·iriyam, Periya Tiruvand<193>di and ç
Tiruv<193>imo<202>i. These are exquisite works describing his profound ç
spiritual experiences. Out of these, the last work with 1102 verses ç
is well-known and widely studied.
The whole mass of compositions of the  °<202>v<193>rs  is  known  as  N<193>l<193>yira ç
Prabandham (because it numbers 4000), or Divya Prabandham. They ç
are regarded in status as equal to the Vedas. Hence the name `Dr<193>vi<195>a ç
Veda.' The Vi·i<218><219><193>-dvaita system which has accorded an ç
equalstatus to the Vedas and the Divya Prabandhams is incidentally ç
known as `Ubhaya Ved<193>nta' (ubhaya = two, both).
The teachings of these °<202>v<193>rs can be briefly summarised as ç
follows: N<193>r<193>ya<207>a is the supreme Lord. He is both immanent ç
and transcendent. He is the personification of all perfection. Apart ç
from incarnating himself as R<193>ma or K<216><218><207>a, he is manifesting ç
himself in the icons that are devoutly  worshipped,  as  `arc<193>vat<193>ra.' ç
Devotion to him, devoted service to him, total surrender to him (called ç
prapatti) is the surest and the easiest way of attaining him.
See also <MS><185>R®VAI<186>ØAVISM<D> and <MS>VI<185>I<186><187>°-DVAITAVED°NTADAR<185>ANA<D>.
@SPACE = 
@NT = <193>malaka, <193>malas<193>ra, <193>malas<193>r<200>
These are technical terms used in Hindu temple architecture. The crown ç
of a N<193>gara style of a temple (with curvilinear towers found mostly ç
in North and North-east India) is called <193>malaka for the simple ç
reason that it resembles an <193>malaka fruit (myrobalan) in shape. ç
It is a solid ring stone with a cogged rim. It forms the crown of ç
the main ·ikhara (dome) as also subsidiary ·ikharas. It clasps the ç
ve<207>u or the central shaft of the structure. It is not found in ç
the Dr<193>vi<195>a temples.
Sometimes, above the usual <193>malaka, there may be a smaller one ç
of similar shape. In this case, the lower one is called <193>malas<193>ra ç
and the upper (smaller) one <193>malas<193>r<200>.
The <193>malaka is the architectural symbol of the celestial world.
@NT = <193>mantra<207>a, nimantra<207>a
@N1 = (`invitation')
Inviting br<193>hma<207>as for partaking the food during a ·r<193>ddha ç
ceremony is an important part of that ritual. The dharma-·<193>stras ç
prescribe elaborate rules with regard to the type of br<193>hma<207>as ç
to be invited and also the mode of inviting them.
The two words constantly used in this connection are `<193>mantra<207>a' ç
and `nimantra<207>a.' Though they are often used synonymously, subtle ç
distinctions are sometimes made. A `nimantra<207>a' is more or less ç
compulsory to accept. If the invitee rejects it without proper grounds, ç
he is said to incur sin. But `<193>mantra<207>a' does not imply compulsion. ç
The invitee has much greater freedom to accept or reject it.
@NT = Amaraka<207><219>aka
@N1 = (`peak of the gods')
Places of pilgrimage have exercised enormous influence on the Hindu ç
society. They have contributed not a little, to thepreservation of ç
Hindu religion and culture. A river, a mountain, a forest, the seashore ç
or for that matter, any place of natural solitude and beauty†have ç
always attracted the devout and the holy, making them in course of ç
time a regular place of pilgrimage.
Amaraka<207><219>aka hill belonging to the Mekala mountain range in ç
the Bilaspur district of Madhya Pradesh is the place of origin of ç
the famous river Narmad<193>. One of the cities of B<193><207><193>sura ç
destroyed by the arrow of Lord <185>iva is said to have fallen here. ç
<185>r<193>ddha performed here is said to yield great results. It ç
is believed that a person committing religious suicide here, by fasting ç
or by jumping into fire or water, after purifying himself through ç
certain vows like that of brahmacarya (celibacy) and ahi<221>s<193> ç
(non-violence), will attain mukti or liberation. Even a visit, especially ç
on the days of lunar and solar eclipses, is highly eulogised.
See also <MS>NARMAD°<D>.
@NT = Amarako<218>a
@N1-1 = (`immortal lexicon' or `Lexicon of Amarasi<221>ha')
Lexicography is one of the important branches of technical literature ç
in Sans-krit. The Nigha<207><219>u, a vocabulary of Vedic words, ç
is the oldest lexicon so far known. The Nirukta of Y<193>ska (800 ç
<F51320MS>B.<|>C.<F255D>) i<F51320W1>s a commentary on it.
But among the extant lexicons of Sanskrit, the Amarako<218>a (also ç
spelt as Amarako·a) of Amarasi<221>ha (<F51320MS>A. D.<W1> 500), a Buddhist ç
scholar, who might have adorned the court of Vikram<193>ditya, is ç
the best known and the most widely used.
Popularly known as the N<193>ma-li<209>g<193>nu·<193>sanam (`a work ç
which deals with vocables and their genders'), it is divided into ç
three `k<193><207><195>as' or books or sections. (Hence the name Trik<193><207><195>a ç
also.) The first called Svargak<193><207><195>a deals with heavenly ç
matters. The second called Bh<220>mik<193><207><195>a deals with ç
earthly things. The third called S<193>m<193>nyak<193><207><195>a ç
is concerned with general matters.
The whole work is in poetry, in the anu<218><219>ubh metre. The major ç
part of the work deals with synonyms and only a small section called ç
N<193>n<193>rthavarga is devoted to homonyms.
Being the most popular of such lexicons, the Amarako<218>a has sixty ç
commentaries. Out of them the Amarako<218>od-gh<193><219>ana by ç
K<218><200>rasv<193>min (11th cent <F51320MS>A. D.<W1>) seems to be the ç
earliest. <F255MI><187><200>k<193>sarvasva of Sarv<193>nanda (12th cent. ç
<F51320MS>A. D.<W1>) is a more scholarly work.
@NT = Amaran<193>tha
@N1 = (`Lord of the immortals')
Pilgrimage to holy places is an integral part of the religious observances ç
of the Hindus. Though the number of such places in India is extremely ç
large, only a few have attained great celebrity over the centuries. ç
The Amaran<193>tha (<185>iva) cave in Kashmir is one such. Its importance ç
and antiquity were well-known even by the twelfth century since Kalha<207>a's ç
R<193>ja-tara<209>gi<207><200> mentions it.
Situated in the Himalayan ranges at a height of about 4300 metres ç
(13,000 ft.) it lies to the north-east of Srinagar, the capital of ç
Kashmir, at a distance of 138 kms. (86 miles.) It is a big natural ç
cave about 45 metres (150 ft.) in height, 30 metres (100 ft.) wide ç
and 60 metres (200 ft.) in length. Except for a small area, most of ç
the roof leaks. There are two holes in the northern wall of the cave ç
from which water trickles out and freezes into ice almost immediately. ç
One of the holes is bigger and below that a huge li<209>ga of snow ç
is formed. This is the famous Amaran<193>tha-li<209>ga. On its left ç
and right sides there are two more formations of ice, known respectively ç
as Ga<207>e·a and P<193>rvat<200>. The cave faces south and the rays ç
of the sun do not fall directly on the li<209>ga.
There is a traditional belief that the snow li<209>ga gets formed ç
every lunar month in the bright half and gets dissolved during the ç
dark half. Thus there is no li<209>ga on the new-moon day and the ç
li<209>ga attains its maximum size on the full-moon day. Even Ain-i-Akbari ç
of Abul Fazal (16t<F51320W1>h cent.) mentions this belief.
Visiting the cave-temple on the <185>r<193>va<207>ap<220>r<207>im<193> ç
day (July<192>August) is considered extremely auspicious since, according ç
to the mythological lore, <185>iva appeared in this cave on this day. ç
He made the gods immortal by feeding them with am<216>ta or nectar. ç
Hence the name Amara-n<193>tha, `Lord of the immortals'.
The pilgrims travel in a group from Srinagar. The government makes ç
elaborate arrangements for their comfort and safety.
@NT = Amarasi<221>ha
See <MS>AMARAKO<186>A<D>.
@NT = Amar<193>vat<200>
@N1 = (`the abode of immortals')
The pur<193><207>as (Hindu mythological works) delight in describing ç
Amar<193>vat<200>, the capital of Indra's paradise. Situated on the ç
eastern side of Mt. Meru it is said to have a thousand gates and a ç
hundred palaces. Full of fragrant flowers and sacred trees and with ç
celestial chariots movingat will, it is the abode of a variety of ç
celestial beings  like  devas,  siddhas,  apsaras, gandharvas and ç
others. It can be attained only by those who have performed sacrifices ç
and practised severe penance as also those who die on the battlefield.
There is an Amar<193>vat<200> in Andhra Pradesh, situated on the south ç
bank of the river K<216><218><207><193>, about 32 kms. (20 miles) ç
from Guntur. Though a small village now, it was formerly a flourishing ç
city by name Dh<193>nyaka<219>aka, the capital of the <185><193>l<200>v<193>hana ç
empire (2nd and 3rd cent. <F51320P10MSC1>A.D.<W1>). The Amare·vara temple ç
and the <185>ivar<193>tri celebrations there were famous even by the ç
tenth century <MS>A.D.<W1> The discovery in<MS>A.D.<W1> 1798 of parts ç
of a st<220>pa by Col. Mackenzie has put Amar<193>vat<200> firmly ç
on the architectural map of India. The great st<220>pa which took ç
shape between 200 <MS>B.<|>C.<W1> and <MS>A.<|>D.<W1> 200 and which ç
was bigger than the S<193><210>c<200> st<220>pa must have been 49 ç
metres (162 ft.) in diameter and about 37 metres (120 ft.) in height. ç
The works of sculpture, most of which are in the British Museum, are ç
exquisitely beautiful carvings, mostly in limestone.
@NT = Amar D<193>s, Guru
@N1 = (<F51320P10MSC1>A. D.<W1> 1479<192>1574)
Third in the hierarchy of the Gurus of Sikhism, Guru Amar D<193>s ç
has left an indelible impression on the religion and society of the ç
Sikhs during the formative period. Born in <F51320P10MSC1>A. D.<W1> 1479 ç
as the son of Tej Bh<193>n and Sulakhn<200> (also known as Lakho or ç
Lachmi) in the village Basarke (near the modern Basarke Gillan in ç
the Amritsar district of Punjab), Amar D<193>s had practically no ç
formal education. Though engaged in trade, the family profession, ç
he had an innate interest in religion which often took him to several ç
places of pilgrimage, especially Hardv<193>r. His strong build enabled ç
him to perform austerities and withstand the rigours of pilgrimages ç
in which he had great faith, imbibed by his deep acquaintance with ç
the Hindu religious traditions. Married to Manas<193> Dev<200>, he ç
begot two daughters andtwo sons. B<200>b<200> Bh<193>ni, the younger ç
daughter, was later on given in marriage to R<193>m D<193>s (nicknamed ç
Je<219>ha) who succeeded him as the next Guru.
His quest for inner peace ended when he met Guru A<209>gad. It was ç
B<200>b<200> Amro, a daughter of Guru A<209>gad that was instrumental ç
in bringing about this meeting. During his long probation of twelve ç
years under the Guru, Amar D<193>s had to unlearn many a Hindu custom ç
and deliberately cultivate the Sikh way of life. After he gained Guru ç
A<209>gad's confidence, he was directed to return to his family and ç
lead the normal life of a householder.
@SPACE1 = 
At the bidding of his Guru, Amar D<193>s built the town of Gobindwal, ç
more familiarly called Goindwal, and started living there. It is said ç
that he used to carry the water of the Beas River everyday from Goindwal ç
where he lived, to Khadur where Guru A<209>gad lived, for the Guru's ç
service. This steady and devoted service to the Guru A<209>gad gained ç
him the Guru's grace who finally decided to ordain him as the next ç
Guru. Amar D<193>s was nearly 73 years old when the Guru's mantle ç
fell on him in <F51320P10MSC1>A.D.<W1> 1552. D<193>tu, the first son of ç
Guru A<209>gad, who felt he had been deprived of the Guruship that ç
`legitimately' belonged to him, harassed Guru Amar D<193>s so much ç
that the latter left Goindwal for an unknown destination. The distressed ç
disciples approached the elderly saint Bhai Buddha on whose suggestion, ç
the Guru's mare was let free. The mare led them to the Guru's hiding ç
place. He was persuaded to return.
Guru Amar D<193>s trained a number of apostles to spread the message ç
of Sikhism. He is also credited with the performance of several miracles ç
like reviving a dead man, curing a lame devotee as also a mad queen.
The Mughal emperor Akbar is said to have sought audience with the ç
Guru and was impressed by him very much.
Having had a premonition of the approaching  death,  Guru  Amar  D<193>s ç
appointed R<193>m D<193>s, his son-in-law, as the next Guru in <F51320P10MSC1>A. ç
D.<W1> 1574 and shed his mortal coil soon after.
His contribution to the contents of the Guru Granth S<193>hib was ç
the third largest. His service to the growth and development of the ç
Sikh community was of a high order.
@NT = <193>ma·r<193>ddha
@N1 = (`·r<193>ddha with raw<R>ç
materials')
It is obligatory on the part of every Hindu to perform ·r<193>ddha, ç
a religious rite to please and to benefit the dead ancestors. It is ç
normally performed, with the offerings of cooked food. However, there ç
are occasions like journey or a·auca (cere- monial impurity caused ç
by the birth of a son and so on) when this will not be possible. The ç
dharma·<193>stras advise that on such occasions <193>ma·r<193>ddha ç
can be performed. Other things being the same, uncooked grains take ç
the place of cooked food, the quantity of the grains being 2to 4 ç
times the grains required for offering cooked  food.  °ma·r<193>ddha  is  always ç
prescribed for ·<220>dras.
See also <MS><185>R°DDHA<D>.
@NT = am<193>tya
@N1 = (`one who is near')
@SPACE = 
@SPACE = 
No civilized life is possible without the protecting hand of a king ç
or a ruler. Among the seven a<209>gas or constituents of a State (r<193>jya), ç
the am<193>tya (minister) occupies a place next only to that of the ç
king. The other two words that are commonly used to denote a minister ç
are `saciva' and `mantrin.' The `saciva' is a helper or a comrade. ç
The `mantrin' is one who is capable of giving counsel and keeping ç
secrets.
Sometimes the ministers are divided into two groups: dh<200>sacivas ç
or matisacivas and karmasacivas. The former are also called mantris ç
and are concerned with giving suitable counsel. The latter are responsible ç
for implementing the decisions taken.
Various views are given with regard to the number of ministers in ç
a king's cabinet. The number usually ranges from 8 to 20 or more.
Though it is obligatory on the part of the king to appoint ministers, ç
it is equally obligatory to test them properly and thoroughly before ç
doing so. Kau<219>ilya, for instance, lays down (Artha·<193>stra ç
1.10) that the would-be am<193>tyas are to be tested by upadh<193>s ç
(tests of honesty). The tests are designed to make them swerve from ç
the path of their duty (dharma) by tempting them through wealth or ç
woman (artha and k<193>ma) or by threats (bhaya), and are conducted ç
secretly.
The ministers, though loyal to the king, were also expected to secure ç
the confidence of the pauras and j<193>napadas (i.e.,the people). ç
This would call for the utmost exercise of tact and courage.
The posts were usually hereditary though the king had the option not ç
to appoint them as ministers if found not suitable.
See also <MS>R°J°<D> and <MS>R°JYA<D>.
@NT = am<193>v<193>sy<193>
@N1 = (`living near')
If  full-moon  has  fascinated  the ancient man, new-moon must have ç
induced a sort of anxiety and fear. In the Hindu religion, am<193>v<193>sy<193> ç
or new-moon has been raised to the status of a deity capable of bestowing ç
wealth and valiant sons on the supplicant (vide Atharvaveda 7.79[84].2).
On this day the moon is not visible from the earth. She is believed ç
to be with the sun (am<193> = near, v<193>sy<193> = living), and is ç
seen only by the sun. Hence the other name `dar·a' for am<193>v<193>sy<193>.
Two kinds of am<193>v<193>sy<193>s are recognised: sin<200>v<193>l<200> ç
when it is mixed with caturda·<200> tithi (the 14th day after fullmoon) ç
and kuh<220> when mixed with pratipad (the 1st day after new-moon). ç
Even these are sometimes referred to as deities who can be supplicated.
One of the well-known Vedic sacrifices, the Dar·a, has to be compulsorily ç
performed on this day.
Am<193>v<193>sy<193> falling on Monday, Tuesday or Thursday is considered ç
as especially holy. So also, if it is associated with the nak<218>atras ç
as An<220>r<193>dh<193>, Vi·<193>kh<193> or Sv<193>t<200>. Several ç
vratas (religious observances) are recommended to be performed on ç
such days.
@NT = Amb<193>
@N1 = (`mother')
Though a general word, meaning `mother,' it is more often used as ç
a proper noun, as a name of one of the aspects of P<193>rvat<200>, ç
the divine spouse of Lord <185>iva. Said to be of the colour of water ç
lily, she is depicted with four hands, carrying p<193>·a (noose), ç
padma (lotus) and p<193>tra (vessel) in three hands whereas the fourth ç
one is exhibiting the abhayamudr<193> (pose assuring freedom from ç
fear).
Mother Durg<193> is also sometimes called Amb<193>.
The first daughter of the king of K<193>·<200> was also named Amb<193>. ç
Ambik<193> and Amb<193>lik<193> were her sisters. Bh<200><218>ma brought ç
the three sisters by force during their svaya<221>vara. When he learnt ç
that Amb<193> had already been betrothed to the king Saubha, he sent ç
her to him. However the king Saubha refused to accept her. She returned ç
and pressed Bh<200><218>ma himself to marry her. He refused her request ç
since he had vowed to remain celibate. Incensed by this, she performed ç
austerities to kill Bh<200><218>ma, was reborn as <185>ikha<207><195><200> ç
(an offspring of Drupada) and ultimately killed him in the Mah<193>bh<193>rata ç
war.
@NT = Ambar<200><218>a
Ambar<200><218>a was an emperor belonging to the S<220>ryava<221>·a ç
and the Ik<218>v<193>ku lineage. A worthy son of a worthy father (M<193>ndh<193>t<216>), ç
Ambar<200><218>a was deeply devoted to Lord Vi<218><207>u. He was ç
very meticulous in observing the fast on ek<193>da·<200>s (11th day ç
after new-moon or full-moon, on which day fasting is obligatory). ç
Durv<193>sas, a sage known for his short temper, once attemp-ted to ç
make him swerve from the rules of the ritual but failed in his efforts. ç
Actually the tables were turned against him. The Sudar·anacakra (discus ç
of LordVi<218><207>u) pursued him relentlessly until he had to seek ç
the forgiveness and deliverance from the king Ambar<200><218>a himself. ç
(For details see Bh<193>gavatam 9.4, 5.)
There was another Ambar<200><218>a, the son of N<193>bh<193>ga. He ç
was known for his generosity and devotion.
In the R<193>m<193>ya<207>a (B<193>lak<193><207><195>a, 61) we come ç
across yet another Ambar<200><218>a who lost the yaj<210>apa·u (the ç
sacrificial animal) during the conduct of a sacrifice and was advised ç
to substitute the lost animal with a human being. <185>una··epha, ç
the middle son of a sage <184>c<200>ka, was purchased for this purpose. ç
Butthe boy was ultimately saved by the dynamic sage Vi·v<193>mitra.
<185>una··epha's story appears in some pur<193><207>as with variations ç
in which Hari·-candra is the king and not Ambar<200><218>a.
The  Mah<193>bh<193>rata  contains  an Ambar<200><218>a-G<200>t<193> ç
(Anug<200>t<193>-parva, 12). After attaining perfection Ambar<200><218>a ç
teaches that lobha (greed) is a great enemy responsible for spiritual ç
disaster, and hence it must be rooted out.
@NT = amba<218><219>ha
When the caste system was born in the Hindu society, the seed of admixture ç
of castes was also sown. Even as early as the Mah<193>bh<193>rata ç
period, such admixture (var<207>asa<209>kara) was deplored. One of ç
the several castes born out of such admixture is the amba<218><219>ha, ç
the offspring of a br<193>hma<207>a father and a vai·ya mother. Practice ç
of medicine and surgery as also agriculture are the professions recommended ç
for this caste. Some books make the amba<218><219>ha the offspring ç
of a k<218>attriya father from a vai·ya mother. Fighting is the vocation ç
recommended.
Amba<218><219>ha seems to be the name of a country also. A king, °mba<218><219>hya, ç
is said to have performed A·vamedha sacrifice (vide Aitareya Br<193>hma<207>a ç
39.7). Mah<193>-bh<193>rata mentions another king Amba<218><219>ha ç
who fought on the side of the Kauravas and met his death at the hands ç
of Arjuna. Ka<221>sa's mahout who tried to assassinate Balar<193>ma ç
and K<216><218><207>a was also known as Amba<218><219>ha.
@NT = <193>mbhas<200>-dh<193>ra<207><193>
@N1 = (`fixing the mind on the water principle')
It is one of the five dh<193>ra<207><193>s techni-cally known as `pa<210>cadh<193>ra<207><193>s' ç
in the works on Ha<219>hayoga. Such dh<193>ra<207><193>s help in the ç
conquest of the mind. When guided properly, this can lead to the realization ç
of the Self. Incidentally, certain super- normal powers are also attained ç
in the process.
°mbhas<200>-dh<193>ra<207>a is dh<193>ra<207><193> or fixing the mind ç
on the principle of ambhas or water. The water principle is white ç
like the kunda flower or conch or moon. It is circular in form with ç
Vi<218><207>u as the presiding deity and `va' as the b<200>ja (seed- ç
letter). Fixing the mind along with the pr<193><207>a (through kumbhaka ç
pr<193><207><193>y<193>ma) for five gha<219>ik<193>s (one gha<219>ik<193> ç
= 24 minutes) will help the yogi to destroy all sorrows. The yogi ç
who has perfected this will not die even in deepest water.
@NT = Ambik<193>
An aspect of goddess P<193>rvat<200>, Ambik<193> is described as being ç
seated on a lion. She has three eyes and is adorned with various ornaments. ç
Out of her four hands, three hold darpa<207>a (mirror), kha<195>ga ç
(sword) and khe<219>aka (shield). The fourth (one of the right hands) ç
exhibits the varadamudr<193> (boon-giving pose).
In the Mah<193>bh<193>rata, Ambik<193> was the wife of Vicitrav<200>rya ç
and mother of the blind king Dh<216>tar<193><218><219>ra. Amb<193>lik<193>, ç
her sister, was another wife who became the mother of P<193><207><195>u.
@NT = a<221>haspati
@N1 = (`lord of sins')
An intercalary month, especially the k<218>ayam<193>sa (the lunar ç
month omitted for adjustments of the calendar) is called `a<221>haspati' ç
in the Vedas (vide V<193>jasaney<200> Sa<221>hit<193> 22.30, 31).
See <MS>ADHIKAM°SA<D> for details.
@NT = <193>mik<218><193>
When milk is drawn in the morning and heated, and then the sour milk ç
of the previous evening is added to it, the mixture divides itself ç
into two portions, the solid one being called <193>mik<218><193> and ç
the liquid one, v<193>jina. °mik<218><193> is also called payasy<193>. ç
It is offered to the Vi·vedevas during the C<193>turm<193>sya sacrifices.
@NT = <193>mn<193>ya
@N1 = (`that which is committed to memory')
The Vedas, the basic scriptures of Hinduism, are known by several ç
other names: ·ruti, <193>mn<193>ya and tray<200>. They are called ç
`·ruti' since they are `heard' (·ru = to hear) by the disciples from ç
the mouth of the teacher. They are `tray<200>,' `a group of three' ç
since <184>gveda, Yajurveda and S<193>maveda, the three earlier ç
compilations were always considered together. They are known as `<193>mn<193>ya' ç
since they are learnt by rote, committed to memory (mn<193> = to commit ç
to memory, to repeat) and are handed downtraditionally from the teacher ç
to the disciple.
The word is sometimes used in the sense of kula or lineage and sa<221>prad<193>ya ç
or tradition as also <193>c<193>ra or custom.
@NT = am<216>t
@N1 = (`the nectar')
There have been several renaissance movements in Hinduism which have ç
reformed and revitalised it. One of the latest of such movements is ç
the one started by Guru N<193>nak (<F51320P10MSC1>A. D.<W1> 1469<192>1538). ç
It is now known as Sikhism and considered as an independent religion.
Guru Gobind Singh (<F51320P10MSC1>A. D.<W1> 1666<192>1708) formed the Kh<193>ls<193> ç
(lit., `personification of the guru') an army of baptised Sikhs. The ç
process of baptism consisted of stirring water in an iron bowl with ç
a double-edged sword, mixing it with sugar and drinking it, as also ç
sprinkling it on the face. Sacred verses from the <F255P255MIC255>Guru ç
Granth S<193>hib were uttered during the stirring. The water itself ç
was called `am<216>t' or nectar. The procedure is followed even now.
See also <MS>GURU GOBIND SINGH <D>and<MS> SIKHISM.<D>
@NT = am<216>ta
@N1 = (`that which gives immortality')
The desire to become immortal is most natural to all mortals. Hindu ç
mytho- logy often mentions `am<216>ta,' the nectar or ambrosia, by ç
drinking which one can become immortal. The story goes that Indra, ç
the king of gods, lost his all to the demons, owing to the curse of ç
the sage Durv<193>sas, whom he had displeased. Lord Vi<218><207>u ç
advised him to make up with the demons and with their help, to churn ç
the ocean of milk, out of which am<216>ta could be got. By drinking ç
it the gods could become immortal and regain their lost sovereignty. ç
Am<216>ta was the last product got out of this churning. Lord Vi<218><207>u, ç
in the guise of Mohin<200> (the enchantress) successfully deceived ç
the demons and served it to the gods. Inebriated by the new strength ç
and vigour got out of consuming it, the gods routed the demons and ç
regained all they had lost.
See <MS>SAMUDRAMATHANA<D> for details.
Garu<195>a is said to have brought it from heaven to give it to Kadr<220>, ç
his aunt, to release his mother Vinat<193> from her slavery. So also, ç
K<216><218><207>a is believed to have got it for the sage Uda<209>ka.
The word am<216>ta is also used in several other senses. For instance: ç
God, moon, liberation, what is left over after a sacrifice, food obtained ç
without begging, milk, ghee, an auspicious time of conjunction of ç
certain nak<218>atras (stars) with certain week days and so on. The ç
last is also known as `am<216>tasiddhiyoga.'
@SPACE = 
@NT = Am<216>tabindu Upani<218>ad
This is a minor Upani<218>ad of just 22 verses belonging to the K<216><218><207>a ç
Yajurveda.
It starts with an oft-quoted statement that it is the mind that is ç
responsible foreither bondage or liberation. When attached to sense ç
objects it leads to bondage; when freed from the same, it leads to ç
liberation. Hence it should be freed from the bondage of sense-life.
It then delineates the process of meditation by which the mind bereft ç
of sense-attachments is fixed in the region of the heart on Brahman. ç
Meditation on Brahman can be practised first through the sound of ç
Om, and then directly.
This is followed by an exposition of Brahman-<193>tman with the usual ç
adjectives like ni<218>kalam (partless), nira<210>janam (stainless), ç
aprameyam (immeasurable) and so on. Then the Upani<218>ad describes ç
how Brahman, the one without a second, appears as many, with the simile ç
of moon and its reflections in water, and, the sky and pots.
It puts forth the theory of two kinds of knowledge, of <185>abda-Brahman ç
and Para-Brahman.
The former is the Vedas and their branches. A mastering of these can ç
help in leading to the latter, which has to be realized through contemplation. ç
This contemplation is likened to the process of churning milk to get ç
butter, or churning the pieces of ara<207>i (See <MS>ARAØI.<D>) to ç
get fire. The Upani<218>ad ends with a statement of thej<210><193>n<200>, ç
a man of realization, reflecting on his realization of his identity ç
with Brahman.
It is interesting to note that there is another Upani<218>ad called ç
Brahmabindu Upani<218>ad which is almost identical with this Upani<218>ad.
See also <MS>UPANI<186>ADS<D>.
@NT = am<216>takala·a
@N1 = (`chalice containing<R>ç
ambrosia')
During samudramathana (churning of the milk-ocean) several celestial ç
objects manifested themselves, the last of which was am<216>ta or ç
ambrosia in a golden vessel(kala·a) carried by Dhanvantari, the celestial ç
physician, considered as an aspect of Vi<218><207>u.
The finial of a Hindu temple is shapedlike the am<216>takala·a, symbolizing ç
immortality, the state to which the devotee aspires to rise.
See also <MS>DHANVANTARI<D> and <MS>SAMUDRA-MATHANA<D>.
@NT = Am<216>tan<193>da Upani<218>ad
@SPACE = 
@SPACE = 
This is a small Upani<218>ad of 38 verses belonging to the K<216><218><207>a ç
Yajurveda and classified among the `Yoga Upani<218>ads' since the ç
subject matter relates to yoga.
The Upani<218>ad starts with the exhortation to study the scriptures ç
like the Vedas and their accessories, practise thedisciplines taught ç
there, realize the highest Brahman and then, give up these scriptures ç
since the purpose of life will have been accomplished.
This is followed by a simile of the chariot in which Om is the chariot ç
and Vi<218><207>u (= buddhi or intellect) is the charioteer. The aspirant ç
devoted to Rudra (his own Self) and desirous of attaining Brahmaloka ç
or the abode of Brahman, travels in that chariot as far as it goes ç
and then abandons it. The idea is that the aspirant while repeating ç
Om thinks of `Rudra' or his own Self as identified with Brahman, through ç
his intellect. When this identity is felt, he abandons the repetition ç
of Om but proceeds to make his meditation deeper, ultimately resulting ç
in direct experience of that oneness.
Then comes the description of `<186>a<195>a<209>ga-yoga' or yoga comprising ç
six steps. They are: praty<193>h<193>ra, dhy<193>na, pr<193><207><193>y<193>ma, ç
dh<193>ra<207><193>, tarka and sam<193>dhi. Praty<193>h<193>ra (lit., ç
withdrawal of the mind from the senses) is defined here as thinking ç
of the mind and the sense-objects as `rays emanating from the <193>tman' ç
thus neutralizing their effects. Dhy<193>na is meditation on the oneness ç
of <193>tman with Brahman. Pr<193><207><193>y<193>ma is regulation ç
of breath, and through that, regulation of the vital energies or pr<193><207>as. ç
Dh<193>ra<207><193> or fixing the mind on the objects of meditation, ç
is the earlier stage of dhy<193>na. Tarka is logic, not opposed to ç
the teachings of the Vedas. Sam<193>dhi is the direct experience of ç
the oneness of the <193>tman with Brahman.
The Upani<218>ad gives some details of the process of pr<193><207><193>y<193>ma, ç
positions and fields of operation of the five pr<193><207>as, certain ç
obstacles to yoga like fear, anger and laziness which must be overcome ç
and a fewother details connected with yogic practices. It concludes ç
with the statements that if a yogi has mastered the techniques of ç
raising his pr<193><207>a through the various plexuses up to the centre ç
of the head, his pr<193><207>a will depart, at the time of death, ç
through the brahmarandhra (aperture in the crown of the head) whatever ç
be the manner of his death, and so, he is never reborn.
See also <MS>PR°Ø°Y°MA<D> and <MS>UPANI<186>ADS<D>.
@SPACE1 = 
@NT = am<216>tatva
@N1 = (`immortality')
@SPACE = 
All living beings are naturally and instinctively struggling for freedom ç
from sorrow and suffering. So also do they seek pleasure and happiness. ç
The Upani<218>ads, the ancient and basic works of Hinduism, call this ç
state `am<216>tatva,' the state of immortality and bliss. Mok<218>a, ç
mukti, nirv<193><207>a and kaivalya are some of the more common synonyms ç
of the same.
All the Hindu scriptures are unanimous that (a) am<216>tatva is the ç
goal of human life; (b) the human beings desirous of obtaining it ç
should purify themselves by giving up evil ways of life; (c) they ç
should take recourse to the ·<193>stras (holy books) and <193>c<193>rya ç
(spiritual preceptor), and practise j<210><193>na (knowledge) as also ç
bhakti (devotion) to reach that goal.
Once  this  goal  of  am<216>tatva  is obtained, there is no return ç
to this life of transmigration. The liberated soul will enjoy eternal ç
bliss.
Details of the path as also the nature of am<216>tatva differ from ç
school to school of religious philosophies.
See also <MS>MOK<186>A<D>.
@NT = Am<216>tsar
@N1 = (`Lake of Nectar')
Am<216>tsar or Amritsar is the principal holy city of the Sikhs. It ç
is in Punjab and is also the district headquarters.
The foundation of the city was laid by guru R<193>md<193>s (<MS>A.<|>D.<D> ç
1534-1581), the fourth Guru of Sikhism, when he inaugurated the digging ç
of the holy tank `Am<216>t-sar' (`lake of nectar') on a piece of land ç
purchased from the residents of the neighbouring village of Tu<209>g ç
during the time of the previous Guru, Amard<193>s (<MS>A.<|>D.<D> 1479- ç
1574). The habitation that grew round the holy lake was initially ç
called `R<193>md<193>spur' or `Chakk R<193>md<193>s' or `Chakk Guru'.
Guru Arjan (<MS>A.<|>D.<D> 1563-1606) comple-ted and lined the tank. ç
He also constructed the holy shrine in its middle, ``Harimandar' (now ç
famous as the Golden Temple).
Guru Hargobind (<MS>A.<|>D.<D> 1595-1644) constructed the Ak<193>l ç
Takht (`Throne of the Eternal') near the pool. He also got dug up ç
two more tanks in the town, known as `Kaulsar' and `Bibeksar'.
During<|> the <|>eighteenth <|>century, Am<216>tsar witnessed many ups ç
and downs like the Sikh community. It suffered repeatedly, desecration ç
and destruction at the hands of the Muslim rulers of Delhi. Only by ç
the time of Mah<193>r<193>j<193> Ra<207>jit Singh (<MS>A.<|>D.<D> 1780-1830) ç
order and peace were established.
Am<216>tsar  gradually  grew  into  an important industrial and commercial ç
city.
Am<216>tsar  has  many  Sikh  shrines associated with the memory of ç
the Gurus, martyrs and heroes. Some of them are: Ak<193>l Bu<209>ga, ç
Gurdw<193>r<193> Dukh Bha<210>jan<200> Ber<200>, Gurdw<193>r<193> ç
Tharh<193> S<193>hib, Gurdw<193>r<193> Ma<210>j<200> S<193>hib, Gurdw<193>r<193> ç
Guruke Mahal, B<193>b<193> A<219>al S<193>hib, Gurdw<193>r<193> R<193>msar, ç
Gurdw<193>r<193> Bibeksar, Gurdw<193>r<193> Dar·an<200> Diorh<200>, ç
Gurdw<193>r<193> Damdam<193> S<193>hib and soon.
@NT = a<221>·<193>vat<193>ra
@N1 = (`partial manifestation of the Divine')
See <MS>AVAT°RA<D>.
@NT = A<221>·um<193>n
@N1 = (`endowed with light')
Emperor Sagara of S<220>ryava<221>·a (race descended from the sun) ç
once started the A·vamedha sacrifice (horse-sacrifice). When the sacrificial ç
horse was lost, his sons went out in search of it and found it grazing ç
in the monastery of the sage Kapila. The disrespect shown by them ç
to the sage resulted in their being reduced to ashes. A<221>·um<193>n ç
the grandson of Sagara then set out in search of the horse and his ç
uncles. When he discovered the horse and the tragedy, he pacified ç
the sage and brought back the horse so that Sagara could  complete  the  sacrifice  without ç
further hitch. After the completion of the sacrifice, A<221>·um<193>n ç
became the king and ruled for some time. Then he left his kingdom ç
in charge of his son Dil<200>pa and retired to the forest to perform ç
austerities. He tried to bring the river Ga<209>g<193> to wash the ç
ashes of his ancestors and redeem their souls, but he did not succeed. ç
The task was achieved later by his grandson Bhag<200>ratha.
See also <MS>BHAG®RATHA<D>.
@NT = anadhy<193>ya, anadhyayana
@N1 = (`not studying [the Vedas]')
All those who labour need rest. The system of holidays and vacations ç
is as old as mankind. The Vedic students and their teachers were no ç
exception. Adhyayana or Vedic studies were to be pursued according ç
to some rules and regulations set by tradition. On certain specified ç
days, the <193>c<193>rya would not teach. Such days wereknown as ç
anadhy<193>ya or days of anadhyayana. However, on such days the students ç
were expected to revise their lessons, to do cintana and manana (reflection) ç
and even get guidance from the senior students.
Days of anadhy<193>ya are: pratipad, a<218><219>am<200>, caturda·<200>, ç
p<220>r<207>im<193> and am<193>v<193>sy<193> as also days of sa<209>krama<207>a. ç
These are† according to the lunar calendar†the 1st, 8th and 14th days ç
after new-moon and full-moon; full-moon and new-moon days, and the ç
days on which the sun enters the next sign of the zodiac.
@NT = an<193>hatacakra
@N1 = (`unbeaten sound plexus')
It is one of the six centres of psychic energy mentioned in the works ç
on Ha<219>ha-yoga. This centre is called an<193>hatacakra since the ç
an<193>hata sound (sound produced without the beating of two objects) ç
is heard there. It is situated in the region of the heart and is said ç
to have twelve petals of red colour.
For details see <MS>CAKRAS<D>.
@NT = an<193>hatan<193>da
@N1 = (`sound produced without beating')
When a yogi practises pr<193><207><193><+>y<193>ma (breathing exercises ç
aimed at regulating theenergy of pr<193><207>a) and achieves purification ç
of the n<193><195><200>s (tubular structures through which pr<193><207>ic ç
energy flows) he starts hearing melodious sounds of pra<207>ava or ç
O<221>k<193>ra. Since these sounds are generated without any beating ç
(<193>hati) of two objects (which, incidentally, is theusual way ç
of producing sound) they are called `an<193>hata-n<193>da.' The sound ç
is normally heard through the right ear whether open or closed. However, ç
it is more distinct when the ears are kept closed.
Some authorities say that the sound can also be heard if the ajap<193>mantra ç
is repeated one lakh times.
See also <MS>AJAP°JAPA, N°£®S,<D> and<MS> PR°Ø°Y°MA<D>.
@NT = anaik<193>ntika
@N1 = (`inconclusive')
The Ny<193>ya system of philosophy describes five kinds of `hetv<193>bh<193>sas' ç
or fallacies in logic, one of which is `anaik<193>ntika,' also called ç
`savyabhic<193>ra.' This fallacy occurs when the ostensible middle-term ç
violates the general rule of inference, namely, that it must be universally ç
related to the major term or that the major term must be present in ç
all cases in which the middle is present. For instance, consider the ç
statement: `All knowable objects are fiery. The hill is knowable. ç
Therefore the hill is fiery.' Here the middle term `knowable' is indifferently ç
related to both fiery objects like the kitchen and fireless objects ç
like the lake. All knowable objects being thus not fiery, we cannot ç
argue that a hill is fiery because it is knowable.
See also <MS>HETV°BH°SA<D>.
@NT = <193>nanda
@N1 = (`complete bliss')
@SPACE1 = 
This term is generally used to indicate unadulterated perfect bliss, ç
got by the realization of God or the Self. In fact, one of the three ç
basic terms used to indicate the nature of God is <193>nanda, the ç
other two being sat (existence) and cit (consciousness). The second ç
chapter of the Taittir<200>ya Upani<218>ad designated as °nanda ç
Vall<200> shows by a calculation of its own, that brahm<193>nanda ç
or bliss of Brahman is infinitely superior to the greatest joy that ç
a human being ideally situated in life can ever hope to get.
The word is also used to indicate Lord  Vi<218><207>u,  a  particular  variety  of ç
Sanskrit metre and particular combinations of nak<218>atras (stars) ç
with weekdays, like A·vin<200> being in conjunction with Sunday, and ç
so on.
The word is also used as a suffix in the names of sa<221>ny<193>sins ç
(monks), though it is difficult to say since when exactly the practice ç
began. Earlier sa<221>ny<193>sins like <185>a<209>kara have not used ç
it. Later <193>c<193>ryas (pontiffs) of the <185><216><209>ger<200> ç
Monastery (for instance, <185>a<209>kar<193>nanda) have started using ç
it.
@NT = °nandabodha
One of the well-known polemical writers of Advaita metaphysics, °nanda-bodha ç
(11th cent. <F51320P10MSC1>A.D.<W1>) (also called °nanda-bodh<193>c<193>rya ç
and °nandabodha Bha<219><219><193>rak<193>- c<193>rya) a disciple ç
of Vimukt<193>tman of the <F255P255MIC255>I<218><219>isiddhi fame (10th ç
cent. <F51320MS>A. D.<W1>) has four works to his credit: <F255MI>Ny<193>yamakaranda, ç
Ny<193>yad<200>p<193>val<200>, Pram<193><207>am<193>l<193> and <185>abda-nir<207>aya ç
Vy<193>khy<193>. The first of these is the most celebrated and has ç
been commented upon by Citsukha (13th cent. <F51320MS>A. D.<W1>). The special ç
features of this work are: refutation of the S<193><209>khyan theory ç
of multiplicity of selves and the apparent difference of objective ç
entities; the theory that everything other than Brahman is mithy<193> ç
(false) since it is d<216>·ya (perceived); a new defini- tion of mithy<193>tva ç
(falsity) viz., <F255MI>sadbhinnatva<221> mithy<193>tvam (falsity is ç
being diffe-rent from the real); that avidy<193> is positive in the ç
sense it is non-negative; that the cessation of avidy<193> is an entity ç
of a fifth category, different from sat (real), asat (unreal), sad-asat ç
(real-unreal) and anirvacan<200>ya (indefinable).
@NT = °nandagiri
Among all the Indian Philosophical systems, the Advaita Ved<193>nta ç
of <185>a<209>kara and his followers can boast of the maximum number ç
of written works. One of the writers in this line who has done yeomen ç
service by writing sub-commentaries on all the major works of <185>a<209>kara ç
is °nanda-j<210><193>na, celebrated as °nandagiri, who lived in the ç
14th cent. <F51320P10MSC1>A. D.<W1> Known as Jan<193>rdana in his premonastic ç
life, he was the son of one S<220>ryan<193>r<193>ya<207>a and belonged ç
to the country called Cera (now in Tamil Nadu). He was probably a ç
devotee of Vi<218><207>u. His guru was <185>uddh<193>nanda. His <219><200>k<193> ç
(comment) on the <F255P255MIC255>B<216>had<193>ra<207>yaka V<193>rttika ç
of Sure·vara (7th<192>8th cent. <F51320MS>A.D.<W1>) has  been  highly  appreciated.  In  his ç
original polemical work <F255MI>Ved<193>nta-tarka-sa<209>graha he has ç
refuted the Vai·e<218>ika categories like dravya, gu<207>a etc. In ç
his conclusions he has tried to follow his predecessors like °nandabodha ç
(11th cent. <F51320MS>A. D.<W1>) and others. He holds that avidy<193> or ç
aj<210><193>na which is an indeterminable false entity is the stuff ç
of this world. Aj<210><193>na is one only and is supported by Brahman.
@NT = <193>nandamayako·a
@N1 = (`the bliss sheath')
One of the five sheaths, the pa<210>ca-ko·as, it gets its name due ç
to the experience of joy in su<218>upti or deep sleep. In content, ç
it is identical with aj<210><193>na or nescience. Since it makes the ç
j<200>va, the individual soul, forget his nature as pure `caitanya' ç
or consciousness, by covering it as it were, like a ko·a or sheath, ç
it is termed as a `ko·a.' It clings to the soul till the state of ç
liberation.
See also <MS>PA<178>CAKO<185>AS<D>.
@NT = °nanda R<193>m<193>ya<207>a
The R<193>m<193>ya<207>a and the Mah<193>bh<193>rata are the two ç
popular scriptures that haveruled the hearts of the Hindus for millennia. ç
They have inspired innumerable writers, poets and artists to create ç
marvellous works of literature and art based upon the themes drawn ç
from their stories and personalities. One of the numerous R<193>m<193>ya<207>as ç
that have sprung up in imita-tion of V<193>lm<200>ki's is the °nanda ç
R<193>m<193>ya<207>a, sometimes styled as Manohara-°nanda-R<193>m<193>ya<207>a ç
also. Though attributed by tradition to V<193>lm<200>ki himself, it ç
is obviously a late work, later than the Adhy<193>tma R<193>m<193>ya<207>a ç
(14th cent. <F51320MS>A.D.<F255D>)<F51320W1>
The work comprises 12,323 verses spread over 109 sargas or chapters ç
contained in nine k<193><207><195>as or books. It is written in the ç
form of a dialogue between P<193>rvat<200> and <185>iva, later on ç
introducing another dialogue between two sages R<193>mad<193>sa and ç
his disciple Vi<218><207>ud<193>sa. A few innovations and many additions ç
have been made to the original story as given in V<193>lm<200>ki's ç
R<193>m<193>ya<207>a.
Perhaps, the book was written at a time when the K<216><218><207>a ç
cults were becoming more popular, to reassert the glory and supremacy ç
of R<193>ma. Though attempts have been made to establish the identity ç
of the two incarnations and to foresee the events of K<216><218><207><193>vat<193>ra ç
in R<193>ma's story, the predisposition in favour of R<193>ma is obvious.
An attempt can now be made to summarise the work briefly:
The first book known as S<193>rak<193><207><195>a (13  sargas,  2565  ·lokas  or  verses) ç
summarises the entire story of V<193>lm<200>ki's R<193>m<193>ya<207>a, ç
including R<193>va<207>a's story as given in the last book, Uttarak<193><207>da. ç
The story of R<193>va<207>a's bringing the <193>tmali<209>ga of <185>iva ç
from Kail<193>sa and the li<209>ga being fixed to the ground at Gokar<207>a ç
due to the machinations of Vi<218><207>u in the guise of a br<193>hma<207>a ç
boy appears in the 9th sarga. So also the story of establishment of ç
the li<209>ga at R<193>me·vara. Other additions to the original are: ç
the humbling of M<193>ruti's pride, the slaying of Air<193>va<207>a ç
and Mair<193>va<207>a (friends of R<193>va<207>a from the nether world), ç
the story of Kany<193>kum<193>r<200> and the teaching of Catu··loki ç
Bh<193>gavata to Vy<193>sa by N<193>rada.
@SPACE1 = 
The second book called Y<193>tr<193>k<193><207><195>a (9 sargas, ç
746 ·lokas) deals with the worship of the river Ga<209>g<193> by S<200>t<193>, ç
the story of the river Saray<220> and R<193>ma's pilgrimage.
The third book designated Y<193>ga-k<193><207><195>a (9 sargas, ç
628 ·lokas) describes the A·vamedhay<193>ga performed by R<193>ma ç
along with S<200>t<193>.
The fourth book, the Vil<193>sak<193><207><195>a (9sargas,  676  ·lokas)  describes  the ç
amorous sports of R<193>ma and S<200>t<193>.
The fifth book named <185>ubhajanma-k<193><207><195>a or Janmak<193><207><195>a ç
(9 sargas, 804 ·lokas) deals with the story of the banish- ment of ç
S<200>t<193> and the birth of Lava and Ku·a to S<200>t<193>. The interesting ç
points to be noted are: R<193>ma deliberately plans and enacts the ç
drama of banishment; Ku·a is the son born in the natural way to S<200>t<193>, ç
whereas another baby created by V<193>lm<200>ki out of `lava' seeds ç
(cloves or nutmeg) (hence named `Lava') and infused with life is accepted ç
by S<200>t<193> as her own son and a special vrata (religious rite) ç
called `Sa<221>yogakara<207>avrata' is performed by S<200>t<193> at ç
the behest of V<193>lm<200>ki. The famous R<193>marak<218><193> Stotra ç
forms part of the 5th sarga.
@SPACE1 = 
The sixth book christened Viv<193>ha-k<193><207><195>a (9 sargas, ç
585 ·lokas) describes the marriage of Ku·a with Campik<193> and Lava ç
with Sumati, as also the marriage of Y<220>paketu (son of <185>atrughna) ç
with Madanasundar<200> (daughter of the King Kambuka<207><219>ha). ç
The last section deals with the m<220>lamantra of °<210>janeya and ç
the process of repeating it in order to get rid of the maladies due ç
to diseases and evil spirits.
R<193>jyak<193><207><195>a (24 sargas, 2641 ·lokas), the seventh ç
book, contains some miscellaneous topics like R<193>masahasran<193>ma, ç
the story of a dog and a sa<221>ny<193>sin who was given the `punishment' ç
of being made the head of a temple organization, the banning of laughter ç
in his kingdom by R<193>ma, the story of V<193>lm<200>ki's previous ç
births and R<193>ma teaching a lesson to S<200>t<193> and R<193>ma's ç
discourses on dharma to his subjects. The 8th sarga of this book is ç
completely in prose.
Manoharak<193><207><195>a (18 sargas, 3101 ·lokas) the penultimate ç
book is the largest in volume and contains R<193>ma's expounding spiritual ç
truths to his mother Kausaly<193> as also Sumitr<193> and Kaikey<200>, ç
at their request. A number of hymns, technically called `kavaca' (= ç
armour) have been included in this section (<185>r<200>r<193>makavaca, ç
Han<220>matkavaca, S<200>t<193>kavaca and so on). A ritual recitation ç
of these is said to fulfil any desire one cherishes. The 17th sarga ç
gives the story of R<193>m<193>ya<207>a in a nutshell and is called ç
S<193>rar<193>m<193>ya<207>a.
The last book, with the appellation of P<220>r<207>ak<193><207><195>a ç
(9 sargas, 577 ·lokas) is the smallest in size. It describes R<193>ma's ç
ascent to Vaiku<207><219>ha (the abode of Vi<218><207>u) as Vi<218><207>u ç
after installing Ku·a on his throne as his successor.
See also <MS>R°M°YAØA<D> and <MS>V°LM®KI<D>.
@SPACE = 
@NT = °nand<193>·rama Mudra<207><193>laya
This is one of the few pioneering institutions that has been dedicated ç
to preserving and publishing old books and manuscripts dealing with ç
Hindu scriptures and Indological subjects.
It was started at Pune in <MS>A.<|>D.<D> 1888 by M. C. Apte who dedicated ç
all his wealth for the new institution.
It is actively engaged in collecting and preserving old manuscripts ç
and books and publishing them.
The building of the institution has a shrine dedicated to <185>iva ç
where religious programmes are conducted.
Apart from a guest-house there is also a hostel for boy-students.
So far, 188 books have been printed and 8000 Sanskrit manuscripts ç
have been collected. The process of digitalising them to preserve ç
them in CD's is going on.
@NT = °nanda-t<200>rtha
See <MS>MADHV°C°RYA<D>.
@NT = Ananta
@N1 = (`the endless')
Literally the word means `that which is endless,' hence `infinite'. ç
It is one of the epithets frequently used to describe or praise God ç
in the Hindu scriptures. The Upani<218>ads hold that Brahman is satya, ç
j<210><193>na and ananta (truth, knowledge or consciousness and infinite).
In the mythological lore, °di·e<218>a the great serpent on whom Lord ç
Vi<218><207>u is resting, is named `Ananta.' He is `Ananta' since ç
he has an infinite number of hoods on which he is supporting the worlds. ç
He represents cosmic time which is infinite and endless. Created worlds ç
come into being in time and are sustained in time. This is the meaning ç
of the hoods of Ananta supporting the worlds.
See also <MS>°DI<185>E<186>A<D>.
@NT = Ananta-caturda·<200>
@N1 = (`the fourteenth day connected with Ananta')
Vratas (religious vows) and utsavas (celebrations) have become an ç
integral part of Hindu religious, cultural and social life. If vratas ç
stress the need for personal religious vows and discipline, utsavas ç
provide an opportunity for rejoicing with the other members of the ç
community.
One of several such vratas is Ananta-caturda·<200> vrata, which is ç
celebrated on the caturda·<200> (14th day) of the brightfortnight ç
of the month Bh<193>drapada (August-September). It consists chiefly ç
in the worship of Lord Vi<218><207>u as Ananta (`the Infinite One') ç
and in the wearing of a holy strap of thread dyed with saffron, on ç
the hand (on the right hand in the case of men and on the left in ç
the case of women). The thread should be of cotton or silk and should ç
have 14knots. It should be worn after keeping it on a jar of water ç
duly established on a ma<207><195>ala (ritual diagram) and worshipping ç
it. The Agnipur<193><207>a (192.9) gives the mantra to be recited ç
on this occasion.
It is an individual vrata which is normally performed on the bank ç
of a river. Salt is forbidden in this vrata. Gaining happiness is ç
the result promised. It is believed that if it is performed regularly ç
for 14 years, one can reach the abode of Vi<218><207>u.
@NT = Ananta-·ayana
@N1 = (`One who is reclining on the serpent Ananta')
Lord Vi<218><207>u has several aspects of manifestation. The one depicting ç
him as reclining on the coils of serpent <185>e<218>a or Ananta (as ç
bed) is called `<185>e<218>a·ayana' or `Ananta·ayana.'
The ·ayana-images (images showing Vi<218><207>u, in the reclining ç
posture) are of fourtypes: yoga·ayana, bhoga·ayana, v<200>ra·ayana ç
and <193>bhic<193>rika·ayana. The first shows him with two arms and ç
in a meditative mood, with half<192>closed eyes. Instead of <185>r<200> ç
and Bh<220>, the two consorts, the sages Bh<216>gu and M<193>rka<207><195>eya ç
are shown. Brahm<193> is shown seated on the lotus emerging from his ç
navel. In the second type there are four arms and the icon is fully ç
bedecked with ornaments. <185>r<200> and Bh<220> are also shown along ç
with the sages Bh<216>gu and M<193>rka<207><195>eya. Brahm<193> and ç
<185>iva are shown on the rear wall. In the third type, he is holding ç
·a<209>kha (conch) and cakra (discus) in two of the four hands. The ç
demons Madhu and Kai<219>abha are shown at his feet, trying to attack ç
him. In the last type, he is shown with an emaciated body, scanty ç
clothing and with no attendants. This image is usually set up outside ç
the town or village.
These four images are respectively worshipped by those seeking spiritual ç
welfare, worldly enjoyments, strength and destruction of enemies.
Trivandrum, capital city of Kerala state, was formerly known as Tiru-Ananta-puram ç
or Ananta·ayana since it has a reputed  temple  dedicated  to  Ananta- ç
·ayana, also called Padman<193>bha. It is one of the well-known shrines ç
dedicated to Vi<218><207>u and was probably built during the early ç
medieval era. The image is made of stucco and hence no abhi<218>eka ç
(ceremonial bathing) is done to it.
The main difference between the Ra<209>gan<193>tha icon (which is ç
also a ·ayana<192> image) and Ananta·ayana is that the latter has ç
Brahm<193> on the lotus rising from thenavel whereas the former does ç
not have it.
@NT = an<193>rabdha
@N1 = (`not begun')
Hinduism, Jainism and Buddhism are the three world religions which ç
accept thetheory of karma and reincarnation. According to this theory, ç
the principle, `As you sow, so you reap' can be applied to the field ç
of our actions, both physical and psychical.
`Karma' is the unseen effect of an action which will become manifest ç
in course of time under favourable circumstances. This karma is of ç
three types: sa<210>cita (`the accumulated') or an<193>rabdha (`not ç
begun'), <193>rabdha or pr<193>rabdha (`the begun') and kriyam<193><207>a ç
(`being done now') or <193>g<193>m<200> (`[giving fruit] in future').
The entire mass of karma which has accumulated over several births, ç
which is yet to fructify, is `an<193>rabdha.' It is from this stock ç
of karma, that a part gets ripened and causes the present birth.
Hindu philosophical and religious works  declare  that  <193>tmaj<210><193>na  (self- ç
realization) can destroy this mass of an<193>rabdhakarma, thus preventing ç
future transmigrations.
The word is also used in its literal sense of anything that is not ç
begun or undertaken.
See also <MS>KARMA, PR°RABDHA, PUNARJANMA, REINCARNATION, SA<178>CITA<D>.
@NT = °narta
°narta was king of the famous Ik<218>v<193>ku race, being the grandson ç
of Manu and son of <185>ary<193>ti. Sukany<193>, the paragon of wifely ç
virtues and wife of the sage Cyavana was his sister. He is said to ç
have built the fortress at the city Ku·asthal<200> which was later ç
chosen by K<216><218><207>a as his capital under the new name Dv<193>rak<193>.
Ved<193>rtha, a reputed scholar, was his subject.
The country ruled by °narta was also called by the same name.
@NT = an<193>rya
@N1 = (`non-°rya')
The words <193>rya and an<193>rya, whatever their original connotations, ç
lost their racial flavour in later literature. `°rya' is a well-bred ç
man, a refined and cultured gentleman. An<193>rya is the opposite ç
of all these. The word was often used in a derogatory sense.
See also <MS>°RYA, D°SA<D> and <MS>DASYU<D>.
@NT = An<193>sakti-yoga
@N1 = (`Yoga of disinterestedness,' `Yoga of detachment')
The dominant trend of the Upani<218>ads is towards karma-sa<221>ny<193>sa ç
or karma-ty<193>ga, renunication of all actions, since it was strongly ç
believed that karma or action lead to spiritual bondage. Opposition ç
to this view is first noticed in the ®·<193>v<193>sya Upani<218>ad ç
(2) which is later on developed in the Bhagavadg<200>t<193> as a ç
regular doctrine. It is <193>sakti or attachment to the fruits of ç
actions that is really the cause of spiritual bondage. Hence, if actions ç
can be performed with an<193>sakti or detachment, the sting or the ç
binding taint, being thus taken away, the very same actions lead to ç
purification of mind and spiritual enlightenment. This is `an<193>sakti-yoga,' ç
yoga or union with God,through an<193>sakti or detachment. This theory ç
thus strikes a balance between karma (activity) and sa<221>ny<193>sa ç
(renunciation), between prav<216>tti (activism) and niv<216>tti (withdrawal). ç
For details see <MS>KARMAYOGA<D>.
See also <MS>BHAGAVADG®T°<D> and<MS> NI<186>K°MA-KARMA<D>.
@NT = an<193>·ramin
@N1 = (`One who has not adopted any <193>·rama')
According to the dharma·<193>stras, the life of an individual is divided ç
into four <193>·ramas or stages of life viz., brahmacarya, g<193>rhasthya, ç
v<193>naprastha and sa<221>ny<193>sa  signifying  the  states  of  a ç
student, house-holder, forest-recluse and monk. It was obligatory ç
for a householder belonging to the first three var<207>as (castes) ç
to maintain sacrificial fire and to offer oblations regularly. The ç
wife also had a place in this ritual and could act as a substitute ç
for her husband in times of need. No greater calamity could befall ç
a householder than the untimely death of his wife. Her body would ç
be cremated with the same fire in which she used to offer oblations. ç
The widower had only two alternatives left: to enter into the next ç
stage of the v<193>naprastha or to marry once again and set up the ç
fire afresh. Anyone who did neither was branded as an `an<193>·ramin,' ç
one who was outside the pale of the <193>·rama scheme. This was incompa-tible ç
with the Vedic scheme of life.
@NT = Anas<220>y<193>
@N1 = (`one without jealousy')
One of the most celebrated women of Hindu mythology, considered as ç
a model of wifely virtues, Anas<220>y<193> was a daughter of Kardama ç
and Devah<220>ti. She was married to the great sage Atri whom she ç
served with intense devotion and love. Once, when there was a severe ç
famine, she saved people by producing vegetables and fruits through ç
her power of tapas (austerity). She even made the river Ga<209>g<193> ç
which had dried up, flow again.
The Trinity (Brahm<193>, Vi<218><207>u and <185>iva) subjected her ç
to a severe test of her chastity from which she emerged successfully. ç
As a reward they were born as her children: Vi<218><207>u as Datt<193>treya, ç
<185>iva as Durv<193>sas and Brahm<193> as Candra.
When R<193>ma and S<200>t<193> visited Atri's hermitage in the da<207><195>aka ç
forest Anas<220>y<193> taught S<200>t<193> the value of devoted service ç
to one's husband as the necessary and sufficient discipline for spiritual ç
welfare.
See also <MS>ATRI<D>.
@SPACE = 
@NT = an<193>tman
@N1 = (`the not-self<|>' or `the non-self<|>')
`Who am I?', `Whence did this world originate?'†these are two of the ç
important questions posed by philosophical inquirers. The Ved<193>nta ç
system of philosophy posits the view that the world has evolved out ç
of the °tman (the Self) and it is the same °tman that is our real ç
nature. Everything else is included under the term `an<193>tman.' ç
Though literally the external world with its myriads of objects is ç
also an<193>tman, the word is used more particularly to denote the ç
body, the sense-organs and the mind which force us to identify ourselves ç
with them, thereby forgetting our °tman-nature.
See also <MS>°TMAN<D>.
@SPACE = 
@NT = <193><207>avamala
@N1 = (`impurity of being atomic')
@SPACE = 
The  <185>aiva  schools  of  philosophy including the P<193>·upata, ç
Pratyabhij<210><193> andthe V<200>ra·aiva, consider <185>iva as the ç
supreme Deity. He is the Pati (the Lord) whereas the j<200>vas (individual ç
souls) are pa·us (animals, the bound ones). Though the j<200>va is ç
similar to <185>iva, the Pa·upati, he is not identical with Him. The ç
difference is rather in quantity than in quality. It is p<193>·aj<193>la ç
(web of bonds) that makes him small, limited, bound, and forces him ç
to transmigrate. The first of these p<193>·as† also known as malas ç
or impurities†is avidy<193> or ignorance which makes him feel he is ç
a<207>u, small, finite and limited. Hence it is called `<193><207>avamala.' ç
Due to this, the j<200>va, though he is pure consciousness, imagines ç
himself finite, confined to the body and of limited knowledge and ç
power.
The other two are k<193>rmamala and m<193>y<200>yamala.
@SPACE = 
@NT = anavasth<193>
@N1 = (`instability,' `non-finality')
This is a technical term specially used in Hindu logic. When the cause ç
and effect series becomes infinite and does not serve as a proof, ç
it is called anavasth<193> (infinite regress) and hence rejected.
This anavasth<193> is sometimes divided into two varieties: pr<193>m<193><207>ik<200> ç
or valid, and apr<193>m<193><207>ik<200> or invalid. For instance, ç
in the series of b<200>ja (seed) and v<216>k<218>a (tree) the infinite ç
regress is valid and natural. Hence it is pr<193>m<193><207>ik<200>. ç
On the other hand, while trying to prove the existence of a cause ç
for this world, if that cause (called Brahman) is accepted to have ç
been caused by something else, it leads to anavasth<193>, infinite ç
regress, and hence to no definite conclusion. This anavasth<193> is ç
apr<193>m<193><207>ik<200> or invalid. (To avoid this, Ved<193>nta ç
accepts Brahman as the uncaused cause.)
@NT = anavasthitatva
@N1 = (`instability')
Pata<210>jali, in his famous work, the Yogas<220>tras (1.30), describes ç
nine anta-r<193>yas or obstacles to the attainment of yoga. Anavasthitatva ç
is the last in the list and also the most formidable one to overcome. ç
With assiduous practice, a yogi can succeed in raising his mind to ç
certain higher states but very soon it slides back to lower ones or ç
reverts into the old rut. Deep-rooted evil tendencies like inordinate ç
lust and love of lucre or mercurial irri-tability or crass selfishness ç
are often responsible for this fall. By dispassionate
