@NID = and deep introspection, consultation with the guru and prayer ç
to God, one can discover the root-cause and eliminate it.
See also <MS>ANTAR°YAS<D>.
@SPACE = 
@NT = °<207><195><193><202>
See <MS>°<170>V°RS<D>.
@SPACE = 
@NT = °<207><195>avan Ma<219>ha
Monasteries known as ma<219>has as also their pontiffs, the ma<219>h<193>dhipatis, ç
have played an important role in preserving Hindu religion and culture. ç
Tapas (austerity) and vidy<193> (learning) have been the bedrock of ç
their spiritual activities.
One of the ma<219>has of recent origin and perhaps less known than ç
its counterparts is the °<207><195>avan Ma<219>ha of <185>r<200>ra<209>gam ç
(Tamil Nadu). The Ma<219>ha belonging to the <185>r<200>vai<218><207>ava ç
tradition and following the Vi·i<218><219><193>dvaita school of Ved<193>nta, ç
originated with <185>r<200>mad Gop<193>l<193>c<193>rya Mah<193>de·ikan, ç
also called Tirukku<195>andai De·ikar, during the middle of the eighteenth ç
century, in Kumbhako<207>am (of Tamil Nadu). He was a man who practised ç
severe austerities and was known for his great scholastic learning. ç
His three disciples, continued the tradition of this great savant ç
without break. <185>r<200>niv<193>sa Mah<193>de·ikan (also known as ç
Periy<193><207>davan), the second of them, was as much a yogi of great ç
powers as he was a monk of austerity and learning. Thepresent pontiff, ç
<185>r<200> Ved<193>nta R<193>m<193>nuja Mah<193>de·ikan (Tirukku<195>andai ç
°<207>davan) the eighth in the order of succession, whowas ordained ç
in 1963 has been working hard to spread the message of his predecessors.
@NT = andhat<193>misra
@EMERGENCY = According to the S<193><209>khyadar·ana, one of the more ç
well-known systems of Hindu philosophy, there are two types of creation: ç
the elemental creation and creation of buddhi. The latter, called ç
pratyaya-sarga, is fourfold: viparyaya (ignorance), a·akti (incapacity), ç
tu<218><219>i (contentment) and siddhi (perfection or powers). Andhat<193>-misra ç
is a subdivision of viparyaya and is manifested as fear of death or ç
self- destruction. Eighteen varieties of this are mentioned. There ç
are five gross objects of pleasure enjoyed through the five organs ç
of perception (e.g., ·abda or sound by ·rotra or ear etc.) and five ç
subtle objects, their counterparts, enjoyed in higher worlds like ç
heaven. There are also eight siddhis or powers like a<207>im<193> ç
(capacity to become atomic in size) and so on. The fear that these ç
siddhis may be lost is andhat<193>misra.
@EMERGENCY = In the Yoga system of Pata<210>jali this is called abhinive·a ç
(excessive attachment or clinging to life).
@EMERGENCY = The words t<193>misra and andhat<193>misra have also ç
been used in the pur<193><207>as to indicate certain hells into which ç
people committing certain types of heinous crimes and sins (like suicide, ç
usurping the wealth and women of other people) are cast.
@NT = °ndhra
@EMERGENCY = Earliest reference to the °ndhras is in the Aitareya ç
Br<193>hma<207>a (33.6) where they are mentioned as one of the low-caste ç
groups along with Pulindas, Pu<207><195>ras and M<220>tibas. These ç
castes were created by the fifty sons of Vi·v<193>mitra as a result ç
of hiscurse. The °ndhras were outcastes subsisting on wild animals.
However, °ndhra as a country and as a people has found mention in ç
the R<193>m<193>ya<207>a, Mah<193>bh<193>rata and some of the pur<193><207>as. ç
The country referred to was that between the rivers God<193>var<200> ç
and K<216><218><207><193>.
The °ndhra country was part of A·oka's empire. The political history ç
of an independent °ndhra starts with the <185><193>tav<193>hanas (280 ç
<F51320P10MSC1>B. C.<W1><192><MS>A. D.<W1> 218). The K<193>kat<200>yas (11th ç
to 14th cent. <MS>A. D.<W1>) were another important dynasty which ç
contri-buted to the cultural development of the °ndhra. However it ç
was under the Vijaya-nagar kings (<MS>A. D.<W1> 1336<192>1556) that ç
specta-cular progress was achieved.
@NT = anek<193>ntav<193>da
@N1 = (`theory of several<R>ç
assertions')
Jaina logic and metaphysics have developed a theory technically called ç
`anek<193>ntav<193>da,' `sy<193>dv<193>da' or `sapta-bha<209>g<200>naya' ç
according to which seven assertions are possible with regard to everything. ç
Though these assertions are seemingly contradictory, they are possible. ç
The theory derives its name from the fact that `ek<193>nta' or one ç
absolute assertion cannot be (`na') made about anything (na+ ek<193>nta ç
= anek<193>nta). Since the possible statements contain the word `sy<193>d' ç
(`may be so'), it is called `sy<193>dv<193>da.' Since the number of ç
such alternatives or possibilities is seven it is also called `saptabha<209>g<200>naya' ç
(sapta = seven, bha<209>g<200> = mode, naya = standpoint; seven modes ç
of expression from different standpoints).
We can now state the theory as follows: The object, like a gha<219>a ç
or jar (1)is (asti); (2) is not, (n<193>sti); (3) is andis not (asti, ç
n<193>sti); (4) is unpredicable (avaktavya); (5)is and is unpredicable ç
(asti, avaktavya); (6)is not and is unpredicable (n<193>sti, avaktavya); ç
(7) is, is not and is unpredicable (asti, n<193>sti, avaktavya).
The word `sy<193>d' (`may be') indicating the possibility is added ç
everywhere (e.g., sy<193>d asti, sy<193>n n<193>sti and so on).
The word <193>sti' (<|>=<|>is) when used with regard to any object affirms ç
its existence from the standpoint of its (sva) r<220>pa (form), dravya ç
(material), k<218>etra (place) and k<193>la (time). Similarly the ç
word `n<193>sti' (= is not) denies that existence from the standpoint ç
of another (para) form, material, place or time. When these two are ç
taken together, it becomes `avaktavya,' unspeakable or unpredicable. ç
For instance, the jar in front of us in this room existsas jar here ç
and now and does not exist as a cloth or elsewhere or at a different ç
time.
The seven possible assertions are obtained by a permutation and combination ç
of the statements (1) to (4).
@NT = a<209>ga
@N1 = (`part,' `limb')
The word which literally means part or a limb, is often used in a ç
technical sense. For instance, in medical sciences it stands for the ç
body or its limb. In Jainism, it stands for a class of scriptures ç
which are twelve in number.
In Vedic sacrifices the word a<209>ga indicates a subordinate rite. ç
For instance, Pa·ubandha is an a<209>ga of Somay<193>ga; orPray<193>ja ç
is an a<209>ga of Dar·a. These subsidiary rites may or may not produce ç
any separate result.
More often the word is used in combination with other words getting ç
a technical flavour. Here are some samples: pa<210>c<193><209>ga, ç
the five parts of an almanac like nak<218>atra or star; r<193>jy<193><209>gas, ç
the seven components of an imperial set-up like the king; sen<193><209>gas, ç
the four parts of an armed force like infantry; Ved<193><209>gas, ç
the six subsidiary branches of knowledge which help the study of the ç
Vedas, like <185>ik<218><193> or the science of articulation; yaj<210><193><209>gas, ç
the vessels used in a sacrifices like sruk and sruva (spoon and ladle) ç
and yog<193><209>gas, the eight steps of yoga like yama or restraint ç
and so on.
A<209>ga has often been mentioned as a country, now identified with ç
eastern Bihar or the region around Bhagalpur in Bihar. <185>iva is ç
said to have burnt Manmatha (Cupid) to ashes here. Since Manmatha ç
was ultimately revived, getting back his a<209>gas or limbs, the place ç
came to be known as A<209>ga or A<209>gade·a. This was once ruled ç
by the well-known king Roma-p<193>da. During his regime there was ç
once a severe famine. When the sage <184><218>ya·<216><209>ga was ç
tactfully brought into the kingdom, it rained heavily and the people ç
were saved from starvation.
The Artha·<193>stra of Kau<219>ilya (2.2) mentions that A<209>ga ç
is famous for well-bred elephants.
In the mythological lore, several kings by name A<209>ga are mentioned: ç
a king who had joined Duryodhana in the Kuruk<218>etra war; a k<218>attriya ç
hero who fought the great king M<193>ndh<193>t<216>; a k<218>attriya ç
king, the eldest son of Bali and Sude<218><207><193>.
Kar<207>a, of the Mah<193>bh<193>rata fame, was the king of A<209>gade·a.
@NT = a<209>ga <M>and<D> li<209>ga
@N1 =  (`that  <|>which<|>  goes towards Brahman' and `that into which ç
everything is dissolved')
In V<200>ra·aivism (one of the important schools of <185>aivism) Brahman ç
is called `Sthala'. `Stha' stands for `sth<193>na' (place) and `la' ç
for `laya' (dissolution). So `Sthala' is that place or source from ç
which the universe evolves and into which it dissolves ultimately. ç
This `Sthala' divides itself out of l<200>l<193> or play into li<209>ga ç
anda<209>ga, also called li<209>gasthala and a<209>gasthala. A<209>ga ç
is the individual soul or j<200>va (so called because he goes back ç
[ga] to Brahman [a<221>] ) and li<209>ga (= that into which everything ç
gets dissolved, l<200>yate) is God, <185>iva. A<209>ga becomes one ç
with li<209>ga in course of time as a result of bhakti, up<193>san<193> ç
or worship. See <MS><186>A<187>STHALA-SIDDH°NTA<D> for details.
@SPACE = 
@SPACE = 
@NT = A<209>gad, Guru
@N1 = (<F51320P10MSC1>A. D.<W1> 1504<192>1552)
@SPACE = 
Sikhism, the youngest of world reli-gions, was started by Guru N<193>nak ç
(<F51320P10MSC1>A. D.<W1> 1469<192>1539). It was nurtured, developed and ç
stabilized by a succession of Gurus up to Guru Gobind Singh (<MS>A. ç
D.<W1> 1666<192>1708) who declared that the sacred book, the <F255P255MIC255>Granth, ç
respectfully called Guru Granth S<193>hib would take the place of ç
the Guru thereafter.
Guru  A<209>gad  was  the  immediate successor of Guru N<193>nak, ç
chosen and anointed by N<193>nak himself. Before ordination his name ç
was Lehna. Lehna who was the son of a trader called Pheru and lived ç
in Khadur in the Punjab was a devotee of Mother Durg<193>. He used ç
to lead pilgrims to the Durg<193> temple and the Jv<193>l<193>mukhi ç
(a volcanic vent nearby). By chance, he once heard the recital of ç
the famous Sikh prayer Japji and diligently sought after its author. ç
When he finally met the Guru N<193>nak his joy knew no bounds.
Then began his long tenure of single- minded and devoted service to ç
his guru. During the period of internship andtraining he endured ç
all the tests, trials and tribulations and earned Guru N<193>nak's ç
confidence and faith in the fullest measure. Much against the opposition ç
of his own wife and two sons, Guru N<193>nak chose Lehna†now called ç
A<209>gad†as his successor and anointed him as the next Guru in <F51320P10MSC1>A.D.<F255P255DC255>1539.<F51320P10MSC1>
A<209>gad, though eminently fitted for the Guru's place, had to contend ç
with the powerful rivalry of Siri Chand, Guru N<193>nak's eldest son, ç
who had started the Ud<193>s<200> sect, a sect with Sikh principles ç
and an ascetic character. In course of time this sect got merged in ç
the general body of the Sikhs, mainly due to Guru A<209>gad's efforts.
Another challenge he had to face was from the orthodox Hinduism. To ç
keep up a distinct character for the Sikhs and Sikhism, he improved ç
upon the Gurumukhi script and committed the hymns of Guru N<193>nak ç
to writing, in that script, making it available to the common folk ç
who got a scripture of their own, in their own language.
A<209>gad further strengthened the two institutions of la<209>gar ç
(free kitchen) and sa<209>gat (regular religious meetings in groups) ç
established earlier by N<193>nak.
@SPACE1 = 
Vigorous preaching of N<193>nak's doctrines, simple life in conformity ç
with those doctrines, building a new town called Goindwal and introduction ç
of physical culture as part of life and religion were his other contributions.
Guru A<209>gad breathed his last in 1552 at the age of forty-eight.
@NT = A<209>gada
A well-known hero of R<193>m<193>ya<207>a, A<209>gada was the son ç
of V<193>l<200> and T<193>r<193>. His exploits are many and varied. ç
When Sugr<200>va was anointed as the king of Ki<218>kindh<193>, A<209>gada ç
was appointed as the yuvar<193>ja, the heir apparent. He was the leader ç
of the group of monkeys that was sent to the south in search of S<200>t<193>. ç
Before the commencement of the war, <185>r<200> R<193>ma had sent ç
him to R<193>va<207>a on a peace mission. Later, when the war was ç
in progress he succeeded in disturbing the sacrifice at Nikumbhil<193> ç
performed by Indrajit. He killed many r<193>k<218>asa heroes of R<193>va<207>a's ç
army during the battles.
There are two more A<209>gadas mentioned in the itih<193>sas: A<209>gada, ç
the first son of Lak<218>ma<207>a and <188>rmil<193>; A<209>gada, ç
a k<218>attriya king, who fought for Duryodhana in the Kuruk<218>etra ç
war.
@NT = a<209>gamejayatva
@N1 = (`shaking of limbs')
Pata<210>jali, the great master of the yoga system, recognizes that ç
the principle `prevention is better than cure' can be and should be ç
applied in the path of yoga also. To facilitate its practice, he has ç
listed nine `antar<193>yas' or obstacles to yoga (Yoga- s<220>tras ç
1.30) and has added another fivein a supplementary list (ibid. 1.31). ç
He calls these as `vik<218>epasahabhuva<199>' (co-existing with mental ç
distractions). A<209>gamejayatva is the third obstacle in this list.
@SPACE1 = 
`A<209>ga' means limb and `ejana' means shaking. So a<209>gamejayatva ç
is shaking or restless movement of limbs. When sorrow, disappointment ç
and despair are not sublimated by discrimination and will-power, they ç
cause tremendous restlessness in the mind. This affects the nervous ç
system, getting reflected in physical restlessness. The aspirant is ç
thus unable to sit steadily on the seat and frequently changes his ç
position. Persisting in the practice of yoga, repetition of pra<207>ava ç
(O<221>) and an attitude of surrender to God will gradually lessen ç
this disturbance.
@NT = a<209>gany<193>sa
@N1 = (`placing on the limbs')
Hindu ritualistic worship has evolved into a well-developed science. ç
Before starting the worship of the deity, all articles used in the ç
process are to be purified, not only physically but also ceremonially. ç
Ny<193>sa is such an act in this process, and means the `placing' ç
of gods or holy words or letters on certain parts of the body. A<209>gany<193>sa ç
is an aspect of this ny<193>sa. Also called `<186>a<195>a<209>gany<193>sa' ç
(<218>a<219> = six, a<209>ga = limb), it involves the ceremonial purification ç
and protection of h<216>daya (heart), ·iras (head), ·ikh<193> (tuft), ç
kavaca (armour, indicated by touching the shoulders with the hands ç
crossed), netratraya (three eyes, including the middle of the eyebrows) ç
and karatala (palm of the hand). The process is sometimes extended ç
to more parts of the body like the feet, navel and so on.
See also <MS>KARANY°SA<D> and<MS> NY°SA<D>.
@NT = A<209>g<193>raka
See <MS>MA<177>GALA<D>.
@NT = a<209>gasthala
See <MS>A<177>GA<D> and<MS> LI<177>GA.<D>
@NT = a<209>gavidy<193>
@N1 = (`science of the limbs')
From the ancient times, the throbbing of the limbs, particularly of ç
the arm andthe eye, has been regarded as the harbinger of coming ç
events, auspicious or otherwise. For men, throbbing of the right side ç
of the body is considered an auspicious sign. For women, the opposite ç
holds good.
Some examples of such prognosti- cations can be given: The fruit indicated ç
by the throbbing of the top of the head is the acquisition of land; ç
of the forehead, the prosperity of the position already occupied; ç
of the region of the eye, death; of the upper arm, union with friends; ç
of the hand, acquisition of wealth; of the back, defeat and so on.
The Matsyapur<193><207>a (ch. 241) advises the placating of br<193>hma<207>as ç
with gifts of gold to ward off the evil effects of such throbbing.
It is interesting to note that the well- known astrological work B<216>hatsa<221>hit<193> ç
of Var<193>hamihira (6th cent. <F51320MS>A. D.<W1>) treats of this subject ç
(in chapter 51) in an entirely different way. When an enquirer wishes ç
to know from the astrologer any information (for instance, about the ç
thief who has stolen his articles), the astrologer has to closely ç
observe the way the enquirer puts the questions touching any of his ç
a<209>gas or limbs in the process in a natural way,and prognosticate ç
the results. For instance, if the enquirer touches his own feet in ç
the process, the astrologer can conclude that the servant is the thief. ç
Of course, time and place of questioning also count.
@NT = A<209>giras
One of the sages we come across, not infrequently, in the Hindu religious ç
literature, is A<209>giras. A number of Vedic hymns are attributed ç
to him. Associated with the fire cult, he is regarded as the first ç
sacrificer and initiator of sacred ritual. In fact, he is said to ç
have discharged the duties of Agni (the fire-god) once when the latter ç
had absconded, and thus saved the world. The mythological works describe ç
him sometimes as a m<193>nasaputra (mind-born son) of Brahm<193>, ç
the Creator and sometimes as having sprung from the sacrificial fire ç
of god Varu<207>a. Vasudh<193>, <185>raddh<193>, Svadh<193> and Sat<200> ç
were his wives. B<216>haspati was one of his sons. The pit<216>- devat<193>s ç
(manes) are also described as his offsprings. The well-known lunar ç
deities R<193>k<193>, Sin<200>v<193>l<200> and Kuh<220> (which are ç
actually phases of the moon) are consi-dered as his daughters.
Extolled for his great virtues, A<209>giras was also a teacher of ç
Brahmavidy<193>, know-ledge of Brahman (the Absolute). This explains ç
his constant association with light, fire and luminous objects, including ç
his identification with the planet Jupiter and a star in the constellation ç
Ursa Major.
He is listed among the Saptar<218>is (the seven sages) of the first ç
Manvantara (the period or age of Manu). He is one of the originators ç
of the gotra system. The °<209>girases, descendants of A<209>giras ç
are stated to be k<218>attriyas by birth and br<193>hma<207>as by ç
profession. They were highly skilled in sacerdotal law, magic and ç
traditional rites.
He is credited with the authorship of a treatise on law (°<209>girasa ç
Sm<216>ti) as also on astronomy.
@NT = °<209>girasa Sm<216>ti
Sm<216>tis are law-books which prescribe the code of conduct for the ç
individual and the society. Out of the several sm<216>tis known to ç
us, °<209>girasa Sm<216>ti is one of the shorter works, but quoted ç
even by authorities like Y<193>j<210>avalkya.
A perusal of the printed texts as also the several manuscripts available ç
now, shows that the verses vary from 32 to 151! The book deals mainly ç
with pr<193>ya·citta or expiation for various forbidden acts like ç
accepting food and drink from antyajas (people of lowest castes), ç
for injuring cows as also for deadly sins. Its views on sat<200> or ç
sahagamana (wife dying on the funeral pyre of her dead husband) have ç
been criticised by other works.
@NT = Angkor Vat
It is now a well-known fact that Hindu culture had spread to countries ç
far beyond the frontiers of the present day India. One such country ç
is Cambodia, nowknown as Kampuchea (`Kamboja' in Sanskrit) in South ç
East Asia. The kingdom of `Kamboja' is said to have been established ç
by one Kambu-Sv<193>yambhuva who had migrated from India; or by a ç
br<193>hma<207>a, Kau<207><195>inya by name, a `disciple' of `A·vatth<193>man.' ç
It had attained stability even by the 2nd-3rd century <F51320P10MSC1>A.<|>D.<W1>
Of the several vestiges of Hindu culture there, Hindu temples are ç
the best. The Angkor Vat is the biggest of such temples discovered ç
in the latter part of the nineteenth century. It was built by S<220>ryavarman ç
II (<F51320P10MSC1>A.D.<W1> 1112-1152), near his capital Angkor Thom.
The Angkor Vat is a Vai<218><207>ava temple of huge proportions built ç
in the Dravi<195>ian style. The temple area is rectangular in shape, ç
surrounded by a moat 195 metres (650 ft.) wide and 3.8 kms. (2<|>1/2 ç
miles) long. The side of the stone-flagged platform is nearly 900 ç
metres (3000 ft.) in length. The temple walls contain carvings from ç
theHindu mythology, mostly from the R<193>m<193>ya<207>a and the ç
Bh<193>gavata. The sculpture shows the effect of the Khmer culture ç
also, original to the land.
@NT = a<209>gula
Out of the several units of length used in the ancient Hindu scriptures, ç
a<209>gula (corresponding to inch) is probably the smallest. It is ç
variously defined as the total length of eight barley grains kept ç
lengthwise side by side; the width of a finger; one-twelfth part of ç
a `vitasti' or span.
In iconography, images are recommended to be prepared according to ç
the`t<193>lam<193>na' system. A `t<193>la' is the measurement of ç
the palm of hand (from the tip of the middle finger to the wrist) ç
and is equal to the length of the face. Each t<193>la is divided into ç
twelve `a<209>gulas.'
@NT = a<207>im<193>
@N1 = (`minuteness')
Acquisition  of  and  mastery  over super- human powers have always ç
fascinated human beings. The Yogas<220>tras of Pata<210>jali, that ç
matchless basic work on the science of yoga, calls such powers `siddhis.' ç
Apart from other methods of obtaining such siddhis as au<218>adhi ç
(drugs) or tapas (austerity), the basic method is to practise the ç
eight steps of yoga leading to sam<193>dhi (trance). When the pa<210>ca-bh<220>tas ç
(the five elements like earth, water etc.) are chosen as the objects ç
of meditation and sam<193>dhi is obtained on them in the prescribed ç
way (vide Yogas<220>tras 3.44) it leads to the acquisition of the ç
eight supernatural powers called a<218><219>asiddhis (ibid. 3.45). ç
A<207>im<193> is the first of these siddhis. As the very name suggests, ç
it is the power to become minute like an `a<207>u' or atom in size. ç
Hanum<193>n is said to have possessed this power.
See also <MS>A<186><187>ASIDDHIS<D>.
@NT = animal sacrifices
Sacrificing an animal to please a supernatural deity is a common feature ç
found in many cultures, including that of Hinduism, during the early ç
part of their development. Though formal animal sacri-fices of the ç
early Vedic period gradually lost their importance, due to the reformatory ç
movements of the Upani<218>adic sages, Jainism and Buddhism, a new ç
type of animal sacrifice got into the fabric of Hinduism during later ç
ages, as aboriginal cultures got integrated into the Hindu fold.
The deity was invariably an aspect of Durg<193> or K<193>l<200> and ç
the rituals were very simple. Buffaloes, goats, sheep and cockerels ç
were the usual sacrificial victims. It was believed that these victims ç
would go to heaven.
Various reform movements have helped to minimise this practice.
See also <MS>NIR<188>£HA PA<185>UBANDHA<D> and<MS> SOMAY°GA<D>.
@NT = A<207>im<193><207><195>avya
A sage by name M<193><207><195>avya was once falsely accused of stealing ç
and was put to death on a spear by the king. But, sincehe was innocent ç
and had accumulated extraordinary powers by austerities, he did not ç
die. When this was noticed, the king was frightened and got him released. ç
He broke the spear but its `a<207>i' or point was firmly imbedded ç
in the sage's body. Hence he came to be known as A<207>im<193><207><195>avya.
Since he had once killed flies as a child, he was taken to the world ç
of Yama after death. But he protested saying that the sin committed ç
by children below four- teen years belongs to their parents. Forhis ç
mistake of forcing the sage to go to his world, Yama was cursed to ç
be born in the human world. He was born as Vidura.
@NT = Aniruddha
@N1 = (`unobstructed')
Aniruddha was the son of Pradyumna and grandson of K<216><218><207>a. ç
U<218><193>, the daughter of B<193><207><193>sura, fell in love with ç
him and got him magically transported to her palace. Though B<193><207><193>sura ç
discovered it and tried his best to destroy him, he did not succeed. ç
Ultimately Aniruddha and U<218><193> were married.
The Bh<193>gavata or the P<193><210>car<193>tra cult(a form of Vai<218><207>avism) ç
considers Aniruddha as one of the four vy<220>has or emanations  of  Lord  Vi<218><207>u.  (See ç
<MS>CATURVY<188>HAS<D>.) Symbolically, he represents the cosmic mind.
See also <MS>P°<178>CAR°TRA °GAMA<D>.
@NT = anirvacan<200>ya, anirvacan<200>ya-khy<193>ti
See under <MS>KHY°TIS<D>.
See also <MS>ADVAITA VED°NTA DAR<185>ANA<D>.
@NT = anitya
@N1 = (`non-eternal')
Time, space and causation are great destroyers. Everything in this ç
created world comes under their sway and hence gets changed, modified, ç
decayed and des-troyed. All such objects are called anitya as opposed ç
to nitya which is the eternal unchanging principle. Hindu philosophical ç
systems generally accept the <193>tman and God as nitya and other ç
things like the external objects or the body as anitya.
See also <MS>NITYA<D>.
@NT = a<210>jalihasta
@N1 = (`with folded hands')
In the Indian iconographical works several mudr<193>s or hastas, poses ç
of the hand, are described for images. Each one of these indicates ç
a particular feeling or sentiment.
In the a<210>jalihasta, the two hands of the image are folded, leaving ç
a hollow between them. The hands thus folded rest on the chest and ç
are kept parallel to the ground.
This pose indicates salutation.
@NT = °<210>janeya
@EMERGENCY = See <MS>HANUM°N<D>.
@NT = a<209>kur<193>rpa<207>a
@N1 = (`offering the germinated seeds')
Building a temple is considered a pious act. Since the temple is a ç
house of God, the construction must be done not only meticulously ç
but also religiously. One of the important religious ceremonies connected ç
with the various stages of construction is `a<209>kur<193>rpa<207>a,' ç
the rite of offering the germinated seeds. It is performed before ç
the construction begins, before laying the last brick or stone (m<220>rdhe<218><219>ak<193>) ç
into the superstructure, prior to the installation of the main image, ç
before the opening of the eyes of the image (ak<218>imocana) and so ç
on.
The rite itself consists of placing the germinated seeds of different ç
varieties of paddy, sesamum, mustard etc., in 16 copper vessels and ç
placing them in front of Soma (the deity presiding over the process ç
of germination).
The main purpose of the rite is to facilitate the fruition of the ç
work without obstacles.
@NT = anna
@N1 = (`food')
Anna or food seems to be a favourite topic dealt with in the Hindu ç
scriptures. The Upani<218>ads have used the word times without number ç
not only in the sense of physical food but also to signify anything ç
that is consumed or enjoyed. It stands for matter in general. In the ç
long process of creation it is the lowest manifestation of the °tman.
Anna nourishes not only the body but also the mind. Hence the stress ç
on purity of food.
The dharma·<193>stras consider even eating as a religious act and ç
give several rules concerning it.
See also <MS>°H°RA<D> and <MS>°H°RA<185>UDDHI<D>.
@NT = anna-homa
@N1 = (`oblation of food')
Among the several Vedic sacrifices A·vamedha and V<193>japeya are ç
among the better known ones. Anna-homa is a subsi-diary rite of these ç
sacrifices. It consists mainly of an oblation of ghee, grains and ç
powder of barley and grains of pounded rice, offered into the sacrificial ç
fire just before sunrise. The oblatory materials however, may sometimes ç
differ.
@NT = annak<220><219>a
@N1 = (`heap of food')
In the D<200>p<193>vali festival which falls during the months of ç
°·vina and K<193>rttika (usually in November), on the third day known ç
as Balipratipad, it is customary to worship the Govardhana hill which ç
is near Mathur<193> (Uttar Pradesh). This is the legendary hill which ç
<185>r<200> K<216><218><207>a as a boy is said to have lifted up on ç
his left little finger to protect the people and cattle of V<216>nd<193>vana ç
from the wrath of Indra who had sent incessant and heavy rains. Those ç
who are not living near this hill are advised to make an image of ç
the hill with cowdung or food. In the latter case, the heap of food ç
(anna = food) is called annak<220><219>a and worship is offered to ç
it.
@NT = A<207><207>am<193>c<193>rya
Saints and mystics who have propagated the cult of devotion to God ç
have played a significant role in the Hindu society. Practically, ç
there is no area or province or section of the Hindu world which does ç
not exult in a saint of its own. The province of °ndhra (present Andhra ç
Pradesh) is one such.
A<207><207>am<193>c<193>rya (<F51320P10MSC1>A. D.<W1> 1424<192>1503) of ç
T<193><202><202>ap<193>kam village in the Cuddapah district of Andhra ç
Pradesh is one such saint who was not only a great scholar in Sanskrit ç
and Telugu languages but also an inspired composer of devotional poetry. ç
Born to N<193>r<193>ya<207>a S<220>ri and Lak<218>mamma in an orthodox ç
br<193>hma<207>a family, he settleddown at Tirupati, a renowned placeof ç
pilgrimage, even in early youth. Having taken initiation in the <185>r<200>vai<218><207>ava ç
tradition from one Vi<218><207>usv<193>min he then studied Ved<193>nta ç
under the then pontiff ofthe Ahobila Ma<219>ha, <185>r<200> <185>a<219>hagopa ç
Yat<200>ndra. He also gained mastery over the Tamil <F255P255MIC255>Prabandhams. ç
He had great devotion to Lord Ve<209>ka<219>e·vara, the presiding ç
deity of Tirupati. It is said that he usedto sing everyday in the ç
early morning before the deity. Even on the last day of his life he ç
did so and then got merged in Him.
According to some popular lores, Purandara D<193>sa (<F51320P10MSC1>A.<|>D.<W1> ç
1484-1564), the musician-saint of Karnataka, is said to have met him ç
at Tirupati and got inspiration from him to compose songs in the vernacular ç
as exercises in music lessons.
A<207><207>am<193>c<193>rya's compositions had been inscribed on copper ç
plates and preserved in the temple of Ve<209>ka<219>e·vara for posterity.
Among his works in Sanskrit are Ve<209>ka<219><193>cala-m<193>h<193>tmyam ç
and Sa<209>k<200>rtana-lak<218>a<207>am. <|>The <|>Telugu <|>works<|> ç
include Dvipada-R<193>m<193>ya<207>a, <185><216><209>g<193>rama<210>jar<200> ç
and Ve<209>ka<219>e·a-·ataka, apart from about 12,000 k<200>rtanas ç
or songs.
@NT = annamaya-ko·a
@N1 = (`the food-sheath')
It is the physical body born out of anna or food and nourished by ç
food. Like a ko·a or sheath, it covers the self and prevents the experience ç
of its true nature. It is the first of the five such ko·as (pa<210>cako·as). ç
It is destroyed at death. It is also called sth<220>la-·ar<200>ra ç
or the gross body, the first of a series of three ·ar<200>ras.
See <MS>PA<178>CAKO<185>AS<D>.
@NT = annapr<193>·ana
@N1 = (`feeding with cooked rice or food')
The Hindu religious works known as dharma·<193>stras consider the ç
life of every Hindu as a religious process. It begins at conception ç
and ends at cremation. The individual's life is to be purified, refined ç
and sanctified continually by certain reli-gious processes called ç
`sa<221>sk<193>ras,' usually translated as `sacraments.' They are ç
sixteen in number. Hence the appellation `<186>o<195>a·a-sa<221>sk<193>ras.'
Annapr<193>·ana is the seventh in the list. It is the first feeding ç
of the child with solid food, starting the process of weaning the ç
child away from breast-feeding. It can be performed any time after ç
the sixth month and before the child completes one year.
The father prepares a food of goat's flesh or flesh of partridge or ç
of fish or boiled rice depending upon the result he expects for the ç
child, like nourishment or holy lustre and so on. One of these is ç
mixed with curds, honey and ghee andthe child is made to taste it ç
with the reciting of certainVedic hymns. Then the father offers oblations ç
to the fire. The mother is to eat the remainder of the food. Homa ç
may also be performed andfeeding of the br<193>hma<207>as may be ç
arranged.
According to some writers, on the day of this ceremony, tools and ç
implements, vessels and weapons are to be spread in front of the gods ç
worshipped in the house and the child allowed to crawl among them. ç
The first object seized by the child is said to indicate its future ç
profession.
See also <MS>SA<189>SK°RAS<D> and<MS> <186>O£A<185>A-SA<189>SK°RAS<D>.
@NT = Annap<220>r<207><193>
@N1 = (`filled with food')
If God is the creator of this universe, his power with which he creates, ç
is pictured as a female deity, his consort, usually called <185>akti. ç
Most of the female deities or goddesses of the Hindu pantheon are ç
aspects of P<193>rvat<200>, the consort of <185>iva, the third deity ç
of the Hindu Trinity, responsible for destruction and dissolution ç
of the universe.
@SPACE = 
@SPACE = 
Annap<220>r<207><193>, the possessor and giver of food, is one of ç
the important aspects of P<193>rvat<200>. She got this name since ç
she served anna or food to Lord <185>iva himself when he was roaming ç
about as a mendicant. She is shown as serving food from a vessel of ç
ruby.
Iconographically, she may be shown with four hands also, two hands ç
holding p<193>·a (noose) and para·u (battle-axe) and the other two ç
showing the varada (boon-giving) and abhaya (protection from fear) ç
mudr<193>s.
@SPACE1 = 
Her worship ensures that the household will never lack food. Her festival ç
is usually observed in Caitra (April), mostly in Bengal.
Her  temple  at  K<193>·<200>  (V<193>r<193><207>as<200>, modern Banaras ç
in Uttar Pradesh) is very famous.
@SPACE = 
@NT = Annap<220>r<207><193> Upani<218>ad
@SPACE = 
This  Upani<218>ad  belongs  to  the Atharvaveda. It is a fairly ç
long work of 337 verses spread over five chapters.
A yogi, Nid<193>gha by name, approaches <184>bhu, the `best among ç
knowers of Brahman,' for Self-knowledge. <184>bhu prefaces his teaching ç
by narrating how his father had taught him the `best of mantras,' ç
`the mantra of Annap<220>r<207><193>' of 27 letters (aimhr<200><221> ç
sau<221> ·r<200><221> kl<200>m o<221> namo bhagavatyannap<220>r<207>e ç
mam<193>bhila<218>itam anna<221> dehi sv<193>h<193>), how he had ç
pleased the Divine Mother Annap<220>r<207><193> by repeating it day ç
after day for a long time, how he had asked for <193>tmaj<210><193>na ç
or Self-know-ledge from her when she appeared before him, and how ç
he had got it by her grace. The name of the Upani<218>ad is derived ç
from this legend.
The rest of the Upani<218>ad is just a long and loose discourse on ç
Advaita philosophy in which many of its aspects have been brought ç
in, though not in a systematic manner.
Apart from the topic of `bhrama' (delusion) and how to overcome it, ç
the Upani<218>ad also deals with topics like v<193>san<193>k<218>aya ç
(destruction of tendencies carried over from the previous lives), ç
manon<193>·a (dissolution of the mind through yogic exercises) and ç
a detailed description of the j<200>vanmukta (`the liberated in life') ç
who never gets affected by the various vicissitudes of life.
@SPACE1 = 
See also <MS>ADVAITA VED°NTA DAR<185>ANA<D> and <MS>UPANI<186>ADS.<D>
@NT = Anna-s<220>kta
@N1 = (`hymn to food')
Anna or food, which is responsible for sustenance, has always been ç
looked upon with reverence in Hinduism. Offering of consecrated food ç
to the sacrificial fire is a common part of some rituals. It is especially ç
so in the ·r<193>ddha (obsequies) ceremonies. In one such ·r<193>ddha, ç
called p<193>rva<207>a<192> ·r<193>ddha, after first consecrating ç
the cooked food meant for oblation into the fire, the rest of the ç
food in the vessel is also purified by the recitation of the Annas<220>kta.
The Annas<220>kta is a series of eleven verses taken from the <184>gveda ç
Sa<221>hit<193> (1.187.1-11). The <216><218>i (the sage to whom it ç
is revealed) is Agastya. The devat<193> (deity to which it is addressed) ç
is Annastuti. The chandas or meter is mostly Anu<218><219>ubh.
According to the sage <185>aunaka (vide <184>gvidh<193>na 1-27) ç
this s<220>kta must be chanted daily at the time of food. Such chanting ç
purifies the food, destroying whatever impurities may be there, and ç
ensures health and energy.
The first verse is introductory. Thesecond verse supplicates food ç
for protection. The third requests food to be palatable. The next ç
three are verses of praise. The seventh verse requests food to be ç
available in plenty when it rains. The next three verses urge the ç
body to grow strong as a result of consuming food. The last verse ç
is a praise to food in the form of Soma.
@NT = an<216>ta
@N1 = (`the not-straight)
The words <216>ta, satya and an<216>ta are frequently used in the ç
Vedic literature,the first two being often used synonymously. If ç
<216>ta stands for `what is straight,' the Truth at its fundamental ç
causal level, for the thing<192>in<192>itself, satya stands for the ç
verbal expression of the same. An<216>ta which may mean the opposite ç
of <216>ta or simply what is not <216>ta is used mostly to indicate ç
untruth, commonly called asatya.Speaking an<216>ta has always been ç
considered as a great sin.
See also <MS>ADHARMA, ASATYA, DHARMA, <184>TA<D> and <MS>SATYA<D>.
@NT = anta<199>kara<207>a
@N1 = (`the inner instrument')
The general name by which mind is known in the Hindu scriptural works ç
is `anta<199>kara<207>a,' the `inner (anta<199>) instrument (kara<207>a).' ç
Even though the external sense-organs like the eye or the ear are ç
functioning, no cognition becomes possible unless the mind is connected ç
with them. Hence the significance of the name.
Among the three states of consciousness viz., j<193>grat (waking state), ç
svapna (dream state) and su<218>upti (deep sleep state),  the  anta<199>kara<207>a  is  actively ç
functioning in the first two and dormant in the third.
This anta<199>kara<207>a functions in four different ways and gets ç
four different names according to the functions. While functioning ç
as the receptive and retentive faculty it is called `citta' or mind-stuff; ç
as the questioning, doubting and willing faculty, it is called `manas' ç
or mind; as the deciding faculty it is called `buddhi' or intelligence; ç
and as the identifying faculty which identifies itself with each of ç
these functions it is called `aha<209>k<193>ra' or the ego.
These words are sometimes used to mean the anta<199>kara<207>a or ç
mind as a whole and sometimes to mean the particular faculty indicated. ç
The sense in which they are used has to be made out from the context.
See also <MS>AHA<177>K°RA, BUDDHI, CITTA, MANAS<D> and <MS>MIND<D>.
@NT = antar<193>la
@N1 = (`that which exists in between')
Temples or houses of God, have been in existence since a long time. ç
The earliest of the Hindu temples as we see them today might have ç
been built during the third or fourth centuries <F51320P10MSC1>A. D.<W1> ç
The most important part of the Hindu temple is the <F255P255MIC255>sanctum ç
sanctorum known as garbhag<216>ha, the `womb House,' housing the ç
image of the deity. Antar<193>la is the narrow passage that connects ç
this garbhag<216>ha to the large hall or pavilion, called ma<207><219>apa ç
which is normally used for congregational religious acts. This antar<193>la ç
is also called ardha-ma<207><219>apa or ·ukan<193>s<200>.
In temple symbology, the antar<193>la represents the neck of the deity, ç
if the whole temple complex represents the bodyof the deity.
@NT = antar<193>yas
@N1-1 = (`those which come in between')
Yoga or union (yuj = to yoke) of the individual self with the Supreme ç
Self can be attained through yoga or perfect concen- tration (yuj ç
= to get sam<193>dhi or superconscious state). All attempts at controllingthe ç
vagaries of the mind†which is constantly rising in the form of v<216>ttis ç
or wave-like  modifications†are  foiled  by antar<193>yas or `intruders' ç
which are actually obstacles in the path of yoga.
Pata<210>jali lists them as nine in number (Yogas<220>tras 1.30): ç
(1) vy<193>dhi or illness; (2)sty<193>na or languor of the mind; ç
(3)sa<221>·aya or doubt; (4) pram<193>da or heedlessness; (5) <193>lasya ç
or laziness of the body; (6) avirati or absence of dispassion; (7) ç
bhr<193>nti-dar·ana or false perception andhallucination; (8) alabdhabh<220>mikatva ç
or non-attainment of yogic states, and (9)anavasthitatva or instability ç
of a yogic state, when obtained.
There  is  a  second  set  of  such antar<193>yas (ibid. 1.31) which ç
`coexist with mental distractions' and are hence called `vik<218>epa-sahabhuva<199>.' ç
They are five: (1)du<199>kha or sorrow; (2) daurmanasya or disappointment; ç
(3) a<209>gamejayatva or restlessness of limbs; (4) ·v<193>sa or forcible ç
inhalation, and (5)pra·v<193>sa or forcible exhalation.
All these disturb the mind and hence prove to be obstacles to the ç
attainment of yoga.
For details, see under each title separately.
@SPACE = 
@NT = antardh<193>natva
@N1 = (`the capacity to become invisible')
Pata<210>jali, the great teacher of Yoga, has described in his Yogas<220>tras ç
several siddhis or miraculous powers, which a yogi can obtain through ç
sa<221>yama. The practice of dh<193>ra<207><193> (fixing the mind ç
on the object of meditation) and dhy<193>na (continuous flow of the ç
mind<192>stuff towards it) ending in sam<193>dhi (superconscious experience) ç
is called sa<221>yama.
When the yogi practises sa<221>yama upon the inherent capacity of ç
his own body to be seen by others, thus controlling it, and by arresting ç
its function, he becomes invisible to others. This siddhi is called ç
antardh<193>natva. See Yogas<220>tras 3.21.
@NT = antardhauti
@N1 = (`internal cleansing')
The science of Ha<219>hayoga prescribes `dhauti' or cleansing of the ç
body to make it pure, healthy and strong so that it can withstand ç
the rigours of R<193>jayoga. This is one of the several techniques ç
and is offour kinds: antardhauti, dantadhauti, h<216>d-dhauti and ç
m<220>la·odhana.
Antardhauti, the first of these, is again of four kinds: v<193>tas<193>ra, ç
v<193>ris<193>ra, vahnis<193>ra or agnis<193>ra and bahi<218>k<216>ti.
In v<193>tas<193>ra, the purification is effec-ted by inhaling air ç
(v<193>ta = air) by shaping the lips like the beak of a crow, filling ç
up the stomach with it and expelling it through eructation.
In v<193>ris<193>ra, warm saline water (v<193>ri= water) is drunk ç
and expelled through the rectum. This is later on followed by vamana-dhauti, ç
drinking saline water and vomitting it.
In vahnis<193>ra, navel knot is pressed against the spinal cord by ç
exhalation and contraction of the muscles of the stomach.
Bahi<218>k<216>ti is similar to v<193>tas<193>ra except that the air ç
is expelled through the rectum instead of through the mouth.
These techniques not only purify the body but also free it from diseases. ç
However, they should be practised only under the personal guidance ç
of an expert ha<219>hayogi.
See Ghera<207><195>a Sa<221>hit<193> 1.14-22 for details.
@NT = antarik<218>a
@N1 = (`that which contains stars,' the sky)
The region pervading the space in between the earth (bh<220>loka) ç
and the heavens, (dyuloka or svarga), is called antarik<218>a. It ç
is also known as bhuvarloka. According to the <184>gveda, Indra ç
or V<193>yu is the presiding deity of this region. Sometimes a few ç
more deities are assigned to this region: Ap<193>m Nap<193>t, Aja-ekap<193>t, ç
Rudra,  Maruts,  Parjanya  and  °pa<199> (waters).
@NT = antarvedi
@N1 = (`inside the sacrificial altar')
The tract of land between the rivers Ga<209>g<193> and Yamun<193>, ç
stretching from Pray<193>ga (modern Allahabad) to Hardv<193>r (or ç
Hardwar) has often been called by thisname. It has been regarded ç
as a sacred region and the principal seat of `°rya-br<193>hma<207>as,' ç
br<193>hma<207>as who were ideal in character and fit to be emulated ç
by others. It has also been called `samasthal<200>,' `·a·asthal<200> ç
and `brahm<193>varta.'
`Antarvedi' is also the name of a place of pilgrimage situated on ç
the bank of the river God<193>var<200>.
@NT = Antary<193>mi Br<193>hma<207>a
The B<216>had<193>ra<207>yaka Upani<218>ad which forms an important ç
part of the <185>atapatha Br<193>hma<207>a of the <185>ukla Yajurveda ç
is by far the biggest of the extant Upani<218>ads. The <185>atapatha ç
Br<193>hma<207>a is found to be in two ·<193>kh<193>s or recensions, ç
the K<193><207>va and the M<193>dhyandina. Hence the Upani<218>ad ç
also is found to have two recensions.
The seventh section†each such section is known as a `br<193>hma<207>a'†of ç
the third chapter of this Upani<218>ad is called Antary<193>mi Br<193>hma<207>a ç
since it deals with the topic of Brahman as the antary<193>min (`the ç
indwelling spirit').
The third chapter starts with the convening of a conference of `knowers ç
of Brahman' by the king Janaka of Videha, who expresses a desire to ç
know the best among them (brahmi<218><219>ha), and offers rich presents. ç
The sage Y<193>j<210>avalkya comes forward to take away the presents ç
even before proving his mettle in the assembly. This naturally enrages ç
the assembled sages who start challenging him with intricate philosophical ç
queries. However, Y<193>j<210>avalkya proves more than a match for ç
all of them.
The seventh br<193>hma<207>a†which is the Antary<193>mi Br<193>hma<207>a†starts ç
with the question of Udd<193>laka °ru<207>i about the antary<193>min ç
or the indwelling spirit in the universe. Y<193>j<210>avalkya replies ç
that it is the °tman or the Self that resides in everything, whether ç
it is the elements like the earth, or the worlds like heaven or living ç
beings or sense organs or mind, and controls them all from within. ç
He knows them but they know him not. He is actually the knower and ç
can never become an object of perception or knowledge. He is the eternal ç
Self of all.
If the K<193><207>va·<193>kh<193> stops with this, the  M<193>dhyandina·akh<193>  continues  the ç
description and adds `ya <193>tmani ti<218><219>han...' (`who, remaining ç
inside the <193>tman...') which lends strength to the belief that ç
the <193>tman (the individual self) and Brahman (the Supreme Self) ç
are different and that the latter controls the former. This comes ç
in handy for the dualistic schools like Vi·i<218><219><193>dvaita ç
Ved<193>nta to defend their position.
@NT = antary<193>min
@N1 = (`One who controls from within')
According to the Upani<218>ads, Brahman is both the immanent and the ç
transcendent Reality. Having created the world, Brahman enters into ç
it (vide Taittir<200>yopani<218>ad 2.6) and controls it from within ç
(vide B<216>had<193>ra<207>yakopani<218>ad 3.7.3-23). In this aspect ç
itis called the `antary<193>min,' the inner controller.
In Advaita Ved<193>nta, the individual self is ultimately identical ç
with the antar- y<193>min. But in Dvaita and Vi·i<218><219><193>dvaita, ç
the two are different.
In the P<193><210>car<193>tra school of Vai<218><207>a-vism, God manifests ç
himself in four forms retaining the para or the highest form in his ç
world called Vaiku<207><219>ha: vy<220>ha (the four emanations), vibhava ç
(incarnations), arca (manifestation through the image during worship) ç
and antary<193>min (the inner controller). According to this school, ç
the last is only a partial manifestation.
@NT = antyaja
@N1 = (`the last-born')
Division of society based on the nature and nurture of the individuals ç
as also their professions is a phenomenon found in many parts of the ç
civilized world. In the special context of India's ancient history ç
when races and cultures battled and blended, this division also took ç
a unique shape. This is known as the `j<193>tipaddhati' or caste system. ç
J<193>ti also means birth. Since children usually adopted the professions ç
of their fathers and forefathers, caste came to acquire a functional ç
character in a self-contained economy and a social structure, based ç
on traditional values.
The var<207>a system from which caste is supposed to have originated ç
was a simple division based on gu<207>a (natural characteristics) ç
and karma (action, acts, vocation). This gradually developed into ç
a labyrinth of j<193>tis and upaj<193>tis or castes and sub-castes ç
most of which were grouped under an umbrella term called the `·<220>dras.' ç
Even among such castes, a few were pushed to the lowest rung of the ç
social ladder because of their unclean food habits and amoral attitude ç
which were unacceptable to the rest of society. Hence the name `antyaja' ç
(`the last-born'). Probably for the same reason they were also considered ç
asp<216>·yas  or  untouchables.  However, neither in the Vedas nor ç
in the earlier sm<216>tis and dharma·<193>stras have they beentreated ç
as such, but only as ·<220>dras. The practice of untouchability seems ç
to be a post-Vedic phenomenon.
Some  of  the  castes  branded  as antyajas are: ca<207><195><193>la, ç
rajaka (the washerman), carmak<193>ra (worker in hides), buru<195>a ç
(bamboo worker), kaivarta (the fisherman) and bhilla (of a forest-tribe ç
or a hill-tribe).
During the medieval ages, these castes had often risen in social status ç
due to their organization and wealth.
Though caste barriers have existed in some form all along at social ç
levels, birth in a low caste has never been considered a bar to spiritual ç
enlightenment as depicted in the story of Dharmavy<193>dha (vide  Mah<193>bharata,  Vanaparva,  210). ç
Indian history is replete with stories of great saints, who, though ç
born as antyajas, rose to very high spiritual states and were recognized ç
and respected as such by the society. To mention only a few: Ka<207><207>appa, ç
Raid<193>s, Cokkame<202>a, Nandan<193>r and Tirupp<193><207>i.
@SPACE1 = 
Eradication of untouchability which is a social curse, has been attempted ç
by several religious and social leaders in India throughout the centuries. ç
The success, however, has not been proportionate to the efforts put ç
forth. Economic, educational and cultural upliftment of the masses ç
is the only solution to this social malady. Since independence the ç
Indian Constitution has positively forbidden the observance, in any ç
form, of untouchability and these socially disabled communities arebeing ç
given special consideration in matters of education and employment, ç
and, many economic benefits.
See also <MS>ASP<184><185>YAT°<D>.
@NT = anty<193>vas<193>yin
@N1 = (`decided as the last')
Apart from the four var<207>as or groups of people in the society, ç
a very large number of j<193>tis or castes which have come into being ç
as a result of mixing up of these var<207>as, have been mentioned ç
in the Hindu religious works. The names of most of these castes actually ç
indicate their vocations and often, the status of the caste group ç
depended upon the type of profession followed by it.
The groups considered almost as outside the pale of the caste system ç
were called `antyajas' (`the least-born) and those considered as the ç
last even among them were named `anty<193>vas<193>yins,' for instance, ç
ca<207><195><193>las and ·vapacas (eaters of dog's flesh). They were ç
considered as untouchables even among the untouchables and used to ç
live in cemeteries. They were disqualified from appearing as witnesses ç
in legal disputes.
@NT = antye<218><219>i
@N1 = (`the last sacrifice')
According to the dharma·<193>stras, a Hindu is expected to lead his ç
life reli- giously. At every stage of his life he is expected toperform ç
or undergo certain religious ceremonies which will add a peculiar ç
excellence not only to his body but also to his mind and spirit. This ç
is technically called `sa<221>sk<193>ra' (purificatory rite or sacrament). ç
Out of the sixteen such sa<221>sk<193>ras  (called  <218>o<195>a·a-sa<221>sk<193>ras) ç
antye<218><219>i is the one that comes at the very end. It is the ç
grand finale of a life that has been well-lived.
As the very name indicates (antya = end, death) it is performed on ç
the death of a person, by his survivors, usually the sons or the nearest ç
male relatives. Since cremation seems to have been the general rule ç
among the Vedic °ryans, it was considered as a sacrifice (i<218><219>i ç
= sacrifice). It was believed that Agni, the fire-god, who acted as ç
a messenger between gods and men, would lead the soul of the dead ç
to the next world.
@SPACE1 = 
On the approach of death, the person who is expecting to die shortly, ç
bids farewell to the assembled relatives and the world. Alms and gifts ç
are distributed. Oblations are offered into the sacrificial fire maintained ç
by him. In the modern days dropping the water of Ga<209>g<193> and ç
tulas<200> leaves into his mouth are in vogue. The body is removed ç
in a bier specially prepared and taken in a procession to the cremation ç
ground, being led by the chief mourner (usually the eldest son). A ç
cow is let free on this occasion. She is called `anustara<207><200>' ç
and is believed to be helpful in crossing the ocean of mortality. ç
The corpse after washing is laid on thepyre and fire is applied with ç
appropriate Vedic mantras (like <184>gveda Sa<221>hit<193> 10.16.1). ç
After udakakarma (offering of water) and consoling the mourners, the ç
nearest relatives observe a·auca (ceremonial impurity) usually for ç
three days. Later on, the bonesare gathered (asthisa<210>cayana) ç
and immersed in a holy river or the sea. <185>r<193>ddha ceremonies ç
are followed by sapi<207><195><200>kara<207>a (affiliation of the ç
dead with the manes).
@NT = a<207>u
@N1 = (`the atom,' `atomic')
The smallest part of a physical substance which cannot be divided ç
further, is called a<207>u (and sometimes, param<193><207>u). According ç
to the Vai·e<218>ika system of philosophy, the four elements viz., ç
earth, water, air and fire are atomic in size. The perceptible elements ç
are formed out of a combination of these atoms.
The Vi·i<218><219><193>dvaita Ved<193>nta and the P<193>·upata system ç
of <185>aivism consider the <193>tman (the individual soul) as a<207>u ç
or atomic in size.
The word is sometimes used to indicate a minute unit of time also: ç
54,675,000th part of a muh<220>rta (of 48 minutes). In prosody it ç
is the fourth part of a m<193>tr<193> (syllabic instant).
@NT = anubandha-catu<218><219>aya
@N1 = (`four-fold<R>ç
connection')
Works on Advaita Ved<193>nta usually commence with the description ç
of the anunbandha-catu<218><219>aya. Anubandha is that which connects ç
or binds, the factors which bind the entire system together into a ç
connected whole. There are four such factors and hence the word `catu<218><219>aya' ç
(a group of four).
The first anubandha is `adhik<193>rin,' the person competent to study ç
and practise the science. The second is `vi<218>aya,' the subject ç
matter dealt with in the treatise. The third is `prayojana,' utility ç
to be gained by its study and practice. The last is `sambandha'   or   connection,    usually ç
between the book that purports to deal with the science and the science ç
itself, or, between the work and the utility promised.
Though this is used as a `technical word' in Advaita literature, it ç
is a general concept that can be applied to other fields of knowledge ç
also.
@NT = an<220>bandhy<193>
@N1 = (`bound, following [the<R>ç
sacrifice]')
Towards the end of the Agni<218><219>oma sacrifice, after the udayan<200>ya ç
rite, a barren cow used to be immolated and sacrificed tothe gods ç
Mitra and Varu<207>a. This cow was called anu(<220>)bandhy<193>. Sometimes ç
three barren cows used to be sacrificed to Mitr<193>-Varu<207>a, Vi·vedevas ç
and B<216>haspati, as inV<193>japeya, R<193>jas<220>ya and Sattra ç
y<193>gas. Substitutes of p<193>yasam (pudding) and <193>mik<218><193> ç
(curdled milk) have also been mentioned, even in the earlier works. ç
Sacrifice of these cows has been given up long since.
See also <MS>AGNI<186><187>OMA, R°JAS<188>YA, UDAYAN®YA<D> and <MS>V°JAPEYA<D>.
@NT = A<207>ubh<193><218>ya
@N1 = (`the tiny commentary')
The Upani<218>ads contain the highest flights of Hindu philosophical ç
thought. Sincethey are not the works of a single author and do not ç
appear to propound a single system of philosophical thought, B<193>dar<193>ya<207>a-Vy<193>sa ç
undertook to streamline and systematize their thoughts through  his  well-known  work  called ç
Brahmas<220>tras. (See <MS>BRAHMAS<188>TRAS<D> for details.) This ç
work, being in the form of aphorisms, could not be easily comprehended ç
without the aid of a suitable commentary. Since it commanded a great ç
respect in the Hindu philosophical tradition, several <193>c<193>ryas ç
(spiritual and reli-gious preceptors) owing allegiance to different ç
thought systems, wrote expositions on it, attempting to show that ç
it expounds their system of philosophy. Among such <193>c<193>ryas, ç
<185>a<209>kara, R<193>m<193>nuja and Madhva have been considered ç
the chief ones.
Madhv<193>c<193>rya (<F51320P10MSC1>A. D.<W1> 1238-1317) the chief exponent ç
of the Dvaita Ved<193>nta (dualistic Ved<193>nta) is reputed to have ç
written four works on the <F255P255MIC255>Brahmas<220>tras: the Brahmas<220>trabh<193><218>ya, ç
Anuvy<193>khy<193>na, Ny<193>yavivara<207>a and A<207>ubh<193><218>ya.
The A<207>ubh<193><218>ya, as the very name indicates, is a very ç
small (a<207>u = tiny) metrical work comprising 32 ·lokas (verses) ç
in the simple anu<218><219>ubh metre, divided into four chapters of ç
8 ·lokas each. This is said to have been composed by Madhva for the ç
convenience of his disciples who were in the habit of reading the ç
entire bh<193><218>ya on the Brahmas<220>tras before taking their ç
food.
The first chapter expounds the greatness of Lord Vi<218><207>u, who ç
is the source of all beings and things. The second chapter brings ç
out the untenability of interpretations of the Upani<218>a<195>ic ç
passages by other schools like the S<193><209>khya. The third chapter ç
extols j<210><193>na (knowledge of God) and advises the aspirants ç
to eschew evil deeds and perform only good deeds. An important doctrine ç
that is set forth here is that there is gradation even in mukti (liberation). ç
The last chapter describes ways of attaining mukti.
@SPACE1 = 
A<207>ubh<193><218>ya is also known as Sarva-·<193>str<193>rtha-sa<209>graha  and  has  several ç
commentaries by Jayat<200>rtha, Ananta Bha<219><219>a, R<193>ghavendra ç
T<200>rtha and others.
Vallabh<193>c<193>rya  (<F51320P10MSC1>A. D.<W1>  1481<192>1533) another ç
of the well-known <193>c<193>ryas of the pluralistic schools, has ç
written a commentary on the <F255P255MIC255>Brahmas<220>tras called A<207>ubh<193><218>ya ç
which, again, has a few sub-commentaries.
@NT = anud<193>tta
@N1 = (`not raised')
The Vedic Sa<221>hit<193>s have been preserved for millennia due to ç
the well-orga-nized system of `svaras' or intonations. Such svaras ç
are of three types: ud<193>tta, anud<193>tta and svarita. They are ç
generally translated as `raised,' `not raised' and `falling.' They ç
are musical in nature.
The anud<193>tta is indicated by a horizontal line below the letter, ç
the ud<193>tta without any sign and the svarita with a vertical line ç
above the letter. For instance: O<221> saha n<F49W1>b<F255D><193>vavatu. ç
Here `sa' is an anud<193>tta and `n<F49W1>b<F255D>a' is a svarita. The ç
other letters are all ud<193>tta.
While chanting, the ud<193>tta letters are chanted as the basic note ç
(`sa' or <218>a<195>ja of music), the anud<193>tta as one note below ç
(`ni' or ni<218><193>da) and the svarita as one note above (`ri' or ç
<216><218>abha).
@NT = Anug<200>t<193>
@N1 = (`following the G<200>t<193>')
The  immense  popularity  of  the Bhagavadg<200>t<193>†generally ç
known as the G<200>t<193>†inspired a number of authors of didactic ç
literature to produce more such works. Most of these are imitations ç
and are almost always incorporated into bigger works like the epics ç
and the pur<193><207>as. There are as many as thirty six such g<200>t<193>s, ç
out of which sixteen are from the Mah<193>bh<193>rata alone. Anug<200>t<193> ç
is one such and perhaps better known than the others. The name `Anug<200>t<193>' ç
is derived from the fact that it purports to follow (anu<|>=<|>following) ç
the G<200>t<193>.
The Anug<200>t<193> comprises chapters<%-3> <%0>16-51 of the fourteenth ç
book (°·vamedhikaparva) of the Mah<193>bh<193>rata and is in the ç
form of a dialogue between <185>r<200> K<216><218><207>a and Arjuna. ç
Being eager to recapitulate the teachings of the Bhagavadg<200>t<193>, ç
Arjuna requests <185>r<200> K<216><218><207>a for the same. After ç
taking Arjuna to task for having forgotten the teaching so soon and ç
confessing that he is not in a high state of yoga now, <185>r<200> ç
K<216><218><207>a gives him another set of teachings, mostly by reciting ç
stories and dialogues that took place between sages of yore.
The topics dealt with in this g<200>t<193> can be briefly indicated ç
as follows: the travels and travails of the j<200>va or the individual ç
soul, karma and rebirth, means of attaining mok<218>a or liberation, ç
j<210><193>nayaj<210>a or knowledge compared to a sacrifice, a description ç
of the pr<193><207>as or vital airs, the greatness of the antary<193>min ç
or the inner controller, spiritual experience described with the allegory ç
of a forest, story of Para·ur<193>ma, description of the three gu<207>as ç
and their effects, creation, greatness of spiritual wisdom, duties ç
of people in the four <193>·ramas, individual and Supreme selves, ç
nature of austerity, nature of <193>tman or Self.
The section comprising the chapters 20-34 is called Br<193>hma<207>ag<200>t<193> ç
since it was taught by an enlightened br<193>hma<207>a to his wife.
@NT = anugraha-m<220>rti
@N1 = (`icon showing favour')
Temples and image worship have had a long history in Hindu religion ç
and culture. Each of the three main cults of Hinduism, viz., <185>aivism, ç
<185><193>ktaism and Vai<218><207>avism has given rise to a variety ç
of icons during the course of its evolution. One set of such icons ç
pertaining especially to Lord <185>iva, showing benediction to hisdevotees ç
is called `anugraha-m<220>rti.' Iconographical works record six such ç
anugraham<220>rtis, m<220>rtis or icons showing anugraha or benediction ç
to Ca<207><195>e·a (one of the attendants of <185>iva), Nand<200>·vara ç
(<185>iva's mount), Vi<218><207>u, Vighne·vara or Ga<207>e·a, Arjuna ç
(the P<193><207><195>ava hero) and R<193>va<207>a (the demon king ç
of La<209>k<193>). One hand of the image is usually kept on the head ç
of the supplicant while one of the other hands exhibits abhayamudr<193> ç
(protec- tion<192>giving pose) or varadamudr<193> (boon-giving pose).
@NT = anukrama<207><200>, anukrama<207>ik<193>
@N1 =  (`coming in order')
The Vedas, the basic scriptures of Hinduism, grew in volume in course ç
of time to such a proportion that it became very difficult to retain ç
them in memory. Realizing this, sages like <185>aunaka and K<193>ty<193>yana ç
composed special works which gave tables of contents of the Vedas ç
as also index of hymns and words. Such works are called `anukrama<207><200>' ç
or `anu-krama<207>ik<193>.' They usually give the first words of Vedic ç
hymns, names of <216><218>is (sages) and chandas (metre) as also of ç
the devat<193>s (deities) arranged in the same manner as they occur ç
in the originals.
<185>aunaka is said to have written ten such works on the <184>gveda, ç
like °r<218><193>nu-krama<207><200>, Chando'nukrama<207><200> and ç
Deva-t<193>nukrama<207><200>. The famous B<216>haddevat<193> is ç
included in this series.
The anukrama<207><200> literature pertaining to the <184>gveda has ç
been greatly enriched by the Sarv<193>nukrama<207><200> of another ç
sage K<193>ty<193>yana. This is an excellent compendium of all indices ç
in one place. K<193>ty<193>yana is reputed to have written an anukrama<207><200> ç
on the <185>ukla Yajurveda also. Atri and C<193>r<193>y<193><207>a ç
have authored two independent anukrama<207><200>s on the K<216><218><207>a ç
Yajurveda.
S<193>maveda has two anukrama<207><200>s: °r<218>a and Daivata.
The anukrama<207><200> literature of the Atharvaveda is called `pari·i<218><219>a' ç
(appendix). Of the 70 pari·i<218><219>as known to exist,Cara<207>avy<220>ha, ç
the 49th, is the most celebrated.
All these works are mostly written in either the ·loka (metrical, ç
verse) or the s<220>tra (aphorism) style.
See also <MS>B<184>HAD-DEVAT°<D>.
@NT = anuloma
@N1 = (`with the hair or grain')
Anything that is the prescribed or accepted order is termed `anuloma' ç
as opposed to `pratiloma' (`opposed to the hair or grain') which indicates ç
the reverse order. The word is widely used with regard to marriages ç
and castes. An anuloma marriage is one in which the male is of a higher ç
caste than the female. Offsprings of such unions belong to a set of ç
castes called anuloma castes.
In the pratiloma marriage the male is of a lower caste than the female ç
and the offsprings belong to pratiloma castes.
@NT = anum<193>na
@N1 = (`to measure or draw conclusions, following [a given premise]'<|>)
Indian systems of philosophy have paid considerable attention to the ç
problem of knowledge and the means of obtaining it. The object to ç
be known is called `prameya' (`that which is measured or known'), ç
the means of knowing it is `pram<193><207>a' (`the measure') and the ç
know-ledge obtained thus is `pram<193>' (`that which is measured').
The pram<193><207>as accepted by the various schools vary from two ç
to six. However, almost all the theistic schools are agreed on three ç
of them and consider them as more basic. They are: pratyak<218>a (direct ç
perception), anum<193>na (inference) and <193>ptav<193>kya (testimony), ç
the <193>gama or scriptural  testimony  being  considered  the highest ç
in the last category.
When smoke is seen on a distant hill, though fire itself is not seen ç
directly, we conclude that there is fire on the hillsince smoke is ç
invariably associated with fire. Here, the means of our know-ledge ç
of fire on the hill is `anum<193>na' or inference. We are measuring ç
(m<193> = to measure) or knowing the object of know-ledge (fire), ç
following (anu = to follow) a given premise (i.e., the smoke and the ç
invariable concomitance of smoke with fireknown to exist from our ç
earlier experiences).
Some technical terms commonly used while defining anum<193>na are: ç
`s<193>dhya' (what is to be proved; here, the fire), `hetu' (the cause ç
for such inference; here, smoke) and `pak<218>a' (that which takes ç
a side, or causes doubts; here, the hill).
See also <MS>PRAM°ØAS<D>.
@NT = Anumati
@N1 = (`approval')
There are several Vedic sacrifices performed on different days, determined ç
by the phases of the moon. The moon rising on the 15th day of the ç
bright fortnight, which is still associated with the 14th day (caturda·<200>), ç
will have one kal<193> or digit less. It is said that i<218><219>is ç
(sacrifices) performed on that day are received favourably by the ç
gods and manes. In Vedic literature the day itself is personified ç
as the goddess Anumati. She is to be propitiated with oblations at ç
a certain stage during the R<193>jas<220>ya sacrifice.
See also <MS>R°JAS<188>YA<D>.
@NT = anupalabdhi
@N1 = (`non-perception')
Out of the six pram<193><207>as (means of obtaining knowledge) accepted ç
by the (Bh<193><219><219>a) M<200>m<193><221>s<193> and the Advaita ç
Ved<193>nta systems of Indian philosophy, anupalabdhi or non-perception ç
forms the last. It is one of the five sources of non- perceptual knowledge.
According to the M<200>m<193><221>s<193> epistemo-logy of Kum<193>rila ç
Bha<219><219>a, the non-perception of an object is a source of our ç
immediate cognition of the non-existence (abh<193>va) of that object. ç
For instance, how is the non-existence of a jar on the table in front ç
of us, known? It is known from the absence of its cognition, since, ç
being a negative fact, it cannot be perceived through the senses.
Can we not get this knowledge through anum<193>na or inference? Why ç
should we accept an additional source of knowledge? No, we cannot; ç
because there is no concomitant relationship between non-perception ç
and non-existence, as for instance in the case of non-perception in ç
the dark. Hence anupalabdhi as an additional  means  of  knowledge  must  be ç
accepted. However, it is to be noted that if a thing would have been ç
perceived under given circumstances, but not perceived, then only ç
its anupalabdhi or non-perception becomes a proof of its non-existence. ç
Such anupalabdhi is sometimes called `yogy<193>nupalabdhi.'
See also <MS>PRAM°ØAS<D>.
@NT = anup<193>taka
@N1 = (`secondary sin')
Human beings are generally prone to commit sins due to certain basic ç
weaknesses inherent in the psycho-physical system. For instance, hunger ç
and sex or passions and prejudices. When they are not sublimated or ç
controlled or not let out through outlets approved by dharma (righteousness ç
or religious laws) sin will result. A sin is generally termed `p<193>taka,' ç
that which makes one fall (pat = to fall), from the ideal.
The sm<216>tis and dharma·<193>stras have categorised the sins in ç
various ways. Anup<193>taka is one such, considered less than mah<193>p<193>taka ç
(grievous sin) but in effect  almost  approaches  it.  False accusations ç
against one's guru (father or preceptor) and sexual relationship with ç
women like the wife of a learned br<193>hma<207>a or those seeking ç
one's protection are two such sins.
A sin must be expiated. Various kinds of expiations known as pr<193>ya·cittas ç
are prescribed for the various crimes. As regards the anup<193>takas, ç
the pr<193>ya·cittas are almost the same as the ones prescribed for ç
the mah<193>p<193>takas. Performing A·va-medha sacrifice and visiting ç
places of pilgrimage are prominently mentioned in this list of pr<193>ya·cittas ç
for the anup<193>takas.
See also <MS>P°TAKA<D> and <MS>PR°YA<185>CITTA<D>.
@NT = An<220>r<193>dh<193>
@N1 = (`causing welfare')
An<220>r<193>dh<193> (also `Anur<193>dh<193>') is the 17th of the ç
27 nak<218>atras or constellations of stars listed in Hindu astronomy. ç
The stars comprising this nak<218>atra are beta, delta and pi Scorpii. ç
In Hindu astrology it is considered as benefic. Persons born under ç
this will be good, compassionate, soft spoken and happy. The day on ç
which the moon is associated with this nak<218>atra is considered ç
as auspicious for religious rites and good undertakings.
See also <MS>NAK<186>ATRA<D>.
@NT = Anu·<193>sana-parva
Also called °nu·<193>sanika-parva, this is the thirteenth book of ç
the great epic Mah<193>bh<193>rata containing lengthy expositions ç
on dharma. For details, See <MS>MAH°-BH°RATA<D>.
@NT = anu·aya
@N1 = (`left over [even] after<R>ç
[experience]')
Hinduism believes in the theory of karma (actions) and punarjanma ç
(reincarnation). As a result of pu<207>ya (meritorious deeds), the ç
j<200>va (the individual) is said to go to svargaloka (heaven) or ç
candraloka (the lunar world) and return to the earth after the merit ç
is used up. Even after this pu<207>ya is exhausted, there are other ç
karmas still left over, which will fructify and give the j<200>va ç
further births and experiences. Such residual karma is called anu·aya.
The word is sometimes used in the sense of pa·c<193>t-t<193>pa or ç
repentance.
See also <MS>PR°RABDHA-KARMA<D>.
@NT = anustara<207><200>
@N1 = (`[a] secondary [animal] that is spread over')
An old cow which is set free during the funeral rites and which is ç
believed to help the deceased to cross the Vaitara<207><200> (afetid ç
river between the earth and naraka or the nether world) is technically ç
called anustara<207><200>.
Since the root `st<216>' has the sense of `spreading,' anustara<207><200> ç
may also refer to an old cow which is immolated during the funeral ç
rites, dissected and its various limbs spread on the dead body. This ç
practice, however, ceased to exist long back.
The anustara<207><200> is sometimes called r<193>jagav<200> also.
See also <MS>ANTYE<186><187>I<D>.
@NT = anuv<193>da
See <MS>ARTHAV°DA<D>.
@NT = anuv<193>ka
@N1 = (`saying after')
Literally the word means `reciting' (the Vedas) `after' or `following' ç
the teacher. Hence it refers to the recitation of the Vedas in general. ç
However, it is used in a more technical sense, to indicate a division ç
of the Vedic mantras.
The <184>gveda Sa<221>hit<193>, the basic scripture of Hinduism, ç
is divided into ten books each of which is called `ma<207><195>ala.' ç
Each ma<207><195>ala is again divided into several subsections called ç
anuv<193>kas. The anuv<193>kas are further subdivided into s<220>ktas, ç
each s<220>kta containing one or more <216>ks (verses). There are ç
85 anuv<193>kas in the <184>gveda.
<185>aunaka has prepared an index for these anuv<193>kas, known as ç
Anuv<193>k<193>nu-krama<207><200>.
@NT = anuv<193>ky<193>
@N1 = (`to say after')
Performance of Vedic rites involves several complex processes. Appropriate ç
Vedic hymns selected from the various sections of the Vedas (mostly ç
from the <184>gveda Sa<221>hit<193>) have to be chanted or sung ç
at certain specified stages during these rites. Such hymns are categorized ç
as y<193>jy<193>, anuv<193>ky<193>, ·astra and so on.
The anuv<193>ky<193> hymns†also called puronuv<193>ky<193>†are to ç
be chanted by the hot<216> (priest reciting the <216>ks) when the ç
adhvaryu (priest following the Yajurveda) cuts the puro<195><193>·a ç
(cakes for offering) into several parts. They are actually invitations ç
to the respective deities to accept the offerings allotted to them. ç
Since the name of the particular deity appears in the first part of ç
the hymn, the hymn itself is also called puronuv<193>ky<193> (puras ç
= first, in front). For instance, <184>gveda 8.44.12 and 1.91.11 ç
are used as anuv<193>ky<193>s.
See also <MS>Y°JY°<D> and <MS><185>ASTRA<D>.
@NT = a<207>uvrata
@N1 = (`the atomic vow')
Jainism lays a great emphasis on the practise of moral and ethical ç
virtues. This emphasis is often on the negative rather than on the ç
positive side. For instance, in the practice of ahi<221>s<193> (non-violence) ç
the stress is on non-injury rather than on love. The basic idea behind ç
this attitude seems to be the great and urgent need to restrain those ç
evil propensities at the individual level which, if unchecked, will ç
lead to chaos and conflict at the social level.
Anyone desirous of obtaining kaivalya (spiritual emancipation) should ç
strive to develop sa<221>yak-c<193>ritrya (virtuous conduct) by avoiding ç
evil deeds which generate sin. Five such disciplines which help counter ç
the five basic human weaknesses are listed as follows: ahi<221>s<193> ç
(not harming others), am<216><218><193> (not uttering falsehood), ç
asteya (not stealing), amaithuna (not engaging in sexual intercourse) ç
and aparigraha (not accepting gifts). Am<216><218><193> and amaithuna ç
are sometimes termed satya and brahmacarya.
When these disciplines are to be practised almost to an absolute degree†as ç
in the case of the monks†they are called `mah<193>vratas' or `the ç
great vows.' However, the  householders  whose  capacity  and opportunity ç
to practise these disciplines are restricted by the very nature and ç
circumstances of their life, are permitted certain exceptions. For ç
example, violence or injury to beings which is inevitable while earning ç
one's livelihood or in day-to-day activities like cooking, is tolerated. ç
Similarly the householder is allowed to enjoy conjugal happiness with ç
his wife. So, in his case these vratas become `a<207>uvratas' or `the ç
small vows.'
Nevertheless, even the householder is advised to gradually intensify ç
and perfect the practise of these vows.
@SPACE1 = 
Pata<210>jali, the great teacher of yoga, also has accepted this division ç
(vide Yogas<220>tras 2.1) by implication.
@SPACE = 
@NT = Anuvy<193>khy<193>na
@SPACE = 
The Ved<193>nta Dar·ana, considered to be the crown-jewel of all the ç
Hindu philosophical systems, is based on the three basic works known ç
as `prasth<193>na-traya.' Prasth<193>natraya comprises the Upani<218>ads, ç
the Brahmas<220>tras and the Bhagavadg<200>t<193>. Any philosophical ç
or reli-gious system, to be acceptable to the Hindutradition, had ç
to acknowledge the authority of these three works, or at least, not ç
contradict them.
Of these three works, the Brahma-s<220>tras, also known as the Ved<193>ntas<220>tras ç
or <185><193>r<200>rakas<220>tras, is a compendium of Upani<218>adic ç
thoughts presented in a syste-matic manner. Since the s<220>tras (aphorisms) ç
of this work are as enigmatic as they  are  laconic,  several  sages  and ç
savants have tried to expound their true meaning and purport through ç
erudite commentaries.
One of the more important savants who have composed such commentaries ç
on the Brahmas<220>tras is Madhv<193>c<193>rya (<F51320MS>A. D.<W1> 1197<192>1276) ç
also known as °nandat<200>rtha. He is the first ac<193>rya (teacher) ç
to syste-matize the dvaita school of Ved<193>nta, based on the prasth<193>natraya.
Madhv<193>c<193>rya is reputed to have composed  four  commentaries  on  the ç
Brahmas<220>tras:  Brahmas<220>tra  Bh<193><218>ya, Anuvy<193>khy<193>na, ç
Ny<193>yavivara<207>a and A<207>ubh<193><218>ya.
@SPACE1 = 
It is said that Anuvy<193>khy<193>na, the second work, was composed ç
by Madhv<193>-c<193>rya at the instance of Trivikrama Pa<207><195>ita, ç
one of his more important disciples, who was not satisfied with the ç
Bh<193><218>ya  since  it  was  not  sufficiently polemical.
The  Anuvy<193>khy<193>na,  a  metrical master-piece in 900 verses ç
is a highly polemical work which subjects all other schools of interpretation ç
opposed to the dvaita system to a ruthlessly critical examination. ç
The most celebrated work of Jayat<200>rtha (<F51320MS>A.<|>D.<W1> 1345-1388), ç
the <F255MI>Ny<193>ya-sudh<193>, is actually a commentary on the Anuvy<193>khy<193>na. ç
The work closely follows the Brahmas<220>tras, chapter by chapter, ç
in its essential logical position.
The more important topics discussed may be briefly summed up as follows: ç
O<209>k<193>ra is the designation of Brahman and the purport of the ç
Vedas; God is supremely independent and the whole creation depends ç
upon Him; all bondage is real; the universe is real; but emancipation ç
is possible by the grace of God.
The work devotes a major part to the criticism of Advaita Ved<193>nta.
See also <MS>BRAHMAS<188>TRAS, DVAITA-VED°NTA-DAR<185>ANA,   JAYAT®RTHA<D>   and ç
<MS>MADHV°C°RYA<D>.
@NT = anuvyavas<193>ya
@N1 = (`after-cognition')
Indian philosophical systems, called dar·anas, have analyzed the phenomenon ç
of knowledge in all its aspects. Out of the several pram<193><207>as ç
or means of knowledge, pratyak<218>a or direct perception is universally ç
accepted and placed as the first in the series.
When a pot is seen by the eyes and the knowledge <%12>`<%0>This is ç
a pot' arises in the mind, such a knowledge is called vyavas<193>ya  or  determinate  cognition. ç
However, this is immediately followed by another knowledge `I know ç
this pot' thus relating the earlier knowledge to the self. Since this ç
vyavas<193>ya or cognition rises after the first, it is termed `anuvyavas<193>ya' ç
(anu = after).
This is a later doctrine developed by the Ny<193>ya school.
See also <MS>PRAM°ØAS<D>.
@SPACE1 = 
@NT = anuy<193>ja
@N1 = (`after-offering')
@SPACE = 
Among the few sacrifices that an <193>hit<193>gni  (one  who  has  ceremonially ç
kindled the Vedic fires) is expected to perform regularly, Dar·a and ç
P<220>r<207>am<193>sa should specially be mentioned. They belong to ç
the class called `i<218><219>i' (needing four priests) and are performed ç
on the new-moon day and full-moon day respectively.
During these sacrifices, certain minor offerings are made before and ç
after the principal offerings. Such offerings made before the principal ç
ones are called pray<193>jas (pra = before) and those made after the ç
principal ones are termed anuy<193>jas (anu = after).
The pray<193>jas are oblations of <193>jya (clarified butter or ghee) ç
and are five in number,  addressed  to  deities  like samidha<199>, ç
nar<193>·a<221>sa and others.
The anuy<193>jas are only three and offered to barhis, nar<193>·a<221>sa ç
and agni svi<218><219>ak<216>t.
The word is sometimes spelled as an<220>y<193>ja also.
See also <MS>DAR<185>A-P<188>RØAM°SA<D>.
@SPACE1 = 
@NT = anv<193>dheya
@N1 = (`given after')
@SPACE = 
Str<200>dhana or a woman's property is an important topic discussed ç
by the writers of the dharma·<193>stras. A perusal of Vedic and early ç
dharma·<193>stra literature reveals that women had an honoured place ç
in the Hindu society. References are not wanting to show that they ç
were given gifts and endowed with property of which they could be ç
independent owners (<184>gveda 10.85.13 and 38; °pastamba Dharmas<220>tras ç
2.6.14.9).
Among the five or six varieties of str<200>dhana mentioned, anv<193>dheya ç
is one. It is generally defined as what is obtained by a woman after ç
(anu = after) her marriage, from the family of her husband as also ç
from the family of her father's kinsmen. It could include all kinds ç
of movable property.
See also <MS>STR®DHANA<D>.
@SPACE1 = 
@NT = anv<193>h<193>rya
@N1 = (`that which is made up')
@SPACE = 
In the Dar·a-p<220>r<207>am<193>sa sacrifice the yajam<193>na (sacrificer) ç
is advised to gift away cooked rice as sacrificial fee to the priests ç
after cooking it on one of the fires, the dak<218>i<207><193>gni. ç
This is meant to offset whatever defects might have been accrued to ç
the sacrifice due to errors of omission and commission. This is called ç
anv<193>h<193>rya.
Since anv<193>h<193>rya is cooked on the dak<218>i<207><193>gni, the ç
latter is also called anv<193>h<193>rya-pacana.
A monthly ·r<193>ddha (religious rite in honour of the departed ancestors) ç
performed immediately after pi<207><195>apit<216>yaj<210>a is also ç
called anv<193>h<193>rya.
See <MS>PIØ£APIT<184>YAJ<178>A<D> also.
@SPACE1 = 
@NT = anv<193>h<193>rya-pacana
@SPACE = 
See <MS>ANV°H°RYA<D> and <MS>DAK<186>IØ°GNI<D>.
@NT = anva<218><219>ak<193>, anva<218><219>akya
@N1 = (`after the<R>ç
a<218><219>aka')
Performing religious rites in honour of the departed ancestors and ç
to satisfy their spirits is a universal phenomenon. In Hinduism such ç
rites are called `·r<193>ddha' (literally, that which is performed ç
with ·raddh<193> or faith). The anva<218><219>ak<193>, also called ç
anva<218><219>akya, is a ·r<193>ddha rite per- formed after the a<218><219>ak<193> ç
rite (anu = after).
After establishing the fire and erecting a shed round it, offerings ç
like boiled rice, pudding, preparations made out of curds as also ç
liquor and scum of boiled rice are spread over barhis (sacrificial ç
grass). After offering some portion into the fire, the rest are dedicated ç
to the manes and their wives. The meat of an animal immolated on the ç
a<218><219>ak<193> day should be cooked and offered to the br<193>hma<207>as ç
invited for the ceremony.
The a<218><219>ak<193> type of ·r<193>ddhas gradually went out of ç
vogue.
See also <MS>A<186><187>AK°, PIØ£APIT<184>YAJ<178>A<D> and<MS> <185>R°DDHA<D>.
@NT = anvaya
@N1 = (`following or succession')
The two words, anvaya and vyatireka, are frequently used in Indian ç
works of philosophy and logic to prove a point. They invariably go ç
together. Anvaya is a positive statement indicating a universal agreement ç
whereas vyatireka is the opposite of it, proving the same point by ç
indicating the universal absence of the contrary.
To illustrate: Smoke is seen on the yonder hill. We conclude that ç
there is fireon that hill. This conclusion is based on  two  premises  from  our  previous ç
experience: (1)Wherever there is smoke, there is fire; (2)Wherever ç
there is no fire, there is no smoke.
Of these, the first one is a positive statement, asserting the presence ç
of fire wherever there is smoke. Hence it is calledanvaya-vy<193>pti, ç
or simply anvaya. The second statement asserts a negative factor, ç
the universal absence of smoke when there is no fire. This is called ç
vyatireka-vy<193>pti or vyatireka (negation or contrariety). To prove ç
the existence of fire on the hill on the evidence of smoke, both these ç
methods of argument are necessary.
@NT = <193>nv<200>k<218>ik<200>
@N1 = (`science of reflecting after')
Ancient works on polity often mention <193>nv<200>k<218>ik<200> as ç
one of the four sciences tobe taught compulsorily to the princes, ç
especi-ally the one who will become the next king. Literally the word ç
means something to be reflected upon (<200>k<218> = to reflect) after ç
(anu= after) hearing about the same from the preceptor. Hence, the ç
earliest connotation seems to be `philo- sophy,' the same as was later ç
on known as `dar·ana.'
However, the word has been used in later literature more exclusively ç
to denote the logical sciences, tarka·<193>stra or Ny<193>ya.
@NT = anvit<193>bhidh<193>na-v<193>da
@N1-1 = (`theory of related words')
See <MS>ABHIHIT°NVAYA-V°DA.<D>
@NT = anyath<193>khy<193>ti
See <MS>KHY°TIS<D>.
@NT = anyath<193>siddha
@N1 = (`proved or demonstrated otherwise')
One of the topics considered to be very important and hence frequently ç
discussed in the works of Indian philosophy and logic is the relationship ç
between k<193>ra<207>a, the cause and k<193>rya, the effect. With ç
regard to a given effect, determining its cause or causes, both primary ç
and subsidiary, is of great significance since the same methods of ç
logic will have to be extended to determine the final cause of this ç
universe.
A given effect might have been produced by a single cause or several ç
causes. Again, among these several causes one might be primary and ç
the others secondary. To illustrate: a pot is a k<193>rya or effect. ç
Its k<193>ra<207>as or causes are clay, potter's wheel, stick and ç
the potter himself. Though all these are causes, clay is the primary ç
cause and all the others are secondary causes. What is common to all ç
these causes is that they are immediately antecedent to the effect, ç
the pot. However, any other thing, merely by its being antecedent ç
to the pot, cannot be considered as its cause. For instance, the ass ç
that brings the clay, the sound made by the potter's wheel or the ç
stick or the potter's father†none of these can be considered as the ç
cause of the pot since its coming into existence can be demonstrated ç
otherwise i.e., without reference to this parti-cular cause also. ç
Such causes are said to be anyath<193>-siddha (anyath<193> = otherwise, ç
siddha = demonstrated), and hence rejec-ted as superfluous.
@NT = anyony<193>bh<193>va
See <MS>ABH°VA<D>.
@NT = anyony<193>·raya
@N1 = (`mutual dependence')
Dar·anas  or  Indian  philosophical systems often take recourse to ç
disputing the claims of other schools, to establish their own. In ç
order to achieve this they have to resort to logic and reasoning, ç
arguments and counter-arguments, pushing their opponent to a dead ç
end or a vicious circle. Such positions are accepted as fallacious ç
and hence invalidated.
Anyony<193>·raya (mutual or reciprocal dependence) is one such defect. ç
To illustrate: If the body is produced by karma, how is karma produced? ç
By the body of course! Or, when I look at this pot and get the knowledge ç
that this is a pot, how did I obtain it? By seeing it. How could I ç
get that knowledge unless I had recognized it as a pot? That means, ç
I must have already known it as a pot!
To sum up:
A situation in which a concept cannot be understood without reference ç
to another which in turn cannot be understood without reference to ç
the first, is a position of `anyony<193>·raya' or mutual dependence ç
which is held to be a defect in reasoning.
Works on logic sometimes go into details or categorisation of this ç
fallacy, which however do not add to our basic knowledge of the concept ç
as such.
@NT = apaciti
@N1 = (`paying respect')
The dharma·<193>stras, treatises on law and code of conduct, specify ç
that six types of people should be shown due honour and respect, by ç
a householder. They are: <193>c<193>rya (teacher), <216>tvik (officiating ç
priest), r<193>jan (the king), sn<193>taka (one who has just finished ç
Vedic studies), ·va·ura (father-in-law), pit<216>vya (paternal uncle) ç
and m<193>tula (maternal uncle).
The reception given in their honour is called `apaciti' or `argha' ç
and consists of offering a seat to sit on, p<193>dya (water for washing ç
feet), arghya (water for washing hands), <193>camana (water for rinsing ç
mouth) and madhuparka (a preparation of honey and other ingredients).
See also <MS>MADHUPARKA<D>.
@SPACE1 = 
@NT = <193>pad-dharma
@N1 = (`conduct [permitted<R>ç
during] calamities')
@SPACE = 
If there is any word which is repea-tedly and most extensively used ç
in the Hindu (as also Jaina and Buddhist) reli-gious works, it is ç
the word `dharma.' Out of the several connotations that have evolved ç
over the centuries, `code of conduct' and `duty and responsibility' ç
are two which have been more widely accepted.
This interpretation has been almost universally applied to the var<207>a-dharmas ç
(See <MS>VARØ°<185>RAMA-DHARMA<D>.) and <193>·rama dharmas. Members ç
of each of the four var<207>as (br<193>hma<207>as, k<218>attriyas, ç
vai·yas and ·<220>dras) have been allotted their respective duties ç
and responsibilities; as for instance, Vedic studies and preaching ç
for the br<193>hma<207>as, fighting and administration for the k<218>attriyas ç
and so on. They are normally expected to follow these avocations. ç
However, in times of great calamities like war, floods or famine, ç
when the whole social fabric becomes disturbed, or during a period ç
of severe crisis in the individual's life, it may not be strictly ç
possible for them to do so.
At such periods of <193>pad or calamity, the dharma·<193>stras allow ç
people to take to any dharma or avocation, even the onesallotted ç
to others, as an emergency measure, to sustain themselves. Thus a ç
br<193>hma<207>a can take to fighting or trade, or a k<218>attriya ç
to agriculture or commerce. Both may accept menial service under others. ç
However, even in dire calamities one is advised not to accept service ç
under evil persons. As soon as normalcy returns they are expected ç
to go back to the original way of life.
Since life is most precious, to save it in times of grave danger, ç
one can transgress all normal rules. Vi·v<193>mitra's readiness to ç
consume the flesh of a dog after stealing it from the house of an ç
outcaste during a severe famine is the classic example quoted in mythological ç
works to illustrate this point.
See Manusm<216>ti 10.98-118 for a few interesting details.
See also <MS>DHARMA<D>.
@NT = apade·a
@N1 = (`that which is pointed out')
In the Ny<193>ya and Vai·e<218>ika dar·anas, the systems of Indian ç
logic, a five- membered syllogism is often resorted to, to prove a ç
point. They are: (i) pratij<210><193> (statement of assertion); (ii) ç
hetu (reason for the assertion); (iii) ud<193>hara<207>a (example ç
containing a universal proposition); (iv)upanaya (application to ç
the case on hand); and (v)nigamana (conclusion).
Out of these, hetu, the second member, is sometimes designated as ç
`apade·a.'
The syllogism can be illustrated in that order as follows: (i) R<193>ma ç
is mortal; (ii)because he is a man; (iii) All men are mortal; (iv) ç
R<193>ma is also a man; (v)Therefore he is mortal.
See also <MS>HETU<D>.
@NT = Ap<193><221>-nap<193>t
@N1 = (`offspring of waters')
Hindu tradition accords <184>gveda Sa<221>hit<193>, its basic scripture, ç
the most venerated place. Out of the several deities mentioned and ç
supplicated in its hymns, Ap<193>m-nap<193>t is a comparatively minor ç
deity.
He is a form of Agni, the god of fire though sometimes he is also ç
described as separate from him. He is perhaps the presiding deity ç
of lightning. He is said to reside even inside water. He is pictured ç
as the child of three goddesses of water. Wearing a coat of lightning ç
he shines like gold.
Sometimes, as is the general trend in the <184>gveda, he is identified ç
with Supreme God and the whole world is said to have been manifested ç
out of him. He is the personification of all powers and the repository ç
of all blessed qualities. He is to be praised through laudatory hymns ç
and pleased through sacrificial rites.
@NT = ap<193>na
@N1 = (`breathing out')
Pr<193><207>a, the vital force that bestows life and energy to the ç
body, is responsible for all its activities. Though one, depending ç
upon the various functions it discharges, it is often described as ç
five-fold: pr<193><207>a, ap<193>na, vy<193>na, sam<193>na and ud<193>na.
Ap<193>na, the second in the series is that aspect of the vital force ç
which flows downward (below the navel) and is respon- sible for the ç
function of the excretory organs.
See also <MS>PR°ØA<D>.
@NT = ap<193><209>kteya
@N1 = (`unfit to be included in the row')
From the most ancient times the Hindus have believed that mind is ç
a product of the food we take, even as the body is, and that purity ç
of food is conducive to the purity of mind (vide Ch<193>ndogya Upani<218>ad ç
7.26.2). As a corollary of the doctrine it was also believed that ç
food handled by persons of doubtful integrity could be defiled and ç
the same had to be purified by appropriate rites. The doctrine seems ç
to have been further extended to declare that certain classes of people, ç
if they were allowed to sit in the same pa<209>kti (row of people ç
sitting for food), could defile the whole row and hence were branded ç
as `ap<193><209>kteya' or unworthy of being allowed to sit in the ç
row along with others.Sometimes they were also called `pa<209>ktid<220><218>akas,' ç
those who defile the row.
Though the dharma·<193>stras have given long lists of persons who ç
are ap<193><209>kteya, the lists vary from book to book. Manusm<216>ti ç
(3.150-166) by far gives the longest list, of 93 persons.
A perusal of these lists shows that persons who have given up their ç
allotted duties (var<207>adharmas) and have taken to other means of ç
livelihood, perpetrators of heinous crimes, patients suffering from ç
incurable or infectious diseases, those addicted to drinks and debauchery ç
as also the others who do not follow even elementary principles of ç
ethics and etiquette have all been stigmatized as ap<193><209>kteyas.
@NT = Ap<193>ntara-tamas
@N1 = (`one who has dispelled the inner darkness')
An ancient sage, classed among the Brahmar<218>is, he is said to have ç
been manifested out of the word `bh<220><199>' uttered by Lord N<193>r<193>ya<207>a. ç
Since V<193>c or word is identified with the goddess Sarasvat<200>, ç
he is also said to be S<193>rasvata or son of Sarasvat<200>. Lord ç
N<193>r<193>ya<207>a commanded him to edit the Vedas and propagate ç
them in each manvantara (age of Manu). It washe who was later on ç
reborn as K<216><218><207>a Dvaip<193>-yana or Vedavy<193>sa during ç
the Dv<193>para-yuga. Pr<193>c<200>nagarbha and Ved<193>c<193>rya ç
are two other names by which he is known.
See also <MS>VEDAVY°SA<D>.
@SPACE = 
@NT = apar<193>nta-j<210><193>na
@N1 = (`knowledge of the little end, i.e., death')
@SPACE = 
Hinduism advocates a cyclic theory of creation. S<216><218><219>i ç
(creation), sthiti (preservation or sustenance) and pralaya (dissolution) ç
go on in a cyclic order eternally. Pralaya or dissolution of the created ç
universe is also called `par<193>nta,' `the great end.' Compared to ç
this, dissolution or death of the body of an individual is `apar<193>nta,' ç
`the little end.' Apar<193>ntaj<210><193>na is thus the knowledge ç
of one's death.
Can one get it in advance? If so, how? This interesting question has ç
been answered by Pata<210>jali (200 <F51320P10MSC1>B. C.<W1>) in his celebrated ç
work, the <F255P255MIC255>Yogas<220>tras (3.22). If a yogi succeeds in ç
attaining sam<193>dhi (perfect  concentration  culminating  in superconscious ç
experience) on the karma that has brought him into being in the present ç
life, he can intuitively perceive when it will come to an end. This ç
can give him a direct knowledge of the time, place and mode of his ç
death.
The yogi can obtain the same know-ledge even without sam<193>dhi on ç
his karma, just by observing the ari<218><219>as (portentous phenomena) ç
like not hearing the usual internal sound when the ears are closed, ç
or seeing the dead ancestors or supernatural beings. Though these ç
ari<218><219>as can be perceived even by ordinary people, it is only ç
the yogi that can interpret them rightly and draw correct conclusions.
@NT = Apar<193>jit<193>
@N1 = (`the unconquered')
Man casts God in his own mould. He cannot help doing it since it comes ç
to him naturally. Again, if God is given a human form and conceived ç
of as the Father, why not as the Mother? This seems to be the psychology ç
behind the cult of the <185>akti or the Dev<200>, the Divine Mother.
Most of the forms of <185>akti are associated with P<193>rvat<200>, ç
the divine spouse of Lord <185>iva. Apar<193>jit<193> (literally, ç
one who is unconquered and unconquerable) is one such aspect. Works ç
on Hindu iconography describe her as a very strong woman with three ç
eyes, with her hair made up as a crown and adorned with the crescent ç
moon, and with four arms holding pin<193>ka (<185>iva's bow), arrow, ç
sword and shield. The snake V<193>suki forms her wristlet. She rides ç
a lion.
The Dev<200>m<193>h<193>tmya, which forms a part of the M<193>rka<207><195>eya ç
Pur<193><207>a, contains a beautiful hymn titled `Apar<193>jit<193>-stotra' ç
(5.8-82) sung by the gods led by Indra, to appease her so that she ç
condescends to kill the demons <185>umbha and Ni·umbha. Kings were ç
expected to worship her on the Vijayada·am<200> day. They would then ç
be assured of victory in battles.
The deity is known to Jaina mytho-logy also wherein she is pictured ç
as a yak<218><200> (demi-goddess).
The seventh day in the bright fortnight of Bh<193>dra (usually September) ç
is observed as Apar<193>jit<193> Saptam<200> vrata, fasting being ç
an important part of the discipline.
@NT = Apar<193>nta
See <MS>MADHYADE<185>A<D>
@NT = apar<193>-prak<216>ti
@N1 = (`the lower prak<216>ti or<R>ç
nature')
Creation of the world is a favourite topic discussed in the Hindu ç
scriptures. Most of the schools mentioned in these works are inclined ç
to accept three basic realities from which the world has been created ç
or evolved. They are: ®·vara or God, j<200>vas (the individual souls) ç
and prak<216>ti (nature, the insentient matrix of the inanimate creation).
The Bhagavadg<200>t<193>, though not a treatise on philosophy, in ç
its wide sweep of discussing all relevant topics, touches upon the ç
subject of creation also. God creates the world out of his twofold ç
prak<216>ti or nature:the par<193>-prak<216>ti or higher nature and ç
the apar<193>-prak<216>ti or lower nature. The former comprises the ç
j<200>vas whereas the latter consists of the three gu<207>as, sattva, ç
rajas and tamas. Thus the apar<193>-prak<216>ti forms the material ç
base from which all non-living creation emerges. (vide Bhagavadg<200>t<193> ç
7.4-14)
See also <MS>GUØAS, K<186>ARAPURU<186>A, M°Y°<D> and <MS>PRAK<184>TI<D>.
@NT = Apar<193>rka
The life of an average Hindu, even today, is influenced, if not guided, ç
by the class of works known as dharma·<193>stras. Even the law-courts ç
are guided by them, especially  in  cases  of  Hindu  family disputes.
The dharma·<193>stras comprise a large body of religious literature ç
based on the sm<216>tis (secondary scriptures based on the·rutis ç
or Vedas), the g<216>hyas<220>tras (aphoristic works dealing with ç
the family life), the dharmas<220>tras (aphoristic works dealing with ç
dharma, both at the indi-vidual level and at the social level) asalso ç
the several commentaries and compendia or digests based on them.
Apar<193>rka or Apar<193>ditya (12th cent <F51320P10MSC1>A.D.<W1>) is one ç
of the writers of such literature. He has composed a voluminous commentary ç
in verse, on the well-known sm<216>ti of Y<193>j<210>avalkya. It is ç
later than the <F255P255MIC255>Mit<193>k<218>ar<193>, the most celebrated ç
commentary on the same by Vij<210><193>ne·vara (circa <F51320MS>A. D.<W1> ç
1120), more voluminous but less renowned than the same.
Apar<193>ditya was a king of the <185>il<193>h<193>ra dynasty whose ç
territory existed in the region  of  modern  S<220>rat  and  Th<193>n<193> ç
(Maharashtra State).
His work is more in the nature of a digest than a commentary on the ç
Y<193>j<210>a-valkya Sm<216>ti. He quotes profusely from earlier ç
works and often comments on the same. Though he does not mention the ç
Mit<193>k<218>ar<193> by name, the latter's views come in for criticism.
See also <MS>MIT°K<186>AR°, VIJ<178>°NE<185>VARA<D> and <MS>Y°J<178>AVALKYA-SM<184>TI<D>.
@NT = apar<193>-vidy<193>
@N1 = (`lower knowledge')
From the most ancient times know-ledge has been highly eulogised in ç
the Hindu  scriptures.  Its  acquisition  and dissemination have been ç
considered as a sacred duty, especially of the br<193>hma<207>as.
One of the more well-known and earlier Upani<218>ads, the Mu<207><195>aka ç
(1.1.4, 5), classifies vidy<193> or knowledge into two groups: par<193>, ç
the higher and apar<193>, the lower. Only spiritual wisdom that gives ç
a direct experience of the imperishable Brahman, the Absolute, is ç
classed as par<193> and all other branches of knowledge, whether they ç
are sacred or secular, are relegated to the lower plane as apar<193>-vidy<193>.
It is interesting to note that even the <184>gveda, the most highly ç
venerated scripture tops the list of apar<193>-vidy<193>s. Other arts ç
and sciences mentioned, include grammar, poetics, and astronomy.
Another Upani<218>ad which is equally revered and perhaps even more ç
ancient, the Ch<193>ndogya (vide 7.1.1-3), gives a much longer ç
list starting from the <184>gveda and ending with magical sciences. ç
By impli-cation, these vidy<193>s have to be classed under apar<193>.
@NT = aparigraha
@N1 = (`non-acceptance')
Spiritual illumination resulting in kaivalya or liberation is the ç
final goal of life. This is possible only when a sinless life is led ç
and efforts are assiduously made to purify the mind. Out of the several ç
disciplines advocated in the Hindu reli-gious works towards this end, ç
aparigraha (non-acceptance of things) is an important one. The Yogas<220>tras ç
of Pata<210>jali (2.30 and 39) has mentioned it under the first of ç
the eight graded steps of yoga, viz., yama.
A yogi or a spiritual aspirant, who has dedicated his life entirely ç
for spiritual illumination, is advised not to accept gifts of material ç
things from others, nor make efforts to obtain them otherwise, beyond ç
the bare necessities of life. This means, he has to consciously keep ç
in check, greed and the desire to possess and enjoy the possession ç
of objects. This is facilitated by constant reflection on the difficulties, ç
risks, and evils involved in obtaining such objects or protecting ç
them.
It is interesting to note that Pata<210>jali assures<|><|>that<|><|>the<|><|>yogi ç
<|>who<|><|>observes  this
