@NID = vow sincerely, can develop, in course of time, the supersensual ç
knowledge about his previous and future lives.
@NT = aparok<218>a
@N1 = (`not mediate')
@NT = aparok<218><193>nubh<220>ti
@N1 = (`not-mediate-experience')
Ak<218>an means a sense-organ like the eye or the ear. Parok<218>a ç
means that which is removed from the sense organ, hence, indirect. ç
Aparok<218>a is that which is opposed to this, i.e., direct. All knowledge ç
obtained through inference and verbal testimony isparok<218>a. Compared ç
to it, knowledge obtained by direct perception is aparok<218>a.
However in the strictest sense, even such knowledge is parok<218>a ç
or indirect only, since the sense organs and the mind intervene between ç
the knower and the object known. `Aparok<218><193>nubh<220>ti' or ç
`immediate and direct experience' is possible only with regard to ç
the <193>tman, our own self. °tman can never be apprehended or comprehended ç
by the senses or the mind since it is the power behind them. It is ç
to be experienced directly by itself.
Aparok<218><193>nubh<220>ti is also the title of a small treatise ç
on Advaita Ved<193>nta attri- buted to <185>a<209>kara (<F51320MS>A. D.<W1> ç
<F255D>788-820). Extending over 144 verses, the work deals mainly with ç
the various disciplines that help destroy aj<210><193>na (ignorance ç
of the real nature of the <193>tman) and manifest the <193>tman.
@NT = apasm<193>ra-puru<218>a
@N1 = (`cretinous person')
To the uninitiated, idols or pictures of the Hindu gods with their ç
wives andchildren, queer mounts and obsolete weapons is an enigma. ç
It is no more so when it is conceded that they are often symbolical ç
and when the symbolism itself is understood from competent sources.
Though Lord <185>iva, the great God of dissolution and the last of ç
the Hindu Trinity, is generally worshipped in the form of the li<209>ga, ç
idols depicting him in various poses are not uncommon. They are, invariably, ç
sculptured on the walls or pillars of temples, but not formally worshipped ç
in the sanctum sanctorum.
Out of such images of <185>iva, that of Na<219>ar<193>ja, `the king ç
of dancers', is the most enchanting. In this, he is shown as tramp- ç
ling upon a dwarf-demon called `apasm<193>ra-puru<218>a.' He symbolises ç
ignorance.
Apasm<193>ra, strictly speaking, is epilepsy. However, in this context, ç
cretinism is perhaps nearer the intended sense. Just as cretinism ç
makes a man underdeveloped both in body and in mind, even so does ç
ignorance stunt one's spiritual growth.
The icons of Dak<218>i<207><193>m<220>rti <185>iva also show him as ç
trampling upon the apasm<193>ra-puru<218>a.
See also <MS>DAK<186>IØ°MURTI <D>and <MS>NA<187>AR°JA.<D>
@NT = °pastamba
°pastamba is one of the few highly venerated ancient sages accredited ç
with the authorship of some important religious works which are considered ç
as authoritative even today. Tradition ascribes his works to the period ç
Kali 450 (i.e., 2652 <F51320P10MSC1>B.<|>C.<W1>).<F255P255DC255> However, it ç
is impossible to confirm or deny this, as in the case of many other ç
ancient authors.
The name is sometimes spelt as `°pastambha' (`one who could restrain ç
water'). The mythological lore attributes to him the yogic power to ç
stay under water for long. This would often attract the aquatic creatures ç
to him. Fishermen interested in making a bonanza of the catch, once ç
spread their nets in the place where he was seated in yoga and un- ç
wittingly netted him. King N<193>bh<193>ga is then said to have freed ç
him honouring him with a cow and a calf and sent him back to his hermitage.
The four or five works ascribed to him may be grouped under one title, ç
the °pastamba Kalpas<220>tras. The `Kalpa' (or Kalpas<220>tras) ç
is a class of literature grouped under the Ved<193><209>gas (subsidiary ç
disciplines which help grasp the purport of the Vedas better), and ç
is further subdivided into ·rauta, g<216>hya, dharma and·ulba. (For ç
details, see under <MS>KALPA-S<188>TRAS, <185>RAUTA-S<188>TRAS, G<184>HYAS<188>TRAS, ç
DHARMAS<188>TRAS<D> and<MS> <185>ULBAS<188>TRAS.)<D>
The °pastamba Kalpas<220>tras is a fairly voluminous work comprising ç
30 pra·nas, or sections. Out of these, the first 24 pra·nas, appropriating ç
a lion's share, form the <185>rautas<220>tras. The next two sections ç
are called Mantrap<193><219>ha. The 27th pra·na is the G<216>hyas<220>tras. ç
The next two make up the Dharmas<220>tras whereas the last is known ç
as <185>ulbas<220>tras. Of course, when these works are treated ç
as independent treatises, they are prefixed by the author's name. ç
(°pastamba <185>rautas<220>tras and so on.)
The <185>rautas<220>tras (no. of s<220>s. 7590) deal exhaustively ç
with the conduct of Vedic sacrifices from Dar·ap<220>r<207>am<193>sa ç
up toA·vamedha and Puru<218>amedha. It is assigned to the K<216><218><207>a ç
Yajurveda and has been commented upon by Dh<220>rtasv<193>min and ç
Kapardisv<193>min.
@SPACE1 = 
The Mantrap<193><219>ha gives the prayers or hymns to be used at ç
appropriate places during the conduct of rituals and sacrifices.
The G<216>hyas<220>tras (no. of s<220>s. 389) deal mainly with the ç
rites connected with the family (g<216>ha = home, family) life, like ç
upanayana (initiation into Vedic studies), sam<193>vartana (returning ç
from the guru's house after Vedic studies), marriage, rites to be ç
performed on the birth of children as also certain magical rites. ç
The work has been commented upon by Haradatta Mi·ra and Sudar·an<193>c<193>rya.
The Dharmas<220>tras (no. of s<220>s. 1381) give a fairly good account ç
of the duties of the four <193>·ramas and the four var<207>as and ç
also describe the sixteen sa<221>sk<193>ras (purificatory rites). ç
Haradatta Mi·ra has written a beautiful commentary on it, which he ç
has named as Ujjval<193>.
The <185>ulbas<220>tras is a highly technical work dealing with ç
the construction of altars for Vedic sacrifices. Out of the three ç
commentaries available, that of Kapardi-sv<193>min is the oldest.
@NT = apathya
@N1 = (`away from the path')
The Hindu system of medicine and treatment,  known  as  °yurveda  (`the ç
science of longevity') is as particular with regard to prescribing ç
diet and conduct as with medicines and treatment. The former is called ç
`pathya, what is on the right road;' i.e., what is in consonance with ç
the rules of the science of treatment. For instance, in almost all ç
cases of illness, over-eating, drinking, and preventing sleep are ç
to be avoided. If this is done, then it is `pathya.' In dehydrating ç
diseases, the patient should consume plenty of warm water. That is ç
`pathya' for him.
`Apathya' is the opposite of `pathya,' the foods, drinks and conduct ç
which will aggravate the disease. For instance, a patient suffering ç
from fever should not take rice or expose himself to cold. It is `apathya' ç
for him.
The principles of pathya and apathya can be extended to the field ç
of religion and spiritual life too.
See also <MS>°YURVEDA<D>.
@SPACE = 
@NT = apav<193>da
@N1 = (`that which over-rules')
In tarka or logic, this word stands for an exception to a general ç
rule. For instance, ahi<221>s<193> or not to harm any living being ç
is a general rule. But killing animals in a sacrifice is permitted ç
as an apav<193>da or exception.
Apav<193>da also means an accusation.
The word is used in Advaita Ved<193>nta too. See <MS>ADHY°ROPA<D>.
@SPACE = 
@NT = apavarga
@N1 = (`beyond classification')
The sages of India were good psycho-logists. With a keen and incisive ç
intellect, they discovered the basic urge of all human beings to get ç
pleasure and happiness in life. They were also wise enough to perceive ç
that this urge had to be contained by a higher motivating power, so ç
that the greatest good of the greatest number could be achieved. This, ç
they called `dharma' (righteousness) while naming the other as `artha ç
and k<193>ma.' K<193>ma is desire in general and artha is the means ç
of satisfying it. The three together have been classified as `trivarga,' ç
whereas mok<218>a (liberation from transmigration, beatitude) which ç
is beyond the pale of this, gets theappellation `apavarga' (varga ç
= class, apa=beyond).
Mok<218>a, mukti, kaivalya and nirv<193><207>a are its synonyms.
See <MS>MOK<186>A<D> for details.
@NT = Aponaptr<200>y<193>
Aponaptr<200>y<193> is a minor ritual conduc- ted during and as a ç
part of Somay<193>ga. Water drawn from a river on the day prior to ç
the extraction of the soma juice and preserved in a vessel called ç
vasat<200>var<200> as also the water drawn on the morning of ritual ç
extraction kept in vessels named ekadhan<193> are ceremonially mixed ç
with appropriate hymns (<184>gveda 10.30). This hymn is also known ç
by the same name as the rite itself.
The hot<216> (priest, representing the <184>gveda) is advised to ç
recite the first stanza (pra devatr<193> brahma<207>e<|>...) continuously ç
thrice. This will induce Parjanya, the rain-god, to give rains where ç
and when necessary.
This rite will also help the yajam<193>na (performer of sacrifice) ç
to complete the sacrifice without any obstacles or hitch.
@NT = Appar
@N1 = (`father')
If Hindu religious traditions have survived the vagaries of time and ç
onslaughts of aliens throughout history, it is not a little due to ç
the sages, saints and seers that have emerged on the scene from time ç
to time. They have cut out the deadwood, rejuvenated the flogging ç
spirits and have blazen forth new vistas of spiritual life.
In this religious renaissance, the part played by the <185>aiva and ç
the Vai<218><207>ava saints of South India is very significant. Of ç
the four <193>c<193>ryas of the Samaya school of <185>aivism, Appar ç
comes first, the other three being Sambandhar, Sundaram<220>rti and ç
M<193><207>ikkav<193>cakar.
`Appar' (= father) is only a title given to Tirun<193>vukkarasar by ç
another great <193>c<193>rya, a much younger contemporary, Tiruj<210><193>na ç
Sambandhar or Sambandhar.
Appar lived probably during the period <F51320P10MSC1>A. D.<W1> 600<192>655, ç
when the Pallava king Mahendra I was ruling at K<193><210>c<200>- ç
puram. Having lost his parents very early, he was brought up by his ç
saintly sister Tilak<193>vatiy<193>r. Being influenced by the Jain ç
doctrines, he got himself converted to Jainism. However, a serious ç
crisis of health which was dispelled by the grace of Lord <185>iva, ç
the family deity, reclaimed him to his faith. It is said that the ç
Jaina religious leaders who were dismayed at his reconversion tried ç
to harass him through the king. However, he came unscathed, converting ç
the king himself in the process.
He travelled widely and met another great saint Sambandhar who was ç
hardly seven years old at that time. They became fast friends and ç
mutual admirers.
A simple man of ardent faith and intense love for God, he is said ç
to have composed in Tamil many padigas or decads of hymns, of which ç
only 311 are extant. These hymns give the essence of the ancient scriptures ç
in a simple but poetic language.
See also <MS><185>AIVISM, SAMAYA-MATA<D> and <MS>SAMBANDHAR<D>.
@NT = Appayya D<200>k<218>ita
@N1 = (<F51320P10MSC1>A. D.<W1> 1520<192>1592)
One of the few most versatile writers on Advaita philosophy, Appayya ç
D<200>k<218>ita was born in a village near K<193><210>c<200>puram ç
(Tamil Nadu), probably in <MS>A.<|>D.<D><|>1520. A scion of a family ç
of great scholars, he was tutored by his father Ra<209>gar<193>ja ç
Adhvarin as also by Yaj<210>e·vara Makh<200>ndra.
Bha<219><219>oji D<200>k<218>ita, the author of the well-known textbook ç
of Sanskrit grammar, Siddh<193>nta Kaumud<200>, was his pupil. N<200>laka<207><219>ha, ç
the famous commentator of Mah<193>bh<193>rata was his grandson.
Being an orthodox br<193>hma<207>a deeply devoted to the Vedic culture, ç
he is said to have performed the Jyoti<218><219>oma and the V<193>japeya ç
sacrifices for the good of mankind. King Narasi<221>ha Bh<220>p<193>la ç
of Tanjore attended the latter and honoured him.
Appayya D<200>k<218>ita toured the south extensively and propagated ç
both <185>aivism and Advaita Ved<193>nta. Traditional anecdotes attribute ç
many miraculous powers to him which he had to exhibit, to counter ç
the evil designs of T<193>t<193>c<193>rya, a contempo-rary Vai<218><207>avite ç
scholar. Governor Cinna Bomma N<193>yaka of Vellur (16th cent. <MS>A.D.<D>)<MS> ç
<D>was a devoted disciple of his. He is reputed to have shed his mortal ç
coil in the famous Cidambaram temple in a mysterious way.
Appayya D<200>k<218>ita was a prolific writer and composer. In all, ç
he composed 104 works, the subject ranging from <185>aivism to Advaita ç
Ved<193>nta, grammar and rhetoric as also tantra and hymnology. Out ç
of these, the three works on the Brahma-s<220>tras and a treatise ç
on the various aspects of Advaita are well-known. They are:
@SPACE1 = 
@NO = (1)
@NOK = Ny<193>yarak<218><193>ma<207>i, an independent commentary ç
on the first p<193>da or quarter of the Brahmas<220>tras from the ç
standpoint of Advaita.
@NO = (2)
@NOK = Parimal<193>, a simple but detailed gloss on the Kalpataru ç
of Amal<193>nanda, which itself is a gloss on V<193>caspati Mi·ra's ç
famous work Bh<193>mat<200>. Bh<193>mat<200>, again is a subcommentary ç
on <185>a<209>kara's Bh<193><218>ya on the Brahma-s<220>tras. The ç
three commentaries† Bh<193>mat<200>, Kalpataru and Parimal<193>† ç
have created a new school of Advaita, known as the `Bh<193>mat<200>-prasth<193>na.'
@NO = (3)
@NOK = <185>iv<193>rkama<207>id<200>pik<193>, a commentary on the ç
<185>r<200>ka<207>tha-bh<193><218>ya of Brahma-s<220>tras, written ç
from the standpoint of <185>ivavi·i<218><219><193>dvaita.
@NO = (4)
@NOK = Siddh<193>ntale·asa<209>graha, an original treatise dealing ç
elaborately with the various aspects of Advaita doctrines developed ç
by the post-<185>a<209>kara writers. This work has attracted the attention ç
of a number of scholars who have written commentaries.
His Kuvalay<193>nanda, a work on rhetoric is studied as a standard ç
text-book even today.
@NT = apr<193>k<216>ta-·ar<200>ra
@N1 = (`non-material body')
According to most of the theistic systems of Hindu philosophy, prak<216>ti ç
or insentient nature (sometimes called apar<193>- prak<216>ti also) ç
is one of the fundamental constituents of the universe. It comprises ç
the three gu<207>as†sattva, rajas and tamas. Not only the inanimate ç
creation but also the bodies of living beings, are made out of this ç
prak<216>ti. Hence, these bodies are called pr<193>k<216>ta-·ar<200>ras ç
or `material bodies'.
However, as opposed to this, the bodies of God in his aspects of vy<220>ha ç
(emanations), vibhava (incarnations) and arca (manifestation in worship), ç
are apr<193>k<216>ta-·ar<200>ras, non-material bodies. The bodies ç
of the nityas (eternal beings) and the muktas (liberated souls) are ç
also made of the same stuff.
This non-material substance is also known as ·uddhasattva and is the ç
stuff of the `nityavibh<220>ti,' the non-material infinite domain ç
beyond prak<216>ti and its three gu<207>as.
See also <MS>VI<185>I<186><187>°DVAITA-VED°NTA- DAR<185>ANA<D>.
@SPACE = 
@NT = aprameya
@N1 = (`immeasurable')
Pram<193><207>a and prameya are two words constantly met with in Hindu ç
epistemo-logy. Pram<193><207>a is the means of knowledge and prameya ç
is that which is thus known. For instance, when we see a pot, the ç
act of seeing is the `pram<193><207>a' and the pot itself is the `prameya' ç
(that which is measured or comprehended).
All objects with name, form and qualities can be subject to comprehension ç
and verification through the pram<193><207>as. However, God the transcendental ç
Being, is beyond all such pram<193><207>as and hence is termed `Apraymeya' ç
(lit., the immeasu-rable). He is beyond even the ·<193>stra or <193>gama ç
(the revealed scripture) which helps only in removing our miscomprehension ç
about him and not reveal him directly.
In devotional literature, the word seems to be more commonly applied ç
to Lord Vi<218><207>u.
@SPACE = 
@NT = °pr<200>
@N1 = (`gaining favour')
Derived from the root `pr<200>' (to propitiate, to gain favour), the ç
word `°pr<200>' refers to a group of invocatory hymns belonging to ç
the class of `y<193>jy<193>s' (formulae of consecration). There are ç
ten °pr<200>-s<220>ktas in the <184>gveda (1.13; 1.142; 1.188; ç
2.3 and so on). The yajam<193>na (sacrificer) has to choose from these ç
verses according to his gotra (lineage). They are recited in the Pa·ubandha ç
sacrifices.
Chanting of these hymns will please the concerned deities and they ç
confer boons on the sacrificer. The deities appear to be personified ç
objects belonging to the sacrifice, like the fuel, the sacrificial ç
grass, the enclosure and so on, all regarded as different forms of ç
Agni, the fire-god.
@NT = ap<216>thak-siddha
@N1 = (`inseparably existing')
The relationship between God on the one hand, and the individual souls ç
as also the insentient nature on the other, is a point often discussed ç
in the theistic schools of Hindu philosophy. Reality of the external ç
world and plurality of the individual selves is a fact of experience. ç
Maintaining the supreme independence of God is a logical and metaphysical ç
necessity. Reconciling these two positions needs a correct statement ç
of the relationship between God and his creation.
Vi·i<218><219><193>dvaita Ved<193>nta, systematised by R<193>m<193>nuja ç
(<F51320P10MSC1>A. D.<W1> 1017-1137) and others, has solved this problem ç
by accepting the acit (insentient nature) and the cit (sentient souls) ç
as being the body of ®·vara (God), the former two being considered ç
as `ap<216>thak-siddha-vi·e<218>a<207>as' of the latter. To explain: ç
In the sentence, `This is a white cow,' the colour whiteness depends ç
upon the cow and cannot exist separately from the cow. Neither are ç
the cow and the whiteness identical. Hence whiteness is an ap<216>thak-siddha-vi·e<218>a<207>a, ç
a vi·e<218>a<207>a or attribute, which is siddha or existing, ap<216>thak ç
or inseparably.
Other examples quoted are: the flower and its fragrance, the vowel ç
and the consonant, the body and the self.
This approach allows for internal plurality but rejects the pluralistic ç
view. The ultimate Truth is thus posited as an organic whole, in spite ç
of different organs or limbs.
Compare with <MS>SAMAV°YA<D>.
See also <MS>PRAK°RA<D>.
@NT = apsar<193>s
@N1 = (`moving in waters;)
The apsar<193>s are the celestial nymphs living in svargaloka (heaven). ç
They perhaps got this name since they are supposed to move among waters, ç
among the clouds. Their main work is to please Indra the lord of the ç
gods, by dancing and singing. Indra often deputes them to seduce the ç
sages engaged in severe austerities, since they may become more powerful ç
than himself, if they succeed!
They are said to have been born out of the milk-ocean when it was ç
churned by the gods and the demons to get nectar. According to other ç
versions they were born out of the palm of Brahm<193>, the creator.
They are too numerous to be listed. <188>rva·<200>, Ra<221>bh<193>, ç
Menak<193> and Tilottam<193> are the most prominent among them.
They are closely associated with the demigods known as `gandharvas.'
Popular Buddhism has adopted some of them, in its mythological lore.
@NT = <193>pta-v<193>kya
@N1 = (`the statement of a trust- worthy person')
The <193>stika-dar·anas or systems of Indian philosophy that accept ç
the autho-rity of the Vedas, have given the highest place to ·abda-pram<193><207>a ç
(scriptural testimony), also called <193>gama (authentic word handed ç
down by tradition) and <193>pta-v<193>kya (statement of a trustworthy ç
person).
It is impossible to obtain all know-ledge through direct perception ç
since the range of the organs of perception is limited. Nor can inference ç
be of much help since it is based on previous experiences which again ç
are based on direct perception. At some stage, faith in the word, ç
spoken or heard or read, has got to be resorted to. In fact the knowledge ç
gained thus is enormous. Even the day-to-day life becomes impossible ç
without believing in the authenticity of the spoken or written word.
Of course, it goes without saying that the person through whom such ç
knowledge comes, must be trustworthy and that he should have based ç
his findings on authentic experience or sources.
Coming to things divine, since they pertain to areas of supersensuous ç
experience, only persons of the highest spiritual calibre†<216><218>is ç
as they are called†can be the guides and the mentors. The scriptures, ç
which are revelations handed down through them, are the highest class ç
of <193>pta-v<193>kya literature.
See also <MS>PRAM°ØAS<D>.
@NT = Aptory<193>ma
Yaj<210>as or Vedic sacrifices are generally of three types: p<193>kayaj<210>as ç
in which cooked articles are offered; haviryaj<210>as in which havis ç
or ghee is the oblation; and somayaj<210>as in which the soma juice ç
is the main ingredient of offering. Aptory<193>ma belongs to the last ç
group. It is considered as an extension of another somayaj<210>a, ç
viz., the Atir<193>tra.
The rite derives its name `Aptory<193>ma' from the belief that by ç
its performance one secures whatever one desires (<193>p =to secure). ç
However, it is usually performed by one who wants to obtain cattle ç
of good breed. More than a thousand cows and a chariot with mules ç
yoked are to be gifted away in this sacrifice.
See also <MS>ATIR°TRA<D> and <MS>SOMAY°GA<D>.
@NT = ap<220>rva
@N1 = (`not existing previously')
The word `ap<220>rva' is a technical term employed by the P<220>rva-m<200>m<193><221>s<193> ç
system of Hindu philosophy which advocates the performance of all ç
the prescribed Vedic rituals as the only means of obtaining the summum ç
bonum of life.
Vedic sacrifices are said to produce results such as attaining heaven. ç
The doubt that naturally arises is: How can an act performed here ç
and now produce a result much later and somewhere else? Does it not ç
violate the law of cause and effect?
This objection is answered by the P<220>rvam<200>m<193><221>s<193> ç
system by formulating the theory of ·akti (potential energy). Just ç
as a seed possesses in it the imperceptible power with the help of ç
which it can produce the sprout, so does the soul possess the power ç
to manifest the results of Vedic rituals. These rituals, as soon as ç
they are completed, generate in the soul that ·akti or power. Since ç
this power did not exist previously (a-p<220>rva = not existing previously) ç
but is generated as a result of the rites, it is termed `ap<220>rva.' ç
This ap<220>rva gets exhausted after producing its results.
See also <MS>AD<184><186><187>A<D> and <MS>KARMA.<D>
@NT = ap<220>rva-vidhi
@N1-1 = (`unprecedental injunction')
The M<200>m<193><221>s<193> (also called P<220>rva-m<200>m<193><221>s<193>) ç
system of Hindu philosophy lays great emphasis on the performance ç
of the rituals†which alone constitute the `dharma'†prescribed in the ç
Vedas. The whole of the Vedas can be broadly divided into `vidhi' ç
or injunctions and `arthav<193>da' or laudatory statements.
The vidhis again are classified into three groups: (1) ap<220>rva-vidhi; ç
(2) niyama-vidhi and (3) parisa<209>khy<193>-vidhi.
The ap<220>rva-vidhi (translated as `original injunction') is a vidhi ç
or injunction which has not been known previously (ap<220>rva = unprecedented) ç
To illustrate: In the Dar·ap<220>r<207>am<193>sa sacrifice, there ç
is the injunction, `vr<200>h<200>n prok<218>ati' (`He sprinkles the ç
rice grains'). In the absence of this injunction the sprinkling with ç
regard to the rice grains used in this sacrifice would never be known. ç
But with this injunction, sprinkling of the rice grains becomes compulsory.  Hence  it  is  an  original ç
injunction.
See also <MS>NIYAMA-VIDHI, PARISA<177>KHY°-VIDHI<D> and <MS>VIDHI<D>.
@NT = <193>rabdha
See   <MS>AN°RABDHA,   KARMA<D>   and <MS>PR°RABDHA<D>.
@NT = <193>rambhav<193>da
See <MS>PARIØ°MAV°DA<D>.
@NT = ara<207>i
@N1 = (`that which is turned round')
The fire in which Vedic sacrifices are performed, should be generated ç
by attrition. The two pieces of wood used for this purpose are called ç
`ara<207>is.' The lower piece, termed `adhar<193>ra<207>i,' is rectangular ç
in shape and has an indentation called `devayoni,' the origin of the ç
god of fire. The upper piece called `uttar<193>ra<207>i' is in the ç
form of a drill, which is inserted into the indentation of the adhar<193>ra<207>i. ç
Fire is generated by vigorous churning, to the chanting of appropriate ç
<216>ks (hymns from the <184>gveda).
There are several rules governing the preparation of these ara<207>is. ç
The upper ara<207>i should be made from the wood of the ·am<200> tree ç
(Prosopis specigera) which is hard; and the lower one should be ç
of the a·vattha (Ficus religiosa) which is softer, the size being ç
16 a<209>gulas long, 12a<209>gulas wide and 4 a<209>gulas in height.
@SPACE = 
@SPACE = 
@SPACE = 
The lower ara<207>i is sometimes figuratively called the `mother,' ç
the upper ara<207>i the father and agni the fire, as the offspring.
@NT = °ra<207>yakas
@N1 = (`forest treatises')
Each of the four Vedas, the basic scriptures  of  Hinduism,  is  generally ç
divided into four parts: the Sa<221>hit<193>, the Br<193>hma<207>a, ç
the °ra<207>yaka and the Upani<218>ad.
The Sa<221>hit<193>s are collections of Vedic hymns. The Br<193>hma<207>as ç
are treatises written in prose, dealing with the conduct of sacrifices ç
and other rites associated with them. The Upani<218>ads deal with ç
philosophical truths and esoteric wisdom.
@SPACE1 = 
The °ra<207>yakas form a link between the ritualism of the Br<193>hma<207>as ç
and the philosophy of the Upani<218>ads. Whether they really represent ç
a transitional phase of thought, is difficult to decide since the ç
°ra<207>yakas and the Upani<218>ads have almost fused into one another.
Hindu tradition connects the four <193>·ramas (stages of life) with ç
the four divisions of the Vedas. The brahmac<193>rin (student of the ç
Vedas) is expected to memorise the Sa<221>hit<193> and know the application ç
of the mantras contained therein, in the various rites and ceremonies. ç
The g<216>hastha (householder) is guided by the Br<193>hma<207>as ç
in the performance of the numerous sacrificial rites. The v<193>naprasthin ç
(forest recluse) is advised to contemplate on the ritual as symbolic ç
of higher philosophic truths. The sa<221>ny<193>sin (monk) is to meditate ç
upon the funda-mental spiritual truths until he directly perceives ç
them.
This traditional linking of the four <193>·ramas with the four parts ç
of the Vedas can perhaps give us an idea about the basis of the °ra<207>yaka ç
thought. Due to the physical infirmity brought on by old age and since ç
the accessories and articles needed for the Vedic rites are not easily ç
procurable in the forest, the v<193>naprasthin will be hard put to ç
continue them. Moreover, battling with the various vicissi- tudes ç
of life, will have brought on enough mellowness and wisdom that will ç
make him receptive tophilosophic speculations. However, the attachment ç
to the rites and the eagerness to reap the promised fruits will still ç
be lingering in the mind due to the long association with the deep ç
involvement in those rites. Hence contemplation on the various aspects ç
and stages of those rites as symbols of cosmic truths will be the ç
best exercise for him, conducive to his ultimate spiritual welfare. ç
This is exactly what the °ra<207>yakas have done. In fact, the  famous  B<216>had<193>ra<207>yaka  Upani<218>ad ç
begins with one such contemplation. Hence they are often classified ç
as `Up<193>san<193>k<193><207><195>a' (section  dealing  with  meditations)  as ç
opposed to the `Karmak<193><207><195>a' (section dealing with the ç
rituals, i.e., Sa<221>hit<193>s and Br<193>hma<207>as) and leading ç
progressively to `J<210><193>nak<193><207><195>a' (section dealing ç
with spiritual knowledge, viz., the Upani<218>ads).
@SPACE1 = 
The extant °ra<207>yakas of the four Vedas may be listed as follows:
@SB = <184>gveda:
Aitareya °ra<207>yaka, <185><193><209>khyana °ra<207>-yaka (sometimes ç
called Kau<218><200>taki °ra<207>-yaka also).
@SB = <185>ukla Yajurveda:
B<216>had<193>ra<207>yaka (the earlier part of the <185>atapatha ç
Br<193>hma<207>a, the later part being the Upani<218>ad).
@SB = K<216><218><207>a Yajurveda:
Taittir<200>ya °ra<207>yaka, Maitr<193>ya<207><200>ya °ra<207>yaka.
@SB = S<193>maveda:
Last part of the T<193><207><195>ya-mah<193>-br<193>hma<207>a (also ç
known as Pa<210>cavi<221>·a-br<193>hma<207>a), Talavak<193>ra °ra<207>yaka.
@SB = Atharvaveda:
No °ra<207>yaka is available.
(For details, see under the respective titles.)
@NT = Ara<207>yak<193><207>da
Ara<207>yak<193><207>da forms the third book of the famous epic, ç
the R<193>m<193>ya<207>a of V<193>lm<200>ki. See <MS>R°M°YAØA<D> ç
for details.
@NT = Ara<207>yaparva
Also known as Vanaparva, it forms the third book of the great epic, ç
the Mah<193>bh<193>rata of Vy<193>sa.
See <MS>MAH°BH°RATA<D> for details.
@NT = Ara<207>ya<218>a<218><219>h<200>
Festivals and sacred days break the monotony and add zest and colour ç
to the life of the common people. Out of the several festivals of ç
the Hindus, Ara<207>ya<218>a<218><219>h<200> (also called °ra<207>ya<218>a<218><219>hi, ç
Ara<207>ya-gaur<200>-vrata or Skanda<218>a<218><219>h<200>) is perhaps ç
a minor one. Celebrated on the sixth day of the bright half of the ç
month of Jye<218><219>ha (around June), it is mainly centred round ç
the worship of <186>a<218><219>h<200>, the mother of Skanda (also ç
known as Subrahma<207>ya and K<193>rttikeya). Since she is the protectress ç
of children, mothers propitiate her for the well-being of their children. ç
Fasting or subsisting on lotus stalks, bulbous roots and fruits is ç
pre- scribed as a discipline. It is usually performed in a wood or ç
forest outside the village. Hence the name Ara<207>ya<218>a<218><219>h<200> ç
(ara<207>ya = forest). In some parts of India, sons-in-law are invited ç
and entertained with a feast and clothes, thus giving the festival ç
another name, viz., j<193>m<193>t<216><218>a<218><219>h<200> (j<193>m<193>t<216> ç
= son-in-law).
@NT = arc<193>
@N1 = (`that which is worshipped')
The Vai<218><207>avite scriptures which preach the cult of Vi<218><207>u-N<193>r<193>ya<207>a-K<216><218><207>a ç
put forth the theory that the Supreme Lord Vi<218><207>u has four ç
kinds of manifestations: (1)the `para' or the Supreme; (2)the `vy<220>ha' ç
or the emanation; (3) the `vibhava' or the incarnation and (4) the ç
`arc<193>' or the icon.
Out of these, the arc<193> represents the images or icons installed ç
and worshipped ceremonially in temples and shrines. Such icons are ç
classified into four groups: svaya<221>vyakta or self-manifested, ç
daiva or established by gods, <193>r<218>a or consecrated by the <216><218>is ç
(sages) and m<193>nu<218>a or prepared by human beings.
Even the man-made images, though prepared out of inanimate substances, ç
can become `alive' if they are duly consecrated through the prescribed ç
rites. God who is omnipotent `descends' into such images with a subtle ç
body. This is the `arc<193>vat<193>ra' orincarnation for purposes ç
of ordinary worship.
@NT = arc<193>vat<193>ra
See <MS>ARC°<D>.
@NT = arcir<193>di-m<193>rga
@N1-1 = (`the path beginning with light')
See <MS>DEVAY°NA<D>.
@NT = ardha-k<216>cchra
@N1 = (`half k<216>cchra;)
Sin (p<193>pa) and its expiation (pr<193>ya-·citta) is one of the ç
topics discussed by the dharma·<193>stras, often in great detail. ç
Many of the expiatory rites have been given the general name `k<216>cchra' ç
(`that which cuts happiness or causes suffering). Out of the several ç
k<216>cchras, the `ardha-k<216>cchra' is an expiation for minor sins ç
and causes only `hal<%14>f<%0>' the suffering of a k<216>cchra (ardha ç
= hal<%14>f<%0>).
The repentant transgressor is expec-ted to subsist on food obtained ç
without asking for it, for the first three days and thereafter fast ç
completely for three more days.
As per another rule, he should eat only once in a day for two days, ç
subsist on food got unasked for two more days and fast completely ç
for the last two days of the six day discipline.
See also <MS>K<184>CCHRA<D>.
@NT = ardha-ma<207><195>apa
@N1 = (`half-open hall')
The most important part of a Hindu temple is the garbhag<216>ha (sanctum ç
sanctorum) wherein is housed the idol of the deity. In front of it ç
and contiguous to it is the mukhama<207><195>apa, also called ·ukan<193>s<200>  and  ardhama<207><195>apa.  This  is ç
actually a passage, its proportion being relative to that of the garbhag<216>ha ç
itself. Apart from being used as a passage it is also used to keep ç
the articles of worship including food offerings on special occasions. ç
The word is sometimes spelt as `ardhaman<219>apa' also.
@NT = Ardha-n<193>r<200>·vara
@N1 =  (`Lord, who is<R>ç
half-woman')
<185>iva, also called ®·vara, is the third deity of the Hindu Trinity. ç
He is generally worshipped in the form of the li<209>ga.
Etymologically both the words, <185>iva and li<209>ga, mean `that ç
into which the universe dissolves.' <185>iva is thus the ultimate ç
source of all creation.
In the Hindu mythological works, the ·akti or power by which God creates, ç
sustains and dissolves the universe is pictured as a female deity, ç
the consort of God. <185>iva's consort is P<193>rvat<200>.
Ardhan<193>r<200>·vara is one of the several forms in which <185>iva ç
manifested himself. The right half is that of <185>iva and the left, ç
that of P<193>rvat<200>. This iconographic concept signifies the identity ç
of <185>iva and <185>akti, and as a corollary, that man and woman ç
are mutually complementary. In a more general sense, it signifies ç
the bipolar nature of the world.
Some scholars opine that the form might have been evolved to bring ç
about a compromise between the cults of <185>iva and <185>akti.
@NT = °rdr<193>
@N1 = (`the wet')
°rdr<193> is the sixth nak<218>atra or constel- lation of stars (of ç
the twentyseven listed by the Hindu astronomy). It is the star Alpha ç
Orionis or Betelgeuse. In Hindu astrology it is considered malefic. ç
Persons born under its influence will become vain, foolish and tend ç
towards a sinful life. The day associated with this nak<218>atra is ç
considered inauspicious for starting any new good venture.
See also <MS>NAK<186>ATRA<D>.
@NT = argha
@N1 = (`that which is deserved')
@SPACE = 
Derived from the root `argh' (`to be valuable') or `arh' (`to deserve'), ç
the word `argha' is used in a more technical sense in the dharma·<193>stras. ç
It signifies a reception ceremony performed in honour of a bridegroom ç
by his father-in-law, of a newly married couple, on their return to ç
the bride's house. It is usual to offer madhuparka (a mixture of honey ç
and other ingredients) on such occasions.
The  word  `arghya'  derived  from `argha' means a person worthy of ç
`argha' or honour. However, it is used in a more restricted sense ç
to indicate the water perfumed with flowers and mixed with d<220>rva-grass, ç
rice grains and mustard seeds that is ceremonially offered in ritualistic ç
worship of God, as also to honoured guests. They are expected to receive ç
it and wash their hands with it.
Six  persons  are  enumerated  as deserving this arghya: <193>c<193>rya ç
(teacher), <216>tvij (officiating priest), r<193>jan (king), priya ç
(friend), sn<193>taka (Vedic student who has completed his studies) ç
and viv<193>hya (bridegroom).
In the sandhy<193> ritual, arghya is the offering of water to the ç
sun. The worshipper takes water in the joined palms of his hands, ç
repeats the G<193>yatr<200> mantra over it and casts it up respectfully ç
while standing and facing the sun. It is interest- ing to note that ç
the use of dust is allowed for this purpose when water is not readily ç
available.
@SPACE = 
@NT = arghya
@SPACE = 
See under <MS>ARGHA<D>.
@NT = Arhat
@N1 = (`venerable')
Derived from the verbal root `arh' (`to deserve') the word `Arhat' ç
is common to both Buddhism and Jainism. However it is in Jainism that ç
it is more current.
The Arhats (also spelt as Arahats or Arahantas) are beings who have ç
become perfect and can teach the way to perfection to others. They ç
are endowed with un- limited knowledge, vision, power and bliss. They ç
are free from the limitations of flesh like hunger or thirst, since ç
their bodies are not material. `Jina' is another name commonly applied ç
to them.
In the Pa<210>caparame<218><219>hi-mantra the Arhats are the first ç
to whom obeisance is offered (<207>amo arihant<193><207>am).
@NT = ari<218>a<195>varga
@N1 = (`group of six enemies')
Hinduism has always considered mok<218>a or liberation from transmigratory ç
existence, as the real and the ultimate goal of life. Since this is ç
got by realising the <193>tman†one's true Self†already present in ç
everyone, but covered over by various impurities of the mind, it is ç
first necessary to efface them.
These impurities of mind, which act as `ari' or an enemy in the path ç
of spiritual evolution, are generally classed into six varieties and ç
are called `ari<218>a<195>varga', the group of six enemies. They are: ç
k<193>ma (lust); krodha (anger); lobha (avarice); moha (delusion); ç
mada (arrogance) and, m<193>tsarya (jealousy).
Some of the treatises of Ved<193>nta like the J<200>vanmuktiviveka ç
of Vidy<193>ra<207>ya (14th century <MS>A.<|>D.<D>) deal with the methods ç
of eradicating them.
According to the teachers of bhakti or devotion, these six passions ç
can be eliminated by n<193>majapa (repetition of the divine name) ç
and up<193>san<193> (meditation on God) or sublimated by directing ç
them towards God Himself<|>!
@NT = ari<218><219>a
@N1 = (`unhurt')
Though the word `ari<218><219>a' is used in several senses (as for ç
instance†proof against injury, crow, soap-berry tree, garlic and so ç
on), in a more technical sense it indicates the ill-omens foreboding ç
misfortune or even death, especially in the case of a patient.
In the °yurveda, the science of health, ari<218><219>as are decoctions ç
prepared out of grapes or certain roots and used as tonics.
Ari<218><219>a is the name of a demon, a servant of Ka<221>sa, who ç
assumed the form of a bull to attack and kill the child K<216><218><207>a, ç
but was ultimately killed by him.
The Mah<193>bh<193>rata mentions about a sage Ari<218><219>a who ç
revived his son who had been killed by a prince.
Ari<218><219><193> was one of the wives of the sage Ka·yapa and was ç
the mother of the gandharvas like H<193>h<193> and H<220>h<220>.
@NT = Ari<218><219>anemi
@N1 =  (`the felly of whose wheel is unhurt')
Ari<218><219>anemi was one of the five sons of Vinat<193> and Ka·yapa, ç
and a brother of the famous Garu<195>a. Sometimes, the sage Ka·yapa ç
himself has been known by this name.
The P<193><207><195>ava prince Sahadeva had assumed this name when ç
he lived in Vir<193><219>anagara, in disguise.
It is also the name of the twenty-second T<200>rtha<209>kara of the ç
Jains.
@NT = Arjan, Guru
@N1 = (<F51320P10MSC1>A. D.<W1> 1563<192>1606)
@EMERGENCY = Whether Sikhism is a separate reli-gion or a reform movement ç
in Hinduism, there is no gainsaying the fact that the Sikh Gurus saved ç
Hinduism from external as well as internal dangers and exercised a ç
tremendous influence on the contemporary Hindu society.
@EMERGENCY = Sikhism, founded by Guru N<193>nak (<F51320P10MSC1>A.D.<W1> ç
1469<192>1538) and nurtured by a succession of nine more Gurus, had ç
to pass through various critical periods in its chequered history. ç
Guru Arjan, the fifth in the line of succession, appeared on the scene ç
just when a serious crisis, which would threaten its very existence, ç
was developing.
@EMERGENCY = He was born at Goindwal in <F51320P10MSC1>A.D.<W1><|>1563. He ç
was the youngest son of Bh<193>i Je<219>ha (later ordained as Guru ç
R<193>m D<193>s) and B<200>bi Bhani (daughter of the third Guru Amar ç
D<193>s). Guru Amar D<193>s is said to have remarked that this child ç
would cruise people across the ocean of life.
Guru R<193>m D<193>s, in course of time, appointed Arjan as his successor. ç
After his passing away, when Arjan took over as the next Guru, Pr<200>ti ç
Cand, his eldest brother, who had not reconciled himself to this supersession, ç
started harassing him to the maximum possible extent. However, being ç
too humble and noble to counter him, Guru Arjan left Goindwal and ç
settled down in a new township. Here he kept himself busy completing ç
the holy tanks of Santokhsar and Amritsar and other works left unfinished ç
by Guru R<193>m D<193>s. It was he who got the foundation stone of ç
Harmandir (later known as the Golden Temple) laid by Mian M<200>r, ç
a Muslim saint from Lahore. After the construction of the temple and ç
the lake was over, he undertook an extensive tour of Punjab to meet ç
his disciples and consolidate the work.
Guru Arjan, who had no children till then, sent his wife to Bh<193>i ç
Buddha, a highly respected Sikh saint, to get his blessings. Bh<193>i ç
Buddha blessed her and foretold that the son she would give birth ç
to, would crush the enemies of Sikhism like crushing an onion. She ç
gave birth to Hargobind, (in <F51320P10MSC1>A.D.<W1> 1595), who later on ç
succeeded Guru Arjan.
Pr<200>ti Chand's machinations to usurp power continued. He organized ç
several attempts to kill the child Hargobind who escaped miraculously. ç
However, when he tried to bring out his own compositions, passing ç
them on to the Sikhs as the compositions of N<193>nak, Guru Arjan ç
had to act quickly and decisively. He personally went to all the important ç
places connected with the previous Gurus and collected the authentic ç
texts of their B<193><207>i (word). This collection subsequently came ç
to be known as the Holy Granth.
@SPACE1 = 
Chandu Sh<193>h, a Hindu banker of Delhi who wielded a lot of influence ç
with the Mughal Emperors, was looking for a suitable match for his ç
daughter. When his agents suggested that he marry her to Hargobind, ç
Chandu Sh<193>h pooh-poohed it deriding the Sikh Guru for lack of ç
social or political status. Later on, when he could not get anyone ç
else, and relented, Guru Arjan politely declined the offer. This antagonized ç
the influential banker who succeeded in creating troubles for the ç
Guru at the hands of the Mughal authorities.
Though Akbar himself was well- disposed towards the Guru, Jeh<193><209>g<200>r, ç
his successor was not. He levied a heavy fine on the Guru who however ç
refused to pay it. This incurred the wrath of the emperor who tortured ç
him in various ways. The Guru however, bore everything with great ç
fortitude. Later (in <MS>A. D.<F51320P10W1C1> <F255P255DC255>1606)<F51320P10W1C1> ç
he entered the river Ravi and was carried away by its swirling waters.
Guru Arjan has left a large number of hymns (2218) rich in imagery ç
and lending themselves easily to music. Sukhma<207>i, his magnum ç
opus ranks only next to the Japji of Guru N<193>nak.
@NT = Arjuna
@N1 = (`the white or the pure')
The most widely known of the five P<193><207><195>ava princes, the ç
great hero of the Kuruk<218>etra war and the instrumental cause  of  the  immortal ç
 Bhagavadg<200>t<193>, Arjuna occupies a very important place in ç
the epic Mah<193>bh<193>rata. Born to Kunt<200>, the senior queen ç
of the King P<193><207><195>u, by the grace of the god Indra, Arjuna ç
exhibited his valour and skill in archery even from his childhood ç
days, thus becoming the most favourite disciple of Dro<207><193>c<193>rya, ç
the superb master of the science of archery. Bent upon settling scores ç
with the King Drupada, who had humiliated him, Dro<207><193>c<193>rya ç
sought Arjuna's help in humbling the king's pride. Arjuna responded ç
enthusiastically and fulfilled his guru's wish. Later, disguised as ç
a br<193>hma<207>a, Arjuna successfully pierced the matsya-yantra ç
(a contrivance for testing the skill in archery) and won the hand ç
of Draupad<200>, Drupada's daughter. However, a curious interference ç
of fate made Draupad<200>, the common wife of all the P<193><207><195>ava ç
princes. Apart from Draupad<200>, Arjuna had three more wives: Subhadr<193>, ç
Ul<220>p<200> and Citr<193><209>gad<193>.
Once he performed severe penance at the Indrak<200>la mountains to ç
propitiate Lord <185>iva. <185>iva however appeared in the guise of ç
a hunter chieftain and man- oeuvred a situation in which Arjuna was ç
obliged to fight him! Of course <185>iva was pleased with his courage ç
and prowess, and granted him the celestial weapon p<193>·upat<193>stra.
Living in disguise under the assumed name B<216>hannal<193> at the ç
court of the king Vir<193><219>a, he taught dancing to Vir<193><219>a's ç
daughter, Uttar<193>. Later he participated in the operation to rescue ç
Vir<193><219>a's cows from the clutches of the Kauravas, who were ç
decisively beaten in the battle.
Before  the  Kuruk<218>etra  war,  he approached <185>r<200> K<216><218><207>a ç
for help and preferred him (as his charioteer) to the Y<193>dava army ç
without K<216><218><207>a.
@SPACE1 = 
At the commencement of the war, he was overcome by intense remorse ç
and abhorrence of the killing involved, and refused to fight. After ç
<185>r<200> K<216><218><207>a's teaching (known as the Bhagavadg<200>t<193>) ç
dispelled his ignorance and delusion, he got up and fought, bringing ç
ultimate victory and glory to the P<193><207><195>avas.
After K<216><218><207>a's demise, he went to Dv<193>rak<193> and while ç
escorting the Y<193>dava ladies to Hastin<193>vat<200>, was ambushed ç
and conquered by robbers, thereby obliging him to realize that all ç
his strength had been derived from K<216><218><207>a's grace! He died ç
during the Mah<193>prasth<193>na (great journey), while ascending ç
to heaven.
Among his children, Abhimanyu, the son of Subhadr<193>, was slain ç
in the Kuru-k<218>etra war. Babhruv<193>hana, the son of Citr<193><209>gad<193> ç
became the ruler of Ma<207>ipura. Par<200>k<218>it, the son of Abhimanyu, ç
succeeded to the royal throne after its abdication by Yudhi<218><219>hira.
K<193>rtav<200>rya, the king of Haihaya, who was reputed to have one ç
thousand arms,was also known as Arjuna. (See <MS>K°RTAV®RY°RJUNA.<D>)
The  well-known  Buddhist  work Lalitavistara mentions one mathematician ç
Arjuna who was aware of the system of calculating numerals in multiples ç
of 100, commencing from ko<219>i (one crore), up to 1053.
@NT = <193>r<218>a-j<210><193>na
@N1 = (`sage-intuition')
Indian epistemology recognizes intuition as a valid source of knowledge. ç
Though normally the mind acquires know-ledge through the medium of ç
the organs of perception, it can do so even without them, under certain ç
conditions. Being next to the <193>tman (the soul) and capable of ç
reflecting its glory, mind has infinite potential for knowledge. This ç
potential is unfolded through spiritual disciplines.
In the case of the <216><218>is or sages, the power of the mind blossoms ç
forth due to learning, austerity and meditation. Through such a mind ç
they can intuit anything they wish to know. Such know-ledge as acquired ç
through the intuition of these sages is called `<193>r<218>aj<210><193>na.' ç
It is also called `pr<193>tibha-j<210><193>na' (intuitive know-ledge) ç
and is often equated with `yogi-pratyak<218>a' (yogic intuition).
Knowledge obtained in this way is distinct and vivid, and is free ç
from doubts or illusions. It always agrees with facts.
@NT = <193>r<218>a-li<209>ga
@N1 = (`linga pertaining to the <216><218>is')
<185>ivali<209>ga is one of the most ancient symbols  of  God  that  is  still  being ç
worshipped in India. Li<209>gas have been discovered in other countries ç
also, especi-ally in Mexico and South East Asia.
Out of the two types of li<209>gas, the cala (the movable) and the ç
acala or the sth<193>vara (the immovable), the latter is classified ç
under nine heads. The `<193>r<218>a-li<209>ga' is one among them. ç
It is defined as the li<209>ga set up and worshipped by <216><218>is ç
or sages. °r<218>a-li<209>gas are usually spheroidal in shape, resembling ç
an unhusked coconut fruit, and do not have the brahma-s<220>tra mark ç
on them.
See also <MS>BRAHMAS<188>TRA<D> and <MS>LI<177>GAS<D>.
@NT = <193>r<218>a-viv<193>ha
@N1 = (`marriage derived from the <216><218>is')
Hindu religion has accorded viv<193>ha or marriage the status of a ç
`sa<221>sk<193>ra,' a sacrament that purifies the embodied soul in ç
its journey towards perfection. Generally eight forms of marriage ç
are described, out of which the `<193>r<218>a' (derived from the <216><218>is ç
or sanctioned by the Vedas) is the third. In this form of marriage, ç
the father of the bride gifts her away to a suitable man after accepting ç
one or two pairs of cattle (cow, bull) as a gift, to fulfil the law ç
and not as a sale of the girl. The kany<193>d<193>na (gifting of the ç
maiden) is done in a ceremonial way.
See also <MS>VIV°HA<D>.
@NT = <193>rta
@N1 = (`afflicted with')
It is a matter of common experience that a person turns towards God ç
for succour when he is in trouble and when he discovers that he cannot ç
expect relief from human efforts alone. Diseases, accidents or danger ç
posed to life in critical situations make a man cry piteously to God ç
to come to his rescue. Such a person is called an `<193>rta' and his ç
devotion to God is classified as `<193>rtabhakti,' `devotion of the ç
afflicted' (vide Bhagavadg<200>t<193> 7.16).
Hindu mythological lore abounds in instances of such <193>rtabhakti: ç
Gajendra, the elephant king, praying for release from the clutches ç
of the crocodile; Draupad<200>, when molested by Du··<193>sana, crying ç
to K<216><218><207>a for help; M<193>rka<207><195>eya appealing to ç
<185>iva to protect him from Yama, the god of death.
@NT = artha
@N1 = (`that which is desired')
The <216><218>is (sages) of yore had recognized the innate human desire ç
for enjoying the pleasures of life and had provided for it in the ç
scheme of `puru<218><193>rthas' prescribed for human beings. The four ç
`puru<218><193>rthas' (dharma, artha, k<193>ma and mok<218>a) or ends ç
to be striven for in human life, have given `artha,' acquisition of ç
wealth and other objects of enjoyment, a very important place. However, ç
this `artha' should be within the perimeters permitted by `dharma' ç
or righteousness as defined by the holy scriptures and practised by ç
sages.
The word `artha' is commonly interpreted as `meaning,' meaning of ç
words, phrases and sentences. According to works on rhetoric, the ç
`artha' of a word can be of three types: v<193>cy<193>rtha (direct ç
meaning), lak<218>y<193>rtha (implied meaning) and vya<209>gy<193>rtha ç
(alluded meaning).
The first is illustrated by the sentence `g<193>m <193>naya,' (`Bring ç
the cow'); the second, by `kali<209>ga<199> s<193>hasika<199>,' (`the ç
Kali<209>ga is adventurous') where, though the word `Kali<209>ga' ç
literally stands for the country, is interpreted by implication, to ç
mean a citizenof that country. In the sentence `sa·a<209>kha-cakro ç
hari<199>,' (`Hari is with ·a<209>kha and cakra') though the word ç
hari<199> has several meanings like Vi<218><207>u, Yama, V<193>yu, ç
lion and monkey, it is confined to Vi<218><207>u only, due to the ç
allusion to ·a<209>kha (conch) and cakra (discus), which he alone ç
holds. That is the example for the third type.
In epistemology, `artha' stands for the objects apprehended by the ç
sense-organs.
See also <MS>PURU<186>°RTHAS<D>.
@NT = artha-kriy<193>-k<193>ritva
@N1 =  (`the capacity to produce a useful result')
Buddha denied permanent reality to anything that is perceived in this ç
world. Later Buddhist philosophers developed this into a regular school ç
called `k<218>a<207>ika-v<193>da' or theory of momentariness (k<218>a<207>a= ç
moment).
According to this theory, the criterion for the existence of a thing ç
is its capacity to produce (k<193>ritva) a useful effect (artha-kriy<193>). ç
From this criterion of existence, it may be deduced that a thing having ç
existence must be momentary. If, for example, an object like a seed ç
be not accepted to be momentary, but thought to be lasting for more ç
than one moment, then we have to show that it is capable of producing ç
an effect during the each moment it exists. Since it does not, we ç
conclude that it exists only for a moment.
@NT = artha-pa<210>caka
@N1 = (`the five truths')
<185>r<200>vai<218><207>avism is the religion of the Vi·i<218><219><193>dvaita ç
Ved<193>nta Dar·ana, the school of Ved<193>nta systematized by R<193>m<193>nuja ç
(<F51320P10MSC1>A.D.<F255P255DC255>1017-1137) and his followers. It prescribes ç
the knowledge of `arthapa<210>caka' or five truths, as very necessary ç
in s<193>dhana or spiritual practice. These five truths equip the ç
s<193>dhaka or the mumuk<218>u (the spiritual aspirant of emancipation) ç
with the correct perspective derived from the philosophy of s<193>dhan<193>.
They are: pr<193>pya (that which is to be obtained viz., ®·vara or ç
God), pr<193>pt<216> (one who obtains, the j<200>va or the individual ç
soul), up<193>ya (the means of achieving God), pr<193>ptivirodhi (that ç
which obstructs attainment of God) and pr<193>pti (attaining the highest, ç
i.e., God). The aspirant is expected to know the `svar<220>pa' or ç
nature of all these five truths.
These five are sometimes described as parasvar<220>pa (nature of the ç
highest), svasvar<220>pa (nature of the self), up<193>ya-svar<220>pa, ç
virodhisvar<220>pa and puru<218><193>rtha-svar<220>pa (nature of the ç
ends of human endeavour) also.
God who is `para' and `pr<193>pya' can manifest himself in five forms ç
as para (the highest form in Vaiku<207><219>ha), vy<220>has (emanations ç
like Sa<209>kar<218>a<207>a), vibhava (incarnations like R<193>ma), ç
arc<193> (icons of worship) and antary<193>min (the indwelling spirit).
@SPACE1 = 
The j<200>vas (individual souls) who are pr<193>pt<216>, have been ç
divided into five groups viz., nityas (the eternally free), muktas ç
(the liberated), baddhas (the bound), kevalas  (the  self-realized  souls)  and ç
mumuk<218>us (those desirous of liberation).
The well-known yogas of j<210><193>na and bhakti as also prapatti ç
(surrender to and dependence on the grace of God) and <193>c<193>ry<193>bhim<193>na ç
(surrender to and faith in the preceptor) are the up<193>yas recommended.
Identification of the body with the souldue to ignorance, disbelief ç
in divine incarnations, pursuit of worldly pleasures to the exclusion ç
of divine grace, doing things which will offend God, insulting devotees ç
of God†these are some of the obstacles listed under `pr<193>ptivirodhi.'
Pr<193>pti in the highest sense means living with God in the world ç
of Vaiku<207><219>ha in eternal service to Him.
Arthapa<210>caka is also the title of a famous work in Tamil by ç
Pi<202><202>ai Lok<193>c<193>rya (<F51320MS>A. D.<W1> 1264<192>1327), the ç
founder of the Te<209>galai or the Southern school of the <185>r<200>vai<218><207>ava ç
movement.
@SPACE = 
@NT = arth<193>patti
@N1 = (`that which is obtained<R>ç
through an established fact,' `Postulation')
@SPACE = 
The dar·anas or Indian philosophical systems have bestowed considerable ç
attention on the methods of obtaining know-ledge. Means of such knowledge ç
vary from three to six. It is the P<220>rva-m<200>m<193><221>s<193> ç
system that accepts and describes six such means, which by the way, ç
form the maximum of such series.
`Arth<193>patti' or `postulation' is the penultimate in this series. ç
It is described as the necessary supposition of an un- perceived fact ç
which alone can explain a phenomenon that demands an explanation. ç
Suppose it is observed that a man is fasting during the day and yet ç
is growing fat. It is impossible to reconcile these two facts†fatness  and  fasting†unless  we ç
admit that he eats at night! This postulation is `arth<193>patti.'
The M<200>m<193><221>sakas and Advaitins maintain that this is a distinctive ç
source of knowledge whereas others include it under `anum<193>na' ç
or inference. 
See also <MS>PRAM°ØAS<D>.
@NT = Artha·<193>stra
@N1 = (of Kau<219>ilya)
@EMERGENCY = Hinduism has accorded `artha' or wealth (which also includes ç
power), which is the most important means of enjoyment in this world, ç
the status of a `puru<218><193>rtha,' one of the four values to be ç
striven for in life. Acquisition and enjoyment of wealth are impossible ç
unless there is enough social security and peace. This is guaranteed ç
only when there is a strong and just head of the State. Hence, statecraft ç
becomes an extremely important branch of knowledge and a highly specia-lized ç
discipline.
@EMERGENCY = Speculations on this subject have been traced to the ç
<184>gveda. <185>aunaka's Cara<207>avy<220>ha lists `Artha·<193>stra' ç
as an Upaveda of Atharvaveda. The epics and the dharma·<193>stra ç
literature have given abundant material on it. There is reason to ç
believe that four distinct schools and thirteen teachers of Artha·<193>stra ç
had existed before the 4th century <F51320MS>B. C.<W1> However the loss ç
of this fairly extensive literature is to be attributed to its supersession ç
by the masterly treatise of Kau<219>ilya, which itself was recovered ç
from oblivion by the providential discovery of a complete manuscript ç
and its publication with an English translation by R. Shama Sastry ç
of Mysore in 1908.
This Artha·<193>stra of Kau<219>ilya has been assigned to the period ç
321<192>300 <F51320MS>B. C.<W1> and the authorship attributed to Vi<218><207>ugupta-C<193><207>akya, ç
nicknamed `Kau<219>ilya' (`the crafty'), the renowned preceptor of ç
the emperor Candragupta Maurya. Not much is known of his life. Hailing ç
from a place called Ca<207>aka†hence the appellation C<193><207>akya ç
to him†near Tak<218>a·il<193> (near Peshawar, Pakistan), he was well-versed ç
in the Vedic lore and had remained a celibate for life. Endowed with ç
a keen intellect, tremendous will-power and pride, he is said to have ç
been once insulted byMah<193>padma Nanda, the monarch of Magadha. ç
Furious at this humiliation, he swore vengeance on the Nanda dynasty ç
and left P<193><219>al<200>putra, the capital of Magadha. Having spotted ç
Candragupta, the son of Mur<193> by Mah<193>padma Nanda, as the worthy ç
candidate for thethrone, he trained him for the high responsibility. ç
He seized the throne in 321 <MS>B. C.<W1> and installed Candragupta ç
as the King. Later, he inspired Candragupta to drive away the Greek ç
invaders, build and consolidate the first empire known to recorded ç
Indian history. He later contrived to bring back R<193>k<218>asa, ç
the premier of the Nandas as the prime minister, and retired into ç
solitude for a contemplative life.
@SPACE1 = 
The word `Kau<219>ilya' is sometimes spelt as `Kau<219>alya' and defined ç
as a `descendent of the gotra Ku<219>ala,' probably to avoid the odium ç
of the literal meaning. Many scholars do not subscribe to this view.
The Artha·<193>stra comprises 6000 ·lokas (stanzas of 32 letters) ç
divided into 15 adhikara<207>as or sections and dealing with 180 prakara<207>as ç
or topics. The first part consisting of adhikara<207>as 1 to 5 is ç
called `Tantra' and deals with the topic of providing security and ç
prosperity to the people by the king. The second part (adhikara<207>as ç
6<192>13) is termed `°v<193>pa' and concerns itself with keeping watch ç
over the neighbouring rulers. The third and the last part (adhikara<207>as ç
14 and 15) treats of whatever is left over and hence christened `<185>e<218>a.'
The contents of the various adhi-kara<207>as may be briefly summarized ç
as follows:
@S10N = Adh. 1 (18 prakara<207>as)
@EMERGENCY = The education and discipline of the king, qualifications ç
and testing of ministers, institution of spies, ambassadors, protection ç
of princes and harem, king's personal safety.
@S10N = <P9B>Adh. 2 <P255D>(38 prakara<207>as)
@EMERGENCY = Superintendents  of  the  various departments of the ç
State, founding of villages,  building  forts,  afforestation, commissioners ç
for revenue from various departments, duties of the accountant- general, ç
prevention of and punishment for embezzlement of public funds, building ç
up the treasury.
@S10N = <P9B>Adh. 3 <P255D>(19 prakara<207>as)
@EMERGENCY = Administration of justice, forms of marriage, duties ç
of married couples and allied topics.
@S10N = <P9B>Adh. 4<P255D> (13 prakara<207>as)
@EMERGENCY = Protection of merchants, artisans and others, remedies ç
and relief during national calamities, suppression of and punishment ç
for  crime,  protection  to  the  various departments of the State.
@S10N = <P9B>Adh. 5 <P255D>(7 prakara<207>as)
@EMERGENCY = Conduct of courtiers, punishment fortreason, replenishing ç
treasury in emergencies.
@S10N = <P9B>Adh. 6 <P255D>(2 prakara<207>as)
@EMERGENCY = Constitution of the ma<207><195>ala (group of kings), ç
seven elements of sovereignty, qualities of a king, sixfold royal ç
policy, threefold ·akti.
@S10N = <P9B>Adh. 7 <P255D>(29 prakara<207>as)
Six possible causes of action like peace,  war,  neutrality,  alliance  etc.; ç
conduct of a mediatory king and a neutral king.
@S10N = <P9B>Adh. 8 <P255D>(8 prakara<207>as)
Vyasanas (vices and misfortunes) of the several elements of sovereignty, ç
troubles of the king and kingdom.
@S10N = <P9B>Adh. 9 <P255D>(12 prakara<207>as)
Organizing invasions.
@S10N = <P9B>Adh. 10 <P255D>(13 prakara<207>as)
About war.
@S10N = <P9B>Adh. 11 <P255D>(2 prakara<207>as)
On corporations and guilds.
@S10N = <P9B>Adh. 12 <P255D>(9 prakara<207>as)
How to deal with a powerful enemy through envoys, intrigues, spies ç
and stratagems.
@S10N = <P9B>Adh. 13 <P255D>(6 prakara<207>as)
Ways to capture the fort of an enemy, entice him, and restore peace ç
in the conquered territory.
@S10N = <P9B>Adh. 14 <P255D>(3 prakara<207>as)
Secret recipes for eliminating or incapacitating the enemy.
@S10N = <P9B>Adh. 15 <P255D>(1 prakara<207>a)
Appendix of the plan of this work, illustrating the methodological ç
principles.
The work shows clearly that Kau<219>ilya was a master in various branches ç
of sciences and a social reformer endowed with robust commonsense ç
and practical wisdom. His views on divorce, remarriage of  widows  and  wives  under  certain ç
conditions, stressing the life here and now as important, his lenience ç
towards certain human weaknesses like gambling are, by any standards, ç
revolutionary. Scholars like P. V. Kane opine that the Y<193>j<210>avalkya ç
Sm<216>ti is a later composition and has borrowed liberally from ç
Kau<219>ilya's work.
Two commentaries on the work by Bha<219><219>asv<193>min and M<193>dhavayajvan, ç
have been discovered. But both are fragmentary.
@NT = arthav<193>da
@N1 = (`statement of meaning')
Out of the six systems of Indian philosophy accepting the authority ç
of the Vedas, the P<220>rva M<200>m<193><221>s<193> has devoted itself ç
exclusively to the methods of correct interpretation of the Vedic ç
texts. It divides the entire Veda into two parts: vidhi or injunction, ç
and arthav<193>da or statements explaining or reiterating certain ç
facts already known through other means.
Vidhi refers to supramundane affairs and has to be understood literally. ç
In contrast to this arthav<193>da relates to matters of ordinary experience ç
and hence carries with it no logical significance. Its main purpose ç
is to make us do certain good things by praising them or reject bad ç
ones by censuring them. Hence it should never be taken literally. ç
For instance when it is stated that `the sacrificial post is the sun,' ç
it simply means that the post is bright like the sun and is intended ç
to commend the sacrifice in the performance of which, the post is ç
used.
Arthav<193>da is of three types: gu<207>a-v<193>da, anuv<193>da and ç
bh<220>t<193>rthav<193>da. When a statement is contradicted by another ç
means of proof†as for instance, in the sentence already quoted, direct ç
perception contradicts the post being the sun†it has to be interpreted ç
by considering the statement as gau<207>a or secondary, the primary ç
sense conveyed being brightness. Such an arthav<193>da is called gu<207>av<193>da.
When the stated meaning has already been established by other means ç
of know-ledge as in `Fire is an antidote of cold,' wherein the fact ç
stated is a matter of direct experience, the statement itself is to ç
be considered as an anuv<193>da, a reitera- tion of a fact already ç
established.
In bh<220>t<193>rthav<193>da, an occurence which happened in the past ç
(bh<220>ta = past) is stated. Since it can neither be confirmed nor ç
denied, it has to be accepted as it is. For instance, a statement ç
such as `Indra raised his thunderbolt to strike at V<216>tra' has ç
got to be accepted at its face value since there is no way of proving ç
or disproving it.
According to another classification, arthav<193>da is of four kinds: ç
nind<193> (censure), stuti (eulogy), parak<216>ti (performance by ç
another great person) and pur<193>kalpa (what happened in bygone ages).
The first is meant to prevent certain acts and the second to impel ç
doing certain others. The third is also meant to praise certain acts ç
and induce us to do them. The last demonstrates something that has ç
been narrated by another as having taken place in the past.
See also <MS>P<188>RVAM®M°<189>S°-DAR<185>ANA.<D>
@NT = Aru<202>nandi, Aru<207>andi
<185>aivism, centred round the worship of <185>iva, is a very ancient ç
religious cult of India. <185>aivasiddh<193>nta, also known as Tamil ç
<185>aivism, is an important contribution to the <185>aiva lore of ç
South India. Its basic canonical works were composed by Meyka<207>d<193>r, ç
Aru<202>nandi (also spelt as Aru<207>andi), J<210><193>na Sambandhar ç
and Um<193>pati, all of whom lived during the period 13th<192>14th ç
centuries. These four have been designated as `San<193>tana °c<193>ryas' ç
or ancient teachers.
Aru<202>nandi was the family preceptor of the young Meyka<207><195><193>r. ç
The story goes that puffed up with vanity, he once asked his pupil ç
Meyka<207><195><193>r about the nature of ignorance. Meyka<207><195><193>r, ç
the young saint simply looked at the proud questioner himself as if ç
in reply. The teacher immedi-ately realized that he himself had been ç
pointed out as a specimen of ignorance, and, overcome by shame, became ç
a disciple of the young saint, assuming the name Aru<202>nandi <185>iv<193>c<193>ri<193>r.
He has written a commentary called <185>ivaj<210><193>nasiddhi on ç
Meyka<207><195><193>r's basic work <185>ivaj<210><193>nabodha which ç
itself is in twelve s<220>tras or aphorisms. This work is in two parts, ç
the first, `Parapakkam,' refuting other schools of philosophy and ç
the second, `Supakkam,' expounding the fundamentals of his own school. ç
The latter is in verse and is considered to be a commentary   on   Meyka<207><195><193>r's   work. ç
Another work, Irup<193>virupabtu is also attributed to Aru<202>nandi.
@NT = Aru<207>a
@N1 = (`the red one')
Aru<207>a, the charioteer of S<220>rya, the Sun-god, was the first ç
son of the sage Ka·yapa and Vinat<193>. Since her pregnancy lasted ç
too long, Vinat<193> impatiently pressed her womb, resulting in the ç
deformity of limbs to the unborn child. So, Aru<207>a was born without ç
thighs. (Hence the name an<220>ru,  one  without  thighs.)  He  was ç
appointed by the gods as the charioteer of S<220>rya. He is red in ç
colour and imparts his hue to the sky as he drives in the chariot.
Garu<195>a, the famous mount of Vi<218><207>u, is his younger brother. ç
Samp<193>ti and Ja<219><193>yu the two giant birds mentioned in the ç
R<193>m<193>ya<207>a are his sons.
Aru<207>a is also the name of a demon killed by the goddess Durg<193>, ç
in her aspect as Bhramar<193>mb<193>.
@NT = Aru<207>agirin<193>thar
A work, Tiruppuga<202> containing soul-stirring hymns on Lord Muruga ç
(Subrah-ma<207>ya), is very popular in Tamil Nadu. The author Aru<207>agirin<193>thar, ç
a <185>aiva saint, lived in the 15th century. It is said that he had ç
an infamous birth and led a riotous life in his youth. A simple remark ç
from his own sister caused such an intense remorse that he tried to ç
commit suicide by jumping from the high tower of the temple. However, ç
God saved him in a miraculous way. Thenceforth he dedicated his life ç
for God. Sublime poetry welled forth from his heart as a result of ç
divine grace showered on him. Some other treatises are also attributed ç
to him.
@NT = Arundhat<200>
Arundhat<200>, the famous wife of the famous sage Vasi<218><219>ha, ç
is considered as the paragon of wifely virtues. She was the daughter ç
of Praj<193>pati Kardama and Devah<220>ti. Atri's wife Anas<220>y<193> ç
was her sister and the sage Kapila, her brother. The <216><218>i <185>akti ç
was her son. She was as erudite as her husband and was an <193>c<193>ry<193> ç
(preceptor) in her own right.
She is said to exist in the form of a nak<218>atra or a star. The ç
`Arundhat<200>-nak<218>atra' is identified as the star Alcor, belonging ç
to the Great Bear group.
It is obligatory for newly married couples to see the Arundhat<200> ç
nak<218>atra. Since it is very dim and scarcely visible, the priest ç
shows the brighter stars nearby and then gradually directs their eyes ç
to the real Arundhat<200>. This is known as `Arundhat<200> Dar·ana ç
Ny<193>ya' or simply as `Arundhat<200> Ny<193>ya.' It signifies the ç
method of leading from the gross to the subtle, from the known to ç
the unknown, in logic and philosophy.
Arundhat<200> is also the name of a medicinal plant used to heal serious ç
wounds.
@NT = Arundhat<200> Dar·ana Ny<193>ya
@NT = Arundhat<200> Ny<193>ya
See <MS>ARUNDHAT®.<D>
@NT = °ru<207>ey<200> Upani<218>ad
Known also as `°ru<207>i<F14M>-<F255D>' and `°ru<207>ika<F14M>-<F255D>' Upani<218>ad, ç
it is a minor work belonging to the S<193>maveda. It deals with ç
sa<221>ny<193>sa or monastic life.
The sage °ru<207>i goes to the abode of Praj<193>pati (`Lord of beings;' ç
same as Brahm<193>, the Creator) and asks Him how he can give up all ç
actions. Praj<193>pati replies that he should give up his family and ç
friends, the holy thread, the sacrificial system and the scriptures ç
that advocate them and the desire for attaining any of the well-known ç
worlds or planes of exis-tence. He should accept sa<221>ny<193>sa ç
or monastic life. This is the first section.
The next section clearly states that anyone, from any state of life, ç
can take to the monastic life, intense spirit of renunciation being ç
the only criterion. The process of ceremonially giving up the sacred ç
thread (yaj<210>opav<200>ta) and the fires, and the exhortation to ç
study the °ra<207>yakas and Upani<218>ads, follow next.
The third section gives the well-known prai<218>amantra, the sacred ç
formula to be repeated thrice, signifying that the aspirant has totally ç
renounced the three worlds. A Vedic prayer for protection, instructions ç
regarding food, wearing of the loin-cloth and observance of disciplines ç
like brahmacarya (chastity), ahi<221>s<193> (non-injury) and satya ç
(truthfulness) are given at the end.
The fourth section deals with the conduct of `paramaha<221>sa-parivr<193>jaka,' ç
the highest class of itinerant monks. They should sleep on the ground, ç
use a bowl of clay, gourd or wood for water, give up lust, anger, ç
avarice and other evil passions and constantly move about, all alone, ç
except during the rainy season. (See <MS>C°TURM°SYA.<D>)
The last section describes the mode of begging, uttering the sacred ç
`O<221>,' and closes with a well-known Vedic prayer that describes ç
the state of enlightenment of sages.
See also <MS>SA<189>NY°SA<D> and <MS>UPANI<186>ADS<D>.
@NT = °ru<207>i
°ru<207>i, son of Aru<207>a Aupave·i, is one of the more important ç
teachers mentioned in the Upani<218>ads. When he was under- going ç
training in Vedic studies, his guru Dhaumya once commanded him to ç
stop the water that was leaking out of his fields. °ru<207>i lay across ç
the breach and stopped it. Hence, he came to be known as Udd<193>laka ç
(`One who bound or fastened the bund'). Gautama is another appellation ç
for him. <185>vetaketu was his son.
He once went to the king Prav<193>ha<207>a Jaivali and was humble ç
enough to learn about the Pa<210>c<193>gnividy<193> or the `doctrine ç
of five fires' from him.
When he discovered that his son <185>vetaketu was puffed up with pride ç
after returning from his teacher's house, due to Vedic learning, he ç
put him a fundamental question: `Have you known that by knowing which, ç
all the unknown becomes known?' Since <185>vetaketu did not know and ç
requested him to teach it, °ru<207>i taught him this esoteric wisdom. ç
(vide Ch<193>ndogya Upani<218>ad, chapter 6.)
@NT = °ryabha<219>a
Studies in Indian history and culture have revealed that India had ç
excelled not only in the spiritual sciences but also in the secular ç
sciences. The names and works of several eminent scholars whose fields ç
of work have embraced several disciplines like  medicine,  surgery,  mathematics, ç
astro- nomy, astrology, politics, economics, dramatics, dance, music, ç
fine-arts, architecture, chemistry, alchemy, archery etc., have been ç
mentioned in the ancient and medieval works.
Among these, °ryabha<219>a is one important name associated with mathematics ç
and astronomy. Historians have discovered two °ryabha<219>as in their ç
researches.
°ryabha<219>a I (5th cent. <F51320P10MSC1>A. D.<W1>) was an astronomer and ç
mathematician who lived in Kusumapura (P<193><219>al<200>putra). His ç
work called <F255P255MIC255>°ryasiddh<193>nta (laghu) is a concise work ç
in four chapters. The first chapter (Da·ag<200>tik<193>) comprises ç
of ten verses in the g<200>tik<193> metre and is introductory. The ç
second (Ga<207>itap<193>da) deals with several aspects of mathematics. ç
The third (K<193>la-kriy<193>) is concerned with the reckoning of ç
time and the last (`gola') expatiates on astronomy.
Aryabha<219>a II lived in the 10th cent. <F51320P10MSC1>A. D.<W1> The work ç
<F255P255MIC255>°ryasiddh<193>nta is attributed to him. It is in 18 chapters ç
and deals with  arithmetic  and  algebra  as  also astronomy. Mah<193>bh<193>skar<200>ya ç
seems to be another title for the same treatise.
@NT = Aryaman
@N1 = (`destroyer of foes')
Aryaman or Aryam<193> is one of the Vedic deities mentioned as an ç
aspect of °ditya, the sun. He is the third among the twelve °dityas. ç
Mythological lore describes him as a son of the sage Ka·yapa and his ç
wife Aditi and as the chief of pit<216>s or manes.
@NT = °ryans
Did the °ryans originate in India or did they migrate from elsewhere? ç
This question has been debated for over 150 years without arriving ç
at any definite conclusions. If one group of scholars thinks that ç
they migrated from Central Asia (near the Capsian Sea) others like ç
Tilak opine that they lived near the Arctic region from where they ç
trekked to southern Europe, Iran and India. Quite a few others have ç
endeavoured to prove that they originally lived in the Indo-Gangetic ç
region itself. Recent French excavations at the Mehr-garh site near ç
the Bolan Pass in Pakistan seem to confirm this view, taking the date ç
of<|>the Indus Valley<|>Civilisation to 6500<MS><|>B.C.<D>
However there is no doubt that the word ``<193>rya'' has been used ç
widely to denote any cultured and refined person.
Many interesting details about the life and culture of the °ryans ç
can be gathered by a study of the <184>gveda. They lived primarily ç
by agriculture and dairy farming. Though cattle were the chief domesticated ç
animals, sheep, goats and horses were also their common possession. ç
Yava (barley) was the chief food grain raised and used by them.
Apart from milk, curds, ghee and flour, they used to consume soma ç
juice and sur<193> (liquor) also. Consumption of liquor was however ç
condemned. Meat- eating was not uncommon.
Apart from villages, they could build forts and towns also. They were ç
good in constructing chariots as also ships, knew weaving of cloth ç
as also tanning and preparing leather goods. They were fami-liar with ç
various kinds of irrigation. Chariot race, hunting and gambling were ç
common sources of recreation. Cows and goods were used as money. Later ç
on, gold and silver coins came into existence.
The father was the head of the family. Mother was however, highly ç
respected. Marriage ties were considered very sacred. Women could ç
choose their husbands. The wife had an important role to play in the ç
performance of Vedic rites. Monogamy seems to have been the rule though ç
poly- gamy was common among the k<218>attriyas. Couples hankered after ç
children, especially good sons. Widows had a share in their husbands' ç
property. Remarriage of widows was prevalent, though rare.
@SPACE1 = 
People lived in groups, each group electing its own ruler or king. ç
In course of time the office of the king became hereditary. The king ç
would take guidance from the wise elders in administration. They would ç
also employ purohits (priests) who exercised a great influence over ç
the kings and the State. All religious activities were conducted and ç
supervised by them. The kings would generously reward them. Performance ç
of big sacrifices like A·vamedha and R<193>jas<220>ya by the more ç
powerful kings was common.
The caste system as we know it did not exist in the beginning. The ç
division of the society into four var<207>as was however, a recognised ç
fact.
Sanskrit, in its archaic form, was the language of the people.
Religion of the °ryans (sometimes called °ryanism) consisted predominantly ç
of yaj<210>as and y<193>gas (sacrifices), which included animal sacrifices, ç
performed mostly for worldly gains like longevity, wealth, progeny ç
or a place in heaven. Belief in one God, as also several deities like ç
Indra, Mitra, Varu<207>a or Vi<218><207>u, often eulogized as the ç
Supreme Deity or as manifestations of the one God, is seen in several ç
of the mantras of the <184>gveda. Temples and worship as we know ç
them today do not seem to have existed then.Reckoning of time, especially ç
for religious purposes, was done both with respect to the movement ç
of the sun and the moon.
The °ryans believed in life after death. In disposing of the dead ç
bodies, both cremation and burial seem to have been in vogue. After ç
death, the soul was believed to go to pit<216>loka (world of manes) ç
or svarga (heaven) or to hell.
@SPACE1 = 
Modern Hinduism, both in its reli-gious and cultural aspect, retains ç
quite a few of the Vedic customs, either in a pure or in a metamorphosed ç
form.
@NT = °ryasam<193>j
@EMERGENCY = Any religion and culture which gives freedom to its adherents ç
for self-introspection and self-criticism naturally paves the way ç
for rejuvenation and renaissance. Thanks to the immense freedom of ç
thought and expression enjoyed by its adherents, Hinduism has passed ç
through several phases of renaissance.
The °ryasam<193>j founded by Sv<193>m<200> Day<193>nanda Sarasvat<200> ç
(<F51320P10MSC1>A. D.<W1> 1824-1883) is one of the more important reform ç
movements of Modern Hindu renaissance initiated during the 19th century. ç
It came as a reaction to the two-way decline of the Hindu society, ç
the first being the loss of faith in its own religion due to the impact ç
of English education and Western culture; and the second being the ç
devitalization brought about by the onslaughts of Islam and Christianity.
@EMERGENCY = It was formally established in 1875 with a creed of 28 ç
principles which were later reduced to 10 in the revision brought ç
about in 1877. Belief in Brahman the one God and in the infallibility ç
of the Vedas is the central part of the creed. Since only the Vedas ç
were accorded the highest place, much of the later Hindu thought, ç
belief and ritualism were given the go by. Even the Upani<218>ads ç
and the G<200>t<193> were relegated to the background.
@SPACE1 = 
@EMERGENCY = However, the °ryasam<193>j fulfilled a very important ç
and urgent need of the Hindu society by instituting the ·uddhi movement ç
(reconversion into Hinduism). A sizeable section of the Indian population ç
which had become alienated from the Hindu religion and society due ç
to historical and other factors, was reclaimed into the Hindu fold.
By abolishing caste among its followers, investing all of them with ç
the yaj<210>opa- v<200>ta (sacred thread) and giving the G<193>yatr<200> ç
mantra to them, °ryasam<193>j has helped in the consolidation of Hindu ç
society, at least in those parts of India which have come under its ç
influence. It also sponsored socialreform by advocating remarriage ç
of widows, abolition of child marriage and untouchability. It has ç
done great service in the field of education and spread of Sanskrit ç
language. Its sphere of influence was mostly confined to Punjab and ç
Uttar Pradesh.
The militant approach of the °ryasam<193>j created many enemies for ç
it which resulted in the martyrdom of some of its leaders.
Within ten years of its founder's death, the movement split into two, ç
one group advocating modernism also and the other devoted to orthodoxy.
See also <MS>DAY°NANDA SARASVAT®, SV°M®<D>.
@SPACE = 
@NT = °ry<193>varta
@N1 = (`the land of the °ryans')
From the most ancient times, the region between the Him<193>layas ç
and the Vindhya mountains, demarcated by the western  and  eastern  seas,  has  been ç
declared as the `°ry<193>varta,' the land of the °ryans, `the refined ç
and cultured people.' Black antelopes roam about this land. It was ç
believed that it was a holy land and that only people with pu<207>ya ç
(religious merit) would have the privilege of being born there.
Of course, there are other descriptions according to which there are ç
slight variations to its geographical limits.
@NT = °<218><193><195>ha
The fourth month of the Hindu lunar calendar is called °<218><193><195>ha ç
(June-July) when the full-moon is said to be near the constellation ç
°<218><193><195>h<193>. The ek<193>da·<200> (11th day) of the bright ç
fortnight of this month is christened `·ayan<200>' since it was believed ç
that Lord Vi<218><207>u went to bed on this day, to wake up again ç
on the ek<193>da·<200> of k<193>rttika bright fortnight, called `prabo-dhin<200> ç
or bodhin<200>.' The legend of Vi<218><207>u's going to bed for four ç
months might be symbolic of the disappearance of the sun (who is also ç
Vi<218><207>u) behind the clouds during the rainy season.
The deity Subrahma<207>ya (also known as <186>a<207>mukha and Skanda) ç
is associated with this month. The sixth day of the bright fortnight ç
called `Skanda<218>a<218><219>h<200>' is an important festival observed ç
especially in South India.
@NT = asamav<193>yi-k<193>ra<207>a
@N1-1 = (`non-inherent cause')
The Vai·e<218>ika Dar·ana (a logical system of Indian philosophy attributed ç
to the sage Ka<207><193>da) recognizes seven pad<193>rthas or categories ç
of reality, out of which samav<193>ya or the relation of inhe-rence ç
forms the sixth. It is the eternal relationship that subsists between ç
the whole and the parts, the quality or an action and the substance ç
possessing or doing it and so on.
Clay is the material cause for the jug. The two are inseparable. Hence, ç
clay is called the samav<193>yi-k<193>ra<207>a, an inherent cause, ç
of the jug. However, the colour of the jug is not caused by the clay, ç
but by the colour of the clay which again exists in clay by samav<193>ya. ç
Hence, the colour of the clay is said to be the asamav<193>yi-k<193>ra<207>a, ç
a non-inherent cause, of the colour of the jug.
@SPACE = 
@NT = asampraj<210><193>ta
@N1 =  (`ultra-cognitive<R>ç
absorption')
@SPACE = 
Out  of  the  <186>a<195>-dar·anas  or  six systems of Indian philosophy, ç
that of Pata<210>jali (200 <F51320P10MSC1>B.<|>C.<W1>) known as the <F255P255MIC255>Yoga-s<220>tras, ç
is very popular since it gives highly practical methods of controlling ç
the mind.
When a systematic attempt is made to control and eliminate the v<216>ttis ç
or modifications of the mind through the practice of the various steps ç
of yoga such as yama and niyama, it will result in `sam<193>dhi,' ç
total absorption in the object of contemplation.
This sam<193>dhi is of two types: sam-praj<210><193>ta  (cognitive)  and  asampraj<210><193>ta ç
(ultra-cognitive). In the former, the object of contemplation will ç
be vividly revealed. In this state, though all other mental modifications ç
are eliminated, that of theobject of contemplation continues to remain ç
active. Hence in the strictest sense of the definition of `yoga' as ç
`cittav<216>tti- nirodha' (Yogas<220>tras 1.2) (`suppression of ç
modifications of mind') this sam<193>dhi indicates a lower state of ç
yoga. As opposed to this, in the higher sam<193>dhi called asampraj<210><193>ta, ç
all modifications of mind are eliminated, leaving only the sa<221>sk<193>ras ç
(latent tendencies) behind. (vide Yoga-s<220>tras 1.18). In this ç
state, it looks as though even the mind does not exist, since there ç
are no mental modifications to reveal its presence.
This sam<193>dhi is sometimes called `nirb<200>ja-sam<193>dhi' (seedless ç
sam<193>dhi) since the seeds of rebirth are eliminated as a result ç
of this experience.
Intense vair<193>gya (`paravair<193>gya') or detachment is said to ç
be the means of achieving this sam<193>dhi.
See also <MS>YOGADAR<185>ANA<D>.
@NT = <193>sana
@N1 = (`posture,' `seat')
Though <193>sanas are a very popular mode of exercise, the word `<193>sana' ç
has a much wider connotation and deeper signi-ficance. Pata<210>jali, ç
the great master of yoga, has listed <193>sana as the third of the ç
eight steps of yoga. According to him, any posture in which the yogi ç
can sit steadily and comfortably, is `<193>sana.' This <193>sana can ç
be mastered through meditation on the infinite and by a relaxation ç
of the body and mind. When this technique of <193>sana is perfected, ç
the yogi acquires immunity from the effects of pairs of opposites ç
like heat and cold, hunger and thirst, happiness and misery (vide ç
Yoga-s<220>tras 2.46, 47 and 48). Out of the six <193>sanas that ç
are recommended as suitable for meditation, padm<193>sana and svasti-k<193>sana ç
are supposed to be the best.
°sanas as physical postures come under the purview of another branch ç
of yoga, known as `Ha<219>hyoga.' These <193>sanas, it is claimed, ç
can cure diseases, improve health and help in meditation. Though the ç
typical posture of every living being can serve as a model for an ç
<193>sana, only 84 <193>sanas are handed down in tradition as especially ç
suitable for human beings. Out of these again, only 32 are more in ç
vogue.
°sana can also mean a seat. Various kinds of seats have been recommended ç
as suitable for meditation. Seats made of ku·a grass, deer-skin, tiger-skin, ç
woollen rug or silk cloth have been mentioned in the works on yoga, ç
along with the fruits one will get by using them.
See also <MS>YOGADAR<185>ANA<D> and <MS>YOG°SANAS<D>.
@NT = <193>sanam<220>rti
@N1 = (`image in the seated<R>ç
posture')
The Hindu temple is an ancient institution. The images that are installed ç
inside the shrines or inscribed on the walls and the pillars should ç
be prepared strictly according to the rules of `m<220>rti·ilpa·<193>stra' ç
or iconography. Such m<220>rtis or images of gods and goddesses are ç
generally divided into three kinds depending upon their posture: the ç
sth<193>naka or standing, the <193>sana or sitting and the ·ayana ç
or lying down.
The <193>sanam<220>rtis again can be of various types depending on ç
the particular <193>sana or posture adopted. At least twenty <193>sanas ç
are mentioned in the iconographical works. To name a few: <193>l<200><195>ha, ç
k<220>rma, dhy<193>na, padma, parya<209>ka, yoga, bhadra, v<200>ra ç
and svastika.
@NT = asat
@N1 = (`the non-existent')
See under <MS>SAT<D>.
@NT = asatk<193>ryav<193>da
@N1 = (`the theory of<R>ç
non-existent effect')
The relationship between a cause (like clay) and its effect (like ç
the pot) has provided enough material for discussion in Indian philosophy. ç
Several theories have been advocated in which this relationship has ç
been sought to be explained. `Asat-k<193>rya-v<193>da' is the theory ç
that has been put forward by the schools of Buddhism and of Ny<193>ya-Vai·e<218>ikas.
When the pot, the effect, is produced from clay, its cause, two explanations ç
are possible. The effect, which already existed in its cause in a ç
subtle form, was mani- fested when favourable circumstances were created; ç
because a real effect cannot be produced from an unreal or non-existing ç
cause. This theory is called `satk<193>ryav<193>da' and is advocated ç
generally by the S<193><209>khya system. The other explanation is ç
that the effect, which is something new, is produced as a result of ç
the efforts of the potter and his implements, even though it did not ç
exist earlier. If the clay and the pot were not different from each ç
other, we should have used the same name for both and they should ç
have served the same purpose. But this is not so. Hence according ç
to this view, a real effect (`k<193>rya') is produced from the cause ç
though it did not exist earlier (hence unreal or `asat') in that cause. ç
Therefore the name `asatk<193>rya-v<193>da.'
@NT = asatkhy<193>ti
See <MS>KHY°TIS<D>.
@NT = asatya
@N1 = (`untruth')
See <MS>SATYA<D>.
@NT = a·auca, <193>·auca
@N1 = (`uncleanness')
Birth and death occurring in a Hindu family were believed to bring ç
about a·auca (also spelt as <193>·auca) or ceremonial impu-rity not ç
only on all its members but also on the near relatives. Though the ç
dharma-·<193>stras have dealt with this subject in great detail, the ç
exact reason, why such a·auca is to be observed, has not been clearly ç
indicated.
A·auca at birth was called `janm<193>·auca' and that at death, `m<216>t<193>·auca.' ç
`S<220>taka' was another general term applied to both, but more for ç
the latter than for the former.
The period of a·auca varied from one month to one day, there being ç
no unani-mity among the writers. Ten days, three days or one day seem ç
to be more common. During these days of a·auca, the members of the ç
family were practically treated as untouchables, and they temporarily ç
lost their religious privileges. After the comple- tion of the period ç
they were to bathe, change clothes and perform certain ·<193>ntis ç
or propitiatory religious rites.
People occupying important places in society, whose duties and works ç
were essential for the general welfare of the community, were exempted ç
from the obser- vance of a·auca: for instance, the doctor, the craftsman ç
and so on. The king had the power to grant such exemptions to anyone, ç
using his discretion.
@NT = <193>·aya
@N1 = (`that which rests [in the mind]')
Hinduism believes in rebirth. The soul of any being, though immortal, ç
continues to be born again and again due to its karma or the subtle ç
unseen deserts. This goes on until it gets mok<218>a or liberation ç
from this cycle of births and deaths.
It is this `karma' that has been called `<193>·aya' or `karm<193>·aya' ç
by some scriptures like the Yogas<220>tras of Pata<210>jali (1.24; ç
2.12). It has been called `<193>·aya' since it `rests in the mind' ç
(·aya = resting) `until' (<193>=until) it fructifies. It is of the ç
form of pu<207>ya (merit) and p<193>pa (de-merit) andis generated ç
by k<193>ma (desire), lobha (greed), moha (delusion) and krodha (anger). ç
Its results may be experienced either in this life itself or in future ç
births.
@NT = ascetics
Hindu asceticism is a very ancient institution. Munis (men of contemplation) ç
and yatis (men of self-control) are mentioned even in the <184>gveda. ç
Tapas (auste-rity), vair<193>gya (detachment), ty<193>ga (renunciation), ç
brahmacarya (celibacy) are virtues extolled in the Vedic and Upani<218>adic ç
literature. Sa<221>ny<193>sa (monastic life) as one of the four <193>·ramas ç
(stages of life) is well-known.
Dissatisfaction with the worldly life, hope of finding eternal peace ç
and faith in the state of liberation called mok<218>a, must have prompted ç
some people to take to the ascetic way of life as a means to their ç
cherished goal. There is reason to believe that such ascetics existed ç
in good numbers.
Tapas (austerity including mortification of the flesh), brahmacarya ç
(celibacy), j<210><193>na and vidy<193> (learning) and yoga (contemplation ç
and meditation) were the prescribed disciplines for the ascetics. ç
They had to be assiduously cultivated.
Modes of dress varied from stark nakedness to wearing ochre-coloured ç
robes. Wearing just a kaup<200>nam (loin-cloth) or tattered garment ç
picked up from the roadside was often commended. Other possessions ç
permitted were: kama<207><195>alu (waterpot), pavitra (cloth used ç
as strainer), da<207><195>a (staff), p<193>tra (vessel of gourd for ç
food), ·ikya (loop of rope to carry the food-pot) and sometimes, a ç
pair of tongs for tending fire.
There were ascetics who lived alone and others who lived in groups, ç
sometimes building monasteries for their stay and activities. Several ç
orders of ascetics have been known to exist, such as sa<221>ny<193>sins ç
(including the da·an<193>mis), bair<193>gis, kab<200>rpanthis and ç
so on. Each of these orders had its own methods of initiation for ç
the novices desiring to enter it.
Though ascetic life was permissible only for the dvijas (`twice-born') ç
in the earlier days, later history of asceticism shows that people ç
from all castes have taken to it.
Women also could become ascetics though for obvious reasons, their ç
number and orders were very much less.
See also <MS>SA<189>NY°SA, SA<189>NY°SINS<D> and <MS>TAPAS<D>.
@SPACE = 
@NT = Asiatic Society, The
See <MS>ORIENTAL RESEARCH INSTITUTES OF INDIA.
@SPACE = 
@NT = asiddha
@N1 = (`unproved')
While  discussing  `hetv<193>bh<193>sa'  or fallacy of inference, ç
the Ny<193>ya system (Logical Theism of Gautama) lists five kinds  of  material  fallacies  of  which ç
`asiddha' forms the fourth. When it is said that `the sky-lotus is ç
fragrant, because it has lotusness in it, like a natural lotus,' the ç
pak<218>a or the minor term viz., the `sky-lotus' has no locus standi ç
(being only an <193>bh<193>sa or an appearance) and hencethe syllogism ç
becomes `asiddha' or unproved.
See also <MS>ANUM°NA<D> and <MS>HETV°BH°SA<D>.
@SPACE = 
@NT = asidh<193>r<193>-vrata
@N1 = (`vow of [walking on the] edge of a sword')
Vratas or religious vows are undertaken either as expiation for sins ç
committed or as a selfimposed discipline to gain something in life ç
which cannot normally be gained by human endeavours or even as a mark ç
of thanksgiving to God when certain desires have been fulfilled. `Asidh<193>r<193>-vrata' ç
is one such vrata and is so called because it is as difficult as walking ç
on the edge of a drawn sword. It begins on the full-moon day of °·vina ç
(September-October) and may be continued for five days, ten days, ç
or four months or one year or even twelve years. During this vrata, ç
one has to sleep on the bare ground, bathe outside the house, eat ç
food only in the night, eschew anger and should observe strict celibacy ç
eventhough sleeping with one's wife. During this period, gifts must ç
be given to worthy persons. Sometimes a da<207><195>a (stick) or even ç
a sword is kept in between the person and his wife when they sleep ç
in the night, as a reminder that they have to practise self-control ç
and are observing a vow as difficult as walking on the edge of a sword.
Many rewards have been promised to those who perform this vrata successfully.
@SPACE = 
@NT = Asikn<200>
@N1 = (`the non-white one')
@SPACE = 
One of the rivers often mentioned in the <184>gveda, it has been ç
identified with the modern Chenab river in the Punjab. The same river ç
was also called Candra-bh<193>g<193> in later literature.
According to the Hindu pur<193><207>as, Asikn<200> (or V<200>ri<207><200>) ç
was the daughter of Pa<210>cajana Brahm<193> (also known as V<200>ra<207>a) ç
and was married to Dak<218>a. She bore him sons called Harya·vas (who ç
were 10,000 in number) and <185>abal<193>·vas (who were 1000) and ç
sixty daughters.
