The ·<193>nti rites are usually sacrificial oblations with suitable ç
mantras addressed to the deity that has been displeased.
See also <MS><186>A£VI<189><185>A BR°HMAØA.
@NT = Adbhuta R<193>m<193>ya<207>a
One of the two great epics of India, the R<193>m<193>ya<207>a of ç
V<193>lm<200>ki, has been the basic text for the story of R<193>ma. ç
It has been the primary source of inspiration over the millennia, ç
for many a poet who has retold the story in his own way, often adopting ç
it to the philosophy of his life. One such work is the Adbhuta R<193>m<193>ya<207>a ç
(`the Wonder that is R<193>m<193>ya<207>a'). Though attributed to ç
V<193>lm<200>ki, it is obviously a late work. Scholars are divided ç
about its being earlier or later to another, more well-known work, ç
the Adhy<193>tma R<193>m<193>ya<207>a (<MS>A. D.<D> 1400). The glorification ç
of K<193>l<200> and identifying her with S<200>t<193> induce us to ç
think that the work must have been written at a time when reconciling ç
the R<193>ma cult of the Vai<218><207>avas and the <185><193>kta cults ç
had become a social necessity. Also, the words in the colophon as ç
seen from a printed text†`iti <193>r<218>e ·r<200>mad-r<193>m<193>ya<207>e ç
v<193>lm<200>k<200>ye <193>dik<193>vye adbhutottarak<193><207><195>e...'†give ç
rise to the suspicion that the writer might have attemp-ted to pass ç
it off as an appendix to the Uttarak<193><207><195>a of V<193>lm<200>ki's ç
R<193>m<193>ya<207>a.
The Adbhuta Ramaya<207>a is a compa-ratively smaller work of 1355 ç
verses spread over 27 sargas or chapters. Unlike the other R<193>m<193>ya<207>as ç
it is not divided into k<193><207><195>as or books.
The contents of the work may be summarized briefly as follows: The ç
sage Bh<193>radv<193>ja approaches the great sage V<193>lm<200>ki ç
and requests him to give the secret teaching that is hidden in his ç
original R<193>m<193>ya<207>a which is rather voluminous. V<193>lm<200>ki ç
replies that the real secret is that R<193>ma is the Highest Brahman ç
and S<200>t<193>, the Highest Prak<216>ti, the power of Brahman. Then ç
he goes on to narrate the reasons for the descent of R<193>ma (sargas ç
2 to 4) and S<200>t<193> (s. 5 to 7), which were apparently due to ç
the curses of the sages N<193>rada and Parvata, but really to destroy ç
the wicked and protect the good. This is followed by the story of ç
the birth of S<200>t<193> as the daughter of R<193>va<207>a, but abandoned ç
by his wife Ma<207><195>odar<200>, and found by Janaka, the king of ç
Mithil<193>, in his field. After this, the events move at a terrific ç
speed: R<193>ma's marriage, Para·ur<193>ma's humiliation at the hands ç
of R<193>ma (s.<|>9), R<193>ma's entering the forest along with S<200>t<193> ç
and Lak<218>ma<207>a (The entire episode of the Ayodhy<193>k<193><207><195>a ç
of V<193>lm<200>ki's R<193>m<193>ya<207>a leading to R<193>ma's ç
banishment is glossed over here!), S<200>t<193>'s abduction by R<193>va<207>a ç
and R<193>ma striking friendship with Sugr<200>va and Hanum<193>n ç
(s.10). In answer to the simple question that Hanum<193>n asks, `Who ç
are you?' (s.10) R<193>ma waxes eloquently to describe himself as ç
the °tman, Parame·vara, M<193>y<193>v<200> and Antary<193>min (s.11 ç
and 12). Most of the ideas and even the words are reminiscent of the ç
Bhagavadg<200>t<193>, and some of the Upani<218>ads. This is followed ç
by a short discourse on bhakti or devotion (s. 13) and a curious mixture ç
of a variety of philosophical and mythological topics (s.14). The ç
next chapter contains a beautiful hymn of Hanum<193>n on R<193>ma ç
(s. 15). The sixteenth sarga disposes off very briefly (in 20 verses) ç
the entire story of the Yuddhak<193><207><195>a. In the seventeenth, ç
S<200>t<193> reveals the existence of a thousand-headed R<193>va<207>a, ç
the elder brother of the ten-headed demon, and describes him as she ç
had heard from a br<193>hma<207>a in her younger days. Hearing this, ç
R<193>ma starts on an invasion of the Pu<218>kara Dv<200>pa, the abode ç
of the thousand-headed monster, in order to destroy him. In the terrific ç
war that ensues, R<193>ma falls down unconscious (s.18 to 22). Seeing ç
this tragedy that had overtaken R<193>ma and his forces, S<200>t<193> ç
assumes the terrible form of K<193>l<200> and destroys the demon along ç
with all his forces. She is helped in this by her innumerable emanations ç
(s. 23). R<193>ma wakes up and is surprised to see K<193>l<200> there ç
(s. 24). He praises her with a long hymn containing 1008 names (s. ç
25). Though called S<200>t<193>-sahasran<193>ma (`thousand names ç
of S<200>t<193>') almost all the names belong to the <185>akti cult. ç
S<200>t<193> dissolves the form of K<193>l<200> and reappears in her ç
original form. After thus gaining victory, R<193>ma returns to Ayodhy<193> ç
and resumes his rule (s. 26 and27).
Though this work might have served a specific purpose during the days ç
of its composition and later, it fails to come up to the level of ç
the Adhy<193>tma R<193>m<193>ya<207>a and the °nanda R<193>m<193>ya<207>a.
See also <MS>ADHY°TMA R°M°YAØA, °NANDA R°M°YAØA<D> and <MS>R°M°YAØA<D>.
@NT = <193>dh<193>na
@N1 = (`placing')
See <MS>AGNY°DH°NA<D>.
@NT = <193>dh<193>ra
@N1 = (`support')
One of the questions discussed frequently in Hindu metaphysical works ç
is the relationship between God, the creator and the created world. ç
Most of them subscribe to the view that God creates theworld, sustains ç
and supports it and dissolves it at the end of a cycle of creation. ç
The created world cannot exist unless it is supported and sustained ç
by him. He is thus the <193>dh<193>ra (the ground and the support) ç
and the world itself is <193>dheya (`that which is supported'). The ç
relationship that subsists between them is called `<193>dhara-<193>dheya-bh<193>va.' ç
The relationship that exists between the ground and a jar kept on ç
it gives us some idea of this `<193>dh<193>ra-<193>dheya-bh<193>va.'
In the works on yoga, the word is used to indicate certain centres ç
in<|>the body like the navel, the heart or the middle of the eyebrows ç
which act as supports for meditation or pr<193><207>a (life-force).
<W1%-1>In Sanskrit grammar the word is used<D%0> to indicate the sense ç
of the locative case.
@NT = <193>dh<193>racakra
@N1-1 = (`supporting psychic centre')
See <MS>CAKRAS<D> and <MS>M<188>L°DH°RA<D>.
@NT = <193>dh<193>ra·il<193>
@N1 = (`support-stone')
Belief in God and putting up structures to worship him or to pray ç
to him seems to be a common trait of human beings irrespective of ç
their geographical boundaries or differences of culture. There are ç
evidences to show that the Hindu places of worship, called dev<193>layas ç
(temples, houses of God), have been existing since very ancient times. ç
These dev<193>layas are highly symbolic and attempt at unravelling ç
this symbology, in concrete terms, have resulted in a regular science ç
and art of temple construction. Apart from the usual foundation laid ç
to support the superstructure of the temple, these works on temple ç
construction insist on the laying of the <193>dh<193>ra·il<193> or ç
support-stone below the floor of the garbhag<216>ha (sanctum sanctorum).
In the middle of the site for thegarbhag<216>ha, where the idol will ç
be installed, the ground is excavated to a pre-determined depth. A ç
number of articles are ceremonially fixed therein, one after another, ç
with appropriate mantras. (See <MS><186>A£°DH°RA-PRATI<186><187>H°<D>.) ç
Of these, the <193>dh<193>ra·il<193> is the first to be fixed, and ç
at the lowest level, as the base or support. It is a square block ç
of granite or any other hard stone, of specific dimensions. On it ç
are placed the other articles like the pot called nidhikumbha and ç
the lotuses of stone and metal.
According to one of the interpretations of temple symbolism, the temple ç
represents the body of the yogi (the spiritual aspirant practising ç
yoga) with all the cakras (centres of psychic power). The <193>dh<193>ra-·il<193>, ç
then, stands for the m<220>l<193>dh<193>ra-cakra (the lowest centre).
See also <MS>CAKRAS<D>.
@NT = adharma
@N1 = (`unrighteousness')
Among the pairs of words used often by the Hindu scriptures, the pair ç
`dharma-adharma' is perhaps the most recurrent. Since the etymological ç
definition of `dharma' is `that which supports and sustains,' all ç
that attempts to destroy or oppose or reverse this process of supporting ç
and sustaining comes within the purview of the word `adharma.' If ç
dharma is the straight path that leads to abhyu-daya (well-being and ç
prosperity) and ni··reyasa (spiritual perfection), adharma is the ç
crooked path that leads away from both. If dharma indicates actions ç
and duties, ritualistic or otherwise, which are in conformity with ç
the teachings of the ·<193>stras (holy scriptures) and <193>c<193>ryas ç
(spiritual and religious leaders), and not antagonistic to samprad<193>ya ç
(customs and traditions), adharma stands for all errors of omission ç
and commission.
In practice however, the word is more frequently used in the sense ç
of unrighteous deeds and conduct resulting in sin. For instance, telling ç
lies, stealing, cheating, adultery and committing such other forbidden ç
acts and crimes are adharma. Dereliction of duties and not discharging ç
the responsibilities one is entrusted with, are adharma. Performing ç
such acts as are not prescribed for one<192>for e.g., a br<193>hma<207>a ç
taking to arms or agriculture even though there is no urgency or emergency†is ç
also considered adharma.
The personified adharma, in the mythological lore, is said to have ç
hi<221>s<193> (violence) as his wife, an<216>ta (falsehood) as his ç
son, and nik<216>ti (deceit) as his daughter. M<193>y<193> (delusion), ç
bhaya (fear), vedan<193> (torment), naraka (hell), du<199>kha (sorrow) ç
and m<216>tyu (death) are the other offsprings coming in that lineage ç
(vide Vi<218><207>upur<193><207>a 1.7). Though the details of such ç
lists may vary, the purport is clear: adharma is at the root of all ç
our fears, troubles and sufferings.
In Jaina metaphysics, adharma is considered to be a dravya (substance) ç
responsible for restful state and immobility of things.
See also <MS>DHARMA<D> and <MS>P°PA<D>.
@NT = <193>dhi
@N1 = (`illness of the mind')
The ancient Hindu sages have recognised that the body and the mind ç
form one unit and that this unit is of fundamental importance in achieving ç
anything worthwhile in life. Hence each should be kept in a healthy ç
condition and in harmony with the other. Vy<193>dhi (illness of the ç
body) and <193>dhi (illness of the mind) are both considered to be ç
serious obstacles in the path of progress, whether temporal or spiritual.
In most general terms, anything that disturbs the equilibrium of the ç
body is a vy<193>dhi and anything that upsets the equi- poise of the ç
mind is an <193>dhi. The ari<218>a<195>- vargas or six enemies viz., ç
lust, anger, greed, delusion, pride and envy, as also worries and ç
anxieties are examples of <193>dhi. R<193>ga (attachment) and dve<218>a ç
(aversion) are the root causes of all <193>dhis. Conquest of these ç
will help in removing the <193>dhis.
In the dharma·<193>stras, the word is used in the sense of a pledge, ç
deposit or article of mortgage.
@NT = <193>dhibhautika, <193>dhidaivika, <193>dhy<193>tmika
The three words respectively mean: pertaining to (a) the bh<220>ta ç
or living beings; (b) the daiva or fate, unseen forces and gods; (c) ç
the <193>tma or the body (and the mind).
Sorrow and suffering (du<199>kha, t<193>pa) are inevitable in life. ç
In fact, they are a part of life. A knowledge of their origin, causes ç
and even categorisation helps one to minimise their effect if not ç
eradicate them. The Hindu religious works usually call them `t<193>patraya,' ç
`the three miseries.' They are: <193>dhy<193>tmika, <193>dhidaivika ç
and <193>dhibhautika.
The <193>dhy<193>tmika du<199>kha or t<193>pa is that which is caused ç
by bodily suffering and mental anguish. Hereditary diseases like leprosy, ç
disabilities like blindness or lameness and diseases caused by the ç
violation of the rules of health and sanitation are classed under ç
this. The mental agony caused by worries and anxieties, attachment ç
and aversion, also comes under this group.
The <193>dhidaivika<|>du<199>ka or t<193>pa is that which is caused ç
by daiva. The word daiva includes the power of time, nature andthe ç
unseen hand or fate. Diseases caused by the changing seasons, misery ç
caused by the elemental forces like floods and fire, suffering caused ç
by black magic or disembodied spirits or gods who are displeased, ç
natural tribulations due to hunger, thirst and old-age belong to this ç
group.
The <193>dhibhautika du<199>kha or t<193>pa is that which is caused ç
by other bh<220>tas or living beings, like wild animals, snakes, or ç
enemies.
Some of these, like hereditary diseases or physical disabilities cannot ç
be got rid of. Hence they must be endured. Some like the diseases ç
caused by change of seasons or the machinations of enemies can be ç
countered by taking appropriate precautions. However, raising the ç
mind to the level of the spirit, thus transcending thelimitations ç
imposed by the body-mind complex, is the best solution to offset the ç
effects of t<193>patraya.
@NT = <193>dhidaivika
See <MS>°DHIBHAUTIKA<D>.
@NT = adhikam<193>sa, adhim<193>sa
@N1 = (`intercalary<R>ç
month')
From the most ancient times, all religious  activity  of  the  Hindus  was ç
performed at times considered auspicious or suitable for them. Calculations ç
were done based on the movements of the sun, the moon, the planets ç
and the stars. This resulted in the growth of an entire scienceof ç
Vedic Astronomy, `Ved<193><209>ga Jyoti<218>a'.
@SPACE1 = 
The most fundamental periods of time, common to all the nations are ç
the day, the month and the year. The day is due to the revolution ç
of the earth round its axis. The month is mainly a lunar phenomenon ç
based on the waxing and waning of the moon. The year is due to the ç
apparent motion of the sun as seen from the earth. Hence the Hindus ç
followed a luni-solar calendar from the ancient times, and being aware ç
of the di<M>fference between the two ways of calculating, also provided ç
for the necessary adjustments to be made to bring the two into consonance. ç
The lunar year on which are based the religious activities, is less ç
than the solar year by about eleven days. Hence two intercalary months ç
are added infive years, one being a second <193><218><193><195>ha ç
(the 4th lunar month) at the end of 2<P8W1><|><$E1/2 ><|><P255M> years ç
and a second pau<218>a (the 10th lunar month) at the end of another ç
2<P8W1><|><$E1/2 ><P255M> years. This is according to Ved<193><209>ga ç
Jyoti<218>a. Later works give varying periods after which the intercalary ç
month occurs. The general rule seems to be that the lunar month in ç
which no sa<209>kr<193>nti (apparent movement of the sun from one ç
constellation to the next, as seen from the earth) occurs, is called ç
an adhikam<193>sa and bears the same name of the next lunar month ç
which is called ·uddha or nija or pr<193>k<216>ta, to distinguish ç
it from the former.
Somehow,  the  adhikam<193>sa  was considered even from the ancient ç
times, inauspicious and hence named malam<193>sa (`the dirty month'), ç
malimluca (`a thief'), a<221>haspati (`the lord of sins') and so on. ç
During this month one was advised to avoid acts like consecrating ç
Vedic fires, installing images, offering gifts, observing vratas or ç
religious vows, performing upanayana and other sa<221>sk<193>ras (puri- ç
ficatory rites).
However in some pur<193><207>as like the Padma (6.64) the intercalary ç
month is named `puru<218>ottama-m<193>sa' (`month of LordVi<218><207>u'), ç
probably with a view to reducing the opprobrium attached to it and ç
considered, on the other hand, asholy.
@NT = adhik<193>ra
@N1 = (`competence')
All people are not endowed with equal ability. To perform an act properly ç
and efficiently one must have at least the minimum capacity and competence ç
in that field. Training can improve it but cannot create it. This ç
patent fact has been recognised by the Hindu scriptures andpropagated ç
under the nomenclature `adhik<193>ra.' For instance, it is the man ç
who is endowed with physical strength and mental courage that has ç
the adhik<193>ra for joining the armed forces. Similarly it is the ç
person who is endowed with more than average intelligence, a fair ç
degree of scholarship and a capacity to speak well, that has the adhik<193>rato ç
enter the teaching profession. Again, it is the person who has practised ç
at least to a certain degree, purity and self-control, that has the ç
adhik<193>ra to become a monk.
In most cases, adhik<193>ra can be developed by assiduous cultivation. ç
One who has adhik<193>ra is called an `adhik<193>rin' and the doctrine ç
that advocates the need for adhik<193>ra is called `adhik<193>rav<193>da.' ç
The differences among the adhik<193>rins are termed `adhik<193>ribheda.'
In this creation there is nothing that is absolute. Everything is ç
relative. Divergences and differences do exist. The `Doctrine of Adhik<193>ra ç
or Adhik<193>rabheda' is just a recognition of this patent fact. It ç
does not necessarily suggest a gradation, with its corollary of `higher' ç
and `lower' status, implying pride or contempt. It is more an acceptance ç
of a fact as it exists, helping one to understand where one stands ç
and start one's progress from that base. Also it is designed to awaken ç
one to one's duties rather than to one's rights and privileges.
@SPACE = 
@NT = adhikara<207>a
@N1 = (`ground or support')
The word is generally used in the sense of a base, ground or support. ç
For instance, when we say, `This is a blue lotus with a sweet smell,' ç
the lotus flower forms the `adhikara<207>a' for the blue colour as ç
also the sweet smell.
In the M<200>m<193><221>s<193> philosophy, it is used as a technical ç
term and indicates the section of a work dealing with a particular ç
topic. It consists of five parts: vi<218>aya (subject of discussion), ç
vi·aya or sa<221>·aya (doubt), p<220>rvapak<218>a (prima facie view), ç
uttara (answer) and siddh<193>nta or nir<207>aya (final conclusion).
@SPACE = 
@NT = Adhik<193>ra Nandi
Everyone that enters a <185>iva temple cannot fail to see the image ç
of Nandi, the reclining bull. In iconography, Nandi or Nandike·vara ç
is depicted in two forms as v<216><218>abha or reclining bull and ç
as Adhik<193>ra Nandi, an image resembling that of <185>iva. In this ç
aspect , the two back hands hold the para·u (battle axe) and the m<216>ga ç
(antelope) and the two front hands are folded on the chest in the ç
a<210>jali (obeisance) pose. In all other respects, the characte-ristics ç
of the image are identical with those of <185>iva.
Since he is the chief of the ga<207>as (retinues) of <185>iva, exercising ç
his authority (adhik<193>ra) over them, he is christened `Adhik<193>ra ç
Nandi.' He is also called Nand<200>·vara or Nandike·vara.
As regards the origin of this deity, there are three different accounts ç
available in Hindu mythology. Desirous of a son, a sage S<193>la<209>k<193>yana ç
by name, propitiated Vi<218><207>u, who granted his wish by producing ç
a boy exactly resembling <185>iva, from the right side of his body. ç
He was named Nandike·vara. According to another account, a sage called ç
Nandi obtained the status of a god and the headship of the ga<207>as ç
of <185>iva by propitiating him. A third account depicts him as emerging ç
from the y<193>ga·<193>l<193> (sacrificial shed) of the blind sage ç
<185>il<193>da, in the form of an young lad resembling <185>iva, thus ç
bringing `nandi' or joy to him. <185>il<193>da adopted him as his ç
son.
Adhik<193>ra Nandi took a prominent part in the destruction of Dak<218>a's ç
sacrifice.
He is more often represented as a bull and also described as the v<193>hana ç
(mount) of <185>iva.
See also <MS>NANDI<D>.
@NT = adhi<218>ava<207>a
@N1 = (`to press out')
The Vedic sages were fond of performing sacrifices to propitiate the ç
various deities like Indra through whom they could fulfil their wishes. ç
In one group of such sacrifices called Somay<193>gas, the libation ç
of the juice of the soma creeper was the most important ceremony. ç
The act of pressing out the juice from the creeper was no less important ç
and even that hada ritualistic bearing. The word `adhi<218>ava<207>a' ç
is used to indicate both this act of pressing the soma creeper and ç
the wooden contrivance used in the process. More often, the latter ç
which is in the form of a pair of semicircular wooden boards, is called ç
`adhi<218>ava<207>a-phalaka.'
@SPACE = 
@NT = adhi<218><219>h<193>na
@N1 = (`base, support, substratum')
While discussing the theory of illusory perception, this word is often ç
used in Ved<193>nta to denote the substratum wherein the illusion ç
occurs. For instance, when a snake is perceived in a rope, or silver ç
in nacre, the rope or the nacre forms the `adhi<218><219>h<193>na' ç
or substratum, for this illusory perception. Ignorance of this adhi<218><219>h<193>na ç
causes the illusion and its true knowledge dispels it.
While enumerating the five causes responsible for the accomplishment ç
of every action, the Bhagavadg<200>t<193> (18.14) puts `adhi<218><219>h<193>na' ç
as the first in the list. The word is interpreted there as the body, ç
since the body is the primary basis necessary for all actions.
In  works  on  Hindu  Architecture including Temple Architecture, ç
the word denotes the basement of a building or even a column. Innumerable ç
varieties of the same are detailed in those works.
In Civics, the word was used to indicatea seat of administration ç
like a city-council.
@NT = adhiv<193>sa
@N1 = (`to live in')
@SPACE = 
@SPACE = 
Temples form a very important part of the Hindu religious institutions ç
and culture. Building of temples has developed, over the years, into ç
a great art. Architecture and iconography have grown both vast and ç
deep because of it. The images, though prepared strictly according ç
to the standards of iconography, are unfit to be installed in them ç
unless sanctified ceremonially by rites recommended in the <193>gamas ç
(a class of religious works connected with temple worship). `Adhiv<193>sa' ç
is such a rite, making the image `live in' various substances like ç
water and grains. The adhiv<193>sas are three: jal<193>dhiv<193>sa, ç
dh<193>ny<193>dhiv<193>sa and ·ayy<193>dhiv<193>sa. The first is to ç
remedy the effects of chiselling, the second for purifying the physical ç
imageand the last for inducing spiritual effulgence.
In jal<193>dhiv<193>sa (`living in water'), the image is taken in ç
a procession round the village, placed on level ground on the bank ç
of a river or tank, sprinkled with the water of the same, wound round ç
with ku·a grass and new cloth and ceremonially immersed in the water ç
so that the head lies towards the east and mouth upwards. The duration ç
of jal<193>dhiv<193>sa is from one night to nine nights, though three ç
nights are more common. After taking it out of water, the image has ç
to undergo physical and ceremonial cleansing once again.
Dh<193>ny<193>dhiv<193>sa (`living in grains') and ·ayy<193>dhiv<193>sa ç
(`living in the bed') are actually one ritual in practice. On the ç
vedi (special platform) a stha<207><195>ila (an esoteric geometric ç
design) is inscribed. Grains like wheat, rice, barley and black sesame ç
are spread and a lotus of eight petals is inscribed on the grains. ç
A bed is now prepared over this with five materials viz., wooden plank, ç
skin of deer or tiger, a rug of animal hair, feathers of birds and ç
cloth. In the absence of the first four materials, five layers of ç
cloth can be used. The image is now made to lie for three nights on ç
this bed, with ku·a grass underneath it, the head being towards the ç
east and mouthupwards.
The word `adhiv<193>sa' is also used in the sense of `perfuming' or ç
sanctifying with perfumes or other approved materials, anyobject ç
or objects used in ceremonial worship.
See also <MS>PRATI<186><187>H°VIDHI<D>.
@NT = adhoniv<200>ta
@N1 = (`that which covers below')
The dharma·<193>stras have made it obligatory for every man born in ç
the br<193>hma<207>a, k<218>attriya and vai·ya castes to undergo the ç
sacrament of upanayana (See <MS>UPANAYANA<D> for details.) after which ç
alone he becomes eligible for the study of the Vedas and the performance ç
of ordained rituals. A concrete part of this sacrament is the investiture ç
with the sacred thread called `upav<200>ta' or `yaj<210>opav<200>ta' ç
which should be worn permanently on the body. One of the three modes ç
of wearing this upav<200>ta is `adhoniv<200>ta' or `adhov<200>ta' ç
or `sa<221>v<200>ta'. In this mode, the sacred thread hangs from the ç
neck like a garland, stretching below the navel. This mode of wearing ç
is recommended at the time of performing secular activities. The relatives ç
of a dead person<192>if he belongs to any of the first three castes<192>attending ç
his funeral procession are also required to wear the sacred thread ç
in this mode.
See  also  <MS>NIV®TA,  UPAV®TA<D>  and <MS>YAJ<178>OPAV®TA<D>.
@SPACE = 
@NT = adhvara
@N1 = (`that which leads by a straight, therefore true, path')
Human beings by nature, are interested in getting the good things ç
of life so that they can live in comfort, happiness and peace. Those ç
of them that believe in an after-life, are also interested in perfor-ming ç
those acts here, that assure them a happy life hereafter. If the religious ç
and spiritual leaders do not show them the right way, in all likelihood, ç
they will take to the wrong way, the way of selfishness, competition ç
and even fighting among themselves. Hence the need to show them the ç
right path, the straight path, the good path. This is exactly what ç
`adhvara' is. Etymologically it means a path which is not crooked, ç
which does not cause harm to others. But in usage,it means a Vedic ç
sacrifice. Since the Vedic sacrifices point the straight and good ç
path for the fulfilment of man's wishes, here and hereafter, it is ç
but proper that they are designated `adhvara.'
For details of sacrifices, see <MS>VEDIC SACRIFICES<D>.
@SPACE = 
@NT = adhvaryu
@N1 = (`One who desires an adhvara or a sacrifice')
Man aspires after maximum happiness but with minimum effort, if he ç
can help it. This aspiration can often tempt him to resort to shortcut ç
methods which will entail a lot of suffering to other beings. The ç
Vedic <216><218>is (sages) who had thoroughly understood human psychology, ç
propounded and propagated a system of sacrifices by following which ç
man could get his desires fulfilled, in a righteous way.
Every such sacrifice must have a minimum of four priests: hot<193>, ç
adhvaryu, udg<193>t<216> and brahm<193>. Adhvaryu, the second priest ç
who follows the Yajurveda, is by far the most active of the group. ç
It is he who surveys the sacrificial ground, designs and builds the ç
altars, prepares or secures the utensils, cooks the sacrificial oblations, ç
fetches water and wood, kindles the fires, brings the animals and ç
immolates them, all the while repeating the appropriate mantras from ç
the Yajurveda at appropriate times. Being constantly on the move, ç
he has no fixed seat. He is normally assisted by three priests: pratiprasth<193>t<216>, ç
ne<218><219><216> and unnet<216>. Sometimes the number of such priests ç
including him may be as large as36.
See also <MS>BRAHM°, HOT<184>, UDG°T<184><D> and <MS>VEDIC SACRIFICES<D>.
@NT = adhy<193>ropa
@N1 = (`superimposition')
The attempts at reconciling Brahman the Absolute with the world which ç
is imperfect and limited have resulted in the`doctrine of adhy<193>ropa-apav<193>da.' ç
The problem is sought to be resolved by considering the world as an ç
adhy<193>ropa or adhy<193>sa, a superimposition (even as a snake is ç
superimposed on a rope resulting in illusory perception) and denying ç
it absolute reality. The process of desuperimposition called `apav<193>da,' ç
consists of negating the illusory appearances by adopting the right ç
means of knowledge and perceiving the truth as it is. Adhy<193>ropa ç
is practically the same as `adhy<193>sa' (See <MS>ADHY°SA.<D>) A slight ç
shade of difference in meaning is perhaps, that adhy<193>ropa refers ç
to the process and adhy<193>sa is the result.
@NT = adhy<193>sa
@N1 = (`superimposition')
The Advaita Ved<193>nta philosophy, the chief exponent of which was ç
<185>a<209>kara (<F51320P10MSC1>A.D<F255P255DC255>. 788-820), accepts Brahman ç
(the Absolute), which is beyond names, forms, attributes, and hence, ç
defies all description, as the Ultimate Reality. But the world that ç
we perceive with its myriad names, forms and attributes, circumscribed ç
by time, space and causation, cannot be easily brushed aside or wished ç
away. Hence there is a great need to explain the relationship between ç
Brahman the Absolute and this world of phenomena. `Adhy<193>sa' or ç
`adhy<193>ropa' is the explanation offered by Advaita Ved<193>nta.
Literally, the word means one thing `sitting upon' another, hiding ç
its nature for the time being. It is defined as `the appearance elsewhere, ç
as in memory, of something perceived earlier.' (Adhy<193>sa-bh<193><218>ya ç
of <185>a<209>kara, Brahmas<220>tras 1.1.1). Two oft-repeated analogies ç
are the erroneous perception of a snake in a rope in insufficient ç
light and of silver in nacre shining in light. In both cases, the ç
impressions of a snake and silver from an earlier idea of the same ç
are superimposed on the rope and the nacre under conditions conducive ç
to the erroneous perception. These erroneous perceptions have been ç
caused by the `adhy<193>sa' of the snake on the rope and the silver ç
on the nacre. This again is due to aj<210><193>na or avidy<193> (ignorance) ç
of the real nature of the adhi<218><219>h<193>na (substratum<192>here, ç
the rope and the nacre). This aj<210><193>na is an<193>di (without  beginning)  since  it  has  no ç
ascertainable beginning. Once this aj<210><193>na is removed by right ç
perception, the error disappears automatically.
Using the doctrine of adhy<193>sa and the two analogies already mentioned, ç
Advaita metaphysics tries to explain that the world palpably perceived ç
by the senses is only an erroneous perception caused by adhy<193>sa ç
on Brahman. Once the real natureof Brahman is realised, the world ç
appearance ceases. At the subjective level, this adhy<193>sa causes ç
the erroneous perception of the body-mind complex on the <193>tman ç
(the immanent aspect of Brahman at the individual level). Once the ç
real nature of the <193>tman is realised, its identification with ç
the body-mind complex will disappear.
See also <MS>ADHY°ROPA<D>.
@NT = adhy<193>tma
@N1 = (`pertaining to the <193>tman')
In the Upani<218>ads as well as in the Bhagavadg<200>t<193> the ç
three words adhibh<220>ta, adhidaiva and adhy<193>tma are frequently ç
met with. The indeclinable `adhi' has the sense of `ruling over,' ç
`pertaining to'. The word `<193>tman' is often used in the sense of ç
the body. Hence `adhy<193>tma' generally indicates the Self within ç
the body which resides in it and rules over it. It is also used to ç
indicate Brahman or the Supreme Self.
The word is also used as an adjective and in combination with other ç
words. For instance: adhy<193>tmavidy<193> (knowledge of the Self), ç
adhy<193>tmayoga (yoga or meditation on the Self).
@NT = adhy<193>tma-pras<193>da
@N1 = (`peace of the mind within')
Mind is the basic instrument for gaining knowledge and wisdom. Controlling ç
its vagaries and making it flow in a concentrated manner is the best ç
means of attaining knowledge in any field. This however is easier ç
said than done. By a long and arduous process of yogic discipline ç
which includes the practice of ethical principles like ahi<221>s<193> ç
(non-violence), satya (truth) and brahmacarya (continence) and the ç
practice of concentration by stages, the mind loses all its dross ç
and impurities and becomes placid and pellucid. Such a state of mind ç
is called `adhy<193>tma-pras<193>da' (vide Yogas<220>tras 1.47). ç
In this state the mind, being rid of all impurities that distract ç
and disturb it, has become like a pure crystal capable of reflecting ç
the consciousness of the puru<218>a (the Self), in full measure. Such ç
a mind can produce instant knowledge of any object towards which it ç
is directed.
@SPACE = 
@NT = Adhy<193>tma R<193>m<193>ya<207>a
Hindu life will lose all its meaning and charm without R<193>ma and ç
K<216><218><207>a, the two colossuses that have strode the Hindu heart ç
for the last few millennia. If the R<193>m<193>ya<207>a of V<193>lmik<200> ç
has been the basis on which the R<193>ma personality has beenbuilt ç
up, no less important are its numerous imitations and adoptions that ç
have kept alive the R<193>ma cult and the R<193>ma community leading ç
to the development of R<193>m<193>logy. Perhaps, one of the most important ç
Sanskrit works of this type is the Adhy<193>tma R<193>m<193>ya<207>a ç
which is very popular in North India, not only among the devotees ç
of R<193>ma but also among the Ved<193>ntins. Infact, it is this ç
work that provided Tulas<200>d<193>sa with the inspiration to compose ç
his immortal work, the R<193>macaritm<193>nasa.
Though depicted as a part of theBrahm<193><207><195>a Pur<193><207>a, ç
respected as a canonical work of the Vai<218><207>avas and begun in ç
the Tantra style of conversation between <185>iva Mah<193>deva and ç
P<193>rvat<200>, scholars ascribe it to<|>the period 14th-15th cent. ç
<F51320MS>A.D.<W1> <F255D>Nothing is known of the author, though the R<193>ma ç
tradition believes it to be Vedavy<193>sa since it is said to be an ç
integral part of the Brahm<193><207><195>a Pur<193><207>a.
Like its original source, the Adhy<193>tma R<193>m<193>ya<207>a ç
also has seven k<193><207><195>as or books, named in the same manner, ç
except for the sixth, the Yuddhak<193><207><195>a, which is sometimes ç
designated La<209>k<193>k<193><207><195>a. The total number of verses ç
is 4200 spread over 65 sargas or chapters. Written in mellifluous ç
Sanskrit, the work admirably sums up the main events of the R<193>m<193>ya<207>a ç
of V<193>lm<200>ki omitting only the minor details, or descriptions ç
of war and nature. On the other hand new material pertaining to Ved<193>nta ç
philo-sophy, the cult of bhakti in general and R<193>ma-bhakti in ç
particular and several hymns in praise of R<193>ma have been liberally ç
added.
A few of the changes and innovations made, departing from the original ç
may be noted here: The major alteration in the facts of the story ç
is the introduction of a shadow S<200>t<193> throughout the period ç
of her abduction, the real S<200>t<193> having disappeared into the ç
fire just before the golden deer episode. She re-emerges from the ç
fire at the end of the war when the shadow S<200>t<193> enters into ç
it. The whole drama is preplanned and enacted at the bidding of R<193>ma ç
himself (vide 3.7). Other alterations though minor in nature, are: ç
the earth accompanies the gods in the form of a cow (1.2); Sumitr<193> ç
gets more of the sacred pudding than Kausaly<193> and Kaikey<200> ç
(1.3); Ahaly<193> after being cursed by her husband, the sage Gautama, ç
becomes a stone (1.5); R<193>va<207>a treats S<200>t<193> with the ç
respect due to a mother (3.7.65); R<193>ma establishes a <185>ivali<209>ga ç
at the site of the bridge to La<209>k<193> (6.4.1-2).
Coming to the additions to V<193>lmik<200>'s story, five paur<193><207>ic ç
episodes need be mentioned:<|> the stories about V<193>lm<200>ki himself ç
(2.6), <185>uka (6.5) and K<193>lanemi (6.6) who warn R<193>va<207>a ç
about R<193>ma's divinity and the need to propitiate him, V<193>l<200> ç
and Sugr<200>va (7.3). The dialogue between R<193>va<207>a and Sanatkum<193>ra ç
is another addition (7.3).
But the major contribution of the Adhy<193>tma R<193>m<193>ya<207>a ç
lies in its casting of R<193>ma in the role of a spiritual teacher ç
and in the several exquisite hymns sung in praise of R<193>ma. There ç
are four occasions when R<193>ma assumes the role of the teacher and ç
gives philosophic disquisitions. In response to Lak<218>ma<207>a's ç
questions on three different occasions he teaches know-ledge, devotion, ç
detachment (vide 3.4), methods of worship (4.4) and the way of emancipation ç
(7.5). In reply to Kausaly<193>'s query, he teaches the three yogas ç
of karma, j<210><193>na and bhakti (7.7).
The well-known R<193>mag<200>t<193> is part of the Adhy<193>tma ç
R<193>m<193>ya<207>a and is the teaching given to Lak<218>ma<207>a ç
on the last occasion already referred to (7.5). It contains a rather ç
strong dose of Advaita Ved<193>nta<|> though <|>couched <|>in<|> beautiful ç
poetry. In fact some scholars feel that this R<193>mag<200>t<193> ç
and R<193>mah<216>daya (1.1) were independent works incorporated ç
later into this Adhy<193>tma R<193>m<193>ya<207>a.
As regards the laudatory hymns, we find quite a good number of them: ç
by Brahm<193> (1.2; 6.13), Kausaly<193> (1.3), N<193>rada (2.1), V<193>lm<200>ki ç
(2.6), Ja<219><193>yu (3.8), Vibh<200><218>a<207>a (6.6) and all the ç
gods (6.15).
However the real contribution of this work is in its repeatedly propounding ç
the doctrine that R<193>ma is Brahman the Absolute and that S<200>t<193> ç
is his M<193>y<193>·akti or Prak<216>ti, thereby raising the personality ç
of R<193>ma to the highest level and providing a firm base to the ç
cult of R<193>ma. No occasion that gives a chance to do this is missed. ç
Not only sages, gods and devotees, but<|> even <|>the<|> enemies <|>of ç
<|>R<193>ma<192>not excepting R<193>va<207>a himself<|>!†recognise his ç
divinity and divine mission. Their only duty is to cooperate in the ç
cosmic play of the Divine and be blessed. This task has been admirably ç
fulfilled by the book.
In the orthodox circles of R<193>ma devotees, the Adhy<193>tma R<193>m<193>ya<207>a, ç
is considered to be a mantra·<193>stra, a sacred book, each stanza ç
of which is revered as a `mantra' (mystic syllable) and devoutly repeated ç
in a ceremonial way.
It is worthwhile noting that the well-known Hindi work, R<193>mcaritam<193>nas ç
of Tuls<200>das (<F51320MS>A. D.<W1> 1532-1623), is based almost entirely ç
on the <F255MI>Adhy<193>tma R<193>m<193>ya<207>a.
See also <MS>R°MAG®T°, R°MAH<184>DAYA<D> and <MS>R°M°YAØA<D>.
@NT = Adhy<193>tma Upani<218>ad
Upani<218>ads are the treasurehouse of the spiritual knowledge of ç
India. They have been accepted and venerated as basicscriptures by ç
most of the religio-philosophical schools of India. Every philo-sopher ç
or religious reformer has taken pains to show that his views are rooted ç
in the Upani<218>adic traditions, or at least, do not go against them. ç
Even the non-Hindu and non-Indian savants have heaped praises on their ç
enlightened views.
The ten Upani<218>ads on which <185>a<209>kara (<F51320P10MSC1>A. D.<W1> ç
788-820) wrote commentaries have universally been accepted as the ç
more ancient, more authentic and authoritative. The <F255P255MIC255>Adhy<193>tma ç
Upani<218>ad, though outside this list, still, breathes the spirit ç
of the more ancient and the major Upani<218>ads.
Since the printed texts give the ·<193>ntimantra as `p<220>r<207>amada<199> ç
...' it is to be surmised that it belongs to the <185>ukla Yajurveda. ç
The last verse of the Upani<218>ad declares that it was first revealed ç
to the sage Ap<193>ntaratamas who taught it to Brahm<193>. Brahm<193> ç
gave it to Ghora A<209>giras who in turn transmitted the same to Raikva. ç
Raikva passed it on to R<193>ma and R<193>ma revealed it to all the ç
living beings.
The teaching itself has been designated as `nirv<193><207><193>nu·<193>sanam' ç
(`command concerning final emancipation').
@SPACE1 = 
The text consists of 70 verses, all in the ·loka metre, and has not ç
been divided into sub-sections. But there is a method and order in ç
the dealing of the subject matter. It starts with the description ç
of the antar<193>tman, the Innermost Self, the same as Adhy<193>tman, ç
(hence the name Adhy<193>tma Upani<218>ad) who exists in all things ç
and beings controlling them from within, but whom none of them knows. ç
He has also been called `N<193>r<193>ya<207>a' here (verse 1). After ç
declaring that the sense of `I' and `mine' with regard to the body ç
and the senses which are an<193>tman or non-Self, arises due to adhy<193>sa ç
or superimposition by ignorance, the Upani<218>ad exhorts us to get ç
rid of this adhy<193>sa by being devoted to Brahman and through discrimination. ç
The line of arguments to be pursued in this is practically the same ç
as in Advaita Ved<193>nta (v. 2-11). This is followed by a description ç
of the <193>tman-Brahman principle as the one without a second, and ç
without internal distinctions. The disciple is asked to see It as ç
his own Self (v. 12-27). Renunciation leads to intuitive knowledge ç
which results in the withdrawal of the mind into itself. Resting it ç
on the <193>tman, one attains infinite peace and joy or realization. ç
This is the next topic (v. 28 and 29). Then, the identity between ç
the j<200>va (individual soul) and Brahman (the Cosmic Soul) is shown ç
by negating the accidental characteristics like association with the ç
mind and the m<193>y<193>-power (v.30-32) followed by a delineation ç
of the three s<193>dhan<193>s or practices, ·rava<207>a (hearing), ç
manana (reflection) and nididhy<193>sana (meditation) resulting in ç
sam<193>dhi (superconscious experience) (v. 33-35). Then, there is ç
the description of `dharma-megha-sam<193>dhi,' `the sam<193>dhi which ç
results in kaivalya or liberation' (v.36-43). This is followed by ç
a nice pen-picture of the j<200>vanmukta, one who is liberated even ç
while living in the body (v.44-47). He is never affected by the vicissitudes ç
of life and is ever in equipoise. Then <|>the <|>Upani<218>ad <|>says ç
<|>that <|>the knowledge of the <193>tman destroys all the previously ç
accumulated karmas, except the pr<193>rabdha-karma which has already ç
begun to fructify. It can be exhausted only through experience. However, ç
the liberated soul is unaffected by it (v.48-60). It ends with a ç
poetic description of the personal experience of the j<200>vanmukta ç
(v. 61-69).
This Upani<218>ad is sometimes called Tur<200>y<193>t<200>ta Avadh<220>ta ç
Upani<218>ad also.
See also <MS>UPANI<186>ADS<D>.
@NT = adhy<193>tmavidy<193>
@N1 = (`science pertaining to the Self within')
The Hindu sages have always advocated mok<218>a (liberation from transmi- ç
gration) as the parama-puru<218><193>rtha (the highest goal to be ç
achieved by man) and have recommended adhy<193>tmavidy<193> as the ç
means of achieving it. Adhy<193>tmavidy<193> is the science that leads ç
one to the realization of the Self within. It is the knowledge and ç
wisdom taught in the Upani<218>ads, the Bhagavadg<200>t<193> and ç
other works which follow them. A study of these books under enlightened ç
teachers will lead to a clear understanding of the <193>tman or the ç
Self and meditation on this understanding will ultimately lead to ç
realization. Par<193>-vidy<193> and brahmavidy<193> are other words ç
often used as synonyms for this. It is the highest knowledge and the ç
only one worth seeking in life. Hence in the Bhagavadg<200>t<193>, ç
Lord K<216><218><207>a goes to the extent of identifying himself with ç
it (vide 10.31).
@NT = <193>dhy<193>tmika
@N1 = (`pertaining to the Self<|>')
See <MS>°DHIBHAUTIKA<D> and <MS>ADHY°TMA.<D>
@NT = adhyayana<M> and <D>adhy<193>pana
@N1 = (`studying and teaching')
Study of the Vedas, technically termed `adhyayana,' was considered ç
not only as part of education but as part of religious life as well. ç
Since a change of svara (intonation) would often entail a change of ç
meaning as well, great care was exercised in preserving the oral musical ç
tradition of the Vedas.
The student desirous of learning the Vedas had to live in the house ç
of the guru,after first completing the sacrament of upanayana. Avoiding ç
the days known as`anadhyayana' <|>(or anadhy<193>ya) (See <MS>ANADHY°YA.<D>) ç
on all other permissible days he could approach the guru for Vedic ç
studies after finishing the daily religious chores like the sandhy<193>. ç
He had to sit facing north. The guru would recite the Vedic mantras ç
p<193>da by p<193>da (i.e., a quarter of a stanza) and the student ç
had to repeat them at leasttwice. Once he learnt the correct pronunciation ç
and intonation and also committed it to memory, the guru would proceed ç
with the next part. The student had to revise the lessons by himself ç
or with the help of senior students the same day. The study would ç
cover the Sa<221>hit<193>, the Br<193>hma<207>a and the Upani<218>ad ç
parts of the particular ·<193>kh<193> (branch) of the Veda to which ç
the student belonged. It would normally take twelve years to master ç
one's ·<193>kh<193>.
Along with the Vedic studies, a study of the Ved<193><209>gas (subsidiaries ç
like grammar) dharma·<193>stras, itih<193>sas and pur<193><207>as ç
as also some secular sciences would also be pursued.
As for teaching (adhy<193>pana), it was expected that the teacher ç
(adhy<193>paka or <193>c<193>rya) should be well-versed and competent ç
and of a sinless life. He could teach anyone eligible for Vedic studies, ç
on any of the following three conditions: (1) as dharma, as part of ç
his duties; (2) for artha or wealth, if the student promised it beforehand; ç
(3)as a reward for ·u·r<220><218><193> or personal service. He was ç
not expected to teach if none of these conditions was fulfilled.
@NT = °dim<220>rti
@N1 = (`the Original form')
Vi<218><207>u, the central deity of the Hindu Trinity, manifests himself ç
in several forms. `°dim<220>rti' is one of them. Considered as a minor ç
manifestation, he is described in iconographical works as sitting ç
upon the serpent °di·e<218>a, with the right leg hanging and the left ç
as folded and resting upon the seat. Of the four hands, the two back ç
hands hold as usual, the ·a<209>kha (conch) and cakra (discus). The ç
front right hand rests upon the seat whereas the front left is supported ç
on the folded left knee. The colour of the figure is coral red and ç
it is richly decorated with ornaments. The other two gods of the Trinity, ç
Brahm<193> and <185>iva, as also the sages Bh<216>gu and M<193>rka<207><195>eya ç
are also shown, in a reveren-tial aspect.
@NT = °din<193>tha
@N1 = (`the Primeval Lord')
The esoteric N<193>tha cult which originated in Bengal and the followers ç
of which are found in some parts of North India considers the Supreme ç
Being as elusive and intangible, and as manifested in the universe ç
created out of him. It designates him as `°din<193>tha.' Following ç
in the footsteps of the <184>gveda (10.129) and the opening verse ç
of Manusa<221>hit<193>, the N<193>tha cult describes the beginning ç
of creation as starting from a bubble or an egg which appeared as ç
a result of the impulse for creation in the infinite void and all- ç
encompassing darkness. The egg hatched and out of it emerged `°din<193>tha' ç
the primeval God. From his sweatwas produced his spouse Ketak<193> ç
or Manas<193> who in turn created Brahm<193>, Vi<218><207>u and <185>iva. ç
Further creation proceeded out of them.
The first of the nine N<193>tha gurus is also °din<193>tha.
See also <MS>N°THA-CULT<D>.
@NT = °diparva
Mah<193>bh<193>rata, <|>the <|>great<|> epic <|>of Hinduism and the ç
biggest didactic work of poetry in world literature, is divided into ç
eighteen books, each of which is known as a `parvan.' °diparva forms ç
the very first book. For details see under <MS>MAH°BH°RATA<D>.
@NT = °dipur<193><207>a
@N1 = (`the original mythology')
Every religion has three aspects: philosophy, mythology and rituals. ç
While philosophy tries to find solutions to the ultimate questions ç
and problems of life, mythology tries to explain the truths discovered ç
by it, through stories, allegories and examples. The Hindu mythological ç
lore, designated `pur<193><207>a,' does this and much more. It gives ç
whole systems of knowledge in various fields whether allied to or ç
even remotely connected with philo-sophy, or not. The °dipur<193><207>a ç
is one of the pur<193><207>as often included in the lists.
According to one tradition, it is the original pur<193><207>a, as ç
its very name implies, composed by Brahm<193> the Creator himself.
Comprising four hundred thousand verses, it is the source book for ç
all the other pur<193><207>as written by Vy<193>sa. The book however ç
is not available now.
Among the extant pur<193><207>as, the Brahmapur<193><207>a is occasionally ç
designated as °dipur<193><207>a also. One °dipur<193><207>a is ç
sometimes listed among the minor pur<193><207>as known as upapur<193><207>as. ç
This book, now available in print is obviously a much later work. ç
It is mainly the story of K<216><218><207>a.
The Jaina tradition (digambara sect) also has an °dipur<193><207>a, ç
an incomplete work by one Jinasena, a part of which was added on later ç
by another author Gu<207>abhadra. It describes the stories of <184><218>abhadeva ç
and Bharata, the first two T<200>rtha<209>karas.
See also <MS>PUR°ØAS<D> and <MS>UPAPUR°ØAS<D>.
@NT = °di·akti
@N1 = (`Primeval Power')
The source and sustenance of all creation whether at the level of ç
matter, mind or life, is one. It is called <185>akti (power or energy). ç
Hinduism posits a cyclic theory of creation (s<216><218><219>i), preservation ç
(sthiti) and destruction (pralaya) and this goes on eternally. It ç
is the <185>akti of God that is responsible for this. This <185>akti ç
is usually conceived as a female deity, as the Consort of God. Since ç
she is the original source, she is often called `°di·akti,' the Primeval ç
Power.
It is the <185>aiva and <185><193>kta °gama works that propound this ç
theory of <185>akti, and She is fully identified with P<193>rvat<200>, ç
<185>iva's Consort. M<193>y<193> (the illusory power of God) of Ved<193>nta ç
and Durg<193> of the pur<193><207>as are also called °di·akti since ç
they also are identified with P<193>rvat<200>.
See also <MS><185>AKTI<D>.
@NT = °di·e<218>a
In the Hindu mythological literature, °di·e<218>a is described as ç
a mighty serpent of a thousand hoods on which he is supporting the ç
world. He forms the bed on which Lord N<193>r<193>ya<207>a is reclining. ç
Ananta, Anantan<193>ga, <185>e<218>a and <185>e<218>an<193>ga are ç
his other names. Born as the son of Kadru and Ka·yapa he later on ç
dropped out of the company of his brother-serpents since  they  illtreated  his  step-mother ç
Vinat<193> who was a good and noble woman. He pleased Brahm<193>, ç
the Creator, by severe austerities and obtained the boon of the power ç
to support the world on his hoods. Lord N<193>r<193>ya<207>a was pleased ç
to make him hiscouch. Lak<218>ma<207>a and Balar<193>ma, the brothers ç
of R<193>ma and K<216><218><207>a, are said to be the incarnations ç
of °di·e<218>a. So also Pata<210>jali, the promulgator of the Yoga ç
system of philosophy.
It is obvious that this is a highly allegorical and symbolical picture. ç
°di·e<218>a really stands for cosmic time and space which are `ananta,' ç
endless or infinite. Hence, the myth of °di·e<218>a supporting the ç
world on his thousand hoods signifies that the created world comes ç
into being in the infinite time and space and is sustained by them. ç
The thousand hoods stand for the innumerable divisions of time and ç
space.
The word `·e<218>a' means `what is left over', `the remainder'. Since ç
creation cannot proceed out of nothing, it is to be assumed that `something' ç
is left over (·e<218>a) from the previous cycle of creation. So <185>e<218>a ç
represents the totality of j<200>vas or individual souls in their ç
subtle forms left over from the previous cycle and needing more opportunities ç
for redemption.
The serpent usually stands for k<193>ma or desire, which is always ç
left over (·e<218>a) even after acquiring and enjoying the desired ç
object. Hence in a cosmic sense it can stand for the desire of the ç
Lord to proceed with the next cycle of creation after rest.
@SPACE1 = 
Lord N<193>r<193>ya<207>a reclining upon the serpent couch can mean ç
that desire for creation as also time and space form the basis, resting ç
on which he proceeds with creation.
See also <MS>N°R°YAØA<D>.
@SPACE = 
@NT = Aditi
@N1 = (`the boundless')
Aditi, the `devam<193>t<193>' (mother of the gods) is one of the few ç
goddesses mentioned in the <184>gveda and other Vedic literature. ç
She is often associated with Diti, her sister, and mother of the daityas ç
(demons). She is eulogised as the boundless and identified with practically ç
everything in the created world. She is the sky and the air. The threeaspects ç
of time are also she. She has become all the human beings, nay, even ç
the gods. She is the mother and she is the father too. That is why ç
supplications are made to her to confer her blessings on children ç
and cattle as also for the removal of sins (vide <184>gveda Sa<221>hit<193> ç
1.89.10).
In the mythological lore of the Vedas she is usually described as ç
one of the daughters of Dak<218>a, though sometimes she is said to ç
be his mother. There are also passages which mention her as the wife ç
of Vi<218><207>u instead of Ka·yapa. However according to most of ç
the accounts she was married to the sage Ka·yapa for whom she bore ç
several sons. The gods being her sons are called °diteyas. Sometimes ç
the eight °dityas are described as her sons. Out of these eight, she ç
is said to have cast out the last son M<193>rtta<207><195>a.
Coming to the Upani<218>ads, the word `Aditi'<|> is <|>used <|>to<|> denote ç
<|>death, <|>the devourer (ad = to devour) (B<216>had<193>ra<207>yaka ç
Upani<218>ad 1.2.5), and the deity presiding over the earth (Mah<193>n<193>raya<207>a ç
Upani<218>ad 28.1) as also the j<200>v<193>tman or the individual ç
soul (Ka<219>ha Upani<218>ad 4.7).
In the epics and the pur<193><207>as she is always depicted as the ç
daughter of Dak<218>a, wife of Ka·yapa and mother of gods including ç
the V<193>mana incarnation of Vi<218><207>u. Indra is said to have ç
picked up a pair of divine ku<207><195>alas (ear-rings) as they were ç
thrown up by the churning of the primeval ocean (See <MS>SAMUDRAMATHANA<D>) ç
and presented them to Aditi. But the demon Narak<193>sura Bhauma (the ç
son of Bh<220>mi or earth) stole them from her. It was K<216><218><207>a ç
who recovered and restored them to her.
Aditi is also the name of a place of pilgrimage on the bank of the ç
river Ga<209>g<193>.
@NT = °ditya, °dityas
@N1 = (`son/sons<|>of Aditi')
°ditya is one of the well-known epithets of the sun.
The °dityas, the sons of Aditi, repre-sent a group of deities. They ç
are six in the <184>gveda, eight in most of the Br<193>hma<207>as ç
(except the <185>atapatha) and twelve in the later mythological ç
lore. They can be described as the personifications of the laws that ç
rule the universe and the human society. They regulate the relationships ç
of human beings among themselves and with the forces of nature.
Since °ditya is one of the names of the sun, the °dityas can be considered ç
as imperishable beings, the gods of light, by whom all kinds of luminous ç
life are manifested and sustained in this universe.
The twelve °dityas are: Mitra (the friend), Varu<207>a (one who encompasses ç
and binds), Aryaman (the destroyer of foes), Dak<218>a (the skilful), ç
Bhaga (the giver), A<221>·a (the liberal), Tva<218><219><216> (the ç
shaper), Savit<216> (the vivifier), P<220><218>an (the nourisher), ç
<185>akra (the mighty), Vivasvat (the resplendent) and Vi<218><207>u ç
(the pervader).
Sometimes, these twelve are linked with the twelve aspects of the ç
sun spread over the twelve months and hence des-cribed as the twelve ç
spokes of the wheel of time.
See also <MS>S<188>RYA.
@SPACE1 = 
@NT = <193>ditya-dar·ana
@N1 = (`seeing the sun')
@SPACE1 = 
Every Hindu has to undergo certain sa<221>sk<193>ras or sacraments<192>religious ç
rites conducive to inner evolution<192>at various stages of his life. ç
The dharma·<193>stras list them as sixteen; hence the name `<218>oda·a-sa<221>sk<193>ras' ç
(<218>oda·a = 16). One such <218>a<221>sk<193>ra called `ni<218>krama<207>a' ç
(lit., `going out') consists of taking the baby outside the lying-in ç
chamber for the first time, to see the sun. This is `<193>ditya-dar·ana.' ç
For details see <MS>NI<186>KRAMAØA.<D>
See also <MS>SA<189>SK°RAS<D> and <MS><186>ODA<185>A-SA<189>SK°RAS<D>.
@SPACE1 = 
@NT = °ditya-h<216>daya
@N1 = (`the heart or the essence of °ditya')
@SPACE1 = 
Hindu hymnal literature is as vast as it is deep. Quite a few of these ç
hymns, whether they contain praises of the Lord or expound some philosophical ç
doctrines, are often used for ceremonial chanting, considering them ç
as mantras (esoteric wordsand sentences) capable of fulfilling one's ç
desires. The R<193>m<193>ya<207>a of V<193>lm<200>ki, though a voluminuous ç
work, strangely enough, contains only one such hymn; strangely enough ç
because, the Mah<193>-bh<193>rata, the other epic, as also the pur<193><207>as ç
contain scores of them. This hymn known as the `°dityah<216>daya' ç
occurs in the Yuddhak<193><207><195>a (sarga 105).
After the first round of battle with R<193>va<207>a, R<193>ma was ç
rather tired and anxious as to how he could vanquish his formidable ç
enemy. Just at that time, Agastya the sage of the Vindhya fame, who ç
was among those that had gathered to witness the battle, came forward ç
to reveal a secret with the help of which R<193>ma could conquer R<193>va<207>a ç
and fulfil the mission of his life. The secret was the °dityah<216>daya ç
hymn by reciting which he could get enough power to destroy his foe. ç
Being initiated into its mysteries by Agastya, R<193>ma recited it ç
thrice, became imbued with energy and enthusiasm and achieved victory ç
with ease.
Whether the °dityah<216>daya comprises the entire chapter or part ç
of it only (e.g., verses 6 to 21) is a point on which there are differences ç
of opinion. Verses 1 to 5 form the introduction and eulogise the hymn. ç
Verses 6 to 21 describe °ditya or the Sun-god, his various names and ç
attributes. Verses 22 to 25 describe his power and give the phala·ruti ç
(the benefits of recitation). Verse 26 gives the viniyoga (the method ç
and purpose of recitation). Verses 27 to 31 complete the narration ç
of the story.
@SPACE1 = 
Here are a few of the epithets which the hymn uses to describe and ç
eulogise °ditya: He is so effulgent that even the gods adore him. ç
In fact he is the very personification of all gods including the Trinity. ç
It is he that is manifested as the leaders of the eight quarters. ç
He is the creator and sustainer of the world. It is again he that ç
destroys the world at the end of the cycle of creation. He is manifested ç
in everything that is created.
The proper recitation of the hymn will free a man from all troubles ç
and tribulations and fulfil the wishes of his heart.
Every mantra has a <216><218>i (the seer to whom it was revealed), ç
a chandas (the poetical metre) and a devat<193> (the deity to whom ç
it is addressed), who are to be adored at the beginning of a ceremonial ç
recitation. In the case of this hymn (which is considered as a mantra), ç
Agastya is the <216><218>i and anu<218><219>ubh is the chandas. As ç
regards the devat<193>, some state that Brahm<193> residing in the ç
sun is the deity whereas others consider R<193>ma the Supreme God, ç
the internal ruler of the sun, is himself the deity. The viniyoga ç
or purpose is to obtain supreme knowledge or victory in all walks ç
of life.
Any Sunday on which there is a sa<209>kr<193>nti (movement of the ç
sun from one zodiacal sign to the next) is believed to bevery holy ç
and suitable for the recitation of this hymn. Repeating it 108 times ç
in aSun-temple and observing a fast in thenight are considered to ç
be highly meritorious.
@NT = °dityapur<193><207>a
@N1 = (`pur<193><207>a concerning <R>ç
°ditya or Sun-god')
Pur<193><207>as or the mythological lore of the Hindus are a vast ç
body of literature dealing with not only philosophical and religious ç
subjects but also cultural and even mundane subjects. They are divided ç
into two broad groups: The Mah<193>pur<193><207>as (the great, big ç
or main pur<193><207>as) and the Upapur<193><207>as (small or subsidiary ç
pur<193><207>as). °dityapur<193><207>a, a pur<193><207>a dealing ç
with the deity °ditya (Sun-god), is often mentioned in the latter ç
group. The book itself is not available now, except for some quotations ç
incorporated by the dharma·<193>stra literature. These quotations ç
concern the following subjects: r<193>jadharma (duties of the king), ç
d<193>na (gifts), ·r<193>ddha (obsequial offerings), vrata (religious ç
vows and obser- vances) and ·auca (ceremonial purity).
The Matsyapur<193><207>a (53.62) as also Al Beruni (<F51320MS>A. D.<W1> ç
1030) mention this pur<193><207>a.
See also <MS>PUR°ØAS<D>.
@NT = °ditya-·<193>nti-vrata
@N1 = (`religious vow to<R>ç
appease °ditya or Sun-god')
Vratas or religious vows and observances are a common form of practical ç
religion in Hinduism. These vratas are undertaken either for fulfilling ç
a desire withdivine intervention or for expiating sin or even as ç
observing a spiritual discipline.
The °ditya·<193>ntivrata can be observed on any Sunday associated ç
with the Hast<193>-nak<218>atra. Worshipping the image of the Sun ç
with 28 or 108 fuel sticks of the arka plant (Calatropis gigantea) ç
is the main part of the ritual. These fuel sticks are to be offered ç
with honey and ghee (or ghee and curds) in homa (fire sacrifice). ç
The vrata can be repeated seven times.
See also <MS>VRATAS<D>.
@NT = °dityat<200>rtha
@N1-1 = (`place of pilgrimage connec- ted with °ditya or Sun-god')
Places of pilgrimage have always played a very important part in the ç
life of a devout Hindu. Endowed with natural beauty and conducive ç
to peace and blessed-ness these places have been attracting millions ç
of pious pilgrims since millennia.
°dityat<200>rtha is one of the less known places of pilgrimage mentioned ç
in some of the Hindu scriptures (vide <185>alyaparva, ch.49 of ç
Mah<193>bh<193>rata). Situated on the bank of the now invisible ç
Sarasvat<200> river, the place got its name on account of its association ç
with °ditya (Sun) who performed a sacrifice there and obtained lordship ç
over all bright objects. It was here that Lord Vi<218><207>u killed ç
the demons Madhu and Kai<219>abha.
Again it was in this sacred place thatgreat sages like Vy<193>sa, ç
K<216><218><207>a and <185>uka performed austerities and gained perfection.
The Padmapur<193><207>a locates it at the confluence of the river ç
S<193>bhramat<200> with the sea.
See also <MS>T®RTHAS<D>.
@NT = °dityavrata
@N1 = (`vrata to please °ditya')
A brahmac<193>rin (celibate student) living in the house of the <193>c<193>rya ç
(preceptor) had to observe several vratas (religious observances) ç
as part of the student-life. Whenever the study of new sections of ç
the Vedas had to be commenced he had to prepare himself physically ç
and mentally for the same. For instance the followers of S<193>maveda ç
were required to perform five vratas before studying its several sections:   god<193>nika,   vr<193>tika,   <193>ditya, ç
aupani<218>ada and jye<218><219>has<193>ma vratas.
°dityavrata  was  considered  as optional by some authorities, whereas ç
the other vratas were compulsory. It had to be performed before beginning ç
the study of the·ukriya section (last part of the °ra<207>yaka) of ç
the S<193>maveda.
Before beginning the vrata n<193>nd<200>-mukha-·r<193>ddha   (See   <MS>°BHYUDAYIKA ç
<185>R°DDHA.<D>) had to be performed and upanayana sa<221>sk<193>ra ç
had to be undergone once again, followed by <193>jyahoma (offering ç
ghee into the fire) with °ditya mantras. During the period of the ç
vrata which lasted for a year, the brahmac<193>rin had to wear only ç
one cloth and avoid taking protection against the sun's rays by contrivances ç
like umbrella. Of course, taking shelter in the house or under trees ç
was allowed. Also, he was prohibited from entering into more than ç
knee-deep water, for bath. The vrata had to be concluded with offering ç
caru (porridge of unpounded rice) to Indra, repeating the <193>jyahoma ç
and gifting a cow to the <193>c<193>rya (preceptor).
@NT = °divar<193>ha
See <MS>BH<188>VAR°HA<D>.
@NT = °div<193>s<200>s
@N1 = (`Original inhabitants')
The population of the °div<193>s<200>s, the original inhabitants of ç
India or aboriginals †that is what the name signifies†exceeds thirty ç
million. They are primarily to befound in north-east India, Bihar, ç
Orissa, Madhya Pradesh and parts of Maharashtra, Deccan and South ç
India. How many of them are really the `original' inhabitants and ç
how many have come as migrants is anybody's guess. The various tribes ç
of °div<193>s<200>s largely inhabiting the mountain and jungle areas ç
differ widely from one another with regard to racial characteristics, ç
language, food habits, modes of dress, means of occupation as also ç
their cult and culture. By and large they are treated as belonging ç
to Hindu culture.
@SPACE1 = 
Their religious beliefs and observances include the worship of nature ç
and totems as also their ancestors and spirits. Taboos are many. Bloody ç
sacrifices are common. Priests are sorcerers too and have a tight ç
grip over the community. Modern education, wherever it has percolated, ç
is fast changing the complexion of their life style.
@NT = adoption
See <MS>DATTAKA<D>.
@NT = adravya
@N1 = (`non-substance')
The Indian systems of metaphysics known as `dar·anas' invariably deal ç
with three topics: Pram<193> (valid knowledge), pram<193><207>a (means ç
of valid knowledge) and prameya (objects of valid knowledge)
The Vi·i<218><219><193>dvaita Dar·ana, one of the important schools ç
of Ved<193>nta, whose chief exponent was R<193>m<193>nuja (<F51320P10MSC1>A. ç
D.<W1> 1017-1137) categorises prameya into two broad groups of `dravya' ç
(substance) and `adravya' (nonsubstance).
If dravya acts as a substratum or locus of change, adravya is an attribute ç
or quality always necessarily dependent on dravya. Neither dravya ç
nor adravya can be thought of apart from the other.
The adravyas are ten: sattva, rajas and tamas (the three gu<207>as ç
or qualities of prak<216>ti or insentient nature); ·abda (sound), ç
spar·a (touch), r<220>pa (colour or form), rasa (taste) and gandha ç
(odour) being the five characteristic qualities of the five bh<220>tas ç
like <193>k<193>·a (ether); sa<221>yoga (conjunction or external relation ç
between substances) and ·akti (potency or the effecting agency in ç
all causal substances as for instance, plasticity in clay or the power ç
of attraction in a magnet).
@SPACE1 = 
According to Vi·i<218><219><193>dvaita, instances
