@NID = with, the reflections too disappear, leaving only the original ç
intact. This view was propounded mainly by Padmap<193>da (<MS>A. D.<D> ç
820) and his successors and is one of the characteristic features ç
of the Vivara<207>a School.<F51320W1>
In the latter theory, propounded by the Bh<193>mat<200> School, when ç
Brahman the Absolute, appears to be limited by m<193>y<193>, it becomes ç
®·vara; when limited by avidy<193>, it becomes the j<200>vas. A classic ç
example for this limitation theory is the sky or space (<193>k<193>·a) ç
and containers like a pot. Though space is unlimited, it appears to ç
be limited by a pot or a room or a house. On the destruction of these ç
limiting adjuncts, space `regains' its original status.
See also <MS>ADVAITA VED°NTA DAR<185>ANA<D>.
@NT = avadh<220>ta
@N1 = (`one who has shaken off [the worldly bonds]')
The word `avadh<220>ta,' often met with in the Hindu religious literature, ç
generally refers to a perfect man, also called a `paramaha<221>sa' ç
or an `ativar<207><193>·ramin.' The Bh<193>gavata (skandha 11, chapters, ç
7, 8 and9) mentions an avadh<220>ta who had twentyfour teachers. ç
The list includes the pa<210>cabh<220>tas or the five elements, animals ç
like elephant and deer, and human beings like a maiden and a child. ç
He says that he learnt a lesson each, from each of them through careful ç
observations.
The Avadh<220>tag<200>t<193>, a work ascribed to Avadh<220>ta Datt<193>treya, ç
gives a description of the characteristics of an avadh<220>ta, based ç
on the four syllables†a, va, dh<220> and ta (8.5-9): He is free from ç
desires. Ever pure, he lives in bliss. His speech is faultless. He ç
has no body-consciousness. His mind is ever absorbed in Brahman and ç
hence he has no need to practise meditation. He is totally free from ç
egoism and ignorance.
Avadh<220>ta Datt<193>treya has been mentioned in several Upani<218>ads.
In a more restricted sense, the term `avadh<220>ta' is applied to ç
the senior N<193>g<193> s<193>dhus of the da·an<193>m<200> orders ç
living in holy places like Rishikesh. They may or may not be naked. ç
But they wear matted hair, necklace of rudr<193>k<218>a beads or even ç
bones, and are indifferent to rules of observance common to other ç
monastic or religious orders. Several types have been noted among ç
them: Brahma-avadh<220>ta, <185>iva-avadh<220>ta, Bhakta-avadh<220>ta ç
and Ha<221>sa-avadh<220>ta.
The avadh<220>tas base their practices on the tantras.
Female ascetics of this variety are also known to exist and are called ç
`avadh<220>t<193>n<200>s.'
See also <MS>DA<185>AN°M®S<D> and <MS>DATT°TREYA<D>.
@NT = Avadh<220>tag<200>t<193>
@N1 = (`song of the Avadh<220>ta')
The Avadh<220>tag<200>t<193> is one of the 36 minor philosophical ç
poems composed in imitation of the well-known Bhagavadg<200>t<193>. ç
It is an independent treatise on Advaita Ved<193>nta and preaches ç
an uncompromising non-dualism. Its authorship is attributed to Avadh<220>ta ç
Datt<193>treya. Hence it is also called Dattag<200>t<193> or Datta-g<200>t<193>-yoga·<193>stra. ç
It is also titled, though rarely, Ved<193>ntas<193>ra.
This small treatise of 271 verses is divided into 28 chapters. The ç
first chapter deals with the nature of the <193>tman, which is omniscient, ç
omnipotent and omnipresent; which has no birth, no death, no bondage ç
and no liberation either. The second deals with the proofs for the ç
same. Duality is born out of ignorance of the real nature of the one ç
Divine. Incidentally, even the great Avadh<220>ta has hinted at the ç
need for a spiritual guide (2.23) in realizing the <193>tman. The ç
next two chapters deal with the inner nature of the <193>tman in highly ç
poetical tones. The fifth chapter advises a man to avoid all lamentations, ç
as the <193>tman is the same in all conditions. The sixth chapter ç
negates all kinds of distinctions whether of caste or family, of senses ç
or their objects, of the mind or the intellect or their activities†because ç
none of these exists when looked at from the standpoint of the <193>tman. ç
The seventh describes the state of the avadh<220>ta. The eighth gives ç
a definition of the word `avadh<220>ta' by interpreting each of the ç
four syllables (a, va, dh<220>, ta) of that word.
See also <MS>AVADH<188>TA<D> and <MS>DATT°TREYA<D>.
@NT = Avadh<220>ta Upani<218>ad
This is one of the minor Upani<218>ads belonging to the K<216><218><207>a ç
Yajurveda and classed among the Sa<221>ny<193>sa Upani<218>ads, i.e., ç
Upani<218>ads teaching sa<221>ny<193>sa or stressing a life of renunciation. ç
The text is a mixture of prose and poetry and has 36 verses/sections.
S<193><209>k<216>ti approaches Avadh<220>ta Datt<193>-treya and questions ç
him thus: `Who is an avadh<220>ta? What is his mental state? Whatare ç
his characteristics? What is sa<221>sara<207>a?'
Datt<193>treya replies: `An ``avadh<220>ta'' is one who has identified ç
himself with the (a =) ``ak<218>ara'' or the indestructible Brahman, ç
who is (va =) ``vare<207>ya'' or excellent, who has destroyed all ç
bonds of transmigration (dh<220> = dh<220>ta-sa<221>s<193>rabandhana) ç
and has become the goal of the Upani<218>adic sentences like (ta =) ç
``tat tvam asi.''<|>' Since he has already realized the <193>tman or ç
the Self, there is no need for him of following the rules and regulations ç
of var<207>a and <193>·rama (castes and stages of life). Hence he ç
is also called an `ativar<207><193>·ramin' (one who has transcended ç
the var<207>a-<193>·rama-system).
`Immortality  can  be  attained  by renunciation alone and not by ç
rituals or progeny or wealth.
`<|>``Sa<221>sara<207>a'' means moving freely among the ignorant people ç
to destroy their ignorance of the Self.
`He may move about stark naked, partially clad or well-clad.
`He sacrifices only to the inner Self and is free from all actions.
`Though experiencing objects of senses, he is not tainted by them ç
even as the sun is not tainted by the nature of the objects upon which ç
he shines.
`He is not affected by the desires entering into him even as the ocean ç
does not overflow by the waters of the rivers entering it.'
@SPACE1 = 
Then follow some verses describing the inner state of the avadh<220>ta: ç
`The highest truth is that there is no creation, nor any destruction. ç
There is no s<193>dhaka (spiritual aspirant) nor a mukta (the liberated ç
one). Those interested in progeny or wealth or other things, may engage ç
themselves in action and suffer transmigration. But I am ever filled ç
with bliss. I am not interested even in sleep or begging for food. ç
I have no need for ·rava<207>a (listening to Ved<193>ntic texts) or ç
manana (reflecting on them) or nidi-dhy<193>sana (meditation). Let ç
pr<193>rabdha karma (results of actions of previous lives) take its ç
own course. Though I am now liberated, there is no harm in my following ç
the path prescribed by the ·<193>stras or scriptures to set an example ç
to the ignorant people. I am ever blessed since I know my Self and ç
the bliss of Brahman is being clearly experienced.'
The Upani<218>ad closes with a phala-·ruti (eulogy) of the results ç
that can be obtained if this is studied and realized.
@SPACE = 
@NT = <193>v<193>hana
@N1 = (`invitation')
During the Vedic sacrifices, gods have to be invited to come to the ç
y<193>ga·<193>l<193> or the sacrificial shed, to receive their share ç
of the offerings. During the ·r<193>ddha or obsequial rites, the pit<216>s ç
or manes have to be invited to come and receive their offerings. Both ç
these are done with appro- priate mantras. This act of inviting is ç
technically called `<193>v<193>hana.'
°v<193>hana is also done during the consecration of an image in a ç
temple. The deity is invoked to come in its subtle form and reside ç
in that image permanently, receiving worship and conferring boons.
In p<220>j<193> or ritualistic worship, <193>v<193>hana is considered ç
as one of the upac<193>ras or items of service to honour the deity. ç
The particular mudr<193> or handpose exhibited during the act is called ç
`<193>v<193>han<200>-mudr<193>.'
@SPACE = 
@NT = avak<200>r<207>in
@N1 = (`one who has violated [the vow]')
A Vedic student living in the house of the guru to learn the Vedas ç
and allied sciences was called a `brahmac<193>rin.' He had to follow ç
a given routine, observe a prescribed code of conduct and keep certain ç
vows. Any violation of these vows, whether intentional or unintentional, ç
had to be atoned by appropriate pr<193>ya·cittas or expiatory rites. ç
Violation of the vow of brahmacarya or celibacy was the worst of these. ç
The brahmac<193>rin who wilfully had sexual intercourse with a woman ç
was called an `avak<200>r<207>in.' The Dharmas<220>tras of °pastamba ç
(1.9.26.8) and Vasi<218><219>ha (23.1-3) as also the Manusm<216>ti ç
(11.118-121) prescribe that the avak<200>r<207>in should sacrifice ç
an ass to the deity Nir<216>ti, which is symbolic of the stupid lapse, ç
wear the skin of an ass for one year, should beg his food from seven ç
houses announcing to them his lapse, take food only once in a day ç
and bathe thrice a day. Then only he will become pure. Vasi<218><219>ha ç
substitutes an oblation of boiled rice for the sacrifice of an ass.
See also <MS>BRAHMAC°RIN<D>.
@NT = av<193>ntara-d<200>k<218><193>
@N1 = (`secondary initiation')
A yajam<193>na (one who performs a sacrifice) is expected to take ç
d<200>k<218><193> or initiation at the beginning of the sacrifice ç
he is undertaking. This is a purificatory ritual which imposes on ç
him certain rules and code of conduct.
Sometimes, as a part of a major sacrifice, minor rites also will have ç
to be performed. Some of these, considered as very important, require ç
the yajam<193>na and his wife to take an additional d<200>k<218><193>. ç
Such a d<200>k<218><193>, taken at the beginning of a subsidiary rite ç
which itself is part of a bigger sacrifice, is called `av<193>ntarad<200>k<218><193>.' ç
For instance in the Agni<218><219>oma (a Soma-y<193>ga), av<193>ntarad<200>k<218><193> ç
has to be taken before the pravargya rite. The yajam<193>na and his ç
wife offer fuel sticks into the <193>havan<200>ya and g<193>rhapatya ç
fires respectively. Touching the water heated in the vessel called ç
`madant<200>,' the yajam<193>na clenches his fists closely, tightens ç
his girdle and drinks hot milk. The d<200>k<218><193> ends with nihnava, ç
a kind of salutation to heaven and earth, by the priests.
See also <MS>D®K<186>°<D>.
@SPACE1 = 
@NT = Avanti
@SPACE1 = 
A well-known janapada or a country, during the period of the Mah<193>bh<193>rata, ç
it was also called Avantik<193>. It was located in western India in ç
the present Ujjain- Mandhata region of Madhya Pradesh. Divided into ç
two parts, the northern region had Ujjayin<200> as its capital whereas ç
the capital of the south was M<193>hi<218>mat<200> (the modern Mandhata). ç
It was being ruled by two brothers Vinda and Anuvinda. They were subdued ç
by Sahadeva, the last of the P<193><207><195>ava brothers and paid ç
contributions towards the expenses of the R<193>jas<220>ya sacrifice.
It is considered to be one of the seven cities (mah<193>pu<207>yanagar<200>s) ç
that confer great merit on those that dwell in it. It was here that ç
S<193>nd<200>pani lived and, Balar<193>ma and K<216><218><207>a were ç
educated. The people of this region were known to be great warriors, ç
being the descendants of Haihayas, the most celebrated of whom was ç
K<193>rtav<200>ry<193>rjuna. Later on, it became the home of Buddhist ç
and Jaina learning.
@SPACE1 = 
@NT = <193>vara<207>a
@N1 = (`veil, cover')
@SPACE1 = 
Derived from the root `v<216>' and with a prefix `<193>,' the word ç
`<193>vara<207>a' means anything which covers or surrounds. In the ç
Advaita Ved<193>nta it refers to the veiling power of m<193>y<193>/avidy<193>. ç
(See <MS>°VARAØA-<185>AKTI.<D>)
In temple architecture, it refers to the enclosures or pr<193>k<193>ras, ç
surrounding the main shrine, wherein the <193>vara<207>a-devat<193>s ç
(minor deities, the attendants of the chief deity) are housed, as ç
also the utsavam<220>rti (procession deity) and other paraphernalia.
In V<200>ra·aivism the word is used for a protective covering, in ç
the spiritual sense. There are eight such <193>vara<207>as. (See <MS>A<186><187>°VARAØAS.<D>)
@SPACE = 
@NT = <193>vara<207>a-devat<193>
@N1 = (`deity [installed in the area] surrounding [the main deity]')
@SPACE = 
The garbhag<216>ha (sanctum sanctorum) of a Hindu temple is generally ç
surrounded by <193>vara<207>as or enclosures whose number may vary ç
from one to seven. Though the main purpose of these <193>vara<207>as ç
is to provide space for pradak<218>i<207><193> (circumambu-lation) ç
round the main deity, they also serve to accommodate the images of ç
other deities considered to be the attendants or the retinue of the ç
main deity. These deities are called `<193>vara<207>a-devat<193>s' ç
or `pariv<193>ra-devat<193>s.'
The Vaikh<193>nas<193>gama lists as many as 135 pariv<193>radevat<193>s ç
spread over seven <193>vara<207>as for a Vi<218><207>u temple. Brahm<193>, ç
Aniruddha, Trivikrama, Varu<207>a, <185>ukra, B<216>haspati, Subhadr<193>†these ç
are some of the deities listed there.
In a <185>iva temple, Dev<200>, Ca<207><195>e·vara and Brahm<193> ç
find a place in the <193>vara<207>as.
In a Dev<200> temple, <185>iva, Vi<218><207>u and Ga<207>apati will ç
invariably be there. So also K<193>rttikeya or Subrahma<207>ya.
@NT = <193>vara<207>a-·akti
@N1 = (`veiling power')
@SPACE = 
According to the Advaita Ved<193>nta as propounded by <185>a<209>kara ç
(<F51320P10MSC1>A. D.<F255P255DC255> 788-820) the ultimate Reality is one only, ç
the one without a second†ekam eva advit<200>yam brahma. But that we ç
perceive this world of multiplicity, is a fact of experience. <185>a<209>kara ç
attributes this to m<193>y<193> or avidy<193> or aj<210><193>na (illusion ç
or nescience or ignorance). This m<193>y<193>/ avidy<193> covers this ç
Truth or Brahman and makes it appear as something else which it really ç
is not, viz., the world. For instance, the semidarkness of twilight ç
covers up the real nature of a rope and the semilight projects it ç
as a snake. The power of m<193>y<193>/avidy<193> to veil the truth ç
is called `<193>vara<207>a·akti' and its power to project it as something ç
else, is called `vik<218>epa·akti.'
Just as bright light destroys the illusory perception of the snake ç
in the rope, even so j<210><193>na, knowledge or direct experience ç
of the Truth (Brahman/°tman) will destroy this m<193>y<193>/avidy<193>.
@SPACE = 
@SPACE1 = 
@NT = <193>vasathya
@N1 = (`related to the dwelling place')
@SPACE1 = 
For performing Vedic sacrifices, duly consecrated fires are needed. ç
The maximum number of such fires is five and they are called `pa<210>c<193>gnis.' ç
They are: g<193>rhapatya, <193>havan<200>ya, anv<193>h<193>ryapacana ç
or dak<218>i<207>a, sabhya and <193>vasathya.
The word `<193>vasathya' is derived from `<193>vasatha' or a dwelling ç
place. According to one view, the br<193>hma<207>as and others who ç
were invited to participate in a sacrifice used to be put up in special ç
dwelling placescalled <193>vasatha (similar to a modern dharma·<193>l<193>) ç
where a fire was to be lit, to ward off cold. This could have been ç
the origin of this fire.
During Vedic sacrifices, this fire is stationed to the east of the ç
sabhya fire, in a hut called `<193>vasatha.' The hearth is triangular ç
in shape, each side being 25 a<209>gulis (a<209>guli = finger's breadth).
Some authorities of Vedic sacrifices held its establishment compulsory ç
and others as optional. For establishing it, the original fire had ç
to be brought from the g<193>rhapatya.
@SPACE = 
@NT = avasth<193>-pari<207><193>ma
See <MS>PARIØ°MA<D>.
@SPACE = 
@NT = avasth<193>-traya
@N1 = (`three states of<R>ç
consciousness')
Works of Ved<193>nta based primarily on the teachings of the Upani<218>ads, ç
recognize three `avasth<193>s' or states of consciousness with which ç
we are all familiar: j<193>grat (waking state), svapna (dream state) ç
and su<218>upti (deep-sleep state). In the j<193>grad avasth<193> ç
both the sense-organs and the mind are active. In the svapna-avasth<193> ç
it is only the mind, impelled by the latent impression of the waking ç
experience, and, sometimes, by the latent impressions of past lives, ç
that is active. In the su<218>upti-avasth<193>, even the mind is at ç
rest.
In all these three states there is always a `witness,' called `s<193>k<218>i-caitanya,' ç
who is ever present as an observer, who also experiences the effects ç
of these states. He is the <193>tman or the Self.
Since he is, apparently, the `fourth' (as opposed to the three states) ç
he is called the `tur<200>ya' (= the fourth). However `tur<200>ya' ç
is not considered as a state of consciousness but consciousness itself.
An analysis of the three states of consciousness leading to the establishment ç
of the <193>tman through reasoning, is called `avasth<193>-traya-viveka' ç
or `avasth<193>-traya-vivecana.'
This subject has been dealt with in detail in the M<193><207><195><220>kya ç
Upani<218>ad and the K<193>rik<193>s of Gau<195>ap<193>da (<F51320MS>A. ç
D.<F255D> 780).
@SPACE = <F51320W1>
@NT = avat<193>ra
@N1 = (`one who has descended')
The concept of `avat<193>ra' (incarnation of the Divine) is one of ç
the fundamental tenets of Hinduism. The locus classicusof the theory ç
of avat<193>ra is in the Bhagavad-g<200>t<193> (4.5-8).
After creating this world, God sets it in motion and regulates it ç
through the cosmic law known as <216>ta, satya or dharma. When the ç
cosmic law, the <216>ta, is comprehended by the intellect, it becomes ç
`satya' (truth). When life is regulated according to it, it becomes ç
`dharma' (righteousness, right conduct).
Since the human mind is a product of the three gu<207>as (sattva, ç
rajas and tamas), it is subject to vicissitudes. In the beginning ç
sattva will have the upper hand and people will naturally be inclined ç
towards dharma. Hence life on earth moves smoothly in harmony and ç
peace. Gradually, as rajas and tamas gain ascend- ance, people will ç
incline towards evil; and this will upset the social equilibrium. ç
Good people devoted to dharma will be neutralised and made ineffective ç
whereas the evil ones addicted to adharma or unrighteousness will ç
rule the roost. At such critical periods in human history God decides ç
to `come down' (avat<193>ra = coming down) in a human form (or even ç
in a non-human form if that is necessary) and restore the spiritual ç
and social equilibrium implied by the word `dharma.'
Though restoring dharma is the primary concern of an avat<193>ra, ç
eliminating or chastising the wicked, and, protecting the good† being ç
a necessary and integral part of this process†are also undertaken ç
by him.
An avat<193>ra is not just a j<200>va who has attained the state of ç
liberation and is eager to help mankind. He represents the direct ç
descent of God himself to the human level in order to help the human ç
beings to ascend to the divine level, of which the liberated soul ç
is a perfect example. A j<200>va is forced to take a body due to his ç
past actions (pr<193>rabdha-karma) whereas the avat<193>ra incarnates ç
of his ownfree will for saving mankind. Consequently, he is always ç
conscious of his mission and power. It is only he who can see both ç
the Absolute (Brahman) and the manifested world simultaneously and ç
can teach the world about the Absolute.
Ved<193>nta admits of God's manifestation as the world, his omniscience ç
as also omnipotence and grace. Hence there is nothing unreasonable ç
in the doctrine that he can also assume a special and unique form ç
as avat<193>ra, fully retaining consciousness of the divinity from ç
his very birth.
@SPACE1 = 
Another speciality of this doctrine is that God incarnates himself ç
in response to the needs of the times wherever and whenever necessary. ç
Hence there are no restrictions regarding either the number of incarnations ç
or the place. The sole consideration is the decline of dharma and ç
the rise of adharma in opposition to it, to such an extent that the ç
social equi- librium is badly disturbed.
The avat<193>ra concept is probably suggested in the <184>gveda ç
itself (3.53.8; 6.47.18) where Indra is said to be endowed with the ç
mysterious power of assuming any form at will. Some of the avat<193>ras ç
mentioned in the lists of the `Da·<193>vat<193>ras' (ten incarnations) ç
are met with in the earlier Vedic literature. The <185>atapatha Br<193>hma<207>a ç
mentions the story of Matsya (fish incarnation) as also of the K<220>rma ç
(tortoise incarnation) and of the Var<193>ha (boar incarnation) (vide ç
1.8.1.1-6; 7.5.1.5; 14.1.2.11). The V<193>man<193>vat<193>ra (dwarf ç
incarnation) of Vi<218><207>u taking the three steps is also clearly ç
mentioned in the same scriptures (1.2.5.1).
@SPACE1 = 
Coming to the age of the epics and the pur<193><207>as we find a tendency ç
towards limiting the avat<193>ras to ten (hence the name `Da·<193>vat<193>ras' ç
or ten incarnations) the last one (Kalki) being yet to come. The Da·<193>vat<193>ras ç
are: Matsya (the fish), K<220>rma (the tortoise), Var<193>ha (the ç
boar), Narasi<221>ha (the man-lion), V<193>mana (the dwarf), Para·ur<193>ma ç
(R<193>ma with the battle-axe), R<193>ma (the son of Da·aratha), K<216><218><207>a ç
(the son of Vasudeva), Buddha (Gautama Buddha) and Kalki. However, ç
there is no unanimity or uniformity in the various lists given by ç
these works. Around the tenth century <F51320P10MSC1>A.<|>D.<F255P255DC255>, ç
Buddha seems to have gained a place in the lists as the ninth incarnation. ç
In the earlier lists as also the later ones, Buddha has been replaced ç
by Balar<193>ma (R<193>ma of strength, elder brother of K<216><218><207>a). ç
Some lists include both Balar<193>ma and Buddha but omit K<216><218><207>a, ç
the raison d'etre being that all the ten are the avat<193>ras of ç
K<216><218><207>a who is the Lord Vi<218><207>u Himself.
Sometimes we come across many more avat<193>ras than the traditional ç
ten. For instance, the Bh<193>gavata gives three lists of 22 names ç
(1.3.6-22), 23 names (2.7.1 ff.) and 16 names (11.4.3 ff.) and also ç
declares that the avat<193>ras are innumerable (1.3.26).
Occasionally the avat<193>ras are classified into three types: p<220>r<207><193>vat<193>ra, ç
a<221>·<193>vat<193>ra and <193>ve·<193>vat<193>ra. P<220>r<207><193>va-t<193>ras ç
are those in which the manifestation of the Divine is full and complete ç
(p<220>r<207>a=full) as in R<193>ma and K<216><218><207>a. A<221>·<193>va-t<193>ras ç
are partial manifestations (a<221>·a = part) of the Divine as in great ç
sages like Vy<193>sa. °ve·<193>vat<193>ras are those in which there ç
is a temporary entry of the Divine (<193>ve·a = entry) as in the caseof ç
N<216>si<221>ha manifesting through Padmap<193>da (a disciple of <185>a<209>kara) ç
who was a votary of that deity.
@NT = <193>ve·<193>vat<193>ra
@N1 = (`[temporary] entry of the Divine')
See <MS>AVAT°RA<D>.
@NT = Ave<218><219>i
Ave<218><219>i is a minor Vedic sacrifice belonging to the `i<218><219>i' ç
group (sacrifices having four priests, and distinguished from the ç
Somay<193>gas) performed as a minor rite in the much bigger R<193>jas<220>ya ç
sacrifice. It may also be performed as an independent rite.
In this sacrifice, puro<195><193>·as (rice-cakes) are offered to propitiate ç
Agni and other deities who supervise over the quarters. The fee is ç
of various kinds, gold being an important item.
@NT = Avidhav<193>-navam<200>-·r<193>ddha
@N1 =  (`obsequial rites to a dead non-widow, on the ninth day')
@EMERGENCY = Married Hindu ladies cherish death before that of their ç
husbands. Such ladies are called `avidhav<193>s' or `non-widows.' ç
The·r<193>ddha or obsequial rite for such women is performed on the ç
ninth day during the dark half of the month Bh<193>drapada (corresponding ç
roughly to September) by their sons or younger male relatives. One ç
of the specialities of this rite is that not only a br<193>hma<207>a ç
but also married ladies whose husbands are alive, are invited, fed ç
and given presents. The rite generally ceases to be performed when ç
their husbands die.
@NT = avidy<193>
@N1 = (`non-knowledge')
@EMERGENCY = How Brahman, `the One without a second,' the only Reality, ç
appears as this phenomenal universe, is a question that has baffled ç
the Indian philosophers who have accepted the final authority of the ç
·ruti or the Vedas, for ages. <185>a<209>kara (<F51320P10MSC1>A.D.<W1> ç
<F255P255DC255>788-820) posits avidy<193>, aj<210><193>na or m<193>y<193> ç
as the factor responsible for this. (See <MS>AJ<178>°NA<D> for details.) ç
Later Advaitins have tried to present m<193>y<193> as the cause and ç
avidy<193> or aj<210><193>na as its effect. The latter words have ç
been variously rendered as `nescience,' `ignorance,' `non-knowledge' ç
or even `anti-knowledge.' In the final analysis it defies all definition.
The word `avidy<193>' has been used by Pata<210>jali (200 <F51320P10MSC1>B. ç
C.<F255P255DC255>) in his Yogas<220>tras (2.3-5). He considers it as ç
one of the five `kle·as' or afflictions, but as the ground for the ç
origin of the others. He defines it as that which makes us feel that ç
the transient is eternal, the impure is pure, misery is happiness ç
and the non-self is the Self. It can be eliminated only by `viveka-khy<193>ti' ç
the knowledge that we as the Self (which is pure consciousness) are ç
entirely separate and different from prak<216>ti or insentient nature.
@NT = avik<216>ta-pari<207><193>ma-v<193>da
@N1 = (`doctrine of<R>ç
unchanged transformation')
Among the post-<185>a<209>kara schools of Ved<193>nta, the <185>uddh<193>dvaita ç
(also known as `Pu<218><219>im<193>rga') of Vallabha (<F51320P10MSC1>A. ç
D.<F255P255DC255> 1473-1531) is an important one. This school based equally ç
on the authority of the Bhagavadg<200>t<193> and the Bh<193>gavata ç
as also on the Vedas and the Brahmas<220>tras, posits Brahman as ç
personal. He creates this world in `l<200>l<193>' or sport out of ç
himself. But though this world is a `pari<207><193>ma' or a transformation ç
of his, he continues to remain `avik<216>ta' or unchanged, since the ç
entire process is only a l<200>l<193>. This doctrine is therefore ç
called `avik<216>ta-pari<207><193>ma-v<193>da.'
See also <MS>PU<186><187>IM°RGA, <185>UDDH°DVAITA<D> and <MS>VALLABH°C°RYA<D>.
@NT = avirati
@N1 = (`absence of renunciation')
Pata<210>jali (200 <F51320P10MSC1>B. C.<F255P255DC255>) the great teacher of ç
yoga, lists nine serious obstacles to the attainment of yoga (vide ç
Yogas<220>tras 1.30) of which `avirati' or absence of the spirit ç
of renunciation is one. Yoga is `citta-v<216>tti-nirodha' or suppressing ç
the modifications of the mind. These modifications continue to rise ç
as long as their causes like k<193>ma or desire for the pleasures ç
of the senses exist. K<193>ma has to be controlled by `virati' or ç
dispassion or an intense spirit of renunciation. If this virati is ç
absent, then, that state is called `avirati' which is a serious obstacle ç
to yoga.
@NT = <193>v<200>ta
See <MS>PR°C®N°V®TA<D>.
@NT = Aviyoga-vrata
@N1 = (`religious vow for<R>ç
non-separation')
Hinduism considers the ties of marriage to be sacred and inviolable. ç
A married Hindu woman shudders at the least prospect of separation ç
from her husband.  `Aviyoga-vrata'  (also  called `Aviyoga-t<216>t<200>y<193>') ç
is a religious vow specially prescribed for a married woman and is ç
supposed to bring about non-separation from her husband. It begins ç
on the 3rd day of the bright half of M<193>rga·ira (November-December) ç
and continues for one year. The women who undertake this vrata start ç
it on this day by partaking rice boiled in milk and sugar. They worship ç
Gaur<200> (P<193>rvat<200>) and <185>ambhu (<185>iva) in images made ç
of rice flour, under different names (in each of the twelve months) ç
with different flowers.
See also <MS>VRATAS<D>.
@NT = Avvaiy<193>r
Tamil is one of the oldest languages of the world with a rich ancient ç
literature. Avvaiy<193>r (also spelt as `Auvaiy<193>r') is one outstanding ç
poetess of the ancient period who is almost as well-known as the other, ç
the most well-known of all, Tiruva<202><202>uvar.
Not  much  is  known  about  her. According to popular stories she ç
was one of the seven children of °di, a lowcaste woman, and Bhagav<193>n, ç
a br<193>hma<207>a.
Scholars who have studied the poems attributed to Avvaiy<193>r have ç
come to the conclusion that there were two or perhaps more poetesses ç
of the same name living in different periods of history. The first ç
belonged to the Sa<209>gam period (2nd cent. <MS>A.D.<D>). King °diyam<193>n ç
had given her a high and honoured place. About 59 poems of this period ç
are available now. Apart from literary grace, these poems stress that ç
it is the character of the people that makes a country great.<F51320P10W1C1>
The second Avvaiy<193>r, a contemporary of the <185>aiva saint Sundaram<220>rti, ç
might have lived in the last part of the 8th cent. <MS>A. D.<D> The ç
third was a contemporary of the famous Kamban (12th cent. <MS>A. D.<D>).<F51320P10W1C1>
Poems of these Avvaiy<193>rs extol the greatness of the householder's ç
life, of agri- culture, and of acquiring knowledge. For a human being, ç
that m<193>na or honour is the most important acquisition, is also ç
stressed.
Ethical works attributed to Avvaiy<193>r, apart from the songs, are: ç
M<220>durai, Atticc<220><195>i, Nalva<202>i and Kosaraivendan.
@SPACE1 = 
@NT = avyakta
@N1 = (`the unmanifest')
@SPACE1 = 
The S<193><209>khya system, one of the six systems of Indian philosophy, ç
posits two fundamental principles of creation: prak<216>ti (also called ç
`pradh<193>na') and puru<218>a. Prak<216>ti is the primeval insentient ç
material cause; and puru<218>as, of infinite number, are the conscious ç
entities or souls. The whole world is a creation that comes out of ç
the association of the puru<218>as with the various evolutes of prak<216>ti.
Prak<216>ti, which consists of the three gu<207>as†sattva, rajas and ç
tamas†is in a state of perfect internal balance and equilibrium. This ç
is its natural state before evolution into the world. Hence it is ç
also called `avyakta' or the unmanifest.
In Ved<193>nta, the term is sometimes used to indicate Brahman, the ç
Absolute.
See also <MS>PRADH°NA<D> and <MS>PRAK<184>TI<D>.
@NT = Avyakta Upani<218>ad
This is a minor upani<218>ad belonging to the S<193>maveda. It is ç
in prose and is spread over seven sections. It deals with the `Avyakta' ç
(the unmanifest) and the evolution of the manifested world from it.
Before creation, It alone existed, the light Divine, beyond all names, ç
forms and qualities. It split itself into two, one being green and ç
the other red in colour. The latter assumed a male form and the former ç
the female form called `m<193>y<193>.' By the union of these two was ç
produced the golden egg from which emerged Parame<218><219>hi or Praj<193>pati. ç
When he was pondering as to who he was and what was his duty, he heard ç
the divine voice of an invisible being. It told him that he had come ç
out of the Avyakta and that he had to create the vyakta (the manifest, ç
the world). For this he had to live a life of brahmacarya for a thousand ç
years. At the end of this period of austere living, parama-vidy<193> ç
or the highest knowledge was revealed to him in the form of <216>ks ç
in the anu<218><219>ubh metre. He sang these for a thousand years. ç
Then he saw the Lord in the form of N<216>si<221>ha (Man-lion). He ç
praised him through appropriate phrases. Being pleased with this, ç
Lord N<216>si<221>ha commanded him to create the world and taught ç
him a special meditation. By meditating that he was offering himself ç
into the Lord as the fire, he obtained all the knowledge and all the ç
powers needed for creation. Then, with the help of these <216>ks, ç
he created the three worlds, the gods including Indra, the eleven ç
Rudras, the eleven °dityas including Vi<218><207>u, the eight Vasus, ç
day and night, the four Vedas, the various metres, the four var<207>as ç
and all the beings of the world. The Upani<218>ad ends with a phala·ruti ç
or laudatory statements regarding the fruits one obtains if he knows ç
this vidy<193> or knowledge revealed here.
@NT = avya<209>ga
@N1 = (`that which is not incomplete or defective')
The images of S<220>rya, the Sun-god, have a waist band called abhya<209>ga ç
or avya<209>ga. According to the Bhavi<218>ya- pur<193><207>a, during ç
each of the six <216>tus or seasons, there came to S<220>rya one representative ç
from among the following by rotation: <216><218>is, devat<193>s, n<193>gas, ç
gandharvas, apsaras, yak<218>as and r<193>k<218>asas. In one of those ç
turns V<193>suki, the n<193>ga, presented S<220>rya with a cord called ç
`avya<209>ga' produced from his body.
This cord was composed of gold and was half red and half white. Iconographical ç
representations of S<220>rya are invariably shown with the avya<209>ga. ç
The followers of the S<220>rya cult wear a similar cord round their ç
waists.
@NT = ay<193>cita
@N1 = (`got unasked')
Fasting on ek<193>da·<200> days (the eleventh day in the fortnight ç
as per the lunar calendar) is an important religious discipline enjoined ç
on the dvijas (`the twice-born,' i. e., br<193>hma<207>as, k<218>attriyas ç
and vai·yas). It is of four types, of which `ay<193>cita' is one.
The word literally means `that which is got without asking.' A person ç
who is observing a fast of this type is permitted to eat food got ç
without asking. But even this can be accepted and eaten only once.
See <MS>EK°DA<185>®<D> and <MS>UPAV°SA<D>.
@NT = °y<193>di-<218>a<195>varga
@N1 = (`the group of six<R>ç
[formulae] starting with °ya')
M<193>nas<193>ra, the most authoritative text dealing with Hindu ç
architecture, iconography as also town-planning, gives us a set of ç
six formulae known as the `°y<193>di-<218>a<195>varga.' While dealing ç
with the length (1), breadth (b) and circumference or height or thickness ç
(c) of any structure, the book gives several alternatives, the right ç
dimension being chosen by the appli- cation<|>of<|>these six formulae. ç
These are<|><193>ya, vyaya, <216>k<218>a yoni, v<193>ra, tithi and ç
a<221>·a.
These names represent well-known groups of objects that always follow ç
a certain serial order. For instance, v<193>ra represents the group ç
of seven days of the week. <184>k<218>a represents the group of twenty-seven ç
nak<218>atras (star-groups).
Each one of these formulae has already been determined by the text ç
itself. The suitability of a dimension is checked by the remainder ç
left after the application of the concerned formulae. For example, ç
if the height of a proposed new building is to be determined from ç
among the several alternatives suggested by the work, the v<193>ra ç
formula (<|><P6W1><$Eroman {C~~x~~9} over 7><P255D><|>) is applied, ç
<MS>C<D> standing for theheight.
If the remainder is 4, it indicates the fourth day (Wednesday) of ç
the week, considered to be auspicious. Then the measurement chosen ç
is right.
@NT = <193>yamukha
@N1 = (`source of income')
Kau<219>ilya (300 <MS>B. C.<D>) the well-known author of Artha·<193>stra, ç
classifies the sources or items of revenue for the State as two: <193>ya·ar<200>ra ç
(body of income) and <193>yamukha (sources of income). The <193>ya·ar<200>ra ç
which refers to the centres of collection comprises durga (fortified ç
cities), r<193><218><219>ra (rural areas), khani (mines), setu (irrigation ç
works,) vana (forests), vraja (herds) and v<193>ripatha (river-borne ç
trade routes). The subdivisions of <193>yamukha are: bh<193>ga (royal ç
share), vy<193>ji (compensation), parigha (gate duty) kl<216>pta (fixed ç
tax), r<220>pika (premia on coins) and atyaya (money-fine).
See also <MS>ARTHA<185>°STRA<D> and <MS>KAU<187>ILYA<D>.
@NT = ayana
@N1 = (`course')
Though the word literally means `course' or `path,' it is generally ç
used to indicate the course of the sun to the north or the south of ç
the equator. The northward course is called `Uttar<193>ya<207>a' whereas ç
the southward course is named as `Dak<218>i- <207><193>yana.' The ç
former is the period of mid-winter to mid-summer and the latter, that ç
of mid-summer to mid-winter. According to the S<220>ryasiddh<193>nta ç
(14.5.9), a well- known authoritative work of astronomy, the period ç
of six months from the sun's entrance (called `sa<209>kr<193>nti') ç
into Capricorn (Makarar<193>·i) is called `Uttar<193>ya<207>a.' Similarly, ç
the period of six months from the sun's entrance into Cancer (Kark<193><219>aka-r<193>·i) ç
is called `Dak<218>i<207><193>yana.'
Hindu  religious  traditions  have always considered death during ç
Utta-r<193>ya<207>a as propitious. The Mah<193>bh<193>rata says ç
that the venerable Bh<200><218>ma waited till Uttar<193>ya<207>a to ç
give up the body.
The word `ayana' is also used to indicate the precession of the equinoxes. ç
According to the later astronomers like °ryabha<219><219>a II (<F51320P10MSC1>A. ç
D.<F255P255DC255> 1028) the equinoctial point oscillates about a mean ç
point. The amplitude of precessional oscillation is 27degrees and ç
the period of one complete oscillation is 7200 years. The rate of ç
precession is uniform and is 54 seconds per year. A sidereal year ç
that disregards this precession is called `nirayana' and, the tropical ç
year that takes it into account is called `s<193>yana.'
The total precession of the equinoxes since zero-precession year is ç
called `ayan<193><221>·a.' The ayan<193><221>·a at present is calculated ç
to be 22 degrees. During the next 350 years it will gradually increase ç
up to 27 degrees. It will then start decreasing to zero over the next ç
1800 years.
@SPACE = 
@NT = ayan<193><221>·a
@N1 = (`part of the ayana')
See <MS>AYANA<D>.
@SPACE = 
@NT = <193>ya·ar<200>ra
@N1 = (`body of income')
See <MS>°YAMUKHA<D>.
@SPACE = 
@NT = Ayodhy<193>
@N1 = (`invincible')
Ayodhy<193> is the first of the seven holy cities of ancient India ç
considered to be capable of giving mukti or liberation. It is also ç
famous because of its association with R<193>ma, the son of Da·aratha, ç
considered to be an incarnation of God.
Manu, the first traditional king of India, is said to have founded ç
the city of Ayodhy<193> as his capital. It was 12 yojan<193>s long ç
and 3 yojan<193>s broad. (1 yojan<193> = 15 kilometres.) The galaxy ç
of great rulers who ruled from here includes Ik<218>v<193>ku, M<193>ndh<193>t<193>, ç
Hari·candra, Bhag<200>ratha, Dil<200>pa and Raghu. The great <216><218>i ç
Vasi<218><219>ha and his family were the hereditary priests of the ç
royal families of Ayodhy<193>.
King Vikram<193>ditya of Vikram <185>aka fame is said to have raised ç
a temple at the birth-place of R<193>ma and also rebuilt the city.
The city of S<193>ketas, well-known during the time of Buddha, has ç
been identified with Ayodhy<193>.
Both Fa-Hien (<F51320P10MSC1>A. D.<F255P255DC255> 400) and Hiuen Tsang (<MS>A. ç
D.<D> 596)†the famous Chinese travellers†visited Ayodhy<193> and have ç
left interesting accounts of the same. During their visits they found ç
it to be a flourishing city with several Buddhist monasteries.<F51320P10W1C1>
Ayodhy<193> has been considered as a sacred place by the Jains also. ç
Several T<200>rtha<209>karas had lived here.
The modern town of Ayodhy<193>, on the bank of the river Saray<220> ç
(also called Ghogr<193>), is about 130 kms. from Lucknow and 190 kms. ç
from V<193>r<193><207>as<200>. It is in the Faizabad district of Uttar ç
Pradesh. Apart from the spot said to be the birth-place of R<193>ma, ç
the other places of interest for the tourists and the pilgrims are: ç
Lak<218>man Gh<193><219>, Svarga Dv<193>r, Hanum<193>n Garh<200>, ç
Kanak Bhavan and Tulas<200> Cowr<193>.
@NT = Ayodhy<193>-k<193><207><195>a
This is the second book of the famous epic R<193>m<193>ya<207>a ç
of V<193>lm<200>ki.
See <MS>R°M°YAØA<D> for details.
@NT = <193>yudha
@N1 = (`that by which one fights')
An <193>yudha is a weapon or an imple- ment by which one fights. Several ç
weapons have been known to have existed in ancient India. They are ç
generally classified into three groups: (1) prahara<207>a (those by ç
which one strikes the enemy, like a kha<195>ga or sword); (2) p<193><207>imukta ç
(those that are discharged or thrown from the hand, like a cakra or ç
discus); (3)yantramukta (those released from a mechanical contrivance, ç
like a ·ara or arrow).
The images of gods and goddesses invariably carry <193>yudhas to signify ç
their role in their fight against the forces of evil and sin. Hindu ç
mythological lore is full of legends of the fights of the deities ç
against the demons. The liberal provision of arms to the iconographical ç
representations of the various deities is often to provide scope for ç
carrying the various weapons, implements and emblems.
Certain weapons are invariably associated with certain deities like ç
the cakra (discus) with Vi<218><207>u, tri·<220>la (trident) with ç
<185>iva, dhanu<218> (bow) with R<193>ma, ·<220>la (spear) with Durg<193> ç
and so on. Consequently, these help us in identifying the particular ç
deity represented by these icons.
Very often, these <193>yudhas are represented with a human form, with ç
the parti- cular weapon shown either in the background behind the ç
head or over the head or in its hands. Such forms are called `<193>yudha-puru<218>as' ç
or personified weapons. The sex of this deity is dependent on the ç
gender of the Sanskrit word for that weapon. For instance, gad<193> ç
(mace) is a female deity whereas cakra (discus) is a eunuch. <185><220>la ç
(spear), a<209>ku·a (goad) and vajra (thunderbolt) are male deities. ç
These deities are generally shown with one face and two hands, held ç
in an attitude of adoration. They wear kara<207><195>a-muku<219>a ç
(bowl-shaped crown).
@NT = °yudha-puru<218>a
@N1 = (`personified weapon')
See <MS>°YUDHA<D>.
@NT = °yurveda
@N1 = (`Science of life')
@EMERGENCY = The Vedic °ryans believed in a vigorous life, a life ç
of health, strength and vitality. They paid as much attention to the ç
culture of the body and the arts of war as to the science of the mind ç
and the spirit. This gradually resulted in the `°yurveda' or the `science ç
of life,' the elements of which have been found even in the <184>gveda. ç
However it is in the Atharvaveda that a more detailed†and to some ç
extent, systematic†treatment of the subject, is found.
@EMERGENCY = Though the word `°yurveda' appears to limit its scope ç
to purely physical health alone, it is not so. Its approach to the ç
science of health is holistic and includes not only the physical but ç
also the mental and spiritual aspects of health in the context of ç
man's interaction with his environment. While doing so, it deals with ç
several subjects which may be categorized briefly as follows: philosophical ç
speculations about matter and life as also general ethics; biological ç
theories which include embryology and genetics; physiology and pathology; ç
food, nutrition and diet, general rules of health and longevity, diagnosis ç
and treatment of diseases; poisons and their antidotes.
As in the case of other ancient Hindu sciences, the origins of °yurveda ç
also are buried in the bosom of hoary myth and tradition. Starting ç
with Bramh<193> the Creator himself, this science was handed down ç
first to the A·vins, the twin deities and then to Indra. Then it is ç
said to have branched off into two streams, of medicine and surgery. ç
Bharadv<193>ja, °treya Punarvasu and the sixdisciples of the latter ç
like Agnive·a andK<218><200>rap<193><207>i established the science ç
of medicine whereas Su·ruta established the science of surgery. Modern ç
scholars are inclined to believe that Dhanvantari and Divod<193>sa ç
(the king of K<193>·i), the other two well-known names, actually represent ç
the same person Bharadv<193>ja; and that °treya and Su·ruta are identical. ç
They also hold that Caraka and Su·ruta are the historical personages ç
who organized the two bodies of know-ledge, medicine and surgery. ç
They probably lived in the pre-Christian era and the redaction of ç
their texts were done in the early part of post-Christian era.
Classical  texts  of  the  °yurveda, especially those of Caraka and ç
Su·ruta, contain certain metaphysical speculations about matter and ç
life. They generally follow the S<193><209>khya-Ved<193>nta view of ç
cosmo-gony and the allied Vai·e<218>ika view of inherent nature of ç
substances. All material substances are evolved from the interaction ç
of prak<216>ti (the dynamic principle comprising the three gu<207>as, ç
sattva, rajas and tamas) and puru<218>a (the static and conscious ç
principle). The material bodies of human beings are composed of kal<193> ç
(protective   layer),   dh<193>tu   (component matter), mala (eliminations), ç
three do<218>as (humours), agni (digestive fire) and kriy<193> (movement ç
or activity). These components, as also the pa<210>ca-mah<193>-bh<220>tas ç
(five gross elements) impart their specific nature and properties ç
to the individual in proportion to their presence.
Most of the standard texts of the °yurveda deal with the subject under ç
eight topical headings†hence the appellation `A<218><219><193><209>ga'†as ç
follows:
K<193>yacikits<193> (therapeutics), <185>alya- tantra (major surgery), ç
<185><193>l<193>kya-tantra (minor-surgery including the E.N.T.), Bh<220>tavidy<193> ç
(psychiatry), Kaum<193>ra-bh<216>tya-tantra (paediatrics), Agada-tantra ç
(toxico-logy), Ras<193>yanatantra (geriatrics) and V<193>j<200>kara<207>atantra ç
(virilification).
K<193>yacikits<193> relates to the treatment of diseases affecting ç
the whole body. The diseases are said to be the result of the imbalance ç
of the three do<218>as or humours. An excess of v<193>ta or wind can ç
lead to nearly 80 diseases. The treatment of such diseases involves ç
the liberal use of medicated oils. A surfeit of pitta or bile can ç
cause as many as 40 diseases affecting blood or eyes or skin. The ç
treatment is generally centred round purgatory pro-cesses and medicines. ç
A profusion of ·le<218>ma (phlegm) can produce 20 kinds of illnesses ç
affecting the throat, the digestive and the excretory organs. Administration ç
of certain astringent substances to make the patient vomit is an important ç
course of treatment adopted in curing this defect.
<185>alya-tantra deals with the methods of removal of arrows (·alya=arrow) ç
and other foreign bodies, obstetrics and treatment of injuries and ç
diseases requiring major surgery. The Su·ruta Sa<221>hit<193> which ç
is a great classic in surgery, gives an amazing amount of information ç
regarding the use of about 100 surgical instruments, alkalis, bandages, ç
pre-operative preparations and post-operative care including nursing. ç
Plastic surgery too was known to the surgeons.
<185><193>l<193>kya-tantra is concerned with the treatment of the ç
diseases of the body above the clavicle (E.N.T.) using thin bars, ç
small sticks and probes as instruments.
Bh<220>tavidy<193> treats of mental derangements and disturbances ç
believed to have been caused by malevolent spirits. Apart from prayers ç
and exorcism, administration of certain drugs is also mentioned. Mention ç
is also made of Pa<210>cakarmas or five purificatory processes which ç
will help relieve the mental illnesses. Analysis of dreams of the ç
patients in order to findout the root causes has also been attempted.
Kaum<193>rabh<216>tya-tantra deals specially with obstetrics, female ç
diseases connected with  child-birth  and  the  diseases  of children, ç
many of which were considered to have been caused by demons. Attention ç
has been paid to the bringing up of children from the standpoint of ç
health.
Agada-tantra discusses the methods of diagnosis and treatment of the ç
bites of poisonous snakes, scorpions or insects and of other poison ç
cases. A very large number of poisons have been mentioned with appropriate ç
remedies including mantras that eliminate or destroy the poisons.
Ras<193>yana-tantra  deals  with  the methods of preservation and ç
increase of vigour, restoration of youth, improvement of memory and ç
prevention of diseases. The medicines are prepared out of mercury ç
and precious stones apart from certain other materials.
V<193>j<200>kara<207>a-tantra concerns the means of increasing virile ç
powers as also prevention and cure of venereal diseases. The standard ç
works generally extol brahmacarya (continence) as the best means.
The techniques of diagnosis of diseases had been fairly well-developed. ç
Apart from his own observations and inferences, the physician also ç
depended upon the instructions of the wise. Other factors which helped ç
in the diagnostic process were: the normal constitution of the patient, ç
time and season of the first appearance of the disease, things giving ç
comfort or relief to the patient, things that cause aggravation of ç
the disease, nature of digestion and appetite, the way the organs ç
of evacuation are functioning, and, whether the disease is in an advanced ç
stage or not.
During the medieval period, `n<193><195><200>-vij<210><193>na' (the ç
science of pulse) came to be a major means of diagnosing the condition ç
of the three do<218>as.
Treatment of diseases, according to the °yurveda, depends upon four ç
factors: physician, patient, medicines and attendant nurse. Factors ç
governing the treatment are puru<218>a (patient), vy<193>dhi (dis- ç
ease), o<218>adhi (medicine), kriy<193> (processes) and k<193>la (seasonal ç
and climatic factors). °h<193>ra (diet) and <193>c<193>ra (right conduct ç
and medical regimen) were also considered important. Sa<221>·amana ç
(sedation) and sa<221>·odhana (purgatory processes) were often resorted ç
to.
Texts of °yurveda lay down a strict code of conduct for the physician. ç
He should treat the patients to the best of his ability since they ç
trust him for their lives. He should refuse to treat morally depraved ç
persons who are a scourge to the society. He should also refuse to ç
take up terminal cases where he is sure that death is imminent. Nor ç
should he undertake the responsibility of patients suffering from ç
incurable diseases. Once he accepts a patient, he should provide him ç
with proper medical and nursing facilities. He should never attend ç
to a woman patient in the absence of her husband or guardian. All ç
professional information should be kept strictly confidential. He ç
must have compassion on his patients, look upon them as his own children; ç
but, adopt a philosophical outlook in respect of cases proving fatal.
°yurvedic theories and practices werealso applied to animal and plant ç
life. There are voluminous medical treatises on plant life (V<216>ks<193>yurveda), ç
bovine species (Gav<193>yurveda), horses (A·v<193>yurveda) and elephants ç
(Hasty<193>yurveda).
A new type of °yurvedic treatment, `rasacikits<193>,' which incorporated ç
iatro- chemistry or metallic compounds came into vogue around <F51320P10MSC1>A.D.<F255P255DC255> ç
1300. Opium and certain other foreign drugs as also mineral acids ç
and tinctures were incorporated into °yurvedic pharmacology in about ç
<MS>A.D.<D> 1500.<F51320P10W1C1>
There is evidence to believe that °yurveda had influenced the medical ç
works of Greece. Translations of several well-known °yurvedic texts ç
into Arabic prove the spread of the science in the Arab countries. ç
Evidence is also not wanting to prove its dispersal in Central and ç
South East Asian countries.
See also <MS>CARAKA<D> and <MS>SU<185>RUTA<D>.
@NT = <193>yu<218>ya
@N1 = (`promoting long life')
When a child is born, a religious sacrament called `j<193>takarma' ç
is performed. °yu<218>ya is the second of the rites involved in this. ç
It consists in the father muttering over the navel or in the right ç
ear of thechild, certain mantras invoking the bestowal of long life. ç
These mantras, beginning with `agne <193>yurasi,' are taken from the ç
K<193><219>haka Sa<221>hit<193> (11.7.66) wherein the word `<193>yu<218>mat' ç
is repeated several times.
See also <MS>J°TAKARMA<D>.
@NT = ayuta-siddha
@N1 = (`existing without<R>ç
conjunction')
The  Ny<193>ya-Vai·e<218>ika  philosophy recognizes two kinds of relations: ç
sa<221>yoga or conjunction and samav<193>ya or inherence. Conjunction ç
is a temporary phenomenon which will come into existence when two ç
things†like two balls moving from opposite directions†meet. Since ç
it comes into existence (siddha) when the two are united (yuta), it ç
is called `yutasiddha.'
However, in the case of samav<193>ya, as distinct from sa<221>yoga, ç
the relationship is permanent since one inheres in the other. For ç
instance, the whole inheres in the parts (as cloth in its threads), ç
a quality or an action inheres in a substance (as redness in the rose, ç
motion in the moving ball) or the universal inheres in the individuals ç
(as manhood in men). Here, the two (e.g., cloth and threads or redness ç
and rose) are related without conjunction. This relation exists ç
(siddha) eventhough there is no conjunction (ayuta) between the entities. ç
Hence it is called `ayuta- siddha.'
Samav<193>ya is a relationship of the `ayutasiddha' type.
See also <MS>SAMAV°YA<D>.
@NT = Ayyappan
See <MS><185>°ST°.
@END = 
