@H = I
@NT = icch<193>·akti
@N1 = (`power of will')
According to the Ved<193>nta philosophy, Hira<207>yagarbha is the ç
second aspect of Brahman, the Absolute. He is pure consciousness associated ç
with aj<210><193>na or nescience, and comes after ®·vara in the process ç
of creation. He is endowed with three powers of icch<193> or will, ç
j<210><193>na or knowledge, and kriy<193> or action. These three powers ç
are respectively known as icch<193>·akti, j<210><193>na·akti, and ç
kriy<193>·akti. By icch<193>·akti he controls the animate and inanimate ç
aspects of creation.
Accordingtothe<185>aivasiddh<193>nta (<185>aivism as developed ç
in Tamil Nadu) these three ·aktis evolve out of the union of Para·iva ç
and Par<193>·akti. They are, respectively, pure j<210><193>na (knowledge) ç
and pure kriy<193> (activity).
@SPACE1 = 
Icch<193>·akti is a combination of j<210><193>na and kriy<193> in ç
equal proportion. Kriy<193>·akti is a combination in which kriy<193> ç
is in excess of j<210><193>na. J<210><193>na·akti is a combination ç
in which j<210><193>na is in excess of kriy<193>.
@NT = Iconography
See <MS>M<188>RTI<185>ILPA<185>°STRA.<D>
@NT = i<195><193>
N<193><195><200>s are passages in the body that carry the pr<193><207>ic ç
energy. According to the works on Ha<219>hayoga, there are 3,50,000 ç
of them in the human body. Of these, fourteen are considered as the ç
principal ones, out of which again, three are most important. They ç
are i<195><193>, pi<209>gal<193> and su<218>umn<193>.
The i<195><193> starts from the left nostril and runs up to the m<220>l<193>dh<193>ra-cakra, ç
at the base of the spine. It is also called `candra or moon'.
It has an important role to play in pr<193><207><193>y<193>ma.
See also <MS>PI<177>GAL°, PR°Ø°Y°MA<D> and <MS>SU<186>UMN°<D>.
The <184>gvedic goddess I<202><193> is also spelt as `I<195><193>'. ç
See <MS>I<170>°<D> for details.
In Vedic sacrifices, i<195><193> is the portion cut up from an oblatory ç
material, sprinkled with <193>jya (ghee) and consumed by all the participants ç
together.
@SPACE = 
@NT = idhma
@N1 = (`that which is lighted')
@SPACE = 
In Vedic sacrifices sticks of wood, of certain trees and plants, are ç
used as fuel. They are called `idhma'. Usually the pal<193>·a (Butea ç
frondosa) and the khadira (Acacia cateclu) wood is used. The number ç
of sticksused is 21, out of which 15 are put into the fire with the ç
S<193>midhen<200> verses (eleven verses from the <184>gveda recited ç
by the hot<193> priest; for e.g., <184>gveda 3.27.1, 6.16.10-12 ç
and so on) which are normally chanted while kindling the fire. The ç
other sticks are used for lining the border and for other purposes.
@SPACE = 
@NT = Idhmav<193>ha
@N1 = (`one who carries sacrificial faggots')
@SPACE = 
The sage D<216><195>hasyu or D<216><195>h<193>sya, the son of Agastya ç
and Lop<193>mudr<193>, was physically so strong that he could transport ç
sacrificial faggots normally carried by a thousand persons! Hence, ç
he got this title from his father.
He was an expert in the Vedic lore and also very austere in his personal ç
life. He was adopted as a son by another great sage Kratu.
@NT = idols
Hinduism is not idolatry. An idol is an external symbol that brings ç
to the mind the living presence of the deity it represents, even as ç
the photograph of a person does.
The idol of a deity is prepared as per the directions given in the ç
dhy<193>na·loka (hymn of meditation) of the deity as revealed in the ç
depths of mystical meditation, to the sages.
Again, when an idol is consecrated by the process of pr<193><207>aprati<218><219>h<193> ç
(infilling with life) it becomes `alive' as it were, by the subtle ç
presence of that deity. It can then be worshipped. It is something ç
like connecting an electric bulb with the source of electricity and ç
putting the switch on.
In all such matters, the scriptures are the final authority.
See also <MS>M<188>RTI<185>ILPA<185>°STRA.<D>
@NT = ignorance
See <MS>AJ<178>°NA<D> and <MS>AVIDY°.<D>
@NT = Ik<218>v<193>ku
Ik<218>v<193>ku was the son of Vaivasvata Manu and the founder of ç
the dynasty of kings that ruled from Ayodhy<193>. <185>r<200> R<193>ma ç
belonged to this dynasty.
Ik<218>v<193>ku had a hundred sons and a daughter named Suvar<207><193>. ç
Among the sons, Nimi started his own dynasty called `Videha' at Mithil<193>. ç
He was the ancestor of Janaka-S<200>radhvaja, the father of S<200>t<193>, ç
of the R<193>m<193>ya<207>a fame.
Ik<218>v<193>ku was also the name of a br<193>hma<207>a. Though he ç
was well-versed in the scriptures, he did not care to teach others ç
but led a glutton's life. He was ultimately saved by the grace of ç
a sage J<193>b<193>li.
@NT = I<202><193>
The <184>gveda (1.13.9) mentions I<202><193> along with Sarasvat<200> ç
and Mah<200>†as a goddess of light and brilliance. She is the goddess ç
of the earth. In another place (1.31.11) she is declared as the daughter ç
of Manu and the teacher of men. Her place is the centre of the earth. ç
On the sacrificial altar, the place sanctified by her feet, is used ç
for keeping the fire of the sacrifice.
In the pur<193><207>as and the Mah<193>bh<193>rata, she is pictured ç
as the daughter of Manu. Due to several reasons like entering a forbidden ç
place or the efforts of the sages like Vasi<218><219>ha she undergoes ç
change of sex, becoming the prince Sudyumna or the wife of Budha (and ç
mother of Pur<220>ravas) and so on. She used to undergo change of ç
sex once a month!
See also <MS>I£°<D>.
@NT = illusion
See <MS>ADHY°SA, BHRAMA<D> and <MS>M°Y°.<D>
@NT = Ilvala
One of the exploits of the great sage Agastya was his destroying the ç
demons Ilvala and V<193>t<193>pi. They were the sons of the demoness ç
Si<221>hik<193>.
Once Ilvala approached a br<193>hma<207>a sage with the request that ç
he be blessed with a son equal to Indra. The sage rejected it. Since ç
then Ilvala started hating and killing the br<193>hma<207>as, with ç
the help of his younger brother V<193>t<193>pi.
The strategy adopted by Ilvala was to convert V<193>t<193>pi by his ç
magical powers, into a goat, cut it and prepare a meal out of it and ç
then serve it to a br<193>hma<207>a specially invited for dinner. ç
After the dinner he would call V<193>t<193>pi to come out. And, V<193>t<193>pi ç
would emerge in his original form tearing thebr<193>hma<207>a apart, ç
in the process. The brothers had thus killed many br<193>hma<207>as.
When Ilvala tried the same trick on the sage Agastya, he quietly uttered ç
the words, `v<193>t<193>pi j<200>r<207>o bhava' (`O V<193>t<193>pi, ç
get digested!') and the demon was destroyed. Ilvala too was burnt ç
to ashes by Agastya's fierce look.
See also <MS>AGASTYA.<D>
@NT = image worship
See <MS>IDOLS.<D>
@NT = immortality
See <MS>AM<184>TATVA.<D>
@NT = immortals
See <MS>CIRAJ®VINS.<D>
@NT = incarnation
See <MS>AVAT°RA.<D>
@NT = Indian Philosophy
See <MS>DAR<185>ANAS<D> and <MS><186>A£DAR<185>ANAS.
@SPACE = 
@NT = Indra
@N1 = (`one who has great wealth')
@SPACE = 
Indra, the king of the gods in heaven †hence known as Devar<193>ja ç
or Devendra also†is a familiar figure met with in Hindu Mythology.
He is undoubtedly the chief deity of the <184>gveda. Almost a quarter ç
of its hymns, is devoted to praising him. He is the most important ç
deity in the sky. Armed with the thunderbolt (Vajr<193>yudha) and ç
riding in a chariot whose speed exceeds that of the mind, he travels ç
everywhere.
His  valour is  awe-inspiring. His exploits are many. He killed ç
the demon V<216>tra and released the waters imprisoned by him. He ç
clipped the wings of the mighty mountains and made them behave. He ç
recovered the cows of the gods that had been abducted by the demons. ç
He is fond of soma-drink. Being a war-lord, he became a symbol of ç
the royal power. Hence warriors worshipped him before going to the ç
battlefield.
Indra has often been equated with the Supreme God. His love and affection ç
for his devotees has been eulogized. Scholars  opine  that  Indra  may  just ç
represent the natural phenomenon of rain being released from the dark ç
clouds as a result of being `bombarded by lightning and thunder!'
Indra's prestige gradually declined and he was relegated to a secondary ç
place by the pur<193><207>as, retaining however, his place as the ç
king of gods.
In some of the temple sculptures, Indra is depicted in a human form ç
with four arms, riding the celestial elephant Air<193>vata.
In the pur<193><207>as he appears in many roles. For instance:
By his boon Kunt<200> conceived and gave birth to Arjuna, the P<193><207><195>ava ç
hero.
He sent his chariot and its driver M<193>tali, to <185>r<200> R<193>ma ç
when he began his final battle with R<193>va<207>a.
He killed Vi·var<220>pa, a sage, and thus incurred the sin of brahmahaty<193>.
By killing V<216>tra, a great devotee of Vi<218><207>u, he incurred ç
brahmahaty<193> once again.
He  was  deposed  by  the  asuras because of the curse of the sage ç
Durv<193>sas whom he had humiliated.
He was cursed by the sage Gautama because  of  his  affair  with  Ahaly<193>, ç
Gautama's wife. She was redeemed by <185>r<200>R<193>ma later.
@SPACE1 = 
Indra is described as a dikp<193>la, the lord of the eastern direction. ç
He is also associated with rain and thunder.
Actually, Indra is more the title of a ruler in the cosmic scheme, ç
than an individual. Fourteen Indras†like Yaj<210>a, Rocana, Satyajit ç
and others†have been named in the scriptural works like the Mah<193>bh<193>rata. ç
Purandara, the seventh, is supposed to be ruling in heaven now.
Any one who successfully performs one hundred A·vamedha sacrifices ç
in one life, is said to gain the position of Indra.
@NT = Indradhvaja
@N1 = (`flagpost of Indra')
When  the  asuras  (non-gods  or demons) were winning the battles ç
against the devas (gods) most of the time, the worried gods approached ç
Brahm<193>, the Father of the universe. He took them to Vi<218><207>u ç
and apprised him of the problem. Vi<218><207>u gave Indra, the king ç
of the gods, a dhvaja or a flag and advised him to fight the asuras, ç
keeping this in front. Indra then succeeded in routing the asuras. ç
Since then, it became known as `Indradhvaja'.
Pur<193><207>as give descriptions of the Indradhvaja and also the ç
method of preparing it with certain kinds of wood as the post.
Kings used to prepare an Indradhvaja and fly it in their kingdoms ç
to please Indra and get rain.
If anyone dreamt that the Indra-dhvaja broke down, it was considered ç
as foreboding evil for the kingdom.
Indradhvaja-p<220>j<193> (`festivalofthe banner of Indra') was an ç
ancient festival. As a part of it, perhaps, there was also a sacrifice. ç
The whole festival was a celebration of the victory of the gods, under ç
the leadership of Indra, over the demons.
The festival used to be celebrated inGujarat at least till the 12th ç
century <MS>A.<|>D<D>. It used to be held on °·vina ·ukla a<218><219>am<200> ç
(8th day of the bright half of the month of °·vina†September/October) ç
and continued upto p<220>r<207>im<193> (full-moon day). Its celebration ç
was believed to ensure a good harvest.
@NT = Indradyumna
@N1 = (`One [whose] wealth and power [are like those of] Indra')
One of the oft-quoted incidents from the pur<193><207>as in support ç
of <193>rtabhakti (`devotion of the distressed') and the immediate ç
response it draws from God is that of Gajendra, the elephant king ç
(vide Bh<193>gavata 8.2-4).
Gajendra was actually a king, Indra-dyumna by name, in his previous ç
birth. He was the king of P<193><207><195>yade·a. Once he incurred ç
the displeasure of the great sage Agastya and was cursed by him to ç
be born as an elephant.
While roaming in a forest along with his herd, the elephant Gajendra ç
went to a lake to drink water but was caught by a crocodile. After ç
exhausting all his might in his struggle to free himself, he helplessly ç
turned towards Lord Vi<218><207>u and prayed piteously. Moved by his ç
prayer, Lord Vi<218><207>u arrived on the scene, discharged his famous ç
discus (Sudar·ana), killed the crocodile and saved Gajendra's life.
This story teaches two lessons: The evil effects of dishonouring saints ç
and the power of intense devotion to god.
There is another Indradyumna who was a king of Avant<200> (or O<207><195>ra) ç
and was a great devotee of Lord Vi<218><207>u. It was he who established ç
the Puru<218>ottama K<218>etra (present Pur<200> or Jagann<193>thapur<200> ç
town), a very holy place of pilgrimage.
@NT = Indraj<193>la
@N1 = (`the snare or net of Indra')
Listed among the 64 kal<193>s or sciences and arts, Indraj<193>la ç
represents the special art of producing illusions, especially in a ç
battle field, to confuse and frighten the enemy. The illusions could ç
be in the form of pictures of their future defeats or the appearance ç
of immense storm-clouds.
Indra, the king of gods, as also some asuras (r<193>k<218>asas or ç
demons) were experts in this art.
The word `indra' is also interpreted as `dexterity' and not the king ç
of gods.
@NT = Indrajit
@N1 = (`One who had conquered Indra')
Indrajit  was the most  formidable enemy in R<193>va<207>a's army ç
encountered by R<193>ma and Lak<218>ma<207>a. He was the son of R<193>va<207>a ç
from his chief queen Ma<207><195>odar<200>. As soon as he was born ç
he thundered like the rain-clouds. Hence he was given the name `Meghan<193>da' ç
(`one who roared like the rain clouds').
His exploits were many. He once fought with Indra, the king of gods, ç
and defeated him. Thus he got the appellation `Indrajit' (`one who ç
had conquered Indra'). When Hanum<193>n was causing a havoc in the ç
A·oka grove after meeting S<200>t<193>, Indrajit captured him using ç
the ultimate weapon, the Brahm<193>stra.
In the war with R<193>ma's army, he once made R<193>ma and Lak<218>ma<207>a ç
swoon with his N<193>gap<193>·a (serpent-weapon). They were later ç
rescued by Garu<195>a (the eagle-mount of Vi<218><207>u).
Another magical device he used, to cheat the enemy, was creating a ç
false S<200>t<193> and beheading her before the enemy's army. He was ç
finally killed by Lak<218>ma<207>a who, with the help of the army ç
of the monkeys, first destroyed the Nikumbhil<193> sacrifice being ç
performed by him and then used the Aindr<193>stra.
According to the Adhy<193>tma R<193>m<193>ya<207>a (Yuddhak<193><207><195>a, ç
9), Indrajit had obtained a boon from Brahm<193> that only he who ç
had observed strict celibacy for twelve years could kill him. And, ç
Lak<218>ma<207>a had fulfilled this condition.
See also <MS>R°M°YAØA.<D>
@NT = Indr<193>k<218><200>
@N1 = (`One whose eyes resemble those of Indra')
Indr<193>k<218><200> is one of the several forms of the Dev<200> (<185>akti ç
or P<193>rvat<200>) often resorted to by the votaries to get rid of ç
diseases like fever, tuberculosis, epilepsy and so on.
According to some works like the <185>r<200>tattvanidhi, Indr<193>k<218><200> ç
has two arms, carrying the vajra (thunderbolt) in her left hand and ç
showing the gesture of bestowal of boons (varada mudr<193>) in the ç
right hand. Her body is red in colour whereas her garments are yellow. ç
She is well-bedecked with various ornaments. Her face is calm and ç
beautiful. She is surrounded by celestial damsels.
There is a well-known hymn called Indr<193>k<218><200>stotra attributed ç
to Indra, the king of gods. It is said to be a part of the M<193>rka<207><195>eya ç
Pur<193><207>a. Almost all the names mentioned here are those of ç
P<193>rvat<200> in her different aspects.
@NT = Indr<193><207><200>
@N1 = (`the spouse of Indra')
Most of the deities of the Hindu pantheon have their female counterparts ç
or spouses (called <185>akti). Indra's ·akti is Indr<193><207><200>. ç
Even the <184>gveda (1.22.12) mentions her as the wife of Indra. ç
In later literature she is known as <185>ac<200>dev<200>. She was ç
the daughter of Puloma, an asura who was the son of Ka·yapa and Diti.
In iconographical works she is shown with Indra, standing on his left. ç
She holds a blue lotus in her left hand and her right hand is embracing ç
Indra. Her features are beautiful and she is bedecked with many ornaments.
She is sometimes shown as Aindr<200>, one of the seven m<193>t<216>k<193>s ç
(Saptam<193>t<216>k<193>s, `Seven Little Mothers'). In this form, ç
she may have either six or four hands. The vajra (thunderbolt) invariably ç
forms one of the things held in the hands, the others being lotus, ç
rosary, water vessel and so on.
Indr<193><207><200> can be worshipped indepen-dently also as the bestower ç
of prosperity. In this aspect, she is shown as seated on a lotus in ç
a pavilion surrounded by the celestial nymphs like <188>rva·<200>, ç
Menak<193>, Rambh<193> and others.
@NT = Indraprastha
When the P<193><207><195>avas returned to Hastin<193>pura, after their ç
marriage with Draupad<200>, Dh<216>tar<193><218><219>ra, the blind ç
king, gave them half the kingdom. The P<193><207><195>avas desired ç
to build a suitable city for their capital. K<216><218><207>a called ç
Vi·vakarma, the architect of the gods and asked him to build a city ç
at Kh<193><207><195>avaprastha, the level ground, where the Kh<193><207><195>ava ç
forest was earlier situated. This had been burnt down by Agni the ç
fire-god. Arjuna and K<216><218><207>a had given him all help and ç
protection in this act.
The city, situated on the bank of the Yamun<193> river, was the most ç
beautiful of all the cities of that time. It was in this city, in ç
their palace of unmatched grandeur, that the P<193><207><195>avas ç
conducted the R<193>jas<220>ya sacrifice.
When the P<193><207><195>avas decided to leave on their final journey ç
(mah<193>prasth<193>na), they crowned the prince Vajra, a grandson ç
of K<216><218><207>a, as the king of Indraprastha.
The old city of Delhi, it is claimed, is standing at the same site ç
of Indra- prastha.
@NT = indriyadh<193>ra<207><193>
@N1 = (`restraining<R>ç
the senses')
This is a special term found in the Ka<219>ha Upani<218>ad (6.11) ç
though the idea itself is quite common.
The full verse runs as follows: `They (the sages) consider that as ç
yoga†the steady control of  the  senses  (sthir<193>m indriyadh<193>ra<207><193>m); ç
the yogi must be vigilant; for yoga can be acquired and lost'.
Yoga is perfect concentration of the mind leading ultimately to the ç
union of the j<200>va (individual soul) with Param<193>tman (the Supreme ç
Soul). This concentration can be attained only when the senses do ç
not function actively, giving rise to mental quietude or tranquillity.
`Indriyadh<193>ra<207><193>' is this holding back of the sense organs ç
and their activity.
@NT = indriyanigraha
@N1 = (`control of the<R>ç
sense-organs')
All the philosophical systems of India as also the various religions ç
which accept the authority of the <185>rutis or the Vedas, are unanimous ç
that indriya-nigraha or the control of the sense-organs is absolutely ç
necessary to attain mok<218>a or liberation from transmigratory existence.
Mok<218>a can be attained either through j<210><193>na (knowledge ç
or direct experience of one's <193>tman-nature) or through bhakti ç
(devotion that leads one to God). For either of these paths, mind ç
is the chief instrument of s<193>dhan<193> or spiritual practice. ç
Since the indriyas or the sense-organs, if allowed to go towards the ç
sense-objects, can make the mind impure or distracted, there is a ç
great need to reign them in. It is this that is meant by the word ç
indriyanigraha.
Of course, the indriyas can and must be directed towards those objects ç
or persons associated with God so that they bring in pure vibrations ç
that help the aspirant to cleanse the mind.
@NT = indriyas
@N1 = (`sense-organs')
The chief instruments with which a human being is equipped, for acquiring ç
knowledge from the external world and react to it, are the indriyas ç
or the sense-organs. They are generally grouped into two categories: ç
the j<210><193>nendriyas (organs of knowledge) and the karmendriyas ç
(organs of action).
Since they are five in each category, they are also called `pa<210>caj<210><193>nendriyas' ç
and `pa<210>cakarmendriyas' (pa<210>ca = five).
The five j<210><193>nendriyas are: ·rotra (ear), tvag (skin), cak<218>us ç
(eye), jihv<193> or rasan<193> (tongue) and ghr<193><207>a (nose).
The five karmendriyas are: v<193>k (speech), p<193><207>i (hands), ç
p<193>da (feet), p<193>yu and upastha (organs of evacuation and procreation).
The j<210><193>nendriyas are produced from the sattva part of the ç
tanm<193>tras or s<220>k<218>mabh<220>tas or subtle elements. The ç
karmendriyas are produced from the rajas part of the same.
The mind is also considered as an indriya and is termed as `anta<199>kara<207>a' ç
or the inner organ.
@NT = Indus Valley Civilisation
When during the middle of the 19th century the two British engineers ç
who were in charge of constructing a railway-line, got the mounds ç
at Harappa (now in Pakistan) dug, for getting the burnt bricks to ç
be used as ballast, little did they know that they were digging up ç
a past and hitherto unknown facet of the history of India! It was ç
a great, even exciting, discovery.
Suspecting theexistence of the remnants of an ancient civilisation, ç
systematic excavations were undertaken during <MS>A.<|>D.<D> 1921-22 ç
by the Archaeological Department of India. These excavations led to ç
the detection of a proto-historic city, now called `Harappa'.
Further excavations over the next few decades in about 80 sites, all ç
over India, revealed some more pre-historic cultures and civilisations. ç
However, almost all the cultures cognate to the discoveries at Harappa, ç
were concentrated in the Sind, Baluchistan and Punjab areas now in ç
Pakistan, a few being found in Gujarat and Rajasthan of India also.
By far, the most extensively researched findings are at Harappa and ç
Mohenjo D<193>ro (both in Pakistan now). The other sites are at Kalibangan ç
(Rajasthan), Lothal,  Rangpur  (both  in  Gujarat), Bahawalpur  Ch<193>nhu  D<193>ro,  Amri,  Ali ç
Murad, Pandi Wahi, Dabarkot and Quetta (all in Pakistan now).
The archaeological finds at various levels or depths have been assigned ç
to different periods of history, the oldest being 4000 <MS>B.<|>C.<D> ç
and the most recent one 2200 <MS>B.C.<D>
As regards the nature of this civilisation and culture, whether it ç
was pre-°ryan and pre-Vedic called Dravi<195>ian, several conjectures ç
have been made, mostly by the European scholars. These scholars opine ç
that this civilisation was destroyed by the invading °ryans around ç
1500 <MS>B.<|>C.<D> However, researches based on the various finds ç
in detail have revealed that this culture of Harappa and allied sites ç
was a continuation of the Vedic culture, its later phase; and that ç
the °ryans were indigenous people who had always lived in the Indo-Gangetic ç
plains.
@SPACE1 = 
The disappearance of the Harappa civilisation might have taken place ç
due to the drying up of the Sarasvat<200> river, disturbance of the ç
ecological balance and severe climatic changes resulting in a great ç
famine, probably during the period 2200-1900 <MS>B.<|>C.
@SPACE1 = 
A brief account of the Harappa and Mohenjo D<193>ro civilisation may ç
now be given.
The Harappa town was a square of about 1.5 kms. (0.9 mile) on each ç
side and about 4.8 kms. (3 miles) in circumference. It was laid out ç
in a grid pattern of streets. The houses were built of burnt bricks ç
whose dimensions conformed strictly to the K<193>·yapa Sa<221>hit<193> ç
(viz., 11.75" x 5.25" x 7.5" and two more sizes). The houses had only ç
one main door for entrance, fixed in the side lanes. There were courtyards ç
inside, windows opened to the streets. Small houses had just two rooms ç
whereas the bigger ones could have even twenty five rooms. Bathrooms, ç
latrines and sanitary arrangements were very good. Apart from bricks ç
and mortar, wood was generously used, not only for construction purposes ç
but also for a wide range of furniture like cots, chairs, stools, ç
tables and easy-chairs. Firewood and charcoal were in use in the domestic ç
stoves. Rooms were often set apart for purpose of worship.
Roads were straight and were maintained well. Special chambers had ç
been constructed for the collection and disposal of garbage.
One of the most striking features ofthe Harappa town was its big ç
granary or warehouse. There were 12 granaries arranged in two parallel ç
rows, with proper arrangements for ventilation and passages of approach. ç
There were also grain millers built on brick platforms where wooden ç
pestles were used for crushing the grains.
Mohenjo D<193>ro (`the mound of the dead') is situated on the west ç
bank of the Indus river, about 600 kms. (375 miles) to the south-west ç
of Harappa.
This site, better preserved, is larger than Harappa. The layout is ç
strikingly similar to that of Harappa.
@SPACE1 = 
The chief attraction of this site is what is now called `The great ç
Bath.' It was built of brick set in gypsum mortar with a damp-proof ç
course of bitumen. The dimensions are: 54 by 33 metres (177 by 108 ç
ft.). The outer walls are massive, 2to 2.5 metres (7 to 8 ft.) in ç
thickness. In the centre there is an open paved quadrangle, with verandahs ç
on four sides. At the back of the verandahs, are galleries and rooms. ç
In the centre of the paved quadrangle is a large swimming bath 11.8 ç
by 7 metres (39 by 23 ft.), which is lined by finely dressed brick ç
laid in gypsum mortar covered with bitumen. There are steps leading ç
down to a low platform for the convenience of the bathers. Arrangements ç
for some kind of steam-bath are also found.
Some features common to all the sites of the Indus Valley Civilisation ç
may now be described.
This civilisation was more ancient and comprehensive than the ones ç
of Egypt, Sumeria, Assyria and Mesopotamia.
People were mostly vegetarians and consumed fish also. Apart from ç
wheat, barley and rice, they grew several varieties of fruits and ç
vegetables also like pumpkin, dates and coconuts. They wore clothes ç
made out of cotton, jute and fibres. Several varieties of dressing ç
hair were common among the women. The ornaments used were girdles, ç
ear-rings, bangles, necklaces, nose-rings, anklets, hairpins and beads. ç
Turbans and head-dresses were used by women too.
The use of metals like gold, silver, lead, tin, copper, nickel, bronze ç
as also many  precious  stones  like  diamonds, rubies, emeralds, ç
topazes was well-known to them. Razors for shaving and highly polished ç
mirrors were made out of these metals.
The soldiers used such weapons as bows and arrows, spears, axes, maces, ç
catapults and slings.
Weightsandmeasureshad been standardised. One scale discovered in ç
the ruins has very accurate markings.
Trade and commerce by land and by sea were flourishing. Contacts had ç
been well-established with Sumeria, Babylonia and Egypt for trade ç
and commerce.
People were good at arts and crafts also, as can be surmised through ç
the various well-finished toys unearthed from the ruins. Ch<193>nhu ç
D<193>ro town was famous for this.
Music and dancing were also known to them. Stringed instruments resembling ç
a v<200><207><193> (lute), cymbals, m<216>da<209>ga (drum) were in ç
use, as can be guessed through their figures on the seals found.
Pots and jars with various drawings and paintings have been recovered ç
from the site.
@SPACE1 = 
Various traditional Indian games like dice-play in current use, were ç
known to them and were in use.
As regards the disposal of the dead, cremation, burial as also leaving ç
the bodies to be eaten up by birds and animals, seem to have existed. ç
Bodies of babies and little children were generally interred in pots ç
and then buried.
One enigmatic aspect of the Indus Valley Civilisation is the script ç
discovered on the various seals. All attempts over the last few decades ç
by eminent paleo-graphers to decipher them have not yielded much results. ç
Whether the seals were amulets containing some mantras or whether ç
it is some kind of the earliest form of Br<193>hm<200> script, it ç
is very difficult to say.
Coming to the religious beliefs, worship of <185>iva-Pa·upati, Goddess ç
Durg<193>, li<209>gas and certain animals and trees like bison, fish, ç
serpent, holy basil (tulas<200>) and peepul tree seem to have existed.
In conclusion it may be said that the Indus ValleyCivilisationandCulture, ç
represents the later phase of the <184>gvedic culture and there is ç
no clinching evidence to support the other views that have been
