@NID = hazarded by the European scholars basedon insufficient evidence ç
or wrong assumptions.
@NT = inheritance
In the Hindu society, the inheritance of the property of a dead person ç
has been considered and decided from a religious standpoint. It is ç
the sapi<207><195>a relationship that clinches the matter. (See <MS>SAPIØ£A<D> ç
for details.) The person who inherits the property is obliged to ç
perform the ·r<193>ddha and other obsequial ceremonies regularly. ç
For this he has to set apart, a part of the inherited property (sometimes ç
as much as 50%!).
The dharma·<193>stras contain exhaustive details aboutthis subject.Thereare ç
different schools of thought also.
@NT = intercalary month
See <MS>ADHIKAM°SA.<D>
@NT = ®·<193>na
@N1 = (`One who rules')
<185>iva, the third deity of the Hindu Trinity, has several aspects. ç
As Pa<210>c<193>-nana, he is represented as a five-faced god, of which ç
®·<193>na is the first face turned towards the Zenith. He represents ç
the highest aspect and is also called `Sad<193>·iva'. On the physical ç
plane he represents the power that rules over <193>k<193>·a or ether, ç
the sky. On the spiritual plane he is the deity that grants mok<218>a ç
or liberation.
®·<193>na is also the name of one of the eight dikp<193>lakas, the ç
guardian-deities of the quarters, the north-east being the direction ç
assigned to him.
He is also classed among the eleven Rudras of the Vedic pantheon, ç
representing the principles of pr<193><207>a or life-force.
Sometimes, the Rudras are listed as eight and ®·<193>na is one of ç
them. Actually all these are different names of <185>iva himself.
Iconographical works represent him as <185>iva in the human form, ç
with four hands, in one of which he is holding the trident and is ç
riding a bull. ®·<193>n<200> is his consort. She is the same as P<193>rvat<200>.
@SPACE = 
@NT = ®·<193>v<193>sya Upani<218>ad
@SPACE = 
Out of the six systems of philosophy of orthodox Hinduism, the Ved<193>nta ç
system is the most popular one. Its canonical works are: the Upani<218>ads, ç
the Brahma-s<220>tras and the Bhagavadg<200>t<193>.
Though the total number of Upani<218>ads  available  in  print  today, ç
exceeds 250, only ten out of them have been universally accepted as ç
basic and authoritative, since <185>a<209>kara(<MS>A. D.<D> 788-820), ç
the earliest commentator, has chosen to write commentaries only on ç
these ten. As he has quoted from another three or four more Upani<218>ads, ç
these too have been recognized as ancient and authentic texts.
The ®·<193>v<193>sya Upani<218>ad†also spelt as ®·opani<218>ad†is ç
the first in this list. It gets this appellation since it begins with ç
the word `<200>·<193>v<193>syam.' It is sometimes christened as Sa<221>hitopani<218>ad ç
also, since† as a lone exception†itappears in the Sa<221>hit<193> ç
portion of the <185>ukla Yajurveda (as its 40th chapter), also called ç
the V<193>jasaney<200> Sa<221>hit<193>. Though a short work of only ç
18 verses, it has attracted the attention of many a scholar, resulting ç
inthe maximum number<|> of <|>Sanskrit<|> commentaries on any single ç
Upani<218>ad. And, in spite of the strenuous efforts of these intellectual ç
giants, the Upani<218>ad continues to baffle the reader even today!
The first verse declares that the whole world is permeated by God†called ç
®·a here†and advises the human beings to enjoy it in a spirit of detachment ç
since it belongs toGodand nottothem. Consequently greed for others' ç
wealth and possessions is forbidden.
The second verse advises all human beings to aspire to live for a ç
hundred years but spend that life in working for the welfare†both ç
temporal and spiritual †of the world. If life is spent in this way, ç
karma or action can never taint and be a cause for suffering.
If on the other hand, this advice is not heeded, such transgressors†declares ç
the third verse†will have to suffer in dark hellish worlds!
The next two verses describe, though in an enigmatic language, the ç
nature of the <193>tman, the inner and the true Self of all.
Verses 6 and 7, portray the state attained by a person who has realized ç
this <193>tman. Since he perceives the same universal Spirit in all, ç
he loves all, thus transcending hatred, delusion and sorrow which ç
are always caused by the seeing of duality.
The next, the 8th, verse gives a highly poetical description of this ç
<193>tman in its universal  dimension,  as  all-pervading, effulgent, ç
absolutely pure and as the Supreme Ruler.
The next six verses (9 to 14) have proved to be rather obscure and ç
the traditional commentators have differed widely in their interpretations.
@SPACE1 = 
The wise ones declare that the end results of vidy<193> and avidy<193> ç
are entirely different. However, a balanced combination of these two ç
alone can lead to immortality.
`Avidy<193>' has been interpreted as Vedic rituals, and `vidy<193>' ç
as the up<193>san<193>s (meditations) on the Vedic deities preceded ç
by a j<210><193>na (knowledge) about them. Mere Vedic rituals will ç
lead to pit<216>loka (the world of manes) and mere up<193>san<193>s ç
on the Vedic gods, to devaloka (heaven). But one has to return to ç
this world from both of them, after exhausting the religious merit. ç
Since a taste of the pleasures of these worlds creates a strong tendency ç
in one's psyche to try for them again, the person takes recourse to ç
the same course† Vedic rituals for getting to pit<216>loka or Vedic ç
meditations to attain devaloka† thereby missing the royal path that ç
leads to mukti or freedom from transmigratory existence. It is this ç
spiritual tragedy that has been described by the Upani<218>ad as `entering ç
into blinding darkness' (andha<221> tama<199>).
When a balanced combination of these two is practised, in the right ç
spirit, the result will be entirely different. Performance of Vedic ç
rituals and ordained duties of one's life will lead to the purification ç
of the mind. Meditation on God (®·a) practised by such a pure mind ç
will lead ultimately to realising him, resulting in mok<218>a (liberation ç
or immortality).
Opinions of the commentators seem to be even more sharply divided ç
with regard to the words sambh<220>ti, asambh<220>ti and vin<193>·a, ç
used in the verses 12 to 14.
@SPACE1 = 
<185>a<209>kara takes the words sambh<220>ti and asambh<220>ti to ç
mean the K<193>ryabrahma (or Hira<207>yagarbha, the totality of creation, ç
the First in evolution) and the K<193>ra<207>a-brahma (Prak<216>ti ç
or Avy<193>k<216>ta, the subtle causal state before creation) respectively. ç
Meditation on the former leads to the acquisition of the supernatural ç
psychic powers and on the latter, to a state called `prak<216>tilaya,' ç
a state in which the soul lies merged in Prak<216>ti, in a state of ç
apparent stupor, free from all experiences of joy or sorrow. (c. f. ç
Yogas<220>tras 1.19 of Pata<210>jali.) The former leads one astray ç
from the spiritual path whereas the latter resembles inertness and ç
consequently no effort is made in any direction.
@SPACE1 = 
Since both these results†from the standpoint of mok<218>a or ultimate ç
liberation †lead one away from the spiritual goal, they have been ç
termed `andha<221> tama<199>' or blinding darkness.
An interesting interpretation†which appears to be more convincing ç
or reasonable†has been offered by Uva<219><193>c<193>rya (11th century), ç
the commentator on the M<193>dhyandina  recension  of  the  <185>ukla ç
Yajurveda. According to him, sambh<220>ti is Parabrahman (God, the ç
Absolute) and vin<193>·a (= asambh<220>ti) is the body. Since continual ç
hunger and thirst result in the death of the physical body which is ç
an invaluable instrument of s<193>dhan<193> (spiritual effort), they ç
have to be transcended by suitable secular activities. Then, through ç
contemplation on Brahman, one can attain immortality. Thatis why ç
a balanced combination of both is needed.
The verses 15 to 18 describe the prayers addressed to God, in and ç
through the orb of the sun, by the earnest spiritual seeker who is ç
on his deathbed.
In the verse 15, he requests God to remove the obstacle to his vision, ç
the obstacle  being  the  attractions of this material world which ç
have hidden God's glorious face. In the next verse the same prayer ç
is continued with a description of God's attributes and a hint ofthe ç
experience of identity of the aspirant withhim.
In the verse 17, the aspirant, becoming aware of the imminent death ç
of the body prays to Agni, the presiding deity of his sacrificial ç
fire†or the word `kratu' here may mean God himself†to remember his ç
good deeds and save him.
In the last verse, the 18th, he urges Agni to take him to Brahmaloka ç
or Satya- loka from which there is no return to mundane existence, ç
by the arcir<193>dim<193>rga or devay<193>na, the path of light, believed ç
to be leading the spiritually mature souls to that world.
At a time when there seems to have been a conflict between the concepts ç
of work and worship, and, some sages were laying a greater emphasis ç
on renunciation and monastic way of life, the teachings of this Upani<218>ad ç
must have come as a refreshing contrast for the ordinary, but earnest, ç
s<193>dhakas. Giving up selfish and desire-motivated actions, performing ç
acts of charity and service, devotion to God and considering human ç
life more as a blessing than as a curse, are the central messages ç
of this small but beautiful Upani<218>ad.
See also <MS>UPANI<186>ADS<D>.
@SPACE = 
@NT = i<218><219>adevat<193>
@N1 = (`deity [of contemplation] dear to oneself<|>')
@SPACE1 = 
Though God is one, his aspects for contemplation can be many. The ç
path of bhakti gives the freedom to the spiritual aspirants to choose ç
any of these aspects for the purpose of meditation. Any one of theseaspects ç
which the aspirant chooses, becomes his `i<218><219>adevat<193>' (chosen ç
deity dear to oneself).
The general rule is that the aspirant has to stick to one i<218><219>adevat<193>. ç
He should receive and repeat one mantra pertaining to it till he gets ç
realisation. For this he should have only one guru or spiritual teacher.
In traditional initiation, the guru generally gives the mantra along ç
with certain ritualistic instructions like ny<193>sas (purificatory ç
processes), dhy<193>na·loka (hymn of contemplation) and the mantra ç
in which the b<200>ja (seed letter) is imbedded.
See also <MS>BHAKTIYOGA.
@SPACE = 
@NT = i<218><219>ak<193>
@N1 = (`burnt brick')
@SPACE = 
Vedic sacrifices often need a proper alter which is normally made ç
of burnt bricks. Such bricks, made of clay, must be as long as the ç
length of the foot of the yajam<193>na or the sacrificer. Three lines ç
are also drawn on them.
The total number needed for the altars of some sacrifices (in five ç
layers) is 10,800.
The very first brick prepared by the wife of the sacrificer is named ç
<193><218><193><195>h<193>. Three more prepared by the sacrificer ç
himself are called `vi·vajyotis'. Other types of bricks are also named ç
with such special nomenclature as yaju<218>mat<200>, lokamp<216><207><193>, ç
v<193>lakhily<193>, svayam<193>t<216><207><207><193>, citri<207><200> ç
and so on. They are used in different parts of the  altar  structure,  with  appropriate ç
mantras known as i<218><219>ak<193>mantras.
See also <MS>VEDIC SACRIFICES.<D>
@NT = i<218><219>ali<209>ga
@N1 = (`li<209>ga dear to one')
V<200>ra·aivism,  one  of  the  several aspects of <185>aivism, has ç
prescribed a special mode of d<200>k<218><193> or initiation. The ç
guru gives triple d<200>k<218><193> to the disciple. Kriy<193>d<200>k<218><193>, ç
the first, has a ceremonial form in which the guru gives the disciple ç
a li<209>ga (emblem of <185>iva, usually of stone, but encased in ç
a silver casket) after worshipping it. The disciple has to wear it ç
like a necklace. He has to worship it thrice daily†in the morning, ç
at noon and in the evening.
Even women can receive such a d<200>k<218><193> and can perform its ç
worship. 
For one who has received the li<209>ga there is no need to observe ç
a·auca or ceremonial impurity.
It is this li<209>ga that is called `i<218><219>ali<209>ga'.
The other two aspects of d<200>k<218><193> aremantrad<200>k<218><193> ç
(imparting the famous mantra, nama· ·iv<193>ya) and vedad<200>k<218><193> ç
(infusing knowledge by direct contact).
See also <MS><185>AIVISM<D>.
@NT = i<218><219><193>p<220>rta
@N1 = (`what is sacrificed and what is filled')
The word `i<218><219><193>p<220>rta' is very ancient. It has been ç
used in the <184>gveda (10.14.8), the Atharvaveda (3.29.1), the ç
Taittir<200>ya Sa<221>hit<193> (7.7.1-3) as also in some of the ç
major Upani<218>ads like the Ka<219>ha (1.8) and the Mu<207><195>aka ç
(1.2.10). Though, individually, the two words of the compound (i<218><219>a ç
and p<220>rta) mean, `what is sacrificed' and `what is filled' the ç
total sense seems to be: cumulative spiritual result or merit due ç
to a man's performance of sacrifices and charitable acts.
`I<218><219>a'  includes all  types  of  Vedic sacrifices, including ç
the gifts given during its performance.
`P<220>rta' indicates the various acts of charity and public utility ç
such as: building and dedicating of deep wells for the goodof the ç
public, building temples and gardens, free distribution of food, giving ç
gifts, nursing the sick and many other acts of charity sanctioned ç
by the holy books.
@SPACE = 
@NT = I<218><219>asiddhi
@N1 = (`attaining what is desired')
@SPACE = 
Ved<193>nta in general, and Advaita Ved<193>nta in particular, has ç
two aspects: statement of its theories and dialectical demolition ç
of other schools. Among the latter group of works, the I<218><219>asiddhi ç
of Vimukt<193>tman (circa <MS>A.<|>D.<D> 900) has earned for itself ç
an important place. It is the fourth work in the Siddhi category, ç
theother three being Brahmasiddhi, Nai<218>karmyasiddhi and Advaitasiddhi, ç
of Ma<207><195>ana Mi·ra (8th cent. <MS>A.<|>D.<D>), Sure·vara (8th ç
century <MS>A.<|>D.<D>) and Madhus<220>dana Sarasvat<200> (<MS>A.<|>D.<D> ç
1525-1632) respectively.
The I<218><219>asiddhi has been considered as such an extremely ç
important polemical work of Advaita Ved<193>nta that it has been accepted ç
as an authority by later writers, not only of Advaita but also of ç
other schools.
The work devotes a major part to the analysis of the various theories ç
of error (called `khy<193>ti') and shows their defects. Itdefends ç
the anirvacan<200>yakhy<193>ti of the Advaita Ved<193>nta. It establishes ç
the inexplicable character of the world of m<193>y<193>.
As regards the removal of avidy<193> or nescience, it puts forward ç
its own theory as the fifth mode (pa<210>camaprak<193>ra). Since avidy<193> ç
is anirvacan<200>ya or indescribable, its removal also is anirvacan<200>ya!
Even in j<200>vanmukti (liberation while alive), Vimukt<193>tman feels, ç
there is a trace of ignorance (avidy<193>le·a); because, the continuance  of  vyavah<193>ra  (day-to-day ç
activities) is impossible without a certain degree of attachment to ç
the body and consciousness of the external world as a separate entity.
Advaitins attribute two other views to Vimukt<193>tman; that there ç
are as many knowledges as there are nesciences; that the <193>tman ç
binds itself and also releases itself.
The entire work is in the form of k<193>rik<193>s or verses and explanations ç
in prose.
J<210><193>nottama (10th century <MS>A.<|>D.<D>) has written a commentary ç
called Vivara<207>a.
@NT = i<218><219>i
@N1 = (`sacrifice')
Vedic sacrifices are classified into several groups. One group in ç
which there are four priests adhvaryu, <193>gn<200>dhra, hot<216> ç
and brahman and the material used for oblation is <193>jya (clarified ç
butter) or puro<195><193>·a (rice-cake) or caru (porridge), is called ç
an `i<218><219>i'.
The Dar·a and the P<220>r<207>am<193>sa are the models for an i<218><219>i.
The word is also used to indicate a particular mode of offering oblation ç
as different from <193>huti and homa.
See also <MS>DAR<185>AP<188>RØAM°SA<D> and <MS>VEDIC SACRIFICES.<D>
@NT = ®·vara
@N1 = (`one who rules,' `the Lord')
The word `®·vara' has been used in the Hindu scriptural works both ç
in a general sense and in a more particular sense. In a general sense ç
it means `God'. In the restricted sense it stands for <185>iva, the ç
last deity of the Hindu Trinity.
See <MS>GOD<D> and <MS><185>IVA<D> for details.
In Advaita Ved<193>nta, the word is used to indicate Brahman, the ç
Absolute, after becoming conscious of his power of m<193>y<193> and ç
reflecting on the process of creation. Sometimes other names such ç
as Avyakta (the Unmanifested), Jagatk<193>ra<207>a (the cause  of ç
the world),  Antary<193>min  (the inner controller) are also used.
@NT = ®·varacandra Vidy<193>s<193>gara
@N1 = <R>ç
(<MS>A.<|>D.<D> 1820-1891)
According to Vivek<193>nanda (<MS>A.<|>D.<D> 1863-1902) any one wishing ç
to work in the field of social reform, must have three quali-fications: ç
intense feeling or sympathy for the oppressed; a thorough knowledge ç
of their problems and the solutions; an adamantine will to put the ç
solutions into practice.
@SPACE = 
@SPACE = 
One such great reformer of the nineteenth century India who fits into ç
this pattern perfectly, was ®·varacandra Vidy<193>s<193>gara.
He was born in <MS>A.<|>D.<D> 1820 in a small village of Midnapur district ç
(in West Bengal)  and  came  to  Calcutta  (now Kolkata) at the age ç
of nine for higher education. Pursuing his education in the midst ç
of many difficulties, he got his title `Vidy<193>s<193>gara' in his ç
nineteenth year from the Sanskrit Mah<193>p<193><219>ha·<193>l<193> ç
where he studied.
He worked as a Sanskrit teacher in the Fort William College. When ç
he was offered the post of the professor of Vy<193>kara<207>a (grammar ç
of Sanskrit) in the Mah<193>p<193><219>ha·<193>l<193> where he had ç
studied, he felt that T<193>r<193>n<193>tha Tarkav<193>caspati (<MS>A.<|>D.<D> ç
1806-1885) was a better candidate and prevailed upon him to accept ç
it, after walking a distance of 161 kms. (100 miles) to his place ç
of residence!
He later on became the principal of the Fort William College wherein ç
he successfully introduced some badly needed reforms. This enabled ç
the members of the non-br<193>hma<207>a  classes  also  to  learn ç
Sanskrit.
In  course  of  time  he  resigned his job and started his own educational ç
institution.
Throughout his life, he struggled with the orthodox and begoted sections ç
of the Hindu society to introduce some urgent social reforms like ç
the remarriage of child-widows. He was one of the important leaders ç
of this movement. The spirit of this movement spread to several other ç
parts of India also.
He fought against the social system of polygamy which was rampant ç
in the Hindu society also.
His literary works in Bengali are: Bet<193>lapa<210>cavi<221>·ati, ç
<185><193>kuntal<193> and S<200>t<193>parity<193>ga. The last ç
work has been considered as his best.
@SPACE1 = 
He breathed his last in July 1891.
@NT = ®·varag<200>t<193>
@N1 = (`[the teaching] sung by ®·vara or <185>iva')
@SPACE = 
@SPACE = 
The Bhagavadg<200>t<193> has, in course of time, given rise to a ç
number of similar religio-philosophical treatises, either as a part ç
of the epics or of the various pur<193><207>as. One such famous work, ç
the ®·varag<200>t<193>, occurs in the uttarabh<193>ga or the second ç
part of the K<220>rmapur<193><207>a. The first elevenchapters of ç
this pur<193><207>a containing 496 ·lokas in all, comprise the ®·varag<200>t<193>. ç
It is called ®·varag<200>t<193> because ®·vara or <185>iva is the ç
teacher, answering the questions put to him by the various sages like ç
Sanatkum<193>ra, Sanandana, Sanaka, A<209>gir<193>,  Bh<216>gu,  Kapila,  Vasi<218><219>ha  and ç
others who had assembled at the Badarik<193>·rama.
A brief synopsis of the contents may now be given here:
Description of ®·vara or °tman as the non-dual Reality, as Sat-cit-<193>nanda.
Evolution of this world from pradh<193>na or prak<216>ti, the details ç
being similar to the ones given in S<193><209>khya philosophy.
The glory of <185>iva in Ved<193>ntic terms emphasising  the  path  of  bhakti  or ç
devotion.
Cosmic dance of <185>iva and his eulogy by the sages.
Description  of  <185>iva's  vibh<220>tis  or various manifestations.
Realising <185>iva in one's heart as the means of liberation.
Identity of ®·vara or <185>iva and Parabrahman, the Absolute.
The path of liberation wherein funda-mental ethical virtues like ahi<221>s<193> ç
(nonviolence), satya (truth), brahmacarya (continence) and others ç
have an important place. So also sv<193>dhy<193>ya (study of scriptures), ç
tapas (austerity), pr<193><207><193>y<193>ma (control of breath) and ç
the eight steps of yoga.
The work closes with the narration of the line of teachers as also ç
the phala·ruti  (eulogy  of  this  spiritual wisdom).
Vij<210><193>nabhik<218>u (16th cent. <MS>A.<|>D.<D>) wrote a commentary ç
called ®·varag<200>t<193>bh<193><218>ya which is fairly exhaustive.
@SPACE = 
@NT = ®·varak<216><218><207>a
@SPACE = 
<185>a<209>kara (<MS>A.<|>D.<D> 788-820) in his commentary on the Brahmas<220>tras ç
(1.4.28) uses theexpression `pradh<193>namalla-nibarha<207>a-ny<193>yena'. ç
The maxim means that if the chief opponent is defeated, it is as good ç
as defeating all the others in his camp.
The S<193><209>khyadar·ana or the S<193><209>khya philosophy, is nearest ç
to Ved<193>nta (since it tries to get support from the Upani<218>ads) ç
but has also deviated from it. It is because of this that B<193>dar<193>ya<207>a ç
Vy<193>sa, the author of the Brahmas<220>tras, has taken it up first ç
for refutation.
Though it is difficult to say when exactly this deviation and separation ç
took place, the S<193><209>khyak<193>rik<193> of ®·varak<216><218><207>a ç
is certainly the earliest of the cardinal works of this system.
Practically next to nothing is known of this ®·varak<216><218><207>a. ç
He might have lived some time during the period <MS>A.<|>D.<D> 350-450. ç
He was a br<193>hma<207>a of the Kau·ika gotra (lineage of the sage ç
Kau·ika) and was a monk. He was probably a follower of V<193>r<218>aga<207>ya, ç
a teacher of S<193><209>khya mentioned in the Mah<193>bh<193>rata ç
(306.57).
See also <MS>S°<177>KHYAK°RIK°.<D>
@NT = <200>·varapra<207>idh<193>na
@N1 = (`devotion to ®·vara or God')
This is a special word used in the Yogas<220>tras (1.23) of Pata<210>jali ç
(200 <MS>B.<|>C.<D>).
After describing a few methods for suppressing the modifications of ç
mind, Pata<210>jali,  apparently  recognising  the desire of a s<193>dhaka ç
for an easy method, is giving it in this s<220>tra.
®·vara is God and pra<207>idh<193>na is devotion. This devotion must ç
express itself in the form of dedicating the fruits of all our actions ç
unto him. When he is pleased, he may give even sam<193>dhi, what to ç
speak of lesser states of yoga.
@NT = Itar<193>
The well-known Aitareya Upani<218>ad, one of the ten major Upani<218>ads, ç
was revealed to Mahid<193>sa Aitareya who is said to have lived for ç
116 years. He was the son of Itar<193> and the sage M<193><207><195><220>ki.
See <MS>AITAREYA<D> for details.
@NT = itih<193>sa
@N1 = (`thus it was')
The R<193>m<193>ya<207>a and the Mah<193>bh<193>rata are known ç
as `itih<193>sa' or epics. An itih<193>sa narrates a story that happened ç
in the ancient days, and has come down to us by oral tradition. It ç
may later be put in writing.
As per the definition given in some Sanskrit works, an itih<193>sa ç
must contain topics dealing with all the four puru<218><193>rthas ç
viz., dharma (virtue), artha (wealth), k<193>ma (desires of the flesh) ç
and mok<218>a (emancipation). This is generally done through the narration ç
of incidents that took place in the olden days.
The words `itih<193>sa' and `pur<193><207>a' have often been mentioned ç
in the Vedic literature (vide Atharvaveda 15.6.4; <185>atapatha ç
Br<193>hma<207>a 13.4.3.12; B<216>had<193>ra<207>yaka Upani<218>ad ç
2.4.10). There, the difference between the two does not seem to be ç
very clear.
@NT = itikartavyat<193>
@N1 = (`mode of performing a duty')
This is a technical term used in the P<220>rvam<200>m<193><221>s<193> ç
Sutras (11.2.8). It answers the question as to how a thing is to ç
be accomplished.
When someone is hungry, he has to prepare food and eat it. For this ç
he has to cook the raw rice, for which again, he has to get the necessary ç
vessels and also prepare fire using fuel sticks.
Similarly, if a person wants to perform a Vedic sacrifice, he must ç
be given detailed, step-by-step, instructions. This is called `itikartavyat<193>'.
@END = 
