@H = P
@NT = p<193>dak<216>cchra
@N1 = (`k<216>cchra of four aspects')
Man is often prone to committing sins due to the weaknesses of the ç
flesh. However, religions generally provide him with ways and means ç
of redeeming himself.
Hinduism prescribes two steps for such redemption: pa·c<193>tt<193>pa ç
(repentance) and pr<193>ya·citta (expiation).
The most general name for pr<193>ya·cittas is `k<216>cchra'. Out of ç
the several varieties of k<216>cchra, the p<193>dak<216>cchra is also ç
one. In this expiation, the transgressor of dharma has to take food ç
only once by day (on the first day of expiation), once only by night ç
on the second day, once at any time (if he gets the food unasked) ç
on the third day and observe a total fast on the fourth day.
Even the quantity of food allowed on the first three days is restricted ç
by the dharma·<193>stras.
See also <MS>K<184>CCHRA<D>.
@SPACE = 
@NT = padap<193><219>ha
See <MS>GHANAP°<187>HA<D>.
@SPACE = 
@NT = pad<193>rtha
@N1 = (`object,' `category')
This word is used in several senses such as the meaning of a word, ç
an object and a category.
The last one is a technical term used in the Vai·e<218>ika Dar·ana ç
and comprises seven pad<193>rthas.
See <MS>VAI<185>E<186>IKA-DAR<185>ANA<D>.
@NT = padma
@N1 = (`lotus')
`Padma' is one of the most widely used words in the Sanskrit language ç
with a variety of meanings such as: lotus flower, certain marks on ç
the face of an elephant, a particular formation of an army, the cakras ç
(psychic centres in the body), one of the nine treasures of Kubera ç
(the god of wealth) and the number 1019.
However, the lotus also is widely used as a symbol and a decorative ç
motif in temples and other types of buildings. Its symbolical significance ç
may be explained as follows:
The lotus bud is born in water and unfolds itself into a beautiful ç
flower. Hence it is taken as a symbol of the universe coming out of ç
the primeval waters and manifesting itself in all its glory. It is ç
also taken as a symbol of the sun. It rises from the navel of Vi<218><207>u ç
and is the seat of Brahm<193>, the creator. Hence the sacredness associated ç
with it.
The Mah<193>bh<193>rata (Sabh<193>parva 9; <185><193>ntiparva ç
363-371) mentions one Padma, as a king of serpents, extremely sagacious ç
and full of great wisdom.
Padm<193> is one of the names of the goddess Lak<218>m<200>, since ç
she is seated on a lotus and wears a lotus garland.
@SPACE = 
@NT = Padman<193>bha Temple
@SPACE = 
Temples and places of worship, especially those connected with the ç
lives of great saints or miraculous incidents, have been an integral ç
part of Hindu religion and culture. Places associated with such temples, ç
soon become important centres of pilgrimage, attracting thousands ç
of devotees every year especially on special occasions.
One such place in the extremity of South India is the Padman<193>bha ç
Temple of Tiruvanantapuram (or Trivandrum), the Capital of the Kerala ç
State. It is a Vi<218><207>u temple with the image in the ·ay<193>na ç
or reclining posture, resting on the great serpent Ananta (or <185>e<218>a). ç
Hence, it is also known as the Ananta·ayana Temple. Since the image ç
of Vi<218><207>u has padma or lotus with Brahm<193> (the creator) ç
seated on it, he is also known as Padman<193>bha or Padman<193>bhasv<193>mi ç
(one who has the lotus in his navel).
Considered one among the 108 Vi<218><207>u temples sacred to the followers ç
of the Vi<218><207>u cult, it has been praised by Namm<193><202>v<193>r, ç
the last of the °<202>v<193>rs (in his Tiruv<193>ymo<202>i). (See ç
<MS>°<170>V°RS<D>.) Since he is assigned to the 9th century <MS>A.<|>D.<D>, ç
this temple must be considered as much older than that period.
There are several local legends that describe how this temple came ç
into being. The Lord is said to have revealed Himself in this form ç
to the sage Div<193>karamuni who was an ardent devotee of K<216><218><207>a.
According to another version, the revelation came to the sage Vilvama<209>gal ç
(known as Vilvama<209>galattu Sv<193>miy<193>r in Malay<193><202>am ç
language) who saw the Lord in a place in a forest, where a big tree ç
collapsed, giving rise to the vision.
@SPACE1 = 
It is reasonable to believe that though the temple is quite ancient, ç
it must have undergone several renovations and changes.
The temple seems to have been connected with several royal dynasties ç
like the Ay dynasty (300 <MS>B.<|>C.<D>), the Cera kings (of Tamil ç
Nadu and Kerala) and the rulers of Venad (in Kerala).
The most significant event in the history of this temple is the total ç
surrender of the kingdom to the Lord Padman<193>bha by the famous ç
king M<193>rt<193><207><195>a Varma (during his rule in <MS>A.<|>D.<D> ç
1729-1758), who assumed the title `Padman<193>bhad<193>sa' and started ç
ruling as the Lord's servant. He is said to have reconstructed the ç
temple including the replacement of the old idol made of wood, with ç
a new one fashioned out of 1200 <185><193>lagr<193>mas (round stone- ç
emblems of Vi<218><207>u).
The temple faces east and is spread out over an area of 2.8 hectares ç
(7 acres). It is enclosed on all sides by a high granite wall, the ç
height ranging from 4.5 to 6.0 metres (15 to 20 ft.).
The garbhag<216>ha (sanctum sanctorum) is a rectangle measuring ç
7.2 metres (24ft.) in length, 5.4 metres (18 ft.) in width and 12 ç
metres (40 ft.) in height.
The reclining image of Lord Padma-n<193>bha is 5.4 metres (18 ft.) ç
in length. It is facing east, with the head to the south and the feet ç
to the north. From the n<193>bhi or navel, rises a padma or lotus ç
on which is a small figure of Brahm<193>, the four faced creator of ç
the world. The serpent Ananta (or <185>e<218>a) has five hoods and ç
three coils, the latter forming the bed for the Lord and the former ç
acting as a protective umbrella.
The posture is Yoga·ayana and the idol itself is classed among the ç
Uttama-yoga-m<220>rtis.
@SPACE1 = 
Since the outer part of the image is made of wood of certain medicinal ç
trees and a mixture called katusarkarayoga, ceremonial bathing with ç
water is never performed.
There are three main doors for the sanctum, to see the image, the ç
three giving a view of the head or the face, the navel and the feet.
Other important structures and features of this temple-complex are: ç
dhvaja-stambha (wooden flagstaff covered with gold plates and 24 metres ç
or 80 ft. in height); temples or shrines of other deities like R<193>masv<193>mi, ç
Narasi<221>hasv<193>mi, Vi<218>vaksena, Ga<207>apati, <185>iva, and ç
<185><193>st<193> (Ayyappa); <185>r<200>balipura (a long paved corridor ç
running all round, with 324 pillars and a covered roof); the O<219><219>akkal-ma<207><219>apa, ç
a pavilion made of one huge stone; the Kula·ekhara ma<207><219>apa ç
containing several beautifully sculptured images; mural paintings ç
inside the sanctum and many other features.
When one presses his ear against the northern outer wall of the sanctum, ç
he hears the `sounds of waves,' believed to be those of the k<218><200>rasamudra ç
(the ocean of milk) on which the Lord is resting!
The temple has four chief priests called `nambies'. They are assisted ç
by 24 pottis or assistant priests.
Daily rituals start at 3:30 A.M. and come to a close by late night. ç
There are also quite a few monthly, bi-annual and annual rites.
@SPACE1 = 
The most important and spectacular festival is the Murajapam, followed ç
by the Lak<218>ad<200>pam. It is celebrated once in six years and ç
is spread over 56 days. During the latter festival, the entire gopuram ç
(tower) and other parts of the temple are lighted with oil lamps giving ç
a magnificent view of the gopuram in the waters of the temple-tank.
This festival, as is conducted now, is said to be only a faint shadow ç
of the original grand festival, the last of which was held in <MS>A.<|>D.<D> ç
1960.
See also <MS>ANANTA<185>AYANA<D>.
@NT = Padmap<193>da
@N1 = (9th century <MS>A.<|>D.<D>)
Born in a place in South India (Tamil Nadu) on the bank of the river ç
K<193>ver<200>, Padmap<193>da  went  to  K<193>·<200>  (V<193>r<193><207>as<200>, ç
modern Banaras in the State of Uttar Pradesh) for his education. There ç
he met <185>a<209>kara (<MS>A.<|>D.<D> 788-820) and became his disciple. ç
He is said to have been <185>a<209>kara's first apostle.
It is said that he was once washing the clothes of his guru <185>a<209>kara, ç
standing on the bank of a river. <185>a<209>kara, who was sitting ç
on the opposite side of the river called him urgently for some work. ç
Then Padmap<193>da†whose earlier name is not known†set out immediately ç
walking on the water! A padma or a lotus started appearing below his ç
p<193>da or foot supporting him! Hence the name `Padmap<193>da'.
His commentary on the Brahmas<220>tra-bh<193><218>ya of <185>a<209>kara ç
was the earliest of such commentaries. It was supposed to be in two ç
parts, the first being known as Pa<210>cap<193>dik<193> and the ç
later part as V<216>tti.
The story goes that the manuscriptof the entire commentary written ç
by him was destroyed by his uncle smitten by jealousy. However, a ç
part of it was retrieved by him since his guru <185>a<209>kara, who ç
had heard it read out to him†and, <185>a<209>kara was endowed with ç
a photographic memory †dictated that portion, viz., the first five ç
p<193>das or quarters (out of the total of sixteen). The name of the ç
commentary, Pa<210>cap<193>dik<193>, is based on this fact.
However, the commentary on the first four s<220>tras only is available ç
now.
Prak<193>·<193>tman (<MS>A.<|>D.<D> 1200) has written a gloss on this, ç
known as Pa<210>cap<193>dik<193>-vivara<207>a, further amplifying ç
Padmap<193>da's views. This has developed into a separate and special ç
school of Advaita Ved<193>nta called the Vivara<207>aprasth<193>na.
Padmap<193>da was a worshipper of the Narasi<221>ha aspect of Lord ç
Vi<218><207>u and had once saved the life of his guru from the hands ç
of the K<193>p<193>likas.
See also <MS>ADVAITA VED°NTA DAR<185>ANA<D>.
@NT = padmap<200><219>ha
@N1 = (`seat of [an icon shaped like a] lotus')
Building  of  Hindu  temples  and installing of images in them is ç
done strictly in accordance with a well-developed science†of architecture ç
and iconography.
Every m<220>rti or image ceremonially installed in a temple for worship, ç
must have a p<200><219>ha (seat or pedestal) whose size is decided ç
by the size of the image or that of the door of the sanctum. There ç
are several varieties of them of which the padmap<200><219>ha is also ç
one.
This p<200><219>ha or pedestal is of the shape of a padma or a lotus. ç
There may be one or two; in the latter case they are abutted against ç
each other, the lower one being inverted.
@NT = Padmapur<193><207>a
Education and culture should go together. Or, rather, that which imparts ç
culture alone is true education. This is exactly what the pur<193><207>as ç
did in the olden days when formal education given in the gurukulas ç
was restricted to the three higher castes.
Out of the eighteen major pur<193><207>as† called Mah<193>pur<193><207>as†the ç
Padmapur<193><207>a (or P<193>dmapur<193><207>a) is the second.
There seem to be two recensions†the Bengal recension and the South ç
Indian recension†of this pur<193><207>a, though it is only the latter ç
that has been printed.
The total number of granthas or verses is 55,000 distributed among ç
690 adhy<193>yas or chapters accommodated in six kha<207><195>as or ç
books.
This pur<193><207>a has been classed among the s<193>ttvika (and Vai<218><207>ava) ç
pur<193><207>as.
A very brief synopsis of its contents may now be attempted.
@S10N = 1.	°dikha<207><195>a (62 chapters)
This kha<207><195>a is sometimes called Svargakha<207><195>a also. ç
Geographical details of ancient India (called Jamb<220>dv<200>pa and ç
Bh<193>ratavar<218>a), description of a large number  of  t<200>rth<193>s  (places  of  pilgrimage) ç
including  the  rites  and  formalities connected with visiting them ç
are described here. Pray<193>ga (modern Allah<193>b<193>d) containing ç
the Trive<207><200> sa<209>gama (the confluence of the three rivers ç
Ga<209>g<193>, Yamun<193> and the subterranean Sarasvat<200>) is eulogised ç
as the best of all the t<200>rthas. Code of conduct and the duties ç
of the four <193>·ramas are also delineated.
@S10N = 2.	Bh<220>mikha<207><195>a (125 chapters)
This book is perhaps named as Bh<220>mikha<207><195>a to show the ç
importance of this bh<220>mi or earth where alone spiritual progress ç
is possible.
Performance of one's duty is stressed here as important like a t<200>rtha ç
or a holy place, since it purifies one who does it. Incidentally a ç
number of stories are narrated, bringing out the importance of devotion ç
to one's parents, repetition of Lord Hari's name and certain aspects ç
of dharma. Description of svarga (heaven) and naraka (hell) are also ç
given briefly.
@S10N = 3.	Brahmakha<207><195>a (26 chapters)
This is the shortest of all the books.
The name of this book does not seem to have any direct connection ç
with the contents.
Devotion to Lord Vi<218><207>u, importance of physical service in ç
a temple, greatness of the K<216><218><207>ajayant<200> festival, ç
virtuous deeds to be performed by which one can get good children, ç
significance of ek<193>da·<200> vrata (vow), the power of Lord Hari's ç
name and what offends it†these are the topics dealt with here.
@S10N = 4.	P<193>t<193>lakha<207><195>a (113 chapters)
In this book there is a detailed description of the A·vamedhay<193>ga ç
(Horse-sacrifice) performed by R<193>ma. Unlike Valm<200>ki's R<193>m<193>ya<207>a, ç
here S<200>t<193> is reunited with R<193>ma and lives for many more ç
years.
The battles between Lava and Ku·a on one side and the army of R<193>ma ç
on the other, are described in great detail.
The latter part of this pur<193><207>a is devoted to describing the ç
story and the greatness of K<216><218><207>a. The gop<200>s of V<216>nd<193>ban ç
are stated here, to be the <216><218>is or the sages of the Tret<193>yuga ç
who had been captivated by the beauty and charm of R<193>ma, reborn ç
to enjoy his company.
Incidentally,  information  about ·<193>lagr<193>mas, a special mantra ç
of K<216><218><207>a and its repetition, p<220>j<193> of Lord Vi<218><207>u, ç
characteristics and effects of true bhakti or devotion, are also explained.
It is interesting to note that in this book, the greatness of <185>iva, ç
his emblem (the li<209>ga) and his name as also the importance of ç
bhasma (holy ash) are also given a wide coverage.
@S10N = 5.	S<216><218><219>ikha<207><195>a (82 chapters)
Though this book is called S<216><218><219>i-kha<207><195>a, the ç
topic of s<216><218><219>i or creation is only a minor aspect of the ç
subjects dealt with.
Apart from the stories connected withthe devas (gods) and the d<193>navas ç
(demons), the topic of ·r<193>ddha (obsequial rites) is dealt with ç
in detail. The other subjects delineated are: sacrifice performed ç
by Brahm<193>; the story of the sage Agastya subjugating the Vindhya ç
mountain; some vratas or religious observances; story of Mahi<218><193>sura; ç
the arising of a golden lotus from the navel of Vi<218><207>u; birth ç
of Brahm<193> from this lotus; characteristics of a bad and a good ç
br<193>hma<207>a; greatness of a pativrat<193> (chaste woman); importance ç
of various kinds of d<193>na or gifts; on the rudr<193>k<218><200> ç
beads and the tulas<200> leaves; significance of the worship of Ga<207>e·a; ç
and, finally on the worship of the Navagrahas (nine planets) and the ç
goddess Durg<193>.
@S10N = 6.	Uttarakha<207><195>a (282 chapters)
The title `uttara' for this book simply signifies `last'. It is the ç
last of the series of kha<207><195>as comprising this pur<193><207>a.
The contents of this book may be briefly summarised as follows:
Greatness of certain places of pilgri-mage like <185>r<200>·aila and ç
Haridv<193>ra as also the rivers Ga<209>g<193> and Yamun<193>; importance ç
of annad<193>na or gifting food; description of the 24 ek<193>da·is ç
(eleventh days of every fortnight); Vi<218><207>usahasran<193>ma ç
(which is different from the one given in the Mah<193>bh<193>rata); ç
description and greatness of the Vai<218><207>avas (devotees of Vi<218><207>u); ç
battles between the gods and the demons; worship of ·<193>lagr<193>ma ç
(stone symbol of Vi<218><207>u); method of observing the D<200>p<193>val<200> ç
festival; on some more places of pilgrimage; greatness of the Bhagavadg<200>t<193> ç
explained through stories; importance of the Bh<193>gavata; description ç
of certain hells, numbered here as 140; how a bath in a sacred river ç
in the month of M<193>gha (11thlunar month, generally in February) ç
purifies even a great sinner; certain ritu- alistic processes connected ç
with the mantra of Lord Vi<218><207>u; the story of churning the ocean ç
of milk to get am<216>ta or ambrosia; the ten avat<193>ras or incarnations ç
of Vi<218><207>u.
On the whole, it can be stated that this pur<193><207>a, which might ç
have evolved over the period <MS>A.<|>D.<D> 600 to 1400, though it ç
extols the greatness of Vi<218><207>u, is not antagonistic to <185>iva ç
(who is also greatly revered here). It also gives a lot of information ç
about the places of pilgrimage in India.
@NT = padm<193>sana
@N1 = (`the lotus-posture')
The padm<193>sana is a posture recommended in the works on Ha<219>hayoga ç
for meditation. In this posture, one has to sit with both the legs ç
crossed, to resemble a full-bloomed lotus (padma = lotus). It is said ç
to destroy all diseases.
Many images in temples, in the <193>s<200>na or sitting postures, ç
are in the padm<193>sana pose.
See also <MS>°SANA<D>.
@NT = Padm<193>vat<200>
Padm<193>vat<200> is one of the names of Lak<218>m<200>, the divine ç
consort of Vi<218><207>u/ N<193>r<193>ya<207>a. Since she emerged ç
from the k<218><200>rasamudra (See <MS>SAMUDRAMATHANA<D>.) with padmas ç
or lotus flowers in her hands, she was called `Padm<193>vat<200>'.
According to the local legends of Tirumala/Tirupati†the famous place ç
of Vai<218><207>ava pilgrimage†Padm<193>vat<200> was the daughter ç
of one king °k<193>·ar<193>ja and was married to Ve<209>ka<219>e·vara ç
(the central deity of Tirumala). Even today this marriage† known as ç
`Padm<193>vat<200>pari<207>aya' (or `kaly<193>-<207>otsava')†is often ç
ceremonially celebrated by the temple authorities as per the desire ç
of the devotees.
At Tiruc<193>n<220>r, 3 kms. (2 miles) from the Tirupati railway station, ç
there is a big temple of Padm<193>vat<200> who is known (in Tamil) ç
as `Alarmelma<209>gai'.
@NT = Paila
@N1 = (`descendant of the sage Pila')
The sage K<216><218><207>a Dvaip<193>yana has been credited with achieving ç
the great task of collecting all the Vedic mantras extant during his ç
time, editing them by dividing them into four books and teaching them ç
to his four chief disciples. Hence he came to be known as Vedavy<193>sa ç
or Vy<193>sa (vyas= to divide, to edit). These four books† known ç
as the <184>gveda, the Yajurveda, the S<193>maveda and the Atharvaveda†were ç
taught respectively to the sages Paila, Vai·amp<193>yana, Jaimini ç
and Sumantu.
Thus Paila, a descendant of the ancient sage Pila, was the first disciple ç
of Vedavy<193>sa through whom the <184>gveda was propagated. Nothing ç
more is known about him.
@NT = pai·<193>caviv<193>ha
See <MS>VIV°HA<D>.
@NT = Pai<219>h<200>nasi
The Vedas and the Upani<218>ads give a general outline of philosophy ç
and ethics. They do not deal with the daily routine or social conduct ç
of persons living in their society.
This, however, has been done by later writers through whose works, ç
evolved a set of literature, now well-known as dharma·<193>stras. ç
(See <MS>DHARMA<185>°STRAS<D>.)
One of the earliest works in the category of dharmas<220>tras is that ç
of Pai<219>h<200>nasi. Though his work has not been recovered, fragments ç
of the same have been culled from other works which have quoted him.
He perhaps was a follower of Atharva-veda.
A few of the topics on which he has been quoted are: marriage within ç
the gotra permitted if it is beyond third degree on mother's side ç
and beyond the fifth on father's side; service to the husband as the ç
greatest austerity for a wife; on the practice of sat<200> (immolation ç
of the wife onthe funeral pyre of her husband); regarding the inheritance ç
of the property of a sonless man after his death; non- observance ç
of a·auca (ceremonial impurity) at certain times like marriage or ç
famine or pilgrimage.
His  period  is  not  known  even approximately.
@NT = pait<216>ka-mantras
@N1 = (`sacred formulae<R>ç
associated with the pit<216>s or manes')
During the times of the <184>gveda persons who died here were believed ç
to go to the pit<216>loka (world of manes) and live there in subtle ç
bodies. They were propitiated through certain rites (now well-known ç
as ·r<193>ddha) wherein oblations were offered for them into a duly ç
consecrated fire.
The fourteen mantras of the <184>gveda (10.15.1-14) used in such ç
rites are called `pait<216>ka-mantras'.
The <216><218>i or sage of this group of mantras is <185>a<209>kha-Y<193>m<193>yana. ç
The pit<216>s (manes) are the devat<193>s or deities. Tri<218><219>up ç
and Jagat<200> are the metres used.
These mantras are recited during the funeral rites performed in the ç
·ma·<193>na (cremation ground).
The first seven mantras are prayers to the pit<216>s for accepting ç
the offerings and protecting the performer. The eighth one is addressed ç
to Yama, the god of death, to accept the offerings given to him. The ç
next two (and 12th to 14th) are an invitation to Agni, the god of ç
fire and a prayer to him.
It is interesting to note that in thesemantras the pit<216>s are ç
categorised into three groups: uttama (the best), madhyama (middling) ç
and adhama (the lowest).
@NT = p<193>kayaj<210>a
See <MS>VEDIC SACRIFICES<D>.
@NT = pak<218>a
@N1 = (`that which is accepted')
This word is used in several senses. A period of a fortnight between ç
a new-moon day and a full-moon day is called `pak<218>a'. That which ç
ends in the former is called k<216><218><207>apak<218>a and in the ç
latter, ·uklapak<218>a.
In logic, the word indicates the minor term like the hill from which ç
smoke is being emitted. (See <MS>ANUM°NA<D> and also <MS>NY°YADAR<185>ANA<D>.)
In philosophical disputations it indicates a view logically presented. ç
For e.g., p<220>rvapak<218>a (prima facie view) and uttarapak<218>a ç
(final view).
In Vedic sacrifices, it indicates the two rectangular aisles or sides ç
of an altar, to the north and the south.
@NT = pal<193>·av<216>k<218>a
@N1 = (`the tree Butea frondosa')
The pal<193>·a tree (Butea frondosa) is closely associated with ç
several Hindu rites and ceremonies. A da<207><195>a (a stick, like ç
a walking stick) used by the brahmac<193>ri after his upanayana has ç
to be of this wood.
In certain death-rites, three twigs of this tree are firmly fixed ç
in the ground and a pot of sour milk, with several holes in it is ç
placed over it, so that the liquid drizzles over an urn (containing ç
the ashes and bones of the dead person cremated earlier).
Its broad leaves are used in several religious rituals.
@NT = P<193>l<200>
@N1 = (also, P<193><202><200>)
Language plays a very important part in the communication of ideas.
P<193>l<200> (or P<193><202><200>) is one of the several ancient languages ç
of India. During the times of Gautama Buddha (6th century <MS>B.C.<D>) ç
it appears to have been the language of the common people.
Derived from the root `p<193>' (`to protect') `P<193>l<200>' is `that ç
which protects'. However, it was originally applied to Buddha's words ç
as contained in the Tripi<219>akas (or Tipi<219>akas). Later on, ç
it indicated the language of these works.
It has also been known as M<193>gadh<200> language. However, the language ç
of the edicts of the Magadhan emperor A·oka (272-232 <MS>B.<|>C.<D>) ç
is a little different.
P<193>li is closer to Vedic rather than classical Sanskrit.
Apart from the Devan<193>gar<200> script, the scripts of other countries ç
like those of Ceylon (Sri Lanka), Burma (Myanmar) and Thailand are ç
also being used to express the P<193>l<200> texts.
The literature in the P<193>l<200> language is quite extensive.
@NT = Pallavas
The Pallavas were a dynasty of kings who ruled over the northern parts ç
of the present Tamil Nadu. Their origin is not known. Though some ç
scholars hazard a guess that the Pahlavas (of Persia, an ancient race, ç
2nd century <MS>A.<|>D.<D>) and the Pallavas are the same, there is ç
not enough proof for it.
Their best period was from the 6th to the 9th century <MS>A.<|>D.<D>
Mahendravarma (<MS>A.<|>D.<D> 600-630) and N<216>si<221>havarma I (also ç
known as `Mah<193>-malla'; <MS>A.<|>D.<D> 630-660) were the best among ç
them.
They were great builders. The remnants of their architecture are the ç
Rathas of Mah<193>balipuram (or M<193>mall<193>puram) as also the ç
shore temple and the Kail<193>sa-n<193>tha temple of K<193><210>c<200>puram.
@SPACE = 
@NT = palmistry
See <MS>HASTAS°MUDRIK°-<185>°STRA.
@SPACE = 
@NT = Pamp<193>
The name of the beautiful lake at the foot of the <184><218>yam<220>ka ç
hill on which lived the exiled monkey-king Sugr<200>va. It was here ç
that R<193>ma and Lak<218>ma<207>a†after the abduction of S<200>t<193>†met ç
Hanum<193>n, Sugr<200>va's minister, for the first time.
It was an extraordinarily beautiful lake with placid water, full of ç
lotus flowers. Its location has been traced to a place, about 13 kms. ç
(8 miles) away from the present town of Anegondi in the Bellary district ç
of Karnataka.
Pamp<193> is also the name of a small river that takes birth from ç
the Pamp<193> lake and is a tributary of the river Tu<209>gabhadr<193>.
There is another Pamp<193> river in the Kerala State. It originates ç
in the K<193>ntamalai hill and flows right under the famous eighteen ç
steps leading to the shrine of Ayyappan (or Hariharaputra) of <185>abar<200>malai. ç
It later joins the river Kall<193>r.
According to the local legends, the famous <185>abar<200> (devotee ç
of R<193>ma) lived in these parts and Pamp<193> is the same as the ç
lake (or river) at the foot of the <184><218>yam<220>ka hill on which ç
Sugr<200>va lived.
@NT = Pa<210>cab<193><207>a
@N1 = (`one who wields five arrows')
Manmatha, the god of love or lust, is said to discharge five kinds ç
of flowers as arrows from his bow made of sugarcane stalk towards ç
his victims to make them lovelorn. Hence the name (pa<210>ca = five, ç
b<193><207>a = arrow).
See also <MS>MANMATHA<D>.
@NT = pa<210>cabhedas
@N1 = (`five kinds of<R>ç
[fundamental] differences')
See <MS>DVAITA VED°NTA DAR<185>ANA<D>.
@NT = Pa<210>cabh<220>tali<209>gas
@N1KERN = (`<185>ivali<209>gas connected with the five bh<220>tas ç
or elements')
Pa<210>cabh<220>tas are the five fundamental elements out of which ç
the whole material world is created. They are: p<216>thv<200> (earth); ç
ap (water); tejas (fire); v<193>yu (air); <193>k<193>·a (space or ç
ether).
The <185>ivali<209>gas in some well-known places of pilgrimage are ç
said to be closely associated with these five. They are:
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(1.0000,.3333,E1), ç
ABOVE(.0833), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
P<216>thv<200>li<209>ga, at, K<193><210>c<200>puram<R>ç
(in Tamil Nadu)
@Z_TBL_BODY = SPACE, TABLE TEXT, TABLE TEXT
, +, +
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
Abli<209>ga, at, Jambuke·vara<R>ç
(in Tamil Nadu)
@Z_TBL_BODY = SPACE, TABLE TEXT, TABLE TEXT
, +, +
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
Tejoli<209>ga, at, Aru<207><193>cala<R>ç
(in Tamil Nadu)
@Z_TBL_BODY = SPACE, TABLE TEXT, TABLE TEXT
, +, +
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
V<193>yuli<209>ga, at, K<193><202>ahasti<R>ç
(in Andhra Pradesh)
°k<193>·ali<209>ga, at, Cidambaram<R>ç
(in Tamil Nadu).
@Z_TBL_END = 
@SPACE1 = 
The exact reason for such classification is not known.
@NT = pa<210>cabh<220>tas
@N1 = (`the five elements')
See <MS>BH<188>TA<D>.
@NT = Pa<210>cabrahmamantras
@N1 = (`five mantras<R>ç
concerning five aspects of Brahman')
@NID = <+><+><+>Though Brahm<193>, Vi<218><207>u and Mahe·vara (or <185>iva) ç
are often described as the three aspects of the Supreme Brahman (God, ç
the Absolute), each one of them also is sometimes praised as Brahman ç
Himself.
In one such description, the five mantras on the five aspects of <185>iva ç
given in the Mah<193>n<193>r<193>ya<207>a Upani<218>ad (sections ç
17 to 21) are known as `Pa<210>cabrahma-mantras'. The five aspects ç
are: Sadyoj<193>ta, V<193>madeva, Aghora, Mah<193>deva and ®·<193>na.
Sometimes, these are shown as five faces of one and the same <185>iva.
These mantras are employed in the worship and meditation of Mah<193>deva ç
with these five faces.
@NT = pa<210>c<193>c<193>ras
@N1 = (`the five aspects of religious or spiritual conduct')
These are the five religious disciplines prescribed for everyone of ç
the V<200>ra·aiva sect.
See under <MS><185>AIVISM<D>.
@NT = pa<210>cada·<193>k<218>ar<200>-mantra
@N1 = (`mantra of<R>ç
fifteen letters or syllables')
This is a fifteen-lettered (pa<210>cada·a= fifteen) mantra or mystic ç
formula closely associated with the goddess Lalit<193> Tripura-sundar<200> ç
(an aspect of P<193>rvat<200>) and her emblem, the <185>r<200>cakra.
Actually there are two such mantras: the one attributed to the sage ç
Agastya which begins with the letter `ka' (hence the name k<193>dimata) ç
and another to his wife Lop<193>mudr<193> which begins with the letter ç
`ha' (hence the name h<193>dimata).
The mantra has to be received ceremonially from a competent guru.
It is said to be a very powerful mantra.
See  also  <MS>LALIT°<D>,  <MS><185>R®CAKRA<D>  and <MS>TANTRAS<D>.
@NT = Pa<210>cada·<200>
@N1-1 = (`[a work of] fifteen [chapters]')
All the three major schools of Ved<193>nta †Advaita, Vi·i<218><219><193>dvaita, ç
and Dvaita† though based on the prasth<193>natraya (the three basic ç
works), also have special treatises called `Prakara<207>agranthas' ç
which can be termed as textbooks of those schools.
The Pa<210>cada·<200> of Vidy<193>ra<207>ya Muni (14th century <MS>A.<|>D.<D>) ç
who was the pontiff of the <185><193>rad<193>-Ma<219>ha of <185><216><209>ger<200> ç
(in the present Karnataka State) from <MS>A.<|>D.<D> 1377 to 1386, ç
is one such work of the Advaita school. It is a voluminous work of ç
1571 verses spread out in fifteen chapters (hence the name Pa<210>cada·<200>, ç
pa<210>cada·a meaning fifteen).
These fifteen chapters have been grouped into three pentads: Vivekapa<210>caka ç
(dealing with the discrimination of the real from the unreal); D<200>papa<210>caka ç
(expounding the nature of the Self as pure consciousness) and °nandapa<210>caka ç
(dwelling on the bliss-nature of Brahman).
These three pentads have for their theme, the three aspects of Brahman, ç
viz., sat, cit and <193>nanda.
It is an elegant work written in a simple style, though dealing with ç
a tough subject.
There is only one Sanskrit commentary, T<193>tparyad<200>pik<193>, ç
by R<193>mak<216><218><207>a about whom nothing is known.
A brief account of the contents of this treatise may now be given:
@S10N = Chapter 1 (Tattvaviveka; 65 verses)
This chapter deals with the nature of the <193>tman (the Self), prak<216>ti ç
(Mother Nature), the five bh<220>tas (elements likethe earth and ç
water), pa<210>c<200>kara<207>a (quintuplication of the elements), ç
the pa<210>ca-ko·as (five sheaths) and the meaning of the mah<193>v<193>kya ç
tat tvam asi.
@S10N = Chapter 2<R>ç
(Pa<210>camah<193>bh<220>taviveka; 109 verses)
Apart from a detailed treatment of the five fundamental elements and ç
their products, this section also deals with the nature of m<193>y<193>, ç
its characteristics and effects.
@S10N = Chapter 3 (Pa<210>cako·aviveka; 43 verses)
The pa<210>cako·as or the five sheaths (like the annamayako·a or the ç
sheath of food) that cover the nature of the <193>tman, and the real ç
nature of the <193>tman as sat-cit- <193>nanda (existence-consciousness-bliss) ç
as also the ultimate identity of the j<200>v<193>tman (the individual ç
soul) with Brahman (the Supreme Soul or the Absolute) are the topics ç
discussed here.
@S10N = Chapter 4 (Dvaitaviveka; 69 verses)
Creation of the world by ®·vara (God), the relation of the j<200>va ç
(individual soul) with ®·vara as also the world, division of dvaita ç
(consciousness of duality) into two varieties, what is to be abandoned ç
and what is to be accepted†these are the subjects dealt with in this ç
chapter.
@S10N = Chapter 5 (Mah<193>v<193>kyaviveka; 8 verses)
This short chapter delineates the method of interpreting the four ç
mah<193>-v<193>kyas or `great sentences' taken from the Upani<218>ads.
@S10N = Chapter 6 (Citrad<200>pa; 290 Verses)
If the first five chapters of this work contained the suffix `viveka' ç
in their titles†because they dealt with viveka or various types of ç
discrimination that help in understanding the principles of the Advaita ç
school better†the five chapters from the 6th to the 10th, containing ç
the suffix `d<200>pa'<|>(= light or lamp) throw light on the subtler ç
aspects of the same school.
In this chapter which is quite exhaustive, comparison is made between ç
the various stages of a citra (drawing or painting) and the degrees ç
of manifestation of Param<193>tman (the Supreme Self) as cit(pure ç
consciousness), antary<193>min (the inner controller) and so on.
@S10N = Chapter 7 (T<216>ptid<200>pa; 298 verses)
This also is a long chapter. Whatever t<216>pti or satisfaction a ç
being gets in any experience, is due to the presence of the <193>tman ç
(Self) only. However, infinite t<216>pti can be got only through the ç
knowledge of Brahman.
@S10N = Chapter 8 (K<220><219>asthad<200>pa; 73 verses)
The word `k<220><219>astha' refers to the undifferentiated, pure, ç
consciousness. Just as general sunlight lights up a wall whereas the ç
same, reflected from a mirror, appears brighter, in the same way, ç
the k<220><219>astha lights up both the outside world and the buddhi ç
or the intellect. Ultimately, it is different from both the outside ç
world and the j<200>va inside, who is only a reflection of consciousness. ç
However, it should be known that this k<220><219>astha and Brahman ç
are one and the same.
@S10N = Chapter 9 (Dhy<193>nad<200>pa; 158 verses)
This chapter states that up<193>san<193> or meditation on the knowledge ç
gained through a correct understanding of the scriptures, though indirect, ç
can also lead to mok<218>a or liberation. Incidentally, the forms ç
of God such as Vi<218><207>u and so on, are accepted as real for the ç
purpose of meditation since they are sanctioned by the scriptures.
@S10N = Chapter 10 (N<193><219>akad<200>pa; 26 verses)
The lamp (= d<200>pa) in a dancing hall or the stage of a theatre, ç
lights up everything, by its mere presence. But it is not affected ç
in any way by the happenings on the stage. Similarly the real Self, ç
the <193>tman, called `s<193>k<218>icaitanya' or `witness-consciousness', ç
also reveals all the activities of the body-mind complex without itself ç
undergoing any change. This is the gist of this chapter.
@S10N = Chapter 11 (Yog<193>nanda; 134 verses)
The spiritual felicity arising out of the realisation of Brahman is ç
the subject-matter of the five chapters 11 to 15. Hence the use of ç
the word `<193>nanda' in the titles.
There is an experience of <193>nanda or bliss in the su<218>upti or ç
deep-sleep state. This also is an aspect of the bliss of Brahman. ç
Far greater is the degree of such bliss in the sam<193>dhi or superconscious ç
state. This is the gist of this chapter.
@S10N = Chapter 12 (°tm<193>nanda; 90 verses)
The concept that everyone loves or likes another person or object ç
is for hisown sake†as described by the sage Y<193>j<210>a- valkya ç
in the B<216>had<193>ra<207>yaka Upani<218>ad (4.5.6)†is expounded ç
here.
@S10N = Chapter 13 (Advait<193>nanda; 105 verses)
Brahman is <193>nanda or bliss. Jagat or the world is an apparent ç
product of that Brahman and hence is identical with It. The ·akti ç
(power) or m<193>y<193> which produces this world-appearance in Brahman ç
cannot be defined. When this world is ignored as asat (unreal), its ç
true nature as Brahman is realised.
To put it in another way, when n<193>ma (names) and r<220>pa (forms) ç
are considered as important, Brahman appears as a real jagat. When ç
they are ignored and only the basic stuff is noticed, Brahman as sat-cit-<193>nanda ç
is experienced.
@S10N = Chapter 14 (Vidy<193>nanda; 65 verses)
Vidy<193>nanda is the bliss got out of the knowledge of Brahman. It ç
has four aspects: absence of sorrow; attainment of all desires; the ç
feeling that one has fulfilled all the duties of life; the sense of ç
having achieved all that is to be achieved in life. This is the essence ç
of this chapter.
@S10N = Chapter 15 (Vi<218>ay<193>nanda; 35 verses)
Based on the statement in the B<216>had<193>ra<207>yaka Upani<218>ad ç
(4.3.32), the author accepts that the happiness (=<193>nanda) one ç
gets out of the contact of the sense organs with the sense-objects ç
is also an aspect†though a poor one†of Brahm<193>nanda or bliss of ç
Brahman. The reflection or the experience of this bliss, however, ç
depends on the degree of purity of the mind.
After describing three kinds of meditation on Brahman, the work ends ç
with a short prayer.
This voluminous treatise on Advaita Ved<193>nta is held in high esteem ç
by scholars because of its lucidity and depth.
@SPACE = 
@NT = pa<210>cagavya
@N1-1 = (`five products [derived] from a cow')
@SPACE = 
The Hindu society has been venerating the cow for over three millennia. ç
Working for the good of `go-br<193>hma<207>a,' the cows and the br<193>hma<207>as, ç
has been considered as a very pious act.
The  Hindu  dharma·<193>stras  have prescribed several pr<193>ya·cittas ç
or expiations for sins. In many of these rites consuming the pa<210>cagavya ç
finds a place, thereby reflecting the great veneration for the cow.
The pa<210>cagavya is a preparation from five (= pa<210>ca) products ç
derived from a cow (= gavya). They are: milk, curds, ghee, urine and ç
dung. The proportion in which they are mixed is 8:8:4:2:1
All these are to be taken from a kapil<193> (brown) cow. While preparing ç
it, several mantras from the <184>gveda (for e.g., 1.91.16; 4.39.6) ç
and other Vedas (for e.g., Taittir<200>ya °ra<207>yaka 10.1; V<193>jasaney<200> ç
Sa<221>hit<193> 22.1) are to be chanted. A part of it, mixed with ç
green darbha (Poa cynosuroides) is offered into fire with some more ç
Vedic mantras and the remainder is consumed with a special mantra ç
indicating the power of this pa<210>cagavya to burn up all sins.
@NT = pa<210>c<193>gnis
@N1 = (`the five fires')
See <MS>°VASATHYA<D>.
@SPACE = 
@NT = Pa<210>c<193>gnividy<193>
@N1 = (`the doctrine of the five fires')
See <MS>VIDY°S<D>.
@SPACE = 
@NT = pa<210>cajana
@N1KERN = (`five [kinds or types of] people')
@SPACE = 
This is one of the archaic words used in the Vedas, the Upani<218>ads ç
and allied literature, whose interpretations vary widely.
In the <184>gveda (10.53.4), this word forms a part of the mantra ç
to be chanted by the hot<216> priest during the Dar·ap<220>r<207>a-m<193>sa ç
sacrifice. Pa<210>cajanas are the five types of persons to whom the ç
hot<216> priest is appealing to accept his duly discharged duties. ç
They are: devas (gods); manu<218>yas (human  beings);  pit<216>s  (manes);  pa·us ç
(animals) and pak<218>is (birds).
According to another interpretation they are the members of the four ç
var<207>as† br<193>hma<207>as, k<218>attriy<193>s, vai·yas and ·<220>dras ç
†along with the ni<218><193>das (hunters).
A third interpretation is that it refers to gandharvas (a kind of ç
semigods), pit<216>s (manes), devas (gods), asuras (antigods) and ç
r<193>k<218>asas (demons).
In the B<216>had<193>ra<207>yaka Upani<218>ad (4.4.17) this word ç
has been used to indicate five kinds of beings who also are established ç
in the °tman/Brahman as their support. Here too, the interpretations ç
given by the commentators are the same as the third and the second ç
ones given above for the word in the <184>gveda.
Pa<210>cajana is also the name of a demon. See <MS>P°<178>CAJANYA<D> ç
for details.
