@NT = P<193><210>cajanya
@N1 = (`[the conch'] derived from Pa<210>cajana')
In the olden days, a ·a<209>kha or a conch was as much an appendage ç
for the k<218>attriya warriors as it was for the br<193>hma<207>as ç
in their ritualistic worship. It was used, like a horn, to blow, signifying ç
a challenge for a fight, the beginning and the end of a battle (every ç
day) and so on.
Famous warriors usually gave special names to their weapons and ·a<209>khas. ç
K<216><218><207>a's ·a<209>kha was known as P<193><210>cajanya, Yudhi<218><219>hira's ç
as Anantavijaya, Arjuna's as Devadatta and Bh<200>ma's as Pau<207><195>ra.
Pa<210>cajana was a fierce demon who lived in a miniscule form inside ç
a ·a<209>kha at the bottom of the sea. Once he abducted the only son ç
of the sage S<193>nd<200>pani and ate him up.
After  completing  their  education under S<193>nd<200>pani, when ç
K<216><218><207>a and Balar<193>ma requested him to accept their gurudak<218>i<207><193> ç
(honorarium paid generally at the end of education) he expressed a ç
desire to get back his lost son.
Coming to know all the details regarding the boy's disappearance, ç
K<216><218><207>a and Balar<193>ma dived into the sea, killed the ç
demon Pa<210>cajana, usurped the ·a<209>kha in which he was dwelling ç
and later got the boy back from Yamaloka, the world of Yama (the god ç
of death).
Since this ·a<209>kha was obtained from Pa<210>cajana, it was named ç
P<193><210>cajanya.
P<193><210>cajanya was also the name of a forest near the Raivataka ç
mountain.
@NT = Pa<210>cako·as
@N1 = (`five sheaths')
According to the Ved<193>nta philosophy, the true nature of the human ç
being†for that matter, any living being or even the whole creation†is ç
<193>tman, the Self. Though this <193>tman is ever present in us, ç
we do not feel its presence. On the other hand, we identify ourselves ç
with the body and mind, and hence, suffer. The factors responsible ç
for this hiding or covering of our true nature are five: the physical ç
body which is a product of anna or food, pr<193><207>a or the vital ç
energies responsible for the functioning of the sense-organs as also ç
other biochemical processes within the body, manas or the mind, vij<210><193>na ç
or the intellect, also called buddhi, and aj<210><193>na or basic ç
ignorance. These five are respectively called annamaya-ko·a, pr<193><207>amaya-ko·a, ç
manomaya-ko·a, vij<210><193>namaya-ko·a and <193>nandamaya-ko·a. Ko·a ç
means a sheath. Since these factors cover the <193>tman like a sheath ç
and are five in number, they are called pa<210>cako·as.
Annamaya-ko·a the first, consists of the physical body given by the ç
parents and nourished by anna or food. The five pr<193><207>as or ç
vital energies like pr<193><207>a, ap<193>na and others form the second, ç
the pr<193><207>amayako·a. Manas or the mind with its capacity for ç
cognition, will and doubts comprises the third, the manomaya-ko·a. ç
Vij<210><193>na or the intellect, with its capacity to weigh the pros ç
and cons, and come to definite conclusions is the fourth, the vij<210><193>namayako·a. ç
°nandamayako·a the fifth, is the name given to aj<210><193>na or ignorance. ç
The <193>nanda or happiness that is enjoyed during deep-sleep is due ç
to it. Hence the name.
@SPACE1 = 
Annamayako·a is the outermost cover. Pr<193><207>amayako·a is within ç
it, filling it fully and of the same form. So also manomaya, vij<210><193>namaya ç
and <193>nandamaya ko·as which succeed pr<193>namayako·a in that order, ç
fill their preceding ko·as.
By a process of negation, negating each of these ko·as as not-self, ç
one can arrive at the true Self.
@SPACE = 
@NT = pa<210>c<193>k<218>ar<200>
@N1 = (`[a mantra of] five syllables')
@SPACE = 
Meditation on the form of the i<218><219>adevat<193> (chosen deity) ç
as also the japa or repetition of the mantra (divine name or formula) ç
connected with that deity is an important and integral part of s<193>dhana ç
or spiritual practice.
Out of the several modes of designating a mantra, the one that indicates ç
the number of syllables is quite common. Thus ek<193>k<218>ar<200>, ç
pa<210>c<193>k<218>ar<200>, <218>a<195>ak<218>ar<200>, a<218><219><193>k<218>ar<200>, ç
nav<193>k<218>ar<200> and dv<193>da·<193>k<218>ar<200> represent the ç
mantras having one, five, six, eight, nine or twelve syllables.
However, some of these general terms,  due  to  constant  usage,  get ç
particularised. For instance, the pa<210>c<193>-k<218>ar<200> refers ç
to the five-syllabled mantra of <185>iva only, viz., nama·-·iv<193>ya ç
(= na-ma·-·i-v<193>-ya) (Hence it is called <185>ivapa<210>c<193>k<218>ar<200>.)
Similarly the a<218><219><193>k<218>ar<200> refers to the famous mantra ç
of N<193>r<193>ya<207>a†o<221> namo n<193>r<193>ya<207><193>ya.
By adding the letter O<221> to the five-syllabled mantra of <185>iva, ç
we get the <218>a<195>ak<218>ar<200> (= six-lettered) mantra. Both ç
these mantras of <185>iva are well-known and are widely used for japa ç
or repetition.
Since O<221> is often an integral part of most mantras (almost considered ç
as a must), even the six-syllabled mantra is considered as Pa<210>c<193>k<218>ar<200> ç
only.
It was originally discovered by the sage V<193>madeva and the chandas ç
(metre) of revelation is the Vedic pa<209>kti. Sad<193>·iva is the ç
deity.
The works on the mantras, like the tantras and pur<193><207>as, give ç
the processes of purification of oneself like a<209>gany<193>sa (of ç
limbs), karany<193>sa (of the hands) and so on as also the dhy<193>na·loka, ç
giving the details for meditation on the form of the deity.
This mantra can be repeated for the sake of mok<218>a or liberation ç
through self-purification. However it can also be repeated to get ç
one's desires fulfilled, such as long life, freedom from diseases ç
as also the troubles created by evil forces, and so on.
Such japa or repetition may run into lakhs and has to be practised ç
in places like the top of a hillock, the bank of a river or some such ç
holy place (of solitude). It must then be followed by homa (offering ç
special oblations into a duly consecrated fire), the number of oblations ç
generally being one-tenth of the number of japa.
This pa<210>c<193>k<218>ar<200> mantra has been highly eulogised in ç
<185>aivite works.
@SPACE = 
@NT = pa<210>camah<193>yaj<210>as
@N1-1 = (`five great sacrifices')
@SPACE = 
Though the Hindu scriptures have eulogised sa<221>ny<193>sa (the life ç
of a monk, a man of total renunciation and dedication to God) they ç
have also boldly declared that the g<216>hastha is the pivot of the ç
whole society since the members of all the other three <193>·ramas ç
depend upon him for their sustenance.
The life of a householder is itself a yaj<210>a or a sacrifice, for ç
the good of the whole society. As if to remind him of this, he has ç
been ordained to perform everyday, five yaj<210>as. These are collectively ç
called `pa<210>camah<193>yaj<210>as'. They are: devayaj<210>a, pit<216>yaj<210>a, ç
<216><218>iyaj<210>a, n<216>yaj<210>a and bh<220>ta- yaj<210>a.
Devayaj<210>a or sacrifice to gods like S<220>rya, Praj<193>pati and ç
Indra, is the usual daily sacrifice offered in a consecrated fire.Since ç
they give us rain, crops and prosperity they have to be satiated through ç
these oblations.
Pit<216>yaj<210>a or sacrifice to the manes (the forefathers) consists ç
in offering rice balls (called pi<207><195>a) and water (arghya). ç
By this offering they are satisfied and bless their descendants who ç
are performing this sacrifice.
<184><218>iyaj<210>a (also called brahmayaj<210>a, `brahma' meaning ç
the Vedas) is sacrifice to the <216><218>is or the sages. Since they ç
have transmitted the knowledge of the Vedas to mankind, it is the ç
householder's duty to recite the Vedas and also teach them to his ç
children and disciples. This itself is the yaj<210>a by which they ç
are pleased.
N<216>yaj<210>a and bh<220>tayaj<210>a are actually feeding hungry ç
human beings that may visit the house as also the domestic and other ç
animals.
@SPACE1 = 
By performing these five daily sacrifices, the householder is actually ç
repaying his debts to the divine beings and the society, from whom ç
he has received help and sustenance. They also help him in offsetting ç
the sin he commits (unknowingly and unwillingly) while using the five ç
implements in his house like the pestle and mortar, domestic fire, ç
grinding stone etc., wherein violence is perpetrated on life through ç
the killing of ants, worms and so on.
@NT = pa<210>camak<193>ras
@N1 = (`five items [beginning with] the letter ``ma''')
See <MS>TANTRAS.<D>
@NT = pa<210>camas
@N1 = (`[those who belong to] the fifth [caste]')
The four var<207>as (or castes) into which the Hindu society was (and ç
is) divided is well-known. Certain castes which were considered as ç
outside this category, were relegated to the `fifth' (= pa<210>cama) ç
place.
Almost all those who have been listed among the Scheduled Castes and ç
Tribes in modern India come under this category.
See <MS>CASTE SYSTEM<D>.
@NT = Pa<210>canada
@N1 = (`the [land of] five rivers')
The country Madrade·a or Ara<219><219>a was called Pa<210>canada (pa<210>ca ç
= five; nada = river) since the Sindh<220> (Indus river) and its five ç
tributaries†<185>atadr<220> (Sutlej), Vip<193>·<193> (Beas), Ir<193>vat<200> ç
(R<193>vi), Candrabh<193>g<193> (Chenab) and Vitast<193> (Jhelum)†flowed ç
through it. It roughly corresponds to themodern Punjab (of both India ç
and Pakistan).
A demon Jalandhara had his capital here (the modern Jalandhar). He ç
was later killed by Lord <185>iva.
One of the 51 <185>aktip<200><219>has (places sacred to the Divine ç
Mother) is situated here. The temple of Vi·vamukhi houses the goddess.
@NT = Pa<210>c<193>nana
@N1 = (`the Five-faced One)
Comparable to the vy<220>has or emanations of Lord Vi<218><207>u, ç
is the Pa<210>c<193>nana form of Lord <185>iva. Pa<210>c<193>nana ç
or the five-faced one represents the five aspects of <185>iva vis-a-vis ç
the created universe. The five faces are respectively ®·<193>na, Tatpuru<218>a, ç
Aghora, V<193>madeva and Sadyoj<193>ta. The face ®·<193>na turned ç
towards the zenith, represents the highest aspect and is also called ç
Sad<193>·iva. On the physical plane, it represents the power that ç
rules over ether or sky and on the spiritual plane, it is the deity ç
that grants Mok<218>a or liberation. Tatpuru<218>a facing east, stands ç
for the power that rules over air and represents the forces of darkness ç
and obscuration on the spiritual plane. Aghora, facing south and ruling ç
over the element fire, stands for the power that absorbs and renovates ç
the universe. V<193>madeva facing north, ruling over the element water, ç
is responsible for preservation. Sadyoj<193>ta, facing west represents ç
the power that creates.
Iconographical works describe Pa<210>c<193>nana (<185>iva) as five-faced ç
and ten-armed. He has fifteen eyes. Seated on a bull he wears an elephant's ç
hide round his waist and a tiger's skin as the upper garment. He has ç
an immense body and matted hair dressed up as a tall crown. He holds ç
in his hands the following objects: ·akti (a weapon), kha<219>v<193><209>ga ç
(a magical wand), tri·<220>la (trident), ak<218>am<193>l<193> (rosary), ç
abhayamudr<193> (gesture of protection), varadamudr<193> (gesture ç
of bestowal of boons), a fruit, a snake, <195>amaru (hand-drum) and ç
utpala flower.
Sinners can get their sins absolved by worshipping this aspect of ç
<185>iva.
@NT = pa<210>c<193><209>ga
@N1 = (`[the almanac which has] five limbs')
Vedic sacrifices were very common even in the most ancient period. ç
However, they had to be performed at certain timesconsidered as auspicious ç
based on the astronomical position of stars and planets.Thus evolved ç
the science of Hindu Almanac, called `pa<210>c<193><209>ga'.
Literally, the word means `five limbs'. These five limbs of the pa<210>c<193><209>ga ç
are:
1.<+>V<193>ra or day of the week.
2.<+>Tithi or lunar day.
3.<+>Nak<218>atra or the lunar mansion.
4.<+>Kara<207>a or half a tithi.
5.<+>Yoga or the time during which thesun and the moon together accomplish ç
13 degrees and 20 minutes of space.
V<193>ra is the day of the week (the solar day or the civil day). ç
A day is the period between two sunrises. This period, again, is divided ç
into ahan (= day, from sunrise to sunset) and r<193>tri (= night, ç
from sunset to sunrise). The week comprises seven days named after ç
the seven planets: bh<193>nu or the sun, soma or the moon, ma<209>gala ç
or the mars, budha or the mercury, guru or the jupiter, ·ukra or the ç
venus and ·ani or the saturn.
The day and the night are further divided into 15 muh<220>rtas each, ç
a muh<220>rta having a duration of 48 minutes. Half a muh<220>rta ç
is called gha<219>ik<193> (= 24 minutes).
Tithi is one lunar day. It is defined as the day in which the moon, ç
leaving the sun (at the last moment of am<193>v<193>sy<193> or new-moon) ç
traverses twelve degrees towards the east, every day.
The tithis are counted from the day next to am<193>v<193>sya as pratipad ç
(first), dvit<200>y<193> (second), t<216>t<200>y<193> (third) and ç
so on, up to the fifteenth which is p<220>r<207>im<193> or full-moon ç
day. The same calculation is continued after that, in the same way, ç
ending with the am<193>v<193>sy<193> or the new-moon day.
The first fortnight is called ·uklapak<218>a (bright fortnight) and ç
the second, k<216><218><207>apak<218>a (dark fortnight). Consequently ç
a tithi has to be qualified by this also. For instance, the fourth ç
day after am<193>v<193>sy<193> is ·ukla-caturth<200>. The eighth day ç
after p<220>r<207>im<193> is k<216><218><207>a-a<218><219>am<200>.
Though the exact duration of a lunar day is of 60 gha<219>ik<193>s ç
(equal to 24 hours), the motion of the moon being irregular, this ç
traversing of twelve degrees varies from 54 to 65 gha<219>ik<193>s. ç
Consequently there may be two tithis on the same unit day or the same ç
tithi can extend over two unit days.
Nak<218>atra (= star or constellation) is actually the lunar mansion. ç
It is the name of <P8L><$E1 over 27><P255D><|> part of the path of ç
the moon round the earth which comes to <P8L>13<P7W1><|><P8L><$E1 over ç
3><|><P7W1> <P255D>degrees of the sky. Though the moon travels through ç
a little less than one nak<218>atra everyday, the day can be called ç
as having that nak<218>atra for that day. The nak<218>atra in its ç
turn is named after a prominent star or constellation nearby.
@SPACE1 = 
Twenty-seven nak<218>atras (from A·vin<200> to Revat<200>) have been ç
recognised by the astronomical works and incorporated into the pa<210>c<193><209>gas ç
also. (See <MS>NAK<186>ATRA<D> for details.)
The next item is kara<207>a. It is half of a tithi. Hence there are ç
60 kara<207>as in a lunar month of 30 tithis.
The kara<207>as are only of astrological use and have been given different ç
names which are eleven in number. Out of them seven are cara (= moving) ç
and four are sthira (= stationary).
The cara-kara<207>as are: bava, b<193>lava, kaulava, taitila, gara, ç
va<207>ija and vi<218><219>i.
The sthira-kara<207>as are: ·akuni, catu<218>p<193>da, n<193>ga and ç
ki<221>stughna.
In a lunar month there are two pak<218>as or fortnights (·ukla and ç
k<216><218><207>a). In each pak<218>a, on each of the days (like pratipad, ç
dvit<200>y<193> and so on) there are two kara<207>as. The sthira-kara<207>as ç
come only at the end of the k<216><218><207>apak<218>a whereas the ç
cara-kara<207>as rotate in both the pak<218>as, the series of seven ç
getting repeated. For instance, after vi<218><219>i (also known as ç
bhadra or kaly<193><207><200>) come bava, b<193>lava and so on.
The following table gives an idea as to how many times these cara-kara<207>as ç
occur in a lunar month:
@Z_TBL_BEG = COLUMNS(9), DIMENSION(IN), COLWIDTHS(.7067,E1,E1,E1,E1,E1,E1,E1,.1667), ç
KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE ç
TEXT, TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE TEXT
bava, 2, <+>9, 16, 23, 30, 37, 44, 51
b<193>lava, 3, 10, 17, 24, 31, 38, 45, 52
kaulava, 4, 11, 18, 25, 32, 39, 46, 53
taitila, 5, 12, 19, 26, 33, 40, 47, 54
gara, 6, 13, 20, 27, 34, 41, 48, 55
va<207>ija, 7, 14, 21, 28, 35, 42, 49, 56
vi<218><219>i, 8, 15, 22, 29, 36, 43, 50, 57
@Z_TBL_END = 
@SPACE1 = 
The numbers indicate the serial number in the series (1-60 kara<207>as).
The sthira-kara<207>as get the numbers as follows: ·akuni (58); catu<218>p<193>da ç
(59); n<193>ga (60); ki<221>stughna (1).
Works on astrology indicate what type of actions can be performed ç
and what should not be done when these kara<207>as occur. For instance, ç
bava is auspicious for religious acts that conduce to good health; ç
taitila for building a house.
The seventh kara<207>a vi<218><219>i is consi-dered as terrible and ç
forbidden for all auspicious acts.
The last item yoga is defined as the time taken by the sun and the ç
moon together to traverse 13<F20W1><198><F255D> 20' of space.
When this amounts to 13<F20W1><198><F255D> 20', the yoga called vi<218>kambha ç
ends. When it is 26<F20W1><198><F255D> 40', the second yoga called pr<200>ti ç
ends and so on.
There are 27 yogas (making a total of 360<F20W1><198><F255D>) each of which ç
is given a separate name. These very names describe their nature also. ç
For example: ·<220>la, the 9th yoga is like a spear. <185>obhana, ç
the 5th is auspicious. Each yoga is said to be presided over by a ç
deity. For instance: vi<218>kambha (1st) by Yama; pr<200>ti (2nd) ç
by Vi<218><207>u; siddhi (16th) by Ga<207>e·a and so on.
Nine of these yogas like parigha (19th), vyat<200>p<193>ta (17th) ç
and vidh<216>ti (27th) are considered very inauspicious and hence ç
condemned.
The system of yoga is said to be very ancient.
@SPACE1 = 
There are numerous pa<210>c<193><209>gas in vogue today, being followed ç
by the various sections of the Hindu society. Though scientific-minded ç
astronomers like Var<193>ha-mihira (<MS>A.<|>D.<D> 505-587) tried to ç
update their works to accord with the actual positions of the stars ç
and the planets during their times, others do not seem to have done ç
it. As a result, several anomalies have crept into the present-day ç
pa<210>c<193><209>gas. For instance the Makara Sa<209>kr<193>nti (the ç
date of the sun leaving the zodiacal sign Dhanus or Sagittarius and ç
entering the sign Makara or Capricorn) is being celebrated on the ç
14 January every year, though the actual transit takes place on the ç
21st December itself, thus pushing it forward by 23 days!
The Government of India appointed a committee called the Calendar ç
Reform Committee in <MS>A. D.<D> 1952, with Dr. Meghan<193>d Saha ç
(<MS>A.<|>D.<D> 1893-1956) as its chairman. After examining all the ç
existing calendars, the committee submitted its proposals in November ç
1955 for an accurate and uniform calendar for the whole of India. ç
The proposals covered both the civil calendar and the religious calendar.
The  following  are  the  important recommendations of the committee:
1)<+>The <185>aka era should be used in the unified national calendar. ç
The <185>aka year 1876 corresponds to 1954-55 <MS>A.<|>D.<D>
2)<+>The year should start from the day following the vernal equinox ç
day.
3)<+>Normal year is to consist of 365 days, while a leap year would ç
have 366 days. After adding 78 to the <185>aka era year, if the sum ç
is divisible by 4, then it would be a leap year. But when the sum ç
becomes a multiple of 100, it would be a leap year only when it is ç
divisible by 400; otherwise it would be a common year.
4)<|>Caitra (or Chaitra as often written) should be the first month ç
of the year and the lengths of the different months should be fixed ç
as follows:†
@SPACE1 = 
Caitra†30 days
   (31 days in a leap year).
Vai·<193>kha†31 days.
Jye<218><219>ha†31 days.
°<218><193><195>ha†31 days.
<185>r<193>va<207>a†31 days.
Bh<193>drapada†31 days.
°·vina†30 days
K<193>rttika†30 days.
M<193>rga·<200>r<218>a†30 days.
Pau<218>a†30 days.
M<193>gha†30 days.
Ph<193>lguna†30 days.
@SPACE = 
The dates of the reformed Indian calendar would thus have a permanent ç
correspondence with the Gregorian calendar. The corresponding dates ç
would be:
@SPACE = 
@L2 = Hindu	Gregorian
@L2 = Caitra 1	March 22 in a<R>ç
	common year and<R>ç
	21 in a leap year.
@L2 = Vai<218><193>kha 1	April 21.
@L2 = Jye<218><219>ha 1	May 22.
@L2 = °<218><193><195>ha 1	June 22.
@L2 = <185>r<193>va<207>a 1	July 23.
@L2 = Bh<193>drapada 1	August 23.
@L2 = °·vina 1	September 23.
@L2 = K<193>rttika 1	October 23.
@L2 = M<193>rga·<200>r<218>a 1	November 22.
@L2 = Pau<218>a 1	December 22.
@L2 = M<193>gha 1	January 21.
@L2 = Ph<193>lguna 1	February 20.
@SPACE = 
Unfortunately however, it did not gain popular acceptance due to the ç
people being habituated to the old and traditional almanacs.
@NT = pa<210>c<193><209>ga·uddhi
@N1 = (`holy period according to the pa<210>c<193><209>ga or almanac')
Any auspicious rite should be performed when all the five aspects ç
dealt with in a pa<210>c<193><209>ga (Hindu almanac) are deemed as ç
auspicious. This is pa<210>c<193><209>ga-·uddhi.
These five aspects have been dealt with in detail in <MS>PA<178>C°<177>GA<D>.
@NT = pa<210>capr<193><207>as
@N1 = (`the five vital-airs')
See <MS>PR°ØA<D>.
@SPACE = 
@NT = P<193><210>car<193>tra °gamas
@N1-1 = (`<193>gamas belonging to the P<193><210>car<193>tra school')
@SPACE = 
@SB = Introduction
°gamas are a special class of Hindu religio-philosophical literature ç
handed down through a succession of teachers from the most ancient ç
days.
Whether they represented a system parallel to and separate from the ç
Vedic traditions or a continuation of the same and rooted in them, ç
has been a subject of discussion among the scholars.
However, Y<193>mun<193>c<193>rya (<MS>A.<|>D.<D> 918-1038) in his scholarly ç
work, the °gama-pr<193>m<193><207>ya, has conclusively established ç
their affinity with the Vedas.
Of the three kinds of <193>gamas†the <185>aiva, the <185><193>kta ç
(or the tantra) and the Vai<218><207>ava†the P<193><210>car<193>tra ç
°gamas belong to the last group.
The other branch of the Vai<218><207>av<193>gamas is the Vaikh<193>nasa ç
°gama or the Vaikh<193>nasa S<220>tras.
@SB = Derivation of the Name
The literal meaning of the word `P<193><210>car<193>tra' means `that ç
which is connected with five nights'.
Lord Ke·ava (Vi<218><207>u or N<193>r<193>ya<207>a) is said to have ç
taught this esoteric science to Ananta, Garu<195>a, Vi<218>vaksena, ç
Brahm<193> and Rudra, over five nights (pa<210>ca = five; r<193>tra ç
= night).
The word r<193>tra also means j<210><193>na, knowledge or wisdom. ç
Since it teaches five kinds of knowledge it is called P<193><210>car<193>tra. ç
These are: tattva (cosmology); muktiprada (that which gives mukti ç
or liberation); bhaktiprada (that which confers devotion); yaugika ç
(yoga);  vai<218>ayika  (objects  of desire).
Or, alternatively, since it teaches about the five aspects of God ç
(called Puru<218>ottama) viz., para (highest), vy<220>ha (emanation),  vibhava  (an  incarnation), ç
antary<193>min (indweller) and arc<193> (form for worship), it is ç
called `P<193><210>car<193>tra'.
@SPACE = 
@SB = P<193><210>car<193>tra Literature
@SPACE = 
The P<193><210>car<193>tra literature is very vast, The total number ç
of works†generally called `sa<221>hit<193>' or `tantra'†exceeds two ç
hundred, as per the lists given in various works, though only a few ç
have been printed. Quite a few are in the form of manuscripts preserved ç
in oriental libra-ries. Many others are not available in any form ç
though their names are mentioned in other works.
The following is a list of the works as available now, along with ç
a very brief summary of each.
@S10 = 1.	Ahirbudhnya Sa<221>hit<193>
This is a fairly voluminous work with 3880 verses in 60 chapters. ç
The speciality of this work is that it deals with the four vy<220>has ç
or emanations of the Lord, description of several mantras (sacred ç
syllables) and yantras (magical diagrams) as also rituals for curing ç
diseases. (See <MS>AHIRBUDHNYA SA<189>HIT°<D> for details.)
@S10 = 2.	Aniruddha Sa<221>hit<193>
Also   called   Aniruddhasa<221>hit<193>- mahopani<218>ad, it has ç
34 chapters dealing entirely with the descriptions of various rituals, ç
methods of initiation, pr<193>ya·cittas or expiations for sins, rules ç
for making and installing the images of gods and other similar topics.
@S10 = 3.	Haya·<200>r<218>a Sa<221>hit<193>
A fairly exhaustive work in 144 chapters, distributed among four K<193><207><195>as ç
orsections†Prati<218><219>h<193>k<193><207><195>a, Sa<209>kar<218>a<207>a- ç
k<193><207><195>a, Li<209>gak<193><207><195>a and Saurak<193><207><195>a†it ç
deals primarily with the rituals concerning the installation of images ç
of various minor deities as also the methods of preparing them.
@S10 = 4.	®·vara Sa<221>hit<193>
It is a work of 24 chapters of which sixteen deal with ritualistic ç
worship. Other subjects treated in this work are: description of images, ç
methods of d<200>k<218><193> or spiritual initiation, practice of ç
meditation, details regarding mantras, methods of self- control and ç
the greatness of the Y<193>dava Hill (now known as `Melko<219>e', ç
a Vai<218><207>ava pilgrim centre on a hillock near Mysore, Karnataka ç
State).
@S10 = 5.	Jay<193>khya Sa<221>hit<193>
This work is one of the three cardinal texts of the P<193><210>car<193>tra ç
literature. It has thirty-three pa<219>alas or chapters and deals ç
with the following topics: detailed account of creation; yog<193>bhy<193>sa ç
(practice of yoga) and mantrop<193>san<193> (spiritual practice through ç
the repetition of mantras or sacred formulae); various Vai<218><207>ava ç
mantras; p<220>j<193> (ritualistic worship) and homa (fire ritual); ç
d<200>k<218><193> (initiation); temples and worship therein; <193>c<193>ras ç
(the codes of conduct) for the vai<218><207>avas; and, pr<193>ya·cittas ç
or expiations for sins.
@S10 = 6.	K<193>·yapa Sa<221>hit<193>
This is a comparatively small work in twelve chapters. It deals mainly ç
with poisons and methods of remedy by suitable mantras or incantations.
@S10 = 7.	Mah<193>-sanatkum<193>ra Sa<221>hit<193>
This is a voluminous work of ten thousand verses spread over forty ç
sections in four chapters. It deals entirely with rituals of worship.
@S10 = 8.	P<193>dma Sa<221>hit<193>
A work dealing mainly with rituals and chanting of mantras, this work ç
is in thirty-one chapters.
@S10 = 9.	Parama Sa<221>hit<193>
A work in thirty-one chapters, it deals with the following topics: ç
process of creation; rituals of initiation and worship; yoga classified ç
as J<210><193>nayoga and Karmayoga.
It declares that J<210><193>nayoga which includes  pr<193><207><193>y<193>ma  and  sam<193>dhi  is ç
superior to Karmayoga. Karmayoga seems to mean ritualistic worship ç
of Vi<218><207>u.
@S10 = 10.	P<193>rame·vara Sa<221>hit<193>
A short work in fifteen chapters, it deals with meditation on mantras, ç
sacrifices and methods of rituals as also pr<193>ya·cittas or expiations.
@S10 = 11.	Par<193>·ara Sa<221>hit<193>
A concise work in eight chapters, it deals with the methods of japa ç
or the muttering of the name of God.
@S10 = 12.	Pau<218>kara Sa<221>hit<193>
Considered as one of the earliest works of the P<193><210>car<193>tra ç
system, the Pau<218>kara Sa<221>hit<193> consists of forty-three ç
chapters. Apart from dealing with various kinds of image-worship, ç
it also contains certain philosophical views. It is interesting to ç
note that some<|>funeral<|>sacrifices<|>also<|>find a place<|>here.
@S10 = 13.	Sudar·ana Sa<221>hit<193>
A treatise comprising forty-one chapters, it deals mainly with meditation ç
on mantras and expiations for sins.
@S10 = 14.	Vihagendra Sa<221>hit<193>
It is in twenty-four chapters. Apart from meditation on mantras, it ç
deals with sacrificial oblations. In the twelfth chapter, the topic ç
of pr<193><207><193>y<193>ma, as a part of the process of worship, ç
is also described extensively.
@S10 = 15.	Vi<218><207>u Sa<221>hit<193>
A work in thirty chapters, it also deals mainly with ritualistic worship. ç
Its philosophy is akin to that of S<193><209>khya Dar·ana with some ç
variations like the puru<218>a (the individual soul) being all- pervading ç
and that he activates the prak<216>ti to evolve into the world.
@S10 = 16.	Vi<218><207>utattva Sa<221>hit<193>
Comprising thirty-nine chapters, it deals with image-worship, ablutions ç
and wearing of the vai<218><207>ava marks and some purificatory rites.
@SB = Philosophy of the P<193><210>car<193>tra °gamas
The philosophy of this system has been expounded in the Jay<193>khya ç
Sa<221>hit<193> in detail. A brief summary of the same will be given ç
here.
Though yaj<210>a (Vedic sacrifices), d<193>na(giving gifts), sv<193>dhy<193>ya ç
(study of the Vedas) and other similar religious disciplines are useful ç
in spiritual life, it is only j<210><193>na (knowledge) of the paratattva ç
or the Highest Reality that can really give mok<218>a.
This paratattva (God) is the same as the Brahman of the Vedas and ç
the Upani<218>ads. He is of the nature of pure consciousness (cit) ç
and bliss (<193>nanda). He is an<193>di and ananta (without beginning ç
or end). He is the substratum and support of the whole universe. Though ç
he is beyond all gu<207>as, he is also the bhokt<216> (experiencer, ç
enjoyer) of all that is born out of the gu<207>as. He is sarvaj<210>a ç
(omniscient) and sarva·akta (omnipotent). He is both transcendent ç
and immanent with regard to this created universe. Hence he is too ç
subtle to be perceived by the senses or the mind. However he can be ç
realised through the pure mind. This is called `m<193>nasika-pratyak<218>a'.
The J<200>vas, when they realise this Brahman or God, appear to have ç
become one with him, but do maintain a subtle distinction also from ç
him. Hence this philosophy can be called `bhed<193>bheda' or `dvait<193>dvaita'.
As regards s<216><218><219>i or creation, three kinds of it are recognised: ç
Brahmasarga, Prak<216>tisarga and <185>uddhasarga.
Brahmasarga is the projection of the four-faced Brahm<193> from Vi<218><207>u ç
and the creation of the world by Brahm<193>.
Prak<216>tisarga is similar to the creation as described in the S<193><209>khya ç
philosophy. Prak<216>ti or pradh<193>na comprises the three well-known ç
gu<207>as†sattva, rajas and tamas.
@SPACE1 = 
The first product of the evolution of pradh<193>na when sattva is ç
predominant, isbuddhi (cosmic intellect). The second product when ç
rajas has gained the upper hand, is aha<209>k<193>ra (egoism). This ç
is of three types: prak<193>·<193>tma or taijas<193>tma; vik<216>t<193>tma; ç
bh<220>t<193>tma. The first gives rise to the five j<210><193>nendriyas ç
(organs of know-ledge) and the mind. The second produces the five ç
karmendriyas (organs of action). From the last evolve the s<220>k<218>mabh<220>tas ç
or tanm<193>tras (the five subtle elements). These then create the ç
five gross elements. The whole creation comes out of a combi-nation ç
of these basic products.
The puru<218>as or j<200>vas (souls) get associated with the bodies ç
in accordance with their karma, due to the will of God. Their association ç
with the inert bodies makes the latter appear as conscious even as ç
an iron piece acts like a magnet in the vicinity of a powerful magnet.
The <185>uddhasarga is the third creation. Here, God†called Puru<218>ottama ç
V<193>sudeva†evolves from out of himself three subsidiary agents or ç
forms: Acyuta, Satya and Puru<218>a. These forms in reality are non-different ç
from him. The third form†Puru<218>a†acts as the antary<193>min or ç
the inner controller. It is he who inspires all the gods to work. ç
It is he who binds the j<200>vas with v<193>san<193>s (residual impressions) ç
and again, it is he who inspires them to do s<193>dhanas (spiritual ç
disciplines) to get out of the bondage of v<193>san<193>s.
@SPACE1 = 
The m<193>y<193> (delusion) power of God makes the j<200>vas (through ç
v<193>san<193>s or past impressions) get identified with the body-mind ç
complex. This association of the v<193>san<193>s is an<193>di or beginningless. ç
However, by the grace of God, the antary<193>min or theindwelling ç
power and spirit, the j<200>va awakens to true knowledge and gets ç
liberated from all the shackles.
The path to this mok<218>a or liberation starts with the inspiration ç
by God for the j<200>va to search out a great guru or spiritual preceptor. ç
This guru gives the disciple mantrad<200>k<218><193> (initiation with ç
a holy name or syllable). Regular and steady practice of the mantrajapa ç
(repetition of the divine name) results in sam<193>dhi or total absorption ç
in God.
@NID = <+><+><+>The up<193>san<193> or meditation on God has two stages. ç
The first is called `kriy<193>khya'. It is in the form of practising ç
various virtues like ·auca (cleanliness), yaj<210>a (sacrifices), ç
tapas (austerity), adhyayana (studying the scriptures), ahi<221>s<193> ç
(not harming others), satya (truth), karu<207><193> (compassion), ç
d<193>na (giving gifts) and s<%30>o<%0>on.
The second is called `satt<193>khya' or `j<210><193>n<193>khya'. It ç
is practically the same as J<210><193>nayoga. The mind purified by ç
the practice of kriy<193>khya is now able to meditate on the <193>tman ç
inside, which results in the experience of unitive consciousness  that  j<210><193>t<216>  (knower),  j<210>eya ç
(object to be known) and j<210><193>na (knowledge) are all one and ç
the same.
The P<193><210>car<193>tra °gamas†especially the Jay<193>khya Sa<221>hit<193>†describe ç
two types of yogas: mantradhy<193>na and yog<193>bhy<193>sa.
The former consists of meditation on God with form along with the ç
repetition of appropriate mantras. The latter is almost the same as ç
the Yoga of Pata<210>jali (200 <MS>B.C.<D>).
A special contribution of the P<193><210>ca-r<193>tra °gamas to ç
the religio-philosophical literature of Hinduism is the concept ofthe ç
Vy<220>has which are four. (Hence the name `Caturvy<220>has,' `catur' ç
meaning `four'.)
@SPACE1 = 
`Vy<220>ha' means a projection or an emanation.
In this system, the various names by which God the Supreme is known ç
are: Param<193>tman, N<193>r<193>ya<207>a, Vi<218><207>u, Bhagav<193>n ç
and V<193>sudeva.
`Bhaga' means <218>a<195>gu<207>as or the group of six blessed qualities. ç
They are: j<210><193>na (knowledge); ai·varya (lordship); ·akti (ability, ç
potency); bala (strength); v<200>rya (virility, unaffectedness) and ç
tejas (splendour).
Since God†more commonly known as V<193>sudeva in this system†has all ç
these gu<207>as or attributes in the fullest measure, he is called ç
`Bhagav<193>n'.
By the will of Bhagav<193>n V<193>sudeva (the first or the original ç
Vy<220>ha) the second Vy<220>ha, Sa<209>kar<218>a<207>a (or Balar<193>ma) ç
emerges. From Sa<209>kar<218>a<207>a emanates Pradyumna and from him, ç
Aniruddha.
Though the latter three Vy<220>has are also, in essence, equal to ç
V<193>sudeva, they manifest only two of the six gu<207>as prominently, ç
the other four being in a latent condition.
If in Sa<209>kar<218>a<207>a, j<210><193>na and bala are predominant, ç
Pradyumna manifests ai·varya and v<200>rya more prominently. Aniruddha, ç
on the other hand, exhibits ·akti and tejas to a much greater degree.
Each of the Vy<220>has is credited with two activities, a creative ç
and a moral one.
Each of the Vy<220>has, again, gives rise to three more sub-Vy<220>has, ç
making a total of twelve emanations. They are: Ke·ava, N<193>r<193>ya<207>a, ç
M<193>dhava, Govinda, Vi<218><207>u, Madhus<220>dana,   Trivikrama,   V<193>mana, ç
<185>r<200>dhara, H<216><218><200>ke·a, Padman<193>bha and D<193>modara.
@SPACE1 = 
These twelve are considered as the m<193>s<193>dhipas or the adhidevat<193>s ç
(tutelary deities) of the twelve lunar months. They are also offered ç
arghya (ceremonial water) in ritualistic worship.
Iconographically, all of them are identical except for the arrangement ç
of the four emblems of Vi<218><207>u†·a<209>kha (conch), cakra (discus), ç
gad<193> (mace) and padma (lotus)†in the four hands.
@SB = Conclusion
The P<193><210>car<193>tra °gamas are a conti-nuation of the Vedic ç
tradition. They also expand and expound the concepts about God and ç
devotion.
Apart from s<216><218><219>i (creation), sthiti (sustenance) and pralaya ç
(dissolution) of the world, God discharges two more functions:   nigraha   (controlling   and ç
punishing the evil-doers) and anugraha (showering his blessings on ç
those who lead a good life and are devoted to him).
If the doctrine of bhakti or devotion and prapatti or self-surrender ç
find an important place in this system, no less is the attention paid ç
to rituals, worship, images of deities and temples as also several ç
mantras, the repetition of which will confer many a blessing on the ç
votaries.
Thus the P<193><210>car<193>tra °gamas have contributed considerably ç
towards practical Hinduism. Even today, most of the Vai<218><207>ava ç
temples, especially in South India, follow their dictates, thus keeping ç
those traditions alive.
@SPACE = 
@NT = pa<210>casa<221>sk<193>ras
@N1 = (`five rites of<R>ç
reformation')
@SPACE = 
The Hindus can generally be divided into three broad groups: the ·aivas ç
(worshippers of <185>iva and allied deities like Ga<207>apati and ç
Subrahma<207>ya), the ·<193>ktas (worshippers of the Mother-goddess) ç
and the vai<218><207>avas (worshippers of Vi<218><207>u and his various ç
aspects).
Among the br<193>hma<207>a followers of Vai<218><207>avism, there ç
are two prominent groups: the ·r<200>vai<218><207>avas and the vai<218><207>a-vas. ç
The former are the followers of R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137) ç
whereas the latter are of Madhva (<MS>A.<|>D.<D> 1238-1317).
Every ·r<200>vai<218><207>ava is expected to undergo five purificatory ç
sacraments known as the pa<210>casa<221>sk<193>ras. These help him ç
to become fit enough to worship God.
They  are:  t<193>pa,  pu<207><195>ra,  n<193>ma, mantra and y<193>ga.
T<193>pa is also called `taptamudr<193>-dh<193>ra<207>a'. It is branding ç
one's arms with the marks of ·a<209>kha (conch) and cakra (discus), ç
the two important symbols of Lord Vi<218><207>u. The permanent marks ç
left on the body can constantly remind him that he now belongs to ç
Lord Vi<218><207>u.
Pu<207><195>ra is the religious mark†one U-line in white clay with ç
a red line of vermillion or turmeric powder in between. This gives ç
him a sense of belonging to the <185>r<200>vai<218><207>ava sect and ç
also reminds him about the spiritual disciplines he has to follow, ç
since this mark represents the three famous n<193><195><200>s†i<195><193>, ç
pi<209>gal<193> and su<218>umn<193>†described in the treatises on ç
yoga.
N<193>ma is the acceptance of a new name for himself such as K<216><218><207>ad<193>sa ç
or Vi<218><207>ud<193>sa, that signifies the beginning of a new life ç
as the servant of God.
@SPACE1 = 
Mantra is receiving through spiritual initiation from a qualified ç
guru, a well-known name of God or formula like the a<218><219><193>k<218>ar<200>, ç
for japa (repetition) and up<193>san<193> (meditation and worship).
After these four requirements are fulfilled, the s<193>dhaka or the ç
spiritual aspirant is expected to perform all his duties in a spirit ç
of sacrifice and as a worship of God. He should strictly avoid all ç
actions forbidden by the scriptures. This is called `y<193>ga'.
A person becomes a true ·r<200>vai<218><207>ava only after undergoing ç
these pa<210>ca-sa<221>sk<193>ras.
See also <MS><185>AIVISM<D> and <MS><185>R®VAI<186>ØAVISM<D>.
@SPACE = 
@NT = Pa<210>ca·ikha
@N1 = (`one with five locks of hair [on the head]')
@SPACE = 
One of the six systems of Hindu philosophy whose elements are rooted ç
in the Vedic literature, and, which is extant even today as an important ç
subject of study is the S<193><209>khya Dar·ana. This system is said ç
to have been originally taught by the sage Kapila and further expounded ç
and expanded by his disciple °suri as also his student Pa<210>ca·ikha.
One Pa<210>ca·ikha is mentioned by the Mah<193>bh<193>rata (<185><193>ntiparva, ç
219) as a teacher of the king Janaka.
He is said to have authored a voluminous work, <186>a<218><219>itantra ç
(in sixty chapters, in two parts, containing thirty two and twenty-eight ç
chapters each) which is not available now. This name might have been ç
given to that work since it was said to deal with sixty<|>(= <218>a<218><219>i) ç
topics of S<193><209>khya philosophy.
Twenty-one s<220>tras in prose have been quoted in the Vy<193>sabh<193><218>ya ç
on the Yoga-s<220>tras of Pata<210>jali (200 <MS>B.<|>C.<D>) as of ç
Pa<210>ca·ikha.
He might have lived during the first century <MS>B.<|>C.<D>
His S<193><209>khya probably represents a transitional stage from ç
that of the Upani<218>ads to that propounded by ®·vara-k<216><218><207>a ç
(<MS>A.<|>D.<D> 350) in his S<193><209>khyak<193>rik<193>.
@SPACE = 
@NT = pa<210>cat<193>la
See <MS>M<188>RTI<185>ILPA<185>°STRA<D>.
@SPACE = 
@NT = Pa<210>catantra
@N1 = (`five rules of political<R>ç
conduct')
@SPACE = 
The Pa<210>catantra is the most celebrated and interesting work ç
in Sanskrit literature, classed under the didactic fable group. It ç
comprises five books or sections (pa<210>ca = five), each dealing ç
with one par- ticular tantra or rule of political conduct.
The introductory part of the work states that it was taught by a wise ç
teacher, Vi<218><207>u·arma by name, to the idle and stupid sons of ç
a king Amara·akti of Mahilaropa, at his request. The princes very ç
soon became well-educated and well-behaved, due to the marvellous ç
effect of the tales they heard from their preceptor.
Till now, the identity of neither the teacher nor the king has been ç
determined.
The earliest edition known to us† though completely lost†is the Pehlevi ç
(language) translation by a Persian physi-cian Burzoe, at the order ç
of the king Khossu Anushirvan (<MS>A.<|>D.<D> 531-575). The text we ç
now have is based on an old Syrian version by Bud in <MS>A.<|>D.<D> ç
570 and an Arabic version by Abdallah Ibnal Mogaffa in <MS>A.<|>D.<D> ç
750. This latter work was translated into several European languages ç
during the period <MS>A.<|>D.<D> 1080 to 1678.
The Pa<210>catantra is generally assigned to the period 100 <MS>B.<|>C.<D> ç
to <MS>A.<|>D.<D> 300.
The contents of the work may be summarised as follows:
@SPACE1 = 
@S10N = 1.	Mitrabheda<R>ç
	(Breaking the Friendship)
@EMERGENCY = This deals with the policy of `divide and rule' by the ç
story of two jackals, Kara<219>aka and Damanaka, who lived happily ç
after estranging the lion and the bull who had been fast friends for ç
a long time.
@SPACE1 = 
@S10N = 2.	Mitral<193>bha<R>ç
	(Acquisition of Friends)
@EMERGENCY = This illustrates the advantages of a judicious friendship ç
by the story of the adventures of a tortoise, a deer, a crow and a ç
mouse.
@SPACE1 = 
@S10N = 3.	K<193>koluk<200>ya<R>ç
	(Tale of Crows and Owls)
@EMERGENCY = This brings out the dangers of friendship between those ç
who are natural enemies.
@SPACE1 = 
@S10N = 4.	Labdhapra<207><193>·a<R>ç
	(Loss of what has been Acquired)
@EMERGENCY = This points out, by means of the story of an ape and ç
a crocodile, how certain weaknesses lead to the loss of one's own ç
possessions.
@SPACE1 = 
@S10N = 5.	Apar<200>k<218>itak<193>ritam<R>ç
	(Results of Inconsiderate Actions)
The general principle of `haste makes waste' is illustrated through ç
a number of stories here.
@EMERGENCY = There are two distinct versions of the Pa<210>catantra ç
available now: the Tantr<193>-khy<193>yik<193> (Kashmir version) ç
in simple prose; the stories found in the Kath<193>-sarits<193>gara ç
of Somadeva and the B<216>hatkath<193>ma<210>jar<200> of K<218>emendra.
The Pa<210>catantra is one of the most translated works in world ç
literature.
See also <MS>HITOPADE<185>A<D>.
@SPACE = 
@NT = pa<210>catapas
@N1 = (`austerity involving five<R>ç
fires')
@SPACE1 = 
Tapas or austerity ia a must before embarking on any important venture ç
or even for self-purification.
One such tapas is pa<210>catapas or pa<210>c<193>gnitapas. In this ç
mode of austerity, the aspirant is to sit in the midst of four blazing ç
agnis or fires in an open place, with the sun burning above his head ç
as the fifth fire. He has to sit in their midst from dawn to dusk, ç
for a specified period, after preparing himself ceremonially as per ç
the prescribed rules.
According to some, this is a substitute for the performance of Vedic ç
sacrifices, while maintaining the duly consecrated Vedic fires.
<185>r<200> S<193>rad<193> Dev<200> (<MS>A. D.<D> 1853-1920) the consort ç
of R<193>mak<216><218><207>a Paramaha<221>sa (<MS>A.D.<D> 1836-1886) ç
is known to have performed this tapas in <MS>A. D.<D> 1893.
@SPACE = 
@NT = pa<210>catattvas
@N1 = (`five basic principles')
@SPACE1 = 
They are the same as the `pa<210>cama-k<193>ras'. See <MS>TANTRAS<D>.
They may also be the five elements †also called `pa<210>cabh<220>tas'†viz., ç
p<216>thv<200> (earth), ap (water), tejas (fire), v<193>yu (air) and ç
<193>k<193>·a (ether).
@SPACE = 
@NT = Pa<210>cava<219><200>
@N1 = (`a grove of five trees')
@SPACE1 = 
During the last phase of his sojourn through the Da<207><195>ak<193>ra<207>ya ç
forest, R<193>ma requested the sage Agastya to suggest a good place ç
in the forest where he could build a nice cottage and live like a ç
recluse performing his duties. The sage in his reply (vide Ara<207>yak<193><207><195>a ç
13.13) suggested a place called Pa<210>cava<219><200> near the God<193>var<200> ç
river.
R<193>ma, along with S<200>t<193> and Lak<218>ma<207>a, repaired to ç
that place, built a beautiful cottage and started living there.
It was here that the lustful demoness <185><220>rpa<207>akh<193> was ç
deformed by Lak<218>ma<207>a and the demons Khara and D<220><218>a<207>a ç
along with their army were decimated by R<193>ma. Again, it was from ç
here that S<200>t<193> was abducted by the demon-king R<193>va<207>a.
It was called Pa<210>cava<219><200> because it was a grove containing ç
five (= pa<210>ca) banyan (= va<219>a) trees.
As per another view, the five specific trees are: a·vattha (Ficus ç
religiosa), bilva (Aegle marmelos), va<219>a (Ficus indica), ç
dh<193>tr<200> (Flacourtia cataphracta) and a·oka (Saraca indica).
According to one legend, five arrogant gandharva youths once surrounded ç
the sage Agastya and did not allow him to move about. He then cursed ç
them to become trees. On their repentance and begging for pardon, ç
he assured them of liberation from that condition when R<193>ma would ç
come and build his hermitage in their midst.
It has now been identified with a place near N<193>sik (in Maharashtra) ç
on the bank of the river God<193>var<200>.
@SPACE1 = 
Pa<210>cavat<200> is also the name of a group of five big trees in ç
Dak<218>i<207>e·var (in Calcutta, now, Kolkata) under which the modern ç
saint R<193>mak<216><218><207>a Paramaha<221>sa (<MS>A.<|>D.<D> 1836-1886), ç
performed many auste-rities.
@NT = Pa<210>cavi<221>·a Br<193>hma<207>a
The T<193><207><195>ya Mah<193>br<193>hma<207>a of the S<193>maveda ç
is known by this name since it has pa<210>cavi<221>·a or twenty-five ç
chapters.
See <MS> T°Ø£YA  MAH°BR°HMAØA<D>  for details.
@NT = pa<210>cayaj<210>as
@N1 = (`the five [daily] sacrifices')
See <MS>PA<178>CAMAH°YAJ<178>AS<D>.
@NT = pa<210>c<193>yatanap<220>j<193>
@N1 = (`worship of five<R>ç
deities')
The <184>gveda (1.164.46) declares that `Sat' or the Truth (= God, ç
the Absolute) is one, but sages designate it by various names. Hence ç
the various deities of the Hindu pantheon should be looked upon as ç
various facets of one and the same God, generally called Brahman or ç
Param<193>tman, in the Hindu scriptures.
These deities can be classified into five groups, each group representing ç
diffe-rent aspects of one principal god. They are: Vi<218><207>u, ç
<185>iva, Dev<200>, Ga<207>apati and S<220>rya.
Gradually, various sects and cults grew round these deities. The votaries ç
of these sects, forgetting the <184>gvedic dictum and the philosophy ç
of the one Supreme Being, became mutually exclusive or even hostile.
To rectify their attitude and put them back on the right track, <185>a<209>kara ç
(<MS>A.<|>D.<D> 788-820) is said to have evolved a method for harmonising ç
them all. The result was pa<210>c<193>yatanap<220>j<193> or worship ç
of all the five deities simultaneously, keeping the i<218><219>a-devat<193> ç
(chosen deity of the worshipper) in the centre and the other four ç
in the four corners of a square.
The  diagram  shown  below  gives details of such arrangements:
These five deities may be worshipped either in their images of small ç
size or through symbolic objects such as ·<193>lagr<193>ma (round ç
black stone) for Vi<218><207>u, b<193><207>ali<209>ga (of white quartz) ç
for <185>iva, metallic stone for Dev<200>, red stone for Ga<207>apati ç
and spha<219>ika (crystal) for S<220>rya. Geometrical drawings (yantra) ç
like square, hexagon or circle are also sometimes used to represent ç
these deities.
These five deities are represented as associated with the five cosmic ç
elements:
Ga<207>apati with earth;
<185>iva with water;
Dev<200> with fire;
S<220>rya with air;
Vi<218><207>u with ether.
See also <MS>DEVAP<188>J°.<D>
@NT = pa<210>c<200>kara<207>a
@N1 = (`the process of<R>ç
quintuplication')
This is a technical term specially found in the treatises on Advaita ç
Ved<193>nta.
The process by which each of the pa<210>camah<193>bh<220>tas (five ç
great elements) is formed out of the pa<210>catanm<193>tras (five ç
primordial elements) is called `pa<210>c<200>-kara<207>a'. Each former ç
element†because of this†contains half of the corresponding tanm<193>tra ç
and one-eighth of each of the other four. For instance, one unit of ç
the mah<193>bh<220>ta p<216>thv<200> = 1/2 p<216>thv<200> tanm<193>tra ç
+ 1/8 of ap tanm<193>tra + 1/8 of agni tanm<193>tra + 1/8 of v<193>yu ç
tanm<193>tra + 1/8 of <193>k<193>·a tanm<193>tra. Because of this ç
pa<210>c<200>kara<207>a, each of the mah<193>bh<220>tas contains a ç
part of the other four bh<220>tas and hence their characteristics.
@NT = pa<210>copac<193>ras
@N1 = (`the five upac<193>ras or<R>ç
modes of service')
In p<220>j<193> or ritualistic worship of a deity, the upac<193>ras ç
or direct modes of offering are important. They may generally be five ç
or ten or sixteen.
When they are five, they are called `pa<210>copac<193>ras' (pa<210>ca ç
= five).
They are: gandha (sandal-paste); pu<218>pa (flowers along with bilva ç
and tulas<200> leaves as also d<220>rva or grass); dh<220>pa (incense); ç
d<200>pa (lighted lamp for waving before the deity) and naivedya (food- ç
offering).
See also <MS>DEVAP<188>J°<D>.
