@NT = pa<210>cop<193>sakas
@N1 = (`five classes of<R>ç
worshippers')
Hindus can generally be classed into three groups: ·aivas (worshippers ç
of <185>iva); ·<193>ktas (worshippers of <185>akti or the Dev<200>,the ç
Divine Mother) and vai<218><207>avas (worshippers of Vi<218><207>u).
<185>a<209>kara (<MS>A.<|>D.<D> 788-820) during his days, attempted ç
to unite the various mutually warring sects by introducing the practice ç
of pa<210>cadevat<193>p<220>j<193> or pa<210>co-p<193>san<193>. Here ç
he has added two more deities: Ga<207>apati and S<220>rya. The worshippers ç
of these are called G<193><207>apatyas and Sauras.
This takes the number of the sects to five.
These five classes of worshippers together are called `pa<210>cop<193>sakas' ç
(pa<210>ca= five; up<193>saka = worshipper).
@NT = P<193><207><195>avag<200>t<193>
See <MS>PRAPANNAG®T°<D>.
@NT = P<193><207><195>av<193>s
@N1 = (`sons of P<193><207><195>u')
The chief characters of the voluminous epic, the Mah<193>bh<193>rata, ç
the P<193><207><195>avas were five in number.
They were: Yudhi<218><219>hira (or Dharma-r<193>ya),  Bh<200>ma, ç
Arjuna,  Nakula  and Sahadeva.
P<193><207><195>u, the king of the Candrava<221>·a (lunar race), was ç
their father. Hence the name `P<193><207><195>avas'.
P<193><207><195>u had two wives†Kunt<200> and M<193>dr<200>. Due to ç
the curse of a <216><218>i†Kindama by name†he could not beget children ç
in his wives. However, since Kunt<200> had been blessed by the great ç
sage Durv<193>sas (whom she as a girl had served with fervour and ç
devotion) with a special mantra (sacred formula) by chanting which ç
she could invite a divine being and give birth to a worthy son, she ç
did so now, with the permission of her husband. The first three†Yudhi<218><219>hira, ç
Bhima and Arjuna† were born by the grace of Yama (or Dharma), V<193>yu ç
and Indra respectively. M<193>dr<200> too, with the help of the same ç
mantra, got the twins Nakula and Saha-deva, by propitiating the A·vin<200>devat<193>s.
The P<193><207><195>avas were greatly devoted to K<216><218><207>a†their ç
friend, guide and philosopher†as also to their mother Kunt<200>.
See under each of the names for more details.
See also <MS>P°Ø£U<D> and <MS>MAH°BH°RATA<D>.
@NT = Pa<207><195>harpur
Pa<207><195>harpur (or Pa<207><195>har<193>pura) in the Satara district ç
of the Maharashtra State is one of the well-known places of pilgri-mage, ç
especially for the vai<218><207>avas (followers of the Vi<218><207>u ç
cults). It is, however, the best and the holiest of such places as ç
far as the Maharashtra state is concerned.
The other names by which it was known earlier, are: Pa<207><195>har<200>, ç
P<193><207><195>ura<209>ga-pura, Pa<207><195>ara<209>gapalli, Phaganipur, ç
and Pu<207><195>ar<200>ka K<218>etra.
This town, famous for its temple of Vi<219>hob<193> (or P<193><207><195>ura<209>ga ç
Vi<219><219>hala), is situated 65 kms. (40 miles) to the west of Sholapur, ç
on the right bank of the river Bh<200>m<193>. At Pa<207><195>harpur ç
itself, it is called Candrabh<193>g<193> river. It is a tributary ç
of the river K<216><218><207><193>.
Though this pilgrim centre cannot claim great antiquity like some ç
other places like K<193>·<200> (or V<193>r<193><207>as<200>), it was ç
quitewell-known even by <MS>A.<|>D.<D> 1000. The Padmapur<193><207>a ç
(Uttarakha<207><195>a 176.56-58) mentions the image of Vi<219><219>hala-Vi<218><207>u, ç
on the bank of the river Bh<200>marath<200>, which has only two arms. ç
It calls him `Bindu-m<193>dhava'.
Although the whole town is clustered with several temples, both big ç
and small, it is the temple of Vi<219>hob<193> or Vi<219><219>hala ç
(an aspect of K<216><218><207>a or Vi<218><207>u) that is the centre ç
of attraction, drawing huge crowds of pilgrims throughout the year.
According to the local legends, LordK<216><218><207>a once came to ç
the house of his matchless devotee, Pu<207><195>al<200>ka (or Pu<207><195>ar<200>ka) ç
who was busy serving his aged parents. He threw a brick towards the ç
Lord, requesting him to stand on it and wait till he finished his ç
filial service. Later, when he attended to him, he begged that the ç
Lord should stay there permanently! Hence it is seen that the image ç
is stationed on a flat brick-like stone-slab.
The temple of Vi<219><219>hala is built on an area of 105 metres (350 ç
ft.) by 51 metres (170 ft.), on a high plinth. It has six mah<193>dv<193>ras ç
or main gates out of which the eastern one is considered as the front ç
gate or the chief gate. This is named after N<193>madev (<MS>A.<|>D.<D> ç
1270-1350), a great saint who was a contemporary of J<210><193>nadev ç
or Sant J<210><193>ne·var (<MS>A.<|>D.<D> 1275-1296). The very first ç
step is said to have been built over his sam<193>dhi or burial place. ç
There is also a brass bust of that saint there.
The image of Vi<219><219>hala is about 1.12 metres (3 ft. 9 in.) and ç
seems to have been carved out of one block of black stone, along with ç
the squarish (brick-like) pedestal. It has only two arms, both resting ç
on the hips. The left holds a ·a<209>kha (conch) and the right, a ç
cakra (discus). The ornaments consist of a necklace and fairly large ç
ear-rings that touch the shoulders. The crown or the headgear is of ç
an uncommon shape, more like a longish cap.
The image has a rough or worn-out appearance. It seems to have had ç
a chequered history, being removed and reinstalled several times, ç
maybe due to constant invasions by alien hordes.
Behind the Vi<219><219>hala temple is the temple of Rakhum<193>y<200> ç
(Rukmi<207><200>, the divine spouse of K<216><218><207>a), the image ç
itself being about 1.2 metres (4 ft.) in height.
The daily worship is an elaborate affair. Ek<193>da·<200> (eleventh ç
day during each of the two fortnights in a lunar month) days are observed ç
as festive days.
There is a large staff of priests and attendants in the temple, the ç
chief ones being called the Badves. The others are known as Sev<193>dh<193>ris ç
and are of various grades.
@SPACE1 = 
The visiting devotees are of two types: the v<193>rkar<200>s who visit ç
the temple regularly every month (on ek<193>da·<200> days) and others ç
who visit at their convenience. (See also <MS>V°RKAR®S<D>.)
There is a temple for the great devotee Pu<207><195>ar<200>ka in the ç
bed of the Candrabh<193>g<193> river, about 66 metres (220ft.) away ç
from Vi<219><219>hala's temple.
To the south of this again, about one kilometer away, is another temple ç
called `Vi<218><207>up<193>d.' It is built on a rock in the river-bed ç
on a plinth 2.1 metres (7 ft.) in height. It contains the `footprints' ç
of Lord K<216><218><207>a and of a cow. Pilgrims perform ·r<193>ddha ç
ceremonies (obsequial rites) here.
The town also contains other temples dedicated to <185>iva and Dev<200> ç
(P<193>rvat<200> or the Divine Mother).
@NT = P<193><207><195>u
@N1 = (`the white one')
When the king Vicitrav<200>rya of the lunar race passed away without ç
any issue, Satyavat<200>, his mother, requested the sage Vy<193>sa ç
to father a son in the queen Amb<193>lik<193> by the system of levirate, ç
which was common during those days.
The two children born thus were Dh<216>tar<193><218><219>ra and P<193><207><195>u. ç
Since the former was born blind, P<193><207><195>u (= of white complexion) ç
was crowned as the king in course of time.
After his marriage with Kunt<200> and M<193>dr<200>, he set out on ç
a conquest mission, thereby subjugating many a king.
He once went out hunting and killed a male deer which was actually ç
a <216><218>i, Kindama by name, who had assumed that form along with ç
his wife as a female deer. The <216><218>i pronounced a curse before ç
breathing his last, that he would die if ever he had intercourse with ç
any woman.
After returning to his capital, P<193><207><195>u retired to the <185>ata·<216><209>ga ç
hill and started living there like a forest recluse. It was during ç
this period that he was dejected since he had no children to continue ç
the race. After taking his permission however, Kunt<200> and M<193>dr<200> ç
gave birth to the five P<193><207><195>avas through the power of a ç
special mantra (esoteric formula) taught to Kunt<200> many years earlier, ç
by the sage Durv<193>sas.
Later, one day, infatuated by the beauty of M<193>dr<200> and unable ç
the control himself he approached her and died instantly.
M<193>dr<200> committed sahagamana (dying on the funeral pyre) along ç
with his body.
@NT = P<193><207><195>ura<209>ga
P<193><207><195>ura<209>ga is another name of Vi<219><219>hala or ç
Vi<219>hob<193>, the presiding deity of the Vi<218><207>u temple at ç
Pa<207><195>harpur in the Sholapur district of Maharashtra.
See <MS>PAØ£HARPUR<D> for more details.
@NT = p<193><207>igraha<207>a
@N1 = (`clasping the hand')
See <MS>VIV°HA<D>.
@NT = P<193><207>ini
Vy<193>kara<207>a or grammar is one of thesix Ved<193><209>gas (`limbs ç
of the Vedas', subsidiary sciences that help to understand the Vedas).
Out of the several vy<193>kara<207>as of Sanskrit said to have existed, ç
the A<218><219><193>dhy<193>y<200> of P<193><207><200>ni is considered ç
as the best and the most authoritative. Even today it is extremely ç
popular and is studied enthusiastically by all the serious students ç
of Sanskrit. (See <MS>A<186><187>°DHY°Y®<D> for details.)
As in the case of many other ancient authors of well-known treatises, ç
not much is known of P<193><207>ini also. From the meagre sources ç
of the writings of Hiuen Tsang (<MS>A. D.<D> 600-664) and the Kath<193>sarits<193>gara ç
of Somadeva (11th cent. <MS>A.<|>D.<D>), he was the son of <185><193>la<209>ka, ç
also known as Pa<207>ina and S<193>mana, and D<193>k<218><200> (or ç
D<193>k<218><193>), and was born at the village <185><193>l<193>tura ç
in G<193>ndh<193>ra-de·a (the modern Kandahar in Afghanistan). Sometimes ç
it is identified with Attock, now in the North-West Frontier province ç
of Pakistan. Hence he was also known as <185><193>la<209>ka, D<193>k<218><200>putra, ç
Ahika as also <185><193>l<193>tur<200>ya. He was a student of Var<218>a ç
who probably lived during the period of the Nandas (5th cent. <MS>B.<|>C.<D>). ç
K<193>ty<193>yana, Vy<193><195>i and Indradatta were his classmates. ç
Being ridiculed as a dullard by them, he is said to have got Lord ç
<185>iva's grace through severe austerities and being blessed by him, ç
composed his great work, the A<218><219><193>dhy<193>y<200>.
He is said to have met with his death in an encounter with a lion.
Several scholars have battled for years to fix his date. It ranges ç
from 700 <MS>B.<|>C.<D> up to 350 <MS>B.<|>C.<D>
Apart from the A<218><219><193>dhy<193>y<200> (his magnum opus), ç
he is said to have written another work called J<193>mbavat<200>-pari<207>aya.
P<193><207>ini mentions several grammarians who preceded him, like ç
°pi·ali and K<193>·ak<216>tsna.
The V<216>tti of Vararuci (or K<193>ty<193>yana) and the Mah<193>bh<193><218>ya ç
of Pata<210>jali (200 <MS>B.C.<D>) are the two most well-known commentaries ç
on his magnum opus.
@NT = P<193><207>in<200>ya <185>ik<218><193>
Listed as one of the six Ved<193><209>gas (`limbs of Veda', subsidiary ç
sciences that help in understanding the Vedas better) <185>ik<218><193> ç
or phonetics teaches about the correct chanting of the Vedic mantras.
Out of the several <185>ik<218><193>s listed in Vedic works and allied ç
literature, it is only the P<193><207>in<200>ya <185>ik<218><193> ç
that is available now, in the most complete form.
Though it goes in the name of P<193><207>ini (the famous grammarian), ç
it is actually composed by Pi<209>gala, the younger brother of P<193><207>ini.
In the available text there are sixty ·lokas or verses. A smaller ç
version comprising twenty-two verses occurs in the Agnipur<193><207>a.
It seems to belong to the <184>gveda as well as the Yajurveda.
@NT = pa<209>ktip<193>vanas
@N1 = (`those who purify the entire line of persons')
Feeding the br<193>hma<207>as, especially at the time of ·r<193>ddhas ç
or obsequial rites, was considered a holy act earning a lot of merit ç
for the host. However, only the pa<209>ktip<193>vana-types of br<193>hma<207>as ç
had to be invited.
A pa<209>ktip<193>vana is one who purifies (= p<193>vana) the entire ç
line (= pa<209>kti) in which he sits. Being a person of great self-control ç
and pure character as also high spiritual attainments, his power of ç
personality is so potent that it can effect the purification of all ç
the persons sitting in the same line.
The epics and the pur<193><207>as give thedescriptions of such pa<209>ktip<193>vanas. ç
SeeMah<193>bh<193>rata, Anu·<193>sanaparva. 90.25 to 38.
@NT = p<193>pa
See <MS>P°TAKA<D>.
@NT = para, par<193>
@N1 = (`the highest')
This word is used in two senses: `the other,' `the highest'.
In the latter sense it can be used in all the three genders†masculine, ç
feminine and neuter.
However in the tantras†treatises dealing with the <185>akti or the ç
Divine Mother†it (par<193>) is used in a technical sense, to indicate ç
the original or the primary state of v<193>k or speech, the other ç
three states being pa·yant<200>, madhyam<193> and vaikhar<200>.
In the par<193> state, speech (or speech energy) is in the potential, ç
unmanifested state. In the pa·yant<200> state, the desire tospeak ç
is getting manifested. In the madhyam<193>, the thought patterns (and ç
sentences) have already evolved. In the vaikhar<200>, the last stage, ç
it is expressed as vocal speech.
@NT = Parabrahman
@N1 = (`Brahman [the Absolute] the Highest')
Treatises of Ved<193>nta describe God, the Absolute, as `Brahman' ç
or `Para- brahman'. See <MS>BRAHMAN<D> for details.
@NT = Parak<193>la Ma<219>ha
This is one of the prominent ma<219>has or monastic centres belonging ç
to the <185>r<200>vai<218><207>ava sect of Vai<218><207>avism.
The original centre was started by Brahmatantra Svatantra Parak<193>la ç
Sv<193>min (<MS>A.<|>D.<D> 1286-1386), a monastic disciple of Ved<193>nta ç
De·ika (<MS>A.<|>D.<D> 1268-1369), at K<193><210>c<200>puram (in Tamil ç
Nadu) in <MS>A.<|>D.<D> 1359. It was later on shifted to Tirupati, ç
Melko<219>e, <185>r<200>ra<209>gapa<219><219>a<207>a and finally, ç
to Mysore. The pontiff of this ma<219>ha was accepted as the R<193>jaguru ç
or royal preceptor by Yadur<193>ya, the first king of Mysore.
The presiding deity of this monastery is Lak<218>m<200>-Hayagr<200>va. ç
The image of this deity is said to have been given to R<193>m<193>nuja ç
(<MS>A.<|>D.<D> 1017-1137) by the goddess Sarasvat<200>. The same was ç
handed over by a succession of teachers to Ved<193>nta De·ika from ç
whom the first pontiff got it.
Till now there has been an unbroken series of pontiffs, the present ç
head†V<193>g<200>·a Brahmatantra Parak<193>lasv<193>mi†occupying the ç
seat since <MS>A.<|>D.<D> 1992.
Though most of them proved to be great teachers, mention may be made ç
of V<193>g<200>·asv<193>min (pontificate from <MS>A.<|>D.<D> 1915 to ç
1925) who was endowed with yogic powers and Abhinava Ra<209>gan<193>tha ç
Sv<193>min who was the head for 41 years (from <MS>A.D.<D> 1925 to ç
1966), in whose period there was a tremendous expansion of intellectual ç
activity.
@NT = parak<193>yaprave·a
@N1 = (`entering into<R>ç
another's body')
The Yogas<220>tras (3.38) of Pata<210>jali (200 <MS>B.<|>C.<D>) describes ç
parak<193>ya prave·a or `entering' into the body of another person ç
(dead or alive) as one of the yogasiddhis or occult powers gained ç
by a yogi who has  succeeded  in  attaining  sam<193>dhi (superconscious ç
state).
Every person is imprisoned as it were in the physical body due to ç
the pr<193>rabdha- karma. A yogi who has attained the sa<221>yama ç
state (the power of concentration culminating in sam<193>dhi) has ç
developed enough power to detach his mind from his own body and enter ç
into the body of another person†dead or alive†and work through it. ç
This is called parak<193>yaprave·a.
For this, he should also have a knowledge of the various n<193><195><200>s ç
(tubular structures)  through  which  the  pr<193><207>ic energy flows ç
or works.
When the yogi thus works through another living person's body, the ç
latter's soul or mind is kept in a temporarily suspended state.
The yogi always uses this power for the good of other people or to ç
exhaust his own pr<193>rabdhakarma.
<185>a<209>kar<193>c<193>rya (<MS>A.<|>D.<D> 788-820) is said to have ç
had and used this power once.
@NT = paramaha<221>sa
@N1 = (`the great swan')
Some of the pur<193><207>as as also the dharma·<193>stras categorise ç
the sa<221>ny<193>sins (Hindu monks) into four groups: the ku<219><200>cakas, ç
the bah<220>dakas, the ha<221>sas and the paramaha<221>sas.
A ku<219><200>caka (`one who lives in a hut') is one who lives in ç
an <193>·rama (monastery), eats only eight morsels of food per day ç
and performs yogic practices.
A bah<220>daka (`one who drinks water from many sources') wears the ç
ochre- coloured cloth (an insignia of a Hindu monk) and carries a ç
kama<207><195>alu (water-pot prepared out of the bitter gourd) as ç
also a trida<207><195>a (staff made of three bamboo sticks tied together). ç
He lives by begging from not more than seven houses.
The ha<221>sa (`the swan') is an ekada<207><195>i (has one staff only, ç
signifying the control of the mind), lives under trees or in mountain ç
caves and such other solitary places, going into the village once ç
a day for begging his food.
The paramaha<221>sa (`the great swan') is the best of these four sa<221>ny<193>sins. ç
He is said to live in deserted places, cremation grounds or dilapidated ç
structures. He is completely indifferent to physical comforts and ç
is perfectly equanimous under all circumstances of life.
The  word  `paramaha<221>sa'  itself perhaps  means  a  person  possessing ç
supreme discrimination (like a ha<221>sa or a swan which can leave ç
off water and drink only milk from the diluted mixture of the two) ç
which ultimately results in the knowledge of Brahman. Or, it may also ç
mean a person of the highest spiritual experience, who is constantly ç
aware that he is one with Brahman (ham<|>=<|>aham =I; sa<199> = he, ç
God or Brahman).
Works like the Vaikh<193>nasa S<220>tras (8.9), Laghuvi<218><207>upur<193><207>a ç
(4.14.23), Bhik<218>u-kopani<218>ad and S<220>tasa<221>hit<193> ç
(M<193>nayoga-kha<207><195>a 6) give a description of these four ç
types of sa<221>ny<193>sins.
@NT = param<193><207>u
@N1 = (`atom')
Generally, all the six systems of Hindu philosophy†known as the <186>a<195>-dar·anas†propound ç
their own theories of creation of this world.
The Ny<193>ya-Vai·e<218>ika systems put forward the theory that the ç
physical world is evolved out of a gradual combinationof the param<193><207>us ç
of the four basic elements †p<216>thv<200> (earth), ap (water), tejas ç
(fire), v<193>yu (air)†and the <193>k<193>·a (ether) as also the j<200>vas ç
(individual souls) in accordance with their karma, by ®·vara or God.
When an element like the earth or water is broken into smaller parts, ç
the smallest ultimate particle beyond which further division is impossible, ç
is called `param<193><207>u'. Only the first four elements can be ç
in the form of param<193><207>us or atoms.
@NT = paramapuru<218><193>rtha
@N1 = (`the highest [goal of life] aspired after, by a human being')
A puru<218>a or a human being is expected to strive for four puru<218><193>rthas ç
or ends in life viz., dharma (righteousness), artha (wealth), k<193>ma ç
(desire for carnal pleasures) and mok<218>a (liberation from transmigratory ç
existence).
Out of these, the last is considered as `parama' or the highest and ç
the best. Hence the name `paramapuru<218><193>rtha'.
@NT = p<193>ram<193>rthika
@N1 = (`relating to the highest truth')
Truth (`satt<193>') according to Advaita metaphysics is of three types: ç
pr<193>tibh<193>sika (apparent), vy<193>vah<193>rika (practical) and ç
p<193>ram<193>rthika (the highest).
When  we  wrongly  perceive  the upright ears of a hare as its horns, ç
it is `pr<193>tibh<193>sika' satt<193>. This world of senses is `vy<193>vah<193>rika' ç
satt<193> since it is real for all practical purposes. Brahman or ç
God which is the highest and unchanging truth is `p<193>ram<193>rthika' ç
satt<193>.
@NT = Param<193>tman
@N1 = (`the Supreme Sel<%14>f<%0>')
If each of the individual souls is called `j<200>v<193>tman', God ç
is called Param<193>t-man as opposed to him. Param<193>tman is the ç
same as Brahman.
See <MS>BRAHMAN<D> for more details.
@NT = Parame·vara
@N1 = (`the greatest Lord')
Though the word refers to God as the supreme ruler of the universe, ç
it is more commonly used to indicate <185>iva, the third deity of ç
the Hindu Trinity.
The Vi<218><207>usahasran<193>ma (name 377) too has used this term ç
for Vi<218><207>u.
@NT = P<193>r<193>nanda S<220>tras
The P<193>r<193>nanda S<220>tras also known as the P<193>r<193>nanda ç
Kalpas<220>tras, is a work belonging to the tantras or <185><193>kt<193>gamas. ç
It is a work assigned to the period <MS>A.<|>D.<D> 900, though some ç
scholars try to push it back to the period 2400-1800 <MS>B.<|>C.<D>, ç
perhaps identifying it with the Vedic Kalpas<220>tra literature.
The work must have been composed at a period when the followers of ç
the t<193>ntrik schools were struggling to get rid of a stigma and ç
endeavouring to be recognised as a part of the Vedic tradition. Hence ç
it is that it declares itself to contain the very cream of the Vedas.
This treatise†which is prose, in the form of s<220>tras†is in two ç
adhy<193>yas or chapters. Each adhy<193>ya is divided into seven <193>hnikas ç
or subsections. The total number of s<220>tras is 1585.
Some of the s<220>tras are short whereas many others are quite long ç
and descriptive.
The work calls God, the Supreme, as Param<193>tman. Under him work ç
seven ®·varas (lords) of extraordinary powers. They are: Brahm<193>, ç
Vi<218><207>u, <185>iva, S<220>rya, Ga<207>e·a, <185>akti and Bhairava.
Param<193>tman (God, the Supreme) is the Lord of even the ®·varas. ç
He is the very embodiment of eternal bliss, life and knowledge. His ç
divinity is supreme and his powers are all-pervading. He is the object ç
of worship of not only the j<200>vas but also of the ®·varas.
The next category of sentient beings are the j<200>vas or individual ç
souls, who are atomic and infinite in number. They are urged to follow ç
the path of dharma or righteousness and eschew the path of adharma ç
or evil which leads them into hell with intense suffering.
@SPACE1 = 
Three paths of the spiritual disciples are described here: The Dak<218>i<207>a, ç
the V<193>ma and the Uttara.
The first one follows the disciplines given in the Vedas, the sm<216>tis ç
and the pur<193><207>as. The second one follows the Vedas and the ç
tantras. The last considers guru-v<193>kya, the command of the spiritual ç
preceptor, along with the Vedas, as very important.
It prescribes a detailed process of d<200>k<218><193> or initiation ç
for a disciple by a guru who must be a j<200>vanmukta (liberated soul).
The j<200>vas aspiring after liberation are advised to cultivate several ç
virtues like ahi<221>s<193> (non-violence), satya (truthfulness), ç
asteya (non-stealing), brahmacarya (celibacy), aparigraha (non-acceptance ç
of gifts), sv<193>dhy<193>ya (study of scriptures), bhakti (devotion ç
to God), dama (control of senses), mauna (control of speech), ·ama ç
(peace ofmind), mantrajapa (repetition of the mantra given by the ç
guru) and so on.
The work, in addition, deals with the dharmas of the four var<207>as ç
and the <193>·ramas as also the four yogas. The efficacies of mantras ç
and mudr<193>s (hand poses), the procedure of observing t<193>ntrik ç
festivals and the use of pa<210>camak<193>ras (See <MS>TANTRAS<D> ç
for details.) also find a place here.
@SPACE = 
@NT = par<193>prak<216>ti
@N1KERN = (`the higher prak<216>ti or<R>ç
nature')
@SPACE = 
Generally most of the Hindu systems of philosophy known as the <186>a<195>dar·anas ç
or the six schools, accept three basic factors as involved in the ç
process of creation: the prak<216>ti (material matrix); the j<200>vas ç
(individual souls, unredeemed as yet); and, ®·vara (God).
®·vara creates the world out of prak<216>ti and involves the j<200>vas ç
in the bodies made out of that prak<216>ti, in accordance with their ç
karma or deserts of previous lives.
It is only in the Bhagavadg<200>t<193> (7.4,5) that we find a classification ç
of prak<216>ti as apar<193> (lower) and par<193> (higher).
Both these prak<216>tis are of the Lord. They belong to him.
The apar<193>prak<216>ti is ja<195>a (lifeless, non-conscious) and ç
is eightfold: bh<220>mi (earth); <193>pas (water); anala (fire); v<193>yu ç
(air); kha<221> (ether or space or sky); manas (mind); buddhi (intellect); ç
and aha<209>k<193>ra (egoity).
The material universe is made out of this.
The j<200>va (individual soul) is different from this apar<193>prak<216>ti ç
and is termed `par<193>prak<216>ti.' It is `prak<216>ti' since it ç
is also involved as a part of creation, as a basic factor. It is `par<193>' ç
or `superior' since it is conscious and is full of life as opposed ç
to the other which is insentient.
The whole universe is a product of these two prak<216>tis and ®·vara, ç
the Lord, is responsible for its evolution or creation, sustenance, ç
and involution or destruction.
See also <MS>APAR°PRAK<184>TI.<D>
@NT = Par<193>·akti
@N1 = (`the great <185>akti or power')
Hinduism considers God not only as the Father, but also as the Mother, ç
of this universe. If God is Parabrahman, he is also Par<193>·akti. ç
These two aspects are inseparable even as fire and its burning power ç
are.
According to the <185>aiv<193>gamas, <185>iva as the highest Principle ç
differentiates himself†at the time of evolution of this universe†into ç
Par<193>·akti (the transcendental, supreme Power), all the while remaining ç
himself unaffected.
From Par<193>·akti (Supreme Power) evolves Cicchakti (Power of Consciousness); ç
from Cichhakti comes °nanda·akti (Power  of  Bliss);  from  °nanda·akti ç
emanates Icch<193>·akti (Will-power); from Icch<193>·akti issues J<210><193>na·akti ç
(Power of Knowledge); and, from this J<210><193>na·akti emerges Kriy<193>·akti ç
(Power of Action).
Sometimes, the five aspects of <185>iva like Sadyoj<193>ta, V<193>madeva ç
and so on are said to have been derived from the five aspects of <185>akti.
The word Par<193>·akti is more frequently used to indicate P<193>rvat<200> ç
herself.
@NT = Par<193>·ara
One of the well-known <216><218>is or sages frequently mentioned in ç
the epics and the pur<193><207>as, Par<193>·ara was the son of the ç
sage <185>akti and the grandson of the famous Vasi<218><219>ha.
He is considered as one of the gotra-pravartakas or the sages from ç
whom the gotras (patriarchal ancestries) originated.
Learning of the cruel end of his father at the hands of a demon, Kalm<193><218>ap<193>da, ç
he started a sacrifice for the destruction of the race of demons.
He was not only a great sage but also a great scholar of the religious ç
lore. His teachings to other sages and kings like Janaka contain a ç
lot of information on many abstruse facets of religion andphilosophy ç
(vide Mah<193>bh<193>rata, Anu·<193>sanaparva 146 to 149; 150 ç
to 152).
He was the father of another great sage†Vy<193>sa or Vedavy<193>sa†through ç
Satyavat<200>, the adopted daughter of a chieftain of the fishermen.
Par<193>·arag<200>t<193> (<185><193>ntiparva 296-304) and the ç
Par<193>·arasm<216>ti are attributed to him.
@SPACE = 
@NT = Par<193>·arabha<219><219>a
@N1 = (<MS>A.<|>D.<D> 1073-1165)
@SPACE = 
One of the unfinished tasks of Y<193>mun<193>c<193>rya (<MS>A. D.<D> ç
912-1042) which R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137) had inherited ç
and promised to fulfil, was the perpetuation of the name of Par<193>·ara, ç
the great sage who wrote the Vi<218><207>upur<193><207>a. As he ç
was searching for a suitable person to whom he could assign the task, ç
his eyes fell on the young son of his own faithful disciple, K<220>re·a. ç
He gave him the name `Par<193>·arabha<219><219>a,' got him trained ç
in the traditional lore of his Ved<193>nta and commanded him to write ç
a detailed commentary on the well-known hymn, the Vi<218><207>u- ç
sahasran<193>ma (Mah<193>bh<193>rata, Anu·<193>sanaparva 149). ç
Par<193>·arabha<219><219>a successfully completed his assignment and ç
named his commentary as Bhagavadgu<207>adarpa<207>a (`a Mirror to ç
the Qualities of the Lord').
Since he was extremely intelligent and had acquired great scholarship ç
in the <185>r<200>vai<218><207>ava philosophy and traditions, R<193>m<193>nuja ç
made him the chief pontiff of the Ra<209>gan<193>tha temple complex ç
at <185>r<200>ra<209>gam (in Tamil Nadu).
He had attained mastery in Sanskrit as well as Tamil.
Nine more works†all in Sanskrit† have been attributed to him. Some ç
of them are: Hymns like the Gu<207>aratnako·a and <185>r<200>ra<209>gar<193>jastava; ç
Tattvaratn<193>kara; Adhy<193>tmakha<207><195>advayavivara<207>a ç
and Kriy<193>d<200>pa.
Ved<193>nta De·ika (<MS>A.<|>D.<D> 1268-1369) had been deeply influenced ç
by the writings of Par<193>·arabha<219><219>a.
@NT = Par<193>·arag<200>t<193>
@SPACE = 
The epics and the pur<193><207>as contain several religious discourses ç
that go by the name `G<200>t<193>,' in imitation of the famous Bhagavadg<200>t<193>. ç
One such, from the epic, the Mah<193>bh<193>rata, is the Par<193>·arag<200>t<193>. ç
It forms a part of the <185><193>ntiparva (chapters 290 to 298). ç
It has nine chapters, the total number of verses being 288. The sage ç
Par<193>·ara is the teacher while the king Janaka is the recipient ç
of the teaching.
A brief summary of the same may now be given:
@SPACE = 
@S10N = Chapter 1 (26 verses)
Dharma is the best means of obtaining ·reyas or spiritual welfare. ç
Karmas give their results, good or bad. Cultivation of virtues like ç
dama (self control), k<218>am<193> (forgiveness), satya (truth) leads ç
to happi-ness. People ruin themselves by going against their svadharma ç
(duties allotted to them).
@SPACE = 
@S10N = Chapter 2 (23 verses)
Since a human birth and a long life are difficult to obtain, one should ç
do only good actions and avoid bad actions. The law of karma is inexorable. ç
Sins committed out of ignorance can be erased through proper expiations ç
but not the ones committed intentionally.
@SPACE = 
@S10N = Chapter 3 (23 verses)
Money earned through dharma, the righteous means, is good. Serving ç
guests is a pious act. 
Everyone is born under certain <216><207>as or debts like deva-<216><207>a ç
and <216><218>i-<216><207>a, debts towards gods and sages, and should ç
discharge oneself from them as described in the holy scriptures.
Prayer to God and performance of good actions are of great help in ç
life.
@S10N = Chapter 4 (21 verses)
Eulogy of the benefits wrought by the company of holy men is stressed ç
here. So also, the importance of following the dharmas (duties) that ç
accrue to one as per his var<207>a and <193>·rama, is highlighted.
@S10N = Chapter 5 (31 verses)
This chapter describes as to how the people of the four var<207>as ç
should live. They should abandon all forbidden actions.
When the <193>sur<200> or demoniac tendencies rose in the hearts of ç
human beings making them inclined towards evil, Lord <185>iva destroyed ç
them. The decimation of the Tripuras (the three cities of the demons ç
and the demons themselves) by Lord <185>iva is symbolic of this.
@S10N = Chapter 6 (39 verses)
A person deeply attached to sense-pleasures gradually goes down whereas ç
the one who performs his duties properly and also tapas or austerities, ç
raises himself and attains perfection in course of time. This is the ç
gist of the teachings of this chapter.
@S10N = Chapter 7 (39 verses)
While continuing the topic of the var<207>as, Par<193>·ara declares ç
here that aperson born in a higher var<207>a, automatically goes ç
down to the lower ones if he neglects his duties. On the other hand, ç
persons of lower var<207>as can raise themselves to higher levels ç
through tapas.
@S10N = Chapter 8 (40 verses)
This chapter deals with the following subjects: importance of sweet ç
speech; various kinds of death; some rules regarding wars and battles; ç
realisation of the <193>tman puts an end to transmigration; greatness ç
of a person, who being born as a human being, attains <193>tmaj<210><193>na ç
or realisation; auspiciousness of dying in the uttar<193>ya<207>a ç
(northern solstice); need for serving the spiritually great ones; ç
condemnation of suicide; eulogy of performing good deeds as also giving ç
gifts and bathing in sacred rivers.
@S10N = Chapter 9 (46 verses)
Importance of asa<209>gatva (non-attachment) and a beautiful description ç
of a man who has attained that state is the main topic of this concluding ç
chapter.
This short work is definitely a useful addition to the G<200>t<193>-literature.
@SPACE = 
@NT = Par<193>·ara Sm<216>ti
@SPACE = 
If the Vedas and the Upani<218>ads give the basic philosophy of Hinduism, ç
the dharma·<193>stras, comprising the sm<216>tis, the pur<193><207>as ç
and the nibandhas (digests), give the rules and regulations that guide ç
a Hindu in his personal and social life.
One of the more ancient sm<216>tis extant even now, is the Par<193>·ara ç
Sm<216>ti. It has twelve chapters and 602†or 592 according to its ç
own statement at the end†verses.
The following is a brief summary of its contents.
@S10N = Chapter 1 (65 verses)
Knowledge of dharma; on the four yugas; six daily duties like bath, ç
sandhy<193> ritual and Vedic studies; proper means of livelihood for ç
the three lower var<207>as.
@S10N = Chapter 2 (20 verses)
@EMERGENCY = Duties of a householder.
@S10N = Chapter 3 (55 verses)
@EMERGENCY = A·auca (ceremonial impurity) and purificatory processes.
@S10N = Chapter 4 (34 verses)
@EMERGENCY = On suicide; punishment for a wife who deserts her husband; ç
remarriage of women under certain conditions; in praise of chaste ç
widows.
@S10N = Chapter 5 (24 verses)
@EMERGENCY = Minor expiations.
@S10N = Chapter 6 (75 verses)
@EMERGENCY = Expiations for pr<193><207>ihaty<193> (killing animals ç
and human beings).
@S10N = Chapter 7 (44 verses)
@EMERGENCY = Purification of various articles such as vessels of wood ç
and metal; about women in menses.
@S10N = Chapter 8 (50 verses)
@EMERGENCY = Expiations for the killing of cows and oxen unwillingly; ç
constitution of a pari<218>ad (assembly) of br<193>hma<207>as.
@S10N = Chapter 9 (60 verses)
@EMERGENCY = Taking proper care of one's cows.
@S10N = Chapter 10 (43 verses)
@EMERGENCY = Certain expiations like c<193>ndr<193>ya<207>a and s<193>ntapana.
@S10N = Chapter 11 (55 verses)
@EMERGENCY = Expiations for the violation of the rules regarding the ç
partaking of food; purification of wells polluted by animals.
