@NID = agha<199>, a<221>has, durita, du<218>k<216>ta, enas, p<193>pa, ç
p<193>pman, p<193>taka, v<216>jina and so on.
The concept of p<193>taka or sin is as old as the <184>gveda (1.17.1; ç
8.47.2) wherein prayers have been offered to the deities like °ditya, ç
Mitra and Varu<207>a for redemption.
The question as to what causes sinand how it is committed has been ç
discussed in the dharma·<193>stras. The G<200>t<193> (16.21) declares ç
that k<193>ma (lust), krodha (anger) and lobha (greed) born out of ç
the rajogu<207>a (in the mind) (See <MS>GUØA<D> for details.) are ç
responsible for a person to perpetrate evil deeds, thereby accumulating ç
sins.
Some of the earliest dharma·<193>stras (like those of Gautama, Y<193>j<210>avalkya ç
and Manu) list the following lapses and misdeeds as leading to sins: ç
doing yaj<210>a (sacrifice) for an unworthy person, eating forbidden ç
food, speaking untruth, neglect of prescribed duties, committing deeds ç
declared as evil by the ·<193>stras or holy books and lack of self ç
control.
In course of time, the list was enlarged to include many more items.
All the sins will result in physical and psychological suffering. ç
Graphic des-criptions of hells given in the pur<193><207>as seem to ç
be an attempt at dissuading human beings from committing sins.
Sins have been classified in several ways. The most common classification ç
is into three groups: mah<193>p<193>takas or atip<193>takas (most ç
heinous or mortal sins); upap<193>takas (minor sins, venial sins) ç
and prak<200>r<207>a or pr<193>sa<209>gika (miscellaneous, incidental).
@SPACE1 = 
Under the first category are giventhe following sins: prohibited ç
sexual relations like incest; murdering; drinking liquor; theft; association ç
with those who have committed these sins; reviling the Vedas; giving ç
false evidence to harm others and so on.
The second category includes such minor sins as: forsaking the sacred ç
fires; offending the guru; becoming an atheist; minor thefts; accepting ç
remuneration for teaching the Vedas; usury and so on.
It is interesting to note that cutting of big trees for fuel was also ç
included in the latter list!
Sins omitted from these two groups and considered as very minor, are ç
relegated to the third or the last group.
The dharma·<193>stras and the pur<193><207>as have also specified ç
the pr<193>ya·cittas (expi-ations) or the various means of reducing ç
the consequences of these sins. They are: p<193>panivedana  (confession);  pa·c<193>tt<193>pa ç
(repentance); pr<193><207><193>y<193>ma (restraint of breath); tapas ç
(austerity); homa (sacrifice into a duly consecrated fire); japa (repetition ç
of Vedic passages as prayers); d<193>na (giving gifts); upav<193>sa ç
(fasting); and t<200>rthay<193>tr<193> (pilgrimage).
P<193>panivedana should be done before God or the sacred fire or the ç
pari<218>ad (anassembly of learned persons of unblemished character).
This should be followed by pa·c<193>tt<193>pa and a firm resolve, ç
not to repeat the sin.
Pr<193><207><193>y<193>ma burns up the impurities of the mind and ç
purifies it. The number should be as prescribed in the ·<193>stras ç
or by the pari<218>ad.
@SPACE1 = 
Tapas has many aspects such as fasting (partial or full), celibacy, ç
truthfulness, bathing thrice a day, wearing of wet clothes until they ç
dry up (on the body), sleeping on the ground, not injuring others, ç
serving the preceptor and so on. The period may extend from one month ç
up to 12 months, depending on the nature of the sin.
As regards the homa, it is the K<220><218>m<193><207><195>ahoma, using ç
the mantras of theTaittir<200>ya °ra<207>yaka (2.3-6), that is ç
normally prescribed. This homa has been specially recommended for ç
the expiation of sins.
Ga<207>ahoma and G<193>yatr<200>homa are also sometimes prescribed.
These are preceded by a d<200>k<218><193> (initi-ation) wherein a ç
set of rules and discipline such as abstaining from meat, sex and ç
falsehood, sleeping on the ground, subsisting on milk and so on, are ç
also to be observed strictly. These homas please the deities for whom ç
they are done. They (the deities) forgive the sins and also grant ç
boons.
Japa can be with the Vedic or the °gamic mantras. Certain passages ç
like the Aghamar<218>a<207>as<220>kta and the Puru<218>a-s<220>kta ç
or the s<193>mans like R<193>jata and Rauhi<207>eya as also some ç
Upani<218>adic passages are prescribed in the first group. Well-known ç
mantras like the G<193>yatr<200>, the Pa<210>c<193>k<218>ar<200> and ç
the A<218><219><193>k<218>ar<200> are recommended in the second group. ç
(R<193>mamantra often called the T<193>rakamantra also finds an important ç
place.) For that matter, any mantra of any deity, duly received froma ç
competent guru, can be used for expiation.
For d<193>na or giving gifts, many things are mentioned such as gold, ç
cow, clothes, horse, land, food etc. Gifts may be offered to temples ç
and religious institutions also.
@SPACE1 = 
During upav<193>sa or fasting, which can be total or partial, the ç
sinner is advised to avoid luxury articles, sleeping in daytime and ç
sex completely.
T<200>rthay<193>tr<193> or pilgrimage should be undertaken to well-known ç
and highly recommended places like K<193>·<200>, Badar<200>, Ked<193>ra ç
and R<193>me·varam.
Association with a saint and serving him is also an aspect of pilgrimage.
Ultimately, it can safely be declared that the following disciplines ç
are the best means of overcoming or attenuating the evil effects of ç
sin on one's life: sincererepentance, resolving not to repeat the ç
sinful deeds, repetition of God's name, earnest prayer and the company ç
of holy persons.
@NT = P<193>t<193>la
@N1 = (`[the evildoers] fall [into this]')
The pur<193><207>as describe fourteen worlds. Out of these, six are ç
higher worlds above this earth (= Bh<220>loka). Seven are below. They ç
are: Atala, Vitala, Sutala, Tal<193>tala, Mah<193>tala, Ras<193>tala ç
and P<193>t<193>la.
According to this list, P<193>t<193>la is the nethermost world. It ç
is the abode of serpents. The serpent-chiefs who live here are: A·vadhara, ç
Devadatta, Dhana<210>jaya, Dh<216>tar<193><218><219>ra, Gulika, Kambala, ç
Mah<193>-·ikha, <185>a<209>kha, <185>a<209>khac<220><195>a, <185>veta ç
and V<193>suki.
At the base of the P<193>t<193>la is a place separated from the rest ç
where lives Ananta or °di·e<218>a or <185>e<218>an<193>ga. He is said ç
to be carrying all the worlds on his thousand hoods.
All the eleven great serpents mentioned above have brilliant gems ç
on their hoods, the light emanating from which illuminates the netherworld.
According to the Mah<193>bh<193>rata (vide Udyogaparva 99) P<193>t<193>la ç
is inhabited by daityas (demons), govratis (persons of great austerity) ç
and mahar<218>is (great sages) as also the four elephant kings (Air<193>va<207>a, ç
V<193>mana, Kumuda and A<210>jana) who are guarding the quarters.
As per the long description given in the Vy<193>sabh<193><218>ya ç
on the Yogas<220>tras (3.26) the P<193>t<193>la-loka has oceans ç
and mountains. All types of beings like asuras, gandharvas, kimpuru<218>as, ç
yak<218>as and r<193>k<218>asas as also various kinds of disembodied ç
spirits (bh<220>tas, pretas, pi·<193>cas, brahmar<193>k<218>asas and ç
so on) live here.
@NT = P<193><219>aliputra
Also known as P<193><219>aligr<193>ma, Puppla-pura (Pu<218>papura) ç
and Kusumapura, it was an ancient city of great fame. Gautama Buddha ç
seems to have visited it (which was a small village at that time) ç
during Aj<193>ta·atru's reign and predicted a great future for it.
According to Kau<219>ilya's Artha·<193>stra (321 <MS>B.<|>C.<D>) ç
it was the greatest city in the East even by the 4th century <MS>B.<|>C.<D>
It was the capital of the Mauryas and the <185>u<209>gas. Megasthanies ç
(302-288 <MS>B.C.<D>) has mentioned that it extended on the bank of ç
the Ga<209>g<193>, defended by a wooden palisade flanked by 570 bastions ç
and surrounded by a deep wide moat. It had 64 gates in all! It was ç
also the capital of the kingdom of Magadha. Hiuen Tsang (<MS>A.<|>D.<D> ç
600-664) has described how the king K<193>l<193>·oka made it his metropolis.
It  has  been  identified  with  the modern Patna city (capital of ç
Bihar).
@NT = Pata<210>jali
`Pata<210>jali' is a great name in Sanskrit literature, both in its ç
secular and the sacred aspects.
He is generally assigned to the 2nd century <MS>B.<|>C.<D>. He was ç
the son of Go<207>ik<193>. His father's name is not known. He had ç
his education at Tak<218>a·il<193> (Taxila, now in Pakistan). He was ç
a familiar figure in the countries called V<193>h<200>ka and G<193>ndh<193>ra.
The word `Pata<210>jali' means `one who fell into the cupped hand'. ç
When a sage of Gonarda (a country?) was praying to the Sun-god with ç
water in his cupped-hands (= a<210>jali) a little baby fell `from ç
the <193>k<193>·a' (or sky) into it. He gave that baby-boy to a woman ç
called Go<207>ik<193> (who had no children) to be brought up.
According to another version, Go<207>ik<193>, the daughter of a sage, ç
was offering arghya (sacred water in hand, joined as a cup) to S<220>rya ç
(Sun-god) with the specific desire of getting a son when a baby-boy ç
fell into her hands. This baby-boy was none other than °di·e<218>a, ç
the king of serpents and the bed of Lord Vi<218><207>u!
Hindu tradition ascribes three works to Pata<210>jali. He wrote them ç
to help people to cleanse the impurities of their body, speech and ç
mind. The first one is a work on the °yurveda which has not been traced ç
till now. (Some scholars opine that the Carakasa<221>hit<193> is ç
actually his work, though others disagree.) The second one is his ç
Mah<193>bh<193><218>ya on the s<220>tras of P<193><207>ini, a well-known ç
work of Sanskrit grammar, called A<218><219><193>dhy<193>y<200>. ç
The last is the Yoga-s<220>tras.
@SPACE1 = 
The Mah<193>bh<193><218>ya is in 85 <193>hnikas or sections. Its ç
diction is most elegant and has been considered as a model for Sanskrit ç
prose. Apart from the explanations of the s<220>tras of P<193><207>ini, ç
this commentary contains a lot of additional information and discussions.
Though this Mah<193>bh<193><218>ya has several commentaries, the ç
Prad<200>pa of Kaiya<219>a (circa 5th cent. <MS>A.<|>D.<D>) is the ç
most well-known.
The Yogas<220>tras is the basic text for Yoga philosophy and practice ç
of yoga. It has several commentaries of which the Bh<193><218>ya ç
of Vy<193>sa (<MS>A.<|>D.<D> 600) and the Tattvavai·<193>rad<200> ç
of V<193>caspati (<MS>A.<|>D.<D> 850) on this Bh<193><218>ya are ç
the best-known.
See also <MS>A<186><187>°DHY°Y®<D> and <MS>P°ØINI.
@NT = patitas<193>vitr<200>ka
@N1 = (`[one who has] fallen [from the sacrament of being taught the] ç
S<193>vitr<200> [mantra]')
In the ancient days, for a dvija (the `twice-born' class, viz., a ç
br<193>hma<207>a, a k<218>attriya and a vai·ya), to be initiated into ç
the S<193>vitr<200> or the G<193>yatr<200> mantra was considered as ç
an absolute necessity. This initiation gave him the right to study ç
the Vedas, perform Vedic sacrifices and attain some status in the ç
society.
Sometimes, due to some unknown or extraordinary reasons, a person ç
might have missed this sacrament even after the proper or the permitted ç
age is past (this age being 8 to 16 years in the case of br<193>hma<207>as ç
11 to 22 years for k<218>attriyas and 12 to 24 for vai·yas).
Such persons came to be known as `patitas<193>vitr<200>kas'. They ç
were deprived of the right to Vedic studies and were treated almost ç
as outcastes.
In case such persons wanted the upanayana sacrament (along with the ç
teaching of the S<193>vitr<200>mantra) to be performed, they had to ç
undergo some pr<193>ya·cittas or expiations.
Different writers of dharma·<193>stras prescribed different kinds ç
of expiations such as: undergoing the disciplines of brahmacarya or ç
studenthood for two months after which his upanayana could be performed; ç
or, the performance of udd<193>lakavrata (subsisting on barley gruel ç
for two months and so on) (See <MS>UDD°LAKA-VRATA<D> for details.); ç
or, three pr<193>j<193>patya penances (See <MS>PR°J°PATYA.<D>) and ç
so on.
In case the father, or father and grandfather, of the patitas<193>vitr<200>ka ç
were also fallen ones (in this sense), the penances were harsher.
@NT = pativrat<193>
@N1 = (`[a woman] deeply devoted to her husband')
Conjugal felicity depends to a very great extent on mutual trust and ç
concern, between the husband and the wife. Though this was stressed ç
as the general rule, the onus was much more on woman than on man.
Perhaps to help the wife by moral support and encouragement, the virtue ç
of being<|> a pativrat<193>†a chaste wife†was eulogised highly in the ç
scriptures, especially in the dharma·<193>stras and the pur<193><207>as.
Single-minded devotion and service to her husband as also the rigid ç
observance of all the rules prescribed for her†voluntarily and willingly†made ç
her a pativrat<193>.
The definition of a pativrat<193> given by B<216>haspati and quoted ç
by other authors of dharma·<193>stras, gives us, perhaps, the best ç
idea of that ideal: `She is distressed when her husband is distressed ç
and isdelighted when he is delighted. She becomes emaciated and wears ç
soiled clothes when her husband goes out on a journey. And, she dies ç
when her husband dies!'
The following women are held before the Hindu society as the ideal ç
pativrat<193>s fit  to  be  emulated:  S<200>t<193>,  S<193>vitr<200>, ç
Damayant<200>, Anas<220>y<193> and Draupad<200>.
Other lists include Sat<200>, P<193>rvat<200>, Arundhat<200> and <185><193><207><195>ili.
The Mah<193>bh<193>rata (Vanaparva chs. 205-206) describes how ç
a devoted wife attained  everything  including  yogic powers, just ç
by serving her husband.
The story of S<193>vitr<200> who succeeded in bringing her husband ç
back from the clutches of Yama (the god of death) is too well-known ç
to be repeated (vide Vanaparva of Mah<193>bh<193>rata, chs. 293-299).
@SPACE = 
@NT = patn<200>·<193>l<193>
@N1 = (`a shed for the wife')
@SPACE1 = 
Vedic sacrifices involved the construction of large (temporary) sheds ç
meant for various purposes. One such shed with the bamboo beams protruding ç
towards the east was called `pr<193>c<200>nava<221>·a'.
In this shed a small part was set apart and screened off where the ç
patn<200> or the wife of the yajam<193>na (the sacrificer) was supposed ç
to stay during the perfor-mance of the pravargya, a minor rite in ç
a somay<193>ga, which she was not supposed to see. Hence the name.
@SPACE = 
@NT = Pa<219><219>adakal
@SPACE1 = 
India is dotted with temples, both ancient and modern.
The earliest temples could have been built with easily perishable ç
materials like wood and hence have not survived the ravages of weather ç
and time. Only when they were built in stone, they have lasted for ç
centuries.
Some of the earliest of such temples are  found  in  Aiho<202>e  and  Pa<219><219>adakal ç
(Bijapur district of Karnataka State). Situated on the left bank of ç
the river Malaprabh<193>, the village Pa<219><219>adakal is hardly ç
four acres in area and is surrounded by a stone-wall, like a fort.
It is said that some of the kings ofseveral dynasties†the Nandas, ç
the Guptas, the Kadambas and the Co<202>as† used to have their pa<219><219><193>bhi<218>eka ç
(coronation ceremony) here. Hence the name `Pa<219><219>adakal'.
Known by other names such as Hamm<200>ranagara, Pa<219><219>a·il<193>pura, ç
Pe<219>irgala, Kisuvo<202>al and Raktapura, Pa<219><219>adakal was ç
once a prosperous town. It was also the capital of the king K<200>rtivarma ç
of the Ca<202>ukyan dynasty.
Along with Aiho<202>e (in the same district), Pa<219><219>adakal is ç
famous for its several old and big temples (ten in number), of which ç
the following are more well-known: Mallik<193>rjuna, P<193>pan<193>tha, ç
and Vir<220>p<193>k<218>a.
The Mallik<193>rjuna temple is small and might have been built during ç
the early part of eighth century. There are three sanctums for Brahm<193>, ç
Vi<218><207>u and <185>iva. Incidents from the epics have been carved ç
on some of the pillars. The various images have a nice appearance.
The P<193>pan<193>tha temple is dedicated to <185>iva. It is in fairly ç
good condition with the <185>ivali<209>ga in the sanctum intact. Its ç
architectural style is a mixture of the dr<193>vi<195>a (South Indian) ç
and the n<193>gara (North Indian). The outer wall on the south contains ç
embossed figures of almost the entire R<193>m<193>ya<207>a.
The Vir<220>p<193>k<218>a temple†also known as Loke·vara temple†built ç
by the queen Lokamah<193>dev<200> (wife of the king K<200>rtivarma, ç
the second, and daughter of the Haihaya king) during the early part ç
of the 8th century <MS>A.<|>D.<D>, is the biggest of the temple complex ç
at Pa<219><219>adakal. Apart from a pr<193>k<193>ra or an outer wall, ç
it has two main gates. Nandima<207><195>apa has been built separately. ç
There are three structures forthe Trim<220>rtis (Brahm<193>, Vi<218><207>u ç
and Mahe·vara) also. Figures depicting scenes from the R<193>m<193>ya<207>a, ç
decorative windows and a squarish ·ikhara (of the dr<193>vi<195>ian ç
style) are the other features.
Other temples in the complex are those of K<193>·<200>vi·ve·vara, ç
Sa<209>game·vara, Ga<202>agan<193>tha, and Jambuli<209>ga.
Several stone edicts belonging to the period 8th and 9th centuries ç
have been found at these temple sites.
The names of some of those involved in the construction of these temples ç
havebeen inscribed here and there. Someof them are: Reva<195>i Ovajja ç
and Aniv<193>rita-gu<207><195>a (Sthapatis or architects); Ce<209>gamma, ç
Pullappan Nirm<193><207>adeva, Baladevayya and Deva °rya (·ilpis or ç
sculptors); Acalan (n<193><219>ya·<193>stra prav<200><207>a, expert ç
dancer).
The Aiho<202>e-B<193>d<193>mi-Pa<219><219>adakal <|>group of  temples  has  been  considered  a ç
great archaeological treasure and is being protected as such.
@SPACE1 = 
See also <MS>AIHO<170>E<D> and <MS>B°D°MI<D>.
@NT = pa<219><219>in<200> cult
@N1 = (`the cult of a chaste wife')
@EMERGENCY = Associated with the cult of <185>akti or the Divine Mother, ç
cults of some minor goddesses also grew, either round them or independently.
@EMERGENCY = Some of these goddesses were personifications of certain ç
dreadful diseases like smallpox. They had to be specially appeased ç
to be freed from these diseases. Some of them again, were human beings ç
like Draupad<200>, the queen of the P<193><207><195>avas, and those ç
who committed sat<200> (dying on the funeral pyres of their husbands) ç
raised to the level of a divinity in course of time.
@EMERGENCY = One cult that arose chiefly in Tamil Nadu was centred ç
round Kannagi†the wife of Kovalan†a paragon of wifely virtues and ç
chastity. It was called the pa<219><219>in<200> cult. (The word pa<219><219>in<200> ç
seems to be a corrupted form of the Sanskrit word patn<200> or wife.)
@EMERGENCY = The cult gradually spread from Tamil Nadu to Ceylon (now ç
Sri Lanka).
@EMERGENCY = An annual celebration with decoration and some sort of ç
worship seems to be a characteristic of such cults.
@NT = paur<207>am<193>s<200>-vratas
@N1 = (`vratas performed<R>ç
on a paur<207>am<200> or full-moon day')
This refers to a number of vratas or religious rites performed on ç
a paur<207>am<200> day (full-moon day).
Some of them are: °<218><193><195>hap<220>r<207>im<193> (June-July): ç
This is also known as Guru-p<220>r<207>im<193> or Vy<193>sap<220>r<207>im<193>. ç
On this day the yatis or sa<221>ny<193>sins (Hindu monks) are expected ç
to have a shave and begin their C<193>turm<193>syavrata, spread over ç
four or two months. During this period they are not expected to have ç
a shave again. (See also <MS>C°TURM°SYA.<D>)
<185>r<193>va<207>ap<220>r<207>im<193> (July-August): On this occasion ç
up<193>karma has to be performed by the followers of the <184>gveda ç
and the Yajurveda. See <MS>UP°KARMA<D> for more details.
Bh<193>drapadap<220>r<207>im<193> (August-September): This day is ç
sacred for the performance of n<193>nd<200>mukha-·r<193>ddha for the ç
gratification of the pit<216>s or manes. See <MS>°BHYUDAYIKA <185>R°DDHA.<D>
Pau<218>ap<220>r<207>im<193> (December-January): By bathing the ç
image of V<193>sudeva in ghee and by worshipping the gods Vi<218><207>u, ç
Indra and B<216>haspati on this day, a person attains prosperity in ç
life.
Ph<193>lgunap<220>r<207>im<193> (February-March): This being the ç
day of the Holi festival which includes Holik<193>dahana (burning ç
to ashes the ogress Holik<193>) or K<193>madahana (burning K<193>ma ç
or Cupid)†an occasion dear to boys†they are allowed to steal firewood ç
for this purpose!
@SPACE = 
@NT = Pau<218>kar<193>gama
@SPACE = 
The Pau<218>kar<193>gama is a minor work and is said to be a supplement ç
to the P<193>rame·var<193>gama, which itself is listed as the 26th ç
of the major <185>aiv<193>gamas.
Though it has been quoted in some other important works like the Sarva-dar·anasa<209>graha ç
of M<193>dhav<193>c<193>rya (<MS>A.<|>D.<D> 1297-1386), the full text ç
has not been secured till now.
Out of the four p<193>das which every <193>gama is said to contain†Kriy<193>p<193>da, ç
Caryap<193>da, Yogap<193>da and Vidy<193>p<193>da or J<210><193>nap<193>da†this ç
work as available in print today has only the last section.
There are eight pa<219>alas or sections containing a total of 971 ç
·lokas or verses.
The origin of the title Pau<218>kar<193>gama seems to be rather ç
obscure. The present text is in the form of a dialogue between Lord ç
<185>iva and some sages.
The contents may be briefly summarised as follows:
There are six categories out of which <185>iva is pati or the Supreme ç
Lord. Thej<200>vas or individual souls are pa·us (animals, the bound ç
ones).
Bindu is the manifold creation shrunk into a point as it were, after ç
pralaya or destruction.
When <185>iva wills for the next cycle of creation†this is called ç
`sa<209>kalpa' in the <193>gama†his <185>akti (which is inherent in ç
him) operates on the bindu (which, actually, is the material cause ç
of this universe) and makes it evolve into this world.
The j<200>vas or individual souls are eternal. But they have got into ç
bondage (= p<193>·a) due to malas or impurities such as moha (delusion), ç
mada (arrogance), r<193>ga (attachment), vi<218><193>da (sorrow) and ç
so on.
General yogic practices including yama and niyama help the j<200>vas ç
to be cleansed of the malas and regain their original state fully.
The work also devotes some space to describe four pram<193><207>as ç
or means of knowledge.
They are: pratyak<218>a (direct perception), anum<193>na (inference), ç
<185>abda or °gama  (the  Vedas)  and  arth<193>patti (presumption).
See also <MS>°GAMAS<D> and <MS><185>AIVISM.<D>
@SPACE1 = 
Um<193>pati <185>iv<193>c<193>rya (14th cent. <MS>A.<|>D.<D>) has written ç
a commentary. From it, one can safely presume that the full text of ç
the Pau<218>kar<193>gama was available at that time and was quite ç
popular.
@NT = Pavah<193>r<200> B<193>b<193>
@N1 = (`the saint whose food was air')
@SPACE = 
It is the sages and saints†whether of the past or of the present†that ç
have shaped the religio-cultured history of India over the last few ç
millennia.
One such highly respected person who lived towards the end of the ç
19th century was Pavah<193>r<200> B<193>b<193>†sometimes called P<193>vanh<193>r<200> ç
B<193>b<193> also†the saint of Gh<193>z<200>pur near Allahabad in ç
Uttar Pradesh. He was a great devotee of Lord R<193>ma.
It is said that he left home at the early age of fifteen or sixteen ç
and started travelling as a religious mendicant. When he reached Badar<200>n<193>th, ç
the famous place of pilgrimage in the Him<193>layas, he found a great ç
saint who initiated him into the mysteries of yoga.
After spending a long time in austerities under his guidance he came ç
to Gh<193>z<200>pur and settled down there in a small cave-like structure. ç
He is said to have been immersed in sam<193>dhi here for a long period ç
of sixteen years!
When he opened his eyes, there was a huge crowd of people to see him ç
and get his blessings. They arranged a grand festival in hishonour ç
and fed a large number of people on that occasion. The B<193>b<193> ç
is said to have performed some miracles at that time.
An incident that is often quoted with regard to his greatness is how ç
a thief that came to steal was converted by his goodness and loving ç
concern.
@SPACE1 = 
Sv<193>mi Vivek<193>nanda had met him during his long sojourn as an ç
itinerant monk.
@NT = Pavam<193>nas<220>kta
@N1 = (`prayer concerning<R>ç
Pavam<193>na-Soma')
This is a well-known s<220>kta or prayer appearing  in  the  <184>gveda  (9.1.1-10). ç
Madhucchand<193> is the sage and Pavam<193>na-Soma is the deity. It ç
is composed in the g<193>yatr<200> metre.
This prayer is actually addressed to the soma juice considered as ç
a deity.
The word `pavam<193>na' literally means `flowing'; hence Pavam<193>na-Soma ç
is the deity of soma juice which is flowing.
However the word `pavam<193>na,' in course of time, came to be associated ç
with or applied to V<193>yu or the wind-god.
The <184>gvedic prayer requests the deity to flow in torrents, to ç
destroy the enemies (the demons), grant wealth and food as also strength.
It also mentions that when Indra, the king of gods, drinks this soma ç
juice, becomes exhilarated and fulfills all the desires of the supplicants ç
like destroying their enemies and granting wealth.
Dharma·<193>stra works often prescribe this s<220>kta to be used as ç
a mantra for the purification of the bones of a dead person; to be ç
repeated in ·r<193>ddha ceremonies; andas a purifier when sins have ç
been committed.
@NT = pavitra
@N1 = (`the pure,' `[what makes one ceremonially] pure')
While performing any religious rite, a Hindu is expected to wear a ç
`pavitra'. It is a ring-like loop made of darbha (Poa cynosuroides) ç
grass. It may be prepared either with three or two or even one darbha ç
leaf. It should be worn on the an<193>mika or the ring-finger, either ç
of the right hand or on the ring-fingers of both the hands.
The following are the occasions on which the pavitra is to be worn, ç
to attain ceremonial fitness: japa (repetition of the divine name ç
or mantras), homa (pouring oblations into a duly consecrated fire), ç
d<193>na (giving gifts), sv<193>dhy<193>ya (study of the scriptures, ç
especially the Vedas) and tarpa<207>a (giving oblations of water to ç
the pit<216>s or manes).
The word is also used to indicate the two pieces of darbha kept over ç
<193>jya (ghee) to purify it before homa, to the piece ofcloth used ç
by a sa<221>ny<193>sin to filter water while filling it into his kama<207><195>alu ç
(water-pot) and even to the yaj<210>opav<200>ta (the sacred thread).
@NT = Pavitr<193>ropa<207>a-vrata
It means investing the image of a deity with the pavitra or the sacred ç
cord. This ritual is supposed to set right all defects and mistakes ç
committed in all the p<220>j<193>s performed during that year. The ç
putting on of the pavitra in the case of several gods is done on different ç
days. It may be made of gold, silver, copper, silk or even ku·a or ç
cotton thread. It must have knots, the maximum number being 100 and ç
a minimum of 8.
@NT = Periy<193><202>v<193>r
@N1 = (`the great devotee')
See <MS>°<170>V°RS.<D>
@NT = Periyapur<193><207>am
@N1 = (`the great pur<193><207>a<R>ç
[mythological work]')
The sixtythree N<193>yanm<193>rs or N<193>yan<193>rs are the <185>aiva ç
saints of Tamil Nadu who spread the cult of devotion to Lord <185>iva ç
(as an aspect of Brahman, the Absolute), brought about a social revolution ç
that made all devotees of Lord <185>iva feel equal to one another ç
and also contri-buted to the disappearance of Jainism from the Tamil ç
land.
Their lives were found in a sketchy form loosely distributed among ç
various works and hearsays.
However, it was Sekkizh<193>r (11th cent. <MS>A.<|>D.<D>) who brought ç
together all the available information about these N<193>yanm<193>rs ç
in one place and wrote the now well-known classic the Periyapur<193><207>am. ç
He based his work on Tiru To<207><195>attokai of Sundaram<220>rti ç
(8th  cent.  <MS>A.<|>D.<D>)  and  the  Tiruto<207><195>ar Tiruvand<193>di ç
of Nambiandar Nambi (10th cent. <MS>A.<|>D.<D>).
The Periyapur<193><207>am is a remarkable composite work of hagiology ç
dealing with all the 63 lives. It is in 72 cantos and has 4286 verses.
The biographies of the four most well-known saints†Sundarar, Tiruj<210><193>na ç
Sambandhar, Appar and Tirum<220>lar†are dealt with in great detail. ç
The others have been portrayed briefly.
This work is also a literary master- piece. Good English translations ç
of the works have been published in the recent past.
See also <MS>N°YAN°RS.<D>
@NT = pilgrimage
See <MS>T®RTHAY°TR°.<D>
@NT = Pi<202><202>ai Lok<193>c<193>rya
See <MS><185>R®VAI<186>ØAVISM.<D>
@NT = Pin<193>ka
The various deities of the Hindu pantheon have certain objects held ç
in theirhands†including some weapons†as distinguishing marks.
Though <185>iva has the tri·<220>la (the trident) as the distinguishing ç
weapon, he also has a bow called `Pin<193>ka' which he uses occasionally ç
as in the destruction of Tripura or the three cities of the demons, ç
and the sons of T<193>rak<193>sura like T<193>r<193>k<218>a.
According  to  one  version,  <185>iva's trident once fell down and ç
got bent into the shape of a bow. This came to be known as the Pin<193>ka. ç
P<193>·upata is the chief arrow that is discharged from this bow.
The word is sometimes defined as `that which protects' (= p<193>ti, ç
rak<218>ati) people from evil forces.
See also <MS><185>IVA.<D>
@NT = pi<207><195>a
@N1 = (`lump of cooked rice')
See <MS><185>R°DDHA.<D>
@NT = Pi<207><195>apit<216>yaj<210>a
@N1 = (`sacrifice to the manes by offering rice balls')
Performance of the ·r<193>ddhas or obse-quial rites in honour of the ç
dead ancestors†generally of three generations†is an ancient custom. ç
It has its origin in such Vedic rites such as the pi<207><195>apit<216>yaj<210>a.
This rite is generally performed one day prior to the Dar·a sacrifice ç
by an <193>hit<193>gni (one who keeps the Vedic firesduly established). ç
The procedure is similar to that of the p<193>rva<207>a·r<193>ddha. ç
(See <MS><185>R°DDHA<D> for details.)
Three pi<207><195>as (rice-balls) have to be offered in the afternoon ç
to the pit<216>s or forefathers. The rice has to be cooked over dak<218>i<207><193>gni ç
(See <MS>DAK<186>IØ°GNI.<D>) and sprinkled with <193>jya or ghee. ç
At the time of offering the pi<207><195>as the performer has to wear ç
his yaj<210>opav<200>ta in the pr<193>c<200>n<193>v<200>ta form, i.e., ç
on the right shoulder, hanging on the left side, below the left arm. ç
(See<MS>NIV®TA.<D>)
Offerings are to be made in the dak<218>i<207><193>gni to gods and ç
Agni (as kavya-v<193>hana, carrier of offerings) first.
Reception rites to the pit<216>s, prayersto them followed by namask<193>ra ç
or obeisance, are some of the other rites.
@NT = pi<209>gal<193>
It is one of the three n<193><195><200>s connected with pr<193><207><193>y<193>ma. ç
It begins from the right nostril. It runs parallel to and on theright ç
ofthe su<218>umn<193>, which is in the middle.
See also <MS>I£°<D>, <MS>N°£®<D>, <MS>PR°Ø°Y°MA<D> and <MS>SU<186>UMN°.
@NT = Pi<209>gal<193>mata
@N1 = (`knowledge taught to the [goddess] Pi<209>gal<193> [by Bhairava-<185>iva]')
The Pi<209>gal<193>mata is a work belonging to the group of <185>aiv<193>gamas. ç
It is closely associated with the Brahmay<193>malatantra.
Cast in the form of a dialogue between the goddess Pi<209>gal<193> ç
and Bhairava, it is said to comprise 8000 verses; and, deals with ç
the method of establishing a li<209>ga (in a temple). Other subjects ç
described here are: definition of a li<209>ga, materials used to make ç
it, places fit for its installation, qualifications of an <193>c<193>rya ç
competent to worship it and those who are unfit to do so.
@NT = pip<200>lik<193>madhya
@N1 = (`the middle part of an ant')
See <MS>C°NDR°YAØA.<D>
@NT = Pippal<193>da
@N1 = (`one who eats pippala')
This is the name of a <216><218>i or sage. He might have got that ç
name because he used<|>to eat pippala (a kind of pepper orthe fruits ç
of a peepul tree) to maintain himself.
In the Pra·nopani<218>ad, Pippal<193>da is the great teacher who ç
was approached by six sages like Suke·a, <185>aibya and others. After ç
living with him as his disciples forone year, they put him questions ç
and got satisfactory answers. This dialogue between him and these ç
six sages forms the subject-matter of the Upani<218>ad.
According to the Mah<193>bh<193>rata (<185><193>ntiparva 47.9) ç
he was one of the sages present when the grandsire Bh<200><218>ma ç
taught Yudhi<218><219>hira, from his bed of arrows.
Naciketas is said to have taught him spiritual wisdom concerning the ç
life after death.
According to another version, he was the son of Dadh<200>ci and Suvarc<193>. ç
Padm<193>vat<200> was his wife. He is said to have advised <185>ani ç
(the malefic planet-deity) not to molest children below twelve years.
The Padmapur<193><207>a (chs. 60-62) des-cribes another Pippal<193>da, ç
a sage who had become arrogant due to the special powers he had obtained ç
by severe austerities. He was humbled by Brahm<193>, the four-faced ç
creator, through proper advice.
@NT = pi·<193>ca
@N1 = (`eater of flesh,' `a goblin')
Belief in devils, goblins, elves and evil spirits is common to almost ç
all the people of the world.
In the Hindu epics and mythological works they are called variously ç
as bh<220>tas, pretas, pi·<193>cas, yak<218>as and so on.
Out of these, the pi·<193>cas, the flesh-eating and blood-drinking ç
evil spirits, are the most malevolent, bent upon harming others. However, ç
being created by Brahm<193>, they too have a place in his creation!
They are unclean spirits confined to the antarik<218>a (the middle ç
regions). They also live in unclean and barren places.
In some pur<193><207>as they are described as belonging to the court ç
of Kubera, the king of Yak<218>as ruling at Alak<193>pur<200>. In ç
some other pur<193><207>as they are depicted as devotees of <185>iva ç
and living on the Mu<210>jav<193>n mountain.
@NT = pit<193>
@N1 = (`one who protects')
The Taittir<200>ya Upani<218>ad (1.11) declares that the father ç
is only next to the mother and should be honoured like agod. This ç
is but proper since he gives birth, education and culture to his offspring.
According to the sm<216>tis it is the father  who  performs  the  upanayana ç
sacrament and imparts the sacred G<193>yatr<200>- mantra to his sons.
Whether the father has a sense of ownership over his sons has been ç
a debatable point.
As regards the division of ancestral property, he could unequally ç
distribute it among his sons in the ancient days though in later days ç
it became mandatory to distribute it equally.
If he dies before clearing all his debts, his sons and grandsons were ç
obliged to clear the same.
According some dharma·<193>stra works the following are pit<193>s ç
or `fathers': anna-d<193>t<193> (one who gives food); bhayatr<193>t<193> ç
(one who  protects  from  dangers);  ·va·ura (father-in-law); janit<193> ç
(father); upanet<193> (one who performs upanayana).
@NT = p<200><219>ha
@N1 = (`seat')
In a general sense it means a thing upon which one sits.
However, in a technical sense, it indicates the pedestal of an icon.
The shape and the size of a p<200><219>ha depend upon the style of ç
the temple†such as n<193>gara, vesara or dr<193>vi<195>a†as also the ç
posture of the image. It is square for a seated (<193>s<200>na) image. ç
It can be rectangular or circular or even oval, if the image is in ç
the sth<193>naka (standing) pose.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
The height may be 12 a<209>gulas (See <MS>A<177>GULA.<D>) or just ç
<P8W1><$E1 over 5><P255D><|> the height of the image. In the case of ç
<185>ivali<209>gas, it should be 4or 5 times the diameter of the ç
cylindrical shaft.
Iconographical works describe p<200><219>has of several designs such ç
as bhadrap<200><219>ha or padmap<200><219>ha which give enough scope ç
to the sculptor to exhibit his skills.
The word p<200><219>ha is sometimes used to indicate a <185>aktip<200><219>ha, ç
a place of pilgrimage connected with <185>akti or Mother-goddess. ç
(See <MS>TANTRAS<D> for details.)
If it is used as a suffix, it gives different meanings. For example: ç
balip<200><219>ha (sacrificial altar); <185><193>rad<193>p<200><219>ha ç
(the monastic centre of Advaita Ved<193>nta at <185><216><209>ger<200>, ç
Karnataka) and so on.
@NT = Pit<216>g<193>th<193>
@N1 = (`song of the manes')
In Hinduism, the pit<216>s (forefathers or manes) have always been ç
respected. Normally, once a year, the descendants are expected to ç
pay homage to them through religious rites known as <185>r<193>ddhas.
It seems that†even as the descendants are eager to appease their pit<216>s†the ç
pit<216>s too hanker for such appeasement.
The Matsyapur<193><207>a (204.3-17), one of the eighteen Mah<193>pur<193><207>as, ç
contains an interesting piece, depicting such hankering. This has ç
come to be known as the Pit<216>g<193>th<193> or the Song of the ç
Manes. It is to be chanted as a part of ·r<193>ddha ceremonies, thus ç
making the br<193>hma<207>as invited for food, listen to it.
The g<193>th<193> expresses the desire of the pit<216>s to get good ç
food (in the ·r<193>ddhas), receive oblations of water in holy rivers, ç
and get a ·r<193>ddha performed at the holy pilgrim centre Gay<193> ç
(in Bihar). They will bless their descendants who donate a milch-cow ç
and a deerskin to a good br<193>hma<207>a, who will set free a bull ç
to roam about as it likes, who will donate gold or cow or a piece ç
of land to a deserving and needy person, who will perform public service ç
activities such as digging a well for drinking water and raising a ç
nice garden.
However, they are pleased immensely if their descendants become scholars ç
in the scriptures and great devotees of Lord Vi<218><207>u.
@NT = pit<216>loka
@N1 = (`the world of [dead] ancestors')
Just as a human being does not want to be destroyed after the death ç
of his body, he also does not want his forefathers and ancestors to ç
be destroyed after their death. The belief that one's dead-ancestors ç
live in a separate world is common to most of the peoples of the world.
The <184>gveda (10.14.2 and 7) mentions the pit<216>loka where one's ç
departed ancestors live.
The Upani<218>ads consider the pit<216>loka as a place that can be ç
attained by one after death, by performing sacrifices like Agnihotra ç
(B<216>had<193>ra<207>yaka 1.5.16), and also as a station on the ç
path of Pit<216>y<193>na (the path of manes, the path of smoke) (ibid ç
6.2.16).
@NT = pit<216>medha
@N1 = (`forefather-sacrifice')
The word actually means consigning the dead-body of a forefather to ç
the fire of cremation which is similar to a medha or a sacrifice.
This ancient custom comprised four stages: cremation, collecting the ç
charred bones and depositing them underground in an urn, expiatory ç
rites and erection of a monument (generally a pole or a staff).
Depositing the urn at the root of a tree or casting the contents in ç
the Ga<209>g<193> river were also practised.
If the deceased person was an <193>c<193>rya (spiritual or Vedic preceptor) ç
or a ·rotriya (learned in the Vedas) the rite was called brahmamedha. ç
The special mantras known as caturhot<193> (vide Taittir<200>ya ç
Br<193>hma<207>a 2.3.11.4; 1.3.1.1; 3.12.5.1; 2.2.3.5; 2.3.1.3; 2.3.1.1; ç
and 2.2.8.2) were chanted on this occasion.
@NT = pit<216>pak<218>a
@N1 = (`the fortnight dedicated to the forefathers')
The 15 days of the dark fortnight ofthe month Bh<193>drapada, are ç
called `Pit<216>pak<218>a' or `Mah<193>layapak<218>a' and the new-moon ç
day as `Mah<193>laya Am<193>v<193>sy<193>'. These days are considered ç
to be extremely auspicious for performing the obsequial rites to the ç
departed ancestors.
The story goes that Kar<207>a, the great hero of the Mah<193>bh<193>rata, ç
could not get any food to eat when he went, after his death, to the ç
higher regions, though he could get plenty of silver and gold there. ç
This was because he had donated plenty of gold and silver but not ç
food! Distressed much, he prayed to Yama, the god of death, and through ç
his grace returned to this earth during this Mah<193>layapak<218>a, ç
gifted plenty of food and then returned. Hence, annad<193>na or giving ç
food to the hungry, is an important duty enjoined in the observance ç
of these days.
On all the fifteen days, offerings are made to the departed manes, ç
including those whose names or manner of death are not known.
Men of the family generally observe some austerities during this period, ç
like not shaving the hair or the beard, not paring the nails and so ç
on. Feeding the priests with kh<200>r or p<193>yasa (pudding) during ç
this period is considered to be highly pleasing to the pit<216>s or ç
manes.
@NT = pit<216>-<216><207>a
@N1 = (`debt to the manes')
Every human being†according to Hinduism†is said to be born under three ç
<216><207>as or debts. Among these, the pit<216>-<216><207>a is the ç
second. This <216><207>a or debt can be repaid by marrying according ç
to dharma and having a son who will perform ·r<193>ddhas to the pit<216>s ç
or departed ancestors thereby appeasing them.
See <MS><184>ØATRAYA<D> for details.
@NT = pit<216>s
@N1 = (`fathers,' `ancestors')
@SPACE = 
The Sanskrit word `pit<216>' becomes `pit<193>' in the singular and ç
`pitara<199>' in the plural. Whereas the former means `father', the ç
latter has been used in several senses such as forefathers or ancestors, ç
a type of semi-divine beings inhabiting their own world called Pit<216>loka, ç
certain types of sages and so on.
The most common meaning as used in ·r<193>ddhas (obsequial rites) ç
is three generations of ancestors: father, grand- father and great-grandfather. ç
It is believed that during the performance of ·r<193>ddhas these pit<216>s ç
accept the offerings in the form of birds or by entering into the ç
invitee br<193>hma<207>as through their subtle bodies.
According to another version (M<193>rka<207><195>eyapur<193><207>a ç
ch. 45) they were created as a separate class of beings along with ç
devas (gods), r<193>k<218>asas (demons) and m<193>navas (human beings), ç
by Brahm<193> the creator himself.
They are also, sometimes, identified with the Sapta<216><218>is or ç
the seven sages, the progenitors of mankind, as the originators of ç
gotras or lineages.
Several classes of pit<216>s such as A<209>girasas, Vair<220>pas or ç
Bh<216>gus have been mentioned in the <184>gvedic verses (vide 10.14.5 ç
and 6). Occasionally they have also been divided into three grades ç
by the same Veda (10.15.1).
The pit<216>s can be satiated through proper rites and they can bless ç
their descendants by granting boons.
See also <MS><185>R°DDHA.
@NT = pit<216>yaj<210>a
@N1 = (`sacrifice unto the forefathers')
See <MS>PA<178>CAMAH°YAJ<178>AS.<D>
@NT = Pit<216>y<193>na
@N1 = (`the path of manes')
@SPACE = 
Literally, the word means the path by which a pit<216> or a dead ancestor ç
goesto the Candraloka or the world of the moon.
We find from the Upani<218>ads (and even the Bhagavadg<200>t<193> ç
8.24-26) that the ancient Hindus believed in two paths by which the ç
soul of a dead person could go, either to the Brahmaloka or to the ç
Candraloka.
The former was called Devay<193>na (or Arcir<193>dim<193>rga) and ç
the latter as Pit<216>y<193>na (or Dh<220>m<193>dim<193>rga).
The various stations mentioned in the Pit<216>y<193>na are: dh<220>ma ç
(smoke), r<193>tri (night), aparapak<218>a (dark fortnight), dak<218>i<207><193>yana ç
(southern solstice), pit<216>loka (world of manes), <193>k<193>·a ç
(space), and Candramas ([world of] Somar<193>ja or the king Moon).
These words represent the various guides on the path.
Those who perform Vedic rites like Agnihotra and public utility activities ç
like digging wells or planting trees etc., go by this path to the ç
Candraloka (the world of the Moon) and return to the earth after exhausting ç
their religious merit. This world (Candraloka) is more like a heaven ç
from which there is return.
See <MS>DEVAY°NA<D> for more details.
@NT = planets
See <MS>NAVAGRAHAS.
@NT = pl<193>vin<200>
@N1 = (`that which makes one float and flow')
The art and science of controlling the pr<193><207>a (vital air, life-force) ç
is technically called pr<193><207><193>y<193>ma. Kumbhaka is its third
