@NID = aspect where retention of breath is the most important function.
This kumbhaka is of nine types of which pl<193>vin<200> is also one. ç
In this, the belly is filled with the air that is circulating within ç
the body, making the body light enough to float even on deep waters, ç
like the leaf of a lotus.
Of course, the technique itself, mentioned in the works like the Ha<219>hayoga-prad<200>pik<193> ç
(2.70), should be learnt and mastered from an expert in the field.
@NT = polyandry
See <MS>VIV°HA.<D>
@NT = polygamy
See <MS>VIV°HA.<D>
@NT = Po<209>gal
In Tamil Nadu, the Makara Sa<209>kr<193>nti is a harvest festival ç
and is called Po<209>gal. Po<209>gal is a kind of sweet preparation, ç
made out of sugar or jaggery, rice, ghee and milk. It is prepared ç
from the newly harvested crops and offered to the Sun-god. The day ç
prior to the Po<209>gal day, is called bhogi. It is a day dedicated ç
to changing the old articles in the house for the new (especially ç
old clothes) and consigning them to flames. The day after the Po<209>gal ç
day is reserved for the observance of the `Cattle Day' with bull-fights ç
or taming the wild bulls by the strong young men of the village.
@NT = Prabandham
See <MS>DIVYAPRABANDHAM.
@NT = Prabodhacandrodaya
See <MS>K<184><186>ØAMI<185>RA<D>.
@NT = Prabh<193>kara
@N1 = (8th cent. <MS>A.<|>D.<D>)
The M<200>m<193><221>s<193> philosophy, one of the six systems of ç
Hindu philosophy, is based primarily on the P<220>rvam<200>m<193><221>s<193>s<220>tras ç
of Jaimini (400 <MS>B.<|>C.<D>). Out of the several bh<193><218>yas ç
(commentaries) known to have existed on that basic work, only that ç
of <185>abarasv<193>min (<MS>A.<|>D.<D> 500) has survived to this day.
Prabh<193>kara Bha<219><219>a (or Prabh<193>kara) and Kum<193>rila ç
were the two most important teachers of this school who have written ç
commentaries on the Bh<193><218>ya of <185>abara. They were contemporaries.
Prabh<193>kara†nicknamed as `Guru'† has followed <185>abara faithfully ç
in his detailed gloss called B<216>hat<200>. His school has become ç
known as Bh<193><219><219>amata or Gurumata.
There is a sub-commentary on this B<216>hat<200> by one <185><193>likan<193>tha ç
Mi·ra, known as <184>juvim<193>l<193>.
Practically nothing is known of him. Tradition holds that he was a ç
pupil of Kum<193>rila.
@NT = prabh<193>ma<207><195>ala
@N1 = (`circle of light')
Behind the icons ceremonially established in temples and meant for ç
worship, there is, invariably, an arch of effulgence (like the solar ç
orb). This is generally made of metal strip and encompasses the image. ç
It is this that is called `prabh<193>ma<207><195>ala' or `prabh<193>val<200>'. ç
It may be round or elliptical in shape and has ornamental designs. ç
It is supported on either side by a pillar-like motif or structure. ç
The top-centre part has the head of a leonine figure known as the ç
k<200>rtimukha. (See <MS>K®RTIMUKHA<D> for details.)
The prabh<193>ma<207><195>ala is a detachable unit. The metal strip ç
may have a support of wooden strip.
If the image in the temple is of stone, the prabh<193>ma<207><195>ala ç
is also etched in stone.
@NT = Prabh<193>sa
@N1 = (`[a place that] shines<R>ç
brilliantly')
Prabh<193>sa†also known as Prabh<193>sa Pa<219><219>a<207>a†is an ç
ancient and famous place of pilgrimage containing the renowned Somn<193>th ç
Temple. (See <MS>SOMAN°THA TEMPLE<D> for its details.) It is situated ç
in the Kathewar region of Gujarat State in western India.
During the days of the Mah<193>bh<193>rata it was a well-known and ç
flourishing city. The P<193><207><195>avas had visited this place ç
of pilgrimage since it was at the confluence of the three holy rivers ç
Hira<207>y<193>, Kapil<193> and Sarasvat<200> which joined the sea ç
here. It was here that Arjuna, the famous P<193><207><195>ava hero, ç
abducted Subhadr<193> (sister of <185>r<200> K<216><218><207>a) with ç
his help. Again, it was here that the Y<193>dava race exterminated ç
itself by infighting after which Balar<193>ma and <185>r<200> K<216><218><207>a ç
gave up their bodies.
There ia a small temple, built in the recent years†maybe on the ruins ç
of an old one†at the spot where <185>r<200> K<216><218><207>a is said ç
to have given up his physical body.
There are a few other temples here dedicated to Mah<193>k<193>la (<185>iva), ç
Ga<207>e·a and Balar<193>ma.
Pur<193><207>as like the Sk<193>nda extol its greatness  in  hyperbolic  terms.  For ç
instance: It was here that Candra (Moon-god) was cured of his disease ç
of consumption. The alligators in the sea here are harmless. The li<209>ga ç
(in the Somn<193>th Temple) is one of the twelve Jyotirli<209>gas, ç
and so on.
@NT = pr<193>c<200>n<193>v<200>ta
@N1 = [(the sacred thread) that is worn after taking it round']
According to the dharma·<193>stras (secondary scriptures dealing with ç
the var<207>a-<193>·rama-dharmas and related topics) every `dvija' ç
(`the twice-born') must wear the yaj<210>opav<200>ta or the upav<200>ta ç
(the sacred thread). This is normally worn on the left shoulder, its ç
right part hanging below the right arm. This mode of wearing, called ç
the yaj<210>opav<200>ta-mode, is maintained for all normal religious ç
rites concerning the gods or the deities. However, in the rites concerning ç
the pit<216>s or manes (for e.g., ·r<193>ddha ceremonies) this mode ç
of wearing is reversed. The thread is worn on right shoulder, the ç
lower part hanging below the left arm. This is called `pr<193>c<200>n<193>v<200>ta' ç
mode or `<193>v<200>ta' mode.
See also <MS>YAJ<178>OPAV®TA<D>.
@NT = pradak<218>i<207>a
@N1 = (`circumambulation')
See <MS>NAMASK°RA.<D>
@NT = Pr<193>de·am<193>tra
@N1 = (`of the dimension of<R>ç
pr<193>de·a')
This is a technical term specially used in the Ch<193>ndogya Upani<218>ad ç
(5.18.1) to indicate ®·vara or God who is the Self of all. The Upani<218>ad ç
has used the word `Vai·v<193>nar<193>tman' to indicate ®·vara and ç
calls him `Pr<193>de·am<193>tra'.
The word `pr<193>de·a' means space. He whose pr<193>de·a extends from ç
the dyuloka (heaven) as the head and the p<216>thv<200> (earth) as ç
the feet is `Pr<193>de·am<193>tra'.
The word may also mean the Self within, who enjoys the food that is ç
eaten through the mouth.
@NT = pradh<193>na
@N1 = (`the chief one')
See <MS>S°<177>KHYA DAR<185>ANA.<D>
@NT = pradhva<221>s<193>bh<193>va
@N1 = (`non-existence after destruction')
See <MS>ABH°VA.<D>
@NT = prado<218>a
@N1 = (`that which is full of do<218>a or defect')
Any religious act should take into consideration the purpose as also ç
the time and place before it is undertaken.
In this, k<193>la or time is a very important factor. Certain periods ç
of time are considered as auspicious and certain others, inauspicious. ç
One of these is prado<218>a.
It is the period of six gha<219>ik<193>s after sunset (1 gha<219>ik<193> ç
= 24 minutes). Some authorities reduce it to three gha<219>ik<193>s ç
also.
Though generally this is considered as inauspicious†say, for the study ç
of the scriptures†it is specially recommended for taking food by one ç
who is observing the vow of nakta; i.e., eating once only in the day, ç
and that too, at night. This applies to one observing ek<193>da·<200> ç
as a vrata or fasting as an expiation.
See also <MS>EK°DA<185>®.<D>
@NT = Pradyumna
Pradyumna was a reincarnation of Manmatha (the god of love, Cupid). ç
He was born as the son of K<216><218><207>a and Rukmi<207><200>. He ç
was considered as a partial manifestation of the sage Sanatkum<193>ra.
As soon as he was born, the demon <185>ambar<193>sura is said to have ç
abducted him and thrown him into the sea, where a big fish swallowed ç
him. The fishermen who caught it brought it to the palace kitchen ç
of <185>ambara. The cooks, on cutting it found a baby inside it! This ç
baby was then adopted by M<193>y<193>vat<200>, the chief maid of <185>ambara's ç
queen and brought him up. Shewas actually Rati, Manmatha's queen ç
in disguise. Later on Pradyumna killed <185>ambara and married M<193>y<193>vat<200>.
He is said to have died during the infighting among the Y<193>davas.
See also <MS>CATURVY<188>HAS.<D>
@NT = pr<193>gabh<193>va
@N1 = (`non-existence before<R>ç
[production]')
See <MS>ABH°VA.<D>
@NT = Prahl<193>da
Prahl<193>da, the king of child-devotees of Lord Vi<218><207>u, was ç
the eldest son of Hira<207>y<193>ka·ipu, the powerful king of the ç
daityas or demons. His mother was Kay<193>dhu, the daughter of the ç
demon-king Jambh<193>sura. She too, being initiated by the great sage ç
N<193>rada, was a devotee of Vi<218><207>u.
His story is delineated in detail in the Bh<193>gavata (7.4 to 8) ç
and the Vi<218><207>upur<193><207>a (1.17).
He alienated his father, who was an inveterate hater of Lord Vi<218><207>u, ç
by his matchless devotion to Vi<218><207>u. All the efforts of Hira<207>yaka·ipu ç
to get him killed were set at naught by the protection Vi<218><207>u ç
gave him. Ultimately Vi<218><207>u killed Hira<207>ya-ka·ipu by assuming ç
the Narasi<221>ha (Man-lion) form. Prahl<193>da's prayer to the Lord ç
Narasi<221>ha liberated Hira<207>yaka·ipu from all his sins.
Prahl<193>da's teaching about the navavidhabhakti or the nine modes ç
of devotion (vide Bh<193>gavata 7.5.23) is widely accepted and acclaimed.
He had four brothers and three sons as also a daughter.
The famous king Bali who too was a great devotee of Vi<218><207>u, ç
was his grandson.
Prahl<193>da has been shown in the pur<193><207>as as having had many ç
learned discussions with others like Bali, Ha<221>sa, Indra and the ç
sage Ajagara, about dharma.
@SPACE = 
@NT = Praj<193>pati
@N1 = (`Lord of beings')
@SPACE = 
The word `Praj<193>pati' has been widely used in the Vedic literature, ç
the Upani<218>ads, the epics and the pur<193><207>as.
Literally, the word means `one who is the Lord of living beings.' ç
It was first used for the four-faced Brahm<193>, the creator. Later ç
on, it was used to indicate the nine m<193>nasaputras or mind-born ç
sons of Brahm<193> like Kardama, Mar<200>ci, A<209>girasa, Dak<218>a ç
and others, who were also great sages.
In the Upani<218>ads he is shown as a teacher of spiritual wisdom ç
(vide, Ch<193>ndogya Upani<218>ad 8; B<216>had<193>ra<207>yaka ç
Upani<218>ad 5.2).
The Bhagavadg<200>t<193> (3.10-12) describes him as giving special ç
instructions to the gods and the human beings after creating them ç
and yaj<210>a or sacrifice as a link between them.
@NT = Praj<193>pati Sm<216>ti
The Sm<216>tis of Baudh<193>yana and Vasi<218><219>ha as also the ç
commentary Mit<193>k<218>ar<193> on the Yaj<210>avalkya Sm<216>ti ç
quote several verses from a Praj<193>pati Sm<216>ti. Since most ç
of these verses are found in the extant Manusm<216>ti and since ç
Manu is sometimes counted among the Praj<193>patis, it is likely that ç
the word Praj<193>pati Sm<216>ti may actually refer to the Manusm<216>ti ç
only.
There is a printed edition bearing the title Praj<193>pati Sm<216>ti ç
containing 198 verses. However, the verses quoted in the works mentioned ç
above do not figure in this work.
The topics attributed to Praj<193>pati in all these works or quotations ç
are: ·r<193>ddha (obsequial rites); references to some of the signs ç
of the zodiac like Kany<193> and V<216>·cika; a·auca (ceremonial impurity); ç
pr<193>ya·cittas (expiations for sins); on parivr<193>jakas (sa<221>ny<193>sins ç
or monks); witnesses and their reliability in disputes; rights of ç
a sonless widow to succeed to her husband's property as also to offer ç
·r<193>ddha and soon.
@NT = pr<193>j<193>patya
@N1 = (`related to Praj<193>pati')
Listed among the k<216>cchras (a kind of expiations for sins), the ç
pr<193>j<193>patya is spread over four periods of three days each. ç
The person observing it has to eat once only by day during the first ç
period, once only by night during the second period, eat only that ç
food which may be got unasked during the third period and fast completely ç
on the last three days.
This order may also be reversed.
While prescribing a k<216>cchra, if no particular name†such as taptak<216>cchra ç
or par<207>ak<216>cchra†is mentioned, then it is to be understood ç
that it is the pr<193>j<193>patya that is referred to.
The word also means the br<193>hm<200>-muh<220>rta (45 minutes before ç
sunrise) and a form of marriage (one of the eight varieties). See ç
<MS>VIV°HA<D> for details.
See also <MS>K<184>CCHRA.<D>
@NT = pr<193>j<210>a
@N1 = (`one who knows well')
The Ved<193>nta philosophy, based mainly on the Upani<218>ads, has ç
utilised the technique of avasth<193>trayaviveka†an analysis of the ç
three states of consciousness†for proving the existence of a conscious ç
soul (the j<200>v<193>tman or the <193>tman) as separate from the ç
body-mind complex. (See <MS>AVASTH°TRAYA<D> for details.)
The three states of consciousness are: j<193>grat (the waking state), ç
svapna (the dream state) and the su<218>upti (the deep-sleep state).
The j<200>v<193>tman as associated with these three states of consciousness ç
is respectively known as vi·va, taijasa and pr<193>j<210>a.
In the j<193>grat state, the j<200>v<193>tman identifies himself with ç
the physical body as also the mind. In the svapna state, identification ç
with the physical body is transcended but that with the mind still ç
remains. In the su<218>upti state, even the mind is transcended and ç
the j<200>v<193>tman is aware of only himself and as a s<193>k<218>i ç
or witness. It is in this state that he is called `pr<193>j<210>a'.
He is designated as `pr<193>j<210>a' since praj<210>apti or consciousness ç
is his only characteristic or form (`praj<210>aptim<193>tram').
However, the Ved<193>ntas<193>ra of Sad<193>-nanda (44) defines ç
him as `pr<193>ye<207>a aj<210>a<199>.' `He is ignorant to a great ç
extent' since his conscious nature is overcome by aj<210><193>na, ç
by rajas and tamas (vide the commentary Vidvanmanora<210>jan<200> ç
on the section 44).
See M<193><207><195><220>kya Upani<218>ad 9 to 11 for a description ç
of these three states of the j<200>v<193>tman.
@SPACE = 
@NT = praj<210><193>jyoti
@N1 = (`[the yogi who possesses] the light of consciousness')
See <MS>PRATHAMAKALPIKA.
@SPACE = 
@NT = prak<193>ra
@N1 = (`mode')
This is a technical term used in some philosophical works of Ny<193>ya ç
(logic) and M<200>m<193><221>s<193> (Vedic ritualism).
A prak<193>ra is that which distinguishes something from the common ç
group. For instance, dravya or a substance is stated to be of nine ç
types. P<216>thv<200> (earth), one of them, is a prak<193>ra or mode ç
of that dravya.
In the phrase `da<207><195>av<193>n puru<218>a<199>' (the person with ç
the stick) da<207><195>a or stick is the prak<193>ra or mode that ç
distinguishes him from others.
Implication and similarity are other senses in which the word is used.
@SPACE = 
@NT = pr<193>k<193>ra
@N1 = (`surrounding wall')
A Hindu temple is often surrounded by a high wall or enclosure called ç
`pr<193>k<193>ra'. It is like a fort protecting the temple. Built ç
of such materials as stone or brick or even wood, it often contains ç
the gopurams or main entrance gates which may vary in number from ç
one to four. The <185>r<200>ra<209>gam temple of Ra<209>gan<193>tha ç
(in Tamil Nadu) has seven pr<193>k<193>ras.
The  pr<193>k<193>ra  may  also  provide accommodation for the shrines ç
of pariv<193>ra-devat<193>s (attendant deities) of the main god.
In the pr<193>k<193>ras of old temples, artistically carved designs ç
and even inscriptions have been found.
In the <185><193><209>kh<193>yana <185>rautas<220>tras (16.18.14) ç
it denotes a walled mound supporting a raised platform (called pr<193>s<193>da) ç
for spectators.
The word is sometimes used to denote the fourth court of a big house ç
or temple generally divided into five courts or areas.
@NT = Prak<193>·<193>nanda Yati
Prak<193>·<193>nanda Yati, a disciple of J<210><193>n<193>nanda Yati, ç
is one of the well-known writers of Advaita Ved<193>nta in the post-<185>a<209>kara ç
(<MS>A.<|>D.<D> 788-820) period. He might have lived during the last ç
part of the 15th and the first part of the 16th centuries. His most ç
famous work is the Ved<193>ntasiddh<193>nta-mukt<193>val<200>.
He is the primary propounder of thetwo doctrines `d<216><218><219>is<216><218><219>iv<193>da' ç
and the `ekaj<200>vav<193>da'.
See <MS>ADVAITA VED°NTA DAR<185>ANA.
@SPACE = 
@NT = Prak<193>·<193>tman
@N1 = (<MS>A.<|>D.<D> 1200)
@SPACE = 
Also known as Prak<193>·<193>nubhava, a disciple of Anany<193>nubhava, ç
Prak<193>·<193>tman has made his name immortal by writing a voluminous ç
commentary called Pa<210>ca-p<193>dik<193>-vivara<207>a on the Pa<210>cap<193>dik<193> ç
of Padmap<193>da, a direct disciple of <185>a<209>kara (<MS>A.<|>D.<D> ç
788-820). The work deals with only the first four s<220>tras of the ç
Brahmas<220>tras, <185>a<209>kara's bh<193>·ya on it and Padmap<193>da's ç
gloss on <185>a<209>kara's bh<193><218>ya.
This famous work has given rise to a new school of Advaita, known ç
as the `Vivara<207>aprasth<193>na'.
See also <MS>ADVAITA VED°NTA DAR<185>ANA.<D>
@SPACE = 
@NT = Pr<193>k<216>t
@N1 = (`unrefined')
@SPACE = 
Sanskrit (or Sa<221>sk<216>ta) and Pr<193>k<216>t (or Pr<193>k<216>ta) ç
are two important languages of ancient India.
`Pr<193>k<216>ta' as against `sa<221>sk<216>ta' means, `the unrefined, ç
the original or the basic'. Taken in this sense, it is the crude form ç
of Sanskrit, the crudeness being brought about by corruption in usage ç
by the common masses.
If Sanskrit was the language of the classes, Pr<193>k<216>t was the ç
language of the masses.
Considered as a vernacular dialect, Pr<193>k<216>t could have existed ç
in many forms. The names of these were: Apabhra<221>·a, Mah<193>r<193><218><219>r<200>, ç
M<193>gadh<200>, Pai·<193>c<200> and <185>aurasen<200>.
The Jain scriptures like the °c<193>r<193><209>ga and the S<220>trak<216>t<193><209>ga ç
as also the edicts of A·oka (272-232 <MS>B.<|>C.<D>) and Kh<193>ravela ç
(200 <MS>B.<|>C.<D>) are in Pr<193>k<216>t.
There are a large number of works including grammars and dictionaries ç
in this language. The subjects covered are poetics, astrology and ç
medical sciences, apart from religion.
@SPACE = 
@NT = prak<216>ti
@N1-1 = (`the natural or original principle,'<R>ç
`that which produces effects')
@SPACE = 
This is one of the most widely used words in Sanskrit literature as ç
also in the Hindu scriptures.
In the most basic sense, it means nature or a natural quality.
In Vedic sacrifices, it means a model y<193>ga†like the Dar·a or the ç
P<220>r<207>am<193>sa† others based on it being called `vik<216>tis'.
In grammar it represents the basic form of a word.
In the S<193><209>khya Dar·ana, it represents pradh<193>na, the basic ç
material cause of the universe, comprising the three gu<207>as†sattva, ç
rajas and tamas. This concept has generally been accepted by almost ç
all the schools of Ved<193>nta.
In Advaita Ved<193>nta it stands for m<193>y<193> at the cosmic level ç
and avidy<193> (ignorance) at the individual level.
In Vi·i<218><219><193>dvaita Ved<193>nta it is called `acit'  (the  unconscious  principle)  and ç
accepted as a permanent reality, but under the control of ®·vara or ç
God.
The Dvaita Ved<193>nta considers it as having two aspects: the citprak<216>ti ç
(conscious entity same as Lak<218>m<200>, the divine consort of Vi<218><207>u) ç
and the acitprak<216>ti or the unconscious basic material cause of ç
the world.
In the <185><193>ktatantras prak<216>ti is the Divine Mother who appears ç
in five forms.They are: Durg<193>, R<193>dh<193>, Lak<218>m<200>, ç
Sarasvat<200> and S<193>vitr<200>. These five goddesses are responsible ç
for creation.
In the °yurveda (health sciences) it stands for the general condition ç
of the body.
The Bhagavadg<200>t<193> (7.4, 5) describes prak<216>ti as representing ç
two aspects of the Lord's power, the apar<193> (lower) and the par<193> ç
(the higher). The former comprises eight unconscious material objects ç
and thelatter, the conscious j<200>va (individual soul).
@SPACE1 = 
In political science (vide Y<193>j<210>avalkya Sm<216>ti 1.353; ç
Kau<219>ilya's Artha·<193>stra 6.1) the word stands for the seven ç
r<193>jy<193><209>gas or constituents of the state.
In Sanskrit poetry, it is the name of a particular metre with 21 letters ç
or syllables per line.
@SPACE = 
@NT = pr<193>k<216>tika-pralaya
See <MS>PRALAYA.
@SPACE = 
@NT = prak<216>tilaya
@N1-1 = (`dissolution into the prak<216>ti')
In the S<193><209>khya and the yoga systems, out of the several attainments ç
predicated for the s<193>dhakas (or aspirants of yoga), the state ç
of prak<216>tilaya is also one.
Some practitioners of yoga, who have developed intense vair<193>gya ç
or detachment towards the world and its pleasures, but who have not ç
acquired the right type of viveka or discriminatory knowledge, meditate ç
on the prak<216>ti (or pradh<193>na), the fundamental matrix of the ç
material universe. By sam<193>dhi on it, they are able to merge themselves ç
in it after death. This state called `prak<216>tilaya,' though free ç
from sorrow, is devoid of any consciousness or bliss. After being ç
in this condition for a very long time, they return to sa<221>s<193>ra ç
or transmigratory existence, the cycle of births and deaths. 
The S<193><209>khyas<220>tras (45) of ®·vara-k<216><218><207>a (4th ç
cent. <MS>A.<|>D.<D>) and the Yogas<220>tras (1.19) of Pata<210>jali ç
(200 <MS>B.<|>C.<D>) refer to this state.
@SPACE = 
@NT = pralaya
@N1 = (`dissolution [of the world]')
The Hindu scriptures propound the cyclic theory of creation. The cycle ç
of s<216><218><219>i (creation), sthiti (preservation) and laya (dissolution) ç
goes on endlessly.
The dissolution, called laya or pralaya, is of four types: nitya; ç
naimittika; pr<193>k<216>tika and <193>tyantika.
Nityapralaya refers to the daily deaths of beings that are born. Naimittika ç
pralaya is the dissolution that takes place at the end of a day of ç
Brahm<193>, called `kalpa' which is equivalent to 4.32 billion human ç
years. The pr<193>k<216>tika pralaya is the dissolution of everything ç
into prak<216>ti (the basic matrix of the universe, often identified ç
with the m<193>y<193>-power of God) at the end of Brahm<193>'s life ç
of (his) hundred years equivalent to 1036 human years. °tyantikapralaya ç
actually refers to mok<218>a or liberation wherein a j<200>va is liberated ç
from transmigratory existence.
@NT = pram<193>
@N1 = (`the knowledge')
Hindu philosophical treatises often use four technical terms: pram<193>, ç
pram<193><207>a, prameya and pram<193>t<216>.
An object that has to be known is `prameya'. The means of knowledge ç
that gives us its correct understanding is `pram<193><207>a'. The ç
correct knowledge that is got through the pram<193><207>as is `pram<193>'.
For instance, a pot is `prameya'. The eye that sees it and the process ç
of seeing is `pram<193><207>a'. The knowledge got that it is a mud ç
pot of small size, black in colour, containing water, is `pram<193>'.
The person who knows it thus is the pram<193>t<216> (knower).
Pram<193> is true knowledge which isnot negated by later perceptions. ç
If negated† like seeing a snake in a rope in insufficient light and ç
then discovering it in bright light that it is a rope†it is only a ç
bhrama (illusion or false perception).
Sometimes, false knowledge is called apram<193> and three more varieties ç
of it are predicated: sm<216>ti (insufficient memory), sa<221>·aya ç
(doubt) and tarka (false logic).
See also <MS>PRAM°ØAS.
@SPACE = 
@NT = pram<193>da
@N1 = (`heedlessness')
@SPACE1 = 
In general, the word means heedlessness or carelessness and a blunder ç
that arises out of it.
However, in the Yogas<220>tras (1.30) of Pata<210>jali (200 <MS>B.<|>C.<D>) ç
it is used as a technical term and listed as an obstacle to yoga or ç
sam<193>dhi. It is defined as neither remembering nor practising the ç
basic virtues like ahi<221>s<193> (non-injury) and satya (truth), ç
which are essential for attaining sam<193>dhi.
Once the mind is allowed to slip from the path of yoga due to pram<193>da, ç
it can result in a total fall (vide Vivekac<220><195><193>ma<207>i, ç
324). The famous sage Sanatsuj<193>ta compares pram<193>da to m<216>tyu ç
or death since it ultimately leads to sa<221>s<193>ra or transmigratory ç
existence (vide Sanatsuj<193>t<200>ya 1.4).
@SPACE = 
@NT = pram<193><207>as
@N1 = (`those which measure,' `valid means of knowledge')
@SPACE1 = 
All the six dar·anas (Hindu systems of philosophy) accept certain ç
basic sources or means of knowledge, known as `pram<193><207>as',  upon  which  they  further ç
develop their theories.
These pram<193><207>as vary from a minimum of three to a maximum of ç
six. They are as follows.
<MS>PRATYAK<186>A<D>  (direct  or  immediate perception) has two stages ç
of development. As soon as the sense-organ comes into contact with ç
the sense-object, there is a general awareness of it, as something ç
existing. This is called nirvikalpaka-pratyak<218>a. In the next stage, ç
all the detailswill be noted in the light of past experience. This ç
is savikalpa-pratyak<218>a.
<MS>ANUM°NA<D> (inference) gives us the knowledge of a thing indirectly, ç
when we see some li<209>ga or sign invariably connected with the original. ç
For instance, by seeing smoke on a yonder hill, we can infer that ç
there is fire there (even though we do not see it directly) since ç
it is known from previous observations and experience that smoke is ç
invariably associated with fire.
<MS>UPAM°NA<D> (comparison) is another source of knowledge. On seeing ç
a rat, one recollects that it is like the mouse he had seen earlier. ç
He then comes to know that the remembered mouse is like the perceived ç
rat. This type of knowledge comes through upam<193>na.
@SPACE1 = 
<MS><185>ABDA<D> (verbal testimony) is the next source of knowledge. ç
The M<200>m<193><221>s<193> Dar·ana pays the greatest attention to ç
this since it has to justify the undisputed authority of the Vedas.
The words of a reliable person are believed to be true. This is called ç
<193>ptav<193>kya.
Verbal testimony, however, is of two types: pauru<218>eya (personal, ç
same as <193>ptav<193>kya) and apauru<218>eya (impersonal). The second ç
denotes the Vedas since they were not created by any human agency. ç
The Vedas are supremely authoritative since they are the `Book of ç
Commandments' and also give us authentic know-ledge of the unseen ç
and the unknown truths. Again, their main purport and purpose lies ç
in propagating sacrificial rites.
The Vedas are eternal, not as the printed Book nor as the orally transmitted ç
mantras but as the eternal teachings contained in them. These teachings ç
are conveyed through the <216><218>is or sages in every age.
Since the Vedas are mainly concerned with giving commands (= vidhi) ç
about the y<193>gas or sacrificial rites and other associ-ated rituals, ç
only those sentences containing such commands as expressed through ç
the verbs couched in `vidhili<209>' (imperative mood as in `svargak<193>mo ç
yajeta,' `One desirous  of  attaining  heaven  should sacrifice!') ç
and other forms should be taken as authoritative and the rest as aids ç
to it. Such verbs have an innate power of urging the hearer to do ç
the sacrifice. This is called `bh<193>van<193>'. The urge contained ç
in the Vedic words is known as `·<193>bd<200>-bh<193>van<193>' (·abda ç
= word). On hearing it, the person who hears it, gets the urge to ç
perform it. This secondary urge is named `<193>rth<200>bh<193>van<193>' ç
(artha = utility, useful activity).
All this depends upon the correct understanding and interpretation ç
of the Vedic sentences. For this, the M<200>m<193><221>s<193> gives ç
six steps: upakrama (beginning); upasa<221>h<193>ra (concluding); ç
abhy<193>sa (repetition for the sake of emphasis); ap<220>rvat<193> ç
(not being known earlier by any other means); phala (utility); arthav<193>da ç
(mere eulogy) and upapatti (logic and reasoning).
Once the correct meaning is thus ascertained, the command may be implemented.
@SPACE1 = 
<MS>ARTH°PATTI<D> (postulation or presumption) is the necessary supposition ç
of an unperceived factwhich alone can explain an anomaly satisfactorily. ç
For instance, if a person is noticed to be getting fat eventhough ç
he does not eat during the day, it can safely be presumed that he ç
issecretly eating at night! Knowledge obtained by arth<193>patti ç
is distinctive since it cannot be got by any other means.
<MS>ANUPALABDHI<D> (non-perception) has also been accepted as a source ç
of know-ledge since it gives the immediate cognition of the non-existence ç
of an object. If it is found that a jar which had been kept on a table ç
earlier, is not perceived now, its non-existence is cognized.
@SPACE = 
@NT = pramathaga<207>a
@N1 = (`the group of beings who punish [the evil ones]')
@SPACE = 
Lord <185>iva is said to be surrounded by a very large retinue of ç
godlings or semi-divine beings whose number is said to be 360 millions. ç
They are capable of taking any form. Generally they appear like ascetics ç
with ja<219><193> (long matted hair) and ardha-candra (crescent moon) ç
on the hair. They are deeply devoted to <185>iva and spend their time ç
in his service. They also fight on his behalf when necessary as on ç
the occasion of destruction of Dak<218>a's sacrifice.
Sometimes they are pictured more like horrible goblins.
They attack sinners and transgressors of dharma, generally in the ç
night.
However, good people who follow the dictates of dharma, cannot come ç
under their influence (vide Mah<193>bh<193>rata, Anu·<193>sanaparva ç
131).
@SPACE = 
@NT = pr<193><207>a
@N1 = (`that by which one lives')
@SPACE = 
One of the most widely used words, `pr<193><207>a' has several senses. ç
Some of the Upani<218>ads like the Kau<218><200>taki use the word ç
for Brahman (2.1). Ved<193>ntic works use the word to denote Hira<207>yagarbha, ç
an aspect of Brahman, involved in the process of creation through ç
his icch<193>·akti or cosmic will-power.
Coming to an individual living being, pr<193><207>a is the life-force ç
or vital air, because of which only the being lives. In its primary ç
sense, it is sometimes called mukhyapr<193><207>a also.
Pr<193><207>a functions inside the body in five different forms. Hence ç
it is also called `pa<210>capr<193><207>as'.
The five pr<193><207>as are: pr<193><207>a, ap<193>na, vy<193>na, ç
ud<193>na and sam<193>na.
Pr<193><207>a is centred in the nose and is responsible for respiration.
Ap<193>na works downwards and is res-ponsible for the working of the ç
excretory organs and the organs of generation.
Vy<193>na pervades the whole body and supplies the energy necessary ç
for hard work like running or lifting a weight.
Ud<193>na is situated in the throat with its movement poised upwards. ç
It helps the j<200>va (the individual soul) to leave the body at the ç
time of death.
Sam<193>na, the last of the pa<210>capr<193><207>as, is situated in ç
the central region of the body and is responsible for digestion or ç
assimilation of food.
Each of these five pr<193><207>as has a subsidiary called upapr<193><207>a. ç
The five upapr<193><207>as are: n<193>ga (of ud<193>na), k<220>rma ç
(of vy<193>na), k<216>kala (of sam<193>na) devadatta (of ap<193>na) ç
and dhana<210>jaya (of sam<193>na). They are responsible for eructation, ç
winking, sneezing, yawning and sustaining the body respectively.
@SPACE1 = 
In the Upani<218>ads, the word is also used to indicate the indriyas ç
or sense-<~>organs.
@NT = pr<193><207><193>gnihotra
@N1 = (`[act of eating] compared to Agnihotra to satisfy the pr<193><207>as')
The Karmak<193><207><195>a of the Vedas is full of not only the instructions ç
about sacrifices but also contains their eulogy.
In the <193>ra<207>yakas and the Upani<218>ads, however, there is ç
a tendency to minimise their ritualistic aspects and substitute them ç
with subtle mental ideas, sometimes associated with ordinary acts ç
of day-to-day life also. The pr<193><207><193>gnihotra of the Ch<193>ndogya ç
Upani<218>ad (5.19-24) is one such instance. Here the act of eating ç
has been elevated to the level of the Agnihotra, a daily sacrifice.
According to the instructions given in the Upani<218>ad, the first ç
five morsels of food are to be preceded by the following mantras: ç
pr<193><207><193>ya sv<193>h<193>; vy<193>n<193>ya sv<193>h<193>; ç
ap<193>n<193>ya sv<193>h<193>; sam<193>n<193>ya sv<193>h<193>; ud<193>n<193>ya ç
sv<193>h<193>.
When these five pr<193><207>as are satisfied by these ritual offerings, ç
they produce certain special results like progeny, possession of cows ç
and excellent physical characteristics, including smooth functioning ç
of the senses.
@NT = pr<193><207>ali<209>ga
See under <MS>V®RA<185>AIVISM<D> included in <MS><185>AIVISM.<D>
@NT = pr<193><207>amayako·a
@N1 = (`the sheath of pr<193><207>a or life')
It is the pa<210>capr<193><207>as or the five vital airs, along with ç
the karmendriyas or organs of action, that constitute the pr<193><207>amayako·a. ç
They cover the soul like a sheath, hiding its real nature, which is ç
caitanya or consciousness.
@NT = pr<193><207>aprati<218><219>h<193>
@N1 = (`infusing life [into an image]')
Worship of God through an image is a common aspect of practical Hinduism.
The image, however, whether established in a temple or in one's house, ç
has first to be infused with life, which process is called `pr<193><207>aprati<218><219>h<193>'.
The basic idea is that God who is in one's own heart, has to be ceremonially ç
transferred to the image and then worshipped.
In the consecration of temples, after several rituals†both major and ç
minor† pr<193><207>aprati<218><219>h<193> is done by uttering the ç
mantra <193><221> hr<200><221> devasya v<193><209>mana-·cak<218>us...... ç
(and so on) and then placing one's thumb on the heart of the image. ç
This is to be followed by the recitation of another mantra o<221> ç
asyai pr<193><207><193><199> prati-<218><219>hantu..... (and so on) ç
which completes the process.
In p<220>j<193> or worship also, a similar procedure is followed, ç
at the time of every worship.
@NT = Pra<207>ava
@N1 = (`that by which [God] is effectively praised,' `that which is ç
ever new')
Pra<207>ava or Om is the universally accepted symbol of Hinduism. ç
All sections, cults and groups honour this and use this. Even Jainism, ç
Buddhism and Sikhism have adopted this. It is both an auricular and ç
a visual symbol for Brahman, the Absolute of Hindu philosophy, and ç
God of Hindu religion.
Literally the word `Pra<207>ava' means `that by which God is effectively ç
praised'. It also means `that which is ever new'. The word `Om' is ç
derived from the Sanskrit root `ava' which has nineteen different ç
senses. From these it is possible to construe that Om represents that ç
Power which (1) is omniscient; (2) rules over the entire universe; ç
(3) protects one from the evils of life; (4) fulfills the cherished ç
desires of its devotees; and, (5) destroys ignorance and gives enlightenment.
Pra<207>ava has been extolled highly in the Vedas, the Upani<218>ads ç
and the G<200>t<193> as also in other scriptures. The Gopatha-br<193>hma<207>a ç
of the Atharvaveda relates astory according to which god Indra ç
successfully overcame the demons with the help of Om. The story can ç
be interpreted to mean that man can conquer his beastly nature by ç
having recourse to the repetition of Om. The Yajurveda exhorts us ç
to try to realise Brahman through repeating andremembering Om. The ç
Ka<219>hopani<218>ad declares that Om is Parabrahman itself. The ç
Mu<207><195>akopani<218>ad advises the spiritual aspirant to meditate ç
on the unity of the <193>tman (the Self) with Brahman (God) using ç
Om for japa. <185>r<200> K<216><218><207>a avers in the G<200>t<193> ç
that he is Om among words and that all religious rites are started ç
with the repetition of Om. Not only that, if anyone succeeds in reciting ç
the word Om at the time of his death, simultaneously thinking of God, ç
he will attain the highest Truth. The Yogas<220>tras of Pata<210>jali ç
declares that Pra<207>ava is the symbol of God and that one can get ç
sam<193>dhi on him by its repetition, and meditation of him.
@SPACE1 = 
Actually Om comprises three independent letters a, u and m, each of ç
which has its ownmeaning and significance. The letter `a' represents ç
`beginning' (<193>dimatva); `u' represents `progress' (utkar<218>a); ç
`m' represents `limit or dissolution' (miti). Hence the word Om represents ç
that power responsible for creation, development and dissolution of ç
this universe, i.e., God Himself.
Sv<193>mi Vivek<193>nanda has given a very simple but interesting ç
and instructive explanation of the three letters comprising Om thereby ç
bringing out the uniqueness of this great symbol: `The first letter ç
A is the root-sound, the key, pronounced without touching any part ç
of the tongue or the palate; M represents the last sound in the series, ç
being produced by closed lips; and the U rolls from the very root ç
to the end of the sounding-board of the mouth. Thus Om represents ç
the whole phenomenon of sound-producing. As such it must be the natural ç
symbol, the matrix of all the various sounds. It denotes the whole ç
range, and possibility of all the words that can be made.'
The full significance of this statement becomes unfolded only when ç
we understand the Hindu theory of creation as mentioned in the Vedas ç
and other scriptures. This theory can be summed up as follows: 1) ç
Creation is not a linear process, beginning and ending at particular ç
points of time, but it is a cyclic process going on eternally; 2) ç
God creates this universe out of Himself by Himself. To put it in ç
a technical language, He is both the material cause and theefficient ç
cause; 3) Before beginning any particular cycle of creation, He utters ç
the Vedic words denoting the various classes of beings and objects, ç
conceives  of  the  corresponding  forms (remembering them from the ç
previous cycles of creation) and creates them.
@SPACE1 = 
Contrary to the general understanding, this means that forms (r<220>pa) ç
are preceded by names (n<193>ma). Names are composed of letters which ç
are sounds. All sounds are included in Om. Hence, the entire creation ç
which proceeds from Vedic words or sounds, proceeds from the basic ç
matrix of all sounds, viz., Om. Since God is the origin of this universe ç
Om and God are identical. Or, at least, Om is the best symbol of God.
God is one. Sages call Him by various names. Though these various ç
names differ from one another, all of them have sprung from the same ç
basic source of all sounds, viz., Om. Hence Om represents all names ç
of God; or, it is the best name of God.
@NT = pra<207>avatanu
@N1-1 = (`body [made up of] Pra<207>ava or O<209>k<193>ra')
See <MS>BAINDAVA<185>AR®RA.<D>
@NT = Pr<193><207>avidy<193>
See <MS>VIDY°S.<D>
@NT = pr<193><207><193>y<193>ma
@N1 = (`controlling of pr<193><207>a')
Pr<193><207>a is the cosmic energy or life-force which is permeating ç
not only the inanimate universe but also all the living beings.
The Hindu sages had discovered even from the most ancient times, the ç
techniques of controlling and channelising this life-force and put ç
it to various uses.
This science of controlling pr<193><207>a is known as pr<193><207><193>y<193>ma.
The  word  `pr<193><207><193>y<193>ma'  has  been defined as lengthening ç
or dispersing the pr<193><207>ic energy so as to pervade the whole ç
body in a uniform manner.
The subject of pr<193><207><193>y<193>ma has been dealt with not only ç
in R<193>jayoga (vide Pata<210>jali's Yogas<220>tras 2.49-53) ç
but also in Ha<219>hayoga (vide Ghera<207><195>a Sa<221>hit<193> ç
5; Ha<219>hayogaprad<200>pik<193> 2.71-77).
In R<193>jayoga, it is listed as the fourth of the eight steps of ç
yoga leading to sam<193>dhi (the last step).
Since there is an intimate connection between the mind and the pr<193><207>a, ç
which again, can be regulated through the regulation of the breathing ç
process, the mind can be brought under control by controlling breath. ç
This is the philosophy behind pr<193><207><193>y<193>ma as given in ç
the Yoga-s<220>tras.
In this work, pr<193><207><193>y<193>ma is described as having three ç
steps: p<220>raka (inhalation), kumbhaka (retention of breath) and ç
recaka (exhalation).
Air has to be inhaled through the left nostril, should be retained ç
in the lungs for some time and then exhaled through the right nostril. ç
The same process should then be repeated in the reverse order. This ç
forms one round of pr<193><207><193>y<193>ma proper.
The relative proportion, with regard to time, can be 1:4:2; or 1:2:2; ç
or 1:1:1. In other words, if p<220>raka or inhalation is done, say, ç
in 8 seconds, kumbhaka or retention must be for (8 x 4 =) 32 seconds ç
and recaka or exhalation, for (8x 2 =) 16 seconds.
@SPACE1 = 
This pr<193><207><193>y<193>ma is regulated by three factors: de·a ç
(distance of air measured during exhalation), k<193>la (time taken ç
for each of the three processes like 4 seconds: 16 seconds: 8 seconds) ç
and sa<209>khy<193> (the number of pr<193><207><193>y<193>mas per ç
sitting). These should be gradually increased until the following ç
limits are reached, if possible: 24 to 36 inches; 16:64:8; 80 per ç
sitting and 320 per day.
