However, these limits are for extra-ordinary and highly qualified ç
s<193>dhakas who practise it under the direct guidance of an expert ç
guru. Hence it should never be attempted by others.
This threefold pr<193><207><193>y<193>ma must be preceded by what ç
is called n<193><195><200>·uddhi. In this exercise, only the p<220>raka ç
and recaka are practised without kumbhaka.
The works on Ha<219>hayoga describe not only various kinds of pr<193><207><193>y<193>mas ç
but also various avasth<193>s or stages involved. They also predicate ç
various kinds of phalas orfruits resulting from their practice like ç
getting rid of sins and curing of ailments.
Pr<193><207><193>y<193>ma being a highly complicated process fraught ç
with serious consequences if wrongly done, should be practised only ç
under the direct guidance of adepts in the field. Several preconditions ç
like purity of physical and ethical life, should also be strictly ç
adhered to.
@NT = pra<207><200>t<193>
@N1 = (`fetched [water]')
@EMERGEN1 = In the Dar·ap<220>r<207>am<193>sa sacrifice, puro<195><193>·a ç
cakes (of rice or barley grains) are offered. The water that is used ç
for preparing the dough has to be brought in a camasa (wooden cup ç
with a handle) purified with pavitras (or darbha grass), from the ç
north of the G<193>rhapatya fire to the north of the °havan<200>ya ç
fire, to the accompaniment of certain mantras (vide Taittir<200>ya ç
Sa<221>hit<193> 1.1.5.1). This process is called pra<207><200>t<193>pra<207>ayana ç
and the waters as pra<207><200>t<193>.
@NT = Prapa<210>cas<193>ra
@S10N = INTRODUCTION
The tantras are a special class of literature dealing mainly with ç
the up<193>san<193>aspect†meditation and rituals† of Hinduism. (See ç
<MS>TANTRAS<D> for details.)
One of the earliest and pre-eminent of these tantras is the Prapa<210>cas<193>ra ç
or Prapa<210>cas<193>ratantra, attributed to °di <185>a<209>kara ç
(<MS>A.<|>D.<D> 788-820). On this work thereis a well-known commentary ç
called Vivara<207>a by Padmap<193>da, one of the four chief disciples ç
of <185>a<209>kara and the first pontiff of the K<193>lik<193>ma<219>ha ç
at Dv<193>rak<193> (in Gujarat).
Whether this work dealing with mantras, yantras and up<193>san<193> ç
of the various deities of the Hindu pantheon is a genuine composition ç
of the famous <185>a<209>kara, or someone else's passed on as his, ç
there is no doubt that it is the handiwork of a great genius.
The work has 2470 verses distributed among 36 pa<219>alas or chapters ç
dealing with various topics such as creation and dissolution, development ç
of the human embryo and birth, letters of the alphabet, b<200>j<193>k<218>aras ç
or seed-letters, d<200>k<218><193> or initiation as also the mantras ç
and rituals connected with the various deities.
A brief summary of this treatise may now be attempted here:
@S10N = Chapter 1 (104 verses)
It starts with the questions of Brahm<193>, Vi<218><207>u and Rudra ç
put to Lord N<193>r<193>ya<207>a.
N<193>r<193>ya<207>a replies that they were brought forth by Ak<218>ara ç
(the Eternal- Imperishable or Brahman). He then proceeds to describe ç
the process of creation beginning with puru<218>a (soul) and prak<216>ti ç
(matter).
A detailed description of the concept of time starting with lava (a ç
split-second) right up to the life of the four-faced Brahm<193> (which ç
is equal to 17,280 million human years) has also been given here.
@S10N = Chapter 2 (67 verses)
Development of the embryo within the mother's womb and certain other ç
topics of °yurveda are dealt with in this chapter.
Another subject discussed here is that of bh<193>vas or sounds and ç
several aspects of ku<207><195>alin<200>.
@S10N = Chapter 3 (75 verses)
The main theme of this chapter is the letters of the alphabet classified ç
as saumya (lunar), saura (solar) and <193>gneya (fiery).
How these letters are uttered by the working of the air, first through ç
the su<218>umn<193> canal and then through the vocal organ is also ç
described.
Incidentally, the names of 50 o<218>adhis (herbs) like candana (sandal), ç
aguru (fragrant aloe) and karp<220>ra (camphor) have also been mentioned ç
here.
@S10N = Chapter 4 (76 verses)
This chapter deals mainly with the b<200>j<193>k<218>ara (seed-letter) ç
hr<200>m, variously called `n<193>da,' `pr<193><207>a', `j<200>va,' ç
`gho<218>a' and so on.
It is identified with the devat<193> (goddess) Bhuvane·var<200>, also ç
known as Ku<207><195>al<200>.
The Ha<221>samantra (so'ha<221> ha<221> sa<199>) too, also called ç
`Mah<193>v<193>kya', finds a mention here.
@S10N = Chapter 5 (70 verses)
Henceforward, this work deals mostly with rituals, normal to such ç
t<193>ntrik works.
The topics dealt with here, are: d<200>k<218><193> (initiation), mantra ç
(sacred formula), v<193>stuma<207><195>ala and v<193>studevat<193> ç
as also v<193>stubali (rites connected with the V<193>stupuru<218>a, ç
a cosmic deity), and erection of a ma<207><195>apa (a small structure, ç
a shed) for purposes of d<200>k<218><193>.
@S10N = Chapter 6 (125 verses)
The topics included in this chapter are: the <216><218>i (sage), chandas ç
(metre) and devat<193> (deity) of a mantra; ny<193>sas (six or five); ç
worship of the deity; establishing of the kumbha (pot); pr<193><207>aprati<218><219>h<193> ç
(infusing life into the image or symbol); the upac<193>ras (special ç
modes of offering); homa (fire- sacrifice); offering unto Brahman; ç
pra<207><193>ma (obeisance).
@S10N = Chapter 7 (70 verses)
This chapter deals with the rules of s<193>dhana concerning Sarasvat<200>, ç
the goddess of speech.
For her mantra, Brahm<193> is the <216><218>i, G<193>yatr<200> is ç
the chandas (metre) and Sarasvat<200> herself is the devat<193> (deity).
The dhy<193>na·loka describes her form for meditation as having three ç
eyes and of transparent brilliance. She is white in colour and holds ç
a rosary, a pot of nectar and a book in three hands, the fourth showing ç
the cint<193>mudr<193> (the pose of knowledge or wisdom).
Her nine attendants include the goddesses Medh<193> (understanding), ç
Prabh<193> (radiance) and Sm<216>ti (memory).
Other details concerning japa and homa are also given.
@S10N = Chapter 8 (60 verses)
The first part of this chapter deals with pr<193><207><193>gni-homa. ç
In the m<220>l<193>dh<193>racakra (where the ku<207><195>alin<200> ç
is resting) five homaku<207><195>as (pits for sacrificial fires) are ç
imagined to exist and offerings of the letters of the alphabet are ç
to be poured into them.
The second part deals with the worship of Sarasvat<200> which includes ç
the steps like ny<193>sa (ritual purification of limbs), p<220>j<193> ç
(worship) as also a beautiful hymn on her.
@S10N = Chapter 9 (44 verses)
This chapter is devoted to the worship of the goddess Tripur<193>. ç
She is called `Tripur<193>' since she is the creatrix of the trim<220>rtis†Brahm<193>, ç
Vi<218><207>u and Mahe·vara. She is also the three Vedas and existed ç
even before creation, filling all the space. Her b<200>jas (seed-letters) ç
are aim and kl<200>m.
Other items dealt with are the dhy<193>na·loka (hymn of meditation), ç
and her attendant goddesses like V<193>m<193> and a cakra (diagram). ç
The effects of worshipping her are also described.
@S10N = Chapter 10 (69 verses)
Worship of M<220>laprak<216>ti (known as Bhuvane·var<200> or Bhuvane·<200> ç
also) along with her mantra, homa, abhi<218>eka (ritual bath) and ç
japa as also other allied subjects are discussed here.
The dhy<193>na·loka describes her formwith p<193>·a (noose), a<209>ku·a ç
(goad) in two hands and exhibiting the abhaya andvarada (offering ç
protection and boon- giving) mudr<193>s in the other two hands.
@S10N = Chapter 11 (70 verses)
The same topic is continued here withsome additional information ç
about her yantra, G<193>yatr<200>mantra and attendant goddesses. There ç
is also a long hymn addressed to her, towards the end.
@S10N = Chapter 12 (65 verses)
In this chapter, a detailed exposition of the worship of <185>r<200> ç
or Lak<218>m<200> is given. For her mantra, Bh<216>gu is the <216><218>i ç
(sage), niv<216>t is the chandas (metre) and <185>r<200> or Lak<218>m<200> ç
is the devat<193> or deity.
The dhy<193>na·loka describes her as holding two lotuses in her two ç
upper hands whereas the two lower hands exhibit the abhaya and the ç
varada mudr<193>s. Two elephants are also pouring gh<216>ta (ghee ç
or clarified butter) from two pots.
After describing japa (repetition of her divine name) and homa (fire-worship), ç
the text gives how her nine <185>aktis are to be invoked round her ç
p<200><219>ha (seat).
She is also described as Ram<193>, and 32 <185>aktis (or aspects) ç
like Bh<193>rat<200>, P<193>rvat<200>, C<193>ndr<200> are enumerated.
Her worship leads to the attainment of purity, bodily perfection, ç
beauty and intelligence.
@S10N = Chapter 13 (90 verses)
Dealing with the goddess Tripu<219><193>, this section gives the <216><218>i, ç
chandas and devat<193> as Var<193>ha, niv<216>t and Dhara<207><200>.
The japa of her mantra has to be done twelve lakh times.
The other topics discussed are the mantra of the goddess Tvarit<193>, ç
yantras with ten and twelve lines, mantra of the deity Nity<193> and ç
associated rites.
@S10N = Chapter 14 (88 verses)
This chapter deals exclusively with the goddess Durg<193> including ç
her several aspects and <185>aktis (attendant deities).
Aspects of Durg<193> are Vanadurg<193> and <185><220>lin<200>durg<193>.
Mantras of all these aspects and their methods of pura·cara<207>a ç
(ceremonial repetition) are also given.
It is specially mentioned here that supplication to Durg<193> as Vindhyav<193>sin<200> ç
can eradicate the effects of all kinds of poisons like those of snakes, ç
scorpions, rats and dogs.
@S10N = Chapter 15 (65 verses)
This chapter concerns S<220>rya or the Sun-god and his four-lettered ç
mantra.
Aja (Brahm<193>) is the <216><218>i for this mantra whereas g<193>yatr<200> ç
is the chandas. Bhuvane·<200>†an aspect of the Divine Mother†is the ç
devat<193>.
As in other cases, here also the dhy<193>na·loka (for meditation), ç
ny<193>sas, homa  and  other  rituals  have  been described.
@S10N = Chapter 16 (65 verses)
This chapter deals with the mantra of Candra or Soma (the Moon), his ç
worship and his nine <185>aktis like Rohi<207><200>, K<216>ttik<193>, ç
Revat<200> and Bhara<207><200>.
It also gives the mantra of Agni and his nine <185>aktis such as P<200>t<193>, ç
<185>vet<193>, Dh<220>mr<193>, Rucir<193> and Jv<193>lin<200>.
@S10N = Chapter 17 (78 verses)
This  section  deals  with  Mah<193>- ga<207>apati.
The mantra is a long one with 28 letters. Its <216><218>i is Ga<207>aka, ç
the chandas is niv<216>t and the deity is Mah<193>ga<207>apati.
The dhy<193>na·loka describes him along with his ·akti (who is wearing ç
shining ornaments and holding a lotus in her hand). He has ten arms ç
holding pomegranate fruit, mace, discus, noose, his own tusk and so ç
on.
He has nine <185>aktis like T<200>vr<193>, Jv<193>lin<200>, Ugr<193>, ç
K<193>mar<220>pi<207><200> and others.
Other mantras including a Ga<207>e·a-g<193>yatr<200> are also given.
@S10N = Chapter 18 (54 verses)
@EMERGENCY = This is devoted to Manmatha (Cupid), the god of love. ç
For his mantra, Sammohana is the <216><218>i, g<193>yatr<200> is the ç
chandas and Manobh<193>va is the deity. He has eight <185>aktis to ç
assist him, like Mohan<200>, Tr<193>s<200>, °kar<218>i<207><200> and ç
so on.
@EMERGENCY = Two mantras are given. The first is of a single letter. ç
The second, called m<193>l<193>mantra, has fifty letters.
@EMERGENCY = A  mantra  of  Ratividy<193>  (K<193>ma's consort) consisting ç
of 32 letters is also indicated.
@EMERGENCY = This section gives a long mantra of <185>r<200>k<216><218><207>a ç
(of 18 letters) and the ways of using it.
@S10N = Chapter 19 (64 verses)
The subjects dealt with in this chapter are: Pra<207>ava (O<209>k<193>ra), ç
meditation on Vi<218><207>u, the four Vy<220>has of Vi<218><207>u, ç
details concerning yoga like yama and niyama, five states of consciousness, ç
different states of yoga and the yogasiddhis like a<207>im<193> (capacity ç
to become small like an atom) and so on.
Methods of utkr<193>nti (leaving the body through its various parts), ç
entering into others' bodies and returning are also described towards ç
the end.
@S10N = Chapter 20 (61 verses)
The a<218><219><193>k<218>ar<200>mantra†the famous eight-lettered ç
mantra of N<193>r<193>ya<207>a†is the main subject here. Of this mantra, ç
S<193>dhyan<193>r<193>ya<207>a is the <216><218>i, g<193>yatr<200> ç
is the chandas and Param<193>tman is the devat<193>.
Apart from giving the names of the ten avat<193>ras†which list omits ç
Buddha but includes Balar<193>ma†some aspects of rituals like arcana ç
(worship) and japa (repetition of the divine mantra) are also dealt ç
with at the end.
@S10N = Chapter 21 (60 verses)
This chapter deals with the twelve yantras or diagrams of the twelve ç
r<193>·is or signs of the zodiac. Bh<193>nu (or the Sun) when associated ç
with these twelve r<193>·is has twelve different names such as Dh<193>t<193>, ç
Aryam<193>, Mitra, Vivasv<193>n, P<220><218><193> and so on.
Towards the end, a beautiful hymn addressed to Vi<218><207>u is also ç
given.
@S10N = Chapter 22 (58 verses)
The dv<193>da·<193>k<218>ar<200> (twelve-lettered) mantra of Lord ç
V<193>sudeva is the subject of this section. Praj<193>pati is the ç
<216><218>i whereas g<193>yatr<200> is the chandas. Vi<218><207>u ç
is the devat<193>.
It is to be repeated twelve lakh timesand is capable of giving mok<218>a ç
or liberation.
Three kinds of ny<193>sas†sa<221>h<193>ra-ny<193>sa, s<216><218><219>iny<193>sa ç
and sthitiny<193>sa†leading to the destruction of do<218>as (faults), ç
and the creation of good, as also gaining peace are also given.
Incidentally, the mantra of Sudar·ana (Lord Vi<218><207>u's discus) ç
and some associated rituals are also given.
@S10N = Chapter 23 (72 verses)
This chapter deals with the Puru<218>ottama aspect of Lord Vi<218><207>u. ç
The names ofhis twelve aspects†like Saty<193>tman, Acyut<193>tman ç
and Apratir<220>pa† associated with twelve parts of the body for their ç
ceremonial purification are also given.
The <216><218>i, chandas and devat<193> are respectively, Jaimini, ç
jagat<200> and Puru<218>ottama.
Other mantras mentioned are thoseof the Sudar·anacakra (discus), ç
P<193><210>cajanya-·a<209>kha (conch), Kaumodak<200>gad<193> (mace), ç
Garu<195>a (the eagle-mount) and so on.
The g<193>yatr<200>mantra of Vi<218><207>u as Trailokyamohana (one ç
who enchants all the three worlds) as also the description of his ç
extremely bewitching form are given towards the end.
@S10N = Chapter 24 (48 verses)
The mantras, meditation and worship of <185>r<200>kara (Lord Vi<218><207>u ç
who produces wealth) and Mah<193>var<193>ha (the Great-boar incarnation ç
of Vi<218><207>u) are the subject matter of this section.
@S10N = Chapter 25 (58 verses)
Meditation and worship of N<216>si<221>ha (man-lion incarnation of ç
Lord Vi<218><207>u) are the main topics here.
The mantra is in the anu<218><219>ubh metre.
N<193>rada or Praj<193>pati is said to be its <216><218>i whereas ç
anu<218><219>ubh is the chandas; and, the devat<193> is N<216>si<221>ha.
He can be worshipped in two aspects: prasanna (benign) and kr<220>ra ç
(fearsome).
Garu<195>amantra and N<216>si<221>hayantra (mystic diagram) are the ç
other topics dealt with.
@S10N = Chapter 26 (66 verses)
It deals with Vi<218><207>upa<210>jarayantra, a mystical diagram that ç
affords protection to the devotee. A mantra of sixteen letters (of ç
V<193>sudeva), other mantras related to the weapons like the Sudar·anacakra ç
(the discus) and <185><193>r<209>gadhanus (the bow) are also given.
A mantra that integrates the ·loka of the G<200>t<193> (11.36) describing ç
the lord's Vi·var<220>pa (Cosmic Form) is also given with all the ç
allied instructions.
@S10N = Chapter 27 (73 verses)
This chapter is concerned with the pr<193>s<193>da mantra, a mantra ç
of Lord <185>iva that helps the s<193>dhaka to get what he wants by ç
pleasing the Lord.
V<193>madeva is the <216><218>i of this mantra. The chandas is pa<209>kti. ç
®·a (<185>iva) is the devat<193>.
The dhy<193>na·loka describes him as pa<210>cavaktra, having five ç
faces. These five faces or aspects are: Sadyoj<193>ta, V<193>madeva, ç
Aghora, Tatpuru<218>a and ®·<193>na.
There is also an exquisite hymn on <185>iva (verses 55 to 64).
@S10N = Chapter 28 (55 verses)
Dak<218>i<207><193>m<220>rti, an important aspect of <185>iva, is ç
the subject matter of this chapter. He is described as sitting undera ç
va<219>av<216>k<218>a (banyan tree), white in complexion, with matted ç
hair ornamented by the crescent moon. He has four hands, holding the ç
para·u (battle-axe) and the m<216>ga (deer) in two hands. The third ç
is showing the j<210><193>namudr<193> (posture of giving spiritual ç
wisdom) and the last rests on his knee.
For  his  mantra†a  long  one  of eighteen letters†<185>uka is the ç
<216><218>i, anu<218><219>ubh is the chandas and Dak<218>i<207><193>m<220>rti-Rudra ç
is the devat<193>.
The rest of the chapter deals with the connected rituals.
@S10N = Chapter 29 (46 verses)
@SPACE1 = 
@SPACE1 = 
Ume·a and Ardhan<193>r<200>·vara are the two aspects of Lord <185>iva ç
dealt with here.
These descriptions are given in the respective dhy<193>na·lokas. So ç
also the rules for their japa and homa.
Ardhan<193>r<200>·vara can be propitiated for various purposes such ç
as pu<218><219>ikarma (nourishment), ·<193>ntikarma (offsetting the ç
evil effects of inauspicious planets etc.) and even <193>kar<218>a<207>a ç
(attracting others) asalso va·<200>kara<207>a (gaining control over ç
others).
The mantra of Ca<207><195>e·vara, a fierce aspect of Lord <185>iva ç
is also given, along with his g<193>yatr<200>.
@SPACE = 
@S10N = Chapter 30 (73 verses)
@SPACE1 = 
The special subject of this chapter is the famous G<193>yatr<200>mantra, ç
along with the Pra<207>ava (Om), the three vy<193>h<216>tis, the seven ç
vy<193>h<216>tis and the g<193>yatr<200>-·iras.
The three vy<193>h<216>is are: bh<220><199>, bhuva<199> and sva<199> ç
or suva<199>.
Th<%18>e<%0>seven vy<193>h<216>tis are: bh<220><199>, bhuva<199>, ç
suva<199>, maha<199>, jana<199>, tapa<199> and satyam.
The g<193>yatr<200>·iras is: om <193>po jyot<200> raso'm<216>tam bh<220>rbhuvassuvarom.
A detailed meaning and significance of all these is also described.
@SPACE = 
@S10N = Chapter 31 (103 verses)
@SPACE1 = 
This  section  gives  the  tri<218><219>ubh- mantra of the goddess ç
K<193>ty<193>yan<200> (an aspect of P<193>rvat<200> or Durg<193>). ç
Actually it comprises the first four lines of the Durg<193>- s<220>kta ç
which is a part of the Mah<193>n<193>r<193>ya<207>a Upani<218>ad ç
(2.1-7).
Mar<200>c<200>-K<193>·yapa is the <216><218>i of this mantra. Tri<218><219>ubh ç
(a Vedic metre of 11 letters in each of the four lines) is the metre ç
whereas J<193>tavedas-Agni is the devat<193>.
Apart from the dhy<193>na of the goddess K<193>ty<193>yan<200>, this ç
section also gives the names of her nine <185>aktis like Jay<193>, ç
Vijay<193>, Bhadrak<193>l<200> and Durg<193>.
As a part of the p<220>j<193> (worship) of the deity, names of some ç
more goddesses like  J<193>gat<193>,  Vedagarbh<193>,  Tapan<200>  and ç
Dahanar<220>pi<207><200>, associated with the letters of the mantra, ç
are also given.
An interesting point made out here is that the repetition of the mantra ç
(j<193>tavedase sunav<193>ma and so on) in the reverse order makes ç
it an astra or weapon capable of destroying all the defects in the ç
ritualistic process undertaken.
Divisions of the nak<218>atras into threegroups (daiva, <193>sura ç
and m<193>nu<218>a) andcertain magical rites like stambhana (arresting),   va·<200>kara<207>a   (subjugating ç
others), <193>kar<218>a<207>a (attracting someone to oneself) and ç
so on, are the other topics dealt with.
@S10N = Chapter 32 (64 verses)
This section deals with the Lava<207>a-mantra, related to the goddesses ç
R<193>tri, Durg<193> and Bhadrak<193>l<200>. A<209>g<200>r<193> is ç
the <216><218>i and the metres are anu<218><219>ubh as also tri<218><219>ubh.
The dhy<193>na·loka of the K<193>ty<193>yan<200> form of Durg<193> ç
describes her with three eyes and four arms holding cakra (discus), ç
·a<209>kha (conch), asi (sword) and ·<220>la (spear).
@SPACE1 = 
Some  magical  rites  like  m<193>ra<207>a (killing enemies) and va·<200>kara<207>a ç
(controlling a person whom we want) are also described.
@S10N = Chapter 33 (72 verses)
The anu<218><219>ubh mantra of 32 letters is dealt with here. Vasi<218><219>ha ç
is the <216><218>i, Rudra is the devat<193> and anu<218><219>ubh itself ç
is the chandas.
A detailed description of Rudra is given by the dhy<193>na·loka. His ç
32 <185>aktis such as Ram<193>, R<193>k<193>, S<193>r<193>, Um<193>, ç
<185><193>nt<193> and Amogh<193> are mentioned too.
There is also the mention of a mantra of 100 letters (·at<193>k<218>aramantra), ç
formed by combining the letters of the three metres†g<193>yatr<200>, ç
tri<218><219>ubh and anu<218><219>ubh. Its repetition gives longevity.
@S10N = Chapter 34 (77 verses)
This chapter deals with a number of rites that can bring about the ç
following results: longevity; cure of fever; controlling the minds ç
of others; attracting others to oneself; conquering of enemies and ç
so on.
@S10N = Chapter 35 (22 verses)
Pr<193><207>aprati<218><219>h<193> or infusing life into an image ç
or a yantra (geometrical diagram of a deity) is the subject matter ç
here. Pr<193><207>a or life force is considered as a deity and her ç
description is given in a dhy<193>na-·loka. She has three eyes. She ç
is seated on a lotus situated in a boat. She is holding in her hands ç
p<193>·a (noose), ik<218>u-koda<207><195>a and pa<210>cab<193><207>as ç
(bow of sugarcane, with five arrows) as also a<209>ku·a (goad) and ç
as<216>k-kap<193>la (skull-cup with blood).
Her companions are M<216>t<193>, Vaivasvat<193>, Pr<193><207>al<193>, ç
°k<216><218>y<193> and others.
@S10N = Chapter 36 (63 verses)
This concluding chapter starts with the condemnation of a person who ç
does not have a son or sons, the reasons for the same and the remedies ç
like the performance of a yaj<210>a (sacrifice).
It also describes the qualifications of a guru (spiritual preceptor, ç
especially the one who gives a mantra and gets all the rituals performed) ç
such as competence in this science, capacity to bless or chastise, ç
conquest of the six enemies (like lust), deep knowledge of the scriptures, ç
being devoted to the worship of God, infinite patience, compassion ç
towards the disciples, capacity of good speech in order to teach well ç
and so on.
The disciple too must deserve his grace by cultivating the following ç
virtues: humility, devotion to the guru as if he is God Himself, service ç
to him, observing truth and celibacy strictly, being controlled in ç
eating, sleep and speech, deep interest in studies, eschewing calumny ç
and so on.
Why this work is called Prapa<210>cas<193>ra is explained at the ç
end. It is the s<193>ra (essence) of the prapa<210>ca (the world).
The treatise ends with a prayer of God as `parip<220>r<207>atejas' ç
(Overfull or Perfect Light).
@S10N = Conclusion
The Prapa<210>cas<193>ra is a difficult work to understand since ç
it contains an esoteric spiritual science. Such sciences used to be ç
taught privately in the seclusion of forest monasteries or academies. ç
That is why they were either in the form of s<220>tras (aphorisms) ç
or couched in an apparently unintelligible language. Only those who ç
could unearth their special terms or symbols, could understand them.
Though the commentary Vivara<207>a of Padmap<193>da does throw light ç
on the many aspects of this work, it still leaves much unsaid or unexplained, ç
especially in the field of the various mantras. Since the tradition ç
that these mantras were to be transmitted directly and secretly by ç
the guru to the disciple was till very strong (and inviolable) during ç
his time, Padma-p<193>da must have played it safe by strictly following ç
it.
However, the work Prapa<210>cas<193>ra-s<193>rasa<209>graha of G<200>rv<193><207>endra ç
Sarasvat<200> has untied the knots in many places and has made it ç
easier to understand and follow.
@NT = Prapannag<200>t<193>
Imitation has been a natural characteristic of human beings. The Bhagavad-g<200>t<193> ç
of the great epic Mah<193>bh<193>rata (Bh<200><218>maparva 25-42)†more ç
popularly known as the G<200>t<193>†has given rise to many other ç
tracts of various lengths composed in verse form, to which the appellation ç
G<200>t<193> is given.
Sixteen of such G<200>t<193>s are from the Mah<193>bh<193>rata, ç
twenty from various pur<193><207>as and four found as independent ç
works untraced to any other known epic or pur<193><207>a.
The Prapannag<200>t<193>†also called the P<193><207><195>avag<200>t<193>†belongs ç
to the last group.
There are eighty verses in different metres. They contain prayers ç
addressed to K<216><218><207>a as Vi<218><207>u-N<193>r<193>ya<207>a, ç
the sentiment of prapatti (surrender to God) being predominant. Hence ç
the title Prapannag<200>t<193> (prapanna = one who has surrendered ç
to God) is very apt.
The number of bh<193>gavatas or devotees of God whose prayers are ç
included here exceeds sixty! Apart from the five P<193><207><195>avas ç
and a few persons prominent in the Mah<193>bh<193>rata like Bh<200><218>ma, ç
Dro<207>aand Vidura, many important sages figure in this work. Some ç
of them are Agastya, Dhaumya, N<193>rada, Vi·v<193>mitra, Jamadagni, ç
Bharadv<193>ja, Gautama, Atri, Vasi<218><219>ha, Ka·yapa, Bh<216>gu, ç
Par<193>·ara, Vy<193>sa and <185>uka.
The subjects dealt with are, briefly, as follows:
Homage to the great devotees like Prahl<193>da, Pu<207><195>ar<200>ka, ç
<185>aunaka, Bh<200><218>ma, N<193>rada and others; verses in praise ç
of the five P<193><207><195>avas who were great devotees of K<216><218><207>a; ç
description of the physical beauty of the Lord Vi<218><207>u-N<193>r<193>ya<207>a; ç
prayer for devotion; various names of the Lord; obeisance to Him; ç
devoted meditation on the Lord is superior to all religious acts; ç
power of the divine name.
@NT = prapatti
@N1 = (`total surrender [to God]')
This is a technical term specially used  in  R<193>m<193>nuja's  (<MS>A.<|>D.<D>  1017-1137) ç
philosophy (Vi·i<218><219><193>dvaita) and religion (<185>r<200>vai<218><207>avism).
God-realisation is the final or the only goal of life. This again, ç
is possible only through the path of bhakti or devotion.
This path of bhakti has two aspects: Bhaktiyoga and Prapatti or Prapattiyoga.
Though the path of bhakti or devotion to God ( = Bhaktiyoga) has been ç
considered as easy, as compared to other yogas like J<210><193>nayoga, ç
it too has quite a few formal rules and disciplines to be followed. ç
This naturally makes it a difficult path, especi-ally for the ordinary ç
s<193>dhakas who have neither the time nor the competence to observe ç
these disciplines properly.
Here comes the role of the second path, that of prapatti or total ç
surrender, complete submission to the will of God.
Prapatti is also known by other names such as <193>tmasamarpa<207>a, ç
bhara-ny<193>sa, nik<218>epa, ny<193>sa, prapadana and ·ara<207><193>gati. ç
The meanings of all these terms are, more or less, the same.
The path of prapatti has the support of the scriptures, both the ·rutis ç
and the sm<216>tis (vide <185>vet<193>·vatara Upani<218>ad 6.18; ç
Mah<193>n<193>r<193>ya<207>a Upani<218>ad 24.1; Bhagavad-g<200>t<193> ç
2.7 and 18.66).
The practice of prapatti is of three types: svani<218><219>h<193> ç
(depending upon oneself); uktini<218><219>h<193> (depending upon the ç
<193>c<193>rya's words or teachings); and, <193>c<193>ryani<218><219>h<193> ç
(giving the entire responsibility to the <193>c<193>rya or the spiritual ç
teacher).
Prapatti has six steps. They are: 1)<+>Making up one's mind to follow ç
the path approved by God and his great devotees (as revealed in the ç
holy books).
@NID = 2)<+>Eschewing the path of evil that goes against the will of ç
God and spiritual evolution.
@NID = 3)<+>Tremendous faith in God that he will certainly protect ç
the surrendered person.
@NID = 4)<+>Hence, voluntarily and willingly choosing God alone as ç
one's protector.
@NID = 5)<+>Self-oblation or mentally keeping oneself at the feet of ç
God for protection.
@NID = 6)<+>A sense of utter unworthiness of oneself vis-a-vis the ç
task of attaining liberation.
The following persons are unfit even for prapatti: those who are 1) ç
unable to follow the prescribed disciplines; 2) devoid of faith in ç
the <193>c<193>rya or teacher; 3) not willing to serve the guru or ç
spiritual preceptor; and, 4) lacking faith in God.
@SPACE1 = 
The Ahirbudhnya Sa<221>hit<193> (37.2.27) and 28) as also the Rahasyatrayas<193>ra ç
(ch.21) of Ved<193>nta De·ika (<MS>A.<|>D.<D> 1268-1369) deal with ç
this subject.
One of the oft-quoted examples of prapatti is that of Vibh<200><218>a<207>a ç
in the R<193>m<193>ya<207>a of V<193>lm<200>ki (vide Yuddhak<193><207><195>a, ç
chs. 17.17; 18.3; 18.33,34).
The cardinal principle in the doctrine of prapatti is that mok<218>a ç
or liberation depends entirely on God's grace and not on the efforts ç
of the s<193>dhaka or the spiritual aspirant. Whereas there are limitations ç
to human efforts, no such limitation exists for God's grace!
@NT = pr<193>rabdhakarma
@N1-1 = (`karma that has <R>ç
started giving the results')
The doctrine of karma†that karma or action done in any life must produce ç
its result, good or bad, now or in future (including future births)†is ç
a fundamental belief in Hinduism.
Of the three karmas recognised (See <MS>KARMA<D> for details.) the ç
pr<193>rabdha karma is the second. It simply means the karma that ç
has started giving its fruits by causing the present birth.
After discussing the various possibilities  and  alternatives  as  regards  the ç
punarjanma or rebirth by pr<193>rabdha-karma, the Vy<193>sabh<193><218>ya ç
(commentary by Vy<193>sa [<MS>A.<|>D.<D> 600]) on the Yogas<220>tras ç
(2.13) of Pata<210>jali (200 <MS>B.<|>C.<D>) comes to the conclusion ç
that several karmas out of the accumulated stock (called sa<210>citakarma) ç
will cause one janma or birth. However, one of the karmas will be ç
the major one, the others being minor ones, but whose nature is in ç
consonance with the major karma.
The pr<193>rabdhakarma is responsible for j<193>ti (birth in a particular ç
species likehuman or animal and so on), <193>yus (duration of life) ç
and bhoga (various experiences, good and bad).
Whether <193>tmaj<210><193>na (or brahma-j<210><193>na), knowledge ç
of the Self, destroys pr<193>rabdhakarma also (along with the sa<210>cita) ç
has been a moot point. Most of the schools of Hindu philosophy do ç
not accept it since it has already started bearing fruit even as an ç
arrow already discharged cannot be withdrawn. That is why it is seen ç
that the j<200>vanmuktas also (those who are liberated, even while ç
living here) are seen to suffer from its effects.
@NT = Pr<193>rthan<193> Sam<193>j
During the eighteenth and the nineteenth centuries, India witnessed ç
several Hindu revival and reform movements. Though generally rooted ç
in the ancient value-system, they tried to give Hindu religion and ç
society a modern look, in consonance with the changing ethos brought ç
about by the British conquest of India and an invasion of Western ç
culture.
One such movement of these times is the Pr<193>rthan<193> Sam<193>j ç
of Bombay (now Mumbai). Inspired by the visits of Ke·avacandra Sen ç
(<MS>A.<|>D.<D> 1838-1884), Dr. °tm<193>r<193>m P<193><207><195>ura<209>g ç
(<MS>A.<|>D.<D> 1823-1898) started it in 1867. R. G. Bha<207><195><193>rkar ç
(<MS>A.<|>D.<D> 1837-1925) and M. G. R<193>na<195>e (<MS>A.<|>D.<D> ç
1842-1901) were the main leaders of this movement.
Though inspired by the Br<193>hmo movement of Bengal, the Pr<193>rthan<193> ç
Sam<193>j did not go to the extent of alienating itself from the traditional ç
Hindu religion and society. It remained more like a protestant movement ç
within Hinduism.
A positive belief in the unity of God, a great stress on the abandonment ç
ofcaste, introduction of remarriage of widows, encouragement of female ç
education, and the abolition of the purdah system as also child marriage ç
were the main tenets and programmes of this Sam<193>j.
It drew its inspiration largely from the Hindu scriptures and the ç
songs of Mar<193><219>hi mystical poets.
The movement did not spread beyond the Mah<193>r<193><218><219>ra ç
region and gradually fadedout.
@NT = Pra·astap<193>da
The Vai·e<218>ikas<220>tras of Ka<207><193>da or Aul<220>kya (who ç
preceded Buddha) has a commentary called Pra·astap<193>dabh<193><218>ya ç
or Pad<193>rthadharmasa<209>graha by Pra·asta-p<193>da. This commentary ç
is more like a long independent essay on the Vai·e<218>ika-s<220>tras ç
than a regular bh<193><218>ya. Apart from explaining the several terms ç
and concepts of the s<220>tras, it has also brought in other doctrines ç
like those of creation, dissolution, number, atoms in a molecule and ç
transformation of colours by heat and so on, which do not find a place ç
in the original.
Pra·astap<193>da was the earliest writer on the Vai·e<218>ikas<220>tras ç
after Ka<207><193>da and must have lived in the 5th or the 6th centuries ç
<MS>A.<|>D.<D>
@NT = Pra·na Upani<218>ad
This Upani<218>ad has been assigned by tradition to the Atharvaveda. ç
The Mu<207><195>aka Upani<218>ad which also belongs to the same ç
Veda, has been called `Mantra' and this Upani<218>ad as `Br<193>hma<207>a' ç
by <185>a<209>kara (<MS>A. D.<D> 788-820).
Considered  as  an  ancient  and authoritative scripture, it has been ç
listed among the ten major Upani<218>ads. Since it is in the form ç
of six questions and their answers, it is called `Pra·nopani<218>ad' ç
or even `<186>a<219>pra·nopani<218>ad'. The total number of verses, ç
all in prose, is 67.
@S10N = First Chapter (16 verses)
Six sages, all devoted to Brahman† Suke·<193>,   Satyak<193>ma,   Saury<193>ya<207>i, ç
Kausalya, Bh<193>rgava and Kabandh<200>†once approached the venerable ç
sage Pippal<193>da, with the sacrificial fuel in hand (as perthe ç
prescribed traditional mode of approaching the spiritual teacher) ç
and expressed theirdesire to know Brahman from him. Pippal<193>da ç
advised them to live in his house for a year, doing tapas or austerity ç
and observing brahmacarya (all the disciplines of studenthood). After ç
completing their probation, they could approach him with their questions ç
and doubts.
Having complied with his directions, they returned to him. Kabandh<200> ç
was the first to ask: `O Venerable one! From where are all these creatures ç
born?'
Pippal<193>da's reply may be summarised as follows: Praj<193>pati, ç
the Lord of creation, desirous of offspring, performed tapas (austerity ç
in the form of intense concentration on the process of creation as ç
done in his previous existence) and brought out (of himself) a pair, ç
the rayi and the pr<193><207>a, which pair would produce the creatures ç
on his behalf.
Rayi is matter and pr<193><207>a is the sentient spirit. Rayi is identified ç
with the moon and pr<193><207>a with the sun. The sun and the moon ç
together are also responsible for the concept of time.
After  briefly  narrating  creation, Pippal<193>da describes the two ç
paths†the Uttar<193>ya<207>a and the Dak<218>i<207><193>yana†by which ç
human beings go to the higher worlds in accordance with their deeds. ç
Those who are devoted to i<218><219><193>p<220>rta (Vedic rituals ç
like the Agnihotra and public utility works like digging wells) will ç
go to the pit<216>loka (the world of manes) by the latter path. However ç
they have to return to this world after exhausting their religious ç
merit. Others devoted to tapas (austerity), brahmacarya (continence) ç
and vidy<193> (contemplation on the deities) will go to the °dityaloka ç
(the world of the sun) by the former and will not return to this mundane ç
existence.
Continuing his discourse, Pippal<193>da compares the sa<221>vatsara ç
(the year with its two parts, the southern and the northern solstices), ç
the month (with its dark and bright fortnights) and the day (with ç
its day and night divisions) to Prj<193>pati. Even anna or food is ç
Praj<193>pati, because, it is out of the semen, the product of food, ç
that people are born; and, Praj<193>pati is the origin of all beings.
@S10N = Second Chapter (13 verses)
The Second pra·na (= question) or chapter starts with the question ç
of Bh<193>rgava: Sir, how many devas (gods) are supporting this body? ç
Who is illumining it? Among them who is the best?
In reply Pippal<193>da declares that it is pr<193><207>a that is actually ç
supporting the body. He narrates a brief story as to how the sense-organs ç
like the eye or the ear claimed superiority but were silenced. When ç
the enraged pr<193><207>a moved as if he was getting up, all the other ç
organs too were forced to rise up from their locations. It was like ç
the queen bee rising, forcing all the ordinary bees also to rise. ç
Then all the senses, understanding pr<193><207>a's superiority started ç
hymning to him. In this hymn, pr<193><207>a has been praised not just ç
as the Self, the master of the body, but as the Supreme Self, Praj<193>pati ç
himself. He is fire, sun, rain, Indra, V<193>yu, the earth, in fact, ç
the Supreme God. He is Parame·vara or Rudra. He it is that receives ç
all oblations given in sacrifices. In this body, it is he who functions ç
as the sense-organs.
They request him to protect them even as a mother protects her children.
@S10N = Third Chapter (12 Verses)
Now, it is the turn of Kausalya to question Pippal<193>da. His question ç
concerns the pr<193><207>a or the vital energy working inside the ç
body. His questions are: Whence is this pr<193><207>a born? How does ç
he come into this body? How does he distribute himself and establish ç
himself? In what way does he depart? How does he support the external ç
world? How does he support what is inside oneself?
Inthe previous section though pr<193><207>a's  nature  and  greatness  were ç
described, his essential nature as the highest truth and his functions ç
were not. They are now being delineated.
The Pr<193><207>a is born or manifested from the °tman (Paramapuru<218>a ç
or the Supreme Being). He comes into the body effortlessly like a ç
shadow following a man, when the j<200>v<193>tman (the individual ç
Self) enters it. He appoints the five functional pr<193><207>as (his ç
own different aspects or parts) even as a king appoints his officers ç
and apportions their duties. The five pr<193><207>as are: pr<193><207>a ç
(secondary), ap<193>na, vy<193>na, ud<193>na and sam<193>na. Their ç
respective functions are: breathing and activating the eyes and the ç
ears; excretion; general diffusing of the air inside the body; taking ç
the j<200>v<193>tman out of the body at the time of death; equitable ç
distribution of the essence of food all over the body.
There are 101 n<193><195><200>s (tube-like structures for the flow ç
of pr<193><207>ic energy) in the region of the heart. The ud<193>na ç
takes the j<200>v<193>tman through one of them, the su<218>umn<193>, ç
to either meritorious worlds or hell or back to the human world, depending ç
on the karma of that individual† whether good or bad or mixed.
°ditya or the sun is the external aspect of pr<193><207>a who is also ç
supporting the power of the eye inside. The earth, the sky, the light ç
(outside) and the air (outside) are the external aspects respectively ç
of ap<193>na, sam<193>na, ud<193>na and vy<193>na.
At the time of death, in whatever way the mind (of the dying person) ç
works, the (chief) pr<193><207>a takes him to the world appropriate ç
to him.
The section concludes with a eulogy of the person who has mastered ç
the knowledge of this pr<193><207>a.
@S10N = Fourth Chapter (11 verses)
Now Saury<193>ya<207>i questions Pippal<193>da: In this puru<218>a ç
(or body) what is it that sleeps? What is awake? Between these two, ç
who sees the dreams? Who enjoys happiness? In whom are all united ç
and dissolved?
When the sense-organs with their experiences become one with the mind, ç
a person is said to be sleeping. Even then, the five pr<193><207>as ç
(compared to the five Vedic fires like g<193>rhapatya by the Upani<218>ad) ç
are fully awake since they continue to function under the general ç
guidance of the mind. It is this mind (or the j<200>v<193>tman, the ç
individual Self closely associated with it) that gets all the dream ç
experiences.
However, when this mind (or the j<200>v<193>tman) with the senses ç
withdrawn into itself is merged in Brahman (in deep sleep), there ç
are no dreams. On the other hand, there is an experience of happiness. ç
It is like the birds coming back in the evening to the tree where ç
they live and be at peace. Thus, it is into Brahman (or Param<193>tman, ç
the Supreme Self) that all get united and dissolved.
The section ends with the eulogy that one who realises this truth ç
becomes one with all.
@S10N = Fifth Chapter (7 verses)
Then Satyak<193>ma steps in to put the question: `What world does ç
a human being, who has been meditating on O<209>k<193>ra throughout ç
his life, even until death, gain?'
Pippal<193>da now discourses on the significance of Pra<207>ava or ç
O<209>k<193>ra, the method of meditating on it and the consequent ç
fruits attained.
O<209>k<193>ra is (i.e., can be a symbol for) both Parabrahman and ç
Aparabrahman, the unmanifested and the manifested aspects. Hence one ç
can choose it as a symbol for meditation on either of these aspects.
Om has three parts, syllables, called `m<193>tras': a, u and m. One ç
who meditates on Brahman through the first syllable `a,' attains a ç
human birth that is conducive to a life of tapas (austerity) and brahmacarya ç
(celibacy). If he meditates through the second syllable `u,' he is ç
reborn in the world of Soma or moon. After enjoying vibh<220>ti (wealth ç
and intense pleasures) there, he will return to the human world. But ç
one who meditates on the third syllable, `m,' will be freed from all ç
sins, will go to Brahmaloka, the abode of Brahman and will not return ç
to mundane existence.
Some commentators have interpreted the word `m<193>tr<193>' in the ç
original not as `syllable', but as a unit of time. According to them, ç
one who chants Om for one unit of time†say, for instance, one second†will ç
go to the world of men, for two units of time, to the world of moon ç
and for three units, to Brahmaloka. This of course applies to each ç
repetition. And it must be accompanied by meditation on Brahman.
@SPACE = 
@SPACE = 
@S10N = Sixth Chapter (8 Verses)
@SPACE = 
Once, Hira<207>yan<193>bha, the prince of Kosala had asked Suke·<193> ç
the question, `Do you know the <186>o<195>a·akala Puru<218>a (the ç
person with 16 aspects)?' But he did not know the answer. Now Suke·<193> ç
is asking Pippal<193>da the same question.
Pippal<193>da replies that this Puru<218>a is in one's own body. He ç
is the <193>tman. He is the creator.
He first created Pr<193><207>a or Hira<207>yagarbha, the primary Person ç
(also called S<220>tr<193>tman) the totality of subtle creation. From ç
this latter Pr<193><207>a, these others were evolved: ·raddh<193> ç
(faith), <193>k<193>·a (ether or sky), v<193>yu (air), jyoti (light ç
or fire), <193>pas (water), p<216>thv<200> (earth), indriya (sense ç
organs), manas (mind), anna (food), v<200>rya (strength  of  body),  tapas  (austerity), ç
mantras (Vedas), karma (Vedic rituals), lokas (the various worlds) ç
and n<193>ma (names of objects in creation).
All these aspects of creation depend on the Puru<218>a even as the ç
spokes in a wheel, on its hub.
At the time of dissolution of the world all these get merged in the ç
Puru<218>a, even as the rivers merge in the ocean.
The six sages then worshipped Pippa-l<193>da as their guru and returned ç
to their homes.
@SPACE = 
@NT = prastara
@N1 = (`that which is strewn')
@SPACE1 = 
In Vedic sacrifices, since even the implements used are considered ç
sacred, they should be kept on the vedi (platform) in a clean and ç
pure place. Whereas cleanliness is external and physical, purity is ç
more a ceremonial concept.
Before placing the sruk and sruva (offering ladles) on the vedi, a ç
small bundle of darbha grass (Poa cynosuroides) is spread out first. ç
The ladles are then placed on this bundle which is called prastara.
@SPACE = 
@NT = prast<193>va
See <MS>S°MAN.
@SPACE = 
@NT = prasth<193>natraya
@N1 = (`the three basic<R>ç
treatises [of Ved<193>nta]')
@SPACE1 = 
Among the six systems of Hindu philosophy†generally called the <186>a<195>-dar·anas†the ç
Ved<193>nta system is certainly the crest-jewel. With a balanced combination ç
of great respect for the Vedas and incontrovertible logic that demolishes ç
the non-Vedic systems, it has earned for itself an unenviable place ç
among the well-known philosophies of the world.
The Ved<193>nta system is built primarily on the prasth<193>natraya, ç
the three foundational works that take one to the final goal of life ç
(= prasth<193>na). They are: the <185>rutiprasth<193>na (Upani<218>ads); ç
the Sm<216>ti-prasth<193>na (the Bhagavadg<200>t<193>) and the Ny<193>yaprasth<193>na ç
(the Brahmas<220>tras).
Of these three, the Upani<218>ads being the <185>ruti, the cardinal ç
scripture of Hindu-ism, are of utmost importance.
The Brahmas<220>tras, being a systematisation of the philosophy ç
of the Upani<218>ads, helps in building up the metaphysical frame ç
of Ved<193>nta.
The Bhagavadg<200>t<193>, being an extremely popular and highly ç
venerated work, had to be admitted into the prasth<193>na group.
@SPACE = 
@NT = prastot<216>
@N1 = (`the eulogist')
@SPACE1 = 
@SPACE1 = 
The udg<193>t<216> (`chanter'), one of the four principal priests ç
in a Vedic sacrifice, has three assistants, out of whom the prastot<216> ç
(or prastot<193>) also is one. He is responsible for chanting the ç
prast<193>va (the first part or prelude in a s<193>man chant). He ç
also participates in the prasarpa<207>a (ritual procession of priests ç
to the <193>st<193>va, a place meant for chanting). It is again he ç
who sings solo, a laudatory hymn to Yama (the god of death) after ç
the horse is immolated in the A·vamedha sacrifice.
See also <MS>UDG°T<184>.
@SPACE = 
@NT = pra·v<193>sa
@N1 = (`exhalation')
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
The words ·v<193>sa and pra·v<193>sa have been used by Pata<210>jali ç
(200 <MS>B.<|>C.<D>) in his Yogas<220>tras (2.49) in connection with ç
the definition of pr<193><207><193>y<193>ma. <185>v<193>sa is inhalation ç
and pra·v<193>sa is exhalation. They are also called p<220>raka and ç
recaka. When theirmovement is stopped temporarily, it results in ç
pr<193><207><193>y<193>ma.
See also <MS>PR°Ø°Y°MA<D>.
@SPACE = 
@NT = Prat<193>parudra Deva
@SPACE = 
A descendant of the S<220>ryava<221>·a (the Solar race), Prat<193>parudra ç
Deva was the king of Orissa from <MS>A.<|>D.<D> 1497 to 1540. Though ç
a valiant king, he was deeply influenced by <185>r<200>k<216><218><207>a ç
Caitanya (<MS>A.<|>D.<D> 1485-1533) and became his initiated disciple. ç
As a result, he neglected the affairs of the State and started spending ç
most of his time in spiritual pursuits. Under his patronage, the Oriya ç
language developed remarkably well. Several works on bhakti or devotion ç
to K<216><218><207>a were composed in his time.
See also <MS><185>R®K<184><186>ØACAITANYA.
@SPACE = 
@NT = pr<193>taranuv<193>ka
@N1 = (`morning litany')
@SPACE = 
In the Somay<193>gas†sacrifices requiring the oblation of the soma ç
juice†the day on which the juice is extracted is called the `suty<193>'. ç
On the previous night, during its last part, the hot<216> priest recites ç
several mantras, technically called `pr<193>ta-ranuv<193>ka'. It is ç
generally chanted by him sitting between the two havirdh<193>na carts ç
(carrying the vessels full of the soma plants or stalks).
The litany comprises three sections. The total number of <216>ks (<184>gvedic ç
mantras) to be chanted varies from 100 to 360, and, sometimes up to ç
1000!
@SPACE1 = 
The pitch of the voice while chanting them has to be gradually raised ç
through seven tones.
