The term `utsava,' often used with the word `vrata,' and sometimes ç
as its equivalent also, literally means `to cause to go upward'. But ç
in usage, it means a joyous festive occasion which naturally buoys ç
up the spirits of the participants. If vrata, being of the nature ç
of tapas or austerity, tends to restrain the spirits, utsava frees ç
it and brightens it. The two are thus complementary. Hence, invariably, ç
almost every vrata is followed by an utsava, thus offsetting its rigours ç
and bringing joy and happiness in its train.
An overwhelming majority of the Hindu festivals are not only vratas ç
but also utsavas, since the latter follow the former without exception.
A classification of these vratas may now be attempted, based on the ç
traditional literature like the pur<193><207>as and allied works. ç
If in a vrata the stress is on physical austerity like fasting, it ç
is a `k<193>yika-vrata,' a vrata pertaining to the body. If the stress ç
is on speaking the truth and reciting the scriptures, both being a ç
function of the organ of speech, it is called `v<193>cika-vrata' or ç
vrata pertaining to speech. If on the other hand, the emphasis is ç
on controlling the mind, by controlling the passions and prejudices ç
that arise in it, it is a `m<193>nasa-vrata' or vrata pertaining to ç
the mind. However, it should be noted that all these three disciplines ç
are almost always present in every vrata.
@SPACE1 = 
The second classification is based on time. A vrata to be performed ç
just for a dina or day is a `dinavrata;' one lasting for a v<193>ra ç
or a pak<218>a (week or fortnight) is a `v<193>ravrata' or a `pak<218>avrata;' ç
one to be undertaken on a particular tithi (a day according to the ç
lunar calendar) or when a particular nak<218>atra (asterism) is on ç
the ascendant, is respectively called a `tithivrata' or `nak<218>atravrata'. ç
Most of the vratas now in vogue are based on the tithis of the lunar ç
calendar.
The third classification is according to the deity (an aspect of God) ç
worshipped; for instance, Svar<207>a-gaur<200>vrata or Varasiddhivin<193>yakavrata ç
or Satya-n<193>r<193>ya<207>avrata (dedicated respectively to the ç
deities Gaur<200>, Ga<207>apati and Satya-n<193>r<193>ya<207>a).
The fourth classification is based on for whom it is meant: those ç
specially recommended for women<+>are `str<200>vratas;' for k<218>attriyas ç
(warrior-class), `k<218>attriya-vratas' and so on.
Who are the persons eligible to perform a vrata? Anyone who has faith ç
in it and wishes to perform it as per the rules, even if he be a mleccha ç
(alien)! Whereas the Vedic sacrifices were strictly restricted to ç
the men of the three upper castes (called dvijas), the doors of the ç
vratas were thrown open to one and all,thus bringing ritualistic ç
Hinduism to especially the lower castes and women, who had been denied ç
that privilege for centuries. Historically speaking, this might have ç
been a master-stroke devised by the liberal-minded religious leaders ç
of the Hindu society to prevent the exodus of their flock to the Jaina ç
and the Buddhist folds, which were singularly free from the labyrinth ç
of rituals and offered a simple religion of ethical conduct.
@SPACE1 = 
Though the rules concerning the vratas had been very much liberalized ç
to embrace as large a segment of the society as possible, there had ç
to be some rules guiding the whole process in order to protect and ç
preserve the sanctity of the ritual  system  itself.  These  may  be ç
summarized  as  follows:  During  the period of the observance of ç
a vrata, one should keep one's person clean and pure, observe celibacy, ç
speak the truth, practise forbearance, avoid non-vegetarian foods ç
and scrupulously perform all the rituals connected with it. Once a ç
vrata is undertaken, it should never be left unfinished nor a new ç
one started before completing it. But, one should never start the ç
observance while in a·auca (ceremonial impurity brought about by birth ç
or death in one's family). Persons too old or too sick, can get the ç
vrata performed for them by the close relatives if they are willing. ç
Women are advised to take the permission of<|>* their father or husband ç
or son. Once the decision is taken to perform a vrata, the actual ç
commencement should be made only as per the auspicious time, place ç
and mode laid down by the books.
Generally, the performance of almost all the vratas starts in the ç
early morning. The votary has to get up in the br<193>hmamuh<220>rta ç
(almost an hour before sunrise), have his ablutions and bath, complete ç
the usual daily rituals like the sandhy<193> (worship of God as the ç
immanent power in the sun) and worship of the family deity, and then ç
start the vrata with the sa<209>kalpa.
The sa<209>kalpa or religious resolve is the most essential, and even ç
compulsory, part of the vrata. Sans it, the whole rite gets nullified. ç
Though the mantras for sa<209>kalpa vary from vrata to vrata, the ç
general context and pattern are almost identical. The performer has ç
to mention his name, the year, month, day and date, the purpose of ç
the vrata, the deity he is propitiating as also the special discipline ç
(if any) he will follow. This is done ceremonially with a little water ç
taken in the palm of the hand.
The total number of vratas and utsavas listed by the largest of the ç
published works†Caturvarga-cint<193>ma<207>i of Hem<193>dri (13th ç
century)†comes to about 700. However, most of these are less known ç
individual vratas.
The following is a list of the more important utsavas or festivals ç
normally observed all over the country by the Hindus:
@IN2 = Ak<218>ayyat<216>t<200>ya, Balipratipad<193>,<R>ç
C<193>ndram<193>na Yug<193>di, C<193>turm<193>sya,<R>ç
Da·ahar<193>, D<200>p<193>val<200>, Durg<193>p<220>j<193>,<R>ç
Ga<207>e·a-caturth<200>, Gurup<220>r<207>im<193>,<R>ç
Holi,Janm<193><218><219>am<200>, Kumbhamel<193>,<R>ç
Mah<193>navam<200>, Mah<193>·ivar<193>tri,<R>ç
Makarasa<209>kr<193>nti, Navar<193>tra,<R>ç
Rak<218><193>bandhan, R<193>manavam<200>,<R>ç
Rathay<193>tr<193>, Vijayada·am<200>.
@SPACE1 = 
See under each title for details.
@NT = vr<193>tyas
The Manusm<216>ti (2.38, 39) declares that a br<193>hma<207>a, k<218>attriya ç
and vai·ya should undergo the upanayana sacrament before the ages ç
of 16, 22 and 24 respectively. If they do not, they become vr<193>tyas, ç
unfit  to  receive  the  S<193>vitr<200>mantra (G<193>yatr<200>mantra).
