Another name of Vi<218><207>u which is extremely common and popular ç
is N<193>r<193>ya<207>a. The word means:
a)
@NK NO # = One who has made the causal waters his abode;
b)
@NK NO # = One who is the abode of all human beings;
c)
@NK NO # = One who has made the hearts of human beings his abode;
d)
@NK NO # = One who is the final goal of all human beings.
@SPACE1 = 
The first interpretation has given rise to a description of N<193>r<193>ya<207>a ç
which is common and popular, as follows:
After the destruction of the universe of the previous cycle and before ç
the creation  of  the  next,  N<193>r<193>ya<207>a,  the Supreme God, ç
falls asleep on his bed of the great serpent <185>e<218>a (also called ç
Ananta), which is floating on the waters of the ocean K<218><200>rasamudra ç
(`ocean of milk'). One of his legs is resting on the lap of his consort ç
Lak<218>m<200>, who is gently pressing it. When he is dreaming as ç
it were, of the next creation, a lotus springs forth from his navel ç
along with god Brahm<193> seated on it. After waking up, he instructs ç
Brahm<193> to proceed with the act of creation.
This is a highly allegorical picture. The ocean represents causal ç
waters from which all life springs, a concept not uncommonly found ç
in other religions also. Or, since it is K<218><200>rasamudra, the ç
ocean of milk, it stands for the purest form of Prak<216>ti or nature ç
in its undifferentiated state, whiteness indicating this purity.
Out of the several equivalents of the word <193>pas (= water), is ç
the word am<216>ta (= nectar, signifying bliss also). Hence we can ç
say that the Lord N<193>r<193>ya<207>a is floating on the ocean of ç
bliss, which is as it shouldbe.
The serpent <185>e<218>a or Ananta is said to have a thousand heads ç
and is supporting the worlds on its hoods. Ananta, which literally ç
means the `endless' or `infinite' actually stands for cosmic time ç
which is infinite or endless. Created worlds come into being in time ç
and are sustained in time. This is the meaning of the thousand hoods ç
supporting the worlds. The thousand hoods simply indicate the innumerable ç
divisions of time.
The concept of the thousand hoods supporting the worlds can also lead ç
to the interpretation that the serpent represents the cosmic space, ç
in which everything exists.
The word <185>e·a is also significant. It actually means `the remainder,' ç
`what is leftover at the end'. Since creation cannot proceed out of ç
nothing, it is to be assumed that `something' is `leftover' (·e<218>a) ç
from the previous creation, which forms the seed as it were, for the ç
next. So, <185>e<218>a represents the totality of the j<200>vas or ç
indi- vidual souls in their subtle form, leftover from the previous ç
cycle and needing more opportunities for regeneration.
Serpent can also represent k<193>ma or desire which is always leftover ç
(·e<218>a), even after acquisition and enjoyment of the desired object. ç
This goes on until mok<218>a or final liberation. Hence, in a cosmic ç
sense, it can stand for the desire of the Lord to proceed with the ç
next cycle of creation after rest!
@SPACE1 = 
Vi<218><207>u is always described as N<200>lamegha·y<193>ma, of a ç
dark blue hue like that of the rain-bearing cloud. Since the infinite ç
empty space appears as deep blue in colour, it is but proper that ç
Vi<218><207>u the all-pervading cosmic power, be depicted as blue ç
in colour.
The commonest form of the Vi<218><207>u icon has one face, four arms ç
holding ·a<209>kha (conch), cakra (discus), gad<193> (mace), padma ç
(lotus) and he wears a necklace with the famous gem Kaustubha dangling ç
on the lock of hair known as <185>r<200>vatsa, on the left chest. ç
He is also wearing a garland (of gems, or fragrant flowers) Vaijayant<200> ç
by name.
@SPACE1 = 
The four arms represent the four quarters, hence, absolute power of ç
the Lord in all directions. The ·a<209>kha represents the five elements ç
like the earth, water etc. Cakra stands for the cosmic mind. Gad<193> ç
indicates the cosmic intellect and the padma points to the evolving ç
world. Just as the lotus is born out of water and unfolds gradually ç
in all its glory, this world also is born out of the causal waters ç
and evolves gradually in all its splendour. Hence the lotus stands ç
for the evolved world. This world can be created only by a combination ç
of the five elements, the mind, and the intellect. Hence the total ç
meaning of this symbology would be that the Lord Vi<218><207>u is ç
the creator and master of this world. The curl of hair, <185>r<200>vatsa, ç
represents all objects of enjoyment, the products of nature. The gem ç
Kaustubha, resting on it, stands for the enjoyer. So, this world of ç
duality, consisting of the enjoyer and the enjoyed, is like an ornament ç
for the Lord. The garland Vaijayant<200> is symbolical of the subtle ç
elements (bh<220>ta-tanm<193>tras).
Sometimes   two   more   weapons, Nandaka the sword (representing ç
wisdom) and <185><193>r<209>ga the bow (representing the cosmic senses) ç
are added to the arsenal of Lord Vi<218><207>u.
@S8ITAL = AVAT°RAS (INCARNATIONS) OF LORD VI<186>ØU
To ward off the extraordinary perils to which mankind is prone†maybe ç
the visitations from the demons, maybe from the human malefactors†and ç
to preserve the socio-ethical order, Lord Vi<218><207>u whose duty ç
it is to preserve this world, often incarnates himself. Though such ç
incarnations are popularly considered to be ten, there is no limit ç
to their number. Nor are there any restrictions regarding the time ç
and place of their appearance. Whenever dharma declines and adharma ç
prospers he bodies himself forth to restore the balance in the world.
In the Matsy<193>vat<193>ra (Fish-incarnation), the Lord is said to ç
have saved Manu (the progenitor of mankind) and the Saptar<218>is ç
(the seven sages, mind-born sons of Brahm<193>) along with their wives ç
during the deluge. The world was repopulated through them later on.
Lord Vi<218><207>u incarnated himself as theK<220>rma (the Tortoise) ç
in order to support the mount Mandara which started sinking during ç
the churning of the ocean(Samudramathana). The gods and the demons ç
had jointly undertaken this adventure to get Am<216>ta (nectar) from ç
the ocean.
Next in the series is the Var<193>h<193>va-t<193>ra (Boar-incarnation) ç
in which the Lord killed the demon Hira<207>y<193>k<218>a and lifted ç
the earth out of the flood waters in which it had been submerged. ç
This may be a symbolic representation of the extrication of the world ç
from the deluge of sin by the power of the Supreme Being.
When Prahl<193>da, the great devotee of Vi<218><207>u was being severely ç
tortured by his father, the demon Hira<207>yaka·ipu (who wasa non-believer ç
in the existence of an omnipresent and omnipotent God), Narasi<221>ha ç
(Man-lion) appeared, emerging out of the pillar shown by him and killed ç
him. Being a combination of man (the best of higher creatures) and ç
lion (the best of lower creatures) Narasi<221>ha represents thebest ç
of creation. Incidentally this also proves the omnipresence of God. ç
Narasi<221>ha is especially the embodiment of valour which is a divine ç
attribute andis hence worshipped by rulers and warriors. His mantra ç
is said to be very powerful, capable of destroying enemies and exorcising ç
evil.
When Bali the grandson of Prahl<193>da conquered the three worlds, ç
Indra was deprived of his heavenly kingdom. At the request of Aditi, ç
the mother of Indra, Lord Vi<218><207>u incarnated as V<193>mana (the ç
dwarf), a young br<193>hma<207>a boy, and approached Bali who was ç
known for his munificence, for a gift of land that could be covered ç
by three steps. With the first and the second he covered the earth ç
and heaven and with the third, he pushed down Bali to the netherworld. ç
Hence he is also known as Trivikrama, one who encompassed the world ç
with three big steps.
This myth teaches us that since even God had to resort to the dwarf's ç
form while begging, one who begs makes himself small! Secondly, a ç
true br<193>hma<207>a can conquer the three worlds by the power of ç
the spirit.
@SPACE1 = 
These  five  avat<193>ras  have  been referred to in the various sections ç
of theVedas.
The next five incarnations are in thehuman form.
Para·ur<193>ma (R<193>ma with the battle-axe) is the sixth avat<193>ra. ç
Born as the son of the sage-couple, Jamadagni and Re<207>uk<193>, ç
he exterminated the tyrannical among the k<218>attriyas led by K<193>rtav<200>rya, ç
who were oppressing the people. Whether this story has any historical ç
basis and represents the struggle for supremacy between the br<193>hma<207>as ç
and k<218>attriyas, it is difficult to say.
<185>r<200> R<193>ma, the next incarnation, meets Para·ur<193>ma and ç
absorbs his power into himself. Hence Para·ur<193>ma is sometimes ç
considered <193>ve·<193>vat<193>ra, an incarnation bythe temporary ç
possession of Vi<218><207>u's powers.
<185>r<200> R<193>ma, one of the two most popular incarnations of ç
the Lord Vi<218><207>u, comes next in the series. His story is too ç
well-known to need any repetition. He typifies the ideal man. His ç
story, the R<193>m<193>ya<207>a has now become an immortal epic. ç
His name is known as the `T<193>raka-mantra,' the mantra that takes ç
one across the ocean of transmigration.
@SPACE1 = 
Balar<193>ma, `R<193>ma the strong,' the elder brother of <185>r<200> ç
K<216><218><207>a, is the eighth incarnation. His many adventures ç
include the slaying of the ape Dvivida and the demon Dhenuka, shaking ç
the ramparts of Hastin<193>vati (the capital city of the Kauravas) ç
and dragging the river Yamun<193> out of its course. The story that ç
the serpent <185>e<218>a issued forth from his mouth at the time of ç
his death gives credence to the belief that he was the incarnation ç
of <185>e<218>a. Some scholars basing their conjecture on the weapon ç
of Balar<193>ma (the hala or plough), opine that he was an agricultural ç
hero raised to the status of an avat<193>ra in course of time.
<185>r<200> K<216><218><207>a, the ninth incarnation of Lord Vi<218><207>u ç
is, perhaps, the most popular, so much so, that he is considered p<220>r<207><193>vat<193>ra ç
(the incarnation in toto) and all other deities are regarded as ç
his manifestations. His story and his exploits are too numerous and ç
too well-known to be mentioned here. To the average Hindu, he is the ç
supreme statesman, warrior, hero, philosopher and teacher, nay, God ç
Himself. He is the great expounder of the `Song Celestial,' the Bhagavadg<200>t<193>.
The tenth Avat<193>ra Kalki, is yet to come. He will descend upon ç
the earth at the end of the present age (Kali Yuga). Riding on the ç
back of a white horse, with a drawn sword, he will destroy the enemies ç
of dharma and re-establish it in all its glory.
This list of the ten avat<193>ras of Lord Vi<218><207>u is by no means ç
the standard one accepted by all. Taking <185>r<200> K<216><218><207>a ç
as Vi<218><207>u himself, he is not included in some lists. His place ç
is taken over by Buddha. In some other lists, Buddha replaces Balar<193>ma. ç
Iconographically speaking, Buddha seems to have disappeared from such ç
lists only after the 15th century.
Strangely enough, the purpose of the Buddha-incarnation was supposed ç
to be to mislead men of low birth and genius, who had become too proficient ç
in the sacred lore and were a threat to the supremacy of the gods! ç
This looks more like a joke than a serious proposition. It is obvious ç
that the Hindus sealed the fate of Buddhism in this country by absorbing ç
Buddha into the pantheon of the avat<193>ras.
@SPACE1 = 
Ha<221>sa, S<193>tvata, Yaj<210>a, Datt<193>treya and Vedavy<193>sa ç
are some of the avat<193>ras included in other lists, keeping the ç
total as ten only. The number, however, rises sometimes to as high ç
as twenty-three.
@S8ITAL = CATURVY<188>HAS
The Bh<193>gavata or the P<193><210>car<193>tra religion, which preaches ç
the cult of Vi<218><207>u-N<193>r<193>ya<207>a, puts forth the theory ç
that the Supreme Lord Vi<218><207>u has four aspects of manifestation: ç
a) the Para or the supreme; b) the Vy<220>ha or the emanation; c) ç
the Vibhava or the incarnation and d) the Arca or icon.
Para is the Supreme as He is, in all His glory. Vibhava represents ç
the incarnations already dealt with. Arca is the descent of the Lord ç
into the icon ceremonially installed and worshipped in the temples.
The Vy<220>has or the emanations arefour in number. Hence the term ç
caturvy<220>has, also called caturm<220>rtis. They are: V<193>sudeva, ç
Sa<209>kar<218>a<207>a, Pradyumna and Aniruddha. According to Vai<218><207>ava ç
mythologies, while <185>r<200> K<216><218><207>a is V<193>sudeva, ç
his brother Balar<193>ma is Sa<209>kar<218>a<207>a. Pradyumna and ç
Aniruddha are K<216><218><207>a's son and grandson respectively. Historically ç
speaking, it is possible that these Y<193>dava heroes were, in course ç
of time, apotheosised into these Vy<220>has. Symbo-logically, V<193>sudeva ç
represents citta (mind-stuff), whereas Sa<209>kar<218>a<207>a stands ç
for aha<209>k<193>ra (egoity), Pradyumna for buddhi (intellect) and ç
Aniruddha for manas (mind). They represent the cosmic psychological ç
evolution.
@SPACE1 = 
Later  on,  these  Vy<220>has  were increased to as many as twenty-four. ç
Iconographically, all these Vy<220>has are identical in appearance ç
except for the arrangement of the four emblems† ·a<209>kha, cakra, ç
gad<193> and padma.
The P<193><210>car<193>tra theology often adds another aspect of the ç
manifestations, viz., the Antary<193>min (the indweller), which obviously ç
cannot be represented through icons.
@SPACE = 
@S8ITAL = MINOR INCARNATIONS
@SPACE = 
Hindu Mythology abounds in stories of Lord Vi<218><207>u's avat<193>ras, ç
which may be p<220>r<207><193>vat<193>ras (full manifestations) like ç
<185>r<200>K<216><218><207>a, a<221>·<193>vat<193>ras (partial manifestations)  like  Kapila  or  <193>ve·<193>var<193>ras ç
(temporary infilling of the divine power) like Para·ur<193>ma. A few ç
of these may now be dealt with.
@S8ITAL = Datt<193>treya
He was the son of the great sage Atri and his wife Anas<220>y<193>, ç
one of the paragons of chastity in Hindu mythology. He was the originator ç
of certain magical rites and the creator of the Soma plant. He was ç
a teacher of non-°ryan people. Association with people of low birth ç
and objects of pleasure has made him ritually impure. But, learning ç
and enlightenment have made him so pure that nothing can ever stain ç
him. Being the incarnation of the Trinity, he is shown as having three ç
heads, six hands and accompanied by four dogs of different colours ç
which represent the four Vedas.
The Datt<193>treya concept may be an attempt at harmonising the three ç
cults of Brahm<193>, Vi<218><207>u and <185>iva. It may also have ç
been the medium through which non-Vedic cults were brought into the ç
Hindu fold.
@S8ITAL = Dhanvantari
Dhanvantari rose from the ocean, at the time of churning, holding ç
the am<216>ta-kala·a (pot of ambrosia) in his hand. He is the originator ç
of medical sciences. Reborn as the king of K<193>·<200> he brought ç
medical science to the earth.
Vedas also mention a Dhanvantari, a god associated with herbs and ç
medicines.
He is described as a handsome person holding the pot of ambrosia and ç
seated in front of Vi<218><207>u's insignias.
@S8ITAL = Hayagr<200>va or Haya·<200>r<218>a
Y<193>j<210>avalkya, the great sage, lost the Yajurveda as a result ç
of his guru's curse and performed severe penance.
Sun-god, pleased by his penance, appeared before him as a deity with ç
the horse's head and taught him the same Veda in another form. This ç
section has come to be known as the V<193>jasaney<200> Sa<221>hit<193> ç
(v<193>ji = horse). The origins of the Hayagr<200>va avat<193>ra (the ç
deity with the horse's head) are perhaps found here.
Two demons Madhu and Kai<219>abha had stolen the Vedas and hidden ç
them under water. Lord Vi<218><207>u took the form of Hayagr<200>va, ç
dived to the bottom of the ocean and rescued them after killing the ç
demons.
Hayagr<200>va is the god of learning, akin to the goddess Sarasvat<200>.
He is shown in the human form, with the horse's head, possessing four ç
or eight arms, carrying the various weapons and emblems of Vi<218><207>u.
@S8ITAL = Kapila
Kapila, the son of Kardama and Devah<220>t<200> was a great sage who ç
reduced to ashes the sixty thousand sons of the king Sagara, just ç
by a glance. Probably this story is at the back of his being identified ç
sometimes with Agni. He taught S<193><207>khya philosophy to his mother.
Kapila icons usually have the hair dressed up as a crown (ja<219><193>-muku<219>a), ç
a beard, four arms, two of which are in yoga holding a pitcher and ç
the other two holding ·a<209>kha and cakra.
@S8ITAL = Mohin<200>
At the behest of the gods who had been deprived of the ambrosia by ç
the demons during the churning of the ocean, Lord Vi<218><207>u appeared ç
as Mohin<200>, the enchantress, who successfully duped the demons ç
and distributed the nectar among the gods. Even <185>iva is said to ç
have been bewitched by her beauty.
The story teaches us that immortality (am<216>tatva) can be gained ç
only by the conquest of delusion (moha).
Mohin<200> is shown as a beautiful young woman wearing colourful garments, ç
decorated with ornaments and carrying a vase of nectar in hand.
@S8ITAL = Nara-N<193>r<193>ya<207>a
After the purpose of Narasi<221>ha-avat<193>ra was accomplished, Narasi<221>ha ç
split himself into two, the lion part becoming the sage N<193>r<193>ya<207>a ç
and the human part the sage Nara. Nara and N<193>r<193>ya<207>a then ç
retired to Badarik<193>·rama for performing austerities. When Indra ç
tried to seduce them through celestial nymphs, N<193>raya<207>a produced ç
the nymph <188>rva·<200> from his thigh (<220>ru = thigh) who was ç
more beautiful than all of them put together.
According to another version, these sages were sons of Dharma and ç
Ahi<221>s<193>. They performed severe austerities and successfully   vanquished   the   ç
demon Sahasrakavaca (one who has a thousand armours).
These sages were reborn later as <185>r<200>K<216><218><207>a and ç
Arjuna.
This story has an important lesson for us. Everyone of us is a mixture ç
of the human and the divine elements. The anti-human and the anti-divine ç
demon is ever attempting to seduce us with his thousand wiles. To ç
successfully vanquish him, we need to perform tapas or austerity.
Nara-N<193>r<193>ya<207>a is represented either as a single person ç
or as two persons. In the former case the icon may have twoor four ç
arms carrying the japam<193>l<193> (rosary) or the usual emblems of ç
Lord Vi<218><207>u. Inthe latter case, Nara may be shown as having ç
two heads and two arms and wearing the deer skin. N<193>r<193>ya<207>a ç
is depicted with the usual four arms carrying the emblems ·a<209>kha, ç
cakra, padma and japam<193>l<193>.
@SPACE = 
@S8ITAL = Vy<193>sa
@SPACE = 
Vy<193>sa is a cosmic entity born in every age to propagate the scriptures.
The sage K<216><218><207>a-Dvaip<193>yana, the son of Par<193>·ara, ç
is the well-known Vy<193>sa of this age. He got that name since he ç
collected all the extant Vedic hymns and divided them (vyas = to divide) ç
into the four Vedas. He is the author of the great epic Mah<193>bh<193>rata ç
as also all the Pur<193><207>as (mythologies) and the Brahmas<220>tras.
In images, he is shown as of slender build, dark in complexion and ç
with the hair dressed up as a crown. His four disciples Paila, Vai·amp<193>yana, ç
Jaimini and Sumantu are also shown by his side.
@SPACE = 
@S8ITAL = Yaj<210>a
@SPACE = 
Vi<218><207>u has been identified with yaj<210>a or sacrifice in early ç
Vedic literature. The Bh<193>gavata calls Var<193>h<193>vat<193>ra ç
as Yaj<210>a-var<193>ha and identifies his limbs with thevarious ç
parts of a sacrifice. In other mythological  lore,  he  as  Yaj<210>e·a,  is ç
described as the son of Ruci and °k<220>ti. The entire universe which ç
is in a constant state of flux is like a sacrifice and the Lord responsible ç
for this creation is looked upon as the personification of that sacrifice. ç
Hence he is Yaj<210>a or Yaj<210>e·vara.
His image has two heads, seven hands, three legs and four horns. The ç
hands carry the sacrificial implements like <193>jyap<193>tra (vessel ç
holding the ghee) sruk, sruva and juh<220> (various kinds of spoons ç
and ladles), apart from ·a<209>kha and cakra.
Obviously this is a symbolical representation, the various limbs representing ç
the various items of the sacrifice. The description is rather too ç
technical to be dealt with in a small essay like this.
@SPACE = 
@S8ITAL = OTHER ASPECTS OF VI<186>ØU<R>ç
COMMONLY WORSHIPPED
@SPACE = 
Jagann<193>tha of Puri in Orissa is a Vai<218><207>ava deity which ç
draws huge crowds, especially during the annual car festival. The ç
image appears rather grotesque and is shaped out of a log and has ç
prominent eyes. Once in twelve years the log-image is renewed, the ç
log being brought every time mysteriously. The insertion of some ancient ç
relic into the new image sanctifies it. It represents <185>r<200> ç
K<216><218><207>a, with similar images  representing  Balar<193>ma  and ç
Subhadr<193> (K<216><218><207>a's sister).
P<193><207><195>ura<209>ga Vi<219><219>hala commonly known as Vi<219><219>hala ç
or Vi<219>hoba is the deity of the famous Vi<218><207>u temple at ç
Pandharpur in Maharashtra. In fact, the word `Vi<219><219>ha' is a ç
corrupted form of the word Vi<218><207>u. Rakum<193>b<193>i  (Rukmi<207><200>)  is  his  consort ç
standing by his left side.
This is the form of the Lord Vi<218><207>u revealed to a br<193>hma<207>a, ç
Pu<207><195>ali by name, because of his intense devotion to his parents.
Ra<209>gan<193>tha, along with Varadar<193>ja of K<193><210>c<200>puram ç
and Ve<209>ka<219>e·a of Tirupati, is the most popular aspect of Vi<218><207>u ç
worshipped in South India. The well-known temple at <185>r<200>ra<209>gam ç
in Tamil Nadu is the very heart of the <185>r<200>vai<218><207>ava ç
cult. This temple†at least the original icon†is said to have been ç
born out of the ocean and given by <185>r<200> R<193>ma to Vibh<200><218>a<207>a. ç
While carrying it from Ayodhy<193> to La<209>k<193>, Vibh<200><218>a<207>a ç
placed it on the ground at the present site, in order to rest a while. ç
Unfortunately for him (and fortunately for others!) it got firmly ç
fixed there!
The image is of the Yoga·ayana type (lying on the serpent-bed in Yoga) ç
with only two hands, the right hand apparently supporting the head ç
while the left rests on the serpent-bed.
The lotus with Brahm<193>, the °yudha-puru<218>as (the weapons in ç
human form), the demons Madhu and Kai<219>abha who were killed by ç
him, as also some sages like Bh<216>gu and M<193>rka<207><195>eya ç
are often depicted along with the Lord.
@SPACE1 = 
Similar Yoga·ayana images are found in Srirangapatna and Shivasamudram ç
of Karnataka  and  Tiruvanantapuram  of Kerala where it is known as ç
Padman<193>bha or Ananta·ayana.
Varadar<193>ja, the king among the bestowers of boons, is another ç
aspect of Lord Vi<218><207>u which is very popular. Also known as ç
Karivarada, it represents that aspect of the Lord responsible for ç
saving Gajendra, the elephant king, from the death-clutches of the ç
crocodile.
He is shown as riding on his vehicle Garu<195>a and in the act of ç
discharging the discus. The elephant Gajendra with its foot caught ç
by the powerful teeth of the crocodile is also shown. Sometimes a ç
human figure with its hands in obeisance is also shown near the crocodile, ç
to represent the Gandharva (a demigod) who had been delivered from ç
his curse which had resulted in his birth as a crocodile.
The temple of Varadar<193>ja at K<193><210>c<200>-puram in South India ç
is one of the most important and famous Vi<218><207>u temples.
Ve<209>ka<219>e·a, also known as Ve<209>ka-<219>e·vara, <185>r<200>niv<193>sa ç
or B<193>l<193>j<200> of Tirupati in Andhra Pradesh is perhaps the ç
most popular of all the Hindu deities in our country and the temple ç
on the Tirupati hills gets fabulous income. The word Ve<209>ga<195>am ç
of Tamil origin signifies a hill. So Ve<209>ka<219>e·a is the Lord ç
of the hill. The story goes that Lord Vi<218><207>u as Var<193>ha ç
(the Boar) decided to continue his stay on the earth and that Garu<195>a ç
brought down the hill of Vaiku<207><219>ha to earth for the Lord's ç
residence. Lord <185>r<200>niv<193>sa or Ve<209>ka<219>e·a, another ç
aspect of Vi<218><207>u, also manifested himself there at that time ç
to reside on the earth for the good of mankind.
@SPACE1 = 
The image is said to be an Udbhava-m<220>rti (spontaneously manifested) ç
and does not conform to known °gama traditions. As regards the exact ç
nature and form of the image, doubts exist, some opining thatit represents ç
Harihara, and others, considering it as Subrahma<207>ya or even Dev<200>.
@EMERGEN1 = Vi<218>vaksena or `the all-conquering' is an aspect of ç
Vi<218><207>u, which occupies the same place in Vai<218><207>ava tradition ç
as Ga<207>e·a in the <185>aiva tradition. He is worshipped  at  the  beginning  of  any ç
undertaking, to avoid obstacles. He is shown with four hands, wearing ç
·a<209>kha, cakra and gad<193> in three hands and thefourth exhibiting ç
the tarjan<200>mudr<193> (threatening finger pose). The right leg ç
is usually hanging down from the pedestal.
@EMERGENCY = Vi<218>vaksena is also depicted sometimes as the gate-keeper ç
or chief attendant of Lord Vi<218><207>u. He is shown standing on ç
a white lotus and with long matted hair as also a beard. He represents ç
the worldly sciences.
@S8ITAL = MINOR DEITIES ASSOCIATED WITH VI<186>ØU
@EMERGEN1 = Garutm<193>n or Garu<195>a, the mighty bird-vehicle of ç
Lord Vi<218><207>u is a minor deity invariably found in all the Vai<218><207>ava ç
temples. He is described as the son of thesage couple Ka·yapa and ç
Vinat<193> and as the younger brother of Aru<207>a, the charioteer ç
of Sun-god. The chief among his multifarious exploits is his bringing ç
of the pot of nectar from Indra's heaven. It is precisely this that ç
made Lord Vi<218><207>u choose him as his vehicle.
@EMERGEN1 = Literally, the word Garu<195>a means `wings of speech'. ç
He actually personifies Vedic knowledge. On his wings, as it were, ç
Vedic knowledge has come down to us, from the world of God.
The  Garu<195>a  image  is  usually anthropomorphic. He is shown with ç
a sharp beak, and two wings at the back. The hands may be eight or ç
four or just two. Two of the hands are always in the adoration pose. ç
In the others, he carries the conch, wheel, mace, sword, snake and ç
nectar pot. The image is usually installed right opposite the central ç
shrine.
It may appear to be rather intriguing that Lord Vi<218><207>u has ç
a serpent as his couch and an eagle, its arch enemy, as his vehicle! ç
This is to show that he is the Lord of balance and harmony which is ç
anessential quality for one charged with the responsibility of sustaining ç
this multi-farious universe.
Another deity invariably found in the Vi<218><207>u temples, especially ç
in the South, is Hanum<193>n the monkey-god. The R<193>m<193>ya<207>a ç
pictures him as a highly erudite, cultured and refined person. He ç
is as strong as he is wise, and as devoted as he is strong, a rare ç
combination indeed.
He is represented in two postures: When in the company of <185>r<200> ç
R<193>ma, S<200>t<193> and Lak<218>ma<207>a, he is shown standing ç
humbly at a distance or sitting devotedly at the feet of <185>r<200> ç
R<193>ma. In shrines specially erected for him, he strikes a heroic ç
pose, usually with the mace in his left hand and carrying the Sa<210>j<200>vin<200> ç
mountain in his right hand.
@SPACE1 = 
Apart from these, it is common to show the weapons of Lord Vi<218><207>u ç
also in human form. They are then called °yudha-puru<218>as (weapon-beings). ç
The °yudha-puru<218>a may be male, female, or neuter, depending upon ç
the gender of the word indicating it. For instance, Gad<193> (mace) ç
is a female deity whereas the Cakra (discus) is a neuter deity.
The Sudar·ana-cakra is shown as a person with a hexagon as his background, ç
brilliant as fire and having four or eight or sixteen arms holding ç
bow, arrow, trident, noose, goad and other weapons as also implements, ç
apart from the usual Vai<218><207>avite symbols. It is said to represent ç
the cosmic mind, the will of the Lord to multiply as well as his infinite ç
power to create and destroy the universe. The Sudar·ana-mantra is ç
said to possess the power to neutralise poisons and exorcise malignant ç
spirits.
The Kaumodak<200>, the gad<193> (mace) of Lord Vi<218><207>u is depicted ç
as a female deity, with one face and two hands which are in the posture ç
of adoration. It symbolises power and sovereignty.
No account of Lord Vi<218><207>u will be complete without mentioning ç
the <185><193>la-gr<193>ma (See <MS><185>°LAGR°MA.<D>), a blackish ç
rounded and polished stone with a hole containing the fossils of tiny ç
molluscs, which is worshipped as an emblem of His.There are several ç
varieties of them representing different aspects of the Lord. <185><193>lagr<193>mas ç
can be installed in temples but are usually worshipped in one's own ç
home privately. Once it is kept at home, its worship becomes obligatory.
@NT = vi<218><207>ubali
@N1 = (`offering to Vi<218><207>u')
This is a rite performed by the husband of a pregnant lady during ç
the eighth month. It should be done on the 2nd, 7th or the 12th day ç
of the bright fortnight when the moon is in the stars <185>r<193>va<207>a, ç
Rohi<207><200> or Pu<218>ya.
@SPACE1 = 
Its purpose is to remove all harm to the foetus and assure an easy ç
and safe delivery. It should be performed during every conception.
