@S10 = Dhruv<193>rundhat<200>-dar·ana
On the night of the marriage, the bride is shown†and she is expected ç
to see it†the pole-star (Dhruvanak<218>atra) and the star Arundhat<200> ç
in the group of the Seven Stars (Saptar<218>ima<207><195>ala or Ursa ç
Major). This is suggestive of being firm in conjugal life.
@S10 = Trir<193>travrata
The couple is expected to observe celibacy for three nights.
See <MS>CATURTH®KARMA<D> for details.
@S10 = Ma<209>galas<220>trabandhana
After the saptapad<200> the bridegroom ties the ma<209>galas<220>tra ç
round the neck of the bride. She should wear it always as long as ç
her husband is alive. See <MS>MA<177>GALAS<188>TRA<D> for details.
@S10 = Airi<207><200>d<193>na
When the bride is about to leave herfather's place for her husband's, ç
a bamboo-basket, full of presents and a lighted lamp, is given to ç
the mother of the bridegroom by the parents of the bride, with a request ç
to treat her with love and consideration.
@SPACE = 
@SB8.5 = Epilogue
@SPACE = 
It is interesting to note that the main framework of rituals of marriage ç
and the Vedic mantras employed have practically remained unchanged ç
over the last five thousand years.
The impact of modern education andcontacts with other†especially ç
the Western†cultures is bringing about vast changes in the Hindu society. ç
Several amendments to the Hindu laws wrought by the Acts of the Parliament ç
are also having  their  effects.  Late  marriages, divorces, remarriage ç
of widows and intercaste marriages are not uncommon though still not ç
very popular.
However, time and experience are showing†even upholding†that the basic ç
values behind the Hindu marriage system are sound and good. The Hindu ç
society can ill-afford to ignore them.
@SPACE = 
@NT = Vivara<207>aprameyasa<209>graha
@SPACE = 
The Advaita Ved<193>nta has been expounded by <185>a<209>kara (<MS>A.<|>D.<D> ç
788-820) in his bh<193><218>ya or commentary on the Brahma-s<220>tras ç
of B<193>dar<193>ya<207>a, especially in the first four s<220>tras. ç
Padmap<193>da (9th century <MS>A.<|>D.<D>), a direct disciple of <185>a<209>kara, ç
has written a commentary on it called Pa<210>ca-p<193>dik<193>. ç
This was further commented upon by Prak<193>·<193>tman (<MS>A.<|>D.<D> ç
1200), which he named as Pa<210>cap<193>dik<193> Vivara<207>a, starting ç
the Vivara<207>a school of Advaita as different from the Bh<193>mat<200> ç
school of V<193>caspati (<MS>A.D.<D>840).
The Vivara<207>aprameyasa<209>graha attri-buted to Vidy<193>ra<207>ya ç
(14th century <MS>A.<|>D.<D>) is a scholarly polemical work in prose ç
in nine var<207>akas or chapters. It tries to give a detailed exposition ç
of the various basic concepts of Advaita, especially avidy<193> (nescience), ç
according to the Vivara<207>a school.
The work is sometimes attributed to Bh<193>rat<200>t<200>rtha.
See also <MS>ADVAITA VED°NTA DAR<185>ANA<D>.
@SPACE = 
@NT = Vivara<207>aprasth<193>na
@SPACE = 
See <MS>ADVAITA VED°NTA DAR<185>ANA<D>.
@NT = vivartav<193>da
@N1 = (`the doctrine of apparent transformation')
The basic cause of an erroneous perception, as that of a snake in ç
rope, is called aj<210><193>na or avidy<193>. It has two powers: <193>vara<207>a·akti ç
(veiling power) and vik<218>epa·akti (transforming power). It veils ç
the real nature of the rope and apparently transforms it into a snake. ç
This apparently transformed object is called a `vivarta' of the original ç
and the theory that propounds it is known as vivartav<193>da.
See also <MS>KHY°TI.<D>
@NT = viveka
@N1 = (`discrimination')
This is the first of the four disciplines mentioned under s<193>dhanacatu<218><219>aya. ç
It means  discrimination  that  helps  an aspirant to distinguish ç
the real from the unreal, the eternal from the non-eternal. For instance, ç
the body is non-eternal (and hence unreal in essence) whereas the ç
<193>tman (the soul) is eternal and hence real.
@NT = Vivekac<220><195><193>ma<207>i
@N1 = (`crestjewel of<R>ç
discrimination')
This is one of the finest prakara<207>agranthas  or  elementary  treatises  of ç
Advaita Ved<193>nta by <185>a<209>kara (<MS>A. D.<D> 788-820). It ç
is in verses of various metres, the total number being 579. There ç
is a balanced  combination  of  philosophical acumen and literary ç
grace in this work.
It has only two commentaries: the older one by Ke·av<193>c<193>ryasv<193>min ç
of Munima<207><195>ala; the other by Candra·ekhara-bh<193>rat<200> ç
(<MS>A.<|>D.<D> 1892-1954), a former pontiff of the <185><193>rad<193>p<200><219>ha ç
of <185><216><209>ger<200>.
A very brief account of its contents may now be set forth here: importance ç
of attaining mukti or liberation; means of attaining it; place of ç
bhakti or devotion in the path of liberation; importance of self-effort; ç
liberation can be attained only by the knowledge of the identity of ç
j<200>v<193>tman (the individual soul) and Para-m<193>tman (the Supreme ç
Soul); m<193>y<193> and its two powers; nature of the <193>tman; means ç
of destroying the bondage of sa<221>s<193>ra ortransmigratory existence; ç
nature of Brahman, the Absolute; explanation of the mah<193>v<193>kya ç
tat-tvam-asi; fruit of <193>tma-j<210><193>na or realisation of ç
the <193>tman, the Self;characteristics of the j<200>vanmukta, theliberated ç
soul; on pr<193>rabdhakarma (karma that has started giving its results); ç
conclusion of the treatise.
See also <MS><185>A<177>KARA<D>.
@NT = vivekakhy<193>ti
@N1 = (`knowledge born out of <R>ç
viveka or discrimination')
See <MS>S°<177>KHYA-DAR<185>ANA<D>.
@SPACE = 
@NT = Vivek<193>nanda, Sv<193>mi
@SPACE1 = 
@SB8.5 = 1.	The Descent
@SPACE = 
An overwhelming number of human beings are just products of history. ç
But, once in a while, the world throws up from its bosom, such extraordinary ç
geniuses who create history. Nay, they are history, if we redefine ç
history as `his story'. It is the story of such men†the salt of the ç
earth†who shape the destinies of millions of human beings for millenniums, ç
that is real history!
R<193>mas and K<216><218><207>as of the most ancient period, Buddhas ç
and Christs of the remote past, were such epoch-making personalities. ç
To this list should be added R<193>mak<216><218><207>a and Vivek<193>nanda ç
of the recent past, the movement in whose names is gaining greater ç
and greater momentum.
As per one of the profound mystical visions of R<193>mak<216><218><207>a, ç
Vivek<193>nanda wasone of the Seven Great Sages who descended to ç
this earth out of his own free-will, to help mankind to rediscover ç
its inherent divinity.
The earthly advent of Narendran<193>th Datta†that was his premonastic ç
name† took place on the 12th January 1863 at Calcutta (now Kolkata). ç
His father Vi·va-n<193>tha Datta was an attorney. Bhuvane·var<200> ç
Dev<200>, his mother, was a highly cultured and pious lady.
Under their loving care, Narendra grew up into a fine boy.
@SPACE = 
@SB8.5 = 2.	Child Prodigy
@SPACE = 
Even in his early boyhood, Narendra exhibited many extraordinary traits ç
and talents indicating his future greatness. Exceptionally  brilliant  intelligence,  a ç
prodigious memory, a generous heart that felt for the poor and the ç
downtrodden, absolute fearlessness, utter contempt for superstitious ç
beliefs and a regal bearing were  conspicuous  in  him  by  their ç
compelling presence.
Though  he  would  often  neglect attending the school regularly due ç
to histremendous attraction for manly sports and voracious reading ç
habits, he would invariably pass the examinations creditably.
By the time he reached the collegefor higher studies, he had already ç
mastered many a difficult text of Western philosophy and logic.
@SB8.5 = 3.	The Restless Search
Delving into deep meditation†even from early boyhood days†was as natural ç
to him as a fish swimming in deep waters.
Though meditation had brought him some inner peace, the intellectual ç
restlessness brought about by an innate desire to know God†if He really ç
existed† andthe various metaphysical treatises (bordering on agnosticism ç
or even atheism) he had thoroughly gone through, increased to such ç
an extent that he started visiting any and every person considered ç
as or appearing to be a holy man or a man of God. Neither anyone of ç
them, nor even the well-known leaders of the Brahma Sam<193>j, could ç
whet his spiritual appetite by giving a direct and unambiguous, positive, ç
answer.
@SB8.5 = 4.	The Search Ends
R<193>mak<216><218><207>a (<MS>A.<|>D.<D> 1836-1886)†more well-known ç
as the Paramaha<221>sa†had already become a household name in Calcutta. ç
Though Narendra had heard about him (and had also seen him once in ç
the house of a devotee at Calcutta), he had not cared to go and meet ç
him, thinking that he was an unlettered rustic and hence it was not ç
worth seeing him. However, persuaded by R<193>macandra Datta (<MS>A.<|>D.<D> ç
1851-1899), a close relative (of Narendra) as also a disciple of R<193>mak<216><218><207>a, ç
he decided to go to Dak<218>i<207>e·var and meet the saint.
This  first  encounter,  wherein Narendra got a direct answer in the ç
affir- mative, for his (eternal) direct question† `Sir! Have you seen ç
God?'†not only thrilled him but also confused him. It confused  him  because  of  the  great ç
Master R<193>mak<216><218><207>a's strange behaviour of addressing ç
him as N<193>r<193>ya<207>a (Lord Vi<218><207>u), shedding tears profusely ç
and talking to him as if he had known him intimately for ages!
Whereas the Master was talking fromthe standpoint of his high mystical ç
experience, Narendra was too dumbfounded to understand it.
Thus the search for a true godman ended for Narendra.
@SB8.5 = 5.	The Struggle Begins
It is one thing to know that the godman  has  truly  realised  God  and ç
entirely another thing to be trained by him to get the same experience ç
oneself<|>!
The next five years were a period of intense training by the great ç
guru, of the great disciple.
While the former wanted to cast the latter in a supermould, to carry ç
on and continue his work even after he was gone, the latter fought ç
every inch of his way before accepting it, unless duly convinced.
The period of apprenticeship often appeared more like a battle between ç
equals than a training session. On one side was a well-educated strong ç
young man, equipped with a razor-sharp intellect, bolstered by a deep ç
knowledge of Western philosophy, science and logic. On the other side ç
was an uneducated br<193>hma<207>a priest from a backward village ç
of the 19th century Bengal, whose one and only asset was the constant ç
companionship of K<193>l<200>, the Divine Mother, whose very existence ç
was doubted, and the image detested, by the likes of Narendra.
Ultimately it was R<193>mak<216><218><207>a that triumphed in the ç
war though he seemed to lose some battles, the battles of wits. In ç
such cases, what he could not achieve through logic, he successfully ç
did by magic, by his magic touch, imparting instant experience of ç
the Divine.
Domestic tragedies like the sudden demise of his father and the consequent ç
penury of the family as also the desertion by his (so-called) friends, ç
made Narendra surrender himself totally at the feet of his guru, whose ç
love and faith had, all along, remained absolutely unshaken.
During this period, a direct, most wondrous, experience of Mother ç
K<193>l<200>, vouchsafed by the grace of the guru, put an end to all ç
the doubts and vacillations of  the  disciple.  His  conversion  or ç
transformation was now complete.
@SB8.5 = 6.	`Keep the Flock Together'
During R<193>mak<216><218><207>a's stay at the temple garden of Dak<218>i<207>e·var, ç
the Br<193>hmo Movement (started originally by R<193>j<193> R<193>mmohan ç
Roy) (<MS>A.<|>D.<D> 1772-1833) was at its zenith. It is a strange ç
irony that animportant leader of this protestant movement against ç
traditional or orthodox Hinduism†Ke·ab Candra Sen (<MS>A.<|>D.<D> 1838-1884)†became ç
instrumental in publicising the greatness of the Paramaha<221>sa of ç
Dak<218>i<207>e·var, thereby bringing the cream of `young Bengal' ç
(educated youth of Bengal) in great numbers to one who was the very ç
antithesis of all for which the Br<193>hmo Movement stood!
Quite a few of these young men became  his  ardent  disciples,  deeply ç
interested in totally dedicating themselves to spiritual pursuits, ç
by adopting the monastic life.
R<193>mak<216><218><207>a trained them so adroitly that each one of ç
them got not only general guidance but also the teachings parti- cularly ç
suited to him.
When he fell ill due to cancer of the throat in the middle of <MS>A.<|>D.<D> ç
1885 and later was completely bedridden, he was moved to a house, ç
first in <185>y<193>mpuk<220>r (Shyamapukur) and later, to a spacious ç
bungalow with an extensive garden in K<193>·<200>p<220>r (Cossipore).
It was here, that the great Master bound his young disciples†who were ç
serving him day and night by turns†into a well-knit body of future ç
monastics, with Narendra as their undisputed leader.
After imparting detailed instructions to the leader as to the continuation ç
of his work and commanding him to `keep the flock together,' the great ç
Master ascended to his heavenly abode on the 16th August 1886, the ç
day he himself had chosen to depart from this world.
@SB8.5 = 7.	The Broken House and the<R>ç
	Unbroken Spirit
As ordained by his Master, Narendra arranged to rent a house†a broken ç
and highly dilapidated one†at Bar<193>nagar (in Calcutta) for the ç
stay of all the young men chosen by him for the monastic life. This ç
was the first monastery of the Ramakrishna Order. In fact,†probably ç
in January 1886†the Master had distributed with his own hands, ochre ç
robes to twelve of these young men. They now formed the nucleus of ç
the Ramakrishna Order of monks.
Under the leadership of Narendra, all of them formally embraced monastic ç
life with proper vows and new monastic names. Narendra is supposed ç
to have adopted the new name Vividi<218><193>nanda though he would ç
sometimes change it to Saccid<193>nanda during his itinerant days ç
so as not to be found out by his brother disciples. However, he later ç
on assumed the name Vivek<193>nanda permanently.
Though these young monks had to live in a god-forsaken place infested ç
withpoisonous reptiles outside and a ramshackle roof on their heads, ç
their spirit was unbroken and the determination to realise the goal ç
of their life, adamantine.
Spurred by the age-old urge of sa<221>ny<193>sins to lead a wandering ç
life, depending entirely on God, the young recluses left the monastery ç
one by one. Only <185>a·i (R<193>mak<216><218><207><193>nanda) stayed ç
put, to take care of the relics of his Master housed in this monastery ç
and care for the other brothers who stayed back.
Vivek<193>nanda was no exception to this `mad' urge. After a few short ç
sojourns here and there, he left the Math as an itinerant monk, this ç
time to closely observe and study India in all her aspects.
@SPACE = 
@SB8.5 = 8.	Unknown Expedition for a<R>ç
	Known Destination
@SPACE = 
Apparently, Vivek<193>nanda's expedition was into the unknown or the ç
little-known facts of India†its land, its people, its religion and ç
culture, its hopes and aspirations, its glories and mistakes, its ç
miseries and sufferings; in short, India in its totality, at first-hand.
This was absolutely necessary for him to know†even as a doctor had ç
to know all about his patient before prescribing his remedies†since ç
he had been specially ordained by his Master to work vigorously for ç
the uplift of his motherland.
Thus it was that, though his expedition was into the unknown, his ç
destination or the final goal was clearly known.
Vivek<193>nanda's experiences as an itinerant monk were as diverse ç
as they were direct too. He could see India's people and their life ç
at close quarters†now in the palaces of the kings or the mansions ç
of the rich, and, the next day sleeping in the cottages of the poor ç
who could hardly manage a square meal per day, or with their animals ç
in the sheds. Vivek<193>nanda could realise how poverty, ignorance ç
and squalour were everywhere, and how the common masses who had been ç
oppressed and exploited for ages, had become next-door neighbours ç
to brutes.
However, to his pleasant surprise, he discovered that the true spirit ç
of religion (as he called it) was still very much present in the Indian ç
blood. He realised that religion was the backbone of India and that ç
she could rise (or had to be raised) only through that.
@SPACE1 = 
After visiting the Him<193>layan shrines, travelling through the fertile ç
Indo-Gangetic plains, meandering through the R<193>jasth<193>n deserts ç
in scorching sun and the Deccan plateau, he finally landed in the ç
Kany<193>kum<193>r<200> temple-town (known as Cape Comorin then).
Offering his obeisance first in the shrine he went to the sea-shore ç
where the Indian Ocean absorbs into its bosom, theBay of Bengal and ç
the Arabian Sea. Seeing two rocks in the ocean at a short distance ç
and unable to withstand the temptation of their call as it were, he ç
swam to the bigger one and sat there in a restful state, gradually ç
souring into deep meditation.
@SB8.5 = 9.	Future Revealed
@EMERGENCY = By now he had seen enough of India at first-hand. He ç
had intuited its glorious past. He had observed its present degradation. ç
He had discovered its causes and also devised the solutions. The only ç
thing that had to be done now was their implementation.
Earlier, during his travels through Gujarat and Madras City (now Chennai), ç
some friends and devotees had suggested, nay, had even pressurised ç
him, that he should go to America and attend the Parliament of Religions. ç
Though he was receptive to the idea, he was not sure whether it had ç
his Master's approval. His own vision of R<193>mak<216><218><207>a ç
walking over the sea towards the west and beckoning him to follow, ç
as also a similar one vouchsafed to <185>r<200> S<193>rad<193>dev<200> ç
(<MS>A.<|>D.<D> 1853-1920), the divine consort of the Master, removed ç
all doubts from his mind.
His plan of action was now clear and vivid in his mind. He would go ç
to America, earn money by the power of his brains, return to India ç
and build an organisation of monks to serve the poor and the downtrodden. ç
Through the twin ideals of renunciation and service to mankind, he ç
would attempt to raise India not only to its past glory but even beyond ç
that!
Spurred and enthused by this vision, and with an unshakable faith ç
in his guru, he returned to Madras. After visiting Khetri in Rajasthan ç
whose king was his disciple, he set sail for America from Bombay (now ç
Mumbai) on the 31st May 1893.
His disciples at Madras as also the Mah<193>r<193>j<193> of Khetri ç
provided him with the necessary money and baggage.
Travelling via Ceylon (now Sri Lanka), China and Japan, he finally ç
reached Chicago on the 30th July, where the Parliament of Religions ç
was scheduled to be held.
However, he was shocked to learn that the Parliament was still three ç
months away.
With help coming from the most unexpected quarters, he shifted to ç
Boston †since  it  was  less  expensive†and returned to Chicago on ç
time to attend the Parliament as an official delegate of Hinduism ç
from India.
@SPACE = 
@SB8.5 = 10.	The East Storms the West
@SPACE = 
The Parliament of Religions was held from the 11th to the 27th of ç
September 1893 in the Hall of Columbus, as a part of the World's Columbian ç
Exposition.
On the inaugural day, Vivek<193>nanda, who had been seated on the ç
vast dais along with a host of delegates from different parts of the ç
world, representing various religions, was a little awed at the great ç
crowd and the august occasion.
However, when he rose to speak, almost towards the end of the day, ç
remembering Mother Sarasvat<200>, the goddess of learning, he was ç
a totally transfigured person. The very first words he uttered, a ç
short address of just five words†`Sisters and Brothers of America!' ç
electrified the audience, a huge mass of humanity, into a thunderous ç
clapping session lasting for over two minutes!
Obviously, the East had stormed the citadel of the West in a matter ç
of a few seconds!
It was a short talk, but scintillating with the spirit of universality, ç
perfectly in tune with the ethos of the Parliament. It stressed the ç
universal spiritual truththat all paths, whether crooked or straight, ç
would ultimately lead to the sameGodhead.
In an instant, the simple monk with a begging bowl, had become the ç
man of the hour, the uncrowned king of countless admirers.
@SB8.5 = 11.	Hectic Tours to Transmit Tranquillity
The Master had wanted him to become like a huge banyan tree giving ç
shelter to thousands in its protective shade, rather than be a recluse ç
interested only in his own liberation. The time for it had arrived ç
now.
During the period September 1893 to August 1895, Vivek<193>nanda had ç
a hectic time visiting places, giving lectures and parlour talks, ç
granting personal interviews, taking classes for earnest students ç
of Ved<193>nta, addressing the gathering at well-known universities ç
as also exchange ideas with the best brains of America like Prof. ç
William James (<MS>A.<|>D.<D> 1842-1910), Prof. J. H. Wright, Robert ç
Ingersoll (<MS>A.<|>D.<D> 1833-1899) and others.
It was during this time (June 1895) that he delivered his now famous ç
Inspired Talks to a small but serious group of twelve disciples ç
at Miss Dutcher's cottage in the Thousand Island Park.
As a result of his tireless efforts through such teaching and preaching, ç
the Americans were able to understand and appreciate Hinduism better, ç
thereby abandoning many a misconception, dispelled by his forceful ç
expositions.
His unexpected presence and the spectacular success in America often ç
ledto persecution and even character assassination, by certain Christian ç
zealots as well as some of his own jealous countrymen. However, the ç
vigorous defence put up by his western disciples silenced them.
He visited England also during the period September 1895 up to April ç
1896. Here too his success was remarkable. And,what is more, he made ç
a few excellent disciples like Mr. and Mrs. Sevier, J. J. Goodwin ç
(<MS>A.<|>D.<D> 1870-1898) andMiss Margaret Noble (Sister Nivedit<193>) ç
(<MS>A.<|>D.<D> 1867-1911).
He also had the opportunity of meeting Prof. Max Muller (at Oxford ç
in England) (<MS>A.<|>D.<D> 1823-1900) and Prof. Deussen (at Kiel in ç
Germany) (<MS>A.<|>D.<D> 1845-1919).
@SB8.5 = 12.	Back to the Motherland
After laying a firm foundation for his work in America and England, ç
and placing his brother disciples, Sv<193>mis S<193>rad<193>nanda ç
(<MS>A.<|>D. <D>1865-1927) and Abhed<193>nanda (<MS>A.<|>D.<D><|>1866-1939) ç
in charge of the work, Vivek<193>nanda returned to India, along with ç
Mr.<|>and Mrs. Sevier as also J. J. Goodwin, via Ceylon. He arrived ç
at Colombo on the 15th January 1897 to a tumultous welcome by a sea ç
of humanity.
Then, travelling through the various cities and towns of the Madras ç
Presidency (now Tamil Nadu) he arrived in Madras.
Here he delivered about six lectures to mammoth audiences†which the ç
city had never witnessed earlier†each scintillating with the power ç
and the pride of Indian nationalism.
After acceding to the request of the local devotees and admirers to ç
start a centre of his work at Madras, he sailed to Calcutta, his hometown, ç
reaching there on the 19th February 1897.
The city of Calcutta gave a fitting reception to the Son of the Soil.
During his long absence, the Math had been shifted from Bar<193>nagar ç
to Alambazar in 1892 and later, to the garden house of N<200>l<193>mbar ç
Mukherj<200> in 1897.
@SB8.5 = 13.	Sleeping Giant Awakened
Now began another hectic period in Vivek<193>nanda's life.
His talks in America were aimed at vigorously propagating true Hinduism ç
through Ved<193>nta, and removing all the misconceptions about it, ç
deliberately spread by the mischievous and bigoted propaganda of the ç
Christian missionaries.
India however, needed an entirely different approach and treatment.
So, he now started on another lecture expedition†which he had begun ç
at Colombo itself†singularly aimed at rousing the Indian nation by ç
demolishing its superstitions†the accretions over several centuries†total ç
lack of self-confidence and the mania of blindly imitating the West. ç
He reminded his audiences of their past glory and greatness, castigated ç
them for their `kitchen and the cooking-pot religion' of exclusivity, ç
their oppression of the lower castes and groups as also keeping their ç
women in ignorance by denying them education.
These lectures, now famous as the Lectures from Colombo to Almora ç
are the modern Veda he has bequeathed to Modern India.
The result was a galvanisation of the Indian morale and a great fillip ç
to the movement for political freedom, whose leaders derived great ç
inspiration from him.
@SB8.5 = 14.	Mission Accomplished
For several years, Vivek<193>nanda had been cherishing a great desire ç
in his heart, an intense yearning, to establish the urn containing ç
the relics of his great Master and mentor, in a permanent place and ç
build a monastery round it. This monastery, wherein will live the ç
Master's disciples and their disciples, thus forming a new monastic ç
tradition and Order, will give a practical shape to his command to ç
rejuvenate Hinduism as also rebuild the motherland.
When he sent Sv<193>mi R<193>mak<216><218><207><193>-nanda (<MS>A.<|>D.<D> ç
1863-1911) to Madras, to start a Math there to continue his work, ç
he had already made a beginning in this direction.
On the 1st May 1897, he called a meeting of all the monastic and lay ç
disciples of the great Master R<193>mak<216><218><207>a in the house ç
of Balar<193>m Bose (<MS>A.<|>D.<D> 1842-1890) and formed the organisation ç
`Ramakrishna Mission Association'.
Later, he purchased a plot of land on the western bank of the river ç
Ga<209>g<193> and built a monastery with a shrine there.
He himself carried the urn containing the relics of R<193>mak<216><218><207>a, ç
established it there and performed the consecration ceremony with ç
all the attendant rituals. This was on the 9th December 1898.
This Math has now become well-known as the Belur Math and houses the ç
Headquarters of the Ramakrishna Order.
Having thus accomplished a great mission he had cherished for long, ç
he could now rest in peace.
Meanwhile, a good number of young men had joined the monastic order ç
established by him. His own brother disciples† the monastic disciples ç
of R<193>mak<216><218><207>a†too were living there. Hence Vivek<193>nanda ç
turned his attention now to the training of these young novices, with ç
their help.
@SB8.5 = 15.	Pilgrimages and Tours
Vivek<193>nanda found some time to go on a few pilgrimages, the notable ç
places being Amarn<193>th and K<218><200>rbhav<193>n<200>, both in ç
Kashmir.
In both the places he observed diligently all the ceremonials and ç
rituals prescribed for ordinary pilgrims as if to set an example to ç
them.
He seems to have had some profound spiritual   experiences   during   these ç
pilgrimages.
He now decided to go to the West a second time, more to see how the ç
work there was progressing. Accompanied by Sv<193>mi Tur<200>y<193>nanda ç
(<MS>A.<|>D.<D> 1863-1922) and Sister Nivedit<193>, he first visited ç
England for two weeks (in July 1899) and later went to America in ç
August. He was happy to see how Sv<193>mi Abhed<193>nanda had established ç
the Ved<193>nta work on a firm foundation. He left Sv<193>mi Tur<200>y<193>nanda ç
on the west-coast at San Antone Valley, to establish a Retreat Centre ç
(now known as the <185><193>nti °·rama). After attending the Parliament ç
of History of Religions in Parisand spending about three months there ç
he returned to Calcutta on the 9th December 1900.
@SB8.5 = 16.	The Ascent
R<193>mak<216><218><207>a had predicted two things about his `Naren' ç
(Vivek<193>nanda): That he would not reach his 40th year of his life; ç
and that, the moment he discovered who he was, he would voluntarily ç
cast off the physical body.
A few days before his passing away, he confided to one of his brother-disciples, ç
in answer to a question inadvertently put to him, that he now knew ç
who he was.
Three days before his final departure from this world, he instructed ç
Sv<193>mi Prem<193>nanda where to cremate his body!
He had even fixed the date as itwere, after scrutinising the Be<209>g<193>l<200> ç
almanac, a week earlier.
On the last day of his life†the 4th of July 1902†he rose from his ç
bed very early, meditated in the shrine room (after closing all the ç
doors and the windows) for an unusually long time, took a class on ç
Sanskrit grammar for the brahmac<193>rins (tyros under training) for ç
three hours, had a long stroll in the evening and then retired to ç
his room at the time of vesper service in the shrine.
After meditating for some time he lay down on the bed, spread on the ç
floor and quietly breathed his last at 9 <MS>P.M.<D>
It was noticed that the eyes were bloodshot and a little blood had ç
oozed through the nostrils and the mouth, indicating the departure ç
of life through the brahmarandhra (the aperture in the crown of the ç
head).
The body was cremated at the very spot he had indicated. A magnificent ç
memorial temple stands on that spot now, beckoning all to come to ç
him and be inspired.
@SB8.5 = 17.	Character and Personality
A sound mind in a sound body, fully reflecting a spirit that is always ç
sound† this is how Vivek<193>nanda's person and personality can be ç
described.
Physically, he was well-built and handsome. Gymnastics, games, swimming ç
and wrestling were his favourite pastimes during early youth.
Intellectually, he was a giant. Photo-graphic memory and a razor-sharp ç
intellect helped him to master any subject in no time. By just glancing ç
through a book he could not only reveal its contents but also often ç
quote it verbatim.
Oratory was his special and most natural gift. When he spoke, tremendous ç
power would appear to be emanating from him, transporting his audience ç
to a plane where they would be listening to a voice from the void ç
as it were.
He was an expert musician too. Endowed with a rich and melodious voice, ç
cultured by years of training in classical music, his singing, especially ç
of devotional songs and hymns, could enthrall even the most prosaic ç
hearts. He was also good at playing many a musical instrument.
Though most of his literary works are records of his inspiring†and ç
extempore†talks, he has left us a few written compositions in Sanskrit, ç
Be<209>g<193>l<200> and English, like hymns, poems and thoughtful ç
essays. It is now acknowledged that he was a pioneer in the creation ç
of a new style of Be<209>g<193>l<200> prose.
His great poem†The Song of the Sa<221>ny<193>sin†reverberating with ç
the fiery feeling of a monk's inner stuff and psyche, is a masterpiece ç
of English literature soaked in the Eastern spirit.
@SPACE1 = 
His power of meditation was astounding. (Even from the childhood days, ç
he could sit still in meditation like a statue, for a long time.) ç
R<193>mak<216><218><207>a had declared that he was a dhy<193>nasiddha, ç
a sage perfected in meditation and had descended to the earth from ç
the region of the Saptar<218>is, the Seven Sages of Hindu mythology.
In spite of the majestic external appearance, striking awe in the ç
minds of the onlookers, he possessed a heart that was simple like ç
that of a child and yet infinitely tender towards the sufferings of ç
others.
In short, he personified in himself the perfect man†with <185>a<209>kara's ç
intellect and the Buddha's heart†that he wanted everyone to become, ç
in life.
@SB8.5 = 18.	The Philosophy of Vivek<193>nanda
Vivek<193>nanda has given his philo- sophy of life succinctly in two ç
places. At the beginning of his remarkable treatise R<193>jayoga ç
he has given the following aphoristic maxims which can be called theCatuss<220>tr<200> ç
(Four Aphorisms) of Neo-ved<193>nta:
@NO = a)
@NOK = Each soul is potentially Divine.
@NO = b)
@NOK = The goal is to manifest this Divine within by controlling Nature, ç
external and internal.
@NO = c)
@NOK = Do this either by work, or worship, or psychic control, or ç
by philosophy, by one, or more, or all of these†and be free!
@NO = d)
@NOK = This  is  the  whole  of  religion. Doctrines or dogmas, or ç
rituals, or books, or temples, or forms, are but secondary details.
In addition, he has also given the motto of the Ramakrishna Order ç
as:
@P = <+>`<193>tmano mok<218><193>rtha<221> jagaddhit<193>ya ca,'
`One should work for the liberation of oneself as also for the good ç
of the world'.
These two together can be considered as the Philosophy of Vivek<193>nanda. ç
They are potentially capable of being expanded into full-fledged theories ç
or even theses.
@SB8.5 = 19.	His Special Contribution
The special contribution of Vivek<193>-nanda to the world in general ç
and to India in particular may be listed as follows:
@NO = i)
@NOK = By creating the Ramakrishna Math and the Ramakrishna Mission, ç
he not only rejuvenated but also recast Hindu monasticism into a new ç
mould, more relevant to the times.
@NO = ii)
@NOK = He laid the foundation for and gave the right direction to ç
the Indian independence movement, most of whose leaders were inspired ç
by his speeches and writings.
@NO = iii)
@NOK = He restored the national self-respect of the Indians by re-educating ç
them in their past glory, advised them against blindly imitating the ç
West, but also exhorted them to learn the best from it, in which we ç
have been deficient.
@NO = iv)
@NOK = He castigated the classes for their neglect, or even oppression, ç
of the masses and inspired them to work for the latter's upliftment.
@NO = v)
@NOK = He  effectively  pointed  out  that religion†in the sense of ç
spiritual evolution†is the soul of India and that all developments ç
or reformations should be done only through that.
@NO = vi)
@NOK = He laid great stress on material development of the country ç
also, sincereligion is not to be imposed upon empty stomachs. It ç
was his humanism and not materialism that made him advocate this. ç
He always felt that poverty and ignorance were dampers to spiritual ç
progress and not its necessary conditions!
@SPACE1 = 
@SPACE1 = 
@NO = vii)
@NOK = He disentangled Ved<193>nta from its traditional Hindu setting ç
and the stranglehold of the pundits, and, taught it as a universal ç
religion applicable to the whole of mankind. In this sense he was ç
a true teacher of the whole world.
@SPACE1 = 
@SPACE1 = 
@NO = viii)
@NOK = Though he has generally followed <185>a<209>kara's Advaita ç
in his discourses on Hinduism and Ved<193>nta, he has made some original ç
contributions too. The following points may specially be noted:
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@NO = 
@NOK = a)
@NK = The Vedas are not particular books but represent the eternal ç
laws of the spiritual world, even as science represents the scientific ç
laws of the material world.
@NO = 
@NOK = b)
@NK = The three systems of Ved<193>nta†Advaita, Vi·i<218><219><193>dvaita ç
and Dvaita†are not mutually conflicting. They give out the same Truth ç
from different (and complementary) standpoints like the photographs ç
of the same sun taken from different distances and angles.
@NO = 
@NOK = c)
@NK = The Supreme Being is Personal-Impersonal. The latter is not ç
a negation but a fulfilment of the former.
@NO = 
@NOK = d)
@NK = Anthropomorphism cannot be avoided in any human conception of ç
God.
@NO = 
@NOK = e)
@NK = He considers m<193>y<193> as not a theory, but a statement of ç
fact. What is important is to transcend it and realise that which ç
is beyond it.
Thus he has made Ved<193>nta practical, by stressing the s<193>dhana ç
aspects like non- attachment and yearning for the truth.
@SPACE = 
@SB8.5 = 20.	Epilogue
@SPACE1 = 
Perhaps, it is best to conclude with the well-known saying of another ç
famous modern Indian leader who had the good fortune as a young man, ç
of pulling the carriage in which Vivek<193>nanda had been seated when ç
he was received at Madras:
`Swami Vivekananda saved Hinduism and saved India. But for him, we ç
would have lost our religion and would not have gained our freedom. ç
We therefore owe everything to Swami Vivekananda.'
@R = C. Rajagopalachari (<MS>A.<|>D.<D> 1878-1972).
@SPACE = 
@NT = vratas and utsavas
@N1-1 = (`religious vows and celebrations')
@SPACE = 
The word `vrata' (`religious vow') is one of the most widely used ç
words in the Hindu religious and ritualistic literature. Derived from ç
the verbal root v<216><210> (`to choose'), it indicates a set of ç
rules and discipline with which one voluntarily binds oneself over ç
a particular period of time, during which period he undertakes the ç
performance of certain rituals in order topropitiate the deity and ç
secure from itwhat he wants. This whole process, however, should ç
be undertaken with a sa<209>kalpa or religious resolve, on an auspicious ç
day and time, fixed as per the dictates of the Hindu religious almanacs.
