@SB8.5 = Conclusion
Though the Vaikh<193>nasa °gamas give primary importance to arc<193> ç
or m<220>rtip<220>j<193>, to the images of gods, their consorts andattendant ç
deities, the outlook is, in essence, idealistic. It holds that Godhead ç
is sarv<193>dh<193>ra (support of all), san<193>tana (ancient and ç
eternal), aprameya (inscrutable), acintya (indefinable), nirgu<207>a ç
(without attributes) and ni<218>kala (without parts). It is all-pervading ç
even as butter in milk, oil in oil seeds or fire in firewood.
However, even as fire blazes forth by friction of the ara<207>i sticks, ç
Vi<218><207>u appears in the heart of the devotee by dhy<193>na-mathana ç
(churning due to meditation) or constant meditation. This is the `sakala' ç
form, the Absolute materialising itself due to the devotion and visualisation ç
of the devotee.
Even then, worshipping an icon, properly prepared, and as per the ç
rules given in the treatises, is extremely important. That itself ç
can, ultimately, lead to salvation.
This seems to be the sine qua non of the Vaikh<193>nasa °gamas.
@NT = Vaikhar<200>
See under <MS>TANTRAS<D>.
@NT = Vaiku<207><219>ha
@N1 = (`that which is without [or beyond] destruction')
This word is used as one of the names of Vi<218><207>u and also of ç
his abode or world.
Vi<218><207>u is called Vaiku<207><219>ha since heis:
1.
@NK = without or beyond destruction;
2.
@NK = the ruler of j<200>vas (individual selves);
3.
@NK = the giver of knowledge.
Vaiku<207><219>ha is more well-known in the epics and pur<193><207>as ç
as the abode or world of Vi<218><207>u. This world is of infinite ç
dimensions. The liberated souls, live there having a similar form ç
as the Lord Vi<218><207>u. It is full of unimaginable wealth and splendour. ç
Great beings like Brahm<193>, sages like Sanaka and other perfected ç
beings live there in eternal bliss under the loving care of Vi<218><207>u ç
and Lak<218>m<200>, serving them with deep devotion. (vide Bh<193>gavata ç
3.15.14-25).
@NT = vair<193>g<200>s
@N1 = (`persons of renunciation')
Vair<193>g<200>s or bair<193>g<200>s are religious ascetics of any ç
of the Vai<218><207>ava orders. They wear white clothes and apply ç
<220>rdhva-pu<207><195>ra (vertical religious mark) on their foreheads, ç
made of white clay and red pigment. They generally wear their hair ç
as a crown and may also grow beard.
There are several sects and subsects among them.
@NT = vair<193>gya
@N1 = (`absence of attachment')
Vair<193>gya or absence of attachment or renunciation is the second ç
of the four s<193>dhanas listed under `s<193>dhanacatu<218><219>aya'. ç
It is a natural consequence of viveka or discrimination. It pertains ç
to all objects of pleasure, whether of this world or of the next.
The highest state of vair<193>gya is that in which the mind is absolutely ç
undisturbed even though an object of temptation is near at hand and ç
can easily be enjoyed (vide Yogas<220>tras 1.15).
@NT = Vairamu<195>i
@N1 = (`crown of diamonds')
The consecrated images of gods in Hindu temples†whether firmly secured ç
inside the sanctum or used as utsava-m<220>rtis (processional images)†are ç
treated with great respect. It is the strong belief of the devoted ç
Hindus that god lives in them in a subtle form. Consequently even ç
the utsavam<220>rtis, especially on important festival days, get the ç
same worship and treatment as the original icon inside the shrine.
There can be no better example for this than the utsavam<220>rti of ç
Celuva-n<193>r<193>ya<207>asv<193>min in his temple at Melko<219>e ç
which is situated at a distance of 36 kms. (22 miles) from Mandya, ç
the district headquarters, in the Karnataka State.
The brahmotsava†the biggest festival of the year†of this temple is ç
generally held during March. The most important day during this period ç
is the Vairamu<195>i utsava, the festival of the Vairamu<195>i. On ç
this day the utsavam<220>rti is decorated with the Vairamu<195>i, ç
the ancient crown of diamonds of unknown origin, and taken round the ç
town in a procession.
According to the sthalapur<193><207>a or the local legends it was ç
originally the crown of Lord N<193>r<193>ya<207>a. Once the demon ç
king Virocana stole it and ran away. However, Garu<195>a, the eagle-mount ç
of the Lord, recovered it after defeating the demon. When he was returning, ç
he saw K<216><218><207>a and offered it to him, realising that he ç
was the incarnation of N<193>r<193>ya<207>a himself. K<216><218><207>a ç
asked him to put it on the head of the image of Celuvan<193>r<193>ya<207>asv<193>min ç
at Melko<219>e. Since it perfectly fitted the image, Garu<195>a returned ç
happily, leaving it there.
@SPACE1 = 
This crown is kept safely in the district treasury at Mandya. On the ç
day of the festival, the casket containing it is brought, under heavy ç
police protection, to Melko<219>e, receiving worship on the way in ç
several places. At the entrance of the town, the casket is transferred ç
to a decorated palanquin and carried to the temple.
Since, as per tradition, it is not to be exposed to sunlight, it is ç
worn on the head of the utsavam<220>rti by the chief priest at night, ç
around 9 p.m. Then the image is taken round the main streets in a ç
procession by placing it on a v<193>hana (vehicle) shaped like the ç
k<218><200>r<193>bdhi or the milky ocean. It returns to the temple ç
before sunrise (around 4 a.m.). The Vaira-mu<195>i is then transferred ç
to the casket and sent back to the treasury.
This festival is the most spectacular of all and is witnessed by lakhs ç
of devotees.
@NT = Vai·amp<193>yana
He was one of the four chief disciples of Vy<193>sa to whom the Yajurveda ç
had been taught. The sage Y<193>j<210>navalkya was his nephew and ç
disciple who later left him.
He taught the Mah<193>bh<193>rata to Janamejaya (vide °diparva ç
Ch. 125).
@NT = Vai·e<218>ika Dar·ana
@SB8.5 = Introduction
The Vai·e<218>ika Dar·ana was founded by Ka<207><193>da, also known ç
as Ul<220>ka. Hence it is also called K<193><207><193>da or Aul<220>kya ç
Dar·ana. Ka<207><193>da seems to be a nickname of Ul<220>ka since ç
he led the life of an ascetic. He used to live on ka<207>as or grains ç
gleaned from agricultural fields (ka<207>a = grain; ad=to eat).
The basic text is the Vai·e<218>ika S<220>tras of Ka<207><193>da. ç
It is divided into ten adhy<193>yas or chapters, each adhy<193>ya ç
containing two <193>hnikas or sections. It has 374 s<220>tras in all.
The earliest exposition of this work seems to be the Pad<193>rtha-dharma-sa<209>graha ç
of Pra·astap<193>da (5th century <MS>A.D.<D>). Though known as Bh<193><218>ya, ç
it is not a regular s<220>tra-by-s<220>tra commentary on the original ç
work. This Bh<193><218>ya, while restating the principles contained ç
in the original s<220>tras, develops them considerably. The Ny<193>yakandal<200> ç
of <185>r<200>dhara (991 <MS>A.D.<D>), Vyomavat<200> of Vyoma·iva ç
and Kira<207><193>-val<200> of Udayana (<MS>A.D.<D>984) are the ç
well-known commentaries of Pra·astap<193>da. Vallabh<193>c<193>rya's ç
(11th cent. <MS>A.<|>D.<D>) Ny<193>ya-l<200>l<193>vat<200> and Udayana's ç
Lak<218>a<207><193>val<200> are two valuable compendiums on this ç
system.
The Vai·e<218>ika system became closely associated with the Ny<193>ya ç
system in course of time, so much so, that the later writers started ç
dealing with them as if they were one system. Of these, mention must ç
be made of the Saptapad<193>rth<200> of <185>iv<193>ditya (10th ç
cent. <MS>A.D.<D>) and the Bh<193><218><193>-pariccheda of Vi·van<193>tha ç
(<MS>A.D.<D> 1650) with his own commentary, Siddh<193>ntamukt<193>val<200>.
@SB8.5 = The Seven Pad<193>rthas
The Vai·e<218>ika school of philosophy recognises seven pad<193>rthas ç
or categories of realities. `Pad<193>rtha' means `what is denoted ç
by a word', an object of knowledge. All such objects can be divided ç
into two classes: bh<193>va (being) and abh<193>va (non-being). Bh<193>va ç
stands for all the positive and existent realities whereas abh<193>va ç
denotes negative facts (Vai·e<218>ikas<220>tras 1.1.14).
The saptapad<193>rthas or seven categories are: 1) dravya (substance); ç
2) gu<207>a (quality); 3)karma (action); 4) s<193>m<193>nya (generality); ç
5) vi·e<218>a (particularity); 6)samav<193>ya (relation of inherence), ç
and 7) abh<193>va (non-existence).
These may now be considered one byone.
<MS>DRAVYA<D> is a substance in which a gu<207>a (quality) and karma ç
(action) can exist. It is the substratum for both.
There are nine kinds of dravyas: the four elements (earth, water, ç
light and air, respectively called p<216>thv<200>, jala, tejas and ç
v<193>yu); <193>k<193>·a (ether); k<193>la (time); dik (space); <193>tman ç
(soul) and manas (mind). All these are eternal.
The four elements exist in the form of param<193><207>us (atoms) before ç
creation.
°k<193>·a, k<193>la, dik and <193>tman are all- pervading whereas ç
manas is a<207>u (atomic) in size.
The Vai·e<218>ika system accepts two kinds of souls: the j<200>v<193>tmans ç
and Param<193>tman (also known as ®·vara or Mahe·vara). The former ç
ones are infinite in number whereas Param<193>tman, the Supreme Soul ç
or God, is only one.
<MS>GUØA<D> or quality is always dependent on dravya or substance ç
for its existence and manifestation. It belongs to a dravya but never ç
to another gu<207>a.
The Vai·e<218>ika system enumerates the gu<207>as as 24. Some of them ç
are: the five qualities of the five sense-organs, pari-m<193><207>a ç
(magnitude), sa<221>yoga (conjunction), buddhi (cognition), sukha ç
and du<199>kha (pleasure and pain), icch<193> and dve<218>a (desire ç
and aversion), sa<221>sk<193>ra (tendency), dharma and adharma (merit ç
and demerit).
This enumeration limiting the gu<207>as to 24, has been done from ç
the standpoint of their impossibility of further division.
<MS>KARMA<D> or action is physical movement. It belongs to a substance ç
and is dynamic in nature. Five kinds of action like utk<218>epa<207>a ç
(throwing upward) and <193>ku<210>cana (contraction) have been listed. ç
They can be perceived by the senses of sight and touch.
Manas or mind too has movement but it is not perceived externally.
<MS>S°M°NYA<D> or generality is the essence in a class and can be ç
called the universal. These universals are nitya (eternal) and inhere ç
in the individuals. For example, gotva (cowness) and gha<219>atva ç
(jarness) are present in each individual cow and jar respectively. ç
The death of a cow or the breaking of a jar do not destroy the s<193>m<193>nya ç
that was in them.
<MS>VI<185>E<186>A<D> or particularity is the direct opposite of the ç
s<193>m<193>nya. It is the unique individuality of the eternal substances. ç
For instance, one param<193><207>u or atom of earth is distinct from ç
another param<193><207>u, also of earth. There is something in these ç
atoms which makes them different from one another. That is vi·e<218>a.
@SPACE1 = 
<MS>SAMAV°YA<D>or inherence seems to be a special concept contributed ç
by the Vai·e<218>ika philosophy. Sa<221>yoga or conjunction between ç
two objects can be brought about at will; so also viyoga or disjunction. ç
This relationship between two objects is temporary. But the samav<193>ya ç
relationship is inherent in the substances. (Hence they are called ç
`ayutasiddha' or related without conjunction.) It is nitya or permanent. ç
The relation by which a whole is in its parts (e.g., the cloth in ç
its threads), a quality like redness in a red object like a red rose, ç
a movement in a moving object (e.g., a moving ball), is samav<193>ya ç
or inherence. The terms related by samav<193>ya are not reversible.
<MS>ABH°VA<D> or non-existence (the last) is the only category of ç
the negative type. It is considered as a reality in this system. When ç
we look at the sky in the night, we recognise the non-existence of ç
the sun there, even as we notice the existence of the moon and the ç
stars. Broadly speaking, abh<193>va is of two types: sa<221>sarg<193>bh<193>va ç
and anyony<193>bh<193>va. The former is the absence of something in ç
something else, as the non-existence of a jar on a table. In the latter ç
case, it simply means that one thing is not another thing, as a horse ç
not being present in a buffalo.
Sa<221>sarg<193>bh<193>va is of three kinds:
1)
@NK = pr<193>gabh<193>va<R>ç
(antecedent non-existence);
2)
@NK = pradhva<221>s<193>bh<193>va or dhva<221>s<193>-bh<193>va (non-existence ç
after<R>ç
destruction); and,
3)
@NK = atyant<193>bh<193>va<R>ç
(absolute non-existence).
Non-existence of the house in the bricks, before it is built, is ç
the examplefor pr<193>gabh<193>va. Non-existence of an earthen jar ç
in the broken pieces, after the jar is broken, is the example for ç
pradhva<221>s<193>-bh<193>va. Absence of colour or shape in air is ç
the example for atyant<193>bh<193>va.
@SB8.5 = God and the World
The Vai·e<218>ika Dar·ana accepts theexistence of God†called ®·vara ç
or Mahe·vara†as the Supreme Intelligent Being under whose will and ç
guidance this world is created, sustained and destroyed.
This world is a system of physical things and the living beings which ç
interact with one another. What guides the world is actually the moral ç
order, by which the life and destiny of all the individual souls are ç
governed, the universal law of karma.
The starting point of creation (followed by sustenance and destruction, ç
these three being cyclic and eternal) is the will of God. The first ç
product of his will to create, is the World-soul, Brahm<193>. He is ç
infilled by God with the six blessed qualities like j<210><193>na, ç
vair<193>gya and ai·varya (knowledge, detachment and splendour). It ç
is this Brahm<193> the chief architect of creation, who proceeds with ç
further creation in accordance with the totality of the ad<216><218><219>as ç
(the unseen merits and demerits) of the individual souls by setting ç
in motion the param<193><207>us or atoms to combine with one another, ç
ultimately resulting in the world.
The process of dissolution is in the reverse order. Brahm<193> gives ç
up his body. Mahe·vara then wills the dissolution and brings about ç
the pralaya or destruction. The whole world is then reduced to its ç
primary state of the seven pad<193>rthas.
@SB8.5 = Conclusion
Like the Ny<193>ya system, the Vai·e<218>ika Dar·ana also is a realistic ç
philosophy which combines pluralism with theism. Creation is not by ç
chance but executed by God in a planned manner, as per the karmas ç
of the individual souls, for the proper realisation of their ultimate ç
moral perfection.
By harmonising the atomic theory with a moral and spiritual outlook ç
on life and accepting God as the creator and moral governor of the ç
world, the Vai·e<218>ika system moved nearer towards the Ved<193>nta ç
system which proved to be the pinnacle of Indian philosophy as a whole.
@SPACE = 
@NT = Vaishno Devi
@SPACE = 
The Vaishno Devi is an important cave temple nestled in the Him<193>layan ç
ranges of the Jammu region of the Jammu and Kashmir State. It is dedicated ç
to the goddess Durg<193> in her three aspects of Mah<193>sarasvat<200>, ç
Mah<193>lak<218>m<200> and Mah<193>k<193>l<200> as described in the ç
well-known work, the Durg<193>sapta·at<200> or the Ca<207><195><200>. ç
The sanctum contains three separate bulbous forms in stone, called ç
Pi<207><195><200>s, all rising from the same base stone. The first ç
representing Mah<193>sarasvat<200> has a whitish tinge. The second ç
called Mah<193>lak<218>m<200> is yellowish red in colour. The last, ç
that of Mah<193>k<193>l<200>, is black.
The whole shrine is in a natural rock form.
The origins of this cave shrine are unknown.
According to the local legends a pious br<193>hma<207>a, Pa<207><195>it ç
<185>r<200>dhar by name, lived at the foot of Trik<220><219>a (the ç
mountain where the shrine is situated) about 700 years back. Due to ç
his intense devotion and earnest prayers, the Divine Mother had manifested ç
herself as a little girl of extraordinary beauty and had fed a very ç
large crowd of people invited by <185>r<200>dhar. This place is now ç
called Bh<220>mik<193> Mandir. She had also spent nine months in meditation ç
in a cave, now known as the Garbh Joon. When pursued by the demon ç
Bhairon (Bhairava?), she beheaded him, assuming the fierce form of ç
Ca<207><195>ik<193>. At the request of the dying demon, she granted ç
the boon that her devotees should also visit the place of his death, ç
where a temple stands now, called Bhairon Mandir.
The other holy places associated with this legend are the B<193><207> ç
Ga<209>g<193> river (also called B<193>l Ga<209>g<193>) produced by ç
the arrow shot by the Mother and the Cara<207>ap<193>duk<193> temple ç
containing her footprints on a rock.
Pilgrims travel up to the small town of Katra which is 48 kms. (30 ç
miles) from Jammu. The ascent to the cave starts from here, the distance ç
being 12 kms. (7.5 miles). On the way are situated the B<193><207> ç
Ga<209>g<193> temple, the Cara<207>ap<193>duk<193> temple and the ç
halfway point called Ardh Kuvari near which is the cave Garbh Joon.
The Vaishno Devi temple is situated at a height of 1700 metres (5200 ç
ft.) above the sea-level. It is a cave 30 metres (93ft.) long and ç
1.5 metres (5 ft.) high.
A lamp is kept burning always. The shrine is kept open round the clock.
Pilgrims have to wade through ankle or knee-deep icy water in the ç
cave to have a view of the deity. The movement is by bending and crawling ç
since the height inside the cave does not permit standing.
After this, the devotees are expected to visit the Bhairon Temple ç
situated at a distance of 2.5 kms. (<%14>1<P7W1%0><$E1 over 2><P255D> ç
miles) from the main shrine and at a height of 2010 metres (6700 ft.).
Ceremonial worship is done to the goddess twice a day, at sunrise ç
and sunset. Each time it lasts for about two hours. During these periods, ç
pilgrims are not allowed inside.
The main celebrations and festivals are during the Navar<193>tra period ç
(in September/October) when a <185>ataca<207><195><200>y<193>ga is ç
organised.
@SPACE1 = 
Since <MS>A.<|>D.<D> 1986, the shrine complex is being ably managed ç
by the `Shri Mata Vaishno Devi Shrine Board'.
Facilities provided for the pilgrims include steps, tracks, resthouses, ç
living rooms, messes providing good food, medical attention, stores ç
and cloakrooms.
@NT = Vai<218><207>ava Bh<193>gavata
Pur<193><207>as are the most popular literature of the Hindus, especially ç
among the masses. Out of the 18 major pur<193><207>as, Bh<193>gavata ç
is an important work. But, there are two Bh<193>gavatas extant, one ç
dealing with the supremacy of the Dev<200>, <185>akt<200> or the Divine ç
Mother, and the other, with that of Vi<218><207>u. The former is called ç
Dev<200>-bh<193>gavata and the latter simply as Bh<193>gavata. ç
However, to distinguish the latter from the former, an appellation ç
`Vai<218><207>ava' is sometimes added, making it the Vai<218><207>ava ç
Bh<193>gavata.
It is the latter that is generally classed among the 18 major pur<193><207>as.
See also <MS>BH°GAVATA<D> and <MS>DEV®-BH°GAVATA<D>.
@NT = Vai<218><207>avadev<200>
See <MS>VAISHNO DEVI<D>.
@NT = Vai<218><207>av<200>
Listed among the Saptam<193>t<216>k<193>s (the Seven Mothers), Vai<218><207>av<200> ç
is the ·akti (power-goddess) of Lord Vi<218><207>u.
In the Durg<193>sapta·at<200> (8.18) she is described as an emanation†one ç
of the seven†of Durg<193>.
She is identical in form with Vi<218><207>u. She is dark in complexion ç
and wears yellow silken robes as also a vanam<193>l<193> (garland ç
of wild flowers). She has four hands holding cakra (discus), ·a<209>kha ç
(conch), gad<193> (mace) and padma (lotus). Sometimes she is shown ç
with six hands, the last two showing the gestures of abhaya (protection ç
from fear) and varada (giving boons).
She rides on the Garu<195>a, the famous vulture-mount of Vi<218><207>u.
@NT = Vai<218><207>avism
@SB8.5 = General Introduction
Whether Vi<218><207>u is one of the Hindu Trinity entrusted with the ç
task of sustenance of the world or an aspect of °ditya (the Sun-god) ç
or the all-pervading cosmic deity (from the root-verb vi<218><202> ç
= to pervade) there is no doubt that he is one of the most popular ç
and widely worshipped gods of the Hindus.
Though he is often associated closely with Indra in the <184>gveda ç
he never loses his prominence. His immense power to occupy and transcend ç
the three worlds asUrukrama (V<193>mana), his supreme unconquerable ç
strength, his limitless compassion towards his devotees, his being ç
the protector of all and his supremely sweet abode (the paramapada) ç
have been described in several mantras (vide <184>gveda 1.155.5; ç
6.69.8; 7.25.12; 3.55.10; 1.154.5). The best way to please him is ç
through sacrificial offerings (ibid 7.40.5) and hymns of praise (ibid ç
1.156.3).
However, by the time of the epics and the pur<193><207>as, he grows ç
in stature occupying the highest position among the gods of the Hindu ç
pantheon.
`N<193>r<193>ya<207>a' is another name by which he is known even in ç
the Vedic literature as also in the epics and the pur<193><207>as.
Being the deity responsible for the sthiti or protection of the created ç
world, he is often obliged to come down as an avat<193>ra or incarnation. ç
Though the number of such avat<193>ras can be limitless†and sometimes ç
as many as 23 are mentioned† somehow the ten known as the Da·<193>va-t<193>ras, ç
have attained a traditional sanction and a religious status.
Gradually, over the centuries, a philo-sophy and a religion centred ç
round Vi<218><207>u evolved into a regular system now called Vai<218><207>avism. ç
Bh<193>gavatamata is another name by which this system has been known.
(See <MS>BH°GAVATADHARMA<D> for details.)
@SPACE1 = 
The N<193>r<193>ya<207><200>ya section of the epic Mah<193>bh<193>rata ç
(vide <185><193>ntiparva, Chapters 334-351) seems to be the earliest ç
systematisation of Vai<218><207>avism. Other sources are: Bhagavadg<200>t<193>, ç
Vi<218><207>upur<193><207>a, Bh<193>gavata, P<193><210>car<193>tra ç
and Vaikh<193>nasa °gamas and Bhaktis<220>tras of N<193>rada ç
and <185><193><207><195>ilya.
Attention has to be drawn to another development in the evolution ç
of Vai<218><207>a-vism. Though K<216><218><207>a was listed as the ç
ninth avat<193>ra in the list of Da·<193>vat<193>ras, he was gradually ç
elevated and made identical with Vi<218><207>u-N<193>r<193>ya<207>a, ç
the ten avat<193>ras being considered his avat<193>ras. Thus the ç
K<216><218><207>a cult got merged with the Bh<193>gavatamata. Since ç
K<216><218><207>a or K<216><218><207>a-V<193>sudeva, belonged to the ç
S<193>tvata clan of the Yadu race, S<193>tvatamata is another name ç
by which it came to be known.
@SB8.5 = Various Schools of Vai<218><207>avism
The basic structure of Vai<218><207>avism as revealed in some of the ç
earliest sources like the N<193>r<193>ya<207><200>ya advocated the ç
supremacy of Vi<218><207>u-N<193>r<193>ya<207>a as God and bhakti ç
or devotion to him as the chief means of mok<218>a or liberation. ç
However, different ways of expounding it by the various <193>c<193>ryas ç
(religious teachers) gave rise, in course of time, to different sects ç
and subsects of Vai<218><207>avism. The more prominent ones among ç
them may now be described briefly.
@SB8.5 = The °<202>v<193>rs
They were the earliest Vai<218><207>ava teachers known to history. ç
They belonged to Tamil Nadu and lived probably during the period 2nd ç
to the 8th century <MS>A.<|>D.<D> Among them were saints from all castes ç
and included a woman (God<193>dev<200>) also.
They taught that Vi<218><207>u-N<193>r<193>ya<207>a was the Supreme ç
God and bhakti or devotion to him was the means of liberation. They ç
accepted the avat<193>ras (incarnations) of Vi<218><207>u such as ç
R<193>ma and K<216><218><207>a and advocated the importance of arc<193> ç
or ritualistic worship with the strong faith that God descends into ç
the icon in a subtle form during the worship.
@SB8.5 = R<193>m<193>nuja<M> (A.<|>D. 1017-1137)<D>
To R<193>m<193>nuja, the Brahman or ®·vara of Ved<193>nta is actually ç
N<193>r<193>ya<207>a (or Vi<218><207>u) inseparably associated with ç
<185>r<200> or Lak<218>m<200>. N<193>r<193>ya<207>a creates the world ç
with his twofold prak<216>ti (basic nature), the acit (insentient ç
matter) and the cit (sentient beings, the j<200>vas or individual ç
souls). He sustains it and, at the end of a cycle, withdraws it.
<185>r<200> or Lak<218>m<200> is his divine consort, the personification ç
of his compassion. She intervenes with N<193>r<193>ya<207>a on behalf ç
of the j<200>vas and gets them what they want, including liberation.
Bhakti or devotion to both of them is the chief means of liberation.
Since R<193>m<193>nuja gives equal importance to <185>r<200> (or Lak<218>m<200>) ç
along with Vi<218><207>u-N<193>r<193>ya<207>a, his system is known ç
as <185>r<200>vai<218><207>avism.
See also <MS>R°M°NUJ°C°RYA<D>, <MS><185>R®VAI<186>ØA-VISM<D> and <MS>VI<185>I<186><187>°DVAITA-VED°NTA-DAR<185>ANA<D>.
@SPACE = 
@SB8.5 = Madhva<M> (A.<|>D. 1238-1317)
@SPACE = 
The credit for establishing Vai<218><207>a-vism on a firm foundation ç
and making it popular among the masses should go to Madhva or Madhv<193>c<193>rya. ç
His philosophy, known as Dvaita Ved<193>nta, can be summed up as follows: ç
`<185>r<200>hari (Vi<218><207>u-N<193>r<193>ya<207>a) is the highest ç
truth who can be known only through the Vedas. The created world is ç
real. The j<200>vas are all different from one another and are dependent ç
on <185>r<200>hari. Among them also, there are differences of quality ç
and status. Mukti or liberation is actually the experiencing of one's ç
real nature as <193>nanda or bliss. This can be got through pure devotion ç
to <185>r<200>hari.'
From this philosophy of devotion to Vi<218><207>u evolved the various ç
corollaries suchas ritualistic worship and devotional singing, giving ç
rise to a regular movement of saints of devotion.
See <MS>D°SAK<188><187>A<D> and <MS>DVAITA-VED°NTA-DAR<185>ANA<D>.
@SPACE = 
@SB8.5 = Nimb<193>rka <M>(12th century A.<|>D.)
@SPACE1 = 
Nimb<193>rka's philosophy is known as Dvait<193>dvaita.
Parabrahman or God is K<216><218><207>a. He is the supreme independent ç
reality. The j<200>v<193>tmas (individual souls) are infinite in number ç
and are atomic in size. Prak<216>ti is insentient nature out of which ç
the world is made. The j<200>vas and prak<216>ti are dependent realities ç
ever inseparable from Parabrahman. The relationship between them is ç
like that of the sea and the waves or the sun and its rays.
Bhakti or devotion to K<216><218>na along with R<193>dh<193>, surrender ç
to them and obedience to the guru or spiritual teacher are the chief ç
means of liberation.
Nimb<193>rka was the first Vai<218><207>ava teacher to introduce R<193>dh<193> ç
as K<216><218><207>a-·akti or divine consort.
@SPACE = 
@SB8.5 = R<193>m<193>nanda <M>(A.<|>D. 1400-1470)
@SPACE1 = 
Though ordained by a monk of the R<193>m<193>nuja sect of Vai<218><207>avism, ç
R<193>m<193>nanda deviated from it in advocating devotion to R<193>ma ç
as the best means of liberation and initiated persons of all castes ç
into his cult. Kab<200>r (<MS>A.<|>D.<D> 1440-1518), barber Sen<193> ç
(of Maharashtra) and Padm<193>vat<200>, a woman, were  among  his  group  of  disciples. ç
Tulas<200>d<193>s (<MS>A.<|>D.<D> 1532-1623) was a follower of R<193>m<193>nanda's ç
path of devotion.
He succeeded to a great extent in spreading Vai<218><207>avism with ç
R<193>ma as the central deity.
@SB8.5 = Kab<200>rd<193>s<M> (A.<|>D. 1440-1518)<D>
Prominent among the leaders of the Bhakti movement of the Middle-Ages, ç
Kab<200>r (supposed to be a Muslim) was a disciple of R<193>m<193>nanda. ç
Devotion to R<193>ma, ignoring the many social conventions,was the ç
path he accepted and preached. In course of time his followers formed ç
a separate sect in his name and came to be known as Kab<200>rpanthis.
@SB8.5 = Vallabha<M> (A.<|>D. 1473-1531)<D>
Originally hailing from the Telugu country (the present Andhra Pradesh) ç
Vallabha settled down in V<216>nd<193>ban. He was not only a great ç
scholar but also a great devotee. He further strengthened the movement ç
of K<216><218><207>abhakti.
Himself remaining a householder he preached an easy path of worship ç
of and total surrender to K<216><218><207>a. Like R<193>m<193>nanda ç
he too accepted disciples from all castes and even from other religions. ç
His disciples were responsible for building temples of K<216><218><207>a ç
and spreading the sect.
Pu<218><219>im<193>rga (`path of spiritual nourishment') which advocates ç
the path of total self-surrender to God receiving proper initiation  from  a  qualified  guru  is ç
Vallabha's special contribution.
See also <MS>PU<186><187>IM°RGA<D>.
@SB8.5 = Caitanya<M> (A.<|>D. 1486-1533)<D>
Caitanya or <185>r<200>k<216><218>na Caitanya, who hailed from Bengal, ç
is another bright jewel shining brilliantly among the leaders of Vai<218><207>avism.
Though an unrivalled scholar, especially in logic, revelling in defeating ç
other scholars, he was totally transformed into an equally unrivalled ç
devotee of K<216><218><207>a, by ®·varapur<200>, a sa<221>ny<193>sin ç
of the M<193>dhva Order.
Group-singing of devotional songs on K<216><218><207>a and dancing ç
in his name†generally called Sa<209>k<200>rtan†are his contribution.
He propagated a philosophy known as Acintyabhed<193>bheda and tried ç
to wipe off caste distinctions in the name of K<216><218><207>a.
His followers consider him a combined incarnation of R<193>dh<193> ç
and K<216><218><207>a.
@NID = <+><+><+>See also <MS>ACINTYA-BHED°BHEDA SCHOOL<D>.
@SPACE1 = 
@SPACE1 = 
@SB8.5 = Spread of Vai<218><207>avism
@SPACE1 = 
Vai<218><207>avism, as an important aspectof the Bhakti Movement, ç
spread all over the land†the Indian peninsula†right from the 13th ç
century up to the 18th. Broadly speaking, there were two important ç
streams centred round R<193>ma and K<216><218><207>a, the latter being ç
much more popular.
The R<193>ma sect which was ushered in by R<193>m<193>nanda and Kab<200>r, ç
was sustained and developed by Gosv<193>mi Tulas<200>-d<193>s (<MS>A.<|>D.<D> ç
1532-1623), Samartha R<193>mad<193>s (<MS>A.<|>D.<D> 1608-1681), Bhadr<193>cala ç
R<193>mad<193>s (<MS>A.D.<D> 1630-1687) and the great musician-saint ç
Ty<193>gar<193>ja (<MS>A.<|>D.<D> 1767-1847) as also their disciples.
@SPACE1 = 
As regards the K<216><207>a sects they are legion.
@SPACE1 = 
The saints of Maharashtra, led by Sant J<210><193>ne·var (end of the ç
13th century <MS>A.<|>D.<D>) and followed by other saintly devotees ç
such as N<193>mdev (<MS>A.<|>D.<D> 1270-1350), Ekn<193>th (<MS>A.<|>D.<D> ç
1533-1606) and Tuk<193>r<193>m (<MS>A.D.<D> 1607-1694) revolutionised ç
the way of life of the common folk with the P<193><207><195>ura<209>ga-Vi<219><219>hala ç
cult. Closely akin to it and on almost parallel lines was the K<216><218><207>abhakti ç
movement of the Harid<193>sas of Karnataka like Purandarad<193>sa ç
(<MS>A.<|>D.<D> 1484-1564), Kanakad<193>sa (15th century <MS>A.D.<D>) ç
and Vijayad<193>sa (1687-1755).
In the Hindi belt of North India it was left to the blind saint S<220>rd<193>s ç
(<MS>A.<|>D.<D> 1478-1583) and the queen-saint M<200>r<193> (<MS>A.D.<D> ç
1450-1547) to popularise devotion to K<216><218><207>a.
Mention should also be made of Naras<200> Meht<193> (<MS>A.<|>D.<D> ç
1415-1481) of Gujarat and  <185>a<209>karadeva  (<MS>A.<|>D.<D> 1449-1569)  of ç
Assam who spread the K<216><218><207>a cult in their regions.
The  Bhakti  Movement  of  these musician-saints made religion simple ç
and practical for the common people. It also successfully reclaimed ç
many of them who hadgone outside the Hindu fold.
@SB8.5 = Conclusion
Vai<218><207>avism  like  <185>aivism,  is  an important aspect of ç
Hinduism. Though rooted in the Vedic concept of dedication to Vi<218><207>u, ç
it has, over the centuries, expanded enormously both in depth and ç
width, fulfilling a great psychological need of the Hindu society. ç
That is why it is a formidable force to reckon with even to this day ç
as reflected in the spate of Vai<218><207>ava temples and festivals.
@SPACE1 = 
@NT = Vai·rava<207>a
Since Kubera was the son of the sage Vi·ravas, he came to be known ç
as Vai·rava<207>a.
See <MS>KUBERA<D> for details.
@SPACE1 = 
@SPACE1 = 
@NT = Vai·vadeva
@N1 = (`pertaining to all the gods')
@SPACE1 = 
@SPACE1 = 
This is the first of the four Vedic sacrifices listed under C<193>turm<193>sya ç
(See <MS>C°TURM°SYA<D>.). It is performed mainly to attain heaven ç
and is spread over two days.
