On the first day an oblation with the pa<210>cahot<216> formula (a ç
mystical mantra in which five priests are mentioned) and a cake are ç
offered to the Vai·v<193>nara Agni (fire-god).
A new fire is generated on the second day mixed with the existing ç
<193>havan<200>ya fire. This is followed by several steps of the sacrifice ç
which are too complicated to mention.
The left-over offering of V<193>jina (liquid portion of `broken' milk) ç
has to be consumed by the sacrificer.
@NT = Vai·v<193>nara
@N1 = (`one who leads all human beings')
This word has been used in several senses. It is one of the names ç
of Agni, fire or fire-god.
The Bhagavadg<200>t<193> (15.14) refers to it as an aspect of K<216><218><207>a ç
(or God) who resides in the bodies of living beings and digests the ç
food they eat (vide B<216>had<193>ra<207>yaka Upani<218>ad 5.9.1 ç
also).
In the Ved<193>nta philosophy it refers to  Brahman<|>/<|><193>tman  as  consciousness, ç
associated with the whole created world (vide M<193><207><195><220>kya ç
Upani<218>ad 3). The Ved<193>ntas<193>ra of Sad<193>nanda calls ç
him as Vir<193><219> also (para 111).
He is called Vai·v<193>nara since he leads all human beings according ç
their pu<207>ya (merit) or p<193>pa (demerit) to the respective goals.
@NT = Vai·ya
See <MS>VARØA<D>.
@NT = Vaitara<207><200>
@N1 = (`[the river] to be crossed')
The pur<193><207>as describe that those sinners who are destined to ç
go to hell, have to cross this foetid river, full of blood, hairs ç
and bones. While crossing it they are tormented terribly.
It is also the name of a cow that is donated to a br<193>hma<207>a ç
during the antye<218><219>i (death-rites), which is supposed to help ç
the soul of the dead to cross the river Vaitara<207><200>.
A river in Kali<209>ga (the modern Orissa State) has been called Vaitara<207><200>. ç
It is sometimes identified either with the river Mah<193>nad<200> ç
or the Betrani.
The ek<193>da·<200> of the dark fortnight of the month of M<193>rga·<200>r<218><193> ç
or Agrah<193>ya<207>a (November/December) is called Vaitara<207><200>. ç
A special vrata (religious observance) called Vaitara<207><200>vrata ç
is observed on this day by worshipping a dark cow so that itwill ç
help the observer to cross the Vaitara<207><200> River after death. ç
This vrata has to be observed for one year in three periods of four ç
months.
@NT = Vaivasvata
@N1 = (`son of Vivasv<193>n')
°ditya†Sun-god†is known as Viva-sv<193>n. His wife was Sa<221>j<210><193>. ç
Vaivasvata was their son. He is also known as Vaivasvata-manu and ç
<185>r<193>ddhadeva.
He is the seventh in the series of Manus. It is his rule, called Manvantara, ç
that is going on now.
@SPACE = 
@NT = V<193>japeya
See <MS>VEDIC SACRIFICES<D> for a short account.
@SPACE = 
@NT = V<193>jasaneya Sa<221>hit<193>
See <MS><185>UKLA YAJURVEDA SA<189>HIT°<D> and <MS>YAJURVEDA<D>.
@NT = vajra
This word has three meanings: 1.diamond; 2. the thunderbolt of the ç
god Indra; 3. lightning.
According to certain °yurvedic texts, wearing a diamond on the body ç
gives it firmness and also rejuvenates it.
It is of course used in various ornaments.
As regards its meaning as Indra's special weapon, see <MS>VAJR°YUDHA<D>.
Vajra, according to the Bh<193>gavata (1.15.39), was the great-grandson ç
of Lord K<216><218><207>a (son of Aniruddha and U<218><193>) who was ç
installed as the king of the country known as <185><220>rasena. He ç
was one of thefive survivors after the Y<193>davas' internecine fighting.
@NT = Vajr<193>yudha
@N1 = (`the thunderbolt weapon')
This is the invincible weapon of Indra with which he killed many powerful ç
asuras (demons) like V<216>tra.
@SPACE = 
@SPACE = 
@SPACE = 
It is said to have been shaped out of the backbone of the sage Dadh<200>ci ç
(See <MS>DADH®CI<D>.) by Vi·vakarma, the architect of the gods.
@NT = v<193>k
@N1 = (`speech')
See <MS>V°C<D>.
@NT = v<193>kyabheda
@N1 = (`split of sentences')
This is an important principle adopted by the P<220>rvam<200>m<193><221>s<193> ç
works to decide the correct meaning of a Vedic text.
The same principle is resorted to, by the dharma·<193>stra works also.
The doctrine of v<193>kyabheda can be understood in two ways. If there ç
are two v<193>kyas or sentences which are equally independent, neither ç
needing the help of the words of the other to complete it, theyshould ç
be treated as two separate sentences. This is the first sense.
The second sense is as follows: Suppose that in one sentence one vidhi ç
or injunction is given and several other related factors have also ç
been added. If these latter factors are considered further vidhis, ç
then, the defect of v<193>kyabheda arises. If on the other hand, they ç
are treated as arthav<193>das†eulogies to strengthen the sense of ç
the vidhi already stated†there is no v<193>kyabheda.
This principle of v<193>kyabheda has often been resorted to by the ç
commentators of Vedic works and dharma·<193>stra-treatises to fix ç
the correct meaning of the originals.
@NT = V<193>lakhilyas
The V<193>lakhilyas were great sages (60,000 in number) born of the ç
parents Kratu and Kriy<193>dev<200>. They were of the size of a thumb! ç
Once they helped the sage Ka·yapa in the performance of a sacrifice ç
and became tired. Indra who saw them in that condition laughed at ç
them incurring their wrath. They cursed him that Garu<195>a†born out ç
of their tapas (austerity)†would punish him for his arrogance.
@NT = V<193>li
See <MS>R°M°YAØA<D>.
@NT = Vallabha
@N1 = (<MS>A.<|>D.<D> 1473-1531)
Vallabha or Vallabh<193>c<193>rya was one of the more prominent teachers ç
of Vai<218><207>a-vism who contributed considerably to the cult of ç
K<216><218><207>abhakti or devotion to K<216><218>na.
He was born at Camp<193>ra<207>ya (near the modern Raipur in the Chattisgarh ç
State) to the couple Lak<218>ma<207>abha<219><219>a and Yellamma who ç
were originally from the Telugu country (Andhra Pradesh).
Since Lak<218>ma<207>abha<219><219>a had settled down at K<193>·<200> ç
(the modern Banaras), Vallabha got the opportunity for very good education. ç
Trained by Vi<218><207>ucitta, he proved to be a child prodigy by ç
mastering the Vedas, the Ved<193><209>gas and the six systems of philosophy ç
as also other scriptures like the Bhagavadg<200>t<193>, and the ç
Bh<193>gavata.
He lost his father at the age of eleven. This led to the break-up ç
of the home at Banaras. From this time†even though he was quite young†he ç
undertook a pilgrimage of the whole of India three times, lasting ç
for about twenty years. During his sojourn to South India, he came ç
to Vijayanagar when the famous king K<216><218><207>a-devar<193>ya ç
(<MS>A.<|>D.<D> 1488-1529) had just taken over as the king.
Though  a  boy  of  twelve  years Vallabha soon established his mastery ç
over the scriptures and philosophies by defeating many a scholar in ç
debates. He was honoured by the king with the rite of kanak<193>bhi<218>eka ç
(showering with gold coins).
Other places he visited included some of the well-known places of ç
pilgrimage. They were: <185>r<200>·aila, Tirupati, K<193><210>c<200>puram, ç
Madurai, R<193>me·varam, U<195>upi, Gokar<207>a (all in South India); ç
Pa<207><195>har<193>pur, N<193>sik and Tryambake·var (in Maharashtra); ç
Dv<193>rak<193> (in Gujarat); Mathur<193> and V<216>nd<193>ban (in ç
western Uttar Pradesh); Him<193>layan centres such as Badar<200>, ç
Ked<193>r and Ga<209>gotri; Ga<209>g<193>s<193>gar and Pur<200> in ç
eastern India.
After  the  second  pilgrimage  he married Mah<193>lak<218>m<200>, ç
daughter of a pious br<193>hma<207>a Devadatta.
During  one  of  his  pilgrimages, Vallabha had a wonderful divine ç
experience. He received the command as to his mission of life from ç
a divine sage who was a disciple of <185><193><207><195>ilya, the ç
great teacher of bhakti.
He now started his own samprad<193>ya or spiritual tradition†a new ç
faith or asect†at Gokula (in the Mathur<193>-V<216>nd<193>ban region). ç
He received an image of Govardhanan<193>tha (Boy K<216><218><207>a ç
in the act of lifting the Govardhana hill)†which emerged mysteriously ç
out of a cave†from a saint M<193>dhavendra-pur<200>, built a small ç
temple for it and started its worship. Later on, a much bigger temple ç
was built. Due to the Muslim invasions, the image was later†after ç
Vallabha's time†shifted to N<193>thdv<193>ra near Udaipur (in Rajasthan). ç
The temple there is now quite famous and the image is called <185>r<200>n<193>thj<200>.
Vallabha considered K<216><218><207>a as the highest God. He advocated ç
his worship, especially  as  B<193>lak<216><218><207>a  (Boy-K<216><218><207>a). ç
Redemption can come only through his grace. The mantra he gave to ç
one and all was <185>rik<216><218><207>a<199> ·ara<207>a<221> mama.
@SPACE1 = 
His philosophy is known as <185>uddh<193>dvaita and the religious ç
path as Pu<218><219>im<193>rga (See <MS>BRAHMAS<188>TRAS<D> and <MS>PU<186><187>IM°RGA<D>).
Vallabha wrote several philosophical and devotional works. Among them ç
the A<207>ubh<193><218>ya on the Brahmas<220>tras and Subodhin<200> ç
on the Bh<193>gavata are famous. Unfortunately both are incomplete.
He took sa<221>ny<193>sa during his last days from M<193>dhavendrapur<200> ç
and gave up his body in the Ga<209>g<193> at Hanum<193>ngh<193><219> ç
in V<193>r<193><207>as<200> (Banaras).
His second son Vi<219><219>halan<193>tha became the leader of the ç
sect after Vallabha.
@NT = V<193>lm<200>ki
V<193>lm<200>ki is the sage who has immortalised himself and his work, ç
the R<193>m<193>ya<207>a.
According to one version, he was a praj<193>pati, a son of Pracetas.
According   to  another   version (Adhyatma R<193>m<193>ya<207>a, ç
Ayodhy<193>k<193><207><195>a 6.57-78) he was a br<193>hma<207>a ç
by birth, but was brought up by robbers. Once, the Saptar<218>is (the ç
Seven Sages) came to his forest and were accosted by him. Contact ç
with these holy sages converted him to pursue a life of devotion to ç
R<193>ma. Since he sat in meditation for many years, an anthill grew ç
over him. When the sages†on their return journey†found him in that ç
condition they poured water over the anthill, released him and blessed ç
him with a new name `V<193>lm<200>ki' (one who emerged out of an anthill).
@SPACE1 = 
V<193>lm<200>ki established his own <193>·rama and started living ç
there. One day when he came to the river Tamas<193> for bath, hesaw ç
a hunter kill a male bird and heard the piteous wailings of the female. ç
Immediately he cursed the hunter, which curse emerged from his mouth ç
in the formof a ·loka (a verse in the anu<218><219>ubh metre). Wondering ç
at this phenomenon he returned to his hut. Then Brahm<193>, the creator ç
appeared before him and commanded him to compose the detailed life-story ç
of R<193>ma for which the basic material was given by the sage N<193>rada. ç
Thus came into existence the great epic R<193>m<193>ya<207>a.
When R<193>ma banished S<200>t<193> due to public criticism, Lak<218>ma<207>a ç
left her near the hermitage of V<193>lm<200>ki. She was pregnant at ç
that time. She delivered twins who were christened by V<193>lm<200>ki ç
as Lava and Ku·a. It was V<193>lm<200>k<200> who brought them up, ç
educated them and also taught them the R<193>m<193>ya<207>a with ç
music. Later he took S<200>t<193> and the children to R<193>ma and ç
offered them back to him. While S<200>t<193> entered the womb of Mother ç
Earth, the sons were accepted by R<193>ma.
@NT = v<193>m<193>c<193>ra
@N1 = (`left-handed path or practice')
See <MS>TANTRAS<D>.
@NT = V<193>madeva
V<193>madeva is a sage well-known in the Upani<218>ads. The Aitareya ç
Upani<218>ad (2.1.5) says he had realised the <193>tman even while ç
in the womb of his mother. The B<216>had<193>ra<207>yaka Upani<218>ad ç
(1.4.10) declares that the sage V<193>madeva realised Brahman and ç
hence his identity with Manu and S<220>rya. The R<193>ma-p<220>rva-t<193>pan<200> ç
Upani<218>ad (6.16) describes that R<193>ma was worshipped by great ç
sages like Vasi<218><219>ha and V<193>madeva.
According to the <185>ivapur<193><207>a (Kail<193>sakha<207><195>a ç
11.12) he learnt about Pra<207>ava from Kum<193>rasv<193>mi (<186>a<207>mukha ç
or Subrahma<207>ya) and taught it to other sages.
°treya was his disciple.
V<193>madeva is also one of the five aspects of <185>iva (See <MS>PA<178>C°NANA<D>.)
@NT = V<193>madevag<200>t<193>
@N1 = (`G<200>t<193> [taught by the <R>ç
sage] V<193>madeva')
This is one of the sixteen minor g<200>t<193>s found in the Mah<193>bh<193>rata. ç
It occurs in the <185><193>ntiparva (Chapters 92 to 94) and has ç
71 verses. It is in the form of a dialogue between the sage V<193>madeva ç
and the king Vasumanas. This has been recounted by Bh<200><218>ma ç
to Yudhi<218><219>hira. R<193>jadharma (or the duties of a king) is ç
the chief topic covered here.
By describing the qualities of a good king and the characteristics ç
of an evil one, the work places before us the picture of an ideal ç
kingdom.
An ideal king follows the path of dharma (righteousness) always. In ç
this he has to be guided by a competent guru or spiritual preceptor. ç
He has to assiduously cultivate great virtues such as self-control, ç
soft but truthful speech, respect for the virtuous people, consideration ç
for others and devotion to spiritual life. By relentless effort and ç
diligence he should acquire competence in as many fields of administration ç
as possible.
He should appoint the right man for the right place, take good care ç
of trusted assistants and employees, and organise an efficient espionage ç
system.
He should keep the following as top-secrets: strengthening defences ç
like the forts; plans of wars; consultations with trusted ministers ç
regarding the affairs of the State; proper plans for giving comforts ç
and conveniences to the people at the right time.
In wars he should fight like a hero and treat the prisoners, especially ç
the captured  rulers,  with  kindness  and sympathy.
As regards internal administration, he has to pay attention to the ç
following factors: protect himself from internal enemies; take the ç
help of reliable people who have proved their loyalty and efficiency; ç
keep the taxes to the minimum level; be just and impartial towards ç
the subjects; avoid haste in implementing the decisions and policies ç
arrived at.
As against this, V<193>madeva also cautions Vasumanasa as to what ç
a king ought not do by describing the follies of a bad king.
A bad king not only abandons dharma but also wilfully follows adharma ç
(evil ways). He rules by force, oppresses the weak but gives a free ç
hand to the wicked. Leading an immoral life himself, he encourages ç
it in others. He ignores the guru and the good ministers (if any), ç
employs evil persons and knaves to assist him and harasses his subjects. ç
Neglecting the time-tested traditions, being indifferent towards well-wishers ç
and the welfare of the State he ultimately ruins himself and the kingdom.
@NT = V<193>mana
V<193>mana  is  the  fifth  avat<193>ra  or incarnation of Lord Vi<218><207>u.
See <MS>AVAT°RA<D> and <MS>DA<185>°VAT°RAS<D>.
The concept of V<193>mana as Trivikrama is very ancient and is found ç
in the Vedas(vide <185>atapatha Br<193>hma<207>a 1.1.5; Taittir<200>ya ç
Sa<221>hit<193> 2.1.3; Taittir<200>ya Br<193>hma<207>a 1.6.1), ç
as also many pur<193><207>as.
Iconographical  works  describe  him as a short-statured brahmac<193>ri ç
(Vedic student) with two arms holding a chatra (umbrella), da<207><195>a ç
(staff) and kama<207><195>alu (water-pot). He wears a kaup<200>na ç
(loin-cloth) and has a ·ikh<193> (tuft of hair) on his head.
Several varieties of V<193>mana†such as Dadhi-v<193>mana and Vi·va-v<193>mana†are ç
sometimes mentioned in some works of tantra.
V<193>mana also figures in the list of 24aspects of Vi<218><207>u ç
(See <MS>CATURVI<189><185>ATI M<188>RTI<D>.).
@SPACE = 
@NT = V<193>manapur<193><207>a
@SPACE = 
This is a comparatively short pur<193><207>a listed among the Mah<193>pur<193><207>as. ç
It was probably compiled during the period <MS>A.<|>D.<D> 600-900. ç
The extant version has 5400 verses, spread over 95 adhy<193>yas or ç
chapters, though, according to the Matsya and the V<193>yu pur<193><207>as, ç
it has 10,000 verses.
There seems to have been a second part of this pur<193><207>a called ç
B<216>had-V<193>mana-pur<193><207>a which, however, is not available ç
now.
It was narrated by the sage Pulastya to N<193>rada at his request.
As the name indicates, it is concerned with the avat<193>ra of Vi<218><207>u ç
as V<193>mana, the fifth incarnation among the Da·<193>vat<193>ras ç
and hence a Vai<218><207>ava pur<193><207>a. However, equal importance ç
and reverence have been accorded to <185>iva and Dev<200> also.
The story of V<193>mana and Bali (the king of Asuras) has been narrated ç
in great detail in the following chapters; 73; 74; 75; 77; 89; 91; ç
92; 93; 94; 95.
Other subjects dealt with are: <185>iva cutting off one of the five ç
heads of Brahm<193>; <185>iva redeemed at V<193>r<193><207>as<200>; ç
destruction of Dak<218>a's sacrifice; Sat<200> (<185>iva's wife) immolating ç
herself and reborn as P<193>rvat<200>, the daughter of Him<193>layas; ç
<185>iva burning up K<193>ma (the god Eros); observance of certain ç
vratas like K<193>l<193><218><219>am<200>; story of Durg<193>, Mahi<218><193>sura ç
and Andhaka; greatness of the Sarasvat<200> river; detailed description ç
of Kuruk<218>etra and pilgrim centres associated with it; story of ç
Da<207><195>aka and Da<207><195>a- k<193>ra<207>ya including <185>ukr<193>c<193>rya's ç
curse; various incidents connected with Prahl<193>da; and, story of ç
Gajendra's deliverance.
@SPACE1 = 
Several topics dealt with in the dharma·<193>stra   treatises   have   been ç
described here, such as†t<200>rthas (holy rivers); sad<193>c<193>ra ç
(good conduct); s<193>manya-dharma (virtues common for all); <193>·rama-dharma ç
(duties of the four stages of life);vratas (religious observances); ç
karma theory and its application.
Unlike other pur<193><207>as, this pur<193><207>a does not give the ç
genealogies of kings andsages. However, detailed geographical descriptions ç
of mountains, rivers and janapadas (countries) are found here.
The  mountains  are:  Mahendra, Malaya, Sahya, <185>uktim<193>n, <184>k<218>a, ç
Vindhya, and P<193>riy<193>tra.
The various rivers arising from there are also mentioned.
The janapadas divided according to the traditional directions are: ç
A<209>ga, B<193>hl<200>ka, Bh<193>rakaccha, Caula, K<193>mbhoja, Kerala, ç
Pr<193>gjyoti<218>a, Pu<207><195>ra, Sur<193><218><219>ra, Tu<218><193>ra, ç
and Va<209>ga.
Some of the social customs that prevailed were: early marriage; ·ulka-dharma ç
(bridegroom's parents giving money and presents to the bride); restriction ç
of freedom to girls and women; sat<200>- custom prevalent in certain ç
sections of the society; disfavour of polygamy and having too many ç
offsprings; killing of animals and felling of trees frowned upon; ç
strict adherence to the caste-system but possibility of attaining ç
the status of a br<193>hma<207>a by taking bath in certain holy rivers ç
(observing all the necessary disciplines) accepted.
Though the language of the work is similar to that of the general ç
pur<193><207>as, it often rises to great literary heights while describing ç
the seasons, the mountains, city of V<193>r<193><207>as<200> and the ç
battles between the devas and asuras.
See <MS>DA<185>°VAT°RAS<D> and<MS> PUR°ØAS.
@SPACE = 
@NT = Vanadurg<193>
@SPACE = 
She is one of the several aspects of Durg<193> (See <MS>DURG°.<D>) ç
described in icono-graphical works. Her complexion is greenish like ç
fresh grass. She has eight arms. In seven, she carries cakra (discus), ç
·a<209>kha (conch), asi (sword), carma (shield), b<193><207>a (arrow), ç
c<193>pa (bow) and ·<220>la (spear). The eighth is showing the tarjan<200> ç
mudr<193> (gesture of threat). She stands on the head of Mahi<218><193>sura ç
(buffalo-demon).
As the name indicates, her shrines are perhaps established in vanas ç
or forests.
@SPACE = 
@SPACE = 
@NT = Vanam<193>l<193>
@N1 = (`garland of forest flowers')
@SPACE = 
@SPACE = 
If  Vi<218><207>u's  garland  is  known  as Vaijayant<200>, K<216><218><207>a's ç
is called Vanam<193>l<193>. Since he spent his childhood days at Gokula ç
(a small village situated in a forest area) he loved to wear a garland ç
(= m<193>l<193>) of flowers available in a forest (= vana). They must ç
be fresh flowers of all varieties with a large kadamba (Nauclea cadamba) ç
flower in the centre.
@SPACE = 
@NT = v<193>naprastha
@N1 = (`forest hermit')
@SPACE = 
This is the third stage of life for a dvija (the twice-born, a member ç
of the first three castes). Vaikh<193>nasa seems to have been the ç
ancient name for a v<193>naprastha.
Generally, a g<216>hastha (a house-holder), around the age of 50 or ç
55, after the birth of grand-children, when the hairstarts turning ç
grey and the skin getswrinkled, is expected to hand over the responsibilities ç
of the family to his children and retire to the vana or forest. He ç
may take his wife if she is willing to share his life of austerities ç
or leave her with his sons.
If he had established the ·rauta or the Vedic fires, he could carry ç
the same with him to the forest also. Otherwise he could carry the ç
g<216>hya or domestic fire.
He was expected to perform some ·rauta sacrifices like the Dar·ap<220>r<207>am<193>sa ç
and the C<193>turm<193>syas.
He had the freedom to give up the ·rauta fires and kindle a separate ç
fire for certain limited rituals.
He had to live an austere life by notshaving the hair, growing a ç
beard, subsisting on simple food available in the forest like roots, ç
vegetables and fruits or even by begging from other hermits. Eating ç
once a day and occasional fasting were emphasised.
Bathing thrice or twice a day, wearing a deerskin or coarse garments, ç
performing the five daily sacrifices (See <MS>PA<178>CAMAH°-YAJ<178>AS<D>.),  studying  the  Vedas  and ç
observing continence were compulsory. He was expected to devote his ç
mind in contemplation on God or Brahman.
Some dharma·<193>stra works describe four types of v<193>naprasthas.
V<193>naprasthas who were suffering from severe old-age ailments or ç
incurable diseases could commit religious suicide by mah<193>prasth<193>na ç
(walking unto death) or by entering a river or fire.
Though br<193>hma<207>as could take to sa<221>ny<193>sa after v<193>naprastha ç
stage, it was denied to others.
@SPACE = 
@NT = Va<207><200>vil<193>sa Press, <185>r<200>ra<209>gam
@SPACE = 
When Saccid<193>nanda <185>iv<193>bhinava N<216>si<221>ha Bh<193>rat<200> ç
(<MS>A.<|>D.<D> 1858-1912), the 33rd pontiff of the <185><193>rad<193> ç
Ma<219>ha of <185><216><209>ger<200>, discovered K<193>la<195><200> ç
(in Kerala State) as the birth-place of <185>a<209>kara (<MS>A.<|>D.<D> ç
788-820), he made all arrangements to acquire the land and develop ç
a monastic centre there. It was his earnest desire that someone should ç
take the responsi- bility of collecting all the works of <185>a<209>kara ç
and bring them out in print. This task was entrusted to T. K. B<193>lasubrahma<207>ya ç
Aiyar (<MS>A.<|>D.<D> 1874-1947) who, with superhuman efforts started ç
the V<193><207><200>vil<193>sa Press at <185>r<200>ra<209>gam in <MS>A.<|>D.<D> ç
1904. After collecting thousands of manuscripts of <185>a<209>kara's ç
works, he successfully brought out over the years, the entire series ç
under the general title <185>r<200> <185>a<209>kara Granth<193>vali<199>.
The books have been out of print for a long time.
They have now been reprinted by the Samata books of Chennai.
@NT = vapana
@N1 = (`shaving')
In the life of a Hindu, even vapana or mu<207><195>ana (shaving or ç
the tonsure ofthe head) becomes associated with religious rites.
It is often resorted to mostly as a compulsory act, in places of pilgrimage ç
like Pray<193>ga. It is also necessary on the death of one's father ç
or mother.
As a part of penances too it has to be done.
For  sa<221>ny<193>sins  (monks)  it  was compulsory. Some dharma·<193>stras ç
have prescribed it for widows also, since their life was to be similar ç
to that of the sa<221>ny<193>sin.
Learned br<193>hma<207>as and kings were generally exempt from it.
@SPACE1 = 
At the Trive<207><200>sa<209>gama in Pray<193>ga, married ladies could ç
offer a small part of their braid of hair with mantras as a part of ç
a religious vow.
