@NT = Varadar<193>ja
@SPACE = 
Varadar<193>ja, the king among the bestowers of boons, is another ç
aspect ofLord Vi<218><207>u which is very popular. Also known as ç
Karivarada, it represents that aspect of the Lord responsible for ç
saving Gajendra, the elephant king, from the death-clutches of the ç
crocodile.
The temple of <185>r<200> Varadar<193>ja at K<193>nc<200>puram in ç
South India, is one of themost important and famous Vi<218><207>u ç
temples.
@SPACE = 
@SPACE = 
@NT = Var<193>hamihira
@N1 = (<MS>A.<|>D.<D> 505-587)
@SPACE = 
@SPACE = 
Hindu science of astronomy has itsroots in Jyauti<218>a, considered ç
one of the six Ved<193><209>gas (limbs of the Vedas). Scholars feel ç
that it dates back to at least 1400 <MS>B.<|>C.<D>
The S<220>ryasiddh<193>nta, believed to be a revealed work, is the ç
earliest treatise available on this subject. It was thoroughly revised ç
by Var<193>hamihira, a great name among the Hindu astronomers.
Var<193>hamihira was the son of °dityad<193>sa of Kapitthaka or Avantik<193>.
Practically nothing is known about him. Tradition describes him as ç
one of the  `Navaratnas'  or  `Nine-jewels'  of scholars adorning ç
the court of the king Vikram<193>ditya.
His well-known works are: B<216>ha-jj<193>taka, B<216>hatsa<221>hit<193>, ç
Laghuj<193>taka and Pa<210>casiddh<193>ntika.
He was both an astronomer and an astrologer.
In the Pa<210>casiddh<193>ntika he enunciates the astronomical principles ç
embodied in the works of ancient scholars like Paili·a, Romaka, Vasi<218><219>ha ç
and Brahma.
The first two treatises enlisted above are on astrology. Incidentally ç
they also furnish some geographical data.
Var<193>hamihira was the first astro-nomer to furnish a revised version ç
of theHindu calendar, after calculating the precession of the equinoxes ç
from the period of the preparation of the earlier S<220>ryasiddh<193>nta.
He has employed ·<220>nya or zero as a positive numerical symbol.
@SPACE = 
@NT = Var<193>hapur<193><207>a
@SPACE = 
Listed as the twelfth among the eighteen Mah<193>pur<193><207>as, ç
the Var<193>hapur<193><207>a is a Vai<218><207>ava work. It was ç
taught by Var<193>ha (third incarnation of Lord Vi<218><207>u) to ç
Bh<220>dev<200> (Mother Earth). The extant texts have 217 or 218 chapters, ç
the total number of verses being around 10,000, though some pur<193><207>as ç
like the Matsya mention it as 24,000. Six chapters are entirely  in  prose.  It  probably  took ç
the  present  shape  before  the  tenth century <MS>A.<|>D.<D>
It deals with a number of stories and gives detailed accounts of vratas ç
(religious rites) and t<200>rthas (places of pilgrimage). It also ç
deals with several topics normally dealt with in the dharma·<193>stras ç
such as·r<193>ddha (obsequial rites), pr<193>ya·cittas (expiations), ç
d<193>na (giving gifts), images and their worship, narakas (hells) ç
and so on.
Verses from this work have been extensively quoted in the dharma·<193>stra ç
treatises.
See also <MS>PUR°ØAS<D>.
@NT = Var<193>h<193>vat<193>ra
Var<193>h<193>vat<193>ra (Boar-incarnation) is the third in the series ç
of Da·<193>vat<193>ras of Mahavi<218><207>u in which the Lord killed ç
the demon Hira<207>y<193>k<218>a and lifted the earth out of theflood ç
waters in which it had been submerged.
See also <MS>DA<185>°VAT°RAS<D>.
@NT = V<193>r<193>h<200>
@N1 = (`boar-faced goddess')
Durg<193>sapta·at<200>, the well-known work of the ·akti-cult, describes ç
Saptam<193>t<216>kas (8.13-21), the seven aspects of the Divine Mother, ç
which are the <185>aktis (female forms) of the seven deities like ç
<185>iva, Vi<218><207>u, Brahm<193> and Indra. V<193>r<193>h<200> ç
is counted among them as the fifth. She is the <185>akti of Var<193>h<193>vat<193>ra ç
(Boar-incarnation) of Vi<218><207>u.
She is boar-faced, is dark in complexion and has four or six arms. ç
On the right side she exhibits the varadamudr<193> (bestowal of boons), ç
and holds da<207><195>a (club) as also asi (sword). On the left she ç
shows the abhayamudr<193> (gesture of protection) and carries carma ç
(shield) and p<193>tra (bowl). Her v<193>hana or mount may be either ç
an elephant or a buffalo.
Sometimes, several varieties of V<193>r<193>h<200> such as Mah<193>v<193>r<193>h<200>, ç
Svapna-v<193>r<193>h<200>, Dh<220>mrav<193>r<193>h<200> and so on ç
are mentioned in t<193>ntrik works. They are usually invoked in black ç
magical rites.
See <MS>SAPTAM°T<184>K°S<D>.
@NT = Var<193>hopani<218>ad
This is one of the minor Upani<218>ads belonging to the K<216><218><207>a ç
Yajurveda and assigned to the group of Yoga Upani<218>ads.
It has 263 mantras, mostly in anu<218><219>ubh verses, spread over ç
five chapters. It was taught by Lord Var<193>ha to the sage Bh<216>gu. ç
The last two chapters were taught by the sage <184>bhu to Nid<193>gha.
A brief summary of these may now be presented here:
@S10N = First Chapter (17 verses)
@SPACE1 = 
Pleased by the tapas (austerities) of the sage Bh<216>gu, Lord Var<193>ha ç
(an incarnation of Vi<218><207>u) appears before him and offers any ç
boon he likes. Bh<216>gu asks only for brahmavidy<193> or knowledge ç
of Brahman that liberates.
The Lord, after narrating a long list of tattvas (fundamental principles ç
of creation) advocates that bhakti or devotion to God alone can give ç
mukti or liberation.
@SPACE = 
@S10N = Second Chapter (83 verses)
@SPACE1 = 
The topics discussed in this chapter are: s<193>dhanacatu<218><219>aya ç
(four preliminary disciplines); true nature of the <193>tman as consciousness ç
and bliss; realised soul becoming one with Brahman; he is free from ç
the bondages of karma; meditation on God (Var<193>ha) leads to dissolution ç
of thoughts; other s<193>dhanas leading to brahmabh<193>va or becoming ç
Brahman.
@SPACE = 
@S10N = Third Chapter (30 verses)
@SPACE1 = 
While declaring that Param<193>tman is Sat-cit-<193>nanda (existence-consciousness-bliss), ç
the means of attaining him is bhakti or devotion to him and nothing ç
else. This is stressed here.
@SPACE = 
@S10N = Fourth Chapter (12 paras and 44 verses)
@SPACE1 = 
This is divided into two sections, the Br<193>hma<207>a and the Mantra. ç
It has been taught by the sage <184>bhu to the enquirer Nid<193>gha.
The Br<193>hma<207>a has 12 sections in prose and the Mantra, 44 verses.
The first section describes seven bh<220>mik<193>s or stages of development ç
of wisdomsuch as ·ubhecch<193> (good desire) vic<193>ra<207><193> ç
(inquiry) and so on.
The first three stages are associated with the mumuk<218>u (the seeker). ç
The yogis associated with the fourth, the fifth, the sixth and the ç
seventh are called brahma-vid, brahmavidvara, brahmavidvar<200>y<193>n ç
and brahmavidvari<218><219>ha. They are the four kinds of j<200>vanmuktas ç
(liberated even while living).
The second section gives a detailed description of all the stages. ç
It also describes the characteristics of the j<200>vanmukta. The sages ç
<185>uka and V<193>madeva are projected as j<200>vanmuktas of two ç
types.
@SPACE = 
@S10N = Fifth Chapter (77 verses)
@SPACE = 
This  chapter  deals  with  various aspects of the practice of yoga. ç
Some of them are: the eight a<209>gas or steps of Yoga; bandhas (methods ç
of controlling the pr<193><207>ic energy); cakras (psychic centres); ç
n<193><195><200>s (nerve current passages); japa of pra<207>ava (o<209>k<193>ra) ç
to remove obstacles and quite a few other technical details.
It ends with a phala·ruti, eulogy of the Upani<218>ad, the study and ç
practice of which results in j<200>vanmukti.
@NT = v<193>rakar<200>s
@N1 = (`those who keep fixed times')
Pa<207><195>har<193>pura (or Pa<207><195>harpur) is a well-known and ç
extremely popular place of pilgrimage (in the Maharashtra State). ç
The main deity of this place is Vi<219><219>hala or Vi<219>hob<193> ç
or P<193><207><195>ura<209>ga (a form of Lord K<216><218><207>a).
The pilgrims who visit this temple are of two types: the v<193>rakar<200>s ç
(or v<193>rkar<200>s) and others.
The former visit the temple regularly whereas the latter occasionally.
The v<193>rakar<200>s, again, are of two categories: those who attend ç
every month and those who visit twice a year (on °<218><193><195>ha-·ukla-ek<193>da·<200> ç
[eleventh day of the bright fortnight of the month of °<218><193><195>ha, ç
usually in July] and K<193>rttika-·ukla-ek<193>da·<200>  [eleventh  day  of  the  bright ç
fortnight  of  the  month  of  K<193>rttika, generally in November]).
The v<193>rakar<200>s have to observe certain rules which are binding. ç
They are: carrying a rosary of tulas<200> beads (tulas<200>m<193>l<193>), ç
giving up flesh-eating, observing a fast on ek<193>da·<200> days, ç
carrying a flag of ochre-coloured cloth, to speak the truth and never ç
cheat.
These rules and the very tradition ofthe sect have socially levelled ç
the adherents to a great extent.
Incidentally, it may be mentioned that a similar group of devotees ç
of R<193>ma belonging to the sect of Samartha R<193>mad<193>s, came ç
to be known as dh<193>rakar<200>s.
@NT = V<193>r<193><207>as<200>
See <MS>K°<185>®<D>.
@NT = Vararuci
There seem to be quite a few persons of this name.
The <185>rautas<220>tras of Gobhila was also known as the Pu<218>pas<220>tras. ç
According to some scholars, it had a South Indian recension known ç
as Phulus<220>tras, attri-buted to Vararuci, either as the author ç
or as the editor.
There was one Vararuci among the `Navaratnas' (or Nine Jewels), well-known ç
scholars, in the court of the king Vikram<193>- ditya.
K<193>ty<193>yana, the grammarian who composed the v<193>rttika ç
(explanatory notes) on the sutras of P<193><207>ini (4th century <MS>B.C.<D>?) ç
was also known as Vararuci.
The earliest grammar of the Pr<193>k<216>t language, the Pr<193>k<216>taprak<193>·a, ç
was the work of a Vararuci.
However very little is known about these Vararucis.
@NT = Varavaramuni
Ma<207>av<193><202>a M<193>muni (<MS>A.<|>D.<D> 1370-1443) was also ç
known as Varavaramuni. See <MS>MAØAV°<170>A M°MUNI<D> and <MS><185>R®VAI<186>ØVISM<D>.
@NT = Vardham<193>na Mah<193>v<200>ra
@N1 = (599-527 <MS>B.<|>C.<D>)
Jainism, one of the great religions of the world, considers 24 T<200>rtha<209>karas ç
(holy men) as its founders. Of them the last two†P<193>r·van<193>tha ç
(circa 800 <MS>B.<|>C.<D>) and Vardham<193>na Mah<193>v<200>ra (599-527 ç
<MS>B.<|>C.<D>)†are historical personalities.
Vardham<193>na Mah<193>v<200>ra was born at Vai·<193>l<200> (identified ç
with the village Basarh in the Muzaffarpur district of Bihar) to the ç
king Siddh<193>rtha and the queen Tri·al<193>. During his early years, ç
he got good education including the use of weapons of war. He led ç
a pure life and served hisparents well. In his 30th year, he renounced ç
the world and started practising severe austerities, to realise the ç
Truth. He attained enlightenment in his 42nd year. Thereafter, he ç
roamed about the country†mostly in the Bihar area† preaching his doctrines ç
and making disciples. He passed away in his 72nd year at P<193>v<193> ç
(the modern town of P<193>v<193>pur<200> near Patna).
It was he who started the sect of Nirgranthas (those who are free ç
from all fetters), same as Digambaras.
To the four supreme commands of P<193>r·van<193>tha, he added a fifth. ç
These five are: ahi<221>s<193> (non-injury); satya (truth); asteya ç
(non-stealing); aparigraha (non- acceptance of gifts); and brahmacarya ç
(celibacy).
His  chief  contribution  was  the popularisation of the principle ç
of ahi<221>s<193>. On its basis he elaborated an ethical code for ç
householders and monks. By peaceful proselytisation, he admitted all ç
aspirants irrespective of caste or sex. In his 30 years of ministration ç
he had won a large number of followers, both monks and householders.
He also left behind a well-organised religious Order, through the ç
efforts of which ahi<221>s<193> became firmly established as a rule ç
of life, even among those who did not join his Order. His followers ç
gradually spread all over the country.
According to his philosophy it is Karma, which is the deed of the ç
soul, that is responsible for bondage. It is a material forming a ç
subtle bond of extremely refined k<193>rmic matter which keeps the ç
soul confined. It is by purging the soul of this Karma, by following ç
the commandments, that one can get liberation.
Vardham<193>na Mah<193>v<200>ra was a senior contemporary of Buddha ç
(557-477 <MS>B.<|>C.<D>).
See also <MS>JAINISM<D> and <MS>P°R<185>VAN°THA<D>.
@NT = v<193>ris<193>ra
See <MS>ANTARDHAUTI<D>.
@NT = Varivasy<193>rahasya
@N1 = (`secret of up<193>san<193> or meditation')
This is a short but well-known work of the <185><193>kta school of ç
the tantras. It was composed by Bh<193>skarar<193>ya Makhin (17th-18th ç
Century). It has 167 k<193>rik<193>s (brief sentences) divided into ç
two a<221>·as or sections (53<|>+<|>114<|>=<|>167). The author himself ç
has written a detailed gloss on it.
The work expounds in detail the philosophy behind the <185>r<200>cakra ç
and the Pa<210>cada·<193>k<218>ar<200> mantra by connecting them with ç
the various tattvas or principles taught in the tantras.
It is an esoteric and a highly complicated work.
See <MS>PA<178>CADA<185>°K<186>AR®MANTRA<D> and <MS><185>R®CAKRA<D>.
@SPACE = 
@NT = Var<207>a
@SPACE = 
The ancient Hindu scriptures have divided the society into four var<207>as ç
or groups viz., br<193>hma<207>as, k<218>attriyas, vai·yas and ·<220>dras.
This division was based upon the allocation of duties and responsibilities ç
as per their nature and nurture. (Bhagavad-g<200>t<193> 18.41-44).
The br<193>hma<207>as were the custodians of knowledge. They had to ç
learn and teach, not only spiritual wisdom, but also other branches ç
of sciences, and arts. They were priests, preceptors and preachers. ç
Being the custodians of the intellectual and spiritual heritage of ç
the race, they had to guide the rulers of the land, expound and administer ç
laws as also assist in carrying out the legislative policies.
The k<218>attriyas governed the State and performed its executive ç
functions. It was their duty as custodians of social power, to protect ç
the society from external aggression and maintain internal law and ç
order.
The vai·yas generated and wielded economic power through agriculture, ç
trade, dairy-farming and manufacture of goods.
The ·<220>dras who were not capable of independent judgement or initiative ç
on anadequate scale, merely assisted in the discharge of essential ç
functions by contributing manual labour.
In national calamities or emergencies change of work was permitted.
The  var<207>a  system  gradually  got fossilised into the j<193>ti ç
(caste) system.
The word var<207>a has two more senses: colour and letter of the alphabet.
See also <MS>CASTE SYSTEM<D>.
@NT = var<207>asa<209>kara
@N1 = (`intermixing of var<207>as or castes')
Though the leaders of the Hindu society, especially the king and the ç
br<193>hma<207>as,  were  very  particular  in preserving the purity ç
of the var<207>a system, mixing up did take place giving rise to several ç
subcastes and their offshoots. This mixing up (i.e., a person of one ç
var<207>a marrying a person of another var<207>a and having children ç
by that union) was called var<207>asa<209>kara or intermixing of var<207>as. ç
This was considered bad for the society. Though anuloma marriages ç
were tolerated and pratiloma marriages (See <MS>ANULOMA<D>.) were ç
frowned upon, var<207>asa<209>kara could not be prevented. Even by ç
the time of the Mah<193>bh<193>rata var<207>asa<209>kara had already ç
taken place to a large extent.
It was the duty of the king to see that purity of the var<207>a-<193>·rama-dharma ç
(or system) was kept up and punishment awarded  to  the  transgressors  (vide ç
Gautama Dharmas<220>tras 11.9 and 10).
@NT = var<207><193>·ramadharma
@N1 = (`duties of var<207>as and <193>·ramas')
In the ancient and medieval Hindu scriptures as also religious treatises, ç
theword `dharma' is generally interpreted as  var<207>a-<193>·rama-dharma,  duties  and ç
responsibilities of the various var<207>as and <193>·ramas. See <MS>VARØA<D> ç
and <MS>°<185>RAMA<D> for details.
@NT = V<193>r<218>aga<207>ya
The S<193><209>khya Dar·ana or S<193><209>khya philosophy, one of ç
the six well-known Hindu philosophical systems, is based on the S<193><209>khyak<193>rik<193> ç
of ®·varak<216><218><207>a (5th century <MS>A.<|>D.<D>). However, this ç
systematic treatise and others of a similar nature are said to have ç
been modelled on an earlier work called <186>a<218><219>itantra ç
(philosophy of sixty basic principles) attributed to V<193>r<218>aga<207>ya ç
who probably lived sometime during the period <MS>A.<|>D.<D> 100-300. ç
Whether he was its author or had only compiled it from various earlier ç
sources, is not known.
Practically nothing has been dis- covered about his life and works.
@NT = v<193>rtt<193>
@N1 = (`means of living')
The Hindu tradition divides the ·<193>stras†authoritative texts of ç
religion and culture†into four broad groups: tray<200> (the Vedas), ç
<193>nv<200>k<218>ik<200> (logic), v<193>rtt<193> (economics and politics) ç
and da<207><195>an<200>ti (statecraft).
V<193>rtt<193>, the third, is directly related to the production and ç
distribution of wealth. It is specially assigned to the vai·yas and ç
they are to be trained to become experts in it.
The following are the occupations listed under it: agriculture, rearing ç
of cattle, trade, mining and any other vocation that produces wealth ç
and goods.
@NT = Varu<207>a
Varu<207>a `the one who encompasses the whole world,' is one of the ç
oldest Vedic deities. Maybe he is the personification of the sky; ç
but he is also associated with clouds and water, rivers and ocean. ç
He is sometimes clubbed with Mitra and praised (Mitr<193>varu<207>a).
Varu<207>a is the king of the universe and lives in the highest world. ç
His knowledge and power are unlimited. He has thousand eyes and oversees ç
the whole world. Hence he is the lord of the moral law. He punishes ç
those who transgress this law but forgives them out of compassion ç
if they repent and pray. By activating V<193>yu, the lord of the wind, ç
he sustains life by giving rain and crops.
Though Varu<207>a was the chief deity in the beginning, he seems to ç
have yielded his place later on to Indra and Praj<193>pati.
In  the  subsequent  mythological literature Varu<207>a is described ç
as the presiding deity of the western quarter and as the lord of oceans, ç
water and aquatic animals. In some of the temples he is depicted as ç
riding on a crocodile. In two of his four arms he holds the serpent ç
and the noose (p<193>·a). Sometimes he is pictured as riding a chariot ç
drawn by seven swans and holding the lotus, the noose, the conch and ç
a vessel of gems in the four hands. There is an umbrella over his ç
head.
@NT = varu<207>ak<216>cchra
@SPACE1 = 
See <MS>JALAK<184>CCHRA<D>.
@SPACE = 
@NT = Varu<207>apragh<193>sa
@SPACE = 
This is one of the Vedic sacrifices listed under the C<193>turm<193>sya ç
group.
Varu<207>a is the chief deity to whom yavas (barley grains) are offered.
It needs two <193>havan<200>ya fires. Apart from the four chief priests, ç
there will be a fifth one, pratiprasth<193>t<216>, an assistant to ç
the adhvaryu.
Offering materials are mainly yava and rice. Two figurines†one of ç
a ram and the other of an ewe†prepared out of barley flour, are also ç
offered into the fire.
Vi<218><207>ukrama†four steps with appropriate mantras taken by the ç
sacrificer†is an important part of this rite.
@SPACE = 
@NT = V<193>ru<207><200>
@SPACE1 = 
V<193>ru<207><200> means liquor or an intoxicating drink. Hence, V<193>ru<207><200> ç
represents the goddess that presides over it.
V<193>ru<207><200> is also the name of one of the queens of the deity ç
Varu<207>a. She is known as Gaur<200> too.
The deity V<193>ru<207><200>, also known by other names such as Am<216>te·var<200> ç
and Sudh<193>m<193>lin<200>, is described by the works on iconography ç
as a goddess with four arms holding a cup of liquor, a bowl of cooked ç
meat, a bejewelled jar and a blue lotus. She is surrounded by a host ç
of ·aktis or feminine spirits.
As an associate of the goddess Lalit<193> she is described as the ç
controller of the fleet of boats.
@NT = v<193>san<193>
@N1 = (`[a strong impression] that lives in the mind')
@SPACE = 
@SPACE = 
The word v<193>san<193> is generally interpreted as sa<221>sk<193>ra, ç
a strong impression in the mind, carried over from previous lives. ç
It is so strong that, when it arises in the mind, a person is forced ç
to act without thinking of the consequences.
It is classified into two kinds, malin<193> (impure) and ·uddh<193> ç
(pure). The former leads to the bondage of transmigration whereas ç
the latter helps in getting liberation.
The malinav<193>san<193>, again, is of three kinds: lokav<193>san<193> ç
(desire to please others); ·<193>strav<193>san<193> (desire for dry ç
intellectual knowledge); dehav<193>san<193> (desire to keep the body ç
healthy and beautiful).
All these three v<193>san<193>s have to be eschewed.
As for the ·uddhav<193>san<193>s, there is no particular way of classification. ç
Some of the disciplines or qualities listed under these, which help ç
to eradicate the evil v<193>san<193>s are: maitr<200> (friendship), ç
karu<207><193> (compassion), mudita (feeling happy in the happiness ç
of others) and upek<218><193> (indifference towards the sinners) (vide ç
Yogas<220>tras 1.33).
The twenty-six qualities like abhaya (fearlessness), dama (self-control), ç
sv<193>dhy<193>ya (study of the holy scriptures), tapas (austerities), ç
ahi<221>s<193> (non-violence) and <193>rjava (straightforwardness) ç
described in the Bhagavadg<200>t<193> (16.1-3) also help in creating ç
·uddhav<193>san<193>s.
The natural qualities of greatness of a perfect being described in ç
the second, twelfth and fourteenth chapters of the Bhagavadg<200>t<193>, ç
if practised as modes of s<193>dhana, will lead to the production ç
of pure v<193>san<193>s that ultimately lead to liberation.
@NT = Vasantapa<210>cam<200>
 Vasantapa<210>cam<200> (M<193>gha-·ukla-pa<210>cam<200>, the 5th ç
day of the bright fortnight of the month of M<193>gha, usually in ç
February) is a day dedicated to the worship of Sarasvat<200>, the ç
goddess of learning and fine-arts. The worship is done to clay image ç
and then immersed in a river or a tank. It is an extremely popular ç
festival  in  Bengal,  especially  among students.
Vasantapa<210>cam<200> is also called <185>r<200>pa<210>cam<200>, ç
<185>r<200> being Sarasvat<200>.
@NT = Vasantar<193>ja-·akuna
@N1 = (`Vasantar<193>ja's [treatise on] prognosticatory signs')
People of all countries and civilisations have believed in prognosticatory ç
signs from times immemorial. Such beliefs persist even now.
The Sanskrit word for such a pro-gnostication is ·akuna (See <MS><185>AKUNA<D> ç
for details.)
Though the literature on the ·akunas is quite extensive, mostly spread ç
over the pur<193><207>as, there are also works which deal with this ç
subject in a specialised way. Outof these, the Vasantar<193>ja·akuna ç
of Vasantar<193>ja (circa <MS>A.<|>D.<D> 900) is an independent and ç
exhaustive work on this subject. It contains 1520 verses in 20 vargas ç
or chapters. It has a commentary by Bh<193>nucandraga<207>i (16th ç
century <MS>A.<|>D.<D>).
Vasantar<193>ja was the son of Vijaya-r<193>jabha<219><219>a  and  Sarasvat<200>.  He  was ç
honoured by the king Candradeva of Mithil<193> and wrote this work ç
at his request. He mentions several works of an earlier period and ç
pays his respects to many of the ancient sages like Atri, Vasi<218><219>ha ç
and Vy<193>sa who had declared the knowledge of the ·akunas.
The following is a brief account of the subjects dealt with: authenticity ç
of the ·akuna·<193>stra; honouring the guru and the eight lokap<193>las ç
like Indra; on directions and distances of factors associated with·akunas; ç
signs of auspiciousness or otherwise, as applied to men and women; ç
on birds and their chirpings; signs as applied to animals; barking ç
of dogs and howling of jackals; importance of this ·<193>stra or science.
A notable feature of this work is that 781 verses†more than half†have ç
been devoted to the sounds of birds.
@NT = Vasi<218><219>ha
Vasi<218><219>ha is one of the most well-known sages, mentioned several ç
times even in the <184>gveda (vide 7.33.14).
According to one version he was one of the m<193>nasaputras or mind-born ç
sons of the creator Brahm<193>. According to another version, he was ç
born in a kumbha (or pot) as the son of the deity Varu<207>a. Agastya, ç
another great sage, was his twin.
Arundhat<200>†also known as Ak<218>am<193>l<193> and <188>rj<193>†was ç
his wife. The sage <185>akti was his son. Sages Par<193>·ara and Vy<193>sa ç
were his grandson and great-grandson respectively.
He was the r<193>jaguru†royal preceptor †to the kings of the Ik<218>v<193>ku ç
race.
There are several legends eulogising his greatness.
The king Vi·varatha, son of G<193>dhi, tried his best to take away ç
by force the divine cow Nandin<200> from Vasi<218><219>ha but failed ç
miserably. After several rounds of tapas, he too became a brahmar<218>i ç
(a sage of the highest order), later on known as Vi·v<193>mitra.
Vasi<218><219>ha  was  one  among  the Saptar<218>is (the seven divine ç
sages) and also a gotrapravartaka (person who started a gotra or lineage).
@SPACE = 
@NT = Vasi<218><219>ha Dharmas<220>tras
@SPACE = 
Belonging to the period 300-100 <MS>B.<|>C.<D>, the Vasi<218><219>ha ç
Dharmas<220>tras is a fairly ancient work. Though assigned to the ç
Kalpas<220>tra group of the <184>gveda there is no specific proof ç
to conclusively prove it.
One of the printed editions considered as a standard publication contains ç
30chapters. Only one commentary†the Vidvanmodin<200> by Yaj<210>asv<193>min†is ç
available.
The contents may be briefly summed up as follows: definition of dharma; ç
limits of °ry<193>varta; sins and sinners; six forms of marriage; ç
the four var<207>as; <193>tat<193>yins or criminals; duties common ç
to all var<207>as; the four <193>·ramas and the duties pertaining ç
to them; on Vedic studies; permitted and forbidden food; rules of ç
adoption; the king and administration of justice; on partition of ç
property; pratiloma castes; certain pr<193>ya·cittas or expiations; ç
virtues of pr<193><207><193>y<193>ma and G<193>yatr<200>mantra as ç
puri- fiers; eulogy of Vedic mantras; eulogy of dharma.
The work refers to several verses of the <184>gveda. Other dharma·<193>stra ç
works like the Mit<193>k<218>ar<193> on Y<193>j<210>avalkya Sm<216>ti ç
by Vij<210><193>ne·vara (<MS>A.<|>D.<D> 1100) quote from this work. ç
It has many things in common with the dharmas<220>tras of Baudh<193>yana ç
and Gautama.
@NT = V<193>si<218><219>ha R<193>m<193>ya<207>a
See <MS>YOGAV°SI<186><187>HA<D>.
@NT = vasordh<193>r<193>
@N1 = (`flow of wealth')
Agnicayana (`piling the fire') is an important aspect of Somay<193>ga, ç
involving quite a few rites. Vasordh<193>r<193> is one of them. It ç
is the name of the whole rite in which several hundred offerings of ç
<193>jya (ghee) are made with a sruc (spoon of udumbara tree) which ç
too is cast into the consecrated fire at the end. The purpose is to ç
secure all the powers of the deity Agni for the sacrificer.
The mantras used are mostly from the Taittir<200>ya and the V<193>jasaney<200> ç
Sa<221>hit<193>s.
@NT = vastradhauti
@N1 = (`cleansing with cloth')
See <MS>H<184>DDHAUTI<D>.
@NT = V<193>stupuru<218>a
@N1 = (`personified deity of the <R>ç
site')
V<193>stu is the layout of a building site. Before constructing a ç
building there, the land has to be reclaimed from the gods and goblins ç
who might be living there for aeons. This ritual of pacification is ç
known as v<193>stu·amana. Generally a ma<207><195>ala (geometrical ç
drawing), a square divided into 9 x 9 (= 81) or 8 x 8 (= 64) smaller ç
squares is used for this purpose. This is called v<193>stuma<207><195>ala.
There  is  an  interesting  legend connected with this ma<207><195>ala. ç
When <185>iva fought with the demon Andhaka, a drop of sweat fell ç
from his forehead on the earth. It assumed the form of a fierce demon ç
who attempted to devour the worlds. Then all the gods and spirits ç
rushed towards him, felled him to the ground (face downwards) and ç
pinned him there, all of them being stationed on him. The v<193>stuma<207><195>ala ç
contains him with his head in the direction north-east, and, with ç
his hands and legs folded. He is now called V<193>stupuru<218>a.
@SPACE = 
@SPACE = 
If he, as also the gods on him are propitiated, the building will ç
be firm and safe.
@NT = v<193>stu·<193>nti
When a new house is built, certain religious rites are performed before ç
entering it. One of them is v<193>stu·<193>nti or v<193>stu·amana.
Rice and barley grains are put into a pot of water. A piece of gold ç
is also deposited into it. The owner now goes round the house three ç
times sprinkling this water on the house, repeating the ·<193>nt<193>t<200>ya ç
hymn of the <184>gveda (7.35). It is repeated three more times by ç
pouring the water continuously, chanting three more mantras of the ç
<184>gveda (10.9.1-3).
This is followed by a homa with <193>jya (ghee) using the <184>gvedic ç
mantras `v<193>sto<218>pate......' (8.17.14).
Preparing food and honouring the br<193>hma<207>as after feeding them ç
is the last part of the ritual.
Some authorities prescribe that this rite can be repeated every month ç
or in every season or every year.
See also <MS>G<184>HAPRAVE<185>A<D>.
@NT = V<193>sudeva
See <MS>VI<186>ØU<D>.
@NT = V<193>sudevopani<218>ad
This is a minor upani<218>ad belonging to the S<193>maveda group.
It is a short work in the form of a dialogue between the sage N<193>rada ç
and Lord V<193>sudeva, mostly in the anu<218><219>ubh metre interspersed ç
with prose sentences.
The main theme is how to prepare and wear the tripu<207><195>ra mark ç
with the yellow clay called gop<200>candana, on different parts of ç
the body.
Parts of the body on which the tripu<207><195>ra has to be inscribed ç
are: forehead, neck, arms and the chest. A sa<221>ny<193>sin, in addition, ç
has to wear it on the top of the shaven head also.
Various Vedic mantras as also the Pra<207>ava (O<209>k<193>ra) are ç
to be used while marking.
@NT = V<193>suki
V<193>suki is one of the eight well-known serpents of paur<193><207>ic ç
celebrity. N<193>gar<193>ja and N<193>gendra are his other names.
He was an offspring of Ka·yapa and Kadr<220>. He is described as one ç
of the seven dragons holding the earth on his hoods.
He was used as a rope wound round the mountain Mandara at the time ç
of churning the milky ocean.
<185>ata·<200>r<218><193> was his wife and Jaratk<193>ru was his sister.
V<193>suki is also, sometimes, described as one of the dikp<193>las ç
(guardians of directions) presiding over the downward direction.
@NT = Vasus
See <MS>A<186><187>AVASUS<D>.
@NT = V<193>t<193>pi
See <MS>ILVALA<D>.
@NT = Va<219>as<193>vitr<200>vrata
The  story  of  S<193>vitr<200>,  the  very embodiment of all the ç
grand wifely virtues like chastity and extreme devotion to the husband, ç
is well-known in all the Hindu homes. Her memory has been cherished ç
for ages by the women of India as an ideal of a pativrat<193> (of ç
wifely devotion to husband). The Va<219>as<193>vitr<200>-vrata has ç
its origin in her legend.
This vrata that is now in vogue must have been in existence long before ç
the 10th century <MS>A.<|>D.<D> The main features of this vrata, observed ç
by suma<209>gal<200>s or married women (whose husbands are alive) ç
are: sa<209>kalpa or resolve, worshipping a va<219>a tree (banyan ç
tree) with several upac<193>ras, worship to S<193>vitr<200> (either ç
in image or mentally), worship of Yama and N<193>rada and giving presents ç
to the priest. The fast is broken the next day.
Satyav<193>n, the husband of S<193>vitr<200>, took the support of ç
a branch of the va<219>a tree, then lay down under it and died. S<193>vitr<200> ç
who sat with his head on her lap under that tree, accompanied Yama, ç
the lord of death, all the way and succeeded in bringing back her ç
husband to life, which again was under the same tree. Hence the importance ç
of the va<219>a tree, worship to it and the naming of the vrata itself ç
after it.
@SPACE = 
@NT = v<193>tsalyabh<193>va
@SPACE1 = 
This is one of the several types of bhakti or devotion. It is the ç
love of a devotee towards God as that of a mother towards her child. ç
Ya·od<193>'s love for the child K<216><218><207>a and Kausaly<193>'s ç
towards the child R<193>ma are classic examples.
The love of a devotee towards God as that of a child towards its mother ç
can also be grouped under this category. R<193>mak<216><218><207>a ç
Paramaha<221>sa (<MS>A.<|>D.<D> 1836-1886) retained this attitude towards ç
Mother K<193>l<200> till the end.
@NT = V<193>tsy<193>yana
@SPACE1 = 
See <MS>K°MA<185>°STRA<D>.
@SPACE = 
@NT = V<193>tula·uddh<193>gama
@SPACE = 
The °gamas are subsidiary scriptures deemed as apauru<218>eya (not ç
man-made but revealed by God Himself) by their votaries.
They are classified into three maingroups: <185>aiv<193>gamas, <185><193>kt<193>gamas ç
or Tantras and Vai<218><207>av<193>gamas.
There are 28 <185>aiv<193>gamas considered pradh<193>na (main) and ç
225 as up<193>gamas (secondary).
The V<193>tula·uddh<193>gama is classified among the 18 <185>aiv<193>gamas ç
known as Rudrabheda.
The work has 778 verses distributed among ten pa<219>alas or chapters. ç
It is in the form of a dialogue between Skanda (Subrahma<207>ya) and ç
his father <185>iva.
Sometimes eleven additional chapters are added as an anubandha or ç
appendix.
There is an old commentary in Sanskrit but it is incomplete.
One Malla<207><207>a of Gubbi (in the Karnataka State) wrote a detailed ç
commentary in Kannada in <MS>A.<|>D.<D> 1475.
A brief account of the work may now be given.
@S10N = 1.	Tattvabhedapa<219>ala (150 verses)
Tattva  or  the  highest  truth  is classified into three types: <185>iva, ç
Sad<193>·iva and Mahe·a. <185>ivatattva is ni<218>kala (without parts). ç
Sad<193>·ivatattva is ni<218>kala and sakala, hence has both parts ç
and is partless. Mahe·atattva is sakala (with parts).
After describing their characteristics, the five ·aktis or powers ç
that evolve out of <185>iva, viz, par<193> (the highest), <193>di ç
(primeval), icch<193> (volition), j<210><193>na (know-ledge) and kriy<193> ç
(action) are recounted.
This is followed by a detailed account of s<216><218><219>i or creation.
There is also a description of the various l<200>l<193>m<220>rtis ç
or forms of <185>iva such as Somadh<193>r<200>, Bhik<218><193><219>anam<220>rti, ç
K<193>m<193>ri and those of the <185>aktis (goddesses) such as Um<193>, ç
Ambik<193>, ®·var<200>, Manonman<200> and others.
@S10N = 2.	Var<207>abheda Pa<219>ala (81 verses)
Hara (<185>iva or God) is <185>abdabrahma. He is the personification ç
of all sounds and var<207>as (letters of the alphabet) which form ç
his body. Details of these var<207>as are given in the rest of the ç
chapter, along with the deities that preside over them, which knowledge ç
is necessary to understand the mantras properly.
@S10N = 3.	Cakrabheda Pa<219>ala (42 verses)
Cakras  are  geometrical  figures representing certain deities. If ç
properly drawn, they will exude the power of the respective deity. ç
This chapter deals with all the details connected with the cakras ç
such as a suitable place to draw them, their proportion and methods ç
of drawing, details of petals and circles, colours to be used, placement ç
of deities and so on.
Worship of properly drawn cakras can fulfil all desires.
@S10N = 4.	Vargabheda Pa<219>ala (46 verses)
It begins with a classification of the var<207>as or letters of the ç
alphabet into several vargas or groups. This is followed by some details ç
regarding mantras and b<200>jas (seed-letters).
@S10N = 5.	Mantrabheda Pa<219>ala (107 verses)
The origin and nature of mantras, their meaning and utility are described ç
here. Some ritualistic details like the making of a ma<207><195>apa ç
and drawing of the cakras (geometrical figures) as also the placement ç
of b<200>j<193>k<218>aras are given.
Then there is a detailed description of certain mantras of <185>iva, ç
called pr<193>s<193>da mantras, their varieties and uses.
@S10N = 6.	Pra<207>avabheda Pa<219>ala (27 verses)
This short section deals mainly with Pra<207>ava or O<209>k<193>ra, ç
its nature, method of meditation and the associated deities.
This is followed by a delineation of its pa<210>cabhedas or five varieties.
@S10N = 7.	Brahmabheda Pa<219>ala (76 verses)
@EMERGENCY = This deals with 25 aspects of Sakala-Brahman (with attributes) ç
and five more of Ni<218>kala-Brahman (without attributes). The latter ç
are: Sadyoj<193>ta, V<193>madeva, Aghora,  Tatpuru<218>a  and  ®·vara.  Their ç
relation with Pra<207>ava (O<209>k<193>ra) and modes of meditation ç
are also discussed.
@S10N = 8.	A<209>gabheda Pa<219>ala (104 verses)
@EMERGENCY = The a<209>gas or limbs of the body are divided into six ç
groups: ·iv<193><209>ga, bh<220>t<193><209>ga, k<220><219><193><209>ga, ç
vidy<193><209>ga, ·aktya<209>ga and s<193>m<193>ny<193><209>ga. The ç
mantras associated with them are described in detail.
@S10N = 9.	Mantraj<193>ta Pa<219>ala (82 verses)
@EMERGENCY = After declaring that <185>ivali<209>ga is mantramaya ç
(consisting of mantras), 19 varieties of mantran<193>mas or mantras ç
of <185>iva, with different names such as atib<193>la, sab<193>la ç
and kaum<193>ra are described.
@S10N = 10.	Mantrak<200>la Pa<219>ala (63 verses)
@EMERGENCY = This chapter deals with the mantras to be adopted as ç
also the ones to be rejected, the right way of pronouncing them, the ç
nature of mantras and other topics connected with rituals.
@EMERGENCY = Most of the printed texts add a long appendix comprising ç
eleven topics that include the following:
@EMERGENCY = Pr<193>ya·cittas (expiations); ceremonial preparation ç
of pa<210>cagavya (five products derived from a cow); homa; celebration ç
of the festival of <185>iva in a temple; method of establishing the ç
<185>ivali<209>ga; rites associated with it or with other deities ç
like Ga<207>apati or Vi<218><207>u or Dev<200> to be performed for ç
one to nine nights.
These are taken from various other works.
@NT = V<193>yu
V<193>yu or air is one of the pa<210>cabh<220>tas or five basic elements ç
of the world. V<193>yu is also the presiding deity over it and is ç
said to be dikp<193>laka (lord of the quarters) ruling in the direction ç
of north-west.
Hanum<193>n and Bh<200>ma were born due to his grace.
V<193>yu as vital air acts inside the body as five major pr<193><207>as ç
and five subsidiary pr<193><207>as (upapr<193><207>as).
Iconographical works describe him as white or ash-grey in complexion. ç
He has two hands carrying a bow and an arrow. He rides on a deer.
Some works describe him as having four arms holding a banner (dhvaja) ç
with two and a water-pot in the third, the last hand showing varadamudr<193> ç
(gesture of giving boons).
Sometimes the four hands are shown as holding p<193>·a (noose), a<209>ku·a ç
(goad), kamala (lotus) and da<207><195>a (cudgel).
V<193>yu's palace is called Gandhavat<200>.
@NT = V<193>yupur<193><207>a
The contribution of the pur<193><207>as tothe growth of popular Hinduism ç
is significant. Even the treatises and digests of dharma·<193>stras ç
have quoted profusely from them. One such pur<193><207>a, classed ç
among the 18 Mah<193>pur<193><207>as is the V<193>yupur<193><207>a ç
or V<193>yav<200>yapur<193><207>a.
It has two kha<207><195>as or sections. The P<220>rvakha<207><195>a ç
(first part) has 61 adhy<193>yas (chapters) and the Uttarakha<207><195>a ç
(second part) has 50 adhy<193>yas. The total number of verses comes ç
to about 12,000.
This pur<193><207>a was first taught by the deity V<193>yu to the ç
sage Vai·amp<193>yana. It was later narrated by the S<220>tapaur<193><207>ika, ç
known as Lomahar<218>a<207>a, to the sages <185>aunaka and others ç
who were engaged in the performance of a Sattray<193>ga in the Naimi<218><193>ra<207>ya ç
forest.
The contents of this pur<193><207>a can be summarised as follows:
On creation; var<207>as and <193>·ramas; yoga; description of Pra<207>ava ç
or O<209>k<193>ra; lineages of sages; the four yugas; some geographical ç
details of Jamb<220>dv<200>pa (where Bh<193>ratavar<218>a or greater ç
India is situated); various regions of the created world; churning ç
of the milky ocean; manifestation of <185>iva as li<209>ga; stories ç
of Vedavy<193>sa and his disciples; ·r<193>ddhas or obsequial rites, ç
speciality of ·r<193>ddha done at Gay<193>; some sages and kings; ç
greatness of Lord Vi<218><207>u and his incarnations; description ç
of the fourteen worlds; greatness and importance of this pur<193><207>a.
See also <MS>PUR°ØAS<D>.
@SPACE = 
@NT = ved<193>dhyayana
@N1 = (`learning and studying the Vedas')
@SPACE = 
Since the Vedas are considered holy scriptures, their study has acquired ç
a religious character.
