Apart from these works mentioned here, there are several other treatises ç
and tracts on the various aspects of Ved<193>nta as interpreted by ç
the numerous schools.
@SB8.5 = Conclusion
There is no gainsaying the fact that the  Ved<193>nta  system  based  chiefly  on ç
the  Brahmas<220>tras†which  itself  is  a systematic exposition ç
of the philosophy of the Upani<218>ads†has influenced all the important ç
aspects of Hindu religion andculture, including the modern Hindu ç
movements.
@NT = Ved<193>nta De·ika
@N1 = (<MS>A.<|>D.<D> 1268-1369)
Next to R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137), Ved<193>nta De·ika ç
was the chief architect who established the Vi·i<218><219><193>dvaita ç
Ved<193>nta on a firm foundation and shaped the <185>r<200>vai<218><207>ava ç
cult into a well-knit movement.
He was born at K<193><210>c<200>puram (in Tamil Nadu) as the only ç
son of Anantas<220>ri and Tot<193>ramma by the grace of Lord Ve<209>ka<219>e·vara ç
of Tirupati. Hence he was named Ve<209>ka<219>an<193>tha.
He had an excellent education under his uncle, °treya R<193>m<193>nuja ç
and became an erudite scholar even by the age of twenty one.
He was married to Tiruma<209>gai whoproved to be an ideal wife, fully ç
co- operating with the husband in his spiritual aspirations.
Throughout his life Ved<193>nta De·ika worked hard and vigorously ç
to propagate R<193>m<193>nuja's philosophy and religion (<185>r<200>vai<218><207>avism) ç
through discourses, disputations with other schools and writing books. ç
He was a prolific writer, whose writings exceed a hundred treatises ç
and compositions.
He toured the country extensively especially visiting the places connected ç
with Vai<218><207>avism.
He was the °c<193>rya of the pontifical seat at K<193><210>c<200>puram, ç
one of the 74 established by R<193>m<193>nuja.
His very goodness and greatness created enemies for him as it has ç
happened in the case of many a great man. However, by the very dint ç
of that greatness he could vanquish them all.
Apart from his erudition in the scriptures, he was also a great poet ç
and dramatist. He had perfect command over the Tamil language also ç
and had mastered the Prabandham literature of the °<202>v<193>rs.
The following are a few of his more well-known works:
@NID = <+><+>Arthapa<210>caka; Day<193>·ataka; <R>ç
<+><+>Drami<195>opani<218>ats<193>ra; Ha<221>sasande·a;<R>ç
<+><+>®·opani<218>adbh<193><218>ya; P<193>duk<193>sahasra;<R>ç
<+><+>Rahasyatrayas<193>ra; Sa<209>kalpas<220>ryodaya;<R>ç
<+><+><185>atad<220><218>a<207><200>; Subh<193><218>itan<200>v<200>;<R>ç
<+><+>T<193>tparyacandrik<193>; Tattvamukt<193>kal<193>pa.
@SPACE1 = 
His son Varadan<193>tha proved worthy of the father by his life and ç
scholarship.
The Parak<193>la Ma<219>ha, one of the important monasteries of the ç
<185>r<200>vai<218><207>ava school, was established by Brahmatantra ç
Svatantra J<200>yar (<MS>A.<|>D.<D> 1286-1386), a sa<221>ny<193>sin ç
disciple of Ved<193>nta De·ika, under his inspiration.
See also <MS><185>R®VAI<186>ØAVISM<D>.
@NT = Ved<193>ntas<220>tras
See <MS>BRAHMAS<188>TRAS.<D>
@NT = Ved<193>rambha
@N1 = (`beginning [the first study] of the Vedas')
In the most ancient days, the study of the Vedas commenced just after ç
the upanayana ceremony. However, as the study of the Vedas was relegated ç
to the background due to the rise of the non-Vedic literature and ç
its study, a new sa<221>sk<193>ra or sacrament called Ved<193>rambha ç
was  introduced  after  upanayana  and before sam<193>vartana (See ç
<MS>UPANAYANA<D> and <MS>SAM°VARTANA<D> for details.). This was to ç
be done if the brahmac<193>rin wished to study the Vedas also.
This simple ceremony consisted of the following steps: °bhyudayika·r<193>ddha ç
or N<193>nd<200>·r<193>ddha; establishing the laukik<193>gni (domestic ç
fire); offerings of ghee into the fire; gifts to the officiating br<193>hma<207>a.
The pattern of offerings was as follows:
@SPACE = 
@SPACE1 = 
@Z_TBL_BEG = COLUMNS(2), DIMENSION(IN), COLWIDTHS(1.3333,E1), BELOW(.0695), ç
KEEP(OFF)
@Z_TBL_BODY = TC2M, TC2M
To begin the<R>ç
study of, Deity
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT
<184>gveda, Bh<220> (earth) and Agni
Yajurveda, Antarik<218>a (space)<R>ç
and V<193>yu
S<193>maveda, Dyaus (heaven)<R>ç
and S<220>rya or °ditya
Atharvaveda, Di·a<199> (quarters)<R>ç
and Candra or Soma
@Z_TBL_END = 
Two offerings of ghee were made to the deities.
This was followed by homa (domestic fire ritual) to Brahman, Chandas ç
and Praj<193>pati as also dak<218>i<207><193> (fees) and d<193>na ç
(gifts) to the officiating priest.
Then commenced the teaching of the Veda.
@NT = Ved<193>rthasa<209>graha
The Ved<193>nta philosophy is based on three foundational works. They ç
are: The Upani<218>ads, the Bhagavadg<200>t<193> and the Brahmas<220>tras.
Though <185>a<209>kara (<MS>A.<|>D.<D> 788-820) and Madhva (<MS>A.<|>D.<D> ç
1238-1317) wrote commentaries on all these three to expound their ç
systems, R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137) wrote only on ç
the last two. However, he chose to write an independent treatise of ç
a different type on the Upani<218>ads, called the  Ved<193>rthasa<209>graha.  Here,  he  has ç
selected and discussed in detail those important statements of the ç
well-known Upani<218>ads like tattvamasi in the Ch<193>ndogya Upani<218>ad ç
(6.8.7) showing how they support his views.
The entire work is in prose. It has not been divided into sections. ç
However, the printed texts have divided it into sections like 102 ç
or 251, depending on their convenience.
The subject matter is spread over three topics:
1.
@NK = A brief account of p<220>rvapak<218>as (views of opponent schools).
2.
@NK = Refutation of the schools of <185>a<209>kara, Bh<193>skara (<MS>A.<|>D.<D> ç
900) and   Y<193>davaprak<193>·a   (11th century <MS>A.<|>D.<D>).
3.
@NK = Establishing his own system on a firm foundation with plenty ç
of quotations and logic.
R<193>m<193>nuja lays great stress on N<193>r<193>ya<207>a as Parabrahman ç
(the Absolute) and devoted meditation on him as the means of liberation.
Sudar·anas<220>ri (<MS>A.<|>D.<D> 1200-1275) wrote a commentary, T<193>tparyad<200>pik<193> ç
by name, which is quite exhaustive.
@NT = Vedas
@SB8.5 = Introduction
The word `Veda,' derived from the root vid (`to know'), indicates ç
a vast bodyof sacred and esoteric knowledge concerning the eternal ç
spiritual values revealed to the great ones called <216><218>is (men ç
of wisdom, sages) in the depths of their meditation. The Hindu religious ç
tradition has accorded the Vedas the highest place in its canonical ç
literature. As such, they are revered as the basic scriptures of Hinduism.
It is extremely difficult to fix the date of the Vedas. The dates ç
assigned by the various scholars vary as widely as 25,000 <MS>B.C.<D> ç
to 1000 <MS>B.C.<D> However the general consensus among most of the ç
Indian scholars is to consider the Harappa-Mohenjo Daro culture (c. ç
4000 <MS>B.C.<D>) to be a later phase of the Vedic culture. This places ç
the date of the <184>g-veda, the earliest of the Vedas, around 10,000 ç
<MS>B.C.<D>
For centuries, the Vedas have been handed down to the posterity by ç
oral tradition. Hence the name <185>ruti, `what isheard'. And, they ç
have been mainly utilized in the performance of yaj<210>as and y<193>gas ç
(sacrifices), which were the most common form of early Vedic religion. ç
Such utilization of the Vedas in the sacrificial processes naturally ç
led to its division based upon the convenience of the chief priests ç
conducting the sacrifices.
A compilation of all the hymns used by the hot<193>-priest to invite ç
the various deities to the sacrifice became the <184>gveda. All ç
the liturgical parts of the Vedas, useful to the adhvaryu-priest, ç
the chief executor of the sacrificial rites, brought together, formed ç
the Yajurveda. Collection of all the musical chants, especially ç
those associated with the Soma group of sacrifices, and to be sung ç
by the udg<193>t<216>-priest, the singer, was named as S<193>maveda. ç
The rest, a sort of miscellaneous appendix and addenda, became the ç
Atharvaveda and was assigned to the brahm<193>-priest, considered ç
as the supervisor  over  the  whole  sacrificial process.
As per the annals of the Hindu orthodoxy, the great sage K<216><218><207>a ç
Dvaip<193>yana Vy<193>sa effected this division by collecting all ç
the mantras extant during his time, and editing them into four groups: ç
<184>k, Yajus, S<193>man and Atharvan. He taught them to his four ç
chief disciples: Paila (<184>gveda), Vai·amp<193>yana (Yajurveda), ç
Jaimini (S<193>maveda)<|>and<|>Sumantu (Atharvaveda). This is how ç
these four Vedas took shape.
@SPACE1 = 
The Vedas are divided in another way too: Mantra and Br<193>hma<207>a. ç
Sa<221>hit<193> is the name given to the collection of the Mantras. ç
The Br<193>hma<207>a includes in itself two more sections, the °ra<207>yaka ç
and the Upani<218>ad. If the Mantras comprise the hymns, the Br<193>hma<207>as ç
contain liturgies in prose. The °ra<207>yakas teach about medi- tations ç
based on symbolical interpretations of the liturgical rites. The Upani<218>ads ç
may roughly  be  defined  as  philosophical treatises dealing with ç
the ultimate problems of life.
Conventionally speaking, it is the Sa<221>hit<193> that is indicated ç
by the word Veda. For instance, <184>gveda means only the <184>ksa<221>hit<193> ç
or the <184>gveda Sa<221>hit<193>. The Br<193>hma<207>as, the °ra<207>yakas ç
and the Upani<218>ads of the <184>gveda have different and independent ç
names and are considered more like its appendages.
These Sa<221>hit<193>s, in course of time, branched off, leading to ç
the formation of ·<193>kh<193>s or recensions. The origin of these ç
·<193>kh<193>s probably lies in the fact that each of the principal ç
sages like Paila or Vai·amp<193>yana had several disciples. These ç
disciples or their successors might have done some editing and readjustment ç
of the Vedic mantras to suit the needs of the rites which they had ç
to perform and upon which local culture too might have exerted its ç
influence.
A brief account of the contents of the four Vedas may now be attempted ç
here.
@SB8.5 = <184>gveda Sa<221>hit<193>
Of all the four Vedic Sa<221>hit<193>s, the <184>gveda Sa<221>hit<193> ç
is the oldest and has a pre-eminent place in the Vedic literature. ç
It is a collection of s<220>ktas or hymns revealed to various <216><218>is ç
or sages at different periods of time. Consequently we can notice ç
a variety of styles of language, grammar, ideas as also historical ç
and cultural factors.
Though it is said to have had 21 ·<193>kh<193>s, only five are known ç
to be extant: <185><193>kala, B<193><218>kala, °·val<193>yana, <185><193><209>kh<193>-yana ç
and M<193><207><195><220>keya. Except for the order of arrangement ç
of the s<220>ktas there do not seem to be any substantial variations ç
among them.
Since ancient days, two methods of dividing this Veda are in vogue. ç
In the first, it is divided into eight a<218><219>akas. Each a<218><219>aka ç
is subdivided into vargas, containing mantras. This mode of division ç
has been done obviously with a view to facili- tating memorization, ç
since the number of vargas in each a<218><219>aka and the mantras ç
in each varga is more or less the same. A total of 10,552 mantras ç
are spread over 2,024 vargas, included in the 64 adhy<193>yas of the ç
eight a<218><219>akas.
@SPACE1 = 
In the second method, the whole Sa<221>hit<193> has been divided into ç
ten ma<207><195>alas. The ma<207><195>alas are subdivided into anuv<193>kas, ç
the anuv<193>kas into s<220>ktas and the s<220>ktas into mantras. ç
The number of anuv<193>kas is 85, that of the s<220>ktas 1,028, the ç
total number of mantras being, of course, the same.
The latter method seems to be the more ancient one and has universal ç
approval  among  the  modern  Vedic scholars.
There seems to be some method and order in the arrangement of the ç
s<220>ktas into the ten ma<207><195>alas. The six ma<207><195>alas ç
(two to seven) contain s<220>ktas revealed to the <216><218>is of ç
the same generic group (va<221>·a). For instance, if the seers of ç
the s<220>ktas in the second ma<207><195>ala belong to the lineage ç
of G<216>tsamada, those in the third belong to the descendants of ç
Vi·v<193>mitra and so on.
The first and the eighth ma<207><195>alas contain  respectively  the  s<220>ktas  of ç
<185>atarcins and Prag<193>thas. The s<220>ktas of the ninth ma<207><195>ala ç
are all in praise of a single deity†Soma Pavam<193>na†and are classified ç
according to their metres. The last, the tenth ma<207><195>ala, is ç
a miscellany of s<220>ktas inclined more towards metaphysical subjects.
The topics dealt with in the <184>gveda Sa<221>hit<193> fall roughly ç
into three groups. The first group deals with the deities like Agni, ç
Indra, Varu<207>a, and others. The second group is concerned with ç
philosophical speculations like the origin of the universe and the ç
real nature of human beings. The third group deals with several secular ç
subjects like marriage, wars of kings, eulogy of generosity and so ç
on.
The Vedic<|>deities are usually enumerated as 33†8 Vasus, 11 Rudras, ç
12 °dityas, Indra and Praj<193>pati. These deities are assigned to ç
the three regions of earth (p<216>thv<200>), heavens (dyaus) and the ç
intermediary space (antarik<218>a). Though they appear like personifications ç
of forces of nature, they are all actually facets of Brahman, the ç
Supreme Truth. The mantra in which the well-known statement, eka<221> ç
sat, vipr<193><199> bahudh<193> vadanti [`Truth is one; sages call ç
It by various names.'] (1.164.46) occurs, is proof enough of this ç
fact. (vide 7.58.2; 10.114.5; 2.1.11; 8.1.27; 2.13.6 also.) However, ç
it may be noted that Indra, Agni, Varu<207>a and Mitra have been given ç
the pride of place in the hymns.
@SPACE1 = 
Coming to the philosophical speculations of this Veda, we find that ç
it is the origin and repository of almost all the later ideas of Ved<193>nta ç
including j<210><193>na (knowledge) and bhakti (devotion), though ç
some of them are in a seed form. This forces us to concede that it ç
is not a book of laudatory hymns only as some try to make it out.
As already pointed out, it teaches eka-devat<193>-v<193>da or monotheism ç
and not polytheism,  as  is  often  mistakenly assumed. However, advocacy ç
of sagu<207>op<193>san<193> (worship of God with form and qualities) ç
is predominant.
God creates this world out of Himself (10.81.2-4) and rules over it ç
(10.82.1; 6.19.10; 6.45.20). He is omnipresent (1.13.10), omniscient ç
(6.7.6; 8.25.9) and omnipotent (6.30.1; 2.29.3; 3.59.1). He is ever ç
perfect (6.24.7; 6.11.4). But He is infinitely compassionate (2.34.5) ç
and easily approachable by the devotees (8.32.15). He is our dearest ç
friend (10.80.2) and grants us immortality (6.45.6; 5.47.7).
As regards the actual process of creation, we find two streams of ç
thought, creation and evolution, both of which have been found in ç
the later Ved<193>ntic literature.
Though the existence of the soul as an eternal entity is accepted ç
and am<216>tatva or immortality is prayed for, the life here-and-now ç
is not relegated to the background. Life here and life hereafter have ç
been nicely harmonized.
@SPACE1 = 
From the group of s<220>ktas dealing with the secular side of life, ç
we can get an inkling into the nature of the society of those times. ç
Social life was permeated by spiritual consciousness. But people strongly ç
believed in samanvaya or harmonizing the life of this world with the ç
one in the next. Satya (truth) and dharma (righteousness) are extolled ç
and am<216>tatva (immortality) as the goal of life accepted. Var<207>a ç
system had already taken roots. Monogamy, polygamy and svaya<221>vara ç
system (that of a bride choosing her husband)†all existed side by ç
side. Agriculture and animal husbandry were thechief means of livelihood. ç
Equitable distribution of wealth was advocated. Civilization was well-developed ç
and fine arts encouraged. Priests and kings were powerful. System ç
of sacrifices had evolved to a high degree of perfection.
Hindu tradition strongly advocates a knowledge of the <216><218>i, ç
the devat<193> and the chandas of any mantra before using it in the ç
religious rites. Then only will it be effective. <184><218>i is the ç
sage to whom the mantra was revealed; devat<193> is the deity to whom ç
the mantra is addressed; and chandas is the metre in which it is composed. ç
According to one calculation the number of <216><218>is exceeds 800 ç
whereas the number of chandases is 19 including the minor variations.
The Br<193>hma<207>as, °ra<207>yakas and the Upani<218>ads of this ç
Veda are:
@NO = 1.
@NOK = Aitareya and Kau<218><200>taki Br<193>hma<207>as;
@NO = 2.
@NOK = Aitareya and <185><193><209>kh<193>yana °ra<207>yakas; ç
and,
@NO = 3.
@NOK = Aitareya and Kau<218><200>taki Upani<218>ads.
@SB8.5 = Yajurveda Sa<221>hit<193>
It is a collection of yajus, the mantras in prose which are specially ç
useful to the adhvaryu-priest in the performance of sacrifices.
@SPACE1 = 
The Yajurveda Sa<221>hit<193> is in two major forms: the K<216><218><207>a ç
and the <185>ukla, meaning the Black and the White. It is not easy ç
to explain why these two major branches got these names. Though a ç
Sa<221>hit<193> (and hence should have been purely in poetry) the ç
former is a mixture of prose and poetry and hence not pure. So, ç
it has been called K<216><218><207>a, the Black one. In contrast, ç
the latter being entirely in poetry, is <185>ukla, the White one. ç
Thisis the first explanation. Being more ancient, the former is rather ç
difficult to comprehend and so is K<216><218><207>a or Black. The ç
latter is of more recent origin and hence easier to grasp. So it is ç
<185>ukla, the White one. This is the second explanation.
Though the K<216><218><207>a Yajurveda Sa<221>hit<193> is reputed ç
to have had 85 ·<193>kh<193>s or recensions, only four are available ç
now: a.Taittir<200>ya; b. Maitr<193>ya<207><200>ya; c. Ka<219>ha; ç
d. Kapisthala.
The Taittir<200>ya Sa<221>hit<193> which is widely prevalent in ç
South India, has 7k<193>n<195>as or books, 44 prap<193><219>hakas ç
or chapters, and 651 anuv<193>kas or mantras. It deals mainly with ç
the detailed descriptions of sacrifices like Pauro<195><193>·a, Y<193>jam<193>na, ç
V<193>japeya, R<193>jas<220>ya, Dar·a-p<220>r<207>am<193>sa and Somay<193>gas.
The other three ·<193>kh<193>s are not so well-known though they too ç
deal with similar sacrifices. The last of these, the Kapisthala, ç
as available now, seems to be incomplete.
Associated with the Taittir<200>ya Sa<221>hit<193> are the Taittir<200>ya ç
Br<193>hma<207>a, Taittir<200>ya °ra<207>yaka and the Taittir<200>ya ç
Upani<218>ad. The well-known Ka<219>hopani<218>ad also belongs ç
to K<216><218><207>a Yajurveda, but to the Ka<219>ha recension.
@SPACE1 = 
The <185>ukla Yajurveda Sa<221>hit<193>, also known as the V<193>jasaney<200> ç
Sa<221>hit<193>, is said to have been collected and edited by the ç
famous sage Y<193>j<210>avalkya. It is entirely in verse and resembles ç
the <184>gveda Sa<221>hit<193> in form. However, there are no s<220>ktas ç
in this. Though 17 ·<193>kh<193>s of this Sa<221>hit<193> are said ç
to have existed, only two†the K<193><207>va and the M<193>dhyandina†are ç
available now. The former, more prevalent in the South, has 40 adhy<193>yas ç
or chapters, 328 anuv<193>kas or sections, and 2,086 mantras. The ç
latter, more common in the North, has 40 adhy<193>yas, 328 anuv<193>kas, ç
and 1,975 mantras.
Like the Taittir<200>ya Sa<221>hit<193>, this Sa<221>hit<193> also ç
deals mainly with sacrifices like Agni<218><219>oma, V<193>japeya ç
and R<193>jas<220>ya.
The <185>atapatha Br<193>hma<207>a, the biggest of the Br<193>hma<207>as, ç
and the B<216>had<193>-ra<207>yaka are the Br<193>hma<207>a and ç
the °ra<207>yaka attached to the <185>ukla Yajurveda. ®·<193>v<193>syopani<218>ad ç
and B<216>had<193>ra<207>ya-kopani<218>ad are the Upani<218>ads ç
of this Veda.
@SPACE = 
@SB8.5 = S<193>maveda Sa<221>hit<193>
@SPACE = 
The S<193>maveda Sa<221>hit<193> has been highly extolled in our ç
holy books. However, it is not considered as an independent work. ç
`S<193>' means <216>k, a mantra of the <184>gveda. `Ama' means various ç
kinds of musical notes. Hence a `s<193>man' is a mantra of the <184>gveda ç
Sa<221>hit<193> set to music. All such mantras ofthe <184>gveda ç
which are useful to the udg<193>t<216>-priest, have been brought together ç
in this work.
Though it is said to have 1,000 ·<193>kh<193>s, only three are available ç
now: Kauthuma, R<193><207><193>yan<200>ya and Jaimin<200>ya.
This Veda is divided into two parts: °rcik<193> and Uttar<193>rcik<193>. ç
The former contains 585 mantras and the latter 964, making a total ç
1,549. Out of these, except 75 mantras, the rest are taken from the ç
<184>gveda Sa<221>hit<193>. As many as 272 mantras have been repeated ç
twice. If these repetitions are also taken into account, then the ç
number of mantras becomes 1,821. Another recension puts it at 1,875.
@SPACE1 = 
Unlike the mantras of the other three Vedas, the mantras of the S<193>maveda, ç
known simply as s<193>mans, have seven svaras or musical scales, identical ç
with the seven scales of classical music. It can thus be inferred ç
that the origin of Indian classical music lies in the S<193>maveda.
There are several varieties of singing the s<193>mans and they are ç
given special names like Rathantara-s<193>ma, B<216>hat-s<193>ma ç
and so on. It is a difficult art to learn and needs expert guidance.
Nine Br<193>hma<207>as are attached to thisVeda. T<193><207><195>ya-mah<193>-br<193>hma<207>a ç
is the biggest and the most important of them.
Only one °ra<207>yaka of this Veda is available now: Talavak<193>ra ç
or Jaimin<200>ya °ra<207>yaka.
Two well-known Upani<218>ads, the Ch<193>ndogya and the Kena (also ç
called Talavak<193>ropani<218>ad<|>) are also attached to the S<193>maveda.
@SPACE1 = 
@SB8.5 = Atharvaveda Sa<221>hit<193>
@SPACE1 = 
Also known as Brahmaveda, since it is assigned to the brahm<193>- ç
priest, the Atharvaveda Sa<221>hit<193> has some special features ç
because of which it stands apart from the other three Vedas, specially ç
from the <184>gveda Sa<221>hit<193>. It deals more with the things ç
here and now, than the hereafter, and with the sacrifices which are ç
a means to them. A major part of this Veda is concerned with diseases ç
and their cure, rites for prolonging life, rites for fulfilling one's ç
desires, building construction, trade and commerce, statecraft, penances ç
and propitiatory rites, as also black magic, though high philosophical ç
ideas much nearer to those of the Upani<218>ads are alsofound. Even ç
the literary style is moresophisticated. Hence it is that some scholars ç
believe that this work is chronologically of a later origin and was ç
admitted into the comity of Vedic literature at a later date.
From the ancient times, nine ·<193>kh<193>s of this Veda are known ç
to have existed, but only two are extant: Pippal<193>da and <185>aunaka. ç
It is only the latter that is available in a complete form.
The Atharvaveda Sa<221>hit<193> is divided into four prap<193><219>hakas ç
or books, comprising 20 k<193><207><195>as or chapters. Each k<193><207><195>a ç
is divided into s<220>ktas or hymns, and the s<220>ktas into mantras. ç
There are 6,077 mantras, in 736 s<220>ktas spread over 20 k<193><207><195>as ç
in four prap<193><219>hakas. The last k<193><207><195>a, i.e., the ç
20th, has borrowed heavily from the <184>gveda Sa<221>hit<193>.
This Veda designates God the Absolute not only as Brahman but also ç
by some interesting names like Skambha, Ucchi<218><219>a and Vr<193>tya ç
which are peculiar only to it. The whole universe has emerged out ç
of Him due to His will and is established in Him. He is the Lord of ç
the whole creation. The sun, called `Rohita' (the `Red One') is a ç
symbol of His power. And He is the indwelling spirit of human beings ç
also. Those who realize this, go beyond all fear. This Veda also refers ç
to heaven and hell, as also virtue and sin. The qualities like satya ç
(truth), d<200>k<218><193> (discipline) and tapas (austerity) that ç
helpman to attain perfection are also mentioned.
@SPACE1 = 
This work gives us an interesting picture of the society of its times. ç
The land in which the people lived extended from G<193>ndh<193>ra ç
(Afghanistan) to Magadha (Bihar) and Va<209>ga (Bengal). The var<207>a ç
system had been well-established. The firstthree var<207>as were ç
powerful. Trade and commerce were prosperous though agriculture was ç
the mainstay of the people. Sometimes the br<193>hma<207>as were harassed ç
by the powerful k<218>attriya kings. The cow was highly venerated ç
and god<193>na (gift of a cow) was considered meritorious. The institution ç
of marriage was similar to that in the <184>gvedic times.
No °ra<207>yaka of the Atharvaveda has come to light so far. Only ç
one Br<193>hma<207>a, the Gopatha Br<193>hma<207>a, has been dis- ç
covered. The three well-known Upani<218>ads †the Pra·na, the Mu<207><195>aka ç
and the M<193><207><195><220>kya†belong to this Veda.
@SB8.5 = Epilogue
As already stated, the Vedic Sa<221>hit<193>s had to be committed ç
to memory and werepassed on orally from generation to generation. ç
Even now they have been preserved in a pure form. This was possible ç
only due to the unique system of chanting that had been evolved, consisting ç
of pada-p<193><219>ha, krama-p<193><219>ha, ja<219><193>-p<193><219>ha, ç
and ghana-p<193><219>ha, which are all various chanting modes. (See ç
<MS>GHANAP°<187>HA<D> for details)
The Vedas, considered `apauru<218>eya' (not man-made but revealed), ç
are rather difficult to understand due to the archaic form of language ç
and terminology. Hence, the  six  Ved<193><209>gas  (limbs  of  Veda)† ç
subsidiary sciences that help unfold the Vedic wisdom†came into existence. ç
They are: <185><200>k<218><193>, Vy<193>kara<207>a, Chandas, Nirukta, ç
Jyoti<218>a and Kalpa. <185><200>k<218><193> deals with the modes ç
of chanting. Vy<193>kara<207>a is Vedic grammar. Chandas is concerned ç
with the details of the metres of Vedic poetry. Nirukta gives the ç
meanings and explanations of Vedic words. Jyoti<218>a, though awork ç
of astronomy, is more directly concerned with the times and periods ç
suitable for the performance of the Vedic sacrifices. Kalpa, in the ç
form of s<220>tras or aphorisms, has four branches ·rauta, g<216>hya, ç
dharma and ·ulba. It deals with all aspects of sacrificial rites and ç
smaller religious rites performed at home.
In understanding the Vedic literature, bh<193><218>yas or commentaries ç
have done yeomen service. There have been a galaxy of commentators ç
over the centuries, among whom S<193>ya<207><193>c<193>rya (14th cent.) ç
holds a unique place, not only because of the sheer volume of work ç
but also because of the quality. Mention may also be made of some ç
of the other commentators: Skanda-sv<193>min<|> (7th century <MS>A.D.<D>);<|> ç
Ve<209>ka<219>a-m<193>dhava (11th century <MS>A.D.<D>); Bha<219><219>a- ç
bh<193>skara (11th century <MS>A.D.<D>) and °nanda-t<200>rtha (Madhv<193>c<193>rya) ç
(13th cent. <MS>A.D.<D>). However, their bh<193><218>yas as available ç
now are incomplete.
A study of the Vedas is a fascinating and highly rewarding experience.
@NT = Vedavat<200>
Vedavat<200> was the daughter of the sage Ku·adhvaja. She was extraordinarily ç
beautiful. When she was doing tapas† severe austerities†to get Lord ç
Vi<218><207>u as her husband, R<193>va<207>a tried to molest her. ç
She escaped from him, cursed him that she will get him killed in her ç
next birth, and immolated herself in the Vedic fire. She was later ç
born as S<200>t<193> (R<193>m<193>ya<207>a, Uttarak<193><207><195>a, ç
Chapter 17), the foster daughter of Janaka.
@NT = vedavratas
Brahmac<193>rins residing in the guru-kulas for learning the Vedas ç
had to observe some vratas or religious vows before commencing the ç
study of certain sections  of  the  same.  They  were enumerated as ç
four: Mah<193>n<193>mn<200>vrata; Mah<193>vrata; Upani<218>advrata; ç
God<193>navrata.
They were each of one year's duration, starting from the age 13, up ç
to the age of 16.
However, they seem to have been given up in course of time.
@SPACE = 
@NT = Vedavy<193>sa
@SPACE = 
K<216><218><207>a Dvaip<193>yana was the son of the sage Par<193>·ara ç
and Satyavat<200>. Since he was k<216><218><207>a or dark in complexion ç
and was born in a dv<200>pa or an island, he came to be known by this ç
name.
It was he who gathered all the mantras of the Veda available during ç
his time and edited them, dividing them into four parts now well-known ç
as <184>gveda, Yajurveda, S<193>maveda and Atharvaveda. Because ç
of this great work he got the appellation `Vedavy<193>sa' (`one who ç
divided the Vedas'). He was known as Vy<193>sa also.
Tradition ascribes to him the author-ship of the epic Mah<193>bh<193>rata, ç
the eighteen Mah<193>pur<193><207>as or the major pur<193><207>as, ç
and the eighteen Upapur<193><207>as or minor pur<193><207>as.
Boy Ga<207>e·a, the little god, is said to have been Vy<193>sa's scribe ç
who took down the Mah<193>bh<193>rata as he dictated it.
It was Vedavy<193>sa who begot Dh<216>ta-r<193><218>tra, P<193><207><195>u ç
and Vidura by the command of his mother Satyavat<200>, on the wives ç
of Vicitrav<200>rya (son of the king <185>antanu).
(See <MS>NIYOGA<D>.)
He gave divine sight to Sa<210>jaya (charioteer of Dh<216>tar<193><218><219>ra) ç
so that he could describe the Kuruk<218>etra battle to his master.
Vy<193>sa was in touch with almost all the important persons of the ç
Mah<193>bh<193>rata period.
@NT = vedha
@N1 = (`intermixed')
Vedha (`pierced' or `intermixed') is a technical term used in Hindu ç
pa<210>c<193><209>gas or almanacs. It belongs to the field of Jyauti<218>a ç
or astronomy.
According to the c<193>ndram<193>na or lunar calendar, a day (from ç
sunrise to the next sunrise) is divided into 60 gha<219>ik<193>s (1gha<219>ik<193> ç
= 24 minutes). If a tithi (like pratipad, dvit<200>y<193> and so on, ç
the number of the day after new-moon or full-moon) is spread over ç
all the 60 gha<219>ik<193>s, it is called p<220>r<207><193>. If another ç
tithi begins some time after sunrise or before sunset, the tithi becomes ç
viddh<193> or with vedha. For instance, the tithi at sunrise on a ç
day may be t<216>t<200>y<193> (3rd) and caturthi (4th) may begin after ç
six gha<219>ik<193>s. Then it is viddha-tithi.
All religious rites including the vratas (vows and festivals) have ç
to be started at the prescribed time even though the tithi may have ç
vedha.
@NT = vedi
@N1 = (`altar')
Vedic sacrifices need a special kind of platform or altar usually ç
situated in a ·<193>l<193> or sacrificial shed. Such an altar is called ç
vedi. It is an elevated plot of ground built or prepared according ç
to the dimensions prescribed in the <185>rautas<220>tra works. These ç
dimensions are fixed in proportion to the height of the sacrificer.
Different y<193>gas need vedis of different shapes.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
The vedi is covered with darbha grass on which the various vessels ç
and implements are arranged.
@NT = Ve<209>ka<219>e·a, Ve<209>ka<219>e·vara
The god of Tirumala-Tirupati is known by various names, of which these ç
two are most common.
The hill on which the temple and the deity are situated was called ç
Ve<209>ga<195>a, a Tamil word, later Sanskritised to Ve<209>ka<219>a. ç
The lord of this hill came to be known as Ve<209>ka<219>e·a or Ve<209>ka<219>e·vara.
According to the local legends, when the sage Bh<216>gu who went to ç
Vaiku<207><219>ha (the abode of Vi<218><207>u) humiliated Lord Vi<218><207>u, ç
Lak<218>m<200> (consort of Vi<218><207>u) got angry, descended to ç
the earth and settled down at Kolh<193>pur. Vi<218><207>u too came ç
down in search of her. Not finding her, he was roaming about in the ç
forest atop this hill. When Padm<193>vat<200>, daughter of the king ç
°k<193>·ar<193>ja, was rescued by him from a fierce elephant, she ç
fell in love with him. (Padm<193>vat<200> was actually Vedavat<200> ç
reborn. She had performed severe austerities to marry Vi<218><207>u ç
himself.) They were duly married.
Vi<218><207>u as Ve<209>ka<219>e·vara settled down on the hill whereas ç
his new consort had to stay back at the foot of the hill. This place ç
now houses her temple and the place itself is called Tirucc<193>n<220>r.
See <MS>TIRUMALA-TIRUPATI<D> for details.
@NT = vesara
This is one of the three styles of temple architecture. It is a combination ç
of the n<193>gara and the dr<193>vi<195>a styles.
See <MS>HINDU TEMPLES<D>.
@NT = ve·y<193>
@N1 = (`one who lives by selling her body')
Ve·y<193>s†prostitutes and concubines† have existed from times immemorial ç
in all the societies of the world.
While recognising their existence as a necessary evil in the society, ç
the dharma·<193>stras have made some specific rules for their maintenance ç
and protection.
Prostitution seems to have been esta-blished as an institution even ç
by the period of the Mah<193>bh<193>rata (vide Udyogaparva 151.58).
@NT = Vibh<193><207><195>aka
Vibh<193><207><195>aka was the father of the sage <184><218>ya·<216><209>ga, ç
of the R<193>m<193>ya<207>a fame. He was a descendant of the great ç
sage Ka·yapa. His hermitage was on the bank of the river Kau·ik<200>. ç
Yudhi<218><219>hira, the eldest of the P<193><207><195>ava brothers, ç
had visited him.
According to another version, his hermitage was near the present town ç
of <185><216><209>ger<200> (in Karnataka) on the bank of the river ç
Tu<209>g<193>. The li<209>ga worshipped by him is said to be the same ç
as that situated on the nearby hill and now known as Malah<193>nike·vara.
@NT = vibhava
See <MS>ARC°<D>.
@NT = Vibh<200><218>a<207>a
See <MS>R°M°YAØA<D>.
@NT = vibh<220>ti, vibh<220>tis
Vibh<220>ti is another name for bhasma, the holy ash smeared on the ç
forehead and other parts of the body by the ·aivas.
See <MS>BHASMA<D> for more details.
The word is also used in the sense of special or extraordinary powers ç
of God, or, the siddhis, the yogic powers that a yogi gains as a result ç
of sa<221>yama (See <MS>SA<189>YAMA<D>.) on various objects.
The tenth chapter of the Bhagavad-g<200>t<193> is called Vibh<220>tiyoga. ç
The third chapter of the Yogas<220>tras of Pata<210>jali (200 <MS>B.<|>C.<D>) ç
has been named Vibh<220>tip<193>da.
@NT = videhakaivalya, videhamukti
@N1 = (`liberation after death')
See <MS>J®VANMUKTI<D>.
@NT = vidhi
@N1 = (`fate', `rule')
This word is used to indicate Brahm<193>, the creator as also fate ç
in general.
(See <MS>AD<184><186><187>A<D>.)
In the P<220>rvam<200>m<193><221>s<193> system it indicates a rule ç
given by the Vedas. Such vidhis are of two kinds: s<193>m<193>nyavidhi ç
(general rule) and vi·e<218>avidhi (special or particular rule).
The second one applies where the first one has to be set aside. For ç
instance: Ahi<221>s<193> (non-injury) is the highest virtue. This ç
is the general rule. However, it doesnot apply to holy acts such ç
as Vedicsacrifices where animals have to be immolated.
@NT = Vidura
During the Mah<193>bh<193>rata period, the practice of niyoga or levirate ç
was quite common. Since the King Vicitrav<200>rya died suddenly without ç
issues, the sage Vy<193>sa†as per the command of his mother Satyavat<200>†raised ç
three children on the two queens Amb<193> and Ambik<193> as also the ç
latter's maid. Vidura was the maid's son.
Though born of a ·<220>dra mother, Vidura was saintly by nature. He ç
proved to be better than Bh<200><218>ma and Dro<207>a by refusing ç
to fight for the Kauravas since they had transgressed all limits of ç
dharma.
He was said to be born out of an a<221>·a (a part) of the glory of ç
Lord Yama, the deity supervising over the death and dharma of the ç
people of this world of mortals.
Throughout his life, he not only observed dharma (righteousness) in ç
his personal life but also taught and warned others about the right ç
path.
The following are some of the more important aspects of his life: ç
warning the P<193><207><195>avas in a secret language about the dangers ç
of the palace at Vara<207><193>vata builtof inflammable materials; ç
advising Dh<216>tar<193><218><219>ra (father of the Kauravas) manytimes ç
against his conduct of blindly supporting his sons even in unholy ç
acts; entertaining K<216><218><207>a with great devotion in his house ç
when he suddenly appeared after he had arrived in Hastin<193>pura ç
for peace parleys; leaving on a pilgrimage just before the Kuruk<218>etra ç
war, to avoid taking part in it; departing for the forest along with ç
Dh<216>tar<193><218><219>ra and ultimately dying in the forest fire.
Viduran<200>ti, the teaching imparted by Vidura to Dh<216>tar<193><218><219>ra ç
(vide Mah<193>bh<193>rata, Udyogaparva Chs. 33-40) has now become ç
a classic on ethics.
@NT = Viduran<200>ti
@N1 = (`ethical philosophy [taught<R>ç
by] Vidura')
The Mah<193>bh<193>rata is like a vast ocean. It is believed that ç
an ocean contains many gems. That is why it is also called `ratn<193>kara' ç
(storehouse of gems). One of the bright gems or jewels of this great ç
epic is Vidura.
@SPACE1 = 
After being convinced that war was inevitable between his sons and ç
the P<193><207><195>avas, Dh<216>tar<193><218><219>ra sent Sa<210>jaya ç
(his charioteer) to the P<193><207><195>avas with the message that ç
they should abandon the path of war and retire to the forest. When ç
he returned Sa<210>jaya abused the blind king for his attitude ofgreed ç
and the injustice meted out to the P<193><207><195>avas. This strong ç
reproach made him restless and sleepless the whole night. The very ç
next morning, he sent for Vidura and confessed his state of mind. ç
The advice that Vidura gave him forms the content of this work. It ç
is spread over eight chapters in the Udyogaparva (Chapters 33 to ç
40). There are 588 verses in all.
