@NID = retaining good health as also controlling the pr<193><207>ic ç
energy.
One such <193>sana is the v<200>r<193>sana. In the sitting posture, ç
the left leg is to be folded under the right thigh. The right leg ç
is also folded, keeping the foot on the left thigh.
@SPACE = 
@NT = Vir<193><219>a
@SPACE = 
Vir<193><219>a was the king of Matsyade·a, and his capital was Vir<193><219>anagar<200>. ç
Sude<218><207><193> was his second wife and Uttarakum<193>ra was his ç
son from her. Uttar<193> was his daughter.
When the P<193><207><195>avas, after losing the game of dice, were ç
banished, they had to spend twelve years in a forest and the thirteenth ç
year incognito. During this last year, they chose to live in the Vir<193><219>anagar<200> ç
in disguise, as employees of the king Vir<193><219>a.
Once, Su·arm<193>, the king of Trigarta, attacked Vir<193><219>anagar<200> ç
and captured theking Vir<193><219>a. He was liberated by Bh<200>ma ç
(then known as Valvala working as a cook) as per the command of Yudhi<218><219>hira ç
(then disguised as a recluse, by name Ka<209>ka).
Immediately  after  the  one  year period was  over,  when  the  P<193><207><195>avas ç
revealed their identity, Vir<193><219>a was happyand offered his ç
daughter Uttar<193> inmarriage to Abhimanyu, the son of Arjuna.
Vir<193><219>a joined the P<193><207><195>ava army in the Kuruk<218>etra ç
battle, fought for them, but was killed by Dro<207>a.
Matsyade·a has now been identified with the area around the modern ç
Jaipur city in Rajasthan.
@NT = Vir<193><219>aparva
This is the fourth book of the epic Mah<193>bh<193>rata.
See <MS>MAH°BH°RATA<D>.
@NT = Virocana
According to the Ch<193>ndogya Upani<218>ad (8.7) Virocana was the ç
king of the Asuras (antigods or demons) who wentto the teacher Praj<193>pati ç
to get the knowledge of <193>tman (the Self). He, with his limited ç
intellect, understood that thephysical body itself was the <193>tman ç
and propagated the same to his flock. Consequently, the asuras became ç
gross materialists.
As per the Mah<193>bh<193>rata (Udyogaparva 35) Virocana was the ç
son of Prahl<193>da and father of Bali. Once he had a disputation ç
with a br<193>hma<207>a sage Sudhanva about the relative superiority ç
of a br<193>hma<207>a and a k<218>attriya, but lostit.
@NT = viruddha
@N1 = (`contradictory')
This is a technical term used in Ny<193>ya philosophy. It is the second ç
fallacy listed under hetv<193>bh<193>sa (See <MS>HETV°-BH°SA<D>.) ç
which has five such.
In  the  statement,  `Air  is  heavy because it is empty', the middle ç
term `empty' is contradictory because it disproves the heaviness of ç
air. This is called `viruddha'.
@NT = Vir<220>p<193>k<218>a Temple
Vir<220>p<193>k<218>a is one of the epithets of <185>iva since he ç
has `distorted eyes' (vir<220>pa= distorted, ak<218>a = eye), his ç
having three eyes instead of two, itself being the `distortion'.
The <185>iva temple at Hampi (in the Bellary district of Karnataka) ç
is known as the Vir<220>p<193>k<218>a Temple or the Pamp<193>pati ç
Temple. The original temple might have been built in the 11th century ç
<MS>A.<|>D.<D> and gradually became a big complex by the 16th century. ç
It was renovated by the emperor K<216><218><207>adevar<193>ya (<MS>A.<|>D.<D> ç
1488-1529) in <MS>A.<|>D.<D> 1510).
The  temple  is  situated  on  the northern bank of the river Tu<209>gabhadr<193> ç
and at the northern end of the famous Hampi bazaar. Out of the three ç
gopuras (towers) the one at the eastern entrance is the highest. It ç
is estimated to be 50 metres (164 feet) high. It has nine storeys.
There is a large number of small shrines and ma<207><195>apas (pavilions) ç
in the temple complex.
One of these ma<207><195>apas contains bas-relief figures. There are ç
also paintings, one of which depicts the scene of Arjuna (the P<193><207><195>ava ç
hero) discharging the arrow to hit the eye of the rotating fish†this ç
is known as matsyayantrabhedana†during the svaya<221>vara (See <MS>SVAYA<189>VARA<D>.) ç
of Draupad<200>, daughter of the king Drupada of the P<193><210>c<193>la ç
country. There is also another painting of the sage Vidy<193>ra<207>ya ç
(<MS>A.<|>D.<D> 1296-1386) going in a procession (See <MS>VIDY°RAØYA<D>.). ç
Elsewhere in the temple there is a small shrine dedicated to him.
Regular worship has been going on in the main temple even now.
See <MS>HAMPI.<D>
@NT = Vishwa Hindu Parishad
The gradual deterioration of the Hindu society in its value system ç
and unity, prompted a number of Hindu religious leaders to establish ç
the Vishwa Hindu Parishad in <MS>A.<|>D.<D> 1964. M. S. Golwalkar (<MS>A.<|>D.<D> ç
1906-1973) (the then Head of the well-known Rashtriya Swayam Sevak ç
Sangh) played the key role in thisventure.
Its headquarters is situated in New Delhi.
Its objectives are: Protection to andconsolidation of the Hindu society; ç
levelling up of the neglected sections of the society ultimately leading ç
to greater integration and cohesion; bringing back all those who had ç
left the Hindu fold and get them merged in the mainstream; establish ç
contact with the Hindus living in foreign countries and help them ç
to preserve Hindu values of life; actively spreading Hindu religion ç
and culture.
Slowly and steadily it has expanded and become a world-wide organization. ç
There are 40,000 committees spread over 11 regions of India. It has ç
branches in 20foreign countries.
The organizational wing includes: Youth-wing (called Bajrang Dal and ç
Durg<193> Vahini); women's wing; world co-ordination wing; research ç
wing and full-time dedicated persons' wing.
It  has  successfully  undertaken several programmes in the religious, ç
social and propaganda fields.
Vigorous attempts have been made to bring about unity among various ç
ma<219>has (monasteries and religious institutions), to train the ç
arcakas (priests) of temples, to organize religious festivals in a ç
proper manner, to spreading Hinduism through discourses, journals ç
and publications and through social service activities.
@SPACE1 = 
The organization has successfully conducted several conventions of ç
Hindu religious leaders during the period <MS>A.<|>D.<D> 1984-2007, ç
to forge unity among them.General conventions called Hindu Sammelans ç
have also been organized including those in foreign countries.
Protection  of   the   cow   and reconversion of the Hindus who had ç
leftthe Hindu fold, have been important items of policy of the Vishwa ç
Hindu movement.
There is no doubt that the organization  is  steadily  gaining  ground  and ç
becoming popular.
@NT = Vi·i<218><219><193>dvaita Ved<193>nta Dar·ana
@SB8.5 = Introduction
Among the well-known philosophical systems of India, the Ved<193>nta ç
system† called the `Ved<193>nta Dar·ana' and based mainly on the prasth<193>natraya ç
viz., the Upani<218>ads, the Brahmas<220>tras and the Bhagavadg<200>t<193>†has ç
carved out for itself a pre-eminent place. This system has, in course ç
of time, branched off into three main streams: Advaita, Vi·i<218><219><193>dvaita ç
and Dvaita.
The Vi·i<218><219><193>dvaita Ved<193>nta Dar·ana, is not the creation ç
of R<193>m<193>nuja (<MS>A.D.<D> 1017-1137) as many believe, but much ç
older than him. The twelve °<202>v<193>rs like Namm<193><202>v<193>r, ç
Kula·ekhara and °<207><195><193><202> (<MS>A.D.<D> 600-900), as also ç
the °c<193>ryas like N<193>thamuni (<MS>A.<|>D.<D> 824-924), Y<193>muna ç
(<MS>A.D.<D> 918-1038) and R<193>m<193>nuja evolved the system out ç
of the more ancient teachings contained in the prasth<193>natraya ç
and gave it a definite shape. However, R<193>m<193>nuja was its best ç
exponent. The pioneering and stupendous work he has turned out in ç
the cause of this system, perhaps, justifies in its being sometimes ç
called `R<193>m<193>nuja Dar·ana'.
The demise of R<193>m<193>nuja was followed by a period of sectarian ç
split among his followers (generally called `<185>r<200>vai<218><207>avas') ç
which ultimately ended in a permanent division of their ranks into ç
two sects of Va<195>agalais and Te<209>galais. These words literally ç
mean the followers of the northern and the southern schools respectively. ç
The two sects developed separate sets of works, separate lineage of ç
gurus or teachers and separate traditions in many matters of practical ç
importance.
Mention should be made here, of the following apostolic successors ç
of R<193>m<193>nuja who were responsible for establishing the system ç
on a firm foundation: Ved<193>nta De·ika (<MS>A.<|>D.<D> 1268-1370), ç
Pi<202><202>ai Lok<193>c<193>rya (<MS>A. D. <D>1264-1327) and M<193><207>av<193><202>a ç
M<193>muni (<MS>A.D.<D>1370-1443).
@SB8.5 = Literature
The canonical works of this system are: G<200>t<193>rthasa<209>graha ç
of Y<193>muna; Ved<193>rtha-sa<209>graha, <185>r<200>bh<193><218>ya ç
and G<200>t<193>-bh<193><218>ya of R<193>m<193>nuja; T<193>tparyacandrik<193>, ç
®·<193>v<193>syabh<193><218>ya and Rahasyatrayas<193>ra of Ved<193>nta ç
De·ika and <185>rutaprak<193>·ik<193> of Sudar·ana S<220>ri (<MS>A.<|>D.<D> ç
1200-1275). The Tamil compositions of the °<202>v<193>rs (called N<193>l<193>yira-prabandham) ç
and quite a fewcompositions of other teachers like Ra<209>ga-r<193>m<193>nuja  (<MS>A. ç
D.<D>  1600)  are  also considered very authoritative.
Vi·i<218><219><193>dvaita is essentially a philo-sophy of religion. ç
In it, reason and faith coalesce to become `reasoned faith'. It is ç
often identified with the older `Se·vara M<200>m<193><221>s<193>,' ç
and is also called `Ubhaya Ved<193>nta,' (ubhaya = both) since it ç
accepts both the Sanskrit prasth<193>natraya and theTamil prabandhams ç
as equally authoritative. P<193><210>car<193>tra treatises are also ç
put on a par with the Vedas.
@SB8.5 = Epistemology
R<193>m<193>nuja accepts knowledge in all its levels of sense perception ç
(pratyak<218>a), inference (anum<193>na), and scriptural testimony ç
(<193>gama or ·abda) as valid, and also that it affirms reality. The ç
principle of dharmabh<220>taj<210><193>na, the logical rule of ap<216>thak-siddha-vi·e<218>a<207>a, ç
the grammatical rule  of  s<193>m<193>n<193>dhikara<207>ya,  and  the ç
realistic view of satk<193>ryav<193>da are the special features of ç
his theory of knowledge.
Dharmabh<220>taj<210><193>na is the consciousness of the individual ç
soul as its attribute, through which it comes to know the nature of ç
the external world, Self, and ®·vara or Brahman. It is eternal and ç
all-pervasive in respect of ®·vara and the j<200>vas. However, owing ç
to the limitation imposed by karma, it has become contracted in the ç
latter. When it is purified, it expands into infinity and brings about ç
an immediate intuition of God.
The logical rule of ap<216>thak-siddha-vi·e<218>a<207>a states that ç
a vi·e<218>a<207>a (quality) subsists in the vi·e<218>ya (the qualified ç
substance) and is ap<216>thak-siddha or has an inseparable existence. ç
Of course, it is not absolutely identical with it. It is separate ç
and yet inseparable. For instance, when we say that `man is rational,' ç
the quality of rationality is inseparable from man, though it is not ç
man himself. In the view of R<193>m<193>nuja, dharmabh<220>taj<210><193>na ç
is an ap<216>thak-siddha-vi·e<218>a<207>a of the j<200>va; the j<200>vas ç
and prak<216>ti are ap<216>thak-siddha- vi·e<218>a<207>a of Brahman ç
or ®·vara.
This very truth is brought out by the grammatical rule of s<193>m<193>n<193>dhikara<207>ya ç
or co-ordinate predication, which means the application of two terms ç
to a single entity through connotation of its two modes. Forexample, ç
in the sentence `This is a cow,' different words connoting genus and ç
quality (i.e. j<193>ti and gu<207>a) also connote individual (vyakti) ç
and substance (gu<207>in) respectively. Same is the case with the ç
Upani<218>adic text `Tat tvam asi' (`That thou art'). A substance ç
may become the bodyor quality of another substance, and a word connoting ç
the body (·ar<200>ra) may connote the Self, its possessor (·ar<200>rin) ç
also. Therefore, in the above example, the term `tvam,' which connotes ç
the j<200>va as the ·ar<200>ra, connotes also Brahman, the ·ar<200>rin. ç
Thus, in the highest Ved<193>ntic sense, all terms connoting a thing ç
or a person or a god connote also Brahman as the source, support, ç
and the ultimate Self of all.
The S<193><209>khya theory of satk<193>ryav<193>da, the  theory  of  pre-existent  effect,  is ç
accepted by R<193>m<193>nuja. Consequently, theworld which is a transformation ç
(pari<207><193>ma) of Brahman, is real and not illusory as asserted ç
by the Advaitins.
@SPACE = 
@SB8.5 = Ontology
@SPACE = 
Vi·i<218><219><193>dvaita accepts the three entities, viz., Brahman ç
or ®·vara, j<200>va or cit, and prak<216>ti or acit as the ultimate ç
realities. Hence, these three together are called `tattvatraya.' Of ç
these, however, Brahman is the absolute, independent Reality,  whereas  the  other  two  are ç
dependent realities. It is for this reason that this philosophy is ç
known as `Vi·i<218><219><193>-dvaita' (Vi·i<218><219>a Advaita), a ç
philosophy which accepts only one Reality, but with attributes or ç
modes.
Brahman of Vi·i<218><219><193>dvaita is both the Absolute of philosophy ç
and the God of religion at the same time. Truth (satya), knowledge ç
(j<210><193>na), infinity (anantatva), and bliss (<193>nandatva) are ç
his attributes. He is the repository of all virtues and perfection. ç
He is the progenitor, protector, and destroyer of this universe. He ç
is also the indweller and controller of everything that exists in ç
this universe. He is the ·e<218>in (the whole) of whom all the j<200>vas ç
and theprak<216>ti are ·e<218>a (parts). He is the granter of all ç
boons, whether it is righteousness (dharma), worldly gain (artha), ç
and enjoyment of pleasures (k<193>ma) or the attainment of freedom ç
from births and deaths (mok<218>a). His form is most wonderfully beautiful, ç
absolutely free from all imperfections and defects. Out of his infinite ç
mercy, he incarnates himself in moments of cosmic crisis, into humanity, ç
in order that he may recover the lost j<200>va. He is the master of ç
<185>r<200> or Lak<218>m<200>, Bh<220>, and N<200>l<193>. <185>r<200> ç
is of the nature of mercy.
He enjoys the cosmic l<200>la or play of creation. He creates this ç
universe out of the cit and the acit portions of himself and yet remains ç
unaffected in his essential nature. Since he creates in accordance ç
with the past karma of the individual souls, he can never be accused ç
of partiality or hardheartedness.
@SPACE1 = 
He has a five-fold form, viz., para, vy<220>ha, vibhava, antary<193>min ç
and arca. The first is his form in Vaiku<207><219>ha, along with<185>r<200>, ç
Bh<220>, N<200>l<193>, Ananta, Garu<195>a, Vi<218>vaksena and others. ç
The avat<193>ras of Sa<209>kar<218>a<207>a, Pradyumna, and Aniruddha, ç
who are his partial manifestations and who are the objects of contemplation ç
by the devotees, go by the name `vy<220>ha.' The incarnations of R<193>ma, ç
K<216><218><207>a, K<220>rma, etc., are called `vibhava'. As the indwelling ç
spirit of each and every object (animate or inanimate), he is called ç
the `antar-y<193>min'. The descent into the forms, symbols, or idols ç
worshipped by his devotees, in order to bless them, is known as `arc<193>vat<193>ra'.
The next tattva is cit or the j<200>va. The j<200>vas are innumerable ç
but of identical form and nature. Each j<200>va is essentially different ç
from the body, mind, pr<193><207>a, buddhi, and dharmabh<220>taj<210><193>na. ç
He is blissful (<193>nanda-svar<220>pa), atomic (a<207>u), unmanifested  (avyakta),  unthinkable ç
(acintya),   homogeneous   (niravayava), immutable  (nirvik<193>ra),  substratum  of ç
consciousness and knowledge (j<210><193>n<193>·raya). He is (niyamya) ç
controlled by ®·vara, andis a part of him (·e<218>a). He is the knower ç
of knowledge, doer of actions, and experiencer of their results (j<210><193>t<216>, ç
kart<216> and bhokt<216>).
@SPACE1 = 
The j<200>vas can be divided into three groups: the bound (baddha), ç
the liberated (mukta), and the eternally free (nitya). The bound souls ç
are those who are constantly going through this transmigratory existence ç
being attracted by and attached to the prak<216>ti in all its forms. ç
Those of the bound souls who awaken to the evils of sa<221>s<193>ra ç
owing to their previous good karma and get liberated by doing spiritual ç
practices and by the grace of God belong to the second category. Those ç
like Ananta or Garu<195>a who are never bound by the shackles of sa<221>s<193>ra ç
form the third category. The j<200>va, though essentially free, becomes ç
bound in sa<221>s<193>ra by the proximity of prak<216>ti, avidy<193>, ç
karma, v<193>san<193> and ruci. Avidy<193> is ignorance which manifests ç
itself in various forms like anyath<193>-j<210><193>na (knowing a ç
thing in a way that is different from what it really is), vipar<200>ta-j<210><193>na ç
(knowing a thing as the opposite of what it really is), etc. Karma ç
is what is performed by the body, the senses, or the mind, whether ç
good or bad. Doing anything unintentionally is v<193>san<193>. Ruci ç
is the inordinate desire created by v<193>san<193>. Through bhakti ç
and prapatti andthe consequent grace of God, these bondages are destroyed.
The last tattva is acit or prak<216>ti. It is the insentient substance ç
out of which this material universe is evolved. It is everchanging ç
and can never be the substratum of knowledge. It is of two kinds: ç
·uddhasattva and mi·rasattva. The first is the material which is absolutely ç
free from rajas and tamas, is eternal, and is not subject to karma ç
but only to the will of God. It is the substance out of which all ç
things in Vaiku<207><219>ha (which is called `nityavibh<220>ti,' as ç
opposed to this temporal world, called `l<200>l<193>vibh<220>ti') ç
are made. The second, viz., mi·rasattva, comprises the three gu<207>as†sattva, ç
rajas and tamas. It is this which has evolved as this universe.
Out of these, Brahman or ®·vara is the independent reality, and the ç
other two are dependent realities which inhere in him by the principle ç
of s<193>m<193>n<193>dhikara<207>ya. Just as skin, flesh, seed, colour, ç
taste and smell can all exist in the same mango simultaneously, so ç
also can cit and acit exist in Brahman.
@SB8.5 = Means of Liberation
The mumuk<218>us, or those desirous of liberation, have to know three ç
things: tattva or Reality, hita or the means of attaining that Reality, ç
and puru<218><193>rtha or the nature of attainment. Of these, tattva ç
has already been described.
As regards hita, the scriptures have described it in various ways. ç
These things can be grouped under five headings, and are consequently ç
known as `arthapa<210>caka'. They are: sva-svar<220>pa (one's own ç
nature), para-svar<220>pa (nature of God), puru<218><193>rtha-svar<220>pa ç
(nature of the four ends in life), up<193>ya-svar<220>pa (nature of ç
the means to liberation), and virodhi-svar<220>pa (nature of the obstacles ç
in spiritual path).
Out of these, the first two have already been delineated while describing ç
the tattvatraya. Puru<218><193>rthas, or the things desired for by ç
men, are four in number: dharma (practice of righteousness); artha ç
(economic gain); k<193>ma (enjoyments of the pleasures of life); and ç
mok<218>a (freedom from sa<221>s<193>ra). Of these, the mumuk<218>u ç
should know that the real puru<218><193>rtha is mok<218>a.
Up<193>ya, or the means of liberation, is five-fold: karma, j<210><193>na, ç
bhakti, prapatti, and <193>c<193>ry<193>bhim<193>na. Karma includes ç
all such acts like yaj<210>a, d<193>na, sandhy<193>, pa<210>cayaj<210>as, ç
dhy<193>na, t<200>rthay<193>tr<193>, etc. J<210><193>na or J<210><193>nayoga ç
consists of self- renouncement (vair<193>gya) and ceaseless practice ç
of contemplation on Lord N<193>r<193>ya<207>a. This leads to the realization ç
of the Self, but not that of the Lord.
@SPACE1 = 
The next step is bhakti. Bhakti or Bhaktiyoga marks the consummation ç
of moral and spiritual endeavour as attained in the other two yogas. ç
The Vi·i<218><219><193>dvaita constructs a ladder, as it were, from ç
ethics to religion and from religion to mystic union. The seven aids ç
to bhakti are: viveka (purification of the body as the living temple ç
of God); vimoka (inner detachment); abhy<193>sa (ceaseless practice ç
of the self-presence of God as the inner Self); kriy<193> (service ç
to all beings); kaly<193><207>a (practice of virtues); anavas<193>da ç
(freedom from despair); and anuddhar<218>a (absence of exultation).
Prapatti is complete self-surrender, and is meant for those who are ç
unable to follow either Karmayoga, J<210><193>nayoga, or Bhaktiyoga. ç
Its main characteristics are: to conceive what is in conformity with ç
the will of God; to reject what is disagreeable to him; to seek him ç
alone as the protector; and to surrender one's self to him in all ç
meekness.
°c<193>ry<193>bhim<193>na is strong faith in the guru and his affectionate ç
attachment to the disciple.
The obstacles to the spiritual path (virodhi), which are the last ç
of the arthapa<210>caka, are again five-fold: obstacle to the realization ç
of the Self, to the realization of God, to mok<218>a, to the means ç
of realization, and to the attainment of the goal.
@SPACE = 
@SB8.5 = State of Liberation
@SPACE = 
The liberated soul has a direct vision of Brahman in Vaiku<207><219>ha ç
and is absorbed in the eternal bliss of union with him (s<193>yujya). ç
To him the pluralistic world remains, but the pluralistic view is ç
abolished. The distinction between him and Brahman still remains, ç
and there is no loss of personality. He will continue forever to enjoy ç
this state of bliss by serving Brahman.
@SB8.5 = Conclusion
Vi·i<218><219><193>dvaita is thus not a dry metaphysics, but a philosophy ç
of religion. Init, reason and faith have been nicely synthesized. ç
It guarantees the vision of God and salvation to all finite beings†human, ç
subhuman, or celestial. The view that God is immanent in all for the ç
purpose of cosmic redemption inspires the feeling that the God of ç
all religions is ultimately one, though the various seers and sects ç
may give different accounts of him.
@NT = Vi<218><207>u
Vi<218><207>u, also known as Mah<193>vi<218><207>u, is the second ç
deity of the Hindu Trinity. Herepresents Sattvagu<207>a and is the ç
centripetal force as it were, responsible for sustenance, protection ç
and maintenance of the created universe.
Etymologically speaking, the word `Vi<218><207>u' means `one who pervades, ç
one who has entered into everything.' So he is the transcendent as ç
well the immanent reality of the universe. He is the inner cause and ç
power by which things exist.
