A mirror is one of the several objects that is shown in the hands ç
of a female figurine or a goddess, sculptured according to the rules ç
of the M<220>rti·ilpa·<193>stra or Hindu Iconography.
It is also one of the a<218><219>ama<209>galas† eight objects signifying ç
auspiciousness† normally used on auspicious occasions like the coronation ç
of a king.
See also <MS>A<186><187>AMA<177>GALAS.
@NT = dar·ana
@N1 = (`seeing or experiencing')
Though the word means `seeing', it is often used in a technical sense, ç
indicating any system of philosophy. Generally the Indian philosophical ç
systems are called `dar·anas' since they claim to have been based ç
on the `seeing' or the `experiencing' of the final truths.
These dar·anas are classified into two broad groups: the <193>stika-dar·anas ç
and the n<193>stika-dar·anas. The former accept the authority of the ç
Vedas whereas the latter do not.
The former, being six in number, is often called `<218>a<195>dar·anas' ç
(<218>a<219><|>=<|>six)
@NID = They are:<R>ç
<|><+>the Ny<193>yadar·ana of Gautama<R>ç
<|><+>the Vai·e<218>ikadar·ana of Ka<207><193>da<R>ç
<|><+>the S<193><209>khyadar·ana of Kapila<R>ç
<|><+>the Yogadar·ana of Pata<210>jali<R>ç
<|><+>the M<200>m<193><221>s<193>dar·ana of Jaimini<R>ç
<|><+>and<|>the<|>Ved<193>ntadar·ana of B<193>dar<193>ya<207>a.
@NID = The latter are:<R>ç
<|><+>the C<193>rv<193>kadar·ana of C<193>rv<193>ka<R>ç
<|><+>the Jainadar·ana<R>ç
<|><+>and the Bauddhadar·ana.
The last two represent the various philosophical systems of Jainism ç
and Buddhism. The first represents materialism of various shades and ç
hues. Though the work itself is not available now, excerpts from it ç
have been quoted in the treatises of other writers.
See under each title for details.
@NT = Dar·ap<220>r<207>am<193>sa
Vedic sacrifices†called yaj<210>as and y<193>gas†are an ancient institution. ç
One of its varieties is `i<218><219>i,' a sacrifice performed with ç
the four priests adhvaryu, <193>gn<200>dhra, hot<216> and brahman. ç
(See under each title for details.) The Dar·ap<220>r<207>am<193>sa ç
is a prak<216>ti (an archetype) in this i<218><219>i group and is ç
obligatory.
The words `dar·a' and `p<220>r<207>am<193>sa' actually stand for the ç
new-moon and the full-moon days. Hence, the Vedic rites to be performed ç
on these days have also been named `Dar·a' and `P<220>r<207>am<193>sa'. ç
The two are identical in almost all respects except for some minor ç
variations. Consequently, they are often clubbed together and called, ç
`Dar·ap<220>r<207>am<193>sa.'
The Dar·a sacrifice is done on the new-moon day and the day next to ç
it (pratipad). The P<220>r<207>am<193>sa is performed on the full-moon ç
day and the following day.
The only difference in the procedure between these two sacrifices ç
is that the puro<195><193>·a (rice-cake) is offered to Indra and Agni ç
in the Dar·a whereas the same is offered to Agni-Soma in the P<220>r<207>am<193>sa.
The preliminaries like shaving, bathing and fasting are done by the ç
sacrificer on the day called `upavasaha' (= fasting and living near ç
the fire). This is followed by anv<193>dh<193>na (offering of three ç
pieces of sacrificial wood into the fire). The other rites to follow ç
are: pi<207><195>apit<216>yaj<210>a (obsequial rites for the forefathers ç
up to three generations); usual daily Agnihotra; preparing the curdled ç
milk for offering on the next day; preparing the puro<195><193>·a ç
(rice-cakes) for offering; repetition of the s<193>midhen<200> verses ç
(eleven verses from the <184>gveda, mostly from the third Ma<207><195>ala, ç
aimed at kindling the fire); <193>gh<193>ra libation (wherein the ç
adhvaryu pours ghee into the fire moving the spoon all over, with ç
appropriate mantras) and five pray<193>ja and two <193>jyabh<193>ga ç
oblations (preliminary offerings).
Then, the principle offerings are madewith puro<195><193>·a (rice-cakes) ç
to the accompaniment of puro'nuv<193>kyas (call or invitation to the ç
deities by the hot<216> priest) and y<193>jy<193>s (technical formulae ç
of consecration chanted by the hot<216> priest while the adhvaryu ç
priest offers a libation of ghee).
In the Dar·a, eleven offerings of Puro<195><193>·a kept in small earthen ç
plates are offered to Indra and Agni. In the P<220>r<207>a-m<193>sa, ç
the offerings are made to Agni and Soma.
This is followed by the svi<218><219>ak<216>t offering (a secondary ç
offering to Agni by whose goodwill the sacrifice has been successfully ç
done) and i<195><193>bhak<218>a<207>a (eating the portions cut off ç
from all the main offerings) by the priests.
Then comes anuy<193>ja (three supplementary offerings) followed by ç
s<220>ktav<193>ka (speech of adoration by the hot<216> priest) and ç
·a<221>yuv<193>ka (formula of benediction, also by the hot<216> priest).
@SPACE1 = 
After a few more minor rites like the patn<200>sa<221>y<193>ja (offerings ç
to the consorts of the deities), removal of the yoktra (a beltof ç
mu<210>ja grass), pr<193>ya·cittas (expiatory rites) and vi<218><207>ukrama ç
(ceremonially taking four steps with appropriate mantras, by the yajam<193>na ç
or the sacrificer) the whole sacrifice comes to a close.
See also <MS>VEDIC SACRIFICES.<D>
@NT = d<193>rujali<209>ga
@N1KERN = (`<185>ivali<209>ga made out of wood')
Unlike the other deities, <185>iva (one of the three aspects of the ç
Supreme, the aspect of involution or withdrawal or destruction of ç
the world) is invariably worshipped in the form of a li<209>ga. A ç
li<209>ga is an icon, cylindrical in shape, with a spherical top. ç
Since God is beyond name and form and since we cannot conceive of ç
an abstract principle like him without the aid of concrete symbols, ç
a spherical surface or emblem is perhaps the nearest approach to him.
`D<193>ru' means wood. Li<209>gas carved out of wood are called `d<193>rujali<209>gas'. ç
They are of the sth<193>vara or stationary type. The minimum and maximum ç
heights prescribed for such li<209>gas are 16 and 144 a<209>gulas. ç
(One a<209>gula is roughly 1.9 cms. or 0.75 inch.)
The d<193>rujali<209>gas are classified into 9 or even 33 varieties, ç
depending upon their height. For instance, if the makara-li<209>ga ç
is 16 a<209>gulas in height (the minimum height permitted), the da<207><195>ali<209>ga ç
is 80 a<209>gulas and the phalodbhava li<209>ga is 144a<209>gulas ç
(the maximum permissible height).
As regards the type of wood out of which it is carved, about 20 varieties ç
are recommended. Some of them are: ·am<200> (Prosopsis spieigera), ç
devad<193>ru (Cedrus deodara), candana (sandalwood), bilva (Aegle ç
marmelos), a·vattha (peepul tree) and a·oka (Saraca asoca).
@SPACE1 = 
See also <MS>LI<177>GA.<D>
@NT = d<193>sa and d<193>s<200>
@N1 = (`a [paid] servant or<R>ç
servant-maid')
@SPACE = 
The word `d<193>sa' occurs in the <184>gveda (5.34.6; 6.22.10) many ç
times and refers to the enemies of the Vedic people. Since these d<193>sas ç
were, in many cases, reduced to slavery, the term has been used in ç
the sense of a `slave' also. (See <MS>SLAVERY.<D>)
In later literature, the word refers to a paid servant.
While naming a person, this word was used as a suffix for persons ç
belonging to the ·<220>dra caste.
In the devotional literature, this expression has been widely used ç
to indicate a devotee as a servant of God or as a servant of the devotees ç
of God. For instance: R<193>mad<193>sa, K<216><218><207>ad<193>sa, ç
Ca<207><195><200>-d<193>sa and so on.
@SPACE = 
@NT = D<193>sabodha
@N1 = (`[spiritual and philosophical] wisdom [as taught by Samartha] ç
R<193>mad<193>sa')
@SPACE = 
Samartha R<193>mad<193>s (<MS>A.<|>D.<D> 1608-1681) was a great saint ç
of Maharashtra. He was the guru (preceptor and guide) of Chatrapati ç
<185>iv<193>j<200> (<MS>A.<|>D.<D> 1627-1680). It was he who was primarily ç
responsible for the rejuvenation of Hindu religion and society by ç
inspiring <185>iv<193>j<200>.
He has left behind him two immortal works both in Mar<193><219>hi: ç
Man<193>ce <185>loka and D<193>sabodha.
The work D<193>sabodha comprises twenty da·akas or decads. Each ç
of these da·akas consists of ten long sections called sam<193>sas. ç
The sam<193>sas again, have a number of ov<200>s or metrical stanzas, ç
their total number being 7756.
The contents in brief may be given as follows:
@S10N = Da·aka-1 (326 stanzas)
@EMERGENCY = prayers to Ga<207>e·a, Sarasvat<200>, guru and saints; ç
greatness and usefulness of human birth.
@S10N = Da·aka-2 (470 stanzas)
@EMERGENCY = descriptions of various types of persons, from fools ç
to wise persons; the three gu<207>as sattva, rajas and tamas; characte-ristics ç
of a good and holy person.
@S10N = Da·aka-3 (581 stanzas)
@EMERGENCY = various evils in worldly life; t<193>patrayas or three ç
kinds of sufferings; death and detachment.
@S10N = Da·aka-4 (295 stanzas)
@EMERGENCY = navavidha bhakti (nine modes of devotion); four kinds ç
of mukti or liberation.
@S10N = Da·aka-5 (573 stanzas)
@EMERGENCY = characteristics of a good guru (spiritual teacher) and ç
of a good ·i<218>ya or disciple; different kinds of teachings on s<193>dhan<193> ç
(spiritual practice); signs of a siddha or a perfected being.
@S10N = Da·aka-6 (415 stanzas)
@EMERGENCY = on Brahman, m<193>y<193> and s<216><218><219>i or creation; ç
worship of God with form; denial of this world which is seen but does ç
notreally exist; indescribable nature of Brahman.
@S10N = Da·aka-7 (564 stanzas)
@EMERGENCY = fourteen kinds of Brahman; offsetting the effects of ç
dvaita or sense of duality; on ·rava<207>a (listening to the Ved<193>ntic ç
truths); death and j<200>vanmukta (one who is liberated even while ç
living).
@S10N = Da·aka-8 (644 stanzas)
on God; various kinds of doubts; the pa<210>camah<193>bh<220>tas (the ç
five elements); on mok<218>a (liberation) and the perfected being.
@S10N = Da·aka-9 (427 stanzas)
various kinds of doubts and their answers; description of the inner ç
state of a man of knowledge.
@S10N = Da·aka-10 (354 stanzas)
the consciousness in all, is one and the same; creation and dissolution; ç
prak<216>ti (nature) and puru<218>a (soul).
@S10N = Da·aka-11 (287 stanzas)
on creation and dissolution of the world; four kinds of manifestations ç
of God; how a s<193>dhaka (spiritual aspirant) should lead his life; ç
behaviour of a true leader of a society; nature of the Self within.
@S10N = Da·aka-12 (294 stanzas)
on devotion; viveka (discrimination) and vair<193>gya (renunciation); ç
need for self-effort; how to become great.
@S10N = Da·aka-13 (300 stanzas)
philosophical truths through a story; on God the creator, various ç
opinions; need to protect the purity of one's mind.
@S10N = Da·aka-14 (406 verses)
desirelessness necessary; a s<193>dhaka (aspirant) should live by ç
bhik<218><193> (begging); efficacy of singing God's names; greatness ç
of a householder's life and the need to keep it pure; remember God ç
constantly.
@S10N = Da·aka-15 (337 stanzas)
how to live in this world, in peace and harmony with others; knowledge ç
makes one superior to others; Brahman as the origin of the world; ç
all activities of prak<216>ti (nature) and puru<218>a (individual ç
soul) are transient; interpretation of the mah<193>v<193>kyas of the ç
Upani<218>ads (like tat-tvam-asi).
@S10N = Da·aka-16 (302 verses)
hymns devoted to V<193>lm<200>ki, S<220>rya (sun-god) and the five ç
elements like theearth and water; on the <193>tman or theSelf; various ç
types of up<193>san<193> or meditation.
@S10N = Da·aka-17 (299 stanzas)
Supreme God (Jagad<200>·vara) manifests himself as various souls; ç
<185>iva and <185>akti are at the root of all beings, male and female; ç
doubts are obstacles in the path of understanding Ved<193>ntic truths; ç
explanation of ajap<193>japa (process of breathing associated with ç
the repetition of the mantra so'ham); four kinds of bodies.
@S10N = Da·aka-18 (288 stanzas)
This section deals with miscellaneous topics like various gods†Ga<207>apati, ç
Brahm<193>, Ve<209>ka<219>e·a, R<193>ma, K<216><218><207>a and so ç
on†as different manifestations of the Antar<193>tman (the °tman inside), ç
company of j<210><193>nis (persons of spiritual wisdom), importance ç
of human body in the path of spiritual progress and so on.
@S10N = Da·aka-19 (285 stanzas)
on  handwriting  and  scholarship; condemnation of laziness; signs ç
of a wise person; methods of giving good advice; efficiency in work ç
and management.
@S10N = Da·aka-20 (308 stanzas)
discussion about p<220>r<207>a and ap<220>r<207>a (what is complete ç
and what is incomplete); the three gu<207>as; up<193>san<193> or meditation ç
on God with form; interesting details about 84 lakhs of species of ç
living beings; on the <193>tman; body compared to a field; on Parabrahman ç
(the Absolute).
The  work  is  extremely  popular especially in Maharashtra.
A ceremonial recitation and discourses on it are considered as a religious ç
and meritorious act.
See also <MS>R°MAD°SA<D> (<MS>SAMARTHA<D>).
@NT = Da·agva
See <MS>NAVAGVA<D> for details.
@NT = Da·ahar<193>
@N1 = (`destroyer of ten [sins]')
Festivals and sacred days have a very important part to play in popular ç
Hinduism. They often act as a catalytic agent to integrate the various ç
sections of the Hindu society.
One of the minor festivals, observed mostly in North India and also ç
on the banks of the big rivers like K<216><218><207><193>, God<193>var<200> ç
and Narmad<193>, is the Da·ahar<193> (also called Ga<209>g<193>-da·ahar<193>). ç
It occurs on the tenth day of the bright fortnight (·ukla-da·am<200>) ç
of the month of Jye<218><219>ha (May-June). The river Ga<209>g<193> ç
is believed to have descended to the earth on this day. If the day ç
happens to be a Tuesday or a Wednesday it is considered even more ç
auspicious. A bath in the river Ga<209>g<193>, especially at the Da·<193>·vamedha-gh<193><219> ç
of V<193>r<193><207>as<200> or K<193>·<200> (in Uttar Pradesh) on ç
this day is said to destroy ten kinds of sins associated with the ç
body, speech and mind. The bath should be followed by worship of the ç
prescribed deity and giving gifts to worthy persons.
@NT = da·ahot<193>ra<199>
@N1 = (`ten hot<216> priests')
@SPACE = 
The religion of the Vedic °ryans comprised mostly of the performance ç
of Vedic sacrifices. Out of these, Agny<193>dheya or Agny<193>dh<193>na ç
was a primary rite meant for generating the Vedic fires like the g<193>rhapatya. ç
These fires had to be maintained for life and all other sacrifices ç
had to be performed only in them.
The `da·ahot<193>ra<199>' is actually a formula of ten sentences taken ç
from the Taittir<200>ya °ra<207>yaka (3.1). These mantras have to ç
be repeated when the upper ara<207>i is placed on the lower one before ç
churning, for generating the fire.
These ten short sentences (o<221> citti<199> sruk; cittam <193>jyam; ç
v<193>g vedi<199> and so on) actually identify ten different parts ç
of the human body with ten things connected with the sacrifice.
@SPACE = 
@NT = d<193>sak<220><219>a
@N1 = (`an assembly of the servants [of God]')
@SPACE = 
In the religio-philosophical literature of Hinduism both bhakti (devotion) ç
and j<210><193>na (knowledge) have been given equal prominence. The ç
various teachers of bhakti, over the centuries, gave the common masses ç
a simple philosophy of life to live by. This they did through their ç
teachings, mostly in the form of devotional songs.
The tradition of devotion with its popular religion and ethics, was ç
originated in North India by the musician-saints like Tulas<200>d<193>s ç
(<MS>A.<|>D.<D> 1532-1623), Kab<200>r (<MS>A.<|>D.<D><|>1440-1518), N<193>nak ç
(<MS>A.<|>D.<D><|>1469-1539), M<200>r<193>b<193><200> (<MS>A.D.<D><|>1450-1547) ç
and others. In Maharashtra, it was Sant J<210><193>ne·var (13th cent. ç
<MS>A.<|>D.<D>), Ekan<193>th (<MS>A.<|>D.<D><|>1533-1599), Tuk<193>r<193>m  (<MS>A.<|>D.<D> ç
1607-1694),  R<193>mad<193>s (<MS>A.D.<D><|>1608-1681) and a host ç
of others whodid the same. In Bengal, <185>r<200>k<216><218><207>a ç
Caitanya (<MS>A.D.<D><|>1485-1533), R<193>mapras<193>d (<MS>A.<|>D.<D><|>1720-1781) ç
and Kamal<193>k<193>nta (<MS>A.<|>D.<D><|>1800 ?) were the important ç
teachers.
In South India, the °<202>v<193>rs (7th to 9th centuries <MS>A.<|>D.<D>) ç
and N<193>yanm<193>rs (7th and 8th centuries <MS>A.<|>D.<D>) spread ç
the cult of bhakti in the Tamil country. The <185>iva- ·ara<207>as ç
(12th cent.<MS> A.<|>D.<D>) and the Harid<193>sas (15th cent.<MS> A.D.<D>) ç
were the pioneers of the bhakti movement in Karnataka.
The Harid<193>sa movement comprised two parallel but closely knit ç
units, generally called the `Vy<193>sak<220><219>a' and the `D<193>sak<220><219>a'. ç
The former was nourished by the sa<221>ny<193>sins of the M<193>dhva ç
school like <185>r<200>p<193>dar<193>ya (15th cent. <MS>A.<|>D.<D>) ç
and Vy<193>sa-r<193>ya (<MS>A.<|>D.<D> 1447-1539) whereas the latter ç
was sustained by Purandarad<193>sa (<MS>A.<|>D.<D> 1484-1564), Kanakad<193>sa ç
(15th cent. <MS>A.<|>D.<D>), Vijayad<193>sa (<MS>A.<|>D.<D> 1687-1755) ç
and other householder-devotees of the same school.
Though the Vy<193>sak<220><219>a derived its name from Vy<193>sar<193>ya ç
(also known as Vy<193>sat<200>rtha) who was responsible for the phenomenal ç
growth of both the units, itwas <185>r<200>p<193>dar<193>ya who was ç
the pioneer of both.
@SPACE1 = 
The sa<221>ny<193>sin teachers were great scholars both in Sanskrit ç
and in Kanna<195>a (the vernacular of Karnataka). They composed scholarly ç
works in the former and popular devotional songs in the latter. TheHarid<193>sas†though ç
quite a few of them also were great scholars†concentrated on spreading ç
the cult of devotion and the Dvaita Ved<193>nta of Madhv<193>c<193>rya ç
(<MS>A.<|>D.<D> 1197-1276) as also simple ethical principles  through  their  songs  which ç
became very popular over the centuries.
Apart  from  Purandarad<193>sa  and Vijayad<193>sa, Gop<193>lad<193>sa ç
(<MS>A.<|>D.<|><D>1721-1762) and Jagann<193>thad<193>sa (<MS>A.<|>D.<D> ç
1728-1809) too have contributed profusely to the Harid<193>sa literature.
Some of the other Harid<193>sas who contributed significantly to the ç
D<193>sak<220><219>a and the bhakti movement are: Vaiku<207><219>ha-d<193>sa, ç
Prasanna-Ve<209>ka<219>ad<193>sa, Timma<207><207>a-d<193>sa, Mohanad<193>sa, ç
He<202>avanaka<219><219>e Giri- yamma (a lady-saint), Kall<220>ru ç
Subba<207><207>a-d<193>sa, Aij<200>d<193>sa and so on.
The Vijayanagara city and the Raichur district of Karnataka were the ç
main centres of origin and activities of these Harid<193>sas.
The compositions of these Harid<193>sas are legion. Their chief characteristic ç
is simplicity. They express the profound truths of Ved<193>nta in ç
a simple language and urge the people to lead a God-centred life even ç
while discharging one's normal duties in the world. The topics generally ç
dealt with are: description of God's form and beauty (almost always ç
as Vi<218><207>u or K<216><218><207>a), childhood pranks of K<216><218><207>a, ç
various devotional practices like repetition of the divine nameor ç
singing the glories of God, moral principles like satya (truth) and ç
dharma (righteous living), evil nature of the evil ones (in order ç
to avoid such conduct), some paur<193><207>ic stories as also autobiographical ç
references, activism as well as dependence on God and a host of other ç
miscellaneous subjects.
@SPACE1 = 
The contribution of the D<193>sak<220><219>a to Hindu religion and ç
culture through the life and literature of the various Harid<193>sas ç
is considerable.
@NT = Da·amah<193>vidy<193>s
@N1 = (`ten great representa-tions of knowledge')
@SPACE = 
@SPACE = 
Ten aspects of <185>akti are sometimes described in t<193>ntric works. ç
They are termed `Da·amah<193>vidy<193>'s. These are the representations ç
of transcendental know-ledge and power, the sources of all that is ç
to be known.
The first is K<193>l<200>, the goddess of time, that destroys everything. ç
T<193>r<193>, the second, is  the  power  of  the  golden  embryo ç
(Hira<207>ya-garbha) from which the universe evolves. She also stands ç
for void or the boundless space. The third is <186>o<195>a·<200>. ç
The word literally means `one who is sixteen years old.' She is the ç
personification of fullness, of perfection. Bhuvane·var<200>, the ç
fourth Vidy<193>, represents the forces of the material world, whereas ç
Bhairav<200> the fifth, stands for desires and temptations leading ç
to destruction and death. Then comes Chinnamast<193>, the naked deity ç
holding her own severed head in hand and drinking her own blood! She ç
simply represents the continued state of self-sustenance of the created ç
world in which are seen continuous self-destruction and self-renewal, ç
in a cyclic order. Dh<220>m<193>vat<200>, the seventh, personifies ç
the destruction of the world by fire, when only smoke (Dh<220>ma) ç
from its ashes remains. She is sometimes identified with Alak<218>m<200> ç
or Jye<218><219>h<193>dev<200>. The eighth Vidy<193>, Bagal<193>, ç
is a crane-headed goddess, and represents the ugly side of living ç
creatures like jealousy, hatred and cruelty. M<193>ta<209>g<200>, ç
the ninth, is the embodiment of the power of domination. The tenth ç
and the last, Kamal<193>, is the pure consciousness of the Self, bestowing ç
boons and allaying the fears of the supplicants. She is identified ç
with Lak<218>m<200>, the goddess of fortune.
@SPACE = 
@NT = Da·an<193>m<200>s
@N1 = (`those [belonging to the<R>ç
order] of ten names')
@SPACE = 
Sa<221>ny<193>sa or monasticism is a very ancient institution. The ç
dharma·<193>stras list it as the fourth and last stage in a man's ç
life. (See <MS>°<185>RAMA<D> for details.)
Organised monasticism into a regular Order (in Hinduism)†though common ç
among the Buddhists†can be attributed to <185>a<209>kara's (<MS>A.<|>D.<D> ç
788-820) pioneering efforts. He established four centres of his monastic ç
order at Badar<200> (in Uttar Pradesh), Dv<193>rak<193> (in Gujarat), ç
Pur<200> (in Orissa) and <185><216><209>ger<200> (in Karnataka). They ç
have been christened as Jyotir Ma<219>ha (or Jo·i Ma<219>ha), K<193>lik<193> ç
Ma<219>ha, Govardhana Ma<219>ha and <185><193>rad<193> Ma<219>ha respectively. ç
He is said to have appointed his four chief disciples as the first ç
abbots of these Ma<219>has as follows: To<219>aka (Jyotir Ma<219>ha), ç
Padmap<193>da (K<193>lik<193> Ma<219>ha), Hast<193>malaka (Govardhana ç
Ma<219>ha) and Sure·vara (<185><216><209>ger<200> <185><193>rad<193> ç
Ma<219>ha).
He also organised his sa<221>ny<193>sin disciples and the tradition ç
of ascetics through them, into ten orders, known as`da·an<193>m<200>-samprad<193>ya', ç
(da·a = ten, n<193>m<200> = with name; hence `da·an<193>m<200>') of ç
the following titles:
@SPACE1 = 
(1) Ara<207>ya; (2) °·rama; (3) Bh<193>rat<200>; (4) Giri; (5) Parvata; ç
(6) Pur<200>; (7) Sarasvat<200>; (8) S<193>gara; (9) T<200>rtha and ç
(10) Vana. Every sa<221>ny<193>sin of these orders adds to his adopted ç
name one of these ten titles as a suffix. For instance: Vidy<193>ra<207>ya, ç
N<216>si<221>habh<193>rati, °nandagiri, Tot<193>pur<200>, °nandat<200>rtha ç
and so on.
These ten orders have been specifically aligned with the four ma<219>has ç
as follows:
@SPACE = 
@NID = Jyotirma<219>ha<192>Giri, Parvata and S<193>gara.
@NID = <185><193>rad<193>ma<219>ha<192>°·rama and T<200>rtha.
@NID = Govardhanama<219>ha<192>Ara<207>ya and Vana.
@NID = <185><216><209>ger<200>ma<219>ha<192>Bh<193>rat<200>, Pur<200> ç
an<%12>d<%0>Sarasvat<200>.
@SPACE = <%18>
Though it is difficult to derive any definite conclusions as to the ç
meanings of these ten terms which may not be related to their normal ç
meanings, traditional interpretations and explanations are on the ç
following lines:
@NIDX = Ara<207>ya
@NK = indicates a monk living in an ara<207>ya or a forest, completely ç
detached from mundane affairs.
@NIDX = °·rama
@NK = indicates a monk living in an <193>·rama or a hermitage thus ç
freed from the botheration of wandering.
@NIDX = Bh<193>rat<200>
@NK = indicates one laden with learning, who has thrown away all burdens.
@NIDX = Giri
@NK = indicates one who is steady like a mountain (= giri) or one ç
who lives at the foot of a mountain.
@NIDX = Parvata
@NK = indicates one who lives at the foot of hills and has steadfast ç
knowledge regarding the transient nature of the world.
@NIDX = Pur<200>
@NK = indicates one who is full of the knowledge of Brahman. (Pur<200> ç
ascetics seem to have been considered as the highest among the monks.)
@NIDX = Sarasvat<200>
@NK = indicates one who is greatly learned and also an adept in yoga.
@NIDX = S<193>gara
@NK = indicates one who has dived into the depths of the ocean of ç
knowledge and collected the gems of truth.
@NIDX = T<200>rtha
@NK = indicates one who bathes in the confluence of the three rivers ç
of the knowledge and the realisation of the truth `tat tvam asi' (`That ç
thou art').
@NIDX = Vana
@NK = indicates one who has transcended all the snares of desires ç
and lives quietly in a forest.
@SPACE = 
The Da·an<193>m<200> monks are further classified into four samprad<193>yas ç
or traditional sects or groups without reference to their orders, ç
but as assigned to the four monastic centres. They are:
@SPACE = 
@LEFT = °nandav<193>ra	attached<|>to<|>the Jyotirma<219>ha;<R>ç
Bhogav<193>ra	attached<|>to<|>the<R>ç
			Govardhanama<219>ha;<R>ç
Bh<220>riv<193>ra	attached<|>to<|>the <185><216><209>ger<200>ma<219>ha;<R>ç
K<200><219>av<193>ra	attached<|>to<|>the <185><193>rad<193>ma<219>ha.
@SPACE = 
These terms (though they appear to be a little fanciful) respectively ç
indicate freedom from
@SPACE = 
@NID = (1)<+>desire for sense-pleasures;<R>ç
(2)<+>desire for all enjoyments;<R>ç
(3)<+>desire for worldly possessions;<R>ç
(4)<+>tendencies hurtful to creatures.
@SPACE = 
Each of these four monastic centres, again, has its own devat<193> ç
and dev<200> (tutelary deities), k<218>etra (place of pilgrimage), ç
t<200>rtha (holy river), gotra (spiritual lineage), Veda, sv<193>dhy<193>ya ç
(study of parti-cular Upani<218>ads) and a mah<193>v<193>kya (sentence ç
for contemplation chosen from the Upani<218>ads). The table given ç
in page no. 467 gives all the details in a nutshell.
In establishing the Da·an<193>m<200> order of monks, as attached to ç
the four ma<219>has, <185>a<209>kara showed remarkable social awareness ç
also which was badly needed during his times. These ma<219>has were ç
charged with the task of caring for the welfare of the people of the ç
regions assigned to them, through tours and discourses.
See also <MS>MONASTICISM, SA<189>NY°SINS<D> and <MS><185>A<177>KARA.<D>
@NT = da·<193>pavitra
@SPACE = 
Vedic sacrifices were very common during the early phase of Hinduism. ç
Among the various y<193>gas or sacrifices, the Somay<193>gas were ç
performed with the soma juice, the soma plant being a special kind ç
of creeper. This creeper had to be crushed for extracting the juice ç
and then filtered. The strainer was the da·<193>pavitra and the vessel ç
into which the juice would get collected, the dro<207>akala·a.
The da·<193>pavitra was made of the wool cut from a living ram, the ç
wool being white. The dimensions had to conform to the directions ç
given in the <185>rautas<220>tras.
@NT = Dasar<193>
@N1 = (`[festival of] ten days')
Festivals and sacred days, which are the popular manifestations of ç
any religion, are legion in Hinduism.
One of the major festivals observed throughout India is the Dasar<193> ç
festival. It is celebrated from the °·vayuja ·ukla pratipad to the ç
da·am<200> (the bright half of the month °·vayuja or °·vina, generally ç
falling in September-October), for nine days (Navar<193>tri, festival ç
of nine nights) or ten days (dasar<193> = da·a + ahar = ten days). ç
This festival takes many forms. In Bengal, Bihar and Orissa it is ç
celebrated as the Durg<193>p<220>j<193>, worship of the Divine Mother ç
Durg<193>, usually in a clay image. In Uttar Pradesh and some other ç
northern States it is observed as R<193>mal<200>l<193>, a re-enactment ç
of the R<193>ma story.
@SPACE1 = 
In Karnataka, it is a multifestival, comprising Sarasvat<200>p<220>j<193> ç
on the saptam<200>, Durg<193>p<220>j<193> on the a<218><219>am<200> ç
and °yudhap<220>j<193> (worship of weapons and implements) on the ç
navam<200> days.
The tenth day known as Vijaya-da·am<200>, again, is observed as the ç
day for immersion of the Durg<193> images after the Durg<193>p<220>j<193>, ç
wherever it is observed.
Where R<193>mal<200>l<193> is enacted, Vijaya-da·am<200> is celebrated ç
as the day of victory of R<193>ma over R<193>va<207>a, the demon-king.
It is also the day on which kings usedto start on expeditions of ç
victory or conquests for expansion. Worship of the ·am<200>v<216>k<218>a ç
(Prosopis spicigera) and the royal weapons like the sword, as also ç
the royal horse and the elephant were part of the Vijayada·am<200> ç
festival.
As per the account of various foreign travellers like Abdur Razak ç
(<MS>A.<|>D.<D> 1413-1482), Domingos Paes (<MS>A.<|>D.<D> 1520) and ç
Fernao Nuniz (<MS>A.<|>D.<D> 1536), the Dasar<193> was being celebrated ç
in all pomp and glory as a State festival with the king being giventhe ç
prime place, in Vijayanagara, the capital of the Vijayanagara empire. ç
After the fall of the empire, it was taken up by the kings of Mysore ç
State, and celebrated  in  a  grand  manner.  The celebrations are ç
continued even now, though as a peoples' festival.
See also <MS>DURG°P<188>J°, R°MAL®L°<D> and <MS>VIJAYADA<185>AM®.
@NT = D<193>·ar<193>j<210>a
@N1 = (`[the battle of] the ten kings')
See <MS>SUD°SA<D>.
@NT = Da·aratha
@N1 = (`One [who could drive his] chariot [in] ten [directions]')
Ancient Hindu mythology traces all the kings of Bharatavar<218>a (India) ç
to two primeval races: The S<220>ryava<221>·a and the Candrava<221>·a. ç
Since Ik<218>v<193>ku and Raghu were the most outstanding emperors ç
of the S<220>ryava<221>·a, the race has also been known by their names ç
as Ik<218>v<193>kuva<221>·a or Raghuva<221>·a. But, the very best ç
of all the kings of this race was R<193>ma or <185>r<200> R<193>ma, ç
considered and worshipped as an incarnation of Lord Vi<218><207>u ç
himself. Da·aratha was the father of this R<193>ma and the son of ç
another great king of this lineage, Aja.
Though the impression created by the Ayodhy<193>k<193><207><195>a ç
of the R<193>m<193>ya<207>a of V<193>lm<200>ki is that Da·aratha ç
was a weak king, a prisoner of his infatuation for his wife Kaikey<200> ç
and a doting father, he was actually a great hero and a good ruler ç
in his younger days. The very word `Da·aratha' which means `one who ç
could drive his ratha or chariot in da·a or ten directions', is proof ç
enough of his valour.
He was the king of Kosala with itscapital at Ayodhy<193>. He had ç
three queens†Kausaly<193>, Sumitr<193>, and Kaikey<200><192> who were ç
the daughters of the kings Bh<193>numanta, <185><220>rasena and A·vapati ç
Kekaya respectively. A cabinet of eight distinguished ministers, under ç
the able guidance of Sumantra, assisted him in administration.
He had a daughter called <185><193>nt<193>dev<200>, but no male issues, ç
<185><193>nt<193>devi had been adopted by the king Romap<193>da as ç
his daughter and had been married to the sage <184><218>ya·<216><209>ga.
On the advice of the royal preceptor Vasi<218><219>ha, Da·aratha performed ç
the Putra-k<193>me<218><219>i sacrifice with <184><218>ya·<216><209>ga ç
as the head-priest and was blessed with four sons. R<193>ma (from ç
Kausaly<193>), Bharata (from Kaikey<200>), Lak<218>ma<207>a and <185>atrughna ç
(from Sumitr<193>).
The four princes grew up into fine young men under the able tutelage ç
of the highly competent sage Vasi<218><219>ha.
Once, the sage Vi·v<193>mitra arrived at the court of Da·aratha and ç
requested him to send R<193>ma and Lak<218>ma<207>a with him to guard ç
the sacrifice he was conducting, against the ruinous attacks of the ç
demons M<193>r<200>ca and Sub<193>hu. Though Da·aratha was at first ç
unwilling, he later on acceded to the request of the sage (on the ç
intervention of Vasi<218><219>ha, who knew better) and sent his two ç
sons.
@SPACE1 = 
After some heroic exploits and excellent training in the arts of war ç
and peace under Vi·v<193>mitra, the youths arrived at the capital ç
Mithil<193> of the king Janaka. When the <185>ivadhanus, the mythical ç
bow of god <185>iva, was broken by R<193>ma, to win the hand of princess ç
S<200>t<193>, Janaka's daughter, Da·aratha arrived soon at Mithil<193> ç
with his entourage and took part in the marriage of R<193>ma and S<200>t<193>, ç
and also ofthe other three princes with suitable brides.
As he was getting old, he decided to instal R<193>ma as the Yuvar<193>ja ç
(crown-prince). When the preparations were in an advanced stage, Kaikey<200>, ç
under the wicked  spell  of  her  malicious  maid Manthar<193>, demanded ç
the fulfilment of the two boons Da·aratha had given her long back. ç
They were: making her son Bharata the king and banishing R<193>ma ç
to the forest for fourteen years. Unable, either to change her mind ç
or to accede to her demand, the mortally shocked Da·aratha passed ç
away. Meanwhile R<193>ma, along with his wife S<200>t<193> and brother ç
Lak<218>ma<207>a had already left for the forest as per Kaikey<200>'s ç
words, conveying the `order' of the king and father Da·aratha.
Da·aratha is said to have met this tragic end due to the curse of ç
a sage-couple whose only son he had killed by mistake, long back, ç
in his youth.
As per the description of the R<193>m<193>ya<207>a Da·aratha was ç
a good and noble king who had ruled his kingdom righteously.
See also <MS>R°M°YAØA.
@SPACE = 
@NT = Da·arathaj<193>taka
@SPACE = 
Over the centuries, the story of R<193>m<193>ya<207>a of V<193>lm<200>ki, ç
has given rise to many other literary works which are faithful adaptations ç
of the original, or, are at variance with it. The Da·arathaj<193>taka, ç
numbered as 461 in the J<193>taka Tales series, is one such, belonging ç
to the latter group. In this j<193>taka, the main story of the R<193>m<193>ya<207>a ç
has been retold in a startlingly distorted form.
Da·aratha was the king of V<193>r<193><207>as<200>. R<193>mapa<207><195>ita, ç
Lak<218>ma<207>akum<193>ra and S<200>t<193>-dev<200> were his children ç
by his chief queen. Bharatakum<193>ra was the son of his second wife ç
who became the chief queen after the death of the first. At her behest, ç
to fulfil a boon he had promised earlier he was forced to exile the ç
first three children for 14 years and hand over the kingdom to her ç
son Bharatakum<193>ra. Meanwhile he died. When R<193>mapa<207><195>ita ç
returned after the period of exile was over, he became the king.
It is strange that the J<193>taka tale narrates R<193>ma as having ç
married S<200>t<193> who was his own sister!
The view that the Da·arathaj<193>taka must have been based on a ç
much older R<193>ma story has been thoroughly discounted by scholars ç
of repute, who have shown that the case may just be the reverse!
See also <MS>R°M°YAØA.
@NT = da·at<193>la
@N1 = (`ten spans')
Hinduism allows the worship of icons or images of deities, not only ç
as their symbolical representations but as the deities themselves, ç
when imbued with their subtle presence through appropriate rites such ç
as<193>v<193>hana (inviting) and pr<193><207>aprati<218><219>h<193> ç
(infusing life).
Such images which are generally installed in temples for public worship ç
areto be prepared strictly according to the principles of m<220>rti·ilpa·<193>stra ç
or icono-graphy. The basic unit of length used in the sculpturing ç
of images is called `t<193>la' (or span). It is the measurement of ç
the palm of the hand (from the tip of the middle finger to the wrist) ç
and is equal to the length of the face (from the top of the forehead ç
to the bottom of the chin). This t<193>la is again divided into 12 ç
equal parts, each part being designated as `a<209>gula'.
While sculpturing the images, standards are prescribed, based on this ç
t<193>la (and the a<209>gulas). Hence this system is called the `t<193>lam<193>na' ç
paddhati or system.
If an image is to be `da·at<193>la,' it simply means that the total ç
height from the bottom of the feet (in the standing posture) to the ç
top of the head should be ten t<193>las.
The da·at<193>la measurement is divided into three varieties: uttama ç
(superior), madhyama (middling) and adhama (inferior). The proportions ç
are 124, 120, and 116 a<209>gulas respectively.
The da·at<193>la is the most preferred scale for making the images ç
of the major deities and their female counter parts. Itis prescribed ç
for the icons that are worshiped for getting various benefits.
See also <MS>M<188>RTI<185>ILPA<185>°STRA.<D>
@NT = Da·<193>vat<193>ras
@N1 = (`ten incarnations [of Lord Vi<218><207>u]')
To ward off the extraordinary perils to which mankind is prone†may ç
be the visitations from the demons, may be from the human malefactors†and ç
to preserve the socio-ethical order, Lord Vi<218><207>u whose duty ç
it is to preserve this world, often incarnates himself. Though such ç
incarnations are popularly considered to be ten, there is no limit ç
to their number. Nor are there any restrictions regarding the time ç
and place of their appearance. Whenever dharma declines and adharma ç
prospers he bodies himself forth to restore the balance in the world.
In the Matsy<193>vat<193>ra (Fish-incarnation), the Lord is said to ç
have saved Manu (the progenitor of mankind) and the Saptar<218>is ç
(the seven sages, mind-born sons of Brahm<193>) along with their wives ç
during the deluge. The world was repopulated through them later on.
Lord Vi<218><207>u incarnated himself as theK<220>rma (the Tortoise) ç
in order to support the mount Mandara which started sinking during ç
the churning of the ocean (samudra-mathana). The gods and demons had ç
jointly undertaken this adventure to get am<216>ta (nectar) from the ç
ocean.
Next in the series is the Var<193>h<193>va-t<193>ra (Boar-incarnation) ç
in which the Lord killed the demon Hira<207>y<193>k<218>a and lifted ç
the earth out of the flood waters in which it had been submerged. ç
This may be a symbolic representation of the extrication of the world ç
from the deluge of sin by the power of the Supreme Being.
When Prahl<193>da, the great devotee of Vi<218><207>u was being severely ç
tortured by his father, the demon Hira<207>yaka·ipu, (who was a non-believer ç
in the existence of an omnipresent and omnipotent God), Narasi<221>ha ç
(Man-lion) appeared emerging out of the pillar shown by him and killed ç
him. Being a combination of man (the best of higher creatures) and ç
lion (the best of lower creatures) Narasi<221>ha represents the best ç
of creations. Incidentally this also proves the omnipresence of God. ç
Narasi<221>ha is especially the embodiment of valour which is a divine ç
attribute and hence worshipped by rulers and warriors. His Mantra ç
is said to be very powerful, capable of destroying enemies and exorcising ç
evil.
@SPACE1 = 
When Bali, the grandson of Prahl<193>da, conquered the three worlds, ç
Indra was deprived of his heavenly kingdom. At the request of Aditi, ç
the mother of Indra, Lord Vi<218><207>u incarnated as V<193>mana (the ç
Dwarf), a young br<193>hma<207>a boy, and approached Bali who was ç
known for his munificence, for a gift of land that could be covered ç
by three steps. With the first and the second he covered the earth ç
and heaven, and with the third, he pushed down Bali to the netherworld. ç
Hence he is also known as Trivikrama, one who encompassed the world ç
with three big steps.
This myth teaches us that since even God had to resort to the dwarf's ç
form while begging, one who begs makes himself small! Secondly, a ç
true br<193>hma<207>a can conquer the three worlds by the power of ç
the spirit. These five avat<193>ras have been referred to in the various ç
sections of the Vedas.
The next five incarnations are in the human form.
Para·ur<193>ma (R<193>ma with the battle-axe) is the sixth avat<193>ra. ç
Born as the son of the sage-couple, Jamadagni and Re<207>uk<193>, ç
he exterminated the tyrannical among the K<218>attriyas led by K<193>rtav<200>rya, ç
who were oppressing the people. Whether this story has any historical ç
basis and represents the struggle for supremacy between the br<193>hma<207>as ç
and k<218>attriyas, it is difficult to say.
<185>r<200> R<193>ma, the next incarnation, met Para·ur<193>ma and ç
absorbed his power into himself. Hence the latter is sometimes considered ç
as <193>ve·<193>vat<193>ra, an incarnation by the temporary possession ç
of Vi<218><207>u's powers.
@SPACE1 = 
<185>r<200> R<193>ma, one of the two most popular incarnations of ç
the Lord Vi<218><207>u, comes next in the series. His story is too ç
well-known to need any repetition. He typifies the ideal man. His ç
story, the R<193>m<193>ya<207>a has now become an immortal epic. ç
His name is known as the `t<193>raka-mantra,' the mantra that takes ç
one across the ocean of transmigration.
Balar<193>ma, R<193>ma, the strong, the elder brother of <185>r<200> ç
K<216><218><207>a is the eighth incarnation. His many adventures include ç
the slaying of the ape Dvivida and the demon Dhenuka, shaking the ç
ramparts of Hastin<193>vati (the capital city of the P<193><207><195>avas) ç
and dragging the river Yamun<193> out of its course. The story that ç
the serpent <185>e<218>a issued forth from his mouth at the time of ç
his death gives credence to the belief that he was the incarnation ç
of <185>e<218>a. Some scholars, basing their conjecture on the weapon ç
of Balar<193>ma (the hala or plough), opine that he was an agricultural ç
hero raised to the status of an avat<193>ra in course of time.
<185>r<200> K<216><218><207>a, the ninth incarnation of Lord Vi<218><207>u ç
is, perhaps, the most popular, so much so, that he is considered P<220>r<207><193>va-t<193>ra ç
(the incarnation in toto) and all other deities are regarded as ç
his manifestations. His story and his exploits are too numerous and ç
too well-known to be mentioned here. To the average Hindu, he is the ç
supreme statesman, warrior, hero, philosopher and teacher, nay, God ç
himself. He is the great expounder of the `Song Celestial,' the Bhagavadg<200>t<193>.
The tenth avat<193>ra Kalki, is yet to come. He will descend upon ç
the earth at the end of the present age (Kali Yuga). Riding on the ç
back of a white horse, with a drawn sword, he will destroy the enemies ç
of dharma and re-establish it in all its glory.
@SPACE1 = 
This list of the ten avat<193>ras of Lord Vi<218><207>u is by no means ç
the standard one accepted by all. Taking <185>r<200> K<216><218><207>a ç
as Vi<218><207>u Himself, he is not included in some lists. His place ç
is taken over by Buddha. Insome other lists, Buddha replaces Balar<193>ma.  Iconographically  speaking, ç
Buddha seems to have disappeared from such lists only after the 15th ç
century.
Strangely enough, the purpose of the Buddha-incarnation was to mislead ç
men of low birth and genius, who had become too proficient in the ç
sacred lore and were a threat to the supremacy of the gods! This looks ç
more like a joke than a serious proposition. It is obvious that the ç
Hindus sealed the fate of Buddhism in this country by absorbing Buddha ç
into the pantheon of the avat<193>ras.
Ha<221>sa, S<193>tvata, Yaj<210>a, Datt<193>treya, Vedavy<193>sa are ç
some of the avat<193>ras included in other lists, keeping the total ç
as ten only. The number, however, rises sometimes to as high as twentythree.
See also <MS>AVAT°RAS.
@NT = Dasyus
@N1 = (`those who destroy others')
The words `°rya' and `Dasyu' are found in the <184>gveda itself ç
(vide 1.34.7; 1.100.18; 1.51.8; 1.117.21). The word `Dasyu' has ç
been used there in several senses such as: super-human enemies, human ç
foes, aborigines and so on. Some of the words used to describe them ç
give us the impression that they were flat-nosed, ugly and unclean ç
persons who did not perform the sacrificial rites (of the °ryans), ç
hated the gods and were addicted to strange practices.
@SPACE1 = 
Cumuri, <185>ambara and <185>u<218><207>a are some of the names of ç
the well-known Dasyus mentioned in the Vedas.
They were probably primitive settlers of the regions conquered by ç
the °ryans. Or, they might have been the renegades in the °ryan society ç
who were cultural outcastes. In later literature the word refers to ç
criminals committing atrocities on peace-loving people.
Indra, the lord of the gods, is sometimes referred to as `dasyuhatya' ç
(one who destroys the Dasyus).
The Iranian terms `da<209>hu' and `daqyn' are similar to the word ç
`Dasyu' and indicate a country inhabited by hostile people.
@NT = dattaka
@N1 = (`[a son] given to oneself [by others]')
The ancient sages of India gave as much importance to life in the ç
next world (pit<216>loka, the world of manes) as to the life here. ç
Hence they always hankered after an aurasaputra or a son born out ç
of the wife married as per the rules given in the dharma·<193>stras. ç
It was this son (or sons) who had the right to the property of his ç
father and also perform the ·r<193>ddha ceremony after his death. ç
(See <MS><185>R°DDHA.)
If a person had no children from his wife, he was permitted to adopt ç
a son who was called `dattaka.' In course of time elaborate rules ç
were framed for the process of adoption.
Every male Hindu who is a major and of a sound mind can adopt a son, ç
if he himself has no son or grandson or near (male) relative, who ç
is eligible to perform the ·r<193>ddha after his death. The boy to ç
be adopted must be from the same caste.
@SPACE1 = 
The primary right to give a son for adoption rests with the natural ç
father. The mother can also do so provided she gets the consent of ç
her husband or is a widow.
Persons having more than one sononly can give a son for adoption ç
by others. They should not, however give the eldest son.
If there is only one son, he should not be given away in adoption. ç
However, even this has been sometimes allowed on the condition that ç
the boy should be considered as the son of both the natural father ç
and adopting father. In such cases, the adopted boy is called `dvy<193>mu<218>y<193>ya<207>a'.
The procedure of adoption given in the dharma·<193>stras has several ç
steps. The more important ones are: fasting by the adopter the previous ç
day, offering madhuparka (See <MS>MADHUPARKA<D> for details.) to the ç
officiating priest, performance of the dattahoma using <184>gvedic ç
verses, holding both hands of the boy symbolic of receiving him into ç
ones own family and offering of boiled rice.
By such an adoption, the boy now becomes like an aurasaputra or natural ç
son, enjoying all the rights and privileges and also bound to discharge ç
all the duties and responsibilities.
If a natural son is born to the adopter later on, then the dattaka ç
gets only one-fourth share in the property.
Though adoption was confined mostly to boys, girls too could be adopted. ç
The two famous examples in our epics are those of <185><193>nt<193> ç
the adopted daughter of Romap<193>da and Kunt<200>, of Kuntibhoja.
@SPACE = 
@NT = Datt<193>treya
@N1 = (`One [who was] given to Atri')
@SPACE = 
Hindu mythology abounds in stories of Lord Vi<218><207>u's avat<193>ras ç
or incarnations which may be p<220>r<207><193>vat<193>ras (full manifestations) ç
like <185>r<200>k<216><218><207>a or a<221>·<193>vat<193>ras (partial ç
manifestations) like Kapila or even <193>ve·<193>vat<193>ras (temporary ç
infilling of the divine power) like Para·ur<193>ma. Datt<193>treya ç
is regarded as an a<221>·<193>vat<193>ra.
He was the son of the sage Atri and Anas<220>y<193>, one of the paragons ç
of wifely virtues and chastity in the mythological lore. According ç
to one of the accounts, Atriwho was childless, performed severe austerities ç
to please God and obtain a worthy son. All the three deities of the ç
Hindu Trinity†Brahm<193>, Vi<218><207>u and <185>iva† appeared before ç
him and granted his desire by being born through their aspects, as ç
three sons: Brahm<193> as Candra, Vi<218><207>u as Datta and <185>iva ç
as D<220>rv<193>sas.
According to another version, the three who came to test the chastity ç
of Anas<220>y<193> were transformed into a child with three heads ç
and six arms! This is how Datt<193>treya was born.
Datt<193>treya also called `Datta'†has been described as a great sage, ç
counted among the saptar<218>is or seven sages in theSv<193>roci<218>a-manvantara. ç
(See <MS>MANVANTARAS<D>.) He was the originator of certain magical ç
rites and the creator of the soma plant. Sometimes pictured as a teacher ç
of non-°ryan races he has been described as ritually impure. However, ç
his powers of knowledge and enlightenment are so great that no impurity ç
can ever taint him.
@SPACE1 = 
The great king K<193>rttav<200>ry<193>rjuna was a disciple of his.
A cult designated as the Datta- samprad<193>ya has grown round him. ç
It still prevails in Maharashtra, Andhra Pradesh and Nepal. His temples ç
are generally called `Dattamandira' and it is his wooden sandals that ç
are normally installed and worshipped. His temples are at M<193>h<220>r ç
(Maharashtra) G<193><207>ag<193>pura (Karnataka) and W<193><195>i ç
(Maharashtra). There is an old shrine on one of the peaks of the Girnar ç
Hill in Gujarat.
The sect of the Mah<193>nubh<193>vas, started by Cakradhara (<MS>A.<|>D.<D> ç
1263) in Maharashtra considers Datt<193>treya as a perfect manifestation ç
of the Godhead.
Iconographically Datt<193>treya may be shown with three heads and ç
six hands, holding the emblems of Brahm<193>, Vi<218><207>u and <185>iva ç
such as kama<207><195>alu (water pot), ·a<209>kha (conch), cakra (discus) ç
and tri·<220>la (trident). A bull (v<216><218>abha, representing dharma ç
or righteousness) is shown as his mount. Sometimes, four dogs (representing ç
the four Vedas) are also shown as his constant companions.
The well-known treatise of Advaita Ved<193>nta, the Avadh<220>tag<200>t<193>, ç
has been attributed to his authorship.
The Datt<193>treya concept may be an attempt at harmonising the three ç
cults of Brahm<193>, Vi<218><207>u and <185>iva. It may also have ç
been the medium through which non-Vedic cults were brought into the ç
Hindu fold.
@SPACE = 
@NT = Datt<193>treya Upani<218>ad
@SPACE = 
This is a minor Upani<218>ad belonging to the cult of Vi<218><207>u ç
and classed among the ones of the Atharva<207>aveda. There are three ç
kha<207><195>as or sections and a total of nine long mantras, all ç
in prose, except one.
The  four-faced  Brahm<193>  once approached N<193>r<193>ya<207>a, ç
the Supreme Lord of the  universe  in  the  Satyak<218>etra†the region ç
situated between the rivers Ga<209>g<193> and Yamun<193>†and requested ç
him to teach that transcendental wisdom by which one can become free ç
from the rounds of birth and death. N<193>r<193>ya<207>a advised him ç
to meditate upon his Abode of pure sattva (the quality of substance ç
of purity and effulgence). Those who meditate thus and realise that ç
the Lord is `Datta,' since he gives (datta = what is granted or given) ç
the knowledge of Brahman, and also declare it to others, will never ç
again be bound  in  sa<221>s<193>ra  or  transmigratory existence.
Having been instructed by N<193>r<193>ya<207>a thus, Brahm<193> meditated ç
upon the Datt<193>treya aspect of N<193>r<193>ya<207>a and taught ç
it as Sat (the eternal Truth) to others.
Next, a series of mantras of Datt<193>treya are given, classifying ç
them as ek<193>k<218>ara (one-lettered), <218>a<195>ak<218>ara (six ç
lettered) and so on.
@NIDX = They are:
@NOX = (1)
@PK = d<193>m<F49P11M>f<F255P255D>
@NOX = (2)
@PK = O<221> ·r<200><221> hr<200><221> kl<200><221> glau<221> dr<193>m<F49P11M>f<F255P255D>
@NOX = (3)
@PK = dr<193><221> datt<193>trey<193>ya nama<199><F49P11M>f<F255P255D>
@NOX = (4)
@PK = Om <193><221> hr<200><221> krom ehi<R>ç
datt<193>treya sv<193>h<193><F49P11M>f<F255P255D>
@NOX = (5)
@PK = Om ai<221> kro<221> kl<200><221> kl<220><221> hr<193><221> hr<200><221> ç
hr<220><221> sau<199> datt<193>trey<193>ya<|>sv<193>h<193><F49P11M>f<F255P255D>
@NOX = (6)
@PK = datt<193>treya hare k<216><218><207>a<R>ç
unmatt<193>nandad<193>yaka<F49P11M>e<F255P255D><R>ç
digambara mune b<193>la<R>ç
pi·<193>ca j<210><193>nas<193>gara<F49P11M>f<F255P255D>
The next section gives a very long mantra, called `m<193>l<193>mantra'. ç
It begins thus:`O<221> namo bhagavate datt<193>trey<193>ya smara<207>am<193>tra-santu<218><219>aya....' ç
and so on. It ends with the words, `O<221> nama··iv<193>ya ityupani<218>at.'
The third or the last section delineates the fruits of the practice ç
of this esoteric science. The results he will get will be equal to ç
that got by repeating the G<193>yatr<200>mantra one lakh times or ç
the Mah<193>rudramantra one lakh times and soon. He purifies a hundred ç
of his predecessors and a hundred of his descendants. He is never ç
tainted even by the most heinous of sins like killing a cow. The knowledge ç
of all mantras and yogas accrue to him of their own accord. In other ç
words he becomes a j<200>vanmukta, one liberated even while living.
See also <MS>DATT°TREYA<D> and <MS>UPANI<186>ADS.
@NT = daurmanasya
@N1 = (`frustration')
Full control over one's own mind is a virtue that we often hanker ç
for. Pata<210>jali (200 <MS>B.<|>C.<D>) the great master of Yoga, had ç
dealt with this topic from two standpoints. In the negative aspect, ç
one should try constantly to avoid or overcome the various obstacles ç
that disturb our mental balance or concentration. In the positive ç
aspect, repeated efforts should be made to tackle the mind directly ç
and control it.
Pata<210>jali in his Yogas<220>tras lists nine major obstacles†which ç
he calls `antar<193>yas' †and five minor ones (vide 1.30, 31) to ç
the control of mind. `Daurmanasya' is listed as the second in the ç
list of minor impediments. Literally it means `being in a bad state ç
of mind' (dur = bad, manas= mind). In effect, it refers to the frustration ç
one gets when one's desires are unfulfilled or thwarted.
It is neither possible nor desirable to fulfil all our cravings and ç
ambitions. Hence we should take recourse to discrimination and be ç
convinced that desire is the root-cause of all our troubles. Once ç
the intensity of desire is lessened, the shock of disappointment also ç
will be lessened. If and when it is completely eliminated, the problem ç
is permanently solved.
@NT = day<193>
@N1 = (`compassion')
Showing day<193> or compassion to all the living creatures and not ç
harming them has been a basic moral discipline enjoined on all, in ç
Hinduism.
The word `day<193>' has been defined in various ways:
@IN2 = (1)
@IN2K = The desire that arises in one's heart to mitigate the sufferings ç
of others by putting forth the necessary effort.
@IN2 = (2)
@IN2K = The desire to do good to others even as one wishes that others ç
should do towards oneself.
The Dev<200>bh<193>gavatam (1.15.60) des-cribes Day<193> as one ç
of the eight female companions  accompanying  the  Dev<200> (Divine ç
Mother).
The word is also used as an appellation for Lak<218>m<200>, the consort ç
of Vi<218><207>u, since she is the very personification of compassion ç
towards all the living beings who are her children.
Ved<193>nta De·ika (<MS>A.<|>D.<D> 1268-1370), the celebrated teacher ç
of the R<193>m<193>nuja school, has composed an exquisitely moving ç
hymn called Day<193>·atakam on Lak<218>m<200> as Day<193>.
@NT = D<193>yabh<193>ga
@N1 = (`Division of estate')
The dharma·<193>stras are the law-books guiding the Hindu society ç
over the centuries. They contain enough material regarding civil as ç
well as criminal topics.
The sm<216>tis (secondary scriptures), nibandhas   (digests)   and   pur<193><207>as ç
(mythological works) are the main components of these dharma·<193>stras.
One of the topics that has been discussed in great detail in these ç
works is that of division of ancestral property and the rules for ç
inheritance. On the whole, there has been a broad twofold system prevailing ç
in the country, for nearly a thousand years.
They are: the Mit<193>k<218>ar<193> school and the D<193>yabh<193>ga ç
school.
The Mit<193>k<218>ar<193> or <184>jumit<193>k<218>ar<193> is a ç
magnificent commentary by Vij<210>ane·vara (12th cent. <MS>A.<|>D.<D>) ç
on the ancient work, Y<193>j<210>avalkya Sm<216>ti. The D<193>yabh<193>ga ç
is an independent work, a digest, written by J<200>m<220>tav<193>hana ç
(<MS>A.<|>D.<D> 1100). It has a standard commentary called D<193>yatattva ç
by Raghunandana (<MS>A.<|>D.<D> 1510-1580).
The  two  schools  depend  almost entirely on these works.
The Mit<193>k<218>ar<193> school is the authority accepted all over ç
India except in Bengal (including Bangladesh). However the D<193>yabh<193>ga ç
school seems to be a binding authority in Bengal.
According to the Mit<193>k<218>ar<193> law, a son, as soon as he was ç
born, became a coparcener (joint owner) with his father in the ancestral ç
property inherited by him. But in the D<193>yabh<193>ga system the ç
son did not automatically acquire that right just by birth.
@SPACE1 = 
The father, during his life-time, could alienate the property or give ç
it to his children or prepare a will according to his desire. None ç
had the right to question it. If the person passed away without issues, ç
his widow became the owner of that property and not his brothers or ç
other relatives.
@NT = Day<193>nanda Sarasvat<200>, Sv<193>m<200>
@N1 = <R>ç
(<MS>A.<|>D.<D> 1825-1883)
@EMERGENCY = The growth and development of any religion and culture ç
depend to a great extent on the freedom of thought and action, that ç
its votaries enjoy. If Hindu religion and culture have survived the ç
onslaughts of time and change, it is not a little due to this freedom ç
and the reform movements that it engenders. One of the effective and ç
largely successful reform movements of the 19th century is the °ryasam<193>j ç
Movement. Svam<200> Day<193>nanda Sarasvat<200> was its founder.
@EMERGENCY = He was born in <MS>A.<|>D.<D> 1825, in the small town ç
of <187>a<209>k<193>ra in the Morvi district of Gujarat as the son ç
of Amb<193>·a<209>kar Tiv<193>r<200> and Am<216>t<193>b<193><200>. ç
His original name was M<220>la·a<209>kara. Being born in an orthodox ç
br<193>hma<207>a family, he underwent the usualreligious sacraments ç
like upanayana (investiture with the sacred thread) and Vedic studies ç
as also performing religious rites.
The free movement of a little rat on the <185>ivali<209>ga on a <185>ivar<193>tri ç
day, became the turning point in his life and in his attitude towards ç
image worship as also ritualistic religion. He developed a great abhorrence ç
for the same.
The death of his uncle and a sister made him more introvert and philosophical. ç
One day, when preparations for his marriage were going on, he managed ç
to slip away from his house, never to return again.
He started travelling from place to place, in search of a competent ç
guru or spiritual teacher. After studying some Ved<193>ntic texts ç
under Sv<193>m<200> Brahm<193>nanda and Paramaha<221>sa Param<193>nanda, ç
he was ordained into sa<221>ny<193>sa or monastic life by one Sv<193>m<200> ç
P<220>r<207><193>nanda Sarasvat<200>.
From then onwards he came to be known as Sv<193>m<200> Day<193>nanda ç
Sarasvat<200>.
It was actually Sv<193>m<200> Viraj<193>nanda Sarasvat<200>, a blind ç
but erudite and a highly evolved soul, that fulfilled the spiritual ç
aspirations of Day<193>nanda. After intensive study and training under ç
Him for about three years, Day<193>nanda set out on his life's mission ç
as per the directions of his guru Viraj<193>nanda.
@SPACE1 = 
Propagation of the pure Vedic religion based entirely on the Sa<221>hit<193>s ç
was the main task assigned to him by his guru.
Now began his relentless fight against the various unhealthy accretions ç
to the Vedic religion as also the assaults on Hinduism by the Semitic ç
religions. He prepared himself for this onerous task by practising ç
severe austerities for two years in a garden in Agra.
During his ceaseless travels all over the country he mercilessly shattered, ç
through his incisive logic and vast know-ledge of the Vedas, the various ç
opinions and practices of the pundits. He successfully roused the ç
religious conscience of the masses. He also reconverted many people ç
who had gone out of the Hindu fold and even gave them the G<193>yatr<200>-mantra, ç
which he considered as a universal mantra and the common property ç
of all the Hindus.
His insistence on the original Vedic religion as true Hinduism, his ç
call to ignore the caste system as a man-made accretion and his stress ç
on the var<207>a system based, not on birth, but on character, earned ç
him a very large following, especially from the deprived sections ç
of the society.
However, his ruthless condemnation of many ritualistic and other practices ç
in the Hindu society based on the secondary scriptures like the pur<193><207>as, ç
created many enemies for him. His criticism of Islam and Christianity ç
as also his campaign for reconversion of those who had left Hindu ç
religion roused the wrath of the Muslims and the Christians. Several ç
attempts were made against his life.
Day<193>nanda established the °rya Sam<193>j at Bombay in 1875 with ç
a creed of 28 principles which he later reduced to 10 in the revision ç
he himself made, in 1877. (See <MS>°RYASAM°J<D> for details.) He passed ç
away in 1883 being poisoned by his own cook, whom he forgave and helped ç
to escape!
By his pure life, fearless and uncompromising adherence to the principles ç
of his conviction, crusades against the forays into the Vedic religion ç
by others and scholarly works like the Saty<193>rthaprak<193>·a (in ç
Hindi) as also Sanskrit commentaries on some portions of the Vedas, ç
Day<193>nanda has carved out a permanent place for himself in Hinduism.
See also <MS>SATY°RTHAPRAK°<185>A<D>.
@NT = deh<193>tmav<193>da
@N1 = (`the doctrine [that the] body [itself is] the self<|>')
Indian philosophical systems have been broadly divided into two streams: ç
the <193>stika and the n<193>stika. The former accept the Vedas as ç
the final authority whereas the latter do not. One of the three systems ç
of the latter group is the C<193>rv<193>ka system. Its founder is ç
said to be one C<193>rv<193>ka or the reputed sage B<216>haspati.
The word `C<193>rv<193>ka' might have been derived from its etymology ç
as `one who speaks sweetly' (c<193>ru = sweet, v<193>k = speech) or ç
as `one who preaches the doctrine of ``eat drink and be merry'' (carv= ç
to eat)'. Inother words it stands for Indian materialism.
According to this system, there is no permanent abiding <193>tman ç
or soul different from and beyond the deha or the physical body. The ç
deha (body) itself is the <193>tman (the soul). The very fact that ç
we say, `Iam stout,' `I am lean,' `I am sick' and so on, shows that ç
we are, in reality, the body.
There is of course consciousness in a living body. But this is a product ç
of the elements of matter like earth and water even as fermentation ç
of certain articles develops the power of intoxication.
The survival of man after death in any form, is unseen and unproved.
Hence make the best of this world even while living here and do not ç
bother about the hereafter.
This is the gist of this school of materialism.
@SPACE = 
@NT = Deoghar
@N1 = (`the house of God')
@SPACE = 
Deoghar†corrupted form of Devag<216>ha (`house of God')†is a town ç
situated in the Santhal Parganas of the Jharkhand State. It is famous ç
for its temple of Vaidyan<193>tha or Baidyan<193>th (<185>iva), one ç
of the twelve Jyotirli<209>gas (See <MS>JYOTIRLI<177>GAS<D>.). Other ç
names by which it was known are: Har<200>tak<200>vana, Ketak<200>vana, ç
R<193>va<207>avana, Cit<193>bh<220>mi and H<193>rdap<200><219>ha. ç
Probably it was a forest of trees of inknuts (har<200>tak<200>) or ç
fragrant screwpine flowers (ketak<200>).
According to the local legends, whenR<193>va<207>a got the <185>ivali<209>ga ç
from <185>iva Himself to be taken to La<209>k<193>, the gods contrived ç
to get it fixed to the ground on the way itself. This place has now ç
become the present Vaidyan<193>tha.
This is also the place where the h<216>daya or the heart of Sat<200>'s ç
body (cut by Vi<218><207>u, by his discus) is said to have fallen. ç
Hence the name H<193>rdap<200><219>ha (seat of the heart of Sat<200>), ç
one of the 52 <185>aktip<200><219>has (places of <185>akti or the ç
Divine Mother).
The temple of Vaidyan<193>tha <185>iva is a simple structure with ç
a pyramidal tower 26.5 metres (72 feet) in height. It faces east. ç
The li<209>ga is cylindrical in form. It is 10 cms (4 inches) high. ç
The diameter is 12.7 cms. (5 inches). The top of the li<209>ga is ç
uneven.
There are different porches, some containing pillars and hanging bells.
Near the main entrance there is a well called Candrak<220>pa (`well ç
of Candra or the Moon'). It is said to contain the essence of all ç
the holy rivers and lakes.
A little away is the <185>ivaga<209>g<193>†a large tank measuring ç
270 metres by 180 metres (900 feet by 600 feet)†with an embankment. ç
It is also called M<193>nas- sarovar.
@SPACE1 = 
The rituals followed in the temple are very simple, like bathing the ç
li<209>ga with water, smearing with sandal paste and offering bilva ç
leaves as also flowers.
There are pilgrims who bring water from the Ga<209>g<193> near Badar<200>n<193>th ç
or even the M<193>nas-sarovar (in Tibet) just to bathe this li<209>ga.
Persons suffering from serious ailments or with unfulfilled desires ç
observe certain simple vows as lying on the bare ground and drinking ç
the holy water with which the li<209>ga has been bathed. They observe ç
it for three days. The redemption is believed to come with revelations ç
during a dream.
There are eleven other shrines in the courtyard of the temple dedicated ç
to deities like Lak<218>m<200>-N<193>r<193>ya<207>a, P<193>rvat<200>, ç
K<193>l<200>, Ga<207>e·a, Sarasvat<200>, R<193>ma and others.
If the present temple of Vaidyan<193>tha was renovated or rebuilt ç
in <MS>A.<|>D.<D> 1596 by one P<220>ra<207> Mal, the others have come ç
up during the period <MS>A.<|>D.<D> 1630 to 1813, built by several ç
others.
@NT = devad<193>s<200>s
@N1 = (`servant-maids of God')
Human beings have a strong tendency to cast their gods also in their ç
own mould. The things we like and love to possess or enjoy here must ç
be dear to God too and hence he should not be deprived of them! This ç
appears to be the logic behind the devad<193>s<200> system.
Dedicating grown-up girls to the service of God in temples and places ç
of worship seems to have been an ancient practice. It existed in Babylonia, ç
Cyprus, Phoenicia, Greece, Mesopotamea, Syria and Arabia, as also ç
some countries of the South-East.
When exactly this custom began in India, is difficult to say. According ç
to some sociologists, it might have started in the 3rd century <MS>A.<|>D.,<D> ç
though in the image of a female dancer discovered at Mohenjo D<193>ro ç
(2500 <MS>B.<|>C.<D>) some archaeologists `see' a devad<193>s<200>.
The custom might have existed throughout India, but much more in the ç
South than in the North.
@SPACE1 = 
Those who were dedicated to the godin a temple were often married ç
ceremonially to the image. Thereafter they were to serve that god ç
devotedly.
The duties of a devad<193>s<200> were, in general, as follows: Keeping ç
the temple precincts clean and neat; preparing flower garlands and ç
other decorative materials for the deity; music and dancing, as a ç
part of the temple rituals and so on.
They were expected to be adepts in music and dancing. Hence they were ç
specially trained in this art.
A lady could become a devad<193>s<200> in several ways. Seven such ç
ways have been mentioned in the relevant works. They are:
@N-2 = (1)<+><+>datt<193>†
@IN2 = One who has offered herself to a temple.
@N-2 = (2)<+><+>vikr<200>t<193>†
@IN2 = One who has sold herself to a temple.
@N-2 = (3)<+><+>bh<216>ty<193>†
@IN2 = One who has given herself to the temple for the upkeep of her ç
family.
@N-2 = (4)<+><+>bhakt<193>†
@IN2 = One who has chosen to become a devad<193>s<200> out of devotion ç
to the Lord.
@N-2 = (5)<+><+>h<216>t<193>†
@IN2 = One who has been abducted and offered to a temple.
@N-2 = (6)<+><+>ala<209>k<193>r<193>†
@IN2 = One who was offered to a temple by a king or his minister as ç
per some tradition.
@N-2 = (7)<+><+>rudraga<207>ik<193> or gopik<193>†
@IN2 = One appointed for singing and dancing in a temple as a profession.
@SPACE1 = 
In some of the edicts found in Karnataka, the service to a god in ç
a temple
