@NID = has been classified into two kinds: a<209>ga-bhoga and ra<209>gabhoga. ç
The former consists of direct services to the image like bath, anointing ç
with sandal paste, burning of incense and waving of lights, offering ç
flowers and food articles and so on. The latter comprises mainly music ç
and dancing by the devad<193>s<200>s.
Enough provision used to be made for their maintenance by the kings ç
or the society through grant of lands, money and materials.
They were also given a place of honour in the society.
Whatever might have bean the original intentions behind this system†noble ç
or devotional†it soon degenerated into prostitution with a `divine' ç
sanction. It also gave rise to exploitation of the weaker sex in the ç
name of religion.
Though several serious attempts havebeen made to eradicate it through ç
punishments to the agents or reformation of the devad<193>s<200>s ç
themselves, the success achieved has not been commensurate with the ç
efforts.
Remnants of the custom continue to exist even today in some parts ç
of Karnataka (jogiti tradition in the Ellamma temple at Saundatti, ç
Belgaum district), Goa, Maharashtra (where the devad<193>s<200>s are ç
called `bh<193>vins') and Tamil Nadu.
@NT = Devah<220>ti
In  imitation  of  the  well-known Bhagavadg<200>t<193>, a number ç
of other G<200>t<193>s have appeared in the later religious literature ç
of Hinduism. One of them isthe Kapilag<200>t<193> from the Bh<193>gavatam ç
(3.25-33). Here, the great sage Kapila, reputed to be an incarnation ç
of Lord Vi<218><207>u, teaches S<193><209>khya or spiritual wisdom, ç
to his own mother Devah<220>ti.
Devah<220>ti was the second of the threedaughters of Sv<193>yambhuva ç
Manu. She was married to the sage Kardama and gave birth to nine daughters ç
including Arundhat<200> (wife of the sage Vasi<218><219>ha) and Anas<220>y<193> ç
(the paragon of wifely virtues and the wife of the great sage Atri) ç
and a son, Kapila.
Kapila was Vi<218><207>u himself born as their son. When Kardama left ç
for the forest to lead a life of retirement and austerities,  he  advised  Devah<220>ti  to ç
approach their divine son for spiritual knowledge. Accordingly Kapila ç
taught her S<193><209>khya·<193>stra. After teaching her, Kapila too ç
departed for the forest.
Then Devah<220>ti performed a sacrifice on the banks of the Sarasvat<200> ç
river and did severe austerities. She thus realized the Truth and ç
gave up the body.
See also <MS>KAPILA<D> and <MS>KARDAMA.<D>
@NT = Devak<200>
One of the several epithets of <185>r<200> K<216><218><207>a is `Devak<200>nandana,' ç
`One who gives joy to Devak<200>'. Devak<200> was his mother and Vasudeva, ç
the father.
Devak<200> was one of the seven daughters of King Devaka of the race ç
of Yadus. She and Vasudeva were P<216>·ni and Sutap<193> in a previous ç
life. They had performed severe penance and had asked the boon from ç
Vi<218><207>u that he should be born as their son in a future incarnation.
After marriage to Vasudeva, when the tyrant Ka<221>sa, her cousin, ç
was taking the couple out in a chariot driven by himself, a voice ç
from the void predicted that her eighth child would kill him. This ç
enraged Ka<221>sa so much that he tried to kill her then and there. ç
Her life was saved on the intervention of Vasudeva who promised to ç
hand over all the children born of her. Ka<221>sa imprisoned the couple ç
and killed all the six babies born to them one after another. The ç
seventh baby was mysteriously transferred to the womb of Rohi<207><200>, ç
the elder wife of Vasudeva. He was Balar<193>ma, the elder brother ç
of <185>r<200> K<216><218><207>a. The eighth child was <185>r<200> ç
K<216><218><207>a who later on killed Ka<221>sa, to the great relief ç
of all.
After the exit of <185>r<200> K<216><218><207>a from the world and ç
the death of Vasudeva, Devak<200> along with Rohi<207><200>, gave ç
up her body in the funeral fire (in sahagamana).
@NT = Devala
Sages†known as <216><218>is and munis† were always held in high esteem ç
in ancient India. The fact that Arjuna, the principal hero of the ç
Mah<193>bh<193>rata war, mentions the name of Asita-devala (`Devala, ç
the dark one') among the great sages (vide Bhagavadg<200>t<193> ç
10.13), shows that Devala was an ancient and highly respected sage. ç
Devala has been described in the Mah<193>bh<193>rata (°diparva ç
67) as the son of Praty<220><218>a who was one of the eight Vasus. ç
(See <MS>A<186><187>AVASUS.<D>) He was a brahmar<218>i (the highest ç
status accorded to a sage in the scriptures). Dhaumya, another <216><218>i, ç
who was the chief priest of the P<193><207><195>avas, was his brother.
He is said to have been present at the Sarpay<193>ga (snake-sacrifice) ç
conducted by the king Janamejaya (the son of Par<200>k<218>it, grandson ç
of the P<193><207><195>ava hero Arjuna).
In  the  dharma·<193>stra  literature, mention is often made of the ç
Dharmas<220>tra of Devala. He has been profusely quoted by other, ç
later, writers. Even <185>a<209>kara (<MS>A.D.<D> 788-820) mentions ç
his name. The work itself, however, has not been traced till now. ç
Even if all that is quoted from his work by other writers is collected, ç
edited and published, it will prove to be a valuable addition to the ç
extant dharma-·<193>stra works.
@NT = dev<193>laya
@N1 = (`house of God')
See <MS>HINDU TEMPLES.
@NT = Deva<207><207>abha<219><219>a
Hindu scriptures have been broadly divided into two groups: <185>ruti ç
and sm<216>ti.
The Vedas including the Upani<218>ads are the <185>ruti. All other ç
secondary works like itih<193>sas, pur<193><207>as, sm<216>tis of ç
Manu andothers, as also dharma·<193>stras, are clubbed together under ç
the omnibus term `sm<216>ti'.
Since the Vedas deal only with the spiritual and otherworldly matters, ç
gradually, a vast class of a special literature dealing more explicitly ç
with the life here and now, both at the individual and at the social ç
level, developed. This came to be known as `dharma·<193>stras'.
If some of the more ancient books among the dharmas<193>stras like ç
the sm<216>tis of Manu and Y<193>j<210>avalkya or the dharma-s<220>tras ç
of °pastamba or Baudh<193>yana did pioneering work in the field, later ç
writers put forth a commendable effort in preparing compilations and ç
digests culling the relevant topics from the earlier canonical literature.
One such well-known digest is the Sm<216>ticandrik<193> of Deva<207><207>bha<219><219>a, ç
who was also known by other names such as Deva<207><207>a-bha<219><219>op<193>dhy<193>ya, ç
Deva<207>a, Dev<193>-nanda and Devaga<207>a. He was the son of Ke·ava-bha<219><219>op<193>dhy<193>ya ç
and might have existed in the 12th century <MS>A.<|>D.<D>
The Sm<216>ticandrik<193> is an extensive digest and its author ç
claims that he has only collected in one place the opinions of various ç
authorities, adding nothing of his own. He quotes profusely from several ç
sources and earlier authors. He refers to Vij<210><193>ne·vara (author ç
of Mit<193>k<218>ar<193> on the Y<193>j<210>avalkya Sm<216>ti) ç
with great respect though he differs from him on several points.
The contents of the work may be briefly summarised as follows: Various ç
sa<221>sk<193>ras or sacraments; duties of brahmac<193>rins (Vedic ç
students) and g<216>hasthas (house-holders); daily duties such as ç
sandhy<193>, ·rauta and sm<193>rta rites; procedure of law-courts, ç
partnership rules; d<193>yabh<193>ga (See <MS>D°YABH°GA.<D>); details ç
about ·r<193>ddha and so on.
Some other writers too†like <185>ukadevami·ra and °padeva†have named ç
their works as Sm<216>ticandrik<193>, but they are not so well-known.
Deva<207><207>abha<219><219>a is said to have written another work, ç
on music and dancing, called Sa<209>g<200>tamukt<193>val<200>.
@NT = Dev<193>pi
Dev<193>pi was the elder brother of the king <185>antanu (father of ç
Bhi<218>ma and great- grandfather of the P<193><207><195>avas).
He was the eldest son of the kingPrat<200>pa of Candrava<221>·a (the ç
Lunar dynasty) by his queen Sunand<193>.
Though he succeeded his father to the kingdom, he was forced to abdicate ç
by the people in favour of <185>antanu, since he became afflicted ç
with leprosy. (Incidentally, this shows the power that the people ç
of a country exerted on the royal house even in the ancient days.) ç
Dev<193>pi then took sa<221>ny<193>sa (monastic orders) and started ç
living independently.
During <185>antanu's rule, the country faced a severe famine. Then ç
<185>antanu went to Dev<193>pi, offered his apology and requested ç
for his blessings. Soon afterwards, there were heavy rains and people ç
were saved from the calamity of starvation.
Dev<193>pi is also the name of another person, a k<218>attriya by ç
birth, who attained br<193>hma<207>ahood through tapas or austerity.
The king of the Cedi country who fought on behalf of the P<193><207><195>avas ç
in the Kuruk<218>etra war and was killed by Kar<207>a was also known ç
as Dev<193>pi.
@NT = devap<220>j<193>
@N1 = (`worship of God or a deity')
Throughout the history of mankind, human beings have been seeking†whether ç
they know it or not†unalloyed happiness or bliss. Freedom from suffering ç
and attainment of eternal peace and joy, have been the universally ç
acclaimed goals of life.
From times immemorial, a firm belief in the existence of a Supernatural ç
Being, omniscient and omnipotent, seems to have been ingrained in ç
the very nature of man. By somehow establishing a contact with this ç
Being, often called `God', one can get whatever one wants in life. ç
This is the conviction resulting from this belief.
Hinduism proclaims that this God is both nir<193>k<193>ra and nirgu<207>a ç
(without any particular form or attributes) as also s<193>k<193>ra ç
and sagu<207>a (capable of assuming any form and attributes at will). ç
He can also manifest himself as a personality without any particular ç
form, but with all the blessed qualities that one can imagine. Nothing ç
prevents him, if need be, from assuming any form that a votary devotedly ç
hankers for seeing or even incarnate here in the human form to set ç
right the mess we create!
An illustration can make this point more clear. Water can exist in ç
three states: ice, liquid water and water vapour or steam. Water vapour ç
has no particular form whereas ice has. But liquid water can assume ç
the shape of the vessel into which it is poured. In all these three ç
states, vastu or substance is one and the same, though n<193>ma (nomenclature) ç
and r<220>pa (form) are different. Similar is the case with God.
Though Hinduism concedes that the gaining of freedom from all suffering ç
and attainment of eternal bliss, are possible by adopting any one ç
of the four well-known yogas (paths of spiritual disciplines)† J<210><193>nayoga,  Bhaktiyoga,  R<193>jayoga  and ç
Karmayoga†Bhaktiyoga or the path of bhakti (devotion to God in his ç
s<193>k<193>ra sagu<207>a aspect) is, comparatively speaking, much ç
easier in this age, characterised as it is, by an excessive attachment ç
to the physical body and (consequently) to physical comforts.
Once  this  is  acknowledged,  the necessity for and the role of rituals ç
in this path of bhakti can easily be recognised and appreciated.
@SB = Necessity of Rituals
By the word `rituals,' certain religious observances and practices ç
performed in a systematic way as per the directions given in the scriptures ç
are meant. P<220>j<193> (worship of God or a deity), sandhyop<193>san<193> ç
(meditation on God as the light of knowledge and wisdom at dawn and ç
dusk), homa (offering of oblations unto a deity in a duly consecrated ç
fire), upav<193>sa (ceremonial fasting) and j<193>gara<207>a (keeping ç
vigil at night as a part of spiritual discipline)†all these are rituals.
The philosophical truths contained in the Vedas, Upani<218>ads and ç
other similar scriptural works are, very often, too recondite to comprehend. ç
Apart from an incisive intellect, purity of mind resulting from a ç
pure sinless life is necessary to understand them. Performance of ç
rituals is one of the easier means to achieve this purity of mind. ç
However they should be done meticulously with a proper knowledge of ç
the spirit behind them.
@SB = Need for Icons
A great majority of human beings are incapable of even conceiving†let ç
alone contemplate upon†God as the Supreme Power or Intelligence without ç
any particular name or form. This is because of the limitation imposed ç
by the body-mind complex and the consequent identification with it. ç
However, an icon†an image or a picture or even a symbol†can definitely ç
help in this process of contemplation, even as a limited window in ç
our room gives us a view of the unlimited sky as long as we are sitting ç
in it.
If the symbolical meaning and signi-ficance of the icon is understood ç
properly, the icon itself will become an actualised form of the ideal. ç
Then, viewing it will be almost as good as viewing the original it ç
represents. It is akin to remembering a person when we look at his ç
photograph.
We may also look at it in another way. An abacus is needed (and used) ç
to teach certain fundamental concepts of arithmetic, to little children. ç
Similarly an icon, especially the one installed in a temple, along ç
with the associated ideas, can help us to conceive of and contemplate ç
on God.
Icons or concrete symbols have played a prominent part in all religions.
@SB = Image Worship
Worship of images, both at home and in temples, as well as in public ç
places of worship is widespread and popular in Hinduism. There is ç
a mistaken notion that this is pure and simple idolatry. When in idolatry, ç
the physical symbol itself is revered as God, in image worship, the ç
reverence is offered to God in and through the image.
Preparation of images of deities, worship to the deities through them, ç
either in one's own personal or in family shrines or even in temples ç
seems to be an ancient custom. Reference to images is found even in ç
the Vedas (vide <184>gveda 4.24.10). Worship of deities through ç
images is explicitly referred to in the R<193>m<193>ya<207>a (Ayodhy<193>-k<193><207><195>a ç
20.14, 15) and Mah<193>bh<193>rata (°diparva 70.49; Anu·<193>sanaparva ç
10.20, 21).
Often, the images are replaced by symbolical objects such as ·ivali<209>gas, ç
·<193>lagr<193>mas and yantras, and worshipped.
@SB = External and Internal Worship
Worship of God can be either internal or external. Internal worship ç
called `m<193>nasap<220>j<193>' is actually meditation which may be ç
a simple process of contemplation on the form of the deity or may ç
involve a regular ritualistic worship with all the ingredients, but ç
all done mentally.
External worship is the worship of the deity in an image or a symbol ç
with all the necessary articles needed for the worship as per the ç
religious works.
When the external worship is performed properly in the right spirit, ç
over a period of time, it may lead to greater and greater introversion. ç
As a result, external, formal, worship may drop off by itself. Then, ç
only internal worship or meditation can be continued.
@SPACE = 
@SB = The Conception of Arc<193>vat<193>ra
@SPACE = 
Some schools of devotion have put forward the theory that God descends ç
(=avat<193>ra) into the image at the time of worship (=<|>arc<193>) ç
in a subtle form when invited through appropriate mantras. It is something ç
like putting on the switch to make the electric current flow through ç
a lamp and give light.
By the same logic, when an image fixed in a temple, is consecrated ç
as per the prescribed procedure (in which pr<193><207>a-prati<218><219>h<193> ç
or infusing with life, is an important aspect), the deity `lives' ç
in that image permanently, in a divine or subtle form.
Hence the worshipper has to be extraordinarily careful while performing ç
the ritualistic worship to such consecrated images.
@SPACE = 
@SB = P<220>j<193> or Worship
@SPACE = 
Now, the various steps involved inan actual p<220>j<193> or worship ç
may be described.
Since external cleanliness and neatness are conducive to internal ç
purity, the first thing to be done before starting p<220>j<193>is ç
to clean the p<220>j<193>-room and the surrounding area thoroughly. ç
Of course, it goes without saying, that the worshipper should take ç
bath and wear washed and clean clothes for the p<220>j<193>. It may ç
be a good custom even to keep two sets of clothes to be worn (by turns) ç
only at the time of ritualistic worship.
After arranging all the vessels and materials needed for the p<220>j<193> ç
properly, the worshipper should sit on the p<220>j<193>-seat (which ç
should be used only for the purposes of p<220>j<193>) in such a way ç
that he is facing the deity or keeping the deity to his left.
Generally, facing east or north is preferred and facing south is forbidden.
The whole rite of p<220>j<193>†for that matter, any religious or ritualistic ç
act† should begin with <193>camana or ceremonial sipping of water ç
with certain mantras.
This should be followed by sa<209>kalpa or religious resolve. Apart ç
from the details of that particular day according to the Hindu calendar ç
(followed in the tradition of the worshipper's family), the sa<209>kalpa-mantra ç
also contains some other statements such as the destruction of one's ç
sins, acquisition of religious merit and some other particulars connected ç
with the mode of worship.
@SPACE1 = 
Then come some purificatory processes like <193>sana·uddhi (ritual ç
sanctification of the seat), bh<220>t<193>pas<193>ra<207>a (driving ç
away the evil spirits), pu<218>pa·uddhi (ritual cleansing of flowers, ç
bilva and tulas<200> leaves) and agnipr<193>k<193>racint<193> (erecting ç
a wall of fire through imagination) and soon.
The next steps are pr<193><207><193>y<193>ma (breath control in aid ç
of peace and concentration) as also bh<220>ta·uddhi or creating a ç
spiritual body in place of the physical one.
Pr<193><207>aprati<218><219>h<193> (filling the spiritual body with ç
the presence of the deity), ny<193>sas (ritual purification of limbs) ç
and mudr<193>s (postures of fingers and hands) follow next.
Now, are taken up the most important parts of the worship†dhy<193>na ç
(meditation on the deity in one's heart and transferring the same ç
into the image or symbol) and upac<193>ras (modes of direct service).
These upac<193>ras can be 5 or 10 or16. Sometimes they are raised ç
to 64 or even 108! But, normally, the first two are common for daily ç
worship and 16 upac<193>ras for special worship. The other two are ç
done only in temples on very special occasions.
These  upac<193>ras  are  ceremonially offered with appropriate mantras ç
to the deity invoked into the image or symbol.
The ten upac<193>ras are: p<193>dya (water for washing the feet), ç
arghya (water for washing the hands), <193>caman<200>ya (water for ç
rinsing the mouth), sn<193>n<200>ya (giving a bath by pouring water ç
over the image or the symbol  with  Vedic  mantras),  gandha (applying  fresh  sandal  paste),  pu<218>pa ç
(offering of flowers, bilva and tulas<200> leaves), dh<220>pa (waving ç
of lighted incense sticks), d<200>pa (waving of a lighted lamp), naivedya ç
(giving food-offering as also drinking  water)  and  punar<193>caman<200>ya ç
(giving water for rinsing the mouth at theend).
@SPACE1 = 
At the end of the worship, pu<218>p<193><210>jali (offering of a handful ç
of flowers) is laid at the feet of the deity, indicating the conclusion ç
of the whole ritual.
Where the p<220>j<193> is done to the deity in a temporarily invoked ç
image (as in the worship of clay icons of Ga<207>apati or Durg<193>), ç
udv<193>san<193> or visarjana also has to be done. It is the ceremonial ç
withdrawal of the deity from the image, back into one's own heart, ç
after which the image or the symbol (like a flower) can be disposed ç
off.
The mode of worship described so far, is according to the t<193>ntric ç
tradition. The Vedic tradition is slightly different from this. A ç
brief account of the same is as follows:
@SPACE1 = 
D<200>pajvalana (lighting the lamp and praying to it as the symbol ç
of the deity and requesting it to burn steadily till the p<220>j<193> ç
is over), <193>camana, guruvandana (obeisance to one's own guru or ç
spiritual teacher), prayer to Vighne·vara or Ga<207>apati (for the ç
removal of obstacles to the p<220>j<193>), gha<207><219><193>n<193>da ç
(ringing the bell with appropriate mantras to drive away the demons ç
and welcome the gods) (Ringing the bell is necessary at other times ç
also as during ceremonial bath to the deity and offering incense etc.), ç
recitation of two Vedic mantras to steady the mind (<184>gveda 10.63.3 ç
and 4.50.6), ma<207><219>apadhy<193>na (meditation on the miniature ç
shrine structure, generally made of wood), <193>sanamantra (for purification ç
and steadiness of the seat), pr<193><207><193>y<193>ma, sa<209>kalpa, ç
ceremonial purification of the water in the kala·a (water vessel) ç
to make it fit for using in p<220>j<193>, filling up the ·a<209>kha ç
(conch) with that water and inviting its presiding deities (like S<220>rya, ç
Varu<207>a, Candra and others) to reside in it in a subtle form, sprinkling ç
that water over all the articles of p<220>j<193> to consecrate them, ç
ny<193>sa with the Puru<218>as<220>kta (<184>gveda 10.7.90), invoking ç
the presence of the deity into the image and offering the upac<193>ras.
The sixteen upac<193>ras offered are: <193>v<193>hana, <193>sana, ç
p<193>dya, arghya, <193>cama-n<200>ya, sn<193>na, vastra (cloth) as ç
also upav<200>ta (sacred thread, called `yaj<210>opav<200>ta'), gandha, ç
pu<218>pa, dh<220>pa, d<200>pa, naivedya, t<193>mb<220>la (betel leaf ç
and nut), recitation of the Mantrapu<218>pa (Taittir<200>ya °ra<207>yaka† ç
Aru<207>apra·na  78  to  84),  pradak<218>i<207>a (circumambulation) ç
and namask<193>ra (obeisance).
@SPACE1 = 
Some more, traditional and interesting, aspects of this worship may ç
now be stated.
In the pa<210>c<193>yatanap<220>j<193> (p<220>j<193> to the five standard ç
deities viz., <185>iva, Dev<200>, Vi<218><207>u, Ga<207>e·a and S<220>rya), ç
one's own family deity should be kept in the centre and the other ç
four around it in the prescribed order.
Abhi<218>eka (pouring water for giving bath to the image) is to be ç
done with go·<216><209>ga (horn of a cow) to the ·ivali<209>ga and ç
with ·a<209>kha to Vi<218><207>u or ·<193>lagr<193>ma.
While offering cloth in p<220>j<193>, different types of cloth are ç
offered to different deities, which can be known from the concerned ç
scriptural injunctions. In the routine daily p<220>j<193> even flowers ç
can be offered in place of cloth, as a substitute.
Dh<220>pa is offered to the feet and d<200>pa before the face of the ç
deity. In general <193>rati (waving of lights), the d<200>pa has to ç
be waved all over the deity's image.
Pradak<218>i<207><193> is to be done three times in the clockwise ç
direction, slowly, with folded hands. Then comes s<193><218><219><193><209>ga-pra<207><193>ma, ç
done by lying down on the chest, on the floor.
At the end, t<200>rtha (the consecrated water of the p<220>j<193>) ç
and pras<193>da (consecrated food offering) should be received by ç
all who have taken part in the p<220>j<193> or witnessed it.
@SB = Epilogue
What has been described till now, just gives an idea of the philosophy ç
and the spirit behind the Hindu ritualistic worship.
The Hindu scriptures themselves consider these rituals as the kindergarten ç
of religion. When understood properly and performed meticulously, ç
they lead to inner purity and concentration. When this concentration ç
becomes deep, the external rituals drop off by themselves. Till then, ç
they must be performed.
@NT = deva-<216><207>a
@N1 = (`debt to gods')
A human being is said to be born under the load of three <216><207>as ç
or debts.
Deva-<216><207>a or the debt to be paid to the gods is one of them. ç
It can be repaid by the regular and proper performance of the prescribed ç
Vedic rites.
See <MS><184>ØATRAYA<D> for details.
@NT = devar<218>i
@N1 = (`sage of the divine group')
Sages of knowledge and wisdom (<216><218>is) as also of austerity ç
(munis, tapasv<200>s) have been well-known in the Hindu scriptural ç
works.
Among the several kinds of <216><218>is mentioned there, the devar<218>is ç
are one group.
The word `devar<218>i' has been defined as a `sage who is like a god' ç
or as `one who is revered even by the gods'.
The most well-known of all the devar<218>is is N<193>rada. The others ç
are: Atri, Bh<216>gu, Kutsa, Vasi<218><219>ha, Gautama, Ka·yapa and ç
A<209>giras. In other lists the names of Tumburu, Bharata, Parvata ç
and Devala appear. There seems to be no unanimity in the classified ç
lists.
See also <MS><184><186>IS.<D>
@NT = devas
@N1 = (`the shining ones')
Derived from the root `div' (= to shine) the word `deva' represents ç
the divine beings inhabiting the heavenly regions. They are described ç
as the sons of the sage Ka·yapa from his first wife Aditi. Hence they ç
are also known as <193>dityas or <193>diteyas.
In the Vedic literature their number is often stated as 33. The break-up ç
is: 8Vasus, 11 Rudras, 12 °dityas, Indra and Praj<193>pati. (See ç
under each title for details.)
But again, they are all the manifestations of the one Supreme God.
In the mythological literature†Vedic and post-Vedic†the devas are ç
pictured as constantly in conflict with the asuras (antigods or demoniac ç
beings). The asuras are probably of two types: the daityas and the ç
d<193>navas. They were the sons of Diti and Danu who too were the ç
wives of Ka·yapa.
Indra was the king of the devas and Virocana, of asuras.
@NT = Devasen<193>
@N1 = (`army of the gods')
Devasen<193> and Daityasen<193> were the daughters of Dak<218>apraj<193>pati ç
and hence sisters. Once they were abducted by a demon called Ke·in, ç
but were rescued by Indra. When <186>a<207>mukha or Subrahma<207>ya ç
(also known as K<193>rttikeya) led the army of the gods against Padm<193>sura ç
and T<193>rak<193>sura and killed them, Indra was so pleased that ç
he gave Devasen<193> in marriage to him. B<216>haspati is said to ç
haveperformed the religious rites of the marriage. According to this ç
story, the well-known festival day, Skanda<218>a<218><219>h<200> or ç
Subrahma<207>ya  <218>a<218><219>h<200>,  is  this  day  of marriage.
Etymologically, the word could just mean `the army of the gods'. Since ç
<186>a<207>mukha led that army as its chief he was called `Devasen<193>pati' ç
(pati = lord, master). Since the word `Devasen<193>' is in the feminine ç
gender, the story that `she' was a princess and he was her husband ç
could have been invented and later interpolated into the pur<193><207>as.
@NT = devat<193>s
@N1 = (`divine beings')
Etymologically speaking, the words `devat<193>' and `deva' mean the ç
same thing. The devat<193>s are gods or deities or divine beings endowed ç
with extraordinary or supernatural powers.
In the Vedic literature, especially in the <184>gveda, we come across ç
a number of devat<193>s. They are usually enumerated as 33. (See <MS>DEVAS<D> ç
for details.) Apart from these gods, many inanimate objects like grinding ç
stone, qualities like faith, emotions like anger, aspects of nature ç
like dawn have been deified and described. There are quite a few female ç
devat<193>s also though they are not as prominent as the male deities.
These deities may have an anthro- pomorphic form or may not have. ç
As an aspect of nature or a physical object they don't. But, as the ç
presiding deity behind them they do have.
The Vedic deities have been allotted different places in the universe. ç
Agni, P<216>thv<200> and Somapavam<193>na belong to the p<216>thv<200> ç
(earth). Indra, V<193>yu and Parjanya belong to antarik<218>a (sky). ç
Varu<207>a, Mitra, S<220>rya and Vi<218><207>u belong to dyuloka (heaven).
But, ultimately, all of them are different aspects of the Supreme ç
God, Brahman-°tman.
Sometimes   these   devat<193>s   are described as being born from ç
one another. For instance Agni is born from S<220>rya and again, S<220>rya ç
from Agni. Being too remote in point of time, it is rather difficult ç
for us to explain these anomalies. Sometimes, even the explanations ç
of the Nirukta by Y<193>ska do not help us much.
The paur<193><207>ic Hinduism has offered a large number of devat<193>s, ç
gods and goddesses, most of whom do not seem to have existed during ç
the Vedic period. However, the basic idea that all of them are different ç
aspects of one and the same Supreme God (Brahman or Param<193>tman) ç
persists.
@NT = Devavrata
@N1 = (`One [whose] penance [is as good as that of a] god')
`Devavrata' was the original name of Bh<200><218>ma, the famous grandsire ç
of the Mah<193>bh<193>rata. See <MS>BH®<186>MA<D> for details.
According to the Padmapur<193><207>a (P<193>t<193>lakha<207><195>a, ç
73) Devavrata was a br<193>hma<207>a who was born as a bamboo stem ç
in the V<216>nd<193>vana where K<216><218><207>a lived, since he had ç
incurred the wrath of the devotee of Vi<218><207>u and had been cursed ç
by him. When K<216><218><207>a cut it, made a flute out of it and ç
started playing on it, Devavrata was liberated.
@EMERGEN1 = `Devavrata' is also the name of a vrata or religious observance ç
mentioned in some of the pur<193><207>as. Worshipping Mahe·vara (<185>iva) ç
on a caturda·<200> day (14th day after full-moon or new-moon) with ç
the star Magh<193> (comprising alpha, eta, gamma, zeta and two more ç
stars) and the planet Guru (Jupiter) in conjunction, will bestow long ç
life, wealth and fame. This is one vrata called `Devavrata'. In another ç
type, nakta (eating once only at night) for eight days and gifting ç
a golden trident and discus as also two garments is the discipline ç
prescribed. Result promised is freedom from even grave sins.
@NT = devayaj<210>a
@N1LS = (`sacrifice unto the gods')
@EMERGEN1 = An awareness of one's social respons-ibilities and earnest ç
attempts to repay one's debts to the concerned persons gradually evolved ç
into the principle of <216><207>atraya (three debts) even at birth. ç
The same was expanded in scope into an allied principle of pa<210>cayaj<210>as. ç
They apply to all human beings, especially to the g<216>hasthas or ç
house-holders.
@EMERGEN1 = Deva-<216><207>a or the debt towards the gods like Indra ç
and Varu<207>a has to be paid back by devayaj<210>a (also spelt as ç
daiva- yaj<210>a) or offering of oblations ceremonially into the duly ç
consecrated fire. Being pleased by (and also sustained by) such sacrificial ç
offerings, these gods who have control over the elemental forces like ç
rain or the growth of crops or granting worthy progeny, fulfil our ç
desires. By thus mutually co-operating with each other both these ç
gods and the human beings can live happily and even prosper well.
See also <MS>PA<178>CAYAJ<178>AS<D> and <MS><184>ØATRAYA.<D>
@NT = Devay<193>na
@N1 = (`the path of gods')
@EMERGENCY = Birth and death have always proved to be a deep mystery ç
for mankind. Every religion has tried to solve this in its own way. ç
The solution Hinduism offers is found in the Vedic literature†the ç
<184>gveda, the <185>atapatha Br<193>hma<207>a and some of the ç
Upani<218>ads like the B<216>had<193>ra<207>yaka and the Ch<193>ndogya.
@EMERGENCY = The religion of the <184>gveda, the earliest available ç
record of human civilisation, is not only optimistic but also dynamic. ç
A life lived well here, in accordance with the principles of <216>ta ç
(straightforwardness), satya (truth) and dharma (righteousness), will ç
automatically give you happiness and peace in the life hereafter also. ç
This is the main teaching of the Vedas, the Upani<218>ads and all ç
the allied scriptures.
@EMERGENCY = A strong belief in an uncreated, unborn eternal soul, ç
born out of their mystical experiences, naturally made the Vedic seers ç
reflect on its sojourn after the death of this body also. What they ç
discovered in their moments of revelation was given expression to ç
in some of the mantras.
Generally, three destinies for the soul of a dead person have been ç
predicated in these Vedic works: going to the Brahma-loka (or the ç
world of Brahm<193>) by the Arcir<193>dim<193>rga (the path of light, ç
also called Devay<193>na or Uttar<193>ya<207>a), from which there ç
is no return to this mundane existence; going to the Pit<216>loka ç
or Candra- loka (the world of manes) by the Dh<220>m<193>di-m<193>rga ç
(the path of smoke) from which there is return after exhausting the ç
fruits of the merit acquired earlier in this world; repeated birth ç
and death in various bodies.
The first mention of the words Devay<193>na and Pit<216>y<193>na is ç
found in the <184>gveda where Agni is addressed as the knower of ç
the path of gods (1.72.7) and the path of the manes (10.2.7). In the ç
mantra (10.18.1) M<216>tyu, the god of death, is requested to clear ç
away from the path of gods. The <185>atapatha Br<193>hma<207>a also ç
mentions these paths in several places. The <184>gvedic verse (10.18.1) ç
is repeated almost verbatim in the Atharvaveda (12.2.21).
It is quite likely that the Devay<193>na and the Pit<216>y<193>na ç
were the celestial paths by which the gods (like Indra) and the manes ç
used to descend to this earth to receive their sacrificial and obsequial ç
offerings and return. Gradually, however the paths were `thrown open' ç
as it were, to deserving human beings too.
The Devay<193>na starts with arcis or the light of the funeral pyre ç
and ends with the Brahmaloka. Various stations are mentioned in between. ç
The enumeration of these stations is found in the following Upani<218>ads: ç
B<216>had<193>ra<207>yaka (6.2.15 and 16); Ch<193>ndogya (4.15.5 ç
and 5.10.1 to 6); Kau<218><200>taki-br<193>hma<207>a (1.3). It is ç
mentioned in the Bhagavadg<200>t<193> (8.24) also.
@NID = <+><+><+>The stations commonly mentioned are:
Arcis (light), aha<199> (day), <193>p<220>rya-m<193><207>apak<218>a ç
(bright fortnight), uttar<193>ya<207>a (summer solstice), sa<221>vatsara ç
(year), <193>ditya (sun) and candramas (moon).
At this point, an `am<193>navapuru<218>a' (a being who is not a human; ç
a divine being) will come and take the soul to Brahm<193> in Brahmaloka ç
or Satyaloka.
@SPACE1 = 
Sometimes `candramas' is omitted and `devaloka' is substituted for ç
`sa<221>- vatsara'. The divine being had also been called `puru<218>o ç
m<193>nasa<199>' (`the mind-born person').
The terms used in these lists such as arcis (light) or aha<199> (day) ç
actually refer to the <193>tiv<193>hik<193>s or divine guides on the ç
path (vide Brahmas<220>tras 4.3.4).
Who are those fortunate persons considered as fit enough to tread ç
this path and go to Brahmaloka, from which there is no return? The ç
Ch<193>ndogya (5.10.1) and the B<216>had<193>ra<207>yaka (6.2.15) ç
Upani<218>ads declare that the knowers of the Pa<210>c<193>gni-vidy<193> ç
(`the doctrine of five fires') (See <MS>PA<178>C°GNIVIDY°<D>.) as ç
also those who live in the forests, devoted to faith, austerity and ç
truth, go by this path. The Mu<207><195>aka Upani<218>ad too (1.2.11) ç
mentions that those who are self-controlled, full of knowledge and ç
wisdom, living on alms and in forests and devoted to austerity, go ç
by the `S<220>ryadv<193>ra' (i.e., Devay<193>na) and attain the Immortal ç
Being. The Pra·na Upani<218>ad (1.10) also proclaims the same thing.
Those who reach the Brahmaloka are supposed to live there enjoying ç
great peace and bliss till the end of Brahm<193>'s life, after which ç
they†along with the Brahma-loka and Brahm<193>†get merged in Parabrahman ç
or the Supreme Spirit.
This mode of mukti or liberation is called kramamukti or gradual liberation.
See also <MS>PIT<184>Y°NA.<D>
@NT = devay<193>trotsava
@N1 = (`[temple] festivals of gods')
@SPACE1 = 
Ever since the elaborate rituals to consecrated images in temples ç
became an established tradition, each temple too started having its ç
own special celebrations. Such celebrations are called `y<193>tr<193>' ç
or `utsava' or `y<193>trotsava'.
There are some general rules guiding such festivals, especially regarding ç
the auspicious days on which they should be done. The following table ç
gives an idea of the same:
@SPACE1 = 
@Z_TBL_BEG = COLUMNS(2), DIMENSION(IN), COLWIDTHS(.8925,E1), ABOVE(.0278), ç
BELOW(.0278), VGUTTER(.0278), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT
All gods<192>, P<220>r<207>im<193> (full-moon day)
Durg<193><192>, Navam<200> (ninth day after<R>ç
full-moon or new-moon day)
Lak<218>m<200><192>, Pa<210>cam<200> (fifth day after<R>ç
full-moon or new-moon day)
<185>iva<192>, A<218><219>am<200> or Caturda·<200><R>ç
(eighth day after full-moon or new-moon day)<R>ç
(fourteenth day after<R>ç
full-moon or new-moon day)
Skanda<R>ç
(<186>a<207>mukha)<192>, <186>a<218><219>h<200> (sixth day after<R>ç
<|>full-moon or new-moon<|>day)
Vin<193>yaka<R>ç
(Ga<207>apati)<192>, Caturth<200> (fourth day after<R>ç
full-moon or new-moon day)
@Z_TBL_END = 
@SPACE1 = 
Of course, local customs can differ and other days may be chosen for ç
the temple festivals.
@NT = dev<200>
@N1 = (`the shining one')
The `dev<200>' is the feminine counterpart of `deva' and hence means ç
a goddess.
@SPACE1 = 
The concept as well as the worship of God as the Mother of the universe† ç
deification into a feminine form, of the Supreme Power ruling over ç
the universe† is as old as the human civilisation. The people of Assyria ç
and Babylonia worshipped thegoddess Ishtar, as the goddess par excellence.
@SPACE1 = 
There is enough evidence to believe that Mother-worship existed during ç
the Indus valley Civilisation (2800 <MS>B.<|>C.<D>).
@SPACE1 = 
The <184>gveda (2.1.11; 8.10.2) refers to several female deities ç
as the consorts of male deities or even as independent and separate ç
goddesses such as Aditi, U<218>as, P<216>thv<200>, R<193>tri, V<193>c, ç
<185>raddh<193> and so on. Sacred  rivers  like  Sarasvat<200>,  Ga<209>g<193>, ç
Yamun<193>, <185>utudr<220> and Paru<218><207><200> were also deified ç
as goddesses.
In  course  of  time,  many  folk- goddesses of great antiquity and ç
uncertain origin were also absorbed into the Dev<200>-cult.
However, it is in the paur<193><207>ic age that the notion of the ç
Mother-goddess, Dev<200>, came to be associated with the three prominent ç
deities (the Trim<220>rtis) Brahm<193>, Vi<218><207>u and <185>iva, ç
thereby giving rise to a great number of her aspects.
The three major goddesses are Sarasvat<200> (consort of Brahm<193>), ç
Lak<218>m<200> (consort of Vi<218><207>u) and P<193>rvat<200> (consort ç
of <185>iva).
In the pur<193><207>as, while there is an attempt to depict them as ç
three aspects of one and the same Dev<200>, there are also legends ç
trying to project one of them as superior to and hence the mistress ç
of, the other two.
By  and  large,  an  overwhelming majority of the goddesses are either ç
different facets of the goddess P<193>rvat<200> (the spouse of <185>iva) ç
or her attendants or her associates. In fact, even the word `Dev<200>' ç
has been specially reserved for her.
For details, see under each title such as <MS>LAK<186>M®, P°RVAT®<D>, ç
<MS>SARASVAT®.<D>
@NT = Dev<200>bh<193>gavata
The pur<193><207>as or Hindu mythological lore, have been classed ç
among the secondary scriptures of Hinduism. Yet, modern Hindu religious ç
practices are, for the most part, dependent on them.
@SPACE1 = 
The great antiquity of the core content of the pur<193><207>as, known ç
as Pur<193>n<193>sa<221>hit<193>, is, by now, well-established. ç
Over the centuries, it gave rise to the eighteen Mah<193>pur<193><207>as ç
as we know them today. Its derivatives include the eighteen Upapur<193><207>as ç
(minor works) also. The Dev<200>bh<193>gavata is one of the more ç
well-known and fairly popular pur<193><207>as.
Whether the Dev<200>bh<193>gavata is a Mah<193>pur<193><207>a or ç
only an Upapur<193><207>a, has been a contentious issue. If the Vai<218><207>avas ç
(followers of the Vi<218><207>u cult) argue that the Bh<193>gavata ç
in the list of Mah<193>pur<193><207>as is the Vi<218><207>ubh<193>gavata, ç
the <185><193>ktas (followers of the cult of <185>akti or the Divine ç
Mother) vehemently assert that it is theDev<200>bh<193>gavata that ç
is meant. Since controversies lead to unnecessary and undesirable ç
conflicts, and obstruct the process of spiritual evolution, it is ç
better to ignore them.
Some scholars opine that a ·<193>kta br<193>hma<207>a of V<193>r<193><207>as<200> ç
(or K<193>·<200>) might have composed it during the 11th or the 12th ç
century.
However, the text follows the general pattern of the other pur<193><207>as.
King Janamejaya (son of the well-known king Par<200>k<218>it and grandson ç
of Arjuna,  the  famous  P<193><207><195>ava  hero) incurred great ç
sin for having massacred innumerable serpents in his Sarpay<193>ga ç
(Serpent-sacrifice, akin to a black-magical rite). He had performed ç
it to avenge the death of his father by the bite of Tak<218>aka, the ç
king of reptiles.
To ward off the effects of this sin the sage Vy<193>sa taught him ç
this Dev<200>-bh<193>gavata.
@SPACE1 = 
As the very name indicates, the main content of the work is the story ç
of the exploits of the Dev<200> (Mother Divine). It is almost identical ç
with†though in greater detail†the story as delineated in the more ç
well-known, but much shorter, work, the Dev<200>m<193>h<193>tmya.
@SPACE1 = 
There are 12 skandhas or Books, the number of adhy<193>yas (Chapters) ç
and ·lokas (couplets or verses) being 318 and 18,457 respectively.
A brief synopsis of the contents may now be given here, to get an ç
idea of this work:
@S10N = Skandha 1 (chs. 20; ·ls. 1184)
Stories of <185>uka, Hayagr<200>va, Madhu and Kai<219>abha and Brahm<193>'s ç
prayer to the Dev<200> find a prominent place in this book.
@S10N = Skandha 2 (chs. 12; ·ls. 723)
Stories of Vy<193>sa, <185>antanu, Bh<200><218>ma and the P<193><207><195>avas ç
are delineated here.
@S10N = Skandha 3 (chs. 30; ·ls. 1746)
Story of the king Sudar·ana of K<193>·<200> who was a great devotee ç
of the Dev<200> and at whose request the Dev<200> stayed back there ç
as also details of the Durg<193>p<220>j<193>, known as <185>aran-navar<193>tri-vrata, ç
the origin of which goes back to <185>r<200> R<193>ma's first worship ç
as per the advice of the sage N<193>rada find a prominent place in ç
this section.
@S10N = Skandha 4 (chs. 25; ·ls. 1416)
Doctrine of Karma, stories of Nara-N<193>r<193>ya<207>a and of K<216><218><207>a ç
are the main contents of this skandha.
@S10N = Skandha 5 (chs. 35; ·ls. 2094)
This skandha contains the entire story of the Dev<200>m<193>h<193>tmya ç
(also known as Durg<193>sapta·at<200> and Ca<207><195><200>) but ç
in greater detail. The story of Mahi<218><193>sura's birth and of ç
his falling in love with the Dev<200> before being obliged to fight ç
with her and be killed, is an additional feature. The rest of the ç
story is the same as in the other work.
(See <MS>DEV®M°H°TMYA<D> for the details of the story.)
@S10N = Skandha 6 (chs. 31; ·ls. 1888)
Stories of V<216>tr<193>sura, Nahu<218>a, <185>un··epha as also of ç
N<193>rada's being deluded by the power of all-bewitching m<193>y<193> ç
of Lord Vi<218><207>u are the main themes dealt with here.
@S10N = Skandha 7 (chs. 40; ·ls. 2245)
Apart from stories and legends of the princess Sukany<193> and her ç
husband, the sage Cyavana, of Tri·a<209>ku, Hari·candra and Vi·v<193>mitra, ç
this skandha gives many details of the various aspects of the Dev<200>like ç
<185><193>kambhar<200> and Gaur<200>. Some miscellaneous topics like ç
Yoga, Bhaktiyoga, temples of Dev<200> and her worship have also been ç
dealt with.
@S10N = Skandha 8 (chs. 24; ·ls. 834)
The special feature of this section is a detailed description of world ç
geography, of Bh<193>ratavar<218>a (India), some astronomical factors ç
as also a description of hells.
@S10N = Skandha 9 (chs. 50; ·ls. 3617)
By far, this is the biggest of all the skandhas of this work. The ç
well-known and popular story of S<193>vitr<200>, other less known ç
legends like that of Mah<193>lak<218>m<200> and Ma<209>galaca<207><195><200> ç
find a place here. Several mantras and procedures for meditation on ç
some aspects of Dev<200> like R<193>dh<193>, Durg<193> and Manas<193> ç
are also given here.
@S10N = Skandha 10 (chs. 13; ·ls. 508)
The story of Dev<200>m<193>h<193>tmya given in greater detail in ç
the 5th skandha has been repeated here, though in a condensed form.
@S10N = Skandha 11 (chs. 24; ·ls. 1239)
This skandha is devoted entirely to sad<193>c<193>ra and p<220>j<193>, ç
various ritualistic items connected with the daily routine of a religious ç
person. Rules of good conduct, personal cleanliness, details of the ç
rudr<193>k<218>a beads, some vratas or religious observances and vows, ç
the sandhy<193> ritual, special worship processes, ritual repetition ç
of the famous G<193>yatr<200>mantra as also the details connected ç
with the preparation and wearing of bhasma or vibh<220>ti (sacred ç
ash, dear to <185>iva) are delineated in this section.
@S10N = Skandha 12 (chs. 14; ·ls. 963)
This small book gives some details regarding the G<193>yatr<200>mantra ç
and d<200>k<218><193> (initiation into spiritual life). It concludes ç
with a description of the Amb<193>yaj<210>a (sacrifice conducted to ç
please the Dev<200>) performed by the king Janamejaya.
On the whole, one has to concede, that this pur<193><207>a successfully ç
propagates the cult of the Dev<200> or the Divine Mother and has given ç
a lot of additional information useful to the spiritual aspirants.
@NT = Dev<200>g<200>t<193>
The Bhagavadg<200>t<193> of the Mah<193>-bh<193>rata has become ç
so well-known and so highly respected as a basic scripture by itself ç
that several G<200>t<193>s in imitation of the same have been composed ç
in later times. Some of them are parts of other bigger works like ç
the Adhy<193>tma R<193>m<193>ya<207>a and the Bh<193>gavata (vide ç
R<193>mag<200>t<193>, Kapilag<200>t<193> and Bhik<218>ug<200>t<193>) ç
while others like the A<218><219><193>vakrag<200>t<193> and the ç
Avadh<220>tag<200>t<193> are independent works. The  Dev<200>g<200>t<193>  belongs  to  the  second ç
category.
It is in the form of a dialogue in 9chapters between the Dev<200> ç
P<193>rvat<200> (as the teacher) and her father Himav<193>n (as the ç
disciple). She teaches the advaita doctrine as expounded by <185>a<209>kara ç
(<MS>A.<|>D.<D> 788-820). Advaitic experience can be obtained only ç
by meditation on the Upani<218>adic texts like tat tvam asi. Such ç
meditation becomes possible only to those who have a strong and pure ç
mind. This, again, can be obtained only by the proper performance ç
of one's duties as per one's var<207>a (caste) and <193>·rama (station ç
in life).
Other subjects dealt with are: Vi·var<220>pa (universal form) of the ç
Dev<200>; a<218><219><193><209>ga yoga or the eight steps of Yoga ç
as taught by Pata<210>jali (200 <MS>B.<|>C<D>); other yogas viz., those ç
of j<210><193>na, karma and bhakti; temples of Dev<200> and her worship ç
(both Vedic and t<193>ntrik) and so on.
Obviously it is a later work of the Dev<200>-cult.
@SPACE = 
@NT = Dev<200>m<193>h<193>tmya
@N1 = (`the greatness of the Dev<200> [or the Goddess]')
@SPACE = 
The Dev<200>-cult is centred round the concept and the worship of ç
God as the Divine Mother. The Dev<200>m<193>h<193>tmya as alsothe ç
Dev<200>bh<193>gavata are the two most important works of this cult.
The roots of this cult can be traced to the <184>gveda itself. The ç
Ambh<216><207><200>s<220>kta (10.125.1) and the R<193>tr<200>s<220>kta ç
(10.127.1) are pointers to this. Some of the minor Upani<218>ads like ç
the Dev<200> Upani<218>ad as also the tantras (<185><193>kt<193>gamas) ç
have expounded this cult in greater detail.
Gradually, as the paur<193><207>ic religion became more popular, three ç
aspects of the Dev<200>†Sarasvat<200>, Lak<218>m<200> and P<193>rvat<200>† ç
were projected by the scriptures for worship and meditation. However, ç
it is P<193>rvat<200> who has been almost exclusively meant by the ç
word `Dev<200>' and the innumerable goddesses considered as her ç
aspects.
The Dev<200>m<193>h<193>tmya is considered as a part of the M<193>rka<207><195>eya ç
Pur<193><207>a (chapters 78 to 90), though it is more likely to be ç
an independent work, grafted on to this pur<193><207>a later. It is ç
also known by two more names: Durg<193>sapta·at<200> (since it contains ç
sapta·ata or 700 verses extolling the greatness of Mother Durg<193>) ç
and Ca<207><195><200> (since it deals with the exploits of the fierce ç
goddess Ca<207><195><200> or Ca<207><195>ik<193>).
The work has thirteen adhy<193>yas or chapters divided into three ç
Caritras or major sections as follows:
@NID = Prathamacaritra: Chapter 1.
@NID = Madhyamacaritra: Chapter 2, 3, and 4.
@NID = Uttamacaritra: Chapter 5 to 13.
These three Caritras are devoted to the exposition of the greatness ç
of the three aspects of the Dev<200>, viz., Mah<193>k<193>l<200>, ç
Mah<193>-lak<218>m<200> and Mah<193>sarasvat<200>, in that order.
@SPACE1 = 
The first section starts with the story of a king, Suratha by name, ç
and the merchant Sam<193>dhi, both of whom had been deprived of their ç
wealth and possessions by their own near and dear ones. They met at ç
the hermitage of the sage Sumedhas, to where they had come, seeking ç
peace. After hearing from each other about the tragedies that had ç
struck them, they approached the sage Sumedhas, with the question ç
as to why they were still mentally attached to their possessions and ç
their relatives even though the latter had deliberately wronged them.
In his long reply the sage described this blind attachment and infatuation ç
as the direct result of the power of moha or m<193>y<193>, the spell ç
cast by the Dev<200> or the Divine Mother on all the living beings. ç
When their curiosity to know more was roused, the sage started describing ç
in detail, the stories related to her.
The first story concerns the Dev<200> as Yoganidr<193>. At the end ç
of a kalpa (cycle of creation) N<193>r<193>ya<207>a was in deep sleep. ç
Using this opportunity, two demons Madhu and Kai<219>abha†tried to ç
attack and kill Brahm<193> (the creator, seated on the navel-lotus ç
of N<193>r<193>ya<207>a). Brahm<193> prayed to Yoganidr<193> (an aspect ç
of K<193>l<200>), to come out of N<193>r<193>ya<207>a so that he could ç
wake up. She obliged, appeared before him and then disappeared. N<193>r<193>ya<207>a ç
then killed the demons and rescued Brahm<193>. With this ends the ç
Prathamacaritra or the first section.
@SPACE1 = 
The second section known as the Madhyamacaritra contains the story ç
of Mahi<218><193>sura, the king of the asuras or demons. He had usurped ç
the kingdom of heaven and driven away all the devas or gods including ç
Indra. Then these gods under the leadership of Brahm<193> came to ç
Vi<218><207>u and <185>iva and recounted their tale of woe. As the ç
two gods got angry, and a brilliant light emerged from their faces, ç
the energies of all the others too emerged similarly out of them, ç
merging into one huge mass of brilliant blazing light and power, which ç
took the form of the goddess Durg<193>. As all the gods equipped her ç
with their respective weapons, she went to Mahi<218><193>sura, challenged ç
him for fight and ultimately killed him. The heavenly region was restored ç
to the gods. The Dev<200> Durg<193> promised to come to the rescue ç
of the gods whenever they called upon her for help. Thus ends the ç
second section.
The last section called Uttamacaritra (or T<216>t<200>yacaritra) ç
begins with the outrageous misdeeds of the demon brothers, <185>umbha ç
and Ni·umbha, who too, like Mahi<218><193>sura, had forcibly occupied ç
the heavenly regions and driven away the gods. Remembering the promise ç
given by the Dev<200>, the gods prayed to her. She manifested herself ç
as Kau·ik<200> Durg<193>, of bewitching beauty and started roaming ç
about the Him<193>layan region. She was noticed by two servants of ç
<185>umbha who informed him about her presence in `his kingdom,' stressing, ç
on her captivating beauty. When <185>umbha sent messengers to her ç
with a proposal for marriage, she informed them about her vow, taken ç
out of `ignorance,' to marry only him who will conquer her in combat! ç
All attempts by <185>umbha's men, including several generals of his ç
armed forces, to capture her, dead or alive, ended in total disaster. ç
The Dev<200>, with her emanations like Brahm<193><207><200>, N<193>r<193>ya<207><200>, ç
Kaum<193>r<200> and others, successfully killed all the demons like ç
Ca<207><195>a, Mu<207><195>a and Raktab<200>ja. Finally, after withdrawing ç
them into herself, she despatched both Ni·umbha and <185>umbha, to ç
the world of Yama, the god of death, thereby ridding the world, of ç
a great terror.
@SPACE1 = 
After listening to these exploits of the Dev<200> and learning from ç
the sage Sumedhas the methods of worshipping her to get her grace, ç
Suratha and Sam<193>dhi practised severe austerities for three years.
