@NID = They got her vision and obtained, through her grace, what they ç
wanted. Suratha gotback his kingdom whereas Sam<193>dhi succeeded ç
in attaining supreme knowledge for which alone he had hankered.
The work contains four hymns which are exquisitely beautiful and are ç
a signal contribution to the hymnal literature. Theyare:
@NID = (1)
@NOK = Brahm<193>'s hymn to Yoganidr<193>†
@R = Ch. 1, ·ls. 72-87.
@NID = (2)
@NOK = Hymn by all the gods, led by Indra, expressing their gratefulness ç
after Mahi<218><193>sura was killed by Durg<193>†
@R = Ch. 4, ·ls. 1-27.
This hymn is known as Indr<193>distuti.
@NID = (3)
@NOK = Hymn by all the gods, on the bank of the river Ga<209>g<193> ç
in the Him<193>layas†
@R = Ch. 5, ·ls. 8-82.
This hymn is called Apar<193>jit<193>stotra.
@NID = (4)
@NOK = Hymn by all the gods, after <185>umbha and Ni·umbha were killed†
@R = Ch. 17, ·ls. 1-35.
This hymn is the famous N<193>r<193>ya<207><200>-stuti.
The entire Dev<200>m<193>h<193>tmya is considered as a mantra, ç
endowed with mystical powers. That is why a ritual recitation of the ç
same is encouraged, nay even recommended, for the fulfilment of one's ç
desires.
Such a ritual recitation normally consists of the following procedure:
@SPACE1 = 
<193>camana (ceremonial sipping of water before beginning any religious ç
rite), pr<193><207><193>-y<193>ma (breath-control), sa<209>kalpa (religious ç
resolve stating the details of the ritual), d<200>pasth<193>pana (lighting ç
a lamp and offering a simple worship to it, considering as a representation ç
of the Dev<200>), worship of theDev<200>m<193>h<193>tmya book used ç
for the ceremonial chanting, repetition of the ·<193>poddh<193>ramantra ç
to ward off the effects of the curses of the sages of yore, if any, ç
and then the actual recital.
The recital should include: Kavaca-stotra, Argal<193>stotra, K<200>lakastotra, ç
repetition of the well-known Nav<193>r<207>amantra (which has to ç
be received from a competent guru in initiation), recital of R<193>tris<220>kta, ç
the entire text of the Dev<200>m<193>h<193>tmya, the Dev<200>s<220>kta, ç
the Rahasyatraya (Pr<193>dh<193>nika, Vaik<216>tika and M<220>rti ç
Rahasyas), ·<193>poddh<193>ramantra and k<218>am<193>pr<193>rthan<193> ç
(recital of the Apar<193>dhak<218>am<193>pa<207>astotra).
There are several modes of chanting for specific purposes like freedom ç
from diseases, attaining wealth or position, for the birth of children ç
and so on. These have to be learnt from teachers who are experts in ç
the field.
Recitations called <185>ataca<207><195><200> (ten br<193>hma<207>as ç
reciting it for four days†once on the first day, twice on the second ç
day, thrice on the third day and four times on the fourth day) and ç
Sahasraca<207><195><200> (with one hundred br<193>hma<207>as, the ç
procedure being similar) are forms of congregational worship and are ç
done for the welfare of the society.
In all these rites, homa (offering of oblations into a duly consecrated ç
fire) is also done.
The Dev<200>m<193>h<193>tmya is highly revered <%-2>even now and ç
its recitation is quite popular.<%0>
@NT = Dev<200>pur<193><207>a
@SPACE1 = 
The Dev<200>pur<193><207>a is an Upapur<193><207>a, belonging to ç
the cult of <185>akti worship. The printed edition available now seems ç
to be only a part of a much bigger original. It was probably composed ç
in Bengal in the seventh century <MS>A.<|>D.<D>
The book deals mainly with the exploits of the Dev<200>, especially ç
as Vindhya- v<193>sin<200>. However, many other topics also have been ç
dealt with. They are:
Various stories connected with Dev<200>'s incarnations; her relationship ç
with <185>iva and other gods; <185><193>kta iconography and <185><193>kta ç
vows; some cults of <185>iva, Vi<218><207>u and Ga<207>apati; construction ç
of towns and forts; different Vedic schools; the science of medicine; ç
holy places; giving gifts; customs and usages of people and so on.
The method of the worship of the Dev<200> mentioned here is very different ç
from that followed in present-day Bengal.
@NT = Dev<200>s<220>kta
@N1 = (`hymn of the Dev<200> or the goddess')
Worship of God as the Mother of the universe is a very ancient practice, ç
especially in Hinduism. One of the oft-quoted authorities to prove ç
this point is the Dev<200>s<220>kta of the <184>gveda (10.125.1-8).
This s<220>kta or hymn is also known as the V<193>g<193>mbh<216><207><200>s<220>kta ç
since it was revealed to the woman <216><218>i V<193>c who was the ç
daughter of the sage Ambh<216><207>a. It has eight mantras or stanzas ç
wherein V<193>c describes her mystical experiences and her identity ç
with Param<193>tman or God.
There are quite a few instances in the scriptural works wherein the ç
sages who had attained mystical union with God had declared that they ç
themselves were God (vide B<216>had<193>ra<207>yaka Upani<218>ad ç
1.4.10; Kau<218><200>taki Upani<218>ad 3.1 and 2). Similar is the ç
case here also.
Commentators  of  the  Vi<218><207>u  cult identify her with Lak<218>m<200>, ç
the eternal consort of Vi<218><207>u-N<193>r<193>ya<207>a.
The first verse declares that it is she (viz., V<193>g<193>mbh<216><207><200>) ç
that is moving in the form of the various Vedic deities like the eleven ç
Rudras, the eight Vasus, the twelve °dityas as also the Vi·vedevas. ç
It is she who is supporting and sustaining the gods Mitra, Varu<207>a, ç
Indra, Agni and the A·vin<200>devat<193>s.
Again, it is she who is sustaining the soma juice, and the gods Tva<218><219><193>, ç
Bhaga and P<220><218>an. It is verily she who rewards a sacrificer ç
when he performs it.
She is the mistress of the whole world, awarding rewards to the worshippers. ç
She is the primary deity propitiated in the vedic sacrifices. She ç
exists everywhere.
It is she who is responsible for all thepsycho-physical activities ç
in the living beings.
Those who please her by proper acts of propitiation are elevated to ç
the level of a <216><218>i (sage, a seer of mantras) or even Brahm<193>, ç
the creator!
It is she that strings the bow of <185>iva when he decides to destroy ç
the demons of the three cities (Tripur<193>suras).
She has created the svargaloka or heaven. She has also entered into ç
all the worlds and all the beings. She it is, who is moving freely ç
in the universe, even like the wind.
Such is the greatness of the Dev<200>.
In spite of all the efforts of the various commentators, the purport ç
of this hymn seems to remain rather elusive.
@NT = Dev<200> Upani<218>ad
This is a small Upani<218>ad of only 32 mantras, assigned to the Atharvaveda. ç
The mantras are both in prose and in verses. The Dev<200> or God as ç
the Divine Mother is the main theme. Verses included here seem to ç
have been culled out from the Dev<200>s<220>kta of the <184>gveda, ç
the Dev<200>-m<193>h<193>tmya of the M<193>rka<207><195>eya Pur<193><207>a ç
as also the Durg<193>s<220>kta of the Mah<193>n<193>r<193>ya<207>a ç
Upani<218>ad.
Once all the gods approached the Dev<200> (the Mother Divine) and ç
asked her who she was. In reply she said she was Brahman and that ç
the whole world comprising matter and souls, the five elements, the ç
sacred and the secular sciences, the unborn and the born or in fact, ç
all that exists every where, is herself. It is again she that exists ç
in the form of the Rudras, the Vasus, and the Vi·vedevas (various ç
kinds of divine beings inhabiting the worlds). It is she that is helping ç
Vi<218><207>u, Brahm<193> and others to sustain themselves. Due to ç
her power and grace only, performers of Vedic sacrifices are able ç
to reap their benefits.
Hearing this, the gods praised her through a beautiful hymn: Obeisance ç
to the auspicious goddess, the origin of the universe and the brilliantly ç
shining deity. We take refuge in her, the goddess Durg<193>, Sarasvat<200> ç
the mistress of speech, the consort of <185>iva (as Dak<218>a's daughter) ç
and the power of Vi<218><207>u (Vai<218><207>av<200>). We bow down ç
to her.
The Upani<218>ad then goes on to give the well-known Dev<200>mantras ç
like the pa<210>cada·<193>k<218>ar<200> (ka e <200> la hr<200>m, ç
ha sa ka ha la hr<200>m, sa ka la hr<200>m) and the nav<193>k<218>ar<200> ç
(ai<221> hr<200><221> kl<200><221> c<193>mu<207><195><193>yai vicce).
It concludes with a long list of the fruits one gets by the repetition ç
of this Upani<218>ad and the mantras therein.
@SPACE1 = 
See also <MS>DEV®<D> and <MS>UPANI<186>ADS<D>.
@NT = dh<193>ma
@N1 = (`abode')
The word means an abode or a sacred place, a place of pilgrimage.
The four well-known pilgrim centers †Badar<200>n<193>tha in the north, ç
Jagann<193>tha-pur<200> or Pur<200> in the east, R<193>me·vara in ç
the South and Dv<193>rak<193> in the west†are specially known as `Caturdh<193>mas' ç
(C<193>r Dh<193>m in Hind<200>) and are coveted places of pilgrimage ç
for all the Hindus.
It is obvious that in the attempt at a visit to these centres, practically ç
all the other important places of pilgrimage all over India too, are ç
covered.
See under each title for details.
@NT = Dh<193>m<200> Sect
Some of the mystics of medieval India made serious attempts to weld ç
the Hindus and the Muslims into one great brother- hood. Pr<193><207>an<193>tha ç
was one of them. He must have lived during the period <MS>A.<|>D<D>. ç
1700-1750. He was an adept in the scriptures of both Hinduism and ç
Islam. He founded a sect called the `Dh<193>m<200> Sect,' which was ç
monotheistic in character and liberal in outlook.
Members of this sect call God as `dh<193>man or Home'. Their religious ç
life is founded on moral purity, compassion, service and love of humanity. ç
In their places  of  worship,  both  Hindus  and Muslims pray together.
@NT = Dhanurveda
@N1 = (`science of archery')
The word `Veda' is a general term used to indicate any branch of organised ç
knowledge. The word `dhanus' can mean weapons in general and the bow ç
(and arrow) in particular. Hence `Dhanurveda' means military science ç
or the science of archery. But, the latter sense is more common.
Another name commonly used is `Dhanurvidy<193>'. It is supposed to ç
be subsidiary to Yajurveda.
The science itself is quite ancient and there are references to it ç
even in the <184>gveda and the Aitareya Br<193>hma<207>a.
No scientific work known as Dhanurveda is extant now. However, a ç
work called Dhanurveda Sa<221>hit<193> available now, is considered ç
to be of a much later date.
The Agnipur<193><207>a (chapters 249-252) as also the Vi<218><207>udharmottarapur<193><207>a ç
(chapters 178-182) contain a lot of information about Dhanurveda.
Weapons of war are generally classified into four groups: Yantramukta ç
(discharged by a contrivance or machine); P<193><207>imukta or hastamukta ç
(discharged by hand); Mukt<193>mukta (discharged by hand or used by ç
holding in hand) and amukta (used directly by hand). The examples ç
are arrow, discus, spear and sword respectively.
The dhanurvidy<193> is concerned exclusively with archery. Use of ç
bows and arrows was quite common even up to the 16th century.
Several varieties of the bows. depending upon the material out of ç
which they are made, are mentioned in certain works like the Artha·<193>stra ç
of Kau<219>ilya (300<MS><|>B.<|>C<D>). They are: k<193>rmuka (made of ç
palm-tree), koda<207><195>a (of bamboo), dru<207>a (of sandalwood) ç
and dhanu (of bone or horns). Another division is two fold: ·<193>r<209>ga ç
(made of ·<216><209>ga or horns) and va<221>·a (made of bamboo).
@SPACE1 = 
Sometimes these classifications are made keeping the size and the ç
weight in view. One work, the Koda<207><195>ama<207><195>ana, gives ç
eighteen such varieties.
In our epics and pur<193><207>as, the <185><193>r<209>ga of Vi<218><207>u, ç
the Pin<193>ka of <185>iva, the Koda<207><195>a of <185>r<200> R<193>ma ç
and the G<193><207><195><200>va of Arjuna are known as formidable ç
weapons.
Since  bows  are  useless  without arrows, a lot of information has ç
been provided by these works on the arrows also. They are prepared ç
out of bamboo or steel. Usually feathers of birds are stuck at the ç
back end. Sometimes poisonous substances would be smeared on the front ç
end. Five kinds of arrows†ve<207>u, ·ara, da<207><195>a·ara, ·al<193>ka ç
and n<193>r<193>ca†are known to have existed. When discharged with ç
appropriate mantras, they would get transformed into very powerful ç
missiles called `astras'. Some of the famous astras are Brahm<193>stra, ç
P<193>·upat<193>stra, N<193>r<193>ya<207><193>stra, °gney<193>stra ç
and Sarp<193>stra.
The bag in which the arrows are kept and tied to one's back is called ç
`t<220><207><200>ra'. Some great warriors who had been blessed by ç
the divine powers or deities had `ak<218>aya-t<220><207><200>ras,' ç
a bag of arrows which would never become empty!
For discharging the arrows effectively, several postures like samap<193>da, ç
ma<207><195>ala, <193>l<200><195>ha and da<207><195>ay<193>ta have ç
been prescribed which also have to be learnt from a competent teacher ç
like other aspects of archery.
Though dhanurvidy<193> was a part of military science, only a br<193>hma<207>a ç
could be a teacher and even the k<218>attriya boys and youth had to ç
learn from him!
@SPACE1 = 
Agastya, Para·ur<193>ma and Bh<193>ra-dv<193>ja were the greatest ç
teachers of this science of archery.
@NT = Dhanus
@N1 = (`the bow')
@EMERGENCY = Whether the stars and planets in the sky have any effect ç
on our life here and now, has been a fascinating subject of study ç
for several centuries. This has resulted in the evolution of a regular ç
science called Jyauti<218>a (also Jyoti<218>a) or astrology.
@EMERGENCY = Hindu astrological works divide the zodiac†the annual ç
path of the sun round the earth†into 12 equal parts of 30<F20><198><F255> ç
each. Each of these is called a `r<193>·i' (a zodiacal sign). The ç
sun travels through these 12 r<193>·is in a year. The time taken by ç
the sun to travel through one r<193>·i is the length of a solar month.
@EMERGENCY = The Dhanus or Dhan<220>r<193>·i (also called Tauk<218>ika) ç
is the 9th in the series of 12 and is called Sagittarius (archer) ç
in Greek astrology. It resembles an archer. It comprises the two nak<218>atras, ç
M<220>l<193> and P<220>rv<193><218><193><195>h<193> as also the first ç
quarter of Uttar<193><218><193><195>h<193>.
If time is considered as a personified being (`k<193>lapuru<218>a') ç
then Dhan<220>r<193>·i forms his thighs. Guru or B<216>haspati (Jupiter) ç
is said to be the lord of Dhan<220>r<193>·i.
During a day of 24 hours, as the earth goes round itself once, the ç
sun appears to move through all the 12 r<193>·<200>s, though the duration ç
of its being seen in each of the r<193>·is varies. For the Dhan<220>r<193>·i ç
it is 5 gha<219>ik<193>s and 30 vigha<219>ik<193>s i.e, 2 hrs. and ç
12 mts. These movements and their durations are needed in astrological ç
calculations.
See also <MS>R°<185>IS.
@NT = Dhanu<218>ko<219>i
@N1 = (`[place sanctified by] the extremity of the bow [of R<193>ma]')
Also spelt as `Dhanu<218>ko<195>i,' it is an important place of pilgrimage ç
of hoary antiquity, contiguous with the land-mass of the island of ç
R<193>me·varam. It got its name from the ancient legend that R<193>ma, ç
at the request of the king Vibh<200><218>a<207>a, destroyed the bridge ç
he had got built by the monkey-army, with the ko<219>i (= extremity) ç
of his dhanus (= bow), so that there would be no future invasions ç
of La<209>k<193>, after its being handed over to Vibh<200><218>a<207>a.
This small, but beautiful, temple-town situated at a distance of 20 ç
kms. (12.5 miles) from R<193>me·varam was almost totally devastated ç
by the fierce cyclone of <MS>A.<|>D.<D> 1964. Miraculously, only the ç
temple of Koda<207><195>ar<193>masv<193>mi survived. It is standing ç
there in its place even today.
It can be approached by any four-wheeler for a distance of 10 kms. ç
(6.2miles), the rest of the distance being traversed on foot, since ç
it is laden with sand.
Where the Koda<207><195>ar<193>masv<193>mi temple stands at present ç
(8 kms. or 5 miles from R<193>me·varam), is said to be the place of ç
surrender of Vibh<200><218>a<207>a (younger brother of R<193>va<207>a) ç
at the feet of R<193>ma.
The temple itself†of Dravi<195>ian archi- tecture†contains the images ç
of R<193>ma, S<200>t<193>, Lak<218>ma<207>a, Hanum<193>n and Vibh<200><218>a<207>a.
At Dhanu<218>ko<219>i, the Bay of Bengal meets the Indian Ocean. This ç
place is called Ratn<193>kara. Pilgrims take a bath here and perform ç
·r<193>ddhas (obsequial rites).
@SPACE1 = 
There are a number of boulders in shallow waters up to Sri Lanka. ç
This† though called `Adam's Bridge'†may be the remnant of the famous ç
bridge which R<193>ma got built during his invasion of La<209>k<193>. ç
A recent satellite picture seems to indicate the remnants of a very ç
old bridge of boulders here.
At the edge of the island, there is a range of sand-dunes popularly ç
called `floating stones'.
@SPACE1 = 
See also <MS>R°ME<185>VARAM.<D>
@NT = Dhanvantari
°yurveda, the science of health and longevity, is very ancient. Dhanvantari ç
is said to be the originator of this science.
@SPACE1 = 
@SPACE1 = 
Considered as a partial manifestation of Vi<218><207>u and the physician ç
of the gods, Dhanvantari rose from the ocean of milk at the time of ç
churning it (See <MS>SAMUDRA-MATHANA<D> for details.) with the am<216>ta-kala·a ç
or pot of ambrosia in his hands.
@SPACE1 = 
He was reborn as Divod<193>sa, the king of K<193>·<200> and composed ç
a standard and basic work on the °yurveda, comprising eight sections.
Dhanvantari has been mentioned inseveral works such as R<193>m<193>ya<207>a, ç
Hariva<221>·a and Bh<193>gavata.
In  course  of  time,  `Dhanvantari' became a title for the very best ç
of physicians, one who had mastered the administration of 300 medicines, ç
the other two titles being bhi<218>ak (expert in 200 medicines) and ç
vaidya (expert in 100 medicines).
Nineteen  works  authored  by Dhanvantari have found mention in other ç
standard works. Some of them are: Cikits<193>-d<200>pik<193><D%20>,<MI%0>B<193>lacikits<193>,<|>Dhanvantari-nigha<207><219>u, ç
Vaidya-bh<193>skarodaya and °yurveda-s<193>r<193>val<200>.
The Dhanvantari-nigha<207><219>u is considered as the most ancient ç
of these works.
Dhanvantari icons are shown in various postures. A two-armed figure ç
holding the am<216>takala·a or the pot of ambrosia is the most common. ç
He is shown with four or even six arms, holding the emblems of Vi<218><207>u ç
like ·a<209>kha and cakra, apart from the am<216>takala·a. Sometimes ç
he is shown as bathing himself with the am<216>ta or nectar, pouring ç
it from the pot.
In one of the more curious forms he is shown holding a leach in one ç
of his hands, suggesting blood-letting or surgery.
@NT = dh<193>ny<193>dhiv<193>sa
See <MS>ADHIV°SA.<D>
@NT = dh<193>ra<207><193>
@N1 = (`fixing [the mind]')
Controlling the vagaries of one's mind and concentrating it on a particular ç
subject has been a life-time's ambition for many a cultured human ç
being. Pata<210>jali (200 <MS>B.C.<D>), the ancient teacher of Yoga, ç
has given us enough material and guidance in this regard in his incomparable ç
work, the Yogas<220>tras.
Out of the eight standard steps he recommends, dh<193>ra<207><193> ç
is the sixth. It is the fixing of attention on a definite locus, such ç
as the lotus of the heart (imagining a red, twelve-petalled, lotus ç
in the region of the heart for purposes of meditation), the light ç
in the brain (imagining a brilliant light in the crown of the head), ç
on the tip of the nose or the tongue, or on an external object like ç
the moon or the image of a god and so on.
It is natural for the fickle mind to get distracted and run away from ç
this object of concentration. However, it is to be repeatedly brought ç
back through strenuous efforts until it develops into dhy<193>na or ç
continuous flow (of the mind) towards the object.
See <MS>YOGADAR<185>ANA<D> for details.
@NT = Dh<193>re·vara
Temples have exerted a great influence on the Hindu society for several ç
centuries. Though the ancient temples built of perishable materials ç
like wood, have disappeared due to the ravages of nature and time, ç
those built of stones have survived. One such is the Pa<210>ca-ke·vara ç
temple†also known as Dor<193>n<193>tha temple†at the village Dh<193>re·vara, ç
near the town Kuma<219>a in the North Kanara district of Karnataka. ç
It is a beautiful temple built in the C<193><202>ukyan style. There ç
is a nice tank just inside the main compound. There are also two `hero-stones' ç
(V<200>ragallu, a stone slab or pillar erected in honour of a hero ç
who fought for the people) and a stone edict (<MS>A.<|>D.<D> 1083) ç
containing the description of a gift by the local queen.
According to mythological accounts, when R<193>va<207>a, the demon ç
king of La<209>k<193>, was bringing the <193>tmali<209>ga (·ivali<209>ga) ç
from Kail<193>sa, it got stuck on the ground at Gokar<207>a (in North ç
Kanara, Karnataka). R<193>va<207>a could not dislodge the li<209>ga ç
from the ground but succeeded in pulling out the cloth and thread ç
from it and threw it away. The thread fell at Dh<193>re·vara and became ç
a li<209>ga.
There are many beautiful images in the area around Dh<193>re·vara ç
like those of Narasi<221>ha and Ve<207>ugop<193>la. There is a broad ç
road in front of the temple for the rathotsava or temple-car festival.
@NT = Dharma
@N1 = (`that which supports')
@S10N = INTRODUCTION
Our scriptures are full of eulogy for dharma. Who has not heard of ç
the famous quotation from the Mah<193>bh<193>rata, `dharma eva hato ç
hanti dharmo rak<218>ati rak<218>ita<199>,' `It is dharma that destroys ç
(us) when destroyed; it is dharma again that protects (us) when protected ç
by (us)'? Or, that famous sentence put in the mouth of G<193>ndh<193>r<200>, ç
`yato dharmastato jaya<199>,' `Where there is dharma, there victory ç
alsois'? Consequently we are advised in poignant terms to accumulate ç
dharma in our lives: `anity<193>ni ·ar<200>r<193><207>i vibhavo naiva ç
·<193>·vata<199>,  nitya<221>  sannihito  m<216>tyu<199> kartavyo ç
dharma-sa<209>graha<199>,' `(Our) bodies are short-lived, wealth does ç
not last long, death is constantly knocking at our door; (so) accumulation ç
of dharma is a must.'
@S10N = WHAT IS DHARMA?
What is this `dharma' about which our scriptures and great men have ç
waxed so eloquent throughout our history?
As is the case with many other Sanskrit words, it is rather difficult ç
to give an exact translation of the word dharma. It has been variously ç
translated as `religion,' `law,' `duty,' `religious ordinance or rite,' ç
`code of conduct' and so on. It can mean anyone or more or all of ç
these, depending upon the context. The reason seems to be that the ç
word itself has been used in various senses down the ages and its ç
meaning as also scope has been enlarged. It will be worthwhile to ç
study this development.
It is universally accepted that the word dharma comes from the root ç
`dh<216>' (`to uphold,' `to support,' `to sustain'). An oftquoted ç
verse from the Mah<193>bh<193>rata says: `dh<193>ra<207><193>t dharmam ç
ity<193>hu<199> dharmo dh<193>rayate praj<193><199>,' `They call it ç
dharma since it upholds; it is dharma that upholds the people (of ç
the world).'
That which upholds this created universe, supports it and sustains ç
it, without which the universe just falls apart, is dharma. Viewed ç
from this standpoint, dharma is none other than God Himself. It is ç
what the Upani<218>ads describe as sat or tat, the very essence ç
of one's being. Whatever conduct or way of life helps us to reveal ç
this fundamental principle in us, can also be called dharma, though ç
in a secondary sense. Hence religious rites, ceremonies and observances, ç
fixed principles of conduct, privileges, duties and obligations of ç
a man depending upon his stage of life and status in society, even ç
rules of law, customs and manners of society†everyone of these can ç
be included under the term dharma.
@S10N = <184>TA AND SATYA
It may be interesting and instructive to turn our attention to two ç
more ancient words, <216>ta and satya, which are closely connected ç
with, if not forms of, dharma. The word <216>ta has been used profusely ç
in the Vedas, especially in the <184>gveda and the K<216><218><207>a ç
Yajurveda. The word in its simplest form, seems to indicate a straight ç
or direct line and so, universal laws of nature,  an  impersonal  order.  When ç
extended to the moral world, it denotes a straight conduct based on ç
truth which itself is also dharma. It has also been used in the sense ç
of an inner awareness of what is true, based on the scriptural teachings ç
and the needs of the duties on hand. When this awareness expresses ç
itself  through  words  and  actions,  it becomes satya. Thus we see ç
that the meanings of all the three words more or less coalesce.
@S10N = DHARMA AS THE FOUNDATION<R>ç
OF THE WORLD
Since  everything  in  this  world appears to have a beginning and ç
an end, with an intervening period of existence, it is but natural ç
for the human intelligence to conceive of a beginning for this creation ç
and to posit an eternal God who existed before creation and from whom ç
creation proceeded. For instance: `sadeva somyeda-magra <193>s<200>t, ç
ekamev<193>dvit<200>yam... tadaik<218>ata bahu sy<193>m praj<193>yeya ç
iti,' `My dear (boy), in the beginning Sat alone existed, the One ç
without a second. It reflected, ``May I become many! May I be born!''<|>' ç
(Ch<193>ndogya Upani<218>ad 6.2.1-3). The `many' that were created, ç
needed a central integrating force, a law or a principle; for, otherwise, ç
chaos would result. This law or principle is dharma. Even this was ç
created by God himself: `tat ·reyor<220>pam as<216>jata dharmam... ç
tasm<193>t dharm<193>t param n<193>sti... yo vai sa dharma<199> satya<221> ç
vai tat,' `He specially created that dharma, of the form of the highest ç
good... therefore there is nothing higher than that... that dharma ç
is verily satya' (B<216>had<193>ra<207>yaka Upani<218>ad 1.4.14). ç
This dharma is the firm foundation upon which the entire universe ç
stands (`dharmo vi·vasya jagata<199> prati<218><219>h<193>'† Mah<193>n<193>r<193>ya<207>a ç
Upani<218>ad 79.7). Obviously here, dharma means righteous behaviour ç
based on truth and knowledge of the unity in spite of the diversity, ç
and capable of bringing the highest good to the whole creation. All ç
other meanings, senses and derivations of this inlater literature ç
are corollaries of this central<+>idea.
@SPACE = 
@S10N = DHARMA AS DUTIES
@SPACE = 
The word dharma occurs in the <184>gveda fifty-six times (e.g., ç
5.63.7; 5.72.2; 9.7.1; 9.25.2; 10.88.1; 10.170.2). But in almost all ç
these places it has been used in the sense of duty or action which ç
contributes to the sustenance of the world (`jagad-dh<193>raka-karma'). ç
In the Upani<218>ads, this sense becomes more explicit. As a member ç
of the society each one of us has certain duties and obligations which ç
must be discharged by performing the prescribed actions. This sustains ç
the structure of the society. Similarly, in our journey towards perfection ç
we have to pass through several stages of spiritual development and ç
each such stage devolves upon us certain duties or a code of conduct. ç
This helps to sustain our inner development and simultaneously contributes  to  the  well-being  of  the ç
society also. The seeds of this†which is well-known as var<207>a-<193>·rama-dharma ç
in later literature†are to be found in the Puru<218>as<220>kta and ç
in the earlier Upani<218>ads also. For instance, in the B<216>had<193>ra<207>yaka ç
passage already quoted (1.4.14) there is clear reference to dharma ç
as a force that regulates even a k<218>attriya, who by virtue of his ç
position as a ruler, could misuse his powers for self-aggrandizement. ç
In the famous passage of the Ch<193>ndogya Upani<218>ad (2.31.1) ç
the reference to the duties of <193>·ramas is crystal clear: `trayo ç
dharmaskandh<193> yaj<210>o'dhyayana<221> d<193>namiti prathama<199>...' ç
`Dharma has three branches. Performance of sacrifice, study of scriptures ç
and giving gifts†this is the first.'
@SPACE = 
@S10N = DHARMA IN THE UPANI<186>ADS
@SPACE = 
Sometimes, the word dharma has also been used in the Upani<218>ads ç
in the sense of ap<220>rva of the P<220>rva M<200>m<193><221>s<193> ç
System (vide B<216>had<193>ra<207>yaka Upani<218>ad 2.5.11† `aya<221> ç
dharma<199> sarve<218><193>m bh<220>t<193>n<193>m madhu'). This ap<220>rva ç
is nothing but the subtle effect of an action performed as per the ç
directions of the scriptures, which will produce suitable results ç
later.
In rare cases, the word has also been used to denote the <193>tman ç
or the Self: `a<207>ure<218>a dharma<199>,' `This Self is very subtle' ç
(Ka<219>ha Upani<218>ad 1.21); `eva<221> dharm<193>n p<216>thak ç
pa·yan,' `thus, considering the selves to be separate' (i.e., `different ç
in different bodies') (ibid 4.14).
In the °c<193>ryopade·a of the Taittir<200>ya Upani<218>ad, the ç
word dharma has been clearly used in the sense of obligatory works: ç
`dharma<221> cara,' `Perform your ordained actions' (1.11.1).
@S10N = DHARMA IN THE G®T°
Coming to the Bhagavadg<200>t<193>, we find the term used in a more ç
definite and clear sense. Dharma is righteousness, the basis of all ç
puru<218><193>rthas (18.34). It is one's duty ordained by the scriptures ç
as per one's var<207>a and <193>·rama, by properly performing which, ç
man attains both well-being in this world (abhyudaya) and highest ç
good (ni··reyasa) (vide 4.8; 18.31; 1.40; 7.11 etc.). Sometimes ç
it has also been used as synonymous with <193>tmaj<210><193>na (vide ç
9.3) or with Karmayoga (2.40).
@SPACE1 = 
@S10N = DHARMA IN THE R°M°YAØA
Let us now turn to the two epics. The very name R<193>m<193>ya<207>a ç
has been explained as `r<193>masya ayana<221> v<216>tta<221> caritam,' ç
`the path trodden by R<193>ma or the conduct of R<193>ma.' <185>r<200> ç
R<193>ma is the hero here, depicted as the ideal man. His conduct ç
was in perfect conformity with dharma as taught and understood then. ç
To such an extent did he go that he has been described by the sage ç
V<193>lm<200>ki as `r<193>mo vigrahav<193>n dharma<199>,' `R<193>ma ç
is dharma personified'. To speak the truth and to keep up the promise ç
given, under all circumstances†this is the keynote of dharma in the ç
R<193>m<193>ya<207>a. No hardship is too great, no sacrifice is ç
too great, when compared to the fulfilment of this dharma. R<193>ma ç
had the full power and strength to vanquish Da·aratha or anybody else ç
and anoint himself as the king. Yet he did not do it since he was ç
afraid of adharma (R<193>m<193>ya<207>a 2.53.26). To please his ç
father and help him keep up his promise to Kaikey<200> he
@K = was prepared to jump into the fire or consume deadly poison or ç
drown himself in the ocean (ibid., 2.18.28-29). He was ready to give ç
up his life or S<200>t<193> or even Lak<218>ma<207>a but would never ç
break the promise once made (ibid., 3.10.19). He was not at all hesitant ç
to forsake even S<200>t<193> in order to set up a very high standard ç
of family life. Since his observance of dharma was dynamic, we can ç
safely surmise that he set up new norms of dharma by accepting the ç
hospitality of Guha and <185>abar<200>, by refusing to have more than ç
one wife and by forcing Vibh<200><218>a<207>a to conduct the last ç
rites of R<193>va<207>a.
@S10N = DHARMA IN THE MAH°BH°RATA
The  Mah<193>bh<193>rata is a veritable encyclopaedia of dharma. ç
It is here that the well-known definition of dharma (`dh<193>ra<207><193>d ç
dharmamity<193>hu<199>') already quoted, occurs. The epic gives a ç
detailed delineation of the var<207><193>·rama-dharmas. The dh<193>rmic ç
virtues like satya and ahi<221>s<193> are  highly  extolled.  Performance  of ç
ordained duties, however small or mean or repulsive they may appear ç
to be, is recommended and eulogised through the stories of Dharmavy<193>dha, ç
Tul<193>dh<193>ra and the simple housewife. The idea of the four puru<218><193>rthas ç
is well-developed, giving worldly life and worldly pursuits a decent ç
place in the scheme of life. Another very interesting feature of this ç
epic is the relaxation of the well-known moral standards and norms ç
in times of distress and emergencies (termed as <193>pad-dharma) which ç
bespeaks of the robust common sense of the author of the epic.
@S10N = DHARMA IN M®M°<189>S° AND<R>ç
VAI<185>E<186>IKA SYSTEMS
It may not be out of place here to refer to two more interpretations ç
of dharma. Jaimini in his P<220>rvam<200>m<193><221>s<193> S<220>tras ç
(1.1.2) uses the word in a very restricted sense: `codan<193>-lak<218>a<207>o'rtho ç
dharma<199>,' `Dharma is the desirable goal or result that is indicated ç
by injunctive (Vedic) passages'. So, dharma means the Vedic ritualistic ç
actions leading to happiness here or hereafter. Ka<207><193>da on ç
the other hand, gives a more liberaldefinition: ``yato'bhyudaya-ni··reyasa-siddhi<199> ç
sa dharma<199>,'' `Dharma is that from which will result both worldly ç
well-being and final beatitude' (Vai·e<218>ika S<220>tras 1.2).
@SPACE1 = 
@S10N = DHARMA IN SM<184>TIS AND DHARMA<185>°STRAS
However it is in the sm<216>tis that we come across a very detailed ç
treatment of the subject of dharma in all its intricacies. That is ç
why they have been rightly designated as `Dharma·<193>stras.' If dharma ç
is the Cosmic Law which holds together the beings of the world and ç
sustains them, it is very necessary that they be given detailed practical ç
instructions about the way of life which helps them to be always in ç
step and in tune with this dharma. Since human beings, like animals, ç
are gregarious by nature, these instructions naturally have to have ç
a sociological bias. This is exactly what the dharma·<193>stras have ç
done when they delineate the var<207>a-<193>·rama-dharmas. True to ç
the tradition of our motherland, all the dharma·<193>stras owe their ç
allegiance to the Vedas. In addition, they also accept the words and ç
conduct of saints, sages and seers well-versed in the knowledge of ç
the Vedas, as authoritative in determining dharma (vide Manusm<216>ti ç
2.6; Gautama Dharmas<220>tras 1.1-2; °pastamba Dharmas<220>tras ç
1.1.1.2; Y<193>j<210>avalkya Sm<216>ti 1.7).
Since man is a rational being and since life-situations are sometimes ç
quite intriguing,  the  dharma·<193>stras  wisely recognised the need ç
for reflective morality also, as for instance in Y<193>j<210>avalkya ç
Sm<216>ti (1.7): `·ruti<199> sm<216>ti<199> sad<193>c<193>ra<199> ç
svasya ca priyam<193>tmana<199> samyaksa<209>kalpaja<199> k<193>mo ç
dharmam<220>lam ida<221> sm<216>tam,' `The Vedas, sm<216>tis, usages ç
of good men, what is agreeable to one's self and desire born ofdeliberation†these ç
are traditionally recognised as the source of dharma'.
@SPACE1 = 
Hinduism considers man's life as a long journey towards perfection. ç
In this journey, natural desires and inclinations of man to possess ç
and enjoy the good things of life cannot be overlooked. Hence the ç
dharma·<193>stras provide for these in their scheme of life while ç
amplifying the theory of the puru<218><193>rthas. Great care has been ç
taken to give detailed rules and regulations in the acquisition of ç
artha (wealth) and k<193>ma (enjoyment of fleshly desires) within ç
the framework of dharma. However, following in the footsteps of the ç
J<210><193>nak<193><207><195>a (section that deals with spiritual ç
wisdom) of the Vedas, they always stress the importance of trying ç
for mok<218>a or liberation as the summum bonum of life (vide Manusm<216>ti ç
12.116 to 125).
No society under the sun is absolutely homogeneous. Differences do ç
exist. Even the five fingers of our own hand exhibit this principle. ç
The dharma·<193>stras recognised this natural division, called it ç
God-made and gave detailed instructions regarding the duties and responsibilities ç
of various groups or var<207>as of society towards one another in ç
their group and towards other groups. Stressing that these divisions ç
were evolved due to gu<207>a (quality) and karma (vocation), they ç
have also provided for stringent punishments for derelictions of duty ç
and rewards for sincere performance. Relaxations of these rules have ç
however been provided for, in times of distress.
While dealing with the duties of a king, the dharma·<193>stras have ç
given us a fairly  well-developed  form  of  Indian Jurisprudence. ç
Fairness and justice occupy the central place in all these rules (vide ç
Manusm<216>ti, chapters 8 & 9).
In consonance with the same principle that life is a long journey ç
towards perfection, stations (<193>·ramas) have been provided in a ç
man's life for effecting this perfection gradually. Detailed directions ç
have been provided with regard to each of the <193>·ramas.
The dharma·<193>stras have not forgotten to provide for some basic ç
rules common to all the var<207>as and <193>·ramas (s<193>m<193>nya- ç
dharmas). A perusal of these will reveal to us the great stress laid ç
on the moral life.
To err is human, to forgive divine. For the Divine to forgive, the ç
human being must make himself pure by recognising his ownsins and ç
repenting for them. The dharma·<193>stras have given us a detailed ç
treatment of the various kinds of sins and necessary expiations or ç
pr<193>ya·cittas (videManusm<216>ti, chapters 10 & 11; Y<193>j<210>avalkya ç
Sm<216>ti, 3.205 to 327; Vasi<218><219>ha Dharmas<220>tras, chapters ç
20 to 28).
Apart from these, the dharma·<193>stras also deal with the sa<221>sk<193>ras ç
or sacraments which purify human beings, making them better fitted ç
for the spiritual journey in life.
@SPACE1 = 
We thus see that the concept of dharma has undergone a healthy evolution ç
over the years, always keeping to the core meaning.
@SPACE1 = 
@SPACE = 
@SPACE1 = 
@S10N = DHARMA, NOT A STAGNANT CONCEPT
@SPACE1 = 
@SPACE = 
Sometimes it is alleged that the Hindu society is very conservative ç
and its dharma (as social laws, customs and manners) is outmoded and ç
stagnant. An impartial study of the sm<216>tis shows, on the other ç
hand, that social laws have been constantly changed, depending on ç
the needs of the times. Even Manu and Y<193>j<210>avalkya, the earliest ç
sm<216>tik<193>ras, say that when a dharma (a law or rule or custom) ç
is hated or disliked by people (lokavik<216>ta) it must be given up ç
(vide Manu 4.176). Throughout the social history of India we find ç
the rules and regulations being changed to suit the tastes and needs ç
of the people, though of course, the central spiritual principles ç
have always been kept intact. Criticism of Vedic ritualism by the ç
Upani<218>ads, changes in the views regarding anuloma marriages1 ç
and food, the kali-varjya principle2†all these clearly show that ç
the Hindu sages and law-givers were endowed with immense common sense ç
and that the Hindu society had always been dynamic.
@SPACE = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@S10N = CONCLUSION
Thus the history of dharma from the most ancient days up to the modern ç
period shows that it has always been dynamic and a very real force ç
to reckon with in the life of our nation.
We have seen how dharma which was conceived of as the Cosmic Law was ç
gradually metamorphosed into duties andresponsibilities prescribed ç
for various beings in different stages of evolution in life, but always ç
based on the principle that this evolution should ultimately bring ç
about spiritual enlightenment. If this fact is kept in mind and all ç
the members of the society act according to dharma, there is no reason ç
why all should not live in happiness and peace. After all, the saying, ç
`dharmo rak<218>ati rak<218>ita<199>' of the great <216><218>i Vy<193>sa ç
cannot go in vain!
@NT = dharmabh<220>taj<210><193>na
@N1 = (`knowledge [which is an] attribute [of the Sel<%14>f<%6>]<%0>')
How the j<200>v<193>tman or the individual soul knows an object, whether ç
such know-ledge or consciousness is accidental to it or innate to ç
it, is a subject of discussion inthe dar·anas or Indian philosophical ç
systems.
If the Advaita Ved<193>nta posits the view that consciousness is the ç
very nature of the soul, the Vi·i<218><219><193>dvaita Ved<193>nta ç
as expounded by R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137) asserts ç
that j<210><193>na or consciousness is always present in ®·vara or ç
God and the j<200>va or the soul as their dharma or attribute.
This dharmabh<220>taj<210><193>na or attributive consciousness is ç
`aja<195>a' (non-material and also non-spiritual). It illumines itself ç
and other objects. It always exists for another and never for itself. ç
That is, it cannot know itself, but illumines objects for the conscious ç
subject for whom it is an attribute.
This dharmabh<220>taj<210><193>na is eternal and all-pervasive in ç
the case of ®·vara, the nityas<220>ris (eternally illumined souls) ç
and the liberated souls. However, in the case of the j<200>v<193>tman ç
(the soul in bondage) it is contracted or obscured. When the j<200>v<193>tman ç
realises the beatific form of the Divine through the yogas of karma, ç
j<210><193>na and bhakti, his dharmabh<220>taj<210><193>na also expands ç
to infinity and becomes perfect.
Terms such as mati, praj<210><193>, sa<221>vit and ·emu<218><200> ç
are all synonyms of dharma-bh<220>taj<210><193>na.
@NT = dharmameghasam<193>dhi
@N1 = (`sam<193>dhi of the cloud of dharma')
The Yogas<220>tras of Pata<210>jali (200 <MS>B.C.<D>) is a well-known ç
ancient treatise that deals with the art and science of concentration. ç
This word `dharmameghasam<193>dhi' is a technical term used there ç
in the s<220>tra 4.29.
@SPACE1 = 
Viveka (discrimination that the puru<218>a or the soul, who is of ç
the nature of consciousness, is separate and distinct from the prak<216>ti ç
or insentient nature) and vair<193>gya (dispassion towards prak<216>ti ç
and its products) are the two basic disciplines that ultimately lead ç
to the purification of the mind and consequent experience of oneself ç
as pure consciousness. When this is achieved through sam<193>dhi or ç
perfect concentration, then even the seeds of old sa<221>sk<193>ras ç
or tendencies that might rise up and disturb the mind, are completely ç
transcended.
