But this experience of prasa<209>khy<193>na or knowledge that one ç
is the conscious spirit, separate and different from the prak<216>ti, ç
may produce a sort of attachment to that state itself as also to the ç
psychic powers that may result from it. However elevated it is, an ç
attachment even to that state is to be overcome. The yogi who is not  attracted  even  by  this,  attains ç
`dharmameghasam<193>dhi'. In this state his vivekakhy<193>ti (knowledge ç
or experience of his separateness from the insentient prak<216>ti)  is  constant,  continuous  and ç
permanent. Such a state is called `dharma-meghasam<193>dhi,' because ç
it `rains' on him, like the rainbearing cloud (= megha), the `dharma' ç
or the special quality of not being affected by any type of karma ç
he does† because he is now a liberated person† which karma is a·ukla-k<216><218><207>a, ç
neither white (good) nor black (bad), incapable of producing any fruits.
See also <MS>SAM°DHI<D> and <MS>YOGADAR<185>ANA.
@SPACE = 
@NT = dharmapari<207><193>ma
See <MS>PARIØ°MA.
@SPACE = 
@NT = Dharmar<193>ja
See <MS>YAMA.
@SPACE = 
@NT = Dharmar<193>jaratha
Situated at a distance of about 50 kms. (31 miles) from the city of ç
Madras (now called `Chennai'), on an open beach, is the village Mah<193>balipuram ç
or M<193>malla-puram, by name. It has carved for itself an important ç
place in the archaeological map of India since it contains ancient ç
rock-cut temples called `Rathas,' belonging to the period <MS>A.<|>D.<D> ç
670 to 700 and built by the Pallava king R<193>jasi<221>ha, also known ç
as Narasi<221>havarman.
These Rathas, seven of them, have withstood the vagaries of time and ç
weather, since they have been cut in granite and in single blocks ç
or big boulders. The Dharmar<193>jaratha is the biggest of them. (A ç
`ratha' is a chariot or a temple-car, the same as a vim<193>na or ç
the shrine of the temple.)
This Ratha is almost a square structure, measuring 8 metres by 8 metres ç
and rising up to 10.5 meters (26 ft. square and 35 ft. in height). ç
It has three storeys including the ground floor. There are a number ç
of images of Hindu gods like <185>iva,Brahm<193>, Vi<218><207>u, ç
Ardhan<193>r<200>·vara, Narasi<221>ha and Var<193>ha. Over these images ç
are short epigraphs containing the name of the king who built the ç
Ratha.
This Ratha too, as the others, seems to be incomplete. It looks as ç
though the construction was suddenly stopped.
@SPACE = 
@SPACE = 
@NT = dharma·<193>stras
@SB = Introduction
@SPACE1 = 
The concept of dharma and its appli- cation to the various aspects ç
of life is of fundamental importance in Hinduism. The concept itself ç
has undergone several changes over the centuries. As derived from ç
the root `dh<216>' (`to support, to sustain'), the most general meaning ç
of the word `dharma' is `that which supports and sustains'. Gradually ç
it came to acquire several senses such as†ordinance, usage, duty, ç
right, justice, morality, virtue, reli-gion, good works, function ç
or characteristic. However, the sense of `duties and responsibilities ç
based on some fundamental moral virtues' became most widely accepted.
@SB = Sources of Dharma
The Vedas being the primary scriptures of Hinduism, naturally get ç
the pride of place as the definer and the source of dharma. But, with ç
the growth of the human society and the consequent problems it had ç
to face, there arose a great need to expand the scope of and to delve ç
deeper into, the concept itself. It is this that gave rise to the ç
composition of the later works, now included under the comprehensive ç
term `dharma·<193>stras.'
According to all these works, the sources of dharma are: the Vedas; ç
the sm<216>tis; the teachings and conduct of persons who are well-versed ç
in the scriptures and are of unblemished character; one's own conscience.
@SB = Growth of the Dharma·<193>stras
Though the Vedas do not have positive precepts on matters of dharma† ç
concerning personal conduct and social regulations as understood and ç
defined by the later works, they do contain incidental references ç
to various topics that fall under the domain of the dharma·<193>stras. ç
There are at least 50 passages in the Vedas that shed light on the ç
forms of marriage, different kinds of sons, adoption of a son, partition, ç
inheritance, ·r<193>ddha ceremony and str<200>dhana or property that ç
should rightfully accrue to women. All these topics have been dealt ç
with in much greater detail in the dharma·<193>stras.
The first stage in the evolution of the dharma·<193>stras is met with ç
in the Ved<193><209>ga (`limb of the Veda' or a subsidiary of the ç
Veda) called `kalpas<220>tras.' `Kalpa' means procedure, the `how' ç
of a thing.
@SPACE1 = 
The  kalpas<220>tras  comprise  four sections:
(1) ·rautas<220>tras; (2) g<216>hyas<220>tras; (3)dharmas<220>tras ç
and (4) ·ulbas<220>tras.
The first and the last are directly concerned with Vedic sacrifices. ç
Whereas the g<216>hyas<220>tras deal with the rites and ceremonies ç
to be performed by a householder in his house (g<216>ha = house), ç
the dharmas<220>tras are concerned with the more general and social ç
aspects of dharma, the conduct of human beings as members of a society, ç
of a community. However, these two are interconnected and even inter- ç
dependent.
In the g<216>hyas<220>tras and the dharma-s<220>tras, the language ç
is archaic and the delineation of the subjects is not very systematic. ç
Hence the need arose for the composition of another class of works, ç
now well-known as `sm<216>tis,' written in a more intelligible language ç
and mostly in poetical verses, to facilitate easy remembrance. Quite ç
a few of these sm<216>tis are now available in print.
Though the dharmas<220>tras in general, are more ancient than the ç
metrical sm<216>tis, it is equally possible that some from the latter ç
group like the Manusm<216>ti, are as old as the former or even older. ç
At least, the core-content could be so.
As <|>the <|>implementation <|>of <|>the<|> rules ofconductinthesocietyprogressed, ç
problems, including differences of opinion must have cropped up. Hence, ç
commentaries on these works, attempting to expand the ideas given ç
there or clear the doubts and anomalies, were written by competent ç
scholars, thus enriching the whole field of dharma·<193>stra literature.
As the number of such compositions increased, it became necessary ç
to produce ready-reference   material,   containing abstracts, surveys ç
and reviews, of all the matter available on that subject. This gave ç
rise to another class of works known as `nibandhas' or digests.
The two epics†the R<193>m<193>ya<207>a and the Mah<193>bh<193>rata†as ç
also many of the pur<193><207>as contain a lot of material that should ç
normally be the concern of the dharma·<193>stras. The nibandhas, naturally, ç
have made good use of this material at the appropriate places.
Hence any standard work on the dharma·<193>stras should avail of all ç
the relevant stuff provided by these various sources.
@SB = Topics of the Dharma·<193>stras
The topics generally dealt with in the dharma·<193>stras fall under ç
three broad groups: <193>c<193>ra (general conduct), vyavah<193>ra ç
(social conduct, law and order) and pr<193>ya·citta (expiatory rites ç
for transgressions).
They may now be described briefly.
@SB = °c<193>ra
Unless the body-mind complex is kept clean and pure, both physically ç
and ceremonially, a human being cannot attain dharma in its two primary ç
aspects, viz., abhyudaya (worldly progress) and ni··re-yasa (spiritual ç
welfare). This is achieved by strictly following <193>c<193>ra or ç
the code of conduct, prescribed to be followed in one'spersonal life. ç
This code as ordained in the ·ruti (the Vedas), the sm<216>tis (the ç
secondary scriptures) and sad<193>c<193>ra (conduct of the sagely ç
persons) should be practised meticulously, without indolence or neglect. ç
Sad<193>c<193>ra (good conduct) leads to long life, fulfilment of ç
desires and attainment of wealth, whereas dur<193>c<193>ra (bad and ç
sinful conduct) results in disease, suffering, short-life and ill-fame.
The <193>c<193>ra or sad<193>c<193>ra concerns mainly what are termed ç
as `<218>a<219>karmas' or six daily rituals. They are: sn<193>na & ç
sandhy<193> (bath and the sandhy<193> ritual), japa (repetition of ç
Vedic mantras or God's name), homa (oblations into a consecrated fire), ç
devap<220>ja (worship of gods), <193>tithya (entertaining the guests) ç
and vai·vadeva (offering cooked food to all the gods).
Tarpa<207>a or ceremonial offering of water with appropriate mantras, ç
to devas (the gods), <216><218>is (sages) and pit<216>s (manes) is ç
also included in the daily routine.
Some aspects of these karmas like bath, worship of one's family deity, ç
repetition of the divine name and entertaining guests, apply to persons ç
of all castes without any distinction.
As an important part of the `<193>c<193>ra-k<193><207><195>a' (section ç
dealing with the <193>c<193>ras), the <218>o<195>a·asa<221>sk<193>ras ç
or 16 purificatory sacraments  are  also  delineated.  Upa- nayana ç
(investiture with the sacred thread called `yaj<210>opav<200>ta' and ç
the imparting of the famous G<193>yatr<200>-mantra), viv<193>ha (marriage) ç
and antye<218><219>i (after-death ceremonies) are the most prominent ç
of the 16 sacraments.
@SPACE1 = 
Another aspect of life, which is cardinal to Hindu religion and society, ç
viz., the var<207>a-<193>·rama-dharmas, has also been given the primary ç
place in all the dharma·<193>stra works in the <193>c<193>ra section.
@SB = Vyavah<193>ra
Though the word `vyavah<193>ra' refers to the general social conduct, ç
in the dharma·<193>stras it is used in a more technical sense, that ç
of civil and criminal law.
In this section 18 subjects have been dealt with. Some of them are: ç
<216><207><193>d<193>na (debts), sambh<220>ya-samutth<193>na (partnership), ç
sa<221>vid-vyatikrama (breach of contract), kraya-vikraya (purchase ç
and sale), sv<193>mi-p<193>la-viv<193>da (disputes between the master ç
and the servant), s<200>m<193>viv<193>da (boundary   disputes),  da<207><195>ap<193>ru<218>ya ç
(assault), v<193>kp<193>ru<218>ya (libel), steya (theft), str<200>sa<209>graha<207>a ç
(abduction of women), str<200>pu<221>dharma (relation between husband ç
and wife) and vibh<193>ga (partition).
The king's court was the judiciary. He was assisted by men of knowledge, ç
wisdom and character in the dispensation of justice. He could also ç
depute a judge to act on his behalf. There were duly appointed persons ç
to oversee the implementation of the decisions taken by the court.
@SPACE = 
@SB = Pr<193>ya·citta
@SPACE = 
To err is human. Human beings are prone to commit errors of omission ç
and commission. If they do not realise their faults and mistakes, ç
and do not reform themselves, they have to suffer a lot. This reformation ç
has to be in two stages: repentance and a firm resolve that the mistake ç
will not be repeated; expiation for the ones already committed.
The mistakes are called `p<193>taka or p<193>pa' (sin) and the expiations, ç
`pr<193>ya·citta'.
The pr<193>ya·citta  sections  of  the dharma·<193>stras describe ç
the various types of sins, categorise them into mah<193>p<193>takas ç
(mortal sins) and upap<193>takas (venial sins) and prescribe the necessary ç
expiations.
Sins like brahmahaty<193> (killing a br<193>hma<207>a), sur<193>p<193>na ç
(drinking wine and other intoxicating liquids) and incest are classed ç
among the mah<193>p<193>takas. Minor sins like forsaking the sacred ç
fires, offending the guru (Vedic teacher), minor thefts, non-payment ç
of debts, selling prohibited articles, cutting down trees or killing ç
harmless animals and so on, are grouped under upap<193>takas.
The pr<193>ya·cittas can vary from certain modes of tapas (austerities) ç
like fasting, japa (repetition of certain Vedic formulae or names ç
of God), d<193>na (giving gifts), going on a pilgrimage (for minor ç
sins), right up to religious suicide (for heinous sins).
@SB = The Philosophy of the Dharma·<193>stras
The dharma·<193>stras are not only based on the Vedas, but, amplify ç
their teachings for better application at day-to-day practical level. ç
Of course, they do not forget to emphasise that the final goal of ç
human life is the attainment of God who is one without a second, who ç
is called by various names, who is the Supreme Ruler of the universe, ç
the origin of creation and its final destination.
It is admirable that the dharma-·<193>stras have recognised the importance ç
of the physical body†its health, strength and energy as also its protection ç
against dangers in times of emergency†as basic to any achievement ç
in life, whether spiritual or temporal. Hence they advise everyone ç
to protect his life and limb by all means at his disposal.
However, this is only the first step. Equally important is the cultivation ç
of moral values. All the dharma·<193>stra works, without exception, ç
lay great stress on the s<193>m<193>nya-dharmas or universal principles ç
of truth, self control, decent and dignified behaviour (especially ç
towards the women-folk), earning one's livelihood by honest and right ç
means, performing one's duties and discharging the obligations to ç
one's family and the society, not harming others, personal and environmental ç
cleanliness, study of (or listening to) sacred literature, a certain ç
degree of austerity and devotion to God.
@SB = Some Important Dharma·<193>stra Works
The dharma·<193>stra literature (in Sans-krit) is very vast. Apart ç
from the well-known works directly composed on the topics of the dharma·<193>stras, ç
there are innumerable verses spread over the two epics and the pur<193><207>as ç
dealing with the various aspects of the subject. Here, an attempt ç
will be made to give a very brief account of the more ancient and ç
important of the works.
@SPACE = 
@S10N = DHARMAS<188>TRAS
@SB = °pastamba Dharmas<220>tras
This work forms the 28th and the 29th pra·nas or sections of the bigger ç
work, the °pastamba Kalpas<220>tras. It belongs to the K<216><218><207>a ç
Yajurveda. When compared with the G<216>hyas<220>tras of the same ç
author, there are a few s<220>tras which are identical and the topics ç
are inter- related. It may be assigned to the period 450-350 <MS>B.C.<D> ç
The style is more archaic and the s<220>tras are very concise.
A wide range of topics normally dealt with in the dharma·<193>stras ç
are found here also though the pr<193>ya·citta portion is more elaborate. ç
One of its peculiarities is that it abounds in the technical terms ç
and doctrines of the P<220>rvam<200>m<193><221>s<193> school.
@SB = Au·anasa Dharmas<220>tras
K<193>vya U·anas is an ancient sage mentioned even in the <184>gveda.
There is an Au·anasa Dharma·<193>stra mostly in prose, available ç
now, though in parts. The topics dealt with are: a·auca (impurity ç
on birth and death), the four var<207>as and some mixed castes, pr<193>ya- ç
·cittas and ·r<193>ddha (obsequial rites).
The Au·anasa Dharmas<220>tras is in prose and contains material ç
identical with that of some parts of the Manusm<216>ti. From the ç
writings of other authors it is possible to assume that a bigger s<220>tra ç
work was available, dealing with all the three aspects of <193>c<193>ra, ç
vyavah<193>ra and pr<193>ya·citta.
Another dharma·<193>stra and also a sm<216>ti, both ascribed to U·anas ç
are available now either in print or in the manuscript form. The former ç
has 51 verses and deals mainly with the mixed castes such as s<220>ta ç
and m<193>gadha. The latter has 600 verses in 9 chapters and deals ç
with such topics as upanayana and ·r<193>ddha.
@SB = Baudh<193>yana Dharmas<220>tras
Baudhy<193>na probably lived during the period 600-300 <MS>B.C.<D> ç
and belonged to South India. His work on all the four branches of ç
the Kalpa are available now.
The Dharmas<220>tras is in 4 pra·nas or kha<207><195>as (sections). ç
The subjects dealt with are: upanayana, duties of a brahma-c<193>rin, ç
severalpurificatory rites, forms of marriage, ·r<193>ddha ceremonies, ç
sa<221>ny<193>sa and some rites for securing siddhis or supernatural ç
powers.
The G<216>hyas<220>tras deals mainly with the sa<221>sk<193>ras.
@SB = Gautama Dharmas<220>tras
This ancient work is entirely in prose and can be assigned to the ç
period 600-400 <MS>B.C.<D> It has 28 chapters.
The topics dealt with are: details of the upanayana for the various ç
var<207>as, the four <193>·ramas, avocations of the four var<207>as, ç
sa<221>sk<193>ras or sacraments, details of the duties of a king including ç
crime and punishment, duties of women, pr<193>ya·cittas, rules of ç
partition of property and a few other minor topics.
@SB = H<193>r<200>ta Dharmas<220>tras
H<193>r<200>ta is considered as an ancient teacher since he has been ç
quoted by °pastamba, Baudh<193>yana and Vasi<218><219>ha. The work ç
available now has thirty chapters. He speaks of eight kinds of marriages, ç
of  which  k<218><193>ttra  and  m<193>nu<218>a  have replaced <193>r<218>a ç
and pr<193>j<193>patya given in other works. He mentions two kinds ç
of women, brahmav<193>din<200>s and sadyovadh<220>s, the former being ç
entitled to undergo upanayana, to the study of the Vedas and even ç
to the maintenance of Vedic fires.
This work may be assigned to the period 600-300 <MS>B.C.<D>
@SB = Hira<207>yake·i Dharmas<220>tras
This treatise forms the 26th and the27th pra·nas of the Kalpas<220>tras ç
by Hira<207>yake·in. It has borrowed profusely from the s<220>tra ç
works of °pastamba and Bh<193>radv<193>ja. Hence, it is not considered ç
as an independent authority.
The author belonged to the Taittir<200>ya school of K<216><218><207>a ç
Yajurveda and lived inthe Konkan region (West Coast, South India).
@SB = Vaikh<193>nasa Dharmas<220>tras
The work as available now, is a small one. It is also called Vaikh<193>nasa-dharma-pra·na. ç
It is considered as a later production, by a devotee of N<193>r<193>ya<207>a ç
and may belong to the period <MS>A.D.<D> 300-400. It could be a redaction ç
of an earlier work.
It mentions four kinds each, of brahmac<193>rins, g<216>hasthas, v<193>naprasthas ç
and sa<221>ny<193>sins.
Purification  of  golden  and  other metallic objects as also other ç
things before their use, mentioned here seems to be interesting.
@SB = Vasi<218><219>ha Dharmas<220>tras
Assigned to the period 300-100 <MS>B.C.<D> this work is not a part ç
of a kalpas<220>tra. It is very similar to the Dharmas<220>tras ç
of Baudh<193>yana and Gautama.
The topics dealt with are almost the same as in other, similar, works. ç
He mentions only six forms of marriage, allows niyoga (levirate) and ç
the remarriage of child-widows. Administration of justice by the king ç
is another important subject dealt with.
@SB = Vi<218><207>u Dharmas<220>tras
This book professes to be a revelation of Vi<218><207>u in his Var<193>ha ç
or Boar-incarnation. It is said to belong to the Ka<219>ha school ç
of the K<216><218><207>a Yajurveda. It has a hundred chapters in ç
mixed prose and verse, of which some parts are in common with the ç
K<193><219>haka G<216>hyas<220>tras, popular in Kashmir.
It draws heavily on the Manusm<216>ti. R<193>jadharma (duties of ç
a king), crime and punishment, twelve kinds of sons, mixed castes ç
and funeral rites are some of the topics dealt with.
The date of the older part of this treatise is fixed as 300-100 <MS>B.<|>C.<D>
@S10N = SM<184>TIS
@SB = A<209>girasa Sm<216>ti
A<209>giras is one of the ten primordial sages and has been mentioned ç
even in the <184>gveda.
Three sm<216>tis bearing his name have been published so far. The ç
first one has 72 verses and is probably an abridgement. It deals mainly ç
with pr<193>ya·cittas.
The second one has 168 verses, the subjectbeing, again,pr<193>ya·cittas. ç
It mentions some of the well-known authors of sm<216>tis like °pastamba, ç
<185>a<209>khalikhita and Sumantu.
The third one has 1200 verses and is different from the other two ç
editions.
@SB = Atri Sm<216>ti
Atri was an ancient writer on dharma. Even Manu refers to him.
There is one °treya Dharma·<193>stra available in 9 chapters. The ç
work is in verses as well as in prose, in the s<220>tra form.
The topics dealt with are: gifts, prayers, austerities and expiations.
The work refers to a number of foreign tribes such as <185>akas, Yavanas, ç
B<193>hl<200>kas and Para·as.
There are other works styled Atri Sm<216>ti or Atri Sa<221>hit<193> ç
available in the manuscript form. They contain secret expiations for ç
sins. They also deal with gifts and <193>c<193>ra.
Another Atri Sa<221>hit<193>, available in print has 400 verses ç
and deals with the duties of the four castes.
Two more works†Laghu Atri and V<216>ddha-<193>treya Sm<216>ti ç
are also available.
@SB = B<216>haspati Sm<216>ti
B<216>haspati was an ancient teacher ofartha·<193>stra (economics ç
and political science). He probably wrote a dharmas<220>tra work which ç
is not available now. He has been quoted by several writers on the ç
dharma·<193>stras. Some writers consider him as an atheist.
The B<216>haspati Sm<216>ti available now has seven sections (mostly ç
in verses) dealing with vyavah<193>ra (social conduct), <193>c<193>ra ç
(general conduct) including <193>pad-dharma (emergency measures) and ç
pr<193>ya·citta.
He is assigned to the period <MS>A.D.<D> 300-500.
@SB = B<216>hat-Par<193>·ara Sm<216>ti
This is an extensive work of a late period, in 12 chapters comprising ç
3000 verses. It seems to be a recast of the Par<193>·ara Sm<216>ti ç
by one Suvrata. The subjects dealt with are: <218>a<219>karmas or ç
six items of the daily routine, sa<221>sk<193>ras, a·auca, pr<193>ya·cittas, ç
duties of the four <193>·ramas, r<193>jadharma (a king's duties and ç
responsibilities) and yogic disciplines.
@SB = Dak<218>a Sm<216>ti
This sm<216>ti is an old one. Printed texts have 220 verses distributed ç
in seven chapters. The subjects treated are: the four <193>·ramas, ç
daily round of duties of the dvijas, various types of action, making ç
gifts, a·auca, yoga and its limbs, philosophies of the dvaita and ç
the advaita schools.
This sm<216>ti has been extensively quoted by others.
@SB = Devala Sm<216>ti
Devala is a sage whose name often appears in the Mah<193>bh<193>rata, ç
sometimes, along with another sage Asita. A dharma-s<220>tra treatise†probably ç
an extensive one †hasbeenattributed tohim. It perhaps contained ç
sections on <193>c<193>ra, vyavah<193>ra and ·r<193>ddha, as can be ç
guessed by the numerous quotations in other works.
The Devala Sm<216>ti available now seems to be a late work. It is ç
in 90 verses and deals with purificatory rites.
@SB = Gobhila Sm<216>ti
There is a g<216>hyas<220>tra work of Gobhila belonging to the S<193>maveda. ç
The Gobhila Sm<216>ti available now has 491 verses in three sections. ç
Topics like yaj<210>opav<200>ta, up<193>karma and ·r<193>ddha are ç
dealt with in this work.
@SB = K<193>ty<193>yana Sm<216>ti
N<193>rada, B<216>haspati and K<193>ty<193>yana are the Trinity of ç
sages considered as authorities in ancient Hindu Law. His work as ç
available now has 973 verses (with an addenda of another 121 verses). ç
Portions of the work on the vyavah<193>ra section are yet to be recovered. ç
He might have lived during the period 4th to 6th cent. <MS>A.<|>D.
@SPACE1 = 
Another work, also attributed to K<193>ty<193>yana is available in ç
3 sections comprising 29 chapters and about 500 verses. The contents ç
are: details of wearing the sacred thread, worship of Ga<207>e·a and ç
the various goddesses in religious rites, some information connected ç
with Vedic sacrifices, chanting of Vedic mantras, ·r<193>ddha and ç
a·auca.
@SB = Manusm<216>ti
The Manusm<216>ti is the most ancient and  authoritative  among  the  extant ç
metrical treatises on dharma. It has 12 chapters and 2684 verses, ç
covering all the three aspects of a typical dharma·<193>stra as follows: ç
<193>c<193>ra (chs. 1-7), vyavah<193>ra (chs.8-10) and pr<193>ya·citta ç
(chs. 11<|>&<|>12).
The topics dealt with include: creation of the world, four <193>·ramas, ç
the sixteen sa<221>sk<193>ras, ·r<193>ddha, the four var<207>as (castes), ç
disputes and their resolution, <193>pad-dharmas (conduct during emergencies), ç
the mortal sins and their expiation, good and bad deeds as also the ç
nature of the °tman.
The extant work may be assigned to the period 300 <MS>B.C.<D> It may ç
have undergone quite a few redactions.
@SB = N<193>rada Sm<216>ti
The printed edition of this work has 21 chapters and 1028 verses. ç
It was probably composed during <MS>A.<|>D.<D> 100-300.
It follows the Manusm<216>ti closely. It has been quoted by a few ç
authors of nibandhas. The contents are generally the same as in the ç
other dharma·<193>stras. N<193>rada differs from Manu in some respects ç
and has introduced many sub-divisions inthe major topics. His classification ç
of impotent  persons,  women  who  can remarry, as also some of the ç
juristic and political principles distinguish it from other works.
@SPACE = 
@SB = Par<193>·ara Sm<216>ti
Though Par<193>·ara was an ancient sage, the present work available ç
in print must be a product of several revisions. The Par<193>·ara ç
Sm<216>ti is said to be the ideal guide for this Kaliyuga or the ç
Iron-age. It has 12 chapters and 592 verses. It deals only with <193>c<193>ra ç
and pr<193>ya·citta.
The contents are: the four yugas, the six daily duties, Vedic study, ç
duties of a householder, the four var<207>as and their duties, remarriage ç
of widows under certain conditions, purification of various articles ç
of use and expiations of various types for sins.
Two more works†the B<216>hat-Par<193>·ara and the V<216>ddha-Par<193>·ara†are ç
also available which are obviously later compositions.
@SPACE = 
@SB = Sa<221>varta Sm<216>ti
The Sa<221>varta Sm<216>ti as available in print today has 230 verses. ç
It contains very ancient material. The extant work may be an epitome ç
of the original sm<216>ti. It is in the form of teaching given by ç
the sage Sa<221>varta to V<193>madeva and other sages.
Its main contents are: rules of conduct for the brahmac<193>rin; pr<193>ya·cittas ç
for lapses on the part of the brahmac<193>rin and others;  duties  of  householders,  forest ç
hermits and monks.
Other authors have referred to the views of Sa<221>varta on topics ç
of vyavah<193>ra by quoting him.
@SB = Vy<193>sa Sm<216>ti
There is a sm<216>ti ascribed to Vy<193>sa and is available now. It ç
has four chapters and 250 verses. It can be assigned to the period ç
<MS>A.<|>D.<D> 200-500.
The contents can be summarised as follows: authoritativeness of the ç
<185>ruti, thesm<216>ti and the pur<193><207>as; the sixteen sa<221>sk<193>ras; ç
mixed castes; duties of a brahmac<193>rin; marriage; nitya (obligatory) ç
naimittika (occasional) and k<193>mya (desire-motivated) karmas; eulogy ç
of the householder stage and a few other related topics.
@SB = Y<193>j<210>avalkya Sm<216>ti
Y<193>j<210>avalkya is a highly respected and one of the most brilliant ç
and outstanding sages of ancient India. The <185>ukla Yajurveda ç
was revealed to him.
The sm<216>ti that goes in his name now, has 1010 verses distributed ç
among the three k<193>n<195>as or sections dealing with all the three ç
topics: <193>c<193>ra, vyavah<193>ra and pr<193>ya·citta. The whole ç
work is well-organised and is in the classical anu<218><219>ubh metre.
The subjects dealt with can be briefly stated as follows: sa<221>sk<193>ras, ç
marriage, var<207>a and j<193>ti, d<193>na, ·r<193>ddha, details of ç
civil disputes and the methods of solving them, crime and punishment, ç
a·auca and pr<193>ya·cittas as also some miscellaneous topics.
The original text must have undergone several revisions. The present ç
form probably belongs to the period 100 <MS>B.<|>C.<D> to <MS>A.<|>D.<D> ç
300.
@SB = Yama Sm<216>ti
Yama was probably a great sage since his views have been quoted even ç
in the Vasi<218><219>ha Dharmas<220>tras.
The extant sm<216>ti has 78 verses dealing  with  pr<193>ya·citta  and  ·uddhi ç
(purificatory rites).
It is interesting to note that he prescribes punishment for cutting ç
trees, shrubs, plants and creepers, especially if they have flowered ç
or have fruits!
@S10N = NIBANDHAS
@SB = Caturvargacint<193>ma<207>i
This is an encyclopaedic work by Hem<193>dri on ancient religious ç
rites and observances. It might have been composed during the period ç
<MS>A.<|>D.<D> 1260-1270. Four volumes containing 6000 verses have ç
so far been printed. The complete work has not been recovered till ç
now. The four puru<218><193>rthas form the main content of the work. ç
The topics of vrata (religious rites and observances), d<193>na (gifts), ç
·r<193>ddha (obsequial ceremonies) and k<193>la (time and proper periods ç
for the observance of religious rites) have been dealt with in great ç
deal.
@SB = Kalpataru
The Kalpataru or the K<216>tya-kalpataru of Lak<218>m<200>dhara ç
is a voluminous work in fourteen k<193><207><195>as or Books. Lak<218>m<200>dhara ç
was a minister in the cabinet of the king Govindacandra of Kanauj ç
(<MS>A.<|>D.<D> 1114-1154).
This treatise has exercised tremendous influence in North India for ç
over 500 years.
The subjects dealt with in these fourteen k<193><207><195>as are: ç
duties of brahma-c<193>rins and g<216>hasthas, <193>hnika, ·r<193>ddha, ç
vratas, p<220>j<193> (worship of gods), pilgrimage, pr<193>ya·cittas, ç
·uddhi, duties of a king, law and administration, ·<193>ntis (propitiatory ç
rites) and mok<218>a (liberation).
@SB = Nir<207>ayasindhu
An extensive and erudite work of Kamal<193>kara Bha<219><219>a, this ç
was probably composed around <MS>A.<|>D.<D> 1612. About a hundred sm<216>tis ç
and three hundred authors of nibandhas have been named in this treatise.
The topics dealt with are: k<193>la, vratas, sa<221>sk<193>ras, Agnihotra, ç
·r<193>ddhas, kalivarjyas  (actions  forbidden  in  the Kaliyuga), ç
a·auca and also sa<221>ny<193>sa.
@SB = Sm<216>ticandrik<193>
This is a well-known digest on the dharma·<193>stra topics, by Deva<207><207>abha<219><219>a ç
(circa <MS>A.<|>D.<D> 1150-1225), most probably from South India.
Thecontents are: var<207>a-<193>·rama-dharmas; sa<221>sk<193>ras; ç
daily duties of a dvija; sandhy<193>, ·rauta and sm<193>rta rites; ç
rules about food; the five daily sacrifices; procedure of law-courts; ç
d<193>yabh<193>ga; and ·r<193>ddhas.
Though several writers composed works styled Sm<216>ticandrik<193>, ç
it is only Deva<207><207>abha<219><219>a's work that is held as authoritative ç
and relied upon.
@SB = Sm<216>tikaustubha
Composed around the period <MS>A.D.<D> 1645-1695 by Anantadeva (grandson ç
of the famous Marathi saint and poet Ekn<193>th), this vast digest ç
deals with several topics such as: the sixteen sa<221>sk<193>ras, ç
rules for adoption, festivals and sacred days, v<193>stu ·<193>stra ç
(architecture and town planning), coronation of a king, homas and ç
·<193>ntis.
@SB = Sm<216>tiratn<193>kara
Ca<207><195>e·vara (circa <MS>A.<|>D.<D> 1314), the author of this ç
extensive digest was a minister in the court of the king Bhave·vara ç
of Mithil<193>. This work is also known as the Ratn<193>kara. It ç
contains seven sections, each of them being called `Ratn<193>kara'. ç
They are: K<216>tyaratn<193>kara, D<193>naratn<193>kara, <185>uddhiratn<193>kara, ç
P<220>j<193>-ratn<193>kara, Vyavah<193>raratn<193>kara, Viv<193>da-ratn<193>kara ç
and G<216>hastharatn<193>kara.
The subjects dealt with comprise the following areas: vratas, duties ç
of house- holders, various kinds of gifts, civil and criminal law, ç
a·auca as also p<220>j<193>.
@SPACE = 
@SB = Sm<216>titattva
@SPACE = 
This is the work of Raghunandana (<MS>A.<|>D.<D> 1510-1580), the last ç
great writer of Bengal on the dharma·<193>stras. It is divided into ç
28 sections, each being called `tattva', such as Tithitattva, Durg<193>p<220>j<193>tattva, ç
D<193>yatattva and so on. The topics delineated include†purificatory ç
rites, sacraments, festivals like Janm<193><218><219>am<200> and Durgotsava, ç
civil law, public utility works, religious observances, establishment ç
of temples, ·r<193>ddha and so on.
@SPACE = 
@SB = V<200>ramitrodaya
@SPACE = 
The V<200>ramitrodaya of Mitrami·ra (circa <MS>A.<|>D.<D> 1610-1640) ç
is a vast digest of dharma·<193>stras, the second largest in size. ç
Each of the sections is named as a `prak<193>·a,' such as Vyavah<193>raprak<193>·a, ç
Sa<221>sk<193>raprak<193>·a, R<193>jan<200>tiprak<193>·a and so ç
on.
The contents include the following topics: <193>hnika, p<220>j<193>, ç
pilgrimage, civil law, sa<221>sk<193>ras, r<193>jan<200>ti or political ç
science, giving gifts, purificatory rites, ·r<193>ddha, pr<193>ya·cittas, ç
bhakti and mok<218>a.
@SB = Other Sources
@EMERGENCY = Apart from the dharmas<220>tras, the sm<216>tis and the ç
nibandhas, another factor that has contributed significantly to the ç
enormous growth of this class of literature is the composition of ç
learned commentaries on these works. These commentaries have explained ç
the originals, expounded the various doctrines and subtle points and ç
resolved many doubts and misgivings, thus giving a clear practical ç
direction for implementing the various rules of the originals.
The following table gives some idea of these commentaries:
@NID = 1.
@NOK = Commentaries of Haradatta, Maska-rin and Asah<193>ya on the ç
Gautama Dharmas<220>tras.
@NID = 2.
@NOK = Bh<193><218>yas (expositions) of Medh<193>tithi, Kull<220>ka ç
and five others on the Manusm<216>ti.
@NID = 3.
@NOK = B<193>lakr<200><195><193> of Vi·var<220>pa, Mit<193>k<218>ar<193> ç
of Vij<210><193>ne·vara and Dikp<193>lik<193> of <185><220>lap<193><207>i ç
on the famous Y<193>j<210>avalkya Sm<216>ti.
@NID = 4.
@NOK = Par<193>·ara-m<193>dhav<200>ya by M<193>dhav<193>-c<193>rya ç
(Vidy<193>ra<207>ya) and Vidvanmanohar<193> of Nandapa<207><195>ita ç
on the Par<193>·ara Sm<216>ti.
The Artha·<193>stra of Kau<219>ilya (300 <MS>B.C.<D>) along with ç
its two commentaries Nayacandrik<193> of M<193>dhava Yajvan and ç
Pratipadapa<210>cik<193> of Bha<219><219>a Sv<193>min contains a<|>lot ç
of material on vyavah<193>ra and r<193>ja-dharma, two of the important ç
topics discussed by most of the dharma·<193>stras.
The R<193>m<193>ya<207>a, though a k<193>vya or a literary composition, ç
contains quite a few references to some of the topics discussed in ç
the dharma·<193>stra treatises. Details of the coronation of a king, ç
effects of anarchy, sins (and expiations), duties and responsi-bilities ç
of a king, obsequial rites, value of truth, and, duties and virtues ç
of women† all these topics have found a place in the epic, here and ç
there.
Similarly, the Mah<193>bh<193>rata also contains a lot of material ç
that comes under the purview of the dharma·<193>stras. The following ç
are the subjects dealt with, somebriefly, others more exhaustively: ç
coronation, evils of anarchy, ahi<221>s<193> (non-violence), the dharmas ç
of the var<207>as and <193>·ramas, <193>c<193>ra, <193>pad-dharmas, ç
pilgrimage, giving gifts, d<193>yabh<193>ga, expiations for sins, ç
rules regarding food, political science (in detail), marriage and ç
·r<193>ddha.
The eighteen principal pur<193><207>as as also some of the minor ones ç
contain extensive and very rich material on the various topics discussed ç
in the dharma-·<193>stras. That is why the commentators and the authors ç
of the nibandhas have quoted from them profusely.
A brief list of these topics as they appear in the pur<193><207>as ç
may now be given:
<193>c<193>ra, <193>hnika, a·auca, var<207>a-<193>·rama- dharmas, ç
rules about food, d<193>na, kali- varjya (what is prohibited in the ç
Kaliyuga), sins and their expiations, duties of a king, sa<221>sk<193>ras, ç
·<193>ntis, ·r<193>ddha, pilgrimages, vratas,vyavah<193>raandyugadharmas ç
(special characteristics of the four yugas).
@SPACE = 
@SB = Epilogue
@SPACE = 
The Hindu society has had a chequered history over the last 2500 ç
years. The dharma·<193>stras too, have grown over the same period, ç
not only to voluminous but also to highly refined, proportions. They ç
have played a very significant part in preserving the unity and solidarity ç
of the society to a considerable extent.
This they have done by:
1.
@NK = preserving the basic values of life compressed in one omnibus ç
term called `dharma.'
2.
@NK = stressing the duties and respons-ibilities towards the society ç
much more than rights and privileges.
3.
@NK = making the necessary adjustments to suit the needs of the changing ç
times.
4.
@NK = not allowing any socio-political rule to have an absolute status, ç
but always preferring a well- established custom to the rule in the ç
Book.
As long as there were Hindu rulers to enforce the code of conduct ç
as prescribed by the dharma·<193>stras, there was order and peace ç
in the society. When the political power passed into the hands of ç
ruthless alien rulers, even a safe and honourable existence became ç
a serious problem. Hence the religious and social leaders, swimming ç
against the current, made supreme efforts to preserve the unity and ç
integrity of the society by modifying the <193>c<193>ra and the pr<193>ya·citta ç
parts of dharma as much as possible, since the vyavah<193>ra part ç
had practically passed out of their hands.
There is a charge that the writers of the dharma·<193>stras of later ç
periods (<MS>A.D.<D> 1000 onwards) unnecessarily went into great depths ç
to discuss small details. One should not forget that, by this time, ç
the dharma·<193>stras had become an important subject for study and ç
discussion even in the academic circles of the day, in the traditional ç
institutions like Ma<219>has, P<193><219>ha·<193>las and Vidy<193>layas. ç
Hence, this scholarship was both necessary and useful in those circles.
Another accusation levelled against these dharma·<193>stras is that ç
they were meant only for the first three castes, that too for the ç
br<193>hma<207>as and the k<218>attriya rulers, and were not very ç
helpful to the others. The reply is that the society of those days ç
was like that and hence these works had to be in tune with the same. ç
An examination of these works also reveals the startling fact that ç
the higher a person was in the social hierarchy, more stringent were ç
the rules guiding or binding him! And, this certainly is not a point ç
for pointing the finger of accusation!
Again, the dharma·<193>stras in general, have all along maintained ç
that any rule disliked by the majority of the people should be replaced ç
by a more agreeable one. The principle of kalivarjya or <193>pad-dharma ç
is a case to the point.
After India gained political freedom, drastic changes have been made ç
in the structure of general laws and Hindu Law, correcting many an ç
imbalance of the past ages. In spite of this, if justice is not being ç
meted out to the weaker sections of the society, the fault obviously ç
lies elsewhere!
@NT = Dharmasindhu
@N1 = (`Ocean of dharma')
For over two millennia, Hindu society has been guided and regulated ç
by a special class of literature known as the dharma-·<193>stras. ç
These works have prescribed rules of conduct for a person both at ç
the individual and at the social level.
@SPACE1 = 
The dharma·<193>stra literature has three aspects: the dharmas<220>tras, ç
the sm<216>tis and the nibandhas.
The nibandhas are digests containing a lot of information on various ç
aspects of dharma and its application, culled from a number of authoritative ç
sources.
The Dharmsindhu†also known as the Dharmasindhus<193>ra or Dharm<193>bdhi-s<193>ra†of ç
K<193>·<200>n<193>tha Up<193>dhye, is a leading and popular work especially ç
in the Maha-rashtra State, guiding Hindu religious observances. It ç
might have been composed during the period <MS>A.<|>D.<D> 1790-91.
The book is divided into three paricchedas or sections. The topics ç
dealt with in it may be summarised as follows:
divisions of the year, the seasons and the times considered auspicious ç
or inauspicious for religious and social rites; sacraments like upanayana ç
and marriage; <193>hnika or the daily duties of a dvija (a member ç
of the first three castes); ·r<193>ddhas or obsequial rites.
It seems to have derived inspiration from another, better known, work ç
called Nir<207>ayasindhu of Kamal<193>kara (<MS>A.<|>D.<D> 1612).
@NT = dharmaskandha
@N1 = (`branch of dharma')
This is an expression peculiar only to the Ch<193>ndogya Upani<218>ad ç
(2.23.1).
`Skandha' means a division. `Dharma' means a way of life. The three ç
ways of life mentioned are those of the householder, the forest-dweller ç
and the Vedic student.
@SPACE1 = 
The householder keeps and tends the Vedic fires, and, performs sacrifices. ç
He also studies the Vedas to retain the knowledge he has already gained. ç
Giving gifts to the needy is his another duty. He is the first dharmaskandha.
The forest-dweller (as also the mendi-cant) is meant by the word `tapas' ç
or austerity, because he leads an austere life. He is the second dharmaskandha.
The Vedic student entirely devoted to the study of the scriptures ç
and service to the guru is the next, the third dharma-skandha.
According to this Upani<218>ad, all of them (after death) go to pu<207>yalokas ç
or heavenly regions attainable by religious merit.
@NT = Dharmasthala
This is a place of pilgrimage very popular among the people of Karnataka ç
State. It is situated at a distance of 75 kms. (46 miles) to the east ç
of the city of Mangalore, near the west coast. The river Netr<193>vat<200> ç
flows close by.
This place was originally known as Ku<195>uma (or Ko<195>uma). According ç
to the local legends, a pious Jain couple who lived here, were commanded ç
by four dharmadevat<193>s†K<193>lar<193>hu, K<193>larak<193>i, Kum<193>rasv<193>mi   and   Kany<193>kum<193>r<200>†to ç
establish a temple for themselves, which was done. Later on, a <185>iva ç
temple with a li<209>ga was also built. Sometime during <MS>A.<|>D.<D> ç
1513 V<193>dir<193>ja (<MS>A.<|>D.<D> 1480-1600), a great saint of ç
the Sode Ma<219>ha of the M<193>dhva tradition, arrived here. He re- ç
established the li<209>ga at the <185>iva temple with proper rites ç
and named the town as Dharmasthala. The descendants of the original ç
Jain couple, with the surname Hegga<195>e (or Perga<195>e), are the ç
dharma-dar·is  (chief  trustees)  of  the  whole complex.
The temple of <185>iva†now known as Ma<210>jun<193>the·vara†is the ç
central shrine and the chief attraction of the pilgrims. The main ç
doors are covered with silver plates. The four corners have four small ç
kala·as or pinions.
The worship in this main temple is managed by the Vai<218><207>ava ç
br<193>hma<207>as of the M<193>dhva tradition.
The following are the major festivals observed in this temple: Lak<218>ad<200>potsava ç
in the month of K<193>rttika (November); Ga<207>e·acaturth<200>; Mah<193>·ivar<193>tri; ç
D<200>p<193>val<200>; nine-day festival during Me<218>a-sa<209>kr<193>nti ç
(in April) including rathotsava (temple- car- festival) and worship ç
of Divine Mother during Navar<193>tri (October).
There are smaller temples dedicated to the four dharmadevat<193>s ç
and A<207><207>appa (a benevolent spirit).
The huge stone image of B<193>hubali, a great saint of Jainism, is ç
another attraction of this place. It is nearly 12 metres (39 ft.) ç
high and is mounted on a pedestal of 4 metres (11 ft.). It was installed ç
in <MS>A.<|>D.<D> 1982.
The large campus has several guest houses and excellent arrangements ç
to feed the thousands of pilgrims that constantly throng the place.
People of all religions visit this pilgrim centre in large numbers ç
maintaining perfect peace and harmony.
The management is running a large number of educational and public ç
utility institutions spread all over the Karnataka State.
@NT = Dharmas<220>tras
The Dharmas<220>tras are the third aspect or branch of the Kalpas<220>tra ç
literature, the last of the six Ved<193><209>gas (subsidiary sciences ç
of the Vedas). Also known as the S<193>may<193>c<193>rika s<220>tras, ç
they deal mainly with <193>c<193>ra and vyavah<193>ra (code of conduct ç
in personal and social life) as also the var<207><193>·ramadharmas.
Though the G<216>hyas<220>tras and the Dharmas<220>tras are closely ç
connected and the topics are sometimes overlapped, the former confines ç
itself mainly to p<193>kayaj<210>as and sa<221>sk<193>ras (See <MS>VEDIC ç
SACRIFICES<D> and <MS>SA<189>SK°RAS<D>.) whereas the latter, to var<207><193>·ramadharmas.
The following is a list of the Dharma-s<220>tras available now:
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(1.0475,.1250,E1), ç
ABOVE(.0695), BELOW(.0278), VGUTTER(.0417), KEEP(OFF)
@Z_TBL_BODY = TL, TL, TL
<184>gveda, :, V<193>si<218><219>ha Dharmas<220>tras
<185>ukla Yajurveda, :, <185>a<209>kha-Likhita Dharmas<220>tras
K<216><218><207>a Yajurveda, :, °pastamba Dharmas<220>tras<R>ç
Baud<193>yana Dharmas<220>tras<R>ç
H<193>r<200>ta Dharmas<220>tras<R>ç
Hira<207>yake·i Dharmas<220>tras<R>ç
Vaikh<193>nasa Dharmas<220>tras<R>ç
Vi<218><207>u Dharmas<220>tras
S<193>maveda, :, Gautama Dharmas<220>tras
@Z_TBL_END = 
@NID = <+><+><+><+>For more details, see <MS>DHARMA<185>°STRAS<D>.
@NT = Dharmavy<193>dha
Once, a br<193>hma<207>a who was an expert in archery, accidentally ç
killed a sage and was cursed by him to be born as a butcher. He was ç
reborn as the butcher Dharma-vy<193>dha in the city of Mithil<193>. ç
He was deeply devoted to his parents and served them with great fervour.
Kau·ika, a br<193>hma<207>a mendicant, was directed by a devout house-wife ç
to learn the secrets of dharma from Dharmavy<193>dha of Mithil<193>. ç
When Kau·ika approached Dharmavy<193>dha, he was pleased to teach ç
him the utility and the significance of performing one's duties in ç
life, however unpleasant they may appear to oneself or to others. ç
Such Karmayoga, as it is rightly called, leads to purification of ç
one's mind and ultimately, to spiritual enlightenment.
His teachings†which appear in the Vanaparva of the Mah<193>bh<193>rata ç
(chapters 207-216)†deserve the name `Vy<193>dhag<200>t<193>'.
@NT = dharmayuddha
@N1 = (`war [in conformity <R>ç
with the principles] of Dharma')
In spite of the desire of an overwhelming majority of the people of ç
the world to live in peace, wars have existed, from times immemorial. ç
Recognising it as a fact of life and even approving of it in certain ç
circumstances, (as in the case of defending one's territorial integrity ç
or dharma) the great sages of India have evolved, over the years, ç
some general rules to be observed during the course of a battle or ç
a war. A war fought under these rules is a `dharmayuddha'.
The Manusm<216>ti (7.90-94) gives some interesting rules. They are:
1)
@NK = One should not use poisonous arms or deceitful means.
2)
@NK = A  foe  in  a  disadvantageous position must not be struck.
3)
@NK = One who has surrendered must be protected.
4)
@NK = Those who are fleeing, the unarmed one, non-combatants or those ç
fighting with others should not be attacked.
When R<193>va<207>a was worsted in his very first encounter with R<193>ma, ç
R<193>ma let him off to return alive to his place and come back after ç
recouping and replenishing for another round. This is a glorious example ç
of dharmayuddha.
In the Kuruk<218>etra, the battle used to start after sunrise and ç
stop at sunset. In the night the combatants moved freely in one another's ç
camps enquiring about the health and welfare of their enemies or expressing ç
their condolences for the dead! This was a part of the dharma- yuddha ç
tradition.
@SPACE = 
@NT = dh<193>tu
@N1 = (`that which exists [in all]')
This word is used in several senses. In the dar·anas or treatises ç
on philosophy it stands for the pa<210>cabh<220>tas or the five elements, ç
viz., earth, water, fire, air and sky (or space or ether).
In the ancient medical sciences, seven dh<193>tus which sustain our ç
body (`sapta-dh<193>tus') are mentioned. They are: rasa (chyle), as<216>k ç
or rakta (blood), m<193><221>sa (flesh), medas (fat), asthi (bone), ç
majj<193> (marrow) and ·ukra (semen).
Metals dug out from the bowels of earth like gold and silver as also ç
precious stones are also known as `dh<193>tu'.
In Sanskrit grammar, the word means the root form of a verb, like ç
bh<220> (= to exist).
@SPACE = 
@NT = dh<193>tupras<193>da
@N1 = (`by the grace of dh<193>tu')
This is a technical term that appears only in the Ka<219>ha Upani<218>ad ç
(1.2.20).
While describing the nature of the <193>tman (the Self), Yama declares ç
that he is smaller than the smallest as also greater than the greatest. ç
He is established in the cave of the heart of all living beings.
One who realizes him and his greatness becomes free from all sorrow ç
and suffering.
This is preceded by two conditions: to be akratu and to receive dh<193>tupras<193>da.
To become an akratu or free from volition, the aspirant should avoid ç
all desires and desire-motivated actions. Not being agitated thus ç
by desires, his mind and senses which are called dh<193>tu since they ç
support the living beings, become propitious unto him. This is dh<193>tupras<193>da.
However, the Bhakti schools of Ved<193>nta interpret the word `dh<193>tupras<193>d<193>t' ç
as `by the grace of Param<193>tman or God'. So, the j<200>va or the ç
individual soul is able to understand the greatness of God through ç
his grace and thus transcends all sorrow.
This verse is repeated in the <185>vet<193>-·vatara (3.20) and Mah<193>n<193>r<193>ya<207>a ç
(8.3) Upani<218>ads also.
@SPACE = 
@NT = Dhaumya
One of the important sages mentioned in the Mah<193>bh<193>rata ç
is Dhaumya. He was the son of Vy<193>ghrap<193>da and the teacher ç
of another well-known sage (a great devotee of <185>iva) Upamanyu.
Being the royal priest of the P<193><207><195>avas he had to play ç
many roles in their  life.  When  the  P<193><207><195>avas  were ç
banished to the forest he is said to have accompanied them. It is ç
he who taught Yudhi<218><219>hira (the eldest of the P<193><207><195>avas) ç
the rite of pleasing the Sun-god and obtain the divine vessel of food ç
(known as ak<218>ayap<193>tra) from him. He was the chief priest at ç
the marriage of Draupad<200> to the five P<193><207><195>avas and ç
also at the R<193>jas<220>ya sacrifice performed by them at Indra- ç
prastha. When the P<193><207><195>avas lived incognito in the kingdom ç
of Vir<193><219>a, he protected their Vedic fires.
It was again he who performed the coronation ceremony of Yudhi<218><219>hira ç
after his victory in the Kuruk<218>etra war.
@NT = dhauti
@N1 = (`process of cleansing')
According to the Hindu scriptures, mok<218>a or spiritual emancipation ç
is the goal of life. This can be attained through yoga. Yoga may be ç
practised in two stages: Ha<219>hayoga and R<193>jayoga. Ha<219>hayoga ç
prepares the body by cleansing it so that it is free from all ailments ç
where as R<193>jayoga cleanses the mind giving it the power to reveal ç
or realise the Self within.
Dhauti is one of the well-known <218>a<219>karmas or six purificatory ç
processes in Ha<219>hayoga and is of four kinds.
See <MS>ANTARDHAUTI<D> for details. See also <MS><186>A<187>KARMAS.<D>
@NT = dhenumudr<193>
@N1 = (`hand-pose [resembling <R>ç
the udder of] a cow')
Mudr<193>s are poses of fingers or hands exhibited in ritualistic ç
acts, especially during the worship of a deity. They are so called ç
because they are supposed to give (= r<193>) joy (= mud) to the deities ç
who are being worshipped.
The dhenumudr<193> is a pose of the fingers of both the hands, in ç
the form of the udder of a cow, and is used during the offering of ç
food to the deity. It is formed by crossing the fingers of the two ç
hands in such a way that the tip of the little finger of one hand ç
touches the tip of the ring finger of the other, and, the tip of forefinger ç
of one hand with that of the middle finger of the other.
This mudr<193> is also called `am<216>t<200>-kara<207>amudr<193>'.
See also <MS>MUDR°S.<D>
@NT = Dh<216><218><219>adyumna
@N1 = (`the  proud  and  the radiant  one')
When Drupada, the king of P<193><210>c<193>la wanted a valiant son ç
who could kill Dro<207><193>c<193>rya, his enemy, he performed a special ç
sacrifice. Dh<216><218><219>adyumna was then born, as an adult son, ç
from the sacrificial fire. Draupad<200> too (wife of the P<193><207><195>ava ç
heroes), was born out of the same fire, after him.
He was a great hero and a good ruler. It was he who conducted the ç
svaya<221>vara† the rite of a princess of marriageable age choosing ç
her husband from among the assembled princes†of his sister Draupad<200> ç
where Arjuna succeeded in the contest and won her.
Since Arjuna and the other P<193><207><195>avas were disguised as ç
br<193>hma<207>as, Dh<216><218><219>a-dyumna secretly went to their ç
dwelling place and discovered their true identity.
During the Kuruk<218>etra war, he was made the commander-in-chief ç
of the P<193><207><195>ava army. He successfully fought with many ç
heroes of the enemy's army, like Dro<207>a, A·vatth<193>ma and Duryodhana. ç
He beheaded Dro<207>a who had retired from the battle as per the sages' ç
advice. They had come to dissuade him from using the Brahm<193>stra.
Dh<216><218><219>adyumna was ultimately killed in sleep by A·vatth<193>ma.
@NT = Dh<216>tar<193><218><219>ra
@N1 = (`One by whom the nation is supported')
@SPACE = 
@SPACE = 
If Dh<216>tar<193><218><219>ra had not been born, the world would ç
have suffered an irreparable loss; because, there would then have ç
been no Mah<193>bh<193>rata and hence no Bhagavadg<200>t<193> ç
either! Born blind, he was impervious to the sage advice of great ç
sages and savants, including his bestwell-wishers. His infatuation ç
for his arrogant son Duryodhana was matched only by his hatred of ç
the virtuous P<193><207><195>avas. He was the very anti-thesis of ç
what his name signifies.
He was the levirate-son of Vicitra-v<200>rya in Ambik<193> by Vy<193>sa. ç
Since he was sightless, he could not be made the king of Hastin<193>pura. ç
His younger brother P<193><207><195>u was hence crowned as the king.
He had married the eleven daughters of Subala, the king of G<193>ndh<193>ra, ç
of whom G<193>ndh<193>r<200> was the eldest and the chief queen.
When P<193><207><195>u died prematurely and his children†the five ç
P<193><207><195>avas†were still young, Dh<216>tar<193><218><219>ra ç
took the reins of the kingdom and arranged for the proper maintenance ç
and education of the P<193><207><195>avas also along with that of ç
his hundred sons.
When Yudhi<218><219>hira, the eldest of the P<193><207><195>avas was ç
of proper age he was crowned as the yuvar<193>ja (the crown-prince). ç
Very soon, he became extremely popular with the subjects.
Egged on by Duryodhana, the jealousy-incarnate, Dh<216>tar<193><218><219>ra ç
sent the P<193><207><195>avas to V<193>ra<207><193>vata for a `change,' ç
where the former had plotted to kill them by arson. Due to the timely ç
help of Vidura,the virtuous minister, the P<193><207><195>avas escaped. ç
Later on, they went to Vir<193><219>anagar<200>, participated in the ç
svaya<221>vara of the princess Draupad<200> and succeeded in marrying ç
her.
Dh<216>tar<193><218><219>ra, on the advice of the grandsire Bh<200><218>ma ç
and others, called them back and gave them half the kingdom. The P<193><207><195>avas ç
started ruling it from their newly built capital Indraprastha. Their ç
prosperity and popularity roused the jealousy of Duryodhana further, ç
who managed to banish them to the forest by the well-planned stratagem ç
of a game of dice exerting pressure on them through his father.
When the P<193><207><195>avas had fulfilled all their commitments ç
and sent <185>r<200> K<216><218><207>a as their emissary of peace, ç
requesting for their share of kingdom or at least some means of maintenance, ç
Dh<216>tar<193><218><219>ra pleaded his helplessness, unable to control ç
or influence his son Duryodhana.
On the one hand, he was afraid of the impending war. On the other, ç
he was hoping against hope that his sons would come out victorious!
After the war when all his sons andtheir comrades had been decimated, ç
his  anger,  especially  against  Bh<200>ma, manifested  itself  in  a  surreptitious ç
attempt to crush him. However, <185>r<200> K<216><218><207>a's forethought ç
saved Bh<200>ma from thetragedy.
Though he was looked after well, by the king Yudhi<218><219>hira, ç
problems of old age, repentance about past actions and the advice ç
of the saintly Vidura induced him to take to the life of a V<193>naprastha. ç
He later perished in a forest fire.
@SPACE1 = 
See also <MS>MAH°BH°RATA.
