@NT = Dhruva
@N1 = (`the steady one')
@SPACE = 
@SPACE = 
Along with Prahl<193>da, Dhruva too has carved out for himself a permanent ç
place in the annals of child-devotees in our pur<193><207>as.
Dhruva was the elder son of the king Utt<193>nap<193>da from his first ç
wife Sun<200>ti. Enamoured of Suruci, his second wife, the king had ç
completely neglected Sun<200>ti and her son Dhruva.
Once, snubbed by his step-mother Suruci in the presence of his father, ç
Dhruva   became   despondent   and approached his mother for solace. ç
She advised him to pray to Lord Vi<218><207>u by performing austerities.
When he was going to the forest, the sage N<193>rada met him and instructed ç
him in meditation. After a severe penance, Dhruva had a vision of ç
Lord Vi<218><207>u who gave him the boon of the kingdom. He also bestowed ç
on him a long, happy life here and a permanent abode in the heavenly ç
regions after death. That is now known as `Dhruvanak<218>atra' (pole-star).
Once, Uttama, younger brother of Dhruva, went to the Him<193>layas ç
on a hunting expedition but was killed in an encounter with the yak<218>as ç
(a kind of demigods) who were the followers of Kubera. Enraged by ç
this, Dhruva attacked them, killing them in large numbers. Kubera ç
was forced to fight with Dhruva when Sv<193>yambhuva Manu (the forefather ç
of Dhruva) appeared on the scene and stopped the fight. Then the two ç
became friends.
Dhruva ruled his kingdom according to the highest principles of dharma ç
for many years.
@NT = dhurvabera
@N1 = (`immovable image')
See <MS>BERA<D> for details.
@SPACE = 
@NT = dh<220>pa
@N1 = (`the [smoke] which destroys<R>ç
[diseases]')
P<220>j<193> or ritualistic worship is an important aspect of Hindu ç
religion. The central part of it is the offering of upac<193>ras. ç
The upac<193>ras are various articles ceremonially offered to the ç
deity with appropriate mantras.
These upac<193>ras can be 5 or 10 or 16or even 64. One of the upac<193>ras ç
common to all these is the `dh<220>pa.' It consists in lighting some ç
incense sticks and waving them before the deity along with the ringing ç
of the bell.
Instead of the incense sticks, one can also wave lighted embers in ç
which fragrant powders like loban have been put and cented smoke is ç
being emitted.
The method of smoke being used for curing certain diseases or for ç
removing pollution from the atmosphere seems to be an ancient one, ç
recommended in the textbooks of °yurveda. The term `dh<220>pa' might  have  been  derived  from  this ç
practice.
@SPACE = 
@NT = dhvaja
@N1 = (`that [which] stands tall;' a flag fixed on a post.)
A flag or a banner called `dhvaja' fixed on a post is a common feature ç
in Hindu temples. The post is called `dhvaja-stambha' and the flag ç
itself is a metallic plate, either of copper or of brass. It contains ç
the figure of the v<193>hana (carrier mount) of the main deity in ç
the temple. For instance, if it is a temple of <185>iva, the figure ç
on the banner will be that of a bull (Nandi). If of Dev<200>, it will ç
be a lion. If of Vi<218><207>u, it will be Garu<195>a (eagle-mount).
The dhvajas or flags made of cloth are hoisted in temples temporarily ç
on special occasions like brahmotsava and rathotsava. (See <MS>BRAHMOTSAVA<D> ç
and <MS>RATHOTSAVA.<D>)
The  sa<221>ny<193>sins  of  some  Hindu religious orders also carry ç
a dhvaja on their staffs.
@SPACE = 
@NT = Dhvaja-Ga<207>apati
@N1 = (`Ga<207>apati with a<R>ç
banner')
@SPACE = 
Ga<207>apati or Ga<207>e·a is an extremely popular deity of the Hindus ç
and is worshiped at the start of all ventures, sacred or secular. ç
Out of the 32 forms described in the iconographical works, `Dhvaja-Ga<207>apati' ç
(also called `Dvija-Ga<207>apati') is one. He is depicted as a fierce ç
deity of the colour of full-moon, with four heads and four hands. ç
In these four hands he is carrying a book, a rosary, a water pot and ç
a flagstaff (da<207><195>a with dhvaja). The name is probably derived ç
from the last item.
@SPACE = 
@NT = dhvajastambha
@N1 = (`flagpost')
@SPACE = 
One of the essential parts of a traditional Hindu temple is the dhvaja-stambha ç
or the flagpost. The actual temple, in the ritualistic sense extends ç
from thegarbhamandira (sanctum) up to the dhvajastambha.
Since a temple is considered as the `palace' of God, the emperor of ç
emperors, it must have a flagpost in front of it, in a prominent place. ç
The l<193><210>chana or insignia, made of copper or brass and fixed ç
like a flag to the top of the post, varies according to the deity ç
in the temple. The figure on the l<193><210>chana is invariably that ç
of the v<193>hana (the mount) of the deity. For instance, in <185>iva ç
temples it contains Nandi; in Dev<200> temples, the lion; in Vi<218><207>u ç
temples, Garu<195>a and so on.
@SPACE = 
@NT = dhva<221>s<193>bh<193>va
@N1 = (`non-existence after<R>ç
destruction')
@SPACE = 
This is the same as pradhva<221>s<193>-bh<193>va. See <MS>ABH°VA<D> ç
for details.
@SPACE = 
@NT = dhvani
@N1 = (`sound')
@SPACE = 
The word `dhvani' means `sound'. It may be buddhihetuka (caused by ç
the intellect) or abuddhihetuka (not caused by the intellect). The ç
sound of thunder is an example for the latter.
Buddhihetuka sounds, again, can be sv<193>bh<193>vika (natural), like ç
the sound of weeping or laughter. Or, it can be k<193>lpanika (produced ç
by imagination) like speaking or music.
In the Ala<209>k<193>ra·<193>stra (the science of figure of speech) ç
`dhvani' means suggested meaning, such usage being generally found ç
in poetical works. Going into intricate details, the works on ala<209>k<193>ra ç
list as many as 5355 varieties of dhvani!
See also <MS>SPHO<187>AV°DA.
@SPACE = 
@NT = dhy<193>na
@N1 = (`[continuous] thinking.'<R>ç
`meditation')
@SPACE = 
A stable and concentrated mind is a great asset in life. In spiritual ç
life, it is a must.
The art and science of concentration has been systematically described ç
in the works on yoga. The Yogas<220>tras of Pata<210>jali (200 <MS>B.<|>C.<D>) ç
is the most standard treatise on this subject.
Pata<210>jali describes eight steps to theattainment of yoga, of ç
which dhy<193>nahappens to be the seventh or the penultimate step.
In dh<193>ra<207><193> (fixing the mind on the object of meditation), ç
the step prior to dhy<193>na, the concentration is not continuous. ç
Moments of concentration are interspersed with moments of distraction. ç
But in dhy<193>na, it is continuous. Each succeeding wave of the mind ç
is absolutely identical with the preceding wave. Say, for instance, ç
if a person is concentrating on the form of a deity like Ga<207>apati, ç
everyone of the mental waves carries the same impression or image ç
of that deity. The mind is then flowing in an unbroken continuous ç
stream like the oil that is being poured from one vessel into another.
Dhy<193>na practised over a long period leads to sam<193>dhi (absolute ç
concentration resulting in mystical experience).
@NT = Dhy<193>nabind<220>pani<218>ad
@SPACE = 
@SPACE = 
This is one of the minor Upani<218>ads belonging to the K<216><218><207>a ç
Yajurveda and classed among the Yoga-Upani<218>ads or Upani<218>ads ç
dealing with the several yogic practices. It is in the anu<218><219>ubh ç
metre the number of verses being 106.
The Upani<218>ad starts with an eulogy of yoga. Then comes a description ç
of Brahman as extremely subtle and also asall-pervading. This is ç
followed by a picturesque depiction of pra<207>ava or Om, and meditation ç
on it.
Meditationon V<193>sudeva (who is Brahman with attributes) in the ç
lotus of the heart as also its fruit is given next.
Then, the yoga of six steps (<218>a<195>a<209>ga-yoga) comprising ç
<193>sana (posture), pr<193><207><193>-y<193>ma (breath-control), ç
praty<193>h<193>ra (with- drawal of mind from sense-objects), dh<193>ra<207><193> ç
(fixing the mind on the object of meditation), dhy<193>na (meditation) ç
and sam<193>dhi (superconscious experience) is described.
A delineation of the cakras like m<220>l<193>- dh<193>ra and the ku<207><195>alin<200> ç
power follows next. The five major pr<193><207>as like pr<193><207>a ç
and ap<193>na, as also the five minor ones like n<193>ga and k<220>rma ç
are also described.
The technique of ajap<193>japa of the Ha<221>samantra (ha<221> = I, ç
sa<199> = [am] He) is also given.
Rousing of the ku<207><195>alin<200> power is described next.
Some of the practices expounded in Ha<219>hayoga, like mudr<193>s ç
and bandhas, also find a place here.
The Upani<218>ad ends with a description of <193>tmadar·ana or realisation ç
of the <193>tman.
@NT = Dhy<193>nayoga
@N1 = (`union [with God through] meditation')
@EMERGENCY = Dhy<193>nayoga is the technique of meditation. The <216><218>is ç
who could not arrive at a satisfactory or convincing answer to theirqueries ç
regarding the ultimate cause of the world, are said to have taken ç
recourse to Dhy<193>nayoga to realise it (vide<185>vet<193>·vatara ç
Upani<218>ad 1.3). In the Bhagavadg<200>t<193>, the sixth chapter ç
has been christened Dhy<193>nayoga.
@EMERGENCY = The word `dhy<193>nayoga' may mean the union (yoga = ç
union) of the j<200>v<193>tman (the individual soul) with Param<193>tman ç
(God) through dhy<193>na or meditation. Or, it can be interpreted ç
as dhy<193>na or meditation resulting ultimately in yoga or sam<193>dhi ç
(perfect concentration) on God.
The Dhy<193>nayoga of the Bhagavadg<200>t<193> has the following ç
steps:
The yogi should select a clean and lonely place for his practice of ç
meditation. He should then prepare his seat by spreading the ku·a ç
grass, covering it with a deer skin and then with a cloth. He should ç
sit on it, keeping the chest, the neck and the head erect. He must ç
start the process of concentration by directing his sight towards ç
the tip of his nose. He can then meditate on God, by withdrawing the ç
mind from all other things.
The yogi should incorporate into his life the following disciplines: ç
fearlessness, continence, faith in God, moderation in eating and sleeping, ç
and desirelessness.
@EMERGENCY = Such a yoga, when practised steadily, will result in ç
great happiness. The yogi will then be able to see all beings in himself ç
and himself in all.
Though this yoga is difficult to practise, due to the fickleness of ç
the mind,it can be achieved by abhy<193>sa (repeated efforts) and ç
vair<193>gya (spirit of renunciation).
If by chance, the yogi dies before attaining its fulfilment, he will ç
be reborn in a family with a congenial atmosphere for continuing the ç
practice.
@NT = digbandhana
@N1 = (`shutting out [the evil <R>ç
spirits]')
In ritualistic worship as also in any ritualistic act, especially ç
those aimed at fulfilment of desires, there is always a possibility ç
of obstacles being created by inimical spirits. These spirits have ç
to be `locked out' of dik (= quarters) during the ritual. The way ç
of doing it is by chanting certain powerful mantras or mystical formulae ç
like the vy<193>h<216>tis of the G<193>yatr<200> or syllables like ç
pha<219>. This is called `digbandhana' or `digbandha'. After the ritual ç
is over, the quarters (or dik) have to be reopened. This is called ç
`digvimoka'.
The process may also be used to arrest the movements of those who ç
are likely to harm a person, like criminals. Such use of extraordinary ç
powers has beenrecorded in the lives of great saints like Taila<209>ga ç
Sv<193>min (19th century) and Vijayad<193>sa (<MS>A.D.<D> 1682-1755).
@NT = diggajas
@N1 = (`the elephants [that are<R>ç
supporting the] directions')
As  per  the  Hindu  mythological accounts, this earth is being carried ç
by eight elephants situated in the eight directions. Hence they are ç
called `a<218><219>a- diggajas' or simply as `diggajas'. Each of the ç
diks or directions has a protector or dikp<193>la (or dikp<193>laka) ç
also and these elephants are under them.
Their names can be listed as follows:
@Z_TBL_BEG = COLUMNS(4), DIMENSION(IN), COLWIDTHS(E1,.7008,.0975,.9217), ç
BELOW(.0833), VGUTTER(.0278), KEEP(OFF)
@Z_TBL_BODY = SB8.5, SB8.5, TABLE TEXT, SB8.5
dik<|>or<|>direction, dikp<193>la, , diggaja
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE TEXT
p<220>rva<R>ç
(east), Indra, , Air<193>vata
<193>gneya<R>ç
(south-east), Agni, , Pu<207><195>ar<200>ka
dak<218>i<207>a<R>ç
(south), Yama, , V<193>mana
nair<216>tya<R>ç
(south-west), S<220>rya, , Kumuda
pa·cima<R>ç
(west), Varu<207>a, , A<210>jana
v<193>yavya<R>ç
(north-west), V<193>yu, , Pu<218>padanta
uttara<R>ç
(north), Kubera, , S<193>rvabhauma
<200>·<193>nya<R>ç
(north-east), ®·<193>na<R>ç
or Candra, , Suprat<200>ka
@Z_TBL_END = 
These elephants have their female consorts too like Abhramu, Kapil<193>, ç
Pi<209>gal<193> and so on.
The R<193>m<193>ya<207>a (1.40) mentions only four diggajas. They ç
are: Vir<220>p<193>k<218>a (east), Mah<193>padma (south), Suman<193> ç
(west) and Bhadra (north).
@NT = digvijaya
@N1 = (`conquering [in all] directions')
Expeditions by ambitious kings for conquering  others'  territories  or  for ç
collecting ransoms from them have been known to exist right from the ç
most ancient times. Such expeditions were called `dig-vijaya'.
Kau<219>ilya's Artha·<193>stra (12.1) classifies such digvijayas ç
into three kinds:†
@SPACE1 = 
@SPACE1 = 
(1) dharmavijaya: Here the conqueror is satisfied if the defeated ç
ruler agrees to be submissive.
(2) lobhavijaya: The conqueror is satisfied if he gets land and money.
(3) asuravijaya: This is the lowest and abominable type since the ç
conqueror robs the vanquished king of all his possessions.
The dharma·<193>stra works condemn the last one.
@NT = dikp<193>lakas
@N1 = (`protectors of the quarters')
In the Hindu scheme of creation, as depicted in the pur<193><207>as, ç
the eight quarters or directions (= dik) have been put under the protection ç
of eight deities. They are known as `dikp<193>lakas' or `a<218><219>adikp<193>lakas'. ç
They are:
@IN2 = Indra for p<220>rva or east<R>ç
Yama for dak<218>i<207>a or south<R>ç
Varu<207>a for pa·cima or west<R>ç
and Kubera for uttara or north.
@SPACE = 
The intermediate directions are taken care of by:
@IN2 = Agni for south-east<R>ç
S<220>rya for south-west<R>ç
V<193>yu for north-west<R>ç
and ®·<193>na for north-east.
These deities are rarely worshipped. They are mostly represented on ç
the central panel of the ceiling in the chief pavilion (mah<193>ma<207><195>apa) ç
of a temple.
@NT = d<200>k<218><193>
@N1 = (`observing a vow')
Derived from the root `d<200>k<218>' (`to destroy ignorance by giving ç
knowledge and wisdom') the word d<200>k<218><193> has several meanings ç
such as observing certain rules for a period of time, a rite to be ç
performed at the beginning of a holy venture, like a  Vedic  sacrifice,  the  sacrament  of ç
upanayana, receiving a mantra (sacred formula) from a qualified guru ç
and shaving the head as a part of a religious vow.
D<200>k<218><193> is a must in all ritualistic acts.
Consecration of the sacrificer at the beginning of a Somay<193>ga ç
is also called `d<200>k<218><193>'. It takes place after some preliminaries ç
like an i<218><219>i and <193>huti (offering a ladleful of ghee into ç
the fire). The sacrificer has to wear a particular garment, a girdle ç
of mu<210>ja grass and a piece of cloth as head-dress. He should also ç
keep a da<207><195>a as staff. His wife should wear a yoktra (a belt ç
of mu<210>ja grass). They are expected to follow certain rules during ç
the period of the sacrifice.
Imparting a mantra to a worthy disciple is called `d<200>k<218><193>' ç
in the t<193>ntrik works. It is of several varieties. The guru can ç
rouse the spiritual potential of the disciple by just a look or a ç
touch. (See <MS>TANTRAS<D> for details.)
@NT = D<200>k<218>a<207><200>y<193>
Vedic sacrifices (yaj<210><193>s and y<193>gas) were very common in ç
India during the ancient days. We find them mentioned not only in ç
the Vedic and allied literature but also in the epics and the pur<193><207>as.
Somay<193>ga is an important variety of such y<193>gas. Before a Somay<193>ga ç
is started the D<200>k<218>a<207><200>y<193>, a minor rite of the ç
i<218><219>i type (See <MS>I<186><187>I<D> for details.) has to be ç
performed. The main part of it is the offering of puro<195><193>·a ç
on eleven kap<193>las (pot-sherds) to Agni and Vi<218><207>u.
@NT = Dil<200>pa
@SPACE1 = 
Dil<200>pa was a great king of the S<220>ryava<221>·a (the royal race ç
which traced its origin from S<220>rya or the Sun-god) and the father ç
of Raghu who became even more renowned than his father. In fact, the ç
race itself came to be known as `Raghuva<221>·a' after him.
Dil<200>pa had no children. As per the directions of his (royal) preceptor ç
Vasi<218><219>ha, he faithfully served his cow Nandin<200> (an offspring ç
of the famous K<193>madhenu, the celestial cow) who tested him by ç
creating a critical situation. Dil<200>pa came out victorious and ç
was then blessed by the divine cow. As a result, he got a valiant ç
son whom he named `Raghu'.
Dil<200>pa was also known as Kha<219>v<193><209>ga. He was once requested ç
by the gods in heaven to help them in their fight against the demons. ç
With his valiant assistance they attained victory. When they offered ç
him a boon, he just asked them to know how much of his life was still ç
left. On getting the reply `one muh<220>rta' (about 48 minutes) he ç
immediately sat in meditation, concentrated his mind on Lord Vi<218><207>u ç
and gave up the body, thus attaining mukti or liberation.
@SPACE = 
@NT = D<200>pakalik<193>
@SPACE = 
The religious works that regulated the conduct of the Hindus during ç
the ancient and the medieval period, both at the personal and at the ç
social level, are known as the dharma·<193>stras. If the g<216>hyas<220>tras ç
and the dharmas<220>tras form the first stratum, the sm<216>tis form ç
the second. Among the sm<216>tis, the Y<193>j<210>avalkya Sm<216>ti ç
is considered only next in importance to the Manusm<216>ti.
@SPACE1 = 
These sm<216>tis needed explanations, amplifications and clarifications ç
of doubts as the society grew more complicated. The commentaries written ç
by later scholars well-versed in this field, supplied the much-needed ç
material for this.
The D<200>pakalik<193> is such a commentary on the Y<193>j<210>avalkya ç
Sm<216>ti written by <185><220>lap<193><207>i (<MS>A.<|>D.<D> 1365-1445). ç
It is a brief work but quoted as an authority by well-known later ç
writers like Raghunandana. His views have been considered as rather ç
archaic.
@SPACE = 
@NT = d<200>pana
@N1 = (`lighting up')
@SPACE = 
In rituals as also in spiritual practices, mantras play a very important ç
part. These mantras have to be received in d<200>k<218><193> or spiritual ç
initiation from a competent guru or teacher.
The special class of works known as the tantras declare that a mantra ç
has to be subjected to a purificatory process if is to be effective. ç
This process called `mantra-sa<221>sk<193>ra' is of ten types, of ç
which `d<200>pana' or `d<200>pan<200>' is also one. According to one ç
view, the b<200>jamantra or seed-letter has to be repeated seven times ç
with the pra<207>ava (O<221>) preceding and following it. This is ç
`d<200>pana' for that mantra. For instance, `Ga<221>' is the b<200>jamantra ç
for Ga<207>apati. In d<200>pana, `O<221> gam O<221>' has to be repeated ç
seven times.
According to another view the d<200>pana has to be done with the formula ç
`O<221> hr<200><221> ·r<200><221>.' The details have to be learnt ç
from the guru.
@SPACE = 
@NT = d<200>pastambha
@N1 = (`the lamp-post')
@SPACE = 
One of the constituents of a temple complex is the d<200>pastambha ç
or the lamp-post. It is situated either in front of the balip<200><219>ha ç
(pedestal of sacrificial offerings) or outside the main gate. The ç
top of this post has a bud-shaped chamber to receive the lamp.
During the days when electricity was unknown, a lamp-post served to ç
give some general light in the area to allow free movement.
@SPACE = 
@NT = D<200>p<193>val<200>
@N1 = (`row of lighted lamps')
@SPACE = 
Being a festival of lights, decorative illuminations and fireworks, ç
<$IDipavali>D<200>p<193>val<200> or <$IDivali>Div<193>l<200> is perhaps ç
the most popular of all the <$IHindu/s>Hindu festivals, bringing joy ç
to the young and old alike. It is celebrated very widely throughout ç
India and among the <$IHindu/s>Hindus settled abroad.
It is very difficult to trace its origin and development. According ç
to some scholars it was already a well-known festival by the time ç
of the <$IBhavisyottara>Bhavi<218>yottara <$IPurana>Pur<193><207>a ç
said to be composed before <MS>A.<|>D.<D> 1000.
In some works it has been called as <$IKaumudi>`Kaumud<200> <$IUtsava>Utsava,' ç
`a festival in which people find delight on this earth among themselves'.
<$IDipavali>D<200>p<193>val<200> proper is of three days' duration; ç
and with the addition of <$IDvitiya>dvit<200>y<193>, it is spread ç
over four days. It normally falls during the last part of October ç
and the early part of November. The first day, <$IAsvayuja>°·vayuja ç
k<216><218><207>a <$ICaturdasi>caturda·<200>, is called <$INarakacaturdasi>`Narakacaturda·<200>'. ç
Originally, the celebration of this day may have been aimed at escaping ç
from <$INaraka>naraka or hell, by propitiating <$IYama>Yama, the <$IGod>god ç
of death and hell. But later, it seems to have been associated with ç
<$IKrsna>K<216><218><207>a's killing of the demon <$INarakasura>Narak<193>sura, ç
the king of <$IPragjyotisapura>Pr<193>gjyoti<218>apura (modern Assam). ç
On this day one is advised to take an oil-bath at dawn, pray for the ç
destruction of one's sins, offer <$ITarpana>tarpa<207>a (satiation ç
with handful of water mixed with <$ISesame>sesame) to <$IYama>Yama ç
and light a lamp to <$INaraka>Naraka. After a sumptuous feast with ç
fourteen kinds of vegetables (since the festival starts from the 14th ç
day), rows of lamps should be lighted in the evening illuminating ç
all parts of one's house. <$ITemple>Temples and public places too ç
should be illuminated in the same way. Some religious texts suggest ç
that the day should be spent in fasting and that food can be taken ç
only at night.
@SPACE1 = 
The next day, <$IAmavasya>am<193>v<193>sy<193>, is said to be the ç
darkest day of the year. Oil-bath, worship of <$ILaksmi>Lak<218>m<200>, ç
the <$IGoddess>goddess of wealth and prosperity, offerings to the ç
<$IPitrs>pit<216>s or departed manes, feeding of <$IBrahmana>br<193>hma<207>as ç
and fasting by day are the main items of the rite on this day. Lighting ç
of lamps and general illumination should continue as on the previous ç
day. Since this is a day specially dedicated to <$ILaksmi>Lak<218>m<200> ç
and since there is every chance of <$IAlaksmi>Alak<218>m<200> (the ç
inauspicious <$IGoddess>goddess, the opposite of <$ILaksmi>Lak<218>m<200>) ç
peeping in to ruin one's prosperity, women of the town or village ç
are asked to create a terrible noise by beating drums and winnowing ç
baskets around midnight<|>!
In Bengal, <$IKali>K<193>l<200> is worshipped on this day in clay ç
image, instead of <$ILaksmi>Lak<218>m<200>, throughout the night. ç
Hence this <$IAmavasya>day is named <$IKalipuja>K<193>l<200>p<220>j<193> ç
day or festival.
In other parts of India, this is traders' day. They adore <$ILaksmi>Lak<218>m<200>, ç
worship their account books, open the new account books, invite friends, ç
customers and other traders and give them <$ITambula>t<193>mb<220>la ç
(betel leaf with betel nuts) and sweets.
Next day†<$IKartika>K<193>rtt<200>ka ·ukla <$IPratipad>pratipad† is ç
known as `<$IBalipratipada>Balipratipad<193>' or `<$IBalipadyami>Bali-p<193><195>yam<200>'. ç
It is one of the 3<P7W1><|><$E1 over 2> <P255D>days considered as most ç
auspicious in the <$IHindu/s>Hindu <$IAlmanac>almanacs. Though there ç
is unanimity in assigning great auspiciousness to C<193>ndram<193>na ç
<$IYugadi>Yug<193>di and <$IVijayadasami>Vijayada·am<200>, there are ç
differences of opinion regarding the third. Some give that privilege ç
to <$IBalipratipada>Balipratipad<193> while others do so to Ak<218>ayyat<216>t<200>y<193>. ç
The left over day becomes the <P7W1><$E 1 over 2 ><|><P255D>!
@SPACE1 = 
Worship of <$IBali>Bali (the powerful king of the asuras who was vanquished ç
and pushed into the <$IPatala>p<193>t<193>la or the nether world by ç
<$IVisnu>Vi<218><207>u as the <$IIncarnation>incarnation <$IVamana>V<193>mana) ç
at night, especially by the king, is the most important rite of this ç
day. One should also keep awake thewhole night spending the time ç
in seeing religious dramas. Gifts made on this day bring inexhaustible ç
fruits.
On all the three or four days of the <$IDipavali>D<200>p<193>val<200> ç
festival, the skies are rent asunder by the terrific sounds of bursting ç
crackers. This bursting of crackers seems to be a universal practice ç
all over the country. It may signify not only the expression of one's ç
joy but also the destruction of evil personified by demons like Narak<193>sura.
<$IBalipratipada>Balipratipad<193> is also called <$IDyutapratipada>`Dy<220>ta- ç
pratipad<193>'. <$IDyuta>`Dy<220>ta' means gambling. There is a curious ç
(or queer?) direction in the <$IBrahmapurana>Brahmapur<193><207>a, ç
issued to those observing this day, to gamble! It seems that on this ç
day <$IParvati>P<193>rvat<200> defeated <$ISankara><185>a<209>kara ç
in a game of dice and that she became very happy whereas <$ISankara><185>a<209>kara ç
was distraught with sorrow. (This scene has been shown in the <$IEllora>Ellora ç
cave no. 21.) Hence those that win in the gambling on this day will ç
be happy throughout the year, the opposite being the case of those ç
that lose! This temptation naturally makes people†even today†to gamble ç
recklessly.* May be that the writers of these <$IPurana>pur<193><207>as ç
wanted the flock not to gamble for the rest of the year! This is ç
perhaps better than our modern contrivances like `Courtesy Week' wherein ç
people think that they need not be courteous for the remaining part ç
of the year!
Some more observances prescribed during the celebration of the <$IBalipratipada>Balipratipad<193> ç
may now be given. They are: worship of cows and bulls, worship of ç
the <$IGovardhana>Govardhana hill, tying of <$IMagrapali>M<193>rgap<193>l<200> ç
and <$IArati><193>rati to menfolk by the womenfolk of the family.
Cows and bulls should be decorated, worshipped and fed well. Cows ç
must not be milked that day and bulls must not be made to work. Obviously ç
this is a way of expressing one's gratitude to those animals which ç
do so much for us.
Next is the worship of the <$IGovardhana>Govar-dhana hill. The `hill' ç
is prepared either out of cow-dung or out of <$IAnna>anna (cooked ç
rice) and other cooked food. This latter, as also its worship, is ç
called `<$IAnnakuta>Annak<220><219>a'. An image or a picture of <$IBalagopala>B<193>lagop<193>la ç
(boy <$IKrsna>K<216><218><207>a) is also kept with it and worship ç
is offered with 16 <$IUpacaras>upac<193>ras. The <$IMantra>mantras ç
used expressly refer to the protection that <$IBalakrsna>B<193>lak<216><218><207>a ç
gave to the people by lifting up the <$IGovardhana>Govardhana hill ç
and sheltering them beneath it.
<$IMagrapali>M<193>rgap<193>l<200> (`protectress of the road') is ç
a rope of <$IKusa>ku·a grass and is tied to a pole on one side and ç
a tree on the other, in the afternoon. All people including the king ç
and the <$IBrahmana>br<193>hma<207>as bow down before it and pass ç
under it. It is perhaps the `<$IGoddess>goddess of the road,' whose ç
grace is needed to keep the town safe and also for safety during journeys. ç
This is then followed by a tug of war between the men of the royal ç
families and the common folk. If the common folk win, it is said to ç
be good for the king and the country. Obviously, this is a symbolic ç
way of expressing the simple truth that the ruler can be successful ç
and the country well-ruled only when the people have a say in the ç
affairs of the State.
Next comes the festival of <$IYamadvitiya>Yama-dvit<200>y<193> or ç
<$IBhratrdvitiya>Bhr<193>t<216>dvit<200>y<193> (<$IKartika>K<193>rtt<200>ka ç
·ukla <$IDvitiya>dvit<200>y<193>). According to an ancient legend, ç
<$IYama>Yama, the <$IGod>god of death and hell, and the river <$IGoddess>goddess ç
<$IYamuna>Yamun<193>, were brother and sister. On this day of <$IKartika>K<193>rtt<200>ka ç
·ukla <$IDvitiya>dvit<200>y<193>, <$IGoddess>goddess <$IYamuna>Yamun<193> ç
is said to have invited her brother <$IYama>Yama to her house for ç
dinner and honoured him. Hence, this day has become a day of reunion ç
of brothers and sisters. Brothers are invited by the sisters to their ç
houses and sumptuously fed. The former give presents to the latter. ç
Since there is separation of the sisters after their marriage, from ç
their parents and brothers, and may live in far off places or may ç
not meet for a long time, this festival provides for a much-needed ç
opportunity for a get-together.
Sometimes, the sisters worship <$IGod>god <$IYama>Yama and pray to ç
him for the longevity of their brothers. People living on the banks ç
of the <$IYamuna>Yamun<193> river, do not miss taking bath in the ç
river on this day. In some places there is a <$IMela>mel<193> (fair) ç
on the banks of the river.
See also <MS>BALIPRATIPAD°<D> and <MS>BHR°T<184>-DVIT®Y°.<D>
@SPACE = 
@NT = D<200>rghatamas
@N1 = (`[One who was in]<R>ç
darkness for a long time')
The Vedas are considered as the basic scriptures of Hinduism. The ç
<184>gveda, the oldest literature of the world, comprises a large ç
number of hymns which were revealed to a galaxy of sages called <216><218>is. ç
A <216><218>i is a person of knowledge and wisdom based on intuitive ç
experience.
D<200>rghatamas is one such <216><218>i to whom a number of <184>gvedic ç
s<220>ktas or hymns are attributed. The s<220>ktas are: 1.140 to 164. ç
Since he was born blind he was named `D<200>rghatamas'. However he ç
regained his sight by pleasing Agni through his hymns.
@SPACE = 
@NT = Diti
@N1 = (`the limited')
@SPACE = 
In the Vedas as also the mythological lore devas and d<193>navas (or ç
daityas), arealways pictured as being in eternal conflict.
Diti and Aditi are two of the daughters of Dak<218>a Praj<193>pati ç
(lord of beings) married to the sage Ka·yapa. Daityas are the sons ç
of Diti and <193>diteyas or <193>dityas or devas are the sons of Aditi.
Once Diti requested her husband Ka·yapa to bless her with a son who ç
could vanquish Indra. However, Indra came to know about it and managed ç
to break the foetus into 49 parts. They were born as the Maruts, a ç
class of minor gods.
See also <MS>ADITI.<D>
@NT = Div<193>l<200>
See <MS>D®P°VAL®.<D>
@NT = Divine Incarnations
See <MS>AVAT°RA.<D>
@NT = Divod<193>sa
Divod<193>sa is a common name met with in the <184>gveda as also ç
in the epics and the pur<193><207>as.
Divod<193>sa Atithigva, son of Vadhr-ya·va, was a leading prince among ç
the Bharatas. He was the father (or grand- father) of the famous king ç
Sud<193>sa mentioned in the `da·ar<193>j<210>a' or the `battle of ç
the ten kings' (vide <184>gveda 7.33.3 and 5). <185>ambara, the ç
chieftain of the mountain tribes, was his great enemy.
The son of Bh<200>masena, the king of K<193>·<200>, was also known ç
as Divod<193>sa. His queen was M<193>dhav<200> and Pratardana, his ç
valiant son, who vanquished V<200>tahavya, the king of the Haihayas.
This Divod<193>sa is considered as a reincarnation of Dhanvantari, ç
the physician of the gods in heaven, and the teacher of Su·ruta (the ç
author of the famous treatise on surgery, the Su·ruta Sa<221>hit<193>).
Another Divod<193>sa has been mentioned in the pur<193><207>as as ç
the son of Bharmy<193>·va and brother of the famous Ahaly<193> (wife ç
of the sage Gautama).
@NT = divorce
Viv<193>ha or marriage has been considered as a sa<221>sk<193>ra (a ç
purificatory rite or sacrament). It is one of the three most important ç
of the sixteen sa<221>sk<193>ras, normally called `<218>o<195>a·asa<221>sk<193>ras'.
The dharma·<193>stras (religio-legal works) of Hinduism have always ç
considered viv<193>ha as sacred and inviolable. Hence the question ç
of divorce or remarriage of widows has not received much attention. ç
Even then, in cases of mutual hatred with the possibility of danger ç
to life and limb, divorce has been permitted.
The husband or the wife can abandon the other under certain circumstances ç
such as longstanding incurable disease, becoming `patita' or an outcaste ç
due to heinous sins and so on. Even in such cases bare maintenance ç
has to be provided to the abandoned party.
After the passage of `The Hindu Marriage Act' in 1955, many desirable ç
changes have been brought about in the system of marriage which include ç
provisions for divorce also.
@SPACE = 
@NT = divya
@N1 = (`divine', `supernatural')
@SPACE = 
Though this word generally means `divine,' it is used in the dharma·<193>stras ç
in a more technical sense. When a king had to decide whether a particular ç
person had committed a crime or not, especially when the evidence ç
normally relied upon, like eye-witness accounts or strong circum- ç
stantial evidence, was not conclusive, he could take recourse to `divya' ç
or supernatural mode of evidence. `Divya' is defined as `that which ç
decides a matter in dispute, not determined by human means of proo<%20>f<%0>'.
The suspect is subjected to an ordeal and is declared innocent if ç
he comes out unharmed. The Ch<193>ndogya Upani<218>ad (6.16.1) refers ç
to the ordeal of holding a heated axe in hand by a suspected thief. ç
If he is not scalded, he is considered innocent and freed.
Such divyas can range from two to nine. Some of them are: vi<218>a ç
(administering poison), ko·ap<193>na (drinking holy water, used for ç
bathing an image in worship), ph<193>la (licking a red-hot ploughshare), ç
ta<207><195>ula (swallowing rice-grains specially prepared) and taptam<193><218>a ç
(taking out heated gold pieces with bare fingers).
The details of the tests are described in the dharma·<193>stra works.
Physical laws of nature are inexorable. How can they fail in such ç
tests? For this objection the answer given by the writers of the dharama·<193>stras ç
is that even the normal processes of strong evidence have sometimes ç
failed to prove the guilt. And, supernatural things, unexplained mysteries, ç
are happening, even now.
@SPACE = 
@NT = divyabh<193>va
@N1 = (`divine disposition')
@SPACE = 
The tantras†the scriptures of the <185>akti-cult†categorise the s<193>dhakas ç
or spiritual  aspirants  into  three  groups according to their bh<193>vas ç
or dispositions. They are pa·u, v<200>ra, and divya.
The s<193>dhakas with the divyabh<193>va are highly s<193>ttvik by ç
nature. They keep themselves meticulously clean, wear clean clothes ç
and the religious marks (tripu<207><195>ra, bhasma or vibh<220>ti), ç
as also the rudr<193>k<218>a beads. They perform their religious rites ç
like sandhy<193>, japa and p<220>j<193> with faith and devotion. They ç
are well-versed in the Vedas and the scriptures of their cults. They ç
always speak the truth and keep the highest standards of morality ç
and ethics. They constantly strive for the attainment of devat<193>bh<193>va ç
or identity with the Divine.
See also <MS>TANTRAS.
@SPACE = 
@NT = divyade·a
@N1 = (`divine place')
@SPACE = 
Milk is got through the udder of a cow, though, theoretically speaking, ç
it pervades the whole body of the cow. Similarly, the tantras declare ç
that God, though omnipresent, is found more easily in certain places ç
called `divyade·as' or divine places. They are enumerated as sixteen ç
in number. Some of them are: vahni (fire), ambu (water), li<209>ga ç
(<185>ivali<209>ga), ma<207><195>ala (specified geometrical diagrams), ç
vigraha (icon or image) and h<216>daya (the region of the heart).
Dh<193>ra<207><193> or meditation has to be practised on the i<218><219>adevat<193> ç
or chosen deity in these places.
@SPACE = 
@NT = divyad<216><218><219>i
@N1 = (`divine sight')
@SPACE = 
According to the works on yoga, clairvoyant  powers  of  perception  are ç
inherent in everyone. These powers are roused by appropriate yogic ç
practices.
When sa<221>yama†dh<193>ra<207><193>, dhy<193>na and sam<193>dhi†is ç
practised on the puru<218>a or the individual soul, the yogi attains ç
special supernatural powers, of which divyad<216><218><219>i or <193>dar·a ç
is also one (vide Yogas<220>tras 3.36). He is then able to `see' ç
objects which may be extremely small or hidden by other things or ç
at a great distance or belonging to a past time or a future time.
Such siddhis or supernatural powers can prove to be obstacles to spiritual ç
illumination.
Lord K<216><218><207>a is said to have given divyad<216><218><219>i ç
to Arjuna before showing his cosmic form (Bhagavadg<200>t<193> 11.8).
The sage Vy<193>sa gave the power to Sa<210>jaya, to `see' the kuruk<218>etra ç
battle from the palace itself (Mah<193>bh<193>rata, Bh<200><218>maparva ç
2.9).
See also <MS>SA<189>YAMA.
@SPACE = 
@NT = Divya-prabandham
@N1 = (`divine<R>ç
compositions')
@SPACE = 
The Vi·i<218><219><193>dvaita system of philosophy is also known as ç
`Ubhaya Ved<193>nta', since it recognises two kinds of works (ubhaya ç
= both, two) as equally authoritative. They are: the Sanskrit works ç
commonly known as the `prasth<193>natraya', viz., the Upani<218>ads, ç
the Brahmas<220>tras and the Bhagavadg<200>t<193>; the Tamil works ç
of the °<202>v<193>rs known as the Divyaprabandham  or N<193>l<193>yira ç
Prabandham (since they contain four thousand [n<193>l = four, <193>yira ç
= thousand] verses).
The °<202>v<193>rs were Tamil saints who lived during the period <MS>A.<|>D.<D> ç
700-900. It is their mystical compositions that are known as Divyaprabandham ç
or `divine compositions'. An `°<202>v<193>r' is one who is deeply ç
immersed in the love of God. Since these prabandhams or compositions ç
were the spontaneous outpourings of their hearts, deeply immersed ç
in devotional fervour, they are `divya' or divine.
The following is the list of the °<202>v<193>rs and their compositions:
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(1.0692,E1,.4725), ç
ABOVE(.1528), BELOW(.0833), VGUTTER(.0278), KEEP(OFF), RULE(BODYX,R0C0..R0C3), ç
L1(R2C0..R2C3), L0(R1C0..R1C3)
@Z_TBL_BODY = TL, TL, TC2M
<R>ç
°<170>V°R, <R>ç
PRABANDHAM, P<193>·uras<R>ç
or<R>ç
Verses
@Z_TBL_BODY = SPACE1, TL, TR
<R>ç
, +, +
@Z_TBL_BODY = SPACE, TL, TR
, +, +
@Z_TBL_BODY = TL, TL, TR
°<207><195><193><202>, Tirupp<193>vai, 30
, N<193>cciy<193>r Tirumo<202>i, 147
@Z_TBL_BODY = SPACE, TL, TR
, +, +
@Z_TBL_BODY = TL, TL, TR
Kula·ekhara, Tirumo<202>i, 105
@Z_TBL_BODY = SPACE, TL, TR
, +, +
@Z_TBL_BODY = TL, TL, TR
Madhurakavi, (No<|>particular name), 11
@Z_TBL_BODY = SPACE, TL, TR
, +, +
@Z_TBL_BODY = TL, TL, TR
Namm<193><202>v<193>r, Tiruviruttam, 100
, Tiruv<193>·iriyam, 7
, Periya Tiruvand<193>di, 87
, Tiruv<193>ymo<202>i, 1102
@Z_TBL_BODY = SPACE, TL, TR
, +, +
@Z_TBL_BODY = TL, TL, TR
Periy<193><202>v<193>r, Tiruppall<193><207><195>u, 12
, Periya Tirumo<202>i, 461
@Z_TBL_BODY = SPACE, TL, TR
, +, +
@Z_TBL_BODY = TL, TL, TR
Pey<193><202>v<193>r, Tiruvand<193>di (third), 100
@Z_TBL_BODY = SPACE, TL, TR
, +, +
@Z_TBL_BODY = TL, TL, TR
Poygai °<202>v<193>r, Tiruvand<193>di (First), 100
@Z_TBL_BODY = SPACE, TL, TR
, +, +
@Z_TBL_BODY = TL, TL, TR
P<220>datta °<202>v<193>r, Tiruvand<193>di (Second), 100
@Z_TBL_BODY = SPACE, TL, TR
, +, +
@Z_TBL_BODY = TL, TL, TR
Tiruma<202>i·ai<|>°<202>v<193>r, Tirucandaviruttam, 120
, N<193>nmuhan<R>ç
<+><+><+>Tiruvand<193>di, 96
@Z_TBL_BODY = SPACE, TL, TR
, +, +
@Z_TBL_BODY = TL, TL, TR
Tiruma<209>gai<|>°<202>v<193>r, Periya Tirumo<202>i, 1084
, Tirukkuru-<R>ç
<+><+><+>dd<193><207><195>aham, 20
, Tirune<195>und<193><207><195>aham, 30
, <185>iriya Tiruma<207><195>al, 77
, Periya Tiruma<207><195>al, 148
, Tiruv<193>lukk<220>ttirakkai, 2
@Z_TBL_BODY = SPACE, TL, TR
, +, +
@Z_TBL_BODY = TL, TL, TR
Tirupp<193><207><193><202>v<193>r, Amalan<193>dipir<193>n, 10
@Z_TBL_BODY = SPACE, TL, TR
, +, +
@Z_TBL_BODY = TL, TL, TR
To<207><195>ara<195>ippo<195>i<R>ç
      °<202>v<193>r, Tirum<193>lai, 45
^, Tirupa<202><202>i Elicci, 10
@Z_TBL_END = 
@NID =   Total<|>:
@IN2K = 4004 p<193>·uras in 24 prabandhams by the 12 °<202>v<193>rs.
@SPACE = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
Since the Vi·i<218><219><193>dvaita Ved<193>nta considers the Divyaprabandham ç
as one of the two cardinal scriptures, the philosophy of the latter ç
is the same as the philosophy of the former. (See <MS>VI<185>I<186><187>°DVAITA ç
VED°NTA DAR<185>ANA.<D>) It can be briefly stated as follows:
The fundamental tattvas or realities are three (tattvatraya). They ç
are ®·vara (God), cit (the conscious soul) and acit (the insentient ç
prak<216>ti or nature). ®·vara is the independent reality whereas ç
the latter two are totally dependent upon him.
The universe is evolved out of the acitprak<216>ti through 24 cosmic ç
principles (as enumerated in the S<193><209>khya philo- sophy). The ç
cit or the j<200>va†there are infinite numbers of j<200>vas†is bound ç
in sa<221>s<193>ra or transmigratory existence since beginning-less ç
time due to karma, both good and bad.
It is ®·vara who out of compassion inspires him to try for mok<218>a ç
or liberation. In this attempt for liberation, the j<200>va has to ç
rediscover his relationship with ®·vara, which is of nine kinds: father ç
and son; protector and protected; whole and part; husband and wife; ç
known and knower; master and possession; supporter and supported; ç
soul and body; enjoyer and enjoyed.
The best means of liberation are: bhakti (devotion), prapatti (total ç
surrender to God) and kai<209>karya (service to God in his various ç
aspects).
The °<202>v<193>rs seem to be more partial to the path of prapatti ç
than bhakti.
@SPACE1 = 
The Prabandhas contain profuse praise of the avat<193>ras like R<193>ma ç
and K<216><218><207>a, as also the deities in the temples like the ç
ones in <185>r<200>ra<209>gam and Tirupati, which are known as arc<193>vat<193>ras ç
and considered as fully living and conscious.
Some of the p<193>·uras of the praban-dhas are chanted in <185>r<200>vai<218><207>ava ç
temples daily as a part of the worship of the deity.
See also <MS>°<170>V°RS<D> and <MS><185>R®VAI<186>ØAVISM.<D>
@NT = divya·rotra
@N1 = (`divine ear')
@SPACE = 
The Yogas<220>tras of Pata<210>jali describes the several supernatural ç
powers that a yogi develops by practising sa<221>yama as directed ç
by it. `Sa<221>yama' is a technical term signifying dh<193>ra<207><193> ç
(fixing the mind on the object of concentration,) dhy<193>na (continuous ç
meditation on the same) and sam<193>dhi (perfect concentration resulting ç
in supernatural or psychic experience) on the same object. By practising ç
sa<221>yama on the relation between pure <193>k<193>·a (ether principle, ç
called `·abdatanm<193>tra') and the organ of hearing, both of which ç
being products of aha<209>k<193>ra or the cosmic ego-principle, the ç
power to hear sounds, even though they are subtle or at a great distance ç
or separated by other objects, is attained. This is called `divya·rotra'.
The same technique can be applied to other organs too, attaining similar ç
divine powers pertaining to the eye, the nose, the tongue and the ç
skin.
See Yogas<220>tras 3.41.
@NT = Dol<193>y<193>tr<193>
@SPACE = 
The Holi is one of the most popular of the Hindu festivals and sacred ç
days. Whereas it is celebrated as a day of revelry in all parts of ç
the country, Bengal observes it in a quiet and dignified manner as ç
Dol<193>y<193>tr<193> or Dolp<220>r<207>im<193> (the festival of the ç
swing). This festival is said to have been initiated by the king Indradyumna ç
in V<216>nd<193>vana. It is spread over 3 or 5 days, starting from ç
the ·ukla caturda·<200> of the month of Ph<193>lguna (usually in March). ç
A celebration in honour of Agni and worship of Govinda (K<216><218><207>a) ç
in image kept on a swing (dol<193> = swing) are the important features. ç
The fire kindled on the first day is to be preserved till the last ç
day. The swing is to be rocked 21 times at the end of the festival.
The day is also observed as the birthday of <185>r<200> K<216><218><207>a ç
Caitanya (<MS>A.<|>D.<D> 1486-1533) mostly in Bengal as also Pur<200> ç
(Orissa), Mathur<193> and V<216>nd<193>van (Uttar Pradesh).
@NT = do<218>a
@N1 = (`that which contaminates', defect)
Derived from the root `du<218>' (`to contaminate,' `to spoil') , the ç
word `do<218>a' is used in several senses such as: fault, sin, vice, ç
crime, disrespect, abuse, evil and deficiency.
However, it is used in a technical sense too, in certain fields of ç
knowledge.
In literary compositions, do<218>a can be of five types, pertaining ç
to the use of the word or a part of the word, sentence, meaning and ç
sentiment. They are respectively known as padado<218>a, pad<193><221>·ado<218>a, ç
v<193>kyado<218>a, arthado<218>a and rasado<218>a. These defects are ç
sometimes raised to ten or even more. 
In tarka or logic, the do<218>as are broadly categorised as lak<218>a<207>ado<218>a ç
(defect in implicatory meaning) and hetudo<218>a (defect in the enumeration ç
of causes).
In the °yurveda, the main constituents of health are the three do<218>as ç
or humours: kapha (phlegm), v<193>ta (wind) and pitta (bile). If they ç
are in a balanced state, health will be maintained. If they are disturbed, ç
disease results.
@NT = Drami<195>opani<218>at
See <MS> TIRUV°YMO<170>I.<D>
@NT = dra<218><219><193>
@N1 = (`the seer')
@EMERGENCY = According to the various works on the Ved<193>nta system ç
of Indian philosophy, each one of us is actually the <193>tman, the ç
soul, whose real nature is `sat-cit-<193>nanda' (existence, knowledge ç
and bliss). This <193>tman has become involved and identified with ç
the body-mind complex due to prim-eval ignorance which, however, can ç
be annihilated by j<210><193>na or knowledge. The process of discrimination ç
between the d<216>k or dra<218><219><193> (the seer, the witness or ç
the subject) and the d<216>·ya (the seen, the object) will help in ç
ultimately isolating the <193>tman from the body, the senses and the ç
mind.
@EMERGENCY = For instance, an external object is d<216>·ya and the ç
eye is the d<216>k. Again, the eye becomes the d<216>·ya for the mind ç
which is now d<216>k. However, even this mind becomes the d<216>·ya ç
for the <193>tman, the conscious Self. There is none who is the d<216>k ç
for the <193>tman. Hence the <193>tman is the ultimate d<216>k<|>or<|>dra<218><219><193>. ç
The dra<218><219><193> who is pure consciousness continues to remain ç
so eventhough there may be nothing to become d<216>·ya for him. For ç
instance, in pitch darkness, in an empty room, though the eye is `seeing,' ç
there is nothing to be `seen.' Similarly, the dra<218><219><193>, ç
the <193>tman as the ultimate witness is always the conscious subject ç
or the seer and there is no loss of his consciousness irrespective ç
of the existence or non-existence of objects to be comprehended by ç
him.
@NT = Draupad<200>
@N1 = (`daughter of Drupada')
@SPACE1 = 
Draupad<200>, also known as K<216><218><207><193> (since she was of ç
dark complexion) (k<216><218><207>a = dark) and P<193><210>c<193>l<200> ç
(since she was the daughter of the king of the country of P<193><210>c<193>la) ç
was the chief queen of the five P<193><207><195>ava princes. She was, ç
in a way, the root-cause of the fratricidal war of Kuru-k<218>etra.
She was born, along with her brother Dh<216><218><219>adyumna, from ç
the sacrificial fire of Drupada, the king of P<193><210>c<193>la. ç
Since she was a damsel of extraordinary beauty, Drupada arranged for ç
her svaya<221>vara (See <MS>SVAYA<189>VARA.<D>) with very high stakes, ç
in the form of piercing the matsyayantra (See <MS>MATSYAYANTRA<D>). ç
Arjuna succeeded in the feat and was garlanded by her.<MS>
When the five P<193><207><195>ava princes who were then in disguise ç
as forest hermits, announced to their mother Kunt<200> that they had ç
brought an extremely precious alms, Kunt<200> who was busy inside ç
the hut, commanded them to `share it equally!' When she actually saw ç
the girl and realised her mistake it was too late! Draupad<200> was ç
then married to all the five brothers. The sage N<193>rada came to ç
the rescue of the brothers stipulating that she should live with each ç
of them for one year by turns and that if any of the others saw her ç
during that period, should go on a pilgrimage for one year as a penance.
In the first gambling match with the Kauravas, Yudhi<218><219>hira, ç
the eldest of the P<193><207><195>avas, lost his all, including Draupad<200>. ç
Though she was humiliated, she was rescued by the divine intervention ç
of <185>r<200> K<216><218><207>a.
The P<193><207><195>avas regained their possessions but Yudhi<218><219>hira ç
lost them again in a second round match. This time they were forced ç
into exile for thirteen years.
@SPACE1 = 
After the exile period was over, when the P<193><207><195>avas were ç
in a mood to compromise  with  the  Kauravas,  Draupad<200> appealed ç
to <185>r<200> K<216><218><207>a to bring about the destruction of ç
the latter through war. <185>r<200> K<216><218><207>a did so. Her ç
anger subsided when Du··<193>sana and Duryodhana were killed in the ç
battle.
When Yudhi<218><219>hira was crowned as the monarch, Draupad<200> ç
became the queen.
During the final journey of the P<193><207><195>avas to heaven (known ç
as `mah<193>-prasth<193>na') Draupad<200> was the first to collapse. ç
The reason given by Yudhi<218><219>hira was that she was loving Arjuna ç
more than the others, though she was expected to love all the five ç
husbands equally.
Draupad<200> has been considered as an aspect of the Mother-goddess ç
and worshipped as such by the folk-cults of South India. There are ç
numerous shrines dedicated to her in Tamil Nadu and Karna-taka, where ç
an annual ritual festival known as `Karaga' is celebrated. The shrines ç
also contain the icons of Dharma-r<193>ja (or Yudhi<218><219>hira) ç
as her consort.
Iconographically, she is shown as a beautiful lady with three eyes ç
and two arms, the right one holding a lotus. The figure is bent in ç
three places (tribha<209>ga).
See also <MS>MAH°BH°RATA.<D>
@NT = Draupad<200>-ratha
@N1 = (`the chariot of<R>ç
Draupad<200>')
There are seven rock-cut temples in M<193>mallapuram or Mah<193>balipuram ç
near Madras (or Chennai) on the east coast. They are generally called ç
`Rathas' since they resemble a ratha or a chariot in shape. The Draupad<200>-ratha ç
is also one of them. It is the first on the northern side.
It is a simple cell, 3.3 metres (11 ft.) square externally, with a ç
curvilinear roof rising to a height of 5.4 metres (18 ft.). The cell ç
inside measures 1.95 metres in depth by 1.35 metres across (6.5 ft. ç
by 4.5 ft.). On the back wall there is the figure of a female deity ç
(with four arms) and her four attendants. There are also two dv<193>rap<193>lik<193>s ç
(gate-keepers) at the entrance.
It is in Pallava style of architecture and belongs to the 7th cent. ç
<MS>A.<|>D.<D>
@NT = Dr<193>vi<195>a
This word has been used in the dharma·<193>stra literature in several ç
senses. `Dr<193>vi<195>a' is the name of a caste classed among the ç
·<220>dras. Persons of this caste are supposed to have sprung from ç
the k<218>attriyas who had not undergone the Vedic sacraments like ç
upanayana.
The br<193>hma<207>as of India have been divided into two groups: ç
pa<210>ca-dr<193>vi<195>a<|>and pa<210>ca-gau<195>a. The kar<207><193><219>as, ç
the taila<209>gas, the gurjaris, the mah<193>r<193><218><219>rians ç
and the dr<193>vi<195>as belong to the former group. Among these, ç
the dr<193>vi<195>as are also one.
Among the three well-known styles of temple architecture, dr<193>vi<195>a ç
is also one, the other two being n<193>gara and vesara. The dr<193>vi<195>a ç
style is in the form of truncated pyramids and is more common in the ç
region to the south of the river K<216><218><207><193>.
@NT = Dravi<195>ians
The question of the ancient people of India, whether they were the ç
original inhabitants or immigrants, has always received great attention ç
at the hands of historians, indologists, anthropologists andphilologists. ç
Several hypotheses and theories have been advanced over the last two ç
centuries though no particular school of thought has been universally ç
acclaimed or even gained a majority of adherents.
One such vexatious question is that of the °ryans and the Dravi<195>ians. ç
If somesay that the Dravi<195>ians were the original inhabitants ç
of India, driven to the southern  peninsula  by  the  invading °ryans, ç
thereare others who declare that they too were immigrants who came ç
from the Mediterranean region much earlier than the °ryans.
However, there is also another view that the Harappa-Mohenjo D<193>ro ç
culture is the advanced stage of Vedic culture† and hence has nothing ç
to do with the so-called Dravi<195>ian culture†and that the Dravi<195>ian ç
languages like Tamil, Telugu and Kannada are gradual evolutions from ç
the Pr<193>k<216>t and Pai·<193>c<200> languages whichthemselves ç
were derivatives of the Sanskrit language.
There has been so much of racial commingling and complicated evolutions ç
of languages over the millennia that no single theory can be accepted ç
as unquestioningly authentic.
Since Agastya, the great Vedic sage, had been universally acclaimed ç
as the originator of the religion, language and culture of South India ç
(which later spread to the South East Asian countries also), suffice ç
it to say that the °ryan-Dravi<195>ian divide is more a conjecture ç
than a well- established fact.
See also <MS>AGASTYA<D> and <MS>°RYANS.<D>
@NT = dravya
@N1 = (`substance')
The word `dravya' has been used widely in several senses, including ç
the technical ones in some systems of Indian philosophy. The general ç
senses are: wealth, an object or substance, an auspicious one, an ç
ointment, intoxicating liquid, medicine and bronze.
In the Ny<193>ya system of Gautama, `dravya' is one of the seven pad<193>rthas ç
or fundamental substances in the universe. This `dravya' is of nine ç
types: the five bh<220>tas or elements, k<193>la (time), dik (quarters ç
or directions), <193>tman (the individual soul) and manas (mind).
In the Dvaita Ved<193>nta system, it comprises 20 items such as Param<193>tman ç
(God), Lak<218>m<200> (The Divine consort of God), j<200>v<193>tman ç
(the individual soul), prak<216>ti (nature), the three gu<207>as like ç
sattva, buddhi (intellect), indriya (senses), avidy<193> (ignorance) ç
and so on.
On the other hand, the Vi·i<218><219><193>dvaita Ved<193>nta recognises ç
only six items under dravya. They are: prak<216>ti (nature), k<193>la ç
(time), ·uddha or pure sattva, dharma-bh<220>ta-j<210><193>na (knowledge ç
as an attribute of the j<200>va), j<200>va (individual soul) and ®·vara ç
(god).
The substances like fuel-sticks of a·vattha (Ficus religiosa), sesamum ç
seeds, pudding of milk, ghee, sweetmeats, coconuts, jaggery, honey ç
and certain fruits† are also called `dravya' or `homadravya' and are ç
used in homas or sacrifices.
In the °yurveda (health science) seven dravyas like v<193>ta (wind), ç
pitta (bile), ·le<218>ma (phlegm), tvak (skin) and m<193><221>sa (flesh) ç
are recognised as comprising the physical body.
@NT = dravyayaj<210>a
@N1 = (`sacrifice with wealth')
Yaj<210>a or the system of sacrifices is an ancient institution. According ç
to the Hindu scriptures like the Bhagavadg<200>t<193> (3.10) it ç
was created by Praj<193>pati (father of creation) himself in the beginning ç
as a link between the gods in heaven and the human beings here. The ç
human beings have to satiate the gods like Indra through yaj<210>a ç
and the latter in return bestow rains and grant other things needed ç
by the human beings.
Though <185>r<200> K<216><218><207>a has accepted this basic system, ç
he has expanded its scope considerably in the Bhagavadg<200>t<193> ç
(4.25-33). It is in this connection that he has used the word `dravyayaj<210>a' ç
(4.28). It is interpreted as giving money or things to worthy and ç
deserving persons at the appropriate time and place, and, in an appropriate ç
manner.
The most important act in a yaj<210>a is sacrificing the individual ç
good for social or universal good. In whichever act, such a spirit ç
is seen, that itself is elevated to the level of a yaj<210>a.
@SPACE = 
@NT = dreams
@SPACE = 
@SPACE1 = 
`Snakes' and dreams have come in very handy for the Advaita Ved<193>nta ç
philosophy to prove one of its cardinal teachings viz., the unreality ç
of this world. If the `snake' in the rajju-sarpa-ny<193>ya (the maxim ç
of the rope appearing as a snake in insufficient light) serves as ç
the proof for the absolute unreality of this world, the dream can ç
help in proving its relative reality. Just as a dream is real as long ç
as it lasts, this world too is real as long as we are under the sway ç
of avidy<193> or nescience.
@SPACE1 = 
However, dreams assume a much greater significance in other fields ç
of knowledge like °yurveda (health-science) and prognostication or ç
futurology. Directions have also been given in them as to how to utilise ç
them to one's advantage if they predict good things and how to offset ç
them if they forebode evil.
Dreams can be caused by physical causes like the disturbance of the ç
humours (kapha or phlegm, v<193>ta or wind and pitta or bile), past ç
experiences of this life or the past lives. Depending upon the type ç
and the time of occurrence of the dreams, the results are predicated. ç
Dreams occurring in the first part of the night will give their results ç
in one year, in the second part in eight months, in the third part ç
in three months and at dawn, in 10 days. The result may be immediate ç
if the person wakes up at once.
If the person sleeps again after the dream or tells others about it, ç
the dream will not give its results.
Seeing the following in a dream is considered as auspicious: elephant, ç
a king, gold, a bull, a cow, a lighted lamp, food, fruits, a maiden, ç
an umbrella, a chariot and a flag.
The following objects seen in a dream forebode evil: shaving of the ç
head, nakedness, wearing dirty garments, falling from high spots like ç
a hill, riding boars, asses and camels, killing horses, ascending ç
a funeral pyre, falling of sun and moon, playing with goblins, plunging ç
into oil or drinks, wearing red garments or applying red unguents ç
and so on.
The epics and the pur<193><207>as contain innumerable verses on this ç
subject.
@SPACE1 = 
The remedies suggested to offset the effects of bad dreams are: performing ç
a ·r<193>ddha like the one on an am<193>v<193>sy<193> day
