@NID = or reciting holy texts like the Durg<193>- sapta·at<200> ç
or the Vi<218><207>usahasran<193>ma or the Gajendramok<218>a part ç
of the Bh<193>gavata. Performance of appropriate ·<193>ntis (reli-gious ç
rites to bring about auspicious results) is also recommended.
The work Adbhutas<193>gara of the king Balla<202>asena of Bengal ç
(<MS>A.<|>D.<D> 1168) is considered as a great authority on this subject.
@SPACE = 
@NT = dre<218>k<193><207>a
@N1 = (also spelt as drekk<193><207>a)
@SPACE = 
Jyauti<218>a or the `science of light' is an ancient science, the ç
science of astro-nomy and astrology combined. Out of the several technical ç
words used in Hindu astrology, the word `dre<218>k<193><207>a' (or ç
drekk<193><207>a) is also one.
When a sign of the zodiac is divided into three equal parts, each ç
part is called `dre<218>k<193><207>a'. The lord of the first dre<218>k<193><207>a ç
is the owner of the sign itself. The lord of the second dre<218>k<193><207>a ç
is the lord of the 5th sign in question. The lord of the third dre<218>k<193><207>a ç
is the lord of the 9th sign.
For instance, consider the zodiacal sign Me<218>a or Aries. Divide ç
it into three equal parts, each being called a dre<218>k<193><207>a. ç
The first is governed by the sign of Me<218>a or Aries, viz., Kuja ç
or Mars. The second is ruled by the lord of the 5th sign (Si<221>ha ç
or Leo), viz., Ravi or Sun. The third is ruled by the lord of the ç
9th (<185>ani or Sagittarius), viz., Guru or Jupiter.
The ecliptic (of 360<F20><198><F255>) is divided into 12 R<193>·is or zodiacal ç
signs like Me<218>a (Aries), V<216><218>abha (Taurus) and so on, each ç
occupying 30<F20W1><198><F255D> in the same. It is this 30<F20><198><F255> that ç
is divided into 3 dre<218>k<193><207>as, each dre<218>k<193><207>a ç
being of 10<F20><198><F255> extension.
The word dre<218>k<193><207>a is said to be of Egyptian or Greek origin, ç
the original word being `decanoi' (deca = 10). Each of these 36 had ç
its own geni or deity, ruling over it.
These terms and associated ideas have their own use in astrological ç
calculations.
@NT = drinking
See <MS>SUR°P°NA.<D>
@NT = d<216>k
@N1 = (`the seer')
See <MS>DRA<186><187>°.<D>
@NT = Dro<207><193>c<193>rya
Bh<200><218>ma and Dro<207>a or Dro<207><193>c<193>rya were the two ç
greatest warriors that fought for Duryodhana in the Kuruk<218>etra ç
war of the Mah<193>bh<193>rata. Like Para·ur<193>ma, his teacher, ç
Dro<207><193>c<193>rya too was a br<193>hma<207>a by birth, but a ç
k<218>attriya (warrior) by profession.
Born as the son of the sage Bharadv<193>ja, he got his early education, ç
including the training in dhanurvidy<193> or archery from the <216><218>i ç
Agnive·a. Drupada, the king of P<193><210>c<193>la, was a fellow-student. ç
After  completing  his  training  under Agni-ve·a, he once approached ç
the king Drupada for financial help. The king in his arrogance humiliated ç
him. Enraged by this, he approached Para·ur<193>ma for higher training ç
in archery and warfare so that he could take revenge on the king. ç
After completing the same, he was, though by chance, appointed as ç
the teacher of the Kaurava and the P<193><207><195>ava princes by ç
Bh<200><218>ma. Arjuna, of the five P<193><207><195>ava princes, proved ç
to be his worthiest and best disciple. With his help, he got Drupada ç
taken prisoner, usurped half of his kingdom and then let him off.
Once, the P<193><207><195>ava princes discovered the hunter-boy Ekalavya ç
in a forest by accident and found him to be a better archer than Arjuna. ç
Ekalavya claimed to be a disciple of Dro<207><193>c<193>rya himself. ç
The latter then demanded and got his thumb as his gurudak<218>i<207><193> ç
or fee just to please Arjuna!
Throughout the conflict between the Kauravas and the P<193><207><195>avas, ç
Dro<207><193>c<193>rya too, like Bh<200><218>ma, tried his best to ç
advise Duryodhana to desist from his evil ways and make peace with ç
the P<193><207><195>avas. But his advice fell on deaf ears.
In the ensuing Kuruk<218>etra war he fought fiercely, first under ç
Bh<200><218>ma and later as the commander-in-chief. Then as per the ç
advice of the sages like Vasi<218><219>ha and Gautama, he retired ç
from the battle and sat in yoga. At that time he was killed  by  Dh<216><218><219>adyumna,  the  son  of ç
Drupada.
Two more Dro<207>as are mentioned in the pur<193><207>as. One was ç
a Vasu (a kind of a demigod) who, along with his wife Dhar<193>, performed ç
austerities in the Gandha-m<193>dana hill for long time to get the ç
Lord as their son. They were reborn as Nanda and Ya·od<193> in their ç
next life. Lord K<216><218><207>a, as their foster child, gave them ç
great happiness and bliss through his childish pranks.
@SPACE1 = 
The sage <185><193>r<209>gaka, the son of the sage Mandap<193>la and ç
Jarit<193> when they had assumed the bodies of birds, was also known ç
as Dro<207>a and was considered a brahmar<218>i.
Dro<207>a is also the name of a mountain mentioned in some pur<193><207>as.
@NT = dro<207>akala·a
Among  the  Vedic  sacrifices,  the Somay<193>gas are a class by themselves. ç
The soma juice is the main dravya or ingredient to be offered into ç
the sacrificial fire in these y<193>gas. The soma juice is prepared ç
by crushing the soma stalks with stones. It is then strained through ç
a cloth called da·<193>pavitra into a wooden vessel with a handle. ç
This latter is called `dro<207>akala·a' or `duro<207>akala·a'.
See <MS>DA<185>°PAVITRA<D> also.
@NT = Dro<207>aparva
The seventh book of the Mah<193>-bh<193>rata, each of which is known ç
as a parva (a knot or a joint or a book), the Dro<207>aparva contains ç
the exploits of the teacher Dro<207><193>c<193>rya until his death ç
at the hands of Dh<216><218><219>adyumna, the commander-in-chief of ç
the P<193><207><195>ava army.
See also <MS>DROØ°C°RYA<D> and <MS>MAH°-BH°RATA.<D>
@NT = d<216><218>ad and upala
@SPACE1 = 
Vedic sacrifices are an ancient institution. Out of the several materials ç
used in the sacrifices for oblation into the duly consecrated fire, ç
puro<195><193>·as or cakes made by baking pounded grains is also one. ç
The two mill-stones used for pounding the grains are called d<216><218>ad ç
and upala. D<216><218>ad is the lower stone, flat in shape whereas ç
Upala is the upper cylindrical stone.
@NT = d<216><218><219><193>nta
@N1 = (`[that by which the] conclusion [is] seen', `illustration')
All the systems of Hindu philosophy give importance to logic and reasoning, ç
to prove their theories. One of the steps normally accepted by them ç
is to give a `d<216><218><219><193>nta' or illustration or example. ç
Take this statement: `The hill is fiery since it is smoky.' The reason ç
normally offered is `Wherever there is fire, there is smoke.' And ç
the d<216><218><219><193>nta or example is: `the fire in the kitchen ç
oven.' This is an example of  the  positive  type  and  is  called ç
`s<193>dharmya-d<216><218><219><193>nta'.
The same point can be proved by giving a negative example too. `Where ç
there is no fire there is no smoke.' This is called `vaidharmya-d<216><218><219><193>nta'.
For a d<216><218><219><193>nta to be valid, it should be acceptable ç
both to the common man and to the philosopher.
@NT = d<216><218><219>i-s<216><218><219>i-v<193>da
@N1 = (`the doctrine [that the world is] created [simultaneously with ç
its] perception')
S<216><218><219>i or creation of this world has been an important ç
topic of discussion inall the six philosophical systems of Hinduism. ç
Though the philosophers of the Advaita Ved<193>nta school admit in ç
general, of the existence of the external world and its creation†since ç
the topic has been dealt with in the Upani<218>ads†they do not accept ç
it as a permanent reality.
Out of the several schools of Advaita Ved<193>nta in the post-<185>a<209>kara ç
period, that developed by Prak<193>·<193>nanda (<MS>A.<|>D.<D> 1550-1600) ç
is also one. It is subjective idealism. His view of creation is known ç
as `d<216><218><219>i-s<216><218><219>i-v<193>da', the view that creation ç
of the external object is simultaneous with its perception by the ç
seer. According to this school, a thing existed only when it was perceived ç
and not before or after perception. For example, a blue lotus and ç
its awareness are one and there is no external object apart from the ç
cognition. The dream state is purely mental and there are no extra-mental ç
objects. Similarly in the waking state, the so-called external object ç
is only a mental state and there is really no distinction. The whole ç
world is thus only a psychic modification and has no reality outside ç
the mind. This view is similar to the idealism of the Yogav<193>si<218><219>ha ç
and is perhaps derived from it. The Vij<210><193>nav<193>da of Buddhism ç
is also almost the same.
@NT = d<216>·ya
@N1 = (`that which is perceived')
See <MS>DRA<186><187>°.<D>
@NT = du<199>kha
@N1 = (`suffering')
All living beings seriously try to escape from du<199>kha or sorrow ç
and suffering. An analysis of the causes of du<199>kha and the means ç
of getting relief from it often find a place in philosophical systems.
Du<199>kha has been defined in various ways by these systems. Some ç
of them are: that which is characterised by pain; One of the qualities ç
or states of mind that can be known by the reactions seen on the face; ç
that which brings about hatred and so on.
Du<199>kha can be brought about by various factors such as: loss of ç
freedom; mental tensions and diseases; sickness of the body; loss ç
of honour; enemies; unhappy marriage; living in a bad place; serving ç
a bad master; old-age; living in the houses of others, depending upon ç
them and soon.
Du<199>kha has been classified in various ways by different systems. ç
Here, the causes are given greater importance. For instance†those ç
caused by: diseases, the six enemies such as lust and greed, tendencies ç
carried over from previous lives, birth and death.
Persons easily susceptible to jealousy, hatred, cruelty and a doubting ç
nature are always subjected to du<199>kha.
Though appropriate remedial measures are available for these du<199>khas, ç
mok<218>a or liberation from transmigratory existence is the ultimate ç
and the surest remedy.
@NT = Dundubhi
Born as the son of May<193>sura and Hem<193>, Dundubhi was a ferocious ç
demon. M<193>y<193>v<200> was his brother and Ma<207><195>odar<200> ç
(the queen of R<193>va<207>a) was his sister.
Puffed up with the arrogance of strength acquired by austerities and ç
boons, he challenged Varu<207>a and Himav<193>n (the kings of the ç
oceans and the mountains) for a duel. They advised him to fight with ç
V<193>l<200>, who would be the best adversary for him. However, V<193>l<200> ç
ultimately killed him after a fierce fight.
Dundubh<200> was a Gandharva princess reborn as Manthar<193> (due ç
to a curse) and served as the hand-maid of Kaikey<200>, the youngest ç
queen of Da·aratha. She was instrumental  in  creating  the  palace ç
intrigues that led to the banishment of R<193>ma to the forest.
@NT = Durg<193>
@N1 = (`the One [who is] difficult [to approach]')
Durg<193> is, perhaps the most widely worshipped aspect of <185>akti. ç
An entire Pur<193>na, the Dev<200>bh<193>gavata, has been dedicated ç
to her. Another work, more well-known than the Dev<200>bh<193>gavata, ç
but containing practically the same material in a concise from, is ç
the Dev<200>m<193>h<193>tmyam. It is also known as the Durg<193>sapta·at<200> ç
or Ca<207><195><200>, and forms a part of another well- known pur<193><207>a, ç
the M<193>rka<207><195>eyapur<193><207>a. This work is so highly ç
venerated that every verse of it is considered to be a mantra (sacred ç
formula) of the Dev<200> and its repetition is believed to confer ç
whatever boons the votary prays for.
Literally `Durg<193>' means one who is difficult to approach, or, ç
difficult to know. Being the personification of the totality of the ç
powers of the gods, she is naturally difficult to approach or to know. ç
However, being the Mother of the universe, she is the personification ç
of tender love, when supplicated.
Out of the several aspects of the <185>akti put forward by this work, ç
Yoganidr<193> (`meditation-sleep') comes first. She is the power of ç
sleep, taking recourse to which, Lord Vi<218><207>u rests between ç
two cycles of creation. She is praised as responsible for the creation, ç
sustenance and withdrawal of the universe. She is the mysterious power, ç
the very personification of know-ledge, wisdom and memory. She is ç
pleasant and beautiful. At the same time she is terrible also. This ç
combination of the opposite qualities is possible only for her. She ç
is described as wielding several weapons like the bow, arrow, sword, ç
discus and trident.
@SPACE1 = 
The next is Mahi<218><193>suramardin<200>, the deity who took shape ç
as a result of the pooling together of the powers of all the gods, ç
who had been oppressed by the demon Mahi<218><193>sura. Vi<218><207>u, ç
<185>iva and Brahm<193> were incensed by hearing the accounts of the ç
misdeeds of Mahi<218><193>sura and the Dev<200> was born out of their ç
wrath, followed by the wrath of the lesser divinities. The powers ç
of these gods formed her limbs and the exact duplicates of their weapons ç
formed her arsenal. Armed with these formidable weapons and riding ç
on a fierce lion, she challenged Mahi<218><193>sura and destroyed ç
him along with his army.
This story is followed by an exquisite hymn which combines in itself ç
both poetic excellence and devotional fervour and insight. She is ç
the power inscrutable, by which the whole universe is permeated and ç
energised. She is the personification of all wealth, power, beauty, ç
as also virtues. She is the embodiment of yaj<210>a (sacrifice), par<193>vidy<193> ç
(the highest know-ledge concerning the spirit) as well as apar<193>vidy<193> ç
(knowledge of the secular sciences). It is she who bestows wealth† ç
both material and spiritual†dispels difficulties, and annihilates ç
the evil ones. Herbeauty as well as her valour, is incomparable.
The gods could not enjoy their freedom for long. Very soon, they were ç
overpowered by the demons <185>umbha and Ni·umbha. So they had to ç
run to the Him<193>layas and supplicate the Dev<200> again. This hymn, ç
well-known as the `Apar<193>jit<193>-stotra,' praises her as the `unconquered'. ç
Her immanence in all the living beings is the main theme of this hymn. ç
The powers and activities of all beings are manifestations of only ç
her power.
In response to this prayer, she manifested herself as Kau·ik<200> ç
Durg<193>, emanating from the body of P<193>rvat<200>, who herself ç
became K<193>l<200> the dark one, after this manifestation.
@SPACE1 = 
The world-bewitching beauty of Durg<193> attracted the attention of ç
<185>umbha and Ni·umbha who sent proposals of marriage through a serf. ç
Unfortunately for them, in a moment of `weakness and foolishness' ç
she had vowed to marry only him who would vanquish her in battle. ç
All attempts at forcibly dragging her away ended in disaster for the ç
demons. Heads rolled, the intervention of giants like Dh<220>mralocana, ç
Ca<207><195>a, Mu<207><195>a and Rakta-b<200>ja not withstanding. ç
K<193>l<200>, the fierce black goddess who emerged from the Dev<200>'s ç
forehead, beheaded Ca<207><195>a and Mu<207><195>a and thus won the ç
name C<193>mu<207><195><193> for herself. Only the battle with Raktab<200>ja ç
was longdrawn needing some special efforts by the Dev<200> since he ç
had the mysterious power to multiply himself through the drops of ç
blood spilled in the battle. Even the Saptam<193>t<216>k<193>s (seven ç
Mothers) who came out of her body to battle, seemed helpless. It was ç
K<193>l<200> who managed to spread her extensive tongue and drink ç
away all the blood gushing out of Raktab<200>ja, thus preventing the ç
emergence of more demons and enabling Durg<193> to exterminate him. ç
The rest was easy. Ni·umbha was easily put to death after a mockery ç
of fight. <185>umbha  being  exasperated  by  now, accused her of ç
taking the help of `others!' Laughing derisively, the Dev<200> withdrew ç
all her emanations and manifestations into herself, showing that she ç
was always the One without a second. In the ensuing battle, <185>umbha ç
the lord of the demons, was easily killed, thus ridding the worlds ç
of the great terror.
@SPACE1 = 
This is followed by another piece of prayer, an enchanting poetical ç
hymn, which is as simple as it is elegant. Known as the `N<193>r<193>ya<207><200>stuti' ç
it starts with a fervent appeal to the Mother by the grateful gods ç
to be benign and gracious. The hymn describes her as the mistress ç
and the mother of the whole creation. She is the physical universe. ç
She is the mysterious power of Vi<218><207>u (Vai<218><207>av<200>·akti), ç
the original cause, as also the power that deludes beings. It is only ç
by pleasing her that one can hope to get spiritual emanci-pation. ç
All arts and sciences as also womankind, are her manifestations. She ç
is residing as the intellect in the hearts of human beings. She is ç
the all-devouring time. She is the very personification of all that ç
is good and auspicious. She is ever engaged in protecting her children. ç
The Saptam<193>t<216>k<193>s are really her aspects. K<193>l<200> ç
the terrible, with a garland of human skulls round her neck, is also ç
another of her aspects. When pleased, she can remedy all diseases. ç
If displeased, she can destroy all that we love and like to possess. ç
Her votaries are always free from troubles. She is the Supreme Truth ç
described in all the scriptural works.
The work also describes her other manifestations like Vindhyav<193>sin<200> ç
(one who lives in the Vindhyas), Raktadant<193> (of red teeth), <185>at<193>k<218><200> ç
(of hundred eyes), <185><193>ka<221>bhar<200> (sustainer of vegetables), ç
Durg<193> (slayer of demon Durgama), Bh<200>m<193> (the terrible) ç
and Bhr<193>mar<200> or Bhrama-r<193>mb<193> (having the form of bees).
The Dev<200> as depicted in this work has three major manifestations: ç
Mah<193>k<193>l<200>, Mah<193>lak<218>m<200> and Mah<193>sarasvat<200>. ç
These aspects should not be confused with the paura<207>ic deities, ç
P<193>rvat<200>, Lak<218>m<200> and Sarasvat<200>. They are actually ç
the three major manifestations of the One Supreme Power Mahe·var<200>, ç
according to the three gu<207>as (tamas, rajas and sattva).
@SPACE1 = 
The first, Mah<193>kal<200>, has ten faces and ten feet. She is deep ç
blue in colour, like the gem N<200>lama<207>i. She is bedecked with ç
ornaments and wields in her ten hands, the following weapons and objects: ç
sword, discus, mace, arrow, bow, iron club, lance, sling, human head ç
and conch. Being the personification of the t<193>masic aspect of ç
the Dev<200>, she is also the Yoganidr<193>, who has put Lord Vi<218><207>u ç
to sleep. It is to her that Brahm<193> prayed, requesting her to leave ç
Vi<218><207>u so that the latter could destroy the demons Madhu and ç
Kai<219>abha.
She is the personification of M<193>y<193>, the mysterious power of ç
Lord Vi<218><207>u. Unless she is pleased and voluntarily withdraws, ç
the Lord in us will not awake and destroy the powers of evil which ç
are trying to destroy us. This seems to be the import of the story ç
of Brahm<193>, Madhu and Kai<219>abha.
Mah<193>lak<218>m<200>, the second, the r<193>jasic aspect of the ç
Dev<200> is described as red in colour like the coral. She holds in ç
her eighteen hands the rosary, battle-pot, cudgel, lance, sword, shield, ç
conch, bell, wine-cup, trident, noose and the discus Sudar·ana. Being ç
`born' out of the combined wraths and powers of all the gods, she ç
is the personification not only of the powers but also of the will ç
to fight the evil forces. That is why she is shown as red in colour, ç
the colour of blood, the colour of war. It is she who destroyed Mahi<218><193>sura.
@SPACE1 = 
The story of Mahi<218><193>sura has several implications. Mahi<218><193>sura, ç
the he-buffalo, represents the jungle law that might is right. He ç
is the ruthless brute force that does not brook any opposition where ç
selfish ends are concerned. And he succeeded even against the gods; ç
but only when they were divided. But he fell before theircombined ç
powers and the will to fight, which is exactly what the Dev<200>, ç
Mahi<218><193>sura-mardin<200>, represents. The lesson of this story ç
at the social level is too obvious to need an explanation. Nor can ç
we ignore its social implications. At the subjective level, Mahi<218><193>sura ç
stands for ignorance and stubborn egoism. Its subju-gation and conquest ç
are possible only when the s<193>dhaka (spiritual aspirant) pools ç
all his energies together and fights it with a tenacious will. Since ç
God helps him who helps himself, the intervention of the divine power ç
in his favour is always there.
Mah<193>sarasvat<200> is the third deity representing the s<193>ttvic ç
aspect of the Dev<200>. She is bright like the autumn moon and has ç
eight hands in which she holds the bell, trident, ploughshare, conch, ç
pestle, discus, bow and arrow. It is she who manifests out of the ç
physical sheath of P<193>rvat<200> and hence known as Kau·ik<200> ç
Durg<193>. She is the very personification of physical perfection ç
and beauty. She is the power of work, order and organization.
@SPACE1 = 
The section dealing with her exploits is the longest. Dh<220>mralocana, ç
Ca<207><195>a, Mu<207><195>a, Raktab<200>ja, Ni·umbha and <185>umbha ç
are the chief demons destroyed by her. All these demons known as Asuras, ç
are archetypes of highly egoistic people who revel in a life of the ç
pleasures of the body and the sense-organs. Symbolically they represent ç
various stages and states of egoism. If Dh<220>mralocana (`the smoky-eyed') ç
stands for the grossest state of ignorance and egoism, Raktab<200>ja ç
represents a more subtle state which multiplies itself and our troubles! ç
While Mu<207><195>a is the low profile of our egoism (mu<207><195>a ç
= the low), Ca<207><195>a is the more horrible sideof it (ca<207><195>a ç
= fierce). <185>umbha and Ni·umbha signify  more  englightened  aspects  of ç
egoism (<185>umbh = to shine).
Dh<220>mralocana was destroyed by a hu<209>k<193>ra, by a mere frown! ç
Ca<207><195>a and Mu<207><195>a were too mean to be handled by the ç
Dev<200> directly. Hence K<193>l<200>, the horrible, finished them ç
at her behest. Raktab<200>ja required more skilful handling. The source ç
of his strength was destroyed first before destroying him. As for ç
Ni·umbha and <185>umbha, the Dev<200> was obliged to give them a straight ç
fight. Lower states of ignorance and egoism as typified by Dh<220>mralocana, ç
Ca<207><195>a and Mu<207><195>a, should be destroyed by sudden bursts ç
of energy and rough handling. More crafty states which result in endless ç
multiplication of desires†that is what Raktab<200>ja signifies† should ç
be tactfully handled by going to the root, by suppressing them as ç
soon as they arise. `Enlightened egoism,' if one can use such an expression, ç
which is egoism all the same, needs a straight fight. It may be a ç
long drawn fight and Dev<200>'s grace is absolutely necessary for ç
success.
Aspects of Durg<193> mentioned in the Pur<193><207>as and °gamas are ç
legion. For instance: <185>ailaputr<200>, K<220><218>m<193><207><195><193>, ç
K<193>ty<193>-yan<200>, K<218>ema<209>kar<200>, Harasiddhi<199>, Vana-durg<193>, ç
Vindhyav<193>sin<200>, Jayadurg<193> and so on. They are of greater ç
interest in icono-graphy and to the supplicants who can get different ç
types of desires fulfilled by worshipping the different aspects.
@SPACE1 = 
Images of Durg<193> can have four or eight or ten or eighteen or even ç
twenty hands. The eyes are usually three. The hair is dressed up as ç
a crown (called kara<207><195>a-muku<219>a). She is gorgeously dressed ç
with red cloth and several ornaments. Among the objects held in hand, ç
the more common ones are†conch, discus, trident, bow, arrow, sword, ç
dagger, shield, rosary, winecup and bell. She may be shown as standing ç
on a lotus or on a buffalo's head or as riding a lion.
Lion, the royal beast, her mount, represents the best in animal creation. ç
It can also represent the greed for food and hence the greed for other ç
objects of enjoyment which inevitably leads to lust. To become divine ç
(devatva) one should keepone's animal instincts under complete control. ç
This seems to be the lesson we can draw from the picture of Si<221>ha-v<193>hin<200> ç
(the rider of lion).
@SPACE = 
@NT = Durg<193>p<220>j<193> or Durgotsava
@N1 = (`worship of Durg<193>', `festival of Durg<193>')
@SPACE = 
The  worship  of  <$IGod>God  as  <$ISakti><185>akti (Supreme Power) ç
and as Dev<200> (Divine <$IMother>Mother, <$IMother>Mother of the ç
Universe) is as old as the <$IRgveda><184>gveda itself. Over the ç
centuries it has grown into a formidable cult with its own philosophy, ç
<$IMyth>myths and <$IRitual>rituals. TheDurg<193>p<220>j<193> is ç
undoubtedly the most important  festival  of  this  religious tradition.
As in the case of many other important <$IVrata/s>vratas and <$IUtsava>utsavas, ç
the <$IDurgotsava>Durgotsava is both <$INitya>nitya (compulsory) and ç
<$IKamya>k<193>mya (optional). It may be performed for nine days or ç
just three days (from <$IAsvayuja>°·vayuja ·ukla <$ISaptami>saptam<200> ç
to navam<200><|>). Those who want to celebrate it just for a day, can ç
do so either on the <$IAstami>a<218><219>am<200> or on the <$INavami>navam<200> ç
day.
@SPACE1 = 
It is interesting to note that the various <$IGod>gods of the <$IHindu/s>Hindu ç
pantheon, including Vi<218><207>u, are described as going to sleep ç
for a period of four months (<$IAsadha>°<218><193><195>ha to <$IKartika>K<193>rtt<200>ka). ç
That the rainy <$ISeason>season spread over this four-month period ç
gave little scope to movement and activity or that the <$ISun>sun ç
gave very little light to the <$IVedic>Vedic <$IAryans>°ryans living ç
the northern latitudes, may have been the origin of this <$IMyth>myth.
Be that as it may, since <$IMother>Mother <$IDurga>Durg<193> who goes ç
to bed on <$IAsadha>°<218><193><195>ha ·ukla a<218><219>am<200>, is ç
still sleeping at the time the <$IDurgotsava>Durgotsava is planned ç
to be celebrated, she has to be woken up first! This is called <$IBodhana>`bodhana' ç
and is done on the evening of <$IAsvayuja>°·vayuja ·ukla <$ISasthi><218>a<218><219>h<200>. ç
A gha<219>a or kala·a (a pot with water containing sandalwood paste, ç
<$IDurva>d<220>rv<193> grass, leaves of five trees like mango, clay ç
from seven places, fruit etc.) is established under a <$Ibilva>bilva ç
tree (Aegle marmelos), the <$IMantra>mantras of <$Ibodhana>bodhana ç
or awakening are uttered, and the <$IBilva>bilva tree itself is worshipped ç
as <$IMother>Mother <$IDurga>Durg<193>. A second gha<219>a is also ç
established there itself. Next morning (i.e., on the <$ISaptami>saptam<200> ç
day), a small branch of that <$IBilva>bilva tree is cut, placed in ç
the second gha<219>a and ceremonially carried to the hall of worship ç
where the clay image has already been established, and kept at its ç
feet. After <$IPranapratistha>pr<193><207>aprati<218><219>h<193>, ç
a detailed worship is done to the <$IGhata>gha<219>a (in the presence ç
of the image) with sixteen <$IUpacaras>upac<193>ras, followed by <$IHoma>homa ç
(<$ISacrifice>sacrifice in a duly consecrated fire).
@SPACE1 = 
The story goes that when <$IDurga>Durg<193> (or <$IParvati>P<193>rvat<200><|>) ç
came to her <$IMother>mother's house from her husband's home, it was ç
late evening. So, she decided not to disturb her parents and spent ç
the whole night under a bilva tree near the house. The <$IRitual>ritual ç
described above is symbolic of this.
The <$IPuja>p<220>j<193>s done on the <$IAstami>a<218><219>am<200> ç
and <$INavami>navam<200> days are practically identical with the <$ISaptami>saptam<200> ç
<$IPuja>p<220>j<193>. On all the days, <$ISnana>sn<193>na or bath ç
is given to the sword or the mirror kept in front of the image reflecting ç
it. Again, on all the days, ceremonial recitation of the famous work ç
<$IDevimahatmya>Dev<200>m<193>h<193>tmya (also known as <185>r<200> ç
<$ICandi>Ca<207><195><200> and <$IDurgasaptasati>Durg<193>- sapta·at<200><|>) ç
is arranged at a suitable placein the worship hall. This recitation, ç
especially on such holy days, is considered to confer great benefits ç
on the performer of the <$IPuja>p<220>j<193>.
Part of the a·<219>am<200> <$IPuja>p<220>j<193> is the <$IKumaripuja>Kumar<200>p<220>j<193>, ç
worship of a girl-child in the age-group of 2 to 10. She should be ç
a healthy child unblemished in body and appearance. She is to be worshipped ç
as the embodiment of the Dev<200> or <$IGoddess>goddess herself.
@NID = <+><+><+>Another  important <$IRitual> ritual  is  the Sandhip<220>j<193>, ç
performed at the junction of the two <$ITithi>tithis, a<218><219>am<200> ç
and <$INavami>navam<200>. The Dev<200> along with the <$IYoginis>Yogin<200>s ç
(various emanations of the Dev<200>, 64 in all) is to be worshipped ç
then. A <$IBali>bali (<$ISacrifice>sacrifice) is also to be given.
Though animal <$ISacrifice>sacrifice has existed as part of <$IDurgapuja>Durg<193>p<220>j<193>, ç
it is relegated as t<193>masic (bad or evil), fit for people of lower ç
culture and evolution.
@SPACE1 = 
On the early morning of <$IDasami>da·am<200>, the tenth day, the <$IVisarjanapuja>visarjanap<220>j<193> ç
(worship signifying a send-off to the <$IGoddess>goddess) is done, ç
symbolically withdrawing the deity from the image into one's own heart. ç
In the evening, after a simple <$IArati><193>rati (waving of light) ç
the image is taken in a grand procession and immersed in a tank or ç
a river or the sea. Much revelry is seen during the procession and ç
afterwards, in the manner of the festivities of <$ISabara><185>abaras ç
(mountain tribes or barbarian tribes). In this <$ISabarotsava><185>abarotsava, ç
as it is called, all people irrespective of their social status, were ç
expected to join, probably emphasizing that all were equal before ç
the <$IMother>Mother of all.
The evening of <$IVijayadasami>Vijayada·am<200>, after the immersion ç
of the <$IDurga>Durg<193> image, is an occasion of great joy for the ç
people who meet their friends and relatives and warmly greet them.
The <$IDurgotsava>Durgotsava described till now as the biggest festival, ç
is mainly celebrated in Bengal, <$IBihar>Bihar and Assam. However, ç
now-a-days, it is being celebrated in the urban areas of almost all ç
parts of the country, thanks to the concentration of the Bengali population ç
there.
See also <MS>DURG°.<D>
@NT = Durg<193>sapta·at<200>
@N1 = (`seven hundred [verses on] Durg<193>')
See <MS>DEV®M°H°TMYA.
@NT = Durg<193><218><219>am<200>-vrata
@N1 = (`the religious vows to be observed on the eighth day [devoted ç
to the worship of the] goddess Durg<193>')
Vratas and utsavas (religious vows and celebrations) are an important ç
aspect of popular Hinduism.
The Dev<200>pur<193><207>a, a minor work, refers to a Durg<193><218><219>am<200>-vrata, ç
which has no reference to the exploits of the goddess Durg<193> like ç
the killing of Mahi<218><193>sura. It is entirely different from the ç
Durg<193>p<220>j<193> or Durgotsava.
@SPACE1 = 
It is observed on the ·ukla a<218><219>am<200> days only, for one ç
year, beginning from <185>r<193>va<207>a-·ukla-a<218><219>am<200> ç
(the eighth day in the bright fortnight of the month of <185>r<193>va<207>a, ç
usually in July/August). Feeding of virgins and br<193>hma<207>as, ç
apart from a worship of Durg<193>, is an important item of this vrata.
@NT = Durg<193>s<220>kta
@N1 = (`hymn in praise of Durg<193>')
@SPACE = 
@SPACE = 
This is a short, but well-known and popular Vedic s<220>kta. There ç
are only seven mantras. These mantras, though forming a part of the ç
Mah<193>n<193>r<193>ya<207>a Upani<218>ad (2.1-7), are spread over ç
in the <184>gveda, the Taittir<200>ya Sa<221>hit<193> and the ç
Taittir<200>ya Br<193>hma<207>a.
Out of the seven mantras only the second concerns Durg<193>. The seventh ç
is a prayer addressed to Indra. The other five are related to Agni. ç
Yet, tradition has considered all the mantras as one unit and called ç
them Durg<193>s<220>kta.
Its recitation is specially recommended for overcoming the difficulties ç
in life. It is believed that Durg<193> (the Divine Mother) and Agni ç
(the deity of fire) protect us from internal and external enemies.
The following is a brief summary of the hymn:
May we extract the soma juice in order to offer as oblation to J<193>tavedas, ç
Agni who is all knowing. May he destroy our enemies. May he take us ç
across all perils even as a ship takes us across the sea. May he also ç
protect us from all wrongs.
I take refuge in her, the goddess Durg<193>, who is lustrous like ç
fire, who is radiating power through her tapas (austerity), who belongs ç
to Param<193>tm<193> or the Supreme God and who is worshipped by the ç
votaries through various rites to get their fruits. Our salutations ç
to you who is skilled in taking us across the ocean of sa<221>s<193>ra.
O Agni! You are worthy of praise. Through auspicious means take us ç
beyond all difficulties, to the other shore. May our home-town and ç
home-land become extensive and may the plot of agricultural land also ç
be ample. Further, may you be pleased to bless our children and grandchildren ç
with joy.
@SPACE1 = 
O Agni! You destroy all our sins and take us beyond all troubles. ç
You protect us just as one who takes a person across the sea by a ç
ship. O Fire-god! Guard our bodies and be mindful of its safety like ç
the sage Atri who always prayed mentally (for the good of all).
We invoke from the highest place of assembly, Agni (the Fire-god) ç
who is the conqueror of enemies, the charger of foes, and who is fierce. ç
May he, the Fire-god, take us across all our difficulties and wrongs, ç
and all that is perishable, and protect us.
You are lauded in sacrifices. You increase our happiness. You are ç
seated in the sacrificial place as ancient and modern sacrificer. ç
O Agni, be pleased to make us happy, we who are your own selves. Grant ç
us good fortune from all sides.
O Indra! You are unconnected (with sin and sorrow). You pervade (all ç
sacrifices). (Desirous of good fortune) comprising cattle and overflowing ç
(with the current of immortal bliss), may we serve you. May the gods ç
who dwell in the highest region of heaven delight me†practising loving ç
adoration of Vi<218><207>u†here on earth by granting my wish.
In some of the readings, a G<193>yatr<200>-mantra of Durg<193> is ç
added thus:
k<193>ty<193>yan<193>ya vidmahe<F49W1>e<F255MI> kanyakum<193>ri dh<200>mahi<F49P12W1>e<F255P255MI> ç
tanno durgi<199> pracoday<193>t<F49P12W1>f<F255P255MI>
Its meaning is: We know K<193>ty<193>yan<200> (daughter of the sage ç
Katy<193>yana). We meditate upon Kany<193>kum<193>ri! May she, Durg<193>, ç
impel our understanding in the right direction!
@NT = Durg<193> Temple
@N1 = (of Aiho<202>e)
One of the more ancient group of temples, built out of stone and preserved ç
as archaeological monuments is at Aiho<202>e, a small town in the ç
Bijapur district of northern Karnataka. The Durg<193> temple is a ç
major building of this group. The temple derives its name because ç
it is situated inside a structure that resembles a `durga' or fort ç
and not because it is dedicated to the goddess Durg<193>. It is ç
assigned to the period <MS>A.<|>D.<D> 600 and is of the C<193><202>ukyan ç
style.  The  apsidal  plinth  resembles Buddhist caitya in architectural ç
style. The vim<193>na (tower above the main shrine) is of the n<193>gara ç
type. (See <MS>N°GARA<D> for details.)
There is no image of any deity insidethe sanctum. There is a passage ç
round it meant for pradak<218>i<207><193> or circumambulation.
The pillars carrying the roof are rectangular in shape and are of ç
a very simple design. The relief figures etched on the outer walls ç
and on the pillars in the front include: R<193>m<193> and S<200>t<193> ç
seated in a boat navigated by Guha, <185>iva riding his bull (Nandi), ç
Vi<218><207>u, Narasi<221>ha, Var<193>ha,  Durg<193>,  Garu<195>a,  Ga<207>g<193>  and ç
Yamun<193>.
There is reason to believe that it was a Vai<218><207>ava temple.
The stone inscriptions discovered here do not give any significant ç
details or information about the temple and its builders.
See also <MS>AIHO<170>E.<D>
@NT = Durgotsava
See <MS>DURG°P<188>J°.<D>
@NT = d<220>roha<207>a
@EMERGENCY = In yaj<210>as and y<193>gas (sacrifices), Vedic mantras ç
are invariably recited. There are specific rules guiding their recitation. ç
These include not only the modes of intonation but also of repetition. ç
One such is the d<220>roha<207>a method mentioned by the commentary ç
(of Devasv<193>min) on the °·val<193>yana <185>rautas<220>tras (8.2.12 ç
and 13). According to this mode, while chanting a mantra the following ç
should be the order:
@NID = ascending<R>ç
order :
@IN5K = First p<193>da, half verse and then three p<193>das at a stretch, ç
followed by a pause.
@NID = descending<R>ç
order:
@IN5K = Three p<193>das, half verse, p<193>da and then the entire ç
verse without a pause.
@NT = d<220>rv<193>
@N1 = (`that which destroys [sin]')
@EMERGENCY = D<220>rv<193> (Cynodon dactylon), a common variety ç
of grass found all over India, has been considered as sacred and fit ç
to be used in worship and other religious rites. After taking bath ç
in a river or a tank, a little of this grass, with a small quantity ç
of mud is placed on the head and some mantras (vide Mah<193>n<193>r<193>ya<207>a ç
Upani<218>ad 1.34 and 35) are repeated as an act of purification. ç
In these mantras d<220>rv<193> has been praised as a deity.
When d<220>rv<193> grows tall, it is called `darbha'. Rings made of ç
darbha are tied to the ring-finger at the commencement of many a religious ç
rite. It is then called `pavitra', `that which `sanctifies'.
D<220>rv<193>, considered as dear to the deity Ga<207>apati, is extensively ç
used in his worship.
The works on °yurveda sometimes mention three varieties of D<220>rv<193>: ç
n<200>lad<220>rv<193>, ·vetad<220>rv<193>, and ga<207><195>ad<220>rv<193>. ç
Several medicinal properties are attributed to them. As such it is ç
an appetiser, an analgesic, a purifier of blood, a remedy for skin ç
troubles and a cure for diarrhoea.
@NT = Durv<193>sas
@N1 = (`[One who is] difficult to live with')
If there was one sage in the entire mythological literature of Hinduism ç
who was the very embodiment of anger and the propensity for cursing, ç
it was Durv<193>sas. For this very nature of his, he was a difficult ç
(= dur) man to live with (= v<193>sa). However, when pleased, he was ç
capable of bestowing great boons too.
He was the third son of the sage Atri and his wife Anas<220>y<193>, ç
the paragon of wifely virtues, born as a partial incarnation of <185>iva.
He is sometimes described as the human personification of <185>iva's ç
arrow that destroyed Tripuras or the Three cities of the demons who ç
were the sons of T<193>rak<193>sura.
His exploits and feats range from the sublime to the not-so-sublime ç
levels. They can be summarised as follows:
@SPACE1 = 
(1) Pleased with the maiden Kunt<200>, the daughter of the king Kuntibhoja, ç
for her devoted service, he gave her a mantra with the help of which ç
she could invite any deity and get a son from his grace. The five ç
P<193><207><195>avas and Kar<207>a were born by the power of this ç
mantra.
(2) As per his direction, K<216><218><207>a smeared his body (except ç
the feet) with the remnants of the p<193>yasa (pudding) eaten by the ç
sage. This made his body (except the soles of his feet) invulnerable ç
to weapons.
(3)<+>He  completed  the  half-done sacrifice of the king <185>vetaki ç
and enabled him to ascend to heaven.
(4)<+>He tried to harm the P<193><207><195>avas (when they were in ç
the forest) at the behest of Duryodhana but was made to flee by the ç
divine intervention of K<216><218><207>a.
(5)<+>His unjustified anger against the virtuous king Ambar<200><218>a ç
created a real crisis in his own life. He had to run for cover, being ç
relentlessly pursued by the Sudar·ana-cakra (the discus-weapon of ç
Lord Vi<218><207>u). He was ultimately rescued by the king himself!
(6)<+>He  was  responsible  for  the banishment and subsequent demise ç
of Lak<218>ma<207>a by forcing him to go against R<193>ma's command.
@NT = Duryodhana
It was the villainy of Duryodhana (also known as Suyodhana), the personification ç
of greed and jealousy, and the inordinate attachment of Dh<216>tar<193><218><219>ra, ç
his blind father, that led to the tragic war of Kuruk<218>etra, resulting ç
in the total extirpation of the Kaurava race.
At the time of his birth there were numerous ill-omens that made many ç
a sane well-wisher of the Kuru-P<193><207><195>ava race, exhort Dh<216>tar<193><218><219>ra ç
to abandon this evil boy. But the blind infatuation of this sightless ç
father made him to ignore theirwise counsels, ultimately leading ç
to disastrous consequences.
The Kaurava and the P<193><207><195>ava princes underwent their training ç
and education, first under K<216>p<193>c<193>rya and then under Dro<207><193>c<193>rya. ç
The brilliance and the remarkable progress of the P<193><207><195>avas ç
roused  the  envy  and  the  hatred  of Duryodhana to such an extent ç
that he tried his best to eliminate them by abominable means such ç
as poisoning and arson. But none of his tricks worked, thanks to the ç
timely intervention of Vidura and other well-wishers of the P<193><207><195>avas.
When the P<193><207><195>avas along with their newly wed wife Draupad<200>, ç
were given half the kingdom and they started ruling from their capital ç
Indraprastha, their popularity and prosperity further fuelled his ç
fire ofjealousy. He invited Yudhi<218><219>hira for gambling through ç
a game of dice. Since the latter had a great weakness for it he readily ç
consented, but was easily vanquished by the crafty <185>akuni, the ç
uncle of Duryodhana, who had substituted for him. The result was an ç
utter debacle for the P<193><207><195>avas who lost everything. Taking ç
this as an opportunity, Du··<193>sana, the second of the Kauravas ç
tried to molest and disrobe the P<193><207><195>ava queen Draupa<195><200>, ç
whose honour was saved by the divine intervention of <185>r<200> K<216><218><207>a. ç
Dh<216>tar<193><218><219>ra then gave them back their kingdom and ç
they returned to Indraprastha.
@SPACE1 = 
Duryodhana contrived with <185>akuni to have a second round of the ç
game of dice with Yudhi<218><219>hira. The latter lost in it his kingdom ç
and was banished for a period of thirteen years. The first twelve ç
years were to be spent in a forest and the last year incognito. If ç
found out during that period, they had to repeat it all over, once ç
again. Duryodhana tried hard to find them out and mounted an attack ç
against them, then living in the capital of the king Vir<193><219>a. ç
But, he tasted a humiliating defeat. By this time,the P<193><207><195>avas ç
had completed their thirteenth year too.
When they demanded their kingdom back, Duryodhana flatly refused, ç
saying that he would not yield even as much land as would be covered ç
by the point of a needle. K<216><218><207>a's last ditch efforts too, ç
for peace, failed. Duryodhana's attempt to capture and imprison K<216><218><207>a ç
was nullified by the latter's yogic powers.
In the ensuing war, Duryodhana lost his all and ultimately died in ç
a duel with Bh<200>ma.
@NT = Du··<193>sana
@N1 = (`One who is difficult to<R>ç
control')
Born as the second son of Dh<216>tar<193><218><219>ra and G<193>ndh<193>r<200>, ç
Du··<193>sana was next to Duryodhana in age but worse in vulgarity ç
and vileness. He laid the foundation for the Kuruk<218>etra war by<|>dragging ç
the princess Draupad<200> to the open court and dis- honouring her, ç
after the first game of dice.
He was defeated in his combats with the heroes in the P<193><207><195>ava ç
army several times. Arjuna, Abhimanyu and S<193>tyaki had that privilege. ç
He was finally killed in his combat with Bh<200>ma.
@NT = Du<218>yanta
One of the famous couples in Hindumythology who have attracted the ç
attention of writers in Sanskrit literature is Du<218>yanta and <185>akuntal<193>.
Du<218>yanta was the son of Ilila and a scion of the famous Candra ç
Va<221>·a. His first wife was L<193>k<218>i or Lak<218>a<207><193>.
When Du<218>yanta went to the forest for hunting, he chanced to meet ç
<185>akuntal<193> (the daughter of Menak<193> from the sage Vi·v<193>mitra) ç
in the hermitage of the sage Ka<207>va. They fell in love with each ç
other and married by the g<193>ndharva rite. Du<218>yanta left, promising ç
to come again and take her to his place. He did not turn up even after ç
five years. Hence the sage Ka<207>va, the foster-father of <185>akuntal<193>, ç
took her, along with her child Sarvadamana-Bharata, to the king. Due ç
to a curse the king had forgotten the whole affair and hence refused ç
to accept <185>akuntal<193>. However there was an `<193>k<193>·a v<193><207><200>' ç
(voice from the void) confirming <185>akuntal<193>'s statement thereby ç
making the king accept her.
Bharata succeeded him to the throne. It was his extraordinary greatness ç
that made this country (India) go by his name as `Bharatakha<207><195>a' ç
or `Bharatavar<218>a'
K<193>lid<193>sa's famous work Abhij<210><193>na-<185><193>kuntalam ç
is based on this story of Du<218>yanta.
See also <MS><185>AKUNTAL°.
@NT = Dv<193>da·<193>ha
@N1 = (`[a sacrifice extending over] twelve days')
The Dv<193>da·<193>ha is a Vedic sacrifice belonging to the Somay<193>ga ç
group. It is called so since it extends over twelve (=dv<193>da·a) ç
days. It can be either an ah<200>na (spread over several days) or ç
a sattra (where the yajam<193>nas themselves are the priests too).
It comprises Da·<193>ha (ten principle days) preceded and followed ç
by an Atir<193>tra. (See <MS>ATIR°TRA.<D>) The Da·<193>ha again has ç
a few minor Soma sacrifices like the P<216><218><219>hya and the Ukthya. ç
The details are too many and complicated.
See also <MS>VEDIC SACRIFICES.<D>
@NT = dv<193>da·<200>
@N1 = (`the twelfth day')
Among the Hindu festivals and sacred days†which  are  generally  celebrated ç
according to the c<193>ndram<193>na or lunar calendar†ek<193>da·<200>  and  dv<193>da·<200>  (the ç
eleventh and the twelfth days) are the more common ones, ceremonially ç
observed.
Dv<193>da·<200> is the day following ek<193>da·<200> and hence known ç
for p<193>ra<207><193>, ceremonial breaking of the fast, which includes ç
worship of Vi<218><207>u, celibacy, avoiding a second meal as also ç
non-vegetarian food. Some of the pur<193><207>as specially mention ç
eight kinds of dv<193>da·<200>s like Jay<193>, Vijay<193>, Jayant<200> ç
and P<193>pan<193>·in<200>, associated with certain nak<218>atras ç
(asterisms). Fasting is enjoined for these days also.
One of the most well-known festivals that falls on a dv<193>da·<200> ç
is the Utth<193>na-dv<193>da·<200> (K<193>rtt<200>ka ·ukla dv<193>da·<200><|>). ç
On this day Lord Vi<218><207>u who had gone to sleep on the <185>ayan<200> ç
day (°<218><193><195>ha ·ukla ek<193>da·<200><|>), gets up. Hence it ç
is called `Utth<193>nadv<193>da·<200> (utth<193>na = getting up).
It is again on this day that Tulas<200> or V<216>nd<193> was married ç
to Hari or Vi<218><207>u. So, it is also called `Tulas<200>viv<193>ha ç
day.' Ceremonial marriage of the Tulas<200> plant (holy basil) with ç
Lord Hari is performed on this day. In some houses images of Hari ç
and Tulas<200> are kept for three days (from the navam<200> to ek<193>da·<200>) ç
and worshipped. They are married on the dv<193>da·<200> day.
Vaiku<207><219>ha-dv<193>da·<200> or Mukko<219>i-dv<193>da·<200> is ç
another festival observed in the South. It is the next day of Vaiku<207><219>ha ç
Ek<193>da·<200>. Details of the festival are the same as for the Ek<193>da·<200>.
@SPACE = 
@NT = Dvaip<193>yana
@N1 = (`one [who was born] in a dv<200>pa or island')
The sage Vy<193>sa, who collected and edited the Vedic hymns, was ç
known as K<216><218><207>advaip<193>yana, since he was dark in colour ç
(K<216><218><207>a = dark) and was born on a dv<200>pa or island. ç
See <MS>VY°SA<D> for details.
@SPACE = 
@NT = dvaita
@N1 = (`dualism')
Any school of Hindu philosophy whichbelieves that the ultimate Reality ç
is not one but many, can be called `dvaita'. The chief system of dvaita ç
is the Dvaita Ved<193>nta Dar·ana propagated by Madhv<193>c<193>rya ç
(<MS>A.<|>D.<D> 1238-1317). The other schools are:
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(.3333,.3333,E1), ç
ABOVE(.0417), BELOW(.0417), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
, Vi·i<218><219><193>dvaita of R<193>m<193>nuja, +
, , (<MS>A.<|>D.<D> 1017-1137)
, Dvait<193>dvaita of Nimb<193>rka, +
, , (13th<|>century <MS>A.D.<D>)
, <185>aiva-vi·i<218><219><193>dvaita of <185>r<200>ka<207><219>ha, ç
+
, , (<MS>A.<|>D.<D> 1270)
, Acintyabhed<193>bheda of Baladeva, +
, , (<MS>A.<|>D.<D> 1725)
@Z_TBL_END = 
@SPACE = 
@NT = Dvait<193>dvaita
@N1 = (of Nimb<193>rka)
@SPACE = 
Nimb<193>rka lived in the latter half of the 12th century. His Dvait<193>dvaita ç
is very similar to the Bhed<193>bheda of Bh<193>skara. However, being ç
a firm believer in Brahman with form and attributes and the path of ç
devotion, his philosophy is more akin to that of R<193>m<193>nuja.
Nimb<193>rka's main work is Ved<193>nta-p<193>rij<193>tasaurabha ç
which is his commentary on the Brahmas<220>tras. It is rather brief ç
but lucid, since he avoids the dialectical methods or a flowery style.
According to him there are three equally real and co-eternal tattvas ç
or principles: Brahman, cit and acit. While Brahman is the controller ç
or niyant<216>, cit (the sentient being, the j<200>va or the soul) ç
is the enjoyer, bhokt<216>, and acit (the insentient nature, prak<216>ti) ç
is the enjoyed, bhogya.
Acit is of three kinds: pr<193>k<216>ta or what is derived from prak<216>ti ç
or primal matter; apr<193>k<216>ta or what is not derived from prak<216>ti, ç
but derived from a non- material substance of which the world of Brahman ç
is made and, k<193>la or time.
They are different from one another in their svar<220>pa or nature. ç
But the cit and  the  acit  are  paratantra-tattvas, dependent realities.
Nimb<193>rka adopts the view that the bheda (difference) and the abheda ç
(non-difference) are both equally real. They coexist but do not contradict ç
each other. It is something like the relationship between the sea ç
and its waves or the sun and its rays. Cit and acit, the souls and ç
the universe, exist in Brahman from all eternity and never get separated ç
from him whether in the causal state or when manifested.
They retain their individuality even during salvation, or dissolution ç
of the universe.
@SPACE1 = 
Brahman is personal, possesses a celestial body full of exquisite ç
beauty and grace. Nimb<193>rka identifies him with K<216><218><207>a ç
and posits R<193>dh<193> as his <185>akti or consort even as R<193>m<193>nuja ç
accepts Lak<218>m<200> as the consort of Vi<218><207>u-N<193>r<193>ya<207>a.
Brahman is omniscient, the cause of the origin, sustenance and destruction ç
of the universe. He is all-powerful and yet all-merciful. He is gracious ç
to his devotees and helps them have a direct vision of himself.
The j<200>vas are atomic and infinite in number. Each of them is a ç
distinctive agent, a j<210><193>t<216> (knower), kart<216> (doer) ç
and bhokt<216> (enjoyer) of the karmas he does. They animate the body ç
they live in, even as a small lamp kept in a room lights up the whole ç
room.
There are three destinies for the j<200>vas†naraka or hell for the ç
sinners, svarga or heaven for the virtuous and apavarga or release ç
for the enlightened ones. Apavarga is attaining the world of Brahman ç
from which there is no return.
Constant meditation on Brahman as the inmost self of the j<200>va ç
or the individual soul is the means of attaining Brahman in Brahmaloka. ç
There he has brahma-svar<220>pa-l<193>bha, becomes similar to him ç
in nature, except for the power of creation.
The other s<193>dhanas recommended are: scripture-ordained work, knowledge, ç
devotion and surrender to God, as also strict obedience to the spiritual ç
teacher.
@SPACE = 
@NT = Dvaita Ved<193>nta Dar·ana
@SPACE = 
@SB8.5 = INTRODUCTION
@SPACE = 
The Ved<193>nta-dar·ana, the last of the six well-known systems of ç
Indian philosophy, has three main branches: Advaita, Vi·i<218><219><193>dvaita ç
and Dvaita. The Dvaita Ved<193>nta system, vigorously propounded and ç
propagated by Madhva* (<MS>A.<|>D.<D> 1238-1317) is the most powerful ç
reaction to the extreme idealism of Advaita as taught by <185>a<209>kara ç
(<MS>A.D.<D> 788-820) and his followers. The division of reality into ç
two tiers viz., the vy<193>vah<193>rika (empirical) and the p<193>ram<193>rthika ç
(absolute), the doctrines of Nirvi·e<218>a-brahman (attributeless ç
Supreme Being) and mithy<193>tva (falsity) of the objective  world  as  asserted  by  the ç
Advaitins, have all received a very severe treatment at the hands ç
of the dualistic philosophers, especially Madhva.
@SB8.5 = DVAITA LITERATURE
Contrary to the general understanding, the literature on the dvaita ç
philosophy of Madhva is quite extensive. Madhva has to his credit ç
37 works in all, generally known as  Sarvam<220>lagrantha. Apart ç
from the commentaries on the ten Upani<218>ads and the Bhagavadg<200>t<193>, ç
he has left three treatises on the Brahmas<220>tras: Brahmas<220>trabh<193><218>ya, ç
A<207>ubh<193><218>ya and Anuvy<193>khy<193>na. Some of the other ç
works that may be mentioned are: a special class of literature known ç
as the T<193>tparya-nir<207>aya on the Bhagavadg<200>t<193>, the ç
Mah<193>-bh<193>rata and the Bh<193>gavata; Vi<218><207>utattva- ç
vinir<207>aya, <184>gbh<193><218>ya and M<193>y<193>v<193>da-kha<207><195>ana.
Some more important works of this school are:
@NOX = (1)
@NOKX = By Jayat<200>rtha (13th century <MS>A.<|>D.<D>):† Ny<193>yasudh<193> ç
(on the Anuvy<193>khy<193>na), Tattvaprak<193>·ik<193> (on the ç
Brahma-s<220>trabh<193><218>ya), Ny<193>yad<200>pik<193> (on the ç
G<200>t<193>-t<193>tparyanir<207>aya) and Prameya-d<200>pik<193> ç
(on the G<200>t<193>bh<193><218>ya).
@NOX = (2)
@NOKX = By Vy<193>sat<200>rtha, also known as Vy<193>sa-r<193>ya (<MS>A.<|>D.<D> ç
1447-1539):†Ny<193>y<193>m<216>ta, Tarkat<193><207><195>ava and ç
Candrik<193>.
@SPACE1 = 
@NOX = (3)
@NOKX = By R<193>ghavendra (<MS>A.<|>D.<D> 1598-1671):† Ny<193>yasudh<193>parima<202><193>.
@SPACE = 
@SPACE1 = 
@SB8.5 = PHILOSOPHY
@SPACE1 = 
@SPACE = 
Generally, the Indian systems of philosophy discuss their subject ç
under four broad categories: pram<193><207>a (means of knowledge),  prameya  (what  is  to  be ç
ascertained by the pram<193><207>as), s<193>dhan<193>s (spiritual ç
practices) and mok<218>a (liberation from transmigratory existence).
@SPACE = 
@S10 = PRAM°ØAS
@SPACE = 
Like most of the other schools, the Dvaita Ved<193>nta of Madhva, ç
accepts the three pram<193><207>as viz., pratyak<218>a (direct perception), ç
anum<193>na (inference) and ·abda, ·ruti or <193>gama (scriptural ç
testimony).  However,  it  gives  very  great importance to pratyak<218>a ç
as far as the things of this world are concerned. It never concedes ç
that this world of sensory experi- ence is mithy<193> (illusion) since ç
it has been a universal and direct experience. This direct experience ç
attains certainty due to its being illumined by the energy of the ç
j<200>va (the individual soul) called s<193>k<218><200> in this system. ç
The analogy of the snake being perceived in a rope in semi-darkness ç
cannot be extended to this world-experience since that snake never ç
existed and was only an illusory perception and hence, it was sublated ç
by the later, correct, perception of the rope. This `khy<193>ti' or ç
the theory of illusory perception has been named here as `abhinava-anyath<193>khy<193>ti' ç
(`ultra-new theory of false perception').
However, as far as the things beyond the ken of our sensory perceptions ç
and inferences based on them are concerned, the ·abda or the scripture ç
(the Veda) is our ultimate authority. It is true that the Upani<218>ads ç
contain statements which support the theory of Brahman, the Absolute, ç
being attributeless and also his being a Person (God) with infinitely ç
great and auspicious qualities. Whereas the Advaita Ved<193>nta treats ç
the former as the main import of these statements and gives a lower ç
status to Personal God in its two tier  theory  of  vy<193>vah<193>rika-satya  (the ç
empirical reality) and p<193>ram<193>rthika-satya (the absolute Reality), ç
the Dvaita Ved<193>nta of Madhva considers the latter as the main ç
import and the former as supporting the same in a round-about way. ç
The latter texts are called `upaj<200>vya' (basic) and the former ç
as `upaj<200>vaka' (dependent or expla-natory). Since the world of ç
multiplicity is a fact of universal experience, certified by the s<193>k<218><200>, ç
its denial by the upaj<200>vaka texts should be construed rather in ç
a symbolic way, as just asserting the unity of the many in the one ç
(God, the absolutely independent Reality on whom all the other categories ç
depend). This assertion of the unity must needs presuppose the many!
@S10 = PRAMEYAS
Coming to the prameyas, the following ten are the ultimate categories ç
as accepted by this system: dravya (substance), gu<207>a (quality), ç
karma (action), s<193>m<193>nya (class character), vi·e<218>a (particularity), ç
vi·i<218><219>a (the qualified), a<221>·<200> (the whole), ·akti (power), ç
s<193>d<216>·ya (similarity) and abh<193>va (negation).
Dravya or substance is the substratum of attributes and the material ç
cause of evolution of some entities like prak<216>ti and the emanation ç
in others like Brahman and the j<200>va.
Dravya,  again,  is  of  six  types: Brahman or Vi<218><207>u (God), ç
Lak<218>m<200> (Consort of God), j<200>vas (individual souls), avy<193>k<216>ta-<193>k<193>·a ç
(unmodified space), prak<216>ti (the insentient material cause) and ç
the three gu<207>as (sattva, rajas and tamas).
A more detailed treatment of these can be taken up later.
Gu<207>as are attributes. They are countless. They may be physical, ç
mental or spiritual. But they always depend on the substances they ç
qualify. God, however, is never touched by the bad gu<207>as.
Karma or action is of two kinds: pu<207>ya (meritorious) and p<193>pa ç
(sinful). They are responsible for the pleasant and the painful experiences ç
of the j<200>vas.
S<193>m<193>nya or universal is that property by which we see something ç
common in a plurality of objects, as for instance `tableness' in several ç
tables, which are all different individual pieces.
@SPACE1 = 
Vi·e<218>a (particularity), translated more often as `difference-identity' ç
by the M<193>dhva scholars, is a special contribution of Madhva to ç
the group of categories. When we say that we see a table, it also ç
means that we see it as different from the floor on which it is placed. ç
Again, we also see it as different from all other objects. There is ç
only one process of knowing involved in the perception of both the ç
entity as such and its difference from all others. This is vi·e<218>a, ç
the self-linking capacity of substances, that enables them to assimilate ç
the attributes into their very nature without obstructing the capacity ç
of the attributes to display themselves. Forinstance, a ripe mango ç
has several attributes: red colour, softness, sweet taste and a flavour ç
of its own. This substance mango is not only identified with them ç
but also different from them. Not only that, even these several attributes ç
are different from one another. This special quality of the substance, ç
of being different and  also  being  identified  with  the attributes ç
is inherent to it and is called `savi·e<218>a-abheda'.
The vi·i<218><219>a or the qualified, is the `thing-in-itsel<%20>f<%0>' ç
(vi·e<218>ya) with the qualifying adjuncts (vi·e<218>a<207>as), seen ç
together in a single perception as one. The subtraction or addition ç
of any vi·e<218>a<207>a will produce a new vi·i<218><219>a. Hence ç
the whole is something more than its parts.
A<221>·<200> is the entity that has a<221>·as or fractions or parts. ç
A cloth is an a<221>·<200> whereas its threads are its a<221>·as. ç
Incarnations of God are called `svar<220>p<193><221>·a' (a fraction ç
of potency) whereas the j<200>vas are termed as `bhinn<193><221>·a' ç
(a potency in separation).
<185>akti is the capacity or power and is said to be of four kinds: ç
Brahman's capacity beyond human comprehension, induced power as in ç
consecrated images, the super-sensory power in causes that helps them ç
to produce their effects and the power of words to produce their meanings.
@SPACE1 = 
S<193>d<216>·ya is resemblance or similarity. After seeing one cow, ç
when we see another, we see not only a new cow but also theresemblance ç
between the two. Since resemblance as such cannot reside in either ç
of the cows, it must be recognised as a separate category.
Abh<193>va or negation, though not positive, is considered as a category ç
in this system.  The  four  varieties†same  as accepted by the Ny<193>ya-Vai·e<218>ika-system† ç
are: pr<193>gabh<193>va (perception of non-existence  before  a  thing  is  produced), ç
pradhva<221>s<193>-bh<193>va  (perception  of  its absence after it ç
is destroyed), anyony<193>-bh<193>va (perception of the mutual non- ç
existence of one thing in another) and atyant<193>bh<193>va (absolute ç
non-existence). The absence of a pot before its production and after ç
its destruction is the example for the first two abh<193>vas. The ç
reciprocal negation between a jar and a cloth is the example for the ç
third. The `son of a barren woman' or the `horns of a hare' are the ç
illustrations for the last.
@SB8.5 = THEOLOGY
The doctrine of pa<210>cabhedas or five-fold differences is fundamental ç
to the dvaita philosophy of Madhva. According to this doctrine, Brahman ç
is different from the j<200>vas, and the prak<216>ti, the j<200>vas ç
are different from one another and from the prak<216>ti, and, the ç
various objects evolved out of prak<216>ti are also different from ç
one another.
@S10 = BRAHMAN OR GOD
Dvaita metaphysics divides the ultimate categories into two groups: ç
the svatantra (absolutely free Reality) and theasvatantra (the dependent ç
reality). Brahman or God alone is svatantra and all the others†Lak<218>m<200> ç
(God's consort), the j<200>vas or the individual souls and prak<216>ti ç
or nature†are asvatantra. Though God does not create them (they being ç
coeval with him) he is their absolute master and controller both from ç
within and from without.
God is personal, but has no physical body, no anthropomorphic form. ç
He is all-pervading. He is Vi<218><207>u, also called Hari, N<193>r<193>ya<207>a, ç
Puru<218>ottama, K<216><218><207>a, V<193>sudeva and by several other ç
names. He is not only the creator and destroyer of the universe but ç
also the controller in each and everyone of its aspects. He is full ç
of infinite, auspicious, attributes as described in the scriptures. ç
He is the quintessence of all perfection. No imperfection in the asvatantra ç
categories can ever touch him. M<193>y<193> is his acintya·akti (inconceivable ç
power) by which he performs all cosmic activities like creation, sustenance, ç
dissolution, control, enlightenment, obscuration, bondage and release ç
of the souls. Grace is one of the most important of his attributes ç
that helps a j<200>va devoted to him, to be redeemed. He can incarnate ç
himself as avat<193>ras. All the avat<193>ras are equal, though the ç
manifestation of his power may be different in them.
The Vedas are the only source of information about God. Though he ç
can be apprehended by them, he can never be comprehended. The authority ç
of secondary scriptures like the Mah<193>bh<193>rata and the pur<193><207>as ç
should also be accepted since they too are works of Vy<193>sa, the ç
editor of the Vedas.
@SPACE = 
@S10 = LAK<186>M®
Lak<218>m<200>, represented as the consort of Vi<218><207>u, is the ç
foremost among the conscious  entities.  Though  absolutely dependent ç
upon him, she has no bondage and is co-eval with the independent Vi<218><207>uand ç
is hence called `Sam<193>n<193>' (his equal).
Like Vi<218><207>u she is omnipresent and has no material form. But ç
she can manifest in infinite forms. Vi<218><207>u has bestowed on ç
her, his own cosmic powers, through which she can control the destinies ç
of the j<200>vas and also the modifications of prak<216>ti, the insentient ç
nature.
@S10 = J®VAS OR INDIVIDUAL SOULS
A j<200>va or an individual soul, is the centre of the I-sense which ç
is endowed with consciousness and will. It has the powers to know, ç
to act and to enjoy. It is atomic in size, but can pervade the body ç
it occupies. It is a knower with an inherent capacity to know itself ç
and others. It is a pratibimba or a reflection of Godand hence gets ç
a faint colouring of some ofhis attributes like self-luminosity and ç
bliss. However, it is ever dependent on him.
The j<200>vas are infinite in number and are all different from one ç
another as also from all the products of prak<216>ti. Each is unique. ç
Its ignorance of its real nature as the centre of consciousness, different ç
from the body-mind complex, is called `avidy<193>' and is due to the ç
will of God. It is this that has brought about its sa<221>s<193>ra ç
or transmigratory bondage.
Unlike the other systems of Ved<193>nta, the dvaita system of Madhva ç
categorises the j<200>vas into three permanent groups: mukti-yogyas ç
(those which are fit for salvation), nitya-sa<221>s<193>rins (the ç
eternally transmigrating ones) and the tamo-yogyas (the damned ones). ç
The j<200>vas of the first group are receptive to spiritual values. ç
By concentrated spiritual disciplines and the grace of God, they can ç
get salvation. Those of the second group are worldlings who delight ç
only in worldly values and feel no need for ethical and spiritual ç
life. Hence they undergo transmigration eternally. The j<200>vas of ç
the last group are positively evil by nature, go on progressively ç
degenerating, finally ending in eternal perdition.
@S10 = PRAK<184>TI OR NATURE
Prak<216>ti or nature is the ultimate source of the physical universe. ç
It is eternal but insentient. The three gu<207>as† sattva, rajas and ç
tamas†are regarded as its first products. From them emerge in succession ç
the mahat (intellect), aha<209>k<193>ra (egoism), manas (mind), the ç
indriyas (sensory organs) and the five bh<220>tas (elements like earth, ç
water etc.). This evolution of prak<216>ti is similar to that in S<193><209>khya ç
philosophy. However, being a dependent reality, it evolves, not by ç
itself but by thewill of God, who again, exercises his will as per ç
the karmas or deserts of the j<200>vas.
Since prak<216>ti is the up<193>d<193>nak<193>ra<207>a or the material ç
cause of the universe, it is necessary to describe here the dvaita ç
view about the cause and effect relationship. When a pot is produced ç
out of clay, clay is the cause (k<193>ra<207>a) and pot is the effect ç
(k<193>rya). The Ny<193>ya-Vai·e<218>ika view that the effect did ç
not exist in the cause, is called `asatk<193>ryav<193>da,' the doctrine ç
that the effect did not exist (asat) in the cause. The S<193><209>khya-Yoga ç
view, accepted by certain schools of Ved<193>nta also, is that the ç
effect (k<193>rya) pre-existed (sat) in the cause (k<193>ra<207>a) ç
though in a subtle form. This view is called `satk<193>ryav<193>da'. ç
The Dvaita Ved<193>nta however, differs from both these schools and ç
puts its own view, viz., `sad-asat-k<193>rya-v<193>da,' the doctrine ç
that the effect is both sat (existent) and asat (non-existent) though ç
not simultaneously. Before production, the pot, existed as the k<193>ra<207>a ç
or the cause but not as k<193>rya or effect. After its production ç
it existed as k<193>rya or effect, but not as k<193>ra<207>a or cause. ç
The Dvaita Ved<193>nta, however, like other doctrines, recognizes ç
the efficient cause (nimittak<193>ra<207>a) also.
@S10 = AVY°K<184>TA-°K°<185>A<|>OR<|>UNMODIFIEDSPACE
The dvaita system postulates an avy<193>k<216>ta-<193>k<193>·a or ç
unmodified space, as afundamental and permanent category, co-eval ç
with God. It is different from the bh<220>t<193>k<193>·a or elemental ç
space which is a product of prak<216>ti. This <193>k<193>·a enables ç
one to perceive dik (direction), like east and west. It exists even ç
in pralaya or dissolution. It is infinite.
@SB8.5 = MOK<186>A OR LIBERATION
A j<200>va is in sa<221>s<193>ra or bondage, due to avidy<193> or ç
ignorance induced in him by God, the absolutely independent Reality. ç
Hence it is only by the grace of God that a j<200>va can get liberation ç
from that bondage.
A j<200>va must first acquire j<210><193>na or knowledge of God†his ç
greatness and goodness†through  the  scriptures  by approaching a ç
competent guru or preceptor. <185>rava<207>a (listening to the scriptures), ç
manana (reflecting on their teachings) and dhy<193>na (meditation) ç
will induce bhakti or devotion towards God and ultimately win his ç
pras<193>da or grace. Thus it is bhakti that is the primary means ç
of salvation, in this system. The ninefold devotion that is described ç
in the Bh<193>gavata (7.5.23) is strongly recommended by Madhva ç
for liberation. Madhva does not recognise vidve<218>a-bhakti   (`hatred-devotion')   of ç
Hira<207>yaka·ipu or <185>i·up<193>la as bhakti and considers it as ç
a eulogy of concentration. He does not recommend madhura-bhakti (lustful ç
attitude towards God as by the gopis of B<216>nd<193>vana) to ordinary ç
mortals and declares it as fit only for the apsara (nymph-like) j<200>vas.
Vair<193>gya or a spirit of renunciation and purity of mind by the ç
practice of Karmayoga as described in the Bhagavad-g<200>t<193> must ç
precede the above-mentioned disciplines. Duties pertaining to one's ç
life must be continued to be performed till the end.
All this applies only to the mukti-yogya j<200>vas and not to the ç
other two varieties.
In mok<218>a, the j<200>va attains its original state of freedom and ç
bliss in accordance with its intrinsic capacity. Since no two j<200>vas ç
are identical, gradation persists even in the state of liberation.
@SPACE1 = 
After the death of the body, such a j<200>va that has qualified to ç
attain the final liberation has all of its karma destroyed, passes ç
through several subtle regions led by the <193>tiv<193>hikas or heavenly ç
guides and goes to Brahmaloka, the supreme abode of Brahm<193>, also ç
known as Hira<207>yagarbha. At the end of the kalpa or the creative ç
cycle when Brahmaloka dissolves, the j<200>va, along with Brahm<193>, ç
enters into Vaiku<207><219>ha, the abode of Vi<218><207>u, after abandoning ç
the s<220>k<218>ma·ar<200>ra or the subtle body and assuming a divine ç
body made of ·uddha-sattva (pure, untainted, sattva).
The system also posits a fourfold distinction in mok<218>a: s<193>lokya ç
(residence in the same region), s<193>m<200>pya (being near God), ç
s<193>r<220>pya (having a form similar to that of God) and s<193>yujya ç
(togetherness with him).
@SB8.5 = CONCLUSION
The contribution of the dvaita of Madhva to Indian philosophical tradition ç
is considerable. Madhva's sharp logic cuts to pieces the snobbish ç
attitude of some thinkers who consider devotion as secondary to knowledge, ç
and restores it to its rightful place. For him to love is to know ç
and to know is to love.
Though his categorisation of the j<200>vas into three groups as salvable, ç
world-bound and damnable, appears a little strange, he lifts God above ç
all the blame for the evil in the world. His theology and ethics are ç
supported by a strong epistemology. The doctrines of s<193>k<218><200>, ç
vi·e<218>a and bheda are his original contribution. He has alsosuccessfully ç
established the harmony of the Upani<218>adic thoughts with those ç
of the itih<193>sas (epics) and the pur<193><207>as (mythology).
An earnest study of his dvaita system can certainly enrich our knowledge ç
and increase our devotion to God thus making our spiritual evolution ç
much more easy.
@NT = Dv<193>parayuga
@N1 = (`the yuga [which comes] after the second; [viz., the third]')
In the Hindu Mythological lore, time is expressed in immense quantities. ç
A kalpa is a day of Brahm<193>, the creator. It is divided into 14 ç
manvantaras and also into 1000 caturyugas. The caturyugas are: K<216>tayuga, ç
Tret<193>yuga, Dv<193>parayuga and Kaliyuga. Thus, the Dv<193>parayuga ç
is the third of the four yugas. Its duration is 8,64,000 human years.
See <MS>YUGAS<D> for details.
@NT = dv<193>ra
@N1 = (`that [through which] one goes out of the [house]')
The science of building construction, architecture and town-planning ç
was well-developed in ancient and medieval India. Works like the Artha·<193>stra ç
of Kau<219>ilya (300 <MS>B.<|>C.<D>), the M<193>nas<193>ra (revised ç
edition, 11th cent. <MS>A.<|>D.<D>), Mayamata, M<193>nasoll<193>sa ç
of king Some·vara (<MS>A.<|>D.<D> 1126-1138) and various pur<193><207>as ç
like the Agnipur<193><207>a andthe Matsyapur<193><207>a contain ç
a lot of information on this subject.
Location and construction of the dv<193>ras (entrances and doors) ç
of buildings was considered as very important, not only from the standpoint ç
of safety and beauty, but also of auspiciousness.
A village or a town must have dv<193>ras in the four cardinal directions ç
and also four, in between, in the corners.
Buildings too should have four maindv<193>ras or doors on the four ç
sides. Smaller doors can be constructed as per convenience.
The main entrance door in a building should not be kept in the middle, ç
but on either side only. But, in the case of temples it should be ç
in the middle only.
The most general rule for the dimension is that the height of the ç
door should be twice the width (h = 2w).
@SPACE1 = 
The doors are generally decorated with the carvings of leaves and ç
creepers. The relief figures of Ga<207>e·a, Sarasvat<200> and other ç
deities should be there on both sides of a door.
Though it is advisable to have two shutters, the door may have a single ç
shutter also.
The  above-mentioned  works  give detailed measurements and instructions ç
for the construction of doors.
@NT = dv<193>radevat<193>
@N1 = (`door-goddess')
Along with the dikp<193>las or dikp<193>lakas (guardian deities of ç
directions), the t<193>ntrik works like the <185>r<200>vidy<193>r<207>avatantra ç
mention fifteen dv<193>radevat<193>s or gods and goddesses guarding ç
doors and doorways. Some of them are: Padm<193>, Bh<193>rat<200>, ç
Durg<193>,Manobhav<193>, Vasant<193>, Ga<209>g<193>, V<200>ra- vighne·a ç
and Dh<193>t<193>.
They guard the doors of the temples of Mother-goddess.
@NT = Dv<193>rak<193>
@N1 = (`the gateway to [liberation]')
Places of pilgrimage are legion in Hinduism. In the olden days, when ç
transport and communication were difficult, the devout  Hindu  cherished  a  life-time's ç
ambition of visiting important pilgrim centres like K<193>·<200> or ç
Pray<193>ga.
One of the seven important places of pilgrimage which every Hindu ç
liked to visit in his life, is Dv<193>rak<193> or Dv<193>rik<193>, ç
also known as `Dv<193>r<193>vat<200>'. It is situated on the sea-shore, ç
near the Okha port in Saurashtra (Gujarat).
<185>r<200> K<216><218><207>a is said to have built it. It got submerged ç
in the sea at the time of his departure from this world. 
Most of the scholars agree that the modern Dwarka along with the Bet-Dwarka ç
(an island in the sea) could have been the same Dv<193>rak<193> described ç
in the Hindu mythological works and digests.
A Vi<218><207>uk<218>etra (place dear to Lord Vi<218><207>u), Dv<193>rak<193> ç
has been highly eulogised in the Hindu religious works, especially ç
the pur<193><207>as.
The main temple is that of Dv<193>rak<193>dh<200>·a or Ra<207>cho<195>j<200> ç
(<185>r<200> K<216><218><207>a). The original temple could have been ç
built during the Gupta period (<MS>A.<|>D.<D> 320-525) and repaired ç
during the age of the Sola<209>kis (9th to 13th cent. <MS>A.<|>D.<D>). ç
It is situated on the bank of the Gomat<200> which is not a river ç
but the back-waters of the Arabian sea. The main dome or tower is ç
42 metres (140 ft.) in height. The large ma<207><195>apa (open hall) ç
has sixty pillars. There is enough space for pradak<218>i<207>a or ç
circumambulation. In the garbhamandir or sanctum there is the beautiful ç
image of K<216><218><207>a made of black stone, 90 cms (3 ft.) in ç
height, with four arms. Pilgrims are permitted to touch the feet of ç
the image and offer tulasi (holy basil) leaves.
Other images in the temple campus are those of Amb<193>, Balar<193>ma, ç
Trivikrama and Pradyumna.
There is a separate temple for <185>iva as `Ku·e·vara Mah<193>deva'.
There are nine bathing gh<193><219>s for pilgrims such as Sa<209>gama-gh<193><219>, ç
N<193>r<193>ya<207>a gh<193><219>, V<193>sudeva-gh<193><219>, Gogh<193><219> ç
and so on.
There is a small lake of salt water near one of the gh<193><219>s, ç
called `Ni<218>p<193>pa-sarovara'. A bath here has been considered ç
almost compulsory.
Other temples in Dv<193>rak<193> are those of Lak<218>m<200>n<193>r<193>ya<207>a ç
and V<193>sudeva. The temple of N<193>ge·vara-li<209>ga (<185>iva) ç
is an ancient one.
@SPACE1 = 
Pilgrims sometimes undertake what is known as `Dv<193>rak<193>pradak<218>i<207>a,' ç
circumambulation of the whole place for which a particular order is ç
prescribed.
<185>r<200> K<216><218><207>a-janm<193><218><219>am<200> is the biggest ç
festival observed in the main temple.
There is an ancient monastery†the <185><193>rad<193>p<200><219>ha†established ç
by <185>a<209>kar<193>-c<193>rya (<MS>A.<|>D.<D> 788-820) here.
@SPACE = 
@NT = dv<193>rap<193>las or dv<193>rap<193>lakas
@N1 = (`guardians of doors')
@SPACE = 
All the Hindu temples built in the traditional style have dv<193>rap<193>las ç
or door-guardians, generally at the sides of the main doorway of the ç
sanctum. Their iconographic details vary according to the sectarian ç
affiliation of the temple (<185>aiva, <185><193>kta or Vai<218><207>ava).
In Vai<218><207>ava temples there are three pairs of dv<193>rap<193>las: ç
Ca<207><195>a and Praca<207><195>a at the sides of the temple; Jaya ç
and Vijayaat the sides of the sanctum in the ardhama<207><195>apa; ç
P<220>r<207>a and Pu<218>kara at the outside enclosure. Sometimes ç
Nanda and Sunanda, as also Kumuda and Kumud<193>k<218>a are also mentioned ç
as dv<193>rap<193>las.
@SPACE1 = 
There are other deities also who too function as guardians. For instance ç
Garu<195>a, Vi<218>vaksena, °nanda, V<200>rasena and Sambhava.
In the <185>iva temples the following four-armed guardians are shown: ç
Nandi to the left and Mah<193>k<193>la to the right of the eastern ç
entrance; Vin<193>yaka and Pu<207><195>ar<200>ka at the southern entrance; ç
V<216><218>abha and Skanda at the western entrance; Dev<200> and Ca<207><195>e·vara ç
at the northern entrance.
Da<207><195>i, Mu<207><195>i, °moda, Pramoda and K<218>etrap<193>la ç
are the other deities mentioned as guardians in <185>iva temples.
In the Dev<200> temples the dv<193>rap<193>las are: Vet<193>la and ç
Kara<219>a at the eastern entrance; Pi<209>gal<193>k<218>a and Bhruku<219>a ç
at the southern entrance; Dh<220>mraka and Kukku<219>a at the western ç
entrance; Rakt<193>k<218>a and Sulocana at the northern entrance.
Sometimes certain goddesses like <186>a<218><219>i, Kum<193>r<200>, ç
Dhanad<193>, Acal<193> and others are also projected as dv<193>ram<193>t<216>k<193>s ç
or guardian deities of entrances.
For temples of other deities like K<193>rttikeya and Ga<207>e·a, the ç
dv<193>rap<193>las will be different.
@NT = dvayamantra
@N1 = (`mantra in two parts')
@SPACE1 = 
In <185>r<200>vai<218><207>avism†the practical religious aspect of ç
Vi·i<218><219><193>dvaita Ved<193>nta† prapatti or ·ara<207><193>gati ç
(total surrender to God) is a very important step of spiritual practice.
In prapatti, one has to receive three mantras or sacred formulae from ç
a compe-tent <193>c<193>rya (spiritual preceptor). The first is the ç
a<218><219><193>k<218>ar<200>mantra (the eight-syllabled mantra) viz., ç
o<221> namo n<193>r<193>ya<207><193>ya. The second is the dvaya ç
or dvayamantra, a twofold mantra. The third is the carama·loka, the ç
66th ·loka of the 18th chapter of the Bhagavadg<200>t<193> (`sarva-dharm<193>n ç
parityajya...').
The dvayamantra is:
1.
@NK = ·r<200>man-n<193>r<193>ya<207>a-cara<207>au<R>ç
·ara<207>a<221> prapadye<F49P11W1>e<F255P255D>
2.
@NK = ·r<200>mate n<193>r<193>ya<207><193>ya nama<199><F49P11W1>e<F255P255D>
The first mantra means: `I take refuge at the feet of <185>r<200>-n<193>r<193>ya<207>a'.
The second one means: `Obeisance to <185>r<200>-n<193>r<193>ya<207>a.'
In both the mantras N<193>r<193>ya<207>a is described as being with ç
<185>r<200> or Lak<218>m<200>.
Though the commentators declare that these mantras are part of the ç
Ka<219>ha·ruti, the recensions available now do not contain them.
This dvayamantra is called `mantra-ratna' and is considered a t<193>ntrik ç
mantra. Hence all have the right to receive it for spiritual evolution.
See also <MS>RAHASYATRAYAS°RA<D>.
@NT = dve<218>a
@N1 = (`[that which causes] repulsion, hatred or dislike')
Hinduism has always stressed the cultivation of moral and ethical ç
virtues in the life of every individual since they conduce to happiness ç
in personal life and peace in social life. Just as there are virtues ç
to be assiduously cultivated, there are vices too, to be avoided and ç
eliminated. One such vice that is classed among the ari<218>a<195>vargas ç
or the six enemies of every human being, is dve<218>a or hatred. Droha ç
(desire to harm), krodha (anger) and amar<218>a (intolerance) are ç
its different forms and manifestations.
It has been defined variously by the different philosophical systems. ç
The Ny<193>yasystem considers it as one of the characteristics of ç
the <193>tman (the j<200>va or soul) since it experiences the same, ç
in the state of bondage. It is the desire to give up that which causes ç
du<199>kha, sorrow and suffering. The Yogas<220>tras (2.8) of Pata<210>jali ç
(200 <MS>B.<|>C.<D>) describes it as the residue in the mind after ç
experiencing pain and suffering. Dve<218>a is similar to fire since ç
it burns, as it were, our mind.
Dve<218>a can be eliminated by removing the cause of dve<218>a. However, ç
viveka or discrimination in the mind, that pinpoints the evil effects ç
of dve<218>a on oneself, is a good method for eliminating it. So also, ç
trying to see God in everyone and the hand of God in the happenings ç
that bring us suffering, to reform and transform us, can be of great ç
help.
See also <MS>R°GA.<D>
@NT = dvibha<209>ga
@N1 = (`bent in two places')
Images of gods and minor deities associated with them, especially ç
in the standing posture may be sabha<209>ga (with bends) or abha<209>ga ç
(without bends). An image which is dvibha<209>ga is bent in two places, ç
one at the loins and the other at the neck. It is usual to show the ç
images of goddesses in this posture, especially when they are with ç
consorts and in the standing pose.
@NT = dvija
@N1 = (`one [who is] born twice')
Persons belonging to the first three var<207>as or castes are called ç
`dvijas'. Literally, the word means `One who is born a second time ç
or twice-born'.
The first birth is the physical birth from the womb of the mother. ç
The second is the spiritual birth brought about by the sacrament of ç
upanayana. Hence all those who have undergone the upanayana ceremony†the ç
br<193>hma<207>as, the k<218>attriyas and the vai·yas†are `dvijas'. ç
However, in practice the term is more generally applied to the br<193>hma<207>as.
The br<193>hma<207>as of Vedic learning are called `vipras' and the ç
vipras with an excellent conduct are known as `·rotriyas'.
See also <MS>UPANAYANA.<D>
@NT = dv<200>pa
@N1 = (`island')
According to the ancient geography as depicted in some pur<193><207>as ç
like the Vi<218><207>upur<193><207>a (2.2) this world (or earth) ç
comprises seven dv<200>pas or continents, each surrounded by an ocean.
Bh<193>ratavar<218>a (India) is in the first continent called Jamb<220>dv<200>pa.
See <MS>SAPTADV®PA<D> for details.
@NT = dvit<193>la
@N1 = (`[measuring] two t<193>las')
In the m<220>rti·ilpa·<193>stra or iconography, all the measurements ç
are based on t<193>la (measurement of the length of the face, which ç
is equal to the span) as the basic unit. The images and associated ç
figures are to be made as per this t<193>lam<193>na system.
The measurement of dvit<193>la (two t<193>las or spans, equal to 24 ç
a<209>gulas) is adopted while preparing the images of birds like swan, ç
dwarfish spirits such as K<220><218>m<193><207><195>a and for the ç
Matsy<193>vat<193>ra of Vi<218><207>u.
See <MS>T°LAM°NA SYSTEM<D> for details.
@NT = dvived<200>
@N1 = (`one [who has studied]<R>ç
two Vedas')
Started perhaps as the academic title of a person who has studied ç
two Vedas (dvi= two) it gradually became the family title of persons ç
born as his descendants.
Similarly is the evolution of the two other titles trived<200> and ç
caturved<200>†for those who are the scions of the persons who had ç
mastered three or four Vedas.
Study of one Veda was the minimum expected of every dvija or the twice-born.
@SPACE = 
@NT = dvya<207>uka
@N1 = (`of two atoms')
Creation of this world is a topic that is invariably discussed in ç
the dar·anas orsystems of Indian philosophy. The Vai·e<218>ika dar·ana ç
of Ka<207><193>da accepts param<193><207>us or atoms of earth, water, ç
fire and air as the four fundamental substances from which this physical ç
universe evolves.
Impelled  by  the  karma  of  the unredeemed j<200>vas or individual ç
souls, at the beginning of the creation, two param<193><207>us are ç
united forming a `dvya<207>uka'. Three such dvya<207>ukas join together ç
making a `trya<207>uka'. This process goes on till the entire physical ç
world is finally created. (vide Brahmas<220>tras 2.2.11 and <185>a<209>kara's ç
commentary on the same.)
See also <MS>VAI<185>E<186>IKA-DAR<185>ANA.
@SPACE = 
@NT = dyaus
@N1 = (`that which shines')
@SPACE = 
Derived from the root `div' (= to shine) the word `dyaus' or `dyo' ç
represents heaven, the region of light. It is sometimes treated as ç
a deity, as the father of both gods and human beings. P<216>thv<200> ç
is considered as the mother. Hence the use of the word `dy<193>v<193>p<216>thiv<200>' ç
as the parents of all beings. These divine parents are invoked to ç
give their worshippers rains, food, wealth and success in life.
@NT = dy<193>v<193>p<216>thiv<200>
See <MS>DYAUS.
@NT = Dyumatsena
Princess S<193>vitr<200> has been highly eulogised in the Hindu mythological ç
lore as an ideal wife, nay, the very personification of wifely virtues ç
like chastity and singular devotion to the husband. Satyav<193>n was ç
her fortunate husband.
Dyumatsena, the king of the S<193><202>va country was his father. ç
Though he was devoted to dharma and ruled well, he lost his eyesight ç
and was conquered by a rival king who drove him out of his kingdom. ç
He lived in a forest along with his wife and son Satyav<193>n. Princess ç
S<193>vitr<200> chose to marry Satyav<193>n even though she was apprised ç
that he would die very soon.
Dyumatsena regained his eyesight and the kingdom due to S<193>vitr<200>'s ç
prayer to Yama, the god of death.
See also <MS>S°VITR®.
@SPACE = 
@NT = dy<220>ta
@N1 = (`gambling')
@SPACE = 
Gambling with dice play seems to be an ancient pastime, especially ç
for kings. The <184>gveda (10.34) contains the piteous laments of ç
a gambler. The notorious game of dice between Yudhi<218><219>hira ç
and <185>akuni (on behalf of Duryodhana) described in the Mah<193>bh<193>rata ç
is now history, as the root-cause of the Kuruk<218>etra war. In the ç
pur<193><207>as and the dharma·<193>stras there are statements  of  condemnation  of  the ç
gambling with dice-play. At the same timerules to regulate it too ç
have been described! It was perhaps necessary to control it since ç
it existed as an unavoidable evil.
The dice pieces are made of vibh<200>taka wood (a kind of myrobalan).
The game has to be conducted in a public place supervised by a sabhika ç
(who gives the place and collects some rent for it) and some expert ç
gamblers, who will act as umpires. The defeated person has to pay ç
a part of his loss to the king as tax which may be 5 to 10 per cent. ç
It is the duty of the sabhika or the agents of the king to see that ç
the stake money is paid by the losing party to the victor. Incircumstances ç
where the loser loses everything, becoming a beggar, the king prevents ç
it by providing for the bare maintenance of the loser.
The kings used to permit gambling centres as one of the methods for ç
finding out thieves and criminals.
An arranged dice-play is a ritual part of the R<193>jas<220>ya sacrifice.
@NT = Dy<220>tapratipad<193>
See <MS>BALIPRATIPAD°<D> and <MS>DY<188>TA.
@END = <R>ç

