<185>r<200> K<216><218><207>a has used the word `yoga' in several ç
senses. For instance, it is Karmayoga that is meant in 2.48, 50 and ç
6.2. However, in 6.12 and 15 it is R<193>jayoga that is indicated. ç
In 5.8 the word `yukta' has been used to signify the j<210><193>nayogi. ç
Again, it is the bhaktiyogi that is implied by the word `nityayukta' ç
in 8.14.
Keeping in mind the fact that <185>r<200> K<216><218><207>a has taught ç
all the four yogas to one and the same person, Arjuna, urging him ç
to follow them, it can be safely concluded that the yoga of the G<200>t<193> ç
is a comprehensive spiritual discipline integra-ting into itself all ç
the four aspects. However,  since  Arjuna's  svabh<193>va  or nature ç
was such that Karmayoga was better suited to him, <185>r<200> K<216><218><207>a ç
relentlessly urges him to fight (2.18; 3.30; 11.34).
The inference is obvious: The G<200>t<193> urges an aspirant to ç
practise a balanced combination of all the four yogas, keeping that ç
yoga which suits one's nature better, as the main discipline and adding ç
the others too in right proportion. Since no human being has only ç
one of the four faculties mentioned earlier, but all the four, though ç
in varying proportions, this deduction is reasonable.
@S10 = c. The Doctrine of Avat<193>ra:
The doctrine of avat<193>ra or incarnation of God is another, original ç
contribution of the G<200>t<193> to Indian philosophical and religious ç
literature. The avat<193>ra concept is perhaps <|>suggested <|>in <|>the<|> ç
<184>gveda<|> (3.53.8; 6.47.18) itself. Some of the avat<193>ras ç
mentioned in the pur<193><207>as in the lists of da·<193>vat<193>ras ç
(ten incarnations of Vi<218><207>u) are met with in the <185>atapatha ç
Br<193>hma<207>a (1.8.1.-6; 1.2.5.1). However, it is only here in ç
the G<200>t<193>, that the concept is more definite and clear.
When <185>r<200> K<216><218><207>a mentions that the yoga which he ç
taught to Vivasv<193>n (Sun-god) and transmitted by him to Manu was ç
lost in course of time, Arjuna naturally questions him out of unbelief ç
how a contemporary person like him could have taught a person who ç
lived in hoary antiquity (4.1-4). It is then that <185>r<200> K<216><218><207>a ç
reveals the truth of both of them passing through many births. Whereas ç
Arjuna underwent those births helplessly due to pr<193>rabdha karma ç
(residual karma, responsible for rebirth) and did not know about them, ç
<185>r<200> K<216><218><207>a being the Supreme Lord himself, voluntarily ç
and willingly accepted these births for a higher purpose.
@SPACE1 = 
It is dharma or righteousness thatis the principle regulating the ç
smooth working of the created world. Since the created world is a ç
product of the three gu<207>as† sattva, rajas and tamas†which are ç
constantly in a state of flux, it is but natural that each one of ç
them gets the upper hand periodically. Whenever sattva goes down and ç
rajas or tamas comes up, dharma declines and adharma (evil) gets the ç
upper hand. At such critical periods of human history, the Supreme ç
Lord decides to incar- nate himself in a human frame to restore the ç
balance. Though he is unborn, eternal and the Lord of all beings, ç
he can and does `come down' (avat<193>ra<|>=<|>coming down) by taking ç
recourse to his m<193>y<193>-power (also called prak<216>ti or nature) ç
(4.6,<|>7). The primary purpose of the avat<193>ra is dharma-sa<221>sth<193>pana ç
or establishing dharma on a firm foundation. In the process, if need ç
be, He will destroy or chastise the wicked and thereby protect the ç
good (4.8).
This descent of the Divine into the human frame can take place anywhere, ç
anytime, the sole condition being the decline of dharma and the ascent ç
of adharma (4.7) to the extent of rendering the good people absolutely ç
helpless, and at the mercy of the evil ones.
There is an added assurance given by <185>r<200> K<216><218><207>a ç
that one who is able to understand the significance of his birth and ç
work as an avat<193>ra, will attain liberation (4.9).
Of course, in a number of places, he urges Arjuna to cultivate devotion ç
to him, to meditate upon him and to work for him (9.34; 11.55; 18.65), ç
the finale being the command to surrender totally to him, with the ç
pledge to free him from all sins (18.66).
@SB = Commentaries
Being a part of the prasth<193>natraya and thus accorded a very high ç
place in the religio-philosophical tradition of India, the G<200>t<193> ç
has attracted the attention of several ancient and medieval teachers ç
who have written commentaries and glosses on it in Sanskrit. In the ç
Advaita Ved<193>nta tradition <185>a<209>kara (<F51320MS>A.<|>D.<W1> <F255D>788-820) ç
comes first. In fact, his is the earliest of the extant commentaries. ç
R<193>m<193>nuja (<F51320MS>A.<|>D.<W1> <F255D>1017-1137), Madhva (<F51320MS>A.<|>D.<W1> ç
<F255D>1197-1276), Nimb<193>rka  (12th  century<F51320W1>  <F255MS>A.<|>D.<D>)  and<F51320W1> ç
<F255D>Vallabha <F51320W1>(<MS>A.<|>D.<W1> <F255D>1473-1531) are the other great ç
<193>c<193>ryas or teachers who have written commentaries on the<F51320W1> ç
<F255MI>G<200>t<193>. °nandagiri (<F51320MS>A.D.<W1> <F255D>1200), Ved<193>nta ç
De·ika (<F51320MS>A.<|>D.<W1> 1<F255D>268-1370) and Jayat<200>rtha (13th century ç
<F51320MS>A.<|>D.<W1>) <F255D>have written glosses on the commentaries of <185>a<209>kara, ç
R<193>m<193>nuja and Madhva respec- tively. Mention may also be made ç
of the commentaries of <185>r<200>dhara (15th century <MS>A.<|>D.<D>), ç
Madhus<220>dana (<MS>A.<|><|>D.<F51320W1> <F255D>1525-1632) and R<193>ghavendra ç
(<F51320MS>A.<|>D.<F255D> 1598-1671) who have made some original contributions ç
to the G<200>t<193> literature.<F51320MS>
@SPACE = 
@SB = Conclusion
@SPACE = 
The Bhagavadg<200>t<193> is one of the most translated religious ç
classics of the world. The beauty and the sublimity of the work, its ç
eternal relevance to the problems of human life and its universal ç
approach that helps us view the whole creation as one, may have prompted ç
the scholars to under- take the task of translating it as a labour ç
of love.
Though part of the great epic Mah<193>-bh<193>rata, it can as well ç
stand on its own as an independent work. Though taught on the battlefield ç
of Kuruk<218>etra, urging Arjuna to fight, it has nothing to do with ç
wars or battles or bloodshed, but only with the discharging of one's ç
sacred duties of life, however unpleasant they may be. Though given ç
by <185>r<200> K<216><218><207>a to Arjuna in the days of yore, its ç
declarations like, `Remember Me and fight!' (8.7) can help and inspire ç
anyone of us, beleaguered with serious problems of life, even now. ç
Though recognizing multiplicity here, its principle of unity in diversity ç
as signified by the Vi·avar<220>pa or the Cosmic Form (11.9-13) and ç
the underlying divinity as taught in 7.7, help us to cultivate a holistic ç
approach to the universe of which ecological balance too is only a ç
small aspect.
If the Mah<193>bh<193>rata can claim to be an encyclopaedia of Hindu ç
religion and culture, the Bhagavadg<200>t<193> can as well claim ç
to be its quintessence.
@NT = Bhagav<193>n, Bhagavat
@N1 = (`one who<R>ç
possesses bhaga')
See <MS>BHAGA<D>.
@NT = Bhagavanta-bh<193>skara
@EMERGENCY = The Hindu way of life has been influenced, to a very ç
large extent, by the dharma·<193>stras. These dharma·<193>stras, chronologically ç
speaking, fall into three categories: (1) The dharmas<220>tras and ç
theManusm<216>ti (6th century <MS>B.C.<D> to the beginning of the ç
Christian era); (2) The versified sm<216>tis (upto <F51320P10MSC1>A.D.<W1> ç
<F255P255DC255>800); (3) The commentaries and nibandhas or digests (<F51320P10MSC1>A.D.<W1> ç
<F255P255DC255>800-1800).
@EMERGENCY = One of the well-known nibandhas or digests is the Bhagavanta-bh<193>skara ç
of N<200>laka<207><219>ha (17th century), a son of <185>a<209>karabha<219><219>a, ç
who was a profound scholar of M<200>m<193><221>s<193>. N<200>laka<207><219>ha ç
composed this encyclopaedic work of religious and civil  law,  in  honour  of  his  patron ç
Bhagavantadeva, a Bundella chieftain of the Sengara clan that ruled ç
at Bareha, near the confluence of the rivers Jumna (Yamun<193>) and ç
Chambal.
This work has been divided into 12 sections called `may<220>khas' ç
(or `rays'), the topics dealt with being: sa<221>sk<193>ra (sacraments), ç
<193>c<193>ra (personal conduct), k<193>la (time), ·r<193>ddha (afterdeath ç
ceremonies), n<200>ti (ethics), vyavah<193>ra (social behaviour), ç
d<193>na (gifts), utsarga (dedication for public benefit), prati<218><219>h<193> ç
(foundation of temples for public good), pr<193>ya·citta (expiations ç
for sins), ·uddhi (purificatory rites) and ·<193>nti (propitiatory ç
rites).
The rules given in this work are considered as a great authority in ç
certain parts of India even now.
See also <MS>NIBANDHAS<D>.
@NT = Bh<193>gavata
@N1 = (`related to Bhagavat or God')
@S10N = INTRODUCTION
R<193>ma and K<216><218><207>a (the most prominent of the incarnations ç
of Vi<218><207>u-N<193>r<193>ya<207>a), <185>ivaand Dev<200>, form ç
the four main pillars upon which the edifice of Hindu theism rests. ç
The two epics, R<193>m<193>ya<207>a and Mah<193>bh<193>rata, as ç
also the vast paur<193><207>ika literature, form the basis for the ç
various cults and sects that have woven the texture of the variegated ç
Hindu fabric. Among the various pur<193><207>as, however, it is the ç
Bh<193>gavata that has earned a pre-eminent place for itself, not ç
only for its philosophical content and devotional fervour but also ç
for its exquisite literary beauty. Though basically a text of the ç
Bh<193>gavata school preaching the Vi<218><207>u-N<193>r<193>ya<207>a-K<216><218><207>a ç
cult, it is remarkably catholic in its outlook and has successfully ç
harmonized Advaita philosophy as also the <185>aiva cults with its ç
basic tenets. While a study of this work is definitely fascinating ç
and highly rewarding, it has also been considered as a test of one's ç
scholarship.
@S10N = PUR°ØAS
The Bh<193>gavata has been classed among the pur<193><207>as. Hence ç
a few words about them will not be out of place here. Since early ç
Vedic literature like the Atharvaveda, <185>atapatha Br<193>hma<207>a, ç
Gopatha Br<193>hma<207>a and B<216>had<193>ra<207>yaka Upani<218>ad ç
mention the word pur<193><207>a (in singular), it may be inferred ç
that the pur<193><207>a was a branch of Vedic learning. The earliest ç
beginnings of the pur<193><207>a literature have been traced to the ç
P<193>ri-plava °khy<193>nas or narrations, commemorating the genealogies ç
of great kingly lines and allied subjects, recited during periods ç
of intervals in sacrifices. In course of time, recitation of the pur<193><207>a ç
seems to have been relegated to the s<220>tas (members of a mixed ç
caste) since it was not integral to the sacrifices. This bifurcation ç
helped in the development of a number of pur<193><207>as and upapur<193><207>as ç
(minor pur<193><207>as) under the leadership of eminent s<220>tas ç
like Lomahar<218>a<207>a who was a disciple of Vy<193>sa. It is very ç
likely that Vy<193>sa compiled theoriginal Pur<193><207>a-sa<221>hit<193> ç
whichwas expanded and divided by Lomahar<218>a<207>a and his disciples, ç
resulting in course of time, in eighteen pur<193><207>as and eighteen ç
upapur<193><207>as as extant now. In the light of this, it is understandable ç
how Vy<193>sa has been taken to be the author of all these pur<193><207>as ç
and upapur<193><207>as.
There has been a controversy whether the `Bh<193>gavata' included ç
in the list of the eighteen pur<193><207>as (also called sometimes, ç
asmah<193>pur<193><207>as) is Dev<200>bh<193>gavata or this (Vi<218><207>u) ç
Bh<193>gavata. Many scholars opine in favour of the latter.
@S10N = DATE AND AUTHORSHIP
With several unknown or variable factors involved, fixing the dates ç
of ancient Hindu scriptures, has always been a difficult exercise. ç
The Bh<193>gavata is no exception tothis. The internal evidence ç
of the work, viz., <185>uka teaching it to king Par<200>k<218>it, ç
takes the date to the beginning of the Kali-yuga, around 3000 <MS>B.C.<D> ç
This is the opinion of theorthodox groups. Another view, that poet ç
Bopadeva (13th cent.) was the author, has been thoroughly discounted ç
by several scholars. A few are of the conviction that the core of ç
the pur<193><207>a is very old. However, it was given the shape of ç
a mah<193>pur<193><207>a in the early Christian era and further expanded ç
bythe Tamil saints of South India, contemporaneous with the °<202>v<193>rs ç
(5th-8th cent. <F51320MS>A.<|>D.<F255D>) Thus, there has been a three-phase development ç
of the text.
Though tradition ascribes the authorship to the sage Vedavy<193>sa, ç
who was the author of the core of the work, those responsible for ç
the second and third phases of development have remained unknown.
@S10N = SYNOPSIS OF THE CONTENTS
The Bh<193>gavata as available today, has been divided into 12 skandhas ç
or books, further divided into 335 adhy<193>yas or chapters, containing ç
in all, a little more than 14,000 ·lokas or verses. However, tradition ç
has always put it at 18,000 verses.
A brief synopsis of the contents may now be given here:
@S10N = First Skandha (19 chapters, 809 verses)
This skandha, though introductory in form, is the final section added ç
to complete the narration of K<216><218><207>a's story and glory. ç
In this sense, it may perhaps be considered as a supplement to the ç
tenth skandha. The famous line `K<216><218><207>astu bhagav<193>n ç
svayam' occurring here (3.28) also signifies the finale to the development ç
of the Bh<193>gavata literature. It also describes how the Bh<193>gavata ç
came to be written.
After an introduction through the story of <185>aunaka and other sages ç
performing a Sattra-y<193>ga (a long-drawn fire sacrifice), the book ç
expatiates the glory of the Bh<193>gavata Dharma or the life of devotion ç
to the Lord, which can be cultivated through the study of the Bh<193>gavata ç
and the teachings of K<216><218><207>a who lives in it. This is followed ç
by a narration of how the Bh<193>gavata came to be composed by Vy<193>sa, ç
on the advice of the sage N<193>rada, to get peace of mind.
The book covers the last part of the story of the P<193><207><195>avas ç
including the incident of king Par<200>k<218>it being cursed by a ç
sage, to die of snake-bite. When the king has resigned himself to ç
his fate, the sage <185>uka, the son of Vy<193>sa, arrives there and ç
starts narrating the story of the Bh<193>gavata for his spiritual ç
good.
@S10N = Second Skandha (10 chapters, 391 verses)
Smallest of the twelve skandhas, this book may probably be the nucleus ç
of the original Bh<193>gavata.
Meditation on the Vir<193><219>puru<218>a or the Cosmic Divinity, ç
the ascent of the soul of yogi to the Brahmaloka, a description of ç
the devotion to the Lord, <185>uka's prayer to the Supreme Lord, glory ç
of Lord N<193>r<193>ya<207>a and his incarnations as also a brief ç
account of the cosmic theories and theological doctrines of Bh<193>gavata ç
form the subject-matter of this skandha.
The well-known Catu··lok<200>-Bh<193>ga-vata forms an integral part ç
of the ninth chapter of this book.
@S10N = Third Skandha (33 chapters, 1410 verses)
This consists of two long quotations by <185>uka, of dialogues that ç
took place bet- ween Uddhava and Vidura, and between Vidura and Maitreya. ç
It is sometimes interspersed with hymns and remarks by Par<200>k<218>it ç
and <185>uka.
The story of mutual fighting among the Y<193>davas and their destruction, ç
the ascension of K<216><218><207>a to his Abode, K<216><218><207>a's ç
message to Vidura through Uddhava, Vidura's seeking Self-knowledge ç
from the sage Maitreya and the latter's teaching containing the philosophy ç
of j<210><193>na and bhakti (knowledge and devotion) as taught by ç
Kapila to his mother Devah<220>ti†are the other contents of this book.
@S10N = Fourth Skandha (31 chapters, 1431 verses)
This skandha deals mainly with the stories of the daughters of Sv<193>yambhuva ç
Manu (a progenitor of mankind) and their lineage.
The story of destruction of Dak<218>a's sacrifice due to the wrath ç
of Rudra who had been antagonized by Dak<218>a and the episode of ç
the child devotee Dhruva who retires to the forest and performs auste- ç
rities to gain the grace of Lord Vi<218><207>u are the main contents ç
of this book.
@S10N = Fifth Skandha (26 chapters, 668 verses)
A considerable part of this skandha is in prose.
A schematic description of Brahm<193><207><195>a or the universe and ç
detailed description of the earth form an important part of this book. ç
The purpose seems to be to help the devotee to meditate on the physical ç
universe as the body of the Lord.
This skandha also contains the stories of great devotee-kings like ç
Priyavrata, <184><218>abha, Bharata and others.
There is also an interesting description of twenty eight kinds of ç
narakas or purgatories.
@S10N = Sixth Skandha (19 chapters, 849 verses)
This skandha starts with the story of Aj<193>mila, a sinner who was ç
saved by uttering the word `N<193>r<193>ya<207>a' on his death-bed, ç
thereby revealing the mysterious power inherent in the divine name.
Another episode dealt with in detail is that of V<216>tr<193>sura, ç
a fiend who fought with Indra, but was defeated and killed by him. ç
V<216>tr<193>sura was a great devotee of Lord Vi<218><207>u. Actually ç
he was<|>a<|>devotee king Citraketu born as a fiend due to a curse.
@S10N = Seventh Skandha (15 chapters, 750 verses)
Misbehaviour provoking the dis- pleasure of holy persons, results ç
in downfall. On the other hand, pleasing them through devoted service ç
can lead to spiritual evolution. This is the theme developed in this ç
skandha.
The examples given are those of N<193>rada, Jaya and Vijaya. N<193>rada ç
had to be reborn as a servant boy of low birth.
Jaya and Vijaya, attendants of Lord Vi<218><207>u at his abode Vaiku<207><219>ha, ç
were reborn as the demons Hira<207>y<193>k<218>a and Hira<207>ya-ka·ipu. ç
The story of Hira<207>yaka·ipu also contains a detailed account of ç
his son Prahl<193>da, one of the greatest exemplars of divine love. ç
Prahl<193>da survives all the attempts of his father to kill him, ç
due to the protection afforded by the Lord Vi<218><207>u to whom he ç
had totally surrendered himself. The discourses of Prahl<193>da onthe ç
cult of bhakti, known as the Bh<193>gavata-dharma are an important ç
part of this skandha.
There is also a nice description of var<207><193>·rama-dharmas, ideals ç
of the social system according to castes and stages of life.
@S10N = Eighth Skandha (24 chapters, 931 verses)
This skandha contains three important incidents: the story of Gajendra, ç
the elephant king; the churning of the ocean of milk and the obtaining ç
of am<216>ta or nectar by the gods; the story of Mah<193>bali, the ç
king of the asuras being vanquished by Lord Vi<218><207>u as V<193>mana ç
(the Dwarf<|>).
This skandha also gives the details of the manvantaras or epochs of ç
Manus (patriarchs endowed with divine powers).
The last part of skandha deals with naimittika-pralaya (intermediary ç
deluge) that occurs at the end of a day of Brahm<193>, the Creator ç
and the Matsy<193>vat<193>ra (Fish-incarnation).
@S10N = Ninth Skandha (24 chapters, 964 verses)
Dealing mainly with genealogies of the great kingly and priestly lines, ç
this skandha also gives accounts of some eminent personalities from ç
among them.
First comes the story of the sage Cyavana, his marriage with Sukany<193> ç
(daughter of king <185>ary<193>ti), her devoted service to the old ç
sage and the blessings of the twin gods A·vins upon the couple.
Then  comes  the  story  of  king Ambar<200><218>a, a great devotee ç
of Lord Vi<218><207>u, how the sage Durv<193>sas wanted to harm him ç
and how he was protected by the Sudar·ana-cakra, the Discus of the ç
Lord Vi<218><207>u.
Another notable episode is that of the king Rantideva who had gifted ç
away everything and was living a very austere life. Once, after a ç
long period of religious fasting when he was about to take his food, ç
he readily parted with it to feed hungry guests.
The stories of the kings Yay<193>ti, Du<218>yanta and his wife <185>akuntal<193> ç
as also the story of the P<193><207><195>avas are the other episodes ç
that appear in this section.
@S10N = Tenth Skandha (90 chapters, 3946 verses)
This is the biggest book of the Bh<193>gavata and is generally divided ç
into two parts: the P<220>rv<193>rdha (the first part) consisting ç
of 49 chapters and 2005 verses; the Uttar<193>rdha (the second part) ç
comprising 31 chapters and 1941 verses. It deals with the story of ç
<185>r<200> K<216><218><207>a in great detail.
The birth, childish pranks and exploits of Lord K<216><218><207>a ç
during his childhood days, his play with the gop<200>s of V<216>nd<193>van, ç
his journey to Mathur<193> along with his elder brother Balar<193>ma, ç
his killing of the tyrant Ka<221>sa, the ruler of Mathur<193>, his ç
education under the sage S<193>nd<200>pani, his marriages with several ç
princesses, his innumerable conquests as also his helping the P<193><207><195>avas ç
in various ways have been dealt with in detail.<F51320P10W1C1>
@S10N = Eleventh Skandha (31 chapters, 1366<|>verses):
The main topic of discourse in this skandha which is the concluding ç
part of the K<216><218><207>a saga, is mok<218>a or liberation from ç
transmigratory existence. The teachings of the Navayog<200>s or the ç
nine sages to Vasudeva containing the Bh<193>gavata-dharma and K<216><218><207>a's ç
long discourse to Uddhava, now well-known as the Uddhavag<200>t<193>, ç
are the main contents of this book. The Uddhavag<200>t<193> deals ç
mainly with spiritual values like holy association, supremacy of devotion ç
and details of the four yogas or paths to enlightenment.
The book ends with the mutual destruction of the Y<193>davas and the ç
exit of K<216><218><207>a from this world.
@S10N = Twelfth Skandha (13 chapters, 566 verses)
This is practically the prologue to the whole work.
The genealogy of kingly lines that ruled after K<216><218><207>a's ç
ascension, the importance of devotion to God in Kaliyuga and the last ç
part of the story of Par<200>k<218>it are the main contents of this ç
book. A synopsis of the whole Bh<193>gavata and the ceremonial way ç
of studying it have been added at the end.
@S10N = K<184><186>ØA
Sage Vy<193>sa composed the Bh<193>gavata solely to express his ç
devotion to the Lord by describing his glory through the K<216><218><207>a ç
incarnation. Hence no study of the book can be complete without touching ç
upon K<216><218><207>a, the person and the personality, his doings ç
and sayings.
The Bh<193>gavata declares that K<216><218><207>a is God himself, ç
`k<216><218><207>astu bhagav<193>n svayam' (1.3.28). Since God is ç
perfect, K<216><218><207>a, his human manifestation, too is perfect. ç
Hisphysical form and beauty are highly bewitching. His speech is ç
exceedingly sweet. His intellect and wisdom, shrewdness and farsightedness, ç
are matchless. His strength and power, valour and heroism are simply ç
awesome. But, he is not a tyrant, though tyrants quake on hearing ç
his very name. His heart is as soft as the butter he loves to consume ç
in liberal quantities. A friend of the lowly and the meek, compassion ç
incarnate, he is the first to rush to protect those in distress. Destroyer ç
of demons, conqueror of emperors, he makes and unmakes kings, himself ç
never accepting a throne. Wealth and power come rolling to his feet ç
unasked, but he is most detached towards them.
K<216><218><207>a is as great a spiritual preceptor as he is a warrior. ç
Lord of Yoga and goal of the yog<200>s, his teachings as given to ç
the gop<200>s or Uddhava, reveal the rarest of insights, but are intensely ç
practical.
K<216><218><207>a's dealings with the gop<200>s of V<216>nd<193>van ç
are often cavilled at, without a careful scrutiny. The king Par<200>k<218>it ç
himself raises serious doubts about K<216><218><207>a's (appa-rently) ç
unwholesome doings. <185>uka's reply which sets his doubts at rest, ç
runs on these lines: Even the sages who have gone beyond the bonds ç
of karma due to spiritual enlightenment got by meditating upon the ç
feet of the Lord, are beyond the dos and don'ts of dharma. Then what ç
to speak of him who is born out of his free will to savemankind? ç
Sometimes these great ones act, transgressing dharma, but with a higher ç
purpose. In such cases their words, and not actions, should be emulated. ç
For instance, <185>iva drank the deadly poison h<193>l<193>hala to ç
save the worlds. We cannot do so. Agni or fire can consume anything ç
that is cast into it. We cannot.
In  whichever  way  the  devotees approached K<216><218><207>a, in ç
the same way did he respond. He knew that the gop<200>s's love was ç
tainted with sex-passion. Like an expert psychiatrist he responded ç
to it, in order to draw it out from the subconscious levels and destroy ç
it, himself remaining all the while unaffected (vide 10.33.26). ç
That this technique worked, is shown by the fact of their realizing ç
him as their very Self (10.47.53).
@SPACE1 = 
Born in a prison, he liberates others from prisons and bondage. Brought ç
up by the cowherds he is highly admired and respected even by great ç
sages and mighty kings. Though subjected to all kinds of tyranny, ç
he frees others from tyranny and fear. He is an ideal householder, ç
an ideal man of renunciation, a hero of thousand battles who knows ç
no defeat, the terror of despots and hypocrites, a master statesman, ç
a consummate man of action, a friend of the lowly ones including the ç
untouchables†he is all things to all persons and hence, `Puru<218>ottama,' ç
the Best of Men.
@S10N = PHILOSOPHY OF THE BH°GAVATA
The Bh<193>gavata is a gospel of divine life and love, and not a ç
treatise of philosophy. It is based upon vij<210><193>na, thedirect ç
experience of the Reality but includes j<210><193>na (rational philosophy ç
built on it) also.
According to it, Brahman or °tman isthe only absolute Reality. The ç
whole universe is only an expression in name and form of this Reality. ç
Other terms used toindicate it are: Param<193>tman, Pratya-g<193>tman, ç
Puru<218>ottama, Ak<218>ara, Tur<200>ya, Bh<220>man and so on, as ç
in the Upani<218>ads. But the Bh<193>gavata calls it also by suchother ç
names as K<216><218><207>a, V<193>sudeva, N<193>r<193>ya<207>a, Hari ç
and so on. It is however pure consciousness, beyond words and thought ç
and free from all limitations.
The Bh<193>gavata accepts four pram<193><207>as or valid sources ç
of knowledge: pratyak<218>a (direct perception), anum<193>na (inference), ç
<193>ptav<193>kya (tradition of spiritual  experience  of  saints)  and  ·ruti ç
(Vedas). However, all these can only pointto Brahman, but cannot ç
give direct experience.
The work describes Brahman as an impersonal Super-person, the creator, ç
sustainer and final refuge of the world of matter and mind. He is ç
present in every atom of the universe in all his glory. M<193>y<193> ç
is the infinite power he wields. He takes whatever form his devotees ç
desire to worship him in, continuing to remain formless too. The emphasis ç
in the text is more on personal God with form, as more suited to love, ç
devotion and worship. And, K<216><218><207>a is God himself; or, rather, ç
God is K<216><218><207>a himself<|>!
`Bhagavat' is one of the central concepts of the text. The word `Bhagav<193>n' ç
frequently used both for the personal God and the Absolute, means ç
the `gracious Lord,' `the Adorable One'. It is also used as a term ç
of respect while referring to saints and holy men.
Then comes the concept of `avat<193>ra,' God come down (avat<193>ra<207>a ç
= coming down) as a living being, in order to help mankind to rise ç
to divine levels by restoring thespiritual equilibrium. The Bh<193>gavata ç
refers to several avat<193>ras, there being no uniformity in the number ç
or sequence, which varies from ten to forty.
The Bh<193>gavata also refers to the four `Vy<220>has' or emanations ç
from Lord Vi<218><207>u. They are sometimes classed under avat<193>ras ç
though considered as different from avat<193>ras that arise as a response ç
to certain cosmic situations. They are: V<193>sudeva, Sa<209>kar<218>a<207>a ç
Pradyumna and Aniruddha. They are different aspects of manifestation ç
of the six qualities known as `bhaga' (like j<210><193>na or knowledge, ç
bala or power, ai·varya or lordship and so on). While v<193>sudeva ç
has all the six qualities in full measure, the other three have two ç
each in greater measure than the others.
@SPACE1 = 
The <184>gvedic concept of `Puru<218>a' also can be seen here. He ç
is the Cosmic Personmanifesting himself objectively as the individual ç
and the universe. He is also called `Puru<218>ottama' and K<216><218><207>a ç
is Puru<218>ottama.
Then comes m<193>y<193>, the power of God. It has three gu<207>as ç
or strands, sattva, rajas and tamas. The whole universe is a product ç
of the permutation and combination of these three when their equilibrium ç
is disturbed by the will of God, who himself remains inactive like ç
a magnet, itself at rest, inducing movement in iron filings.
The world process appears to the devotees of the Lord as only his ç
`l<200>l<193>' or sport. He takes pleasure in it, the redemption of ç
the struggling souls being its main purpose.
The most important aspect of the teachings of the Bh<193>gavata ç
is the mode of s<193>dhan<193> it prescribes for attaining perfection. ç
Bhakti, love or devotion, has been given the pride of place, though ç
j<210><193>na (knowledge), yoga (contemplation) and karma (right activities) ç
too find an important place in its scheme. Bhakti has been advocated ç
as a more natural and hence an easier, path to perfection.
Bhakti has two aspects. When undertaken as the preliminary discipline, ç
it is called `s<193>dhan<193>-bhakti' or `vaidh<200>-bhakti.' It is ç
more of the nature of karma or activities like worship or chanting ç
or singing the divine names or other rituals. This ripens into `aik<193>ntik<200>' ç
or `ahaituk<200>' or `<193>tyantik<200>' (intense, single-pointed) ç
bhakti, wherein love flows unobstructed towards God even as a river ç
flows into the ocean. It is also termed as `nirgu<207><193> bhakti.' ç
One who has attained to this state of intense devotion is called a ç
`mah<193>bh<193>gavata' (a great devotee of God) or `bh<193>gavatottama' ç
(the best of devotees).
@SPACE1 = 
The object of bhakti may be the personal God or an avat<193>ra, or ç
the whole universe. Of these, bhakti towards an avat<193>ra is the ç
easiest and the sweetest. This bhakti can take several forms depen-ding ç
upon the relationship that the devotee cultivates towards the Deity: ç
·<193>nta (peaceful contemplation), d<193>sya (servitude), v<193>tsalya ç
(parental love), sakhya (friendship) and k<193>nta or m<193>dhurya ç
(conjugal love).
Sometimes, even hatred and fear of God have been included within the ç
orbit of bhakti by the text, since the intense concentration brought ç
about by them on God can purify and liberate them that do so.
Since love naturally expresses itself as service of the loved ones, ç
the Bh<193>gavata lays great stress on service of the Personal God ç
or saints or even the beings of the world as God's manifestation. ç
Service to the poor, the needy and the suffering is especially advocated.
Another peculiar feature of the work is the special reverence it advises ç
one to cultivate towards the mother-land. Bh<193>ratavar<218>a, named ç
after the great r<193>jar<218>i (sagely king) Bharata, is not a mere ç
geographical unit but the mother of civilization and, the very embodiment ç
of moral and spiritual culture.
There is a fairly detailed treatment of the subject of var<207><193>·rama-dharma ç
(scheme of duties according to castes and stages of life) which is ç
a vindication of man's right to grow to the heights of spiritual realization. ç
Character and conduct, rather than birth, are recognized as the sine ç
qua non of greatness. It is also stressed that devotion helps one ç
to transcend the limitations. imposed by birth.
@SPACE1 = 
Religious emotion leads to reverence which expresses itself as worship. ç
The Bh<193>gavata deals with ritualistic worship also as a part ç
of the practice of devotion. Worship of pratim<193>s (icons) and prat<200>kas ç
(symbols), the sun, holy rivers like the Ga<209>g<193> and the Him<193>laya ç
mountains are mentioned as aids to devotion. It is also stressed that ç
the devotee should never pray to God for anything for himself since ç
the omniscient God knows what is best for him.
The highest goal of life is called mukti. It is a state of freedom ç
from all bondage and getting back one's natural state of divinity ç
or bliss. Bhakti and japa (repetition of God's name) are the most ç
efficacious means of purifying the mind leading ultimately to mukti.
It is interesting to note that the work considers bhakti as the fifth ç
puru<218><193>rtha or value of life, beyond the other four, including ç
even mok<218>a or liberation. Bhakti is not merely the purifying agency, ç
a means for a higher end, as in the view of many monistic thinkers, ç
but, as its highest, is the acme of life, transcending mukti.
Though several varieties or aspects of mukti such a s<193>r<220>pya ç
(having a form similar to that of the Lord) or s<193>lokya (living ç
in the world of God, viz., Vaiku<207><219>ha) are described, Bh<193>gavata ç
is more inclined towards par<193>bhakti, the highest or the most intense ç
love of God, as the goal of life, wherein a semblance of the duality ç
between the devotee and the Deity is kept up.
@SPACE1 = 
Following the usual traditions of the pur<193><207>as, the Bh<193>gavata ç
also deals with many concepts involving immense time- periods and ç
almost boundless regions of space in its narrations about creation. ç
They become intelligible and meaningful only when it is recognized ç
that the pur<193><207>as trace the origin of the universe to the Supreme ç
Being and accept the cyclic theory of creation, preservation and withdrawal ç
as against the linear theory held by the modern scientists. Thus, ç
they deal with cosmic history and geography.
@S10N = LITERARY GRACE
The Bh<193>gavata is also a work of exceptional literary merit. ç
It is as graceful as it is tough. Whether it is a description of nature ç
(10.20) or of places like Mathur<193> and Dv<193>rak<193> (10.41; ç
10.37) or depiction of the well-known navarasas (nine poetic sentiments†10.29; ç
10.60; 10.37; 10.8; 10.80, 81), Bh<193>gavata excels in every way. ç
No wonder then, that the community of scholars have, for centuries, ç
accepted it as a touchstone of their erudition.
@S10N = TRADITIONAL COMMENTARIES
For this very reason, the Bh<193>gavata has attracted the attention ç
of several scholars who have composed commentaries on it. As many ç
as 44 commentaries are known to exist.
By  far,  the  Bh<193>v<193>rthad<200>pik<193>  of <185>r<200>dharasv<193>min ç
(14th cent.) seems to be the most popular of these commentaries. Brevity ç
and clarity, a rather difficult combination, are its chief characteristics. ç
It hasalso steered clear of controversies. D<200>pin<200> is sub-commentary ç
on this work byR<193>dh<193>rama<207>ad<193>sa Gosv<193>min. Since ç
<185>r<200>dhara was a monk of the Advaita school of Ved<193>nta, ç
the other two schools† Vi·i<218><219><193>dvaita and Dvaita†did not ç
want to lag behind. The Bh<193>gavata-candrik<193> of V<200>rar<193>ghav<193>carya ç
and the Padaratn<193>val<200> of Vijayadhavaja-t<200>rtha are the ç
commenta- ries, respectively, of these two schools. The  other  well-known  commentaries ç
still  holding  their  sway  among  the followers ofthe respective ç
cults are: Subodhin<200> of Vallabh<193>c<193>rya (<MS>A.<|>D.<D><|>1473-1531); ç
Siddh<193>nta-prad<200>pa of Nimb<193>rk<193>-c<193>rya (12th cent.); ç
Kramasandarbha of J<200>vagosv<193>min (15th cent.) and S<193>r<193>rtha-dar·in<200> ç
of Vi·van<193>tha-cakravartin (17th cent.). San<193>tana Gosv<193>min ç
(15th cent.) has chosen to comment only on the tenth skandha. This ç
work, B<216>had-vai<218><207>ava-to<218>i<207><200>, is highly venerated ç
by the followers of the Caitanya school.
@SPACE = 
@S10N = CONCLUSION
The Bh<193>gavata is essentially a devotional text. Much of the ç
metaphysics found in it is theological in nature, supporting the devotional ç
doctrines. The metaphysics, however, is that of Ved<193>nta. Hence, ç
the ideas stated in the Upani<218>ads are often found here, sometimes ç
using the very words or expressions. Though the work leans heavily ç
towards advaita, the supre-macy of the Personal God, especially as ç
N<193>r<193>ya<207>a or Mah<193>vi<218><207>u or K<216><218><207>a, ç
is always upheld; so also bhakti or devotion to him as the best means ç
of achieving anything in life.
However, the bhakti advocated here is not sentimentalism. It is up<193>san<193> ç
or meditation brought about by vair<193>gya (renunciation) and j<210><193>na ç
(knowledge of the Reality). Even sentimental devotion can help since ç
it is directed towards the Lord, who knows how to react, correct, ç
lead and guide his devotees.
Attempts have also been made in the work to reconcile the <185>iva ç
and the Vi<218><207>u
