@NID = cults, at loggerheads with each other at that time.
Synthesis of the paths of j<210><193>na, bhakti and karma is another ç
feature noticed here.
But the greatest achievement of the Bh<193>gavata is the projection ç
of the K<216><218><207>a saga and the K<216><218><207>a personality ç
in the most poetical, and yet, powerful and graceful language. If ç
K<216><218><207>a remains as the darling of millions of Hindu hearts ç
even today, it is not a little due to this matchless work.
@NT = Bh<193>gavata-dharma
@N1 = (`The Bh<193>gavata<R>ç
Religion')
Bhakti or love of God is a very ancient religious sentiment. Its origin ç
can be traced even to the <184>gveda (1.156.3; 8.98.11). It appears ç
like a flash of lightning in the Upani<218>ads (vide Ka<219>ha ç
Upani<218>ad 2.23; <185>vet<193>·vatara Upani<218>ad 6.23). By ç
the time of the epics and the pur<193><207>as it has grown to voluminous ç
proportions.
Gradually bhakti was developed into a doctrine or a religion or even ç
a philosophy. This has been christened as `Bh<193>gavata-dharma.' ç
The term `Bh<193>gavata-dharma' has been derived from the word `Bhagavat' ç
or God, endowed with `bhaga' or the six divine attributes of ai·varya ç
(lordship), dharma (righteousness), ya·as (celebrity), ·r<200> (wealth ç
and splendour), j<210><193>na (knowledge) and vair<193>gya (detachment). ç
Since this God is identified with N<193>r<193>ya<207>a, this religion ç
is also called `N<193>r<193>ya<207><200>ya-dharma.' It was also called ç
`S<193>tvata-mata' since it was current among the people of the `satvat' ç
tribe to which K<216><218><207>a belonged. As it teaches ek<193>nta-bhakti ç
or single-minded devotion, it has come to be known as `Ek<193>ntika ç
or Aik<193>ntika mata.' Other names of this system are: P<193><210>car<193>tra ç
mata (religion as taught in the P<193><210>car<193>tra °gamas) and ç
Vai<218><207>ava-dharma (religion of the followers of Vi<218><207>u).
@SPACE1 = 
The N<193>r<193>ya<207><200>ya section of the Mah<193>-bh<193>rata ç
(<185><193>ntiparva ch. 334 onwards), Vi<218><207>upur<193><207>a, ç
Bhagavadg<200>t<193>, Bh<193>gavata, P<193><210>car<193>tra °gamas, ç
Bhaktis<220>tras of <185><193><207><195>ilya and N<193>rada†these ç
are the sources of the Bh<193>gavata-dharma.
Not being satisfied with the impersonal Brahman of the Upani<218>ads, ç
the Bh<193>gavata religion has converted it into the Personal God. ç
®·vara, Mah<193>vi<218><207>u, N<193>r<193>ya<207>a and K<216><218><207>a-V<193>sudeva ç
are some of the names most commonly used with respect of him. He cannot ç
be apprehended by the senses nor by logic. <185>rutis or scriptures, ç
at best, point towards him. His grace is the supreme factor in realizing ç
him. <|>Ek<193>nta-bhakti<|> or <|>single-minded devotion is the only ç
mode bywhich his grace can be obtained and hecan be apprehended. ç
Though He is `sarvatantra-svatantra'  or  supremely  independent, ç
actually it is not so! He is always `bhakta- par<193>dh<200>na' or ç
subject to the will ofthe devotees! He is ever fond of those that ç
are devoted to him and reveals himself to them. Prapatti or ·ara<207><193>gati ç
(complete resignation) is another means of attaining him.
The Caturvy<220>ha doctrine is another speciality of this Bh<193>gavata-dharma. ç
Thefour vy<220>has or emanations of the Lord Vi<218><207>u are: V<193>sudeva, ç
Sa<209>kar<218>a<207>a, Pradyumna and Aniruddha. They are different ç
aspects of manifestation of the six qualities known as `bhaga' mentioned ç
earlier. While V<193>sudeva has all the six qualities in full measure, ç
the other three have two each in greater measure than the others.
Followers of the Bh<193>gavata-dharma are called `bh<193>gavatas.'
See also <MS>BH°GAVATA<D> and <MS>P°<178>CAR°TRA °GAMAS.<D>
@NT = Bhagavat<200>
The theistic systems of Hindu philo-sophy and the cults based on them ç
use the general term `Bhagav<193>n' to denote God since He possesses ç
`bhaga' or the six blessed qualities of j<210><193>na (knowledge), ç
ai·varya (lordship) and so on, in abundance. His power, conceived ç
as His consort, is called `Bhagavat<200>; same as <185>akti or Dev<200>.
Though this word can apply to any goddess or female deity, it is almost ç
invariably used to denote P<193>rvat<200> and her several aspects.
In the heart of the town Chengannur (in the Alleppy district of Kerala ç
State)is situated a well-known temple of a goddess known as Bhagavat<200>. ç
According to the local legend, <185>iva and P<193>rvat<200> presented ç
themselves before the sage Agastya, at the time of their marriage ç
and settled down there. While residing there, the Dev<200> had her ç
menses, thus forcing the couple to stay back till the periods were ç
over and the purificatory bath gone through. Even today, the devotees ç
believe that the goddess Bhagavat<200>†whose image is cast in pa<210>caloha ç
or an alloy of five metals†has her periods. The cella is kept closed ç
for three days during such periods. On the fourth day there is a bathing ç
ritual, conducted in the nearby river Pamp<193>.
Stories abound about the sceptics who had derided this phenomenon, ç
having incurred the wrath of the deity and come to grief.
The temple, sprawling over a six-acre plot, is a massive structure. ç
The image of the deity faces west. After the original icon was damaged ç
by fire, it was replaced by a pa<210>caloha idol. It is a beautiful ç
image, about 60 cms. in height and has two hands in the varada (boon-giving) ç
and abhaya (granting protection) poses.
There is also a shrine for <185>iva and the li<209>ga is of the svayambh<220> ç
(self-manifested) type. Subsidiary shrines dedicated to Ga<207>e·a ç
and Ca<207><195>e·a located inside the complex, and temples of <185><193>st<193> ç
and K<216><218><207>a, a little away, are the other attractions. A ç
giant peepul tree on the western side issaid to be endowed with the ç
miraculous power of curing those possessed by evil spirits.
The original temple might have been built by the Cerman dynasty (9th ç
to 12th cent.). It was renovated later, though this renovation has ç
not been completed.
@NT = Bhag<200>ratha
The word `bhag<200>ratha-prayatna' often used in Indian literature ç
for Herculean efforts in any field, owes its origin to the king Bhag<200>ratha, ç
the son of Dil<200>pa of the Ik<218>v<193>ku race, ruling in Ayodhy<193> ç
for several generations.
The S<193>garas, 60,000 sons of the Sagara, an ancestor of Bhag<200>ratha, ç
had been reduced to ashes by the wrath of the sage Kapila. The only ç
way of their spiritual redemption was to bring the river Ga<209>g<193> ç
from the svargaloka or heaven, and make its waters flow over these ç
ashes. Though successive kings tried to do it, they failed. Finally, ç
it was Bhag<200>ratha who succeeded in doing so.
He performed very severe austerities to please Brahm<193>, the Creator, ç
who appeared before him and advised him to solicit the help of <185>iva ç
who alone could arrest the torrential flow of the river Ga<209>g<193> ç
and slow her down. Bhag<200>ratha did tapas or penance once again ç
and appeased <185>iva who agreed to do so. Then, at the behest of ç
Brahm<193> and the request of the king Bhag<200>ratha, Ga<209>g<193> ç
descended on to <185>iva's ja<219><193> or matted hair, emerged as ç
a stream, followed the king right up to the p<193>t<193>la or the ç
nether world and flowed over the ashes, thus redeeming the S<193>garas.
Since Bhag<200>ratha brought the river Ga<209>g<193> down to this ç
earth, it has come to be known as the `Bh<193>g<200>rath<200>.'
Some mythological works say that Bhag<200>ratha was the son of A<221>·um<193>n, ç
the grandson of Sagara.
See also <MS>GA<177>G°<D>.
@NT = Bh<193>g<200>rath<200>
@N1 = (`connected with Bhag<200>ratha')
One of the several names of the river Ga<209>g<193> is Bh<193>g<200>rath<200>,since ç
it was brought from heaven to this earth by the king Bhag<200>ratha.
See <MS>BHAG®RATHA<D> and <MS>GA<177>G°<D>.
@NT = Bhairava
@N1 = (`one with a frightening cry')
Bhairava is regarded as one of the terrible aspects of Rudra-<185>iva, ç
associated with his fights against the asuras or demons. During his ç
fight with Andhak<193>-sura, eight emanations came out of him, called ç
A<218><219>a-bhairavas. They are: Vidy<193>-r<193>ja,<|>K<193>mar<193>ja,<|>N<193>gar<193>ja,<%-3> ç
<%0>Svacchandar<193>ja, Lambitar<193>ja, Devar<193>ja, Ugrar<193>ja ç
and Vighnar<193>ja. Other lists give the names as: Mah<193>bhairava, ç
Sa<221>h<193>rabhairava, Asit<193><209>gabhairava, Rurubhairava, K<193>la-bhairava, ç
Krodhabhairava, T<193>mrac<220><195>a (orKap<193>labhairava) and ç
Candrac<220><195>a (or Rudra-bhairava).
Bhairava is sometimes mentioned as one of the five leaders of <185>iva's ç
troops.
The Rudra-y<193>mala-tantra provides a list of 64 bhairavas in 8 ç
groups. The groups are distinguished by the colour of their bodies, ç
their ornaments and weapons.
Iconographical works generally des-cribe the Bhairava as of a dark ç
or reddish complexion and having four arms in which he carries mace, ç
lotus, spear and discus. The number of arms may be increased to eight ç
and the other objects carried in the hands may include sword, axe, ç
small drum (<195>amaru), bell, fire and so on. Other texts describe ç
him as having a flabby belly, round yellow eyes, sidetusks and wide ç
nostrils, and, wearing a garland of skulls. Snakes are his ornaments. ç
A dog is often shown as his companion.
It is quite likely that the Bhairava was the deity of the people of ç
the outcaste groups. In some parts of India he is the protecting deity ç
of the farmers.
Bhairava is also the deity of some obscure religious cults like the ç
N<193>tha Cult and the K<193>p<193>lika Cult. The K<193>p<193>likas ç
are sometimes referred to as `Bhairava-yog<200>s.'
@NT = Bhairav<200>
@N1 = (`the terrible goddess')
One of the several aspects of the Dev<200> or the <185>akti (the Mother ç
Goddess, P<193>rvat<200>) Bhairav<200> is the consort of Bhairava ç
(a terrible aspect of Rudra-<185>iva). Though sometimes she is identified ç
with C<193>mu<207><195><193>, she is depicted in several forms such ç
as Tripur<193>-bhairav<200>, K<193>me·var<200>, Annap<220>r<207><193>-bhairav<200>, ç
and so on. She is also the fifth in the series known as `Da·amah<193>vidy<193>s.'
She is described as resplendently red in complexion, wears a silk ç
garment as also a garland of skulls. Her crown is adorned with a crescent ç
moon. She has four arms. She holds a book and a rosary in two hands, ç
the other two exhibiting the abhaya and varada mudr<193>s granting ç
protection from fear and the boons asked for.
See also <MS>BHAIRAVA<D>.
@NT = Bhai<218>ajya-s<220>ktas
@N1-1 = (`Invocations connected with curing of diseases')
See <MS>ATHARVAVEDA<D>.
@NT = bhajana
@N1 = (`service, adoration')
Bhakti or devotion to God is considered to be one of the earliest ç
and the most efficacious forms of spiritual disciplines. Bhajana, ç
also called k<200>rtana, which generally takes the form of singing ç
devotional hymns and songs, is a popular mode of propagating the cult ç
of bhakti or devotion among the masses.
These bhajans and k<200>rtanas may be set to classical tunes and sung ç
by experts; or to simple popular tunes or even folk-tunes, so that ç
the masses can easily follow. The latter is sometimes called `n<193>m<193>val<200>-bhajanas'. ç
Groups of singers of bhajanas, going round a village or a town or ç
a temple is still a common sight, especially in rural India.
Institutions known as `bhajana-ma<219>has' have also come into existence, ç
to organise congregational singing. Such singing, organised by the ç
singers of different religious cults has resulted in different `bhajana-paddhatis'  or  traditions  of ç
bhajanas.
Singing of tev<193>rams and praban-dhams of the saints of Tamilnadu, ç
the d<193>sapadas and vacanas of Karnataka, the abha<209>gas ç
of Maharashtra, the Vai<218><207>ava k<200>rtanas, the ba<220>l ç
songs and the K<193>l<200>- k<200>rtanas of Bengal, the barg<200>ts ç
of <185>a<209>karadeva and his followers in Assam, the bhajanas of ç
M<200>r<193>, Tulas<200>d<193>s, Kab<200>r, S<220>radas and N<193>nak ç
form the various bhajana-paddhatis or traditions of devotional songs.
@NT = bhakta
@N1 = (`devotee')
Bhakti or devotion to God has been recognised as one of the easiest, ç
but most efficacious, method of s<193>dhan<193> or spiritual practice, ç
ultimately leading to beatitude. One who cultivates such devotion ç
is called a `bhakta;' and, the path of bhakti itself systematised ç
as a spiritual discipline is named `Bhaktiyoga'.
A bhakta or a devotee of God is expected to cultivate certain virtues ç
such as viveka (discrimination regarding food), vimoka (freedom from ç
desire), abhy<193>sa (regular practice of disciplines), kriy<193> ç
(doing good to others), kaly<193><207>a (purity through truth, straightforwardness, ç
compassion and non-violence), anavas<193>da (cheerfulness) and anuddhar<218>a ç
(absence of hilarity).
Other disciplines he is expected to follow are: vi<218>ayaty<193>ga ç
(renunciation of objects of desire), sa<209>gaty<193>ga (giving up ç
mental attachment towards them), avy<193>-v<216>tta-bhajana (constant ç
and continuous thinking of the Lord), ·rava<207>a and manana (hearing ç
about and singing the glories of God), mahatsa<209>ga (cultivation ç
of holy company), totally<|>abjuring dussa<209>ga or evil company, ç
taking recourse to viviktasth<193>na or lonely and peaceful places ç
conducive to the cultivation of bhakti, complete dependence on God, ç
performance of duties, but dedicating their fruits to God and so on.
The bhaktas can be divided into three groups depending upon the gu<207>a ç
or the nature of their devotion. As is well-known, there are three ç
gu<207>as†sattva rajas and tamas. The s<193>ttvika bhakta practises ç
disciplines of bhakti to purify himself and to please the Lord. The ç
r<193>jasa bhakta practises devotion to gain worldly benefits. The ç
t<193>masa bhakta practises his devotions to bring harm upon others, ç
out of jealousy and enmity (vide Bh<193>gavata 3.29.7-10).
@SPACE1 = 
The Bhagavadg<200>t<193> (7.16) offers a different classification: ç
<193>rta (one who is afflicted by serious problems, needing immediate ç
succour), arth<193>rthi (one desirous of worldly gains that cannot ç
be easily obtained by human efforts), jij<210><193>su (the inquirer ç
of Truth) and j<210><193>ni (the enlightened one). Each succeeding ç
devotee is considered as superior to the preceding one.
The bhaktas may also be classified into different groups, depending ç
upon the type of bhakti they practise towards God. For instance, those ç
who cultivate d<193>sya-bhakti (devotion of the servant towards his ç
master, like Hanum<193>n's towards R<193>ma) form one group. Those ç
that practise sakhya-bhakti (an attitude of friendship, like Arjuna's ç
or Uddhava's towards K<216><218><207>a) belong to another group. Others ç
whopractise v<193>tsalyabhakti (maternal love towards the child, ç
as Ya·od<193>'s towards the child K<216><218><207>a) fall into another ç
group. Still others like  °<207><195><193><202>  and  M<200>r<193>,  who  practised ç
madhurabhakti or conjugal love towards the Lord, form another group.
An ideal bhakta is one who has no hatred or enmity towards anyone. ç
He is full of compassion and friendly feeling towards all. He is free ç
from egoism and possessiveness. He is equanimous in plea-sure and ç
pain, ever forgiving and ever contented. He has mastered his passions ç
and dedicated his mind to God. He can never cause unrest in others ç
nor can he be upset by others in anyway. He is beyond all dualities ç
of the mundane life. He is therefore, extremely dear to the Lord (vide ç
Bhagavadg<200>t<193> 12.13-20).
See also <MS>BHAKTI<D> and <MS>BHAKTIYOGA<D>.
@NT = Bhakta-Vighne·vara
@N1 = (`Lord of obstacles, dear to the devotees')
Ga<207>apati or Ga<207>e·a, the elephant-faced god of the Hindu pantheon ç
is one of the most popular and widely worshipped deities. He has a ç
very large variety of aspects and Bhakta-Vighne·vara, also called ç
Bhakta-Ga<207>apati, is one of them.
Iconographical works describe him as shining like the autumnal moon. ç
He has four hands in which he carries a coconut, a mango fruit, a ç
lump of sugar and a cup of p<193>yasa (pudding). In some descriptions ç
a plantain replaces the lump of sugar.
See also <MS>GAØAPATI<D>.
@NT = bhakti
@N1 = (`devotion')
Bhakti or devotion or love of God is one of the most widely recognised ç
religious sentiments in all the major religions of the world. In Hinduism, ç
its origins can be traced even to the <184>gveda itself. Praise ç
of God (1.156.3), hearing or recitation of his names as also surrender ç
to him (1.156.2), filial affection towards God (8.98.11), that he ç
seeks his devotees (6.47.17), that he is our dearest and nearest (10.82.3)†these ç
are some of the aspects of bhakti found in it.
@SPACE1 = 
Coming to the Upani<218>ads, we see that though they are mainly devoted ç
to j<210><193>na or knowledge, the doctrine of grace which is an important ç
aspect of the philosophy of devotion, is found in some statements ç
like, `Whom the °tman chooses, by himis He obtained; to him, He reveals ç
Himsel<%16>f<%0>'. (Ka<219>ha Upani<218>ad 2.23) So also another: ç
`When he who is devoid of desire-motivated actions, through the grace ç
of God, the Supporter, sees the Param<193>tman's glory, then does ç
he become freed from sorrow' (ibid 2.20). The <185>vet<193>·vatara ç
Upani<218>ad actually uses the word `bhakti' and clearlystates `prapatti' ç
(self-surrender) also (6.23; 6.18).
In the Bhagavadg<200>t<193>, as also in the epics and the pur<193><209>as, ç
bhakti has been dealt with extensively. In the later literature, treatises ç
specially devoted to delineating the doctrine of bhakti have also ç
appeared, thus enriching the cult of devotion, like <185><193><207><195>ilya-bhakti-s<220>tras, ç
N<193>rada-bhakti-s<220>tras, N<193>rada-p<193><210>ca-r<193>tra, ç
Bhakti-ras<193>yana, Bhakti-ras<193>m<216>ta-sindhu and so on.
The philosophy of bhakti, called `Bh<193>gavatadar·ana' accepts God ç
as Personal, though the transcendental aspect too is not taboo. That ç
he can be apprehended neither by the senses nor by the intellect, ç
but only by devotion to him and his grace, is another cardinal principle. ç
That the path of bhakti is open to all without exception and that ç
is much easier than the other well-known paths like j<210><193>na ç
(knowledge) or yoga (contemplation), is another doctrine often propagated.
@SPACE1 = 
Bhakti has been defined as `parama-prema' (intense love) or `par<193>-anurakti' ç
(extreme attachment) to God, thus excluding or transcending all other ç
kinds of love. And, this is also `par<193>-bhakti' or supreme devotion, ç
which comes as the fulfilment of the practice of devotion. All other ç
practices of devotion that are preliminary, but ultimately lead to ç
par<193>-bhakti, are called `apar<193>-bhakti'.
Categorisation of bhakti depends upon the standpoint adopted for the ç
purpose. Division according to the gu<207>as, listing bhakti as s<193>ttvika, ç
r<193>jasa and t<193>masa, is one method; according to the state of ç
mind of the votary, as bhakti of the <193>rta (the afflicted), of ç
the arth<193>rthi (the one seeking worldly gains), of the jij<210><193>su ç
(an inquirer of Truth) and of the j<210><193>ni (the enlightened one) ç
is another method. A third method depends upon the attitude of the ç
devotee towards God. For instance, ·<193>nta is the devotion of a ç
serene votary, d<193>sya of a servant, sakhya of a friend, v<193>tsalya ç
of a parent and madhura of a consort.
One who aspires after cultivating bhakti is expected to adopt certain ç
moral and spiritual disciplines in life. Avoiding evil company and ç
cultivating holy company, detachment towards worldly things, taking ç
recourse to lonely places conducive to devotion, giving up evil actions ç
and actions motivated by selfish desires, performing one's duties ç
as an act of worship of God, practising fortitude and dependence upon ç
God, are some of the disciplines recommended.
The actual act of devotion itself can take several forms such as listening ç
to and singing the glories of God, ritualistic worship, repetition ç
of the divine names and contemplation on the divine forms of God, ç
dedicating the fruits of action to God and an attitude of utter surrender.
Scriptures of bhakti do not prohibit a person from living an active ç
life in the world. They only advise him to couple God with it. As ç
regards the sins of omission and commission, a sincere repentance ç
and prayer, and the consequent descent of God's grace, will efface ç
them.
See also <MS>BH°GAVATA-DHARMA, BHAKTA<D> and <MS>BHAKTIYOGA.
@NT = Bhaktiyoga
@N1 = (`union with [God] through devotion')
Hindu scriptural works posit mok<218>a or liberation from transmigratory ç
existence, as the final goal of life. This can be achieved either ç
through j<210><193>na (know-ledge) or through bhakti (devotion). The ç
well-known path of bhakti or devotion that ultimately leads to yoga ç
or union with, or, being firmly rooted in, God is termed `Bhaktiyoga'.
God has been described in the Upani<218>ads both as the transcendent ç
and as  the  immanent  Spirit  (Brahman- °tman), as also a Person ç
with infinite blessed qualities (Aupani<218>ada-Puru<218>a or ®·vara). ç
In Bhaktiyoga, the stress is almost entirely on the latter aspect, ç
though the former is accepted.
Dhy<193>na or meditation on the form of the deity and japa or repetition ç
of the divine name are the chief disciplines of this yoga.
Diverse forms of one and the same God, first articulated in the <184>gveda ç
(1.64.46; 10.114.5), have received a much more detailed treatment ç
in the pur<193><207>as and allied literature, as a result of the growth ç
of various cults. These have come in very handy for the votaries of ç
the bhakti cult advocating Bhaktiyoga. Meditation on anyone of the ç
forms of God that one cherishes†and this is called the `I<218><219>adevat<193>'†and ç
repetition of the mantra or the divine name associated with it, has ç
been a popular and effective mode of spiritual practice in Bhaktiyoga. ç
However, as per the age-old tradition, this mantra has to be received ç
from a qualified guru or spiritual preceptor in a ceremonial way, ç
called `d<200>k<218><193>'.
A person to be qualified as a guru hasto be sinless, fairly well-versed ç
in the concerned spiritual literature and deeply rooted in God. Anyone ç
who wishes to be a disciple should have cultivated the elementary ç
moral virtues like satya or truth and dama or self-control. He should ç
approach the guru in all humility and do personal service also. He ç
should receive the mantra with great ·raddh<193> or faith and adhere ç
strictly to the instructions given by him.
Apart from japa or repetition of the divine name, other aspects of ç
the practice of Bhaktiyoga are: ·rava<207>a (listening to the stories ç
of God), k<200>rtana (singing devotional hymns and songs), arcana ç
(ritualistic worship), vandana (obeisance), culti-vation of anyone ç
of the well-known attitudes like d<193>sya, sakhya or v<193>tsalya ç
and so on.
@SPACE1 = 
The saints, sages and seers who have attained perfection by following ç
the path of bhakti or devotion, are legion. Their characteristics ç
like universal love and compassion, absolute selfcontrol, unselfishness ç
to the core, equanimity under all vicissitudes of life are common ç
to all the perfected beings who might have attained that state by ç
other well-known means of s<193>dhan<193> like j<210><193>na or knowledge.
See also <MS>BHAKTA<D> and <MS>BHAKTI<D>.<MS>
@NT = Bh<193>mat<200>
The philosophy of the Upani<218>ads has been systematized in the Brahmas<220>tras ç
(also called the Ved<193>ntas<220>tras) attributed to B<193>dar<193>ya<207>a. ç
The Hindu tradition identi-fies him with the Vy<193>sa of the Mah<193>-bh<193>rata ç
fame.
Of the several Sanskrit commentaries on it extant today, <185>a<209>kara's ç
(<F51320P10MSC1>A.D.<W1> <F255P255DC255>788-820) is the earliest. In the post-<185>a<209>kara ç
period, several sub-commentaries were written on his Brahmas<220>tra-bh<193><218>ya, ç
necessitated by the need to further amplify certain subtle points ç
of the Advaita philosophy or to counter the dialectical criticisms ç
against theschool. One of the most outstanding of these, is the Bh<193>mat<200> ç
of V<193>caspati Mi·ra (9th century <MS>A.<|>D.<D>) which created a ç
new sub-school of Advaita Ved<193>nta, known as the Bh<193>mat<200> ç
Prasth<193>na.
The story goes that V<193>caspati Mi·ra named his celebrated gloss ç
after his wife Bh<193>mat<200> who had served him devotedly, sacrificing ç
all the conjugal pleasures, so that he could totally apply his mind ç
to the creative literary work.
The Bh<193>mat<200>, again, has six commentaries on it, the best-known ç
among them being the Kalpataru of Amal<193>nanda (13th century <MS>A.<|>D.<D>)<F51320W1>
The views of the Bh<193>mat<200> school can be briefly summarised ç
as follows: Brahman is the material cause of this world, not as the ç
locus of avidy<193> or nescience but as the object of avidy<193>s ç
supported by the j<200>vas or individual selves. M<193>y<193> is only ç
an accessory cause. Avidy<193> cannot abide in Brahman. It abides ç
in the j<200>vas and is plural. V<193>caspati advocates two kinds ç
of avidy<193>s: the m<220>l<193>vidy<193> or k<193>ra<207><193>vidy<193> ç
(primal nescience) and the t<220>l<193>vidy<193> or k<193>ry<193>vidy<193> ç
(derivative nescience). It is the latter that is responsible for error ç
impressions. Also, V<193>caspati seems to be more inclined towardsthe ç
`avaccheda-v<193>da' or the theory of limitation with regard to the ç
appearance of the j<200>vas. Just as a pot limits the infinite sky ç
in itself, avidy<193> of the individual limits Brahman and makes it ç
appear like a j<200>va. Another point of importance of this work is ç
that the mah<193>v<193>kyas or great sentences (like tat tvam asi) ç
do not produce anubhava or immediate experience. It is the mind seasoned ç
by meditation that gives such experience.
See also <MS>ADVAITA VED°NTA DAR<185>ANA<D> and <MS>V°CASPATI MI<185>RA.
@NT = Bha<207><195><193>sura
After  <185>iva  reduced  Manmatha (Cupid) to ashes, Citrakarma (an ç
attendant of <185>iva) gathered the ashes and shaped it into a human ç
form. When <185>iva opened his eyes after a long meditation, his eyes ç
fell upon this image which immediately came to life. This person worshipped ç
<185>iva himself and secured several boons. He came to be known as ç
Bha<207><195><193>sura. Strengthened by these boons which conferred ç
a long life and immense power as also immunity against several weapons, ç
Bha<207><195><193>sura started harassing Indra  and  other  gods.  Then  Indra ç
performed a sacrifice in honour of the Par<193>·akti or the Divine ç
Mother. Pleased by  it,  she  rose  out  of  the  sacrificial fire ç
as Lalit<193>-Parame·var<200> and killed Bha<207><195><193>sura.
See also <MS>LALIT°.
@SPACE = 
@NT = bha<209>ga
@N1 = (`break or bend')
@SPACE = 
This is a technical term used by the Indian iconographical works. ç
It may mean either `bend or inclination' or `posture'.
Images sculptured in the standing pose may have any one of the following ç
four bha<209>gas:
(1) samabha<209>ga (equally balanced): The image is poised firmly ç
on both the legs. The right and left halves are identi-cal. Theonly ç
exception is that the mudr<193>s or poses of the hands may be different.
(2) <193>bha<209>ga ( slightly bent): The upper half of the image ç
is made to incline slightly to the right side.
(3) tribha<209>ga (bent in three places): The head and the hips are ç
disposed slightly to the right and left sides of the centre line.
(4) atibha<209>ga (excessively bent): This is really an accentuated ç
form of tribha<209>ga.
In some iconographical works, the images are classified as sabha<209>ga ç
(with bha<209>ga) and abha<209>ga (without bha<209>ga). Images standing ç
with both legs firmly placed on the ground typify the latter. The ç
former ones are divided into five varieties †the word `bha<209>ga' ç
being interpreted as `posture'†as follows: sth<193>naka (standing), ç
<193>s<200>na (seated), ·ay<193>na (recumbent), y<193>naka (moving ç
about) and n<216>tta (dancing).
The first three among these, are sometimes, again subdivided into ç
yoga (inmeditation), bhoga (in enjoyment), v<200>ra (inheroic posture) ç
and <193>bhic<193>rika (black-magical).
@SPACE = 
@NT = Bharadv<193>ja
@SPACE = 
Bharadv<193>ja (also Bh<193>radv<193>ja) is the name of a sage that ç
occurs often in the Hindu scriptures. The several Bharadv<193>jas ç
we come across there are obviously different persons. There is one ç
Bharadv<193>ja- B<193>rhaspatya who is the seer of several hymns of ç
the <184>gveda (Ma<207><195>ala 6). He is probably the same as Bharadv<193>ja, ç
son of B<216>haspati and the father of the well-known Dro<207><193>c<193>rya ç
of the Mah<193>bh<193>rata.
The R<193>m<193>ya<207>a mentions one Bhara-dv<193>ja, a disciple ç
of V<193>lm<200>ki, who lived in Pray<193>ga (Allahabad). It was at ç
his instance that R<193>ma chose to stay at Citrak<220><219>a. While ç
returning from La<209>k<193>, R<193>ma stayed back at his hermitage ç
and sent the information of his coming, through Hanum<193>n, to Bharata.
Bharadv<193>ja is sometimes counted among the seven sages known as ç
`gotra-pravartakas' or the originators of the gotra (lineage). His ç
descendants thus became Bh<193>radv<193>jas.
Two works attributed to a Bharadv<193>ja are available now: Bharadv<193>ja ç
<185>rauta-s<220>tras and Bharadv<193>ja G<216>hyas<220>tras. The ç
extant manuscript of the former consists of nine pra·nas (sections) ç
and part of the tenth. Passages from the latter have been quoted by ç
other dharma·<193>stra writers.
The Artha·<193>stra of Kau<219>ilya cites the views of a Bharadv<193>ja ç
seven times and of Ka<207>i<209>ka Bharadv<193>ja once. Not much is ç
known of them or their works now.
@NT = Bhara<207><200>
@N1 = (`that which bears')
Bhara<207><200> is the second of the 27 nak<218>atras depicted in ç
the Hindu calendar. It is sometimes called as ``Apabhara<207><200>'' ç
also. Stars 35, 39 and 41 in the Me<218>a or Aries group comprise ç
this nak<218>atra. In the astrological treatises, its effect is considered ç
as malefic.
See also <MS>NAK<186>ATRA.
@NT = Bharata
Of the several Bharatas known to the Hindu mythological lore, first ç
comes the emperor Bharata, the son of <184><218>abha and Jayant<200>. ç
The country that he ruled came to be known as `Ajan<193>bhavar<218>a' ç
or `Bharatavar<218>a' or `Bh<193>ratavar<218>a'.
The son of the king Du<218>yanta and his queen <185>akuntal<193> was ç
also known as Bharata; and sometimes, as Sarvadamana.
The P<193><207><195>avas and the Kauravas were his descendants. Some ç
scholars opine that this country got its name `Bharatavar<218>a' from ç
him.
Of all the Bharatas known to the Hindus, Bharata of the R<193>m<193>ya<207>a, ç
the younger brother of R<193>ma, is the most popular. The second son ç
of Da·aratha born in the womb of Kaikey<200> he was deeply devoted ç
to R<193>ma. When Kaikey<200> forced Da·aratha, on the pretext of ç
unfulfilled boons given earlier, to banish R<193>ma for 14 years and ç
got the kingdom for Bharata, he refused to accept it. After chastising ç
his mother, he went to the Citrak<220><219>a mountain where R<193>ma ç
had just settled down, to persuade him to return. Since R<193>ma was ç
firm, that obeying the commands of their father Da·aratha was binding ç
upon both of them, and advised Bharata to rule the kingdom during ç
theperiod of his banishment, Bharata returned to Ayodhy<193> with ç
a heavy heart. He established the p<193>duk<193>s or wooden sandals ç
of R<193>ma on the throne at Ayodhy<193> and ruled the kingdom on ç
his behalf from Nandigr<193>ma, a nearby village. He lived like an ç
ascetic till R<193>ma returned and then handed back the kingdom to ç
him.During his rule he had considerably improved it. (See also <MS>R°M°YAØA.<D>)
Bharata has remained as the model of brotherly love, affection and ç
loyalty for the Hindus over the centuries.
N<193><219>ya·<193>stra, an original treatise on dramaturgy, is ç
ascribed to one Bharata who is almost a legendary figure for us now. ç
He might have lived during the period 200<MS> B.C.<192>A.D. <D>400. ç
His work as extant today does not seem to be the original. According ç
to Abhinavagupta (<MS>A.<|>D.<D> 980) the most authoritative commentator ç
on the N<193><219>ya·<193>stra of Bharata, this work was in 36 chapters ç
comprising 6000 ·lokas or verses (vide Abhinava-bh<193>rat<200>). ç
(See <MS>ALA<177>K°RA-<185>ASTRA<D> for details.)<MS>
The <184>gveda (3rd and 4th ma<207><195>alas) mentions Bharatas ç
as a clan of people.
@NT = Bh<193>rata-s<193>vitr<200>
The Mah<193>bh<193>rata is one of the two epics of Hinduism. It ç
has been acclaimed as a veritable encyclopaedia of dharma or righteousness.
Almost at the very end of this great epic, Vy<193>sa, its celebrated ç
author, declares in great anguish that though dharma is the basis ç
of all wealth and pleasures of life, though he is crying hoarse with ç
both his hands uplifted, none seems to be interested in following ç
it in life! He exhorts people not to abandon dharma even at the cost ç
of one's life, let alone out of lust or fear or greed.
The  three  verses  containing  his final message (vide Svarg<193>roha<207>a-parva, ç
5.62-64) are called `Bh<193>rata-s<193>vitr<200>'.
@NT = Bh<193>ratavar<218>a
@N1 = (`the continent ruled by Bharata')
Ancient and medieval Hindu scriptures often refer to India as `Bh<193>ratavar<218>a,' ç
`Bharatakha<207><195>a,' `Jamb<220>-dv<200>pa' and so on. Generally, ç
the country to the south of the Him<193>layas and to the north of ç
the Indian ocean is described as `Bh<193>ratavar<218>a,' practically ç
the same as modern India or undivided India.
Sometimes, Jamb<220>dv<200>pa is described as comprising nine countries, ç
out of which Bh<193>ratavar<218>a is one. The name `Bh<193>rata-var<218>a' ç
might have been derived from the names of its rulers like Manu (who ç
was also called Bharata) or Bharata, the son of <184><218>abhadeva ç
or Bharata-Sarvadamana, the son of Du<218>yanta and <185>akuntal<193>.
Well-known mountains like Himavat, Mahendra and Malaya, and rivers ç
like Sarasvat<200>, Ga<209>g<193>, Yamun<193> and Gomat<200> belong ç
to this Bh<193>ratavar<218>a.
Even in the early works it has been admitted that dharma was fully ç
developed in the Bh<193>ratavar<218>a and that the people were highly ç
cultured.
@NT = Bh<193>rat<200>
@N1 = (`one who delights in light or knowledge')
The <184>gveda (1.142.9) mentions Bh<193>rat<200> as one of the ç
three goddesses (the other two being I<202><193> and Sarasvat<200>) ç
who are requested to reside in the barhis or sacrificial grass.
In the later literature, Bh<193>rat<200> has been identified with ç
Sarasvat<200>, the goddess of learning. (See <MS>SARASVAT®<D> for ç
details.)<MS>
According to some religious texts, Bh<193>rat<200> is one of the two ç
consorts of Ga<207>apati, the other being <185>r<200>.
`Bh<193>rat<200>' is also one of the ten titles assigned to the monks ç
of the Da·an<193>m<200> Order created by <185>a<209>kara (<MS>A.<|>D.<D> ç
788-820).<F51320P10W1C1>
@NT = Bharatiya Vidya Bhavan
Dedicated to spreading Hindu edu-cational and cultural values, the ç
Bharatiya Vidya Bhavan was founded in <MS>A.<|>D.<D> 1938 (at<|>Bombay, ç
now<|>Mumbai) by K<W1%16>.<D%0>M<W1%24>.<D%0>Munshi (<MS>A.<|>D.<D> ç
1887-1971), one of the prominent leaders of the freedom movement in ç
India.
True  to  its  goal  of  revitalizing dharmaor the Moral Law, in ç
its threefold form of Satyam (Truth), <185>ivam (Auspiciousness) and ç
Sundaram (Beauty), the organisation is striving to carry forward India's ç
ageless message of <185>raddh<193> (Faith), Sa<221>yama (Self-discipline) ç
and Samarpa<207>a (Dedication).
The activities of this Institution are spread over various fields ç
such as education, literature, morality, art and culture as also spiritual ç
values.
It has scrupulously kept itself away from the political field.
Over the last seven decades it has established 121 centres all over ç
India and abroad, with 315 constituent institutions. So far it has ç
published 1700 titles of books with sales crossing 26 millions.
Its most valuable publication has been the book, The History and ç
Culture of the Indian People, in eleven volumes.
Through its various institutions it isimparting education in subjects ç
like Sanskrit, Indology, Indian Culture including music, dance and ç
painting, as also yoga, ancient scriptures and languages.
It is also promoting national integration, communal harmony, purity ç
in public life and rural upliftment through suitable programmes.
@NT = Bh<193>rgava
@N1 = (`a descendant of Bh<216>gu')
Though all the descendants of the sage Bh<216>gu are entitled to have ç
this patronymic, it is to Para·ur<193>ma (R<193>ma of the battle-axe) ç
that this name is particularly applied.
See <MS>BH<184>GU<D> and <MS>PARA<185>UR°MA.<D>
@NT = Bhart<216>hari
Bhart<216>hari is a well-known name in the classical Sanskrit literature. ç
However, we come across two of them.
The first was a grammarian who lived probably in the 5th century <MS>A.<|>D.<D> ç
He has been classed among the famous trinity of grammarians†the other ç
two being P<193><207>ini (400 <MS>B.<|>C.<D>) and<F51320P10W1C1> <F255P255DC255>N<193>ge·a ç
or N<193>goji Bha<219><219>a (18th cent. <MS>A.<|>D.<D>)†who developed ç
the Spho<219>av<193>da, the theory that the meaning of a word or a ç
sentence reveals itself in a flash as soon as its utterance is completed. ç
(See <MS>SPHO<187>AV°DA.<D>) He is said to have been a Buddhist. Mah<193>bh<193><218>ya-d<200>pik<193> ç
and V<193>kyapad<200>ya are the two works attributed to him. The ç
former is a commentary on the Mah<193>bh<193><218>ya of Pata<210>jali ç
on the s<220>tras of P<193><207>ini. The latter is a grammatico-philosophical ç
work in three k<193><207><195>as or sections dealing with Brahman, ç
the Supreme, as <185>abda or Logos.
The second Bhart<216>hari, whose period has been placed somewhere ç
between 100 <MS>B.<|>C.<D> and <MS>A.<|>D.<D> 500, was the author of ç
the three well-known <185>atakas (one hundred verses) viz., the <185><216><209>g<193>ra·ataka, ç
the N<200>ti-·ataka and the Vair<193>gya·ataka. The first deals ç
with erotics, the second with general ethics and the last with renunciation.
Though very little is known of him, tradition describes him as a king ç
ruling in Ujjayin<200> who later abdicated his throne in favour of ç
his younger brother Vikram<193>-ditya, the originator of the Sa<221>vat ç
era, since he was disgusted with the infidelity of his queen.
@NT = Bhart<216>prapa<210>ca
The Ved<193>nta system is the most well-known of the six systems of ç
Indian philosophy. It is commanding great respect among the intellectuals ç
even now. <185>a<209>kara (<MS>A.<|>D.<D> 788-820), R<193>m<193>nuja ç
(<MS>A.<|>D.<D> 1017-1137) and Madhva (<MS>A.<|>D.<D> 1197-1276) were ç
the pioneers in the three schools of Ved<193>nta, viz., advaita, vi·i<218><219><193>dvaita ç
and dvaita, which are popular even today. However, there are other†though ç
less-known† schools of Ved<193>nta, the propagators of some of which ç
preceded even <185>a<209>kara. Bhart<216>prapa<210>ca was one such. ç
Practically nothing is known of him except that he taught `bhed<193>bheda-v<193>da,' ç
the doctrine of `identity in difference'.
This doctrine is a kind of monism in which both bheda or difference ç
and abheda or identity are accepted between Brahman on the one hand ç
and the j<200>vas, as also the world, on the other. The waves and ç
the foam or the bubbles that arise in the ocean are all identical ç
as water, but different as waves or bubbles. Similarly, the j<200>vas ç
or the individual souls and the world, which evolve out of Brahman ç
are both different and non-different from it.
Bhart<216>prapa<210>ca  accepts  pram<193><207>a- samuccaya, a combination ç
of all the three well-known means of knowledge† pratyak<218>a or direct ç
perception, anum<193>na or inference and <193>gama or the Vedas. As ç
a consequence, he accepts the reality of the world experienced through ç
the sense-organs and hence the need for karma or action including ç
ritualistic actions. This leads us to his next proposition of j<210><193>na-karma-samuccaya, ç
a combination of know-ledge and action, as a means to mok<218>a or ç
liberation. Karma or desireless action leads to apavarga or freedom ç
from sa<221>s<193>ra (transmigration) and j<210><193>na leads to the ç
destruction of avidy<193> or ignorance, ultimately resulting in identity ç
with Brahman, the ultimate Truth.
@NT = Bh<193>sa
Bh<193>sa is one of the reputed authors known to the writers of ancient ç
classical literature in Sanskrit. Though mentioned by K<193>lid<193>sa ç
and B<193><207>a, his works had notbeen traced. It was only in 1912 ç
thatPa<207><195>it Ga<207>apati <185><193>stri of Trivandrum published ç
13 plays like Pratij<210>a Yaugandar<193>ya<207>a and Svapnav<193>savadatta. ç
After several rounds of controversies among the Sanskrit scholars, ç
it is now generally agreed that all these 13 plays are by a single ç
author and that it could be Bh<193>sa, though the evidence is not ç
conclusive. He might have been a contemporary of P<193><207>ini, the ç
grammarian, and might have lived in the 4th century <MS>B.<|>C.<D>, ç
but in a place far away from his.<F51320W1>
Very little is known of his life. He was probably a br<193>hma<207>a-muni ç
and had strong leanings towards the Vi<218><207>u cult.
Six of his plays like Madhyama Vy<193>yoga, Kar<207>abh<193>ra ç
and <188>rubha<209>ga are based on the Mah<193>bh<193>rata  and ç
two (Pratim<193> and Abhi<218>eka) on the R<193>m<193>ya<207>a.
The rest like Svapnav<193>savadatta and Avim<193>raka are from ç
miscellaneous sources like the B<216>hatkath<193> of Gu<207><193><195>hya, ç
an ancient collection of tales in the Pai·<193>c<200> language.
Bh<193>sa's language is simple, direct and forceful. The dramas are ç
eminently suited to be enacted on the stage.
@NT = Bh<193><218><193>pariccheda
This is a well-known and popular treatise on the Ny<193>ya-Vai·e<218>ika ç
philo- sophy by Vi·van<193>tha Ny<193>yapa<210>c<193>nana Bha<219><219><193>c<193>rya ç
(17th Century <MS>A.<|>D.<D>) who lived in Navadv<200>pa (in Bengal).
The author himself has written a detailed commentary, Siddh<193>ntamukt<193>val<200> ç
by name.
There are 168 verses in the anu<218><219>ubh metre.
The work, which is quite a tough one, deals with the following topics: ç
the seven  categories  (saptapad<193>rthas);  the substances (dravyas); ç
the five methods of knowledge like pratyak<218>a or direct perception; ç
mind; qualities (gu<207>as); some details about inference (anum<193>na); ç
some miscellaneous qualities.
@NT = Bh<193>skara
The Ved<193>nta system of philosophy based mainly on the Brahmas<220>tras, ç
which itself is a systematization of the doctrines of the major Upani<218>ads, ç
gained greater currency and respectability due to <185>a<209>kara ç
(<MS>A.<|>D.<D> 788-820). Out of the several post-<185>a<209>kara Ved<193>ntins, ç
who criticised his views,Bh<193>skara was one. Since R<193>m<193>nuja ç
(<F51320MS>A.D.<W1> <F255D>1017-1137) in turn criticises the views of Bh<193>skara, ç
the latter may have lived prior to him, around <F51320MS>A.D.<W1> <F255D>900.
@SPACE1 = 
Bh<193>skara wrote a commentary on the Brahmas<220>tras, the Bh<193>skara-bh<193><218>ya, ç
wherein he has expressed his views. His school is generally called ç
the Bhed<193>-bhedav<193>da, a doctrine that upholds the reality ç
of both unity and multiplicity.
This world of souls and matter is a real evolution of Brahman. Brahman ç
is not an undifferentiated mass of consciousness. In the causal state, ç
it is a unity and in the evolved state it is a multiplicity. In its ç
causal and generic aspect, this worldis non-different from Brahman, ç
but different as effects and individuals. Both are equally real.
Matter as evolved into bodies and senses acts on Brahman as an up<193>dhi ç
or limiting adjunct and results in the rise of the j<200>vas or individual ç
souls. However, the j<200>vas are related to Brahman as sparks to ç
fire and are atomic in size. The life of sa<221>s<193>ra or bondage ç
brought about by transmigration is due to the confusing between Brahman ç
and the up<193>dhis. Libe-ration comes through karma or actions prescribed ç
by the Vedas, done in the right spirit, and j<210><193>na or knowledge ç
of the soulthat arises in the mind purified by karma. Thus he advocates ç
j<210><193>na-karma-samuccaya or a balanced combination of action ç
and knowledge.
There was another Bh<193>skara, who probably lived in the 7th century ç
A.<|>D. Hewas the author of two works on astronomy†Mah<193>bh<193>skar<200>ya ç
and Laghu-bh<193>skar<200>ya†which were used for astronomical calculations ç
in South India upto the end of the 15th century.
@NT = Bh<193>skar<193>c<193>rya
@SPACE = 
A celebrated astronomer and mathematician, Bh<193>skar<193>c<193>rya ç
(<MS>A.<|>D.<D> 1114-1160) wrote the monumental work Siddh<193>nta- ç
·iroma<207>i when he was only 36. It has four chapters of which the ç
first†called L<200>l<193>vat<200>†is on arithmetic. The story goes ç
that he named this part of his work after his daughter L<200>l<193>vat<200> ç
who was widowed at an early age, to immortalize her. An extremely ç
popular work written in an interesting and entertaining manner, it ç
has been translated into several languages over the centuries. It ç
includes sections on ·<220>nya or zero, geometry, mensuration, and ç
ku<219><219>aka or indeterminate equations of the first magnitude. ç
B<200>jaga<207>ita or algebra is the second chapter. The other two ç
chapters called Ga<207>it<193>dhy<193>ya and Gol<193>dhy<193>ya ç
are works on astronomy that include celestial mathematics.
The work has several commentaries in Sanskrit.
Another work of his, called K<193>ra<207>a- kut<220>hala, a handbook ç
for preparing astronomical tables, is not so well-known.
@SPACE = 
@NT = Bh<193>skara-r<193>ya
@SPACE = 
Worship of God as Mother is an ancient practice in India. Though the ç
references to the Mother-cult are very meagre in the early Vedic literature, ç
we have plenty of material in the later pur<193><207>as and tantras. ç
One of the most famous texts of the Mother-cult, which is very popular ç
in South India is the Lalit<193>sahasran<193>ma, which again is ç
a part of the Brahm<193><207><195>apur<193><207>a. The most celebrated ç
commentary on this text is the Saubh<193>gyabh<193>skara of Bh<193>skara-r<193>ya- ç
makhin (also known as Bh<193>sur<193>nanda-n<193>tha). He lived during ç
the 17th-18th centuries. His spiritual preceptor was Narasi<221>ha ç
Adhvar<200> who taught him 18 kinds of sciences. An adept in several ç
fields like the Ved<193>nta, M<200>m<193><221>s<193>, vy<193>kara<207>a ç
(grammar) and mantra·<193>stra (science of mantras) he is said to ç
have composed 42 works. The works Varivasy<193>-rahasya and Setubandha ç
along with the Saubh<193>gya-bh<193>skara are considered as the ç
`prasth<193>natraya' or the three basic texts of <185>r<200>vidy<193>, ç
the Mother-cult of South India.
@NT = bhasma
@N1 = (`that which shines,' `that which destroys all sins,' `that ç
which produces auspiciousness,' `ashes')
Fire is believed to reduce all substances to their primal state of ç
purity. Hence, bhasma or ashes have always been considered as sacred ç
by certain sections of the Hindu society, especially the <185>aivas ç
and the <185><193>ktas (followers of <185>iva and <185>akti or the ç
Divine Mother).
Bhasma derived from the Vedic fires is called `<185>rauta-bhasma.' ç
It is to be taken out of the fire when the Vedic ritual is in progress ç
and applied on the body. That derived from the fire lit up during ç
a ritual performed as per the directions of sm<216>tis (secondary ç
scriptures like the dharma- ·<193>stras) is called `sm<193>rta-bhasma.' ç
If the fire is kindled by the Aghora-mantra (a mantra describing the ç
aghora or non-fierce aspect of <185>iva) with the wood of the bilva ç
tree (Aegle marmelos), the ashes are called `·iv<193>gni-bhasma.' ç
This bhasma is considered to be extremely sacred and capable of destroying ç
sins as also ritual impurities.
Wearing a `tripu<207><195>ra,' a mark of three lines on the forehead ç
with bhasma, using the fingers on the right hand (the thumb, the middle ç
finger and the ring finger) is considered a must for all the devotees ç
of <185>iva. These three lines are supposed to represent: the three ç
Vedas (<184>g, Yajus and S<193>man); the three syllables (a, ç
u and ma) of Om; the three gu<207>as (sattva, rajas and tamas); ç
the three ·aktis or powers (kriy<193>·akti, icch<193>·akti and j<210><193>na·akti) ç
of Dev<200> or Divine Mother; the three pressings of soma juice in ç
Somay<193>ga (pr<193>tassavana, m<193>dhyandinasavana and t<216>t<200>yasavana) ç
and so on. The whole idea seems to be to bring into one's mind, various ç
religio-spiritual concepts so as to feel pure and elevated.
Bhasma may be smeared over other parts of the body also, often to ç
the accompaniment of appropriate mantras, thus purifying both the ç
body and the mind. This is sometimes called bhasma-sn<193>na or bath ç
with bhasma.
Among the li<209>g<193>yats (·aivites of Karnataka  State)  bhasma-dh<193>ra<207>a  or ç
applying the tripu<207><195>ra of bhasma on the forehead is considered ç
as an important act of practice classed under `a<218><219><193>vara<207>as.' ç
(See <MS>A<186><187>°VARAØAS.<D>) According to their philosophy, bhasma ç
is really that which burns up all illusions and paves the way for ç
the intuition of the inner Self. The ashes are only an external and ç
gross symbol of the process.
@SPACE1 = 
Bhasma as consecrated ash is used for ritual purification (like the ç
water of the Ga<209>g<193> river) of objects defiled by the touch ç
of undesirable (or sinful) persons or animals etc., for protection ç
against inauspicious things or evil spirits or even for purposes of ç
sorcery and magical rites.
Bhasma has to be prepared by burning cowdung cakes in fire with appropriate ç
mantras. The process has been described in the Bhasma-j<193>balopani<218>ad, ç
one of the minor upani<218>ads of the <185>aiva cult.
@SPACE = 
@NT = Bhasma-j<193>b<193>lopani<218>ad
@SPACE = 
One of the minor upani<218>ads of the Atharva<207>aveda group, Bhasmaj<193>b<193>lopa-ni<218>ad ç
is in the form of a long conversation between the sage J<193>b<193>la-Bhusu<207><195>i ç
and Lord <185>iva. It is in prose and consists of two chapters.
The sage J<193>b<193>la approaches Lord <185>iva with great reverence ç
and inquires of him thus:
(1) Please teach me all about bhasma (holy ash) including the mode ç
of wearing the tripu<207><195>ra (religious mark of three lines drawn ç
on the forehead) by which mok<218>a or liberation can be easily obtained.
(2) Kindly enlighten me about the dailyduties of a br<193>hma<207>a ç
in detail.
@SPACE1 = 
The reply given by the Lord <185>iva may be summarised as follows:
Before sunrise, fresh cowdung is to be collected on a pal<193>·a leaf ç
(Butea frondos), dried and then reduced to ashes in the g<216>hya ç
fire duly established, using materials  like  sesame  or  paddy  soaked ç
in ghee, which should be offered into thefire with appropriate mantras ç
like tryambaka<221> yaj<193>mahe and som<193>ya sv<193>h<193>. ç
The ashes, after being consecrated through the G<193>yatr<200>-mantra, ç
should be collected in a pot made of gold or silver or even mud. Taking ç
some of it in the palm of the left hand, it should be applied on all ç
parts of the body like the head, forehead, ears, neck, arms, chest ç
and navel, repeating themantras prescribed for each of the application.
In case the duly prepared bhasma is not available, the bhasma gathered ç
from a cremation ground or any other place may be used after purifying ç
it with appropriate mantras.
Applying the bhasma as prescribed is a sacred and compulsory duty ç
for a br<193>hma<207>a. If he fails to do so he incurs sin which has ç
to be expiated by the repetition of the G<193>yatr<200>-mantra, while ç
standing in water and fasting. However, if he does it as prescribed, ç
he will be freed from all sins, and obtains the fruits of pilgrimage ç
to all the holy places as also a long life.
As for the daily duties of a br<193>hma<207>a the Lord <185>iva gives ç
a detailed procedure for bath, putting on clean washed clothes, anointing ç
with bhasma and wearing rudr<193>k<218>a beads.
This is then followed by instructions for worshipping the <185>ivali<209>ga ç
(the emblem of <185>iva). This has to be done thrice a day. Meditation ç
on Lord <185>iva's form, bathing the li<209>ga with water as also ç
the bhasma and  worship  with  the  bilva  (Aegle marmelos) leaves, ç
are its constituents.
Next, the Lord teaches the mantra of six letters (O<221> nama· ·iv<193>ya) ç
and the mantra of eight letters (O<221> namo mah<193>-dev<193>ya). ç
These are called `t<193>rakamantras' since they help the human being ç
to cross (t<193>raka = that which helps one to cross) the ocean of ç
sa<221>s<193>ra or transmigration.
Then comes a description of <185>iva as Brahman, followed by the assertion ç
that knowledge of <185>iva-Rudra leads to mok<218>a or liberation.
@SPACE1 = 
Lord <185>iva is the support of the whole
