@H = B
@NT = B<193>bhravya
@N1 = (`descendant of Babhru')
Being a patronymic name it represents anyone who is a descendant of ç
the sage Babhru. The sage Girija of the Aitareya Br<193>hma<207>a ç
and the sage <185>a<209>kha of Jaimin<200>ya Upani<218>ad Br<193>hma<207>a ç
were B<193>bhravyas.
The sage G<193>lava, mentioned in the Mah<193>bh<193>rata, was also ç
a B<193>bhravya. He was a great yogi and had organized the science ç
of euphony of the Vedas (called <185>ik<218><193>).
The Sk<193>ndapur<193><207>a mentions a B<193>bhravya. Arjuna, the ç
P<193><207><195>ava hero, during his pilgrimage, met B<193>bhravya ç
and heard from him about the greatness of the sage N<193>rada.
One B<193>bhravya is said to have produced a condensed version of ç
K<193>ma-·<193>stra (the Science of Erotics), originally written by ç
<185>vetaketu.
@NT = Babhruv<193>hana
When Arjuna, the P<193><207><195>ava hero, was on a tour, as penance, ç
he went to the kingdom of Citrav<193>hana, ruling at Ma<207>al<220>r. ç
The king offered his daughter Citr<193><209>gad<193> in marriage to ç
him. Babhru-v<193>hana was the son born to them. He grew up into a ç
great warrior worthy of his father.
After the Kuruk<218>etra war, when Yudhi<218><219>hira decided to ç
perform the A·va-medha sacrifice, Arjuna escorted the sacri-ficial ç
horse through various kingdoms. The horse was caught by Babhruv<193>hana; ç
andin the ensuing fight Arjuna was killed by him, but was revived ç
by Ul<220>p<200>, another wife of Arjuna, by placing the Sa<210>j<200>vaka-ma<207>i, ç
a precious stone capable of reviving dead persons, on his chest.
Babhruv<193>hana attended the A·va-medha sacrifice at Hastin<193>pura.
See also <MS>CITR°<177>GAD°<D> and <MS>UL<188>P®.<D>
@NT = B<193>d<193>mi
Nestling at the foot of steep hills, this small town is situated in ç
the Bijapur district of Karnataka State. Known as V<193>t<193>pi in ç
the ancient days, it was the capital of the C<193>lukyan empire during ç
the period <MS>A.D.<D> 550-753. It contains several temples of the ç
structural as well as the rock-cut varieties. Near the fort there ç
are temples dedicated to Hanum<193>n and <185>iva. On the southern ç
hill, situated on its western side, there are four cave-temples (three ç
Hindu and one Jain). They resemble the ones at Ellora. The pillared ç
halls in them show a high standard of workmanship and are uniformly ç
of the same appearance. The pillars are mostly square in section though ç
a few of the inner colonnade in Cave no.3 are multifaceted.
In the first cave are seen images of <185>iva with 18 arms, Ga<207>e·a, ç
Vi<218><207>u, Lak<218>m<200> as also <185>iva-P<193>rvat<200>. The ç
back wall containspanel-figures of Mahi<218><193>suramardin<200> ç
(Durg<193>), Ga<207>e·a and Skanda. The second cave contains images ç
of V<193>mana, Var<193>ha, N<193>r<193>ya<207>a on Garu<195>a and ç
N<193>r<193>ya<207>a on the serpent <185>e<218>a. The third cave has ç
images and figures of Ardhan<193>r<200>·vara, P<193>rvat<200>, Narasi<221>ha ç
and Var<193>ha. The fourth cave contains the images of the Jain T<200>rtha<209>karas.
Among the structural temples, the M<193>legitti <185>iv<193>laya built ç
on a hill over- looking the town of B<193>d<193>mi needs special mention. ç
It is a massive solid structure, though not very large. It consists ç
of a cella, an assembly hall and a porch.
There are fine frescos, very much like those of Ajanta, in Cave no. ç
3. The most important and well-preserved of these is that of the betrothal ç
of P<193>rvat<200> to <185>iva. These paintings belong to the 6th ç
century <F51320P10MSC1>A. D.<W1>
See also <MS>AIHO<170>E<D> and <MS>PATTADAKAL.<D>
@NT = B<193>dar<193>ya<207>a
Ved<193>nta is the last of the six systems of Indian philosophy. B<193>dar<193>ya<207>a ç
is stated to be its author. Hindu tradition identifies him with Veda-Vy<193>sa ç
(also known as K<216><218>naDvaip<193>yana), the celebrated author ç
of the Mah<193>bh<193>rata. Lexicographers like Hemacandra (<F51320MS>A.<|>D.<W1> ç
<F255D>1088-1173) (vide his Abhidh<193>nacint<193>ma<207>i†Martyak<193><207><195>a, ç
512) support this view. Since he lived along with his disciples and ç
son <185>uka, at the Badar<200> in the Him<193>layas, he might have ç
used this name in his composition, the Brahmas<220>tras.
B<193>dar<193>ya<207>a appears in the S<193>ma-vidh<193>na Br<193>hma<207>a ç
of the S<193>maveda. Var<193>hamihira (<F51320MS>A. D.<W1> <F255D>505-587) ç
and Bha<219><219>otpala (10th cent. <F51320MS>A. D.<W1>) <F255D>well-known astronomers, ç
have mentioned another B<193>dar<193>ya<207>a in their works. But, ç
they are different from B<193>dar<193>ya<207>a-Vy<193>sa.
See also <MS>VY°SA.<D>
@NT = Badarik<193>·rama
See <MS>BADAR®N°THA.
@NT = Badar<200>n<193>tha
@N1 = (`Lord of Badar<200>')
@SPACE = 
@SPACE = 
T<200>rthay<193>tr<193> or pilgrimage to holy places has been an age-old ç
exercise under- taken by the pious Hindus. The Him<193>layas and the ç
river Ga<209>g<193> have so captivated the Hindu mind for generations ç
that a majority of these places of pilgrimage is associated with them. ç
Badar<200>n<193>tha, also spelt as Badrin<193>th, situated in the ç
Chamoli district of Uttaranchal, is one of the most important of these ç
and has been classed among the `Caturdh<193>mas' (the four Holy Places), ç
the other three being Dv<193>rak<193> in Western India, Pur<200> in ç
Eastern India and R<193>me·varam in South India. A visit to these ç
four places has been a life-time's ambition of many a devout Hindu ç
since it is as good as covering all important places of pilgrimage ç
in the country.
The place itself might have derived its name from the existence of ç
Badar<200> or the jujube tree in plenty in that area.
Even from the most ancient days, Badar<200>n<193>tha has been considered ç
as very sacred. It was known as Badarik<193>·rama. It was here that ç
the twin sages, Nara-N<193>r<193>ya<207>a, had built their hermitage ç
and performed severe austerities. The sage Par<193>·ara and Vy<193>sa, ç
the celebrated author of the Mah<193>bh<193>rata, lived here with ç
their disciples. Consequently Vy<193>sa got the by-name B<193>dar<193>ya<207>a.
The town is situated at a height of about 7000 metres (23,300 ft.), ç
in a valley nearly 6 kms. long and 2 kms. wide (4miles by 1.3 miles). ç
The temple is on the right bank of the river Alakanand<193>.
The original temple is said to have been built by <185>a<209>kar<193>c<193>rya ç
in the 8th century <F51320P10MSC1>A.D.<W1>, <F255P255DC255>after recovering ç
the old image from the N<193>rada Ku<207><195>a (pond). Over the centuries, ç
avalanches washed out many a temple and the present one is comparatively ç
a modern structure.
Near the temple is a hot-water pond called `Taptaku<207><195>a', with ç
a thermal spring of sulphurous waters. A bath here is a must, before ç
the visit to the temple.
The temple of Lord N<193>r<193>ya<207>a is about 13.5 metres (45 ft.) ç
in height and faces east. There is a golden kala·a or pinnacle on ç
the top. The image inside the temple is made of `·<193>lagr<193>ma·il<193>' ç
or black stone. It is in the padm<193>sana or seated posture, with ç
four arms, carrying the well-known symbols ·a<209>kha (conch), cakra ç
(discus), gad<193> (mace) and padma (lotus). Other images found in ç
the temple are those of Nara and N<193>r<193>ya<207>a, Uddhava, N<193>rada, ç
Garu<195>a and Kubera.
The chief priest called `R<193>val' is a Namb<220>diri br<193>hma<207>a ç
from Kerala, as perthe traditions established by <185>a<209>kar<193>c<193>rya.
The temple, being situated among the mountains of the Him<193>layan ç
snow range, is open to the devotees only for about six months (April-May ç
to November). The utsavam<220>rti (image used in temple processions) ç
is shifted to the temple of Narasi<221>ha at Joshimath, a place situated ç
at a distance of 48 kms (31 miles) from Badarinath and worshipped ç
there during the winter months. The chief priest and his entourage ç
also shift to this place for this purpose. The `Jyotirma<219>ha,' ç
one of the four principal monasteries established by <185>a<209>kar<193>c<193>rya ç
is also situated here.
Lord Badar<200>n<193>tha is worshipped in five different places. Hence ç
they are collectively called `Pa<210>cabadar<200>s.' They are: Vi·<193>laBadar<200> ç
(the main Badar<200>nath); Yogadhy<193>na Badar<200> (at P<193><207><195>uke·vara, ç
about 24 kms. [16 miles] away from Badar<200>nath);  Bhavi<218>ya  Badar<200>  (near ç
Tapovana, about 17 kms. [11 miles] away from the Joshimath); V<216>ddha ç
Badar<200> (at Animath, 17 kms. from Joshimath in the direction of ç
Pipalkot) and °di Badar<200> (about 16 kms. [10 miles] from Kar<207>a-pray<193>g ç
on the road to R<193><207>ikhet).
It is believed that if ·r<193>ddha (obsequial ceremonies) is offered ç
here at the place called `Brahmakap<193>la' on the bank of Alakanand<193> ç
to the dead ancestors, they are liberated at once. Hence it is no ç
more necessary to continue the annual ·r<193>ddhas.
@NT = b<193>dha
@N1 = (`that which contradicts')
The word has several meanings: abh<193>va or absence; pratibandha ç
or obstacle; p<200><195><193> or harassment. However, it is the Ny<193>ya ç
school (of Indian Philosophy) that uses it as a technical term of ç
logic.
In the sentence, parvato vahnim<193>n dh<220>m<193>t (`The hill ç
is fiery, since there is smoke there'), vahni or fire is called `s<193>dhya' ç
(the major term), parvata or hill is called `pak<218>a' (the minor ç
term) and dh<220>ma or smoke as `hetu' or `li<209>ga' (the middle ç
term).
In a situation where the s<193>dhya does not exist in the pak<218>a, ç
then the pak<218>a is called b<193>dha. For instance, in the sentence ç
hrado vahnim<193>n dh<220>m<193>t (`The lake is fiery, since there ç
is smoke there') the minor term hrada or lake, which is the pak<218>a, ç
is `b<193>dha' since it is impossible for the fire, the s<193>dhya, ç
to exist in the lake. The lake obstructs or prevents (b<193>dha = ç
obstacle) fire from existing in it.
Many more varieties of b<193>dha are discussed in the works of Indian ç
logic.
@NT = b<193>dhita
@N1 = (`contradicted')
In the Ny<193>ya school of Indian philo-sophy, a material fallacy ç
is technically called `hetv<193>bh<193>sa,' which literally means ç
that a hetu or reason which appears as, but really is not, a valid ç
reason. Out of the five hetv<193>bh<193>sas generally listed, `b<193>dhita' ç
is the last.
Consider the sentence agniranu<218><207>a<199> dravyatv<193>t, `Fire ç
is cold, since it is a substance'. Here anu<218><207>atva or coldness ç
is the s<193>dhya (major term) and dravya or substance is the hetu ç
(middle term). The non-existence of coldness, nay more, the existence ç
of hotness, is perceived in fire by our sense of touch. So, we have ç
toreject hetu or the middle term, dravyatva (being a substance), ç
as it is b<193>dhita or contradicted by another means of knowledge ç
(here, pratyak<218>a or direct perception).
@NT = Bahi<218>pavam<193>na
@N1 = (`Pavam<193>na<R>ç
chanted outside')
Among the various types of Vedic sacrifices, the Somay<193>ga is an ç
important one. It derives its name from the fact that the juice of ç
the soma creeper is used as oblation. This juice is pressed out of ç
the creepers by stones or mortar and pestle, and is purified by being ç
passed slowly through a strainer of sheep's wool. It is then transferred ç
to jars and mixed with milk.
There are three savanas or press- ings†morning, noon and evening, ç
known respectively as pr<193>tas-savana, m<193>dhyan-dina-savana and ç
t<216>t<200>ya-savana.
The Bahi<218>pavam<193>na is the stotra or hymn that is chanted during ç
the pr<193>tas-savana. Since it is outside (bahir = outside) the sadas ç
or the assembly hall, it is called Bahi<218>pavam<193>na.
It consists of three t<216>cas or triplets of <184>gvedic mantras ç
(9.11.1-3; 9.64.28-30; 9.66.10-12) making a total of nine verses. ç
These verses are sung as S<193>mans (S<193>ma-vedic chants) in a special ç
style called `triv<216>t' wherein the first verse of each triplet ç
is chanted first followed by the second and the third. If the verses ç
of each triplet are symbolically represented as a,b and c, the scheme ç
of chanting will be thus: a1+a2+a3; b1+b2+b3+; c1+c2+c3.
In sum, these verses welcome the deity presiding over the soma juice, ç
beg him to protect the family and property of the sacrificer and describe ç
the graceful flow of the juice through the strainer.
@NT = B<193>hl<200>ka
The country of B<193>hl<200>ka (also spelt as B<193>hlika or V<193>hl<200>ka) ç
has been mentioned in the epic Mah<193>bh<193>rata (Bh<200><218>maparva9). ç
It has been identified with Bactria, north of Afghanistan and east ç
of Iran. Arjuna, the P<193><207><195>ava hero, conquered this country ç
during his victory marches before the R<193>jas<220>ya sacrifice. ç
The people of this country had come in for a lot of criticism due ç
to their unethical ways of life (Kar<207>aparva 44). The R<193>m<193>ya<207>a ç
(Ayodhy<193>k<193><207><195>a 68.18) alludes to a country called ç
B<193>hl<200>ka, situated between Ayodhy<193> and Kekaya, which again ç
extended between the rivers <185>atadr<220> (Sutlej) and Vip<193>·<193> ç
(Beas).
The word B<193>hl<200>ka also refers to the king of that country who ç
fought for Duryodhana against the P<193><207><195>avas. There is also ç
the mention of another B<193>hl<200>ka, younger brother of king <185>antanu, ç
the father of Bh<200><218>ma.
@SPACE = 
@NT = B<193>hud<193>
@N1 = (`that which gives arm')
The ancient sages of India strove to maintain the highest standards ç
of ethical purity in their personal life as well as social life. <185>a<209>kha ç
and Likhita, the brothers whose Sm<216>ti has earned a place for ç
itself in the dharma·<193>stra literature, were men of such sterling ç
character. Once Likhita, the younger brother, went to the hermitage ç
of <185>a<209>kha and ate some fruits from the garden without his ç
prior permission. He realized the mistake which amounted to stealing ç
and confessed the same to <185>a<209>kha. <185>a<209>kha sent him ç
to the king Sudyumna. The king cut off his arms as a punishment. Likhita ç
returned to <185>a<209>kha who approved of the punishment, but directed ç
him to take a bath in the nearby river. When Likhita did so, he regained ç
his arms. Since then, the river got the name `B<193>hud<193>,' `that ç
which gave arms'. It is identified with a river near Ayodhy<193>.
See also <MS><185>A<177>KHA<D> and <MS>LIKHITA.<D>
@SPACE = 
@NT = Bah<220>daka
See <MS>PARAMAHA<189>SA.<D>
@SPACE = 
@NT = B<193>huka
The story of the king Nala and his wife Damayant<200> is well-known ç
in the romantic literature of India.
After banishment from his kingdom, Nala retired to a forest, deserted ç
Dama-yant<200> there, was bitten by a cobra in hissojourns and was ç
disfigured. He changed his name to B<193>huka and lived incognito ç
for some time before regaining his kingdom.
See also <MS>DAMAYANT®<D> and <MS>NALA<D>.
@NT = Bahul<193>
Bahul<193>  (also  known  as  Bahul<193>- caturth<200>) is one of ç
the minor festivals observed in the northern parts of India on the ç
fourth day of the dark fortnight (k<216><218><207>a-caturth<200>) ç
of the month of Bh<193>dra (September). It is generally observed by ç
women who have children. After the usual fasting and prayers as prescribed ç
for such festivals, a cow with a calf is worshipped in the evening ç
and also offered some sweets in an earthen pot. Fast can be broken ç
only after that, with cooked barley. An observance of this festival ç
with its vows is said to confer children and wealth on the votary.
This festival is connected with two folk tales: A cow was caught by ç
a hungry lion, begged the lion to allow it to feed its little calf ç
at home and then return. The lion obliged and the cow returned, true ç
to its promise. Moved by its devotion to truth, the lion let it go. ç
It was on this day that the truthful cow was liberated by the lion.
A lady, Vipul<193> by name, took the dead body of her young husband ç
on a raft by a river called Bahul<193>, to the world of the serpent ç
goddess Manas<193> and got him revived on this day. Hence, listening ç
to this story on this day gives religious merit.
@NT = bahv<216>ca
@N1 = (`relating to that which contains many <216>ks')
A verse of the <184>gveda is known asa `<216>k.' That in which ç
there are a largenumber of such <216>ks is `bahv<216>c,' (bahu ç
= many) the <184>gveda itself. Anything related to this is `bahv<216>ca.'
The word is generally used to indicate a follower of the <184>gveda. ç
The hot<216> priest in a sacrifice, since he represents the <184>gveda, ç
is also called as a bahv<216>ca.
@NT = Bahv<216>copani<218>ad
This is one of the minor Upani<218>ads of recent origin (c. 13th cent. ç
<F51320P10MSC1>A. D.<W1>) <F255P255DC255>and sectarian in character. It belongs ç
to the <184>gvedic tradition (See <MS>BAHV<184>CA<D>.) and deals with ç
the Goddess or <185>akti. The entire Upani<218>ad, which is a short ç
one, is in prose except for quotations.
In the beginning, the Dev<200> or the Goddess alone existed. She created ç
the Cosmic Egg. Brahm<193>, Vi<218><207>u and Rudra were born out ç
of her; so also various otherbeings like the maruts (wind-gods), ç
gandharvas (celestial minstrels), apsaras (nymphs) and beings of this ç
earth.
She is the Power Supreme. She is the various arts and sciences like ç
the <185><193>mbhav<200>-vidy<193> (the science of <185>ambhu or God), ç
the K<193>di-vidy<193>, the H<193>di-vidy<193> and the S<193>di-vidy<193> ç
(sciences related to the Divine Mother). She is Om and abides in the ç
realm of words as their import. She is Mah<193>tripurasundar<200>, ç
pervading the three bodies†the gross, the subtle and the causal†as ç
pure consciousness. She alone is the °tman. Nothing exists apart from ç
her. What is contemplated upon by the mah<193>v<193>kyas (See <MS>MAH°V°KYAS<D>.) ç
is she herself. It is she that is called by various names such as: ç
B<193>l<193>, Ambik<193>, Bagal<193>, M<193>ta<209>g<200>, Bhuvane·var<200>, ç
C<193>mu<207><195><193>, V<193>r<193>h<200>, A·v<193>r<220><195>h<193>, ç
Pratya<209>gir<193>, Dh<220>m<193>vat<200>, S<193>vitr<200>, Sarasvat<200> ç
and so on. (See under each name for details.)
@NT = baindava-·ar<200>ra
@N1 = (`body comprising the bindu')
Among the several schools of <185>aivism, the Siddha school has a ç
concept of mukti or liberation, peculiar to itself. Mukti is incomplete ç
if it is confined only to the elimination of future births after ç
death. It becomes complete only when death here is also transcended. ç
A s<193>dhaka or aspirant of the Siddha School, through appropriate ç
exercise and spiritual practice, is able to transmute every cell in ç
his body so that it is transformed from a·uddha-m<193>y<193> (impure ç
m<193>ya or nature)-state to ·uddha-m<193>y<193> (pure m<193>y<193> ç
or nature)-state. This transformed body which is incorruptible, is ç
called `pra<207>avatanu' (body of pra<207>ava or Om) or `baindava-·ar<200>ra' ç
(body comprising the binduor divine power†·akti). Then he becomes ç
a `j<200>vanmukta' (one liberated even while living).
See also <MS>SIDDHA-DAR<185>ANA.<D>
@NT = Baka
Baka or Bak<193>sura was a r<193>k<218>asa (demon) who lived near ç
the small town Ekacakranagara. Since he used to attack the town and ç
eat up the human beings there, the residents of the town had made ç
an agreement with him to supply food and one adult human being every ç
day from among them, by turns. When the P<193><207><195>avas were ç
living there after being exiled, Bh<200>ma (the second of the P<193><207><195>ava ç
brothers) managed to kill him, thus ridding the town of a great menace ç
(vide Mah<193>-bh<193>rata, °diparva-163).
The Bh<193>gavata (10.12) mentions of another demon Baka (in the ç
form of a crane) who was killed by K<216><218><207>a.
@NT = Baka-d<193>lbhya
@N1 = (`Baka, a descendant of Dalbha')
The Ch<193>ndogya Upani<218>ad (1.2.13) mentions one Baka-d<193>lbhya, ç
as a sage who had realized the pr<193><207>a (the chief vital air ç
in the body and the deity presiding over it) through the singing of ç
the udg<200>tha (a part of the s<193>ma hymn). He was the udg<193>t<216> ç
priest in the sacrifice performed by the Naimi·<200>yas and successfully ç
got them what they wanted.
The Jamin<200>ya Upani<218>ad Br<193>hma<207>a states (1.9.2) that ç
Baka-d<193>lbhya restrained Indra from harming the °jake·ins (mem-bers ç
of a particular family).
The V<193>manapur<193><207>a (ch. 39) gives the story of a sage ç
Baka-d<193>lbhya who was about to destroy the kingdom of a ruler, ç
Dh<216>tar<193><218><219>ra by name, through a sacrifice. The latter ç
meanwhile realized his mistake†he had slighted the sage once†made ç
amends for the same, pleased the sage and got back all that he had ç
lost.
It is rather difficult to say whether all these Baka-d<193>lbhyas ç
were one and the same. The possibility cannot be ruled out.
@NT = Bakapa<210>caka
@N1 = (`pentad related to the crane')
Vratas or religious vows and observances are an integral part of Hinduism ç
in practice. They are common even today. Among the several such vratas, ç
`Baka-pa<210>caka' is one listed by religious digests. The five days ç
from K<193>rttika ·ukla ek<193>da·i (eleventh day of the bright fortnight ç
in the month of K<193>rttika, generally falling in November) to p<220>r<207>im<193> ç
(the full-moon day) are so called since it was believed that even ç
a baka or a crane will not eat meat in these days. Hence, abstaining ç
from eating meat during these five days is the main discipline expected ç
of the votary.
See also <MS>VRATAS<D>.
@NT = bala
@N1 = (`strength;' `armed forces')
The literal meaning of the word `bala' is `strength.' However, the ç
word is often used in a metaphorical sense, as for instance in statements ç
like `dhigbala<221> k<218>attriyabala<221> brahmatejobala<221> balam;' ç
(`Fie be unto the power of the k<218>attriya! The power of lustre ç
of Brahman is verily the power!'). There are other interesting statements ç
such as: v<193><207>ijya (trade) is the bala of a vai·ya; yuddha (war) ç
is the bala of a k<218>attriya; dhana (wealth) is the bala of a rich ç
man; rodana (crying) is the bala of a child; an<216>ta(falsehood) ç
is the bala of thieves; Param<193>tman (God) is the bala of devotees ç
and so on.
Works on Hindu political science like the Artha·<193>stra of Kau<219>ilya ç
(300 <P8W1>B.C.<P255D>) declare that a r<193>jya or state is constituted ç
by seven elements like sv<193>min (ruler or sovereign), am<193>tya ç
(minister), janapada or r<193><218><219>ra (the territory of the State ç
and its people) and so on. Da<207><195>a or bala (armed forces) is ç
one of these seven constituents.
Most of the ancient and early medieval works state that a big army ç
should consist of four constituents; hence the name `catura<209>ga-bala,' ç
`armed forces with four parts'. They are hasti (elephants), a·va (horses), ç
ratha (chariots) and pad<193>ti (foot-soldiers).
The works also mention six kinds of troops: maula (hereditary troops), ç
bh<216>ta or bh<216>taka (mercenary troops), ·re<207>i (guild troops), ç
mitra (troops of an ally), amitra (troops that once belonged to an ç
enemy) and a<219>av<200> or <193><219>avika (wild tribes as troops). ç
The earlier varieties of troops are superior to the later ones.
The Mah<193>bh<193>rata declares that out of the several balas of ç
a king like b<193>hubala (brute force), dhanabala (power of wealth), ç
am<193>tyabala (power due to the right type of ministers) and so on, ç
praj<210><193>bala (power of wisdom) is the greatest (Udyogaparva ç
37.52-55).
Balar<193>ma, K<216><218><207>a's elder brother is also known as Bala. ç
(For details see <MS>BALAR°MA<D>.)
@NT = B<193>l<193>
@N1 = (`the girl-child')
Worship of <185>akti or the Mother Goddess is a very ancient practice ç
in India. Of the several aspects of the Divine Mother P<193>rvat<200>, ç
Lalit<193> or Lalit<193>-Tripurasundar<200> is very important and ç
popular. B<193>l<193> (also called B<193>l<193>-Tripurasundar<200>) ç
is an aspect of this Lalit<193>. Sometimes she is described asthe ç
daughter of Lalit<193> who helped herto destroy the army of the demon ç
Bha<207><195><193>sura.
As her very name suggests, B<193>l<193> is pictured as an eternal ç
girl of nine years. Iconographical works describe her as red in colour ç
like hibiscus flower. She has four arms carrying ak<218>am<193>l<193> ç
(rosary), p<193>·a (noose), a<207>ku·a (goad) and pustaka (book).
B<193>l<193> is specially worshipped, by those desiring psychic powers.
See also <MS>LALIT°<D>.
@NT = Balabhadra
This is one of the several names by which Balar<193>ma, the elder ç
brother of K<216><218><207>a, was known. See <MS>BALAR°MA<D> for details.
@NT = Baladeva
In the Hindu mythological lore `Baladeva' is one of the several names ç
by which Balar<193>ma, the elder brother of K<216><218><207>a, was ç
known.
@NT = Baladeva Vidy<193>bh<220><218>a<207>a
Among the luminaries of the Bhakti Movement that energized the Hindu ç
masses  during  the  middle  ages,  the greatest, perhaps, was <185>r<200>k<216><218><207>a ç
Caitanya (<F51320P10MSC1>A.D.<W1> <F255P255DC255>1485-1533), more commonly known ç
as Caitanya Mah<193>prabhu. His teachings gradually got metamorphosed ç
into a system of philosophy, now well-known as the Acintyabhed<193>bheda ç
school. Baladeva Vidy<193>bh<220><218>a<207>a who lived in the early ç
18th century, is an important writer of this school. He was born in ç
a village near Remuna in Orissa. He was a pupil of Vair<193>gi P<200>t<193>mbara ç
D<193>sa. Out of the 14 works attributed to him, the Govinda-bh<193><218>ya, ç
a commentary on the Brahma-s<220>tras is most well-known. It has ç
a subcommentary called S<220>k<218>ma, the author of which is unknown.
@NT = B<193>la-Ga<207>apati
@N1 = (`Ga<207>apati, the boy')
Among the several gods of the Hindu pantheon, Ga<207>apati, the elephant-headed ç
god is one of the most widely worshipped. Temples to him are also ç
legion.
There are several aspects of Ga<207>apati, of which B<193>la-Ga<207>apati ç
is one. He is represented iconographically as a boy, holding a mango, ç
a plantain, a jack-fruit and a sugar-cane in his four hands. With ç
his trunk he holds a wood-apple. His colour is that of the rising ç
sun.
See also <MS>GAØAPATI<D>.
@NT = B<193>l<193>j<200>
See <MS>TIRUPATI<D> and <MS>VE<177>KA<187>E<185>VARA.<D>
@NT = B<193>lak<193><207><195>a
This is the first book of the well-known epic R<193>m<193>ya<207>a ç
of V<193>lm<200>ki.
See <MS>R°M°YAØA<D> for details.
@NT = B<193>l<193>ki
@N1 = (`Son of Bal<193>k<193>')
The B<216>had<193>ra<207>yaka Upani<218>ad (2.1) mentions one sage ç
B<193>l<193>ki (Son of the lady Bal<193>k<193>) who was G<193>rgya ç
(a descendant of the sage Garga). He was nicknamed `D<216>pta-B<193>l<193>ki' ç
since he was a vain person (d<216>pta=vain). He had mastered one ç
aspect of the knowledge of Brahman. He went to the King Aj<193>ta·atru ç
of K<193>·<200> and expressed his desire to teach him. The King, who ç
was more learned, and could see through his vanity, proved his superi-ority. ç
Then B<193>l<193>ki became his disciple andlearnt about the Brahman ç
without attributes.
B<193>l<193>ki is also one of the names of the hundred sons of the ç
king Dh<216>tar<193><218>t<216>a, the father of Duryodhana.
@NT = b<193>lak<216>cchra
@N1 = (`the small penance')
P<193>taka (sin) and pr<193>ya·citta (expi-ation of sin) are two of ç
the widely discussed topicsin the sm<216>tis and dharma·<193>stras. ç
Sins may be serious (mah<193>p<193>takas) or minor(upap<193>takas). ç
The pr<193>ya·cittas prescribed for the mah<193>p<193>takas like killing ç
a br<193>hma<207>a or incest, often end in the death of the sinner. ç
But, those prescribed for the upap<193>takas like minor thefts or ç
abandoning the Vedic fires, are tolerable and purify the sinners.
K<216>cchra is a very general name givento most of these pr<193>ya·cittas. ç
B<193>lak<216>cchra†also called ·i·uk<216>cchra or laghuk<216>cchra†is ç
one variety prescribed for upap<193>takas in which the expiation is ç
light and easy. If k<216>cchras are usually spread over 12 days, b<193>lak<216>cchra ç
is observed only for 4 days. It consists in eating once only in day ç
time on the first day, once only in the night on the second day, eating ç
food that comes unasked, that too only once, on the third day and, ç
fasting on the fourth day. Other general rules as applicable to k<216>cchras ç
like bathing thrice daily, speaking the truth and so on, should also ç
be followed.
See <MS>K<184>CCHRA<D> and <MS>C°NDR°YAØA.
@NT = B<193>lakr<200><195><193>
Sm<216>tis are secondary scriptures which expound dharma, in consonance ç
with the <185>ruti or the Vedas. If the <185>ruti gives the general ç
spiritual truths, the sm<216>tis give elaborate details pertaining ç
to the code of conduct of an individual member of the society both ç
at the personal and at the social level. One of the earliest sm<216>tis ç
that ranks on almost equal terms with the Manusm<216>ti, is the ç
Y<193>j<210>avalkya Sm<216>ti. This work has two well-known commentaries: ç
the Mit<193>k<218>ar<193> of Vij<210><193>-ne·vara (12th cent. <F51320MS>A.D.<W1>) ç
<F255D>and the<F51320W1> <F255MI>B<193>lakr<200><195><193> of Vi·var<220>pa (9th ç
cent. <F51320MS>A. D.<W1>).
Being earlier than the Mit<193>k<218>ar<193>, the B<193>lakr<200><195><193> ç
is a pioneering work. Its author, Vi·var<220>pa shows a good grasp ç
of the P<220>rvam<200>m<193><221>s<193> terms and logic, but seems ç
to lean towards the advaita of <185>a<209>kara (<F51320MS>A.D.<W1> <F255D>788-820) ç
where philosophical ideas are concerned.<F51320W1>
Some scholars opine that Vi·var<220>pa and Sure·vara, a disciple of ç
<185>a<209>kara, are identical, `Vi·var<220>pa' being his premonastic ç
name.
See also <MS>VI<185>VAR<188>PA<D> and <MS>Y°J<178>AVALKYA SM<184>TI.<D>
@NT = b<193>l<193>laya
@N1 = (`the little temple')
Hindu temples, with their images, are built with materials like stone, ç
so that they can last long. Due to the ravages of time, weather, accidents ç
or any other cause, when the temple structure or the image is damaged, ç
needing repair or replacement, provision has been made in the <193>gamas ç
for the necessary ritualistic processes to transfer the `kal<193>' ç
or the power of the deity temporarily through a kala·a (consecrated ç
pitcher of water) to a new image and installed in a new temple provisionally ç
built for the purpose. Once the renovation work is over, the `kal<193>' ç
is transferred back to the old renovated temple and image.
The temporary structure put up for this purpose to house the deity ç
during the renovation work, so that the usual rituals can go on undisturbed, ç
is technically called `b<193>l<193>laya' or `the little temple', since ç
it is `small' compared to the original structure. It is generally ç
built in the front of the old temple, but to its left side, and its ç
door facing that of the old one. It should have both a garbhag<216>ha ç
(sanctum sanctorum) and a ma<207><195>apa (hall) attached to it. ç
The image may be made of either metal or wood.The entire process ç
of consecration of the b<193>l<193>laya is identical with that of ç
any newly built temple. Once the old temple is renovated, the kal<193> ç
is transferred back to the old image in the renovated shrine or to ç
the new image installed there,if the old one had been damaged necessitating ç
replacement. After this, the image of the b<193>l<193>laya has to ç
be burnt, if of wood, or melted, if of metal, and presented to the ç
<193>c<193>rya or preceptor. The old image of the original temple, ç
if replaced, should be taken in a procession and immersed deeply in ç
sea or river or lake.
@NT = Balapramathin<200>
@N1 = (`destroyer of strength')
<185>akti or divine power of God is often pictured as a goddess, as ç
the consort of the Deity. For instance, P<193>rvat<200> is the power ç
of <185>iva, personified as his consort. Out of the several such goddesses, ç
all being the aspects of the supreme <185>akti, Balapramathin<200> ç
is a minor one. Since S<220>rya or Sun is hot and enervating, this ç
deity represents the Sun as a tattva or principle. She is pictured ç
as white or reddish in complexion and has two hands carrying a kap<193>la ç
(skull) and a p<193>·a (noose). She is the destroyer of all enemies ç
and hence propitiated as such. Her consort is Ugra, a terrible aspect ç
of <185>iva.
@NT = Balar<193>ma
@N1 = (`R<193>ma of strength')
Balar<193>ma was the elder brother of K<216><218><207>a. He was conceived ç
as the seventh son of Devak<200> by Vasudeva. But the foetus was drawn ç
out of her by Yogam<193>y<193> (divine power) and placed in the womb ç
of Rohi<207><200>, the elder wife of Vasudeva, living at Nandagokula. ç
So he was born as the son of Rohi<207><200>. Since he was extraordinarily ç
strong, he was called `Balar<193>ma' (bala= strength). He had several ç
other names like Sa<209>kar<218>a<207>a, Rauhi<207>eya, Musal<200>, ç
Hal<200>, N<200>l<193>mbara and so on. As per the paur<193><207>ic ç
lore, he was the incarnation of °di·e<218>a (the serpent on which ç
Vi<218><207>u is resting in the K<218><200>ras<193>gara or ocean of ç
milk) come down to help K<216><218><207>a who was Vi<218><207>u himself. ç
He was an expert in fighting with gad<193> or mace. The plough (hal<193>) ç
was his favourite weapon. The Bh<193>gavata is full of his exploits. ç
Along with K<216><218><207>a, he too killed many a demon like Pralamba, ç
Dhenuka, Dvivida and Balvala. After the killing of Ka<221>sa by K<216><218><207>a, ç
Balar<193>ma too got his formal education under the sage S<193>nd<200>pani. ç
He married Revat<200>, the daughter of the king Revata. When the Kauravas ç
of Hastin<193>pura had abducted S<193>mba, a son of K<216><218><207>a, ç
he went there and rescued him. Itwas he who taught gad<193>-vidy<193> ç
(the science of fighting with the mace) to Bh<200>ma (the second of ç
the five P<193><207><195>avas) and Duryodhana (the eldest of the Kauravas). ç
He had a soft corner for the latter.
During the Kuruk<218>etra (or Mah<193>-bh<193>rata) war, he refused ç
to participate but went away on a pilgrimage. He reappeared at the ç
time of the duel between Bh<200>ma and Duryodhana. He tried to prevent ç
it but did not succeed. He was cross with Bh<200>ma for having flouted ç
the rules of mace-fighting but was pacified by K<216><218><207>a.
When the Y<193>davas exterminated one another in mutual fighting, ç
Balar<193>ma sat in yoga and left the body in the form of a serpent ç
thus confirming that he was °di·e<218>a.
See also <MS>K<184><186>ØA<D>.
@NT = balasiddhi
@N1 = (`power of physical strength')
The Yogas<220>tras of Pata<210>jali (200<|><F51320MS>B.C.<W1>) <F255D>is accepted ç
as a basic text of yoga and has been highly venerated. In the third ç
chapter of the work called Vibh<220>tip<193>da<F51320W1>,<F255D> various vibh<220>tis ç
or siddhis (supernatural powers) that a yogi obtains by the practice ç
of `sa<221>yama' are described; and balasiddhi is one of them. Sa<221>yama ç
is a technical term used to indicate the triad of dh<193>ra<207><193> ç
(fixing the mind on the object of concentration), dhy<193>na (meditation) ç
and sam<193>dhi (total absorption in the object thus chosen), practised ç
on one and the same object. This sa<221>yama results in the development ç
or manifestation of supernatural powers in the yogi.
If sa<221>yama is practised on the strength of an elephant (vide ç
Yogas<220>tras 3.24) or lion or the mythical bird Garu<195>a or Hanum<193>n ç
(the devotee of R<193>ma), the yogi develops a strength similar to ç
theirs. This is called `balasiddhi'.
@NT = B<193>lasubrahma<207>ya
@N1 = (`the boy<R>ç
Subrahma<207>ya')
Subrahma<207>ya†also known by several other names such as Kum<193>ra, ç
Skanda, K<193>rttikeya, <186>a<207>mukha and Guha†is a very popular ç
Hindu deity in South India, especially in Tamil Nadu. He is the son ç
of <185>iva and P<193>rvat<200> and the elder brother of Ga<207>e·a. ç
Many heroic exploits are attributed to him including the leading of ç
the armies of the gods and killing the formidable demon T<193>rak<193>sura. ç
Most of these were accomplished when he was still a `b<193>la' or ç
boy. Hence he is more often represented as `B<193>la-Subrahma<207>ya'. ç
Iconographical works describe him as red in colour, with only two ç
hands, holding a lotus in the right and keeping the left on the waist.
See also <MS>SUBRAHMAØYA<D>.
@SPACE = 
@NT = Balavikara<207><200>, Balavikara<207>ik<193>
@N1 = (`that which augments strength')
She is one of the several aspects of the Mother Goddess whose worship ç
will endow the votary with strength and peace. She is also classed, ç
sometimes, among the pariv<193>radevat<193>s or attendant deities ç
of the Divine Mother. Iconographically, she is described as grey in ç
colour with long eyes and two hands holding a kap<193>la (skull) and ç
ak<218>am<193>l<193> (rosary).
Occasionally she is stated to be the personification of the principle ç
of the moon (candratattva), responsible for the vigorous growth of ç
o<218>adhis or medical herbs. In this aspect, she is considered to ç
be the consort of Mah<193>deva (<185>iva).
See also <MS>SUBRAHMAØYA.
@SPACE = 
@NT = Bali
Like Prahl<193>da, Bali is another great name among the asuras or ç
demons who were devotees of Lord Vi<218><207>u. Actually, he was the ç
grandson of the former and the son of Virocana. After losing his life ç
in a battle with Indra, the king of devas or gods, he was revived ç
by his guru <185>ukr<193>c<193>rya. Hethen performed severe austerities, ç
got some divine weapons and then usurped svarga, the Kingdom of Indra, ç
after worsting him in the battle. When the gods appealed to Lord Vi<218><207>u ç
to restore their domain backto them, Vi<218><207>u incarnated himself ç
as V<193>mana, the Dwarf, approached Bali, who was well-known as extraordinarily ç
generous, for a gift of land and occupied all the three worlds in ç
the process of receiving it. He also pushed Bali down into the nether ç
world and restored to Indra and the gods, their lost svarga. Bali ç
became the Indra later, in another cycle of creation, known as S<193>var<207>ika  Manvantara.  He  is  listed ç
amongthe eight ciraj<200>vins (those who are immortal).
See also <MS>PRAHL°DA<D> and <MS>V°MANA.
@NT = bali
@N1 = (`that which is brought')
`Bali' is a technical term used for an offering of grain or cooked ç
rice to certain gods, household divinities, spirits, animals and even ç
lifeless objects that form a part of the householder's life. The bali ç
offerings are thrown, in the mornings, in the direction of the four ç
cardinal points or into the fire. Some of the offerings are placed ç
near the main door, in water, in the pestle and mortar, near the bed, ç
and so on. In the evenings bali is offered to the spirits that roam ç
about at night.
Bali also means the tax collected by the king.
The word is also used to signify the living beings offered in sacrifice ç
to fierce deities like Durg<193> and K<193>l<200>, as also in certain ç
Vedic sacrifices like Pa·ubandha.
@NT = B<193>l<200>
The spread of Hindu culture in the South East Asian countries like ç
Malaya, Java, Sumatra, Bali and Cambodia must have started as early ç
as the 1st century of the Christian era, if not earlier. Quite a few ç
of the kingdoms there were established by Hindu kings from India. ç
Along with them, as also the traders who preceded them, came Hindu ç
religion and culture including the Sanskrit language.
The B<193>l<200> island (called Balidv<200>pa in ancient texts) (also ç
spelt as Bali) which is a part of the present Indonesia and is situated ç
very near the much bigger Java, is still a citadel of Hindu religion ç
and culture. Its area is 5623 sq.kms. and the population, 2.1 millions. ç
It is an island full of hills and forests and includes a volcano which ç
sometimes gets active.
@EMERGENCY = The people follow Hindu religion quite actively. They ç
believe in gods, spirits and other supernatural beings and their influence ç
on human life. Appeasing these through yaj<210>as (sacrifices) is ç
a common feature of their religion. The sacraments of j<193>takarma, ç
n<193>makara<207>a, upanayana and viv<193>ha, to be performed at the ç
time of birth, initiation and marriage are also observed. Worship ç
of God as the family deity is common in all the houses. Animal sacrifices ç
to appease terrible deities like Durg<193> or certain demons are also ç
common. The few rivers of the island have been named as Sindh<220>, ç
Ga<209>g<193> and K<193>ver<200> though their waters are not considered ç
as sacred. The caste system is very much prevalent and the br<193>hma<207>a ç
has an important place in all religious activities. Influence of the ç
Sanskrit language is also clearly seen.
@NT = balihara<207>a
@N1 = (`distributing the balis or<R>ç
offerings')
`Balihara<207>a' is the same as `bh<220>ta- yaj<210>a', one of the ç
pa<210>cayaj<210>as or five daily sacrifices to be performed by every ç
householder. The balis or offerings of cooked rice are kept on the ç
ground, properly cleaned, to be accepted by the domestic deities, ç
by the deities of water, of herbs and others. As part of this rite, ç
food is to be offered to other human beings in need of the same, as ç
also animals, out of compassion.
See also <MS>VAI<185>VADEVA<D>.
@NT = balip<200><219>ha
@N1 = (`pedestal for offering')
Balip<200><219>ha or a pedestal where balis or food offerings are ç
made, is an essential part of a Hindu temple. Situated usually near ç
the dhvajastambha or the flagpost, but nearer the shrine, it is a ç
raised platform made of stone, the height being generally one-eighth ç
that of the garbha-g<216>ha or the sanctum sactorum. Materials other ç
than stone, like metal, mud or bricks, may also be used.
The balip<200><219>ha may be square, rectangular, octagonal, sixteen-sided ç
or circular; and will have several tiers, each tier providing space ç
for a particular class of celestial beings like the dikp<193>las (guardian ç
deities of the quarters), apsar<193>s (celestial nymphs), pi·<193>cas ç
(goblins) and so on, to receive the food offered.
After the main deity is served with naivedya or food, the priests ç
begin a procession for feeding the guardian deities and minor deities. ç
The first one to receive the offering is the `balibera' or the movable ç
metallic image, which is then carried in the procession. After circumambulating ç
the main deity, the food offering is kept on the balip<200><219>ha.
Balis or food-offerings are given only in the temple worship and not ç
in the worship at home.
@NT = Balipratipad<193>
Considered as one of the three most holy days of the Hindu Calendar, ç
Bali-prati-pad<193> falls on the K<193>rttika ·ukla- pratipad (first ç
day of the bright fortnight of  the  month  K<193>rttika,  generally  in ç
November). It is also one of the three days of the D<200>p<193>val<200> ç
(also spelt as Div<193>l<200>) festival, the festival of lights. It ç
was onthis day, according to the Hindu mythology, that Bali, the ç
emperor of the asuras or demons, was conquered by Lord Vi<218><207>u ç
and was granted several boons since he was a great devotee.
Worship of an image of Bali along with that of his consort Vindhy<193>val<200>, ç
is an important item of the festival, especially for kings. Gifts ç
given on this day produce manifold results.
Worship of cows and bulls as also the hill Govardhana (See <MS>ANNAK<188><187>A<D>.), ç
tying of the M<193>rgap<193>l<200> (lit., protectress of the road) ç
or a rope of ku·a grass between a pole and a tree across a road and ç
passing under it, and playing dice, are some of the items generally ç
observed during this festival. A paur<193><207>ic story of the game ç
of dice between <185>iva and P<193>rvat<200> seems to be at the back ç
of this practice of dice-play. Hence the name `Dy<220>tapratipad<193>' ç
also for this day.
Sometimes, a ceremonial tug-of-war is also arranged in front of a ç
temple or the palace, between the princely class and the commoners, ç
the latter always `winning' at the end! Occasionally, images of Agni ç
and Brahm<193> are established on a ratha or chariot and worshipped. ç
The chariot is then drawn round the streets of the town. Hence this ç
festival is also called `Balipratipad<193>-rathay<193>tr<193>vrata'.
See also <MS>D®P°VAL®.
@NT = B<193><207>a
B<193><207>a or B<193><207><193>sura was the eldest son of the demon ç
king Bali. He was a great devotee of Lord <185>iva and had obtained ç
several boons from him. Aniruddha, the grandson of K<216><218><207>a, ç
had surreptitiously married B<193><207>a's daughter U<218><193> at ç
her request. This led to a war between K<216><218><207>a and B<193><207>a ç
in which the latter was defeated.
B<193><207>a is also the name of another asura or demon who had constructed ç
three flying cities. At the behest of the gods like Indra, <185>iva ç
spared his life and permitted him to live in the Svar<207>apura (the ç
golden city).
@NT = b<193><207>ali<209>ga
@N1 = (`li<209>ga of B<193><207>a')
B<193><207>ali<209>gas are natural li<209>gas of <185>iva (svayambh<220> ç
or self-manifest) made of crystallized quartz, and generally found ç
in some sacred rivers like the Narmad<193>. A legend goes that <185>iva ç
got them manifested at the special request of B<193><207><193>sura, ç
a great devotee of his; hence the name `b<193><207>ali<209>ga'.
Though several stones shaped like a li<209>ga are found in the river ç
Narmad<193>, not all of them are b<193><207>ali<209>gas. Special charac-teristics ç
are prescribed for them by noting which one can discover a true b<193><207>ali<209>ga.
The b<193><207>ali<209>gas occur in many shapes and sizes as also ç
colours. They are hence given different names. The `<193>gneya-li<209>ga' ç
will be rose in colour and warm to touch. The `y<193>mya-li<209>ga' ç
is shaped like a cudgel whereas the `varu<207>a-li<209>ga' is round ç
in shape. The `raudra-li<209>ga' resembles a bone-piece. The `vai<218><207>ava-li<209>ga' ç
has varie-gated colours. They are sometimes given different names ç
of <185>iva†like Svayambh<220>, M<216>tyu<210>jaya or N<200>laka<207><219>ha†depending ç
upon their external characteristics.
@SPACE = 
@NT = bandha, bandhana
@N1 = (`bondage')
@SPACE = 
These words which mean `bondage,' have been used in the Indian philosophical ç
literature in a more technical sense, that of the bondage of the <193>tman ç
(or soul) due to various factors. Generally, all the six well-known ç
schools of philosophy accept thatbandha or bondage has been caused ç
by avidy<193>, aj<210><193>na or mithy<193>j<210><193>na (ignorance ç
or false knowledge of the Reality) and mok<218>aor liberation comes ç
through j<210><193>na or right knowledge and experience of the Reality.
For details see under each of the six systems of Indian philosophy.
In Ha<219>hayoga, the word bandha or mudr<193> is used to indicate ç
the various methods prescribed for controlling the pr<193><207>a or ç
the vital airs and arousing the ku<207><195>alin<200>·akti, the basic ç
psycho-spiritual energy situated at the root of the spinal column.
For details see <MS>MUDR°S.
@SPACE = 
@NT = bandhu
@N1 = (`one who binds [through love or blood relationship]')
The word `bandhu' used in early Vedic literature meant a `friend.' ç
Later, it was used to indicate any relative or blood- relation, in ç
general. Gradually, by the time of the medieval digests of dharma·<193>stras, ç
it acquired a more technical or legal sense, since a clear definition ç
of the word was all important in cases of rights to the property of ç
a deceased person. Hence it was defined as a person related to the ç
deceased through one or more female relatives (cognate) as opposed ç
to the gotrajas (agnates) or relativesthrough the male members of ç
the family. Elaborate details with regard to the line of succession ç
have been provided by the dharma·<193>stras.
@SPACE = 
@NT = Baramula
@SPACE = 
Situated near the place where the river Jhelum (Vedic river Vitast<193>) ç
leaves the Kashmir valley, the modern Baramula wascalled Var<193>ham<220>lak<218>etra ç
or Var<193>ha-k<218>etra in the ancient days. Originally, it was a ç
suburb of Huvi<218>kapura (modern Ushkur). Associated with the °divar<193>ha, ç
the boar incarnation of Vi<218><207>u, it was considered very sacred. ç
Consequently many temples and monasteries had been built in the 9th ç
and 10th centuries, during the reigns of Lalit<193>ditya Mukt<193>p<200><195>a, ç
(Queen) Sugandh<193>, and K<218>emagupta, when the cult of Vi<218><207>u ç
flourished there. These were later destroyed by Sikandar B<220><219>-<186>ik<193>n ç
during the period <F51320P10MSC1>A. D.<W1> 1390-1416. Only a few columns ç
and tablets of stone remain now as a remnant of the old glory.
@SPACE = 
@NT = barg<200>t
@N1 = (`excellent songs')
The Vai<218><207>ava movement in Assam owes its origin mainly to <185>a<209>karadeva ç
(<F51320P10MSC1>A.D.<W1> 1486-1568). He and his chief disciple M<193>dhavadeva ç
have left behind them a class of devotional poems and songs in Assamese, ç
well-known as `barg<200>t' (`vara-g<200>tam or excellent songs') which ç
still hold their sway upon the masses of Assam.
These lyrical songs are classical as far as musical techniques are ç
concerned. Their content however is highly philosophical, though stories ç
of R<193>ma and K<216><218><207>a also find a place.
The barg<200>ts of <185>a<209>karadeva are full of d<193>syabhakti ç
(devotion to God as of a servant towards his master) whereas those ç
of M<193>dhavadeva excel in V<193>tsalyabhakti (devotion to God considering ç
him as one's child).
Later writers like Gop<193>ladeva, Ani-ruddha, <185>r<200>r<193>ma ç
and others, who were mostly pontiffs of Vai<218><207>avite monasteries ç
(called `Sattras') imitated these barg<200>ts and attained some distinction ç
in this field.
@SPACE = 
@NT = B<193>rhaspatya-m<193>na
@N1 = (`measure of<R>ç
B<216>haspati')
@SPACE1 = 
The B<193>rhaspatya-m<193>na is a method of reckoning time in cycles ç
of 60 years (S<220>ryasiddh<193>nta 14.1-2) which is quite common ç
in South India even now. The sidereal period of B<216>haspati or planet ç
Jupiter is nearly 112 sidereal years. Hence Jupiter stays roughly ç
for one year in one zodiacal sign, if the calculation is based on ç
mean motion.
This led to the devising of a cycle of 12 Jovian years of about 361 ç
days each. Atsome period, a fivefold multiple, a cycle of 60 Jovian ç
or B<193>rhaspatya years, each with a special name suffixed by the ç
word sa<221>vatsara (= year) came into use. The earliest available ç
evidence points to the 6th century <F51320P10MSC1>A. D.<W1>, as found in ç
the inscription of the C<193>lukyan king Ma<209>gale·a.
The sixty years are:
1.<+>Prabhava; 2.<+>Vibhava; 3.<+><185>ukla; 4.<+>Pramod<220>ta; 5.<+>Prajotpatti ç
(Praj<193>pati); 6.<+>A<209>giras; <+><+>7.<185>r<200>mukha; <+><+>8. ç
Bh<193>va; 9.<+>Yuvan; 10. Dh<193>t<216> (Dh<193>tu); 11.<+>®·vara; ç
12. Bahudh<193>nya; 13. Pram<193>thin; 14. Vikrama; 15. V<216><218>an ç
(Vi<218>u); 16. Citrabh<193>nu; 17. Subh<193>nu (Svabh<193>nu); 18. ç
T<193>ra<207>a; 19.P<193>rthiva; 20.Vyaya; 21. Sarvajit; 22.Sarvadh<193>rin; ç
23. Virodhin; 24. Vik<216>ti; 25. Khara; 26.Nandana; 27.Vijaya; ç
28.Jaya; 29. Manmatha; 30. Durmukha; 31. Hevilambin (Hemalambin); ç
32.<+>Vilambin; 33.<+>Vik<193>rin; 34.<185><193>rvarin; 35. Plava; ç
36. <185>ubhak<216>t; 37.<185>obhak<216>t;<|> (<185>obhana); 38.Krodhin; ç
39.Vi·v<193>vasu; 40. Par<193>bhava; 41. Plava<209>ga; 42. K<200>laka; ç
43.Saumya; 44.S<193>dh<193>ra<207>a; 45.Virodhik<216>t; 46. Par<200>-dh<193>vin;   47.<+>Pram<193>din;    48.<+>°nanda; ç
49.<+>R<193>k<218>asa;<+> 50.<+>Anala; <+>51.<+>Pi<209>gala; 52<%30>.<%0>K<193>layukta; ç
53. Siddh<193>rtha; 54. Raudra; 55. Durmati; 56. Dundubhi; 57.Rudhirodg<193>ra; ç
58. Rakt<193>k<218>a (Rakt<193>k<218>in); 59.<+>Krodhana; 60 K<218>aya ç
(Ak<218>aya).
It was believed that the Sa<221>vatsara names indicated different ç
consequences for the years concerned.
@SPACE1 = 
Since the Jovian year is only 361 days long, shorter than a solar ç
year by 4 or 5 days, it became necessary to expunge one Jovian year ç
in every 85 or 86 solar years. This is called a `K<218>aya-sa<221>vatsara.'
