`Sadyovadh<220>s' were those who became vadh<220>s or brides straight-away, ç
(sadyas = at once) on the attainment of puberty, without undergoing ç
the training in the Vedic studies. In their case, the upanayana ceremony  was  performed  just  before ç
marriage, as a formality.
The practice of performing upanayana for women as also teaching them ç
the Vedas, seems to have disappeared even by the time of the Manusm<216>ti ç
(composed much earlier than <MS>A.<|>D.<D> 200).
The word brahmav<193>din<200> is sometimes applied to the famous Gayatr<200>mantra ç
also.
@NT = Brahma-vaivarta-pur<193><207>a
Modern Hinduism, though rooted in the Vedas and the Ved<193>nta, is ç
deeply influenced by the pur<193><207>as, at least on the practical ç
side. The Brahma-vaivarta-pur<193><207>a is one such that is often ç
quoted by the writers of the dharma·<193>stras while dealing with ç
topics like castes, gifts, vratas(religious vows during festival ç
days), descriptions of narakas or hells for transgression of dharma ç
and so on. The original part of the pur<193><207>a may be ancient. ç
However, the extant edition, as available in print, seems to have ç
evolved over the period <MS>A.<|>D.<D> 800-1600.
It is probable that this pur<193><207>a may have acquired this title ç
because it treats this created world as only a vivarta of or an appearance ç
in Brahman, the Absolute.
It is a fairly voluminous work comprising 18,000 verses spread over ç
four kha<207><195>as or books, the total number of chapters being ç
276.
The first book called Brahmakha<207><195>a lauds this pur<193><207>a ç
and also gives a gist of the contents of the entire work. It declares ç
that it is <185>r<200> K<216><218><207>a who is the creator of the ç
entire universe and that his world, the Goloka, is the highest of ç
all the divine abodes, even Vaiku<207><219>ha and Kail<193>sa being ç
inferior to it. A detailed account of creation which includes the ç
emanation of other deities like N<193>r<193>ya<207>a, <185>a<209>kara ç
or <185>iva, Brahm<193> and Dharma-puru<218>a, as also the goddesses ç
like M<220>rti, Lak<218>m<200>, Sarasvat<200>, Durg<193> and S<193>vitr<200> ç
is also given. Other topics dealt with in this book include °yurveda, ç
(science of health) worship of <185><193>lagr<193>ma (the stone symbol ç
of Vi<218><207>u), austerities to be practised by the sa<221>ny<193>sins ç
and widows, philosophical teachings concerning the ultimate identity ç
of the j<200>va (individual soul) with Brahman and a description of ç
the Goloka.
Prak<216>tikha<207><195>a, the second book, deals with the m<220>laprak<216>ti ç
or the Mother Nature, who is pictured as the consort of God, forming ç
the left part of his body as it were. She evolves into five goddesses: ç
R<193>dha and Durg<193>, Lak<218>m<200> and Sarasvat<200> as also ç
S<193>vitr<200>. God or Puru<218>a splits himself into <185>r<200> ç
K<216><218><207>a and N<193>r<193>ya<207>a. Later, Brahm<193> and ç
<185>iva also emanate from him.
M<220>laprak<216>ti gives birth to a golden egg from which emerges ç
Mah<193>vir<193><219>, the Cosmic Being. He creates the worlds.
As in the previous kha<207><195>a, here also a number of miscellaneous ç
subjects have been dealt with: stories of various female deities  including  the  river-goddesses, ç
worship and meditation concerning Bh<220>mi or Mother Earth, merits ç
of a bath in the Ga<209>g<193> River, importance of the tu<202>as<200> ç
leaves and rules concerning its use, details of the various ·<193>lagr<193>ma ç
stones, the well-known story of S<193>vitr<200> and Satyav<193>n, ç
karma and its effects, descriptions of narakas or hells, detailed ç
information about the growth of the human foetus in the womb, story ç
of Durg<193> in brief as also some details about her worship.
Next comes Ga<207>apatikha<207><195>a. This book deals mainly with ç
the birth and exploits of Ga<207>apati and <186>a<207>mukha, the two ç
sons of <185>iva and P<193>rvat<200>. The story of Para·ur<193>ma ç
(the R<193>ma of the battle-axe) is also an important part of this ç
section. There are quite a few beautiful hymns in praise of Ga<207>apati.
<185>r<200>-K<216><218><207>a-janma-kha<207><195>a, the last book, ç
is also the biggest. Though the story of K<216><218><207>a follows ç
the one given in the Bh<193>gavata, the amorous deeds of R<193>dh<193> ç
and K<216><218><207>a are portrayed prominently. Stories of Ambar<200><218>a ç
and Durv<193>sa, A<218><219><193>vakra and <185>r<200> R<193>ma also ç
find a place. A variety of topics like the evil omens indicated by ç
bad dreams, duties of the people belonging to the four var<207>as, ç
special code of conduct for the widows, foods fit and unfit for consuming, ç
description of Kaliyuga or the Iron Age, greatness of the country ç
of Bh<193>rata and the science of architecture are also included at ç
appropriate places. 
The last chapter of this book gives a list of eighteen major pur<193><207>as ç
along with the total number of verses in each of them.
A special feature of this pur<193><207>a is that it gives several ç
important mantras (esoteric formulae) as also their usage.
See also <MS>PUR°ØAS<D>.
@NT = brahmavidy<193> 
@N1 = (`knowledge of Brahman')
The words Brahman and °tman are extensively used in the Hindu scriptures.
The word `Brahman' has several senses: God the Absolute, the Vedas, ç
a br<193>hma<207>a, the Brahm<193>-priest in a Vedic sacrifice as ç
also tapas or austerity. However, it is in the first sense that it ç
is more widely used.
Vidy<193> means knowledge, wisdom, an art or a science. Hence brahmavidy<193> ç
refers to that art or science or discipline by practising which, one ç
is able to attain Brahman or God the Absolute.
This brahmavidy<193> is very ancient and has a hoary tradition. According ç
to the Upani<218>ads, Brahm<193>, the Creator, was himself the first ç
teacher. It has been handed down to us by a galaxy of successive teachers.
One who aspires for brahmavidy<193> should first cultivate the s<193>dhana-catu<218><219>aya  or  the  fourfold  spiritual ç
discipline, like viveka (discrimination) and vair<193>gya   (renunciation).   (See   also ç
<MS>S°DHANACATU<186><187>AYA<D> for details.) Tapas (austerity) and ç
devotion to the spiritual preceptor  are  other  aspects  of  this ç
discipline.
The teacher of brahmavidy<193> should be a ·rotriya (well-versed in ç
the scriptures) and a brahmani<218><219>ha (established in Brahman). ç
It is obligatory on his part to impart that knowledge to one qualified ç
for it, if he requests for the same.
The word `brahmavidy<193>' is sometimes applied to the knowledge of ç
the Vedas and their subsidiary sciences, since Vedas are also known ç
as Brahman.
See also <MS>BRAHMAN<D> and <MS>UPANI<186>ADS<D>.
@NT = Brahmavidy<193> Upani<218>ad
This is one of the minor Upani<218>ads belonging to the K<216><218><207>a ç
Yajurveda. It is a fairly large work of 110 ·lokas or verses inthe ç
anu<218><219>ubh meter. The Pra<207>ava or O<209>k<193>ra as also ç
the Ha<221>samantra (so'ha<221> ha<221>sa<199>) are the main topics ç
dealt with. However, the several details that are given, concerning ç
the various aspects of meditation on these two mantras, make the work ç
quite recondite.
The Upani<218>ad starts with an exposition of Pra<207>ava, its four ç
parts and contem- plations connected with them. Just as the sound ç
of a gong or a bell, made of bell- metal, gradually gets attenuated, ç
finally merging into the infinite sound or infinite silence, the mind ç
of a yogi who utters the Pra<207>ava (O<221>), lengthening it over ç
sixteen m<193>tr<193>s or instants of time, simultaneously concentrating ç
his mind on that sound, also gets dissolved in Brahman, the final ç
goal of pra<207>ava-japa.
Ha<221>savidy<193> is the next topic taken up. The words `ha<221>' ç
and `sa<199>' represent the j<200>v<193>tman (the individual self) ç
and Parm<193>tman or Brahman (the Supreme Self) respectively. The ç
natural breathing process of inhalation and exhalation should be mentally ç
connected with the two words `ha<221>' and `sa<199>'. Then the process ç
of breathing itself gets converted into japa (repetition of divine ç
name) ultimately resulting in the experience of the unity of the two. ç
This is Ha<221>savidy<193>.
@SPACE1 = 
After stressing that the <193>tman can be known only through the ·ruti ç
(the scripture or the Vedas) and the <193>c<193>rya (spiritual preceptor), ç
the Upani<218>ad goes on to describe three types of <193>c<193>ryas†the ç
codaka, the bodhaka and the mok<218>ada. Codaka is actually the Vedas ç
which impel a person to take to the spiritual path. The bodhaka is ç
the teacher who teaches the disciple, `Thou art That.' Mok<218>ada ç
(giver of liberation) is the Lord himself, since it is only he that ç
can give mok<218>a or liberation.
Here, the Upani<218>ad declares that it is in the heart alone that ç
one realises this `Ha<221>sa' or the Lord who is the indwelling spirit.
The work concludes with a long, highly poetical, soliloquy by the ç
knower of the Self, the gist of which is that he exists in all and ç
is all.
See also <MS>UPANI<186>ADS<D>.
@SPACE = 
@NT = br<193>hma-viv<193>ha
@N1 = (`marriage of the<R>ç
br<193>hma [type]')
@SPACE = 
Out of the <218>oda·a-sa<221>sk<193>ras or sixteen sacraments recommended ç
in the dharma·<193>stras for the dvijas (the `twice-born') viv<193>ha ç
or marriage is considered not only very important but also basic, ç
since all the other sacraments depend onit.
Out of the eight forms of marriage listed in the works, the br<193>hma ç
is the best. It is called `br<193>hma' since it is sanctioned by the ç
Vedas (Brahma = the Veda) or, is in accordance with dharma (Brahma ç
= dharma), the moral law sanctioned by the holy books and sacred traditions.
In this form of marriage, the father of the girl bedecks her with ç
the best of clothes and ornaments and gifts her to a worthy young ç
man, learned in the Vedas and of good character. Before doing so, ç
the bridegroom is invited and honored properly.
See also <MS>SA<189>SK°RAS, <186>O£A<185>ASA<189>-SK°RAS<D> and <MS>VIV°HA<D>.
@NT = brahmayaj<210>a
@N1 = (`sacrifice unto Brahman')
@EMERGENCY = Every g<216>hastha or householder was expected to perform ç
five yaj<210>as or sacrifices everyday. They were called `pa<210>camah<193>yaj<210>as'. ç
They had nothing to do with the ·rauta or the Vedic sacrifices wherein ç
oblations had to be poured into the duly consecrated Vedic fires, ç
but were of the nature of performing certain obligatory duties.
Brahmayaj<210>a is one of them. Here, Brahma means the Vedas and brahmayaj<210>a ç
means recitation of the Vedic texts as prescribed by the dharma·<193>stras.
@EMERGENCY = In the <185>atapatha Br<193>hma<207>a (11.5.6. 3-8) ç
there is an interesting comparison of the various limbs and functions ç
of the body involved in reciting the Vedas, with the implements used ç
in a sacrifice. For instance, the various spoons and ladles like juh<220>, ç
upabh<216>t and dhruv<193> are symboli- cally represented by the speech, ç
the mind and the eyes. The conclusion of the Vedic chanting in the ç
brahmayaj<210>a is avabh<216>tha-sn<193>na or the ceremonial bath ç
at the end of a sacrifice.
Brahmayaj<210>a may be performed either in a quiet place outside the ç
village or in one's own house. The usual practice is to do it during ç
the sandhy<193> or at noon. After sitting on the seat and performing ç
<193>camana (ceremonial sipping of water) certain prescribed Vedic ç
texts are to be chanted. Generally, it is one's own branch of the ç
Veda studied in the gurukula. Other works mentioned for sv<193>dhy<193>ya ç
(self-study) during brahmayaj<210>a are: the four Vedas, the Br<193>hma<207>as, ç
the Kalpas, the itih<193>sas and pur<193><207>as.
The contents of the brahmayaj<210>a varies from one ·<193>kh<193> ç
(branch of the Vedas) to another. However, the G<193>yatr<200>-mantra, ç
the Puru<218>as<220>kta and the ·<193>nti-mantra `O<221> namo brahma<207>e....' ç
seem to find a place in almost all these traditions.
Now-a-days, brahmayaj<210>a is rarely performed. However, during the ç
lunar month of <185>r<193>va<207>a (July-August) it is performed once ç
by most br<193>hma<207>as, especially in South India. A set formula ç
has been adopted which includes the G<193>yatr<200>-mantra, the <184>gveda ç
(1.1.1-9), the first sentences of Aitareya °ra<207>yaka, the K<216><218><207>a ç
and <185>ukla Yajurvedas, the S<193>maveda, the Atharvaveda ç
as also the first sentences of the six Ved<193><209>gas. This is followed ç
by the ·<193>ntimantra `O<221> namo brahma<207>e' and a tarpa<207>a ç
(water libation).
See also <MS>PA<178>CA-MAH°-YAJ<178>AS<D>.
@NT = Brahmay<193>mala
The  <193>gamas  and  the  tantras†a special class of religious literature ç
dealing with the different aspects of <185>aivism and <185><193>kt<193>ism†have ç
the unique distinction of integrating the non-Vedic local religious ç
cults into the general framework of Vedic Hinduism.
The Y<193>malas, belonging to the <185>aiv<193>-gama group, have, ç
in all probability, derived their name from the fact of their dealing ç
with both <185>iva and <185>akti (Yamala= twin, couple) in their ç
works. Out of the eight Y<193>malas known to exist, the  Brahmay<193>mala,  occupies  a  very ç
important place. According to one version it is said to consist of ç
22,100 ·lokas or verses.
®·vara propitiated Lord <185>r<200>ka<207><219>ha, got this knowledge ç
from him and then communicated the same to his spouse, P<193>rvat<200> ç
or Dev<200>.
The work describes the process of creation from Sad<193>·iva through ç
his Par<193>·akti (supreme energy).
It also traces the origin of the three srotas or currents of t<193>ntric ç
traditions. They are Dak<218>i<207>a, V<193>ma and Madhyama. The Dak<218>i<207>a-srota ç
is characterised by sattva and hence is called `·uddha'. The V<193>ma-srota ç
has predominance of rajas and hence is `mi·ra'. The last, the Madhyama-srota, ç
is dominated by tamas and so, is described as `a·e<218>a-mala-ra<210>jita' ç
(fully coloured by impurity).
Some of the gods and sages who promulgated this knowledge of <185>iva ç
are: ®·vara, Mah<193>dev<200>, Brahm<193>, Vi<218><207>u, U·anas, ç
B<216>haspati, Sanatkum<193>ra and Lakul<200>·a.
The earliest manuscript of the Brahmay<193>mala available now is ç
preserved in Nepal and has been assigned the date <MS>A.<|>D.<D> 1052. ç
According to it, the eight Y<193>malas were communicated by eight ç
Bhairavas such as Svacchanda, Krodha and others. These Y<193>malas ç
indicate great developments in the t<193>ntric s<193>dhan<193>s.
See also <MS>°GAMAS<D> and <MS>TANTRAS<D>.
@NT = Br<193>hm<200>
@N1KERN = (`that which is related to Brahm<193>')
Br<193>hm<200> is the ·akti or power of Brahm<193>, the creator, considered ç
as his consort. See <MS>BRAHM°Ø®<D> for details.
Br<193>hm<200> is also the name of a script, one of the earliest in ç
recorded history, and, considered as the mother of the devan<193>gar<200> ç
script as also the allied scripts, like those of Tibet, Burma, Sri ç
Lanka and Thailand.
The earliest records available in the Br<193>hm<200> script are the ç
edicts of A·oka. Most of them, except the ones found in the North-West ç
part of India, are in the Br<193>hm<200> script. The North-Western ç
edicts are in the Kharo<218><219>h<200> script.
The Br<193>hm<200> is normally read from left to right.
Regarding its origin there are two theories. Most Indian scholars ç
maintain that it was derived from the Harappan script. Many European ç
scholars believe that it was derived from a Semitic script like the ç
Greek, Aramaic or the Phoenician.
The Hindu tradition holds that it has come from Brahm<193>, the Creator, ç
himself; and hence the name Br<193>hm<200>. The similarities with ç
the script of Indus valley civilization seem to support the theory ç
of its Indian origin.
But, one thing is certain: By the time of emperor A·oka (272-232 <MS>B.C.<D>) ç
the script was not only in existence but had also been considerably ç
developed and refined.
Knowledge of the script had long been forgotten. It goes to the credit ç
of James Prinsep (<F51320P10MSC1>A.<|>D.<F255P255DC255> 1799-1840) and Kamal<193>k<193>nta ç
Vidy<193>la<209>k<193>ra for the complete decipherment of the script ç
in <MS>A.D.<D> 1838.<F51320P10W1C1>
See also <MS>KHARO<186><187>H®.<D>
@NT = br<193>hm<200>-sthiti
@N1 = (`the state of being<R>ç
established in Brahman')
Brahman is the Absolute from whichthis universe has evolved, in which ç
it lives and to which it returns at the end of a cycle of creation. ç
It is described as `sat-cit-<193>nanda,' existence-knowledge-bliss ç
absolute.
When a person, through appropriate s<193>dhan<193>s or spiritual practices, ç
realises this Brahman in the inmost depths of his being, his life ç
undergoes a dramatic change, reflecting this inner experience in every  action.  Such  a  person  called ç
`sthitapraj<210>a' or `a man of steady wisdom', always maintains an ç
equanimous attitude towards all situations of life.
This inner state of mystical experience resulting from realising Brahman ç
and expressing itself outwardly as equanimity has been called `br<193>hm<200>-sthiti' ç
by the Bhagavadg<200>t<193> (2.72). Once attained, this state will ç
continue till the last moment of one's life.
@NT = brahmodya
@N1 = (`that which stimulates<R>ç
[a knowledge of] Brahman')
During the ancient days performance of the Vedic sacrifices was widely ç
prevalent. Though the sacrifices took a lot of time to do them meticulously, ç
intervals and free time would also be there. These had to be utilised ç
in a way useful to the people involved, especially the priests. One ç
such programme that served this purpose well was the `brahmodya,' ç
a theological dialogue, where questions and riddles were propounded ç
and answered. This helped the priests and others to enrich their knowledge ç
in the company of persons endowed with better knowledge and greater ç
experience. A sample of the same, which occurs in the A·vamedha sacrifice ç
may be given here: p<216>cch<193>mi paramanta<199> p<216>thivy<193><199>, ç
.....iya<221> vedi<199> paro anta<199>, `Iask you the furthest limit ç
of the earth.....' `This vedi is the furthest limit.' (<184>gveda ç
1.164.34,35)
@NT = Br<193>hmoism
It is the philosophy of the Brahma Sam<193>j, one of the modern reform ç
movements of Hinduism, started by R<193>j<193> R<193>mmohan Roy (<MS>A.D.<D> ç
1772-1833). 
See <MS>BRAHMA SAM°J <D>for details.<MS>
@NT = Brahmopani<218>ad
@EMERGENCY = The Brahmopani<218>ad is a minor Upani<218>ad and is ç
assigned to the K<216><218><207>a Yajurveda. There seems to be two ç
recensions†the South Indian and the North Indian. The latter is the ç
longer version.
<185>aunaka approaches the sage Pippa-l<193>da of the A<209>giras-gotra ç
and puts him a question regarding the location and functioning of ç
the deities of the indriyas or sense-organs in the divine Brahmapura ç
(the human body). In reply, Pippal<193>da imparts the excellent Brahmavidy<193> ç
or spiritual  wisdom  concerning  <193>tman/ Brahman.
@EMERGENCY = It is pr<193><207>a or <193>tman that exercises its power ç
over all the devas or the indriyas (sense-organs). Situated in this ç
Brahma-pura (the human body) it is the pure, resplendent,  partless  Brahman  that ç
controls these sense-organs.
When the j<200>va (pr<193><207>a or <193>tman) goes out of the body ç
during su<218>upti or deep sleep, all the sense-organs also follow ç
him even as the bees follow the queen bee. He moves about in sleep ç
like an eagle flying freely in the sky. In this state of su<218>upti ç
the j<200>va is not tainted or affected by good and bad. He comes ç
back to the waking state through the dream state.
@EMERGENCY = This puru<218>a (the j<200>va or the <193>tman bound ç
in this body) has four seats where his presence is felt: n<193>bhi ç
(navel), h<216>daya (heart), ka<207><219>ha (throat) and m<220>rdh<193> ç
(head). Associated with the four states of consciousness, viz., j<193>grat ç
(waking state), svapna (dream state), su<218>upti (deep sleep state) ç
and tur<200>ya (the fourth or the super-conscious state), he is known ç
respectively as Brahm<193>, Vi<218><207>u, Rudra and Ak<218>ara. But ç
in himself he is pure Light, beyond the limitations of all the sense- ç
organs.
At the cosmic level, since he is everything and all things are merged ç
in him without distinction, the worlds, the gods, the sacrificial ç
systems, all human relationships  and  varieties  of  human beings ç
do not exist separately as distinguished from him.
The  Upani<218>ad  then  goes  on  to describe the real meaning of ç
·ikh<193> (tuft of hair) and yaj<210>opav<200>ta (sacred thread) as ç
related to Brahman (the Absolute). The externals should be discarded ç
and j<210><193>na or knowledge (of the <193>tman) should take their ç
place.
This is then followed by some verses which appear in other Upani<218>ads ç
like the <185>vet<193>·vatara  also.  They  describe  the Supreme ç
Lord as the all-pervading reality and also as residing in the hearts ç
of all beings in a subtle form. He is the supreme witness, energiser, ç
master-controller and supervisor. Those who realize him in their own ç
hearts attain eternal happiness, and not the others.
Just as the fire which is inherent in the ara<207>is (attritional ç
pieces of wood used in Vedic sacrifices to produce fire) is brought ç
out by their attrition, or oil from the oil-seeds or butter from curds ç
or water from the earth by proper means, the <193>tman inside us can ç
be brought out, i.e., experienced, through meditation. Once this is ç
done, the j<200>va or the individual soul is liberated from all types ç
of bondage.
See also <MS>UPANI<186>ADS<D>.
@NT = brahmotsava
@N1 = (`the big festival')
Hindu temples and worship of the images permanently fixed in their ç
garbhag<216>ha (sanctum sanctorum) are quite ancient. Out of the several ç
public festivals observed by these temples, the `brahmot- sava' is ç
the biggest. (`Brahma' means `big'.) However, the orthodox belief ç
is that the fourfaced Brahm<193> (the creator-god) himself conducts ç
this festival in honour of the chief deity of the temple. Hence the ç
name `brahmotsava'. Generally it is the grandest and the most spectacular ç
of all the temple- festivals. The celebrity of a temple is often measured ç
by the extent of the grandeur of its brahmotsava.
°g<193>mic works speak of five varieties of brahmotsavas. They are:
(1)<+><|>br<193>hma<|>: It is celebrated just for a day and is supposed ç
to increase the spiritual power of the temple.
(2)<+><|>·aiva<|>: It is conducted for three days and is aimed at removing ç
all the obstacles of the people.
(3)<+><|>aindra<|>: Spread over five days, this is believed to prevent ç
famine and drought.
(4)<+><|><193>r<218>a<|>: Conducted for seven days, this is meant to ç
secure prosperity for the kingdom.
(5)<+><|>daivika or vai<218><207>ava<|>: This is a nine-day affair purported ç
to bring about all-round protection and happiness.
This last one is considered as s<193>ttvika (pure) as against the ç
others which are either r<193>jasika (middling) or t<193>masika (inferior).
@SPACE1 = 
Some of the more important aspects of a brahmotsava are: bher<200>t<193><195>ana ç
(beating the drum), dhvaj<193>roha<207>a (hoisting the temple flag), ç
<193>v<193>hana (inviting the deityto they<193>ga·<193>l<193> or ç
place of sacrificial rites), establishing of kala·as (holy pots filled ç
with water) and performance of homas.
The rathotsava (festival of taking the utsavam<220>rti or the procession-image ç
in the ratha or temple car) is conducted two days before the close ç
of the festival.
In some temples where there is the facility of a tank or a river nearby, ç
teppotsava  or  boat-festival  too  is celebrated.
@NT = branding
See <MS>TAPTA-MUDR°-DH°RAØA<D>.
@NT = B<216>had<193>ra<207>yaka Upani<218>ad
@SB = Introduction
Out of the three basic scriptures of Hinduism known as the prasth<193>natraya, ç
the Upani<218>ads rank first. In the group of the ten Upani<218>ads ç
the B<216>had<193>ra<207>yaka and the Ch<193>ndogya occupy a unique ç
place since they not only delineate the fundamental principles of ç
Ved<193>nta but also describe a number  of  up<193>san<193>s  or  meditations, ç
technically called Vidy<193>s.
The B<216>had<193>ra<207>yaka Upani<218>ad, as its very name suggests, ç
is quite a large work (b<216>had = large, big) and forms an integral ç
part of the well-known <185>atapatha Br<193>h-ma<207>a which itself ç
belongs to the <185>ukla Yajurveda. The <185>atapatha Br<193>hma<207>a ç
has two recensions†the K<193><207>va and the M<193>dhyandina. ç
The former has 17 k<193><207><195>as or sections whereas the latter ç
has only14. The six adhy<193>yas or chapters of the B<216>had<193>ra<207>yaka ç
actually form chapters 3to 8 of the 17th k<193><207><195>a in the ç
K<193><207>va recension and chapters 4 to 9 of the 14th k<193><207><195>a ç
of the M<193>dhyandina recension.
The adhy<193>yas are divided into kha<207><195>as or br<193>hma<207>as, ç
which again are subdivided  into  ka<207><195>ik<193>s  (similar  to ç
mantras). There are 435 ka<207><195>ik<193>s distri-buted among the ç
47 br<193>hma<207>as of the 6adhy<193>yas of this Upani<218>ad.
There is another way of dividing this Upani<218>ad. The first two ç
adhy<193>yas form the Madhuk<193><207><195>a, the middle two, the ç
Munik<193><207><195>a or the Y<193>j<210>avalkyak<193><207><195>a ç
and the last two, Khilak<193><207><195>a. These k<193><207><195>as ç
respectively deal with upade·a (the teaching), upapatti (the argument) ç
and up<193>san<193> (the meditations and rites).
By  far,  the  Munik<193><207><195>a,  which accounts for almost ç
half the number of the ka<207><195>ik<193>s, is the most important ç
part of this Upani<218>ad. The sage Y<193>j<210>avalkya, who is the ç
principal person that appears here, has expounded brilliantly the ç
philo-sophy of °tman/Brahman as also several subtle aspects of related ç
teachings. He can easily be classified among the greatest thinkers ç
of the world of any age.
A chapterwise summary of the work may now be attempted.
@SB = First Chapter
The first br<193>hma<207>a known as the A·va-br<193>hma<207>a,  describes  a  special ç
process of meditation wherein the various aspects of Praj<193>pati, ç
the Creator, like k<193>la (time), loka (the various worlds) and devat<193> ç
(the various deities) are advised to be superimposed on the different ç
limbs of the horse chosen for the A·vamedha (horse-sacrifice). This ç
can transform†in a spiritual sense†the horse into Praj<193>pati himself. ç
The ritual of the A·vamedha itself can lead the performer to Brahmaloka ç
or the world of Brahm<193>, also known as Hira<207>yagarbha. Though ç
only kings are competent to perform this sacrifice, even others can ç
attain to the same result by imagining themselves to be the horse ç
and superposing the various items on themselves as described.
Agni-br<193>hma<207>a is the second section of this chapter. It ç
deals with the manifestation of agni or fire from Praj<193>pati and ç
the method of contemplation on it as Praj<193>pati himself. This leads ç
to the fruit of m<216>tyujaya or conquest of death.
The third is the Udg<200>tha-br<193>hma<207>a. The udg<200>tha is ç
the second and the most important part of a s<193>man sung by the ç
priest ugd<193>t<216> in a Soma sacrifice. In this br<193>hma<207>a, ç
the importance of pr<193><207>a, the vital force, has been brought ç
out by an allegorical story. The devas or gods wanted to conquer the ç
asuras or demons by performing the Jyoti<218><219>oma sacrifice. They ç
employed sense-organs like the speech, the eye, the nose, and also ç
the mind to sing the udg<200>tha for them. The asuras, however, succeeded ç
in contaminating them through selfishness, thereby defeating  the  purpose ç
of the devas. However, when  these  asuras rushed towards the pr<193><207>a, ç
the chief vital force, they were destroyed. By meditating on one's ç
pr<193><207>a, which is not only the real power behind the sense-organs ç
but also the essence of the Vedas and a replica of the cosmic Pr<193><207>a ç
(also known as Praj<193>pati or Hira<207>yagarbha) one can attain ç
to the world of Praj<193>pati. The speciality of this up<193>san<193> ç
or meditation is that it does not involve any rites or rituals.
@SPACE1 = 
The fourth kha<207><195>a is known as the Puru<218>avidha-br<193>hma<207>a. ç
Before creation, the entire universe was within the bodyof Puru<218>a ç
or Praj<193>pati or Vir<193>j, undifferenti-ated from him. He desired ç
for a mate. As a result of his will, he projected out of himself another ç
entity which split into two, the male part being Manu and the female ç
<185>atar<220>p<193>. By their union, not only in the human form, ç
but also in various other forms, all the living beings, up toan ant, ç
were created. He, however, remained as he was, unaffected. He then ç
realized that the created universe of beings was also himself. Later, ç
he created the gods like Agni.
Since the Puru<218>a, the Supreme Self, has entered into the whole ç
creation and exists in it like a sword in its sheath or fire in the ç
wood, it is he who is being manifested through all the activities ç
of the body-mind complex. However, the activities like speaking and ç
the names like speech, are only nomenclatures born out of the various ç
types of functioning. He is the inmost self in us and is unaffected ç
by the sense of doership or actions or their fruits, which have been ç
superimposed on him by avidy<193> or ignorance of his real nature. ç
The sage V<193>madeva and many others like him, realized that they ç
were in the ultimate analysis, the Supreme Self.
@SPACE1 = 
Then comes a classification of the gods. Agni is br<193>hma<207>a. ç
Indra, Varu<207>a, Soma, Yama and ®·<193>na are k<218>attriyas. Vasus, ç
Rudras and °dityas are vai·yas. P<220><218>an is a ·<220>dra. The ç
human beings were born out of these four classes of gods. The Puru<218>a ç
or the Supreme Being also created dharma or righteousness (the Cosmic ç
Law) to regulate them all. However, it is declared that an aj<210><193>ni ç
or an ignorant person becomes an object of enjoyment for all. These ç
ignorant ones are advised to discharge their debts to the gods and ç
the others through the pa<210>cayaj<210>as or the five daily sacrifices. ç
The Upani<218>ad also says that it is desire that binds a person and ç
it is meditation on the °tman or the Self alone that can deliver him. ç
One who fails in this has to suffer much.
The next kha<207><195>a is known as the Sapt<193>nna-br<193>hma<207>a, ç
the br<193>hma<207>a of seven foods. The first anna or food is the ç
usual physical food upon which all living beings sustain themselves. ç
Human beings have to consume food so that they can perform the prescribed ç
religious rites which can give them the unseen results later on. If ç
they do not perform these rites, they will be eating only sin. The ç
second and the third annas are the huta and the prahuta sacrificial ç
oblations and gifts given during the sacrifices. They are sometimes, ç
identified with the two sacrifices Dar·a and P<220>r<207>am<193>sa, ç
meant for the gods. Milk is the fourth anna, specially meant for the ç
animals.
The last three annas or foods, were kept by Praj<193>pati for himself. ç
They are: v<193>k (speech), manas (mind) and pr<193><207>a (vital ç
force). Since they help him to create the worlds and sustain them, ç
they are called `anna'. These three are then identi-fied with the ç
three worlds, the three Vedas, the three beings (gods, manes and human ç
beings) and so on. In fact they comprise the whole world. One who ç
meditates upon them as limited, attains the finite world. If he meditates ç
upon them as unlimited, he obtains the infinite world.
@SPACE1 = 
This Praj<193>pati or the Hira<207>yagarbha is himself the time. The ç
Upani<218>ad des-cribes how the various organs like v<193>k or speech, ç
competed against one another but were overcome by fatigue. However, ç
pr<193><207>a or the vital force was not affected by it. Hence, the ç
organs identified themselves with it and became immortal. Among the ç
gods likeAgni (fire), °ditya (Sun) and Candra (Moon), only V<193>yu ç
(air), the cosmic counterpart of pr<193><207>a, could sustain itself ç
in its work. If a person can meditate on the organs like speech which ç
exist in all living beings and the elements like fire, which exist ç
in this world, as identified with his own Self, he attains identity ç
with Hira<207>yagarbha and live in his world.
The sixth and the last kha<207><195>a, which is sometimes called the ç
Uktha-br<193>hma<207>a, declares that the whole universe is nothing ç
but n<193>ma (name), r<220>pa (form) and karma (action). Like the ç
three mutually supporting sticks, these three support one another ç
and also help in manifesting one another. Since this universe is only ç
an up<193>dhi orlimiting adjunct to Param<193>tman (the Supreme Self), ç
anyone who is interested in it, will not be inclined to meditate on ç
him.
@SB = Second Chapter
This chapter, comprising six br<193>hma-<207>as, is more directly ç
concerned with <193>tma- tattva or the knowledge of the °tman. The ç
well-known discourse by the great sage Y<193>j<210>avalkya to his ç
wife Maitrey<200>† which, incidentally, appears in the fourth chapter ç
also, though shorter†forms the core of this chapter.
The first br<193>hma<207>a known as the Aj<193>ta·atru-br<193>hma<207>a ç
starts with the legend of B<193>l<193>ki the proud one, a descendant ç
of Garga and Aj<193>ta·atru, the king of K<193>·<200>. B<193>l<193>ki ç
proposed to Aj<193>ta·atru to teach Brahman. However, what he taught ç
was elementary and concerned only with the conditioned Brahman, like ç
the Being resid-ing in the sun, the moon, the lightning, the ether, ç
the air and so on. But Aj<193>ta·atru knew better. He had realized ç
the uncondi-tioned Brahman. So, he taught this to B<193>l<193>ki. ç
In deep sleep, all the sense organs like speech, are absorbed in their ç
sources, the individual Self is merged in the Supreme Self, the unconditioned ç
Brahman. It then resembles a child or a great king or a worthy br<193>hma<207>a, ç
having reached the acme of bliss. The teaching ends with a statement ç
that all the beings, all the worlds and all the gods emerge out of ç
the °tman, the Supreme Being, even as sparks spring from fire.
The next the <185>i·u-br<193>hma<207>a and it speaks of the pr<193><207>a ç
or the vital force as a calf. Its body is its abode, the head is its ç
special place, the vigour generated by food and drink is its post ç
and the food itself is its tether. Seven deities like Rudra and °ditya ç
are praising this pr<193><207>a. One who knows thus, will never be ç
without food.
The third is the M<220>rt<193>m<220>rta-br<193>h-ma<207>a and it ç
is devoted to the description of the two forms of Brahman. One form ç
is gross, mortal, limited and perceptible. The other is subtle, immortal, ç
unlimited and imperceptible. By superimposing these two forms, the ç
Supreme Brahman is made conceivable. The words `neti, neti' (`not ç
this, not this') deny all limitations to Brahman and reveal its essential ç
nature.
@SPACE1 = 
Next comes the Maitrey<200>-br<193>hma<207>a which starts with the ç
story of Y<193>j<210>avalkya and his two wives, Maitrey<200> and K<193>ty<193>-yan<200>. ç
It stresses the need for sa<221>ny<193>sa or monastic life, to attain ç
the Self. The sage Y<193>j<210>avalkya, intending to embrace the monastic ç
life, wants to divide his wealth between the two wives. However, Maitrey<200>, ç
after learning that the wealth, and the Vedic rites performed with ç
the help of wealth, cannot give her immortality, rejects the offer ç
of wealth and opts for <193>tmaj<210><193>na or the knowledge of the ç
Self. Y<193>j<210>avalkya responds by teaching her that all the beings ç
here like the husband or the wife or the children, as also wealth ç
or the various worlds or the gods are dear to us only because of the ç
°tman or the Self in them and not by themselves. This °tman has to ç
be heard of (from a qualified teacher), reflected uponand meditated ç
upon†these three being called ·rava<207>a, manana and nidi-dhy<193>sana†in ç
order to be realized. As it is not possible to grasp the special sources ç
of a drum or a conch or a lute without the grasping of sound in general, ç
it is not possible to perceive anything in this world as different ç
from Brahman, its basic reality. Y<193>j<210>avalkya further asserts ç
that even the Vedas have emerged out of it and that it exists in everything ç
as homogeneous consciousness, even as salt exists everywhere in the ç
water in which it has been dissolved. Perception of duality in this ç
world is only apparent and has been caused by avidy<193> or ignorance ç
of the Reality.
@SPACE1 = 
Madhu-br<193>hma<207>a, the fifth section, sums up the import of ç
the first two chapters. There is an elaborate account of the °tman ç
or the Self which is the ruler and the king of all beings. Even as ç
spokes are fixed in the nave and the rim of a chariot wheel, so are ç
all beings, all gods and all worlds are fixed in the Supreme Self.  The  Sage  Dadhya<209>  °tharva<207>a ç
taught this knowledge of the Self to the two A·vins†the twin gods†through ç
a temporary equine head. The br<193>hma<207>a ends with the essential ç
teaching of all the Ved<193>nta texts, viz., that the Self, though ç
one, is perceived as manifold through m<193>y<193> his inscrutable ç
power.
Va<221>·a-br<193>hma<207>a, the last section of this chapter, gives ç
the line of teachers beginning with Hira<207>yagarbha.
@SB = Third Chapter
Whereas the Madhuk<193><207><195>a, comprising the first two chapters ç
dealt with upade·a or <193>gama (the teachings), the Munik<193><207><195>a ç
(also called Y<193>j<210>avalk<200>ya-k<193><207><195>a) consisting ç
of the third and the fourth chapters, strengthens it through upapatti ç
or yukti, or reasoning. There are nine br<193>hma<207>as in the third ç
chapter.
The first is the A·vala-br<193>hma<207>a. It starts with an interesting ç
story. Janaka Vaideha, the great king, had just completed a big sacrifice†the ç
Bahudak<218>i<207>a† to participate in which, a large number of br<193>hma<207>as ç
from the countries of Kuru and Pa<210>c<193>la had come. The King ç
proposed to give away as a gift, a thousand cows on the horns of each ç
of which had been tied ten gold coins, to the Brahmi<218><219>ha (the ç
most learned in Brahman or the Vedas) among them. Though none of the ç
assembled dared to accept the challenge, Y<193>j<210>avalkya did. ç
He even ordered his disciple S<193>ma·rava to drive the cattle home! ç
Naturally the assembly fell into a rage and all started questioning ç
him. A·vala who was the first to pose eight questions to him, was ç
easily vanquished by the satisfactory replies of Y<193>j<210>avalkya.
The °rtabh<193>ga-br<193>hma<207>a, the next section, starts with ç
another Vedic scholar, °rtabh<193>ga, shooting six questions at Y<193>j<210>avalkya ç
who answers them all to the satisfaction of the questioner. The last ç
of these questions deals with the problem of the destination of the ç
soul of a dead person. Y<193>j<210>avalkya takes °rtabh<193>ga to ç
a secluded place and the two finally conclude that it is karma that ç
decides the future life of the soul of a dead person. Good karma leads ç
to noble births and bad karma to ignoble ones.
Bhujyu-br<193>hma<207>a, the third, states that even the best of ç
karmas or rites results in transmigration and that even karmas accompanied ç
by up<193>san<193> or meditation cannot give mok<218>a or freedom.
The fourth is the U<218>asta-br<193>hma<207>a. U<218>asta questions ç
Y<193>j<210>avalkya to tell him about Brahman which is s<193>k<218><193>t ç
(immediate) and aparok<218><193>t (direct). Y<193>j<210>avalkya replies ç
that it is the °tman that works in the bodythrough the five pr<193><207>as ç
or vital-airs. It is the seer and the knower and hence it cannot be ç
seen or known like an external object.
The Kahola-br<193>hma<207>a follows next. A further description ç
of the °tman is given here, as beyond hunger, thirst, sorrow, delusion, ç
old-age and death. The wise ones realize this °tman and give up their ç
desire for progeny, wealth and meritorious worlds. A realized soul ç
is a realized soul irrespective of his conduct. His brahma-j<210><193>na ç
or knowledge of Brahman never ceases.
@SPACE1 = 
The sixth section, named G<193>rg<200>-br<193>hma<207>a, deals with ç
the questions posed by G<193>rg<200>, the daughter of Vacaknu, and ç
the ready answers given by Y<193>j<210>avalkya. The questions concerned ç
with the relative subtlety of the pa<210>cabh<220>tas or the five ç
elements as also the worlds right up to the Brahmaloka, the abode ç
of Brahman. When she asks, `By what is the Brahma-loka pervaded?' ç
Y<193>j<210>avalkya warns her not to proceed further since the nature ç
of Brahman can be known only through the scriptures and the preceptor ç
and never through logic or inference.
The  Antary<193>mi-br<193>hma<207>a  is  the seventh in the series. ç
It is now the turn of Udd<193>laka °ru<207>i to question Y<193>j<210>a- ç
valkya. It concerns the `antaratama-s<220>tra' or the inmost thread ç
that passes through all the worlds and all the beings, holding them ç
together. Udd<193>laka also asks about the Antary<193>min, the Being ç
that dwells in all and controls them all. Y<193>j<210>avalkya replies ç
that V<193>yu is that s<220>tra or thread. It is the °tman that indwells ç
all the worlds and all the beings. He resides in them and controls ç
them whereas they know him not. He is the s<193>k<218>in or the eternal ç
witness, the ·rot<216> or the listener, the mant<216> or the thinker ç
and the j<210><193>t<216> or the knower. However, he is not the object ç
of cognition for any of the senses. He is the immortal °tman. All ç
else is perishable.
@SPACE1 = 
This is followed by the Ak<218>ara-br<193>hma<207>a, the eighth ç
section, wherein G<193>rg<200> puts two questions to Y<193>j<210>avalkya. ç
The first question is: `What pervades that (the s<220>tra) which is ç
above heaven and below the earth as well as between them, and which ç
was, is and will be?' Y<193>j<210>a- valkya replies that it is <193>k<193>·a, ç
the unmanifested ether. In reply to her next question as to what pervades ç
this <193>k<193>·a also, he answers that it is Ak<218>ara, the indestructible. ç
He describes it through several words revealing its unique qualities: ç
It is asth<220>la (not gross), ana<207>u (not fine), ahrasva (not ç
short), ad<200>rgha (not long), atama<199> (not darkness), an<193>k<193>·am ç
(not ether), acak<218>u<218>kam (without eyes), apr<193><207>am (without ç
the vital force), amana<199> (without mind) and so on.
It can be described only by such negative attributes since it can ç
never be apprehended either by the senses or by the mind.
Y<193>j<210>avalkya further avers that, verily under the command of ç
this Ak<218>ara (the Absolute) only the sun, the moon and all the ç
heavenly bodies are held in their positions and perform their allotted ç
duties. Rivers  and  mountains,  quarters  and directions and even ç
time itself, keep to their duties. It is by the rule of this very ç
Absolute that the lives of the human beings and the gods in heaven ç
are being regulated.
He concludes by saying that the performance of any rite or ritual ç
without knowing this Ak<218>ara is a waste and that the condition ç
of one who leaves this world without realizing this Ak<218>ara will ç
be miserable. But the one who leaves this world after knowing this ç
Ak<218>ara will be a knower of Brahman.
@SPACE1 = 
<185><193>kalya-br<193>hma<207>a is the last section of this chapter ç
. It conveys the immediacy and directness of Brahman by a reference ç
to the different enumerations of the gods who are ruled by it. In ç
reply to <185><193>kalya's question about the number of gods Y<193>j<210>avalkya ç
says that though there are tens or hundreds or thousands of gods they ç
are the manifestations of but one God, Hira<207>yagarbha, who is the ç
cosmic aspect of pr<193><207>a or the vital force. This God is one ç
and at the same time, the many. Hence, when the up<193>saka (the worshipper) ç
gets identified with Hira<207>yagarbha, he becomes all, the Self of ç
all.
Finally Y<193>j<210>avalkya asks the assembled br<193>hma<207>as whether ç
they know the root from which a dead person is reborn, even as a tree ç
that is cut off, springs up again from the original root. They were ç
ignorant of it. The Upani<218>ad itself declares that this root is ç
Brahman, the consciousness and the bliss, the ultimate resort of all ç
the human beings, be they the performers of rituals or the knower ç
of Brahman.
@SPACE = 
@SB = Fourth Chapter
@SPACE = 
This chapter comprises six br<193>hma<207>as. In the first, known ç
as the <186>a<195><193>c<193>rya-br<193>hma<207>a, Y<193>j<210>avalkya ç
poses some questions to the king Janaka Vaideha. The king in his reply ç
states the characteristics of Brahman as he had learnt from six of ç
his teachers. He posits Agni, V<193>yu, °ditya, Digdevat<193>, Candra ç
and Praj<193>pati, the presiding deities of speech, vital air, eyes, ç
ears, mind and intellect, as Brahman. Y<193>j<210>avalkya rules them ç
out as only partial manifestations of Brahman.
In the K<220>rca-br<193>hma<207>a, the second, Y<193>j<210>avalkya ç
describes the avasth<193>traya or the three states of consciousness ç
which the embodied <193>tman experiences. J<193>grat (waking state), ç
svapna (dream state) and su<218>upti (deep-sleep state) are the three ç
states and the soul while associated with these three states is designated ç
as Vi·va (or Vai·v<193>nara), Taijasa and Pr<193>j<210>a. Though the ç
terms used in this section are different, the interpretation given ç
by the commentators leads us to this conclusion.
The third section is the Jyotir-br<193>hma<207>a, a fairly voluminous ç
one, comprising 38 ka<207><195>ikas. The avasth<193>traya or the three ç
states of consciousness, mentioned in the previous br<193>hma<207>a, ç
is discussed in detail through yukti or logic and reasoning. For an ç
ordinary human being endowed with the body and the senses, what is ç
it that acts as a jyoti or light?†This is the question that Janaka ç
repeatedly asks Y<193>j<210>avalkya. Y<193>j<210>avalkya lists them ç
one by one as: the sun, the moon, fire, speech and <193>tman or the ç
Self. When questioned about this <193>tman, associ- ated with the ç
body and the senses, Y<193>j<210>avalkya says that as a large fish ç
swims alternately to both banks of a river, so this <193>tman, simulating ç
the intellect, moves between the dream world and the waking world. ç
Since the intellect is transparent and next to the <193>tman, it easily ç
reflects the consciousness of the latter. Like a crystal glowing in ç
the light of a lamp, the intellect also, though bereft of consciousness, ç
appears to shine by the light or consciousness of the <193>tman, which ç
alone is self-luminous. in fact the luminaries like the sun and the ç
moon are able to shine only by the light of the <193>tman.
@SPACE1 = 
Then follows the conception of dream according to the Ved<193>nta. ç
In the dream state, the Self puts aside the gross body of the waking ç
state and creates a dream-body comprising the impressions of the waking ç
state. Dreams are not new experi-ences of the waking state. Sometimes ç
they may reflect the experiences of past lives also. The objects of ç
the dream state are then and there created by the mind. Though the ç
Self is dreaming, he has no direct connection with the physical body. ç
Hence it is not advisable to suddenly wake up a sleeping person as ç
that may endanger his life or senses. In dream, the Self merely witnesses ç
the results of good and bad actions but does not actually experience ç
them or do anything.
@SPACE1 = 
The <193>tman or the Self then enters the sampras<193>da or the su<218>upti ç
state, the state of deep-sleep. He enjoys supreme peace and bliss ç
in this state, since he has merged himself in the Supreme Self. This ç
is the nearest approximation to the state of Brahman. However, avidy<193> ç
or ignorance does persist even in that state, though in an unmanifested ç
form.
Then follows a description of the sufferings of an aged or diseased ç
body in order to rouse the spirit of renunciation in us. When the ç
Self leaves the present body it takes up another, made ready by its ç
own past work. This passing of the Self is analogous to the return ç
of man from the dream to the waking state.
The <185><193>r<200>raka-br<193>hma<207>a, the fourth section, gives ç
a detailed description of the transmigration of the j<200>va or the ç
Self. At the time of death it withdraws its sense- organs and comes ç
to the heart. It then exits through one of the parts of the body. ç
The potential results of up<193>san<193> (meditation), karma (good ç
and bad deeds) and v<193>san<193>s (past impressions) follow the j<200>va ç
in its onward journey. It creates for itselfa new body, even as the ç
goldsmith prepares ornaments out of gold. Once the results of past ç
deeds are exhausted, it returns to this world for new work. It should ç
be noted that only a person with desires and cravings transmigrates ç
and not the one who has no cravings. The latter is merged in Brahman, ç
after casting off his body even as a snake casts off its slough. Theknowers ç
of Brahman alone become immortal. The others are miserable.
There is no duality or multiplicity inBrahman. One who sees it otherwise ç
transmigrates from death to death. The seeker of Brahman should not ç
reflect on many words which only cause exhaustion to the vocal cords. ç
He should abjure all vain talk.
Other teachings given in this section are: The <193>tman in reality, ç
is unaffected by good or bad deeds. Knowledge of this <193>tman alone ç
can make a being a `muni' or a sage. Seekers of liberation desire ç
only the <193>tman and not the worlds of men, of the manes or of the ç
gods. Hence they renounce their hearth and home and become monks. ç
The <193>tman cannot be defined in positive terms. At best it can ç
be described negatively as `neti' (`not this'). The knower of the ç
<193>tman is never beset with the thoughts of rewards or punishments ç
for his past actions. He is ever controlled, serene and free from ç
desires. He sees the <193>tman in himself and all else also as his ç
own Self. He is free from all doubts and evils, ever blessed and absolutely ç
fearless.
The fifth br<193>hma<207>a†the Maitreyi- br<193>hma<207>a†is, for ç
all practical purposes, a repetition of 2.4. The last section†the ç
Va<221>·a-br<193>hma<207>a†traces the genealogy of the <193>c<193>ryas ç
or the teachers. As in the Madhuk<193><207><195>a, here also, Hira<207>yagarbha ç
is the primeval teacher.
@SB = Fifth Chapter
With this, begins the Khilak<193><207><195>a, the `supplementary ç
book'. The fifth chapter introduces some auxiliary meditations which ç
do not conflict with the rites but lead to worldly well-being and ç
also kramamukti or gradual liberation.
The first br<193>hma<207>a starts with the well-known ·<193>ntimantra ç
(peace-chant) `p<220>r<207>amada<199>.' The infinite universe has ç
come out of the infinite Brahman. Even after realizing its identity ç
with Brahman, Brahman alone is left, because the universe as sop<193>dhika ç
or conditioned Brahman has no real existence. The latter half deals ç
with pra<207>avop<193>sana or meditation on Brahman with the Pra<207>ava ç
or O<209>k<193>ra.
Pr<193>j<193>patya-br<193>hma<207>a, the second, prescribes the ç
cultivation of the three qualities of dama (self-control), d<193>na ç
(giving gifts) and day<193> (showing compassion) as a part of up<193>san<193> ç
or meditation by means of an interesting parable.
The third is the H<216>daya-br<193>hma<207>a which eulogises the ç
heart, the seat of the intellect. The fourth and the fifth br<193>h-ma<207>as ç
enjoin meditations on the h<216>daya-brahman as Satya (the Truth) ç
and its eulogy. Meditations on the different parts of its body are ç
also described. The ak<218>ipuru<218>a (the ocular being) or the j<200>va ç
and the <193>dityapuru<218>a or the solar being are aspects of Satya-brahman. ç
At the time of death, the solar being withdraws his raysand hence ç
the dying man sees the sun as an orb without its rays.
@SPACE1 = 
The sixth called Mano-br<193>hma<207>a, enjoins a meditations on ç
vidyut (lightning) and v<193>k (speech or the Vedas) as Brahman. The ç
ninth recommends meditation on agnior fire as Vai·v<193>nara or Vir<193>j. ç
The tenth section known as the Gati-br<193>hma<207>a des-cribes ç
the goals of the above meditations, which is, residence in Brahmaloka ç
throughout the life-time of Hira<207>yagarbha. Tapo-br<193>hma<207>a, ç
the eleventh, advises us to look upon illness or being carried forthe ç
funeral after death, as a tapas or penance, since it can destroy our ç
sins. The twelfth section enjoins that anna (food) and pr<193><207>a ç
(vital force) should be meditated upon asBrahman. The thirteenth ç
br<193>hma<207>a recommends meditations on the pr<193><207>a as uktha ç
(a recitation connected with Soma-y<193>ga), yajus, s<193>man and ç
k<218>attra (the healer).
The G<193>yatr<200>-br<193>hma<207>a, the fourteenth, describes ç
a meditation on Brahman as possessing the G<193>yatr<200> as the up<193>dhi ç
or limiting adjunct. The four p<193>das or quarters of the G<193>yatr<200> ç
are to be identified respectively with the three worlds, the three ç
Vedas, the three pr<193><207>as or vital-airs and <193>ditya or the ç
sun. This will result in various divine fruits.
The last section contains a prayer to °ditya or the Sun and Agni or ç
the fire by a dying man, who has combined meditation with rites (j<210><193>na-karma-samuccaya), ç
for the removal of the obstacles to his journey on the uttar<193>ya<207>a ç
or the northern path, after death.
@SB = Sixth Chapter
There are six br<193>hma<207>as in this chapter. Pr<193><207>asa<221>v<193>da-br<193>hma<207>a, ç
the first one, demonstrates through an allegory that the pr<193><207>a ç
or the vital force, is the eldest and the best of all organs. Once, ç
a dispute arose among the sense-organs like the eye and the speech, ç
as to which of them was the greatest. Praj<193>pati when approached ç
by them for the adjudication, ruled that the greatest among them was ç
that organ by whose departure the body would be rendered more impure. ç
The departure of v<193>k (speech), cak<218>us (the eyes), ·rotra (the ç
ears), retas (organ of generation) and manas (the mind), one by one, ç
did not make the body more impure. It continued to live. But, when ç
pr<193><207>a (also called mukhyapr<193><207>a) tried to depart, all ç
the other organs also were pulled out of their places of residence. ç
Hence it was decided that the pr<193><207>a or the vital force was ç
the best.
@SPACE1 = 
The second is the Karmavip<193>ka-br<193>hma<207>a which teaches ç
the Pa<210>c<193>gni-vidy<193> or the Doctrine of the Five Fires. ç
<185>vetaketu, the proud son of the sage Gautama °ru<207>i, goes to ç
the court of the king Prav<193>ha<207>a Jaivali to exhibit his learning. ç
However, when the king puts him five questions, he is unable to answer ç
any of them. Crest-fallen, he returns to his father and objects to ç
his not having taught this subject. Since Gautama too did not know ç
this science, he chooses to go to the king to learn it from him. The ç
king teaches him Pa<210>c<193>gnividy<193> or the Doctrine of the ç
Five Fires. The five fires are: dyuloka (heaven), parjanya (rain), ç
this loka or world, puru<218>a (man) and yo<218><193> (woman). Householders ç
who know this meditation on the Five Fires as also the hermits who ç
meditate with faith on the Hira<207>yagarbha go to Brahmaloka by the ç
Uttar<193>ya<207>a, the northern path (also called Devay<193>na and ç
Arcir<193>dim<193>rga) and will not return to this world again. But ç
those who practise sacrifices and penances, and give gifts, will travel ç
along the path of smoke (called Dh<220>m<193>dim<193>rga or the Dak<218>i<207><193>yana ç
or Pit<216>y<193>na) to the Pit<216>loka, the world of manes. After ç
exhausting the results of their good deeds there, they return to this ç
world. They rotate like a Persian Wheel in the circle of transmigration, ç
till they attain the Devay<193>na or immediate liberation. The rest, ç
the ignorant ones, are born as moths, insects and so on.
The third section called <185>r<200>mantha-br<193>hma<207>a describes ç
the rite of <185>r<200>mantha (the paste for prosperity) as a means ç
to attaining greatness and thereby, wealth, which is needed to perform ç
the Vedic rituals. There is also the eulogy of this rite and the line ç
of teachers.
The  fourth  section  describes  the Putramantha rite, by which a ç
house-holder can get a worthy son or a worthy daughter. Only the performer ç
of the <185>r<200>mantha rite is eligible to conduct this rite.
The fifth, the last, section called Va<221>·a-br<193>hma<207>a describes ç
the long line of teachers from Hira<207>yagarbha up to Pautim<193><218><200>putra.
@SPACE = 
@SB = Conclusion
@SPACE = 
The B<216>had<193>ra<207>yaka Upani<218>ad occupies a pre-eminent ç
place among the Upani<218>ads not only for its size but also for its ç
teachings. Almost all aspects of the teachings of Ved<193>nta†Brahman/°tman, ç
creation, nature of the individual soul and its destiny, theory of ç
karma, analysis of thethree states of consciousness, various modes ç
of Upani<218>adic meditations, characteristics of a liberated being†find ç
a place in it.
The Upani<218>ad also throws some inte-resting light on the contemporary ç
society. Not only were there, great sages and men of learning, devoted ç
to their respective fields of knowledge, they would also meet occasionally, ç
either for disputation or for exchange of ideas. Noble kings like ç
Janaka, Prav<193>ha<207>a Jaivali and Aj<193>ta·atru, who were themselves ç
eminent men of learning, provided opportunities for such sages to ç
gather in their courts and also rewarded them generously. Women, earnestly ç
interested in Vedic learning, austerity or even self-knowledge had ç
easy access to it, as shown by the instances of Maitrey<200> (a housewife) ç
and G<193>rg<200> (a brahmav<193>din<200>, student of Vedic learning). ç
The fact that G<193>rg<200> was also one among the sages that had ç
assembled in the court of the king Janaka, and had dared to question ç
Y<193>j<210>avalkya, speaks volumes about the high status of women ç
during the Vedic period. The myth that the ancient Hindus always craved ç
for sons and looked down upon daughters has been exploded in the mantra ç
6.4.17 wherein the desire of the parents fora learned daughter (pa<207><195>it<193> ç
duhit<193>) has been clearly stated.
The Upani<218>ad also places frankly before us, examples of men of ç
conceit, born out of their scholarship or high birth (eg., D<216>pta ç
B<193>l<193>ki and <185>vetaketu) on the one hand and persons of great ç
humility and culture who were never averse to learning from the others ç
even though they may be inferior in the social hierarchy of those ç
days (eg., Gautama) on the other.
References to the powerful horses of Sindhu country, to the chariots, ç
kings and their big retinue, cows and gold coins as also to the various ç
kinds of spiritual sciences and rituals bespeak of a high degree of ç
civilization and culture.
@SPACE1 = 
One can safely say that the B<216>had<193>-ra<207>yaka Upani<218>ad ç
represents a landmark in the development of early philosophical literature ç
of India.
@NT = B<216>had-devat<193>
@N1 = (`[a] big work dealing with the] Vedic deities')
The sage <185>aunaka (500 <MS>B.C.<D>) has done yeomen service to ç
the preservation of the Vedic literature by composing ten works, generally ç
classed as `anukrama<207><200>s' (See <MS>ANUKRAMAØ®<D> for details.) ç
in which is included this celebrated work, B<216>had-devat<193>. ç
It is an index of the Vedic gods, more extensive than other similar ç
works.
This treatise on the Vedic deities isin the form of verses in the ç
anu<218><219>ubh meter spread over eight adhy<193>yas or chapters, ç
corresponding to the eight a<218><219>akas (the moreancient method ç
of dividing the <184>gveda) of the <184>gveda. The first two chapters ç
contain 125 verses of an introduc- tory nature which discuss several ç
aspects of Vedic grammar useful in the analysis or interpretation ç
of the Vedic words. Then the book takes up the difficult task of determining ç
and describing the devat<193>s or deities of the various s<220>ktas ç
of the <184>gveda, often narrating interesting anecdotes also, related ç
to those deities.
Some of the more ancient sages mentioned in this work are: <185><193>ka<219><193>yana, ç
Y<193>ska, <185><193>kap<220><207>i and G<193>lava.
Since an `°c<193>rya <185>aunaka' has been mentioned in this B<216>had-devat<193> ç
itself, some Western scholars opine that this work must have been ç
composed by another person, probably his contemporary. But other scholars ç
do not subscribe to this view.
See also <MS><185>AUNAKA<D>.
@NT = B<216>had-dharma-pur<193><207>a
The pur<193><207>as (Hindu mythological lore) served two purposes. ç
As the primary means of mass education they spread not only knowledge†both ç
secular and sacred† but also wisdom and culture. In addition they ç
also helped the society to preserve its historyand hoary traditions.
The pur<193><207>as are generally classified into two groups: the ç
mah<193>pur<193><207>as and the upapur<193><207>as. Each group comprises ç
18works.
The B<216>had-dharma-pur<193><207>a is an upapur<193><207>a, probably ç
compiled in the 13th century. It is more like a sm<216>ti or a dharma·<193>stra ç
than a pur<193><207>a. Rites and practices of the various var<207>as ç
and <193>·ramas, gifts, duties of women and others†these are some ç
of the topics dealt with. The birth and sports of K<216><218><207>a ç
are also portrayed.
See also <MS>PUR°ØAS<D>.
@SPACE = 
@NT = B<216>had<200>·vara Temple
@N1 = (`Temple of the Great Lord')
@SPACE = 
Belief in God is a basic human trait. Though this God may be the infinite ç
cosmic spirit, the human being, encased as he is, in a limited frame ç
and a limited mind, can think of him only in a place of worship or ç
in a temple.
Hindu temples are a very ancient institution. Their development has ç
been spread over several centuries. Though the earliest permanent ç
structures built out of stone and bricks that have withstood the vagaries ç
of time have been assigned to the 4th century <MS>A.D.<D>, icons of ç
gods and goddesses have been discovered even in the Harappa-Mohenjodaro ç
excavations (2500 <MS>B.C.<D>) suggesting the possibility of existence ç
of places of worship.
In the history of the development of the Hindu temples, the Co<202><193> ç
period (<MS>A.D.<D> 900-1200) is one of the golden periods. The B<216>had<200>·vara ç
temple of Ta<210>j<193>v<220>r (also spelt as Tanjore) in Tamil Nadu ç
is a remarkable structure, perhaps the biggest and the best, belonging ç
to this period. Itwas built by R<193>jar<193>ja the First (reign ç
<MS>A.D.<D> 985-1013).
The story goes that R<193>jar<193>ja was a victim of black leprosy ç
due to the sins committed in an earlier life as a hunter. To expiate ç
the sins and to get rid of the disease, he was commanded by his guru ç
Haradatta to build a temple for <185>iva after getting a li<209>ga ç
(emblem of <185>iva) from the river Narmad<193>. When the king went ç
to the river and got the li<209>ga out of water, it started growing ç
bigger and bigger. Hence the name B<216>had<200>·vara (b<216>hat<|>=<|>big ç
or large). The temple took twelve years to build and was consecrated ç
during <MS>A.D.<D> 1011. The official name given to the li<209>ga ç
or the deity is R<193>jar<193>je·vara.
The temple complex is situated in the southern half of a small fort ç
and is surrounded by a moat on the east andthe west. Apart from the ç
main temple, the complex contains temples of Dev<200> called B<216>hann<193>yak<200>, ç
Subrahma<207>ya, Ga<207>e·a, Navagrahas and a number of li<209>gas ç
estimated around 252.
The length and width of the actual temple structure is 45.5 metres ç
(150 ft.) and 27 metres (90 ft.).
@SPACE1 = 
The most striking feature of this temple is its vim<193>na or towered ç
sanctuary which rises perpendicularly from a 15 metre (50 ft.) high ç
square base and then tapers off to a total height of 65 metres (216 ç
ft.). There are fourteen storeys, with small pillars, pretty balcony ç
windows and beautiful images carved thereon. The kala·a or finial ç
is 3.8 metres (12.5 ft.) high and weighs 80 tonnes.
The li<209>ga itself is quite massive, both in diameter and in height.
Nandi, the mount of <185>iva, placed in front is also of generous ç
proportions, measuring nearly 6 metres (20 ft.) in length and 3.6 ç
metres (12 ft.) in height. It is said to be the second biggest in ç
India, the one at Lep<193>k<218>i (in Andhra Pradesh) being the biggest.
The corridor of circumambulation just outside the sanctum sanctorum ç
has fresco paintings depicting stories and incidents from Hindu mythology.
Another temple in the campus, dedicated to Subrahma<207>ya or K<193>rttikeya ç
(son of <185>iva) deserves our attention due to its being an exquisite ç
piece of architecture. The stone carvings of elaborate patterns are ç
perfect. Its vim<193>na (tower over the shrine) rises to a height ç
of 16.5 metres (55 ft.). It was probably built around <MS>A.D.<D> ç
1600 by the Naik dynasty.
The religious rituals of the temple are according to the Muku<219><193>gama ç
and thebrahmotsava, the chief festival, is conducted for 18 days ç
during April-May.
@SPACE = 
@NT = B<216>had-yogi-y<193>j<210>avalkya
@SPACE = 
The B<216>had-yogi-y<193>j<210>avalkya is a large work in Sanskrit ç
comprising 930 verses spread over 12 chapters. The subject matter ç
is a combination of some topics of dharma·<193>stras and of others ç
dealt with in works on yoga and mantras.
The work begins with the questions posed by some sages to Yog<200>·vara ç
of Mithil<193>.
The following is a brief summary of the twelve chapters:
<+>1.
@NK = Essence of the Vedas, the sm<216>tis and the fourteen vidyas; ç
<193>tma-j<210><193>na; mantrajapa.
<+>2.
@NK = Pra<207>ava or O<209>k<193>ra.
<+>3.
@NK = The Vy<193>h<216>tis (bh<220><199> etc.).
<+>4.
@NK = The G<193>yatr<200>.
<+>5.
@NK = Some ny<193>sas (purification of limbs).
<+>6.
@NK = Sandhy<193> ritual.
<+>7.
@NK = Sn<193>na (bath), tarpa<207>a (offering of water to the manes) ç
and japa (muttering of mantras). 
<+>8.
@NK = Pr<193><207><193>y<193>ma (breath control) and praty<193>h<193>ra ç
(withdrawal of mind from sense-objects).
<+>9.
@NK = Dhy<193>na or meditation.
10.
@NK = S<220>ryopasth<193>na (worship of the Sun  with  the  mantras  and ç
G<193>yatr<200>).
11.
@NK = Yogadharma or the practice of yoga.
12.
@NK = Origination of the ·<193>stras from the Vedas and allied topics.
The work quotes a large number of verses from the Manusm<216>ti ç
and contains many verses of the Bhagavadg<200>t<193> also. Several ç
passages from the Upani<218>ads too are found in it.
One interesting statement that this book makes is that G<193>rg<200> ç
was the wife of Y<193>j<210>avalkya. This however is not correct as ç
we find from the more authoritative scripture, viz., the B<216>had<193>ra<207>yaka ç
Upani<218>ad.
See also <MS>Y°J<178>AVALKYA<D> and <MS>YOGI- Y°J<178>AVALKYA<D>.
@NT = B<216>hajj<193>b<193>lopani<218>ad
@EMERGENCY = The Upani<218>ads are the foundation of the Ved<193>nta ç
philosophy. Apart from the ten Upani<218>ads, considered as very ancient ç
and canonical, there are a large number of other works, also designated ç
as Upani<218>ads. Most of these belong to a much later period and ç
are obviously the creations of the master-minds of the various sects ç
to further their own views. The B<216>hajj<193>b<193>lopani<218>ad ç
is one such, of the <185>aivite group. Assigned to the Atharva<207>a-veda, ç
it comprises 8 br<193>hma<207>as or chapters. The total number of ç
mantras†in verses, interspersed with long passages in prose also†is ç
178.
The Upani<218>ad is concerned mainly with bhasma or the holy ash, ç
dear to <185>iva.
@EMERGENCY = The sage Bhusu<207><195>a was a great yogi but with a ç
corvine body. Once Praj<193>pati entered into him in a subtle form ç
and made him approach K<193>l<193>gni Rudra (one of the several aspects ç
of God <185>iva) with the question, `O Lord! Kindly tell me about ç
the greatness of vibh<220>ti or the holy ash and rudr<193>k<218>a ç
(the berry of the tree Elaeocarpus ganitrus).'
The reply of the Lord as given in the first br<193>hma<207>a may be ç
briefly stated as follows: <185>iva has five faces: Sadyoj<193>ta, ç
V<193>madeva, Aghora, Tatpuru<218>a and ®·<193>na. From these emanated ç
five divine cows named Nand<193>, Bhadr<193>, Surabhi, Su·<200>l<193> ç
and Citravar<207><193>, all of different colours. The holy ashes prepared ç
out of the dungs of these cows are known as†vibh<220>ti, bhasita, ç
bhasma, k<218><193>ra and rak<218><193>.
The second br<193>hma<207>a starts with the question of Bhusu<207><195>i ç
about the rules concerning bhasmasn<193>na or a bath with the holy ç
ash. The Lord replies by stating that this world itself is bhasma ç
and it assumes several forms by being their antar<193>tman or the ç
inner Self. Here bhasma is identified with the Lord himself since ç
he alone is left when the super- imposed world is negated, even as ç
bhasma or ash is left when everything is consumed in the fire.
The world is called `agn<200><218>om<193>tmaka' since agni (the fire ç
element) and soma (the moon element responsible for rasa or essence ç
or juices) are its components in the cosmic sense. Agni and soma are ç
also identified with the <185>iva and <185>akti. Hence the whole world ç
is a product of the combination of <185>iva and <185>akti. One who ç
realises that <185>iva and <185>akti are identical and also his own ç
oneness with them, attains am<216>tatva or immortality.
The third br<193>hma<207>a describes the process of preparing the ç
vibh<220>ti or the holy ash. The dung of which types of cows is to ç
be selected and which to be avoided is stated first. After preparing ç
small balls of the dung and drying them in the sun, they have to be ç
offered into the fire with the appropriate mantras. The bhasma or ç
ash collected should then be scented with certaindry powders, uttering ç
the mantras as stated in the work.
The bhasma should then be applied all over the body, from head to ç
feet, chanting the Pa<210>cabrahma-mantras (Mah<193>n<193>r<193>ya<207>opani<218>ad ç
17 to 21) while doing so.
@SPACE1 = 
The fourth br<193>hma<207>a states the times of the day†like dawn, ç
dusk and night† when bhasma can be applied. This bhasma should be ç
applied as three lines on the forehead, with the three middle fingers ç
after mixing it with the water from a conch. While applying it, one ç
should think of the three aspects of God, Brahm<193>, Vi<218><207>u ç
and <185>iva. The bhasma can be applied on other parts of the body ç
also, like the chest, throat and nose.
The fifth br<193>hma<207>a gives some more details concerning the ç
wearing of bhasma on the forehead and other parts of the body. The ç
three lines have to be mentally identified with the three Vedas†the ç
S<193>maveda, the Yajurveda and the <184>gveda†in that order ç
from the top to the bottom. The members of the three var<207>as (br<193>hma<207>as, ç
k<218>attriyas and vai·yas) should use the bhasma of the g<193>rhapatya ç
fire used for the Agnihotra sacrifice. The avadh<220>tas†the saints ç
who have transcended the var<207>a and <193>·rama system† should wear ç
the ashes gathered from the cremation ground. The ashes obtained from ç
a <185>iva temple are sacred for all, without any distinction.
This is then followed by an eulogy of wearing the tripu<207><195>ra†the ç
three lines drawn with the bhasma†by narrating the fruits that will ç
accrue to the wearer. Then comes a castigation in strong terms, of ç
thosewho have abandoned wearing the bhasma or who deride and harass ç
the votaries that wear it.
The greatness and the miraculous powers of bhasma are recounted by ç
the next, the sixth, br<193>hma<207>a. It can revive even dead persons ç
if sprinkled upon the bodies with the M<216>tyu<210>jaya-mantra. ç
It can destroy the sins of even the vilest ones and can grant knowledge ç
even to Hari or Vi<218><207>u! The section ends with further eulogies ç
of the knowledge taught here, called B<216>hajj<193>b<193>lavidy<193>.
@SPACE1 = 
The seventh br<193>hma<207>a is almost a revision of the earlier section. ç
It also describes the birth of the rudr<193>k<218>a beads(the berries ç
of the tree Elaeocarpus ganitrus) and the mode of wearing them. ç
These beads were born out of the eyes (ak<218>aor ak<218>i) of Rudra, ç
and hence the name rudr<193>k<218>a. One who wears them on his body ç
attains infinite merit.
The last chapter†the eighth br<193>h-ma<207>a†states the results of ç
reciting this Upani<218>ad such as attaining purity, the capacity ç
to assert the power of the elemental  forces  like  fire  and  wind, ç
conquest of death and all the worlds, as also getting the knowledge ç
of all sciences. After  death,  the  reciter  attains  the Supreme.
See also <MS>BHASMAJ°B°LOPANI<186>AD<D>.
@NT = B<216>hajj<193>taka
Hindu astronomy and its allied branch, astrology, are as old as the ç
Vedas. Called `Ved<193><209>ga-jyauti<218>a' or simply `Jyauti<218>a' ç
it deals with the appropriate periods and timings for conducting the ç
Vedic sacrifices.
Astrology deals more specifically with the influence of the stars ç
and planets on human life, both at the individual and at the collective ç
level.
Of the several ancient works (in Sanskrit) on astrology, the B<216>hajj<193>taka ç
of Var<193>hamihira (<MS>A.D.<D> 600) is generally consi-dered as ç
the best and the most authoritative. It has 28 adhy<193>yas or chapters ç
and 409 ·lokas or verses in different metres. As the very name suggests, ç
it deals mainly with j<193>takas or horoscopes of human beings. Of ç
the four commentaries available now, that of Bha<219><219>a Utpala ç
is considered the best.
The topics dealt with in the work are: the twelve r<193>·is or the ç
zodiacal signs, the nine planets, effects of the planets at the time ç
of conception on the person to be born, indications of early death, ç
longe-vity of a child, lunar combinations, avocations as indicated ç
by the planets, miscellaneous planetary combinations, on evils, on ç
female horoscopes, on death and on lost horoscopes.
In the last chapter the author apo-logises for any mistakes that may ç
have crept in and also gives some information about himself. He was ç
the son of a br<193>hma<207>a, °dityad<193>sa by name, hailing from ç
the village Kapittha. He got his education and knowledge from Savit<216> ç
(the Sun-god). He lived in the court of Ujjayin<200> in the province ç
of Avant<200>.
See also <MS>B<184>HATSA<189>HIT°<D> and <MS>VAR°HA-MIHIRA<D>.
@NT = B<216>hannal<193>
This is the name that Arjuna, the great P<193><207><195>ava hero, ç
assumed when he had to live in the palace of the king Vir<193><219>a ç
for one year as a eunuch, among the ladies of the palace, teaching ç
them music and dancing.
When the Kauravas attacked Vir<193><219>a's capital and seized the ç
palace cows, B<216>hannal<193> became the charioteer of Uttara-kum<193>ra, ç
the son of Vir<193><219>a. Uttarakum<193>ra went to the battlefield ç
to repulse the attack but was too frightened to fight. So, B<216>hannal<193> ç
had to reveal his identity and do the fighting himself.
Arjuna had once been cursed to become a eunuch, by the nymph <188>rva·<200> ç
since he had spurned, though respectfully, her amorous advances. The ç
curse came in handy during the one year period the P<193><207><195>avas ç
had to live incognito as per the accord with the Kauravas, after ç
they had been defeated in the game of dice.
See also <MS>ARJUNA<D>.
@NT = B<216>han-n<193>rad<200>ya-pur<193><207>a
Pur<193><207>as or the mythological works of Hinduism serve several ç
purposes. They amplify and expound the truths contained in the Vedas. ç
They give us a glimpse of the contemporary history and culture. They ç
also prescribe a code of conduct to be followed by all, for the welfare ç
of the society. More often they give detailed accounts of several ç
sciences like town- planning, architecture, sculpture, medical sciences ç
or religious rites motivated by the desire for worldly well-being, ç
since that was their way of educating the public.
These pur<193><207>as are usually classified into two groups: the ç
Mah<193>pur<193><207>as and the Upapur<193><207>as. Each group is ç
said to contain 18 works and all are ascribed by tradition to the ç
sage Vedavy<193>sa.
The B<216>han-n<193>rad<200>ya-pur<193><207>a is classed among the ç
minor pur<193><207>as and is assigned to the period <MS>A.D.<D> 900. ç
It is a sectarian work of the Vai<218>nava schools. One of the printed ç
versions comprises 3600 verses in 38 chapters.
Sometimes this pur<193><207>a has been considered as the first part ç
of the N<193>rad<200>ya-pur<193><207>a itself.
Praise of Vi<218><207>u and of bhakti, geo- graphy of India, story ç
of Sagara, Ga<209>g<193>-m<193>h<193>tmya, a few vratas (religious ç
vows and rites), var<207><193>·rama-dharmas and ·r<193>ddha (obsequial ç
ceremonies)†these are the general contents of this pur<193><207>a.
See also <MS>PUR°ØAS<D>.
@NT = B<216>haspati
@N1 = (`Lord of prayer')
B<216>haspati is a name that is often mentioned in the Hindu scriptures, ç
right from the <184>gveda up to the pur<193><207>as and the dharma·<193>stras. ç
Obviously there are several B<216>haspatis, divine and human. 
In the <184>gveda he is described as the Lord of prayers and is ç
identified with Brahma<207>aspati (2.23.1). He is considered as a ç
devat<193> or a god. Ga<207>apati, the later paur<193><207>ic deity, ç
seems to have had his origin in this B<216>haspati-Brahma<207>aspati.
During the period of the epics and the pur<193><207>as he is described ç
as a sage, the son of A<209>g<200>rasa. Being a person of great learning<+>and ç
wisdom and an expert in the performance of rituals, the gods in heaven ç
under the leadership of Devendra, chose him as their guru or preceptor. ç
<185>ukr<193>c<193>rya, the preceptor of the asuras or demons was ç
his rival.
T<193>r<193> was his wife and the mother of Budha from Candra, the ç
moon. Budha is one of the planets.
He has many exploits attributed to him such as saving the worlds by ç
assuming the form of Agni or fire, saving the honour of <185>ac<200>dev<200>, ç
the consort of Devendra from being forced by the king Nahu<218>a, ç
surreptitiously acquiring the knowledge of the rejuvenation of the ç
dead through his son Kaca, misleading the asuras when <185>ukr<193>-c<193>rya ç
was away and so on.
B<216>haspati is the presiding deity of the planet called Guru or ç
Jupiter and effects beneficial results. In the works on iconography ç
he is described as a minor deity of splendid appearance, with rosary ç
or with four arms, carrying a da<207><195>a (staff) and a kama<207><195>alu ç
(water-pot) in addition. He is seated on a chariot drawn by eight ç
horses.
Sometimes, B<216>haspati is mentioned as the originator of atheism. ç
This may have been based on the myth that he once disguised himself ç
as <185>ukr<193>c<193>rya and taught atheism and materialism to the ç
asuras to mislead them!
There is one more B<216>haspati, the writer of a dharma·<193>stra, ç
or artha·<193>stra. Kau<219>ilya (300 <MS>B.C.<D>) has quoted several ç
verses from his work. The Mah<193>bh<193>rata alludes to B<216>haspati ç
who is said to have compressed into 3000 chapters the work on dharma, ç
artha and k<193>ma composed originally by Brahm<193>. The Vanaparva ç
of the Mah<193>bh<193>rata speaks of a work called B<216>haspatin<200>ti.
This B<216>haspati is said to have advised the kings, the acquisition ç
of only two vidy<193>s†vart<193> (agriculture, trade and commerce) ç
and da<207><195>an<200>ti (statecraft including the laws governing ç
crime and punishment as also the science of war).
@NT = B<216>hat<200>
@N1 = (`the big one')
The B<216>hat<200> is a well-known chandas or meter of Vedic Sa<221>hit<193>s. ç
Out of 14such Vedic meters, it occupies the 4th place. It has 4 p<193>das ç
or quarters, with 9 letters in each p<193>da. According to the sage ç
<185>aunaka, as mentioned in his Chando'nu-krama<207><200>, there ç
are 181 mantras in the <184>gveda Sa<221>hit<193> composed in the ç
B<216>hati metre.
B<216>hat<200> is also the name of a well-known commentary by Prabh<193>kara ç
(8th century) on the <185><193>bara-bh<193><218>ya, which itself ç
is a commentary by <185>abara (57 <MS>B.C.<D>) on the famous M<200>m<193><221>s<193>s<220>tras ç
of Jaimini (200 <MS>B.<|>C.<D>).
@NT = B<216>hat-par<193>·ara-sa<221>hit<193>
@N1 = (`A big<R>ç
collection of verses of Par<193>·ara')
Medieval, and even modern, Hindu practices depend much upon the dharma-·<193>stras, ç
works that generally deal with <193>c<193>ra and vyavah<193>ra, personal ç
and social conduct.-
One such work, though not an ancient one wielding greater authority, ç
is the B<216>hat-par<193>·ara-sa<221>hit<193>. It appears to be ç
a recast of an earlier work, the Par<193>·ara Sm<216>ti.
Said to have been imparted by the sage Par<193>·ara to Suvrata, it ç
contains about 3000 verses divided into 12 chapters.
The  subject  matter  contains  the following topics: the sphere of ç
the <193>ryas; the six daily karmas like bath, sandhy<193>, japa, ç
worship of gods and honouring guests; the G<193>yatr<200> mantra; ç
the duties of the various var<207>as and <193>·ramas; forms of marriage ç
and connected topics; on gifts; ·r<193>ddha or after-death ceremonies; ç
pr<193>ya·cittas or expiations; rites for propitiating deities like ç
Ga<207>e·a and Rudra; some aspects of yoga like pr<193><207><193>y<193>ma ç
and so on.
See also <MS>DHARMA<185>°STRAS<D> and <MS>PAR°<185>ARA<D>.
@NT = B<216>hatsa<221>hit<193>
Jyauti<218>a or astronomy is Ved<193><209>ga, a subsidiary science ç
that helps in determining suitable times for the performance of Vedic ç
sacrifices.
Over the centuries, Jyauti<218>a evolved into a much larger and much ç
more complicated science, embodying in itself, not only<+>astronomy, ç
but also astrology, the science that predicts the influence of the ç
planets and other heavenly bodies on human affairs.
One of the basic works on Hindu Astrology is the B<216>hatsa<221>hit<193> ç
of Var<193>ha-mihira (6th century <MS>A.D.<D>). Though it deals mainly ç
with astrology, it is quite encyclopaedic in its scope and includes ç
several other branches of knowledge as geography, architecture, iconography, ç
gem-therapy and so on. Each of these subjects has been treated, keeping ç
in view its significance as an augury or its astrological effects.For ç
instance, the section on rubies describes how one can know the quality ç
of a gem, but it also gives the effects of wearing a good ruby. 
Another interesting feature of this work is its 104th chapter. The ç
various stanzas that deal with the astrological effects of the planets ç
are composed in different meters, the name of the meter itself being ç
ingeniously included in the verse itself.
See also <MS>JYAUTI<186>A<D> and <MS>VAR°HAMIHIRA<D>.
@NT = b<216>nd<193>vana
The tulas<200> plant (holy basil) is consi-dered extremely sacred ç
so much so that almost every household†especially of the Vai<218><207>avas†deem ç
it a privilege to have it in their compound. More often than not, ç
it is enclosed in a brick structure filled with fertile earth. This ç
structure along with the plant is called b<216>nd<193>vana.
B<216>nd<193>vanas are also built on the sam<193>dhis (places of burial) ç
of Vai<218><207>ava s<193>dhus (sa<221>ny<193>sins and religious heads).
The word is sometimes used to indicate V<216>nd<193>ban (K<216><218><207>a's ç
childhood place) in Uttar Pradesh.
@NT = Buddha
@N1 = (`The Enlightened One')
Buddha (also known as Gautama Buddha and <185><193>kya Muni) is one ç
of the very few religious leaders of the world who have revolutionised ç
the life of a very large mass of people for generations, influencing ç
their religion, philosophy and culture including many aspects of arts ç
and sciences.
Born on a Vai·<193>kha p<220>r<207>im<193> day, as the only son of ç
<185>uddhodana (the king of Kapilav<193>stu) and M<193>y<193>dev<200> ç
(at Lumbi<207><200>, now in Nepal), he was named Siddh<193>rtha. He ç
lived an easy and protected life as the beloved prince and heir to ç
the throne up to the age of 29 years. He was married to the princess ç
Ya·odhar<193> and had a son (R<193>hula) by her. One day (for the ç
first time in his life), he went out to see the city. The sight of ç
an old man, a sick man, a corpse and a monk made a deep impression ç
on his mind. He then realized that life was full of suffering and ç
decided to become a monk to discover the path to blessedness, totally ç
free of all suffering. He renounced the world on a Vai·<193>kha p<220>r<207>im<193> ç
day, retired to a forest and practised very severe austerities but ç
to no avail. He then sat under a tree on the bank of the river Nair<193><210>jan<193> ç
in Gay<193> vowing that he would not get up from his seat until he ç
realized the truth. Soon, he was enlightened and it was again on a ç
Vai·<193>kha p<220>r<207>im<193> day. The tree came to be known as ç
`Bodhiv<216>k<218>a' and he became the Buddha, the enlightened one. ç
He then went to V<193>r<193><207>as<200> (K<193>·<200>) and gave his ç
first sermon there. This sermon came to be known as dharmacakrapravartana ç
or the discourse of setting in motion, the wheel of dharma. He was ç
35 at that time. He lived up to 80. For a long period of 45 years ç
he roamed about the country teaching his doctrines of spiritual wisdom ç
to one and all. He established a Sa<209>gha ora religious order of ç
his monastic disciplesto propagate his teachings. He passed away, ç
again, on a Vai·<193>kha p<220>r<207>im<193> day. Hence this day is ç
called the thrice-blessed day.
@SPACE1 = 
As regards the period of Buddha's life the dates vary from 624 <MS>B.C.<D>-544 ç
<MS>B.C.<D> up to 557 <MS>B.C.<D>-477 <MS>B.C.<D> It may be safely ç
assumed that he lived during the sixth century <MS>B.C.<D>
Buddha's teachings may be summarized as follows:
Buddha teaches `catv<193>ri <193>ryasaty<193>ni,' the four noble truths. ç
They are:
@SPACE1 = 
(a) du<199>kha  or  the  existence  of suffering  in  this  world;  (b)  du<199>kha- ç
samud<193>ya or that there is a cause for this suffering; (c) du<199>khanirodha ç
or that it is possible to stop this suffering; (d) du<199>kha-nirodha-m<193>rga ç
or that there is a way out of this suffering. He calls the last as ç
the <193>rya-a<218><219><193><209>gika-m<193>rga, or the eightfold ç
noble path. These eight steps are: samyag-d<216><218><219>i (right ç
views), samyak-sa<209>kalpa (right resolve), samyag-v<193>k (right ç
speech), samyak-karm<193>nta (right conduct), samyag-<193>j<200>va ç
(right livelihood), samyag-vy<193>y<193>ma (right effort), samyak-sm<216>ti ç
(right mindfulness)  and  samyak-sam<193>dhi  (right concentration).
Buddha calls the state of enlightenment as nirv<193><207>a which, ç
literally, means extinction (of all sorrow and suffering).
Compilation, preservation and elaboration of Buddha's teachings (leading ç
to several schools of Buddhism and Buddhist philosophy) took place ç
over centuries through several Buddhist Councils. The Vinaya Pi<219>aka ç
and the Sutta Pi<219>aka containing the rules for guiding the monks ç
and the direct teachings of Buddha were compiled during the first ç
Buddhist Council held immediately after Buddha's demise. The Abhidhamma ç
Pi<219>aka was compiled during the third Council conducted by the ç
emperor A·oka (3rd century <MS>B.C.<D>). The work is abstruse and ç
philosophical and contains the teachings of Buddha's disciples and ç
scholars of the tradition.
The three works together are known as the Tripi<219>aka or the Tipi<219>aka ç
and are the canonical works of Buddhism.
See also <MS>BUDDHISM<D>.
@NT = buddhi
@N1 = (`that by which [an object] is known', the intellect)
The word `buddhi,' indicating the intellect, is sometimes used as ç
a general term for the mind. At other times it is applied to the discriminative ç
faculty of the mind. According to the Advaita Ved<193>nta, the j<200>va ç
(individual soul) is the reflection of the <193>tman in this buddhi.
@BT1 = See <MS>ANTAßKARAØA<D> for details.
@NT = Buddhism
@N1 = (`religious principles and<R>ç
doctrines taught by Buddha')
`Buddhism' is the general name given by post-Buddha historians to ç
the religious principles and practices, doctrines and dogmas, of the ç
followers of Gautama Buddha. Though what Buddha taught might be regarded ç
as a cleansing or reformation of the Hinduism of his times, his teachings, ç
over the centuries, have attained a distinctive character of their ç
own,  thus  deserving  the  appellation `Buddhism' or `Buddha-mata' ç
or `Bauddha-dharma'.
The four noble truths (catv<193>ri <193>ryasaty<193>ni) and the eightfold ç
noble path (<193>rya-a<218><219><193><209>gika-m<193>rga) form the ç
core of Buddhism. Ahi<221>s<193> or non-injury or non-violence is ç
a cardinal ethical principle. Monastic life, as means to nirv<193><207>a ç
(libe-ration) and Buddha-hood is emphasized greatly.
During the second Buddhist Council held at Vai·<193>li (the present ç
Basarh of Bihar) about a 100 years after the demise of Buddha, there ç
was a split in the ranks of the Buddhists. The conservatives came ç
to be known as the Sthavirav<193>dis or Therav<193>dis. The rest came ç
to be called the Mah<193>s<193><209>ghikas. These two groups gradually ç
evolved the H<200>nay<193>na and the Mah<193>y<193>na schools. The ç
former stressed individual nirv<193><207>a as the goal of life. The ç
latter stressed compassion, in addition, so that all can be helped ç
in their attempts at obtaining nirv<193><207>a. Whereas Mah<193>y<193>na ç
flourished in China, Japan and Tibet, H<200>nay<193>na spread in <185>r<200> ç
La<209>k<193>, Myanmar (Burma) and some South East Asian countries.
Buddhism also developed in course of time, four schools of philosophy: ç
the M<193>dhyamika or <185><220>nyav<193>da, the Yog<193>c<193>ra ç
or Vij<210><193>nav<193>da, the Sautr<193>ntika and the Vaibh<193><218>ika.
Philosophical works on these schools were written both in P<193><202><200> ç
and Sanskrit languages.
@BT1 = See also <MS>BUDDHA.
@NT = Buddhiyoga
@N1 = (`the yoga of buddhi or intellect')
This is a unique word used only in the Bhagavadg<200>t<193> and ç
that too, only three times (2.49; 10.10 and 18.57).
`Buddhi' means the intellect and `yoga' means perfect concentration ç
as well as union. So, the path of spiritual discipline wherein the ç
buddhi plays an important role and ultimately leads to the union of ç
the j<200>va (the individual soul) with Param<193>tman (God) is buddhiyoga.
Karma or action normally binds a person due to the selfish desires ç
behind it. If karma is performed with the full understanding that ç
its motivation by selfish desires leads to sa<221>s<193>ra or the ç
bondage of transmigration, and that, if motivated by the spirit of ç
unselfish service and devotion to God, the same will lead to liberation, ç
it becomes buddhiyoga since this leads to the ultimate union with ç
God.
The commentators of the Bhagavad-g<200>t<193> have interpreted it ç
variously, depending upon the context. However, all the interpretations ç
boil down to the same meaning as given above.
These are some of them: karma per- formed with equanimity; ni<218>k<193>ma-karma-yoga ç
that leads to <193>tmaj<210><193>na or self-know-ledge; yoga endowed ç
with the vision of the <193>tman; uniting the mind with God and so ç
on.
See also <MS>BHAGAVADG®T°<D>.
@NT = Budha
For thousands of years, people all over the world have believed in ç
the influence of the planets on human life and history. Logically ç
speaking, the creation of the grahas or planets precedes that of the ç
living beings. Hence, some sort of cause and effect relation must ç
subsist between these two. This seems to be the basis for this belief.
The Navagrahas or the nine planets are regarded by the Hindus as of ç
the greatest astrological significance and are believed to influence ç
the life of the individual as also the course of history.
As per the traditional list, the nine planets are: Ravi or S<220>rya ç
(Sun), Soma or Candra (moon), Ma<209>gala or Kuja or A<209>g<193>raka ç
(Mars), Budha (Mercury), B<216>haspati  or  Guru  (Jupiter),  <185>ukra ç
(Venus), <185>ani (Saturn), R<193>hu and Ketu.
The seven days of the week have derived their names from the first ç
seven planets. R<193>hu and Ketu are not planets but ascending and ç
descending nodes of the moon.
Budha or Mercury is the fourth in this group of nine planets. According ç
to Hindu mythology, he is the son of Candra and T<193>r<193>. He had ç
once been transformed into a woman when he entered the forbidden forest ç
area, the Kum<193>ra-vana. Hence he is also considered as a str<200>graha, ç
a feminine planet. He is saumya (pacific in nature) and ·ubha (auspicious). ç
In images he is shown either as dark or yellow in complexion, wearing ç
a garland of yellow flowers, with four arms, carrying in his hands ç
sword, shield and mace, the last one being in the varadamudr<193> ç
(gesture of bestowal of boons). His consort is I<202><193>.
@NT = burial
@BT1 = Birth and death have ever proved to be a mystery to the human ç
mind. If birth, generally, has brought joy and satisfaction to a family, ç
death, on the other hand, especially of a near and dear one, has invariably ç
caused grief and consternation.
Again, disposal of the dead body was often looked upon as a religious ç
duty and custom. There seem to have been many ways of disposing off ç
the corpses: leaving them in a forest or an open field or on the top ç
of trees, immersing in rivers or the sea, burial and cremation.
Existence of the burial system might have been due to the belief that ç
the dead person's soul still resided in the body and might be resurrected ç
to a better birth in course of time.
Even by the time of the <184>gveda, cremation seems to have gained ç
precedence over all the other methods though burial was not unknown ç
(vide <184>gveda Sa<221>hit<193> 10.18.10-13). However, burial was ç
the rule as far as dead infants and yatis or sa<221>ny<193>sins (monks) ç
were concerned.
The body of the dead yati had to be bathed, adorned with new cloth ç
and buried in a pit as deep as the da<207><195>a (staff) which he ç
used to carry. Special Vedic mantras like the Puru<218>as<220>kta ç
had to be chanted during the burial process. The ·ikya (loop of strings), ç
the pavitra (cloth used for filtering water) and the kama<207><195>alu ç
(water-pot) had to be placed on the various parts of the body as recommended ç
by the dharma·<193>stra works and the pit filled with salt, sand and ç
earth. A mound may be raised later on the spot.
Burial seems to have been resorted to in the case of the yatis or ç
sa<221>ny<193>sins since they had ceremonially given up the Vedic ç
fires at the time of taking sa<221>ny<193>sa.
In the modern times, except certain classes of the lower castes, all ç
the others prefer cremation to burial.
@END = 
