@NID = (4 chapters). Thus, the 12,000 verses of this pur<193><207>a ç
are spread over 116 chapters in 4 p<193>das. This is followed by Lalitop<193>-khy<193>na ç
(in 40 chapters) which contains the famous Lalit<193>sahasran<193>ma, ç
a hymn known for its mystical power and is extremely popular in South ç
India.
The subjects dealt with in this pur<193><207>a may be summarised briefly ç
as follows: creation, geography of the earth and of Bh<193>ratavar<218>a, ç
manvantaras, pupils of Vy<193>sa and the distribution of the Veda·<193>khas ç
or branches of the Vedas; creation of gods, demons, gandharvas, sages ç
and their progeny; all aspects of ·r<193>ddha or obsequial ceremonies ç
in detail; exploits of the warrior-sage Para·ur<193>ma; story of the ç
descent of the river Ga<209>g<193> to this earth; Dhanvantari and ç
the °yurveda, the science of health and longevity.
The writers of the dharma·<193>stras have quoted verses from this ç
pur<193><207>a fairly extensively in support of their views.
See also <MS>PUR°ØAS.
@SPACE = 
@NT = Brahm<193><207><200>
@N1 = (`the spouse of Brahm<193>')
@SPACE = 
According to the <185>akti-cult or the cult of the Divine Mother, ç
each one of the major gods of the Hindu pantheon has his ·akti or ç
power, portrayed as the female consort or counterpart, with a similar ç
form, weapons and vehicle. Brahm<193><207><200>, also known as Br<193>hm<200>, ç
is the ·akti of Brahm<193>, the four-faced god of creation.
According to the Durg<193>sapta·at<200>, one of the basic texts ç
of the <185>akti-cult, when Kau·ik<200> Durg<193> was fighting the ç
demon Raktab<200>ja†whose blood, if spilled, could produce demons ç
similar to him†she manifested out of herself seven emanations. These ç
are usually called the Saptam<193>t<216>k<193>s or `Seven little Mothers'. ç
Br<193>hm<200> or Brahm<193><207><200> is the first among them.
@SPACE = 
@SPACE = 
According to the Matsyapur<193><207>a when Brahm<193> was in deep ç
meditation, his purebody divided itself into two halves† male and ç
female†and the female deity came to be known as Brahm<193><207><200>, ç
S<193>vitr<200>, Sarasvat<200> and ®atar<220>p<193>.
Iconographical works describe her as having four faces and six arms. ç
Her colour is pi<209>gala or tawny. She wears a deerskin as an upper ç
garment. She holds the rosary and a wooden spoon (sruva) as also a ç
book and a water pot in four hands. The other two hands display the ç
abhaya and the varada mudr<193>s, signifying the giving of protection ç
and boons asked for. She rides on a swan.
@NT = brahmanirv<193><207>a
@N1 = (`getting merged in<R>ç
Brahman')
The Hindu scriptures posit mok<218>a or liberation from transmigratory ç
existence as the ultimate goal of life. According to some Ved<193>ntic ç
works, this is attained when the j<200>va or the individual soul gets ç
merged in Brahman or Param<193>tman, the Absolute or the Supreme Soul.
Nirv<193><207>a means getting extinguished like a burning lamp being ç
blown out. When the little or the individual self (j<200>v<193>tman) ç
extinguishes  itself  into  Brahman  the Absolute, losing its separate ç
identity and becoming merged in Brahman, it is brahmanirv<193><209>a. ç
Another example that expresses the same idea is the merging of the ç
rivers into the ocean.
Brahmanirv<193><207>a or mok<218>a can be attained through j<210><193>na ç
(knowledge) and bhakti (devotion).
This word seems to be peculiar only to the Bhagavadg<200>t<193> ç
(vide 2.72; 5.24-26).
@SPACE = 
@NT = Br<193>hmanism
@N1 = (`Religion of Brahman')
@SPACE = 
Scholars from the Western countries who  got  interested  in  the  study  of ç
Hinduism during the 19th century and the early part of the 20th century, ç
used the words `Br<193>hmanism,' `Br<193>hminism' and `Vedism' to ç
indicate Hinduism. Since God, the Absolute, has been designated as ç
`Brahman' they used the word `Br<193>hma-nism'. Since, according to ç
them, it was a religion practised and propagated by the br<193>hma<207>as†members ç
of the first of the four var<207>as†it was also called `Br<193>hmi-nism'. ç
Again, the Vedas being the main and basic scriptures, the appellation ç
`Vedism' was also used.
However, a deeper and wider study of all aspects of Hinduism clearly ç
reveals the deficiency of these terms in indicating Hinduism.
@NT = Brahma-pari<207><193>ma-v<193>da
@N1 = (`the doctrine that Brahman transforms itself [into this world]')
The origin of this world, in which we live and move, is one of the ç
important topics invariably discussed in the dar·anas or the Indian ç
philosophical systems. The Ved<193>ntic systems, while agreeing that ç
Brahman, the Absolute, is the ultimate cause of this world, are not ç
unanimous about the way of evolution of the world from Brahman. While ç
the Advaita system describes Brahman as the unchanging reality and ç
hence, the world as only an illusory appearance foisted on it due ç
to ignorance of its real nature, the Vi·i<218><219><193>-dvaita system ç
accepts that Brahman does transform itself as this world even as milk ç
becomes curds. (pari<207><193>ma = transformation).
Vi·i<218><219><193>dvaita Ved<193>nta accepts Brahman (or ®·vara) ç
as the primary reality and cit (the sentient beings, the j<200>vas ç
or the individual souls) as well as acit (the insentient nature, also ç
called prak<216>ti) as secondary realities dependent on Brahman. Brahman ç
includes them in itself as an integral part, pervades them and transcends ç
them. It is this acit or prak<216>ti part that really gets transformed.
This doctrine which accepts that Brahman transforms itself into this ç
world through its prak<216>ti-part is known as `Brahma-pari<207><193>ma-V<193>da'.
@NT = brahmapura
@N1 = (`city of Brahman')
This word has been used in the Upani<218>ads in several senses. Just ç
as a city, (pura = city) full of people and various goods, supplies ç
the wants of the king, this body of several limbs and sense-organs, ç
supplies the needs of Brahman who resides in it in the form of the ç
j<200>va or the indi- vidual soul. Hence it is called `brahmapura' ç
or `the city of Brahman' (vide Ch<193>ndogya Upani<218>ad 8.1.1).
Sometimes the word is applied to the `lotus of the heart' (h<216>dayapu<207><195>ar<200>ka†the ç
psychic heart, where meditation is practised) since it `houses' Brahman; ç
i.e., Brahman is realised there by the practice of meditation on it, ç
there. (vide Mu<207><195>aka Upani<218>ad 2.2.7)
@NT = Brahmapur<193><207>a
@N1 = (`the pur<193><207>a [revealed by] Brahm<193>')
The religious practices of the modern Hindus depend largely upon the ç
information and instruction given by the paur<193><207>ic literature. ç
This literature has grown voluminously over several centuries.
Hindu tradition recognises 18 mah<193>-pur<193><207>as or major pur<193><207>as ç
and 18 upa-pur<193><207>as or subsidiary ones. The Brahma- pur<193><207>a ç
(also spelt as Br<193>hmapur<193><207>a) is invariably placed at ç
the head of the list of the major pur<193><207>as. It is sometimes ç
called the °dipur<193><207>a or the °dibrahma-pur<193><207>a. ç
It may have attained its present form by the 10th to the 12th century ç
<F51320MS>A.D.<F255D> It gets its name mainly due to the fact that Brahm<193> ç
narrates it, even though Vy<193>sa is the narrator in the later part. ç
It may have originated in the God<193>var<200> basin.
The Brahmapur<193><207>a, as available in print now, has 13,783 ç
verses, spread over 245 chapters.
The contents, which deal with various aspects of Hindu religion may ç
be presented briefly as follows: creation of the world and the living ç
beings, histories of various kings, description of the earth with ç
its seven islands, hells of various types, Dak<218>a's sacrifice and ç
its destruction by <185>iva, detailed descriptions of various places ç
of pilgrimage like Ek<193>mra, Avant<200> and Puru<218>ottamak<218>etra ç
(Pur<200>), origin of the river Ga<209>g<193>, story of R<193>va<207>a, ç
story of the king Hari·candra, story of <185>r<200> K<216><218><207>a ç
in detail, various avat<193>ras or incarnations of Vi<218><207>u, ç
performance of ·r<193>ddhas or obsequial rites, spiritual wisdom contained ç
in S<193><209>khya and Yoga dar·anas, and a eulogy of listening to ç
the whole pur<193><207>a.
Its treatment of the places of pilgrimage is fairly exhaustive and ç
its verses on this subject have been extensively quoted by the writers ç
on the dharma·<193>stras.
See also <MS>PUR°ØAS<D>.
@NT = brahmarandhra
@N1 = (`the crevice of<R>ç
Brahman')
The crevice in the crown of the head is called `brahmarandhra' since ç
Brahman (®·vara or God) is said to have entered this body through ç
this randhra or crevice, after creating it, to make it alive (vide ç
Aitareya Upani<218>ad 1.3.12).
If a person manages to leave the body at the time of death, through ç
this randhra, he goes to Brahmaloka or the world of Brahm<193>. Hence ç
the name. Of course, this is possible only for great yog<200>s, persons ç
of very high spiritual evolution.
Works on Ha<219>hayoga describe this brahmarandhra as the top end ç
of the su<218>umn<193> canal.
@NT = brahmar<218>i
@N1 = (`knower of Brahman')
A <216><218>i is one who has known the truth (<216><218> = to know) ç
or attained the final goal (<216><218> = to attain) of life. Of the ç
seven types of <216><218>is mentioned in the Hindu religious works, ç
the brahmar<218>i stands as the first or the highest in eminence. ç
He has known or experienced Brahman, the Absolute, theSelf of all, ç
and has thus reached the other end of sa<221>s<193>ra or transmigratory ç
existence.
If the word `Brahman' is interpreted as the Vedas, then, the brahmar<218>i ç
is one who has obtained a thorough knowledge of the Vedas.
The sages like <185>uka, Sanaka, Sanandana and Vasi<218><219>ha are ç
classed among the brahmar<218>is.
See also <MS><184><186>I.<D>
@NT = Brahma-Sam<193>j
@SB8.5 = a)	The background
During  the  latter  part  of  the eighteenth century and the early ç
part of the nineteenth, the Hindu society was in a state of turmoil. ç
English education and Christian culture imposed on a subject nation ç
by the British rulers and their comrades, the Christian Church, had ç
had a devastating effect on the minds of the younger generation. They ç
were fast losing faith in their mother religion, Hinduism, as also ç
in the Hindu values of life and culture. It was at this critical juncture ç
that three renaissance movements sprang forth from the bosom of Hinduism. ç
The Brahma Sam<193>j (also spelt as Br<193>hmo Sam<193>j) was the ç
earliest in the series, followed by the °rya Sam<193>j and the Ramakrishna ç
Movement.
@SB8.5 = b)	A Brief History
R<193>j<193> R<193>mmohan Roy (<MS>A.D.<D> 1772-1833), the founder ç
of the Brahma Sam<193>j was born in a village in the Hoogly district ç
of Bengal in 1772. Not much is known of his early life. He settled ç
down in Calcutta in 1814. By the time he came into prominence he was ç
already a good scholar in Sanskrit, Persian and Arabic languages. ç
Later  on,  he  mastered  the  English language also. Being dissatisfied ç
with the various Hindu religious practices of his times like idol ç
worship, child-marriage and Sat<200> (burning of widows on the funeral ç
pyres of their husbands) as also the problems of young widows, and, ç
after studying deeply the dharma·<193>stras (Hindu law-books) he came ç
to the conclusion that these were later accretions responsible for ç
the decadence of the Hindu society. With a view to reforming the Hindu ç
social valuesand practices and take them back to their original source, ç
viz., the Upani<218>ads, he established the Brahma Sam<193>j on August20, ç
1828. Scholars of repute  like  R<193>macandra  Vidy<193>-v<193>g<200>·a, ç
Utsav<193>nanda Vidy<193>v<193>g<200>·a and T<193>r<193>candra Cakravart<200> ç
were his collaborators in this work. He succeeded in building a permanent ç
home for it in 1830.
When he passed away in 1833, there was a temporary setback to the ç
movement. However, the entry of Dv<193>rak<193>n<193>th <187>h<193>k<220>r ç
and his son Devendran<193>th <187>h<193>k<220>r (father of the famous ç
poet, Rabindranath Tagore) rejuvenated the movement, the contribution ç
of the latter being much more.
@SPACE1 = 
It was the `Mahar<218>i' Devendran<193>th <187>h<193>k<220>r (as he ç
was popularly known) that introduced the study of the Upani<218>ads ç
and allied literature through a formal seat of learning which he named ç
as `Tattvabodhin<200> Sabh<193>'. This Sabh<193> attracted the attention ç
of the elite and its membership swelled. He also composed the text ç
of the oaththat every member of the Sam<193>j had to take at the ç
time of admission into it and framed a code of conduct to be followed ç
by all.
Ke·avacandra Sen (<MS>A.<|>D.<D> 1838-1884), the younger contemporary ç
of the Mahar<218>i Devendran<193>th was the next important leader ç
of this movement. He became the <193>c<193>rya or minister when he ç
was hardly twentyfour. He paid much greater attention to the propagation ç
of the Br<193>hmo ideals and social reforms. He started the V<193>m<193>bodhin<200>, ç
a Bengali journal meant exclusively for women as also the English ç
journal Indian Mirror. He toured the country extensively, delivering ç
lectures and opened a branch†the Veda Sam<193>ja† at Madras in 1864. ç
Serious differences with his mentor Devendran<193>th led to his parting ç
of ways and establishing his own organization, the `Brahma Sam<193>j ç
of India' (`Bh<193>rat-Var<218><200>ya Brahma Sam<193>j') in 1866. ç
The parent body came to be known as the `°di Brahma Sam<193>j'. Whereas ç
the latter considered the Brahma Sam<193>j movement as an integral ç
part of Hinduism, the doors of the former were open to the non-Hindus ç
also. Ke·avacandra Sen's Sam<193>j suffered a serious setback when ç
Pa<207><195>it <185>ivn<193>th <185><193>str<200> got separated from ç
him and established the `S<193>dh<193>ra<207> Brahma Sam<193>j' in ç
1878. Ke·av's marrying his minor daughter to the prince of Cooch Bihar, ç
against the rules of the Sam<193>j which he himself had framed or ç
endorsed, was one of the main reasons for this schism.
@SPACE1 = 
After Ke·avacandra Sen, there being no leaders of comparable eminence, ç
the influence of the Br<193>hmo movement gradually waned and it is ç
now almost a spent force.
@SB8.5 = c)	The Creed and the Rituals
According to the famous Trust Deed of the Brahma Sam<193>j created ç
by R<193>j<193> R<193>mmohan Roy, image worship in any form is to ç
be totally abjured, though its practice by others shall not be reviled. ç
It accepts the philosophy of the Upani<218>ads but rejects Vedic ritualism ç
and the worship of several deities current in the Hindu society. It ç
believes in one God, Brahman, the formless Supreme Reality. It lays ç
great emphasis  on  the  cultivation  of  moral virtues and advocates ç
social reforms like education of women, remarriage of widows, equal  share  for  women  in  parental ç
property, toning down of the caste distinctions and so on.
The pratij<210><193> or the oath to be taken by every member at the ç
time of admission into the Sam<193>j, as introduced by Devendra- n<193>th, ç
emphasised the need to repeat the G<193>yatr<200>mantra before food, ç
to give up image worship in any form, to pay the prescribed subscription ç
to the Sam<193>j regularly and to shape one's life according to the ç
principles of Ved<193>nta advocated by the founder.
Devendran<193>th also systematised the rites to be performed at birth, ç
at the time of naming the child, during marriage and at the time of ç
death†all in consonance with the basic principles of the Sam<193>j.
The service conducted during the weekly meetings generally consisted ç
of Vedic chanting behind a screen, readings from the Upani<218>ads, ç
discourses and prayers. Singing of devotional songs was added later ç
on by Ke·avacandra Sen.
@SB8.5 = d)	Epilogue
The Brahma Sam<193>j rendered useful service to the Hindu society ç
by popularising social reforms like the abolition of the practice ç
of the Sat<200>, by preventing conversion of the Hindus to Christianity ç
and by rousing the orthodox Hindus to revive their ancient religion. ç
However, its refusal to recognize the accepted canon of Hindu scriptures ç
and certain deep-rooted beliefs like the faith in the Avat<193>ras ç
or incarnations of God, undermined its credibility in the eyes of ç
the common Hindu masses. This may be the chief reason for its listless ç
existence now.
@SPACE = 
@NT = Brahma-sarovara
@N1 = (`lake of Brahm<193>')
@SPACE = 
Kuruk<218>etra, where the Mah<193>bh<193>rata war, between the P<193><207><195>avas ç
and the Kauravas, is said to have been fought, is a famous place of ç
pilgrimage even now. It is situated in the Karnal-Ambala region of ç
Haryana, about 40 kms. (26 miles) to the east of the Ambala city.
According to the pur<193><207>as it was surrounded by five lakes called ç
`Samantapa<210>caka.' One of these lakes, the biggest, is called Brahmasarovara ç
or Brahmasaras. Since it is situated in the present Kuru-k<218>etra ç
region, it is commonly known as the Kuruk<218>etra lake. It is also ç
called Pavanahrada. It is 1320 meters (4400 ft.) long and 640 meters ç
(2100 ft.) wide.
Brahm<193>, the creator, is said to have had his y<220>pasthambha ç
or the sacrificial pillar here. Hence the name `Brahma-sarovara.' ç
King Kuru, from whom the race of the Kurus originated, is said to ç
have performed tapas here.
There are two small islands inside this lake containing an ancient ç
temple of Vi<218><207>u and the ruins of some old temples.
Taking a bath in this lake, especially during the solar eclipse, is ç
considered to be extremely auspicious. Great merit also accrues to ç
those who circumambulate it.
See also <MS>KURUK<186>ETRA.<D>
@NT = Brahmasiddhi
@N1 = (`establishment [of the<R>ç
nature of] Brahman')
The Brahmasiddhi of Ma<207><195>ana Mi·ra (<MS>A.D.<D> 800) is one ç
of the four major independent treatises of Advaita Ved<193>nta belonging ç
to the Siddhi-group. The other three are: Nai<218>karmyasiddhi ç
of Sure·vara (<MS>A.<|>D.<D> 800), I<218><219>asiddhi of Vimukt<193>tman ç
(<MS>A.D.<D> 1200) and Advaitasiddhi of Madhus<220>dana Sarasvat<200> ç
(<MS>A.<|>D.<D> 1500).
The traditional view that Ma<207><195>ana Mi·ra and Sure·vara were ç
one and the same person has not been accepted by scholars of repute ç
in the field.
The work is in four chapters: Brahmak<193><207><195>a, Tarkak<193><207><195>a, ç
Niyogak<193><207><195>a and Siddhik<193><207><195>a. It is in ç
the form of verses (k<193>rik<193>) and long annotations (v<216>tti). ç
Out of the four commentaries said to have been written, that of <185>a<209>khap<193><207>i ç
has been traced and utilised by the savants interested in it. 
In  the  Brahmak<193><207><195>a,  nature  of Brahman is discussed. ç
The Tarkak<193><207><195>a discusses questions regarding perception ç
and whether `difference' can be perceived at all. The Niyogak<193><207><195>a†the ç
longest of the four chapters†refutes certain views of the M<200>m<193><221>s<193> ç
school. The Siddhik<193><207><195>a, the shortest, tries to show ç
that the Upani<218>adic  texts  treat  this  world  of multiplicity ç
as an appearance due to avidy<193> or ignorance.
The Advaita Ved<193>nta as propounded here differs from that of <185>a<209>kara ç
in certain respects. Yet, it is considered as an important handbook ç
of Advaita.
See also <MS>MAØ£ANA-MI<185>RA.<D>
@NT = brahma·il<193>
@N1 = (`the stone of Brahm<193>')
Hindu temples are built as per the instructions given in the <193>gamas. ç
The garbhag<216>ha or the sanctum sanctorum is the heart of the ç
temple structure. The icon of the deity is placed in the centre of ç
this. Below the icon, several objects are placed one above the other, ç
starting with the <193>dh<193>ra·il<193> (base stone). Over this are ç
placed a pot, tortoise and lotus made of stone, two more tortoises ç
and lotuses made of silver and gold and a funnel shaped tube called ç
`yogan<193>l<193>' above which the slab brahma·il<193> is placed. ç
The brahma·il<193> will be at the floor level. The icon is placed ç
over this brahma·il<193>.
@NT = Brahm<193>stra
@N1 = (`the missile of Brahm<193>')
The art and science of warfare was highly developed in ancient India, ç
if the accounts of war given in the R<193>m<193>ya<207>a and the ç
Mah<193>bh<193>rata are to be believed.
Weapons used were divided into twobroad categories: astras and ·astras. ç
Astras were missiles discharged from theirsources like the bow. <185>astras ç
were weapons used by directly holding them in hand. Arrows, discuses ç
and spears belong to the first,whereas swords belong to the second ç
category. 
By far, the most powerful of all the astras often mentioned in the ç
epics and the mythological lore is the Brahm<193>stra also called ç
`Brahma·irostra'. <185>iva is said to have given it to the sage Agastya. ç
Agastya gave it to Agnive·a who gave it to Dro<207>a. Arjuna got it ç
from Dro<207>a. 
According to another version, Brahm<193> the creator specially made ç
it for Devendra. The sage Agastya who got it in course of time, handed ç
it over to <185>r<200> R<193>ma.
It is more likely that the Brahm<193>stra was not a particular missile ç
physically existent, but a terrible power that could be invoked into ç
any missile by the appropriate mantras. Its use was restric-ted to ç
extraordinary situations and when the enemy was not an ordinary human ç
being. 
<185>r<200> R<193>ma is reputed to have killed R<193>va<207>a with ç
this Brahm<193>stra.
@SPACE = 
@NT = brahmas<220>tra
@N1 = (`the thread of Brahm<193>')
The cult of <185>iva and the worship of his emblem, the li<209>ga, ç
are as old as Hinduism itself. The li<209>gas installed in temples ç
are almost always made of stone. They consist of three parts out of ç
which only the third part†called `Rudrabh<193>ga'† is seen above the ç
ground. This cylindrical portion alone†termed `p<220>j<193>bh<193>ga'†is ç
to beworshipped. It contains certain lines technically called `brahmas<220>tra,' ç
without which the li<209>ga becomes unfit for worship.
See also <MS><185>IVALI<177>GA<D>.
@SPACE = 
@NT = Brahmas<220>tras
@N1 = (`aphorisms [dealing<R>ç
with] Brahman')
@SB = Preamble†S<220>tras
The system of education in ancient India required the students to ç
live in the campus of a forest academy along with the teachers. The ç
teaching imparted was, almost always, in the form of s<220>tras or ç
aphorisms, followed by explanations and discussions. At a time when ç
committing things  to  memory  was  considered supremely important, ç
this method suited admirably.
The s<220>tra literature is a class by itself. As per the norms set ç
for a s<220>tra, it should be `alp<193>k<218>ara' (consisting of minimum ç
number of letters), `asandigdha' (without doubt as regards the meaning), ç
`s<193>ravat' (must contain the essence of the subject) and yet`vi·vatomukham' ç
(reflect all aspects of the same). However, in their anxiety to economise ç
the words, the composers of the s<220>tra-works seem to have so overdone ç
it that bh<193><218>yas or explanatory commentaries by later writers ç
became necessary.
The ·rauta, the g<216>hya and the dharma s<220>tras form the earliest ç
bunch of s<220>tra literature. The dar·anas or the philosophical systems ç
which are of a later period, followed this s<220>tra model since it ç
served their purpose well.
@SB = Ved<193>nta Dar·ana
Out of the six dar·anas or systems of philosophy which accept the ç
authority of the Vedas (the basic scriptures of Hinduism), the last ç
two†the M<200>m<193><221>s<193> and the Ved<193>nta systems†are directly ç
connected with them. Whereas the former tries to reconcile the various ç
Vedic texts that seem to give different directions with regard to ç
the same ritual system, the latter attempts to make out a coherent ç
philosophy of Brahman (God, the Absolute) from the apparently conflicting ç
statements in the Upani<218>ads.
@SB = Prasth<193>natraya
The Ved<193>nta system, as its very name implies, deals with the Upani<218>ads ç
which are the end-portions (anta = end) of the Vedas and also contain ç
the essence (anta= core or essence) of the same. The system itself ç
is based on three canonical works: the Upani<218>ads, the Brahmas<220>tras ç
and the Bhagavadg<200>t<193>. The Upani<218>ads are called `·rutiprasth<193>na', ç
the Brahmas<220>tras, `ny<193>yaprasth<193>na' and the Bhagavadg<200>t<193>, ç
`sm<216>tiprasth<193>na', the three together being termed `prasth<193>natraya'. ç
`Prasth<193>na' means a school of philosophy or religion.
@SB = The Upani<218>ads
Though a very large number of works going by the name `Upani<218>ad' ç
are available in print today, orthodox tradition accepts only a handful ç
of them†twelve to fourteen †as ancient and authoritative. The entire ç
edifice of the Ved<193>nta system of philosophy depends upon these ç
few Upani<218>ads.
The teachings of the Upani<218>ads may, broadly speaking, be classified ç
as follows: Brahman as the ultimate cause of this world, nature of ç
Brahman, evolution of this world and its character, nature of the ç
living being as individual souls, their relationship with Brahman, ç
their involvement in this world as well as their transmigration, the ç
final goal of life, the disciplines that help in reaching that goal ç
and the nature of attainment of that final goal. 
It is a fact that the Upani<218>ads, as extant today, do not give ç
a coherent picture of these various subjects discussed in them. Since ç
tradition and orthodoxy deem the entire body of the Upani<218>ads ç
as one canonical scripture†the <185>ruti†it became necessary to reinterpret ç
and reorganise their teachings so as to give them a more coherent ç
look. It was exactly this that B<193>dar<193>ya<207>a attempted and ç
the result was the Brahmas<220>tras.
@SB = The Brahmas<220>tras
The work derives its name from the fact that it deals chiefly with ç
Brahman (God, the Absolute) as described in the Upani<218>ads, in ç
all its aspects. It is also known by other names as follows:
(a)<+><|>The Ved<193>ntas<220>tras, since the subject matter is that ç
of Ved<193>nta or the Upani<218>ads;
(b)<+><|>The <185><193>r<200>rakas<220>tras, since the °tman living ç
in the ·ar<200>ra or the body is dealt with in the work;
(c)<+><|>The Uttaram<200>m<193><221>s<193>s<220>tras  (as opposed ç
to the P<220>rvam<200>m<193><221>s<193>s<220>tras) since it does ç
m<200>m<193><221>s<193> or enquiry into the uttara or latter part ç
of the Vedas;
(d)<+><|>The Bhik<218>us<220>tras since it is specially recommended ç
for study by the bhik<218>us or the sa<221>ny<193>sins.
@SB = B<193>dar<193>ya<207>a, the Author
Nothing is known about B<193>dar<193>ya<207>a, the author of this ç
celebrated work. Tradi-tionalists identify him with Vy<193>sa, the ç
author of the Mah<193>bh<193>rata and the pur<193><207>as. The work ç
is generally assigned to the period 500 <MS>B.<|>C.<D>-200 <MS>B.<|>C.<D> ç
by the Indian and some Western scholars. However there are other scholars ç
who consider the two to be different and assign B<193>dar<193>ya<207>a ç
to the period <MS>A.<|>D.<D> 200.
@SB = About the Work
The work Brahmas<220>tras is in four adhy<193>yas or chapters. Each ç
adhy<193>ya is divided into four p<193>das or quarters. The p<193>das ç
comprise adhikara<207>as or topics, each composed of s<220>tras.
The total number of adhikara<207>as and s<220>tras, according to <185>a<209>kara, ç
the earliest commentator, are 191 and 555 respectively. However, variations ç
are seen in this number as also in the readings themselves. Splitting ç
one s<220>tra into two, fusing two s<220>tras into one or adding the ç
last word of a s<220>tra to the beginning of the next are some of ç
the reasons for such variations in the readings. Such alterations ç
in the structure of the s<220>tras have contributed to divergent interpretations ç
also. Not only that, divergent views have also arisen due to one school ç
considering a particular s<220>tra as stating the p<220>rvapak<218>a ç
(the prima facie view, the objection or doubt) and another school ç
accepting the same s<220>tra as the siddh<193>nta (the theory propounded ç
by the author of the work).
As already stated, each p<193>da of the various adhy<193>yas, comprises ç
several adhikara<207>as or topics. An adhikara<207>a needs must have ç
five parts connected in a graded manner. They are:
(1) vi<218>aya or topic; (2) vi·aya or sa<221>- ·aya, doubt; (3) p<220>rvapak<218>a ç
or opponent's view; (4) siddh<193>nta or established conclusion and ç
(5) sa<209>gati or connection between the different sections.
The number of s<220>tras in any adhikara<207>a depends on the nature ç
of the subject under discussion. Thanks to the ambiguity in the s<220>tras, ç
the titles and the number of the adhikara<207>as vary from commentator ç
to commentator. 
While Nimb<193>rka (13th century <MS>A.D.<D>) has the minimum number ç
of adhikara<207>as (151), Madhuv<193> (<MS>A.D.<D> 1238-1317) has ç
the maximum (223).
@SPACE1 = 
The purport of the s<220>tra itself is determined by the commentators ç
as per the principle of <218>a<195>vidhali<209>gas or six characteristic ç
signs. They are: upakrama and upasa<221>h<193>ra (the beginning and ç
theend), abhy<193>sa (repetition), ap<220>rvat<193> (novelty),  phala  (objective),  arthav<193>da ç
(eulogy) and upapatti (logicality).
True to its name, the work Brahma-s<220>tras, deals primarily with ç
Brahman as the highest truth, by realising which, a person transcends ç
transmigratory existence. The one and only authority for the existence ç
of Brahman as also for its true nature is the ·ruti, the j<210>anak<193><207><195>a ç
part (section dealing with the knowledge of Brahman/ °tman) of the ç
Vedas, comprising the  Upani<218>ads.  This  knowledge  of Brahman ç
can never be obtained by logic and reasoning which depend upon the ç
puny human intellect. Since the intellect depends upon the knowledge ç
gained by the senses and since Brahman, the pure consciousness that ç
he is, is beyond the ken of the senses, the ·ruti as revealed to the ç
<216><218>is is the only source for knowing him.
@SPACE1 = 
This takes us to the next point†the various Upani<218>adic statements ç
that form the basis for the philosophy of the Brahma-s<220>tras. ç
Since some of these statements appeared to contradict one another, ç
B<193>da-r<193>ya<207>a had to undertake the unenviable task of collating ç
them to weave out a homogeneous philosophy. While doing it, he naturally ç
chose the most ancient of the Upani<218>ads. Which are those Upani<218>ads ç
the statements of which, B<193>dar<193>ya<207>a has discussed in these ç
s<220>tras? There is no direct indication in the s<220>tras themselves ç
since they are too laconic. For this we have to depend almost entirely ç
on the bh<193><218>yak<193>ras or the commentators who, fortunately ç
for us, are more or less unanimous in deciphering the same.
In the first 31 adhikara<207>as (as per <185>a<209>kara) the major ç
statements that form the vi<218>aya or vi<218>ayav<193>kya (subject ç
matter) are from the following Upani<218>ads, with the number of such ç
sentences noted against them:
Ch<193>ndogya (14), B<216>had<193>ra<207>yaka (5), Ka<219>ha ç
(4), Taittir<200>ya (2), Mu<207><195>aka (3), Pra·na (1) and ç
Kau<218><200>taki(2).
Apart from these, sentences taken from the <185>vet<193>·vatara, ç
the Aitareya and the J<193>b<193>la have also been discussed.
While analysing the purport of the various passages from the Upani<218>ads, ç
B<193>dar<193>ya<207>a has quoted the opinions of other teachers also. ç
They are: °treya, °·marathya, Au<195>ulomi, K<193>r<218><207><193>jani, ç
K<193>·a-k<216>tsna, Jaimini and B<193>dari. Almost all these names ç
appear in the earlier works like the ·rauta-s<220>tras and the g<216>hyas<220>tras. ç
It is likely that some preceded B<193>dar<193>ya<207>a and others ç
like Jaimini might have been his contemporaries. Though he differed ç
from them, he has not criticised their views, probably because they ç
were also Ved<193>ntins of repute, who had accepted the Upani<218>ads ç
as the primary authority and Brahman as the highest Truth.
@SPACE = 
@SB = A Brief Synopsis
The contents of the work may now be summarised as follows:
@SPACE = 
@S10 = First Chapter
The first chapter comprising 134 s<220>trasin 39 adhikara<207>as ç
has been called Samanvay<193>dhy<193>ya, (samanvaya = harmony) since ç
it attempts to harmonise the principles dealt with in the various ç
Upani<218>ads.
The work starts with the famous s<220>tra ath<193>to brahmajij<210><193>s<193> ç
(`Now, therefore, the desire to know Brahman'). Since the knowledge ç
or experience of Brahman, leads to mok<218>a or freedom from transmigration, ç
it is very necessary to have a correct understanding of Brahman. Keeping ç
this in view, the treatise deals with the various statements in the ç
well-known Upani<218>ads concerning Brahman. Brahman is he from whom ç
this world came into existence, in whom it inheres and to whom it ç
returns at the end of a cycle of creation. The only source for the ç
knowledge of this Brahman is the ·ruti or the Upani<218>ads.
It is Brahman alone who is the ultimate cause of this world and not ç
prak<216>ti or pradh<193>na as the S<193><209>khyas aver, since it ç
is insentient. An insentient cause can never think or will and produce ç
such a perfectly designed universe. 
This Brahman is <193>nandamaya, full of bliss. He is transcendent ç
as well as immanent in this world, including the j<200>v<193>tmas ç
or the individual souls. The being of light that exists in <193>ditya ç
or the Sun and our eyes is also Brahman. He is also designated as ç
<193>k<193>·a, pr<193><207>a, bh<220>m<193> and ak<218>ara. The being ç
described as `a<209>gu<218><219>ha-m<193>tra puru<218>a' (the person ç
of the size of the thumb) is also really Brahman and not the j<200>va ç
or the individual soul. So also does the word °tman refer to him.
@SPACE1 = 
B<193>dar<193>ya<207>a quotes the opinions of °·marathya, Au<195>ulomi ç
and K<193>·ak<216>tsna in the fourth p<193>da of this chapter. °·marathya ç
thinks that the j<200>v<193>tmas are both different and non-different ç
from Brahman (or Param<193>tman) even as the sparks of fire are both ç
identical with and different from fire. Au<195>ulomi opines that the ç
j<200>vas are different from Brahman in the state of bondage but become ç
one with him in the state of liberation. K<193>·ak<216>tsna, however, ç
considers the two to be identical since it is Brahman that has become ç
the j<200>va also.
Though the views of these teachers are stated, B<193>dar<193>ya<207>a ç
does not give his own opinion or preference.
The last part of this chapter asserts that Brahman is both the up<193>d<193>nak<193>ra<207>a ç
(material cause) and the nimitta k<193>ra<207>a (efficient cause) ç
for this world.
@S10 = Second Chapter
Designated as Avirodh<193>dhy<193>ya, this chapter with 157 s<220>tras ç
distributed among 47 adhikara<207>as applies itself to dispel any ç
virodha or contradiction that may confront this philosophy of Ved<193>nta.
Ved<193>nta is not opposed to sm<216>ti (secondary scriptures like ç
the Bhagavad-g<200>t<193> and °pastamba Dharmas<220>tras) and ç
tarka (logic and reasoning). The opposition of schools like that of ç
S<193><209>khya is fallible. There is no contradiction among the various ç
statements in the Upani<218>ads dealing with subjects like creation. ç
This is the burden of the teaching of this chapter.
Out of the several non-Ved<193>ntic systems of philosophy that existed ç
during B<193>dar<193>ya<207>a's time, the S<193><209>khya system was ç
the most powerful. Hence it has been given special attention while ç
refuting other schools.
One of the important factors discussed here is the relationship between ç
the k<193>ra<207>a (the cause) and the k<193>rya (the effect). The ç
S<193><209>kyan view known as `Satk<193>ryav<193>da' states that the ç
k<193>rya or the effect pre-exists (sat = existing) in the k<193>ra<207>a ç
or cause. In the process of creation it just gets manifested and is ç
not newly produced, since something real can never be produced from ç
the unreal. On the other hand the Vai·e<218>ika school accepts the ç
`asat-k<193>rya-v<193>da,' according to which the previously non-existent ç
(=asat) effect is newly produced. In the former case, the effect ç
pre-exists in the up<193>d<193>na-k<193>ra<207>a (the material cause) ç
and in the latter, the nimitta-k<193>ra<207>a (the efficient cause) ç
is constant. B<193>dar<193>ya<207>a accepts these views partially ç
and declares, on the basis of the Upani<218>ads, that Brahman is `abhinna-nimitta-up<193>d<193>na-k<193>ra<207>a', ç
both the material and the efficient cause, for this world. Hence this ç
world is non-different from Brahman. The objection that this world ç
consists of insentient objects and hence cannot be the product of ç
the sentient Brahman does not hold good, since the <185>ruti, the ç
highest authority in such matters which are beyond the powers of the ç
ordinary human intellect, declares it to be so.
Brahman has no selfish motive in creating this world, since he is ç
self- contented. There is neither partiality nor cruelty in this creation ç
since justice is meted out to the j<200>vas according to their karmas ç
or deserts. The very purpose of creation of this world is to help ç
the j<200>vas to attain <193>nanda or bliss by getting established ç
in Brahman, the Bliss-Absolute.
@SPACE1 = 
Apart from the S<193><209>khya school, the other schools like those ç
of the Vai·e<218>ikas, the Buddhists, the Jains, the P<193>·upatas ç
and the Bh<193>gavatas, like the Pa<210>car<193>tras have also been ç
critically examined and dismissed. 
@S10 = Third Chapter
The third chapter is called S<193>dhan<193>-dhy<193>ya and is the ç
longest with 186 s<220>tras spread over 67 adhikara<207>as. Though ç
called thus, the topics discussed are diverse. They are: transmigration ç
of the j<200>va into other bodies, dream-creations of the j<200>va, ç
its experiencing the deserts of karma by the will of ®·vara or God, ç
various vidy<193>s or meditations mentioned in the Upani<218>ads and ç
clarifications regarding them, collating of a vidy<193> when described ç
differently indifferent Upani<218>ads, knowledge of the °tman or ç
Brahman as independent of karmas or rituals and duties prescribed ç
for the various <193>·ramas (stages of life like brahmacarya or sa<221>ny<193>sa) ç
as also pr<193>ya·-cittas (expiations) and so on.
@S10 = Fourth Chapter 
Known as Phal<193>dhy<193>ya this chapter is the shortest with only ç
78 s<220>tras and 38 adhikara<207>as. The main topic discussed is ç
the journey of the j<200>va after death to Brahmaloka by the `arcir<193>dim<193>rga' ç
or `devay<193>na', the path of light or of gods.
One who is interested in mok<218>a or liberation has to practise ·rava<207>a ç
(listening to the scriptures describing the nature of °tman [Brahman] ç
and allied disciplines until realisation). The various up<193>san<193>s ç
or meditations described in the Upani<218>ads aid the j<200>va in ç
the process of attaining mok<218>a. On attaining brahmaj<210><193>na ç
or knowledge of Brahman, sa<210>cita-karma (karma accumulated over ç
several lives) gets destroyed. °g<193>m<200>-karma, karma done after ç
realisation is rendered fruitless. The pr<193>rabdha-karma, the karma ç
that has already started this body and yielding the results, has to ç
be exhausted only by experiencing it.
The j<200>vas who have practised severe spiritual disciplines like ç
tapas (austerity), ·raddh<193> (devoted faith) and brahmacarya (celibacy), ç
as also vidy<193>s like meditation on Brahman will travel, after death, ç
by the arcir<193>dim<193>rga or the path of light comprising light, ç
day, bright fortnight and so on, and reach the Brahmaloka from which ç
there is no return. There are divine guides called `<193>tiv<193>hik<193>s' ç
who take the j<200>va through the various stations of light to the ç
Brahmaloka.
Anomalies in the descriptions concerning the details of the arcir<193>dim<193>rga ç
have been set right through proper interpretations and arguments.
The work ends with the declaration, `an<193>v<216>tti<199>  ·abd<193>t,'  repeated  twice  for ç
emphasis, (`There is no return since the scriptures declare so.') ç
meaning that the j<200>va reaching Brahmaloka will not return to this ç
mundane existence. Descriptions of the nature of the muktapuru<218>a, ç
the liberated soul, are given at the appropriate places. The views ç
of Jaimini, Au<195>ulomi and B<193>dari in this regard have also been ç
cited.
@SB = The Philosophy of B<193>dar<193>ya<207>a
@SPACE1 = 
B<193>dar<193>ya<207>a wrote the Brahmas<220>tras to systematise ç
the teachings of the Upa-ni<218>ads into a coherent philosophy. However, ç
since the s<220>tras are short and terse, it becomes quite a job to ç
find out what exactly is his own philosophy as revealed through this ç
work. Even so, with the help of the s<220>tras which seem to be more ç
unambiguous than the others, an attempt may now be made to portray ç
the same.
The one and only pram<193><207>a (source of knowledge) that B<193>dar<193>ya<207>a ç
accepts while expounding the Ved<193>nta system is <185>ruti or the ç
Vedas, especially the j<210><193>na-ka<207><195>a part or it, viz., ç
the Upani<218>ads. He considers the words of the Vedas as nitya or ç
eternal. Logic and reasoning, which can always be unsettled by superior ç
ones, can never be relied upon in determining the transcendental truths ç
like the ultimate Cause of the world. Sm<216>tis or secondary scriptures ç
like the Manusm<216>ti and  the  Mah<193>bh<193>rata  including  the ç
Bhagavad-g<200>t<193> can also be depended upon in so far as they ç
do not contradict the <185>ruti.
The <185>ruti declares Brahman as the origin of this universe, the ç
primary, nay, the only truth. In fact, the very definition (janm<193>dyasya ç
yata<199>, 1.1.2) makes him the uncaused cause, the ground of sustenance ç
and involution of the world. He is both the material and efficient ç
cause for the world. He needs no external implements or assistance ç
and can transform himself even as milk is transformed into its products. ç

He evolves himself into <193>k<193>·a (ether), v<193>yu (air) and ç
other products by willing the same; and, he is associated with every ç
stage of creation up to the last.
Since it is Brahman that has evolved into this world, this world is ç
non-different from him, even as an unfolded cloth is non-different ç
from the same which was earlier folded.
@SPACE1 = 
The activity of creation is a l<200>l<193> or effortless sport for ç
Brahman. But, since it is done as per the karmas of the unredeemed ç
j<200>vas, one should not attribute partiality or cruelty to him, ç
seeing the good and evil that exist here.
As regards the j<200>va or the individual soul, B<193>dar<193>ya<207>a ç
defines him as a `j<210>a' or knower, a being endowed with consciousness. ç
He has no birth or death. He is eternal and atomic in size. Whether ç
the j<200>va is an a<221>·a (part) of Brahman or his <193>bh<193>sa ç
(reflection) has not been stated clearly though the views of other ç
Ved<193>ntins like °·marathya, Au<195>ulomi and K<193>·ak<216>tsna ç
have been given.
The relationship between the j<200>va and Brahman has been likened ç
to the snake and its coiled-up state or light and its source. Thus ç
the question whether they are different or identical has been left ç
unanswered.
By meditation on °tman/Brahman leading to j<210><193>na, or experience ç
of the same, the j<200>va attains liberation. The <185>rutis give ç
equal importance to the perfor- mance of karma or prescribed actions ç
and ty<193>ga or renunciation of the same, though the performance ç
of duties prescribed for the respective <193>·ramas (stages of life) ç
has been stressed even for the spiritual aspirant. The fruits of the ç
various up<193>san<193>s or meditations practised by a j<200>va accrue ç
to him by the grace of ®·vara (Brahman as the ruler of the created ç
world).
On attaining the knowledge of Brahman all the sa<210>cita karma (accumulated ç
past karma) of the j<200>va will be destroyed. He will live as long ç
as the pr<193>rabdha karma (karma already fructified) lasts. But, ç
the karma does after attaining knowledge will not affect him.
@SPACE1 = 
The j<200>va who has reached the acme of meditation while living, ç
will, after death, travel by the arcir<193>dim<193>rga or devay<193>na ç
(the path of light or of the gods) and reach Brahmaloka from which ç
there is no return to this world. There, he will be one with Brahman, ç
non-different from him. The various attributes predicated of Brahman ç
get manifested in the liberated j<200>va. Caitanya or consciousness, ç
being his essential nature, is of course, always there.
In conclusion it can be affirmed that B<193>dar<193>ya<207>a, in these ç
s<220>tras, teaches a kind of advaita (Brahm<193>dvaita?).
He does not admit the existence of either the j<200>vas or the world, ç
as indepen-dent of or different from Brahman. Since he has accepted ç
the Upani<218>ads as the supreme authority and since the other teachers ç
like B<193>dari whom he has quoted, also did the same, he has not ç
contradicted them. Both the views†that Brahman is nirvi·e<218>a-cinm<193>tra-svar<220>pa ç
(pure consciousness without any attributes) and savi·e<218>a (with ç
attributes)†seem to be acceptable to him. Obviously he has tried to ç
reconcile the various, apparently conflicting, views expressed in ç
the Upani<218>ads and explain them rather than formulate his own philosophy.
@SB = The Commentators and their Works
@SPACE1 = 
The Vedas have been the foundation of Hindu religion and culture for ç
millennia. The philosophy of Ved<193>nta based on the Upani<218>ads ç
has held sway over the intelligentsia for centuries. Hence, it is ç
but natural that the Brahmas<220>tras of B<193>da-r<193>ya<207>a ç
has attracted the attention of the distinguished scholars over the ç
years who have enriched the Ved<193>nta literature by their brilliant ç
expositions. All these commentators have evinced great respect for ç
B<193>dr<193>ya<207>a and his monumental work. They have tried to ç
critically examine all the other schools that were important during ç
their days and to prove the superiority of the Ved<193>nta over them. ç
Of course, they were equally keen to establish their own school of ç
Ved<193>nta also.
@EMERGENCY = Of the several bh<193><218>yas or commen- taries available ç
to us today, that of <185>a<209>kara is the earliest. There might ç
have been quite a few bh<193><218>yas composed by the earlier writers. ç
It can however be stated with certainty that Upavar<218>a, to whom ç
<185>a<209>kara refers in his commentary (1.3.28; 3.3.53) must have ç
been one such. Bodh<193>yana, another commentator, referred to as ç
`v<216>ttik<193>ra' by R<193>m<193>nuja, is sometimes identified with ç
this Upavar<218>a though there is no unanimity regarding it. 
@EMERGENCY = The following list of commentators who have left bh<193><218>yas ç
directly on the Brahmas<220>tras may be useful to the students of ç
Ved<193>nta philosophy:
@Z_TBL_BEG = COLUMNS(6), DIMENSION(IN), COLWIDTHS(.2083,E1,.0692,E1,.0975,E1), ç
ABOVE(.0833), VGUTTER(.0097), KEEP(OFF)
@Z_TBL_BODY = TC2M, TL, TC2M, TC2M, TABLE TEXT, TC2M
Bh<193><218>yak<193>ra, +, , Period, , School of Ved<193>nta
@Z_TBL_BODY = TL8, TL8, TABLE TEXT, TL8, TABLE TEXT, TL8
<+>1., <185>a<209>kara, , A.D. 788-820, , Advaita
<+>2., Bh<193>skara, , A.D. 996-1061, , Bhed<193>bheda
<+>3., Y<193>davaprak<193>·a, , A.D. 1000, , Bhed<193>bheda
<+>4., R<193>m<193>nuja, , A.D. 1017-1127, , Vi·i<218><219><193>dvaita
<+>5., Madhva, , A.D. 1238-1317, , Dvaita
<+>6., Nimb<193>rka, , Latter half of<R>ç
13th century, , Dvait<193>dvaita
<+>7., <185>r<200>ka<207><219>ha, , A.D. 1270, , <185>aiva-<R>ç
<+>vi·i<218><219><193>dvaita
<+>8., <185>r<200>pati, , A.D. 1400, , Bhed<193>bhed<193>t-<R>ç
<+>maka-<R>ç
<+><+>vi·i<218><219><193>dvaita
<+>9., Vallabha, , A.D. 1473-1531, , <185>uddh<193>dvaita
10., <185>uka, , A.D. 1550, , Bhedav<193>da
11., Vij<210><193>nabhik<218>u, , A.D. 1550, , °tma-<R>ç
<+>brahmaikya-<R>ç
<+><+>bhedav<193>da
12., Baladeva, , A.D. 1725, , Acintya-<R>ç
<+>bhed<193>bheda
@Z_TBL_END = 
A brief summary of the more important of these schools may now be ç
given. Since the schools propounded by <185>a<209>kara, R<193>m<193>nuja ç
and Madhva are more well- known and gained precedence over the others, ç
they will be taken up first.
@S10 = <185>a<209>kara
<185>a<209>kara's dar·ana or philosophy as revealed in his bh<193><218>yas ç
on the Bhagavad-g<200>t<193>, the ten ancient Upani<218>ads and ç
the Brahmas<220>tras  is  now  well-known  as Advaita  Ved<193>nta.  The  oft-quoted  and ç
famous<|>verse `brahma<|>satya<221><|>jaga<%16>n<%0>mithy<193> j<200>vo ç
brahmaiva n<193>para<199>' (`Brahman alone is real; this world is ç
only an illusory appearance. The j<200>va is verily Brahman and is ç
not different from him.')<|>gives this philosophy in a nutshell. 
<185>a<209>kara categorises Brahman into twoaspects: Para-brahman ç
and Apara-brahman. Where the Upani<218>adic statements deny all limiting ç
adjuncts like name and form, created by avidy<193> or ignorance of ç
his essential nature to Brahman, he is Para, the higher, Brahman. ç
On the other hand, where these statements describe him as endowed ç
with name, form and several attributes, it is the Apara or the lower, ç
Brahman that is referred to. It is the latter that is the cause for ç
the creation of this world, its sustenance and its dissolution.
Really speaking, Brahman does not get transformed into this world. ç
The multiplicity of names and forms is only a `vivarta,'an appearance, ç
due to avidy<193> or ignorance, even as a snake is perceivedin a ç
rope in insufficient light. This, he calls as `adhy<193>sa' or `adhy<193>ropa' ç
(superimposition). Through vidy<193> or discriminative knowledge, ç
`apav<193>da' or desuperimposition takes place giving the true knowledge ç
of the reality. 
<185>a<209>kara  considers  the  j<200>vas  as caitanya  or  pure  consciousness,  but, ç
circumscribed by the anta<199>kara<207>a (the `inner organ' or mind). ç
The j<200>va, though nitya (eternal), ·uddha (pure), buddha (awakened) ç
and mukta (free), appears as kart<193> (the doer) and bhokt<193> (the ç
experiencer) due to the limitations imposed by the anta<199>kara<207>a.
The Upani<218>adic sentences like tat tvam asi teach the essential ç
identity between the j<200>va and Brahman, as pure consciousness,  after  eliminating  their ç
adventitious qualities.
<185>a<209>kara does accept kramamukti or gradual liberation of the ç
j<200>va after death, by travelling through the Devay<193>na, to Brahmaloka, ç
as described in the Upani<218>ads and the Brahmas<220>tras. However, ç
he is emphatic about sadyomukti or instant liberation, here and now, ç
simultaneously with the rising of j<210><193>na or knowledge. Such ç
a mukti is also called j<200>vanmukti, liberation even while living.
@SPACE = 
@S10 = R<193>m<193>nuja
@SPACE = 
R<193>m<193>nuja's  commentary  on  the Brahmas<220>tras is known ç
as <185>r<200>bh<193><218>ya. Apart from this, he has also composed ç
two more, smaller, works on the Brahma-s<220>tras, the Ved<193>ntad<200>pa ç
and the Ved<193>nta-s<193>ra. The former, being a later work, contains ç
some additional explanations.
@SPACE1 = 
R<193>m<193>nuja's <185>r<200>bh<193><218>ya is stated to follow ç
in the footsteps of the more detailed Bodh<193>yana-v<216>tti as ç
also the works of some earlier Ved<193>ntins like Brahmanand<200> ç
and Drami<195><193>c<193>rya whose works are not available now.
R<193>m<193>nuja accepts Brahman as the highest and independent reality. ç
However Brahman includes in himself cit (the sentient beings, the ç
j<200>vas) and acit (the insentient prak<216>ti or nature). These ç
two are also real, but under the absolute control of Brahman. Brahman†also ç
called ®·vara by him†includes them, is immanent in them and also transcends ç
them. Hence, R<193>m<193>nuja's system is called `Vi·i<218><219><193>dvaita,' ç
advaita or non-duality of Brahman, the Absolute, but `vi·i<218><219>a' ç
or qualified by cit and acit. It is similar to a tree with branches, ç
leaves and fruits. Though the tree is `one,' it has internal parts, ç
each part being different from the other parts, the tree itself, however, ç
always remaining as one.
To  R<193>m<193>nuja,  Brahman  is  the Supreme Person (Sarve·vara) ç
who is the ruler of all. He is antagonistic to all evil. He possesses ç
infinite auspicious qualities. He is Omniscient and Omnipotent. The ç
creation, subsistence and reabsorption of this world proceed from ç
him.
R<193>m<193>nuja considers the j<200>va or the individual soul as ç
the spirit different from the body, atomic in size and endowed with ç
j<210><193>na or consciousness which contracts or expands.
He has a free will. And, the j<200>vas are infinite in number. Some ç
j<200>vas called `nitya' are ever free. Others who are now `baddha' ç
or bound, can attain mukti through bhakti and prapatti (devotion and ç
surrender) and the grace of God. All the liberated j<200>vas are similar ç
in nature.
@SPACE1 = 
Spiritual life starts with the performance of the prescribed karmas ç
in the right spirit leading to the purification of the mind. Such ç
a pure j<200>va becomes fit to practise j<210><193>na and experience ç
his separateness from the body-mind complex. However, it is through ç
bhakti and prapatti that he ultimately attains Brahman through the ç
devay<193>na and becomes free.
@S10 = Madhva
A thorough-going dualist, Madhva has composed 37 works which collectively ç
go by the name Sarvam<220>la. The short and tersebh<193><218>ya ç
on the Brahmas<220>tras, the A<207>ubh<193><218>ya <|>a<|> brief ç
<|>treatise <|>on <|>the <|>same, in verses, Ny<193>yavivara<207>a and ç
the Anuvy<193>khy<193>na are the four works on the s<220>traprasth<193>na. ç
His is a philosophy of realism and a monotheistic theology cente-ring ç
on devotion to Vi<218><207>u or N<193>r<193>ya<207>a. 
According to him Brahman, identified with Vi<218><207>u (N<193>r<193>ya<207>a) ç
is the independent reality. Prak<216>ti or matter and the j<200>vas ç
or souls who are atomic and infinite in number, are coeval realities ç
but entirely dependent on him. Brahman is essentially knowledge and ç
bliss. Though his infinite personality is beyond our conception, out ç
of grace for us, he can take forms which are neither material nor ç
finite. 
Madhva proclaims the theory of pa<210>cabhedas or five eternal differences ç
between Brahman and the j<200>vas, Brahman and prak<216>ti, j<200>vas ç
and prak<216>ti, j<200>va and j<200>va and various objects of prak<216>ti.
He categorises the j<200>vas into three groups: muktiyogyas, nityasa<221>s<193>rins ç
and tamoyogyas. The first group is capable of attaining mukti or liberation. ç
The second group, being interested only in the crass pleasures of ç
the world and not a whit in moral regeneration or spiritual elevation, ç
eternally go through the rounds of births and deaths. The third group, ç
the damned sinners that they are, degenerate into lower births and ç
suffer in hell.
The j<200>vas get liberation through bhakti and the grace of God. ç
In the state of liberation they are not only freed from suffering ç
but also enjoy positive bliss. Differences among the j<200>vas, however, ç
persist even in the state of liberation. 
@S10 = Bh<193>skara
Bh<193>skara is the trail-blazer for the post-<185>a<209>kara schools ç
of Ved<193>nta which did not agree with <185>a<209>kara's brand of ç
advaita based on m<193>y<193>v<193>da, the theory of the unreality ç
of the world. He is a strict Ved<193>ntin in the sense that he takes ç
his stand on the Upani<218>ads and the Brahma s<220>tras. His commentary ç
on the latter expounds his philosophy.
Bh<193>skara advocates the acceptance of the direct meaning of all ç
the passages of the Upani<218>ads without distinction. He presents ç
a Brahman who has innumerable auspicious attributes, but, without ç
any particular form. He has a twofold power †the  bhokt<216>·akti  (the  power  of  the ç
enjoyer) and the bhogya·akti (the power of the enjoyed). Using these ç
two powers he transforms himself into the acetana or insentient objects ç
and the j<200>vas or the sentient souls. Though this transformation ç
is real, it does not affect him in any way. The j<200>vas in their ç
essential nature are one with Brahman, but get differentiated from ç
him in the state of bondage due to the up<193>dhis or limiting adjuncts†the ç
bodies and the minds†which are real. These up<193>dhis, though real, ç
are not nitya or eternal. They are to be considered as real since ç
they are actually experienced. But, in the state of liberation, they ç
become one with Brahman even as the rivers flowing into the ocean ç
become one with it.
Bh<193>skara considers this world as the k<193>ry<193>r<220>pa or ç
effect, of Brahman, and hence real.
As regards the s<193>dhana, Bh<193>skara recommends  performance  of  scripture- ç
ordained duties without desire for their fruits and the practice of ç
meditation on Brahman as also the j<200>va's oneness with him. Since ç
he does not accept a personal God, there is no place for divine grace ç
in his system.
@S10 = Nimb<193>rka
Nimb<193>rka's Dvait<193>dvaita is very similar to the Bhed<193>bheda ç
of Bh<193>skara. However, being a firm believer in Brahman with form ç
and attributes and the path of devotion, his philosophy is more akin ç
to that of R<193>m<193>nuja.
Nimb<193>rka's main work is Ved<193>nta-p<193>rij<193>ta-saurabha ç
which is his commentary on the Brahmas<220>tras. It is rather brief ç
but lucid, since he avoids the dialectical methods or a flowery style.
According to him there are three equally real and co-eternal tattvas ç
or principles: Brahman, cit and acit. While Brahman is the controller ç
or niyant<216>, cit (the sentient being, the j<200>va or the souls)is ç
the enjoyer, bhokt<216> and acit (the insentient nature, prak<216>ti) ç
is the enjoyed, bhogya.
Acit is of three kinds: pr<193>k<216>ta or what is derived from prak<216>ti ç
or primal matter; apr<193>k<216>ta or what is not derived from a non-material ç
substance of which the world of Brahman is made and, k<193>la or time. ç

They are different from one another in their svar<220>pa or nature. ç
But the cit and  the  acit  are  paratantra-tattvas, dependent realities. ç

Nimb<193>rka adopts the view that the bheda (difference) and the abheda ç
(non- difference) are both equally real. They co-exist but do not ç
contradict each other. It is something like the relationship between ç
the sea and its waves or the sun and its rays. Cit and acit, the souls ç
and the universe, exist in Brahman from all eternity and never get ç
separated from him whether in the casual state or when manifested. ç
They retain their individuality even during salvation or dissolution ç
of the universe.
Brahman is personal, possesses a celestial body, full of exquisite ç
beauty and grace. Nimb<193>rka identifies him with K<216><218><207>a ç
and posits R<193>dh<193> as his <185>akti or consort even as R<193>m<193>nuja ç
accepts Lak<218>m<200> as the consort of Vi<218><207>u-N<193>r<193>ya<207>a.
Brahman is omniscient, the cause of the origin, sustenance and destruction ç
of the universe. He is all-powerful and yet all-merciful. He is gracious ç
to his devotees and helps them have a direct vision of himself.
The j<200>vas are atomic and infinite in number. Each of them is a ç
distinctive agent, a j<210>at<216> (knower), kart<216> (doer) and ç
bhokt<216> (enjoyer) of the karmas he does. They animate the body ç
they live in, even as a small lamp kept in a room lights up the whole ç
room. 
There are three destinies for the j<200>vas†naraka or the hell for ç
the sinners, svarga or heaven for the virtuous and apavarga or release ç
for enlightened ones. Apavarga  is  attaining  the  world  of Brahman ç
from which there is no return.
Constant meditation on Brahman as the inmost Self of the j<200>va ç
or the individual soul is the means of attaining Brahman in Brahmaloka. ç
There he has brahma-svar<220>pa-l<193>bha, becomes similar in nature, ç
except for the power of creation.
The other s<193>dhan<193>s recommended are: scripture-ordained work, ç
knowledge, devotion and surrender to God, as also strict obedience ç
to the spiritual teacher.
@S10 = Vallabha
Vallabha's philosophy is known as <185>uddh<193>dvaita. He is said ç
to have written two commentaries on the Brahmas<220>tras, the B<216>hadbh<193><218>ya ç
and the A<207>ubh<193><218>ya, of which the former is not available ç
now. The latter is up to the 33rd s<220>tra of the second p<193>da ç
of the third adhy<193>ya (3.2.33). The book was completed by his son ç
Vi<219><219>halan<193>tha. Apart from the prasth<193>natraya, he holds ç
the Bh<193>gavata in very high esteem. He wrote a commentary onit ç
also, called Subodhin<200>, which too remained incomplete.
For Vallabha, God the Absolute is K<216><218><207>a whom the Upani<218>ads ç
call `Brahman'. He is one without a second and is sat-cit-<193>nanda, ç
(being, awareness and bliss). He has three forms: Parabrahman, Puru<218>ottama ç
or K<216><218><207>a; Antary<193>min, the indwelling spirit of all ç
the living beings and Ak<218>ara-brahman which is the object of meditation ç
and the abode of K<216><218><207>a. It is this Ak<218>ara that appears ç
as prak<216>ti (insentient nature, the matrix of all created objects) ç
and puru<218>a (sentient soul, the j<200>va), but is beyond both. ç
While Puru<218>ottama is the highest, Ak<218>ara is an expression ç
of his.
This Ak<218>ara, again, appears in three more forms: k<193>la (time), ç
karma (action) and svabh<193>va (nature).
K<193>la or time is suprasensible and is inferred from its effects. ç
It is all-pervasive and the support of all beings. Karma or action ç
is also universal. It manifests itself as different actions of different ç
beings. Svabh<193>va or nature is that which produces pari<207><193>ma ç
or change.
God is both sagu<207>a and nirgu<207>a (with and without attributes). ç
He cannot be known except through his own grace. Through his m<193>y<193>·akti, ç
he can become anything at any time. He is both the material and the ç
efficient cause of this world. He creates the world through his own ç
nature and hence the samav<193>yi-k<193>ra<207>a, the inherent cause. ç
Though he exists everywhere in his tripartite nature as being, consciousness ç
and bliss, their manifestation in the created universe differs. Matter ç
reflects only the being aspect (`sat'), the souls reflect the consciousness ç
also (`cit') whereas as Brahman, he manifests all the three fully.
Though unmanifest and transcendent in his own nature, by creating ç
the world through his will, he becomes manifest and an object of comprehension. ç
Since this world is a manifestation of Brahman, it is never destroyed ç
but is only withdrawn into him at his will.
@SPACE1 = 
The j<200>vas or individual souls come out of Ak<218>ara Brahman like ç
sparks from fire. They are eternal parts of Brahman and are atomic ç
in size. They are of three classes: pu<218><219>i, mary<193>da and ç
prav<193>ha. The first are the chosen ones enjoying the grace of God, ç
and ardently devoted to him. The second study the scriptures, perform ç
the rites prescribed as ordained duties and also cultivate devotion. ç
They attain God in course of time. The last are interested only in ç
the worldly life and hence transmigrate constantly. Some of them, ç
due to satsa<209>ga or good company, may attain God later. 
Vallabha considers bhakti or devotion as the only means of salvation. ç
By that, the j<200>va is released from the cycle of birth and death ç
and enjoys the bliss of God in all possible ways.
Vallabha holds that the knower of Brahman is absorbed in Ak<218>ara-Brahman ç
and not in Puru<218>ottama. It is only through bhakti that the latter, ç
the highest aspect, can be attained.
He advocates two forms of bhakti: mary<193>d<193>-bhakti and pu<218><219>i-bhakti. ç
The former is formal devotion to be practised as described in the ç
scriptures and has to be cultivated by self-effort. The latter is ç
attained by the grace of God alone, without one's effort. `Pu<218><219>i' ç
refers, not to the physical nourishment, but to the spiritual nourishment ç
got by the grace of God. Hence the name `pu<218><219>i-bhakti'. Consequently, ç
Vallabha's system is also called `Pu<218><219>i-m<193>rga.' Emphasis ç
on the worship of B<193>lak<216><218><207>a, (child K<216><218><207>a) ç
and sev<193> or service to him, find an important place in the mode ç
of s<193>dhan<193> taught by him.
@SPACE = 
@S10 = Baladeva
@SPACE = 
Baladeva is an important teacher of the Bengal school of Vai<218><207>avism ç
developed by <185>r<200>k<216><218><207>a Caitanya (<F51320P10MSC1>A.D.<W1> ç
<F255P255DC255>1485-1533). The philosophy of this school is known as Acintyabhed<193>bheda.
Govindabh<193><218>ya is his commentary on the Brahmas<220>tras, ç
Siddh<193>ntaratna being another work that expounds this philo- ç
sophy. This school, though deeply indebted to thedvaita system of ç
Madhva, also differs from it. 
According to this school of thought, Brahman the highest reality is ç
K<216><218><207>a, Vi<218><207>u or Hari. He is the Personal God possessed ç
of infinite auspicious qualities, which are `acintya' or beyond our ç
comprehension. He is `nirgu<207>a' only in the sense that he is beyond ç
the three gu<207>as of sattva, rajas and tamas. The scriptures are ç
the only authority to reveal him.
God has three powers: par<193>·akti (higher power), apar<193>·akti ç
(lower power) and avidy<193>·akti (nescience power). Through the first, ç
he becomes the efficient cause, and, through the other two, the material ç
cause. When the latter two powers are manifested in gross forms, the ç
universe of souls and matter arises. 
Creation of the world is a spontan-eous act of the Lord. However, ç
he does it as per the karmas of the individual souls.
The individual soul is eternal. It is both knowledge and knower, an ç
enjoyer and an active agent, though not independent. It is atomic ç
in size.
@SPACE1 = 
Bhakti is the sole and direct cause ofsalvation. Though dhy<193>na ç
or up<193>san<193> (meditation) is one form of bhakti, it is through ç
prem<193>bhakti (intense devotion) that God can be realised. Performance ç
of duties purifies the mind. Study of the scriptures is an aid in ç
the path of s<193>dhan<193>. However, it is ultimately by the grace ç
of God alone that he can be realised and salvation attained. The freed ç
soul resides in the same world as the Lord and in hisproximity, attains ç
his nature and attributes. However, it retains its separate identity.
Baladeva does not admit of j<200>vanmukti or liberation while living ç
in the body here.
@SB = The Brahmas<220>tra Literature
Being the basic text of Ved<193>nta, bothin its metaphysical and ç
and in its dialectical aspect, the Brahmas<220>tras has attracted ç
the attention of a host of elite scholars over the centuries. Apart ç
from the direct bh<193><218>yas by the great <193>c<193>ryas, several ç
subcommentaries and glosses over them have enriched the Brahmas<220>tra ç
literature. In such literature now available to us, the maximum number ç
of works belong to the Advaita school. 
On the <185><193><209>karabh<193><218>ya, three <219><200>k<193>s ç
or subcommentaries are available in full: Bh<193>mati of V<193>caspatimi·ra ç
(<MS>A.<|>D.<D> 840), Ny<193>yanir<207>aya of °nandagiri (<MS>A.<|>D.<D> ç
1260) and Ratnaprabh<193> of R<193>m<193>nanda (17th century).
The one by Padmap<193>da (<MS>A.<|>D.<D> 820), a direct disciple of ç
<185>a<209>kara, called Pa<210>ca-p<193>dik<193> deals with the ç
first four s<220>tras (1.1.1-4) only. This was commentated uponby ç
Prak<193>·<193>tman (<MS>A.<|>D.<D> 1200) in his Pa<210>cap<193>dik<193>-vivara<207>am. ç
There is a gloss on this called Tattvad<200>panam by Akha<207><195><193>-nanda ç
Muni (<MS>A.<|>D.<D> 1350). All these commen- taries collectively, ç
have created the Viva-ra<207>a-prasth<193>na, a special school of ç
Advaita Ved<193>nta, in the post-<185>a<209>kara period.
As opposed to this, the Bh<193>mat<200>-prasth<193>na was developed ç
by Amal<193>nanda (13th century <MS>A.<|>D.<D>) in his Kalpataru ç
on the Bh<193>mat<200> and Appayya-d<200>k<218>ita (16th century ç
<MS>A.<|>D.<D>) in his Parimal<193>, on this Kalpataru.
Mention may also be made of a few other works on the Brahmas<220>tras, ç
con-sidered to be more important than others: Sa<209>k<218>epa·<193>r<200>rakam ç
of Sarvaj<210>atma Muni (<MS>A.<|>D.<D> 900), Vivara<207>aprameya-sa<209>graha ç
of Vidy<193>ra<207>ya (<MS>A.<|>D.<D> 1350), Brahmas<220>tra-d<200>pik<193> ç
of <185>a<209>kar<193>nanda (14th century <MS>A.D.<D>) and Brahmatattvaprak<193>·ik<193> ç
of Sad<193>·iva-brahmendra (18th century <MS>A.<|>D.<D>).
Comparatively speaking, the Brahma-s<220>tra literature of the other ç
schools of Ved<193>nta, is not so voluminous though it is in no way ç
inferior in its quality and its erudition.
After creating his magnum opus, the <185>r<200>bh<193><218>ya, ç
R<193>m<193>nuja wrote two more treatises on the Brahmas<220>tras ç
entitled Ved<193>ntad<200>pa and Ved<193>ntas<193>ra. The <185>r<200>bh<193><218>ya ç
has only one ancient commentary the <185>rutaprak<193>·ik<193> of ç
Sudar·anas<220>ri (13th cent. <MS>A.<|>D.<D>) On this, Ved<193>ntade·ika ç
(<MS>A.<|>D.<D> 1268-1369) wrote a gloss called Tattva<219><200>k<193>.
Apart from his bh<193><218>ya (generally called the Madhvabh<193><218>ya) ç
on the Brahma-s<220>tras, Madhva wrote the A<207>ubh<193><218>ya ç
in verses, giving the gist of the various adhikara<207>as of the work. ç
R<193>ghavendra-t<200>rtha (<MS>A.<|>D.<D> 1598-1671) has written an ç
extensive commentary on this and has named it Tattvama<210>jar<200>.
Trivikrama Pa<207><195>ita, a disciple of Madhva, has commented upon ç
the bh<193><218>ya of Madhva. It is called the Tattvad<200>pik<193>. ç
Tattvaprak<193>·ika of Jayat<200>rtha (<MS>A.<|>D.<D> 1365-1388) ç
and T<193>tparyacandrik<193> of Vy<193>sar<193>ya (<MS>A.<|>D.<D> ç
1481) are the other commentaries on the same.
@SPACE1 = 
However, the most celebrated work of the Dvaita school of Madhva is ç
the Ny<193>yasudh<193> of Jayat<200>rtha which is a highly dialectical ç
and yet lucid commentary on Madhva's Anuvy<193>khy<193>na, a work ç
elucidating his own commentary on the Brahmas<220>tras.
Nimb<193>rka's  commentary  on  the Brahmas<220>tras, known as the ç
Ved<193>nta-p<193>rij<193>ta-saurabha, has been expounded further ç
by Sr<200>niv<193>sa (13th cent. <MS>A.<|>D.<D>) in his Ved<193>nta-kaustubha ç
which again has been explained further by Ke·ava K<193>·m<200>rin ç
(15th cent. <MS>A.<|>D.<D>) in his Ved<193>nta-kaustubha-prabh<193>.
The other commentaries which have drawn the attention of the Ved<193>ntic ç
scholars are the Vij<210><193>n<193>m<216>ta-bh<193><218>ya of Vij<210><193>na-bhik<218>u ç
(<MS>A.<|>D.<D> 1550) and the commentary S<220>k<218>ma on Baladeva's ç
Govinda-bh<193><218>ya.
Apart from these works mentioned here, there are several other treatises ç
and tracts on the various aspects of Ved<193>nta asinterpreted by ç
the numerous schools.
@SB = Conclusion
There is no gainsaying the fact that the Ved<193>nta system based ç
chiefly on the Brahmas<220>tras†which itself is a systematic exposition ç
of the philosophy of the Upani<218>ads†has influenced all the important ç
aspects of Hindu religion and culture, including the modern Hindu ç
movements.
@SPACE = 
@NT = brahmav<193>da
@N1 = (`the philosophy<R>ç
[that propounds] Brahman')
@SPACE = 
The  Bh<193>gavata  occupies  a  pre- eminent place not only among ç
the pur<193><207>as but also among the general scriptures of Hinduism ç
on its own. It is a gospel of divine life and is not a textbook of ç
systematic philosophy.
Its teaching has a theoretical as well as a practical aspect. The ç
former is known as Brahmav<193>da and the latter as Bh<193>gavata-dharma.
The essence of Brahmav<193>da is that Brahman or °tman is the only ç
Absolute Reality. The whole universe, including our body, mind and ç
ego, is only an expression in name and form of that Brahman. However, ç
this view differs from pantheism in that Brahman does not exhaust ç
himself in the manifestation of this universe. He is neither limited ç
nor affected in any way by the phenomenal universe. And yet, he is ç
both immanent and transcendent.
See also <MS>BH°GAVATA.<D>
@NT = brahmav<193>din<200>
@N1 = (`the woman who speaks about Brahman')
In the ancient days, women were divided into two classes: the brahma-v<193>din<200>s ç
and the sadyovadh<220>s.
The brahmav<193>din<200>s underwent the sacrament of upanayana, kept ç
the Vedic fires, studied the Vedas under their own father and lived ç
by begging the food, also under the parental roof. They had sam<193>-vartana ç
(valedictory rite at the end of the period of Vedic studies) also. ç
They could then marry and settle down in life.
The name `brahmav<193>din<200>' seems to have been given due to the ç
fact that the girl could recite (vad = to speak or recite) the Vedas ç
(Brahma = Veda). It might also have been applied to those women who ç
were interested in discussing about Brahman, the Absolute, and perform ç
spiritual practices to realize the same. May be due to this reason ç
that the B<216>had<193>ra<207>yaka Upani<218>ad (4.5.1) calls Maitrey<200>, ç
wife of the sage Y<193>j<210>avalkya, as a `brahmav<193>din<200>'.
