@NID = creation. He is the one who liberates the living beings from ç
bondage. Those who are unable to realize this, should go to K<193>·<200> ç
and live there till death. Such votaries of <185>iva who live in K<193>·<200> ç
should never swerve from the path of truth and never miss smearing ç
bhasma on their bodies, wearing rudr<193>k<218>a beads and worshipping ç
Him through the li<209>ga, which is `jyotirli<209>ga' or `li<209>ga ç
of light'. Such worship and meditation on him will confer results ç
like freedom from sins, sorrows and sufferings. He will ultimately ç
attain mukti or liberation. Failure to worship Lord <185>iva at K<193>·<200> ç
thus, will entail sin which has to be expiated through bath, fasting ç
and chanting of the Rudra (asection from the K<216><218><207>a ç
Yajurveda).
Lord <185>iva utters the t<193>rakamantra (O<221> nama··iv<193>ya) ç
into the ears of those dying at K<193>·<200>, thus liberating them ç
from sa<221>s<193>ra or transmigration.
The upani<218>ad concludes with a warning to those that live at K<193>·<200>, ç
but transgress the prescribed mode of living. But  they  too will  be  liberated  after ç
suffering and repentance.
See also <MS>UPANI<186>ADS<D>.
@NT = Bha<219><219>a, Bh<193><219><219>as
See <MS>KUM°RILA-BHA<187><187>A.<D>
@NT = bh<193>va
@N1 = (`emotion')
The words `bh<193>va' and `rasa' are often used in works dealing with ç
dramatics and poetics. A bh<193>va is defined as a permanent or lasting ç
emotion lying deep in the subconscious strata of our minds. When it ç
is aesthetically excited, it produces, in a sympathetic heart, the ç
corresponding sentiment called `rasa.' Bh<193>vas have been listed ç
as nine with the corresponding rasas, also nine, known as `navarasas'. ç
They are:
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(.1808,1.2642,E1), ç
ABOVE(.0972), BELOW(.0972), VGUTTER(.0278), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
, <P9W1>BH°VA, RASA
1., rati (lust), ·<216><209>g<193>ra (erotic)
2., h<193>sa (mirth), h<193>sya (comic)
3., ·oka (sorrow), karu<207><193> (pathetic)
4., krodha (anger), raudra (furious)
5., uts<193>ha (courage), v<200>ra (heroic)
6., bhaya (fear), bhay<193>naka (terrible)
7., jugups<193><|>(aversion), b<200>bhats<%24>a<%0>(disgusting)
8., vismaya<|>(wonder), adbhut<W1%21>a<D%0>(marvellous)
9., nirveda or ·ama  ·<193>nta (peaceful)<R>ç
(detachment,, repose), +
@Z_TBL_END = 
These bh<193>vas considered as permanent, are sometimes called `sth<193>y<200>-bh<193>vas' ç
as against the transitory ones, called `sa<210>c<193>r<200> or vyabhic<193>r<200> ç
bh<193>vas.' The latter may be as many as 33 or 34.
Eight more bh<193>vas or states, involuntary evidences of internal ç
feelings like trembling, shedding tears and so on, are also mentioned ç
sometimes, taking the total number to 50 or 51. (See also <MS>ALA<177>K°RA-<185>°STRA<D> ç
and <MS>RASAS.<D>)
The word `bh<193>va' in Hindu astrology indicates the significance ç
of a house in a horoscope. For instance, the `bh<193>va' of the second ç
house is dhana or wealth, and of the fifth house it is putra or son. ç
So, if theplanets are propitiously situated with reference to the ç
second or the fifth house, he would be wealthy or have sons.
@NT = Bhavabh<220>ti
In the classical Sanskrit literature, one of the playwrights who is ç
often compared  favourably  with  K<193>lid<193>sa† considered to ç
be the greatest†is Bhava-bh<220>ti. His original name was <185>r<200>ka<207><219>ha. ç
`Bhavabh<220>ti' or `Bha<219><219>abhavabh<220>ti' was the name by ç
which he came to be known in the annals of Sanskrit literature. His ç
parents were Jatukar<207>i and N<200>laka<207><219>ha. J<210><193>nanidhi ç
was his teacher. He belonged to the K<193>·yapa gotra or lineage. ç
He must have lived in the early part of the 8th century <MS>A.D.<D>, ç
in Padmapura of Vidarbha-de·a (near the modern Nagpur).
M<193>lat<200>m<193>dhava, Mah<193>v<200>racarita and Uttarar<193>macarita ç
are the three well-known n<193><219>akas or plays authored by him. ç
The first is a love-story whereas the latter two are stories based ç
on the R<193>m<193>ya<207>a. The author has taken quite a bit of ç
freedom in altering the original story to suit his purpose. His style ç
is rather tough though elegant. Books on dramaturgy and poetics often ç
quote from his works as ideal examples for the particular points made ç
out by them.
@NT = Bhavadeva-bha<219><219>a
Hindu scriptures have been classified into two groups: ·ruti and sm<216>ti. ç
The Vedas are the ·ruti, the revealed works. All other works†the works ç
of the sages like Manu, Y<193>j<210>avalkya and Par<193>·ara† which ç
deal with more mundane matters such as <193>c<193>ra (personal conduct) ç
and vyavah<193>ra (social conduct) come under the second group. These ç
works are also called `dharma-·<193>stras.'
The dharma·<193>stra literature has grown abundantly over the centuries, ç
due to the contributions of numerous sages, scholars and religio-social ç
leaders. Consi-dering the needs of the contemporary society these ç
savants added or deleted or substituted or modified the several rules ç
given in the earlier books.
One such author was Bhavadeva-bha<219><219>a, who also had the honorific ç
`B<193>lavalabh<200>-bhuja<209>ga.' He was the son of Govardhana and ç
S<193><209>gok<193> and belonged to the S<193>var<207>a gotra or lineage ç
of the Kauthum<200> school of S<193>maveda. The family belonged ç
to the Siddhalagr<193>ma in R<193>h<193> (in Bengal). Baladevabha<219><219>a ç
was a minister of the king Harivarmadeva. He must have lived around ç
<MS>A. D.<D> 1100.
The works attributed to him are: Vyavah<193>ratilaka,   Sambandhaviveka, ç
Karm<193>nu<218><219>h<193>napaddhati, Pr<193>ya·citta-prakara<207>a ç
and Taut<193>titamatatilaka.
@SPACE1 = 
The first work, on judicial procedure, though quoted by some others, ç
has not been traced till now. The second is a small work based on ç
a part of Manusm<216>ti (3.5) dealing with the prohibition of endogamous ç
marriages. The principal subjects dealt with in the third are: navagraha-homa ç
(oblations into the duly consecrated fire to appease the nine planets), ç
m<193>t<216>p<220>j<193> (worshipping the mother), p<193><207>igraha<207>a ç
(clasping the hand) and other rites connected with marriage as also ç
the other sa<221>sk<193>ras or sacraments like upanayana (initiation ç
into Vedic studies). The fourth deals with the expiations for five ç
grave sins like brahmahaty<193> (killing a br<193>hma<207>a), sur<193>p<193>na ç
(drinking liquor) and so on. The last work deals with the first three ç
adhy<193>yas or chapters of the P<220>rvam<200>m<193><221>s<193>-s<220>tras ç
of Jaimini following in the footsteps of Kum<193>rilabha<219><219>a ç
(8th century <F51320MS>A.D.<F255D>) who was also known as Taut<193>tita.
Bhavadevabha<219><219>a was also an expert in °yurveda (life-science ç
or medicine and surgery) and astravidy<193> (military scien-ces). ç
He is supposed to have composed works on hor<193> or astrology also.
@NT = bh<193>van<193>
@N1 = (`that which is produced')
Though the word is commonly used in the sense of an idea or a thought, ç
it is frequently employed in a technical sense by several sciences.
In the Ny<193>ya-Vai·e<218>ika school, it is defined as a special ç
quality of the mind, a sa<221>sk<193>ra or past impression, born out ç
of experience and giving rise to memory.
In  the  P<220>rvam<200>m<193><221>s<193>  school  it denotes the ç
mental activity of the person who intends to get some work done or ç
do it himself. For instance, when Yaj<210>adatta asks Devadatta, `Bring ç
the cow,' the mental activity of Yaj<210>adatta that induces Devadatta ç
to bring the cow is called `bh<193>van<193>' and is expressed through ç
the words uttered by him. Hence it is called `·<193>bd<200>-bh<193>van<193>' ç
or bh<193>van<193> related to `·abda' or word. The mental activity ç
that arises in devadatta on hearing those words is also a `bh<193>van<193>;' ç
but it is called `<193>rth<200>bh<193>van<193>' since this bh<193>van<193> ç
or mental activity is related to `artha' or utility.
Since the Vedas (the karmak<193><207><195>a part that prescribes rituals) ç
are `apauru<218>eya' or impersonal, the ·<193>bd<200>bh<193>van<193> ç
is inherent in their words of command.
The pur<193><207>as use the word in the sense of a deep-rooted mental ç
impression based on which one sees the world or works in it. For instance ç
sages like Sanaka or Sanandana who were endowed with brahmaj<210><193>na ç
or knowledge of Brahman saw the world with `brahma-bh<193>van<193>,' ç
or that it is Brahman itself. Ordinary gods and human beings endowed ç
with `karma-bh<193>van<193>' saw it as fit for action. Extraordi-nary ç
deities like the Hira<207>yagarbha who had `brahma-karma-bh<193>van<193>,' ç
saw it as Brahman but also fit for discharging the duties (karma = ç
action, duties) allotted to them.
In °yurveda the word `bh<193>van<193>' stands for the process of dissolving ç
some powders of medical qualities in appropriate solvents to prepare ç
the medicine.
@NT = Bhav<193>n<200>
@N1 = (`consort of Bhava or <185>iva')
<185>iva, the last of the Hindu Trinity, is called `Bhava' since the ç
creation comes into being (bhavati asm<193>t) out of Him. P<193>rvat<200>, ç
His consort is therefore known as `Bhav<193>n<200>.'
See <MS>P°RVAT®<D>.
@NT = Bh<193>vanopani<218>ad
This is a minor upani<218>ad belonging to the <185><193>kta school, ç
dealing with <185>akti or the Divine Mother and has been classed under ç
the Atharva<207>aveda. The <185><193>kta school holds that Brahman ç
the Absolute, the ultimate cause and substratum of this universe, ç
is also the <185>akti or the primordial power. It is also called `prak<193>·a' ç
or the Supreme Light. When it deliberates to manifest the creation ç
out of itself†the deliberation itself being called `vimar·a'† it results ç
in a movement or vibration known as `spanda.' The interplay of prak<193>·a ç
and vimar·a increases the spanda gradually, resulting in a graded ç
manifestation of this world of name and form. The rays emerging from ç
the supreme light in the course of various stages of manifestation  array  themselves  in ç
a  form pattern which is now well-known as <185>r<200>cakra. It is ç
a masterplan of the universe, a symbol image and abode of <185>akti ç
or the Divine Mother variously called as Lalit<193> (the Mother of ç
grace), R<193>ja-r<193>je·var<200> (Her most Imperial Majesty) or ç
K<193>me·var<200> (the Mother of love).
The pur<193><207>as describe the <185>r<200>cakra as the central place ç
of the city of the great Goddess. However, this <185>r<200>cakra is ç
not outside, in the external universe, but is within oneself. This ç
upani<218>ad teaches us the `bh<193>van<193>' or the right attitude ç
or mode of meditation to rediscover the <185>r<200>cakra within oneself. ç
Hence it is called Bh<193>vanopani<218>ad.
Since whatever is in the macrocosm, is also in the microcosm, by knowing ç
the latter one can know the former. The bh<193>van<193> or meditation ç
taught here, starts from the outermost cakra or diagram of the <185>r<200>cakra ç
and traverses step by step, the whole gamut of the nine cakras up ç
to the innermost. In the aspirant, the identity is established part ç
by part, limb by limb, from the outermost to the innermost being, ç
the very soul. As a culmination everything is experienced as pure ç
consciousness and one's own body becomes full of bliss. The aspirant ç
thus realizes the light or becomes one with it.
The Upani<218>ad declares that the act of meditation is itself worship; ç
and gives symbolic meaning of terms like arghya (water offered for ç
washing hands) or homa (duly consecrated fire-offerings).
@SPACE = 
@NT = bhavapratyaya
@N1 = (`that which causes <R>ç
transmigration')
@SPACE = 
The Yogas<220>tras of Pata<210>jali (200<F51320MS><|>B.C.<F255D>) describes ç
eight graded steps for controlling the mind. The last step is `sam<193>dhi,' ç
perfect<|>concentration, resulting in a superconscious experience. ç
This sam<193>dhi, again, is twofold: sampraj<210><193>ta andasampraj<210><193>ta. ç
In the former, the object of concentration is fully revealed and known. ç
In the latter the mind settles down into itself without any v<216>ttis ç
or modifications. Hence there will be no j<210><193>na or knowledge ç
of any object in particular.
This latter sam<193>dhi is also twofold: up<193>yapratyaya   and   bhavapratyaya. ç
`Prat-yaya' means k<193>ra<207>a or cause. `Bhava' means sa<221>s<193>ra ç
or transmigratory existence. Since this latter sam<193>dhi does not ç
give mok<218>a orliberation, but causes bhava or transmigration, ç
has been rightly called `bhava-pratyaya.'
Some yogis, endowed with apara-vair<193>gya or inferior spirit of ç
renunciation, choose such objects as the pa<210>ca-bh<220>tas (the ç
five elements such as earth and water), the indriyas (the sense-organs) ç
or aha<209>k<193>ra (the ego) and so on for their objects of meditation. ç
When they attain asam-praj<210><193>ta sam<193>dhi through these, ç
they attain a state which is similar to kaivalya or liberation. However, ç
since they lack viveka-khy<193>ti or the direct experience that the ç
<193>tman (the Self) is separate from prak<216>ti (nature), they return ç
to transmigratory existence after some time.
See also <MS>ASAMPRAJ<178>ATA-SAM°DHI, SAM°DHI, SAMPRAJ<178>°TA-SAM°DHI<D> ç
and <MS>UP°YA-PRATYAYA.
@SPACE = 
@NT = bh<193>var<220>pa
@N1 = (`of the form of existence,' `positive')
@SPACE = 
According to the Advaita Ved<193>nta philosophy our real nature is ç
the <193>tmanor the Self which is pure consciousness. Our ignorance ç
of our real nature†technically called `avidy<193>' or `aj<210><193>na'†has ç
led to our wrong identification with the body-mind complex resulting ç
in sa<221>s<193>ra or transmigratory existence. Hence, to attain mok<218>a ç
or liberation, we have to get rid of this avidy<193>or aj<210><193>na ç
through vidy<193> or j<210><193>na (knowledge).
In this connection, philosophers of the Advaita school have widely ç
discussed the nature of this avidy<193> or aj<210><193>na and have ç
come to the conclusion that it is `bh<193>var<220>pa' or positive ç
and not `abh<193>va-r<220>pa' or negative since it is felt or experienced. ç
For instance, when we say, `I do not know anything,' `I am an ignorant ç
person' we actually feel or experience that ignorance. However, its ç
reality has not been given the status of `sat' (`that which exists') ç
since it can be destroyed by knowledge.
See also <MS>AJ<178>°NA<D>.
@SPACE = 
@NT = Bhavat<193>ri<207><200>
@N1 = (`One who causes the [j<200>va] to cross [the ocean of] sa<221>s<193>ra')
@SPACE = 
Worship of God as the <185>akti (the Divine Power or Mother) is quite ç
ancient in the Hindu religious tradition. One of the more well-known ç
aspects of this <185>akti, especially the fierce ones, is K<193>l<200>. ç
Bhava-t<193>r<200><207><200>, which literally means `one who helps ç
the j<200>va or the individual soul to cross over sa<221>s<193>ra ç
or transmigratory existence,' is one of the names by which K<193>l<200> ç
is known in the Bengali tradition of <185>akti worship. The deity ç
at the famous temple of K<193>l<200> in Dak<218>i<207>e·var (Calcutta) ç
has been well-known as Bhavat<193>ri<207>i.
See <MS>K°L®<D> for details.
@NT = Bhavi<218>ya-pur<193><207>a
@N1-1 = (`pur<193><207>a of the future')
Pur<193><207>as are the mythological lore of Hinduism and rank among ç
its secondary scriptures. Hindu tradition lists 18 major pur<193><207>as ç
and another 18 minor pur<193><207>as, all ascribed to the well-known ç
sage Veda-vy<193>sa.
@EMERGENCY = The Bhavi<218>ya-pur<193><207>a has been classed among ç
the major pur<193><207>as and hence sometimes called the Bhavi<218>ya-mah<193>pur<193><207>a ç
also. According to one printedversion, it is divided into four books: ç
Brahmaparva, Madhyamaparva, Pratisargaparvaand Uttaraparva. In ç
all, there are 585 chapters and 26,000 ·lokas.The last book is sometimes ç
treated as an independent pur<193><207>a entitled Bhavi<218>yottara-pur<193><207>a. ç
Minus this book, the number of verses comes to 14,000 or 14,500, a ç
number generally and widely accepted by the scholars based on the ç
information given in other pur<193><207>as like the Matsya and the ç
Agni.
This pur<193><207>a belongs to the period <F51320P10MSC1>A.D.<W1> <F255P255DC255>600-1000. ç
Its last book, with its many references to kings including the Muslim ç
invaders, known to history, has been considered as having many interpolations. ç
The first book Br<193>hmaparva is undoubtedly the oldest part.
@EMERGENCY = As per another version, the pur<193><207>a consists of ç
five books: Br<193>hmaparva, Vai<218><207>avaparva, <185>aivaparva, ç
Sauraparva and Pratisargaparva. The total number of chapters is ç
605, the number of verses being 14,000.
The whole pur<193><207>a is a miscellany dealingwithabewilderingvarietyof ç
subjects. The up<193>san<193> (worship) of S<220>rya, the Sun-god, ç
has been given a prominent place. Details concerning the construction ç
of temples, making and consecration of images, varieties of vratas ç
or religious observances motivated by desires, sins and their expiations, ç
d<193>na or giving gifts† these ar some of the other subjects dealt ç
with in the work.
The prefix `bhavi<218>ya' (`future') seems to have been given to it ç
on the assumption that though an ancient work composed by the hoary ç
sage Vedavy<193>sa, it predicts many events of the future.
See also <MS>PUR°ØAS<D>.
@NT = Bh<193>vayoga
See under <MS>YOGA<D>.
@NT = bhed<193>bheda-v<193>da
@N1 = (`the doctrine of<R>ç
difference and non-difference')
One of the important concepts discussed by the <218>a<195>dar·anas ç
or the six sys- tems of Indian Philosophy is that of bheda (difference) ç
and abheda (non-difference). Once a basic doctrine is evolved, it ç
can then be applied to the relationship between the j<200>va (individual ç
soul) and Param<193>tman or Brahman (the Supreme Soul).
Some of the schools of Ved<193>nta like those of Bh<193>skara (<F51320P10MSC1>A.D.<F255P255DC255> ç
900) and Nimb<193>rka (12th century <F51320P10MSC1>A.D.<F255P255DC255>) propounded ç
this doct-rine of bhed<193>bheda (bhed<193>bheda-v<193>da) between ç
the j<200>va and Brahman. There is both difference and identity between ç
them, identity as pure consciousness and difference in powers and ç
functions. Such bhed<193>-bheda is not inconceivable as can be seen ç
in the relationship between gu<207>a (quality) and gu<207>in (the ç
substance possessing the quality) or between j<193>ti (a genus or ç
class) and vyakti (an individual belonging to that class).<F51320P10W1C1>
@NID = <+><+><+> See<|>also<|><MS>ACINTYA-BHED°BHEDA SCHOOL.<D>
@NT = bher<200>
@N1 = (`that which produces fear,'<R>ç
`a kettledrum')
Drums and kettledrums, of various types and sizes, have been in use ç
in India since the ancient times. They have been associated both with ç
war and with peace.
A bher<200> or kettledrum is an essential part of the Hindu temple ç
equipment. All the important festivals of the temple including the ç
brahmotsava, start with bher<200>-t<193><195>ana or beating the kettledrum. ç
It is an invitation even to the gods in heaven to come down and attend ç
the festival. The sound of the bher<200> is said to destroy the sins ç
of all those that hear it. Even the animal from whose hide the instrument ç
has been made, is said to attain heaven.
@NT = bhik<218><193>
@N1 = (`begging')
Though begging has been looked down upon in the modern times, in ancient ç
and medieval India, it was generally given an honourable place.
Bhik<218><193> or begging as described in the sm<216>tis and dharma·<193>tras ç
falls into two categories: that which is prescribed as a religious ç
duty and that which is allowed as a means of sustenance.
A brahmac<193>rin (initiated Vedic student) had to obtain alms by ç
bhik<218><193> since it was considered as very pure. Though on the ç
day of his upanayana (investiture with the sacred thread, yaj<210>opav<200>ta, ç
making initiation into the Vedic studies) he has to beg the first ç
morsel of food from his own mother, he could, later on, get it from ç
the ladies (or men) from several houses. The food got thus had to ç
be kept before his teacher and the boy could consume only that much ç
as was allotted by him. Excess food was not to be wasted but given ç
to needy persons, or even left under a tree for animals.
Though alms could be accepted from persons of all castes (except the ç
ca<207><195><193>las or outcastes and patitas or the morally depraved) ç
in the earlier years, restrictions regarding caste were gradually ç
tightened, so much so, that a brahmac<193>rin could not, often, get ç
enough food to eat. On such occasions he was permitted to beg from ç
the members of his own family or even from the teacher himself.
It was obligatory for the householders to give food to the brahmac<193>rins ç
as also monks according to their ability and any refusal would result ç
in the destruction of their religious merit.
A sa<221>ny<193>sin or a monk was expected to be a `parivr<193>jaka' ç
or an itinerant, and hence, bhik<218><193> was the only means of his ç
sustenance. However, he was allowed to beg alms only once a day (in ç
day-time) and that too, not from more than seven houses, without selecting ç
them before-hand. Such bhik<218><193> was called `m<193>dhukar<200>' ç
(collecting food like bees collecting honey; madhu = honey) and was ç
considered very pure. As regards the caste of the persons from whom ç
alms could be accepted, opinion is divided in the dharma·<193>stras.
@SPACE1 = 
Begging was allowed to others, but under certain restrictions. Begging ç
(whether for food or for wealth) was permitted forthe sake of the ç
teacher, for one's first marriage, for a sacrifice, to support one's ç
parents or as a pr<193>ya·citta (expiation). What was obtained from ç
such begging had to be utilized for that parti-cular purpose only.
@NT = Bhik<218>a<219>ana-m<220>rti
@N1 = (`image of [·iva] in the begging posture')
<185>iva, the last deity of the Hindu Trinity, is invariably worshipped ç
as theli<209>ga. (See <MS>LI<177>GA<D>.) However, several anthropomorphic ç
forms too have been attributed to him. One such form belonging to ç
his ugra or raudra (terrific) aspect is the Bhik<218><193><219>ana-m<220>rti ç
or the `begging-form'.
The story goes that he cut off the fifth head of Brahm<193>, the Creator, ç
with his fingernail, since the latter was irreve-rent. The severed ç
head or skull, however, stuck to his finger; and the sin of brahma- ç
haty<193> (See <MS>BRAHMAHATY°<D>.) incurred thus had to be expiated. ç
So, he had to roam about the earth for 12 years, begging his food ç
in the skull-cup. It is this form that is known as the `Bhik<218><193><219>ana-m<220>rti.' ç
As soon as he entered V<193>r<193><207>as<200> (K<193>·<200> or Banaras) ç
he was freed from this sin.
@SPACE1 = 
In iconographical works the Bhik<218><193>-<219>ana-m<220>rti<|> is ç
<|>shown<|> as<|> a <|>naked<|> person
