@NT = barhis
@N1 = (`that which is plucked up;'<R>ç
`sacrificial grass')
Vedic sacrifices involve a lot of details to be looked into while ç
organizing their performance. One such is the spreading of the ku·a ç
grass (Poa cynosuroides) in the sacrificial shed, and more so on ç
the vedi (sacrificial platform) upon which the sacrificial vessels ç
and oblations are kept. The seat of the performers and the place where ç
the gods invited to receive the offerings are expected to be seated, ç
are also situated here. This place thus covered with the ku·a grass, ç
is called `barhis'.
See also <MS>DARBHA<D> and <MS>KU<185>A<D>.
@NT = barhi<218>ads
@N1 = (`those seated on the barhis or sacrificial grass')
Barhi<218>ads are a class of pit<216>s or manes born of the sage Atri. ç
They are described as the manes of demons like the daityas and d<193>navas ç
as also demigods like yak<218>as, the gandharvas and other similar ç
beings.
Sometimes they are described as one of the two classes of beings created ç
by Brahm<193>, the Creator, the other class being the agni<218>v<193>ttas.
They are members of the council of Yama, the Lord of death and perform ç
m<193>ntric rites for the dead.
@NT = Basave·vara
@N1 = (death†<F51320P10MSC1>A.<|>D.<W1> 1168)
V<200>ra·aivism, one of the important aspects of <185>aivism, more ç
popular in Karnataka, owes its development and popularity mainly to ç
Basave·vara, also called Basava<207><207>a or Basava, who flourished ç
in the 12th century. Though attempts have been made to project him ç
as the founder of the faith, others in the tradition have not accepted ç
it, since quite a few teachers of the same school have preceded him.
The socio-political condition of the people of Karnataka during the ç
latter part of the 11th and early part of the 12th centuries, was ç
ripe for the advent of a rebel-reformer and Basave·vara fitted into ç
it admirably. The br<193>hma<207>as with the strength of their learning ç
in the traditional lore and secular sciences as also their cultural ç
roots, wielded enormous power both in the political field and in the ç
social set-up. The caste system had an iron grip over the society ç
and persons of lower castes enjoyed few privileges but several disabilities. ç
Their colossal ignorance and arrant superstition had created many ç
a deified spirit, the fear of which had led to several ridiculous ç
practices.
Women in general were always treated as inferior to men. Jainism, ç
as a result of constant conflict with the various cults of Hinduism, ç
had lost its popular appeal.
@SPACE1 = 
Basave·vara was born as the son of a ·aiva br<193>hma<207>a couple†M<193>dir<193>ja ç
and M<193>d<193>mb<193>, at B<193>gev<193><195>i in the Bijapur district ç
of modern Karnataka. Since he was born after much austerity and prayers ç
to V<216><218>abha or Nandin<193>tha (the bullmount of <185>iva) he ç
was christened `Basava' (=v<216><218>abha). Though brought up in ç
the Vedic br<193>hmanical tradition he could not reconcile himself ç
to many of the customs that obtained during his times like immolating ç
animals in Vedic sacrifices. Most unwillingly and under protest, he ç
underwent the upanayana ceremony (the ceremony of investiture with ç
the sacred thread called yaj<210>opav<200>ta). He was given a good ç
education which he could assimilate well, due to the unusual powers ç
of comprehension. However, he could not bring himself to accept the ç
various rituals of Vedic origin. Nor could he tolerate the injustice ç
being heaped upon the lower caste groups by the upper classes. This ç
gradually led to a lot of bad blood between him and his parents as ç
also the elders in the contem-porary society. Meanwhile his parents ç
passed away leaving him an orphan. He thought he was now free to come ç
out of the clutches of br<193>hminical orthodoxy, which he did, by ç
tearing off the sacred thread that symbolized it. He then went to ç
Kappa<195>i Sa<209>gama, a holy place situated at the confluence of ç
the rivers Malaprabh<193> and K<216><218><207><193>. He settled down ç
near the temple of Sa<209>game·vara and started his spiritual quest ç
through the worship of the <185>ivali<209>ga there. A holy man ®·<193>nya-guru ç
by name, is said to have given him shelter there.
It is not known how long Basave·vara stayed at Kappa<195>i Sa<209>gama. ç
Once <185>iva appeared to him in a dream and commanded him to go to ç
Ma<209>ga<202>ive<195>a and meet the King Bijja<202>a. He did so, ç
though most unwillingly.
Bijja<202>a of the Kalacuri race, who had been a governor of the C<193>lukyas ç
had, gradually grown in power and had usurpedtheir kingdom during ç
the period <F51320P10MSC1>A.D.<W1> 1157-62.
Being impressed by the appearance and personal magnetism of Basave·vara, ç
Bijja<202>a appointed him as an employee in his treasury under Siddha ç
Da<207><195><193>dhipa. After the latter's demise, Basave·vara took ç
over as the chief. Soon after this, he got married to Ga<209>g<193>dev<200> ç
and N<200>lalocan<193>, daughters of two high-ranking officers.
Neither wealth nor power, nor even happy family could deflect Basave·vara ç
from his chosen path: worship of <185>iva and serving the ja<209>gamas ç
and ·ara<207>as (V<200>ra·aiva ascetics and devotees). His hospitality ç
and generosity soon attracted all and sundry to his house in the guise ç
of devotees of <185>iva. Though sometimes, he hadto suffer their ç
quixotic behaviour, he would do so with infinite patience and cheerfulness.
Sometime later, Basave·vara shifted to Kaly<193><207>a, the capital ç
of Bijja<202>a. Though he  worked  honestly  and  efficiently, rumours ç
floated by persons inimical to him†like misuse of state funds for ç
entertaining hispersonal guests†gradually soured his relationship ç
with Bijja<202>a. Added to it was the attempt he made to bring about ç
a social revolution that would transcend caste barriers, accord an ç
equal status to women and stress the importance of honest physical ç
labour as an integral part of religious or spiritual life. This he ç
did by founding an institution called `<185>iv<193>nubhava-ma<207><219>apa' ç
(`religious house of experience'). This was, perhaps, the birth-place ç
or cradle of V<200>ra·aivism as known to us today. It was a spiritual ç
as well as a social institution organized by Basave·vara and presided ç
over by Allama Prabhu, the greatest saint of thetimes. It acted as ç
a nucleus round which gathered persons of all ranks and professions ç
including women, to take part in the discussions that ranged from ç
the most sublime spiritual truths to social problems, norms and conduct.
The  social  revolution  that  was initiated by this movement developed ç
from a ripple to gigantic waves resulting ultimately in the marriage ç
of a br<193>hma<207>a girl to a Harijan (untouchable) boy since both ç
the families had embraced the V<200>ra·aiva cult. This naturally led ç
to a great commotion and social unrest resulting first in the plucking ç
out of the eyes of the fathers of the couple by Bijja<202>a and then ç
in the assassination of Bijja<202>a himself at the hands of Basave·vara's ç
followers as a reaction. In the melee that resulted, Basave·vara escaped ç
to Kappa<195>i Sa<209>gama; and later, he voluntarily drowned himself ç
at the confluence of the rivers there.
Basave·vara, though a social revolutionary, was basically a spiritual ç
aspirant who rose to saintly heights. His devotion to his Lord, `K<220><195>ala ç
Sa<209>gamadeva (<185>iva),' was as intense as his keen intellect. ç
Heused everything he had†wealth and possessions, power, good name†in ç
the service of his Lord and His devotees. Hewas a byword for magnanimity ç
and generosity.
He has left behind him a large number of his sayings as `vacanas.' ç
The vacana isa class of Kannada literature, midway between prose ç
and poetry, and couched in the common language of the masses. The ç
topics dealt with range from the deepest philosophical reflections, ç
to simple ethics or problems and parodies of the day-to-day life.
@SPACE1 = 
His philosophy may be summarized briefly thus: Have a great ideal ç
in life, to live by. Try hard, try sincerely, to stick to that ideal ç
or to reach it. Be fearless and face all the problems that may have ç
to be encountered while trying to live that life. Do not neglect the ç
life here and now; because, if it is lived well `here,' you can live ç
well `there' also. Do some constructive physical labour to earn your ç
livelihood or to deserve the food that you eat. Be contented with ç
what you have and try to share the good things of your life with others. ç
Since spiritual evolution is more important than the status in society ç
brought about by caste, the latter has to be overlooked in favour ç
of the former.
There is no doubt that Basave·vara was one of the brightest luminaries ç
thatadorned South India, especially the Karnataka region, in the ç
12th century.
See also <MS>LI<177>G°YATA CULT<D> and <MS>V®RA<185>AIVISM.<D>
@NT = basti
@N1 = ( `[cleansing the] pelvic region')
The aim of human life is to get spiri- tual illumination. This can ç
be achieved only by strenuous s<193>dhan<193> or spiritual discipline. ç
The body is an invaluable instrument in this process of s<193>dhan<193>. ç
This body may wear out before time due to impurities in the internal ç
systems. The science of Ha<219>hayoga has devised several simple methods ç
for correcting the internal disorders through cleansing processes. ç
They are six in number and are called `<218>a<219>karmas' (<218>at ç
= six). The second of these six is `basti.'
Basti is the process of cleansing the intestines. It is of two types: ç
jalabasti and sthala or ·u<218>ka-basti. The first is practised in ç
water and the second on land.
Jalabasti is yogic enema, practised in navel deep water, by sitting ç
in utka<219><193>sana and alternately contracting and expanding the ç
anus muscle (the sphincter).
When the same is practised on land, it becomes sthalabasti (sthala ç
= land, ground) or ·u<218>ka-basti (·u<218>ka = dry). However, pa·cimott<193>n<193>sana ç
is recommended for this basti.
Gastric troubles, wind troubles, constipation, cough and bile complaints ç
are said to be cured by these two bastis.
It is advisable to practise them under the care and guidance of an ç
expert.
See also <MS>°SANA, PA<185>CIMOTT°NA °SANA, <186>A<187>KARMAS<D> and ç
<MS>UTKA<187>°SANA<D>.
@NT = Baudh<193>yana
@N1-1 = (`descendant of Bodh<193>yana')
One of the ancient but well-known names met with in the Ved<193><209>ga ç
literature, is that of Baudh<193>y<193>na. Baudh<193>yana is a descendant ç
of Bodh<193>yana who himself is a son of Bodha. However, nothing is ç
known of this Bodha.
The two names Bodh<193>yana and Baudh<193>yana have sometimes been ç
usedas if they are synonymous. A K<193><207>va Bodh<193>-yana, mentioned ç
in the Baudh<193>yana- dharmas<220>tras, is perhaps a more ancient ç
teacher, and, may be a predecessor.
Baudh<193>yana probably existed somewhere during the period 600-300 ç
<MS>B.C.<D>, and belonged to South India. This surmise is based on ç
the fact that S<193>ya<207>a (14th cent. <F51320P10MSC1>A.D.<W1>) <F255P255DC255>the ç
great commentator on the Vedas, was a descendant of Baudh<193>yana. ç
Practically nothing is known about him.
Baudh<193>yana is one of the very few authors whose work is available ç
on all the four branches of Kalpa, the last of the six Ved<193><209>gas. ç
They are: ·rautas<220>tras, g<216>hyas<220>tras, dharmas<220>tras ç
and ·ulba-s<220>tras.
The extant work of Baudh<193>yana consists of six sections (each called ç
`s<220>tra') as follows: the <185>rautas<220>tras, the Dvaidha-s<220>tras, ç
the Karm<193>ntas<220>tras, the G<216>hya-s<220>tras, the Dharmas<220>tras ç
and the <185>ulba-s<220>tras.
The <185>rautas<220>tras, considered as very ancient, has 30 pra·nas ç
or sections, each divided into several adhy<193>yas or chapters. It ç
is in prose and the sentences are rather long. The whole work deals ç
with the details of Vedic sacrifices of various types like Agnihotra, ç
Dar·ap<220>r<207>am<193>sa, C<193>turm<193>sya, V<193>japeya, A·vamedha ç
and so on.
The Dvaidhas<220>tras which deals with vaikalpika vidhis or choices ç
given with regard to any particular rule and the Karm<193>ntas<220>tras ç
which deals with the rest of the injunctions not given earlier, form ç
a part of the <185>rautas<220>tras.
@SPACE1 = 
The last pra·na of the <185>rautas<220>tras is the <185>ulbas<220>tras. ç
It deals with the geometrical and mechanical details of constructing ç
the sacrificial vedi or altar.
The G<216>hyas<220>tras is in 4 pra·nas or sections, comprising ç
47 adhy<193>yas or chapters. The subjects dealt with include the sixteen ç
sa<221>sk<193>ras or sacraments, like j<193>takarma (rites to be performed ç
at birth),n<193>makara<207>a (naming ceremony), upanayana (investiture ç
with yaj<210>opav<200>ta or the sacred thread to mark the beginning ç
of Vedic studies), viv<193>ha (marriage) and so on. Other topics dealt ç
with in the work are: certain rites like Vai·vadevahoma and pr<193>ya·cittas ç
or expiatory rites for transgressing rules while performing the Vedic ç
rites described earlier.
In some printed books, three more works are added as appendices. They ç
are G<216>hyaparibh<193><218><193>s<220>tram, G<216>hya·e<218>as<220>tram ç
and Pit<216>medhas<220>tram. Some scholars however, consider these ç
also as an integral part of the G<216>hyas<220>tras. The first work ç
in two pra·nas and 23 adhy<193>yas defines the various terms used ç
in Vedic sacrifices. The second in 5 pra·nas and 97 adhy<193>yas, ç
fills up the gap as it were, in the performance of the Vedic rites ç
described earlier, by giving the details of the rituals left out. ç
The third or the last, comprising 3 pra·nas and 48 adhy<193>yas deals ç
almost exclusively with the aurdhvadehika rites (rites to be performed ç
after death).
The Dharmas<220>tras, also considered as an ancient work, is in ç
4 pra·nas or kha<207><195>as (sections), the last pra·na being considered ç
as a later interpolation by some scholars. The topics dealt with are: ç
sources of dharma, upanayana and duties of a brahmac<193>rin (Vedic ç
student), duties of a sn<193>taka (one who has completed the study ç
of the Vedas) and eight forms of marriage, pr<193>ya·cittas or expiatory ç
rites for sins, the sandhy<193> ritual, the pa<210>cayaj<210>as or ç
the five daily sacrifices, ·r<193>ddha cere- monies connected with ç
death and post-death rituals, sa<221>ny<193>sa or rites to be performed ç
to become a monk, means of securing siddhis or supernatural powers ç
and so on.
@NT = B<193>uls
@N1 = (`the crazy ones')
The B<193>uls of rural Bengal who are found even today, form one of ç
the obscure religious cults of India. They are wandering minstrels ç
comprising mostly mendicants.
The word `b<193>ul,' of uncertain origin, may have been derived from ç
either of the Sanskrit words: V<193>tula (affected by wind-disease, ç
i.e., mad or crazy) or vy<193>kula (impatiently eager). Both these ç
derivations are consistent with the modern sense of the word: `inspired ç
people with an ecstatic eagerness for a spiritual life, leading to ç
ultimate union with the eternal Beloved.'
Historically, this sect might have been derived from the N<193>tha ç
Cult. However, the influence of Vai<218><207>avism and S<220>fism ç
can easily be recognized.
The B<193>uls are most unconventional in their customs and manners, ç
habits and practices. They pride themselves on calling their ways ç
as `ul<219>a' or `the reverse'. That is why they care not for formal ç
observances of any religious practice.
The literature of the B<193>uls is entirely in their songs and poems ç
(in Bengali) couched in mystic terms and riddles. Whatever philosophy ç
can be gleaned from these can be stated briefly as follows:
The human body is the microcosm of the universe, the temple of the ç
Dear one. This Beloved, also called `maner m<193>nu<218>' (`the Man ç
of the Heart') is the Lord of the universe living in our heart. Hence, ç
any search for Him outside is fruitless. This Divine Personality residing ç
in us is our essential nature, love is the means of achieving union ç
with Him and the lover is the human personality. In the highest union, ç
all limitations are transcended, all differences between humanity ç
and divinity are annihilated.
Madan, Bi·a Bh<220>mim<193>li, ®·<193>n Yugi, K<216><218><207>ak<193>nta ç
P<193><219>hak and L<193>lan Fak<200>r are some of the celebrated ç
composers of the b<193>ul songs.
See also <MS>N°THA CULT<D> and <MS>SAHAJIY°S.<D>
@NT = bera
@N1 = (`icon')
Worship of images is an integral part of Hindu religion. Arc<193> ç
or image is oneof the several forms of manifestation of the Divine. ç
Another term which is commonly used in the <193>gamas for images, ç
but in a more technical sense, is `bera'. This word, of uncertain ç
origin, is generally employed to indicate images made to conform to ç
the prescriptions of m<220>rti·ilpa·<193>stra or icono-graphy and ç
used in worship.
A bera should be either `citra' (solid figure) or `citr<193>rdha' ç
(relief figure). Painted or engraved figures are not classed under ç
`bera'.
The height and the width of the bera are taken as standards for determining ç
other measurements like those of the p<200><219>ha or pedestal, of ç
the garbhag<216>ha or the cella, or, the vim<193>na (the tower over ç
the main shrine). (See <MS>A<177>GULA <D>and <MS>T°LAM°NA.<D>)
Beras can be of two general types: acala or immovable and cala or ç
movable and portable. The acalabera, also called `dhruvabera' (the ç
constant icon) or `m<220>labera' (the original icon), is the original ç
image, of stone, permanently fixed in the sanctuary. The calaberas ç
can be as many as four and are made of metal. Along with the original ç
(dhruvabera) they are collectively called `Pa<210>caberas' (five icons).
@SPACE1 = 
The  first  in  the  series  is  the `kautukabera,' also called `kriy<193>bera' ç
and `karm<193>rc<193>', kept in the central part of the altar in the ç
shrine. Life is infused into it from the main image and all the items ç
of worship of the main image are also offered to this image. The second ç
is the `snapanabera,' an image that receives the daily ceremonial ç
bath. This image is sometimes designated as `t<200>rthasn<193>n<193>rc<193>,' ç
also. The next is the `utsavabera' or `utsav<193>rc<193>' or `rathabera', ç
which is meant to be taken out in procession on festival days. The ç
fourth is the `balibera' or `balyarc<193>', an image that receives ç
the food offerings meant to be distributed among the attendant and ç
minor deities. It is taken out in a procession at the time of balihara<207>a ç
or distribution of food offerings to these deities. Some texts add ç
another, `·ayan<193>rc<193>', the image which is put to rest during ç
night. These divisions of beras are found mostly in the Vai<218><207>av<193>gamas. ç
The <185>aiv<193>gamas sometimes add a `n<216>ttabera,' a Na<219>ar<193>ja ç
icon employed on certain occasions like aridrotsava.
See also <MS>ARC°<D> and <MS>IMAGE WORSHIP<D>.
@NT = Besnagar Inscription
Inscription on stone pillars and walls as also on metal plates have ç
always been a source of valuable material for reconstructing ancient ç
or medieval Indian history. One such, belonging to a fairly early ç
period (2nd century <MS>B.C.<D>) is the Besnagar inscription, discovered ç
on a `garu<195>adhvaja' (votive pillar with the sculpture of Garu<195>a, ç
the mythical bird-mount of Vi<218><207>u) near Bhilsa in Madhya Pradesh.
Besnagar was the capital of the <185>u<209>ga dynasty which ruled ç
during the period 187-75 <MS>B.C.<D>
The stone pillar has been dedicated toV<193>sudeva (K<216><218><207>a), ç
called `deva-deva' or `God of gods', by Heliodoros who was a Yavana ç
or a Greek. In the inscription on it, he calls himself as a `paramabh<193>gavata' ç
(the best of the bh<193>gavatas or devotees of Vi<218><207>u). He ç
was the son of one Diya and a native of Tak<218>a·il<193>. He had ç
been deputed as the ambassador by the Greek King Antialcidas to the ç
Indian King Bhaga-bhadra K<193>·<200>putra, probably the same as the ç
fifth <185>u<209>ga King Bhadraka.
This inscription proves two things, viz., that the K<216><218><207>a-V<193>sudeva ç
cult or the Bh<193>gavata religion had already become quite popular ç
and that even Greeks of high descent had gladly accepted it. Incidentally, ç
this also helps us to prove the historicity of K<216><218><207>a.
@NT = Bhadr<193>calam
@N1 = (`mountain of Bhadra')
Bhadr<193>calam<192>also known as Bhadra-giri†is considered as one ç
of the 25 important places of pilgrimage associated with <185>r<200> ç
R<193>ma. It is situated in the Khammam district of Andhra Pradesh. ç
It is 50 kms. (31 miles) from Kothagudem, the place famous for the ç
coal mines of Singareni.
The sanctum of the temple has all the three images, of <185>r<200> ç
R<193>ma, S<200>t<193> and Lak<218>ma<207>a. According to the sthalapur<193><207>a ç
(local mythological accounts), the three appeared before the sage ç
Bhadra (personification of the mountain Bhadragiri, consi-dered as ç
the son of Meruparvata or mountain Meru and Menak<193>) and transformed ç
themselves into stone images at his request, to stay there permanently. ç
An anthill grew over the images and they were hidden from the human ç
gaze for centuries.
The presence there of the images was revealed accidentally or by divine ç
dispensation to one Pokala Dammakka, a childless widow who had adopted ç
a boy named R<193>ma. She retrieved the images and preserved them, ç
offering a simple worship. One day in a dream she saw the sage Bhadra ç
who instructed her to keep up her devoted worship until such a time ç
whena great devotee of <185>r<200> R<193>ma will come and construct ç
a temple for the images. Later, when Ka<210>carla Gopanna (<MS>A.<|>D.<D> ç
1630-1687) who was the tax-collector of the Muslim ruler  Tanisha  visited  the  place,  she ç
revealed her dream to him. Since he was a great devotee of <185>r<200> ç
R<193>ma, he got the temple built. Though he was punished by the ruler ç
for the `misuse' of State funds, <185>r<200> R<193>ma came to his ç
rescue in a miraculous way.
Gopanna became a famous composer-musician, now well-known as Bhadr<193>cala ç
R<193>mad<193>sa.
The temple was built in the 17th century and was thoroughly renovated ç
during the 1960's.
<185>r<200> R<193>ma-Navam<200> and Vaiku<207><219>ha Ek<193>da·<200> ç
are the biggest festivals conducted in this temple.
Temples of Narasi<221>ha and Govinda-r<193>ja as also the R<193>mad<193>sa ç
Dhy<193>namandira are places of importance for the pilgrims.
About 36 kms. (20 miles) away is the Par<207>a·<193>l<193> where <185>r<200> ç
R<193>ma and S<200>ta stayed, before S<200>t<193> was abducted by ç
R<193>va<207>a, the demon-king. A rivulet, <185><200>t<193>v<193>ga ç
by name, flows nearby.
Dummagu<195>em (16 kms. or 10 miles from Bhadr<193>calam) where <185>r<200> ç
R<193>ma is said to have killed Khara and his army of 14,000 demons, ç
as also Gu<207><195>ala (5 kms. or 3 miles down the river, from Bhadr<193>-calam) ç
containing hot springs are other places of interest.
@NT = Bhadra-k<193>l<200>
@N1 = (`the Auspicious K<193>l<200>')
Worship of God as Mother has been in vogue in India since the most ç
ancient times. Out of the several aspects of the Mother Goddess that ç
are still worshipped, an overwhelming majority are forms of P<193>rvat<200> ç
or <185>akti, the consort of <185>iva. Bhadrak<193>l<200> is one of ç
them.
Since `bhadra' means auspiciousness, Bhadrak<193>l<200> is a pleasing ç
deity with a charming appearance. She is depicted as seated on a chariot ç
drawn by four lions. She has eighteen hands in which she carries things ç
such as rosary, trident, sword, shield, bow and arrow, conch, discus, ç
sacrificial ladles, holy water-pot, spear and so on. One of the hands ç
is raised in the gesture of benediction.
The girl-child of Ya·od<193> which was brought to the prison by Vasudeva, ç
the father of K<216><218><207>a, after exchanging it with baby K<216><218><207>a, ç
and which Ka<221>sa tried to kill, was also Bhadrak<193>l<200>. She ç
is an aspect of Durg<193>.
The K<193>lik<193>pur<193><207>a (ch. 59) however describes Bhadrak<193>l<200> ç
as an aspect of Durg<193>, and as an exceedingly terrible deity. The ç
demon Mahi<218><193>sura saw her in dream and was stricken with mortal ç
fear. He worshipped her and got the boon to be killed directly by ç
her. She also granted an additional boon that he too would be worshipped ç
in future along with her.
According to another account Bhadra-k<193>l<200> was the female companion ç
of V<200>ra-bhadra, who had been created by <185>iva out of a hair ç
from his matted locks to destroy Dak<218>a's sacrifice.
@SPACE = 
@NT = bhadrap<200><219>ha 
@N1 = (`the auspicious pedestal')
@SPACE = 
A p<200><219>ha is a pedestal for an icon. Out of the four varieties ç
mentioned in iconographical works, bhadrap<200><219>ha is one, the ç
other three being padmap<200><219>ha, vedik<193> and parima<207><195>ala.
If the height of the pedestal is sixteen units accommodated in eight ç
parts, then,it is called `bhadrap<200><219>ha'. The parts reckoned ç
from the bottom to the top as also their measurements are as follows:
@Z_TBL_BEG = COLUMNS(4), DIMENSION(IN), COLWIDTHS(.3350,.4167,.9167,E1), ç
ABOVE(.0278), BELOW(.0278), VGUTTER(.0139), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE TEXT
, (1), up<193>na, 1 unit
, (2), jagat<200>, 4 units
, (3), kumuda, 3 units
, (4), kampa, 1 unit
, (5), ka<207><219>ha, 3 units
, (6), kampa, 1 unit
, (7), pa<219><219>ik<193>, 2 units
, (8), gh<216>tav<193>ri, 1 unit
@Z_TBL_END = 
See also <MS>P®<187>HA<D>.
@NT = bhadr<193>sana
@N1 = (`the auspicious posture,' `the auspicious seat')
°sanas or yog<193>sanas are various postures of the body aimed at ç
freeing it from diseases and improving its health, energy and stamina. ç
Out of the 32 <193>sanas most commonly practised, bhadr<193>sana is ç
one. In this posture, one has to sit on one's knees, allowing the ç
calf-muscles touch the thighs. Hands should be taken to the back and ç
catch hold of the toes with the fingers. This should be followed by ç
J<193>landhara-bandha, wherein the gaze is fixed on the tip on the ç
nose.
In another variety, the hands have to cross each other. The right ç
hand should hold the left toe and the left, the righttoe.
This <193>sana is said to cure the stiffness of bones and rigidity ç
of ligaments.
In iconographical works, it represents a golden throne with cushions.
See also <MS>J°LANDHARA-BANDHA<D> and <MS>YOG°SANAS<D>.
@NT = Bhaga
Bhaga is one of the twelve °dityas (solar deities of the Vedas) born ç
to Ka·yapa Praj<193>pati and his wife Aditi.
According to another view he is classed among the eleven Rudras.
He is said to be the lord of the month Pu<218>ya (January-February). ç
It is quite likely that the twelve °dityas are the twelve aspects ç
of the sun spread over the twelve months and the aspect connected ç
with the month Pu<218>ya is named Bhaga.
There was one Bhaga in the sacrificial assembly of Dak<218>a Praj<193>pati. ç
He too like others was subjected to the wrath of V<200>rabhadra, the ç
terrible emissary of <185>iva, and lost his eyes.
The word bhaga represents the group of six gu<207>as or blessed qualities: ç
ai·varya (lordship), dharma (righteousness), ya·as (renown), ·r<200> ç
(splendour), j<210><193>na (know-ledge) and vair<193>gya (detachment). ç
One who possesses these in abundance is `Bhagav<193>n.' The term is ç
generally applied to God; and even to sages and prophets. When applied ç
to a goddess it becomes `Bhagavat<200>.'
Sometimes these six gu<207>as are listed in a slightly different way: ç
j<210><193>na, ai·varya, ·akti (ability), bala (strength), v<200>rya ç
(viri-lity) and tejas (splendour). They are considered as the material ç
or instruments of ·uddhas<216><218><219>i or pure creation. They also ç
play a part in the manifestation of vy<220>has or emanations from ç
God V<193>sudeva viz., Sa<209>kar<218>a<207>a, Pradyumna and Aniruddha.
@SPACE = 
@NT = Bhagavadg<200>t<193>
@N1 = (`Song of God')
@SPACE = 
The Bhagavadg<200>t<193>, popularly known as the G<200>t<193>, ç
is one of the outstanding religious classics of the world. Hindus, ç
irrespective of their sects and denomi- nations, cherish great reverence ç
for this book. A ceremonial reading of the book or even a part thereof, ç
is believed to confer great religious merit.
The book itself, comprising eighteen chapters, forms an integral part ç
of a much bigger work, the great epic Mah<193>bh<193>rata (vide ç
Bh<200><218>maparva, chapters 25 to 42). It is a poetical work in ç
the form of a dialogue between <185>r<200> K<216><218><207>a and Arjuna, ç
on the battlefield of Kuruk<218>etra. The setting of the battlefield ç
contributes a dramatic element to the book and relates religion to ç
the realities of life.
The greatness and the popularity of the G<200>t<193> can be attributed ç
to several factors. It is part and parcel of the epic Mah<193>bh<193>rata ç
which itself has been highly venerated as the fifth Veda (Pa<210>cama-Veda). ç
The teacher of the G<200>t<193> is <185>r<200> K<216><218><207>a, ç
who is regarded by the Hindus as an avat<193>raor incarnation of ç
God Himself. An ideal friend, a great statesman, an invincible warrior, ç
a wise preceptor and a yogi par excellence he harmonizes in his ç
life the various conflicting activities of life. It is precisely this ç
that makes him the fittest person to preach such a religio-spiritual ç
classic. Arjuna, the recipient of the teaching, though himself a great ç
warrior, is a typical representative of the humans, easily liable ç
to be upset or confused during periods of crisis. Hence, his predicament, ç
very much represents ours, in a similar situation. The questions, ç
doubts and misgivings he raises and the solutions that <185>r<200> ç
K<216><218><207>a offers are not only relevant but also valid even ç
today.
@SPACE1 = 
There is an additional reason too. The Hindu Ved<193>ntic tradition ç
has always regarded the prasth<193>natraya (the three foundational ç
works) as its basis; and the G<200>t<193> is one of them, the other ç
two being the Upani<218>ads and the Brahmas<220>tras. That is why ç
<185>a<209>kara (<F51320MS>A.<|>D.<W1> <F255D>788-820) and other ancient teachers ç
have chosen to write commentaries on it.
Since the G<200>t<193> is an integral part of the epic Mah<193>bh<193>rata, ç
its date and authorship are obviously the same as those of the epic ç
itself. (See <MS>MAH°BH°RATA<D>.) K<216><218><207>a Dvaip<193>yana, ç
better known as Vedavy<193>sa, is reputed to be its author. As per ç
the Hindu oral traditions based on their notion of time as the yuga-system, ç
the Kuruk<218>etra war must have taken place during 3139 <MS>B.C.<D> ç
The dates given however by the modern historians and scholars (mostly ç
of the West) vary from 1424 <MS>B.C.<D> to 575 <MS>B.C.<D> At the ç
present stage of research, it may be difficult to clinch the issue ç
on such chronological matters.
The widely accepted present text of the G<200>t<193> is based on ç
the one chosen by <185>a<209>kara, the earliest of the traditional ç
commentators. It consists of 700 ·lokas or verses spread over 18 chapters. ç
The following is a brief summary of the book, arranged chapterwise.
@N-1 = Chapter 1 (Arjuna-vi<218><193>da-yoga, 47 verses)
Arjuna, the P<193><207><195>ava hero, shaken by the prospect of killing ç
the venerable Bh<200><218>ma and the preceptor Dro<207>a, gets into ç
a despondent mood at the start of the war. He describes the horrendous ç
fallout of such wars, and lays down his arms refusing to fight.
@N-1 = Chapter 2 (S<193><209>khya-yoga, 72 verses)
<185>r<200>  K<216><218><207>a,  at  first,  admonishes Arjuna for ç
his unmanly and ignominious behaviour. This, however, falls on deaf ç
ears. Hence he is obliged into giving a long philosophical discourse. ç
Since the soul inhabiting bodies, is immortal, one should not grieve ç
over death and destruction. It is Arjuna's duty to fight this righteous ç
war and win it or become a martyr if necessary, but never yield to ç
unrighteousness. Work done as duty, in a spirit of detachment and ç
for public good, ultimately leads to perfection. A perfect man (called ç
`sthitapraj<210>a' here) is equanimous under all the vicissitudes ç
of life.
@N-1 = Chapter 3 (Karmayoga, 43 verses)
Clearing Arjuna's doubts regarding the conflict between j<210><193>na ç
(knowledge), which envisages renunciation and karma (work, action) ç
<185>r<200> K<216><218><207>a opines that the path of karma is easier ç
and better for most people. Citing the example of ancient kings like ç
Janaka and of his own, he urges Arjuna not to relinquish work, but ç
to perform his duties without selfish motives.
@N-1 = Chapter 4 (J<210><193>na-yoga)
While reminiscing how Karmayoga or the yoga of action taught by him ç
in the ancient days to Vivasv<193>n and others got lost in course ç
of time, <185>r<200> K<216><218><207>a reveals that he is God Himself ç
come down to save dharma or righteousness. He incarnates here out ç
of his own will whenever dharma declines, to put it on a firm foundation. ç
He extols the greatness of j<210><193>na or spiritual wisdom.
@N-1 = Chapter 5 (Karma-sa<221>ny<193>sa-yoga,<R>ç
29 verses)
Answering a question from Arjuna whether karma-sa<221>ny<193>sa (renunciation ç
of action) or Karmayoga (yoga of action) is better, <185>r<200> K<216><218><207>a ç
avers that the latter is better for him. What is needed is equanimity ç
while doing karma.
@N-1 = Chapter 6 (Dhy<193>nayoga, 47 verses)
In this chapter <185>r<200> K<216><218><207>a describes the process ç
of dhy<193>na or meditation. Place and posture suitable for meditation ç
as also the methods of controlling the mind are graphically depicted.
@N-1 = Chapter 7 (J<210><193>na-vij<210><193>na-yoga, 30 verses)
<185>r<200> K<216><218><207>a as the Supreme Lord, has created the ç
whole universe, drawing upon his twofold prak<216>ti or nature. It ç
is he that is holding together all beings and things. Only those that ç
surrender themselves to him can transcend his m<193>y<193> or power ç
of delusion.
@N-1 = Chapter 8 (Ak<218>arabrahmayoga, 28 verses)
<185>r<200> K<216><218><207>a describes here how a person remembering ç
Him at the moment of death attains Him. Repetition of pra<207>ava ç
or Om at this juncture is a great help. He also mentions the two well-known ç
paths†arcir<193>dim<193>rga and dh<220>m<193>dim<193>rga, the paths ç
of light and smoke†which the j<200>vas or embodied beings take to ç
after death.
@N-1 = Chapter 9 (R<193>javidy<193>-r<193>jaguhya-yoga,<R>ç
34 verses)
Continuing the discourse, <185>r<200> K<216><218><207>a gives here ç
the esoteric wisdom by which Arjuna can get liberation. He is everything ç
in creation. If people can worship him with devotion, offering him ç
even insigni-ficant things like a flower, or a leaf or water, he accepts ç
them and blesses them. His devotee never perishes in life.
@N-1 = Chapter 10 (Vibh<220>tiyoga, 42 verses)
@EMERGENCY = <185>r<200> K<216><218><207>a devotes this chapter almost ç
entirely to the delineation of his vibhutis or divine manifestations. ç
He is the best or the essence in all beings or things. The whole world ç
has been supported by just a part of His glory.
@N-1 = Chapter 11 (Vi·var<220>pa-dar·ana-yoga,<R>ç
55 verses)
@EMERGENCY = At Arjuna's request whose curiosity has been roused, ç
<185>r<200> K<216><218><207>a reveals his Vi·var<220>pa or celestial ç
form, after endowing him with a divine sight. Awed by it, Arjuna offers ç
his prayers and obeisance. <185>r<200> K<216><218><207>a withdraws ç
the Vi·var<220>pa and declares that it can be seen only by those who ç
have intense devotion.
@N-1 = Chapter 12 (Bhaktiyoga, 20 verses)
@EMERGENCY = In this chapter, <185>r<200> K<216><218><207>a declares ç
that even though contemplation on the Avyakta or the Unmanifest leads ç
to the same result as devotion to him, the latter path is better. ç
He advises Arjuna to cultivate devotion to him. Towards the end, the ç
characteristics of a bhakta or an ideal devotee are delineated.
@N-1 = Chapter 13 (K<218>etra-k<218>etraj<210>a-yoga,<R>ç
34 verses)
The body is the k<218>etra or the field. The Self is the k<218>etraj<210>a ç
or the knower of the field. These two are described in this chapter. ç
This is followed by descriptions of j<210><193>na (knowledge), j<210>eya ç
(that which is to be known, viz., Brahman), prak<216>ti (nature) and ç
puru<218>a (the Self or k<218>etraj<210>a). Those who can intuit the ç
difference between the last two, will attain Brahman.
@N-1 = Chapter 14 (Gu<207>atraya-vibh<193>ga-yoga,<R>ç
27 verses)
Prak<216>ti or nature from which creation proceeds, prodded by the ç
Lord (<185>r<200> K<216><218><207>a), comprises the three gu<207>as†sattva, ç
rajas and tamas. There is a detailed description of these gu<207>as ç
and also that of the gu<207><193>t<200>ta or the person who has transcen-ded ç
them.
@N-1 = Chapter 15 (Puru<218>ottama-yoga, 20 verses)
In this chapter <185>r<200> K<216><218><207>a describes sa<221>s<193>ra ç
or the created world as an inverted tree with its roots above, in ç
Brahman or Pur<193><207>a-puru<218>a, the Primeval Being. By taking ç
refuge in Him, this tree can be cut resulting in liberation. There ç
is also a description of transmigration of the j<200>va, the bound ç
soul. <185>r<200> K<216><218><207>a also states that He is the power ç
that sustains the world and the living beings. He is the Puru<218>ottama ç
or the Best of beings.
@N-1 = Chapter 16 (Daiv<193>sura-sampad-vibh<193>ga-yoga, 24 verses)
<185>r<200> K<216><218><207>a delineates here those traits of character ç
(sampat) that make a person divine (daiv<200>) or demoniac (<193>sur<200>). ç
He assures Arjuna that he belongs to the divine group but urges him ç
to avoid the three gateways to hell: lust, anger and greed.
@N-1 = Chapter 17 (<185>raddh<193>traya-vibh<193>ga-yoga,<R>ç
28 verses)
This chapter contains interesting des-criptions of ·raddh<193> (faith), ç
<193>h<193>ra (food), yaj<210>a (sacrifices), tapas (austerity) and ç
d<193>na (gifts), all being divided into three categories according ç
to the three gu<207>as. <185>r<200> K<216><218><207>a also gives the ç
aphorism `O<221> tat sat,' a designation for Brahman, which can act ç
as a magic formula to correct the deficiencies in religious acts.
@N-1 = Chapter 18 (Mok<218>a-sa<221>ny<193>sa-yoga)<R>ç
78 verses)
This is the last and the longest chapter dealing with several miscellaneous ç
topics like ty<193>ga and sa<221>ny<193>sa (renunci-ation), j<210><193>na ç
(knowledge), karma (action) and kart<193> (doer) classified as per ç
the three gu<207>as. There is also the mention of the society being ç
divided into four var<207>as or groups, according to nature and vocation. ç
Finally <185>r<200> K<216><218><207>a advises Arjuna to totally surrender  himself  to  Him,  with  the ç
promise of freeing him from all sins. Arjuna, with his delusion destroyed ç
by this wonderful discourse vows to fight in obedience to hiscommand.
@SB = The Philosophy of the Bhagavadg<200>t<193>
The Indian philosophical systems, known as dar·anas, generally treat ç
their subject under four major headings: the Cause of the universe; ç
creation or evolution of the universe; nature of the individual soul; ç
the goal of human life and the means of achieving it. Though the Bhagavadg<200>t<193> ç
is not a systematic treatise on philosophy it is possible to deal ç
with its subject matter under these headings. It may not be out of ç
place to mention here that the colophon given at the end of each chapter ç
of the G<200>t<193> viz., Upani<218>ad, Brahmavidy<193> and Yoga·<193>stra, ç
reflects its contents very well. It is an `Upani<218>ad' or esoteric ç
wisdom given by the teacher to a disciple on request. It is `Brahmavidy<193>' ç
since it deals with Brahman, the Absolute. It is `Yoga·<193>stra' ç
since it describes yoga or practical disciplines that help an aspirant ç
to attain spiritual wisdom, the goal of life.
<185>r<200> K<216><218><207>a has been venerated and worshipped as ç
God Himself, come down as a human being, to save mankind and re-direct ç
it in the path of dharma or righteousness. In the Mah<193>bh<193>rata ç
and the Bh<193>gavata, as also in the G<200>t<193> itself, <185>r<200> ç
K<216><218><207>a often identified himself with God and speaks with ç
indisputable authority. While studying the philosophy of the G<200>t<193>, ç
it is necessary to keep this fact in mind.
The G<200>t<193> compares the created universe to an inverted tree ç
with its roots above, established in God (15.1-4). The more popular ç
view of the mythological lore that Brahm<193> (the four-faced Creator) ç
creates the world during his `day' and withdraws it into himself during ç
`night,' is also referred to (8.17-19). The variousterms used to ç
indicate the Supreme or God are: Parabrahman (13.12), Param<193>tman ç
(13.22, 31), Uttamapuru<218>a or Puru<218>ottama (15.17-19), ®·vara ç
(15.17; 18.61), k<218>etraj<210>a (13.2) and Parame·vara (13.27).
God has a twofold prak<216>ti or nature. The apar<193> or the lower ç
one is insentient and comprises these eight: the five elements like ç
earth and water, manas (mind), buddhi (intellect) and aha<209>k<193>ra ç
(egoism). The par<193> or the higher one consists of the innumerable ç
j<200>vas or souls. Creation proceeds out of the combination of these ç
two. It is under His direction that prak<216>ti gives birth to all ç
beings and things. He is the sole origin and place of dissolution ç
of this universe (7.4-6; 9.7). The whole universe is supported by ç
Him even as the beads of a necklace are supported by the string on ç
which they are strung (7.7). AsAvyakta or the Unmanifest, He has ç
pervaded the whole universe (9.4). That is why He is the essence of ç
all, in this creation (10.41).
God is not only transcendent and immanent (18.61), he can also incarnate ç
himself as a human being, whenever dharma or righteousness declines, ç
in order to restore its balance. He does it out of his own free will. ç
By his m<193>y<193>-power, and subjugating his prak<216>ti, he creates ç
a body for himself (4.6-8).
As incarnation, the personal aspect of the Impersonal, God is more ç
easily approachable through devotion (9.26). He responds in whatever ç
way people approach him (4.11; 7.21-23). His devotee never gets perished ç
(9.31). Those who surrender to him will easily cross over m<193>y<193> ç
(the delusive power of God), which is otherwise impossible to cross ç
(7.14). He takes over their entire responsibility even here in this ç
world (9.22). That is why He constantly urges Arjuna to cultivate ç
devotion to him and surrender to him (9.34; 11.55; 18.65, 66).
The j<200>va or the individual soul is an important aspect of this ç
creation. He is a part of God (15.7). He is the higher aspect of his ç
nature, par<193>prak<216>ti (7.5). He is essentially unborn, indestructible ç
and eternal (2.17-25). He takes on bodies like wearing garments and ç
then discards them, to take new ones (2.22). While doing so he draws ç
to himself the five sense-organs and the mind from the apar<193> prak<216>ti ç
or the lowerprak<216>ti (7.4,<|>5) and transmigrates with them. He ç
is deluded by aj<210><193>na or ignorance which covers j<210><193>na ç
or know-ledge (5.15).
The goal of life is to reach the Lord's Abode from which there is ç
no return to this mundane existence (8.16; 5.17; 15.6). This state ç
has been variously called as brahma-nirv<193><207>a (dissolution into ç
Brahman †2.72; 5.24), br<193>hm<200>sthiti (being established in Brahman†2.72), ç
sa<221>siddhi (perfection†8.15; 18.45), par<193>gati (highest state†6.45; ç
8.13, 21; 9.32; 13.28; 16.22) and attaining <185>r<200> K<216><218><207>a ç
Himself (4.9, 10; 5.29; 7.3, 18, 23, 30; 8.5, 7, 14, 15, 16; 9.28, ç
34; 10.10; 11.55; 12.4, 9; 18.55). The ancient Upani<218>adic idea ç
of the j<200>va reaching Brahmaloka (Abode of Brahm<193>) by the arcir<193>di-m<193>rga ç
or the path of light, has also been mentioned by the G<200>t<193> ç
(8.24-26).
Since it is aj<210><193>na or ignorance thatis responsible for transmigration, ç
it can be erased only by j<210><193>na or spiritual wisdom which alone ç
can accomplish it (4.35-39; 5.16,17).
Acquisition  of  j<210><193>na  has  to  be preceded by spiritual ç
disciplines that help in purifying the mind. Indriyanigraha or control ç
of sense-organs is one of the most important disciplines referred ç
to (2.58, 60, 61, 64, 68; 3.34, 41; 5.22, 23; 6.4, 24; 12.4). Tapas ç
or austerity (16.1; 17.14-16; 18.5) and other disciplines including ç
the performance of one's duties with the right attitude have also ç
been recommended. But devotion to the Lord and surrendering to him ç
have been highly extolled (7.21; 8.10, 22; 9.14, 26, 29, 31; 11.54; ç
12.17, 20; 13.10; 14.26; 18.55).
There are three beautiful descriptions of the perfect being, who has ç
reached the final goal of life: the sthitapraj<210>a or the man of ç
steady wisdom (2.55-72), the bhakta or the devotee (12.13-20) and ç
the gu<207><193>t<200>ta or one who has transcended the three gu<207>as ç
(14.22-27).
The sthitapraj<210>a (man of steady wisdom) is bereft of all desires. ç
He is unmoved by the pairs of opposites like pleasure and pain, attachment ç
and aversion. He is capable of withdrawing his sense-organs from the ç
sense-objects effortlessly. He is the supreme master of himself. He ç
can wield his sense-organs among the sense-objects without being affected ç
by them. He is ever awake to the <193>tman, the reality within himself. ç
He is free from egoism and possessiveness, and hence ever filled with ç
peace. This state is called br<193>hm<200>sthiti; the state of being ç
established in Brahman.
The bhakta or the ideal devotee who is ever dear to God, is free from ç
inimical thoughts towards all beings. He has nothing but friendliness ç
and compassion for them. He has neither egoism nor attachment. He ç
is ever equanimous and contented. Having controlled the senses and ç
the mind, he has totally dedicated them to God, out of devotion. He ç
is never upset by the people nor are they agitated by him. Bereft ç
of desires, pure to the core and expert in the field of work, he hasyet ç
renounced all selfish works. Deeply devo-ted to God, indifferent to ç
praise and blame, unaffected by the vagaries of the weather and having ç
no fixed place for dwelling, the bhakta is extremely dear to the Lord.
The gu<207><193>t<200>ta (who is beyond the three gu<207>as) is ever ç
unaffected by the experiences brought about by the three gu<207>as, ç
like knowledge or happiness or delusion. He knows that the gu<207>as ç
as the senses act upon the gu<207>as as objects and that he as the ç
Self is beyond them. He looks upon happiness and misery, wealth and ç
worthless objects, praise and blame with equipoise. He never undertakes ç
desire- motivated actions, but ever serves God through devotion.
@SB = Special Contribution of the G<200>t<193> to<R>ç
Indian Philosophical Thought
Though the G<200>t<193> has been reputed to contain the essence ç
of the teachings of the Upani<218>ads and is considered to be one ç
of the three basic scriptures of Ved<193>nta (prasth<193>natraya) ç
there is no gainsaying the fact that it has charted new avenuesin ç
the Indian philosophical literature, previously unknown or unexpressed. ç
The work presents us with three original doctrines: a.The doctrine ç
of ni<218>k<193>ma-karma-yoga (or the yoga of desireless action), ç
with the allied concepts of svadharma and loka-sa<209>graha; b. The ç
doctrine of integral yoga as a comprehensive mode of s<193>dhan<193> ç
(or spiritual discipline); and c. The doctrine of avat<193>ra (descent ç
of God into the human form or the theory of incarnation of God.)
@S10 = a. The Doctrine of Ni<218>k<193>makarmayoga:
At the time of <185>r<200> K<216><218><207>a, two major streams of ç
thought, resulting in two different views and ways of life existed.On ç
one side was the philosophy of abhyudaya or worldly well-being with ç
its inordinate emphasis on yaj<210>as and y<193>gas, sacrificial rites ç
and rituals, by which one could get everything in life, here and hereafter. ç
Since this involved a lot of time, energy and money, and since the ç
results were considered petty, the reaction came in the form of the ç
doctrine of ni··reyasa or the highest good, put forward by the sages ç
of the Upani<218>ads, who advocated a life of renunciation of all ç
actions except those needed for the bare sustenance of life, coupled ç
with mendicancy and contem- plation on the <193>tman (the Self) within.
By their very nature these two views and ways were restricted to the ç
br<193>hma<207>a-k<218>attriya combine, at least, to the more affluent ç
and the more rigorous amongst them. As a result, the majority of the ç
people were left in the lurch, though imbued with higher spiritual ç
aspirations. It is here that <185>r<200> K<216><218><207>a's doctrine ç
of ni<218>k<193>ma-karma-yoga becomes relevant and extremely useful.
Being a wise and sensible leader, <185>r<200> K<216><218><207>a accepts ç
the tradition of sacrifices as it existed then, but shows the way ç
to transform it or even transcend it. Since Praj<193>pati (Father ç
of beings) created the system of yaj<210>a or sacrifice as a link ç
between human beings and gods, they are expected to prosper only by ç
mutual help and cooperation (3.10, 11). But a yaj<210>a or sacrifice ç
need not be only that done in a duly consecrated fire. Any act of ç
an indi- vidual, involving the sacrifice of selfishness and done for ç
the public good can also be a yaj<210>a (vide 4.25-30).
@SPACE1 = 
After defining sa<221>ny<193>sa as the renunciation of all k<193>mya-karmas ç
or desire-motivated actions, and ty<193>ga as the abandonment of sarvakarmaphala ç
or the fruits of all actions (18.21), <185>r<200> K<216><218><207>a ç
rules out the renunciation of actions like yaj<210>a (sacrificial ç
rites), d<193>na (giving gifts) and tapas (austerity) since they purify ç
the mind (18.5). Even they are to be performed without attachment ç
and the desire for fruits, as a matter of duty. What really binds ç
one is not work itself, but the selfish desire for its fruits (vide ç
9.20, 21). Since work is inevitable for an embodied being (3.5,8; ç
18.11) it is better to accept the fact gracefully and perform itwith ç
self-control (3.7), as a yaj<210>a or sacrifice (3.9) and giving up ç
the desire for the fruits thereof (3.19; 12.11). One who performs ç
actions thus is both a sa<221>ny<193>si and a yogi (6.1). Alternatively, ç
one can perform actions for the sake of God and offer the fruits thereof ç
(3.19; 12.11). One who performs actions thus is both a sa<221>ny<193>si ç
and a yogi (6.1). Alternatively, onecan perform actions for the sake ç
of Godand offer the fruits also to him (12.6,10, 11; 11.55; 5.10-12). ç
It is necessary to perform actions even from the standpoint of lokasa<209>graha ç
or guiding the people on the right path (3.20, 25) which is the bounden ç
duty of the leaders of the society.
Work done in the right spirit, thus, can also lead to mok<218>a (liberation ç
or perfection). It is in no way less effective than j<210><193>na ç
or knowledge. Many a great onein the past, like Janaka, attained ç
perfection through the path of action alone (3.19, 20; 4.15,<|>23,<|>41; ç
5.5,<|>6,<|>12; 8.7; 9.27,<|>28; 12.12; 18.45,<|>46,<|>56). Not only that, ç
such persons, including <185>r<200> K<216><218><207>a himself, continued ç
to live in the society and work, to set an example to the unenlightened ç
ones, as to perfection in work, which also will lead to beatitude ç
(3.21-26).
@SPACE1 = 
Arjuna was a sincere seeker of spiritual wisdom. He was not interested ç
in  sak<193>ma-karma  or  desire-motivated actions. However, he was ç
not qualified to tread the path of j<210><193>na or knowledge which ç
entails renunciation of all actions. That is why <185>r<200> K<216><218><207>a ç
declares that Arjuna has the competence only to work; and not to renouncing ç
it; but he should do so without reference to the fruits thereof (2.47).
Closely associated with this, is the idea of `svadharma', `dharma' ç
or duties that are `sva' or one's own, accruing to one by one's nature ç
and nurture, and, ordained by the scriptures. It goes without saying ç
that `svadharma' must be `dharma' (righteousness) first. Such svadharma ç
should never be abandoned. If performed, it brings in great good; ç
if abandoned, sin(2.31-33). However imperfect it may appear, it is ç
far better to die performing it than to do paradharma or someone else's ç
dharma which is unsuitable (3.35). One who acts according to svadharma ç
will never be tainted by its effects (18.47). There is no doubt that ç
the performance of svadharma in the right spirit will lead to perfection ç
(18.45,<|>46).
@S10 = b. The Doctrine of Integral Yoga:
As already stated, the colophon of the G<200>t<193> calls it as ç
a `yoga·<193>stra.' `Yoga' is a technical term which means union with ç
God as also the spiritual discipline that leads to such union.
@SPACE1 = 
Though yoga is one, taking into consideration the different types ç
of human mind†the active, the philosophical, the emotional and the ç
psychic†it has branched off into four paths: Karmayoga, the path of ç
work for the active:, J<210><193>na-yoga, the path of knowledge, for ç
the philo- sophical; Bhaktiyoga, the path of devotion, for the emotional; ç
and, R<193>jayoga, the path of psychic control for the psychic. Each ç
of these yogas opens upon the infinite horizon of Truth and effects ç
union with God. The G<200>t<193> describes them all.
