@NT = mah<193>janapadas
@N1 = (`great countries')
@SPACE = 
Janapada or r<193><218><219>ra is a country and its people. Certain ç
janapadas seem to have acquired the name `mah<193>janapada' during ç
the period of early Buddhism. They were sixteen and were spread over ç
the Indo-Gangetic plains. Though they were small territories, they ç
might have got this appellation either due to the greatness of the ç
dynasties of the kings that ruled them or because they were prosperous ç
and militarily strong.
Some of them are: A<209>ga, Magadha, K<193>·<200>, Kosala, Vajji, ç
Kuru, P<193><210>c<193>la, <185><220>ra-sena, K<193>mbhoja, Avant<200> ç
and G<193>ndh<193>ra.
@SPACE = 
@SPACE = 
@NT = Mah<193>k<193>la
@N1 = (`Great Time', `Great<R>ç
Destroyer')
@SPACE = 
`Mah<193>k<193>la' is one of the well-known epithets of <185>iva, ç
since he brings about the destruction of the universe at the end of ç
a cycle of creation.
The <185>ivali<209>ga at Ujjayin<200> (the modern Ujjain in Madhya ç
Pradesh), one of the twelve jyotirli<209>gas, is also called `Mah<193>k<193>la'.
Sometimes Mah<193>k<193>la is described as an offspring of <185>iva ç
and the leader of his troops (pramathaga<207>a).
Some works of the tantras like the Tantras<193>ra picture him as ç
a terrific deity who can be appeased for destroying one's enemies. ç
He has a fierce appearance, is dressed in a tiger-skin, has two arms ç
carrying da<207><195>a (cudgel) and kha<219>v<193><209>ga (magical ç
wand) and wears a garland of severed heads.
He is the husband of Mah<193>k<193>l<200>.
@NT = Mah<193>lak<218>m<200>
@SPACE = 
@SPACE = 
There are two aspects of Mah<193>lak<218>m<200>. The first is the ç
same as Lak<218>m<200>, the consort of Vi<218><207>u. (See <MS>LAK<186>M®<D> ç
for details.)
In the second aspect, as depicted in the Dev<200>m<193>h<193>tmya ç
or Durg<193>sapta·at<200>, she is the same as Durg<193> or P<193>rvat<200>, ç
who destroyed the demon Mahi<218><193>sura. She is described as light ç
red in complexion and seated on a lotus. She has eighteen arms holding ç
various weapons like battle-axe, mace, bow and arrow and lance as ç
also other items like lotus, rosary, wine-cup, conch and bell.
In the annexure to the same work known as Pr<193>dh<193>nikarahasya, ç
she is depicted as the first to appear (before everything) and the ç
other deities like Brahm<193>, Vi<218><207>u and Mahe·vara, as also ç
their consorts, to have emanated out of her.
The cult of Mah<193>lak<218>m<200> is essentially <185><193>kta in ç
orientation.
The most famous temple dedicated to her is at Kolh<193>pur (also known ç
as Karav<200>rak<218>etra) in Maharashtra.
See also <MS>KOLH°PUR.<D>
@SPACE = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@NT = mah<193>laya
@N1 = (`the great dissolution')
@SPACE = 
In the works dealing with Ha<219>hayoga, the word `mah<193>laya' or ç
layayoga is used in the sense of sam<193>dhi (highest superconscious ç
experience) wherein the j<200>va or the individual soul loses his ç
identity in <185>iva or Param<193>tman (the Supreme Self) even as ç
a drop of water gets merged in the sea or salt gets dissolved in water.
The s<193>dhana of layayoga has nine parts. See <MS>LAYAYOGA<D> for ç
details.
The word Mah<193>laya also represents Mah<193>laya Am<193>v<193>sy<193> ç
occuring in September-October, when the pit<216>pak<218>a (the fortnight ç
considered as extremely auspicious for performing obsequial rites ç
to the departed ancestors) comes to a close. It also indicates the ç
commencement of the Dasara festival from the next day.
@NT = mah<193>laya·r<193>ddha
@N1 = (`·r<193>ddha [performed on the] festival day of [the pit<216>s ç
or manes]')
Performance of ·r<193>ddhas to appease the dead ancestors is an integral ç
part of Hindu rituals. Out of these, the mah<193>laya-·r<193>ddha ç
is a well-known rite. It is to be performed during the k<216><218><207>apak<218>a ç
or the dark half of the month of Bh<193>drapada (September), when ç
the sun is in the Kany<193>lagna (Virgo). It is supposed to give great ç
joy to the manes. It can be performed for the benefit of not only ç
the paternal and maternal ancestors but also for other relatives.
The procedure is almost identical with that of p<193>rva<207>a·r<193>ddha. ç
See <MS><185>R°DDHA<D> for details.
@NT = Mah<193>m<193>y<193>
@N1 = (`the [goddess of] great<R>ç
delusion')
This is one of the names of Durg<193> since she is unlimited creative ç
energy and delusive power (mah<193> = great, m<193>y<193> = creative ç
energy or delusive power). She isoften identified with Vi<218><207>um<193>y<193> ç
(vide Bhagavadg<200>t<193> 7.14), the special power of Vi<218><207>u ç
responsible for creation, preservation and destruction.
The   M<193>rka<207><195>eyapur<193><207>a   (85.34) describes her ç
as a secondary manifestation of Mah<193>k<193>l<200>, the t<193>masik ç
aspect of Mah<193>-lak<218>m<200>.
She is generally described as a goddess of the complexion of red hibiscus ç
flower, having three eyes and four arms carrying ik<218>ukoda<207><195>a ç
(bow of sugarcane), pu<218>pab<193><207>a (arrow of flowers), p<193>·a ç
(noose) and raktotpala (red lotus).
The goddess associated with Amara-n<193>tha <185>iva (in the cave ç
of Amarn<193>th, Kashmir) is also called Mah<193>m<193>y<193>. This ç
is one of the <185>aktip<200><219>has where the neck of Sat<200>-D<193>k<218><193>ya<207><200> ç
is supposed to have fallen.
@NT = mah<193>n<193>mn<200>
@N1 = (`of great fame')
It is the name of a group of nine verses of the S<193>maveda (Jaimin<200>ya ç
Sa<221>hit<193> 2.7) beginning with the words `vid<193> maghavan'. ç
These verses are also called <185>akvar<200> verses. They are chanted ç
on various occasions as during Ah<200>na sacrifices.
They are chanted as a part of Vedavratas (religious rites connected ç
with the commencing of Vedic studies) and also as expiation for certain ç
kinds of sins.
@NT = Mah<193>n<193>r<193>ya<207>a Upani<218>ad
The Upani<218>ads are the last part of the Vedas†hence the appellation ç
`Ved<193>nta' (anta = end)†and contain the quintessence of the spiritual ç
wisdom of the same. This wisdom helps us to loosen our bonds of sa<221>s<193>ra ç
(transmigratory existence), destroys our ignorance of our real nature ç
as the <193>tman†the pure spirit beyond the body-mind complex†and ç
leads us to God, giving us the supremely blissful experience.
If the ten Upani<218>ads upon which <185>a<209>kara (<MS>A.<|>D.<D> ç
788-820) has commented upon are considered as the major ones, the ç
Mah<193>n<193>r<193>ya<207>a Upani<218>ad comes in the series as ç
only next to them. It is the tenth prap<193><219>haka or section of ç
the Taittir<200>ya °ra<207>yaka of the K<216><218><207>a Yajurveda, ç
the earlier three prap<193><219>hakas (7th to 9th) forming the well-known ç
Taittir<200>ya Upani<218>ad.
This work is also known as the Y<193>j<210>ik<200> Upani<218>ad.
There are two recensions or versions of this Upani<218>ad known as ç
the Dr<193>vi<195>a-p<193><219>ha and the °ndhrap<193><219>ha. ç
The former has 64 sections while the latter†the longer version†has ç
80 sections.
Both Bha<219><219>abh<193>skara (<MS>A.<|>D.<D>1188) and S<193>ya<207>a ç
(14th century <MS>A.<|>D.<D>) have written commentaries on the shorter ç
version. They have considered this Upani<218>ad as `khila' or a supplementary ç
part of the K<216><218><207>a Yajurveda. The longer version also ç
has a commentary but the author's name is not known.
Another commentary in the name of one Puru<218>ottam<193>nanda T<200>rtha ç
is also available. It is in the k<193>rik<193> form (in anu<218><219>ubh ç
verses). The text is either short or incomplete.
Unlike as in the other Upani<218>ads, the subject matter here does ç
not seem to follow any systematic arrangement or pattern. All the ç
three major subjects of the Vedas, viz., karma (rituals), up<193>san<193> ç
(meditation) and j<210><193>na (knowledge) find a place here. Many ç
of the mantras used inthe sandhy<193> ritual, p<220>j<193>s (ritualistic ç
worship) or other rites are found here. Hence it may be considered ç
more as a miscellany of all the subjects left over.
@SPACE1 = 
The vast contents may be briefly summarised as follows: description ç
of Brahman in his various aspects as Praj<193>pati,  Parame·vara  and  Ak<218>ara- ç
Brahman; realisation of Brahman in one's heart; knowledge of God alone ç
leads to mok<218>a or liberation; God pervades the universe; God is ç
one's all-in-all; various G<193>yatr<200>-mantras for up<193>san<193>; ç
prayers to Mother Earth; on Indra; destruction of sins; hymn to Durg<193>; ç
prayers for the attainment of knowledge; prayers for the increase ç
of retentive faculty; good and bad works; God can be seen only by ç
his grace; sacrifices help in getting purity of mind; N<193>r<193>ya<207>a ç
as the cosmic being who also resides in the heart; mantras for consecrating ç
the ·ivali<209>ga; salutation to the various aspects of <185>iva; ç
on Pra<207>ava; on G<193>yatr<200> mantra; Trisupar<207>a mantras; ç
Madhumantras; prayers for longevity and safety as also wealth; longing ç
for liberation; Viraj<193>homa-mantras; pr<193><207><193>gnihotra ç
ritual; unity of <185>iva and Vi<218><207>u; truthfulness as the supreme ç
means for liberation; importance of Agnihotra sacrifices; importance ç
of sa<221>ny<193>sa; yaj<210>a as a potent weapon; description of ç
<193>tmayaj<210>a which is the same as sa<221>ny<193>sa and sa<221>ny<193>sin's ç
life.
@SPACE1 = 
This Upani<218>ad is a mine of special information and instructions. ç
The well-known s<220>ktas†the N<193>r<193>ya<207>as<220>kta, the ç
Medh<193>s<220>kta, and the Durg<193>s<220>kta†find a place as ç
a part of the text. Mantras and procedures connected with the sandhy<193> ç
ritual,  repetition  of  G<193>yatr<200>-mantra, mantras used in the ç
Viraj<193>homa (a part of the procedure for taking sa<221>ny<193>sa), ç
the Trisupar<207>a mantras (also used in the same), the usual teachings ç
of the Upani<218>ads connected with <193>tman/Brahman, mukti, the ç
paths of devay<193>na andpit<216>y<193>na as also many principles ç
of philosophy and ethics are described here in an elegant language.
On the whole it is a very interesting and attractive Upani<218>ad, ç
extremely popular in the ritualistic circles.
See also <MS>UPANI<186>ADS.
@SPACE = 
@NT = Mah<193>n<193><219>aka
See <MS>HAN<188>MANN°<187>AKA.
@SPACE = 
@NT = Mah<193>nirv<193><207>a Tantra
Tantras may be grouped among the secondary class of literature and ç
are quite popular even now. Even though the word `tantra' means any ç
science or body of knowledge, in actual usage it has got restricted ç
to the works primarily devoted to the cult of <185>akti or the Divine ç
Mother.
The  Mah<193>nirv<193><207>a  Tantra  is  an important and well-known ç
work of the tantra group of literature that has also been printed. ç
The work now available is in 14 ull<193>sas or chapters, the total ç
number of verses being 2517. It is in the form of a dialogue between ç
Sad<193>·iva (the teacher) and his spouse P<193>rvat<200> (the disciple). ç
Many scholars feel it is incomplete. There is a Sanskrit <219><200>k<193> ç
or commentary by Harihar<193>-nanda Bh<193>rat<200>, the spiritual ç
preceptor of the famous social reformer and founder of the Brahma ç
Sam<193>j, R<193>j<193> R<193>mmohan Roy (<MS>A.<|>D.<D> 1772-1833). ç
It is even suggested that this commentator revised the original text ç
of the tantra itself to eliminate the unsavoury aspects of it and ç
bring it nearer to Ved<193>nta philosophy.
There is an incomplete commentary (up to the 158th verse of the 6th ç
chapter) by  one  <185>a<209>kar<193>c<193>rya  (<MS>A. D.<D> 1886?) ç
published from V<193>r<193><207>as<200>. He gives an esoteric interpretationand ç
criticises other(earlier) commentators.
The contents of the fourteen chapters may be summarised as follows: ç
liberation of beings; worship of Brahman; Supreme Brahman; importance ç
of kul<193>c<193>ra in the age of Kali; revelations of mantras and ç
elements of worship; homa and other rites; stotra and kavaca of Dev<200>; ç
var<207><193>·rama-dharmas; sa<221>sk<193>ras or the purificatory ç
sacraments; ·r<193>ddhas or funeral/obsequial rites; pr<193>ya·cittas ç
or expiatory acts; d<193>ya-bh<193>ga or division of property; installation ç
of images; consecration of <185>ivali<209>gas; four types of avadh<220>tas ç
or the perfected beings.
See also <MS>TANTRAS.<D>
@NT = mah<193>p<193>takas
@N1 = (`heinous sins')
The concept of sin exists in almost all the great religions of the ç
world. `P<193>taka' or `p<193>pa' is the most common word used in ç
the Sanskrit scriptures of Hinduism. It comes as a result of the transgression ç
of the laws of the moral and the spiritual world as enunciated by ç
the scriptures, which again, are considered as promulgated by God ç
Himself.
The dharma·<193>stras and the pur<193><207>as generally classify sins ç
into two main categories: the mah<193>p<193>takas or atip<193>takas ç
(major, mortal or most heinous sins) and the upap<193>takas (minor ç
or venial sins).
Under the mah<193>p<193>takas are included prohibited sexual relationships ç
like incest, murder, drinking liquor, theft and associating with the ç
sinners who commit such deeds.
The pr<193>ya·cittas or expiations for the mah<193>patakas range from ç
voluntary death to long years of very severe penances.
See also <MS>P°PA.<D>
@NT = mah<193>pralaya
@N1 = (`the great dissolution')
Hinduism believes in a cyclic order of creation: s<216><218><219>i ç
(creation), sthiti (maintenance) and laya (dissolution). After an ç
interval,  the  same  process  is  again repeated.
Brahm<193> (the fourfaced Creator) has a life-span of one hundred ç
years as per the divine scale, which comes to 1036 human years! ç
At the end of this period takes place the mah<193>pralaya or great ç
dissolution.
See <MS>PRALAYA<D> for more details.
@NT = mah<193>prasth<193>na
@N1 = (`the great or final<R>ç
departure')
The seventeenth book of the Mah<193>-bh<193>rata is known as Mah<193>prasth<193>nikaparva. ç
It describes the final journey of the five P<193><207><195>avas along ç
with Draupad<200> towards heaven.
`Mah<193>prasth<193>na' means walking continuously towards the north, ç
the Him<193>-layas, without food and rest, until the body falls and ç
dies out of sheer exhaustion.
This kind of religious suicide was permitted to the V<193>naprasthins ç
who had completed all their duties in life and found no more reason ç
to live.
It was also prescribed as a punishment for people who had committed ç
heinous sins like murder of a br<193>hma<207>a or of a foetus, incest ç
etc. However, it was prohibited in the Kaliyuga. Epigraphical evidences ç
show that certain kings like G<193><209>geya committed religious suicide ç
which might have included mah<193>prasth<193>na also.
@NT = mah<193>pur<193><207>a
See <MS>PUR°ØAS.<D>
@NT = mah<193>raurava
Naraka or hell is a place to where an evil person goes after death ç
to suffer for the heinous crimes and sins he has committed here. The ç
pur<193><207>as describe several varieties of them, the number varying ç
from 7 to 32. In the mah<193>raurava, terrible and highly poisonous ç
serpents torment the sinners who had usurped the properties of others, ç
their rightful owners.
See also <MS>NARAKA.
@NT = Maharloka
This is the fourth world above the earth (Bh<220>loka). It is not ç
destroyed during pralaya (dissolution) and lasts for the whole kalpa. ç
<184><218>is (sages) like Bh<216>gu live here till the end of the ç
kalpa. (See <MS>KALPA<D>.)
@NT = mahar<218>i
@N1 = (`the great sage')
See <MS><184><186>IS.<D>
@NT = Mah<193>rudra
See <MS>ATIRUDRA.<D>
@NT = mah<193>s<193>ntapana
@N1 = (`the great [expiation]<R>ç
that burns')
The topic of sins and their expiation (pr<193>ya·cittas) has been ç
widely discussed in the dharma·<193>stras as also the pur<193><207>as. ç
S<193>ntapana, mah<193>s<193>ntapana and atis<193>ntapana are one ç
variety of these expiations.
See <MS>S°NTAPANA<D> for details.
@NT = mah<193>·<193>nti
@N1 = (`the great propitiatory rite')
When problems, troubles and difficulties arise which are beyond human ç
efforts and capacities to get redemption from, human beings are apt ç
to take to religious or divine remedies. <185><193>ntis or propitiating ç
rites belong to this class. Mah<193>·<193>nti is one such rite prescribed ç
in some ancient works like the <185><193><209>kh<193>yana G<216>hyas<220>tras ç
(5.11).
Mah<193>·<193>nti is performed when mishaps such as the following ç
occur or for general well-being: fall of meteors, before the coronation ç
of a king or before he starts on an invasion, birth of a baby under ç
an inauspicious star, falling down of holy objects like the umbrella ç
of a deity in procession, when costly things are lost, during eclipses ç
and so on.
It is generally done on a specially raised platform wherein there ç
will be an agniku<207><195>a (fire place) as also places for kala·as ç
to be established. Mostly <184>gvedic mantras are recited during the ç
ceremonies. A homa also is performed. The yajam<193>na (main performer) ç
takes a bath at the end. The ·<193>ntijala (holy water used in the ç
rite) is sprinkled over him by the priests who are then suitably rewarded.
See also <MS><185>°NTIS.<D>
@NT = Mah<193>·ivar<193>trivrata
The deity Rudra-<185>iva is as old as the <184>gveda. The <185>iva ç
cult and <185>aivism are of hoary antiquity. Hence religious observances ç
on the days considered dear to <185>iva, must have been existing since ç
the ancient days.
The 14th day of the dark half of every month†k<216><218><207>a caturda·<200>†is ç
called `<185>ivar<193>tri' or `M<193>sa·ivar<193>tri'. The one in ç
the month of M<193>gha (February<192>March) is christened `Mah<193>·ivar<193>tri', ç
since it is the greatest of all.
In several pur<193><207>as like the Sk<193>nda, Padma and Garu<195>a, ç
there are stories and passages of hyperbolic eulogy of this Mah<193>·ivar<193>trivrata. ç
One of the common stories is how a ni<218><193>da or a kir<193>ta ç
(a hunter or an aborigine) who `observed' the vrata on the Mah<193>·ivar<193>tri ç
day unknowingly, out of the force of circumstances, by fasting, keeping ç
vigil and bathing a <185>ivali<209>ga (the emblem of <185>iva) with ç
water, was taken to the world of <185>iva. How much more would the ç
benefit be, if it is observed knowingly, with devotion!†This seems ç
to be the burden of such stories.
Of all the major Hindu festivals, Mah<193>·ivar<193>tri is the only ç
one wherein the austerity part (as signified by the very word `vrata') ç
is predominant. There is practically no festivity, revelry or gaiety ç
in its observance, the whole thing being one of continuous solemnity. ç
This is but natural since <185>iva is the god of the ascetics, the ç
very incarnation of vair<193>gya or renunciation!
About the origin of Mah<193>·ivar<193>tri, there are several myths. ç
When Brahm<193> (the fourfaced god of creation) and Vi<218><207>u ç
were disputing each other's greatness to establish their own supremacy, ç
a huge li<209>ga or pillar of fire appeared suddenly between them ç
and a voice from the void declared that he who would find the extremities ç
of this li<209>ga would be considered the greater one. Neither of ç
them succeeded and were hence obliged to accept the greatness of <185>iva ç
who had manifested as that pillar of light. This was the origin of ç
<185>ivali<209>ga and Mah<193>·ivar<193>tri.
@SPACE1 = 
According to the second myth, Mah<193>-·ivar<193>tri is the day on ç
which <185>iva Mah<193>deva, drank the h<193>l<193>hala poison that ç
emerged out of the milky ocean (k<218><200>ra-s<193>gara) when it ç
was being churned by the devas and the d<193>navas (gods and demons), ç
and thus saved the worlds from destruction. A third myth attributes ç
its greatness to its being the day of marriage of <185>iva with P<193>rvat<200>, ç
the daughter of the mountain king Him<193>laya. A fourth myth describes ç
this day as the day on which Lord <185>iva, out of joy, burst forth ç
into a great dance which has since been known as <185>ivat<193><207><195>avan<216>tya.
This vrata is open to all human beings. The basic disciplines to be ç
kept up on this day are: ahi<221>s<193> (non-injury), satya (speaking ç
the truth), brahmacarya (continence), day<193> (compassion), k<218>am<193> ç
(forgiveness) and anas<220>yat<193> (absence of jealousy). Fasting ç
is one of the most essential aspects of this vrata. So also j<193>gara<207>a ç
or keeping vigil in the night. Worship of <185>iva throughout the ç
night, bathing the ·ivali<209>ga with pa<210>c<193>m<216>ta (five ç
tasty things†milk, curds, ghee, sugar and honey), homa, japa of the ç
m<220>lamantra (basic mantra, viz., o<221> nama··iv<193>ya) and ç
prayer for forgiveness†are the other items involved in its observance. ç
He can then, at the end of the vrata, do p<193>ra<207><193> (breaking ç
the fast by partaking of the offerings).
One may take a vow to observe this vrata for 24 or 14 or 12 years. ç
At the end of this period one has to perform the udy<193>pana, a concluding ç
rite indicating the completion of the vow.
In the modern days, fasting, visiting <185>iva temples and keeping ç
awake in the night are common, though p<220>j<193> throughout the ç
night at homes is confined to the more orthodox sections.
@SPACE1 = 
The festival is celebrated with greatsolemnity and <F20M>Ç<F255D>clat in ç
the famous temples of <185>iva at V<193>r<193><207>as<200> (Banaras), ç
R<193>me·varam, Cidambaram, Soman<193>th, Bhuvane·var, K<193><202>ahasti ç
and other pilgrim centres.
@NT = mah<193>·vet<193>
@N1 = (`the great white [pure]<R>ç
mantra')
Fasting and japa or repetition of prescribed mantras are supposed ç
to give great merit. If the mantra `hr<193><221> hr<200><221> sa<199>' ç
(called mah<193>·vet<193>) is repeated on a Sunday along with fasting, ç
it is said to yield whatever one wants.
@NT = mahat
@N1 = (`the great')
Mahat is an important concept of the S<193><209>khya philosophy, also ç
accepted by theVed<193>nta metaphysics. It is the first product of ç
evolution of pradh<193>na or prak<216>ti (basic inert matter) comprising ç
the three gu<207>as†sattva, rajas and tamas. In its cosmic aspect ç
it is `mahat', the great germof this vast world of objects. In its ç
psychological aspect it is buddhi, the cosmic intellect, from which ç
the individual buddhis are produced in course of time by further evolution.
See <MS>S°<177>KHYA DAR<185>ANA.<D>
@NT = Mah<193>tala
The pur<193><207>as describe the universe as comprising 14 worlds, ç
7 being above this bh<220>loka or earth and 6 being below it. These ç
six are generally given the name P<193>t<193>lalokas. However, Mah<193>tala ç
is the fourth nether world starting with Atala, just below this earth.
It is supposed to be inhabited by multiheaded serpents, all descendants ç
of the sage Ka·yapa and his wife Kadr<220>. Some of the chief ones ç
among them are: Kahaka, Tak<218>aka, Su<218>e<207>a and K<193>liya.
@EMERGEN1 = Though they are terrible in appearance and cruel by nature, ç
they live in eternal fear of Garu<195>a, the great eagle-mount of ç
Lord Vi<218><207>u, an inveterate enemy of theirs.
@NT = mahatpari<207><193>ma
@N1 = (`transformation [that gives the a<207>us or atoms] mahattva ç
or practical dimension')
@EMERGEN1 = The Vai·e<218>ika Dar·ana is one of the six recognised ç
systems of Hindu philosophy. It has developed its own atomic theory ç
of creation.
@EMERGEN1 = Out of the seven fundamental basic principles of creation, ç
the four elements† earth, water, light or fire and air†are in the ç
form of param<193><207>us or extremely minute atoms. They have existence ç
but no perceptible dimension.
@EMERGEN1 = However, when by the will of ®·vara or God and the totality ç
of the karmas of the unredeemed souls of the previous creation, the ç
process of creation starts, two param<193><207>us†of course, of the ç
same element like the earth†join together forming a dvya<207>uka or ç
a diad. When three such dvya<207>ukas join together forming a trya<207>uka ç
then only it attains mahattva (perceptible dimension) and d<200>rghatva ç
(length and breadth). This change in the param<193><207>us becoming ç
`mahat,' is called `mahatpari<207><193>ma'.
@EMERGEN1 = See also <MS>VAI<185>E<186>IKA DAR<185>ANA.<D>
@NT = mah<193>v<193>kyas
@N1 = (`great sentences')
@EMERGEN1 = The post-<185>a<209>kara writers on Advaita Ved<193>nta ç
have mentioned four sentences, taken from four Upani<218>ads and belonging ç
to the four Vedas, which teach the unity of the <193>tman and Brahman, ç
as four `mah<193>v<193>kyas' or great sentences. They are: praj<210><193>nam ç
brahma (`Consciousness is Brahman') from the Aitareya Upani<218>ad ç
(5.3) of the <184>gveda; aham brahm<193>smi (`Iam Brahman') from ç
the B<216>had<193>ra<207>yaka Upani<218>ad of the Yajurveda (1.4.10); ç
tat tvam asi (`You are That') from the Ch<193>ndogya Upani<218>ad ç
(6.8.7) of the S<193>maveda and ayam<193>tm<193> brahma (`This ç
<193>tman is Brahman') from the M<193><207><195><220>kya Upani<218>ad ç
(2) of the Atharvaveda.
@NT = Mah<193>v<193>kyopani<218>ad
This is one of the minor Upani<218>ads and is assigned to the Atharvaveda. ç
Thereare only twelve mantras, mostly inprose. Parts of this Upani<218>ad ç
are identical with the Puru<218>as<220>kta and the N<193>r<193>ya<207>opani<218>ad.
The fourfaced Brahm<193>, the creator, is the teacher here. Having ç
found a worthy disciple, he starts teaching this secret and sacred ç
knowledge to him, advising him to give it only to the pure soul, introvert ç
in nature and who pleases the teacher by devoted service.
There are two types of people in this world: those who consider this ç
world to be real and those who know that it is not real. The former, ç
entertaining desires and ambitions, take to the prav<216>ttim<193>rga, ç
the path of Vedic sacrifices and get into bondage. The latter, endowed ç
with the eye of wisdom, take to the niv<216>ttim<193>rga or the path ç
of renunciation, seek mok<218>a or liberation, realise Brahman and ç
become free even here and now.
This <193>tman (inside) which is the same as Brahman, is not darkness ç
but brilliant light. This is realised by the repetition of the Ha<221>samantra ç
(ha<221>sa<199> so'ham) by identifying the spirit in the sun with ç
one's own Self.
This realisation of the most brilliant <193>tman/Brahman cannot be ç
compared to sam<193>dhi  (perfect  concentration),  yoga-siddhi (perfection ç
in yoga) or manolaya (dissolution of the mind). It is actually an ç
experience of oneness with Brahman.
Verses 8 to 10 are identical with the verses 16 to 18 of the Puru<218>as<220>kta ç
and describe the God-vision of the perfected sage.
The eleventh verse describes the identity of the light of the sun ç
and the light of the <193>tman inside brought about through meditation ç
with Pra<207>ava or Om.
The last section (12th mantra or verse) gives the phala·ruti, the ç
benefits and results of studying this Upani<218>ad, which is the same ç
as the total destruction of sins and dissolution into Lord Vi<218><207>u.
@NT = mah<193>vedi
@N1 = (`the great altar')
Somay<193>gas†Vedic sacrifices wherein the oblation of the soma juice ç
is the most important rite†need a lot of space, time and preparation. ç
A special vedi (altar or platform) has to be constructed for performing ç
them. This altar is called `mah<193>vedi'.
It is laid out to the east of the usual place of the g<193>rhapatya ç
and <193>havan<200>ya fires. It is a trapezium measuring 36 steps ç
east to west, 30 (or 33) steps north to south on the west and 24 steps ç
north to south on the east. The area is marked by driving pegs on ç
the ground at the appropriate places.
It contains many places specially marked or reserved for various priests ç
and objects used in the sacrifice.
@NT = Mah<193>v<200>ra
@N1 = (`the great hero')
See <MS>HANUM°N.<D>
It is also the name of Vardham<193>na Mah<193>v<200>ra, the last of ç
the Jaina T<200>rtha<209>-karas.  See  <MS>VARDHAM°NA-MAH°V®RA<D>  for ç
details.
@NT = mah<193>v<200>ra
It is the name of an earthen pot in which milk for the pravargya rite ç
(See <MS>PRAVARGYA.<D>) is boiled. It is generally prepared by the ç
adhvaryu priest with lumps of clay as per the directions given in ç
the ·rautas<220>tras. It resembles a wooden cup. There may be one ç
main cup and two secondary ones.
@NT = mah<193>vrata
@N1 = (`the great observance')
This is a rite that is performed on the penultimate day of the Gav<193>mayana ç
sacrifice. (See <MS>GAV°MAYANA.<D>)
In this rite a cup of soma juice is offered with the chanting of the ç
mah<193>vrata-s<193>man, one of the well-known mantras of the S<193>maveda. ç
An animal is sacrificed for the deity Praj<193>pati.
Playing on the V<193><207>a or a harp by a br<193>hma<207>a, the udg<193>t<216> ç
priest sitting on a chair of the udumbara wood, the hot<216> priest ç
sitting on a pre<209>kh<193> or swing, a wordy duel between a br<193>hma<207>a ç
and a ·<220>dra as a part of the ritual, are some of the interesting ç
sidelights of this mah<193>vrata rite.
@SPACE1 = 
@NT = mah<193>yaj<210>as
@N1 = (`great sacrifices')
See <MS>PA<178>CA-MAH°YAJ<178>AS<D>.
@SPACE1 = 
@NT = mah<193>yoga
@N1 = (`The great [or final] yoga')
In certain aspects of <185>aivism (vide V<193>yav<200>ya Sa<221>hit<193> ç
7.2.37), five kinds of yoga are described. Out of these mah<193>yoga ç
is the last and the highest. In this state, union with <185>iva is ç
experienced wherein all other kinds of attractions and attachments ç
are transcended.
The various steps of yoga described by Pata<210>jali (200 <MS>B.<|>C.<D>) ç
are generally accepted here also.
@SPACE1 = 
@NT = Mahendra
@SPACE1 = 
It is one of the names of Indra, the king of the gods in heaven. (See ç
<MS>INDRA.<D>) It is also the name of a famous parvata or mountain, ç
mentioned in the epics andthe pur<193><207>as. It is one of the seven ç
Kulaparvatas or mountains making the boundaries of the Jamb<220>dv<200>pa, ç
the island on which Bh<193>ratade·a (India) is situated. Ten rivers ç
like the Tribh<193>g<193>, the Acal<193>, the T<193>mrapar<207><200> ç
and the Vimal<193> take birth here.
Para·ur<193>ma spent his last days here. Yudhi<218><219>hira, the ç
eldest of the P<193><207><195>avas had visited it while on a pilgrimage.
@NT = Mahe·vara
@N1 = (`the Great Lord')
`Mahe·vara' is one of the names and aspects of <185>iva.
Iconographical works describe him as wearing a ja<219><193>muku<219>a ç
(crown of matted hair), fair in complexion, adorned with the crescent ç
moon on the head and having four arms, holding para·u (axe) or <219>a<209>ka ç
(hammer) and m<216>ga (deer), the other two arms assuming the gestures ç
of abhaya (protection) and varada (bestowal of boons). Or he may be ç
shown as having tri·<220>la (trident) <195>amaru (hand-drum), kap<193>la ç
(skull-cup) and n<193>ga (a serpent). He has, of course, three eyes.
He may also be shown as riding his bull, along with his spouse P<193>rvat<200> ç
and the two sons, Ga<207>e·a and K<193>rttikeya.
Mahe·vara is also the name of a dharma·<193>stra writer who lived ç
around <MS>A.D.<D>1550. He is the author of a commentary on the ç
d<193>yabh<193>ga system of dividing property. (See <MS>D°YABH°GA.<D>)
@NT = M<193>he·varas<220>tras
@N1 = (`aphorisms of<R>ç
Mahe·vara [<185>iva]')
Grammar  is  the  science  of  any language. Greater its perfection, ç
more refined will be the language.
Indologists, especially those who are adepts in the Sanskrit language, ç
have opined that the A<218><219><193>dhy<193>y<200> of P<193><207>ini ç
(350<MS>B.<|>C.<D>) is the best grammar that any language has produced.
Hindu tradition believes that the letters of the Sanskrit alphabet ç
were given by Lord Mahe·vara or <185>iva himself to P<193><207>ini ç
by playing on his <195>amaru (small drum) fourteen times. Thus were ç
created the fourteen s<220>tras known as the M<193>he·varas<220>tras  embodying  all  the ç
alphabets.
These fourteen s<220>tras are:
<+>1. a-i-u<207>;
<+>2. <216>-<202>r-k;
<+>3. e-o<209>;
<+>4. ai-au-c;
<+>5. ha-ya-va-ra-<219>;
<+>6. la-<207>;
<+>7. <210>-ma-<209>-<207>a-na-m;
<+>8. jha-bha-<210>;
<+>9. gha-<195>ha-dha-<218>;
10. ja-ba-ga-<195>a-da-·;
11. kha-pha-cha-<219>ha-tha-ca-<219>a-ta-v;
12. ka-pa-y;
13. ·a-<218>a-sa-r;
14. ha-l.
These  s<220>tras  are  so  ingeniously composed that they can be ç
utilised for several grammatical processes.
The last letter in each of these fourteen s<220>tras is called `it' ç
and has to be omitted in the various grammatical processes. However, ç
they serve the purpose of indicating the letters included up to them. ç
For instance, ak means the letters a,i, u, <216>, <202>r, from ç
the first two s<220>tras.
In all, forty-two combinations are possible and have been used in ç
the original s<220>tras and commentaries.
These M<193>he·varas<220>tras are also known as Ak<218>aram<193>mn<193>y<200> ç
and Caturda·a-s<220>tr<200>.
See also <MS>A<186><187>°DHY°Y®<D> and <MS>P°ØINI.
@NT = M<193>he·var<200>
@N1 = (`spouse of Mahe·vara', `the Great Goddess or Mistress')
She is P<193>rvat<200>, the feminine counterpart of Mahe·vara <185>iva. ç
She is shown as fair-complexioned, with three eyes and four arms. ç
She wears a crown of hair (ja<219><193>-muku<219>a) and is bedecked ç
with all ornaments. She carries the battle-axe (para·u) and the deer ç
(m<216>ga) in two hands and shows  the  hand-poses  of  protection ç
(abhaya) and giving boons (varada) with the other two. She rides on ç
a bull (Nandi).
@NT = Mah<200>dhara
It is very difficult to understand the Vedas, not only because of ç
their archaic language but also because they are closely associated ç
with a system of rituals with which we are not at all familiar.
Out of the several commentators on the Vedas, Mah<200>dhara also is ç
one. He might have lived in the 16th century and probably composed ç
his commentary, the Vedad<200>pa on the M<193>dhyandina Sa<221>hit<193> ç
of the <185>ukla Yajurveda around <MS>A.<|>D.<D> 1587.
Mah<200>dhara was a resident of K<193>·<200>. In his commentary he ç
has been influenced by Uva<219><193>c<193>rya (11th century <MS>A.<|>D.<D>) ç
an earlier commentator on the same work, to a great extent. However, ç
his explanations are more detailed. He quotes profusely from the ·rautas<220>tras.
He has another work also to his credit, the Mantramahodadhi, a work ç
on the tantras.
@SPACE = 
@NT = Mahi<218><193>sura
@N1 = (`the buffalo-demon')
@SPACE1 = 5
See <MS>DEV®M°H°TMYA.
@SPACE = 
@NT = M<193>hi<218>mat<200>
@SPACE1 = 
The city of M<193>hi<218>mat<200> (now identified with the O<209>k<193>ra-M<193>ndh<193>t<193> ç
island in the river Narmad<193>, 64 kms. or 40 miles from the modern ç
city of Indore in Madhya Pradesh) has been mentioned not only in the ç
epics but also in the pur<193><207>as. It was the capital of the powerful ç
king K<193>rta-v<200>ry<193>rjuna who had once humbled the mighty ç
R<193>va<207>a (the king of La<209>k<193>) himself. The sage Para·ur<193>ma ç
attacked and killed K<193>rtav<200>ry<193>rjuna at M<193>hi<218>mat<200> ç
lateron.
It was also the capital of Da·<193>·va, a son of the famous king Ik<218>v<193>ku.
Sahadeva, the last of the P<193><207><195>ava heroes, is said to have ç
conquered the king N<200>la who was reigning at M<193>hi<218>mat<200> ç
at that time.
@SPACE = 
@NT = maitr<193>varu<207>a
@N1 = (`belonging to Mitra and Varu<207>a')
@SPACE1 = 
A Vedic sacrifice needs four principal priests:  hot<216>,  adhvaryu,  udg<193>t<216>  and ç
brahman.
Each one of these can have three assistants, taking the total number ç
to sixteen, which is the maximum.
Maitr<193>varu<207>a is an assistant priest attached to the hot<216>, ç
the first of the four major priests (who are sometimes called `mahartvij'). ç
His duty is to recite the hymns to the Vedic deities Mitra and Varu<207>a ç
at the pr<193>tassavana or morning pressing of the soma juice. He ç
also gives instructions, sometimes, to other priests.
He is associated with pa·ubandha sacrifices†sacrifices involving the ç
immolation of pa·us or animals†also.
@NT = Maitr<193>ya<207><200>ya Sa<221>hit<193>
The Sa<221>hit<193> part of the K<216><218><207>a Yajurveda is said ç
to have had 85 ·<193>kh<193>s or recensions. However, only four are ç
available now, out of which the Maitr<193>ya-<207><200>ya Sa<221>hit<193> ç
is the second. It is a mixture of prose and verses. It has 2144 mantras ç
out of which 1701 have been borrowed from the <184>gveda itself. ç
Some of its mantras find a place in the K<193><219>haka and Taittir<200>ya ç
Sa<221>hit<193>s also.
This Sa<221>hit<193> has four k<193><207><195>as or books, each divided ç
into prap<193><219>hakas or subsections.
The following are the contents:
1.<+>Prathama or °dima K<193><207><195>a: It has eleven prap<193><219>hakas. ç
Some Vedic sacrifices like Dar·ap<220>r<207>am<193>sa, C<193>turm<193>sya ç
and V<193>japeya are described here.
2.<+>Dvit<200>ya or Madhyama K<193><207><195>a: This contains thirteen ç
prap<193><219>hakas dealing with some k<193>mye<218><219>is (desire-motivated ç
sacrifices), R<193>jas<220>ya and Agniciti (rite of piling the fire-altar).
3.<+>T<216>t<200>ya or Upari K<193><207><195>a: This comprises sixteen ç
prap<193><219>hakas. Sacrifices likethe A·vamedha and Sautr<193>ma<207>i ç
are described here.
4.<+>Caturtha or Khila K<193><207><195>a: Containing fourteen prap<193><219>hakas, ç
this section deals with many important and necessary accessories and ç
rites connected with the sacrifices described in the other three sections.
@SPACE = 
@NT = Maitr<193>ya<207><200>ya Upani<218>ad
@SPACE = 
The Upani<218>ads are a treasure-house of spiritual wisdom. One of ç
the more ancient Upani<218>ads assigned to the period 2000 <MS>B.C.<D> ç
but not classed among the major ones is the Maitr<193>ya<207><200>ya ç
Upani<218>ad (also known as the Maitr<200> Upani<218>ad) since ç
it was originally taught by the sage Maitri and belongs to the Maitr<193>ya<207><200>ya·<193>kh<193> ç
(·<193>kh<193> = recension) of the K<216><218><207>a Yajurveda.
The longer version as available now has seven prap<193><219>hakas ç
or chapters and 73 mantras, both in prose and in poetry.
The Upani<218>ad starts with the story of the king B<216>hadratha ç
who renounced his kingdom and did severe austerities to realise the ç
<193>tman. A sage, <185><193>k<193>yanya by name, came to his place ç
whereupon the king fell at his feet and begged him to teach about ç
the °tman. Being pleased with his earnest entreaties, the sage started ç
teaching him.
The V<193>lakhilyas, the tiny sages, had got this wisdom from Kratu ç
Praj<193>pati and the sage Maitr<200> taught the same to <185><193>k<193>yanya.
The various and varied teachings of this Upani<218>ad may be summarised ç
as follows:
The <193>tman, though encased in the body, is really free. This <193>tman ç
is full of many blessed qualities and enlivens the body with consciousness. ç
The whole creation has emerged out of Praj<193>pati (the Lord of creatures). ç
In this body there are two selves, the j<200>va (individual Self) ç
and the para (Supreme Self). The Para or Brahman is attained by vidy<193> ç
(knowledge), tapas (austerity) and cint<193> (meditation). There are ç
several gods like Agni (fire), V<193>yu (air), °ditya (sun), and the ç
trim<220>rtis (Brahm<193>, Vi<218><207>u and Rudra); but they are ç
all manifestations of the same Brahman.
The other topics dealt with are: Pra<207>ava or O<209>k<193>ra; the ç
three worlds bh<220><199>, bhuva<199> and suva<199>; gist of the G<193>yatr<200> ç
mantra; taking food compared to a sacrifice; importance of time as ç
a cosmic element; some methods of yoga which are similar to the ones ç
described in the Yogas<220>tras of Pata<210>jali (200 <MS>B.<|>C.<D>); ç
description of the muktapuru<218>a or the liberated person.
Mentioning of the kings of the Solar and the Lunar dynasties, a knowledge ç
of astronomy, familiarity with the S<193><209>khyan metaphysics and ç
an indication about the existence of the fine-arts like drawing anddramaturgy†these ç
are some of the specialities noted in this Upani<218>ad.
@SPACE = 
@NT = Maitreya
@N1 = (`son of Mitr<193>')
@SPACE = 
One of the well-known sages mentioned in the epics and the pur<193><207>as, ç
he was the son of Kau<218><193>rava (or Tu<218><193>rava) and Mitr<193>. ç
On hearing that the P<193><207><195>avas were banished to the forest, ç
he advised Dh<216>tar<193><218><219>ra (the blind king and the father ç
of the Kauravas) to make peace with them. Duryodhana (the eldest of ç
the Kauravas) patted his own thighs out of arrogance which enraged ç
the sage who cursed him to die due to broken thighs.
The Vi<218><207>upur<193><207>a  was  taught to Maitreya by the ç
sage Par<193>·ara (father of the famous Vy<193>sa).
The sage Baka-D<193>lbhya (vide Ch<193>ndogya Upani<218>ad 1.12.1) ç
was also known as Maitreya.
Maitreya is prominently mentioned in the Bh<193>gavata also.
@NT = Maitrey<200>
The B<216>had<193>ra<207>yaka Upani<218>ad (2.4 and 4.5) has immortalised ç
Maitrey<200> by depicting her as a woman of high spiritual aspirations ç
who cared more for mok<218>a or emancipation than for worldly wealth.
She was the first wife of the great sage Y<193>j<210>avalkya, the ç
second being K<193>ty<193>yan<200>.
When   Y<193>j<210>avalkya   decided   to renounce worldly life and ç
take to the monastic life, he called both of them and announced his ç
decision, not only about his leaving the house as a recluse but also ç
about the dividing of his property between them. Though K<193>ty<193>yan<200> ç
was happy with getting her share of the property, Maitrey<200> was ç
more interested in that for the sake of which her husband was renouncing ç
the world. On hearing that he was doing so for attaining mok<218>a ç
or liberation from transmigratory existence, she begged him to teach ç
the same to her also, rejecting the other offer of worldly wealth ç
and possessions.
Then follows a long discourse by Y<193>j<210>avalkya on the existence ç
and attainment of the <193>tman, for whose sake only, people love ç
one another.
These two sections of the Upani<218>ad† 2.4 and 4.5†are known as Maitrey<200> ç
Br<193>hma<207>a.
See also <MS>Y°J<178>AVALKYA.<D>
@NT = maitr<200>
@N1 = (`friendship')
The Vedic sages while recognising the existing natural divisions of ç
the society also prescribed some s<193>manya dharmas or common virtues ç
to be practised by all the human beings irrespective of their <193>·rama ç
or var<207>a, thus contributing to greater peace and harmony in the ç
society. Some of these are: ahi<221>s<193> (non-violence), satya(truth), ç
asteya (non-stealing), k<218><193>nti (forbearance) and so on.
One such common virtue is maitr<200> or an attitude of friendship ç
towards all (vide Brahmapur<193><207>a 114.16-18).
Pata<210>jali (200 <MS>B.<|>C.<D>) in his monumental work, the Yogas<220>tras ç
considers the cultivation of maitr<200> or an attitude of friendship ç
towards those who are happy will help in attaining greater control ç
over one's mind (vide s<220>tra 1.33).
@NT = makara
@N1 = (`that which harms human<R>ç
beings')
Makara  is  a  mythological  sea- monster. It is generally represented ç
with the tail of a fish and the trunk of an elephant. Since its representation ç
is seen even in the B<193>rhut st<220>pa (1st century <MS>B.C.<D>) ç
in Madhya Pradesh it can be taken as quite an ancient symbol.
In iconographical works, it is often shown as the mount or vehicle ç
of the river-goddess Ga<209>g<193>.
In some sculptures makara is shown like a crocodile.
Vi<218><207>u is often shown as wearing ku<207><195>alas (ear-rings) ç
shaped like a makara. Hence he is called `Makaraku<207><195>aladhara', ç
`the wearer of ear-rings shaped as a makara'.
Sometimes <185>iva is also shown as wearing it, but only on one of ç
the ears, the other ear having patra or a leaf as the ornament.
The tenth r<193>·i or zodiacal sign is also known as Makara.
@SPACE = 
@NT = Makara Sa<209>kr<193>nti
@SPACE = 
An important Hindu festival, connec-ted not only with bathing (especially ç
during Kumbhamelas) but also with the harvest season, is Makara Sa<209>kr<193>nti ç
(or Uttar<193>ya<207>a Pu<207>yak<193>la). Sa<209>kr<193>nti means ç
`the (apparent) passage of the sun from one r<193>·i (sign of the ç
zodiac) to the next following one' and hence the r<193>·i in which ç
the sun enters is designated as the Sa<209>kr<193>nti of the name, ç
like Me<218>a Sa<209>kr<193>nti, V<216><218>abha Sa<209>kr<193>nti, ç
and so on. However, out of these, Makara Sa<209>kr<193>nti, (which ç
usually falls generally on January 14) from which the northern journey ç
(uttar<193>ya<207>a) starts and Kark<193><219>aka Sa<209>kr<193>nti ç
(generally occurring on July 16) from which the southern journey (dak<218>i-<207><193>yana) ç
starts are considered as more important and auspicious.
Sa<209>kr<193>nti is sometimes deified and identified with Durg<193> ç
herself.
The `pu<207>yak<193>la' (auspicious time) in a Sa<209>kr<193>nti is ç
generally spread over 16 gha<219>ik<193>s (6 hours and 24 minutes), ç
8 gha<219>ik<193>s on either side of the actual moment of crossing ç
of the sun from the previous r<193>·i into the next. This time is ç
to be used for fasting, japa and d<193>na (giving gifts) only and ç
not for anything else.
The rites prescribed for Makara Sa<209>kr<193>nti are bath in a holy ç
river like the Ga<209>g<193>, tarpa<207>a or offerings with water ç
to gods and manes, fasting, homa (oblations into a sacred fire) and ç
gifts to worthy br<193>hma<207>as and other deserving persons.
In Tamil Nadu, the Makara Sa<209>kr<193>nti is a harvest festival ç
and is called Po<209>gal. Po<209>gal is a kind of sweet preparation, ç
made out of sugar or jaggery, rice, ghee and milk. It is prepared ç
from the newly harvested crops and offered to the Sun-god. The day ç
prior to the Po<209>gal day, is called Bhogi. It is a day dedicated ç
to changing the old articles in the house for the new (especially ç
old clothes) and consigning them to flames. The day after the Po<209>gal ç
day is reserved for the observance of the `Cattle Day' with bull-fights ç
or taming the wild bulls by the strong young men of the village.
In Karnataka, exchanging of sesame preparation (called e<202><202>u) ç
and blocks of sugar (sakkare accu) is a pleasant social aspect of ç
the festival. Washing and decorating the cattle and making them jump ç
over a burning fire specially lit up for the occasion as a sort of ç
exorcising the evil spirits that may harm them is also a common feature.
See also <MS>KUMBHAMEL°.
@SPACE = 
@NT = mala
@N1 = (`impurity')
@SPACE = 
According to the P<193>·upata cult of <185>aivism, j<200>va, the bound ç
soul (technically called `pa·u') is fettered by three kinds of impurities ç
called malas. They are <193><207>ava-mala, m<193>y<200>yamala and ç
k<193>rmamala. With the help of yoga, the pa·u or the j<200>va can ç
get rid of them.
See under the respective titles as also <MS><185>AIVISM.<D>
@NT = malam<193>sa
@N1 = (`impure month')
See <MS>ADHIKAM°SA.<D>
@NT = mal<193>vaha
@N1 = (`that which brings impurity [to the mind]'; `sin')
P<193>takas or sins are of several types. `Mal<193>vaha' is the name ç
given to some minor sins like killing insects, stealing fruits and ç
flowers, eating things which might have come into contact with spirituous ç
liquors and so on.
Observing the C<193>ndr<193>ya<207>a for a month expiates such sins.
See <MS>C°NDR°YAØA<D> also.
@NT = M<193><202>av<200>ya, Madanmohan
@N1 = <R>ç
(<MS>A. D.<D> 1861-1946)
@EMERGENCY = Ever remembered as the founder of the well-known centre ç
of learning, the Ban<193>ras Hindu University (<MS>BHU<D>), Pa<207><195>it ç
Madanmohan M<193><202>av<200>ya was born in <MS>A.<|>D.<D> 1861 at ç
Allahabad in Uttar Pradesh (then known as the United Provinces). He ç
was the son of Brajn<193>th, who was himself a great scholar and author ç
in Sanskrit.
@EMERGENCY = After some education in traditional Sanskrit learning, ç
he studied in English schools and colleges ultimately getting a degree ç
in law. He worked as a teacher first and later practised law.
@EMERGENCY = Like many of his contemporaries, he too jumped into the ç
freedom movement. He was the president of the Indian National Congress, ç
four times†in 1909, 1918, 1932 and 1933.
@EMERGENCY = M<193><202>av<200>ya was a devout Hindu and was also ç
a great scholar. He was a powerful speaker in Hindi. He helped in ç
starting and running some important journals.
He was also closely associated with the Hindu Mah<193>sabh<193>, an ç
organisation started in 1915 to protect the interests of the Hindus.
@NT = m<193><221>sabhak<218>a<207>a
@N1 = (`eating of flesh')
M<193><221>sabhak<218>a<207>a, eating of flesh or meat, has been a ç
subject hotly discussed in the dharma·<193>stras. During the early ç
Vedic period, as also during the period of the Upani<218>ads, flesh-eating, ç
including beef, seems to have been quite common. It was a part of ç
the madhuparka usually offered to an honoured guest (vide °·val<193>yana ç
G<216>hyas<220>tra  1.24.25).  Apart  from  the k<218>attriya kings ç
even the sages like Y<193>j<210>a-valkya have been mentioned as consuming ç
meat (vide <185>atapatha Br<193>hma<207>a 3.1.2.21). Animals immolated ç
in sacrifices†like horse, ox, goat and ram†were cooked and eaten (vide ç
Aitareya Br<193>hma<207>a 6.8).
However, as the °ryans moved towards the Indo-Gangetic plains and ç
cultivation of food-crops picked up in momen- tum, eating of the flesh ç
of animals gradually reduced and was even looked down upon. The growth ç
of Jainism and Buddhism also delivered a powerful blow to this practice.
Development of the doctrine of ahi<221>s<193>, gradual replacement ç
of the Vedic sacrificial religion by the paur<193><207>ic modes of ç
worship and the Bh<193>gavata-cult, contri- buted to the disappearance ç
or minimisation of the practice of eating meat.
Protection of the cow, the roots of which are found even in the <184>gveda ç
(1.164.27; 4.1.6; 8.69.21), became an article of faith with the whole ç
Hindu society.
Now, even those who have been meat eaters for ages, have either given ç
it up or take it only occasionally and not daily.
@NT = m<193><221>s<193>h<193>ra
@N1 = (`meat as food')
@EMERGENCY = The food that a human being consumes may be sasy<193>h<193>ra ç
(vegetarian food) or m<193><221>s<193>h<193>ra (non-vegetarian food, ç
flesh or meat).
@EMERGENCY = Though m<193><221>s<193>h<193>ra was quite common in ç
the earlier ages, it was gradually superseded by sasy<193>h<193>ra ç
because the latter came to be considered as more s<193>ttvik and hence ç
more conducive to spiritual pursuits.
@EMERGENCY = The spread of Ved<193>ntic ideas as also Jainism and ç
Buddhism contributed not a little to this trend.
See also <MS>M°<189>SABHAK<186>AØA.
@NT = manana
@N1 = (`reflecting in the mind')
@EMERGENCY = This is the second of the three direct disciplines prescribed ç
for getting the knowledge of the °tman and its oneness with Brahman. ç
It is defined as constant thinking of Brahman, already heard from ç
the spiritual preceptor, strengthening it by logic which is in consonance ç
with the purport of Ved<193>nta.
@NT = manas
@N1 = (`that by which one thinks')
It is an aspect of the anta<199>kara<207>a or internal organ, responsible ç
of sa<209>kalpa or general thinking, including willing and vikalpa ç
or doubting. It is an evolute of the combined sattva-aspect of all ç
the five tanm<193>tras or primordial elements.
See also <MS>MIND.<D>
@NT = Manas<193>
@N1 = (`created by mind')
Manas<193> is the goddess controlling all the reptiles, especially ç
the snakes. Her worship is very common in Bengal and Assam.
The story goes that when the people of the world, unable to bear the ç
affliction created by snakes, approached the great sage Ka·yapa†whose ç
offsprings were these snakes†for succour, he created the goddess Manas<193> ç
by using his mental powers (manas = mind) as the presiding deity and ç
controller of the reptiles.
She pleased <185>iva and Vi<218><207>u through her severe austerities ç
and obtained several boons from them.
Jaratk<193>ru was her another name.
She was married to a sage whose name also was Jaratk<193>ru and gave ç
birth to a son, °stika by name. He later on succeeded in stopping ç
the sarpay<193>ga or serpent-sacrifice of the king Janamejaya, the ç
son of Par<200>k<218>it.
She is known by many other names such as Trijagadgaur<200>, <185>iv<193>, ç
Vai<218><207>av<200>, N<193>gam<193>t<193>, Vi<218>ahar<193>, M<216>tasa<210>j<200>van<200>, ç
Siddhayogin<200> and so on. Repetition of her twelve names is said ç
to give full protection against poisonous reptiles.
Her images show her as a goddess with two arms, one holding a snake ç
and the other in abhayamudr<193>. She may also be shown with four ç
arms and a seven-hooded snake as a parasol, along with her husband ç
(the sage Jaratk<193>ru) and her child °stika.
@NT = m<193>nasa-pratyak<218>a
@N1 = (`direct perception by the mind')
Perception of objects in order to get a knowledge about them is an ç
important topic discussed in the Indian philosophical systems. Normally, ç
the mind gets the direct knowledge of an object through the five organs ç
of knowledge or j<210><193>nendriyas. However, sometimes, a knowledge ç
can arise in the mind directly also. For instance, when we see a ç
rose from a distance, the mind can also comprehend its smell, from ç
previous experiences. This is called `m<193>nasa-pratyak<218>a'.
According to the Kum<193>rila's (<MS>A.<|>D.<D> 700) school of M<200>m<193><221>s<193> ç
philosophy, a person gets the knowledge of himself as the soul or ç
Self, different from the body, directly in his mind as the ``I''<192>consciousness. ç
This is termed in that school as `m<193>nasa-pratyak<218>a'.
See also <MS>YOGIPRATYAK<186>A.<D>
@NT = M<193>nas<193>ra
Architecture, town planning, building construction, iconography and ç
allied topics were well-known to the Hindus right from the most ancient ç
times. The epics and the pur<193><207>as contain innumerable references ç
to the same.
One of the most standard works containing a well-organised body of ç
this knowledge (called <185>ilpa·<193>stra) is the M<193>nas<193>ra ç
of an unknown author.
As available now, the book has 70chapters and 10,000 lines in Sanskrit. ç
Itgoes into great detail about all aspects of architecture, townplanning ç
and icono-graphy, including casting of images in metals. Sixteen types ç
of village and town plans are described.
The original work might have been composed during the Gupta period ç
(<MS>A.<|>D.<D> 320-525). The extant (redacted version) work probably ç
belongs to 11th to 15th centuries.
@NT = M<193>nasa-sarovara
@N1 = (`lake [that emerged out of Brahm<193>'s] mind or heart')
@SPACE1 = 
One of the most sacred places of pilgrimage for a Hindu is the mount ç
Kail<193>sa and the lake M<193>nasa-sarovara. The  four-faced  Brahm<193>  while  doing ç
penance in the Him<193>layas is said to have created it out of his ç
mind (or heart). Hence the name.
It is in Tibet, at a distance of 32kms. (20 miles) from the mount ç
Kail<193>sa. Several rivers like the Sindh<220> (Indus), Sutlej and ç
Brahmaputra originate from here. Its water is crystal clear and very ç
cold. It is 90 metres (300 ft.) deep. It abounds in swans and ducks. ç
There are eight ma<219>has or monasteries on its banks, some of them ç
containing the images of Hindu gods like K<193>l<200>.
It is situated at a height of 4500 metres (15,000 ft.) above the sea-level.
A bath in it is considered highly meritorious. Its actual circumference ç
is 89 kms. (55 miles). However, the route of circumambulation is 113 ç
kms. (70 miles).
Those who visit this lake, often undertake the circumambulation of ç
the mount Kail<193>sa also which takes about 2to3 days.
There is a twin lake called R<193>k<218>asa-t<193>l, where R<193>va<207>a ç
is said to have performed tapas (austerity) to please Lord <185>iva.
@NT = m<193>nasa-sn<193>na
@N1 = (`mental bath')
@SPACE1 = 
Before the performance of any ritua-listic act, taking sn<193>na or ç
a bath is compulsory. However, sometimes, due to some valid reasons ç
like illness, decrepitude (due to old-age) or non-availability of ç
facilities to take bath, it is not possible tofulfil this requirement. ç
Under such circumstances, the dharma·<193>stras have provided some ç
alternatives like mantra-sn<193>na and m<193>nasa-sn<193>na.
