In mantrasn<193>na one has to sprinkle a little water on the head ç
with the repetition of the mantra `<193>po hi <218><219>h<193> mayo ç
bhuva<199>....' (<184>gveda 10.9.1-3).
In m<193>nasa-sn<193>na, one has simply to repeat in the mind any ç
name of Lord Vi<218><207>u and feel that he has been purified by that ç
divine name.
See also <MS>SN°NA.
@NT = M<193>nasoll<193>sa
@N1 = (`that which exhilarates the mind')
There are two well-known works of this name.
The first is an exhaustive gloss (v<193>rttika) by Sure·vara (<MS>A.<|>D.<D> ç
800) on the famous hymn <185>r<200> Dak<218>i<207><193>m<220>rti ç
Stotra of <185>a<209>kara (<MS>A.<|>D.<D> 788-820). The total number ç
of ·lokas or verses on the ten verses of theoriginal is 367. It discusses ç
all aspects of Advaita Ved<193>nta and also tries to refuteother ç
schools like Ny<193>ya, Vai·e<218>ika, S<193><209>khya and <185>aiva. ç
There is also a detailed exposition of the mah<193>v<193>kya (the ç
great sentence or Vedic dictum) tat tvam asi.
ThisM<193>nasoll<193>sa has a Sanskrit commentary, M<193>nasoll<193>sa ç
V<216>tt<193>nta, by one R<193>mat<200>rtha (17th century <MS>A.<|>D.<D>). ç
This commentary explains the original hymn also.
The second one is a voluminous work on the dharma·<193>stra and allied ç
branches, by the C<193>lukyan king Some·vara III who ruled from <MS>A.<|>D.<D> ç
1126 to <MS>A.<|>D.<D> 1138. This work is also called Abhila<218>it<193>rtha- ç
Cint<193>ma<207>i. It has five books, each containing 20 chapters. ç
It deals with 100 different topics connected with the royal household ç
and the royal court.
Some of the subjects dealt with in this work are: general and religious ç
ethics; social service; marriage and rearing of children; making of ç
idols; private and inter-state  law;  architecture;  painting; astrology; ç
alchemy; music and musical instruments.
The original author himself has given his own commentary called Dharma-prad<200>pik<193>.
@NT = Ma<207>av<193><202>a M<193>muni
@N1 = (<MS>A.<|>D.<D> 1370-1443)
One of the prominent teachers of theVi·i<218><219><193>dvaita philosophy ç
and the <185>r<200>vai<218><207>ava sect, Ma<207>av<193><202>a M<193>muni ç
was born in <MS>A.<|>D.<D> 1370 at Tirukkuruh<220>r of Tamil Nadu. ç
His parents were T<193>tara<207><207>ar Araiyar and <185>r<200>ra<209>ga ç
N<193>cciy<193>r.
He was educated first by his father and later by two well-known teachers ç
of his times, Tiruv<193>ymo<202>i Pi<202><202>ai and Ki<195><193>mbi ç
N<193>yan<193>r. He thus became an expert in the Sanskrit scriptures ç
as also the Tamil lore of Vi·i<218><219><193>dvaita.
He settled down at <185>r<200>ra<209>gam. He was a householder at ç
first. Later on, he embraced sa<221>ny<193>sa (monastic life) receiving ç
the monastic vows from <185>a<219>hagopa J<200>yar.
He spent most of his time in giving religious discourses, writing ç
books and helping in building temples or renovating old ones.
He toured widely, visiting all the important places connected with ç
<185>r<200>vai<218><207>a-vism. He was a prolific writer mostly in ç
Tamil. Some of them are: commentaries on the important works of Pi<202><202>ai ç
Lok<193>c<193>rya (<MS>A.<|>D.<D> 1228-1327) such as <185>r<200>vacana-bh<220><218>a<207>a ç
and Tattvatraya; Pram<193><207>at- tira<219><219>u; Yatir<193>javi<221>·ati; ç
Upade·aratna-m<193>lai; °rtiprabandha and Tiruv<193>r<193>dhana-krama.
He trained eight disciples†three were sa<221>ny<193>sins and the rest ç
house- holders†and  appointed  them  as  the pontiffs of the several ç
Ma<219>has (religious centres) such as V<193>nam<193>malai Ma<219>ha, ç
Yatir<193>ja Ma<219>ha and others.
He emphasised the superiority of bhakti (devotion) to God and service ç
tothe society in one's personal life. Even members of the lower castes ç
were his disciples.
@NT = ma<207><195>ala
@N1 = (`a circular figure that<R>ç
embellishes')
The word `ma<207><195>ala' has been used in various senses in the ç
Hindu scriptures and allied works depending upon the particular field ç
of knowledge.
In the <184>gveda it is the name of the ten books or sections into ç
which it is divided, based on the subject content.
In the ritualistic field, it is a circular diagram containing squares ç
and triangles, generally prepared with coloured powders. When consecrated ç
it acts like a fence or border protecting the ritual from evil influences ç
and forces. The names of some of  the  ma<207><195>alas  are:  Sarvatobhadra, ç
Caturli<209>gabhadra, Pr<193>s<193>dav<193>stuma<207><195>ala, Hariharama<207><195>ala ç
and so on.
A Hindu temple when viewed from above, represents a ma<207><195>ala.
In the works on political science (artha·<193>stra or r<193>jya·<193>stra) ç
ma<207><195>ala is a part of a king's territory. A ma<207><195>ala ç
is made up of four de·as, each de·a containing 100 villages. In some ç
works, this definition has been reversed, making the ma<207><195>ala ç
a subdivision of de·a.
@NT = Ma<207><195>ala-br<193>hma<207>opani<218>ad
This is one of the minor Upani<218>ads assigned to the <185>ukla ç
Yajurveda. It was taught by °ditya, the Puru<218>a (being) in the ç
orb of the sun, to the sage Y<193>j<210>avalkya.
The Upani<218>ad has five br<193>hma<207>as or chapters, thirteen ç
kha<207><195>as or subsections and eightynine mantras, both in prose ç
and in poetry.
The first chapter starts with the story of the great sage Y<193>j<210>avalkya ç
approaching °ditya or the Sun-god (also called N<193>r<193>ya<207>a) ç
for the knowledge of the °tman. °ditya starts his teaching by describing ç
the a<218><219><193><209>gayoga (the yoga comprising eight steps) ç
leading to j<210><193>na or knowledge of Brahman (= °tman). Though ç
these eight steps appear to be the same as in the Yogas<220>tras ç
of Pata<210>jali (200 <MS>B.<|>C.<D>) they are not. Here yama has four ç
parts and niyama has nine. Items under these include forbearance of ç
the vagaries of nature, steadiness of mind, devotion to the spiritual ç
teacher, solitude, not desiring the fruits of action and self-control. ç
°sana is that posture of meditation wherein the mind can easily flow ç
towards Brahman. Fixing the mind on the <193>tman (the soul inside ç
oneself) as pure consciousness, after eliminating the mental waves ç
of sense- objects is dh<193>ra<207><193>. Seeing the <193>tman (pure ç
caitanya or consciousness) in all living beings continuously is dhy<193>na. ç
Forgetting oneself completely in this experience is sam<193>dhi.
@SPACE1 = 
This is followed by the enumeration of pa<210>cado<218>as or five ç
defects in an embodied being which are obstacles to mukti or liberation. ç
They are k<193>ma (lust), krodha (anger), ni··v<193>sa (unsteadiness ç
of breath), bhaya (fear) and nidr<193> (sleep). They have to be conquered ç
respectively by not making up one's mind, forgiveness, pr<193><207><193>y<193>ma ç
(breath-control), giving up the consciousness of duality and thinking ç
of the highest Truth.
Fixing the mind on the light in between the eyebrows along with some ç
other details is described next.
The j<200>va (individual soul) by following the disciplines described ç
here, detaches himself from all the 24 principles of prak<216>tiand ç
realises that he himself isParam<193>tman (the Supreme Self) in essence.
Thus ends the first chapter.
The second chapter starts with the questions by Y<193>j<210>avalkya ç
regarding some teachings in the last chapter which he has not grasped. ç
In reply, the Puru<218>a in the orb of the sun (who is the teacher ç
here) replies describing the °tman/Brahman which is extremely brilliant ç
and the cause of the five fundamental elements. This °tman, which ç
is also the final resting place of the universe after dissolution, ç
can be attained only by j<210><193>na (the path of knowledge leading ç
to its experience). Here a few techniques of yoga which are rather ç
difficult to comprehend, are described.
Next comes a description of Pra<207>ava (or O<209>k<193>ra) as identified ç
with Brahman and the absence of the bondage of karma in him who has ç
realised it.
The inner experience of a man of knowledge is next compared to a ritualistic ç
worship. For instance, renunciation of all actions is <193>v<193>hana ç
(inviting the deity to the place of worship). The continuous flow ç
of the mind in the form of Brahman is itself sn<193>na (bath) of the ç
deity. The realisation, `I am He' is itself namask<193>ra (salutation) ç
and so on.
@SPACE1 = 
Continuous meditation of Brahman in this manner†if practised by the ç
s<193>dhaka or the votary†ultimately leads to its realisation.
There is an interesting para here that shows the difference between ç
su<218>upti (deep-sleep) and sam<193>dhi (perfect concentration resulting ç
in the superconscious experience of the °tman) since the mind is dissolved ç
in both these experiences. In su<218>upti the mind is dissolved in ç
tamas (the basis of ignorance) and hence comes back with all its defects ç
intact. In sam<193>dhi, tamas is completely destroyed and the perception ç
of the world (as a real object) is gone. Hence, even after coming ç
out of sam<193>dhi, the realised soul does not see the world as a ç
real object but only as Brahman and as identified with himself.
Then comes a description of five states of consciousness. They are: ç
j<193>grat (waking state), svapna (dream state), su<218>upti (deep-sleep ç
state), tur<200>ya (the fourth state) and tur<200>y<193>t<200>ta (the ç
state beyond even the tur<200>ya).
The j<200>va or the bound soul, gradually progresses from the first ç
to the last state through experiences got over several lives.
Now comes a delineation of the path that leads to the transcending ç
of sa<221>s<193>ra (transmigration). This is the usual traditional ç
path consisting of approaching the spiritual teacher, giving up all ç
actions motivated by selfish desires, duly performing the prescribed ç
duties, acquiring the four well-known s<193>dhan<193>s (viveka, vair<193>gya ç
and so on), meditating on Brahman in the heart and realising the same.
The Upani<218>ad declares here that sa<209>kalpa (making up one's ç
mind to acquire and enjoy the objects of desire) is responsible for ç
bandha (bondage) and giving it up, leads to mok<218>a (liberation).
One who gives up sa<209>kalpa and sees the whole world as °tman/Brahman ç
is able to realise it in course of time and himself become that.
The third chapter which is short describes unman<200>bh<193>va and ç
amanaskatva. When the various pratyayas or mental waves are looked ç
upon as nothing but Param<193>tman, the Supreme Self, who is the final ç
or original cause of all, including Brahm<193>, Vi<218><207>u and ç
Rudra, and who is sporting in one's heart or intellect, then, the ç
effects of the indriyas or the senses on the mind are destroyed. Then ç
the mind will become absolutely steady like a lamp kept in a windless ç
place. This itself is aman<200>-bh<193>va (a state in which the mind ç
does not behave like the original fickle mind).
This is also unman<200>bh<193>va, a state of transcending the mind ç
and an experience of the bliss of Brahman.
The fourth chapter is very short. It describes the vyomapa<210>caka ç
or five kinds of <193>k<193>·as or space. They are: <193>k<193>·a, ç
par<193>k<193>·a, mah<193>k<193>·a, s<220>ry<193>k<193>·a and param<193>k<193>·a.
@SPACE1 = 
The ordinary physical space which is dark both inside and outside ç
is the first, the <193>k<193>·a. The par<193>k<193>·a has the fire ç
of deluge in it. The mah<193>k<193>·a is that tattva or principle ç
which is full of unlimited light. The s<220>ry<193>k<193>·a is brilliant ç
like the sun. And, the param<193>k<193>·a is the all- pervading and ç
indescribable light and is also full of bliss.
Here, the word <193>k<193>·a in the latter, four terms, should be ç
deemed to have been derived from the root-verb `k<193>·' (`to shine'). ç
They are states of increasing enlightenment, of the knowledge of the ç
°tman/Brahman. The last is the final state.
The last chapter also is very short. After describing how the mind ç
can be dissolved (manolaya) by detaching it from the world and directing ç
it towards the °dityapuru<218>a (who is Brahman), the text describes ç
how a paramaha<221>sa or an avadh<220>ta, the perfected being, lives ç
in the world. He is ever pure and detached. Hispurity and spiritual ç
greatness are capable of liberating one hundred and one generations.
On the whole it can be said that the Upani<218>ad, while not deviating ç
from the usual (core) teachings of the major Upani<218>ads, also gives ç
a lot of information about the esoteric teachings of Ha<219>hayoga ç
and R<193>jayoga.
@NT = Ma<207><195>ana Mi·ra
@N1 = (circa <MS>A.<|>D.<D> 750-800)
According to the traditional biographies of <185>a<209>kara (<MS>A.<|>D.<D> ç
788-820) like the <185>a<209>karavijaya of M<193>dhava-Vidy<193>ra<207>ya ç
(<MS>A.D.<D> 1350) Ma<207><195>ana Mi·ra was a disciple of the well-known ç
M<200>m<193><221>s<193> scholar Kum<193>rila Bha<219><219>a (8th century ç
<MS>A.<|>D.<D>). He was defeated by <185>a<209>kara in disputation ç
and became his disciple. After taking Sa<221>ny<193>sa, he was given ç
the name Sure·var<193>c<193>rya. His wife too became a sa<221>ny<193>sin<200> ç
disciple of <185>a<209>kara under the name Ubhayabh<193>rat<200>.
However, this has been disputed by the modern scholars. Since Ma<207><195>an<W1%20>a<D%0>Mi·ra ç
was the author of a well-known work on Advaita Ved<193>nta, the Brahmasiddhi, ç
it is possible that he too was a Ved<193>ntin, though holding views ç
different from those of <185>a<209>kara. According to these scholars, ç
Sure·var<193>c<193>rya was a different person whose original name ç
was Vi·var<220>pa.
The works attributed to Ma<207><195>ana† allon the M<200>m<193><221>s<193>†are: ç
Vidhiviveka, Bh<193>van<193>viveka, Vibhramaviveka and M<200>m<193><221>s<193>nukrama<207><200>.
Umbeka, a disciple of Kum<193>rila, has written a commentary on Bh<193>van<193>viveka.
@NT = ma<207><195>apa
In the works on Hindu architecture like the M<193>nas<193>ra, this ç
word (also spelt as ma<207><219>apa) is used in several senses. Generally ç
it means a detached building, a pavilion or an open hall, with a roof ç
supported on pillars, but without any wall-enclosure.
In temples, the small corridor in front of the garbhag<216>ha (santcum) ç
is called ·ukan<193>s<200> or ardhama<207><195>apa or mukha-ma<207><195>apa. ç
The general pavilion or hall is called ma<207><195>apa or n<216>ttama<207><195>apa ç
whichis used for congregational religious acts like singing, dancing ç
or religious discourses.
The ma<207><195>apa should be built to the north or the east of the ç
temple.
@NT = Mandara
When the devas (gods) and d<193>navas (demons) wanted to churn the ç
ocean of milk, k<218><200>ras<193>gara, to get am<216>ta or ambrosia, ç
they are said to have used the Mandara (or Mand<193>ra) mountain as ç
the churning rod. Vi<218><207>u supported the mountain on his back, ç
in his incarnation as K<220>rma or the tortoise.
Mandara  mountain  is  sometimes enumerated  among  the  seven  `Kula- ç
parvatas,' mountains that act like the borders of the islands of this ç
earth.
A hill situated about 50 kms. (30miles) south of Bhagalpur in Bihar ç
has been identified with the Mandara of the pur<193><207>as.
@NT = M<193><207><195>avya
See <MS>AØIM°Ø£AVYA.<D>
@NT = M<193>ndh<193>t<216>
M<193>ndh<193>t<216> was a great king. He was the son of the king ç
Yavan<193>·va. He got this name because as the new born baby he was ç
sustained by drinking nectar oozing out of Indra's thumb. (Indra is ç
said to have remarked, `m<193>m dh<193>syati,' `He will suck my thumb').
His wife was Bindumati. Purukutsa, Ambar<200><218>a and Mucukunda ç
(all of whom proved to be great kings and devotees of God) were his ç
sons.
He successfully performed one hundred A·vamedha and R<193>jas<220>ya ç
sacrifices.
He is said to have fought Lava<207><193>sura and was killed by him.
@NT = Ma<207><195>odar<200>
See under <MS>R°M°YAØA.<D>
@NT = M<193><207><195><220>kyak<193>rik<193>
The M<193><207><195><220>kya Upani<218>ad belonging to the Atharvaveda ç
is the shortest of the ten Upani<218>ads considered as the major ones. ç
It has the unique distinction of a detailed exposition by two stalwarts:† ç
<185>a<209>kara (<MS>A.D.<D>788-820) and his teacher's teacher, ç
Gau<195>ap<193>da (7th century <MS>A.<|>D.<D>).
Gau<195>ap<193>da (about whom we know next to nothing) (See <MS>GAU£AP°DA.<D>) ç
wrote a detailed commentary on this Upani<218>ad, in the form of K<193>rik<193>s ç
(explanatory verses). His work is now well-known as the  M<193><207><195><220>kyak<193>rik<193>.  °gama·<193>stra  is ç
another name by which also it is known.
Though, apparently, this K<193>rik<193> is a commentary on the M<193><207><195><220>kya ç
Upani<218>ad, in reality, it is much more than that. It looks as ç
though Gau<195>ap<193>da has used this Upani<218>ad as a means, to ç
expound his own brand of Advaita Ved<193>nta. Some people even go ç
to the extent of not granting the status of an Upani<218>ad to the ç
M<193><207><195><220>kyopa-ni<218>ad and dub it as the creation ç
of Gau<195>ap<193>da himself!
The M<193><207><195><220>kyak<193>rik<193> has a total of 215 verses ç
divided into four prakara<207>as or sections. They are:
1. °gama-prakara<207>a (29 verses)
2. Vaitathya-prakara<207>a (38 verses)
3. Advaita-prakara<207>a (48 verses)
4. Al<193>ta·<193>nti-prakara<207>a (100 verses)
@SPACE1 = 
The °gamaprakara<207>a is a commentary  on  the  entire  M<193><207><195><220>kyopani<218>ad ç
dividing it into four parts. The explanatory K<193>rik<193>s are interspersed ç
here and there as follows: K<193>rik<193>s 1 to 9 after the sixth ç
mantra of the Upani<218>ad; K<193>rik<193>s 10 to18 after the seventh ç
mantra; K<193>rik<193>s 19 to23 after the eleventh mantra and the ç
rest, K<193>rik<193>s 24 to 29, after the last (the twelfth) mantra.
The otherthree prakara<207>as are entirely independent expositions ç
of Advaita Ved<193>nta from various angles.
<185>a<209>kara has commented upon all the K<193>rik<193>s also, apart ç
from the Upani<218>ad itself.
The Vaitathyaprakara<207>a deals with the Vaitathya or unreality ç
of the world by analysing the three states of consciousness.
The Advaitaprakara<207>a attempts to establish advaita (viz., that ç
Brahman is the one and only Reality) through yukti or logic.
The Al<193>ta·<193>ntiprakara<207>a, the longest of the four sections, ç
refutes 35 schools of philosophy that existed during Gau<195>a-p<193>da's ç
time, using the famous example of al<193>ta or a lighted torch, which, ç
when rotated, appears as a circle of fire, though no such circle really ç
exists. In the same way, the dvaitaprapa<210>ca or the world of duality ç
is only an appearance and not real.
Some of the more important concepts given by Gau<195>ap<193>da in ç
this work may now be mentioned briefly.
Analysingtheavasth<193>traya (See <MS>AVASTH°TRAYA.<D>) or the three ç
states of consciousness†j<193>grat (waking state), svapna (dream state) ç
and su<218>upti (deep-sleep state)†Gau<195>ap<193>da makes an important ç
point: It is only in the waking state that the dream and the deep-sleep ç
states are negated. However, from the standpoint of the tur<200>ya ç
(the `fourth' state) which is the eternal `waking state' in the <193>tman, ç
even the so-called waking state also is filled with the darkness of ç
ignorance! Compared to this, all the three states are actually the ç
night of ignorance.
@SPACE1 = 
`Aj<193>ti' or `non-birth' is another concept which is peculiar to ç
this work. (See <MS>AJ°TIV°DA<D> for details.) Since Brahman alone ç
is real and all other objects† whether it is this world or the j<200>vas ç
(living beings)†are only appearances, there is no question of any ç
`birth' (j<193>ti = birth) or creation of this world at all. Though ç
the scriptures have described s<216><218><219>i or creation, they ç
have not declared it to be real!
However, following the beaten track of tradition and as a concession ç
(out of compassion) to the ordinary s<193>dhakas (spiritual aspirants) ç
Gau<195>ap<193>da accepts pra<207>avop<193>san<193> (meditation on ç
°tman/ Brahman, with the help of Pra<207>ava or O<209>k<193>ra) and ç
explains the procedure in detail.
Another special term used in this work is `aspar·ayoga'. It is the ç
same as the experience of unalloyed bliss of the Self (°tman/Brahman) ç
wherein there is no spar·a or contact of the senses with their objects, ç
but only with the Self (a = not; spar·a = contact; yoga = union).
The K<193>rik<193> ends with a definition of mok<218>a or liberation ç
as just a rediscovery ofone's true nature asthe°tman (=Brahman) ç
and a brief description of the man of liberation.
°nandagiri (15th century <MS>A.<|>D.<D>) has written a gloss on the ç
commentary of <185>a<209>kara,elucidating further, wherever necessary.
See <MS>M°Ø£<188>KYA UPANI<186>AD<D> also.
@NT = M<193><207><195><220>kya Upani<218>ad
This is the smallest of the ten Upani<218>ads and belongs to the Atharva-veda. ç
It has only twelve verses, all in prose. But, it has been considered ç
as basic to the principles of Ved<193>nta, especially the Advaita ç
Ved<193>nta. An analysis of the three states of consciousness viz., ç
j<193>grat (wakefulness), svapna (dream) and su<218>upti (deep-sleep) ç
and relating them to the three syllables a, u and m of Pra<207>ava ç
or O<209>k<193>ra and establishing the tur<200>ya (literally `the ç
fourth') as the highest reality is the speciality of its teaching.
A brief account of the twelve verses may now be given here:
Verse 1: All this (the manifested world) is the syllable Om. Whatever ç
exists in time†the past, the present and the future†as also whatever ç
is beyond it, that too is Om.
Verse 2:<+>All this is verily Brahman. This <193>tman (the individual ç
soul) is Brahman. He has four aspects.
Verse 3:  Vai·v<193>nara,  the  <193>tman associated with the waking ç
state, is the first aspect. He cognises external objects. He has seven ç
limbs like the sun, the air and the earth. He has nineteen mouths ç
such as the sense-organs and the motor-organs. He experiences gross ç
material objects.
Verse 4: Taijasa, the second aspect is the <193>tman associated ç
with the dream state and cognises internal objects. He too has seven ç
limbs and nineteen mouths and experiences the subtle objects.
Verse 5: The pr<193>j<210>a is the third aspect. He is the same ç
<193>tman associated with the deep-sleep state, where there are neither ç
dreams nor desires. He is a solid mass of cognition, full of bliss ç
and enjoys bliss.
Verse 6: He is the lord of all, the knower of all and the inner ç
controller. He is also the origin of this world.
@SPACE1 = 
Verse 7: The tur<200>ya is the fourth aspect of the <193>tman as ç
it were. He is different from the other three. He is indescribable ç
since he is beyond the ken of all the senses. He is one without a ç
second. He is the °tman (Universal Self) who should be known or realised.
Verse 8: From the standpoint of the whole letter, the <193>tman ç
is Om. The three syllables of Om are a, u, and m.
Verse 9: Vai·v<193>nara is the first syllable a. One who knows him ç
thus will be able to attain all desires.
Verse 10:  Taijasa  is  the  second syllable u. One who knows him ç
thus increases his knowledge. In his family only knowers of Brahman ç
(= °tman) are born.
Verse 11: Pr<193>j<210>a is the third syllable, m. He who knows ç
this, knows all and gets merged in all.
Verse 12: The Tur<200>ya†the `fourth' as it were†is beyond all the ç
three syllables. He it is into whom the world dissolves.He is one, ç
beyond all dualities, and the very personification of auspiciousness. ç
One who realises him, attains his own real self.
One of the four Mah<193>v<193>kyas or `great sentences', accepted ç
by the Advaita Ved<193>ntic tradition, viz., ayam <193>tm<193> brahma, ç
occurs in the second verse.
Proving the existence of the <193>tman as the pure conscious spirit, ç
different from the body-mind complex, though existing in it or even ç
identified with it, and, equating it with Brahman, the Absolute, the ç
cause of and the spirit behind the universe is the main purpose of ç
this Upani<218>ad. The unique method used for this is the analysis ç
of the three states of consciousness.
@SPACE1 = 
There is a long expository treatiseon this Upani<218>ad called K<193>rik<193> ç
or M<193><207><195><220>kya-k<193>rik<193> by Gau<195>ap<193>da ç
(7th Century <MS>A.<|>D.<D>), teacher's teacher of <185>a<209>kara ç
(<MS>A.<|>D.<D> 788-820).
@NT = ma<209>gala
@N1 = (`the auspicious')
See <MS>A<186><187>AMA<177>GALAS.<D>
The planet mars, one of the nine mentioned in the works on astrology ç
is also known as Ma<209>gala. Its other names are: A<209>g<193>raka, ç
Kuja, Bhauma, °vaneya, Lohit<193><209>ga and Kr<220>r<193>k<218>a. ç
It is supposed to rule over the colour red and ruled over by God K<193>rttikeya ç
or Subrahma<207>ya and the element of fire. It is said to be a malefic ç
planet but give beneficial results in southern direction. Its nature ç
is that of a k<218>attriya. Its residence in the body is the marrow ç
whereas outside, it lives in the fire-place.
Actually, these details are useful in astrological predictions.
@NT = ma<209>galas<220>tra
@N1 = (`the auspicious thread')
Viv<193>ha or marriage is considered as an important sa<221>sk<193>ra ç
or sacrament in the life of every Hindu. One of the primary steps ç
in this sacrament is the tying of the ma<209>galas<220>tra by the ç
bridegroom round the neck of the bride, which she is expected to wear ç
as long as her husband is alive. This rite comes after the saptapad<200>. ç
(See <MS>SAPTAPAD®.<D>) The s<220>tra generally consists of a string ç
with golden and other beads including a coin-shaped amulet.
Though this is considered as one of the most important aspects of ç
the marriage ritual now, it has not been mentioned inthe earlier ç
dharma·<193>stra works. The <185>aunakasm<216>ti is the earliest ç
treatise that mentions it. The practice must have come into vogue ç
around <MS>A.<|>D.<D> 1000.
In some works, the tying of ka<209>ka<207>a (protective cord) by the ç
couple to each other's hands is mentioned as `ka<209>ka<207>abandhana'. ç
This cord itself is called ma<209>galas<220>tra.
@NT = ma<207>i
@N1 = (`gem')
Wearing of precious gems to ward off evil or diseases and to gain ç
health or a desired object seems to be an ancient practice. Even the ç
Atharvaveda (1.29.1 to6) mentions it.
Each of the gems recommended is supposed to have a perennial source ç
of one specific ray which is not exhausted even after wearing it constantly ç
for years.
These gems and the nine planets are believed to have some mysterious ç
connection.  Hence,  qualified  and  competent astrologers, by studying ç
the horoscope of a person suffering from a disease or upset by a calamity ç
can prescribe the particular gem to be worn on the body by which the ç
disease can be cured or calamity averted.
For instance, wearing of emerald can cure acidosis. Wearing of a red ç
coral can avoid accidents.
@NT = Ma<207>ika<207><219>han
See <MS><185>°ST°<D>.
@NT = M<193><207>ikkav<193>cagar
@N1 = (9th or 10th cent. <MS>A.D.<D>)
@EMERGENCY = If the ·iva·ara<207>as (servants of Lord <185>iva) and ç
the d<193>sas (servants of Lord Vi<218><207>u) spread the universal ç
cult of bhakti (devotion to God) in Karnataka, the N<193>yanm<193>rs  and  the  °<202>v<193>rs  (those ç
immersed in the love of God) did the same in Tamil Nadu.
@EMERGENCY = Among the sixty-three N<193>yanm<193>rs who were great ç
devotees of <185>iva, M<193><207>ikka-v<193>cagar was an important ç
person whose two great works Tiruv<193>sagam and Tirukkovai are ç
popular even today.
@EMERGENCY = Born of br<193>hma<207>a parents at Tiruva<195>uv<220>r ç
(near Madurai in Tamil Nadu) he became an adept in the know-ledge ç
of the scriptures, especially the <193>gamas. The P<193><207><195>yan ç
king, Arimarttanam by name, who had heard of his stupendous knowledge ç
and uncanny wisdom as well as impeccable character, appointed him ç
as his chief minister.
Once the king sent him on a mission to purchase imported Arab horses ç
from Tirupirend<220>r. However, M<193>nikkav<193>cagar met a great ç
<185>aiva saint (who was <185>iva himself), received spiritual instructions ç
and utilised the money given by the king for purchasing the horses, ç
to build a temple for <185>iva. The king jailed him for embezzlement ç
of funds. But by the grace of <185>iva he was released. He resigned ç
from his ministership and started roaming about as a minstrel of God. ç
He is said to have defeated a band of Buddhist scholars in public ç
debate at Cidambaram (Chidambaram).
Of his two works Tiruv<193>sagam is autobiographical and reveals ç
his spiritual struggles culminating in spiritual illumination.
The Tirukkovai depicts the longing of the soul for <185>iva, but ç
using erotic imagery.
@NT = ma<207>iprav<193><202>a
@N1 = (`jewel and pearls')
Tami<202>  and  Malay<193><202>am  are  two languages considered of ç
a Dravi<195>ian origin and  not  derived  from  or  related  to Sanskrit. ç
As Sanskrit became more and more popular, it also became a favourite ç
of the scholars. There seems to have arisen a need to integrate it ç
with Malay<193><202>am and Tami<202>, and, produce a new style of ç
composition. This came to be known as `ma<207>iprav<193><202>am' (ma<207>i ç
= jewel like ruby or diamond; prav<193><202>a = pearl), Malay<193><202>am ç
being the `ma<207>i' and Sanskrit being the `prav<193><202>am'.
The origin of this style is attributed to the poet Tolan in the court ç
of the king Kula·ekhara (circa 9th century <MS>A.<|>D.<D>).
L<200>l<193>tilaka, a grammar of Malay<193><202>am, has systematised ç
this style and has also evolved the necessary rules. It might have ç
been composed around the middle of the 15th century.
In this style of writing, Malay<193><202>am words and Sanskrit words ç
already present in the common language of the people have been fused ç
into one.
The ma<207>iprav<193><202>a literature is generally divided into two ç
styles, sande·a andcamp<220>. Unnan<200>l<200>sande·a composed ç
probably during <MS>A.<|>D.<D> 1315 is a typical work of the sande·a ç
group.
In the camp<220> works, the poetry part is in Sanskrit metres. The ç
prose part is in the style of Malay<193><202>am and Tami<202>.
The R<193>m<193>ya<207>a-camp<220> and the Bh<193>ratacamp<220> ç
are two important works of this class.
@SPACE1 = 
@NT = ma<207>ip<220>racakra
@SPACE1 = 
See <MS>CAKRAS.
@SPACE1 = 
@NT = ma<209>kig<200>t<193>
@N1 = (`song of [the sage] Ma<209>ki')
@SPACE1 = 
The Bhagavadg<200>t<193> (`Song of God') by its extraordinary beauty, ç
elegance and spiritual eminence, inspired the emergence of many other ç
g<200>t<193>s, most of them being in the Mah<193>bh<193>rata itself. ç
One such is this Ma<209>kig<200>t<193>. It is a part of the <185><193>ntiparva ç
(ch. 177, verses 5 to 54).
The sage Ma<209>ki purchased two oxen, yoked them and was taking them ç
to a field. It so happened that a camel lying on the road, suddenly ç
got up when the oxen had just approached it and started running with ç
the yoke on its neck and the two bullocks hanging! Having lost his ç
source of livelihood, Ma<209>ki developed vair<193>gya or dispassion ç
and taught this g<200>t<193> to his own mind.
The gist of the Ma<209>kig<200>t<193> can be given as follows:
The mind is full of desires. These desires can never be satiated. ç
A person takes a lot of trouble in acquiring wealth. But the accumulated ç
wealth tempts thieves and robbers who take it away, harming or even ç
killing its owner. Loss of wealth also generates intense suffering.
Hence one must destroy the seven enemies†k<193>ma (lust), krodha (anger), ç
lobha  (greed),  moha  (delusion),  mada (intoxication), m<193>tsarya ç
(jealousy) and aha<209>k<193>ra (egoism).
The best way to conquer desires is to stop sa<209>kalpa (deciding ç
to work for fulfilling the desire).
By attaining yoga (concentration of mind on Brahman) I will become ç
happy. Then you (= the mind) can never dupe me into sorrow and suffering!
See also <MS>BHAGAVADG®T°.<D>
@NT = Manmatha
@N1 = (`one who churns the mind')
Also known by other names such asMadana (one who intoxicates) and ç
Kandarpa (one who was arrogant towards Brahm<193> the creator), he ç
was born out of Brahm<193> himself as the personification of bewitching ç
(male) physical beauty. He got the boon that he could entice anyone ç
with lust. When he tried this power on Brahm<193> himself, creating ç
uncontrollable lust in him towards Sandhy<193>, his own daughter, ç
he cursed Manmatha to be reduced to ashes by <185>iva.
@SPACE = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
When this happened, he was restored to life again, by <185>iva himself ç
who was moved by the piteous wailings of Rati (Manmatha's wife) as ç
also the interventions of the gods.
His distinguishing features are the bow of sugarcane stalk, a bunch ç
of five kinds of flowers as arrows, fish as his flag-symbol and the ç
makara (mythical crocodile) as his carrier. Rati is his consort.
Actually Manmatha and Rati are the archetypes of physically perfect ç
man and woman. Manmatha is akin to Eros or Cupid.
@NT = manomayako·a
@N1-1 = (`the sheath of the mind')
The manas or mind, along with the pa<210>caj<210><193>nendriyas or ç
the five organs of knowledge, form the `manomayako·a' or the sheath ç
of mind. Like a sheath, it covers and hides the real nature of the ç
°tman or the Self. It is a part of the s<220>k<218>ma-·ar<200>ra (also ç
called li<209>ga-·ar<200>ra), the subtle body, the other two parts ç
being pr<193><207>amayako·a (sheath of vital airs) and vij<210><193>namayako·a ç
(sheath of intellect).
See <MS>PA<178>CAKO<185>AS.<D>
@NT = Manonman<200>
@N1 = (`one who makes our mind eager [to attain her]')
She is one of the aspects of the Divine Mother P<193>rvat<200> dear ç
to Sad<193>·iva, more common in South India. She is worshipped for ç
bh<220>ti (prosperity) and also for striking fear in the minds of ç
enemies.
Iconographical works describe her in various ways. The most common ç
description is that she is of the colour of the moon with a benevolent ç
appearance. She has four arms, holding a red and a blue lotus in two ç
hands, the other two being in varada and abhaya mudr<193>s. Sometimes, ç
a rosary is shown instead of the blue lotus.
Other works show her with five faces and ten arms carrying ·<220>la ç
(spear), <219>a<209>ka (hammer), p<193>·a (noose), a<209>ku·a (goad), ç
gha<207><219><193> (bell), fire and lotuses.
She may also be shown as surrounded by 46 <185>aktis and an equal ç
number of Kany<193>s (virgin-deities).
@NT = mantra
@N1 = (`that which protects when<R>ç
reflected upon')
One of the most widely used words in Sanskrit religious literature ç
is the word `mantra.' It is, etymologically speaking, defined as that ç
which protects (tra = to protect) when repeated and reflected upon ç
(man = to think, to reflect).
This word has two meanings: the poetical part of the Vedas and, the ç
names and syllables used to indicate or propitiate deities. The former ç
is Vedic and the latter is t<193>ntrik.
The Vedas are generally divided into two broad divisions: the Mantra ç
and the Br<193>hma<207>a. The Mantra part of the first three Vedas ç
is again classified as <216>k, yajus and s<193>man. The Br<193>hma<207>as ç
are in prose, deal with the details of sacrificial rites and quote ç
the appropriate mantras (sacred formulae) to be used in the rites.
In the Mantra section, a fourth category, the nigada, is sometimes ç
added. Nigadas are, strictly speaking, not mantras but instructions ç
uttered loudly by one priest to another, during a sacrificial rite.
There are several rules in the <185>rauta s<220>tras (See <MS><185>RAUTAS<188>TRAS.<D>) ç
about the recitation of the Vedic mantras.
The most famous of all the Vedic mantras which is popular and very ç
much in vogue even today is the G<193>yatr<200>-mantra.
The latter kind of mantras appear inthe earlier pur<193><207>as. ç
They extol the greatness of the pa<210>c<193>k<218>ar<200> or <218>a<195><193>k<218>ar<200> ç
(mantra of five or six letters nama··iv<193>ya and o<221> nama··iv<193>ya), ç
a<218><219><193>k<218>ar<200> (of eight letters†o<221> namo n<193>r<193>ya<207><193>ya) ç
and dv<193>da·<193>k<218>ari (of twelve letters†o<221> namo bhagavate ç
v<193>sudev<193>ya) mantras and a few others.
However it is the tantras or <185><193>kt<193>-gamas that developed ç
the art and science of the mantras, both extensively and intensively. ç
Various types of mantras for the various deities of the Hindu pantheon ç
along with different b<200>j<193>k<218>aras (See <MS>B®JAMANTRA<D>.) ç
and their usages have been dealt with in the well-known works like ç
the Prapa<210>cas<193>ra, <185><193>rad<193>tilaka and Mah<193>nirv<193><207>atantra.
For more details see under <MS>TANTRAS<D>.
@NT = Mantr<193>bhidh<193>na
See <MS>M°T<184>K°NIGHAØ<187>U.<D>
@NT = mantradra<218><219><193>
@N1 = (`seer of a [Vedic] mantra')
Vedas,  the  basic  scriptures  of Hinduism, are considered as `apauru<218>eya' ç
(not man-made), but as revelations of God Himself through certain ç
<216><218>is or sages. These sages only `saw' (d<216>· = to see) these ç
mantras and uttered them. Hence they came to be known as mantrad<216>k ç
or mantradra<218><219><193>.
Vasi<218><219>ha, V<193>madeva, Madhucchand<193>, Medh<193>tithi, ç
D<200>rghatamas, Asita Devala and Vi·v<193>mitra are some of these ç
sages.
There are at least 27 women sages also.
Before reciting a Vedic mantra, three things have to be stated. The ç
first is the <216><218>i or the sage to whom it was revealed. The ç
second is the chandas or the metre. The third is the devat<193> or ç
the deity to whom it is addressed.
@NT = Mantr<193>rth<193>bhidh<193>na
See <MS>M°T<184>K°NIGHAØ<187>U.<D>
@NT = Mantr<193>laya
Originally a small village called Ma<210>c<193>le, and now a well-known ç
place of pilgrimage, Mantr<193>laya is famous for its b<216>nd<193>vana ç
(See <MS>B<184>ND°VANA<D>) of the great sage and mystic R<193>ghavendrat<200>rtha ç
(<MS>A.<|>D.<D> 1595-1671). He is said to have entered into it while ç
still alive. (See <MS>R°GHAVENDRA- T®RTHA<D>.). It is situated on ç
the bank of the river Tu<209>gabhadr<193>, in the Kurnool district ç
of Andhra Pradesh at a distance of 93kms. (58 miles) from the railway ç
junction of Guntakal.
Apart from this b<216>nd<193>vana, there are three more, of other ç
saints.
An image of god V<193>yu (wind-god) as also a shrine for Ma<210>c<193>l<193>mbik<193> ç
(an aspect of P<193>rvat<200>) are the other attractions for the devotees.
There is a heavy rush of pilgrims throughout the year. Desires of ç
the devotees who serve the sage in the prescribed manner are fulfilled.
According to the local legends, this was the place where Prahl<193>da, ç
the great devotee of Lord Vi<218><207>u had worshipped thegoddess ç
Ma<210>c<193>l<193>mbik<193> and had also performed Vedic sacrifices.
The place is now well-developed with good arrangements for the benefit ç
of the devotees and pilgrims.
@NT = Mantrapu<218>pa
This is a short piece forming a part of the Taittir<200>ya °ra<207>yaka ç
(1.22.1 to 7). It is primarily used in the worship of S<220>rya (the ç
Sun-god) as also in S<220>rya-namask<193>ra. It is also used to offer ç
flowers at the end of ritualistic worship.
The sun, the moon and the stars (s<220>rya, candra and nak<218>atra) ç
appear to rise from the waters of the ocean for an onlooker. Hence ç
they have been called pu<218>pa or flowers of the water. One who knows ç
them as such reaps great benefits like having children and cows.
@NT = mantrasa<221>sk<193>ra
@N1 = (`refining of the<R>ç
mantra')
The tantras are a highly specialised literature dealing exclusively ç
and exhaustively with the mantras of the various deities of the Hindu ç
pantheon. Before these mantras are used for any purpose†sacred or ç
secular†they have to be purified ceremonially. This is called `mantra-sa<221>sk<193>ra'.
Mantrasa<221>sk<193>ra comprises ten rituals. They are: janana (extraction ç
of the letters of the mantra through a specially drawn drawing called ç
m<193>t<216>k<193>yantra); j<200>vana (writing the letters of the ç
mantra got from the process of janana, in the prescribed order and ç
doing japa of each letter preceded by O<221>, to infill it with life); ç
t<193><195>ana (striking each letter with sandal-water, repeating ç
`ya<221>'); bodhana (beating the letters of the mantra with red oleander ç
flowers [Nesium odorum] to the accompaniment of the syllable `ra<221>'); ç
abhi<218>eka (bathing the same letters of the mantra [written on a ç
metal plate as prescribed] with water using an a·vattha leaf [Ficus ç
religiosa] and the syllable `ra<221>'); vimal<200>kara<207>a (purifying ç
the mantra with the special formula `o<221> hraum' while contemplating ç
on it); <193>py<193>yana (satiating the letters of the mantra in water ç
in which ku·a grass or a flower is immersed, using the same mantra ç
[o<221> hraum] which is called `jyotirmantra'); tarpa<207>a (offering ç
libations of water to the mantra to the accompaniment of the same ç
jyotirmantra); d<200>pana (illuminating the mantra with the formula ç
`o<221> hr<200><221> ·r<200>m'); gupti (keeping the  mantra  as  a  great  secret  thus ç
protecting its power).
All these are highly esoteric in nature and should be done under the ç
expert guidance of a competent guru.
@NT = mantrasiddhi
@N1-1 = (`the potency of the mantra being fully roused')
Though a mantra received from a qualified guru in the traditional ç
manner has its potency, this has to be fully roused to make it effective ç
in the practical field.
One of the methods is pura·cara<207>a (See <MS>PURA<185>CARAØA<D> ç
for details.).
Sometimes, this process of pura·-cara<207>a may have to be repeated ç
two times more.
If the power is not roused even after this, then the s<193>dhaka or ç
the spiritual aspirant, under the direct guidance of the guru, has ç
to take to the sevenfold procedure starting with bhr<193>ma<207>a ç
and ending with d<193>hana (vide Mantrayogasa<221>hit<193> 67).
This procedure has to be directly learnt and practised under the guidance ç
of an adept in the field.
A simple method suggested by some of the pur<193><207>as is `ak<218>ara-lak<218>a-japa'. ç
It is the same as repeating the mantra as many lakhs of times as there ç
are letters in the mantra. For instance, to get mantrasiddhi in the ç
six-lettered mantra, `O<221> nama·-·iv<193>ya,' one has to repeat ç
it 6 lakh times.
@NT = mantrasn<193>na
@N1 = (`bathing through mantra')
See <MS>M°NASA-SN°NA<D> and <MS>SN°NA.<D>
@NT = Mantrayoga
@N1 = (`yoga through mantra')
The V<193>yav<200>ya Sa<221>hit<193> is an important work on <185>aivism. ç
It describes yoga as of five kinds. Mantrayoga is the first in the ç
series. It is that yoga in which, by the constant repetition of the ç
mantra imparted by the guru, the mental states become steady.
When this is associated with pr<193><207><193>-y<193>ma or breath-control, ç
it is called Spar·a-yoga. Spar·ayoga develops into Bh<193>vayoga when ç
mantrajapa or the repetition of the mantra stops automatically, leaving ç
only the bh<193>va or feeling. By further practice, the world appearance ç
in its various forms, disappears, thus leading to Abh<193>vayoga.
At the last stage of spiritual evolution union with <185>iva is attained. ç
This is Mah<193>yoga.
The eight steps of yoga described in the Yogas<220>tras of Pata<210>jali ç
(200 <MS>B.<|>C.<D>) are also included in this practice.
@NT = mantrin
@N1 = (`one who gives counsel')
@EMERGEN1 = See <MS>AM°TYA.<D>
@NT = Manu
@EMERGEN1 = See <MS>MANUSM<184>TI.<D>
@NT = Manus
@EMERGEN1 = See <MS>MANVANTARA.<D>
@NT = m<193>nu<218>a-li<209>ga
@N1KERN = (`·ivali<209>ga made by human beings')
@EMERGEN1 = Lord <185>iva is worshipped in the form of a li<209>ga, ç
an emblem with a rounded surface, cylindrical in shape. Li<209>gas ç
are classified into several varieties, of which the m<193>nu<218>a-li<209>ga ç
is also one. It is defined as a li<209>ga prepared by the m<193>navas ç
or human beings and worshipped by them.
The iconographical works give all the details needed to prepare such ç
a li<209>ga. The ritualistic processes for installing the li<209>ga ç
in a temple are given by the <185>aiv<193>gamas, religious texts dealing ç
with the worship of Lord <185>iva.
See <MS><185>IVALI<177>GA<D> for more details.
@NT = Manusm<216>ti
@N1 = (`the sm<216>ti of Manu')
The Manusm<216>ti†among the Hindu religious works†has the unique ç
distinction of being thoroughly misunderstood and even reviled, in ç
the modern days, especially in post-independence India. However, it ç
goes to the credit of Manu himself (4.176) that rules which cause ç
widespread resentment among the people, even if they are dharma (by ç
earlier standards), should be given up. This is akin to changing the ç
constitution if the people of a country so desire.
The extant Manusm<216>ti which compri-ses 12 adhy<193>yas or chapters, ç
has 2694 ·lokas or verses in the anu<218><219>ubh metre.
Scholars have battled for years to establish the identity and the ç
time of Manu, the author of this treatise. He iscertainly not one ç
of the 14 Manus (progenitors of mankind and rulers over the manvantaras) ç
mentioned in the epics and the pur<193><207>as. He must have been ç
a great sage and an erudite law-giver since he has been widely quoted ç
by many a writer of dharma·<193>stras.
@SPACE1 = 
The present work probably took the final shape during the period 200 ç
<MS>B.<|>C.<D><192><MS>A.D.<D> 200. Though it contains earlier and ç
later strata, as seen from quite a few conflicting or contradictory ç
statements on the same point, the number of recasts do not seem to ç
be many.
Sometimes, a theory is hazarded that the extant Manusm<216>ti is ç
a work based on an earlier one called M<193>navadharmas<220>tra. ç
This, however, has been rejected by well-known scholars in this field ç
(vide Dr. P. V. Kane, History of Dharma·<193>stra, vol. 1, part ç
1, p. 149, Poona, Bhandarkar Oriental Research Institute, 1968).
A brief account of the contents of the extant work may now be given:
@S10N = Chapter 1 (119 verses)
Creation of the world and various creatures; divisions of time; var<207>adharmas ç
or duties of the four castes; greatness of the br<193>hma<207>a.
@S10N = Chapter 2 (249 verses)
On dharma; divisions of the land of Bh<193>ratavar<218>a as Brahm<193>varta, ç
°ry<193>varta and so on; sa<221>sk<193>ra; definitions of the terms ç
<193>c<193>rya, up<193>dhy<193>ya and others.
@S10N = Chapter 3 (286 verses)
Eight forms of marriage; mutual relation between husband and wife; ç
pa<210>ca- yaj<210>as or five daily sacrifices; ·r<193>ddha and tarpa<207>a ç
(obsequial rites).
@S10N = Chapter 4 (260 verses)
Means of livelihood; rules of conduct; condemnation  of  immoral  enjoyments; ç
efficacy of <193>c<193>ra or good conduct.
@S10N = Chapter 5 (169 verses)
Causes of death; on food and drink; a·auca or ceremonial impurity; ç
duties of women.
@S10N = Chapter 6 (97 verses)
Exhaustive treatment of the V<193>na-prasth<193>·rama.
@S10N = Chapter 7 (226 verses)
Political science and statecraft including  the  details  like  punishment  for ç
transgressions, taxation, appointment of ministers, espionage, envoys ç
and political expedients.
@SPACE1 = 
@S10N = Chapter 8 (420 verses)
Administration of justice; eighteen titles of law such as <216><207><193>d<193>na ç
(non-repayment of debt), asv<193>mivikraya (sale of property by one ç
who is not the legal owner), vetan<193>d<193>na (non-payment of wages), ç
s<200>m<193>viv<193>da (boundary dispute), vibh<193>ga (partition) ç
and so on.
@SPACE1 = 
@S10N = Chapter 9 (336 verses)
Duties of men and women; inheritance; succession; str<200>dh<193>na ç
(property of women); and, gains of learning.
@SPACE1 = 
@S10N = Chapter 10 (131 verses)
Duties of br<193>hma<207>as; mixed castes; <193>pad-dharma (duties ç
in emergencies).
@SPACE1 = 
@S10N = Chapter 11 (265 verses)
Duties of a sn<193>taka (a brahmac<193>ri who has completed his studies); ç
sins and their expiation.
@SPACE1 = 
@S10N = Chapter 12 (126 verses)
Results of good and bad deeds; natureand knowledge of the <193>tman, ç
the Self within; benefits of studying the Manusm<216>ti.
The Manusm<216>ti has several Sanskrit commentaries. The bh<193><218>yas ç
of Medh<193>tithi (<MS>A.<|>D.<D> 900), Govindar<193>ja (Manv<193>·ay<193>nu-s<193>ri<207><200>) ç
(<MS>A.<|>D.<D> 1100) and the Manvartha-mukt<193>val<200> of Kull<220>ka ç
(earlier than <MS>A.<|>D.<D> 1100) are more well-known among them. ç
N<193>r<193>ya<207>a (Manvarthaviv<216>ti), R<193>ghav<193>-nanda ç
(Manvarthacandrik<193>), Nandana (Nandin<200>) and R<193>machandra ç
are the other commentators about whom not much is known.
The Manusm<216>ti seems to have influenced the law-books of some ç
other countries outside India also. The Culova<221>·a of Ceylon ç
(now Sri Lanka), the Kutasa M<193>nava and the Dawagama of Indonesia ç
have been greatly influenced by Manu.
Works very similar to Manusm<216>ti have been found in China and ç
Japan. Adeity of the old Persian pantheon hasbeen called `Vaivasvata ç
Manu'. Darius (600 <MS>B.<|>C.<D>) is said to have framed his laws ç
according to Manu's work. There is a statue of Manu in the Philippines.
In later works, two more treatises† the B<216>hanmanu and the V<216>ddhamanu† ç
have been referred to. It is difficult to say whether they were independent ç
works or redactions of Manusm<216>ti.
See also <MS>MANVANTARA.
@SPACE = 
@NT = manu<218>ya-yaj<210>a
@N1 = (`sacrifice to the human beings')
See <MS>PA<178>CAMAH°YAJ<178>AS.
@SPACE = 
@NT = manv<193>di-tithi
@N1 = (`the day on which a<R>ç
manvantara starts')
There are fourteen manvantaras. (See <MS>MANVANTARA<D> for details.) ç
Each of these manvantaras is said to begin on a particular day. This ç
is called `manv<193>di-tithi'.
The following are the fourteen manv<193>di-tithis:
°·vina-·ukla-navam<200> (9th day of the bright half of °·vina); K<193>rttika-·ukla-dv<193>da·<200> ç
(12th day of the bright half of K<193>rttika); Caitra-·ukla-t<216>t<200>y<193> ç
(3rd day of the bright half of Caitra); Bh<193>drapada-·ukla-t<216>t<200>y<193> ç
(3rd day of the bright half of Bh<193>drapada); am<193>v<193>sy<193> ç
of Ph<193>lguna (new-moon day of Ph<193>lguna); Pau<218>a-·ukla-ek<193>da·<200> ç
(11th day of bright half of Pau<218>a or Pu<218>ya); °<218><193><195>ha-·ukla-da·am<200> ç
(10th day of the bright half of °<218><193><195>ha); M<193>gha-·ukla-saptam<200> ç
(7th day of the bright fortnight of M<193>gha); <185>r<193>va<207>a-k<216><218><207>a-a<218><219>am<200> ç
(8th day of the dark half of <185>r<193>va<207>a); p<220>r<207>im<193> ç
(full-moon) of the months of °<218><193><195>ha, K<193>rttika, Ph<193>lgu<207>a, ç
Caitra and Jye<218><219>ha.
These manv<193>di-tithis are considered extremely good for the performance ç
of ·r<193>ddhas to appease the pit<216>s or the manes.
@SPACE = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@NT = manvantara
@N1 = (`period of rule or epoch of a Manu')
@SPACE = 
The concept of time as given in the pur<193><207>as is, to say the ç
least, mind-boggling!
Each day of Brahm<193>, the creator, (called `kalpa' by the pur<193><207>as) ç
includes one thousand Mah<193>yugas. Each Mah<193>yuga includes the ç
four well-known yugas: K<216>tayuga, Tret<193>yuga, Dv<193>parayuga ç
and Kaliyuga.
This day or kalpa is divided into fourteen manvantaras (epochs of ç
Manu) or periods of time, ruled by a Manu. Each manvantara has a little ç
more than 71Mah<193>yugas.
The fourteen Manus ruling over these manvantaras of the present kalpa ç
are: Sv<193>yambhuva, Sv<193>roci<218>a, Uttama, T<193>masa, Raivata, ç
C<193>k<218>u<218>a, Vaivasvata, S<193>var<207>i, Dak<218>a-s<193>var<207>i, ç
Brahma-s<193>var<207>i, Dharma-s<193>var<207>i, Rudra-s<193>var<207>i, ç
Ruci and Bhauma.
The Manu of the present age is Vaivasvata. He is the son of S<220>rya ç
and is also known as <185>r<193>ddhadeva.
Each Manu has his own set of gods, Indra, <216><218>is and others. ç
The name of the present Indra is Purandara. The Saptar<218>is or the ç
Seven Sages of this manvantara are:Vasi<218><219>ha, Ka·yapa, Atri, ç
Jamadagni, Gautama, Vi·v<193>mitra and Bharadv<193>ja.
In terms of human years, one Mah<193>yuga is of the duration of 43,20,000 ç
years. Hence the period of a manvantara comes to 308 million human ç
years!
@SPACE1 = 
@NT = mara<207>a
@N1 = (`that which separates the <193>tman form the body')
Birth (janma) and death (mara<207>a) have been an inscrutable mystery ç
to man right from the most ancient days. In trying to solve this mystery, ç
several theories have been put forward. If death is considered by ç
some as total annihilation of the human personality, others accept ç
the survival of a soul after death, which goes to either heaven or ç
hell, eternally, depending upon its deeds done here. Both of them ç
are, more or less, silent on what causes birth. The third view, as ç
held by the Hindu sages, is that the soul is eternally existing, having ç
neither birth nor death. It is the body that is born. It is the body ç
again, that dies. The soul is made to incarnate in the body, by an ç
eternal law of God, the kind of body, the duration of life and the ç
various experiences in life being determined by the karma or the moral ç
deserts of that soul, carried over from the previous lives.
Every being that is born, has to die one day, the manner of death, ç
again, depending upon the soul's karma.
