Mara<207>a or death can come to a person due to natural causes like ç
old age or diseases, or, it can be caused by unnatural causes like ç
accident, suicide, murder or capital punishment.
It is interesting to note that the Hindu scriptures describe certain ç
signs as indicative of approaching death. Some of them are: not being ç
able to see the star Arundhati (the small star Alcor) or the pole-star ç
or the full-moon even though there is perfect visibility; seeing the ç
orb of the moon or the sun with a hole in it; smelling the odour of ç
a corpse even though fragrant substances are near; not hearing the ç
humming or the internal noise when the ears are closed; not seeing ç
one's reflection in another's eyes standing in front and so on.
Dreaming of an ass or an old maid or a trident also prognosticates ç
imminent death.
The scriptures also stress the point that the last thought at the ç
time of death,can determine the next birth (vide Bhagavadg<200>t<193> ç
8.6).
Death, while fighting for dharma†as for instance, to protect a righteous ç
person in danger†has been considered glorious.
Hindu scriptures have permitted reli-gious suicide in certain cases ç
such as j<200>vanmukti (liberation even while living), decrepitude ç
due to extreme old-age, incurable diseases causing unbearable suffering ç
or as a pr<193>ya·citta (expiation) for heinous crimes.
See also <MS>ANTYE<186><187>I<D>, <MS>M<184>TYU<D> and <MS>YAMA.<D>
@NT = Mar<200>ci
Considered a m<193>nasaputra or mind-born son of Brahm<193>, the creator, ç
Mar<200>ci, is reckoned among the praj<193>patis (progenitors of mankind). ç
He is also one of the Saptar<218>is (seven sages).
His wife was Kal<193>, the daughter of Kardama, another praj<193>pati. ç
The sage Ka·yapa was his son.
There is a sm<216>ti attributed to him and its verses are quoted by ç
other writers of dharma·<193>stras.
His opinions on <193>hnika (daily routine of  a  dvija or  the  twice-born),  a·auca ç
(ceremonial impurity), ·r<193>ddha (obsequial rites), pr<193>ya·citta ç
(expiations for sins) and vyavah<193>ra (secular life) have been noted ç
with respect.
Some of his views like the transactions involved in sale of property ç
approach our modern laws.
The sm<216>ti perhaps, contained both verses and sentences in prose.
@SPACE = 
@NT = m<193>rjana
@N1 = (`cleansing')
@SPACE = 
The sandhy<193> ritual†also called `sandhy<193>vandana'†is an important ç
part of the daily routine of every dvija (a member of the first three ç
castes). Out of the several steps involved in its performance, m<193>rjana ç
is also one.
M<193>rjana is ceremonially purifying the body by sprinkling water ç
with ku·a grass (Poa cynosuroides retz) on specified parts of the ç
body, with the repetition of the well-known Vedic mantra `<193>po ç
hi <218><219>h<193>' (<184>gveda 10.9.1-3).
Sometimes the G<193>yatr<200> mantra along with the three vy<193>h<216>tis ç
(bh<220><199> etc.) as also some more Vedic mantras are also pres-cribed ç
to be recited during m<193>rjana.
See  also  <MS>G°YATR®<D>  and  <MS>SANDHY°- VANDANA<D>.
@NT = M<193>rka<207><195>eya
@N1-1 = (`son of the [sage] M<216>ka<207><195>u')
Destined to die at an early age, the young M<193>rka<207><195>eya ç
worshipped Lord <185>iva with intense devotion to transcend death.Just ç
as Yama, the god of death, approached him with his noose, to take ç
him away, M<193>rka<207><195>eya clung to the <185>ivali<209>ga he ç
was worshipping, whence <185>iva appeared with his trident and prevented ç
him from doing so. He also gave M<193>rka<207><195>eya, a long life ç
of 14 kalpas' duration (a kalpa = one day of Brahm<193>).
He is sometimes classed along the cira<210>j<200>vis (those who live ç
eternally) along with Hanum<193>n, Vy<193>sa and others.
The M<193>rka<207><195>eyapur<193><207>a is attributed to him as ç
the chief narrator.
@EMERGENCY = He is said to be one of the sm<216>tik<193>ras who edited ç
and condensed the original Manusm<216>ti to 8000 ·lokas and passed ç
iton to Sumati Bh<193>rgava. M<193>rka<207><195>eya appears in the ç
Mah<193>bh<193>rata as also in some pur<193><207>as like the Bh<193>gavata ç
and the Matsya. He is said to have visited the P<193><207><195>avas ç
in the K<193>myakavana and taught them dharma through many stories. ç
Healso told Yudhi<218><219>hira that <185>r<200> K<216><218><207>awas ç
the Supreme Lord Himself (Vanaparva 189).
@EMERGENCY = While discussing dharma with the sage N<193>rada, M<193>rka<207><195>eya ç
gives his views on various topics connected with marriage and chastity ç
(Mah<193>bh<193>rata, Anu·<193>sanaparva 50-62).
@EMERGENCY = There is one M<193>rka<207><195>eya °·rama near Bh<193>ge·vara ç
at the confluence of the rivers Gomat<200> and Saray<220> in Uttar ç
Pradesh.
@NT = M<193>rka<207><195>eyapur<193><207>a
See under <MS>PUR°ØAS.<D>
@NT = marriage
See <MS>VIV°HA.<D>
@NT = Marudga<207>a
@N1 = (`the group of [gods] called Marut')
There are many Vedic gods out of which the Marudga<207>a or a group ç
of Maruts is one. They are described by some modern scholars as the ç
personification of storms. Their number is mentioned sometimes as ç
21 and sometimes as 180.
They are depicted as the sons of Rudra and P<216>·ni. They are handsome, ç
fiery in colour and nature, and, live in the antarik<218>a (intervening ç
space between this earth and heavens). Lightning and thunderbolt are ç
their weapons. Giving rains to us is one of their important duties. ç
Though terrifying in appearance they are full of compassion towards ç
their votaries. Several hymns of the <184>gveda (vide 5.52-60) ç
are in praise of them.
The epics contain an interesting story about them. When Diti, the ç
mother of the daityas (demons), was pregnant, expecting a very powerful ç
son as per the blessing of her husband Ka·yapa, Indra, the king of ç
gods, is said to have stealthily broken the foetus into 49 parts. ç
These `babies' started weeping. At the request of their mother  Diti,  Indra  granted  them ç
protection, godhood, and made them thecontrollers of wind (Mah<193>bh<193>rata, ç
°diparva, 132).
@NT = Maskarin
The dharma·<193>stras of various competent and scholarly <216><218>is ç
or sages have guided the personal, social and religious lives of the ç
Hindus for several centuries. Gautama is one such whose works like ç
the Dharmas<220>tras have been held in high esteem. The s<220>tras, ç
though containing a lot of information and instructions, being laconic, ç
need bh<193><218>yas or commentaries to expound their contents.
The Bh<193><218>ya of Maskarin (which is available in print and ç
is quite extensive) on the Gautama Dharmas<220>tras has been respectfully ç
quoted by several later writers of the dharma·<193>stra digests.
Maskarin also quotes profusely from the works of his predecessors ç
like U·anas, Ka<207>va, K<193>ty<193>yana, Pai<219>h<200>nasi and ç
J<193>t<220>-kar<207>i. He might have lived during the period <MS>A.<|>D.<D> ç
900-1100.
See also <MS>GAUTAMA.
@NT = m<193>t<193>
@N1 = (`one who is honoured or<R>ç
worshipped', `mother')
Hinduism has given the highest place of honour to the mother. In fact; ç
the very etymological derivation on the word `m<193>t<193>' is `m<193>nyate ç
p<220>jyate y<193> s<193>', `one who is honoured or worshipped'. The ç
Taittir<200>ya Upani<218>ad (1.11)  advises  the  outgoing student ç
of the gurukula (forest academy run by the <216><218>is or sages) ç
to look upon his mother as if she were God Himself. In this series ç
of pithy teachings, she is placed above the father and the Vedic teacher.
In fact, the status of motherhood has been raised to the highest level ç
by depicting even God, as the Divine Mother, in later religious literature ç
like the pur<193><207>as and the tantras.
It is the bounden duty of the son to protect her and maintain her ç
at all costs even if she were a sinner, reduced to the level of an ç
outcaste.
One of the sm<216>tis (the <185>a<209>khalikhita) gives an interesting ç
piece of advice to a son that he should not normally take sides when ç
the father and the mother are quarrelling. If at all, he should side ç
with the mother!
The epics and the pur<193><207>as are full of eulogy of the mother ç
and of instances (like that of the P<193><207><195>avas) where the ç
sons have served their mother devotedly.
They also warn that if a mother is deeply hurt and utters a curse, ç
it can never be averted.
Even during the historical period there are several instances where ç
the mothers have inspired and shaped the character of their sons and ç
the latter's gratitude towards them.
@NT = Mata<209>ga
A great sage classed among the brahmar<218>is, he had his hermitage ç
on the <184><218>yam<220>ka hill (near Hampi in Karnataka). When V<193>li ç
killed the demon Dundubhi and threw his severed head, it fell in this ç
hermitage defiling it. The sage got angry and cursed that V<193>li ç
would die if he ever stepped into this place.
Since Sugr<200>va, the younger brother of V<193>li, knew this, he ç
took shelter on this hillock along with his loyal ministers (including ç
Hanum<193>n) to escape from V<193>li.
According to the legends connected with the exploits of Lalit<193> ç
(an aspect of P<193>rvat<200>, spouse of Lord <185>iva), Mata<209>ga ç
was a great sage endowed with the knowledge and power of various mantras. ç
His daughter M<193>ta<209>g<200> was an attendant of Lalit<193>.
@NT = materialism
See <MS>B<184>HASPATI<D> and <MS>C°RV°KADAR<185>ANA.<D>
@NT = ma<219>ha
@N1 = (`dwelling place of yatis or monks')
@SPACE = 
@SPACE = 
A ma<219>ha (monastery), in the sense we understand it today, is, ç
perhaps, nota veryancient institution. The Baudh<193>yana Dharmas<220>tras ç
(3.1.16) (600-300 <MS>B.<|>C.<D>) has used the word `ma<219>ha' in ç
the sense of a hut where a teacher and his pupils reside, to pursue ç
their studies. Ma<219>has might have evolved from the example of the ç
Buddhist vih<193>ras. They definitely received a fillip from the celebrated ç
teacher of Advaita Ved<193>nta, <185>a<209>kara (<MS>A.<|>D.<D> 788-820), ç
who established four principal ma<219>has in the four cardinal directions ç
of India.
A temple and a ma<219>ha both have a common religious motive and sentiment. ç
However, if a temple is built primarily for the purpose of prayer ç
and worship as also religious instruction for the masses in a general ç
way, a ma<219>ha is specially meant for the training of the pupils ç
and the laity in the tenets of the sect to whichit belongs or in ç
the doctrines of some philosophy including allied fields of knowledge. ç
The heads of these ma<219>has were, generally, sa<221>ny<193>sins ç
(monks) and were called `ma<219>h<193>dhipatis' (`mahanta' in vernaculars).
Originally the ma<219>has were simple dwelling places for these monks ç
since theywere expected to constantly tour the country for spreading ç
the message ofdharma (moral and spiritual values). However, due to ç
the enthusiasm and generosity of the laity, these ma<219>has gradually ç
acquired a lot of property, both movable and immovable. This naturally ç
necessitated the evolution of some norms,guidelines and rules for ç
the judicious management of the ma<219>ha and its property. Related ç
to it was also the problem of succession.
Though the entire property belonged to the ma<219>ha, its legal head ç
(the ma<219>h<193>dhipati) had the full control and the freedom to ç
use it in the best interests of the institution and its followers.
A ma<219>h<193>dhipati is selected in one of the three ways as follows:
1.<+>The present head selects from among his disciples a fit one to ç
succeed him.
2.<+>The disciples will elect from among themselves one person if the ç
previous head had passed away without choosing his successor.
3.<+>The ruling power (the State) or the original founder or his heirs ç
appoint the next head.
Over the centuries, ma<219>has of various sects have proliferated.
As the properties and income of these ma<219>has went on swelling, ç
disputes over their control as also the rights and privileges, also ç
increased. Consequently law-courts have been flooded with cases related ç
to these disputes.
However, whenever a spiritually eminent person has occupied the pontiff's ç
seat, really great work has been done for the welfare of Hindu society ç
by these ma<219>has. Types of service also have been increased and ç
diversified.
Wherever an important temple and a ma<219>ha have been closely associated ç
with each other, both have grown in quantity and quality.
@NT = Mathur<193>
R<193>ma and K<216><218><207>a have so deeply influenced the Hindu ç
psyche over the last five or six millennia that no aspect or field ç
of life of the Hindus has been left untouched by their influence. ç
Philosophy, religion, fine-arts, architecture, sculpture, literature, ç
music, dancing, drama†practically every field of life, bears their ç
impress. It is but natural that places closely associated with them ç
became, in course of time, holy places, places of pilgrimage.
Mathur<193>, a small town on the west bank of the river Yamun<193> ç
(in Uttar Pradesh) has been very closely associated with Lord K<216><218><207>a's ç
boyhood days. Hence, this town and the area spread over 32 kms. (20 ç
miles) around it†known as Vrajabh<220>mi or Vrajama<207><195>ala†has ç
been considered as extremely sacred. There are several temples here ç
connected with the K<216><218><207>a-cult.
The temple of Dv<193>rak<193>dh<200>·a is the biggest and worship ç
is conducted there asper the traditions set up by Vallabha (<MS>A.<|>D.<D> ç
1473-1531). <185>r<200>k<216><218><207>a Janm<193><218><219>am<200> ç
(the birthday of <185>r<200> K<216><218><207>a) is celebrated here ç
on a grand scale.
The other temples are: Trivikrama-n<193>r<193>ya<207>a-mandira<%24>,<%0>Vijayagovinda-mandira ç
and a temple of Ke·ava. Patraku<207><195>a, a well near this temple, ç
is said to be the place where baby K<216><218><207>a's clothes used ç
to be washed.
Mah<193>vana (Mah<193>ban) which is 14 kms. (9 miles) away, as also ç
Baladeva at a further distance of 8 kms. (5 miles) are two more important ç
places visited by the pilgrims.
Vanay<193>tr<193> (perambulation of Mathur<193>) starts from the place ç
called Vi·r<193>mgh<193><219>.
@SPACE1 = 
The Govardhana hillock which K<216><218><207>a as a child of seven ç
years is said to have lifted up and held as an umbrella over the head, ç
to protect the villagers from the torrential rain caused by Indra, ç
is at a distance of 26 kms. (16 miles) from Mathur<193>.
There is a small village nearby which has two small tanks†R<193>dh<193>ku<207><195>a ç
and K<216><218><207>aku<207><195>a.
V<216>nd<193>ban, another major place of pilgrimage, is situated at ç
a distance of 11 kms. (7 miles) from Mathur<193>. There are many important ç
temples associated with K<216><218><207>a, here also.
Taking bath in the Yamun<193> river on the Yamadvit<200>y<193> or ç
Bhr<193>t<216>dvit<200>y<193> day (2ndday of the bright half of the ç
month of  K<193>rttika,  K<193>rttika-·ukla-dvit<200>y<193>)  is considered ç
as extremely meritorious. Such bathers are believed not to go to ç
Yamaloka or Abode of Yama.
As already indicated, the entire Mathur<193>-V<216>nd<193>ban region ç
is known as `Vrajama<207><195>ala.' Holik<193>g<200>tas, a special ç
kind of devotional music, is peculiar to this region.
There are many facilities for the pilgrims like dharma·<193>las (free ç
guest houses or with very nominal charges).
There are at least 25 bathing places on the banks of the river Yamun<193>, ç
known as `gh<193><219>s', like Vi·r<193>mgh<193><219>, Dhruvagh<193><219>, ç
K<216><218><207>aga<209>g<193>gh<193><219>, As<200>ku<207><195>agh<193><219> ç
and so on.
@SPACE1 = 
Mathur<193> is a very ancient city established by <185>atrughna, the ç
younger brother of <185>r<200> R<193>ma. He is said to have killed ç
Lava<207><193>sura (son of the demon Madhu) and remodelled the old ç
capital Madhupura into Mathur<193>. Archaeological finds at the sites ç
near Mathur<193> have revealed that the town-ship must have existed ç
even around 1000 <MS>B.<|>C.<D> Later on, it became a stronghold of ç
Buddhism and Jainism. Fa Hien (5thcentury <MS>A.<|>D.<D>) mentions ç
that there were 20 Buddhist monasteries. Hiuen Tsang (7th century ç
<MS>A.<|>D.<D>) says that 200 monks lived in these monasteries. But ç
orthodox Hinduism†the Bh<193>gavata Cult of K<216><218><207>abhakti ç
or devotion to K<216><218><207>a†also was regaining its lost ground. ç
By the 11thcentury, Buddhism had practically disappeared.
During the period <MS>A.<|>D.<D> 1000-1700, intolerant Muslim invaders ç
and rulers unleashed a reign of terror and destroyed many  temples  and  Hindu  religious ç
monuments.
Almost all the Vai<218><207>ava teachers and religions reformers like ç
the followers of R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137), Nimb<193>rka ç
(12th century <MS>A.<|>D.<D>), Sv<193>mi Harid<193>s (16th century ç
<MS>A.<|>D.<D>), R<220>pa Gosv<193>mi (<MS>A.<|>D.<D> 1493-1568) and ç
San<193>tana Gosv<193>mi (<MS>A.<|>D.<D> 1481-1558) have established ç
their ma<219>has here to spread their cult.
See also <MS>V<184>ND°BAN.<D>
@NT = M<193>t<216>k<193>nigha<207><219>u
@N1 = (`dictionary of M<193>t<216>k<193>s [or letters of the alphabet]')
The tantras†religions works dealing mainly with the Devi-cult or worship ç
of God as the Divine Mother†have exercised a tremendous influence ç
over the ritualistic and the practical aspects of Hinduism. The up<193>san<193> ç
or meditation upon a deity also requires the japa (repetition) of ç
the mantra (name or an esoteric formula). This mantra, more often ç
than not, has a b<200>ja or a seed-letter. There are different b<200>jas ç
for different deities of the Hindu pantheon. Also, the same b<200>ja ç
can represent several deities.
To keep the science well-guarded, but intelligible only to the initiates, ç
the tantras adopt a round-about way of indicating these b<200>jas. ç
Unless the methodology adopted is understood by the initiates, it ç
is impossible to decipher these b<200>j<193>k<218>aras or b<200>jamantras.
To help the novitiates in this field, expert teachers have composed ç
abhi-dh<193>nas, ko·as and nigha<207><219>us (dictionaries) that unravel ç
the mystic syllables more easily.
The following list gives some of theseworks, arranged in the English ç
alphabetical order:
@S10N = 1.	B<200>j<193>bhidh<193>na (of Bh<220>ta<195><193>maratantra)
This is a small work of 75 lines inanu<218><219>ubh metre describing ç
the b<200>ja-mantras like hr<200>m, str<200>m, aim, kr<200>m representing ç
various deities like Aindr<200>, V<193>mek<218>a<207><193>, Sarasvat<200> ç
and K<193>l<200>.
@S10N = 2.	B<200>janigha<207><219>u (of Bhairava)
The author Bhairava says in the beginning of this work that it is ç
based onthe information given in the Bh<220>ta<195><193>maratantra ç
and the <185>rutis he has studied.
It starts with the narration as to what the 50 letters of the alphabet ç
stand for.
This is followed by various b<200>ja- mantras like ·r<200><221>, hr<200><221>, ç
kr<200><221>, hu<221> and others, and, what deities they represent.
@S10N = 3.	Ek<193>k<218>arako·a (of Puru<218>ottamadeva)
As the very name indicates, this short work describes the various ç
gods and goddesses as also other objects represented by each of the ç
Sanskrit alphabets. For instance if `a' represents V<193>sudeva, `<193>' ç
stands for the Pit<193>maha (Brahm<193>). `Pa' indicates  Pavana  (god  of  wind).  `S<193>' ç
represents both Lak<218>m<200> and <185>iva.
@S10N = 4.	Mantr<193>bhidh<193>na
There are 35 ·lokas in this work. This too describes the letters of ç
the alphabet†called `m<193>t<216>k<193>-ak<218>aras'†as standing for ç
certain deities.
@S10N = 5.	Mantr<193>rth<193>bhidh<193>na (of Varad<193>tantra)
This is a short work of 50 lines in the ·loka metre. It describes ç
the various b<200>jamantras like hau<221> (for <185>iva), d<220>m ç
(forDurg<193>), kr<200><221> (for K<193>lik<193>), hr<200><221> (for ç
Bhuvane·var<200>), kl<200><221> (for K<193>madeva), ga<221> (for Ga<207>e·a), ç
k<218>rau<221> (for Narasi<221>ha) and so on.
@S10N = 6.	M<193>t<216>k<193>nigha<207><219>u (of Mah<200>d<193>sa)
Like the other works described above, this work also describes in ç
59 verses the letters of the alphabet and what they stand for. For ç
instance, `a' stands for <185>r<200>ka<207><219>ha (<185>iva), Ke·ava ç
(K<216><218><207>a) and V<193>ta (god of wind). The letter `ka' represents ç
M<193>y<193> and Deve·a. If `ma' denotes Vaiku<207><219>ha (Vi<218><207>u) ç
and Mah<193>k<193>la (<185>iva), `ya' stands for Yamun<193>.
@EMERGENCY = There are three more similar works which are variations ç
of the ones already mentioned like the Mantr<193>bhidh<193>na, with ç
practically the same subject-content.
@NT = m<193>t<216>k<193>ny<193>sa
@N1 = (`keeping the m<193>t<216>k<193>s [or the little mothers on ç
the different parts of the body]')
@EMERGENCY = Ritualistic worship as also many rites associated with ç
it are guided by the rules and regulations given in the <193>gamas ç
and the tantras. One of the important acts in such rituals is the ç
ny<193>sa.
Literally `ny<193>sa' means `keeping or placing'.
In m<193>t<216>k<193>ny<193>sa, the various letters of the Sanskrit ç
alphabet†considered as `m<193>t<216>k<193>s' or `little mothers', ç
aspects of the Divine Mother†are ceremonially placed on the different ç
parts of the body, thus destroying the sins and purifying the same.
The <216><218>i (sage), chandas (metre), devat<193> (deity) and b<200>ja ç
(seed) for this m<193>t<216>k<193>ny<193>sa are, respectively, Brahm<193>, ç
G<193>yatr<200>, M<193>t<216>k<193>dev<200> and all the letters of ç
the alphabets.
A<209>gany<193>sa (also called <218>a<195>a<209>ga-ny<193>sa), antarm<193>t<216>k<193>ny<193>sa ç
and bahir-m<193>t<216>k<193>ny<193>sa are the three aspects of this ç
ny<193>sa.
In all these, the letters of the alphabet adding anusv<193>ra, <221>, ç
are used. For instance, in a<209>gany<193>sa: a<221> ka<221> kha<221> ç
ga<221> gha<221> <209>a<221> h<216>day<193>ya nama<199> and soon.
Inantarm<193>t<216>k<193>ny<193>sa, the process concentrates on the ç
six cakras like sv<193>dhi<218><219>h<193>na, ma<207>ip<220>ra up ç
to <193>j<210><193> with appropriate letters ba<221> bha<221> and ç
so on.
In the bahirm<193>t<216>k<193>ny<193>sa, the process of placing the ç
letters is performed on the various limbs like the forehead, mouth, ç
the eyes and so on.
There is also another ny<193>sa called p<200><219>hany<193>sa wherein ç
the various <185>akti-p<200><219>has are symbolically established ç
on the different parts of the body thus purifying it.
@NT = m<193>t<216>k<193>yantra
@N1 = (`esoteric drawing of <R>ç
m<193>t<216>k<193>s or letters of the alphabets')
A mantra is a mystic formula which is generally used for up<193>san<193> ç
(worship and meditation) and japa (repetition). There are several ç
ways of making a mantra efficacious before actually using it. The ç
first of it is called `janana' or extrication of the letters of the ç
mantra from a specially drawn `yantra' or mystical figure. This is ç
the `m<193>t<216>k<193>yantra'.
@SPACE = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE = 
It may be drawn either by the filaments of certain flowers or candana ç
(sandal-paste) or bhasma (holy ash used in the worship of <185>iva). ç
The base is a plate of gold or silver or copper.
The yantra consists of eight petals surrounded by a square with gates. ç
In the centre there is a small circle and radial passages spread from ç
it to the petals. All the letters of the Sanskrit alphabet are incorporated ç
in it in a particular order.
The actual method of deriving the required mantra from this yantra ç
should be personally learnt from the guru.
@NT = Matsyapur<193><207>a
@N1 = (`Pur<193><207>a related to the Matsy<193>vat<193>ra [or Fish-incarnation]')
The pur<193><207>as, as secondary scriptures of Hinduism, have contributed ç
a lot to spread of religion, culture and moral values as also several ç
aspects of secular sciences  like  architecture  or  political science ç
or health-care.
Out of the eighteen Mah<193>pur<193><207>as, the Matsyapur<193><207>a ç
is considered not onlyimportant but also comparatively more ancient, ç
assigned to the period circa <MS>A.<|>D.<D> 300.
The editions available in print now have 291 chapters and 14,000 verses.
It was probably a Vai<218><207>ava work earlier, and, later additions ç
might have been done by <185>aivites, with a view to harmonising the ç
two cults.
Many of the verses from the V<193>yu and the Vi<218><207>udharmottara ç
pur<193><207>as have been found here also. Hence it is difficult to ç
say who has borrowed from whom.
Several dharma·<193>stra works have quoted from this pur<193><207>a ç
profusely.
The pur<193><207>a begins with a dialogue between lord Vi<218><207>u ç
as the Matsya and Manu. Hence the name Matsyapur<193><207>a.
A brief account of the contents may be given as follows:
Creation of the world by Brahm<193> and the Praj<193>patis; destruction ç
of Tripur<193>sura by <185>iva; Sat<200>'s immolation in Dak<218>a's ç
sacrifice; on K<193>rttikeya; wars between the devas and asuras; geneologies ç
of kings of the lunar and solar dynasties; names and accounts of future ç
kings and races; avat<193>ras of Vi<218><207>u (including the name ç
of Buddha); funeral rites; vratas (religious vows and observances); ç
d<193>na (gifts); places of pilgrimage and bath in the holy rivers; ç
var<207>a-<193>·rama-dharmas; duties of women; establishing wells, ç
tanks and gardens for public good; descriptions of hells; stories ç
about the <185>ivali<209>gas.
@SPACE1 = 
See also <MS>PUR°ØAS.<D>
@NT = Matsy<193>vat<193>ra
@N1 = (`Fish-incarnation')
This is the first of the Da·<193>vat<193>ras or Ten Incarnations of ç
Vi<218><207>u. During this incarnation the Lord appeared as a tiny ç
fish that fell into the hands of Vaivasvata Manu who was praying. ç
When sheltered by him in his palace, he gradually grew into gigantic ç
proportions instructing him to release him into the sea. There he ç
told him how he would save him and the Saptar<218>is†the Seven Sages†at ç
the time of the great deluge destroying the world.
See also <MS>AVAT°RA<D> and <MS>DA<185>°VAT°RAS<D>.
@NT = matsyayantra
In the epics and the pur<193><207>as we often come across very difficult ç
tests laid down for the contestants who wanted to win the hands of ç
the best of k<218>attriya maidens. If it was lifting and stringing ç
the <185>ivadhanus (the great bow of Lord <185>iva) in the case of ç
S<200>t<193> (king Janaka's daughter), it was the matsyayantra in ç
the case of Draupad<200>, the P<193><210>c<193>la princess, the only ç
daughter of the king Drupada.
The contrivance matsyayantra had a fish fixed near the roof of the ç
big hall. Just below it, on the ground was a big pond full of oil. ç
Between the two, nearer the roof, was a revolving disc containing ç
a hole, the contestant had to discharge five arrows through the hole, ç
while looking at the reflection of revolving wheel in the pond of ç
oil, from the bow supplied, to hit the target fish.
Only Arjuna succeeded in accomplishing this heroic and dexterous act. ç
(Vide Mah<193>bh<193>rata, °diparva, chapter 184-188.)
@NT = Matsyendran<193>tha
The N<193>tha Cult is one of the more obscure religious cults of <185>aivism ç
which gives primary importance to the practice of Ha<219>hayoga and ç
the attainment of occult powers.
The guru-parampar<193> or the tradition of gurus has a long list of ç
84 siddhas or perfected beings. In this list, Matsyendra-n<193>tha ç
(or M<200>nan<193>tha) is shown as the founder and the first teacher, ç
the second being  Gorak<218>an<193>tha  or  Gorakhn<193>th. According ç
to other lists, °din<193>tha (or <185>iva) is the first teacher, Matsyendran<193>tha ç
being the second. He is said to have been born out of the womb of ç
a matsya or m<200>na (fish), as a perfected being. This was possible ç
because he accidentally happened to listen to the teachings of Lord ç
<185>iva to P<193>rvat<200>, even while he was in the womb of his ç
mother (a fish).
Gorak<218>an<193>tha or Gorakhn<193>th was hischief disciple. However, ç
the Bengali tradition treats it the other way, making Gorakhn<193>th ç
the teacher and Matsyendra-n<193>th as his chief disciple.
@SPACE1 = 
Buddhist tradition in Nepal identifies him with Avalokite·vara Padmap<193><207>i. ç
In Tibet he is called L<220>ip<193>.
He probably belonged to the 12th century <MS>A.<|>D.<D> though some ç
like to place him in the 7th. The Akulav<200>ratantra is attributed ç
to him as the author.
Not much is known of his life and works.
See also <MS>N°THA-CULT.<D>
@NT = maun<200>-am<193>v<193>sy<193>
@N1 = (`the new-moon day of mauna [or observing silence]')
The am<193>v<193>sy<193> during the month of M<193>gha, is called ç
`maun<200> Am<193>v<193>sy<193>'. On this day people are advised to ç
keep mauna or observe silence or behave like munis or sages, observing ç
spiritual disciplines like satya or speaking the truth, brahmacarya ç
or celibacy and so on. However, thisday is held to be extremely auspicious ç
to have a dip in the Sa<209>gama or Trive<207><200>sa<209>gama, the ç
confluence of the rivers Ga<209>g<193>, Yamun<193> and the subterranean ç
Sarasvat<200> of Vedic fame, situated in Pray<193>ga or the modern ç
Allahabad (in Uttar Pradesh). Every year lakhs of people gather on ç
the banks of the rivers Ga<209>g<193> and Yamun<193> at Allahabad ç
during themonth of M<193>gha (January) and the religious fair goes ç
by the name `M<193>ghamel<193>'. Once in 12 years is held the biggest ç
religious fair of the whole world, called `Kumbhamel<193>'.
@NT = Mausalaparva
@N1 = (`the book of musala or pestle')
See <MS>MAH°BH°RATA.<D>
@NT = Maya
The seeds of the Mah<193>bh<193>rata war were sown at the exquisitely ç
beautiful palace of the P<193><207><195>avas in Indraprastha, their ç
capital. It was here that Duryodhana was subject to an optical illusion ç
making himself a subject for laughter of Draupad<200>.
And, the builder of this wondrous place was Maya, the chief architect ç
of theasuras or demons. When Arjuna cleared the forest Kh<193><207><195>avavana ç
for being consumed by Agni, the god of fire, Maya who was living there ç
took refuge in Arjuna and K<216><218><207>a who saved his life. (Mah<193>-bh<193>rata, ç
°diparva 228). As a token of hisgratitude, Maya built the palace ç
at Indraprastha (the new capital of the P<193><207><195>avas). He ç
also gave a divine gad<193> (mace) to Bh<200>ma and the ·a<209>kha ç
(conch) Devadatta to Arjuna.
Maya was the son of Ka·yapa and his third wife Danu. Even from his ç
boyhood days he was interested in the science  of  architecture.  He  acquired ç
proficiency in it by appeasing Brahm<193>, the creator, through severe ç
austerities. For some time he was the king of the d<193>navas (demons). ç
Hem<193> was his queen. The two fierce demons, M<193>y<193>v<200> ç
and Dundubhi, were his sons and Ma<207><195>odar<200> was his daughter. ç
She was given in marriage to R<193>va<207>a of La<209>k<193>.
`Mayamata' is the science of architecture attributed to him.
Vi·vakarma the chief architect of the devas or gods was his rival ç
in this field.
@SPACE = 
@NT = m<193>y<193>
@N1 = (`that which does not [really] exist')
@SPACE = 
If God, the Absolute†called Brahman or °tman in the Upani<218>ads†is ç
`ekam eva advit<200>yam' or `One only, without a second', how can ç
he become this world of duality or multiplicity?†is a question that ç
has puzzled many an Indian philosopher for ages. The Advaita Ved<193>nta ç
school which was  vigorously  propagated  by  <185>a<209>kara (<MS>A. ç
D.<D> 788-820) solves this problem by putting forth the theory that ç
it is due to m<193>y<193>, an inscrutable and apparent power of Brahman ç
which functions in two ways. It covers the real nature of Brahman ç
ascaitanya or pure consciousness and projects this world of duality ç
in that Brahman as the substratum. These two aspects of m<193>y<193> ç
are respectively called `<193>vara<207>a·akti' and `vik<218>epa·akti'.
At the individual level, m<193>y<193> is termed `aj<210><193>na'. ç
At the cosmic level, though m<193>y<193> lasts for the full cycle ç
of creation, at the individual level, it can be eliminated by j<210><193>na ç
or spiritual know-ledge.
@SPACE1 = 
An illustration can make this point clear. A piece of rope lying on ç
the road appears like a snake for a person passing by it at dusk. ç
The semidarkness successfully hides its real nature as the rope and ç
projects the illusion of a snake on it simultaneously producing fear ç
in his mind. If that person however, brings a light and a stick to ç
kill it, he discovers that it is only a rope! He then, perhaps, laughs ç
at it and goes away. But, the next day, if he is passing by the same ç
road at the same time, he will again see the rope as a snake but does ç
not react with fear. This is because his ignorance regarding it has ç
now been destroyed. The semidarkness of the dusk and the snake-like ç
shape of the rope being external to him, the illusion itself persists. ç
What has changed is only his personal reaction. Similarly when a person ç
destroys his personal avidy<193> or aj<210><193>na through spiritual ç
illumination, his reactions to the world and its affairs will undergo ç
a thorough transformation, though the world itself†being a product ç
of m<193>y<193>†will continue to remain as it is.
Even <185>a<209>kara accords a much greater degree of reality to the ç
world and calls it `vy<193>vah<193>rikasatt<193>,' an empirical truth.
M<193>y<193> or M<193>y<193>pur<200> is the same asHaridv<193>ra ç
(the modern Hardwar in Uttaranchal), one of the seven most important ç
places of pilgrimage situated on the river Ga<209>g<193>.
In the pur<193><207>as and tantras, M<193>y<193> is one of the names ç
of the Divine Mother.
The word also stands for the b<200>ja (seed-letter) `hr<200><221>' ç
of the Divine Mother.
The Jay<193>khyasa<221>hit<193> (8.77) states that M<193>y<193> ç
is one of the four <185>aktis of Vi<218><207>u the other three being ç
Lak<218>m<200>, Jay<193> and K<200>rti.
See also <MS>ADVAITA VED°NTA DAR<185>ANA.
@NT = m<193>y<200>yamala
@N1 = (`the impurity of m<193>y<193>')
The various schools of <185>aivism, have many things in common. One ç
of them is the concept of malas or impurities. They are three: <193><207>avamala, ç
m<193>y<200>yamala and k<193>rmamala.
Though the pa·u or the j<200>va (indi-vidual Self) is actually <185>iva ç
in essence, he has become the very limited J<200>va due to his false ç
association with the body-mind complex. This impurity of limitations ç
is <193><207>avamala.
M<193>y<193> is the power of <185>iva responsible for this creation ç
of multiple objects, namesand forms. Seeing this multiplicity, considering ç
it as real and getting involved in it, is the m<193>y<200>yamala, ç
mala (impurity) brought about by m<193>y<193>.
The mala brought about by karma (effect of actions of previous lives) ç
is k<193>rmamala.
@NT = medh<193>janana
See <MS>J°TAKARMA.
@NT = Medh<193>s<220>kta
@N1 = (`hymn of Medh<193>, the<R>ç
goddess of comprehension')
To understand the correct meaning of the scriptures, power of intellect ç
and comprehension  as  also  retention  in memory are very necessary. ç
All these are reflected in that one wonderful word `medh<193>·akti'. ç
Medh<193> has been conceived in the Vedas as a goddess presiding over ç
the power of memory and understanding.
There are two Medh<193>s<220>ktas available now. The first is a ç
khila, addendum, occurring at the end of <185>raddh<193>s<220>kta ç
(<184>gveda 10.151). The second forms a part of the Taittir<200>ya ç
°ra<207>yaka (10.39.42) and occurs in the body of the Mah<193>n<193>r<193>ya<207>a ç
Upani<218>ad (43). It is a short hymn of only five mantras.
A free translation of these verses can now be given:
May the all-penetrating goddess of intellect (Medh<193>dev<200>) who ç
is auspicious, well-disposed towards us, delighted with us come to ç
us. May we, who were delighting in profitless speech before your visit, ç
be now blessed by you, become enlightened and speak†along with our ç
heroic progeny†forcefully expressing the Supreme Truth.
O Medh<193>devi! Favoured by you, one becomes a <216><218>i (seer), ç
a br<193>hma<207>a (knower of Brahman) or a possessor of riches, of ç
various types. O goddess of intellect! Kindly bless us with the best ç
of wealth.
May Indra grant me intelligence. May the goddess Sarasvat<200> grant ç
me intelligence. May the twins, the A·vins, wearing garlands of lotus, ç
generate intelligence inme.
May that Medh<193>dev<200> who resides in the apsaras (celestial maidens), ç
who is the mental power of the gandharvas (a type of demi-gods), who ç
is the Vedic lore (Sarasvat<200>) belonging to the gods, who spreads ç
like fragrance, favour me!
That Medh<193> (the goddess of intelligence) who is fragrant, who ç
is of the form of retention in memory of all ·<193>stras, who is of ç
golden hue, who is pervading the world, who is fit to be resorted ç
to by the seekers, who is full of strength, who nourishes us by milk, ç
may she come to me with a joyful face and favour me.
@SPACE = 
@NT = Medh<193>tithi
@SPACE = 
The Manusm<216>ti is, perhaps, one of the most ancient and authoritative ç
worksin the dharma·<193>stra literature. The earliest and exhaustive ç
commentary on it is the bh<193><218>ya of Medh<193>tithi. Circumstantial ç
evidence as gleaned from other works of dharma·<193>stra points to ç
the period <MS>A.<|>D.<D> 825-900 as his probable period.
The Manusm<216>ti with the bh<193><218>ya of Medh<193>tithi has ç
been published three or four times.
Nothing is known of Medh<193>tithi. Some scholars feel that he belonged ç
to South India while others assert that he hailed from Kashmir.
He seems to have been a deep scholar of  P<220>rvam<200>m<193><221>s<193>  system  and  quotes ç
numerous writers of an earlier period such as Gautama, °pastamba, ç
Baudh<193>yana, Vasi<218><219>ha, Par<193>·ara, B<216>haspati and ç
others. He has drawn upon the Artha·<193>stra of Kau<219>ilya (321-300 ç
<MS>B.<|>C.<D>) in numerous places as also the s<220>tras of P<193><207>ini ç
(400 <MS>B.<|>C.<D>) and the bh<193><218>ya of Pata<210>jali (200 <MS>B.<|>C.<D>).
He also brings in several ny<193>yas or maxims for explaining Manusm<216>ti, ç
like the K<193>kat<193>l<200>yany<193>ya (on 1.12) and Vi·vajit-ny<193>ya ç
(on 2.2).
It is interesting to note that the text of the Manusm<216>ti on ç
which he has commented is practically the same as we have now.
@NT = meditation
See <MS>BHAKTIYOGA<D> and <MS>DHY°NA.<D>
@NT = Meghan<193>da
See <MS>INDRAJIT.<D>
@NT = Melko<219>e
Places of pilgrimage have played a very important role in preserving ç
and reforming Hindu religion and culture. If some places have acquired ç
importance due to the location of famous temples, and, others due ç
to the association with great saints, Melko<219>e, a small town in ç
the Mandya district of Karnataka State of South India, has the distinction ç
of both. The ancient temple of N<193>r<193>ya<207>asv<193>mi and the ç
intimate association with R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137) ç
the doyen among the teachers and propagators of the Vi·i<218><219><193>-dvaita ç
Ved<193>nta school, over a period of twelve years have made this little ç
sleepy town, one of the four chief fortresses of the cult of <185>r<200>vai<218><207>avism.
Situated 48 kms. north-west of Mysore  and  157  kms.  south-west  of ç
Bangalore†the capital of Karnataka†the Melko<219>e town is perched ç
on a small hillock of pink granite, that rises about 150 metres above ç
the surrounding plains. It has a salubrious climate and agriculture ç
is the main occupation of the residents.
Known variously, over the centuries, as Melgo<219>e, Y<193>davagiri, ç
Tirun<193>r<193>ya<207>a- puram, Bh<220>loka-Vaiku<207><219>ha and ç
Dak<218>i<207>a- Badarik<193>·rama, its political control had changed ç
hands several times due to the vicissitudes of history. The Ga<209>gas ç
(8th century), the Co<202>as (10th and 11th centuries) and the Hoysa<202>as ç
(12th century) werethe main dynasties that ruled over Melko<219>e ç
before R<193>m<193>nuja's arrival. Rulers of Vijayanagara empire and ç
the Wo<195>eyars of Mysore controlled it in later times.
It was during the rule of Vi<218><207>u- vardhana (<MS>A.<|>D.<D>  1106-1142)  of  Hoysa<202>a ç
dynasty that R<193>m<193>nuja arrived at Melko<219>e incognito from ç
<185>r<200>ra<209>gam (now in Tamil Nadu) to escape from persecution ç
at the hands of the <185>aiva rulers there. Sometime during this period ç
of his stay at Melko<219>e (<MS>A.<|>D.<D> 1117-1128) he renovated ç
the ancient N<193>r<193>ya<207>asv<193>mi temple with the King's help ç
and reorganized its rituals and management. Over the years this temple ç
town has grown into an influential seat of the cult of <185>r<200>vai<218><207>avism ç
with several temples and ma<219>has (traditional monasteries) accruing ç
to it.
@SPACE1 = 
Apart from the N<193>r<193>ya<207>asv<193>mi temple complex, the only ç
other major temple is that of Narasi<221>ha (`Man-lion' incarnation ç
of Vi<218><207>u) situated on the top of the hillock adjoining the ç
Kaly<193><207><200> or temple-tank. There are, of course, several ç
minor but  independent  shrines  outside  the temple-complex. Shrines ç
dedicated to Ve<209>ka<219>arama<207>a (an aspect of Vi<218><207>u ç
as found in Tirupati), Var<193>ha (`Boar-incarnation' of Vi<218><207>u) ç
and R<193>ma are near the Kaly<193><207><200>. Two shrines†one of ç
Ga<207>apati and another of K<193>l<200>†are situated in two different ç
corners, a little away from habitation.
Apart from these temples and shrines, there are also four ma<219>has ç
or monasteries well-known in the annals of the history of <185>r<200>vai<218><207>avism: ç
Ahobila Ma<219>ha, Parak<193>la Ma<219>ha, V<193>nam<193>malai Ma<219>ha ç
and Yatir<193>ja Ma<219>ha.
The N<193>r<193>ya<207>asv<193>mi temple†also called Celuvar<193>yasv<193>mi ç
temple in the local language†is the most sacred and important structure ç
situated at the southern end of the flat plateau occupied by the present ç
town. It is rectangular in plan (75 x 60 metres) and faces east. The ç
garbhag<216>ha (cella) and the ardhama<207><195>apa (passage-hall) ç
are the oldest part of the structure built probably during the early ç
part of the 11th century. Additional structures like pradak<218>i<207><193> ç
(passage for circumambulation) and pillared corridors or halls have ç
been continually added right up to the early part of the 19th century.
Apart from the shrine for the main deity N<193>r<193>ya<207>a, there ç
are subsidiary shrines for the Dev<200> (known as `T<193>y<193>r' ç
orMother and `Yadugiri Nacciyar'), the procession image known as ç
`<185>elvapi<202><202>ai', R<193>m<193>nuja and a few other saints.
The gopuram or tower over the main entrance is imposing.
@SPACE1 = 
Out of the several annual festivals of this temple the Brahmotsava ç
conducted during March-April is the biggest. It is spread over twelve ç
days. Since the deity is adorned with the `Vairamu<195>i' (a huge ç
diamond crown of unknown antiquity) on the night of the sixth day, ç
the festival isalso called `Vairamu<195>i Utsava'. This attracts ç
a very huge gathering every year.
The only other temple of almost equal importance in Melko<219>e is ç
the Narasi<221>ha-sv<193>mi temple located at the highest peak of ç
the eastern fringe of the hill. There is a flight of steps leading ç
to it. Half-way up, two rock-cut caves are also seen.
There is a Sanskrit school (p<193><219>ha·<193>l<193>) attached to ç
the main temple. In the recent times a big institute has come up in ç
the town for encouraging studies in Vi·i<218><219><193>-dvaita Ved<193>nta ç
as also research.
See also <MS>R°M°NUJA<D>, <MS><185>R®VAI<186>ØAVISAM<D> and <MS>VAIRAMU£I.<D>
@NT = Meru
@N1-1 = (`that which throws away [or reflects light]')
Also called Sumeru, this mountain is described as the axis of the ç
whole world. It is golden in colour and is very bright. Its total ç
height is one lakh yojanas† 15lakh kms. or 9 lakh miles since one ç
yojana is 15 kms. or 9 miles†of which 16,000 yojanas (2,40,000 kms. ç
or 1,44,000 miles) are below the earth and 84,000 yojanas (12,60,000 ç
kms. or 7,56,000 miles) above it. It is situated in the centre of ç
the Jamb<220>dv<200>pa and Bh<193>ratavar<218>a (India) is to its ç
south.
On its top there is flat plateau of 32,000 yojanas (4,80,00 kms. or ç
2,88,000 miles). It is here that Brahm<193> (the creator), his m<193>nasaputras ç
(mind-born sons) like Dak<218>a, the Saptar<218>is like Vasi<218><219>ha ç
live (vide Mah<193>bh<193>rata, Vanaparva 162; Bh<193>gavata ç
5.16).
@SPACE1 = 
TheKed<193>rn<193>thmountain(inthe Garhwal district of Uttaranchal) ç
is traditionally believed to be the original Meru.
In a japam<193>l<193> (rosary), there is an extra bead fixed perpendicularly ç
to the m<193>l<193> and above it. This is also called `meru' and is ç
not to be crossed over while doing japa.
@NT = Meyka<207><195><193>r
@N1 = (`discoverer of Truth')
The <185>aivasiddh<193>nta is an ancient school of <185>aivism prevailing ç
in the Tamil country. Of the four major teachers of this school, Meyka<207><195><193>r ç
(or Meyka<207><195>adeva) was the greatest. He is said to have lived ç
around <MS>A.<|>D.<D> 1235. He was a disciple of Para<210>joti   Muni   and   belonged   to ç
Tiruvenneyllur  near  the  South  Arcot district of the present day ç
Tamil Nadu. An inscription of the Co<202>a King R<193>jar<193>ja III ç
(<MS>A.<|>D.<D> 1216-1248) refers to the gift of land to Meyka<207><195><193>r.
<185>ivaj<210><193>nabodham is the cardinal work of <185>aivasiddh<193>nta ç
attributed to him. This is a brief work of 12 k<193>rik<193>s or s<220>tras ç
(in Tamil) selected from the Raurav<193>gama. The k<193>rik<193>s ç
seem to be translations of the original Sanskrit text culled from ç
that <193>gama.
The title <185>ivaj<210><193>nabodham is interpreted as: `<185>ivam ç
is One; j<210><193>nam is the knowledge of Its true nature; bodham ç
is the realisation of such knowledge.'
See also <MS><185>AIVISM.<D>
@NT = M<200>m<193><221>s<193> Dar·ana
@SB = Introduction
If there is any system of Hindu philosophy where the Book becomes ç
more important than the Maker of the Book, itis the M<200>m<193><221>s<193>. ç
Also called P<220>rva-m<200>m<193><221>s<193> Dar·ana, it primarily ç
aims at giving a methodology of interpretation with the help of which ç
complicated Vedicinjunctions regarding rituals may be understood ç
and given effect to.
Vedic ritualism believes that:
@NO = 1)
@NOK = there is a soul which survives the death of the body and enjoys ç
the fruits of the rituals in heaven;
@NOX = 2)
@NOK = there is a ·akti or power of potency which preserves the effects ç
of the rituals performed;
@NOX = 3)
@NOK = the Vedas are infallible;
@NOX = 4)
@NOK = this world is real;
@NOX = 5)
@NOK = our life and actions performed here are real and not mere dreams.
@SB = Basic Works
The M<200>m<193><221>s<193>s<220>tras of Jaimini (200 <MS>B. C.<D>) ç
is the basic text of this system. Itis a voluminous work comprising ç
more than 2500 aphorisms divided into 12 chapters and 60 subsections ç
in all.
The Bh<193><218>ya of <185>abara Sv<193>min (57<MS> B.C. <D>or ç
<MS> A.D.<D>200) gives the most authoritative interpretation of ç
the s<220>tras. <185>abara's Bh<193><218>ya has two commentaries. ç
The B<216>hat<200> of Prabh<193>kara (<MS>A.<|>D.<D> 650), still ç
in the manuscript form, is the first. The second is by Kum<193>rila ç
Bha<219><219>a (<MS>A.<|>D.<D> 700) in three parts: <185>lokav<193>rttika, ç
Tantra-v<193>rttika and <187>up<219><200>k<193>. Prakara<207>apa<210>cik<193> ç
of <185><193>likan<193>tha (a pupil of Prabh<193>kara), <185><193>strad<200>pik<193> ç
of P<193>rthasarathi (<MS>A.<|>D.<D> 900), Ny<193>yam<193>l<193>vistara ç
of M<193>dhava Vidy<193>ra<207>ya (<MS>A.<|>D.<D> 1350) and Arthasa<209>graha ç
of Laug<193>k<218>i Bh<193>skara (17thcent. <MS>A.<|>D.<D>) are some ç
of the other works of this system.
@SB = Theory of Knowledge
To justify the supreme authority of the Vedas, the M<200>m<193><221>s<193> ç
Dar·ana has developed an elaborate epistemology which has been accepted ç
by other schools also, especially the Ved<193>nta Dar·ana.
For knowledge to be valid, three conditions have to be fulfilled. ç
They are:
@NOX = (1)
@NOK = It should yield some new information previously unknown.
@NOX = (2)
@NOK = It should not be contradicted by any other knowledge.
@NOX = (3)
@NOK = The conditions which generate that knowledge  should  be  free  from ç
defects.
@SPACE = 
The M<200>m<193><221>s<193> admits of two kinds of knowledge: pratyak<218>a ç
(immediate) and parok<218>a (mediate).
The latter, again, is of five kinds: anum<193>na (inference), upam<193>na ç
(comparison), ·abda (verbal testimony, also called `<193>ptav<193>kya', ç
words of a reliable person), arth<193>patti (postulation) and anupalabdhi ç
(non-perception).
These may now be briefly described.
<MS>PRATYAK<186>A<D> (direct or immediate perception) has two stages ç
of development. As soon as the sense-organ comes into contact with ç
the sense-object, there is a general awareness of it, as something ç
existing. This is called nirvikalpaka-pratyak<218>a. In the next stage, ç
all the details will be noted in the light of past experience. This ç
is savikalpaka-pratyak<218>a.
<MS>ANUM°NA<D> (inference) gives us the knowledge of a thing indirectly, ç
when we see some li<209>ga or sign invariably connected with the original. ç
For instance, by seeing smoke on a yonder hill, we can infer that ç
there is fire there (even though we do not see it directly), since ç
it is known from previous observations and experience that smoke is ç
invariably associated with fire.
<MS>UPAM°NA<D> (comparison) is another source of knowledge. On seeing ç
a rat, one recollects that it is like the mouse he had seen earlier. ç
He then comes to know thatthe remembered mouse is like the perceived ç
rat. This type of knowledge comes through upam<193>na.
<MS><185>ABDA<D> (verbal testimony) is the next source of knowledge. ç
The M<200>m<193><221>s<193> Dar·ana pays the greatest attention to ç
this since it has to justify the undisputed authority of the Vedas.
The words of a reliable person are believed to be true. This is called ç
<193>ptav<193>kya.
Verbal testimony, however, is of two types: pauru<218>eya (personal, ç
same as <193>ptav<193>kya) and apauru<218>eya (impersonal). The second ç
denotes the Vedas since they were not created by any human agency. ç
The Vedas are supremely authoritative since they are the `Book of ç
Commandments' and also give us authentic know-ledge of the unseen ç
and the unknown truths. Again, their main purport and purpose lies ç
in propagating sacrificial rites.
The Vedas are eternal, not as the printed Book nor as the orally transmitted ç
mantras but as the eternal teachings contained in them. These teachings ç
are conveyed through the <216><218>is or sages in every age.
@SPACE1 = 
Since the Vedas are mainly concerned with giving commands (= vidhi) ç
about the y<193>gas or sacrificial rites and other associated rituals, ç
only those sentences containing such commands as expressed through ç
the verbs couched in `vidhili<209>' (imperative  mood  as  in  `svargak<193>mo ç
yajeta', `One desirous of attaining heaven should sacrifice!') and ç
other forms should be taken as authoritative and others as aids to ç
it. Such verbs have an innate power of urging the hearer to do the ç
sacrifice. This is called `bh<193>van<193>'. The urge contained in ç
the Vedic words is known as `·<193>bd<200>bh<193>van<193>' (·abda ç
= word). On hearing it, the person who hears it, gets the urge to ç
perform it. This secondary urge is named `<193>rth<200>bh<193>van<193>' ç
(artha = utility, useful activity).
All this depends upon the correct understanding and interpretation ç
of the Vedic sentences. For this, the M<200>m<193><221>s<193> gives ç
six steps: upakrama (beginning) and upasa<221>h<193>ra (concluding); ç
abhy<193>sa (repetition for the sake of emphasis); ap<220>rvat<193> ç
(not being known earlier by any other means); phala (utility); arthav<193>da ç
(mere eulogy) and upapatti (logic and reasoning).
Once the correct meaning is thus ascertained, the command can be implemented.
<MS>ARTH°PATTI<D> (postulation or presumption) is the necessary supposition ç
of an unperceived factwhich alone can explain an anomaly satisfactorily. ç
For instance, if a person is noticed to be getting fat even though ç
he does not eat during the day,it can safely be presumed that he ç
is secretly eating at night! Knowledge obtained by arth<193>patti ç
is distinctive since it cannot be got by any other means.
<MS>ANUPALABDHI<D> (non-perception) has also been accepted as a source ç
of know-ledge since it gives the immediate cognition of the non-existence ç
of an object. If it is found that a jar which had been kept on a table ç
earlier, is not perceived now, its non-existence is cognized.
@SPACE1 = 
Since the validity of knowledge that we get is an important aspect ç
of our life, giving rise to necessary activities, this has been discussed ç
in detail by the writers of M<200>m<193><221>s<193> works.
Incidentally, they also discuss how errors creep in, giving their ç
own explanations and theories. This has led to two different views.
When a snake is perceived in a rope in dim light, though the rope ç
seen now and the snake seen in the past are both real, a mixing ç
up takes place due to a lapse of memory giving rise to a reaction ç
of fear. This is called akhy<193>tiv<193>da (denial of illusory ç
perception).
In the second view known as vipar<200>ta-khy<193>tiv<193>da, the ç
error consists in wrongly relating two really existing, but separate, ç
entities.
@SB = Metaphysics
@S10N = a)	The World
Unlike some other systems (like Advaita Ved<193>nta) the M<200>m<193><221>s<193> ç
believes in the reality of the world, with all the myriad objects ç
in it. This world, according to it, comprises the living bodies including ç
the various indriyas or the sense-organs, wherein the souls reside ç
temporarily to reap the effects of their karmas, good or bad. The ç
various objects of the world serve as the fruits to be suffered or ç
enjoyed.
@S10N = b)	The Soul
There are infinite number of souls. They are eternal but undergo transmigration ç
due to their karmas (good or bad deeds) performed when encased in ç
real bodies in a real world.
The soul has no consciousness of its own. Consciousness rises in it ç
due to association with the mind, the sense- organs and the sense-objects, ç
especially when the organs come into contact with their respective ç
objects. This is proved bythe absence of consciousness in the deep-sleep ç
state.
When a person performs Vedic sacri-fices like Jyoti<218><219>oma, ç
say to get to heaven, the potential effect of it in a subtle form ç
resides in his soul and will give its fruit after death. This potential ç
imperceptible power or ·akti, is called `ap<220>rva'.
Since the whole of the Vedas are meant to urge the human beings to ç
perform karmas (Vedic rituals), every human being is bound to do his ç
duty for duty's sake. A ritual is to be done, only because the Vedas ç
command it and none has the choice not to do it or do it in a ç
different way!
Such duties are classified into two broad groups: nitya or daily obligatory ç
duties and naimittika or occasional (but obligatory) duties. These ç
help in the purification of the soul through moral improvement.
@S10N = c)	Mok<218>a or liberation
The highest good (ni··reyasa) for a person is to get mok<218>a or ç
liberation, total cessation of transmigratory existence. In this state ç
the soul is permanently free from all pain and suffering though there ç
is no consciousness or bliss!
The  ultimate  goal  of  life  was, probably, according to the earlier ç
conception of the M<200>m<193><221>s<193>, the attainment of unalloyed ç
bliss in heaven. However, the available literature does not support ç
it.
How to attain mok<218>a?†is a question that has been answered in a ç
rather simplistic way. Not performing k<193>mya- karmas or desire-motivated ç
actions will not cause rebirth. Sins committed unwillingly can be ç
offset by the performance of the various pr<193>ya·cittas (expiatory ç
rites). Performance  of  nitya  and  naimittika karmas will bring ç
about citta·uddhi or purity of mind whereas their non-performance ç
will result in pratyav<193>yado<218>a or the error of omission, proving ç
to be an obstacle in the path of mok<218>a. Pr<193>rabdhakarma (karma ç
that has caused this birth) is exhausted by experience in this life. ç
So, when the body falls, there is no residual factor that can bring ç
the soul back to this world onceagain. Consequently liberation is ç
attained automatically.
@S10N = d)	®·vara or God
Another question that is discussed and discarded by the M<200>m<193><221>s<193> ç
system is whether ®·vara or God exists or not. Since all the materials ç
that make up the physical world are eternally existing and since the ç
ad<216><218><219>as or the karmas of the souls impel these materials ç
in the process of creation, there is no need to accept any God as ç
the agent or author of creation.
@SPACE = 
@SB = Epilogue
@SPACE1 = 
@SPACE1 = 
It is rather strange that a system that champions the supremacy of ç
the Vedas goes to the extent of enthroning the Book as God, and, dethrone ç
and abandon its maker! Let alone God, even the various deities like ç
Indra, Mitra and Varu<207>a who are invoked in the sacrificial rites ç
to receive the offerings, are treated more like the imaginary characters ç
of a fictitious drama.
@SPACE1 = 
It may not be wrong to declare that by overemphasizing the means to ç
the detriment<|><|>of<|> the<+>end,<|><|>the M<200>m<193><221>s<193><+>dug
