@NID = its own grave as a living system of philosophy.
However, an earnest study of its theory of knowledge as also its method ç
of interpreting the Vedic sentences will be of great help in understanding ç
the Ved<193>ntic systems better.
@NT = mind
@SB = Introduction
@EMERGENCY = Hindu view of life accords great importance to the mind ç
since both abhyu-daya (worldly prosperity) and ni··reyasa (spiritual ç
progress) depend upon its condition. An impure mind binds the soul ç
to transmigratory existence whereas a pure mind leads to mok<218>a ç
or liberation (Am<216>ta-bindu Upani<218>ad 2).
While recognising the importance of the mind as a distinguishing unique ç
feature of human beings, the Hindu scriptures and the various systems ç
of Hindu philosophy have given different views about its content, ç
nature and function. A study of the mind, therefore, will not only ç
be interesting but also useful in one's personal life of spiritual ç
evolution.
@SB = What the Mind is
The Ch<193>ndogya  Upani<218>ad  (6.6.5) declares that the mind ç
is `annamaya,' made up of the subtle essence of food. It also asserts ç
that purity of food conduces to purity of mind (ibid 7.26.2).
The B<216>had<193>ra<207>yaka Upani<218>ad (1.2.1) describes  the  mind  as  having  been ç
produced from ®·vara or Hira<207>yagarbha (Creator). It also declares, ç
though indirectly, that the soul or the Self (<193>tman) knows the ç
external world through the mind (vide 1.5.3).
The S<193><209>khya and the Yoga systems consider the mind as a product ç
evolved from the insentient prak<216>ti, a direct product from aha<209>k<193>ra ç
(the ego-principle) and hence made up of the three gu<207>as† sattva, ç
rajas and tamas. It is also, therefore, ja<195>a or insentient but ç
can reflect the consciousness of the puru<218>a or the <193>tman (the ç
soul).
The Ny<193>ya-Vai·e<218>ika schools consider the manas or the mind ç
as one of the dravyas (fundamental or basic realities) out of which ç
the world is eventually created. It acts as a link between the soul ç
and the sense-organs by which the external objects are known.
Certain cults of <185>aivism and <185><193>kt<193>ism (tantras) advocate ç
the theory that mind is a limitation or a modification of pure consciousness.
As regards the size of the mind, some systems like Ny<193>ya and Vai·e<218>ika ç
hold itas a<207>u (atomic) while others (Advaita Ved<193>nta)  consider  it  as  vibhu  (all- ç
pervading).
@SB = Importance of the Mind
The ultimate purpose of human life is to attain mok<218>a or liberation ç
from transmigratory existence. This is possible only when s<193>dhan<193> ç
or spiritual practice is undertaken as per the dictates of the scriptures. ç
S<193>dhan<193> consists mainly in purifying the mind through proper ç
personal morality, social ethics and religions observances. When the ç
mind becomes completely pure, the <193>tman inside is automatically ç
revealed.
Impurities of the mind are of three types: basic impurity due to its ç
being a product of the three gu<207>as (sattva, rajas and tamas); ç
impurities carried over from the previous lives, technically called ç
`sa<221>sk<193>ras'; impurities due to the sins and evils committed ç
in this life.
The third one can be offset by the performance of pr<193>ya·cittas ç
or expiatory rites prescribed in the holy books as also by experiencing ç
the suffering brought about by them. The second has to be counteracted ç
by trying hard to cultivate the opposite, good, tendencies. When these ç
are carried out, along with nididhy<193>sana or meditation on oneself ç
as the pure <193>tman (ultimately one with Brahman) or any aspect ç
of God, the r<193>j<193>sik and the t<193>masik contents of the mind ç
gradually get attenuated and the s<193>ttvik part gets predominance. ç
When this process is completed, realisation can come in a flash.
@SPACE = 
@SB = Mind and the °tman
@SPACE = 
Most  of  the  Hindu  philosophical systems consider the mind either ç
as an up<193>dhi (limiting adjunct) or as a quality of the j<200>v<193>tman ç
(the individual soul). It is through the mind that the j<200>v<193>tman ç
knows the external world or gets internal experiences.
@SPACE = 
@SB = Functions of the Mind
@SPACE = 
There are several ways of looking at the functions of the mind. Works ç
on Ved<193>nta generally define the mind as `anta<199>kara<207>a' ç
(the inner organ) and state that it has fouraspects: manas (general ç
thinking and cognition); buddhi (discriminative faculty); aha<209>k<193>ra ç
(ego-sense); citta (mind-stuff, responsible for memory).
According to another view it has three qualities or functions or modifications: ç
j<210><193>n<193>tmaka   (cognitive);   <193>veg<193>tmaka (emotional); ç
prayatn<193>tmaka (volitional).
Cognition, again, can produce either pram<193> (true knowledge) or ç
bhrama (false knowledge). The latter includes sa<221>·aya or doubt ç
also.
Pram<193> or true knowledge can be produced by six ways out of which ç
pratyak<218>a (direct perception), anum<193>na (inference) and <193>ptav<193>kya ç
(verbal testimony of reliable persons) are universally accepted. <185>abda ç
or <185>ruti or °gama is an extension of the last, as applied to things ç
beyond the ken of the senses.
The emotional functions of the mind can be listed as follows: sukha ç
(pleasure or happiness), du<199>kha (pain or unhappiness), icch<193> ç
(desire) and dve<218>a (hatred).
Many other kinds of emotions are also recognised, such as bhaya (fear), ç
h<193>sya (laughter), vismaya (wonder) and so on.
Ved<193>ntic works often mention three states of consciousness with ç
a view to proving that the <193>tman (the soul) is the pure spirit ç
beyond them. These three states†all of the mind†are j<193>grat (waking ç
state), svapna (dream state) and su<218>upti (deep-sleep state).
@SB = Extra-sensory Perceptions
Besides these states of the mind normally experienced  by  all,  there  is ç
another, the extra-ordinary or the extra- sensory perception. Highly ç
evolved spiritual persons have attained these states like clairvoyance, ç
clairaudience and so on, which have been described in the standard ç
treatises of yoga like the Yogas<220>tras ofPata<210>jali (200 ç
<MS>B.<|><|>C.<D>) (vide 3.16-55). However these have been considered ç
as obstacles to the final emancipation since they tempt the s<193>dhaka ç
to misuse them.
@SB = Conclusion
The main purpose behind the study of the mind is to facilitate its ç
ultimate purification leading to the realisation of the <193>tman ç
or the Self. Though there are differences of opinion regarding its ç
nature, the processes of purification are almost universally accepted.
@NT = M<200>r<193>b<193><200>
@N1 = (<MS>A.<|>D.<D> 1547-1614)
One of the brightest jewels of the Bhakti Movement†a movement that ç
raised, roused and united the common masses as well as the blue bloods ç
through divine love†was M<200>r<193>b<193><200>.
She was born as the daughter of Ratan Singh at Kudki, a village in ç
Rajasthan. When she was still three years old, she was tremendously ç
attracted by the image of Giridhar (Lord K<216><218><207>a) that a ç
s<193>dhu (a holy man) had brought. Her piteous pleadings ultimately ç
forced the s<193>dhu to leave the image with her.
When she was five, a marriage party was passing by the road in front ç
of her palatial house. She innocently asked her mother who her bridegroom ç
would be. Her mother smilingly replied that Giridhar was her bridegroom.
And, this statement stuck very deeply in her heart.
She lost her mother when she was just eight years old.
She was married to the prince Bhojr<193>j, the crown-prince of Mah<193>r<193><207>a ç
Sa<209>ga, the king of Mewar with the capital at Chittore. At her ç
husband's house she refused to bow down to their family deity Durg<193> ç
since she would recognise and honour only her Giridhar! Thus started ç
a series of frictions and troubles for her in the family.
When Bhojr<193>j died four years later M<200>r<193> intensified her ç
spiritual s<193>dhanas after receiving initiation from Raidas, the ç
famous saint of the day.
Soon after, R<193><207><193> Sa<209>ga too passed away and his second ç
son Vikramjit ascended the throne. Considering M<200>r<193>'s ascetic ç
way of life as also the congregational singing with devotees and mendicants ç
as a slur on the royal family, the R<193><207><193> tried his best ç
to harass her, and even kill her. But Giridhar was there always by ç
her side to protect her even as he had protected Prahl<193>da, the ç
child- devotee, ages ago.
M<200>r<193> finally left Chittore and travelling all the way like ç
a mendicant, through the various places of pilgrimage such as V<216>nd<193>ban, ç
she finally settled down at Dv<193>rak<193> in Gujarat.
At V<216>nd<193>ban she is said to have gone to meet J<200>va Gosv<193>mi, ç
a famous Vai<218><207>ava saint. When he refused to meet her since ç
she was a woman, she retorted that she thought in the world (and especially ç
in V<216>nd<193>ban) there was only one man†that was Lord K<216><218><207>a† ç
and all the others were women (prak<216>ti)! She was now surprised ç
to find another man! This opened the inner eye of the Gosv<193>mi ç
who begged her pardon.
@SPACE1 = 
Uday Singh, the new king of Mewar, being urged by the people to bring ç
back M<200>r<193> (whose banishment was thought to be the chief cause ç
for the troubles of Mewar) sent a batch of holy persons with the chief ç
priest (r<193>jaguru) as the leader for the purpose. M<200>r<193> ç
did not agree but was merged in the image of the Lord in the temple.
M<200>r<193>  was  the  paragon  of  the madhura-bh<193>va or bridal ç
mysticism.
M<200>r<193>'s songs are all composed in Brajbh<193><218><193>,  a  dialect  of  Hindi,  more ç
common in Brajbh<220>mi (Mathur<193>-V<216>nd<193>ban area). About ç
500 songs are available now.
Most of the songs are on <185>r<200> K<216><218><207>a though a few ç
are on R<193>ma and the efficacy of R<193>man<193>ma. The theme is ç
mostly pining for her Lord. Some of the songs however contain hints ç
for s<193>dhan<193> or spiritual practice also.
@NT = Mit<193>k<218>ar<193>
@N1-1 = (`[a work with] limited number of letters,' `a small work')
A Hindu's life, at the personal as well as the social level, has been ç
regulated by  the  dharma·<193>stras  for  over  two millennia. The<|>Y<193>j<210>avalkyasm<216>ti, ç
a metrical work in about a thousand verses, is one of the earliest ç
and most authoritative works. It has several commentaries out of which ç
the Mit<193>k<218>ar<193> of Vij<210><193>ne·vara (circa<MS>A.<|>D.<D> ç
1100) has been considered outstanding.
Vij<210><193>ne·vara was an expert in P<220>rva-M<200>m<193><221>s<193> ç
Dar·ana and applies its rules for determining the purpose of the ç
Sm<216>ti of Y<193>j<210>avalkya wherever there is doubt.
Though the Mit<193>k<218>ar<193>†also termed <184>jumit<193>k<218>ar<193>  and  Pramit<193>k<218>ar<193>†is ç
generally brief and clear, as the very name indicates, it also goes ç
into great details when needed.
The work quotes about 80 sm<216>tis and writers of dharma·<193>stras. ç
An interesting factor noticed is that it almost ignores the pur<193><207>as. ç
Only five pur<193><207>as have been quoted. Other, earlier, authors ç
quoted by it are Vi·var<220>pa (circa <MS>A.<|>D.<D> 800), Medh<193>-tithi ç
(<MS>A.<|>D.<D> 825-900) and Dh<193>re·vara (circa <MS>A.<|>D.<D> 1000).
The Mit<193>k<218>ar<193> has several commentaries out of which ç
the following are more noteworthy: Subodhin<200> of Vi·ve·vara-bha<219><219>a ç
(14th century <MS>A.<|>D.<D>); Pramit<193>k<218>ar<193> of Nandapa<207><195>ita ç
(<MS>A.<|>D.<D> 1580-1630); B<193>lambha<219><219><200> of B<193>lambha<219><219>a ç
or B<193>lak<216><218><207>a (<MS>A.<|>D.<D> 1730-1820).
There is also another Mit<193>k<218>ar<193> which is a commentary ç
on the Gautama-dharmas<220>tras by Haradatta (circa <MS>A.<|>D.<D> ç
1100).
See also <MS>Y°J<178>AVALKYA SM<184>TI.<D>
@NT = Mithil<193>
@N1 = (`where enemies are routed')
Mithil<193> has been a well-known city in the epics and the pur<193><207>as. ç
This was where the king Janaka (Vaideha or S<200>ra-dhvaja), father ç
of S<200>t<193>, lived and ruled over his kingdom, the Videha. It ç
was built by the king Mithi, grandson of Ik<218>v<193>ku.
It is sometimes identified with Janakpur in Uttar Pradesh near Nepal ç
border. Others think it is Tirhut in Bihar.
The epics and the pur<193><207>as have described it as a grand and ç
majestic city.
@NT = mithy<193>
@N1KERN = (`that which upsets or confuses the mind'); mithy<193>j<210><193>na ç
(`false knowledge')
The words `mithy<193>' and `mithy<193>j<210><193>na' are widely used ç
in the Advaita Ved<193>nta Dar·ana. If Brahman, the Absolute, is the ç
one and only Reality, the one without a second (tathya; eka; advit<200>ya), ç
then, all else that appears to exist†this world and the innumerable ç
beings in it†must be mithy<193>, unreal and false. To think that the ç
world is real, that the body-mind complex is itself the <193>tman ç
or the Self, is mithy<193>j<210><193>na or false knowledge.
The reason for this is avidy<193> or aj<210><193>na (nescience) which, ç
at the cosmic level, is called m<193>y<193>. It is an<193>di (without ç
beginning) but can be ended with vidy<193> or j<210><193>na (true ç
knowledge of the <193>tman/ Brahman).
See also <MS>AVIDY°.<D>
The Brahmavaivartapur<193><207>a describes Mithy<193> as the wife ç
of Adharma. Her brother is Kapa<219>a (deceit). These two are invisible ç
in the K<216>ta or Satya yuga, appear in a subtle form in the Tret<193>yuga, ç
half manifest in the Dv<193>parayuga and fully manifest, creating ç
havoc in the Kaliyuga.
Obviously this is a symbolic way of describing the gradual increase ç
of falsehood and deceit over the four epochs.
@NT = Mitra, mitra
@N1 = (`the friend')
Mitra is one of the important deities praised in the <184>gveda. ç
More often, he is praised along with Varu<207>a, another Vedic god. ç
He is one of the twelve °dityas (aspects of the Sungod, S<220>rya). ç
He resides in the antarik<218>a or sky and gives us rain. He impels ç
the people of the world towards constructive activity. He unites people ç
with mutual love and friendship. He sustains the world, protects it ç
and is capable of bestowing boons (vide <184>gveda 3.59.1, 2 and ç
7).
The word `mitra' has been used in a technical sense in political science, ç
to indicate an ally of a king. A mitra had to be courted either by ç
s<193>ma (spirit of reconciliation) or by d<193>na (the spirit of ç
give and take).
While  maitr<200>  or  an  attitude  of friendship has been recommended ç
by the Yoga-s<220>tras (1.33) as an aid to concentration of mind, ç
the characteristics of a true friend (mitra) are described as follows: ç
He will prevent you from committing sins. On the other hand he will ç
encourage you to do good deeds. He will keep your secrets. Hewill ç
praise your good qualities openly. He will not desert you in your ç
periods of crisis. He will give all assistance when needed (N<200>ti·ataka ç
of Bhart<216>hari 70).
@NT = mlecchas
@N1 = (`those who speak in an<R>ç
uncultured way')
The word `mleccha' has often been used in the epics and the pur<193><207>as ç
to describe the non-°ryan tribes who perhaps came  from  outside  the  country.  The ç
<185>atapatha Br<193>hma<207>a (3.2.1.23 and 24) declares that those ç
who speak an incorrect and  corrupt  dialect  are  asuras  and mlecchas. ç
The Gautama-dharmas<220>tras (9.17) prohibits a person from speaking ç
with mlecchas as also impure and irreligious persons. People of countries ç
beyond the °ry<193>varta, where the var<207><193>·rama system did ç
not exist, had been dubbed as mlecchas.
The Mah<193>bh<193>rata has some interesting details about the mlecchas: ç
1. They were produced from the tail of the celestial cow Nandin<200> ç
of Vasi<218><219>ha and drove away the army of Vi·v<193>mitra. 2. ç
They were living in the coastal regions and their king was A<209>ga. ç
3. A<209>ga was killed by Bh<200>ma in the Kuruk<218>etra war. 4. ç
The wealth that was left over in the y<193>ga·<193>l<193> (sacrificial ç
shed) of Yudhi<218><219>hira (after the A·vamedha sacrifice) was taken ç
away by the mlecchas. 5.Kalki, the future incarnation of Vi<218><207>u ç
will destroy the mlecchas who will be found everywhere in the world.
In the later period, by the time ofthe Bhavi<218>yapur<193><207>a ç
(<MS>A.<|>D.<D> 900), the mlecchas seem to have been absorbed as a ç
caste at the lowest rung of the social ladder. They have been described ç
as the eaters of cow's flesh and selling their children for financial ç
benefits. But they could worship the clay images of the Dev<200> and ç
other gods.
@SPACE = 
@NT = moha
@N1 = (`delusion', `confusion')
That state of mind which causes delusion and confusion, leading to ç
either ignorance or false knowledge, has been termed `moha' in the ç
Hindu philosophical works. It is caused by the excessive play of tamas. ç
Under its influence, one becomes extremely attached to the sense-objects ç
and completely loses the sense of discrimination. This naturally leads ç
to sa<221>s<193>ra or the cycle of transmigration.
Viveka (discrimination) arising out of the words of wisdom of the ç
scriptures as also of the spiritual preceptor, is the best antidote ç
for moha.
It has been included in the list of six enemies of spiritual evolution†generally ç
called `ari<218>a<195>vargas'†the others being k<193>ma (lust), krodha ç
(anger), lobha (greed), mada (arrogance) and m<193>tsarya (jealousy).
@SPACE = 
@NT = Mohenjo D<193>ro
See <MS>INDUS VALLEY CIVILISATION.<D>
@SPACE = 
@NT = Mohin<200>
@N1 = (`the enchantress')
At the behest of the gods who had been deprived of the ambrosia by ç
the demons during the churning of the ocean, Lord Vi<218><207>u appeared ç
as Mohin<200>, the enchantress, who successfully duped the demons ç
and distributed the nectar among the gods. Even <185>iva is said to ç
have been bewitched by her beauty.
The story teaches us that immortality (am<216>tatva) can be gained ç
only by the conquest of delusion (moha).
Mohin<200> is shown as a beautiful young woman wearing colourful garments, ç
decorated with ornaments and carrying a vase of nectar in hand.
@NT = mok<218>a
@N1 = (`liberation [from transmigratory existence]')
The topic of bandha (bondage) and mok<218>a (liberation) has been ç
widely discussed in all the systems of Hindu philosophy.
Man is essentially the <193>tman, the pure spirit, of the nature of ç
consciousness; but has somehow forgotten it and has identified himself ç
with the body-mind complex. As a result, he is constantly undergoing ç
transmigration, the cycle of birth-death-rebirth and so on. Whatever ç
suffering a man undergoes, is due to this identification with the ç
body and the mind, and consequent transmigration brought about by ç
karma.
This cycle of transmigration, called `sa<221>s<193>ra', can be ended ç
only by the realisation of the <193>tman. This again is achieved by ç
the destruction of aj<210><193>na or avidy<193> (ignorance) through ç
j<210><193>na (know-ledge). Once this is done, mok<218>a is attained.
Of course, there are other schools which advocate ni<218>k<193>ma ç
karma (action not motivated by selfish desires) or bhakti (devotion ç
to God resulting in his grace) as the means to mok<218>a.
Mok<218>a is posited as the final puru<218><193>rtha, the ultimate ç
goal of life.
The synonyms for mok<218>a are: mukti, kaivalya and nirv<193><207>a.
See also <MS>BANDHA.<D>
Some works like the S<220>tasa<221>hit<193> (Muktikha<207><195>a ç
3.28) describe four kinds of mukti or mok<218>a as follows: s<193>lokya ç
(living in the same world as God); s<193>r<220>pya (having a form ç
similar to that of God); s<193>m<200>pya (living near God); s<193>yujya ç
(getting identified or united with God). These ideas seem to have ç
existed in the Vedic literature itself (vide Taittir<200>ya Sa<221>hit<193> ç
5.7.5.7; Aitareya Br<193>hma<207>a 2.24; B<216>had<193>ra<207>yaka ç
Upani<218>ad 1.3.22; Ch<193>ndogya Upani<218>ad 2.20.2).
@NT = Mok<218>adharmaparva
The Mah<193>bh<193>rata has 18 parvas or books or sections, of which ç
the <185><193>ntiparva is the biggest. It contains the teachings ç
of Bh<200><218>ma from his bed of arrows to Yudhi<218><219>hira in ç
reply to the various questions put by the latter.
The Mok<218>adharmaparva is a subsection of the <185><193>ntiparva ç
and comprises the Chapters 174 to 365. It deals with a variety of ç
topics connected with spiritual life including mok<218>a or liberation.
See also <MS>MAH°BH°RATA.<D>
@NT = Monasticism
@SB = Introduction
`Great things can be done by great sacrifices only' avers Vivek<193>nanda ç
(<MS>A.<|>D.<D> 1863-1902). No wonder then, that, in order to attain ç
mok<218>a or liberation from transmi-gratory existence†which is an ç
extremely arduous task†great effort is needed. This presupposes freedom ç
from the bondages, duties and responsibilities of worldly life or ç
family life. Hence ty<193>ga or renunciation and tapas or austerities†in ç
short, asceticism†are often stressed in the Hindu scriptures.
Mok<218>a has been declared as the birth- right of every human being ç
and not the prerogative of only a handful of persons. The  very  purpose  of  the  puru<218><193>rtha ç
concept and the <193>·rama scheme of life is to afford an opportunity ç
for everyone to try for mok<218>a (See <MS>°<185>RAMA<D> and <MS>PURU<186>°RTHAS.<D>).
@SB = In the Vedas and the Upani<218>ads
Asceticism was not unknown to the Vedas. In the <184>gveda (10.136.2) ç
there is a reference to the munis. They put on dirty garments and ç
had great psychic powers. The Ch<193>ndogya Upani<218>ad (2.23.1) ç
refers to the brahmac<193>ri who remains celibate throughout his life ç
and lives in his guru's house,studying the scriptures. The B<216>had<193>ra<207>yaka ç
Upani<218>ad (3.5.1) clearly refers to the <216><218>is who had known ç
the <193>tman, to have renounced the world and taken to a mendicant's ç
life. Some minor Upani<218>ads like the Mah<193>n<193>r<193>ya<207>a ç
(10.5) and the Kaivalya (1.3) state how some aspirants attained ç
immortality by renouncing the world and worldly life. Other Upani<218>ads ç
(from among them) like the N<193>radaparivr<193>jaka, the Paramaha<221>sa ç
and the Bhik<218>uka deal directly with the monastic life.
@SB = The Two Paths
Though mok<218>a was posited before the human beings as the final ç
goal of life, the Hindu sages knew that all were not equally competent ç
to pursue it vigorously and consciously. Hence they offered two paths ç
to reach the goal†the prav<216>ttim<193>rga (path of activism) and ç
the niv<216>ttim<193>rga (path of detachment)†both of which, if properly ç
understood and assiduously practised, will lead to the same goal.
In the former way of life, a person was free to marry, raise a family ç
and fulfill all the legitimate desires of the body and the mind, as ç
per the dictates of the ·<193>stras (the holy scriptures) and the ç
codes of dharma (righteous living). In this stage of life, called ç
`g<193>rhasthya', great stress was also laid upon the social responsibilities ç
to be discharged by the couple and the family as a whole.
As the person passes through the various experiences of life, both ç
good and bad, vair<193>gya (disinterestedness through the maturing ç
of wisdom) will rise in his mind, making him gradually withdraw from ç
the family life and turn his attention more and more towards the higher, ç
the spiritual, values of life. This in essence, is niv<216>ttim<193>rga, ç
even though the person may not formally take to the v<193>naprastha ç
or the sa<221>ny<193>sa <193>·rama.
In the niv<216>ttim<193>rga, a person may take to sa<221>ny<193>sa ç
or the last stage of life even from the first (or the second) without ç
going through the other stages or <193>·ramas, an intense feeling ç
of vair<193>gya (the spirit of renunciation) being the only criterion.
@SB = Asceticism and Monasticism
Asceticism (or tapas) in life was a common phenomenon even in the ç
Vedic days. Anyone interested in spiritual welfare or even in achieving ç
something which could not be got by ordinary human means, was advised ç
to undergo tapas or austerities, the intensity of which depended upon ç
the greatness of the goal desired to be achieved. For instance, the ç
sage Bh<216>gu, Varu<207>a's son, was advised to perform tapas to ç
know Brahman (vide Taittir<200>ya Upani<218>ad 3.1). Hira<207>yaka·ipu, ç
the king of the r<193>k<218>asas or demons, undertook tapas to achieve ç
greaterpowers to conquer the devas or the gods in heaven (vide Vi<218><207>upur<193><207>a ç
1.17.2; Bh<193>gavata 7.3). So also R<193>va<207>a, the kingof ç
La<209>k<193> (R<193>m<193>ya<207>a, Uttarak<193><207>da 9 and ç
10).
Though <|>asceticism <|>does<|> not <|>necessarily include monasticism, ç
it is an integral part of the latter. A sa<221>ny<193>sin or a monk ç
is permitted to accept only the bare necessities of life like a kaup<200>na ç
(loin-cloth), kanth<193> (wrapper), da<207><195>a (stick), kama<207><195>alu ç
(water-pot), p<193>duk<193> (wooden footwear) and ·ikya (cloth hung ç
over the shoulder, for collecting alms). These are necessary for the ç
sustenance of the body so that he can practise spiritual disciplines ç
in a better frame of mind.
@SB = Organised Monasticism
Though sa<221>ny<193>sa (monastic life) was prescribed as the last ç
stage of life and though individual monks did exist in the Hindu society ç
over the millennia, organised monasticism owes its origin to <185>a<209>kara ç
(<MS>A.D.<D> 788-820). Of course, it already existed in Buddhism ç
and Jainism.
@SPACE1 = 
<185>a<209>kara established four chief mona-steries in the four cardinal ç
directions of India†Jyotir Ma<219>ha near Badar<200> in the north, ç
K<193>lik<193> Ma<219>ha at Dv<193>rak<193> in the west, Govardhana ç
Ma<219>ha at Pur<200> in the east and <185><216><209>ger<200> <185><193>rad<193>p<200><219>ha ç
at <185><216><209>ger<200> in the south. He also appointed four of ç
his disciples as the first pontiffs of these four monasteries.
Later, other monastic and ascetic orders also came into existence.
@SB = List of Monastic and Ascetic Orders
Over the centuries several ascetic orders have come into existence, ç
some of which are monastic and the others, not. They may be dealt ç
with very briefly as follows:
The Aghorapanth<200>s are the ascetics of a queer <185>aiva order ç
who worship <185>iva as `Aghora' (the `non-terrible') but practise ç
abominable things like cannibalism and eating from a human skull and ç
so on. See <MS>AGHORAPANTH®<D> for details.
The Alakhn<193>m<200>s are a sect of ·<220>dra ascetics living mostly ç
in Rajasthan. They are gentle by nature and practise non- violence.
(See <MS>ALAKHN°M®S<D> for details.)
The Da·an<193>m<200>s are sa<221>ny<193>sins of the advaita school, ç
established by <185>a<209>kara. They are ten in number (as the very ç
name suggests), attached to the four principal ma<219>has. (See <MS>DA<185>AN°M®S<D> ç
for details.)
The K<193>l<193>mukh<193>s are a sect of ascetics belonging to the ç
<185>aiva order. They are so called since they deface their faces ç
with black marks and symbols. They belong to the Nakul<200>·a-P<193>·upata ç
cult.
The K<193>p<193>likas are also ascetics of <185>aiva cult using the ç
kap<193>la or the human skull as a begging bowl. Hence the name. (See ç
<MS><185>AIVISM.<D>)
The N<193>g<193>-s<193>dhus are a militant sect of sa<221>ny<193>sins ç
of the da·an<193>m<200> group organised by Madhus<220>dana Sarasvat<200> ç
(<MS>A.D.<D> 1525-1632). Their monasteries are called `akh<193><195>as'.
The N<193>thpanthis, also called Jog<200>s, are the followers of Matsyendran<193>tha ç
and Gorak<218>an<193>tha (Gorakhn<193>th). They concentrate on Ha<219>hayoga ç
and are vehemently opposed to association with women in any form.
The Nirmalas are a sect of reformist ascetics more akin to Sikhism. ç
They accept the worship of the five Hindu gods†<185>iva, Vi<218><207>u, ç
Dev<200>, Ga<207>apati and S<220>rya†revere the Granth S<193>hib ç
and consider that R<193>m and Rah<200>m are the names of the same ç
Supreme God.
The  R<193>m<193>nandis  are  sa<221>ny<193>sins belonging to the ç
order established by R<193>m<193>nanda (birth <MS>A.<|>D.<D> 1300). ç
They call their Vai<218><207>ava tradition as `<185>r<200>sampra-d<193>ya'. ç
Their tutelary deity is S<200>t<193>. Their centres are known as `dv<193>ras'.
The Ud<193>sis are a sect of monistic sa<221>ny<193>sins started by ç
<185>r<200>cand (<MS>A.<|>D.<D> 1494-1629), the elder son of Guru N<193>nak ç
(<MS>A.<|>D.<D> 1469-1539). They accept the authority of the Vedas ç
and worship the five deities (pa<210>c<193>yatana p<220>j<193>). In ç
addition, they revere Guru N<193>nak and the Grantha S<193>hib. ç
That is why they are also known as N<193>nak·<193>his or N<193>nakpanth<200>s.
The Vair<193>gis (or Bair<193>gis) are a sect of Vai<218><207>ava ç
ascetics who wear white robes and the <220>rdhvapu<207><195>ra (vertical ç
religious mark) on their foreheads. They may grow beard and keep their ç
hair matted. Four traditions or orders are recognised among them.
@SB = Modern Orders of Monasticism
Among the modern editions of ancient and traditional monasticism, ç
the most important one is the Ramakrishna Order. Modern but simple ç
way of living, community life, preaching work combined with social ç
service activities distinguish it from the traditional monasticism. ç
A parallel order for women†of sa<221>ny<193>sin<200>s†has also been ç
started since 1956.
@SB = Conclusion
Monasticism as a way of life is still very much in vogue in the Hindu ç
society. The fact that many highly educated young men and women are ç
opting for this life shows that it is still vibrant and a force to ç
reckon with.
@NT = monks
@NID = <+><+><+><+>See <MS>MONASTICISM<D>, <MS>SA<189>NY°SA<D> and <MS>YATI.<D>
@NT = moon
See <MS>CANDRA.<D>
@NT = morality
Hinduism considers morality or practising moral values as the primary ç
and the most essential part of religion. Without morality there can ç
be no true religion or spirituality.
See <MS>DHARMA<D>, <MS>NIYAMA<D> and <MS>YAMA.<D>
@NT = mother
See <MS>M°T°.<D>
@NT = M<216>tyu
@N1 = (`that which brings about death')
According to the Hindu scriptures, the concept of death has to be ç
looked at, from two different standpoints. The first is as a deity ç
or a goddess who brings about the separation of the j<200>va (individual ç
soul in bondage) from its body. The second is as Yama, the king of ç
the world, to where the souls are taken, before disposing off their ç
cases according to their good or bad deeds.
M<216>tyu as the goddess of death is said to have manifested out of ç
the anger of Brahm<193> (the creator) who had been moved by the piteous ç
wailings of Bh<220>dev<200> (Mother Earth) since she was overburdened ç
by the ever increasing number of living beings, who never died! When ç
she was assigned her duty of killing the living beings, she was horrified ç
and started crying, shedding copious tears. However, Brahm<193> assured ç
her that she would never incur any sin by this. But, at her special ç
request, Brahm<193> also created the six enemies (ari<218>a<195>varga) ç
like lust, anger and greed, to be embedded in the hearts of the living ç
beings making them vulnerable to death (vide Mah<193>bh<193>rata, ç
Dro<207>aparva chs. 53 and 54).
See also <MS>YAMA.<D>
@NT = Mucukunda
Many of the great kings of the epic and the paur<193><207>ic period ç
were also deeply religious and intensely devoted to God. Mucukunda, ç
one of the three sons of theking M<193>ndh<193>t<193>†the other two ç
being Purukutsa and Ambar<200><218>a†was a r<193>jar<218>i (sage-king) ç
of this type.
After  fighting  with  the  r<193>k<218>asas (demons) on behalf of ç
the devas (gods) at their request, and helping them to win, he got ç
the boon of a long and deep sleep as rest. He was also assured that ç
anyone disturbing his sleep would be reduced to ashes by his very ç
look.
When   the   demon   K<193>layavana attacked Mathur<193>, <185>r<200> ç
K<216><218><207>a maneuvered to lead him into the dark cave where ç
Mucukunda was sleeping. K<193>layavana kicked Mucukunda thinking that ç
he was K<216><218><207>a. When Mucukunda opened his eyes in anger ç
and looked at him, he was immediately reduced to ashes! As K<216><218><207>a ç
appeared on the scene and revealed his divine form, Mucukunda praised ç
him with a beautiful hymn (vide Bh<193>gavata 10.51).
There is a hillock near Dholpur in Rajasthan. A cave in this hillock ç
is said to be the place where Mucukunda slept.
@NT = Muddusv<193>mi D<200>k<218>itar
@N1 = (<MS>A.<|>D.<D> 1775-1835)
The science of Hindu music, though originally one, gradually got crystallised ç
into two broad traditions: The uttar<193>di (North Indian) and the ç
dak<218>i<207><193>di (South Indian, also called Karnatic).
If the saint Purandara D<193>sa (<MS>A.<|>D.<D> 1484-1564) laid the ç
foundation for the present form of South Indian music, the three jewels ç
(`ratnatraya') of the same system have enriched it abundantly. They ç
are: Ty<193>gar<193>ja (<MS>A.<|>D.<D> 1767-1847), Muddu-sv<193>mi ç
D<200>k<218>itar (<MS>A.<|><|>D.<D> 1775-1835) and <185>y<193>m<193>·<193>stri ç
(<MS>A.<|>D.<D> 1763-1827).
Muddusv<193>mi D<200>k<218>itar†also known as Muttusv<193>mi D<200>k<218>itar ç
or just `D<200>k<218>itar'† was the son of R<193>masv<193>mi D<200>k<218>itar ç
and Subbalak<218>mi Amm<193><202>, born as a result of the grace of ç
the Divine Mother B<193>l<193>mbik<193> (P<193>rvat<200>) (of Vaid<200>·varan ç
Koil, a famous temple in Tamil Nadu). This is obviously reflected ç
in many of the compositions of D<200>k<218>itar on the Mother Divine.
Muddusv<193>mi†known in his earlier days as Kum<193>rasv<193>mi†was ç
the eldest son and had three younger brothers. He was well-educated ç
by his father himself in several branches of knowledge like the Vedas, ç
Sanskrit language and literary works,  health  sciences,  mantra·<193>stra ç
(esoteric science of sacred formulae) and music. Cidambaran<193>tha, ç
a great yogi, who was the guru of R<193>masv<193>mi D<200>k<218>itar, ç
took him and Muddusv<193>mi to K<193>·<200> where they spent six years. ç
During this sojourn in the north, the boy not only visited many places ç
of pilgrimage but also picked up a fairly good knowledge of the North ç
Indian music. Its influence can be noticed in some of his compositions ç
like `ra<209>gapuravihara,' `jamb<220>pate m<193><221> p<193>hi,' ç
and `akhil<193><207>-<195>e·vari.'
Muddusv<193>mi D<200>k<218>itar then returned to his native place ç
Ma<207>ali.
Once he went to Tirutta<207>i, a nearby sacred place and practised ç
special spiritual disciplines, meditating on the deity Subrahma<207>ya. ç
A strange mystical experience here induced in him a remarkable power ç
to compose songs. This is the reason why his songs always contain ç
the words `Guruguha' (= Subrahma<207>ya) towards the end.
Later in life he toured South India extensively and composed songs ç
on the various deities of the Hindu pantheon (the presiding deities ç
of the places visited).
He had met both Ty<193>gar<193>ja and <185>y<193>m<193>·<193>stri ç
in his tours.
D<200>k<218>itar was not only a composer and singer but also an accomplished ç
player of v<200><207><193> (lute).
All his compositions are in Sanskrit and excel not only in diction ç
but also in rousing our devotion. His `nav<193>vara<207>a-k<216>tis' ç
are special compositions on the esoteric worship of the Divine Mother.
He intuitively perceived that his death was very near and passed away ç
when his disciples were singing†at his behest†his famous song `m<200>n<193>k<218>i ç
me muda<221> dehi'.
He left behind him a galaxy of disciples to continue his tradition.
@NT = Mudgala
Mudgala was a great sage performing austerities at Kuruk<218>etra. ç
He was the father of Divod<193>sa (a king) and Ahaly<193> (the wife ç
of the sage Gautama). He was well-known for his hospitality to guests. ç
He once rejected the offer of the gods to go to heaven since he was ç
interested in mok<218>a or liberation.
He is said to have performed a great sacrifice near the bridge built ç
by <185>r<200> R<193>ma. Pleased with it Lord Vi<218><207>u created ç
a big pond of milk (of K<193>madhenu, the celestial cow) to be used ç
in his sacrifice. This pond called K<218><200>rat<200>rtha which is ç
near R<193>me·-varam is visited by the pilgrims even now.
Mudgala is the sage of the <184>gvedic s<220>kta 10.102. It is mentioned ç
there that his cows were once stolen. He yoked an old ox to his cart, ç
followed the thieves and got back his cows after routing them with ç
his drugha<207>a (wooden mace). His wife, Mudgal<193>n<200> drove ç
his cart or chariot, thus helping him in this venture.
@NT = Mudgalapur<193><207>a
The pur<193><207>as contain a lot of ancient historical traditions ç
and material though couched in the style and language of mythology.
Generally, they are divided into two groups: Mah<193>pur<193><207>as ç
(the major pur<193><207>as) and Upapur<193><207>as (the minor pur<193><207>as). ç
The Mudgalapur<193><207>a is one classed among the latter group ç
of works.
Written probably during the period <MS>A.D.<D> 900-1100, it is devoted ç
mainly to the description of nine incarnations of Ga<207>apati. They ç
are: Vakratu<207><195>a, Ekadanta, Mahodara, Gaj<193>nana, Lambodara, ç
Vika<219>a, Vighnar<193>ja, Dh<220>mravar<207>a and Yoga.
It speaks of 23 more forms of Ga<207>apati. It has imbibed the influence ç
of the tantras very much.
See also <MS>PUR°ØAS.<D>
@NT = Mudgala Upani<218>ad
This is one of the minor Upani<218>ads assigned to the <184>gveda. ç
It is like a brief commentary on the Puru<218>as<220>kta (vide ç
<184>gveda 10.7.90.1-16). There are four kha<207><195>as or sections ç
with 30 mantras in all. Only the first section is in verses in the ç
anu<218><219>ubh metre. The rest are in prose.
The first section gives a brief explanation of the various verses ç
of the Puru<218>a-s<220>kta. For instance, the word `sahasra ·<200>r<218><193>' ç
(verse 1) indicates that the Puru<218>a (God)  is  infinite.  The  second  verse ç
describes him as the giver of mok<218>a or liberation. The verses ç
16 and 17 describe the greatness of Hari (= Puru<218>a).
The  second  section  says  that Bhagav<193>n V<193>sudeva gave this ç
teaching of the Puru<218>as<220>kta to Indra, the king of gods.N<193>r<193>ya<207>a, ç
the Paramapuru<218>a (the Supreme Person), though beyond names and  forms  and  ordinary  knowledge, ç
assumed this form of the thousand-headed Puru<218>a for the benefit ç
of ordinary mortals, so that they could attain liberation just by ç
looking at him. It was this Puru<218>a† called `Mah<193>puru<218>a' ç
here†that divided himself into four forms, out of which only one is ç
here manifested as this world, the rest being beyond creation and ç
comprehension.
It is him†who has manifested himself in various forms†that the adhvaryu ç
priests worship as the threefold Agni (fire-god). It is again him ç
that others identify with the three Vedas. Others again†like human ç
beings, demons and manes†identify him with rayi (food), delusive power ç
or with the mantra `svadh<193>' used in sacrifices. This is the gist ç
of the third section.
The  last  section  describes  that Brahman (= Puru<218>a) is without ç
the six ko·as or sheaths like skin and blood, beyond the six <220>rmis ç
or infirmities like hunger and thirst as also the six bh<193>vas or ç
changes like birth and death. But the Supreme Puru<218>a somehow, ç
voluntarily, accepts these and becomes the j<200>va (individual soul ç
in bondage).
One  who  studies  this  Upani<218>ad becomes pure in every way. He ç
is liberated from all sins of all types. However, being an esoteric ç
knowledge of the highest, it should never be imparted to unworthy ç
persons who have not studied the Vedasor who have not performed sacrifices ç
orwho are harsh of speech and ever discontented.
@SPACE1 = 
The guru who gives this knowledge to worthy disciples must follow ç
some sacred rules like choosing a clean place, an auspicious time ç
and meditation on the Puru<218>a. He should impart it secretly in ç
the ear of the disciple.
Then, both the teacher and the disciple become identified with the ç
Puru<218>a himself.
See also <MS>UPANI<186>ADS.
@NT = mudr<193>
@N1 = (`that which gives pleasure [to the deity]')
The word `mudr<193>' has been used in several senses. Etymologically, ç
it means `that which gives pleasure to the deityand makes its heart ç
melt out of compassion'.
In the <193>gamas and tantras, it is used to indicate: a pose of hand; ç
a posture of the body; as one of the five mak<193>ras (various  kinds  of  grains);  a  woman ç
companion of the t<193>ntrik s<193>dhaka.
@SPACE = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
In dance also several mudr<193>s indicating several bh<193>vas or ç
sentiments are used.
In iconographical works, the images are depicted as exhibiting several ç
mudr<193>s (poses of hand) like abhayamudr<193> (pose of protection) ç
or varadamudr<193> (pose of granting boons) or cinmudr<193> (pose ç
of imparting knowledge).
In p<220>ja or worship, some of the mudr<193>s (poses) used are <193>v<193>han<200> ç
(inviting the deity) or sammukh<200>kara<207><200> (requesting the ç
deity to turn towards the worshipper), k<220>rma (in meditation on ç
the deity) and avagu<207><219>hana (covering the food ceremonially ç
while offering it).
