The mudr<193>s (also called bandhas) in Ha<219>hayoga vary from 8 ç
to 108. They indicate several processes of controlling the body and ç
the pr<193><207>ic energy which give health, strength and energy as ç
also freedom from diseases. Some of these mudr<193>s are: mah<193>mudr<193>, ç
nabhomudr<193>, m<193>t<193><209>gin<200> and so on.
In the political sciences as depicted in the Artha·<193>stra of ç
Kau<219>ilya (321-300 <MS>B.C.<D>), a mudr<193> represents a seal ç
of the government. Different kinds of seals were used for different ç
purposes like seals on merchandise for having paid the tax orabout ç
their quality or while issuing instructions in the name of the king.
Sometimes, those who committed abominable crimes were branded with ç
certain signs called `mudr<193>s' and banished from the kingdom. For ç
instance, a thief was branded with the sign of a dog on his forehead.
See also <MS>BANDHA<D>, <MS>P<188>J°<D> and <MS>TANTRAS.
@NT = muh<220>rta
@N1 = (`a short unit of time')
Measurement of time in certain units has been known to the Hindus ç
since a long time. The word `muh<220>rta,' meaning `a short time', ç
is one such unit known even to the Vedas (vide <184>gveda 3.35.5; ç
3.53.8 and <185>atapatha Br<193>hma<207>a 1.8.3.17).
However, in course of time, it became fixed as 1/30th part of a day ç
of 24 hours and hence, of a duration of 48 minutes.
The 15 muh<220>rtas of a day (as different from those of the night) ç
are sometimes given specific names such as br<193>hma-muh<220>rta<W1%22>,<D%0>abhijit-muh<220>rta<W1%18>,<D%0>vair<193>ja- ç
muh<220>rta and so on.
A proper muh<220>rta is one of the four elements†the other three being ç
tithi, nak<218>atra and kara<207>a†needed to be looked into for the ç
success of an undertaking.
Muh<220>rtas considered auspicious for various acts, have been mentioned ç
in the works on Hindu astrology. For instance: for purchasing merchandise, ç
for the performance of auspicious acts, for wearing new garments for ç
the first time, for upanayana and marriage and so on.
It is interesting to note that a workcalled Muh<220>rtamukt<193>val<200> ç
prescribes `auspicious' time even for stealing!
However, certain sages have also declared that if there is purity ç
of mind†as indicated by faith in God, honouring theholy ones and ç
contentment†all the planets will become favourable and hence there ç
is no need to look for auspicious times (Matsyapur<193><207>a 243.25-27; ç
Vi<218><207>u-dharmottarapur<193><207>a 2.163.32).
See also <MS>K°LA.
@NT = M<220>k<193>mbik<193> Temple
See <MS>KOLL<188>RU<D>.
@NT = mukhali<209>ga
@N1 = (`li<209>ga with face')
<185>iva is worshipped in the form of a li<209>ga. (See <MS><185>IVALI<177>GA<D> ç
for details.)
A li<209>ga may be aniconic (without anyimage form) or partially ç
iconic. The mukhali<209>ga belongs to this latter group.
In a mukhali<209>ga, the <185>iva-part is one unit more than the Brahm<193>-part ç
and the Vi<218><207>u-part.
If the <185>iva-part is divided into three equal portions, the mukha ç
or face of <185>iva should occupy one and a half portion.
There may be one, two, three or four faces on the round shaft of the ç
li<209>ga. Whereas li<209>gas with one face and four faces can be ç
installed in villages and towns (i.e., human settlements), the two-faced ç
ones are generally used in black-magical rites and are established ç
in forests or on mountains.
The one-faced li<209>ga must have the face turned towards the entrance ç
of the sanctum.
If it is three faced, the main face should be turned towards the door ç
of the sanctum.
@NT = mukhama<207><195>apa
See <MS>TEMPLES, HINDU.<D>
@NT = Mukt<193>b<193><200>
Sant J<210><193>ne·var (<MS>A.<|>D.<D> 1275-1296) was the earliest ç
of the saints of Maharashtra who initiated the Bhakti Movement. His ç
elder brother Niv<216>ttin<193>tha (a disciple of Gayan<200>n<193>tha, ç
a follower of the N<193>tha Cult) was his guru. Sop<193>na was his ç
younger brother and Mukt<193>b<193><200>, his sister, the youngest ç
in the family.
Mukt<193>, as she was fondly known, was considered as an incarnation ç
of Mah<193>m<193>y<193> (the power of Lord Vi<218><207>u). She too ç
was a highly evolved saint and was the spiritual teacher of Visob<193> ç
Khecar and C<193><209>gadev (a great ha<219>hayogi, well-known for ç
his psychic powers).
There are a few abha<209>gas (bhajans in Mar<193><219>hi) in her name.
See also <MS>J<178>°NE<185>VARA.
@NT = muktapuru<218>a
@N1 = (`the liberated person')
The basic works of Hinduism like the Upani<218>ads and the Bhagavadg<200>t<193>, ç
as also several secondary treatises based on them like the epics and ç
the pur<193><207>as, have described in detail, the characteristics ç
of a muktapuru<218>a, the liberated person, also called `j<200>vanmukta' ç
(`liberated even while living in the body').
The <193>tman or the soul (the Self) is essentially free. But, that ç
he has got himself entangled in the body-mind complex, that he is ç
therefore suffering much and that he is undergoing transmigration ç
repeatedly, isalso a recognised fact. Though the cause of his bondage ç
and themeans of his deliverance as described in the various philosophical ç
systems of Hinduism may appear to differ, descriptions of his state ç
of liberation are, more or less similar. The Ka<219>hopani<218>ad ç
(5.1) says that a muktapuru<218>a is fully free from all kinds of ç
desires. So does the B<216>had<193>ra<207>yaka Upani<218>ad (4.4.7). ç
Some ofthe other Upani<218>ads declare that a liberated soul is absolutely ç
untouched by any kind of sin, heinous or venial (vide Kau<218><200>taki ç
Br<193>hma<207>opani<218>ad 3.1).
Excellent and detailed descriptions of a muktapuru<218>a, called variously ç
`j<200>vanmukta,' `sthitapraj<210>a,' `bhakta,' `gu<207><193>t<200>ta,' ç
`br<193>hma<207>a' and `ativar<207><193>·rami' are found in a number ç
of authoritative religious workslike Laghuyogav<193>si<218><219>ha ç
(5th sarga), Bhagavadg<200>t<193> (2.54-64<%22>;<%0>12.13-19; 14.21-26), ç
Mah<193>bh<193>rata (<185><193>ntiparva 245.12-24) and S<220>tasa<221>hit<193> ç
(Muktikha<207><195>a 5.9-42).
The gist of all these descriptions is that his mind has transcended ç
all pairs of opposites like happiness and misery, likes and dislikes ç
as also the various passions and prejudices like lust and greed, avarice ç
and delusion, pride, vanity and jealousy. He is ever immersed in the ç
bliss of the <193>tman inside and looks upon the world as a reflection ç
or a manifestation of Brahman, the Absolute.
@SPACE1 = 
See also <MS>BANDHA<D> and <MS>MOK<186>A<D>.
@NT = mukti
See <MS>MOK<186>A.
@NT = Muktikopani<218>ad
@EMERGENCY = This is a well-known minor Upani<218>ad assigned to the ç
<185>ukla Yajurveda. It is often referred to by others since it ç
gives a long list of 108 Upani<218>ads. It is in twoadhy<193>yas ç
or chapters containing 134 mantras mostly in the anu<218><219>ubh ç
metre, the rest being in prose.
@EMERGENCY = It is cast in the form of a dialogue between Hanum<193>n ç
and <185>r<200> R<193>ma the emperor, (considered as an incarnation ç
of Lord Vi<218><207>u Himself) at Ayodhy<193>, the capital from where ç
he ruled.
@EMERGENCY = Hanum<193>n asks <185>r<200> R<193>ma as to his greatness ç
and the way of attaining liberation without much effort. <185>r<200> ç
R<193>ma replies that by the true knowledge of Ved<193>nta, one can ç
get the mukti or liberation known as s<193>yujya, absorption into ç
him. Incidentally he gives the several divisions of the Vedas (which ç
are produced by his breath as it were) and the Upani<218>ads.
@EMERGENCY = In answer to another question by Hanum<193>n about the ç
various descriptions of mukti given by others, <185>r<200> R<193>ma ç
delineates four kinds of mukti†s<193>lokya (attaining his world), ç
s<193>m<200>pya (living near him), s<193>r<220>pya (having a form ç
similar to his) and s<193>yujya (unity in him)†and praises the greatness ç
of the t<193>rakamantra (`R<193>ma') uttered by <185>iva, the Lord ç
of K<193>·<200>, in the ears of persons dying there.
@EMERGENCY = However, he also stresses that only a knowledge of the ç
Upani<218>ads can give liberation. Then he proceeds to give the names ç
of 108 Upani<218>ads. (All these are now available in print, with ç
the commentary of Upani<218>adbrahma Yog<200>ndra.)
Then comes the method of giving the knowledge of these Upani<218>ads ç
to worthy seekers. Atheists, ungrateful ones, persons of evil character, ç
those who lack devotion to God, those who have no love for the guru†all ç
these are unfit to receive this knowledge. On the other hand, the ç
disciples devoted to the service of the guru, those who are of good ç
character and devoted to God should be given this knowledge after ç
testing them.
Next, there is a long section giving the <185><193>ntimantras (peace-invocations) ç
for the various Upani<218>ads. They are decided as per the Veda to ç
which the Upani<218>ad belongs: v<193><209> me manasi for the Upani<218>ads ç
of the <184>gveda (like Aitareya and Kau<218><200>taki); p<220>r<207>amada<199> ç
for the Upani<218>ads of the <185>ukla Yajurveda (like ®·<193>v<193>sya ç
and B<216>had<193>ra<207>yaka); saha n<193> vavatu for the Upani<218>ads ç
of the K<216><218><207>a Yajurveda (like Ka<219>ha and Taittir<200>ya); ç
<193>py<193>yantu for the Upani<218>ads of the S<193>maveda (like ç
Kena and Ch<193>ndogya); bhadra<221> kar<207>ebhi<199> for the ç
Upani<218>ads of the Atharva<207>aveda (like Pra·na and Mu<207><195>aka).
Here ends the first chapter.
The Second chapter deals mainly with j<200>vanmukti (liberation while ç
living in the body) and videhamukti (liberation from future transmigration ç
after death).
@SPACE1 = 
It is the v<193>san<193>s (tendencies and impressions in the mind ç
carried over from previous lives) that are responsible for bondage. ç
Hence, in order to get liberation, the seeker has to practise simultaneously ç
vij<210><193>na (knowledge about the <193>tman or the true Self), ç
v<193>san<193>k<218>aya (attenuation and destruction of the v<193>san<193>s) ç
and manon<193>·a (destruction of the tendencies in the mind that arise ç
involuntarily).
The Upani<218>ad then proceeds to des-cribe in detail how they can ç
be achieved. Desisting from the will to fulfil desires, practising ç
pr<193><207><193>y<193>ma and meditating on pure consciousness as ç
the essence behind one's Self and the world†these are the means of ç
attaining j<200>vanmukti.
See also <MS>J®VANMUKTI-VIVEKA.
@SPACE = 
@SPACE1 = 
@NT = muktiyogyas
@N1 = (`those who are fit for liberation')
 See <MS>NITYASA<189>S°RI.
@SPACE = 
@SPACE1 = 
@NT = muku<219>a
@N1-1 = (`that which decorates [the head]')
Muku<219>a (also spelt as `maku<219>a') is headwear or crown. In iconographical ç
works, almost all the images†whether of gods or semi-gods or demons ç
or human beings†are shown with some kind of muku<219>a.
There are varieties of the same. Some of them are:
1. kir<200><219>amuku<219>a†It is a crown, usually 16 to 24 a<209>gulas ç
in height and cylindrical or conical in shape with details like a ç
diadem or a lotus or studded with gems. It is shown on the heads of ç
male deities like Vi<218><207>u as also emperors. Sometimes dev<200> ç
images too have them.
2. kara<207><195>amuku<219>a†shaped like a pot or a bulb, it is ç
shown as adorning the major feminine deities and also kings. The lower ç
part of this crown may be studded with precious stones.
3. ja<219><193>muku<219>a†Here, the matted hair is done up like ç
a crown. This is generally shown in the images of <185>iva, his attendants ç
as also the sages and in some forms of the Dev<200>.
In the images of yak<218>as and the n<193>gas,  a  turban-like  headgear,  called ç
·irastraka, is provided.
@NT = M<220>la
Hindu astronomy lists 28 nak<218>atras or groups of stars. The M<220>la ç
is the 19th in the list. It comprises two stars†the lambda and the ç
upsilon Scorpio. It is generally considered as inauspicious.
The Atharvaveda calls it as `Vic<216>tan'.
See also <MS>NAK<186>ATRAS.<D>
@NT = m<220>l<193>dh<193>ra
See <MS>CAKRAS.<D>
@NT = M<220>lar
Also known as Tirum<220>lar N<193>yan<193>r (tiru = <185>r<200>; n<193>yan<193>r ç
= a <185>aiva saint in general), M<220>lar is one of the 64 <185>aiva ç
saints of Tamil Nadu, who probably lived in the 6th century <MS>A.<|>D.<D>
He was one of the eight disciples of a great teacher Tirumandi Devar.
It seems he was living on a hillock called Potiy<193>n. Once he strongly ç
felt to see the sage Agastya and came to the southern country, visiting ç
many a <185>iva temple on the way. In one village, on the bank of ç
K<193>veri he found a herd of cows shedding tears. He came to know ç
that the cowherd named M<220>lan had just died. Out of pity for the ç
cows, he, using his special yogic power known as `parak<193>yaprave·a' ç
(entering into the dead-body of another person), entered into M<220>lan's ç
body, but kept his own body safely hidden in the cavity of a huge ç
tree.
The villagers found this `M<220>lan' diffe-rent from the old M<220>lan, ç
discovered that he had become a saint (Tirum<220>lar) and let him ç
go freely as he liked.
This Tirum<220>lar later found that his original body had disappeared! ç
Hence he was forced to live in his new body.
He often used to go into sam<193>dhi and compose his work Tirumandiram ç
(of 3000 verses) whenever he came down to normal consciousness.
See also <MS>N°YANM°RS.<D>
@NT = m<220>la·odhana
Cleansing the body is an important aspect of Ha<219>hayoga. Such processes ç
are known by the term `<218>a<219>karma', one of which is dhauti. ç
Of the four kinds of dhauti, m<220>la·odhana is also one. It is the ç
purification of the rectum and the large intestines using a stalk ç
of the root of turmeric or the middle finger of the hand. It should ç
be done only under the guidance of an expert.
See also <MS>DHAUTI<D> and <MS><185>A<187>KARMAS.<D>
@NT = M<220>laveda
The P<193><210>car<193>tra °gamas, the basic texts of Vai<218><207>avism ç
or the Bh<193>gavata Cult were called `M<220>laveda' by their followers ç
since they were taught by God N<193>r<193>ya<207>a Himself to the ç
sages Nara, <185><193><207><195>ilya, Prahl<193>da and others.
See also <MS>P°<178>CAR°TRA °GAMAS.
@NT = m<220>l<193>vidy<193>
@N1 = (`universal or primeval<R>ç
ignorance or nescience')
Some of the schools of Advaita Ved<193>nta categorise avidy<193> or ç
nescience into two types: m<220>la-avidy<193> (universal or primeval ç
nescience) and tula-avidy<193> (individual nescience).
The former is the material cause of this world.
The latter is the avidy<193> that covers consciousness circumscribed ç
by particular objects, like the body.
Whether m<220>l<193>vidy<193> is located in Brahman or in the j<200>va ç
has been a moot point. The Vivara<207>a school of Pa<210>cap<193>dik<193> ç
holds the former view whereas the Bh<193>mat<200> school sticks ç
to the latter.
See also <MS>ADVAITA VED°NTA DAR<185>ANA.
@SPACE = 
@NT = mumuk<218>utva
@N1 = (`desire for mok<218>a or<R>ç
liberation')
According to the <218>a<195>dar·anas or the six systems of Indian ç
philosophy the real bondage for a soul is its being encased in a body, ç
whether human or non-human. Hence mok<218>a or mukti is permanent ç
liberation from rebirth, and, regaining the original state. The desire ç
for such mok<218>a is `mumuk<218>utva' or `mumuk<218><193>' and one ç
who  possesses  such  a  desire  is  a `mumuk<218>u'.
See also <MS>S°DHANACATU<186><187>AYA.
@SPACE = 
@NT = Mu<207><195>a
@SPACE = 
Ca<207><195>a and Mu<207><195>a were two fierce demons who worked ç
under the demon king <185>umbha as chiefs of a section of his army. ç
Both of them were killed by K<193>l<200> (an emanation of Goddess ç
Durg<193>) in their encounter with Durg<193>. K<193>l<200> got the ç
name C<193>mu<207><195><193> because of this act of hers.
Mu<207><195>a also means the decapitated head. <185>iva and K<193>l<200> ç
are described as wearing a garland of the mu<207><195>as. Hence the ç
names Mu<207><195>am<193>lin and Mu<207><195>am<193>lin<200> for them.
See also <MS>C°MUØ£°<D> and <MS>DURG°- SAPTA<185>AT®.<D>
@NT = Mu<207><195>aka Upani<218>ad
The Mu<207><195>aka Upani<218>ad of the Atharva Veda (hence its ç
other name, the °tharva<207>opani<218>ad) has been a popular work ç
due to its attractive poetry, elegant expressions and sublime thoughts.
Since the word `mu<207><195>a' means `a shaven head', the Upani<218>ad ç
was perhaps, meant to be specially studied by men of shaven heads, ç
viz., the sa<221>ny<193>sins or monks. Or, like the shaving of one's ç
head, it was meant to `shave off' all ignorance regarding the tattvas ç
or higher truths taught in this work.
There are three mu<207><195>akas or chapters with two kha<207><195>as ç
or sections in each. The total number of verses is 65.
Division of all knowledge into two categories (the higher and the ç
lower), eulogy of renunciation, a specific mode of meditation using ç
Om and the method of liberation of a realised soul at the time of ç
death are the special features of this Upani<218>ad.
@S10N = First Mu<207><195>aka (22 verses)
Once <185>aunaka approaches the sage A<209>giras respectfully and ç
puts him the question: `O Venerable one! What is that, by knowing ç
which everything else is known?'
Replying to it, A<209>giras first tells him that all knowledge in ç
this world can be divided into two categories: The par<193>vidy<193> ç
and the apar<193>vidy<193>, the higher and the lower knowledges respectively. ç
Higher knowledge is that by which the indestructible Brahman (Ak<218>ara) ç
is realised. All other branches of knowledge, including the Vedas ç
and their subsidiaries, are lower knowledge.
Then A<209>giras describes the Ak<218>ara as the spirit beyond the ç
ken of the senses andthe mind, all-pervading and eternal, inherent ç
in all, but too subtle to be perceived easily.
This entire creation has been effortlessly projected by that Ak<218>ara, ç
even as a spider weaves its web or vegetation appears out of this ç
earth or the hair grows on the body.
Creation proceeds from the Ak<218>ara in an orderly way. The products ç
are: Anna (avy<193>k<216>ta, the first unmanifested aspect ofAk<218>ara/Brahman), ç
Pr<193><207>a (or Hira<207>ya- garbha, the world-soul), manas (mind- ç
principle), satya (the five elements like the earth, water and so ç
on), lokas (the seven worlds), karmas (living beings and their activities) ç
and am<216>ta (results of karmas).
The second section gives some details about Vedic rituals at first. ç
Then it goes on to condemn them as `leaky rafts' (ad<216><195>h<193><199>  plav<193><199>)  since  they  lead  to ç
transmigration and not to liberation. Those who praise them and advocate ç
their performance, are like the blind persons trying to lead other ç
blind ones.
@SPACE1 = 
On the other hand, those men of renunciation who live in forests and ç
practise austerities (to realise the Ak<218>ara), go to Brahmaloka ç
by the Arcir<193>dim<193>rga or the bright path.
That is why a person seeking the Ak<218>ara (Brahman) should renounce ç
the Vedic rituals and approach a competent teacher for the same. The ç
teacher, on his part, should teach such a worthy disciple all that ç
he knows.
@S10N = Second Mu<207><195>aka (22 verses)
This chapter gives further details about the Ak<218>ara from whom ç
creation has proceeded.
All living beings come out of that Ak<218>ara and return to it even ç
as sparks spring from a blazing fire and then fall back into it.
The five elements like earth and water, mind and senses (at the cosmic ç
level) as also pr<193><207>a (vital air) are born out of that Ak<218>ara ç
Puru<218>a.
The Vir<193><219>puru<218>a (Ak<218>ara in the manifested state, Cosmic ç
Being) for whom fire is the head, the sun and the moon the two eyes, ç
quarters the ears, Vedas the speech, the world the heart, the earth ç
the feet, is the inner Self of all.
He is the origin of the Vedic mantras and the sacrificial rites as ç
also the worlds attained through them.
All the living beings†from the gods right up to animals and even the ç
inanimate objects†rivers, oceans, mountains and vegetation have been ç
projected out of him.
Hence one who realises him, the highest Brahman, in one's own heart, ç
successfully destroys all bonds of ignorance here and now.
But then, how to know this Ak<218>ara Brahman, the brilliant one, ç
who is subtler than the subtlest, in whom all the worlds and beings ç
are established?
Now, the Upani<218>ad describes this process of meditation with an ç
interesting and picturesque analogy. An expert archer takes a good ç
strong bow, fixes a sharp arrow and then with great concentration ç
discharges it towards the target.
Similarly the seeker should take the bow of pra<207>ava (O<209>k<193>ra) ç
given in the Upani<218>ads, fix his Self as the arrow sharpened by ç
the practice of meditation, and discharge it with vigilant concentration, ç
towards the target, Brahman. In other words, the seeker has to concentrate ç
his purified mind on Brahman (or Ak<218>ara Puru<218>a), repeating ç
the pra<207>ava in his mind and thus attain unity with him (Brahman).
The text then advises the seekers to know this Cosmic Being, to meditate ç
upon him using Om and give up all other talk, not helpful in this. ç
This is the bridge to immortality.
After describing this Being again, as all-pervading and as the light ç
of lights the Upani<218>ad declares that one who realises him will ç
be freed from all the bonds of the heart (the mind and the intellect).
@S10N = Third Mu<207><195>aka (21 verses)
This section starts with a graphic description of the j<200>va (individual ç
soul) and ®·vara (the Supreme Soul) as two birds perching on the same ç
tree (the human body). While the former is eating the sweet and bitter ç
fruits of the tree, the latter is sitting majestically looking at ç
the other bird, itself not eating any fruit.
When the first bird (the j<200>va) realises the greatness of the second ç
(®·vara), itbecomes freed from all sorrow and suffering.
This °tman (®·vara, Supreme Self) can be attained by (satya) truth, ç
(tapas) austerity and (j<210><193>na) knowledge, as alsoby (brahmacarya) ç
continence. He is realised in one's own heart as the divine light.
Then comes the famous declaration, `satyameva jayate' (`Truth alone ç
triumphs'), `na an<216>tam' (`Not falsehood'). The path devay<193>na ç
to Brahmaloka is ever connected with truth.
After  describing  once  again  the nature of this °tman as very subtle, ç
but realisable through a pure mind, the Upani<218>ad advises the ordinary ç
seekers to worship and honour the knower of the °tman to get what ç
they want.
However, if they worship or honour him without any selfish motives, ç
they can transcend even rebirth in this world.
Though intellectual pursuits and scholarship can be aids to the realisation ç
of the °tman at lower levels if utilised properly, they do not directly ç
help. In fact, °tman can be realised only by him who diligently strives ç
for it or to whom he (the °tman) chooses to reveal himself.
It should also be known that the weak and the careless cannot attain ç
him. However, those who are strong in faith and conviction, who are ç
vigilant and are endowed with the spirit of renunciation can certainly ç
attain him.
@SPACE1 = 
Such  persons  who  have  rightly understood the principles of Ved<193>nta ç
and become pure through renunciation and contemplation on the °tman, ç
will go to Brahmaloka and attain total liberation there. Even as the ç
rivers flowing into the ocean lose their separate identity and get ç
merged in it, the liberated soul gets merged in Brahman, the Supreme ç
Person.
The Upani<218>ad closes with a statement that this spiritual wisdom ç
must be taughtto the deserving seekers who have completed the special ç
rite called `·irovrata' current  among  the  followers  of  the Atharvaveda ç
and not to others.
@NT = mu<207><195>ana
@N1 = (`haircutting,' `shaving')
In the life of a Hindu, every act, whether a part of daily routine ç
or occasional, is considered sacred and hence done religiously. This ç
attitude helps himto purify his whole being in course of time.
Mu<207><195>ana or ke·avapana (haircutting or shaving) is one such ç
act. The dharma-·<193>stras prescribe that it will be beneficial if ç
done when certain stars are present† like Hast<193>, Citr<193> and ç
Sv<193>t<200>†and during certain r<193>·is or zodiacal signs like ç
Makara (Capricorn), Dhanus (Sagittarius), Kany<193> (Virgo) or Mithuna ç
(Gemini).
As regards the sa<221>ny<193>sins, some (belonging  to  the  Advaita  tradition) ç
tonsure their heads completely whereas others (mostly of Vai<218><207>ava ç
tradition) keep the ·ikh<193> (tuft of hair) and shave the rest.
Coming to the practice of tonsure of the widows, it may be noted that ç
there is no Vedic authority or any reference in the early sm<216>tis ç
and dharma·<193>stras. The solitary exception is Skandapur<193><207>a. ç
The practice that exists mostly among some sections of the br<193>hma<207>as ç
in South India might not be older than the 14th century. It has practically ç
disappeared now.
The idea probably was to protect their chastity and inspire them to ç
lead a life like that of a sa<221>ny<193>sin.
@NT = muni
@N1 = (`one who is immersed in<R>ç
contemplation')
@EMERGENCY = The word `muni' is derived from the root-verb `man' (`to ç
think', `to contemplate'). Hence it means anyone who contemplates ç
deeply on God and the higher values of life.
@EMERGENCY = The <184>gveda (10.136.2-3) calls munis as the sons ç
of V<193>tara·ana who wear dirty clothes and are in ecstacy. Munis ç
were befriended by Indra and other gods (ibid 8.17.14 and 10.136.4).
@EMERGENCY = Great sages and ascetics were called munis. The lists ç
of munis generally include Vasi<218><219>ha, his son, <185>akti and ç
Par<193>·ara.
@EMERGENCY = In the tradition of Sanskrit grammar, the three great ç
grammarians†P<193><207>ini (400 <MS>B.<|>C.<D>), K<193>ty<193>yana ç
and Pata<210>jali (200 <MS>B.<|>C.<D>)† are generally called `munitraya'.
@EMERGENCY = Some of the scriptures like the Hariva<221>·a call ç
certain persons as munis. For instance: the teacher who gives d<200>k<218><193> ç
(religious vows), the teacher of the Vedas, an ascetic, an assembly ç
of old ascetics, an acclaimed man of wisdom and so on.
@EMERGENCY = In iconographical works, images of munis are to be prepared ç
according to the navat<193>la or the a<218><219>at<193>la system. ç
They are generally shown standing and have two hands only in the poses ç
of a<210>jali (supplication) or as offering flowers or with japam<193>l<193> ç
(rosary).
@EMERGENCY = The various munis are stated to have emerged out of the ç
various parts of Brahm<193>'s body. For instance: Atri from the right ç
eye, Ara<207>i from the nostrils, A<209>giras from the mouth and so ç
on.
@NT = m<220>rdhe<218><219>ak<193>
@N1 = (`topmost brick')
Construction of Hindu temples is a highly evolved science. At each ç
step and stage, some kind of religious observance is performed before ç
proceeding further. Laying of the last and topmost brick (i<218><219>ak<193> ç
= brick) is one such, done before starting the work on the finial. ç
This brick is called `m<220>rdhe<218><219>ak<193>'. Over this comes ç
the kala·a or the finial. A<209>kur<193>rpa<207>a is the rite performed ç
on this occasion.
See <MS>A<177>KUR°RPAØA<D> also.
@NT = M<220>rti·ilpa·<193>stra
@N1 = (`Science of preparing Icons or Images,' `Iconography')
@SB = Introduction
Whether it is the fear of the unknown, or the mystery of death, especially ç
of one's parents and ancestors, or, an admiration for the great heroes ç
who had sacrificed their lives for a cause dear to their heart, worshipping ç
some sort of symbols and icons in their honour, is an established ç
fact in the history of human civilisation. Devastating diseases or ç
the furies of nature too might have contributed to the concept of ç
some controlling forces being deified and appeased. Such `gods' could ç
have been represented originally by heaps of stones or pillars or ç
even some crude figures.
Thus  might  have  originated  the science of iconography, called ç
`M<220>rti·ilpa-·<193>stra' in Hinduism.
@SB = Vedic Gods
Though the gods and godlings of popular Hinduism of the masses might ç
have originated thus, the Vedic deities of the classes were not. If ç
the Vedas, the basic scriptures of Hinduism, describe their gods in ç
a particular way, they have to be accepted unquestioningly since they ç
are considered as the revealed word of God Himself, through the great ç
<216><218>is, the sages renowned for their mystical experiences. There ç
is nothing odd or fantastic in this belief since many a world-religion ç
too claims the same infallible divinity for its scripture.
The gods of the Vedas have wonderful forms and their own peculiar ç
characteris-tics. However, their worship through their images†as we ç
have today of the deities like  <185>iva,  Dev<200>,  or  Vi<218><207>u†was  not, ç
probably, in vogue.
@SB = Vedic Literature on Image Worship
Anyway, there is enough evidence to believe that the science of m<220>rti·ilpa ç
or iconography did exist even in the Vedic period. The beautiful description ç
of the bodies, limbs and weapons of the gods (vide <184>gveda 8.29) ç
and the clear mention of the sage Tva<218><219><193> as a deva·ilpi ç
(an architect of the gods) should lead us to the conclusion that there ç
must have existed competent sculptors who could fashion the icons ç
out of solid physical materials as per the visions of the sages.
The V<193>jasaney<200> Sa<221>hit<193> (1.15.16) refers to the Sun ç
as `hira<207>yap<193><207>i' (`one with a golden hand'). The K<193><219>haka ç
Sa<221>hit<193> (22.11) refers to a sage Devala who lived by preparing ç
images. While the S<193>maveda (1.9.5) refers to an image, there ç
is a reference to a temple in the Atharva-veda (2.2.2). Other Vedic ç
works like the <186>a<195>vi<221>·a Br<193>hma<207>a (5.10), Taittir<200>ya ç
Br<193>hma<207>a and Taittir<200>ya °ra<207>yaka refer not only ç
to the images of gods but also to the sculptors like Tva<218><219><193>.
By the time of the ·rautas<220>tras and the g<216>hyas<220>tras, worship ç
of deities through images in temples seems to have been fairly well-established ç
(vide Bodh<193>yana G<216>hyas<220>tras 3.7).
@SB = Evolution of Icons
Apart from the images of various gods, honouring or worshipping several ç
icons and symbols like the ·ivali<209>ga, the ·r<200>cakra, various ç
yantras as also kumbhas (pots filled with water) gradually appeared ç
in the Hindu religious firmament over the centuries. Starting of various ç
sects and cults by new religious leaders, and their diffusion, as ç
also the growth of the <193>gamas and tantras may have been an important ç
factor in this development. This naturally gave a fillip to the old ç
science of m<220>rti-·ilpa·<193>stra or Hindu Iconography.
@SB = Literature on Iconography
With the popularity and evolution of image worship, voluminous literature ç
on this science and art grew over the years. Some of the more important ç
works are:
@IN2 = Bodh<193>yana G<216>hyas<220>tras<R>ç
B<216>hatsa<221>hit<193><R>ç
K<193>ra<207><193>gama<R>ç
M<193>nas<193>ra<R>ç
Mayamata<R>ç
<185>ilparatna<R>ç
<185>ilpasa<209>graha<R>ç
<185>ilpas<193>ra<R>ç
<185>ukran<200>tis<193>ra<R>ç
Suprabhed<193>gama<R>ç
Vaikh<193>nas<193>gama<R>ç
Vi<218><207>udharmottarapur<193><207>a
@SB = Images for Worship†Public<|>and<|>Private
Though the establishment of images in temples and their worship became ç
common, it had its effect on the devotees visiting the temples, gradually ç
inducing them to have private shrines in their homes and have images ç
there for worship. The general rule is that these images should be ç
small in size, of the size of the thumb of the worshipper.
The images in the temples can, of course, be of any size; but, should ç
be big enough to be seen by a large number of devotees.
@SB = Materials for Making the Images
The images fixed permanently in the temples†called `acala' or `dhruvabera'† ç
are made of stones like granite, soapstone or marble. The other images ç
like utsava-m<220>rtis (processional images) or the ones worshipped ç
at home, are made of metal, precious stones, wood or clay. Though ç
images are sometimes prepared out of ivory also, they are not considered ç
as fit for worship. Metal images, made of silver or gold or pa<210>caloha ç
(alloy of five metals) are most common.
Wooden images are seen only in two temples: the Jagann<193>tha temple ç
at Pur<200> (in Orissa) and the Trivikrama temple at Tirukkoil<220>r ç
(in Tamil Nadu).
@SB = Dhruvabera Images
The permanently fixed images† called dhruvabera or acala†are of three ç
types: the sth<193>naka (in the standing posture); the <193>s<200>na ç
(in the sitting posture); and the ·ay<193>na (in the reclining posture).
The images of most of the gods and goddesses in the temples are of ç
the first type.
Many images of the Dev<200>, the images of Ga<207>apati and Narasi<221>ha ç
are of the second type.
Only the images of Vi<218><207>u like those of Padman<193>bha and ç
Ra<209>gan<193>tha are of the last type.
According to another classification, the dhruvaberas can be of two ç
types: ugra (fierce) and ·<193>nta (serene). Certain aspects of the ç
Dev<200> like K<193>l<200>, Narasi<221>ha, Para·u-r<193>ma and Gajah<193> ç
(<185>iva) belong to the former group. Temples of these deities are, ç
normally, built outside the village or the town. All other images ç
which do not exhibit the fierce aspect, are classed among the latter ç
group.
@SB = V<193>hanas or Mounts
@EMERGENCY = Almost all the major  deities  of Hinduism are also ç
associated with their v<193>hanas (mounts or carrier-vehicles). For ç
instance, if Vi<218><207>u has Garu<195>a (eagle) as his v<193>hana, ç
<185>iva has his Nandi (bull) to ride. Ha<221>sa (swan) for the fourfaced ç
Brahm<193>, Si<221>ha (lion) for Dev<200> (Durg<193>), M<220><218>aka ç
(rat) for Ga<207>apati and May<220>ra (peacock) for Subrahma<207>ya ç
are  other examples.
@EMERGENCY = The relation of a specific v<193>hana to a specific deity ç
is often based on mythological legends.
@EMERGENCY = Iconographically, these v<193>hanas are merely indicated ç
on the pedestal of the image. Sometimes, they may be independently ç
sculptured and installed in front of the main image.
@EMERGENCY = During festivals, the utsavam<220>rtis may be carried ç
on these v<193>hanas, which are separately prepared and housed in ç
their own sheds in temples.
@SB = Sculpturing of the Images†<R>ç
The T<193>lam<193>na System
Since <185>ivali<209>gas and images of m<193>t<216>devat<193>s (mother-goddesses) ç
have been unearthed in the Indus Valley Civilisation, one can surmise ç
that Hindu Iconography has been an ancient science which existed even ç
as early as 3000 <MS>B.<|>C.<D>
Hinduism considers, as in other fields of life, the sculpturing of ç
images, especially of gods and goddesses, as a sacred religious act. ç
Hence, the ·ilpi or the sculptor, is expected to bind himself with ç
d<200>k<218><193> or initiation and certain vows.
Unlike the human beings who can be seen and closely observed by the ç
sculptor at the time of sculpturing the image, the gods are invisible ç
to the physical eyes. Hence, the one and only source and support for ç
his work of art is the dhy<193>na·loka (verse describing the features ç
of the deity) of thatparticular deity. These dhy<193>na-·lokas describe ç
the features as revealed in the mystic vision of the <216><218>i to ç
whom the revelation came. That is why the sculptor is commanded by ç
the ·<193>stras to lead a well-regulated and pure life as per the ç
prescribed norms (the same as d<200>k<218><193>), repeat the dhy<193>na-·loka ç
mentally as much as possible and pray to the deity to reveal his/her ç
form. Gradually the revelation comes. The form seen in such revelations ç
is called `mantra- m<220>rti'. It is this form that the sculptor ultimately ç
reproduces outside in stone or other material.
@SPACE1 = 
This d<200>k<218><193> is of two types: ek<193><207><195>a and pak<218>a. ç
The former applies to such cases where the sculptor works continuously ç
until the image is completed. When that is not possible, and the work ç
has to be done intermittently, the latter mode is adopted. However, ç
even in the latter case,mental devotion and seriousness of purpose ç
have to be kept up.
When all the rules pertaining to d<200>k<218><193> are meticulously ç
observed, the sculptor will succeed in infilling the image with a ç
subtle power of life as it were.
The most important aspect of sculpturing an image is a thorough knowledge ç
of  pratim<193>-m<193>na-lak<218>a<207>a  (the  special characteristics ç
and relative measurements of an image†or iconometry). A concept basic ç
to this science of measurement or iconometry is that the face of a ç
human being (from the top of the forehead to the bottom of the chin) ç
is almost of the same length as that of the palm of that person (from ç
the top of the middle finger to the base of the palm, just above the ç
wrist). This is technically called `t<193>la'. This t<193>la is subdivided ç
into 12 equal parts, each such part being named `a<209>gula.'
All the parts of the image to be sculptured are expressed in terms ç
of thist<193>la and a<209>gula. Hence the name `T<193>lam<193>na ç
System'.
While describing the m<193>nas or the dimensions of an image, some ç
works like the M<193>nas<193>ra (55.9) use the following technical ç
terms: pram<193><207>a (breadth); parim<193><207>a (circumference); ç
lambam<193>na (measurement taken along the plumbline); unm<193>na ç
(thickness or diameter) and upam<193>na (interspaces).
The well-known work B<216>hatsa<221>hit<193> (68.7) classifies the ç
human beings into five types according to their heights. Out of these ç
only the first known as `ha<221>sa' and the last as `m<193>lavya' ç
are important. The height of ha<221>sa is 96 a<209>gulas (or a<218><219>at<193>la) ç
and that of m<193>lavya 108 a<209>gulas (or navat<193>la).
@SPACE1 = 
TheT<193>lam<193>na System prescribes sixteen varieties of t<193>las ç
for different types of beings including animals, goblins and demons. ç
Out of these only a few, the more important ones, may be described:
@SPACE1 = 
1.
@NK = Ekat<193>la (one t<193>la): lion's head (in motifs); K<220>rma ç
or Tortoise incarnation of Vi<218><207>u.
2.
@NK = Dvit<193>la (two t<193>las): Matsya or Fish-incarnation of Vi<218><207>u.
3.
@NK = Trit<193>la (three t<193>las): bh<220>tas or goblins, attendants ç
of <185>iva.
4.
@NK = Pa<210>cat<193>la (five t<193>las): boys; hunchbacks; Ga<207>apati; ç
V<193>mana.
5.
@NK = <186>a<219>t<193>la (six t<193>las): Ga<207>e·a; Var<193>ha; ç
Kum<193>ra (Subrah-ma<207>ya).
6.
@NK = A<218><219>at<193>la(eight  t<193>las):sages; human beings ç
(both male and female).
7.
@NK = Navat<193>la (nine t<193>las): gods like Indra and asuras or ç
demons.
8.
@NK = Da·at<193>la (ten t<193>las): A<218><219>a-dikp<193>lakas (eight ç
guardian deities of the quarters); the twelve °dityas; the eleven ç
Rudras; goddesses like Lak<218>m<200> and P<193>rvat<200>; the trinity, ç
viz., Brahm<193>, Vi<218><207>u and <185>iva.
According to another version, all human beings should be represented ç
in saptat<193>la (seven t<193>las), goddesses in a<218><219>at<193>la ç
(eight t<193>las) and gods in navat<193>la (nine t<193>las).
T<193>las greater than this (eleven to sixteen) are to be used for ç
deities like Narasi<221>ha, Skanda and Hanum<193>n, goddesses like ç
Ca<207><195><200>, wicked giants and some fierce goddesses as also ç
great d<193>navas like Mahi<218><193>sura and R<193>va<207>a.
One point has to be specially noted here. Even though the various ç
treatises on Hindu Iconography give general rules, patterns and directions, ç
the sculptor still has plenty of freedom either regarding the depicting ç
of the facial features or the ornaments or dresses and implements. ç
That is why any two images of the same god in the same posture sculptured ç
by two different artisans†say, Ga<207>apati† will not be absolutely ç
identical<|>!
@SB = Kir<200><219>as, Mudr<193>s and °yudhas
Anotherfactorwhichembellishes images is the way kir<200><219>as ç
(crowns and hair-dos), mudr<193>s (poses of arms and hands) as also ç
the <193>yudhas (weapons, implements and other objects held in the ç
hand) are sculptured.
The kir<200><219>as, shown on the heads of images of Vi<218><207>u ç
as also of kings, are generally simple but tall, the top being either ç
flat or capped with a jewel.
The kara<207><195>amaku<219>a is a variation of the kir<200><219>a, ç
less in height and appears more like a vessel with a wide mouth. There ç
are stripes of decreasing diameters. Such crowns are generally shown ç
on the heads of the images of goddesses.
The ja<219><193>muku<219>a is the hair itself arranged in the fashion ç
of a crown. Images of <185>iva are shown with this type of crown.
Mudr<193>s are poses of fingers or of hands expressing a variety of ç
sentiments. It is quite likely that the ·ilpa·<193>stra (icono- graphy) ç
texts have borrowed the various mudr<193>s from the texts of n<193><219>ya·<193>stra ç
or dancing.
These mudr<193>s may be sa<221>yukta (poses with both hands joined) ç
or asa<221>yukta (poses with<|>one<|>hand only). The total number of ç
the mudr<193>s varies from 35 to 39. However only 8 to 10 mudr<193>s ç
are most commonly used. Some of them are: abhayamudr<193> (assuring ç
protection), varadamudr<193> (offering boons), vy<193>khy<193>namudr<193> ç
(teaching) and namask<193>ramudr<193> (obeisance).
Though the word `<193>yudha' means a weapon, it is used in the works ç
of iconography, in a more technical sense indicating anything held ç
in the hand.
The  following  are  some  of  the <193>yudhas or weapons shown in ç
the hands of the deities: tri·<220>la (trident); ·<220>la (spear); ç
vajra (thunderbolt); a<209>ku·a (goad); p<193>·a (noose); cakra (discus); ç
dhanus and b<193><207>a (bow and arrow); kha<195>ga (sword) and khe<219>aka ç
(shield); gad<193> (mace) and so on.
Other objects are: <195>amaru (small hand-drum); darpa<207>a (mirror); ç
kama<207><195>alu (water-pot);  pustaka  (book);  ak<218>am<193>l<193> ç
(rosary); gha<207><219><193> (bell); kha<219>v<193><209>ga (magical ç
wand); padma (lotus); ·a<209>kha (conch); modaka (a kind of sweet); ç
d<193>lima (pomegranate); ik<218>u (sugarcane); bhagnadanta (broken ç
tusk); cint<193>ma<207>i (wish-yielding gem); sruk (ladle); p<193>nap<193>tra ç
(vessel for drinking) and so on.
Most often, these weapons, implements and objects, can indicate which ç
deity the icon represents, since they are invariably associated with ç
that deity. For instance: <185>iva with tri·<220>la and <195>amaru; ç
Sarasvat<200> with pustaka and ak<218>am<193>l<193>; Ga<207>apati ç
with bhagnadanta and modaka; Lak<218>m<200> with padma; Brahm<193> ç
with kama<207><195>alu; Vi<218><207>u with ·a<209>kha and cakra; Skanda ç
(Subrahma<207>ya) with ·<220>la; Balar<193>ma with hala (plough) and ç
so on.
@SPACE1 = 
One more feature that is to be noticed in the sculptured images is ç
the number of heads and arms. Most of the gods have four arms. Goddesses ç
like Durg<193> have eight or ten or even eighteen arms. If Brahm<193>, ç
the creator is shown with four heads, <185>iva is, sometimes (as pa<210>c<193>nana), ç
sculptured with five and <186>a<207>mukha (as the very name indicates) ç
with six.
Though, on the face of it, these images  may  appear  queer  or  even ç
grotesque,  they  are  highly  symbolic, indicating supreme poweror ç
supreme- intelligence.If the national flag of a country can reflect ç
the past glories and present aspirations of the people of that country ç
or a cross, the supreme sacrifice of Christ for the good of mankind, ç
why not concede that these images also can stand for the supreme power ç
and intelligence of the Supreme Lord in that form?
@SPACE = 
@SPACE1 = 
@SB = Idolatry and Image-Worship
@SPACE1 = 
@SPACE1 = 
This naturally takes us to the topic of image-worship which is often ç
dubbed as idolatry by self-proclaimed iconoclasts, forgetting that ç
they too are practising their own brand of the same!
No Hindu ever worships an image or prays to it believing that itself ç
to be God or the deity! His prayers are addressed to God Himself, ç
the image serving only as an aid to his imagining the Divine Presence ç
within himself. Some of the scriptures declare that the worship of ç
images in only the kindergarten of religion and urge the votaries ç
to gradually rise to the level where they can feel the Divine within ç
oneself and also see him in all.
However, there is also another view expressed by the pur<193><207>as, ç
the <193>gamas and the tantras. According to this, when an image is ç
prepared strictly as per the dictates of the scriptures, and is properly ç
consecrated, it becomes `alive' as it were, radiating the subtle presence ç
of the deity in it. It is akin to an electric bulb start burning as ç
soon as the line is connected to the source of electrical energy. ç
If this view is accepted†as felt by many a greatmystic and<|><|>saint ç
while visiting such temples where the images have been properly installed ç
and consecrated†then, the worship offered even to such a physical ç
image is accepted by the deity residing init.
@SPACE = 
@SPACE = 
@SB = Other Related Rites
@SPACE = 
Some of the more important rites and rituals to be conducted before ç
the image isdeemed fit for worshipping in the temple are:  jal<193>dhiv<193>sa  (keeping  the ç
image immersed in water for 3 days); dh<193>ny<193>dhiv<193>sa (putting ç
the image for rest on grains for another 3 days); ·ayy<193>dhi-v<193>sa ç
(making the image lie down on a specially prepared bed for 3 more ç
days); netronm<200>lana (`opening' the eyes of the image by marking ç
the pupils of the eyeballs with a golden needle); a<218><219>abandha ç
(adhesive paste of eight substances like lac and perfume, spread at ç
the place where the image is to be fixed) and pr<193><207>a-prati<218><219>h<193> ç
(the ceremony for infusing the life-force of the deity).
It may also be mentioned here, though in passing, that the dimensions ç
of a temple, especially the garbhag<216>ha or the sanctum, are closely ç
inter-related with the height of the image. Works like the M<193>nas<193>ra ç
and the B<216>hatsa<221>hit<193> give many details regarding the ç
construction of temples.
@SB = Four Styles of Hindu Iconography
@SPACE = 
Right from the period of Indus Valley Civilisation, Hindu Iconography ç
has beencontinuously growing and evolving. Experts in its historical ç
evolution have recognised four distinct styles in it. Theymay be ç
listed as follows: 1) The Madhur<193> style; 2) The early C<193><202>ukya ç
andthe Pallava styles; 3)The later C<193><202>ukya and the Hoysa<202>a ç
styles; and 4)the styles developed in Bengal, Assam and Orissa.
In the first two styles, simplicity and naturalness are evident. The ç
third is characterised by heavy ornamentation and finesse of sculpturing. ç
The last strikes the viewers with round faces, large fish-shaped eyes, ç
wide foreheads and thin lips.
@SPACE = 
@SB = Conclusion
@SPACE = 
Every science and art of the Hindus, even if they appear to be secular ç
in character, are basically related to the spirit, either as its expression ç
or as an attempt at leading to it. M<220>rti·ilpa·<193>stra or the ç
science of images†iconography†is no exception. More than the external ç
beauty, it is the feeling of devotion that an image arouses in the ç
minds of the votaries that is important.
A beautiful image can rouse our admiration. If the image has the likeness ç
of the deity revealed to a <216><218>i (mystic, sage) and is further ç
consecrated ceremonially by proper religious rites prescribed in the ç
scriptures, its power to awaken our innate divinity will be tangibly ç
felt. Further, visits of saints (as part of their pilgrimage to holy ç
places) will enhance this power to suchan extent that these temples ç
and images will become an unfailing source of inspiration for generations.
If God does not dwell in such images, where else will he?
See also <MS>HINDU TEMPLES<D>.
@NT = M<220>rtya<218><219>aka
@N1 = (`eight forms')
See <MS>A<186><187>AM<188>RTIS.<D>
@NT = musala
@N1 = (`wooden club')
In Vedic sacrifices, very often, grains will have to be pounded or ç
dehusked. For this, a musala is used. It is a wooden pestle made of ç
khadira wood (Acacia catechu) with a metallic head.
Some deities like Balar<193>ma (elder brother of K<216><218><207>a) ç
are shown with the musala in one of the hands, as a weapon.
@NT = music
See <MS>SA<177>G®TA.<D>
@NT = Mu<218><219>ika
Mu<218><219>ika and C<193><207><220>ra were the most powerful wrestlers ç
in the court of the evil king Ka<221>sa. When the latter invited K<216><218><207>a ç
and Balar<193>ma to attend a special sacrifice called Dhanury<193>ga ç
at Mathur<193>, they obliged. Out of the several stratagems employed ç
by Ka<221>sa to kill K<216><218><207>a was to challenge him (and Balar<193>ma) ç
for a wrest-ling bout with these two. In the ensuing fight, K<216><218><207>a ç
killed C<193><207><220>ra whereas Balar<193>ma finished Mu<218><219>ika.
@NT = mysticism
See <MS>YOGA.
@NT = mythology
See <MS>PUR°ØAS.
@END = 
