@H = F
@NT = fasting
See <MS>UPAV°SA.<D>
@NT = father
See <MS>PIT°.<D>
@NT = festivals
See <MS>VRATAS AND UTSAVAS.<D>
@NT = five fires
See <MS>PA<178>C°GNI.

@NT = flesh-eating
See <MS>M°<189>SABHAK<186>AØA.<D>
@NT = food
See <MS>°H°RA<D> and <MS>°H°RA<185>UDDHI.<D>
@NT = funeral monuments
See <MS>GRAVES.<D>
@NT = funeral rites
See <MS>ANTYE<186><187>I, BURIAL, CREMATION<D> and <MS><185>R°DDHA.
@END = <R>ç

