@H = L
@NT = l<193>ghava
@N1 = (`lightness')
An earnest practice of yogic exercises like  pr<193><207><193>y<193>ma  (See  <MS>PR°Ø°Y°MA<D>  for ç
details.) under the guidance of an expert teacher will engender certain ç
signs, both physical and psychical, by which one can judge the progress. ç
One of these is l<193>ghava or laghutva, a feeling of lightness of ç
the body, indicating good health.
See <MIS><185>VET°<185>VATARA UPANI<186>AD<D> (2.13).
@NT = laghim<193>
@N1 = (`the power to become light or weightless')
The desire to acquire siddhis or super-natural powers is not uncommon ç
among the spiritual aspirants. Pata<210>jali (200 <MS>B.<|>C.<D>) in ç
his Yogas<220>tras (3.45) mentions about eight such siddhis among ç
which laghim<193> is also one. It is the power to become extremely ç
light.
Such siddhis can be obtained by tapas (austerity) as also mantrajapa ç
(repetition of holy syllables).
Even levitation may result from the attainment of this power.
@SPACE = 
@NT = Laghu H<193>r<200>ta Sm<216>ti
@SPACE = 
During the ancient and medieval times, the life of a Hindu was well- ç
regulated, both at the personal and at the social levels, by the dharma·<193>stras. ç
As time passed and social changes became inevitable, newer dharma·<193>stras ç
or revised editions of the older ones appeared on the scene, composed ç
by competent scholars who had realised the need for suchchanges. ç
Such works were generally preceded by the words `Laghu' or `V<216>ddha', ç
especially when the authors belonged to the particular schools or ç
traditions of the older composers of these works.
The Laghu H<193>r<200>ta Sm<216>ti is one such work. Two versions ç
or editions of the same are available now.
The first one contains seven chapters and 250 verses. The main content ç
of this work deals with the four var<207>as, the four <193>·ramas ç
as also yoga.
The second version has only 117 verses and deals with ·uddhis (purificatory ç
ceremonies), pr<193>ya·cittas (expiatory rites), a·auca (ceremonial ç
impurity connected with birth and death), ·r<193>ddhas (after-death ç
rites) as also rules about inheritance and partition.
See also <MS>DHARMA<185>°STRAS.
@SPACE = 
@NT = Laghurudra
@SPACE = 
See <MS>ATIRUDRA.
@SPACE = 
@SPACE = 
@NT = Laghu Vi<218><207>usm<216>ti
@SPACE = 
This is a late work of the dharma-·<193>stra literature, having five ç
chapters and 114 verses. It deals mainly with the four var<207>as ç
and the four <193>·ramas.
Though Apar<193>rka (12th century <MS>A.<|>D.<D>) has quoted a few ç
verses from a Laghu Vi<218><207>usm<216>ti in his commentary on ç
the Y<193>j<210>avalkyasm<216>ti, those verses are not found in ç
the printed texts available now.
See also <MS>LAGHU-H°R®TA-SM<184>TI<D>.
@NT = Laghuyogav<193>si<218><219>ha
The Yogav<193>si<218><219>ha†also known as Yogav<193>si<218><219>ha ç
R<193>m<193>ya<207>a†is a well-known standard treatise dealing with ç
Advaita Ved<193>nta of an uncompromising type. This voluminous work ç
(of 23,734 verses in six prakara<207>as or sections) has been summarised ç
by several writers. One such work more well-known than the others ç
is theLaghuyogav<193>si<218><219>ha attributed to one Abhinanda ç
(9th century <MS>A.<|>D.<D>), a br<193>hma<207>a from K<193>·m<200>ra ç
(Kashmir). It has six prakara<207>as or sections, containing 5000 ç
verses.
Only a very brief summary of the same can be given here.
@S10N = 1.	Vair<193>gyaprakara<207>a<R>ç
	(3 chapters, 359 verses)
The work begins in a dramatic setting. <185>r<200> R<193>ma goes on ç
a pilgrimage with the permission of his father Da·aratha. After returning, ç
he becomes a little dejected and develops intense vair<193>gya (spirit ç
of renunciation). As a result he loses all interest in life. Seeing ç
this, the sages who had gathered there under  the  leadership  of  Vi·v<193>mitra, ç
request Vasi<218><219>ha to tackle the problem. Then ensues a long ç
dialogue between him and <185>r<200> R<193>ma, continuing till the ç
end of the work.
The gist of this section centres roundthe evanescent nature of the ç
world. Pleasures of life are temporary, ultimately leading to suffering. ç
Everything in this world is destructible. Attachment to it leads to ç
sa<221>s<193>ra (transmigration). Mind is subject to v<193>san<193>s ç
(past impressions). Hence attempts should be made to destroy these ç
v<193>san<193>s and attain freedom.
@S10N = 2.	Mumuk<218>uvyavah<193>ra prakara<207>a<R>ç
	(one chapter, 110 verses)
@SPACE = 
This section concentrates on the subject of conquest of v<193>san<193>s, ç
deep impressions in the mind carried over from past lives.
The mind can be compared to a river flowing in two parallel streams ç
viz., ·ubhav<193>san<193>s (good impressions) and a·ubhav<193>san<193>s  (bad  impressions).  The ç
mumuk<218>u (seeker after liberation) should try to increase the former, ç
and, attenuate and destroy the latter. This is possible only if there ç
is puru<218>aprayatna or self- effort.
Mok<218>a or liberation is compared to a mansion with four entrances, ç
each being guarded by a sentry. They are ·ama (internal peace), viveka ç
(discrimination), s<193>dhusa<209>ga (company of holy persons) and ç
santo<218>a (contentment). Out of these, s<193>dhusa<209>ga is the ç
easiest and the most effective.
@SPACE = 
@S10N = 3.	Utpattiprakara<207>a<R>ç
	(9 chapters, 1008 verses)
@SPACE = 
This section mainly propagates the advaitic doctrine known as `d<216><218><219>i-s<216><218><219>i-v<193>da' ç
(See <MS>D<184><186><187>I-S<184><186><187>I-V°DA<D> for details.).
The whole world is a creation of the mind. If the mind is stilled, ç
the world that binds, also disappears.
There are some interesting up<193>khy<193>nas (stories) like L<200>lop<193>khy<193>na, ç
Indrop<193>khy<193>na, Br<193>hma<207>op<193>khy<193>na and Lava<207>op<193>khy<193>na  to  illustrate  the ç
important teachings.
Saptabh<220>mik<193>s†seven stages of knowledge from ·ubhecch<193> ç
upto turyag<193>† have also been described.
@S10N = 4.	Sthitiprakara<207>a<R>ç
	(5 chapters, 541 verses)
Sthiti or sustenance of this world is also an imagination of the mind ç
like utpatti or creation. This is the important teaching of this section.
A person, identified with the body-mind-complex thinks he is the doer ç
and enjoyer. Hence he gets bound. He can free himself by cultivating ç
one of these two attitudes: `I am not the doer,' `I am notthe body'; ç
`I do everything', `I am every-thing'.
The s<193>dhaka can also free himself by constantly thinking that ç
he is subtler than the subtlest.
There are five interesting stories in this section also.
@S10N = 5.	Upa·amaprakara<207>a<R>ç
	(10 chapters, 1124 verses)
The main topic of this section is how to quieten the mind and lead ç
it to dissolution.
It is due to the mind that we have the sense of `I', `you' and `this'. ç
This can be dissolved by dissolving the mind (called manon<193>·a ç
here). At first one has to cultivate good v<193>san<193>s or tendencies ç
such as maitr<200> (friendly attitude towards all beings), karu<207><193> ç
(compassion) and so on. Then one has to transcend even these when ç
the mind as mind gets dissolved. This leads to a direct awareness ç
of the <193>tman or the Self.
This section too contains several up<193>khy<193>nas or stories as ç
those of Janaka, Bali, Prahl<193>da, Udd<193>laka and others.
@S10N = 6.	Nirv<193><207>aprakara<207>a<R>ç
	(18 chapters, 1859 verses)
This long section deals with nirv<193><207>a or mok<218>a (liberation) ç
and the nature of a liberated soul. Through self-effort, the s<193>dhaka ç
gradually destroys all v<193>san<193>s and  realises  his  essential  nature  as ç
Brahman. This can be attained only by the pure buddhi or intellect. ç
Though ·<193>stra (the scriptures), guru (spiritual teacher) and their ç
teachings are a help, they have no direct role to play.
In this section, there are references to Jainism and Buddhism as also ç
the Bhagavadg<200>t<193>. Also, as in other sections there are plenty ç
of stories like those of Bhu·u<207><195>a, Arjuna, Bhag<200>ratha, ç
Kaca and Ik<218>v<193>ku to illustrate the teachings given here.
On the whole it is an extremely interesting work and can serve as ç
an introduction to the study of the bigger work, the Yogav<193>si<218><219>ha ç
R<193>m<193>ya<207>a.
@NT = lagnanir<207>aya
@N1 = (`deciding a suitable lagna [for initiation into a mantra]')
The zodiac has been divided by the astrologers into twelve r<193>·is ç
(special signs comprising certain groups of stars) like Me<218>a (Aries), ç
V<216><218>abha (Taurus) and so on. Every day, the sun (as viewed ç
from the earth) appears to pass through all the twelve R<193>·is from ç
Me<218>a (Aries) to M<200>na (Pisces). The r<193>·i at the time of ç
sun-rise is said to be the `lagna' for that day. This has an important ç
bearing on astrological calculations.
@SPACE1 = 
When spiritual aspirants desire to receive a mantra through initiation ç
from a qualified guru, different lagnas have been prescribed for different ç
deities. For instance, to receive mantras of Vi<218><207>u, the lagnas ç
V<216><218>abha (Taurus), Si<221>ha (Leo) and Dhanus (Sagittarius) ç
are auspicious.
Similarly Me<218>a (Aries), Kark<193><219>aka (Cancer) and Tul<193> ç
(Libra) are good for receiving <185>ivamantras.
And for imparting or receiving <185>akti or the Dev<200> mantras, ç
Mithuna (Gemini), Kany<193> (Virgo) and M<200>na (Pisces) are considered ç
good.
Inauspicious moments can be known by a study of the lagnaku<207><195>ali ç
(chart based on lagna) and they must be avoided.
@NT = l<193>jahoma
@N1 = (`offering parched grains into the fire')
The dharma·<193>stras or Hindu Lawbooks have prescribed sixteen sa<221>sk<193>ras ç
or sacraments for every human being, especially of the first three ç
castes. Out of these viv<193>ha or marriage is a very important one.
Of the several steps involved in this sa<221>sk<193>ra, l<193>jahoma ç
also is one.
The brother of the bride fills her joined palms with l<193>ja or parched ç
grains,mixed with ·am<200> leaves (Prosopsis spicigera). She has ç
to offer it into the consecrated fire while going round it. Her husband ç
may touch her hands while she is offering.
The mantras uttered during this ceremony are addressed to the Vedic ç
gods like Varu<207>a and P<220><218>an, requesting them to loosen ç
the bonds with her father, and strengthen the same towards her husband.
@NT = lak<218>ahoma
See <MS>NAVAGRAHA<185>°NTI.<D>
@NT = lak<218>a<207><193>
@N1 = (`implication')
@SPACE1 = 
There are three ways in which words can express their meanings. The ç
direct way or v<193>cya is the first, as for instance in `aya<199>,' ç
which means iron. The meaning hinted at or vya<209>gya is the second, ç
as in `sa·a<209>khacakro hari<199>,' `Vi<218><207>u with ·a<209>kha ç
(conch) and cakra (discus)'. Here though the word `hari<199>' has ç
several meanings like lion, monkey, Yama, V<193>yu or Vi<218><207>u, ç
the additional word `sa·a<209>khacakra<199>' limits it to Vi<218><207>u ç
alone. The implied meaning or lak<218>ya is the third. For instance ç
in thesentence `Kali<209>ga<199> s<193>hasika<199>', `The Kali<209>ga ç
is a bold man', though the word `Kali<209>ga' means the country of ç
that name, it means by implication, a citizen of that country.
Implication, called `lak<218>a<207><193>', is of three types: jahal-lak<218>a<207><193>, ç
ajahal-lak<218>a<207><193> and jahad-ajahal-lak<218>a<207><193>.
In `jahal-lak<218>a<207><193>', the direct meaning is completely given ç
up (jahad = giving up) in favour of the implied meaning. For example, ç
consider the sentence `ga<209>g<193>y<193><221> gho<218>a<199>', `The ç
village of cowherds is in the Ga<209>g<193> river'. Since a village ç
cannot exist inside a river it is to be interpreted as `on the bank ç
of the Ga<209>g<193> river', so near that it looks as if it is under ç
the river.
In `ajahal-lak<218>a<207><193>' the direct meaning is not altogether ç
given up (ajahad = not giving up) though it cannot also be accepted ç
in toto. For instance, in the sentence `·o<207>a<199> dh<193>vati' ç
(`red colour is running'), obviously it means a red animal like a ç
horse which is running and not red colour (·o<207>a = red) itself.
@SPACE1 = 
In `jahad-ajahal-lak<218>a<207><193>', a part of the direct meaning ç
is given up and another part is retained. In a sentence like `soya<221> ç
devadatta<199>' (`This is that Devadatta'), Devadatta who is seen ç
here and now is recognised as the same person seen earlier in some ç
other place. In this recognition, Devadatta, the person, is retained ç
whereas the time and place are ignored.
It is this `jahad-ajahal-lak<218>a<207><193>' that is adopted by the ç
Advaitins while interpreting the famous Ved<193>ntic dicta like tat ç
tvam asi (`That thou art') or aha<221> brahm<193>smi (`Iam Brahman').
@SPACE1 = 
@NT = lak<218>a<207>a-pari<207><193>ma
See <MS>PARIØ°MA.
@SPACE1 = 
@NT = Lak<218>ma<207>a
As regards the well-known hero Lak<218>ma<207>a of the R<193>m<193>ya<207>a, ç
see <MS>R°M°YAØA<D> for details.
Lak<218>ma<207>a  is  also  the  name  of Duryodhana's son, considered ç
as a hero. He fought with Abhimanyu several times and was ultimately ç
killed by him on the 13th day of the Kuruk<218>etra war.
@SPACE1 = 
@NT = Lak<218>m<200>
For obvious reasons, Lak<218>m<200>, the goddess of fortune, is more ç
sought after than Sarasvat<200>, the goddess of learning. Being the ç
power and consort of Vi<218><207>u, the preserver, she is represented ç
as the power of multiplicity and the goddess of fortune, both of which ç
are equally necessary in the process of preservation.
`<185>r<200>' or `Lak<218>m<200>', as depicted in the Veda, is the ç
goddess of wealth and fortune, power and beauty. Though there is scope ç
for the supposition that <185>r<200> and Lak<218>m<200> are two separate ç
deities, the descriptions of them are so identical, that we are tempted ç
to conclude that they represent one and the same deity. Some scholars ç
opine that `<185>r<200>' was a pre-vedic deity connected  with  fertility,  water  and ç
agriculture. She was later fused with Lak<218>m<200>, the Vedic goddess ç
of beauty.
In her first incarnation, according to the pur<193><207>as, she was ç
the daughter of the sage Bh<216>gu and his wife Khy<193>ti. She was ç
later born out of the ocean of milk at the time of its churning. She, ç
being the consort of Vi<218><207>u, is born as his spouse whenever ç
he incarnates. When he appeared as V<193>mana, Para·ur<193>ma, R<193>ma ç
and K<216><218><207>a, she appeared as Padm<193> (or Kamal<193>), ç
Dhara<207><200>, S<200>t<193> and Rukmi<207><200>. She is as inseparable ç
from Vi<218><207>u as speech from meaning or knowledge from intellect, ç
or good deeds from righteousness. He represents all that is masculine, ç
and she, all that is feminine.
Lak<218>m<200>  is  usually  described  as enchantingly beautiful ç
and standing on a lotus, and holding lotuses in each of her two hands. ç
It is because of this, perhaps, that she is named as Padm<193> or ç
Kamal<193>. She is also adorned with a lotus garland. Very often elephants ç
are shown on either side, emptying pitchers of water over her, the ç
pitchers being presented by celestial maidens. Her colour is variously ç
described as dark, pink, golden yellow or white. While in the company ç
of Vi<218><207>u, she isshown with two hands only. When worshipped ç
in a temple†separate temples for Lak<218>m<200> are rather rare†she ç
is shown seated on a lotus throne, with four hands holding padma, ç
·a<209>kha, am<216>takala·a (pot of ambrosia) and bilva fruit. Sometimes, ç
another kind of fruit, the M<193>tuli<209>ga (a citron) is shown instead ç
of bilva. When shown with eight hands, bow and arrow, mace and discus ç
are added. This is actually the Mah<193>lak<218>m<200>, an aspect ç
of Durg<193>.
We can now attempt an explanation that is behind this highly symbolical ç
picture. If Lak<218>m<200> is pictured as dark in complexion, it is ç
to show that she is the consort of Vi<218><207>u, the dark god. If ç
golden yellow, that shows her as the source of all wealth. If white, ç
she represents the purest form of prak<216>ti (nature) from which ç
the universe has developed. The pinkish complexion,  which  is  more  common, ç
reflects her compassion for creatures, since she is the mother of ç
all.
Her four hands signify her power to grant the four puru<218><193>rthas ç
(ends of human life), dharma (righteousness), artha (wealth), k<193>ma ç
(pleasures of the flesh) and mok<218>a (beatitude).
The lotuses, in various stages of blooming, represent the worlds and ç
beings in various stages of evolution.
@SPACE1 = 
The fruit stands for the fruits of our labours. However-much we may ç
toil and labour, unless the Mother is gracious enough to grant the ç
fruits of our labour, nothing will be of any avail. If the fruit is ç
a coconut†with its shell, kernel and water†it means that from her ç
originate the three levels of creation, the gross, the subtle and ç
the extremely subtle. If it is a pomegranate or a citron, it signifies ç
that the various created worlds are under her control and that she ç
transcends them all. If it is a bilva fruit†which, incidentally, is ç
not very tasty or attractive, but which is extremely good for health†it ç
stands for mok<218>a, the highest fruit of spiritual life.
Am<216>takala·a also signifies the same thing, viz., that she can ç
give us the bliss of immortality.
In some of the sculptural depictions of Lak<218>m<200>, the owl is ç
shown as her carrier- vehicle. It looks rather odd and strange that ç
the goddess of fortune and beauty should have an ugly bird, the very ç
sight of which is considered inauspicious, as her carrier! Once the ç
symbolical significance of this oddity is unravelled, we will be in ç
a better position to appreciate the poor bird and its compassionate ç
mistress!
The word in Sanskrit for the owl is Ul<220>ka. Ul<220>ka is also one ç
of the names of Indra, the king of gods! Hence Lak<218>m<200> being ç
the goddess of fortune could not have found a better person to ride ç
on, than the king of gods, who personifies all the wealth, power and ç
glory that a living being can aspire for in life. At the same time, ç
here is a warning administered to the seekers of secular wealth, instead ç
of spiritual wealth, by comparing even the glory of Indra to the ugliness ç
of an inelegant and partially blind bird.
@SPACE1 = 
Based on the beautiful description given in the Bhagavadg<200>t<193> ç
(2.69) we can be generous enough to compare our owl to the sthitapraj<210>a, ç
the man of steady wisdom. Then, the symbol would mean that Mother ç
Lak<218>m<200> is the mistress of spiritual wisdom. If we are not ç
so generous, then, we can learn a lesson from it in another way, viz., ç
`Do not shut out your eyes to the light of wisdom coming from the ç
sun of knowledge!' Out of consideration for mankind, the all-compassionate ç
Mother has kept this personification of ignorance under her control.
@SPACE = 
@NT = Lak<218>m<200>dhara
See <MS>K<184>TYAKALPATARU.
@SPACE = 
@NT = Lakshmi<%-5> <%0>Venkateswara Steam Press
During the period <MS>A.<|>D.<D> 1750 to 1900, a lot of interest had ç
been roused among the European scholars and others to knowabout the ç
ancient and medieval Hindu scriptures. One of the pioneering publishing ç
houses that arose during this time was the Lakshmi Venkateswara Steam ç
Press.
It was established in <MS>A.<|>D.<D> 1871 in Bombay (now Mumbai) with ç
the sole aim of publishing all the extant Sanskrit and Hindi works ç
of outstanding merit on different subjects. So far, this publishing ç
house has printed as many as 2800 titles. Many of these have been ç
reprinted several times. The subjects covered are philosophy, Indian ç
mythology, the two great epics† R<193>m<193>ya<207>a and Mah<193>bh<193>rata†Bhagavad-g<200>t<193>, ç
classical Sanskrit literature, Astro-logy, °yurveda, music and so ç
on.
Its present name and address are:Shri Venkateshwar Press, Mumbai; ç
Khemraj Shrikrishnadas, 91/109, Khemraj Shrikrishnadas Marg, 7th Khetwadi ç
Back Road Corner, Mumbai 400<|>004, India.
It has branches at Pune, Thane (inMaharashtra) and V<193>r<193><207>asi ç
(in Uttar Pradesh).
@SPACE = 
@NT = Lakul<200>·a
@SPACE = 
The P<193>·upata Cult is a prominent aspect of <185>aivism. (See <MS><185>AIVISM.<D>) ç
It is said to have been started by Lakul<200>·a (or Nakul<200>·a), ç
supposed to be the 28th (and the last) human incarnation of Lord <185>iva. ç
Since he used to hold a lakula (or club) always, he came to be known ç
as Lakul<200>·a.
The village Karja<207> near Baroda in Gujarat seems to have been the ç
place where he lived.
He had four disciples: Ku·ika, Mitra, Garga and Kauru<218>ya.
The town Jharpatan in Gujarat has a temple dedicated to him.
Since the P<193>·upata Cult had spread in some parts of Gujarat and ç
South India even by the 6th century <MS>A.<|>D.<D> Lakul<200>·a must ç
have lived much earlier.
@SPACE = 
@NT = L<193>ld<193>s<200>s
@N1 = (`followers of L<193>ld<193>s')
@SPACE = 
One of the religious sects thrown up by the Bhakti Movement is that ç
of L<193>ld<193>s who lived in the latter half of the 16th century ç
(d. <MS>A.<|>D.<D> 1647). He belonged to the Meo caste (robbers by ç
profession!) and was born in Alwar of Rajasthan. He was deeply influenced ç
by Kab<200>r (<MS>A.<|>D.<D> 1440-1518) and D<193>du (<MS>A.<|>D.<D> ç
1544-1603). His sayings and songs, composed as a work, are known as ç
`B<193>n<200>'.
L<193>ld<193>s<200>s are his followers. They lay great stress on the ç
repetition of R<193>mn<193>m (Lord R<193>ma's name) as the only s<193>dhana ç
or spiritual practice.
@NT = Lalit<193>
An aspect of the Dev<200> which is more widely worshipped in South ç
India is Lalit<193> Tripurasundar<200>. Repetition of the well- known ç
Lalit<193>sahasran<193>ma and Tri·at<200>*, as also the worship ç
of her emblem, the `<185>r<200>cakra,' are extremely popular. The ç
initiation into her powerful mantra, the pa<210>cada·<193>k<218>ar<200> ç
(mantra of 15 letters) is an esoteric rite. Regular worship of the ç
<185>r<200>cakra is said to yield any result the devotee desires.
If Durg<193> and K<193>l<200> represent the aspects of power of the ç
Goddess, Lalit<193> represents the aspect of beauty. Hence her form ç
is depicted as extremely beautiful and her worship more refined.
According to the Lalitop<193>khy<193>na of the Brahm<193><207><195>a ç
Pur<193><207>a, Lalit<193> Dev<200> manifested herself in the midst ç
of a disc of extreme brilliance, that arose from the sacrificial pit ç
when Indra was performing a sacrifice in honour of her. At the behest ç
of the gods assembled there, she chose to wed K<193>me·vara (Lord ç
<185>iva). She destroyed the demon Bha<207><195><193>sura and annihilated ç
his city, the <185>o<207>itapura. Vi·vakarm<193>, the engineer of ç
the gods, built a gorgeous city `<185>r<200>pura' on the mountain ç
Meru, for her sake, where, along with her spouse <185>iva K<193>me·vara, ç
she is residing eternally. The <185>r<200>cakra actually represents ç
the Dev<200> in this <185>r<200>pura.
Bha<207><195><193>sura, the shameless demon, living in the <185>o<207>itapura, ç
the city of blood and flesh, is actually the ego which makes the soul ç
identify itself with the body and estrange itself from all the divine ç
forces. When the Dev<200>, who is the embodiment of God's power and ç
grace, `kills' it, she is actually liberating it from its stifling ç
limitations.
Lalit<193> is usually depicted as slightly red in colour (as that ç
of the dawn) and extraordinarily beautiful. In her four hands she ç
is holding a bow of sugarcane, arrows, the goad (a<209>ku·a) and the ç
noose (p<193>·a). Sometimes she is shown holding a wine cup made of ç
diamond. One of her feet, usually the left, is shown resting on a ç
pedestal, also of diamond.
The bow made of sugarcane actually represents the mind. It is through ç
the mind that we experience all joy. Hence it is described as made ç
of sugarcane. The bow is the instrument for discharging the arrows. ç
The mind is the instrument by which the sense organs are `shot' towards ç
the sense-objects. Hence it is described as a bow. The arrows are ç
the pa<210>ca-tanm<193>tras, the five subtle elements of <193>k<193>·a ç
(ether), v<193>yu (air), agni (fire), <193>pas (water), p<216>thv<200> ç
(earth). The sense organs like the eye and the ear, are products of ç
these subtle elements and are discharged like arrows, through the ç
mind, towards the sense-objects. Hence the subtle elements are described ç
as the arrows in her hand. She is the power that energises and controls ç
our minds and sense organs. This is the underlying idea. The p<193>·a ç
(noose) is actually r<193>ga (attachment) which binds. The a<209>ku·a ç
(goad) is krodha (anger, aversion) which hurts. The power that animates ç
our attachments and aversions is also hers. If we forget her, she ç
can bind us with r<193>gap<193>·a, and pierce us with the krodh<193><209>ku·a. ç
If we take refuge in her, she can withdraw them into her hands and ç
thereby free us from their torment.
An  account  of  Lalit<193>  cannot  be complete without a few words ç
of description of the <185>r<200>cakra. The <185>r<200>cakra is essentially ç
a yantra.* The form and pattern of the deity. It is a rather complicated ç
geometrical figure of forty three triangles formed by the intersection ç
of nine triangles, of which five have their apexes downward and the ç
other four upward. This is surrounded by concentric circles with eight ç
and then sixteen lotus petals. The whole figure is skirted by a square ç
of three lines with openings in the middle of each side. There is ç
a dot in the centre of the entire diagram.
This dot represents the combination of <185>iva and <185>akti, as ç
also the first throb, which gradually gathers momentum and gets concentrated ç
into a polarisation of <185>iva and <185>akti, but continuing to keep ç
the original <185>iva-<185>akti combination also. The process repeats ç
continuously resulting in various levels of creation, which are depicted ç
by the different triangles and the lotus petals.
The <185>r<200>cakra can be used for permanent worship either in the ç
form of a yantra (two dimensional engraved figure) or<|>in<|>the form ç
of meru (three dimensional figure).
@NT = Lalit<193>sahasran<193>ma
@N1-1 = (`one thousand <R>ç
names of [the Divine Mother] Lalit<193>')
The  Sanskrit  stotra  literature (hymnology) in Hinduism is very ç
vast. Some varieties of stotras are considered as very powerful, like ç
mantras or mystical formulae. Their chanting, either ceremonially ç
or even simply†but with faith and devotion†is said to confer on the ç
votaries whatever they want. The sahasran<193>ma (one thousand names) ç
stotras belong to this group.
The Lalit<193>sahasran<193>ma is one such, which is not only famous ç
but also popular even today, especially in South India. Actually, ç
it forms the 36th chapter of the work Lalitop<193>khy<193>na which ç
itself, again, is a part of the Brahm<193><207><195>apur<193><207>a.
It was taught by the sage Hayagr<200>va (an emanation of the Hayagr<200>va ç
incarnation of Vi<218><207>u) to the sage Agastya at the latter's ç
earnest entreaties.
This wonderful and powerful hymn was composed by the V<193>gdevat<193>s ç
or the goddesses presiding over the power of speech, like Va·in<200> ç
and her companions after  being  commanded  by  the  Dev<200> herself.
The thousand names beginning with the word `<185>r<200>m<193>t<193>' ç
and ending with the word `Lalit<193>mbik<193>' and spread over 183 ç
·lokas or verses reflect an infinite variety of the Divine Mother ç
Lalit<193>'s beauties, splendours, powers and doings. Many of the ç
names are highly esoteric in nature and are difficult to comprehend ç
without the help of a teacher who is an adept in the science called ç
<185>r<200>vidy<193> (See <MS><185>R®VIDY°.<D>).
The ceremonial recitation is generally accompanied by the worship ç
of the <185>r<200>cakra (See <MS><185>R®CAKRA<D> for details.) with ç
bilva leaves (Aegle marmelos) or tulas<200> leaves (holy basil) ç
andrepetition of thepa<210>cada·<193>k<218>ar<200>mantra (mantra ç
of 15 syllables or letters). The chanting can also be done without ç
these formalities.
@SPACE1 = 
The phala·ruti (that part of the hymn which narrates the fruits of ç
the recitation) gives a long list of the benefits that a votary who ç
chants it with due respect and faith, gets. This list includes such ç
results as the merit equal to that of establishing millions of <185>ivali<209>gas ç
at K<193>·<200>, destruction of the effects of even the most heinous ç
sins, the merit of performing numberless A·vamedha sacrifices and ç
so on.
There are five commentaries on this text. Out of these, the Saubh<193>gya ç
Bh<193>skara of Bh<193>skarar<193>ya (also known as Bh<193>sur<193>nandan<193>tha) ç
is considered the best.
See <MS>BH°SKARAR°YA.<D>
@NT = Lalit<193>tri·at<200>
@N1 = (`[hymn of] three hundred names of Lalit<193> [Divine Mother]')
The sage Hayagr<200>va was an emanation from god Hayagr<200>va, an ç
aspect of Lord Vi<218><207>u. It was this sage, who was an ardent ç
devotee of the Divine Mother Lalit<193>, that taught the Lalit<193>sahasran<193>ma ç
stotra to Agastya. Even after listening to it, the sage Agastya somehow ç
felt that there was some vacuum in his heart, to fill which, he caught ç
hold of the feet of the sage Hayagr<200>va and entreated him to teach ç
him further. Three years passed by in this way! Then the Divine Mother ç
Lalit<193>dev<200> herself appeared on the scene and commanded Hayagr<200>va ç
to teach the Lalit<193>tri·at<200> hymn also to the sage Agastya. ç
Thereupon, Hayagr<200>va gladly taught it to him.
As per this story, the Lalit<193>tri·at<200> is even more powerful ç
in its efficacy than the Lalit<193>sahasran<193>ma!
The speciality of this hymn of three hundred names of the Divine Mother ç
Lalit<193> is that it contains the famous pa<210>ca- da·<193>k<218>ar<200> ç
mantra skilfully imbedded.
@SPACE1 = 
Hence all the rules that are enunciated for the recitation of the ç
bigger hymn, apply here also.
The text has a p<220>rvap<200><219>hik<193> (prologue) and a phala·ruti ç
(epilogue giving the fruits of recitation).
There is a well-known commentary on this hymn attributed to <185>a<209>kara ç
(<MS>A.<|>D.<D> 788-820) though the scholars are not unanimous about ç
his being the original (or °di-) <185>a<209>kara.
See also <MS>LALIT°SAHASRAN°MA.<D>
@NT = Lalitop<193>khy<193>na
@N1 = (`storyrelatedtothe<R>ç
[Divine Mother] Lalit<193>')
Lalit<193>, an aspect of P<193>rvat<200> is an extremely popular goddess ç
in South India. The two hymns addressed to her, the Lalit<193>sahasran<193>ma ç
and the Lalit<193>tri·at<200>, are considered as mantras, the recitation ç
of which can grant the fulfilment of any wish.
They are considered to be a part of the Brahm<193><207><195>apur<193><207>a.
The Lalitop<193>khy<193>na is said to be an integral part of this ç
pur<193><207>a and appears in its Uttarakha<207><195>a. It has 32 ç
chapters and 2743 verses.
Cast in the form of a dialogue between Hayagr<200>va and Agastya, ç
it deals exhaustively with the story of Lalit<193>dev<200>. This story ç
can be summarised very briefly as follows:
When  <185>iva  reduced  Manmatha (Cupid, Eros) to ashes, the same ç
was shaped into a beautiful image by Citra-karma, one of the attendants ç
of <185>iva. By chance, <185>iva's eyes fell on this image and lo! ç
it sprang to life. <185>iva gave this newly born person several boons, ç
a life of 60,000 years and invincibility during this period. He came ç
to be known as Bha<207><195><193>sura and started ruling over the ç
devas (gods) and the d<193>navas. Even Indra, the king of the gods, ç
became subservient to him. By the time his allotted duration of life ç
was over, the gods, under the leadership of Indra, performed a big ç
sacrifice from which Lalit<193>dev<200> emerged and assured them that ç
she would destroy Bha<207><195><193>sura and restore their kingdom ç
to them.
As per the desire of the gods including Brahm<193>,  the creator,  Lalit<193>dev<200>  was ç
married to <185>iva (K<193>me·vara) (since actually she was P<193>rvat<200> ç
in that form). Then the Dev<200> started on her victory expedition ç
against Bha<207><195><193>sura. After a fierce fight,he as also all ç
his associates, were decimated.
The overjoyed gods prayed to her with a long and beautiful hymn (Ch. ç
25, verses 10 to 42).
The work ends with the eulogy of the pa<210>cada·<193>k<218>ar<200> ç
mantra, the mantra of 15 letters, which must be received from a competent ç
guru or spiritual preceptor.
@NT = La<209>k<193>
La<209>k<193> has been well-known to the students of Hindu mythology ç
as the capital of the demon king R<193>va<207>a. The original builder ç
of this city was M<193>li. He had got it built by the divine architect ç
Vi·vakarma and was living there along with his brothers M<193>lyav<193>n ç
and Suke·a.
Since M<193>li had become a terror to the gods, Vi<218><207>u killed ç
him. When the demons deserted the city and took refuge in P<193>t<193>la ç
or the nether world, it was given to Kubera the king of the yak<218>as ç
(a type of demigods). R<193>va<207>a, a cousin of Kubera, drove him ç
away and occupied it. He started ruling it assisted by his brothers ç
Kumbha- kar<207>a and Vibh<200><218>a<207>a as also his eldest son ç
Meghan<193>da or Indrajit.
La<209>k<193> was a very rich and prosperous city of dazzling splendour. ç
Its citizens, the r<193>k<218>asa tribes, were physically strong but ç
ruthless in nature. They were addicted tosense-pleasures and drinking. ç
Even cannibalism was not uncommon among them. La<209>ki<207><200> ç
was the demon-protectress of the city.
When Hanum<193>n vanquished her she disappeared from the scene saying ç
that her time was over and the city would soon be destroyed.
See also <MS>R°M°YAØA.<D>
@NT = La<209>k<193>k<193><207><195>a
@N1 = (`book or section dealing with La<209>k<193>')
The R<193>mcaritam<193>nasa of Gosv<193>m<200> Tulas<200>d<193>s ç
(<MS>A.<|>D.<D> 1532-1623) written in the Avadh<200> dialect of the ç
Hindi language is the most celebrated version of the R<193>m<193>ya<207>a, ç
highly venerated in the Hindi belt of North India. It is based more ç
on the Adhy<193>tma R<193>m<193>ya<207>a than on that of V<193>lm<200>ki.
Out of the seven k<193><207><195>as or books of this work, the sixth ç
has been named by him as the La<209>k<193>k<193><207><195>a instead ç
of Yuddhak<193><207><195>a as done by V<193>lm<200>ki. The content ç
is the same except for some minor variations.
@NID = <+><+><+><|>See <MS>R°MCARITAM°NASA<D> and <MS>TULAS®D°S.
@NT = Lava
One of the twin-sons of <185>r<200> R<193>ma and S<200>t<193>, Lava ç
got half the kingdom, the capital of which was <185>r<193>vasti.
See <MS>KU<185>A<D> for more details.
@SPACE1 = 
@NT = laukik<200>
This is the fourth of the <218>a<219>karmas or  the  six  purificatory  exercises  for ç
cleansing the body prescribed in the works on Ha<219>hayoga. It consists ç
in moving the stomach and intestines with great force from one side ç
to the other. It destroys all diseases and increases digestive power. ç
(See Ghera<207><195>a Sa<221>hit<193> 1.52.)
@SPACE = 
@NT = laya
@N1 = (`dissolution')
@SPACE1 = 
@SPACE1 = 
Derived from the root `l<200>' (to dissolve, to disappear) the word ç
`laya' has been used in several senses.
When it refers to the dissolution of the created world (for e.g., ç
s<216><218><219>i, sthiti and laya), the term `pralaya' is more frequently ç
used. (See <MS>PRALAYA<D> for details.)
In the works on yoga, it refers to the sam<193>dhi state wherein the ç
mind iscompletely merged in the object of meditation.
In Advaita Ved<193>nta, it is considered as the first obstacle to ç
the realisation of <193>tman, the others being vik<218>epa (distraction), ç
ka<218><193>ya (failure to rest on the <193>tmandue to attachments) ç
and ras<193>sv<193>da (enjoying the taste of bliss in lower sam<193>dhi). ç
Here, laya is the relapsing of the mind into sleep instead of meditating ç
on the <193>tman.
In music it refers to the maintenance of the speed with which a song ç
is begun to be sung.
@SPACE1 = 
@NT = layayoga
@N1 = (`yoga of dissolution [of the mind in Brahman]')
@SPACE1 = 
Out of the several systems of yoga mentioned in the works on yoga, ç
Layayoga also is one.
@SPACE1 = 
Laya or dissolution of the individual consciousness is achieved when ç
prak<216>ti (Mother Nature, same as the Ku<207><195>alin<200>) is ç
taken up from the m<220>l<193>dh<193>racakra (the lowest plexus), ç
step by step, right up tothe sahasr<193>ra (the `thousand-petalled ç
lotus') where it is merged in Puru<218>a or Brahman. This is called ç
`Layayoga'.
According to some works on yoga like the Ma<207><195>alabr<193>hma<207>a ç
Upani<218>ad (5.1-5), Layayoga comprises nine steps: yama (restraint), ç
niyama (culture), sth<220>lakriy<193> (gross practices like the <193>sanas), ç
s<220>k<218>ma kriy<193> (subtle practices like pr<193><207><193>y<193>ma), ç
praty<193>h<193>ra (withdrawal of senses), dh<193>ra<207><193> (fixed ç
attention), dhy<193>na (meditation), layakriy<193> (act of dissolution ç
of the mind into Brahman) and sam<193>dhi or mah<193>laya (final dissolution ç
resulting in the losing of one's personality into that of Brahman).
Mok<218>a or liberation from transmigratory existence results from ç
this.
@NT = Lep<193>k<218>i
@N1 = ([village of] the blinded eye')
Lep<193>k<218>i is one of the 108 important <185>ivak<218>etras (holy ç
place dedicated to god <185>iva) mentioned in the Skandapur<193><207>a. ç
Its temple is said to have been established by the great sage Agastya ç
himself.
The present Lep<193>k<218>i is a small village which lies 14.5 kms. ç
(9 miles) east of Hindupur in the Ananthapur district of Andhra Pradesh. ç
The original temple might have been built in the 7th century <MS>A.<|>D.<D>
Its famous temple of V<200>rabhadra lies on a low rocky hill called ç
K<220>rma·il<193> because it is shaped like a k<220>rma or tortoise. ç
It was constructed by Vir<220>pa<207><207>a (the treasurer of Vijayanagara ç
empire) during the 16th century. Since he constructed the temple from ç
the State funds without the permission of the king, he was punished ç
by plucking out his eyes, which, he did, himself!
The temple campus has four shrines dedicated  to  V<200>rabhadra  (the  terrible ç
deity who destroyed Dak<218>a's sacrifice), P<193>pan<193>·e·vara-<185>iva, ç
<185>r<200> R<193>ma and Durg<193>.
There  are  very  good  sculptured images of Ananta·ayana (Vi<218><207>u), ç
Datt<193>-treya, Brahm<193>, the sage N<193>rada, Rambh<193> (a celestial ç
nymph) and Vir<220>pa<207><207>a (the builder).
The n<193><219>yama<207><195>apa is decorated with exquisitely sculptured ç
pillars having life size images of musicians and dancers.
The kalya<207>ama<207><195>apa is unfinished.
Bas-reliefs on the outer walls and mural paintings with vegetable ç
dyes on the inner walls are very attractive. They depict stories from ç
the epics and the pur<193><207>as.
At a distance of 180 metres (600 ft.) to the east of the temple, there ç
is a colossal Nandi, said to be the largest in India. It is carved ç
out of a monolithic rock. It is 6 metres (20 ft.) in height and 9 ç
metres (30 ft.) in length.
@NT = liberation
See <MS>MOK<186>A.<D>
@NT = Licchavis
The Licchavis, often mentioned in Buddhist works and even by Kau<219>ilya ç
(300 <MS>B.<|>C.<D>) in his Artha·<193>stra, were a powerful tribe ç
of k<218>attriyas belonging to the Vasi<218><219>ha gotra (lineage). ç
Their capital was at Vai·<193>li or Ves<193>li. They were one of the ç
partners in the Vajjian confederacy. Theirs was a republican form ç
of Government.
Though they were good in trade and commerce and hence quite prosperous, ç
they lived a hard and austere life. In course of time, luxury crept ç
into their life making them a soft nation.
Their civilisation was of a high standard and refinement. Candragupta, ç
the first, and Samudragupta (5th century <MS>A.<|>D.<D>) had married ç
Licchavi princesses.
The Licchavis had ruled Nepal also for some time.
@NT = Likhita
The dharmas<220>tra work of <185>a<209>kha- Likhita is considered ç
as very authoritative by the V<193>jasaneyins (followers of <185>ukla ç
Yajurveda).
As per the story in the Mah<193>bh<193>rata (<185><193>ntiparva ç
23.18-43) Likhita once went to the hermitage of his elder brother ç
<185>a<209>kha. Since <185>a<209>kha had gone out, Likhita had to ç
wait until he returned. During this time he saw some nice fruits hanging ç
from the trees in the garden, plucked a few and ate them. When <185>a<209>kha ç
returned and found what Likhita had done, he admonished him for this ç
act of his, as theft and advised him to go to the kingSudyumna to ç
receive appropriate punishment.
Though Sudyumna refused to give punishment†since Likhita was well-known ç
as a sage of great rectitude†he was obliged to do so due to Likhita's ç
insistence. As per the law, both the hands of Likhita were cut off. ç
When he arrived at <185>a<209>kha's hermitage again and reported to ç
him of having received the punishment, <185>a<209>kha advised him ç
to take bath in the nearby river. As soon as Likhita did so, he got ç
back both his hands, due to the mysterious power exercised by <185>a<209>kha.
Likhita was the co-author of the dharmas<220>tras, along with his ç
brother <185>a<209>kha.
See <MS><185>ANKHA-LIKHITA-DHARMAS<188>TRAS.<D>
@NT = l<200>l<193>m<220>rtis
@N1 = (`aspects of [<185>iva] in various forms')
Though <185>iva, the third aspect of the Hindu Trinity, is worshipped ç
only as a li<209>ga in the temples, twenty five forms of his are mentioned ç
in the iconographical works. These forms (in human shapes) areestablished ç
separately as decorative motifs, but, not worshipped.
Some of them are: Anugraham<220>rtis (bestowing  grace  upon  devotees  like ç
Nandi, R<193>va<207>a or Ca<207><195>e·a); Antakam<220>rtis (des-troying ç
the demons like Gaj<193>sura or Tripuras); N<216>ttam<220>rtis (in ç
the dancing pose like t<193><207><195>ava dance); Dak<218>i<207><193>m<220>rti ç
(in  the  teaching  pose  of  a  guru); Haryardham<220>rti (combined ç
form of Hari and Hara); Ardhan<193>r<200>·vara (combined form of <185>iva ç
and P<193>rvat<200>); Bhik<218><193><219>ana-m<220>rti (as a mendicant ç
with a begging bowl) and so on.
@NT = L<200>l<193>·uka
The long hymn <185>r<200>k<216><218><207>a-kar<207><193>m<216>ta, ç
is an extremely popular hymn extolling the doings and the greatness ç
of Lord K<216><218><207>a. Its author is L<200>l<193>·uka. Whether ç
it was his real name or the pen-name, is difficult to say. Some identify ç
him with the devotee Bilvama<209>gal.
Since <185>r<200>k<216><218><207>a Caitanya (<MS>A.<|>D.<D> 1485- 1533) ç
is said to have brought a copy of this book from South India, he must ç
have lived before the 15th century.
He was a disciple of Somagiri and might have got his general education ç
from <185>ikhipi<210>cha. Though a <185>aiva by birth, K<216><218><207>a ç
was his chosen deity. He probably belonged to the °ndhrade·a (the ç
present Andhra Pradesh).
Some popular stories picture him as having become an ascetic after ç
being admonished by a harlot, Cint<193>ma<207>i by name, to whom he ç
was terribly attached.
@NT = li<209>ga
@N1 = (`sign')
This word is commonly used to indicate the famous emblem of <185>iva. ç
See <MS><185>IVALI<177>GA<D> for details.
How j<210><193>na or empirical knowledge is acquired, is an important ç
topic discussed in the Indian philosophical systems. These means of ç
knowledge are called `pram<193><207>as'. Out of the several such pram<193><207>as ç
normally accepted by these systems, anum<193>na or inference is an ç
important and universally accepted one. The term `li<209>ga' is used ç
as a part of this anum<193>na.
A statement of anum<193>na generally has three parts: s<193>dhya (major ç
term); pak<218>a (minor term); s<193>dhana or li<209>ga or hetu (middle ç
term).
If smoke is seen on a yonder hill one can infer from this li<209>ga ç
or sign that there is fire there.
See also <MS>ANUM°NA<D> and <MS>PRAM°ØAS.<D>
@NT = li<209>gadh<193>ra<207>a
@N1 = (`wearing the <185>ivali<209>ga [on the body]')
V<200>ra·aivas are also called `Li<209>g<193>yatas' since they wear ç
the <185>ivali<209>ga (a stone emblem of <185>iva encased in a small ç
casket) on their body.
Li<209>gadh<193>ra<207>a is a part of the cere-monies connected with ç
d<200>k<218><193> or initiation. The guru worships the li<209>ga first ç
and then ties it round the neck of the initiate.
See also <MS><185>AIVISM<D> and <MS>V®RA<185>AIVAS.<D>
@NT = Li<209>gapur<193><207>a
@SPACE = 
@SPACE = 
The  pur<193><207>as,  generally  grouped under the all-comprehensive ç
term `sm<216>tis,' contain a lot of material useful to the common ç
masses, to educate them both in the spiritual and in the secular fields.
The Li<209>gapur<193><207>a, considered as an important work of ç
the <185>aiva cults, has been classified among the Mah<193>pur<193><207>as ç
or the major pur<193><207>as. It might have been composed between ç
<MS>A.<|>D.<D> 600 and 1000. The total number of verses as per the ç
different editions varies from 6000 to 11,000. The book, as available ç
now, is in two parts and has about 9000 verses, the number of chapters ç
being 108 in the first part and 55 in the second.
A sanskrit commentary by Ga<207>e·a N<193>tu (early part of the 19th ç
century), <185>ivato<218>i<207><200> by name, has been printed.
The contents are variegated. See under <MS>PUR°ØAS.
@SPACE = 
@NT = li<209>ga·ar<200>ra
@SPACE = 
The j<200>v<193>tman or the bound soul has three ·ar<200>ras or bodies. ç
They are: sth<220>la-·ar<200>ra (gross body); s<220>k<218>ma or li<209>ga ç
·ar<200>ra (subtle body) and k<193>ra<207>a·ar<200>ra (causal body).
The s<220>k<218>ma or the li<209>ga ·ar<200>ra comprises sixteen parts ç
and is directly responsible for punarjanma or transmi-gration.
The sixteen parts are: the five j<210><193>nendriyas (organs of knowledge ç
like the eyes); the five karmendriyas (organs of action like the hands); ç
the five pr<193><207>as (vital airs like pr<193><207>a and ap<193>na) ç
and the mind (including the buddhi or the intellect).
@NT = li<209>gasthala
@N1 = (`<185>iva as infinite Brahman')
@SPACE = 
In V<200>ra·aivism (the philosophy and religion of the Li<209>g<193>yata ç
sect), <185>iva (Brahman, God) is called `Sthala', which means infinite ç
space or the origin of creation and dissolution of the universe.
When <185>iva divides himself into two aspects†li<209>ga and a<209>ga†the ç
former is known as `li<209>gasthala'. It is actually he himself.
@NID = <+><+><+>See <MS><185>AIVISM<D> and <MS><186>A<187>STHALA-SIDDH°NTA.
@SPACE = 
@NT = Li<209>g<193>yata Sect
@SPACE = 
See <MS>V®RA<185>AIVISM<D> under <MS><185>AIVISM.<D>
@SPACE = 
@NT = lobha
@N1 = (`greed')
@SPACE = 
All religions in general and Hinduism in particular, stress the importance ç
of cultivating some basic ethical principles. One of these is eschewing ç
greed.
`Lobha,'  translated  as  `greed',  is excessive desire, especially ç
the desire to appropriate to oneself what belongs to others; that ç
too, against the principles of dharma.
The ®·<193>v<193>sya Upani<218>ad in its very first verse advises ç
us not to covet anyone's wealth and possessions. The Bhagavadg<200>t<193> ç
(16.21) calls it as a gateway to hell and exhorts the aspirant to ç
give it up.
Lobha is classed among the ari<218>a<195>-vargas or six enemies of ç
man, the others being k<193>ma (lust), krodha (anger), moha (infatuation), ç
mada (intoxication) and m<193>tsarya (jealousy).
@SPACE = 
@NT = logic
@SPACE = 
See <MS>NY°YADAR<185>ANA.
@NT = loka
@N1 = (`world')
@SPACE = 
See <MS>BHUVANA.<D>
This word is also used in a more general sense, to indicate birth ç
in a body capable of experiencing happiness and misery. It can also ç
mean people in general.
Apart from the three worlds or the seven worlds or the fourteen worlds, ç
the scriptures mention other types of worlds also. See <MIS>CH°NDOGYA ç
UPANI<186>AD<D> (8.2).
@SPACE = 
@NT = Lok<193>c<193>rya
See <MS>PI<170><170>AI LOK°C°RYA.
@SPACE = 
@NT = Lok<193>loka
@N1 = (`bright and dark')
The pur<193><207>as like Bh<193>gavatam (5.20) describe a mythical ç
mountain called Lok<193>loka or Cakrav<193>la situated at the southernmost ç
tip of the earth and bordering the sea. It is called Cakrav<193>la ç
since it is circular in shape and is like hair to mother earth (cakra ç
= circular; v<193>la = hair). Since one side of it is always bright ç
(loka = bright) and the opposite side always dark (aloka = dark), ç
it is also called `Lok<193>loka'. The sun always rises and sets within ç
its circular barrier. The region beyond it is in perpetual darkness. ç
This however is no obstacle to the spirits of the virtuous persons, ç
who go to higher worlds.
@SPACE = 
@NT = lokap<193>las
@N1 = (`protectos of worlds')
See <MS>DIKP°LAKAS.
@SPACE1 = 
@NT = lokasa<209>graha
@N1 = (`maintaining order in the society')
This is  a  word peculiar to  the Bhagavadg<200>t<193> (3.20, ç
25).
Among the various counter-arguments that <185>r<200> K<216><218><207>a ç
gives to Arjuna to make him fight, lokasa<209>graha is also one. It ç
is interpreted as keeping the people within the orbit of dharma and ç
not allowing them to transgress it. This has to be achieved by the ç
leaders of the society even if they have transcended it by attaining ç
mukti or liberation by conforming themselves to the path of dharma ç
and thus induce or inspire the common people also to do the same.
In this context, if Arjuna as a k<218>attriya and a prince does not ç
discharge his duty (to fight the evil-doers and destroy them), ordinary ç
people in the society too, will do the same and abandon their duties ç
and responsibilities. This will ultimately upset the whole social ç
balance.
@NT = Lok<193>yata
See <MS>C°RV°KADAR<185>ANA.<D>
@NT = Lomahar<218>a<207>a
@N1 = (`one who raises the hair [of the listeners]')
Lomahar<218>a<207>a (also spelt as Romahar<218>a<207>a) is a familiar ç
figure that we comeacross in the pur<193><207>as as the chief narrator, ç
especially to the <216><218>is engaged in a Sattray<193>ga and mostly ç
in Naimi<218><193>ra<207>ya, the Naimi<218>a forest (identified with ç
the modern Nimsar in Uttar Pradesh). He was also known as S<220>tapur<193><207>ika. ç
He was a disciple of Vedavy<193>sa. His son was Ugra·ravas who later ç
on took his father's place as the chief narrator of pur<193><207>as.
He had six disciples through whom the pur<193><207>as gradually took ç
the present shape. They were: Sumati, Agnivarcas, Mitr<193>yus, <185><193><221>sap<193>yana, ç
Ak<216>tavar<207>a and S<193>var<207>i.
@NT = Lop<193>mudr<193>
Lop<193>mudr<193> was the wife of the famous sage Agastya. (See <MS>AGASTYA<D> ç
for details.) She was the daughter of the king of the Vidarbha country.
According to one story, Agastya oncesaw his forefathers in a miserable ç
condition. On enquiry, they advised him to marry and beget sons who ç
would deliverthem from this misery. He then approached the king of ç
Vidarbha and requested him to give his daughter Lop<193>mudr<193> ç
in marriage. Though the king was hesitant, Lop<193>mudr<193> herself ç
came forward accepting the proposal.
The two were married at the place called Mah<193>sindhut<200>rtha.
D<216><195>hasyu (or Idhmav<193>ha) was their son.
She was also known as Satyavat<200>. She is sometimes identified with ç
K<193>ver<200>, daughter of the sage Kavera, who became the river ç
K<193>ver<200>.
@END = 
