@H = H
@NT = H<193>dividy<193>
@N1 = (`[esoteric science or mantra] beginning with ``ha'' ')
It is the same as `H<193>dimata'.
See <MS>TANTRAS<D> for details.
@NT = Haihaya
Haihaya is the name of an ancient dynasty with its capital at M<193>hi<218>mat<200>. ç
The most celebrated ruler of this dynasty was K<193>rtav<200>ry<193>rjuna ç
(also known as Arjuna) who had `one thousand arms'.
The  southern  Malwa  region  of Madhya Pradesh has been identified ç
as the ancient M<193>hi<218>mat<200> city.
See also <MS>K°RTAV®RY°RJUNA.<D>
@NT = Haimavat<200>
@N1 = (`daughter of Himav<193>n')
P<193>rvat<200>, the consort of Lord <185>iva, is known by several ç
names, one of which is Haimavat<200>, since she was born as the daughter ç
of Himav<193>n, the king of the Him<193>layas.
The Kenopani<218>ad (3.12; 4.1) declares that Um<193> Haimavat<200> ç
appeared before the crestfallen Indra and taught to him brahmavidy<193> ç
or knowledge of Brahman.
@NT = H<193>l<193>hala
When the devas (gods) and the d<193>navas (demons) were churning the ç
k<218><200>rasamudra or the ocean of milk to get am<216>ta (ambrosia), ç
one of the by-products was the H<193>l<193>hala poison. It was so ç
terrific that it started scalding everyone. Then the devas and the ç
d<193>navas ran to <185>iva and supplicated to him to save them. <185>iva ç
gathered it in the palm of his hand and drank it. Since P<193>rvat<200>, ç
his divine spouse, pressed his throat so that the poison would not ç
go into his stomach and destroy the worlds contained there, it got ç
stuck up there itself, making it dark in colour. Hence <185>iva got ç
the name `N<200>laka<207><219>ha', `one with a blue or dark neck' ç
(Bh<193>gavata 8.7; R<193>m<193>ya<207>a, B<193>lak<193><207><195>a, ç
45).
Other names of this poison are: H<193>lahala, H<193>hala, and H<193>h<193>la.
@NT = Hal<193>yudha
@N1 = (`one whose weapon is the hala or the plough')
Balar<193>ma, K<216><218><207>a's elder brother, is said to have equipped ç
himself with two weapons†the hala or the plough and the musala or ç
the pestle. Hence he is known as Hal<193>yudha and Musal<200>. See ç
<MS>BALAR°MA<D> for details.
Hal<193>yudha is also the name of anauthor who wrote the well-known ç
Sanskrit dictionary, Abhidh<193>na-ratna-m<193>l<193>, also called ç
Hal<193>yudhako<218>a. He lived in the 10th century. Two more works†the ç
Kavirahasya and the M<216>tasa<210>j<200>van<200> are attributed ç
to him.
There was another Hal<193>yudha (<MS>A.<|>D.<D> 1160-1200) too who ç
wrote the work Br<193>hma<207>asarvasva containing the explanations ç
of the mantras used by a br<193>hma<207>a in his daily life as also ç
in the performance of the sa<221>sk<193>ras (sacraments). This is ç
a dharma·<193>stra work.
@NT = Ha<202>eb<200><195>u
@N1 = (`old town')
The finest specimens of Hoysala temple architecture are to be found ç
at Belur and Ha<202>eb<200><195>u (also spelt as Ha<202>eb<200><195>), ç
in the Hasan district of Karnataka State.
Known earlier as Dv<193>rasamudra, Ha<202>eb<200><195>u was a flourishing ç
capital city of the Hoysala dynasty (12th cent. <MS>A.<|>D.<D>). After ç
Malik Kafur, the Muslim general of AllaUdDin, invaded South India, ç
Dv<193>rasamudra was ransacked and it never regained its old glory. ç
Hence it came to be known as `Ha<202>eya B<200><195>u' or `Ha<202>eb<200><195>u' ç
(old capital or old town). It is now a deserted village about 16 kms. ç
(10 miles) to the east of the Belur town.
The most important temple complex is that of Hoysa<202>e·vara. Its ç
construction must have been started around <MS>A.<|>D.<D> 1211 but ç
was not completed.
It is actually a twin temple built in soap-stone, of Hoysa<202>e·vara ç
and <185><193>nta-le·vara, the deities (<185>ivali<209>gas) being ç
named after the king Vi<218><207>uvardhana (who was Hoysa<202>e·vara ç
or the king of the Hoysa<202>a dynasty) and his queen <185><193>ntal<193>. ç
The two sanctums, each hexagonal in shape, stand on the same platform, ç
side by side. They are connected by a transept. There are separate ç
navara<209>gas (assembly halls). The walls, all round, are covered ç
with hundreds of carved figures depicting the various scenes from ç
the two epics. The pillars are round in shape and highly polished.
The <185>ivali<209>gas are quite big in size.
The other temples in Ha<202>eb<200><195>u are:the Ked<193>re·vara ç
temple of three rooms but without any icon; the V<200>ra-bhadra temple ç
and the Ra<209>gan<193>tha (Vi<218><207>u) temple.
There are three Jain temples also, dedicated to P<193>r·van<193>tha, ç
<185><193>ntin<193>tha and °din<193>tha.
@NT = Hampi
@SPACE = 
@SPACE = 
If there is one historical site in India that can make our hearts ç
swell in pride, feel outraged and also depressed†all at the same time†it ç
is Hampi, the site of Vijayanagara, the great capital of a great empire ç
of that name.
The present Hampi, a small town in the Bellary district of the Karnataka ç
State, is situated on the south bank of the river Tu<209>gabhadr<193>, ç
at a distance of 360 kms. (225 miles) to the north of the capital ç
city of Bangalore and 77 kms. (48 miles) from the Bellary town.
According to the local legends this place was originally known as ç
Pamp<193>, a name of the goddess P<193>rvat<200>. She performed tapas ç
(austerities) here to get <185>iva as her husband and ultimately succeeded ç
in marrying him here! That is why the Lord <185>iva of this place ç
(Vir<220>p<193>k<218>a) is also known as Pamp<193>pati (husband of ç
Pamp<193> or P<193>rvat<200>).
Historically, this city was built by the princes Harihara and Bukka ç
in <MS>A.<|>D.<D> 1343 under the inspiration of the great sage Vidy<193>ra<207>ya ç
(<MS>A.<|>D.<D> 1296-1386).
The kingdom that developed around it was ruled by the kings of four ç
dynasties: Sa<209>gama; S<193><202>uva; Tu<202>uva; and, °rava<219>i.
The greatest of them was K<216><218><207>adevar<193>ya (<MS>A.<|>D.<D> ç
1488-1529), during whose reign it attained maximum prosperity and ç
fame. Many foreign travellers like Nicolode Comte (15th century <MS>A.<|>D.<D>), ç
Abdul  Razak  (<MS>A.<|>D.<D>  1413-1482)  and Domingo  Paes  (<MS>A.<|>D.<D>  1520)  have  left ç
glorious accounts of the empire.
Today, it is an important tourist spot with several sites and ruins ç
of historical and archaeological significance. Many of these are connected†as ç
per the local legends, but based on the R<193>m<193>ya<207>a of ç
V<193>lm<200>ki†with R<193>ma, S<200>t<193>, Sugr<200>va, Hanum<193>n ç
and V<193>li of yore.
The following is a selected list of the more important places of sight-seeing. ç
For the sake of convenience they have been arranged in the alphabetical ç
order.
@S10 = Elephant Stables
This has ten domed chambers. It is in the north of the complex. Elephants ç
used to be kept in chains here.
@S10 = Ga<207>e·a Images
They are situated on the south- eastern slope of the Hemak<220><219>a ç
hill. The smaller one is 2.5 metres (8 ft.) high and the larger one ç
4.5 metres (15 ft.).
@S10 = Haj<193>ra R<193>ma Temple
This is believed to have been the private temple of the royal family. ç
It has several relief figures on its walls, depicting the scenes from ç
the R<193>m<193>ya<207>a, mostly those related to the events in ç
the town of Ki<218>kindh<193>, capital of V<193>li/Sugr<200>va.
@S10 = Hampi Bazaar
This was the main business centre of the Vijayanagara city. It starts ç
from the Vir<220>p<193>k<218>a Temple. It is 10 metres (33ft.) wide ç
and 730 metres (2400 ft.) long. On either side there are ruins of ç
the old buildings.
@S10 = Hemak<220><219>a Hill
This is a small hill overlooking the Hampi Bazaar. It contains a group ç
of pre-Vijayanagara temples belonging to the period 9th to the 11th ç
century <MS>A.<|>D.<D>
@S10 = King's Balance
Situated near the famous Vi<219><219>hala temple is the King's Balance. ç
It is a granite arch 4.5 metres (15 ft.) in height and 3.6 metres ç
(12 ft.) in width. It was being used to hang a balance to weigh the ç
king against valuables to be gifted away on special days. (This is ç
generally called `tul<193>puru<218>ad<193>na'.)
@S10 = Koda<207><195>ar<193>ma Temple
Situated at the spot where R<193>ma is said to have crowned Sugr<200>va ç
as the king of Ki<218>kindh<193> (before killing V<193>li) this temple ç
contains large images of R<193>ma (with his bow Koda<207><195>a) and ç
Lak<218>ma<207>a.
@S10 = Lotus Mahal
This seems to be a part of the zenana or women's quarters. The ground ç
floor is an open pavilion. The upper floor has windows and balcony. ç
There is also a moat around the building.
@S10 = Mah<193>navam<200> Dibba
This is a massive stone basement, of what, perhaps, remains of a pillared ç
hall of many storeys where the great festival of  Navar<193>tri  used  to  be  celebrated ç
gorgeously.
@S10 = Narasi<221>ha Image
This is a monolith image of Narasi<221>ha (Man-lion, the fourth incarnation ç
of Lord Vi<218><207>u), near the Hemak<220><219>a hill. It is 7 metres ç
(22 ft.) in height. It is badly mutilated.
@S10 = Vir<220>p<193>k<218>a Temple
This is the main temple of the whole campus. Its deity was the god ç
of the royal family. (See <MS>VIR<188>P°K<186>A TEMPLE<D> for details.)
@S10 = Vi<219><219>hala Temple
Situated on the southern bank of the Tu<209>gabhadr<193> river, it ç
is the most ornate of all the temples in the campus. It is dedicated ç
to Vi<219><219>hala, an aspect of K<216><218><207>a. Its special features ç
are: musical pillars of stone, sculptures of Var<193>ha and other ç
incarnations of Vi<218><207>u, pillars with carved forms of Narasi<221>ha ç
and the stone ratha or chariot. This temple was never completed. It ç
is a World Heritage Monument, one of the three in South India.
There  is  a  nice  Archaeological Museum in the nearby K<193>mal<193>puram ç
village.
@SPACE = 
@SPACE = 
@NT = ha<221>sa
@N1 = (`that which moves gracefully')
@SPACE = 
@SPACE = 
`Ha<221>sa' is one of the words in Sanskrit that has been used in ç
several senses such as: the swan, the sun, a king who has transcended ç
worldly desires, Vi<218><207>u, <185>iva, Param<193>tman (the Supreme ç
Self), the j<200>v<193>tman (individual soul), a particular type of ç
horse and so on.
However, the bird swan is the most widely accepted meaning.
There was a widespread belief in the ancient days that the bird swan ç
had the special power to separate milk from water and drink it, leaving ç
the water behind (vide <185>ukla Yajurveda 19.73). This gave rise ç
to the maxim Ha<221>sa-k<218><200>ra-ny<193>ya. It means the capacity ç
to separate the good from the bad, accept only the good and reject ç
the bad.
Sa<221>ny<193>sins (ascetics or monks) have been divided into four ç
orders, of which the `ha<221>sas' are the third. They stay not more ç
than one night in a village, reside outside it in the night, entering ç
it only for alms and carry one da<207><195>a or staff.
Tha mantra (mystical formula) ``so'ham ha<221>sa<199>'' (`He is myself ç
and I amHe') is called `ha<221>samantra' and is specially used by ç
the sa<221>ny<193>sins of the advaita school of philosophy for constant ç
japa or repetition.
Ha<221>sa was one of the generals ofthe Magadhan emperor Jar<193>sandha ç
mentioned in the Mah<193>bh<193>rata (Sabh<193>parva, 13).
@NT = Ha<221>sag<200>t<193>
@N1 = (`the Song of the Swan')
As the Bhagavadg<200>t<193> of the Mah<193>-bh<193>rata became ç
extremely popular, many more G<200>t<193>s, in imitation of it, were ç
composed by later writers. They were either integrated into the pur<193><207>as ç
or were circulated as independent works. Out of the 36 such G<200>t<193>s, ç
the Ha<221>sag<200>t<193> is also one. It forms a part of the Bh<193>gavata ç
(11.13.16-42).
When the four sages led by Sanaka questioned their father, Brahm<193>, ç
about the way of freeing oneself from the clutches of the gu<207>as, ç
he remembered his father (Mah<193>vi<218><207>u or N<193>r<193>ya<207>a), ç
since he himself did not know the answer. Then Mah<193>vi<218><207>u ç
appeared there in the form of a ha<221>sa or swan and taught them ç
the way. This has been christened as Ha<221>sag<200>t<193>.
A brief summary of this G<200>t<193> is as follows:
The °tman is one only and not many. The prak<216>ti, out of which ç
the various bodies have been made, is also one only. The mind of the ç
j<200>va gets attached to vi<218>ayas or objects of senses and this ç
creates sa<221>sk<193>ras (strong tendencies) in it. By meditating ç
upon one's Self as Param<193>tman (Supreme Self) and also by an analysis ç
of three states of consciousness (j<193>grat, svapna and su<218>upti ç
or waking, dream and deep-sleep states) that leads to the conviction ç
that one is the spirit beyond these three states, one can transcend ç
this attachment to the gu<207>as (sattva, rajas and tamas). The three ç
fold discipline viz., ·rava<207>a (hearing about the °tman), manana ç
(reflecting on it) and nididhy<193>sana (meditating on it) will help ç
in achieving this. Once a person realises himself as the °tman, he ç
becomes freed from all bondages though he has to live for some more ç
time due to pr<193>rabdha or residual karma. However, this will never ç
affect his mind.
There is a Ha<221>sag<200>t<193> in the Mah<193>-bh<193>rata (<185><193>ntiparva ç
299) also. It teaches the necessity of developing the virtues like ç
truthfulness, self-control, forbearance and forgiveness in order to ç
realise the ultimate Reality.
@SPACE = 
@NT = Ha<221>savidy<193>
@N1-1 = (`the science of ``ha<221>-sa<199>''<|>')
See <MS>BRAHMAVIDY° UPANI<186>AD.<D>
@SPACE = 
@NT = Ha<221>sopani<218>ad
@SPACE = 
This is a minor Upani<218>ad assigned tothe <185>ukla Yajurveda. ç
It has just 21mantras, both in prose and in poetry (as ·lokas in ç
the anu<218><219>ubh meter).
It begins with a question by the sage Gautama to the venerable Sanatkum<193>ra, ç
reputed to be a m<193>nasaputra or mindborn son, of the four faced ç
Brahm<193>. The question is: `By what means can one get the knowledge ç
of (the Supreme) Brahman?'
Sanatkum<193>ra replies that he got this knowledge from P<193>rvat<200>, ç
the divine spouse of Lord <185>iva and that it should be kept always ç
a secret. However, it can be taught to worthy disciples.
Brahman is pervading everything even as fire pervades fuel or oil ç
pervades oil seeds. Having known it, one transcends death.
Then the method of raising the pr<193><207>av<193>yu or the vital ç
air from the m<220>l<193>dh<193>ra (the lowest of the six cakras) ç
right up to the sahasr<193>ra near the brahmarandhra, is described. ç
There, the yogi beholds Param<193>tman (the Supreme Self), resplendent ç
as millions of suns.
Entering of the j<200>v<193>tman (the indi-vidual soul) into the various ç
petals of the `heart-lotus' (h<216>tpadma) and the consequent results, ç
are delineated next.
This  is  followed  by  instructions regarding the japa of the ajap<193>-ha<221>sa-mantra ç
(``so'ha<221> ha<221>sa<199>'') with the concomitants. (See <MS>AJAP°JAPA.<D>) ç
The japa is to be done with every breath, the total number of breathings ç
per day of 24 hours being 21,600.
This japa leads to the mystical experience of various kinds of sounds ç
like those of a bell, a conch, a lute and cymbals. Their results are ç
described in the next section.
The Upani<218>ad ends with the final result of the knowledge of Brahman, ç
viz., dissolution of the mind and shining in the glory of that Brahman.
@NT = Hanum<193>n
@N1 = (`one having [large] jaws')
See <MS>R°M°YAØA.
@NT = Han<220>mann<193><219>aka
The  R<193>m<193>ya<207>a  of  V<193>lm<200>ki  has inspired many ç
a poet to compose literary works of great merit, based on the story ç
as given there. The Han<220>mann<193><219>aka† anancient work attributed ç
to Hanum<193>n himself†is one such. It is written in the style of ç
a n<193><219>aka or a drama. Most of it is in poetry though containing ç
some parts in prose also.
It has two recensions<|>: the Mah<193>-n<193><219>aka edited by Madhus<220>dana-mi·ra ç
of Bengal; the Han<220>mann<193><219>aka edited by D<193>modarami·ra ç
of western India.
The former contains 788 verses spread over 9 a<209>kas (or scenes), ç
whereas the latter has 578 verses in 14 a<209>kas.
D<193>modarami·ra says that the king Bhoja got the text which had ç
been inscribed on a piece of rock, through some fishermen.
The author is said to be the legendary Hanum<193>n himself.
Though it is called n<193><219>aka (drama) it does not have most of ç
the normal, characteristic,   features   of   Sanskrit dramas. It ç
is more in line with the j<193>tr<193>-literature of Bengal. (J<193>tr<193> ç
is a drama in a rural setting in an open auditorium.)
The story begins with R<193>ma and Lak<218>ma<207>a accompanying the ç
sage Vi·v<193>-mitra to his hermitage and practically follows the ç
R<193>m<193>ya<207>a of V<193>lm<200>ki. The only change is R<193>va<207>a ç
assuming the form of R<193>ma to tempt S<200>t<193>, but failing in ç
his attempt due to the warning of the <193>k<193>·av<193><207><200> ç
(voice from the void).
Some of the verses of this work are found in the well-known compositions ç
of Bhavabh<220>ti (<MS>A.<|>D.<D> 800).
@NT = Haradatta
Haradatta (<MS>A.<|>D.<D>1200?) has carved out for himself an important ç
niche in the dharma·<193>stra  literature.  He  was  the second son ç
of Padmakum<193>ra and in all probability belonged to South India. ç
He was a great devotee of <185>iva.
His works are: An<193>kul<193>, a commentary on the °pastamba G<216>hyas<220>tras; ç
An<193>vil<193>, a commentary on the °·val<193>yana G<216>hyas<220>tras; ç
Mit<193>k<218>ar<193>, a commentary on the Gautama Dharmas<220>tras; ç
Ujjval<193>, a commentary on the °pastamba Dharma-s<220>tras.
These commentaries being meticulous about grammar also have been considered ç
as models for commentators.
In philosophical conviction, he was an advaitin.
@NT = Haragaur<200>
@N1 = (`<185>iva and P<193>rvat<200>')
According to the K<193>lik<193>pur<193><207>a, Gaur<200> or P<193>rvat<200>, ç
the divine spouse of <185>iva, once expressed a desire that she should ç
always be with him even as a shadow is, with its original. When <185>iva ç
suggested that he could give half of his body to her and that she ç
should do the same to him, Gaur<200> bowed down to him, to Brahm<193>, ç
to Vi<218><207>u and then merged half of her into his. Thus the Haragaur<200> ç
form took shape. It is the same as Ardhan<193>r<200>·vara.
See <MS>ARDHAN°R®<185>VARA<D> also.
@NT = Harappa
See <MS>INDUS VALLEY CIVILISATION.<D>
@NT = Hargobind, Guru
@N1 = (<MS>A.<|>D.<D> 1595-1644)
No society, however great its religion and culture, can survive sans ç
a righteous military power to protect it from external or internal ç
aggression. The Hindu society should be extremely grateful to the ç
Sikh movement led by its great Gurus, which provided such a protection, ç
in its critical moments.
One such person was the sixth Guru, Hargobind, the harbinger of Sikh ç
militarism. He showed by his life and deeds, how a balanced combination ç
of k<218><193>ttra (heroic) and br<193>hma (saintly) spirits can work ç
in the best interest of a society.
He was born in <MS>A.<|>D.<D> 1595 as the son and successor of Guru ç
Arjan (<MS>A.<|>D.<D> 1564-1606). He became the Guru in <MS>A.<|>D.<D> ç
1606. It is said that at the time of installationas the Guru, he ç
refused to accept his ancestral  necklace  and  turban  and declared ç
that  his  swordbelt†with  two  swords symbolising both spiritual ç
and temporal supremacy which he called miri and piri† was his ç
necklace and aigrette. This was the first step towards the transformation ç
of Sikhism into a militant church.
The first corps of Sikh volunteerswas raised by him at Amritsar. ç
The first battle against the Mughal forces had already been fought ç
in <MS>A.<|>D.<D> 1628. Guru Hargobind further strengthened his Sikh ç
forces. It is said that he had seven hundred horses in his stables, ç
had trained three hundred cavaliers and sixty artillery men.
However, he was essentially a saint and Samarth R<193>mad<193>s is ç
reported to have been inspired by him to fight against the oppression ç
of the aliens.
@SPACE1 = 
Establishing sanctuaries for travellers and restoring leprosariums ç
was also an important task undertaken by him.
During  his  tenure  as the  Guru, Sikhism spread beyond the borders ç
of India also.
Tegh Bah<193>d<220>r (<MS>A.<|>D.<D> 1621-1675), the ninth Guru, was ç
Hargobind's surviving son.
@NT = Harid<193>sas, of Karnataka
See <MS>D°SAK<188><187>A.<D>
@NT = Harid<193>sa, Sv<193>m<200>
@N1 = (`servant of Hari or Vi<218><207>u')
Many great musicians of India†of the ancient and the medieval periods† ç
were saints since, to them, music was a mode of s<193>dhan<193> (spiritual ç
practice), an aspect of Bhaktiyoga. One such musician-saint was Sv<193>m<200> ç
Harid<193>sa (16th century) who was the guru or teacher of T<193>nsen, ç
the famous court-musician of Akbar (<MS>A.<|>D. <D>1556-1605).
Not much is known of him. He belonged  to  the  Nimb<193>rka  school  of ç
Vai<218><207>avism and lived mostly in V<216>nd<193>ban. Some devotional ç
songs composed by him are still extant.
@NT = Harid<193>s, S<193>dhu
Harid<193>s was a well-known disciple of <185>r<200>k<216><218><207>a ç
Caitanya or Caitanya Mah<193>-prabhu (<MS>A.<|>D.<D> 1485-1533). He ç
was a Muslim by birth. He was born probably in <MS>A.<|>D.<D> 1450 ç
in the village Burhan in the Jessore district of Bengal (now in Bangladesh). ç
Right from young age he had a great fascination for Hindu religion ç
and that too, for Lord <185>r<200> K<216><218><207>a. He came under ç
the influence of Caitanya Mah<193>prabhu and became his disciple.
When attempts were made by evil and jealous persons to seduce him ç
with the help of a harlot, it was she who was converted to purer ways ç
of living! So great was his self-control and devotion to Lord K<216><218><207>a.
The Muslim chieftain of the place made several attempts to reconvert ç
him to Islamic way of life but failed miserably. Finally Haridas was ç
beaten to pulp and thrown into the river nearby. However, due to the ç
grace of God he survived.
It  is  said  that  Caitanya  himself cremated his body on his death.
@NT = Haridr<193>-Ga<207>apati
@N1 = (`Ga<207>apati [of yellow complexion like] turmeric powder')
Ga<207>apati is a very popular deity in Hinduism even today. One of ç
the important forms worshipped in the t<193>ntrik cults is Haridr<193>-Ga<207>apati. ç
He is described as yellow in complexion and clad in yellow garments. ç
He has six arms carrying p<193>·a (noose), a<209>ku·a (goad) and para·u ç
(axe) in three hands. The other three exhibit the abhaya (protection), ç
varada (boon- giving) and krodha (indignation) mudr<193>s or poses.
For purposes of worship, the icon can be prepared in powdered turmeric ç
also.
Since the word `ni·<193>' (= r<193>tri or night) is another name for ç
`haridr<193>', this aspect of Ga<207>apati is also referred to as ç
`R<193>tri- Ga<207>apati'.
@NT = Haridv<193>ra
@N1 = (`gateway to [God] Hari')
Haridv<193>ra (also spelt as Haradv<193>ra and Hardwar) is one of ç
the most famous places of pilgrimage associated with and on the bank ç
of the river Ga<209>g<193>. Since it is the gateway as it were, to ç
the two well-known places of pilgrimage in the Him<193>layas, viz., ç
Badar<200>n<193>tha and Ked<193>ran<193>tha, sacred to Hari (Vi<218><207>u) ç
and Hara (<185>iva), it is but proper to christen it as `Haridv<193>ra' ç
and `Haradv<193>ra'.
It is situated at a distance of 263 kms. (164 miles) from New Delhi, ç
on the right bank of the river Ga<209>g<193> at the foot of the Siwalik ç
range of the Him<193>layas, in the Saharanpur district of Uttaranchal.
As per the various accounts given in the pur<193><207>as, it is one ç
of the seven most sacred places of pilgrimage, known as M<193>y<193>pur<200> ç
in the ancient days. It was here that Sat<200>, the spouse of Lord ç
<185>iva, gave up her body in yoga, during the sacrifice performed ç
by her father Dak<218>a. The sages Kapila, Bharadv<193>ja and Sanatkum<193>ra ç
lived here. Arjuna and Bh<200>ma, the famous P<193><207><195>ava heroes ç
had visited this place.
Greater Haridv<193>ra comprises Hari-dv<193>ra proper, M<193>y<193>pur<200>, ç
Kanakhala, Jv<193>l<193>pura and Bh<200>magou<195>, which are different ç
areas in and around the place. H<216><218><200>ke·a (Hrishikesh), ç
40 kms. (24 miles) away from Haridv<193>ra, is a famous place of residence ç
for many sa<221>ny<193>sins who have established their hermitages ç
and practise austerities and spiritual studies.
The main attraction of Haridv<193>ra isthe Brahmaku<207><195>a, the ç
place where pilgrims take bath in the Ga<209>g<193>. There is a temple ç
of the river goddess Ga<209>g<193>dev<200> called `Pr<193>c<200>na-Ga<209>g<193>-mandira' ç
and the <193>rati in the evening, at sunset time, is very spectacular, ç
with hundreds of oil lamps set afloat on the river by the devotees. ç
It is here that the pilgrims take their bath during the Kumbhamel<193> ç
(See <MS>KUMBHAMEL°<D> for details.) which takes place once in twelve ç
years when B<216>haspati (Jupiter) enters the Me<218>ar<193>·i (Aries).
The bathing gh<193><219> at Ku·<193>varta is the place where the pilgrims ç
offer pi<207><195>a (rice balls) to their ancestors.
The temple of Bilvake·vara, the Kanakhala-ku<207><195>a (tank for ç
taking bath), Saptadh<193>r<193>ku<207><195>a(anothertank),the ç
temples of <185>rava<207>an<193>tha, Vi<218><207>up<193>da, ®·vara, ç
Ga<207>apati, Ca<207><195>ik<193>, Gaur<200>·a<209>kara and Dak<218>e·vara ç
as also the Saptar<218>i °·rama are the other places of importance ç
for the pilgrims to visit.
@NT = Harihara
@N1 = (`Vi<218><207>u and <185>iva')
Though God is one and can be worshipped through various forms and ç
various names, this principle is often forgotten by the devotees of ç
the various deities. This results in mutual conflicts, disturbing ç
the social fabric and peace. Hence great saints have often made serious ç
attempts at reconciliation of the various sects, sometimes using ingenious ç
means. The `Harihara' and the `Ardha-n<193>r<200>·vara' deities seem ç
to be such innovations.
Harihara†also called Haryardha-m<220>rti and <185>a<209>karan<193>r<193>ya<207>a†is ç
Hara (<185>iva) on the right side and Hari (Vi<218><207>u) on the ç
left side.
The right half may be shown as red or white in complexion and has ç
a half of the third eye on the forehead. The two right hands hold ç
the trident or the m<216>ga (deer) and show the abhayamudr<193>.
The left half is dark in complexion, has yellow silk robes, and the ç
hands hold the ·a<209>kha (conch) and gad<193> (mace). Sometimes cakra ç
(discus) and padma (lotus) are shown instead of the conch and the ç
mace.
According to the V<193>manapur<193><207>a Vi<218><207>u is said ç
to have revealed this form to the gods who had approached him to know ç
where <185>iva was.
As per another version a demon, Guh<193>sura by name, had obtained ç
a boon from Brahm<193> that neither Hari nor Hara should be able to ç
kill him. Hence Hari and Hara joined together in this form and killed ç
him. The place where this manifestation took place is called `Harihara.' ç
It is an important town in the Chitradurga district of Karnataka and ç
has a beautiful temple of <185>a<209>kara-n<193>r<193>ya<207>a (same ç
as Harihara).
Icons of this form seem to be of great antiquity (<MS>A.<|>D.<D> 100) ç
and belong to the Ku·<193>na period.
@SPACE = 
@NT = harijans
@N1 = (`people of God')
This word was coined by Mah<193>tm<193> G<193>ndh<200> (<MS>A.<|>D.<D> ç
1869-1948) with regard to those people in the Hindu society who had ç
been treated for centuries as untouchables. Even if the society disowned ç
them, God did not, since they belonged to God!†This seems to be the ç
idea behind the word.
See <MS>ANTYAJA<D> and <MS>ASP<184><185>YAT°<D>.
@SPACE = 
@NT = harikath<193>
@N1 = (`stories related to God')
The vast masses of Hindu India, though unlettered or uneducated in ç
the formal sense, have been more educated and cultured than their ç
counterparts in many other countries of the world. This has been mainly ç
due to the methods of mass education adopted by the religio- cultural ç
teachers of medieval and post- medieval India.
One of such methods is the harikath<193> found mostly in South India. ç
Kath<193>-k<193>la-k<218>epa or k<193>lak<218>epa (of Tamil Nadu), ç
k<200>rtana by the buv<193>s (of Maharashtra), harikath<193> and burrakath<193> ç
(of Andhra Pradesh) and kathakath<193> or g<200>ti-<193>lekhya (of ç
Bengal) are its equivalents.
The main purpose of the harikath<193> is to spread moral, ethical, ç
religious and spiritual ideas among the masses. This is done through ç
the recitation of interesting and touching stories and episodes from ç
the epics, the pur<193><207>as and the lives of saints.
After preliminary prayers, the Bh<193>gavatar, as the narrator is ç
generally called, starts either with a song pregnant with a deep philosophy ç
of life or with a short account of some fundamental religio-ethical ç
teaching. The teaching is then expanded and is expounded in detail ç
through the story chosen for the discourse.
@SPACE1 = 
Apart fromdevotionalmusic,the narrator also embellishes his discourse ç
with suitable stories and anecdotes interspersed with dramatisation ç
at appropriate places.
The Bh<193>gavatar is accompanied by musical instruments like the ç
t<193>np<220>ra, harmonium and tabla or m<216>da<209>ga (percussion ç
instruments) and t<193>la (cymbals).
Harikath<193>s spread over 2 to 3 hours' duration are common and popular ç
even today.
Temples and religious institutions are their patrons.
Modernisation, the result of the fast development of science and technology, ç
has caught up with this art also. Training institutions are coming ç
up where the future Bh<193>gavatars are receiving training. Audio ç
and video tapes of the Harikath<193>s of the well-known exponents ç
are also being made available to the interested public.
@NT = Harimandir
@N1 = (`House of God')
Sikhism is the youngest of world religions and was started by Guru ç
N<193>nak (<MS>A.<|>D.<D> 1469-1539). The Harimandir, also called `<185>r<200> ç
Darb<193>r S<193>hib,' but popularly known as the `Golden Temple', ç
is the most sacred shrine of the Sikhs. It is in Amritsar (Punjab).
It is situated inside a huge tank the construction of which had been ç
started in <MS>A.<|>D.<D> 1577 by Guru R<193>md<193>s (<MS>A.<|>D. <D>1534-1581). ç
The foundation for the temple was laid by the Muslim saint Mia M<200>r ç
(<MS>A.<|>D.<D> 1550-1635) in <MS>A.<|>D.<D> 1588, at the request of ç
Guru Arjan (<MS>A.<|>D.<D> 1563-1606).
The dimensions of the tank are 154.5 by 148.5 metres (507 by 487 feet). ç
The temple itself is 12.25 metres (40 feet) square and stands on a ç
platform which is 19.7 metres (64 feet) square.
The temple took its present shape and form during the reign of Mah<193>r<193>j<193> ç
Ra<207>jit Singh (<MS>A.<|>D.<D> 1780-1839). The architecture is a ç
mixture of the Rajput and the Mughal styles.
The object of worship is the °di Granth, (or Guru Granth S<193>hib), ç
the sacred scripture of the Sikhs compiled by the fifth Guru, Arjan. ç
He also set the daily routine and liturgy which continue even today. ç
As in some Hindu temples where  the  utsavam<220>rti  (processional ç
image) is shifted ceremonially in the night to a rest-room, the Book ç
is also reverently escorted from the main shrine to the Ak<193>lBu<209>g<193> ç
(the edifice raised over the Ak<193>l Takht, the primary Church of ç
Sikh religious authority) in the night and brought back in the early ç
morning.
The Harimandir has been desecrated several  times  by  hosts  of  Muslim ç
marauders from Delhi and Afghanistan. They have even defiled the tank ç
in abominable ways including filling it up with sand . However, these ç
sacrilegious acts have always been met with stiff resis- tance and ç
the shrine has been redeemed and renovated with greater vigour and ç
faith.
The great dome over the temple is covered with plates of copper gilded ç
with gold. Hence the name `Golden Temple'.
Inside the temple, several verses from the Guru Granth S<193>hib ç
(°di Granth) have been inscribed in letters of gold on the arches.
See also <MS>N°NAK<D> and <MS>SIKHISM.<D>
@NT = Hari·candra
In Hindu religion and society, the name `Hari·candra' has become synonymous ç
with satya or truth, so much so, that he is called `Satya-Hari·candra'.
The various legends we come across in our religious literature probably ç
referto more than one Hari·candra. The Aitareya Br<193>hma<207>a ç
(7.18) gives the story of one Hari·candra. He was a king of the Ik<218>v<193>ku ç
dynasty. He had no children. He prayed to Varu<207>a that if he got ç
a son, he would sacrifice him to Varu<207>a. Though a son was born†he ç
was named `Rohit<193>·va'†he went on delaying the sacrifice. Hence ç
Varu<207>a made him ill. To get rid of it, Hari·candra bought a br<193>hma<207>a ç
boy, <185>una··epha by name, and tried to sacrifice him to Varu<207>a. ç
However, the pathetic prayers of this boy melted the heart of Varu<207>a ç
who got him released. The boy was adopted by the sage Vi·v<193>mitra ç
whowas conducting the sacrifice for Hari·candra.
The more common and widely current story of Hari·candra runs like ç
this:
The sage Vasi<218><219>ha had declared that the king Hari·candra of ç
solar dynasty, son of Tri·a<209>ku was the most truthful person on ç
earth. Vi·v<193>mitra, who could not bear his bete noire's confidence ç
in Hari·candra, vowed to disprove it. Due to his malicious machinations, ç
Hari·candra lost his kingdom and wealth, was banished and forced to ç
go to K<193>·<200>. There, he had to sell his wife Candramati and ç
son Rohit<193>·va to a rich man to pay his dues to the sage. Then ç
he took employment under the care-taker of acrematory as his assistant. ç
His son Rohit<193>·va died of snake-bite one day. His wife Candramati ç
was charged with murder by the local king. She was sentenced to death ç
and was brought tothe cremation ground. And, Hari·candra had to behead ç
her! As he was about to strike, gods and sages appeared on the scene, ç
prevented it, brought Rohit<193>·va back to life and restored the ç
kingdom to Hari·-candra. Vi·v<193>mitra had to concede defeat.
@NT = H<193>r<200>ta
H<193>r<200>ta is an ancient sage mentioned by Bh<200><218>ma in the ç
Mah<193>bh<193>rata (<185><193>ntiparva ch. 278) as having taught ç
a g<200>t<193> now known as the H<193>r<200>tag<200>t<193>. The ç
contents of the H<193>r<200>tag<200>t<193>, which has just 22 verses ç
and describes the code of conduct for a sa<221>ny<193>sin can be summarised ç
as follows:
A s<193>dhaka or a mumuk<218>u (one whoisdesirous of liberation) ç
should first renounce the world and take to the sa<221>ny<193>sin's ç
life. He should not find fault with others. He should be friendly ç
and kind towards all. He should bear with fortitude all insults that ç
may be hurled at him by others. He should approach the householders ç
for alms after they have finished their food. He should eat just ç
enough to keep the body and the soul together. He should resort to ç
lonely places for contemplation on the <193>tman. He should practise ç
self-control at all times. He should be broad-minded, always detached ç
from the things of the world and never harm anybody. Such an one will ç
attain the world oflight,thehighest Abode.
H<193>r<200>ta is also the name of a famous writer of dharmas<220>tras ç
who has often beenquoted by other ancient authors like °pastamba ç
and Vasi<218><219>ha as an authority. Though his time is not known, ç
he existed long before <MS>A.<|>D.<D> 600.
From the profuse quotations given by other writers of the dharma·<193>stras, ç
some scholars have tried to rebuild his lost work.
The Dharmas<220>tras of H<193>r<200>ta was definitely an extensive ç
work, in prose and verses. The topics as gleaned from the quotations ç
given in others are as follows: sources of dharma, two kinds of brahma-c<193>rins, ç
the sn<193>taka, the g<216>hastha (householder), thev<193>naprasthin(forest ç
hermit), injunctions and prohibitions about food, a·auca  (ceremonial  impurity),  ·r<193>ddha ç
(obsequial rites), pa<210>camah<193>yaj<210>as (five daily sacrifices), ç
Vedic studies, statecraft, court procedures, sins and expiations, ç
prayers and so on.
H<193>r<200>ta refers to two kinds of women: brahmav<193>din<200>s  and ç
sadyovadh<220>s.  The former were entitled for upanayana, Vedic studies ç
and keeping the sacred fire.
Two more works, one known as Laghu-H<193>r<200>ta and the other ç
as V<216>ddha-H<193>r<200>ta are mentioned by some writers like ç
Apar<193>rka (12th century <MS>A.<|>D.<D>).
@NT = H<193>r<200>tag<200>t<193>
See <MS>H°R®TA<D>.
@NT = Harit<193>lik<193>
Vratas (religious vows) and utsavas (festivals) are an important aspect ç
of Hindu rituals.
The Harit<193>lik<193> which falls on the third day of the bright ç
fortnight (·ukla t<216>t<200>y<193>)  of  the  month  of  Bh<193>drapada ç
(generally September) is a popular vrata observed by the Hindu women ç
(whose husbands are alive), mostly in Maha-rashtra and Rajasthan. ç
It is performed to please Um<193> or P<193>rvat<200>, the spouse of ç
<185>iva, to secure health and longevity for their husbands. Fasting, ç
worshipof Um<193> with <185>iva and breaking the fast after the moon ç
is seen are part of this vrata.
A grand procession of an image of P<193>rvat<200> taken out from the ç
city palace of Mah<193>r<193>j<193> M<193>n Singh in Jaipur, is a ç
special feature of this festival.
@NT = Hariva<221>·a
The Hariva<221>·a is considered as the khila part (an appendix or ç
addendum) of the great epic Mah<193>bh<193>rata. Its main purpose ç
seems to be to supply the details of the K<216><218><207>a story, ç
especially of the childhood and the boyhood days.
It is sometimes classed among the upapur<193><207>as also, since it ç
contains the five well-known characteristics of a standard pur<193><207>a ç
(vide <MS>PUR°ØAS<D>).
It has three sections, each section being designated as a `parva'.
The following are the details:
@SPACE1 = 
@L6LS = Parva<+><+><+><+><+><+><+><+><+><+><+><+><|>Chapters	<+>Verses<R>ç
Hariva<221>·aparva	<+>55	<+><+>3,111<R>ç
Vi<218><207>uparva	128	<+><+>7,817<R>ç
Bhavi<218>yatparva	135	<+><+>5,205
@L6 = <MUO>Total	318	<+>16,133<D>
@SPACE1 = 
@SPACE1 = 
However, in the Critical Edition of the Mah<193>bh<193>rata, the ç
details are as follows:
@SPACE1 = 
@L6-1 = Hariva<221>·aparva	chs. 1-45;	·lokas 2442.<R>ç
Vi<218><207>uparva	chs. 46-113;	·lokas 3426<R>ç
Bhavi<218>yatparva	chs. 114-118;	·lokas 205
@L6-1 = <MUO>Total	118 chs.	6073 ·lokas<D>
@SPACE = 
The Hariva<221>·aparva (also called Va<221>·aparva) gives detailed ç
geneologies ofYadus, V<216><218>as, Andhakas, V<216><218><207>is ç
and Madhus. The lists are quite exhaustive.
The Vi<218><207>uparva gives the details of K<216><218><207>a's ç
life. The story is almost the same as in the Vi<218><207>upur<193><207>a ç
and the Bh<193>gavata. (See <MS> BH°GAVATA<D>  and<MS> VI<186>ØUPUR°ØA<D>  for ç
details.)
Some minor differences between the details given in Hariva<221>·a ç
and the two pur<193><207>as may be noted here:
The  word  `R<193>sakr<200><195><193>'  has  been substituted by `Hall<200>·akr<200><195><193>' ç
which means the same thing.
When the people of Gokula were not willing to go to V<216>nd<193>vana ç
as suggested by K<216><218><207>a, he created a very large number ç
of wolves from his own body to frighten them and force them to leave ç
(2.9).
In the Govardhana hill episode, thedescription of Indra's defeat ç
is less ignominious to him!
The incident of taking away the p<193>rij<193>ta tree from svargaloka ç
(heaven) has also been described in a similar vein.
The Bhavi<218>yatparva  contains the following stories: Janamejaya's ç
sacrifice, creation of the world by God, episode of the king P<216>thu, ç
destruction of Dak<218>a's sacrifice, stories of some of the avat<193>ras ç
or incarnations of Vi<218><207>u, <185>iva and K<216><218><207>a, ç
K<216><218><207>a's killing of several demons and so on.
@NT = hariv<193>sara
@N1 = (`day of [Lord] Hari')
See <MS>EK°DA<185>®.<D>
@NT = Harivy<193>sadeva
Nimb<193>rka (12th century <MS>A.<|>D.<D>) was one of the great teachers ç
of Vai<218><207>avism whose philosophy was known as `Dvait<193>-dvaita.' ç
Harivy<193>sadeva (15th century <MS>A.<|>D.<D>) was an important teacher ç
of this school. He was a disciple of the musician-saint <185>r<200>bha<219><219>a. ç
He used to live mostly in V<216>nd<193>van (in theMathur<193> district, ç
Uttar Pradesh), his favorite resort being the N<193>rad<219><200>l<193> ç
(N<193>rada's mound) near Mathur<193>.
Deeply devoted to Lord K<216><218><207>a, he was very fond of pilgrimage, ç
spreading the cult of bhakti through discourses and written compositions ç
as also organising the people for assisting him in this task of uplifting ç
dharma.
It is said that, to make the Hindu society more virile, he propagated ç
the worship and mantrajapa of Narasi<221>ha, the fierce aspect of ç
Lord Vi<218><207>u. He is also believed to have stopped animal sacrifice ç
in some Dev<200> temples in the Him<193>layan region.
He has left a Sanskrit commentary onthe work Ved<193>ntaratnama<210>j<220><218><193> ç
of Puru<218>ottam<193>c<193>rya, a famous teacher of the Nimb<193>rka ç
school.
His disciple Svabh<220>r<193>m worked hard in the Punjab region to ç
bring about peace among the warring factions of certain Hindu cults. ç
Another disciple of his, Para·ur<193>madeva, successfully countered ç
the anti-Hindu activities of the Muslim fak<200>rs of the time.
@NT = Harki<218>an, Guru
@N1 = (<MS>A.<|>D.<D> 1656-1664)
@SPACE1 = 
That spiritual greatness need not and does not depend upon the physical ç
age of a person has been proved time and again in the lives of many ç
a saint†whether it is <185>uka of the paur<193><207>ik age or J<210><193>ndev ç
(13th Century) of the historic age. Guru Harki<218>an, the eighth ç
in the line of the Sikh Gurus, belongs to this category.
When the seventh Guru, Har Rai (<MS>A.D.<D> 1630-1661), chose his ç
second son Harki<218>an for the august seat of the Sikh Gurus, he ç
was hardly five years old! However, like the early morning sun which, ç
though small, lights up the wholeworld, Guru Harki<218>an shone in ç
his precocious wisdom of explaining the °di Granth, the basic scripture ç
of the Sikhs.
R<193>m Rai, his elder brother, who had been superseded in favour ç
of his younger brother,  complained  to  the  Mughal emperor Aurangzeb ç
(<MS>A.<|>D.<D> 1618-1707) and sought his assistance to redress the ç
`injustice' done to him. When the emperor called Guru Harki<218>an ç
to his court and tried to test him, the child-Guru acquitted himself ç
admirably.
Smallpox which was raging at Delhi at that time, took the life of ç
the young Guru at the tender age of eight.
Before passing away he nominated Teg Bah<193>dur of the town Bak<193>l<193> ç
as the next Guru.
@NT = Har R<193>i, Guru
@N1 = (<MS>A.<|>D.<D> 1630-1661)
@SPACE1 = 
Har R<193>i was the seventh Guru of the Sikhs. He was the son of B<193>b<193> ç
Guruditt<193> and  grandson  of  Guru  Hargobind. Sulakha<207><200> ç
was his noble and worthy wife.
Once he saw Guru Hargobind (<MS>A.<|>D.<D> 1595-1644) from a distance ç
and while rushing to meet him, broke some branches of a flower plant. ç
This pained him so much that he started weeping. Observing this, the ç
Guru advised him with a few words that became the beacon of his life.
Guru Hargobind nominated him as his successor in 1644 before his death.
Guru Har R<193>i kept up the military traditions  introduced  by  his  guru ç
Hargobind for the defence of dharma. It is said that he had 2200 armed ç
followers.
There were no armed conflicts during his time with the ruling powers.
He established three important teaching missions. They were by Bhagv<193>n ç
Gir (or Bhagat Bhagv<193>n), Sa<209>gat<200><193> (or Bh<193><200> ç
Pher<220>) and Bh<193><200> Gond<193>. These preachers worked respectivelyineasternIndia, ç
westernIndiaand K<193>b<220>l. Two more preachers†Bh<193><200> Natth<193> ç
and Bh<193><200> Jodh† were also sent to preach at £h<193>k<193> and ç
Mult<193>n.
