@NID = It is the sacred duty of all the leaders of the Hindu society ç
to make every effort in this direction.
@NT = hi<209>k<193>ra
@N1 = (`[the sound] hi<221>')
Vedic sacrifices were the most important aspect of religion in practice ç
in the ancient days. Out of the several acts enjoined in the same, ç
chanting of the s<193>mans (<216>k-mantras set to music according ç
to the S<193>maveda) was also one.
Uttering the word `hi<221>' marked the opening of the s<193>man in ç
some sacrifices. It was repeated thrice by the hot<216> priest. Sometimes, ç
the udg<193>t<216> priest did it; but he replaced `hi<221>' by `h<220>m ç
<193>' twice.
When  `hi<221>'  was  repeated  thrice followed by `bh<220>r bhuvas ç
suvarom' it was called `abhihi<209>k<193>ra'.
@NT = Hira<207>yagarbha
@N1 = (`golden egg')
According to the Advaita Ved<193>nta he is the second aspect of Brahman, ç
the pure consciousness, associated with aj<210><193>na or nescience, ç
after ®·vara. He is connected with the totality of the s<220>k<218>ma·ar<200>ras ç
or subtle bodies in creation, permeating them like the thread passing ç
through the beads. Hence the name `S<220>tr<193>tman'. He is also ç
called `pr<193><207>a,' being the subtle principle of life. The unmanifested, ç
seed-state of creation is compared to a golden egg. Since he keeps ç
it in his womb as it were, before manifesting it, he is called `Hira<207>yagarbha' ç
(`golden egg'). He has the three powers of will, knowledge and action, ç
known as icch<193>·akti, j<210><193>na·akti and kriy<193>·akti.
@NT = Hira<207>yagarbha S<220>kta
The s<220>ktas from the <184>gveda are widely used in the Vedic ç
sacrifices either as prayers or as mantras for the performance of ç
appropriate rituals. One such s<220>kta used in Pa·ubandha sacrifices ç
is the Hira<207>yagarbha S<220>kta.
Though used as a part of Vedic ritual, this s<220>kta has a profound ç
philosophical import.
Originally it appears in the <184>gveda (10.121). It is repeated ç
in the Taittir<200>ya Sa<221>hit<193> (4.1.8) of Yajurveda and ç
the Paippal<193>da Sa<221>hit<193> (4.2) of the Atharva-veda with ç
slight changes.
This s<220>kta has ten <216>ks or stanza each of which ends with the ç
words, `kasmai dev<193>ya havi<218><193> vidhema.'
The word `ka' and its dative case, `kasmai,' repeated in every stanza, ç
has rather posed a problem of interpretation. The simplest meanings ç
are, `who' and `to whom'. However, this direct meaning does not allow ç
grammatically proper syntactical connection. Hence commentators have ç
struggled to give other interpretations.
Depending on an anecdote in the Aitareya Br<193>hma<207>a (12.21) ç
S<193>ya<207>a (14th century), the well-known commentator of the Vedas, ç
interprets the word `ka' as a name of Praj<193>pati (one of the aspects ç
of God) the creator of the world.
According to another interpretation `ka' means `bliss'.
Hence the sentence would mean, `We offer the oblations unto God, the ç
creator, who is bliss-personified.'
A brief summary of the s<220>kta can now be given:
@SPACE1 = 
Hira<207>yagarbha (God the creator in whom the whole world existed ç
in a seed-form like a golden egg) alone existed in the beginning. ç
He created the world and was its supreme monarch. It was he who was ç
responsible for supporting heaven and earth. Again, it was he who ç
gave strength to all the living beings including the gods, who have ç
been obeying his commands. The Him<193>layas, the oceans and the rivers ç
are reflecting his glory. If the earth and heaven have been firmly ç
established in their places, if the sun and the rainbearing clouds ç
are performing their duties regularly, it is because of him only.
This is the gist of the first seven verses.
The  eighth  verse  indicates  that primeval waters existed before ç
creation and Praj<193>pati or Hira<207>yagarbha was its witness.
The next verse is a prayer to him so that he does not trouble the ç
votaries.
The last, the tenth, verse praises him as the only one capable of ç
creating the world and prays to him for granting or fulfilling the ç
desires of the devotes who are offering this prayer.
@SPACE = 
@NT = Hira<207>yaka·ipu
@N1 = (`one who has covered himself with gold', `the greedy one')
@SPACE = 
Jaya and Vijaya, the gate-keepers of Vaiku<207><219>ha (the abode ç
of Vi<218><207>u) were once cursed by the sages Sanaka, Sanandana, ç
Sanatkum<193>ra and Sanatsuj<193>ta, to be born as r<193>k<218>asas ç
(demons). The curse was to be effective for three births only.
They were hence born as Hira<207>y<193>k<218>a and Hira<207>yaka·ipu ç
in the K<216>tayuga, as R<193>va<207>a and Kumbhakar<207>a in the ç
Tret<193>-yuga, and as <185>i·up<193>la and Dantavaktra in the Dv<193>parayuga. ç
In all the three births they were killed by Lord Vi<218><207>u in ç
his incarnations as Var<193>ha, Narasi<221>ha, R<193>ma and K<216><218><207>a.
Hira<207>yaka·ipu, the son of Ka·yapa and Diti, was enraged by the ç
killing of his twin-brother Hira<207>y<193>k<218>a at the hands of ç
Vi<218><207>u. He performed severe austerities, pleased the god Brahm<193> ç
and secured several boons from him. Emboldened by these, he conquered ç
the gods in heaven and started harassing one and all.
He had four sons, of whom Prahl<193>da (the famous child-devotee) ç
was the eldest. Since this boy was deeply devoted to Vi<218><207>u, ç
Hira<207>yaka·ipu tried his level best, first to `reform' him and ç
then to liquidate him. But by Lord Vi<218><207>u's grace and protection ç
the  boy  remained  <|>unharmed!  Finally Hira<207>yaka·ipu was killed ç
by the lord in the form of Narasi<221>ha (man-lion), thus ridding ç
the world, of an incorrigible tyrant.
This story appears mainly in the Vi<218><207>upur<193><207>a (1.17-20) ç
and the Bh<193>gavata (7.1-10).
@SPACE = 
@NT = Hira<207>yake·i Dharmas<220>tras
@SPACE = 
Secondary scriptures like the sm<216>tis, <193>gamas and pur<193><207>as, ç
have a say even today in the life of the Hindus. The dharmas<220>tras ç
which are part of these secondary scriptures, are quite ancient.
The Hira<207>yake·i Dharmas<220>tras which forms an integral part ç
of a bigger work, the Hira<207>yake·i Kalpas<220>tras (pra·nas 26 ç
and 27), is not considered as an independent work since it borrows ç
profusely from the °pastamba Dharmas<220>tras.
It belongs to the Taittir<200>ya branch of Yajurveda. There is a ç
commentary called Ujjval<193> by Mah<193>deva D<200>k<218>ita.
The work must have been composed much earlier than <MS>A.<|>D.<D> 200.
The contents of this work are practically the same as those of the ç
°pastamba Dharmas<220>tras.
See <MS>°PASTAMBA.<D>
@NT = Hira<207>y<193>k<218>a
See <MS>HIRAØYAKA<185>IPU.<D>
@NT = hita
@N1 = (`[that which is conducive to] well- being')
Though this word in a general sense means `well-being,' it is used ç
in the philosophy of R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137) in ç
a technical sense.
A person desirous of mukti or liberation has to know three things: ç
tattva or Reality, hita or the means of attaining the Reality and ç
puru<218><193>rtha or the nature of final attainment or mukti.
One who is interested in hita should be aware of five things such ç
as svasvar<220>pa (one's own nature), parasvar<220>pa (nature of God) ç
and so on.
See <MS>VI<185>I<186><187>°DVAITA VED°NTA DAR<185>ANA<D> for details.
@NT = Hitopade·a
@N1 = (`salutary instructions')
Didactic compositions are a special feature of Sanskrit literature. ç
Two of the more well-known works of such a type are the Pa<210>catantra ç
of Vi<218><207>u·arma and the Hitopade·a of N<193>r<193>ya<207>a, ç
a court pundit of the king Dhavalacandra of Bengal.
The Hitopade·a is a collection of fables and tales in prose and ç
poetry. It has borrowed the material partly from thePa<210>catantra ç
and partly from the K<193>mandak<200>ya  N<200>ti·<193>stra.  It  has  four ç
chapters:
1. Mitral<193>bha<199> (`The winning of friends); 2. Suh<216>dbheda<199> ç
(`The breaking up of friendship'); 3. Vigraha<199> (`War') and 4.Sandhi<199> ç
(`peace').
King Sudar·ana had been very muchworried by the lack of education ç
and culture, and consequent indecent behaviour of his sons. N<193>r<193>ya<207>a ç
promised to educate them in six months and, to the surprise of all, ç
achieved it. The result was this wonderful work Hitopade·a.
The Hitopade·a contains a number of new tales and fables, including ç
edifying stories, tales of intrigue and even fairy tales, but always ç
aimed at teaching some great value, useful to life. It contains a ç
good number of maxims and proverb-like statements.
The work has been very popular over the centuries and retains that ç
position even now. It has been translated into thirteen foreign languages, ç
let alone the several ones of India.
See also <MS>PA<178>CATANTRA.<D>
@NT = hl<193>din<200>
See <MS>ACINTYA-BHED°BHEDA.<D>
@NT = Holi, Holik<193>
Holi or Holik<193>, also called holi- kotsava, is an extremely popular ç
festival observed throughout the country. It is especially marked ç
by unmixed gaiety and frolics and is common to all sections of the ç
people.
This festival is very ancient. Known originally as `holik<193>,' it ç
has been mentioned in very early religious works such as Jaimini's ç
P<220>rvam<200>m<193><221>s<193>s<220>tras and K<193><219>haka ç
G<216>hyas<220>tras. It must have therefore existed several centuries ç
before Christ. It was at first actually a special rite performed by ç
married women for the happiness and well-being of their families and ç
the full moon (`R<193>k<193>') was the deity worshipped by them.
There are two ways of reckoning a lunar month: p<220>r<207>im<193>nta ç
and am<193>nta. In the former, the first day starts after the full-moon; ç
and in the latter, after the new-moon. Though the latter reckoning ç
is more common now, the former was very much in vogue in the earlier ç
days. According to this p<220>r<207>im<193>nta reckoning, Ph<193>lguna ç
p<220>r<207>im<193> was the last day of the year and the new year ç
heralding the Vasanta-<216>tu or spring started the next day. Thus ç
the full-moon festival of Holik<193> gradually became a festival of ç
merry- making, announcing the commencement of the spring. This perhaps ç
explains the other names of this festival: Vasantamahotsava and K<193>ma-mahotsava.
According to the stories in the pur<193><207>as and various local ç
legends, this day is important for three reasons:
@SPACE1 = 
1.<+>It was on this day that Lord <185>iva opened his third eye and ç
reduced K<193>madeva (the god of Love, Cupid or Eros) to ashes.
2.<+>It was on this day that Holik<193>, the sister of the demon king ç
Hira<207>ya-ka·ipu, who tried to kill the child-devotee Prahl<193>da ç
by taking him on her lap and sitting on a pyre of wood which was set ç
fire to, was herself reduced to ashes, while Prahl<193>da was unscathed!
3. It was again, on this day, that an ogress called £hu<207><195>hi, ç
who was troubling the children in the kingdom of P<216>thu (or Raghu) ç
was made to run away for life,by the shouts and pranks of the mischievous ç
boys. Though she had secured several boons that made her almost invincible, ç
this†noise, shouts, abuses and pranks of boys†was a chink in her armour ç
due to a curse of Lord <185>iva. The day itself came to be called ç
`A<195><193><195><193> or Holik<193>' since then.
@SPACE1 = 
There are practically no religious observances for this day like fasting ç
or worship. Generally a log of wood will be kept in a prominent public ç
place on the Vasantapa<210>cam<200> day (M<193>gha ·ukla pa<210>cam<200>) ç
almost 40 days before the Holi festival. An image of Holik<193> with ç
child Prahl<193>da in her lap is also kept on the log. Holik<193>'s ç
image is made of combustible material  whereas  Prahl<193>da's,  of  non- ç
combustible ones. People go on throwing twigs of trees and any combustible ç
material they can spare, on to that log which gradually grows into ç
a sizeable heap. On the night of Ph<193>lguna p<220>r<207>im<193>, ç
it is set fire to in a simple ceremony, the Rak<218>oghna mantras ç
of the<184>gveda (4.4.1-15; 10.87.1-25 and so on) being sometimes ç
chanted to ward of all evil spirits. The next morning, the ashes from ç
the bonfire are  collected  as  pras<193>da  (consecrated material) ç
and smeared on the limbs of the body. Singed coconuts, if any, are ç
also collected and eaten.
In some houses, the image of K<193>madeva is kept in the square yard ç
and a simple worship is offered. A mixture of mango blossoms and sandalwood ç
paste is partaken as the pras<193>da.
The day†Ph<193>lguna k<216><218><207>a pratipad† is observed as a ç
day of revelry especially by throwing on one another gul<193>l or ç
coloured  water  or perfumed  coloured powder. Throwing of mud or ç
earth-dust was prevalent in the earlier days also, but among the low ç
culture groups only.
Instead of the gay and frenzied celebrations that are witnessed elsewhere ç
in the country, Bengal observes it in a quiet and dignified manner ç
as Dolp<220>r<207>im<193> or Dol<193>y<193>tr<193> (the festival of ç
the swing). The festival, said to have been initiated by the king ç
Indradyumna in V<216>nd<193>vana, is spread over 3 or 5 days, starting ç
from the ·ukla caturda·<200> of Ph<193>lguna. A celebration in honour ç
of Agni and worship of Govinda (K<216><218><207>a) in image kept on ç
a swing (dol<193> = swing) are the important features. The fire kindled ç
on the first day is to be preserved till the last day. The swing is ç
to be rocked 21 times at the end of the festival.
The day is also celebrated as the birthday of <185>r<200> K<216><218><207>a ç
Caitanya (<MS>A.<|>D.<D> 1486-1533), mostly in Bengal, as also in Pur<200> ç
(in Orissa), Mathur<193> and V<216>nd<193>van (in Uttar Pradesh).
@NT = homa
@N1 = (`pouring oblation')
Vedic sacrifices, which werevery simple in the beginning, gradually ç
grew into a labyrinth of rites and rituals. As a reaction to this, ç
in course of time, evolved simpler  fire-rituals  conducted  in  the ç
domestic fire. This is how homa was born.
Literally, homa (or havana) means the act of pouring an oblation (usually ç
of ghee or clarified butter) into a duly consecrated fire. It is an ç
essential feature of  domestic  rites.  Also,  it  is  often considered ç
as an integral part of special p<220>j<193> or worship of a deity.
The major steps involved in the performance of a homa are: preparing ç
the stha<207><195>ila (altar for the fire, a raised surface of sand ç
or loose earth), purification of the <193>jya (ghee used for oblation), ç
warming the ladle, putting the faggots and lighting the fire, pouring ç
of the oblations with mantras appropriate to the deity, p<220>r<207><193>huti ç
(final offering), ceremonially putting out the fire (generally with ç
curds) and preparing the rak<218><193> (ashes from the remnants pasted ç
with ghee, to be applied on the forehead as a religious mark).
@NT = hor<193>
@N1 = (`astrology')
This  word seems to  have  been borrowed from the greek `hora' and ç
was used for the first time by Var<193>hamihira (6th century <MS>A.<|>D.<D>).
Hindu astrology (jyoti<218>a) includes three  skandhas  or  branches:  tantra ç
(determination of the motions of planets), hor<193> (j<193>taka or ç
horoscope) and ·<193>kh<193> (various kinds of divinations).
A work that embodies all these three is called `sa<221>hit<193>'.
Hor<193> has two other meanings in astrology: lagna (that sign which ç
is rising on the eastern horizon at the particular moment) and half ç
of a r<193>·i (zodiacal sign).
See also <MS>JYOTI<186>A.<D>
@NT = horoscope
See <MS>J°TAKA.<D>
@NT = hospitality
See <MS>ATITHI.<D>
@NT = hot<216>
@N1 = (`one who invites [gods for receiving oblations]')
@SPACE = 
A Vedic sacrifice needs four principal priests of whom the hot<216> ç
is one. He belongs to the <184>gveda; i.e., his special duty is ç
to recite the mantras of the <184>gveda called `·astras' (laudatory ç
hymns) to invoke the gods to the sacrifice.
He performs all the ritualistic acts for which no other person has ç
been specifically mentioned. He sits, facing the east, to the north ç
of the northern vedi (platform). His assistants are: maitr<193>-varu<207>a, ç
acch<193>v<193>ka and gr<193>vastut.
See also <MS>VEDIC SACRIFICES.
@SPACE = 
@NT = house
@SPACE = 
It is but natural for every g<216>hastha or householder to construct ç
his own house and live there. The g<216>hyas<220>tras and the pur<193><207>as ç
have dealt with almost all the aspects†except the engineering details† ç
involved in the construction and entering it. Selection of a suitable ç
site, starting of the construction, the various stages in the same ç
and entering the new house are the subjects dealt with.
The construction must be begun on an auspicious day in the ·uklapak<218>a ç
orthe bright fortnight of uttar<193>ya<207>a (northern solstice) ç
and when the nak<218>atras like Rohi<207><200>, Uttaraph<193>lgun<200> ç
or Uttar<193><218><193><195>h<193> are present.
The Matsyapur<193><207>a (253.1-5) states the results of beginning ç
the construction of a house in the twelve months from Caitra   (March-April)   onwards.   For ç
instance, if it is begun in °<218><193><195>ha (July), the owner will ç
gain in cattle and will get good servants. If in Caitra, he suffers ç
from diseases and so on.
Nak<218>atras which are auspicious as also those which are inauspicious, ç
have also been mentioned.
The rules regarding entering a new house†g<216>haprave·a†are observed ç
even now.
See also <MS>G<184>HAPRAVE<185>A.<D>
@NT = h<216>daya
@N1 = (`[that which is] taken away [by the sense-objects]')
The word `h<216>daya' is generally used in two senses: the physical ç
heart and the seat of mind.
It has always been considered as the seat of consciousness.
Su·ruta describes the shape of the heart as that of a half-open lotus ç
with the face upward.
Caraka (3rd cent. <MS>A.<|>D.<D>) says that the ten dhaman<200>s (ducts) ç
which carry the constituents of the body start from the heart.
Figuratively, the word is used to indicate the inner sense of a thing.
@NT = h<216>d-dhauti
@N1 = (`cleansing of the throat')
Ha<219>hayoga is one of the important branches of yoga. It is devoted ç
mainly to the cleansing and the strengthening of the body so that ç
it becomes a fit instrument for the practice of R<193>jayoga.
Dhauti (cleansing process) which is one of the <218>a<219>karmas or ç
six practices recommended by Ha<219>hayoga, is of four types: antardhauti, ç
dantadhauti, h<216>d-dhauti and m<220>la·odhana.
H<216>d-dhauti means cleansing of the throat. It is of three kinds: ç
da<207><195>adhauti, vamana and vastra. As these very names indicate, ç
they are the processes of cleansing the throat passage and oesophagus ç
byusing a da<207><195>a (stick, plantain stalk), by vamana (vomitting) ç
and by vastra (swallowing a thin strip of cloth).
These, however, must be practised under the direct guidance of experts.
@NT = hr<200><221>
Mantras recommended for japa and meditation usually include a b<200>ja ç
(or b<200>jamantra) (seed-letter) which contains in itself the form ç
and the power of the deity of the mantra. `Hr<200><221>' is one of ç
the well-known b<200>jas assigned to the goddess <186>o<195>a·<200>, ç
an aspect of P<193>rvat<200>.
It  is  also  one  of  the  niyamas prescribed by Layayoga. (See <MS>LAYAYOGA<D> ç
for details.) It is interpreted as being ashamed (hr<200> = sense ç
of shame) of allsuch undesirable actions which are opposed to yoga ç
as described by the scriptures.
See also <MS>B®JAMANTRA.<D>
@NT = humours
According to °yurveda, the science of health and longevity, the human ç
body has three humours, called `do<218>as', viz., kapha (phlegm), ç
v<193>ta (wind) and pitta (bile) which have to be kept in a state ç
of balance, to maintain good health.
See <MS>°YURVEDA.<D>
@NT = hymnology
See <MS>STOTRAS.
@END = 
