@H = Z
@NT = zero
The invention of the symbol zero has brought about a great revolution ç
in the field of mathematics. So also the decimal system. Both have ç
their origin in India.
Zero has been called by various names:  ·<220>nya;  kha;  ambara;  gagana; ç
abhra; <193>k<193>·a; bindu; p<220>r<207>a.
Pi<209>gala's work on metres (Chanda<199>- s<220>tra (8.28-31) makes ç
use of zero called ·<220>nya.
From references in the Sa<221>hit<193>s scholars opine that the decimal ç
system goes back to thousands of years.
It was introduced in Europe through the Arabs during the 12th century<MS> ç
A.D.

@NT = Zodiacal Signs
See <MS>JYAUTI<186>A.

@END = 
@H = <P10M>Blank
@H = <R>ç
<R>ç
<R>ç
<R>ç
<R>ç
<R>ç
<R>ç
<R>ç
<R>ç
<F21P17B>A<P14>DDENDUM<F255P255D>
@H = <P10M>Blank<P255D>
