@H = G
@NT = gad<193>
@N1 = (`mace or club')
The gad<193> or the mace is one of the ancient weapons used in direct ç
fighting. It is frequently mentioned in the two epics and the pur<193><207>as. ç
Fighting with the gad<193> (gad<193>-yuddha) had been developed into ç
a well-developed art. Hanum<193>n, Balar<193>ma, Bh<200>ma and Duryodhana ç
were experts in the wielding of this weapon.
The gad<193>s of famous warriors had their own special names.
Vi<218><207>u's mace was called `Kaumodak<200>'. It had been prepared ç
by Vi·vakarma, the celestial artisan, from the bones of an exceedingly ç
strong demon Gad<193>sura.
Sometimes Kaumodak<200> is pictured as a goddess standing on the right ç
side of Vi<218><207>u.
The gad<193>s are of various sizes and shapes, and are made out of ç
hard wood or iron.
Gad<193>dhara is one of the names of Vi<218><207>u since he holds ç
the gad<193>, Kaumodak<200> by name. He used it to kill the demon ç
Heti.
The particular form of Vi<218><207>u presiding over the pilgrim centre ç
of Gay<193> is also `Gad<193>dhara' or `°di-gad<193>dhara'.
@NT = gaja
@N1 = (`that which roars [due to the<R>ç
arrogance of strength]', `an elephant')
The gaja or an elephant is a familiar figure met with in Hindu mythology ç
and other religious literature. Being the biggest and the most powerful ç
of all the animals on land, it might have induced awe inthe minds ç
of the aboriginal people. According to one guess, this might have ç
been the origin of the elephant-headed god Ga<207>apati and his cult.
Even by the time of the Aitareya Br<193>hma<207>a (8.22), use of ç
tamed and trained elephants in warfare, was common.
Possessing elephants was often a symbol of one's wealth and power. ç
It was a must for a king or an emperor who wouldhave an elephant ç
(generally a white elephant) as the State elephant after a ritual ç
baptism. This would then invariably be a part of his entourage on ç
all important occasions.
The <185>atapatha Br<193>hma<207>a (3.1.3.3-4) ascribes a divine ç
origin to the elephant as being evolved out of M<193>rtt<193><207><195>a, ç
a son of Aditi, the mother of gods.
Eight mythical elephants are supposed to be carrying this earth on ç
their shoulders. They are: Air<193>vata, Pu<207><195>ar<200>ka, V<193>mana, ç
Kumuda, A<210>jana, Pu<218>padanta, S<193>rvabhauma and Suprat<200>ka.
Elephants formed one of the four divisions of an army (catura<209>gabala) ç
of a king, the other three being horses, chariots and infantry.
The elephant is listed among the a<218><219>ama<209>galas,  eight  objects  signifying ç
auspiciousness. (See <MS>A<186><187>AMA<177>GALAS<D>.)
Elephants are often shown in the motifs on the walls of temples.
@NT = gajacch<193>y<193>
@N1 = (`shadow of an elephant')
In the Hindu calendars, certain combinations of lunar days and asterisms ç
are considered as very good. The gajacch<193>y<193> is one such. When ç
the moon is in the Magh<193> or Makh<193> nak<218>atra (the 10th constellation ç
of 5 stars) and the sun in the Hast<193> (the13th constellation, ç
also of 5 stars), theperiod is considered as very sacred, especially ç
for the performance of ·r<193>ddhas.
The ·r<193>ddha recommended here is to be performed in the shadow ç
of an elephant. Hence the name (gaja = elephant; ch<193>y<193> = shadow). ç
It is said to give gratification tothe manes for thousands of kalpas ç
(extraordinarily long periods of time).
This ·r<193>ddha can be performed during the intercalary months (adhika ç
or mala m<193>sa) also.
@NT = gajahasta
@N1 = (`hand-pose [resembling the] trunk of an elephant')
In the m<220>rti·ilpa·<193>stra or iconography, one of the important ç
aspects of the subject dealt with is the hasta or the pose of the ç
hand. Out of the several poses mentioned, the `gajahasta' is also ç
one. It is called so because of its resemblance to the trunk of an ç
elephant (gaja = elephant, hasta = hand or trunk).
Gajahasta in images is shown in two different ways. In the first, ç
the arm is shown dangling by the side. Usually the left arm of the ç
images of Dev<200> is shown in this way. In the second the arm may ç
be shown across the chest, with the hand bent down, as is seen in ç
the images of Na<219>ar<193>ja (the left normal arm).
@NT = Gajalak<218>m<200>
@N1 = (`Lak<218>m<200> [associated with]<R>ç
elephants')
@SPACE = 
Gajalak<218>m<200> is the most popular of the eight forms of Lak<218>m<200>†called ç
A<218><219>amah<193>lak<218>m<200>†and is usually shown on the lintels ç
of door-frames. She is dressed in snow-white garments and is seated ç
on a lotus of eight petals. She has four arms carrying a long-stalked ç
lotus, a pot of nectar, a bilva fruit (Aegle marmelos) and a conch. ç
Behind her are two decorated elephants shown as pouring water over ç
her from pots held in their trunks. The elephants may also be shown ç
with raised trunks, holding a lotus each, in adoration.
One of the well-known figures is in the stone relief of the Var<193>hama<207><195>apa ç
at M<193>mall<193>puram (Mah<193>balipuram) near Chennai (or Madras).
@NT = Gaj<193>sura
@N1 = (`the demon [in the form of a] gaja or elephant')
He was the son of Mahi<218><193>sura, the demon in the form of a bison, ç
who was ultimately killed by the goddess Durg<193>.
Gaj<193>sura pleased <185>iva with his auste-rities performed with ç
devotion and secured several supernatural boons. Armed with the might ç
of these, he started harassing the gods in heaven. When they supplicated ç
to <185>iva himself for succour and protection, <185>iva challenged ç
Gaj<193>sura for a duel. Gaj<193>sura surrendered with the condition ç
that <185>iva should wear his skin as his apparel after killing him. ç
<185>iva obliged him by doing so. Hence he came to be known by such ç
names as Gajacarm<193>mbaradhara or N<193>gacarmadhara or K<216>ttiv<193>sa ç
(the wearer of the skin of Gaj<193>sura as his dress), Gajaghna (the ç
killer of Gaj<193>sura) and so on.
@NT = Gajendra-mok<218>a
@N1 = (`liberation of the king of elephants')
One of the most famous episodes in the mythological literature of ç
the Hindus is the story of the liberation of Gajendra or the elephant ç
king from the death grip of a crocodile.
Indradyumna, the king of the P<193><207><195>yan country once ignored ç
the great sage Agastya and was cursed by him to be born as an elephant. ç
Consequently he reincarnated as Gajendra, the king of the elephants ç
in the region of the Trik<220><219>a-parvata (a mountain with three ç
peaks). On a hot day in summer he went to a lake, along with all his ç
tribe and was enjoying himself. At that time a crocodile caught his ç
foot and started dragging him into water. All the heroic efforts of ç
Gajendra and his herd to be freed fromits clutches came to a nought ç
and he started collapsing. At that time, he remembered the Lord Vi<218><207>u ç
and prayed to him intensely. The Lord arrived there on his mount Garu<195>a, ç
discharged his famous discus-weapon, the Sudar·ana, thereby killing ç
the crocodile and thus liberating the elephant king.
This episode (vide Bh<193>gavata 8.4 ) is now well-known as `Gajendra-mok<218>a' ç
and has supplied the core material for many a devotional composition, ç
depicting `<193>rta-bhakti' or `devotion of the distressed'.
The prayer of Gajendra, spread over 31 verses (8.3.2-32) contains ç
not only high philosophy of advaita but also extreme devotion. The ç
ceremonial recitation of this section is common among the devotees ç
of Vi<218><207>u.
The chief lesson of this section is that no disrespect should ever ç
be shown to the devotees of the Lord.
See also <MS>INDRADYUMNA<D>.
@SPACE = 
@NT = gambling
See <MS>DY<188>TA<D>.
@SPACE = 
@NT = ga<207>a 
@N1 = (`group')
This word has been used in several senses, often as a technical term ç
also. The most general meaning is `an assemblage or a group.'
In the pur<193><207>as the word is widely used to indicate the pramatha-ga<207>a, ç
the group of demi-gods, the associates of <185>iva. Ga<207>apati or ç
Ga<207>e·a, the famous and popular deity of the Hindu pantheon, is ç
their leader.
Sometimes, the pur<193><207>as also mention `ga<207>adevat<193>s,' ç
special classes of deities. They are 422 in number distributed among ç
nine classes as follows: °dityas (12), Vi·vedevas (10), Vasus (8), ç
Tu<218>itas (36), °bh<193>svaras (64), Anilas (49), Mah<193>r<193>jikas ç
(220), S<193>dhyas (12) and Rudras (11).
In the military science it indicates one of the four formations of ç
an armed force the proportion of the four a<209>gas or limbs being ç
as follows†
27 elephants: 27 chariots: 81 horses: 135 foot-soldiers.
The nak<218>atras or groups of lunar mansions are also divided into ç
ga<207>as suchasDevaga<207>a, (A·vin<200>, M<216>ga·iras etc.), ç
Naraga<207>a (Bhara<207><200>, °rdr<193> etc.) and R<193>k<218>asa-ga<207>a ç
(K<216>ttik<193>, Citr<193> etc.). This grouping helps the astrologers ç
to match the horoscopes of the boy and the girl for marriage.
@SPACE1 = 
In Sanskrit prosody, eight ga<207>as, each  comprising  three  syllables,  are ç
recognised. By the permutation and combination of these, several metres ç
are obtained. For instance, the `ya-ga<207>a' has three syllables†one ç
laghu (short) and two gurus (long). Similarly the other ga<207>as ç
like ma-ga<207>a, ta-ga<207>a, ra-ga<207>a and so on, are also defined.
The word is also used in Sanskrit grammar to indicate the groups of ç
certain padas or words (like gaura and utsa) as also dh<193>tus or ç
verbal roots (like bh<220>-<193>di, ad-<193>di and so on). They have ç
their ownutility in the various grammatical processes.
`Ga<207>a' is also a term signifying a certain type of courts administering ç
the laws of Hindu republics.
@NT = Ga<207>apati
@N1 = (`lord of the groups [of deities]')
Ga<207>apati or Ga<207>e·a, also known as Vin<193>yaka, is perhaps, ç
the most popular of the Hindu deities worshipped by all sections of ç
the Hindus. No undertaking, whether sacred or secular, can get started ç
without first honouring and worshipping him. This is understandable ç
and highly desirable, since he is said to be the lord of obstacles ç
(Vighne·vara or Vighnar<193>ja). However, what is not understandable ç
and certainly not very agreeable is his repulsive origin and grotesque ç
form! Even for those who admire Lord <185>iva's skill in the surgical ç
art of head-transplantation, it becomes rather difficult to admire ç
the end-product! Once we successfully manage to delve into the mysteries ç
of this symbolism our repugnance will give rise to respect and respect ç
to reverence and worship.
@SPACE1 = 
Notwithstanding the fact that the Ga<207>apati referred to in the ç
famous <184>gvedic mantras, `ga<207><193>n<193><221> tv<193> ga<207>apati<221> ç
hav<193>-mahe...' (2.23.1) and `ni<218>u s<200>da ga<207>apate...' ç
(10.112.9) and the Ga<207>apati we worship today arestrangers to ç
each other, all unbiased scholars agree that the seeds of the Ga<207>apati ç
concept are already there in the <184>gveda itself. In the subsequent ç
centuries, this concept has passed through the mills of the epics ç
and the pur<193><207>as to produce the Ga<207>apati as we know him ç
today. In any community, the development of the concept of God and ç
the modes of his worship are as much the products of geographical, ç
historical and cultural factors as of mystic experience and spiritual ç
realizations of the highly evolved persons. It is quite reasonable ç
to suppose that the `Ga<207>apati-Brahma<207>aspati' of the<184>gveda ç
gradually got metamorphosed into the deity, `Gajavadana-Ga<207>e·a-Vighne·vara.'
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
The <184>gvedic deity `Ga<207>apati-Brahma-<207>aspati'†also called ç
B<216>haspati and V<193>caspati†manifests himself through a vast mass ç
of light. He is golden-red in colour. The battle axe is an important ç
weapon of his. Without his grace no religious rite can succeed. He ç
is always in the company of a group (ga<207>a = a group) of singers ç
and dancers. He vanquishes the enemies of gods, protects the devoted ç
votaries and shows them the right way of life.
Another class of <184>gvedic deities, known as the Maruts or Marudga<207>a, ç
described as the children of Rudra, also have similar characteristics. ç
In addition, they can be malevolent towards those who antagonise them ç
and can cause destruction like the wild elephants. They can put obstacles ç
in the path of men if displeased and remove them when pleased. They ç
are independent, not subject to any one's sovereignty (Ar<193>jana= ç
Vin<193>yaka).
A perusal of these two descriptions will perforce lead us to the obvious ç
conclusion that Ga<207>apati is the metamorphosed form of the B<216>haspati-Marudga<207>a ç
deities. There is nothing strange in this, especially if we can recognize ç
the transformations thathave taken place among the various Vedic ç
deities, as they were gradually absorbed among the gods of the later ç
Hindu pantheon. The once all-important and all-powerful Indra was ç
demoted to the rank of a minor deity ruling over one of the quarters. ç
His lieutenant Vi<218><207>u was elevated to the central place in ç
the Trinity. Rudra, the terrible, became <185>iva the auspicious. ç
Many other deities like Dyaus, Aryaman and P<220><218>an were quietly ç
despatched into oblivion!
Despite the fact that Ga<207>apati is a highly venerated and all-important ç
deity, his `head' has often been a mystery for others. No doubt, our ç
pur<193><207>as have easily `solved' this problem, each in its own ç
way. But this has satisfied neither the layman nor the scholar.
It will be extremely interesting to bring together, though in brief, ç
all the stories about the origin of this wondrous deity:
@NO = 1)
@NOK = At the request of the gods who wanteda deity capable of removing ç
all obstacles from their path of action and fulfilment, <185>iva himself ç
was born of the womb of P<193>rvat<200> as Gaj<193>nana.
@SPACE1 = 
@NO = 2)
@NOK = Once P<193>rvat<200>, just for fun, prepared an image of a ç
child with an elephant's head, out of the unguents smeared over her ç
body and threw it into the river Ga<209>g<193>. It came to life. Both ç
Ga<209>g<193>, the guardian deity of the riverand P<193>rvat<200>, ç
addressed the boyas their child. Hence he is known as Dvaim<193>tura, ç
`one who has two mothers'.
@SPACE = 
@NO = 3)
@NOK = P<193>rvat<200> prepared the image of a child out of the scurf ç
from her body, endowed him with life and ordered him to stand guard ç
before her house. When <185>iva wanted to enter the house he was rudely ç
prevented by this new gatekeeper. <185>iva became `Rudra' and got ç
him beheaded. Seeing that P<193>rvat<200> was inconsolable owing to ç
this tragedy that befell her `son' and not finding the head of the ç
body anywhere†meanwhile one of the goblins of <185>iva had gourmandized ç
it!†he got an elephant's head, grafted it on to the body of the boy ç
and gave him life. To make amends for his `mistake,' <185>iva appointed ç
this new-found son as the head of all his retinues, who thus became ç
`Ga<207>apati'.
@SPACE = 
@NO = 4)
@NOK = He sprang from <185>iva's countenance which represents the ç
principle of ether (<193>k<193>·atattva). His captivating splendour ç
made P<193>rvat<200> react angrily and curse him, resulting in his ç
uncouth form!
@SPACE = 
@NO = 5)
@NOK = Ga<207>e·a was originally K<216><218><207>a himself in the ç
human form. When <185>ani, the malevolent planet spirit gazed at him, ç
his head got separated and flew to Goloka, the world of K<216><218><207>a. ç
The head of an elephant was subsequently grafted on the body of the ç
child.
Equally interesting are the other myths about his adventures: He lost ç
one of his tusks in a fight with Para·ur<193>ma, which he successfully ç
used as a stylus to write the epic Mah<193>bh<193>rata dictated ç
by the sage Vy<193>sa. He tactfully won the race against his brother ç
Skanda by circumambulating his parents and declaring that it was equivalent ç
to going round the worlds. He thus won the hands of two damsels <184>ddhi ç
and Siddhi. He cursed the moon to wax and wane, since the latter derisively ç
laughed at him when he was trying to refill his burst belly with the ç
sweets that had spilled out. He vanquished the demon Vighn<193>sura ç
and successfully brought him under his subjugation.
There is no gainsaying the possibilities of man developing the concept ç
of God and faith in him as a result of his experiences through the ç
various vicissitudes of life which prove his helplessness. He often ç
disposes, what he proposes. Such a God must needs be all powerful. ç
If he is pleased, all the obstacles in our path will be removed. If ç
displeased, He may thwart our efforts and make them infructuous. Hence ç
the paramount need to appease Him and please Him.
@SPACE1 = 
What could be the form of this almighty God? For a simple aboriginal ç
living in a group (= ga<207>a) near a forest or a mountain, the mighty ç
elephant might have provided the clue. This might have led to the ç
worship of an elephant-like God. He being the pati (= Lord) of the ç
ga<207>a (clan or group) might have obtained the name Ga<207>apati. ç
As the group became more refined and cultured, this Elephant God might ç
have been transformed into the present form.
However plausible or attractive this hypothesis may be, it is at best ç
a guesswork, if not an invention! Since Ga<207>apati had gained de ç
facto recognition in the hearts of millions of votaries, over several ç
centuries, the pur<193><207>as rightly struggled to make it de jure! ç
True, theyhave given very confusing accounts. Nevertheless they have ç
succeeded in fusing together the votaries by giving them a scriptural ç
or authoritative base. There is certainly no contradiction or confusion ç
in the accounts as far as the worship and its results are concerned.
It is a favourite pastime of some Western scholars and their Indian ç
counter-parts to `discover' a Dravi<195>ian base for many interesting ç
developments in our cultural and religious life and then to `unearth' ç
the further fact of the white-skinned °ryan `conquerors' graciously ç
and condescendingly absorbing these, tactfully elevating the same ç
to `higher' levels all the while. This has naturally led to a vigorous ç
reaction and these `reactionaries' go the whole hog to `prove' it ç
the other way round! When our Ga<207>apati is caught in the web of ç
such controversies one may be driven to the ridiculous conclusion ç
that he is not an °ryan deity at all, but, most probably, imported ç
from Mongolia! It is therefore better to play safe, rescue our deity ç
from embarrassing situations and get the best out of him for our spiritual ç
life.
The most commonly accepted form of Ga<207>apati depicts him as red ç
in colour and in a human body with an elephant's head. Out of the ç
two tusks, one is broken. He has four arms. Two of the arms hold the ç
p<193>·a (noose) and a<209>ku·a (goad). The other two are held in ç
the abhaya and varada mudr<193>s. The belly is of generous proportions ç
and is decorated with a snake-belt. There is also a yaj<210>opav<200>ta ç
(sacred brahminical thread), either of thread or of serpent. He may ç
be seated in padm<193>sana (lotus-posture). When the belly does not ç
permit this, the right leg may be shown bent and resting on the seat.
Apart from beautiful robes and ornaments, he wears a lovely carved ç
crown.
The trunk may be turned to the left or to the right.
He is normally seen helping himself to liberal quantities of modaka ç
(a kind of sweet).
A mouse, of ridiculously small proportions, is seen near him, nibbling ç
at his share of the sweets, hoping perhaps, to gain enough strength ç
to carry his master!
A third eye may sometimes be added on the forehead, in the centre ç
of the eyebrows. The number of heads may be raised to five. The arms ç
may vary from two to ten. Lotus, pomegranate, water-vessel, battle-axe, ç
lute, broken tusk, sugarcane, ears of paddy, bow and arrow, thunderbolt, ç
rosary, book†these are some of the other objects shown in the hands. ç
His <185>aktis are often shown with him as sitting on his lap. Sometimes ç
two <185>aktis, <184>ddhi* and Siddhi, are also shown.
Let us now make an attempt at unravelling this symbology.
`Ga<207>a' means category. Everything that we perceive through our ç
senses or grasp through our mind can be expressed in terms of kind, ç
of category. The principle from which all such categories have manifested ç
themselves is Ga<207>apati, the Lord of categories. In effect, it ç
means the origin of the whole creation, God himself.
A common Sanskrit word to denote the elephant is `Gaja'. Hence the ç
name Gaj<193>nana or Gajamukha (`elephant-faced') for Ga<207>apati. ç
But the word `Gaja' has a much deeper connotation. `Ga' indicates ç
`gati', the final goal towards which the entire creation is moving, ç
whether knowingly or unknowingly; `ja' stands for `janma', birth or ç
origin. Hence `Gaja' signifies God from whom the worlds have come ç
out and towards whom they are progressing, to be ultimately dissolved ç
in him. The elephant head is thus purely symbolical  and  points  to  this  truth. ç
Another factor we observe in creation is its two-fold manifestation ç
as the microcosm (s<220>k<218>m<193><207><195>a) and the macrocosm ç
(brahm<193><207><195>a). Each is a replica of the other. They are ç
one in two and two in one. The elephant head stands for the macrocosm ç
and the human body for the microcosm. The two form one unit. Since ç
the macrocosm is the goal of the microcosm, the elephant part has ç
been given greater prominence by making it the head.
@SPACE1 = 
Perhaps, the boldest statement concerning philosophical truths ever ç
made is contained in that pithy saying of the Ch<193>ndogya Upani<218>ad ç
(6.8.7): `tat-tvam-asi', `That thou art'. It simply means: `You, the ç
apparently limited individual, are, in essence, the Cosmic Truth, ç
the Absolute.' The elephant-human form of Ga<207>apati is the iconographical ç
representation of this great Ved<193>ntic dictum. The elephant stands ç
for the cosmic whereas the human stands for the individual. The single ç
image reflects their identity.
Among the various myths that deal with Ga<207>apati's origin, the ç
one that attributes it to the scurf or dirt taken out of her body ç
by P<193>rvat<200> seems to be the most widely known, and considered ç
as odd and odious. It is therefore worthwhile to delve a little deeper ç
into this mystery.
One of the epithets by which Ga<207>apati is well-known and worshipped ç
is `Vighne·vara' or `Vighnar<193>ja' (`the Lord of obstacles'). He ç
is the lord of all that obstructs or restricts, hinders or prevents. ç
With the various grades and shades of the powers of obstruction under ç
his control, he can create a hell of trouble for us if he wants! In ç
fact, according to the mythological accounts, the very purpose of ç
his creation was to obstruct the progress in the path of perfection!
@SPACE1 = 
How does he do it? If he is not appeased by proper worship, all undertakings, ç
whether sacred or secular, will meet with so many obstacles that they ç
will simply peter out. This is to show that nothing can succeed without ç
his grace. If he is pleased by worship and service, he will tempt ç
his votaries with success and prosperity (siddhi and <216>ddhi) the ç
very taste of which can gradually lead them away from the spiritual ç
path. Why does he do it? To test them thoroughly before conferring ç
upon them the greatest spiritual boon of mok<218>a. Being the master ç
of all arts and sciences, and the repository of all knowledge, He ç
can easily confer success or perfection in any of these. However, ç
he is unwilling to give spiritual knowledge leading to the highest ç
spiritual experience, lest it should appear easy of achievement in ç
the eyes of men. Hence the severity of the test. The path of the good ç
is fraught with  innumerable  obstacles,  `·rey<193><221>si bahuvighn<193>ni.' ç
Only the very best of heroes, who can brave the roughest of weathers, ç
deserve to be blessed with it. Human beings by nature are inclined ç
towards the enjoyments of the flesh and intoxications of power and ç
pelf. It is only one in a million that turns towards God. Among many ç
such souls, very few survive the struggles and reach the goal. (vide ç
G<200>t<193>7.3)
When compared to the highest spiritual wisdom, which alone is really ç
worth striving for, even <216>ddhi and siddhi (success and prosperity) ç
are like impurities, mala, as it were. Since Ga<207>apati's consorts ç
are <184>ddhi and Siddhi (personifications of the powers of success ç
and prosperity), he, their spouse, has been described as created out ç
of P<193>rvat<200>'s bodily scurf.
Again the word `mala' need not have any odium about it. If <185>iva ç
represents Paramapuru<218>a, the Supreme Person, P<193>rvat<200> stands ç
for Param<193> Prak<216>ti, Nature Supreme, considered as his power, ç
inseparable from him. She is, in the language of philosophy, M<193>y<193>prak<216>ti, ç
comprising the three gu<207>as†sattva, rajas and tamas. Sattva is ç
stated to be pure and, as compared to it, rajas and tamas are said ç
to be `impure'. Since creation is impossible out of pure sattva, even ç
as pure gold does not lend itself to be shaped into ornaments unless ç
mixed with baser metals, it has got to be mixed with rajas and tamas ç
to effect it. This seems to be the import of the story of the `impure' ç
substances being used by Mother P<193>rvat<200> to shape Ga<207>apati.
@SPACE1 = 
Let us now try to interpret the other factors involved in the symbology ç
of this god. His ears are large, large enough to listen to the supplications ç
of everyone, but, like the winnowing basket, are capable of sifting ç
what is good for the supplicant from what is not. Out of the two tusks, ç
the one that is whole stands for the Truth, the One without a second. ç
The broken tusk, which is imperfect, stands for the manifest world, ç
which appears to be imperfect because of the inherent incongruities. ç
However, the manifest universe and the unmanifest unity are both attributes ç
of the same Absolute. The bent trunk is a representation of O<209>k<193>ra ç
or pra<207>ava which being the symbol of Brahman, the Absolute, is ç
declaring as it were that Ga<207>apati is Brahman Itself. His large ç
belly indicates that all the created worlds are contained in him.
The p<193>·a (noose) stands for r<193>ga (attachment), and the a<209>ku·a ç
(goad) for krodha (anger). Like the noose, attachment binds us. Anger ç
hurts us like the goad. If God is displeased with us, our attachments ç
and anger will increase, making us miserable. The only way of escaping ç
from the tyranny of these is to take refuge in God. Or it can mean ç
that it is far safer for us to surrender our attachment and anger ç
to him. When they are in his hands, we are safe!
@SPACE1 = 
How we wish that Lord Ga<207>apati had chosen a big bandicoot as his ç
mount. The fact, however, is otherwise and that privilege has been ç
conferred on a small mouse! The word m<220><218>aka (= mouse) is derived ç
from the root `mu<218>' which means `to steal'. A mouse stealthily ç
enters into things and destroys them from within. Similarly egoism ç
enters unnoticed, into our minds and quietly destroys all our undertakings. ç
Only when it is controlled by divine wisdom, it can be harnessed to ç
useful channels. Or, the mouse that steals, can represent love that ç
steals the human hearts. As long as human love is kept at the low ç
level, it can create havoc. Once it is directed towards the Divine, ç
it elevates us. The mouse that is wont to see the inside of all things ç
can stand for the incisive intellect. Since Ga<207>apati is the lord ç
of the intellect, it is but meet that he has chosen it as his vehicle.
@SB = Icons of Ga<207>apati
There are several varieties of Ga<207>apati icons available in our ç
temples and archaeological monuments. Whether the number is 71, 50, ç
31 or 21, it is certain that there are several aspects of this deity. ç
Only a few of them can be dealt with here.
`B<193>laga<207>apati' and `Taru<207>aga<207>apati' images depict ç
him as a child and a young man, respectively. `Vin<193>yaka' is shown ç
with four arms holding the broken tusk, goad, noose and rosary. He ç
holds the sweet modaka in his trunk. He may be standing or seated. ç
`Herambaga<207>apati' has five heads, ten hands, three eyes in each ç
face and rides on a lion. `V<200>ravighne·a' exhibits the martial ç
spirit with several weapons held in his ten hands. `<185>aktiga<207>apati,' ç
several varieties of which are described in the tantras, is shown ç
with his <185>akti, called variously as Lak<218>m<200>, <184>ddhi, ç
Siddhi, Pu<218><219>i and so on. Worship of this aspect is said to ç
confer special powers or grant the desired fruits quickly.
One of the varieties of this `<185>akti- ga<207>apati' is called `Ucchi<218><219>aga<207>apati,' ç
the Ga<207>apati associated with unclean things whose worship belongs ç
to V<193>m<193>c<193>ra (`the left-handed path,' i.e., the heterodox ç
and unclean path) and said to give quick results. There is nothing ç
to dread or recoil in this concept. Dirty things are as much a part ç
of nature as clean things, but, do not scavengers and doctors handle ç
them in a hygienic way and serve the people? Are not all people obliged ç
to be scavengers in varying degrees? Why not do it reli-giously, as ç
an act of service and worship? Nature converts clean things into unclean ç
things and vice versa. Making Ga<207>apati preside over it and handle ç
dirt scientifically and religiously can also be a spiritual discipline. ç
This seems to be the philosophy behind this concept.
`N<216>ttaga<207>apati' is a beautiful image showing him as dancing. ç
It seems once Brahm<193> met Ga<207>apati and bowed down to him with ç
great devotion and reverence. Being pleased with this, Ga<207>apati ç
started dancing gracefully. That is why Ga<207>apati is declared to ç
be the master of the arts of music and dancing.
`Varasiddhi Vin<193>yaka' is the aspect worshipped during the famous ç
Ga<207>e·a Caturth<200> festival. He is said to be a celibate.
Ga<207>apati is sometimes depicted as a <185>akti (female deity) under ç
the names of Ga<207>e·<193>n<200>, Vin<193>yak<200>, <185><220>rpakar<207><200>, ç
Lamba-mekhal<193> and so on.
@SPACE1 = 
Ga<207>apati is worshipped not only in images but also in li<209>gas, ç
·<193>lagr<193>mas, yantras (geometrical diagrams) and kala·as (pots ç
of water). Ga<207>apati ·<193>la-gr<193>mas however, are very rare. ç
The Svastika is also accepted as a graphic symbol of Ga<207>apati.
Temples and shrines dedicated to Ga<207>apati are very numerous. They ç
are spread all over the country. He appears in the campuses of temples ç
of most other deities also.
@NT = Ga<207>apati Upani<218>ad
Ga<207>apati or Ga<207>e·a is an extremely popular deity in Hinduism. ç
Three minor Upani<218>ads deal with him, this being one of them. It ç
belongs to the Atharvaveda.
Comprising 19 sections it is mostly in prose, interspersed here and ç
there, with verses in the ·loka metre.
The first two verses identify Ga<207>apati with Brahm<193>, Vi<218><207>u, ç
and Mahe·vara, responsible for creation, preservation and destruction ç
of this world. He is also Brahman and °tman.
He is <216>ta and satya, the cosmic order and truth.
The fourth section prays to him for protection, not only of the teacher ç
and the disciple but also of all things in all directions. Then only ç
can we live here safely and happily.
The next verse identifies him with speech, consciousness and bliss. ç
In fact he is the Brahman, the one without a second.
The sixth section describes him as responsible for creation, preservation ç
and dissolution of the world. He is also identified with the five ç
elements in the created world, like the earth and water. He is the ç
four aspects of speech like par<193> and pa·yant<200>. He is beyond ç
the three well-known gu<207>as, the three bodies, and the three aspects ç
of time. He is the deity presiding over the m<220>l<193>dh<193>ra ç
centre. It is upon him that the yogis meditate.
The next three verses describe the Ga<207>apati mantra. Ga<207>aka ç
is the sage who discovered the mantra. `Ga<221>' is the seed letter; ç
and `g<193><221>' should be used for purposes of ny<193>sa (purificatory ç
process for the limbs of the body). The letter `la<221>' must be used ç
in the p<220>j<193> with five items. The mantra itself is `O<221> ç
ga<207>apataye nama<199>.'
@SPACE1 = 
The tenth verse contains the famous Ga<207>e·a-g<193>yatr<200>-mantra:
@P1 = ekadant<193>ya vidmahe<R>ç
vakratu<207><195><193>ya dh<200>mahi<R>ç
tanno danti<199> pracoday<193>t<F49P11M>f<F255P255D>
`We know him who has only one tusk. We meditate upon him with a bent ç
trunk.May he, the Lord with tusks (i.e., Ga<207>apati), impel (us ç
in the right direction, i.e., towards himself).'
The next four verses†11th to the 14th describe Ga<207>apati's form ç
and attri-butes to facilitate meditation:
He has one (unbroken) tusk and four hands, holding the noose and the ç
goad in two, the other two exhibiting the poses of granting boons ç
and protection. His complexion is red all over. He is wearing red ç
dress and flowers. He is the origin of the universe. Yet, he is the ç
all-merciful god, especially towards his votaries.
One who meditates on him thus, is the best of yogis.
Section sixteen describes the effects and fruits of knowing and realising ç
this science related to Ga<207>apati. Freedom from sins and attaining ç
the four ends of life (puru<218><193>rthas) are the most prominent ç
among them.
This spiritual wisdom must be taught only to a worthy disciple and ç
never to others.
The last section describes the various ritualistic processes meant ç
to be adopted by those who have specific desires to be fulfilled. ç
Attaining oratory, scholarship, freedom  from  fear,  obtaining  fame, ç
destruction of obstacles, gaining the power of a mantra†these are ç
some of the things mentioned.
The Upani<218>ad concludes with the statement that one becomes all ç
knowing by a knowledge of this science.
See also <MS>GAØAPATI<D> and <MS>UPANI<186>ADS.
@SPACE = 
@NT = G<193><207>apatyas
@N1 = (`those following the cult of Ga<207>apati')
@SPACE = 
Ga<207>apati has been one of the most popular and important of the ç
deities of the Hindu pantheon. The G<193><207>apatyas were members ç
of a powerful sect that considered Ga<207>apati as the Supreme God. ç
The sect might have originated during the seventh century <MS>A.<|>D.<D> ç
It became powerful around the tenth century and declined later.
The Ga<207>e·apur<193><207>a and the Ga<207>e·ag<200>t<193> are ç
the basic works accepted by this cult.
This cult envisages the worship of five kinds of Ga<207>apati along ç
with their <185>aktis or spouses. They are: Ucchi<218><219>a-Ga<207>apati, ç
Mah<193>-Ga<207>apati, <188>rdhva-Ga<207>apati, Pi<209>gala-Ga<207>apati ç
and Lak<218>m<200>- Ga<207>apati.
Out of these, worship of the first aspect clearly belongs to the V<193>m<193>c<193>ra ç
cults and is against the Vedic traditions.
Later on, the G<193><207><193>patyas got divided into six separate ç
sects.
<185>a<209>kara (<MS>A.<|>D.<D> 788-820) is said to have converted ç
most members of the sect to Vedic practices.
@NT = Ga<207><195>abheru<207><195>a
The Ga<207><195>abheru<207><195>a, a doubleheaded eagle, has been ç
the State symbol of many a royal dynasty, especially in South India. ç
Prominent among them are the emperors of Vijayanagara and the kings ç
of Mysore. It continues to be so, of the Karnataka State even now.
According to the highly sectarian accounts of the pur<193><207>as, ç
Vi<218><207>u as Narasi<221>ha was conquered by <185>iva as <185>arabha ç
(an animal more fierce than thelion). Then Vi<218><207>u took the ç
form of Ga<207><195>abheru<207><195>a and subdued <185>iva in the ç
guise of <185>arabha!
The bird Supar<207>a of the <184>gveda may be an early edition of ç
this bird-monster.
The Ga<207><195>abheru<207><195>a symbol has been traced to the Indus ç
Valley civilisation, at Mohenjo D<193>ro and later found at Tak<218>a·il<193> ç
(Taxila) also.
The well-known folk-tale poem, the Pa<210>catantra, mentions this ç
bird in one of its tales.
In  the  village  Ba<202><202>ig<193>ve  in  the Shimoga district ç
of Karnataka, there is a pillar ofthe C<193><202>ukyan era (<MS>A.<|>D.<D> ç
1047) depicting the deity Bheru<207><195>e·vara (deified Ga<207><195>abheru<207><195>a) ç
along with an edict.
The bird†according to the archaeo- logists and historians†signifies ç
peace, progress and power.
@NT = ga<207><195>ak<193>la
@N1 = (`inauspicious time')
@SPACE = 
@SPACE = 
In Hindu astrology, the birth of a baby at certain times considered ç
as inauspicious forebodes evil to its parents, One such inauspicious ç
time is called `ga<207><195>ak<193>la'.
For instance, the first three gha<219>ik<193>s (1 gha<219>ik<193> ç
= 24 minutes) when the three nak<218>atras A·vin<200>, (the stars ç
beta and gamma, arietis), Makha (the stars alpha, eta, gamma, zeta, ç
mu and epsilon leonis) and M<220>l<193> (the stars lambda and upsilon ç
scorpii) are present, are inauspicious. If it occurs in the night ç
and the baby is born at that time it forebodes evil for the mother.
@SPACE = 
@NT = Ga<207><195>ak<200>
@N1 = (`that [which has flown] from the cheeks')
@SPACE = 
Ga<207><195>ak<200> is the same as the modern river Ga<207><195>ak. ç
It gets its name from the fact†as per the accounts given in the Var<193>hapur<193><207>a ç
(ch. 144)†that it was formed from the sweat on the cheeks of Mah<193>vi<218><207>u ç
(ga<207><195>a = cheek). Other names are <185><193>lagr<193>m<200>, ç
Saptaga<207><195>ak<200> and N<193>r<193>ya<207><200>.
@SPACE1 = 
It rises in the Him<193>layas, passes through Nepal and joins the ç
river Ga<209>g<193> at Sonepur in the Muzaffarpur district ofBihar. ç
Its total length is 300 kms. (192miles).
It is said that when the river goddess asked for a boon, Vi<218><207>u ç
said he would always reside in her in the form of ·<193>lagr<193>ma ç
stones. The part of the river in Nepal near Muktin<193>tha abounds ç
in these stones, considered as emblems of Vi<218><207>u and extremely ç
holy.
@NT = ga<207><195><193>nta
@SPACE = 
@SPACE = 
Belief in astrology, the effect of the movement of the heavenly bodies ç
like the planets and the stars on human life, is a common phenomenon ç
seen among all the people of the world. The word `ga<207><195><193>nta' ç
used in Hindu astrology, is a technical word indicating certain inauspicious ç
timings and combinations. They exert inauspicious influences on birth, ç
marriage, starting on a journey or an invasion andother similar incidents ç
in life. For instance, the conjunction of the 15th tithi with  pratipad  for  two  gha<219>ik<193>s  (48 ç
minutes), the conjunction of Kark<193><219>aka (Cancer) and Si<221>ha ç
(Leo) for half a gha<219>ik<193> (12 minutes) or the conjunction of ç
the stars Revat<200> and A·vin<200> for four gha<219>ik<193>s (96 ç
minutes) are all ga<207><195><193>nta. These ga<207><195><193>ntas ç
produce evil effects on the child's father or mother and so on. Hence ç
all auspicious undertakings should be avoided during these periods.
@NT = gandha
@N1 = (`smell')
Though its simple meaning is `smell' the word has been used in a more ç
technical sense in the Ved<193>nta philosophy. It is one of the five ç
tanm<193>tras or subtle elements indicating the pure and subtle element ç
of earth (s<220>k<218>ma-p<216>thv<200> or gandhatanm<193>tra).
The word is also used to denote candana or sandal paste used as an ç
unguent in p<220>j<193> or ritualistic worship.
In literature it indicates, in a metaphorical sense, the slightest ç
tinge of a substance or a quality. For instance, in thesentence, ç
`<185>uka did not have even gandhale·a of k<193>ma', it means <185>uka ç
did not have even the least trace of lust.
@NT = Gandham<193>dana
@N1 = <R>ç
(`intoxicating fragrance')
This is the name of one of the four mountains enclosing the central ç
region of the world, according to the accounts given in the Mah<193>bh<193>rata ç
and the pur<193><207>as. It was renowned for the fragrance emanating ç
from its forests, due to the rare herbs in it. It was under the control ç
of Kubera, the king of the Yak<218>as. The P<193><207><195>avas had ç
visited it during their residence in the forests (Vanav<193>sa). It ç
was in the vicinity of this mountain that K<216><218><207>a had killed ç
the demon Naraka.
Gandham<193>dana is also the name of a monkey-general in the army ç
of Sugr<200>va, who fought bravely with Kumbhakar<207>a.
@NT = G<193>ndh<193>ra
The G<193>ndh<193>ra is an ancient country mentioned once in the <184>gveda ç
(1.126.7) as famous for its sheep and their wool.
During the Mah<193>bh<193>rata period it was ruled by the king Subala ç
whose daughter G<193>ndh<193>r<200> had been married to the blind ç
king Dh<216>tar<193><218><219>ra. <185>akuni was his son.
The kingdom might have extended from the shores of the river Sindh<220> ç
(Indus) up to the modern Kabul. According to another view it extended ç
from Jalalabad (inAfghanisthan) toRawalpindi(in Pakistan) and included ç
the Kumar<200> river.
Later on it came under Buddhist influence and its capital was Tak<218>a·il<193> ç
(Taxila). There were flourishing trade links with Magadha (Patna region ç
of modern Bihar).
@SPACE1 = 
G<193>ndh<193>ra is also the third note of the octave in music.
@NT = G<193>ndh<193>r<200>
G<193>ndh<193>r<200> is one of the brightest of the women-characters ç
of the Mah<193>bh<193>rata. She was the eldest daughter of Subala, ç
the king of the country of G<193>ndh<193>ra and the chief queen of ç
Dh<216>tar<193><218><219>ra, the blindprince of Hastin<193>pura. ç
She was the personification of not only wifely virtues but also of ç
virtues in general. It is an irony that Duryodhana, the primary villain ç
of the Kuruk<218>etra war was her son!
She had thirteen brothers and ten sisters. <185>akuni, the master ç
plotter, was her elder brother. All her sisters too had married Dh<216>tar<193><218><219>ra.
Since Dh<216>tar<193><218><219>ra was born blind, she decided to bind ç
her eyes with a wrapper  and  thus  remain  sightless, voluntarily ç
and willingly.
@EMERGENCY = By the grace of <185>iva, whom she had worshipped with ç
great devotion, she had secured the boon of getting one hundred sons.
@EMERGENCY = Since her delivery was very much delayed, the story goes ç
that she forced the foetus out. The sage Vy<193>sa, who arrived there ç
at that time averted the disaster and arranged for the proper care ç
of the same. In course of time one hundred sons and one daughter were ç
born out of that foetus. Duryodhana and Du··<193>sana were the first ç
two sons.
@EMERGENCY = As her sons grew up she noticed with great dismay their ç
animosity towards the P<193><207><195>avas and the planned ill-treatment ç
meted out to them. Her interventions and sage advice had no effect ç
at all upon Duryodhana, the evil genius that he was. She had even ç
taken her own husband to task for his blind infatuation towards their ç
eldest son.
When the war between the P<193><207><195>avas and the Kauravas became ç
inevitable and when Duryodhana approached her for blessings, the reply ç
she gave has now become a classic!
When Duryodhana died in the battle, her heart, as a mother's was shaken ç
and she wanted to curse Yudhi<218><219>ira. This was however prevented ç
by the timely inter- vention of the sage Vy<193>sa.
She consented to live in Hastin<193>pura along with her husband, being ç
well-taken care of, by Yudhi<218><219>ira. Later she repaired to the ç
forest, along with Kunt<200> and Dh<216>tar<193><218><219>ra and perished ç
in a forest fire.
@NT = g<193>ndharva
@N1 = (`pertaining to the<R>ç
Gandharvas')
The dharma·<193>stras declare viv<193>ha or marriage, not as a social ç
contract, but as a sa<221>sk<193>ra, religious sacrament. Of the eight ç
forms of marriage mentioned in them, the first four are the recommended ç
forms. (See <MS> VIV°HA<D> for details.) In the g<193>ndharva viv<193>ha, ç
the boy and the girl decide by themselves to marry and then get the ç
approval of their parents and guardians. The svaya<221>vara system ç
among the k<218>attriya kings belongs to this type. Even in the <184>gveda ç
(10.27.12) there is a mention of this type that was in vogue then.
@NT = Gandharvas
Gandharvas are a class of deities described as the sons of Ka·yapa ç
Praj<193>pati from his wife Ari<218><219><193>. Their number is 12 ç
or 15. Some of them are: Tumburu, H<193>h<193>, H<220>h<220>, Vi·v<193>vasu, ç
Citrasena, Vidy<193>dhara, Par<193>vasu and Vir<193>dha.
In the <184>gveda (9.86.36) the word `Gandharva' has been used to ç
indicate Soma, as the lord of waters.
In the later literature the Gandharvas have been described as celestial ç
musicians (vide Mah<193>bh<193>rata, Sabh<193>-parva, Chapters 8 ç
to 10) in the courts of Yama, Varu<207>a and Kubera. Hence the name ç
Gandharvavidy<193> or G<193>ndharvaveda for music.
@NT = G<193>ndharva-veda
Veda means any science of know-ledge. Since the gandharvas, a class ç
of demigods, were considered experts in the field of music, the science ç
of music including musicology came to be known as G<193>ndharva-veda.
See <MS>SA<177>G®TA<D> for details.
Sometimes a work called G<193>ndharva Veda, comprising 30,000 verses, ç
is believed to have existed as an Upaveda of S<193>maveda. But it ç
is not available now.
@NT = gandha-tanm<193>tra
See <MS>BH<188>TA<D> and <MS>GANDHA<D>.
@NT = G<193>ndh<200>, M. K.
@N1 = (<MS>A.<|>D.<D> 1869-1948)
Mohand<193>s Karamcand G<193>ndh<200>†more well-known as Mah<193>tm<193> ç
G<193>ndh<200> or just G<193>ndh<200>ji†is one of the brightest stars ç
of the freedom movement in India during the first half of the twentieth ç
century. Though his main contribution was in the political field, ç
in the struggle for political freedom, his contribution in the social ç
field was also considerable.
He was born on the 2nd October 1869 at Porbander in Gujarat to Karamcand ç
G<193>ndh<200> and Putal<200>b<193><200>. He had his early education ç
there and at Rajkot, also in Gujarat. Later he went to England and ç
completed higher education getting the Barrister degree. After returning ç
to India he practised as a lawyer at Bombay (now Mumbai) for a couple ç
of years. Then, at the request of a Muslim merchant from South Africa, ç
he went to Durban. There he had the bitter taste of apartheid of the ç
white people and the government. This induced him to organise the ç
Indians there to fight the government for their rights. Thus started ç
his famous civil disobedience movement which later came to be known ç
as `saty<193>graha'. He succeeded to a great extent to restore to ç
the Indians their civil rights.
He returned to India in 1915. He travelled widely all over the country ç
and gradually got involved in various movements wherein he used his ç
new weapon of saty<193>graha effectively. Naturally drawn into the ç
vertex of the struggle for political freedom started by the Indian ç
National Congress, he practically became its undisputed leader very ç
soon. However, when India won freedom, he was the saddest man not ç
only because of the partition of the country but also because of the ç
widespread communal riots.
@SPACE1 = 
He was assassinated on the 30th January 1948 in Delhi, while on his ç
way to his usual prayer meeting.
G<193>ndh<200>j<200> was a staunch believer in God and R<193>man<193>ma ç
was the very breath of his life. In fact, he died with it on hislips. ç
His contribution to the eradication of many social evils like drinking ç
and untouchability was considerable. He advocated education in mother ç
tongue and strongly recommended the integration of vocational training ç
with education. The economic system he recommended for the progress ç
of free India was based primarily on rural life. He laid great stress ç
on the cultivation of basic moral values like ahi<221>s<193> (non-violence), ç
satya (truth), brahmacarya (self-control) and asa<209>graha (non-accumulation ç
of wealth and goods more than what is really necessary) not only in ç
individual life but also in public life. The credit of elevating the ç
political life of the nation (during his times) to much higher levels ç
by importing moral and ethical values into it undoubtedly goes to ç
him.
He remained a devout Hindu throughout his life and was highly critical ç
of the evangelical attitudes and conversion acti-vities of the followers ç
of the Semitic religions.
He was extremely  fond of the Bhagavadg<200>t<193> which he ç
had adopted as the guide book of his life.
His wife Kast<220>rb<193> proved to be a great asset in all his activities.
@NT = G<193><207><195><200>va
@N1 = (`[a bow] made of the hide of a rhinoceros')
The greatest archers found in the Hindu mythological literature are ç
<185>r<200> R<193>ma and Arjuna. If <185>r<200> R<193>ma's bow was ç
known as the Koda<207><195>a, Arjuna's was called the G<193><207><195><200>va.
This bow was made by Brahm<193> (the four faced creator) himself with ç
the hide of a Ga<207><195>a or rhinoceros. (Hence the name G<193><207><195><200>va.) ç
It was handed down to a succession of heroes as follows: Praj<193>pati, ç
Indra, Candra and Varu<207>a.
When Agni, the fire-god, wanted to devour the Kh<193><207><195>ava ç
forest, Varu<207>a lentthe G<193><207><195><200>va bow to Arjuna ç
so that he could protect Agni. Arjuna kept it for
