@NID = 65 years, fought all his battles with it, including the Kuruk<218>etra ç
war.
This  bow was so versatile and powerful that one could fight with ç
one lakh persons at a time!
Agni took it back for Varu<207>a when Arjuna was on his last journey ç
(mah<193> prasth<193>na).
@SPACE = 
@NT = Ga<207>e·a
See <MS>GAØAPATI.
@SPACE = 
@NT = Ga<207>e·a-caturth<200>
@SPACE = 
<$IGanesa>Ga<207>e·a or <$IGanapati>Ga<207>apati, the elephant-faced ç
<$IGod>god, is an extremely popular deity, not only with the masses ç
but also with the classes. Being <$IVighnesvara>Vighne·vara†Lord of ç
and destroyer of obstacles†he is eagerly sought by the classes. The ç
masses try to propitiate him to fulfil their needs, since he is `<$IVarada>Varada' ç
and `<$ISiddhida>Siddhida,' the giver of boons and success in undertakings. ç
No venture can be started without worshipping him first. He is also ç
the <$IGod>god of knowledge and wisdom as well as literature and fine-arts. ç
Hence the supreme importance of the <$IGanesacharturthi-vrata>Ga<207>e·a-caturth<200>-vrata.
The <$IPurana>pur<193><207>as are replete with his stories, that describe ç
his origin or adventures, or that contain philosophical disquisitions ç
delving into his symbology. <$IPundit>Pundits have been battling over ç
the years to solve the riddles concerning the origin or evolution ç
of the enigmatic deity. We are however interested in harnessing his ç
grace and powers for the benefit of the devotees  by  describing  ç
some  relevant details concerning the <$IVrata/s>vrata which has been ç
so highly extolled in the <$IHindu/s>Hindu religious works.
The main time for the performance of <$IPuja>p<220>j<193> to <$IGanesa>Ga<207>e·a ç
on this sacred day is noon. A clay image, beautifully painted, is ç
to be brought and installed on a suitable altar, and decorated. After ç
the usual preliminary rites, <$IPranapratistha>pr<193><207>aprati<218><219>h<193> ç
(`infusing life into the image' or `invoking the presence of the deityinto ç
the image') has to be done withappropriate <$IMantra>mantras. This ç
should be followed by worship with sixteen <$IUpacaras>upac<193>ras ç
or modes of showing honour. Offering of <$IDurva>d<220>rv<193> (grass) ç
tendrils and <$IModaka>modaka (a kind of sweet supposed to be dear ç
to <$IGanesa>Ga<207>e·a), twenty-one in number, is a very important ç
part of this <$IPuja>p<220>j<193>. This may symbolically teach us ç
that we have to offer in all humility (represented by the <$IDurva>d<220>rv<193> ç
grass), all the good things of life that give us pleasure and happiness ç
(represented by the <$IModaka>modaka; `<$IModaka>modaka' literally ç
means `that which gives us joy'). The number 21 may stand for the ç
21items in our person viz., <$IJnanendriyas>j<210><193>nendriyas ç
or the five organs of perception, <$Ikarmendriyas>karmendriyas or ç
the five organs of action, the five <$IPrana>pr<193><207>as or vital ç
airs, the five <$IBhutas>bh<220>tas or elements and the mind. Thus ç
the <$IPuja>p<220>j<193> can teach us total dedication and surrender ç
at the feet of Lord <$IGanesa>Ga<207>e·a, who is none other than the ç
highest <$IBrahman>Brahman or the Absolute in that form. The image ç
has to be ceremonially immersed in water after the completion of the ç
<$IVrata/s>vrata.
@SPACE1 = 
In modern times, the image is kept and worshipped for 1<|><P9.5M><$E ç
1/2 > <P255D>days or 2 to 7days or even up to <$IAnantacaturdashi>Anantacaturda·<200> ç
(14th dayof bright half of <$IBhadrapada>Bh<193>drapada) before immersing. ç
It is taken in a procession for the immersion which is done in a well ç
or a tank or a river or the sea.
There is a widespread popular belief that if one sees the <$IMoon>moon ç
on the Ga<207>e·a Caturth<200> day, he will be falsely charged with ç
the commission of a theft or a similar crime. The story of <185>r<200> ç
<$IKrsna>K<216><218><207>a being thus implicated in the theft of the ç
famous gold-yielding gem (<$ISyamantaka>syamantaka) belonging to the ç
<$IYadava>Y<193>dava chieftain <$ISatrajit>Satr<193>jit is cited as ç
an example. (This story appears in the <$IMahabharata>Mah<193>bh<193>rata ç
as also in several <$IPurana>pur<193><207>as such as <$IVayu>V<193>yu, ç
Matsya, Vi<218><207>u and <$IBhagavata>Bh<193>ga-vata.) The ç
problem has also been `solved' by these works, by recommending to ç
such inadvertent `offenders' the recitation of a <$IMantra>mantra* ç
over some water and drinking it.
One more Ga<207>e·a Caturth<200> is mentioned in some <$IPurana>pur<193><207>as, ç
as falling on <$IMagha>M<193>gha ·ukla <$ICaturthi>caturth<200><|>. ç
But it is not being observed now.
@SPACE = 
@SPACE = 
@NT = Ga<207>e·ag<200>t<193>
@N1 = (`the song of Lord Ga<207>e·a')
@SPACE = 
@SPACE = 
The Bhagavadg<200>t<193>, a part and parcel of the immortal epic, ç
the Mah<193>bh<193>rata, has left a very deep impression on the ç
psyche of the Hindu nation. This has, in course of time, given rise ç
to a number of similar works of a didactical nature, either as a part ç
of some pur<193><207>a or even as an independent work.
The Ga<207>e·ag<200>t<193> is one typical example. It is an integral ç
part of the Ga<207>e·a-pur<193><207>a, comprising the eleven chapters† ç
138 to 148†and has 413 ·lokas or verses in all. It is in the form ç
of a dialogue between the king Vare<207>ya and his divine son Gaj<193>nana ç
or Ga<207>e·a.
@SB = Summary of the Contents
A brief summary of the work may now be attempted here.
@S10 = Chapter 1<R>ç
S<193><209>khy<193>rthas<193>rayoga, 69 verses
The king Vare<207>ya requests his son Gaj<193>nana (knowing full well ç
that he is God himself) to expound to him yoga·<193>stra or the science ç
of yoga.
In reply, Gaj<193>nana discounts several concepts normally thought ç
of as yoga and states that true yoga is withdrawing one's mind from ç
the objects of senses and directing it towards the <193>tman within. ç
In this attempt several modes of s<193>dhan<193> like the s<193>dhanacatu<218><219>aya, ç
·rava<207>a (hearing about the <193>tman), manana (reflection of the ç
same) and nididhy<193>sana (meditation), which are useful, are described. ç
The need for a proper guru or spiritual teacher is also stressed.
@S10 = Chapter 2<R>ç
Karmayoga, 43 verses
In reply to the question whether j<210><193>nani<218><219>h<193> (devotion ç
to knowledge) or karmani<218><219>h<193> (devotion to work) is a better ç
path of s<193>dhan<193>, Gaj<193>nana replies that both are equally ç
effective if properly understood and practised. Work done as a duty ç
and without selfish motives is far better than giving up work altogether. ç
When Praj<193>pati created this world along with gods and men, as ç
also the system of the four var<207>as among men, he ordained that ç
all should perform their duties and sustain one another by helping ç
one another. Gaj<193>nana specifically declares that even the liberated ç
ones should work to set an example to the ignorant people, of the ç
world. Towards the end, in reply to another question, he says that ç
it is k<193>ma or desire that impels a man to commitsins and hence ç
exhorts Vare<207>ya to control it.
@S10 = Chapter 3<R>ç
J<210><193>napratip<193>danayoga, 50 verses
Continuing his teaching, Gaj<193>nana declares that he taught this ç
ancient yoga or spiritual wisdom to Vi<218><207>u in the beginning ç
of creation. Through him and a succession of teachers like S<220>rya ç
and Manu it was propagated in this world. To the question how he, ç
of this generation, could teach it to Vi<218><207>u, the ancient divine ç
person, Gaj<193>nana reveals that he is the an<193>di-<200>·vara, ç
the primeval Lord of the universe, who is the origin, the sustenance ç
and the place of dissolution of the whole universe, from whom even ç
Vi<218><207>u and other gods originate!
The ignorant persons worship other deities for petty results and hence ç
are caught in the web of sa<221>s<193>ra or transmi-gration.
Gaj<193>nana declares that the systemof the four var<207>as was evolved ç
by him. He also explains the terms kriy<193> (actions done without ç
selfish desires) and akriy<193> (abandonment of prescribed actions), ç
various yaj<210>as, the importance of approaching a worthy guru and ç
satsa<209>ga (holy company).
@S10 = Chapter 4<R>ç
Dvaidhasa<221>ny<193>sayoga, 37 verses
Now, the king Vare<207>ya raises the question whether karmayoga or ç
karma-sa<221>ny<193>sa is superior. Though both are good and give ç
the same result, Gaj<193>nana opines, that the former is better.
A true karmayogi offers the fruits of all his karmas to God. Hence ç
he is not bound. It is the person who performs desire-motivated actions ç
that is bound and hence suffers.
God never creates karma (action) or kart<216>tva (agency). They are ç
done by the prak<216>ti of three gu<207>as. Those wise ones who know ç
this are the real pa<207><195>itas (men of knowledge) and can get ç
whatever they want.
In reply to another question, Gaj<193>nana describes the nature of ç
true sukha or happiness, as the one rooted in the <193>tman (Self).
@S10 = Chapter 5<R>ç
Yog<193>v<216>ttipra·a<221>san<193>yoga, 27 verses
Gaj<193>nana stresses that yoga is possible only when the mind is ç
purified by the performance of ordained works, but without the desire ç
for the fruits. Such a work is called `akarma'. But, when work is ç
performed with selfish motives and desires, it binds.
The divine teacher then describes in detail, the factors that are ç
not conducive to the practice of yoga like physical diseases, disturbed ç
state of mind, unclean and risky places, very hot or cold seasons ç
and so on. The practitioner of yoga should also avoid going to extremes ç
in the case of food, fasting, sleep or keeping awake.
Renunciation of desires is another important aspect of s<193>dhan<193>.
In answer to two more questions raised by Vare<207>ya, the lord replies ç
that the mind, though difficult to control can be brought round through ç
vair<193>gya (spirit of renunciation) and abhy<193>sa (repeated effort). ç
If a yogi dies before reaching the final goal of life, he will be ç
reborn in the family of yogis, after first enjoying divine pleasures ç
in heaven. He will then continue his spiritual practices.
@S10 = Chapter 6<R>ç
Buddhiyoga, 21 verses
This chapter starts with a description of the twofold prak<216>ti ç
of the Lord†the lower prak<216>ti comprising ten parts (four elements, ç
mind, the sun and the moon and three other aspects); the higher prak<216>ti, ç
viz., the j<200>va or cetana who is in the grip of aha<209>k<193>ra, ç
born out of the attachment to the mind. The whole world is a product ç
of these two prak<216>tis.
People in general are overcome by prak<216>ti and hence bound. However, ç
once in a while, some fortunate soul, purified through the performance ç
of his ordained duties (var<207>a-<193>·rama-dharma) crosses over ç
this prak<216>ti or m<193>y<193>.
After describing how he is present in every object of the created ç
world, Gaj<193>nana declares that even those who worship other gods ç
with desires actually worship him alone. And again, it is he that ç
responds to their supplications through them.
The importance of the final thoughts at the time of death is stressed ç
at theend.
@S10 = Chapter 7<R>ç
Up<193>san<193>yoga, 25 verses
This chapter begins with a short account of the two well-known paths ç
described in the Upani<218>ads†the devay<193>na or arcir<193>dim<193>rga ç
and pit<216>y<193>na or dh<220>m<193>di-m<193>rga. They are the paths ç
leading to the Brahmaloka (the world of Brahm<193>, the creator) and ç
to the Pit<216>loka (the world of manes).
Brahman, the Absolute, is beyond both. It is identical with Gaj<193>nana ç
himself. Those who meditate upon him attain this Brahman and get mukti ç
or liberation.
This meditation is aided by ritualistic worship performed with faith. ç
And, this ritualistic worship can be performed mentally also.
Though sak<193>map<220>j<193> (worship motivated by desires) is permissible, ç
ni<218>k<193>ma- p<220>j<193> (unselfish worship) is more desirable.
Since all the gods are the manifestations of the one God (Gaj<193>nana), ç
it is not proper to dislike other gods even while being devoted to ç
one of them.
A simple mode of mantrajapa (repetition of the divine name) along ç
with its subsidiary processes like the ny<193>sas, is also described.
Towards the end, there is a eulogy of the Pra<207>ava or O<209>k<193>ra.
@S10 = Chapter 8<R>ç
Vi·var<220>padar·anayoga, 25 verses
@EMERGENCY = At the specific request of the king Vare<207>ya, Lord ç
Gaj<193>nana shows him the cosmic form of his, after endowing him ç
with a divine sight. Seeing that cosmic form, Vare<207>ya describes ç
it and also praises the Lord. At his entreaties, the Lord withdraws ç
the cosmic figure and re- assumes his original form. The description, ç
though brief, is very similar to the one given in the Bhagavadg<200>t<193>.
@S10 = Chapter 9<R>ç
K<218>etra-j<210><193>t<216>-j<210>eya-viveka-yoga, 41 verses
Worshipping God with form and contemplating on the Ak<218>ara/Avyakta ç
(God, the formless) are two well-known modes of spiritual discipline. ç
Which one is the better of the two? In reply to this question, Gaj<193>nana ç
replies that both are equally effective. However, the former is easier ç
whereas the latter is extremely hard.
In spiritual life, devotion is everything. Even the well-known sages ç
like Sanaka, <185>uka or N<193>rada became great because of bhakti ç
or devotion. Hence, meditating on the Lord, with steady devotion, ç
results in yoga and through that, attaining him.
Performance of one's svadharma or ordained duties and offering its ç
fruits to the Lord, purifies the mind. Equanimity of mind too is a ç
great help.
Then comes a description of the k<218>etra and the k<218>etraj<210>a. ç
K<218>etra is the physical body as well as the subtle body (the s<220>k<218>ma·ar<200>ra ç
comprising 16 items) (and the j<200>vas too) whereas God is the k<218>etraj<210>a ç
residing in them all.
J<210><193>na  or  knowledge  comprises several items of discipline ç
such as <193>rjava (straight-forwardness), guru·u·r<220><218><193> ç
(ser-vice to the guru), virakti (detachment), equanimity, self-control ç
and so on. This j<210><193>na will ultimately help in the revelation ç
of Brahman, the Absolute.
This is then followed by a nice description of this Brahman which ç
again, is identified with Ga<207>e·vara or Gaj<193>nana himself.
@S10 = Chapter 10<R>ç
Yogopade·ayoga, 23 verses
This chapter starts with a description of three kinds of prak<216>ti†sattva, ç
rajas and tamas†and the way they manifest in the human beings.
Sattva frees a person from the bondage of sa<221>s<193>ra whereas ç
rajas and tamas bind him all the more.
The signs of sattva, of daiv<200> type, are: abhaya (fearlessness), ç
ahi<221>s<193> (non-injury to others), ·auca (purity), apai·unya (absence ç
of calumny), am<193>nit<193> (absence of pride and vanity) and so ç
on.
The characteristics of a person of the <193>sur<200> type, of rajas, ç
are: bragging, arrogance, perverted understanding, short-temper, jealousy ç
and so on.
The qualities seen in a person of the r<193>k<218>as<200> type, of ç
tamas, are: delusion, egoism, vanity, hatred, violence, anger, harming ç
others for nothing, agnosticism, falsehood and many other evil qualities.
Whereas good persons go to heaven after death, the evil-doers go to ç
hell. But both of them come back to this earth again.
Even bhakti or devotion can be of three types according to these gu<207>as. ç
But devotees are always advised to cultivate s<193>ttvic devotion ç
only.
@S10 = Chapter 11<R>ç
Trividhavastunir<220>pa<207>ayoga, 52 verses
In this final chapter, there is a beautiful delineation of three kinds ç
of tapas (austerity), d<193>na (gifts), j<210><193>na (knowledge), ç
karma (action), kart<193> (doer), sukha (happiness) and du<199>kha ç
(unhappiness), according to the three gu<207>as of sattva, rajas and ç
tamas.
Serving the respected elders, perfor-mance of one's ordained duties ç
and worship of gods is tapas of the body. Truthful and sweet speech ç
is tapas of speech. Keeping the mind unexcited and at peace is tapas ç
of the mind.
When this tapas is performed without any desires, it is s<193>ttvika. ç
When done with desires it is r<193>jasika, when practised to harm ç
others or as a show, it is t<193>masika.
D<193>na or gifts when given as per the injunctions of the scriptures ç
to the right person at the right time and place, is s<193>ttvika. ç
When given with selfish motives it is r<193>jasika. If given to those ç
who will dishonour or misuse it, it is t<193>masika.
Similarly there is the three fold distinction in j<210><193>na (knowledge) ç
also. Seeing the Saccid<193>nanda Brahman everywhere is s<193>ttvika ç
j<210><193>na. Seeing the limited j<200>v<193>tman is r<193>jasika ç
j<210><193>na. Mistaking the body for the <193>tman is t<193>masika ç
j<210><193>na.
S<193>ttvika karmas aretheactions ordained by the scriptures, performed ç
without selfish motives and in a way that does not inconvenience others. ç
R<193>jasika karmas are performed as a show without the proper attitude. ç
Foolish and idiotic actions are t<193>masika.
A s<193>ttvika kart<193> or doer, though he does actions rightly, ç
is never egoistic. The r<193>jasika doer is selfish and is subject ç
to constantly changing moods. The t<193>masika doer is always engaged ç
in harming others.
S<193>ttvika sukha or happiness appears to  cause  difficulty  in  the  beginning ç
(because of the disciplines involved in attaining it) but gives bliss ç
at the end. Happiness derived from sense-pleasures results in suffering ç
at the end and hence is  r<193>jasika.  The  t<193>masika  happiness ç
produces delusion and harm.
Then follows a brief explanation of a famous phrase O<221> tat sat. ç
A detailed account of the four var<207>as†br<193>hma<207>as, k<218>attriyas, ç
vai·yas and ·<220>dras†and their duties is given next.
Towards the end there is the specific injunction that this teaching ç
should not be imparted to the unworthy ones but to be protected by ç
all means.
The teaching ends with a detailed phala·ruti or eulogy. There is also ç
the instruction regarding the proper mode of reciting it including ç
the recommendation of certain holy days and holy places.
@SB = Conclusion
A careful perusal of this Ga<207>e·ag<200>t<193> reveals that it ç
is almost an imitation, nay, an adoption, of the celebrated Bhagavad-g<200>t<193>. ç
The topics discussed, the questions raised, the replies given are ç
all very much reminiscent of the G<200>t<193>. The language is elegant ç
and the presentation good. (It is said that there is a Sanskrit commentary ç
too on this work. But not much is known about it.) In some places, ç
it is even more detailed. On the whole, it is a work that deserves ç
a deeper study.
See also <MS>GAØE<185>A-PUR°ØA.<D>
@NT = Ga<207>e·apur<193><207>a
The main purpose of the pur<193><207>as or mythological lore is to ç
bring philosophy and religion to the doors of the masses. They have ç
also played an important role in spreading knowledge†both sacred and ç
secular†and preserve Hindu culture among the common people.
Out of the eighteen Upapur<193><207>as or secondary pur<193><207>as, ç
(all ascribed to the sage Vy<193>sa), the Ga<207>e·apur<193><207>a ç
is listed as the first. It is a big work of 12,000 verses spread over ç
250 chapters. Except for the Ga<207>e·ag<200>t<193>, an important ç
treatise on religion and philosophy, which forms a part of the last ç
portion of the pur<193><207>a, the rest of the work is highly sectarian ç
in character, clearly aimed at spreading the G<193><207>apatya-cult ç
(cult of Ga<207>apati). It abounds in stories of gods, sages and kings, ç
always aimed at glorifying Ga<207>e·a above even the well-known deities ç
<185>iva, Dev<200>, Vi<218><207>u and Brahm<193>!
Incidentally, certain mantras of Ga<207>e·a, vratas or religious observances ç
andworship connected with him are also described.
See also <MS>GAØE<185>AG®T°, PUR°ØAS<D> and <MS>UPAPUR°ØAS<D>.
@NT = Ga<209>g<193>
@N1 = (`one who descended to this earth')
The rivers of a country are its life- line. Hindu India has always ç
looked upon its rivers, not as just physical or natural objects but ç
as divinities, goddesses of prosperity.
Of all the rivers of India, no river has captivated the minds and ç
the hearts of the people more than the river Ga<209>g<193>. For many ç
a Hindu, a bath in it is a life-time's ambition. No religious act ç
can be ceremonially complete without its water being used in some ç
form or the other. Afew drops of its water poured into the mouth ç
of a dying person will remove all the sins. Immersion of the ashes ç
of a dead person's body in it will give him liberation.
@SB8.5 = Ga<209>g<193>, in the Scriptures
Though the river Ga<209>g<193> has been mentioned in the <184>gveda ç
only once (vide Nad<200>stuti 10.75.5 and 6), it is the first in ç
the list. There are references to it in other places also such as ç
the <184>gveda (6.45.31), the <185>atapatha Br<193>hma<207>a (13.5.4.11 ç
and 13) and also the Aitareya Br<193>hma<207>a (39.9). The R<193>m<193>ya<207>a, ç
the Mah<193>bh<193>rata (Anu·<193>sanaparva) and many pur<193><207>as ç
such as the Padma, the N<193>rad<200>ya, the Agni and the Matsya ç
contain hundreds of verses eulogising the greatness and the sanctifying ç
power of the Ga<209>g<193> river. In the Bhagavadg<200>t<193> (10.31) ç
<185>r<200> K<216><218><207>a identifies himself with it among all ç
the rivers.
@SB8.5 = Ga<209>g<193>, the Goddess
Almost all the well-known rivers of (undivided) India have a dual ç
form and have been described in the mythological literature as deities ç
or goddesses. Icono-graphical works even ascribe to them specific ç
forms and give detailed descriptions. For instance the river goddess ç
Ga<209>g<193> is pictured as a beautiful lady of white complexion ç
riding a crocodile and holding a pot and a lotus in her two hands. ç
If shown with four hands, she may be exhibiting the abhaya (protection) ç
and thevarada (boon-giving) mudr<193>s also. P<193>·a(noose) and ç
a<209>ku·a (goad) are also shown sometimes, instead of the pot and ç
the lotus.
As per the account in the Mah<193>bh<193>rata (°diparva 96-98) ç
Ga<209>g<193>, the river-goddess was cursed to be born as a human ç
being in this world. The king Mah<193>bhi<218>a who had attained heaven ç
was also cursed similarly. He was reborn as the king <185><193>ntanu. ç
<185><193>ntanu married Ga<209>g<193>. Bh<200><218>ma of the Mah<193>bh<193>rata ç
fame was their last son.
@SB8.5 = Ga<209>g<193>, the Celestial River
The river Ga<209>g<193> is said to have been born out of the left ç
foot of Vi<218><207>u in his incarnation as V<193>mana-Trivikrama. ç
(Hence the name `Vi<218><207>upad<200>.') It was then confined to ç
the celestial region only.
When the 60,000 sons of the king Sagara of Ayodhy<193> were reduced ç
to ashes by the curse of the sage Kapila, a way had to be found to ç
redeem them from their sins. Bringing the celestial river Ga<209>g<193> ç
to this earth and making it flow on their ashes was the solution. ç
King Bhag<200>ratha, a descendant of Sagara, achieved this stupendous ç
task by pleasing <185>iva through severe austerities. Thus she came ç
to be known as `Bh<193>g<200>rath<200>'. <185>iva captured the celestial ç
river that started to jump down with a terrific speed, in his matted ç
locks and then allowed her to stream out. While flowing through the ç
hermitage of the sage Jahnu, she flooded it, thereby provoking him ç
to swallow it up. At the earnest entreaties of Bhag<200>ratha she ç
was allowed to emerge from the ear of the sage. (Hence the name `J<193>hnav<200>'.) ç
She finally flowed over the ashes of Sagara's sons thereby liberating ç
them.
@SB8.5 = Ga<209>g<193>, the River as We Know It
Geographically speaking, the river Ga<209>g<193> takes its birth near ç
Ga<209>gotr<200> in the Tehri Garhwal district of Uttar Pradesh. It ç
is then known as Bh<193>g<200>rath<200>. Alakanand<193> is the second ç
rivulet born near the Tibetan border which joins the former near Devapray<193>ga ç
about 64 kms. (40 miles) from the well-known place of pilgrimage, ç
Haridv<193>ra. At this place it enters the plains, and is called `Ga<209>g<193>' ç
hereafter. The various tributaries that join the Ga<209>g<193> over ç
its long course are: Mand<193>kin<200>, Yamun<193>, Gh<193>gr<193> ç
(Saray<220>), Sone, D<193>modar, Ga<207><195>ak and Kos<200>. Near ç
the sea†the Bay of Bengal†another mighty river, the Brahmaputra, joins ç
it.
The total length of the river is 2500 kms. (1557 miles). It breaks ç
into a number of branches near the sea. Hoogly and Padm<193> are the ç
major branches.
A good number of pilgrim centres are situated on the banks of the ç
Ga<209>g<193> and its tributaries. They are: Devapray<193>ga, Rudrapray<193>ga, ç
Kar<207>apray<193>ga, Badar<200>-n<193>tha, Ked<193>ran<193>tha, H<216><218><200>ke·a, ç
Haridv<193>ra, Pray<193>ga and K<193>·<200> (V<193>r<193><207>as<200>). ç
To this list may be added Ga<209>gotr<200> and Ga<209>g<193>s<193>gara, ç
where it joins the sea, the Bay of Bengal.
@SB8.5 = Ga<209>g<193>sn<193>na or Ritual Bath in the Ga<209>g<193>
A bath in any river cleanses the body. But a bath in the holy river ç
Ga<209>g<193>, that too when the proper procedure prescribed in the ç
religious treatises is followed, purifies the mind too.
The following are the various steps given in such works (vide Matsyapur<193><207>a ç
102), to be followed by an earnest pilgrim who wishes to take a ritual ç
bath in the holy river: 
Sa<209>kalpa (pious resolve indicating the desire to destroy one's ç
sins and acquire religious merit), selecting a suitable spot in the ç
river for taking bath uttering the famous a<218><219><193>k<218>ar<200>-mantra ç
(O<221> namo n<193>r<193>ya<207><193>ya), <193>camana (ceremonial ç
sipping of water), <193>hv<193>na (invitation to the river goddess ç
to be present at that particular spot by uttering her various names ç
such as Dak<218><193>, P<216>thv<200>, Vihag<193>, Am<216>t<193>, ç
<185>iv<193>, K<218>em<193>, J<193>hnav<200>, <185><193>nt<193> and ç
so on), prok<218>a<207>a (sprinkling the river water on one's head), ç
m<216>ttik<193>lepana (applying clay taken from the bottom of the ç
river, with appropriate mantras), sn<193>na (bath), <193>camana, wearing ç
of clean white clothes, tarpa<207>a (satiating the manes and other ç
beings in all the three worlds), arghya to S<220>rya (offering of ç
water taken in the joined palms of the hand) and visiting a temple ç
of Vi<218><207>u and returning home.
For the benefit of those who have cherished a strong desire to take ç
a bath in the Ga<209>g<193> river, but are unable to do so due to ç
reasons like serious illness, old-age or poverty, the pur<193><207>as ç
and thedharma·<193>stras have suggested an ingenious method, the ç
`pratinidhi' system. On the request made to a pilgrim who is actually ç
going to take the bath, this pilgrim can make a small effigy of ku·a ç
grass and give it the bath with appropriate mantras that include the ç
name of the solicitor. The latter then gets one-eighth of the religious ç
merit he would have got if he had actually taken the bath himself.
Taking bath in the river Ga<209>g<193> on certain special days is ç
supposed to give infinitely great religious merit. Some of these are: ç
am<193>v<193>sy<193> (new-moon day); sa<209>kr<193>nti (days of the ç
apparent passageof the<|>sun from one zodiacal sign to the next); ç
days of lunar and solar eclipses; days of pu<218>kara (the day on ç
which the planet B<216>haspati or Jupiter enters the zodiacal sign ç
assigned to the river Ga<209>g<193> viz., Me<218>a, or Aries). The ç
pu<218>kara day for any river comes once in twelve years and the auspicious ç
moment for a few minutes only.
@SB8.5 = Festivals Related to the Ga<209>g<193>
An important day on which a festival called `Da·ahar<193>' is celebrated ç
in North India, falls on Jye<218><219>ha ·ukla da·am<200> (the 10th ç
day in the bright fortnight of the month of Jye<218><219>ha, usually ç
in May). It is said to be the day on which the river Ga<209>g<193> ç
descended to this earth. Since a bath in the river on this day, especially ç
at  the  Da·<193>·vamedha-gh<193><219>  of  K<193>·<200> (Banaras), ç
destroys ten types of sins itischristened `da·ahar<193>' (da·a = ç
ten; har<193> = destroyer).
The biggest bathing festival connected with the river Ga<209>g<193> ç
is the Kumbhamel<193> and the Ardhakumbhamel<193>, held respectively ç
once in twelve years and six years at Haridv<193>ra (Hardwar) and ç
at Pray<193>ga (modern Allahabad), in the Statesof Uttaranchal and ç
Uttar Pradesh. Millions of people take bath in the river on these ç
occasions.
@SB8.5 = Death, Last-rites and the Ga<209>g<193>
With a rare insight into the human problem of suffering, the dharma·<193>stras ç
have permitted religious suicide in certain cases such as decrepitude ç
brought by old-age, incurable diseases with great pain or as voluntary ç
punishment for mortal sins. This has to be normally done by drowning ç
oneself in the sacred river Ga<209>g<193>, especially attheTrive<207><200>-sa<209>gama ç
of Pray<193>ga (Allahabad).
Ceremonial immersion of either the body or the ashes after cremation ç
is another practice in vogue that is said to bring great religious ç
merit to the soul of the dead person.
@SB = Conclusion
Thus it is seen that the Ga<209>g<193> has been one of the major aspects ç
of Hindu religion and culture that has helped it to be not only alive ç
but also vigorously active. That is why a popular saying has identified ç
it with one of the three legs of the tripod upon which Hinduism stands ç
the other two being the G<200>t<193> and the G<193>yatr<200>.
@NT = Ga<209>g<193>dv<193>ra
@N1 = (`entrance to the Ga<209>g<193>')
See <MS>HARIDV°RA (HARDWAR)<D>.
@NT = Ga<209>gaiko<207><195>a-co<202>a-puram
This place near the famous place of pilgrimage, Cidambaram (Chidambaram), ç
in Tamil Nadu, is now a deserted village. However, it was once the ç
capital of the king R<193>jendra I (<MS>A.<|>D.<D> 1012-1044) of the ç
Co<202>a dynasty who had conquered a large part of the peninsular ç
India including Ceylon (now <185>r<200> La<209>k<193>). His father ç
had built the renowned B<216>had<200>·vara temple at Ta<210>j<193>v<220>r ç
(Tanjore). To commemorate his own victories and also as his offering ç
to his God, he built another, very similar, <185>iva temple at his ç
new capital. Except for the vim<193>na (tower over the sanctum) and ç
the ma<207><219>apa (large open hall) the rest of the temple is in ç
ruins. Compared to the Ta<210>j<193>v<220>r temple the sculptures ç
of this temple as also the carvings are of greater excellence. Another ç
interesting feature is that there is a separate shrine for Amman or ç
the Divine Mother, called `Tirukk<193>ma-ko<219><219>am.'
See also <MS>B<184>HAD®<185>VARA TEMPLE.<D>
@NT = Ga<209>g<193>s<193>gara
@N1 = (`the place [where the river] Ga<209>g<193> [joins the] s<193>gara ç
or ocean')
The river Ga<209>g<193> is undoubtedly the holiest of all the rivers ç
of India and has been thus revered for at least five millenniums. ç
Just as the place of its origin (Ga<209>gotr<200>) and the various ç
places of pilgrimage on its banks, even the region of its joining ç
the ocean (the Bay of Bengal) has been considered as extremely holy. ç
This place, known as the Ga<209>g<193>s<193>gara (and also Guhyak<218>etra), ç
was once the hermitage of the sage Kapila, who had reduced to ashes, ç
the 60,000 sons of the king Sagara. The P<193><207><195>avas, during ç
their vanav<193>sa or sojourn through the forests had visited this ç
place.
The place is situated about 144 kms. (90 miles) from the Diamond Harbour ç
which itself is 61 kms. (38 miles) from the metropolis of Calcutta. ç
There are steamer or boat services from the harbour up to the island.
There are some old temples in the region known as V<193>mankhal and ç
Candan-p<200><195>i. One of them is that of the goddess Vi·<193>l<193>k<218><200>.
On the occasion of Makara Sa<209>kr<193>nti (14th-15th January) thousands ç
of pilgrims take bath here.
See also <MS>GA<177>G°<D>.
@NT = Ga<209>g<193>vatara<207>a
@N1 = (`descent of [the river] Ga<209>g<193>')
The story of Bhag<200>ratha, bringing the celestial river Ga<209>g<193> ç
down to this earth has been described in great detail in the R<193>m<193>ya<207>a ç
(1.43), the Bh<193>gavata (9.9), the Mah<193>bh<193>rata (Vanaparva ç
109) and the M<193>rka<207><195>eya Pur<193><207>a (53). This has ç
often provided the artisans and sculptors with an inspiring theme ç
for their work.
In  Mah<193>balipuram  (or  M<193>mall<193>- puram) situated 50 kms. ç
to the south of Madras (now Chennai) there is a distinguished relief ç
work, carved into a huge rock, depicting the descent of Ga<209>g<193> ç
on this earth. It has many details, such as ascetics in prayer, pilgrims, ç
animals of all kinds heading towards the sacred water and so on. It ç
belongs to the 7th century <MS>A.<|>D.<D>
See also <MS>BHAG®RATHA<D> and <MS>GA<177>G°.<D>
@SPACE = 
@NT = Ga<209>ge·a
@SPACE = 
Ga<209>ge·a, also known as Ga<209>ge·a Up<193>dhy<193>ya (<MS>A.<|>D.<D> ç
1200), was the brightest luminary among the logicians of Bengal who ç
practically started a new school called `Navya-ny<193>ya'. He belonged ç
to Mithil<193> (in North Bihar). He wrote only one work, the Tattvacint<193>ma<207>i ç
in which he has dealt with only four pram<193><207>as (means or methods ç
of knowledge) accepted by the Ny<193>ya-s<220>tras of the sage Gautama. ç
They are: pratyak<218>a (direct perception), anum<193>na (inference), ç
upam<193>na (comparison) and ·abda (the Vedas).
His discussions on the anum<193>na aspect of knowledge received very ç
great attention among the scholars, thus developing an entirely new ç
school of thought. A very large number of commentaries and subcommentaries ç
have been composed on this single work. Among them, the commentary ç
of Raghun<193>tha <185>iroma<207>i (<MS>A.<|>D.<D> 1500) and the subcommentaries ç
on the same became extremely popular among the scholars of Bengal.
The contribution of this work is more in the direction of linguistic ç
notations than in metaphysics.
@NT = garbh<193>dh<193>na
@N1 = (`inseminating')
See <MS>GARBHANY°SA<D> and <MS><186>O£A<185>A- SA<189>SK°RAS<D>.
@NT = garbhag<216>ha
@N1 = (`inmost house,' `sanctum sanctorum')
For centuries, Hindu temples have played a very significant part in ç
the spiritual, religious and cultural life of Hindus.
If the temple is the house of God (dev<193>laya = house of God) then, ç
its sanctum sanctorum, technically called `garbhag<216>ha' or `garbhamandira' ç
is like the drawing room or private living room of God!
The garbhag<216>ha is generally square in shape with a low roof, with ç
no doors and windows, except for the front opening through which light ç
falls on the image or from which the devotees can have a view of the ç
deity. The roof over the whole shrine is a small tower called `vim<193>na'. ç
This tower is quite high in North Indian temples and of modest height ç
in the South Indian ones.
In some temples a pradak<218>i<207>apatha† a circumambulatory passage†is ç
provided justround the garbhag<216>ha, to enable the devotees to ç
go round the deity.
@NT = garbhany<193>sa
@N1 = (`inseminating [the temple site]')
A dev<193>laya or a Hindu temple is not just a place of prayer but ç
a structure where the particular deity `lives' in itssubtle body, ç
literally accepting the worship.
An extremely important rite which is performed during the construction ç
of a temple is the garbhany<193>sa or inseminating the temple site. ç
A casket or a tray or pot of copper, the dimensions of which are proportional ç
to the dimensions of the temple, is ceremonially lowered into the ç
ground on an auspicious night after filling it with precious stones, ç
several metals, herbs and soils, symbolising creation and prosperity. ç
This ceremony is said to help in the smooth consummation of the temple ç
project. A stone called <193>dh<193>ra·il<193> is kept over this spot. ç
This will be the foundation, ultimately, for the installation of the ç
icon.
It is because of this ceremony that the sanctum is called `garbhag<216>ha'.
@SPACE = 
@SPACE = 
@NT = garbharak<218>a<207>a
@N1 = (`protection of the<R>ç
foetus')
@SPACE = 
Every human being, according to the sm<216>tis and the dharma·<193>stras, ç
was expected to undergo some sa<221>sk<193>ras or purificatory rites. ç
One of the sixteen such sa<221>sk<193>ras (called `<218>o<195>a·a-sa<221>sk<193>ras') ç
is the pu<221>savana rite, of which the rite of garbharak<218>a<207>a ç
is a part.
In this rite, which is meant for protecting the foetus, the husband ç
of the pregnant lady inserts a little d<220>rv<193>rasa (juice of ç
the grass cynodon dactylon) intoher nostril, touches her heart ç
and repeats some mantras such as `<193> te garbho yonimaitu....' (Atharvaveda ç
3.23.2).
This rite is also called `anavalobhana' and is generally done in the ç
fourth month after conception.
See also <MS>PU<189>SAVANA<D> and <MS><186>O£A<185>A SA<189>SK°RAS<D>.
@NT = Garbhopani<218>ad
@SPACE = 
@SPACE = 
This is a minor Upani<218>ad of the K<216><218><207>a Yajurveda ç
group. It is remarkable for its detailed and accurate description ç
of the development of the garbha or the foetus in the womb. The philosophical ç
part of the work lies in the reflections of the j<200>va or the individual ç
soul caught in the womb, before birth.
There are 22 mantras, mostly in prose.
First comes an aphoristic description of the human body which is expanded ç
in the next six mantras. The five bh<220>tas or elements like earth, ç
water and fire, the sense-organs like the eyes and the ears, mind ç
and intellect, the capacity to know the six kinds of tastes like sweet ç
and sour, voice capable of producing desirable or undesirable sounds†all ç
these are part of the body-system.
The eighth mantra describes how the foetus is formed in the mother's ç
womb and how it develops, to become complete by the end of the eighth ç
month. It is interesting to note that according to this Upani<218>ad, ç
the j<200>va (the individual soul) enters the foetus only in the seventh ç
month!
The next mantra dilates upon how a male or a female child†or even ç
a eunuch† as also twins are born.
The verses 10 to 17, give a poignant description of the j<200>va repenting ç
his miserable state†for being forced to take birth and suffer in numerous ç
lives†due primarily to his own mistake of not seeking God but seeking ç
the transitory pleasures of the world.
However, all this knowledge of his previous lives and the present ç
state is totally forgotten as soon as he is born! (verse 18)
By conceiving of the various parts of the human body as different ç
items in a Vedic sacrifice, the individual can purify his mind and ç
finally attain liberation.
See also <MS>UPANI<186>ADS<D>.
@NT = g<193>rdhabhejy<193>
@N1 = (`offering an ass')
See <MS>AVAK®RØIN.
@NT = Garga
There appear to be several sages of this name. The <216><218>i or ç
the sage of the 47th s<220>kta of the 6th ma<207><195>ala of the <184>gveda ç
is Garga, the son of Bharadv<193>ja.
The woman-sage G<193>rg<200> V<193>caknav<200> mentioned in the B<216>had<193>ra<207>yaka ç
(3.6.1) was a descendant of the sage Garga.
The kulapurohita or the family priest of the Y<193>davas of Mathur<193> ç
was also a Garga. He performed the n<193>makara<207>a or the naming ç
ceremony of <185>r<200> K<216><218><207>a and Balar<193>ma secretly. ç
Again, it was he who advised Vasudeva (their father) to send them ç
to the sage S<193>nd<200>pani for education.
The name of Garga is mentioned in the list of sages who visited <185>r<200> ç
R<193>ma after his return to Ayodhy<193>. It appears in another list ç
too, of sages who visited Dro<207><193>c<193>rya in the battlefield ç
of Kuru-k<218>etra and advised him to retire.
There is also the mention of an astronomer sage Garga who performed ç
austerities at Gargasrota on the bank of the river Sarasvat<200>. ç
He discovered the paths of the planets and the stars. Several Gargasa<221>hit<193>s ç
are found now. They mayallbe different versions of an original work.
This Garga perhaps lived in 50 <MS>B.<|>C.<D> Utpala, the famous commentator ç
of the B<216>hajj<193>taka of Var<193>hamihira (d. <MS>A.<|>D.<D> ç
587) quotes nearly 300 verses from Garga's Sa<221>hit<193>. He was ç
the teacher of Atri, another well-known sage. The Vi<218><207>upur<193><207>a ç
(2.5.26) mentions him as an ancient <216><218>i who had known the ç
consequences of all the nimittas or omens.
@NT = G<193>rg<200> V<193>caknav<200>
G<193>rg<200>, daughter of Vacaknu, was the only woman-sage present ç
in the court of the king Janaka. She questioned Y<193>j<210>a- valkya, ç
the greatest exponent of the knowledge of Brahman, of his times, about ç
the warp and woof that links all things. Her learning is representative ç
of the high intellectual standard of the women of the upper classes ç
during the age of the Upani<218>ads.
@NT = G<193>rgya
@N1 = (`One who has descended from [the sage] Garga')
The dharmas<220>tras are early compilations on the various aspects ç
of Dharma. One such ancient work mentioned by famous writers like ç
Vi·var<220>pa (9th century <MS>A.<|>D.<D>) is the one by G<193>rgya ç
(a descendant of the sage Garga). His original work has not been traced.
The subjects dealt with by this G<193>rgya in his work†as can be gleaned ç
from the questions given by Vi·var<220>pa, Apar<193>rka (12th century ç
<MS>A.<|>D.<D>) and others† are: <193>hnika (daily routine), ·r<193>ddha ç
(obsequial rites), and pr<193>ya·citta (expiations).
The B<216>had<193>ra<207>yaka Upani<218>ad (2.1) mentions one `D<216>pta-b<193>l<193>ki ç
G<193>rgya.' He was a descendant of Garga, the son of a lady called ç
Bal<193>k<193> and got the appellation `d<216>pta' since he was extremely ç
proud of his learning (d<216>pta = proud).
Two more sages known to the Hindu epics and mythological works may ç
also be mentioned here. The first one was the priest of Yudh<193>jit, ç
a prince of the Kekaya kingdom. The second G<193>rgya was the son ç
of the sage Ve<207>uhotra. He is said to have taught the secrets of ç
dharma to Indra, the king of the gods in heaven.
@NT = g<193>rhapatya
@N1 = (`belonging to the g<216>hapati or the master of the house')
In the Vedic and the epic period, many a dvija (the `twice born') ç
maintained three sacred fires, ceremonially established. The g<193>rhapatya ç
fire was the first, the other two being the <193>havan<200>ya and ç
the dak<218>in<193>gni.
The g<193>rhapatya fire is first established by kindling it with the ç
ara<207>is (See <MS>ARAØI.<D>) through the process of agny<193>dh<193>na. ç
(See <MS>AGNY°DH°NA<D> for details.)
The pit for the g<193>rhapatya fire is round in shape and one square ç
aratni in area. (An aratni is 1/5 of the height of the sacrificer ç
who establishes the fire.)
The fire itself is used for various purposes such as: daily Agnihotra; ç
warming the havis of oblatory material; warming the vessels used for ç
the same; circumambulation; cooking the havis; to start the other ç
two fires.
This fire, once kindled, had to be maintained throughout life.
In Somay<193>gas, another <193>havan<200>ya fire is generated from ç
the earlier one, in the uttaravedi (a higher platform to the east). ç
In such a case, the former fire is also called `g<193>rhapatya.'
See also <MS>PA<178>C°GNI.<D>
@NT = g<193>rhasthya
@N1 = (`the state of being the<R>ç
master of the house')
@SPACE = 
@SPACE = 
The var<207>a-<193>·rama system was a basic institution that guided ç
the Hindu society during the ancient and medieval days. The var<207>a ç
system, based on the principle of division of labour, helped in the ç
smooth running of the society. The <193>·rama system, on the other ç
hand, prepared the individual to become a worthy member of the society ç
first, and later, to transcend it so that the ultimate goal of life†mok<218>a ç
or liberation†can be achieved more easily.
Out of the four <193>·ramas†brahmacarya, g<193>rhasthya, v<193>naprastha ç
and sa<221>ny<193>sa†g<193>rhasthya, the second, has been considered ç
as central, the pivot, of the whole society. This is because the g<216>hastha ç
is the only earning member among all the four groups.
The term `g<193>rhasthya' has been derived from the words `g<216>ha' ç
(`house') and `g<216>hastha' (`one who stays in the house' or `one ç
who is established in the married state'). So, it means the state ç
of the householder.
After finishing his education and training in the gurukula, a student ç
(brahmac<193>rin) was expected to return home, marry a suitable girl ç
and raise a family. He thus became a g<216>hastha.
The g<216>hastha was obliged to earn well by dh<193>rmic or right ç
means and live a happy, decent, life which should be socially useful. ç
Among his principal duties were the pa<210>cayaj<210>as or the five ç
daily sacrifices. (See <MS>PA<178>CAYAJ<178>AS<D> for details.)
Other duties prescribed for him were: eating only twice a day, honouring ç
guests that come to one's house (especially the holy persons), taking ç
care of the basic needs of all the members of the family and the dependents, ç
treating the elders in the family (like the parents, grand- parents, ç
elder brothers and so on) with due respect and not getting angry with ç
them, and, finally, self-control.
@NT = Garu<195>a
@N1 = (`one who flies with the help of wings')
One of the most common and well-known figures that we come across ç
in the Hindu pur<193><207>as is that of Garu<195>a or Garutm<193>n. ç
He is pictured in a human form, but with two powerful wings and a ç
sharp beak, resembling those of an eagle. He is the v<193>hana (mount ç
or vehicle) of God Vi<218><207>u. He is also shown as the insignia ç
on the banner (dhvaja) of the flagpost of Vi<218><207>u temples.
@SPACE = 
@SPACE = 
@SPACE = 
@SPACE1 = 
The story of Supar<207>a, the golden winged eagle, bringing the soma ç
juice from heaven, as it appears in the <184>gveda (4.26 and 27) ç
seems to be the basis for the later accounts of Garu<195>a in the ç
epics and the pur<193><207>as. According to the °diparva (chs. 31-34) ç
of the Mah<193>bh<193>rata, Garu<195>a was the son of the sage Ka·yapa ç
(the progenitor of all living beings) and Vinat<193>. Since Vinat<193> ç
had become the slave of Kadr<220> (another wife of Ka·yapa) due to ç
a curse, Garu<195>a liberated her from it by bringing the am<216>ta ç
or nectar from heaven, as per the desire and condition set by Kadr<220>. ç
(See <MS>KUMBHAMEL°.<D>)
His many heroic exploits so pleased Lord Vi<218><207>u that he made ç
Garu<195>a his mount.
In the R<193>m<193>ya<207>a of V<193>lm<200>ki, he appears once ç
on the battlefield, when R<193>ma, Lak<218>ma<207>a and others had ç
become unconscious due to the n<193>gap<193>·a or sarp<193>stra (snake-missile) ç
discharged by Indrajit. The serpents immediately fled and they were ç
all back on their feet (vide Yuddhak<193><207><195>a ch. 50).
In the iconographical works, he is usually depicted as a human figure ç
with powerful and outstretched wings at the back of the two arms, ç
which are in the pose of a<210>jali or obeisance. Sometimes he is ç
shown as flying, carrying Vi<218><207>u on his back, his two hands ç
supporting Vi<218><207>u's dangling feet.
The colour of his body may be that of an emerald or pure white. He ç
is also decked with several ornaments.
@SPACE = 
@NT = Garu<195>apur<193><207>a
@SPACE = 
For centuries, the pur<193><207>as†stories of the ancient period, ç
mythological lore† have served the purpose of educating the masses, ç
both in the religious and in the secular fields. Recitation and exposition ç
of the pur<193><207>as in temples and dharma·<193>las by a learned ç
br<193>hma<207>a for the benefit of the masses was a common sight ç
in the towns and villages of India, even a hundred years ago.
Out of the eighteen mah<193>pur<193><207>as† all ascribed to the sage ç
Vy<193>sa†the Garu<195>apur<193><207>a is listed as the seventeenth. ç
It is said to have derived its name from the fact that Vi<218><207>u ç
taught it to Garu<195>a (See also <MS>GARU£A.<D>) at his request.
Assigned to the period <MS>A.<|>D.<D> 900, the number of ·lokas of ç
this pur<193><207>a, as per different compilations and editions, varies ç
from 8000 to 19,000!
Though considered as a spurious Vai<218><207>ava  work  by  the  scholar-king ç
Balla<202>asena (12th century <MS>A.<|>D.<D>) of the D<193>nas<193>gara ç
fame, it is a highly revered work even now.
It comprises two parts: the P<220>rva-kha<207><195>a (with 240 chapters) ç
and the Uttarakha<207><195>a. The latter again, is divided into ç
two sections, called Pretakalpa (42chapters) and Brahmakha<207><195>a ç
(29 chapters).
The work is encyclopaedic in character. The contents of the two epics, ç
as also of the Hariva<221>·a have been retold here.
@SPACE1 = 
The topics dealt with in the P<220>rva-kha<207><195>a can be summarised ç
as follows: creation of the world; worship of the deities S<220>rya ç
(the Sun-god), <185>iva, Dev<200>, Ga<207>e·a, various aspects of ç
Vi<218><207>u and also his <193>yudhas or weapons; yoga or meditations ç
based on the Vai<218><207>ava view-point; the sandhy<193> ritual; ç
architecture and town- planning; iconography; d<193>na or gifts; var<207><193>·ramadharmas; ç
sins andtheir expiations;  geographical  and  cosmological description ç
of the universe; various vratas or religious observances; the solar ç
and the lunar races of kings; incarnations of Lord Vi<218><207>u; ç
°yurveda or the science of medicine and surgery; A·vavidy<193> or ç
the science of horses; grammar, poetry and rhetoric; a<218><219><193><209>gayoga ç
(eightfold yoga); hymns on various aspects of Vi<218><207>u as Narasi<221>ha ç
or Acyuta; mantras and astrology.
The  subjects  discussed  in  the Pretakalpa are:
exposition of dharma; causes for various kinds of births; way to the ç
abode of Yama, the god of death; description of Yama's world and his ç
affluent palace; rites connected with the death of a person; after-death ç
ceremonies; various types of ·r<193>ddhas; sapi<207><195><200>kara<207>a ç
rite (See <MS>SAPIØ£®-KARAØA.<D>); N<193>raya<207>abali rite; results ç
of good and bad deeds of human beings.
The Brahmakha<207><195>a deals with the following topics: procedure ç
for saluting <185>r<200>hari; the three gu<207>as of sattva, rajas ç
and tamas; unity of Brahm<193>, Vi<218><207>u and <185>iva; creation ç
of the world; incarnations of Vi<218><207>u and Lak<218>m<200>; the ç
·<193>lagr<193>ma stone; importance of many holy rivers; worship of ç
Vi<218><207>u and eulogy of dharma.
On the whole, this is a very useful work throwing light on several ç
facets of Hindu religion, culture and social conditions.
See also <MS>PUR°ØAS<D>.
@NT = Garu<195>a Upani<218>ad
This is a minor Upani<218>ad belonging to the Atharvaveda. Its main ç
purpose seems to be to attain freedom from the fear of all poisonous ç
creatures.
There are 25 mantras, mostly in prose.
The science taught here is called `g<193>ru<195>a-brahmavidy<193>' ç
and is said to have originated from the four-faced Brahm<193>, the ç
other important teachers being N<193>rada, B<216>hatsena, Indra and ç
Bharadv<193>ja.
Mantras 2 to 4 give the usual prelimi- naries like <216><218>i (sage), ç
chandas (metre), devat<193> (deity) and viniyoga (usage) as also the ç
ny<193>sas, purificatory processes of hands and limbs.
Then comes dhy<193>na or meditation on Garu<195>a or Garutm<193>n ç
(the eagle-mount of Lord Vi<218><207>u, known for his stupendous strength ç
and enmity towards the serpents) in a long passage comprising seven ç
versesin the ·loka metre. It contains a picturesque description of ç
Garu<195>a who has the famous serpents like Ananta, V<193>suki, Tak<218>aka, ç
K<193>rko<219>aka and others as his ornaments, all over his body!
This is followed by several m<193>l<193>- mantras (very long mantras) ç
(mantras 6 to 24) the main purport of them being the destruction (or ç
prayers for destruction) of various kinds of poisons which are described ç
in detail.
The Upani<218>ad ends with a phala·ruti, a statement of the favourable ç
results got by the chanting or listening to it.
See also <MS>GARU£A<D> and <MS>UPANI<186>ADS<D>.
@NT = g<193>th<193>
@N1 = (`song')
The word, as used in the <184>gveda, usually meant a song or a verse. ç
In later Vedic literature including the <184>gveda (10.85.6) and ç
the Atharvaveda (20.127.1 to 3) as also the Aitareya Br<193>hma<207>a ç
(30.32) it seems to have acquired a more technical flavour, indicating ç
a religious, poetical, composition, but not considered as a mantra, ç
like the <216>k or the s<193>man.
Two well-known g<193>th<193>s need special mention here: the g<193>th<193>-n<193>r<193>·a<221>s<200> ç
and the g<193>th<193>-raibh<200>. The three <216>ks of the Atharvaveda ç
mentioned above, are the first. The latter g<193>th<193> is the group ç
of three <216>ks in the same section of the Atharvaveda (20.127.4 ç
to 6).
The n<193>r<193>·a<221>s<200>-g<193>th<193> is in praise of the ç
deity that grants the power of speech to children.
The raibh<200>-g<193>th<193> enabled the <216><218>is and the performers ç
of sacrifice to go to heaven.
@NT = g<193>th<193>-n<193>r<193>·a<221>s<200>
See <MS>G°TH°.<D>
@NT = gati
@N1 = (`movement')
This word, though commonly it means `movement,' is used in several ç
other senses like consequence, path, nature, progress and so on.
The Upani<218>ads and the Bhagavadg<200>t<193> describe two types ç
of gatis or paths (leading to a destination)†the ·ukla (the white, ç
also called `arcir<193>dim<193>rga') for the fortunate souls and the ç
k<216><218><207>a (the black, also called `dh<220>m<193>dim<193>rga') ç
for the ordinary ones.
Some of the pur<193><207>as predicate four gatis (or results) for ç
human beings as follows: reaching the presence of a deity through ç
yaj<210>a, intense spirit of renunci-ation through tapas or austerity, ç
status of br<193>hma<207>a through karmasa<221>ny<193>sa or renunciation ç
of desire-motivated actions and kaivalya or mok<218>a (liberation) ç
through j<210><193>na (spiritual wisdom).
In the Matsyapur<193><207>a gati is described as one of the eight ç
daughters of Kardama Praj<193>pati. She was married to the sage Pulaha. ç
Her three sons once offended <185>iva and were cursed by him to die ç
by drowning in the Brahmaputra.
@NT = Gau<195>ap<193>da
In the Advaita Ved<193>nta tradition, Gau<195>ap<193>da has been honoured ç
as the teacher of Govindayog<200>ndra who himself was the teacher ç
of <185>a<209>kara (<MS>A.<|>D.<D> 788-820). He is said to have lived ç
in the Badari-k<193>·rama in the Him<193>layas and acquired the knowledge ç
of the Upani<218>ads from Lord N<193>r<193>ya<207>a himself.
Whether the name `Gau<195>ap<193>da' was his real name or only a cognomen ç
indicating that he came originally from the Gau<195>ade·a (Bengal?) ç
is rather difficult to say. He might have lived around <MS>A.<|>D.<D> ç
800.
There are seven works attributed to Gau<195>ap<193>da. They are:
1.
@NK = The K<193>rik<193>s on the M<193><207><195><220>kya Upani<218>ad.
2.
@NK = A bh<193><218>ya (commentary) on the S<193><209>khyak<193>rik<193> ç
of ®·varak<216><218><207>a.
3.
@NK = A v<216>tti (concise commentary) on the Uttarag<200>t<193>.
4.
@NK = <185>r<200>vidy<193>ratnas<220>tra.
5.
@NK = Subhagodaya.
6.
@NK = A bh<193><218>ya on the N<216>si<221>ha P<220>rva-t<193>pin<200> ç
Upani<218>ad.
7.
@NK = A commentary on the Durg<193>- sapta·at<200> (same as the ç
Dev<200>-m<193>h<193>tmya or the Ca<207><195><200>).
However, except the first, all the other works might be the compositions ç
of a different Gau<195>ap<193>da.
@SPACE1 = 
The philosophy of Gau<195>ap<193>da, as reflected in the M<193><207><195><220>kya ç
K<193>rik<193>, is an extreme form of advaita. According to him, ç
the avasth<193>traya-vivecana or an analysis of the three states of ç
consciousness reveals that all these states (j<193>grat or waking, ç
svapna or dreaming and su<218>upti or deep sleep) are like night for ç
the j<200>va or the individual soul, since there is no direct and ç
clear experience of oneself as the pure consciousness in these three ç
states. It is only in the tur<200>ya (or the fourth) state that one's ç
<193>tman nature is experienced. Hence, even the so-called `j<193>grat ç
or waking' state is a state of sleep or illusion or ignorance!
By giving the example of a fire brand, moved around fast, which creates ç
optical illusions, Gau<195>ap<193>da tries to prove the illusory nature ç
of this world.
`Aj<193>tiv<193>da' or the doctrine that this world is never created ç
(aj<193>ti = no birth) or born and that Brahman alone is ever existent, ç
is another theory that he puts forward with supporting logic. He vigorously ç
refutes other theories like asatk<193>ryav<193>da (the doctrine that ç
effect never pre-existed in the cause) of the Ny<193>ya-Vai·e<218>ika ç
school, the satk<193>ryav<193>da (the doctrine that the effect did ç
exist in its cause) of the S<193><209>khya philosophy as also the ç
vij<210><193>nav<193>da (that vij<210><193>na or continuous waves ç
of intellect alone exist) of the Buddhists. Ultimately he rejects ç
his own aj<193>tiv<193>da also since even the ajatva (non-birth) of ç
the <193>tman is kalpita or imagined!
However Gau<195>ap<193>da accepts pra<207>avo-p<193>san<193> (meditation ç
on the <193>tman through pra<207>ava or o<221>) as the means for destroying ç
dvaita-j<210><193>na or knowledge of duality.
@SPACE1 = 
Gau<195>ap<193>da also recommends aspar·ayoga or the yoga of non-contact ç
of the mind with any object, as an important mode of s<193>dhan<193>. ç
It is the same as j<210><193>nayoga. In this practice, themind, throughthe ç
disciplines of viveka (discrimination), vair<193>gya (spirit of renunciation) ç
and abhy<193>sa (repeated efforts) gradually gets dissolved†this state ç
being called `aman<200>bh<193>va'†since the objects of the world presented ç
to the mind do not exist in reality. Hence, even as fire dies out ç
when there is no fuel, the mind too stops working in the form of v<216>ttis ç
or mental waves. The knowledge that the <193>tman alone is real, becomes ç
well-established.
Gau<195>ap<193>da concludes his K<193>rik<193>s with a description ç
of mok<218>a (liberation) and the mukta (liberated soul). This description ç
resembles the ones given in the Bhagavadg<200>t<193>.
See also <MS>ASPAR<185>AYOGA<D> and <MS>M°Ø£<188>KYAK°RIK°<D>.
@NT = Gaur<193><209>ga
@N1 = (`one whose body is white')
See <MS><185>R® K<184><186>ØA CAITANYA.<D>
@NT = Gaur<200>
@N1 = (`The white one')
`Gaur<200>' is another name of P<193>rvat<200>, the consort of <185>iva. ç
(See <MS>P°RVAT®<D> for more details.) She is described as a girl ç
of ten years.
She may be worshipped along with <185>iva as Candra·ekhara or as an ç
independent deity. In the former case she is shown as standing on ç
a lotus seat, to his left. She is dark-blue in complexion, three-eyed ç
and two-armed. She holds a blue-lotus in her right hand.
Works like the Apar<193>jit<193>s<220>tra mention several forms ç
of Gaur<200> such as Um<193>, P<193>rvat<200>, Lalit<193>, K<216><218><207><193> ç
and <185>r<200>. The number of these forms varies from 12 to 24.
@NT = Gaur<200>ku<207><195>a
Pilgrimage to the Him<193>layan shrines at Ked<193>ra and Badar<200> ç
(Garhwal district of Uttaranchal) has been a great dream to many a ç
Hindu even from the very early times.
Gaur<200>ku<207><195>a, situated 13 kms. (8miles) below the Ked<193>rn<193>th ç
temple, is one of the places the pilgrims do not miss. Gaur<200> or ç
P<193>rvat<200> is believed to have been born here. There is a nice ç
temple here dedicated to her.
There are also two ku<207><195>as or ponds of water, one containing ç
hot water and the other, cold. The latter is called `Am<216>taku<207><195>a' ç
and P<193>rvat<200> is said to have bathed here.
There is also a temple of R<193>dh<193>-K<216><218><207>a.
The climb to Ked<193>rn<193>th temple from here is quite steep.
There  is  another  Gaur<200>ku<207><195>a  in Tibet, to the east ç
of the Mount Kail<193>sa. Situated at a height of 5520 metres (18,400 ç
ft.), it is an elliptical lake 1.2 kms. (0.75 mile) long and 0.8 km. ç
(0.5 mile) wide. It is believed to be 25 metres (84 ft.) deep. It ç
is always covered by ice blocks. Pilgrims take bath here while proceeding ç
towards the M<193>nasa-sarovara and the Mount Kail<193>sa.
@NT = Gautama
@N1 = (`descendent of [the sage]<R>ç
                            Gotama')
Being a patronymic title, the word `Gautama' can apply to anyone supposed ç
to be a descendant of the sage Gotama. We come across several Gautamas ç
in the Vedic literature like the <185>atapatha Br<193>hma<207>a ç
and also in quite a few Upani<218>ads. Here the Gautama may be a sage ç
giving some important teaching or may have just been mentioned in ç
the lists of va<221>·as or genealogies.
Of all the Gautamas, Gautama the son of the sage D<200>rghatamas and ç
the husband of Ahaly<193> is the most celebrated one. He is considered ç
as one among the Saptar<218>is (the Seven Sages) and a gotra-pravartaka ç
or the originator of a particular lineage. Of his many achievements, ç
the more important ones may be listed as follows: scholarly conversations ç
with other great sages like Atri, A<209>giras and Yama (the god of ç
death); training the sage Uda<209>ka who was his disciple and <185>at<193>nanda, ç
his own son; protecting the people during a severe famine; originating ç
the sacred river God<193>var<200> (also called Gotam<200> river) by ç
the power of his prayer and so on.
Ak<218>ap<193>da, the author of the Ny<193>ya-s<220>tras (the basic ç
work of the Ny<193>ya systemof Philosophy) was also known as Gautama.
There  is  an  ancient  work called Gautama Dharmas<220>tras. This ç
Gautama probably belonged to the period 600-400 <MS>B.C.<D> His work ç
has been quoted as an authority by later writers on the dharma-·<193>stras.
@SPACE = 
@NT = Gautama Dharmas<220>tras
@SPACE = 
@SPACE = 
Hinduism has always considered dharma (foundational morality and ethics) ç
as a basic value which must cover all aspects of life, individual ç
as well as social. One of the earliest classes of scriptures dealing ç
with dharma is the dharmas<220>tra literature.
The Dharmas<220>tras of Gautama has been considered a quite ancient ç
(600-400 <MS>B.C.<D>)†perhaps, the oldest†dharmas<220>tra work and ç
authoritative. It has been held in high esteem by the later writers ç
of dharma·<193>stras.
There is reason to believe that the Dharmas<220>tras of Gautama ç
is an independent work and not a part of the Kalpas<220>tras.
The sage Gautama probably belonged to the R<193><207><193>y<193>n<200>ya ç
school of the S<193>maveda.
This work has a bh<193><218>ya or commentary by Maskarin (<MS>A.<|>D.<D> ç
900) and another one called Mit<193>k<218>ar<193> by Haradatta (<MS>A.<|>D.<D> ç
1100).
The Gautama Dharmas<220>tras is written entirely in prose and has ç
28 chapters.
A brief summary of the contents can now be attempted:
Sources of dharma; details of the upanayana sacrament; the four <193>·ramas; ç
rules concerning marriage and the duties of a householder; the pa<210>camah<193>yaj<210>as ç
or the five daily sacrifices; the duties of the four var<207>as; r<193>jadharma ç
or the duties and responsibilities of a king; crime and punishment; ç
rules concerning law-suits; ·r<193>ddhas or obsequial ceremonies; ç
rules regulating food and eating; on women; sins and their expiations; ç
penances; partition of property and related matters.
@NT = Gav<193>mayana
@N1 = (`course of the cows [or rays of the sun]')
The Vedic sacrifices†yaj<210>as or y<193>gas †are an ancient institution. ç
According to the Bhagavadg<200>t<193> (3.10 and 11) sacrifices were ç
created by Praj<193>pati (Lord of men, the creator) himself at the ç
very beginning of creation.
Among the various varieties of such sacrifices, the Sattray<193>ga ç
is also one. It is the one sacrifice wherein all the priests who ç
perform it are also the yajam<193>nas (masters who reap the results ç
equally). The duration of a Sattray<193>ga may be from 12 days up ç
to a year or more. The Gav<193>mayana is a typical Sattray<193>ga, ç
a model for such sacrifices of one year's duration. It may be performed ç
for various
