@NID = rewards like progeny, prosperity, greatness or heaven.
The sacrifice is performed in three phases. The first and the third ç
are spread over 180 days (6 lunar months of 30 days) each. In between ç
comes the vi<218>uvat or the central day.
Several rites like Abhiplava (a Soma ritual), Agni<218><219>oma (a ç
Soma sacrifice), Da·ar<193>tra  (another rite  of  ten  days' duration) ç
and Udayan<200>ya (a concluding rite of any Somay<193>ga) are involved ç
in this Sattray<193>ga.
See also <MS>VEDIC SACRIFICES.
@NT = Gay<193>
Hindu epics, dharma·<193>stras and pur<193><207>as extol t<200>rthay<193>tr<193> ç
or pilgrimage very highly. It helps a person spiritually by destroying ç
his sins and adding to his religious merit.
One of the most celebrated places of pilgrimage for the Hindus is ç
Gay<193> in the Gay<193> district of Bihar. It is 88 kms. (55miles) ç
from the capital city Patna and is situated on the western bank of ç
the river Phalgu.
Gay<193> proper, the main pilgrimage centre of the Hindus, is called ç
Brahma-Gay<193>. Situated 11 kms. (7 miles) away from this is Bodh-Gay<193>, ç
the place where Siddh<193>rtha attained bodhi and became the Buddha. ç
There is a temple here, dedicated to Buddha, measuring 15 metres square ç
(50 ft.) and 48 metres (160 ft.) high. There is also a bodhi tree ç
under which Buddha is said to have attained enlightenment.
According to a paur<193><207>ic legend, Gayawas an asura (demon) ç
who was a great devotee of Vi<218><207>u. By performing severe austerities ç
he propitiated Vi<218><207>u and secured a boon that whoever touched ç
him would go to heaven. As a result, all people started going to heaven ç
just by touching him and Yama's hell became empty! At his request, ç
Vi<218><207>u suggested to Brahma to perform a Vedic sacrifice on ç
Gaya's body. Gaya agreed and the sacrifice started. But his head started ç
shaking thus disturbing the sacrifice. In order to make it steady ç
a stone called `dharma·il<193>' was secured from the world of Yama ç
and placed upon Gaya's head. Since even this did not work, all the ç
gods and Vi<218><207>u himself with his gad<193> or mace, had to stand ç
on it, thus stopping the shaking. Gaya, the devotee, requested Vi<218><207>u ç
that all the gods should be permanently stationed on his body. Vi<218><207>u ç
granted the same. As a result, the place where Gaya's body lay, became ç
an extremely holy place.
Before starting on a pilgrimage to Gay<193> one should circumambulate ç
one's own town or village and perform a ·r<193>ddha (See <MS><185>R°DDHA<D> ç
for more details.), which is a call to the pit<216>s or ancestors ç
to come to Gay<193>.
@SPACE1 = 
The rites to be performed after reaching Gay<193> may be summarised ç
as follows: digging a pit in the bed of the Phalgu river (which is ç
dry most of the time) to get water and offer tarpa<207>a (water for ç
satiation of the manes) and also perform a ·r<193>ddha; twelve ancestors ç
(three generations on the paternal and maternal side) are to be satiated ç
by these rites; offering pi<207><195>as (rice-balls) at the Vi<218><207>u-p<193>da ç
in the Vi<218><207>u temple (built in <MS>A.<|>D.<D> 1787 by the queen ç
Ahaly<193>b<193><200> Ho<202>kar) and sprinkling the holy water on ç
oneself; offering  pi<207><195>as  at  the  foot  of  the famous Ak<218>ayava<219>a ç
(See <MS>AK<186>AYAVA<187>A<D>.) and honouring the br<193>hma<207>as; ç
visit to some minor t<200>rthas (holy places) like R<193>ma·il<193> ç
and Preta·il<193> hillocks.
The footprints of Lord Vi<218><207>u (Vi<218><207>u-p<193>da) in the ç
Vi<218><207>u temple are in an octagonal basin 1.2 metres (4 ft.) ç
in diameter and measure 40 cms. (16 inches) by 15 cms. (6 inches).
The ·r<193>ddha performed at Gay<193> is said to yield inexhaustible ç
results. Hence once it is performed there, there is no need to do ç
it again during the rest of one's life.
The bodhi tree is not the original tree. However, replanting from ç
taking the branches of the original or growing it from its seeds must ç
have been going on for centuries. The present one was probably planted ç
around <MS>A.<|>D.<D> 1876.
Many edicts of kings, mostly from South India, have been discovered ç
at Gay<193>.
@NT = Gay<193>·r<193>ddha
See <MS>GAY°<D> and <MS><185>R°DDHA<D>.
@NT = g<193>yatr<200>
@SPACE1 = 
The g<193>yatr<200> is a celebrated Vedic chandas or meter. The other ç
well-known meters are u<218><207>ik, anu<218><219>ubh, b<216>hat<200>, ç
pa<209>kti, tri<218><219>ubh and jagat<200>. 
The main reason for the g<193>yatr<200> meter to be so celebrated ç
is the revelation to the sage Vi·v<193>mitra, of the famous S<193>vitr<200>- ç
mantra in the g<193>yatr<200> meter. This being the first mantra in ç
that meter and an extremely important one at that, the mantra itself ç
came to be known as the G<193>yatr<200>-mantra.
Consequently, the word `G<193>yatr<200>' is used not only to indicate ç
the meter, but also the mantra. In course of time it was also used ç
to denote the presiding deity or the goddess of that mantra.
There is an interesting story in the Vedic literature to prove the ç
greatness of this meter (vide <184>gveda 4.26.4 to 7; Taittir<200>ya ç
Sa<221>hit<193> 6.1.6.1 to 3; Aitareya Br<193>hma<207>a 13.25 to ç
28). The gist of the story is that the meter G<193>yatr<200>, at the ç
request of the devas or gods, took the form of a bird (Supar<207>a), ç
flew to the world of Soma and brought it (the soma juice or am<216>ta, ç
the ambrosia) to the world of gods. This story is very similar to ç
the story of Garu<195>a bringing am<216>ta from svargaloka to get ç
his mother Vinat<193> freed from slavery.
Symbolically, this story may indicate that the G<193>yatr<200>mantra ç
which is a prayer addressed to the Supreme God in and through the ç
orb of the sun, is capable of giving us am<216>tatva or immortality ç
or liberation.
The word `g<193>yatr<200>' seems to have undergone gradual transmutation ç
from meaning a Vedic meter first, the mantra (addressed to Savit<216> ç
or the creator) next and ultimately, the Vedam<193>t<193> or the goddess ç
who is the mother of the Vedas.
@SPACE1 = 
This goddess has three aspects:
a)
@NK NO # = G<193>yatr<200>, the feminine counterpart of Brahm<193> ç
and associated with the morning sun;
b)
@NK NO # = S<193>vitr<200>, the feminine counterpart of Vi<218><207>u ç
and associated with the mid-day sun;
c)
@NK NO # = Sarasvat<200>, the feminine counterpart of Rudra, associated ç
with the evening sun.
Iconographically, they are shown as follows:
G<193>yatr<200> representing the <184>gveda and Brahm<193>, is a ç
kum<193>r<200> (young girl), red in complexion. She has two arms carrying ç
an ak<218>as<220>tra (rosary) and a kama<207><195>alu (water pot). ç
She is riding a swan.
S<193>vitr<200> representing the Yajurveda and Vi<218><207>u is ç
a dark complexioned yuvati (young woman). She has four arms carrying ç
·a<209>kha (conch), cakra (discus), gad<193> (mace) and padma (lotus). ç
She is riding on the Garu<195>a (Vi<218><207>u's eagle-mount).
Sarasvat<200> representing the S<193>maveda and Rudra is a fair-complexioned ç
v<216>ddh<193> (old woman) with four arms in which she is holding ç
tri·<220>la (trident), <195>amaru (small kettle-drum), p<193>·a (noose) ç
and p<193>tra (bowl). She has the V<216><218>abha or the bull as her ç
mount.
The dhy<193>na·loka normally chanted at the time of the Sandhy<193> ç
ritual, however, describes  G<193>yatr<200>,  the  goddess,  in  a ç
different way. She has five faces and ten arms. The five faces have ç
the colours of mukt<193> (pearl), vidruma (coral), hema (gold), n<200>la ç
(blue) and dhavala (white). Each face has three eyes, ten arms carrying ç
aravindayugala (two lotuses), cakra  (discus),  ·a<209>kha  (conch),  gu<207>a ç
(trident), kap<193>la (skull-cup), a<209>ku·a (goad), ka·a (rope or ç
whip), abhaya and varada mudr<193>s (handposes assuring protection ç
and offering boons). She is seated on a lotus-seat.
This occurs in the Dev<200>bh<193>gavata (12.3).
See also <MS>G°YATR®-MANTRA.
@NT = G<193>yatr<200>-mantra
@N1 = (`the mantra which<R>ç
protects [one who] chants it')
@SPACE1 = 
If there is one Vedic mantra which is very much prevalent and alive ç
even now in certain sections of the modern Hindus, it is the G<193>yatr<200>mantra. ç
Apart from the <184>gveda Sa<221>hit<193> (3.62.10), it occurs in ç
the other Vedas also: Taittir<200>ya Sa<221>hit<193> (1.5.6.4; 4.1.11.1); ç
Taittir<200>ya °ra<207>yaka (1.11.2); V<193>jasaney<200> Sa<221>hit<193> ç
(3.35; 22.9; 30.2 and 36.3); S<193>maveda Sa<221>hit<193> (1462).
This mantra is said to have been revealed to the well-known sage Vi·v<193>-mitra. ç
It is widely used as a part†the most important part†of the Sandhy<193> ç
ritual performed by every br<193>hma<207>a, twice or thrice a day.
Actually, the<|>mantra is called `S<193>vitr<200>- mantra' since it ç
is a prayer addressed to the Supreme God Savit<216> or Savit<193> ç
(the Creator). However, being the very first mantra revealed in the ç
now famous g<193>yatr<200> metre (a poetical mode, comprising three ç
lines of eight letters each), the mantra itself came to be known popularly ç
as the `G<193>yatr<200> mantra'.
The  word  `G<193>yatr<200>'  is  sometimes defined as that (mantra) ç
which protects (tra= to protect) one who sings or chants (gai or ç
g<193>y = to sing) it.
The Mantra has three parts:
1)<+><+>the vy<193>h<216>tis;
2)<+><+>the G<193>yatr<200>mantra proper;
3)<+><+>the g<193>yatr<200>·iras.
Of course, the Pra<207>ava or O<221> is always added†as in the case ç
of most of the Vedic mantras†in the beginning and is not counted.
The vy<193>h<216>tis are: bh<220><199>, bhuva<199> and suva<199>.
@SPACE1 = 
`Vy<193>h<216>ti' means `uttering'. Brahm<193> the creator, is said ç
to have uttered these at the beginning of creation. Hence this appellation, ç
`vy<193>h<216>tis'.
They mean and represent the three worlds: earth, intervening space ç
and heaven.
Sometimes, the number of these vy<193>h<216>tis is increased from ç
3 to 7, indicating the seven worlds spread over from the earth up ç
to the Satyaloka or Brahmaloka. However, these vy<193>h<216>tis are ç
used more for counting purposes in pr<193><207><193>y<193>ma than ç
for japa.
The second part, the S<193>vitr<200>-mantra proper, is:
@IN2 = tatsavitur vare<207>ya<221><R>ç
bhargo devasya dh<200>mahi<R>ç
dhiyo yo na<199> pracoday<193>t<F49P11M>f
@SPACE1 = 
A free translation of this mantra is as follows: `We meditate upon ç
that effulgence of God, the creator. May he guide our intellects!'
The third part, the g<193>yatr<200>·iras, runs thus: Om <193>po jyot<200> ç
raso'm<216>ta<221> brahma bh<220>rbhuvas suvarom. It means: `Om. ç
He is water, light, flavour, ambrosia and also the three worlds'.
(In effect, it means that water, light and other things are all manifestations ç
of the Brahman indicated by the Pra<207>ava.)
This g<193>yatr<200>·iras too is used only in the process of pr<193>n<193>y<193>ma ç
and not in the japa of the G<193>yatr<200>mantra.
The G<193>yatr<200>mantra can also be used for pura·cara<207>a†a particular ç
ceremonial mode of repeating the mantra†in order to secure certain ç
special fruits or results. The following are the usual steps involved ç
init: daily rituals like Sandhy<193>vandana, worship of the goddess ç
G<193>yatr<200>, japa of the G<193>yatr<200>-mantra, homa (fire ritual), ç
tarpa<207>a (offering of water ceremonially) and feeding of the br<193>hma<207>as. ç
However, it should be done under the guidance of experts.
In imitation of this G<193>yatr<200>mantra, several more mantras have ç
appeared in later literature on the various cult deities like R<193>ma, ç
K<216><218><207>a, <185>iva, Dev<200>, Ga<207>apati and others.
See Mah<193>n<193>r<193>ya<207>opani<218>ad 1.22<|>t<%18>o<%0>33.
See also <MS>G°YATR®.<D>
@SPACE = 
@SPACE = 
@NT = ghanap<193><219>ha
@SPACE = 
@SPACE = 
The Vedas are the basic scriptures of Hinduism. The Sa<221>hit<193>s ç
are the core part of these Vedas. These Sa<221>hit<193>s had to be ç
committed to memory and passed on orally from generation to generation. ç
Even now they have been preserved in a pure form. This was possible ç
only due to the unique system of chanting that had been evolved, consisting ç
of padap<193><219>ha, kramap<193><219>ha, ja<219><193>p<193><219>ha ç
and ghanap<193><219>ha, which are all various chanting modes.
These four modes of chanting can be explained more clearly by choosing ç
one sentence from the <184>gveda Sa<221>hit<193> (10.97.22) and ç
working upon it.
@SPACE = 
@SPACE = 
@SB = sa<221>hit<193>p<193><219>ha
@SPACE = 
@PATA1 = <+> <|>|<+><+><+><+><+><+><+><+><+><+><+><+><+><+><+><+><+><+><+><+><+><+>|       <|>        <%-23>|<%0>|
@PJLS = o<MIO><218>a<D>dhaya<199> sa<221> <MIO>va<D>dante ç
so<MIO>me<D>na
@SPACE = 
@PATA1 = <|><+><+><+>        <+><+><W1%-23>|<D%0>|
@PJLS = saha r<193>j<MIO><210><193><F49P12M>e<F255P255D>
@SPACE = 
@SPACE = 
@SB = padap<193><219>ha
@SPACE = 
@PATA1 = <|><+><+>|
@PJ1LS = o<MIO><218>a<D>dhaya<199><F49P12M>e<F255P255D> sa<221><F49P12M>e<F255P255D> ç
vadante<F49P12M>e<F255P255D>
@PATA =    <|> 1           2   <|> <|> 3
@SPACE = 
@PATA1 =     <W1%-23>|<D%0>|                      <W1%-23><|>|<D%0>|
@PJ1LS = so<MIO>me<D>na<F49P12M>e<F255P255D> saha<F49P12M>e<F255P255D> r<193><MIO>j<210><193><F49P12M>e
@PATA =    <|>4     <|> 5        6
@SB = kramap<193><219>ha
@PATA1 = <|> |                                |
@PJ1LS = o<MIO><218>a<D>dhaya<199> sa<221><F49P12M>e<F255P255D> sa<221> ç
<MIO>va<D>dante<F49P12M>e
@PATA =      1         2   <|>  2       3
@PATA1 =                   <W1%-23>|<D%0>|             <W1%-23>|<D%0>|
@PJ1LS = vadante so<MIO>me<D>na<F49P12M>e<F255P255D> so<MIO>me<D>na saha<F49P12M>e
@PATA =    <|>3          4         4        5
@PATA1 =              <W1%-23>|<D%0>|             <|>        <W1%-23>|<D%0>|
@PJ1LS = saha r<193><MIO>j<210><193><F49P12M>e<F255P255D> r<193>j<210>eti ç
r<193><MIO>j<210><193><F49P12M>e
@PATA =   5      <|>6        6       <|>6
@SPACE = 
@SB = ja<219><193>p<193><219>ha
@SPACE = 
@PATA1 =    |                               <|>|
@PJ1LS = o<MIO><218>a<D>dhaya<199> sa<221> samo<MIO><218>a<D>dhaya
@PATA =      1         2       2      1
@PATA1 = <|>  |
@PJ1LS = o<MIO><218>a<D>dhaya<199> sa<221><F49P12M>e
@PATA =    1           <|>2
@PATA1 =          |
@PJ1LS = sa<221> <MIO>va<D>dante vadante sa<221>
@PATA =  <|>2       3          3       2
@PATA1 =    <|><|>     | 
@PJ1LS = sa<221> <MIO>va<D>dante<F49P12M>e
@PATA =   2      <|>3
@SPACE = 
@SB = ghanap<193><219>ha
@SPACE = 
@PATA1 =  <|> |                              |
@PJ1LS = o<MIO><218>a<D>dhaya<199> sa<221> samo<MIO><218>a<D>dhaya
@PATA =       1        <|>2     2   <|>1
@PATA1 = <|> |                     <|> |
@PJ1LS = o<MIO><218>a<D>dhaya<199> sa<221> <MIO>va<D>dante
@PATA =    1           2        3
@PATA1 =                       |    <|>         |
@PJ1LS = vadante samo<MIO><218>a<D>dhaya o<MIO><218>a<D>dhaya<199>
@PATA =    3        <|>2      <|>1        1
@PATA1 =       <|>  |
@PJ1LS = sa<221> <MIO>va<D>dante
@PATA =   2      3
@PATA1 =          |  
@PJ1LS = sa<221> <MIO>va<D>dante vadante sa<221>
@PATA =  <|>2       3         <|>3      <|><|>2
@PATA1 =          |        <|>       <W1%-23>|<D%0>|
@PJ1LS = sa<221> <MIO>va<D>dante so<MIO>me<MIU>na....
@PATA =  <|>2       3          4
@SPACE = 
When the text of the Sa<221>hit<193> is broken into the constituent ç
words as per the rules of the pr<193>ti·<193>khyas (works connected ç
with phonetics of the Vedas) we get the padap<193><219>ha first. The ç
other p<193><219>has or readings can be got by a permutation and combination ç
of the words of the padap<193><219>ha. By numbering these words, the ç
other p<193><219>has can be shown as follows:
@N-1 = kramap<193><219>ha†1+2, 2+3, 3+4, 4+5, 5+6.
@N-1 = ja<219><193>p<193><219>ha†1+2, 2+1, 1+2; 2+3, 3+2, 2+3;<R>ç
                       and so on.
@N-1 = ghanap<193><219>ha†1+2, 2+1, 1+2+3, 3+2+1,<R>ç
<+><+><+><+><+><+><+><+><+><+><+><+>1+2+3; 2+3, 3+2, 2+3+4,<R>ç
<+><+><+><+><+><+><+><+><+><+><+><+>4+3+2, 2+3+4 and so on.
Since the words are repeated several times in different ways, not ç
only the words but also the svaras or intonations have been preserved ç
over the centuries.
@NT = gha<207><219><193>
@N1 = (`that which makes sound')
Gha<207><219><193> or bell is an indispensable part of ritualistic ç
worship. No worship can be started or performed without sounding it ç
first. It is said to embody in itself all the musical instruments. ç
The sound of a bell is Pra<207>ava or O<209>k<193>ra, perceptible ç
to the ears.
@SPACE = 
It is generally made of bronze.
The body of the bell represents Ananta (the divinity of time) and ç
the tongue, Sarasvat<200> (the goddess of speech). The handle signifies ç
pr<193><207>a·akti or the energy of pr<193><207>a. Usually, the top ç
of the handle is adorned by the images of Hanum<193>n or Garu<195>a ç
or a cakra (discus) or Nandi (the bull-mount of <185>iva) or a tri·<220>la ç
(trident).
When the bell is sounded in p<220>j<193> or worship it is an invitation ç
for the gods to come and a warning for the evil spirits to depart ç
immediately.
The sound of the bell is said to rouse the power of the mantras used ç
in worship. Hence, it is sometimes called `mantram<193>t<193>' (`mother ç
of mantras').
The bell is sounded during p<220>j<193> and homa at various stages: ç
<193>v<193>hana (inviting the deity), sn<193>na (giving bath to the ç
image or the symbol), dh<220>pa (waving of incense), d<200>pa (waving ç
of a lighted lamp), at the end of chanting of hymns, p<220>r<207><193>huti ç
(final offering) and so on.
It is the usual practice to hang a bell or a few bells in a temple, ç
in front of the main shrine. Devotees are expected to ring them as ç
they enter.
@NT = Gha<207><219><193>kar<207>a
@N1 = (`one wearing bells on the ears')
To what ridiculous extent the devotion of a votary towards his i<218><219>adevat<193> ç
or chosen deity can go, is illustrated by the story of Gha<207><219><193>kar<207>a. ç
He was a staunch devotee of <185>iva and an inveterate hater of Vi<218><207>u. ç
Not wishing even to listen to the name of Vi<218><207>u, he used to ç
hang two bells from his ears, so that their sound could drown the ç
sound of the name of Vi<218><207>u if ever uttered by anyone in his ç
presence! However, he is said to have overcome this and become a devotee ç
of Vi<218><207>u too, thanks to the intervention of <185>iva himself.
According to another story, Gha<207><219>a and Kar<207>a were two ç
r<193>k<218>asa brothers who attained salvation by propitiating Vi<218><207>u ç
through severe austerities.
Gha<207><219><193>kar<207>a was also the name of a terrible goblin ç
created by <185>iva to eradicate cutaneous diseaseslikesmallpox. ç
He became, in course of time, a minor village deity, established in ç
a temple of his own and worshipped. By his grace several diseases, ç
especially those born out of sins committed in the previous lives, ç
are cured. His image has 18 hands, holding several articles like vajra ç
(thunderbolt), sword, discus, arrow, broom, rope, bell, pick-axe and ç
so on.
According to another version in the pur<193><207>as Gha<207><219><193>kar<207>a ç
was a ghoul, but devoted to Vi<218><207>u. He was ultimately saved ç
by K<216><218><207>a.
Gha<207><219><193>kar<207>a is counted among the attendants of Skanda ç
(Subrahma<207>ya) and also Kubera, the lord of wealth presiding over ç
the northern quarter.
@NT = gha<219>a
@N1 = (`a pot')
A gha<219>a or a mud-pot is an important accessory in many a Hindu ç
ritual. When filled with water and decorated with certain leaves and ç
coconut it becomes fit for any deity being ceremonially invoked into ç
it. Such a gha<219>a is also called a kumbha or a kala·a. It is one ç
of the four receptacles of divinity, the other three being agni (fire), ç
vigraha (icon) and stha<207><195>ila (consecrated platform).
It is sometimes used as an art motif indicating auspiciousness and ç
abundance, on the pillars and doors in temples.
A ceremonially installed pot is an essential part of the worship of ç
the Divine Mother Durg<193> during  the  Navar<193>tra festival.
According to the works on Ha<219>hayoga, gha<219>a or gha<219><193>vasth<193> ç
is a state of pr<193><207><193>-y<193>ma. In this state, the two pr<193><207>as ç
or vital airs†the pr<193><207>a and the ap<193>na†are in a balanced ç
state leading to the union of the j<200>va (individual soul) with ç
Param<193>tman (the Supreme Soul).
In philosophical and mystical treatises, the word `gha<219>a' is sometimes ç
used to indicate the body, since it is as fragile as a mudpot.
@NT = gha<219>am
Indian music, though originally one, gradually branched off into two ç
systems: the North Indian (Uttar<193>di) and the South Indian (Dak<218>i<207><193>di). ç
The SouthIndian classical music retained its original flavour whereas ç
the North Indian system attained a distinctness of its own due to ç
the Persian influence  wrought during  the Mughal period.
Among the percussion instruments used in the South Indian classical ç
music †vocal or instrumental†the m<216>da<209>gam is the most important. ç
The next in importance is the gha<219>am. It is actually a large earthen ç
pot carefully prepared so as to give a musical sound when beaten, ç
with the finger-tips and palms of the hands.
Unlike the m<216>da<209>gam, the ·ruti or the tonic of the gha<219>am ç
cannot be changed. Hence, the player of a gha<219>am generally keeps ç
a large number of them to suit the different ·rutis of the singers.
@NT = gha<219>aspho<219>a
@N1 = (`[the rite of] breaking a pot')
Though it is human to err and divine to forgive, there are human beings ç
addicted to committing heinous sins but reluctant to repent or perform ç
expiations. Gha<219>a-spho<219>a is the ritual method of excommunicating ç
such incorrigibles from the society.
In this rite, a gha<219>a or an earthen pot, filled with dirty water ç
is kept on a bed of darbha grass and a slave girl or man is made to ç
kick it with her or his left foot so that it is overturned, spilling ç
all the water. By this ritual, the sinner is considered to have become ç
dead for the society. His near relatives observe†after this  gha<219>aspho<219>a†a·auca  (ceremonial ç
impurity) and also offer pi<207><195>as (rice-balls) in his name as ç
to a dead person.
@NT = Gha<219>otkaca
@N1 = (`one [whose head] is<R>ç
hairless [like that of] a gha<219>a or pot')
Out of the many characters of the Mah<193>bh<193>rata, that of Gha<219>otkaca ç
is rather short, but interesting. Born absolutely bald, without any ç
hair on his head (hence the name Gha<219>a + ut + kaca = Gha<219>otkaca). ç
He was the son of Bh<200>ma (the second of the P<193><207><195>ava ç
heroes) and Hi<195>imb<193>, the sister of the demon Hi<195>imb<193>sura ç
whom Bh<200>ma had slain. As per the boon received by the r<193>k<218>asa ç
(or demon) race from the goddess P<193>rvat<200>, any offspring of ç
the r<193>k<218>asas would attain adulthood immediately after birth ç
itself. So Gha<219>otkaca attained physical and mental adulthood soon ç
after birth. When Bh<200>ma left Hi<195>imb<193> and her son Gha<219>otkaca ç
to rejoin his brothers and mother, Gha<219>otkaca promised to help ç
him and serve him in any way, as soon as he just remembered this son ç
of his.
He helped the P<193><207><195>avas in several ways especially when ç
they were under- going banishment in the forest.
He fought the Kauravas fiercely on behalf of the P<193><207><195>avas ç
but was killed by Kar<207>a who was forced to use his weapon <185>akti, ç
which he had reserved for Arjuna!
@SPACE = 
@NT = Ghera<207><195>a Sa<221>hit<193>
@SPACE = 
Ha<219>hayoga is an important aspect of yogic discipline. If R<193>jayoga ç
deals with disciplining the mind, Ha<219>hayoga concentrates on purifying ç
and disciplining the body through <193>sanas, mudr<193>s and pr<193><207><193>y<193>mas.
The Ghera<207><195>a Sa<221>hit<193> is one of the two important ç
texts of Ha<219>hayoga, the other being Ha<219>hayogaprad<200>pik<193>.
This work comprises 350 ·lokas or verses spread over seven chapters. ç
It is in the form of a dialogue between Ca<207><195>ak<193>p<193>li ç
and his preceptor, the sage Ghera<207><195>a.
The first chapter with 49 ·lokas deals with <218>a<219>karmas or the ç
six purificatory exercises like dhauti, basti and so on. These purificatory ç
processes are explained in detail.
The second chapter with 45 ·lokas delineates the various yog<193>sanas, ç
32 in all, like padm<193>sana, dhanur<193>sana, ·ala-bh<193>sana, ç
bhuja<209>g<193>sana and others.
The third, with 100 ·lokas, is the biggest chapter. It explains several ç
mudr<193>s like mah<193>mudr<193>, nabhomudr<193>, <193>mbhas<200>-mudr<193> ç
and others, totaling 30 in all.
The fourth chapter, the shortest, has only seven verses and deals ç
with praty<193>-h<193>rayoga, the art of withdrawing the mind from ç
all factors that disturb yoga or concentration and meditation.
The fifth chapter, also a long one, has 96 verses. It deals with pr<193><207><193>y<193>ma ç
or the control of the pr<193><207>ic energy through breath-control. ç
A variety of exercises like kumbhaka and bhastrik<193> are described. ç
In this section stress is also laid upon the quality of food that ç
a yogi can take and its regulation.
The sixth chapter, with only 22 verses, is concerned with dhy<193>nayoga ç
or the yoga of meditation. It gives a few varieties of dhy<193>na ç
with some practical instructions.
The last chapter†the seventh†with 23 verses, describes a few types ç
of sam<193>dhi like dhy<193>nayogasam<193>dhi and n<193>dayoga-sam<193>dhi.
Once sam<193>dhi is attained, the yogi has no rebirth. He attains ç
emancipation.
@SPACE1 = 
The various exercises described in this work must be practised only ç
under the direct guidance and supervision of an expert in the field.
@NT = Ghora °<209>girasa
@N1 = (`the terrible descendant of the [sage] A<209>giras')
The Ch<193>ndogya Upani<218>ad (3.17.6) while dealing with puru<218>ayaj<210>a ç
(human life contemplated upon as a sacrifice) has mentioned that the ç
sage Ghora °<209>girasa taught this science to K<216><218><207>a Devak<200>putra. ç
It is well-known from the Vi<218><207>upur<193><207>a (5.21.19) ç
and the Bh<193>gavata (10.45.31) that S<193>nd<200>pani of Avanti ç
was the teacher of K<216><218><207>a (and Balar<193>ma). The question ç
is whether the two sages were one and the same.
Ghora was one of the eight sons of the sage A<209>giras. Hence he ç
was known as `Ghora-°<209>girasa'. (°<209>girasa = a descendant of ç
A<209>giras.) If S<193>nd<200>pani belonged to the A<209>giras gotra ç
(lineage) and had the appellation `ghora' (`the terrible') since he ç
was a strict disciplinarian, the two sages can be deemed as one and ç
the same person. But there is no clinching evidence to proveit.
@NT = Gho<218><193>
Out of the 27 brahmav<193>din<200>s (women seers) mentioned in the ç
<184>gveda, Gho<218><193> is also one. Two entire hymns of the tenth ç
ma<207><195>ala (39 and 40) are her contribution. Her grandfather ç
was the sage D<200>rgha-tamas and Kak<218><200>v<193>n was her father.
The story goes that she was a victim of a fell disease because of ç
which she had to remain in her father's house and unmarried. As she ç
was getting old there, she decided to pray to the twin gods, the A·vins ç
who were known as divine physicians endowed with the power of rejuvenation. ç
The hymns 39 and 40 of the tenth ma<207><195>ala are her prayers. ç
Pleased with her earnest entreaties, the A·vins granted her youth ç
and a worthy husband. Her son Suh<193>sya is the <216><218>i or the ç
sage of the next hymn, the 41st.
@NT = gh<216>ta
Gh<216>ta (ghee, clarified butter) has been held in high esteem right ç
from the <184>gvedic times. Libation of gh<216>ta into a duly consecrated ç
fire is a part of many a ritual in Hinduism. Lighting a lamp in front ç
of a deity using gh<216>ta instead of oil has been considered as a ç
meritorious act.
The Su·ruta Sa<221>hit<193> attributes many medicinal qualities ç
to ghee such as cures of diseases like insanity, epilepsy, colic  and  fever.  `Kumbhagh<216>ta',  ghee ç
matured in a pitcher for eleven to a hundred years, willbecome possessed ç
of mystic potencies capable of warding off monsters!
Gh<216>ta, cooked a hundred times in succession with a quantity of ç
vac<193> (an aromatic root) and taken every day extends one's life ç
to five centuries!
@NT = Girija-Narasi<221>ha
@N1-1 = (`Man-lion [incarnation] emerging out of a mountain cave')
N<216>si<221>ha or Narasi<221>ha is the fourth in the series of the ç
ten incarnations of Vi<218><207>u generally known as `Da·<193>vat<193>ras'. ç
His head is that of a lion (= si<221>ha) whereas the rest of the body ç
is that of a human being ( = nara).
As per the stories of the Bh<193>gavata (7.8.18-23) and the Vi<218><207>upur<193><207>a ç
(1.32) he emerged out of a pillar in the court-hall of the demon-king ç
Hira<207>yaka·ipu. However in some iconographical works, he is described ç
as having emerged out of cave in a hill (giri = hill, ja = born or ç
emerge) like an infuriated lion in a flash of blinding light. Hence ç
the name Girija-Narasi<221>ha.
In this form he is shown alone, without Lak<218>m<200> or Prahl<193>da. ç
He may have two arms or four arms. In the latter posture, the upper ç
two hands are holding the usual emblems of Vi<218><207>u†the conch ç
and the discus†whereas the two lower hands  are  thrown  forward  to  seize ç
Hira<207>yaka·ipu.
The complexion of this form is des-cribed as white and the garments ç
red. The crown on the head is of the kara<207><195>a-maku<219>a (honeycomb) ç
type.
@NT = G<200>t<193>
See <MS>BHAGAVADG®T°.<D>
@NT = G<200>ta-govinda
@N1 = (`song concerning Govinda [or K<216><218><207>a]')
One of the most popular of all the lyrics in Sanskrit is the G<200>tagovinda ç
of Jayadeva (12th cent. <MS>A.<|>D.<D>). The work comprises 12 sargas ç
or sections, each containing 24 stanzas set to music. The poet himself ç
has fixed the r<193>gas (tunes) and t<193>las (time-beats) so that ç
they can be sung by musicians and also adopted by dancers.
The main theme is the love of R<193>dh<193> for K<216><218><207>a ç
and his response.
The work is considered as a master-piece in Sanskrit poetry and a ç
model for many a later writer. Perfection of metrical form and a wonderful ç
display of human feelings and sentiments mark it out as an extraordinary ç
piece of Sanskrit literature. It also shows to what heights the Sanskrit ç
language can rise as regards beauty, elegance and even sublimity.
@SPACE1 = 
See also <MS>JAYADEVA<D>.
@NT = G<200>t<193> Press
@SPACE = 
@SPACE = 
Generally speaking, Hinduism and organised propagation of its tenets ç
are poles apart! The very nature of Hinduism, which lays great stress ç
on personal mukti or individual liberation, prevents it.
However, over the last two centuries, several attempts have been made ç
to propagate either general Hinduism or some of its cults through ç
various religious movements and organisations. One such organisation  that  is  rendering  great ç
service to the cause of Hinduism quietly and unostentatiously, is ç
the Gita Press of Gorakhpur in Uttar Pradesh.
Since the Bhagavadg<200>t<193> or the G<200>t<193> is the most ç
popular scripture, accepted by almost all the sections of the Hindus, ç
the late Jayday<193>l Goe<209>k<193> established the G<200>t<193> ç
Press in <MS>A.<|>D.<D> 1923. Its Govind Bhavan K<193>ry<193>laya (office) ç
at Calcutta has been registered  under the Registration  of Societies ç
Act of West Bengal, 1961. The institution is managed by a board of ç
trustees.
The primary purpose of establishing the G<200>t<193> Press was to ç
propagate Hinduism by printing and sellingatahighly subsidised ç
price, Hindu religious literature. This includes the Bhagavadg<200>t<193>, ç
the Upani<218>ads, the R<193>m<193>ya<207>a, the Mah<193>-bh<193>rata, ç
the Bh<193>gavata, the pur<193><207>as, other religious works like ç
the R<193>mcarit-M<193>nas, the N<193>rada Bhaktis<220>tras, Ved<193>ntic ç
works like the Vivekac<220><195><193>ma<207>i, compendiums of stotras ç
or hymns, lives of saints and so on.
Till now (March 1998) a total number of 270 million copies of these ç
books have been printed and circulated.
These books have been mostly in Sanskrit and Hindi languages as also ç
English. Recently, the same books are being brought out in other regional ç
languages also.
Two monthly journals†Kaly<193><207> in Hindi and Kaly<193><207>a ç
Kalpataru in English† are also being published. These journals have ç
become extremely popular.
The main gate of the G<200>t<193> Press of Gorakhpur is very impressive ç
and has incorporated  in  itself  the  special architectural features ç
from several parts of India.
The L<200>l<193> Citra Mandir houses hundreds of pictures depicting ç
the incidents from the lives of R<193>ma and K<216><218><207>a. <185>lokasfrom ç
the G<200>t<193> and the sayings of saints like Tulas<200>d<193>s, ç
Kab<200>r, D<193>d<220>day<193>l, Sundard<193>s, Rah<200>m and others ç
have been inscribed on the walls. Every year, during the G<200>t<193> ç
Jayanti celebrations, special exhibitions of G<200>t<193> literature ç
(including rare books in several languages) are organised.
There is a G<200>t<193> Bhavan at Svarg<193>·ram (Uttar Pradesh) on ç
the bank of the river Ga<209>g<193>, run by the G<200>t<193> Press. ç
It has more than 1000 rooms, to accommodate s<193>dhakas (spiritual ç
aspirants) who throng to the place now and then.
The G<200>t<193> Press is also running a <184><218>ikul-Brahmacary<193>·rama  at  C<220>r<220> ç
in Rajasthan,  to impart training  on the Gurukula model, to willing ç
students.
@SPACE1 = 
The Govind Bhavan K<193>ry<193>laya at Calcutta,  the  Head  Quarters  of  the ç
organisation has facilities for the chanting of the G<200>t<193> ç
and religious discourses. An <193>yurvedic dispensary is also attached ç
to the same.
@NT = G<200>t<193>rthasa<209>graha
@N1 = (`an abridgement of the essentials of the G<200>t<193>')
@EMERGENCY = Though theVi·i<218><219><193>dvaitaVed<193>nta philosophy ç
has been expounded and elaborated by R<193>m<193>nuja (<MS>A.<|>D.<D> ç
1017-1137), the contribution of his predecessors was considerable. ç
Among them Y<193>mun<193>c<193>rya (<MS>A.D.<D> 918-1038) was the ç
most celebrated. He wrote three works in Sanskrit, out of which the ç
G<200>t<193>rthasa<209>graha is also one. On this, two commentaries ç
are available: G<200>t<193>rthasa<209>graha-rak<218><193> by Ved<193>nta ç
De·ika (<MS>A.<|>D.<D> 1268-1370) and G<200>t<193>rtha- sa<209>graha-d<200>pik<193> ç
by Varavara Muni (<MS>A.<|>D.<D> 1370-1443).
The work has only 32 ·lokas or verses summarising the whole Bhagavadg<200>t<193>.
The first verse declares that God, the Supreme, is N<193>r<193>ya<207>a ç
and that he can be attained by bhakti or devotion alone.
Verses 3 to 5 state that the G<200>t<193> can be divided into three ç
<218>a<219>kas or triads of 6 chapters each. The first <218>a<219>ka ç
(chs. 1-6) states that <193>tm<193>nubh<220>ti or self-realisation ç
can come through the performance of desireless action (ni<218>k<193>ma ç
karma), know-ledge (j<210><193>na) and meditation (yoga).
The second <218>a<219>ka states that Bhakti-yoga, which results from ç
Karmayoga and J<210><193>nayoga, is the means for realising God and ç
gives some details about it.
@EMERGENCY = The third <218>a<219>ka deals with the rest of the relevant ç
topics (which subserve the previous two <218>a<219>kas), gives some ç
details of pradh<193>na or prak<216>ti (matter), puru<218>a (the individual ç
self), ®·vara (God) and some disciplines relating to j<210><193>na ç
(knowledge), bhakti (devotion) and karma (work).
@EMERGENCY = The verses 5 to 22 give very briefly, the gist of the ç
eighteen chapters of the G<200>t<193>, chapter by chapter.
The ideas spread over the rest of the ten verses†23 to 32†may be summarised ç
as follows:
Karmayoga is performing austerity (tapas), undertaking pilgrimages ç
(t<200>rtha-y<193>tr<193>), doing sacrifices and other similar activities.
Bhaktiyoga is meditation on God with love.
Obligatory (nityakarma) and occasio-nal (naimittika-karma) works are ç
associated with all the yogas.
Removal of nescience (aj<210><193>na) leads to the realisation of ç
the Self (the <193>tman) whereas practising supreme devotion (par<193>bhakti) ç
towards God will help the aspirant to attain the world of God.
Bhaktiyoga can give the aspirant whatever he wants†prosperity here ç
or salvation (kaivalya).
The man of supreme knowledge is also a man of supreme devotion since ç
they coalesce in the final stage.
The perfect being finds his supreme satisfaction in several acts connected ç
with devotion to God such as meditation, speaking about him, bowing ç
down to him, singing his praises and so on. In fact all his activities ç
are directed only to please God under all circumstances.
See also <MS>BHAGAVADG®T°<D> and <MS>Y°MUN°-C°RYA<D>.
@NT = Gobhila
Gobhila was an ancient sage who belonged to the group of followers ç
of the S<193>maveda. Nothing is known of him. Adherents of the Kauthuma ç
and the R<193><207><193>ya<207><200>ya schools of the S<193>maveda ç
consider his works as highly authoritative.
@SPACE1 = 
Three works are attributed to him: Gobhila G<216>hyas<220>tras, Gobhila ç
Sm<216>ti and Gobhila <185>r<193>ddhakalpa.
The Gobhila G<216>hyas<220>tras, the text of which has been fully ç
recovered, has four main sections called `prap<193><219>hakas'. Each ç
prap<193><219>haka is divided into `ka<207><195>ik<193>s' (chapters) ç
and the ka<207><195>ik<193>s have indi-vidual s<220>tras or aphorisms. ç
The total number of s<220>tras is 1089 accommodated in 39 ka<207><195>ik<193>s.
It has three commentaries by: Bha<219><219>a N<193>r<193>ya<207>a, ç
Ya·odhara and an unknown author (the commentary itself being called ç
Saral<193>).
Being a g<216>hyas<220>tra work, it naturally deals with the rites ç
and rituals connected with the life of a g<216>hastha or a householder. ç
The topics dealt with include some sacrifices like Pit<216>yaj<210>a, ç
P<193>rva<207>ayaj<210>a, A<218><219>ak<193>yaj<210>a, °grah<193>ya<207><200>yaj<210>a, ç
the pa<210>ca-mah<193>yaj<210>as (five daily sacrifices) and 13 sa<221>sk<193>ras ç
like j<193>takarma, upanayana, sam<193>vartana, viv<193>ha and antye<218><219>i.
The Gobhilasm<216>ti has been identified with the Karmaprad<200>pa ç
of K<193>ty<193>yana (4th cent. <MS>A.<|>D.<D>). It deals with the ç
usual topics found in the sm<216>tis and dharma·<193>stras like <193>c<193>ra ç
(daily routine and behaviour), the sandhy<193> ritual, japa of Vedic ç
mantras, ·r<193>ddha, a·auca, tarpa<207>a and so on.
The work Gobhil<200>ya <185>r<193>ddhakalpa has not been found till ç
now. Portions from it have been quoted in the works of other authors ç
like Raghunandana (<MS>A.<|>D.<D> 1510-1580) in his <185>r<193>ddhatattva.
@NT = Gobind Singh, Guru
@N1 = (<MS>A.<|>D.<D> 1666-1708)
@SPACE1 = 
Guru Gobind Singh, the tenth and the last, of the Sikh Gurus, has ç
carved out for himself a permanent place in the history of Sikhism ç
and Hinduism. It was he who infused the k<218>attriya (or martial) ç
spirit into the docile Sikh community and transformed them into the ç
now heroic race. But for the fights and supreme sacrifices of the ç
Guru, the fate of the Hindu society would have been sealed.
He was the son of the illustrious ninth Guru, Tegh Bahadur (<MS>A.<|>D.<D> ç
1620-1675) and succeeded him as the tenth Guru in <MS>A.<|>D.<D> 1675, ç
at the age of nine! Hereceived an extensive education and became ç
a noted writer in course of time.
In <MS>A.<|>D.<D> 1699 he started the nucleus of the kh<193>ls<193>, ç
(`the pure', `the Lord's own') at the Keshgarh S<193>hib, the most ç
important shrine (in Anandpur S<193>hib of Punjab) by baptising five ç
heroes who had come forward to sacrifice their lives at the Guru's ç
feet, by giving them the `am<216>t' (water in an iron bowl, mixed ç
by a dagger with some sugar cubes) as t<200>rtha or holy water. Later, ç
he himself was baptised by them. These five heroes became known as ç
the `Pa<210>j Piy<193>r<193>s,' the `five beloved ones'. On the same ç
day 20,000 Sikhs were baptised in this manner. Thus was born the new ç
militant order for the protection of the Sikhs.
Each member of the kh<193>ls<193> was expected to wear five k's. They ç
are: ke· (uncut hair), ka<209>gh<193> (comb), kar<193> (iron bangle),  k<193>c<193>  (loin-cloth)  and  kirp<193>n ç
(dagger or sword).
The Kh<193>ls<193>s were to be saint soldiers, worshippers of one ç
God, but, at the same time fighting injustice and oppression.
@SPACE1 = 
Guru GobindSinghfoughtmany battles against the Muslim kings and ç
the Mughal emperor Aurangzeb. Though he did win many battles, he had ç
to suffer also terribly. All his four sons sacrificed their lives ç
for the sake of their religion, the last two being brutally done with ç
by the Moghuls.
He was assassinated in <MS>A.<|>D.<D> 1708 by a hired Afghan fanatic.
Guru Gobind Singh declared that the line of the Sikh Gurus ended with ç
him and that the °di Granth compiled by Guru Arjan (<MS>A.<|>D.<D> ç
1563-1607) should itself be treated as the Guru and honoured as such. ç
Henceforward, the book came to be known as Guru Granth S<193>hib.
Guru  Gobind Singh  knew three languages†Braja, Persian and Punj<193>bi† ç
and wrote extensively. The writings included translations and summaries ç
of ancient Hindu scriptures and also an autobiography. These running ç
into 1300 large-size pages are now available under the title <185>r<200> ç
Da·am Granth or the book of the Tenth Guru.
By any standards, Guru Gobind Singh was an extraordinary personality ç
who left an indelible mark on Indian history.
See also <MS>SIKHISM.
@SPACE = 
@NT = goc<193>ra
@N1 = (`movement of the planets')
@SPACE = 
Hindu astrologyrecognisesnine planets which exercise a great influence ç
on the life of the human beings, both at the individual and at the ç
social levels. These are: Ravi (Sun), Candra or Soma (Moon), Ma<209>gala ç
or Kuja (Mars), Budha (Mercury), Guru or B<216>haspati (Jupiter), ç
<185>ukra (Venus), <185>ani (Saturn), R<193>hu and Ketu (lunar nodes). ç
These planets produce good or bad effects depending on their position ç
on the day in the zodiac, relative to the r<193>·i (zodiacal sign ç
like Me<218>a or Aries). The r<193>·i is that sign of the Zodiac where ç
the moon was present on the day of the birth of the person.
Goc<193>ra is the technical name given to the movement of these nine ç
planets, starting with the r<193>·i of the birth of the person, in ç
the eleven succeeding positions. These movements† depending upon the ç
particular planet and its position†give good or bad or mixed results.
@SPACE1 = 
For instance when Ravi (Sun) is in the r<193>·i of birth, he will ç
bring about disease. When Soma (Moon) is occupying the ninth house ç
from the r<193>·i of birth, quarrels arise in one's life. If Guru ç
(Jupiter) is occupying the eighth house, he causes loss of wealth. ç
If <185>ukra (Venus) is in the third house, he will bestow happiness. ç
If <185>ani (Saturn) is occupying the sixth house, wealth is gained.
The duration of stay of these planets in each of the r<193>·is has ç
been calculated by the astrological works. They are as follows:
@SPACE = 
@SPACE = 
@L2 = Ravi (Sun)	one month
@SPACE1 = 
@L2 = Candra or Soma<R>ç
<+><+>(Moon)	one day
@SPACE1 = 
@L2 = Kuja (Mars)	two<|>and<|>a<|>half<|>months
@SPACE1 = 
@L2 = Budha (Mercury)	one month
@SPACE1 = 
@L2 = B<216>haspati or Guru<R>ç
<+><+>(Jupiter)	twelve months
@SPACE1 = 
@L2 = <185>ukra (Venus)	one month
@SPACE1 = 
@L2 = <185>ani (Saturn)	thirty months
@SPACE1 = 
@L2 = R<193>hu and Ketu	twenty months
@SPACE = 
@SPACE = 
The details of the effects of the planets on one's life, on a particular ç
day, can be known by consulting an almanac and the tables given in ç
Hindu astronomical texts.
@SPACE1 = 
See also <MS>JYOTI<186>A<D>.
@NT = God
@SPACE = 
@SPACE = 
In Hinduism, God has been described by  various terms  such  as  Bhagav<193>n ç
(possessor of blessed qualities and power), Dh<193>t<193> (the Supporter ç
and the Sustainer of the world), ®·vara (the Lord), Para-m<193>tman ç
(the SupremeSelf),Parame·vara (the Supreme Lord), Vidh<193>t<193> ç
(the Creator) and so on.
Unlike the Semitic religions, Hinduism does not depend upon a single ç
scripture. However, the entire body of its philosophical literature ç
accepts the Upani<218>ads and, to a great extent, the Bhagavadg<200>t<193>, ç
as authoritative and does not go against them. Hence any concept of ç
God based on these books is welcome to practically all sections of ç
Hinduism.
While deriving the concept of God, it is but natural for man to start ç
from the world in which he lives and moves. So, the God of Hinduism, ç
when looked at from this angle, is the Creator. However, he creates ç
the entire world, not out of nothing which is illogical, but out of ç
himself. After creation, he sustains it with his power, rules over ç
it like an all-powerful emperor, meting out justice, as reward and ç
punishment, in accordance with the deeds of the individual beings. ç
At the end of one cycle of creation†Hinduism advocates the cyclic ç
theory of creation†he withdraws the entire world order into himself.
The Hindu scriptures are eloquent while describing the qualities of ç
God. He is all-knowing and all-powerful. He is the very personification ç
of justice, love and beauty. In fact, he is the personification of ç
all the blessed qualities that man can ever conceive of. He is ever ç
ready to shower his grace, mercy and blessings on his creation. Really ç
speaking, the very purpose of his creating this world is to shower ç
his blessings on the creatures, to lead them gradually from less perfect ç
states to more perfect ones. He is easily pleased by the prayers and ç
supplication of his devotees. However his response to these prayers ç
is guided by the principle, that it should not be in conflict with ç
the cosmic law concerning the general welfare of the world, and the ç
law of Karma concerning the welfare of the particular individual.
The Hindu concept of God has two special features. Depending upon ç
the needs and tastes of his votaries, he can appear to them in any ç
form they like to worship, and respond through that form. He can also ç
incarnate himself amongst human beings in order to lead them to his ç
own kingdom. And this incarnating is a continuing process, taking ç
place whenever and wherever he deems it necessary.
Then, there is the other, the imperso-nal, aspect of God, as the Absolute. ç
`Brahman' is the name usually given to this aspect. It means what ç
is infinitely big. It is the Infinite itself. It transcends everything ç
that is created. Yet it is so unlike anything we know that it defies ç
all description. It has been stated that the only way by which it ç
can be predicated, is the negative way: `Not this! Not this!'
In its own essential nature, it is defined as`Sat-cit-<193>nanda,'`existence- ç
consciousness-bliss'. It is the basis or substratum of all existence, ç
consciousness and joy.
@SPACE1 = 
Metaphysics points towards Brahman, the Absolute. A thinking mind ç
and a feeling heart†that is what a human being is†can accept only ç
God, the Creator and the Ruler (®·vara), since the world is very much ç
a reality to it. The correlation between the Brahman and this ®·vara, ç
though instinctively felt by the feeling heart, will ever remain an ç
enigma to the thinking mind! Could this be due to the mysterious power ç
of m<193>y<193>?
@SPACE = 
@NT = god<193>na
@N1 = (`gifting of a cow')
@SPACE = 
See <MS>COW<D>.
@SPACE1 = 
`God<193>na' is also the name of a sa<221>sk<193>ra or sacrament wherein ç
the hairon the head (go = hair) above the right ear is shaved off. ç
`Ke·<193>nta' is another name forit.
@SPACE1 = 
See <MS>KE<185>°NTA<D> for details.
@SPACE = 
@NT = God<193>var<200>
@N1 = (`the best of the givers of water')
@SPACE = 
Even today, a devout and orthodox Hindu, invokes seven sacred rivers ç
of India at the time of bath and also during the ritualistic worship ç
of the family deity. God<193>var<200> is one of them. Gautam<200> ç
and V<216>ddhaga<209>g<193> are two other names for it, though less ç
known.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
The invocation runs like this:
@P1 = ga<209>ge ca yamune caiva<R>ç
<|><+><+><+>god<193>vari sarasvati<F49P12M>e<F255P255D><R>ç
narmade sindhu k<193>veri<R>ç
<+><|><+><+>jale'smin sannidhi<221> kuru<F49P12M>f<F255P255D>
``Oh Ga<209>g<193>! Yamun<193>! God<193>var<200>! Sarasvat<200>! Narmad<193>! ç
Sindh<220>! K<193>ver<200>! Please be present in this water here!''
@SPACE = 
The water can be the one used for one's bath or for worshipping the ç
deity.
