Unlike the rivers Sarasvat<200> and Ga<209>g<193>, the name of God<193>var<200> ç
has not been mentioned in the Vedic literature. However there are ç
enough references to it in the two epics and the pur<193><207>as. ç
In importance and sacredness, it has been given a status next only ç
to that of Ga<209>g<193>. In fact the Brahmapur<193><207>a (78.77) ç
goes to the extent of declaring that the Ga<209>g<193> to thesouth ç
of the Vindhya mountains is Gautam<200> (God<193>var<200>).
The river originates from the Brahmagiri hill near Tryambake·var in ç
the Nasik district of Maharashtra State. It flows towards the east ç
and joins the Bay of Bengal near R<193>jamahendram (or Rajamundry) ç
where it is almost 6.4 kms. (4 miles) wide. It then divides itself ç
into two branches Gautam<200> God<193>var<200> and Vasi<218><219>ha ç
God<193>var<200>. The latter again branches off into Vainateya God<193>var<200>.
The total length of the river is 1465 kms. (915 miles). It is joined ç
by a few important tributaries like P<220>r<207><193>, Phenaga<209>g<193>, ç
Vardh<193>, Vainaga<209>g<193>, Pr<193><207>ahit<193>, Indr<193>vat<200> ç
and <185>abar<200>.
There ia an interesting legend in thepur<193><207>as according to ç
which the sage Gautama, the husband of Ahaly<193>, brought this river ç
(originally the Ga<209>g<193>) from the matted locks of <185>iva, ç
to this earth, near Brahmagiri. At his request, <185>iva also agreed ç
to stay near his hermitage. This became the famous Tryambake·vara.
According to the R<193>m<193>ya<207>a of V<193>lm<200>ki, <185>r<200> ç
R<193>ma lived in the Pa<210>cava<219><200> on the bank of the river ç
God<193>var<200>, during his sojourn in the Da<207><195>aka forest. ç
It was from here that S<200>t<193> was abducted by the demon-king ç
R<193>va<207>a.
A bath in the God<193>var<200>, especially during its Pu<218>kara-period ç
(when the planet B<216>haspati or Guru or Jupiter enters the zodiacal ç
sign Si<221>ha or Leo) is considered extremely holy. The Pu<218>kara-period ç
comes once in twelve years and lasts for 12 days.
<185>r<193>ddhas and tarpa<207>as offered to the manes during the ç
period, will save them from hell and may even give them liberation.
The holy places, of pilgrimage, situated on the banks of the God<193>var<200> ç
are: Govardhana, Janasth<193>na, N<193>sik and Pa<210>cava<219><200>. ç
There are several temples in these places. For the pilgrims who visit ç
N<193>sik, a bath in the R<193>maku<207><195>a, on the left bank of ç
God<193>var<200>, is a must.
The famous temple of R<193>ma at Bhadr<193>calam in the Khammam district ç
of Andhra Pradesh is another holy place on the God<193>var<200>, frequented ç
by the devotees.
@NT = godh<220>li
@N1 = (`[the auspicious time when] dust is raised by cows')
Any good work or activity has to be undertaken during a time that ç
is astrologically considered as auspicious. This has been the belief ç
of the Hindus for millennia.
One of the great events in life for a Hindu is marriage. Since it ç
is considered as a religious sacrament and not as a social contract, ç
choosing an auspicious time forits performance becomes even more  important.  Dharma·<193>stras  have ç
prescribed several, astrologically auspicious, times and periods for ç
this sacrament depending upon several factors. However, when a suitable ç
time or period is not near at hand, and when one is in a hurry to ç
celebrate the marriage due to other factors, godh<220>li lagna or ç
muh<220>rta is recommended.
Godh<220>li is defined as the time of the setting sun, when the cows ç
which had gone out for grazing, return home, raising dust with their ç
hoofs. (go = cow; dh<220>li = dust).
Though the actual period varies due to the particular season, the ç
duration is for two gha<219>ik<193>s or 48 minutes.
Since selecting the godh<220>li muh<220>rta is only an emergency measure, ç
it should not be resorted to when more auspicious periods are readily ç
available.
This muh<220>rta was also resorted to for invasions by kings.
@NT = Gokar<207>a
@N1 = (`the ear of the cow')
Out of the three extremely important places of pilgrimage for the ç
devotees of Lord <185>iva, Gokar<207>a is also one. The other two ç
are K<193>·<200> (V<193>r<193><207>asi) and R<193>me·varam. The three ç
together are called `Tristhal<200>'.
Gokar<207>a is on the west coast in South India. It is situated in ç
the Kumta taluk of the North Canara (or Uttarakannada) district of ç
the Karnataka State.
The story goes that R<193>va<207>a, the demon king of La<209>k<193>, ç
secured the <193>tmali<209>ga (the <185>ivali<209>ga containing the ç
very essence and power of Lord <185>iva) from <185>iva himself and ç
was bringing it in his hands with a view to establishing it in his ç
capital city. Since this would have ended in catastrophe for the gods ç
as well as the human beings, the gods worked out a stratagem by which ç
Ga<207>apati disguised as a young brahmac<193>rin would see that the ç
li<209>ga is some how placed on the ground. At the approach of sunset, ç
R<193>va<207>a wanted to perform his evening sandhy<193> ritual. He ç
gave charge of the li<209>ga to the boy Ga<207>apati who was found ç
loitering nearby, with the special instruction that it should not ç
be placed on the ground since it would then get stuck permanently. ç
Ga<207>apati accepted the responsibility stipulating the condition ç
that R<193>va<207>a should come back before he is called thrice, to ç
return. Ga<207>apati however, managed to call R<193>va<207>a three ç
times before he could finish his sandhy<193>, and kept the li<209>ga ç
on the ground. It got permanently fixed there.
After punishing Ga<207>apati by a severe punch on his head, R<193>va<207>a ç
tried all his might to uproot the li<209>ga but to no avail. In the ç
process, the li<209>ga got deformed into the shape of a gokar<207>a ç
or the ear of a cow. Hence the name `Gokar<207>a' for the place of ç
pilgrimage that sprang up there.
The <185>ivali<209>ga is known as `Mah<193>-bale·vara' (`®·vara of ç
infinite might') since even the mighty R<193>va<207>a could not move ç
it even by an inch!
The whole li<209>ga is under the ground and hardly 5 cms. (2 inches) ç
of it is seen above.
The temple is considered as very old and belongs probably to the early ç
christian era.
The sanctum is about 5.1 metres (17ft.) square. The kala·a or pinial ç
is made of brass. The height of the vim<193>na (tower over the sanctum) ç
is 18 metres (60ft.). The ra<209>gama<207><219>apa (hall in front ç
of the sanctum) is 18 metres by 9 metres (60ft. by 30 ft.).
Images of P<193>rvat<200>, Ga<207>apati and Nandi have been established ç
round the main shrine.
@SPACE1 = 
The icon of Ga<207>apati here is in the standing posture and is a ç
little peculiar in appearance. It is considered as very ancient (<MS>A.<|>D.<D> ç
600 to 700).
Mah<193>·ivar<193>tri is the biggest of the festivals observed here. ç
The rathotsava (temple car festival) is held on Ph<193>lguna ·ukla ç
pratipad (first day of the bright fortnight in the month Ph<193>lguna, ç
usually in February/March).
Ko<219>it<200>rtha is the biggest of the temple tanks where the pilgrims ç
bathe before visiting the temple. Some of the other bathing places ç
are: Bindut<200>rtha, Agastya-t<200>rtha, Ja<219><193>yut<200>rtha, ç
R<193>mat<200>rtha, P<193><207><195>ava-t<200>rtha and so on. For ç
those who undertake the pilgrimage to Gokar<207>a as a religious ritual, ç
the following are prescribed: bath in the Ko<219>it<200>rtha, fasting, ç
·r<193>ddha to the forefathers, bath in the sea, p<220>j<193>s at ç
the main temple and other temples and giving of gifts.
Two more Gokar<207>as have been mentioned in the pur<193><207>as as ç
existing near the Sarasvat<200> river and Mathur<193> (in Uttar Pradesh). ç
But they are not well-known now.
Gokar<207>a is the name of the saintly person mentioned in the Padmapur<193><207>a ç
(vide Uttarakha<207><195>a chs. 4 and 5). Born of a barren cow due ç
to the grace of a monk, Gokar<207>a had a human body with a cow's ç
ears. Hence the name `Gokar<207>a.' His devoted recital of the famous ç
pur<193><207>a, the Bh<193>gavata, brought liberation to all the ç
hearers.
@NT = Gokula
@N1 = (`the abode of cows')
Gokula or Nandagokula was the village where the child K<216><218><207>a ç
(and his elder brother Balar<193>ma) spent his childhood days. It ç
was a fertile and prosperous village of the cowherds situated on the ç
bank of the river Yamun<193>. Nanda was the chieftain of the village. ç
However, after K<216><218><207>a was attacked by a number of demons ç
sent by Ka<221>sa†who were all, of course, destroyed by him†the people ç
of the village migrated to the nearby V<216>nd<193>vana, also on the ç
bank of the Yamun<193> river.
The modern Gokula is about 8 kms. from Mathur<193> (in Uttar Pradesh), ç
lower down the stream, but on the opposite bank of the Yamun<193> ç
river. It is now the Head-quarters of the Vallabha sect of the Vai<218><207>avas.
@NT = Golden Temple
See <MS>HARIMANDIR.<D>
@NT = Goloka
@N1 = (`the world of light')
What happens to the person after the death of the physical body has ç
been the subject of discussion and conjecture in manyreligions of ç
the world. In Hinduism, especially in its mythological literature, ç
some special lokas or worlds (special regions of existence) are mentioned ç
to where extremely fortunate souls, deeply pious and spiritual persons, ç
go after their exit from this mundane existence. In the Vai<218><207>avite ç
works, Vaiku<207><219>ha and Goloka are prominently mentioned. The ç
former seems to be a more ancient concept. As the cult of K<216><218><207>a ç
developed, superseding the cult of Vi<218><207>u wherein K<216><218><207>a ç
was considered as only one of the incarnations of Vi<218><207>u, ç
K<216><218><207>a was projected as the maincult-deity, Supreme Brahman ç
in his personal aspect. Even Vi<218><207>u in Vaiku<207><219>ha and ç
<185>iva in his Kail<193>sa were pictured as inferior to K<216><218><207>a ç
and as his lower manifestations.
As per this K<216><218><207>a cult, he, the Supreme Brahman or the ç
Absolute, lives in Goloka (also called Mah<193>vaiku<207><219>ha and ç
V<216>nd<193>vana) which is his eternal abode. `Goloka' means `the ç
world of light' and not the world of cows as is often mistaken. ç
This light is all-pervading and extremely beautiful. It is the highest ç
world below which are situated other worlds like Vaiku<207><219>ha,  Kail<193>sa,  svarga  (heaven), ç
martya (world of mortals) and p<193>t<193>la (nether-world). Its extent ç
is 900 million square yojanas (1 yojana = 15 kms. or 9 miles). It ç
is full of brilliant light, precious stones and other riches. Even ç
the great yogis cannot perceive it, even in their dreams! However ç
the devotees of K<216><218><207>a have access to it. Those who go ç
there and live eternally, will never suffer from any disease or disability.
@NT = Gomat<200>
Gomat<200> is one of the sacred rivers mentioned in the Nad<200>s<220>kta ç
of the <184>gveda (10.75.6). There, it is a tributary of the river ç
Sindh<220> (Indus).
The modern Gomat<200> (spelt as Gomt<200>) is a tributary of the river ç
Ga<209>g<193> flowing near Lucknow (the capital of Uttar Pradesh).
According  to  some  mythological accounts, Kau·ik<200>, sister of ç
Vi·v<193>mitra, being cursed by her husband <184>c<200>ka, became ç
the river Gomat<200>.
<185>r<200> R<193>ma is said to have conducted the A·vamedha sacrifice ç
on the banks of this river.
The Mah<193>bh<193>rata (°diparva 169.20) says that one can get ç
rid of one's sins by drinking the water of this river.
The Sabh<193>parva of the same epic (vide 9.23) declares that ç
the goddess Gomat<200>, the presiding deity of the river, lives in ç
the court of Varu<207>a (the deity of the water principle or oceans), ç
serving him.
Sometimes Gomat<200> and Ga<209>g<193> are considered identical, the ç
former being given as one of the names of the latter (Skandapur<193><207>a, ç
K<193>·<200>kha<207><195>a 29-51).
According to <185><193>t<193>tapa, a writer on the dharma·<193>stras ç
referred to by others, Gomat<200>is a type of Vedic mantra used in ç
pr<193>ya·cittas or expiations, especially for killing a cow.
@NT = Gomma<219>e·vara
@N1 = (`lord of Cupid', `lord of beauty')
Establishingtheimagesofgreat persons in public places seems to ç
be a natural trait of human beings in almost all the cultures and ç
civilisations of the world. But in India, where religion gets precedence ç
over all other aspects of life, the images of gods and saints are ç
seen carved out or put up everywhere, especially in places of pilgrimage.
One of the images of Jaina tradition more frequently found is that ç
of Gomma-<219>e·vara (also spelt as `Goma<219>e·vara'), mostly in ç
the Karnataka State.
Gomma<219>e·vara's earlier name was B<193>hubali. He was the last ç
son of V<216><218>abha-n<193>tha, the first of the T<200>rtha<209>karas ç
(founders of Jainism). After distributing his kingdom among his children, ç
V<216><218>abha-n<193>tha retired for tapas. Bharata, the eldest son, ç
started on an invasion tour and conquered all the kings except his ç
own brothers.  When  challenged,  they  too renounced the world and ç
retired for tapas, abdicating their kingdoms in his favour. However, ç
B<193>hubali, the youngest of the brothers, refused to oblige. When ç
Bharata fought a duel with him, he was defeated. But B<193>hubali, ç
eventhough he was the victor, refused to be the emperor and started ç
performing severe tapas standing in the same place. He attained enlightenment ç
very soon. Bharata established his image in Paudanapura (near Ujjayin<200> ç
in Madhya Pradesh).
There are quite a few images of Gomma<219>e·vara or B<193>hubali in ç
India, most of them being in the Karnataka State. The relief figure, ç
about 2<|>1/4 metres (7<|>1/2 ft.) high found in a Jaina cave of B<193>d<193>m<200> ç
(in Karnataka) is the earliest among these (7thcent. <MS>A.<|>D.<D>). ç
There is another in the Me<207>ada-basadi of Aiho<202>e (Bijapur district ç
of Karnataka) probably belonging to the period <MS>A.<|>D.<D> 750.
Some Gomma<219>e·vara icons are foundin the Jaina caves of Ellora ç
(in Maharashtra) also.
By far, the biggest and the most well-known of all these images is ç
the one on the hillock in <185>rava<207>abe<202>ago<202>a (Hasan district ç
of Karnataka). It has been sculptured out of a single stone on a small ç
hillock. C<193>mu<207><195>ar<193>ya, the prime minister of the king ç
R<193>camalla of the Ga<209>ga dynasty is said to have got it made ç
during the period <MS>A.<|>D.<D> 978-983. It is 17.4 metres (58ft.) ç
high. There is a beautiful, but almost imperceptible, smile on his ç
face. The body is naked and covered with wild creepers here and there.
@SPACE1 = 
Other images of Gomma<219>e·vara are at K<193>rka<202>a (12.5 metres ç
or 41.5 ft.), Ve<207><220>r (10.5 metres or 35 ft.), Dharmastha<202>a ç
(11.7 metres or 39 ft.), Goma<219>agiri (5.4 metres or 18 ft.) and ç
Bastiha<202><202>i (5.4 metres or 18 ft.). All these are in the Karnataka ç
State only.
The image at K<193>rka<202>a was established by V<200>rap<193><207><195>ya ç
in <MS>A.<|>D.<D> 1432 and the one at Ve<207><220>r by Timma<207><207>a ç
Ajila in <MS>A.<|>D.<D> 1604. The Dharmastha<202>a image was installed ç
very recently, in 1973.
@NT = gomukha
@N1 = (`mouth of the cow')
Gomukha is the place of origin of the river Ga<209>g<193>. It is considered ç
as a highly sacred place. Sixteen kilometres (ten miles) from Ga<209>gotri ç
(in Uttaranchal) a rivulet Devag<193><195>, joins the Ga<209>g<193>. ç
At a further distance of 6.5 kms. (4 miles) there is pine-grove. Gomukha ç
is further up from here. Here, the river Ga<209>g<193> emerges from ç
below a glacier. Water of the river is extremely cold. Pilgrims are ç
advised to visit before the sun rises up, since the heat of the sun's ç
rays will start melting the rocks of ice and so it will be very difficult ç
for them to walk back.
Gomukha is also the name of one of the yog<193>sanas described in ç
Ha<219>hayoga.
Vai<218><207>ava s<193>dhakas, generally, use an L-shaped  cloth-bag  to  conceal  their ç
japam<193>l<193> (rosary) while doing japa. This is called `gomukha'.
@SPACE = 
@NT = Gomukha-prasava-·<193>nti
@SPACE = 
Belief in astrological phenomena and predictions based on the horoscope ç
is very strong in the Hindu society even today. The °·le<218>a nak<218>atra ç
(the stars comprising eta, sigma, delta, epsilon, rho and zeta hydrae) ç
is considered r<193>k<218>asa or demoniac in nature and hence birth ç
under it is considered inauspicious for the baby. To ward off the ç
evil effects the Gomukha prasava-·<193>nti is performed by the parents. ç
The whole rite is aimed at making the baby to be `reborn' (prasava) ç
from the mouth of a cow (gomukha) at an auspicious moment.
Keeping the new-born baby in a winnowing basket covered with a piece ç
of cloth, bringing the basket near the mouth of a cow (as if it is ç
new born from the cow's mouth), bathing it with the milk of the cow, ç
handing it over to the father and then to the mother, all the while ç
chanting appropriate Vedic mantras†these are some of the steps involved ç
in the rite.
@SPACE = 
@NT = Gop<193>la-p<220>rvat<193>pin<200> Upani<218>ad
@SPACE = 
Modern scholars generally divide the Upani<218>ads†the basic scriptures ç
of Ved<193>nta philosophy†into two groups: TheMajor Upani<218>ads ç
and the Minor Upani<218>ads. The words `major' and `minor' do not ç
refer to their size but only to the importance given to them by the ç
earliest of the three well-known <193>c<193>ryas, viz., <185>a<209>kara ç
(<MS>A.<|>D.<D> 788-820) Ram<193>nuja (<MS>A.<|>D.<D> 1017-1137) and ç
Madhva (<MS>A.<|>D.<D> 1238-1317). The ten Upani<218>ads upon which ç
he has written commentaries and 3 or 4 more which he has quoted in ç
his famous exposi- tion of the Brahmas<220>tras, are generally considered ç
as `major' since they may be taken as more ancient and authoritative.
The number of the minor Upani<218>ads is considerably large. Among ç
them one group of Upani<218>ads goes by a common term `T<193>pin<200>'. ç
They are five in number:
Ga<207>e·at<193>pin<200> Upani<218>ad, Gop<193>la- t<193>pin<200> ç
Upani<218>ad, N<216>si<221>hat<193>pin<200> Upani<218>ad, <185>r<200>r<193>mat<193>pin<200> ç
Upani<218>ad and Tripur<193>t<193>pin<200> Upani<218>ad. Out of ç
these, except the last, all the others are divided into two parts†the ç
p<220>rva (former) and the uttara (latter).
The Gop<193>la-p<220>rvat<193>pin<200> Upani<218>ad which is assigned ç
to the Atharvaveda has 49 mantras divided into 6 `Upani<218>ads' ç
or sections. It is in the form of a dialogue between some sages and ç
a br<193>hma<207>a who was a knower of Brahman.
The first section describes K<216><218><207>a as the Supreme God. ç
He is also known as Govinda (`one who is known by the Vedas') and ç
Gop<200>janavallabha (`dear to the gop<200>s' or `the basis of the ç
world-appearance' or `the inspirer of all sciences'). One who meditates ç
upon him, becomes immortal.
Then comes a short description of his form (the usual K<216><218><207>a-form) ç
which facilitates meditation on him.
This is followed by the mantra of Gop<193>lak<216><218><207>a for ç
purposes of japa. The mantra which has five words (and hence called ç
`pa<210>capada') is: kl<200>m k<216><218><207><193>ya govind<193>ya ç
gop<200>janavallabh<193>ya sv<193>h<193>. The repetition of this ç
mantra ultimately leads to mok<218>a or liberation.
Next follow some practical instructions needed to draw the yantra ç
of Govinda along with the mantra known as Ana<209>ga-g<193>yatr<200> ç
(k<193>madev<193>ya vidmahe, pu<218>pa-b<193><207><193>ya dh<200>mahi, ç
tanno'na<209>ga<199> praco- day<193>t) and worship of the p<200><219>ha ç
(throne) of the Lord.
S<216><218><219>i or creation of the world has always remained a mystery. ç
In answer to a query regarding the same, the br<193>hma<207>a replies ç
that the Lord creates the world out of the eighteen letters of the ç
mantra given above (kl<200>m k<216><218><207><193>ya...).
@SPACE1 = 
This mantra from which proceeded the  creation  of  the  world,  is  also ç
the one that conferred Self-knowledge on Mahe·vara-<185>iva. It is ç
also identical with V<193>sudeva (K<216><218><207>a) himself.
A beautiful hymn of obeisance to <185>r<200> K<216><218><207>a is ç
given next.
The Upani<218>ad ends with the statement that hymning to K<216><218><207>a ç
and meditating upon him will result in freedom from transmigratory ç
existence.
@NT = Gop<193>la-uttarat<193>pin<200> Upani<218>ad
This can be considered as the latter part of the Gop<193>la-p<220>rvat<193>pin<200> ç
Upani<218>ad. There are 68 mantras, both in prose and in poetry, ç
the two being more or less equally balanced.
The Upani<218>ad starts with a parable of the gop<200>s of V<216>nd<193>vana ç
and K<216><218><207>a. K<216><218><207>a advised them to give alms ç
to the great sage Durv<193>sas. Since he lived on the opposite bank ç
of the Yamun<193> river, they asked K<216><218><207>a how they could ç
cross the river and go there. Thereupon, K<216><218><207>a said to ç
them to declare just once, `K<216><218><207>a is a brahmac<193>rin, ç
par excellence!' and that the river would give way to them! K<216><218><207>a ç
also told them that whoever remembered him (with faith and devotion) ç
would become pure and would attain the fulfilment of all desires.
The gop<200>s did as they were directed by K<216><218><207>a and crossed ç
the river Yamun<193>. After meeting the sage Durv<193>sas in his hermitage ç
and feeding him sumptuously with milk, butter and ghee and sweets ç
prepared out of milk, they asked him how they could cross the river ç
and get back to their homes. He advised them to remember him, `who ç
had not eaten anything' and that the river would give way!
Since these two†K<216><218><207>a being a `celibate' and Durv<193>sas ç
having `fasted'†were quite baffling (as proved by the Yamun<193> river ç
obeying their dictate), one of the gop<200>s, G<193>ndharv<200> by ç
name, raised her doubts before the sage. The reply of the sage, interspersed ç
with allied topics, forms the Upani<218>ad proper.
Durv<193>sas explained that K<216><218><207>a as the Supreme Self ç
was beyond all the elements (like the earth, water and so on) and ç
their products like bodies, and hence untainted by them. He was actually ç
their inner Self.
Then, G<193>ndharv<200> asked the sage how he could know the greatness ç
of K<216><218><207>a who was only a cowherd boy born among them. If ç
he were really God Himself, how was he born here, what was the mantra ç
(sacred word) by which he could be appeased and what was the mode ç
of worship that could be offered to him.
Durv<193>sas replied to this question by quoting the conversation ç
between N<193>r<193>y<193><207>a (K<216><218><207>a, the Supreme Self) ç
and four-faced Brahm<193>, the creator. This part of the Upani<218>ad ç
is quite long (mantras 17 to 68) and comprises several topics. They ç
may be briefly summarised as follows:
On the top of the mountain Meru, there are seven cities out of which ç
Madhur<193> or Gop<193>lapur<200> is one. But it is Brahman Itself. ç
This city is surrounded by twelve vanas or forests. In these vanas ç
live the twelve °dityas, eleven Rudras, eight Vasus, seven Munis or ç
sages and five Vin<193>yakas. All these are divine and extraordinary ç
beings.
Then comes a brief description of twelve m<220>rtis or forms of K<216><218><207>a ç
which are worshipped by the Rudras, the <216><218>is like Sanaka, ç
the Vin<193>yakas and others.
Meditation on K<216><218><207>a, that he is our own <193>tman or soul, ç
will ultimately leadto mok<218>a or liberation. This is the next ç
topic.
This is followed by a description of the mahim<193> or greatness of ç
the city of Madhur<193> where the Lord K<216><218><207>a resides. ç
The content of the next few mantras is the fourfold form (caturvy<220>has) ç
of K<216><218><207>a.
A detailed procedure of dhy<193>na or meditation on K<216><218><207>a ç
in one's heart as also the symbology of the various weapons and ornaments ç
is given in the next part.
The last part concludes the Upani<218>ad with namask<193>ras or obeisance ç
to K<216><218><207>a and his various forms and manifestations in the ç
universe.
@NT = Gop<193><218><219>am<200>
@N1 = (`eighth day [connected with] Gopa [K<216><218><207>a]')
Great men like K<216><218><207>a have left an indelible impression ç
upon the collective psyche of the Hindus. Even a small incident in ç
his life becomes a great event, fit for celebration. Gop<193><218><219>am<200> ç
is one such.
K<216><218><207>a as a little boy was given the task of grazing and ç
looking after the calves only. He was too small to take care of the ç
cows and the bulls.
But when he grew older, into boyhood or adolescence, he had to be ç
given the charge of cows and bulls too! The day on which this was ç
done†it being K<193>rttika ·ukla a<218><219>am<200>, eighth day of ç
the bright fortnight  of  the  month  of  K<193>rttika (November)†was ç
declared as Gop<193><218><219>am<200>, to be specially celebrated ç
by feeding thecows, worshipping them and then circumambulating them. ç
Being pleased by this, Lord K<216><218><207>a will fulfil all our ç
desires.
@NT = Gopatha Br<193>hma<207>a
Each of the four Vedas†the basic scriptures of Hinduism†has been divided ç
into four sections, of which the Br<193>hma<207>as form the second. ç
They are in prose and generally deal with the practical aspects of ç
Vedic sacrifices.
The Gopatha Br<193>hma<207>a is the only extant Br<193>hma<207>a ç
of the Atharvaveda. Unlike the other Br<193>hma<207>as of the other ç
three Vedas (for e.g., the Aitareya Br<193>hma<207>a) this work ç
is considered as not so ancient. It is later than 2000 <MS>B.<|>C.<D>, ç
but earlier than 1000 <MS>B.<|>C.<D>
Generally the s<220>tra literature of the Ved<193><209>gas like the ç
<185>rautas<220>tras, follow the Br<193>hma<207>as. But here, this ç
Br<193>hma<207>a, in its latter part, appears to follow the Vait<193>nas<220>tras ç
(the <185>rautas<220>tras of the Atharvaveda).
This Br<193>hma<207>a is in two parts: The P<220>rva-Gopatha and ç
the Uttara-Gopatha. The former has five prap<193><219>hakas (chapters) ç
and a total of 135 ka<207><195>ik<193>s (short sections). The latter ç
has six prap<193><219>hakas and 123 ka<207><195>ik<193>s. Each ka<207><195>ik<193> ç
contains five or six long sentences.
According to one view, this Br<193>hma<207>a might have been composed ç
at a time when the Atharvaveda was officially admitted into the ç
group of the Vedas which were only three for a long time. (See <MS>ATHARVA-VEDA.<D>) ç
Its language is not archaic nor is there a well-knit order in the ç
presentation of the ideas. Many words and phrases from the Upani<218>ads ç
as also <193>khy<193>nakas (stories) find a place here. However, its ç
style in general resembles that of the other Br<193>hma<207>as.
@SPACE1 = 
The text starts with a description ofcreation from Brahman which ç
alone existed in the beginning. This creation started with water and ç
then, through it, the sages like Bh<216>gu, Atharvan and the ten °tharva<207>a ç
sages evolved. Further creation proceeded from them in this order. ç
the Atharvaveda, Pra<207>ava (O<209>k<193>ra), the three worlds, ç
Agni, V<193>yu and S<220>rya, the three Vedas, Oceans, Varu<207>a ç
(the presiding deity of the oceans and the water principle), the sage ç
°<209>girasa and his descendants, the five quarters (the four directions  and  the  sky  above),  the ç
subsidiary  Vedas like Sarpaveda (the science  of  serpents),  Pi·<193>caveda  (the ç
science of goblins), °suraveda (thescience ofdemons) and Pur<193><207>aveda ç
(mythology).
Other topics that appear in this Br<193>hma<207>a are: descriptions ç
of O<209>k<193>ra and G<193>yatr<200>; details regarding the rules ç
of brahmacarya (which is usually spread over twelve years) needed ç
for the study of the Vedas; duties of the four main priests in Vedic ç
sacrifices; descriptions of sacrifices like Agny<193>dh<193>na, Agnihotra, ç
Dar·ap<220>r<207>a-m<193>sa, Sattra, °graya<207>a, Pa·ubandha, R<193>jas<220>ya, ç
V<193>japeya, A·vamedha, Sarpa-medha and others.
Gopatha is the sage who composed this work. He is one of the sages ç
mentioned in the Atharvaveda. He probably resided in the Madhyade·a ç
(middle part of India) and belonged to the Pippal<193>da branch of ç
the Veda. Some of the more interesting factors mentioned here, considered ç
as `new,' are the stringent rules imposed on the br<193>hma<207>as ç
like prohibiting them from learning music and dancing!
Many mantras of the <184>gveda have been quoted here.
The Uttara-Gopatha Br<193>hma<207>a bans receiving dak<218>i<207><193> ç
in sacrifices.
The language of this Br<193>hma<207>a is elegant and the definition ç
of words appears a little peculiar.
@SPACE1 = 
See also <MS>BR°HMAØAS.<D>
@NT = gop<200>candana
@SPACE = 
According to the <193>gamas and the pur<193><207>as, every Hindu is ç
expected to wear a pu<207><195>ra or a religious mark, appropriate ç
to his cult or sect, on the forehead and also on the specified parts ç
of the body. This pu<207><195>ra may be <220>rdhva (upright) or tiryak ç
(crosswise). The n<193>ma and the gop<200>candana of the Vai<218><207>avas ç
belong to the former category and the vibh<220>ti (holy ash) to the ç
latter.
The gop<200>candana is yellowish clay available near the lake called ç
Gop<200>t<193>l<193>b, in Gujarat, in the vicinity of Dv<193>rak<193>, ç
the famous place of pilgrimage. It has to be mixed with water to prepare ç
a thin paste and then applied on the forehead, arms, shoulders and ç
the belly. It is better to use that water with which a ·<193>lagr<193>ma ç
(round stone symbol of Vi<218><207>u) has been bathed. The paste has ç
to be sanctified further by the repetition of the G<193>yatr<200>mantra, ç
three times.
Clay collected from such sacred places as <185>r<200>ra<209>gam (Tamil ç
Nadu), Si<221>h<193>cala (Andhra Pradesh), Pray<193>ga (Uttar Pradesh) ç
and also from the earth near the root of Tulas<200> plants is also ç
used for this purpose.
@SPACE = 
@NT = Gop<200>g<200>t<193>
@N1 = (`song of the gop<200>s')
@SPACE = 
The Bhagavadg<200>ta has created such a tremendous impression on ç
the Hindu psyche that several religious works or authors of later ç
years have produced their own g<200>t<193>s in imitation of the ç
original G<200>t<193>. Among such g<200>t<193>s that find a place ç
in the well-known Vai<218><207>ava scripture, the Bh<193>gavata, ç
the Kapilag<200>t<193>, (3.25 to 33) and the Uddhavag<200>t<193> ç
(11.7 to 29) are more well-known.
@SPACE1 = 
The Gop<200>g<200>t<193>, also called Gopik<193>g<200>t<193>, ç
is actually the prayer-hymn of the gop<200>s contained in the tenth ç
skandha of this work (chapter 31). There are only 19 verses (all in ç
the Tri<218><219>ubh metre except one) in it.
Being attracted by the bewitching music emanating from K<216><218><207>a's ç
flute who is sitting on the bank of the river Yamun<193>, one night, ç
the gop<200>s of Vraja (V<216>nd<193>vana) rush to him. As if taken ç
by surprise, he non-chalantly advises them to return home. Since they ç
are deeply in love with him, they refuse. Then K<216><218><207>a sports ç
with them for some time. This rouses their pride andsuperiority-complex. ç
So, he suddenly disappears from their midst. Smitten with anguish ç
and even indignation, they madly search for him, weeping and wailing ç
piteously. Not finding him anywhere they assemble together on the ç
sandy bank and start singing prayers to him. It is this prayer of ç
theirs that forms the Gop<200>g<200>t<193> (Bh<193>gavata 10.31.1-19).
These nineteen verses are highly poetic and full of pathos, often ç
reflecting erotic sentiments. Though they were panting for reunion ç
with him, they were also fully conscious of his being the Supreme ç
Lord of the universe and the inner Self of all of them (vide verses ç
4, 9 and 18).
As regards the propriety of K<216><218><207>a's amorous play with ç
them, <185>uka gives a detailed explanation, in reply to the questions ç
raised by the king Par<200>k<218>it himself (vide 10.33.27-40).
The love of the Gop<200>s towards Lord K<216><218><207>a has been ç
categorised as `madhura-bh<193>va' or `bridal mysticism' which has ç
been recognised by Christianity and Sufism also.
@NT = gop<200>s
@N1 = (`cowherdesses')
The gop<200>s or cowherdesses of V<216>nd<193>-vana have been well-known ç
in Hindu mythological and devotional literature as the supreme example ç
of madhurabhakti or bridal mysticism, loving God as one's beloved.
Though theMah<193>bh<193>rata isthe earliest record of K<216><218><207>a's ç
life, it does not contain accounts of his childhood and boyhood days. ç
This has been supplied by three works: the Hariva<221>·a, the Vi<218><207>upur<193><207>a ç
and the Bh<193>gavata. These pur<193><207>as give a fairly detailed ç
account of the early life of K<216><218><207>a, which also contain ç
a lot of material about the gop<200>s of V<216>nd<193>vana.
Their love for K<216><218><207>a was intense. They also knew, in their ç
heart of hearts, that K<216><218><207>a was not human but the Supreme ç
Lord himself (vide Bh<193>gavata 10.31.3, 9). They were actually ç
goddesses of heaven reborn on earth to play their role in the Lord's ç
life (ibid. 10.1.23).
Medieval schools of philosophy of the K<216><218><207>a cults have ç
pictured these gop<200>s as manifestations of the <185>akti or the ç
divine power of God. If Lak<218>m<200> and Bh<220>dev<200> represent ç
the ai·varya·akti, the gop<200>s represent the m<193>dhurya·akti.
In the Acintya-bhed<193>bheda school of Caitanya (<MS>A.<|>D.<D> 1485-1533), ç
R<193>dh<193>, the chief of the gop<200>s stands for the hl<193>din<200>-·akti ç
of K<216><218><207>a, the Supreme God.
See also <MS>BH°GAVATA<D> and <MS>K<184><186>ØA<D>.
@NT = gopura
@N1 = (`that which protects the town or city')
A gopura is any high structure from where representatives of the armed ç
forces can keep a watch over the movements of men and materials that ç
may prove harmful to the society or the country.
Gradually, and in common parlance, it came to be associated with the ç
towers built over the temples, both on the sanctum and on the outer ç
walls. The former, generally small in size, are called `vim<193>na' ç
and the latter, usually of gigantic proportions, are termed `gopura'.
According to the treatises on Hindu architecture like the M<193>nas<193>ra, ç
gopuras are of ten types and can have as many as sixteen or seventeen ç
storeys.
Gopuras are built at the main entrances of temples. In the case of ç
big temples they can be situated in all the four directions, if a ç
high wall is surrounding them.
Temple gopuras are generally of three types: n<193>gara, dr<193>vi<195>a ç
and vesara. The n<193>gara gopura is a curvilinear tower. The dr<193>vi<195>a ç
gopura is in the form of a truncated pyramid. The vesara type combines ç
in itself both these features.
The gopura is generally constructed with a stone base and the superstructure ç
of brick and mortar. It is rectangular in shape. The exterior walls ç
are covered with sculpture of stucco.
The various storeys of the gopura are similar but the sizes and dimensions ç
become gradually smaller. The top will be shaped like a semi-circular ç
drum and is capped with kala·as or finials which may be 3 or 5 or ç
7 or 9.
The gopuras of some temples in South India are noteworthy. They are ç
those at Tiruccirapalli, Cidambaram, <185>r<200>ra<209>gam, Ta<210>j<193>v<220>r, ç
K<193><210>c<200>puram, Madurai, (all in Tamil Nadu) and Hampi (in ç
Karnataka).
@NT = Gorakhn<193>th
The N<193>tha cult, with its stress on Ha<219>hayoga and a philosophy ç
of advaita preceded the Bhakti Movement. The cultrecognises 84 teachers ç
(known as Siddhas) out of which 9 are considered more important. The ç
founder was °din<193>tha who wasan incarnation of Lord <185>iva. ç
Matsyendran<193>tha was his disciple. Gorakhan<193>th (or Gorak<218>an<193>tha) ç
was his chief disciple and successor.
Very little is known of his life or activities. According to the traditions ç
of the cult he was `born' out of a cow-dung heap as a twelve-year ç
old boy and joined his guru Matsyendran<193>tha. According to some ç
scholars, he belonged to the Northern Karnataka region and might have ç
flourished during the eleventh century <MS>A.<|>D.<D>
Many stories are current in the annals of the N<193>tha cult about ç
his miraculous powers and yogic attainments.
The V<200>ra·aiva tradition of Karnataka narrates an incident according ç
to which Gorakhan<193>th was vanquished by Allama Prabhu in a test ç
of Ha<219>hayogic powers and became his disciple!
Several works on various aspects of yoga, both in Sanskrit and in ç
Hindi, are attributed to him. Some of them are:
@SPACE = 
@LEFT = <MS>SANSKRIT<D>:<R>ç
	Amanaska, Amaraugha-·<193>sana,<R>ç
	Gorak<218>apaddhati, Gorak<218>a·ataka,<R>ç
	Gorak<218>asa<221>hit<193>,<R>ç
	Siddha-siddh<193>nta-paddhati.
@SPACE = 
@LEFT = <MS>HINDI<D>:<R>ç
	Sabad<200>, Gy<193>ncaut<200>s<193>, Gy<193>ntilak,<R>ç
	Machindra-gorakh-bodh.
@SPACE = 
There is reason to believe that therewas a great tradition of esoteric ç
yoga practices even before the time of Gorakh-n<193>th which was common ç
to the Hindus and the Buddhists. He might have gathered material from ç
both while composing his works.
His philosophy is akin to <185>aivism and Advaita Ved<193>nta. Guru ç
and monastic disciplines have been given a place of supreme importance.
See also <MS>MATSYENDRAN°THA<D> and the <MS>N°THA-CULT.<D>
@NT = Gorakhpur
@N1 = (`city of Gorakhn<193>th')
Situated on the bank of the river R<193>pti, at a distance of 240 ç
kms. (150 miles) to the north of V<193>r<193><207>as<200> or K<193>·<200> ç
in Uttar Pradesh, this city is the Head-quarters of the N<193>tha ç
cult. A beautiful temple built over the sam<193>dhi (place of burial) ç
of the well-known sage Gorakhn<193>th (also spelt as Gorakha/Gorak<218>a-n<193>tha) ç
who perhaps lived in the eleventh century <MS>A.<|>D.<D>, is the main ç
religious attraction of this place. The sanctum houses the sam<193>dhi. ç
Behind it is an image of Mother K<193>l<200>. An oil lamp is kept ç
burning always near the image and never allowed to be put out.
The Ma<219>ha (monastery) is a part ofthe temple campus. Its head ç
(called `mahanta') is considered as a perfect being.
One of the chief attractions of this place is the G<200>t<193> Press ç
which is doing commendable service in spreading Hindu religion and ç
culture. (See <MS>G®T° PRESS.<D>)
The town now has a University and is also a centre of trade, industry ç
and commerce.
@NT = Go<218><219>h<200>p<220>r<207>a
@N1 = (11th cent. <MS>A.<|>D.<D>)
R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137) was the most important ç
of the teachers of Vi·i<218><219><193>dvaita Ved<193>nta and one of ç
the most prominent religious leaders of <185>r<200>vai<218><207>ava ç
cult. After taking sa<221>ny<193>sa by himself before Lord Varadar<193>ja, ç
the deity of the temple in K<193><210>c<200>puram (in Tamil Nadu) ç
he left for <185>r<200>ra<209>gam (also in Tamil Nadu) to grace the ç
pontificate, lying vacant due to the death of the previous incumbent, ç
Y<193>mun<193>c<193>rya (10th cent. <MS>A.<|>D.<D>). He was advised ç
by Mah<193>p<220>r<207>a, the seniormost disciple of Y<193>mun<193>c<193>rya, ç
to get initiation into the Vai<218><207>ava cult from another, highly ç
respected, teacher of the times, Go<218><219>h<200>-p<220>r<207>a. ç
When R<193>m<193>nuja approached him, he is said to have postponed ç
the event 18times, just to test the earnestness of the disciple! ç
However, R<193>m<193>nuja rose to the occasion and Go<218><219>h<200>p<220>r<207>a ç
had to yield at last!
When the great teacher imparted thewell-known A<218><219><193>k<218>ar<200>-mantra ç
(See <MS>A<186><187>°K<186>AR®.<D>), he commanded R<193>m<193>nuja ç
to keep it an absolute secret since those who heard it would be liberated ç
whereas those who imparted it to unworthy persons would go to hell. ç
R<193>m<193>nuja hastened to a nearby temple, quickly climbed to the ç
top of its gopuram (gateway tower), called out to the people to assemble ç
there and loudly imparted the esoteric mantra to one and all! When ç
Go<218><219>h<200>p<220>r<207>a got the news, he was furious and called ç
for his errant disciple immediately. R<193>m<193>nuja, however, expressed ç
his willingness to go to eternal hell, with great joy in his heart,since ç
so many ordinary people who, otherwise, might not, have got the opportunity ç
for liberation, would now surely get it! Go<218><219>h<200>p<220>r<207>a ç
realised the magnanimity of R<193>m<193>nuja and fell at his feet!
@NT = gosv<193>m<200>
@N1 = (`master of the senses')
This word can be used as an honorific for anyone who has mastered ç
his senses. However, it is normally used as a title indicating the ç
religious status of a person. It is much more common among the Vai<218><207>avas ç
(followers of the Vi<218><207>u cults).
A Vai<218><207>ava gosv<193>m<200> (or gos<193><200> or gus<193><200>) ç
may be a monk or a householder. He may be the head of a religious ç
institution or just an ordinary devotee.
The luminaries among the gosv<193>m<200>s are the following spiritual ç
leaders of theCaitanya cult (followers of <185>r<200> K<216><218><207>a ç
Caitanya of Bengal): R<220>pa Gosv<193>m<200> (<MS>A.<|>D.<D> 1493-1568), ç
San<193>tana Gosv<193>m<200> (<MS>A.<|>D.<D> 1481-1558) and J<200>va ç
Gosv<193>m<200> (16th cent. <MS>A.<|>D.<D>).
Tulas<200>d<193>s, the famous author of the monumental work, the R<193>mcaritm<193>nas ç
was a gosv<193>m<200> too.
The word is also used as a surname, for the descendants of the gosv<193>m<200>s.
@NT = Gotama
Gotama is a sage mentioned in the <184>gveda several times, (vide ç
1.62.13; 1.78.2; 4.4.11) but not as the seer (dra<218><219><193>) ç
of mantras. He was closely connected with the A<209>girasas (descendant ç
of A<209>giras). His patronymic was R<193>h<220>ga<207>a (descendant ç
of Rah<220>ga<207>a). The <185>atapatha Br<193>hma<207>a (1.4.1.10) ç
says he was the purohita (family priest) of M<193>thva Videgha and ç
a bearer of Vedic civilisation. His name also finds a place in the ç
Atharvaveda (4.29.6). V<193>ma-deva and Nodhas were his sons.
He is considered as one of the original sages who started the gotra ç
tradition.
@NT = gotra
@N1 = (`that which protects the cows', `a cow-shed')
The words `gotra' and `pravara' have been extensively used in the ç
dharma·<193>stra literature, especially while a person has to introduce ç
himself to another and also in connection with marriages.
In  its  etymological  sense,  which perhaps indicates its earliest ç
sense, `gotra' means a cowshed (or a cowherd) where the cows of a ç
group of people (most probably relatives) were kept together andprotected. ç
But, in course of time, the word acquired the meaning, `a common patriarchal ç
ancestor from whom one has descended'.
Gotra was of great importance in several fundamental matters of family ç
affairs like inheritance or marriage and religious ceremonies like ç
·r<193>ddha.
The original sages from whom the gotras are traced, are eight in number: ç
Vi·v<193>mitra,  Jamadagni, Bharadv<193>ja, Gautama, Atri, Vasi<218><219>ha, ç
Ka·yapa and Agastya. In course of time, the number of gotras increased ç
enormously.
When a person mentions his gotra by giving the name of one of these ç
sages, it means that he traces his lineage from the  ancient  sage  by  unbroken  male ç
descent.
Another  word  which  is closely connected with gotra is `pravara.' ç
Literally, it means `pr<193>rthan<193>', `choosing or invoking'. A ç
synonym for the same is `<193>r<218>eya'. So, pravara actually means ç
the illustrious sages, ancestors of the yajam<193>na who is now performing ç
a Vedic sacrifice, who themselves had invoked Agni, the deity of fire, ç
in the earlier days, even as he is doing now.
@SPACE1 = 
Though the gotras can be almost unlimited, the pravaras have been ç
fixed at 49. The more important gotras (seven only) have been classified ç
into seven ga<207>as or groups, the number of sages in each group ç
varying from 3 to 10, and the total 49. These ga<207>as are subdivided ç
into pak<218>as and the pak<218>as, again into gotras.
So, if gotra represents the original ancestor from whom the family ç
tree was born and evolved, pravara stands for the more important of ç
the ancient ancestors who had performed Vedic sacrifices. The sages ç
of the pravara may be more ancient than the sage of gotra. Generally ç
these sages (of a pravara) mentioned while performing religious rites, ç
are only three.
When a person does not know his gotra, he can adopt that of his priest ç
or guru (teacher). If even that is not properly known, he can then ç
take K<193>·yapa-gotra, Ka·yapa being the original Praj<193>pati from ç
whom creation of living beings started.
When a boy is adopted by a childless couple, he will retain the gotra ç
of his original father and also get the one of the foster father.
Marriage between persons of the same gotra is prohibited.
@NT = Govardhana
@N1 = (`that which helps in the prosperity of the cows')
Govardhana is a small hillock situated about 25 kms. (16 miles) from ç
the town Mathur<193> in Uttar Pradesh.
When K<216><218><207>a was living in V<216>nd<193>vana, he found that ç
one day all the elders of the village were busy preparing for the ç
annual festival of Indramaha (vide Vi<218><207>upur<193><207>a 5.10.16) ç
involving the worship of Indra, the king of the gods in heaven. With ç
a view to demolishing the pride of Indra, K<216><218><207>a advised ç
his foster-father Nanda and the other elders of the village to abandon ç
itand worship instead, the Govardhana hillock as also the cows and ç
the bulls. It is they that were protecting and sustaining them. His ç
suggestion was gladly accepted and duly implemented.
@EMERGENCY = Enraged by this act of `arrogance' on the part of K<216><218><207>a, ç
Indra, the lord of cloudsand rain, retaliated by creating an unprecedented ç
deluge. However, the boy K<216><218><207>a lifted up the Govardhana ç
hillock with one hand, held it like an umbrella and protected the ç
people of the village who took shelter beneath it. Indra realised ç
his folly and the true nature of K<216><218><207>a asVi<218><207>u ç
himself. After apologising and worshipping him, he left for his heavenly ç
abode. Since then K<216><218><207>a came to be known as `Govardhana-giridh<193>r<200>' ç
(`one who lifted the Govardhana hill'), `Govinda' (`one who protected ç
the cows') and `Upendra' (`one who was above or superior to Indra').
@EMERGENCY = The Govardhana hillock near Mathur<193> is about 6.5 ç
kms. (4 miles) in length and not very high. Pilgrims who visit it ç
sometimes do `parikrama,' i.e., circumambulation, as per the directions ç
given in some sm<216>tis and pur<193><207>as.
