A ceremonial worship of the hillock (called `Govardhanap<220>j<193>') ç
is generally held on K<193>rttika-·ukla-pratipad (first day of the ç
bright fortnight in the month of K<193>rttika, generally in November), ç
the daybeing known as `Balipratipad<193>' also. Worship of cows and ç
bulls is an important aspect of this festival.
In other places, the worship is done to a replica of the hillock.
See also <MS>ANNAK<188><187>A.
@SPACE = 
@NT = Govardhana Ma<219>ha
@SPACE = 
One of<|> the pioneering works done by <185>a<209>kara (<MS>A.<|>D.<D> ç
788-820) is the establishment of four ma<219>has or monasteries in ç
four cardinal places of India to spread Vedic religion and Advaita ç
philosophy. They are: the K<193>lik<193> Ma<219>ha at Dv<193>rak<193> ç
in the west, Gujarat; the Jyotir Ma<219>ha near Badar<200> in the ç
north, in Uttaranchal; the Govardhana Ma<219>ha at P<220>r<200> in ç
the east, in Orissa and the <185><193>rad<193> Ma<219>ha at <185><216><209>geri ç
in the south, in Karnataka.
The first pontiff of the Govardhana Ma<219>ha at Pur<200> was Padmap<193>da, ç
one of the four chief disciples of <185>a<209>kara, who is reputed ç
to have rescued his guru from the clutches of the k<193>p<193>likas ç
who wanted to sacrifice him.
The Veda assigned to this Ma<219>ha is the <184>gveda. The brahmac<193>rins ç
of this tradition are given the appellation `Prak<193>·a.' `Vana' ç
and `Ara<207>ya' are the titles reserved for the sa<221>ny<193>sins ç
ordained through this Ma<219>ha.
There seem to be breaks in the continuity of the gurus occupying the ç
pontiff's seat.
@SPACE1 = 
See also <MS>DA<185>AN°M®S.<D>
@NT = Govindabh<193><218>ya
See <MS>BALADEVA VIDY°BH<188><186>AØA.<D>
@NT = Govind<193>nanda
The medieval Hindu society (and, to a considerable extent, the modern ç
Hindu society too) is regulated by the sm<216>tis, thedharma·<193>stras, ç
the pur<193><207>as and the nibandhas (digests) in its performance ç
of rituals and some sacraments. Govind<193>-nanda who flourished during ç
the period <MS>A.<|>D.<D> 1500-1540 (exact dates not known) was an ç
important author of nibandhas. He was a Vai<218><207>ava and probably ç
lived in B<193>gri in the Medin<200>pur (Midnapur) district of West ç
Bengal.
He wrote eleven works in all, of which mention may be made of the ç
following: D<193>nakaumud<200>, <185>uddhikaumud<200>, <185>r<193>ddha-kaumud<200>, ç
and Var<218>akriy<193>kaumud<200>.
These works, respectively deal with the subjects of d<193>na (gifts), ç
·uddhi (purifi- catory rites), ·r<193>ddha (obsequial rites)and festivals ç
observed throughout the year.
@NT = graha<207>a
@N1 = (`[the sun or the moon] being seized [by R<193>hu]', `eclipse')
@SPACE1 = 
Graha<207>a or eclipse (both solar and lunar) has been given great ç
importance in the Hindu liturgical works. That it was a natural phenomenon ç
was known to the Hindu astronomers as can be gleaned from Var<193>hamihira's ç
(6th cent. <MS>A.<|>D.<D>) B<216>hat-sa<221>hit<193> (5.8 and 13). ç
However, the basically religious nature of the Hindus made them look ç
with awe and wonder on such natural phenomena as reflecting God's ç
power  and  glory.  Consequently  they became occasions for performing ç
religious rites.
Between the lunar and the solar eclipses, the latter has been considered ç
as more holy and rewarding, from the standpoint of religious observances.
The observances generally prescribed are: bath before and after the ç
eclipse, performance of worship of gods and ·r<193>ddha as also homa, ç
giving of gifts to worthy persons, japa of G<193>yatr<200> and other ç
well-known mantras, fasting and even giving d<200>k<218><193> or initiation.
Taking bath in holy places like Kuruk<218>etra (near Delhi) or rivers ç
like God<193>var<200> was highly commended.
Any religious act like doing japa orgiving gifts was considered to ç
confer infinitely greater results when performed during eclipses.
Certain astrological results, good or bad, were deemed to follow from ç
eclipses depending on the nak<218>atra (constellation of the stars) ç
at the time of the eclipses. <185><193>ntisor propitiatory rites ç
have also been prescribed to offset the evil results.
@NT = grahas
See <MS>NAVAGRAHAS.<D>
@NT = grahayaj<210>a
@N1 = (`yaj<210>a [to appease the]<R>ç
grahas or planets')
Hindus have believed that the nine grahas or planets like the sun, ç
the moon, or the mars have a bearing on human life. This has to be ç
ascertained for each individual as per the details of the horoscope. ç
During certain periods in one's life, some of the grahas are said ç
to become inimical and affect the person adversely. Hence, certain ç
rites known as `grahayaj<210>a' have to be performed. They have to ç
be done on certain days specified as good by the almanac. During such ç
rites gifts of a cow, a conch, gold or cloth are to be given to worthy ç
persons.
@NT = gr<193>madevat<193>
@N1 = (`village deity')
The concept of gr<193>madevat<193> (village deity or a tutelary deity) ç
is as old as the human civilisation. When the early man cleared a ç
forest area to build a human habitation he naturally felt apprehensive ç
that the god or the deity or the spirit protecting the forest might ç
get offended and harm him. Hence he might have started erecting some ç
sort of monument or structure for the deity to reside, receive his ç
worship and be pleased.
Gr<193>madevat<193>s, either in their own shrines or under big trees, ç
are seen almost all over India, especially in the rural and tribal ç
areas. Clay images of horses and elephants are often placed in the ç
premises of these deities. They are guardian deities situated at the ç
entrance of the villages. Their main duty is to protect the village ç
under their care from epidemic diseases, natural disasters and evil ç
spirits. They are mostly mother-goddesses, aspects of P<193>rvat<200>. ç
They are worshipped by the villagers either regularly or on important ç
occasions like the beginning of agricultural operations, for theprotection ç
of the crops, prevention of diseases as also auspicious ceremonies ç
in the family like marriage or birth.
Sacrificing animals like sheep, goats and buffaloes on special occasions ç
to appease the goddess is also not uncommon.
@NT = Grantha script
One of the important factors responsible for the development of any ç
language is its script. According to the experts in the field of paleography, ç
the origins of writing with a definite script might be traced to the ç
period 4000 <MS>B.<|>C.<D>
The Kanna<195>a and the Telugu characters might have evolved around ç
the 5th century <MS>A.<|>D.<D> from a South Indian edition of the Br<193>hm<200> ç
script.
The Tami<202> characters were already in use even by the 2nd century ç
<MS>A.<|>D.<D> Since this script contained only the first and the last ç
letters in each of the five vargas (like ka-varga, ca-varga, viz., ç
ka and <209> or ca and <210>) and did not have the letters like ·a, ç
<218>a, sa or ha, Sanskrit works could not be copied in this script. ç
To remedy this defect, the Grantha script seems to have been evolved. ç
There is evidence of the use of this script in the earliest copper ç
plate inscriptions of the Pallavas belonging to the 5th or the 6th ç
century <MS>A.<|>D.<D> Hence the name `Pallava Grantha script' also.
Though this script was used mostly for Sanskrit writings, it seems ç
to have gained greater currency in general use also, around the 14th ç
century.
The Malay<193><202>am script is a metamorphosis of the Grantha script.
It has been used sometimes as a script for the Tu<202>u language also.
Two varieties of the Grantha script are found: the Br<193>hma<207>ic ç
or the square variety and the Jaina or the round variety.
The script has 35 letters, of which five are vowels.
@NT = granthi
@N1 = (`knot')
@SPACE = 
`Granthi' means a knot. Just as a knot binds something, the three ç
gu<207>as† sattva, rajas and tamas†bind the j<200>va (individual soul) ç
to the world of nature.He has to untie them or cut them, to transcend ç
them and rise to the level of the spirit.
In  the  t<193>ntrik  literature  three granthis have been described. ç
They are: Brahmagranthi, Vi<218><207>ugranthi and Rudragranthi. They ç
obstruct the upward movement of the Ku<207><195>alin<200> power.
Each of the six cakras (like m<220>l<193>dh<193>ra and sv<193>dhi<218><219>h<193>na) ç
has two granthis on either side. The Brahma- granthi is situated between ç
m<220>l<193>dh<193>ra and sv<193>dhi<218><219>h<193>na. The Vi<218><207>ugranthi ç
is situated between ma<207>ip<220>ra and an<193>hata. The Rudragranthi ç
is situated between vi·uddha and <193>j<210><193>.
The Ku<207><195>alin<200>-·akti or power pierces these three granthis ç
before reaching the sahasr<193>ra, when roused by proper yogic exercises ç
under the guidance of an expert.
See also <MS>CAKRAS<D> and <MS>KUØ£ALIN®.<D>
@SPACE = 
@NT = Granth-S<193>hib
@N1 = (`the Master-Book')
@SPACE = 
Sikhism is the youngest of the world religions. It was started by ç
Guru N<193>nak (<MS>A.<|>D.<D> 1469-1539). It has been developed and ç
nourished by nine more Gurus of whom the last was the illustrious ç
Guru Gobind Singh (<MS>A.<|>D.<D> 1666-1708).
The basic scripture of Sikhism is the °di-Granth, also known as ç
Granth S<193>hib or <185>r<200> Guru Granth-S<193>hib. It was ç
thefifth Guru, Guru Arjan Dev (<MS>A.<|>D.<D> 1563-1606) that compiled ç
the original edition of the Granth-S<193>hib in <MS>A.<|>D.<D> 1604. ç
It was later revised by Guru Gobind Singh in <MS>A.D.<D> 1705 by ç
including the hymns of Guru Tegh Bah<193>d<220>r (<MS>A.<|>D.<D> 1621-1675) ç
also. In <MS>A.D.<D> 1708, he declared that there would be no more ç
Gurus to guide the Sikhs and that the Book itself would be the Guru ç
and hence had to be revered as such.
The Book comprises 6000 hymns. TheGurus represented and the hymns ç
composed by them are as follows:
@SPACE = 
@L2 = <+><+><+>N<193>nak	:<+><+>974 hymns.<R>ç
<+><+><+>A<209>gad	:<+><+>62 hymns.<R>ç
<+><+><+>Amar Das	:<+><+>907 hymns.<R>ç
<+><+><+>Arjan Dev	:<+><+>2,218 hymns.<R>ç
<+><+><+>Tegh Bah<193>d<220>r	:<+><+>115 hymns.
@SPACE = 
Compositions of other saints†called Bhagats†have also been included. ç
For instance 61 hymns of the Maharashtrian saint N<193>mdev (<MS>A.<|>D.<D> ç
1270-1350), 39 of the moc<200> (shoe-maker caste) saint Raidas (15thcent. ç
<MS>A.<|>D.<D>) and 226 of Kab<200>r (<MS>A.<|>D.<D> 1440-1518) form ç
part of the Book.
The Book starts with the Japji, the famous morning prayer. This ç
is followed by Rahiras and K<200>rtan Sohila the evening and night ç
prayers.
The gist of its teaching is that God is one and that his name is Sat ç
or Truth. He has no birth and hence no death. He can be realised only ç
by the grace of the Guru. He lives in our bodies too. Repeating God's ç
n<193>ma or name and remembering him through the name, is the chief ç
mode of spiritual discipline.
See also <MS>SIKHISM<D>.
@NT = gr<193>vastut
@N1 = (`one who praises the stone [used for crushing the soma stalks]')
Vedic sacrifices are of several varieties. Somay<193>gas, the sacrifices ç
in which the soma juice has to be offered as oblation, are an important ç
type among them.
The soma juice has to be extracted by using stone crushers called ç
`gr<193>van' specially meant for the purpose. The crushing or pressing ç
(called `savana') takes place threetimes a day. They are: pr<193>tassavana, ç
m<193>dhyandinasavana and t<216>t<200>ya-savana.
The gr<193>vastut is a priest who is an assistant of the hot<216> ç
priest. During the m<193>dhyandina-savana; he enters the havirdh<193>nama<207><219>apa ç
(a shed housing the two carts loaded with soma stalks), is given a ç
special turban to wear and thenrecites the gr<193>vastotra (°·val<193>yana ç
<185>rautas<220>tra 5.12.9-25). He is entitled for a share in the ç
soma juice.
@SPACE = 
@NT = graves
@SPACE = 
Burial and cremation of the bodies of the dead have both been an ancient ç
practice among the Hindus. Building graves or sepulchral mounds over ç
the places of burial is common even now. However, what is not generally ç
known is that sepulchral mounds used to be built over the charred ç
bones of a cremated person too! After cremation, the bones collected ç
from the cremation ground used to be preserved in an urn, kept either ç
in an open ground under a tree or temporarily buried in a place, with ç
some distinguishing marks to resurrect it later.
After a sufficiently long time, a grave used to be dug in a suitable ç
place like a level ground full of trees and natural beauty, the bones ç
taken out of the urn and placed in the pit in a particular order. ç
It would then be filled with bricks, clay and earth, and a mound raised ç
over the spot, like a monument. Of course, all this had to bedone ç
as per the procedure given in the<185>rautas<220>tras with appropriate ç
Vedic mantras.
This practice was not universal and went out of vouge in course ç
of time.
See  also<MS>  ANTYE<186><187>I,  BURIAL<D>  and<MS> CREMATION<D>.
@SPACE = 
@NT = g<216>hakarman
@N1KERN = (`the act of building a house')
@SPACE = 
Any householder, who could afford it, was expected to build a house ç
for himself and his family. However, he was to observe certain rules ç
and regulations in doing so.
A place where the earth is whitish in colour and the ground is level, ç
is considered suitable.
As regards the wood to be used, the following are to be avoided: wood ç
of a tree from which its milk is oozing out; trees on which birds ç
are living; trees which have fallen to the ground or those which have ç
been burnt; trees grown in the premises of temples; trees in which ç
deities or divine beings are believed to reside; thorny trees.
As regards digging a well inside one's compound, certain directions ç
like south-east and north-west were prohibited. On the other hand, ç
east, west and north were recommended.
Houses could be begun to built in certain auspicious months only like ç
Vai·<193>kha (April/May) or °<218><193><195>ha (July/ August) and ç
not in the inauspicious oneslike Caitra (March/April) or M<193>gha ç
(February/March).
More details have been provided in the science called `V<193>stu·<193>stra.' ç
Certain Pur<193><207>as also deal with this subject.
@SPACE = 
@NT = g<216>haprave·a
@N1 = (`entering a [new] house')
@SPACE = 
@SPACE = 
A distinguishing feature in a Hindu's life is that no action of his ç
is divorced from religion. Starting from personal cleanliness and ç
hygiene as a part of daily routine, right up to the time of going ç
to bed or even up to death, everything he is expected to do, has to ç
have a religious colour or flavour.
Building a new house and entering it is one of the most important ç
occasions in the life of a g<216>hastha or a householder. Naturally, ç
this has to be done in a befitting manner. The g<216>hyas<220>tras ç
as also the dharma·<193>stras prescribe elaborate procedures for this ç
ceremony called `g<216>ha-prave·a' or ceremonially entering the house.
It may not be out of place to mention here that when Lak<218>ma<207>a ç
built a par<207>a-ku<219>i (a thatched house) for R<193>ma, S<200>t<193> ç
and himself to live, in Citrak<220><219>a, an elabo- rate g<216>haprave·a ç
ceremony was performed (R<193>m<193>ya<207>a, Ayodhy<193>k<193><207><195>a, ç
56.22-35).
@SPACE = 
@SPACE = 
A g<216>haprave·a is of four types:
@SPACE = 
@SPACE1 = 
1.
@NK = Entering an old house by the new master who has acquiredit.
@SPACE1 = 
2.
@NK = Entering a renovated house by the same owner.
@SPACE1 = 
3.
@NK = Entering a newly built house by its owner.
@SPACE1 = 
4.
@NK = Entering one's own (old) house after a long lapse of time due ç
to pilgrimage and so on.
@SPACE1 = 
Of these, it is really the third one that is treated more elaborately ç
as g<216>haprave·a in the true sense.
Before performing g<216>haprave·a, an auspicious day according to ç
the traditional Hindu calendar has to be fixed. On the previous night, ç
R<193>k<218>oghna-homa has to be performed to ward off the evil spirits ç
that might have been living there since a long time.
The first thing to be done is the worship of the V<193>stupuru<218>a, ç
the cosmic man embodying the whole creation, including the different ç
deities of the Hindu pantheon. For this, a V<193>stuma<207><195>ala ç
(a geometrical drawing, square in shape, containing 9 x 9 = 81 small ç
squares) has to be drawn at an appropriate place in the house and ç
decorated with coloured powders. This has to be followed by V<193>stu- ç
homa, worship oftheNavagrahas(the nine planets) and of Ga<207>apati, ç
the lord of (and destroyer of) obstacles as also p<220>r<207><193>huti ç
(the final oblation).
A long cotton thread is then wound round the house thrice to make ç
it secure† this is called `digbandhana' or `locking the quarters'†followed ç
by balis or offerings to the guardian deities like Indra. A bali is ç
offered to the V<193>stupuru<218>a also.
@SPACE1 = 
The owner, then, has to ceremonially enter the house along with his ç
wife. The procession should comprise instrumental music, Vedic chanting, ç
p<220>r<207>akumbha (holy water pot), certain auspicious materials ç
like milk and butter, suv<193>sin<200>s (married ladies whose husbands ç
are alive), images of gods, images of the family deities, a cow and ç
its calf. The cow and the calf are taken in first and led up to the ç
place where the family shrine is to be established. After establishing ç
the family deities there, a simple worship is done. The br<193>hma<207>a ç
priests are then honoured and given  presents.  Guests  are  also  fed ç
sumptuously.
Writing of O<221> (Pra<207>ava), the Svastika symbol, letters and ç
words like `·r<200><199>,' `ga<207>e·<193>ya nama<199>' (preferably ç
in Sanskrit) on the walls of the new house as also boiling milk in ç
a pot and make it overflow are other local customs present in some ç
parts of the country.
@SPACE = 
@NT = g<216>hastha
@N1 = (`one [who is] established in a home', `a married person or ç
a householder'.)
@SPACE = 
See <MS>°<185>RAMA.
@SPACE = 
@NT = G<216>hyas<220>tras
@SPACE = 
The Vedas, the basic scriptures of Hinduism, are considered `apauru<218>eya' ç
(not man-made but revealed). Couched in an archaic language they are ç
often difficult to decipher or comprehend. Hence the sixVed<193><209>gas ç
(`limbs of the Vedas'), six subsidiary sciences that help unfold the ç
Vedic wisdom, came into existence.
Out of these six Ved<193><209>gas, the Kalpa is the last. `Kalpa' ç
means `prayoga' or practical method of doing a thing. It has, again, ç
four branches: ·rauta, g<216>hya, dharma and ·ulba. All these four ç
are in the form of s<220>tras composed by different authors.
The G<216>hyas<220>tras, the second in the series, deal with the various ç
rites to be performed in one's g<216>ha or house, such as the sixteen ç
sa<221>sk<193>ras like upanayana, viv<193>ha and others.
A list of the G<216>hyas<220>tras belonging to the four Vedic traditions, ç
as available now, may now be given:†
@SPACE = 
@NOX = <184>gveda:<R>ç
<+><+><+>°·val<193>yana G<216>hyas<220>tras<R>ç
<+><+><+><185><193><209>kh<193>yana G<216>hyas<220>tras
@NOX = <185>ukla Yajurveda:<R>ç
<+><+><+>P<193>raskara G<216>hyas<220>tras
@NOX = K<216><218><207>a Yajurveda:<R>ç
<+><+><+>°pastamba G<216>hyas<220>tras<R>ç
<+><+><+>Baudh<193>yana G<216>hyas<220>tras<R>ç
<+><+><+>Bharadv<193>ja G<216>hyas<220>tra
@NOX = S<193>maveda:<R>ç
<+><+><+>Gobhila G<216>hyas<220>tras<R>ç
<+><+><+>Jaimin<200>ya G<216>hyas<220>tras<R>ç
<+><+><+>Kh<193>dira G<216>hyas<220>tras
@NOX = Atharvaveda:<R>ç
<+><+><+>Kau·ika G<216>hyas<220>tras
@SPACE = 
@SPACE = 
See under each title for more details.
@SPACE = 
@NT = G<216>tsamada
@SPACE = 
G<216>tsamada is a <216><218>i or sage to whomthe authorship of the ç
second ma<207><195>ala of the <184>gveda is attributed. The name ç
has been defined as one who was both intelligent and happy always.
He was the son of the sage <185>unahotra. When he was performing a ç
sacrifice once, asuras or demons abducted him. However, on his praying ç
to Indra, Indra rescued him.
He seems to have been the adopted son of <185>unaka, a descendant ç
of the sage Bh<216>gu. Hence the patronym Bh<193>rgava.
According to another version he was the son of V<200>tahavya, a k<218>attriya ç
king, who later became a br<193>hma<207>a.
@SPACE1 = 
G<216>tsamada is said to have saved Indra once, from being caught ç
by the asuras, by assuming his form and cheating them.
The <216>ks (<184>gvedic mantras) attributed to him are highly poetic.
@NT = Gu<195>imallam
God being nir<193>k<193>ra (formless) and nirgu<207>a (without attributes) ç
a symbol of rounded surface is, perhaps, the nearest iconic representation ç
of his. A li<209>ga or <185>ivali<209>ga is exactly that. However ç
phallic association of the li<209>ga cannot also be ruled out since ç
it might have been present in some aboriginal cults which might have ç
been, later on, absorbed into the Vedic fold. The earliest <185>ivali<209>ga ç
discovered so far is at the Para·ur<193>me·vara temple of Gu<195>imallam, ç
a village situated about ten kilometres from Renigunta in Andhra Pradesh. ç
This is an unmistakable piece of iconic representation of <185>ivali<209>ga ç
as an erect phallus. It is 1.5 metres (5ft.) tall and is assigned ç
to the period 100-200 <MS>B.C<D>. A beautifully carved image of <185>iva ç
standing against it and trampling a r<193>k<218>asa (demon), the apasm<193>ra ç
puru<218>a (cretinous person), is an added attraction.
See also <MS><185>IVALI<177>GA<D>.
@NT = Guha
@SPACE1 = 
Guha of the R<193>m<193>ya<207>a is a glorious example to show that ç
great men like R<193>ma paid greater attention to the character of ç
persons and honoured them than their birth and caste. <185>abar<200> ç
is another such character met with in the same epic.
Guha was the chieftain of the forest tribes living at <185><216><209>gaverapura. ç
He was a great friend of Da·aratha, R<193>ma's father. After banishment ç
when R<193>ma reached the forest Guha was his host who entertained ç
him with love and affection. He also helped R<193>ma, along with S<200>t<193> ç
and Lak<218>ma<207>a, to cross the Ga<209>g<193> and reach its southern ç
bank.
When R<193>ma was staying at the Citrak<220><219>a mountain, Bharata ç
arrived at the forest, with his army, to take him back. Suspecting ç
that he must have come to harm R<193>ma, Guha prepared his men to ç
face Bharata and fight him if necessary. However, after learning of ç
his real motive, Guha regretted his hasty action, entertained Bharata ç
and his party and then helped them to cross the river Ga<209>g<193>.
Guha is also one of the names of Subrahma<207>ya, known by other names ç
too such as Skanda, <185>arava<207>abhava, Kum<193>ra, and <186>a<207>mukha. ç
He is the son of <185>iva and P<193>rvat<200> and the commander-in-chief ç
of the army of the gods. See <MS>SUBRAHMAØYA<D> for details.
@NT = Gujarati Printing Press
This is one of the oldest printing presses in India that has also ç
published invaluable works bearing on philosophy and religion.
It was started by Fardunjee Marzban (<MS>A.<|>D.<D> 1787-1847) in <MS>A.<|>D.<D> ç
1805 at Bombay (now Mumbai).
Started first as a book binding shop it was later developed into a ç
printing press and a publishing house.
@SPACE1 = 
It published the Zoroastrian Calendar in <MS>A.<|>D. <D>1814 and the ç
newspaper<MS> <MI>Bombay Samachar in <MS>A.<|>D.<D> 1822 in the Gujarati ç
language. This newspaper continues to this day, making it one of the ç
oldest, continuously printed newspaper, in the world.
This  press,  over  the  years,  has published many extremely valuable ç
scriptures of Hinduism with commentaries and translations.
By far, the most outstanding contribution of this institution is the ç
publication of the R<193>m<193>ya<207>a of V<193>lm<200>ki with ç
three standard commentaries.
@NT = gu<207>a
@N1 = (`quality')
One of the most widely used words, `gu<207>a' has several senses such ç
as quality, rope, bow-string, nature and certain letters of the Sanskrit ç
alphabet used in grammar. However, in the Indian philosophical systems ç
such as S<193><209>khya, Yoga and Ved<193>nta it refers to the three ç
fundamental components of prak<216>ti or pradh<193>na or m<193>y<193>, ç
the basic matrix out of which the physical universe is created.
These gu<207>as are three in number: sattva, rajas and tamas.
They are not qualities or attributes in any sense, but fundamental ç
subtle substances or elements which constitute the prak<216>ti like ç
three cords making a rope.
The existence of these gu<207>as is inferred from the qualities presented ç
in the created world. Sattva is responsible for knowledge and pleasure. ç
Rajas is responsible for activity and passions. Tamas produces indolence, ç
sleep and evil.
Before creation, these three are in a perfectly balanced state. At ç
the beginning of creation, this balance is upset and evolution of ç
the world starts.
@SPACE1 = 
See  <MS>S°<177>KHYA<D>  <MS>DAR<185>ANA<D>  for  more details.
In the Ny<193>ya and Vai·e<218>ika systems, `gu<207>a' is described ç
as a quality or an attribute. Gu<207>as are 24 in number. Some of ç
them are: r<220>pa (shape), gandha (odour), sa<209>khy<193> (number), ç
sa<221>yoga (conjunction), gurutva (weight), icch<193> (desire), dharma ç
(merit) and so on.
In Sanskrit literature ten gu<207>as or excellences of a composition, ç
are listed. For instance, pras<193>da (clarity), samat<193> (uniformity ç
in the type of clusters of consonants used), ud<193>ratva (decency ç
and dignity of the subject), k<193>nti (loveliness of expression) ç
are some of these.
The word when used to indicate the policies of a state refers to six ç
measures such as sandhi (alliance), vigraha (war) and <193>sana (neutrality), ç
adopted by the State.
@SPACE = 
@NT = gu<207><193>t<200>ta
@N1 = (`one [who is] beyond [the sway of the three] gu<207>as')
@SPACE = 
The quest for perfection has been acommon characteristic feature ç
of all religions and philosophical systems. Since perfection is only ç
a concept, it can best be understood only when concretised through ç
a person or a personality. The Bhagavadg<200>t<193> has done this ç
in three places (vide 2.55-72; 12.13-20 and 14.22-27). The `gu<207><193>t<200>ta' ç
is the last of these three.
The gu<207><193>t<200>ta is the one who has transcended the three ç
gu<207>as†sattva, rajas and tamas. He is unmoved by the effects of ç
the three gu<207>as (like knowledge or action or delusion). He is ç
equanimous in happiness or misery. He looks upon a clod of earth or ç
stone or gold as of equal worth†being neither repelled nor tempted ç
by them†and is unmoved by the pleasant and the unpleasant or praise ç
and blame. He treats friends and enemies equally, based on the merits ç
of the case. He serves God with undeviating love. Such an one is fit ç
to attain Brahman.
@NT = gu<207>atraya
@N1 = (`the triad of gu<207>as')
See <MS>GUØA<D>.
@NT = gu<207>av<193>da
See <MS>ARTHAV°DA.<D>
@NT = Gupta-god<193>var<200>
@N1 = (`the hidden God<193>var<200>')
Nearly 10 kms. (6 miles) from the Atri-Anas<220>y<193> °·rama in Citrak<220><219>a ç
(in Uttar Pradesh) there is a dark cave. About 15 metres (50<|>ft.) ç
inside it, there is a pond called `S<200>t<193>ku<207><195>a'. Water ç
streams constantly fall into this pond. Taking a bath here, is considered ç
by the pilgrims, as equal to taking a bath in the sacred river God<193>var<200>. ç
Hence the name `Gupta-god<193>var<200>'.
@NT = Gupta-k<193>·<200>
@N1 = (`hidden K<193>·<200>')
Situated at a distance of 34 kms. (21 miles) from Rudrapray<193>ga ç
(in Uttaranchal) Guptak<193>·<200> is a small place of pilgrimage. ç
Many sages of the olden days are said to have performed severe austerities ç
here to realise Lord <185>iva. B<193><207><193>sura's daughter U<218><193> ç
had her palace here.
There is a beautiful image of <185>iva as Ardhan<193>r<200>·vara, ç
riding his bull, the Nandi, here.
In a pond nearby, two streams of water are constantly falling into ç
it. These are called `Ga<209>g<193>' and `Yamun<193>'. Pilgrims take ç
bath in this pond and give gifts secretly (gupta = secretly).
@NT = Gupta script
A modified form of the Br<193>hm<200> script, it has been used in ç
the inscriptions of the kings of the Gupta empire during the period ç
4th to 6th centuries <MS>A.<|>D<D>. It had 37 letters including five ç
vowels.
This script has been considered as the precursor of later Indian scripts ç
as also of some Central Asian scripts.
See also <MS>BR°HM®.
@SPACE = 
@NT = Gurmukhi script
@SPACE = 
The survival of a religion depends very much upon its basic scripture. ç
The survival of this scripture, again, depends on its being committed ç
to writing.
When Sikhism came into existence and started becoming popular, especially ç
with the masses, it became necessary to compile the sayings of its ç
founder Guru N<193>nak (<MS>A.D.<D> 1469-1539). Guru A<209>gad (<MS>A.D.<D> ç
1504-1552) took the trouble of getting the scripture committed to ç
writing. He modified the La<207><195><193> script, then in existence, ç
by borrowing letters from other scripts like the <185><193>rad<193>, ç
the <187>h<193>kur<200> and the N<193>gar<200>. The present script ç
has 35 letters. It is called the Punjabi script. Since it was done ç
by the Sikh Guru A<209>gad, it was also called the Gurmukhi script. ç
The fifthGuru, Arjan Dev (<MS>A.<|>D.<D> 1563-1607), compiled the ç
°di Granth in this script.
The Gurmukhi script has 3 vowels and 32 consonants. There are no conjunct ç
consonants. Words like `Bhagav<193>n' are written as `Pahagv<193>n'.
@SPACE = 
@NT = guru
@N1 = (`one who is praised [due to his great qualities]' `one who ç
teaches [the ·<193>stras like the Vedas]')
@SPACE = 
In Hindu religion and culture, every science or art or craft has to ç
be learnt directly from a competent teacher in that field. Since learning ç
is considered as a tapas (austerity, discipline), the teacher has ç
to belooked upon with great respect and reverence.
A teacher of the scriptures is called an adhy<193>paka or an up<193>dhy<193>ya ç
or an <193>c<193>rya. The former two teach the chanting of the Vedas ç
whereas the last one teaches their meaning and significance also.
The word `guru' is used in a more comprehensive sense. It has sometimes ç
been defined as one who dispels the dark- ness of ignorance. It invariably ç
refers to a spiritual teacher, an advanced soul, who is an expert ç
not only in the knowledge of the scriptures but also well-established ç
in Brahman or God (vide Mu<207><195>aka Upani<218>ad 1.2.12).
A guru should be a person of pure parentage, of a sinless life and ç
great self-control. Apart from having a deep knowledge of the scriptures, ç
he should be an adept in the various modes of meditation and worship ç
also. He must be the very personification of compassion and love towards ç
his disciples.
A disciple is expected to look upon his guru as if he is God himself. ç
However, the Hindu scriptures also warn the people against false gurus.
B<216>haspati, the teacher of the gods in heaven is also known as ç
Guru.
Guru is also the name of the planet Jupiter. (See <MS>B<184>HASPATI<D>.)
`Guru' was also the nickname of Prabh<193>kara (<MS>A.<|>D.<D> 700?), ç
a prominent teacher of the P<220>rvam<200>m<193><221>s<193> school ç
of philosophy.
The word `guru' has been used widely in the Sanskrit works in several ç
other senses such as: father, mother, husband, any teacher in any ç
field of knowledge and God himself.
See also <MS>°C°RYA<D>.
@SPACE = 
@NT = gurudak<218>i<207><193>
@N1 = (`honorarium [paid to the] guru')
@SPACE = 
Education was considered in ancient and medieval India as too sacred ç
an act to demand or accept any fee. If, however, a disciple wanted ç
to give something to his guru, at the time of his departure from the ç
gurukula, as a mark of his gratitude, the guru could accept it. This ç
could take two forms: accepting whatever the disciple gave, or, asking ç
for something which one really wanted.
Though offering of money, cows or land was common, uncommon or even ç
odd or novel things were sometimes asked for as gurudak<218>i<207><193>. ç
Dro<207><193>c<193>rya wanted the P<193><207><195>avas to capture ç
the king Drupada and bring to him! Uda<209>ka, a sage, had to take ç
a lot of trouble to bring and give the ear-rings of the queen Madavat<200> ç
to Ahaly<193>, the wife of his guru, Gautama.
However, the idea has always been there that the debt to one's guru ç
can never be repaid.
@SPACE = 
@NT = gurudv<193>ra
@N1 = (`gateway to the Guru')
@SPACE = 
All religious communities have their own places of worship and prayer, ç
be it a temple or a church or a mosque. The place of worship of the ç
Sikhs is the gurudv<193>ra (also spelt as `gurdv<193>ra').
Guru Gobind Singh (<MS>A.<|>D.<D> 1666-1708) the tenth and the last ç
Guru, ordained that there would be no more human Gurus and that the ç
Book, the °di Granth (compiled by the fifth Guru, Arjan) itself ç
should be looked upon as the Guru after him.
A gurudv<193>ra is the place where this book, the °di Granth†also ç
called Guru Granth S<193>hib†is kept in a hall with all the paraphernalia ç
needed to honour it like a human Guru.
The Book, once established, is looked after, by the granthis (scripture-readers). ç
It is also taken out in a procession like the utsava-vigraha, (processional ç
deity) in a Hindu temple.
@SPACE1 = 
The Golden Temple (called Hari Mandir or Darb<193>r S<193>hib) at ç
Amritsar in Punjab is the chief gurudv<193>ra of the Sikhs.The other ç
important ones are at Kapurthala, Anandpur (both in Punjab), Nanded ç
(Maharashtra) and Patna (Bihar).
@NT = gurukula
@N1 = (`house of the guru')
@SPACE1 = 
In ancient and medieval India edu-cation was generally residential. ç
The students had to reside in the houses of their gurus. This gave ç
them not only greater opportunities to learn the sciences and the ç
arts, with all their intricacies and secrets, but also get inspiration ç
for their life from that of their gurus.
When the number of students that the teachers kept in their houses ç
grew quite large, these houses grew into institutions called `gurukulas'. ç
And, they were maintained by the society, especially the kings and ç
the rich persons, who endowed these gurukulas with sufficient property ç
and funds, so that they could provide quality education, free of cost, ç
to all the students.
In these gurukulas, attention was paid not only for the physical welfare ç
and intellectual development but also for spiritual growth so that ç
the students could develop a wholesome personality.
It was not uncommon to find as manyas ten thousand students in some ç
of the bigger institutions. Not only out of necessity but also as ç
a good practice, the senior and better-qualified students were made ç
to teach the novices and also supervise over their life and discipline.
Though punishments for transgressions existed, they were not very ç
severe. Incorrigible students were expelled to save the discipline ç
and reputation of the institution.
@NT = Guruv<193>y<220>r
@N1 = (`town established by Guru [B<216>haspati] and V<193>yu')
@SB8.5 = Introduction
One of the well-known and popular places of pilgrimage, especially ç
for the devotees of K<216><218><207>a, is Guruv<193>y<220>r in the ç
Kerala State. It is a small town situated to the west of the city ç
of Tri··<220>r or Trichur, at a distance of 30 kms. (20 miles). It ç
is famous for its temple of <185>r<200>k<216><218><207>a, the deity ç
being fondly called Guruv<193>y<220>rappan (father or master of Guruv<193>y<220>r).
@SB8.5 = Local Legends
According to the sthalapur<193><207>a or the local legends based on ç
the N<193>rad<200>yapur<193><207>a (Gurupavanapuram<193>h<193>tmya), ç
the image was being worshipped at Dv<193>rak<193> by <185>r<200>k<216><218><207>a ç
himself. When the city was submerged, he gave it to his disciple Uddhava ç
with the instruction that, in consultation with Guru (B<216>haspati, ç
the preceptor of gods) and V<193>yu (the wind- god), it should be ç
installed in a suitable holy place. When Guru and V<193>yu came to ç
the south, in search of a suitable place, the great sage Para·ur<193>ma ç
helped them to find one and got it installed in a beautiful temple.
@SPACE1 = 
Thus, according to this traditional account, the temple is at least ç
5000 years old.
King Janamejaya, the great grandson of the P<193><207><195>ava hero ç
Arjuna, is said to have worshipped this deity to get rid of his leprosy ç
which he had contracted by the performance of the Sarpay<193>ga (serpent-sacrifice) ç
to exterminate the entire race of serpents. (See <MS>JANAMEJAYA<D> ç
for details.)
@SB8.5 = A Brief History
Historically speaking, the earliest references to this temple are ç
available only from the 16th century onwards.
During the various political turmoils that South India had to face, ç
the temple suffered many times at the hands of the Dutch (<MS>A.<|>D.<D> ç
1756), Haidar Al<200> (<MS>A.<|>D.<D> 1766) and <187>ippu Sult<193>n ç
(<MS>A.<|>D.<D> 1789). It was ultimately saved by the princes of the ç
Zamorin family in <MS>A.<|>D.<D> 1792.
From <MS>A.<|>D.<D> 1825 onwards, the condition of the temple improved, ç
mainly due to the dedicated services of the Ulan<193><195> Pa<207>ikkars' ç
family.
The eastern gopuram (tower) was rebuilt in <MS>A.<|>D.<D> 1842. Renovations ç
and beautifications of the central shrine and the ma<207><195>apa ç
(open auditorium) as also of the dhvajastambha (flag-staff), were ç
carried out in <MS>A.<|>D.<D> 1892. Several administrative reforms ç
were introduced from <MS>A.<|>D.<D> 1900 onwards. Temple doors were ç
thrown open to the people of the lower castes, hitherto treated as ç
untouchables, from <MS>A.D.<D> 1931. Gold-casing of the dhvajastambha ç
was completed in <MS>A.<|>D.<D> 1952.
In  <MS>A.<|>D.<D> 1970,  a  disastrous  fire destroyed a major part ç
of the buildings, the main shrine and the subsidiary ones being miraculously ç
untouched. Very soon, the temple-complex was restored to its original ç
form.
@SB8.5 = The Presiding Deity
The main deity in the sanctum sanctorum†called <185>r<200>koil†is ç
that of N<193>r<193>ya<207>a in the standing posture. It is made of ç
a rare stone called p<193>t<193>la-a<210>janam (black bismuth). It ç
has four arms carrying the ·a<209>kha (conch), cakra (discus), gad<193> ç
(mace) and padma (lotus). It is adorned with a tulas<200> (holy basil) ç
garland and a pearl necklace. The walls of the <185>r<200>koil are ç
adorned with  paintings  depicting  boy  K<216><218><207>a's pastimes.
@SB8.5 = The Temple Complex
The main temple is rather small in size and has been built in the ç
typical Kerala style of architecture, with a wooden roof covered with ç
copper plates, over the main shrine. It faces east and is usually ç
entered from that direction.
The eastern gateway, called Bh<220>vai-ku<207><219>ham, is the main ç
entrance. The dhvajastambha is gold-plated and is 33.5 metres (110 ç
ft.) high. On either side of it, there are two d<200>pastambhas (pillars ç
of lamps), 7 metres (22 ft.) in height with13 circular receptacles ç
for lighting the lamps.
Surrounding the garbhag<216>ha or the sanctum, is a pillared hall ç
known as N<193>lambalam.  On  the  outside  of  the northern wall ç
surrounding the sanctum is the vi<202>akkumatam, a gallery of 11 rows ç
of 6614 tiny lamps that are lit on festival days.
On the outside of the whole structure, there is a paved path for processions ç
called m<193>tilakam.
Other structures in this area are: thestage for K<216><218><207>a-a<219><219>am ç
(dance drama on  K<216><218><207>a);  two  v<193>tilmatams  (raised ç
platforms with carved pillars); temple kitchen; shrines for Ga<207>e·a ç
and <185><193>st<193> (or Ayyappan).
It is interesting to note that there is a permanently closed cell ç
on the western side of the kitchen, believed to house many precious ç
jewels and guarded by the Pa<210>can<193>gas (five divine serpents).
Other temples at and near Guruv<193>y<220>r are: <185>iva-P<193>rvat<200> ç
temple at Mammiy<220>r to the north-west; N<193>r<193>ya<207><200> ç
temple to the north of Mammiy<220>r; P<193>rthas<193>rathi temple, ç
believed to be more than 1000 years old; Tiruve<209>ka<219>am temple ç
near the above one; Peruta<219><219>a <185>iva temple to the south ç
of Guruv<193>y<220>r temple, at a distance of one kilometre.
@SB8.5 = Rites and Rituals
The  main  temple  at  Guruv<193>y<220>r follows an elaborate system ç
of rites and rituals initiated by <185>a<209>kara (<MS>A.<|>D.<D> 788-820). ç
There are five main p<220>jas (worship) perday spread over the period ç
3 <MS>A.M.<D> to 10 <MS>P.M.<D> The utsavam<220>rti (processional ç
image) is taken round the main shrine twice a day, mounted on an elephant.
The dar·an (seeing the deity) at 3<MS>A.M.<D> with all the flowers ç
and garlandsof the previous day, is considered extremely auspicious. ç
This is known as nirm<193>lya-dar·ana (nirm<193>lya = used flowers, ç
to be removed and thrown away in a place set apart for it). Usually ç
there will be a heavy crowd of devotees for this.
One of the popular modes of offering by the devotees is the tul<193>bh<193>ram. ç
It is the ritual of weighing oneself against a specified material ç
like bananas, sugar, jaggery, coconuts, sandalwood and so on. The ç
material is then gifted to the temple.
@SB8.5 = Festivals
The following are the most important of the numerous festivals conducted ç
in this temple:
G<200>t<193>jayant<200>; Vi<218>u (New year's day which falls generally ç
on the 15th April); Ak<218>ayyat<216>t<200>y<193> (in April/May); ç
Brahmotsavam or Utsavam, the main annual festival spread over ten ç
days, during February/March, an elephant race being a great attraction.
The last day of the Utsavam is observed as the special bathing festival ç
of the Lord at the temple-tank called Rudrat<200>rtha.
Next to this tank is the temple of Bhagavat<200> (Divine Mother). ç
At this temple, the Navar<193>tra festival is observed on a grand ç
scale.
The other festivals are K<216><218><207>ajanm<193><218><219>am<200> ç
(in August/September) and Kucela's Day (first Wednesday in M<193>rga·ira ç
(December/January).
@SB8.5 = Cultural Programmes
Several  cultural  programmes  and religious discourses are conducted ç
under the aegis of the Guruv<193>y<220>r temple. They are: K<216><218><207><193><219><219>am; ç
K<220><219><219>u; Bh<193>gavata Sapt<193>ha; recital of the N<193>r<193>ya<207><200>yam.
The K<216><218><207><193><219><219>am is a dance-drama with characters ç
acting their roles while the story is narrated by others. So also ç
the singing. It is enacted on nine days, with one theme from K<216><218><207>a's ç
life (except the last scene of K<216><218><207>a's ascension) on each ç
day, between 10 <MS>P.M.<D> and 3 <MS>A.M.<D> A special permanent ç
stage has been erected in the north-western part of the processional ç
path (m<193>tilakam).
The K<220><219><219>u is a mono-acting performance by a talented artist, ç
the themes being selected from the two epics as also the Bh<193>gavata. ç
Humour and wit are the keynotes of this performance. It is enacted ç
at the place reserved for it in the south-east corner, the place being ç
called k<220><219><219>amba<202>am.
The Bh<193>gavata-sapt<193>ha†recital of the Bh<193>gavata spread ç
over seven days†is conducted quite often.
The N<193>r<193>ya<207><200>yam is an extremely famous and popular ç
work in the Kerala State. It is a condensed version†but anoriginal ç
work†of the Bh<193>gavata by Meppatt<220>r N<193>r<193>ya<207>a ç
Bha<219><219><193>tirip<193>d (<MS>A.<|>D.<D> 1560-1625). (See <MS>N°R°YAØA ç
BHA<187><187>°TIRI<D>.) Arecital of this work is also conducted regularly ç
in the temple.
@SB8.5 = God of Miracles
Innumerable  miracles  have  been attributed to the grace of the Lord ç
here by the faithful. The votaries belonging to non-Hindu faiths too ç
are being drawn towards this deity.
The gingelly-oil used in the bathing of the image during abhi<218>eka ç
(ceremonial bath) is in great demand since it is believed to be a ç
sure medicine for arthritis and similar diseases.
It is interesting to note here, the story of the temple elephant (tusker) ç
Ke·avan by name. It served the temple during all the festivals and ç
ceremonies, for 62 years, including the carrying of the ti<195>ambu ç
(golden howdah) for 54 years. It was extremely docile and friendly. ç
It died quietly and suddenly in <MS>A.<|>D.<D> 1976, in front of the ç
chief gateway, as if bowing down to the deity. A life-size image of ç
this elephant had been installed in the campus and its day of demise ç
is celebrated with a procession of decorated elephants.
@SB8.5 = Finis
While visiting a holy place, a pilgrim expects not only spiritual ç
solace but also the fulfilment of his desires which he is unable to ç
achieve through normal human efforts. The Guruv<193>y<220>r temple ç
has certainly succeeded in fulfilling such hopes and aspirations of ç
its votaries if judged from the numerous experiences of numberless ç
devotees.
There is no wonder then, that year by year, the number of pilgrims ç
is swelling, contributions by them is increasing, thus making it one ç
of the few most popular temples of India with a fabulous income which ç
is being properly utilised by the temple management.
@SPACE = 
@NT = guruv<216>tti
@N1 = (`behaviour before the guru')
@SPACE = 
In the ancient days, education was imparted in the gurukulas or the ç
houses of the gurus, the preceptors. A brahmac<193>rin (the Vedic ç
student) was expected to follow strictly a code of conduct prescribed ç
for him. That part of it, which concerned his behaviour (= v<216>tti) ç
before the guru, was called `guruv<216>tti'.
The Vedic student was expected to desire the welfare of his guru always. ç
He was to be diligent in his studies even if he was not specifically ç
directed to do so. He was to cultivate a very pure and reverential ç
attitude towards the guru. He was also to avoid any type of ostentation ç
before him. He should never sit in his presence, unless permitted ç
to do so. He should never speak ill of or criticise his guru before ç
anyone at anytime nor listen to such words if others are doing so. ç
He must never address his guru by his name (vide Manusm<216>ti, ç
Second Chapter).
@END = 
