@T1 = A Concise Encyclopaedia of<R>ç
HINDUISM
@T3 = (in 3 Volumes + 1 Supplementary Volume)
@T1-1 = (Covers all aspects of Hindu Religion Philosophy and Culture)
@T2 = by Swami Harshananda
@T4 = Size	:  Crown quarto (24 x 18 cm)
@T4 = Paper	:  90 gsm NS Maplitho
@T4 = End-Papers	:  120 gsm Paper with Lamination
@T4 = Binding	:  Full Calico
@T4 = Jacket	:  170 gsm Art Paper with Lamination
@T5 = No. of Articles	:	3788
@T5 = No. of Pages	:	2312
@T5 = Line Drawings	:	234
@T5 = Colour Photographs	:	124
@T5 = Approx. Weight	:  6.5 Kgs.
@T6 = Price Per Set of Four Volumes	:<+><+>Rs. 2300/-
@T7 = <P14.5B>Ramakrishna Math<P255D><R>ç
Bull Temple Road<R>ç
Bangalore<|>-<|>560<|>019.<R>ç
Karnataka<|><|><196> India.
@T7 = Phone and e-mails<|>:<R>ç
Office	:	91-80-2661<|>3149, 2667<|>1010<R>ç
		rkmfive@gmail.com<R>ç
Bookstall	:	91-80-2661<|>6161, 2661<|>6060<R>ç
		bangalorebookstall@gmail.com<R>ç
Website	:	www.rkmathbangalore.org
