@H = Volume Two at a Glance
@Z_TOC LVL 1 = Preface	v
@Z_TOC LVL 1 = Acknowledgements	viii
@Z_TOC LVL 1 = List of Photographs <P9W1>(<MI>Vide<W1> Photo Section<R>ç
<+><+>at the end of the book)<P255D>	ix
@Z_TOC LVL 1 = Key to Transliteration<R>ç
<+><+>and Pronunciation	xi
@Z_TOC TITLE = H
@Z_TOC LVL 1 = H<193>dividy<193>	1
@Z_TOC LVL 1 = Haihaya	1
@Z_TOC LVL 1 = Haimavat<200>	1
@Z_TOC LVL 1 = H<193>l<193>hala	1
@Z_TOC LVL 1 = Hal<193>yudha	1
@Z_TOC LVL 1 = Ha<202>eb<200><195>u	1
@Z_TOC LVL 1 = Hampi	2
@Z_TOC LVL 1 = ha<221>sa	4
@Z_TOC LVL 1 = Ha<221>sag<200>t<193>	4
@Z_TOC LVL 1 = Ha<221>savidy<193>	5
@Z_TOC LVL 1 = Ha<221>sopani<218>ad	5
@Z_TOC LVL 1 = Hanum<193>n	5
@Z_TOC LVL 1 = Han<220>mann<193><219>aka	5
@Z_TOC LVL 1 = Haradatta	6
@Z_TOC LVL 1 = Haragaur<200>	6
@Z_TOC LVL 1 = Harappa	6
@Z_TOC LVL 1 = Hargobind, Guru	6
@Z_TOC LVL 1 = Harid<193>sas, of Karnataka	7
@Z_TOC LVL 1 = Harid<193>sa, Sv<193>m<200>	7
@Z_TOC LVL 1 = Harid<193>s, S<193>dhu	7
@Z_TOC LVL 1 = Haridr<193>-Ga<207>apati	8
@Z_TOC LVL 1 = Haridv<193>ra	8
@Z_TOC LVL 1 = Harihara	9
@Z_TOC LVL 1 = harijans	9
@Z_TOC LVL 1 = harikath<193>	9
@Z_TOC LVL 1 = Harimandir	10
@Z_TOC LVL 1 = Hari·candra	11
@Z_TOC LVL 1 = H<193>r<200>ta	11
@Z_TOC LVL 1 = H<193>r<200>tag<200>t<193>	12
@Z_TOC LVL 1 = Harit<193>lik<193>	12
@Z_TOC LVL 1 = Hariva<221>·a	12
@Z_TOC LVL 1 = hariv<193>sara	13
@Z_TOC LVL 1 = Harivy<193>sadeva	13
@Z_TOC LVL 1 = Harki<218>an, Guru	14
@Z_TOC LVL 1 = Har R<193>i, Guru	14
@Z_TOC LVL 1 = hasta	15
@Z_TOC LVL 1 = hast<193>	15
@Z_TOC LVL 1 = Hast<193>malaka	15
@Z_TOC LVL 1 = Hasta-s<193>mudrika-·<193>stra	15
@Z_TOC LVL 1 = Hastin<193>pura	16
@Z_TOC LVL 1 = Ha<219>hayoga	17
@Z_TOC LVL 1 = Ha<219>hayoga-prad<200>pik<193>	18
@Z_TOC LVL 1 = havana	18
@Z_TOC LVL 1 = havirdh<193>na	18
@Z_TOC LVL 1 = haviryaj<210>a	18
@Z_TOC LVL 1 = havis	19
@Z_TOC LVL 1 = havi<218>ya	19
@Z_TOC LVL 1 = Hayagr<200>va	19
@Z_TOC LVL 1 = Hayagr<200>vasa<221>hit<193>	20
@Z_TOC LVL 1 = Hayagr<200>va Upani<218>ad	20
@Z_TOC LVL 1 = heaven	21
@Z_TOC LVL 1 = Hedonism	21
@Z_TOC LVL 1 = Heliodoros	21
@Z_TOC LVL 1 = hell	21
@Z_TOC LVL 1 = Hem<193>dri	21
@Z_TOC LVL 1 = Hemak<220><219>a	21
@Z_TOC LVL 1 = hema·r<193>ddha	21
@Z_TOC LVL 1 = Heramba-Ga<207>apati	22
@Z_TOC LVL 1 = heretics	22
@Z_TOC LVL 1 = hetu	22
@Z_TOC LVL 1 = hetv<193>bh<193>sa	22
@Z_TOC LVL 1 = Him<193>layas	23
@Z_TOC LVL 1 = hi<221>s<193> 	23
@Z_TOC LVL 1 = Hinduism	24
@Z_TOC LVL 1 = Hindu Temples	36
@Z_TOC LVL 1 = hi<209>k<193>ra	55
@Z_TOC LVL 1 = Hira<207>yagarbha	55
@Z_TOC LVL 1 = Hira<207>yagarbha S<220>kta	55
@Z_TOC LVL 1 = Hira<207>yaka·ipu	56
@Z_TOC LVL 1 = Hira<207>yake·i Dharmas<220>tras	56
@Z_TOC LVL 1 = Hira<207>y<193>k<218>a	57
@Z_TOC LVL 1 = hita	57
@Z_TOC LVL 1 = Hitopade·a	57
@Z_TOC LVL 1 = hl<193>din<200>	57
@Z_TOC LVL 1 = Holi, Holik<193>	57
@Z_TOC LVL 1 = homa	59
@Z_TOC LVL 1 = hor<193>	59
@Z_TOC LVL 1 = horoscope	59
@Z_TOC LVL 1 = hospitality	59
@Z_TOC LVL 1 = hot<216>	60
@Z_TOC LVL 1 = house	60
@Z_TOC LVL 1 = h<216>daya	60
@Z_TOC LVL 1 = h<216>d-dhauti	60
@Z_TOC LVL 1 = hr<200><221>	61
@Z_TOC LVL 1 = humours	61
@Z_TOC LVL 1 = hymnology	61
@Z_TOC TITLE = I
@Z_TOC LVL 1 = icch<193>·akti	62
@Z_TOC LVL 1 = Iconography	62
@Z_TOC LVL 1 = i<195><193>	62
@Z_TOC LVL 1 = idhma	62
@Z_TOC LVL 1 = Idhmav<193>ha	62
@Z_TOC LVL 1 = idols	63
@Z_TOC LVL 1 = ignorance	63
@Z_TOC LVL 1 = Ik<218>v<193>ku	63
@Z_TOC LVL 1 = I<202><193>	63
@Z_TOC LVL 1 = illusion	63
@Z_TOC LVL 1 = Ilvala	63
@Z_TOC LVL 1 = image worship	64
@Z_TOC LVL 1 = immortality	64
@Z_TOC LVL 1 = immortals	64
@Z_TOC LVL 1 = incarnation	64
@Z_TOC LVL 1 = Indian Philosophy	64
@Z_TOC LVL 1 = Indra	64
@Z_TOC LVL 1 = Indradhvaja	65
@Z_TOC LVL 1 = Indradyumna	66
@Z_TOC LVL 1 = Indraj<193>la	66
@Z_TOC LVL 1 = Indrajit	66
@Z_TOC LVL 1 = Indr<193>k<218><200>	67
@Z_TOC LVL 1 = Indr<193><207><200>	67
@Z_TOC LVL 1 = Indraprastha	67
@Z_TOC LVL 1 = indriyadh<193>ra<207><193>	68
@Z_TOC LVL 1 = indriyanigraha	68
@Z_TOC LVL 1 = indriyas	68
@Z_TOC LVL 1 = Indus Valley Civilisation	69
@Z_TOC LVL 1 = inheritance	72
@Z_TOC LVL 1 = intercalary month	72
@Z_TOC LVL 1 = ®·<193>na	72
@Z_TOC LVL 1 = ®·<193>v<193>sya Upani<218>ad	72
@Z_TOC LVL 1 = i<218><219>adevat<193>	74
@Z_TOC LVL 1 = i<218><219>ak<193>	75
@Z_TOC LVL 1 = i<218><219>ali<209>ga	75
@Z_TOC LVL 1 = i<218><219><193>p<220>rta	75
@Z_TOC LVL 1 = I<218><219>asiddhi	76
@Z_TOC LVL 1 = i<218><219>i	76
@Z_TOC LVL 1 = ®·vara	76
@Z_TOC LVL 1 = ®·varacandra Vidy<193>s<193>gara	77
@Z_TOC LVL 1 = ®·varag<200>t<193>	78
@Z_TOC LVL 1 = ®·varak<216><218><207>a	78
@Z_TOC LVL 1 = <200>·varapra<207>idh<193>na	79
@Z_TOC LVL 1 = Itar<193>	79
@Z_TOC LVL 1 = itih<193>sa	79
@Z_TOC LVL 1 = itikartavyat<193>	79
@Z_TOC TITLE = J
@Z_TOC LVL 1 = J<193>b<193>la Upani<218>ad	80
@Z_TOC LVL 1 = J<193>b<193>li	81
@Z_TOC LVL 1 = J<193>b<193>li Upani<218>ad	81
@Z_TOC LVL 1 = Ja<195>abharata	82
@Z_TOC LVL 1 = Jagann<193>thad<193>sa	82
@Z_TOC LVL 1 = Jagann<193>tha Pa<207><195>ita	83
@Z_TOC LVL 1 = Jagann<193>tha-Pur<200>	83
@Z_TOC LVL 1 = Jagann<193>tha Temple	84
@Z_TOC LVL 1 = jagat<200>	84
@Z_TOC LVL 1 = j<193>grat	85
@Z_TOC LVL 1 = Jahad-ajahal-lak<218>a<207><193>	85
@Z_TOC LVL 1 = Jahal-lak<218>a<207><193>	85
@Z_TOC LVL 1 = J<193>hnav<200>	85
@Z_TOC LVL 1 = Jaig<200><218>avya	85
@Z_TOC LVL 1 = J<193>jali	85
@Z_TOC LVL 1 = Jaimini	85
@Z_TOC LVL 1 = Jaimini-s<220>tras	85
@Z_TOC LVL 1 = Jaimin<200>ya G<216>hyas<220>tras	86
@Z_TOC LVL 1 = Jaina R<193>m<193>ya<207>as	86
@Z_TOC LVL 1 = Jainism	86
@Z_TOC LVL 1 = jalabasti	87
@Z_TOC LVL 1 = jal<193>dhiv<193>sa	87
@Z_TOC LVL 1 = jalak<216>cchra	87
@Z_TOC LVL 1 = j<193>landharabandha	87
@Z_TOC LVL 1 = jalpa	88
@Z_TOC LVL 1 = Jamadagni	88
@Z_TOC LVL 1 = J<193>mbav<193>n	88
@Z_TOC LVL 1 = Jamb<220>dv<200>pa	89
@Z_TOC LVL 1 = Janaka	89
@Z_TOC LVL 1 = Janaloka	89
@Z_TOC LVL 1 = Janamejaya	90
@Z_TOC LVL 1 = janana	90
@Z_TOC LVL 1 = janapada	90
@Z_TOC LVL 1 = Jan<193>rdana Sv<193>min	91
@Z_TOC LVL 1 = J<193>na·ruti	91
@Z_TOC LVL 1 = Janasth<193>na	92
@Z_TOC LVL 1 = ja<209>gama	92
@Z_TOC LVL 1 = Janm<193><218><219>am<200>	92
@Z_TOC LVL 1 = japa	93
@Z_TOC LVL 1 = japam<193>l<193>	94
@Z_TOC LVL 1 = Jar<193>sandha	95
@Z_TOC LVL 1 = Jaratk<193>ru	95
@Z_TOC LVL 1 = ja<219><193>	96
@Z_TOC LVL 1 = j<193>taka	96
@Z_TOC LVL 1 = j<193>takarma	96
@Z_TOC LVL 1 = ja<219><193>muku<219>a	97
@Z_TOC LVL 1 = ja<219><193>p<193><219>ha	97
@Z_TOC LVL 1 = Ja<219><193>yu	97
@Z_TOC LVL 1 = j<193>ti	98
@Z_TOC LVL 1 = j<193>tij<210><193>na	98
@Z_TOC LVL 1 = J<193>t<220>kar<207>ya	98
@Z_TOC LVL 1 = J<193>va	98
@Z_TOC LVL 1 = Jaya	99
@Z_TOC LVL 1 = Jayadeva	99
@Z_TOC LVL 1 = Jay<193>khya Sa<221>hit<193>	100
@Z_TOC LVL 1 = jayant<200>s	104
@Z_TOC LVL 1 = Jayar<193>mb<193><219><200>	106
@Z_TOC LVL 1 = Jayat<200>rtha	106
@Z_TOC LVL 1 = J<200>m<220>tav<193>hana	107
@Z_TOC LVL 1 = Jinas	107
@Z_TOC LVL 1 = J<200>vagosv<193>min	108
@Z_TOC LVL 1 = j<200>va, j<200>v<193>tman	108
@Z_TOC LVL 1 = j<200>vana	108
@Z_TOC LVL 1 = j<200>vanmukti	108
@Z_TOC LVL 1 = J<200>vanmuktiviveka	109
@Z_TOC LVL 1 = j<200>vat-·r<193>ddha	109
@Z_TOC LVL 1 = j<200>votkr<193>nti	109
@Z_TOC LVL 1 = j<210><193>na	109
@Z_TOC LVL 1 = J<210><193>nak<193><207><195>a	110
@Z_TOC LVL 1 = j<210><193>na-karma-samuccaya-v<193>da	110
@Z_TOC LVL 1 = j<210><193>nam<193>rga	111
@Z_TOC LVL 1 = j<210><193>namudr<193>	111
@Z_TOC LVL 1 = j<210><193>na·akti	111
@Z_TOC LVL 1 = J<210><193>nasambandhar	111
@Z_TOC LVL 1 = J<210><193>nayoga	112
@Z_TOC LVL 1 = j<210><193>nendriyas	114
@Z_TOC LVL 1 = J<210><193>ne·var, Sant	114
@Z_TOC LVL 1 = j<210><193>t<216>tva	115
@Z_TOC LVL 1 = juh<220>	115
@Z_TOC LVL 1 = Jupiter	116
@Z_TOC LVL 1 = Jyauti<218>a	116
@Z_TOC LVL 1 = Jye<218><219>h<193>	117
@Z_TOC LVL 1 = Jyotirli<209>gas	117
@Z_TOC LVL 1 = Jyotir Ma<219>ha	118
@Z_TOC LVL 1 = jyoti<218>mat<200>	118
@Z_TOC LVL 1 = Jyoti<218><219>oma	118
@Z_TOC TITLE = K
@Z_TOC LVL 1 = Kabandha	119
@Z_TOC LVL 1 = Kab<200>r	119
@Z_TOC LVL 1 = Kaca	120
@Z_TOC LVL 1 = K<193>dividy<193>	120
@Z_TOC LVL 1 = Kadr<220>	120
@Z_TOC LVL 1 = Kahola	120
@Z_TOC LVL 1 = Kaikey<200>	121
@Z_TOC LVL 1 = Kail<193>sa	121
@Z_TOC LVL 1 = Kail<193>sanatha Temple	121
@Z_TOC LVL 1 = Kai<219>abha	121
@Z_TOC LVL 1 = kaivalya	121
@Z_TOC LVL 1 = Kaivalya Upani<218>ad	122
@Z_TOC LVL 1 = K<193>kin<200>	123
@Z_TOC LVL 1 = kal<193>	123
@Z_TOC LVL 1 = k<193>la	123
@Z_TOC LVL 1 = K<193>labhairava	123
@Z_TOC LVL 1 = K<193>la<195><200>	124
@Z_TOC LVL 1 = K<193>l<193>gnirudra	125
@Z_TOC LVL 1 = K<193><202>ahast<200>	125
@Z_TOC LVL 1 = k<193>lak<218>epa	126
@Z_TOC LVL 1 = K<193>l<193>mukha	126
@Z_TOC LVL 1 = K<193>lanir<207>aya	126
@Z_TOC LVL 1 = K<193>lar<193>tri	127
@Z_TOC LVL 1 = kala·a	127
@Z_TOC LVL 1 = K<193>layavana	127
@Z_TOC LVL 1 = Kali	128
@Z_TOC LVL 1 = K<193>l<200>	128
@Z_TOC LVL 1 = K<193>lid<193>sa	130
@Z_TOC LVL 1 = K<193>lik<193>pur<193><207>a	131
@Z_TOC LVL 1 = K<193>lind<200>	131
@Z_TOC LVL 1 = Kali<209>ga	131
@Z_TOC LVL 1 = Kalisantara<207>a Upani<218>ad	132
@Z_TOC LVL 1 = kalivarjya	132
@Z_TOC LVL 1 = Kaliyuga	133
@Z_TOC LVL 1 = Kalki	133
@Z_TOC LVL 1 = Kalm<193><218>ap<193>da	134
@Z_TOC LVL 1 = kalpa	134
@Z_TOC LVL 1 = kalpan<193>gaurava	134
@Z_TOC LVL 1 = kalpan<193>l<193>ghava	134
@Z_TOC LVL 1 = Kalpas<220>tras	135
@Z_TOC LVL 1 = Kalpataru	135
@Z_TOC LVL 1 = k<193>ma	135
@Z_TOC LVL 1 = K<193>madhenu	136
@Z_TOC LVL 1 = K<193>makal<193>	136
@Z_TOC LVL 1 = K<193>m<193>khy<193>	136
@Z_TOC LVL 1 = K<193>m<193>k<218><200>	137
@Z_TOC LVL 1 = Kamal<193>kara	138
@Z_TOC LVL 1 = K<193>mandaka	138
@Z_TOC LVL 1 = kama<207><195>alu	139
@Z_TOC LVL 1 = K<193>m<193>rpuk<220>r	139
@Z_TOC LVL 1 = K<193>ma·<193>stra	139
@Z_TOC LVL 1 = K<193>mbhoja	140
@Z_TOC LVL 1 = K<193>me·vara	140
@Z_TOC LVL 1 = K<193>me·var<200>	140
@Z_TOC LVL 1 = Ka<221>sa	140
@Z_TOC LVL 1 = k<193>myakarma	141
@Z_TOC LVL 1 = k<193>mye<218><219>i	141
@Z_TOC LVL 1 = Ka<207><193>da	142
@Z_TOC LVL 1 = Kanakad<193>sa	142
@Z_TOC LVL 1 = Kanakhala	143
@Z_TOC LVL 1 = K<193><210>c<200>puram	143
@Z_TOC LVL 1 = ka<210>cukas	143
@Z_TOC LVL 1 = Kandariya Mah<193>deva Temple	144
@Z_TOC LVL 1 = k<193><207><195>ar<218>i	144
@Z_TOC LVL 1 = K<193><209>gri Gurukula	144
@Z_TOC LVL 1 = ka<209>ka<207>a	144
@Z_TOC LVL 1 = Ka<207><207>agi	144
@Z_TOC LVL 1 = Ka<207><207>appa	145
@Z_TOC LVL 1 = ka<207><219>aka·odhana	145
@Z_TOC LVL 1 = Ka<207>va	146
@Z_TOC LVL 1 = K<193><207>va·<193>kh<193>	146
@Z_TOC LVL 1 = kany<193>	146
@Z_TOC LVL 1 = kany<193>d<193>na	147
@Z_TOC LVL 1 = Kanyak<193>-Parame·var<200>	147
@Z_TOC LVL 1 = Kany<193>kum<193>r<200>	147
@Z_TOC LVL 1 = kap<193>la	148
@Z_TOC LVL 1 = kap<193>labh<193>ti	149
@Z_TOC LVL 1 = K<193>p<193>lika	149
@Z_TOC LVL 1 = Kapila	149
@Z_TOC LVL 1 = Kapilag<200>t<193>	149
@Z_TOC LVL 1 = Kapisthala-K<193><219>haka-Sa<221>hit<193>	149
@Z_TOC LVL 1 = k<193>ra<207>a	150
@Z_TOC LVL 1 = k<193>ra<207>a·ar<200>ra	150
@Z_TOC LVL 1 = kara<207><195>a-muku<219>a	150
@Z_TOC LVL 1 = karany<193>sa	151
@Z_TOC LVL 1 = Karav<200>ra	151
@Z_TOC LVL 1 = Kardama	151
@Z_TOC LVL 1 = karma	151
@Z_TOC LVL 1 = Karmak<193><207><195>a	152
@Z_TOC LVL 1 = K<193>rma-mala	152
@Z_TOC LVL 1 = karmam<193>rga	153
@Z_TOC LVL 1 = karmam<200>m<193><221>s<193>	153
@Z_TOC LVL 1 = karmasa<221>ny<193>sa	153
@Z_TOC LVL 1 = karm<193>·aya	153
@Z_TOC LVL 1 = karmavip<193>ka	154
@Z_TOC LVL 1 = Karmayoga	154
@Z_TOC LVL 1 = karmendriyas	155
@Z_TOC LVL 1 = Kar<207>a	156
@Z_TOC LVL 1 = Kar<207>aparva	157
@Z_TOC LVL 1 = kar<207>arandhra-dhauti	157
@Z_TOC LVL 1 = kar<207>avedha	157
@Z_TOC LVL 1 = K<193>rtav<200>ry<193>rjuna	157
@Z_TOC LVL 1 = kart<216>tva	158
@Z_TOC LVL 1 = K<193>rttikeya	158
@Z_TOC LVL 1 = k<193>rya	158
@Z_TOC LVL 1 = k<193>rya-k<193>ra<207>a-bh<193>va	158
@Z_TOC LVL 1 = ka<218><193>ya	158
@Z_TOC LVL 1 = K<193>·<200>	158
@Z_TOC LVL 1 = K<193>·m<200>r <185>aivism	160
@Z_TOC LVL 1 = Ka·yapa	160
@Z_TOC LVL 1 = K<193>·yapa Sa<221>hit<193>	160
@Z_TOC LVL 1 = Ka<219>ha Upani<218>ad	161
@Z_TOC LVL 1 = K<193><219>haka G<216>hyas<220>tras	164
@Z_TOC LVL 1 = Kathakal<200>	164
@Z_TOC LVL 1 = Ka<219>ha Sa<221>hith<193>	165
@Z_TOC LVL 1 = K<193><219>haka Sa<221>hit<193>	165
@Z_TOC LVL 1 = Ka<219>harudropani<218>ad	165
@Z_TOC LVL 1 = K<193>ty<193>yana	166
@Z_TOC LVL 1 = K<193>ty<193>yan<200>	167
@Z_TOC LVL 1 = kaula	167
@Z_TOC LVL 1 = Kaul<193>c<193>ra, Kaulam<193>rga	167
@Z_TOC LVL 1 = Kaum<193>r<200>	167
@Z_TOC LVL 1 = Kaumodak<200>	168
@Z_TOC LVL 1 = Kausaly<193>	168
@Z_TOC LVL 1 = Kau·ika	168
@Z_TOC LVL 1 = Kau·ika G<216>hyas<220>tras	169
@Z_TOC LVL 1 = Kau·ika S<220>tras	169
@Z_TOC LVL 1 = Kau<218><200>taki Br<193>hma<207>a	170
@Z_TOC LVL 1 = Kau<218><200>taki Br<193>hma<207>a Upani<218>ad	170
@Z_TOC LVL 1 = Kau<218><200>taki G<216>hyas<220>tras	172
@Z_TOC LVL 1 = Kaustubha	172
@Z_TOC LVL 1 = Kau<219>ilya	172
@Z_TOC LVL 1 = Kautsas<220>kta	172
@Z_TOC LVL 1 = Kautukabera	173
@Z_TOC LVL 1 = k<193>va<195><200>	173
@Z_TOC LVL 1 = Kava<218>a Ail<220><218>a	173
@Z_TOC LVL 1 = K<193>ver<200>	173
@Z_TOC LVL 1 = K<193>vya U·anas	174
@Z_TOC LVL 1 = k<193>yasampat	174
@Z_TOC LVL 1 = k<193>yastha	175
@Z_TOC LVL 1 = k<193>ya·uddhi	175
@Z_TOC LVL 1 = k<193>yavy<220>haj<210><193>na	175
@Z_TOC LVL 1 = Ked<193>ran<193>tha	175
@Z_TOC LVL 1 = Kena Upani<218>ad	176
@Z_TOC LVL 1 = ke·abandha	177
@Z_TOC LVL 1 = ke·<193>nta	178
@Z_TOC LVL 1 = Ke·avacandra Sen	178
@Z_TOC LVL 1 = ke·avapana	178
@Z_TOC LVL 1 = ke·avapan<200>ya	178
@Z_TOC LVL 1 = Ketu	178
@Z_TOC LVL 1 = key<220>ra	179
@Z_TOC LVL 1 = kha<195>ga	179
@Z_TOC LVL 1 = Kh<193>dira G<216>hyas<220>tras	179
@Z_TOC LVL 1 = Khajur<193>ho	180
@Z_TOC LVL 1 = Kh<193>ls<193>	180
@Z_TOC LVL 1 = Kha<207><195>ana-kha<207><195>a-kh<193>dya	180
@Z_TOC LVL 1 = Kharo<218><219>h<200>	181
@Z_TOC LVL 1 = kha<219>v<193><209>ga	181
@Z_TOC LVL 1 = khecar<200>mudr<193>	181
@Z_TOC LVL 1 = khe<219>aka	182
@Z_TOC LVL 1 = khila	182
@Z_TOC LVL 1 = khy<193>ti	182
@Z_TOC LVL 1 = K<200>caka	183
@Z_TOC LVL 1 = kimpuru<218>as	184
@Z_TOC LVL 1 = king	184
@Z_TOC LVL 1 = Kinnaras	184
@Z_TOC LVL 1 = kir<193>ta	184
@Z_TOC LVL 1 = kir<200><219>a	184
@Z_TOC LVL 1 = k<200>rtana	185
@Z_TOC LVL 1 = k<200>rtimukha	185
@Z_TOC LVL 1 = Ki<218>kindh<193>	185
@Z_TOC LVL 1 = kle·a	186
@Z_TOC LVL 1 = Koj<193>gar<200> P<220>r<207>im<193>	186
@Z_TOC LVL 1 = Kolh<193>pur	186
@Z_TOC LVL 1 = Koll<220>ru	187
@Z_TOC LVL 1 = Ko<207><193>rka	188
@Z_TOC LVL 1 = ko·a	188
@Z_TOC LVL 1 = Kosala	188
@Z_TOC LVL 1 = Ko<219>ihoma	189
@Z_TOC LVL 1 = kramamukti	189
@Z_TOC LVL 1 = kramapari<207><193>ma	190
@Z_TOC LVL 1 = kramap<193><219>ha	190
@Z_TOC LVL 1 = kr<193>nt<193>s	190
@Z_TOC LVL 1 = k<216>cchra	190
@Z_TOC LVL 1 = k<216>cchr<193>tik<216>cchra	190
@Z_TOC LVL 1 = kriy<193>·akti	190
@Z_TOC LVL 1 = Kriy<193>yoga	190
@Z_TOC LVL 1 = Kriy<193>yogas<193>ra	191
@Z_TOC LVL 1 = k<216>kala	191
@Z_TOC LVL 1 = K<216><218><207>a	191
@Z_TOC LVL 1 = K<216><218><207>a-dvaip<193>yana	216
@Z_TOC LVL 1 = K<216><218><207>a-janm<193><218><219>am<200>	216
@Z_TOC LVL 1 = k<216><218><207><193>jina	216
@Z_TOC LVL 1 = K<216><218><207>ami·ra	216
@Z_TOC LVL 1 = K<216><218><207>a Yajurveda	216
@Z_TOC LVL 1 = K<216>tayuga	216
@Z_TOC LVL 1 = K<216>ttik<193>	216
@Z_TOC LVL 1 = K<216>tyakalpataru	217
@Z_TOC LVL 1 = K<216>tyaratn<193>kara	217
@Z_TOC LVL 1 = kru<218><219>a	218
@Z_TOC LVL 1 = k<218>a<207>a	218
@Z_TOC LVL 1 = k<218>ara	218
@Z_TOC LVL 1 = k<218>arapuru<218>a	218
@Z_TOC LVL 1 = k<218>attriya	218
@Z_TOC LVL 1 = K<218>ema<209>kar<200>	218
@Z_TOC LVL 1 = k<218>etra	219
@Z_TOC LVL 1 = k<218>etraj<210>a	219
@Z_TOC LVL 1 = K<218>etrap<193>la	219
@Z_TOC LVL 1 = k<218>ipta	220
@Z_TOC LVL 1 = K<218><200>rabhav<193>n<200>	220
@Z_TOC LVL 1 = k<218><200>rasamudra	221
@Z_TOC LVL 1 = K<218><200>rasv<193>min	221
@Z_TOC LVL 1 = Kubera	221
@Z_TOC LVL 1 = Kucela	222
@Z_TOC LVL 1 = kuh<220>	222
@Z_TOC LVL 1 = Kuja	222
@Z_TOC LVL 1 = Kukke Subrahma<207>ya	222
@Z_TOC LVL 1 = kula	223
@Z_TOC LVL 1 = Kulaparvata	223
@Z_TOC LVL 1 = kulapati	223
@Z_TOC LVL 1 = Kula·ekhara °<202>v<193>r	223
@Z_TOC LVL 1 = Kull<220>kabha<219><219>a	223
@Z_TOC LVL 1 = Kum<193>ra	224
@Z_TOC LVL 1 = Kum<193>ra-Vy<193>sa	224
@Z_TOC LVL 1 = Kum<193>rila Bha<219><219>a	224
@Z_TOC LVL 1 = kumbhaka	225
@Z_TOC LVL 1 = Kumbhakar<207>a	225
@Z_TOC LVL 1 = Kumbhako<207>am	225
@Z_TOC LVL 1 = Kumbhamel<193>	226
@Z_TOC LVL 1 = Ku<207><195>alin<200>	227
@Z_TOC LVL 1 = Ku<207><195>ikopani<218>ad	227
@Z_TOC LVL 1 = Kunt<200>	228
@Z_TOC LVL 1 = Kura<202>	228
@Z_TOC LVL 1 = k<220>rca	228
@Z_TOC LVL 1 = K<220>re·a	229
@Z_TOC LVL 1 = K<220>rma	229
@Z_TOC LVL 1 = K<220>rmapur<193><207>a	230
@Z_TOC LVL 1 = Kuru	230
@Z_TOC LVL 1 = Kuruke·a	230
@Z_TOC LVL 1 = Kuruk<218>etra	230
@Z_TOC LVL 1 = Ku·a	231
@Z_TOC LVL 1 = ku·<193>sana	232
@Z_TOC LVL 1 = k<220><219>a·lokas	232
@Z_TOC LVL 1 = ku<219><200>caka	233
@Z_TOC TITLE = L
@Z_TOC LVL 1 = l<193>ghava	234
@Z_TOC LVL 1 = laghim<193>	234
@Z_TOC LVL 1 = Laghu H<193>r<200>ta Sm<216>ti	234
@Z_TOC LVL 1 = Laghurudra	234
@Z_TOC LVL 1 = Laghu Vi<218><207>usm<216>ti	234
@Z_TOC LVL 1 = Laghuyogav<193>si<218><219>ha	235
@Z_TOC LVL 1 = lagnanir<207>aya	236
@Z_TOC LVL 1 = l<193>jahoma	237
@Z_TOC LVL 1 = lak<218>ahoma	237
@Z_TOC LVL 1 = lak<218>a<207><193>	237
@Z_TOC LVL 1 = lak<218>a<207>a-pari<207><193>ma	238
@Z_TOC LVL 1 = Lak<218>ma<207>a	238
@Z_TOC LVL 1 = Lak<218>m<200>	238
@Z_TOC LVL 1 = Lak<218>m<200>dhara	240
@Z_TOC LVL 1 = Lakshmi<|>Venkateswara<|>Steam<|>Press	240
@Z_TOC LVL 1 = Lakul<200>·a	240
@Z_TOC LVL 1 = L<193>ld<193>s<200>s	240
@Z_TOC LVL 1 = Lalit<193>	241
@Z_TOC LVL 1 = Lalit<193>sahasran<193>ma	242
@Z_TOC LVL 1 = Lalit<193>tri·at<200>	243
@Z_TOC LVL 1 = Lalitop<193>khy<193>na	244
@Z_TOC LVL 1 = La<209>k<193>	244
@Z_TOC LVL 1 = La<209>k<193>k<193><207><195>a	245
@Z_TOC LVL 1 = Lava	245
@Z_TOC LVL 1 = laukik<200>	245
@Z_TOC LVL 1 = laya	245
@Z_TOC LVL 1 = layayoga	245
@Z_TOC LVL 1 = Lep<193>k<218>i	246
@Z_TOC LVL 1 = liberation	246
@Z_TOC LVL 1 = Licchavis	246
@Z_TOC LVL 1 = Likhita	247
@Z_TOC LVL 1 = l<200>l<193>m<220>rtis	247
@Z_TOC LVL 1 = L<200>l<193>·uka	247
@Z_TOC LVL 1 = li<209>ga	248
@Z_TOC LVL 1 = li<209>gadh<193>ra<207>a	248
@Z_TOC LVL 1 = Li<209>gapur<193><207>a	248
@Z_TOC LVL 1 = li<209>ga·ar<200>ra	248
@Z_TOC LVL 1 = li<209>gasthala	249
@Z_TOC LVL 1 = Li<209>g<193>yata Sect	249
@Z_TOC LVL 1 = lobha	249
@Z_TOC LVL 1 = logic	249
@Z_TOC LVL 1 = loka	249
@Z_TOC LVL 1 = Lok<193>c<193>rya	249
@Z_TOC LVL 1 = Lok<193>loka	249
@Z_TOC LVL 1 = lokap<193>las	249
@Z_TOC LVL 1 = lokasa<209>graha	249
@Z_TOC LVL 1 = Lok<193>yata	250
@Z_TOC LVL 1 = Lomahar<218>a<207>a	250
@Z_TOC LVL 1 = Lop<193>mudr<193>	250
@SPACE = 
@SPACE = 
@Z_TOC TITLE = M
@SPACE = 
@Z_TOC LVL 1 = mada	251
@Z_TOC LVL 1 = Mad<193>las<193>	251
@Z_TOC LVL 1 = Madanap<193>rij<193>ta	251
@Z_TOC LVL 1 = Madanaratna	251
@Z_TOC LVL 1 = M<193>dhav<193>c<193>rya	252
@Z_TOC LVL 1 = Madhu	252
@Z_TOC LVL 1 = madhubh<220>mika	252
@Z_TOC LVL 1 = Madhubr<193>hma<207>a	252
@Z_TOC LVL 1 = Madhucchandas	253
@Z_TOC LVL 1 = madhumat<200>	253
@Z_TOC LVL 1 = madhuparka	253
@Z_TOC LVL 1 = Madhur<193>	253
@Z_TOC LVL 1 = madhurabh<193>va	254
@Z_TOC LVL 1 = Madhurakavi °<202>v<193>r	254
@Z_TOC LVL 1 = Madhus<220>dana Sarasvat<200>	254
@Z_TOC LVL 1 = Madhuvidy<193>	255
@Z_TOC LVL 1 = Madhv<193>c<193>rya	255
@Z_TOC LVL 1 = Madhyade·a	258
@Z_TOC LVL 1 = M<193>dhyandina-·<193>kh<193>	258
@Z_TOC LVL 1 = Madurai	259
@Z_TOC LVL 1 = madyap<193>na	260
@Z_TOC LVL 1 = Mah<193>balipuram	260
@Z_TOC LVL 1 = mah<193>bh<193>gavata	260
@Z_TOC LVL 1 = Mah<193>bh<193>rata	261
@Z_TOC LVL 1 = Mah<193>bh<193><218>ya	266
@Z_TOC LVL 1 = mah<193>bh<193>va	266
@Z_TOC LVL 1 = mah<193>bhi<218>ava	266
@Z_TOC LVL 1 = mah<193>bhi<218>eka	266
@Z_TOC LVL 1 = mah<193>bh<220>tas	267
@Z_TOC LVL 1 = mah<193>d<193>na	267
@Z_TOC LVL 1 = Mah<193>deva	267
@Z_TOC LVL 1 = mah<193>havis	267
@Z_TOC LVL 1 = mah<193>janapadas	268
@Z_TOC LVL 1 = Mah<193>k<193>la	268
@Z_TOC LVL 1 = Mah<193>lak<218>m<200>	268
@Z_TOC LVL 1 = mah<193>laya	268
@Z_TOC LVL 1 = mah<193>laya·r<193>ddha	269
@Z_TOC LVL 1 = Mah<193>m<193>y<193>	269
@Z_TOC LVL 1 = mah<193>n<193>mn<200>	269
@Z_TOC LVL 1 = Mah<193>n<193>r<193>ya<207>a Upani<218>ad	269
@Z_TOC LVL 1 = Mah<193>n<193><219>aka	271
@Z_TOC LVL 1 = Mah<193>nirv<193><207>a Tantra	271
@Z_TOC LVL 1 = mah<193>p<193>takas	271
@Z_TOC LVL 1 = mah<193>pralaya	272
@Z_TOC LVL 1 = mah<193>prasth<193>na	272
@Z_TOC LVL 1 = mah<193>pur<193><207>a	272
@Z_TOC LVL 1 = mah<193>raurava	272
@Z_TOC LVL 1 = Maharloka	272
@Z_TOC LVL 1 = mahar<218>i	272
@Z_TOC LVL 1 = Mah<193>rudra	272
@Z_TOC LVL 1 = mah<193>s<193>ntapana	272
@Z_TOC LVL 1 = mah<193>·<193>nti	272
@Z_TOC LVL 1 = Mah<193>·ivar<193>trivrata	273
@Z_TOC LVL 1 = mah<193>·vet<193>	274
@Z_TOC LVL 1 = mahat	274
@Z_TOC LVL 1 = Mah<193>tala	274
@Z_TOC LVL 1 = mahatpari<207><193>ma	275
@Z_TOC LVL 1 = mah<193>v<193>kyas	275
@Z_TOC LVL 1 = Mah<193>v<193>kyopani<218>ad	275
@Z_TOC LVL 1 = mah<193>vedi	276
@Z_TOC LVL 1 = Mah<193>v<200>ra	276
@Z_TOC LVL 1 = mah<193>v<200>ra	276
@Z_TOC LVL 1 = mah<193>vrata	276
@Z_TOC LVL 1 = mah<193>yaj<210>as	277
@Z_TOC LVL 1 = mah<193>yoga	277
@Z_TOC LVL 1 = Mahendra	277
@Z_TOC LVL 1 = Mahe·vara	277
@Z_TOC LVL 1 = M<193>he·varas<220>tras	277
@Z_TOC LVL 1 = M<193>he·var<200>	278
@Z_TOC LVL 1 = Mah<200>dhara	278
@Z_TOC LVL 1 = Mahi<218><193>sura	279
@Z_TOC LVL 1 = M<193>hi<218>mat<200>	279
@Z_TOC LVL 1 = maitr<193>varu<207>a	279
@Z_TOC LVL 1 = Maitr<193>ya<207><200>ya Sa<221>hit<193>	279
@Z_TOC LVL 1 = Maitr<193>ya<207><200>ya Upani<218>ad	280
@Z_TOC LVL 1 = Maitreya	280
@Z_TOC LVL 1 = Maitrey<200>	281
@Z_TOC LVL 1 = maitr<200>	281
@Z_TOC LVL 1 = makara	281
@Z_TOC LVL 1 = Makara Sa<209>kr<193>nti	282
@Z_TOC LVL 1 = mala	282
@Z_TOC LVL 1 = malam<193>sa	283
@Z_TOC LVL 1 = mal<193>vaha	283
@Z_TOC LVL 1 = M<193><202>av<200>ya, Madanmohan	283
@Z_TOC LVL 1 = m<193><221>sabhak<218>a<207>a	283
@Z_TOC LVL 1 = m<193><221>s<193>h<193>ra	284
@Z_TOC LVL 1 = manana	284
@Z_TOC LVL 1 = manas	284
@Z_TOC LVL 1 = Manas<193>	284
@Z_TOC LVL 1 = m<193>nasa-pratyak<218>a	284
@Z_TOC LVL 1 = M<193>nas<193>ra	285
@Z_TOC LVL 1 = M<193>nasa-sarovara	285
@Z_TOC LVL 1 = m<193>nasa-sn<193>na	285
@Z_TOC LVL 1 = M<193>nasoll<193>sa	286
@Z_TOC LVL 1 = Ma<207>av<193><202>a M<193>muni	286
@Z_TOC LVL 1 = ma<207><195>ala	287
@Z_TOC LVL 1 = Ma<207><195>ala-br<193>hma<207>opani<218>ad	287
@Z_TOC LVL 1 = Ma<207><195>ana Mi·ra	289
@Z_TOC LVL 1 = ma<207><195>apa	290
@Z_TOC LVL 1 = Mandara	290
@Z_TOC LVL 1 = M<193><207><195>avya	290
@Z_TOC LVL 1 = M<193>ndh<193>t<216>	290
@Z_TOC LVL 1 = Ma<207><195>odar<200>	290
@Z_TOC LVL 1 = M<193><207><195><220>kyak<193>rik<193>	290
@Z_TOC LVL 1 = M<193><207><195><220>kya Upani<218>ad	292
@Z_TOC LVL 1 = ma<209>gala	293
@Z_TOC LVL 1 = ma<209>galas<220>tra	293
@Z_TOC LVL 1 = ma<207>i	294
@Z_TOC LVL 1 = Ma<207>ika<207><219>han	294
@Z_TOC LVL 1 = M<193><207>ikkav<193>cagar	294
@Z_TOC LVL 1 = ma<207>iprav<193><202>a	295
@Z_TOC LVL 1 = ma<207>ip<220>racakra	295
@Z_TOC LVL 1 = ma<209>kig<200>t<193>	295
@Z_TOC LVL 1 = Manmatha	296
@Z_TOC LVL 1 = manomayako·a	296
@Z_TOC LVL 1 = Manonman<200>	296
@Z_TOC LVL 1 = mantra	297
@Z_TOC LVL 1 = Mantr<193>bhidh<193>na	297
@Z_TOC LVL 1 = mantradra<218><219><193>	297
@Z_TOC LVL 1 = Mantr<193>rth<193>bhidh<193>na	297
@Z_TOC LVL 1 = Mantr<193>laya	298
@Z_TOC LVL 1 = Mantrapu<218>pa	298
@Z_TOC LVL 1 = mantrasa<221>sk<193>ra	298
@Z_TOC LVL 1 = mantrasiddhi	299
@Z_TOC LVL 1 = mantrasn<193>na	299
@Z_TOC LVL 1 = Mantrayoga	299
@Z_TOC LVL 1 = mantrin	299
@Z_TOC LVL 1 = Manu	299
@Z_TOC LVL 1 = Manus	299
@Z_TOC LVL 1 = m<193>nu<218>a-li<209>ga	299
@Z_TOC LVL 1 = Manusm<216>ti	300
@Z_TOC LVL 1 = manu<218>ya-yaj<210>a	301
@Z_TOC LVL 1 = manv<193>di-tithi	301
@Z_TOC LVL 1 = manvantara	302
@Z_TOC LVL 1 = mara<207>a	302
@Z_TOC LVL 1 = Mar<200>ci	303
@Z_TOC LVL 1 = m<193>rjana	303
@Z_TOC LVL 1 = M<193>rka<207><195>eya	304
@Z_TOC LVL 1 = M<193>rka<207><195>eyapur<193><207>a	304
@Z_TOC LVL 1 = marriage	304
@Z_TOC LVL 1 = Marudga<207>a	304
@Z_TOC LVL 1 = Maskarin	304
@Z_TOC LVL 1 = m<193>t<193>	305
@Z_TOC LVL 1 = Mata<209>ga	305
@Z_TOC LVL 1 = materialism	305
@Z_TOC LVL 1 = ma<219>ha	306
@Z_TOC LVL 1 = Mathur<193>	306
@Z_TOC LVL 1 = M<193>t<216>k<193>nigha<207><219>u	308
@Z_TOC LVL 1 = m<193>t<216>k<193>ny<193>sa	309
@Z_TOC LVL 1 = m<193>t<216>k<193>yantra	309
@Z_TOC LVL 1 = Matsyapur<193><207>a	310
@Z_TOC LVL 1 = Matsy<193>vat<193>ra	311
@Z_TOC LVL 1 = matsyayantra	311
@Z_TOC LVL 1 = Matsyendran<193>tha	311
@Z_TOC LVL 1 = maun<200>-am<193>v<193>sy<193>	312
@Z_TOC LVL 1 = Mausalaparva	312
@Z_TOC LVL 1 = Maya	312
@Z_TOC LVL 1 = m<193>y<193>	312
@Z_TOC LVL 1 = m<193>y<200>yamala	313
@Z_TOC LVL 1 = medh<193>janana	314
@Z_TOC LVL 1 = Medh<193>s<220>kta	314
@Z_TOC LVL 1 = Medh<193>tithi	314
@Z_TOC LVL 1 = meditation	315
@Z_TOC LVL 1 = Meghan<193>da	315
@Z_TOC LVL 1 = Melko<219>e	315
@Z_TOC LVL 1 = Meru	316
@Z_TOC LVL 1 = Meyka<207><195><193>r	317
@Z_TOC LVL 1 = M<200>m<193><221>s<193> Dar·ana	317
@Z_TOC LVL 1 = mind	321
@Z_TOC LVL 1 = M<200>r<193>b<193><200>	323
@Z_TOC LVL 1 = Mit<193>k<218>ar<193>	324
@Z_TOC LVL 1 = Mithil<193>	324
@Z_TOC LVL 1 = mithy<193>	324
@Z_TOC LVL 1 = Mitra, mitra	325
@Z_TOC LVL 1 = mlecchas	325
@Z_TOC LVL 1 = moha	326
@Z_TOC LVL 1 = Mohenjo D<193>ro	326
@Z_TOC LVL 1 = Mohin<200>	326
@Z_TOC LVL 1 = mok<218>a	326
@Z_TOC LVL 1 = Mok<218>adharmaparva	327
@Z_TOC LVL 1 = Monasticism	327
@Z_TOC LVL 1 = monks	330
@Z_TOC LVL 1 = moon	330
@Z_TOC LVL 1 = morality	330
@Z_TOC LVL 1 = mother	330
@Z_TOC LVL 1 = M<216>tyu	330
@Z_TOC LVL 1 = Mucukunda	330
@Z_TOC LVL 1 = Muddusv<193>mi D<200>k<218>itar	331
@Z_TOC LVL 1 = Mudgala	332
@Z_TOC LVL 1 = Mudgalapur<193><207>a	332
@Z_TOC LVL 1 = Mudgala Upani<218>ad	332
@Z_TOC LVL 1 = mudr<193>	333
@Z_TOC LVL 1 = muh<220>rta	334
@Z_TOC LVL 1 = M<220>k<193>mbik<193> Temple	334
@Z_TOC LVL 1 = mukhali<209>ga	334
@Z_TOC LVL 1 = mukhama<207><195>apa	335
@Z_TOC LVL 1 = Mukt<193>b<193><200>	335
@Z_TOC LVL 1 = muktapuru<218>a	335
@Z_TOC LVL 1 = mukti	336
@Z_TOC LVL 1 = Muktikopani<218>ad	336
@Z_TOC LVL 1 = muktiyogyas	337
@Z_TOC LVL 1 = muku<219>a	337
@Z_TOC LVL 1 = M<220>la	337
@Z_TOC LVL 1 = m<220>l<193>dh<193>ra	337
@Z_TOC LVL 1 = M<220>lar	337
@Z_TOC LVL 1 = m<220>la·odhana	338
@Z_TOC LVL 1 = M<220>laveda	338
@Z_TOC LVL 1 = m<220>l<193>vidy<193>	338
@Z_TOC LVL 1 = mumuk<218>utva	338
@Z_TOC LVL 1 = Mu<207><195>a	338
@Z_TOC LVL 1 = Mu<207><195>aka Upani<218>ad	339
@Z_TOC LVL 1 = mu<207><195>ana	341
@Z_TOC LVL 1 = muni	342
@Z_TOC LVL 1 = m<220>rdhe<218><219>ak<193>	342
@Z_TOC LVL 1 = M<220>rti·ilpa·<193>stra	342
@Z_TOC LVL 1 = M<220>rtya<218><219>aka	349
@Z_TOC LVL 1 = musala	349
@Z_TOC LVL 1 = music	349
@Z_TOC LVL 1 = Mu<218><219>ika	349
@Z_TOC LVL 1 = mysticism	349
@Z_TOC LVL 1 = mythology	349
@Z_TOC TITLE = N
@SPACE = 
@SPACE1 = 
@Z_TOC LVL 1 = N<193>bh<193>d<193>sa	350
@Z_TOC LVL 1 = N<193>bh<193>nedi<218><219>ha	350
@Z_TOC LVL 1 = N<193>bhi	351
@Z_TOC LVL 1 = N<193>ciket<193>gni	351
@Z_TOC LVL 1 = Naciketas	351
@Z_TOC LVL 1 = n<193>da	351
@Z_TOC LVL 1 = N<193>dabind<220>pani<218>ad	351
@Z_TOC LVL 1 = n<193>d<193>nusandh<193>na	352
@Z_TOC LVL 1 = nad<200>	353
@Z_TOC LVL 1 = n<193><195><200>	354
@Z_TOC LVL 1 = Nad<200>stuti	354
@Z_TOC LVL 1 = n<193><195><200>·uddhi	355
@Z_TOC LVL 1 = n<193>ga	355
@Z_TOC LVL 1 = N<193>gapa<210>cam<200>	356
@Z_TOC LVL 1 = n<193>gap<193>·a	356
@Z_TOC LVL 1 = n<193>gara	356
@Z_TOC LVL 1 = N<193>garakha<207><195>a	356
@Z_TOC LVL 1 = N<193>g<193>rjuna	356
@Z_TOC LVL 1 = N<193>gas	357
@Z_TOC LVL 1 = n<193>gav<193>yu	357
@Z_TOC LVL 1 = N<193>goji Bha<219><219>a	358
@Z_TOC LVL 1 = Nahu<218>a	358
@Z_TOC LVL 1 = Naigamas	359
@Z_TOC LVL 1 = Naimi<218><193>ra<207>ya	359
@Z_TOC LVL 1 = naimittika-karma	359
@Z_TOC LVL 1 = nair<193>tmyav<193>da	359
@Z_TOC LVL 1 = nai<218>karmya	359
@Z_TOC LVL 1 = Nai<218>karmyasiddhi	360
@Z_TOC LVL 1 = nai<218><219>hika-brahmac<193>rin	361
@Z_TOC LVL 1 = naiy<193>yika	361
@Z_TOC LVL 1 = nak<218>atra	361
@Z_TOC LVL 1 = nak<218>atrasn<193>na	362
@Z_TOC LVL 1 = nakta, naktavrata	362
@Z_TOC LVL 1 = Nakula	362
@Z_TOC LVL 1 = Nakul<200>·a	362
@Z_TOC LVL 1 = Nala	362
@Z_TOC LVL 1 = N<193>land<193>	363
@Z_TOC LVL 1 = N<193>l<193>yira Prabandham	365
@Z_TOC LVL 1 = n<193>makara<207>a	365
@Z_TOC LVL 1 = namask<193>ra	366
@Z_TOC LVL 1 = namb<220>diri	367
@Z_TOC LVL 1 = N<193>mdev	367
@Z_TOC LVL 1 = Namm<193><202>v<193>r	369
@Z_TOC LVL 1 = N<193>nak, Guru	369
@Z_TOC LVL 1 = Nanda	370
@Z_TOC LVL 1 = Nandaka	371
@Z_TOC LVL 1 = Nandana	371
@Z_TOC LVL 1 = Nandan<193>r	371
@Z_TOC LVL 1 = Nandapa<207><195>ita	371
@Z_TOC LVL 1 = Nandi	372
@Z_TOC LVL 1 = n<193>nd<200>mukha·r<193>ddha, n<193>nd<200>·r<193>ddha	372
@Z_TOC LVL 1 = Nandipur<193><207>a	373
@Z_TOC LVL 1 = Nandotsava	373
@Z_TOC LVL 1 = nara, Nara	373
@Z_TOC LVL 1 = narabali	373
@Z_TOC LVL 1 = N<193>rada	374
@Z_TOC LVL 1 = N<193>rada Bhaktis<220>tras	374
@Z_TOC LVL 1 = N<193>rada-parivr<193>jaka-Upani<218>ad	383
@Z_TOC LVL 1 = N<193>radasm<216>ti	388
@Z_TOC LVL 1 = N<193>rad<200>ya-pur<193><207>a	389
@Z_TOC LVL 1 = Narahari T<200>rtha	389
@Z_TOC LVL 1 = naraka	390
@Z_TOC LVL 1 = Narak<193>sura	391
@Z_TOC LVL 1 = Nara-N<193>r<193>ya<207>a	391
@Z_TOC LVL 1 = n<193>r<193>·a<221>·<200>g<193>th<193>	392
@Z_TOC LVL 1 = Narasi<221>ha	392
@Z_TOC LVL 1 = Narasi<221>hapur<193><207>a	392
@Z_TOC LVL 1 = N<193>r<193>ya<207>a	393
@Z_TOC LVL 1 = n<193>r<193>ya<207>abali	393
@Z_TOC LVL 1 = N<193>r<193>ya<207>a Bha<219><219><193>tiri	393
@Z_TOC LVL 1 = N<193>r<193>ya<207>a Guru	394
@Z_TOC LVL 1 = N<193>r<193>ya<207>as<220>kta	395
@Z_TOC LVL 1 = N<193>r<193>ya<207>a Upani<218>ad	396
@Z_TOC LVL 1 = N<193>r<193>ya<207><200>	397
@Z_TOC LVL 1 = N<193>r<193>ya<207><200>ya	398
@Z_TOC LVL 1 = Narmad<193>	400
@Z_TOC LVL 1 = Nars<200> Meht<193>	401
@Z_TOC LVL 1 = N<193>sad<200>yas<220>kta	402
@Z_TOC LVL 1 = N<193>sik	404
@Z_TOC LVL 1 = n<193>stika	405
@Z_TOC LVL 1 = N<193>stika Dar·anas	405
@Z_TOC LVL 1 = Na<219>ar<193>ja	405
@Z_TOC LVL 1 = N<193>tha Cult	406
@Z_TOC LVL 1 = N<193>thamuni	407
@Z_TOC LVL 1 = N<193><219>ya·<193>stra	407
@Z_TOC LVL 1 = nauli	408
@Z_TOC LVL 1 = Navadurg<193>s	408
@Z_TOC LVL 1 = Navadv<200>pa	408
@Z_TOC LVL 1 = Navagrahamakha	408
@Z_TOC LVL 1 = Navagrahas	408
@Z_TOC LVL 1 = Navagraha·<193>ntis	410
@Z_TOC LVL 1 = Navagva	410
@Z_TOC LVL 1 = nav<193>nna	411
@Z_TOC LVL 1 = Navar<193>tra	411
@Z_TOC LVL 1 = navat<193>la	412
@Z_TOC LVL 1 = Navyany<193>ya	412
@Z_TOC LVL 1 = N<193>yan<193>rs	412
@Z_TOC LVL 1 = Neo-Ved<193>nta	413
@Z_TOC LVL 1 = neti	413
@Z_TOC LVL 1 = netronm<200>lana	413
@Z_TOC LVL 1 = nibandhas	413
@Z_TOC LVL 1 = nidhana	413
@Z_TOC LVL 1 = nidhikumbha	413
@Z_TOC LVL 1 = nididhy<193>sana	414
@Z_TOC LVL 1 = Nidr<193>, nidr<193>	414
@Z_TOC LVL 1 = nigada	414
@Z_TOC LVL 1 = nigama	415
@Z_TOC LVL 1 = nigamana	415
@Z_TOC LVL 1 = Nigam<193>nta De·ika	415
@Z_TOC LVL 1 = Nigha<207><219>u	415
@Z_TOC LVL 1 = nigrahasth<193>na	416
@Z_TOC LVL 1 = N<200>laka<207><219>ha	416
@Z_TOC LVL 1 = N<200>laka<207><219>ha Bha<219><219>a	417
@Z_TOC LVL 1 = N<200>laka<207><219>ha Caturdhara	417
@Z_TOC LVL 1 = N<200>laka<207><219>ha D<200>k<218>ita	417
@Z_TOC LVL 1 = N<200>l<193>k<218>a-nakula	417
@Z_TOC LVL 1 = N<200>lapur<193><207>a	417
@Z_TOC LVL 1 = N<200><202><193>s<220>kta	418
@Z_TOC LVL 1 = nimantra<207>a	418
@Z_TOC LVL 1 = Nimb<193>rka	418
@Z_TOC LVL 1 = nimitta	419
@Z_TOC LVL 1 = nimittak<193>ra<207>a	419
@Z_TOC LVL 1 = n<200>r<193>jana	419
@Z_TOC LVL 1 = nirayana	419
@Z_TOC LVL 1 = nirb<200>jasam<193>dhi	420
@Z_TOC LVL 1 = nirgarbha	420
@Z_TOC LVL 1 = Nir<200>·vara-s<193><209>khya	420
@Z_TOC LVL 1 = nirm<193><207>acitta	421
@Z_TOC LVL 1 = Nir<207>ayas<193>gara Press	421
@Z_TOC LVL 1 = Nir<207>ayasindhu	421
@Z_TOC LVL 1 = nirodha-sam<193>dhi	422
@Z_TOC LVL 1 = Nir<216>ti	422
@Z_TOC LVL 1 = Nir<220><195>hapa·ubandha	422
@Z_TOC LVL 1 = Nirukta	422
@Z_TOC LVL 1 = nirup<193>dhika	423
@Z_TOC LVL 1 = nirv<193><207>a	424
@Z_TOC LVL 1 = nirvic<193>rasam<193>patti	424
@Z_TOC LVL 1 = nirvikalpaka	424
@Z_TOC LVL 1 = nirvikalpa-sam<193>dhi	424
@Z_TOC LVL 1 = nirvi·e<218>a	424
@Z_TOC LVL 1 = nirvitarkasam<193>patti	425
@Z_TOC LVL 1 = ni<218><193>da	425
@Z_TOC LVL 1 = ni<218><193>dasthapati	425
@Z_TOC LVL 1 = ni<218>edha	425
@Z_TOC LVL 1 = ni<218>eka	426
@Z_TOC LVL 1 = ni<218>iddhakarma	426
@Z_TOC LVL 1 = ni<218>ka	426
@Z_TOC LVL 1 = ni<218>k<193>makarma	426
@Z_TOC LVL 1 = ni<218>krama<207>a	426
@Z_TOC LVL 1 = ni<218>patti-avasth<193>	426
@Z_TOC LVL 1 = ni··reyas	427
@Z_TOC LVL 1 = n<200>ti	427
@Z_TOC LVL 1 = N<200>tis<193>ra	427
@Z_TOC LVL 1 = N<200>ti·<193>stra	427
@Z_TOC LVL 1 = nitya	427
@Z_TOC LVL 1 = nityakarma	428
@Z_TOC LVL 1 = nityal<200>l<193>	428
@Z_TOC LVL 1 = nityamukta	428
@Z_TOC LVL 1 = nity<193>nuv<193>da	428
@Z_TOC LVL 1 = nityasa<221>s<193>ri	428
@Z_TOC LVL 1 = Nivedit<193>, Sister	429
@Z_TOC LVL 1 = nivid	432
@Z_TOC LVL 1 = niv<200>ta	432
@Z_TOC LVL 1 = niv<216>tti	432
@Z_TOC LVL 1 = niv<216>ttim<193>rga	432
@Z_TOC LVL 1 = Niv<216>ttin<193>th	432
@Z_TOC LVL 1 = niyama	433
@Z_TOC LVL 1 = niyamavidhi	433
@Z_TOC LVL 1 = niyoga	434
@Z_TOC LVL 1 = N<216>ga	434
@Z_TOC LVL 1 = N<216>si<221>ha-t<193>pin<200> Upani<218>ad	434
@Z_TOC LVL 1 = n<216>ttam<220>rti	436
@Z_TOC LVL 1 = ny<193>sa	437
@Z_TOC LVL 1 = ny<193>ya	437
@Z_TOC LVL 1 = Ny<193>ya Dar·ana	437
@Z_TOC LVL 1 = Ny<193>yakusum<193><210>jali	442
@Z_TOC LVL 1 = Ny<193>y<193>m<216>ta	442
@Z_TOC LVL 1 = Ny<193>yapari·uddhi	443
@Z_TOC LVL 1 = ny<193>yas	444
@Z_TOC LVL 1 = Ny<193>yasudh<193>	447
@Z_TOC LVL 1 = Ny<193>yas<220>tras	447
@Z_TOC TITLE = O
@Z_TOC LVL 1 = Oghavat<200>	448
@Z_TOC LVL 1 = O<207>am	448
@Z_TOC LVL 1 = O<209>k<193>ra	448
@Z_TOC LVL 1 = O<209>k<193>re·vara	448
@Z_TOC LVL 1 = Oriental<|>Research<|>Institutes<|>of<|>India	449
@Z_TOC TITLE = P
@Z_TOC LVL 1 = p<193>dak<216>cchra	460
@Z_TOC LVL 1 = padap<193><219>ha	460
@Z_TOC LVL 1 = pad<193>rtha	460
@Z_TOC LVL 1 = padma	460
@Z_TOC LVL 1 = Padman<193>bha Temple	460
@Z_TOC LVL 1 = Padmap<193>da	462
@Z_TOC LVL 1 = padmap<200><219>ha	463
@Z_TOC LVL 1 = Padmapur<193><207>a	463
@Z_TOC LVL 1 = padm<193>sana	465
@Z_TOC LVL 1 = Padm<193>vat<200>	465
@Z_TOC LVL 1 = Paila	465
@Z_TOC LVL 1 = pai·<193>caviv<193>ha	466
@Z_TOC LVL 1 = Pai<219>h<200>nasi	466
@Z_TOC LVL 1 = pait<216>ka-mantras	466
@Z_TOC LVL 1 = p<193>kayaj<210>a	467
@Z_TOC LVL 1 = pak<218>a	467
@Z_TOC LVL 1 = pal<193>·av<216>k<218>a	467
@Z_TOC LVL 1 = P<193>l<200>	467
@Z_TOC LVL 1 = Pallavas	467
@Z_TOC LVL 1 = palmistry	468
@Z_TOC LVL 1 = Pamp<193>	468
@Z_TOC LVL 1 = Pa<210>cab<193><207>a	468
@Z_TOC LVL 1 = pa<210>cabhedas	468
@Z_TOC LVL 1 = Pa<210>cabh<220>tali<209>gas	468
@Z_TOC LVL 1 = pa<210>cabh<220>tas	469
@Z_TOC LVL 1 = Pa<210>cabrahmamantras	469
@Z_TOC LVL 1 = pa<210>c<193>c<193>ras	469
@Z_TOC LVL 1 = pa<210>cada·<193>k<218>ar<200>-mantra	469
@Z_TOC LVL 1 = Pa<210>cada·<200>	469
@Z_TOC LVL 1 = pa<210>cagavya	472
@Z_TOC LVL 1 = pa<210>c<193>gnis	472
@Z_TOC LVL 1 = Pa<210>c<193>gnividy<193>	472
@Z_TOC LVL 1 = pa<210>cajana	472
@Z_TOC LVL 1 = P<193><210>cajanya	473
@Z_TOC LVL 1 = Pa<210>cako·as	473
@Z_TOC LVL 1 = pa<210>c<193>k<218>ar<200>	474
@Z_TOC LVL 1 = pa<210>camah<193>yaj<210>as	474
@Z_TOC LVL 1 = pa<210>camak<193>ras	475
@Z_TOC LVL 1 = pa<210>camas	475
@Z_TOC LVL 1 = Pa<210>canada	475
@Z_TOC LVL 1 = Pa<210>c<193>nana	475
@Z_TOC LVL 1 = pa<210>c<193><209>ga	476
@Z_TOC LVL 1 = pa<210>c<193><209>ga·uddhi	479
@Z_TOC LVL 1 = pa<210>capr<193><207>as	479
@Z_TOC LVL 1 = P<193><210>car<193>tra °gamas	479
@Z_TOC LVL 1 = pa<210>casa<221>sk<193>ras	484
@Z_TOC LVL 1 = Pa<210>ca·ikha	485
@Z_TOC LVL 1 = pa<210>cat<193>la	485
@Z_TOC LVL 1 = Pa<210>catantra	485
@Z_TOC LVL 1 = pa<210>catapas	486
@Z_TOC LVL 1 = pa<210>catattvas	486
@Z_TOC LVL 1 = Pa<210>cava<219><200>	486
@Z_TOC LVL 1 = Pa<210>cavi<221>·a Br<193>hma<207>a	487
@Z_TOC LVL 1 = pa<210>cayaj<210>as	487
@Z_TOC LVL 1 = pa<210>c<193>yatanap<220>j<193>	487
@Z_TOC LVL 1 = pa<210>c<200>kara<207>a	488
@Z_TOC LVL 1 = pa<210>copac<193>ras	488
@Z_TOC LVL 1 = pa<210>cop<193>sakas	489
@Z_TOC LVL 1 = P<193><207><195>avag<200>t<193>	489
@Z_TOC LVL 1 = P<193><207><195>av<193>s	489
@Z_TOC LVL 1 = Pa<207><195>harpur	489
@Z_TOC LVL 1 = P<193><207><195>u	491
@Z_TOC LVL 1 = P<193><207><195>ura<209>ga	491
@Z_TOC LVL 1 = p<193><207>igraha<207>a	491
@Z_TOC LVL 1 = P<193><207>ini	491
@Z_TOC LVL 1 = P<193><207>in<200>ya <185>ik<218><193>	492
@Z_TOC LVL 1 = pa<209>ktip<193>vanas	492
@Z_TOC LVL 1 = p<193>pa	492
@Z_TOC LVL 1 = para, par<193>	492
@Z_TOC LVL 1 = Parabrahman	493
@Z_TOC LVL 1 = Parak<193>la Ma<219>ha	493
@Z_TOC LVL 1 = parak<193>yaprave·a	493
@Z_TOC LVL 1 = paramaha<221>sa	494
@Z_TOC LVL 1 = param<193><207>u	494
@Z_TOC LVL 1 = paramapuru<218><193>rtha	494
@Z_TOC LVL 1 = p<193>ram<193>rthika	495
@Z_TOC LVL 1 = Param<193>tman	495
@Z_TOC LVL 1 = Parame·vara	495
@Z_TOC LVL 1 = P<193>r<193>nanda S<220>tras	495
@Z_TOC LVL 1 = par<193>prak<216>ti	496
@Z_TOC LVL 1 = Par<193>·akti	496
@Z_TOC LVL 1 = Par<193>·ara	497
@Z_TOC LVL 1 = Par<193>·arabha<219><219>a	497
@Z_TOC LVL 1 = Par<193>·arag<200>t<193>	498
@Z_TOC LVL 1 = Par<193>·ara Sm<216>ti	499
@Z_TOC LVL 1 = P<193>raskara G<216>hyas<220>tras	500
@Z_TOC LVL 1 = para·u	500
@Z_TOC LVL 1 = Para·ur<193>ma	501
@Z_TOC LVL 1 = par<193>vartana	502
@Z_TOC LVL 1 = par<193>-vidy<193>	503
@Z_TOC LVL 1 = P<193>rij<193>ta	503
@Z_TOC LVL 1 = parikarma	503
@Z_TOC LVL 1 = Par<200>k<218>it	504
@Z_TOC LVL 1 = pari<207><193>ma	504
@Z_TOC LVL 1 = pari<207><193>mav<193>da	505
@Z_TOC LVL 1 = pari<207><193>minitya	505
@Z_TOC LVL 1 = p<193>riplava	505
@Z_TOC LVL 1 = pari<218>ad	506
@Z_TOC LVL 1 = parisa<209>khy<193>vidhi	506
@Z_TOC LVL 1 = pari·i<218><219>a	507
@Z_TOC LVL 1 = pariv<193>radevat<193>s	507
@Z_TOC LVL 1 = parivedana	508
@Z_TOC LVL 1 = parivr<193>jaka	508
@Z_TOC LVL 1 = par<207>ak<220>rca	508
@Z_TOC LVL 1 = parok<218>a	509
@Z_TOC LVL 1 = P<193>r·van<193>tha	509
@Z_TOC LVL 1 = partition	509
@Z_TOC LVL 1 = P<193>rva<207>a·r<193>ddha	510
@Z_TOC LVL 1 = p<193>rva<207>asth<193>l<200>p<193>ka	510
@Z_TOC LVL 1 = P<193>rvat<200>	510
@Z_TOC LVL 1 = paryagnikara<207>a	511
@Z_TOC LVL 1 = parya<209>ka·auca	512
@Z_TOC LVL 1 = Pary<193>yamahotsava	512
@Z_TOC LVL 1 = p<193>·a	512
@Z_TOC LVL 1 = p<193><218>a<207><195>in	512
@Z_TOC LVL 1 = pa·c<193>t-t<193>pa	513
@Z_TOC LVL 1 = pa·u	513
@Z_TOC LVL 1 = Pa·ubandha	513
@Z_TOC LVL 1 = P<193>·upata	513
@Z_TOC LVL 1 = P<193>·upata Dar·ana	513
@Z_TOC LVL 1 = P<193>·upatas<220>tras	513
@Z_TOC LVL 1 = Pa·upati	513
@Z_TOC LVL 1 = Pa·upatin<193>tha Temple	514
@Z_TOC LVL 1 = pa·uvadha	514
@Z_TOC LVL 1 = pa·yant<200>	514
@Z_TOC LVL 1 = p<193>taka	514
@Z_TOC LVL 1 = P<193>t<193>la	516
@Z_TOC LVL 1 = P<193><219>aliputra	517
@Z_TOC LVL 1 = Pata<210>jali	517
@Z_TOC LVL 1 = patitas<193>vitr<200>ka	518
@Z_TOC LVL 1 = pativrat<193>	518
@Z_TOC LVL 1 = patn<200>·<193>l<193>	519
@Z_TOC LVL 1 = Pa<219><219>adakal	519
@Z_TOC LVL 1 = pa<219><219>in<200> cult	520
@Z_TOC LVL 1 = paur<207>am<193>s<200>-vratas	520
@Z_TOC LVL 1 = Pau<218>kar<193>gama	521
@Z_TOC LVL 1 = Pavah<193>r<200> B<193>b<193>	522
@Z_TOC LVL 1 = Pavam<193>nas<220>kta	522
@Z_TOC LVL 1 = pavitra	522
@Z_TOC LVL 1 = Pavitr<193>ropa<207>a-vrata	523
@Z_TOC LVL 1 = Periy<193><202>v<193>r	523
@Z_TOC LVL 1 = Periyapur<193><207>am	523
@Z_TOC LVL 1 = pilgrimage	523
@Z_TOC LVL 1 = Pi<202><202>ai Lok<193>c<193>rya	523
@Z_TOC LVL 1 = Pin<193>ka	523
@Z_TOC LVL 1 = pi<207><195>a	524
@Z_TOC LVL 1 = Pi<207><195>apit<216>yaj<210>a	524
@Z_TOC LVL 1 = pi<209>gal<193>	524
@Z_TOC LVL 1 = Pi<209>gal<193>mata	524
@Z_TOC LVL 1 = pip<200>lik<193>madhya	524
@Z_TOC LVL 1 = Pippal<193>da	524
@Z_TOC LVL 1 = pi·<193>ca	525
@Z_TOC LVL 1 = pit<193>	525
@Z_TOC LVL 1 = p<200><219>ha	525
@Z_TOC LVL 1 = Pit<216>g<193>th<193>	526
@Z_TOC LVL 1 = pit<216>loka	526
@Z_TOC LVL 1 = pit<216>medha	527
@Z_TOC LVL 1 = pit<216>pak<218>a	527
@Z_TOC LVL 1 = pit<216>-<216><207>a	527
@Z_TOC LVL 1 = pit<216>s	528
@Z_TOC LVL 1 = pit<216>yaj<210>a	528
@Z_TOC LVL 1 = Pit<216>y<193>na	528
@Z_TOC LVL 1 = planets	528
@Z_TOC LVL 1 = pl<193>vin<200>	528
@Z_TOC LVL 1 = polyandry	529
@Z_TOC LVL 1 = polygamy	529
@Z_TOC LVL 1 = Po<209>gal	529
@Z_TOC LVL 1 = Prabandham	529
@Z_TOC LVL 1 = Prabodhacandrodaya	529
@Z_TOC LVL 1 = Prabh<193>kara	529
@Z_TOC LVL 1 = prabh<193>ma<207><195>ala	529
@Z_TOC LVL 1 = Prabh<193>sa	530
@Z_TOC LVL 1 = pr<193>c<200>n<193>v<200>ta	530
@Z_TOC LVL 1 = pradak<218>i<207>a	530
@Z_TOC LVL 1 = Pr<193>de·am<193>tra	530
@Z_TOC LVL 1 = pradh<193>na	531
@Z_TOC LVL 1 = pradhva<221>s<193>bh<193>va	531
@Z_TOC LVL 1 = prado<218>a	531
@Z_TOC LVL 1 = Pradyumna	531
@Z_TOC LVL 1 = pr<193>gabh<193>va	531
@Z_TOC LVL 1 = Prahl<193>da	531
@Z_TOC LVL 1 = Praj<193>pati	532
@Z_TOC LVL 1 = Praj<193>pati Sm<216>ti	532
@Z_TOC LVL 1 = pr<193>j<193>patya	532
@Z_TOC LVL 1 = pr<193>j<210>a	533
@Z_TOC LVL 1 = praj<210><193>jyoti	533
@Z_TOC LVL 1 = prak<193>ra	533
@Z_TOC LVL 1 = pr<193>k<193>ra	533
@Z_TOC LVL 1 = Prak<193>·<193>nanda Yati	534
@Z_TOC LVL 1 = Prak<193>·<193>tman	534
@Z_TOC LVL 1 = Pr<193>k<216>t	534
@Z_TOC LVL 1 = prak<216>ti	534
@Z_TOC LVL 1 = pr<193>k<216>tika-pralaya	535
@Z_TOC LVL 1 = prak<216>tilaya	535
@Z_TOC LVL 1 = pralaya	535
@Z_TOC LVL 1 = pram<193>	536
@Z_TOC LVL 1 = pram<193>da	536
@Z_TOC LVL 1 = pram<193><207>as	536
@Z_TOC LVL 1 = pramathaga<207>a	538
@Z_TOC LVL 1 = pr<193><207>a	538
@Z_TOC LVL 1 = pr<193><207><193>gnihotra	539
@Z_TOC LVL 1 = pr<193><207>ali<209>ga	539
@Z_TOC LVL 1 = pr<193><207>amayako·a	539
@Z_TOC LVL 1 = pr<193><207>aprati<218><219>h<193>	539
@Z_TOC LVL 1 = Pra<207>ava	539
@Z_TOC LVL 1 = pra<207>avatanu	541
@Z_TOC LVL 1 = Pr<193><207>avidy<193>	541
@Z_TOC LVL 1 = pr<193><207><193>y<193>ma	541
@Z_TOC LVL 1 = pra<207><200>t<193>	542
@Z_TOC LVL 1 = Prapa<210>cas<193>ra	542
@Z_TOC LVL 1 = Prapannag<200>t<193>	549
@Z_TOC LVL 1 = prapatti	550
@Z_TOC LVL 1 = pr<193>rabdhakarma	551
@Z_TOC LVL 1 = Pr<193>rthan<193> Sam<193>j	551
@Z_TOC LVL 1 = Pra·astap<193>da	552
@Z_TOC LVL 1 = Pra·na Upani<218>ad	552
@Z_TOC LVL 1 = prastara	555
@Z_TOC LVL 1 = prast<193>va	555
@Z_TOC LVL 1 = prasth<193>natraya	555
@Z_TOC LVL 1 = prastot<216>	556
@Z_TOC LVL 1 = pra·v<193>sa	556
@Z_TOC LVL 1 = Prat<193>parudra Deva	556
@Z_TOC LVL 1 = pr<193>taranuv<193>ka	556
@Z_TOC LVL 1 = Pratardana	557
@Z_TOC LVL 1 = pr<193>tas-savana	557
@Z_TOC LVL 1 = prathamakalpika	557
@Z_TOC LVL 1 = pratibandhikalpan<193>	557
@Z_TOC LVL 1 = pr<193>tibha	557
@Z_TOC LVL 1 = pr<193>tibh<193>sika	558
@Z_TOC LVL 1 = pratibimbav<193>da	558
@Z_TOC LVL 1 = pratigara	558
@Z_TOC LVL 1 = pratih<193>ra, pratihart<216>	558
@Z_TOC LVL 1 = pratij<210><193>	558
@Z_TOC LVL 1 = prat<200>kop<193>san<193>	558
@Z_TOC LVL 1 = pratiloma	559
@Z_TOC LVL 1 = pratim<193>	559
@Z_TOC LVL 1 = pratinidhi	559
@Z_TOC LVL 1 = pratipattikarma	559
@Z_TOC LVL 1 = Pr<193>ti·<193>khya	560
@Z_TOC LVL 1 = prati<218>edha	561
@Z_TOC LVL 1 = prati<218><219>h<193>pana	561
@Z_TOC LVL 1 = pratiyogi	561
@Z_TOC LVL 1 = pratyabhij<210><193>	561
@Z_TOC LVL 1 = Pratyabhij<210><193>dar·ana	562
@Z_TOC LVL 1 = pratyabhiv<193>da	562
@Z_TOC LVL 1 = pratyag<193>tman	562
@Z_TOC LVL 1 = praty<193>h<193>ra	562
@Z_TOC LVL 1 = pratyak<218>a	562
@Z_TOC LVL 1 = praty<193>mn<193>ya	562
@Z_TOC LVL 1 = pratyavaroha<207>a	563
@Z_TOC LVL 1 = pratyutth<193>na	563
@Z_TOC LVL 1 = Prav<193>ha<207>a Jaivali	563
@Z_TOC LVL 1 = pravara	563
@Z_TOC LVL 1 = Pravargya	563
@Z_TOC LVL 1 = Pray<193>ga	564
@Z_TOC LVL 1 = pray<193>ja	565
@Z_TOC LVL 1 = Pr<193>ya<207><200>y<193>	565
@Z_TOC LVL 1 = pr<193>ya·citta	565
@Z_TOC LVL 1 = preta	565
@Z_TOC LVL 1 = pretyabh<193>va	565
@Z_TOC LVL 1 = preyas	565
@Z_TOC LVL 1 = p<216><218>ad<193>jya	566
@Z_TOC LVL 1 = P<216>thu	566
@Z_TOC LVL 1 = p<216>thv<200>	566
@Z_TOC LVL 1 = p<220>j<193>	567
@Z_TOC LVL 1 = p<220>j<193>bh<193>ga	567
@Z_TOC LVL 1 = Pulastya	567
@Z_TOC LVL 1 = pu<221>savana	568
@Z_TOC LVL 1 = punar<193>dheya	568
@Z_TOC LVL 1 = punarbh<220>	569
@Z_TOC LVL 1 = punarjanma	569
@Z_TOC LVL 1 = Punarvasu	569
@Z_TOC LVL 1 = pu<207><195>ra	569
@Z_TOC LVL 1 = pu<207>ya	569
@Z_TOC LVL 1 = pu<207>y<193>hav<193>cana	570
@Z_TOC LVL 1 = p<220>raka	570
@Z_TOC LVL 1 = Pur<193><207>as	570
@Z_TOC LVL 1 = Pur<193><207>asa<221>hit<193>	585
@Z_TOC LVL 1 = Purandarad<193>sa	585
@Z_TOC LVL 1 = pura·cara<207>a	586
@Z_TOC LVL 1 = Pur<200>	586
@Z_TOC LVL 1 = p<220>r<207><193>huti	587
@Z_TOC LVL 1 = p<220>r<207>akumbha	587
@Z_TOC LVL 1 = p<220>r<207>ap<193>tra	587
@Z_TOC LVL 1 = P<220>r<207>apraj<210>a	587
@Z_TOC LVL 1 = p<220>r<207><193>vat<193>ra	587
@Z_TOC LVL 1 = puro<195><193>·a	588
@Z_TOC LVL 1 = purohita	588
@Z_TOC LVL 1 = puronuv<193>ky<193>	588
@Z_TOC LVL 1 = p<220>rta	588
@Z_TOC LVL 1 = P<220>ru	589
@Z_TOC LVL 1 = Purukutsa	589
@Z_TOC LVL 1 = Pur<220>ravas	589
@Z_TOC LVL 1 = puru<218>a	589
@Z_TOC LVL 1 = Puru<218>amedha	590
@Z_TOC LVL 1 = puru<218><193>rthas	590
@Z_TOC LVL 1 = Puru<218>as<220>kta	591
@Z_TOC LVL 1 = Puru<218>avidy<193>	603
@Z_TOC LVL 1 = Puru<218>ottama	603
@Z_TOC LVL 1 = puru<218>ottamam<193>sa	603
@Z_TOC LVL 1 = Puru<218>ottamat<200>rtha	603
@Z_TOC LVL 1 = P<220>rvam<200>m<193><221>s<193>	603
@Z_TOC LVL 1 = p<220>rvapak<218>a	603
@Z_TOC LVL 1 = p<220>rvavat	604
@Z_TOC LVL 1 = purya<218><219>aka	604
@Z_TOC LVL 1 = P<220><218>an	604
@Z_TOC LVL 1 = Pu<218>kara	604
@Z_TOC LVL 1 = Pu<218>paka	605
@Z_TOC LVL 1 = pustaka	606
@Z_TOC LVL 1 = pu<218><219>im<193>rg<193>	606
@Z_TOC LVL 1 = Pu<218>ya	607
@Z_TOC LVL 1 = pu<218>yasn<193>na	607
@Z_TOC LVL 1 = putra	608
@Z_TOC LVL 1 = Putrak<193>me<218><219>i	608
@Z_TOC LVL 1 = putrik<193>	608
@Z_TOC LVL 1 = 
@Z_TOC LVL 1 = P<MS>HOTO<D> S<MS>ECTION<D>	609
@END = 
@H = <R>ç
<R>ç
<R>ç
<R>ç
<R>ç
<R>ç
Blank
