@HALF = A C<MS>ONCISE<D><R>ç
E<MS>NCYCLOPAEDIA<D> <MS>OF<D><R>ç
HINDUISM
@HALF-1 = V<MS>OLUME<D> 2<R>ç
<%10>H<%0><196><|>P
@BLANK = <P12W1>Blank<P255D>
@T1 = A
@T1 = Concise Encyclopaedia
@T1 = of
@T1-1 = HINDUISM
@T2 = Volume 2
@T3 = H<|><%-4><196><%-24> <%0>P
@T4 = Swami Harshananda
@T5 = Ramakrishna Math<R>ç
<P12.5B>Bangalore<|>-<|>560<|>019<P255D>
@IMP = A C<P8W1>ONCISE<P255D> E<P8W1>NCYCLOPAEDIA<P255D> <P8W1>OF<P255D> ç
H<P8W1>INDUISM<P255D> (in Three Volumes)<197>Volume 2<R>ç
Written and Published by<R>ç
Swami Harshananda, President, Ramakrishna Math<R>ç
Bull Temple Road, Bangalore-56<%16>0<%0>019. Karnataka<|><196><|>India.<R>ç
Phone and e-mails<|>:<R>ç
	Office	:	91-80-2661<|>3149, 2667<|>1010<R>ç
			office@rkmathbangalore.org<R>ç
	Bookstall	:	91-80-2661<|>6161, 2661<|>6060<R>ç
			bookstall@rkmathbangalore.org<R>ç
<R>ç
Pages: xxxii + 608 + Photos
@IMP1 = <189> R<MS>AMAKRISHNA<D> M<MS>ATH<D><R>ç
Bangalore 56<W1%16>0<D%0>019
@IMP2 = All rights reserved. No part of this book may be reproduced ç
or utilized in any form or by any means, electronic or mechanical, ç
including photocopying, recording, or by any information storage and ç
retrieval system without the permission in writing from the publisher.
@IMP = First Edition<|>:	April 2008; Copies 8M<R>ç
Second Edition<|>: November 2008; Copies 1M<R>ç
Third Edition<|>:	July 2012; Copies 1M
@IMP = ISBN-13<R>ç
978-81-7907-057-4 (Set of Three Volumes)
@IMP = Price<|>: Per Set of Three Volumes<|>:	Rs. 2,000/-
@IMP = Printed by<R>ç
B. N. Nataraj<R>ç
Sri Nithyananda Printers<R>ç
# 46, 4th Cross, Ashoknagar<R>ç
BSK 1st Stage, Bangalore-560<|>050<R>ç
Karnataka<|><196><|>India.<R>ç
Phone: 91-80-2242<|>6027
@H = Preface
@PREF = Hinduism is a great religion. The traditionalists however ç
prefer to call it `San<193>tana Dharma'. Perhaps, this is a far better ç
term that reflects its true meaning and significance. The word dharma ç
is generally used to denote religion, the path to perfection or beatitude. ç
`San<193>tana' means `ancient' as also `eternal'. Hence the expression ç
means `the religion or thepath of spiritual discipline that is not ç
only ancient but also eternal'. In other words, Hinduism has been ç
offering an unbroken continuous tradition of spiritual discipline ç
which is not only very ancient but also relevant even to the modern ç
times. The beauty of this tradition is that it proffers several alternatives ç
that can suit different types of s<193>dhakas (aspirants) instead ç
of prescribing the same cap for every head. Thus, starting from the ç
aspirant at the highest rung of the spiritual ladder who is fit to ç
meditate on the non-dual Brahman (the Absolute), right up to the tyro ç
worshipping the images, everyone has a place specially carved out ç
for him.
@PREF = Of late, study of Hinduism is drawing the attention of scholars ç
both from India and from other countries. However, books on general ç
Hinduism covering all aspects are not many. Even the few that are ç
available deal with subjects like the Upani<218>ads, the Bhagavadg<200>t<193>, ç
Ved<193>nta systems and Yoga philosophy in greater detail ignoring ç
other aspects relevant to popular Hinduism.
@PREF = Hence there is a great need for an exhaustive omnibus type ç
of work.
@PREF = There were two choices before me:
@NPREF = 1.
@NKPREF = To prepare a comprehensive work with several chapters touching ç
on all aspects of Hinduism.
@NPREF = 2.
@NKPREF = To work on a regular encyclopaedia of Hinduism, arranging ç
the various subjects in the English alphabetical order.
@PREF = After weighing the pros and cons, I decided in favour of the ç
latter since it would be much easier for the average reader to locate ç
the subject he wants to know.
@PREF = This is now in your hands.
@PREF = The entries have been arranged in the English alphabetical ç
order.Since most of the subject headings are in Sanskrit, standard ç
diacritical marks as approved by the International Alphabet of Sanskrit ç
Transliteration and based on a standard established by the Congress ç
of Orientalists at Athens in <MS>A.<|>D.<D> 1912 have been adopted. ç
However, while arranging the titles in the alphabetical order, the ç
diacritical marks have been ignored to facilitate easy recognition.
@PREF = As for the subject content, the following are the main topics ç
dealt with in greater detail: religion, philosophy, mythology, rituals, ç
scriptural works, festivals and pilgrim centres.
@PREF = Other topics described include astrology, biographies of religious ç
personalities, iconography, Sanskrit language and literature, temples ç
and religious institutions.
@PREF = Care has been taken to deal with the four Vedas, their subsidiary ç
works and allied literature. Several important Vedic S<220>ktas, y<193>gas ç
or sacrifices as also unfamiliar concepts and terms have also been ç
described.
@PREF = Along with the major Upani<218>ads and the Mah<193>pur<193><207>as, ç
several minor Upani<218>ads and the upapur<193><207>as too have been ç
dealt with.
@PREF = While the essay on the R<193>m<193>ya<207>a is fairly exhaustive, ç
the one on the Mah<193>bh<193>rata is more condensed because of ç
its immense size. However, the various topics dealt with in it like ç
dharma or the minor G<200>t<193>s or the Yak<218>apra·na do find ç
a place as independent articles.
@PREF = Since most of the <193>gamas and tantras are still in the ç
manuscript form, justice could not be done to this subject area. Only ç
a few major ones, more well-known, have been delineated.
@PREF = Since Buddhism, Jainism and Sikhism are closely allied to ç
Hinduism they too have been described briefly along with the biographies ç
of their founders.
@PREF = Now, a word about the language: The Basic Manual of Style ç
given in standard dictionaries has been closely followed as far as ç
possible. Use of capital letters has been minimised. Italics have ç
been used to indicate the titles of books and works as also foreign ç
words. In the body of the work, all Sanskrit words are given in the ç
usual Roman script only except in rare cases where found necessary ç
italics have been used. All references to works quoted have been given ç
in full, avoiding abbreviations.
@PREF = Line-drawings as also halftone pictures have been given in ç
the body of the work itself under the respective titles. Photographs ç
have been given separately in a bunch at the appropriate places.
@PREF = Brief biographical notes of the better known Indologists have ç
been given at the end as appendices.
@PREF = A work of this dimension could not have been accomplished ç
without academic help from various quarters. However, only a select ç
bibliography has been prepared and added at the end. Small booklets ç
and articles which have also been consulted, have not been mentioned ç
since they are too numerous to do so.
@PREF = This stupendous task, normally undertaken by institutions, ç
has some how been completed†it was started in 1975†solely by the grace ç
of God. It is being dedicated to <185>r<200> S<193>rad<193>dev<200>†better ç
known as the Holy Mother†the Divine Spouse of the Divine Lord, Bhagav<193>n ç
<185>r<200> R<193>mak<216><218><207>a Paramaha<221>sadeva.
@PREF = I earnestly hope that the students of Hinduism as also the ç
Hindu society will find this work useful in understanding the essence ç
of Hinduism in the right spirit.
@SIGN = Bangalore	Swami Harshananda<R>ç
December 30, 2007
@H = <R>ç
Acknowledgements
@IN2 = A big project like this could not have been successfully accomplished ç
but for the help of several persons received over the years. The following ç
are the more important ones to whom we are deeply indebted:
@IN2 = Sri B. N. Nataraj of Sri Nithyananda Printers who had taken ç
the entire responsibility of photo-composing, printing, binding and ç
other allied works.
@IN2 = Kum. K. Susheela who ably assisted Sri B. N. Nataraj in various ç
ways. She has been working at it for over 18years.
@IN2 = Sriyuths C. N. Mohan Kumar and C. N. Sathyanarayana of the ç
Gurudutt Printers Pvt. Ltd, for the excellent job of printing.
@IN2 = Sri N. Arvind who gave his expertise in fine-tuning the scanning ç
of the line-drawings and photographs.
@IN2 = Sri S. Sudarshan who took immense trouble in scanning all the ç
necessary materials including the line-drawings and photographs.
@IN2 = Sri Nagsundar of Geetanjali Graphics for meticulously preparing ç
all the necessary plates for printing.
@IN2 = We are also grateful to the various devotees who have helped ç
us financially, the chief ones being Ms. Stella Soper of United Kingdom, ç
Prof. M. Lakshmanan of Bangalore and Dr. V. V. Srinivasan of U.S.A.
@HLS = List of Photographs<R>ç
<P10.5B>(<BI>Vide<B> Photo Section at the end of the book)<P255D>
@CAPN = Ref. Article	
@CAPH = Temple entrance at Ha<202>eb<200><195>u	Ha<202>eb<200><195>u
@CAPH = A view of Hampi Vir<220>p<193>k<218>a Temple	Hampi
@CAPH = Banks of the river Ga<209>g<193>	Haridv<193>ra
@CAPH = Golden Temple at Amritsar	Harimandir
@CAPH = Panoramic views of the Him<193>layas	Him<193>layas
@SAPCE2 = 
@CAPH = Language of the Indus Valley	Indus Valley Civilisations
@CAPH = A clay cart from Mohenjo Daro	Indus Valley Civilisations
@CAPH = The Grain Mills at Harappa	Indus Valley Civilisations
@CAPH = Warehouses for grains at Harappa<R>ç
         and Mohenja Daro	Indus Valley Civilisations
@CAPH = A toy cart in clay	Indus Valley Civilisations
@SAPCE2 = 
@CAPH = Jagann<193>tha Temple	Jagann<193>tha-Pur<200>
@CAPH = Sant J<210><193>ne·var	J<210><193>ne·var, Sant 
@SAPCE2 = 
@CAPH = Kab<200>rdas	Kab<200>r
@CAPH = Mt. Kail<193>s	Kail<193>sa
@CAPH = K<193>la<195><200> Temple	K<193>la<195><200>
@CAPH = K<193><202>ahast<200>·vara Temple	K<193><202>ahast<200> 
@CAPH = The Temple of K<193>m<193>khy<193>	K<193>m<193>khy<193>
@CAPH = Kany<193>kum<193>r<200> idol in the temple	Kany<193>kum<193>r<200>
@CAPH = Vi·van<193>tha Temple at K<193>·<200>	K<193>·<200>
@CAPH = Kathakal<200> Dancer	Kathakal<200>
@CAPH = Ked<193>rn<193>tha Temple	Ked<193>rn<193>tha
@CAPH = Kandariya Mah<193>deva Temple	Khajur<193>ho
@CAPH = S<220>rya Temple at Ko<207><193>rka	Ko<207><193>rka
@CAPH = K<218><200>rabhav<193>n<200> Temple	K<218><200>rabhav<193>n<200> ç

@CAPH = Kukke Subrahma<207>ya Temple	Kukke Subrahma<207>ya
@SAPCE2 = 
@CAPH = V<200>rabhadra Temple at Lep<193>k<218>i	Lep<193>k<218>i
@SAPCE2 = 
@CAPH = Madan Mohan M<193><202>av<200>ya	M<193><202>av<200>ya, Madanmohan
@CAPH = Madhav<193>c<193>rya	Madhav<193>c<193>rya
@CAPH = M<200>n<193>k<218><200> Temple	Madurai
@CAPH = Shore Temple at Mah<193>balipuram	Mah<193>balipuram
@CAPH = Mah<193>k<193>la Temple at Ujjayin<200>	Mah<193>k<193>la  
@CAPH = A view of M<193>nasa-sarovara	M<193>nasa-sarovara
@CAPH = A view of Mantr<193>laya Temple	Mantr<193>laya
@CAPH = B<216>nd<193>vana at Mantr<193>laya	Mantr<193>laya
@CAPH = M<200>r<193>b<193><200>	M<200>r<193>b<193><200>
@CAPH = Shrine at M<220>k<193>mbik<193> Temple	M<220>k<193>mbik<193> ç

@SAPCE2 = 
@CAPH = N<193>ga Serpents under A·vattha tree	N<193>ga
@CAPH = N<193>ga tribal in his traditional attire	N<193>gas  
@CAPH = Guru N<193>nak	N<193>nak, Guru
@CAPH = N<193>r<193>ya<207>a Guru	N<193>r<193>ya<207>a Guru
@CAPH = Nars<200> Meht<193>	Nars<200> Meht<193>
@CAPH = Nimb<193>rk<193>c<193>rya	Nimb<193>rka
@CAPH = God<193>var<200> at N<193>sik	N<193>sik
@SAPCE2 = 
@CAPH = O<209>k<193>re·vara Temple	O<209>k<193>re·vara
@CAPH = Asiatic Society	Oriental Research Institutes of India
@CAPH = Bhandarkar Institute	Oriental Research Institutes of India
@SAPCE2 = 
@CAPH = Padman<193>bha Temple at Tiruvanantapuram	Padman<193>bha Temple
@CAPH = Parak<193>la Ma<219>ha at Mysore	Parak<193>la Ma<219>ha
@CAPH = Pa·upatin<193>tha Temple at Nepal	Pa·upatin<193>tha Temple
@CAPH = Purandarad<193>sa	Purandarad<193>sa
@CAPH = A view of the temples at Pa<219><219>adakal	Pa<219><219>adakal
@CAPH = Holy dip at Trive<207>i Sa<209>gam	Pray<193>g
@END = <R>ç

@H = Key to Transliteration and Pronunciation
@Z_TBL_BEG = COLUMNS(6), DIMENSION(IN), COLWIDTHS(.6667,.3333,E1,.3333,1.7917,.6667), ç
KEEP(OFF), L0(R8C0..R8C3), L0(R0C3..R24C4)
@Z_TBL_HEAD = A2, A2, A2, A2, A2, A2
, , Sounds like, , Sounds like, 
@Z_TBL_BODY = TABLE TEXT, A3, A4, A3, A4, TABLE TEXT
, De, a-o in son, [, <195>-d in den, 
, Dee, <193>-a in master, {, <195>h-dh in godhood, 
, F, i-i in if, Ce, <207>-n in under, 
, F&, <200>-ee in feel, le, t-t in French, 
, G, u-u in full, Le, th-th in thumb, 
, T, <220>-oo in boot, o, d-th in then, 
, $e<189>, <216>-somewhat between, Oe, dh-the in breathe, 
@Z_TBL_BODY = A4, A4, A4-1, A3, A4, TABLE TEXT
, , r and ri, ve, n-n in not, 
@Z_TBL_BODY = TABLE TEXT, A3, A4, A3, A4, TABLE TEXT
, S, e-ay in May, He, p-p in pen, 
, Ss, ai-y in my, He†, ph-ph in loop-hole, 
, Dees, o-o in oh, ye, b-b in bag, 
, Deew, au-ow in now, Ye, bh-bh in abhor, 
, ke†, k-k in keen, ce, m-m in mother, 
, Ke, kh-ckh in blockhead, ìe, y-y in yard, 
, ie, g-g (hard) in go, j, r-r in run, 
, Ie, gh-gh in log-hut, ue, l-l in luck, 
, *, <209>-ng in singer, Je, v-v in avert, 
, ée, c-ch in chain, Me, ·-sh in reich (German), 
, <205>, ch-chh in catch him, <<e, <218>-sh in show, 
, pe, j-j in judge, me, s-in sun, 
, Pe, jh-dgeh in hedgehog, n, h-in hot, 
, _e, <210>-n (somewhat) as in, U, <202>, 
@Z_TBL_BODY = TABLE TEXT, A3, A4-1, A3, A4, TABLE TEXT
, ,  French, <+>b, <221>-m in sum, 
@Z_TBL_BODY = TABLE TEXT, A3, A4, A3, A4, TABLE TEXT
, <204>,  <219>-t in ten, <203>, <199>-h in half, 
, <222>, <219>h-th in ant-hill, , , 
@Z_TBL_END = 
@END = 
