@HALF = A C<MS>ONCISE<D><R>ç
E<MS>NCYCLOPAEDIA<D> <MS>OF<D><R>ç
HINDUISM
@HALF-1 = V<MS>OLUME<D> 4<R>ç
<P13.5MJ249>Supplement<P255DJ0%10><R>ç
A<%0><196><|>Z
@BLANK = <P12W1>Blank<P255D>
@T1 = A
@T1 = Concise Encyclopaedia
@T1 = of
@T1-1 = HINDUISM
@T2 = Volume 4
@T3 = <P12.5BJ250>Supplement<P255DJ0><R>ç
A<|><%-4><196><%-24> <%0>Z
@T4 = Swami Harshananda
@T5 = Ramakrishna Math<R>ç
<P12.5B>Bangalore<|>-<|>560<|>019<P255D>
@IMP = A C<P8W1>ONCISE<P255D> E<P8W1>NCYCLOPAEDIA<P255D> <P8W1>OF<P255D> ç
H<P8W1>INDUISM<P255D><|><197><|>Volume 4 (Supplement)<R>ç
Written and Published by<R>ç
Swami Harshananda, President, Ramakrishna Math<R>ç
Bull Temple Road, Bangalore<|>-<|>56<%16>0<%0>019. Karnataka<|><196><|>India.<R>ç
Phone and e-mails<|>:<R>ç
	Office	:	91-80-2661<|>3149, 2667<|>1010<R>ç
			rkmfive@gmail.com<R>ç
	Bookstall	:	91-80-2661<|>6161, 2661<|>6060<R>ç
			bookstall@rkmathbangalore.org<R>ç
Website	:	www.rkmathbangalore.org<R>ç
<R>ç
Pages: xvi + 176
@IMP1 = <189> R<MS>AMAKRISHNA<D> M<MS>ATH<D><R>ç
Bangalore 56<W1%16>0<D%0>019
@IMP2 = All rights reserved. No part of this book may be reproduced ç
or utilized in any form or by any means, electronic or mechanical, ç
including photocopying, recording, or by any information storage and ç
retrieval system without the permission in writing from the publisher.
@IMP = First Edition<|>:	April 2014; Copies 3M
@IMP = Code: 4098<R>ç
<R>ç
ISBN-13<R>ç
978-81-7907-057-4 (Set of Three Volumes + Supplement)
@IMP = <P8W1I>Cover<|>Picture<|><W1>: Ruins of Sharada Temple in Pak ç
Occupied Kashmir<P255D>
@IMP = Price<|>: Per Set of Three Volumes	:<+>Rs. 2,000/-<R>ç
Price<|>: Volume 4 (Supplement)	:<+>Rs. <+>300/-
@IMP = Printed by<R>ç
B. N. Nataraj<R>ç
Sri Nithyananda Printers<R>ç
# 46, 4th Cross, Ashoknagar<R>ç
BSK 1st Stage, Bangalore<|>-<|>560<|>050<R>ç
Karnataka<|><196><|>India.<R>ç
Phone: 91-80-2242<|>6027
@H = Preface to the Three Volume Edition
@PREF = Hinduism is a great religion. The traditionalists however ç
prefer to call it `San<193>tana Dharma'. Perhaps, this is a far better ç
term that reflects its true meaning and significance. The word dharma ç
is generally used to denote religion, the path to perfection or beatitude. ç
`San<193>tana' means `ancient' as also `eternal'. Hence the expression ç
means `the religion or thepath of spiritual discipline that is not ç
only ancient but also eternal'. In other words, Hinduism has been ç
offering an unbroken continuous tradition of spiritual discipline ç
which is not only very ancient but also relevant even to the modern ç
times. The beauty of this tradition is that it proffers several alternatives ç
that can suit different types of s<193>dhakas (aspirants) instead ç
of prescribing the same cap for every head. Thus, starting from the ç
aspirant at the highest rung of the spiritual ladder who is fit to ç
meditate on the non-dual Brahman (the Absolute), right up to the tyro ç
worshipping the images, everyone has a place specially carved out ç
for him.
@PREF = Of late, study of Hinduism is drawing the attention of scholars ç
both from India and from other countries. However, books on general ç
Hinduism covering all aspects are not many. Even the few that are ç
available deal with subjects like the Upani<218>ads, the Bhagavadg<200>t<193>, ç
Ved<193>nta systems and Yoga philosophy in greater detail ignoring ç
other aspects relevant to popular Hinduism.
@PREF = Hence there is a great need for an exhaustive omnibus type ç
of work.
@PREF = There were two choices before me:
@NPREF = 1.
@NKPREF = To prepare a comprehensive work with several chapters touching ç
on all aspects of Hinduism.
@NPREF = 2.
@NKPREF = To work on a regular encyclopaedia of Hinduism, arranging ç
the various subjects in the English alphabetical order.
@PREF = After weighing the pros and cons, I decided in favour of the ç
latter since it would be much easier for the average reader to locate ç
the subject he wants to know.
@PREF = This is now in your hands.
@PREF = The entries have been arranged in the English alphabetical ç
order.Since most of the subject headings are in Sanskrit, standard ç
diacritical marks as approved by the International Alphabet of Sanskrit ç
Transliteration and based on a standard established by the Congress ç
of Orientalists at Athens in <MS>A.<|>D.<D> 1912 have been adopted. ç
However, while arranging the titles in the alphabetical order, the ç
diacritical marks have been ignored to facilitate easy recognition.
@PREF = As for the subject content, the following are the main topics ç
dealt with in greater detail: religion, philosophy, mythology, rituals, ç
scriptural works, festivals and pilgrim centres.
@PREF = Other topics described include astrology, biographies of religious ç
personalities, iconography, Sanskrit language and literature, temples ç
and religious institutions.
@PREF = Care has been taken to deal with the four Vedas, their subsidiary ç
works and allied literature. Several important Vedic S<220>ktas, y<193>gas ç
or sacrifices as also unfamiliar concepts and terms have also been ç
described.
@PREF = Along with the major Upani<218>ads and the Mah<193>pur<193><207>as, ç
several minor Upani<218>ads and the upapur<193><207>as too have been ç
dealt with.
@PREF = While the essay on the R<193>m<193>ya<207>a is fairly exhaustive, ç
the one on the Mah<193>bh<193>rata is more condensed because of ç
its immense size. However, the various topics dealt with in it like ç
dharma or the minor G<200>t<193>s or the Yak<218>apra·na do find ç
a place as independent articles.
@PREF = Since most of the <193>gamas and tantras are still in the ç
manuscript form, justice could not be done to this subject area. Only ç
a few major ones, more well-known, have been delineated.
@PREF = Since Buddhism, Jainism and Sikhism are closely allied to ç
Hinduism they too have been described briefly along with the biographies ç
of their founders.
@PREF = Now, a word about the language: The Basic Manual of Style ç
given in standard dictionaries has been closely followed as far as ç
possible. Use of capital letters has been minimised. Italics have ç
been used to indicate the titles of books and works as also foreign ç
words. In the body of the work, all Sanskrit words are given in the ç
usual Roman script only except in rare cases where found necessary ç
italics have been used. All references to works quoted have been given ç
in full, avoiding abbreviations.
@PREF = Line-drawings as also halftone pictures have been given in ç
the body of the work itself under the respective titles. Photographs ç
have been given separately in a bunch at the appropriate places.
@PREF = Brief biographical notes of the better known Indologists have ç
been given at the end as appendices.
@PREF = A work of this dimension could not have been accomplished ç
without academic help from various quarters. However, only a select ç
bibliography has been prepared and added at the end. Small booklets ç
and articles which have also been consulted, have not been mentioned ç
since they are too numerous to do so.
@PREF = This stupendous task, normally undertaken by institutions, ç
has some how been completed†it was started in 1975†solely by the grace ç
of God. It is being dedicated to <185>r<200> S<193>rad<193>dev<200>†better ç
known as the Holy Mother†the Divine Spouse of the Divine Lord, Bhagav<193>n ç
<185>r<200> R<193>mak<216><218><207>a Paramaha<221>sadeva.
@PREF = I earnestly hope that the students of Hinduism as also the ç
Hindu society will find this work useful in understanding the essence ç
of Hinduism in the right spirit.
@SIGN = Bangalore	Swami Harshananda<R>ç
December 30, 2007
@H = <R>ç
Acknowledgements for the Three Volume Edition
@IN2 = A big project like this could not have been successfully accomplished ç
but for the help of several persons received over the years. The following ç
are the more important ones to whom we are deeply indebted:
@IN2 = Sri B. N. Nataraj of Sri Nithyananda Printers who had taken ç
the entire responsibility of photo-composing, printing, binding and ç
other allied works.
@IN2 = Kum. K. Susheela who ably assisted Sri B. N. Nataraj in various ç
ways. She has been working at it for over 18years.
@IN2 = Sriyuths C. N. Mohan Kumar and C. N. Sathyanarayana of the ç
Gurudutt Printers Pvt. Ltd., for the excellent job of printing.
@IN2 = Sri N. Arvind who gave his expertise in fine-tuning the scanning ç
of the line-drawings and photographs.
@IN2 = Sri S. Sudarshan who took immense trouble in scanning all the ç
necessary materials including the line-drawings and photographs.
@IN2 = Sri Nagsundar of Geetanjali Graphics for meticulously preparing ç
all the necessary plates for printing.
@IN2 = We are also grateful to the various devotees who have helped ç
us financially, the chief ones being Ms. Stella Soper of United Kingdom, ç
Prof. M. Lakshmanan of Bangalore and Dr. V. V. Srinivasan of U.S.A.
@H = Preface to the Supplement
@PREF = The book, A Concise Encyclopaedia of Hinduism in three volumes, ç
was brought out during May 2008. It was released on the 30th May 2008 ç
by Bharat Ratna Dr. A. P. J. Abdul Kalam at an impressive function ç
in the presence of a very large gathering of scholars, devotees and ç
distinguished persons.<P8W1>
@PREF = During this release function, Dr. Kalam had suggested that ç
supplements can be brought out as and when new material is discovered ç
or gathered.
@PREF = This supplement is a sequel to it.
@PREF = It contains some of the subjects omitted in the earlier volumes ç
as also plenty of new material, especially related to the tantra-literature.
@PREF = The entire system of arrangements adopted in the earlier volumes ç
has been continued here also.
@PREF = Though this is a small volume, the same standard of excellence ç
in printing and getup as in the earlier volumes has been maintained.
@PREF = We hope that the admirers of Hindu values of life will find ç
this small book also useful.<R>ç

@SIGN = Bangalore<R>ç
March 3, 2014
@H = <R>ç
Acknowledgements for the Supplement
@IN2 = We are deeply indebted to the following persons but for whose ç
help this work would not have been a success:
@IN2 = Sri B. N. Nataraj of Sri Nithyananda Printers who had taken ç
the entire responsibility of photo-composing, printing, binding and ç
other allied works.
@IN2 = Kum. K. Susheela who ably assisted Sri B. N. Nataraj in various ç
ways.
@IN2 = Sriyuths C. N. Mohan Kumar and C. N. Sathyanarayana of the ç
Gurudutt Printers, for the excellent job of printing.
@IN2 = Sri N. Arvind who has fine-tuned the photographs and printed ç
the cover page.
@IN2 = Sri S. Sudarshan who took immense trouble in scanning all the ç
necessary photographs.
@IN2 = Sri Nagsundar of Geetanjali Graphics for meticulously preparing ç
all the necessary plates for printing.
@IN2 = 
@SIGN1 = Bangalore<R>ç
March 3, 2014
@H = Key to Transliteration and Pronunciation
@Z_TBL_BEG = COLUMNS(6), DIMENSION(IN), COLWIDTHS(.6667,.3333,E1,.3333,1.7917,.6667), ç
KEEP(OFF), L0(R8C0..R8C3), L0(R0C3..R24C4)
@Z_TBL_HEAD = A2, A2, A2, A2, A2, A2
, , Sounds like, , Sounds like, 
@Z_TBL_BODY = TABLE TEXT, A3, A4, A3, A4, TABLE TEXT
, De, a-o in son, [, <195>-d in den, 
, Dee, <193>-a in master, {, <195>h-dh in godhood, 
, F, i-i in if, Ce, <207>-n in under, 
, F&, <200>-ee in feel, le, t-t in French, 
, G, u-u in full, Le, th-th in thumb, 
, T, <220>-oo in boot, o, d-th in then, 
, $e<189>, <216>-somewhat between, Oe, dh-the in breathe, 
@Z_TBL_BODY = A4, A4, A4-1, A3, A4, TABLE TEXT
, , r and ri, ve, n-n in not, 
@Z_TBL_BODY = TABLE TEXT, A3, A4, A3, A4, TABLE TEXT
, S, e-ay in May, He, p-p in pen, 
, Ss, ai-y in my, He†, ph-ph in loop-hole, 
, Dees, o-o in oh, ye, b-b in bag, 
, Deew, au-ow in now, Ye, bh-bh in abhor, 
, ke†, k-k in keen, ce, m-m in mother, 
, Ke, kh-ckh in blockhead, ìe, y-y in yard, 
, ie, g-g (hard) in go, j, r-r in run, 
, Ie, gh-gh in log-hut, ue, l-l in luck, 
, *, <209>-ng in singer, Je, v-v in avert, 
, ée, c-ch in chain, Me, ·-sh in reich (German), 
, <205>, ch-chh in catch him, <<e, <218>-sh in show, 
, pe, j-j in judge, me, s-in sun, 
, Pe, jh-dgeh in hedgehog, n, h-in hot, 
, _e, <210>-n (somewhat) as in, U, <202>, 
@Z_TBL_BODY = TABLE TEXT, A3, A4-1, A3, A4, TABLE TEXT
, ,  French, <BJ14><|>b<DJ0>, <221>-m in sum, 
@Z_TBL_BODY = TABLE TEXT, A3, A4, A3, A4, TABLE TEXT
, <204>,  <219>-t in ten, <203>, <199>-h in half, 
, <222>, <219>h-th in ant-hill, , , 
@Z_TBL_END = 
@END = 
@HALF = A C<MS>ONCISE<D><R>ç
E<MS>NCYCLOPAEDIA<D> <MS>OF<D><R>ç
HINDUISM
@HALF-1 = V<MS>OLUME<D> 4<R>ç
<P13.5MJ249>Supplement<P255DJ0%10><R>ç
A<%0><196><|>Z
@BLANK = Blank
