@H = U
@NT = Ubhayabh<193>rat<200>
The traditional biographies of <185>a<209>kara (<MS>A.<|>D.<D> 788-820) ç
like the <185>a<209>kara-digvijaya of M<193>dhava-Vidy<193>ra<207>ya ç
(14th century <MS>A.<|>D.<D>) state that after <185>a<209>kara vanquished ç
Ma<207><195>ana Mi·ra†a great scholar of M<200>m<193><221>s<193> philosophy†his ç
wife Bh<193>rat<200> challenged him for an intellectual debate. She ç
was finally humbled by <185>a<209>kara and like her husband, she too ç
decided to become a recluse and a disciple. She is said to have followed ç
<185>a<209>kara up to <185><216><209>ger<200> and settled down there.
She has been described as an incarnation of Sarasvat<200>, born on ç
earth due to a curse of the sage Durv<193>sas.
The temple of <185><193>rad<193>mb<193> at <185><216><209>ger<200> ç
is her temple.
Since she acted as a judge in the debate between <185>a<209>kara and ç
Ma<207><195>ana† for both of them†she came to be known as Ubhayabh<193>rat<200> ç
(ubhaya = both).
Her original name has also been mentioned as Sarasav<193><207><200>, ç
V<193><207><200> and Amb<193>.
@NT = Ubhayaved<193>nta
@N1 = (`Ved<193>nta [that accepts] both')
Ved<193>nta has branched off into three main streams: Advaita, Vi·i<218><219><193>dvaita ç
and Dvaita.
Unlike the Advaita and the Dvaita philosophies which accept only the ç
prasth<193>natraya (See <MS>PRASTH°NATRAYA<D>.) as authoritative, ç
the Vi·i<218><219><193>dvaita of R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137) ç
accords equal status to the Sanskrit prasth<193>natraya as also to ç
the Divyaprabandham (Tamil works of the °<202>v<193>rs). Hence it ç
is called Ubhayaved<193>nta, Ved<193>nta that accepts both (= ubhaya) ç
the authorities.
@NT = Uccai·ravas
@N1 = (`[the horse whose] ears are erect and high')
This is a divine horse that emerged out of the K<218><200>rasamudra ç
(milk-ocean) at the time of its churning (See <MS>SAMUDRA-MATHANA<D>.) ç
by the gods and the demons. Indra chose to accept it as his royal ç
horse (vide Bh<193>gavata 8.8).
It was pure white in colour.
The father of Satyavat<200> (queen of theking <185>antanu) was also ç
known as Uccai·ravas.
@NT = ucc<193><219>ana
@N1 = (`exorcising')
Employment of spells for malevolent purposes is known as abhic<193>ra ç
and <193>bhic<193>rika-karma.
The six types mentioned in the related works are: m<193>ra<207>a (for ç
causing the death of an enemy); mohana (for casting a spell); stambhana ç
(for arresting the power of an enemy); vidve<218>a<207>a (for causing ç
enmity); ucc<193><219>ana (for throwing out or banishing) and va·<200>kara<207>a ç
(for hypnotising any person).
The rite of ucc<193><219>ana can also be used for exorcising ghosts ç
and evil spirits.
See also <MS>ABHIC°RA<D>.
@NT = ucchi<218><219>a
@N1 = (`the leftover')
In the most general sense, it means anything left over after a rite ç
or action. For instance, oblatory materials like ghee, leftover after ç
a homa or a yaj<210>a (sacrifice) is ucchi<218><219>a.
However it is more commonly used with regard to the food leftover ç
in the plate after a person has eaten.
Though some dharma·<193>stras like the Baudh<193>yana-dharmas<220>tras  (1.2.34, ç
37) allow a disciple to eat the ucchi<218><219>a of his guru, it was ç
discouraged later.
@NT = Ucchi<218><219>a-ga<207>apati
This is one of the thirty-two major forms of Ga<207>apati. It is a ç
form mentioned in the tantras and worshipped for magical ends.
The expression `ucchi<218><219>a' (`leftover') here signifies Brahman, ç
because that alone†or He alone†remains even after the dissolution ç
of the whole world.
It may also mean `unclean'. Ucchi<218><219>a-ga<207>apati is absolute ç
and mighty but unclean or indecent in appearance. He is capable of ç
granting the desires of his votaries even though they too may be unclean!
His images may have six arms or four. The things shown in his hands ç
include lotus, pomegranate, lute, bunch of paddy grains, rosary, bow, ç
arrow, noose, goad, sweetmeat, bowl and broken tusk. He is usually ç
shown with his <185>akti (consort) in an amorous pose.
See also <MS>GAØAPATI<D>.
@NT = Udaka·<193>nti
See <MS><185>°NTIS<D> for details.
@NT = ud<193>na
See <MS>PR°ØA<D>.
@NT = Uda<209>ka
A sage often mentioned in the Mah<193>bh<193>rata, Uda<209>ka had ç
propitiated Vi<218><207>u through his tapas and had got some boons.
Once K<216><218><207>a†after the Kuruk<218>etra war†came to his hermitage ç
to pay his respects. Thinking that the war which had decimated many ç
k<218>attriya warriors, had been manoeuvred by him, the sage tried ç
to curse him. However, he soon realised (by the cosmic form exhibited ç
by K<216><218><207>a) his mistake and sought boons from him.
Uda<209>ka†also known as Utta<209>ka† was a disciple of the sage Gautama. ç
While bidding goodbye to him after completing his studentship, Gautama ç
asked him to get the ear-rings of Madayant<200>, the queen of the ç
king Saud<193>sa, for his wife Ahaly<193>. Uda<209>ka got them after ç
a great effort.
@NT = udarabandha
@N1 = (`belly-band')
Iconographical works describe ka<219>i-bandha (waist-band) and udarabandha ç
(belly-band) for certain images like those of Ga<207>e·a.
It is of various forms and is to be shown above the navel and below ç
the chest, covering the belly.
@NT = Ud<193>s<200>s
The Ud<193>s<200>s are an ascetic sect of the Sikhs founded by <185>r<200>cand ç
(<MS>A.<|>D.<D> 1494-1629), the elder son of Guru N<193>nak (<MS>A.<|>D.<D> ç
1469-1539). The word ud<193>s<200> is derived from the Sanskrit word ç
ud<193>sin, which means one who is indifferent towards the comforts ç
and attachments of the world.
<185>r<200>cand was a devoted Sikh and a saintly person. His object ç
in establishing the order of the Ud<193>s<200>s was to propagate the ç
mission of his father. Though he was not anointed as the next Guru ç
by his father, he kept an amicable relationship with all the Gurus.
B<193>b<193> Guruditt<193>, the eldest son of Guru Hargobind (<MS>A.<|>D.<D> ç
1595-1644), was sent by the Guru to assist and to succeed <185>r<200>cand.
B<193>b<193> Guruditt<193> appointed four head-preachers: Almast; ç
Ph<220>l; Goind (or Gonda); B<193>l<220> Husn<193>. They were given ç
his own dress†which became the peculiar Ud<193>s<200> uniform†as also ç
the dhuni (smouldering embers) from <185>r<200>cand's dhuni. These ç
four established four new seats of the Ud<193>s<200> sect.
The Ud<193>s<200>s proved to be zealous preachers of Sikhism and carried ç
its message to all the corners of the country and beyond. They revered ç
and recited the b<193><207><200> (sayings) of the Gurus, but retained ç
their separate identity. They took control of the Sikh places of worship ç
and protected them when needed.
The Ud<193>s<200>s recruit their followers from all castes and professions. ç
In their monasteries it is the Guru Granthas<193>hib that is recited. ç
They do not subscribe to the Sikh rites and use the bell, conch and ç
gong in religious services.
They wear white or ochre or red clothes. There is also one group that ç
goes naked. Having matted hair and smearing the body with ashes are ç
also common.
They have built bu<209>gas (resthouses) around the Harmandir complex ç
in Amritsar. These are also prominent centres of learning, °yurveda ç
being one of the important subjects taught.
The most important centres of this sect in North India are: the Brahm ç
B<220><219><193> Akh<193><195><193> and Sa<209>gal<193>nv<193>l<193> ç
Akh<193><195><193> at Amritsar; Nira<210>janiy<193> Akh<193><195><193> ç
at Patiala (both in Punjab); Pa<210>cait<200> Akh<193><195><193> at ç
Hardwar (in Uttar Pradesh).
@NT = ud<193>tta
@N1 = (`raised')
See <MS>ANUD°TTA<D> for details.
@NT = Udayana
See <MS>NY°YAKUSUM°<178>JALI.<D>
@NT = Udayan<200>y<193>
A Somay<193>ga has an introductory or opening rite called Pr<193>ya<207><200>y<193> ç
and a closing rite called Udayan<200>y<193>.
These sacrifices belong to the i<218><219>i type (see <MS>I<186><187>I<D> ç
for details.)
The Pr<193>ya<207><200>y<193> is performed after the d<200>k<218><193> ç
(consecration of the sacrificer) day. Going out to fetch the soma ç
creepers is the most important part of this rite. Offering of caru ç
(porridge-like preparation) and <193>jya (ghee) to some deities is ç
also done.
In the Udayan<200>y<193> i<218><219>i, the concluding rite is performed ç
in the fire of the shedcalled pr<193>c<200>nava<221>·a, erected with ç
bamboos, with four oblations.
@NT = Udd<193>laka
See <MS>°RUØI<D>.
@NT = udd<193>lakavrata
@N1 = (`penance [prescribed by] Udd<193>laka')
Any boy born in the family of a dvija (the twice-born) is expected ç
to undergo the Upanayana sacrament within the prescribed age-limit, ç
which is 16 years for a br<193>hma<207>a, 22 years for a k<218>attriya ç
and 24 years for a vai·ya. If he fails to do so, he is branded as ç
patitas<193>vitr<200>ka or vr<193>tya. (`S<193>vitr<200>' means the ç
G<193>yatr<200> mantra.)
One of the expiations prescribed for such a person to become fit again ç
for the Upanayana sacrament is the Udd<193>laka vrata. Since the sage ç
Udd<193>laka-°ru<207>i prescribed it, it has been named after him.
A person who performs this vrata should subsist on the prescribed ç
food as follows:
@NID = for two months on barley gruel;
@NID = for one month on milk;
@NID = for half-a-month on <193>mik<218><193> (whey);
@NID = for eight days on ghee;
@NID = for six days on alms got without begging;
@NID = for three days on water;
@NID = and a total fast for one day.
@NID = (vide Vasi<218><219>hasm<216>ti 11.76-79)
See also <MS>PATITAS°VITR®KA<D>.
@NT = Uddhava
Uddhava, the son of Devabh<193>ga a y<193>dava hero, was a cousin ç
and friend of K<216><218><207>a.
When K<216><218><207>a decided to send the news of his welfare to ç
the gop<200>s of V<216>nd<193>ban who had been very much worried, ç
it was Uddhava who acted as his messenger.
Before K<216><218><207>a left for his eternal Abode, Uddhava approached ç
him for his last message. This has now become well- known as the Uddhavag<200>t<193> ç
(Bh<193>gavata, 11.7-29).
@NT = Uddhavag<200>t<193>
See under <MS>K<184><186>ØA<D>.
@NT = u<195><195><200>y<193>nabandha
This is one of the exercises†known as mudr<193>s or bandhas†prescribed ç
by works on Ha<219>hayoga for controlling the pr<193><207>a (vital ç
air and energy) and make it move into the su<218>umn<193>-n<193><195><200> ç
(canal). It consists mainly in contracting the muscles of the belly ç
backwards towards the spine. It helps one to revitalise his energy.
The actual technique has to be learnt from an adept in the science ç
(vide Ha<219>hayogaprad<200>pik<193> 3.54-59).
@NT = udg<193>t<216>
@N1 = (`the chanter')
In any Vedic sacrifice, four principal priests are involved. The udg<193>t<216> ç
is the third priest representing the S<193>maveda. His main duty ç
is to chant the s<193>mans (mantras of the S<193>maveda) at the ç
appropriate stages in the sacrifice. Sometimes he is also to perform ç
some minor rites.
He has three assistants. They are: prastot<216>, pratihart<216> and ç
subrahma<207>ya.
@NT = udg<200>tha
The mantras of the S<193>maveda are called `s<193>man'. Each s<193>man ç
has five fundamental steps in singing. Out of them the second†which ç
is the main part†is known as the `udg<200>tha'. It is sung by the ç
main priest udg<193>t<216>. It always begins with O<221>.
See also <MS>S°MAN<D>.
@NT = udg<200>thavidy<193>
See <MS>VIDY°S<D>.
@NT = U<195>upi
@N1 = (`the place where Candra [Moon] was blessed [by <185>iva]')
U<195>upi is one of the most famous and popular places of pilgrimage, ç
especially to the Vai<218><207>avas.
It is in the South Kanara district of the Karnataka State (in south ç
India), situated on the seashore at a distance of 60 kms. (37 miles) ç
to the north of the city of Mangalore. 
Candra or the deity Moon (also called U<195>upa) is said to have performed ç
austerities here to rid himself of the curse of Dak<218>a Praj<193>pati. ç
He was redeemed by Lord <185>iva. A temple dedicated to Candramau<202><200>·vara ç
(<185>iva) is situated here now.
Another ancient temple is that of Anante·vara, right opposite the ç
Candra-mau<202><200>·vara temple.
Both the temples belong to the period 7th to 9th century <MS>A.<|>D.<D>
U<195>upi†also called Rajatap<200><219>hapura† is now famous for its ç
K<216><218><207>a temple and the eight Ma<219>has (monasteries) established ç
by Madhv<193>c<193>rya (<MS>A.<|>D.<D> 1238-1317). The K<216><218><207>a ç
temple also was built by him after he secured the beautiful image ç
from a big lump of yellow clay which had been used as a ballast by ç
a ship. The ship was about to sink when Madhv<193>c<193>rya saved ç
it by using his divine powers. He then obtained that heap of clay ç
as a present at his own request. After recovering the image he carried ç
it on his head to the present place and built the temple.
The image is that of child K<216><218><207>a, in the standing posture, ç
holding the churning rod in the left hand and a rope in the right. ç
Sculptured out of the <185><193>lagr<193>ma stone (by the divine architect ç
Vi·vakarma himself) and worshipped by Rukmi<207><200>, it was later ç
secured by Arjuna (the P<193><207><195>ava hero) who hid it in clay ç
before his departure. This is how the local legends describe the origin ç
of the image.
It is 38 cms. (15 inches) in height.
The temple, built of black granite stone, is rather a small structure. ç
To theright of the main entrance is the Madhvasarovara, the temple ç
tank. The main entrance gate is facing north whereas the deity is ç
facing west. It can be seen only through a small open window, known ç
as `Kanakana ki<207><195>i' (`Kanaka's Window'). When Kanakad<193>sa ç
(<MS>A.<|>D.<D> 1508-1606), the famous devotee of K<216><218><207>a ç
was denied entrance into the temple because he belonged to a low caste, ç
he prayed to the Lord with an intensely yearning heart for dar·an. ç
In response to his prayer, K<216><218><207>a's image turned towards ç
the west where Kanakad<193>sa was standing and an opening appeared ç
on the wall mysteriously, thus enabling him to see the Lord.
@SPACE1 = 
The main festivals of the <185>r<200> K<216><218><207>a temple  are:  Saptotsava  (a  seven-day ç
festival celebrated during the middle of January), Madhvanavam<200> ç
(the day on which Madhv<193>c<193>rya disappeared from the world), ç
<185>r<200> K<216><218><207>a Jayant<200> (birthday of Lord <185>r<200> ç
K<216><218><207>a in August-September), Lak<218>a-d<200>potsava (on ç
the day of Utth<193>nadv<193>da·<200> generally in November), and ç
Pary<193>ya- mahotsava.
The pontiffs of each of the eight ma<219>has (monasteries) got a two-month ç
term to worship the image of K<216><218><207>a in the temple. Since ç
this was considered too short a period, V<193>dir<193>ja (<MS>A.<|>D.<D> ç
1480-1600), the best of the pontiffs at that time, raised it to two ç
years. So, there is a change of guard†the next pontiff taking over ç
the responsibility of running the K<216><218><207>a temple †every ç
two years, during the last part of January. This is called Pary<193>yamahotsava.
Other festivals are: R<193>manavam<200>, Narasi<221>hajayant<200>, ç
Anantacaturda·<200>, Makara-Sa<209>kr<193>nti and D<200>p<193>val<200>.
A few more holy places around U<195>upi worth visiting are: Ambalap<193><195>i ç
(with an ancient temple of Jan<193>rdana as also of Mah<193>k<193>l<200>); ç
Da<207><195>at<200>rtha (a tank built by Madhv<193>c<193>rya); Nadyant<193>di ç
(where there is a ma<219>ha as also two bathing places called Gad<193>t<200>rtha ç
and Gautamaku<207><195>a) and Ka<195>tila or Setutila (where Madhv<193>c<193>rya ç
established the image of Gop<193>lak<216><218><207>a).
See also <MS>MADHV°C°RYA<D> and <MS>KANAKA-D°SA<D>.
@NT = udy<193>pana
@N1 = (`concluding')
Any religious vrata or rite has to be concluded with the rite prescribed ç
for it generally called udy<193>pana or p<193>ra<207><193>.
It consists in taking food after the fasting involved in the vrata, ç
and giving gifts to the needy.
@NT = Udyogaparva
It is the fifth book of the great epic Mah<193>bh<193>rata. See ç
the same for details.
@NT = ugraratha·<193>nti
See <MS><186>A<186><187>YABDAP<188>RTI<D> under <MS><185>°NTIS.<D>
@NT = Ujjayin<200>
@N1 = (`the victorious')
@SPACE = 
@SPACE = 
Ujjayin<200> is one of the seven ancient, most holy, cities capable ç
of giving liberation (mok<218>ad<193>yaka). It got this name because ç
<185>iva is said to have vanquished and killed Tripur<193>sura here. ç
It was also known by several other names such asAvant<200>, Kanaka·<216><209>ga, ç
Kau·asthal<200>, Amar<193>vat<200> and Vi·<193>l<193>. It has been ç
identi-fied with the modern Ujjain city in Madhya Pradesh, which is ç
80 kms. (50 miles) to the north of Indore.
It was the capital of the legendary emperor Vikram<193>ditya (circa ç
57 <MS>B.<|>C.<D>), in whose court the navaratnas or nine gems of scholars ç
like K<193>lid<193>sa, Dhanvantari, Amarasi<221>ha, Var<193>hamihira ç
and Vararuci were believed to have existed.
The city is 486 metres (1620 feet) above the sea-level and is situated ç
on the bank of the <185>ipr<193> (or Sipr<193>) river.
It is famous for the Mah<193>k<193>la temple †one of the twelve jyotirli<209>gas ç
(See <MS>JYOTIRLI<177>GAS<D>.) and as the fourth place where the Kumbhamel<193> ç
festival is held once in twelve years. It is observed when B<216>haspati ç
or Guru (the planet Jupiter) enters the Si<221>har<193>·i (Leo, the ç
fifth sign of the zodiac) in the month of Vai·<193>kha (generally ç
in April).
According to the <185>ivapur<193><207>a (1.46) Mah<193>k<193>la ç
is <185>iva who emerged out of the earth and destroyed the demon D<220><218>a<207>a. ç
At the request of the local devotees he agreed to stay on there itself.
The Mah<193>k<193>la temple has a cellar floor housing the Mah<193>k<193>la-li<209>ga ç
and a ground floor housing O<209>k<193>re·vara-li<209>ga.
Devotees wishing to have the dar·ana (seeing) of the deity have to ç
take bath in the <185>ipr<193> river at the R<193>mgh<193><219> and ç
proceed to the shrine.
Everyday, at 4:30 a.m. <193>rati is done to the Mah<193>k<193>la-li<209>ga ç
by sprinkling the ashes of a freshly cremated corpse of the previous ç
day. This is done on all the days of the year!
°vantik<193>dev<200> is the consort of the Lord in this temple complex.
The Harasiddhi temple (of Mother Annap<220>r<207><193>) is another ç
important shrine. Other temples are those of Gop<193>la (R<193>dh<193>- ç
k<216><218><207>a), Ga<195>hak<193>lik<193> (or Mah<193>k<193>l<200>), ç
K<193>la-bhairava, Ma<209>galan<193>tha and Cint<193>ma<207>i Ga<207>e·a.
About 3 kms. (1.8 miles) from the temple of Gop<193>la is the S<193>nd<200>pani ç
°·rama, where K<216><218><207>a and Balar<193>ma were educated by ç
the sage S<193>nd<200>pani.
Ancient astronomers assigned 0<F14><198><F255> (zerodegree longitude) to ç
Ujjayin<200> (like Greenwich) and based their calculations on it. ç
There is an observatory (Vedha·<193>l<193>) built by the king Jai ç
Singh (circa <MS>A.<|>D.<D> 1700).
@NT = Um<193>
In the Kenopani<218>ad (3.12; 4.1) there is the mention of Um<193> ç
Haimavat<200>·var<200> (Um<193>, the daughter of Himav<193>n, same ç
as P<193>rvat<200>) teaching Indra about Brahman. She is the personification ç
of Brahmavidy<193> or knowledge of Brahman.
See <MS>P°RVAT®<D>.
@NT = u<210>chav<216>tti
@N1 = (`living by leftover grains')
Some of the br<193>hma<207>as, in the olden days, who wanted to live ç
a very austere life, adopted u<210>chav<216>tti for a living, since ç
it entailed no violence or harm to other living beings.
It consisted in gathering grains from agricultural fields after the ç
harvesting was over. Collecting the grains that have fallen on the ç
ground in any shop that sells grains was also included under u<210>chav<216>tti. ç
Food cooked out of these grains was considered very pure.
Ved<193>nta De·ika (<MS>A.<|>D.<D> 1268-1370) and Ty<193>gar<193>ja ç
(<MS>A.<|>D.<D> 1767-1847) are said to have lived by this means.
@NT = unman<200>mudr<193>
This is one of the exercises prescribed by Ha<219>hayoga. It is classed ç
among the mudr<193>s or methods of controlling the body, the pr<193><207>ic ç
energy and the mind.
The yogi has to direct his eyes towards the tip of the nose, raise ç
his eyebrows a little and concentrate the mind on the Brahman (as ç
pure consciousness) inside himself. This results in unman<200>-bh<193>va, ç
an experience of consciousness that transcends the mind (vide Ha<219>hayoga- ç
prad<200>pik<193> 4.39.).
@NT = upac<193>ras
@N1 = (`modes of direct service')
See <MS>DEVAP<188>J°<D>.
@NT = up<193>d<193>nak<193>ra<207>a
@N1 = (`material cause')
See <MS>NIMITTA<D>.
@NT = Upade·as<193>hasr<200>
@N1 = (`[a treatise of] a<R>ç
thousand teachings')
A theoretical treatise on any system of Indian philosophy is generally ç
called `prakara<207>a'. Among the several praka-ra<207>as on Advaita ç
Ved<193>nta written by <185>a<209>kara (<MS>A.<|>D.<D> 788-820), the ç
Upade·a-s<193>hasr<200> is also one, and, a very important one at ç
that.
It is a fairly big work and consists of two sections known as Gadyaprabandha ç
(Prose  Section)  and  Padyaprabandha (Metrical Section).
The former has 116 sections divided into three prakara<207>as and ç
the latter 675 verses spread over nineteen prakara<207>as.
Though it is universally accepted that the Metrical Section is a genuine ç
work of <185>a<209>kara, there are differences of opinion regarding ç
the authorship of the Prose Section.
@S10N = GADYAPRABANDHA (Prose Section)
This section is divided into three parts, each being called a prakara<207>a. ç
Theyare: <185>i<218>yabodhavidhiprakara<207>a; K<220><219>asth<193>dvay<193>tmabodhaprakara<207>a; ç
Parisa<209>khy<193>naprakara<207>a.
In the first prakara<207>a, the °c<193>rya (spiritual teacher) cites ç
many scriptures like the Upani<218>ads and the Bhagavadg<200>t<193> ç
to show the ultimate unity of the j<200>va (individual soul) with ç
Param<193>tman and thus remove his aj<210><193>na (nescience).
In the second prakara<207>a, the logic ofavasth<193>trayaviveka†discrimination ç
as applied to the three states of consciousness (j<193>grat or waking ç
state, svapna or dreaming and su<218>upti or deep sleep state)†is ç
used to prove the existence of the j<200>v<193>tman as pure-consciousness.
The  third  prakara<207>a  deals  with repeated meditation on the ç
truths discovered in the first two viz., the separation of the j<200>va ç
from the body-mind complex and its ultimate identity with Param<193>tman ç
or Brahman.
The contents of these three sections practically correspond to the ç
three aspects of advaitic s<193>dhana, viz., ·rava<207>a (listening ç
to the teachings of Ved<193>nta), manana (deep reflection on the same) ç
and nidi-dhy<193>sana (meditation on the <193>tman).
@S10N = PADYAPRABANDHA (Metrical Section)
A very brief summary of the nineteen prakara<207>as may now be given:
@S10N = Prakara<207>a 1 (26 verses)<R>ç
(Upodgh<193>taprakara<207>a)
Aj<210><193>na (nescience) leads to identification with the body. ç
This leads to the performance of karma, experiencing its results, ç
and rebirth. This is called sa<221>s<193>ra or transmigration. Hence ç
the destruction of this sa<221>s<193>ra by destroying aj<210><193>na ç
is necessary. The science of Brahman or Brahmavidy<193> is therefore ç
taken up to destroy this sa<221>s<193>ra.
@S10N = Prakara<207>a 2 (4 verses)<R>ç
(Prati<218>edhaprakara<207>a) 
This section deals with the assertion of the existence of the <193>tman ç
by denying the body-mind complex as not being one's real nature.
@S10N = Prakara<207>a 3 (4 verses)<R>ç
(®·var<193>tmaprakara<207>a)
This teaches that the understanding of oneself, the <193>tman, being ç
actually the Param<193>tman, is itself vidy<193> (knowledge) which ç
dispels avidy<193> (ignorance).
@S10N = Prakara<207>a 4 (5 verses)<R>ç
(Tattvaj<210><193>nasvabh<193>vaprakara<207>a) 
Identification with the body is bondage. The awareness that one is ç
the spirit, beyond it, is liberation. This is the gist of this section.
@S10N = Prakara<207>a 5 (5 verses)<R>ç
(Buddhyapar<193>dhaprakara<207>a)
@EMERGENCY = Not  accepting  <193>tmaj<210><193>na  by  the buddhi ç
(the intellect), thinking that it leads to the giving up of the karmas ç
prescribed for one's var<207>a and <193>·rama, is the real apar<193>dha ç
(mistake) committed bythe buddhi. This can be rectified byretaining ç
the `I-consciousness,' to the exclusion of all that is not ``I''. ç
Then one experiences directly that one is Param<193>tman.
@S10N = Prakara<207>a 6 (6 verses)<R>ç
(Vi·e<218><193>pohaprakara<207>a)
@EMERGENCY = When a man loses his hand, his sense of `I-ness' in that ç
is lost. Similarly if one can drop off all the adjectives or qualities ç
that really do not belong to one's essential nature, he will realise ç
that he, as the knower, is the <193>tman.
@S10N = Prakara<207>a 7 (7 verses)<R>ç
(Buddhy<193>r<220><195>haprakara<207>a)
@EMERGENCY = The  <193>tman  knows  everything through the buddhi ç
(intellect) in which its consciousness is reflected. It is this s<193>k<218><200>-caitanya ç
(supervisory consciousness) that is the <193>tman, the same as Brahman.
@S10N = Prakara<207>a 8 (6 verses)<R>ç
(Mativil<193>panaprakara<207>a)
@EMERGENCY = Given in the form of a dialogue between the <193>tman ç
and the mind, this section teaches that all the apparent activities ç
of the j<200>v<193>tman are due to its wrong association with the ç
mind. In its essential nature, the j<200>v<193>tman is really the ç
<193>tman, pure and unattached.
@S10N = Prakara<207>a 9 (9 verses)<R>ç
(S<220>k<218>mat<193>vy<193>pit<193>prakara<207>a)
@EMERGENCY = This section describes that the <193>tman is extremely ç
s<220>k<218>ma (subtle) and also sarvavy<193>pi (all-pervading) by ç
using Upani<218>adic type of logic.
@S10N = Prakara<207>a 10 (14 verses)<R>ç
(D<216>·isvar<220>paparam<193>rthadar·anaprakara<207>a)
@SPACE1 = 
The <193>tman is pure consciousness, of the nature of d<216>k (the ç
seer) and has no object to be known. He is one without a second. This ç
is the main teaching of this prakara<207>a.
@SPACE = 
@S10N = Prakara<207>a 11 (16 verses)<R>ç
(®k<218>it<216>tvaprakara<207>a)
@SPACE1 = 
This section declares that consciousness is the natural and essential ç
characteristic of the <193>tman.
@SPACE = 
@S10N = Prakara<207>a 12 (19 verses)<R>ç
(Prak<193>·aprakara<207>a)
@SPACE1 = 
It is due to sunlight that one sees one's own body and not due to ç
the light of the body itself since it has no light of its own. Similarly ç
the mind that appears as the conscious knower, appears so only due ç
to the reflection of the pure consciousness in it.
@SPACE = 
@S10N = Prakara<207>a 13 (27 verses)<R>ç
(Acak<218>u<218><219>vaprakara<207>a)
@SPACE1 = 
This section tries to prove that the <193>tman in his essential nature ç
is beyond the senses, vital airs, mind, intellect, and even the body. ç
He is eternal, ever pure consciousness. Due to ignorance, people identify ç
themselves with these non-Self items and suffer.
@SPACE = 
@S10N = Prakara<207>a 14 (50 verses)<R>ç
(Svapnasm<216>tiprakara<207>a)
@SPACE1 = 
This section proves that the <193>tman is dra<218><219><216> (the ç
seer) and is the ever-present reality. Everything else is d<216>·ya, ç
the seen, and hence non-eternal.
