@S10N = Prakara<207>a 15 (54 verses)<R>ç
(N<193>nyadanyatprakara<207>a)
If Brahman and j<200>va are different and if j<200>va becomes Brahman, ç
then it dies, giving rise to Brahman. But who is it that becomes Brahman, ç
if it were not already so? Hence one has to accept that the j<200>va ç
has always been Brahman. This is the gist of this section.
@S10N = Prakara<207>a 16 (74 verses)<R>ç
(P<193>rthivaprakara<207>a)
The <193>tman is the j<210><193>t<216>, the knower; all else, including ç
the body-mind complex is the j<210>eya (the known). They†the body, ç
the senses, the mind and the intellect†are all lighted up by the light ç
of the <193>tman. That is why they are able to function. This is the ç
summary of this prakara<207>a.
@S10N = Prakara<207>a 17 (89 verses)<R>ç
(Sa<221>ya<209>matiprakara<207>a)
This section emphasises that the greatest benefit one can get in life ç
is from <193>tmaj<210><193>na or knowledge of the <193>tman. This ç
again is possible only through the Vedas. The nature of this knowledge ç
is that one is eternal, pure consciousness.
@S10N = Prakara<207>a 18 (233 verses)<R>ç
(Tattvamasiprakara<207>a)
This is the longest section, culminating in the highest philosophy ç
of Advaita Ved<193>nta, by a detailed exposition of the mah<193>v<193>kya ç
tat-tvam-asi (vide Ch<193>ndogya Upani<218>ad 6.8.7 to 6.16.3).
@S10N = Prakara<207>a 19 (28 verses)<R>ç
(Bhe<218>ajaprayogaprakara<207>a)
Also known as °tmamanassa<221>v<193>da- prakara<207>a, it is cast ç
in the form of a conversation between the Self and the mind, the former ç
advising the latter about the true nature of himself.
On the whole, this is a comprehensive and authentic treatise of Advaita ç
Ved<193>nta.
R<193>mat<200>rtha (17th Century <MS>A.<|>D.<D>) has written a lucid ç
commentary called Padayojanik<193> on the whole work.
Two more glosses†by °nandaj<210><193>na and Bodhanidhi†are known to ç
exist though not printed till now.
@NT = up<193>dhi
@N1 = (`limiting adjunct')
Any adventitious object which apparently influences something else ç
to appear differently from what it really is, is `up<193>dhi'. For ç
instance, a red flower near a colourless crystal makes it appear as ç
red. The red flower is called an `up<193>dhi' for the crystal. Similarly ç
the body-mind complex is an up<193>dhi for the <193>tman (the individual ç
soul) making it appear as the j<200>va (the limited transmigrating ç
self) and the world is an up<193>dhi for Brahman, the Absolute, who ç
has nothing to do with creation.
@NT = up<193>dhy<193>ya
@N1 = (`teacher [of Vedas]')
An up<193>dhy<193>ya is a Vedic teacher who teaches the Veda or a ç
part of it, for remuneration. He is also called adhy<193>paka.
An up<193>dhy<193>y<193> is a lady teacher of the Vedas, whereas the ç
wife of an up<193>dhy<193>ya is known as up<193>dhy<193>y<193>n<200> ç
or up<193>dhy<193>y<200>.
Other words of similar purport are: ·rotriya or ch<193>ndasa (scholar ç
well-versed in the Vedas); <193>c<193>rya (one who teaches the Vedas ç
along with their meaning); guru (who performs the sa<221>sk<193>ras ç
or the sacraments).
@NT = up<193>karma
See under <MS>UPANAYANA<D>.
@NT = Upakosala
Upakosala†also known as K<193>ma-l<193>yana†was a disciple of the ç
sage Satyak<193>ma J<193>b<193>la. He served his guru for twelve years, ç
tending his sacred fires with great care and devotion. Though Satyak<193>ma ç
J<193>b<193>la educated and sent away his other disciples, he did ç
not condescend to teach Upakosala. Even the sympathetic intervention ç
of his wife in favour of Upakosala had no effect. Then Upakosala started ç
fasting out of dejection. The Vedic fires which he had devotedly served, ç
took pity on him and taught him that pr<193><207>a (the life force) ç
and the bliss one experiences in the region of the heart are Brahman.
Later on, Satyak<193>ma discovered that Upakosala had been taught ç
by the Vedic fires. He completed the same by teaching him about the ç
<193>tman, the seer in the eye (vide Ch<193>ndogya Upani<218>ad ç
4.10 to 4.15).
@NT = Upakosalavidy<193>
See <MS>VIDY°S<D>.
@NT = upakrama
@N1 = (`beginning')
See <MS><186>A£VIDHALI<177>GAS<D>.
@NT = upakurv<193><207>a-brahmac<193>rin
See <MS>NAI<186><187>HIKA-BRAHMAC°RIN<D>.
@NT = upala
See <MS>D<184><186>AD<D>.
@NT = upam<193>na
@N1 = (`comparison,' `simile')
See <MS>PRAM°ØAS<D>.
@NT = Upamanyu
Upamanyu was a disciple of the sage Dhaumya. He was entrusted with ç
the task of taking care of his guru's cows. Once he felt very hungry ç
and had nothing to eat. He ate the leaves of a poisonous shrub which ç
made him lose his eye-sight. Not knowing the way to return, he fell ç
into a dry well. There, he prayed to the twin deities, the A·vins ç
and regained his eyesight (vide Mah<193>bh<193>rata, °diparva 3).
The Li<209>gapur<193><207>a (107) gives the story of another Upamanyu, ç
the son of the sage Vy<193>ghrap<193>da. As a little boy, he pestered ç
his mother for milk. Due to extreme poverty, the mother gave him some ç
water mixed with a little flour since there was no milk. The boy refused ç
to drink it. As advised by the mother, he prayed to <185>iva and got ç
the rulership over the ocean of milk! It was he who composed a <185>ivasahasran<193>ma.
@NT = up<193><221>·ujapa
See <MS>JAPA<D>.
@NT = Upanayana
@N1 = (`additional eye')
@SB8.5 = What is Sa<221>sk<193>ra?
Hinduism declares that mok<218>a or liberation from the cycle of birth ç
and death is the final goal of life. It is the same as God-realisation, ç
resulting in the enjoyment of eternal bliss. Whatever effort is put ç
forth in that direction is called `s<193>dhana'. Our body and our ç
mind are the chief instruments in this endeavour. Sa<221>sk<193>ra ç
is nothing but the process of purifying and refining these instruments, ç
making them fit for s<193>dhana.
The word `sa<221>sk<193>ra' literally means `to do well'. A block ç
of stone when subjected to  `sa<221>sk<193>ra'  by  an  expert  sculptor ç
becomes a lovely image. Similarly rice, sugar and milk get converted ç
into a delicious pudding in the hands of an expert cook.
Basic materials like the block of stone, or, rice, sugar and milk, ç
are called `prak<216>ti'. When the stone-block is broken into pieces ç
or rice becomes putrefied ormilk gets sour, they become `vik<216>ti' ç
(`deformed'), become useless. We want sa<221>sk<216>ti and not vik<216>ti. ç
We want `sa<221>sk<193>ra' which can convert `prak<216>ti' into `sa<221>sk<216>ti' ç
and not its opposite, `vik<193>ra' (distortion, deformation).
@SB8.5 = Sixteen Sa<221>sk<193>ras
Such sa<221>sk<193>ras (called `sacraments') that purify and refine ç
a human being, making him fit for the life here and here- after, are ç
sixteen. Hence the term `<186>o<195>a·a-sa<221>sk<193>ras' (<218>o<195>a·a ç
= 16). Among them upanayana, viv<193>ha (marriage) and antye<218><219>i ç
(death-rites) are the most important ones.
@SB8.5 = Meaning of the Word `Upanayana'
`Upanayana' means `leading' the disciple to the guru or the Vedic ç
teacher (upa = near; nayana = leading, taking). Or, it can also mean ç
providing him with an `additional eye,' the `eye of knowledge and ç
wisdom' (upa = additional, nayana = eye). That is, in addition to ç
the two physical eyes he already has, to give him a third eye, that ç
of knowledge and wisdom, through proper education. Consequently, the ç
sacrament of the beginning of formal education too, has been called ç
by the same name, i.e., `upanayana'.
@NID = <+><+><+><|>`Mau<210>j<200>bandhana' and `Brahmopade·a' are two ç
other terms sometimes used to denote this sacrament. Since a girdle ç
made of the mu<210>ja grass is tied round the waist of the boy undergoing ç
the upanayana ceremony, to support the kaup<200>na or loin-cloth, ç
the ceremony itself is termed `Mau<210>j<200>bandhana'.
The word `Brahma' stands for the Vedas as also for the G<193>yatr<200>mantra ç
which contains their quintessence. Since, in this sa<221>sk<193>ra, ç
the G<193>yatr<200>mantra is taught to the novice, the word `Brahmopade·a' ç
is quite an appropriate expression for the rite also.
@SB8.5 = Important Steps of Upanayana
The novice undergoing upanayana is called `va<219>u'. The prescribed ç
age-limit for the va<219>u is between 7 and 16 years. It is best to ç
perform upanayana in the spring season (around March-April).
There are quite a few injunctions and steps in the process of the ç
upanayana ceremony. A few of them†the more important ones†may be set ç
out here.
On the day prior to the upanayana, the parents of the va<219>u should ç
perform the worship of Ga<207>e·a and the family deity.
On the day of the upanayana, the va<219>u and his mother are to eat ç
from the same leaf-plate. It is for the last time that they can eat ç
like this. It signifies the end of the childhood days of the va<219>u ç
and a life of unbridled conduct. Hereafter he cannot act and behave ç
as he likes, but should subject himself to socio-religious norms of ç
conduct.
Then, he has to get his head shaven, leaving a ·ikh<193> (tuft of ç
hair) at the appropriate place, take bath and wear a new set of dress ç
comprising kaup<200>na (loin- cloth), dhoti and valli (upper cloth). ç
A girdle made of mu<210>ja grass also should be worn round the waist. ç
It is this that is technically called mau<210>j<200>bandhana. This ç
indicates the beginning of a life of brahmacarya or self-control, ç
of which celibacy is the most important aspect.
Next  comes  the  wearing  of  the yaj<210>opav<200>ta or the sacred ç
thread. The <193>c<193>rya (chief priest) makes the va<219>u wear ç
it with appropriate mantras so that it hangs from the left shoulder ç
to the right loin.
This sacred thread comprises three strands of strings and the knot ç
resembles a cow in the sitting posture. At the time of the upanayana ç
a small piece of k<216><218><207><193>jina (skin of a black antelope) ç
is also tied to this sacred thread.
In the ancient days people used to wear the skin of a black antelope ç
or an upper cloth during yaj<210>as or sacrifices. The yaj<210>opav<200>ta ç
is a remnant of that practice. When the va<219>u wears it, he should ç
think, `From today my life is like a yaj<210>a or sacrifice. I will ç
dedicate it to the welfare and service of the society!' The three ç
strands stand for the three Vedas thereby reminding him that he has ç
to study them and incorporate their message in his life. They may ç
also represent purity and control of body, speech and mind, which ç
again should be dedicated to the service of the society.
The next step is holding the da<207><195>a or the staff made of pal<193>·a ç
wood (Butea frondoza).
@SPACE1 = 
Actually the va<219>u is expected to keepit throughout his student-life ç
as an inseparable companion. It stands for dama or control of the ç
sense-organs at the psychological level. In his day-to-day life at ç
the gurukula, it helps him to take care of the cows of the household ç
and also comes in handy in times of dangers as a weapon for self-protection.
After the va<219>u circumambulates the sacred fire and offers sacrificial ç
fuel into it, the <193>c<193>rya administers him certain vows. They ç
are: performing <193>camana (ceremonial sipping of water with certain ç
mantras) before any religious rite, control of speech, avoiding sleep ç
during the day and offering fuel sticks into the sacred fire and so ç
on.
Then comes `S<193>vitr<200> Upade·a,' the heart of the whole sacrament. ç
It means imparting the G<193>yatr<200>mantra. `Savit<216>' or `Savit<193>' ç
means God the creator. He is identified with the sun. He is the Supreme ç
Lord residing in the heart of the sun. Hence the real name of the ç
mantra is `S<193>vitr<200>mantra'. Since it was revealed to the sage ç
Vi·v<193>mitra, for the first time in the Vedic metre known as the ç
G<193>yatr<200>, the mantra itself has been identified with it and ç
has popularly come to be known as the `G<193>yatr<200>mantra'. The ç
<193>c<193>rya has to teach it to the va<219>u, little by little, ç
with proper intonation until he picks it up completely.
Next comes the offering of the fuel sticks into the duly consecrated ç
fire (that has already been prepared by the <193>c<193>rya) with proper ç
mantras signifying prayers for long life, brilliance, intellectual ç
acumen, general competence, name and fame as also (in course of time) ç
good offspring.
@SPACE1 = 
Last comes the begging of food by the va<219>u from his own mother ç
and other elderly ladies of the family. Since he has to beg his food ç
as long as he lives in the gurukula, this ritual begging is a trial ç
run as it were, for it. The food got by begging is to be offered to ç
the <193>c<193>rya first and consume only that given to him as his ç
share.
@SPACE = 
@S10N = SANDHY°VANDANA
@SB8.5 = Meaning of the Term
The junction between night and day (i.e., dawn) and that between day ç
and night (i.e., dusk) are called `sandhy<193>'. The former is known ç
as `pr<193>tassandhy<193>' and the latter as `s<193>ya<221>sandhy<193>'. ç
The worship of S<220>rya (the sun) to be performed during these two ç
periods is called `Sandhy<193>- vandana' (`obeisance to the Sun-god ç
during the periods of sandhy<193>'). In addition one more is added, ç
the `m<193>dhy<193>hnika', a rite that is to be performed during noon ç
when the sun is right above our head.
The va<219>u who has undergone the upanayana ceremony, as also the ç
house-holders (among the dvijas or those belonging to the first three ç
castes), are expected to perform this sandhy<193> ritual three times ç
a day, as a sacred duty.
These three†the pr<193>tassandhy<193>, the m<193>dhy<193>hnika and ç
the s<193>ya<221>sandhy<193>† have many steps in common. However, ç
in practice, only the first and the last have survived. The scriptures ç
have provided for this modification.
@SB8.5 = Various Steps
After taking bath and wearing the traditional religious dress (dhoti ç
and chadar or uttar<200>ya) one should apply the religious marks (like ç
the vibh<220>ti or the<220>rdhvapu<207><195>ra) as per one's family ç
traditions, on the forehead, and sit on the seat (kept aside and to ç
be used only for such religious purposes). Though there are differences ç
in the procedure and the various steps to be followed, as per differing ç
traditions, the six steps common to all will be delineated here. The ç
detailed procedure has to be learnt from the family priest or the ç
elders in the family.
These six steps are: <193>camana, pr<193><207><193>-y<193>ma, m<193>rjana, ç
arghyaprad<193>na, g<193>yatr<200>-japa and s<220>ryopasth<193>na.
@S10 = a)	°camana
°camana is the ceremonial sipping of water from the right hand cupped ç
in the shape of the face of a cow, to the chanting of appropriate ç
mantras like `Ke·av<193>ya sv<193>h<193>' and touching specified parts ç
of the body for ritual purification. This <193>camana is a general ç
purificatory act that precedes every religious undertaking.
@S10 = b)	Pr<193><207><193>y<193>ma
Pr<193><207><193>y<193>ma is control of the pr<193><207>ic energy ç
through the regulation of the breathing process as detailed in the ç
works on yoga. P<220>raka (inhalation), kumbhaka (retention) and recaka ç
(exhalation) are its three steps. The G<193>yatr<200>mantra along ç
with the vy<193>h<216>tis is used in pr<193><207><193>y<193>ma to ç
keep time. Pr<193><207><193>y<193>ma helps in the control of mind ç
also.
@S10 = c)	M<193>rjana
Literally, `m<193>rjana' means cleansing or purifying. It consists ç
of sprinkling of water on specified parts of the body with the mantra ç
`<193>po hi<218><219>h<193>....' This process will make the body ceremonially ç
pure and fit for the ritualistic act.
@S10 = d)	Arghyaprad<193>na
Any object fit for being offered in ritualistic worship is `arghya'. ç
However, in a more technical sense, it is the offering of water taken ç
in the two hands cupped together, by repeating the G<193>yatr<200>mantra ç
and addressing the Sun-god (i.e., Savit<193> or God the creator, in ç
the orb of the sun). This is just to show our gratitude to the Sun-god ç
who is our primary life-support.
@S10 = e)	G<193>yatr<200>japa
This is the most important part of the Sandhy<193> ritual. Its primary ç
steps are: karany<193>sa, a<209>gany<193>sa, dhy<193>na and japa.
`Ny<193>sa' means `to keep or to place'. It is aimed at filling the ç
fingers of the hand and other limbs like the head and heart with the ç
divine power of the deities.
Dhy<193>na is meditation on the deity as per the detailed description ç
given in the hymn (called `dhy<193>na·loka') while repeating it. The ç
goddess G<193>yatr<200> within the orb of the sun is the deity here.
After dhy<193>na comes japa or repetition of the G<193>yatr<200>mantra. ç
While doing japa, dhy<193>na on the form of the goddess should be ç
continued. It is better to repeat the mantra 1008 times, or at least ç
108 times per sitting.
@S10 = f)	S<220>ryopasth<193>na
Repeating the prayer addressed to the deity G<193>yatr<200> (in the ç
orb of the sun) in the standing posture, facing the sun, is `s<220>ryopasth<193>na' ç
(upasth<193>na = standing). This is the last rite of bidding farewell ç
to the goddess after having invoked her and satiated her through japa.
Apart from the sun, the mountain Meru is sometimes described as her ç
abode.
@S10N = UP°KARMA
In the ancient days, the brahmac<193>rins (Vedic students) used to ç
stay in the houses of their teachers and study the Vedas. After a ç
few months of study and a short holiday, when they resumed their study, ç
they were expected to perform a short ritual called `up<193>karma,' ç
signifying the restarting of their studies. The word `up<193>- karma' ç
means `upakrama' or `pr<193>rambha', or beginning.
Now-a-days, it has remained just as an annual ritual. The procedure ç
comprises the following steps: sa<209>kalpa (religious resolve), worship ç
of Ga<207>apati, oblations to nine deities like S<193>vitr<200>, Brahm<193> ç
and <185>raddh<193>, homa with a mixture of barley and curds with ç
some specific mantras from the <184>gveda, wearing of a new yaj<210>opav<200>ta ç
and discarding the old one, preferably in the waters of a river or ç
a tank.
The same mantra and procedure for changing the yaj<210>opav<200>ta ç
given here can be used at other times also, to discard a worn-out ç
or a dirty or a broken one and wear a new one.
@SPACE = 
@S10N = G°YATR®-MANTRA-JAPA
@SB8.5 = What is G<193>yatr<200>?
It is known as `G<193>yatr<200>' since it protects (= tr<193>yate) ç
one who chants it (=g<193>yantam) correctly as per the rules of Vedic ç
intonation. This is the etymological definition of the word.
It is also called `S<193>vitr<200>mantra' since it is a prayer addressed ç
to Savit<216> or God the creator. The Sun is also called Savit<216> ç
or Savit<193>, because it is due to him (or the power of God in him) ç
that the whole world and all of us, are able to live.
