This mantra was revealed for the first time to the sage Vi·v<193>mitra, ç
in a new metre called `G<193>yatr<200>'. Hence the mantra itself ç
came to be known as `G<193>yatr<200>mantra'. It is also called `S<193>vitr<200>-mantra' ç
since it concerns the deity Savit<216>.
@SB8.5 = The Mantra and Its Meaning
The first part of the mantra comprises the three vy<193>h<216>tis:
Om bh<220>r-bhuvas-suva<199> (O<221>, bh<220><199>, bhuva<199>, suva<199>).
When the G<193>yatr<200> is used for pr<193><207><193>-y<193>ma, the ç
number of vy<193>h<216>tis is increased from3 to 7.
Literally `vy<193>h<216>ti' means `uttering'. Brahm<193> the creator, ç
is said to have uttered these at the beginning of creation. Hence ç
the appellation `vy<193>h<216>tis'.
The second part is the S<193>vitr<200>mantra:
tat savitur-vare<207>yam, bhargo devasya dh<200>mahi, dhiyo yo na<199> ç
pracoday<193>t<F49P12W1>f<F255P255D>
Sometimes,  a  third  part  called `G<193>yatr<200>-·iras' is also ç
added. Its use also is in the process of pr<193><207><193>y<193>ma. ç
It is:
Om <193>po jyot<200> raso'm<216>tam brahma bh<220>rbhuvassuvarom<F49P12W1>f
However, in the mantra used for japa, only the three vy<193>h<216>tis ç
and the S<193>vitr<200>-mantra are utilised.
A general summary of the mantra may now be given:
We meditate upon the divine effulgence of Savit<193> (God, the creator ç
of the three worlds, the earth, the heaven and the intervening space ç
as indicated by the three vy<193>h<216>tis) signified by the Pra<207>ava ç
or O<209>k<193>ra (and existing in the orb of the sun). May he impel ç
our intellects in the right direction (i.e., towards himself)!
Whatever we want to achieve in our life, the first and foremost requirement ç
is that our intellect, our understanding, must be in an excellent ç
form! Repetition of the G<193>yatr<200>mantra with faith and reverence ç
will help not only in cleansing the mindbut also in achieving greater ç
concentration.
The mode and method of its repetition must be learnt from a competent ç
teacher.
@SB8.5 = Pura·cara<207>a
Pura·cara<207>a is the technical name given to a particular (ceremonial) ç
mode of repeating the G<193>yatr<200>mantra in order to secure certain ç
special fruits or results. The following are the usual steps involved ç
in it:
Daily  rituals  like  the  Sandhy<193>- vandana, worship of the goddess ç
G<193>yatr<200>, japa of G<193>yatr<200>mantra, homa (fire ritual), ç
tarpa<207>a (offering of water ceremonially) and feeding of the br<193>hma<207>as.
It should be undertaken, however, under the guidance of experts.
@NT = Upani<218>ads
@SB = 1.	General Introduction
If there is one mass of scriptures that has inspired and sustained ç
the Hindus over the millennia, it is the Upani<218>ads. By advocating ç
the ultimate triumph of the spirit over matter, of man over nature, ç
the Upani<218>ads have created, strengthened  and  preserved  a  great ç
tradition of spirituality. This they have done, not only by a fearless ç
spirit of inquiry to its logical conclusions, but also by intuitive ç
mystical experiences beyond the ken of the intellect, these experiences ç
almost always converging to a unitive principle. No school of thought, ç
no religious movement, of the subsequent periods in the  history  of  India  has  remained ç
untouched  by  their  influence,  if  not pervaded by them. In fact, ç
many of theseschools and movements could gain respectability or acceptance ç
only because they trode the path lighted up by the Upani<218>ads.
Research scholars of Indian thought have discovered the influence ç
of the Upani<218>ads on the religio-cultural life of other nations ç
far beyond the boundaries of India, whether it is Japan, China and ç
Korea in the east or Central Asia in the west.
Hindu religious tradition has always accorded the Upani<218>ads the ç
status of the highest authority since it has unquestioningly been ç
accepted as <185>ruti, the Revealed Word.
@SPACE = 
@SB = 2.	Meaning of the Word `Upani<218>ad'
@SPACE = 
The word `Upani<218>ad' is derived from the verbal root sad which ç
has several meanings:  loosening,  movement  and annihilation. Putting ç
all these three senses together, the word `Upani<218>ad' refers to ç
that divine knowledge or wisdom which loosens the bonds of sa<221>s<193>ra ç
(transmigratory existence) of a being, annihilates his aj<210><193>na ç
or the ignorance of his real nature, and leads him to Brahman or God, ç
the Absolute. The book or the scriptural work that teaches this wisdom ç
is also called `Upani<218>ad'.
The word may also mean `sitting devotedly near'. Hence it represents ç
the`secret teaching, of spiritual wisdom' imparted in private to ç
worthy pupils, but jealously guarded from the unworthy ones.
@SB = 3.	Date of Composition
The orthodox view is that the Upani<218>ads are Revealed Word. They ç
are revealed by God himself at the commencement of each cycle of creation ç
to the worthy few. Hence they are eternal.
However, treating them as books of spiritual wisdom, can we assign ç
any date or period, in relation to human history as known till now? ç
Attempts in this direction have rather been frustrating, thanks to ç
that peculiar trait of the Hindu mind which accords much greater importance ç
to the principle rather than to the person or the period.
The Upani<218>ads have been an integral part of the Vedas. Hence, ç
a date assigned to them can as well hold good for the Upani<218>ads ç
also. The date of the <184>gveda has varied from 4500 <MS>B.<|>C.<D> ç
(B.<|>G. Tilak) and 2400 <MS>B.<|>C.<D> (Hang) to 1200 <MS>B.<|>C.<D> ç
(Max M<F20W1>Å<F255D>ller). Modern European scholars assign the period 700 ç
<MS>B.C.<D>-<|>600<|><MS>B.<|>C.<D> to the Upani<218>ads assuming a ç
gradual evolution of the philosophical ideas from the period of the ç
Vedic hymns to that of the °ra<207>yakas and the Upani<218>ads. B.<|>G. ç
Tilak, on the basis of an astronomical data provided in the Maitr<193>ya<207><200>ya ç
Upani<218>ad, has however, assigned 1900 <MS>B.<|>C.<D> as the date ç
of that Upani<218>ad. Hence, according to him and the scholars who ç
concur with him, the Upani<218>ads belong to the period 2500 <MS>B.<|>C.<D><192>2000 ç
<MS>B.<|>C.<D>
@SB = 4.	Nature of Composition
From among the extant Upani<218>ads, only ten to fifteen are considered ç
to be the older ones. They are the basic sources of ancient Hindu ç
philosophy.
However, do all these Upani<218>ads teach a single system of philosophy? ç
Or,do they contain several, mutually conflicting, systems?
The orthodox Hindu tradition has always considered the entire body ç
of the Upani<218>adic literature as one unit (`<185>ruti') and hence ç
teaching one philosophy. Though  this  philosophy  may  contain several  aspects,  they  always  form  a ç
homogeneous unit.
@SPACE1 = 
A look at the different and divergent teachings of these Upani<218>ads ç
does not easily convince us about the soundness of the orthodox standpoint. ç
The traditional commentators have, however, solved this problem by ç
sticking to one view as the teaching of the Upani<218>ads and explaining ç
(explaining away?) the others in a way that suits their interpretation.
Could it be that, over the centuries, many vital links have been lost, ç
and what we now have are only fragments of the original works leading ç
to this dichotomy of views? Though this is a plausible explanation, ç
there is no clinching evidence to prove it.
Or, can we say that the various sages that we come across in the Upani<218>ads† ç
like Gautama °ru<207>i, Y<193>j<210>avalkya, <185>veta-ketu or Raikva†were ç
great thinkers and mystics in their own right, who have given independent ç
views, based on their own logic and experience? The Truth, Brahman ç
(the Infinite, the Absolute), is too great to be known exhaustively ç
by anyone. One can get only a glimpse of the same, like the six blind ç
men touching the same elephant. Hence, could it not be that the views ç
of these sages, though apparently different, reflect the several facets ç
of the same Brahman?
At the most, these are all intelligent guesses and may continue to ç
remain so for quite some time!
@SPACE = 
@SB = 5.	Number and Classification
@SPACE = 
The number of works that go by the name `Upani<218>ad' and available ç
in print today exceeds 200. The Muktikopani<218>ad gives a list ç
of 108 Upani<218>ads. <185>a<209>kara (<MS>A.D.<D> 788<192>820), ç
the earliest commentator, has chosen only ten Upani<218>ads to expound. ç
He refers to a few more in his commentary on the Brahmas<220>tras. ç
R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137) has chosen, in addition, ç
two more. Considering the ones chosen by them as more ancient and ç
authoritative we can now list them (in the alphabetical order) as ç
follows:
@SPACE = 
@IN2 = Aitareya Upani<218>ad<R>ç
B<216>had<193>ra<207>yaka Upani<218>ad<R>ç
Ch<193>ndogya Upani<218>ad<R>ç
®·<193>v<193>sya Upani<218>ad<R>ç
J<193>b<193>la Upani<218>ad<R>ç
Kaivalya Upani<218>ad<R>ç
Ka<219>ha Upani<218>ad<R>ç
Kau<218><200>taki Upani<218>ad<R>ç
Kena Upani<218>ad<R>ç
M<193><207><195><220>kya Upani<218>ad<R>ç
Mah<193>n<193>r<193>ya<207>a Upani<218>ad<R>ç
Mu<207><195>aka Upani<218>ad<R>ç
Pra·na Upani<218>ad<R>ç
<185>vet<193>·vatara Upani<218>ad<R>ç
Taittir<200>ya Upani<218>ad<R>ç
Vajras<220>cik<193> Upani<218>ad
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE = 
As regards the classification, different scholars have adopted different ç
methods. Some have grouped them in the chronological order, considering ç
the B<216>had<193>-ra<207>yaka, the Ch<193>ndogya and the Taittir<200>ya ç
as more ancient than the Ka<219>ha or the <185>vet<193>·vatara. ç
Others have classified them according to the style of language, as ç
Upani<218>ads in prose or in poetry. Such methods of classification ç
do not help us much in studying them.
Most of the Upani<218>ads, outside the list given above, belong to ç
a much later period in our history and were written to propagate specific ç
cults and sects. The nomenclature `Upani<218>ad' was conveniently ç
added to them to gain respectability, acceptance and authority in ç
the orthodox circles or among the followers. However, it must be conceded ç
that these Upani<218>ads also, though sectarian in character, have ç
contributed quite a lot to the propagation of popular religion and ç
ethics as also to the maintenance of the Ved<193>ntic spirit among ç
the people.
These minor Upani<218>ads are sometimes grouped as follows:
@SPACE = 
a)<+><+>Ved<193>nta Upani<218>ads
@SPACE1 = 
b)<+><+><185>aiva Upani<218>ads
@SPACE1 = 
c)<+><+><185><193>kta Upani<218>ads
@SPACE1 = 
d)<+><+>Vai<218><207>ava Upani<218>ads
@SPACE1 = 
e)<+><+>Yoga Upani<218>ads
@SPACE1 = 
f)<+><+>Sa<221>ny<193>sa Upani<218>ads
@SPACE = 
The Ved<193>nta Upani<218>ads follow the beaten track of the major ç
Upani<218>ads as far as the general principles are concerned. The ç
<185>aiva, the <185><193>kta and the Vai<218><207>ava Upani<218>ads ç
deal with the respective cults of <185>iva, Dev<200> and Vi<218><207>u. ç
The Yoga Upani<218>ads supply a lot of information about Ha<219>hayoga ç
and R<193>jayoga based on the Yogas<220>tras of Pata<210>jali and ç
other works. The Sa<221>ny<193>sa Upani<218>ads deal exclusively with ç
monasticism, its ideals and practices.
@SB = 6.	Sanskrit Commentaries
By its very definition, an Upani<218>ad is an esoteric work, recondite ç
in nature and spirit. The language is archaic. Many of the concepts, ç
being closely allied to the sacrificial religion of the Sa<221>hit<193>s ç
and the Br<193>hma<207>as, are unintelligible to us, removed as we ç
are, by millennia, fromthose rituals or ideas. Hence it is impossible ç
to understand them, much less, get a consistent view of them, without ç
an authoritative and reliable commentary. <185>a<209>kara (<MS>A.<|>D.<D> ç
788-820) is the earliest and the first to comment upon them. His bh<193><218>yas ç
or commentaries, further elucidated by the <219><200>k<193>s or glosses ç
of °nandagiri (13th century) are invaluable source books to unlock ç
the wisdom of the Upani<218>ads.
@EMERGENCY = R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137) has not commented ç
upon any of the Upani<218>ads though he has tried to amplify some ç
of their concepts in his Ved<193>rthasa<209>graha. Ra<209>ga-r<193>m<193>nuja ç
(circa <MS>A.<|>D.<D> 1600) has completed the work by commenting on ç
all the major Upani<218>ads. Madhva (<MS>A.<|>D.<D> 1197-1276) has ç
written brief commentaries on all the ten ancient Upani<218>ads upon ç
which some like R<193>ghavendra T<200>rtha (<MS>A.<|>D.<D> 1595-1671) ç
have written glosses.
Some commentators have chosen to write only on certain Upani<218>ads. ç
The ®·<193>v<193>syopani<218>ad has attracted the attention of many ç
scholars like Brahm<193>nanda Sarasvat<200>, <185>a<209>kar<193>nanda ç
(14th cent.), Uva<219><193>rya (11th cent.) as also Ved<193>nta-de·ika ç
(<MS>A.<|>D.<D> 1268-1370) who have not chosen to comment on the other ç
Upani<218>ads.  R<193>ghavendra  T<200>rtha  has commented on the ç
®·a, Kena, Ka<219>ha, Pra·na, Mu<207><195>aka and M<193><207><195><220>kya ç
following Madhva's line of interpretation. A later writer, Upani<218>ad ç
Brahma Yog<200>ndra, has done remarkable work by commenting on most ç
of the minor Upani<218>ads.
@SB = 7.	Philosophy of the Upani<218>ads
The thought current of the Upani<218>ads is, in a way, a continuation ç
of that in the Br<193>hma<207>as and the °ra<207>yakas. However, the ç
trend is definitely against ritualism and strongly favours up<193>san<193> ç
(meditation) and j<210><193>na (knowledge).
In the more philosophical portions of the Upani<218>ads, the discussions ç
generally centre round the fundamental cause of the world, if there ç
is one, and its nature as also its evolution into this world. This ç
cause is usually called `Brahman.'
As against this, there is a parallel mode of enquiry, into the existence ç
or otherwise, of a permanent subjective entity behind the body-mind ç
complex. This is called `<193>tman' (the Self or the soul).
Is this <193>tman one or many? Is it finite in size or infinite? Is ç
it identical with Brahman or different? Though the Upani<218>ads discuss ç
these questions, there does not appear to be a single answer. Different  viewpoints  seem  to  exist. ç
However, the orthodox Ved<193>ntic schools struggle to present only ç
one view as the right one to the exclusion of the others.
Destiny of the living beings here and hereafter, including some eschatological ç
questions, form another topic of the Upani<218>ads. Ignorance of one's ç
real nature as the cause of bondage and its eradication through the ç
practice of certain virtues like self-control and speaking the truth ç
are also touched upon.
A brief summary of these teachings may now be given.
@S10N = BRAHMAN
The basic cause of the universe, the cause of all causes, is called ç
`Brahman' by the Upani<218>ads. °tman, Sat, Ak<218>ara. °k<193>·a ç
and Bh<220>m<193> are the other appellations used for this Brahman. ç
The world rises out of him, is supported by him and gets dissolved ç
back into him. He is omniscient, omnipotent and omnipresent. He is ç
greater than the greatest, smaller than the smallest and is also the ç
inmost Self of all. He is immanent in this world even as salt is, ç
in saline water. He is beyond all wants and limitations. He is the ç
lord as well as the substratum of the whole creation. He sees, hears ç
and knows although none can see or hear or know him. He is the very ç
personification of all the great virtues to their perfection. It is ç
he who responds to the prayers of his votaries and grants them whatever ç
they seek. He is the ultimate goal of all.
To facilitate meditation upon him, the Upani<218>ads sometimes describe ç
him as a Puru<218>a (the divine being in the human form), bright and ç
brilliant, of golden hue, with all parts of his body of golden colour ç
and his eyes resembling a fully bloomed red lotus. Fire is his head, ç
the sun and the moon are his eyes, the quarters are his ears, the ç
Vedas are his speech and the earth is his feet. Sometimes he is also ç
described as having thousand heads, thousand eyes and thousand feet, ç
thereby stressing his omnipresent cosmic form. This <|>form <|>recommended ç
<|>for <|>meditation is  the  Aupani<218>ada-Puru<218>a  (the  Being ç
described in the Upani<218>ads).
@S10N = °TMAN
When a person dies, is there anything in him that survives and continues ç
to live on? What is that, impelled by which, the senses and the mind ç
of a living person are active? Such inquiries by the sages of the ç
Upani<218>ads have led to the establishment of the <193>tman, the ç
soul or the Self, as the abiding spirit behind the body and the mind ç
of every living being.
This <193>tman is neither born nor does he die with the birth and ç
the death of the body. He is unborn and eternal. Heisdifferent from ç
the body, the senses, the vital airs, the mind and the ego-sense and ç
is ever free. All of them are enlivened by him, made to work by him, ç
for him.Thedefects and the infirmities in them, or even their loss, ç
can never affect him.
However, it is also a fact of experience that this <193>tman has been ç
encased and bound in this corporeal frame and has lost much of his ç
freedom. In this state, he is called `j<200>v<193>tman' or simply ç
the `j<200>va'. The answer to the question as to why and how he has ç
come to such a pass is `karma,' the inexorable consequence of his ç
past actions. For the question, how and when the very first karma ç
started this chain of bondage, there is no answer, since the Upani<218>ads ç
accept creation as an eternal process, without beginning or end.
@SPACE1 = 
His involvement in the cycle of birth and death, and consequent suffering, ç
has been called `sa<221>s<193>ra.' Mok<218>a or liberation from this ç
bondage of sa<221>s<193>ra has been presented before him as the goal ç
of his life. And, this can be achieved by j<210><193>na or knowledge ç
and, bhakti or devotion, which includes up<193>san<193> or meditation. ç
Karma or action as prescribed in the scriptures is an aid to this ç
mok<218>a.
@S10N = CREATION
@EMERGENCY = Though Brahman is the permanent substratum of this world ç
and <193>tman is our essential nature, we cannot ignore this world ç
in which we live and move and have our being as it were. For all practical ç
purposes it is very real to us. And, even our struggles or attempts ç
for mok<218>a have to take place only in this world. Hence, it is ç
necessary to know about it, how it came into being, how it is sustained ç
now and its ultimate destiny.
In the beginning, Brahman alone† also called `°tman' or `Sat'†existed, ç
as the one without a second. He decided to become many. He then created ç
out of himself, <193>k<193>·a (sky or space or ether), v<193>yu (air), ç
agni or tejas (fire), ap (water) and p<216>thv<200> (earth). A permutation ç
and combination of these five elements, with Brahman associated at ç
every stage, has resulted in this world. Later, Brahman entered into ç
this creation as the antar-y<193>min or the inner controlling spirit.
According to other descriptions, the original substances created were ç
only three (tejas, ap and anna or earth) or even two, rayi (moon or ç
anna or matter) and pr<193><207>a (sun or fire or energy or spirit). ç
By a combination of these, in different proportions, this world came ç
into being. It is ever under his control. Nay, it is non-different ç
from him.
Even after being created out of†or, emerging out of†Brahman, this ç
world continues to be in him. It will merge backin him at the time ç
of pralaya or dissolution.
With  regard  to  the  relationship between Brahman and the world, ç
two views seem to exist in the Upani<218>ads. According to one view†known ç
as Saprapa<210>cav<193>da†since the world is an evolute of Brahman, ç
it is also Brahman. The other view†called as Ni<218>prapa<210>cav<193>da†denies ç
the world an existence of its own and asserts the existence of Brahman ç
alone.
@S10N = BONDAGE AND LIBERATION
Some Upani<218>ads picture the j<200>v<193>tman and the Param<193>tman ç
(the Supreme Self, Brahman as the indwelling spirit) as two birds ç
perching on the same tree (the body). The former eats the fruits of ç
the tree (results of karma)†some sweet and some bitter†and experiences ç
joy and sorrow. The latter is sitting majestically, ever calm and ç
collected, never touching those fruits. When the j<200>v<193>tman ç
realises the greatness of Param<193>tman, he becomes free from all ç
sorrow and suffering.
Though the question, how the everfree <193>tman became the j<200>va, ç
has not been answered by the Upani<218>ads, they have given several ç
modes of s<193>dhana or spiritual exercises by which the j<200>va ç
can recover his original state.
A s<193>dhaka or a spiritual aspirant should first cultivate certain ç
moral and ethical virtues as the first step. Through discrimination ç
he should understand that the Vedic rituals can never lead him to ç
the eternal Truth and hence renounce them. He must be ever ready to ç
reject the preyas (the pleasant) and choose the ·reyas (the good). ç
By eschewing evil conduct and by practising self-control, he should ç
turn back his mind from outside, into himself, the region of the heart, ç
the seat of the <193>tman, and meditate on it. He should show compassion ç
to all the living beings. He should try to give them what they need ç
and should never be greedy. He must be vigilant forever and should ç
always speak the truth and act according to dharma or righteousness, ç
by following thescriptural injunctions. Study of the Upani<218>ads,  performing  austerities  and ç
observing brahmacarya or celibacy are also invaluable aids in his ç
s<193>dhana.
He should approach a competent guru or spiritual teacher in all humility ç
and learn the truth about the <193>tman from him, through proper questioning ç
and sev<193> or service to him.
The Upani<218>ads make it incumbent onthe guru to teach spiritual ç
wisdom to a worthy disciple, after testing him if necessary.
The disciple should then practise manana (reflection) and nididhy<193>sana ç
(meditation) on the <193>tman which will result in anubh<220>ti or ç
realisation.
What is the nature of the spiritual experience that an aspirant gets ç
when he realises the <193>tman? He sees all beings in himself and ç
himself in all. Hence he feels neither special attraction nor repulsion ç
for others. Behind every thought of his, he is able to feel the power ç
of the <193>tman, the pure consciousness. He clearly perceives that ç
all the bonds of his heart which had him tied down to this mundane ç
existence, have broken down. He experiences great joy and bliss within ç
himself. When he directs his attention outside, there too he sees ç
the same spirit, the <193>tman, the Brahman.
@SPACE1 = 
The bliss he experiences is incomparably superior to any other happiness ç
one can get in this world. And he will never have any type of regret ç
for anything in life. He may even roam about the world in a joyous ç
state, declaring his experiences for the benefit of others.
@EMERGENCY = When such a one, the j<200>vanmukta (one who is liberated ç
even while living here in this body), gives up his body, what happens ç
to him?
@EMERGENCY = According to one view, his physical body and the subtle ç
body disintegrate at death and get absorbed into the five elements. ç
And, he gets merged in Brahman, like a river entering into the ocean. ç
Losing his separate identity, he attains complete and perfect unity ç
with Brahman.
However, a large body of the Upani<218>adic lore propounds the theory ç
of the  liberated  soul  travelling  by  the Arcir<193>dim<193>rga ç
or the Bright Path (also called Devay<193>na and Uttar<193>ya<207>a) ç
to the Brahmaloka (also known as Satyaloka) and reside there permanently ç
in infinite peace and bliss. The various stations on the path are ç
fire, day, bright fortnight, the six months of the northern solstice, ç
the year, the sun, the moon and the lightning. All these actually ç
represent the guardian deities of these stations. From the last station, ç
the vidyut or lightning, an  `am<193>nava  puru<218>a,'  a  non-human ç
(divine) being, leads the liberated soul to the Brahmaloka.
@SPACE1 = 
Is the Brahmaloka a state of inner experience or an actual world to ç
which the liberated soul repairs? Most of the Upani<218>ads contain ç
practically no or very scanty details. The Ch<193>ndogya (8.5.3) ç
describes it as a world, third from this earth, wherein there are ç
two huge lakescalled Ara and Øya. There is also a smaller reservoir ç
of food-juice known as Airammad<200>ya. Somasavana, a peepul tree ç
and a city called Apar<193>jit<193>, containing a golden hall are ç
also there. The Kau<218><200>taki Br<193>hma<207>opani<218>ad (1.3,<|>4 ç
and 5) gives a more picturesque description which adds a river Viraj<193>, ç
two doorkeepers (Indra and Praj<193>pati), a throne called Vicak<218>a<207>a ç
and a couch by name Amitaujas. Five hundred celestial nymphs greet ç
the liberated soul and adorn him. The fragrance and flavour of Brahm<193> ç
enters him at the appropriate state of his entrance.
Anyone reaching Brahmaloka will not return to mundane existence.
@S10N = ESCHATOLOGY
What happens to a person who dies without realising the <193>tman/Brahman? ç
This question too has been discussed in the Upani<218>ads.
Those who have performed sak<193>ma-karmas (desire-motivated actions) ç
or have practised lower kinds of up<193>san<193>s get their desires ç
fulfilled. Some of them go to svargaloka* (heaven) from where they ç
will return to this world after exhausting the results of their good ç
deeds. Sometimes, this movement is described as through the Dh<220>m<193>dim<193>rga ç
(the path of smoke) (also called Dak<218>i<207><193>yana) wherein ç
the soul is led to the Candraloka (the world of moon) after passing ç
through smoke, night, the dark fortnight and the six months of the ç
southern solstice. After exhausting the result of meritorious deeds ç
he returns again to this earth, through the sky, rain, vegetation ç
and living beings.
Those who know neither of these two paths, return again and again ç
and may even be reborn at the subhuman levels, as animals and worms.
As related to this topic, ideas about karma and rebirth are also found ç
in the Upani<218>ads here and there. A doer of pu<207>yakarma or good ç
deeds attains good results and a doer of p<193>pakarma or sinful deeds ç
gets bad results. Hence human beings are advised not to harm anyone.
@S10N = VIDY°S OR UP°SAN°S
An important aspect of s<193>dhana as enunciated in the Upani<218>ads ç
is `vidy<193>' or up<193>san<193>. A man deeply devoted to†or even ç
addicted to†the religion of yaj<210>as or Vedic sacrifices, has to ç
be led gradually, first to contemplation and then to j<210><193>na ç
(knowledge or direct experience) of the <193>tman in course of time, ç
because that is the ultimate goal of life. And, that is the only way ç
to mok<218>a.
These up<193>san<193>s have taken two forms. In the first group, the ç
s<193>dhaka is advised to imagine the various parts of a ritual and ç
then superimpose certain ideas on them. For instance, the B<216>had<193>ra<207>yaka ç
Upani<218>ad (1.1.1, 2) advises one to meditate upon the horse, to ç
be offered in the A·vamedha sacrifice, by thinking that it is Praj<193>pati, ç
the Lord of beings. This up<193>san<193>, which can be practised even ç
by those who are not competent to perform the A·vamedha sacrifice, ç
gives the same fruits as the real A·vamedha itself.
In the second group of up<193>san<193>s certain known objects like ç
n<193>ma (name), v<193>k (speech), bala (strength) or manas (mind) ç
are recommended to be meditated upon  as  Brahman,  by  imagining  or ç
discovering some similarity between that object and Brahman. Such ç
up<193>san<193>s gradually help the aspirant's mind to be raised to ç
the highest level, Brahman, andgive him the much needed spiritual ç
experience.
The number of such vidy<193>s or up<193>san<193>s which are spread ç
out throughout the Upani<218>ads is quite large and may be considered ç
as 32.
The following list gives a few of the more important ones and the ç
Upani<218>ads in which they occur.
@L5 =      Vidy<193>	  Upani<218>ad<R>ç
Ak<218>ipuru<218>a Vidy<193>	Ch<193>ndogya 4.15.1.<R>ç
Antar<193>ditya Vidy<193>	B<216>had<193>ra<207>yaka 5.52.<R>ç
Bh<220>ma Vidy<193>	Ch<193>ndogya 7.23,<|>24,<|>25.<R>ç
Dahara Vidy<193>	Ch<193>ndogya 8.1.<R>ç
G<193>yatr<200> Vidy<193>	Ch<193>ndogya 3.12.<R>ç
Madhu Vidy<193>	Ch<193>ndogya 3.1 to 11.<R>ç
Pa<210>c<193>gni Vidy<193>	Ch<193>ndogya 5.3 to 10.<R>ç
	B<216>had<193>ra<207>yaka 6.2<R>ç
Parya<209>ka Vidy<193>	Kau<218><200>taki 1.<R>ç
Pr<193><207><193>gnihotra Vidy<193>	B<216>had<193>ra<207>yaka 5.9.<R>ç
Pratardana Vidy<193>	Kau<218><200>taki 3.<R>ç
Puru<218>a Vidy<193>	Ch<193>ndogya 3.16, 17.<R>ç
Sad Vidy<193>	Ch<193>ndogya 6.2.1, 2.<R>ç
Sa<221>varga Vidy<193>	Ch<193>ndogya 4.3.<R>ç
<185><193><207><195>ilya Vidy<193>	Ch<193>ndogya 3.14.<R>ç
Udg<200>tha Vidy<193>	B<216>had<193>ra<207>yaka 5.8.1.<R>ç
Upakosala Vidy<193>	Ch<193>ndogya 4.10 to 15.<R>ç
Vai·v<193>nara Vidy<193>	Ch<193>ndogya 5.11 to 17.
These vidy<193>s were taught privately to deserving candidates after ç
testing themfor their competence. That is why the information available ç
either in theUpani<218>ads or in their commentaries regarding them ç
is very meagre. It is likely that they provided the basic materials ç
for the later schools of various kinds of yoga.
@SB = 8.	Civilisation and Culture during the<R>ç
	Age of the Upani<218>ads
Gleaning through the various Upani<218>ads it is possible to have ç
a fairly good idea of the type of society that existed during the ç
period of the Upani<218>ads.
The country extended up to G<193>ndh<193>ra (Afghanistan)  in  the  north-west,  and ç
included several kingdoms like Madra (Sailkot), Kuru (Delhi), Kekaya ç
(Punjab), P<193><210>c<193>la (Bareilly, Kanauj in Uttar Pradesh), ç
Kosala (Ayodhya in Uttar Pradesh), Videha (Tirhut in Bihar), Kau·<193>mbi ç
(Kosam, in Uttar Pradesh) and K<193>·<200>. The kings who ruled over ç
these countries were all k<218>attriyas who were experts in warfare ç
and administration, asalso in the Vedic lore. In fact, they were ç
the traditional custodians of some types of esoteric sciences. They ç
not only sheltered learned br<193>hma<207>as and sages but also strove ç
to propagate the Vedic dharma. They were ruthless in enforcing the ç
highest standards of satya (truth) and dharma (righteousness). The ç
var<207>a system was very much in vogue. As for the <193>·rama system, ç
brahmacarya, g<193>rhasthya and v<193>naprastha were more common, ç
though there is enough reason to believe that sa<221>ny<193>sa was ç
also being practised. Great stress was laid on the purity and integrity ç
of personal life, irrespective of a person's station in life.
Apart  from  religion,  ethics  and philosophy, a number of secular ç
sciences like grammar, music, dance, archery, astrology, exorcising ç
the evil spirits, preparing of perfumes, toxicology and so on, were ç
also well-known.
Vedic sacrifices were very common. If they provided an occasion for ç
the kings to earn merit and show their generosity, it was also an ç
opportunity to the scholars to display their knowledge and earn name ç
and fame, as also some wealth.
On the whole, people seemed to be contended with whatever they could ç
earn by the right means. They believed that their sorrows and misfortunes ç
were caused by their own karma in their previous lives and hence did ç
not hold others responsible for the same.
@SB = 9.	Literary Grace
The language of the Upani<218>ads is closely allied to that of the ç
Vedas. Hence it is not only archaic but also abounds in Vedic phraseology ç
and symbolism.
Most of the Upani<218>ads are in verses composed in standard Vedic ç
metres. Some like the M<193><207><195><220>kya, the Taittir<200>ya ç
and the Aitareya are completely in prose. Some have a mixture of ç
both.
One of the striking features of the Upani<218>adic literature is its ç
use of beautiful similes and examples. The simile of two birds (the ç
j<200>v<193>tman and the Param<193>tman) perching on the same tree ç
(the human body) occurs in several Upani<218>ads: Ka<219>ha (1.3.1.); ç
<185>vet<193>·vatara (4.6.) and Mu<207><195>aka (3.1.1). The Mu<207><195>aka ç
gives the simile of the bow and the arrow (2.2.3,<|>4) to explain meditation ç
on the <193>tman. The Ka<219>ha compares the world to an inverted ç
tree (6.1) and the human body to a city of eleven gates (5.1). The ç
®·<193>v<193>sya compares the orb of the sun to a golden disc hiding ç
the face of the Lord (15). The Ka<219>ha compares the body to a ç
chariot, the senses to horses, the mind to reins, the intellect to ç
the charioteer and the <193>tman to the owner of the chariot (3.3 ç
and 4). The Mu<207><195>aka compares the evolution of the world ç
from Brahman to a spider weaving the web and hairs growing on the ç
body or vegetation appearing on earth (1.1.7). It also compares the ç
Vedic sacrifices to a leaky raft since they are unable to give liberation ç
(1.2.7). Rivers flowing into the ocean and becoming one with it is ç
another simile given to illustrate the union of the <193>tman with ç
Brahman (3.2.8). The B<216>had<193>ra<207>yaka abounds in many similes: ç
The Vedas have come out of Brahman even as smoke comes out of burning ç
wet wood (2.4.10). Just as spokes are fixed on the rim of a wheel, ç
similarly all beings find their support in Param<193>tman (2.5.15). ç
The j<200>v<193>tman travels from the waking state to the dream state ç
like a big fish swimming in water from one shore to the opposite shore ç
(4.3.18). While dying, the j<200>va catches hold of the next subtle ç
body even as a grasshopper catches hold of the leaf of the next nearby ç
plant, before leaving the former support (4.4.3). A liberated soul ç
casts off the body like a snake casting off its slough (4.4.7). The ç
pitiable condition of an ordinary mortal leaving his body is compared ç
to travelling in a heavily laden, but weak, cart (4.3.35).
The style of prose in the Upani<218>ads is not only simple and elegant ç
but also quite powerful.
@SB = 10.	Stories
Strangely enough, the Upani<218>ads, though teaching recondite philosophy, ç
also give us some interesting stories. The Kena describes how the ç
gods in heaven, under the leadership of Indra, were taught a lesson ç
by Brahman in the guise of a yak<218>a or demigod (3.1to 11). A major ç
part of the Ka<219>ha is devoted to the story of Naciketas and Yama. ç
The Ch<193>ndogya contains the following stories: Dogs singing the ç
udg<200>tha (1.12); the king J<193>na·ruti learning from the sage ç
Raikva (4.1 to 3); the story of Satyak<193>ma J<193>b<193>la approaching ç
H<193>ridrumata for knowledge (4.4 to 9); the story of Satyak<193>ma ç
and his disciple Upakosala (4.10 to 15); <185>vetaketu the proud boy, ç
his humble father Gautama and the king Prav<193>ha<207>a Jaivali (5.3 ç
to 10); Sanatkum<193>ra teaching N<193>rada (7.1 to 26); Indra and ç
Virocana approaching Praj<193>pati for the knowledge of the <193>tman ç
(8.7 to 12).
The B<216>had<193>ra<207>yaka too is not lagging behind. Its stories ç
and legends are: the struggle between the devas (gods) and asuras ç
(demons) to supersede each other (1.3); the proud B<193>l<193>ki and ç
the wise king Aj<193>ta·atru (2.1); Maitrey<200> seeking spiritual ç
wisdom from her husband Y<193>j<210>avalkya (2.4 and 4.5); King Janaka ç
and the great sage Y<193>j<210>avalkya (chapters 3 and 4).
@SB = 11.	<184><218>is or Sages of the Upani<218>ads
We come across a good number of <216><218>is or sages in the Upani<218>ads. ç
Some likeY<193>j<210>avalkya are extraordinarily great geniuses. ç
Others like Gautama °ru<207>i are excellent teachers. A few others ç
like <185>vetaketu are hard task-masters. Sacrifices conducted by ç
rich and powerful†but noble†kings provided opportunities to these ç
sages not only to exhibit their skills but also earn wealth and fame.
A selected list of sages that occur in the major Upani<218>ads may ç
now be given just for the sake of information:
A<209>giras, Bh<216>gu, G<193>rg<200>, Ghora °<209>girasa, H<193>ridrumata, ç
Mahid<193>sa Aitareya, N<193>rada, Pippal<193>da, Raikva, Sanatkum<193>ra, ç
<185><193><207><195>ilya, Satyak<193>ma J<193>b<193>la, Udd<193>laka ç
°ru<207>i, V<193>madeva and Varu<207>a.
Yama, the god of death, Praj<193>pati, the creator, great kings like ç
Janaka, Aj<193>ta·atru and Prav<193>ha<207>a Jaivali also appear in ç
the role of teachers.
One thing that strikes us is that these teachers were revered for ç
their knowledge and excellence, irrespective of their birth, caste ç
or sex.
@SPACE = 
@SB = 12.	A R<F20BI>Ç<F255D>sum<F20BI>Ç<F255D> of the<R>ç
	Principal Upani<218>ads
@SPACE = 
A brief summary of the more ancient and important Upani<218>ads can ç
now be given here. For the sake of convenience and ready reference, ç
they have been arranged in the English alphabetical order. The details ç
of the Veda to which they belong, the number of chapters, sections ç
and mantras are given in brackets to facilitate better understanding.
@SPACE = 
@S10N = AITAREYA UPANI<186>AD<R>ç
(<184>gveda; 4 chapters; 6 sections; 33 mantras)
@SPACE = 
One of the more enigmatic of the Upani<218>ads, this small work gets ç
its name from Mahid<193>sa Aitareya, the son of Itar<193>. He is the ç
<216><218>i of the Aitareya °ra<207>yaka of which this Upani<218>ad ç
is a part.
°tman or Param<193>tman, the supreme Lord, alone existed in the beginning. ç
He desired to create the world and did it without the aid of any other ç
thing, by himself, out of himself. He also entered into that creation. ç
This is the gist of the first chapter.
The second chapter describes the birth, the metamorphosis, the death ç
and the rebirth of the j<200>v<193>tman in order to awaken vair<193>gya ç
or detachment in our minds. It is only by realising our real nature ç
as <193>tman that we become free from the shackles of sa<221>s<193>ra ç
or transmigration. The sage V<193>madeva succeeded in getting that ç
spiritual wisdom even while in the womb of his mother and became free.
The last section of the Upani<218>ad distinguishes manas or the mind ç
from praj<210><193>na  or  pure  consciousness  and declares that ç
it is this praj<210><193>na that is the real <193>tman or Brahman, ç
by realising which V<193>madeva became free.
@S10N = B<184>HAD°RAØYAKA UPANI<186>AD<R>ç
(<185>ukla Yajurveda; 6 chapters;<R>ç
47 sections; 435 mantras)
Considered to be an integral part of the <185>atapatha Br<193>hma<207>a ç
of the <185>ukla Yajurveda, this Upani<218>ad is the biggest (as ç
its very name suggests) and is quite ancient. It is in prose and contains ç
quotations from other ancient sources which are all in verses.
The first two chapters aim at describing the <193>tman who is beyond ç
the various Vedic deities. He is the inmost Self of all and is nearest ç
and dearest. A living body is able to function only because of his ç
presence inside. To realise him one has to give up worldly desires, ç
take to the life of a monk or a mendicant and practise meditation ç
on his true nature. Realising him is the same as realising Brahman, ç
the cosmic Spirit.
In the third and the fourth chapters we find Y<193>j<210>avalkya, ç
the genius of a sage, at his best. He not only vanquishes all his ç
opponents but also establishes the fundamental teachings of Ved<193>nta ç
very effectively. A very brief summary of these teachings is as follows: ç
The life of a being here and hereafter is determined by the karma ç
he has done†good karma producing good results and bad karma, bad ones. ç
Even ritualistic karmas, in spite of their being coupled with up<193>san<193>s, ç
cannot givemok<218>a or freedom. Only the realisation of the <193>tman, ç
who is really Brahman, who transcends the body-mind complex, can give ç
freedom from transmigratory existence. To realise this <193>tman, ç
the wise br<193>hma<207>as renounce their family, wealth and the desire ç
for heaven, and take to the life of a mendicant.
Y<193>j<210>avalkya describes that which has pervaded everything in ç
creation, which has also transcended it and is also its antary<193>min ç
or the inner-controller, as Ak<218>ara (the Indestructible). He gives ç
a long list of its characteristics which appear to be rather self-contradictory ç
or confusing since it is an attempt to describe the indescribable.
He also establishes the true nature of the <193>tman, by an analysis ç
of the three states of consciousness, as the ever free blissful Self.
A description of the j<200>va suffering at the time of his death and ç
his transmigration also find a place in these teachings, to induce ç
vair<193>gya.
The last two chapters contain a number of up<193>san<193>s, as on ç
the pra<207>ava or O<221>, the need to cultivate the virtues like ç
self-control, compassion and giving gifts to the needy, the Pa<210>c<193>gnividy<193> ç
(the doctrine of five fires) and some rituals connected with the birth ç
of a son.
@SPACE1 = 
The Upani<218>ad ends with a long list of the line of the Vedic teachers.
@S10N = CH°NDOGYA UPANI<186>AD<R>ç
(S<193>maveda; 8 chapters;<R>ç
154 sections; 628 mantras)
Considered to be the oldest of the Upani<218>ads, the Ch<193>ndogya ç
begins with the up<193>san<193> on O<221> as the udg<200>tha, the ç
part of the S<193>maveda sung by the udg<193>t<216> priest. Meditation ç
on O<221> as pr<193><207>a (the life-force) and as the person in the ç
sun are the other topics dealt with in the first chapter.
There are various types of s<193>mans (mantras of the S<193>maveda). ç
The second chapter recommends several up<193>san<193>s on s<193>mans. ç
There is also a reference to the four <193>·ramas (stages of life) ç
and to the fact that one who is established in Brahman attains immortality.
The third chapter starts with the Madhuvidy<193>, meditation on ç
the sun as madhu or honey since he gives joy to the gods. Meditation ç
on Brahman through the G<193>yatr<200>-mantra is also mentioned here. ç
The famous <185><193><207><195>ilyavidy<193> is also a part of this ç
chapter. It consists of meditating on the <193>tman as the creator ç
and sustainer of the universe, in one's own heart. How a human being ç
can live long is also described by considering one's life as a long ç
yaj<210>a. The example of Mahid<193>sa Aitareya is quoted as the model ç
for such a meditation.
The next chapter starts with the story of the King J<193>na·ruti Pautr<193>ya<207>a ç
and his attaining wisdom, from the sage Raikva. Up<193>san<193> on ç
the v<193>yu (air) outside and the pr<193><207>a (vital air) inside ç
as the power that absorbs everything into itself is his teaching. ç
It has been called Sa<221>varga-vidy<193>.
A description of the j<200>va travelling by the Arcir<193>dim<193>rga ç
to the Brahmaloka as a result of meditation on the ak<218>ipuru<218>a ç
or the `person in the eye', who is Brahman, also finds a place here.
The  fifth  chapter  delineates  the process by which the dead return ç
to this world again. This, as taught by the kingPrav<193>ha<207>a ç
Jaivali to Gautama, is known as Pa<210>c<193>gnividy<193>. Meditation ç
on the supreme <193>tman, living inside the body as Vai·v<193>nar<193>tman, ç
makes one the enjoyer of all food through all beings. This is the ç
next teaching, given by the king A·vapati to the five sages who had ç
approached him for knowledge.
The sixth chapter is, by far, the most interesting and instructive. ç
Finding that his son <185>vetaketu was puffed up with egoism even ç
after his education at the guru's house, Udd<193>laka °ru<207>i questions ç
him about that by knowing which everything else becomes known. Since ç
<185>vetaketu was ignorant in this regard, °ru<207>i starts teaching ç
him in various ways. Before its creation, this world was one with ç
Sat (the self-existent Truth). This Sat willed to become many. The ç
world was created out of it in stages. Sat also entered into this ç
world as the j<200>v<193>tman. °ru<207>i traces the true nature of ç
the Self through an analysis of the three states of consciousness. ç
His final teaching is that <185>vetaketu in his essential nature is ç
that Sat itself.
@SPACE1 = 
The next chapter is in the form of a long dialogue between Sanatkum<193>ra ç
and his disciple N<193>rada. Though N<193>rada had mastered several ç
sciences and arts, he had no peace of mind since he had not known ç
the <193>tman. Sanatkum<193>ra takes him step by step through several ç
modes of up<193>san<193>s, and finally to Bh<220>man or Brahman.
The last chapter starts with the Daharavidy<193>, meditation on ç
the Self within the small <193>k<193>·a of the heart. A major part ç
of this chapter is devoted to the teaching of Praj<193>pati to Indra, ç
the king of gods, about the <193>tman, the true Self within. The Upani<218>ad ç
concludes with the statement of a liberated soul about his being free ç
from all sins and attaining the world of Brahman.
@SPACE = 
@SPACE = 
@S10N = ®<185>°V°SYA UPANI<186>AD<R>ç
(<185>ukla Yajurveda; 18 verses)
@SPACE = 
Though the smallest of the ten major Upani<218>ads, the ®·<193>v<193>sya ç
has attracted the attention of several savants who have chosen to ç
comment upon it. Some of its terms like vidy<193> and avidy<193>, ç
as also sambh<220>ti and asambh<220>ti, have proved to be elusive ç
or vague, thus giving rise several conflicting interpretations.
@SPACE1 = 
It teaches that the whole world is pervaded by ®·a or God. It advocates ç
the performance of karma or one's duties and encourages human beings ç
to desire to live the full span of life, viz., one hundred years. ç
After describing the nature of the <193>tman, it declares that one ç
who has realised this <193>tman in himself and sees the same in others, ç
transcends sorrow and delusion. It advises the practice of a balanced ç
combination of vidy<193> (meditation) and avidy<193> (karma, sanctioned ç
by the scriptures and helpful to meditation) as also sambh<220>ti ç
(meditation on Brahman) and asambh<220>ti (duties to be performed ç
in the world). There is also a beautiful description of Param<193>tman ç
and a prayer for God-vision by the sage at the time of his death.
@S10N = J°B°LA UPANI<186>AD<R>ç
(Atharvaveda; 6 chapters; 6 passages)
@EMERGENCY = This is a small Upani<218>ad in prose. All the six chapters ç
contain long passages. A description of V<193>r<193><207>as<200> (the ç
famous place of pilgrimage) and up<193>san<193> on the space between ç
the eyebrows as V<193>r<193><207>as<200> is the first teaching given ç
in this Upani<218>ad. The japa of the <185>atarudr<200>ya-mantra also ç
finds a place in this up<193>san<193>. This is followed by a discourse ç
on sa<221>ny<193>sa (monkhood) by Y<193>j<210>avalkya in reply to ç
a query by the king Janaka. It includes some details of the procedure ç
also. It concludes with a beautiful description of the way of life ç
of some great men of realisation like Sa<221>vartaka, °ru<207>i, <184>bhu, ç
Ja<195>abharata, Datt<193>treya and others.
@S10N = KAIVALYA UPANI<186>AD<R>ç
(K<216><218><207>a Yajurveda; 2 chapters; 24 mantras)
@EMERGENCY = This small work is in the form of a dialogue between ç
the sage °·val<193>yana (the disciple) and the creator Brahm<193> ç
(the teacher). It stresses the importance of ty<193>ga or renunciation ç
in the path of knowing Brahman. Some details of meditation on Brahman ç
in one's own heart, while sitting in a clean and secluded place, are ç
given. This meditation is compared to the production of fire by the ç
mutual rubbing of the two pieces of ara<207>i (See <MS>ARAØI<D>), ç
normally used to generate fire in Vedic sacrifices. This is then followed ç
by the usual description of Brahman (as given in other Upani<218>ads) ç
and the state of realisation of <193>tman-Brahman attained by the ç
aspirant.
@S10N = KA<187>HA UPANI<186>AD<R>ç
(K<216><218><207>a Yajurveda; 6 chapters; 119 mantras)
Also known as K<193><219>haka Upani<218>ad, it is an extremely readable ç
and interesting work. It starts with the story of the sage V<193>ja··ravas ç
performing a sacrifice. Seeing the famished and useless cows kept ç
apart by him to be gifted away during the sacrifice, Naciketas, his ç
young son, tries to draw his attention to this lacuna. V<193>ja··ravas ç
gets annoyed, and in a fit of anger, curses his son, `I give you to ç
Death!' Naciketas goes straight to the world of Yama, the god of death. ç
Finding Yama absent, he patiently awaits his return, for three days, ç
not touching food or water. When Yama on returning feels great remorse ç
for having kept a guest outside the house denying even elementary ç
comforts. Of the three boons he grants to Naciketas as atonement, ç
the third is utilised by Naciketas for seeking <193>tma-j<210><193>na ç
or knowledge of the Self. After thoroughly testing the boy with many ç
a tempting offer, Yama finally teaches him spiritual wisdom.
Two choices offer themselves before every human being†preyas (the ç
pleasant) and ·reyas (the good). Ordinary mortals choose the former ç
and get into endless trouble leading to bondage. The wise ones however, ç
forsake preyas, the immediately pleasant, for ·reyas, the path of ç
spiritual good, which alone can give permanent happiness, peace and ç
bliss.
@SPACE1 = 
Realising the <193>tman is the highest aspect of ·reyas. Though the ç
nature of the <193>tman, the true Self of man, is too subtle to be ç
grasped, it can be properly understood when taught by a competent ç
guru or preceptor. Self-control on the one hand, and grace of God ç
on the other, areaids in realising this <193>tman. Yama describes ç
the <193>tman or the j<200>va as the master of the chariot, the chariot ç
being the body itself. Just as the master sitting in a good chariot ç
drawn by good horses and an expert driver reaches his destination, ç
so also the j<200>va reaches the abode of Vi<218><207>u if the body ç
and the senses are in good condition and controlled by a wise intellect.
Drawn by the attraction of the senses, a person lets his mind go outwards. ç
However, if he can withdraw it from the outward objects and direct ç
it within himself, he can realise his <193>tman.
Yama also declares that the destiny of a being, after his death, is ç
determined by his karma or actions done in this life. He compares ç
the created world to an inverted tree, Brahman being the root that ç
sustains it. If taught by a competent teacher and through the conquest ç
of desires, one can know this Brahman.
Comparing the j<200>v<193>tman to a person of the size of the thumb ç
and that the exit through the crown of the head at the time of death ç
leads to the abode of Brahman, as also comparing the j<200>v<193>tman ç
and Param<193>tman to two birds perching on the same tree (the body) ç
are the other special aspects of the teaching of this Upani<218>ad.
@S10N = KAU<186>®TAKI UPANI<186>AD<R>ç
(<184>gveda; 4 chapters; 51 mantras)
Also called Kau<218><200>taki Br<193>hma<207>opa-ni<218>ad, it is ç
a fairly long Upani<218>ad and is entirely in prose.
The first chapter deals with the two well-known paths†Devay<193>na ç
and Pit<216>-y<193>na. There is a fairly detailed description of not ç
only the journey to the world of Brahm<193>, by the Arcir<193>dim<193>rga ç
or Deva-y<193>na, but also of the Brahmaloka itself.
The second chapter gives a detailed account of Pr<193><207>avidy<193>, ç
up<193>san<193> of pr<193><207>a as Brahman. There is also a rite ç
recommended  to  be  performed  by  anyone coveting `ekadhana,' interpreted ç
as the `highest wealth'.
The third chapter contains a long discourse by Indra (who has realised ç
the Supreme Being and hence identified with him) to the King Pratardana, ç
the son of Divod<193>sa. Indra advises Pratardana to meditate on him ç
as pr<193><207>a. Pr<193><207>a is also identified with praj<210><193> ç
(consciousness).
The last chapter which is in the form of a dialogue between the King ç
Aj<193>ta·atru and the learned G<193>rgya B<193>l<193>ki is almost ç
a repetition of B<216>had<193>ra<207>yaka Upani<218>ad (2.1).
@S10N = KENA UPANI<186>AD<R>ç
(S<193>maveda; 4 chapters; 35 mantras)
Also known as Talavak<193>ra Upani<218>ad, this small work gets ç
its name by its very first word `kena' (`by what'). The first half ç
is in verses and the second half in prose.
The Upani<218>ad begins with a description of the <193>tman in the ç
body as the spirit behind the sense-organs and the mind. It has been ç
identified with Brahman. Though it cannot be known as an object, since ç
it is the subject, its presence is felt in and through every thought. ç
When this realseer is realised, a person becomes immortal.
@SPACE1 = 
The second section gives the parable of the gods in heaven. Under ç
the leadership of Indra they had met to celebrate their victory over ç
the asuras or demons forgetting that it was due to the grace and power ç
of Brahman and not to their own valour. Brahman appeared on the scene ç
as a yak<218>a (a demi-god) and taught them a lesson after humiliating ç
them. Then Um<193> Haimavat<200> (the personification of Brahmavidy<193>) ç
came on the scene and taught Indra, spiritual wisdom.
The Upani<218>ad specially mentions that tapas (austerity), dama (self-control) ç
and karma (actions ordained by the scriptures) are the basic disciplines ç
needed to attain knowledge of Brahman. It concludes with a eulogy ç
of this knowledge.
@SPACE = 
@S10N = MAH°N°R°YAØA UPANI<186>AD<R>ç
(K<216><218><207>a Yajurveda; 80 sections; 259 mantras)
@SPACE = 
The Taittir<200>ya °ra<207>yaka of the K<216><218><207>a Yajurveda ç
contains two well-known Upani<218>ads: the Taittir<200>ya Upani<218>ad ç
and the Mah<193>n<193>r<193>ya<207>a Upani<218>ad. The latter is ç
also known as the N<193>r<193>ya<207>a Upani<218>ad and the Y<193>j<210>ik<200> ç
Upani<218>ad.
Two recensions are available now: the °ndhrap<193><219>ha and the ç
Dr<193>vi<195>ap<193><219>ha, the former being the longer one.
This Upani<218>ad seems to be a composition of many varied subjects, ç
almost like an appendix or an addenda to some other work. There is ç
no systematic treatment of any major doctrine. Each section seems ç
to be an independent unit. It deals with all the three aspects of ç
Vedic religion viz., karma (rituals), j<210><193>na (knowledge) and ç
up<193>san<193> (meditation).
Some of the most popular of the Vedic s<220>ktas which are chanted ç
even now during religious ceremonies†like the N<193>r<193>ya<207>a-s<220>kta, ç
the Durg<193>s<220>kta and the Medh<193>-s<220>kta†find a place ç
here.
The mantras commonly used during the sandhy<193> rituals, mantras ç
used during sa<221>ny<193>sad<200>k<218><193> (taking to the monastic ç
order), several g<193>yatr<200> hymns on different deities and some ç
famous mantras like the trisupar<207>amantras also find a prominent ç
place.
Various aspects of spiritual life like satya (truth), tapas (austerity), ç
dama (sense-control), d<193>na (giving gifts), dharma (righteous living) ç
and ·ama (mental peace) have been greatly stressed.
A beautiful description of the Cosmic Person in the orb of the sun, ç
contemplation on the various parts of a yaj<210>a or sacrifice in ç
a symbolical way and the journey to the Brahmaloka are also included ç
among the topics dealt with by this Upani<218>ad.
@S10N = M°Ø£<188>KYA UPANI<186>AD<R>ç
(Atharvaveda; 12 mantras)
Comprising only 12 mantras†all in prose†this small Upani<218>ad delves ç
straight-away into the philosophy of pra<207>ava (O<221>), <193>tman ç
and Brahman. Pra<207>ava is the best symbol of the eternal truth, ç
Brahman. The <193>tman inside this body†whose existence and real nature ç
are established by this Upani<218>ad through the analysis of the three ç
states of consciousness, viz., j<193>grat (waking state), svapna (dream ç
state) and su<218>upti (deep sleep state)†and Brahman, the Cosmic ç
Truth are, in the ultimate analysis, one and the same. He is called ç
the Tur<200>ya (the Fourth, beyond the three states described). It ç
is impossible to describe his nature since he is acintya (beyond thought) ç
and alak<218>a<207>a (beyond characteristics). He alone has to be ç
known. Meditation on the pra<207>ava (O<221>), especially its last ç
part, results in the realisation of the <193>tman.
A long commentary called K<193>rik<193> (in verses) attributed to ç
Gau<195>ap<193>da (circa <MS>A.D.<D> 700), generally goes with it ç
and is studied deeply by the students of Ved<193>nta.
@S10N = MUØ£AKA UPANI<186>AD<R>ç
(Atharvaveda; 3 chapters;<R>ç
6 sections; 64 mantras)
The word `mu<207><195>a' means a shaven head. This Upani<218>ad might ç
have derived its name from the fact that the spiritual wisdom contained ç
in it can shave off all the illusions and delusions of one who studies ç
it and understands it. Or, it could be that it was specially meant ç
for the sa<221>ny<193>sins with shaven heads.
Cast in excellent poetry, this Upani<218>ad is a delight to read.
It divides all knowledge into two groups†the par<193> (higher) and ç
the apar<193> (lower). Except the knowledge of the Ak<218>ara, the ç
indestructible Brahman, all other branches of knowledge†including ç
the Vedas themselves†are only apar<193>-vidy<193>, lower or inferior ç
knowledge! Then comes a nice description of this Ak<218>ara-Brahman ç
and the creation of the world out of it.
Though Vedic rituals were considered necessary and sacred, this Upani<218>ad ç
points out their limitations and advises the aspirant after spiritual ç
wisdom to eschew them like leaky rafters, take to a life of renunciation ç
and approach a competent guru for brahmavidy<193> or knowledge of ç
Brahman. The method of meditation on Brahman with the help of pra<207>ava ç
(O<221>) is picturesquely described with the simile of a bow and arrow. ç
This ends in the realisation of the <193>tman-Brahman inside oneself, ç
thereby resulting in the destruction of all the knots of ignorance ç
that bind one's heart or being.
The work compares the j<200>v<193>tman and the Param<193>tman to two ç
birds perching on the same tree, which is this body. The former is ç
bound whereas the latter is ever free. However, when he realises this ç
Param<193>tman he goes beyond good and evil and attains union with ç
him.
The famous declaration that Truth alone triumphs and not falsehood ç
(vide 3.1.6) belongs to this Upani<218>ad.
This <193>tman can be realised only when taught by an enlightened ç
preceptor and never by merely listening to discourses or intellectualism. ç
However, the grace of Godplays a very important part in this realisation.
Both types of liberation†the gradual one by going to the Brahmaloka ç
and the instantaneous one, at the fall of the body†have been mentioned ç
towards the end of this Upani<218>ad.
@SPACE = 
@S10N = PRA<185>NA UPANI<186>AD<R>ç
(Atharva-veda; 6 chapters; 67 mantras)
@SPACE = 
Since the Upani<218>ad is in the form of pra·nas or questions and ç
their answers, it has been named as Pra·nopani<218>ad.
Six sages like Kabandhi K<193>ty<193>yana, Bh<193>rgava Vaidarbhi ç
and others, come to the great teacher Pippal<193>da with their questions. ç
After they undergo the disciplines of student-hood for one year†as ç
per his command†they approach him again, with six questions. The answers ç
provided by Pippal<193>da form the main body of this work.
The first section deals with the subject: What is the origin of all ç
the beings? Pippal<193>da describes it as Praj<193>pati (God, as the ç
Lord of all beings), who creates the universe through the combination ç
of rayi (Soma or matter) and pr<193><207>a (Agni or °ditya or Spirit). ç
There is also a mention of the two paths: Uttar<193>ya<207>a (the ç
Northern Path) and Dak<218>i<207><193>yana (the Southern Path).
The second section describes the mukhyapr<193><207>a (the main life ç
force) as thesole support of the body and the sense-organs.
The third section says that this mukhyapr<193><207>a emerges out of ç
the Parama-puru<218>a or the Cosmic Person (God). He works inside ç
this body in five forms. At the time of death, the ud<193>nav<193>yu ç
(one of the five forms of mukhya-pr<193><207>a) carries the j<200>va ç
through one of the n<193><195><200>s (a tubular path for the flow ç
of pr<193><207>ic energy) originating in the heart, to heaven or hell ç
or this very world of human beings, depending upon his karma.
The fourth section gives an account of the deep sleep state of a being. ç
In that state, the j<200>va is merged in Param<193>tman or the Supreme ç
Self.
The next section delineates the method of meditation on the pra<207>ava ç
(O<221>) and the results one obtains from it. Highest meditation leads ç
to the attainment of Brahmaloka.
The last section, the sixth, deals with the <218>o<195>a·akalapuru<218>a, ç
`the person with sixteen parts'. He is the j<200>v<193>tman. When ç
these so-called parts get destroyed, the j<200>v<193>tman becomes ç
immortal.
@S10N = <185>VET°<185>VATARA UPANI<186>AD<R>ç
(K<216><218><207>a Yajurveda; 6 chapters; 113 mantras)
This Upani<218>ad starts with a discussion by some sages on the jagatk<193>ra<207>a ç
or the ultimate cause of this world, and comes to the conclusion, ç
in the very first chapter, that the Dev<193>tma·akti or the Param<193>tman ç
(God) with his inherent power, is that cause. This truth is discovered ç
by them through dhy<193>nayoga or meditation. This is followed by ç
a description of j<200>v<193>tman and Param<193>tman through various ç
elegant phrases.
The second chapter deals with the yoga of meditation, the various ç
aids to meditation like control and concentration of the mind, the ç
right posture, pr<193><207><193>y<193>ma or regulation of the pr<193><207>ic ç
energy through breath-control and some results of the practice of ç
yoga.
The third chapter contains several mantras found in other Vedic sections ç
like the Rudr<193>dhy<193>ya and the Puru<218>as<220>kta. The ç
descriptions, again, centre round the j<200>v<193>tman and the Param<193>tman.
Continuing the same subject, the next chapter<|>declares that those ç
who realise the truth, Brahman, will attain immortality.
@SPACE1 = 
The fifth chapter deals with the emergence of Hira<207>yagarbha (the ç
Golden-egg or the Cosmic Person) (called `Kapila' here) from Parame·vara, ç
the Supreme Lord. Descriptions of several aspects of creation are ç
also there. That the <193>tman (Brahman) can be known through the ç
secret parts of the Veda and that the knowers of the same attain immortality ç
is repeated here.
The  sixth  and  the  last  chapter declares Parame·vara or the Supreme ç
Lord as the lord of the karmas of the individual souls, and also eulogises ç
his greatness. The teachings of such Upani<218>ads as this are revealed ç
only to those who have devotion not only to Parame·vara but also to ç
the guru or spiritual teacher†is another important declaration of ç
this Upani<218>ad.
@SPACE = 
@S10N = TAITTIR®YA UPANI<186>AD<R>ç
(K<216><218><207>a Yajurveda; 3 chapters; 31 mantras)
@SPACE1 = 
The three chapters of this Upani<218>ad are respectively called <185><200>k<218><193>vall<200>, ç
Brahm<193>-nandavall<200> and Bh<216>guvall<200>, based on the ç
first words used in them.
The first chapter starts with the science of ·ik<218><193> or phonetics. ç
This is then followed by certain meditations on such subjects as jyotis ç
or light and a few homas (ceremonial oblations into fire) meant for ç
persons desirous of wealth and intelligence. Meditation on Brahman ç
within oneself, through the vy<193>h<216>tis like bh<220> etc., is ç
also touched upon. The last part gives the parting message of the ç
Vedic teacher to his student who is about to leave the institution.
The second chapter describes the five ko·as or sheaths that cover ç
the <193>tman, like the annamaya (the sheath of food, viz., the body), ç
the pr<193><207>amaya (the sheath of sense-organs) and so on. There ç
is also an interesting attempt to show that the bliss of realising ç
Brahman is infinitely superior to the pleasures one gets at the lower ç
levels (in this world or in heaven) by taking the ideal human happiness ç
as the basic unit.
@SPACE1 = 
The last chapter extols tapas orausterity as the means of realising ç
Brahman and also describes some up<193>san<193>s on anna or food. ç
That one should not despise food in any way, that one should honour ç
guests with food and shelter, is another idea prominently taught here. ç
The Upani<218>ad ends with the declaration that one who transcends ç
the five sheaths and realises the <193>tman, who is also in the sun, ç
attains eternal joy.
@SPACE = 
@S10N = VAJRAS<188>CIK° UPANI<186>AD<R>ç
(S<193>maveda; 9 mantras)
@SPACE = 
This is a small Upani<218>ad in prose, except for the first mantra. ç
It asks thequestion, `Who is a br<193>hma<207>a?' and answers it.
@SPACE1 = 
The body, the individual soul, birth, knowledge, work, religious duties†none ç
of these makes one a br<193>hma<207>a. It is character that makes ç
a person a real br<193>hma<207>a.
One who has realised the Self, the one without a second, who is therefore ç
free from all faults and defects, is a real br<193>hma<207>a. Peace ç
of mind, and absence of desire, jealousy and delusion, as also egotism, ç
are his characteristics.
@SPACE1 = 
The text closes with the exhortation to one and all to become a true ç
br<193>hma<207>a by realising Brahman.
@SPACE = 
@SB = 13.	Conclusion
@SPACE = 
The Upani<218>ads contain the quintessence of Vedic religion and philosophy. ç
The <186>a<195>dar·anas or the six systems of Indian Philosophy derive ç
their strength and inspiration from them. The Ved<193>nta systems ç
are entirely an outcome of their study. The idea of mok<218>a as the ç
primary goal of life, which has permeated the Indian  religions  and  culture  of  the ç
succeeding  centuries,  owes  its  origin entirely to the Upani<218>ads. ç
And, they are the basis of the prasth<193>natraya (the three foundational ç
scriptures), the other two being the Bhagavadg<200>t<193> and the ç
Brahma-s<220>tras.
