@H = K
@NT = Kabandha
@N1 = (`headless [demon]')
@SPACE = 
An interesting interlude in the story of the R<193>m<193>ya<207>a ç
is that of Kabandha. He was a headless demon with two very long arms ç
and a mouth inside his abdomen. A gandharva (a class of semigods), ç
Vi·v<193>vasu by name, he had incurred the wrath of the sage Sth<220>la·iras ç
and had been cursed by him to get this grotesque form. A blow on the ç
head by Indra with his vajr<193>yudha (thunderbolt) had made it worse.
When R<193>ma and Lak<218>ma<207>a were wandering in the Da<207><195>aka ç
forest, searching for S<200>t<193>, they were caught by him. However, ç
when they cut his arms, he enquired who they were and was glad to ç
get their identity since his liberation from the curse was in R<193>ma's ç
hands. At his request R<193>ma and Lak·ma<207>a killed himand cremated ç
his body. Once the abominable body was destroyed, Vi·v<193>vasu appeared ç
and advised R<193>ma to contact Sugr<200>va for help in locating and ç
recovering S<200>t<193>.
@SPACE = 
@NT = Kab<200>r
@N1 = (<MS>A.<|>D.<D> 1440-1518)
@SPACE = 
One of the great leaders of the Bhakti Movement and a pioneer of Hindu-Muslim ç
unity, Kab<200>r†also known as Kab<200>rd<193>s† was brought up as ç
an adopted child by the Muslim weaver couple N<200>ru and N<200>m<193> ç
who had found him abandoned near a tank. From the childhood days, ç
he was of a devotional and philosophical temperament. He cleverly ç
managed to become a disciple of the great saint of the times, R<193>m<193>nanda ç
of the Vai<218><207>ava sect, who later accepted him wholeheartedly.
@EMERGENCY = He had also come under the influence of Gos<193>i A<218><219><193>vand.
@EMERGENCY = His adopting Hindu ways of life brought him into conflict ç
with the contemporary Muslim society. But very soon, everybody had ç
to concede that he was a saint, a man of God, who had transcended ç
all social and religio-cultural barriers.
@EMERGENCY = Kab<200>r was married to Lori and had a son, Kam<193>l ç
who was also a saint.
Kab<200>r is said to have passed away in Maghar (now in Pakistan). ç
When the Muslims and Hindus were quarelling over the disposal of the ç
dead body, they are said to have found a heap of flowers below the ç
shroud! This was equally shared by them to be disposed off according ç
to their respective customs. The result was a Mandir and a Mausoleum ç
side by side.
@EMERGENCY = Kab<200>r has composed hundreds of songs mostly in the ç
Avadhi and Bhojpur<200> languages. They are compositions containing ç
the natural outpourings of the heart of a saint, of a realised soul. ç
His philosophy as reflected in these songs may be summarized as follows: ç
God is one only, for all the people of the world. There is no need ç
to worship him through symbols and icons. The path to God is open ç
to all, without any distinction of caste, colour or sex. The path ç
of devotion is universal and is equally open to the Hindus as well ç
as the Muslims. In the spiritual path, guidance from a competent guru ç
or teacher is a must. All devotional literature must be in simple ç
local vernaculars.
The followers of Kab<200>r gradually evolved into a separate sect ç
known as `Kab<200>rpanthis' within the Hindu fold.
Scholars are of the opinion that Kab<200>rhad influenced Guru N<193>nak ç
(<MS>A. D.<D> 1469-1539) and D<193>du (<MS>A.<|>D.<D> 1544-1603), two ç
more well-known teachers of the Bhakti Movement.
Kab<200>r's  compositions  have  been compiled into a work called ç
B<200>jak, as early as <MS>A.<|>D.<D> 1570.
His works are now available in the following forms: Kab<200>r S<193>habk<200> ç
<185>abd<193>val<200>, Kab<200>ranke Pad, S<193>khiy<193>, Kab<200>r ç
Vacan<193>-val<200> and Kab<200>r Granth<193>val<200>.
@NT = Kaca
@N1 = (`[One] who shines [by tapas]')
The devas and the asuras (gods anddemons) were eternal enemies. Theywere ç
guided in their deeds and dealings by their preceptors, B<216>haspati ç
and <185>ukr<193>c<193>rya.
<185>ukr<193>c<193>rya knew the science of m<216>tasa<210>j<200>van<200> ç
(bringing the dead back to life) whereas B<216>haspati did not. So, ç
the gods sent Kaca, B<216>haspati's son, to <185>ukr<193>c<193>rya ç
as a Vedic student, to somehow get a knowledge of that science. Having ç
got scent of their plan asuras managed to kill him. However, at the ç
earnest entreaties of his dear daughter Devay<193>n<200> who had fallen ç
in love with Kaca, <185>ukr<193>c<193>rya brought him back to life. ç
The asuras who would not give up so easily, managed to kill Kaca once ç
again, burnt his body and surreptitiously fed <185>ukr<193>c<193>rya ç
with wine†of which he was very fond of†mixed with the ashes of Kaca's  body.  When  Devay<193>n<200>  became ç
inconsolable at this tragedy, <185>ukr<193>c<193>rya revived Kaca ç
in his abdomen, taught them<216>tasa<210>j<200>van<200> science to ç
him and requested him to come out and also save his own life. Kaca ç
did as directed.
Having succeeded in getting what he wanted, he returned to his father ç
B<216>haspati, flatly rejecting the marriage proposal of Devay<193>n<200>, ç
since she was like a sister to him, being the daughter of his guru.
@SPACE1 = 
@NT = K<193>dividy<193>
@N1 = (`[esoteric] science or mantra beginning with ``ka'' ')
It is the same as `K<193>dimata'.
See <MS>TANTRAS<D> for details.
@SPACE1 = 
@NT = Kadr<220>
A daughter of the Praj<193>pati Dak<218>a, she was one of the thirteen ç
wives of the sage Ka·yapa and the mother of serpents. Vinat<193> (the ç
mother of Garu<195>a) was her co-wife.
Once there was a dispute between them regarding the colour of the ç
heavenly horse Uccai·ravas. Kadr<220> won it by a wily manoeuvre and ç
as a result Vinat<193> became her slave-maid as agreed earlier. However ç
Vinat<193> was rescued by her valiant son Garu<195>a.
The famous serpents <185>e<218>a, V<193>suki, K<193>rko<219>aka and ç
Dhana<210>jaya were her sons. Jaratk<193>ru was her daughter, later ç
on married to the sage Jaratk<193>ru, who was instrumental in stopping ç
the sarpay<193>ga (sacrifice of snakes) of Janamejaya, the son of ç
Par<200>k<218>it.
See also <MS>VINAT°.
@SPACE1 = 
@NT = Kahola
@SPACE1 = 
Kahola was a disciple of the sage Udd<193>laka. Later, he married ç
Suj<193>t<193>, Udd<193>laka's daughter and got A<218><219><193>vakra ç
as his son. (See also <MS>A<186><187>°VAKRA.<D>)
He once visited the court of the king Janaka and was defeated by the ç
sage Bandi  in  a  philosophical  disputation. Consequently he had ç
been imprisoned in water. A<218><219><193>vakra rescued him.
As per the B<216>had<193>ra<207>yaka Upani<218>ad (3.5.1) Kahola ç
questioned the sage Y<193>j<210>a-valkya in the court of the king ç
Janaka about Brahman but was silenced by his brilliant answers.
@NT = Kaikey<200>
@N1 = (`daughter of [the king o<%16>f<%0>]<R>ç
Kekaya')
See <MS>R°M°YAØA.
@NT = Kail<193>sa
Kail<193>sa has been mentioned in the R<193>m<193>ya<207>a, the ç
Mah<193>bh<193>rata and some Pur<193>nas as the abode or world of ç
<185>iva. It is one of the northern peaks of the Him<193>layas. It ç
is also called Rajat<193>dri (=the mountain of silver).
Devotees of <185>iva who get liberation are believed to go to this ç
world.
The P<193><207><195>avas had visited this place during their pilgrimage ç
while living in exile in the forest.
According to the <185>ivapur<193><207>a K<216><218><207>a is said ç
to have performed austerities here to please <185>iva.
Alak<193>pur<200>, the capital of Kubera was also situated in this ç
peak.
R<193>va<207>a had once tried to uproot it with his twenty hands but ç
was severely punished by <185>iva who just pressed his big toe and ç
got him trapped!
The modern Kail<193>sa mountain is about 40 kms. (25 miles) from the ç
famous M<193>nasa Sarovara in Tibet.
@NT = Kail<193>sanatha Temple
See <MS>ELLORA.<D>
There is a Kail<193>san<193>tha Temple at K<193><210>c<200>puram also. ç
See <MS>K°<178>C®PURAM<D> for details.
@NT = Kai<219>abha
The Hindu pur<193><207>as contain interesting stories often aimed ç
at glorifying a particular deity of the Hindu pantheon.
According to the Dev<200>bh<193>gavata (1.4.9) and the Dev<200>m<193>h<193>tmya ç
(1) Madhu and Kai<219>abha were two demons who came out of the ears ç
of Lord Vi<218><207>u when he was asleep. They tried to kill the four ç
faced Brahm<193>, the creator, who had just emerged from Vi<218><207>u's ç
n<193>bhikamala or navel-lotus. Brahm<193> then earnestly prayed to ç
Mah<193>k<193>l<200>, an aspect of the Divine Mother, who had put ç
even Vi<218><207>u to sleep. As she came out of Vi<218><207>u's body ç
and manifested herself to Brahm<193>, Vi<218><207>u woke up and fought ç
with the two demons. Finding it difficult to subdue them, he had to ç
pray to the Divine Mother for help. With her power of delusion overcoming ç
the demons, Vi<218><207>u succeeded easily in killing them.
See also <MS>DEV®BH°GAVATA<D> and <MS>DEV®-M°H°TMYA.<D>
@NT = kaivalya
@N1 = (`being all alone')
Liberation from the seemingly endless cycle of birth and death has ç
been posited by all the six systems of Hindu philosophy, as the final ç
goal of life. This goal has been<+>variously described as: mukti, mok<218>a, ç
kaivalya and nirv<193><207>a.
Kaivalya is a technical word usedmostly by the S<193><209>khya and ç
Yoga philosophies. Literally it means `kevalatva' or `being all alone'. ç
The puru<218>a or the individual soul who was in bondage due to his ç
association and identification with pradh<193>na or prak<216>ti (insentient ç
nature, matrix of material creation) realises by the practice of yoga ç
that he is absolutely different and separate from it. This know-ledge†called ç
`vivekakhy<193>ti'†frees him from that bondage and so becomes himself ç
once again and `all alone', never again under  the  slavery  of  prak<216>ti  (vide ç
Yogas<220>tras 4.34).
@NT = Kaivalya Upani<218>ad
@SPACE1 = 
This is a minor Upani<218>ad classed among the <185>aiva Upani<218>ads ç
and assigned to the K<216><218><207>a Yajurveda. There are 25 mantras, ç
mostly in the ·loka metre.
The sage °·val<193>yana approaches Brahm<193> (creator)†called Parame<218><219>hi ç
here †and requests him to teach brahmavidy<193> (knowledge of Brahman) ç
so that he can destroy all the sins and attain the highest Puru<218>a ç
or God.
After advising the disciple to cultivate faith and devotion to know ç
the Truth, Brahm<193> declares that this knowledge can be attained ç
by ty<193>ga or renunciation alone and not by rituals or progeny or ç
wealth. Those who have obtained the knowledge of Ved<193>nta, who ç
have purified themselves through sa<221>ny<193>sayoga or the spirit ç
of renunciation, they go to Brahmaloka andattain final liberation ç
at the end of the cycle of creation when even the Brahmaloka gets ç
dissolved in the Supreme Brahman.
In order to get this, the aspirant has to meditate on Lord <185>iva, ç
along with his divine consort Um<193> (P<193>rvat<200>), in the lotus ç
of the heart, after sitting in a suitable posture in a lonely and ç
pure place conducive to the practice of yoga.
When this meditation ripens into sam<193>dhi, he realises his identity ç
with the Lord. He becomes one with Brahm<193>, Vi<218><207>u and <185>iva ç
as also Indra, pr<193><207>a (vital airs), k<193>la (time) and so ç
on. Having thus become one with everything, past, present and future, ç
he transcends death.
The  teacher  then  describes  the process of meditation on the Self ç
inside by giving the analogy of the ara<207>is (See <MS>ARAØIS.<D>) ç
which are used to generate fire for Vedic sacrifices.
The topic discussed next is that of the j<200>va (the individual soul). ç
In reality he is the Supreme Soul (Param<193>tman) from whom the whole ç
universe evolves, but now apparently in bondage due to the effect ç
of m<193>y<193> (creative, illusory power of the Lord). Due to this ç
apparent bondage only, he experiences the three states of consciousness ç
(waking, dream and deep-sleep).
Brahm<193> then teaches °·val<193>yana that the j<200>va (individual ç
soul) in essence is pure consciousness, is the witness of all the ç
three states and is Brahman itself in reality. It is this realisation ç
of identity that frees him from all bondage.
The  last  part  of  the  Upani<218>ad describes the subjective experience ç
of a realised soul. He is smaller than the smallest, bigger than the ç
biggest, without limbs and parts, can get all knowledge without the ç
aid of the senses, and, in reality is <185>iva himself.
@SPACE1 = 
The Upani<218>ad concludes with an advice to the unenlightened, to ç
repeat the <185>atarudriya (Rudr<193>dhy<193>ya) in order to get ç
enough purity of mind, ultimately leading to kaivalya or liberation.
See also <MS>UPANI<186>ADS.<D>
@NT = K<193>kin<200>
Yogin<200>s are a group of female deities, 64 in number, associated ç
with Durg<193>. K<193>kin<200> is one of them. She is generally pictured ç
as having four faces, three eyes and two or four hands. Decorated ç
in yellow garments, she is shown as having a skull-bowl in one hand ç
and exhibiting the abhayamudr<193> (gesture of protection) with the ç
other. In the case of four hands, they carry in addition, a noose ç
and show the varadamudr<193> (boon-giving posture). She is sometimes ç
posited as the presiding goddess of the an<193>hatacakra (lotus of ç
the heart).
@NT = kal<193>
@N1 = (`that which increases')
Sanskrit is a marvellous language. This word `kal<193>' is one that ç
has several meanings. Any interpretation depends on the context in ç
which it is used.
Normally, it is used in the sense of a `part' (generally 1/16) of ç
anything.
When it refers to an art or science, 64 of them are listed. Some of ç
them are: g<200>tam (music), n<216>tyam (dancing), pu<218>p<193>-stara<207>am  (decoration  with  flowers), ç
aindraj<193>la  (magic),  prahelik<193>  (giving riddles for solving), ç
tak<218>akarma (carpentry), v<193>stuvidy<193> (architecture), nimitta-j<210><193>na ç
(futurology with the help of omens), dh<193>tuv<193>da (metallurgy) ç
and so on.
In °yurveda (health-science) it refers to the seven parts of a human ç
body.
The Upani<218>ads sometimes refer to 16kal<193>s or parts like pr<193><207>a ç
(life force), indriya (sense organ), tapas (austerity) and so on as ç
associated with a living being and responsible for his bondage (Pra·na ç
Upani<218>ad 6).
@NT = k<193>la
@N1 = (`that which counts [and spends away life]')
K<193>la or time is a fundamental concept and has been defined in ç
various ways. That which helps us to perceive change of state in a ç
thing is time. Taking the time needed to wink the eyelids as one unit ç
(called `nime<218>a') a table has been worked out as follows:
@L2 = 18 nime<218>as = 1 k<193><218><219>h<193><R>ç
30 k<193><218><219>h<193>s = 1 kal<193><R>ç
30 kal<193>s = 1 k<218>a<207>a<R>ç
12 k<218>a<207>as = 1 muh<220>rta<R>ç
30 muh<220>rtas = 1 ahor<193>tra (day + night)<R>ç
30 ahor<193>tras = 1 m<193>sa (month)<R>ç
12 m<193>sas = 1 sa<221>vatsara (year)
K<193>la has been considered as a dravya, a fundamental substance, ç
of the universe, by some philosophies like that of Jainism.
The S<193><209>khyak<193>rik<193> (50) considers k<193>la as a form ç
of tu<218><219>i (contentment), the satisfaction that comes as a result ç
of thinking that in course of time, mukti or liberation will definitely ç
come.
K<193>la is also one of the names of Yama, the god of death.
The Bhagavadg<200>t<193> (11.32) and the Bh<193>gavata (3.29.37-45) ç
equate k<193>la with God Himself.
@NT = K<193>labhairava
K<193>labhairava (an aspect of <185>iva) is the guardian deity of ç
K<193>·<200> (V<193>r<193><207>as<200>). The story goes that he nipped ç
the fifth head of Brahm<193>, the creator, because of his arrogant ç
behaviour. This head or skull, stuck to <185>iva's hand and as a penance ç
he had to wander about for 12 years as a mendicant. When he took bath ç
at a particular pool in V<193>r<193><207>as<200>, the skull fell off. ç
Since then, the pool has become known as `Kap<193>lamocanat<200>rtha'.
The word `K<193>labhairava' means one who is terrific (= bhairava) ç
even to Yama, the god of death (= k<193>la).
K<193>labhairava is also known as `Brahma·ira·cchet<216>m<220>rti'.
In  iconographical  works  he  is described as white in complexion ç
with three eyes and the hair dressed as a crown atop the head (ja<219><193>muku<219>a). ç
His ear- ornaments are patra or t<193><219>a<209>ka (leaf) and makaraku<207><195>ala ç
(mythical crocodile). In his four hands he carries para·u (battle-axe), ç
vajra (thunderbolt), ·<220>la (spear) or tri·<220>la (trident) and ç
Brahmakaro<219>ik<193> (Brahm<193>'s skull).
As per other descriptions he is shown with sword, trident, kettle-drum ç
(<195>amaru) and skull. He wears a garland of beads made of bones.
He is accompanied by a dog, just to indicate that he is the guardian ç
deity (K<218>etrap<193>la) of the sacred sites.
@NT = K<193>la<195><200>
Almost all the traditional biographies of <185>a<209>kara (<MS>A.<|>D.<D> ç
788-820) declare that he was born at K<193>la<195><200> (or K<193>la<219><200>), ç
a small town situated on the bank of the river P<220>r<207><193> (or ç
Periy<193>r). It is the same as the modern town K<193>la<195><200> ç
(or Kalady) in the Ernakulam district of Kerala State. It is about ç
13 kms. (8 miles) from Alwaye, 45 kms. (28 miles) from Kochi (Cochin) ç
and 55 kms. (34 miles) from the city of Trichur.
A chieftain, R<193>ja·ekhara by name, is said to have founded the ç
original village of K<193>la<195><200>. He had a dream in which he ç
saw a self-manifested <185>ivali<209>ga at this place. After discovering ç
it, he built a temple and a colony for the br<193>hma<207>as and others ç
who took care of it.
@EMERGENCY = Vidy<193>dhir<193>ja was one of these first settlers, ç
<185>ivaguru, the father of <185>a<209>kara was his son.
@EMERGENCY = The <185><193>rad<193> Ma<219>ha of <185><216><209>ger<200> ç
has a branch here, at the very place where <185>a<209>kara's original ç
house was situated. There are two temples here, one of goddess <185><193>rad<193>mb<193> ç
and the other of <185>a<209>kara as Dak<218>i<207><193>m<220>rti
@EMERGENCY = A black pole to the left of the main entrance is believed ç
to mark the exact place where <185>a<209>kara was born.
@EMERGENCY = The other places of interest are: a memorial which marks ç
the place where °ry<193>mb<193> (<185>a<209>kara's mother) was cremated; ç
the Crocodile Gh<193><219>, the bathing place in the P<220>r<207><193> ç
river where the boy <185>a<209>kara is said to have been attacked ç
by a crocodile and the <185>r<200>k<216><218><207>a temple, K<216><218><207>a ç
being family deity of <185>a<209>kara.
The erstwhile <185>a<209>kar<193>c<193>rya of the K<193><210>c<200>  K<193>mako<219>i  P<200><219>ha  (Candra·ekha- ç
rendra Sarasvati [<MS>A.<|>D.<D> 1894-1994]) has built a monument called ç
`°di <185>a<209>kara K<200>rtistambha Ma<207><195>apa' in K<193>la<195><200>. ç
It is 45 metres (147 ft.) high and has nine storeys. There are illustrations ç
in the form of relief paintings depicting the story of <185>a<209>kara.
The <185><216><209>ger<200> <185><193>rad<193> Ma<219>ha is running ç
a Sanskrit University here.
See also <MS><185>A<177>KARA<D>.
@NT = K<193>l<193>gnirudra
This is one of the terrific forms of Rudra or <185>iva, denoting the ç
destructive fire or `fire of death' (= k<193>l<193>gni). He is shown ç
with four arms holding kha<195>ga (sword), khe<219>aka (shield), dhanus ç
(bow) and b<193><207>a (arrow). He wears garments of red colour.
Sometimes he is shown among the Bhairavas (generally 64 in number). ç
In this case he carries ku<207><195>a (water pot), khe<219>aka (shield), ç
parigha (iron club) and bhi<207><195>ip<193>la (hand javelin).
In the works on <185>aivasiddh<193>nta, k<193>l<193>gni represents ç
one of the regions of the earth-element.
@SPACE = 
@NT = K<193><202>ahast<200>
@N1 = (`[spider], serpent and<R>ç
elephant')
@SPACE = 
K<193><202>ahast<200> is a well-known place of pilgrimage situated ç
in the Chittor district of Andhra Pradesh. It is 27 kms. (16.5 miles) ç
to the north-east of Tirupati, one of the foremost places of pilgrimage ç
in India. It lies between two hills†<185>r<200>puram and Mummi<195>ico<202>apuram†which ç
form part of the seven hills surrounding Tirupati. The river Suvar<207>amukhi ç
flows on one side of the town.
@SPACE1 = 
K<193><202>ahast<200> is famous for its temple of <185>iva, known ç
as K<193><202>ahast<200>·vara. This <185>ivali<209>ga is one of the ç
five elemental li<209>gas (pa<210>cabh<220>tali<209>gas) and is called ç
V<193>yuli<209>ga (li<209>ga associated with v<193>yu or air). There ç
is a lamp in the inner sanctum that is constantly flickering as if ç
to prove this point, despite the lack of movement of air inside.
The entrance to the temple is from the south whereas the deity faces ç
west. The main li<209>ga is said to be svayambh<220> or self manifested. ç
It is white in colour and has the shape of the trunk of an elephant ç
with tusks on either side. It is untouched by human hands, even by ç
the priest. Abhi<218>eka (bathing) is done by pouring a mixture of ç
water, milk, camphor and pa<210>c<193>m<216>ta (See <MS>PA<178>C°M<184>TA.<D>). ç
P<220>j<193> or worship is offered to the utsavam<220>rti or processional ç
image.
It is interesting to note that neatly dressed <185>aivaite br<193>hma<207>as ç
conduct the worship which includes that of various images of deities ç
kept inside.
@SPACE1 = 
The temple structure is very impress-ive. The gopuram (main tower) ç
is 36.5 metres (120 feet) high. The entire temple seems to have been ç
carved out of the side of a huge stone hill.
There is an underground shrine (9metres or 30 ft. below the ground ç
level) of Ga<207>e·a, called P<193>t<193>la-Vin<193>yaka.
Many royal dynasties have contributed to the construction of the temple ç
complex. The Pallavas, the Co<202>as and the rulers of Vijayanagara ç
are more prominent among them.
It should be mentioned here that the famous hundred-pillared hall ç
of the temple was built by K<216><218><207>adevar<193>ya (<MS>A. D.<D> ç
1488-1529) in <MS>A.<|>D.<D> 1516.
@SPACE1 = 
It is believed that this K<193><202>ahast<200>·vara li<209>ga is the ç
same as that which was worshipped by the hunter-saint Ka<207><207>appa, ç
now considered as one of the 63 N<193>yan-m<193>rs (or N<193>yan<193>rs) ç
(See <MS>N°YAN°RS<D>.), the well-known saints of the Tamil country.
According to the sthalapur<193><207>a (local mythology) this li<209>ga ç
had been worshipped by Brahm<193> himself and a galaxy of the ancient ç
<216><218>is in all the four yugas (See <MS>YUGAS<D>.). Arjuna is ç
said to have visited it during his pilgrimage. In the historical period, ç
Nakk<200>rar (celebrated Tamil poet who flourished in the 3rd century ç
<MS>B.<|>C.<D>)as also the great N<193>yanm<193>rs†Sambandhar, Appar ç
(both lived in the 7th century <MS>A.D.<D>), M<193><207>ikkav<193>cagar ç
(9th century <MS>A.<|>D.<D>) and Sundaram<220>rti (8th century <MS>A.<|>D.<D>)†also ç
visited this temple.
P<193>rvat<200>, the divine consort of Lord <185>iva is known here ç
as J<210><193>naprasann<193>mb<193>, and has a separate shrine for ç
her. She isconsidered as the sister of Lord Ve<209>ka<219>e·vara.
The temple has quite a few rare iconslike those of Vallabha-Ga<207>apati, ç
Mah<193>lak<218>m<200>-Ga<207>apati and Sahasra-li<209>ge·vara.
The temple campus contains a fewminor shrines dedicated to K<193>·<200>-Vi·van<193>tha, ç
Annap<220>r<207>a, S<220>ryan<193>r<193>ya<207>a, Sadyoga<207>apati ç
and Subrahma<207>ya.
Apart from the big hundred-pillared ma<207><195>apa, there<|>are other ç
smaller ones also like the Jalako<219>i-ma<207><195>apa and Palagar-ma<207><195>apa.
There are two sacred wells known as S<220>ryapu<218>kari<207><200> ç
and Candrapu<218>kari<207><200>.
Two separate temples dedicated to Durg<193>mb<193> and Ka<207><207>abe·vara ç
are situated on the surrounding hills.
The total number of festivals celebrated during the year is 85. Out ç
of these the Mah<193>·ivar<193>tri is the biggest festival celebrated ç
for ten days.
@NID = <+><+><+> The utsavam<220>rti (processional images) is taken out ç
in a procession on the third day during the Sa<209>kr<193>nti festival.
There are twelve t<200>rthas or holy places with ponds (or rivulets) ç
in the nearby Kail<193>sagiri hills. The water of one of the t<200>rthas†the ç
Sarasvat<200>-t<200>rtha†is believed to be endowed with the power ç
to make the dumb speak if drunk!
@NT = k<193>lak<218>epa
It is also known as kath<193>k<193>lak<218>epa.
See <MS>HARIKATH°.<D>
@NT = K<193>l<193>mukha
See <MS><185>AIVISM.<D>
@NT = K<193>lanir<207>aya
M<193>dhava-Vidy<193>ra<207>ya (<MS>A. D.<D> 1296-1386), the founder-saint ç
of the Vijaya- nagara empire was a scholar of extra- ordinary brilliance. ç
One of his well-known works is the K<193>lanir<207>aya, a treatise ç
on the definition of time and determination of suitable periods for ç
religious occasions.
The work is in five prakara<207>as or chapters. The contents may be ç
briefly stated as follows: scholastic disquisition on k<193>la or ç
time; the year and its sub- divisions; intercalary months and religious ç
acts permitted or forbidden during those months; about the tithis, ç
pure and mixed and determination of the various nak<218>atras for ç
religious acts.
The work names numerous sages, pur<193><207>as, astronomical and astrological ç
writers and their works.
@NT = K<193>lar<193>tri
@N1 = (`presiding goddess of the fierce night')
K<193>lar<193>tri is one of the several aspects of the Divine Mother ç
or a minor goddess presiding over the night that brings death and ç
destruction.
She is dark in complexion, fierce in appearance and has a cruel laughter. ç
She rides an ass.
If shown with four arms, she carries da<207><195>a (cudgel) and a ç
li<209>ga, the other two hands showing the varadamudr<193> (bestowal ç
of boons).
@NT = kala·a
@N1 = (`that which sounds [when filling with water]')
The word `kala·a' is commonly used in two senses: a ceremonially established ç
waterpot and the finial of a temple.
The waterpot kala·a is used in many rituals. It is considered as a ç
replica of the am<216>takala·a, the celestial pot prepared by Vi·vakarma ç
(the architect of the gods) at the time of churning the ocean, to ç
hold the am<216>ta or nectar.
A kala·a may be made of gold, silver, copper or even clay. The dimensions ç
recommended are:
@L1-1 = Maximum circumference: 101<+>cms.<|>(40<|>inches)<R>ç
Diameter of mouth: 16<+>cms. (6.4 inches)<R>ç
<+><+><+><+><+><+><+><+><+><+><+>Height: 32<+>cms. (12.8 inches)
It should be filled with water. Other things that may be put inside ç
it are: precious stones, flowers, fruits and herbs.
The kala·a is regarded as a composite divinity. Brahm<193>, Rudra, ç
Vi<218><207>u and Dev<200> are supposed to reside in its mouth, neck, ç
bottom and middle part respectively.
It is sometimes described as containing in its belly, all the seven ç
seas, all the seven islands as also all the planets and the stars. ç
It is the replica of the whole universe.
Nine varieties of the kala·as are also mentioned in some works. Eight ç
are arranged in the eight directions and the ninth (called `indriyaghna,' ç
with five mouths) kept in the centre during certain rituals.
Establishment of a kala·a is a must in the Durg<193>p<220>j<193>.
The  K<193>lik<193>pur<193><207>a  (chapter  87) recommends that ç
all gods should be worshipped in kala·as only.
Coming to the kala·a as the finial of the temple:
It is an important member of the superstructure over the sanctum of ç
a temple. It may be made of copper or silver or gold. Inside it a ç
`suvar<207>apuru<218>a' (a golden person) is installed, with an elaborate ç
ritual known as `h<216>dayavar<207>akavidhi'.
@NT = K<193>layavana
The Y<193>davas once offended their priest, the sage Garga. Garga ç
prayed to <185>iva to give him a son who could destroy the Y<193>davas. ç
K<193>layavana was that son born to a celestial nymph from Garga.
K<193>layavana was a very powerful warrior and demoniacal by nature. ç
He harassed the Y<193>davas many times and had even attacked Dv<193>rak<193>, ç
their capital.
Once, when he attacked Dv<193>rak<193>, K<216><218><207>a tactfully ç
drew him away, ran into a dark mountain cave where the great king ç
Mucukunda was sleeping and hid himself. K<193>layavana, entered the ç
cave and kicked the king thinking that he was K<216><218><207>a. When ç
the king opened his eyes and saw K<193>layavana, the latter was immediately ç
reduced to ashes, as a result of the boon he had received from the ç
gods whom he had helped in their fight against the demons.
@NT = Kali
@N1 = (`he who ruins [one's mind by sinful thoughts]')
According to the pur<193><207>as Kali the presiding spirit of Kaliyuga ç
or the Iron Age, is the personification of all that is bad and evil, ç
the very antithesis of dharma. He is the son of Krodha (anger) and ç
Hi<221>s<193> (violence).
His wife is Durukti (harsh and bad speech), and son Bhaya (fear). ç
Bhaya's wife is M<216>tyu (death) and son, Niraya (dark hell).
Obviously all these are symbolical.
Kali's images are very rare. When shown, he is depicted as dark in ç
colour, hideous in appearance with the tongue lolling out.
Kali entered this world on the demise of Lord K<216><218><207>a. Though ç
vanquished by the king Par<200>k<218>it, he was allowed to live in ç
certain places, as mentioned below.
He is said to reside in gambling, liquor, wanton women and gold.
@NT = K<193>l<200>
@N1 = (`Goddess of time or destruction')
Of all the forms of the Hindu pantheon, that of K<193>l<200> is perhaps ç
the most enigmatic to the modern mind. Who will not recoil in horror ç
and disgust from the form of a dark nude woman wearing an apron of ç
human hands and a garland of human heads, especially if she is also ç
holding a freshly severed human head and the chopper used in the slaughter, ç
dripping with  blood?  Throughout  its  history, mankind has been ç
baffled by profound symbology. More so when it does not conform to ç
its own `sweet and refined' standards. Even when one particular group ç
or cult successfully assimilates it and starts revering it, other ç
groups or cults continue to abhor it. It is natural for one group ç
to abhor the symbols of all others, forgetting conveniently that the ç
`other groups' are doing the same! The picture of the `Slain Lamb' ç
or the cultus of the `Sacred Heart' are just two illustrations to ç
show this.
@SPACE1 = 
On the other hand, a close look at such symbols will not only dispel ç
our ignorance about them but can also produce positive admiration. ç
Is not the water of the sea, which appears as dark blue or green from ç
a distance, really colourless and transparent when examined at close ç
quarters?
The word `K<193>l<200>' comes from the well-known word k<193>la, time. ç
She is the power of time. Time, as we are all well- aware, is all-destroying, ç
all-devouring. That is why the Lord says in the G<200>t<193> (11.32) ç
that He is time which has grown to infinite proportions and is destroying ç
the worlds. A power that destroys has got to be depicted in terms ç
of awe-inspiring terror.
Let us now turn to the K<193>l<200> imagery as normally found in the ç
scriptures, pictures and icons. The background is a cremation ground ç
or a burial ground or a warfield, showing the dead bodies including ç
the mutilated ones. She herself is standing in a challenging posture, ç
on a `dead' body, which is her own spouse <185>iva himself. If <185>iva ç
is pure white, she is deep blue in colour bordering on blackness. ç
She is completely naked, except for an apron of human hands. She is ç
wearing a garland of fifty human heads or skulls. Her luxuriant hair ç
is completely dishevelled. She has three eyes and four hands. In her ç
upper hands she is holding a freshly severed and bleeding human head, ç
as also the sword (or chopper) used in the carnage. The two lower ç
hands are in the abhaya and varada mudr<193>s. Her face is red and ç
the tongue protruding.
@SPACE1 = 
The background or the setting is in complete harmony with the theme. ç
The severed head and the sword are graphic representations of destruction ç
that has just taken place.
God is said to have created this universe and then entered into it. ç
(Taitti-r<200>yopani<218>ad 2.6.) So the universe becomes a veil, ç
a cloak for the divinity. When that is destroyed, the divinity remains ç
unveiled. This is the meaning of K<193>l<200> being naked. She is ç
hence termed `Digambar<193>' (`clad in space'), having the vast limitless ç
space itself as her only vesture.
Being the embodiment of tamas, the aspect of energy responsible for ç
dispersion ad infinitum producing limitless void, a void that has ç
swallowed up everything, she is black. She represents the state where ç
time, space and causation have disappeared without any trace as it ç
were. Hence she is black.
The hand represents the capacity for work. Hence the apron of severed ç
hands can signify that she is so pleased with the offerings of our ç
works and the fruits thereof that she wears them on her body.
The hand can also stand for kinetic energy. Therefore, severed hands ç
can stand for potential energy, the energy that has stopped all outward ç
manifestation, and yet is tremendously powerful, ready to manifest ç
itself when desired.
The dishevelled hair, for which she is  called  `Muktake·<200>,'  bespeaks  her ç
untrammelled freedom.
And then, the garland of skulls or heads which number fifty. They ç
represent the fifty letters of the alphabet, the manifest state of ç
sound, or sound (·abda) in general, from which the entire creation ç
has proceeded. To show that the manifest creation has been withdrawn, ç
she is wearing the garland on her body. The skulls or severed heads ç
indicate the state of destruction.
Since she is the supreme energy responsible for the dissolution of ç
the created universe, her form as depicted here naturally strikes ç
awe and fear. But then she is the creatrix, the Mother also. Hence ç
she is reassuring her fear-stricken children through the abhaya mudr<193> ç
saying, `Don't be afraid! I am your own dear Mother!' Simultaneously ç
she is also exhi-biting her desire to grant boons through the varada ç
mudr<193>.
So far, so good! But what about <185>iva Mah<193>deva being `trampled' ç
under her feet? According to one of the mythological accounts, K<193>l<200> ç
once destroyed all the demons in a battle and then started a terrific ç
dance out of the sheer joy of victory. All the worlds began to tremble ç
and give way under its impact. At the request of all the gods <185>iva ç
himself asked her to desist from it. She was too intoxicated to listen. ç
Hence <185>iva lay like a corpse among the corpses on which she was ç
dancing in order to absorb its shock into himself. When she stepped ç
upon him she suddenly realised her mistake and put out her tongue ç
in shame!
<185>iva Mah<193>deva is Brahman, the Absolute which is beyond all ç
names, forms and activities. Hence he is shown lying prostrate like ç
a ·ava, corpse. K<193>l<200> represents his ·akti or energy. The energy ç
however can never exist apart from its source or act independently ç
of it. It can manifest itself and act only when it is based firmly ç
on the source. It is exactly this that is meant while showing K<193>l<200> ç
standing on the chest of <185>iva.
From all this, one should not jump to the conclusion that K<193>l<200> ç
represents only the destructive aspect of God's power. What exists ç
when time is transcended, the eternal night, of limitless peace and ç
joy, is also K<193>l<200> (Mah<193>r<193>tri). Again it is she who ç
prods <185>iva Mah<193>deva into the next cycle of creation. In short, ç
she is the power of God in all his aspects.
@NT = K<193>lid<193>sa
@N1 = (`servant of K<193>l<200>')
If K<193>lid<193>sa has been universally acclaimed as the brightest ç
star among the great authors of Sanskrit literature, and one of the ç
greatest poets and dramatists of the world, he richly deserves it.
Though he is so well-known, his date has not been fixed with any certainty. ç
It varies from the 2nd century <MS>B.<|>C.<D> up to the 4th century ç
<MS>A.<|>D<D>. However, based on an embossed metallic piece discovered ç
at Bhi<219>a (20 kms. or 12 miles from Allahabad in Uttar Pradesh) ç
during archaeological excavations, some modern scholars have tried ç
to fix his date as 2nd century <MS>B.<|>C<D>.
Many stories are current in the popular literatures of India regarding ç
his life. According to most of these, he was a dunce who became a ç
highly evolved scholar and poet overnight by his devotion to Mother ç
K<193>l<200>.
According to other versions, he was a br<193>hma<207>a of good <185>aiva ç
parentage, highly educated and cultured. He was one of the nine jewels ç
in the court of the king Vikram<193>ditya (whose identity has not ç
been established conclusively).
@SPACE1 = 
@SPACE1 = 
K<193>lid<193>sa's works are:
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@OUT2 = <MS>DRAMAS<D>: Abhij<210><193>na-·<193>kuntala;<R>ç
Vikramorva·<200>ya; M<193>lavik<193>gnimitra.
@SPACE = 
@OUT2 = <MS>POETICAL WORKS<D>: (called `Mah<193>k<193>vyas')<R>ç
Raghuva<221>·a; Kum<193>rasambhava;<R>ç
Meghad<220>ta; <184>tusa<221>h<193>ra.
@SPACE = 
Abhij<210><193>na·<193>kuntala depicts the story of the king Du<218>yanta ç
and <185>akuntal<193>, the adopted daughter of the sage Ka<207>va.
The story of the king Vikrama (also known as Pur<220>rava) and the ç
celestial nymph <188>rva·<200> is the main theme of the drama Vikramorva·<200>ya. ç
So also, the lovestory of M<193>lavik<193>, the princess of Vidarbha ç
and Agnimitra, the king of Vidi·<193> has been depicted in the drama ç
M<193>lavik<193>gnimitra.
The Raghuva<221>·a is a long poetical work classed among the Mah<193>k<193>vyas. ç
It is in 19 sargas or cantos. It deals with the stories of 23 kings ç
of the race of the Raghu, though, for obvious reasons, the story of ç
R<193>ma gets the pride of place.
Though the Kum<193>rasambhava is in eighteen cantos, K<193>lid<193>sa, ç
perhaps, wrote only the first seven, the other eleven being the handiwork ç
of an inferior author. It describes the marriage of <185>iva and P<193>rvat<200> ç
and the birth of Kum<193>ra (also known as Subrahma<207>ya or K<193>rttikeya) ç
who later killed the demon T<193>raka.
The Meghad<220>ta is a small work that graphically describes the ç
pangs of separation of a yak<218>a from his beloved wife.
The <184>tusa<221>h<193>ra gives a graphic description of the <216>tus ç
or seasons. K<193>lid<193>sa was, without doubt, the super-master ç
of Indian poetic style. His upam<193>s or allegories have been considered ç
as the very best and models for other writers.
@NT = K<193>lik<193>pur<193><207>a
Pur<193><207>as and Upapur<193><207>as have been responsible for preserving ç
and spreading popular Hinduism. Among the eighteen Upapur<193><207>as, ç
a K<193>lik<193>pur<193><207>a is also listed.
Two K<193>lik<193>pur<193><207>as have been dis-covered. While one ç
is assigned to the period <MS>A.<|>D.<D> 1000, the other is dated as ç
<MS>A.D.<D> 1600.
The one available in print now has 7375 verses in 93 chapters. It ç
seems to have been composed in K<193>mar<220>pa (Assam) and has been ç
considered an authoritative text quoted by later nibandhas like K<216>tyakalpataru ç
and D<193>nas<193>gara.
The pur<193><207>a deals with the exploits and worship of K<193>l<200> ç
or K<193>lik<193>. She is primarily the Yoganidr<193> or Vai<218><207>av<200>m<193>y<193> ç
of Vi<218><207>u, reborn as Sat<200> first and later as P<193>rvat<200>. ç
The work contains a plethora of subjects connected with pilgrimage, ç
worship of the various aspects of the Dev<200>, various methods of ç
p<220>j<193>, a lot of infor-mation regarding mantras, pura·cara<207>a, ç
yantras, spells and so on. Much of this information might have been ç
drawn from works extant then, but not available now.
@NT = K<193>lind<200>
@N1 = (`that which originates from the hill Kalinda')
The river Yamun<193> is well-known in the Vai<218><207>ava pur<193><207>as ç
as K<193>lind<200>. (See <MS>YAMUN°<D> for details.)
One of the eight queens of <185>r<200> K<216><218><207>a was K<193>lind<200>, ç
daughter of S<220>rya and sister of Yamun<193>. She married him after ç
performing severe austerities, knowing that he was Vi<218><207>u himself. ç
While on a hunting mission, K<216><218><207>a found her in a forest ç
and married her after knowing her intentions. She bore him ten valiant ç
sons.
One of the ponds of the Yamun<193> river was also known as K<193>lind<200>. ç
A sage Saubhari had once cursed Garu<195>a not to come to this pond ç
to eat up the snakes there. Consequently many snakes including the ç
terrible K<193>liyan<193>ga had made it their habitation.
@NT = Kali<209>ga
@N1 = (`[country established by]<R>ç
Kali<209>ga')
The kingdoms of A<209>ga, Va<209>ga and Kali<209>ga have been famous ç
from very ancient times.
Kali<209>ga was a prince who was the son of the sage D<200>rghatamas. ç
The country conquered and ruled over by him came to be known as Kali<209>gade·a. ç
It is identified with the region between the rivers Mah<193>nad<200> ç
and God<193>var<200>, now in Orissa.
During the period of the rule of the P<193><207><195>avas, one king, ç
Citr<193><207>gada by name (a maternal uncle of Duryodhana) was the ç
ruler of this country. R<193>japura was its capital.
Kali<209>ga was famous for first rate elephants needed for the armed ç
forces.
@NT = Kalisantara<207>a Upani<218>ad
The Kalisantara<207>a Upani<218>ad is a short work in prose, classed ç
among the minor Upani<218>ads of the K<216><218><207>a Yajurveda ç
and propagating Vai<218><207>avism.
The sage N<193>rada, observing that the Dv<193>parayuga had come to ç
an end and that  the  Kaliyuga  had  just  begun, approached Brahm<193> ç
(the creator) and asked how he could overcome the evil effects of ç
Kali (the Iron Age and its sinful effects). Brahm<193> replied that ç
this could be done by the repetition of the name of N<193>r<193>ya<207>a, ç
the primeval person (°di-puru<218>a). On being requested to reveal ç
it, Brahm<193> replied that the mantra was:
@P1 = hare r<193>ma hare r<193>ma<R>ç
<+><+><+>r<193>ma r<193>ma hare hare<F49P12M>e<F255P255D><R>ç
hare k<216><218><207>a hare k<216><218><207>a<R>ç
<+><+><+>k<216><218><207>a k<216><218><207>a hare hare<F49P12M>f<F255P255D>
This mantra of sixteen parts is capable of destroying the sixteen ç
covers (vide Pra·na Upani<218>ad 6.4) binding the soul. When that ç
happens, then the soul will shine like the sun, after the clouds that ç
were covering it, are driven away by a powerful wind.
There are no hard and fast rules regarding the repetition of this ç
mantra. Whether one is clean or unclean, by repeating it, one can ç
get liberation in the form of attaining God's world, living near him, ç
becoming like him in form or even getting dissolved in him.
By doing japa of this mantra 35 millions of times, a person becomes ç
freed from even the most heinous sins like brahmahaty<193> or stealing ç
gold and so on.
See also <MS>UPANI<186>ADS.<D>
@NT = kalivarjya
@N1 = (`what is prohibited in the age of Kali')
Hinduism has two important sets of teachings: The <185>ruti and the ç
sm<216>ti. The <185>ruti or the Vedas (including the Upani<218>ads) ç
concern themselves mainly with the ultimate truths of life and the ç
ultimate goal of life as also the means of achieving it.
The sm<216>tis, on the other hand, are handbooks of social values ç
and conduct, regulating the current-day societies. As changes take ç
place in a society due to external and internal factors, the sm<216>tis ç
also have revised their rules and regulations to be in tune with the ç
changes. The principle of kalivarjya is a typical example of this ç
healthy attitude and flexibility.
The principle of Kalivarjya†what was once permitted in the earlier ç
ages, but now to be given up or prohibited in this age of Kali†seems ç
to have made its appearance around <MS>A.<|>D.<D> 1000, mostly in the ç
pur<193><207>as.
Scholars have listed 55 items as kalivarjya. Some of these are: giving ç
a larger share of property to the first or eldest son; niyoga (levirate); ç
remarriage of widows; intercaste marriages; read- mission of a br<193>hma<207>a ç
into the fold even after sea voyage; sattra sacrifices; killing of ç
a cow in the sacrifice called Gosava; v<193>naprastha stage; the sale ç
of the soma creeper by a br<193>hma<207>a; allowing a br<193>hma<207>a ç
to eat the food of persons of lower var<207>as which had been permitted ç
earlier; pilgrimage to very distant holy places; begging of food by ç
a sa<221>ny<193>sin from all var<207>as; engaging a ·<220>dra for ç
cooking in the house of a br<193>hma<207>a; resorting  to  sa<221>ny<193>sa;  observance  of ç
Agnihotra; performance of A·vamedha and R<193>jas<220>ya sacrifices; ç
perpetual studenthood (nai<218><219>hika brahmacarya); animal sacrifices; ç
intoxicating drinks.
Though it is difficult to say on what basis these rules or recommendations ç
were made, except a few of them like the first two items, the rest ç
do not seem to be very relevant. What is really needed is the educational, ç
economic and cultural upliftment of the Hindu society based on the ç
age-old spiritual values as depicted in the Upani<218>ads and the ç
Bhagavadg<200>t<193>.
@NT = Kaliyuga
@N1 = (`the age of Kali')
The concept of time as given in the pur<193><207>as, to say the least, ç
is mind-boggling. One year of the human beings is one day of the celestials. ç
Twelve-thousand such celestial years form one Caturyuga or the period ç
of four yugas of K<216>ta, Tret<193>, Dv<193>para and Kali.
The duration of the Kaliyuga in terms of human years in 4,32,000 years. ç
Kaliyuga is supposed to have started on the 18th February 3102 <MS>B.<|>C.<D> ç
Of course, there are other dates given by scholars and there is no ç
unanimity among them. Some reckon it from the day of the beginning ç
of the Mah<193>bh<193>rata war and others from the day of the ascension ç
of <185>r<200> K<216><218><207>a.
At present, the 5101st year of the Kaliyuga has begun (from the 15th ç
April 2000).
The age of Kali or Kaliyuga has been described as an age of evil and ç
sin.
The itih<193>sas and the pur<193><207>as give a highly graphic but ç
pessimistic account of the Kaliyuga.
Here is a sample: All men will be liars. Br<193>hma<207>as will give ç
up the sacred way of life prescribed for them. <185><220>dras will ç
acquire wealth and will be intent on doing japa. Many mleccha kings ç
will rule over the earth. They will be sinful and oppressive. People ç
will be short-lived. They will be weak, both physically and mentally. ç
K<218>attriyas and vai·yas will oppress the society. Ferocious animals ç
will increase in number. Women will be of loose character. False ascetics ç
will cheat the gullible persons.
Though a general decline of moral values seems to be what is intended ç
bythese descriptions, they are highly exaggerated.
See also <MS>YUGAS.
@SPACE = 
@NT = Kalki
@SPACE = 
Lord Vi<218><207>u whose duty it is, to take care of the world after ç
its creation, incarnates himself whenever dharma (righteousness)  declines  and  adharma ç
(unrighteousness) gets the upper hand, to restore the balance.
Out of the ten avat<193>ras or such incar- nations†generally known ç
as `Da·<193>vat<193>ras' †Kalki is the last and is yet to come. He ç
is said to appear at the end of the Kaliyuga as the son of Vi<218><207>u·arma ç
and Sumati at the city of <185>ambal<193>pura. He will finish his ç
education under Para·ur<193>ma, please Parame·vara by his tapas, obtain ç
a divine sword and a steed from him, and then kill Kali in a combat, ç
thus freeing the world from his unrighteous rule.
In this incarnation, Padm<193>vat<200>, the princess of Si<221>hala ç
will be his queen.
See also <MS>AVAT°RA.<D>
@NT = Kalm<193><218>ap<193>da
@N1 = (`one with black feet')
Some of the stories in the itih<193>sas and the pur<193><207>as are ç
not only interesting but also instructive. The story of Kalm<193><218>ap<193>da ç
is, perhaps, one such.
The king Saud<193>sa of the Ik<218>v<193>ku dynasty was once tricked ç
by a demon into serving his guru Vasi<218><219>ha with human flesh. ç
He was consequently cursed by the angered sage to become a cannibal-demon. ç
Saud<193>sa, who was now called Kalm<193><218>a-p<193>da (since his ç
feet were black) ate up all the sons of Vasi<218><219>ha himself. ç
However, after the twelve year period of the curse was over, Vasi<218><219>ha ç
was kind enough to bless him with a good son to succeed him.
@NT = kalpa
@N1 = (`era')
Brahm<193>, the four faced creator, is the deity who creates our world. ç
His lifespan is 100 divine years.
A kalpa is one day in his life. The creation lasts for this one day ç
only. At the end of this day, there is pralaya or dissolution, called ç
`naimittika-pralaya'. During Brahm<193>'s night there will be no creation.
Each  kalpa  is  divided  into  14 manvantaras and one Manu rules ç
over each of them.
We are now passing through the first kalpa (called `<185>vetavar<193>hakalpa') ç
of the 51st year of Brahm<193>. Of the 14 manvantaras, the 7th is ç
now in progress, ruled over by Vaivasvata Manu.
A kalpa is also divided into 1000 caturyugas or sets of four yugas. ç
One Manu rules over 1000/14 or 71.42 catur-yugas. The present Manu ç
is now in the Kaliyuga of the 28th caturyuga.
In terms of Human years, one kalpa is 4.32 billion years.
See also <MS>YUGAS.
@NT = kalpan<193>gaurava
@N1KERN = (`excessive imagination')
This is one of the eleven varieties of tarka or logic.
To say that all pots in this world are one and the same since they ç
are made of the same material (clay) and have the same quality of ç
`potness'†is the example given to substantiate the term.
@NT = kalpan<193>l<193>ghava
@N1 = (`simple imagination')
Samav<193>ya  (inherence)  has  been accepted as one of the seven ç
pad<193>rthas or categories by the Vai·e<218>ika philosophy. The connection ç
that exists between the parts and the whole, a moving object andthe ç
movement itself, a quality and the object that possesses it†these ç
are examples of samav<193>ya.
Is samav<193>ya only one or many? Though it may exist in many forms, ç
it is actually one only. This kind of argument is kalpan<193>l<193>ghava. ç
It is one of the eleven forms of tarka.
@NT = Kalpas<220>tras
@N1 = (`treatises dealing with<R>ç
practical aspects')
The Kalpa or the Kalpas<220>tras is one of the six Ved<193><209>gas ç
or subsidiary treatises that help in the conducting of Vedic sacrifices.
`Kalpa' means prayoga or the practical methods.
The Kalpas<220>tras belong to a period later than that of the major ç
Upani<218>ads.
The work has four sub-branches. They are: <185>rautas<220>tras, G<216>hyas<220>tras, ç
Dharmas<220>tras and <185>ulbas<220>tras.
The <185>rautas<220>tras deal with Vedic sacrifices. The G<216>hyas<220>tras ç
deal with domestic rites and rituals. The Dharma-s<220>tras deal with ç
the var<207><193>·rama dharmas. The <185>ulbas<220>tras contain detailed ç
information about the construction of the altars for Vedic sacrifices.
See under each title for more details.
@NT = Kalpataru
@N1 = (`wish-yielding tree')
In the Hindu mythological works, aKalpataru (also called Kalpadruma ç
or Kalpav<216>k<218>a) is often mentioned as a divine tree situated ç
in heaven, in the garden of Indra. It is said to have emerged out ç
of the k<218><200>rasamudra (ocean of milk) at the time of churning ç
it by the devas (gods) and the d<193>navas (demons). Its special quality ç
is that it fulfils the desires of persons sitting under it.
According to another version, it is one of the five divine trees found ç
in heaven, the other four being Mand<193>ra, P<193>rij<193>ta, Sant<193>na ç
and Haricandana.
Kalpataru is also the name of a scholarly commentary by Amal<193>nanda ç
(13th century <MS>A.<|>D.<D>) on the Bh<193>mat<200> of V<193>caspati ç
(<MS>A.<|>D.<D> 840) which itself is a detailed gloss on the Brahmas<220>trabh<193><218>ya ç
of <185>a<209>kara (<MS>A.D.<D> 788-820).
@NT = k<193>ma
@N1 = (`desire')
One of the most widely used words in the religio-philosophical as ç
also mythological literature, `k<193>ma' has three meanings: a) desire ç
in general; b) cupid, the god of lust and c) lust.
K<193>ma, also known as Manmatha, Madana, Kandarpa and Ana<209>ga, ç
was the son of Brahm<193>. When Brahm<193> gave him the boon of the ç
power to delude the whole world with lust, he dared to use it against ç
Brahm<193> himself! Then Brahm<193> cursed him to be reduced to ashes ç
by the third eye of Lord <185>iva. At the earnest entreaties of Rati, ç
his wife, <185>iva revived him.
Iconographical works depict him as a handsome young man with a bow ç
of sugarcane and five arrows tipped with flowers. He is accompanied ç
by his two wives, Rati and T<216><218><193> and rides on a parrot. ç
His banner is a makara or crocodile.
K<193>ma as desire in general, can be good or bad. A good desire, ç
as the desire for mok<218>a or liberation, elevates whereas bad desires ç
prove to be formidable obstacles in the path of spiritual evolution.
K<193>ma as lust, has been considered as one of the four puru<218><193>rthas ç
or ends to be striven for, in life. Since procreation was considered ç
as one of the sacred dutiesof duly married couples, k<193>ma has ç
been given that status. However, it has always to be within the limits ç
set by dharma or righteousness as described in the scriptures. Transgressions ç
have been severely condemned and punishments also prescribed.
See also <MS>PURU<186>°RTHAS.
@SPACE = 
@NT = K<193>madhenu
@N1 = (`wish-yielding cow')
@SPACE = 
K<193>madhenu, the celestial cow that fulfils all the desires, was ç
born out of the ocean of milk when it was being churned. (See <MS>SAMUDRA ç
MATHANA.<D>) Indra took it away.
@SPACE = 
@SPACE = 
Vasi<218><219>ha's cow Nandin<200> is sometimes identified with K<193>madhenu.
According to another version, the cow Surabhi was the daughter of ç
Dak<218>a. Surabhi's offspring was Rohi<207><200> and K<193>madhenu ç
was Rohi<207><200>'s daughter.
It is white in colour and has four feet which represent the four Vedas. ç
Its four udders can confer the four puru<218><193>rthas.
See <MS>PURU<186>°RTHAS.<D>
@NT = K<193>makal<193>
A t<193>ntrik ideology, K<193>makal<193> represents the Divine Mother ç
(Tripurasundar<200>) in terms of three bindus or dots, arranged in ç
a triangular form. The dot at the apex is said to be the face and ç
the other two dots, the breasts.
The three dots separately indicate the three powers†kriy<193>·akti, ç
icch<193>·akti and j<210><193>na·akti (powers of action, will and ç
knowledge)†and their presiding deities Brahm<193>, Vi<218><207>u and ç
<185>iva.
The  conception  is  esoteric  and mystical.
@NT = K<193>m<193>khy<193>
@N1 = (`[Goddess] known as [the fulfiller of] desires')
Worship of God as Dev<200> or <185>akti, the Divine Mother, is as ç
old as the Vedas. Most of the aspects and forms of the Dev<200> are ç
those of P<193>rvat<200>. In the pur<193><207>as, legends connected ç
with P<193>rvat<200> and her spouse, Lord <185>iva, are legion. One ç
of these is the story of the destruction of the sacrifice of Dak<218>a ç
by <185>iva whose spouse Sat<200> had immolated herself in the sacrificial ç
ground, unable to bear the insult to her husband.
When <185>iva was carrying the dead body of Sat<200> on his back and ç
roaming about the world with inconsolable grief, Brahm<193> and Vi<218><207>u ç
cleverly managed to enter into that body and cut it into 51 pieces. ç
Every place, where a piece of that body fell, became a sacred spot ç
and came to be known as a <185>aktip<200><219>ha, the seat of <185>akti ç
or the Divine Mother. K<193>m<193>khy<193> isone such <185>aktip<200><219>ha ç
where the yoni (generative organ) is said to have fallen.
The temple of K<193>m<193>khy<193> is situated on a hill known as ç
`N<200>l<193>cala' 5 kms. (3miles) from Guwahati, the capital city ç
of Assam. There is also a small township here. The district itself ç
is known as Kamrup (K<193>mar<220>pa).
@SPACE1 = 
This region of Assam was earlier known as `Pr<193>gjyoti<218>apura,' ç
ruled by the king Naraka, who was killed by <185>r<200> K<216><218><207>a. ç
It got the new name `K<193>mar<220>pa' after K<193>ma (cupid) was ç
restored to life by <185>iva here and a temple for the Dev<200> was ç
built by Vi·vakarma, the architect of gods.
The present temple has been built by the king Nara-n<193>r<193>ya<207>a ç
of Coochbihar in <MS>A.<|>D.<D> 1565, after the earlier one had been ç
destroyed by the Muslim iconoclast Kalapahar.
The architecture of the temple is simple. The ·ikhara (dome over the ç
sanctum) follows the beehive pattern. Parts of the older temple are ç
also seen in the lower portion.
The temple houses no image of the goddess. There is a cave within ç
the temple in a corner of which stands a block of stone with the symbol ç
of a yoni sculptured on it. It is kept moist from the oozings of a ç
natural spring within the cave. The devotees touch it and offer flowers ç
and leaves.
Among the sculptures adorning the temple structure may be mentioned ç
dancing Ga<207>e·a and C<193>mu<207><195><193>. The former is charming ç
whereas the latter is fierce.
Other temples on the N<200>l<193>cala are those of Gha<207><219><193>kar<207>a, ç
T<193>r<193>, Bhairav<200> and Bhuvane·var<200>.
The most important festivals celeb-rated at  this  temple  are  Ambuv<193>c<200>, ç
Debaddhani and Durg<193>p<220>j<193>. (See <MS>AMBUV°C®<D> and <MS>DURG°P<188>J°<D>.) ç
The second festival is connected with the goddess Manas<193> (snake-goddess, ç
identified with Jaratk<193>ru, daughter of the serpent king V<193>suki).
Animal sacrifice during the festivals exists even today.
When shown as an icon, K<193>m<193>khy<193> is pictured or sculptured ç
as a youthful lady, yellowish-red in colour with unbraided hair, having ç
three eyes and two hands (showing the abhaya and varada mudr<193>s). ç
She is seated on a red lotus. The sun and the moon are her ear- ornaments.
@SPACE = 
@NT = K<193>m<193>k<218><200>
@SPACE = 
K<193><210>c<200>puram  (the  modern  town Kanchi or Conjeevaram in ç
Tamil Nadu) is one of the seven very ancient sacred cities described ç
in the Hindu scriptures.
The goddess in the Dev<200> temple attached  to  the  Ek<193>mran<193>tha  temple ç
complex is known as K<193>m<193>k<218><200>, `one with beautiful eyes'.
It is said that once when <185>iva and Gaur<200> quarelled during ç
a game of dice, <185>iva cursed Gaur<200> to become ugly. With Vi<218><207>u's ç
grace she obtained lovely features with beautiful eyes. Then by performing ç
severe austerities under a single mango tree (=eka + <193>mra), she ç
pleased <185>iva and was reunited with him.
This goddess has several names: K<193>mako<219><219>am, Devagarbh<193>, ç
K<193>maka<207><207>i and K<193>me·var<200>.
@SPACE1 = 
K<193>m<193>k<218><200> is shown as seated in the padm<193>sana with ç
four hands. In the upper right and left hands she is holding the a<209>ku·a ç
(goad) and p<193>·a (noose). The other two hands are holding lotuses. ç
A parrot is also shown at the back.
