There is a <185>r<200>cakra or a <185>r<200>yantra, established by ç
<185>a<209>kara (<MS>A.<|>D.<D> 788-820), in front of the image, on ç
the ground. Worship is offered to this yantra.
The story goes that originally this goddess was fierce and used to ç
come out of the temple at dead of night to devour the people who had ç
incurred her wrath. When <185>a<209>kara came to know of it, he appeased ç
her and exhorted a promise that she would not stir out of the temple ç
without his permission!
The tradition of taking <185>a<209>kara's permission (whose image ç
also has been established in the temple complex) before the utsavam<220>rti ç
or the procession image is moved out, is kept up even now.
See also <MS>K°<178>C®PURAM.<D>
@NT = Kamal<193>kara
See <MS>NIRØAYASINDHU.<D>
@NT = K<193>mandaka
The Artha·<193>stra of Kau<219>ilya or C<193><207>akya (300 <MS>B.<|>C.<D>) ç
was a monumental work on political science and allied fields of knowledge. ç
However, its language being rather terse and prosaic, K<193>mandaka ç
(or K<193>mandaki) rendered its contents into more elegant poetry, ç
elucidating the teachings and adding didactic tales. This work is ç
known as N<200>tis<193>ra or K<193>mandak<200>ya N<200>tis<193>ra.
K<193>mandaka might have lived any where during the period <MS>A.<|>D.<D> ç
300 to <MS>A.<|>D.<D> 600.
The work N<200>tis<193>ra is in 20 cantos and 36 prakara<207>as. ç
The contents may be briefly summarised as follows:
@SPACE = 
@NID = Cantos 1 to 3:<+>
@NK-1 = Discipline and training of the king and the princes. Var<207><193>·rama ç
dharma. General rules of conduct.
@SPACE1 = 
@NID = Cantos 4 to 7:<+>
@NK-1 = The Sapt<193><209>gas or the seven elements of the State.
@SPACE1 = 
@NID = Cantos 8 to 12:<+>
@NK-1 = Inter-state relationships, treatises, nature of hostilities ç
and diplomatic counter-moves.
@SPACE1 = 
@NID = Canto 13:<+>
@NK-1 = Envoys, ambassadors and spies.
@SPACE1 = 
@NID = Canto 14:<+>
@NK-1 = Glorious results of strenuous actions and initiatives taken ç
on time.
@SPACE1 = 
@NID = Canto 15:<+>
@NK-1 = Vices  and  their  consequent afflictions.
@SPACE1 = 
@NID = Canto 16:<+>
@NK-1 = Enemy aggression and measures to combat it.
@SPACE1 = 
@NID = Cantos 17 to 19:<+>
@NK-1 =  Army movements and political expedients. Assessment of one's ç
strength and rectifying one's weaknesses.
@SPACE1 = 
@NID = Canto 20:<+>
@NK-1 = Deployment of the armed forces in offensive and defensive ç
warfare.
@SPACE = 
K<193>mandaka openly acknowledges his indebtedness to Kau<219>ilya.
@SPACE1 = 
The significant omissions in K<193>mandaka's work are: internal administration, ç
theories of taxation and regulation of trade and commerce.
The work has Balinese and J<193>vanese versions.
See also <MS>ARTHA<185>°STRA.<D>
@NT = kama<207><195>alu
@N1 = (`that which brings the<R>ç
essence of water')
A sa<221>ny<193>sin (Hindu monk) who has renounced all possessions ç
is permitted to keep and use a few things absolutely essential for ç
living. One of them is the kama<207><195>alu or the water pot, usually ç
made of bitter gourd (and sometimes of clay). It has a handle, a lid ç
and a spout. He is expected to carry it, along with the pavitra (cloth ç
for straining water).
@NT = K<193>m<193>rpuk<220>r
In Hinduism, a place of pilgrimage is called t<200>rthak<218>etra. ç
The word t<200>rtha refers to any place considered sacred due to its ç
association with a holy river, a mountain, a temple or any other object. ç
More often, it may be due to its close connection with a great spiritual ç
or reli-gious leader. And, the two remote villages of Bengal†K<193>m<193>rpuk<220>r ç
and Jayar<193>ma-b<193><219><200>, the birth places of <185>r<200> ç
R<193>mak<216><218><207>a and S<193>rad<193>dev<200>†have become famous ç
t<200>rthak<218>etras  or  places  of  pilgrimage exactly due to this ç
reason.
The town of K<193>m<193>rpuk<220>r is 112 kms. (70 miles) to the north-west ç
of Calcutta (now, Kolkata). The ancestral house where <185>r<200> ç
R<193>mak<216><218><207>a†better known as the Paramaha<221>sa†was ç
born was taken over by the Ramakrishna Math and the Rama-krishna Mission ç
and a beautiful temple raised over his birthplace.
The main shrine which is the birth place, contains an elegant marble ç
image of <185>r<200> R<193>mak<216><218><207>a.
The small temple of Raghuv<200>r (R<193>ma), the  family  deity  of  <185>r<200>  R<193>mak<216><218><207>a's ç
ancestors, the room where <185>r<200> R<193>mak<216><218><207>a used ç
to live and associated structures have been maintained in a good condition.
Other places connected with his boyhood days like the small temple ç
of <185>iva (where his mother had a unique mystical experience), the ç
village tank Hald<193>rpuk<220>r, the village school†which is a shed†and ç
the houses of the Lah<193> family are also there to be visited.
The following are the major religious festivals celebrated at this ç
centre: birthdays of <185>r<200> R<193>mak<216><218><207>a, S<193>rad<193>dev<200> ç
and Vivek<193>nanda; Durg<193>p<220>j<193>; Mah<193>·ivar<193>tr<200> ç
and K<193>l<200>p<220>j<193>.
The centre is running schools, hostels and a dispensary apart from ç
conducting several rural welfare activities. There are good facilities ç
for the pilgrim-devotees who throng the place throughout the year.
@NT = K<193>ma·<193>stra
@N1 = (`treatise dealing with love')
In the Hindu scheme of life embodied in the dharma·<193>stras, k<193>ma ç
or sexual love also has been given a place, as the third puru<218><193>rtha, ç
end to be striven for in life. Hence, like many other fields of knowledge ç
k<193>ma·<193>stra  or  erotics  too  has  been developed as a science.
Erotic elements are not rare even in the Vedas. The Vedic seers appear ç
to have had a realistic approach to the process of procreation.
Quite a few sages like <185>vetaketu, B<193>bhravya,  Dattaka,  C<193>r<193>ya<207>a  and ç
Kucum<193>ra have been cited as authorities on the k<193>ma·<193>stra.
V<193>tsy<193>yana's K<193>mas<220>tras†V<193>tsy<193>-yana (3rd ç
century <MS>A.<|>D.<D>) was also known as Mallan<193>ga†seems to be ç
the earliest and basic work on erotics. Ya·odhara's (13th century ç
<MS>A.<|>D.<D>) Jayama<209>gal<193> is the standard commentary on ç
the same.
Other works cited on this science of erotics are: N<193>garasarvasva ç
(of Padma·r<200>, 10th century <MS>A.<|>D.<D>), Ratirahasya (of Kokkoka), ç
Ana<209>gara<209>ga (of Kaly<193><207>amalla-deva), Kandarpac<220><195><193>ma<207>i ç
(of V<200>rabhadra, <MS>A.<|>D.<D> 1577) and so on.
The V<193>j<200>kara<207>a section of the °yurveda is related to ç
the science of erotics.
Some Western scholars like Pisanus Fraxi have admired the decency ç
and finesse with which the subject of erotics has been handled by ç
the Indian writers, who were interested in preventing disharmony between ç
the husband and the wife and not in promoting sensual indulgence.
@NT = K<193>mbhoja
One of the countries (and its people) well-known in the ancient days, ç
K<193>mbhoja was the region to the north-west of India, extending ç
from the Punjab to Bactria or Balkh. It was probably to the north ç
of the present day Kabul.
The country was known for its excellent breed of horses and great ç
warriors. It was considered as a `Mah<193>janapada' or `a great country'.
Sudak<218>i<207>a was the king ruling over it during the days of the ç
Mah<193>bh<193>rata. He sided with the Kauravas and was killed by ç
Arjuna in the Kuruk<218>etra war.
@NT = K<193>me·vara
@N1 = (`lord of desires')
K<193>me·vara is one of the several forms of ·iva, as the male counterpart ç
or spouse of K<193>me·var<200>, especially in the ritualistic worship ç
of the <185>r<200>cakra. (See <MS><185>R®CAKRA<D>.) He stands for ç
this phenomenal world, as the presiding deity. He is also the principle ç
governing our consciousness, especially our k<193>ma or desires. `Ka', ç
the first consonant of Sanskrit alphabets, represents him (k) along ç
with his <185>akti or spouse (a). `K<193>ma' in his name `K<193>me·vara' ç
suggests the cosmic urge to find an expression outside.
@NT = K<193>me·var<200>
@N1-1 = (`goddess lording over desires,' `granter of desires')
She is the counterpart of <185>iva as K<193>me·vara. (See <MS>K°ME<185>VARA.<D>) ç
She is an aspect of K<193>m<193>khy<193>. (See <MS>K°M°KHY°.)
Iconographical works describe her as dark in complexion. She has six ç
faces, eighteen eyes and twelve arms. She carries pustaka (book), ç
siddhas<220>tra (thread), pa<210>cab<193><207>a (five arrows), kha<195>ga ç
(sword), ·akti and ·<220>la (spears), ak<218>am<193>l<193> (rosary), ç
padma (lotus), koda<207><195>a (bow), abhaya mudr<193> (gesture of ç
protection), carma (shield), and pin<193>ka (spear-bow), in her arms.
Her six faces are of different colours and represent six deities: ç
white (M<193>he·-var<200>), red (K<193>m<193>khy<193>), yellow (Tripur<193>), ç
green (<185><193>rad<193>), black (K<193>me·var<200>) and variegated ç
(Candr<193>).
Multicoloured garments and tiger skin adorn her.
Worship of K<193>me·var<200> is done in the <185>r<200>cakra. (See ç
<MS><185>R®CAKRA.<D>)
@NT = Ka<221>sa
Supposed to be the son of the king Ugrasena of Mathur<193>, Ka<221>sa ç
was actually the son of the demon K<193>lanemi (or Drumila) from Ugrasena's ç
queen whom he cleverly cheated by assuming the form of Ugrasena using ç
his magical powers.
Ka<221>sa was a tyrant from the beginning. As he grew up, he usurped ç
the kingdom by dethroning Ugrasena and imprisoning him. When Devak<200>, ç
his younger sister was married to Vasudeva and when Ka<221>sa was ç
taking them for a ride in his chariot, he heard a voice from the void ç
that the eighth issue of Devak<200> would cause his death. Ka<221>sa, ç
frightened by this, tried to kill Devak<200>. But he was pacified ç
by Vasudeva who promised to hand over all the children born to Devak<200>.Though ç
Ka<221>sa spared her life, he imprisoned her and Vasudeva and also ç
killed all the six babies born to them. The seventh was miraculously ç
transferred to the womb of Rohi<207><200>, the elder wife of Vasudeva, ç
living in Gokula. The eighth was K<216><218><207>a, the incarnation ç
of Lord Vi<218><207>u. Ka<221>sa tried his best to get him killed ç
but was himself killed by him later.
See also <MS>K<184><186>ØA.<D>
@NT = k<193>myakarma
@N1 = (`desire-motivated actions')
A human being can never rest without performing karma or some sort ç
of action or activity. Such karmas, as per the Hindu scriptures, are ç
of four types: ni<218>iddhakarma (prohibited actions); k<193>myakarma  (actions  motivated  by ç
desires); nityakarma and naimittikakarma (obligatory actions prescribed ç
to be performed daily and on special occasions); ni<218>k<193>makarma ç
(desireless actions).
Ni<218>iddhakarma or sinful actions like stealing, rape and murder ç
are highly condemned and hence must be eschewed at all costs.
K<193>myakarma  or  desire-motivated actions are permitted to be performed ç
to fulfil one's desires if they cannot be got in the normal course ç
by human efforts alone. The k<193>mye<218><219>is of the Vedas and ç
the various vratas prescribed by the pur<193><207>as belong to this ç
category.
Nityakarmas are the prescribed daily duties like Agnihotra, sandhy<193>vandana ç
and devap<220>j<193> (worship of family deity). Naimittikakarmas are ç
occasional rites like ·r<193>ddhas (obsequial rites) or fasting on ç
certain days like ek<193>da·<200>s and so on.
Ni<218>k<193>makarma is any good work done without selfish desires ç
or motives, like service to others or as an offering to God or with ç
the attitude of worship of God. This type of work purifies the mind, ç
ultimately leading to the realisation of the Self within.
@NT = k<193>mye<218><219>i
@N1 = (`desire-motivated sacrifice')
Since  all  our  desires  cannot  be fulfilled by human resources ç
and efforts alone, the Vedic sages provided in the system of sacrifices ç
some special ones for this purpose. They are generally called k<193>mye<218><219>is ç
(k<193>mya = desired object; i<218><219>i = sacrifice).
A very short list of such sacrifices is given here as a sample:
Annak<193>me<218><219>i for plenty of food.
Ayu<218>k<193>me<218><219>i for long life.
Dar·ap<220>r<207>am<193>sa for attaining heaven.
K<193>r<200>r<200><218><219>i for getting rains.
Pavam<193>ne<218><219>i for the cure of chronic diseases.
Putrak<193>me<218><219>i for begetting worthy sons.
Vasuk<193>me<218><219>i for attaining wealth.
These are performed on the new-moon or full-moon days and are variants ç
of the Dar·a sacrifice.
See also <MS>VEDIC SACRIFICES.<D>
@NT = Ka<207><193>da
Vai·e<218>ika-dar·ana, one of the six systems of Hindu philosophy ç
grouped under the <193>stika schools†schools that accept the authority ç
of the Vedas†owes its systematisation to the sage Ka<207><193>da, ç
who was also known as Aul<220>kya. He was probably living by the u<210>chav<216>tti ç
or subsisting on small grains and hence got the name Ka<207><193>da ç
(ka<207>a = small grain, ad = to eat). Since he was the son of the ç
sage Ul<220>ka, he was called Aul<220>kya (son of, or, belonging to ç
the family of, Ul<220>ka). Nothing is known about him. According to ç
some scholars he might have lived before Buddha and belonged to Prabh<193>sa ç
in Saur<193><218><219>ra (Gujarat).
See <MS>VAI<185>E<186>IKA DAR<185>ANA<D> also.
@NT = Kanakad<193>sa
@N1 = (<MS>A.<|>D.<D> 1508-1606)
Kanakad<193>sa, one of the four most important leaders of the Vai<218><207>ava ç
Bhakti Movement in Karnataka, is also an ideal example to show how ç
bhakti or devotion to God levels up human beings, transcending all ç
barriers of caste or culture.
He was born at K<193>ginele, a small village near Dharwad in northern ç
Karna-taka. He probably belonged to the d<193>sa, kuruba or be<195>a ç
community classed among the ·<220>dras. According to one version, ç
he was the son of a chieftain of a small province, lost his all in ç
a battle with the enemies, was critically injured but was miraculously ç
saved by the grace of °dike·ava (an aspect of Lord Vi<218><207>u) ç
atwhose command, became a harid<193>sa (servant of Lord Hari) or ç
a saint. He was a disciple of Vy<193>sar<193>ya (<MS>A.<|>D.<D> 1447-1539) ç
a well-known Vai<218><207>ava sa<221>ny<193>sin and the abbot of a ç
monastery. Purandarad<193>sa (<MS>A.D.<D> 1484-1564) was his co-disciple.
He was a great devotee of God and a saint of a very high order. Quite ç
a few miracles have been attributed to him. Some of them are: the ç
image of K<216><218><207>a in the temple at Udupi (Karnataka) turning ç
around to the backside to give dar·an to him, who was praying there ç
since he had been denied entry into the main entrance; blasting of ç
a big boulder that was proving an obstacle to a new tank under construction ç
and so on.
Apart from a number of devotional songs in which he has used the words ç
`K<193>ginele °dike·ava' as his pen-name, he has also composed the ç
following poetical works: Mohanatara<209>gi<207><200> (a poetical ç
work of a mythological type); Na<202>acaritre (story of Na<202>a ç
and Damayant<200>); R<193>madh<193>nyacaritre (a humorous composition ç
to prove the superiority of r<193>gi [a kind of millet] over rice); ç
Haribhaktis<193>ra (an ethico- devotional work) and N<216>si<221>hastava ç
(a hymn on Narasi<221>ha, the man-lion incarnation of Vi<218><207>u, ç
now not available).
See also <MS>D°SAK<188><187>A<D> and <MS>VY°SAR°YA.<D>
@NT = Kanakhala
See <MS>HARIDV°RA.<D>
@NT = K<193><210>c<200>puram
K<193><210>c<200>puram†also spelt as Ka<210>ci, K<193><210>c<200>, ç
Conjeevaram†is one of the seven very ancient cities and pilgrim centres. ç
It is situated on the bank of P<193>l<193>r river, at a distance of ç
75 kms. (46 miles) to the south-west of Chennai (or Madras city) and ç
very near Chengleput (the district head-quarters). K<193><210>c<200>puram ç
is a city of temples. It is divided into <185>ivak<193><210>c<200> ç
and Vi<218><207>uk<193><210>c<200>. Temples of Ek<193>mran<193>tha ç
(also called Ek<193>mbare·vara), Kail<193>san<193>tha and K<193>m<193>k<218><200> ç
adorn the former. The latter has the Varadar<193>jasv<193>mi temple.
The tower of the Ek<193>mbaran<193>tha temple (of <185>iva) is majestic ç
and is 56 metres (188 ft.) high. Its high compound encloses an area ç
of 10 hectares (25 acres) and contains the images of 63 N<193>yanm<193>rs ç
(<185>aiva saints of Tamil Nadu). The temple has been renovated during ç
the recent years.
The next in importance among the temples of <185>ivak<193><210>c<200> ç
is the K<193>m<193>k<218><200> temple. It is one of the most well-known ç
<185>aktip<200><219>has (abodes of Divine Mother). A <185>r<200>cakra ç
in the form of a disc (See <MS><185>R®CAKRA.<D>) in front of the image ç
receives all the worship. There is also a shrine of <185>a<209>kar<193>c<193>rya ç
(<MS>A.<|>D.<D>788-820) in the temple complex which is 1.6 hectares ç
(4 acres) in area. The sacred tank in the complex is called Pa<210>caga<209>g<193>. ç
The annual temple festival takes place in the Tamil month of M<193>·i ç
(February-March) which includes a silver-car festival also.
The most famous temple of Vi<218><207>uk<193><210>c<200> is that of ç
Varadar<193>ja. It is situated on a small hillock called Hastigiri ç
and is 360 metres by 240 metres (1200 ft. by 800 ft.). The image of ç
Varadar<193>ja (an aspect of Vi<218><207>u) is quite big in size and ç
is in the standing posture. There are images of the °<202>v<193>rs ç
and R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137) which also receive ç
worship.
Another temple of importance is that of Vaiku<207><219>ha Perum<193><202> ç
built in the 8th century <MS>A.<|>D.<D> The vim<193>na (tower) of this ç
temple is in three storeys and contains three images in the standing, ç
sitting and recumbent postures.
A rare temple of Citragupta with his image holding a book of palmyrah ç
leaves is also in K<193><210>c<200>puram. It is visited by both the ç
<185>aivas and the Vai<218><207>avas.
K<193><210>c<200>puram has been associated with many famous persons. ç
C<193><207>akya, (300 <MS>B.C.<D>) the author of Artha·<193>stra ç
is said to have been born here. So also <185>y<193>m<193>·<193>stri ç
(<MS>A.D.<D> 1762-1827) a famous musician-saint of South India. Buddha ç
(563-483 <MS>B.<|>C.<D>), <185>a<209>kara and Ved<193>nta De·ika (<MS>A.<|>D.<D> ç
1268-1369) had visited this place. The Pallavas and the Co<202>as ç
had ruled here. Buddhism and Jainism had had their heydays at some ç
time here.
The town is famous for Sanskrit learning as also for silk sarees.
See also <MS>K°M°K<186>®.
@NT = ka<210>cukas
@N1 = (`armour,' `covering')
See `K<193>·m<200>r <185>aivism' under <MS><185>AIVISM.<D>
@NT = Kandariya Mah<193>deva Temple
See <MS>KHAJURAHO.<D>
@NT = k<193><207><195>ar<218>i
@N1 = (`the sage of the k<193><207><195>a [or section of the Vedas]')
The Vedas are generally divided into two k<193><207><195>as or sections: ç
the Karmak<193><207><195>a and the J<210><193>nak<193><207><195>a ç
dealing with Vedic rituals and knowledge respectively. The chief <216><218>is ç
or sages who have expounded these are called `k<193><207><195>ar<218>is'.
The former was expounded by Jaimini and the latter by B<193>dar<193>ya<207>a ç
Vy<193>sa. So, these two are specifically known as `k<193><207><195>ar<218>is'.
Sometimes, the sage <185><193><207><195>ilya is recognised as the ç
third k<193><207><195>ar<218>i since he expounded the bhakti aspect ç
of the Vedas as different from the karma and the j<210><193>na aspects. ç
He calls the J<210><193>nak<193><207><195>a section as Brahmak<193><207><195>a.
@NT = K<193><209>gri Gurukula
@SPACE1 = 
It is education that moulds the minds of the young ones and ultimately ç
shapes a nation. Realising the importance of imparting basic Hindu ç
values of life to our children even from a young age, the leaders ç
of the °ryasam<193>j (See <MS>°RYA SAM°J<D> also.)  started  a  gurukula  type  (See ç
<MS>GURUKULA<D>.) of institution in <MS>A.<|>D.<D> 1902 in Punjab. ç
What started as an experimental primary school, gradually developed ç
into a big educational complex and was shifted to K<193><207>gri near ç
Hardwar (in Uttaranchal) in <MS>A.<|>D.<D> 1924. It was given the status ç
of a deemed university in <MS>A.<|>D.<D> 1962.
The institution is entirely residential and is modelled on the ancient ç
gurukula system. Hindi is the medium of instruction even at the post-graduate ç
level though Sanskrit is given a prominent place. There are separate ç
sections for boys and girls. No distinction is made based on caste, ç
region, social or economic status. All are given the same facilities ç
and treated alike. The subjects taught include Sanskrit, Hindi, mathematics, ç
geography, history, drawing, dharma·<193>stras, ethics as also some ç
basic training in a few trades like weaving mats. In higher classes ç
English and science are also taught.
Vedamah<193>vidy<193>laya and °yurveda-mah<193>vidy<193>laya are its ç
two wings at the graduate and post-graduate levels.
@NT = ka<209>ka<207>a
@N1 = (`that which expresses<R>ç
auspiciousness')
Images of Hindu gods and goddesses including the minor deities are ç
often shown with several ornaments. One such is the ka<209>ka<207>a ç
(bangle, bracelet). The number varies from two to seven on each hand. ç
The material used may be gold (suvar<207>a) or conch-shell studded ç
with pearls (ma<207>i-ka<209>ka<207>a).
@SPACE = 
@SPACE = 
A ka<209>ka<207>a may be round (valaya) or like a lotus-stem (m<216><207><193>lavalaya).
It is said to signify auspiciousness (kam = ·ubha or auspiciousness; ç
ka<207>a = to produce by sound).
@NT = Ka<207><207>agi
Ka<207><207>agi was a lady of ideal wifely virtues who was later deified ç
in Tamil history. See <MS><185>ILAPPADIK°RAM<D> for details.
@NT = Ka<207><207>appa
@EMERGENCY = Hindu didactic literature, especially of the mythological ç
type, has tried to convince the masses that God is more pleased with ç
the pure devotion of a simple heart than with the ostentatious devotion ç
of rituals and allied paraphernalia.
@EMERGENCY = Ka<207><207>appa (also known as Be<195>ara Ka<207><207>appa, ç
the head of the hunters' tribe) is one of the 63 <185>aiva saints†the ç
tenth among them†pictured in such works.
His story is given in the Tamil Periyapur<193><207>am (of Sekkilar, ç
11th century <MS>A.<|>D.<D>) as also in certain Kannada literary works ç
like V<216><218>abhendravijaya of <186>a<195>ak<218>ari (17th century ç
<MS>A.<|>D.<D>) and the Raga<202>es of Harihara (13th century <MS>A.<|>D.<D>).
Ka<207><207>appa  was  the  chief  of  the hunters living at the foot ç
of the hills near K<193><202>ahasti (now in Andhra Pradesh). Once ç
<185>iva appeared in his dream and asked him to worship the <185>ivali<209>ga ç
in the nearby forest. Ka<207><207>appa soon discovered the <185>ivali<209>ga ç
he had seen in the dream in anearby desolate temple and started worshipping ç
it in most unorthodox and even abominable ways with meat and flowers ç
worn by him on his own body! The br<193>hma<207>a priest doing regular ç
worship used to find the li<209>ga `desecrated' every day!
@EMERGENCY = One day when he was hiding in the temple to catch the ç
culprit, he found Ka<207><207>appa entering. Just at that time, blood ç
started oozing from the eye of Lord <185>iva's li<209>ga. Ka<207><207>appa ç
plucked one of his eyes and fixed it on the li<209>ga. Then the second ç
eye on the li<209>ga also started bleeding. When Ka<207><207>appa ç
was about to pluck his other eye also, the Lord appeared there and ç
blessed him.
Ka<207><207>appa got back his eyes and alsoenjoyed the bliss of seeing ç
<185>iva andadoring him. The br<193>hma<207>a priest, realising the ç
greatness of this devotee, fell at his feet.
@NT = ka<207><219>aka·odhana
@N1 = (`searching [and<R>ç
punishing] evil persons')
Running a kingdom is a challenging task. A king has to look at the ç
management side not only from the positive angle, but also from the ç
negative angle. `Ka<207><219>aka- ·odhana' belongs to this latter ç
group.
`Ka<207><219>aka' literally means a `thorn' and figuratively, a `harmful ç
person'. A ruler has to organise a set of good spies who can not only ç
find out but also catch red-handed, the culprits who are against the ç
people and against the nation. Such an act was known as `ka<207><219>aka·odhana' ç
(vide section 4 of the Artha·<193>stra of Kau<219>ilya [300 <MS>B.<|>C.<D>]).
Some of the items listed under `ka<207><219>aka·odhana' by the Artha·<193>stra ç
are:
Whether the artisans working in the guilds were maintaining the quality ç
of the work and giving the finished articles on time; whether the ç
weights and measures used by the traders were genuine and standard; ç
whether the traders, workers and manufacturers were maintaining thestandards ç
set for them and selling unadulterated things; whether the government ç
officers were taking bribes or cheating the State; whether the doctors ç
were treating their patients as per the ethics of medical science ç
and so on.
The espionage system described and prescribed by Kau<219>ilya was ç
quite elaborate and almost fool-proof.
See also <MS>ARTHA<185>°STRA.<D>
@NT = Ka<207>va
`Ka<207>va' seems to be the name of many sages. In the <184>gveda, ç
one Ka<207>va, son of Ghora, has been mentioned as the author of 101 ç
<216>ks or <184>gvedic mantras.
A more famous Ka<207>va is the sage who was the foster-father of <185>akuntal<193>. ç
He not only brought her up but also took her to the king Du<218>yanta, ç
her husband. He was the son of another well-known sage Medh<193>tithi.
He once advised Duryodhana to make peace with the P<193><207><195>avas. ç
But, the prince refused to listen and patted his thighs in arrogance. ç
Then Ka<207>va cursed him that he would die with broken thighs.
His hermitage has been traced to a place near the modern Lucknow (in ç
Uttar Pradesh).
A sm<216>ti known as Ka<207>vasm<216>ti has been attributed to the ç
sage Ka<207>va and quoted by certain works lik<W1%-12>e<D%0> Sm<216>ticandrik<193> ç
of °padeva-m<200>m<193><221>saka (<MS>A.<|>D.<D> 1200).
@NT = K<193><207>va·<193>kh<193>
The <185>ukla Yajurveda has two ·<193>kh<193>s or recensions; the ç
K<193><207>va·<193>kh<193> and the M<193>dhyandina·<193>kh<193>.
The <185>atapatha Br<193>hma<207>a also has two ·<193>kh<193>s of ç
the same name. The B<216>had<193>- ra<207>yaka Upani<218>ad is found ç
in both the recensions. The K<193><207>va·<193>kh<193> has 17 k<193><207><195>as ç
or chapters and the M<193>dhyandina- ·<193>kh<193> 14.
There is not much difference between these two recensions.
See also <MS>B<184>HAD°RAØYAKA UPANI<186>AD.
@NT = kany<193>
@N1 = (`unmarried girl')
An unmarried girl (a maiden)†about ten years in age has been called ç
a `kany<193>' in the Hindu scriptures.
A kany<193> was supposed to be under the protection of Soma, Gandharva ç
and Agni before her marriage.
Though the marriage of a girl was primarily the responsibility of ç
her father (or brother, in case the father is not alive), she was ç
free to select her husband in case they failed in their duty.
The qualifications prescribed for a kany<193> or a bride, have changed ç
over the centuries. A few of the most common and general qualifications ç
are: b<193>ndhavam or purity of the family; r<220>pam (beauty); praj<210><193> ç
(intelligence); and, vittam (wealth) (vide Bh<193>radv<193>ja G<216>hyas<220>tras ç
1.6).
Kany<193>s  without  brothers,  with awkward names and whose virginity ç
was in doubt were to be avoided.
Sale of girls in marriage, which seems to have existed in ancient ç
times†as was the case in many other countries†was severely condemned ç
by the dharmas<220>tras and nibandhas (digests). Whatever money or ç
property was taken by the girl's father (as kany<193>·ulka) from the ç
bridegroom's family, was to be given back to the newly married couple ç
for their maintenance.
Though during the period 600 <MS>B.<|>C.<D> to <MS>A. D.<D> 200, the ç
age of a girl for marriage was not seriously considered or limits ç
fixed, popular feeling seems to have swungtowards early (pre-puberty) ç
marriages*. Reasons cited by some competent authorities for this trend ç
are: spread of Buddhism and a cheap kind of monasticism; laxity of ç
morals among the nuns; lack of education among girls; marriage for ç
girlsbeing looked upon as an equivalent of the upanayana for boys ç
and hence the fixing of the age for marriage as eight years. For a ç
girl to remain unmarried and die as a spinster was generally disliked.
Kany<193> (Virgo) is one of the twelve zodiacal signs or constellations ç
(the sixth) in astrology. The Hast<193> and the Citt<193> are the ç
main stars in this.
Those born under this sign are supposed to be handsome in appearance, ç
learned in many sciences, become wealthy but are religious by nature.
@NT = kany<193>d<193>na
@N1 = (`gifting the maid [to the young man in marriage]')
Hinduism considers marriage as a sacrament. Husband and wife are fellow ç
travellers and companions in the path of spiritual evolution.
When a suitable young man has been found as a match for his daughter, ç
the father of the girl had to give her to him in a religious rite ç
known as `kany<193>d<193>na'.
Kany<193>d<193>na is one of the several steps involved in the much ç
bigger process called `viv<193>ha' or marriage. The father of the ç
bride tells the bride-groom in this rite that he should not prove ç
false to the bride in dharma, artha and k<193>ma. The latter responds ç
with the words, `n<193>ticar<193>mi' (`Ishall not do so.').
This rite described in the ancient dharma·<193>stras has practically ç
remained the same even to this day.
See also <MS><186>O£A<185>A-SA<189>SK°RAS<D> and <MS>VIV°HA.<D>
@NT = Kanyak<193>-Parame·var<200>
She is the patron goddess of the vai·ya community, especially in Andhra ç
Pradesh and Karnataka.
It is said that once Brahm<193> asked Jayanta, the son of Indra, to ç
fight and kill a demon <185>atajihva by name. <185>ac<200>dev<200>, ç
his mother, intervened and prevented him from going, out of fear that ç
he himself may be killed in the process. This enraged Brahm<193> who ç
cursed her to be born on earth among the vai·yas.
So, she was born as the daughter of Kusuma·re<218><219>hi and was ç
named V<193>sav<193>mb<193>. A king, Vi<218><207>uvardhana by name, ç
proposed that she be given to him in marriage. Since the members of ç
the community refused permission, the king threatened to fight and ç
kill them. But before he could do it, a large section of the community ç
led by V<193>sav<193>mb<193> herself, immolated themselves in fire. ç
She was in course of time deified into the goddess Kanyak<193>parame·var<200>. ç
Her temples are found generally in places where the vai·yas are concentrated.
Another story identifies her with P<193>rvat<200>.
@NT = Kany<193>kum<193>r<200>
Also known as `Kany<193>t<200>rtha,' Kany<193>-kum<193>r<200> is a ç
very ancient place of pilgrimage of over two thousand years dedicated ç
to the Divine Mother in her aspect of a virgin. It is situated at ç
the southernmost tip of India, in the Kany<193>kum<193>r<200> district ç
of Tamil Nadu. It is very near Thiruva-nanthapuram (Trivandrum), the ç
capital city of Kerala State, the distance being just 87 kms. (54 ç
miles). It is on the sea-shore where the Indian ocean, the Bay of ç
Bengaland the Arabian sea merge.
There are two mythological accounts connected with this deity. The ç
first tells us that the female child that escaped from the clutches ç
of Ka<221>sa, assumed the form of Durg<193> and warned him about his ç
killer K<216><218><207>a living elsewhere, settled down here.
@SPACE1 = 
As per the second account, Pu<207>yake·<200>, the daughter of May<193>sura ç
(the chief architect of the asuras or demon race) performed severe ç
tapas or austerities here to get Lord <185>iva as her husband. <185>iva ç
promised to marry her at the end of the kalpa or aeon but advised ç
her to continue her tapas. While she was doing so, a terrible demon ç
B<193><207><193>sura pressed her to marry him. She was obliged to ç
kill him by using her cakra or discus. After this she resumed her ç
tapas and is still waiting for her final union with <185>iva.
According to another version the Dev<200> was born as the daughter ç
of a king in order to kill the demon B<193><207><193>sura who had ç
become invincible by divine boons. Only a maiden could kill him.
When the Dev<200> started meditating on Lord <185>iva and appealed ç
to him to marry her, he came down from Kail<193>sa and was waiting ç
at the town <185>uc<200>ndram for the auspicious moment, in order ç
to come to her for the marriage. The gods, afraid that their purpose ç
of the Devi (as a maiden) killing B<193><207><193>sura would be rendered ç
fruitless, made a fake cock crow so that <185>iva was roused from ç
meditation. In utter dismay he found that the auspicious moment had ç
passed off! So he remained at <185>uc<200>ndram itself. And, the Dev<200> ç
here was made to wait indefinitely with the garland in her hand, for ç
<185>iva!
Of course, she did kill B<193><207><193>sura also who appeared there ç
and fought with her.
The goddess is also known as K<193>ty<193>-yan<200> (daughter of the ç
sage Katya), an aspect of P<193>rvat<200>.
The image of the virgin goddess is in the standing posture with two ç
arms. She is holding an ak<218>am<193>l<193> or rosary in her hand. ç
There is a carved figure of si<221>ha or lion, suggesting that she ç
is Durg<193>, on the pedestal.
There are four pillars in the temple which, when struck, emit musical ç
sounds like those of a M<216>da<209>ga (drum), V<200><207><193> (lute), ç
flute and jalatara<209>ga (porcelain water cup instrument).
Apart from the Dev<200> temple, there is also a beautiful and magnificent ç
temple with an imposing image of Swami Vivek<193>nanda, built on the ç
bigger rock in the sea, not far from the coast. There is a regular ç
ferry service from the coast to the temple.
@NT = kap<193>la
@N1 = (`that which protects the head')
Kap<193>la is skull. Some of the fierce deities of the Hindu pantheon ç
like Ka<209>k<193>la Bhairava, Bhik<218><193><219>anam<220>rti (both ç
being the terrible aspects of <185>iva) as also K<193>l<200> are shown ç
carrying skull-cups or skull-pots, either for receiving alms or for ç
drinking the blood of their victims.
The story connected with the Bhik<218><193><219>anam<220>rti aspect ç
of <185>iva narrates how <185>iva nipped the fifth head of the arrogant ç
Brahm<193> and how it (the skull) stuck to his finger. Because of ç
this sin, he had to roam about the earth as a mendicant for expiating ç
that sin, finally getting rid of that skull (head) at K<193>·<200> ç
or V<193>r<193><207>as<200>.
Vampires and cemetery spirits (Vet<193>las) are believed to carry ç
the skulls of their victims and drink their blood in them.
The sect of the K<193>p<193>likas has made the kap<193>la, a part ç
of its paraphernalia. Burnt pot-sherds used for baking puro<195><193>·as ç
(rice-cakes) are also called `kap<193>las'.
@NT = kap<193>labh<193>ti
Texts on Ha<219>hayoga prescribe various methods for the internal ç
purification of the body that help in maintaining it in good health. ç
The <186>a<219>karmas or six practices are an important prescription ç
given by them.
The kap<193>labh<193>ti (vide Gheran<195>a Sa<221>hit<193> 1.56-59) ç
is the last of these six practices. It is, again, of three kinds:
a)<+>v<193>takrama†Also called `v<193>ma-krama' it consists in drawing ç
air through the left nostril and expelling it through the right and ç
then, reversing the process.
b)<+>vyutkrama†In this, the yogi draws water through both the nostrils ç
and expels it through the mouth slowly.
c)<+>·<200>tkrama†This is the reverse of the above-mentioned practice, ç
viz., drawing water through the mouth and then expelling through the ç
nostrils.
See also <MS><186>A<187>KARMAS.<D>
@NT = K<193>p<193>lika
@N1 = (`one who uses a kap<193>la [or skull as a cup]')
See <MS><185>AIVISM.<D>
@NT = Kapila
He was a celebrated sage, considered as the fifth incarnation of Lord ç
Vi<218><207>u (Bh<193>gavata 1.3; 3.24). He was the brother of Arundhat<200> ç
(wife of the sage Vasi<218><219>ha) and the only son of Kardama and ç
Devah<220>ti.
He taught spiritual wisdom to his mother Devah<220>ti. This part of ç
the Bh<193>gavata is known as the Kapilag<200>t<193> (3.25-33). ç
This teaching contains not only the S<193><209>khya philosophy but ç
also A<218><219><193><209>ga-yoga and Bhaktiyoga.
The S<193><209>khyadar·ana (the S<193><209>khya- s<220>tras) is ç
attributed to him.
The sixty-thousand sons of the king Sagara were reduced to ashes when ç
they tried to attack him thinking that he was the person who had stolen ç
the horse of the A·vamedha sacrifice of their father.
He was against the sacrifice of a cow in the Vedic y<193>ga called ç
Gosava as per the incident quoted in the Mah<193>bh<193>rata (<185><193>ntiparva ç
273).
The Bhagavadg<200>t<193> extols his greatness that K<216><218><207>a ç
is Kapila among the siddhas or perfected sages (10.26).
@NT = Kapilag<200>t<193>
See <MS>KAPILA.
@NT = Kapisthala-K<193><219>haka-Sa<221>hit<193>
This is a Sa<221>hit<193> of the K<216><218><207>a Yajurveda group. ç
The only manuscript available is incomplete. Its svara system (Vedic ç
intonation) resembles that of the <184>gveda.
@SPACE1 = 
It has 64 chapters spread over 8a<218><219>akas. The following are ç
the details as available now:
@SPACE = 
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(1.0275,.1250,E1), ç
KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
First A<218><219>aka, :, It is complete with eight chapters.
@Z_TBL_BODY = SPACE1, TABLE TEXT, TABLE TEXT
<R>ç
, +, +
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
Second A<218><219>aka, :, Damaged and<R>ç
incomplete.
Third A<218><219>aka, :, Chapters 9 to 24 have been lost.
@Z_TBL_BODY = SPACE1, TABLE TEXT, TABLE TEXT
<R>ç
, +, +
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
Forth A<218><219>aka, :, Chapters 25 to 31 are intact. Chapter 32 ç
is lost. Chapter 27 is the famous Rudr<193>dhy<193>ya.
@Z_TBL_BODY = SPACE1, TABLE TEXT, TABLE TEXT
<R>ç
, +, +
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
Fifth A<218><219>aka, :, All chapters except the 33rd,, have been ç
recovered.
@Z_TBL_BODY = SPACE1, TABLE TEXT, TABLE TEXT
<R>ç
, +, +
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
Sixth A<218><219>aka, :, The 43rd Chapter has been lost. The rest† ç
seven chapters†are available.
@Z_TBL_BODY = SPACE1, TABLE TEXT, TABLE TEXT
<R>ç
, +, +
@Z_TBL_END = 
The contents are similar to the other Sa<221>hit<193>s of this Veda.
@NT = k<193>ra<207>a
@N1 = (`that by which something is accomplished')
Indianphilosophicalsystemshave devoted some attention to the problem ç
of k<193>ra<207>a or cause and k<193>rya or effect, and their mutual ç
relationship.
K<193>ra<207>a or cause is of various kinds:
Up<193>d<193>nak<193>ra<207>a is the material cause, like clay for ç
a pot.
Nimittak<193>ra<207>a is the efficient cause like the potter's wheel ç
and stick as also the potter himself, for the pot.
Samav<193>yik<193>ra<207>a is the inherent cause, as the threads are ç
for the cloth out of which it is woven.
Other examples for samav<193>yik<193>ra<207>a are the existence of ç
a part in a whole, a quality in a qualified object or movement in ç
a moving object.
Asamav<193>yik<193>ra<207>a is the non-inherent cause, like the colour ç
of the threads, which causes the colour of the cloth, after the cloth ç
is woven. Colour is related to the threads directly and indirectly ç
to the cloth.
M<220>lak<193>ra<207>a is the original cause of the universe, i.e., ç
Brahman or God.
@NT = k<193>ra<207>a·ar<200>ra
@N1 = (`causal body')
According to the Ved<193>nta philosophy as depicted in the Upani<218>ads, ç
the Brahma-s<220>tras and allied scriptures, every j<200>va or individual ç
soul has three ·ar<200>ras or bodies: sth<220>la (gross), s<220>k<218>ma ç
(subtle) and k<193>ra<207>a (causal).
The k<193>ra<207>a·ar<200>ra or causal body is nothing but aj<210><193>na ç
or ignorance which is the root-cause of embodiment and hence, transmigration.
See also <MS>J®VA.<D>
@NT = kara<207><195>a-muku<219>a
@N1 = (`crown resembling a basket')
Images of Hindu gods, goddesses and lesser divinities have, almost ç
always, a muku<219>a or a crown on their heads. One of the several ç
varieties of such crowns is the kara<207><195>a-muku<219>a. `Kara<207><195>a' ç
means a basket, usually made of bamboo strips. Hence a kara<207><195>a-muku<219>a ç
is a crown that resembles a basket of bamboo strips.
Usually female deities and some minor gods like Ga<207>apati or yak<218>as ç
are provided with kara<207><195>a-muku<219>as.
This type of crown has three round basket-like shapes in three, five ç
or seven tiers. The lower one is studded with jewels and has a golden ç
band. The topmost one is surmounted by a ·ikh<193>ma<207>i or crest-jewel.
@NT = karany<193>sa
@N1 = (`dedication or purification of the hand')
Ny<193>sa or purification of limbs is an important aspect of many ç
a ritualistic process like p<220>j<193> (worship), japa (repetition ç
of divine name) and p<193>r<193>ya<207>a (ceremonial recitation of ç
scriptures or sacred texts). Out of seven such ny<193>sas, the a<209>gany<193>sa ç
and the karany<193>sa are most common.
In the karany<193>sa, the fingers of both the hands are purified simultaneously ç
to the accompaniment of appropriate mantras. First, the thumbs are ç
rubbed by the tips of the index-fingers from bottom to top with the ç
mantra `a<209>gu<218><219><193>bhya<221> nama<199>'. Then the thumbs ç
do the rest of the work in a similar manner, to the other four fingers, ç
the mantras being changed according to the fingers touched.
See also <MS>A<177>GANY°SA<D> and <MS>NY°SA.<D>
@NT = Karav<200>ra
See <MS>KOLH°PUR.<D>
@NT = Kardama
A great <216><218>i (sage) considered as oneof the nine mind-born ç
sons of Brahm<193>, the creator, was an ardent devotee of Vi<218><207>u. ç
He pleased Vi<218><207>u by his austerities and got the boon of a ç
worthy wife as also the Lord Vi<218><207>u himself to be born as his ç
son.
Very soon, Manu, the king of human beings came to his hermitage and ç
offered Devah<220>ti, his daughter, in marriage.
Kardama had nine daughters and a son, Kapila, considered as an incarnation ç
of Vi<218><207>u himself. Anas<220>y<193> (wife of the sage Atri), ç
Arundhat<200> (wife of the sage Vasi<218><219>ha) and Khy<193>ti (wife ç
of the sage Bh<216>gu) were among these nine daughters.
After completing his duties as a householder, Kardama advised his ç
wife Devah<220>ti to get spiritual wisdom from her son Kapila, who ç
was none other than Lord Vi<218><207>u himself and retired to the ç
forest for austerities.
See also <MS>KAPILA.<D>
@NT = karma
@N1 = (`that which is done')
`Karma' is one of the most widely used words in Hinduism. Derived ç
from the root-verb `k<216>' (= to do), its general meaning is anything ç
that is done. In this sense, it means: work; profession; and, duty.
However, more often than not, it is used in a technical sense, as ç
an action that binds one to sa<221>s<193>ra or transmigratory existence. ç
This type of karma can be accomplished either by the body or by speech ç
or by the mind. The respective names for these are: k<193>yika, v<193>cika ç
and m<193>nasa karmas.
Again, this karma with the potential to produce its fruits, can be ç
classified as sa<210>cita (accumulated over several lives), pr<193>rabdha ç
(begun to bear fruit in this life) and <193>g<193>m<200> (being performed ç
now and in future).
All the dar·anas or philosophies that accept this theory of karma ç
also concede that: 1)<+>The effects of karmas done in one life cannot ç
be expected to be exhausted in that life itself. Hence punarjanma ç
or rebirth has to be accepted.
@SPACE1 = 
2)<+>J<210><193>na or spiritual wisdom resulting in the realisation ç
of one's nature as the immortal soul, destroys sa<210>citakarma completely ç
and makes <193>g<193>m<200> incapable of producing its results even ç
as a burnt seed cannot sprout. However, pr<193>rabdhakarma, since ç
it has already started giving its results, has got to be exhausted ç
only through experiencing it.
From another standpoint, karma is of two types: ni<218>iddhakarma ç
or prohibited or sinful actions that must be avoided; vihita-karma ç
or actions ordained by the scriptures as duty, to be performed.
@SPACE1 = 
The latter again, is of three types: k<193>myakarma (desire-motivated ç
actions); nityakarma (daily duties); naimittika-karma (occasional ç
duties).
K<193>myakarma is performed to fulfil a desire that cannot, otherwise, ç
be fulfilled by normal human efforts. For instance, the Putrak<193>me<218><219>i ç
rite said to have been performed by the king Da·aratha to get worthy ç
sons, belongs to this category. So also the several vratas (religious ç
vows and rites) like the Satyan<193>r<193>ya<207>a vrata which are ç
common even now.
Ordained daily duties like sandhy<193>-vandana, repetition of the ç
G<193>yatr<200> mantra and Agnihotra belong to the nityakarma group.
Naimittikakarmas have to be performed due to certain nimittas or the ç
presence of special causes. For instance, during an eclipse, ·r<193>ddhas ç
(obsequial rites) have to be done.
Sometimes, karmas or actions are classified according to their nature, ç
good or bad. Actions done without being tainted by likes and dislikes ç
or selfish motives, (but with noble intent) are called s<193>ttvika ç
(good). If done with these, they become r<193>jasika (mixed). If they ç
are motivated by evil designs, to harm others, they are dubbed as ç
t<193>masika (dark or evil).
Occasionally the word `karma' is also used to indicate the sa<221>sk<193>ras ç
or sacraments.
@NT = Karmak<193><207><195>a
@N1 = (`branch [of the Veda<R>ç
dealing with] karma or rituals')
Hindu tradition generally divides the Vedas into two broad groups: ç
Karmak<193><207><195>a and J<210><193>nak<193><207><195>a.
The J<210><193>nak<193><207><195>a comprises the Upani<218>ads.
The Karmak<193><207><195>a deals with the various Vedic rituals including ç
the y<193>gas or sacrifices. The Br<193>hma<207>as are the main content ç
of the Karmak<193><207><195>a. The mantras in the Sa<221>hit<193> ç
section are chanted at the appropriate stages in the performance of ç
the Vedic rites.
Whereas the Ved<193>ntic systems give the Karmak<193><207><195>a a ç
lower place, the M<200>m<193><221>s<193> system makes it the chief ç
aspect of the Vedas assigning to the Ved<193>nta (or the Upani<218>adic ç
section) a subsidiary place.
See also <MS>J<178>°NAK°Ø£A.<D>
@NT = K<193>rma-mala
@N1 = (`impurities [that arise] due to karma')
<185>aivism isanimportantpartof Hinduism. The P<193>·upata cult ç
is a major aspect of the same.
According to this cult, the j<200>va or the soul in bondage called ç
`pa·u' (or animal) here has three malas or impurities that act as ç
fetters. K<193>rma-mala is the third of these. It is actually the ç
limitations that arise due to the effect of the past karmas.
Yoga helps the pa·uj<200>va to cleanse himself of all the three malas.
@SPACE1 = 
See also <MS>°ØAVAMALA,<D> <MS>M°Y®YAMALA<D> and <MS><185>AIVISM.
