@NT = karmam<193>rga
@N1 = (`the path of karma or action')
From the most ancient times, the Vedic religion has kept before man, ç
two paths†karmam<193>rga (the path of action) and j<210><193>nam<193>rga ç
(the path of knowledge). Since the former advocates activism, whereas ç
the latter upholds withdrawal from actions except those needed for ç
main- taining the body for s<193>dhan<193> or spiritual practice, ç
the two are also called, respectively, prav<216>tti-m<193>rga and ç
niv<216>tti-m<193>rga.
In the karmam<193>rga, a person entitled for it, has to avoid ni<218>iddhakarma ç
(prohi-bited or sinful actions), perform nitya andnaimittika karmas ç
(obligatory daily actions  and  occasional  ones)  without selfish ç
motives, as a duty and in a spiritof worship of God. This purifies ç
him gradually, enabling him to go to higher worlds like pit<216>loka ç
or the world of manes through the Dh<220>m<193>dim<193>rga, the path ç
of smoke.
Performance of Vedic sacrifices like the Agnihotra and the Dar·ap<220>r<207>am<193>sa ç
as also several others including those motivated by unfulfilled desires, ç
are also included in this karmam<193>rga.
See also <MS>KARMAYOGA.<D>
@NT = karmam<200>m<193><221>s<193>
@N1 = (`enquiry [into the<R>ç
philosophy of] Vedic rituals')
It is the philosophical system that tries to determine the correct ç
meaning of the karmak<193><207><195>a part of the Vedas. It is the ç
same as the M<200>m<193><221>s<193> philosophy.
See <MS>M®M°<189>S°DAR<185>ANA<D> for details.
@NT = karmasa<221>ny<193>sa
@N1 = (`renunciation of [al<L%5>l<D%0>]<R>ç
actions')
As per the sm<216>tis and dharma·<193>stras (secondary scriptures ç
dealing with personal and social conduct) a g<216>hastha or a householder ç
had to perform a number of rites and rituals. Vedic sacrifices (if ç
he had duly established the Vedic fires), nityaand naimittika karmas ç
(obligatory and occasional duties), <218>o<195>a·a sa<221>sk<193>ras ç
(sacraments) and other duties connected with personal and social life ç
would keep him so busy that he would not get sufficient time and mood ç
for spiritual pursuits. Hence he was advised to hand over the responsibility ç
of running the family to the eldest son and retire to the forest, ç
to lead the life of a v<193>naprastha (forest-recluse). There, he ç
was to maintain one Vedic fire†the g<193>rhapatya†and perform only ç
the daily agnihotra apart from the sandhy<193> ritual. Later on, he ç
was advised to send back his wife (if she had accompanied him to the ç
forest) to his eldest son and embrace monastic life which necessarily ç
involved wandering from place to place, depending entirely on God. ç
This type of life, while being conducive to spiritual aspirations, ç
did not allow him to continue the karmas or rituals. (Nor were they ç
necessary now, since he had transcended them.) Hence, he took the ç
vows of karmasa<221>ny<193>sa or renunciation of all rites and actions ç
except those needed for maintaining the body and doing s<193>dhan<193>s.
See also <MS>SA<189>NY°SA.<D>
@NT = karm<193>·aya
@N1 = (`[the potential result o<%18>f<%0>]<R>ç
karma that resides in the mind')
This is a technical word that has been used in the yoga philosophy ç
(vide Yogas<220>tras of Pata<210>jali 2.12).
When a particular karma†good or bad†is done, its unseen result will ç
`lie' (·ete) in the mind in a subtle form, until it gets a suitable ç
opportunity to be manifested. Such residual karma is called `karm<193>·aya'.
This karm<193>·aya, which may be good or bad, is born out of k<193>ma ç
(desire), lobha (greed), moha (delusion) or krodha (anger and hatred). ç
For instance, those desiringto attain svarga or heaven, perform sacrifices ç
like Jyoti<218><219>oma thereby accumulating good karm<193>·aya. Those ç
who commit sins like cheating or murder, due to greed or anger accumulate ç
bad karm<193>·aya.
This karm<193>·aya, if very intense, can produce its effect in this ç
life itself. If not, it is manifested in future births.
The results will, of course, be good or bad according to the merit ç
or demerit of the actions done.
Karm<193>·aya is sometimes called `k<193>rma·ar<200>ra' also.
See also <MS>KARMA.<D>
@NT = karmavip<193>ka
@N1 = (`fruition of karma')
The theory of karma is an extension of the proverb, `As you sow, so ç
you reap!' to the spiritual field. All the actions done by us have ç
a twofold effect: that which is seen here and now; and, their future ç
effect, depending upon whether they are pu<207>ya (good) or p<193>pa ç
(bad).
The ripening of a part of the accumulated karma, to give its result ç
is called `karmavip<193>ka'.
See also <MS>KARMA.<D>
@NT = Karmayoga
@N1 = (`yoga of karma or action')
According to all the six systems of Hindu philosophy, especially the ç
Ved<193>nta, mok<218>a or liberation from the cycle of transmigration, ç
is the final goal of human life. This can be got by realising God† ç
called °tman or Brahman or ®·vara†who is not only transcendent but ç
also immanent in every object of the universe including the human ç
being. This can be done either by j<210><193>na (knowledge) or by ç
bhakti (devotion) through the respective paths known as J<210><193>nayoga ç
and Bhaktiyoga.
However, all the schools of Ved<193>nta concede  that  ni<218>k<193>makarma  (ordained ç
actions performed without the taint of selfish desires) purifies the ç
mind†this is called `citta·uddhi'†making it fit for the paths of either ç
j<210><193>na or bhakti.
@SPACE1 = 
If God is in the heart of every human being and if the impurity of ç
mind is preventing him from getting God-experience, removing that ç
impurity should do the trick. And, ni<218>k<193>makarma pursued till ç
the whole mind is completely purified, must be able to achieve ç
this and hence God-realisation as well as mok<218>a too! This is the ç
line of argument of those who advocate that Karmayoga also, like the ç
other yogas, can be an independent path leading to mok<218>a. And, ç
there is enough support in the scriptures for this school also (vide ç
Am<216>tabindu Upani<218>ad 2, 3 and 4; ®·<193>v<193>sya Upani<218>ad ç
2; Bhagavadg<200>t<193> 3.20; 5.19; 18.46; Vi<218><207>upur<193><207>a ç
2.3.25 and so on).
Man is essentially a social being and cannot live without doing some ç
karma or the other. By guiding him in this field of karma itself, ç
Karmayoga shows him the way of spiritual evolution.
Every human being has to work at two levels: the individual or the ç
personal and, the social. The work at the individual level comprises ç
general maintenance of the body and spiritual practices for spiritual ç
evolution. The work at the social level consists of earning one's ç
livelihood and discharging one's obligations to the other members ç
of the society, including those of one's own family.
@SPACE1 = 
Our body-mind complex is the basic instrument for us, to practise ç
any yoga. Hence it must be kept in a good condition. In Karmayoga, ç
since work or activity isall important, this becomes even more vital.
Apart from this, coming to the field of work itself, the spiritual ç
aspirant following the path of Karmayoga has to implement the following, ç
as a part of his s<193>dhan<193>:
1)<+>He has to eschew completely all actions and conduct declared as ç
ni<218>iddha (sinful and hence prohibited).
2)<+>He has to renounce all k<193>mya-karma or actions motivated by ç
selfish desires, since they bind him to sa<221>s<193>ra or transmigratory ç
existence.
3)<+>On the other hand, he should never shirk from doing his ordained ç
duties or kartavyakarmas, however unpleasant they may appear to be. ç
Ordained duties are determined by the scriptures, social conventions ç
and even by what one has voluntarily chosen as a duty (provided it ç
does not transgress the basic principles of dharma).
4)<+>Since each is great in his own place, he should never think that ç
his own work (and hence himself) is greater than that of others. Everyone, ç
irrespective of his status in the society or the work that is his ç
ordained duty, is capable of attaining spiritual enlightenment by ç
cultivating the attitude that he is worshipping God through that work.
5)<+>He should also pay great attention to attaining proficiency in ç
his field of work. Efficient work, done without desires and ambitions, ç
helps one in subjective spiritual evolution. It will also benefit ç
the society greatly. And, if the society is benefited, he too should ç
be benefited.
The epics and the pur<193><207>as give us the names of quite a few ç
persons who gotenlightenment through Karmayoga. They are: a br<193>hmin ç
lady (Mah<193>bh<193>rata, Vanaparva 206); Dharmavy<193>dha (op. ç
cit. 209); Tul<193>dh<193>ra (<185><193>ntiparva 262); Janaka (Bhagavadg<200>t<193> ç
3.20).
The saint Pu<207><195>ar<200>ka (10th century <MS>A.D.<D>) from Maharashtra ç
may also be taken as an example.
A perfect karmayogi is never attached to anything in this world. He ç
has actually no duties or obligations since he has already attained ç
the final goal of life. However, he is ever active in the world, out ç
of infinite compassion for the suffering human beings and also to ç
set an example to the un-enlightened persons.
Another characteristic of his is that he works like a master and not ç
like a servant or a slave. And, his own work is so perfect that it ç
becomes a model for others to emulate.
See also <MS>KARMA.<D>
@NT = karmendriyas
@N1 = (`organs of action')
Every human being is endowed witheleven indriyas or sense-organs. ç
Theyare: the five j<210><193>nendriyas, the five karmendriyas and ç
the mind.
The five karmendriyas or organs of action are: v<193>k (speech), p<193><207>i ç
(hands), p<193>da (feet), p<193>yu (excretory organ) and upastha (organ ç
of reproduction).
These have been called `karmendriyas' because they are the indriyas ç
or sense- organs, responsible for karma or action. They are the products ç
of the rajas aspect of the five tanm<193>tras (subtle elements) as ç
follows: <193>k<193>·a (ether, space) gives rise to v<193>k, v<193>yu ç
(air) to p<193><207>i, agni (fire) to p<193>da, <193>pas (water) to ç
p<193>yu and p<216>thv<200> (earth) to upastha.
See also <MS>J<178>°NENDRIYAS<D> and <MS>TANM°TRAS.<D>
@NT = Kar<207>a
If fate, the invincible power, can ever be accused of messing up things, ç
it is in the life of Kar<207>a. Born to a would-be queen by the grace ç
of no less a deity than the Sun-god himself, he was condemned to live ç
and die in the shadow of an irredeemable villain.
He was the first offspring of Kunt<200>, the elder queen of the king ç
P<193><207><195>u. She begot him before her marriage when she experimented ç
with the powerful mantra taught to her by the sage Durv<193>sas, by ç
invoking S<220>rya or the Sun-god. Afraid of calumny, she abandoned ç
the baby-son in the stream of a river. For Adhiratha and R<193>dh<193>, ç
a couple of the charioteer caste, who retrieved the baby it was a ç
god-send since they were childless. They christened him as Vasu<218>e<207>a. ç
However he was more well-known as Kar<207>a, R<193>dheya (son of R<193>dh<193>), ç
°dhirathi (son of Adhiratha) and S<220>taputra (son of a s<220>ta ç
or a person of the charioteer caste) being the other names.
After becoming an adept in the use ofvarious weapons, he approached ç
the warrior-sage Para·ur<193>ma for higher training in the use of ç
arms. This he did in the guise of a br<193>hma<207>a since the sage ç
was a sworn enemy of the k<218>attriyas and would never accept them ç
as disciples. However almost at the end of the period of training, ç
the truth was out. The sage cursed him for having cheated him by telling ç
a lie as a result of which Kar<207>a would not be able to remember ç
the appropriate formulae connected with the divine weapons, during ç
the most critical moments in a war.
When the P<193><207><195>avas were being tested for their prowess ç
and proficiency in the use of arms at the close of their training ç
period, Kar<207>a appeared on the scene throwing a challenge that ç
he could do better than them. However, since he belonged to a caste ç
lower than that of the k<218>attriyas, he was not allowed to compete ç
with them. Consequently he was dejected. Duryodhana, the eldest of ç
the Kauravas and the P<193><207><195>ava-baiter at that, seized this ç
opportunity, accepted him as a friend on equal terms and even crowned ç
him as the king of A<209>gade·a, the country called `A<209>ga'.
This disgrace, as also the humiliation he had to suffer at Draupad<200>'s ç
svaya<221>vara (ceremony of a maiden choosing her husband) made him ç
an inveterate enemy of the P<193><207><195>avas, especially of Arjuna.
Kar<207>a now became the right-hand man of Duryodhana and antagonised ç
the P<193><207><195>avas at every opportunity he could seize. His ç
part in the ugly and indecent act  of  Du··<193>sana  trying  to  disrobe ç
Draupad<200> was not insignificant.
@SPACE1 = 
At the beginning of the Kuruk<218>etra war, K<216><218><207>a tried ç
to win him over to the side of the P<193><207><195>avas by disclosing ç
his real identity as the eldest of the P<193><207><195>avas. However, ç
Kar<207>a's loyalty to Duryodhana prevented him from being tempted ç
to change sides.
A tiff with Bh<200><218>ma, the first commander-in-chief of the Kaurava ç
army, forced  Kar<207>a  to  withdraw  from  the Kuruk<218>etra war ç
as long as he lived and led the army. It was only after the withdrawal ç
of Bh<200><218>ma from the war-front, that Kar<207>a joined the fray.
Though he fought valiantly, first as a great warrior and later as ç
the commander-in-chief, he was ultimately killed by Arjuna in the ç
single combat with him.
@SPACE = 
@NT = Kar<207>aparva
See <MS>MAH°BH°RATA.
@SPACE1 = 
@NT = kar<207>arandhra-dhauti
@N1 = (`cleaning of the ear-passages')
Cleansing the various parts of the body is an important aspect of ç
Ha<219>hayoga. Such processes are called `dhauti'. Kar<207>arandhra-dhauti ç
is the 3rd and the 4th part of Dantadhauti. It consists of cleaning ç
the two holes or passages of the ears, using the index or the ring ç
fingers. By practising it daily, some mystical sounds are supposed ç
to be heard, according to the Ghera<207><195>a Sa<221>hit<193> (1.33).
See also <MS>DANTADHAUTI<D> and <MS>DHAUTI.<D>
@SPACE1 = 
@SPACE1 = 
@NT = kar<207>avedha
@N1 = (`piercing the ear-lobes')
@SPACE1 = 
Sa<221>sk<193>ras  or  sacraments  (ritual purificatory processes) ç
are common to many religions. One of the minor sa<221>sk<193>ras  recommended  in  the  later ç
dharma·<193>stra literature is kar<207>avedha or piercing the lobes ç
of the ears of a child.
@SPACE1 = 
Since both men and women were using ear-ornaments in those days kar<207>avedha ç
used to be done both on the female and on the male child.
It used to be performed on the 10th or the 12 or the 16th day from ç
birth. Alternatively, it could be done in the 7th or the 10th month ç
after birth.
The ceremony used to be done by the father of the child with Vedic ç
mantras (vide <184>gveda 1.89.8) followed by the feeding of the ç
br<193>hma<207>as.
In the modern times, it may be done by a goldsmith with pointed gold ç
wire or even by a doctor.
@NT = K<193>rtav<200>ry<193>rjuna
Arjuna, the son of the king K<216>tav<200>rya of  Candrava<221>·a  (lunar  dynasty)  was ç
better known as `K<193>rtav<200>ry<193>rjuna'. He was the king of ç
M<193>hi<218>mat<200> in the Vindhya mountain range. A devotee of ç
Datt<193>treya (See <MS>DATT°TREYA<D>.) he had secured the boon of ç
getting one thousand arms during any war he would fight.
He had once defeated the mighty R<193>va<207>a in a battle and had ç
taken him captive.  R<193>va<207>a's  father,  the  sage Pulastya, ç
had to intervene to get him released.
During hunting, one day, he happened to enter the hermitage of the ç
sage Jamadagni and was sumptuously fed by him. The cow Kapil<193> ç
endowed with divine powers had helped him to entertain the guests. ç
When K<193>rtav<200>ry<193>rjuna asked for it to be gifted to him, ç
the sage refused. Offended by this refusal, the king killed the sage. ç
On hearing this, however, Para·ur<193>ma, Jamadagni's son, went to ç
M<193>hi<218>mati, killed the king, decimated his army and destroyed ç
his city.
@NT = kart<216>tva
@N1 = (`doership', `agency of an action')
Though the <193>tman or the Self, being pure caitanya or consciousness ç
is neither the kart<193> or the agent of an action, nor the bhokt<193>, ç
the enjoyer of its fruits, the <193>tman in bondage (called j<200>va) ç
is.
See <MS>BHOKT<184><D> for details.
@NT = K<193>rttikeya
@N1 = (`son of the presiding<R>ç
goddesses of K<216>ttik<193>')
See <MS>SUBRAHMAØYA.<D>
@NT = k<193>rya
@N1 = (`that which is done')
Widely used, this word has several senses.
As associated with the word `k<193>ra<207>a' (cause), it means the ç
effect. For instance, if clay is the k<193>ra<207>a, pot is its k<193>rya ç
or effect.
Some of the other senses in which itis used are: work, conduct, utility, ç
profession and duty.
The word is also used in a more technical sense in astrology and legal ç
works.
See also <MS>K°RAØA.<D>
@NT = k<193>rya-k<193>ra<207>a-bh<193>va
@N1 = (`causeandeffect relationship')
The six systems of Hindu philosophy generally try to establish their ç
doctrines by basing them on the Vedas and allied scriptures as also ç
logic and reasoning.
One of the basic topics discussed by these systems is the origin of ç
this world. If this world is here, now, being experienced by our senses ç
and the mind, it must have had a beginning, an original cause from ç
which it has evolved.
To prove this logically, the theory of cause  and  effect,  and,  their  mutual ç
relationship has to be stated clearly. This is technically called ç
`k<193>rya-k<193>ra<207>a-bh<193>va'. Unconditionality  and  invariability  are ç
indispensable for this.
Fire as the cause and smoke as the effect, clay as the cause and a ç
pot as the effect are the examples commonly given.
Arguing backwards, all the schools agree that there must be an original ç
cause or causes for this world. However, as to the number and nature ç
of these causes there are wide differences of opinion.
@NT = ka<218><193>ya
@N1 = (`that which upsets')
The word `ka<218><193>ya' is used in several senses depending upon ç
the particular branch of knowledge.
If it means astringent taste in the culinary sciences, it represents ç
the boiled and decanted essence of medicinal herbs, in °yurveda.
@SPACE1 = 
In the philosophical works, however, the word is used to indicate ç
those weaknesses and impurities of mind which are obstacles to spiritual ç
evolution. They may be either in a potential state or manifested fully. ç
For instance: r<193>ga (attachment) and dve<218>a (hatred). It is ç
only the person who has transcended the ka<218><193>yas that is fit ç
for mok<218>a or liberation.
@NT = K<193>·<200>
@N1 = (`that which shines [because of<R>ç
spiritual power]')
A pilgrimage to K<193>·<200> (also known as V<193>r<193><207>as<200> ç
or Banaras, in the State of Uttar Pradesh), a ceremonial bath in the ç
river Ga<209>g<193> and a visit to the temple of Lord Vi·van<193>tha, ç
has always been a lifetime's ambition for an average Hindu, right ç
from the ancient times. To him K<193>·<200> has been synonymous with ç
Hindu religion, culture, learning, arts and crafts; in fact, with ç
every aspect of Hindu civilisation. It is the only city in the whole ç
world that has kept up its halo of holiness for over three thousand ç
(or even more number of) years.
It is one of the three most holy cities, the other two being Pray<193>ga ç
and Gay<193>.
The pur<193><207>as and the dharma·<193>stras as also the digests ç
have devoted thousands of verses to expatiate upon the greatness of ç
this holy city.
The antiquity of the city is established by the fact that it has been ç
mentioned in the Br<193>hma<207>as and the Upani<218>ads in several ç
places.
It appears that K<193>·<200> was a country and its capital, V<193>r<193><207>as<200>. ç
In course of time, the capital too got the same name. Other names ç
of K<193>·<200> are: °nandak<193>nana, Avimukta, Mah<193>·ma·<193>na ç
and <185>ma·<193>na.
`Banaras' is the anglicised form of V<193>r<193><207>as<200>.
It got the name V<193>r<193><207>as<200> since it was situated between ç
two rivers Vara<207><193> and As<200>. This is now the official name ç
of the city.
It was established by Divod<193>sa, a huma<W1%19>n<D%0>incarnation ç
of the god Dhanvantari.
K<193>·<200> is reputed to have had 1500 temples at one time. Most ç
of the temples are in a dilapidated condition.
The most important temples and holy spots which a modern pilgrim normally ç
visits are the following:
@SPACE1 = 
The Vi·van<193>tha temple; the Anna-p<220>r<207><193> temple; the ç
Bindu-M<193>dhava temple; the Durgiana temple; the temple of S<220>rya ç
(Sun-god) at Lol<193>rka; the Da·<193>·vamedha- gh<193><219>; the ç
Ma<207>ikar<207>ik<193>-gh<193><219>; the Pa<210>caga<209>g<193>-gh<193><219>.
Lord Vi·van<193>tha is the tutelary deity of K<193>·<200> and his ç
temple is the centre of attraction. Every Hindu of K<193>·<200> is ç
expected to bathe in the river Ga<209>g<193> and visit the temple ç
of Vi·van<193>tha every day.
The Vi·van<193>tha temple has had a chequered  history  over  the  centuries. ç
According to Hiuen Tsang (7th century <MS>A.D.<D>) there was a copper ç
image of Deva Mahe·vara, almost 30 metres (100 ft.) in height, at ç
K<193>·<200>. Between <MS>A.<|>D.<D> 1194 and 1585 it was destroyed ç
and rebuilt many times. Due to a saintly br<193>hma<207>a, N<193>r<193>ya<207>a ç
Bha<219><219>a, it was rebuilt with the help of R<193>j<193> Todarmal ç
in <MS>A.<|>D.<D> 1585. However it was destroyed by Aurangzeb in <MS>A.<|>D.<D> ç
1669 and a mosque was built on its ruin, which is still to be seen. ç
It was Ahaly<193>b<193><200> Ho<202>kar who built the present temple ç
during the last quarter of the 18th century. This temple is situated ç
in a lane, next to the river Ga<209>g<193>. It has a tower covered ç
with gold-plated copper sheets which was the contribution of Mah<193>r<193>j<193> ç
Ra<207>ajit Si<209>gh (<MS>A.<|>D.<D> 1780-1839) and is 4.5 metres ç
(50 ft.) high. Only Hindus without caste-distinctions, are permitted ç
inside. Behind the temple is an ancient well called `J<210><193>nav<193>p<200>' ç
(well of knowledge) which was repaired in <MS>A.<|>D.<D> 1830.
The Vi·van<193>tha temple is surrounded by several other temples like ç
those of Annap<220>r<207><193>, Durg<193>, Ga<207>e·a, <185>anai·cara ç
and others.
@SPACE1 = 
The   Bindu-M<193>dhava   temple   is situated in the Pa<210>caga<209>g<193>-gh<193><219> ç
where five rivers†Kira<207><193>, Dh<220>tap<193>p<193>, Ga<209>g<193>, ç
Yamun<193> and Sarasvat<200>†meet and merge. However only the Ga<209>g<193> ç
is seen and the other four are supposed to join it from below the ç
earth.
The  Da·<193>·vamedha-gh<193><219> has  been famous for centuries. ç
Brahm<193>, the creator, is said to have performed ten A·vamedha sacrifices ç
here.
The Ma<207>ikar<207>ik<193>-gh<193><219> is, practically, a cremation ç
ground. Bodies of the dead are cremated here in the belief that <185>iva ç
liberates their souls. The pool of water here is very small. Near ç
it is the temple of T<193>rake·vara-<185>iva.
The temple of Lol<193>rka (Sun-god) is situated at the confluence ç
of the river As<200> with Ga<209>g<193>.
Since ages, the Hindus have believed that death at K<193>·<200> automatically ç
gives them liberation. Hence, the number of persons, especially the ç
old ones, living here, awaiting death, is quite large.
Those who take a vow to live in K<193>·<200> till death, are expected ç
to observe the rules of dharma very strictly and avoid all types of ç
sins.
A very important aspect of pilgrimage to K<193>·<200> is the pa<210>cakro·<200>-parikrama ç
on foot. Starting from the Ma<207>ikar<207>ik<193>-gh<193><219>, the ç
pilgrim has to walk about 80 kms. (50 miles), in a semicircle, coming ç
back to the same point at the end. The journey is to be covered in ç
six days, offering one's worship at the temples on the way and also ç
pi<207><195>as (obsequial offerings to the manes) at the village Kapiladh<193>r<193>.
K<193>·<200> is famous for the various seats of learning. The Banaras ç
Hindu University (BHU) and the K<193>·<200> Vidy<193>p<200><219>ha ç
are the two most well-known institutions of this type.
@SPACE = 
@NT = K<193>·m<200>r <185>aivism
@SPACE1 = 
See under <MS><185>AIVISM.<D>
@NT = Ka·yapa
The sage Ka·yapa has been mentioned not only in the <184>gveda (9.114.2) ç
but also in the R<193>m<193>ya<207>a (B<193>lak<193><207><195>a ç
70 and 75), the Mah<193>bh<193>rata (°diparva 63), the Vi<218><207>upur<193><207>a ç
(1.15 and 21) and theBh<193>gavata (4.1). Whether all these Ka·yapas ç
are one and the same or are different, it is difficult to say.
He was the son of the sage Mar<200>ci and grandson of Brahm<193>, ç
the creator. His mother was Kal<193>, a daughter of Kardama and Devah<220>ti. ç
He had married the 13 daughters of Dak<218>a and thereby became the ç
father of the devas (gods), asuras (demons), siddhas, gandharvas, ç
yak<218>as (all these being demigods), n<193>gas (reptiles) and other ç
animals; i.e., the whole creation. That is why, when the gotra (lineage) ç
of a person is not known, he is permitted to say `K<193>·yapagotra'. ç
(This is necessary in the performance of religious ceremonies.)
Ka·yapa and Aditi (the eldest wife) were reborn as Da·aratha and Kausaly<193>, ç
Vasudeva and Devak<200> since they had prayed to the Lord Vi<218><207>u ç
that he be born as their son.
@NT = K<193>·yapa Sa<221>hit<193>
It is a dharmas<220>tra work, attributed to the sage Ka·yapa, quoted ç
by other writers like Baudh<193>yana (600-300 <MS>B.<|>C.<D>), and ç
also later writers.
The work not available now, seems to have dealt with the usual topics ç
of dharma·<193>stras like daily duties, ·r<193>ddha (obsequial  rites),  a·auca  (ceremonial ç
impurity), pr<193>ya·citta (expiation for sins) and so on.
A manuscript discovered a few years back, called Ka·yapasm<216>ti ç
is in prose and deals with the duties of the householders, expiation ç
for polluting public places like wells, ponds and temples, expiations ç
for killing cows and other animals as also other sins, rules concerning ç
mourning after death, purification of vessels of wood and metal and ç
so on.
@NT = Ka<219>ha Upani<218>ad
The Ka<219>ha Upani<218>ad belongs to the K<216><218><207>a Yajurveda. ç
Since it is included in the K<193><219>haka recension of that Veda, ç
it is also called K<193><219>haka Upani<218>ad.
The story of Naciketas and Yama (the god of death) is very ancient ç
and finds a mention even in the <184>gveda (10.135). The Taittir<200>ya ç
Br<193>hma<207>a (3.1.8) gives an outline of the same story. In this ç
Upani<218>ad, the story gets a fuller treatment. Actually the whole ç
work is in the form of a dialogue between Naciketas and Yama. It is ç
spread over six vall<200>s or sections and the total number of verses ç
is 119.
@S10N = First vall<200> (29 verses)
V<193>ja·ravasa, also known as Audd<193>laki °ru<207>i, was performing ç
the Vi·vajit sacrifice. He was, as per the rules of the sacrifice, ç
to give away all his wealth. However, he had arranged to donate ç
decrepit, useless cows as sacrificial gifts. This was observed by ç
Naciketas, his young son in early boyhood. A precocious boy that he ç
was, he sensed his father's motive in doing so. Wishing to draw his ç
attention, to this lacuna, Naciketas asked his father as to whom he ç
was being gifted away. Incensed by the repeated questioning, the father ç
shot back saying that he would be given to M<216>tyu (Yama, the god ç
of death). Though he repented for his intemperate reaction, he allowed ç
Naciketas to go to the Yamaloka, the abode of Yama. When the boy reached ç
there Yama was not in his house. So he patiently awaited the god's ç
return, spending three days and three nights without accepting any ç
hospitality. When Yama returned and learnt about the young guest, ç
he regretted the inconvenience caused to him and offered him three ç
boons to compensate for the same.
Naciketas asked, as the first boon, that his father regain his mental ç
peace and balance and also recognize him (Naciketas) after returning ç
from the abode of death.
As the second, he requested Yama to teach him the sacrifice by which ç
one could go to svargaloka (heaven). Yama obliged and taught the process ç
in detail. He even tested Naciketas at the end to know whether he ç
had grasped all the intricacies of the ritual. Naciketas' reply so ç
pleased him that he granted him (Naciketas) an additional boon in ç
the form of a beautiful necklace. He also christened the fire-ritual ç
as `N<193>ciket<193>gni'.
@SPACE1 = 
As the last of the boons, Naciketas asked Yama whether a human being ç
continued in existence even after the death of the physical body, ç
or not. Since this question related to <193>tmaj<210><193>na or a ç
know-ledge of the divine Self which was extremely subtle and difficult ç
to comprehend, Yama wanted to test the boy thoroughly before imparting ç
the same. Acquisition of <193>tmaj<210><193>na has to be preceded ç
by an intense spirit of renunciation and total dedication to its pursuit. ç
Hence Yama tried to dissuade him by describing it as extremely difficult ç
to comprehend and offered exceedingly attractive alternatives like ç
immense wealth, intense pleasures and unimaginably long life. However, ç
Naciketas being made of sterner stuff, rejected them all with disdain ç
and insisted upon his original boon.
@S10N = Second Vall<200> (25 verses)
Yama does not directly answer the question of Naciketas but begins ç
his long discourse by introducing some basic concepts as a background.
Human beings generally have two alternatives in life: the ·reyas (what ç
is really good in the ultimate analysis) and the preyas (what is momentarily ç
attractive and pleasant, but ultimately disastrous). The wise ones ç
with an intuitive insight choose the former whereas the dull-witted ç
persons who lack even elementary sense of discrimination, fall for ç
the latter. Having done so, these latter ones consider themselves ç
as very intelligent and clever. Not only that, they even mislead the ç
innocent persons. It is like the blind leading the other blind ones! ç
Thus they get into the grip of the lord of death through repeated ç
transmigrations.
Those who choose the path of ·reyas will realize the <193>tman, the ç
true self ofall.
This <193>tman is beyond logic and reasoning and is difficult to comprehend ç
by the ordinary run of mankind. But it can be understood if taught ç
by a person who has realised his identity with it. It is hidden deep ç
within oneself and can be attained by adhy<193>tmayoga, yoga of inner ç
contemplation.
Yama then expounds the art of meditation on the <193>tman/Brahman ç
with the help of Pra<207>ava or Om. Om is the best symbol for Brahman ç
and also the best means for attaining that Brahman.
°tman/Brahman is smaller than the smallest and greater than the greatest. ç
It is also established in the hearts of all. It can be realised by ç
the pure, calm and controlled mind. One who realises it goes beyond ç
death and rebirth.
Neither the study of the scriptures and  encyclopaedic  knowledge  nor  the ç
retentive power of memory can help in attaining the <193>tman. Only ç
an intense desire to know it, can make the seeker succeed in his efforts.
Yama also stresses the importance of a clean moral life and of self-control ç
in this endeavour.
@SPACE = 
@S10N = Third Vall<200> (17 verses)
@SPACE = 
The most important teaching of this section is the allegory of the ç
chariot to describe the j<200>v<193>tman, the individual soul enmeshed ç
in the body-mind complex. The body is the chariot. The senses are ç
the horses. The mind is the reins. The intellect is the charioteer. ç
The Self is the master of the chariot. The objects of the senses are ç
the road by which the chariot moves.
If the horses are controlled by an expert charioteer, he can take ç
the chariot to the right destination. An inefficient charioteer and ç
restive horses will lead the chariot astray into a ditch and endanger ç
the life of its owner.
Similarly one who can control his senses through a disciplined mind ç
will reach the final goal of his life, viz., the abode of Vi<218><207>u ç
(i.e., liberation). On the other hand, a person of impure mind and ç
uncontrolled senses will end up in sa<221>s<193>ra or transmigration.
The <193>tman or the Self, also called `puru<218>a' (divine being), ç
who is deeply hidden in one's heart can be seen or realised by a person ç
of refined and subtle mind through concentration. For this, one has ç
to awaken to this reality and approach the great spiritual teachers, ç
to learn from them, because, the path that leads to this <193>tman ç
is extremely difficult to tread.
@S10N = Fourth Vall<200> (15 Verses)
This vall<200> starts with a statement of fact that our senses always ç
tend to go outwards and consequently we are inte-rested in the outside ç
world. However, once in a while, some wise person discovers that what ç
is really worth knowing in life is the pratyag<193>tman, the Self ç
within. Hence he turns the gaze of the senses and the mind inwards ç
and realises him there. But the ignorant, childish persons continue ç
to revel in the outside world of sense-objects and get into the bondage ç
of transmigration.
Yama then declares that it is possible to realise the <193>tman through ç
the pure and refined mind.
Yama describes the <193>tman residing inthe hearts of all, as of ç
the size of the thumb,since the heart is of that size. Even so, he ç
is the lord of the past, present and future (because, in the ultimate ç
analysis he is Brahman).
Once a person realises this <193>tman, he becomes united with him ç
even as one pure water mixed with another pure water becomes identical ç
with it.
@S10N = Fifth Vall<200> (15 verses)
This short section begins by describing the human body as a pura or ç
city in which the <193>tman, its lord lives. Meditation on him delivers ç
one from the bondage of transmigration.
Then comes an interesting, even poetical, account of that <193>tman: ç
He moves every where. He is the sun and the moon. He exists in every ç
object of the universe. He manages the biological functions of the ç
body from inside. In fact, it is his residence in the body that makes ç
it full of life and consciousness.
Then there is a description of the transmigration of the unredeemed ç
souls. Their next lives are determined by their karma, good or bad. ç
If some are reborn as living beings of the higher or the lower type, ç
others may even enter inert objects!
Quoting the examples of fire, air and the sun, the Upani<218>ad goes ç
on to describe that Brahman as the inner Self (anta-r<193>tman) of ç
all beings, seems to appear in different forms, identifies with those ç
forms, and also simultaneously exists in his own, outside them. Even ç
as the sun, while shining on all objects†pure and impure†himself remains ç
untainted, Brahman too remains untainted for ever.
Only those who realise this <193>tman/ Brahman, succeed in attaining ç
everlasting peace and not the others.
@S10N = Sixth Vall<200> (18 verses)
This last vall<200> sets out with the description of the sa<221>s<193>ra ç
v<216>k<218>a, the tree of the world, in a poetical language. It is ç
an inverted tree, with the root above and the branches below. This ç
root is Brahman.
This Brahman, (also called Pr<193><207>a here) the origin and power ç
of sustenance of the whole creation, is so terrific that it strikes ç
fear in the hearts of all, functioning as a part of this universe. ç
Thesun shines, the fire burns and the wind blows out of his fear. ç
While Indra discharges his duties, M<216>tyu or the god of death just ç
runs away!
The Upani<218>ad then urges all human beings to realise this <193>tman/Brahman ç
before the fall of the body. It also declares the superiority of the ç
<193>tman over all other aspects of the body and the mind. It gives ç
a brief account of yoga as self-control andconcentration by which ç
the <193>tman is realised. For this, it is necessary to conquer and ç
destroy all the desires in the mind. Once this is done, man becomes ç
immortal.
Here, the text brings in the idea well-known in the other Upani<218>ads ç
also, that the realised soul leaves by the n<193><195><200> (subtle ç
tubular structure) in the crown of the head, which is connected with ç
the arcir<193>dim<193>rga (or the bright path, the path of light) ç
and goes to Brahmaloka, the Abode of Brahman, never to return again ç
to the mundane existence.
For this realisation, one must know the art of separating the Self ç
from the body even as the stalk of the mu<210>ja grass is drawn out ç
of its sheath. This can be done by a direct experience of the inner ç
Self, the <193>tman, through the knowledge that he is pure and deathless, ç
immortal.
@SPACE1 = 
The last verse of the Upani<218>ad gives us encouragement and hope, ç
and also instils confidence in us. Brahmavidy<193> and mok<218>a or ç
am<216>tattva (liberation and immortality) were not the special ç
prerogative of Naciketas or persons like him (who had the courage ç
and conviction to go to the world of Yama and return alive) but of ç
all of us, provided we too know the path from competent persons and ç
practise adhy<193>tmayoga properly.
From all standpoints this Upani<218>ad has been quite popular. The ç
philosophical concepts and the practical modes of s<193>dhan<193> ç
described here are reminiscent of  the  popular  Hindu  scripture,  the ç
Bhagavadg<200>t<193>.
@NT = K<193><219>haka G<216>hyas<220>tras
@SPACE1 = 
The G<216>hyas<220>tras are a part of the Kalpa or Kalpas<220>tra ç
literature, which itself is one of the six Ved<193><209>gas (subsidiary ç
literature that aids the study of the Vedas). The K<193><219>haka ç
G<216>hyas<220>tras is one of the four G<216>hyas<220>tras belonging ç
to theK<216><218><207>a Yajurveda. It is also known by other names ç
such as Carakag<216>hya, C<193>r<193>ya<207><200>yag<216>hya and ç
Laug<193>k<218>ig<216>hya.
This work has been quoted by others, like Hem<193>dri (13th century ç
<MS>A.<|>D.<D>). Since it has five kha<207><195>as or chapters, it ç
is also called G<216>hyapa<210>cik<193>. Three commentaries have ç
been discovered so far. They are: Vivara<207>a of °dityadar·ana, ç
Paddhati of Br<193>hma<207>abala and Bh<193><218>ya of Devap<193>la.
The contents are very similar to those of the other g<216>hyas<220>tras ç
like those of °pastamba or Baudh<193>yana.
@NT = Kathakal<200>
Dance, like music, has always been a means by which human beings have ç
tried to express their inner feelings. For instance, the rustic villagers ç
express their gratitude to the deities of nature even now, through ç
their folk-dances during the harvest season. In most of the societies ç
there are dances for every important social occasion.
Indian dance is said to have originated from <185>iva and P<193>rvat<200>, ç
the divine couple, the parents of the world. Gods like Ga<207>apati ç
and K<216><218><207>a, minor deities like Nandi and Bh<216><209>gi, ç
goddess Sarasvat<200>†all of them are fond of dancing.
Kathakal<200> is a speciality of the Kerala State and Malay<193><202>am ç
culture. It seems to have originated from folk-dances with paur<193><207>ic ç
themes.
It has three varieties: K<220>ttu, R<193>ma-n<193><219><219>am and ç
K<216><218><207>an<193><219><219>am.
@SPACE1 = 
The K<220>ttu dance was the privileged possession of the C<193>ky<193>r ç
community of Kerala. It used to be exhibited in temples during festival ç
days, the themes being chosen from paur<193><207>ic legends or even ç
famous incidents culled from history.
The other two are identical in form and pattern except that the former ç
has R<193>ma episodes and the latter K<216><218><207>a episodes for ç
their themes.
In the Kathakal<200>, the dancers do not speak or sing but express ç
all the sentiments through acting. The themes are invariably from ç
Hindu mythology. Colours of the dress and ornaments are apportioned ç
as per the nature of the character, viz., whether it is s<193>ttvik, ç
r<193>jasik or t<193>masik.
The Kathakal<200> dances are usually held in the open fields and that ç
too in moonlight.
Announcing  about  the  Kathakal<200> programme, invocatory verses ç
from behind the screens, beating of drums, entry of the first dancer, ç
narration of the story from the background, dance and acting by the ç
persons playing the various roles, their conversations being recited ç
in the background†these are the various aspects of the programme.
@SPACE = 
@NT = Ka<219>ha Sa<221>hith<193>
@SPACE1 = 
See <MS>K°<187>HAKA SA<189>HIT°<D>.
@SPACE = 
@NT = K<193><219>haka Sa<221>hit<193>
@SPACE = 
The K<216><218><207>a Yajurveda has four ·<193>kh<193>s or recensions. ç
The K<193><219>haka Sa<221>hit<193> (or Ka<219>ha Sa<221>hit<193>) ç
is the third in that series.
Not many followers of this Sa<221>hit<193> are found now, even in ç
South India which is the home of K<216><218><207>a Yajurveda.
This work has five k<193><207><195>as or sections. These k<193><207><195>as ç
are, again, divided into subsections known as `sth<193>nakas'.
A brief description of the same may now be given:
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(1.1108,.4583,E1), ç
ABOVE(.0417), BELOW(.0833), VGUTTER(.0555), KEEP(OFF)
@Z_TBL_BODY = TC1, TABLE TEXT, TC1
K<193><207><195>a<+><+><+>   <+> Sth<193>nakas, +, Contents
@Z_TBL_BODY = TL, TL, TL
1.<+>I<219>himik<193>k<193><207><195>a, <+><+>18, puro<195><193>·a (rice-cake),<R>ç
adhvara,, some<|>y<193>gas<R>ç
like V<193>japeya and R<193>jas<220>ya.
2.<+>Madhyamik<193>-<R>ç
         k<193><207><195>a, <+><+>12, S<193>vitr<200>,, svarga (heaven),, ç
d<200>k<218>ita (consecrated sacri-<R>ç
ficer),, <193>yu<218>yahoma <R>ç
and so on.
3,, 4 and 5.<R>ç
   Oramik<193>k<193><207><195>a, <+><+>10, Sattra,, C<193>turm<193>sya,<R>ç
sava,, Sautr<193>ya<207><%42><200><%0>etc.
@Z_TBL_END = 
The five k<193><207><195>as with forty sth<193>nakas contain in all, ç
3091 mantras.
(Note: Details of the technical terms used here may be found under ç
the particular headings.)
@NT = Ka<219>harudropani<218>ad
The Ka<219>harudropani<218>ad is a minor Upani<218>ad classed among ç
those belonging to the K<216><218><207>a Yajurveda. It has 47 mantras, ç
both in prose and in ·lokas. It is mainly devoted to sa<221>ny<193>sa ç
or monastic life and its fruit, viz., the knowledge of Brahman.
It is in the form of a dialogue between the gods and Praj<193>pati. ç
In reply to the request of the gods to teach about brahma-vidy<193>, ç
Praj<193>pati expatiates on sa<221>ny<193>sa and its result.
A householder who desired to take to the life of a sa<221>ny<193>sin ç
(monk) should ceremonially give up all the insignias of a br<193>hma<207>a ç
like the ·ikh<193> (tuft of hair), yaj<210>opav<200>ta (sacred thread) ç
and the Vedic fires.
He should hand over the responsibilities of the family to the eldest ç
son.
While taking leave of the family members, he should not shed tears! ç
(Nor should they!)
Then, the Upani<218>ad describes briefly how a person should pass ç
through the firsttwo stages of life†brahmacarya and g<193>rhasthya†and ç
then renounce all things connected with them.
A sa<221>ny<193>sin should not kindle the Vedic fires again. He should ç
desire thewell-being of all persons. He should move about without ç
any fixed place for dwelling, living on alms only. He must also renounce ç
all possessions which are normally allowed for the lower type of ç
sa<221>ny<193>sins, like the kama<207><195>alu (water bowl), p<193>duk<193>s ç
(footwear), kanth<193> (covering cloth) and so on.
He is also expected to observe brahmacarya (celibacy) very strictly.
@SPACE1 = 
The Upani<218>ad ends with a long description of the fruit of brahmaj<210><193>na ç
or knowledge of Brahman, which is the same as is normally found in ç
other Upani<218>ads.
@NT = K<193>ty<193>yana
@SPACE = 
@SPACE = 
K<193>ty<193>yana is one of the ancient sages credited with the authorship ç
of many works.
The  <185>rautas<220>tra  of  K<193>ty<193>yana belongs to the <185>ukla ç
Yajurveda and has 26 chapters. The y<193>gas described in the <185>atapatha ç
Br<193>hma<207>a are dealt with in this work in greater detail. There ç
is a Karkabh<193><218>ya, a commentary attributed to one Kark<193>c<193>rya, ç
on this work.
K<193>ty<193>yana is also the author of a <185>ulbas<220>tra with ç
seven ka<207><195>ik<193>s or sections. It deals mainly with the construction ç
of the vedis or platforms for the performance of Vedic sacrifices. ç
The knowledge of geometry revealed in this work is astonishing.
Two more works on the Vedas, attributed to K<193>ty<193>yana are available ç
now: Sarv<193>nukrama<207><200> on the <184>gveda and a similar ç
work on the <185>ukla Yajurveda.
Many authors of dharma·<193>stras like <185>a<209>kha-Likhita, Y<193>j<210>avalkya ç
and Par<193>·ara have considered K<193>ty<193>yana as an important ç
expounder of dharma.
Though his original work on the various aspects of dharma is not available ç
now, numerous quotations from his work are seen in the nibandhas or ç
digests by other authors.
One K<193>ty<193>yanasm<216>ti,  also  called Karmaprad<200>pa, ç
available now is in three prap<193><219>hakas (sections) divided into ç
29 kha<207><195>as (chapters) and has 500 verses. This work contains ç
miscellaneous topics like wearing of sacred thread, worship of deities ç
like Ga<207>e·a and the M<193>t<216>k<193>s, details of some implements ç
useful in Vedic sacrifices,  personal  hygiene,  Sandhy<193> ritual, ç
the five daily sacrifices, ·r<193>ddha and so on.
The date of K<193>ty<193>yana has been approximately placed between ç
the 4th and the 6th centuries <MS>A.<|>D<D>.
There is another K<193>ty<193>yana (a grammarian), the author of v<193>rttik<193>s ç
or critical explanatory and complementary notes on certain rules of ç
P<193><207>ini's Sanskrit grammar. Pata<210>jali (200 <MS>B.<|>C.<D>), ç
the composer of the Mah<193>bh<193><218>ya on P<193><207>ini's A<218><219><193>dhy<193>y<200> ç
often quotes his v<193>rttikas.
@NT = K<193>ty<193>yan<200>
@N1 = (`daughter of [the sage] Kata')
One of the forms of the Divine Mother, she is so called because she ç
was once born as the daughter of the sage Kata. She is one of the ç
nine forms of Durg<193> (Navadurg<193>s). Iconographical works describe ç
her in different ways. She has three eyes and her body is bent in ç
three places (tribha<209>ga). She may be shown with four or eight ç
or even ten arms. The objects commonly shown in her hands are: kha<195>ga ç
(sword), khe<219>a (shield), kamala (lotus), abhayamudr<193> (gesture ç
of protection), tri·<220>la  (trident),  dhanus  (bow),  b<193><207>a ç
(arrow), a<209>ku·a (goad), p<193>·a (noose), ·akti (a special weapon) ç
para·u (battle axe) and gha<207><219><193> (bell).
A lion as her mount and the demon Mahi<218><193>sura below her left ç
foot are also shown sometimes.
In the Bh<193>gavata (10.22.1-5) the young girls of the cowherds ç
are described to have performed a religious rite called `K<193>ty<193>yan<200>-vrata' ç
(worship of the Mother-goddess K<193>ty<193>yan<200>) in order to ç
get K<216><218><207>a as their husband. From this it can be surmised ç
that K<193>ty<193>yan<200> is an ancient folk goddess.
@NT = kaula
See <MS>TANTRAS.<D>
@NT = Kaul<193>c<193>ra, Kaulam<193>rga
`Kula' means <185>akti or the Divine Mother. The `V<193>m<193>c<193>ra' ç
or the `left-handed path' of the Tantras is also called `Kaul<193>c<193>ra' ç
and `Kaulam<193>rga'.
See <MS>TANTRAS<D> for details.
@NT = Kaum<193>r<200>
@N1 = (`feminine aspect of Kum<193>ra')
<185>akti or the Divine Mother is said to have seven aspects known ç
as `Sapta-m<193>t<216>k<193>s'. Kaum<193>r<200> is one of them. She ç
is the <185>akti or the feminine aspect of Kum<193>ra, also known ç
as <186>a<207>mukha, Subrahma<207>ya, K<193>rttikeya, Skanda and by ç
several other names.
Kaum<193>r<200> is pictured as having six heads and twelve arms. Red ç
in complexion and draped in red garments she rides on a peacock.
The twelve hands exhibit or hold varadamudr<193> (bestowal of boons), ç
·akti (spear), pat<193>k<193> (banner), da<207><195>a (staff), gha<207><219><193> ç
(bell), dhanus (bow), b<193><207>a (arrow), kamala (lotus), kukku<219>a ç
(cock), khe<219>aka (shield), para·u (axe) and p<193>tra (bowl).
She is one of the <185>aktis or goddesses that emerged out of Durg<193>'s ç
body during her fight with <185>umbha and Ni·umbha and their army.
@NT = Kaumodak<200>
Most of the gods of the Hindu pantheon are shown with weapons of various ç
kinds. One of the common weapons is the gad<193> or mace.
The gad<193> of Vi<218><207>u is named `Kaumodak<200>' since it gives ç
`moda' or happiness to `ku' or the earth, by protecting it against ç
the asuras (demons) and other evil forces.
It was fashioned out of the extremely strong bone of an asura called ç
Gad<193>. Gad<193> gave up his body in deference to the wishes of ç
Brahm<193>, the father of creation. Then Brahm<193> got it made by ç
Vi·vakarm<193>, the celestial engineer. It was then deposited with ç
the god Varu<207>a.
When K<216><218><207>a got the Kh<193><207><195>ava forest consumed ç
by Agni, with the help of Arjuna, Agni requested Varu<207>a to give ç
it to K<216><218><207>a as a sign of his gratitude to K<216><218><207>a. ç
Iconographical works show Gad<193> as a female deity. Symbolically, ç
it stands for cosmic intellect.
@NT = Kausaly<193>
She was the daughter of a king Bh<193>num<193>n, the eldest queen ç
of Da·aratha and the mother of <185>r<200>r<193>ma.
Da·aratha and Kausaly<193> were Ka·yapa and Aditi reborn.
See <MS>R°M°YAØA<D> for details.
@NT = Kau·ika
@N1 = (`a descendent of [the sage] Ku·ika')
Vedic studies and the performance of severe austerities can bestow ç
upon a person special powers. However, the sincere and devoted performance ç
of one's duties in life also can confer such powers is a fact that ç
has been stressed in our epics and mythological lore.
One of the well-known stories narrated in the Mah<193>bh<193>rata ç
(Vanaparva 209) is that of a br<193>hma<207>a ascetic named Kau·ika. ç
Once, he was sitting for meditation under a tree. It so happened that ç
a crane sitting on the tree eased itself and its faeces fell upon ç
him. He opened his eyes and gazed at it with an angry look. And lo! ç
the poor bird was reduced to ashes in no time!
Later on Kau·ika went into the nearby village for alms and stood in ç
front of a house, calling the attention of the inmates. When the lady ç
of the house came out with the alms after a long time, the sage Kau·ika ç
stared at her with an angry look. She however coolly said that she ç
was not a poor crane to be affected byhis
