@NID = (perfect  concentration,  superconscious experience).
Pata<210>jali recommends kriy<193>yoga for the benefit of ordinary ç
s<193>dhakas, who are incapable of practising all the eight steps.
The three disciplines†tapas or auste-rity, sv<193>dhy<193>ya or study ç
of the scriptures as also the japa of pra<207>ava (Om) and <200>·varapra<207>idh<193>na ç
(surrendering the fruits of actions to God)†together form kriy<193>-yoga. ç
They are called `kriy<193>yoga' since they are in the form of kriy<193> ç
(activity) and lead to yoga (union with God) in course of time.
Tapas or austerity consists of physical austerity like serving the ç
elders and continence, austerity of speech like speaking the truth ç
and the study of the Vedas, and, austerity of mind like purity of ç
emotions.
Sv<193>dhy<193>ya includes the study of scriptures that help in the ç
path towards kaivalya (liberation) and the repetition of mantras like ç
Om and the G<193>yatr<200>.
®·varapra<207>idh<193>na comprises offering all actions and their ç
fruits at the feet of God.
This kriy<193>yoga helps in the attenuation of evil qualities and ç
ultimately leads to sam<193>dhi.
@NT = Kriy<193>yogas<193>ra
Pur<193><207>as and upapur<193><207>as have done yeoman service in ç
spreading morality and religion among the masses.
The B<216>had-dharma-pur<193><207>a (1.25) gives a list of upapur<193><207>as ç
in which Kriy<193>yogas<193>ra is also one. It is a Vai<218><207>ava ç
work composed by someone in Bengal, probably in the 13th or the 14th ç
century <MS>A.<|>D<D>.
Its teachings can be summarised as follows:
K<216><218><207>a is Vi<218><207>u himself. The Bh<193>gavatapur<193><207>a ç
has to be studied well to  understand  him.  D<193>syabhakti,  the ç
attitude of a servant towards the master, is the best for an ordinary ç
s<193>dhaka. Another discipline useful to the s<193>dhakais kriy<193>yoga. ç
It means yoga through kriy<193>or work. This can take the form of ç
worshipping the Ga<209>g<193>, Vi<218><207>u and Lak<218>m<200>, showing ç
respect to the br<193>hma<207>as, giving gifts to worthy and needy ç
persons, observing ek<193>da·<200> as a religious ritual with fasting ç
and worship, hospitality to guests and honouring the tulas<200> plant.
This work seems to be a distinct and independent work confined to ç
Bengal and throws some light on the contemporary society.
@NT = k<216>kala
@N1 = (`pertaining to the throat')
The human system, according to the treatises on the Ved<193>nta, works ç
with the help of five major pr<193><207>as (pa<210>capr<193><207>as, ç
five vital airs) and five minor ones which are subsidiaries of the ç
major pr<193><207>as (hence called upapr<193><207>as).
K<216>kala is one of the five upapr<193><207>as, said to be an aspect ç
of sam<193>na (one of the five major pr<193><207>as). It is responsible ç
for the act of sneezing.
@NT = K<216><218><207>a
@N1 = (also, <185>r<200>k<216><218><207>a)
@SB = 1.	Introduction
The philosophy of the Upani<218>ads is characterized by a rational ç
temper, a passion for the welfare of the human beings and a spirit ç
of harmony as applied to the whole world. This philosophy, though ç
impersonal in itself, has yet been the womb of a galaxy of personalities ç
who have shone brilliantly in the horizon of India. R<193>ma and K<216><218><207>a ç
are the brightest of these stars; and, they have dominated the pages ç
of Indian cultural history for centuries. Not only that,they have ç
become models for emulation for later ages.
Between the two, it is perhaps, K<216><218><207>a who has influenced ç
the Indian thought, life and culture in a more profound way. He has ç
entered, not only into its religion and philosophy, but also into ç
its mysticism and poetry, painting and sculpture, music and dancing, ç
and all aspects of the Indian folklore. To say the least, he has mesmerized ç
a whole people for generations. Where else can one seek for the secret ç
of this mesmerism of K<216><218><207>a except in his great character ç
and noble life?
And yet, it is a strange irony that no other person in India's history ç
and culture has been subjected to so much of unsympathetic or even ç
foul criticism, based on either an incomplete or an incorrect understanding ç
of all the facts available, if not a deliberate distortion of the ç
same to serve an ulterior purpose. True, there have also been presentations ç
of his personality by over-enthusiastic votaries that rob quite a ç
bit of the grace of a wondrously graceful personality. Hence an attempt ç
will be made here to steer clear of the extremes and give a fairly ç
balanced assessment of his life, personality and work.
@SB = 2.	Several K<216><218><207>as
We come across several K<216><218><207>as in the Hindu scriptures. ç
The <184>gveda (1.116.23) mentions one K<216><218><207>a, the father ç
of a Vi·vak<193>ya. The last ma<207><195>ala or section of the same ç
work (10.42-44) attributes two s<220>ktas or hymns to the sage K<216><218><207>a. ç
We meet with a K<216><218><207>a °<209>girasa in the Kau<218><200>taki ç
Br<193>hma<207>a (30.9) and a K<216><218><207>a H<193>r<200>ta in ç
the Aitareya °ra<207>yaka (3.26). Then there is K<216><218><207>a ç
Dvaip<193>yana, also called Vy<193>sa, the reputed author of the epic ç
Mah<193>bh<193>rata. It can safely be assumed that none of these ç
K<216><218><207>as is the K<216><218><207>a of our study.
However, the Ch<193>ndogya Upani<218>ad (3.17.6) mentions K<216><218><207>a-Devak<200>putra ç
as a disciple of Ghora °<209>girasa by whom he was taught the science ç
of Puru<218>ayaj<210>a. It is very likely that this is the same as ç
K<216><218><207>a, the son of Vasudeva and Devak<200>. The only snag ç
is that S<193>nd<200>pani has been specifically mentioned as<|>the ç
guru or preceptor of K<216><218><207>a and not Ghora °<209>girasa.*
Some scholars opine that the K<216><218><207>a we worship today is ç
a syncretic deity of four personalities: Vi<218><207>u (a solar deity), ç
N<193>r<193>ya<207>a (of some theistic philosophical systems), V<193>sudeva ç
(of the Bh<193>gavata cult) and Gop<193>la (a cowherd king of °bh<200>ra). ç
However, this much has to be conceded that at the time of the epic ç
story of the Mah<193>bh<193>rata, K<216><218><207>a was already ç
well-known, considered not only as a very great person, but, even ç
deserving worship as a manifestation of the Divine.
@SPACE = 
@SB = 3.	Date of K<216><218><207>a
@SPACE1 = 
@SPACE1 = 
Since K<216><218><207>a took an active part in the<+>Mah<193>bh<193>rata ç
war, his date naturally depends upon the date of this war. Scholars ç
have been battling for decades to fix its date. Adopting various methods ç
like philological considerations of the language of the epic, or, ç
allowing an average length of period of a ruler and calculating backwards ç
from the time of a known ruler whose date has been fixed, the European ç
scholars* have generally assigned it to the period 1400<192>300<|><MS>B.<|>C.<D> ç
Indian scholars,<F20W1><185><F255D> who have seriously weighed the internal ç
astronomical evidence, have concluded that the latest date can be ç
around 1400<|><MS>B.<|>C.<D> They are more inclined, however, to accept ç
the period 3200 to 3100 <MS>B.<|>C.
@SPACE = 
@SB = 4.	Sources of the K<216><218><207>a Story
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
The primary sources of the K<216><218><207>a story are four: the Mah<193>bh<193>rata, ç
and its adjunct Hariva<221>·a, the Vi<218><207>upur<193><207>a ç
and the Bh<193>gavata. The story is also met with in other pur<193><207>as ç
like the Brahmapur<193><207>a, Padmapur<193><207>a and Brahmavaivarta-pur<193><207>a ç
(K<216><218><207>ajanma-kha<207><195>a).
In the Mah<193>bh<193>rata, K<216><218><207>a appears for the first ç
time during the marriage of Draupad<200> with the P<193><207><195>avas. ç
Though there are casual references to his earlier life, no details ç
have been given. To make up for this lacuna, as it were, the Hari- ç
va<221>·a was added as an adjunct, later. It is a fairly long work ç
of over 16,000 verses and deals with the story of K<216><218><207>a ç
in great detail in the section called Vi<218><207>uparva. The Vi<218><207>upur<193><207>a ç
(<F51320MS>A. D.<W1> 300; 6000 verses) is one of the earliest pur<193><207>as ç
and deals with the story of K<216><218><207>a in the fifth<|>section ç
(pa<210>cam<193><221>·a). The <F255MI>Bh<193>gavata (<F51320MS>A. D.<W1> 600; ç
18,000 verses) seems to be an expanded version of the <F255MI>Vi<218><207>upur<193><207>a ç
in that it deals with practically the same topics, but in much greater ç
detail.
@SPACE = 
@SB = 5.	Story of K<216><218><207>a in brief
@SPACE = 
The story of K<216><218><207>a may now be stated briefly, following ç
the accounts given in the Mah<193>bh<193>rata and the Bh<193>gavata.
Mother Earth, unable to bear the burden of sins committed by evil ç
kings and rulers, of whom Ka<221>sa of Mathur<193> and Jar<193>sandha ç
of Magadha were the worst, appealed to Brahm<193>, the Creator for ç
help. Brahm<193> prayed to the Supreme Lord N<193>r<193>ya<207>a and ç
got the assurance that He would soon be born in this world to eliminate ç
all the evil doers.
Ugrasena of the Y<193>dava race, was the ruler of the kingdom of Mathur<193>, ç
with its capital at the city of Mathur<193>. His son Ka<221>sa, the ç
crown prince, was a tyrant, dreaded by all and it was he that was ç
practically ruling the kingdom. When Devak<200>, a daughter of Devaka, ç
the cousin of Ugrasena, came of age, she was married to Vasudeva, ç
the son of <185><220>rasena, another Y<193>dava chieftain. Ka<221>sa ç
who loved his sister Devak<200>, took the couple out for a ride on ç
a royal chariot, driving it himself. A voice from the void (<193>k<193>·a-v<193><207><200>) ç
warned him that the eighth issue of the couple would destroy him. ç
Enraged and unnerved by this quirk of fate, Ka<221>sa was about to ç
kill Devak<200>. Vasudeva intervened and averted the tragedy to his ç
wife, by promising to hand over all the children born of her. Though ç
Ka<221>sa spared Devak<200>'s life, not being prepared to take chances, ç
he put the couple in prison.
@SPACE1 = 
Vasudeva kept up his word. Ka<221>sa mercilessly slaughtered the first ç
six sonsof Devak<200>. The seventh foetus was mysteriously transferred ç
to the womb of Rohi<207><200>, the elder wife of Vasudeva, now living ç
at Gokula, a cowherd settlement, across the river Yamun<193>. She ç
gave birth to a hefty boy. Then the Lord entered into Devak<200> and ç
she conceived for the eighth time. Now she shone with a brilliance ç
that was matchless but soothing. Ever since Ka<221>sa came to know ç
of it, he started living in mortal fear. On the blessed day when nature ç
was at its best to welcome the Lord, He appeared to the couple in ç
all His glory and instructed Vasudeva to exchange him for the baby-girl ç
just born to Ya·od<193>, wife of the cowherd chief Nanda, at Gokula. ç
Then He assumed the form of an extremely charming human baby. The ç
instructions were carried out faithfully. Under the divine spell, ç
the gates of the prison opened up, the guards slept and the river ç
Yamun<193> made way for the transportation of the divine infant.
When Ka<221>sa arrived at the prison next morning on hearing the news, ç
he found a baby-girl in his sister's lap! Since fear of death had ç
dehumanized him, he dashed the babe against a boulder. But, it escaped, ç
flew up into the sky, assumed the fierce form of Yogam<193>y<193> ç
(Durg<193>) and prophesied that his enemy was living elsewhere and ç
would soon kill him.
@SPACE1 = 
The divine child started growing at Gokula giving the greatest joy ç
to one andall by his bewitching beauty and supremely charming pranks. ç
All attempts of Ka<221>sa to kill the child were set at nought by ç
the little fellow who dispatched demon after demon to the abode of ç
death.
Garga, the family priest of the Y<193>davas arrived at Gokula and ç
secretly performed the n<193>makara<207>a (the ritual of christening) ç
for the two children. Rohi<207><200>'s son was christened as R<193>ma ç
or Balar<193>ma and Ya·od<193>'s baby-son as K<216><218><207>a.
The exploits of K<216><218><207>a at the cowherd settlement included ç
revealing the whole universe in his little mouth to his mother Ya·od<193> ç
and felling the twin trees by dragging the grinding stone to which ç
he had been tied, in between them. Meanwhile, the elders of the village ç
decided to abandon Gokula and migrate to V<216>nd<193>-vana, a nearby ç
place, which offered better facilities for a new settlement. It proved ç
to be very attractive to the brothers Balar<193>ma and K<216><218><207>a.
Apart from extirpating some more emissaries of death dispatched by ç
Ka<221>sa, K<216><218><207>a's adventures at V<216>nd<193>vana included ç
subduing and driving away the serpent K<193>liya from the river to ç
the sea, lifting the Govardhana hill up with his little finger and ç
holding it like an umbrella to protect the people of V<216>nd<193>vana ç
from the torrential rain caused by Indra (the king of gods in heaven) ç
who had been annoyed by K<216><218><207>a's stopping of worship to ç
him, the R<193>sa dance with the gop<200>s on the banks of Yamun<193> ç
and rescuing his foster-father Nanda from drowning.
@SPACE1 = 
Finding that all his efforts to assassinate the two children were ç
in vain, Ka<221>sa decided to get them to his capital on the pretext ç
of a royal invitation and contrived to kill them there. Accordingly ç
he sent Akr<220>ra, a Y<193>dava chief, with a chariot to V<216>nd<193>vana ç
to bring the two brothers. Balar<193>ma and K<216><218><207>a seized ç
this opportunity and went there gladly. After a few more bouts of ç
adventure in the capital and in the palace, K<216><218><207>a killed ç
Ka<221>sa, freed his parents Vasudeva and Devak<200>, as also his ç
grandfather Ugrasena who was then re- installed on the throne.
Vasudeva, then, arranged for the upanayana (a religious sacrament ç
done at the commencement of Vedic studies) and education of the boys ç
under the preceptor S<193>nd<200>pani,  living  at  Avant<200>pura.  The ç
geniuses that they were, Balar<193>ma and K<216><218><207>a mastered ç
the well-known sixty-four sciences and arts in just sixty-four days. ç
They returned to Mathur<193> after restoring to the preceptor his ç
dead son at his request, as gurudak<218>i<207><193> (respectful offering ç
to the preceptor as a mark of gratitude).
Jar<193>sandha, the emperor of Magadha, started invading Mathur<193> ç
with his huge army. Though beaten back, he was returning again and ç
again. So, K<216><218><207>a built an impregnable capital Dv<193>rak<193> ç
in an island in the sea and shifted the people there.
@SPACE1 = 
Soon after this, Balar<193>ma and K<216><218><207>a married Revat<200> ç
and Rukmi<207><200>, the daughters of Revata and Bh<200><218>maka. ç
K<216><218><207>a also married J<193>mbavat<200>, the daughter of ç
J<193>mbav<193>n, and, Satyabh<193>m<193>, the daughter of Satr<193>jit.
Narak<193>sura, the demon king of Pr<193>g-jyoti<218>apura, had abducted ç
and imprisoned 16,000 princesses. K<216><218><207>a invaded his kingdom, ç
killed him in the battle, released the girls and married them, since ç
they had nowhere else to go.
Vasudeva had a sister, P<216>th<193> by name †but more well-known ç
as Kunt<200>†who had been married to prince P<193><207><195>u, the ç
ruler of Hastin<193>pura. He died early, leaving five young sons (later ç
known as the P<193><207><195>avas) to the care of Kunt<200>. She took ç
refuge in Bh<200><218>ma, the grandsire of the Kuru race, who brought ç
them up along with the hundred Kauravas, sons of the blind king Dh<216>tar<193><218><219>ra, ç
the elder brother of P<193><207><195>u. Jealousy and enmity of the ç
Kauravas towards the P<193><207><195>avas forced the latter to go ç
into exile. After many a travail, they reached K<193>mpilya, the capital ç
of southern P<193><210>c<193>la kingdom ruled by Drupada, just in ç
time for the svaya<221>vara (marriage by self-choice) of his daughter ç
Draupad<200>. Disguised as br<193>hma<207>as they too were sitting ç
in the assembly.
K<216><218><207>a also had come there along with Balar<193>ma. He ç
immediately recognized the P<193><207><195>avas. After the failure ç
of all the princes, Arjuna, the third of the P<193><207><195>ava brothers, ç
succeeded in piercing the fish fixed on a special contrivance called ç
matsya-yantra, thus passing the prescribed test. That a beggarly br<193>hma<207>a ç
succeeded where mighty princes failed, naturally roused the wrath ç
of the kings assembled there. When they started a fight with the P<193><207><195>avas, ç
K<216><218><207>a intervened, reminding them all that Arjuna had won ç
the hand of Draupad<200> according to dharma or righteous and just ç
way. This cooled their frayed tempers and an ugly situation was averted.
Once, while on a pilgrimage, Arjuna came to Dv<193>rak<193> and fell ç
in love with Subhadr<193>, the sister of K<216><218><207>a. Since ç
the love was mutual and since Arjuna was the best match for her, K<216><218><207>a ç
successfully contrived to get them married.
@SPACE1 = 
When the P<193><207><195>avas got their share of half the kingdom, ç
and wanted to build the capital, it was K<216><218><207>a who helped ç
them to clear the Kh<193><207><195>ava forest and establish their ç
capital there. It came to be known as Indraprastha or Kh<193><207><195>avaprastha.
Yudhi<218><219>hira, the eldest of the P<193><207><195>avas wanted ç
to perform the R<193>jas<220>ya sacrifice. K<216><218><207>a encouraged ç
him to undertake this ambitious venture. Since the performer of the ç
R<193>jas<220>ya sacrifice would be proclaimed as the emperor, all ç
opposition had to be overcome before taking it up.
Jar<193>sandha of Magadha was a mighty king and a tyrant. He had to ç
be conquered first, as a part of that victory expedition. K<216><218><207>a, ç
along with Arjuna and the mighty Bh<200>ma (the second of the P<193><207><195>avas), ç
wentto the capital of Jar<193>sandha in disguise, challenged him ç
to a dual with Bh<200>ma and got him killed. He then crowned Jar<193>sandha's ç
son Sahadeva as the king of Magadha. He also released from prison ç
the large number of princes and kings held captive by Jar<193>sandha.
The R<193>jas<220>ya went off on a grand scale. When the question ç
of who should be offered the `agrap<220>j<193>'†worship offered to ç
the best of the assembled men, the highest honour bestowed on such ç
occasions †came up, there was near unanimity in favour of K<216><218><207>a. ç
The lone dissenter was <185>i·up<193>la, the king of Cedi, who did ç
so, out of an old enmity. Since he abused K<216><218><207>a, Bh<200>ma ç
and others in that august assembly and even challenged them to fight ç
him, K<216><218><207>a was obliged to kill him using his celebrated ç
discus, the Sudar·ana.
@SPACE1 = 
Unable to bear the prosperity of the P<193><207><195>avas, Duryodhana, ç
the eldest of theKauravas challenged Yudhi<218><219>hira, the eldest ç
of the P<193><207><195>avas, to gambling through a game of dice. The ç
latter, who had a weakness for the game, succumbed; but was defeated ç
by the wily <185>akuni, uncleof the Kauravas, who played as Duryodhana's ç
substitute. In the process Yudhi<218><219>hira lost everything including ç
his brothers, wife Draupad<200> and also himself. Then, Duryodhana ç
forcibly got Draupad<200> to the assembly hall and an attempt was ç
made by Du··<193>sana, the second of the Kaurava brothers, to disrobe ç
her. Her fervent prayers to K<216><218><207>a brought him there in ç
an invisible form, who protected her modesty by multi-plying her robes ç
to infinite length. Then Dh<216>tar<193><218><219>ra, the blind king, ç
got Draupad<200> released and restored to the P<193><207><195>avas ç
theirlost wealth and kingdom. They returned to Indra- prastha and ç
resumed their rule.
However, prodded by the evil counsels of <185>akuni, his uncle, Duryodhana ç
succeeded once again in extracting a promise from the blind king Dh<216>tar<193><218><219>ra ç
to challenge the P<193><207><195>avas for a second round of the game ç
of dice. Yudhi<218><219>hira, with his proverbial weakness for the ç
same, succumbed to it and lost his kingdom. As per the stakes he was ç
banished to the forest. When the P<193><207><195>avas were living ç
in the forest, undergoing great hardship, K<216><218><207>a came to ç
know of it and arrived there to console them and advise them. K<216><218><207>a ç
toldYudhi<218><219>hira that if he were at Hastin<193>pura, the capital ç
of the Kauravas, he would have left no stone unturned to prevent the ç
game by impressing upon all, the evils of such gambling.
After  successfully  completing  the period of banishment, the P<193><207><195>avas, ç
who had gathered in Vir<193><219>anagara, the capital of the country ç
Matsya, celebrated the marriage of Abhimanyu (son of Arjuna and Subhadr<193>) ç
with Uttar<193> (daughter of the king Vir<193><219>a and Sude<218><207><193>, ç
his second wife). K<216><218><207>a and Balar<193>ma attended the ç
same. While discussing the future plans of the P<193><207><195>avas ç
in the assembly that had gathered there, K<216><218><207>a advised ç
them all to think of any course that will bring the good of both ç
the P<193><207><195>avas and the Kauravas.
Seeing that Duryodhana was obdurate in refusing to part with even ç
the minutest part of his kingdom for the sake of the P<193><207><195>avas, ç
K<216><218><207>a decided to make a last attempt at restoring peace ç
between them. He tried hard and sincerely, but without success.
@SPACE1 = 
When it was finally decided that war was the only way out for the ç
P<193><207><195>avas to get back their kingdom, K<216><218><207>a ç
was wooed by both the parties. When he offered the choice of the mighty ç
Y<193>dava army on one side or himself, but unarmed, on the other, ç
Arjuna chose him. Duryodhana was happy to get the army.
Before the commencement of the war at Kuruk<218>etra, K<216><218><207>a ç
tried to win over Kar<207>a, the king of A<209>gade·a and a warrior ç
of exceptional valour, to the side of the P<193><207><195>avas, but, ç
without success.
During the war which lasted for eighteen days, K<216><218><207>a, ç
at the request of Arjuna, consented to be his charioteer. At the very ç
outset, he had to deliver the great sermon, now well-known as the ç
Bhagavadg<200>t<193>, to rouse Arjuna who, suddenly, being overcome ç
by a moral stupor, had refused to fight.
This  worked  and  Arjuna  fought vali- antly. K<216><218><207>a also ç
played many an important role, but always in defence of dharma.
The P<193><207><195>avas emerged victorious at the end and the Kauravas ç
were decimated. After the coronation of Yudhi<218><219>hira as the ç
king at Hastin<193>pura, K<216><218><207>a retired to Dv<193>rak<193>.
After a few years, the Y<193>davas, the kinsmen of K<216><218><207>a, ç
fell into evil ways of life and exterminated one another in mutual ç
fighting, at Prabh<193>sa, a place near Dv<193>rak<193>. K<216><218><207>a ç
taught spiritual wisdom to Uddhava, his friend and disciple, and ascended ç
to his abode after casting off his body which was shot at by a hunter ç
named Jara.
@SB = 6.	Personality of K<216><218><207>a
Whether  K<216><218><207>a-V<193>sudeva  was  a human being or God-incarnate, ç
there is no gainsaying the fact that he has been ruling the hearts ç
of millions of Hindus for over three millennia. If a person can make ç
such a profound impact on the Hindu race affecting its psyche and ç
ethos and all aspects of its life for centuries, he is no less than ç
God. And, the Hindus do believe that he was an avat<193>ra, God Himself ç
come down to save mankind.
An avat<193>ra or incarnation of God is not a product of history but ç
creates it and shapes it. The primary purpose of an avat<193>ra, as ç
K<216><218><207>a himself has stated in the G<200>t<193> (4.<|>7,<|>8) ç
is to re-establish dharma or righteousness on a firm foundation. This ç
needs protecting and strengthening the hands of the good people who ç
protect dharma; and, if need be, subduing and eliminating the evil ç
ones who are out to destroy it. To achieve this he will use all the ç
powers and resources at his command. But, in the process, he does ç
not and need not give up his human character. If at all, at times, ç
he may transcend it, just to exhibit to the human beings the possibility ç
of rising to superhuman levels, if only they exert themselves sufficiently.
A study of K<216><218><207>a's character and personality from this ç
angle will not only be useful but also inspiring.
Throughout his life, K<216><218><207>a's sole concern was dharma; ç
to uphold it, to protect it and to reassert its supremacy; and to ç
unravel its mystery whenever it became inscrutable.
@SPACE1 = 
Dharma becomes just an ethereal concept unless it lives in the minds ç
and hearts of human beings and gets expressed through their actions. ç
Hence, K<216><218><207>a was very much concerned about human beings, ç
especially the underprivileged or the weaker sections of the society ç
as also women. The care he bestowed on the cowherds of V<216>nd<193>vana, ç
his curing Kubj<193> of her deformity, his protecting the honour of ç
Draupad<200> at a critical moment or his bestowal of wealth on the ç
poor Kucela, reveal this.
K<216><218><207>a, though possessing a heart `softer than a flower,' ç
could exercise an adamantine will and terrific valour when necessary, ç
in defence of dharma and the dh<193>rmic people. In fact, he was the ç
strongest man and the greatest warrior of his times. He knew no fear, ç
nor tasted defeat at any time in his life. The demons he killed, the ç
tyrants he subdued were legion. He was an expert in the martial arts.
All the same, he was not a war- monger. He was a master statesman, ç
skilled in the art of peace too. He was interested in peace; but not ç
at the cost of dharma.
There is a common belief that brain and brawn cannot go together. ç
But K<216><218><207>a was an extraordinary exception. His scholarship ç
in the Vedic lore and the secular sciences and arts, was renowned. ç
His three G<200>t<193>s, the Bhagavadg<200>t<193>, the Anug<200>t<193> ç
and the Uddhavag<200>t<193> are standing monuments to his learning ç
and wisdom.
He possessed a tremendous intellect, and an intuitive insight, coupled ç
with immense common sense, which he often brought to bear upon knotty ç
problems or nasty situations solving them in the best interest of ç
all concerned. His going to Hastin<193>pura as a peace emissary, his ç
trying to win over Kar<207>a to the side of the P<193><207><195>avas ç
or his apparently questionable strategies during the Kuruk<218>etra ç
war bespeak of this.
@SPACE1 = 
Intelligence and learning do not nece-ssarily lead to culture and ç
refinement. Arrogance or craftiness is the more common result. But ç
K<216><218><207>a was a perfect gentleman. When he killed Ka<221>sa ç
or got Jar<193>sandha eliminated, he put Ugrasena and Sahadeva on ç
the thrones though he could have easily usurped them. He was the first ç
to honour elders, br<193>hma<207>as, sagesandothers, showering respect ç
wherever it was due. Even in the face of grave provocation, he could ç
be calm and nonchalant. The remarkable tolerance he exhibited towards ç
the cantankerous <185>i·up<193>la is a case to the point.
@SPACE1 = 
K<216><218><207>a was not only a philosopher but an accomplished yogi ç
or mystic as well; hence the epithet `Yoge·vara' applied to him (vide ç
G<200>t<193> 18. 78). The Bh<193>gavata narrates several incidents ç
wherein he had displayed yogic powers. Giving a vision of Vi<218><207>u ç
to Akr<220>ra, the Y<193>dava emissary who had come to V<216>nd<193>vana ç
or curing Kubj<193>-Trivakr<193> of her physical handicap are instances ç
to the point.
Mysticism and activism rarely go together; but in K<216><218><207>a, ç
they did. K<216><218><207>a was ever active, ever busy, in the best ç
interest of the world. From the cradle to the grave, his life was ç
one continuum of dynamic activity; but always for the good of others ç
and never for himself. The very personification of selflessness, he ç
lived ever for others.
K<216><218><207>a as a rule, followed old customs, kept up time-honoured ç
traditions; but would not make a fetish of the same. If in his judgment, ç
any such custom needed to be altered or even given up, or replaced ç
with another, he would unhesitatingly do so. He stopped the worship ç
of god Indraby the cowherds at V<216>nd<193>vana and substituted ç
it with the worshipping of the cows and the Govardhana Hill which ç
were the backbone of their agrarian society. He acceded to Arjuna's ç
request to be his charioteer, though such a job was considered to ç
be menial, reserved for the lowborn ones because, he knew that any ç
help rendered to the P<193><207><195>avas would help the cause of ç
dharma.
Above  all,  K<216><218><207>a  was  intensely human. He responded ç
to every human emotion in an appropriate way making the persons concerned ç
feel at home with him, even important. His parents Devak<200> and ç
Vasudeva, his foster parents Ya·od<193> and Nanda, his mates at Gokula ç
and V<216>nd<193>vana, the gop<200>s, his own wives like Rukmi<207><200> ç
and Satyabh<193>m<193>, the Y<193>dava chieftains, the P<193><207><195>avas, ç
the elders at Hastin<193>pura, even cows, monkeys or horses, in fact ç
everyone that came in touch with him, was never left untouched by ç
his magic touch of their hearts. His bewitching beauty, enchanting ç
music of his flute and honey-sweet words as also irrefutable logic ç
behind them could enslave even the gods; what to speak of the poor ç
human beings! It is but natural that he was called `Puru<218>ottama,' ç
the best of human beings.
@SB = 7.	In Defence of K<216><218><207>a
Does K<216><218><207>a who staked his life to defend and protect the ç
defenceless ones, himself need defence? It appears so, on the face ç
of it, if only we look at the spate of criticisms and abuses heaped ç
upon him by the aliens to Indian culture or decultured Indians themselves ç
who are aliens in their own society.
At the outset, one thing has to be made clear. The criticisms levelled ç
against K<216><218><207>a are based on the story as depicted in the ç
Mah<193>bh<193>rata and the Bh<193>gavata. These two works have ç
declared the greatness, nay, the divinity, of K<216><218><207>a in ç
nouncertain terms calling him as the Supreme Lord Himself. If the ç
detractors of K<216><218><207>a accept as true only those parts of ç
these works that come in handy for their criticism and conveniently ç
ignore the rest, they are no wiser than the guy who wanted to cut ç
an egg into two halves, keep one half for hatching chicken and use ç
the other half for preparing an omelet!
@SPACE1 = 
Jesting apart, it is yet possible tooffer satisfactory explanations ç
to the objections and criticisms raised against K<216><218><207>a.
These criticisms fall under two broad categories: those pertaining ç
to his relationship with the gop<200>s (cowherd women) of V<216>nd<193>vana ç
and those related to the various stratagems he adopted to get victory ç
for the P<193><207><195>avas.
The former again, is related to two well-known incidents as given ç
in the Bh<193>gavata: gop<200>vastr<193>pahara<207>a (snatching ç
away the clothes of the gop<200>s) and R<193>sal<200>l<193> (R<193>sa-dance). ç
Neither the Vi<218><207>upur<193><207>a nor the Hariva<221>·a ç
refers to the first episode. The second is dealt with in all the three ç
works.
K<216><218><207>a snatches away the robes of the bathing gop<200>s ç
and perches himself atop a nearby tree along with his friends. When ç
the gop<200>s plead for the return of their robes, he asks them to ç
come up from water and stand with uplifted arms to receive them from ç
him. This is the gist of the episode as given in the Bh<193>gavata ç
(10.22).
The gop<200>s were kum<193>rik<193>s, girls in the prepuberty age-group ç
(vide 10.22.1). K<216><218><207>a was just seven years old (vide ç
10.26.3). Hence it is foolish to attribute any sexual motives to K<216><218><207>a ç
here. Actually, the girls were undergoing a religious vow (called ç
K<193>ty<193>yan<200>-vrata) to get K<216><218><207>a as their husband! ç
(10.22.4)
Having seen for themselves all the superhuman acts of K<216><218><207>a ç
even from babyhood, they were convinced of his greatness and divinity. ç
Hence they had mentally cherished conjugal love towards him. This ç
attitude of a soul towards the Divine is well-known as k<193>ntabh<193>va ç
or madhurabh<193>va (bridal mysticism) in the works on devotion and ç
mysticism. It is very much present in Christianity and Sufism too. ç
One who wants to approach God should eschew a<218><219>ap<193>·as ç
or eight infirmities that bind a soul like gh<216><207><193> (hatred), ç
·a<209>k<193> (doubts), bhaya (fear), lajj<193> (shame) and so on. ç
What is depicted here is just symbolic of this, of total surrender ç
of the j<200>vas or souls to God by giving up all bonds of life; and ç
hence should be studied in the proper perspective.
@SPACE1 = 
The five chapters 29 to 33, of the tenth skandha or book of the Bh<193>gavata, ç
are called R<193>sapa<210>c<193>dhy<193>y<200> and deal exclusively ç
with K<216><218><207>a's play with the gop<200>s.
One  moonlit  night  K<216><218><207>a  plays tantalizing tunes on ç
his flute, sitting on the bank of the river Yamun<193>. On hearing ç
it, unable to control themselves, the gop<200>s rush to the spot.
K<216><218><207>a non-chalantly asks them the purpose of their coming ç
to him at that hour and advises them to return home. They refuse, ç
express their desire to enjoy his company and beg him for the same. ç
K<216><218><207>a obliges them with amorous sports seeing that they ç
have totally given up everything for his sake. After some time, conceit ç
creeps into their minds and hearts, thinking that the Lord of the ç
universe is their mate. Sensing it, and to teach them a lesson, K<216><218><207>a ç
suddenly vanishes from their midst. Stricken with remorse, the gop<200>s ç
wail and wander, pine for and pray to him. After chastising them thus, ç
K<216><218><207>a reappears in their midst to their great delight ç
and dances the R<193>sa-dance, multi-plying himself so that each gop<200> ç
has a K<216><218><207>a with her. All the while, the people at the ç
homes of the gop<200>s, have not missed them at all! They continue ç
to `exist' there! This is the summary of this section.
Now, the question is: By sporting with the wives of other people, ç
did not K<216><218><207>a behave like an ordinary paramour? If so, ç
was it not against even the primary norms of dharma?
In fact, such a question was raised by the king Par<200>k<218>it himself ç
(vide Bh<193>gavata 10.33.27-29).
@SPACE1 = 
At the outset, an interesting fact has to be brought to light. During ç
the R<193>jas<220>ya sacrifice performed by the king Yudhi-<218><219>hira, ç
K<216><218><207>a was chosen by the gathering for the `agrap<220>j<193>' ç
or `first worship'. <185>i·up<193>la, the ruler of the Cedi kingdom, ç
who was an inveterate enemy of K<216><218><207>a, vehemently opposed ç
it and rained abominable abuses upon him. But he did not so much as ç
even mention K<216><218><207>a's illicit relationship with the gop<200>s ç
of V<216>nd<193>vana! (vide Mah<193>bh<193>rata, Sabh<193>parva, ç
ch. 39 and 40) Since the Mah<193>bh<193>rata is the earliest of ç
the works on K<216><218><207>a, can we say that the gop<200>-episodes ç
are the poetical fancies of the later writers who were eager to propagate ç
the cult of K<216><218><207>abhakti or devotion to K<216><218><207>a? ç
Such an answer will remove the very ground from under the feet of ç
the objectors!
However, since the Hariva<221>·a, considered as an adjunct to the ç
epic to complete the K<216><218><207>a story, deals with the R<193>sal<200>l<193> ç
episode, an earnest attempt can be made to meet the objection squarely. ç
Since the objection itself is based on the Bh<193>gavata, the rebuttal ç
also should be based on the same.
The gop<200>s were not ignorant of K<216><218><207>a's greatness and ç
divinity (vide Bh<193>gavata 10.<|>29.<|>32,<|>33,<|>37; 10.31.3,<|>4,<|>9). ç
They had been captivated by the bewitching beauty of the K<216><218><207>a-form, ç
even as everyone else in the Vraja (V<216>nd<193>vana) had been. ç
The woman in them had gotthe upper hand and so, they had approached ç
him as their lover. This type of love orapproach is not unknown to ç
human history. Many a mystic, both of the East and the West, has cultivated ç
this type of love towards the Divine. °<209><195><193><202>, Akka ç
Mah<193>dev<200> and M<200>r<193> of India, St. Teresa of Avila of ç
Spain and Rabiya of Basra, Iraq are the well-known mystics who prove ç
this point.
@SPACE1 = 
K<216><218><207>a was not a libertine, nor a paramour. It is the gop<200>s ç
that approached him with love tainted by sex-passion. Considering ç
it more as a disease that vitiates pure love, he treated them with ç
sympathy, responding to their love, but without himself being affected ç
by it (vide Bh<193>gavata 10.33.26). It is more like the parents ç
or teachers responding to the whims of children in a healthy and dignified ç
way, gradually leading them to wisdom. This worked and the gop<200>s ç
were put back on the road of rectitude (ibid 10.47.18, 46; 10.82.40, ç
48, 49). The gop<200>s were not unchaste. They remained faithful to ç
their husbands. The only person whom they loved, apart from their ç
husbands, was K<216><218><207>a and none else. This they did, knowing ç
full well, that he was the Lord Himself.
Wonder of wonders, the men-folk of Vraja never felt that they had ç
been separated from their wives! (ibid 10.33.38)
All this is from the subjective standpoint of K<216><218><207>a and ç
the gop<200>s. From the objective standpoint, did not K<216><218><207>a ç
transgress dharma? If yes, has he not set a bad example to the world ç
for centuries? This is exactly the question that the king Par<200>k<218>it ç
put to the sage <185>uka, the narrator of the Bh<193>gavata (vide ç
10.33. 27-29).
<185>uka in his reply classifies men into three groups: the ®·varas ç
(Lords, Incarnations), the j<200>vanmuktas (the liberated ones) and ç
the ordinary people.
@SPACE1 = 
Those who realize God in this very life are called j<200>vanmuktas. ç
According to the Hindu scriptures like the Upani<218>ads, they have ç
transcended even dharma and hence are not bound by the dos and don'ts ç
of this world. Nor are they tainted evenby grave sins (vide Kau<218><200>taki ç
Upani<218>ad 3.1).
These j<200>vanmuktas get that power bymeditating on the lotus feet ç
of God. Then, what to speak of K<216><218><207>a, who is God Himself! ç
He can transgress the ordinary norms of dharma for extraordinary ends ç
in life, which are always for the good of others. The acts of such ç
®·varas cannot be and should not be emulated by the ordinary beings. ç
<185>iva drank the deadly poison h<193>l<193>hala. Fire can destroy ç
everything it touches. But ordinary mortals can never do it. K<216><218><207>a ç
responded to the love of the gop<200>s for their sake and never ç
for his own sake. Even in doing so he multiplied himself, out of ç
his m<193>y<193> power, to be with them all simultaneously. He was ç
also, at the same time, present as gop<200>s in their houses, doing ç
their normal work. Hence, the supra-dh<193>rmic doings of ®·varas ç
like K<216><218><207>a cannot be and should not be emulated by the ç
ordinary run of mankind. If someone can do all that K<216><218><207>a ç
did, then, he, like K<216><218><207>a, is an ®·vara and so, can take ç
liberties with dharma!
@SPACE1 = 
That is why Swami Vivek<193>nanda, whose life was unsullied and whose ç
criticism spared none who was not above board, has spoken of K<216><218><207>a ç
at V<216>nd<193>vana in these glorious terms: `Ah! that most marvellous ç
passage of his life, the most difficult to understand, and which none ç
ought to attempt to understand until he has become perfectly chaste ç
and pure, thatmost marvellous expansion of love, allegorized and ç
expressed in that beautiful play at Vrindaban, which none can under- ç
stand but he who has become mad with love, drunk deep of the cup of ç
love! Who can understand the throes of the love of the Gopis†the very ç
ideal of love, love that wants nothing, love that even does not care ç
for heaven, love that does not care for anything in this world or ç
the world to come?... A great landmark in the history of religion ç
is here, the ideal of love for love's sake, duty for duty's sake, ç
and it for the first time fell from the lips of the greatest of Incarnations, ç
Krishna, and for the first time, in the history of humans, upon the ç
soil of India.' (The Complete Works of Swami Vivekananda, Vol. 3, ç
1984 edn., pp. 257-258.)
Allied to this is the criticism that K<216><218><207>a had married ç
16,008 wives, a staggering number by any standards! The `a<218><219>amahi<218><200>s' ç
were the eight queens, chief among them being Rukmi<207><200> and ç
Satya-bh<193>m<193>. The other 16,000 were the princesses he had saved ç
from the prison of the demon Naraka. Since they had been practically ç
deserted by their relatives, K<216><218><207>a gave them shelter for ç
which ceremonial marriage was a necessity. And, polygamy was quite ç
common<|>among kings and princes during those days. It is important ç
to note that the divine sage N<193>rada, once, out of curiosity, visited ç
the houses of all the wives of K<216><218><207>a and found him ç
there (Bh<193>gavata 10.69).
@SPACE1 = 
Sometimes an esoteric interpretation is given to this. The number ç
16,000 really represents 16, the zeros being the reflection of poetic ç
fancies. And, this 16 actually represents the 16 parts of the human ç
personality with which the j<200>v<193>tman, the individual soul, ç
is associated. They are: five organs of perception, five organs of ç
action, five vital airs and the mind. The j<200>v<193>tman is the ç
lord of all these 16 parts. Hence they are allegorically represented ç
as his wives. Since, in the ultimate analysis (as per Advaita Ved<193>nta) ç
the j<200>v<193>tman is identical with Param<193>tman or God, K<216><218><207>a ç
is depicted as having 16(000) wives.
An allegorical interpretation is also given for the love of the gop<200>s ç
towards K<216><218><207>a. The gop<200>s represent the j<200>vas or ç
the individual souls pining for reunion with the Param<193>tman or ç
the Supreme Soul who is K<216><218><207>a, from whom they have been ç
separated.
The second category of objections that pertain to K<216><218><207>a's ç
way of handling the various problems that arose during the Kuruk<218>etra ç
war may now be taken up. He is accused of political perfidy and Machiavellian ç
methods in his dealings with the Kauravas. It is therefore necessary ç
to examine the various episodes and incidents of the Mah<193>bh<193>rata ç
and get at the truth. They may be listed and tackled as follows:
@SPACE = 
@SPACE1 = 
@NO = 1.
@NOK = He tried to break the friendship of Kar<207>a with Duryodhana ç
and wean him away from the Kauravas.
@SPACE1 = 
@SPACE1 = 
K<216><218><207>a never wanted the fratricidal war of Kuruk<218>etra ç
to take place. Having failed in his peace mission due to the recalcitrance ç
of Duryodhana, he made a final attempt to somehow stop it by revealing ç
to Kar<207>a the well-kept secret that he was really the first son ç
born to Kunt<200>. If Kar<207>a had agreed to defect to the P<193><207><195>ava ç
side, Duryodhana, having come to know the truth, might have agreed ç
to his being the king of half the kingdom and both the groups could ç
have lived in peace. Kar<207>a was the best friend and the main source ç
of strength of Duryodhana. His loss would certainly have had a demoralizing ç
effect on Duryodhana forcing him for a compromise. Thus bloodshed ç
would have been avoided and dharma kept up. Hence what K<216><218><207>a ç
did was really a master stroke of statesmanship.
@SPACE = 
@NO = 2.
@NOK = Though he had taken the vow of renouncing weapons and not ç
fight during the war, he broke the same and attacked Bh<200><218>ma.
@SPACE1 = 
@SPACE1 = 
When Bh<200><218>ma was fighting so fiercely that the P<193><207><195>ava ç
forces were being merci-lessly destroyed or put on the run, K<216><218><207>a ç
found that Arjuna was not putting forth his best against Bh<200><218>ma ç
due to an inherent softness towards him. It was then that K<216><218><207>a ç
decided to take up his discus and attack Bh<200><218>ma himself. He ç
was stopped by Arjuna halfway with the promise of doing his best (Mah<193>bh<193>rata, ç
Bh<200><218>maparva, 59.103). Then, K<216><218><207>a returned to ç
the chariot.
The act of K<216><218><207>a was more to induce and inspire Arjuna ç
than himself fight Bh<200><218>ma. Again, the primary purpose of K<216><218><207>a's ç
life was to uphold and protect dharma. For him no sacrifice was too ç
great compared to this task; and, transgressinga vow when needed ç
was a part of the same.
It is necessary to mention here that the popular story that Bh<200><218>ma ç
too had vowed that he would force K<216><218><207>a to take to arms ç
and that K<216><218><207>a, pleased by his intense devotion, obliged ç
him by breaking his own vow is not found in the Mah<193>bh<193>rata.
@SPACE1 = 
@NO = 3.
@NOK = K<216><218><207>a induced Yudhi<218><219>hira to tell a lie ç
(`a·vatth<193>m<193> hata<199>'†A·vatth<193>m<193> has been killed) ç
camouflaging it like truth, by adding the words `ku<210>jara<199>' ç
(`elephant'), to force the invincible Dro<207>a to retire from the ç
battle.
The original verse in the Mah<193>bh<193>rata attributed to Yudhi<218><219>hira ç
is: tamatathyabhaye magno jaye sakto yudhi<218><219>hira<199><F49P12W1>e<F255P255D> ç
a·vatth<193>m<193> hata iti ·abdamuccai·cac<193>ra ha<F49P12W1>e<P12.5M> ç
<F255P255MI>avyaktamabrav<200>d r<193>jan hata<199> ku<210>jara ityuta<F49P12W1>f<F255P255D> ç
(Dro<207>aparva 190.55). `Yudhi<218><219>hira, O king, afraid of ç
telling an untruth, but interested in victory, addressed Dro<207>a ç
thus in a loud voice: ``A·vatth<193>m<193> is dead.'' But, he also ç
added the words, ``The elephant is dead'' in an inaudible voice'.
If we accept this version as a part of the original text (and not ç
an inter- polation), then we will be obliged to concede that Yudhi<218><219>hira ç
told a blatant lie at the instance of K<216><218><207>a, to discomfit ç
Dro<207>a, notwithstanding the fact that Bh<200>ma had just then killed ç
an elephant of the same name, A·vatth<193>m<193>.
But, fortunately, there are strong reasons to believe that this is ç
an interpolation carelessly added by a raw hand at a later period. ç
The same may now be summarized briefly as follows:
a.<+>Contrary to the common belief, Dro<207>a did not lay down arms, ç
even on hearing this shocking news, but continued to fight, routing ç
Dh<216><218><219>adyumna and others. Thus, the very purpose of telling ç
that lie has been nullified (Dro<207>aparva, ch. 191).
@SPACE1 = 
b.<+>It is unthinkable that Bh<200>ma, fearlessness personified, who ç
dared to face even the N<193>r<193>ya<207><193>stra discharged by ç
A·vatth<193>m<193> against the advice and persuasion of even K<216><218><207>a, ç
would stoop to such mean levels as killing an elephant by name `A·vatth<193>m<193>' ç
and give grist to the mill of falsehood. It is, by the same standards, ç
absurd to think that Yudhi-<218><219>hira, the Dharmar<193>ja (king ç
of dharma), would have allowed himself to utter a falsehood, that ç
too against his preceptor; and that, K<216><218><207>a, the very purpose ç
of whose life was to establish dharma, could be the originator of ç
such a heinous plan.
c.<+><+>Since Dro<207>a was killing innocent warriors on the battlefield ç
by using formidable weapons like the Brahm<193>stra, against the ç
norms prescribed for the discharge of such missiles, several sages ç
like Vi·v<193>mitra, Jamadagni, Bharadv<193>ja, Gautama,  Atri,  Vasi<218><219>ha,  Bh<216>gu  and ç
others, arrived there and remonstrated with him, urging him to renounce ç
his weapons and return to the spiritual path which he had given up ç
out of delusion (ibid 190. 32-40). They also reminded him that his ç
time was up and death was imminent.
It was this that ultimately made Dro<207>a retire from the battle ç
and sit in meditation at which time, Dh<216><218><219>adyumna (son ç
of king Drupada) beheaded him.
We can safely conclude from this that this part of the story that ç
maligns Yudhi-<218><219>hira and K<216><218><207>a is a clumsy interpolation ç
which serves no purpose.*
It will not be out of place here to mention another incident from ç
the Mah<193>-bh<193>rata (Kar<207>aparva, chs. 68-71) which brings ç
out brilliantly K<216><218><207>a's character and wisdom. Arjuna, ç
in a moment of impulse, had taken a vow that he would decapitate anyone ç
that would speak disparagingly of his celebrated bow, G<193><207><195><200>va. ç
Once, on the battlefield, Yudhi<218><219>hira was routed by Kar<207>a ç
and barely managed to escape with his life. When Arjuna came to enquire ç
about his welfare, learning that Kar<207>a had not yet been killed ç
by Arjuna, Yudhi<218><219>hira abused him and taunted him to part ç
with his G<193><207><195><200>va. `True' to his vow, Arjuna was about ç
to attack Yudhi<218><219>hira, when K<216><218><207>a intervened. ç
After learning of his vow, K<216><218><207>a brought wisdom to his ç
mind through a wonderful discourse on dharma (righteousness) and satya ç
(truth).
This is the gist of his discourse: Satya is that which is sanctioned ç
by dharma and asatya (untruth) is that which is not. Dharma  is  that  which  brings  about ç
lokahita or good to the world. Hence, the test of satya is whether ç
it will result in good to the world. Looked at from this angle, an ç
asatya which brings about good to the world is satya; and a satya ç
which harms the world is asatya!
@SPACE = 
@SPACE = 
@NO = 4.
@NOK = K<216><218><207>a tricked Jayadratha by creating artificial ç
darkness, hiding the orb of the sun through his disc Sudar·ana, and ç
got him killed by Arjuna.
@SPACE = 
Jayadratha, the king of Sindhu country was the brother-in-law of the ç
Kauravas and was fighting on their side. Once he had abducted Draupad<200>, ç
when the P<193><207><195>avas were living in the forest. He was however ç
caught and punished, and Draupad<200> was rescued from his clutches. ç
Later, he was primarily responsible in preventing the four P<193><207><195>avas ç
(without Arjuna) from coming to the rescue of the young Abhimanyu ç
(son of Subhadr<193> and Arjuna) who had been trapped inside the Cakravy<220>ha ç
or wheel formation of the Kaurava army. This had resulted in the cruel ç
murder of the boy by the so-called warriors and against all norms ç
of the battle. On coming to know of it, Arjuna had vowed that he would ç
kill Jayadratha before sunset, the next day or immolate himself by ç
entering fire. The Kauravas were frightened by this terrible vow and ç
tried their best to hide Jayadratha from Arjuna's view. Though Arjuna ç
fought fiercely and relentlessly till the evening there was no sign ç
of the targeted enemy. At that time K<216><218><207>a, by his yoga ç
power (and not by Sudar·ana discus) created subjective darkness ç
in Jayadratha, who out of joy and relief stuck his head out, but was ç
killed by Arjuna (Dro<207>aparva ch. 146. 64-68). Since Jayadratha ç
was fighting on the side of adharma or unrighteousness and had sinned ç
on two counts, it is butproper that Arjuna killed him and that K<216><218><207>a ç
who was working for the re-establishment of dharma, aided him.
@SPACE = 
@SPACE = 
@NO = 5.
@NOK = K<216><218><207>a incited Arjuna to kill Kar<207>a eventhough ç
the latter was unarmed and was trying to lift up his chariot which ç
had run aground. This was a cowardly act, against all norms of dharma.
@SPACE = 
@SPACE1 = 
The fact is that Kar<207>a was not killed when in a disarmed or ç
helpless condition. He died fighting in the usual way.
This incident is narrated in detail in the Kar<207>aparva (chs. ç
90, 91). The rebuttal given by K<216><218><207>a to Kar<207>a (ch. ç
90. 1-14) was so logical and powerful that Kar<207>a had to swallow ç
it in shame (vide 90. 15).
K<216><218><207>a's argument was simple. When the Kauravas had flouted ç
all norms of dharma in trying to kill or harm the P<193><207><195>avas†reflected ç
in their trying to poison Bh<200>ma, destroy them all through arson, ç
molest their wife Draupad<200> and snatch away their kingdom through ç
the deceitful game of dice†and since Kar<207>a had abetted in their ç
crimes, he had forfeited all claims to dharma!
@SPACE = 
@SPACE = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@NO = 6.
@NOK = During the gad<193>-yuddha (mace-fight) between Bh<200>ma ç
and Duryodhana, K<216><218><207>a reminded Bh<200>ma of his vow to ç
break Duryodhana's thighs by slapping his own thigh, though hitting ç
below the navel was prohibited in such fights.
@SPACE1 = 
@SPACE1 = 
Actually it was Arjuna who did it after hearing K<216><218><207>a's ç
comments on the fight, since Duryodhana was slowly getting the upper ç
hand (vide <185>alyaparva ch. 58.21).
Though it was against the rules of the mace fight, Bh<200>ma had to ç
do it since he had vowed to break Duryodhana's left thigh at the time ç
when the latter had indecently showed to Draupad<200> his bared lap ç
(vide Sabh<193>parva ch. 69.10-14). If this had not been done, K<216><218><207>a ç
averred, then, Duryodhana would have won and would have continued ç
to rule the kingdom persisting in his evil ways, bringing misery upon ç
all. When the choice was between losing dharma on earth or breaking ç
a rule in the duel, the lesserevil was chosen. It is like amputating ç
a limb to save life.
@SPACE = 
@NO = 7.
@NOK = K<216><218><207>a did not prevent the fratricidal fight among ç
the Y<193>davas though he was capable of doing so. On the other hand ç
he too joined in it.
@SPACE1 = 
@SPACE1 = 
The Y<193>davas as a race, had degene-rated beyond redemption due ç
to severe addiction to drinking. All efforts of K<216><218><207>a ç
to reform them had proved futile. Since K<216><218><207>a was for ç
dharma and never for his own people, his role in the destruction ç
of the Y<193>davas who had given up dharma is rather laudable!
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@NO = 8.
@NOK = K<216><218><207>a's end was ignominious since he was assassinated ç
by an ordinary hunter.
@SPACE1 = 
@SPACE1 = 
K<216><218><207>a left his body out of his own free will, in yoga ç
(Vi<218><207>upur<193><207>a 5.37.75). According to the Bh<193>gavata ç
(11.31.6) he ascended to his world with the body (since it was divine).
The story of Jara, the hunter, killing K<216><218><207>a may be an ç
allegorical way of describing that K<216><218><207>a left the body ç
in old age (jar<193> = old age).
Even if the story is taken to be literally true, there is nothing ç
in it that lowers K<216><218><207>a's prestige. The manner of discarding ç
the physical body, after the purpose of life has been achieved, is ç
left to the person concerned and does not affect his greatness in ç
any way. Buddha was poisoned. Jesus was crucified like ordinary criminals. ç
Some of the Sikh Gurus died as martyrs at the hands of barbarians.
Not only the manner of death, even insults heaped upon such great ç
ones while they were living, neither affected them nor their reputation. ç
For instance, Mah<193>v<200>ra was spat upon. Sri Ramakrishna was ç
kicked by a greedy treacherous priest. Since they practised ahims<193> ç
as the highest dharma, they never retaliated. On the other hand, they ç
blessed these sinners. But, today, the world continues to adore them. ç
In fact, these very incidents have made them shine even more brilliantly.
@SB = 8.	Teachings of K<216><218><207>a
K<216><218><207>a was as great a master in the spiritual sciences ç
as he was in the secular ones. His immortal teachings have been left ç
to us through three great works: Bhagavadg<200>t<193>, Anug<200>t<193> ç
and Uddhavag<200>t<193>. The first two are a part of the well-known ç
epic, Mah<193>bh<193>rata and the last, of Bh<193>gavata.
@S10N = BHAGAVADG®T°
The  Bhagavadg<200>t<193>  is  the  most celebrated of these and ç
has been con-sidered as a monumental work in the religio-philosophical ç
literature of India for centuries. It is a part of the Bh<200><218>maparva ç
(Ch. 25 to42). It is in the form of a dialogue between K<216><218><207>a ç
and Arjuna spread over 18 chapters, comprising 700 verses.
Just at the commencement of the Kuruk<218>etra war, after his chariot ç
has been stationed in between the armies of the P<193><207><195>avas ç
and the Kauravas, but right in front of the venerable Bh<200><218>ma ç
and the preceptor Dro<207>a, Arjuna sees them as alsothe others arrayed ç
against him and collapses due to mental depression. He refuses to ç
fight after narrating his reasons to do so. His arguments boil down ç
to this: Killing is a sin. Killing one's own kith and kin, that too ç
for the sake of a paltry kingdom, is worse. It is far better to renounce ç
the world and take to begging to maintain oneself.
K<216><218><207>a's reply to this is direct and clear. Here, the basic ç
question is not whether to fight and kill or to retire from it. The ç
basic question is whether to punish those who, impelled by greed and ç
selfishness, have transgressed all norms of dharma with impunity; ç
or to let them enjoy the fruits of their heinous crimes. This war ç
has been foisted upon the P<193><207><195>avas by the irascible ç
Duryodhana even though they have tried all means at their command ç
to avoid it. Since the society expects the k<218>attriya prince to ç
protect its life, possessions and values, which duty it has put on ç
his shoulders, Arjuna (and the P<193><207><195>avas) have no other ç
go but to fight in defence of these.
@SPACE1 = 
As to the question of killing or dying, K<216><218><207>a states that ç
the essential nature of all beings is <193>tman, the Self. It has ç
no birth, no change, no disease nor death. It is the body worn by ç
the soul like an apparel, that is born or that dies. Hence, there ç
need be no misgivings about the sin of killing or the fear of dying. ç
Even supposing that our birth and death are coterminous with those ç
of the body, there is no cause for sorrow since this is inevitable ç
in life.
K<216><218><207>a avers that no living being can avoid activity or ç
work. Hence one must learn to perform one's duties and discharge one's ç
responsibilities,†K<216><218><207>a calls this as `svadharma'†however ç
unpleasant they may appear to be. The reaction of work on the mind, ç
whether it is pleasant orunpleasant, is due to the emotional attachment ç
one has towards it and its results. If one can learn to do one's work ç
as best as one can, without attachment or aversion, as a matter of ç
duty or to serve the world or to please God, then, it brings about ç
internal peace and equani-mity. This mode of working is known as `ni<218>k<193>makarmayoga'.
@SPACE1 = 
Incidentally and in reply to Arjuna's several questions, K<216><218><207>a ç
deals with many other topics too. He accepts the yaj<210>a- system, ç
the system of sacrifices in duly consecrated Vedic fires, but expands ç
the scope of the word `yaj<210>a' by calling any act of self-sacrifice ç
and public good as a yaj<210>a, no less than its Vedic counterpart. ç
Thus, donating one's wealth to the needy can be called `dravyayaj<210>a' ç
(dravya = wealth or money); imparting knowledge to others becomes ç
`j<210><193>nayaj<210>a' and so on.
K<216><218><207>a has christened as `·re<218><219>ha' anyone who works ç
for the good of the world and advises him to be extremely careful ç
in his personal and public life so as to set a model to others.
K<216><218><207>a also deals with the several paths to perfection ç
like J<210><193>nayoga (the yoga of knowledge), Bhaktiyoga (the yogaof ç
devotion to God) and Dhy<193>nayoga (the yoga of meditation) and equates ç
Karmayoga (the yoga of selfless action) with them.
Another teaching of tremendous hope given by K<216><218><207>a is ç
the assurance that he, the Lord, will come down as an `avat<193>ra' ç
or incarnate himself here, whenever dharma declines and adharma gains ç
in momentum. There are no conditions with regard to time and place ç
in this act of grace. And, this doctrine of avat<193>ra has been enunciated ç
for the very first time in the Hindu scriptures, in the Bhagavadg<200>t<193> ç
(4.6-8).
K<216><218><207>a reveals his divinity by vouchsafing to Arjuna his ç
Cosmic Form (vi·var<220>pa) so as to strengthen his faith. Towards ç
the end K<216><218><207>a advises Arjuna tosurrender himself to Him ç
with the assurance of freeing him from all sins.
Arjuna shakes off his delusion and rouses himself to action to defend ç
dharma.
@S10N = ANUG®T°
The Anug<200>t<193>, the second of the three G<200>t<193>s attributed ç
to K<216><218><207>a, is also a part of the epic Mah<193>bh<193>rata ç
(A·vamedhaparva, chs. 16 to 51). It comprises 1056 verses spread ç
over 36 chapters.
Having completed his task of restoring their kingdom to the P<193><207><195>avas ç
so that they can rule according to dharma, K<216><218><207>a has decided ç
to return to Dv<193>rak<193>. Wishing to take advantage of his spiritual ç
wisdom before his departure, Arjuna requests him to teach him once ç
again the great spiritual knowledge which he had taught at the start ç
of the Kuruk<218>etra war. Chiding Arjuna for having forgotten such ç
a profound teaching and pleading his inability to bring back to memory ç
all that teaching once again, K<216><218><207>a proceeds to teach ç
him through `itih<193>sa' or ancient stories.
Avoiding  these  rather  involved stories, the gist of the teachings ç
may be given here. The first topic dealt with is that of the j<200>va, ç
the individual soul, how he gets out of the body and how he gets into ç
another, after death. Both these depend upon the karma (action) he ç
has done. Good karma takes him to svarga or heaven, bad karma to naraka ç
or hell. He then returns to this human birth to continue his journey. ç
If he takes to the path of dharma, he is gradually led towards mok<218>a ç
or liberation.
@SPACE1 = 
The next topic is how a human being can attain mok<218>a or liberation. ç
Anyone who has cultivated virtues like equanimity, intense desire ç
for mok<218>a, renunciation and self-control, becomes fit for mok<218>a. ç
By adopting the path of yoga in which self-control, austerity, contemplation ç
on the <193>tman or the Self within, desirelessness and peace are ç
important s<193>dhanas, he will be able to attain the Abode of Brahman.
The third topic, expounded in the form of a dialogue between a br<193>hma<207>a ç
and hiswife†hence called Br<193>hma<207>ag<200>t<193> †comprises ç
miscellaneous subjects like the °tman-Brahman principle which is beyond ç
the ken of the senses, meditating on the functioning of the senses ç
and the mind as a yaj<210>a or sacrifice, importance of the pa<210>capr<193><207>as ç
or the five vital airs, the greatness of Janaka, the king of Mithil<193> ç
who had conquered mamak<193>ra or the sense of possessions and the ç
state of a j<200>vanmukta, one liberated even while living in the ç
body.
Then, Arjuna questions K<216><218><207>a about the path that leads ç
to mok<218>a or liberation. K<216><218><207>a in his reply states ç
that the Param<193>tman, or the Supreme Self, residing in the hearts ç
of all, is to be realized through tapas or austerity, for which sa<221>ny<193>sa ç
(life of renunciation) is the best means. Trying to see one Self in ç
all and giving up all that obstructs this, is a part of this discipline.
This is followed by a description of the three gu<207>as†sattva, rajas ç
and tamas †and their products like aha<209>k<193>ra (egoity) and the ç
five elements like earth and water.
Then comes a description of the four <193>·ramas or stages of life ç
(brahmacarya, g<193>rhasthya, v<193>naprastha and sa<221>ny<193>sa), ç
the allegory of the `Brahmav<216>k<218>a' (actually the human body, ç
compared to a tree) and how it can be cut by the sword of j<210><193>na ç
(spiritual wisdom), some discussions about dharma or religious duties ç
and activities, and the efficacy of tapas or austerity in the form ç
of self-control, which can destroy sins and give spiritual enlightenment. ç
The Anug<200>t<193> ends with this.
@SPACE = 
@S10N = UDDHAVAG®T°
@SPACE = 
Unlike these two G<200>t<193>s, the Uddhava-g<200>t<193> is not ç
a part of the epic Mah<193>bh<193>rata, but of the Bh<193>gavata. ç
It comprises 23 chapters (chs. 7 to 29 of the eleventh skandha or ç
book) and has 1030 verses.
Having   intuited   the   imminent destruction of his race of the ç
Yadus by mutual fighting, K<216><218><207>a decides to return to his ç
divine Abode. Realizing this, Uddhava, an intimate companion and devotee, ç
approaches him for guidance. K<216><218><207>a then teaches him spiritual ç
wisdom and directs him to go to the Badarik<193>·rama in the Him<193>layas.
K<216><218><207>a commences his teaching with an ancient story. King ç
Yadu, the son of Yay<193>ti, once saw an Avadh<220>ta, a perfect being ç
(who had shaken off all bonds born out of ignorance), and asked him ç
how he had attained to that state of freedom and bliss. The Avadh<220>ta ç
replied that he had learnt his lessons from 24 teachers: patience ç
from earth; non-attachment from wind which is not tainted by the smell ç
it carries; purification from water; power to destroy evil, from fire; ç
living for the good of  others  from  the  sun;  indifference towards ç
the world from a python; dangers of temptation from a moth; the desirability ç
of collecting good teachings from all available sources, from a bee; ç
the need to conquer the instinct of sex and taste from an elephant ç
and a fish; the need to conquer desires, from a courtesan; the necessity ç
of living alone, to progress in the inner life from a girl and so ç
on.
Then K<216><218><207>a proceeds to tell Uddhava that karma or action ç
binds a person to transmigratory existence. Hence one should renounce ç
evil actions and actions motivated by desires; but perform ordained ç
or obligatory duties without the desire for fruits. He clarifies that ç
sa<221>s<193>ra or transmigratory existence is due to attachment to ç
the body and, the <193>tman or Self is never subject to it.
@SPACE1 = 
He then describes the characteristics of the bound and the free souls. ç
Bondage comes from egoism and attachment to the body. Freedom results ç
from detachment.
At the specific request of Uddhava, K<216><218><207>a delineates the ç
signs of s<193>dhus or holy beings and of devotion to God. Compassion,  truthfulness,  self-control, ç
devotion to duties, equanimity under all conditions, fortitude†these ç
are some of the traits found in s<193>dhus. Devotion to God (or K<216><218><207>a) ç
manifests itself as worship of images, interest in listening to the ç
stories of the Lord, cultivation of certain attitudes of love, going ç
on pilgrimage, observing religious festivities and so on. A true devotee ç
is deeply interested in serving the Lord through rituals, and is devoid ç
of pride and self-praise. Satsa<209>ga or cultivating the company ç
of devotees and holy beings is the best means of attaining God.
Continuing, K<216><218><207>a describes the three gu<207>as or qualities ç
of sattva, rajas and tamas and stresses the need to overcome the last ç
two but augment the first. This leads to devotion and knowledge.
Then comes a description of dhy<193>na or meditation on God. The mode ç
of sitting, method of pr<193><207><193>y<193>ma or breath-control ç
and contemplation on the beautiful form of K<216><218><207>a-Vi<218><207>u ç
are dealt with in detail. The a<218><219>asiddhis or the eight psychic ç
powers that result by yogic practices are also touched upon; but the ç
yogi is advised against taking interest in them since they are obstacles ç
to spiritual enlightenment.
@SPACE1 = 
Uddhava  now  puts  a question: `O Lord! What are the various ways ç
in which the sages contemplate you and attain the siddhis or powers?' ç
K<216><218><207>a in reply, states how he is the best in all things, ç
their very essence. For instance, he is the Self, friend and inner ç
controller of all beings. He is Vi<218><207>u among the °dityas and ç
N<200>lalohita among the Rudras. He is Bh<216>gu among the great sages, ç
Prahl<193>da among the daityas or demons, V<193>suki and Ananta among ç
the serpents, lion among the animals, Ga<209>g<193> among the rivers, ç
Him<193>layas among the mountains, Uddhava among the devotees and ç
so on. In fact, wherever there is excellence, he is that.*
Uddhava is now interested to know those dharmas or duties that are ç
conducive to the development of devotion. In reply K<216><218><207>a ç
gives a fairly detailed account of the  well-known  var<207><193>·rama-dharmas, ç
duties of the four castes and stages of life.
K<216><218><207>a then proceeds to declare that all duality that appears ç
here, is only m<193>y<193>, illusion and hence unreal. He, the basis ç
of all, alone is Real. Uddhava then requests K<216><218><207>a to ç
teach him j<210><193>na and bhakti by which one can attain mok<218>a ç
or liberation. In reply K<216><218><207>a expounds them. J<210><193>na ç
or knowledge is that by which one knows that Param<193>tman, the Supreme ç
Self, is in everything; He is everything. Since karmas or ritualistic ç
actions give transient  fruits,  one  should  not  get attached to ç
them. Bhakti or devotion arises as a result of listening to and reciting ç
the stories of the Lord, of worshipping the Lord and honouring His ç
devotees. Renunci-ation of worldly desires and worldly objects of ç
pleasure strengthens bhakti.
K<216><218><207>a, at the request of Uddhava, further expounds the ç
various spiritual disciplines that are conducive to j<210><193>na ç
and bhakti. They are: yama and niyama comprising the disciplines like ç
ahi<221>s<193> (non-injury), satya (truth), japa (repetition of the ç
divine name), tapas (austerities), p<220>j<193> (worship), paropak<193>ra ç
(helping the needy), <193>c<193>ryasev<193> (serving the preceptor) ç
and so on; ·ama (concentrating the mind on the Lord); dama (self control); ç
titik<218><193> (forbearance);  dh<216>ti  (controlling  the instincts ç
of taste and sex); sa<221>ny<193>sa (renunciation of the fruits of ç
action) and so on.<F20W1><185><F255D>
Continuing further, K<216><218><207>a describes the three well-known ç
yogas: J<210><193>nayoga, Karmayoga and Bhaktiyoga. An intense spirit ç
of renunciation is a must for the first. Renouncing evil actions and ç
the fruits of the good ones is a precondition for the second. Interest ç
and faith in listening to the stories of the Lord is a quality needed ç
for the third.
This is then followed by a discussion about the various philosophical ç
truths and principles given in other works like prak<216>ti (nature) ç
and puru<218>a (soul). The mode of rebirth of an ignorant being, due ç
to that very ignorance, is also stated.
Uddhava nowraisesapertinent question: How should a devotee react ç
to the evil behaviour of evil persons? K<216><218><207>a, in reply, ç
narrates the story of a bhik<218>u (mendicant) who put up bravely ç
with the harassment of unsympathetic and evil persons. (This section ç
is known as the Bhik<218>ug<200>t<193>.) There was a rich man in ç
the country of Avant<200>. He was a miser and treated even his own ç
wife, children and other relatives with scant regard. The gods were ç
offended with him. So, he lost everything, being cheated by his own ç
people. His troubles gave rise to wisdom and a genuine spirit of renunciation. ç
He then became an itinerant mendicant. Whenever he moved out, begging ç
for alms, evil people who had known his earlier life, started harassing ç
him in many ways including violent physical assaults. However, accepting ç
everything as the fruit of his evil karmas, he never retaliated nor ç
reacted in any way, practising extreme forbearance, without any rancour ç
in his heart. He then sang unto his own mind, a poem containing nuggets ç
of great spiritual wisdom. The gist of that poem†the Bhik<218>ug<200>t<193>†is ç
that it is one's own mind that is responsible for weal or woe, and ç
that one who conquers his own mind is the Master of even gods! And, ç
this can be achieved by devotion to God.
Some discussions about getting rid of moha or delusion by S<193><209>khyayoga ç
or the path of knowledge, as also a description of the three gu<207>as ç
and their products follow next.
The obstacles created by lust in the path of yoga are described by ç
narrating the story of Pur<220>ravas. The need for and the tremendous ç
advantages of cultivating satsa<209>ga or company of the holy ones ç
is the topic that comes next.
@SPACE1 = 
This is followed by a rather detailed description of p<220>j<193> ç
or ritualistic worship of God. A brief summary of the items involved ç
in the worship can be given as follows: bath and wearing clean clothes ç
suitable for p<220>j<193>; keeping the image or symbol of worship; ç
preliminary processes of ritual purification (called ny<193>sa); <193>v<193>hana ç
or inviting the Lord into the image or symbol; offering sandal paste, ç
flowers, incense, lamp and items of food. On special occasions homa ç
(offering oblations into a duly consecrated fire) may also be done. ç
The whole worship can be concluded with recitation of hymns and salutation. ç
Faith and devotion are most important in such worship.
After stressing once again that the external world is only an appearance, ç
that the <193>tman or Self is the spirit beyond thebody-mind complex ç
and giving some methods of yoga that help in overcoming the obstacles ç
to the inner life, K<216><218><207>a concludes his teaching with a ç
description of a pa<207><195>ita, a man of spiritual wisdom who has ç
attained equanimity. Uddhava then departs for the Badarik<193>·rama ç
in the Him<193>layas with a heavy heart, due to the pain of separation ç
from K<216><218><207>a.
@SPACE = 
@SB = 9.	K<216><218><207>a's Philosophy of Life
@SPACE = 
He lives long that lives well! He alone lives, who lives for others! ç
And, K<216><218><207>a did all these: He lived long; he lived for ç
others and so, he lived well!
The philosophy of life that K<216><218><207>a has taught us can best ç
be learnt from his own life. The basic note of the music of his life ç
was dharma. And, to him, anything that brought about the good of the ç
individual and the society, the two being in consonance with each ç
other, was dharma. Whenever there was a conflict between these two, ç
it was the social good that he preferred.
There are three recognized sources of dharma: the ·<193>stras or the ç
Holy Books; the samprad<193>ya or tradition set up by a long line ç
of <216><218>is or sages; and, one's own purified mind. K<216><218><207>a ç
followed them all in his personal life. He performed all the rituals ç
prescribed for his station in life, did his duties, honoured the elders, ç
the br<193>hma<207>as and the sages and took good care of all his ç
dependents.
Dharma is protected and nourished when institutions and the people ç
running the institutions follow dharma unhindered. K<216><218><207>a ç
was ever ready to protect them both. If, in the process, confrontation ç
with the wicked was necessary, he was the first to rise against them ç
in defence of dharma.
The Bh<193>gavata (1.3.28) has called him as Bhagav<193>n, the Lord ç
Himself (k<216><218><207>astu bhagav<193>n svayam). He is the Puru<218>ottama, ç
the best of men, of the Bhagavadg<200>t<193> (15.18). Hence, there ç
was no need for him to be engaged in action, either to get or get ç
rid of anything in life. And yet, he worked relentlessly; but, only ç
for the sake of others, for the good of the world. He never had any ç
axe to grind. He was unselfish to the core.
Furthermore, his work, his actions, were always perfect. He was ç
as skilled in the art of love and compassion as in war; as dexterous ç
in speaking honey and milk to the suffering ones, as in chiding or ç
deriding hotheaded renegades. He was easily controlled by pure love, ç
but adam-antine to those that hated him and fought with him. He was ç
ever forgiving to the meek and the humble, but an inveterate enemy ç
of the cheats and the hypocrites.
@SPACE1 = 
Fearlessness personified, he was ever ready to face any problem in ç
life. But he always tried his best to defuse nasty situations before ç
they grew into knotty problems.
Above  all,  he  was  completely detached, the very picture of supreme ç
unconcern.
Finally, he was Yoge·vara, the master of yoga and Yog<200>·vara, the ç
master of yogis too. He never forgot to teach the highest spiritual ç
verities to those that sought them.
This, then, is what he has taught us to emulate: Be ever active for ç
the sake of dharma, for the good of others; but never be selfish. ç
Do your work as best as you can. Follow dharma and have firm faith ç
that it will protect you. Do not run away from the problems of life; ç
but face them boldly. Pray to God and He will give you the strength ç
needed to face them or transcend them. Never forget that the final ç
goal of life is liberation. Strive your best to attain it through ç
j<210><193>na and bhakti, and be free!
@SPACE = 
@SB = 10.	R<193>dh<193>
@SPACE = 
In the popular religious lore of the Hindus R<193>dh<193> has been ç
very intimately associated with K<216><218><207>a. Hence it is but ç
meet that a few lines be devoted to her here.
At the outset, it must be mentioned that R<193>dh<193> is nowhere ç
to be seen in the four well-known sources of the K<216><218><207>a ç
story: Mah<193>bh<193>rata, Hariva<221>·a, Vi<218><207>upur<193><207>a ç
and Bh<193>gavata. There is a reference in the Bh<193>gavata (10.30.25 ç
ff.) to a fortunate gop<200> who had gone alone with K<216><218><207>a ç
just before the R<193>sakr<200><195><193>. The words used here†anay<193>r<193>dhita<199> ç
(=<|>being propitiated by her)†might have provided the seeds forthe ç
later concept of R<193>dh<193>, as the gop<200> dearest to K<216><218><207>a.
The story of R<193>dh<193> in detail appears in the K<216><218><207>ajanma-kha<207><195>a ç
of the Brahma- vaivartapur<193><207>a,  a  late  work.  She  is ç
described here as having emerged out of K<216><218><207>a and as his ç
<185>akti or power. It is, perhaps, the poet Jayadeva (<MS>A. D.<D> ç
1200) that has immortalized her through his well-known lyric, G<200>tagovinda. ç
Bengal Vai<218><207>avism nourished by Caitanya (<MS>A. D.<D> 1485-1533) ç
and others, has given her a unique place in its K<216><218><207>a ç
theology and metaphysics.
It is plausible that the `Prak<216>ti-pradh<193>na' (Mother Nature) ç
of the earlier S<193><209>khya system of philosophy has gradually ç
got metamorphosed into the R<193>dh<193> personality of the later ç
Vai<218><207>ava schools of theology.
@SB = 11.	K<216><218><207>a Festivals
Generally, every religion has three aspects: philosophy, mythology ç
and rituals. Philosophy tries to deal with the ultimate truths and ç
values. Mythology tries to present them to the masses in a languagethat ç
they can understand. Rituals, by affording  opportunities to  practise ç
religion, fulfil an emotional need.
Festivals in Hinduism are legion. A few of the more important ones, ç
directly related to the K<216><218><207>a legends, will be outlined ç
here.
The most important of these is <P9B>K<216><218><207>a- janm<193><218><219>am<200><P255D>, ç
the birthday of K<216><218><207>a. He was born on the a<218><219>am<200> ç
or the eighth day of the k<216><218><207>apak<218>a or dark fortnight ç
of the month of <185>r<193>va<207>a (August-September) at midnight. ç
The nak<218>atra or constellation was Rohi<207><200>. Generally this ç
comes the next day. Hence that day is called <P9B>Jayant<200><P255D>. ç
Both the days are important though the actual worship has to be done ç
at midnight on the a<218><219>am<200> day.
Fasting for the whole day and night, worship of K<216><218><207>a ç
in image or picture, keeping vigil throughout the night, listening ç
to the stories and exploits of K<216><218><207>a, recitation of the ç
Bh<193>gavata, singing of hymns and songs, and japa (repetition ç
of the divine name) of the famous mantra Om namo bhagavate V<193>sudev<193>ya ç
are the essential parts of this festival.
In Mathur<193> and V<216>nd<193>van, the two towns associated with ç
K<216><218><207>a's birth and childhood, there are a number of temples ç
dedicated to him. Janm<193><218><219>am<200> is celebrated there on ç
a grand scale.
It may be of interest to state here that in Maharashtra, it is the ç
practice, particularly of boys and the common folk, to hang up pots ç
full of curds and buttermilk on the day after the birth of K<216><218><207>a ç
is celebrated, to play underneath the pots and get drenched by the ç
curds and buttermilk running out from the holes made by the boys, ç
in typical K<216><218><207>a fashion!
@SPACE1 = 
The birthday of R<193>dh<193> or R<193>dhik<193>, the gop<200> dearest ç
to K<216><218><207>a, is celebrated as <P9B>R<193>dh<193><218><219>am<200><P255D>, ç
on Bh<193>drapada ·ukla a<218><219>am<200> (eighth day of the bright ç
fortnight in the month of Bh<193>drapada, September). During this ç
festival, worship is offered to R<193>dh<193> and K<216><218><207>a ç
together. One should subsist on fruits only on this day. Apart from ç
hearing and singing devotional music, one should also listen to certain ç
episodes from the Brahmavaivartapur<193><207>a related to R<193>dh<193> ç
and K<216><218><207>a.
<P9B>Govardhanap<220>j<193><P255D> (worship of the hill Govardhana ç
of Mathur<193>) which includes <P9B>Annak<220><219>a<P255D> (`mountain ç
or heap of food') is another festival, more commonly observed in North ç
India, related to K<216><218><207>a. It is observed on the first day ç
of the bright half of the month of K<193>rttika (K<193>rttika ·ukla ç
pratipad†generally in November), a day after the famous D<200>p<193>val<200> ç
(Diwali) festival. Worship of the Govardhana hill and K<216><218><207>a ç
as Gop<193>la (cowherd boy), decorating and worshipping the cows, ç
calves and bulls, keeping vigil in the night as also contemplating ç
on the K<216><218><207>a story are its salient features. Of course, ç
the Govardhana hill can be worshipped only in Mathur<193> (Uttar Pradesh). ç
Elsewhere, a replica is made, generally in cowdung, for purposes of ç
worship. A big heap of food, comprising various items of eatables, ç
should also be prepared resembling a hill, and worshipped. This is ç
the <P9B>Annak<220><219>a<P255D> festival.
When the festival of revelry, the Holi or Holik<193>, is celebrated ç
all over the country, Bengal celebrates it as <P9B>Dol<193>y<193>tr<193> ç
or Dolotsava<P255D> (festival of the swing). It is observed for three ç
or five days from the 14th day of the dark half of the month Ph<193>lguna ç
(March) (ph<193>lguna k<216><218><207>a caturda·<200><|>). Worship ç
of Agni or the fire-god, worship of K<216><218><207>a in an image ç
stationed in a dol<193> or swing and swinging it for 7times on the ç
first day and 21 times on the last day are the chief elements of this ç
festival.
@SPACE1 = 
The day on which K<216><218><207>a taught the Bhagavadg<200>t<193>  to  Arjuna,  called  <P9B>G<200>t<193>- ç
jayant<200><P255D>, falls on the eleventh day of the bright  half  of  the  month  M<193>rga·ira ç
(December) (M<193>rga·ira ·ukla ek<193>da·<200>). It is celebrated ç
with fasting, worship of K<216><218><207>a as G<200>t<193>c<193>rya ç
(preceptor of the G<200>t<193>), chanting of the G<200>t<193> ç
and listening to discourses on the same.
@SB = 12.	Conclusion
For aeons if K<216><218><207>a has been an agonizing enigma to some, ç
he has put millions into ecstasies. There is nothing to wonder at ç
in this. His very name `K<216><218><207>a-V<193>sudeva' solves this ç
riddle. Etymolgoically speaking, `K<216><218><207>a' is one who is ç
ever blissful and ever attracts others to himself (vide Vi<218><207>usahasran<193>ma ç
57). `V<193>sudeva' is the Divinity that pervades everything in the ç
universe and is also immanent in it (ibid 332).
@EMERGENCY = So, K<216><218><207>a as a human being, extremely handsome ç
and intensely affectionate, has been driving the votaries into rapturous ç
moods. But as God or God's incarnation on earth, his ways have been ç
inscrutable.
The word `K<216><218><207>a' also means `dark', `mysterious'. He was ç
dark in colour and his ways were mysterious!
The ocean appears to be dark from a distance. But when we approach ç
it and take its water into our hands, the water is pure and colourless. ç
Similarly, K<216><218><207>a is a problem and a riddle only from a ç
distance. When approached with love and faith, the dark mist of misunderstanding ç
dissolves into a crystal clear experience of divine bliss and eternal ç
presence.
K<216><218><207>a is true to his word: `In whichever way people approach ç
me, in the same way do I respond.' (G<200>t<193> 4.11.) If we approach ç
him as `problem-K<216><218><207>a' he will create more problems for ç
us! If on the other hand, we approach him as the Divine in human form, ç
ever gracious and merciful, he will solve all our problems. The innumerable ç
mystics and devotees of K<216><218><207>a over the centuries, are ç
the standing proof of this.
