@NT = K<216><218><207>a-dvaip<193>yana
See <MS>VEDAVY°SA.<D>
@NT = K<216><218><207>a-janm<193><218><219>am<200>
See under <MS>K<184><186>ØA.<D>
@NT = k<216><218><207><193>jina
@N1 = (`black antelope skin') 
See <MS>AJINA.
@NT = K<216><218><207>ami·ra
One of the novel methods adopted by the philosophers of the schools ç
of Ved<193>nta was to present their tenets in and through a story ç
or a drama. K<216><218><207>ami·ra, who was probably a recluse living ç
in the 11th century <MS>A.<|>D.<D> has done a good job of it in his ç
famous work Prabodha Candrodaya. It is said that he wrote it to ç
convince one of his disciples who had no faith in Ved<193>nta, about ç
the truth and greatness of Advaita Ved<193>nta.
He was closely associated with a king †K<200>rtivarma by name†in whose ç
presence the drama was first enacted.
The drama Prabodha Candrodaya has six acts and reflects the whole ç
life of a man with a profound philosophical allegory. It is conceived ç
as a struggle between the two powerful sons†Moha (delusion) and Viveka ç
(discrimination or wisdom)†of the king Manas (mind), born respectively ç
of his two queens Prav<216>tti (worldly life) and Niv<216>tti (Monastic ç
life). The drama gives us an ingenious picture of the spiritual struggle ç
of the human mind in the form of a vivid conflict, wherein the comic, ç
the erotic and the devotional interests play a prominent part. In ç
the final battle between Viveka and Moha, the former wins due to the ç
rise of the moon (candrodaya) of knowledge (prabodha).
Though Advaita Ved<193>nta is eulogised, Vi<218><207>ubhakti or devotion ç
to Lord Vi<218><207>u is also advocated as necessary for mok<218>a ç
or liberation.
@NT = K<216><218><207>a Yajurveda
See <MS>YAJURVEDA.<D>
@NT = K<216>tayuga
The pur<193><207>as, while describing creation and allied topics, ç
give us some idea of the concept of time in the ancient days. `Yuga' ç
is one such concept.
The yugas are four in number. They are: K<216>tayuga, Tret<193>yuga, ç
Dv<193>parayuga and Kaliyuga.
The K<216>tayuga†also called `Satya-yuga'†is spread over 4800 years ç
of the gods or 17,28,000 human years.
It is supposed to begin on that day when Ravi (the sun), Candra (the ç
moon) and B<216>haspati or Guru (the jupiter) meet in the nak<218>atra ç
or asterism of Pu<218>ya (gamma, delta, theta cancri).
In this yuga, dharma (conceived of as a bull) is firmly established ç
on all the four feet. People are well-fed, well-clothed, ever satisfied ç
and happy. They are always rooted in dharma and never swerve from ç
it. Members of the four var<207>as are ever devoted to their vocations. ç
There is perfect harmony in the society.
See also <MS>DV°PARAYUGA, KALIYUGA, TRET°YUGA<D> and <MS>YUGAS.<D>
@NT = K<216>ttik<193>
It is a nak<218>atra or asterism, third in the series of 27 nak<218>atras. ç
It is actually a group of six stars known as the pleiades. Persons ç
born under this nak<218>atra are considered as demoniacal in nature.
These six stars are described in the pur<193><207>as as six goddesses ç
who simultaneously suckled the baby Subrahma<207>ya who assumed six ç
heads and hence came to be known as <186>a<207>mukha or the Six faced ç
one.
As per the Taittir<200>ya Sa<221>hit<193> and the Atharvaveda, ç
this nak<218>atra was the first in the series. Some scholars have ç
therefore attempted to fix the date of the Vedic Sa<221>hit<193>s ç
on the assumption that the vernal equinox occurred at that time when ç
the sun was in K<216>ttik<193>.
See also <MS>NAK<186>ATRAS.<D>
@NT = K<216>tyakalpataru
@N1 = (`wish-yielding tree of rituals')
Rituals and sacraments of modern Hindu society depend to a great extent ç
on the pur<193><207>as and the dharma·<193>stras including the nibandhas ç
or digests. The K<216>tyakalpataru†more popularly known as Kalpataru†of ç
Lak<218>m<200>dhara (12th century <MS>A.<|>D.<D>) is one such nibandha ç
which is both voluminous and also considered as an authority especially ç
in Mithil<193>, Bengal, Northern and Western India.
Lak<218>m<200>dhara was the son of Bha<219><219>a H<216>dayadhara ç
and was the minister for peace and war (called `sandhivigrahika') ç
of the king Govindacandra of Kanauj who ruled from <MS>A.<|>D.<D> 1114 ç
to <MS>A.<|>D.<D> 1154.
The work comprises fourteen k<193><207><195>as dealing with a variety ç
of subjects as follows:
@SPACE1 = 
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(.4608,1.1667,E1), ç
ABOVE(.1250), VGUTTER(.0555), KEEP(OFF)
@Z_TBL_BODY = TC1, TC1, TC1
K<193><207><195>a, Name, Contents
@Z_TBL_BODY = TLJ, TLJ, TLJ
1., Brahmac<193>rik<193><207><195>a, Duties of a brahma-c<193>rin ç
or a Vedic student.
<+>2., G<216>hasthak<193><207><195>a, Duties of a g<216>hastha or ç
a householder.
<+>3., °hnikak<193><207><195>a, Daily duties like Sandhy<193> and ç
pa<210>ca-mah<193>yaj<210>as.
<+>4., <185>r<193>ddhak<193><207><195>a, Obsequial rites.
<+>5., D<193>nak<193><207><195>a, Giving of gifts.
<+>6., Vratak<193><207><195>a, Vratas or religious rites based mostly ç
on the pur<193><207>as.
<+>7., P<220>j<193>k<193><207><195>a, Worship,, consecra-<R>ç
tion of temples and images.
<+>8., T<200>rthavivecana-<R>ç
  k<193><207><195>a, Pilgrimage to holy places like K<193>·<200>,, ç
Pray<193>ga,, Gay<193> and so on.
<+>9., Pr<193>ya·cittak<193><207><195>a, Expiatory rites.
10., <185>uddhik<193><207><195>a, A·auca (ceremonial impurity) and ç
ways of remedying it.
11., R<193>jadharmak<193><207><195>a, Coronation of the king,, on ç
ministers,, forts and palaces,, administration of the State and so ç
on.
12., Vyavah<193>rak<193><207><195>a, Law and administra-tion of ç
justice.
13., <185><193>ntikak<193><207><195>a, <185><193>ntis or propitiatory ç
rites for averting a deity's wrath or evil effects of a planet.
14., Mok<218>ak<193><207><195>a, Liberation as per Advaita Ved<193>nta.
@Z_TBL_END = 
Lak<218>m<200>dhara might have composed his work during the period ç
<MS>A.<|>D.<D> 1125-1145.
@NT = K<216>tyaratn<193>kara
@N1 = (`ocean of religious<R>ç
observances')
The K<216>tyaratn<193>kara is one of the seven sections of the voluminous ç
nibandha or digest, the Sm<216>tiratn<193>kara or simply, the Ratn<193>kara ç
by Ca<207><195>e·vara. (See <MS>CAØ£E<185>VARA<D>.)<MS>
It has 22 tara<209>gas (sub-sections) dealing with the nature of dharma, ç
various vratas and other religious observances including rites to ç
be performed on eclipse days.
The Ratn<193>kara has influenced greatly, the writers of dharma·<193>stras ç
and nibandhas from Mithil<193> (North Bihar) and Bengal.
@NT = kru<218><219>a
Indian music, especially the sapta-svara system (the seven fundamental ç
notes), gradually evolved from the seven notes of s<193>mag<193>na ç
used in chanting the hymns of the S<193>maveda. Kru<218><219>a is ç
the last of the notes as arranged there. Theseven notes of S<193>mag<193>na ç
and their equivalents in the saptasvara system are given below:
@Z_TBL_BEG = COLUMNS(2), DIMENSION(IN), COLWIDTHS(1.1667,E1), ABOVE(.0555), ç
BELOW(.0555), KEEP(OFF)
@Z_TBL_BODY = TC1, TC1
of S<193>maveda, of Indian Music
@Z_TBL_BODY = IN2, IN2
prathama<R>ç
dvit<200>ya<R>ç
t<216>t<200>ya<R>ç
caturtha<R>ç
mandra<R>ç
atisv<193>rya<R>ç
kru<218><219>a, ga (g<193>ndh<193>ra)<R>ç
ri (<216><218>abha)<R>ç
sa (<218>a<195>ja)<R>ç
ni (ni<218><193>da)<R>ç
dha (daivata)<R>ç
pa (pa<210>cama)<R>ç
ma (madhyama)
@Z_TBL_END = 
Thus, kru<218><219>a corresponds to ma or madhyama of Indian music.
@NT = k<218>a<207>a
@N1 = (`moment')
See <MS>K°LA.<D>
@NT = k<218>ara
@N1 = (`destructible')
Literally, the word k<218>ara stands foranything that gets destroyed, ç
that is ephemeral.
However, the Bhagavadg<200>t<193> (15.16) uses it in a technical ç
sense. According to it there are two kinds of beings†the k<218>arapuru<218>as ç
and the ak<218>arapuru<218>as.
All beings associated with prak<216>ti (i.e., embodied beings undergoing ç
transmigration)†starting with the fourfaced Brahm<193> right up to ç
a blade of grass†are `k<218>ara' whereas the muktapuru<218>as or liberated ç
souls, are `ak<218>ara' since they are not associated with the everchanging ç
prak<216>ti.
@NT = k<218>arapuru<218>a
@N1 = (`the being who changes')
In the Bhagavadg<200>t<193> (15.16) Lord <185>r<200> K<216><218><207>a ç
describes two kinds of puru<218>as or beings: the k<218>ara and the ç
ak<218>ara.
All the living beings and objects associated with prak<216>ti or nature† ç
whether it is Brahm<193> the creator or the blade of grass†are `k<218>ara' ç
puru<218>as since they are subject to change. The `ak<218>ara' puru<218>as ç
are the liberated souls, ever established in their essential changeless ç
nature.
Sometimes `k<218>arapuru<218>a' is interpreted as the products of ç
prak<216>ti (mother nature) and `ak<218>arapuru<218>a' as the m<193>y<193>-power ç
of God.
@NT = k<218>attriya
@N1 = (`one who protects others from injuries')
See <MS>VARØA<D> and <MS>VARØ°<185>RAMA DHARMA.<D>
@NT = K<218>ema<209>kar<200>
@N1 = (`one who brings about the welfare [of beings]')
Worship of God as the Divine Mother is a very old tradition in Hinduism. ç
Most of the Hindu goddesses are facets of P<193>rvat<200>, the spouse ç
of <185>iva.
One of the nine aspects of Durg<193> (Navadurg<193>s) is called `K<218>ema<209>kar<200>'. ç
She is shown with four arms of which three are carrying tri·<220>la ç
(trident), kamala (lotus) and p<193>nap<193>tra (drinking bowl). The ç
fourth is exhibiting the varadamudr<193>.
@NT = k<218>etra
@N1 = (`field')
Though this word is used in a general sense for an agricultural field, ç
in a more technical sense, it stands for the body since it is through ç
this body that the fruits of karma†good or bad†are reaped (vide Bhagavadg<200>t<193> ç
13.1). Later, the same work includes the five elements, egoism, intellect, ç
the ten sense-organs and their objects also under the purview of this ç
term (ibid 13.5 and 6).
Another meaning of the word is `a place of pilgrimage'.
In Hindu astrology, the twelve signs of the zodiac are considered ç
as the k<218>etras of the seven planets. For instance, Ravi (Sun) ç
has Si<221>ha (Leo) as his k<218>etra. This helps in estimating the ç
effects of these planets.
@NT = k<218>etraj<210>a
@N1 = (`one who knows the k<218>etra')
If the human body is the k<218>etra or the field (since the human ç
being reaps the results of his karmas through it) then the k<218>etraj<210>a ç
is the one who resides in it and `knows' it, experiences it and controls ç
it. This is, of course, the j<200>v<193>tman (the individual soul).
However, the Lord <185>r<200>k<216><218><207>a says in the Bhagavadg<200>t<193> ç
(13.2) that he too is k<218>etraj<210>a in all the bodies. This ç
statement can be interpreted from two different standpoints.  From  the  standpoint  of ç
advaita, all the j<200>v<193>tmans or the j<200>vas are only appearances ç
or reflections of the Param<193>tman. Hence all the j<200>vas in all ç
the k<218>etras or bodies are the Lord Himself.
The bhakti schools however, which advocate dvaita or dualism, declare ç
that behind or inside all the j<200>vas in all the k<218>etras, is ç
the one Supreme Lord, ®·vara as the Antary<193>min, the inner Self ç
and controller. The Antary<193>mi Br<193>hma<207>a of the M<193>dhyandina ç
recension of the B<216>had<193>-ra<207>yaka Upani<218>ad supports ç
this view (3.7.22).
@NT = K<218>etrap<193>la
@N1 = (`guardian of the site')
Among the subsidiary deities in the temples of <185>iva, the K<218>etrap<193>la ç
occupies an important place. He is the chief guardian of the temple. ç
His image is usually naked, with protruding eyes, sharp fangs in the ç
mouth and dishevelled hair. Snakes are his ornaments. He is shown ç
with two or four or even six hands carrying a sword, a bell, a trident, ç
a noose, a skull-cup and fire.
He may have three aspects according to the three gu<207>as, sattva, ç
rajas and tamas. He stands on a lotus and is accompanied by a dog. ç
He is worshipped first before commencing the regular service of the ç
day.
He seems to be an aspect of Bhairava.
K<218>etrap<193>la can also be an independent deity with his own shrine, ç
usually set up in the north-eastern corner of the village or town. ç
This shrine should not face east.
@SPACE1 = 
@NT = k<218>ipta
@N1 = (`thrown about')
@SPACE1 = 
According to the Yogas<220>tras of Pata<210>jali (200 <MS>B.<|>C.<D>) ç
the citta or the mind has five states. K<218>ipta is the first state. ç
In this state the mind is constantly thrown about (k<218>ip = to throw) ç
from one sense-object to another. Hence no yoga or concentration is ç
possible in this state.
@SPACE1 = 
@NT = K<218><200>rabhav<193>n<200>
@N1 = (`Bhav<193>n<200> [the Divine<R>ç
Mother] [who is fond of] milk')
@SPACE1 = 
K<193>·m<200>ra or the modern Kashmir is one of the very old parts ç
of India full of several sacred spots. An ancient and voluminous work ç
called the Bh<216><209>g<200>·a Sa<221>hit<193>, fragments of which ç
only are available now, that too in the manuscript form, is said to ç
contain details of all these places.
Along with the Amaran<193>th cave and the Vai<218><207>o Dev<200> ç
shrine, K<218><200>rabhav<193>n<200> ranks as the third centre of ç
Hindu pilgrimage in Kashmir.
According to one version, it is one of the 51 <185>aktip<200><219>has ç
where the neck of the sat<200> D<193>k<218><193>ya<207><200> fell. ç
(See <MS>TANTRAS<D>.)
The K<218><200>rabhav<193><207>i (or the modern Khir Bhawani) is situated ç
at the village Tul<193>m<220>la (or Tulamulla), which is 4 kms. (2.5 ç
miles) from Gandharbal and 44 kms. (27 miles) to the north west of ç
the capital Srinagar. The temple is a small structure of marble with ç
its dome covered by thin gold leaf. The present temple was builtby ç
the Mah<193>r<193>ja Prat<193>p Si<209>gh in <MS>A.<|>D.<D> 1912. It ç
contains the images of the Dev<200> knownas Mah<193>r<193>j<210><193> ç
and of <185>iva called Trisandhe·vara. It is situated inside a ku<207><195>a, ç
a natural water tank of small size, hexagonal in shape. The water ç
constantly supplied by several natural springs is about 2 metres (6.5 ç
ft.) deep.
This water is often changing its colour, the colours usually seen ç
being white, red, brown, yellow, blue and black. People believe that ç
when the water turns blackish, it is a bad omen for the country.
All worship by the devotees is offered to the waters of the ku<207><195>a ç
from outside. K<218><200>ra (milk) and mi<218><219><193>nna (rice ç
pudding) are considered dear to the goddess.
Jye<218><219>ha-·ukla-a<218><219>am<200> (generally occurring during ç
June) is the main festival day when pilgrims throng in thousands.
The shrine complex is being taken care of by the Dharmarth Trust of ç
the State. It has effected several improvements as follows: a p<220>j<193>ma<207><219>apa ç
measuring 10 by 5 metres (34 ft. by 17 ft.) in front of the ku<207><195>a; ç
sheds for performing homas (fire-rituals); an electric pump to clean ç
the water of the ku<207><195>a, generally once in 2to 3 years; Dharma·<193>las ç
or guest-houses for the visiting pilgrims.
The little island containing the ku<207><195>a of the Dev<200> is ç
full of Chinar trees.
Each one of the br<193>hma<207>a families in Kashmir has a kuladevat<193> ç
(goddess of the family). K<218><200>rabhav<193><207>i is the goddess ç
for most of them.
A brief account of the local legends may be given here:
@SPACE1 = 
The Dev<200> (K<193>l<200> or P<193>rvat<200>) got angry with the ç
demon king R<193>va<207>a, in whose kingdom she had settled, and asked ç
Hanum<193>n along with 360 N<193>gas (snake-chieftains) to take her ç
to K<193>·m<200>ra. Hanum<193>n did so, settling the Dev<200> in her ç
different aspects, in different places. The N<193>gas too were given ç
appropriate places to live.
According to another version, the Dev<200> shifted to K<193>·m<200>ra ç
from La<209>k<193> and started begging for food from the houses of ç
a few br<193>hma<207>as. They gave her k<218><200>ra or inspissated ç
milk. She settled down at the present place of pilgrimage. Later on, ç
a temple was built there.
As regards the discovery of this place also, there are two stories. ç
According to the first, the goddess appeared to one Pandit Govind ç
Joo Gadru and showed him the place. When he saw it, he poured milk ç
which he had brought in a number of earthern vessels into the spring.
According to the second, a pious br<193>hma<207>a, K<216><218><207>apa<207><195>ita ç
by name, was informed by a divine being about the existence of the ç
spring of the Divine Mother. As directed by the being, the Pa<207><195>it ç
started in a boat and went behind a serpent that guided him to the ç
marshy spot. The pa<207><195>it then got it filled up with several ç
loads of earth to prepare the present place of pilgrimage.
@SPACE = 
@NT = k<218><200>rasamudra
@N1 = (`ocean of milk')
@SPACE = 
The pur<193><207>as describe seven oceans (sapta-mah<193>samudras) ç
in the universe. Out of them, the k<218><200>rasamudra (the ocean ç
of milk) also is one. It surrounds the island called Krau<210>cadv<200>pa.
It is said to have been formed by the profuse outflow of milk from ç
the udder of the celestial cow Surabhi.
Mah<193>vi<218><207>u is said to have made it his abode, wherein he ç
lies on the serpent <185>e<218>a which is floating on the ocean.
It is by churning this ocean that am<216>ta or ambrosia was produced. ç
(See <MS>SAMUDRA-MATHANA.<D>)
According to another version, <185>iva is said to have given this ç
ocean of milk to Upamanyu, the young son of the sage Vy<193>ghrap<193>da.
@SPACE1 = 
@NT = K<218><200>rasv<193>min
@SPACE1 = 
Of all the lexicons in Sanskrit, the Amarako<218>a of Amarasi<221>ha ç
(5th century <MS>A.D.<D>) is the most famous one and has attracted ç
many scholars to comment and expound it. One of the better known commentators ç
is K<218><200>ra or K<218><200>rasv<193>min who was a scholar attached ç
to the court of the king Jayaprada of Kashmir and might have lived ç
in the 8th century <MS>A.<|>D<D>. Other sources assign him to the 11th ç
century <MS>A.D<D>.  His  commentary  is  known  as Amarako<218>odgh<193><219>ana.
K<218><200>rasv<193>min is said to have composed a commentary on the ç
Dh<193>tup<193><219>ha of P<193><207>ini (5th century <MS>B.<|>C.<D>) ç
also.
@SPACE1 = 
@NT = Kubera
@SPACE1 = 
Born as the son of the sage Vi·ravas and Devavar<207>i, Kubera was ç
the king of La<209>k<193>. When his cousins, R<193>va<207>a and Kumbhakar<207>a, ç
defeated him in a battle and usurped his kingdom, he did severe penance ç
to please Lord <185>iva. By his grace he built a new kingdom and capital ç
(known as Alak<193>pur<200>) on the Him<193>layas near Kail<193>sa, ç
the abode of <185>iva.
He was the lord of the yak<218>as (a type of demigods) and possessed ç
immense wealth. Nalak<220>bara, famous for his extra-ordinary handsomeness, ç
was his son from his wife <184>ddhi.
He blessed Arjuna†when he was per- forming tapas in the Indrak<200>la ç
mountain† with several divine weapons.
Kubera is one of the eight dikp<193>lakas, protectors of the quarters, ç
ruling over the North.
@NT = Kucela
See <MS>SUD°MA.<D>
@NT = kuh<220>
Religious rites must always be performed on certain days considered ç
as good and auspicious. Similarly, they should be avoided on inauspicious ç
days.
According to the sm<216>tis and the pur<193><207>as the sage A<209>giras ç
begot four daughters from his wife Sm<216>ti. They were: Anumati, ç
Sin<200>v<193>l<200>, Kuh<220> and R<193>k<193>. They were considered ç
as the goddesses associated with certain phases of the moon producing ç
good or evil results.
Kuh<220> is the goddess associated with the new-moon day mixed with ç
the (next) first day of the bright fortnight. If, in addition, the ç
planets R<193>hu, S<220>rya (Sun), <185>ani (Saturn) and Kuja (Mars) ç
in the zodiacal  sign  Makara  (Capricorn)  get assembled, it is called ç
Kuh<220>yoga.
The Kuh<220>yoga, though it may occur once in centuries, is considered ç
as an extremely inauspicious moment, dangerous, or even fatal, for ç
the rulers.
It is said that this occurred during the reign of K<216><218><207>adeva ç
R<193>ya (<MS>A.<|>D.<D> 1488-1529) (the famous ruler of the Vijayanagar ç
kingdom) and that he was saved by the M<193>dhva sage Vy<193>sar<193>ya ç
(<MS>A.<|>D.<D> 1447-1539).
@NT = Kuja
See <MS>MA<177>GALA.
@NT = Kukke Subrahma<207>ya
Situated between two hills†Kum<193>raparvata and <185>e·aparvata†and ç
very near the rivulet Kum<193>radh<193>r<193>, Kukke Subrah-ma<207>ya ç
is a well-known pilgrim centre of Karnataka State. It is 105 kms. ç
(65 miles) to the south-east of Mangalore. It was originally known ç
as Pu<218>pagiri and Kukke-pa<219><219>a<207>a (the word Kukke probably ç
means b<193>la or child.).
It is believed that the original shrine of Subrahma<207>ya, the chief ç
deity of this temple, may be at least 1500 years old.
According to the local legends, Subrahma<207>ya†also known as Kum<193>ra, ç
Skanda and <186>a<207>mukha (the one with six faces)†is said to have ç
washed his weapon, the <185>akti, in the waters of the Kum<193>ra-dh<193>r<193>, ç
after killing the demon T<193>rak<193>sura. Hence its name. The waters ç
of this river is said have the power to cure skin diseases.
The chief deity of the temple complex is the six-faced Subrahma<207>ya. ç
Over this image is the icon of a seven hooded serpent.
@SPACE1 = 
In the north-east corner, there is another shrine with the images ç
of the five deities Ambik<193> (Durg<193>), Vi<218><207>u, Ga<207>apati, ç
®·vara and S<220>rya. There are also other shrines dedicated to Lak<218>m<200>narasi<221>ha ç
and Um<193>mahe·vara.
There  is  a  Subrahma<207>ya  Ma<219>ha (monastery) belonging to ç
the M<193>dhva tradition, the first pontiff of which was Vi<218><207>ut<200>rtha ç
(Younger brother of Madhva [<MS>A.<|>D.<D> 1238-1317]).
The original deity of this temple is in a place 250 metres (820 ft.) ç
away from the outer wall to the north. Here, there is only an anthill ç
(with live snakes) which is worshipped as the deity Subrahma<207>ya.
The greatest festival of this temple is  the  Subrahma<207>ya<218>a<218><219>h<200>  usually  in ç
December.
<185>a<209>kara (<MS>A.<|>D.<D> 788-820) is said to have visited this ç
place.
@NT = kula
Though the literal meaning of the word is `clan' or `family', it has ç
been used in a more technicalsenseinthet<193>ntrik literature. ç
`Kula' is interpreted as `<185>akti' or the `Divine Mother' and the ç
disciplines of the tantras advocating her worship are known as `Kaulam<193>rga' ç
or `Kaul<193>c<193>ra'. As per this definition, kula can also mean ç
the spiritual lineage from the guru to the disciple, the °diguru or ç
Primeval Teacher being <185>iva Himself.
Kula, va<221>·a or gotra (lineage) is a very important factor considered ç
especially in the settling of marriages.
@NT = Kulaparvata
@N1 = (`a mountain that<R>ç
demarcates')
Pur<193><207>ic  geography  of  the  world mentions seven dv<200>pas ç
(island continents) each of which (except the last) has seven Kulaparvatas. ç
These Kulaparvatas are mountains that demarcate the lands in the above ç
mentioned island-continents.
Bh<193>ratavar<218>a (the Indian Subcontinent) is a part of the Jamb<220>dv<200>pa. ç
Its Kulaparvatas  are:  Mahendra,  Malaya, Sahya, <185>aktim<193>n, ç
<184>k<218>a, Vindhya and P<193>riy<193>tra.
Similarly there are Kulaparvatas in other dv<200>pas also. For instance, ç
Gomoda in Plak<218>adv<200>pa; Kumuda in <185><193>lmali; Vidruma ç
in Ku·adv<200>pa; V<193>mana in Krau<210>cadv<200>pa; Raivataka in ç
<185><193>kadv<200>pa and M<193>nasottara in Pu<218>karadv<200>pa.
@NT = kulapati
@N1 = (`head of a gurukula')
Education in the olden days was completely residential. The house ç
of the <193>c<193>rya or the teacher where the students resided and ç
learnt, was called `<193>c<193>ryakula'.
When the campus grew big and the number of resident-students went ç
beyond ten thousand, the chief <193>c<193>rya who was the head of ç
the institution came to be known as `kulapati'.
See also <MS>GURUKULA.<D>
@NT = Kula·ekhara °<202>v<193>r
See <MS>°<170>V°RS.<D>
@NT = Kull<220>kabha<219><219>a
The life of an average Hindu was generally guided†both at the individual ç
and at the social level†by the sm<216>tis and the dharma·<193>stras. ç
Among all the sm<216>tis, the most ancient and the most widely accepted ç
one is the Manusm<216>ti (100 <MS>B.<|>C.<D>).
Of all the commentaries on this work, the Manvarthamukt<193>val<200> ç
of Kull<220>kabha<219><219>a is the most widely known and has been ç
printed several times.
Kull<220>kabha<219><219>a was the son of Bha<219><219>a-div<193>kara ç
and belonged to the V<193>rendra family of Bengal. He must have flourished ç
sometime during the period <MS>A.<|>D.<D> 1150-1300. This work was ç
probably composed around <MS>A.<|>D.<D> 1250 in K<193>·<200>.
His commentary is concise, lucid and to the point. He avoids all unnecessary ç
discussions though he is quite critical ofMedh<193>tithi (circa <MS>A.D.<D> ç
825-900) and Govindar<193>ja (11th century <MS>A.<|>D.<D>) both of ç
whom also wrote commentaries on the Sm<216>ti of Manu.
<185>r<193>ddhas<193>gara  is  another  work attributed to him wherein ç
he deals with the following topics: times and places suitable for ç
·r<193>ddha; a<218><219>ak<193>·r<193>ddha which even the ·<220>dras ç
can perform; details regarding   inter-calary   months;   the yaj<210>opav<200>ta ç
or the sacred thread and so on.
This work was perhaps, a part of a bigger work called Sm<216>tis<193>gara ç
not available now. Viv<193>das<193>gara and A·aucas<193>gara are ç
two more works, alluded to, by him, which too must have been a part ç
of this bigger work.
Kull<220>kabha<219><219>a was an adept in the P<220>rvam<200>m<193><221>s<193> ç
doctrines.
See also <MS>MANUSM<184>TI.<D>
@NT = Kum<193>ra
@N1 = (`the young boy')
See <MS>SUBRAHMAØYA.<D>
Kum<193>ra is also the name of a person who authored a digest of dharma·<193>stras ç
and quoted by many other authors. But nothing is known of him.
A boy below five years is called a `kum<193>ra'. No cognisance is ç
taken of any`sin' or transgressions of dharma committed by him for ç
obvious reasons. Sometimes his parents have to undergo expiations ç
for purifying or protecting him and themselves.
@NT = Kum<193>ra-Vy<193>sa
@N1 = (`the young or junior Vy<193>sa')
The R<193>m<193>ya<207>a and the Mah<193>bh<193>rata have influenced ç
the Hindu psyche to suchan extent over the last two millennia that ç
works in many vernaculars, either summarising them or imitating them ç
or adopting them as the basis, have been composed. The most well-known ç
Mah<193>bh<193>rata in the Kannada language is the Kar<207><193><219>a-bh<193>rata-kath<193>ma<210>jar<200>, ç
more popularly known as Kum<193>ra Vy<193>sa Bh<193>rata or Gadugina ç
Bh<193>rata.
The author of this work, N<193>ra<207>appa, lived most probably during ç
the period <MS>A.D.<D> 1350 to 1425. He belonged to a village near ç
Gadag in Northern Karnataka and was a devotee of V<200>ran<193>r<193>ya<207>a, ç
the deity of the chief temple there. He was probably a vai<218><207>ava ç
of the Bh<193>gavata school. His work is a poetical composition in ç
the well-known metre called `bh<193>min<200><218>a<219>pad<200>'. ç
It is in ten parvas or books or sections and covers the entire story ç
of the Mah<193>bh<193>rata. <185>r<200> K<216><218><207>a is the ç
chief hero in this work. Its literary quality has been highly eulogised. ç

Air<193>vata is another poetical work attributed to him. It deals ç
with the heroic exploits of Arjuna, the P<193><207><195>ava hero.
@NT = Kum<193>rila Bha<219><219>a
Kum<193>rila Bha<219><219>a was one of the two most important teachers ç
and scholars who fought with the nihilistic philosophies of Jainism ç
and Buddhism to re-establish the glory of Vedic religion. The other ç
teacher was <185>a<209>kara (<MS>A.<|>D.<D> 788-820), his junior contemporary.
Kum<193>rila Bha<219><219>a hailed probably from Mithil<193> (in Bihar) ç
and might have lived during the period <MS>A.<|>D.<D> 650-700. He was ç
a rich householder and also a great scholar. The story goes that he ç
was defeated by a well-known Buddhist teacher, Dharmak<200>rti by ç
name. After adopting Buddhism and studying its tenets deeply under ç
Dharmap<193>la, he is said to have defeated Dharmap<193>la himself.
As per the agreement, Dharmap<193>la had to commit suicide by burning ç
himself in paddy husk set on fire.
Kum<193>rila is also credited with victories over the Jains in the ç
court of theking Sudhanva in Kar<207><193><219>ade·a, in South India.
When <185>a<209>kara came to Kum<193>rila with a view to having a ç
philosophical disputation,  he  was  actually  burning himself as ç
an expiation for the sin of cheating his Buddhist guru. As per his ç
direction, <185>a<209>kara is said to have gone to Ma<207><195>ana ç
Mi·ra for the same.
Kum<193>rila was a very great scholar. He has written, in the v<193>rttika ç
form (explanatory notes in verses), a detailed commentary on the <185><193>barabh<193><218>ya ç
of the M<200>m<193><221>s<193>s<220>tras of Jaimini. They are inthree ç
parts known as <185>lokav<193>rttika, Tantrav<193>rttika and <187>up<219><200>k<193>. ç
Other works attributed to him by certain later writers† such as B<216>hat<219><200>k<193> ç
and Madhyama<219><200>k<193>† are not available now.
Prabh<193>kara, Ma<207><195>anaMi·raand Umbeka (or Bhavabh<220>ti) ç
were his chief disciples.
@NT = kumbhaka
@N1 = (`retention')
See <MS>PR°Ø°Y°MA.<D>
@NT = Kumbhakar<207>a
@N1 = (`one whose ears were like a pot')
See <MS>R°M°YAØA.
@NT = Kumbhako<207>am
The town of Kumbhako<207>am is one of the oldest centres of Hindu ç
pilgrimage in South India. It is situated at a distance of 70 kms. ç
(43 miles) to the south-west of another famous place of pilgrimage, ç
Cidambaram (in Tamil Nadu). The rivers K<193>ver<200> and Arasalar ç
flow on the two sides of the town.
The Am<216>takumbha (pot containing nectar) established by Brahm<193>, ç
the creator, at the instance of <185>iva, is said to have stopped ç
here, after being carried by the waters of pralaya (destruction of ç
the world). Hence the name Kumbhako<207>am.
This town contains many ancient temples. There are twelve of <185>iva, ç
four of Vi<218><207>u and one of Brahm<193> (which is extremely rare).
The temple of S<193>ra<209>gap<193><207>i (Vi<218><207>u) is the most ç
imposing of all the temples. Its central shrine is probably the oldest ç
part of the complex since eight of thetwelve °<202>v<193>rs have ç
sung its praise. Additions were made by the N<193>yak kings during ç
the period <MS>A.<|>D.<D> 1300-1700. Its gopuram (tower) is 44 metres ç
(146 feet) high and has 12 storeys. There are numerous ornamental ç
figures.
Two main entrances lead to the central shrine. The southern entrance ç
isused during the dak<218>i<207><193>yana period (period of the southern ç
solstice, July to January) and the northern entrance during the uttar<193>ya<207>a ç
period (period of northern solstice, january to July).
The shrine of Komalavall<200> (Lak<218>m<200>, consort of Vi<218><207>u) ç
is in the northern part of the temple.
There is a pu<218>kara<207><200> (temple tank) also, next to the temple, ç
meant for bathing by the devotees before they enter. The annual teppotsava ç
(floating festival) is alsoheld here in the month of M<193>·i (in ç
March).
The p<220>j<193> (worship) and allied rituals are done according to ç
the P<193><210>car<193>tra °gamas.
There are two big rathas (temple chariots) made of wood with elaborate ç
carvings. There is, in addition, one made of silver used on special ç
occasions.
The Kumbhe·vara temple also is a big one and is located in the centre ç
of the town. Its main gopuram is 38 metres (128 feet) high and has ç
many intricately carved sculptures on it. The temple can boast of ç
quite a few silver v<193>hanas (palanquins) used to carry the various ç
deities during festival days.
There is another temple of <185>iva† known as N<193>ge·vara <185>iva ç
temple†which contains a shrine for S<220>rya (the Sun-god) also. The ç
rays of the sun enter the inner sanctum through the openings in the ç
gopuram three times a year and fall right on the <185>ivali<209>ga! ç
This is considered as the worship of <185>iva by S<220>rya himself.
The   R<193>masv<193>mi   temple   built probably in the 16th century ç
has the images of R<193>ma's brothers also apart from that of S<200>t<193>. ç
There are sculptures on the pillars and murals on the walls depicting ç
scenes from the R<193>m<193>ya<207>a.
@SPACE1 = 
Some of the other Vai<218><207>avite temples of Kumbhako<207>am are: ç
Cakrap<193><207>i temple; Var<193>ha  temple;  Gop<193>lasv<193>mi  temple; ç
Varadar<193>ja temple and Vedan<193>r<193>ya<207>a temple.
Another  important  place  for  the pilgrims in Kumbhako<207>am is ç
the Kany<193>t<200>rtha, more commonly known as the Mah<193>m<193>gham ç
tank. It is a huge lakespread over an area of 20 acres (8hectares). ç
There are 16 towers with ma<207><195>apas (small halls) all-round ç
this tank. Once in 12 years, on the p<220>r<207>im<193> (full-moon) ç
day of the month of M<193>gha (in February) when Guru (Jupiter) is ç
in Si<221>ha (Leo) and Candra (Moon) is in the Makha Nak<218>atra, ç
a very big bathing festival is held here. This is called Mah<193>m<193>kham ç
or Mah<193>m<193>gham. All the sacred rivers are supposed to be present ç
in the water on this day.
There is also an ancient Ma<219>ha (ormonastery belonging to the ç
Advaita tradition)†the K<193><210>c<200> K<193>mako<219>i P<200><219>ham† ç
in Kumbhako<207>am existing since <MS>A.<|>D.<D> 1743.
@NT = Kumbhamel<193>
Once in 12 years is held the biggest religious fair of the whole world, ç
called `Kumbhamel<193>'.
As per a legend widely believed by the devout Hindus, the Am<216>ta ç
Kumbha or the pot of nectar that emerged out of the milky ocean during ç
its churning, was carried away by Jayanta, the son of Indra, to heaven, ç
being hotly pursued by the asuras or demons. In the process of this ç
carrying, which took him 12 days (of the gods, being equivalent to ç
12 human years) Jayanta is said to have dropped a little of it in ç
four places: Pray<193>ga (Allahabad) (in Uttar Pradesh), Haradv<193>ra ç
or Hari-dv<193>ra (now Hardwar) (in Uttaranchal), Ujjayin<200> (in ç
Madhya Pradesh) and N<193>sik (in Maharashtra). That is why the Kumbhamel<193> ç
fair is held, once in 12 years, in all these places by turns.
During the period of M<193>ghamel<193> (a religious festival held ç
in Pray<193>ga during the month of M<193>gha in January), hundreds ç
of persons live on the banks of the river, practising  austerities†this  is  called ç
`Kalpav<193>sa'†like taking bath in the river thrice a day, living ç
on simple food or even fruits, doing a lot of japa (repetition of ç
God's name) and meditation and giving gifts to deserving persons.
On the special days earmarked for the bath†like the Makara Sa<209>kr<193>nti ç
or Maun<200> Am<193>v<193>sy<193>†the pilgrims take a complete shave. ç
After the ceremonial bath and offering prayers, they make gifts according ç
to their capacities.
During the periods of Kumbhamel<193> thousands of s<193>dhus and sa<221>ny<193>sins, ç
mendicants  and  religious  persons  of various denominations, cults ç
and groups congregate at the sites of the mel<193>. Apart from  ceremonial  processions,  religious ç
discourses, discussions, k<200>rtans (devotional songs) and other ç
religio-cultural activities are also organized by them in their camps.
@NT = Ku<207><195>alin<200>
@N1 = (`the coiled one')
See <MS>CAKRAS<D> and <MS>TANTRAS.<D>
@NT = Ku<207><195>ikopani<218>ad
Classed among the minor Upani<218>ads, the Ku<207><195>ikopani<218>ad ç
of the S<193>maveda deals entirely with sa<221>ny<193>sa or monastic ç
life. There are 34 verses, almost all in the anu<218><219>ubh metre.
After completing the first stage of brahmacarya by studying the Vedas ç
under a competent teacher, a person has to marry a suitable girl and ç
settle down as a house- holder. Once the various duties of the householder's ç
life are fulfilled, he has to distribute his property among his sons ç
and take to the life of a v<193>naprastha or forest-recluse. In this ç
stage, he has to lead a very austere life depending upon air or water ç
or roots and fruits of the forest for living.
Once his vair<193>gya or spirit of renunciation becomes ripened, he ç
should decide to embrace the monastic life. In this way of life, he ç
should totally give up all actions (including the Vedic fires themselves) ç
and dedicate himself to the realisation of the <193>tman/Brahman (the ç
Self of all) by the repetition of the well-known Upani<218>adic Mah<193>v<193>kyas. ç
He must also adopt the monk's way of life by wearing the red-robes ç
and keeping a few necessary things like the ku<207><195>ik<193> or ç
kama<207><195>alu (water-pot), a cup made of the coconut shell, cloth ç
for filtering water, footwear, a loin-cloth, an upper cloth and a ç
blanket.
He should†when not travelling†stay at temples or river-banks and other ç
(deserted) places.
He should never care for the comforts or discomforts of the body nor ç
for the praise or blame of people.
If he cannot follow the path of j<210><193>na as described in the ç
Vedas, he can practise the yoga of rousing the Ku<207><195>alin<200>.
@SPACE1 = 
If he realises the <193>tman here and now, he will become a j<200>vanmukta ç
and enjoy great bliss.
Otherwise, he gets kramamukti or gradual liberation by leaving the ç
body through the brahmarandhra (aperture in the cranium) and passing ç
through the devay<193>na.
The Upani<218>ad ends with a brief description of the brahmaj<210><193>ni's ç
subjective experience.
See also <MS>UPANI<186>ADS.<D>
@NT = Kunt<200>
Among all the women characters of the Mah<193>bh<193>rata, Kunt<200>, ç
the mother of the P<193><207><195>avas, impresses us as a noble and ç
gentle lady, a personification of fortitude, even in the most troublesome ç
periods of her life.
Known formerly as P<216>th<193>, the daughter of the king <185><220>ra ç
of the race of the Yadus (and a sister of Vasudeva, K<216><218><207>a's ç
father) she was adopted by the king Kuntibhoja. Hence she acquired ç
the name `Kunt<200>' which stuck.
Once, as a girl, while attending upon the sage Durv<193>sas in her ç
father's house, the sage, being pleased by her devoted service, taught ç
her a special mantra by which she could invite a god to come to herself ç
to bless her with a child. Out of sheer curiosity, she tried it, inviting ç
S<220>rya or the Sun-god. As a result, a brilliant and valorous son ç
was born to her. Being an unwed girl and afraid of calumny she left ç
the baby floating in the nearby river after putting it in a wooden ç
box. The box was recovered by one Adhiratha (the charioteer of Dh<216>tar<193><218><219>ra) ç
who along with his wife R<193>dh<193>, adopted him as his son and ç
brought him up. This was Kar<207>a.
Kunt<200> was married to P<193><207><195>u, the younger brother of ç
the blind prince Dh<216>tar<193><218><219>ra. M<193>dr<200> was her ç
co-wife. Since P<193><207><195>u was under a curse and could not get ç
children in the normal way, Kunt<200> revealed to him, about the gift ç
of mantra she had received from the sage Durv<193>sas. With P<193><207><195>u's ç
permission she begot three sons (Yudhi<218><219>hira, Bh<200>ma and ç
Arjuna) and M<193>dr<200> too, with her help, gave birth to the twins†Nakula ç
and Sahadeva.
After the death of P<193><207><195>u and M<193>dr<200>, she brought ç
the five P<193><207><195>avas to Bh<200><218>ma, the grandsire, for ç
bringing them up and for proper education.
She accompanied the P<193><207><195>avas after they escaped from the ç
arson of the inflammable house built of lac, to the small town Ekacakranagara. ç
It was she who encouraged her son Bh<200>ma to kill the demon Bak<193>sura, ç
who was harassing the residents of that town.
When the P<193><207><195>avas were banished to the forest after the ç
second game of dice, she lived in the house of Vidura, the minister ç
of Dh<216>tar<193><218><219>ra.
Before the Kuruk<218>etra war, she met Kar<207>a, revealed the secret ç
of his birth and advised him to join the P<193><207><195>avas. (However ç
Kar<207>a politely refused.)
After the war and Yudhi<218><219>hira was crowned the king, she retired ç
to the forest along with G<193>ndh<193>r<200> and Dh<216>tar<193><218><219>ra. ç
There she perished in a forest fire.
@NT = Kura<202>
See <MS>TIRUKKURA<170>.<D>
@NT = k<220>rca
Ku·a grass (Poa cynosuroides) is widely used in Vedic sacrifices ç
for various purposes.
K<220>rca is a bundle of this grass generally used as a seat, a sort ç
of a cushion, on which the sacrificer and the adhvaryu priest sit.
K<220>rca is also the name of a small elongated plate made of Ku·a ç
grass or V<193>ra<207>a wood (Crataeva roxburghii) about 36 a<209>gulas ç
in length and shaped like a tortoise or a dolphin. It is kept on the ç
west of the <193>havan<200>ya fire. The ·rucas (sacrificial ladles) ç
are kept on it when not in use.
@NT = K<220>re·a
Great religious leaders have often been helped by highly dedicated ç
disciples who assisted them tirelessly but, themselves remained in ç
the background. K<220>re·a a trusted disciple of R<193>m<193>nuja ç
(<MS>A.<|>D.<D> 1017- 1137) was one such fortunate soul. Hewas a wealthy ç
land-lord living near K<193><210>c<200>- puram (in Tamil Nadu). He ç
was as gener- ous as he was rich. His wife, °<207><195><193><202>amma ç
too, was of the same disposition.
The couple renounced everything and followed R<193>m<193>nuja wherever ç
he went. When they stayed at <185>r<200>ra<209>gam, K<220>re·a used ç
to live by begging. One day, a divinely handsome boy appeared before ç
°<207><195><193><202>amma and gave her the sacred food offerings of ç
<185>r<200> Ra<209>gan<193>tha, the main deity of the temple there. ç
After consuming this sacramental food, she conceived and gave birth ç
to twins. R<193>m<193>nuja named them as Par<193>·ara and Vy<193>sa.
Par<193>·ara later became a great scholar and wrote an erudite commentary ç
on the famous hymn, the Vi<218><207>usahasran<193>ma.
When the Co<202>a king Kulottu<209>ga, who was a fanatic <185>aiva, ç
wanted to eliminate R<193>m<193>nuja and sent his men, K<220>re·a ç
impersonated himself as R<193>m<193>nuja and went to his court. The ç
evil king gouged out his eyes! Thus K<220>re·a sacrificed himself ç
to save his guru.
He spent his last days near Madurai.
@SPACE1 = 
See also <MS>R°M°NUJA.<D>
@NT = K<220>rma
@N1 = (`the tortoise')
On the suggestion of Mah<193>vi<218><207>u, the devas (gods) and the ç
d<193>navas (demons) started churning the k<218><200>rasamudra (the ç
ocean of milk) for obtaining am<216>ta or ambrosia. The mount Meru ç
was the churning rod and V<193>suki, the serpent king was the rope. ç
During the process of churning, the mount Meru started sinking. So, ç
at the request of the two parties, Mah<193>vi<218><207>u took the ç
form of a huge k<220>rma or tortoise and supported the Meru mountain ç
on his back. This is considered as the K<220>rm<193>vat<193>ra or ç
K<220>rma incarnation of Mah<193>vi<218><207>u.
Iconographically he is shown either as a tortoise or with the lower ç
part as a tortoise and the upper part in the human form but with four ç
hands, two hands carrying the emblems of Vi<218><207>u (·a<209>kha ç
or conch and cakra or the discus) and the other two showing the poses ç
of abhaya (protection from fear) and varada (giving of boons). Sometimes ç
the gad<193> (mace) is shown in the right hand instead of the discus.
K<220>rma is also the name of one ofthe five upapr<193><207>as (minor ç
vital-airs) responsible for opening the eyelids.
K<220>rma is also the name of a mudr<193> (handpose) used in p<220>j<193> ç
or worship.
@NT = K<220>rmapur<193><207>a
See <MS>PUR°ØAS.<D>
@NT = Kuru
The words Kuruj<193><209>gala, Kuru-p<193><210>c<193>la and Kuruk<218>etra ç
are often found in the Hindu epics and the pur<193><207>as. All these ç
are connected with Kuru, who was the founder of the dynasty Kuruva<221>·a. ç
He  was  the  son  of  Sa<221>vara<207>a  (of Candrava<221>·a or the ç
race of the Moon) and Tapat<200>.
There was another Kuru, the seventh son of the king °gn<200>dhra who ç
had nine sons. He became the ruler of 1/9 th of his father's kingdom ç
which came to be known as Kuruvar<218>a.
Kuru, the son of the king Sa<221>vara<207>a, built a y<193>ga·<193>l<193> ç
(a huge campus for performing Vedic sacrifices) between the river ç
Sarasvat<200> and D<216>·advat<200>, later known as Kuruk<218>etra. ç
There is no unanimity among the scholars about this Kuruk<218>etra ç
being the same where the Mah<193>bh<193>rata war took place.
@NT = Kuruke·a
@N1 = (<MS>A.<|>D.<D> 1061-1161)
Great spiritual teachers often have great disciples to carry on their ç
work even after they leave this world. One such disciple of R<193>m<193>nuja ç
(<MS>A.<|>D.<D> 1017-1137), considered as his `j<210><193>naputra', ç
(spiritual son)  was  Kuruke·a,  also  known  as Tirukkurugaippir<193>n ç
Pi<202><202><193>n. He was the son of R<193>m<193>nuja's maternal ç
uncle <185>r<200>·ailap<220>r<207>a and was born in Tirumalai in <MS>A.<|>D.<D> ç
1061. R<193>m<193>nuja chose him to complete one of the three promises ç
he had made to fulfil the last wishes of Y<193>mun<193>-c<193>rya ç
(<MS>A.<|>D.<D> 912-1042). This was to get composed an authoritative ç
commentary in Tamil on the Tiruv<193>ymo<202>i of Namm<193><202>var.
He had acquired great erudition in the Sanskrit and the Tamil scriptures. ç
Equally laudable was his single-minded devotion to R<193>m<193>nuja.
When R<193>m<193>nuja got an image of Lak<218>m<200>-Hayagr<200>va ç
(an aspect of Vi<218><207>u) in Kashmir, he gave it to Kuruke·a for ç
worship and reverential maintenance.
He was the first successor of R<193>m<193>nuja as the <193>c<193>rya ç
(pontiff).
He wrote a detailed commentary in the Ma<207>iprav<193><202>a language ç
(Sanskritised Tamil) on the Tiruv<193>ymo<202>i of Namm<193><202>var ç
in 6000 stanzas (called `granthas'). This work is known as °r<193>yirappa<195>i. ç
It is said to contain all the important doctrinal points expounded ç
in the <185>r<200>bh<193><218>ya of R<193>m<193>nuja.
He was also a good speaker in Sanskrit as well as Tamil, and conducted ç
discourses throughout his life.
He passed away in <MS>A.<|>D.<D> 1161.
@NT = Kuruk<218>etra
Though Kuruk<218>etra has been closely associated with the fratricidal ç
war of the Mah<193>bh<193>rata, it has also been hailed as the `dharmak<218>etra' ç
(field of righteousness) (vide Bhagavadg<200>t<193> 1.1). It is ç
almost the same as the modern Kuruk<218>etra, 40 kms. (25 miles) to ç
the east of Ambala in the Haryana State.
There is no doubt that it was consi-dered a very sacred spot even ç
from the most ancient times. It was the place where the gods had performed ç
many y<193>gas or sacrifices. It was the heart of Vedic culture in ç
the olden days. The lands to the southern and the northern parts were ç
known as Kh<193><207><195>ava and T<220>rghna. There was also a desert ç
near it.
According to another version it was the sacrificial ground of the ç
king Kuru, the son of Sa<221>vara<207>a and Tapat<200>, of the Candrava<221>·a.
It has been known by several other names such as Brahm<193>varta, ç
Kuruj<193><209>gala (situated between the rivers Sarasvat<200> and ç
D<216><218>advat<200>), Brahmasaras, R<193>mahrada, Samantapa<210>caka, ç
Vina·ana and so on.
The lake in Kuruk<218>etra was originally five big pools of blood ç
of the k<218>attriyas killed by Para·ur<193>ma which was converted ç
into a single lake of holy water by the grace of his pit<216>s or ç
forefathers who were pleased by his penance and forgave him. It is ç
oblong in shape and is 1063 metres (3546 ft.) in length. On the days ç
of solar eclipse, lakhs of people gather here for a holy dip.
The forests mentioned in the Mah<193>bh<193>rata  like  the  K<193>myakavana, ç
Aditivana  and  Vy<193>savana  were  near Kuruk<218>etra.
Hastin<193>pura (situated at a distance of 104 kms. or 65 miles to ç
the north-west of Delhi), Indraprastha (now a part of old Delhi), ç
Sth<193><207>e·vara (the present Thanesar in Haryana) and P<216>th<220>daka ç
(the present Pehova) were the famous cities of Kuru- k<218>etra. Kuruk<218>etra ç
has been considered a very holy place for the performance of ·r<193>ddhas.
@SPACE1 = 
Var<193>hat<200>rtha (where Vi<218><207>u stood in his incarnation ç
as a boar), Vy<193>sat<200>rtha (where Vy<193>sa wanted to give up ç
his body, but was dissuaded from doing so) and Saptasarasvata  (where  <185>iva  appeared ç
before the sage Ma<209>ka<207>aka) are the holy spots near Kuruk<218>etra ç
apart from the place where the Bhagavadg<200>t<193> was taught by ç
K<216><218><207>a to Arjuna.
The  modern  regions  of  Karnal, Panipat,  Sonepat  and  Amin  roughly ç
correspond to the ancient Kuruk<218>etra.
After independence, Kuruk<218>etra has been developed as a big pilgrim ç
and tourist centre.
@NT = Ku·a
As per the Uttarak<193><207><195>a of the R<193>m<193>ya<207>a ç
of V<193>m<200>ki (chs. 91, 98 and 108), Ku·a and Lava, the twins ç
were born of S<200>t<193> in the hermitage of V<193>lm<200>ki. S<200>t<193> ç
was pregnant when she had been banished by R<193>ma, being afraid ç
of the calumny that had spread in his kingdom, though both of them ç
were innocent and pure. S<200>t<193> had then been sheltered by the ç
sage V<193>lm<200>ki in his hermitage.
Ku·a and Lava were educated by V<193>lm<200>ki in the various arts ç
and sciences. He had also taught them to sing the whole of R<193>m<193>ya<207>a ç
to the accompaniment of musical  instruments.  The  boys  who attended ç
the A·vamedha sacrifice, along with V<193>lm<200>ki, endeared themselves ç
to one and all by their enchanting music and charming appearance. ç
After revealing the truth, V<193>lm<200>ki handed over S<200>t<193> ç
and the two boys to R<193>ma. S<200>t<193>, however, was absorbed ç
into the bowels of the earth by Bh<220>m<193>t<193> (Mother Earth) ç
at her request.
@SPACE1 = 
Later, R<193>ma coronated Ku·a as theking of Ku·<193>vat<200> near ç
the Vindhy<193> mountains and Lava at <185>r<193>vasti before exiting ç
from this world. Ku·a, later on, shifted his capital to Ayodhy<193>.
Ku·a had two wives, Campak<193> and Kumudvat<200>. His lineage continued ç
through the eight sons of the latter.
The word ku·a also stands for theku·a grass (same as darbha) (Poa ç
cynosuroides) used in religious rites and the island Ku·adv<200>pa, ç
one among the seven described in Hindu mythology.
@NT = ku·<193>sana
@N1 = (`seat of ku·a grass')
For a good meditation, a conducive external atmosphere is as much ç
necessary as internal conditions like the health of the body and a ç
peaceful mind.
A level and clean place, away from all sources of noise and disturbance ç
is a must. (vide <185>vet<193>·vatara Upani<218>ad 2.10). Sitting ç
posture is the most comfortable one (vide the Brahmas<220>tras ç
4.1.17). For this, a good seat is necessary.
The Bhagavadg<200>t<193> (6.11) recommends a seat comprising the ç
ku·a grass, the deerskin and a cotton cloth spread one over the other ç
in that order. The first one is called ku·<193>sana, a seat made of ç
ku·a grass (Poa cynosuroides).
Now-a-days, ku·<193>sanas made of ku·a grass woven like a small mat, ç
are available in the market.
Since the ku·a grass is considered holy  and  is  closely  associated  with ç
religious rites and ceremonies, the ku·<193>sana is recommended for ç
meditation as also in the religious ceremonies.
@NT = k<220><219>a·lokas
@N1 = (`verses with enigmatic <R>ç
meaning')
The Mah<193>bh<193>rata, the great epic of the Hindus, has a large ç
number of verses whose meaning is quite enigmatic. Their actual etymological ç
meaning and the sense they try to convey are not only different but ç
may even appear opposed to each other. Such verses or ·lokas are called ç
`k<220><219>a·lokas'.
According to the °diparva (1.79-83) the sage Vy<193>sa requested ç
Ga<207>apati, the god of learning, to take down the text of the Mah<193>bh<193>rata ç
as he went on reciting. Ga<207>apati laid down the condition that ç
Vy<193>sa should never stop reciting so that he could write it continuously. ç
Vy<193>sa put a counter-condition that Ga<207>apati should understand ç
the full meaning of the ·loka first, before writing it down. Whenever ç
Vy<193>sa needed some time to think of the next ·loka, he would compose ç
a `k<220><219>a·loka,' a ·loka with a difficult or double meaning ç
†and hence enigmatic†to keep Ga<207>apati guessing and thinking about ç
it before writing it down with his stylus. During the interval he ç
managed to get thus, hewould compose the next ·loka of the text!.
According to the Mah<193>bh<193>rata itself (°diparva 1.81) there ç
are 8,800 k<220><219>a·lokas in the work.
One example can make this more clear:
@SPACE1 = 
Duryodhana the wily genius, has planned to destroy his cousins, the ç
P<193><207><195>avas†whom he considers as his arch-enemies†by setting ç
fire to a palace at the city of V<193>ra<207><193>vata which he has ç
got built with highly combustible substances like lac and straw. He ç
has cleverly managed to make them agree to the proposal  of  retiring  to  that  city  and ç
live in that palace, the proposal itself coming from Dh<216>tar<193><218><219>ra. ç
The P<193><207><195>avas readily agree. Just before their departure, ç
Vidura,  the  wise  minister  of  the Kauravas and a great well-wisher ç
of the P<193><207><195>avas warns Yudhi<218><219>hira (the eldest ç
and the shrewdest of the P<193><207><195>avas) of the impending danger ç
and also suggests the solutions (vide °diparva, 145.20 to 26). Out ç
of these, only one verse (145.22) may be cited.
Direct translation: `One who knows about that weapon of the enemy ç
which is sharp and capable of killing, though not made out of metal, ç
will not be killed (or harmed) by it'.
The hidden meaning, however, is:
`One who knows that the house (or the palace) though made up of combustible ç
materials, has camouflaged itself (nicely) and will destroy him in ç
the night, will not be killed by the enemies.'
Yudhi<218><219>hira  gets  the  hint,  takes remedial  measures  and  successfully ç
escapes the arson attempt, along with his mother and brothers.
See also <MS>VANAPARVA<D> 188.42.
@NT = ku<219><200>caka
See <MS>PARAMAHA<189>SA.<D>
@END = 
