The root of the story of Matsy<193>vat<193>ra (Fish-incarnation) and ç
jalapralaya or water-deluge are also recorded here.
On the whole it can safely be declared that this <185>atapatha Br<193>hma<207>a ç
is one of the few and most important works of the Vedic literature.
See also <MS>YAJURVEDA.
@NT = <185>atarudriya
Japa or repetition of Vedic mantras or passages is said to purify ç
a person. One of such well-known passages is the Rudra or the Rudr<193>dhy<193>ya ç
(Taittir<200>ya Sa<221>hit<193> 4.5.1-11).
Since the Yajurveda has 102 ·<193>kh<193>s or recensions and since ç
this Rudra appears in all of them, it has been designated as <185>atarudriya ç
(·ata = one hundred) also.
See <MS>RUDRAPRA<185>NA.<D>
@NT = <185><193>t<193>tapa
<185><193>t<193>tapa is one of the ancient authorsof a sm<216>ti, ç
quoted by others like Y<193>j<210>avalkya, Par<193>·ara, Vi·var<220>pa ç
and Haradatta, especially on the topic of pr<193>ya·citta or expiations ç
for sins.
His work seems to have been both in prose and in verses. Or, the prose-work ç
in the form of s<220>tras and the one in verses may have been different ç
compilations.
The manuscript of a <185><193>t<193>tapa Sm<216>ti discovered, has ç
twelve chapters dealing with the following subjects: pr<193>ya·cittas, ç
viv<193>ha (marriage), vai·vadeva (offering of cooked food for all ç
gods, a domestic rite), ·r<193>ddha (obsequial rites), rules about ç
taking food, a·auca (observance of ceremonial impurities) and so on.
Another work called Karmavip<193>ka attributed to <185><193>t<193>tapa ç
contains different subjects like gifts of land, eulogy of br<193>hma<207>as, ç
rites for those who meet violent or accidental death and certain penances.
One more work called V<216>ddha-<185><193>t<193>tapa has also been ç
quoted by the writers and commentators of dharma-·<193>stras.
@SPACE = 
@NT = <218>a<219>cakrabheda
@N1 = (`piercing of the<R>ç
six cakras [by the Ku<207><195>alin<200>]')
@SPACE1 = 
See <MS>CAKRAS.
@SPACE = 
@NT = <185>a<219>hakopa
@SPACE1 = 
Namm<193><202>var†the most celebrated of the twelve °<202>v<193>rs ç
(those who are deeply immersed in God-consciousness)†was also known ç
as <185>a<219>hakopa or <185>a<219>h<193>ri because he was an enemy ç
of ·a<219>has or hypocrites.
See <MS>°<170>V°RS.
@SPACE = 
@NT = Sat<200>
@N1 = (`the chaste one')
@SPACE1 = 
Sat<200> was a daughter of Dak<218>a Praj<193>pati given in marriage ç
to <185>iva.
Being a paragon of the highest womanly virtues and unable to bear ç
the insults hurled at her husband by her arrogant father Dak<218>a, ç
she burnt herself in a self-generated fire through yoga in the sacrificial ç
hall (of Dak<218>a). She was later reborn as P<193>rvat<200> (the ç
daughter of the mountain king Himav<193>n and queen Men<193>) and ç
married <185>iva after pleasing him with severe austerities.
Because of this act of hers, her name †Sat<200>†became a synonym for ç
p<193>tivratya or chastity and absolute faithfulness to one's husband.
See also <MS>P°RVAT®.<D>
@NT = Sat<200>
@N1 = (practice of self-immolation by a<R>ç
widow on the funeral pyre of her husband)
@SB = Introduction
The practice of widow-burning was not peculiar to the Hindus of India ç
only. It owes its origin, according to European scholars like Schrader ç
(vide his Prehistoric Antiquities of the Aryan Peoples) to the ç
oldest religious views and superstitions of mankind in general. The ç
practice obtained among the ancient Greeks, Germans, Slavs and other ç
races. A. L. Basham in his work The Wonder that was India* (p. 188) ç
says that this custom dates back to the earliest cultures and notes ç
that it existed among the Kings of Ur, the ancient Chinese and some ç
early Indo-European peoples. They used to either burn or bury a man's ç
widow, as also his horses and other cherished possessions with his ç
corpse, in order that he might have all that he loved and needed in ç
the other world.
@SB = Symbolic Act
But in India, even by the time of the <184>gveda, the practice had ç
become outmoded and had been given up. One of its mantras (10.18-8) ç
refers to the practice of the widow lying on the funeral pyre of her ç
husband, before it is lit up, and then coming down. So it existed ç
only as a symbolic ritual.
@SB = Not Compulsory
With the solitary exception of the Vi<218><207>udharma-s<220>tras, ç
no other work including the famous Manusm<216>ti, has ordained it. ç
Even in the Vi<218><207>udharma-s<220>tras, committing Sat<200> ç
is a choice given to the widow and is not compulsory. In the epics ç
a few instances of the queens and other wives of the deceased kings ç
having burned themselves on the funeral pyres of their husbands are ç
mentioned. It was a voluntary act and was not highly extolled. In ç
all probability, this pure voluntary practice existed only among the ç
kings and noblemen and never at the general level of the populace. ç
In fact, religious works have extolled a life of austerity and purity ç
by the widows as of far superior merit than Sahagamana or self-immolation.
@SB = Unfortunate Developments
But it is an unfortunate fact that the practice became, in course ç
of time, more universal and more widely prevalent among all sections ç
of the people, thanks to the superstitions among the ignorant masses ç
and their clever exploitation by economic vested interests. This is ç
borne out by the fact that incidents of Sat<200> were very high in ç
Bengal where the share of women in the properties of joint families ç
was rather high as compared to other parts of India. Consequently, ç
instances are not wanting where unwilling women, even innocent child-widows, ç
have been forcibly burnt alive most inhumanly. It was but natural ç
that large sections of society under the enlightened leadership of ç
people like Raja Rammohan Roy (<MS>A.<|>D.<D> 1772-1833) rebelled against ç
this heinous custom and put a stop to it.
@SB = Condemned by Ancient Writers
It is not that Raja Rammohan Roy was the first person who fought against ç
this abominable custom. Ancient commentators  of  scriptures  like  Medh<193>tithi ç
(circa 10th century) and literary geniuses like B<193><207>a (7th ç
century) have condemned the practice in no uncertain terms. All the ç
teachers of Tantras were vehemently against it.
@SPACE1 = 
@SB = Abominable Practice
@SPACE1 = 
There are no two opinions regarding the stopping of this practice. ç
But, people who are preaching against it vigorously, sometimes issue ç
statements of wholesale condemnation of the practice. As far as the ç
forcible burnings are concerned, no words are strong enough to condemn ç
them. They are first degree murders. Hence the long and strong arm ç
of the law of the land must have its full sway.
@SPACE1 = 
@SB = Not All Sat<200>s Were Forced Ones
@SPACE1 = 
But not all Sat<200>s have been forced ones.  Travellers  like  Jean  Baptiste ç
Tavernier of France, who toured India between <MS>A. D.<D> 1641 and ç
1667 have described graphically how a young widow non- chalantly burnt ç
her finger in a blazing torch as a `test', before she finally committed ç
Sat<200>, of her own free will. None could dissuade her. He also states ç
how the eleven queens of the King of Vellore (now in Tamil Nadu), ç
when confined to a room and locked up to prevent them from committing ç
Sat<200>, were found dead after three hours. There were no signs of ç
hanging or poison or physical injury on their bodies!
The mass Jauhar system (jumping into fire) of the Rajput princesses, ç
to save their honour from the marauding barbaric invaders,  is  now  a  well-documented ç
historical fact.
@SB = Voluntary Sat<200> Admirable
What one has to admire here† whether the practice itself is right ç
or wrong†is the tremendous courage displayed by these noble ladies ç
who cared more for their cherished ideal than for their lives. Honour ç
and chastity were everything for them and life was like straw when ç
compared to these. In this connection it is worthwhile to quote a ç
well-known modern savant, Dr. P.<|>V. Kane, from his monumental work ç
History of Dharma-·<193>stra (Vol. II, P-I. p.<|>636): ``Modern India ç
does not justify the practice of Sat<200>, butit is warped mentality ç
that rebukes modern Indians for expressing admiration and reverence ç
for the cool and unfaltering courage of Indian women in becoming Sat<200>s ç
or performing Jauhar for cherishing their ideals of womanly conduct. ç
If Englishmen can feel pride in their ancestors who grabbed one fourth ç
of the world's surface or if Frenchmen can feel pride in the deeds ç
of their Emperor Napoleon who tried to enslave the whole of Europe ç
and yet are not held up to ridicule or rebuke, there is no reason ç
why poor Indians cannot express admiration for the sacrifices which ç
their women made in the past, though they may condemn the institution ç
itself which demanded such terrible sacrifice and suffering.''
@SB = Origin of ``Sat<200>''
@SPACE1 = 
The word `Sat<200>' comes form the root `sat', the truth. Hence it ç
actually means a woman who is true to her ideals. And Indian tradition ç
has placed chastity and personal purity as the highest ideal of Indian ç
womanhood, even as it is so for men. Any woman who has risen to the ç
heights of this ideal is a Sat<200>. The best known example of this ç
ideal is Sat<200> herself, also known as D<193>k<218><193>ya<207><200>, ç
Lord <185>iva's consort. When Dak<218>a, her father, insulted her ç
and her husband in the sacrificial site before a large gathering, ç
she resolved to give up her body in protest. As per the accounts given ç
in the Bh<193>gavata (4.4) she sat in deep meditation and burnt ç
her body to ashes in yog<193>gni or the fire generated by the yogic ç
meditation!
This story reveals to us two startling facts: Sat<200> gave up her ç
body voluntarily in yoga and did not jump into the sacrificial fire ç
as is often made out in popular legends. And, her husband, <185>iva, ç
had not ceased to exist.
If any woman is capable of giving up her body in yogic meditation, ç
unable to stand the insults to her husband and herself, none should ç
prevent her from doing so! Even if she wants to give up her body in ç
this fashion, on the death of her dear husband, there should be no ç
objection! And she indeed should be honoured as the original Sat<200> ç
herself!
@SB = Goal of Life
But, a more fundamental question is: Why should a widow die at all, ç
just because her husband had died? Our holy scriptures declare that ç
human birth is extremely valuable and should be fully utilised for ç
realising the final goal of life, viz., realisation of the °tman or ç
the Self and consequent stoppage of transmigratory existence.
@SB = Equal Scope
And, as far as this goal of life andthe possibility of achieving ç
it are concerned, man and woman are treated as absolutely equal. In ç
fact the Ved<193>ntic scriptures do not even recognise the man-woman ç
differences as fundamental, but only as incidental to the respective ç
karma of the individual soul, which is a spirit, sans sex.
@SB = Glorious Examples
Really speaking, a widow has much greater opportunity for spiritual ç
progress, if only she can take her life in the right spirit. In fact, ç
the stringent rules imposed on a widow in her personal life approximate ç
to the code of conduct of a sa<221>ny<193>sin or a monk, and should ç
be looked upon from this angle. Apart from <185>r<200> S<193>rad<193> ç
Dev<200> herself, the consort of R<193>mak<216><218><207>a, the many ç
women disciples of the Master, some of whom were child-widows and ç
had been the victims of tragic events of life, have set before us ç
glorious examples of Indian womanhood.
@SB = Middle Ages or `Dark' Ages?
No one denies that during the Middle Ages the Hindu society meted ç
our very cruel treatment to its women. Problems of child-widows as ç
a result of the ridiculous system of child-marriage, absence of education ç
resulting in superstitions, various unjust taboos forcing the widows ç
to slave in the joint families for life, utter economic dependence†all ç
these might have produced a dismal attitude in the minds of women ç
often forcing them to opt for Sat<200> rather than die every moment ç
of life. Pioneering efforts in the field of women's education by persons ç
like Sister Nivedit<193>, (<MS>A.<|>D.<D> 1867-1911) the fiery disciple ç
of the fiery guru Vivek<193>nanda (<MS>A.<|>D.<D> 1863-1902), had certainly ç
brought a glimmer of hope to these hapless women during the last century.
@SB = Conclusion
Now, after independence, when practically every field of life has ç
been thrown open to women and when several women's organisations run ç
by enlightened women are working for their welfare, women in general ç
and destitute widows in particular, have nothing to despair.
If the Hindu society can vigorously propagate the idea that women ç
can do better things in life than dying on the funeral pyres of their ç
dead husbands, the Sat<200> problem will die a natural death.
There  is  a  popular  saying  that marriages are made in heaven. ç
If it is so, then let our widowed sisters and mothers wait for their ç
marriages to be continued or dissolved in heaven by the Power that ç
made them, but live here happily till they go to that heaven!
As for the people who think that the Sat<200> system had `solved' ç
the problem of widows of our country and hence should be continued ç
or revived, it may be suggested that many similar problems can be ç
solved in the ``Sat<200> Way''. For instance, since there can be no ç
headache if there is no head, headaches can be cured once for all ç
by cutting off the heads! One only prays that our society will not ç
become that wise!
@NT = <218>a<219>karmas
@N1 = (`six purificatory exercises [for the body]')
Works on Ha<219>hayoga lay great stress on cleansing and strengthening ç
the physical body so that it becomes fit enough for the practice of ç
R<193>jayoga. For this, they prescribe the <218>a<219>karmas or six ç
purificatory processes.
They are: dhauti (washing); basti (cleansing the lower part of the ç
abdomen); neti (cleaning the nostrils); laukik<200> (movement of stomach-muscles); ç
tr<193><219>aka (gazing without winking); kap<193>labh<193>ti (cleansing ç
the inside of cranium).
See under each title for details.
@NT = satk<193>ryav<193>da
@N1 = (`the theory of the effect really existing [previously in the ç
cause]')
Since a real effect cannot come out of an unreal cause, this theory ç
put forward by the S<193><209>khya philosophy argues that the effect ç
(`k<193>rya') must have pre-existed (`sat') in the cause, in a subtle ç
form before manifestation. This is satk<193>ryav<193>da. This theory ç
is also called <193>rambhav<193>da and pari<207><193>mav<193>da.
See also <MS>ASATK°RYAV°DA.<D>
@NT = satkhy<193>ti
See <MS>KHY°TIS.<D>
@NT = satpratipak<218>a
@N1 = (`inferentially<R>ç
contradicted middle')
The well-known example given for anum<193>na or inference in the Indian ç
systems of logic like the Ny<193>ya Dar·ana runs as follows:
@NID = <|><+>There is fire on the yonder hill;
@NID = <|><+>because there is smoke.
@NID = <|><+>Wherever there is smoke, there is fire.
There are three factors here. They are called pak<218>a (minor term, ç
the hill), s<193>dhya (major term, the fire) and li<209>ga or hetu ç
(middle term, the smoke).
However, an inference can be falla-cious†this is called hetv<193>bh<193>sa†and ç
it is of five types. The satpratipak<218>a is the third in the series. ç
Here, the middle term is contradicted by another statement which is ç
sat or real.
@NID = Suppose the first statement is:
@IN2 = Sound is eternal, because<R>ç
it is audible.
@NID = This is contradicted by a second one thus:
@IN2 = Sound is non-eternal because<R>ç
it is produced, like a pot.
Here, the non-existence of eternality in the first is proved by the ç
second inference (which is a pratipak<218>a or opposition view) which ç
is sat or real.
See <MS>HETV°BH°SA<D> also.
@NT = satra
See<MS> <185>A<177>KARADEVA.<D>
@NT = <185>atrughna
@N1-1 = (`one who kills or destroys the enemy')
<185>atrughna was a son of Sumitr<193>, the second queen of Da·aratha. ç
He and Lak<218>mana were twins. He was very much attached to Bharata, ç
even as Lak<218>ma<207>a was to R<193>ma.
Very little is mentioned about him in the first six books of V<193>lm<200>ki's ç
R<193>m<193>ya<207>a.
He was married to <185>rutak<200>rti, daughter of Ku·adhvaja, younger ç
brother of Janaka.
He was sent to Mathur<193> by R<193>ma to kill the demon-king Lava<207><193>sura ç
who had become a despot and terror to his subjects. He not only killed ç
Lava<207><193>sura but also took over the kingdom as its ruler and ç
ruled it according to the highest principles of dharma.
Since he had not seen R<193>ma for a long time he visited the hermitage ç
of V<193>lm<200>ki and then came to Ayodhy<193>, after dividing his ç
kingdom between his two sons Sub<193>hu and <185>atrugh<193>ti who ç
ruled from Mathur<193> and Vaidi·a respectively.
R<193>ma was extremely happy to meet him.
When R<193>ma decided to go back to his divine abode, <185>atrughna ç
too followed him.
@NT = <218>a<219>sthala
@N1 = (`six spaces')
See <MS><185>AIVISM.<D>
@NT = <186>a<219>sthalasiddh<193>nta
See under <MS><185>AIVISM<D>.
@NT = <218>a<219>-t<193>la
@N1 = (`seven t<193>las')
See <MS>M<188>RTI<185>ILPA<185>°STRA.<D>
@NT = Sattray<193>ga
See <MS>VEDIC SACRIFICES.<D>
@NT = sattva
@N1 = (`existence')
Used in several senses such as purity and strength, this word represents ç
sattva-gu<207>a, the first of the three gu<207>as.
The Ch<193>ndogya Upani<218>ad (7.26.2) has used it in the sense ç
of the mind.
See <MS>GUØA.<D>
@NT = S<193>tvata
@N1 = (`belonging to the Satvat tribe')
S<193>tvata was a king of the Yadu dynasty. He had seven sons: Bhaja, ç
Bhaji, Divya, V<216><218><207>i, Devap<216><218><219>ha, Andhaka and ç
Mah<193>bhoja.
All men born in his dynasty were known as S<193>tvatas.
<185>r<200> K<216><218><207>a was a descendent of V<216><218><207>i.
S<193>tvata is also the name of a Vai<218><207>ava work that preaches ç
devotion to Vi<218><207>u. This is called Bh<193>gavatamata.
@NT = satya
@N1 = (`truth')
@EMERGENCY = Satya or truth has been accorded thepride of place among ç
the virtues recommended to be cultivated by man. The Hindu as well ç
as Jaina and Buddhist works wax eloquently over it. Its fundamental ç
definition is `that which is un- affected by time, place and causation'. ç
This simply means that `satya' stands for God, the Absolute. In fact, ç
several sahasra-n<193>mas (thousand names of God) use this word to ç
denote God. As an extension of this meaning, anything that helps a ç
man's progress towards God, is satya.
In a more practical sense, satya is speaking the truth, consonance ç
of thought and word. One should avoid speaking falsehood, partial ç
truths and even unpleasant truths. Truth should be spoken in a sweet ç
and pleasant way. Unpleasant truths, when they must be spoken, should ç
be presented in a palatable manner.
In the ancient days if a person accused of a crime denied it, he was ç
to prove his innocence by touching a red-hot iron! It was believed ç
that if he was speaking the truth, truth itself would protect him ç
(vide Ch<193>ndogyopani<218>ad 6.16.1,2)
@EMERGENCY = Asatya on the other hand, stands for all that is opposed ç
to satya. It is what is untrue, unreal, evil and crooked.
@EMERGENCY = Speaking asatya has been permitted as an <193>pad-dharma ç
(emergency situation), under extraordinary circumstances when one's ç
life is threatened by evil and unscrupulous persons.
@NT = Satyabh<193>m<193>
Satyabh<193>m<193> was one of the a<218><219>a-mahi<218><200>s or ç
eight queens of K<216><218><207>a. She was the daughter of Satr<193>jit, ç
a chieftain of the Yadu race.
In her previous life she was Gu<207>avat<200>, daughter of a pious ç
br<193>hma<207>a Deva- ·arman. Due to her purity of life, austerities ç
and devotion to Vi<218><207>u, she was reborn as Satyabh<193>m<193> ç
and got K<216><218>na as her husband.
It was for fulfilling her wish, that K<216><218><207>a brought the ç
p<193>rij<193>ta (night jasmine) tree from heaven.
Once she was obliged to accept defeat at the hands of Rukmi<207><200>, ç
the chief queen of K<216><218><207>a, whose devotion proved to be ç
greater than hers.
@NT = S<193>tyaki
S<193>tyaki was the son of Satyaka, a chieftain of the Yadu race. ç
He was also known as Yuyudh<193>na.
Throughout his life he was a devoted friend of K<216><218><207>a and ç
Arjuna. No love was lost between him and Balar<193>ma (K<216><218><207>a's ç
elder brother) who always sided with Duryodhana.
He accompanied K<216><218><207>a on all his major sojourns like attending ç
the R<193>j<193>s<220>ya sacrifice or the final peace mission.
Not only did he advocate war with the Kauravas, he also took active ç
part in it as one of the seven commanders of the P<193><207><195>ava ç
army.
He too perished in the internecine  quarrels of the Y<193>davas at ç
Prabh<193>sa along with others.
@NT = Satyaloka
@N1 = (`world of Truth')
See <MS>BRAHMALOKA.<D>
@NT = Satyan<193>r<193>ya<207>a-vrata
This is an extremely popular vrata (religious rite), almost all over ç
the country, especially among the lower middle class people and women. ç
It can be done on any day, preferably on P<220>r<207>im<193>, Sa<209>kr<193>nti ç
or Ek<193>da·<200> days, the places being a temple, bank of a river, ç
under the va<219>a or a·vattha trees or in one's own house. The quantity ç
of naivedya (food offering) is fixed at <%18>1<P7W1%0><$E1 over 4><P255D> ç
(for e.g., 1.25 kgs). The ingredients of this special naivedya are: ç
plantains, ghee, milk,wheat or rice flour, jaggery or sugar. They ç
are all to be mixed up to prepare the naivedya. Apart from the elaborate ç
worship of the deity, listening to the stories about the greatness ç
of this vrata, keeping vigil the whole night with devotional songs ç
and devotional dances are also recommended.
@NT = Saty<193>rthaprak<193>·a
@N1 = (`[a work] which <R>ç
brings out the truth')
The Saty<193>rthaprak<193>·a is the magnum opus of Sv<193>mi Day<193>nanda ç
Sarasvat<200> (<MS>A.<|>D.<D> 1824-1883), a pioneer in the renaissance ç
of Hinduism during the 19th century. He was the founder of the well-known ç
°rya-sam<193>j. (See <MS>°RYASAM°J<D> and <MS>DAY°NANDA SARASVAT®<D>.)
A powerful work on general Hinduism written in Hind<200> language, ç
it has 14 ull<193>sas or chapters, with a concluding section also, ç
in which he has given his own views on the various principles of Hinduism.
A brief summary of the work may now be given here:
@S10 = First Chapter
Various names of God are mentioned here with relevant quotations from ç
the Vedas.
@S10 = Second Chapter
Along  with  certain  Vedic  rites connected with the birth of a child ç
and some techniques of training and educating it, this chapter discounts ç
the claims of astrologers who cast the horoscope and ridicules the ç
ignorance of people who believe in ghosts and evil spirits.
@S10 = Third Chapter
After emphasising the need for good education, both for boys and for ç
girls, the work explains in detail pr<193><207><193>y<193>ma, upanayana, ç
sandhy<193>, brahmacarya (first stage of life) and methods of study.
Here the author forcefully advocates the study of the Vedas by the ç
·<220>dras and women also.
@S10 = Fourth Chapter
The topics dealt with in this chapter are: eight types of marriage; ç
certain sa<221>sk<193>ras or sacraments like pu<221>savana; the pa<210>camah<193>yaj<210>as ç
or the five daily sacrifices; duties of a g<216>hastha or a householder; ç
characteristics of a good student; criticism of Par<193>·arasm<216>ti.
@S10 = Fifth Chapter
The two <193>·ramas, v<193>naprastha and sa<221>ny<193>sa, are described ç
here.
There is a clear declaration that only br<193>hma<207>as are eligible ç
for sa<221>ny<193>sa.
In this chapter, it is interesting to note, that the Manusm<216>ti ç
has been quoted extensively.
@S10 = Sixth Chapter
The entire chapter deals with political science in detail. The Manusm<216>ti ç
is quoted profusely.
@S10 = Seventh Chapter
The following subjects are dealt with in this section: ®·vara, Brahman ç
or God, his nature (as formless and all-pervading) and his worship ç
through prayer and meditation; denial of the theory that God incarnates; ç
about the nature of the j<200>va or individual soul; j<200>va and ç
Brahman are different though a little similarity exists; Vedas were ç
created by ®·vara or God; Vedic Sa<221>hit<193>s are the real Vedas ç
and supreme.
@S10 = Eighth Chapter
The topic of this chapter is creation. There are three fundamental ç
realities: ®·vara or Param<193>tman; j<200>va or the individual souls; ç
prak<216>ti or nature.
®·vara does the primary creation of the whole world using prak<216>ti ç
as the material. The j<200>va does his own, using the articles available ç
in the world.
Creation is a continuous process.
Karma theory is supported.
Advaita theory of Brahman alone being the material as well as the ç
efficient cause (abhinna-nimitta-up<193>d<193>na-k<193>ra<207>a) is ç
rejected.
@S10 = Ninth Chapter
The subjects dealt with in this chapter are: characteristics of knowledge ç
and ignorance; rejection of the various views of the advaitins; mukti ç
or liberation of the j<200>va and his 24 special powers.
The mukta or the liberated soul returns to this world after the end ç
of par<193>ntak<193>la (duration of Brahma's life) (3x 1013 years). ç
In mukti he enjoys the bliss of Brahman, being established in Brahman ç
who is infinite or all-pervading, the j<200>va himself being a<207>u ç
or atomic in size.
@S10 = Tenth Chapter
This section deals with several topics normally dealt with in the ç
dharma·<193>stra works such as sad<193>c<193>ra (good conduct), service ç
to parents and elders, purity of food, unity of all the var<207>as, ç
need to avoid flesh-eating, eschewing intoxicating drinks and mutual ç
love and respect among all var<207>as.
@S10 = Eleventh Chapter
This is the biggest section dealing with several, miscellaneous, topics. ç
They are, briefly, as follows:
Greatness of the knowledge and wisdom in India; destruction of the ç
true spirit of the br<193>hma<207>as leads to total destruction; true ç
meaning of animal sacrifices such as A·vamedha, Gomedha or Puru<218>a-medha; ç
criticism of ·r<193>ddha conception; criticism of the various stories ç
of the pur<193><207>as; true nature of tapas or austerity; m<220>rtip<220>j<193> ç
shown as defective, including the worship of the various deities; ç
pilgrimages decried; pur<193><207>as are not by Vy<193>sa; Bh<193>gavata ç
considered as Bopadeva's work and hence not authoritative; ·<220>dras ç
and women can study the Vedas; no belief in astrology; d<193>nas ç
or making gifts accepted; criticism of many other schools.
@S10 = Twelfth Chapter
This entire chapter is devoted to a severe criticism of the schools ç
of C<193>rv<193>ka (materialism), Jaina and Bauddha which are against ç
the Vedic religion.
@S10 = Thirteenth Chapter
It deals with Judaism and brushes it aside as a religion sanctioning ç
violence. It also criticises Christianity.
@SPACE = 
@S10 = Fourteenth Chapter
@SPACE1 = 
This chapter is devoted to denunciation of Islam and the Kor<193>n. ç
Several suras are quoted and critically analysed.
@SPACE = 
@SPACE = 
@SB8.5 = The Philosophy of Day<193>nanda Sarasvat<200> as Revealed ç
in this Treatise
@SPACE = 
Since the author has been devastatingly critical of most of the schools ç
of Hinduism it is necessary to know what exactly his own philosophy ç
is. This he has done in the last section titled Svamantavya-Amantavya-Prak<193>·a<199> ç
(revealing what is acceptable as also not acceptable to himself).
The following is a brief summary of the concepts:
@SPACE = 
@S10 = ®·vara or God
@SPACE1 = 
Known as Brahm<193>, Param<193>tma and a host of other names, He is ç
Sat-Cit-°nanda (Truth, Consciousness and Bliss). He is omniscient, ç
omnipresent and all-powerful. He is the creator, endowed with all ç
the blessed qualities.
@SPACE = 
@S10N = Pram<193><207>as (Means of Knowledge)
@SPACE1 = 
The Sa<221>hita portions of the four Vedas are the basic pram<193><207>as.
The other parts of the Vedas like the Br<193>hma<207>as, Ved<193><209>gas ç
and the Upavedas are accepted in so far as they do not conflict with ç
the Sa<221>hit<193>s.
In <|>addition, <|>eight<|> pram<193><207>as <|>are accepted. They are:<|> ç
pratyak<218>a (direct perception); anum<193>na (inference); ·abda ç
(verbal testimony, the Vedas); upam<193>na (comparison); arth<193>patti ç
(postulation); anupalabdhi (non-perception); sambhava (possibility); ç
aitihya (past history).
@SPACE = 
@S10N = Dharma (Righteousness)
@SPACE1 = 
It is the code of conduct given by the Vedas and not against the spirit ç
of the Vedas.
@SPACE = 
@S10 = J<200>va
@SPACE1 = 
The j<200>va or the individual soul is nitya (uncreated and eternal) ç
and a<207>u (atomic in size). He has several qualities like icch<193> ç
(desire), dve<218>a (dislike), prayatna (effort), j<210><193>na (knowledge) ç
and so on.
There are many j<200>vas. They are all different from ®·vara, though ç
similar in nature. ®·vara being omnipresent, pervades them.
@SPACE = 
@S10N = Prak<216>ti (Nature)
@SPACE1 = 
The world is created by ®·vara using this prak<216>ti as the material ç
cause.
@SPACE = 
@S10N = S<216><218><219>i (Creation)
@SPACE1 = 
Creation is done by ®·vara to help the j<200>vas in their path of ç
further evolution, according to their karmas.
@SPACE = 
@S10N = Bandha (Bondage)
@SPACE1 = 
The j<200>va falls into bondage due to avidy<193> or ignorance of ç
his real nature.
@SPACE = 
@S10N = Mukti (Liberation)
@SPACE1 = 
Mukti is liberation from all sorrows and sufferings. The liberated ç
soul will get full freedom to move about in the whole creation as ç
also in ®·vara who is all- pervading. However, the liberated soul ç
has to come back at the end of a par<193>ntak<193>la, the life duration ç
of Brahm<193>.
®·varop<193>sana (worship of God) through yoga, vidy<193> (knowledge), ç
practice of dharma and company of the spiritually evolved souls, is ç
the means.
@SPACE = 
@S10 = Var<207><193>·ramadharmas
They are accepted if based on gu<207>a (qualities of the mind) and ç
karma (actions in accordance with them) and not based on birth.
@SPACE = 
@S10N = Devas and Asuras (Gods and Demons)
Vidv<193><221>sas (men of wisdom) are the devas (gods) and the avidv<193><221>sas ç
(men of ignorance) are the asuras. Sinners are the r<193>k<218>asas ç
and renegades, the pi·<193>cis.
@SPACE = 
@S10N = Devap<220>j<193> (Worship of God)
Honouring the men of wisdom, one's own parents, the teacher, a just ç
king, guests and virtuous persons†this is real devap<220>j<193>.
@SPACE = 
@S10N = <185>ik<218>a<207>a (Education)
The training that helps one to eliminate the impurities of the mind ç
and develop great virtues is ·ik<218>a<207>a in the true sense.
@SPACE = 
@S10 = Pur<193><207>as
It is the Br<193>hma<207>as of the Vedas that are accepted as the ç
pur<193><207>as and not the present eighteen pur<193><207>as.
@SPACE = 
@S10N = T<200>rthas (Places of Pilgrimage)
It is the cultivation of virtues like truth, knowledge and the company ç
of the spiritually great souls that is true `t<200>rtha' and not the ç
physical places of pilgrimage.
@S10N = Puru<218>aprayatna (Self-effort)
@SPACE1 = 
Even pr<193>rabdha karma can be overcome by pur<218>aprayatna.
@SPACE = 
@S10N = Sa<221>sk<193>ra (Sacraments)
@SPACE1 = 
All  the  sixteen  sa<221>sk<193>ras  are accepted. However, nothing ç
need be done after cremation.
@SPACE = 
@S10N = Yaj<210>as (Sacrifices)
@SPACE1 = 
Simple Vedic rituals are accepted but not the complicated system of ç
sacrifices.
@SPACE = 
@S10N = °ryas (Cultured People)
@SPACE1 = 
The word does not indicate any race. It refers to the cultured and ç
refined people as against the Dasyus, the evil ones.
@SPACE = 
@S10N = Svarga and Naraka (Heaven and Hell)
@SPACE1 = 
The experience of joy and happiness here is svarga and the opposite ç
is naraka.
@SPACE = 
@S10N = Karma and Punarjanma (Karma<|>and<|>Rebirth)
The usual theories are accepted.
@SPACE = 
@S10N = Niyoga (Levirate)
@SPACE1 = 
The ancient system of niyoga is accepted within the framework of the ç
rules prescribed.
Up<193>san<193> (worship and meditation), pr<193>rthan<193> (prayer) ç
and yog<193>bhy<193>sa are also accepted.
See also <MS>°RYASAM°J<D> and <MS>DAY°NANDA<D> <MS>SARASVAT®.
@SPACE = 
@NT = Satyav<193>n
@N1 = (`the truthful one')
See <MS>S°VITR®.<D>
@NT = Satyavat<200>
She was the daughter of a king Uparicara Vasu of Cedi (a kingdom) ç
but was brought up by a chieftain of fishermen.
The sage Par<193>·ara was once infatuated with her beauty and K<216><218><207>a-dvaip<193>yana ç
Vy<193>sa was born of their union.
She was later married to the king <185>antanu from whom she got two ç
sons: Citr<193><209>gada and Vicitrav<200>rya. Both these princes ç
however died young.
Then, since Bh<200><218>ma (<185>antanu's first son) was not willing ç
to beget children in the widows of Vicitrav<200>rya by niyoga (See ç
<MS>NIYOGA.<D>) Satyavati ordered Vy<193>sa to do so.
Later on, she is said to have retired into a forest along with her ç
two daughters- in-law, Ambik<193> and Amb<193>lik<193>.
Vi·v<193>mitra's sister and the mother of the sage Jamadagni was also ç
a Satyavat<200>. The queen of the king Tri·a<209>ku of the solar race ç
was another Satyavat<200>.
@SPACE = 
@NT = ·auca
@N1 = (`cleanliness,' `purity')
@SPACE = 
The Yogas<220>tras of Pata<210>jali (200 <MS>B.C.<D>) lists ·auca ç
or purity as one of the five disciplines under niyama, the second ç
of the eight steps of yoga.
It is of two kinds: b<193>hya or external; <193>ntara or internal. ç
The former is achieved by cleansing the body and the latter, by conquering ç
the six-enemies like lust and greed.
It is interesting to note that the Manusm<216>ti (5.106) considers ç
purity in financial dealings as the real or the best purity.
The dharma·<193>stras and the various sm<216>tis give a detailed account ç
of <193>hnika or the daily routine of a dvija (a member of the first ç
three castes). <185>auca or bodily purity is an important part of ç
the same.
@NT = <185>aunaka
<185>aunaka is the name of a sage foundin our ancient religious literature ç
in many places (vide <185>atapatha Br<193>hma<207>a 13.5.3.5; B<216>had<193>ra<207>yaka ç
Upani<218>ad 2.5.20; Kau<218><200>taki Br<193>hma<207>a 4.7; Ch<193>ndogya ç
Upani<218>ad 1.9.3; Mu<207><195>aka Upani<218>ad 1.1.3).
His original name was G<216>tsamada and came to be known as <185>aunaka ç
since he was the son of the sage <185>unaka. He was considered a reincarnation ç
of Indra, the king of gods.
He was the author of several works most of which were centred round ç
the <184>gveda. They are known as Anukrama<207><200>s (indices). ç
(See <MS>ANUKRAMAØ®.<D>)
His magnum opus is the B<216>haddevat<193> dealing with the Vedic ç
deities. (See <MS>B<184>HADDEVAT°<D> for details.)
°·val<193>yana was his chief disciple.
He was a kulapati (supreme head of a gururkula or a residential forest ç
university) with ten thousand Vedic students under his care.
According to the pur<193><207>as there was another <185>aunaka†also ç
known as Indrota †who made the king Janamejaya (son of Puru, of the ç
lunar race) perform the A·vamedha sacrifice to get rid of brahmahaty<193>do<218>a ç
(the sin of killing a br<193>hma<207>a).
See also <MS>°<185>VAL°YANA.
@NT = <185>aunaka-sm<216>ti
<185>aunaka as an author of a sm<216>ti has been mentioned even by ç
the Manusm<216>ti (3.16). His work has not been traced till now.
A work called Pra<207>avakalpa with a commentary of Hem<193>dri ç
(13th century <MS>A.D.<D>) is known to have existed.
Numerous works are attributed to <185>aunaka. However, it is difficult ç
to say whether they are by the same person. Some of these are: Arkaviv<193>hapaddhati; ç
Ekada<207><195>isa<221>ny<193>savidhi; Adbhutotpatti-·<193>nti; ç
J<200>vacchr<193>ddhaprayoga and Prayoga-p<193>rij<193>ta.
See also <MS><185>AUNAKA.
@SPACE = 
@SPACE = 
@NT = Saundaryalahar<200>
@N1 = (`Wave of beauty')
@SPACE = 
Apart from writing learned bh<193><218>yas or commentaries on recondite ç
scriptures like the Upani<218>ads and philosophical works like the ç
Brahmas<220>tras, <185>a<209>kara (<MS>A.D.<D> 788-820) also composed ç
a number of beautiful stotras or hymns on the various deities of the ç
Hindu pantheon. The Saundaryalahar<200> is one of his most famous ç
hymns.
According to orthodox traditions, <185>a<209>kara got the first 41 ç
verses from Kail<193>sa, the abode of <185>iva and composed another ç
59, to make the total of 100.
As per another version, <185>a<209>kara as a child was breastfed by ç
the Divine Mother (Tripurasundar<200>) herself, because of which he ç
gained great spiritual power as well as the power to compose poetry ç
(vide verse 74).
Though the first part comprising 41 verses is more commonly known ç
as the °nandalahar<200> and only the second part† the rest, 59 verses†as ç
the Saundarya- lahar<200>, the whole hymn is now generally called ç
by the latter name.
The speciality of this composition is that it reflects equally the ç
three important aspects of Hinduism, viz., Ved<193>nta, devotion to ç
the deity through the hymn, and the esoteric science of the mantras ç
and yantras (mystic diagrams).
A brief account of the first part is as follows:
@Z_TBL_BEG = COLUMNS(2), DIMENSION(IN), COLWIDTHS(1.0000,E1), BELOW(.0417), ç
VGUTTER(.0424), KEEP(OFF)
@Z_TBL_BODY = SB8.5, SB8.5
Verses, Subject
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT
1 and 2, The Dev<200> is the creatrix.
3 to 8; 22;<R>ç
27; 30, Various traditions of <R>ç
meditation on her.
31 to 33, Description of the <185>r<200>cakra.
9; 10; 14; 21, Meditation on the <R>ç
Ku<207><195>alin<200>.
12; 24 to 26;<R>ç
28; 29, Greatness of <185>r<200>vidy<193>.
13; 15 to 20, On cupidity.
23; 34, Meditation on the unified form of <185>iva and <185>akti.
35, Evolution of the world.
36 to 41, Meditation on the deity in the six cakras.
@Z_TBL_END = 
The second part (verses 42 to 100) describes the physical form and ç
beauty of the Dev<200> in great detail.
Experts of the tradition of <185>r<200>vidy<193> (science of worship ç
and meditation on the Divine Mother) have prescribed detailed procedures ç
for worshipping the Dev<200> through different yantras along with ç
the repetition of the respective verses (a thousand times each), to ç
secure various results. These have to be learnt from a qualified guru.
This hymn has 36 commentaries out of which Lak<218>m<200>dhar<193> ç
of Lak<218>m<200>dhara-de·ika, Saubh<193>gyavardhin<200> of Kaivaly<193>-·rama ç
and Aru<207><193>modin<200> of K<193>me·vara- s<220>rin are considered ç
more important.
