@NID = pralaya (or withdrawal of the created world) and `sleeps' in ç
Him till the next cycle of creation, <185>ivali<209>ga is the symbol ç
for that Supreme God.
Again, since God (the Supreme, as Brahman) is nir<193>k<193>ra and ç
nirgu<207>a (without any particular form or specific qualities) a ç
uniformly rounded surface like the <185>ivali<209>ga can be the best ç
visible representation of that God.
Whether the <185>ivali<209>ga is the final product of the y<220>pastambha ç
(Vedic sacrificial post) as the y<193>ga·<193>l<193> (Vedic sacri-ficial ç
shed) evolved gradually into the Hindu temple, or is a Hindu replica ç
of the Buddhist st<220>pa, there is no clinching evidence to prove ç
it. However, it is an undeniable fact that it is an extremely ancient ç
symbol.
Is the <185>ivali<209>ga a phallus emblem? The icon of Para·ur<193>me·vara ç
at Gu<195>i- mallam (in the Chittoor district of Andhra Pradesh) being ç
an exact replica of the phallus, gives us this impression. The word ç
li<209>ga (indicating the generative organ of man) seems to confirm ç
it. However there are many <185>ivali<209>g<193>s†especially of the ç
svayambh<220> or udbhavam<220>rti (self-manifested) type†which do ç
not at all resemble the phallus. <185>iva for instance, is said to ç
have manifested himself as a great altar of gold from which sprang ç
forth a blazing fire (Mah<193>bh<193>rata, Sauptikaparva 17.13, ç
14), before A·vatth<193>ma.
Even supposing it does, one may surmise that certain non-Vedic cults ç
wherein  phallic  worship  might  have existed†as in many ancient ç
civilizations of the world†were absorbed into the Vedic culture, and ç
the same elevated to represent the father-mother principle at the ç
cosmic level.
It is interesting to note that the li<209>gas have been described ç
as emblems of the Dev<200>, Ga<207>apati and Narasi<221>ha also and ç
worshipped as such. The sculptured images of <185>iva and P<193>rvat<200> ç
worshipping a li<209>ga, in the Kail<193>san<193>tha temple of Ellora ç
(in the Aurangabad district of Maharashtra) adds some mystery, leading ç
to the supposition that the li<209>ga may be a very ancient object ç
of reverence, not necessarily considered an emblem of <185>iva.
As regards the origin of the <185>ivali<209>ga, the Li<209>gapur<193><207>a ç
(chapters 17 to 20) states that when Vi<218><207>u and Brahm<193> ç
were puffed up with arrogant pride about their powers, ignoring <185>iva, ç
he appeared before them as a pillar of fire of infinite length and ç
challenged them to find out the extremities. They failed to do so ç
and had to accept his superiority. This pillar of fire came to be ç
known as li<209>ga because all creatures merge in it at the time ç
of dissolution (l<200>yate asmin; laya<221> gacchanti).
@SPACE1 = 
Li<209>gas are broadly divided into two classes: ak<216>trima (natural) ç
and k<216>trima (man-made).
The former include the svayambh<220> li<209>gas (naturally emerging ç
out of the earth) and the b<193><207>ali<209>as, made of quartzi-ferous ç
substances and naturally available in certain rivers, mainly the Narmad<193> ç
(in Madhyapradesh). These b<193><207>ali<209>gas are of various sizes, ç
shapes and colour. They areconsidered holy always, not needing the ç
rites of consecration or invocation and so on.
Another way of classifying the li<209>gas is as cala (movable) and ç
acala (immovable). The former are the ones that can be kept in one's ç
home and worshipped. They may also be carried on the body as the V<200>ra·aivas ç
(or li<209>g<193>yats) do. They do not normally need the customary ç
installation rites, or a permanent abode.
Such cala-li<209>gas may be made of several materials such as metals, ç
clay, precious stones or even wood. The metals recommended are gold, ç
silver, copper and bell-metal. Precious stones that may be used are ç
rubies, pearls, corals, topaz, emerald and even diamond.
Li<209>gas made of different materials are recommended for worship ç
to fulfil different kinds of desires. For instance, the worship of ç
a pearl-li<209>ga can result in the elimination of sins. That of topaz ç
can give prosperity.
As for the li<209>gas made of wood, the following trees are considered ç
suitable: red-sandalwood, babul, pine, bilva and a few others.
Coming to the acala or the immovable li<209>gas, they are the ones ç
made of stone and fixed in the sanctums of the temples for worship.
@SPACE1 = 
These li<210>gas are in two pieces: the pedestal (called p<200><219>ha ç
or yoni) and the li<209>ga proper. This li<209>ga is divided into ç
three parts: the lowest part is square and is called `Brahmabh<193>ga'. ç
The middle part is octagonal, represents Vi<218><207>u and hence called ç
`Vi<218><207>ubh<193>ga'. The topmost part is cylindrical and is called ç
`Rudrabh<193>ga'. It is this part that is above the ground level and ç
is worshipped, the other two being below. The Brahmabh<193>ga is buried ç
in the ground whereas the Vi<218><207>ubh<193>ga is encased inside ç
the pedestal.
The topmost part known as the p<220>j<193>bh<193>ga has certain lines ç
called the brahmas<220>tra, without which the li<209>ga is considered ç
unfit for worship.
Sometimes the face of <185>iva is carved on the p<220>j<193>bh<193>ga. ç
Such a li<209>ga called `®·varali<209>ga'. If the whole figure is ç
carved, it becomes known as `Rudrali<209>ga'.
There are li<209>gas which have the cylindrical part (the p<220>j<193>bh<193>ga) ç
treated with the design of fluted facets. These are called `dh<193>r<193>li<209>gas'. ç
The fluted facets may vary from 5 up to 100.
If the image of <185>iva is carved on the middle portion of the li<209>ga, ç
it is called `Li<209>godbhavam<220>rti'.
See also <MS><185>IVA<D>.
@SPACE = 
@NT = <185>iv<193>nanda, Sv<193>mi
@N1 = (<MS>A.<|>D.<D> 1887-1963)
@SPACE = 
A well-known saintly figure of modern India,  Sv<193>mi  <185>iv<193>nanda†known  as ç
Kuppusv<193>mi in his premonastic days†was born at Pattama<195>ai ç
in Tamil Nadu in <MS>A.D.<D> 1887. His parents were Ve<209>gu Ayyar ç
and P<193>rvat<200> Amm<193><202>.
After getting the medical degree, he worked as a doctor in the rubber ç
plantations of Malaya for ten years, earning a good name.
His deeply religious bent of mind made him return to India seeking ç
spiritual enlightenment.   He   took   Sa<221>ny<193>sa (monastic ç
vows) in <MS>A.<|>D.<D> 1924 from Sv<193>mi Vi·v<193>nanda Sarasvat<200> ç
of Hrishikesh (or Rishikesh) and was named Sv<193>mi <185>iv<193>nanda ç
Sarasvat<200>.
After a hectic tour of India he returned to Hrishikesh and settled ç
down there itself, establishing a monastery under the name The Divine ç
Life Society. Being an expert in Yoga and °yurveda, he started allied ç
institutions to teach them also.
The Divine Life Society has branches all over India and outside also.
He was a prolific writer on Ved<193>nta and other subjects connected ç
with religion and philosophy.
He has left numerous disciples who are carrying on his work even now.
@NT = <185>iv<193>nubhava-ma<207><219>apa
@N1 = (`religious house of experience [of God] as <185>iva')
See <MS>BASAVE<185>VARA.<D>
@NT = <185>ivapur<193><207>a
The pur<193><207>as are encyclopaedic in nature. They practically ç
deal with all aspects of Hindu religion, philosophy and culture.
They are generally divided into two groups: the Mah<193>pur<193><207>as ç
and the Upa-pur<193><207>as, Though the former contain eighteen pur<193><207>as ç
and the latter is also said to have eighteen works, the actual number ç
as discovered now is much more.
The <185>ivapur<193><207>a†also called <185>iva-mah<193>pur<193><207>a ç
and <185>aivapur<193><207>a†is sometimes listed under the first ç
group (in place of V<193>yupur<193><207>a) and sometimes under the ç
second group .
The original pur<193><207>a is said to have had one lakh verses spread ç
over twelve sa<221>hit<193>s or books. The sage Vy<193>sa condensed ç
it to 24,000 verses in seven sa<221>hit<193>s. They are: 1. Vidye·varasa<221>hit<193>; ç
2. Rudrasa<221>hit<193>; 3. <185>atarudrasa<221>hit<193>; 4.Ko<219>irudrasa<221>hit<193>;  5. ç
Um<193>sa<221>hit<193>; 6.Kail<193>sasa<221>hit<193>; 7. V<193>yav<200>yasa<221>hit<193>.
A very brief synopsis of the contents of this voluminous work may ç
now be attempted here:
@SPACE = 
@SB = 1.	Vidye·varasa<221>hit<193>
@SPACE = 
It deals mainly with the ritualistic worship of <185>iva. The topics ç
touched uponare: establishing the <185>ivali<209>ga and worshipping ç
it; pilgrimage to sacred places of <185>iva; exposition of the greatness ç
of the mantra O<221> nama·-·iv<193>ya; on the holiness of rudr<193>k<218>a ç
beads (Elaeocarpus ganitrus) and bhasma (sacred ash).
@SPACE = 
@SB = 2.	Rudrasa<221>hit<193>
@SPACE = 
This is a very big sa<221>hit<193> and is divided into five kha<207><195>as ç
or sections. They are: S<216><218><219>ikha<207><195>a; Sat<200>kha<207><195>a; ç
P<193>rvat<200>-kha<207><195>a; Kum<193>rakha<207><195>a; Yuddhakha<207><195>a.
The S<216><218><219>ikha<207><195>a describes not only the creation ç
of the world but also the methods of worshipping <185>iva.
The Sat<200>kha<207><195>a describes in detail how Dak<218>ayaj<210>a ç
(sacrifice performed by Dak<218>a) was destroyed by V<200>rabhadra, ç
a fierce god created by <185>iva, since Sat<200> (<185>iva's wife) ç
being insulted by Dak<218>a, had immolated herself in the fire of ç
yoga generated in her own body.
Sat<200> is reborn as P<193>rvat<200>, the daughter of Himav<193>n ç
and Men<193>. After performing severe austerities she pleases <185>iva ç
and marries him. This is the gist of the P<193>rvat<200>kha<207><195>a.
The  Kum<193>rakha<207><195>a,  the  next, describes the birth of ç
Kum<193>ra†also knownby other names such as Skanda, K<193>rttikeya, ç
<186>a<207>mukha and Subrahma<207>ya †and his exploits, especially ç
the killing of the demon T<193>rak<193>sura. The story of Ga<207>apati ç
also appears at the end.
The last in this sa<221>hit<193> is the Yuddhakha<207><195>a. Apart ç
from the well-known episode of Tripuradahana†the burning of the three ç
cities of the demons by <185>iva†it deals with the several yuddhas ç
(wars and battles) between <185>iva, Vi<218><207>u and the gods on ç
one side and the asuras (demons) T<193>raka, Jalandhara, Dambha and ç
<185>a<209>khac<220><195>a on the other.
@SB = 3.	<185>atarudrasa<221>hit<193>
This book describes the hundred avat<193>ras or manifestations of ç
<185>iva. Hence the name <185>atarudrasa<221>hit<193>.
Unlike the avat<193>ras of Vi<218><207>u, <185>iva manifests himself ç
directly wherever and whenever necessary and disappears after the ç
task is done.
The avataras dealt with here include the following: the five forms ç
like Sadyoj<193>ta and V<193>madeva; the A<218><219>am<220>rtis (eight ç
forms) such as <185>arva, Bhava and Rudra; other forms like K<193>labhairava, ç
<185>arabha, Yaj<210>e·vara, Mah<193>k<193>la and Ek<193>da·a or eleven ç
Rudras like Kap<193>l<200>, <185>ambhu and Vilohita; V<216><218>abha; ç
Avadh<220>te·vara and Kir<193>ta.
@SB = 4.	Ko<219>irudrasa<221>hit<193>
This book deals with the twelve famous <185>ivali<209>gas known as ç
Dv<193>da·a-Jyotirli<209>gas spread out in places of pilgrimage like ç
K<193>·<200>, Soman<193>tha, Ked<193>ra and R<193>me·vara. It also ç
contains a long hymn on <185>iva known as the <185>ivasahasran<193>ma ç
(Chapter 35, verses 2-131).
There is also a detailed descriptionof how to perform the worship ç
of <185>iva onthe famous Mah<193>·ivar<193>tri day (Chapter 38).
@SB = 5.	Um<193>sa<221>hit<193>
The subjects dealt with in this section are as follows: a description ç
of various sins and hells; d<193>nas or gifts; some geographical descriptions ç
like those of Jamb<220>dv<200>pa and Bh<193>ratavar<218>a (India); ç
embryology; on death; stories of S<220>rya, Manu and a few kings of ç
the Ik<218>v<193>ku race; ·r<193>ddha (obsequial rites); story of ç
the Dev<200> in brief (same as in the Dev<200>-m<193>h<193>tmya).
@SB = 6.	Kail<193>sasa<221>hit<193>
This section gives a detailed description of pra<207>ava (O<209>k<193>ra), ç
the procedure of taking sa<221>ny<193>sa, performance of p<220>j<193> ç
(ritualistic worship) of <185>iva, explanations of the Mah<193>v<193>kyas ç
(See <MS>MAH°V°KYAS.<D>) and other statements of the Upani<218>ads ç
as also the after-death ceremonies for a sa<221>ny<193>sin who dies.
@SB = 7.	V<193>yav<200>yasa<221>hit<193>
This is divided into two parts, the p<220>rvabh<193>ga and the uttarabh<193>ga.
Since the deity V<193>yu is an important teacher here, this section ç
gets his name.
The  p<220>rvabh<193>ga  deals  with  the following topics: <185>iva ç
as the best of gods; creation of the world by <185>iva; destruction ç
of Dak<218>a's sacrifice; some details regarding <185>aivadharma; ç
story of the sage Upamanyu.
The topics of the uttarabh<193>ga are: the whole world is a form of ç
<185>iva; various avat<193>ras of <185>iva as a teacher of Yoga (such ç
as <185>veta, Sut<193>ra, Gautama, Soma-·arma and Lakul<200>·vara); ç
importance of the mantra Nama·-·iv<193>ya; details of <185>ivad<200>k<218><193> ç
(initiation); daily duties; p<220>j<193> of <185>ivali<209>ga; details ç
of homa; on dhy<193>nayoga.
It is thus seen that this pur<193><207>a is a comprehensive work dealing ç
with manyaspects of religion and philosophy connected with <185>iva.
@NT = <185>ivar<193>tri
See <MS>MAH°<185>IVAR°TRIVRATA.<D>
@NT = <185>iv<193>rkama<207>id<200>pik<193>
See <MS>APPAYA D®K<186>ITA.<D>
@NT = <185>ivas<220>tras
This is one of the basic works on K<193>·m<200>r <185>aivism.
Taught by <185>iva himself to Vasugupta (9th century <MS>A.<|>D.<D>) ç
it has 77 s<220>tras in three sections: <185><193>mbhavop<193>ya, ç
<185><193>ktop<193>ya and °<207>avop<193>ya.
The first section deals with the methods which utilise consciousness ç
itself and are applicable to the highest grades of disciples.
The second section deals with the method of utilising <185>akti or ç
divine energy through n<193>da or vibration, to lead the qualified ç
disciple out of the world of manifestation into the world of equal ç
Reality.
The third section deals with the method of unfoldment of consciousness. ç
It is similar to the one described in the Yogas<220>tras of Pata<210>jali ç
(200 <MS>B.<|>C.<D>).
See also <MS><185>AIVISM.<D>
@NT = Skambha
The Atharvaveda Sa<221>hit<193> (10.7) uses this word to indicate ç
the Highest Being beyond even Brahm<193>. Literally it means One who ç
is the support and basis of the whole universe.
See also <MS>ATHARVAVEDA.
@NT = Skanda
See <MS>SUBRAHMAØYA.
@NT = Sk<193>ndapur<193><207>a
It is one of the eighteen Mah<193>pur<193><207>as and the biggest ç
of them all. It is available in two forms, the first having seven ç
kha<207><195>as and the second divided into six sa<221>hit<193>s. ç
The former has been fully available in print whereas only the first ç
three of the latter are available.
The number of ·lokas in the various editions varies from 81,000 up ç
to 100,000.
The printed edition of the former contains 81,000 verses spread over ç
1671 chapters.
Since it is a very voluminous work, only a brief summary can be attempted ç
here:
@SB = 1.	M<193>he·varakha<207><195>a
Introduction; greatness of Skanda; story of Dak<218>ayaj<210>a and ç
its destruction; fruits of worshipping the <185>ivali<209>ga; story ç
of Devendra; Samudramathana (churning of milky ocean to get am<216>ta ç
or nectar); story of P<193>rvat<200> and her marriage to <185>iva; ç
birth of Kum<193>ra (Skanda or <186>a<207>mukha or K<193>rttikeya ç
or Subrahma<207>ya; Kum<193>ra's fighting with T<193>rak<193>sura ç
and killing him; greatness of V<193>sudeva; story of the P<193><207><195>avas; ç
descriptions of several places of pilgrimage.
@SB = 2.	Vai<218><207>avakha<207><195>a
Story of Var<193>h<193>vat<193>ra (Boar-incarnation) rescuing Bh<220>dev<200> ç
or Mother Earth; story of Kamal<193> and <185>r<200>niv<193>sa or ç
Ve<209>ka<219>e·a; legends of Bharadv<193>ja and M<193>rka<207><195>eya; ç
greatness (eulogy) of Puru<218>ottama of Pur<200>; Ambar<200><218>a's ç
episode; other episodes such as those of Indra-dyumna, Jaimini, N<193>rada, ç
and N<200>laka<207><219>ha; description of Narasi<221>ha; passage ç
to Brahmaloka; details concerning the rathay<193>tra of Jagann<193>tha ç
of Pur<200>; story of Dak<218>i<207><193>m<220>rti; Da·avat<193>ras; ç
greatness of Badar<200> (place of pilgrimage); about some rituals ç
and the method of observing ek<193>da·<200>; importance of Bh<193>gavata; ç
sacredness of the months K<193>rttika and M<193>gha(October-November ç
and January-February).
@SB = 3.	Brahmakha<207><195>a
This kha<207><195>a deals mainly with thefollowing places of pilgrimage: ç
Setu(Dhanu<218>ko<219>i); Cakrat<200>rtha (near R<193>me·vara); Brahmaku<207><195>a ç
(near Gay<193>); R<193>mat<200>rtha (near Gay<193>); Lak<218>m<200>t<200>rtha ç
(on the banks of God<193>var<200> river); <185>a<209>khat<200>rtha ç
(in Kururk<218>etra).
Greatness of R<193>man<193>tha <185>iva of R<193>me·varam; philosophical ç
principles; method of going on a pilgrimage; on the four var<207>as ç
and <193>·ramas; on temples; dharma as described in the sm<216>tis; ç
eulogy of d<193>na (gifts); duties of a vai<218><207>ava.
Greatness of <185>iva and his pa<210>c<193>k<218>ar<200> mantra (nama·-·iv<193>ya); ç
sacredness of Gokar<207>a (place of pilgrimage dedicated to <185>iva) ç
and the <185>ivar<193>tri festival; on the rudr<193>k<218>i beads.
@SB = 4.	K<193>·<200>kha<207><195>a
Stories of pativrat<193>s (wives devotedto their husbands); the Saptar<218>is ç
(the Seven Great Sages); story of Dhruva; description of Tapoloka; ç
eulogy of V<193>r<193><207>as<200>; story of the deliverance of a ç
devil.
@SB = 5.	Avant<200>kha<207><195>a
Story of the Mah<193>k<193>la forest; a beautiful hymn of <185>iva; ç
the vratas (reli-gious observances) of N<193>gapa<210>cam<200> and ç
Gaur<200>; description of some more pilgrim centres; story of the ç
king Dundhum<193>ra.
@SB = 6.	N<193>garakha<207><195>a
Manifestation of <185>iva as the <185>iva-li<209>ga; story of the ç
king Hari·candra; Vi·v<193>mitra's extraordinary feats including sending ç
the king Tri·a<209>ku to heaven; greatness of H<193><219>ake·vara ç
(on the bank of the God<193>var<200>); other centres like Vi<218><207>u-p<193>da ç
(Gay<193>), Gokar<207>a, V<193>r<193><207>as<200>, Dv<193>rak<193>, ç
Avant<200>  and  V<216>nd<193>ban;  description  of sacred  rivers  Ga<209>g<193>,  Narmad<193>  and ç
Sarasvat<200>.
@SB = 7.	Prabh<193>sakha<207><195>a
Several legends connected with some ancient personalities like Some·a, ç
Vi·ve·a, Siddhe·vara, Narake·vara, Sa<221>varte·a and Nidh<200>·vara.
See also <MS>PUR°ØAS.<D>
@NT = Skandasv<193>min
@N1 = (<MS>A.<|>D.<D> 630)
Ancient Hindu scriptures in Sanskrit, especially the Vedas, are difficult ç
to understand  because  of  their  archaic language and recondite ç
ritual system. A commentary written by scholars coming in the Vedic ç
tradition will be very helpful in unravelling their mysteries.
Skandasv<193>min is the earliest of the commentators on the <184>gveda ç
known to usnow, and whose commentary†though incomplete as extant ç
now†is available. He was the son of one Bhart<216>dhruva and belonged ç
to the country of Valabh<200> (the modern Gujarat). He was the guru ç
of Harisv<193>min, the well-known commentator of <185>atapatha Br<193>hma<207>a. ç
He might have lived around <MS>A.<|>D.<D> 625.
His commentary is quite lucid. Apart from mentioning the <216><218>i ç
(the sage who discovered the mantra) and devat<193> (the deity to ç
whom the mantra is dedicated) he also deals with the grammatical factors ç
involved and quotes several verses from other sources like the Anukrama<207><200>s ç
(index- works). His opinion is that the Vedic mantras are meant to ç
be used in sacrifices.
He has also written a commentary on the Nirukta of Y<193>ska (800 ç
<MS>B.<|>C.<D>).
See also <MS><184>GVEDA.
@SPACE = 
@NT = slavery
@SPACE = 
The <184>gveda uses the words d<193>sa and d<193>s<200> several ç
times, in several senses such as an enemy of demoniac character, a ç
paid servant or a slave. The last sense is evident in 7.86.7 and 8.56.3.
Though Megasthanes (4th century <MS>B.C.<D>) denies that slavery ç
(of the Grecian type?) existed in India, there is every reason to ç
believe that it did, as in other ancient civilisations.
It is interesting to note that the Artha·<193>stra (3.13) of Kau<219>ilya ç
(321 <MS>B.<|>C.<D>) prescribes severe punishment for those who try ç
to force others into slavery.
Slaves are classified as follows: dhvaj<193>h<216>ta (one captured ç
in a battle); <193>tmavikrayin (one who sells himself); udarad<193>sa ç
or garbhad<193>sa (one who is born to a slave woman from a slave man); ç
<193>hitika (one who is made a slave to repay a debt); da<207><195>apra<207><200>ta ç
(made a slave by a decree of the court).
All these slaves can regain their freedom by the prescribed methods ç
such as repaying the debt, working for wages to be set off against ç
the debt, and being in bondage for a specified period of time, all ç
the while working.
A master who is pleased of the services of the slave can always set ç
him free.
The dharma·<193>stras ordain that the slave should be treated in a ç
humane manner. Any abuse will result in the master undergoing punishment.
See also <MS>D°SA.
@SPACE = 
@NT = <185>lokav<193>rttika
@SPACE1 = 
Kum<193>rila Bha<219><219>a (8th century <MS>A.<|>D.<D>) was the senior ç
contemporary of <185>a<209>kara (<MS>A.<|>D.<D> 788-820). He was a ç
great scholar ofM<200>m<193><221>s<193> Dar·ana and struggled throughout ç
his life to fight Buddhism and re-establish Vedic religion.
He wrote an independent exposition on the <185><193>barabh<193><218>ya ç
(<185>abara's commentary on the P<220>rvam<200>m<193><221>s<193> ç
S<220>tras of Jaimini) in three parts. The <185>lokav<193>rttika ç
is the first and deals with the philosophical portion of <185>abara's ç
work as contained in the first chapter of the first book known as ç
the Tarkap<193>da.
See also <MS>KUM°RILA BHA<187><187>A.<D>
@SPACE = 
@NT = sm<216>ti
@N1 = (`remembrance')
@SPACE1 = 
In a technical sense it refers to the secondary scriptures like the ç
Manusm<216>ti which remind one, of the great spiritual truths ç
contained in the <185>ruti or the Vedas. See <MS>DHARMA<185>°STRAS<D> ç
for details.
In a more literal or common sense it means memory or remembrance.
After directly perceiving or experiencing any object of sense through ç
the j<210><193>nendriyas or the five organs of know-ledge, when a ç
person remembers that experience, it is called sm<216>ti. In such ç
a sm<216>ti, either all the experience is remembered or a little ç
less but never more. This is how it has been defined by the Yogas<220>tras ç
(1.11). It is one of the five kinds of mental modifications (cittav<216>ttis).
@NT = Sm<216>ticandrik<193>
See <MS>DEVAØØABHA<187><187>A.<D>
@NT = Sm<216>tiratn<193>kara
See <MS>CAØ£E<185>VARA.
@NT = snake-worship
See <MS>N°GA<D> and <MS>N°GAPA<178>CAM®.<D>
@NT = sn<193>na
@N1 = (`bath')
In the life of a Hindu, even ordinary acts like sn<193>na or bathing, ç
needed to keep the body clean and pure, are considered a sacrament ç
that elevates one spiritually.
A bath is compulsory for persons of all var<207>as. It is to be ç
taken in a river, a big tank, the tank attached to a temple, or from ç
the water drawn from one's own well or even a public well.
The br<193>hma<207>a householders are expected to take bath twice†before ç
sunrise and at noon†whereas a brahmac<193>rin is to take it only once. ç
A sa<221>ny<193>sin should bathe thrice, the last one being before ç
sunset.
The bath should always be accompanied by the chanting of Vedic mantras ç
such as <184>gveda (10.9.1-3), Taittir<200>ya Sa<221>hit<193>  (5.6.1.1, ç
2)  and  <184>gveda (10.190.1-3).
When a person is unable to take bath as prescribed (with all the formalities ç
and mantras) shortcuts are permitted such as invoking river-goddesses ç
into the water and sprinkling the same over himself.
Some of the pur<193><207>as and sm<216>tis (vide<185>a<209>khasm<216>ti ç
8.1 to 11; Agnipur<193>na 155.3, 4) give a list of six varieties ç
of sn<193>na. They are: nitya, naimittika, k<193>mya, kriy<193><209>ga, ç
mal<193>pakar<218>a<207>a (or abhya<209>ga) and kriy<193>.
Nityasn<193>na  is  the  one  already described.
Naimittikasn<193>na is occasioned by a nimitta or a special reason ç
like the birth of a son or the completion of a sacrifice or an eclipse ç
and so on.
K<193>myasn<193>na (bath for some desired object)  is  undertaken  in  a  place  of ç
pilgrimage or at any other place.
Kriy<193><209>gasn<193>na is resorted to as a part of a religious ç
rite.
Mal<193>pakar<218>a<207>a sn<193>na is actually an oilbath undertaken ç
on certain auspicious days to get prosperity.
Kriy<193>sn<193>na is the bathing done at a place of pilgrimage to ç
get the merit and performed as per the procedure prescribed (vide ç
<185>a<209>khasm<216>ti 9).
@SPACE1 = 
The dharma·<193>stras have also enume-rated six kinds of gau<207>asn<193>na ç
(secondary baths). They are: mantrasn<193>na (sprinkling water over ç
oneself with certain mantras); bhaumasn<193>na (smearing the body ç
with loose earth); <193>gneyasn<193>na (applying holy ashes); v<193>yav<200>yasn<193>na ç
(taking on or exposing the body to the dust raised by the hoofs of ç
cows); divyasn<193>na (wetting one's body in a shower of rain accompanied ç
by sunshine) and m<193>nasasn<193>na (repeating the name of God in ç
the mind).
@NT = Sn<193>nay<193>tr<193>
@SPACE = 
The p<220>r<207>im<193> during the month of Jye<218><219>ha†Jye<218><219>hap<220>r<207>im<193> ç
(May-June)†is known as the Sn<193>nay<193>tr<193> day. This is the ç
day on which Lord Jagann<193>tha (of Pur<200>) is said to have incarnated ç
himself in the present form of that image. On this occasion all the ç
three images are brought out of the temple on to a platform and anointed ç
by 108 pitchers of sacred water to the accompaniment of music and ç
Vedic chants. The images are then dressed in resplendent clothes.
See also <MS>JAGANN°THA PUR®<D> and <MS>RATHAY°TR°.
@SPACE1 = 
@NT = sn<193>taka
@N1 = (`one who has taken the<R>ç
[ceremonial] bath [after studenthood]')
@SPACE1 = 
A brahmac<193>rin (a Vedic student living in the house of his guru) ç
was expected to take a ceremonial bath at the end of his student-period ç
and seek the permission of his guru to return home, after paying the ç
gurudak<218>i<207><193> (fees). Such an one was called `sn<193>taka'.
Sn<193>takas were of three types: vidy<193>sn<193>taka (one who had ç
finished the course of Vedic studies but had not kept the Vedavratas ç
or Vedic vows); vrata-sn<193>taka (one who had kept the vows but could ç
not complete the course in the stipulated period); vidy<193>vratasn<193>taka ç
(one who had finished both).
The last one was considered the best of the three and was highly respected.
He could then return home and settle down as a g<216>hastha or householder.
A sn<193>taka could be introduced to an assemblage of learned men ç
by his guru.
The dharma·<193>stras give innumerable rules for a sn<193>taka to ç
observe. Most of them are concerned with his physical safety and maintenance ç
of the purity of his life.
See also <MS>SAM°VARTANA.<D>
@NT = <218>o<195>a·<193>k<218>ar<200>-mantra
By adding the letter `·r<200><221>' to the pa<210>cada·<193>k<218>ar<200>mantra, ç
the <218>o<195>a·<193>k<218>ar<200>-mantra is generated. It is a very ç
powerful mantra of Lalit<193>-tripurasundar<200>, an aspect of the ç
Dev<200> (Divine Mother P<193>rvat<200>). It has to be received ceremonially ç
from a qualified guru.
@NID = <+><+><+>See also <MS>PA<178>CADA<185>°K<186>AR®<D> and <MS>TANTRAS.<D>
@NT = <218>o<195>a·a-mah<193>d<193>na
@N1 = (`sixteen great gifts')
See <MS>D°NA<D> and <MS>MAH°D°NA.<D>
@NT = <218>o<195>a·a-sa<221>sk<193>ras
@N1 = (`sixteen sacraments')
According to Hinduism, a human being is purified and refined by under- ç
going certain rites, generally called sa<221>sk<193>ras. (See <MS>SA<189>SK°RAS.<D>)
The most widely accepted number of such sa<221>sk<193>ras is <218>o<195>a·a ç
or sixteen. Hence the name <218>o<195>a·a-sa<221>sk<193>ras.
The Hindu scriptures do not consider birth as the starting point of ç
life. It goes farther back, as it is conditioned by heredity, parentage ç
and environment. Keeping this in mind, the sa<221>sk<193>ras start ç
with conception.
The following is a brief description of these sixteen sa<221>sk<193>ras:
@SB = 1.	Garbh<193>dh<193>na
This is mainly concerned with the purification of the seed and the ç
womb so that the progeny will be endowed with good health and intelligence.
@SB = 2.	Pu<221>savana
This is performed with the specific desire of getting a male offspring. ç
The pregnant woman is made to undergo this during the third or the ç
fourth month of pregnancy.
@SB = 3.	S<200>mantonnayana
This consists in the parting of the hair above the forehead ceremonially. ç
It is said to protect the baby in the womb.
@SB = 4.	J<193>takarma
This is performed immediately after the baby is born and before the ç
umbilical cord is cut.
@SB = 5.	N<193>makara<207>a
This is the naming ceremony. It is generally performed on the eleventh ç
or the twelfth day after birth.
@SB = 6.	Ni<218>krama<207>a
During the fourth month, the baby is brought out of the house (for ç
the first time) where it was born and is blessed by the relatives ç
and friends.
@SB = 7.	Annapr<193>·ana
Performed after the sixth month, this sacrament of feeding the baby ç
with solid food is primarily meant to wean it away from breast-feeding ç
and gradually get used to normal food.
@SB = 8.	C<220><195><193>karma
@EMERGENCY = This is the first hair-cutting ceremony for the male ç
child performed generally during the third year (and before the seventh). ç
A ·ikh<193> (tuft of hair) is to be kept.
Vidy<193>rambha or the beginning of primary education by teaching ç
the alphabet is a subsidiary rite.
@SB = 9.	Upanayana
This is of primary importance in the life of a dvija (the twice-born). ç
Investiture with the yaj<210>opav<200>ta (sacred thread) and imparting ç
the G<193>yatr<200>-mantra are the most important steps.
@SB = 10 to 13 Vedavratas
A brahmac<193>rin had to undergo four Vedavratas: mah<193>namn<200>, ç
mah<193>vrata, upani<218>advrata and god<193>navrata.
They wereto be observed after the Upanayana ceremony and for a period ç
of one year each.
Gradually they went out of use and were substituted by other sa<221>sk<193>ras ç
as described later under 16.
@SB = 14.	Sam<193>vartana
This signifies the return of the brahmac<193>rin, after the completion ç
of his studenthood†he is now called a sn<193>taka† to his house.
@SB = 15.	Viv<193>ha
Through viv<193>ha or marriage, the sn<193>taka enters into the second ç
stage of life viz., g<193>rhasthya (life of the householder). This ç
stage is considered all- important, since the householder is the prop ç
of the whole society.
@SB = 16.	Antye<218><219>i
This stands for all the post-death ceremonies performed by the survivors ç
of the dead-person for his future welfare.
