Saram<193> was also the name of the wife of Vibh<200><218>a<207>a, ç
the youngest brother of R<193>va<207>a. She was the daughter of a ç
gandharva, <185>ail<220><218>a by name. She helped S<200>t<193> in ç
many ways in the days of her captivity in La<209>k<193>.
@NT = ·ara<207><193>gati
@N1 = (`surrender [to God]')
See <MS>PRAPATTI.
@NT = Sarasvat<200>
@N1 = (`the flowing one')
Sarasvat<200> is the <185>akti, the power and the consort of Brahm<193> ç
the creator. Hence she is the procreatrix†the mother†of the entire ç
creation.
Literally Sarasvat<200> means `the flowing one'. In the <184>gveda ç
she represents a river and the deity presiding over it. Hence, she ç
is connected with fertility and purification. Here are some of the ç
names used to describe her: S<193>rad<193> (giver of essence), V<193>g<200>·var<200> ç
(mistress of speech), Br<193>hm<200> (wife of Brahm<193>), Mah<193>vidy<193> ç
(knowledge supreme) and so on. It is obvious that the concept of Sarasvat<200>, ç
developed by the later mythological literature, is already here. The ç
`flowing one' can represent speech also if taken in an allegorical ç
sense. Hence Sarasvat<200> represents power and intelligence from ç
which organized creation proceeds.
She is considered as the personification of all knowledge†arts, sciences, ç
crafts, and skills. Knowledge is the anti-thesis of the darkness of ç
ignorance. Hence she is depicted as pure white in colour. Since she ç
is the representation of all sciences, arts, crafts and skills she ç
has to be extraordinarily beautiful and graceful. Clad in a spotless ç
white apparel and seated on a lotus seat, she holds in her four hands ç
a v<200><207><193> (lute), ak<218>am<193>l<193> (rosary) and pustaka ç
(book). Though these are most common, there are several variations. ç
Some of the other objects shown are: p<193>·a (noose), a<209>ku·a ç
(goad), padma (lotus), tri·<220>la (trident), ·a<209>kha (conch), ç
cakra (discus) and so on. Occasionally she is shown with five faces ç
or with eight hands. Even three eyes or blue neck are not uncommon. ç
In this case she is the Mah<193>sarasvat<200> aspect of Durg<193> ç
or P<193>rvat<200>.
Though no separate carrier vehicle is mentioned, ha<221>sa or swan, ç
the vehicle of Brahm<193>, her spouse, is usually associated with ç
her also. In popular mythological literature and pictures, a peacock ç
is also shown as her carrier vehicle.
Coming to the symbology: Being the consort of Brahm<193> the creator, ç
she represents his power and intelligence, without which organized ç
creation is impossible. Toshow that this intelligent power is stupendous ç
and absolutely pure, she is pictured as white and dazzling.
As usual, the four arms show her unimpeded power in all directions ç
or her all-pervasiveness.
Being the goddess of learning, it is but proper that Sarasvat<200> ç
is shown holding a book in her left hand. The book represents all ç
areas of secular sciences. Mere intellectual learning, without a heart ç
tempered by higher feelings, sentiments, and emotions, is as dry as ç
saw-dust. So she holds a v<200><207><193> (lute) on which she actually ç
plays, to show the need for the cultivation of fine-arts. Then there ç
is the ak<218>am<193>l<193> (rosary) held in the right hand. This ç
symbolises all spiritual sciences or yoga including tapas (austerities), ç
meditation and japa (repetition of the divine name). By holding the ç
book in the left hand and the rosary in the right hand she is obviously ç
teaching us that spiritual sciences are more important than secular ç
sciences.
@SPACE1 = 
The peacock with its beautiful plumage stands for this world in all ç
its glory. Since the attractions of the world lead the spiritual aspirant ç
astray, the peacock can actually symbolise avidy<193> (ignorance or ç
nescience). On the other hand the swan, which is supposed to possess ç
the peculiar power of separating milk from water, stands for viveka ç
(wisdom, discrimination) and hence for vidy<193> (knowledge). Though ç
it is true that vidy<193> or par<193>vidy<193> (spiritual illumination) ç
alone can give us mok<218>a (beatitude), avidy<193> signifying secular ç
knowledge†the sciences and arts of the world†need not be and should ç
not be neglected. As the ®·<193>v<193>sya Upani<218>ad (11) puts it, ç
we transcend hunger and thirst through the secular sciences and then ç
alone can we obtain immortality through the spiritual sciences. It ç
is to teach this great truth to us that Mother Sarasvat<200> has chosen ç
the two carrier vehicles, the swan and the peacock.
@NT = Sarasvat<200> River
@EMERGENCY = The <184>gveda often speaks of the Sarasvat<200> as ç
a mighty river (vide 2.41.16; 7.95.2 and so on) flowing from the ç
Him<193>layas into the ocean (almost parallel to the Sindh<220> or ç
the Indus river). There are references to it in other Vedic scriptures ç
also such as Aitareya Br<193>hma<207>a (2.19.1,<|>2) Pa<210>cavi<221>·a ç
Br<193>hma<207>a (25.10.1), <185>atapatha Br<193>hma<207>a and ç
Taitti-r<200>ya Sa<221>hit<193> (7.2.1.4).
The Mah<193>bh<193>rata declares that many Vedic sacrifices were ç
performed on its banks (vide °diparva 95.26; Vanaparva 12.14). ç
The K<193>myakavana (forest) where the P<193><207><195>avas lived ç
for some time was on its bank (Vanaparva 36.41); so also the hermitage ç
of the famous sage Dadh<200>ci (ibid 100.13).
@EMERGENCY = It seems to have originated in the higher Him<193>layan ç
ranges and flown through the present <185>iv<193>lik range of mountains ç
joined by other tributary rivers.
@EMERGENCY = Once a mighty river, as wide as 8to 13 kilometres, it ç
might have been the life-line of the people up to 3000 <MS>B.<|>C.<D> ç
Severe tectonic disturbances might have contributed to its gradual ç
disappearance by 2200 <MS>B.<|>C.<D> into a desert.
@EMERGENCY = The modern rivers†Sarasut<200> and Ghaggar (Himachal ç
Pradesh)†may be the remnants of the ancient Sarasvat<200>.
During the recent years, great efforts are being made to trace its ç
origin and course as also to revive it in some form. Satellite pictures, ç
controlled excavations under the supervision of expert archaeologists, ç
testing of soil sediment and artifacts by the most modern and scientific ç
methods †all these are leading to a positive proof of the existence ç
of the mighty river.
@NT = Sarasvat<200>vil<193>sa
@EMERGENCY = The Sarasvat<200>vil<193>sa is a compilation of various ç
subjects normally dealt with in the dharma·<193>stras. The author ç
Prat<193>pa-rudradeva was a king of the Gajapati dynasty, who ruled ç
at Ka<219>akanagar<200> (the modern Cuttack) during the period <MS>A.<|>D.<D> ç
1497-1540.
@EMERGENCY = The subjects dealt with in the Vyavah<193>rak<193><207><195>a ç
which is available now in print, mostly concern the methods of judicial ç
procedure.
@EMERGENCY = The work often quotes from the Mit<193>k<218>ar<193> ç
of Vij<210><193>ne·vara (<MS>A.<|>D.<D> 1100) and appreciates the views ç
of Bh<193>ruci (<MS>A.<|>D.<D> 700) who commented upon the Vi<218><207>udharma-s<220>tras.
@NT = Saray<220>
@EMERGENCY = Saray<220> is the famous river on the bank of which the ç
city of Ayodhy<193> was situated. Since it originates from a saras ç
(lake) in the Him<193>layas it is called Saray<220>.
@EMERGENCY = It is one of the seven tributaries of the river Ga<209>g<193> ç
and considered so sacred that one is advised to remember it with devotion ç
both at dawn and at dusk. A bath in it absolves one, of all sins.
@EMERGENCY = R<193>ma and Lak<218>ma<207>a bathed here before being ç
initiated by the sage Vi·v<193>-mitra into the secrets of dhanurvidy<193> ç
(science of archery).
@EMERGENCY = R<193>ma is said to have drowned himself in it at the ç
end of his life after having successfully completed the task of his ç
incarnation.
@EMERGENCY = It is now identified with the Goghr<193> river in Ayodhy<193>.
@NT = <185><193>r<200>rakas<220>tras
@EMERGENCY = See <MS>BRAHMAS<188>TRAS.<D>
@NT = <185><193>r<200>rasth<193>na
See <MS>CARAKASA<189>HIT°.
@NT = <185><193>r<209>ga
The weapons and implements that gods hold in their hands are often ç
givenspecial names. Iconographical works describe them with a definite ç
form and certain features.
<185><193>r<209>ga is the name of the bow wielded by Vi<218><207>u ç
even as Koda<207><195>a is of R<193>ma and G<193><207><195><200>va ç
of Arjuna.
In the personified form he is shown as a dv<193>rap<193>laka (doorkeeper) ç
on the leftside of the entrance, usually in thefifth enclosure. ç
He is a napu<221>saka (hermaphrodite) with body in five colours. He ç
wears red garments and carries a bow on his head which he symbolises. ç
His dhvaja (banner) has an arrow on it.
@NT = Sarpay<193>ga
@N1 = (`sacrifice of serpents')
A y<193>ga (sacrifice with Vedic mantras) is a very powerful instrument ç
for achieving any result one wants, good or bad.
The  king  Par<200>k<218>it  (grandson  of Arjuna, the great P<193><207><195>ava ç
hero) had been cursed by the young sage <185><216><209>gi to die by ç
snake-bite, since the king had humiliated the sage <185>am<200>ka ç
(<185><216><209>gi's father) by putting a dead snake round his neck. ç
Ultimately the king died by being bitten by Tak<218>aka, the lord ç
of snakes in the nether world.
Janamejaya, the eldest son of Par<200>k<218>it who  succeeded  him,  decided  to  take ç
revenge on Tak<218>aka and the entire race of snakes and serpents ç
by performing the Sarpay<193>ga (serpent-sacrifice).
As the y<193>ga started and progressed, innumerable snakes and serpents ç
were drawn  irresistibly  into  the  fire  and perished. Meanwhile ç
Tak<218>aka had taken refuge in Indra the king of gods and hence he ç
could not be easily drawn into the sacrificial fire. Knowing this ç
through their power of intuition, the <216><218>is who were performing ç
the sacrifice, changed the mantra to include Indra also! As Indra ç
too started being pulled by the power of the mantra, he abandoned ç
Tak<218>aka and escaped.
But before Tak<218>aka actually fell into the fire, his life as also ç
those of the surviving snakes, was saved by the timely intervention ç
of a young sage, °st<200>ka by name  (vide  Mah<193>bh<193>rata,  °diparva, ç
Chapters 51-58).
See <MS>°ST®KA<D> for details.
@NT = sar<220>pa-vigraha
@N1 = (`an icon with form')
In ritualistic worship vigrahas or icons are used extensively. These ç
may be sar<220>pa (with form) or ar<220>pa (without form).
A sar<220>pa-vigraha has a definite form, the form of the deity to ç
whom worship is offered. It may be anthropomorphic or otherwise.
Excessive limbs like four hands, or unnatural features like half-animal ç
body are often seen in them, to denote their supernatural status and ç
power.
The ar<220>pa-vigrahas are the ·iva-li<209>gas, ·<193>lagr<193>mas, ç
yantras and cakras as also stones of irregular shapes.
@NT = Sarvadar·anasa<209>graha
@N1 = (`an abridged<R>ç
version of all the philosophical systems')
Various systems of Indian philosophy have their own basic scriptures, ç
mostly in the form of s<220>tras or aphorisms. Since they were too ç
laconic to understand clearly, later followers of those schools brought ç
up in that tradition, wrote bh<193><218>yas or commentaries on the ç
same. These were followed further by subcommentaries to elucidate ç
the subtler and finer points of the doctrines as also the arguments ç
for and against them.
However, for an earnest student who wanted to know only the essentials ç
of these systems there were no brief compendiums or summaries available ç
in one place. This prompted several scholars of the later period to ç
produce such treatises.
The following is a list of such compendiums available now:
@NO = 1.
@NOK = Prasth<193>nabheda by Madhus<220>dana<R>ç
Sarasvat<200> (<MS>A.<|>D.<D> 1490-1580).
@NO = 2.
@NOK = <186>a<195>dar·ananir<207>aya by<R>ç
Merutu<209>ga (14th century <MS>A.<|>D.<D>)
@NO = 3.
@NOK = <186>a<195>dar·anasamuccaya by<R>ç
R<193>ja·ekharas<220>ri (13th century <MS>A.<|>D.<D>)
@NO = 4.
@NOK = <186>a<195>dar·anasamuccaya by<R>ç
Haribhadras<220>ri (<MS>A.<|>D.<D> 750).
@NO = 5.
@NOK = Sarvadar·anakaumud<200> by M<193>dhava Sarasvat<200> (14th ç
century <MS>A.<|>D.<D>).
@NO = 6.
@NOK = Sarvasiddh<193>ntaprave·aka by a<R>ç
Jaina muni (12th century <MS>A.<|>D.<D>).
@NO = 7.
@NOK = Sarvasiddh<193>ntasa<209>graha by a<R>ç
<185>a<209>kar<193>c<193>rya of a<R>ç
<185><193><209>karite monastery.
@NO = 8.
@NOK = Sarvamatasa<209>graha edited by Ga<207>apati <185><193>stri. ç
The author is unknown.
@NO = 9.
@NOK = Sarvamatasa<209>grahavil<193>sa by<R>ç
R<193>masubrahma<207>y<193>c<193>rya.
@NO = 10.
@NOK = Vivekavil<193>sa by<R>ç
Jinadattas<220>ri (<MS>A.<|>D.<D> 1200).
@SPACE1 = 
However, the Sarvadar·anasa<209>graha of M<193>dhava is not only ç
the best of such compendiums but also unique in many ways. Extending ç
over sixteen chapters, it deals with each of the systems as its protagonist ç
himself would have done. The language is elegant prose, interspersed ç
with appropriate quotations.
The systems treated here are: C<193>rv<193>ka; Bauddha; °rhata (or ç
Jaina); R<193>m<193>nuja (or Vi·i<218><219><193>dvaita); P<220>r<207>apraj<210>a ç
(or Dvaita); Nakul<200>·a P<193>·upata (a form of <185>aivism); <185>aiva; ç
Pratyabhij<210><193> (or K<193>·m<200>r <185>aivism); Rase·vara (glorifying ç
mercury); Aul<220>kya (Vai·e<218>ika); Ak<218>ap<193>da (Ny<193>ya); ç
Jaimini (P<220>rvam<200>m<193><221>s<193>); P<193><207>ini (philo-sophy ç
of ·abda or sound); S<193><209>khya; P<193>ta<210>jala (Yoga); <185>a<209>kara ç
(Advaita).
Whether the author M<193>dhava is the same as the sage Vidy<193>ra<207>ya ç
or another person, the son of S<193>ya<207>a (<MS>A.<|>D.<D> 1315-1387), ç
has been debated by scholars. But no clinching evidence has been offered ç
on behalf of either.
@NT = Sarvaj<210><193>tma Muni
See <MS>SA<177>K<186>EPA-<185>°R®RAKA.<D>
@NT = Sarvama<209>gal<193>
@N1 = (`one who brings<R>ç
auspiciousness to everybody')
She is one of the aspects of the Dev<200> or Divine Mother.
She is described as of golden hue and is decorated richly with splendid ç
ornaments. In her four hands she holds a rosary, a spear and a waterpot, ç
the last hand showing the varadamudr<193> (hand pose of bestowal of ç
boons).
She may be seated on a lotus or a lion.
@NT = Sarvam<220>la
@N1 = (`essence or root of all<R>ç
[scriptures]')
All the 37 works of Madhv<193>c<193>rya (<MS>A.D.<D> 1238-1317) exhibit ç
a thorough unity of purpose. Each work serves as an interpretation ç
of the others. Hence his immediate followers collected his works under ç
a single title, the Sarvam<220>la.
They are generally divided into sevengroups: G<200>t<193>prasth<193>na; ç
Upani<218>atprasth<193>na; S<220>traprasth<193>na; <184>kprasth<193>na; ç
Itih<193>sa  and  Pur<193>na;  Da·aprakara<207>as; Tantras<193>ra ç
and Stotras.
See also <MS>DVAITA VED°NTA DAR<185>ANA<D> and <MS>MADHV°C°RYA<D>.
@NT = Sarv<193>nukrama<207><200>
@N1 = (`an all-round index')
See <MS>ANUKRAMAØ®.<D>
@NT = sarvapr<193>ya·citta
@N1 = (`universal expiation')
This is a special omnibus type of expiation prescribed for a dying ç
person to ward off the effects of all sins that mighthave been committed ç
knowingly or unknowingly.
It may be performed either by the person himself or his son or any ç
other close relative.
This rite includes the following steps: shaving, bath, drinking pa<210>cagavya ç
(See <MS>PA<178>CAGAVYA<D>.), honouring a br<193>hma<207>a of pure ç
life, gifting a cow or money after referring to the various types ç
of sins he might have committed. This may be followed by further gifts ç
known as da·<193>d<193>nas (ten kinds of d<193>nas or gifts) and  the  recitation  of  the  K<193>mastuti ç
(Atharvaveda 3.29.7; Taittir<200>ya Br<193>hma<207>a 2.2.5.9).
The  whole  procedure  has  been described in the work Antyakarmad<200>pik<193> ç
of Haribha<219><219>ad<200>k<218>ita.
If the person takes <193>turasa<221>ny<193>sa, there is no need for ç
any expiation (See <MS>°TURASA<189>NY°SA.<D>).
@NT = Sarv<193>rthasiddhi
The philosopher saint Ved<193>nta De·ika (<MS>A.<|>D.<D> 1268-1370) ç
is considered as next only to R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137) ç
in the Vi·i<218><219><193>dvaita tradition. He was a prolific writer ç
not only in Sanskrit but also in Tamil.
Among the independent treatises on Vi·i<218><219><193>dvaita Ved<193>nta ç
written by him, the Tattvamukt<193>kal<193>pa is an important work. ç
It comprises 500 verses in the long metre, sragdhar<193>.
It has five chapters dealing with five different aspects of the philosophy ç
such as ja<195>adravya (prak<216>ti or nature), j<200>va (individual ç
souls), N<193>yaka (God) and so on.
The Sarv<193>rthasiddhi, also in verses, is his own commentary on ç
the Tattvamukt<193>kal<193>pa, elucidating the finer aspects of ç
the system.
See also <MS>VED°NTA DE<185>IKA.<D>
@NT = <185><193>st<193>
@N1 = (`one who commands')
The Hindu genius has the peculiar virtue of reconciling the irreconcilables. ç
At a time when the <185>aivas and Vai<218><207>avas were at loggerheads, ç
the story in the Bh<193>gavata (8.12), of <185>iva being enraptured ç
by the voluptuous beauty of (Vi<218><207>u as) Mohin<200>, the enchantress, ç
must have come in very handy. By taking it to the logical conclusion ç
it produced the wonderful deity Hariharaputra or <185><193>st<193>, ç
more commonly known as `Ayyappan' (a corrupted form of °rya). Whatever ç
he might have been in the beginning, he was certainly not a compromise ç
candidate tolerated by both the groups, but Supreme God Himself, highly ç
venerated by both.
Mythological accounts, of course, havetheir own story to tell. After ç
the death of Mahi<218><193>sura at the hands of Durg<193>,  his  spouse  Mahi<218><200>  performed ç
severe austerities to please Brahm<193>. She succeeded in getting ç
the boon that she could not be killed by <185>iva or Vi<218><207>u. ç
This newfound strength of Mahi<218><200> posed a formidable challenge ç
to the gods and the world. <185>iva and Vi<218><207>u, who could not ç
singly vanquish her, hit upon the plan of coming together as parents ç
to create her destroyer. The child thus created was found by King ç
R<193>ja·ekhara of Panthalam in Kerala who named it as Ma<207>ika<207><219>han ç
and brought it up as his own son, since he had no offspring. When ç
Ma<207>ika<207><219>han was twelve years old, he killed Mahi<218><200> ç
and brought leopardesses to his father's palace since their milk was ç
needed to cure the `headache' of the queen. Meanwhile, the secret ç
of Ma<207>ika<207><219>han being God Himself, had been revealed to ç
the king.Adored by the king Ma<207>ika<207><219>han disappeared, ç
after instructing him to build a temple at the place where his arrow ç
would land. That was the summit of the hill <185>abar<200>malai. The ç
temple is said to have been built by Vi·vakarma and the image prepared ç
and installed by Para·ur<193>ma. The place attracts millions of pilgrims ç
even now.
@SPACE1 = 
The word `<185><193>st<193>' means one who controls and rules over ç
the whole world. Mah<193>·<193>st<193> and Dharma·<193>st<193> are ç
the other names by which the deity is known. `<185><193>st<193>' is ç
one of the names of Buddha. The deity is said to ride on a white elephant ç
calledYogi. He is also described as the protector of Dharma. Hence ç
some scholars opine that Dharma-<185><193>st<193> may be Buddha absorbed ç
into the Hindu pantheon by the South Indian Hindus.
The image of <185><193>st<193> has four arms, three eyes and a peaceful ç
countenance, and is seated in Padm<193>sana. Two of the hands carry ç
the sword and the shield and the other two exhibit the Abhaya and ç
Varada Mudr<193>s.
According to another version, the image should have only two hands ç
and two eyes, and should be seated with the legs folded. It should ç
be bedecked with ornaments and have the Yaj<210>opav<200>ta. A crooked ç
stick, fruits and tender leaves of plants are sometimes shown in his ç
hands. A Vajrada<207><195>a is also shown occasionally.
Images in the standing posture are also seen to exist, though rare.
The ritual pilgrimage to the shrineof <185>r<200> Ayyappan at <185>abar<200>malai ç
is considered to be extremely auspicious and meritorious. The pilgrimage ç
itself has to be preceded by forty-one days of austerity during which ç
period strict celibacy is to be observed as also restrictions regarding ç
food, speech and sleep.
@NT = <186>a<218><219>h<200>
@N1 = (`sixth aspect [of the<R>ç
Divine Mother]')
<186>a<218><219>h<200> is a minor goddess, the sixth among the sixteen ç
m<193>t<216>k<193>s (minor goddesses). She guards a newborn baby on ç
the sixth day of its birth and also on the twenty-first day. She is ç
worshipped in the delivery room itself.
She is the deity who can cause or cure the maladies of children.
Sometimes she is identified with Devasen<193>, the spouse of Skanda ç
or Subrah-ma<207>ya, and is worshipped along with him on the Skanda<218>a<218><219>h<200> ç
day.
@NT = <186>a<218><219>itantra
@N1 = (`science of sixty topics')
@SPACE = 
The S<193><209>khyadar·ana is one of the oldest systems of Hindu philosophy ç
whose origins can be traced even to the Upani<218>ads.
The Ahirbudhnya Sa<221>hit<193> (12.19-30) refers to an ancient ç
work on the S<193><209>khya known as the <186>a<218><219>itantra. ç
Whether it was one particular ancient work or referred in general ç
to any work (or works) of <185><193><209>khya philosophy dealing with ç
sixty topics, is difficult to say.
According to one version, Pa<210>ca·ikha †the third of the three original ç
teachers of S<193><209>khya†is said to have composed this work.
The work is divided into two parts: The pr<193>k<216>tama<207><195>ala ç
(with 32 subdivisions) and the vaik<216>tama<207><195>ala (with 28 ç
sub- divisions).
The following is a general overview of the topics dealt with: prak<216>ti; ç
puru<218>as; relation of the prak<216>ti with the puru<218>as; evolution ç
of the categories from the prak<216>ti; inactivity of the puru<218>as; ç
five viparyayas or misconceptions; nine tu<218><219>is or contentments; ç
twenty-eight kinds of defects of organs and eight siddhis or attainments.
It is believed that the S<193><209>khya of Kapila and °suri was theistic ç
whereas Pa<210>ca·ikha made it atheistic.
@SPACE = 
@NT = ·astra
@N1 = (`that by which one is hurt')
@SPACE = 
The words astra and ·astra are commonly used in the epics and the ç
pur<193><207>as.
An astra is a missile discharged from a suitable instrument (like ç
a bow) whereas a ·astra is a weapon (like a sword) which is directly ç
wielded by the hand.
The word may also be used to indicate an instrument used in surgery.
In the Vedas a ·astra refers to a laudatory hymn†used in a sacrifice†that ç
is simply recited and not sung. A stotra is always sung.
A ·astra belongs to and follows a stotra.
Composed of several verses it is generally recited by the hot<216> ç
and his associates called ·rotrakas. This recitation involves other ç
steps like <193>h<193>va (summoning),  pratigara  (response),  t<220><218><207><200><221>japa ç
(silent or inaudible recitation) and so on.
@NT = ·<193>stra
@N1 = (`a treatise that commands and protects')
Etymologically speaking, the word refers to any treatise that gives ç
a command and protects the person who obeys it. In general it can ç
be applied to any systematically composed work dealing with any subject ç
that is useful to the human beings.
According to M<200>m<193><221>s<193> and Ved<193>nta, a ·<193>stra ç
must have four aspects that help in binding it into a single integrated ç
whole. (See <MS>ANUBANDHACATU<186><187>AYA<D> for details.)
It is interesting to note that every ancient ·<193>stra claims to ç
have originated from God Himself!
@NT = <185><193>strasiddh<193>ntale·asa<209>graha
This is a well-known and popular work of Appayya D<200>k<218>ita (<MS>A.<|>D.<D> ç
1520-1592) (See <MS>APPAYYA D®K<186>ITA<D> for details.).
Also known as Siddh<193>ntale·a-sa<209>graha, it<|>is<|>a<|>comprehensive<|><|>survey ç
of  the  doctrinal  interpretations  and arguments as formulated by ç
post-<185>a<209>kara advaitins. Though called a `sa<209>graha' (an ç
epitomised version) it is quite exhaustive.
There are four paricchedas or chapters. A very brief summary of the ç
contents may be attempted as follows:
@S10 = First Pariccheda
Nature  of  Brahman;  distinction between ®·vara and j<200>vas; problem ç
of causality of the world; nature and locus of avidy<193> and m<193>y<193>; ç
nature and scope of vidhi (injunction) in respect of Ved<193>ntic ç
study.
@S10 = Second Pariccheda
Relative importance of <185>ruti (the scripture) and pratyak<218>a ç
(direct perception); authority of the <185>ruti is to be accepted; ç
nature of svapna or dream and bhrama or erroneous cognition; the d<216><218><219>i-s<216><218><219>i-v<193>da; ç
refutation of the theories that a j<200>va (individual soul) is a<207>u ç
(atomic in size) and is different from Brahman.
@S10 = Third Pariccheda
Means of mukti or liberation; utility of karma or duties; the need ç
for sa<221>ny<193>sa or monastic life; discussion about m<220>l<193>-j<210><193>na ç
(root-nescience).
@S10 = Fourth Pariccheda
On j<200>vanmukti; dispelling of avidy<193> or ignorance; permanence ç
of mok<218>a or liberation; nature of liberation in the context of ç
ekaj<200>vav<193>da and anekaj<200>vav<193>da.
The work has an excellent commentary†the K<216><218><207><193>la<209>k<193>ra†by ç
Acyutak<216><218><207><193>-nanda T<200>rtha.
See also <MS>ADVAITA VED°NTA DAR<185>ANA<D>, <MS>D<184><186><187>I-S<184><186><187>I-V°DA<D> ç
and <MS>EKAJ®VAV°DA.<D>
@NT = <218>a<218><219>yabdap<220>rti-·<193>nti
Known also as Ugraratha·<193>nti, it is a propitiatory rite performed ç
on the completion of 60 years in a man's life. See <MS><185>°NTIS<D> ç
for details.
@NT = sat
@N1 = (`the existent')
The two words `sat' and `asat' are frequently mentioned and discussed ç
in Indian philosophical and religious works. If `sat' stands for existence, ç
unchanging reality, truth or the good, `asat' represents all that ç
is opposed to it; the non-existent, the transient, falsehood, evil ç
and so on.
However, the word `asat' is sometimes used in the Upani<218>ads in ç
the sense of the unmanifested state (vide Taittir<200>yopani<218>ad ç
2.7) before creation, and the word `sat' to denote its manifested ç
state.
@NT = <185>ataca<207><195><200>; Sahasraca<207><195><200>
One of the most important texts of the <185><193>kta school (cult ç
of the Divine Mother) is the Ca<207><195><200>, also known as the ç
Dev<200>m<193>h<193>tmya or the Durg<193>sapta·at<200>. A ceremonial ç
recital of this work is believed to bestow on the devotee whatever ç
boon he wants.
If ten br<193>hma<207>as of pure character recite it ten times it ç
becomes <185>ataca<207><195><200>. If a hundred br<193>hma<207>as ç
recite it ten times it becomes Sahasraca<207><195><200>. The recital ç
is spread over four days as follows:
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(.3333,1.0000,E1), ç
ABOVE(.0278), BELOW(.0417), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
, First day, Once
, Second day, Two times
, Third day, Three times
, Fourth day, Four times
@Z_TBL_END = 
After the recital, a hundred br<193>h-ma<207>as are to be fed in the ç
former and a thousand in the latter.
The <185>ataca<207><195><200> and the Sahasraca<207><195><200> are ç
conducted for the good of the whole society or the world.
See also <MS>CAØ£®P°<187>HA.<D>
@NT = <185>atad<220><218>a<207><200>
@N1 = (`[a work pointing out]<R>ç
a hundred defects [in Advaita Ved<193>nta]')
Offence is the best form of defence! This principle seems to have ç
inspired a number of scholars of the various schools of Ved<193>nta ç
to produce highly polemical works with a view to demolishing other, ç
rival, systems.
One such work is the <185>atad<220><218>a<207><200> of Ved<193>nta ç
De·ika (<MS>A.<|>D.<D> 1268-1370). It has been commented upon by R<193>m<193>nujad<193>sa ç
and <185>r<200>niv<193>s<193>carya. These commentaries are known as ç
Ca<207><195>am<193>ruta and Sahasra-kira<207><200>.
Though  the  title  indicates  one hundred refutations of Advaita ç
Ved<193>nta of <185>a<209>kara (<MS>A.<|>D.<D> 788-820) the text now ç
available has only sixty-six. Scholars opine that the rest of the ç
work comprising thirty four refutations might have been lost or the ç
work might have ended with the sixty sixth paragraph only. In that ç
case `·ata' may mean, not `hundred', but `many'.
It is interesting to note that Ved<193>nta De·ika  considers  <185><193><209>kara  Ved<193>nta's ç
barring of <185><220>dras from attaining the knowledge of Brahman, ç
as inappropriate.
The work concludes with the statement that <185>a<209>kara's philosophy ç
cannot be reconciled with that of the Brahmas<220>tras.
See <MS>VED°NTA DE<185>IKA<D> also.
@NT = <185>atapatha Br<193>hma<207>a
The biggest of all the Br<193>hma<207>as, the <185>atapatha Br<193>hma<207>a ç
belongs to the <185>ukla Yajurveda. It derives its name from the ç
fact that it has ·ata or one hundred chapters.
It might have been compiled during 3000 <MS>B.<|>C.<D> It is available ç
in two ·<193>kh<193>s or recensions: the K<193><207>va and the M<193>dhyan-dina. ç
The K<193><207>va·<193>kh<193> has 17 k<193><207><195>as (books) ç
divided into 104 adhy<193>yas (chapters). They are subdivided into ç
435 br<193>hma<207>as (subsections), the total number of ka<207><195>ik<193>s ç
or mantras being 6806.
The corresponding figures for the M<193>dhyandina·<193>kh<193> are ç
14; 100; 438 and 7624.
It may be interesting to note that the first nine k<193><207><195>as ç
of the M<193>dhyandina recension follow the Sa<221>hit<193> (the ç
<185>ukla Yajurveda Sa<221>hit<193>, also called the V<193>jasaney<200> ç
Sa<221>hit<193>) closely. They may be considered like a commentary.
The work, almost entirely, concerns itself with the various aspects ç
of Vedic sacrifices.
A very brief summary of the contents may now be given:
@SPACE = 
@S10 = K<193><207><195>a 1
Dar·ap<220>r<207>am<193>sa sacrifice.
@SPACE = 
@S10 = K<193><207><195>a 2
Agny<193>dh<193>na (producing the sacrificial fire); Agnihotra; Pi<207><195>apit<216>yaj<210>a ç
(sacrifice to the manes); °graya<207>a (offering of firstfruits) ç
and C<193>turm<193>sya (four-monthly sacrifices).
@SPACE = 
@S10 = K<193><207><195>as 3 and 4
Somay<193>ga.
@SPACE = 
@S10 = K<193><207><195>a 5
V<193>japeya and R<193>jas<220>ya sacrifices.
@S10 = K<193><207><195>as 6 to 10
@SPACE1 = 
Vi<218><207>ukrama (taking three or four steps in a Somay<193>ga with ç
mantras of Vi<218><207>u); va<207><200>-v<193>hana (coming and going ç
of the vessel containing fire on a cart); cayana (piling of fire); ç
<185>atarudr<200>yahoma (homa with the mantras of the Rudr<193>-dhy<193>ya); ç
up<193>san<193> (meditation) on Agni and a few other topics.
@SPACE1 = 
@S10 = K<193><207><195>as 11 to 14
Upanayana; brahmayaj<210>a (Vedic studies);  obsequial  rites;  A·vamedha; ç
Sarvamedha; Puru<218>amedha and Pravargya (a minor rite associated ç
with Somay<193>ga).
There is very little difference of topics in the K<193><207>va recension.
The sage Y<193>j<210>avalkya is prominent in the first five k<193><207><195>as. ç
However, it is the sage <185><193><207><195>ilya that is very conspicuous ç
in the next five. Even then, all the ten k<193><207><195>as must have ç
been the handiwork of Y<193>j<210>navalkya who gave <185><193><207><195>ilya ç
his due place out of respect.
The <185>atapatha Br<193>hma<207>a mentions by name many janapadas ç
or countries such as G<193>ndh<193>ra, Kekaya, <185><193>lva, certain ç
parts of °ry<193>varta, Kurup<193><210>c<193>la, Kosala, Videha and ç
S<216><210>jaya.
Apart from describing many Vedic sacrifices in great detail, the work ç
also gives many interesting <193>khy<193>nas or stories of the ancient ç
periods often with historical content.
There is an obvious reference to the spread of Vedic religion and ç
culture from the river Sarasvat<200> in the west right up to the river ç
Sad<193>n<200>r<193> (Saray<220>?) in the east.
@SPACE1 = 
Spiritual  interpretations  of  the sacrifices also find a place now ç
and then.
