@NT = Sauptikaparva
It is the tenth parva or book of the Mah<193>bh<193>rata.
See <MS>MAH°BH°RATA.<D>
@NT = Saurapur<193><207>a
@N1 = (`the pur<193><207>a concerning<R>ç
S<220>rya or the Sun-god')
The pur<193><207>as are the secondary sources of Hindu religion and ç
culture. They are broadly classified into two divisions: The mah<193>pur<193><207>as ç
and the upapur<193><207>as.
Though tradition counts them as 18 in each group, the upapur<193><207>as ç
as they are listed now are at least 29.
They were taught by S<220>rya or °ditya to Manu, his own son.
The Saurapur<193><207>a is one of them. It has 3900 verses spread ç
over 69 chapters. It belongs to the <185>aiva group of pur<193><207>as. ç
Its contents, which are variegated, may be summarised briefly as follows:
Greatness of <185>iva and the effect of devotion to him as also his ç
mantra (O<221>nama··iv<193>ya); construction of <185>iva temples, ç
worship of <185>iva as also several stotras or hymns to him.
Several stories like the destruction of Dak<218>a's sacrifice, <185>iva's ç
marriage to P<193>rvat<200>, birth of Skanda (Subrahma<207>ya), killing  of  T<193>rak<193>sura,  destruction  of ç
Tripuras or the three cities of the demons, Upamanyu being blessed ç
with an ocean of milk and Vi<218><207>u getting his Sudar·ana discus ç
by the grace of <185>iva.
On places of pilgrimage like K<193>·<200>, Ujjayin<200>, the river ç
Ga<209>g<193> and several other places.
Pr<193>ya·cittas (expiations), ·r<193>ddhas (obsequial  rites),  var<207><193>·ramadharmas, ç
details of creation as also some s<193>dhanas according to yoga.
Thus, this pur<193><207>a can be considered an important work on <185>aivism.
@NT = Sauti
@N1 = (`S<220>ta's son')
In most of the pur<193><207>as, the narrator is said to be Romahar<218>a<207>a ç
who was also known as the S<220>tapaur<193><207>ika. His son Ugra·ravas ç
was called Sauti (the son of S<220>ta). Sauti too narrated many pur<193><207>as ç
(ancient lore) to the <216><218>is of Naimi<218><193>ra<207>ya.
Once Balar<193>ma killed him using a darbha (blade of dry grass) since ç
he did not show enough respect. However, at the intervention of the ç
sages, he restored him to life.
@NT = Sautr<193>ma<207><200>
@N1 = (`a rite [for Indra] the <R>ç
S<220>tr<193>tman')
It is a Vedic sacrifice belonging to the Haviryaj<210>a group. (See ç
<MS>HAVIRYAJ<178>A<D> for details.)
Two varieties of this have been recognised; Caraka-sautr<193>ma<207><200> ç
and Kaukil<200>-sautr<193>ma<207><200>.
The former is a part of the R<193>jas<220>ya-y<193>ga whereas the ç
latter is an independent rite.
Though sur<193> or wine is ceremonially purified and offered in it, ç
it is not drunk by the priests. In Modern times, milk is offered instead ç
of sur<193>.
It involves animal sacrifice also, the animals being a goat, an ewe, ç
and a bull. Alternatively, all the three may be goats only.
It was performed either for regaining one's  lost  kingdom  or  for  getting ç
prosperity.
See also <MS>VEDIC SACRIFICES.<D>
@NT = <185>auva-udg<200>tha
@N1 = (`the udg<200>tha revealed<R>ç
through a dog')
@SPACE = 
@SPACE = 
There is an interesting incident mentioned in the Ch<193>ndogya Upani<218>ad ç
(1.12)
A sage, Gl<193>va-maitreya by name, had started searching for a suitable ç
place to repeat and study the Vedas. He suddenly saw a beautiful white ç
dog in front of him. Very soon a few more dogs too appeared on the ç
scene and requested the white dog to get them food†because they were ç
hungry†by singing for the same. They were asked to be present in that ç
very place the next morning. And they did so.
Now, as per the directions of the chief dog, they formed a continuous ç
chain†each dog catching hold of the tail of the dog in front of it†and ç
started singing an udg<200>tha (the second, the most important, part ç
of a s<193>ma chanting) which was a prayer addressed to the deity ç
°ditya (Sun-god) and requesting him for food.
The dogs had actually imitated such a formation by the priests in ç
a Somay<193>ga during the chanting of the Bahi<218>pavam<193>na hymn.
This came to be known as the <185>auva-udg<200>tha, the udg<200>tha ç
revealed by a dog.
The white dog was a deva (god) or a <216><218>i (sage) in that disguise.
It had appeared before the sage Gl<193>va-maitreya to teach him an ç
udg<200>tha by singing which, one could get plenty of food. This had ç
become necessary since the people (as per the previous section of ç
the Ch<193>ndogya Upani<218>ad) were suffering from a famine.
The dogs represent the mukhya or the chief pr<193><207>a and the subsidiary ç
pr<193><207>as.
@NT = savana
@N1 = (`to press out')
The process of pressing the soma stalks to prepare the soma juice ç
for offering as oblations in a Somay<193>ga is known as savana. The ç
day on which it is done is called suty<193>.
The pressing is done three times during this day: in the morning, ç
at noon and in the afternoon. They are respectively called pr<193>tassavana, ç
m<193>dhyandinasavana and t<216>t<200>yasavana.
They all follow the same pattern.
These three savanas are referred to even in the <184>gveda (3.28.1, ç
4 and 5) thereby showing that this rite of savana is quite ancient.
@NT = <185>avas<193>dhan<193>
@N1 = (`a [t<193>ntrik] practice<R>ç
involving a dead-body')
@EMERGENCY = Certain t<193>ntrik works like the Kaul<193>val<200>nir<207>aya ç
(14.75-260) describe this terrible s<193>dhan<193> involving a corpse ç
whereby the aspirant can get what he wants, in a single night.
@EMERGENCY = He has to get the corpse of a man as per the instructions ç
given in the works, wash it first, offer worship to it and then to ç
Durg<193> or K<193>l<200> at dead of night in a cemetery. He has to ç
repeat the prescribed mantra. If he is not frightened by the terrific ç
sights and experiences, and after following a long procedure he secures ç
the fulfilment of his desires.
@NT = savic<193>ra-sam<193>patti
@EMERGENCY = The Yogas<220>tras of Pata<210>jali (200 <MS>B.C.<D>) ç
has used the word sa<221>yama as a technical term (vide 3.4). It ç
denotes dh<193>ra<207><193> (fixing the mind on an object), dhy<193>na ç
(meditation) and sam<193>dhi (total absorption) on the same object ç
of concentration.
When sa<221>yama on a gross object leads to its realisation, revealing ç
everything about it, it is called savitarka-sam<193>patti (or sam<193>dhi). ç
When this realisation†after practice†comes instantaneously without ç
the intervening processes of details involved in the meditation, it ç
is called nirvitarka-sam<193>patti.
When the mind is raised from the gross to the subtle aspects of the ç
same object like the five tanm<193>tras up to prak<216>ti, the sam<193>dhi ç
is known as savic<193>ra-sam<193>patti.
The yogic power generated by the first leads to the next step; as ç
for instance, from the savitarka to the nirvitarka and from the savic<193>ra ç
to the nirvic<193>ra (ibid 1.17; 1.44).
See also <MS>NIRVIC°RASAM°PATTI.<D>
@NT = savikalpaka
@N1 = (`with details')
This word has two applications. In pratyak<218>apram<193><207>a (direct ç
perception) it refers to a perception with all the details. For instance, ç
when we see a pot and note its general presence, it is nirvikalpaka ç
perception (`Here is a pot.'). But, when we closely observe its size, ç
colour, position and other details it becomes savikalpaka perception ç
(`This is a small black pot kept on a table.').
As applied to sam<193>dhi, it refers tosampraj<210><193>tasam<193>dhi, ç
wherein all the details of the object of meditation are seen and known ç
very clearly.
See also <MS>ASAMPRAJ<178>°TA<D> and <MS>NIRVIKALPAKA.<D>
@NT = S<193>vitr<200>
Along with S<200>t<193> and Damayant<200>, S<193>vitr<200> also has ç
been considered a paragon of wifely virtues. Her story appears in ç
detail in the Mah<193>bh<193>rata (Vanaparva, chapters 293-299).
She was the daughter of the king A·vapati of Madrade·a. She chose ç
to marry Satyav<193>n, the only son of the blind king Dyumatsena of ç
S<193>lvade·a, even though the sage N<193>rada had warned her that ç
he would die just after a year.
Dyumatsena was living with his wife in a hermitage in a forest after ç
being deposed by the enemies. Satyav<193>n was living with them, serving ç
them with great care and devotion.
On that fateful day, S<193>vitr<200> insisted upon accompanying Satyav<193>n ç
to the forest for his normal work. When, after some work, he fell ç
sick and lay down on her lap, god Yama appeared there with his noose ç
to take Satyav<193>n's soul to his world. Because of her power of ç
chastity, she was able, not only to see him but also follow him! After ç
much argument†in spite of Yama's persuasive efforts to send her back†she ç
so pleased him with her devotion to her husband that he revived Satyav<193>n, ç
gave him a long life as also other boons she asked for. As a result, ç
Dyumatsena regained his eyesight and kingdom. Satyav<193>n became ç
the king in course of time.
See also <MS>G°YATR®.<D>
@NT = S<193>vitr<200>mantra
See <MS>G°YATR<200>.<D>
@NT = s<193>vitr<200>prave·a
@N1 = (`entering into the S<193>vitr<200> [G<193>yatr<200>] mantra')
Most of the dharma·<193>stras have ruled that sa<221>ny<193>sa (monastic ç
life) is permitted only to the br<193>hma<207>as.
A br<193>hma<207>a householder is expected to keep the ·ikh<193> (tuft ç
of hair) and the yaj<210>opav<200>ta (the sacred thread) which alone ç
make him eligible for the performance of Vedic and other rituals.
However, when he wishes to embrace sa<221>ny<193>sa, he will have ç
to give up all the ritualistic actions of the previous stages of life. ç
This includes the giving up the ·ikh<193>, the yaj<210>opav<200>ta ç
as also the sandhy<193> ritual along with the G<193>yatr<200> (= S<193>vitr<200>) ç
mantra.
The s<193>vitr<200>prave·a is one of the stepsin this process, wherein ç
the S<193>vitr<200> (G<193>yatr<200>) mantra is internalised. This ç
is done by repeating the O<209>k<193>ra, the vy<193>h<216>tis and ç
the S<193>vitr<200> mantra thus:
@SPACE = 
@OUT2 = Om<+>bh<220><199>, s<193>vitr<200>m pravi·<193>mi,<R>ç
tat saviturvare<207>yam;
@OUT2 = Om<+>bhuva<199>, s<193>vitr<200>m pravi·<193>mi,<R>ç
bhargo devasya dh<200>mahi;
@OUT2 = O<221><+>sva<199>, s<193>vitr<200>m pravi·<193>mi,<R>ç
dhiyo yo na<199> pracoday<193>t;
@OUT2 = Om<+>bh<220>rbhuvassuva<199> s<193>vitr<200>m pravi·<193>mi,<R>ç
tatsaviturvare<207>yam bhargo devasya dh<200>mahi dhiyo yo na<199> ç
pracoday<193>t<F49W1>f<W1I>
@NT = S<193>vitr<200>vrata
See <MS>VA<187>AS°VITR®VRATA.<D>
@NT = savyabhic<193>ra
@N1 = (`irregular middle')
According to the Ny<193>ya system of Hindu philosophy, there are five ç
kinds of hetv<193>bh<193>sas (invalid reasonings) of which the first ç
is savyabhic<193>ra. Here the middle term of the syllogism is irregular.
To illustrate:
All bipeds are rational.
Swans are bipeds.
Hence, swans are rational.
Since the middle term `biped' is not uniformly related to the major ç
term `rational,' the conclusion is wrong.
(Vyabhic<193>ra is a technical term which means the absence of cause ç
and effect relationship between two things.)
See also <MS>HETV°BH°SA.<D>
@NT = S<193>ya<207>a
@N1 = (14th century <MS>A.<|>D.<D>; d.<MS>A.<|>D.<D> 1387)
If it was left to <185>a<209>kara (<MS>A.<|>D.<D> 788-820) to unravel ç
the mysteries of the Ved<193>ntic scriptures†especially the prasth<193>natraya†destiny ç
chose S<193>ya<207>a toexpound the other three aspects of theVedas, ç
viz., the Sa<221>hit<193>s, the Br<193>hma<207>as and the °ra<207>yakas. ç
But for his monumental work, much of the original Vedic literature ç
would have remained inscrutable.
Though far removed from the times of the Vedas chronologically, being ç
brought up in the orthodox tradition as also withhis vast knowledge ç
of the Sanskrit language and ancient literature, he was ideally suited ç
to this stupendous task.
He was the second son of M<193>ya<207>a and <185>r<200>mat<200>, M<193>dhava ç
(Vidy<193>ra<207>ya) and Bhogan<193>tha being his elder and younger ç
brothers.
Physically he was strong and handsome, well-versed even in the martial ç
arts. As regards his education in the traditional scriptures, arts ç
and sciences, he seems to have been trained by his own father first ç
and later by Sarvaj<210>a Vi<218><207>ubha<219><219>a (Vidy<193>-t<200>rtha) ç
and <185>r<200>ka<207><219>ha Up<193>dhy<193>ya.
He was deeply involved in the training of the princes of the Vijayanagara ç
empire and was also the prime minister for four kings from <MS>A.<|>D.<D> ç
1340 to 1387.
Eight works have been ascribed tohis authorship. They are: Subh<193><218>ita-sudh<193>nidhi; ç
Yaj<210>atantrasudh<193>nidhi; Pr<193>ya·cittasudh<193>nidhi; ç
°yurvedasudh<193>-nidhi; Ala<209>k<193>rasudh<193>nidhi; Dh<193>tuv<216>tti; ç
Puru<218><193>rthasudh<193>nidhi; Ved<193>rthaprak<193>·a.
It is the general opinion of Vedic scholars that the last work†detailed ç
commentary on the Vedas†must have been undertaken by a group of scholars ç
under the overall supervision of S<193>ya<207>a (and Vidy<193>ra<207>ya). ç
Of course, S<193>ya<207>a too must have contributed to it substantially.
The Subh<193><218>itasudh<193>nidhi is a compendium of pithy sayings ç
on morality, ethics and general knowledge.
As the very name indicates, the Yaj<210>atantrasudh<193>nidh<200> ç
deals with the performance of Vedic sacrifices.
The  third  work,  also  known  as Karmavip<193>ka, deals with pr<193>ya·cittas ç
or expiatory rites.
The fourth work on the °yurveda was probably written by Ek<193>mran<193>tha ç
Pa<207><195>ita at the instance of S<193>ya<207>a. It is not available ç
now.
The next work on ala<209>k<193>ra or figures of speech was probably ç
authored by his younger brother Bhogan<193>tha. The full text has ç
not been secured so far.
Dh<193>tuv<216>tti, the sixth in the series, is an authoritative ç
work on Sanskrit grammar, concentrating on the dh<193>tus (basic roots ç
of verbs). The full text has been edited and printed.
@SPACE1 = 
The next work, the Puru<218><193>rthasudh<193>-nidhi deals in detail ç
with the four puru<218><193>rthas†dharma, artha, k<193>ma and mok<218>a†and ç
is similar to the treatises on the dharma·<193>stras and the <193>gamas.
However, it is the Ved<193>rthaprak<193>·a, his magnum opus, that ç
has made him immortal in the annals of Vedic literature. It might ç
have been composed during the period <MS>A.<|>D.<D> 1360 to 1385.
It should however be noted that he has dealt with only the Karmak<193><207><195>a ç
part of the Vedas and has not touched the J<210><193>nak<193><207><195>a ç
part (i.e., the Upani<218>ads or the Ved<193>nta).
It  was  the  encouragement  and generous patronage of the king Bukka ç
(rule: <MS>A.<|>D.<D> 1354 to 1376) that helped S<193>ya<207>a  to  successfully  complete  this ç
astounding work. Many contemporary scholars of repute like Pa<210>c<193>gni ç
M<193>dhava, Naraharibha<219><219>a, N<193>r<193>ya<207>a V<193>japey<200>, ç
Pa<207><195>ari D<200>k<218>ita and V<193>manabha<219><219>a were ç
also involved in this work, S<193>ya<207>a's contribution being the ç
greatest.
S<193>ya<207>a is very particular to mention the names of the earlier ç
teachers and commentators like Y<193>ska, °pastamba, °·val<193>yana, ç
P<193><207>ini, K<193>ty<193>yana, Pata<210>jali, Bha<219><219>abh<193>skara ç
Mi·ra, Skandasv<193>min and others.
Though his interpretations have sometimes  been  criticised  by  modern ç
scholars†both European and Indian† none in his position could have ç
accomplished such a gigantic task in so perfect a manner.
Scholars of religion and philosophyin general, and Hindus in particular, ç
should ever remain deeply indebted to him.
See also <MS>VIDY°RAØYA.<D>
@NT = s<193>yana
See <MS>NIRAYANA.<D>
@NT = ·ay<193>nam<220>rti
@N1 = (`image in the reclining<R>ç
posture')
The images of gods established in temples are generally of three types, ç
of which the ·ay<193>nam<220>rtis (in the reclining posture) are the ç
last. According to the Vaikh<193>nas<193>gama it is only the images ç
ofVi<218><207>u†as those of Ra<209>gan<193>tha and Padman<193>bha†that ç
are shown as ·ay<193>na-m<220>rtis.
See also <MS>M<188>RTI<185>ILPA<185>°STRA.<D>
@NT = s<193>yujya
@N1 = (`getting united [with God]')
In this state of liberation, the j<200>va gets merged in the Supreme ç
even as a river merges with the sea or ocean.
See <MS>MOK<186>A.
@NT = ·ayy<193>dhiv<193>sa
See <MS>ADHIV°SA.<D>
@NT = <185>e<218>a
See <MS>°DI<185>E<186>A.<D>
@NT = ·e<218>a, ·e<218>in
@N1 = (`part and whole')
In the Vi·i<218><219><193>dvaita Ved<193>nta, the j<200>va (individual ç
soul) being a part (= ·e<218>a) of Brahman, is called ·e<218>a and ç
Brahman Himself as <185>e<218>in (the whole).
@NT = ·e<218>avat
See <MS>S°M°NYATOD<184><186><187>A.<D>
@NT = Se·vara-s<193><209>khya
@N1 = (`S<193><209>khya that accepts ®·vara')
The Yogadar·ana of Pata<210>jali (200 <MS>B.C.<D>) accepts all items ç
of the S<193><209>khya philosophy and adds ®·vara (God) as the 26th ç
principle. Hence it is called Se·vara-s<193><209>khya.
@NT = <185>ibi
<185>ibi†also known as V<216><218><193>darbhi†was a king of K<193>·<200>. ç
He had taken a vow that he would protect anyone who took refuge in ç
him. Once Indra and Agni decided to subject him to a severe test. ç
Indra took the form of a hawk and Agni, that of a pigeon. The hawk ç
started pursuing the pigeon to kill it and eat it. The pigeon managed ç
to approach the king <185>ibi and sought his protection which he instantly ç
promised. When the hawk too approached him to give the pigeon which ç
was its rightful food, <185>ibi struck a compromise saying that he ç
would give as much flesh as the pigeon weighed, from his own body. ç
When he started cutting his own body, the two gods revealed themselves ç
in their true form, appreciated his sacrifice and gave him several ç
boons including making his body whole as it was earlier, (vide Mah<193>bh<193>rata, ç
Vanaparva, 197).
@NT = siddh<193>nta
@N1 = (`an established tenet')
In the most general sense, this word means a theory. It has to be ç
established firmly after countering effectively all the doubts and ç
objections raised against it.
In the Ny<193>ya philosophy (vide Ny<193>ya-s<220>tras 1.1.26 to ç
31), it is classified into four types: sarvatantrasiddh<193>nta (adogma ç
of all the schools); pratitantrasiddh<193>nta (a dogma peculiar to ç
some school); adhikara<207>asiddh<193>nta (a hypothetical dogma) and ç
abhyupagamasiddh<193>nta (an implied dogma).
The example for the first dogma is that all schools accept the existence ç
of the five elements (earth, water etc.).
`Something can never come out of nothing.' This dogma of the S<193><209>khya ç
philosophy is accepted by similar schools but rejected by opposite ç
schools. This is the example for the second siddh<193>nta.
In the third siddh<193>nta, acceptance of one fact leads to the acceptance ç
of other facts. For instance, acceptance of the j<200>va or the soul ç
as the experiencer leads to the acceptance of senses and their respective ç
objects.
In the last siddh<193>nta a tenet which is not explicitly declared ç
as such, follows from the examination of particulars concerning it. ç
For example, when it is discussed whether sound is eternal or non-eternal, ç
it presupposes or implies that sound is a substance.
Special works on Hindu astronomy and astrology based on the Ved<193><209>ga ç
Jyauti<218>a are also called Siddh<193>ntas. They are nine in number: ç
Brahmasiddh<193>nta; Somasiddh<193>nta; S<220>ryasiddh<193>nta; ç
B<216>has-patisiddh<193>nta; Gargasiddh<193>nta; N<193>rada-siddh<193>nta;  Par<193>·arasiddh<193>nta; ç
Pulastya- siddh<193>nta; and Vasi<218><219>hasiddh<193>nta.
Obviously they are the theories put forward by these different sages.
@SPACE = 
@NT = Siddh<193>ntabindu
@SPACE = 
For the benefit of ordinary s<193>dhakas (seekers of spiritual wisdom), ç
<185>a<209>kara (<MS>A.D.<D> 788-820) composed a few elementary treatises ç
known as prakara<207>as which describe succinctly the essence of his ç
Advaita Ved<193>nta. One such work†which appears more like a stotra ç
or a devotional hymn†is the Da·a·lok<200>, in ten verses.
Madhus<220>dana Sarasvat<200> (<MS>A.<|>D.<D> 1490-1580), a well-known ç
writer of Advaita philosophy, has written a fairly long commentary ç
on this Da·a·lok<200>, known as the Siddh<193>ntabindu.
Apart from countering the arguments of other schools of philosophy, ç
this work also tries to elucidate and syncretize thevarious views ç
within the Advaita philosophy itself.
It has four commentaries.
@NT = Siddh<193>nta·iroma<207>i
See <MS>BH°SKAR°C°RYA.<D>
@NT = siddhas
@N1 = (`the perfected ones')
The word siddha has been used in several senses. Literally, it means ç
anyone who has attained perfection.
The siddhas, like the gandharvas, are a group of demigods endowed ç
with certain miraculous powers.
Those of the human beings who have attained the a<218><219>asiddhis ç
(eight miraculous powers) (vide Yogas<220>tras 3.45), are called ç
siddhas.
Alchemists who tried to convert base metals into gold or transform ç
the internal body-chemistry to make an old body into a young one, ç
by the process known as k<193>yakalpa, were also called siddhas.
Some physicians who broke away from the traditional °yurveda and formed ç
the school of Siddha System of Medicine wherein only the products ç
of plants, roots and trees were used for preparing medicines, came ç
to be known as siddhas.
Some Tamil poets of the seventh and eighth centuries†like Tirum<220>lar ç
and <185>iva-vakkiyar†who were heterodox in their attitudes and rebels ç
against the hierarchy of the caste system were also known as the siddha(r)s.
@NT = Siddh<193>·rama
This is the place where V<193>mana (the fifth of the ten incarnations ç
of Vi<218><207>u) pushed the emperor Bali to the netherworld. Again ç
it was here that R<193>ma killed Sub<193>hu and drove away M<193>r<200>ca. ç
In course of time it became a place of tapas or austerities for sages ç
like Ka·yapa and Vi·v<193>mitra who established their hermitages here. ç
It has been identified with the modern town Buxar in Uttar Pradesh.
@NT = siddhis
@N1 = (`powers')
In general, the word siddhi indicates the fulfillment of any effort. ç
In a more technical sense, it stands for the supernatural powers gained ç
by s<193>dhanas (yogic exercises and spiritual practices).
The Yogas<220>tras (4.1) of Pata<210>jali (200 <MS>B.<|>C.<D>) states ç
that siddhis are attained by janma (birth), au<218>adhi (drugs), mantra ç
(sacred word), tapas (austerity) and sam<193>dhi (perfect concentration).
Eight siddhis, called a<218><219>asiddhis, are generally mentioned ç
by the treatises on yoga like the Yogas<220>tras (3.45) (See <MS>A<186><187>ASIDDHIS<D> ç
for details.). This work mentions several other siddhis also (from ç
2.35 up to 3.48).
A warning too is administered about their being obstacles in the path, ç
before realisation (vide 3.37).
@NT = <185>ikha<207><195>in
Amb<193>, the eldest daughter of the king of K<193>·<200>, was forcibly ç
taken away from the court during her svaya<221>vara (marriage by choice) ç
by Bh<200><218>ma, along with her twosisters Ambik<193> and Amb<193>lik<193>. ç
Since neither the king Saubha whom she had loved nor Bh<200><218>ma ç
who abducted her agreed to marry her, she vowed to kill Bh<200><218>ma ç
in her next birth. (See <MS>AMB°<D> for details.)
She was reborn as the daughter of the king Drupada but was brought ç
up as a son. Later, due to the grace of a yak<218>a, Sth<220><207><193>kar<207>a ç
by name, she became a man and was named <185>ikha<207><195>in.
Prince <185>ikha<207><195>in trained by Dro<207><193>-c<193>rya, became ç
a great warrior. He married the daughter of the king Hira<207>yavarma ç
of the country Da·<193>r<207>a and had two sons from her.
He fought the Kauravas on behalf of the P<193><207><195>avas. Since ç
Bh<200><218>ma, who knew the whole truth, refused to fight with him, ç
Arjuna kept him in front of himself and shot Bh<200><218>ma, who now ç
retired from the battlefield.
<185>ikha<207><195>in was killed by A·vatth<193>ma in sleep along ç
with the other warriors of the P<193><207><195>ava army, towards the ç
end of the Kuruk<218>etra war.
See also <MS>BH®<186>MA.<D>
@NT = ·ikhara
@N1 = (`that which has a top')
The words gopura, ·ikhara and vim<193>na are generally assumed to ç
be synonymous, but are not.
Gopura is the huge tower built over the entrance of big temples. Vim<193>na ç
is a small tower built over the garbhag<216>ha (sanctum sanctorum) ç
to indicate the place where the chief deity is installed. <185>ikhara ç
is the uppermost tapering part of the Vim<193>na. Over the ·ikhara ç
is built the <193>malaka (myroballan-shaped structure) capped by a ç
kala·a (finial).
See also <MS>GOPURA.<D>
@NT = Sikhism
@SB = Introduction
Whether Sikhism is a part of Hinduism as enunciated in the Constitution ç
of India (Article 25.2B; explanation 11) ora separate and independent ç
religion, depends on the way one looks at it.
If its acceptance of the theory of karma and rebirth, sa<221>s<193>ra ç
(transmigratory existence) and mukti (liberation) through j<210><193>na ç
(knowledge) and bhakti (devotion to God and faith in his grace) are ç
the criterion then it becomes a part of Hinduism.
If its rejection of the Vedic religion of sacrifices and rituals, ç
the vehement criticism of the caste system and denunciation of image ç
worship are given prominence, it can be considered as being outside ç
the pale of orthodox Hinduism.
It may be safer to assume that it is a vigorous reform movement against ç
thedegenerated forms of Hinduism that existed during its origin and ç
growth.
@SB = The Gurus
Guru N<193>nak (<MS>A.<|>D. <D>1469-1539) was the founder of Sikhism ç
(See <MS>N°NAK<D>, <MS>GURU<D> for details.) He was followed by a ç
succession of nine more Gurus, the pontifical tradition ending with ç
Guru Gobind Singh (<MS>A.<|>D.<D> 1666-1708), the tenth in the series.
@SPACE1 = 
Though each one of them contributed to the growth and success of the ç
Sikh movement, that of the last Guru was, by any standard, significant. ç
It was Guru Gobind Singh who transformed Sikhism into a dynamic religion ç
and the Sikhs into a race of warriors in defence of their dharma.
Again, it was he who terminated the Guru-tradition with himself as ç
the last Guru and declared that the Granth S<193>hib would hereafter ç
fill that place with all the respect due to the Guru and has to be ç
venerated as such.
@SB = Guru Granth S<193>hib
The Guru Granth S<193>hib is the Scripture of the Sikhs even as ç
the Vedas are for the Hindus, the Bible for the Christians and the ç
Qur<193>n for the Muslims. (See <MS>GRANTH S°HIB<D> for details.)
It was compiled by Guru Arjan Dev (<MS>A.D.<D> 1563-1606) in <MS>A.<|>D.<D> ç
1604 with the help of Bhai Gurudas.
It is also called °di Granth (the Original or the Primary Book).
The Da·am Granth is the secondary scripture containing the writings ç
of the tenth Guru, Gobind Singh. Some of its hymns are used in Sikh ç
worship.
@SB = Metaphysics
Sikhism accepts only one God. He can have two aspects: without attributes ç
(Nirgu<207>a) and with attributes (Sagu<207>a). The former is called ç
Ek-O<209>k<193>r and the latter, O<209>k<193>r.
In reality these two aspects are one and the same.
God endowed with his power of m<193>y<193> is the creator of this ç
universe. In this aspect, he is also called Parabrahma and ®·vara. ç
He is day<193>lu (kind) and k<216>p<193>lu (benevolent). Thus he becomes ç
an object of worship and devotion.
@SPACE1 = 
M<193>y<193> has the peculiar power of concealing God and give rise ç
to five evils which bind the human beings. They are: k<193>ma (lust), ç
krodha (anger), lobha (greed), moha (infatuation) and aha<209>k<193>ra ç
(egoism, pride).
Human beings can free themselves from these five evils only by the ç
grace of God.
According to Sikhism God does not incarnate himself in this world.
Other names used for God are: Satn<193>ma (Holy name), Kart<193>r ç
(Creator), Ak<193>l (Eternal), All<193>h, Khud<193> and Paravardig<193>r ç
(Cherisher). In later literature, Wahe-guru is also used as his name.
Man is an embodied soul. The soul is immortal but the body is not. ç
Man as the soul is like a spark from a blazing fire or like the water ç
of the ocean kept in a tumbler. Body is the greatest bondage. To get ç
mok<218>a or liberation he has to put an end to transmigration. Bondage ç
has been caused by the five evils stated above. When the divinity ç
in him makes him gurumukh (turn towards God) and prevents him from ç
becoming manmukh (turn towards the evils of the mind) and he surrenders ç
to the will of God, he is freed by His grace.
This world is a wonderful creation of God, his l<200>l<193> or sport. ç
It is real but dependent on him. Hence everyone has to perform his ç
duty properly, please God by it and win his release by His grace.
@SPACE1 = 
Man can realise God only with the help of a sadguru. To realise the ç
Nirgu<207>a aspect he has to follow the path of j<210><193>na consisting ç
of three steps: suniyai (=·rava<207>a) (listening to the guru); mannai ç
(= manana) (pondering over it); and dhy<193>na (= nididhy<193>sana) ç
(deep meditation).
To realise the Sagu<207>a aspect or ®·vara, the path of devotion has ç
to be adopted. Here n<193>masumirana (= n<193>ma-smara<207>a) or constant ç
utterance of God's name as also total surrender to him are the disciplines ç
recommended. Release comes by the grace of God which is his gift.
The released soul attains Sac-kha<207><195>, the eternal abode of ç
God and lives there happily.
The unreleased soul has to undergo countless rebirths according to ç
his karma.
@SPACE = 
@SPACE1 = 
@SPACE1 = 
@SB = Epilogue
@SPACE1 = 
It is thus seen that Sikhism and Hinduism have many things in common. ç
It is also a historical fact that the Sikhs have often fought for†and ç
even sacrificed their lives in defence of†Hinduism. Conse-quently, ç
the social relationship between the Sikhs and the Hindus is quite ç
close and intimate.
@SPACE = 
@NT = <185>ik<218><193>
@N1 = (`instruction [in phonetics]')
@SPACE = 
An understanding of the Vedas is quite a tough job, primarily due ç
to two factors: the archaic language and its phonetic system. That ç
is why a study of the six Ved<193><209>gas†subsidiary sciences that ç
help in understanding the Vedas†is often insisted upon while undertaking ç
a study of the Vedas.
@SPACE1 = 
The very first of the six Ved<193><209>gas is <185>ik<218><193>. Its ç
main purpose is to teach the correct pronunciation and intonation ç
of the Vedic mantras of the Sa<221>hit<193>s. One peculiar feature ç
of the Vedic mantras is that they are divided in several ways leading ç
to what are known as padap<193><219>ha, kramap<193><219>ha, ja<219><193>p<193><219>ha ç
and ghanap<193><219>ha (See <MS>GHANAP°<187>HA<D> for details.).
