Under the Va<219>av<216>k<218>a (banyan tree) there is a small <185>ivali<209>ga. ç
The local legends say that this is the original <185>ivali<209>ga ç
upon which the black cow of the princess Candr<193>vat<200> who was ç
living in that forest area at that time, used to empty her milk. The ç
princess built a small temple to house it, under instructions from ç
<185>iva himself.
Other attractions within the pr<193>k<193>ra are: the Sahasrali<209>ga ç
consisting of 1001 miniature li<209>gas, established by <185>r<200> ç
R<193>ma on his way back from La<209>k<193>; and five more li<209>gas ç
set up by the five P<193><207><195>ava princes in the inner courtyard.
The temple of Bhramar<193>mb<193> (P<193>rvat<200>) is outside the ç
pr<193>k<193>ra, above a flight of stairs.
A mirror hall to the right as one enters the gate and a beautiful ç
icon of Na<219>ar<193>ja are the other attractions.
There is an Um<193>mahe·vara temple, about 3 kms. north-west of the ç
Malli-k<193>rjuna temple, on the way to the P<193>t<193>laga<209>g<193>.
The main festival season is from February to the end of May, <185>ivar<193>tri ç
being the most important one.
The forest tribals known as Chenchus manage the temple through a ja<209>gama ç
priest.
<185>r<200>·ailam is a stronghold of the V<200>ra- ·aivas or Li<209>g<193>yats. ç
It houses one of the five original monasteries. The stone li<209>gas ç
worn on the body by them are picked up from the bed of the P<193>t<193>laga<209>g<193> ç
river.
@NT = <185>r<200>s<220>kta
@N1 = (`hymn devoted to <185>r<200> [or<R>ç
Lak<218>m<200>]')
The Vedas are the basic scriptures of Hinduism. They are defined as ç
those sacred texts which can show the human beings divine means of ç
getting what they want and getting rid of what they do not want.
A s<220>kta is a Vedic hymn devoted to a particular devat<193> or ç
deity.
Some of the well-known s<220>ktas which are commonly used in religious ç
rituals even today are: Agnis<220>kta, Bh<220>s<220>kta, Dev<200>s<220>kta, ç
Medh<193>s<220>kta, N<193>r<193>ya<207>as<220>kta, N<200><202><193>s<220>kta, ç
Puru<218>as<220>kta, <185>r<200>s<220>kta and Vi<218><207>us<220>kta.
Out of these the Puru<218>as<220>kta and the <185>r<200>s<220>kta ç
are much more popular and in constant use.
The <185>r<200>s<220>kta is the khila part of the <184>gveda appearing ç
after the 5th ma<207><195>ala. Those mantras of the Vedas for which ç
no viniyoga (utility) has been mentioned in the Kalpas<220>tras, ç
are technically called `khila'. (See also <MS>KHILA.<D>)
The <185>r<200>s<220>kta contains 15 <216>ks, the 16th stating its ç
use and utility in rituals.
@SPACE1 = 
Since it has been considered extremely important, several commentaries ç
have been written on the same by competent scholars from different ç
angles. Some of them are: °<207><195>avall<200>vy<193>khy<193>na, ç
Bh<193>gadheyabh<220><218>a<207>am, Cidvil<193>sav<216>tti, P<216>thv<200>dharabh<193><218>ya, ç
S<193>rasvatasiddhi, <185>at<193>nandav<216>tti, Saubh<193>gyasa<210>j<200>vanam, ç
S<193>ya<207>abh<193><218>ya<W1%18>,<MI%0><185>r<200>ka<207><219>habh<193><218>ya, ç
<185>r<200>s<220>kta- bh<193><218>ya (by Na<210>j<200>yar) and S<220>kt<193>rtha-sa<209>graha.
While these are direct commentaries on the <185>r<200>s<220>kta ç
itself, there are other works where some of the verses are referred ç
to and explained, mostly from thepractical aspects of worship. They ç
are: Mah<193>lak<218>m<200>ratnako·a, Mantrakalp<193>r<207>ava ç
and <185>r<200>vidy<193>vil<193>sa. They provide icono-graphic  details,  methods  of  drawing ç
yantras (mystic diagrams), prescriptions for p<220>j<193> (worship), ç
japa (recitation) and homa (oblations).
Though a part of the <184>gveda, the <185>r<200>s<220>kta has ç
been given an independent status. Its <216><218>i (seer) is Indra ç
or Lak<218>m<200> herself  or  her  four  sons†°nanda, Kardama, Cikl<200>ta ç
and <185>r<200>da or Indir<193>suta. The devat<193> (deity) is <185>r<200> ç
(Lak<218>m<200>). Or, <185>r<200>and J<193>tavedas (Agni, god of ç
fire) can be the deities. `J<193>tavedas' is sometimes interpreted ç
as N<193>r<193>ya<207>a also. The chandas (Vedic metre) is varied:
@IN2 = ·lokas 1 to 3 are in anu<218><219>ubh.<R>ç
·loka 4 is in b<216>hat<200>.<R>ç
·lokas 5 and 6 are in tri<218><219>ubh.<R>ç
·lokas 5 to 14 are in anu<218><219>ubh.<R>ç
·loka 15 is in prast<193>rapa<209>kti.
@SPACE1 = 
The viniyoga (utility) is to get the grace of Mah<193>lak<218>m<200> ç
as also dispelling the evil effects of Alak<218>m<200> (the deity ç
of misfortune).
The dhy<193>na·loka (hymn for contemplation) (amalakamalasa<221>sth<193> ç
etc.) describes her form thus: `She is seated on a pure lotus. Her ç
colour resembles that of the dust of the lotus. In her two hands she ç
is holding two lotuses whereas the other two hands are exhibiting ç
the gestures of boon-giving (varada) and protection (abh<200>ti or ç
fearlessness). There is a resplendent jewel-studded crown on her head. ç
She is wearing a garland of lotus flowers. May this Goddess, the Mother ç
ofthe universe, bring prosperity to us always!'
Sometimes karany<193>sa and a<209>gany<193>sa (ritual placements of ç
divine powers on one's limbs) are also given before the dhy<193>na·loka.
The ritualistic preliminaries given here are for the whole hymn.
Such processes have been described by the commentators separately ç
for each of the verses also.
Similarly a yantra (mystical diagram for worship or wearing on the ç
body) for the whole hymn and separate individual ones for each of ç
the verses have also been prescribed.
Now a summary of the whole s<220>kta can be attempted:
@S10 = Verse 1
O all knowing Agni! Please bring unto me the goddess of good-fortune, ç
who is of golden complexion, who is bright, who is wearing a garland ç
of flowers made of gold and silver, who like the moon, is bringing ç
joy and who is golden.
@S10 = Verse 2
O all-knowing Agni! Bring to me that Lak<218>m<200> (the goddess of ç
wealth and well-being) who will never leave me and on whose arrival ç
I will be able to possess gold, cows, horses, sons, grandsons as also ç
servants.
@S10 = Verse 3
As the procession of the Mother- goddess draws near, with horses ahead ç
and chariots in the centre, her arrival is proclaimed by the roar ç
of the elephants. I beseech the goddess to come near me. May she be ç
gracious unto me!
@S10 = Verse 4
I invoke that goddess who is Brahman the Absolute! She is smiling. ç
She is of the form of gold. She is cool, but brilliant. She is ever ç
content, but satisfies the desires of the devotees. She is seated ç
on a lotus and is of the same colour as that of the lotus.
@S10 = Verse 5
I take refuge in this goddess who is delightful like the moon, effulgent, ç
shining in all the worlds due to renowned qualities, who is being ç
served by gods (like Indra), who is generous, who is holding lotuses ç
in her hands and who is designated by the letter `<200>m'. I seek ç
your protection for the destruction of misfortune.
@S10 = Verse 6
O goddess who is brilliant like the sun! By your grace, the bilva ç
tree (Aegle marmelos) belonging to the vanaspati group (trees that ç
produce fruits without flowering) was produced. It was then that its ç
fruits attained celebrity by your grace. May they dispel the veil ç
of ignorance inside and destroy the misfortunes outside!
@S10 = Verse 7
May god Kubera, the friend of Mah<193>deva (<185>iva) along with fame ç
(or the goddess of fame) and the jewel called cint<193>ma<207>i, come ç
to me. Since I have been born in this world of men, may he (Kubera) ç
grant me celebrity and prosperity.
@S10 = Verse 8
O goddess <185>r<200>! I will destroy or drive away that deity of ç
misfortune (called Alak<218>m<200>) who comes in the form of hunger ç
and thirst. Please drive away all poverty and lack of prosperity from ç
my house.
@S10 = Verse 9
I invoke the presence here of <185>r<200>, the goddess of prosperity, ç
who is verily Bh<220> or the earth endowed with a peculiar aroma, ç
who is hard to damage, who is ever well-nourished, who has an abundance ç
of cattle and who is the ruler of all living beings.
@SPACE = 
@S10 = Verse 10
May I obtain by your grace, the desires of the mind, happiness, truthful ç
speech, wealth of cattle, abundant food and good name. May Lak<218>m<200>, ç
who is capable of all this, come to me.
@SPACE1 = 
@S10 = Verse 11
O Kardama! The goddess <185>r<200> has you for her son. Hence, kindly ç
show your grace to me by making your mother, the wearer of a garland ç
of lotuses, reside in my abode.
@SPACE1 = 
@S10 = Verse 12
May the deities presiding over the element water generate amiable ç
effects for me! O Cikl<200>ta! Come and dwell in my house. And, make ç
thy mother, the goddess of wealth and prosperity, to live in my household.
@SPACE1 = 
@S10 = Verse 13
O Agni! Bring unto me, Lak<218>m<200>, who is moist with compassion. ç
She is being bathed by two elephants. She is nourishing the worlds ç
of yellow hue, she is wearing a garland of lotuses. She is of pleasant ç
complexion like the moon. She is bedecked with golden ornaments. (Bring ç
her unto me!)
@SPACE1 = 
@S10 = Verse 14
O Agni! Bring unto me Lak<218>m<200>, the goddess who is cool, who ç
is holding the mace of righteousness, who is lustrous like gold, who ç
is wearing a garland of golden flowers, who is brilliant like the ç
sun and who is bedecked with golden ornaments.
@SPACE = 
@S10 = Verse 15
O Agni! Please bring unto me that Lak<218>m<200> who will never go ç
away from my home, by whose presence I will be able to obtain abundant ç
wealth, cattle, maids, horses, relatives and well-wishers†like sons, ç
friends and others.
There is a sixteenth mantra mentioned in the Nirukta of Y<193>ska, ç
which gives the phala·ruti, what one gets if he uses the hymn in the ç
prescribed ritualistic manner.
It is customary to chant another 18 ·lokas after reciting the <185>r<200>s<220>kta. ç
They are in simple classical Sanskrit and form a long hymn.
Besides this well-known <185>r<200>s<220>kta, there is another, ç
known as the Kashmir recension. It comprises 31 verses divided into ç
five groups.
As mentioned earlier each of the 15 verses has separate ritualistic ç
usage, the prescriptions being quite difficult and complicated.
The work Mantrakalp<193>r<207>ava gives all the details of religious ç
observances. The results projected may be summarised as follows:
@SPACE = 
@S10 = Verse 1
Wealth, health and long-life.
@SPACE = 
@S10 = Verse 2
Plenty of wealth in the form of gold, cows, sons and grandsons.
@S10 = Verse 3
If observed by a king, he will become invincible and attain great ç
wealth.
@S10 = Verse 4
Destruction of poverty and all types of wants.
@S10 = Verse 5
Attainment of wealth, honour by the king, victory in battles, going ç
to the world of moon after death.
@S10 = Verse 6
Destruction of sorrow and suffering.
@S10 = Verse 7
Vision of deities like Kubera, securing many kinds of gems and destruction ç
of evil spirits.
@S10 = Verse 8
Destruction of ignorance, sins, misfortune and diseases.
@S10 = Verse 9
Increase of agricultural produce, cattle and wealth, name and fame, ç
and power.
@S10 = Verse 10
Perfection of speech, attainment of wealth and all kinds of enjoyments.
@S10 = Verse 11
Continuity of the family lineage.
@S10 = Verse 12
Attainment of various kinds of food and other objects of enjoyment.
@S10 = Verses 13 and 14
Obtaining emperorship, control over others, name and fame.
@S10 = Verse 15
Victory over enemies, attainment of knowledge and wisdom as also kingship.
It is thus seen that this <185>r<200>s<220>kta has become a potent ç
means of s<193>dhana for attaining Lak<218>m<200>'s grace, both here ç
and hereafter.
@NT = <185>r<200>vai<218><207>ava
See <MS><185>R®VAI<186>ØAVISM.<D>
@NT = <185>r<200>vai<218><207>avism
@SB = Introduction
<185>r<200>vai<218><207>avism, the religion, and Vi·i<218><219><193>dvaita ç
Ved<193>nta, its philosophy, are of hoary antiquity. In his introductory ç
verse of <185>r<200>bh<193><218>ya (the commentary on the Brahma ç
S<220>tras), <185>r<200> R<193>m<193>nuja traces this philosophy ç
to the Upani<218>ads, which was well guarded by the later °c<193>ryas ç
like Vy<193>sa, Bodh<193>yana, <187>a<209>ka, Drami<195>a, Guhadeva, ç
Kapardin, Bh<193>ruci and others. According to the tradition that ç
obtains among the <185>r<200>vai<218><207>avas, the religion of <185>r<200>vai<218><207>avism ç
was first taught by the Lord N<193>r<193>ya<207>a himself to Lak<218>m<200>, ç
his divine Consort, who communicated the same to Vi<218>vaksena. From ç
him it was handed over to a series of teachers headed by <185>a<219>hagopa.
@SB = The °<202>v<193>rs
°<202>v<193>rs are <185>r<200>vai<218><207>ava saints of the Tamil ç
country who lived between the sixthand the ninth centuries <MS>A.<|>D.<D> ç
The word `°<202>v<193>r' literally means one who is immersed in divine ç
love. They are twelvein number: Poygai, P<220>dam, Pey, Tirumo<202>i·ai, ç
Namm<193><202>v<193>r, Kula·ekhara, Periy<193><202>v<193>r, To<207><195>ara<195>ippo<195>i, ç
Tiruma<209>gai, Tirupp<193><207>, Madhurakavi, and °<207><195><193><202>. ç
Theirs was a religion of ecstatic love for God. Hence, neither caste ç
nor sex was any barrier to their attaining to that state.
Coming to the historical times, it wasthese °<202>v<193>rs who first ç
propagated thereligion and the philosophy of <185>r<200>vai<218><207>avism ç
through their songs. These songs, called the N<193>l<193>yira Prabandham, ç
combine in themselves rare poetic beauty and high philosophical tenets, ç
couched in a simple language.
Namm<193><202>v<193>r, the author of the famous Tiruv<193>imo<202>i, ç
is by far the greatest among them. He is called the K<220><219>astha ç
by the later°c<193>ryas of <185>r<200>vai<218><207>avism, because ç
the fundamental doctrines of this faith as current today, were taught ç
by him.
@SB = The °c<193>ry<193>s
The °<202>v<193>r movement was more emotional in nature than metaphysical. ç
The °<202>v<193>rs were great devotees of the Lord Vi<218><207>u. ç
They believed in the impermanence of worldly enjoyments and in the ç
acquisition of liberation by union with Him. They taught more by example ç
than by precept, though they propagated the philosophy of Vi·i<218><219><193>dvaita ç
in their songs.
Hence it was left to the °c<193>ryas beginning with N<193>thamuni, ç
who succeeded the °<202>v<193>rs, to put the system on a firm footing, ç
basing it both upon the Sanskrit scriptures and the Tamil teachings ç
of the °<202>v<193>rs. The °c<193>ryas were very orthodox br<193>hma<207>as, ç
well-versed equally in Sanskrit and Tamil, who passed through thedifferent ç
stages of orthodox life and discharged their duties so as to serve ç
asan ideal for theirfollowers. Apart from expounding the philosophy ç
of Vi·i<218><219><193>dvaita, they also laid down various rules for ç
theproper observance of festivals, fasts, vows and customs. They ç
were thus the makers of modern <185>r<200>vai<218><207>avism. It is ç
not surprising, therefore, that they in turn have become objects ofworship ç
like the °<202>v<193>rs whom they themselves apotheosized.
The first of the °c<193>ryas was Ra<209>gan<193>thamuni, popularly ç
known as N<193>thamuni (<MS>A.<|>D.<D> 824-924). He was at once an ç
erudite scholar, a yogin, and a devotee. It was he who first collected ç
all the Prabandhams, edited them with proper introductory verses, ç
popularized them by setting them to music, and made them sung in temples. ç
It was, again, he who gave these Prabandhams the status equal to ç
that of the Vedas in temple festivals. The various reforms brought ç
about by N<193>thamuni necessitated the creation of a post of a universal ç
°c<193>rya whose authority was lawin religious worship and whose ç
advice was a guide to temples and house-holders. It was but natural ç
that when such a post was established, the choice should fall on N<193>thamuni ç
himself. Since this office was combined with the management of the ç
<185>r<200>ra<209>gam temple, it was easy for the °c<193>ryas to revolutionize ç
and reorganize the <185>r<200>vai<218><207>ava cult by introducing ç
the necessary reforms first in that temple, which is one of the most ç
important shrines of Vi<218><207>u and a stronghold of <185>r<200>vai<218><207>avism.
@SPACE1 = 
N<193>thamuni was succeeded by Pu<207><195>ar<200>k<193>k<218>a and ç
R<193>mami·ra for two short periods. Then came Y<193>mun<193>c<193>rya ç
(<MS>A.D.<D> 918-1038), who was the grandson of N<193>thamuni himself. ç
It was he who, endowed with great scholarship and insight, first attempted ç
to put the Vi·i<218><219><193>dvaita philosophy on a firm foundation. ç
He wrote scholarly works in Sanskrit defending it, and established ç
the orthodoxy of the P<193><210>car<193>tra school, whose authority ç
is accepted as equal to that of the <185>rutis bythe Vi·i<218><219><193>dvaitins. ç
Siddhitraya and °gamapr<193>m<193><207>ya are his two important ç
works, in addition to the G<200>t<193>rtha-sa<209>graha. It was ç
his cherished desire to write a commentary on the Brahmas<220>tras ç
according to the Vi·i<218><219><193>dvaita, just as<185>a<209>kara ç
had done according to the Advaita. But he died before he could attempt ç
it, and it fell on R<193>m<193>nuja to achieve it.
@SB = R<193>m<193>nuja <M>(<P8>A.<|>D.<P255> 1017-1137)<D>
The name of R<193>m<193>nuja is inseparably associated with the Vi·i<218><219><193>dvaita, ç
just as <185>a<209>kara's is with the Advaita. The traditional date ç
of his birth is <MS>A.D.<D> 1017, and he is said to have lived for ç
120 years. Y<193>muna died before R<193>m<193>nuja became the °c<193>rya, ç
and the interval was filled up by Mah<193>p<220>r<207>a.
Y<193>muna bequeathed to R<193>m<193>nuja the three great tasks of ç
his life which he himself had failed to achieve, viz., the perpetuation ç
of the memory of the sage Par<193>·ara, the immortalization of the ç
glory of Namm<193><202>v<193>r, and the interpretation of B<193>dar<193>ya<207>a's ç
Brahmas<220>tras according tothe Vi·i<218><219><193>dvaita system. ç
R<193>m<193>nuja fulfilled all these three in his lifetime. He commanded ç
Bha<219><219>a, the son of K<220>re·a, to write a commentary on the ç
Vi<218><207>usahasra-n<193>ma, and named him as Par<193>·ara. He ç
authorized Kuruke·a, the son of his uncle <185>r<200>·ailap<220>r<207>a, ç
to compose a commentary on the Tiruv<193>imo<202>i of Namm<193><202>v<193>r.
To achieve the third object, R<193>m<193>nuja had to undertake an ç
arduous journey to Kashmir, where the last surviving copy of the V<216>tti ç
of Bodh<193>yana, a commentary on the Brahmas<220>tras was available. ç
After going through it with great difficulty, hecomposed his <185>r<200>bh<193><218>ya, ç
a masterly commentary on the Brahmas<220>tras.
R<193>m<193>nuja was as great an organizer as he was a thinker. He ç
divided the <185>r<200>vai<218><207>ava world into seventy-four °c<193>ryic ç
dioceses, over each of which he appointed a pious householder as the ç
head or `si<221>h<193>san<193>dhipati' as he was called. These spiritual ç
leaders earnestly took up the work of carrying the message of Vi·i<218><219><193>dvaita ç
to all the villages and homes, each within his diocese.
@SPACE1 = 
@SB = Split in <185>r<200>vai<218><207>ava Ranks
@SPACE1 = 
The demise of R<193>m<193>nuja was followed by a period of sectarian ç
split among the <185>r<200>vai<218><207>avas, which ultimately ended ç
in the permanent division of their ranks into the two sects of Va<195>agalais ç
and Te<209>galais. These words literally mean the followers of the ç
northern and the southern schools respectively. The two sects developed ç
separate sets of works, separate lineage of gurus, and separate traditions ç
in many matters of practical importance.
The language of the holy books to be studied, the comparative importance ç
of bhakti and prapatti (self-surrender) in the path of liberation, ç
relation with the lower castes, details of certain ceremonials to ç
be observed on certain special occasions, and a few other questions ç
were the causesfor such a division. The Va<195>agalais favoured the ç
Sanskrit works and the path of bhakti, and were more conservative ç
in their relation towards the lower castes. The Te<209>galais, on ç
the other hand, preferred the Tamil works to the Sanskrit ones, and ç
laid greater stress on prapatti based on the m<193>rj<193>laki·orany<193>ya ç
(the maxim of the kitten totally dependent on its mother) than on ç
the marka<219>aki·ora-ny<193>ya (the maxim of the young one of the ç
monkey which clings to its mother). Theformer assumes self-effort ç
as a prerequisite to prapatti whereas the latter does not.
Though there has never been a check to interdining, intermarriage, ç
and free social harmony at home or at the temple, the allegiance to ç
different teachers and philosophies, as also the scramble for control ç
over the temples, has perpetuated this division.
@SPACE = 
@SB = Apostolic Successors of R<193>m<193>nuja
@SPACE = 
The two sects have a different guru-parampar<193> (succession of teachers) ç
though both trace their origin to R<193>m<193>nuja himself. Kuruke·a ç
was the first successor of R<193>m<193>nuja according to the Va<195>agalais. ç
Vi<218><207>ucitta, his successor, is the author of two famous works ç
S<193>r<193>rthacatu<218><219>aya and Vi<218><207>ucitt<200>yam ç
(a commentary on the Vi<218><207>upur<193><207>a). The next in line ç
is Varad<193>rya or Varad<193>c<193>rya, otherwise known as Na<195><193>d<220>r ç
Amm<193><202>. A substance of his lectures and interpretations of ç
the <185>r<200>bh<193><218>ya was committed to writing under the ç
title of <185>rutaprak<193>·ik<193> by a talented disciple of his, ç
named Sudar·anas<220>ri.
After the death of Varad<193>rya, the °c<193>ryaship devolved on °treya ç
R<193>m<193>nuja, who in turn was succeeded by Ved<193>nta De·ika ç
or Ve<209>ka<219>an<193>tha.
@SB = Ved<193>nta De·ika<M> (<P8>A.<|>D.<P255> 1268-1370)<D>
Ved<193>nta De·ika, who was a contemporary of Vidy<193>ra<207>ya, ç
is undoubtedly the greatest of the °c<193>ry<193>s of the post R<193>m<193>nuja ç
period. For more than three quarters of a century, he enriched the ç
<185>r<200>vai<218><207>ava world with his teachings and writings. ç
His works number more than a hundred, and are characterized by versatility, ç
beauty of style and thought, and a deep spiritual insight. He was ç
a poet, a philosopher, a thinker, a polemist, and a sage, all rolled ç
into<|><|>one. His works includeoriginal writings in Tamil,as also ç
commentaries on older works. G<200>t<193>bh<193><218>ya-t<193>tparyacandrik<193>, ç
bh<193><218>ya on the ®·<193>-v<193>syopani<218>ad, Tattva<219><200>k<193>, ç
Adhikara<207>a- s<193>r<193>val<200>, Ny<193>yasiddha<210>jana, Saccaritra-rak<218><193>, ç
Rahasyatrayas<193>ra, and Ha<221>sa- sande·a are only a few of ç
the important works which may be mentioned here. It is not a matter ç
of surprise that he was called in his own times as `Kavit<193>rkika-si<221>ha.' ç
One of the greatest of his services was his saving the <185>rutaprak<193>·ik<193> ç
fromthe chaos that followed in the wakeof invasion of <185>r<200>ra<209>gam ç
by the Mohammedans. It is for this reason that his name as Ved<193>nt<193>c<193>rya ç
is gratefully remembered by all the <185>r<200>vai<218><207>avas, ç
without sectarian bias, in beginning the study of the <185>r<200>bh<193><218>ya.
@SB = Pi<202><202>ai Lok<193>c<193>rya <M>(<P8>A.<|>D. <P255>1264-1327)<D>
The Te<209>galai sect traces the apostle ship in succession of R<193>m<193>nuja ç
in the following manner: Emb<193>r, Par<193>·ara Bha<219><219>a, Na<210>j<200>yar ç
(the famous commentator of the Prabandham), Nampillai, K<216><218><207>a-p<193>da, ç
Pi<202><202>ai Lok<193>c<193>rya, Tirumalai °<202>v<193>r, Ma<207>av<193><202>a ç
M<193>muni (or Varavaramuni). Among these, Pi<202><202>ai Lok<193>c<193>rya, ç
who was a contemporary of Ved<193>nta De·ika, occupies the same place ç
amidst the Te<209>galais as De·ika does among the Va<195>agalais. ç
In fact, he is generally regarded as the founder of Te<209>galaism ç
as a distinct sect. Being a man of brilliant intellect, he composed ç
several treatises in order to uphold his school. Vacanabh<220><218>a<207>a ç
is a difficult work in aphoristic style which deals with the doctrine ç
of prapatti in all its aspects. For the benefit of women and the common ç
folk, Lok<193>c<193>rya composed sixteen treatises on the secret doctrines ç
and the philosophy of <185>r<200>vai<218><207>avism like Nigamanappa<195>i, ç
Mumuk<218>uppa<195>i, Tattvatraya, Arthapa<210>caka, etc. Though ç
most of these works are small in size, they are regarded by the Te<209>galai ç
school as the only correct interpretation of the cults of R<193>m<193>nuja ç
and the °<202>v<193>rs.
@SPACE = 
@SB = Ma<207>av<193><202>a M<193>muni <M>(<P8>A.<|>D.<P255> 1370-1443)
@SPACE = 
Pi<202><202>ai Lok<193>c<193>rya was succeeded by <185>r<200>·aile·a, ç
who in turn handed over the °c<193>ryaship to Ma<207>av<193><202>a ç
M<193>muni, also known as A<202>agiya Ma<207>av<193><202>a or Varavaramuni. ç
He was a master of the Tamil Veda and other lore. Though he was trained ç
by the teachers of the Va<195>agalai sect also, he openly declared ç
that ®<195>u (the commentary by K<216><218><207>ap<193>da on the ç
Tamil Veda) was the equal of <185>r<200>bh<193><218>ya. He wrote ç
several works explaining the treatises of Pi<202><202>ai Lok<193>c<193>rya. ç
Though his works were limited in range and diction, he gave a definite ç
form to Te<209>galaism. His magnetic personality elevated him in the ç
eyes of his followers to the position of an incarnation of R<193>m<193>nuja.
@SB = <185>r<200>vai<218><207>avism in Practice
Everyone  born  in  a  <185>r<200>vai<218><207>ava family must approach ç
a proper guru and undergo what is called pa<210>casa<221>sk<193>ra, ç
if he is to be considered a true <185>r<200>vai<218><207>ava. This ç
five-fold ritual includes tapas or the°c<193>rya's initiating the ç
student into the sacred fire by branding the latter's shoulders with ç
the symbols of Vi<218><207>u; the pu<207><195>ra or initiating into ç
wearing the sectarian mark, the symbol of the Lord'sfoot; giving ç
a spiritual name like N<193>r<193>ya<207>ad<193>sa or Govindad<193>sa ç
to the disciple; imparting the three mantras. viz., the a<218><219><193>k<218>ar<200>, ç
the dvaya, and the carama-·loka; and handing over a ·<193>lagr<193>ma ç
or other concrete objects for daily worship.
Though in theory this pa<210>casa<221>sk<193>ra is enough to secure ç
the devotee's entry into the blissful world of Lord Vi<218><207>u, ç
in practice he finds that his past karma and present weaknesses are ç
serious obstacles to spiritual progress. He is thus forced to realise ç
that the Lord's grace is absolutely necessary, and therefore surrenders ç
himself at his feet. This is technically called `prapatti' or `·ara<207><193>gati,' ç
and the devotee who does it is known as a `prapanna.'
The prapanna is again, in need of a mediator, since he is unable to ç
communicate with the Lord directly. Therefore, he has to go to a teacher ç
and beg him to intercede on his behalf and place his soul at the Lord's ç
feet. This vicarious employment of the teacher is technically designated ç
as `bh<193>rany<193>sa.'
@SB = <185>r<200>vai<218><207>ava Ma<219>has
The evolution and consolidation of <185>r<200>vai<218><207>avism as ç
a cult is closely associated with the origin and development of the ç
<185>r<200>vai<218><207>ava Ma<219>has or monasteries. From the most ç
ancient times, <193>·ramas and ma<219>has in India have been the repositories ç
of religion in theory and practice. Their heads, whether monks or ç
pious householders, have been responsible for arresting the decay ç
of dharma and forpropagating true religion, apart from guiding the ç
society often in secular matters also. The same holds good in the ç
case of the <185>r<200>vai<218><207>ava Ma<219>has too. Ahobila Ma<219>ha, ç
Parak<193>la Ma<219>ha, Yadugiri Yatir<193>ja Ma<219>ha, °<207><195>avan ç
Ma<219>ha and V<193>nam<193>malai Ma<219>ha†these are some of the ç
important ma<219>has of <185>r<200>vai<218><207>avism.
The Ahobila Ma<219>ha was founded in the year <MS>A.D.<D> 1398, in ç
the Ahobila Kshetra of Andhra Pradesh, by <185>r<200>niv<193>s<193>c<193>rya, ç
who became a sa<221>ny<193>sin under the name of °di Va<207>a <185>a<219>hagopa ç
Sv<193>min. He was a great scholar and lived as a sa<221>ny<193>sin ç
for the full length of sixty-years. The successive Jeers or abbots ç
of the Ma<219>ha have kept up the tradition of erudition and of touring ç
the country to spread religion.
According  to  the  tradition  that obtains at the Parak<193>la Ma<219>ha ç
in Mysore (Karnataka), its founder was Ved<193>nta De·ika himself. ç
His disciple, Periya Brahmatantra Svatantra Sv<193>min, occupied the ç
p<200><219>ha or pontifical seat in <MS>A. D.<D> 1360. So far there ç
have been thirty-three Jeers (abbots). The principal deity worshipped ç
in the Ma<219>ha is Hayagr<200>va, which has been handed down to the ç
Ma<219>ha from Ved<193>nta De·ika himself.
@SPACE1 = 
Yadugiri is a small hill, about 48 kms. (30 miles) to the east of ç
Mysore. It is claimed that R<193>m<193>nuja himself established a ç
ma<219>ha here during <MS>A.<|>D.<D> 1103. This Ma<219>ha, known as ç
Yadugiri Yatir<193>ja Ma<219>ha, had a branch at Rewa (in Madhya Pradesh), ç
which is now functioning independently. Some of the Jeers of this ç
Ma<219>ha had kept contacts with North India also.
The °<207><195>avan Ma<219>ha, better known as ``<185>r<200>ra<209>gam ç
°<207><195>avan °·rama,'' has its main centre at <185>r<200>ra<209>gam ç
in Tamil Nadu. Ved<193>nta R<193>m<193>nuja De·ika is the founder ç
of this Ma<219>ha, the youngest among the <185>r<200>vai<218><207>ava ç
Ma<219>has. It was started in early nineteenth century. The present ç
head is the seventh in the apostolic succession.
V<193>nam<193>malai Ma<219>ha was established at Nangunderi, Tirunelveli ç
District, Tamil Nadu, by Ma<207>av<193><202>a M<193>muni during the ç
fourteenth century <MS>A.<|>D.<D> So far there have been twenty-seven ç
Jeers.
@SB = The Philosophy of Vi·i<218><219><193>dvaita
Any account of the history of <185>r<200>vai<218><207>avism should ç
be deemed incomplete without a description of its philosophical tenets. ç
As has already been pointed out, this philosophy is much older than ç
R<193>m<193>nuja, who only systematized it. However, the pioneering ç
and yet stupendous work he has turned out in the cause of Vi·i<218><219><193>dvaita ç
has justified its being called R<193>m<193>nuja Dar·ana. Vi·i<218><219><193>dvaita ç
is essentially a philosophy of religion. In it, reason and faith coalesce ç
to become `reasoned faith.' It is often identified with the older ç
Se·vara M<200>m<193><221>s<193>, and is also called Ubhaya Ved<193>nta, ç
since it accepts both the Sanskrit Prasth<193>natraya and the Tamil ç
Prabandham as equally authoritative. P<193><210>car<193>tra treatises ç
are also put on a par with the Vedas.
See <MS>VI<185>I<186><187>°DVAITA VEDANTA DAR<185>ANA<D> for details.
@SB = Conclusion
@SPACE = 
Thus <185>r<200>vai<218><207>avism, with its Philo-sophy of Vi·i<218><219><193>dvaita ç
Ved<193>nta and the great stress laid on bhakti and prapatti, has ç
made the path of spiritual evolution a little more easy for the ordinary ç
s<193>dhakas or spiritual aspirants. It has also contributed to social ç
harmony, at least among its own ranks.
@SPACE = 
@NT = <185>r<200>vidy<193>
@N1 = (`sacred or auspicious<R>ç
knowledge')
@SPACE = 
If God can be conceived as the Father in Heaven, why not as the Mother ç
too? Human psychology being what it is, God has been approached ç
or adored as the Divine Mother also, not only in ancient India, but ç
also in many other countries (See <MS>DEV®.<D>).
One of the cults of the worship of Dev<200> or the Divine Mother is ç
the <185>r<200>vidy<193>. Literally, it means sacred or auspicious ç
knowledge and is the same, for all practical purposes, as the Brahmavidy<193> ç
of the Upani<218>ads.
In a more technical sense, it meansup<193>san<193> or the spiritual ç
discipline connected with meditation and worship of the Divine Mother ç
in her aspect as Lalit<193>- Tripurasundar<200>. The four mantras ç
connected with it are also known by the same name.
They are: the G<193>yatr<200>mantra; the pa<210>cada·<193>k<218>ar<200>mantra; ç
the <218>o<195>a·<193>k<218>ar<200>-mantra;  and  the  b<193>l<193>tripurasundar<200>- ç
mantra.
Even among these, it is the pa<210>ca-da·<193>k<218>ar<200>mantra ç
(mantra of 15 letters) that is particularly called `<185>r<200>vidy<193>'.
