The breaking of a compound word (with intonation marks) into the constituents ç
of a padap<193><219>ha depends entirely on the chanting marks like ç
ud<193>tta, anud<193>tta and svarita (See <MS>ANUD°TTA<D> for details.). ç
Different notes on the same compound word can lead to different ways ç
of breaking it and hence different meanings! An oft-quoted example ç
in this regard is the wrong intonation of the word indra·atru<199> ç
by Tva<218><219><193> (the father of V<216>tr<193>sura). As a result, ç
the word used in the oblation of offerings into the consecrated fire ç
meant `one to whom Indra is an enemy,' instead of the one intended, ç
viz., `one who is an enemy of Indra'.
This Ved<193><209>ga is very ancient. Its subject matter is found ç
in some of the Br<193>hma<207>as and the Upani<218>ads also.
In the Taittir<200>ya Upani<218>ad (1.2) it has been referred to ç
briefly. This science of <185>ik<218><193> has six parts: var<207>a ç
(letter of the alphabet); svara (pitch or intonation); m<193>tr<193> ç
(syllabic instant or measure of time); bala (stress or emphasis); ç
s<193>ma (medium mode of pronunciation); and, sant<193>na (juxtaposition ç
or combination).
@SPACE1 = 
The var<207>as or letters of the Sanskrit alphabet are 63 or 64 according ç
to the <185>ik<218><193>, taking the three svaras (ud<193>tta etc.) ç
into consideration.
M<193>tr<193> refers to the three kinds oftime duration: hrasva (one ç
syllabic instant); d<200>rgha (two syllabic instants); and pluta (three ç
syllabic instants).
Bala (stress applies to the place of production of the sound of the ç
alphabet by the flow of air and the effort needed, both external and ç
internal. There are further subdivisions in these.
S<193>ma (medium mode of pronunciation) should produce faultless and ç
sweet pronunciation.
Sant<193>na is the same as uniting two words as per the rules of sandhi, ç
described in the works on grammar.
The extant <185>ik<218><193> works are:
@IN2 = P<193><207>in<200>ya <185>ik<218><193> on the <184>gveda ç
and<R>ç
   the Yajurveda;
@IN2 = Vy<193>sa <185>ik<218><193> for the K<216><218><207>a Yajurveda;
@IN2 = Y<193>j<210>navalkya <185>ik<218><193> for the<R>ç
   <185>ukla Yajurveda;
@IN2 = N<193>rad<200>ya <185>ik<218><193> for the S<193>maveda;
@IN2 = M<193><207><195><220>k<200>ya <185>ik<218><193> for the<R>ç
   Atharvaveda.
Recently 32 works on <185>ik<218>a have been procured from various ç
sources and printed.
See also <MS>PR°TI<185>AKHYA.<D>
@NT = <185>ilappa<195>ik<193>ram
@N1 = (`the jewelled anklet')
This is an epic poem in Tamil considered equal in literary quality ç
to the R<193>m<193>ya<207>a of Kamban (12th century <MS>A.<|>D.<D>). ç
Assigned to the 5th century <MS>A.<|>D.<D> it was composed by I<202>a<209>kova<219>ika<202>. ç
Nothing is known about him except that he was a prince of the country ç
of Cera (comprising parts of the present Tamil Nadu and Kerala).
The epic poem describes the story of Ka<207><207>agi and her husband ç
Kovilan. After living happily with his beautiful wife Ka<207><207>agi, ç
Kovilan fell in love with a dancer M<193>dhav<200> and so deserted ç
his legally wedded wife. After wasting all his wealth with the dancer, ç
Kovilan returned to his wife Ka<207><207>agi who received him warmly.
Since they were very poor now, Kovilan took one of the two jewelled ç
anklets of Ka<207><207>agi (which was their only possession now) to ç
the market in the capital city of Madurai, to sell. Meanwhile the ç
queen of Ne<195>u<210>jeliyan (the king of P<193><207><195>yan dynasty) ç
had lost one of her anklets and the soldiers were searching for the ç
thief. When they saw Kovilan trying to sell his anklet, they mistook ç
him for the thief and killed him. When Ka<207><207>agi learnt of the ç
tragedy she went to the kingand accused him of murdering her husband. ç
Out of shock, the king died on the spot!
Ka<207><207>agi cursed the city of Madurai which was now engulfed ç
in fire and then killed herself.
The goddess M<200>n<193>k<218><200> of Madurai, however, saved the ç
city from total destruction.
Ka<207><207>agi was deified and became the patron deity of the city ç
of Madurai.
@NT = <185>ilpa·<193>stra
@N1 = (`science of dexterous crafts and industries')
@SB = Introduction
Vedic  sacrificial  religion  clearly demonstrates how advanced the ç
ancient Hindus were in pure sciences like mathematics as also applied ç
sciences like the building of y<193>ga·<193>l<193>s (sacrificial sheds) ç
and rathas (carts and chariots).
Apart from the Vedas, the basic scriptures of Hinduism, it is interesting ç
to note that any organised body of know-ledge is also called a Veda ç
since Veda in general, means knowledge. One such Veda †considered ç
rather as an Upaveda or subsidiary Veda†is the Sth<193>patyaveda. ç
It is the Veda concerned with the sthapati (chief architect or master-builder).
Its other names, more commonly used, are: <185>ilpa·<193>stra, <185>ilpavidy<193>, ç
V<193>stu-·ilpa and V<193>stuvidy<193>.
@SB = Original Teachers
Hindu mythical tradition ascribes this science to eighteen teachers ç
of whom Vi·vakarma and Maya, the well-known architects of devas or ç
gods and asuras or demons, stand out as supreme.
Some of the others mentioned are: Bh<216>gu, Atri, Vasi<218><219>ha, ç
N<193>rada, Brahm<193>, Kum<193>ra and B<216>haspati.
@SB = Basic Treatises and Literature
The treatises on this subject are legion. Only a few of them may be ç
mentioned here: Abhila<218>it<193>rthacint<193>ma<207>i, A<221>·ubodhin<200>, ç
A<221>·umadbhed<193>gama, B<216>hatsa<221>hit<193>, K<193>·yapa·ilpa, ç
M<193>nas<193>ra, Mayamata·ilpa·<193>tra, Samar<193><209>ga<207>as<220>tra-dh<193>ra ç
and V<193>sturatn<193>val<200>.
The Artha·<193>stra of Kau<219>ilya (320 <MS>B.C.<D>), some pur<193><207>as ç
like the Agnipur<193><207>a, Matsyapur<193><207>a, Padmapur<193><207>a, ç
and the Vi<218><207>udharmottarapur<193><207>a also contain a lot ç
of material on this subject.
@SB = Four Divisions
The <185>ilpa·<193>stra is a very vast body of science and technology, ç
arts and crafts.
It is generally divided into four sections, each dealing with a different ç
areaof subject. They are: Dhar<193> (earth); Harmya (buildings); ç
Y<193>na (vehicles) and Parya<209>ka (bedsteads).
These four may now be dealt with separately, but briefly.
@S10 = Dhar<193>
Dhar<193> means the earth. This section deals with the testing of ç
a soil in various ways to determine whether it is fit for building ç
what is intended, such as a village or a town, with the necessary ç
structures. Town-planning, surveying and marking are also included.
Several types of designs of towns and cities are mentioned.
@SPACE = 
@S10 = Harmya
@SPACE = 
Harmya is the general name for a building. Several types of it are ç
mentioned such as pr<193>s<193>da (palace or temple), ma<207><195>apa ç
(open hall), sabh<193> (auditorium), ·<193>l<193> (stable or stall) ç
and ra<209>ga (pavilion) apart from private dwellings. Details of ç
standard bricks and stones, mortars, and methods of arranging the ç
bricks and stones are also given. It is interesting to note that the ç
ancient architects knew how to prepare a strong and superior kind ç
of cement called vajralepa.
Buildings with several storeys have also been described.
Palaces  of  several  varieties  too, depending upon the status of ç
the king, are mentioned in detail.
Works on building construction frequently use four technical terms ç
as applied to the builders†the engineers and the craftsmen†which may ç
be cited here. They are: the sthapati (the chief architect who is ç
an expert in all aspects of construction);<R>ç
the s<220>tragr<193>hi (the surveyor who is an expert in the art of ç
measuring); the vardhaki (the painter); and the tak<218>aka (the carpenter ç
and the sculptor).
@SPACE = 
@S10 = Y<193>na
@SPACE = 
Y<193>na  stands  for  any  mode  of transport.
Various types of carts and carriages (·aka<219>as), chariots (rathas) ç
and palanquins (·ibik<193>s) have been mentioned in these treatises. ç
Details of designs helpful in making them are also given.
Rathas are constructed for ceremonial or ordinary drives of idols, ç
br<193>hma<207>as or kings, as also for fighting purposes. They are ç
therefore, of several varieties and shapes.
@S10 = Parya<209>ka
Though this word literally means a cot for sleeping, several types ç
of furniture (like thrones and chairs), ornaments (likecrowns, bangles ç
and necklaces), and household articles are also included in this section.
@SB = Epilogue
The discovery of the Indus Valley Civilisation (2500 <MS>B.<|>C.<D>) ç
which is now considered to be a later phase of the Vedic civilisation, ç
has conclusively proved that the Hindus knew the science and art of ç
town-planning very well. Gorgeous descriptions of the cities and the ç
palaces of Ayodhy<193> and La<209>k<193> in the R<193>m<193>ya<207>a ç
or of the royal mansion of the P<193><207><195>avas at Indraprastha ç
in the Mah<193>bh<193>rata are pointers to the high degree of the ç
advanced state of the contemporary society even after allowing for ç
poetical exaggerations.
The construction of altars for Vedic sacrifices involving complicated ç
designs based on the geometrical science is also a pointer to a highly ç
evolved technology mastered by the Vedic °ryans.
From the frequent mention of missiles like the Brahm<193>stra and ç
the Vim<193>nas orflying carrier vehicles†including the fantastic ç
Pu<218>pakavim<193>na†in the pur<193><207>as, we can surmise that ç
our ancient fore- fathers either had a high degree of civilisation ç
or at least high ambitions which they considered as not impossible ç
of achievement.
It should also be noted that quite a few of the <193>gamas and the ç
pur<193><207>as whose origins might be traced to the pre- Christian ç
era, deal extensively with the sciences involving town-planning, architecture, ç
construction of various types of buildings and other structures as ç
also chariots and images.
From all these materials available, it may be concluded that <185>ilpa·<193>stra ç
was a well-developed field of science and technology even from the ç
earliest period of our history.
See also <MS>M<188>RTI<185>ILPA<185>°STRA<D> and <MS>HIND<188> TEMPLES<D>.
@SPACE = 
@NT = s<200>mantonnayana
@N1 = (`parting of the hair [of a pregnant woman] upwards')
@SPACE = 
This is the third of the sixteen sa<221>sk<193>ras, generally known ç
as <186>o<195>a·a-sa<221>sk<193>ras. It is a ritual act performed ç
on a pregnant woman by her husband to protect the baby in the womb ç
from evil spirits and confer a long life on it.
The earliest reference to it is in the Mantra Br<193>hma<207>a (1.5.2) ç
of the S<193>ma-veda. Several G<216>hyas<220>tras also deal with ç
it in greater detail.
The rite is to be performed during the fourth or the fifth month of ç
pregnancy.
Since it is considered a purificatory rite of the mother, it is enough ç
if it is performed during the first pregnancy only.
The following are the steps of the rite: M<193>t<216>k<193>p<220>jana ç
(worship of the seven Mother-goddesses like Br<193>hm<200>, M<193>he·var<200> ç
etc.); N<193>nd<200>·r<193>ddha; oblations to Praj<193>pati; parting ç
of the hair of the pregnant woman upwards by her husband using a ç
bunch of unripe udumbara (fig tree) fruits, darbha-grass (Poa cynosuroides) ç
and porcupines quill and a stick of v<200>ratara wood (or Bilva); ç
playing on a lute and so on.
Then some duties were prescribed for the pregnant woman and her husband. ç
They were aimed at protecting her from evil influences and over-exertion. ç
Others were calculated to preserve her physical and mental health. ç
The husband was advised to fulfil all her wishes, as also avoid taking ç
part in rituals or processions connected with death and ·r<193>ddha.
See also <MS><186>O£A<185>ASA<189>SK°RAS.
@SPACE = 
@NT = si<221>h<193>sana
@N1 = (`lion-seat')
@SPACE = 
The lion is generally considered the king or the monarch of the forest, ç
the animal kingdom. Hence it became a symbol of royalty.
The throne of a monarch is usually decorated with figures of lions ç
on either side of the seat as arm-rests. The four legs of the throne ç
may also be shown as resting on crouching lions. Hence it is called ç
si<221>h<193>sana.
The M<193>nas<193>ra (55.1-112), a famous ancient  work  on  Hindu  Architecture, ç
divides the si<221>h<193>sanas into four classes: prathama, ma<209>gala, ç
v<200>ra and vijaya. These four are used successively by the same ç
king during coronation.
Deities in temples also have si<221>h<193>-sanas. The one used for ç
daily worship is called nity<193>rcana-si<221>h<193>sana. The vi·e<218>a-si<221>h<193>sana ç
is used on special occasions.
The thrones in general are sometimes divided into ten kinds such as ç
padm<193>sana, ·r<200>bhadra, ·r<200>mukha and so on.
Though various kinds of si<221>h<193>sanas have been described, the ç
most beautiful one may be chosen for the king or the deity.
@NT = sin
See <MS>P°TAKA.<D>
@NT = Sindhu
The name of the river Sindhu (the modern Indus river) appears many ç
times in the <184>gveda. According to the pur<193><207>as it is ç
a branch of the heavenly river Ga<209>g<193>. When Ga<209>g<193> fell ç
into the lake Bindu from heaven, it broke into seven branches, oneof ç
which was Sindhu, which flowed towards the west. A bath in this river ç
was supposed to take one to heaven.
Sindhu was also the name of a country. Jayadratha was its king during ç
the period of the Mah<193>bh<193>rata.
The country of Sindhu was famous for its robust and fine horses.
Sindhu also means the sea.
@NT = sin<200>v<193>l<200>
See <MS>AM°V°SYA.<D>
@NT = ·i·nadevas
@N1 = (`those who considered the<R>ç
phallus as their deity')
This word occurs in the <184>gveda twice (7.21.5; 10.99.3). Though ç
its literal meaning refers to people who consider the ·i·na (= phallus) ç
as deva (= deity), S<193>ya<207>a interprets it as people who are ç
lecherous. They were to be kept out of the cultured and decent society.
@NT = ·i·<219>as; ·i<218><219><193>c<193>ra
A ·i<218><219>a is one who is well-trained in moral and ethical behaviour ç
as described in the ·<193>stras or scriptures. The code of conduct ç
prescribed for him is ·i<218><219><193>c<193>ra. It comprises the ç
following virtues: satya (truth), tapas (austerity), d<193>na (giving ç
giftsto the needy), alobha (absence of greed), vidy<193> (learning), ç
ijy<193> (performing sacrifices), p<220>jana (worshipping gods and ç
elders) and dama (self-control).
Other virtues mentioned in the workson dharma are: absence of jealousy ç
and  egoism;  freedom  from  hypocrisy, arrogance, delusion and anger; ç
acquisition of Vedic wisdom as per the norms set by tradition.
<185>i<218><219><193>c<193>ra is also a source of dharma.
@NT = <185>i·um<193>ra
Dhruva, the child prince, secured for himself, the boon of ruling ç
over his father's kingdom here and also a celestial region after death, ç
by pleasing Vi<218><207>u through his austerities and devotion.
This celestial region comprising an assemblage of luminaries as a ç
formation in the shape of <185>i·um<193>ra (an alligator) is called ç
<185>i·um<193>ra or <185>i·um<193>racakra. It houses its master Dhruva ç
in its tail-region. Dhruva moves the entire region, himself also moving ç
with it.
Vi<218><207>u or N<193>r<193>ya<207>a is the support of the whole ç
system.
Gazing at this formation every night with a specific prayer will free ç
one from all the sins committed during the day. He will also attain ç
a long life (vide Vi<218><207>upur<193><207>a 2.9 and 12; Bh<193>gavata ç
5.23).
@NT = <185>i·up<193>la
One of the villains depicted in the Mah<193>bh<193>rata, <185>i·up<193>la ç
was the son of Damagho<218>a (the king of Cedi) and <185>ruta-·rav<193> ç
(sister of Kunt<200>). He was born with four hands and three eyes. ç
A voice from the void declared that he, in whose lapthe child will ç
lose its extra limbs, will ultimately be its killer. When this happened ç
in K<216><218><207>a's lap, <185>ruta·rav<193> begged K<216><218><207>a ç
to forgive him a hundred times. K<216><218><207>a consented.
When <185>i·up<193>la ascended the throne of the kingdom of Cedi, ç
he proved to be a great tyrant and womaniser.
During the R<193>jas<220>ya sacrifice, he abused K<216><218><207>a ç
right and left. K<216><218><207>a forgave his abuses upto a hundred ç
times and then killed him with his Sudar·ana discus.
He was the third incarnation of Jaya (gatekeeper of Vaiku<207><219>ha) ç
who had been cursed by the four sages (Sanaka and his brothers). Hira<207>yaka·ipu ç
and R<193>va<207>a were his earlier incarnations.
@NT = ·i<218>ya
@N1 = (`one who is fit to be trained')
Hinduism prescribes special qualifications, both for the guru (the ç
teacher) and for the ·i<218>ya (the disciple) in every field of knowledge.
One of the most general descriptions prescribes the following as the ç
basic and minimum qualification: peaceful nature, humility, purity ç
of mind, faith in the guru,capacity to absorb and retain the knowledge ç
taught by him, efficiency, birth in a good family, intelligence, good ç
conduct and the ability to repay the debt to the guru in some form.
According to other sources, an intense desire to learn, inquisitive ç
nature and service to the guru are other qualifications expected in ç
a ·i<218>ya.
See <MS>GURU<D> also.
@NT = S<200>t<193>
See <MS>R°M°YAØA.<D>
@NT = <185><200>tal<193>
Almost every village in India houses a folk-goddess, generally at ç
the entrance to it. This goddess will be a protectress if appeased ç
and a scourge if displeased.
One such is <185><200>tal<193> (a minor form of Dev<200>) who is common ç
in North India, especially in Bengal. She is the deity of smallpox. ç
She is generally worshipped in a crude stone with a painted human ç
face. She can cure smallpox if pleased or bring it on if displeased.
T<193>ntrik works describe her as black-complexioned, two-armed and ç
naked, riding on a donkey. She wears a winnowing basket on her head ç
and holds in her two hands a broom and a pot of water.
A variant form of hers is described as red-complexioned, three-eyed ç
and four-armed. In these four arms, she carries a skull-cup, hand-drum, ç
spear and sword. Her hair resembles a blazing fire and she is seated ç
on a lotus.
In South India, she is worshipped as M<193>riyamma. Other forms are ç
°-i of Assam and <187>h<193>kur<193>n<200> in Orissa.
@NT = <185>iva
@N1 = (`the auspicious one')
<185>iva is the last deity of the Hindu Trinity. He is responsible ç
for the dissolution of the universe. He is the embodiment of Tamas, ç
the centrifugal inertia, the tendency towards dispersion and annihilation.
Literally, <185>iva is one in whom the Universe `sleeps' after destruction, ç
till the next cycle of creation.
All that is born, must die. All that is produced, must disintegrate ç
and be destroyed. This is an inviolable law. The principle that brings ç
about this disintegration, the power behind this destruction, is <185>iva.
<185>iva  is  much  more  than  that. Disintegration of the universe ç
ends in the ultimate thinning out, into a boundless void. This boundless ç
void, the substratum of all existence, from which springs out again ç
and again this apparently limitless universe, is <185>iva. So, though ç
<185>iva is described as responsible for destruction, he is equally ç
responsible for creation and existence. In this sense, Brahm<193> ç
and Vi<218><207>u are also <185>iva. It is perhaps this identity that ç
is revealed by some of the stories in the pur<193><207>as. If one ç
story makes <185>iva speak from the womb of the infinite pillar of ç
fire to Brahm<193> and Vi<218><207>u that they are his own aspects, ç
other stories make <185>iva as being born from the brows of an angry ç
Vi<218><207>u or from Brahm<193> who was intensely desiring to beget ç
a son.
Though <185>iva is often called Rudra, especially in his terrific ç
aspect, whether the two are identical or not has been a subject of ç
discussion and even controversy. Some scholars are inclined to think ç
that the Rudra of the Vedas and the <185>iva of the pur<193><207>as ç
and <193>gamas are two different deities fused into one at a later ç
date as cultural integration of the two races accepting them progressed. ç
According to these scholars <185>iva the pacific deity is a non-°ryan ç
god, `more ancient' than theVedic Rudra. Though the `°ryan conquerors' ç
despised and derided the <185>aivas and their <185>iva (apparently ç
because of some of their mysterious rituals and practices), as the ç
two races had to live together, rapprochement and consequent cultural ç
reconciliation became inevitable.
Whatever may be the conjecture behind these statements they are irrelevant ç
to our study here, since we are more interested in discovering the ç
significance of the symbology concerned, to enrich our lives.
<185>iva  is  worshipped  both  in  the anthropomorphic aspect and ç
as the li<209>ga, the latter being the rule whereas the former is ç
an exception. The most common of his pictures and images shows him ç
as a very handsome youth, white as camphor. His limbs besmeared with ç
ashes are strong and smooth. He has three eyes†the third eye being ç
on the forehead between the eyebrows†and four arms, two of the arms ç
holding the tri·<220>la (trident) and <195>amaru (drum) while the ç
other two are in the abhaya (protection-giving) and varada (boon-giving) ç
mudr<193>s (poses). He has a crown of long matted hair from which ç
flows the river Ga<209>g<193>. He also wears the crescent moon as ç
a diadem. A tiger-skin and an elephant-skin adorn his body as his ç
garments. There are serpents all over his body forming the necklace, ç
the girdle, the yaj<210>opav<200>ta (sacred thread) as also arm-bracelets. ç
There is also a garland of skulls round his blue neck.
Man, being what he is, cannot help superimposing his own states on ç
his gods too! Therefore it is but natural for him to conceive of <185>iva ç
as a man with family. P<193>rvat<200> is his consort. Ga<207>e·a and ç
Kum<193>ra (the latter also known as Skanda or Subrahma<207>ya) are ç
his sons.
@SPACE1 = 
Then there is the large retinue forming a veritable zoo as it were! ç
Nandi his vehicle bull, Bh<216><209>gi the <216><218>i with three ç
legs and three arms, the mouse of Ga<207>e·a, the peacock of Kum<193>ra ç
as also a host of ghosts, goblins and imps constantly capering round ç
him†form his large retinue.
Though he has his headquarters in the icy mountains, the Him<193>layas, ç
he is fond of roaming the earth, especially the burial grounds and ç
cremation sites. All this is in perfect consonance with his nature ç
as the Lord of destruction and dissolution.
Before embarking upon the explanation of all this, which is obviously ç
symbolical, it is better to summarise first the various stories about ç
<185>iva recounted in our mythological literature:
@SPACE1 = 
1.<+>Once P<193>rvat<200>, in a playful mood, closed his two eyes, ç
and lo! the entire world was plunged into darkness. To save the worlds ç
from this predicament, <185>iva willed a third eye in between his ç
eyebrows, sending forth light, fire and heat. Later on, he opened ç
this third eye†normally kept closed out of infinite mercy for humanity†to ç
burn up K<193>madeva, the lord of lust.
2.<+>When the celestial river Ga<209>g<193>, which was descending from ç
the heaven to this earth, fell ferociously on <185>iva's head out ç
of pride, he just got her locked up there! Only after much prayer ç
and supplication by Bhag<200>ratha (who was responsible for bringing ç
the celestial river down to this earth) and due apologies by Ga<209>g<193>, ç
did he allow her to stream out.
3.<+>When the K<218><200>rasamudra, the ocean of milk, was being churned, ç
one of the objects to rise was the cool crescent moon. <185>iva seized ç
it and made it his diadem. When the deadly poison H<193>l<193>hala ç
also rose and started destroying the worlds with its leaping tongues ç
of fire, <185>iva gathered it on to his palm and drank it, thus saving ç
the worlds. P<193>rvat<200>, getting alarmed about the safety of her ç
spouse, pressed his throat so that the poison could not go down into ç
the stomach! It thus remained in his throat, lending its blue colour ç
permanently to it.
4.<+>Being angered by <185>iva whose extraordinary beauty had attracted ç
their wives, the <184><218>is of D<193>rukavana tried to kill him ç
through sorcerous rituals. Out of the sacrificial fire rose a tiger, ç
a deer and a red-hot iron. <185>iva killed the tiger and wore its ç
skin, caught hold of the deer with his left hand (which has remained ç
there ever since) and made the iron one of this weapons.
5.<+>Other stories relate to his destroying the sacrifice of Dak<218>a, ç
his cutting off of one of the five heads of Brahm<193> for having ç
spoken disrespectfully, his destroying the three cities built by the ç
demon Tripur<193>sura,  his  killing  the  elephant demon Gaj<193>sura ç
and wearing his hide, his having granted to Arjuna as a boon the weapon ç
P<193>·upat<193>stra, his having become Ardhan<193>r<200>·vara to ç
dispel the ignorance of his devotee Bh<216><209>gi, his appearing ç
as a pillar of fire to teach a lesson to Brahm<193> and Vi<218><207>u, ç
his vanquishing Yama, the god of death, to save his votary M<193>rka<207><195>eya, ç
and so on.
@SPACE1 = 
An attempt can now be made to unravel this mysterious symbology of ç
the <185>iva-picture. <185>iva is snow-white in colour, which matches ç
wonderfully with that of his abode, the Him<193>layas. White stands ç
for light that dispels darkness, knowledge that dispels ignorance. ç
He is the very personification of cosmic consciousness. It may appear ç
strange that <185>iva who represents Tamas (the force of darkness ç
and destruction) is pictured as white, whereas Vi<218><207>u who represents ç
Sattva (the force of light and enlightenment) is pictured as dark! ç
There is nothing strange in this since the opposing Gu<207>as are ç
inseparable. Hence <185>iva is white outside and dark inside whereas ç
Vi<218><207>u is the reverse of it.
The three eyes of <185>iva represent the sun, the moon and the fire, ç
the three sources of light, life and heat. The third eye can also ç
indicate the eye of knowledge and wisdom and hence his omniscience.
If the sun and the moon form his two eyes as it were, then the whole ç
sky including the powerful wind blowing in it, forms his hair. That ç
is why he is called Vyomake·a (one who has the sky or space as his ç
hair).
Tiger is a ferocious animal that mercilessly devours its hapless victims. ç
Desire, which consumes human beings, without ever being satiated, ç
can be compared to a tiger. That <185>iva has killed the tiger and ç
wears its skin as his apparel shows his complete mastery over desire.
The elephant being a powerful animal, wearing its skin implies that ç
<185>iva has completely subjugated all animal impulses.
The garland of skulls (mu<207><195>am<193>l<193>) that he wears and ç
the ashes of the funeral pyre with which he has besmeared his body ç
indicate that he is the lord of destruction. The garland of skulls ç
also represents the revolution of ages and successive appearance and ç
disappearance of the human races.
@SPACE1 = 
<185>iva is the lord of yoga and yogis. He is often shown as sitting ç
in deep meditation immersed in the enjoyment of the bliss of his own ç
self. The water of the river Ga<209>g<193> represents this. Or it ç
can represent j<210><193>na, knowledge. Since Ga<209>g<193> is highly ç
adored as a great purifying agent, it goes without saying that he ç
whom it adorns, is the very personification of purifying or redeeming ç
power.
The crescent moon stands for time, since measurement of time as days ç
or months depends upon the waxing and waning of the moon. By wearing ç
it as a diadem, <185>iva is showing us that even the all-powerful ç
time is only an ornament for him!
And then, the snakes. The venomous cobras which symbolise death for ç
us adorn his frame in all possible manner embellishing it further. ç
He alone, to whom symbol of death is a decoration, can gulp down the ç
deadly poison H<193>l<193>hala to save the worlds. All this points ç
to one thing: He is M<216>tyu<210>jaya, the conqueror of death! Coiled ç
serpents may also represent cycles of time in the macrocosm and the ç
basic energy†akin to sexual energy†of living beings in the microcosm. ç
So, <185>iva is the master of time and energy.
@SPACE1 = 
Iconographically <185>iva may have two, three, four, eight, ten or ç
even thirty-two hands. Some of the various objects shown in these ç
hands are: tri·<220>la (trident), cakra (discus), para·u (battle axe), ç
<195>amaru (drum), ak<218>am<193>l<193> (rosary), m<216>ga (deer), ç
p<193>·a (noose), da<207><195>a (staff), pin<193>ka or ajagava (bow), ç
kha<219>v<193><207>ga (magic wand), p<193>·upata (spear), padma (lotus), ç
kap<193>la (skull-cup), darpa<207>a (mirror), kha<195>ga (sword) and ç
so on. It is rather difficult to find a meaning for everyone of these ç
items. However an attempt will be made to explain some of them.
The  tri·<220>la  (trident)  being  an important weapon of offence ç
and defence, indicates that <185>iva is the supreme ruler. Philosophically ç
it can stand for the three gu<207>as or the three processes of creation, ç
preservation and dissolution. Hence <185>iva the wielder of the trident ç
is the master of the gu<207>as and from him proceed the cosmic processes.
It is said that while dancing the t<193><207><195>avan<216>tya, <185>iva ç
sounded his <195>amaru (small drum) fourteen times, thereby producing ç
sounds like a-i-u<207>, r-l<216>-k and soon, which are now known ç
as the M<193>he·vara-s<220>tras, the fourteen basic formulae containing ç
all of the alphabet arranged in the most ingenious manner, facilitating ç
innumerable grammatical processes. Hence the <195>amaru represents ç
the alphabet, grammar (the science of language) or language itself. ç
In other words it stands for all words†spoken or written or other-wise ç
expressed†and hence for the entire gamut of all arts and sciences, ç
sacred and secular. It also represents sound as such, the logos, from ç
which the entire creation has proceeded. By holding it in his hand, ç
<185>iva is demonstrating the fact that the entire creation, including ç
its various arts and sciences, has proceeded out of his will, his ç
play.
@SPACE1 = 
If the ak<218>am<193>l<193> (rosary) shows that he is the master of ç
spiritual sciences, the kha<219>v<193><209>ga (magic wand with a skull ç
fixed at one end) shows that he is an adept in occult sciences too. ç
The kap<193>la (skull-cup) with which he drinks blood, is another ç
symbol that points to his all-destroying power. The darpa<207>a (mirror) ç
indicates that the entire creation is just a reflection of his cosmic ç
form.
The icon of <185>iva is never worshipped as the m<220>lam<220>rti ç
(original, installed in the sanctum sanctorum), but only as an utsavam<220>rti ç
(the icon used during festivals for taking out in a procession).
@SPACE = 
@S10N = <185>IVALI<177>GA
@SPACE = 
As regards the li<209>ga, the emblem of <185>iva universally venerated, ç
some explanation is needed. Literally <185>iva means auspiciousness ç
and Li<209>ga means a sign or symbol. Hence the `<185>ivali<209>ga' ç
is just a symbol of the great God of the universe (`Mah<193>deva') ç
who is all-auspiciousness. As already explained, `<185>iva' means ç
the one in whom the whole creation sleeps after dissolution. `Li<209>ga' ç
also means the same thing†aplace where created objects get dissolved ç
during the disintegration of thecreated universe. Since, according ç
to Hinduism, it is the same God that creates, sustains and destroys ç
the universe, the <185>ivali<209>ga represents symbolically God Himself.
Whether the <185>ivali<209>ga is a phallic emblem or not, is a moot ç
point. Phallic cults have existed in all countries and in all civilizations. ç
It is quite likely that the phallic cults of an aboriginal civilization ç
were absorbed into Hinduism and the worship itself was elevated to ç
honour the Father-Mother-Principle of creation. This is one view. ç
That it is a remnant of the Vedic y<220>pastambha, to which sacrificial ç
victims used to be tied, is another view. According to this view, ç
the Hindu temple is a metamorphosis of the Vedic y<193>ga·<193>l<193> ç
(sacrificial shed). That it is an imitationof the Buddhist st<220>pa ç
is another guess that is sometimes hazarded but not substantiated, ç
since <185>ivali<209>gas have been found even in the pre-Buddhistic ç
civilization of Harappa and Mohenjo Daro.
Since God is beyond name and form, and since we cannot conceive of ç
an abstract principle like Him, without the aid of concrete symbols, ç
a rounded surface is perhaps the nearest approach to him.
<185>ivali<209>gas may be cala (movable) or acala (immovable). The ç
cala-li<209>gas may be kept in the shrine of one's own home for worship ç
or prepared temporarily with materials like clay or dough etc., for ç
worship and dispensed with after the worship or worn on the body as ç
i<218><219>ali<209>ga as the V<200>ra·aivas do. The acala-li<209>gas ç
are those installed in temples. They are usually made of stone and ç
have three parts. The lowest part which is square, is called Brahmabh<193>ga ç
and represents Brahm<193>, the creator. The middle part which is octagonal, ç
is called Vi<218><207>u-bh<193>ga and represents Vi<218><207>u, the ç
sustainer. Thesetwo parts are embedded inside the pedestal. The Rudrabh<193>ga ç
which is cylindrical and projects outside the pedestal is the one ç
to which worship is offered. Hence it is called p<220>j<193>bh<193>ga.
The p<220>j<193>bh<193>ga also contains certain lines technically ç
called Brahmas<220>tra, without which the Li<209>ga becomes unfit ç
for worship.
@S10N = ASPECTS OF LORD <185>IVA
@SPACE1 = 
Comparable to the Vy<220>has or emanations of Lord Vi<218><207>u, ç
is the Pa<210>c<193>nana form of Lord <185>iva. Pa<210>c<193>nana ç
or the five-faced one, represents the five aspects of <185>iva vis-a-vis ç
the created universe. Thefive faces are respectively ®·<193>na, Tatpuru<218>a, ç
Aghora, V<193>madeva and Sadyoj<193>ta. The face ®·<193>na, turned ç
towards the zenith, represents the highest aspect and is also called ç
Sad<193>·iva. On the physical plane, it represents the power that ç
rules over ether or sky and on the spiritual plane, it is the deity ç
that grants Mok<218>a or liberation. Tatpuru<218>a facing east, stands ç
for the power that rules over air and represents the forces of darkness ç
and obscuration on the spiritual plane. Aghora, facing south and ruling ç
over the element fire, stands for the power that absorbs and renovates ç
the universe. V<193>madeva facing north, ruling over the element water, ç
is responsible for preservation. Sadyoj<193>ta, facing west represents ç
the power that creates.
Iconographically, these five aspects are shown in different ways.
There are several other aspects in which Lord <185>iva is depicted ç
or worshipped. They can be broadly divided into the following  categories:  ç
1)  Saumya  or Anugraham<220>rti; 2) Ugra, Raudra or Sa<221>h<193>ram<220>rtis; ç
3) N<216>tta or T<193><207><195>ava m<220>rti; 4) Dak<218>i<207><193>m<220>rti; ç
5) Li<209>godbhava-m<220>rti; 6) Bhik<218><193><219>anam<220>rti; ç
7) Haryardha-m<220>rti; 8) Ardhan<193>r<200>·varam<220>rti.
The peaceful form of <185>iva as also the form showing mercy and grace ç
belong to the first group. The forms showing grace or granting boons ç
to Ca<207><195>e·a, Nand<200>·vara, Vighne·vara or R<193>va<207>a ç
belong to this category.
@SPACE1 = 
All terrific aspects can be classed under the second group. Ka<209>k<193>la ç
Bhairava represents <185>iva who cut off the fifth head of Brahm<193> ç
for having reviled him and who had to wander as a beggar for twelve ç
years to get rid of that sin. Gaj<193>sura- vadham<220>rti represents ç
him as killing the demon N<200>la (an associate of Andhak<193>sura) ç
who had assumed the form of an elephant. Tripur<193>ntakam<220>rti ç
depicts him as destroying by his arrow, the three cities of iron, ç
silver and gold built on the earth, in air and in heaven by the three ç
sons of Andhak<193>sura who had become almost invincible because of ç
these three impregnable shelters. <185>arabhe·am<220>rti pictures ç
<185>iva as a <185>arabha (an imaginary animal more ferocious than ç
the lion) destroying the Narasi<221>ha form of Vi<218><207>u, a story ç
obviously conceived by the <185>aivites to assert the superiority ç
of their Lord overVi<218><207>u! K<193>l<193>rim<220>rti portrays ç
him as vanquishing Yama, the god of death, whowanted to take away ç
the life of M<193>rka<207><195>eya, a great devotee of <185>iva. K<193>m<193>ntakam<220>rti  ç
illustrates  him  as destroying K<193>ma, the god of lust, by thefire ç
emitted through his third eye. Andhak<193>suravadham<220>rti shows ç
him as vanquishing Andhak<193>sura and later on, on supplication, ç
conferring on him the commandership  of  the  ga<207>as (dwarf attendants). ç
Andhaka became Bh<216><209>g<200>·a.
@SPACE1 = 
Lord <185>iva is a great master of dance. All the 108 modes of dancing ç
known to the treatises on dancing have come from him. It is said that ç
he dances every evening in order to relieve the sufferings of creatures ç
and entertain the gods who gather in Kail<193>sa in full strength. ç
(Hence he is called Sabh<193>pati, the lord of the congregation.)
Only nine modes of dancing are described of which the Na<219>ar<193>ja ç
aspect is the most well-known. The Na<219>ar<193>ja icon shows him ç
with four hands and two legs, in the posture of dancing. There is ç
the <195>amaru (drum) in the upper right hand and fire in the left. ç
The lower right hand is in abhayamudr<193> (pose of protection) and ç
the left is pointing towards the uplifted left foot. The left foot ç
is resting on the demon Apasm<193>rapuru<218>a. The whole image may ç
or may not be surrounded by a circle of blazing fire.
<185>iva's dance indicates a continuous process  of  creation,  preservation  and ç
destruction. The <195>amaru represents the principle of ·abda (sound) ç
and hence <193>k<193>·a (ether), which proceeds immediately from the ç
<193>tman and is responsible for further creation or evolution. Fire ç
represents pralay<193>gni, the fire that destroys the world at the ç
time of dissolution of the world, and hence symbolises the process ç
of destruction. Thus <195>amaru and fire represent the continuous ç
cycle of creation, preservation and destruction. The other two hands ç
indicate that he who takes refuge at the feet of the Lord will have ç
nothing to fear. The Apasm<193>rapuru<218>a (apasm<193>ra = epilepsy) ç
symbolises ignorance which makes us lose our balance and consciousness. ç
He is trampled upon by the Lord for the good of the devotees who take ç
refuge.
Several other dancing postures of <185>iva like °nanda-t<193><207><195>avam<220>rti, ç
Um<193>-t<193><207><195>avam<220>rti, Tripura-t<193><207><195>avam<220>rti, ç
and <188>rdhva-t<193><207><195>avam<220>rti are also mentioned in ç
the <193>gamas.
@SPACE1 = 
<185>iva is as great a master of yoga and spiritual sciences as he ç
is of music, dancing and other arts. As a universal teacher he is ç
called Dak<218>i<207><193>m<220>rti. Since <185>iva was seated facing ç
south (dak<218>i<207>a = south) when he taught the sages in a secluded ç
spot on the Him<193>layas, he is called Dak<218>i<207><193>m<220>rti. ç
He has three eyes and four arms and one of the legs is trampling upon ç
the Apasm<193>rapuru<218>a. Two of the arms (the front right and the ç
front left) are in j<210><193>namudra and varadamudra poses (showing ç
the imparting of knowledge and bestowing of gifts). The back hands ç
hold the ak<218>am<193>la (rosary) and, either fire or serpent. He ç
is the very model of theperfect Guru. He is surrounded by several ç
<216><218>is eager to learn <193>tmavidy<193> (Self-knowledge) from ç
him.
<185>iva is said to have appeared as a blazing pillar of fire, of ç
immeasurable size, to destroy the pride of Brahm<193> and Vi<218><207>u. ç
Li<209>godhbavam<220>rti depicts him as manifesting in the heart of ç
the li<209>ga. The image has four arms. Brahm<193> and Vi<218><207>u ç
stand on either side adoring him.
The Bhik<218><193><219>anam<220>rti shows <185>iva as a naked Bhairava ç
begging his food in the skull cup. It is almost the same as the Ka<209>k<193>lam<220>rti.
The Haryardham<220>rti, also called as Harihara and <185>a<209>karan<193>r<193>ya<207>a, ç
has <185>iva on the right half and Vi<218><207>u on the left. A fusion ç
of these two aspects into one godis an obvious attempt at a happy ç
reconciliation of the warring cults of <185>iva and Vi<218><207>u.
The Ardhan<193>r<200>·vara (half man and half woman) form which P<193>rvat<200> ç
as the left half represents the bipolar nature of the created world ç
and hence the need to look upon woman as equal and complementary to ç
man.
@S10N = MINOR DEITIES ASSOCIATED WITH <185>IVA
There can be no <185>iva temple without Nandi, the recumbent bull ç
placed in front of the shrine. Nandi or Nandike·vara may be depicted ç
exactly like <185>iva†with three eyes and two hands holding the para·u ç
(battle axe) and m<216>ga (the antelope). But the other two hands ç
are joined together in the a<210>jali pose (obeisance). More commonly ç
he is shown as a bull-faced human being or just as a bull.
The pur<193><207>as describe him as born out of the right side of ç
Vi<218><207>u resembling <185>iva exactly and given as a son to thesage ç
S<193>la<209>k<193>yana who had practised severe austerities. Other ç
versions describe him as the son of the sage <185>il<193>da who got ç
him by the grace of <185>iva.
Nandike·vara,   also   known   as Adhik<193>ranandi, is the head of ç
the ga<207>as of <185>iva and also his v<193>hana (carrier vehicle).
Symbolically, the bull represents the animal instincts, especially ç
the sex, and <185>iva's riding on it reflects his absolute mastery ç
over it.
Then comes Bh<216><209>gi, the sage, who was singularly devoted to ç
Lord <185>iva, and was elevated to the retinue of <185>iva's abode. ç
The sage was so fanatical in his devotion to <185>iva that he did ç
not care even for P<193>rvat<200>, his consort! When P<193>rvat<200> ç
merged herself into the body of <185>iva and <185>iva thus became ç
Ardhan<193>r<200>·vara, Bh<216><209>gi was still so bigoted that he ç
became a Bh<216><209>ga (= bee) and bored through the centre of the ç
Ardhan<193>r<200>·vara form to complete his circumambulation! Hence ç
the name Bh<216><209>gi. <185>iva, of course, made him realise his ç
mistake.
@SPACE1 = 
V<200>rabhadra is another deity associated with <185>iva. He is the ç
personification of <185>iva's anger manifested during Dak<218>a's ç
sacrifice because of the contemptuous treatment meted out to him. ç
<185>iva is said to have created him out of a hair plucked out from ç
his head. V<200>rabhadra successfully destroyed Dak<218>a's sacrifice ç
and humiliated all the gods who had assembled there. He is usually ç
shown with three eyes and four arms holding bow, arrow, sword and ç
mace. He wears a garland of skulls. The face isterrific. Bhadrak<193>l<200>, ç
his counterpart created by P<193>rvat<200>, is sometimes shown by ç
his side. <185>iva temples may have a small shrine dedicated to him, ç
located usually in the south-east.
Next comes Ca<207><195>e·vara, a human devotee raised to the status ç
of a deity by Lord <185>iva because of his intense devotion. He is ç
a fierce deity holding weapons of war and destruction like the bow, ç
arrow, trident, chisel, noose and so on. Though independent shrines ç
dedicated to him are not uncommon, he is usually installed in every ç
<185>iva temple in the north-eastern corner, facing south. Devotees ç
believe that he can act as a messenger and mediator interceding with ç
the Lord on behalf of the devotees. Hence supplication before him ç
is a duty of every devotee visiting the <185>iva temples.
Other attendants of <185>iva are the ga<207>as, also known as pramathaga<207>as ç
orbh<220>taga<207>as (demigods or malignant spirits). If they are ç
not propitiated, they can do harm.
@NT = <185>ivadharmapur<193><207>a
It is an upapur<193><207>a included in the list of eighteen upapur<193><207>as. ç
It has been called a ·<193>stra (scriptural treatise) by the Bhavi<218>yapur<193><207>a ç
thereby getting some status of importance.
It is a short work of twelve chapters in which Nandike·vara reports ç
to Sanatkum<193>ra what <185>iva had taught to P<193>rvat<200> and ç
Subrahma<207>ya. It is a pro-Vedic P<193>·upata work assigned to the ç
period <MS>A.D.<D> 200-500.
The topics dealt with are, briefly, as follows: origin and worship ç
of the <185>ivali<209>ga; construction of <185>iva temples; offer ç
of tri·ulas (tridents) and other things to him; giving gifts to please ç
him; fasting on days dear to him; duties of his worshippers and so ç
on.
It is critical of Vedic sacrifices but praises various acts of service ç
to <185>iva.
Several dharma·<193>stra writers like Deva<207><207>abha<219><219>a ç
(12th century <MS>A.<|>D.<D>) and Hem<193>dri (13th century <MS>A.<|>D.<D>) ç
quote from this upapur<193><207>a.
@NT = <185>ivadharmottarapur<193><207>a
Classed among the upapur<193><207>as, it is another P<193>·upata work ç
with pro-Vedic leanings. It has twelve chapters. It might have been ç
compiled during the period <MS>A.D.<D> 700-800.
Cast in the form of a dialogue between Skanda (or <186>a<207>mukha) ç
and Agasti (same as Agastya) it deals with several topics of <185>aivism ç
such as duties of worshippers of <185>iva, d<193>na (giving gifts), ç
imparting knowledge to the devotees of <185>iva, sins and the sufferings ç
of sinners, punarjanma (re-birth), practice of <185>ivayoga leading ç
to the attainment of <185>iva and so on.
Writers of dharma·<193>stras like Apar<193>rka (12th century <MS>A.<|>D.<D>) ç
and Hem<193>dri (13th century <MS>A.<|>D.<D>) have drawn upon the material ç
contained here.
@NT = <185>ivad<220>t<200>
@N1 = (`one who sent <185>iva as her <R>ç
assistant [for negotiations'])
Dev<200> or P<193>rvat<200> got this name because she sent her husband ç
<185>iva himself as a d<220>ta (servant or negotiator) to the demon-king ç
<185>umbha (vide Dev<200>m<193>h<193>tmya 8.28) with an ultimatum ç
to retire to the p<193>t<193>la (nether-world) or face extinction ç
at her hands.
As a form of Durg<193> she is one of the eight yogin<200>s like Brahm<193><207>i, ç
Vai<218><207>av<200> and so on.
She has four arms, a large face and big lips. She is tall and has ç
a fierce appearance. She wears a garland of severed heads. Her crown ç
is of matted hair. Snakes are her ornaments. She is draped in a tiger-skin. ç
In her four hands she carries a spear, a discus, a noose and a shield. ç
She stands in the <193>l<200><195>h<193>sana (See <MS>°L®£H°SANA.<D>) ç
with her feet on a corpse and a jackal. She is surrounded by a pack ç
of wolves.
@NT = <185>ivag<200>t<193>
@N1 = (`song of <185>iva')
The well-known Bhagavadg<200>t<193> has inspired many a similar ç
work. The Mah<193>-bh<193>rata, the Bh<193>gavata and the pur<193><207>as ç
contain as many as forty such treatises out of which the <185>ivag<200>t<193> ç
is also one. Though claimed to be a part of the Padma- pur<193><207>a, ç
most of the printed versions† except the Gau<195><200>ya or Be<209>g<193>li ç
recension† do not contain it.
The <185>ivag<200>t<193> as available now has sixteen chapters. ç
It is in the form of a dialogue, first between <185>r<200> R<193>ma ç
and the sage Agastya, and later, between <185>r<200> R<193>ma and ç
<185>iva.
The contents may be summarised briefly as follows:
@S10 = Chapter 1
The guruparampar<193> (succession of teachers) is described here.
@S10 = Chapter 2 and 3
Sage Agastya initiates <185>r<200> R<193>ma into ·ivad<200>k<218><193> ç
(esoteric methods connected with meditation and worship of <185>iva).
Chapters 4 to 16 form a dialogue between <185>r<200> R<193>ma and ç
<185>iva. Agastya first comforts <185>r<200> R<193>ma who was sorrowing ç
for S<200>t<193> who had been abducted by R<193>va<207>a by giving ç
him timely philosophical advice and then advises him to propitiate ç
<185>iva.
@SPACE1 = 
@S10 = Chapters 4 and 5
<185>r<200> R<193>ma worships <185>iva, gets a vision of the empirical ç
universe, how it is created, sustained and withdrawn by <185>iva and ç
how <185>iva reveals that R<193>va<207>a and others are already destroyed ç
by their own evil deeds. <185>r<200> R<193>ma has only to be nimitta ç
or proximate cause.
@SPACE1 = 
@S10 = Chapters 6 and 7
<185>r<200> R<193>ma questions about the cosmic form of <185>iva or ç
Um<193>-Mahe·vara. The same is revealed to him.
@SPACE1 = 
@S10 = Chapters 8 and 9
These describe how the living beings are born as also their physiology ç
and psychology.
@SPACE1 = 
@S10 = Chapter 10
This describes the svar<220>pa or the intrinsic  nature  of  the  j<200>va  or  the ç
individual soul. When associated with the up<193>dhis (limiting adjuncts) ç
it appears as limited. When shorn of them it is the same as Brahman.
@SPACE1 = 
@S10 = Chapter 11
This chapter delineates the well-known arcir<193>dim<193>rga (the ç
path of light) and the dh<220>m<193>dim<193>rga (the path of smoke) ç
that a j<200>va has to take after death. The descriptions are the ç
same as given in the Upani<218>ads.
@S10 = Chapter 12
According to this chapter, <185>iva can be worshipped both as the ç
Supreme Deity (Parame·vara) and as the immanent deity (Sarv<193>ntary<193>min).
@S10 = Chapter 13
Four kinds of mukti like s<193>m<200>pya are described here.
@S10 = Chapter 14
The pa<210>cako·as (five sheaths) and the <193>tman being separate ç
from them†this is the main subject matter here.
@S10 = Chapter 15
Essentials of bhakti are the contents of this chapter.
@S10 = Chapter 16
The qualifications required of an adhik<193>rin (competent aspirant) ç
are described here.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@NT = <185>ivaj<210><193>nabodham
See <MS>MEYKAØ£AR.
@SPACE1 = 
@SPACE1 = 
@NT = <185>ivali<209>ga
@N1 = (`emblem of <185>iva')
@SPACE1 = 
<185>iva, the third god of the Hindu Trinity, is generally worshipped ç
in the aniconic form of the li<209>ga. Literally, <185>iva means auspiciousness ç
and li<209>ga means anemblem. Hence <185>ivali<209>ga means an emblem ç
of auspiciousness.
Since both the words, <185>iva and li<209>ga, also mean the Supreme ç
God into whom the whole universe dissolves at the timeof
