@NID = some  sacrifices  like  Dar·ap<220>r<207>m<193>sa, Somay<193>gas, ç
C<193>turm<193>sya sacrifices, Sattra-y<193>gas and so on; agnicayana ç
or preparing the platform for the sacrifices with bricksetc.
All the four Vedas have their respective <185>rautas<220>tras. They ç
may be listed as follows:
@Z_TBL_BEG = COLUMNS(1), DIMENSION(IN), ABOVE(.0555), BELOW(.0555), ç
KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT
<184>gveda:
@Z_TBL_BODY = IN2
°·val<193>yana <185>rautas<220>tras<R>ç
<185><193><209>kh<193>yana <185>rautas<220>tras
@Z_TBL_BODY = SPACE

@Z_TBL_BODY = TABLE TEXT
<185>ukla Yajurveda:
@Z_TBL_BODY = IN2
K<193>ty<193>yana <185>rautas<220>tras
@Z_TBL_BODY = SPACE

@Z_TBL_BODY = TABLE TEXT
K<216><218><207>a Yajurveda:
@Z_TBL_BODY = IN2
°pastamba <185>rautas<220>tras<R>ç
Baudh<193>yana <185>rautas<220>tras<R>ç
Bharadv<193>ja <185>rautas<220>tras<R>ç
M<193>nava <185>rautas<220>tras<R>ç
Vaikh<193>nasa <185>rautas<220>tras
@Z_TBL_BODY = SPACE

@Z_TBL_BODY = TABLE TEXT
S<193>maveda:
@Z_TBL_BODY = IN2
°r<218>eya Kalpas<220>tras (or Ma·aka<R>ç
Kalpas<220>tras) containing the<R>ç
<185>rautas<220>tra part also.<R>ç
Dr<193>hyaya<207>a <185>rautas<220>tras<R>ç
Jaimin<200>ya <185>rautas<220>tras<R>ç
L<193><219>y<193>yana <185>rautas<220>tras
@Z_TBL_BODY = SPACE

@Z_TBL_BODY = TABLE TEXT
Atharvaveda:
@Z_TBL_BODY = IN2
Vait<193>na <185>rautas<220>tras
@Z_TBL_END = 
Without the help of these <185>rauta-s<220>tras, it would not have ç
been possible to perform the various Vedic sacrifices.
@NT = ·reyas
@N1 = (`the good')
See <MS>PREYAS.<D>
@NT = <185>r<200>, <185>r<200>dev<200>
She is the same as Lak<218>m<200>.
See <MS>LAK<186>M®<D> for details.
@NT = <185>r<200>bh<193><218>ya
See <MS>BRAHMAS<188>TRAS<D>, <MS>R°M°NUJA<D> and <MS>VI<185>I<186><187>°DVAITA ç
VED°NTA DAR<185>ANA.<D>
@NT = <185>r<200>cakra
The <185>r<200>cakra is perhaps, the most important and the most widely ç
used symbol of the <185>akti cult, the cult of the votaries of the ç
Divine Mother. If God can be conceived of as the Father in Heaven, ç
He can as well be conceived of as the Mother Divine also. Though God ç
is neither masculine nor feminine, human nature being what it is, ç
it is but natural that anthropomorphic ways of worship are resorted ç
to in religion. Once this principle is accepted, what form of the ç
Deity can be more fitting for worship and contemplation than that ç
of the all-loving Divine Mother?
Even though Mother-worship is very ancient in Hinduism, the `Father' ç
has not been neglected! In fact, the Father-Mother-Principle is one ç
and the same. Just as fire and its burning power or the word and its ç
meaning cannot be separated, even so <185>iva and <185>akti cannot ç
be separated.
Though the three consorts of the Trinity†Sarasvat<200> of Brahm<193> ç
the creator, Lak<218>m<200> of Vi<218><207>u the protector and P<193>rvat<200> ç
of Mahe·vara, the destroyer†are the main deities in the Mother-cult, ç
it is the various aspects of P<193>rvat<200> that are most widely ç
used in worship, japa or contemplation. In fact, an entire branch ç
of Hindu religious practice, the tantras, has developed round this ç
Deity.
Again, Durg<193>, K<193>l<200> and Lalit<193> are the three forms ç
of P<193>rvat<200> which are most widely used for worship. The <185>r<200>cakra ç
is the symbol of the Lalit<193>-aspect of the Divine Mother. It is ç
essentially a yantra, a geometrical diagram representing the form-pattern ç
of the Goddess.
@SPACE1 = 
The <185>r<200>cakra consists of a dot (bindu) at the centre surrounded ç
by nine triangles (triko<207>a), of which five have their apexes downward ç
and the other four, upward. The mutual intersections of these nine ç
triangles form forty-three triangles in all. This is surrounded by ç
two concentric circles with eight lotus petals and sixteen lotus petals. ç
This again is surrounded by three more concentric circles. Finally ç
on the outskirts, there is a square (caturasra) or three lines, the ç
lines one inside the other, opening out in the middle of each side ç
as four portals.
According to the <185><193>ktatantras, scriptures of the cult of Mother ç
worship, the ultimate Reality is one, a transcendental Absolute which ç
is immutable and ineffable. It is pictured as Supreme Effulgence, ç
Prak<193>·a. Desiring to become many, thisAbsolute starts reflecting ç
on Itself. This deliberation is technically designated vimar·a. This ç
vimar·a creates a throb or stir, spanda, which develops as vibration ç
or n<193>da and gets concentrated to a point or bindu.
This bindu, like a dicotyledonous seed, contains the <185>iva-<185>akti ç
principle as one closely-knit unit. It then gradually swells, giving ç
rise to the polarisation of <185>iva (father-principle) and <185>akti ç
(mother-principle), retaining simultaneously the original latent and ç
potent status containing the <185>iva-<185>akti combination. These ç
three units now form a triangle, as it were. This process goes on, ç
until it results in the <185>r<200>cakra. This is nothing but a representation ç
of the Supreme Consciousness in its various levels of evolution.
We thus see that the <185>r<200>cakra is a symbol of the Divine, its ç
ovulation into the created universe as well as the universe itself. ç
In other words, it represents the Absolute in all its aspects.
The <185>r<200>cakra can be used for permanent worship, either in ç
the form of a yantra (two-dimensional engraved figure) or a meru (three-dimensional ç
embossed figure). The yantra can be drawn on a Bh<220>rja leaf, or ç
plates of copper, silver or gold. The most common material for the ç
meru is the pa<210>caloha (alloy of five metals†gold, silver, copper, ç
tin and lead).
@SPACE = 
@NT = <185>r<200>dharasv<193>min
@SPACE = 
<185>r<200>dharasv<193>min or <185>r<200>dhara is one of the few commentators ç
belonging to the Advaita school of Ved<193>nta who has tried to harmonise ç
j<210><193>na (knowledge) and bhakti (devotion) in his writings.
He probably lived in the 15th century <MS>A.<|>D.<D> A br<193>hma<207>a ç
from Maharashtra, he lived in Gujarat.
He was a householder and an apparently insignificant incident in his ç
life made him renounce the world and become a sa<221>ny<193>sin.
His works are:
@Z_TBL_BEG = COLUMNS(2), DIMENSION(IN), COLWIDTHS(.3333,E1), BELOW(.0278), ç
VGUTTER(.0417), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT
1., Subodhin<200><R>ç
(commentary on the Bhagavadg<200>t<193>);
2., Bh<193>v<193>rthad<200>pik<193><R>ç
(commentary on the Bh<193>gavata);
3., °tmaprak<193>·a<R>ç
(commentary on the Vi<218><207>upur<193><207>a);
@Z_TBL_END = 
His writings are quite popular among the students of Ved<193>nta.
@NT = <185>r<200>har<218>a
One of the few important dialecticians of Advaita Ved<193>nta, <185>r<200>har<218>a ç
probably lived during the middle part of the 12th century <MS>A.<|>D.<D>, ç
in the court of the king Jayacandra of Kany<193>kubja (Kanauj).
Nai<218>adhacarita, a great poetical workdescribing the story of ç
Nala and Damayant<200> and Kha<207><195>ana-kha<207><195>a-kh<193>dya, ç
a highly polemical work attacking the Ny<193>ya school of philosophy ç
are his two most well known works. Nine more works like Ar<207>ava-Var<207>ana, ç
Vijaya-pra·asti and ®·var<193>bhisandhi are also attributed to ç
him.
See also <MS>KHAØ£ANA-KHAØ£A-KH°DYA.<D>
@NT = <185>r<200>ka<207><219>ha
<185>r<200>ka<207><219>ha is one of the important <193>c<193>ryas ç
who have written commentaries on the Brahmas<220>tras. He advocates ç
a type of <185>aivism as contained in the V<193>yav<200>ya-sa<221>hit<193> ç
of the <185>ivapur<193><207>a.
According to him Brahman is <185>iva (Sagu<207>a-Brahman). Prak<216>ti ç
(nature) and j<200>vas (individual souls who are atomic in size) are ç
his parts as it were. Evolution of the world takes place as per his ç
will and supervision. Though, thus, he is the nimittak<193>ra<207>a ç
or the efficient cause, he is, in a way, the up<193>d<193>nak<193>ra<207>a ç
or the material cause also since prak<216>ti is his part.
<185>r<200>ka<207><219>ha considers that the performance of Vedic ç
sacrifices and the prescribed duties without any selfish motive, prepares ç
a person for the realisation of <185>iva.
Man (or the soul) is free to do good or bad as per his sa<221>sk<193>ras ç
carried over from the previous lives. However, <185>iva the merciful, ç
is ever eager to help him to do good and get liberation.
The souls are the conscious knowers, both by way of the senses and ç
by the manas (superior mind, which is a special property possessed ç
by them, different from the ordinary mind which is a product of prak<216>ti). ç
By following the path of j<210><193>nayoga, the threefold impurities ç
of the mind (See <MS>MALA<D> for details.) are removed and self-knowledge ç
is fully manifested. It is almost like the knowledge of Brahman.
In the state of liberation, the soul has no body but enjoys bliss ç
through the mind. If it wants, it can also create its own body and ç
enjoy all happiness. It is never again brought under the control of ç
karma.
<185>r<200>ka<207><219>ha's philosophy may be termed as <185>ivavi·i<218><219><193>dvaita, ç
because of its similarity to R<193>m<193>nuja's system.
Appayya D<200>k<218>ita (<MS>A.<|>D.<D> 1520-1592) has written an excellent ç
commentary called <185>iv<193>rkama<207>id<200>pik<193> on the bh<193><218>ya ç
of <185>r<200>ka<207><219>ha.
It is not known when exactly <185>r<200>ka<207><219>ha lived. Some ç
scholars suggest that he lived in <MS>A.<|>D.<D> 1270 and was from ç
Andhra Pradesh.
@NT = <185>r<200>karabh<193><218>ya
The <185>r<200>karabh<193><218>ya is the magnum opus of <185>r<200>patipa<207><195>ita.
The Brahmas<220>tras is a basic work of Ved<193>nta. Among the several ç
<193>c<193>ryas who have written commentaries on it, <185>r<200>patipa<207><195>ita ç
is also one. He most probably lived in the 14th century <MS>A.<|>D.<D> ç
He was a sa<221>ny<193>sin belonging to one of the five famous monasteries, ç
the Ekor<193>ma Ma<219>ha situated at Ked<193>ra in the Him<193>layas. ç
He was supposed to have been born with a part of the divine power ç
of N<193>raya<207>a (N<193>r<193>ya<207><193><221>·asambh<220>ta).  Apart  from ç
being  a  great  scholar  he  also  had miraculous powers. He might ç
have lived in the area near Vijayavada of the modern Andhra Pradesh.
He was a V<200>ra·aiva and hence his bh<193><218>ya reflects the philosophy ç
of that sect. He declares that he has followed the V<216>tti (brief  commentary)  of  Agastyamuni. ç
However, this work has not been traced till now. He adores Reva<207>a, ç
Maru<202>a and R<193>ma, earlier teachers of his school.
His philosophy in which the P<220>rvam<200>m<193><221>s<193> and the ç
Ved<193>nta are taken as forming one science, and based mainly on ç
this bh<193><218>ya, may be summarised as follows:
Brahman who is <185>iva or Para·iva is the only reality. His existence ç
can be proved only by the <185>rutis (Vedas, Upani<218>ads and the ç
Bhagavadg<200>t<193>). He is a person without any particular form ç
but with infinite knowledge and power (nir<193>k<193>ra and sagu<207>a). ç
M<193>y<193> is this power.
@SPACE1 = 
Before creation, prak<216>ti or matter (which is in the param<193><207>u ç
or atomic state) and the j<200>vas (souls) are inherent in him. He ç
creates the universe out of himself as per the karma of the individuals. ç
In one sense, he is the efficient cause and in another the material ç
cause also.
The world is real and not an illusion.
The j<200>vas are a<221>·as or parts of Brahman. Hence they are similar ç
to him in nature. They are eternal and are a<207>u(atomic) in character. ç
Their number is infinite. They have the capacity for understanding ç
and also the power to act independently.
By performing the duties prescribed in the Vedas in a desireless manner, ç
the j<200>va becomes pure in heart. By meditating on Brahman as <185>iva ç
and worshipping him, the j<200>va attains him. Becoming like him (s<193>r<220>pya) ç
he lives in eternal bliss in <185>ivaloka which is the same as Brahma-loka. ç
He will never return to this world. He will continue to be obedient ç
to <185>iva and serve him for ever.
Being a pioneer of V<200>ra·aiva philo-sophy, <185>r<200>patipa<207><195>ita ç
supports the <186>a<219>sthalasiddh<193>nta and the wearing of the ç
<185>ivali<209>ga on the body.
See <MS><185>AIVISM<D> also.
@NT = <185>r<200>k<216><218><207>a
See <MS>K<184><186>ØA.<D>
@NT = <185>r<200>k<216><218><207>a Caitanya
@N1 = (<MS>A.<|>D.<D> 1486-1533)
@SB = Introduction
The life of a god-man has two faces, the external and the internal. ç
Whereas the former can be traced and described, the latter cannot ç
be, since it is a matterof direct personal and mystical experience. ç
<185>r<200>k<216><218><207>a   Caitanya†also   known   as Caitanya ç
Mah<193>prabhu†belongs to this group.
@SB = Birth and Early Life
He was born on a full-moon day (February 4, 1486) in the small town ç
of Navadv<200>p (in Bengal) as the tenth child of Jagann<193>tha Mi·ra ç
and <185>ac<200>dev<200>. He was given the name Vi·vambhara. His mother ç
called him `Nim<193>i' (the neem tree)†since she had lost eight children ç
and the ninth had run away to become a monk†in the belief that the ç
god of death would not touch him, he being `bitter' like the neem ç
leaves and fruits! Since his complexion was like that of gold and ç
since he was extraordinarily handsome, he was given the name Gaur<193><209>ga ç
(the white one) also.
As a child, his pranks and naughty behaviour were very much reminiscent ç
of those of <185>r<200>k<216><218><207>a himself. Certain unusual ç
signs of divinity also†like demanding the food offering meant for ç
K<216><218><207>a or humbling an elderly pa<207><195>it†started manifesting ç
in him.
He was admitted into a Sanskrit school where he made astonishing progress ç
in his education especially because of his exceedingly sharp intellect ç
and memory.
Meanwhile his father passed away. Mother <185>ac<200> took charge ç
of his higher education. Very soon he matured into a great scholar ç
of unsurpassed reputation. He also started his own <219>ol (Sanskrit ç
school). During this period he was married to Lak<218>m<200>, the ç
daughter of a reputed pa<207><195>it, Vallbh<193>c<193>rya.
Being endowed with handsome features and immense scholarship, he now ç
started on a tour of the nearby places to vanquish all the pa<207><195>its ç
of the region and establish his supremacy over them all. When he returned ç
he learnt that his wife had died of a snakebite. Maintaining his inner ç
poise, he continued his teaching work at his <219>ol. However his ç
mother <185>ac<200> got him married to Vi<218><207>upriy<193>, the ç
daughter of a wealthy pa<207><195>it of great reputation.
@SB = The Transformation
Some time after his tour, he decided to visit Gay<193>, the famous ç
pilgrim centre of Gad<193>dhara (Vi<218><207>u). During this visit, ç
after he completed all the formal rituals he worshipped at the Vi<218><207>up<193>da ç
(place containing the imprint of God's foot-prints) where he had a ç
strange mystical experience that changed his entire mood. He then ç
begged ®·vara Pur<200> (a sa<221>ny<193>sin- disciple of a well-known ç
saint M<193>dha- vendra Pur<200>) whom he had known earlier and who ç
was then present there, to initiate him into the mantra of worship ç
of K<216><218><207>a, the beloved of the gop<200>s. ®·vara Pur<200> ç
obliged and Nim<193>i's mood now changed completely into one of pathos ç
(like thatof the gop<200>s) due to an inner feeling ofseparation ç
from K<216><218><207>a, the beloved. Nim<193>i now became K<216><218><207>a ç
Caitanya or Caitanya Mah<193>-prabhu, the apostle of the love of K<216><218><207>a.
@SB = Self-revelation
From now onwards, Caitanya started going into ecstatic moods, his ç
behaviour often making people doubt his sanity and mental balance. ç
However, the great spiritual power that manifested in him now and ç
then, totally transforming persons whom he touched, did also speak ç
of therevelation of his divinity. <185>r<200>v<193>s, a committed ç
devotee, Advait<193>c<193>rya the scholarly leader of the Vai<218><207>avas, ç
K<193>zi the Muslim Governor, Jag<193>i and Madh<193>i, the confirmed ç
rowdies were some of the fortunate souls who gained from his infinite ç
grace and compassion.
It was during this period that he gathered a good number of followers ç
like Nity<193>nanda or Nit<193>i who became his inseparable companion, ç
Harid<193>s (a Muslim saint), Mur<193>ri and others.
@SB = Adopting Sa<221>ny<193>sa
Caitanya now decided to take sa<221>ny<193>sa (monastic life) and ç
somehow managed to extract permission from his mother and wife. He ç
then left Navadv<200>p and proceeded to Ka<219>va where lived a great ç
monk Ke·ava Bh<193>rat<200>, with whom he had had contacts earlier. ç
Ke·ava Bh<193>rat<200> administered the monastic vowsand changed ç
his name to <185>r<200>k<216><218><207>a Caitanya.
Meanwhile his mother and the devotees met him and got the promise ç
that he would live at N<200>l<193>cal (Jagann<193>tha Pur<200> or ç
Pur<200>) in Orissa (a nearby place) and not go to V<216>nd<193>ban ç
(which is far off) as he had planned.
@SB = At Pur<200>
This was his first visit to Pur<200>. The yearning to meet his K<216><218><207>a ç
at V<216>nd<193>ban now turned towards Jagann<193>tha of Pur<200>, ç
who was K<216><218><207>a himself.
One of the important events that took place at Pur<200> was the conversion ç
of V<193>sudeva S<193>rvabhauma, the doyen of scholars at that time, ç
who was made to give up his Advaita philosophy and turn to devotion ç
for Lord K<216><218>na.
@SB = Pilgrimages
Caitanya  then  undertook  a  long pilgrimage to South India (spread ç
over two years) visiting all the important holy centres including ç
Kany<193>kum<193>r<200> (in Tamil Nadu) and U<195>upi (in Karnataka).
It was during this visit that he converted R<193>m<193>nanda Roy, ç
the governor of Vidy<193>nagara (in Andhra Pradesh) under the king ç
Prat<193>parudra of Kali<209>ga (Orissa), to the cult of devotion ç
to K<216><218><207>a. The king too, drawn by his magnetic personality, ç
became his disciple.
After returning to Pur<200> and taking part in the famous Rathay<193>tr<193> ç
(car-festival) of Lord Jagann<193>tha, he travelled towards V<216>nd<193>ban ç
and returned via other holy places in North India like V<193>r<193><207>as<200> ç
(K<193>·<200>) and Pray<193>ga (Allahabad). It was during this tour ç
that he made three important disciples R<220>pa Gosv<193>min (<MS>A.<|>D.<D> ç
1493-1568), his brother San<193>tana Gosv<193>min (<MS>A.<|>D.<D> 1481-1558) ç
and their nephew J<200>va Gosv<193>min (d. <MS>A.<|>D.<D> 1609). They ç
were not only devotees of K<216><218><207>a but also great scholars ç
who were instrumental informulating the Acintyabhed<193>bheda philosophy ç
of the Caitanya cult.
At that time V<216>nd<193>ban, the place connected with the childhood ç
days of K<216><218><207>a, was in a very bad shape. Caitanya commanded ç
San<193>tana to rediscover and reclaim all the important places and ç
convert it into a good place of pilgrimage, especially for the devotees ç
of K<216><218><207>a. San<193>tana succeeded in the task admirably.
It is said that Vallabh<193>c<193>rya (<MS>A.<|>D.<D> 1473-1531) the ç
well-known Vai<218><207>ava teacher of the pu<218><219>im<193>rga, ç
met Caitanya here.
@SB = Last Years
The last thirteen (or fourteen) years of life were spent by Caitanya ç
exclusively at Pur<200>. During this period he often used to be in ç
ecstatic states of K<216><218><207>abhakti (as that of R<193>dh<193> ç
towards K<216><218><207>a). Hence someone had to be with him always ç
to take care of him.
Though a great scholar, Caitanya never left any writings of his own, ç
except two  exquisitely  beautiful  hymns†the Caitanya·ik<218><193><218><219>aka ç
and the Jagann<193>tha-stotra.
Apart from the Bh<193>gavata, Caitanya was fond of the famous hymn ç
<185>r<200>k<216><218><207>a-kar<207><193>m<216>ta and another work ç
called the Brahmasa<221>hit<193>.
@SB = The End
There are two versions of Caitanya's end. According to the first, ç
he entered into the image of Jagann<193>tha in the temple. The second ç
account describes that he entered into the waters of the sea and disappeared.
@SB = Epilogue
Caitanya has been considered an incarnation of R<193>dh<193> and K<216><218><207>a ç
in one body. Though he exhibited in his life the intense love and ç
passion of R<193>dh<193> for K<216><218><207>a†technically known as ç
prem<193>bhakti †he led a very strict life as an ordained monk. There ç
was absolutely no trace of k<193>ma or lust in his philosophy of devotion ç
to K<216><218><207>a or the R<193>dh<193>-K<216><218><207>a ideal.
In course of time, V<216>nd<193>ban in the north, Navadv<200>p in ç
Bengal in the east and Pur<200> in south-east became the centres of ç
Caitanya Vai<218><207>avism.
In Bengal, the Vai<218><207>ava movement developed more as a Caitanya ç
cult than as a tradition of devotion to K<216><218><207>a. A special ç
contribution of this movement is the stress on k<200>rtans, singing ç
of devotional songs to the accompaniment of musical instruments and ç
dancing.
Inability of the common people to understand the significance of true ç
devotion<|> gradually<|> gave <|>rise <|>to <|>various unhealthy and immoral ç
cults like those of the Sahaj<200>yas, Kart<193>bhajas, Vair<193>gi-Vair<193>gi<207><200>s ç
and so on.
See <MS>ACINTYA-BHED°BHEDA<D> also.
@NT = <185>r<200>niv<193>sa
@N1 = (`the abode of <185>r<200> [Lak<218>m<200> or goddess of wealth]')
This is another name of the famous deity  Ve<209>ka<219>e·a  of  Tirumala-Tirupati ç
temple.
See <MS>TIRUPATI<D> and <MS>VE<177>KA<187>E<185>A.<D>
@NT = <185>r<200>p<193>dar<193>ja
@N1 = (d. <MS>A.<|>D.<D> 1486)
The Bhakti Movement of Karnataka has been nourished and sustained ç
by two traditions: the <185>aiva tradition of the <185>iva·ara<207>as ç
and the Vai<218><207>ava tradition of the Harid<193>sas.
The latter is divided into two parallel but closely knit streams†the ç
vy<193>sak<220><219>a and the d<193>sak<220><219>a. (See <MS>D°SAK<188><187>A.<D>) ç
The vy<193>sak<220><219>a comprises the sa<221>ny<193>sins of the ç
M<193>dhva sect whereas the d<193>sak<220><219>a consists of the householders, ç
also of the same sect.
<185>r<200>p<193>dar<193>ja was a pioneer of the vy<193>sak<220><219>a.
Known as Lak<218>m<200>n<193>r<193>ya<207>a (the son of <185>e<218>agiri ç
and Giriyamma) in his premonastic days, he was adopted by Svar<207>a-var<207>at<200>rtha, ç
the abbot of a dvaita monastery at Mu<202>ab<193>gilu (Mulbagal, in ç
the Kolar district of Karnataka). After initiation into the monastic ç
order, he was given the name Lak<218>m<200>n<193>r<193>ya<207>ayogi. ç
Later on he came to be popularly known as <185>r<200>p<193>dar<193>ja ç
or <185>r<200>p<193>dar<193>yaru. Under his guru's vigorous training ç
he became a great scholar and a monk of repute.
After taking over as the abbot of the monastery, when his teacher ç
passed away, he worked hard to improve its condition and expand its ç
scope as also the area of its influence.
S<193><202>uva Narasi<221>har<193>ja, who was the king of a small ç
state Candragiri, became his disciple in <MS>A.<|>D.<D> 1471, and was ç
greatly benefited by his holy influence.
<185>r<200>p<193>dar<193>ya then undertook a long pilgrimage to K<193>·<200> ç
and other places, establishing his reputation as an invincible scholar.
After returning to his place, he started the new tradition of introducing ç
bhajans and sa<209>k<200>rtans (devotional hymns and songs) in Kannada, ç
the local language of the people, in his monastery, especially after ç
ritualistic worship. This gave the common people a grand opportunity ç
to understand the essence of the Sanskrit scriptures in their own ç
language.
There are several Kannada compositions attributed to him.
He is reputed to have exhibited many miraculous powers including the ç
rising of the Ga<209>g<193>-waters at the pond known as the N<216>si<221>hat<200>rtha ç
near the monastery.
He passed away in <MS>A.<|>D.<D> 1486.
@NT = <185>r<200>pa<210>cam<200>
<185>r<200>pa<210>cam<200> is one of the minor festivals of the Hindus. ç
It is observed on the M<193>rga·ira-·ukla-pa<210>cam<200> day (the ç
fifthday in the bright half of the monthM<193>rga·ira, generally ç
in November/ December).
It is a day sacred to <185>r<200> or Lak<218>m<200> and is dedicated ç
to her worship. The worship may be offered to a metallic or clay image ç
or even to a picture. Honouring chaste married women and donating ç
a cow to a worthy person are recommended.
The worship may also be carried on for one full year, observing it ç
as a vrata (religious vow) on the ·ukla-pa<210>cam<200> every lunar ç
month.
@NT = <185>r<200>r<193>ma
See <MS>R°M°YAØA.<D>
@NT = <185>r<200>ra<209>gam
<185>r<200>ra<209>gam is one of the most sacred places of pilgrimage ç
for the devotees of Vi<218><207>u†especially the <185>r<200>vai<218><207>avas, ç
the followers of R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137)† ranking ç
next only to Tirupati (in Andhra Pradesh). This small town is situated ç
just 5 kms. (3 miles) from the Tiruchirapalli railway station which ç
itself is 320 kms. (200 miles) to the south-west of Chennai (Madras) ç
in Tamil Nadu.
This little town, the whole of whichisthe temple-complex dedicated ç
to Ra<209>gan<193>tha (an aspect of N<193>r<193>ya<207>a or Vi<218><207>u), ç
is located on the island formed by the river K<193>ver<200> which ç
splits into two streams†the K<193>ver<200> and the Kolla<195>am †which ç
later rejoin. The temple proper is known by several names such as ç
Koil, Bh<220>vaiku<207><219>ha, Tiruvara<209>ga-Tirupati, °dira<209>ga ç
and Bhogama<207><195>apa.
The chief deity is considered to be svaya<221>vyakta (self-manifested) ç
and not man-made. According to the local legends this deity has ç
a very ancient history. Originally worshipped by Brahm<193>, the creator, ç
it was handed over to the kings of the Ik<218>v<193>ku race. Later ç
on <185>r<200>r<193>ma gave it to Vibh<200><218>a<207>a to take it ç
to La<209>k<193> and establish it in a temple there. However, on his ç
way to La<209>k<193>, Vibh<200><218>a<207>a had to place it on the ç
ground at the time of his evening prayer. The image got firmly fixed ç
on the ground (at the present place known as <185>r<200>ra<209>gam) ç
and Vibh<200><218>a<207>a had to return empty-handed.
(However, there is a belief that he comes once in twelve years in ç
the night, quietly worships it and goes back!)
From this legend this much can be assumed that the original shrine ç
is very ancient. It must have been renovated and rebuilt many times.
Over the centuries, this sacred placehas been visited by many a saint ç
like <185>r<200>k<216><218><207>a Caitanya (<MS>A.<|>D.<D> 1485-1533), ç
Vallabh<193>c<193>rya (<MS>A.<|>D.<D> 1481-1531), Ty<193>gar<193>ja ç
(<MS>A.D.<D> 1767-1847) and a host of others.
<185>r<200>ra<209>gam is the largest temple- complex in India. Its ç
area is 243 hectares (600 acres). The actual temple area is 62 hectares ç
(2.5 sq. kms.).
The main temple is surrounded by seven concentric pr<193>k<193>ras ç
or boundary walls enclosing or housing several subsi-diary shrines ç
as also the small township for the people living there.
The total number of gopuras (temple- towers) is 21.
The main deity is Ra<209>gan<193>tha, Lord Vi<218><207>u in the reclining ç
posture. He is lying on <185>e<218>an<193>ga or °di·e<218>a (the great ç
serpent), forming the bed out of his coils and an umbrella of five ç
hoods.
@SPACE1 = 
The image of Ra<209>gan<193>tha is 6.4 metres 21 ft.) long. Near his ç
feet are seated Bh<220>dev<200> and N<200>l<193>dev<200>, his consorts. ç
In front of this original deity is kept theprocessional image or ç
utsavam<220>rti. Another image called Tiruvara<209>ga used as a substitute ç
for worship during the period of Muslim invasions, is also kept in ç
the sanctum.
The sanctum sanctorum is square inside and circular outside. Immediately ç
round the altar, there is a circumambulatory passage used strictly ç
for ritual purposes.
Encircling the sanctuary there is a moat-like canal of stone which ç
is filled with water in summer to keep the sanctum cool.
On the upper wall there are paintings estimated to be 300 years old, ç
depicting the 108 shrines dedicated to Vi<218><207>u and sacred to ç
the <185>r<200>vai<218><207>avas.
Above the main altar there is a Ra<209>gavim<193>na (a golden tower) ç
containing carvings of four forms of Vi<218><207>u.
The outermost pr<193>k<193>ra†the seventh in the series†has the main, ç
most imposing gopuram, called the `R<193>jagopuram.' completed and ç
consecrated in <MS>A.<|>D.<D> 1987. It is 72 metres (235 ft.) high ç
and has a passage below it which is 26 metres (100 ft.) long.
The area of this pr<193>k<193>ra measures 864 metres by 742 metres ç
(2880 ft. by 2475 ft.) The temple-tank is outside this pr<193>k<193>ra. ç
Houses and bazaars are situated in its enclosure.
The sixth pr<193>k<193>ra houses the rathas or processional cars in ç
its enclosure. The houses of the br<193>hma<207>as serving in the ç
temples are also situated here.
The fifth pr<193>k<193>ra-enclosure houses a museum apart from some ç
temples.
@SPACE1 = 
From the enclosure of the fourth pr<193>k<193>ra, the temple proper ç
begins. This pr<193>k<193>ra measures 370 metres by 254 metres (1235 ç
ft. by 849 ft.). It contains a hall known as Garu<195>ama<207><195>apa ç
with 212 pillars.
This pr<193>k<193>ra itself has four gopurams in the four cardinal ç
directions, the eastern one being the largest and the finest.
The other three enclosures created by the three pr<193>k<193>ras are, ç
naturally, smaller but contain several shrines.
It was R<193>m<193>nuja who reorganised the mode of worship in the ç
temple (according to the P<193><210>car<193>tra °gamas) and overhauled ç
the entire administration. The same tradition has been kept up even ç
now.
In this big temple-complex, there areseveral shrines dedicated to ç
various aspects of Vi<218><207>u like Hayagr<200>va and K<216><218><207>a, ç
to the <193>yudhapuru<218>as or the weapon- deities like Sudar·ana, ç
°lv<193>rs, consorts of Vi<218><207>u and the <193>c<193>ryas of the ç
<185>r<200>vai<218><207>ava tradition, R<193>m<193>nuja, Ved<193>nta ç
De·ika (<MS>A.D.<D>1260-1370) and Pi<202><202>ai Lok<193>c<193>rya ç
(<MS>A.D.<D> 1264-1327).
One of the biggest attractions is the `thousand-pillared hall' (150 ç
metres by 48 metres or 500 ft. by 160 ft.) lying to the east in the ç
inner campus. The actual number of granite pillars is 953 only, each ç
being 5.4 metres (18 ft.) in height and intricately carved.
@SPACE1 = 
Out of the several festivals celebrated at the temple, the biggest ç
is the Vaiku<207><219>ha Ek<193>da·<200>  (Pu<218>ya-·uddha-ek<193>da·<200>,  the ç
eleventh day in the bright fortnight of themonth Pu<218>ya, generally ç
in December/ January). It is spread over twenty days. On this day, ç
the utsavam<220>rti is gorgeously decorated, dressed in a garment ç
of rubies and taken out in a magnificent procession to the thousand ç
pillared hall.
The temple was attacked by the Muslim marauders from the north led ç
by Malik K<193>fur and Ulugh Kh<193>n in <MS>A.<|>D.<D> 1311 and <MS>A.<|>D.<D> ç
1323. However, the devotees managed to save both the original deity ç
and the processional icon.
Several kings and dynasties have helped in renovating as also maintaining ç
this great temple. Some of them are: the Co<202>as, the Pallavas, ç
the P<193><207><195>yas, the Hoysa<202>as, the emperors of Vijayanagara ç
and the N<193>yaks of Madurai.
There are as many as 600 inscriptions on the walls and other places ç
in the complex.
There is a popular story and belief that <185>a<209>kara (<MS>A.<|>D.<D> ç
788-820) installed a Jan<193>kar<218>akayantra (a special and sacred ç
magical diagram) because of which this temple attracts a very large ç
number of pilgrims and devotees, always, throughout the year.
The <185>r<200>ra<209>gam temple is considered by a long-standing ç
tradition to be one of the Navagrahasthala-temples (temples representing ç
the nine planets) and stands for the <185>ukra or the Venus.
There is no doubt that this temple complex is a fortress that is protecting ç
Hinduism in general and Vai<218><207>avism in particular.
@NT = <185>r<200>ra<209>gapa<219><219>a<207>a
Ra<209>gan<193>tha is an aspect of Vi<218><207>u. Images of Ra<209>gan<193>tha ç
are invariably in the ·ayana or reclining posture. Three temples of ç
this deity are at <185>r<200>ra<209>ga-pa<219><219>a<207>a, <185>ivasamudra ç
and <185>r<200>ra<209>gam. The first two are in the Karnataka state ç
and the last in Tamil Nadu. The deities are known as °dira<209>ga, ç
Madhyara<209>ga and Antyara<209>ga respectively. All the three temples ç
are situated on small islands created by the branching off into two, ç
of the river K<193>ver<200>.
<185>r<200>ra<209>gapa<219><219>a<207>a is a small town 13kms. (8 ç
miles) from the city of Mysore. According to the local legends, the ç
greatsage Gautama lived here and wasworshipping the °dira<209>ga ç
image. Tirumalayya, a chieftain of the kings of the Ga<209>ga race ç
built the present temple in <MS>A.<|>D.<D> 849 and named the small ç
town as <185>r<200>ra<209>gapura.
The Ra<209>gan<193>tha temple has been built in the Dravidian style ç
of architecture. At the entrance of the navara<209>ga (open auditorium) ç
there are two big images of Dv<193>rap<193>lakas (gate-keepers).
The original image is very beautiful and attractive. The serpent °di·e<218>a, ç
on whom the deity is lying, has seven hoods. Near the feet of the ç
deity is an image of goddess Lak<218>m<200> and of the sage Gautama.
There are two more temples in the town, of Narasi<221>ha (Man-lion ç
incarnation of Vi<218><207>u) and of Ga<209>g<193>dhare·vara (<185>iva) ç
built during the 17th century <MS>A.<|>D.
Very near <185>r<200>ra<209>gapa<219><219>a<207>a is the pilgrim centre ç
Pa·cimav<193>hin<200>. Here, one of the branches of the K<193>ver<200> ç
river flows towards the west (= pa·cima) for a short distance. Hence ç
the name. There are quite a few dharma·<193>l<193>s (choultries) catering ç
to the pilgrims who crowd here for the performance of religious rites.
See also <MS><185>R®RA<177>GAM<D>.
@NT = <185>r<200>·ailam
@N1 = (`the holy hill')
<185>r<200>·ailam†also called <185>r<200>parvata†is a small town situated ç
on the <184><218>abhagiri hill, on the bank of the river K<216><218><207><193> ç
in the Kurnool district of Andhra Pradesh.
The  temple  of  <185>iva,  known  as Mallik<193>rjuna, is the centre ç
of attraction of this pilgrim centre. It is one of thetwelve Jyotirli<209>gas ç
(`li<209>gas of light') known for their sanctity.
The deity gets this name because the original li<209>ga used to be ç
worshipped daily with mallik<193> or jasmine flowers.
The river, called locally as P<193>t<193>laga<209>g<193>, is about ç
3 kms. down the hill. All the devotees who come for dar·an (`seeing ç
[the li<209>ga]') must take a bath in this river.
The main temple is enclosed by a massive pr<193>k<193>ra (boundary ç
wall) which measures 183 metres by 152 metres (600 ft. by 500 ft.) ç
and is 8.5 metres (29 ft.) high. It is made of huge blocks of stone ç
riveted to one another.
On the inside of this pr<193>k<193>ra, there are five regular rows ç
of sculpture from above the base. There are innumerable varieties ç
of figures of superb sculpture.
According to the earliest reference available in a <185><193>tav<193>hana ç
inscription theshrine existed even in the second century <MS>A.<|>D.<D> ç
The temple however, has been renovated by several dynasties of kings ç
who also gifted land and precious objects.
The garbhag<216>ha (sanctum) containing the li<209>ga is a small stone-structure ç
with an equally small pillared porch attached to the front. In front ç
of this is the exquisitely  carved  mukhama<207><195>apa  or pillared ç
hall built in <MS>A.<|>D.<D> 1404-1405 by the king Harihara of Vijayanagara ç
Empire. It contains several beautifully sculptured stone pillars and ç
ornamental eaves, also of stone.
There is a Nandi (the bull) near the eastern gateway.
All devotees, irrespective of their caste, creed or sex, are allowed ç
inside the sanctum to touch the image and even bathe it with the water ç
brought from the P<193>t<193>laga<209>g<193> river.
@SPACE1 = 
The oldest structure in the campus is  the  shrine  dedicated  to  V<216>ddha- ç
Mallik<193>rjuna, assigned to the seventh century <MS>A.<|>D.<D> It ç
is considered to be the original icon of the temple.
