Behind the golden advice that none is a stranger and that the whole ç
world is our own, is the great Ved<193>ntic truth taughtby numberless ç
sages over several millennia! If the same <193>tman (the Self) or ç
God dwells in the hearts of all including myself, then, finding fault ç
with others will tantamount to abusing myself! Once this truth is ç
discovered or the deep conviction developed, the entire gamut of human ç
relationships gets transmuted to a higher plane!
True, this is not that easy as we may imagine. But, by trying to learn ç
to practise it we gradually elevate ourselves †and others†in the truly ç
spiritual sense.
A mother never sees the infirmities of her children. Even if she does, ç
she makes light of them.
Then what to speak of the Universal Mother, the Mother of all mothers! ç
She who could melt the hearts of the robber couple or make a hardened ç
criminal like Amzad (a Muslim labourer, notorious for his nefarious ç
activities) behave like a loving son, only she could deliver such ç
a unique message, since she had attained to the status of the Universal ç
or the Divine Mother and reflected it in every word and act of hers.
The world at large is yet to learn and act on her message.
@SB = 19.	Epilogue
If the motherly love inhabiting the hearts of all the mothers in the ç
world were to be put together and churned, the nectar that would issue ç
forth would perhaps approximate to S<193>rad<193>dev<200>. R<193>mak<216><218><207>a ç
left her in this world to uphold the highest ideal of universal motherhood.
Her rare insight into the problems of Indian women who were handicapped ç
by obsolescent social customs on the one side, and, exposure to the ç
modern Western culture on the other, made her recognise the need for ç
their education and even economic independence. That is why she was ç
an ardent supporter of Sister Nivedit<193>'s (<MS>A.<|>D.<D> 1867-1911) ç
endeavours in the field of educating Indian women.
She is certainly the best bridge between the ancient and the modern ç
ideals of Indian womanhood, retaining the best of both.
@NT = S<193>rad<193> Ma<219>h or Sri Sarada Math
@N1 = (of Dak<218>i<207>e·var)
The sages of ancient India had given women equal opportunities, not ç
only for higher education but also for spiritual evolution,  including  monastic  life  if ç
necessary.
Sv<193>m<200> Vivek<193>nanda (<MS>A.<|>D.<D> 1863-1902) had seriously ç
thought of establishing a Ma<219>h (monastery) for women also when ç
he had established the Ramakrishna Math (and the Ramakrishna Mission) ç
for men-aspirants.
At the behest of the Sv<193>m<200>, Sister Nivedit<193> (<MS>A.<|>D.<D> ç
1867-1911) (See <MS>NIVEDIT°<D> for details.) came to India from London ç
and established a school for girls in Calcutta (now, Kolkata), in ç
<MS>A.<|>D.<D> 1898. This school gradually became the nucleus of the ç
later organisation now known as the S<193>rad<193> Ma<219>h (and the ç
Ramakrishna Sarada Mission).
When Nivedit<193> plunged into the political field of struggle for ç
independence, the school was managed successfully by Sister Christine ç
and later by Sudh<200>r<193> Bose. They added a new section to train ç
adult women in various activities such as sewing and needle-work, ç
along with the teaching of academic subjects like Be<209>g<193>l<200>, ç
Sanskrit and English.
Sudh<200>r<193> also started an <193>·rama (a semi-monastery) for ç
dedicated women workers as also a boarding home for students and poor ç
women. This <193>·rama, sanctified by the stay of S<193>rad<193> Dev<200> ç
(the Holy Mother) was later named as S<193>rad<193> Mandir.
Nivedit<193> had named her school as the `Ramakrishna School for Girls.' ç
However, it was popularly called Nivedit<193> School.
Since she had been initiated into the Ramakrishna Order by Sv<193>m<200> ç
Vivek<193>-nanda himself, her school was legally affiliated to the ç
Ramakrishna Mission in <MS>A.<|>D.<D> 1918.
Gradually†and especially after India gained political independence†more ç
and more educated girls, some of whom had taken spiritual initiation ç
from the sa<221>ny<193>sin disciples of <185>r<200> R<193>mak<216><218><207>a, ç
started joining the school to dedicate their lives for self-realisation ç
and service to mankind.
The movement for a parallel monastic organisation exclusively for ç
women, gained momentum when another group of inspired and dedicated ç
women living in a place called S<193>rad<193> °·rama joined those ç
of the S<193>rad<193> Mandir. The centenary of the Holy Mother S<193>rad<193> ç
Dev<200> celebrated during the year <MS>A.<|>D.<D> 1953-1954 gave further ç
fillip to their aspirations.
@SPACE1 = 
In January 1959 eight senior members of the S<193>rad<193> Ma<219>h ç
were invested with sa<221>ny<193>sa by the then president of the Ramakrishna ç
Order and the <185>r<200> S<193>rad<193> Ma<219>h was made legally ç
separate and independent.
A parallel organisation, but under the same management, known as the ç
`Ramakrishna Sarada Mission' was registered in <MS>A.<|>D.<D> 1960.
The Sri Sarada Math (<185>r<200> S<193>rad<193> Ma<219>h)  and  the  Ramakrishna  Sarada ç
Mission are run on the same model, includ- ing all the activities, ç
as the Ramakrishna Math and the Ramakrishna Mission.
Their Headquarters are situated in Dak<218>i<207>e·var with a massive ç
and beautiful temple for S<193>rad<193> Dev<200> and a building complex ç
housing the offices and living quarters.
They now have several branches all over India and one in Australia.
See also <MS>RAMAKRISHNA ORDER.<D>
@NT = <185><193>rad<193> Ma<219>ha
@N1 = (of <185><216><209>ger<200>)
@SB = Introduction
If a scientific gadget can discover a hidden object for which it is ç
designed, it is even more possible for holy persons with heightened ç
consciousness†and hence endowed with special psychic powers†to discover ç
places vibrating with holiness. Hence it is but natural for <185>a<209>kara ç
(<MS>A.<|>D.<D> 788-820), the great philosopher-mystic that he was, ç
to detect with his uncanny power of superconsciousness, the inherent ç
spiritual power of the place now well-known as <185><216><209>ger<200>.
The story goes that <185>a<209>kara's intuition was confirmed by his ç
seeing a cobra spreading its hood over a she-frog in labour pains, ç
to give it protection from the fierce rays of the hot sun.
This was the first place where he built his earliest of the four P<200><219>has ç
or Ma<219>has (monastic centres of learning and propagation of dharma), ç
the other three being established later at Badar<200> (the Jyotir ç
Ma<219>ha) in the north in Uttaranchal, Pur<200> (the Govardhana Ma<219>ha) ç
in the east in Orissa and the K<193>lik<193> Ma<219>ha in the west ç
in Gujarat.
This centre is also known as the <185><193>rad<193> P<200><219>ha ç
and Dak<218>i<207>a-<193>mn<193>ya P<200><219>ha.
@SB = Early History of the Place
The place <185><216><209>ger<200> (a corrupted form of <184><218>ya·<216><209>gapura) ç
was closely associated with the great sage <184><218>ya·<216><209>ga ç
(See <MS><184><186>YA<185><184><177>GA.<D>), son of Vibh<193><207><195>akamuni. ç
His story appears in the R<193>m<193>ya<207>a (B<193>la-k<193><207><195>a ç
9), the Mah<193>bh<193>rata (Vanaparva, Chapters 111-114) and ç
the Bh<193>gavata (9.23). He stayed here and practised severe austerities. ç
He passed away at a nearby place, now known as Kigga, both the places ç
being in the Chikkamagalur district of Karnataka State. A temple of ç
<185>iva†called <184><218>ya·<216><209>ge·vara†adorns the place.
@SB = Establishment of the Ma<219>ha
<185>a<209>kara established the Ma<219>ha on the northern bank of ç
the river Tu<209>g<193>. He built a small temple for <185><193>rad<193> ç
(Sarasvat<200>, the goddess of learning), drew a <185>r<200>cakra ç
(See <MS><185>R®CAKRA.<D>) on a piece of stone and invoked her presence ç
into it. Whether he also placed an image on it and consecrated it ç
is not known. A broken image of <185><193>rad<193>, made of sandalwood, ç
is still preserved and worshipped in the nearby temple of Vidy<193>·a<209>kara. ç
This image is considered very ancient.
This  temple  was  once  renovated during the period of the Vijayanagar ç
Empire (14th to the 16th centuries). The latest renovation was in ç
<MS>A.<|>D.<D> 1916 resulting in a grand structure.
@SB = The Guruparampar<193>
<185>a<209>kara appointed Sure·vara as the first guru or chief to ç
occupy the pontifical seat, generally called the p<200><219>ha. He ç
reigned over it during the period <MS>A.<|>D.<D> 820-834.
Counting <185>a<209>kara as the first guru, there have been till now, ç
thirty seven gurus.
A few, more well-known, gurus are the following.
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(.2500,1.5692,E1), ç
ABOVE(.0972), VGUTTER(.0278), KEEP(OFF)
@Z_TBL_BODY = TC1, TABLE TEXT, TC1
Order of Succession, +, Period of<|><|>Reign
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
10., Vidy<193>·a<209>kara T<200>rtha, <MS>A.<|>D.<D><|>1229-1333
12., Vidy<193>ra<207>ya, <MS>A.<|>D.<D><|>1380-1386
26., Saccid<193>nandabh<193>rat<200>-I, <MS>A.<|>D.<D><|>1623-1663
27., Narasi<221>ha Bh<193>rat<200>-II, <MS>A.<|>D.<D> 1663-1706
31., Saccid<193>nanda<R>ç
          Bh<193>rat<200>-III, <MS>A.<|>D.<D> 1770-1814
33., Ugranarasi<221>ha<R>ç
             Bh<193>rat<200>, <MS>A.<|>D.<D><|>1817-1879
34., Saccid<193>nanda<R>ç
<+><+><185>iv<193>bhinava <+><+>N<216>si<221>ha Bh<193>rat<200>, <MS>A.<|>D.<D><|>1879-1912
35., Candra·ekhara<R>ç
<+><+><+><+><+><+><+>Bh<193>rat<200>-III, <MS>A.<|>D.<D><|>1912-1954
36., Abhinava Vidy<193>t<200>rtha, <MS>A.<|>D.<D><|>1954-1989
37., Bh<193>rat<200> T<200>rtha, <MS>A.<|>D.<D><|>1989
@Z_TBL_END = 
@SB = Through Fiery Ordeals
As the Ma<219>ha grew in size, activities, and importance, it also ç
had to pass through many fiery ordeals, primarily due to the political ç
turmoils in South India. After the collapse of the Vijayanagara Empire, ç
which acted as a bulwark against all dangers, the monastic institution ç
and its pontiffs had to face many serious problems. However, due to ç
the power of their own tapas (austerities) and the timely cooperation ç
of genuine devotees and well-wishers, all the troubles were tided ç
over.
@SB = The Ma<219>ha at Present
If the goddess <185><193>rad<193> is the central deity of the institution, ç
the pontiff†popularly called <185>a<209>kar<193>c<193>rya†is the focal ç
point of the whole system.
He lives in the monastic quarters in the area known as Narasi<221>havana, ç
on the opposite bank of the river Tu<209>g<193>.
It is his special privilege to offer worship to the li<209>ga, known ç
as Candra-maul<200>·vara (said to have come down from <185>a<209>kara ç
himself) as also the Narasi<221>ha-·<193>lagr<193>ma (a symbol of ç
Vi<218><207>u in his form as Narasi<221>ha).
He often tours all over the country on the invitation from the devotees ç
of theMa<219>ha. During the rainy season he performs the C<193>turm<193>sya ç
vrata (See <MS>C°TURM°SYA.<D>) in any chosen place.
There are several temples in the area of the Ma<219>ha (as also <185><216><209>geri), ç
the chief ones being the <185><193>rad<193> temple, the Vidy<193>-·a<209>kara ç
temple, the Jan<193>rdana temple, the Harihara temple and the Caturm<220>rti ç
Vidye·vara temple.
The ancient temple of <185>iva†called Malah<193>nikare·vara†is  situated  on  a ç
hillock in the centre of the town.
The following are some of the more important festivals celebrated ç
at the Ma<219>ha: Yug<193>di, R<193>manavam<200>, <185>a<209>kara- ç
jayant<200>, Narasi<221>hajayant<200>, Vy<193>sp<220>r<207>im<193>, ç
K<216><218><207>ajanm<193><218><219>am<200>, Ga<207>e·a Caturth<200>, ç
Navar<193>tri, Mah<193>·ivar<193>tri, as also the jayant<200>s (birthdays) ç
and <193>r<193>dhanas (ascension days) of some of the gurus.
The Ma<219>ha is conducting a few public service activities also.
There are about 80 religious institutions spread all over the country†mostly ç
in South India†under its control.
@NT = <185><193>rad<193>tilaka
The <185><193>rad<193>tilaka†also called the <185><193>rad<193>tilakatantra†is ç
one of the best known and the most widely used works of the tantra-group ç
of Hindu scriptures, which deals primarily with up<193>san<193> or ç
meditation (and allied topics) on the various deities of the Hindu ç
pantheon.
Lak<218>ma<207>a De·ikendra (11th century <MS>A.<|>D.<D>) is the author. ç
He was the son of <185>r<200>k<216><218>na and a disciple of Utpal<193>c<193>rya.
Out of the several commentaries on it, the Pad<193>rth<193>dar·a ç
by R<193>ghavabha<219><219>a (circa <MS>A.<|>D.<D> 1493-94) is the ç
most important one.
R<193>ghavabha<219><219>a was the son of P<216>thv<200>dhara and belonged ç
to Janasth<193>na (the modern N<193>sik in Maharashtra). He was a ç
profound scholar and a many-sided genius. He has, in his commentary, ç
drawn the material heavily from the famous Prapa<210>cas<193>ra ç
attributed to °di <185>a<209>kara (<MS>A.<|>D.<D> 788-820). (See <MS>PRAPA<178>CAS°RA.<D>)
The work is in 25 pa<219>alas or chapters and contains 4500 verses ç
in all.
A brief summary of the work may now be attempted here:
@S10N = Chapter 1 (113 verses)
This chapter deals with the philo- sophy of tantras which is allied ç
to S<193><209>khya and Ved<193>nta. See <MS>TANTRAS<D> for details.
@S10N = Chapter 2 (153 Verses)
Since the letters of the alphabet arethe basic material out of which ç
the various mantras are formed, this chapter is devoted to them, their ç
evolution and their varieties.
Mantras  ending  in  pha<219>  are considered masculine, those ending ç
in sv<193>h<193> are feminine and the others ending in nama<199> are ç
neuter.
@S10N = Chapter 3 (135 Verses)
This section deals with V<193>stuy<193>ga, erection  of  ma<207><195>apa  (small  enclosed ç
structure), vedi (platform) with yantras (mystical diagrams) and homa. ç
These are the fundamental rites needed in all the rituals dealt with ç
in the future chapters.
@S10N = Chapter 4 (138 Verses)
The first part of the d<200>k<218><193> (initiation) ceremony is dealt ç
with in this chapter. D<200>k<218><193> is the process by which the ç
evil inthe mind is destroyed (k<218>a = k<218>aya ordestruction) ç
and divine knowledge (d<200>=divyaj<210><193>na) is imparted.
All the details of the ritual to be performed on the first day are ç
given here.
@S10N = Chapter 5 (165 Verses)
The topics of the previous chapter are continued here.
Four kinds of d<200>k<218><193>†kriy<193>vat<200>, var<207>amay<200>, ç
al<193>vat<200> and vedhamay<200>†are described. (See <MS>TANTRAS<D> ç
for details.)
@S10N = Chapter 6 (118 Verses)
From this chapter right up to the twenty-fourth, various mantras along ç
with the accessory subjects like <216><218>i (sage), chandas (metre) ç
and devat<193> (the deity) as also dhy<193>na·loka (verse describing ç
the deity's form for meditation), ny<193>sa (ritual purification of ç
limbs) and pura·cara<207>a (special methods of japa) are described.
@EMERGENCY = This chapter deals with Sarasvat<200> (the goddess of ç
learning) as the personification of the alphabet. She is described ç
as holding a book, a rosary, a vessel of nectar in three hands and ç
the fourth exhibiting the j<210><193>namudr<193> (hand-pose showing ç
knowledge).
@EMERGENCY = The other deities dealt with are: Ardhan<193>r<200>·vara, ç
combined form of Vi<218><207>u and Lak<218>m<200>, Jagad<200>·var<200>, ç
Lak<218>m<200> and transcendent Light called Prapa<210>cay<193>ga-m<220>rti.
@EMERGENCY = There is also a mention of the wonderful properties of ç
the bitter herb called br<193>hm<200> which can enhance intellectual ç
powers when consumed.
@S10N = Chapter 7 (123 Verses)
@EMERGENCY = The first part of this chapter deals with the var<207>as ç
(letters of the alphabet) and their goddesses, Var<207>e·var<200> ç
and V<193>g<200>·var<200>.
@EMERGENCY = Other topics dealt with later are: yantras of the five ç
elements, the V<193>gv<193>din<200>-mantra (that gives the power of ç
speech) a few other mantras and the rules of conduct for one who wants ç
to worship Sarasvat<200>.
@S10N = Chapter 8 (167 Verses)
@EMERGENCY = This chapter is mainly dedicated to <185>r<200> or Lak<218>m<200>, ç
the consort of Vi<218><207>u. Other names by which she is called are: ç
Kamal<193>, Par<193>devat<193> and <185><193>r<209>gipriy<193>.
@EMERGENCY = Recitation of the <185>r<200>s<220>kta of the <184>gveda ç
is recommended to please her.
@EMERGENCY = Rules to be observed by the s<193>dhaka who wants to ç
worship and please her are given at the end.
@S10N = Chapter 9 (107 Verses)
The goddess Bhuvane·var<200> or Bhuvane·<200> is the main topic dealt ç
with here.
Her b<200>j<193>k<218>ara (hr<200>m), description of her form, the ç
nine goddesses adorning the legs of her throne and other allied topics ç
are also given.
A s<193>dhaka, if he takes the br<193>hm<200>gh<216>ta (ghee prepared ç
out of br<193>hm<200> creeper descried in earlier chapters) over which ç
her mantra has been chanted, evolves into a great poet.
Some more mantras of the goddess are also given along with modes of ç
worship.
@S10N = Chapter 10 (123 Verses)
The goddess Tvarit<193> (one who gives results quickly) is the main ç
topic here. Her form, her mantra and all the associated rituals are ç
described.
Other aspects of the goddess dealt with are: Trika<207><219>ak<200>, ç
Vajraprast<193>ri<207><200>, Tripu<219><193>, Annap<220>r<207><193> ç
and Padm<193>vat<200>. Their mantras and modes of worship are also ç
given.
@S10N = Chapter 11 (126 Verses)
This chapter is devoted to the meditation and worship of the goddess ç
Durg<193> and her various aspects. They are: Durg<193>, Mahi<218>amardin<200>, ç
Jayadurg<193>, <185><220>lin<200>durg<193>, Vanadurg<193> and Vindhyav<193>sin<200>.
The  rak<218><193>karayantra  (protective mystical diagram) of the ç
last deity is also given at the end.
@S10N = Chapter 12 (166 Verses)
It begins with a prayer to Tripur<193> and her mantra which is composed ç
of three parts.
The other mantras of Dev<200> dealt with are those of B<193>l<193> ç
and R<193>jam<193>ta<209>gin<200>.
@S10N = Chapter 13 (151 Verses)
Now, worship of the different aspects of Ga<207>e·a is taken up. The ç
primary b<200>jamantra of Ga<207>e·a is ga<221>.
The Mah<193>ga<207>apati mantra of 28 letters is also given.
Other aspects of Ga<207>apati dealt with are: Viriga<207>apati, <185>aktiga<207>apati, ç
K<218>ipra-pras<193>dana-ga<207>e·a and Heramba-ga<207>e·a.
At the end, the mantra of Subrah-ma<207>ya (= K<193>rttikeya) is also ç
given along with his dhy<193>na·loka that describes his form.
@S10N = Chapter 14 (148 Verses)
This chapter starts with the mantra of Soma (Candra, the deity Moon). ç
Thisis then followed by an eight-lettered mantra of S<220>rya (the ç
Sun-god).
Other aspects of Sun dealt with are: Bh<193>nu and M<193>rtta<207><195>a ç
(whose b<200>jamantra, which being very difficult, has to be directly ç
learnt from the guru).
The Ha<221>samantra (same as Ajap<193>-mantra) is also dealt with. ç
It is identified with the Pra<207>ava (Om).
Other mantras given are those of Agni (fire-god) and Turag<193>gni ç
or Va<195>av<193>gni (= Horse-fire, the fire that destroys the created ç
world at the time of pralaya or dissolution).
@S10N = Chapter 15 (147 Verses)
Now, the worship and meditation ofVi<218><207>u is taken up. The ç
famous dv<193>da·<193>k<218>ar<200>-mantra (of 12 letters) is also ç
given.
Though in paur<193><207>ic accounts, the abode of Vi<218><207>u is ç
called Vaiku<207><219>ha, here that term is applied to Vi<218><207>u ç
himself since he is vi (= without) ku<207><219>ha (= limitations).
Then follows an 18 lettered mantra and the description of a yantra.
Other mantras dealt with are those of R<193>ma (including a long one ç
called m<193>l<193>mantra), of Hayagr<200>va and Var<193>ha. A dhar<193>h<216>daya-mantra ç
(on bh<220> or the earth-goddess) is added at the end.
@S10N = Chapter 16 (142 Verses)
First comes the mantra of Narasi<221>ha in his saumya (or peaceful) ç
aspect which is used in propitiatory rites.
Then is given the mantra of Jv<193>l<193>-narasi<221>ha (in his fierce ç
aspect).
Other mantras dealt with are those of the Lak<218>m<200>-n<216>si<221>ha ç
and Sudar·ana (the discus of Vi<218><207>u).
Towards the end six yantras are also described.
@S10N = Chapter 17 (162 Verses)
Vi<218><207>u  as  Puru<218>ottama  and  his mantra of 200 letters ç
is given first.
Other mantras given are those of <185>r<200>kara (8 letters), Gop<193>la ç
(18 letters), K<216><218><207>a (6 letters) and K<193>ma (1 letter).
The method of drawing the K<193>mali<209>gayantra is described towards ç
the end.
@S10N = Chapter 18 (129 Verses)
Now, the mantras of <185>iva are taken up.
<185>iva is he who rules over dharma. His famous mantra consists of ç
six letters.
A mantra of eight letters, another called pras<193>damantra, also ç
of eight letters, are given later.
A short mantra of <185>iva as M<216>tyu<210>jaya is given towards ç
the end.
@S10N = Chapter 19 (132 Verses)
Next comes the mantra of Dak<218>i<207><193>-m<220>rti with associated ç
details.
The other mantras mentioned are those of N<200>laka<207><219>ha, Cint<193>ma<207>i ç
and Kha<195>gar<193>va<207>a.
@S10N = Chapter 20 (160 Verses)
This chapter begins with a long mantra of 52 letters, known as the ç
Aghor<193>stramantra.
The Aghora-form of <185>iva has to be meditated upon as of different ç
hues for different results. For instance, he is to be meditated upon ç
as black for exorcism and as white for mok<218>a or liberation.
Mantras of other aspects given are: P<193>·upat<193>stramantra, K<218>etrap<193>lamantra ç
and °paduddh<193>ra-mantra (of Va<219>uka).
The Va<219>uka aspect of <185>iva can be meditated upon in three forms: ç
t<193>masa, r<193>jasa and s<193>ttvika.
A yantra for averting dangers and a mantra of three letters (of Ca<207><195>e·vara ç
aspect of <185>iva) are also described.
The chapter ends with a beautiful hymn to <185>iva.
@S10N = Chapter 21 (147 Verses)
The work now turns its attention to the Vedic G<193>yatr<200>-mantra, ç
its vy<193>h<216>tis and other details.
The different forms of ny<193>sa and dhy<193>na on the goddess G<193>yatr<200> ç
are also given.
The famous <184>gvedic mantra (1.99.1) in  the  tri<218><219>ubh  metre  <%22>(<MI%0>j<193>tavedase ç
sunav<193>ma somamar<193>t<200>yato...) is dealt with next. This ç
mantra, if chanted in the reverse order, becomes °gney<193>stra-mantra ç
(a mantra as powerful as the arrow of fire). Its uses in fulfilling ç
worldly desires are also given. Atidurg<193>, Ga<207>idurg<193>, Vi·vadurg<193>, ç
Sindhudurg<193> and Agnidurg<193> are the deities to be appeased in ç
these rites.
@S10N = Chapter 22 (164 Verses)
Beginning with the two aspects ofthe Atidurg<193>mantra†Din<193>stra ç
and K<216>ty<193>stra †it gives several injunctions relating to the ç
different purposes for which the mantras can be used.
Ci<219>imantra of 24 letters (a mantra for black-magical rites) is ç
also given along with the details of its usage.
@S10N = Chapter 23 (145 Verses)
This chapter starts with the famous <184>gvedic mantra on <185>iva ç
(7.59.12) known as the M<216>tyu<210>jayamantra.
Meditation on Varu<207>a and his mantra †from the <184>gveda (7.88.7) ç
known as the V<193>ru<207><200>-<216>k†are also given.
A long mantra comprising mostly the letters of the alphabet is given ç
for infusing life into the other mantras.
Some black-magical rites known as <218>a<219>karmas†to gain control ç
over others or harm them†are described towards the end.
@S10N = Chapter 24 (111 Verses)
A major part of this chapter is taken up to delineate 36 different ç
kinds of yantras or mystical diagrams (inscribed on different surfaces ç
by different materials) for achieving different ends.
It closes with a long hymn to the goddess  °nandamay<200>  who  is  <185>abda- ç
brahman, the basic cause of the universe.
@S10N = Chapter 25 (89 Verses)
This chapter deals with yoga. Various definitions of yoga offered ç
by different schools and sects are given first.
Conquest of the ari<218>a<195>vargas (like k<193>ma or lust, krodha ç
or anger and so on) through the eight steps of yoga (See <MS>YOGADAR<185>ANA.<D>) ç
is recommended.
These eight steps are also defined. However, their descriptions vary ç
from the ones given by Pata<210>jali (200 <MS>B.<|>C.<D>) in his Yogas<220>tras. ç
More details are filled up under each item.
In addition, the various n<193><195><200>s and cakras are also described. ç
(See <MS>CAKRAS<D> and <MS>N°£®.<D>)
Other aspects of s<193>dhana dealt with are: methods of <193>sana ç
(ways of sitting for meditation); ten kinds of dhvani or sound heard ç
in meditation; on Pra<207>ava; Brahman in his two aspects of sagu<207>a ç
(with attri-butes) and nirgu<207>a (without attributes); R<193>jayoga ç
as meditation on the Ku<207><195>alin<200>.
The last part describes the union of the j<200>v<193>tman with Para·iva ç
(Brahman).
@SPACE = 
@NT = Saram<193>
According to Vedic mythology as depicted in the <184>gveda (10.108) ç
Saram<193> was a bitch in heaven belonging to Indra. When a group ç
of demons called pa<207>is stole the cows of heaven, Indra sent her ç
on a search mission. She successfully accomplished the task that led ç
to Indra attacking the pa<207>is and recovering the cows.
Her two issues†the dogs S<193>rameyas †were employed as the doorkeepers ç
of Yama, the god of death.
