In later dharma·<193>stra literature, the four Vedavratas were omitted ç
and the following four were added: kar<207>avedha (piercing the ear-lobes); ç
vidy<193>rambha (same  as  ak<218>ar<193>bhy<193>sa,  learning  the ç
alphabet); ved<193>rambha (first study of theVedas); ke·<193>nta ç
(cutting the hair or shaving the beard).
See under each title for details.
@NT = <186>o<195>a·<200>
See <MS>DA<185>AMAH°VIDY°S.
@NT = <186>o<195>a·in
Among the Vedic sacrifices, those that use the soma juice for offering ç
as oblations are called Somay<193>gas.
Out of the seven Somay<193>gas, the <186>o<195>a·in is the fourth. ç
It is performed to attain vigour.
While extracting the soma juice from the cuttings of the plant, sixteen ç
·astras (mantras which are to be chanted and not sung) and sixteen ç
stotras (verses taken from the <184>gveda and set to the musical ç
tunes of S<193>maveda) are used. Hence the name <186>o<195>a·in ç
(comprising sixteen chants).
This is done during the third extraction (= t<216>t<200>yasavana) ç
in the evening.
A quadrangular cup made of khadira wood (Acacia catechu) is used ç
to keep the soma juice.
Indra is the chief deity appeased through this sacrifice.
See  also  <MS>SOMAY°GA <D> and  <MS>VEDIC SACRIFICE.<D>
@NT = <218>o<195>a·opac<193>ras
@N1 = (`sixteen items offered in the worship [of a deity]')
See <MS>DEVAP<188>J°.<D>
@NT = soma
@SPACE = 
@SPACE = 
The word `soma' has been used in several senses. One of the common ç
meaning is Candra or the deity Moon. He is the presiding deity of ç
Somav<193>ra or Monday and one of the Navagrahas or Nine Planets. ç
(See <MS>CANDRA<D> for details.)
In the Vedas it has been used to indicate the soma-creeper, as also ç
its juice, somarasa, which is extensively used to offer as oblations ç
in Somay<193>gas. The twigs of the creeper were brown or tawny in ç
colour and would hang down. It used to grow on hills and mountains. ç
Hence it was difficult for ordinary people to obtain it. Probably ç
some of the hill-tribes were experts in collecting these creepers ç
and supplying them.
Crushing the stalks of this creeper to extract the juice was also ç
a part of Vedic ritualism. This was called `abhi<218>ava' or `savana'.
The  stalks  were  probably  kept immersed in water and then crushed ç
with the stones called gr<193>va and adri, The juice was then filtered ç
in da·<193>pavitra (made of wool) into a vessel called dro<207>akala·a.
Cam<220> was the name of the vessel containing the somarasa for gods. ç
The vessels used by the priests for drinking it were called kala·a ç
and camasa (all made of wood).
In Somay<193>gas, the savana or the extraction of the soma juice from ç
the creepers was done thrice a day: morning (pr<193>tassavana),   noon   (m<193>dhyandina- ç
savana) and evening (t<216>t<200>yasavana). The presiding deities ç
of these were Indra, Maruts and Vi·vedevas for the first, Indraalone ç
for the second and the <184>bhus (human beings raised to the status ç
of gods) for the third.
The soma juice is sometimes mixed with milk or curds or barley. Then ç
it is called gav<193>·ira, daddhy<193>·ira and yav<193>·ira respectively.
Soma is a highly exhilarating drink that induces tremendous energy. ç
Indra is said to be very fond of it; so also the gods to whom it is ç
offered as libation.
It is not at all an intoxicating drink like liquor though, sometimes, ç
prejudiced and ignorant Western scholars dub it so.
Soma seems to have become a rare plant and gone out of vogue even ç
by the time of the Vedic Br<193>hma<207>as. Hence several substitutes ç
like extracts of ph<193>lguna plants, p<220>tik<193> stalks, d<220>b ç
plantsand greenish ku·a grass have been prescribed.
@SPACE = 
@NT = Soman<193>thapura
@SPACE = 
Soman<193>thapura is a small town 40kms. from the Mysore city, Karnataka. ç
Soman<193>tha, who was a minister of the king Narasi<221>ha (the Third) ç
of the Hoysa<202>a dynasty, is said to have built this as an agrahara ç
(a small township for br<193>hma<207>as). He built two temples, one ç
for Vi<218><207>u and the other for <185>iva in <MS>A.<|>D.<D> 1258. ç
The former is known as the Ke·ava temple and the latter as the Pa<210>cali<209>ge·vara ç
temple.
The Ke·ava temple stands in the centre of the courtyard measuring ç
65 metres (218 ft.) by 35 metres (117 ft.). It has three sanctums ç
and three towers, each of 9 1/2 metres (32 ft.) height. The whole ç
structure is on a jagat<200> (platform) almost a metre high. Attached ç
to the high pr<193>k<193>ra (boundary wall) there are 64 verandah-like ç
structures with pillars.
The towers (vim<193>na) of the sanctum have a few beautiful sculptures. ç
The vim<193>nas are capped with inverted lotus-like structures.
The pr<193>k<193>ra has three rows of figures depicting scenes form ç
the R<193>m<193>ya<207>a, the Mah<193>bh<193>rata and the Bh<193>gavata.
Out of the three garbhag<216>has or sanctums, the central one is empty. ç
It is said to have contained the image of Ke·ava. The other two shrines ç
contain the images of Jan<193>rdana and Ve<207>ugop<193>la (aspects ç
of Vi<218><207>u).
Some of the beautifully carved images are those of N<216>tyaga<207>apati, ç
N<216>tyalak<218>m<200>, Indra on his royal elephant Air<193>vata, ç
K<220>rm<193>vat<193>ra (Tortoise incarnation), Durg<193>, Sarasvat<200> ç
and Para·ur<193>ma.
The <185>iva temple has five sanctums for five aspects of <185>iva: ç
Bijjale·vara, Perga<195>e·vara, Revale·vara, Bayirale·vara and Soman<193>the·vara. ç
Though these shrines are independent, they have a common verandah ç
or portico.
The Ke·ava temple is an excellent specimen of Hoysa<202>a Architecture, ç
rivalling the ones in Bel<220>r and Ha<202>eb<200><195>u.
@NT = Somn<193>th Temple
The temple of Somn<193>th†also spelt as Soman<193>tha†can rightly ç
be described as the phoenix of the Hindu ethos. No sooner was the ç
temple razed to the ground by the barbarian marauders who invaded ç
the country (India) than it would rise again!
Situated in the small town of Prabh<193>s Pa<219>an in the Saurashtra ç
area of the modern Gujarat state, on the shore of the Arabian Sea, ç
it is the first of the twelve Jyotirli<209>gas (`li<209>gas of light') ç
mentioned in the pur<193><207>as.
The original icon, called the Spar·ali<209>ga (almost the size of ç
a hen's egg), was vouchsafed to Soma (the deity Moon) by Lord <185>iva ç
who was immensely pleased by his severe austerities. Hence, the li<209>ga ç
got the appellation Soman<193>tha (Lord of Soma or the Moon).
The first temple over it was, as per legend, built by Moon in gold. ç
Subsequently†as it was ravaged in course of time†it was rebuilt by ç
R<193>va<207>a in silver, by K<216><218><207>a in wood and by Bh<200>ma ç
in stone.
Prabh<193>s Pa<219>an is an important pilgrim centre, associated with ç
K<216><218><207>a's final departure from the world. The river Sarasvat<200> ç
was said to join the ocean here.
There is a reference to Somn<193>th even in the <184>gveda (khila ç
part at the end of the 9th ma<207><195>ala).
The Prabh<193>sakha<207><195>a of the Skanda-pur<193><207>a deals ç
with this subject in great detail.
Historically, one of the first temples might have been built by the ç
Valabh<200> kings sometime during the 5th century <MS>A.D.<D> From ç
the ruins at the site, it is surmised that a temple might have existed ç
even in <MS>A.<|>D. <D>4.
This place was a stronghold of the P<193>·upata cult started by Lakul<200>·a ç
before <MS>A.<|>D.<D> 600.
@SPACE1 = 
The Somn<193>th temple was the wealthiest at its time, before being ç
looted by Ghazni Mohammed in <MS>A.<|>D.<D> 1026. The earnings from ç
ten thousand villages were dedicated to it as offering. For the daily ç
worship, water was being brought from the river Ga<209>g<193> and ç
flowers from K<193>·m<200>ra. One thousand br<193>hma<207>as were ç
engaged in its worship, in various ways. A very heavy chain of gold ç
was used to ring the temple bell.
The<|> temple<|> hall <|>(ra<209>gama<207><195>apa) contained 56 gem-studded ç
pillars, each encrusted with gold sheets.
The li<209>ga in the garbhag<216>ha or the sanctum was 3 metres (10 ç
ft.) high and 1.8 metres (6 ft.) in diameter. The sanctum itself was ç
very majestic. There were three paths leading to it.
A golden palanquin had been gifted by the Sola<209>ki king Bh<200>mdev, ç
to carry the utsavam<220>rti (processional icon).
This very wealth and splendour tempted Ghazni Mohammed to plunder ç
and destroy the temple in <MS>A.<|>D.<D> 1026.
Thereafter,<|> reconstruction <|>by<|> the local kings and destruction ç
by the Muslim invaders went on for several centuries, the last destruction ç
being the one by Aurangazeb in <MS>A.<|>D.<D> 1706.
Ahalyabai<|> Holkar<|> built <|>another temple near the ruins in <MS>A.<|>D.<D> ç
1783.
@SPACE1 = 
After independence, the temple was rebuilt, the garbhag<216>ha being ç
located in the original place, the <185>ivali<209>ga being established ç
on the same brahma·il<193> (See <MS>BRAHMA<185>IL°.<D>). The credit ç
goes mainly to Sard<193>r Vallabh-bhai Pa<219>el (<MS>A.<|>D.<D> 1875-1950), ç
the then Deputy Prime Minister of India. Dr. R<193>jendra Pras<193>d ç
(<MS>A.<|>D.<D> 1884-1963) the then President of India, opened the ç
rebuilt shrine on the 11th May 1951. The whole complex was completed ç
only in 1995. Dr. <185>a<209>kar Day<193>l <185>arma, who was the ç
President of India at that time, dedicated it on 1st December. It ç
has been built in the C<193>lukyan type of temple architecture.
The vim<193>na (tower over the sanctum) of the new temple is 50 metres ç
(164 ft.) high. There are intricate carvings and silver doors. The ç
Nandi (reclining bull) isquite elegant. Other idols also find appropriate ç
places in the temple-complex.
In and around the Somn<193>th temple there are quite a few places ç
of religious significance like G<200>t<193> Mandir, Lak<218>m<200>-n<193>r<193>ya<207> ç
Temple, Baldev-guf<193> (cave), Trive<207><200>sa<209>gam, Para·ur<193>mak<218>etra, ç
Sun-temple and others.
A statue of Sard<193>r Pa<219>el stands out in the precincts, in commemoration ç
of his historic association with the reconstruction of this temple ç
of Somn<193>th.
@NT = somas<220>tra
<185>iva is said to be fond of shower bath as also a regular bath! ç
Hence, the <185>ivalli<209>gas (or li<209>gas) installed in temples ç
are bathed either continuously or during the ceremonial worship. On ç
one side of the li<209>ga, there is a small projected channel to convey ç
the water thus poured, to a vessel kept below it. This channel is ç
called `somas<220>tra'. While circumambulating the li<209>ga, the ç
somas<220>tra should not be crossed. The devotee should start from ç
it, go round the li<209>ga clockwise and return anticlockwise after ç
reaching the other side of the same.
The water collected in the vessel is used as t<200>rtha (consecrated ç
water for sipping) by the devotees.
See also <MS><185>IVALI<177>GA.
@NT = Somay<193>ga
@N1 = (`Vedic sacrifice [using] soma juice')
Vedic sacrifices†called y<193>gas and yaj<210>as†are generally classified ç
into three groups, out of which the Somay<193>gas form the last. They ç
are called so since the soma juice is the main ingredient of the oblations.
There are seven Somay<193>gas which are the models. They are: Agni<218><219>oma, ç
Aptory<193>ma, Atir<193>tra, Atyagni<218><219>oma, <185>o<195>a·<200>, ç
Ukthya and V<193>japeya.
A Somay<193>ga needs mantras from all the three Vedas†<184>gveda, ç
Yajurveda and S<193>maveda†as also all the sixteen <216>tviks or ç
priests.
The soma juice is extracted from the creeper three times. The extraction ç
is called pr<193>tassavana, m<193>dhyandinasavana and t<216>t<200>yasavana, ç
done in the morning, noon and late afternoon.
See <MS>AGNI<186><187>OMA<D> and <MS>VEDIC SACRIFICES<D>.
@NT = so<218>yant<200>-karma
@N1 = (`a rite for a woman<R>ç
about to deliver')
This is a very ancient rite meant for the safe delivery of the baby, ç
from the mother who is in labour pains. The mantras from the <184>gveda ç
(5.78.7-9) and the Atharvaveda (1.11.1-7) are used as prayers and ç
magical chants for the safety of both the mother and the baby.
Keeping the T<220>ryant<200> plant at the feet of the woman about ç
to deliver the baby and sprinkling the water collected from a river ç
or a spring on her head by her husband with appropriate mantras is ç
an important aspect of this rite.
@NT = soul
See <MS>°TMAN.<D>
@NT = spanda
@N1 = (`vibration')
This is a typical technical term used by one of the schools of K<193>·m<200>r ç
<185>aivism.
Based on the <185>ivas<220>tras of Vasugupta (9th century <MS>A.<|>D.<D>), ç
Kalha<219>a or Kalla<219>a (<MS>A.D.<D> 854) wrote a small work of ç
51 verses called Spandak<193>rik<193> which expounds the theory ç
of spanda.
<185>iva is the supreme Lord. When his ·akti or inherent power starts ç
the process of creation, with the very first wave or vibration, it ç
is called spanda. The 36 evolutes are manifested out of this.
See <MS><185>AIVISM.
@NT = spar·ayoga
See <MS>MANTRAYOGA.
@NT = Spho<219>av<193>da
@N1 = (`the doctrine of ``breaking<R>ç
forth'' ')
This is the theory of the school of grammarians.
How does the meaning of a word flash in the mind? When a person utters ç
the word `cow,' its meaning as an animal of certain peculiar characteristics ç
flashes across the mind immediately after the word is fully uttered. ç
That factor or principle or power by which this happens is called ç
`spho<219>a'. This spho<219>a is different from the individual letters ç
of the word which die or disappear as soon as they are uttered. Only ç
after the last letter is uttered, does the meaning flash in the mind. ç
Hence, it is not the letters that produce the meaning. A separate ç
factor different from them, but which gets manifested through their ç
combination like a flash, has to be accepted. This is spho<219>a. ç
It applies to a sentence also.
@NT = sphura<207>a
@N1 = (`throbbing [of limbs]')
Prognostication by observing the throbbing of one's limbs seems to ç
be an ancient field of knowledge.
Apart from some of the pur<193><207>as like the Matsya (241.1-14), ç
some independent works like the Vasantar<193>ja·akuna (by Vasantar<193>ja ç
who might have lived in circa <MS>A.<|>D.<D> 700) also deal with this ç
subject in great detail.
The limbs involved in throbbing may be any one from the head to the ç
foot.
For men, all throbbings of limbs on the right side indicate auspicious ç
results; and on the left, inauspicious ones. For women it is exactly ç
the opposite.
A few of these (for men) may now mentioned here:
@Z_TBL_BEG = COLUMNS(2), DIMENSION(IN), KEEP(OFF)
@Z_TBL_BODY = TC1, TC1
Limb, Prognostication
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT
Top of the head.<R>ç
Forehead.<R>ç
<R>ç
Region of the eye.<R>ç
Upper arm.<R>ç
Hand.<R>ç
Back.<R>ç
Chest.<R>ç
Soles., Acquisition of land.<R>ç
Prosperity in the <R>ç
   present position.<R>ç
Death.<R>ç
Union with friends.<R>ç
Wealth.<R>ç
Defeat.<R>ç
Success.<R>ç
Journey with gains.
@Z_TBL_END = 
Sa<221>ny<193>sins were prohibited from practising such arts to gain ç
alms.
The results of inauspicious indications can be offset by giving gifts ç
as prescribed in the ·<193>stras (vide Matsya-pur<193><207>a 241.14).
See also <MS><185>°NTIS.<D>
@NT = sphya
@N1 = (`wooden sword')
See <MS>VEDIC SACRIFICES.<D>
@NT = spiritualism
See <MS>BH<188>TAVIDY°.<D>
@NT = ·raddh<193>
@N1 = (`faith')
<185>raddh<193> or faith is the fifth in the list of ·am<193>di<218>a<219>ka ç
(hexad of the disciplines beginning with ·ama or tranquillity). It ç
is defined as unwavering faith in the words of the ·<193>stra (the ç
relevant scripture) and of the guru (spiritual preceptor).
@NT = <185>r<193>ddha
@SB = Introduction
Birth and death have always remained a great mystery to man. If birth ç
has been hailed, death has been abhorred and feared. For one who believes ç
that death is the end of life and of one's personality, it is an ogre ç
that devours him and decimates him. The `all-important' HE suddenly ç
becomes a NIHIL! However, the one who trusts God, feels that He is ç
with him during his life here and also hereafter.
While most of the religions of the world believe in some sort of life ç
after death, the Hindus consider death as atransition from one life ç
to another. According to them, the disembodied soul badly needs help ç
and succour from its descendants, not only during the period following ç
the death of the physical body but also during its journey to other ç
worlds. It is here that comes the role of the various rites performed ç
immediately after death but also other rites that are repeated every ç
month for a year or even, every year. These rites generally go by ç
the name ·r<193>ddha.
It appears that the worship of one's ancestors by means of post-death ç
ceremonies like antye<218><219>i and ·r<193>ddha was a very ancient ç
institution. In several passages of the <184>gveda the pit<216>s ç
or forefathers have been mentioned and have, sometimes, been identified ç
with `sapta <216><218>aya<199>' (`seven sages') like the Navagvas ç
or Da·agvas.* Occasionally, they have also been divided into several ç
groups such as `pitara<199> somavanta<199>'  (`those  who  performed ç
Somay<193>gas')  or  `pitara<199>  barhi<218>ada<199>' (`those that ç
did p<193>kayaj<210>as, with cooked offerings'). Sometimes they have ç
been described as inhabiting a separate world of their own, the Pit<216>loka. ç
Rites such as pi<207><195>apit<216>yaj<210>a and mah<193>pit<216>yaj<210>a ç
have been ordained compulsorily for the <193>hit<193>gnis (those who ç
have duly consecrated the Vedic fires). These seem to be the precursors ç
of the latter-day rites of ·r<193>ddha.
@SB = Theory of Karma and<R>ç
Punarjanma versus <185>r<193>ddha
According to the theory of karma and punarjanma†widely believed in ç
and propagated by Hinduism†anyone who dies here is reborn (punarjanma ç
= rebirth) either in this world or in other abodes of existence, depending ç
on his karma or actions. This goes on until he attains mok<218>a or ç
freedom from transmigration by spiritual wisdom. Hence, when a person ç
offers the pi<207><195>as or rice-balls in the ·r<193>ddha rites, ç
what certainty is there that their essence reaches and sustains the ç
ancestor for whom it is meant? This question has been discussed and ç
debated even in the sm<216>tis and allied works. The principal reply ç
is that the scriptures being the final authority regarding the things ç
beyond the ken of the sense-organs, one has just to trust them and ç
do as they direct. According to them, the offerings are received by ç
the special classes of deities called Vasus, Rudras and °dityas†the ç
guardians of the pit<216>s†who transmit their essence to the concerned ç
ones in a form that suits their level of existence, be they in heaven ç
or hell, in human or subhuman bodies. They may also reward the living ç
descendants whohave performed the ·r<193>ddha, in an appropriate ç
manner.
@SB = Literature on <185>r<193>ddha
The literature on ·r<193>ddha is legion. Apart from the hoary Vedic ç
Sa<221>hit<193>s, the subject has found a place in the ancient Sm<216>tis ç
of Manu and Y<193>j<210>avalkya as also the G<216>hyas<220>tras of ç
°pastamba and °·va-l<193>yana. The Dharmas<220>tras of Baudh<193>yana ç
also deal with this subject.
Some of the pur<193><207>as too have presented the subject of ·r<193>ddha ç
fairly exten- sively. They are:
@IN2 = Agnipur<193><207>a<R>ç
Brahmapur<193><207>a<R>ç
Garu<195>apur<193><207>a<R>ç
K<220>rmapur<193><207>a<R>ç
M<193>rka<207><195>eyapur<193><207>a<R>ç
Matsyapur<193><207>a<R>ç
Vi<218><207>udharmottara-pur<193><207>a<R>ç
Vi<218><207>upur<193><207>a
@SPACE = 
Apart from these, there are several compendiums describing exhaustively ç
the same subject. A few of them are listed below:
@IN2 = K<216>tyakalpataru of Lak<218>m<200>dhara<R>ç
Sm<216>ticandrik<193> of <185>ukadevamitra<R>ç
Sm<216>tyarthas<193>ra of N<200>laka<207><219>h<193>c<193>rya<R>ç
<185>r<193>ddhacandrik<193> of Rudradhara<R>ç
<185>r<193>ddhakalpalat<193> of Nandapa<207><195>ita<R>ç
<185>r<193>ddhakriy<193>kaumud<200> of<R>ç
                  Govind<193>nanda<R>ç
<185>r<193>ddhamay<220>kha of N<200>laka<207><219>ha<R>ç
<185>r<193>ddhatattva of Raghunandana<R>ç
<185>r<193>ddhaviveka of <185><220>lap<193><207>i
@SPACE = 
The approximate dates of some of these authors are as follows:
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(.3333,E1,E1), ABOVE(.0139), ç
BELOW(.0417), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
, °pastamba, †<|>450 <MS>B.C.<D>
, Baudh<193>yana, †<|>500 <MS>B.C.<D>
, Govind<193>nanda, †<|><MS>A. D.<D> 1500-1540
, Manu (or the extant Manusm<216>ti), +
, , †<|>200 <MS>B.C.<D>
, Raghunandana, †<|><MS>A. D.<D> 1510-1580
, Rudradhara, †<|><MS>A. D.<D> 1360-1400
, <185><220>lap<193><207>i, †<|><MS>A. D.<D> 1365-1445
, Y<193>j<210>avalkya, † 100 <MS>B. C.
, <+><+>(or the extant Y<193>j<210>avalkyasm<216>ti), +
@Z_TBL_END = 
The periods of the others are not known, even approximately.
@SB = Meaning of the Word <185>r<193>ddha
The term `·r<193>ddha' is derived from the root-word `·raddh<193>' ç
or faith. Hence, whatever is offered with ·raddh<193> becomes a ·r<193>ddha. ç
However, the term has been widely used in a strictly technical senseas ç
related to after-death rites and subsequent ceremonies.  Putting  all  the  various ç
definitions of the word together, their contents can be summarised ç
as follows:
@SPACE1 = 
@N = a)
@NK = It is performed by a competent descendant of the dead ancestors, ç
with ·raddh<193> or faith.
@N = b)
@NK = It is done for the benefit of three generations of ancestors, ç
viz., father, grandfather and great-grandfather.
@N = c)
@NK = It has to be executed at the appropriate time and place as determined ç
by the·<193>stras or scriptures and family traditions.
@N = d)
@NK = It may be accomplished by giving either cooked food or uncooked ç
articles of food or gold (money) to worthy br<193>hma<207>as.
A ·r<193>ddha is said to have been accomplished by the followers of ç
the <184>gveda if they honour the worthy br<193>hma<207>as. For ç
the followers of the Yajurveda, pi<207><195>ad<193>na (offering ç
cooked rice-balls to the pit<216>s) is more important. However, the ç
followers of the S<193>maveda are expected to do both.
@SB = The Performer of <185>r<193>ddha (Kart<193>)
When a person dies, his antye<218><219>i (last rites) and ·r<193>ddha ç
are to be done by his eldest son.* If he has more than one son and ç
if they are all living separately, then each of them is entitled to, ç
and expected to, perform the ·r<193>ddha ceremony.
In case the deceased person has no sons, then any of the near (male) ç
relatives like a brother, an adopted son, son-in-law or a grandson ç
can do it.
If the son is too young and had not had his upanayana then the wife ç
of the dead person can get it done through a priest.
@SPACE = 
@SB = For Whom <185>r<193>ddha should be done
@SPACE1 = 
The most-widely accepted general rule is that ·r<193>ddha must be ç
performed for the benefit of (dead) father, grandfather and great-grandfather ç
(paternal). It can be done for others also in case they are near relatives ç
with no male issues. When a woman dies, her ·r<193>ddha can be done ç
by her eldest son. If she has no male issues, the grandson can do ç
it. If there is no grandson, the daughter can get it done through ç
the br<193>hma<207>a priests.
As for an unmarried woman, when she dies, her ·r<193>ddha can be done ç
by her father or the eldest of the brothers or the nearest male relative.
In the case of persons dying an unnatural death (like suicide or by ç
an accident and so on) n<193>r<193>ya<207>abali is to be offered first. ç
The ·r<193>ddha can be performed one year after this.
No  ·r<193>ddha  is  performed  for sa<221>ny<193>sins (ascetics or ç
monks) since they have already done it for themselves, at the time ç
of taking sa<221>ny<193>sa.
@SPACE = 
@SB = Tim<BI%10>e<D%0><|>and Plac<BI%10>e<D%0><|>Appropriate fo<BI%10>r<D%0><|><185>r<193>ddha
@SPACE1 = 
The most common day for the performance of the ·r<193>ddha of a dead ç
person is the day of his death as per the lunar calendar. For instance, ç
if a person dies on the M<193>gha·ukla-a<218><219>am<200> day (i.e., ç
the eighth day of the bright fortnight in the month of M<193>gha [January-February]<|>) ç
the ·r<193>ddha has to be done on that day only, every year.
The <193>hit<193>gnis (those who have ceremonially established the ç
Vedic fires) however, were to perform the ·r<193>ddhas (for others) ç
only on the dar·a (am<193>v<193>sy<193> or new-moon) days.
It is interesting to note that every householder of the first three ç
var<207>as or castes was expected to perform pa<210>ca-mah<193>-yaj<210>as ç
or five sacrifices everyday, in which pit<216>yaj<210>a or tarpa<207>a ç
(satiating the ancestors) comprising offering of food or water or ç
milk or fruits, was an integral part.
<185>r<193>ddhas may also be performed on certain days considered ç
good or auspicious. For instance: am<193>v<193>sy<193> (new-moon day); ç
a<218><219>ak<193> days (eighth day in the dark fortnight  of  the  months  M<193>rga·ira ç
[November-December], Pau<218>a [December-January], M<193>gha and Ph<193>lguna ç
[January-March]); dark half of any month; the two ayanas or solstices ç
(in June and January); the sa<209>kr<193>nti days (days of Sun's apparent ç
entrance into the twelve zodiacal signs like Aries); on joyous occasions ç
like the birth of a son and other periods like eclipsedays considered ç
auspicious by the scriptures.
Certain days classified as yug<193>di or manvantara by the lunar calendars ç
are stated to be extremely auspicious for the performance of ·r<193>ddhas.
Monthly ·r<193>ddhas are generally performed during the first year ç
after death only.
As for the time, apar<193>h<207>a or afternoon is prescribed, rather ç
than forenoon.
@SPACE1 = 
Coming to the topic of a suitable spot for the performance of ·r<193>ddha, ç
generally, a clean spot sloping towards the south is recommended. ç
If it is not frequented by people and if it can be covered on all ç
sides, it becomes an ideal place. However, performing it in one's ç
own house is very common and also convenient.
@SPACE1 = 
Performing ·r<193>ddhas in holy placesand places of pilgrimage is ç
highly commended. The following places are frequently mentioned and ç
even recommended: Gay<193> (Bihar), Prabh<193>sa (Gujarat), Pu<218>kara ç
(Rajasthan), Pray<193>ga (Uttar Pradesh); on the banks of Ga<209>g<193> ç
and Yamun<193>; Amaraka<207><219>aka (Madhya Pradesh) on the bank ç
of Narmad<193>; V<193>r<193><207>as<200>   (Banaras   or   K<193>·<200>)   and ç
Kuruk<218>etra (Haryana).
<185>r<193>ddhas should not be done in Mleccha countries; i.e., countries ç
inhabited by people who do not observe the var<207>a-<193>·rama system.
@SB = Classification of <185>r<193>ddhas
<185>r<193>ddhas  have  been  variously classified:
@N = 1)
@NK NO # = nitya, naimittika, k<193>mya.
@N = 2)
@NK NO # = ekoddi<218><219>a and p<193>rva<207>a.
@N = 3)
@NK NO # = aharaha··r<193>ddha, p<193>rva<207>a·r<193>ddha, v<216>ddhi·r<193>ddha, ç
ekoddi<218><219>a ·r<193>ddha and sapi<207><195><200>-kara<207>a.
Nitya·r<193>ddhas are to be compulsorily performed on a certain or ç
fixed occasion such as everyday, on an am<193>v<193>sya day or on ç
a<218><219>ak<193> days.
@SPACE1 = 
The naimittika ·r<193>ddhas are to be done when there is a special ç
nimitta or a cause such as the birth of a son.
The k<193>mya·r<193>ddhas are done for the fulfilment of certain desires.
Some writers of dharma·<193>stras haveincreased the number to twelve, ç
by adding some more to these lists, such as go<218><219>h<200>·r<193>ddha, ç
·uddhi·r<193>ddha, y<193>tr<193>-·r<193>ddha, pu<218><219>i·r<193>ddha ç
and so on.
Out of these, ekoddi<218><219>a, p<193>rva<207>a, sapi<207><195>ana ç
(or sapi<207><195><200>kara<207>a) and v<216>ddhi ·r<193>ddhas are ç
considered the principal ones.
In the ekoddi<218><219>a rite, the ·r<193>ddha is performed with respect ç
to only one, the dead person (eka = one, uddi<218><219>a = concerning). ç
Only one pi<207><195>a is offered.
In the p<193>rva<207>a rite, three pi<207><195>as are offered to father, ç
grandfather and great-grandfather.
The sapi<207><195>ana rite is done on the twelfth day after death, ç
and signifies the union of the spirit of the dead person with those ç
of his ancestors.
The v<216>ddhi·r<193>ddha, also called n<193>nd<200>mukha·r<193>ddha, ç
is performed on all auspicious occasions like marriages of sons and ç
daughters, entering a new house and so on. In this ·r<193>ddha, the ç
three paternal ancestors beyond the great-grandfather †they are called ç
n<193>nd<200>mukhapit<216>s†are satiated by appropriate rites.
@SB = The P<193>rva<207>a <185>r<193>ddha
During the Vedic days, every <193>hit<193>gni was obliged to perform ç
the pi<207><195>apit<216>yaj<210>a on am<193>v<193>sy<193> days. The ç
annual ·r<193>ddha still in vogue, is a replica of this yaj<210>a. ç
This is called p<193>rva<207>a·r<193>ddha. It is also, sometimes, ç
designated as m<216>t<193>ha-anna-·r<193>ddha.
This rite involves a number of steps which may be described very briefly.
At the outset, the performer of the ·r<193>ddha (called kart<193> ç
or ·r<193>ddhakart<193>) has to invite competent br<193>hma<207>as ç
on the previous day itself to attend the ·r<193>ddha and to receive ç
the honours as also food. Only those br<193>hma<207>as who do not ç
belong to the same gotra or lineage, who are learned, who are married, ç
healthy and have a blameless character are to be invited. This process ç
of invitation is called k<218>a<207>a.
Though two br<193>hma<207>as are to be invited to represent the Vi·vedevas* ç
and three to represent the pit<216>s, in practice, only one each is ç
requested.
Yatis or sa<221>ny<193>sins are considered to be ideal invitees. But ç
they do not accept such invitations!
@SPACE1 = 
From the moment the invitation is extended, both the kart<193> and ç
the bhokt<193>s (invitees) have to observe celibacy and other codes ç
of conduct like speaking truth, not getting angry and so on, strictly.
@SPACE1 = 
As for wearing the religious marks on the forehead (like vibh<220>ti ç
or tripu<207><195>ra) on this occasion, it is left to the traditions ç
existing in the family of the kart<193>.
@SPACE1 = 
The following materials are expected to be used during the ·r<193>ddha ç
both in the cooked and in the uncooked form:
@SPACE1 = 
Milk, Ga<209>g<193> water, honey, sesame, wheat, m<193><218>a (a kind ç
of pulse, Phaseolus mungo), green gram, and things cooked in oil.
@SPACE1 = 
Friends of the same lineage, cousins and those who have been benefactors ç
(and of the same caste) can be invited to cook the food for ·r<193>ddha.
@SPACE1 = 
Daughters-in-law of the kart<193> are to be preferred to serve the ç
food to the br<193>hma<207>as.
@SPACE1 = 
Sa<209>kalpa or religious resolve by the kart<193>, as per the details ç
given in the concerned scriptures, stating the procedure of the rite, ç
will be the first act.
Establishing a kala·a (pot of consecrated water) and sprinkling its ç
water all over the place connected with the ·r<193>ddha comes next.
To receive the invitee-br<193>hma<207>as, two ma<207><195>alas or ç
diagrams (one a square and the other, a circle) are to be drawn on ç
the floor of the house at a suitable place. The former is for the ç
br<193>hma<207>a representing the Vi·vedevas and the latter for the ç
one representing the pit<216>s. The kart<193> washes their feet on ç
these ma<207><195>alas.
Next comes the casting of the sesame with appropriate mantras over ç
the place of the ·r<193>ddha to drive away the demons, devils and ç
other evil spirits.
This is followed by the worship of the Vi·vedevas through the first ç
br<193>hma<207>a and the pit<216>s through the second br<193>hma<207>a. ç
Arghyap<193>tras†vessels containing water mixed with sesame and darbha ç
grass†are very important in this ritual.
Then comes p<193><207>ihoma or offering a small quantity of cooked ç
rice into the right hand of the br<193>hma<207>a who represents the ç
pit<216>s.
This is followed by br<193>hma<207>a-bhojana or feeding the invitees. ç
They should be served delicious food to their satisfaction. When they ç
are eating, other br<193>hma<207>as are requested to chant some mantras ç
likethe R<193>k<218>oghnamantras, Pavam<193>na-mantras or Upani<218>ads. ç
This is called abhi- ·rava<207>a and it creates a spiritual mood in ç
the minds of the br<193>hma<207>as who are eating. Since it is believed ç
that the pit<216>s have entered into these br<193>hma<207>as with ç
their ethereal bodies, it is they who will enjoy the food and feel ç
uplifted.
Pi<207><195>aprad<193>na comes next. Pi<207><195>as are rice-balls ç
prepared by mixing the cooked rice and other cooked articles of food, ç
left over in the vessels (after the br<193>hma<207>as have been fed). ç
Three such balls are kept on the ground covered with darbha and offered ç
to the three generations of pit<216>s.
According to one practice (recommended by Baudh<193>yana) the pi<207><195>as ç
are to be placed in such a place where crows can come and eat them. ç
The pit<216>s are believed to enter their bodies in a subtle form ç
and be satisfied by those pi<207><195>as.
The br<193>hma<207>as then disperse after blessing the kart<193> and ç
his family. The kart<193> is expected to follow them over some distance ç
as a mark of respect.
The entire rite is then offered to Lord V<193>sudeva (N<193>r<193>ya<207>a ç
or K<216><218><207>a) with a prayer for forgiveness for the faults ç
that may have crept into it.
@SPACE = 
@SB = Gay<193>·r<193>ddha
@SPACE = 
For centuries, performing ·r<193>ddha forone's ancestors at Gay<193> ç
has been considered not only extremely auspicious but also obligatory ç
on the part of the eldest son (or anyone of the sons). It is supposed ç
to bestow infinite results.
Gay<193>·r<193>ddha has three stages. First, the kart<193> has to ç
take bath in the river Phalgu and offer tarpa<207>a (satiatory rite) ç
with water and pi<207><195>as into the river. Then he should offer ç
pi<207><195>a at the feet of Vi<218><207>u in the temple dedicated ç
to Lord Vi<218><207>u. Later he must offer the pi<207><195>a at the ç
foot of the well-known Ak<218>ayava<219>a (the banyan tree). This ç
completes the rite.
Gay<193>·r<193>ddha can be performed by anyone for himself also.
@SPACE = 
@SB = Finis
@SPACE = 
Observance of the ·r<193>ddha ceremonies is still in vogue in the ç
Hindu society in some form or the other. Though doubts have been cast ç
over the need to observe them or their efficacy, by the modern Hindus, ç
the spirit behind them, viz., showing our love, affection and respect ç
to our dead ancestors, at least the immediately preceding forefathers, ç
has to be appreciated by one and all.
Apart from the rites to be observed immediately after the death of ç
the person as also the ·r<193>ddhas performed every month for the ç
first one year, only the annual ·r<193>ddha is being observed by persons ç
belonging to the first three castes.The procedure is more or less ç
the same as described in the p<193>rva<207>a-·r<193>ddha section.
For those whose faith in these rites has been shaken due to the onrush ç
ofmodern ideas and English education, Dr. P. V. Kane has suggested ç
the following via media:
@IN2 = <+><+><+>It is a good practice to set apart at least one day in ç
a year for the remembrance of one's near and dear relatives that are ç
no more, to invite relatives, friends and learned people to a dinner ç
in memory of the dead and to bestow monetary gifts on poor but learned ç
persons of character and devoted to the practice of plain living and ç
high thinking. This will be in keeping with our past traditions and ç
will also give a new orientation to and infuse new life into practices ç
that have become lifeless and meaningless to many people.*
To this may be added the following religious observances and disciplines ç
also: Fasting  (either  partial  or  complete), worship of the family ç
deity, meditation and japa and earnest prayer to God for the peace ç
and bliss of the departed ones.
It is thus seen that the performance of ·r<193>ddha, though an ancient ç
practice, deserves to be kept up even now, at least in a modified ç
form.
@NT = <185>rautas<220>tras
It is quite difficult to understand theVedas because of the archaic ç
language and the esoteric rites described there, mostof which are ç
completely unfamiliar and unknown to us today. However, the six Ved<193><209>gas ç
(subsidiary sciences of the Vedas) help us to a great extent in unraveling ç
their mystery and even guide us to perform these Vedic rites.
Out of the six Ved<193><209>gas, the last one is called Kalpas<220>tras. ç
This again has branched off into four fields, the first of which is ç
the <185>rautas<220>tras.
@SPACE1 = 
The <185>rautas<220>tras are concerned mainly with the details connected ç
with the performance of the Vedic sacrifices. A few of these may be ç
listed as follows:
The yajam<193>na (sacrificer) and the <216>tviks (priests); agny<193>dheya ç
(production of fire from the ara<207>is or wooden pieces for the sacrifice); ç
details of the performanceof
