The basic treatises of <185>r<200>vidy<193> are the following: Lalit<193>sahasran<193>ma ç
of the Brahm<193><207><195>apur<193><207>a with its commentary Saubh<193>gyabh<193>skara ç
by Bh<193>skarar<193>ya Makhin (18th century <MS>A.<|>D.<D>); Lalit<193>tri·at<200>, ç
also from the same pur<193><207>a, with a bh<193><218>ya by <185>a<209>kara ç
(<MS>A.<|>D. <D>788-820); Nitya<218>o<195>a-·ik<193>r<207>ava (from ç
the V<193>make·varatantra) with the commentary Setubandha by Bhaskarar<193>ya  Makhin;  Para·ur<193>ma- ç
kalpas<220>tra; Varivasy<193>rahasya, also by Bh<193>skarar<193>ya ç
Makhin.
The best known teachers of <185>r<200>vidy<193> are the following: ç
Manu, Candra, Kubera, Lop<193>mudr<193>, Manmatha, Agastya, Nandi-ke·vara, ç
S<220>rya, Vi<218><207>u, <185>iva, Skanda and Durv<193>sas.
The <185>r<200>vidy<193>, as a religio-spiritual system has three ç
aspects: the philosophy, the ritual and the contemplation.
The Ultimate Reality is one in whichthere is a perfect merging of ç
<185>iva (consciousness) and <185>akti (power). There arises in its ç
mind the desire to become many. This is called vimar·a (deliberation). ç
This creates spanda (throb or stir) which  develops  into  n<193>da  (vibration), ç
getting concentrated into a bindu (point).
@SPACE1 = 
This bindu gradually swells, giving rise to a polarisation of <185>iva ç
(Father- principle) and <185>akti (Mother-principle), retaining at ç
the same time the original latent and potent status containing the ç
<185>iva-<185>akti combination. These three now form a triangle as ç
it were. This process goes on getting repeated until it results in ç
a pattern now well-known as the <185>r<200>cakra, representing the ç
whole creation. (See <MS><185>R®CAKRA<D> also.)
The ritual consists in the worship of the <185>r<200>cakra†also known ç
as <185>r<200>yantra if it is in the form of a drawing, and Meru, ç
if a three-dimensional icon†with several items of worship. This is ç
called `bahiry<193>ga'.
As a continuation of the spiritual evolution brought about by the ç
performance of a devoted bahiry<193>ga, `antary<193>ga' results.
It is the spiritual contemplation of the <185>r<200>cakra as identified ç
with the Divine Mother Lalit<193>-Tripurasundar<200>. At this stage, ç
every act of the s<193>dhaka (the worshipper) is elevated to the level ç
of spiritual experience as depicted in the Saundaryalahar<200> (verse ç
27).
In t<193>ntrik terminology, this entire process, which is in perfect ç
harmony with the Vedic tradition, is called `Samay<193>c<193>ra' (Samay<193><|>=<|>Dev<200>).
Repetition of the pa<210>cada·<193>k<218>ar<200>-mantra becomes an ç
integral part of this antary<193>ga.
This mantra, as its very name indicates, has pa<210>cada·a (or fifteen) ç
ak<218>aras (or letters). Unlike a word or a sentence comprising several ç
letters of the alphabet giving some sensible meaning, these fifteen ç
letters produce subtle vibrations revealing the subtle body or form ç
of the goddess.
There  are  two  versions  of  this mantra, one beginning with the ç
letter ka (hence called the `K<193>dimata') attributed tothe sage ç
Agastya and the other with the letter ha (hence termed `H<193>dimata') ç
promulgated by his wife Lop<193>mudr<193>.
@SPACE1 = 
The only difference between these to versions is in the number of ç
effective letters used.
(See <MS>PA<178>CADA<185>°K<186>AR®-MANTRA.<D>)
Though  there  are  several  other versions of the mantra, they are ç
not very common.
The mantra of the K<193>dimata is:
@SPACE = 
ka, e, <200>, la, hr<200><221>;
ha, sa, ka, ha, la, hr<200>m;
sa, ka, la, hr<200>m.

In the H<193>dimata, it is:
@SPACE = 
ha, sa, ka, la, hr<200><221>;
ha, sa, ka, ha, la, hr<200>m;
sa, ka, la, hr<200><221>.
@SPACE = 
Equally famous and very much in vogue is the <218>o<195>a·<200>mantra, ç
the mantra with sixteen letters, got by adding ·r<200><221> at the ç
end.
Another mantra is the b<193>l<193>mantra (ai<221>, kl<200><221>, ç
sau<199>) which is addressed to the goddess as a b<193>l<193> or ç
a small girl.
In the Vedic as also the t<193>ntrik tradition, every mantra has a ç
<216><218>i (seer), devat<193> (deity) and chandas (metre). For the ç
pa<210>cada·<193>k<218>ar<200>-mantra, Dak<218>i<207><193>m<220>rti ç
(an aspect of <185>iva) is the <216><218>i. Lalit<193>- Tripurasundar<200> ç
is the devat<193>. Pa<209>kti is the chandas (a Vedic metre with five ç
syllables in each quarter).
The pa<210>cada·<193>k<218>ar<200>mantra is divided into three k<220><219>as ç
or parts each being given a separate name:
First part†V<193>gbhavak<220><219>a.
Second part†K<193>mar<193>jak<220><219>a.
Third part†<185>aktik<220><219>a.
These three represent the face, the torso and the legs (and feet) ç
of the deity. Hence a devoted repetition of this mantra helps in visualising ç
the whole form of the deity.
<185>r<200>vidy<193> is a highly esoteric science of spiritual wisdom. ç
Hence it has to be received from an adept guru in a proper manner ç
as described in the t<193>ntrik works. Otherwise it can do more harm ç
than good!
@NT = ·rotriya
@N1 = (`one who is well-versed in the <185>ruti [Vedas]')
@SPACE = 
Vedas are known as <185>ruti. Hence a ·rotriya is one who is well-versed ç
in the <185>rutis.
However, the word has often been used in a technical sense. According ç
to the Padmapur<193><207>a (Uttarakha<207><195>a, Chapter 116) ç
one who is born to br<193>hma<207>a parents is called a br<193>hma<207>a. ç
By undergoing the sa<221>sk<193>ras or sacraments, he becomes a dvija ç
(`twice born'). By studying the Vedas he becomes a vipra. If he is ç
endowed with all the three factors, he becomes a ·rotriya.
According to another version (as given in some of the dharma·<193>stras) ç
a ·rotriya is one who has studied his branch of the Veda, along with ç
the six Ved<193><209>gas and is performing the six allotted duties, ç
viz., adhyayana (study of the Vedas), adhy<193>pana (teaching the ç
Vedas), yajana (performing sacrifices), y<193>jana (getting the sacrifices ç
done by others), d<193>na (giving gifts) and pratigraha (receiving ç
gifts).
In ·r<193>ddha ceremonies, feeding a ·rotriya is considered highly ç
meritorious.
A king should see that no ·rotriya in his kingdom remains uncared ç
for.
@SPACE = 
@SPACE1 = 
@NT = s<216><218><219>i
@N1 = (`creation')
See <MS>COSMOLOGY.
@SPACE = 
@SPACE1 = 
@NT = <185>rutaprak<193>·ik<193>
@N1 = (`exposition of what is heard')
B<193>dar<193>ya<207>a's  Ved<193>ntas<220>tras  is  a basic work ç
of Ved<193>nta philosophy on which many <193>c<193>ryas (spiritual ç
preceptors and founders of the systems of philosophy) have written ç
learned commentaries.
R<193>m<193>nuja's (<MS>A.<|>D.<D><|>1017-1137) commentary on it is ç
well-known as <185>r<200>bh<193><218>ya. The earliest and the most ç
authoritative subcommentary on it is the <185>ruta-prak<193>·ik<193> ç
of Sudar·anas<220>ri (<MS>A.<|>D.<D> 1200-1275). He was a disciple ç
of V<193>tsya Varad<193>c<193>rya (<MS>A.<|>D.<D> 1165-1275) who was ç
also called Na<195><193>d<220>r Amm<193><202>.
When V<193>tsya Varad<193>c<193>rya used to deliver enlightening discourses ç
on the <185>r<200>bh<193><218>ya of R<193>m<193>nuja, Sudar·anas<220>ri ç
used to listen attentively and make notes. Based on that, he composed ç
his detailed subcommentary. He named it as <185>ruta-prak<193>·ik<193> ç
because it expounded (or brought to light, prak<193>·ik<193>) what ç
he had heard (·ruta).
Being a detailed and unambiguous exposition it is regarded highly ç
in Vi·i<218><219><193>dvaita circles.
@NT = stars
See <MS>NAK<186>ATRA.<D>
@NT = sthalapur<193><207>a
@N1 = (`local legend')
Every place of pilgrimage, including its temples and sacred spots, ç
has its own ancient story to tell. Such legends are transferred mostly ç
by oral tradition, though the more famous ones have been incorporated ç
in the well-known pur<193><207>as and upapur<193><207>as. These are ç
generally called sthalapur<193><207>as.
One of the interesting factors to be noted in such sthalapur<193><207>as ç
is that some renowned personalities from the epics and the pur<193><207>as ç
like R<193>ma, Hanum<193>n and K<216><218><207>a, the P<193><207><195>ava ç
brothers, sages like N<193>rada, Vasi<218><219>ha and Agastya, or ç
even great kings like Vibh<200><218>a<207>a, Prahl<193>da and Bali ç
will have visited almost all the places!
@NT = sth<193>l<200>p<193>ka
@N1 = (`boiling or cooking in the earthen pot')
@SPACE = 
Sth<193>l<200> is an earthen bowl used for holding rice grains.
When husked grains are cooked in the sth<193>l<200>, on the dak<218>i<207><193>gni ç
(See <MS>DAK<186>IØ°GNI.<D>), mixed with clarified butter they form ç
the sth<193>l<200>p<193>ka. It is used as an oblation to the pit<216>s.
It is also the name of a sacrifice belonging to the p<193>kayaj<210>a ç
group (See <MS>VEDIC SACRIFICES.<D>). It is performed on the first ç
full-moon day after marriage by the married couple. Its continued ç
performance on the day of full-moon and new-moon throughout their ç
lives has been recommended.
@NT = sth<193>naka
@N1 = (`standing [posture]')
Images of deities installed in temples are generally of three types: ç
sth<193>naka (standing), <193>s<200>na (sitting) and ·ay<193>na (reclining).
Images of the sth<193>naka type are the most common ones. These images ç
can be samap<193>da (when the two feet are close together) or vi<218>amap<193>da ç
(where one leg is straight and the other slightly bent and placed ç
at a distance from the former).
See also <MS>M<188>RTI<185>ILPA<185>°STRA.<D>
@NT = stha<207><195>ila
The homa rites (See <MS>HOMA<D> for details.) performed as a part ç
of g<216>hya or domestic religious ceremonies must always be performed ç
on a stha<207><195>ila.
A stha<207><195>ila is a raised and perfectly levelled altar or platform ç
of sand or loose earth raised by two or four finger breadths. It is ç
a square measuring one i<218>u (or length of an arrow i.e., 18 a<209>gulas) ç
on all sides. The measurement may be 21 or even 32a<209>gulas.
Lines†one  horizontal  and  five vertical†are drawn as prescribed, ç
on which the fire is placed.
The sacrificer sits facing the east, whereas the Brahm<193> priest†the ç
only priest in such rites†sits facing north.
@NT = sthapati
@N1 = (`architect')
See <MS><185>ILPA<185>°STRA.
@NT = Sth<193>patyaveda
@N1 = (`Veda or treatise of the sthapati [architect]')
See <MS><185>ILPA<185>°STRA<D>.
@NT = sthitapraj<210>a
@N1 = (`person of steady wisdom')
See <MS>BHAGAVADG®T°.<D>
@NT = sth<220>ladhy<193>na
@N1 = (`gross meditation')
Ha<219>hayogic works like the Ghera<207><195>a Sa<221>hit<193> (6.2 ç
to 14) describe this sth<220>la-dhy<193>na. It is meditation on the ç
chosen deity in the heart.
The heart has to be imagined as a sea of nectar in which there is ç
a beautiful island of precious stones, full of flowering and fruit-giving ç
trees. In the midst of it there is a platform with a throne on which ç
the deity is seated.
The form of the deity including the dress and the ornaments is also ç
described in such works.
@SPACE = 
@NT = sth<220>la·ar<200>ra
@N1 = (`the gross body')
@SPACE1 = 
According to the Ved<193>nta, the j<200>va or the individual soul, ç
is enveloped in three ·ar<200>ras or bodies. They are: sth<220>la·ar<200>ra ç
(gross or physical body); s<220>k<218>ma·ar<200>ra (subtle body, also ç
called li<209>ga·ar<200>ra); and, k<193>ra<207>a·ar<200>ra (causal ç
body).
The sth<220>la·ar<200>ra is given by the parents and nourished by ç
food. It is subjected to <218>a<195>vik<193>ras or six changes viz.,  birth, ç
existence, growth, change, decay and death.
Karma or the result of the actions of previous lives is an important ç
factor in shaping this body.
See also <MS>K°RAØA<185>AR®RA<D> and <MS>LI<177>GA-<185>AR®RA<D>.
@SPACE = 
@NT = stobha
@N1 = (`[letters used] in praise')
@SPACE = 
In S<193>mavedic chants, certain letters like h<193>-u, h<193>-i, ç
hum, ho, oh<193>, <200> and <220> are used for musical interjections ç
and interpolated into a s<193>man. They are actually additional letters, ç
not part of the letters of the original <184>gvedic mantras which ç
have been set to the musical notes of the S<193>maveda.
See also <MS>S°MAVEDA.
@NT = stoma
@N1 = (`praise')
Stotras are <184>gvedic mantras set to the S<193>mavedic tunes.
A stoma is a group of such verses and has several names depending ç
on the number of repetitions. They are, for instance, pa<210>cada·astoma ç
(15), saptada·a-stoma (17), ekavi<221>·astoma (21) and so on.
These stomas are arranged in two or more different varieties called ç
vi<218><219>uti.
For instance, the <193>jyastotra (chantedduring the morning pressing ç
of soma juice), consists of three verses (<184>gveda 6.16.10-12) ç
which can be called a, b and c. Then in a pa<210>cada·astoma of 15 ç
verses the arrangement will be as follows:
@IN2 = 1st pary<193>ya or round†a a a b c;<R>ç
2nd pary<193>ya or round†	a b b b c;<R>ç
3rd pary<193>ya or round†a b c c c.
This is called pa<210>capa<210>cin<200>-vi<218><219>uti.
@NT = stotra
@N1 = (`chant of praise')
The word stotra is used in two senses: the Vedic and the paur<193><207>ic.
The Vedic stotra is composed of verses taken mainly from the <184>gveda. ç
These verses are chanted as per the rules of intonation, especially ç
those of the S<193>maveda.
A stotra always precedes a ·astra, (which is a laud that is just recited).
It may be in any<|>one<|>of the innumerable melodies (s<193>man), and ç
stobhas (See <MS>STOBHA.<D>) are added at appropriate places.
All stotras are chanted (or sung) by the udg<193>t<216> and his assistants, ç
prastot<216> and pratihart<216>.
In Somay<193>gas the stotras are spread over all the three savanas. ç
(See <MS>SAVANAS.)<D>
According to the pur<193><207>as and devotional literature, a stotra ç
is a hymn of the outpourings of the heart of a devotee of God. Stava, ç
stuti and nati are the equivalents for the word stotra.
Though they may be in any language, either in prose or in poetry, ç
only the Sanskrit  hymnal  literature  will  be considered here. They ç
are legion.
@SPACE1 = 
The subject matter of these stotras may be ranging from the sublime ç
heights of philosophy or mystical experiences, right up to petitioning ç
for the small comforts of life here and now.
A few of these may be mentioned here: description of the form of God ç
(or a deity) seen in a vision; request for pardon of sins committed ç
knowingly or unknowingly; prayer for the removal of problems and difficulties ç
and request for the grant of the good things of life; desire for obtaining ç
devotion, knowledge and detachment that help one in spiritual life; ç
a spontaneous outburst of emotion after deep spiritual experience ç
and so on.
Stotras containing 108 names, 300 names or 1008 names of a deity are ç
also commonly met with. They are used mostly in ritual chanting or ç
ceremonial worship.
Another type called Suprabh<193>ta-stotras (`good-morning hymns!') ç
are also quite common and popular. Hindu tradition prescribes that ç
these stotras can be chanted after meditation or worship.
@NT = str<200>
@N1 = (`woman')
See <MS>WOMAN.<D>
@NT = str<200>dhana
@N1 = (`woman's wealth')
@SPACE = 
In the Hindu society, a woman was always required to be protected ç
by a male member of the family. Generally speaking that responsibility ç
had devolved on the father before marriage, on the husband after marriage ç
and on the son after the husband's demise.
However, since situations of emergency could always arise, provision ç
had to be made for her maintenance. Str<200>dhana was an important ç
mode of achieving it.
Literally, str<200>dhana means the wealthgiven to the woman, becoming ç
her property, with her full rights over it. The money and presents ç
given to her by her father, mother, brothers or near relatives before ç
her marriage, and by her husband and others during or after marriage ç
constituted str<200>dhana. It could include immovable property also. ç
During her lifetime, no one else, not even her husband, had any right ç
or control over it. With her consent it could be used for the good ç
of the family during emergencies.
There  were  rules  regarding  the distribution or disposal of her ç
str<200>dhana after her demise. Generally speaking, itwas to be given ç
to the unmarried daughters.
If the husband had taken her str<200>-dhana partly or wholly as a ç
debt and died before clearing it, it was the duty of the sons to clear ç
that debt!
@SPACE = 
@NT = Str<200>parva
@SPACE = 
It is the eleventh book of the great epic Mah<193>bh<193>rata.
See <MS>MAH°BH°RATA.<D>
@NT = sty<193>na
@N1 = (`langour')
The Yogas<220>tras of Pata<210>jali (200 <MS>B.C.<D>) lists nine ç
antar<193>yas or obstacles to yoga (1.30). Sty<193>na (apathy or langour) ç
is the second of such obstacles. It is mental laziness and has to ç
be overcome by great will power and self-effort.
@NT = Sub<193>la Upani<218>ad
This is a fairly long minor Upani<218>ad, assigned to the <185>ukla ç
Yajurveda. It has 16 kha<207><195>as (sections), the total number ç
of mantras being 67. Almost the whole Upani<218>ad is in prose.
A brief summary of the Upani<218>ad may now be attempted here:
@S10N = Kha<207><195>a 1 (6 mantras)
Nature  of  Brahman  without attributes; creation of the world.
@S10N = Kha<207><195>a 2 (4 mantras)
Puru<218>a (the Supreme Person); creation of scriptures, various beings, ç
and the reverse process (of dissolution).
@S10N = Kha<207><195>a 3 (3 mantras)
Attainment of the °tman by practising the six disciplines viz., satya ç
(truth), d<193>na (charity), tapas (austerity), ahi<221>s<193> (non-violence), ç
brahmacarya (celibacy) and nirvedana (detachment or renunciation).
@S10N = Kha<207><195>a 4 (4 mantras)
On the dahar<193>k<193>·a (space in the region of the heart) and the ç
three states of consciousness.
@S10N = Kha<207><195>a 5 (15 mantras)
This section which is fairly long, describes how the various organs, ç
their objects and their presiding deities are all connected by n<193><195><200>s ç
(tubular structures similar to nerves) and how the <193>tman activates ç
them all.
He (the <193>tman) is the knower of all, the supreme ruler of all, ç
fit to be worshipped by all and unaffected in any way. He is indescribable.
@S10N = Kha<207><195>a 6 (7 mantras)
This section declares that the whole creation has proceeded out of ç
N<193>r<193>ya<207>a and that he is everything.
@S10N = Kha<207><195>a 7 (2 mantras)
That N<193>r<193>ya<207>a is the inner Self (antary<193>min) of everything ç
is the subject matter of this kha<207><195>a.
@S10N = Kha<207><195>a 8 (1 mantra)
The <193>tman lives in the impure body but is ever pure, shining and ç
divine.
@S10N = Kha<207><195>a 9 (16 mantras)
Dissolution of the entire creation into Brahman during pralaya; result ç
of knowing that Brahman is becoming that Brahman; means of attaining ç
Brahman (through Ved<193>ntic disciplines like repeating the Vedas, ç
self-control, renunciation and sam<193>dhi).
@S10N = Kha<207><195>a 10 (2 mantras)
All the worlds have been established in Brahman. One who knows it, ç
becomes Brahman.
@S10N = Kha<207><195>a 11 (1 mantra)
This section describes the four types of n<193><195><200>s and the ç
result of departure of the soul through these. Exit through the fourth ç
n<193><195><200> called apunarbhav<193> gives the soul liberation.
@S10N = Kha<207><195>a 12 (1 mantra)
This short section deals with the purity of food. One should not consume ç
food which is stale and gone bad. A sa<221>ny<193>sin can eat the ç
food brought to him unasked by his devotees, but should not plan for ç
it.
@S10N = Kha<207><195>a 13 (2 mantras)
The mode of s<193>dhana of a sa<221>ny<193>sin is described here. ç
His characteristics after attaining perfection are also given.
@S10N = Kha<207><195>a 14 (1 mantra)
This kha<207><195>a, using the analogy of the food and the eater, ç
comes to the conclusion that Brahman (called Paradeva) is the substratum ç
of all the `eaters'.
@S10N = Kha<207><195>a 15 (1 mantra)
How does one who is vij<210><193>naghana (a realised soul) burn or ç
destroy the seed of rebirth? As he rises above the body at the time ç
of death, he burns everything from pr<193><207>a right up to m<216>tyu ç
(death), because of the very realisation.
@S10N = Kha<207><195>a 16 (1 mantra)
This gives the tradition of transmitting Brahmavidy<193>†whom to give ç
and whom not to give. The importance of devotion to the guru is also ç
stressed.
@SPACE = 
@NT = Subhadr<193>
@SPACE = 
Subhadr<193> was the daughter of Vasudeva and Devak<200>, and the ç
younger sister of K<216><218><207>a.
Arjuna,  the  P<193><207><195>ava  hero,  and Subhadr<193> were in ç
love with each other. Since Balar<193>ma, the elder brother of K<216><218><207>a ç
was against their marriage, K<216><218><207>a worked out a stratagem ç
by which they eloped. Later on they were married.
Abhimanyu was her son. He was an extraordinarily brave warrior and ç
was ruthlessly killed by the Kauravas by unethical means, in the Kuruk<218>etra ç
war.
After the war, she went to Dv<193>rak<193> to live with her brothers.
She is one of the three deities worshipped in the Jagann<193>th temple ç
at Pur<200> (in Orissa).
See also <MS>ABHIMANYU<D> and <MS>ARJUNA.<D>
@NT = Subrahma<207>ya
If Ga<207>apati is universally revered by almost all the Hindus, Buddhists ç
and Jains, and has even succeeded in going abroad to many countries ç
of South East Asia, China, Japan and Afghanistan, Subrahma<207>ya ç
his brother, has somehow remained confined to South India. Historically ç
speaking, he is a much older deity, being mentioned in stone inscriptions ç
and shown on coins (1st cent. to 5th cent. <MS>A.D.<D>), and was ç
well-known in North India. The sixth day of a lunar month (<218>a<218><219>h<200>) ç
is considered sacred to him (as with serpent deities). He is said ç
to have been married to a forest maid Va<202><202>iamma. The peacock ç
is his carrier mount. His temples are usually found on hill-tops. ç
All these factors may indicate that he was a sylvan deity connected ç
with serpent worship and tree-worship, and hence was more popular ç
among the people of lower strata in the society. Now, however, all ç
sections of Hindus have accepted him and venerate him.
He is said to have been born of <185>iva from P<193>rvat<200>, to ç
destroy the demon T<193>rak<193>sura. Before conceiving him, even ç
these Parents of the World had to perform severe tapas or austerities! ç
This teaches the world, of the great need for tapas on the part of ç
the parents desirous of excellence of offspring. He is stated to have ç
been born in a forest of arrow-like grass (hence the name <185>arava<207>abhava) ç
and reared by the six divine mothers of the constellation K<216>ttik<193> ç
(Pleiades). Hence the names `K<193>rttikeya' and `<186>a<207>m<193>tura'. ç
It seems he assumed six faces to suckle the milk of the six mothers ç
and so got the appellation `<186>a<195><193>nana or <186>a<207>mukha'. ç
He was appointed the commander-in-chief of the gods and thus became ç
`Deva-sen<193>pati'. With his matchless weapon, the<185>akti or lance, ç
shining brilliantly likefire, he easily destroyed T<193>rak<193>sura, ç
thus becoming `<185>aktidhara' and `T<193>rak<193>ri'. Being very ç
young and virile he is `Kum<193>ra' or `Sanatkum<193>ra.' A forceful ç
attacker in war, he is known as `Skanda'. `Skanda' also means one ç
who has accumulated the power of chastity. He likes holy people (br<193>hma<207>as) ç
and is always good to them. Hence he is `Subrahma<207>ya'. Once he ç
broke down the Krau<210>caparvata (a mountain), earning  the  name  Krau<210>cabhett<193>.  At ç
another time he exposed Brahm<193>'s ignorance of the Vedas and hence ç
got the name Brahma-<185><193>st<193>. His other names are Guha (the ç
secret one), G<193><209>geya (son of Ga<209>g<193>) and Sv<193>min<193>tha ç
(the preceptor of his own father).
In icons, he is known as a boy either with one head and two arms or ç
with six heads and twelve arms. His lance and hispeacock are also ç
prominently displayed. A fowl adorns his banner.
@SPACE1 = 
Subrahma<207>ya, the son of <185>iva and <185>akti, represents the ç
highest state to which a spiritual aspirant can evolve. Etymologically ç
the word `Subrahma<207>ya' means `one who tends the spiritual growth ç
of the aspirants'. It is only he who has reached the summit of spiritual ç
perfection in this life, that is capable of tending the spiritual ç
growth of others. Mythology describes him as the Son of God begotten ç
to save the world from the tyranny of the fiend T<193>rak<193>sura. ç
This is more true in the spiritual sense.
Subrahma<207>ya,  the  <186>a<207>mukha,  is depicted with six heads ç
and twelve hands, all of them being attached to one trunk resting ç
on two feet.
Of course, even a boy knows that biologically this is impossible even ç
as an angel with wings is! But a concept like this can be conceded ç
if it fits into useful philosophical postulations. His six heads represent ç
the five sense organs and the mind, which co ordinates their activities. ç
When these are controlled, refined and sublimated, man becomes a superman. ç
This is the implication of the symbology.
According to Yoga psychology, there are six centres of psychic energy, ç
of consciousness, in the human body, designated as Cakras. They are: ç
M<220>l<193>dh<193>ra (atthe anus), Sv<193>dhi<218><219>h<193>na ç
(at the root of the sex organ), Ma<207>ip<220>ra (at the navel), An<193>hata ç
(at the region of the heart), Vi·uddha (at the throat), °j<210><193> ç
(between the eyebrows) and Sahasr<193>ra at the top of the head which ç
is the destination for this energy. When the yogi successfully raises ç
his psychic energy to this topmost centre he has a vision of <185>iva-<185>akti.
@SPACE1 = 
Though it is the same energy that flows through all the six centres, ç
in the case of an ordinary being it is concentrated in the three lowest ç
centres. In a perfect being the flow is so refined and uniform, that ç
practically all the centres have been elevated to the highest level. ç
Subrahma<207>ya represents this perfected state of spiritual consciousness.
Man has only two hands. But, his superior intellect has enabled him ç
to invent so many tools and instruments through which he can accomplish ç
many manual tasks, even simultaneously. Subrahma<207>ya with his twelve ç
hands, symbolically represents this power and capacity of man.
The combination of the six heads and twelve hands teaches us that ç
the ideal of humanity is the perfected being who is not only a great ç
Yogi but also a great worker!
Subrahma<207>ya has two consorts: Va<202><202>i and Devasen<193>. ç
The former is the daughter of a humble chieftain of a race given to ç
agriculture and woodcraft. The latter is the daughter of Indra, the ç
king of gods. This is just to show that God does not make any distinction ç
between the humble folk and the elite. He loves both equally. Alternatively, ç
this can also mean that the true leader of a society will espouse ç
agriculture and industry on the one hand, and the armed forces on ç
the other, in order to develop the society as also to protect it.
The lance of dazzling brightness is the weapon with which this Devasen<193>pati ç
vanquished many an enemy. It actually stands for knowledge and wisdom ç
with which all the ugly demons of ignorance can be destroyed.
@SPACE1 = 
The peacock is his mount. It is shown as belabouring a snake with ç
one of its legs. The snake stands for time. The peacock that kills ç
it stands for what is opposed to it. By riding the peacock he is showing ç
that he is beyond what is within time and outside it. He is beyond ç
all dualities.
If the snake represents lust, as it often does in the symbology of ç
psychology, the peacock signifies the power of celibacy. As Skanda, ç
he is the very personification of the powers of chastity and hence ç
is shown as riding on the peacock.
Lastly, the peacock, with its beautiful plumage, represents creation ç
in all its glory. Hence he that rides it is the Supreme Lord, the ç
master of creation.
See <MS>SUBRAHMAØYA-<186>A<186><187>I<D>.
@NT = subrahma<207>y<193>
The udg<193>t<216>, the third priest (from among the four) in a Soma ç
sacrifice, has three assistants. Of these, subrahma<207>ya is the ç
last. One of his special duties is to recite a litany called `subrahma<207>y<193>,' ç
which is an <193>hv<193>na (call) to Indra, repeated thrice. Recitation ç
of this litany is done on the second and subsequent days of the Agni<218><219>oma ç
sacrifice. This litany contains several adjectives of Indra.
@NT = Subrahma<207>ya-<218>a<218><219>h<200>
@SPACE = 
@SPACE = 
°<218><193><195>ha ·ukla <218>a<218><219>h<200> is dedicated to the ç
worship of Subrahma<207>ya or Skanda, the brave son of <185>iva and ç
commander-in-chief of the devas or gods. Hence it is called Subrahma<207>ya<218>a<218>th<200> ç
or Skanda-<218>a<218><219>h<200>. It is an extremely popular and widely ç
observed festival in Tamil Nadu. Those desirous of getting a good ç
son or desirous of health for their sickly children are specially ç
advised to observe this festival. Offering of lamps, garments and ç
live cocks (as playthings) is a speciality of this festival.
Devotees who want to get over great calamities in their life take ç
a vow to carry the k<193>va<195>i, a wooden stick with two baskets ç
at the ends. They observe strict celibacy, beg their food and offerings ç
for the Lord and walk bare-footed all the way to a famous shrine of ç
Subrahma<207>ya like the ones at Tirucand<220>r or Pa<202>ani (both ç
in Tamil Nadu). After reaching the place they ceremonially offer the ç
things they have brought.
The   Subrahma<207>ya   temple   at Tirucand<220>r commemorates his ç
victory over Surapadma or T<193>rak<193>sura. Corresponding to the ç
six days of the war, a six days' severe penance is prescribed for ç
the devotees who are willing to undergo it. They stay within the temple ç
complex and fast on all these days. On the day of the Skanda<218>a<218><219>h<200> ç
they do not partake even water.
On that day, events leading to theconquest of the demon by Lord Subrahma<207>ya ç
are dramatised and enacted on the sea-beach.
According to some works, the festival falls on Caitra ·ukla <218>a<218><219>h<200> ç
(in March/ April), but is rarely observed on that day.
@NT = s<220>c<200>hasta
@N1 = (`needle [pose] of hand')
This is one of the hand-poses shown in the images of gods and goddesses. ç
It is a gesture of the right hand, in which the forefinger is held ç
upright and all the other fingers are pressed against the palm. It ç
signifies several things such as threat, warning, beating of drum, ç
truth, or the numbers one and hundred.
The pose is also called s<220>c<200>mukhahasta.
@NT = <185>uc<200>ndram
@N1 = (`[the place where] Indra was purified')
<185>uc<200>ndram is mainly famous for its beautiful temple built ç
in the 17th century. It is 13 kms. (8 miles) from the famous pilgrimage ç
centre, Kany<193>kum<193>r<200>, the southern-most tip of the Indian ç
peninsula.
The main shrine is contained in the hollow of a laurel tree, believed ç
to be 2000 years old. It is one li<209>ga representing all the three ç
Hindu deities, Brahm<193>, Vi<218><207>u and <185>iva. The bottom ç
of the li<209>ga represents Brahm<193>, the middle part Vi<218><207>u ç
and the top <185>iva.
The sage couple, Atri and Anas<220>y<193>, got a boon that the three ç
deities should be born as their children. Consequently they took birth ç
as Candra, Datt<193>treya and Durv<193>sas. This li<209>ga is the ç
combined form of these three.
The entrance gopuram (main gate) isa seven-storeyed structure 40 ç
metres (134 ft.) high. There is a huge carved Nandi (<185>iva's bull) ç
said to be 800 years old. At the entrance to the main temple are two ç
large door-keepers.
According to the local legend, Indra who had committed the sin of ç
adultery  with Ahaly<193>, did tapas (severe austerity) here, worshipping ç
the Trim<220>rtis (the three deities mentioned above), and was purified. ç
The very name <185>uc<200>ndram (·uci = purification; of Indra) indicates ç
this.
The temple campus contains 30 minor shrines dedicated to Vi<218><207>u ç
(with a metallic image of eight metals), S<200>t<193>r<193>ma, Ga<207>e·a ç
and Navagrahas (the nine planets). There is also an image of Hanum<193>n ç
5.4 metres (18 ft.) high.
Sculptures from the R<193>m<193>ya<207>a and the Mah<193>bh<193>rata ç
as also the four musical pillars of stone carved out of a single block ç
of granite are added attractions. Each pillar gives the sound of a ç
different instrument, that of m<216>da<209>ga, sit<193>r, tamp<220>ra ç
and jalatara<209>ga.
On Fridays there is a special sun-set ceremony. Daily rituals, however, ç
close before dusk since Indra is believed to come then and perform ç
the worship, the whole night.
Non-Hindus are allowed to enter this temple.
@NT = Sud<193>ma
Sud<193>ma (or <185>r<200>d<193>ma) as a poor br<193>hma<207>a boy, ç
was a classmate and an intimate friend of K<216><218><207>a in the ç
gurukula (forest academy) of the sage S<193>nd<200>pani. Since he ç
used to wear bad and worn out clothes, he was also called Kucela.
After marriage and with a big family he used to suffer much due to ç
poverty. At the insistence of his wife, he went to Dv<193>rak<193> ç
to see K<216><218><207>a and beg some wealth from him. He had carried ç
with him some flattened rice for K<216><218><207>a as an offering. ç
When K<216><218>na ate a handful of the same, his house at his village ç
was transformed into a palatial mansion with plenty of wealth!
He is cited as an example of sakhya-bhakti (devotion to God as a friend) ç
(videBh<193>gavata 10.80 and 81).
@NT = Sudar·ana
@N1 = (`that which has a nice<R>ç
appearance')
Sudar·ana is the name of the cakra or discus of Lord Vi<218><207>u. ç
In his incarnation as K<216><218><207>a he used this weapon quite ç
often.
@SPACE1 = 
According to certain <185>aiva pur<193><207>as, <185>iva is said to ç
have gifted it to Vi<218><207>u who had worshipped him with great ç
devotion at K<193>·<200>.
In iconography Sudar·ana is treated as <193>yudhapuru<218>a (personified ç
deity of the weapon) and also as an independent deity. He is shown ç
as a figure similar to Vi<218><207>u, but with six arms (or hands). ç
Behind him there is a hexagonal frame enclosed in a flaming circle.
@NT = Sudar·anacakra
@N1 = (`the discus of pleasing appearance')
See <MS>CAKRA.<D>
@NT = Sudar·anas<220>ri
@N1 = (<MS>A.<|>D.<D> 1200-1275)
He was the son of Digvijayabha<219><219>a and the grandson of Vedavy<193>sabha<219><219>a ç
whohimself was the second son of K<220>re·a, the famous disciple ç
of R<193>m<193>nuja (<MS>A.<|>D.<D> 1017-1137).
He was the author of the now famous <185>rutaprak<193>·ik<193>, ç
a detailed gloss on the <185>r<200>bh<193><218>ya of R<193>m<193>nuja.
Ved<193>nta De·ika (<MS>A.<|>D.<D> 1268-1369) was his younger contemporary, ç
who tactfully managed to save Sudar·anas<220>ri's book as also his ç
two sons during the Muslim invasion of South India.
The other works of Sudar·anas<220>ri are: <185>rutaprad<200>pik<193>, ç
T<193>tparyad<200>pik<193>, <185>ara<207><193>gatigadyabh<193><218>ya, ç
a commentary on the Sub<193>lopani<218>ad, Sandhy<193>vandana-bh<193><218>ya ç
and K<218>am<193><218>o<195>a·<200>.
@NT = Sud<193>sa
Sud<193>sa†the son of Divod<193>sa and a descendent of Pijavana†was ç
a king of the Bh<193>rata race. In the D<193>·ar<193>j<210>a episode ç
of the <184>gveda (7.33.3, 5; 7.83.8) he is said to have defeated ç
the combined armies of the ten kings of races like the Pakthas, the ç
Bhal<193>nas, the Va<218><193>nins and others. His chief priest was ç
Vasi<218><219>ha whereas the latter kings were guided by Vi·v<193>mitra.
The A·vins gave him Sudev<200> as his queen. Indra is said to have ç
helped him in all his invasions.
He was a great king known for his generous gifts.
