Over the years, the Sv<193>min<193>r<193>ya<207>a sect has grown into ç
a mighty organisation with several branch centres in India and abroad. ç
These centres are undertaking many public service activities including ç
the running of educational institutions and hospitals as also rural ç
welfare schemes.
@NT = svapna
@N1 = (`dreams')
See <MS>AVASTH°TRAYA<D> and <MS>DREAMS.<D>
@NT = Svapne·vara
The <185><193><207><195>ilya Bhaktis<220>tras†also known as the ç
<185><193><207><195>ilya-·ata-s<220>tr<200>yam† has two well-known ç
commentaries: the Bh<193><218>ya of Svapne·vara and the Bhakticandrik<193> ç
of N<193>r<193>ya<207>at<200>rtha.
Svapne·vara must have existed sometime during the period 14th to the ç
17th century <MS>A.<|>D.<D>, much nearer to the 14th.
He belonged to Gau<195>ade·a or Bengal. He was the son of Jale·vara ç
and grandson of Vi·<193>rada. Jale·vara was the commander-in-chief ç
of the king of Bengal.
Nothing more is known about him except that he wrote two more treatises ç
†the Ny<193>yatattvanika<218>a and the Ved<193>ntatattvanika<218>a. ç
Unfortunately neither work is available now.
@NID = <+><+><+><+>His commentary on <185><193><207><195>ilya's Bhakti- ç
s<220>tras is simple, natural and direct.
@NT = svara
@N1 = (`that which makes sound')
This word has several meanings. InSanskrit grammar, it represents ç
the thirteen vowels.
In Vedic chanting it stands for the three notes†ud<193>tta, anud<193>tta ç
and svarita. (See <MS>ANUD°TTA<D> for details.)
In music, it denotes the seven basic notes like <218>adja, <216><218>abha ç
and so on.
@NT = svarga
@N1 = (`heaven')
See <MS>SVARLOKA.<D>
@NT = Svarg<193>roha<207>aparva
This is the last book of the great epic Mah<193>bh<193>rata.
See <MS>MAH°BH°RATA.<D>
@NT = svarita
@N1 = (`falling')
See <MS>ANUD°TTA<D> for details.<MS>
@NT = Svarloka
Also known as Svarga, it is situated between the sun and the Dhruva-nak<218>atra ç
(the pole-star). It is ruled by Indra (the king of gods) with his ç
capital at Amar<193>vati. Gods and extremely meritorious human beings ç
live here. It is the Hindu concept of heaven.
@NT = Svarodayavij<210><193>na
@N1-1 = (`science of prediction<R>ç
depending on the breather's health')
The air we breathe in, the pr<193><207>a (vital air or energy) in ç
the body, and themind are interconnected. Hence by controlling the ç
act of breathing which istechnically called svara, it is possible ç
to control health, achieve longevity and predict certain things.
Normally, breathing takes place through one nostril at a time and ç
it changes over to the other after an hour. When it is in the left, ç
it is connected with the i<195><193>-n<193><195><200> and when in ç
the right, with the pi<209>gal<193>-n<193><195>i. When it is flowing ç
smoothly through both, it is connected with the su<218>umn<193>-n<193><195>i.
This science teaches the methods of changing the svara (or respiration) ç
from one to the other.
Perfection in this science can endow the person with several supernatural ç
powers.
@NT = svar<220>palak<218>a<207>a
@N1 = (`essential<R>ç
characteristic')
According to the Advaita Ved<193>nta theintegral or essential characteristic ç
(svar<220>palak<218>a<207>a) of Brahman is `sat-cit-<193>nanda' (existence-consciousness-bliss) ç
whereas the ta<219>asthalak<218>a<207>a (accidental characteristics) ç
is responsible for creation, preservation and dissolution of this ç
world. An example can make these ideas more clear.
While indicating the house of Devadatta, one can point out the direction ç
of its location through the extended branch of a mango tree nearby. ç
The house itself may then be described as built of bricks with a tiled ç
roofing and green in colour. The former (the mango tree and its branch) ç
stands for the ta<219>asthalak<218>a<207>a and the latter for the ç
svar<220>palak<218>a<207>a.
It should be noted that the ta<219>asthalak<218>a<207>a has nothing ç
to do with the object described though it certainly helps in locating ç
or recognizing it.
@NT = svar<220>pa·akti
This is one of the three ·aktis or powers of <185>r<200> K<216><218><207>a ç
who is Brahman Himself.
See <MS>ACINTYABHED°BHEDA SCHOOL.
@NT = ·v<193>sa
@N1 = (`inhalation')
See <MS>PRA<185>V°SA<D>.
@NT = svastika
The svastika is a symbol of auspiciousness (svasti<|>=<|>auspiciousness). ç
It has been used as a symbol of the sun or of Vi<218><207>u or even ç
of Ga<207>e·a. It also represents the world-wheel, the eternally changing ç
world, round a fixed, unchanging centre or God.
Svastika marks depicted on doors or walls of building or on animals, ç
are believed to protect them from the wrath of evil spirits or furies ç
of nature.
@SPACE = 
@NT = Svastis<220>kta
@N1 = (`hymn of auspiciousness')
@SPACE = 
The five mantras of the <184>gveda (5.51.11-15) together are known ç
as the Svastis<220>kta since each verse begins with the word `svasti' ç
(= auspiciousness).
It is generally chanted at the time of consecrating the image of Vi<218><207>u ç
by tying a strip of cloth (sanctified by this hymn) to its hand.
The deities who are praised and whose blessings are solicited here ç
are: The A·vins; Aditi (the mother of gods); P<220><218>an; Heaven ç
and Earth; V<193>yu (god of wind); Soma; B<216>haspati (teacher of ç
gods); °dityas; Vi·vedevas; Agni (fire-god); <184>bhus (a class of ç
gods who were originally human beings); Rudra; Mitr<193>-Varu<207>a; ç
and Indra.
The three verses (13 to 15) are repeated to cure the sacrificer if ç
he becomes ill.
The last mantra (the 15th) can be repeated to overcome the obstacles ç
and dangers while on tour.
@SPACE = 
@NT = svastiv<193>cana
@SPACE = 
Before  beginning  any  auspicious religious rite, some br<193>hma<207>as, ç
elders andsuma<209>galis (married women whose husbands are alive) ç
are invited, honoured andthen requested to say `May it be auspicious!'
This is called svastiv<193>cana or svastyayana.
This is a custom prevalent even now.
@SPACE1 = 
@NT = svayam<193>c<193>ryas
@N1KERN = (`self-appointed teachers')
Ram<193>nuja (<MS>A.<|>D.<D> 1017-1137) did not appoint any single ç
person as the next pontiff to succeed him. Instead, he selected 74 ç
pious householder disciples and gave them the power to spread the ç
philosophy of Vi·i<218><219><193>dvaita and the religion of <185>r<200>vai<218><207>avism. ç
These 74 came to be known as `svayam<193>c<193>ryas'. They were not ç
only great scholars but also great devotees committed to the <185>r<200>vai<218><207>avism ç
sect.
They could grant pa<210>casa<221>sk<193>ras (See <MS>PA<178>CASA<189>SK°RAS.)<D> ç
and mantropade·a (giving the famous mantras like the a<218><219><193>k<218>ar<200>) ç
to disciples.
They were also expected to expound the scriptures according to R<193>m<193>nuja's ç
philosophy.
@SPACE1 = 
@NT = sv<193>yambhuvali<209>ga
@N1 = (`self-manifested<R>ç
li<209>ga [of <185>iva]')
<185>ivali<209>gas†emblems of god <185>iva† are of several types. ç
According to one classification, by the Suprabhed<193>gama (pa<219>ala ç
33), three types of li<209>gas are uttamottama or the very best. They ç
are divya (divine, worshipped by gods like Brahm<193> and Vi<218><207>u), ç
p<220>rva (extremely ancient) and sv<193>yambhuva (self manifested).
Sv<193>yambhuvali<209>gas are not carved or made by human beings or ç
sages or demons, but have manifested by themselves.
See also <MS>LI<177>GA.<D>
@NT = Svayamprabh<193>
@N1 = (`[one who] is<R>ç
self-shining')
@EMERGENCY = Svayamprabh<193> was the daughter of the sage <185><193><207><195>ilya†hence ç
known as <185><193><207><195>ili also†and was a friend of Hem<193>, ç
an apsaras (celestial nymph). They lived in a beautiful cave created ç
by Maya, a divine architect. When Hem<193> left for heaven Svayamprabh<193> ç
was taking care of the cave.
@EMERGENCY = While searching for S<200>t<193>, Hanum<193>n and other ç
monkeys entered this cave and were entertained by her.
Once Garu<195>a offended her and lost his wings by her curse. Later ç
he apologised and got them back.
@NT = svaya<221>vara
@N1 = (`choosing the husband [by a girl] by her own choice')
@EMERGENCY = In the olden days, if a girl who had attained puberty ç
was not married off to a suitable young man by her father or guardian, ç
she would wait for three years and then choose her husband herself. ç
This was a well-known variety of svaya<221>vara common to all castes. ç
S<193>vitr<200> choosing Satyav<193>n is quoted as an example for ç
this kind.
@EMERGENCY = But the svaya<221>varas described in the two great epics ç
are often more elaborate and spectacular affairs. They were confined ç
to the royal families only. In some cases, the svaya<221>varas did ç
not depend upon the will of the bride at all, but upon some heroic ç
deed set by her father, as in the case of S<200>t<193> and Draupad<200>.
@EMERGENCY = The svaya<221>varas of Damayant<200> and Indumati may ç
also be quoted as examples.
@EMERGENCY = The writers of dharma·<193>stras include this under the ç
category of g<193>ndharva viv<193>ha.
@NT = <185>vetadv<200>pa
@N1 = (`the white island')
The <185>vetadv<200>pa is a mythical island mentioned in the Mah<193>bh<193>rata ç
(<185><193>ntiparva Ch. 335). It is said to have been formed by ç
the solidification of the foam of the K<218><200>rasamudra (ocean ç
of milk) and lies in its midst. It is situated 32000 yojanas (one ç
yojana = 15 kms. or 9 miles) above the Meru mountain (See <MS>MERU<D> ç
for details.).
It is inhabited by great devotees of Vi<218><207>u. They are absolutely ç
white in complexion, of an extraordinarily strong constitution and ç
extremely handsome. They are always worshipping and meditating upon ç
Vi<218><207>u.
Once R<193>va<207>a is said to have gone there. But, the women of ç
the place manhandled him and drove him out!
@NT = <185>vetaketu
<185>vetaketu is one of the great sages we come across in the Upani<218>ads ç
and the Mah<193>bh<193>rata.
He was the son of Gautama °ru<207>i (also known as Udd<193>laka). ç
In his younger days he was proud and arrogant, but had to taste defeat ç
in the court of the king Prav<193>ha<207>a Jaivali (Ch<193>ndogya ç
Upani<218>ad 5.3.1-5). Later on, his father taught him the science ç
of Brahman (ibid 6).
In course of time he himself became a great teacher. Upakosala was ç
a talented disciple of his (vide Ch<193>ndogya Upani<218>ad 4.10).
Naciketa was his brother and Suj<193>t<193> the wife of the sage Kaho<202>a ç
was his sister. He had married Suvarcal<193>, the daughter of the ç
sage Devala.
<185>vetaketu  is  considered  to  have assigned proper duties to ç
the priests performing sacrifices.
Annoyed  at  the  loose  sexual behaviour of the people of his times, ç
he is said to have systematised the institution of marriage.
He also produced an abridged edition of the K<193>ma·<193>stra (Science ç
of Erotics) originally written by Nandi, <185>iva's famous mount.
Another famous sage, A<218><219><193>vakra, was his nephew.
@NT = <185>vet<193>·vatara Upani<218>ad
The <185>vet<193>·vatara Upani<218>ad, though not included within ç
the group of the ten Cardinal Upani<218>ads, is deemed so important ç
that it is always placed in the eleventh position. It must be considered ç
as ancient as the Mu<207><195>aka and the Ka<219>ha Upani<218>ads.
It belongs to the K<216><218><207>a Yajurveda. It has 113 mantras ç
included in six chapters.
<185>vet<193>·vatara is the sage who propagated or transmitted this ç
Upani<218>ad. Three of its mantras (6.9; 4.5 and 5.8) have been discussed ç
in the Brahmas<220>tras (1.4.11; 1.4.8; 2.3.22).
It has some special features. It has addressed Param<193>tman (Supreme ç
Self) as Hara (1.10), Rudra (3.2; 3.4; 4.12; 4.21 and 22) and <185>iva ç
(3.14; 4.10). However scholars consider them as general names of God ç
and hence do not concede that it is a <185>aiva Upani<218>ad.
The second speciality is its advocacy of bhakti or devotion to God ç
as an important aspect of s<193>dhana.
The third is giving a definite form to God and consider him as a Person.
Use of the words S<193><209>khya, Yoga and Kapila is the next. However, ç
these do not propagate the S<193><209>khya philosophy as described ç
in later philosophical literature.
The general ideas found in the other Upani<218>ads are reflected here ç
also.
This Upani<218>ad has five commentaries †written by <185>a<209>kara ç
(<MS>A.<|>D.<D> 788-820), Vij<210><193>n<193>tman (13th century), <185>a<209>kar<193>-nanda ç
(14th century), N<193>r<193>ya<207>at<200>rtha (18th century) and ç
Upani<218>ad Brahmayogin (18th century).
See also <MS>UPANI<186>ADS.
@SPACE = 
@NT = Syamantakama<207>i
@SPACE = 
Satr<193>jita was a Y<193>dava chieftain. Through  severe  austerities  he  had ç
appeased S<220>rya (the Sun-god). Pleased with him, S<220>rya had ç
given him a special gem called Syamantakama<207>i which would yield ç
160 tolas (equivalent to 34 kgs.) of gold every day.
Satr<193>jit had strung it into a necklace which could be worn whenever ç
one liked.
Once K<216><218>na is said to have requested Satr<193>jit to give ç
it to him but Satr<193>jit refused.
One day, Prasena, brother of Satr<193>jit, wearing this necklace, ç
went out hunting. A lion killed him and was taking the necklace away ç
when J<193>mbav<193>n (the king of bears, of the R<193>m<193>ya<207>a ç
fame) encountered it, killed it and took the necklace to be given ç
to J<193>mbavat<200> his daughter. She tied it to the cradle of the ç
baby in her house.
When Satr<193>jit heard that Prasena had been killed and that the ç
necklace had been missing he suspected K<216><218><207>a of stealing ç
it. K<216><218><207>a quickly searched for it, recovered it from J<193>mbav<193>n ç
and restored it to Satr<193>jit.
@NT = <185>y<193>m<193>·<193>stri
@N1 = (<MS>A.<|>D.<D> 1763-1827)
Hindu music has been predominantly spiritual in content and orientation. ç
It has attained the status of a yoga (`n<193>dayoga').
During the period <MS>A.<|>D.<D> 1750-1850 three great musician-saints, ç
who were also inspired composers, appeared in South India and enriched ç
classical South Indian music, also known as Carnatic music. <185>y<193>m<193>·<193>stri ç
was the seniormost of them, the other two being Ty<193>gar<193>ja ç
(<MS>A.<|>D.<D> 1767-1847) and Muddusv<193>mi D<200>k<218>itar (<MS>A.<|>D.<D> ç
1775-1835).
His parents were br<193>hma<207>as. They were originally from the ç
Telugu country (now Andhra Pradesh). They were worshippers of goddess ç
K<193>m<193>k<218><200> of K<193><210>c<200>- puram (now in Tamil ç
Nadu). From North India, they migrated to Tiruv<193>r<220>r (in Tamil ç
Nadu) due to the unsettled conditions created by frequent Muslim invasions. ç
They had no issues.
By the grace of Lord Ve<209>ka<219>esvara of Tirupati to whom they ç
were constantly praying, a son was born during <MS>A.<|>D.<D> 1763. ç
An oracle had declared that this son would become very famous. He ç
was named <185>y<193>m<193>·<193>stri.
The boy was given very good education in Sanskrit and Telugu languages ç
as also fundamentals of music. He attained proficiency under a musician-monk ç
and °diyappan, the most famous singer of those days.
As a result of devoted worship of thegoddess K<193>m<193>k<218><200>, ç
he became highlyinspired and started spontaneously composing songs ç
of various types. He became an unparalleled expert in that field. ç
Many an arrogant musician or detractor of his times was humbled by ç
him in no time.
His compositions end with the a<209>kita (assumed name) `<185>y<193>mak<216><218><207>a'.
He has 300 compositions to his credit. They are, generally speaking, ç
difficult to master.
He had two sons. His second son Subbar<193>ya·<193>stri was an equally ç
great musician.
@END = 
