@NID = Fridays. However, there are no restrictions regarding taking ç
bath in the sea at Setu or R<193>me·varam.
The pur<193><207>as enumerate the oceans as seven. They are: lava<207>asamudra ç
(ocean of salt water); ik<218>usamudra (ocean of sugarcane juice); ç
sur<193>samudra (ocean of wine); sarpis-samudra (ocean of ghee); dadhisamudra ç
(ocean of curds); k<218><200>ra- samudra (ocean of milk); and, jalasamudra ç
(ocean of water) (vide V<193>yupur<193><207>a 49.123; Vi<218><207>upur<193><207>a ç
2.2.6).
The sage Agastya is said to have drunk the ocean at the request of ç
Indra, so that the demons, K<193>lakeyas, who used to hide under its ç
water, could be destroyed (Mah<193>bh<193>rata, Ara<207>yaparva ç
99).
At one period of time, samudray<193>na or sea-voyage was prohibited ç
for the br<193>hma<207>as, dubbing it as one of the items of kalivarjyas ç
(things to be given up during the kali-age or iron-age). It is difficult ç
to understand this prohibition except by the historical fact that ç
many learned br<193>hma<207>as were emigrating to foreign countries ç
either on invitation or to spread their knowledge, thus making Bh<193>rata ç
that much poorer!
The Vi<218><207>udharmas<220>tras (3.160.1-7) mentions a Samudravrata, ç
a rite aimed at appeasing the presiding deities of the seven samudras, ç
to be performed for seven days from C<193>ndram<193>na Yug<193>di. ç
The performer is said to attain health, wealth and heaven.
See also <MS>SAMUDRAMATHANA.
@SPACE = 
@NT = sagarbha
@N1 = (`with the womb [of the<R>ç
mantra]')
@SPACE = 
See <MS>NIRGARBHA.<D>
@NT = sagotra
@N1 = (`of the same gotra or lineage')
The words gotra and pravara have been used extensively in the sm<216>tis ç
and dharma·<193>stras.
Sagotra means a person belonging tothe same gotra. Marriages between ç
persons of the same gotra have been prohibited.
See <MS>GOTRA<D> for details.
@NT = Sagu<207>a-Brahman
@N1 = (`Brahman with<R>ç
qualities')
See <MS>ADVAITA VED°NTA DAR<185>ANA.<D>
@NT = Sahadeva
Sahadeva was the last of the five P<193><207><195>avas. Nakula and ç
Sahadeva were twins born to M<193>dr<200> (the second wife of the ç
king P<193><207><195>u) by the grace of the A·vin<200>devat<193>s.
He was†like Nakula†very handsome in appearance. An expert in taming ç
horses and elephants, he was very good in taking care of cows.
Before the R<193>jas<220>ya sacrifice, he toured the southern countries ç
to conquer their kings and collect ransoms for the sacrifice. He is ç
said to have collected the ransom even from Vibh<200><218>a<207>a ç
(of the R<193>m<193>ya<207>a fame) through Gha<219>otkaca (son of ç
Bh<200>ma in his wife Hi<195>imb<193>).
During the sacrifice he had the privilege  of  performing  the  agrap<220>j<193> ç
(worship of the greatest person present) to <185>r<200>K<216><218><207>a ç
as per the advice of the grandsire Bh<200><218>ma.
When  the  P<193><207><195>avas  were  living incognito at the palace ç
of the king Vir<193><219>a, he had assumed the name Tantr<200>p<193>la ç
and was in charge of the king's dairy.
In the Kuruk<218>etra battle, he killed the villain <185>akuni.
He was endowed with trik<193>laj<210><193>na or the special power ç
of knowing the past, present and future.
He had two sons: <185>rutasena from Draupad<200>; Suhotra from Vijay<193> ç
(daughter of <185>alya). His third wife was Bh<193>numati (daughter ç
of king Bh<193>nu).
During the mah<193>prasth<193>na (final journey towards heaven) he ç
died after Draupad<200>, the reason for early death being his pride ç
about his intellectual powers.
The Mah<193>bh<193>rata mentions three more Sahadevas. The first ç
was a great sage attached to the royal court of Indra, the king of ç
gods. The second was a king in ancient India. The third was the son ç
of Jar<193>sandha (the emperor of Magadha) who succeeded him after ç
his death at the hands of Bh<200>ma.
The Bh<193>gavata also alludes to three Sahadevas, one being a demon ç
and the other two, kings of solar dynasty.
See also <MS>NAKULA<D> and <MS>P°Ø£AVAS.
@SPACE = 
@NT = Sahajiy<193>s
@SPACE = 
The Sahajiy<193> is a cult that had itsorigin in the Sahajay<193>na ç
school of Buddhism. It is closely associated with the Caitanya sect ç
of Vai<218><207>avism.
Sahaja literally means that which is born along with birth. It stands ç
for the original basic nature or quality of a thing at its birth or ç
origination and persists throughout,  unchanged.  It  may  be considered ç
an equivalent of Brahman of Advaita Ved<193>nta or the <185><220>nya ç
of Nihilistic Buddhism.
The love of R<193>dh<193> towards K<216><218><207>a is the mode of ç
s<193>dhana (spiritual discipline) recommended.
The Sahajiy<193>s reject all kinds of vidhis or rules and regulations, ç
normally followed by the society.
They are against vegetarianism and austerities as recommended by the ç
gosv<193>mis of Vai<218><207>avism.
Another important feature of this system is the highest place and ç
honour given to the guru.
It is interesting to note that some techniques of calming the mind ç
have been adopted by them from the Yogas<220>tras of Pata<210>jali ç
(200 <MS>B.<|>C.<D>).
@NT = sahasrali<209>ga
@N1 = (`thousand li<209>gas')
<185>ivali<209>gas or emblems of <185>iva are sculptured in several ç
ways. One such is the sahasrali<209>ga.
On the Rudrabh<193>ga or the p<220>j<193>bh<193>ga are carved 1000 ç
emblems by the incision of parallel horizontal and vertical lines, ç
and by chamfering the edges of the resultant criss-cross sections.
See also <MS><185>IVALI<177>GA.<D>
@NT = sahasran<193>mastotras
@N1 = (`hymns containing one thousand names')
The chanting of the n<193>ma or the divine name has an important place ç
in the disciplines prescribed by the Bhakti schools of Ved<193>nta ç
like those of R<193>m<193>nuja (<MS>A.<|>D.<D> 1017- 1137), Madhva ç
(<MS>A.<|>D.<D> 1238-1317) and Caitanya (<MS>A.<|>D.<D> 1485-1533). ç
In fact, this tradition goes so far as to declare that the n<193>ma ç
(the name) and the n<193>min (the one who is named, i.e., God) are ç
identical.
This adoration of God by the divine name assumes two forms: japa and ç
stotra. In japa, the name of God (or even a long formula) has to be ç
silently repeated. The stotra, however, is invariably uttered aloud. ç
It may consist in chanting verses conveying the glory and attributes ç
of God. The sahasran<193>mastotras belong to this group and are extremely ç
popular.
The word sahasran<193>ma literally means `thousand names of God'. ç
According to the Vedic tradition, there is only one manifesting sound ç
(·abda) indicative of the Supreme Being (Parabrahman). And, this is ç
called Pra<207>ava or Om. (See <MS>PRAØAVA<D> for details.) Just as ç
that one Parabrahman is adored as manifesting in the form of many ç
deities, the one name Om, indicative of Him, also takes the shape ç
of innumerable sound forms representing divine attributes  and  other  excellences.  A ç
sahasran<193>ma is, perhaps, the most extensive elaboration of the ç
divine name. And, its recitation, along with p<220>j<193> or ritualistic ç
worship, is said to be an easier method to  control  the  mind  than  japa  and ç
meditation.
Though a sahasran<193>mastotra comprises only the names of the deity, ç
these names have been so ingeniously composed as to reflect many aspects ç
of the divine.
@SPACE1 = 
Generally, a sahasran<193>mastotra has to be chanted ceremoniously, ç
preceded by certain preliminaries. They are: reciting the name of ç
the <216><218>i or the sage to whom it was first revealed, the chandas ç
or the metre in which it is composed, the devat<193> or the deity ç
adored through this stotra, and, the viniyoga or the purpose for which ç
it is chanted.
This should be followed by karany<193>sa and a<209>gany<193>sa (ceremonial ç
purification of the hands and the upper limbs). Then the dhy<193>na·loka, ç
describing the form of the deity is to be chanted.
Now comes the actual recitation of the whole hymn.
At the end, it is the normal practice to recite the phala·ruti or ç
eulogy of the hymn also.
If one likes, these thousand names can be used in ritualistic worship ç
also offering flowers or tulas<200> leaves (holy basil) or bilva leaves ç
(Aegle marmelos) or even ku<209>kum (vermillion powder) with each ç
name.
Hindu tradition often considers that some of the names of the sahasran<193>mastotras ç
are potent with special powers and that their repetition can result ç
in the fulfilment of one's desires.
A very large number of sahasra-n<193>mastotras are now available in ç
print. They occur mostly in the pur<193><207>as and are addressed ç
to several deities of the Hindu pantheon.
The following is a list of the sahasra-n<193>mas thus available, arranged ç
in the English alphabetical order:
@SPACE1 = 
@L2 = °<210>janeya	<+><+>Sahasran<193>mastotra
@L2 = B<193>l<193>	<+><+>Sahasran<193>mastotra
@L2 = Bhav<193>n<200>	<+><+>Sahasran<193>mastotra
@L2 = Dak<193>r<193>di-·r<200>durg<193>	<+><+>Sahasran<193>mastotra
@L2 = Durg<193>	<+><+>Sahasran<193>mastotra
@L2 = Ga<207>apati	<+><+>Sahasran<193>mastotra
@L2 = G<193>yatr<200>	<+><+>Sahasran<193>mastotra
@L2 = Hayagr<200>va	<+><+>Sahasran<193>mastotra
@L2 = Kak<193>r<193>di-k<216><218><207>a	<+><+>Sahasran<193>mastotra
@L2 = K<193>l<200>	<+><+>Sahasran<193>mastotra
@L2 = K<193>lik<193>	<+><+>Sahasran<193>mastotra
@L2 = Lak<218>m<200>	<+><+>Sahasran<193>mastotra
@L2 =                   <|><+><+>(3 different hymns)
@L2 = Lak<218>m<200>n<216>si<221>ha	<+><+>Sahasran<193>mastotra
@L2 = Lalit<193>rahasya	<+><+>Sahasran<193>mastotra
@L2 = Lalit<193>	<+><+>Sahasran<193>mastotra
@L2 = Mak<193>r<193>di-·r<200>r<193>ma	<+><+>Sahasran<193>mastotra
@L2 = M<200>n<193>k<218><200>	<+><+>Sahasran<193>mastotra
@L2 = P<193>rvat<200>	<+><+>Sahasran<193>mastotra
@L2 = R<193>dhik<193>	<+><+>Sahasran<193>mastotra
@L2 = Rak<193>r<193>di-·r<200>r<193>ma	<+><+>Sahasran<193>mastotra
@L2 = R<193>ma	<+><+>Sahasran<193>mastotra
@L2 = Sant<193>nagop<193>la	<+><+>Sahasran<193>mastotra
@L2 = Sarasvat<200>	<+><+>Sahasran<193>mastotra
@L2 = S<200>t<193>	<+><+>Sahasran<193>mastotra
@L2 = <185>iva	<+><+>Sahasran<193>mastotra
@L2 = <185>o<195>a·<200>-r<193>jar<193>je·var<200>	<+><+>Sahasran<193>mastotra
@L2 = S<220>rya	<+><+>Sahasran<193>mastotra
@L2 = S<220>ryop<193>sana	<+><+>Sahasran<193>mastotra
@L2 = <185>y<193>mal<193>	<+><+>Sahasran<193>mastotra
@L2 = Ve<209>ka<219>e·a	<+><+>Sahasran<193>mastotra
@L2 = Vi<218><207>u	<+><+>Sahasran<193>mastotra
@SPACE = 
Though thus thirty-three sahasra-n<193>mastotras have been printed ç
so far, only three†of Vi<218><207>u, <185>iva and Lalit<193> are extremely ç
popular and constantly in use.
See also <MS>STOTRA<D>.
@NT = sahasr<193>ra
@N1 = (`thousand-petalled [cakra or psychic centre]')
See <MS>CAKRAS.<D>
@NT = S<193>i B<193>b<193> of Shirdi
@N1 = (d. <MS>A.<|>D.<D> 1918)
India seems to have a knack of producing great men in great numbers, ç
though the greater number of people who worship them rarely make efforts ç
to shape their own lives in their mould.
S<193>i B<193>b<193> of Shirdi is one such who lived long enough†four ç
score years and more†to spread the true spirit of religion as spiritual ç
evolution.
Though his early life is shrouded in mystery there is reason to believe†based ç
on his own admissions†that he was born to br<193>hma<207>a parents. ç
But fate made him to be brought up by a Muslim fakir and his wife. ç
Before his demise the fakir asked his wife to hand over the boy†now ç
about eight years old†to a br<193>hma<207>a devotee of Ve<209>ka<219>e·vara ç
of Tirupati known as Gopal Rao (but called Ve<209>k<220>s<193> by ç
S<193>i B<193>b<193> later). This person was not only a great devotee ç
of God but also had mysterious yogic powers. The boy served him with ç
extraordinary devotion and dedication. Later on, this guru bequeathed ç
all his spiritual powers to the boy†now a young man†and passed away.
However, there are other versions of B<193>b<193>'s early life also.
S<193>i B<193>b<193> arrived at Shirdi, a small village on the bank ç
of God<193>var<200> river, 18kms. (11 miles) from the Kopergaon railway ç
station in the Ahmednagar district of Maharashtra, probably during ç
<MS>A.<|>D.<D> 1854. After about four years of wandering he returned ç
to Shirdi and never moved out. At Shirdi he stayed in a dilapidated ç
mosque (which he used to call Dv<193>rak<193> M<193>y<200>) till the ç
end and passed away there itself in <MS>A.<|>D.<D> 1918.
He had many miraculous and extraordinary yogic powers which he usedabundantly ç
to help the devotees, especially those in distress, out of infinite ç
compassion. He stressed the importance of guru's grace in the path ç
of spiritual evolution. In his own way he strove to bring about unity ç
between the Hindus and Muslimssince both were among his disciples ç
and followers.
@SPACE1 = 
Today, Shirdi has become an important place of pilgrimage with the ç
temple built over his sam<193>dhi (place of interment) as the centre ç
of attraction.
@NT = <185>aiv<193>gamas
°gamas are post-Vedic Hindu scriptures relevant even today. They primarily ç
deal with practical spiritual disciplines, ethical codes and temple ç
rituals.
Of the three main divisions of the <193>gamas (See <MS>°GAMAS.<D>), ç
the <185>aiv<193>gamas are listed as the first. They are also called ç
by other names such as Sa<221>hit<193> and Mah<193>tantra. They had ç
already come into existence by the first century <MS>B.<|>C.<D>
Their philosophical tenets are the same as those of the P<193>·upata ç
cult (See<MS><185>AIVISM.<D>).
The <185>aiv<193>gamas are divided into two groups: pradh<193>n<193>gamas ç
and up<193>gamas.
The former comprises 28 works and the latter either 208 or 225.
The twenty-eight major <193>gamas are:
Acinty<193>gama, Ajit<193>gama,
A<221>·um<193>n<193>gama, Anal<193>gama,
Bimb<193>gama, Candraj<210><193>n<193>gama,
D<200>pt<193>gama, K<193>mik<193>gama,
K<193>ra<207><193>gama, Kira<207><193>gama,
Lalit<193>gama, Maku<219><193>gama,
Ni··v<193>s<193>gama, P<193>rame·var<193>gama,
Prodg<200>t<193>gama, Raurav<193>gama,
S<193>hasr<193>gama, Sant<193>n<193>gama,
<185>arv<193>gama, Siddh<193>gama,
S<220>k<218>m<193>gama, Suprabhed<193>gama,
Sv<193>yambhuv<193>gama, V<193>tul<193>gama,
Vijay<193>gama, Vimal<193>gama,
V<200>r<193>gama, Yogaj<193>gama.
@SPACE1 = 
These major <193>gamas have evolved out of the five faces of <185>iva ç
(= Pa<210>c<193>nana) as follows:
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(.9167,.1250,E1), ç
ABOVE(.0417), BELOW(.0417), VGUTTER(.0432), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
1. Sadyoj<193>ta, :, K<193>mika,, Yogaja,, Acintya,, K<193>ra<207>a,, ç
Ajita.
2. V<193>madeva, :, D<200>pta,, S<220>k<218>ma,, S<193>hasra,, A<221>·um<193>n, ç
Suprabheda.
3. Aghora, :, Vijaya,, Ni··v<193>sa,, <R>ç
Sv<193>yambhuva,<R>ç
Anala,, V<200>ra.
4. Tatpuru<218>a, :, Raurava,, Maku<219>a,, Vimala,<R>ç
Candraj<210><193>na,, Bimba.
5. ®·<193>na, :, Prodg<200>ta,, Lalita,, Siddha,, <R>ç
Sant<193>na,, <185>arva,<R>ç
P<193>rame·vara,<R>ç
Kira<207>a,, V<193>tula.
@Z_TBL_END = 
Sometimes, the first ten <193>gamas listed under the first two aspects ç
of <185>iva are named as <185>ivasa<221>hit<193>s and the rest as ç
Rudrasa<221>hit<193>s.
All these <193>gam<193>s follow the standard pattern of the fourfold ç
division, viz., J<210>anap<193>da, Yogap<193>da, Kriy<193>p<193>da ç
and Cary<193>p<193>da. (See <MS>°GAMAS<D> for details.)
Anyone who wishes to practise the disciplines of the <185>aiv<193>gamas ç
has to undergo d<200>k<218><193> or initiation. The process is explained ç
in detail. One interesting point is that it varies according to the ç
gotra (lineage) and Vedic ·<193>kh<193> (branch assigned for study) ç
of the seeker, thereby confirming that the <185>aiv<193>gamas are ç
very much a part of the Vedic tradition.
@NT = <185>aivasiddh<193>nta
See under <MS><185>AIVISM.<D>
@NT = <185>aivism
@SB = 1.	Introduction
<185>aivism is the religion and philosophy of those who believe that ç
god <185>iva is the Supreme Being.
Whether Rudra the Terrible, of the Vedas and <185>iva, the Auspicious ç
One, of the `non-Vedic' (`non-°ryan') `Dravi<195>ian' cults battled ç
for centuries and then blended to emerge as one deity of compromise†<185>iva-Mah<193>deva, ç
the Auspicious Great God†is a moot point. As the Indus Valley civilisation, ç
which had once been believed to be pre-°ryan, non-Vedic or Dravi<195>ian, ç
came to be accepted as a continuation of the Vedic civilisation itself, ç
in fact its later phase, scholars had to concede that <185>iva as ç
depicted on some of the seals with a trident and a bull, was very ç
much a Vedic deity even as the Mother Goddess was.
Being the god of destruction and dissolution of the world, as delineated ç
in later literature, <185>iva had to be Rudra, the Terrible. Hence ç
supplications to him to be propitious to one's children (vide <184>gveda ç
7.46.2), descendants, cattle and property (ibid., 1.114.8) are quite ç
in order. However, he also has a benign form (<185>ambhu, the beneficent ç
one), is the heavenly physician who cures one's diseases and protects ç
one's cattle.
By the time of the Atharvaveda and the <185>vet<193>·vatara Upani<218>ad ç
(1.10; 3.2; 4.12,21,22; 3.14; 4.10), the concept had further evolved ç
to indicate him as the supreme or the highest God.
@SPACE1 = 
Along with the development of the concept of Rudra-<185>iva, there ç
had also been an evolution of the concept and symbology of the li<209>ga ç
as the chief emblem of <185>iva. The li<209>ga resembles a pillar ç
with a semispherical top. Being a rounded surface in all directions, ç
it is, perhaps, the closest approximation to a god considered as beyond ç
all names, forms and attributes. Whereas some scholars find in it ç
the remnants of phallic worship of aboriginal tribes, others feel ç
it is a metamorphosed form of the Vedic y<220>pastambha (sacrificial ç
post) as the y<193>ga·<193>l<193> (sacrificial shed) gradually evolved ç
into the now common Hindu temple. Even if a phallic origin is admitted, ç
a third section of savants argue, there is nothing wrong in it since ç
it represents the generative principle of God, the creator.
Though <185>aivism might have started as a simple faith and a mode ç
of worshipping Lord <185>iva as the Supreme Being, over the centuries, ç
it branched off into several varieties of sects and cults. Six of ç
these have left their imprint on the religious history of India though ç
two or three only are surviving and thriving. These may now be considered ç
by arranging them in the English alphabetical order.
@SPACE = 
@SB = 2.	K<193>l<193>mukhas
@SPACE = 
Based on the fierce descriptions of Rudra in the Vedas, some bizarre ç
cults emerged in course of time. The K<193>l<193>- mukhas and the ç
K<193>p<193>likas are two such sects worshipping Rudra-<185>iva as ç
Bhairava and Ca<207><195><200>.
The K<193>l<193>mukhas were so called, probably because they were ç
defacing their faces with black marks and symbols (k<193>la= black, ç
mukha = face).
Scholars of <185>aivism consider this sect as a branch of the P<193>·upata ç
cult of Lakul<200>·a, also spelt as `Nakul<200>·a'.
@SPACE1 = 
These K<193>l<193>mukhas (sometimes called `ekko<219>i-munis') had ç
some connections with the descendants of a Devavrata Muni of Kashmir. ç
They were quite powerful during the period <MS>A.<|>D.<D> 700-1200 ç
in Andhra Pradesh  and  Karnataka.  Ked<193>re·vara temple of Ba<202><202>ig<193>ve ç
(in the Shimoga district of Karnataka) and the temple town of <185>r<200>·aila ç
(near Kurnool, Andhra Pradesh) were their strongholds. Edicts of the ç
C<193><202>ukyan kings (11th cent. <MS>A.<|>D.<D>) speak of royal patronage ç
to this cult. One of their gurus†Sarve·vara <185>aktideva†was the ç
master of 77 temples. They were also well- known for austerity and ç
scholarship.
However, some horrendous practices of theirs, like drinking wine in ç
human skulls, smearing the body with the ashes of crematories, cannibalism ç
and loose morals, made them outcastes in the society.
The teachers of this sect were divided into two groups: R<193>·i and ç
<185>akti.
R<193>jar<193>jaguru (circa <MS>A.<|>D.<D> 1370), a well-known K<193>l<193>mukha ç
teacher, was a contemporary of the sage Vidyara<207>ya (14th century ç
<MS>A.<|>D.<D>).
@SB = 3.	K<193>p<193>likas
Members of a powerful <185>aiva sect, the K<193>p<193>likas, were ç
christened as such because they were using a kap<193>la or human skull, ç
as their begging bowl. Theywere also wearing a garland of human skulls. ç
They were quite active and powerful during the period 7th century ç
onwards for about 500 years in <185>r<200>·aila (Andhra Pradesh) and ç
some parts of Tamil Nadu like K<193><210>c<200>puram, Tiruvo<219>riy<220>r, ç
Melp<193><195>i and Ko<195>umb<193><202><220>r. Worship of Bhairava ç
and Ca<207><195><200>, drinking wine, eating human flesh and ash, ç
arming themselves with a mace and promiscuous sex were common among ç
the members of the sect.
According to a work called <185>abara-tantra 24 teachers, starting ç
with °din<193>tha and ending with Malay<193>rjuna, have been mentioned. ç
They were fiercely anti-Vai<218><207>ava.
@SB = 4.	Kashmir <185>aivism
@S10 = Introduction
@SPACE1 = 
Though <185>aivism is an old religio-philosophical system prevalent ç
in many parts of India, certain erudite and enlightened teachers from ç
Kashmir developed a special brand of the same. This came to be popularly ç
knownas `Kashmir <185>aivism' in the annals of philosophical literature ç
of later periods. However, a more technical and acceptable title has ç
been `Pratya-bhij<210><193>dar·ana'.
@SPACE1 = 
@S10 = Basic Literature
Althoughthebasicliteratureof Kashmir <185>aivism is some of the ç
<193>gamas like the Svacchanda, the Netra and the Vij<210><193>nabhairava, ç
a new class of cardinal works was produced by the later writers. Among ç
them, the following are the principal ones: <185>ivas<220>tras (revealed ç
to Vasu-gupta) (9th century <MS>A.<|>D.<D>), Spandas<220>tra of Vasugupta, ç
Spandas<220>trav<216>tti of Kalla<219>a (chief disciple of Vasugupta), ç
<185>ivad<216><218><219>i of Som<193>nanda (9th century <MS>A.<|>D.<D>) ç
and ®·varapratyabhij<210><193> of Utpala (<MS>A.<|>D.<D> 900).
Abhinavagupta (<MS>A.<|>D.<D> 950-1000) was the most brilliant of the ç
later writers whose V<216>tti on the ®·varapratyabhij<210><193> ç
of Utpala, and his own independent works Tantr<193>loka and Param<193>rthas<193>ra ç
have made him immortal in the chronicles of Kashmir <185>aivism.
K<218>emar<193>ja (<MS>A.<|>D.<D> 975-1025), Bh<193>skara and Varadar<193>ja ç
were the other noted writers who have enriched this literature.
@SPACE1 = 
@S10 = Philosophical Tenets in Brief
This system puts forward 36 tattvas or fundamental principles out ç
of which the whole creation has evolved. They are divided into three ç
main groups:
<185>uddhatattva, <185>uddh<193>·uddhatattva and A·uddhatattva.
The <185>uddhatattvas (pure principles) are five: <185>ivatattva, ç
<185>aktitattva, Sad<193>·iva-tattva,  ®·varatattva  and  <185>uddhavidy<193>- ç
tattva.
The <185>uddh<193>·uddhatattvas are six: m<193>y<193>, k<193>la, niyati, ç
r<193>ga, vidy<193> and kal<193>.
The A·uddhatattvas are twenty-five. They  are:  puru<218>atattva,  prak<216>titattva, ç
buddhi, aha<209>k<193>ra, manas, the five j<210><193>nendriyas, the ç
five karmendriyas, the five tanm<193>tras and the five bh<220>tas.
These tenets appear to be similar to the ones described in the Advaita ç
Ved<193>nta and the S<193><209>khya systems. But there are some basic ç
differences.
These tattvas or principles may now be taken up one by one.
The  fundamental  tattva  of  this system is <185>ivatattva, generally ç
described as Parasa<221>vit or the highest (and pure) consciousness, ç
the same as the Nirgu<207>a Brahman of the Advaita Ved<193>nta. However, ç
as against the two aspects there†the Sagu<207>a and the Nirgu<207>a ç
aspects†there are five in this system.
@SPACE1 = 
This  Parasa<221>vit  is  the  original primeval tattva from which ç
all the other tattvas have emerged. It is eternal and ineffable.
The <185>aktitattva is primarily the prathama-spandana or first vibration-product ç
(if we can use such a word) of Parasa<221>vit. °nanda or bliss is ç
its chief characteristic. It is the primary source of all movement ç
in further creation and the rise of `aha<221>' or `I-consciousness'.
Then comes the Sad<193>·ivatattva, a further evolution of the Parasa<221>vit, ç
wherein there is an awareness of `aha<221>' (`I') and `ida<221>' (`this'), ç
the former being more prominent. Since `ida<221>' (creation) is still ç
in an extremely subtle state, Sad<193>·iva may also feel `aha<221> ç
ida<221>' identifying himself with the creation about to be projected.
In ®·varatattva, the fourth, the consciousness `ida<221>' (creation) ç
becomes equal in prominence to `aha<221>' (`I').
In <185>uddhavidy<193>tattva, the fifth form of Parasa<221>vit, `ida<221>' ç
(creation) becomes more prominent. This is the starting point of the ç
actual process of creation or evolution or projection.
These five principles have been named `<185>aktya<207><195>a'.
The next six principles are called `M<193>y<193><207><195>a'.
@SPACE1 = 
M<193>y<193>, the first, is the unique power of <185>iva, which can ç
make the impossible possible. It is not an illusory power responsible  only  for  ignorance  as  in ç
Advaita metaphysics. It is the real power by which <185>iva envelops ç
himself, producing bheda (differences), n<193>ma (names), r<220>pa ç
(forms) and so on, where they did not exist.
This m<193>y<193> gives rise to the `pa<210>ca-ka<210>cukas' or five ç
coverings that apparently limit the powers of <185>iva and make him ç
appear as the j<200>v<193>tman (individual soul), subject to k<193>la ç
(time), niyati (cause and effect relationship, law of karma), r<193>ga ç
(desire and attachment), vidy<193> (limited knowledge, or avidy<193>, ç
ignorance) and kal<193> (limited powers of action).
The next group of principles beginning with prak<216>ti is called ç
`Prak<216>tya<207><195>a'. Prak<216>ti is the matrix of the three ç
gu<207>as (sattva, rajas and tamas) in a state of balance. When this ç
balance is upset, theproducts that gradually emerge are: buddhi (discriminative ç
faculty), aha<209>k<193>ra (ego-sense, sense of individuation and ç
separation), manas (mind, general power of thinking, feeling and willing), ç
the five j<210><193>nendriyas (organs of perception, viz., eyes, ears, ç
nose, tongue and skin or the sense of touch), the five karmendriyas ç
(organs of action viz., speech, hands, feet and the two organs of ç
evacuation) and the five tanm<193>tras (the five subtle elementsof ç
earth, water, fire, air and ether or space).
The tanm<193>tras, by their combination, produce the five mah<193>bh<220>tas ç
or gross elements. Further creation proceeds from them. This group ç
is called `P<216>thivya<207><195>a'.
The significant points to be noted in this system are: 1) S<216><218><219>i ç
or creation is the evolution of the <185>akti or power of <185>iva. ç
2) The individual soul in bondage in creation is also, really speaking, ç
<185>iva himself. 3) The total number of fundamental cosmic principles ç
is 36 and not 25 as in the S<193><209>khya system.
Since the created world is an evolute of <185>iva, it is not different ç
from him. But, it also appears to have its own separate identity. ç
Hence, this system accepts the theory of bhed<193>bheda (both difference ç
and non-difference) between God (<185>iva) and his creation.
Similarly, the j<200>v<193>tman (the individual soul) who is called ç
`pa·u' (bound soul) is also <185>iva himself. By practising pratya-bhij<210><193> ç
(remembrance of his real nature as <185>iva himself) the j<200>va ç
can get rid of all <193>vara<207>as (coverings) and become one with ç
<185>iva. This is his mukti or liberation.
@SPACE1 = 
However, this can be secured only by serviceto the guru (spiritual ç
teacher), listening to the teachings of the ·<193>stras (holy books), ç
reflection on them and the practice of yoga. But, the final deliverance ç
can come only by ·iv<193>nugraha (grace of Lord <185>iva), technically ç
called `·aktip<193>ta' (descent of Lord's power).
Ultimately, as per this system, it is <185>iva who covers himself ç
and becomes the j<200>va, the bound soul. It is <185>iva, again, who  recognises  his  real  nature  and ç
`regains' it as it were.
Thus  self-forgetfulness  (sv<193>tma- vismara<207>a<%20>)<%0>and ç
self-remembrance (sv<193>tma- pratyabhij<210><193>) are two scenes ç
in the world-play of <185>iva!
@SPACE1 = 
@SB = 5.	P<193>·upata Cult
@S10 = Introduction
@EMERGENCY = The cult of Pa·upati or the P<193>·upata cult seems to ç
be an ancient one. The use of words `pati,' `p<193>·a,' and `pras<193>da' ç
in the <185>vet<193>·vatara Upani<218>ad (1.11; 6.9; 3.20), worship ç
of <185>iva as li<209>ga, the practice of tying the <185>ivali<209>ga ç
on the arm as per the stone edict of the king Pravarasena (<MS>A.<|>D.<D> ç
428), <185>ivali<209>gas discovered in Cambodia (now Kampuchia) and ç
assigned to the period <MS>A.<|>D.<D> 550†all these confirm this belief.
@SPACE1 = 
@EMERGENCY = The P<193>·upata cult is based mainly on the <185>aiv<193>gamas, ç
certain pur<193><207>as and a few minor Upani<218>ads of the post-Vedic ç
period. Some of the <193>gamas are: K<193>mika, Ajita, A<221>·um<193>n, ç
Suprabheda, Sv<193>yam-bhuva, Raurava, M<216>gendra, Pau<218>kara ç
and V<193>tula. The pur<193><207>as are: V<193>yu, K<220>rma and ç
<185>iva. As for their authoritative nature, they have been considered ç
equal to the Vedas, the Ved<193><209>gas, the Mah<193>bh<193>rata ç
and the dharma·<193>stras.
The period of the <193>gamas ranges from the first century to the ç
fourteenth. They are prevalent mostly in South India, that too in ç
Tamil Nadu. Whether they†some of them at least†were originally composed ç
in Tamil and later rendered into Sanskrit, or were directly written ç
in Sanskrit itself, opinion seems to be divided.
@S10 = Chief Tenets
The topics dealt with in the P<193>·upata literature are technically ç
called Pa<210>c<193>r-thas, the five basic subjects. They are: k<193>ra<207>a, ç
k<193>rya, yoga, vidhi and du<199>kh<193>nta.
@S10 = K°RAØA
K<193>ra<207>a, the primeval cause, is <185>iva, called `Pati' (Lord) ç
here. Some of his other names are: Rudra, <185>a<209>kara, K<193>la, ç
Bala-vikara<207>a, Aghora, Sarva, <185>arva, Tatpuru<218>a, ®·<193>na, ç
®·vara and Brahm<193>. He is an<193>di (without beginning or origin), ç
avyaya (indestructible) and the cause of creation, sustenance and ç
dissolution of the world. He is transcendent as well as immanent. ç
He is compassion unlimited. Pra<207>ava or O<221> is his best symbol.
Unlike the Ved<193>ntic systems, <185>iva or ®·vara is only the nimittak<193>ra<207>a ç
(efficient cause) of creation and not the up<193>d<193>na-k<193>ra<207>a ç
(material cause). Though the j<200>vas (individual souls) and the ç
world have a separate existence, they are completely under his control. ç
It is due to him that the world and the j<200>vas undergo changes. ç
However, being a pras<193>di (one who bestows grace), he is ever compassionate ç
to the j<200>vas. That is why they can get liberation by meditating ç
on him.
It may not be out of place to mention here that the P<193>·upata system ç
is very much akin to the Dvaita Ved<193>nta system of Madhva (<MS>A.<|>D.<D> ç
1197-1276). The only difference is that <185>iva has taken the place ç
of Vi<218><207>u, in this case.
@S10 = K°RYA
K<193>rya is the second of the five basics mentioned above. K<193>rya ç
is defined here not as an effect, but as that which is asvatantra ç
or dependent, k<193>ra<207>a being that which is svatantra or independent. ç
In this sense, ®·vara or <185>iva alone is the k<193>ra<207>a, the ç
jagat (world) and the j<200>vas being k<193>ryas since they are dependent ç
upon him.
Though ®·vara is the k<193>ra<207>a, the j<200>vas, being prodded ç
by him, can also be the k<193>ra<207>as in the further process of ç
creation. So also prak<216>ti or pradh<193>na which is responsible ç
for further evolution of the world. Hence these two have been called ç
`k<193>rya-k<193>ra<207>a'.
Evolution of the world from the prak<216>ti is the same as in the ç
S<193><209>khya philosophy.
One thing has to be noted here. ®·vara as the original k<193>ra<207>a ç
never gets affected by the evolution of the world whereas prak<216>ti ç
which is a `k<193>rya-k<193>ra<207>a' does. Two examples can make ç
this concept clear. Lotus blooms when the sunlight falls on it. Iron ç
filings move in the vicinity of a magnet. In these cases, neither ç
the sun nor the magnet is affected though the lotus and the iron filings ç
are. So also, ®·vara remains unaffected by the evolution of the world ç
through the prak<216>ti (and the j<200>vas).
Among the k<193>ryas, the j<200>v<193>tman (individual soul) is the ç
most important. He has been called `pa·u' since he is subject to `p<193>·a' ç
(bondage) and sees (`pa·yati') himself as the body-mind complex forgetting ç
that he is the spirit, whereas <185>iva has been declared as `Pa·upati' ç
(Lord of pa·us).
The pa·u or the j<200>va is eternal, all-pervading and possesses the ç
powers to see (d<216>k·akti) and to act (kriy<193>·akti).
Thepa·us,depending on their spiritual evolution, are classified ç
into two groups: s<193><210>jana (those attached to the body, the ç
senses and the mind) and nira<210>jana (the free souls).
The p<193>·as or bonds that bind the pa·u are called malas or impurities. ç
They are three: <193><207>avamala, m<193>y<200>yamala and k<193>rmamala.
The impurity that makes the pa·u (or j<200>va) get identified with ç
the limited body though he is really infinite, is <193><207>avamala. ç
The bondage that has been brought about by m<193>y<193> (the power ç
of ®·vara) is m<193>y<200>yamala. Limitations that arise due to past ç
karmas are k<193>rmamala.
With the help of yoga, the pa·u is able to cleanse himself of all ç
these malasand attain the du<199>kh<193>nta state (destruction or ç
cessation of all sorrow and suffering).
@S10 = YOGA
This takes us to the next subject, viz., yoga. Yoga is defined as ç
the sa<221>yoga (union) of <193>tman (pa·u) and ®·vara (Pa·upati). ç
It consists in detachment from the comforts and pleasures of the life ç
here and looking upon ®·vara alone as the sole aim of one's life. ç
This yoga can be achieved either through the grace of ®·vara or through ç
total surrender to him as the only refuge for a pa·u.
@EMERGENCY = Yamas like ahi<221>s<193> (non-violence), brahmacarya ç
(celibacy), satya (speaking the truth in a way that helps living beings), ç
asa<209>graha (non-accumulation of things) are useful s<193>dhanas ç
in yoga. So also the niyamas viz., akrodha (conquest of anger), gurusev<193> ç
(service to the guru), ·auca (cleanliness), mit<193>h<193>ra (moderation ç
in eating) and j<193>gar<220>kat<193> (vigilance).
@S10 = VIDHI
@EMERGENCY = `Vidhi' is the fourth in the pa<210>c<193>rthas. It means ç
activities like bhasmasn<193>na (pouring the holy ash on one's body), ç
upah<193>ra (deliberately acting in a way that people in general will ç
shun the company of the s<193>dhaka), japa (repetition of <185>iva's ç
mantra) and pradak<218>i<207><193> (circumambulation of the <185>ivali<209>ga).
@S10 = DUßKH°NTA
@EMERGENCY = Du<199>kh<193>nta is the last of the pa<210>c<193>rthas. ç
It means cessation of all sorrow and suffering, the same as mukti ç
or liberation. It is achieved by withdrawing the mind from all objects ç
and directing it towards the Lord Pa·upati only. This will result ç
in total surrender to him and living near him (sam<200>pa pr<193>pti). ç
In this mukti, there is no `living alone' (kaivalya, as inthe S<193><209>khya-Yoga ç
systems) or total merging (aikya as in Advaita Ved<193>nta). The pa·u ç
will then be in the eternal company of Pa·upati.
@EMERGENCY = It is interesting to note that the P<193>·upata texts ç
describe the attainment of psychic powers like clairvoyance or clair-audience ç
as a part of du<199>kh<193>nta. But they also discourage the yogi ç
from paying attention to them since they can prevent him from attaining ç
liberation in the ultimate sense.
@SB = 6.	<185>aivasiddh<193>nta
Though the word `<185>aiva-siddh<193>nta' means the doctrine of <185>aivism ç
in general, it has come to be particularly identified with the brand ç
of <185>aivism that has been prevalent in the Tamil country over the ç
last thousand three hundred years. It is more a religion of devotional ç
mysticism than a systematic and speculative philo-sophy, based on ç
the compositions of the N<193>yanm<193>rs or N<193>yan<193>rs who ç
were 63 in number and lived during the period 7th to 12th centuries ç
<MS>A.<|>D<D>.
The canonical literature of Tamil <185>aivism as redacted by Nambi ç
°<207><195><193>r Nambi (<MS>A.<|>D.<D> 1000) can be given as follows:
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(.5000,E1,.6000), ç
ABOVE(.1250), BELOW(.0555), VGUTTER(.0417), KEEP(OFF), L1(R0C0..R2C3), ç
L0(R0C0..R2C0), L0(R0C3..R3C3)
@Z_TBL_BODY = TL, TC2M, TC2M
Sl. Nos.<R>ç
of the books, Authors, Period<R>ç
A.<|>D.
@Z_TBL_BODY = SPACE, TL, TL
, +, +
@Z_TBL_BODY = TL, TL, TC2M
1,, 2 and 3, Tiruj<210><193>na Sambandhar, 7th cent.
4,, 5 and 6, Tirun<193>vukkarasar, 7th cent.
7.*, Sundarar, 9th cent.
8., M<193><207>ikkav<193>cagar (Works†<R>ç
Tiruv<193>cakam and<R>ç
Tirukkovai), 3rd or 9th cent.
9., Nine different saints <R>ç
(Works†Tiruvi·aipp<193> and Tiruppall<193><207><195>u), 900-1100
10., Tirum<220>lar (Work†<R>ç
Tirumandiram), 6th cent.
11., Miscellany of poems by saints Pattinatt<193>r,, Karaikk<193>l ç
Ammaiyy<193>r and others., 
12., Sekkilar (Work†<R>ç
Periyapur<193><207>am), 12th<|>cent.<R>ç
<MS>
@Z_TBL_END = 
The first attempt at a systematic presentation of Tamil <185>aivism ç
was by Meyka<207><195><193>r (13th cent. <MS>A.<|>D.<D>) in his well-known ç
work <185>ivaj<210><193>nabodham, a short treatise of 12 aphorisms. ç
It seems to be a translation in Tamil, of a sanskrit original.
Next in importance, considered a classic in Tamil <185>aivism, is ç
the work <185>ivaj<210><193>na-·ittiy<193>r by Aru<207>andi, a disciple ç
of Meyka<207><195><193>r. This work along with its numerous commentaries ç
is most widely read even now. The <185>ivaj<210><193>nabodham mentions ç
and defines the three basic concepts†Pati, pa·u and p<193>·a†deals ç
with the s<193>dhana for the pa·u to realise Pati and the phala or ç
spiritual fruit that accrues to him.
The philosophy of <185>aivasiddh<193>nta is very similar to that of ç
the P<193>·upata cult, the only difference being that the former accepts ç
36 basic principles (like Kashmir <185>aivism) whereas the latter ç
only 25.
@SPACE = 
@SB = 7.	V<200>ra·aivism
@S10 = Introduction
@SPACE = 
V<200>ra·aivism, also known as the Li<209>g<193>yata Religion or Sect, ç
is a variant of <185>aivism found mostly in the Karnataka region of ç
South India. Though the more orthodox sections claim that it is an ç
ancient religion originating from some mythical teachers like Reva<207><193>r<193>dhya, ç
Maru<202><193>r<193>dhya, Pa<207><195>it<193>r<193>dhya and others, ç
there are others who are inclined to treat it in a figurative sense. ç
For all practical purposes, Basave·vara (d. <MS>A.<|>D.<D> 1168), also ç
known as Basava<207><207>a or Basava, who was the prime minister of ç
the king Bijja<202>a (who ruled from <MS>A.<|>D.<D> 1157 to 1167) was ç
the chief organiser and reformer (if not the founder) of this sect.
A galaxy of saints (numbering more than 300) of this sect like Allama ç
Prabhu and Cannabasava<207><207>a, and women-saints like Akkamah<193>dev<200> ç
have enriched the Li<209>g<193>yata Movement. They revolutionised ç
the religio-social fabric of their times.
@S10 = Principal Dogmas
A special feature of V<200>ra·aivism is the supreme importance, reverence ç
and worship given to the <185>ivali<209>ga or li<209>ga as the sole ç
emblem of God <185>iva. Hence the appropriateness of the name `Li<209>g<193>yata' ç
(`a religion that considers the li<209>ga as the chief support or ç
basis'). After receiving it from a qualified guru in d<200>k<218><193> ç
or initiation, it should be worn on the body always, thereby purifying ç
every part of the body.
The chief tenets of this faith are: <185>iva is the Supreme God. The ç
li<209>ga is his chief symbol or emblem. The pa<210>c<193>k<218>ar<200>- ç
mantra, nama··iv<193>ya, is the redeeming spiritual formula. Pa<210>c<193>c<193>ras ç
and a<218><219><193>-vara<207>as are the main code of conduct. <185>aktivi·i<218><219><193>dvaita ç
is the philosophy behind this system.
As for the process of evolution of the world, the same 36 tattvas ç
or principles given by Kashmir <185>aivism have been adopted here ç
also.
@S10 = Practical Disciplines
But for the three malas or impurities (viz., <193><207>avamala, m<193>y<200>yamala ç
and k<193>rma mala explained earlier), the j<200>va or pa·u (the individual) ç
would have been as wise as <185>iva, the Pati. In order to get rid ç
of these malas, the individual has to take d<200>k<218><193> (initiation) ç
from a duly qualified guru. D<200>k<218><193> is a simple ritual in ç
which the guru worships a li<209>ga and then ties it round the neck ç
of the disciple which will hang like a necklace. The li<209>ga is ç
usually encased in a small silver casket. By this process, the guru ç
gives the mantra (nama··iv<193>ya) and also transmits his spiritual ç
power.
Women also are entitled for d<200>k<218><193> in this cult.
One who is thus initiated is expected to practise the five disciplines ç
known as pa<210>c<193>c<193>ras and also protect himself with eight ç
`coverings,' the a<218><219><193>vara<207>as, stipulated by the system.
@SPACE1 = 
@N-1 = The pa<210>c<193>c<193>ras are:
@SPACE1 = 
@NO = 1.
@NOK = Li<209>g<193>c<193>ra†Worshipping daily, the li<209>ga given ç
to him in d<200>k<218><193>.
@NO = 2.
@NOK = Sad<193>c<193>ra†Earning money by a virtu-ous profession and ç
utilising the savings for serving the needy, including the ja<209>gamas ç
(itinerant preachers).
@NO = 3.
@NOK = <185>iv<193>c<193>ra†Treating all li<209>g<193>yats equally ç
as if they are <185>iva himself.
@NO = 4.
@NOK = Bh<216>ty<193>c<193>ra†Cultivating   humility towards <185>iva ç
and his devotees.
@NO = 5.
@NOK = Ga<207><193>c<193>ra†Zealously guarding one's religion,  protesting  against  dis- ç
respectto one'sGodand religion as also not tolerating cruelty to ç
animals.
@SPACE1 = 
@N-1 = The a<218><219><193>vara<207>as are:
@SPACE1 = 
@NO = 1.
@NOK = Guru†Faith and respect towards the guru.
@NO = 2.
@NOK = Li<209>ga†Treating  the  li<209>ga  with reverence and devotion.
@NO = 3.
@NOK = Ja<209>gama†Respectful treatment of the ascetics and mendicants.
@NO = 4.
@NOK = P<193>dodaka†Purifying oneself by drinking or sprinkling oneself ç
with the water, with which guru's or a ja<209>gama's feet have been ç
washed.
@NO = 5.
@NOK = Pras<193>da†Accepting food sanctified in worship.
@NO = 6.
@NOK = Bhasma†Wearing holy ash on the forehead and other parts of ç
the body as prescribed.
@NO = 7.
@NOK = Rudr<193>k<218>a†using a rudr<193>k<218>a rosary for japa and ç
also wearing it on the body.
@NO = 8.
@NOK = Mantra†Repetition of the pa<210>c<193>-k<218>ar<200>-mantra   (nama··iv<193>ya)   as ç
directed by the d<200>k<218><193>guru.
Since the five <193>c<193>ras and the eight <193>vara<207>as purify ç
a v<200>ra·aiva (or li<209>g<193>yata) by burning up all his impurities, ç
there is †theoritically†no need for him to observe s<220>takas (ceremonial ç
impurities) or cremate his body after death. Hence it is buried.
@S10 = The Doctrine of <185>akti-vi·i<218><219><193>dvaita
Like the vi·i<218><219><193>dvaita of R<193>m<193>nuja (<MS>A.<|>D.<D> ç
1017-1137), the vira·aivas also accept a vi·i<218><219><193>dvaita ç
philosophy, which, however, is a little different. In R<193>m<193>nuja's ç
system, Brahman is advaita (one without a second), but qualified (vi·i<218><219>a), ç
since he has prak<216>ti (acit) and the j<200>vas (cit) in himself, ç
as inseparable entities. However, in V<200>ra·aivism, the vi·i<218><219>atva ç
(being `qualified') is confined only to his <185>akti or power, with ç
the help of which creation, sustenance and dissolution of the world ç
take place. Brahman or God and his <185>akti are non-different, even ç
as heat is from fire or light from the sun. And, Brahman is always ç
conscious of his power. Thus here, vi·i<218><219>atva implies only ç
vimar·a or self- consciousness of the inherent power. Hence the  name  ·akti-vi·i<218><219><193>dvaita  for  this ç
system.
@S10 = The Doctrine of <186>a<219>sthala
In V<200>ra·aivism, <185>iva or Brahman or God is called `Sthala'. ç
He is `Sthala' because he, like the sky or space (sthala= space) ç
is limitless or infinite. Also the word `sthala' can, etymologically, ç
mean that from which the world emerges and evolves, in which it is ç
stationed and into which it gets dissolved (stha = being stationed; ç
la = getting dissolved).
According to the doctrine `<186>a<219>sthala-siddh<193>nta,' <185>iva ç
divides himself into two aspects, li<209>ga and a<209>ga, the former ç
being himself and the latter, the j<200>va. Both these, again, divide ç
themselves into three further aspects; li<209>ga into i<218><219>ali<209>ga, ç
pr<193><207>ali<209>ga and bh<193>vali<209>ga; a<209>ga into ty<193>g<193><209>ga, ç
bhog<193><209>ga and yog<193><209>ga.
When the j<200>va renounces his attachment to worldly objects, he ç
is called `ty<193>g<193><209>ga' and the li<209>ga given to him by ç
his guru at the time of d<200>k<218><193> or initiation is the `i<218><219>ali<209>ga' ç
which is the means of his up<193>san<193> or worship. When due to ç
the up<193>san<193> of the i<218><219>ali<209>ga he is purified, then ç
he enjoys the things of the world as the grace of <185>iva, becomes ç
`bhog<193><209>ga' andexperiences the `pr<193><207>ali<209>ga' (<185>iva's ç
presence in his heart). When he progresses further, to very high states ç
of consciousness in the sahasr<193>racakra, he is called `yog<193><209>ga' ç
and enjoys highest bliss by his identity with <185>iva, now called ç
`bh<193>vali<209>ga'.
@S10 = Conclusion
V<200>ra·aivism, rooted in the ancient <185>aivism, was nourished ç
by a galaxy of saints. Its active propagation of social equality, ç
its stress on work†not only as a social obligation but also as a part ç
of one's spiritual evolution†earned for itself a large number of followers. ç
Even though the social revolution part of it has gradually fizzled ç
out (mainly due to the rigidity of the caste system that still has ç
a sway over the Hindu society), the other aspects ofits religio-philosophical ç
system have certainly enriched Hinduism.
@SB = 8.	Epilogue
Like the two important cults of Vi<218><207>u and <185>akti (or Dev<200>), ç
the cult of <185>iva (or <185>aivism) also has contributed significantly ç
totheethos andspiritualgraceof Hinduism. Rooted in the Vedas ç
and nourished by the secondary scriptures like the <193>gamas and ç
the pur<193><207>as, <185>aivism has grown into a widely accepted ç
and popular religious system, well-integrated with othersystems, ç
sects and subsects within Hinduism.
@NT = saj<193>t<200>yabheda
@N1KERN = (`homogeneous distinction')
According to Advaita Ved<193>nta, Brahman, the Absolute, is one without ç
a second, is entirely homogeneous, and is the only Reality.
The Vi·i<218><219><193>dvaita Ved<193>nta, however, though it accepts ç
Brahman as the Absolute and independent Reality, also accepts the ç
cit (conscious entities, the j<200>vas or the individual souls), and ç
the acit (the insentient prak<216>ti or nature comprising the three ç
gu<207>as) as secondary or dependent realities included in itself.
To prove the possibility of such internal distinctions, the protagonists ç
of this school declare that bheda or distinction can be of three different ç
kinds: vij<193>t<200>ya bheda (heterogeneous distinction as that of ç
a cow from a horse); saj<193>t<200>yabheda (homogeneous distinction ç
as that of one cow from another cow); svagatabheda (internal distinction ç
as between the head and the tail of the same cow).
Though Brahman does not have the first two bhedas†because it is the ç
only and independent Reality†it does have the third (svagatabheda).
@NT = <185>akadv<200>pa
See <MS>SAPTADV®PAS.<D>
@NT = <185><193>kalya
The B<216>had<193>ra<207>yaka Upani<218>ad (3.9) describes in detail, ç
the philosophical dispu-tation between Y<193>j<210>avalkya and Vidagdha ç
<185><193>kalya in the court of the king Janaka-Vaideha. The discussion ç
centered round the number of devas or gods. Ultimately, Y<193>j<210>avalkya ç
won and <185><193>kalya lost his life due to the curse of the former. ç
The main reason was that <185><193>kalya was `Vidagdha', vain and ç
arrogant due to his scholarship.
Some say that Vidagdha was his name (since he was a great scholar) ç
whereas the word <185><193>kalya indicated that he was the son of ç
the sage <185>akala.
The Nirukta (6.28) mentions one <185><193>kalya as a padap<193><219>hak<193>ra ç
(an expert in breaking the words of the Vedic Sa<221>hit<193> †See ç
<MS>GHANAP°<187>HA.<D>) of the <184>gveda.
Another <185><193>kalya is mentioned by P<193><207>ini  (circa  500 ç
<MS>B.<|>C.<D>)  four  times  in his  A<218><219><193>dhy<193>y<200>.  He  was  probably  a ç
grammarian.
@SPACE1 = 
The well-known sage Ka·yapa was once saved from public ridicule by ç
a teacher, <185><193>kalya by name, who prescribed some special purificatory ç
rites.
@NT = <185><193>kambhar<200>
@N1 = (`One who is full of<R>ç
vegetables')
In the Durg<193>sapta·at<200> (11.49) the Divine Mother, while addressing ç
the gods who had supplicated her, tells them that when severe drought ç
affects the world, she will bring out plenty of ·<193>ka or nourishing ç
vegetables out of herself and save the famished people.
She is an aspect of Durg<193> having sixteen hands, carrying in them ç
the following items: spear, noose, skull-cup, bow, arrow, thunderbolt, ç
goad, shield, conch, discus, mace, snake, sword, magic wand and cudgel. ç
One hand shows the abhayamudr<193> (gesture of protection).
She is described as the Mother of the three worlds Trailokyajanan<200>.
The Mah<193>bh<193>rata (Vanaparva 84.13) describes a place of ç
pilgrimage known as<185><193>kambhar<200>. Fasting at this place ç
improves one's health.
@NT = S<193>kamedha
An <193>hit<193>gni (one who has ceremonially established the Vedic ç
fires) was expected to perform a particular group of sacrifices†known ç
as C<193>turm<193>sya†once every four months. (See <MS>C°TURM°SYA.<D>) ç
Each of them was called a parvan (part or joint). The third of these ç
is S<193>kamedha.
These sacrifices marked the advent of a particular season.
The S<193>kamedha was to be performed at the beginning of the hemanta-<216>tu ç
(autumn), on the full-moon day of themonth of K<193>rttika or M<193>rga·<200>r<218>a ç
(November). The sacrifice is of the i<218><219>i type (See <MS>I<186><187>I<D> ç
for details.) and is spread over two days.
On the preliminary day, three i<218><219>is are performed to the three ç
deities: Agni-an<200>kavat, s<193>ntapana-Maruts and g<216>ha-medhin-Maruts. ç
The offerings to these, respectively, are: a cake on eight potsherds, ç
a caru (porridge from unpounded rice or barley grains) and another ç
caru boiled in milk of all the cows belonging to the sacrificer.
The priests and the sons as also grandsons of the sacrificer are to ç
partake of the remainings of these offerings.
On the principal day, a homa is performed with a darv<200> (wooden ç
spoon), scraping out the remainder of the cooked rice of the previous ç
day.
An interesting (and intriguing?) part of the rite is to bring a bull ç
and make it bellow! It is later on gifted away.
This is then followed by a mah<193>havis (great offerings) and Mah<193>pit<216>-yaj<210>a ç
dedicated to certain classes of pit<216>s (manes) like barhi<218>adpit<216>s ç
and agni<218>v<193>tta-pit<216>s.
@NT = S<193>keta
S<193>keta is another name for Ayodhy<193>, the capital of the country ç
Kosala.
It is rather intriguing that this name for Ayodhy<193> is not found ç
in the R<193>m<193>ya<207>a of V<193>lm<200>ki, though it has been ç
mentioned in the Raghuva<221>·a (5.31) of K<193>lid<193>sa (200 ç
<MS>B.C.<D>). By the time of Gautama Buddha (6th century <MS>B.<|>C.<D>) ç
it was considered one of the six great cities of Bharatavar<218>a. ç
In all the works of Buddhists, Jains, Greeks and of Pata<210>jali ç
(200 <MS>B.<|>C.<D>), Ayodhy<193> has always been referred to as S<193>keta ç
only.
@NT = ·<193>kh<193>s
@N1 = (`branches [of the Vedas]')
See <MS>VEDAS.<D>
@NT = sakhyabhakti
@N1 = (`devotion [to God] as a<R>ç
friend')
Bhakti  or  devotion  to  God,  can assume several forms. The N<193>rada ç
Bhakti-s<220>tras, a well-known treatise on bhakti, describes eleven ç
such modes (s<220>tra 82). The sixth mode in this series is called ç
`sakhy<193>sakti,' same as sakhyabhakti.
It denotes love of God as one's dear friend. Arjuna, Uddhava, Sud<193>ma ç
(or Kucela) and the cowherd boys of V<216>nd<193>bana are quoted as ç
the classic examples. The Bhagavadg<200>t<193> (11.41, 42) reflects ç
this idea very well.
See also <MS>BHAKTI.<D>
@NT = <185><193>kin<200>
She is an aspect of the Divine Mother (<185>akti or P<193>rvat<200>).
Each of the six cakras or psychic centres in the human body (See <MS>CAKRAS.<D>) ç
is associated with a <185>akti as the presiding deity. The <185>akti ç
of the vi·uddhacakra is called <185><193>kin<200>, the <185>iva aspect ç
being Sad<193>·iva.
She wears yellow garments and has four hands in which she carries ç
bow, arrow, noose and goad.
@NT = <185>akradhvajamahotsava
See <MS>INDRADHVAJA.<D>
@NT = s<193>k<218><200>
@N1 = (`witness')
A s<193>k<218>in or s<193>k<218><200> is one who witnesses the happenings ç
around him in a detached way, and can give an unbiased account.
In the Hindu judicial system a s<193>k<218><200> or a witness is accepted ç
as reliable if he comes from a respectable family, is deeply religious ç
by temperament, is devoted to truth and is straightforward.
A few of the interesting descriptions of an unreliable witness are: ç
shifting the position constantly, licking the corner of his own lips, ç
sweat on the forehead, change of colour of the face, faltering speech ç
and contradictory statements.
In Ved<193>nta, the j<200>v<193>tman (the individual Self) is called ç
s<193>k<218><200> or s<193>k<218><200>- caitanya since he is a witness ç
to all the three states of consciousness, viz., j<193>grat (waking), ç
svapna (dreaming) and su<218>upti (deep sleep).
°tman or Brahman also is called s<193>k<218><200> in the Upani<218>ads ç
(vide <185>vet<193>·vatara Upani<218>ad 6.11) and the Bhagavadg<200>t<193> ç
(9.18) since he is witnessing everything, but is unaffected by the ç
changes of the empirical world.
@NT = ·<193>kta
@N1 = (`worshipper of <185>akti [or Divine Mother]')
Worshippers of God, in Hinduism, are generally divided into three ç
groups: the vai<218><207>avas, the ·aivas and the ·<193>ktas. Vi<218><207>u, ç
<185>iva and <185>akti (Divine Mother, P<193>rvat<200> and her aspects) ç
are, respectively, the deities they worship. Of course, even these ç
deities are facets of Brahman, the Absolute.
The religion and the philosophy of the <185><193>ktas is contained ç
in the tantras.
See also <MS>TANTRAS.
@NT = <185><193>kt<193>gamas
°gamas are a special class of Hindu religious literature devoted to ç
the propagation of the various sects centred round the cult-deities. ç
They are generally classified into three groups viz., <185>aiv<193>gamas, ç
<185><193>kt<193>gamas and Vai<218><207>av<193>gamas, dealing with ç
the three deities <185>iva, <185>akti (or the Divine Mother, usually ç
an aspect of P<193>rvat<200>) and Vi<218><207>u.
The  <185><193>kt<193>gamas  are  also  called Tantras. See <MS>TANTRAS<D> ç
for details.
@NT = <185><193>ktaism
See <MS>TANTRAS.<D>
@NT = <185>akti
@N1 = (`[Divine] Power [as Goddess]')
@EMERGENCY = The universe that we see and experience is a bundle of ç
energy, both packed and unpacked. This is the discovery of modern ç
science, which incidentally, has demolished the distinction between ç
matter and energy. According to it, there is one basic energy behind ç
all forms of matter and energy. However, it seems to be still far ç
off from discovering the relationship between matter on the one hand, ç
and, mind and life on the other. Are they also, though apparently ç
poles apart, manifestations of the same basic energy? Could it be ç
that the same energy or matter, at one level of vibration, is called ç
`matter', at another, `mind' and yet another, `life'? Modern science ç
or the modern scientists, devoting most of their attention to the ç
manifest material universe may not even be prepared to concede this ç
possibility! Hindu philosophy, based on the Ved<193>nta and a group ç
of works based on the Ved<193>ntaand more commonly known as the Tantras* ç
postulates exactly this! The source and sustenance of all creation, ç
whether at the level of matter or life or mind, is one and one only. ç
It is <185>akti (=energy). Brahman (the Absolute) of the Ved<193>nta ç
and <185>akti or Dev<200> of the Tantras are identical. When that ç
`energy' is in a static condition, with neither evolution nor involution, ç
when the universe to be created is not even in a seed-form as it were, ç
it is called Brahman. When it starts evolving into this creation, ç
sustains it and withdraws it back into itself, it is called <185>akti. ç
If Brahman is the coiled serpent in sleep, <185>akti is the same serpent ç
in motion. If Brahman is likened to the word, <185>akti is its meaning. ç
If Brahman is like fire, <185>akti is its burning power. The two are ç
inseparable: one in two and two in one.
In the Hindu mythological literature, as also in the Tantras, this ç
energy is always pictured as a female deity, the Dev<200>, as the ç
consort of its counterpart male deity. Each member of the Trinity ç
has his <185>akti or Dev<200> as his consort: Sarasvat<200> of Brahm<193>, ç
Lak<218>m<200> of Vi<218><207>u and P<193>rvat<200> of <185>iva. However, ç
the mother-cult that has evolved over the last few centuries is predominantly ç
centered round P<193>rvat<200>, the consort of <185>iva.
Mother-worship and mother-cult are not alien to the Vedic religion ç
as some suggest. The concept of Aditi†the mother of gods, personification ç
of nature, and the Ambh<216><207><200>s<220>kta as also the R<193>tr<200>s<220>kta ç
of the <184>gveda clearly contain the origins of mother-worship
See  also  <MS>LAK<186>M®<D>,  <MS>P°RVAT®<D>,  and <MS>SARASVAT®.<D>
@NT = ·aktic<193>lan<200>-mudr<193>
@N1 = (`pose of the body that helps in activating the Ku<207><195>alini')
<185>akti is the Ku<207><195>alin<200> power, the basic and total ç
energy of every human being, imagined to be like a coiled serpent, ç
lying at the root of the spinal column. The yogic exercise that helps ç
this power to be roused and move towards the sahasr<193>ra-cakra in ç
the head is called `·aktic<193>lan<200>-mudr<193>'. Some of the steps ç
involved in its practice are: sitting with a loin cloth only, smearing ç
the body with holy ash (vibh<220>ti), siddh<193>sana posture, special ç
pr<193><207><193>y<193>ma techniques as instructed by the guru and ç
so on.
Being a complicated exercise, it has to be practised directly under ç
the guidance of an expert teacher of yoga.
See also <MS>CAKRAS.
@NT = <185>aktivi·i<218><219><193>dvaita
See under <MS><185>AIVISM<D>.
@NT = ·akuna
@N1 = (`omen,' `prognostic sign')
Belief in the supernatural is a common trait of humanity all over ç
the world, even from the most ancient times.
<185>akuna means a bird ingeneral. Even in the <184>gveda (10.165.1-5), ç
the bird kapota (pigeon) has been regarded as a harbinger of impending ç
evil and misfortune. Hence the word ·akuna gradually came to mean ç
premonition of evil conveyed by the cries, the sounds and the movements ç
of birds and of other animals. This, gradually, developed into a science ç
of prognostication.
There is a vast literature on this subject. Some of the works are: ç
Matsya-pur<193><207>a (Chapters 237, 241 and 243); Agnipur<193><207>a ç
(Chapters 230 to 232) Padma-pur<193><207>a (4.100.65 to 126); B<216>hatsa<221>hit<193> ç
(Chapters 85 to 95); B<216>hadyogay<193>tr<193> (Chapters 23 to ç
27) and Vasantar<193>ja-·akuna.
The last is a comprehensive work belonging to the early part of the ç
eighth century and has been quoted extensively by later writers on ç
this subject.
The details given in these works regarding the ·akunas and their interpretations ç
are, to say the least, mind-boggling!
The following is a short consolidated list of birds, animals and other ç
living beings whose sounds and movements are considered as ·akunas, ç
good or bad: crow, eagle, owl, cat, snake, chameleon, lizard, dog, ç
jackal and frog as also human beings.
The prognostication differs from animal to animal and from case to ç
case. In the case of crows and cats, it is their movement across our ç
path that indicates the results. In the case of dogs, jackals and ç
lizards it is their sound. In some cases, it may be the very sight ç
of a person or an object.
Results indicated may relate to travelling, success or otherwise of ç
an important work, diseases and their cure, wealth and poverty, promotion ç
or demotion in service, harmony or disharmony in the family, good ç
rains or drought, welfare or danger to the country and so on.
Some other omens like the throbbing of one's limbs or sneezing are ç
also included in the list of ·akunas.
A sample of the ·akunas may now be given just to give an idea of the ç
subject:
When a person has started on a journey and sees a cat moving across ç
his path from left to the right, it is a bad sign. If he sees married ç
ladies carrying water pots or milk, or, an elephant or a horse, it ç
is a good omen.
@SPACE1 = 
When a person is thinking about some important work, and someone sneezes ç
once in his presence, it indicates failure of that work. Similarly, ç
if he finds that his right limbs are throbbing, it indicates success. ç
(For women, throbbing of the left limbs is considered auspicious.)
By sincere prayer to God, the evil effects prognosticated may be eliminated ç
or minimised.
@NT = <185>akuni
<185>akuni of the Mah<193>bh<193>rata could rival even Satan in ç
his villainy and craftiness. If Duryodhana's heart was full of the ç
raging fire of jealousy and hatred, <185>akuni was the breezy wind ç
that spread it in his whole personality, ultimately destroying his ç
entire race.
He was the eldest son of the king Subala of the country of G<193>ndh<193>ra. ç
G<193>ndh<193>r<200>, the chief queen of the blind king Dh<216>tar<193><218><219>ra, ç
was his sister. Ever since her marriage, <185>akuni started living ç
in Hastin<193>pura, the capital of the kings of the Kuru race.
He had the master-mind of an evil genius and relentlessly prodded ç
Duryo-dhana in his wicked pursuits.
His nefarious designs and vile deeds may briefly be listed as follows: ç
cheating the P<193><207><195>avas in the game of dice; advising Duryodhana ç
to decimate the P<193><207><195>avas byany and every means; encouraging ç
Duryodhana to exhibit his glory, wealth and power before the P<193><207><195>avas ç
living as recluses in the forest and so on. He too participated in ç
the Kuruk<218>etra war and was killed by Sahadeva on the last day.
He is said to have been born out of the anger of the devas or gods, ç
to destroy righteousness (°diparva 63.111).
See also <MS>MAH°BH°RATA.<D>
The epics and the pur<193><207>as mention a few other <185>akunis ç
like a serpent, a demon, a king and a sage.
@NT = <185>akuntal<193>
The origins of the well-known legend of <185>akuntal<193> based on ç
which the great poet K<193>lid<193>sa (2nd century <MS>B.<|>C.<D>) ç
wrote his immortal drama Abhij<210><193>na-·<193>kuntalam lie in ç
the Mah<193>bh<193>rata (°diparva, Chapters 68-74) as also the ç
Padmapur<193><207>a (Svarga-kha<207><195>a).
She was born to Menak<193> (a nymph) from Vi·v<193>mitra, to wreck ç
whose austerities Indra, the king of the gods, had sent her. However, ç
as both the parents abandoned her, the ·akunta birds (ravens) took ç
care of her, thereby getting her the name <185>akuntal<193>.
The sage Ka<207>va who found the abandoned baby, carried her to his ç
own hermitage and brought her up as his foster daughter.
When she had grown into a beautiful young woman, Du<218>yanta, the ç
king of the lunar race happened to visit Ka<207>va's hermitage. They ç
fell in love with each other and married according to the g<193>ndharva ç
rites. (See <MS>VIV°HA<D> for details.) The same was approved by the ç
sage Ka<207>va who came to know about it later.
In course of time <185>akuntal<193> gave birth to a heroic child whose ç
strength and valour astonished everyone. He was named Sarvadamana ç
as also Bharata.
Later, when <185>akuntal<193> went with Bharata and the disciples ç
of the sage Ka<207>va to Du<218>yanta to live with him, he hesitated ç
to accept her. At the intervention of an <193>k<193>·av<193><207>i ç
(a celestial message from an unseen god), he accepted her as his queen ç
and coronated Bharata as the crown-prince. The name Bh<193>ratavar<218>a ç
or Bh<193>rata for India and the lineage of Bharatava<221>·a started ç
from him.
There is a slight deviation in the story as given by K<193>lid<193>sa. ç
Due to a curse of the sage Durv<193>sa who was once ignored by <185>akuntal<193>, ç
Du<218>yanta could not recognise her. However, when the signet ring ç
he had given to her was accidentally lostbut miraculously recovered ç
and shown to him, he remembered everything and gracefully accepted ç
her.
@NT = ·<193>l<193>
@N1 = (`shed')
<185><193>l<193> is a shed built for the performance of Vedic sacrifices. ç
It is built to the west of mah<193>vedi (See <MS>MAH°VEDI.<D>) having ç
its beams in the easterly direction. Henceit is also called pr<193>c<200>nava<221>·a ç
(with bamboo beams oriented to the east).
It is a quadrangular shed measuring 20 x 10 aratnis (one aratni = ç
1/5 the height of the sacrificer). There are four doors in the four ç
cardinal directions and also windows at the corners. The shed is covered ç
and enclosed with mat. A room for boiling milk and a hut for the sacrificer's ç
wife (hence called patn<200>·<193>l<193>) are also built round it.
Inside the ·<193>l<193>, three fires are lighted. Hence the name agni·<193>l<193> ç
also.
@NT = <185><193>lagr<193>ma
@SB = Introduction
In Hinduism, God can be worshipped in two forms: the iconic and the ç
aniconic. Images worshipped in temples or at home †this may include ç
pictures or paintings also†belong to the first group. Yantras (mystical ç
line-drawings), ·ivali<209>gas, kumbhas (pots filled with water), ç
·<193>la-gr<193>mas, spha<219>ikas (crystals) and ·o<207>a·il<193> ç
(piece of red metallic stone) belong to the second group.
Out of these, ·ivali<209>gas and ·<193>la-gr<193>mas are more widely ç
worshipped.
The literature concerning the ·<193>la-gr<193>mas is copious. Apart ç
from the several pur<193><207>as like Brahmavaivarta, Garu<195>a, ç
Padma, Skanda and Var<193>ha, which deal with them, there are ç
special treatises also on the same, like <185><193>lagr<193>malak<218>a<207>am, ç
<185><193>lagr<193>mapar<200>k<218><193> (of An<220>pasi<221>ha), ç
<185><193>la-gr<193>mam<220>lalak<218>a<207>apaddhati, and <185><193>la-gr<193>ma·il<193>par<200>k<218>a<207>apaddhati.
@SB = The Name
<185><193>lagr<193>ma is actually a village (and a place of pilgrimage) ç
on the bank of the river Ga<207><195>ak<200> in Nepal. As it has ·<193>l ç
trees (Shorea robusta or Valica robusta) in abundance, it got that ç
name. Since these stone emblems are found in the Ga<207><195>ak<200> ç
river near this village, they too came to be known as <185><193>lagr<193>mas. ç
The river too got its additional name <185><193>lagr<193>m<200>. (See ç
<MS>GAØ£AK®<D> also.)
@SB = What it is
The ·<193>lagr<193>ma stone is actually an ammonite, the fossilized ç
shell of an extinct species of mollusk found in the Ga<207><195>ak<200> ç
river. It invariably contains the discus or the cakra-marks.
@SB = Source of <185><193>lagr<193>mas
@SPACE1 = 
The ·<193>lagr<193>mas are natural objects found in the river Ga<207><195>ak<200> ç
of Nepal and are never man-made. There are four specified spots in ç
the river within Nepal's jurisdiction, from where these stones are ç
picked up.
@SPACE = 
@SB = Paur<193><207>ic Legends
@SPACE1 = 
There are several interesting legends connected with the appearance ç
or manifestation of the ·<193>lagr<193>mas on earth.
The river goddess Ga<207><195>ak<200> performed severe austerities ç
to please Vi<218><207>u and get him as her child. Vi<218><207>u granted ç
theboon and became the ·<193>lagr<193>ma stones in her womb, i.e., ç
the waters of the river.
According to another version, the river Ga<207><195>ak<200> was formed ç
by the drops of sweat of Vi<218><207>u and <185>iva, containing the ç
·<193>lagr<193>mas.
@SPACE = 
@SB = Sanctity of the <185><193>lagr<193>mas
@SPACE1 = 
Even from ancient times, ·<193>lagr<193>mas have been considered very ç
sacred emblems of Vi<218><207>u. The images of N<193>r<193>ya<207>a ç
at Badar<200>n<193>tha (in Uttaranchal) and that of K<216><218><207>a ç
at U<195>upi (in Karnataka) are said to be carved out of the ·<193>lagr<193>ma ç
stone. In the pa<210>c<193>yatana p<220>j<193> system (See <MS>PA<178>C°YATANAP<188>J°<D> ç
for details.) it is the ·<193>lagr<193>ma that is used to represent ç
god Vi<218><207>u.
Unlike  the  images  installed  in temples or the ones used at home ç
for worship, wherein the presence of God has to be induced or infused ç
through appropriate mantras, the ·<193>lagr<193>mas have His presence ç
eternally, by their very nature. Not only that, they are believed ç
to possess inherently, a sahajavibh<220>ti or mysterious divine power.
This has given rise to several popular beliefs. Some of them are:
@NO = 1)
@NOK = Placing a ·<193>lagr<193>ma on a plate along with ·a<209>kha ç
(conch) and covered withtulas<200> leaves (holy basil) is an extremely ç
meritorious act.
@NO = 2)
@NOK = Any religious observance like d<193>na (gifts), vrata (vows), ç
·r<193>ddha (obsequial rite) and p<220>j<193> (worship), if done in ç
association with the ·<193>lagr<193>ma, will confer greater benefits.
@NO = 3)
@NOK = Sipping or drinking the water in which a ·<193>lagr<193>ma ç
has been bathed, will help in the absolving of all sins. When put ç
in the mouth of a dying person, this water will help him attain the ç
world of Vi<218><207>u.
@NO = 4)
@NOK = Rituals performed on holy occasions like the periods of an ç
eclipse become more effective if done in the presence of a ·<193>lagr<193>ma.
@NO = 5)
@NOK = If a witness in a court of law gave his statement holding a ç
·<193>lagr<193>ma in his hand, it was taken as true, since telling ç
lies would have serious repercussions on him. The same process applied ç
to making solemn promises also.
@NO = 6)
@NOK = Worship of a ·<193>lagr<193>ma, even without devotion, can ç
confer liberation.
@NO = 7)
@NOK = The gifting of a ·<193>lagr<193>ma stone was considered an ç
extremely meritorious act whereas selling it was frowned upon. The ç
one that was bought was declared unfit for worship!
@SB = Modes of Worship of a <185><193>lagr<193>ma
Fire, which already exists in a piece of wood, manifests itself when ç
rubbed against another piece of wood (as in the case of the ara<207>is) ç
(See <MS>ARAØI<D> for details.). So also, Vi<218><207>u who is already ç
present in the ·<193>lagr<193>ma stone, manifests himself when it ç
is worshipped.
For the same reason, no process of consecration or purification is ç
needed for a ·<193>lagr<193>ma before worshipping it. So also there ç
is no need for initiation from a guru with a mantra or learning of ç
a formal procedure. What is really needed is a pure conduct, freedom ç
from arrogance and infatuation, and, aversion to the base temptations ç
of the world.
The simplest form of worship of a ·<193>lagr<193>ma consists in bathing ç
it with water or milk, keeping tulas<200> leaves on it and offering ç
some sweet preparation as naivedya (food for the deity).
A few other details connected with its worship are:
@SPACE = 
@NO = 1)
@NOK = The numbers of ·<193>lagr<193>mas that may be worshipped together ç
can be four or six or any even number, except two. Worshipping one ç
is permitted, though odd numbers is not.
@SPACE1 = 
@NO = 2)
@NOK = Worshipping twelve ·<193>lagr<193>mas every day with devotion ç
is considered highly meritorious.
@SPACE1 = 
@NO = 3)
@NOK = Even though a ·<193>lagr<193>ma has been damaged, it does not ç
become unfit for worship. However, the one that has been secured by ç
unethical means like fraud or force, becomes unfit for worship. Even ç
if worshipped, it will be in vain.
@SPACE1 = 
@SB = Varieties, Shapes and Sizes
@SPACE1 = 
The ·<193>lagr<193>mas are stones, rendered round and smooth by water ç
currents flowing for millenniums. They are distinguished by the discus-like ç
(= cakra) marks left by ·<193>l<193>s or vajrak<200><219>as (ammonite) ç
which had entered into them, for residence, and got fossilized. Thus ç
the cakra-formation is the most distinguishing mark of this stone ç
emblem. Since the cakra or the discus is the chief weapon and mark ç
of god Vi<218><207>u, these stone emblems came to be regarded as Vi<218><207>u ç
Himself in that aniconic form.
As many as eighty-nine varieties of ·<193>lagr<193>ma have been listed ç
by experts and treatises on them. They are available in several forms ç
like round, umbrella-shaped, spear-shaped, cart shaped, crooked and ç
so on. Their sizes also vary from that of an <193>malaka (gooseberry, ç
myrobalam) to as big as a ball that can just be covered by both the ç
palms (about 20 cms. or 8 inches in diameter).
Depending on the smoothness of the surface, colour and shape, ·<193>lagr<193>mas ç
are classified as uttama (the best), madhyama (the middling) and adhama ç
(the worst). Perfectly smooth and blue-black ones belong to the first ç
group. The ones with bluish or blackish colour belong to the second ç
group. If the colour is tawny, yellowish, ash-grey or red, they belong ç
to the last group and must be avoided.
@SB = Identification and Testing
Examination and identification of ·<193>lagr<193>mas (·<193>lagr<193>mapar<200>k<218><193>) ç
is an art and science, well-developed. Several pur<193><207>as like ç
Agni, Brahma, K<220>rma and Padma as also a few independent ç
works, contain exhaustive accounts of this subject.
Though the ·<193>lagr<193>mas are emblems of Vi<218><207>u in general, ç
there are several varieties of them, each representing a particular ç
aspect of his. The factors that contribute to this variety are: size, ç
shape, colour, texture, the number and nature of cakras (discus-forms) ç
as also other marks like lines and holes.
Since genuine ·<193>lagr<193>mas are considered extremely sacred and ç
beneficial, and also bought or sold for fabulous prices, fake ones ç
are produced by unscrupulous traders cheating the gullible devotees. ç
Hence, the standard texts on this subject prescribe a few tests to ç
check the genuineness or otherwise of these stones. Some of them are: ç
striking it gently or all sides by a small hammer or knocking it with ç
one's finger after holding it firmly; placing it on a plate with its ç
equal weight of rice or keeping it in milk in a bowl and leave it ç
for a night.
The former test shows that it is fake, if soft powders fall down. ç
In the latter case, a slight increase in the weight of rice or the ç
quantity of milk proves that the stone is not only genuine but also ç
beneficial.
@SPACE = 
@SB = Aspects of Vi<218><207>u Represented
The aspects of Vi<218><207>u represented by the ·<193>lagr<193>mas ç
are quite numerous. The designation of each one is determined by the ç
distinguishing marks of identification as given by the pur<193><207>as ç
and special treatises. For instance, if a ·<193>lagr<193>ma is round ç
in shape, has two cakras at the opening and is of whitish hue, it ç
represents V<193>sudeva. If it has a wide opening, is black in colour ç
with two cakras on the left side, it represents Lak<218>m<200>-narasi<221>ha ç
and so on.
Some of the other aspects are: the ten avat<193>ras (incarnations) ç
of Vi<218><207>u; N<193>r<193>ya<207>a; Padman<193>bha; Hayagr<200>va; ç
D<193>modara;   Sudar·ana;   Gad<193>dhara; Madhus<220>dana and so ç
on.
@SB = Fruits of Worshipping <185><193>lagr<193>mas
The pur<193><207>as are particular in mentioning the various fruits ç
and results that can be got by worshipping certain specified ·<193>lagr<193>mas. ç
For instance, to obtain†
mantrasiddhi (rousing the inherent power of a mantra), one should ç
worship a smooth and shining stone.
freedom from sins†pale-coloured one.
progeny†yellow one.
fame†black one.
worldly prosperity†blue-black one.
@SPACE1 = 
These texts also warn that worship of the wrong ones will bring about ç
great harm. For example, worship of a red one will cause illness, ç
whereas the worship of a very large one will cut the life-span. Hence  the  possessor  of  a  ·<193>lagr<193>ma ç
emblem should know all the essential details before keeping it and ç
worshipping it.
@SB = Dv<193>r<193>vat<200>-·il<193>
The dv<193>r<193>vat<200>·il<193>s are white stones similar in shape ç
to the ·<193>lagr<193>mas. They too have cakras (and other marks). ç
They are available in Dv<193>rak<193> (now in Gujarat), a famous place ç
of pilgrimage for the devotees of K<216><218><207>a. If ·<193>lagr<193>mas ç
are worshipped along with these, then all the sins of the worshipper ç
are destroyed.
@SB = Conclusion
The followers of every religion believe what  their  scripture  says,  especially ç
regarding <|>things <|>beyond<|> the<|><|>ken<|> of <|>the
