@NT = <185>uddh<193>dvaita
@N1 = (`the pure advaita')
The system of philosophy of Vallabh<193>-c<193>rya or Vallabha (<MS>A.<|>D.<D> ç
1481-1531) is known as <185>uddh<193>dvaita.
Vallabha does not accept <185>a<209>kara's (<MS>A.<|>D.<D> 788-820) ç
advaita as sufficiently non-dualistic since he also accepts m<193>y<193>, ç
a principle of illusion, thereby negating non-dualism!
According to Vallabha, m<193>y<193> is a real power of Brahman, ç
the Saccid<193>nanda, inherent in him. Hence, since there is no second ç
reality different from or outside Brahman, his philosophy should be ç
called <185>uddh<193>dvaita†is his claim.
See also <MS>VALLABHA.<D>
@NT = ·uddham<193>y<193>
@N1 = (`pure m<193>y<193>')
In the Siddha system of medicine ·uddham<193>y<193> is pure matter ç
and a·uddha-m<193>y<193> is impure matter. The latter is corruptible ç
whereas the former is always incorruptible.
When by a special method, the a·uddham<193>y<193> is purified and ç
brought into the line of ·uddham<193>y<193>, there will be no bodily ç
death. The method, however, has to be learnt from the expert Siddhas.
In K<193>·m<200>r <185>aivism, ·uddham<193>y<193> is the intrinsic ç
power of <185>iva to create the world, sustain it and withdraw it†likethe ç
burning power of fire†in its purest form.
When it manifests itself in the form of the five ka<210>cukas (or ç
sheaths) and apparently binds <185>iva it becomes a·uddham<193>y<193> ç
or impure m<193>y<193>.
See `K<193>·m<200>r <185>aivism' under <MS><185>AIVISM.<D>
@NT = ·uddhasattva
@N1 = (`the pure sattva')
See <MS>VI<185>I<186><187>°DVAITA VED°NTA DAR<185>ANA.<D>
@NT = ·uddhavidy<193>tattva
@EMERGENCY = See `K<193>·m<200>r <185>aivism' under <MS><185>AIVISM.<D>
@NT = ·uddhi
@N1 = (`purification')
@EMERGENCY = <185>uddhi or purification†which is more ceremonial than ç
physical†is a very vast subject. It covers such areas as a·auca (impurity ç
that accrues to a person due to the birth or the death of a near relative) ç
(See <MS>A<185>AUCA<D> for details.), purification of a person after ç
contact with an impure object or on certain occurrences, and purification ç
of food, vessels, ponds and other things after they are polluted.
@EMERGENCY = The literature on ·uddhi is very extensive.
@EMERGENCY = <185>uddhi  has  been  categorised  in several ways; ç
for instance: b<193>hya (external, like bath) and <193>ntara (internal, ç
like purity of emotions). According to another classification, ·uddhi ç
comprises purity of body, of speech, of mind and of financial dealings. ç
A third one states ·uddhi consists in avoiding forbidden food, in ç
associating only with sinless persons and in firmly abiding by one's ç
svadharma (prescribed duties).
However, all dharma·<193>stra treatises stress the importance of mental ç
purity.
It is interesting to note that the °pastamba <185>rautas<220>tras ç
(2.12) declares that the performer of the Pavitre<218><219>i (and ç
two more similar i<218><219>is or sacrifices) purifies himself and ç
ten generations of his family.
Various expiatory rites (pr<193>ya·cittas) also purify a person who ç
might have committed sins or evil deeds, knowingly or unknowingly.
The word ·uddhi has also been usedfor the process of reconversion ç
to Hinduism. See <MS>PAR°VARTANA<D> for details.
@NT = ·<220>dras
See <MS>VARØA<D> and <MS>VARØ°<185>RAMADHARMA.<D>
@NT = Sugr<200>va
@N1 = (`one with a beautiful neck')
Sugr<200>va and V<193>l<200> were the sons of the v<193>nara king ç
(of Ki<218>kindh<193>) <184>k<218>arajas, born by the grace of S<220>rya ç
(sun-god) and Indra (king of gods).
See <MS>R°M°YAØA<D> for details.
@NT = suicide
See <MS>°TMAHATY°.<D>
@NT = <185>uka
<185>uka, the son of the sage Vy<193>sa, was an extremely great and ç
respected sage. He is said to have been born of the celestial maiden ç
Gh<216>t<193>c<200> when she had taken the form of a ·uka or parrot, ç
from Vy<193>sa.
He had his education from his father as also from the king Janaka.
His self-control was so great that Rambh<193>, a reputed apsar<193> ç
(celestial maiden) failed to entice him by her amorous charms.
It was he who learnt the Bh<193>gavata from his father Vy<193>sa ç
and then taught it to the king Par<200>k<218>it during his last days.
There was another <185>uka (along with S<193>ra<207>a) who was one ç
of the spies of R<193>va<207>a and who had sneaked into the army camp ç
of R<193>ma. However, R<193>ma ordered that he be shown everything ç
and sent back to R<193>va<207>a!
@NT = ·ukan<193>s<200>
See <MS>ARDHAMAØ£APA.<D>
@NT = <185>ukla Yajurveda
See <MS>YAJURVEDA.<D>
@NT = <185>uklayajurveda Sa<221>hit<193>
The <185>uklayajurveda Sa<221>hit<193>†also known  as  the  V<193>jasaneya  Sa<221>hit<193>† ç
attributed to the great sage Y<193>j<210>avalkya is said to have 15 ç
·<193>kh<193>s or recensions. They actually bear the names of the ç
disciples to whom Y<193>j<210>avalkya taught. Some of them are: K<193><207>va, ç
M<193>dhyandina, J<193>b<193>la,  Baudheya,  <185><193>peya,  P<193>r<193>·ara, ç
Baijav<193>pa and so on.
However, only the first two are extant now, the rest being completely ç
lost.
The  K<193><207>va·<193>kh<193>  contains  2086 mantras spread over ç
40 adhy<193>yas or chapters. The M<193>dhyandina·<193>kh<193> also ç
has 40 chapters, but only 1900†or 1975 according to another version†mantras.
The entire work is in verses without prose portions as in the K<216><218><207>a ç
Yajurveda.
The following is a brief summary of the contents:
@S10N = Chapter 1 (31 verses)
Dar·ap<220>r<207>am<193>sa sacrifices; ty<193>ga-vrata (resolve to ç
give the object of offering); bringing water and purifying it; spreading ç
the deer-skin; preparing cooked rice; driving away the demons and ç
evil spirits.
@S10N = Chapter 2 (34 verses)
Purifying the samidh (faggots) and ku·a grass; lighting the fire; ç
keeping the implements in their respective places; prayer for the ç
protection of the sacrifice; putting the samidhs into the fire; keep ç
away a part of the offering for the demons; mantras for getting offspring.
@S10N = Chapter 3 (63 verses)
Agny<193>dh<193>na  (producing  the  fire); Agnihotra; eulogy of the ç
cow; the S<193>vitr<200>mantra; worship of the other fires like the ç
<193>havan<200>ya; the d<200>k<218><193> (taking the vows) of the ç
sacrificer; worship of Rudra, the three-eyed God.
@S10N = Chapter 4 (37 verses)
Somay<193>ga and some of its details.
@S10N = Chapter 5 (43 verses)
Details of the preparation for the Somay<193>ga  are  continued  here.  They ç
include preparation of soma juice and placing of the appropriate vessels.
@S10N = Chapter 6 (37 verses)
Erecting the y<220>pastambha (sacrificial post of wood); tying the ç
animal to it; bali (immolation and sacrifice); mantras for sending ç
it to heaven.
@S10N = Chapter 7 (48 verses)
Filling the soma juice in various cups meant for the various deities ç
like Indra, V<193>yu, Mitra, Varu<207>a and others.
@S10N = Chapter 8 (63 verses)
Continuation of the previous topics; some Soma sacrifices like <186>o<195>a·in, ç
Dv<193>da·in and Gav<193>mayana.
@S10N = Chapter 9 (40 verses)
V<193>japeya and R<193>jas<220>ya, two well-known and popular sacrifices ç
of those days, are described here.
@S10N = Chapter 10 (34 verses)
Description of the R<193>jas<220>yay<193>ga is continued here.
@S10N = Chapter 11 (83 verses)
A detailed description of Agnicayana (the rite of piling the fire-altar ç
for Soma sacrifices in 5 layers with bricks) is started from this ç
chapter right up to he 18th chapter.
@S10N = Chapter 12 (117 verses)
Vi<218><207>ukrama (taking 4 steps with appropriate mantras), Va<207><200>v<193>hana ç
rite (coming and going of fire kept in a vessel on a cart), purification ç
of the place, bringing the bricks and so on†these are the topics of ç
this chapter.
@S10N = Chapters 13 to 15 (153 verses)
They describe in detail the building up the altar with 10,008 bricks ç
in four layers, in the form of a bird with its wings stretched.
@S10N = Chapter 16 (66 verses)
The  entire  chapter  contains  the famous Rudr<193>dhy<193>ya. ç
It is used in the <185>atarudr<200>ya homa. (It appears in the Taittir<200>ya ç
Sa<221>hit<193> [4.5] also.)
@S10N = Chapter 17 (99 verses)
Ascending  the  vedi  (the  altar), inviting the Fire-god, offering ç
madhuparka (See <MS>MADHUPARKA.<D>), praising Agni and Indra, pouring ç
of milk and a few more rites are described here.
@S10N = Chapter 18 (77 verses)
This contains the mantras used in vasordh<193>r<193> (`flow of wealth'), ç
an oblation of ghee poured in a continuous stream into the fire on ç
the altar.
@S10N = Chapter 19 (95 verses)
The topics dealt with are: the Sautr<193>ma<207>i sacrifice; offering ç
milk to the deities†the A·vins, Indra and Sarasvat<200>; offering  wine,  after  purifying  with ç
mantras, into the dak<218>i<207><193>gni; praising the pit<216>s (manes) ç
like the Agni<218>v<193>ttas; story of Indra being rejuvenated by ç
the A·vins.
@S10N = Chapter 20 (90 verses)
The subjects of this chapter are: mantra for one's welfare: avabh<216>tha ç
(final bath) of the sacrificer; mantra for destruction of sins; giving ç
sacrificial food to Indra; chanting of the °pr<200>s<220>ktas (See ç
<MS>°PR®.<D>); inviting Indra; hymns to the A·vins, Sarasvat<200> ç
and Agni.
@S10N = Chapter 21 (60 verses)
This contains the following topics: hymns to Varu<207>a and Agni; ç
worship of Aditi the mother of gods; oblations to Mitr<193>-Varu<207>a; ç
chanting of Indras<220>kta; conclusion of the Sautr<193>ma<207>i ç
sacrifice.
@S10N = Chapter 22 (34 verses)
@EMERGENCY = The topic of the A·vamedha sacrifice is begun here and ç
continues with the details through Chapters 23 (65 verses), 24 (40 ç
verses) and 25 (47 verses).
@S10N = Chapters 26 (26 verses); 27 (45 verses);<R>ç
28 (46 verses) and 29 (60 verses)
@EMERGENCY = Various minor sacrifices, conclusion of A·vamedha sacrifice, ç
hymn to the horse and the Sun-god identifying the two as one, eulogy ç
of the weapons of war†these are the topics described here.
@S10N = Chapters 30 (22 verses) and 31 (22 verses)
@EMERGENCY = The sacrifice called Puru<218>amedha (human sacrifice) ç
is described here with 184 varieties of living beings as the offering! ç
Scholars however describe it as only symbolical.
@S10N = Chapters 32 (16 verses) and 33 (97 verses)
@EMERGENCY = These deal with the sacrifice called Sarvamedha. Along ç
with the praise of the sacrificer there is a prayer for granting knowledge, ç
wisdom and wealth. There are several mantras and yajus (prose passages) ç
in praise of several deities.
@SPACE1 = 
@S10N = Chapter 34 (58 verses)
The first six mantras are known as the <185>ivasa<209>kalpopani<218>ad. ç
This is followed by some details of a few sacrifices and hymns of ç
praise of the deities Bhaga, P<220><218>an and Brahma<207>aspati.
@SPACE1 = 
@S10N = Chapter 35 (22 verses)
Pit<216>medha mantras are the chief content here.
(See <MS>PIT<184>MEDHA<D> for details.)
@SPACE1 = 
@S10N = Chapters 36 to 39 (86 verses)
These contain the mantras connected with the Pravargya rite. (See ç
<MS>PRAVARGYA.<D>)
@SPACE1 = 
@S10N = Chapter 40 (18 verses)
This is the famous ®·<193>v<193>sya Upani<218>ad
Some important aspects of the teaching of the Sa<221>hit<193> are:
Meticulous performance of the Vedic sacrifices was considered the ç
highest puru<218><193>rtha. Even the gods got special powers by performing ç
sacrifices. Mantras are very powerful, if chanted correctly and will ç
harm if chanted wrongly, the power being dependent on the correctness ç
of chanting.
See <MS>®<185>°V°SYA UPANI<186>AD.
@SPACE = 
@NT = <185>ukra
@N1 = (`the bright one')
@SPACE = 
<185>ukra is one of the Nine Planets†the planet Venus. He is an auspicious ç
deity very much interested in making people happy. He follows a course ç
alternating in front of and behind S<220>rya the Sun. Hepossesses ç
a big chariot drawn by eight horses.
In the sky he appears as the brightest planet.
See also <MS>NAVAGRAHAS.<D>
@NT = <185>ukr<193>c<193>rya
B<216>haspati and <185>ukr<193>c<193>rya (also known as U·anas) are ç
the two most colourful personalities met with in the pur<193><207>as. ç
Whereas B<216>haspati was the guru (teacher) of the devas (gods), ç
<185>ukr<193>c<193>rya was the guru of the d<193>navas (demons).
He was the son of the sage Bh<216>gu and Pulom<193>. The great sage ç
Cyavana was his elder brother. By pleasing <185>iva through severe ç
austerities, he had obtained the sa<210>j<200>vin<200>-vidy<193>, ç
the science of reviving the dead. He had three wives: <185>ataparv<193>, ç
<188>rjasvat<200> and Jayant<200>. Devay<193><207><200> was his daughter ç
born in <188>rjasvat<200>.
He lost one eye during V<193>mana's visit to the king Bali.
<185>a<207><195>a and Amarka were his sons who became the teachers ç
of the demons later.
See also <MS>B<184>HASPATI.<D>
@NT = <185>ukran<200>tis<193>ra
This is an abridged edition of an earlier, much bigger, work. The ç
subject matter is both political and non-political. It has four adhy<193>yas ç
or chapters. The last has seven prakara<207>as or subsections.
It may be assigned to the period circa <MS>A.<|>D.<D> 1800.
The contents may be stated briefly as follows:
The duties and functions of princes, including that of the crown-prince ç
and some dignitaries; general rules of morality to be observed by ç
the king and his associates; characteristics of a king's friends or ç
allies; on the royal treasure; arts and sciences; some customs and ç
institutions; duties and functions of the king; forts and armed forces; ç
council of ministers; trade and commerce; public finance; jurisprudence; ç
international law.
The non-political subjects dealt with include architecture, sculpture, ç
painting, manners and morals, fine-arts and literature.
There is a voluminous work called <185>ukran<200>ti in five chapters, ç
which has been printed in <MS>A.<|>D.<D> 1987.
@NT = ·ukriya
<185>ukriya is one of the four Vedavratas, preparatory disciplines ç
undertaken before the study of the four Vedas.
It should be observed for 3 days or 12 days or even one year, as directed ç
by the Vedic teacher. After this, the study of the main parts of the ç
<184>gveda is begun.
Upanayana has to be performed again before beginning this vrata.
See also <MS>VEDAVRATAS.<D>
@NT = s<220>k<218>madhy<193>na
@N1 = (`subtle contemplation')
@SPACE = 
When the Ku<207>dali<207>i is awakened, and joins the j<200>v<193>tman ç
(the soul), it leaves the body through astral light (through the portals ç
of the eyes) and the yogi is able to see his own subtle body (li<209>ga·ar<200>ra).
The  Ghera<207><195>a  Sa<221>hit<193>  (6.18-21) describes this ç
process.
@NT = s<220>k<218>makriy<193>
@N1 = (`the subtle process)
It is the fourth step in the practice of Layayoga. (See <MS>LAYAYOGA.<D>)
It consists in withdrawing the mind from  the  external  sense-objects  and ç
concentrating on the light between the eyebrows. This is also called ç
jyotirdhy<193>na.
@NT = s<220>k<218>ma·ar<200>ra
@N1 = (`subtle body')
See <MS>LI<177>GA<185>AR®RA.
@NT = s<220>kta
@N1 = (`well-said')
The s<220>kta is a hymn of the <184>gveda comprising several <216>ks ç
(verses). Some of the famous s<220>ktas are: Puru<218>as<220>kta, ç
Vi<218><207>us<220>kta, <185>r<200>s<220>kta, N<193>sad<200>yas<220>kta, ç
and so on.
See also <MS><184>GVEDA.<D>
@NT = s<220>ktav<193>ka
@N1 = (`speech of adoration')
This word means the deity Agni as also the formula repeated by the ç
hot<216> in the Dar·ap<220>r<207>am<193>sa sacrifice.
It is chanted by the hot<216> priest at a particular stage in the ç
sacrifice when the adhvaryu priest and then the <193>gn<200>dhra request ç
him.
The contents of this may be stated briefly as follows:
Praise of heaven and earth; an appeal to Agni (the sacrificial fire) ç
for one's elevation; various attributes of heaven and earth; acceptance ç
of the sacrificial offerings by various deities; blessings on the ç
sacrificer; prayer for the attainment of the fruits of sacrifice.
See also <MS>VEDIC SACRIFICES.
@SPACE1 = 
@NT = Sulabh<193>
@SPACE1 = 
Even in the ancient days, women had the freedom to take to monastic ç
life. This is illustrated by the story of Sulabh<193> as narrated ç
by Bh<200><218>ma to Yudhi<218><219>hira (Mah<193>bh<193>rata, <185><193>ntiparva ç
Ch. 320).
Sulabh<193> was the daughter of the king Pradh<193>na. She had taken ç
to monastic life and was moving about at will after attaining spiritual ç
illumination. Once she heard that the king Dharmadhvaja Janaka of ç
Mithil<193> was a knower of Brahman. She went to him just out of curiosity ç
to test him and entered into his mind through her mind. A long conversation ç
ensued between them about spiritual and philosophic topics. This has ç
been described in detail by the Mah<193>bh<193>rata as mentioned ç
above.
@SPACE1 = 
@NT = <185><220>lagava
@SPACE1 = 
It is a very ancient sacrifice performed to please Rudra/<185>iva ç
(who was called <185><220>lin, the wielder of ·<220>la or the spear ç
or the trident) when cattle were stricken with pests or diseases.
It could be performed during the bright half of a month and on an ç
auspicious nak<218>atra.
Though an ox used to be sacrificed in the most ancient period, it ç
was substituted by a goat or even cooked food in the later days due ç
to the repugnance of the people against it. The deity was called ®·<193>na ç
(same as <185>iva).
The rite soon went out of vogue.
@NT = <185><220>lap<193><207>i
@N1 = (<MS>A.<|>D. <D>1375-1445)
<185><220>lap<193><207>i is one of the three important writers  on  the  dharma·<193>stras  from ç
Bengal (See <MS>J®M<188>TAV°HANA.<D>). He wrote several small treatises ç
on various topics of thedharma·<193>stras. Twelve of his tracts,ending ç
with the word `viveka' are well-known. Some of them are: Dattaka-viveka, ç
Dol<193>y<193>tr<193>viveka, Durgotsava-viveka, Ek<193>da·<200>viveka, ç
Prati<218><219>h<193>viveka, Pr<193>ya·cittaviveka, <185>r<193>ddhaviveka ç
and <185>uddhiviveka.
The  <185>r<193>ddhaviveka  is  the  most famous of these and has ç
been printed. The Pr<193>ya·cittaviveka is an extensive workand ç
deals with various kinds of pr<193>ya·cittas or expiations for sins.
His D<200>pakalik<193> is a commentary on the Y<193>j<210>avalkyasm<216>ti ç
and is regarded as his earliest work.
<185><220>lap<193><207>i  has  been  respectfully referred to by Raghunandana ç
(<MS>A.<|>D.<D> 1510-1580) another famous author of dharma-·<193>stras ç
from Bengal.
@NT = <185>ulbas<220>tras
The Ved<193><209>gas are the subsidiary treatises that help us in ç
understanding the Vedas more clearly because the latter are couched ç
in archaic and even symbolic language.
The Kalpas<220>tras form the last part of the Ved<193><209>gas. They ç
are again divided into four streams, the last of which is the <185>ulbas<220>tras ç
(also spelt as <185>ulvas<220>tras).
<185>ulba means the thread used for measurement.
The  <185>ulbas<220>tras  deal  with  the construction of yaj<210>avedis ç
(platforms forthe performance of Vedic sacrifices). They reveal an ç
astonishing knowledge of geometrical sciences.
Seven <185>ulbas<220>tras are now available. They are closely related ç
to the <185>rauta-s<220>tras, the first of the four branches of the ç
Kalpas<220>tras.
@SPACE = 
They are:
°pastamba <185>ulbas<220>tras
@SPACE1 = 
Baudh<193>yana <185>ulbas<220>tras
@SPACE1 = 
K<193>ty<193>yana <185>ulbas<220>tras
@SPACE1 = 
Maitr<193>ya<207>a <185>ulbas<220>tras
@SPACE1 = 
M<193>nava <185>ulbas<220>tras
@SPACE1 = 
V<193>dh<220>la <185>ulbas<220>tras
@SPACE1 = 
Var<193>ha <185>ulbas<220>tras
@SPACE1 = 
See also <MS>KALPAS<188>TRAS.<D>
@NT = Sumantra
@N1 = (`one [who gives] good advice')
Sumantra was a minister in the cabinet of the King Da·aratha. He was ç
also an expert charioteer. He was highly respected for his age and ç
wisdom.
It was he who drove the royal chariot on several important occasions ç
like bringing the sage <184><218>ya·<216><209>ga for the sacrifice ç
Putrak<193>me<218><219>i, sending R<193>ma to the forest and so on. ç
He too had gone to the forest with Bharata, who tried to bring back ç
R<193>ma.
Some more persons by the same name are met with in the Mah<193>bh<193>rata: ç
a kingof the country of Sauv<200>ra, a sage (descendent of Bh<216>gu), ç
the charioteer of Abhimanyu and a son of Drupada.
@NT = Sumantu
The sage Vedavy<193>sa had four chief disciples to whom he taught ç
the four Vedas. Sumantu was the last of these and received the Atharvaveda ç
from him.
See also <MS>JAIMINI<D>, <MS>PAILA<D> and <MS>VY°SA.<D>
@NT = Sumedhas
@N1 = (`one endowed with pure<R>ç
intelligence')
See <MS>DEV®M°H°TMYA.<D>
@NT = Sumitr<193>
Sumitr<193> was the daughter of <185><220>ra, the king of Magadha. ç
She was the second wife of Da·aratha.
See <MS>R°M°YAØA<D> for more details.
@NT = <185>un<193>s<200>r<200>ya
@N1 = (`guide of plough')
This is the last of the four Vedic sacrifices grouped under the c<193>turm<193>syas. ç
It is referred to even in the <184>gveda (4.57.5 and 8).
The word <185>un<193>-s<200>ra may refer to any of the following deities: ç
V<193>yu and S<220>rya; S<220>rya and Indra; Indra and two forms of ç
Agni.
Offering havis (special oblations) in this sacrifice is considered ç
as very important. It consists of puro<195><193>·a (rice) cakes in ç
twelve mud plates as also milk.
This sacrifice can be performed at any time during the year. There ç
is no uttaravedi (high alter erected in the east). The fire is not ç
produced by ara<207>is.
Attaining wealth and success in life are the twin purposes of performing ç
this sacrifice.
See also <MS>C°TURM°SYA.<D>
@NT = <185>una··epha
<185>una··epha is a classic example to show that poverty and famine ç
can drive even pious parents to sell their children.
He was the second son of Aj<200>garta, a sage of the Bh<216>gu race. ç
During a severe famine, unable to sustain his family, he sold <185>una··epha ç
to the king Hari·candra who was in search of a boy to be offered in ç
a sacrifice he was performing. However, the great sage Vi·v<193>mitra ç
managed to save his life and adopted him as his own son, giving a ç
new name, Devar<193>ta.
Aj<200>garta was reborn as a pi·<193>ca (goblin) because of his sin. ç
Devar<193>ta however, redeemed him by the power of his austerities.
<185>una··epha is the <216><218>i (the sage, the seer) of some <184>gvedic ç
mantras (1.24.1-15). The Aitareya Br<193>hma<207>a (Chapter 33) ç
describes his story in great detail.
The story of <185>una··epha appears in the R<193>m<193>ya<207>a ç
also (B<193>laka<207><195>a Chapters 61, 62). There, it is the king ç
Ambar<200><218>a and not Hair·candra, who purchased the boy. The sage ç
Vi·v<193>mitra who was the boy's maternal uncle, taught him some secret ç
mantras to please the god Varu<207>a, by whose grace he was ultimately ç
saved.
@NT = Sundarak<193><207><195>a
This is the fifth book of V<193>lm<200>ki's R<193>m<193>ya<207>a.
See <MS>R°M°YAØA<D> for details.
@NT = Sundaram<220>rti
Out of the sixty-three N<193>yanm<193>rs (or N<193>yan<193>rs), the ç
great <185>aiva saints of Tamil Nadu, four are considered most important. ç
Sundaram<220>rti is one of them. He lived in the eighth century <MS>A.<|>D.<D>
He was the son of <185>a<195>aiyan<193>r and I·aij<210><193>niy<193>r. ç
He was born in a small town, Tirun<193>val<220>r. He was given the ç
name Nambi °r<220>ran. He however came to be known as Sundaram<220>rti.
In his young age, he was adopted by Narasi<209>ga Munaiyaraiyar, the ç
local king. Under his loving care, the boy grew into a fine young ç
man, well-educated and cultured.
Just at the time of his marriage, Lord <185>iva came, disguised as ç
an old br<193>hma<207>a and claimed that this youth was his slave ç
as per the agreement between him and the grandfather of theyouth. ç
The marriage was abandoned. Sundaram<220>rti got the vision of <185>iva ç
himself in that br<193>hma<207>a and became his ardent devotee. He ç
sang a wonderfully poetic and melodious song inspired by the Lord ç
Himself.
He then started on a long pilgrimage of all the sacred places connected ç
with <185>iva. He was blessed with many divine visions and spiritual ç
experiences and also performed several miracles to help the needy ç
persons.
He had two wives†Paravaiy<193>r and Sa<209>giliy<193>r (supposed to ç
be divine damsels born on earth)†both of whom were also great devotees ç
of <185>iva and loyal to their husband.
He is said to have departed for the world of <185>iva in the <185>iva ç
temple at a place called Tiruva<210>jaikka<202>am.
Sundaram<220>rti's compositions are part of the Tev<193>ram (part ç
of the seven books of collection known as Tirumurai) and are sung ç
in <185>iva temples even today in Tamil Nadu. Only a hundred songs ç
are available now though he is said to have composed thousands.
@SPACE = 
@NT = Supar<207>a
@N1 = (`one with beautiful wings')
See <MS>GARU£A.<D>
@NT = Surabhi
See <MS>K°MADHENU.
@SPACE = 
@NT = sur<193>p<193>na
@N1 = (`consuming intoxicating <R>ç
drinks')
@SPACE = 
Hindu scriptures have always condemned sur<193>p<193>na or madyap<193>na, ç
consuming of intoxicating drinks as mah<193>p<193>taka or a grave ç
sin (vide Chandogya Upani<218>ad 5.10.9; Manusm<216>ti 11.54; ç
°pastamba Dharmas<220>tras 1.7.21.8).
Sur<193> is the intoxicating drink prepared out of flour. (It should ç
not be confused with the soma juice). Other drinks like the ones prepared ç
out of molasses or madh<220>ka flowers were permitted to be taken ç
by the k<218>attriyas and vai·yas. But, the br<193>hma<207>as were ç
strictly forbidden from consuming all types of intoxicants.
It is interesting to note that sur<193> was one of the oblations made ç
in the Sautr<193>ma<207>i sacrifice.
@SPACE = 
@NT = suras
@N1 = (`gods')
@SPACE = 
The words sura and asura are commonly used in the Vedic and paur<193><207>ic ç
literature. They stand for the gods and the antigods or demons.
Sura is one of the 25 names of the gods.
The word asura is sometimes defined as one who revels in his senses ç
(sve<218>u asu<218>u rama<207><193>t). That means, the persons given ç
to reckless sense-enjoyments. As opposed to them are the suras, the ç
divine beings, beings of light and wisdom.
See <MS>ASURAS<D> and <MS>DEVAS<D>.
@NT = <185><220>rasena
<185><220>rasena was the name of a janapada or a country, one of the ç
sixteen well-known janapadas that existed during the time of Mah<193>bh<193>rata. ç
It was probably established by the king <185><220>ra, the father of ç
Vasudeva and Kunt<200>. Its capital was Mathur<193>.
@NT = Suratha
See <MS>DEV®M°H°TMYA.<D>
@NT = S<220>rd<193>s
@N1 = (<MS>A.<|>D.<D> 1471-1584)
One of the greatest saints and poets of Hindi devotional literature, ç
S<220>rd<193>s has etched for himself an indelible place in the cult ç
of K<216><218><207>abhakti or devotion to K<216><218><207>a. Born ç
blind in a br<193>hma<207>a family of the village of Sihi near Delhi, ç
he was, yet, endowed with extraordinary powers of perception. It was ç
perhaps this power that made him, in his later life, have visions ç
of K<216><218><207>a in his heart. He also had a prodigious memory ç
that helped him to memorise the whole of the Bh<193>gavata- pur<193><207>a ç
and several devotional texts.
Neglected by his parents and even ill-treated by them sometimes, he ç
left his home and started living on the bank of the river Yamun<193> ç
at a place called Gaugh<193><219>.
The turning point in his life came when he received initiation from ç
Vallabh<193>-c<193>rya (<MS>A.<|>D.<D> 1473-1531), the great teacher ç
of pu<218><219>im<193>rga (See <MS>PU<186><187>IM°RGA.<D>). After ç
this he is said to have lived in Govardhan near Mathur<193> (in Uttar ç
Pradesh).
Vallabha inspired him to devote himself to the portrayal of K<216><218><207>a's ç
playful moods as also the incidents depicted in the folklore on K<216><218><207>a.
S<220>rd<193>s is said to have composed 100,000 songs of which only ç
8000 are available today. They have been brought out in a book form ç
known as S<220>rs<193>gar (ocean of S<220>rd<193>s songs). The songs ç
are written in Brajbh<193><218><193>, a Hindi dialect of the Mathur<193> ç
region. They are highly musical and extremely popular. The themes ç
are always centred round K<216><218><207>a whether pertaining to his ç
childish pranks or the R<193>sal<200>l<193>, his famous dance with ç
the gop<200>s of V<216>nd<193>ban.
@NT = Sure·vara
Sure·vara was one of the four chief disciples of <185>a<209>kara (<MS>A.<|>D.<D> ç
788-820). Not much is known about him.
According to the traditional bio-graphies of <185>a<209>kara†like ç
the <185>a<209>kara-digvijaya†he was Ma<207><195>ana Mi·ra, a great ç
scholar  of  M<200>m<193><221>s<193>,  whom  <185>a<209>kara defeated ç
in a disputation. As per the earlier agreement, he accepted sa<221>ny<193>sa ç
from <185>a<209>kara and became his disciple, assuming  the  new  name  Sure·vara. ç
Modern scholars however do not subscribe to this view. According to ç
them he was an entirely different person, known earlier as Vi·var<220>pa.
Sure·vara's  works  are  V<193>rttikas (poetical expositions) on ç
<185>a<209>kara's bh<193><218>yas (commentaries) on the B<216>had<193>ra<207>yaka ç
and the Taittir<200>ya Upani<218>ads; M<193>nasoll<193>sa a(v<193>rttika) ç
on the Dak<218>i<207><193>m<220>rtistotra; abh<193><218>ya on <185>a<209>kara's ç
Pa<210>c<200>kara<207>a; Nai<218>karmyasiddhi (an independent ç
treatise on Advaita Ved<193>nta).
He was the first pontiff of the <185><193>rad<193>p<200><219>ha of ç
<185><216><209>ger<200>, one of the four monasteries established by ç
<185>a<209>kara.
According to another version, he was the first pontiff of the K<193><210>c<200> ç
K<193>mako<219>i-p<200><219>ham (after <185>a<209>kara), a fifth monastery ç
supposed to have been established by <185>a<209>kara himself for his ç
own stay. The controversy regarding this point is still very much ç
alive. It is however true that this Ma<219>ha also has produced many ç
great <193>c<193>ryas.
@NT = <185><220>rpa<207>akh<193>
@N1 = (`one whose nails resembled a winnowing basket')
<185><220>rpa<207>akh<193> is one of the two iniquitous ladies†the ç
other being Manthar<193>† but for whom the classic, the R<193>m<193>ya<207>a, ç
would never have been composed, thereby depriving <|>millions <|>of ç
<|>people <|>for<|> millenniums, of the great inspiration for life!
She was the daughter of the sage Vi·ravas and Kaikas<200>. She was ç
younger than R<193>va<207>a and Kumbhakar<207>a but older than Vibh<200><218>a<207>a. ç
She had been married to Vidyujjihva who was killed by R<193>va<207>a ç
since he had joined the enemy camp. As a result of her pleadings, ç
R<193>va<207>a made arrangements for her stay in the Da<207><195>aka ç
forest with Khara and D<220><218>ana, with their large army to protect ç
her.
Infatuated with R<193>m<193>'s beauty, she pressed him to marry her, ç
abandoning S<200>t<193>. When she tried to kill S<200>t<193>, R<193>ma ç
got her punished through Lak<218>ma<207>a who cut off her nose and ç
ears.
Her complaints to Khara and R<193>va<207>a resulted in the decimation ç
of Khara and his army at the hands of R<193>ma, and the abduction ç
of S<200>t<193> by R<193>va<207>a.
@NT = S<220>rya
@N1 = (`Sun-god')
S<220>rya or the sun, often identified with °ditya, Savit<216> and ç
P<220><218>an, is an important Vedic deity. He is extremely brilliant  and  rides  in  an  exquisitely ç
beautiful chariot drawn by seven horses. He is compared to a bird ç
that flies in the sky and is described as the jewel of the sky. He ç
gives light, produces day and night, gives power and strength to the ç
living beings, makes them active, and destroys their laziness and ç
disease.
Savit<216> is the aspect of the sun before sunrise. He is golden all ç
over. He establishes people in their respective places. He gives life ç
and energy and guides people in the right path.
The famous G<193>yatr<200>mantra is dedicated to this Savit<216>.
The nourishing and life-supporting aspect of the sun is personified ç
and praised as P<220><218>an. He is exceedingly beautiful. He destroys ç
the evil ones with the discus he wears. He looks upon all with an ç
equal eye. He is extremely generous and ever ready to protect.
The story of S<220>rya appears in many of the pur<193><207>as as also ç
the two epics.
He was the son of Ka·yapa and Aditi. Sa<221>j<210><193>dev<200>, the ç
daughter of Tva<218><219><216>, was
