@NID = five sense-organs. Thus, the scripture being the sole authority ç
in such matters, and since the Hindu scriptures declare as also highly ç
eulogise the sanctity of the ·<193>lagr<193>ma stones, they are being ç
greatly revered even today.
@SPACE = 
@NT = <185><193>lihotra
@SPACE1 = 
Said to be the son of the well-known sage Kapila, <185><193>lihotra ç
was the author of a standard treatise on a·va·<193>stra (the science ç
of horses). His <193>·rama or hermitage had an ageless tree and a ç
pond of sweet water which could immediately quench all hunger and ç
thirst. They had been created by his tapas or power of austerity.
Vy<193>sa, the author of the great epic Mah<193>bh<193>rata, is ç
said to have lived in his <193>·rama once.
The P<193><207><195>avas, during their twelve-year exile, visited ç
him and were his guests for a few days.
@SPACE = 
@NT = <185><193>liv<193>hana-<185>aka
@SPACE1 = 
In the traditional Hindu calendars (pa<210>c<193><209>gas), generally, ç
reckoning of the eras (called `·aka') starts either with Vikram<193>ditya ç
or <185><193>liv<193>hana, both of whom were supposed to be famous ç
emperors.
Vikram<193>ditya, son of Gardabhilla, was a great emperor ruling at ç
Ujjayin<200> during the period 58-57 <MS>B.<|>C.<D>, (according to ç
the Pr<193>k<216>t work K<193>lak<193>carya-kath<193>naka). However, ç
no historical or literary evidence is available to prove the existence ç
of <185><193>liv<193>hana.
Though the era of Vikram<193>ditya is known as Vikrama-<185>aka or ç
Vikrama-Sa<221>vat, the era of <185><193>liv<193>hana is mostly written ç
as the <185>aka era. It begins from <MS>A.<|>D.<D> 78.
The earliest reference to the <185>aka era is in the Jain work Lokavibh<193>ga ç
of Si<221>has<220>ri, mentioned as <185>aka era 380. The earliest ç
inscription so far discovered is that of C<193>lukya Vallabhe·vara ç
which mentions the <185>aka era 465 (= <MS>A.<|>D.<D> 534).
Almost  all  Sanskrit  works  on astronomy from <MS>A.<|>D.<D> 500 ç
onwards, employ the <185>aka era.
Oriental research scholars sometimes identify the emperor K<193>ni<218>ka ç
of the Ku<218><193><207>a race with <185><193>liv<193>hana.
@SPACE = 
@NT = s<193>lokya
@N1 = (`living in the same world')
@SPACE1 = 
See <MS>MOK<186>A.
@SPACE = 
@NT = <185>alya
@SPACE1 = 
One of the great heroes (atiratha) of Mah<193>bh<193>rata, <185>alya ç
was the son of <184>t<193>yana, the king of Madrade·a. M<193>dr<200>, ç
the second wife of P<193><207><195>u and the mother of Nakula and ç
Sahadeva, was his sister.
He had two sons, Rukm<193><209>gada and Rukmaratha.
Though he wanted to join the P<193><207><195>avas in the Kuruk<218>etra ç
war, the wily Duryodhana managed to get him on to his side. He served ç
as the charioteer ofKar<207>a. After Kar<207>a's death, he was appointed ç
as the commander-in-chief of the Kaurava army. He was killed by Yudhi<218><219>hira ç
in the battle.
@NT = <185>alyaparva
@SPACE1 = 
It is the ninth parva or book of the epic Mah<193>bh<193>rata.
See <MS>MAH°BH°RATA.<D>
@NT = ·ama
@N1 = (`peace')
@SPACE1 = 
Treatises on Ved<193>nta deal with the s<193>dhanas or means of attaining ç
mok<218>a or liberation.
In Advaita Ved<193>nta the preliminary step is known as s<193>dhanacatu<218><219>aya ç
or four means. Out of these four, the third is ·am<193>di<218>a<219>ka ç
or <218>a<219>sampatti or the group of six disciplines beginning with ç
·ama. <185>ama is defined as the internal peace or quietude got by ç
preventing the mind from rushing towards the sense-objects that disturb ç
it.
See <MS>S°DHANACATU<186><187>AYA.
@SPACE = 
@NT = samabha<209>ga
@N1 = (`symmetrical posture')
@SPACE1 = 
See <MS>BHA<177>GA.
@SPACE = 
@NT = sam<193>dh<193>na
@N1 = (`keeping [the mind] well- established [in the <193>tman or ç
God]')
@SPACE1 = 
Advaita Ved<193>nta describes a four-fold s<193>dhana (spiritual discipline) ç
generally called s<193>dhanacatu<218><219>aya. The third step, the ç
·am<193>di<218>a<219>ka (the group of six steps), includes sam<193>dh<193>na ç
as the last item. It is concentration of mind on the object of contemplation.
(See <MS>S°DHANACATU<186><187>AYA.<D>)
This word is also used to indicate a suitable or satisfactory reply ç
given to a doubt or a query or an objection raised in philosophical ç
disputations.
In a more general sense, it means pacification of an aggrieved party.
@SPACE = 
@NT = sam<193>dhi
@N1 = (`state of perfect concentration')
@SPACE1 = 
The Yogas<220>tras of Pata<210>jali (200 <MS>B.C.<D>) deals with ç
the techniques of controlling and concentrating the mind. The work ç
gives eight steps†generally known as a<218><219><193><209>gas (hence ç
the name A<218><219><193><209>gayoga for Pata<210>jali's system)†out ç
of which the last three are dh<193>ra<207><193>, dhy<193>na and sam<193>dhi.
Dh<193>ra<207><193> is the fixing of attention on a definite locus, ç
such as the lotus of the heart, the light in the brain, the tip of ç
the nose or the tongue, or on an external object like the moon or ç
the image of gods and so on.
When dh<193>ra<207><193> ripens so that the flow of the thought-current ç
becomes unbroken, it becomes dhy<193>na. Here the mind hovers round ç
the object of meditation. There is still the consciousness of the ç
trio†the ego-sense, the object of meditation and the process of meditation.
When again dhy<193>na becomes perfect and the mind is so deeply absorbed ç
in the object that it loses itself and has no awareness of itself, ç
the state attained is called sam<193>dhi. In this state, only the ç
object of meditation will be shining in the mind and the yogi is not ç
even aware of the thought process involved in it. Even the ego-sense ç
is completely subjugated.
@SPACE1 = 
In the state of sam<193>dhi, which is an intuitive and superconscious ç
experience, the object of meditation will reveal all its secrets to ç
the yogi. If the yogi can make his own self or ®·vara the object of ç
meditation after learning about them from the S<193><209>khya (an ç
allied philosophical system declaring the knowledge of the Self as ç
the means of liberation), he will get kaivalya (liberation). Pata<210>jali ç
calls these two sam<193>dhis respectively as sampraj<210><193>ta and ç
asampraj<210><193>ta. In the former, the object of meditation is known ç
in its entirety. In the latter nothing outside the Self is known (sampraj<210><193>ta ç
= well-known, asampraj<210><193>ta = not known).
See also <MS>NIRVIKALPA.<D>
Sam<193>dhi is the name of a vai·ya (merchant) who too received the ç
esoteric teaching concerning the greatness of Dev<200>, the Divine ç
Mother, along with the king Suratha, from the sage Sumedhas. He had ç
been driven out of his home by his own greedy wife and children.
When he strayed into the hermitage of the sage, he met the king Suratha. ç
Both of them then approached the sage for consolation. By his teaching ç
Sam<193>dhi was guided towards mukti or liberation.
See <MS>DEV®M°H°TMYA.<D>
@NT = ·am<193>di<218>a<219>ka
@N1 = (`the group of six<R>ç
[disciplines]' starting with ·ama')
This is the third of the four spiritual disciplines listed under s<193>dhanacatu<218><219>aya. ç
It consists of the following six steps: ·ama (tranquillity); dama ç
(self-control); uparati (cessation of external sense-organs from the  pursuit  of  sense-objects);  titik<218><193> ç
(forbearance); ·raddh<193> (faith) and sam<193>-dh<193>na (concentration).
@NT = s<193>maga
@N1 = (`one who sings the s<193>ma')
A s<193>ma (or s<193>man) is any mantra of the <184>gveda set to ç
tune as per the rules given in works like the N<193>rad<200>ya·ik<218><193>. ç
The S<193>maveda is full of such s<193>mas.
A s<193>maga in general, is one who sings the s<193>ma. All the four ç
priests of the S<193>maveda, viz., the udg<193>t<216>, the prastot<216>, ç
the pratihart<216> and the subrahma<207>ya, are s<193>magas, though ç
the udg<193>t<216> is the chief among them.
Chanting of a s<193>ma needs specialised training.
A s<193>maga should have a musical voice and a fine sense of ·ruti ç
or tuning (of his voice to a basic note). He should chant in a medium ç
tone†neither too loud not too low†uttering the words clearly and without ç
tremour. He should know where the words have to be paused and must ç
never make a mistake of the svara (intonation). Those who cannot chant ç
in this way, should never attempt to learn it!
S<193>maga is also one of the names of Vi<218><207>u as given in the ç
Vi<218><207>usaharan<193>ma (number 575). <185>r<200> K<216><218><207>a ç
declares that he is S<193>maveda among the Vedas (Bhagavad-g<200>t<193> ç
10-22). Hence one who sings this Veda†the s<193>maga†has practically ç
identi-fied himself with the Lord in ecstasy.
@SPACE = 
@NT = sam<193>hart<216>
@N1 = (`one who brings revenue')
@SPACE = 
Kau<219>ilya (300 <MS>B.<|>C.<D>) in his monumental work, the Artha·<193>stra, ç
has described in detail, an ideal system of administration of a State.
One of the important officers of the State is the sam<193>hart<216> ç
(the Collector- General). He divides the kingdom into four districts, ç
arranges the villages into three grades and supervises over the collection ç
of various taxes and revenues from forts, rural areas, mines, embankments, ç
forests, herds of cattle and roads for traffic (vide 2.6 and 2.35).
See also <MS>ARTHA<185>°STRA.
@SPACE = 
@NT = s<193>man
@SPACE = 
The word s<193>man refers to the S<193>maveda as also its mantras. ç
(See <MS>S°MAVEDA<D> for details.)
S<193>man is also one of the four up<193>yas or means available to ç
the kings while dealing with others. In general, it means to cement ç
the bonds of friendship with the person who should not be alienated.
This can be done in five ways: by recounting the good turns done by ç
each to the other; by praising the qualities and actions of the other ç
person who is to be won over; declaring the relationship of each other; ç
representing the good that will result in future; declaring `I am ç
yours and I am at your service.' (K<193>mandak<200>ya-n<200>tis<193>ra ç
17.4 and 5).
@SPACE1 = 
@NT = sam<193>na
See <MS>PR°ØA.
@SPACE1 = 
@NT = Samantapa<210>caka
@N1 = (`the place surrounded by five [lakes]')
See <MS>KURUK<186>ETRA.
@SPACE1 = 
@NT = samanu
@N1 = (`with mantra')
`Manu' means a mantra (holy syllable). Works on Ha<219>hayoga describe ç
various processes of pr<193><207><193>y<193>ma for n<193><195><200>·uddhi ç
(purification of the tubular structures through which pr<193><207>ic ç
energy flows). Very often, certain b<200>jamantras (seed-letters) ç
like ya<221>, ra<221> and <219>ha<221>, are associated with the different ç
stages of these pr<193><207><193>y<193>mas. Hence they are called ç
`samanu' (pr<193><207><193>y<193>mas with b<200>jamantras) (vide ç
Ghera<207><195>a Sa<221>hit<193> 5.36-45).
The actual processes have to be learnt personally from expert teachers.
@SPACE1 = 
@NT = s<193>m<193>nya
@N1 = (`that which is the same,'<R>ç
`generality')
This is one of the seven pad<193>rthas or categories recognised by ç
the Vai·e<218>ika-dar·ana.  See  <MS>VAI<185>E<186>IKA-DAR<185>ANA<D>  for ç
details.
In the Ala<209>k<193>ra·<193>stra (the science of figure of speech), ç
s<193>m<193>nya refers to such an element which exists both in the ç
basic object and the object with which it is compared, without any ç
distinction.
@SPACE = 
@NT = s<193>m<193>nyatod<216><218><219>a
@N1-1 = (`seen in a general way')
@SPACE = 
Anum<193>na or inference is an important pram<193><207>a or means ç
of knowledge recognised  by  almost  all  systems  of Indian philosophy. ç
The Ny<193>yadar·ana of Gautama (550 <MS>B.<|>C.<D>) has further categorised ç
anum<193>na into three varieties: p<220>rvavat; ·e<218>avat and s<193>m<193>nyatod<216><218><219>a.
The  p<220>rvavat  (`as  seen  earlier') inference is that in which ç
we infer an unperceived effect from a perceived cause, as in the case ç
of inferring future rain from the appearance of dark heavy clouds ç
in the sky.
In ·e<218>avat (`from the seen [effect] to the unseen [cause]'), the ç
unperceived cause is inferred from a perceived effect, as in the case ç
of inferring of past rain by seeing the swift muddy currents in the ç
river now.
In the s<193>m<193>nyatod<216><218><219>a inference, there is no direct ç
cause and effect relationship (as between fire and smoke). The inference ç
is drawn from the universal experience regarding such an incident. ç
For instance, if there is a change of place, there must have been ç
a movement asknown from our common experience. Similarly when we ç
see the moon in different positions at long intervals, we infer that ç
it moves, though the actual movement itself is not easily or clearly ç
perceivable (vide Ny<193>yas<220>tras 1.1.5).
@NT = sam<193>patti
@N1 = (`attaining identity [with the object of concentration]')
This is a technical term used by Pata<210>jali (200 <MS>B.<|>C.<D>) ç
in his Yogas<220>tras (1.41). Literally, it means attaining identity ç
(<193>patti) totally (sam) with the object of concentration. It refers ç
to the state that the mind attains.
When the citta or the mind loses its v<216>ttis or modifications raised ç
by tamas and rajas through yogic disciplines, and becomes absolutely ç
pure like a colourless crystal, becomes one with the object of concentration, ç
it is said to have attained sam<193>patti. This is like the pure crystal ç
totally reflecting a red hibiscus flower kept near it, as if losing ç
its own identity in the process.
This is practically the same as sam<193>dhi.
@NT = sam<193>roha<207>a
@N1 = (`making [the fire] ascend')
If an <193>hit<193>gni†one who had ceremonially established a Vedic ç
fire†wanted to go on a pilgrimage, he could put out the fire by the ç
site of sam<193>roha<207>a and re-establish it after returning.
In sam<193>roha<207>a, the <193>hit<193>gni had to warm his hands ç
on the g<193>rhapatya fire (with appropriate mantras) causing Agni ç
to enter into his body. Alternatively, it could be done by warming ç
the ara<207>is and another piece of wood which will be the subtle ç
dwelling place for it till he returns.
When the same process is carried out to establish the fire (once established) ç
elsewhere, it is called sam<193>ropa<207>a.
@NT = sam<193>ropa<207>a
See <MS>SAM°ROHAØA.<D>
@NT = sam<193>vartana
@N1 = (`return')
@SPACE = 
@SPACE = 
Sam<193>vartana means returning fromthe house of the teacher to one's ç
own house after duly completing Vedic studies. Since a ceremonial ç
bath was a necessary part of it, it was also known as sn<193>naand ç
<193>plavana (both of which mean bathing).
After this rite, the brahmac<193>ri came to be known as a sn<193>taka ç
(one who has undergone the ceremonial bathing). He was now free to ç
marry a suitable girl and settle down as a g<216>hastha or householder.
For the sam<193>vartana rite, an auspicious day had to be fixed. Permission ç
of the guru (preceptor) had to be sought after offering him suitable ç
dak<218>i<207><193> (gifts).
He should then take the ceremonial bath by taking water from eight ç
vessels (full of water) kept in the eight directions, chanting the ç
prescribed mantras. After this bath, he has to cast off his old outfit ç
completely and put on new clothes more comfortable and suitable for ç
a householder's life. He could also accept ornaments, turban, umbrella, ç
shoes, flower- garlands and so on, all of which had been forbidden ç
till now!
Dressed in his new attire, the sn<193>taka was expected to go to an ç
assembly of the learned and prove his competence as a scholar.
A sn<193>taka commanded great respect and there was a strict code ç
of conduct prescribed for him.
In the modern days, the rite of sam<193>vartana  is  observed  just  before ç
marriage, as a formal ritual shorn of its meaning and seriousness ç
as K<193>·<200>y<193>tr<193>.
See also <MS>SN°TAKA.<D>
@NT = samav<193>ya
@N1 = (`inherence')
@SPACE = 
It is one of the saptapad<193>rthas or seven categories put forward ç
by the Vai·e<218>ika system.
See <MS>VAI<185>E<186>IKA-DAR<185>ANA.
@SPACE = 
@NT = S<193>maveda
@SPACE = 
@SB = Introduction
@SPACE = 
The S<193>maveda or the S<193>maveda sa<221>hit<193> is the third ç
in the traditional list of the four Vedas. It comprises mostly the ç
<184>gvedic mantras (or <216>ks)†1504 to be specific†set to the saptasvara ç
system (the seven basic notes of Indian music), to be sung at appropriate ç
places in a sacrifice. It is the udg<193>t<216> (the third of the ç
four major priests) along with his three assistants (prastot<216>, ç
pratihart<216> and subrah-ma<207>ya) that does this. The total number ç
of <216>ks in this Veda as per one calculation is 1875.
It should be noted that this Veda has been eulogised highly in the ç
other Vedas also (vide <184>gveda 1.107.2; 2.43.2; 5.44.14. Atharvaveda ç
2.7.24; 7.54.1; 10.7.20). K<216><218><207>a while describing his special ç
aspects, says in the Bhagavadg<200>t<193> (10.22) that he is S<193>maveda ç
among the Vedas.
@SPACE = 
@SB = Commentators of the S<193>maveda
@SPACE = 
The Vedas are difficult to comprehend not only because of their archaic ç
language but also because of their close association with the system ç
of yaj<210>a or sacrifice. Hence, the help of bh<193><218>yas or commentaries ç
by those scholars, who also have an intimate knowledge of the Vedic ç
tradi-tions, is invaluable.
The following are the commentators on  the  S<193>maveda  whose  works  are ç
available even now, though some of these are still in the form of ç
manuscripts:
@SPACE = 
@Z_TBL_BEG = COLUMNS(2), DIMENSION(IN), COLWIDTHS(1.3533,E1), ABOVE(.0417), ç
BELOW(.1667), VGUTTER(.0278), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT
M<193>dhava Pa<207><195>ita, (<MS>A.<|>D.<D> 630)
Gu<207>avi<218><207>u, (12th century <MS>A.<|>D.<D>)
Bharatasv<193>min, (<MS>A.<|>D.<D> 1300)
Mah<193>sv<193>min, (13th century <MS>A.<|>D.<D>)
S<193>ya<207>a, (<MS>A.<|>D.<D> 1315-1387)
<185>obh<193>kara Bha<219><219>a, (circa <MS>A.<|>D.<D> 1400)
S<220>ryadaivaj<210>a, (circa <MS>A.<|>D.<D> 1502)
@Z_TBL_END = 
@SB = Meaning of S<193>ma
@SPACE = 
The etymological meaning of the word s<193>ma is `that which destroys ç
sorrow by its sweetness; a song'.
The B<216>had<193>ra<207>yaka Upani<218>ad defines the s<193>ma ç
as a <216>k (<184>gvedic mantra) set to various tunes of music (vide ç
1.3.25; 1.3.22).
Thus the s<193>mas are those mantras of the <184>gveda which had ç
been set to the tunes as prescribed by the special treatises like ç
the N<193>rad<200>ya·<200>k<218><193>.
However, the same <216>k can be sung in different tunes thus producing ç
different s<193>mas. The number of such s<193>mas can vary from one ç
to eighteen!
According to one calculation there are 1875 <216>ks and 2639 s<193>mas ç
in the S<193>maveda texts available now.
@SPACE = 
@SB = <185><193>kh<193>s of S<193>maveda
@SPACE = 
As in the case of the other three Vedas, the S<193>maveda also has ç
several <185><193>kh<193>s (branches or recensions). Though some traditional ç
works like the Cara<207>a-vy<220>ha (an appendix to the Atharvaveda) ç
mention that there are a thousand ·<193>kh<193>s in the S<193>maveda, ç
only thirteen names have been discovered so far. They are the names ç
of the teachers who were responsible for re-editing the text and starting ç
their own ·<193>kh<193>s.
Nevertheless, only three such ·<193>kh<193>s are extant now. They ç
are: Jaimin<200>ya·<193>kh<193>, Kauthuma·<193>kh<193> and R<193><207><193>yan<200>ya·<193>kh<193>. ç
The last two have many similarities like equal number of mantras. ç
The first one has 182 mantras less than the other two.
@SB = Internal Divisions
The S<193>maveda has two sections called P<220>rv<193>rcik<193> ç
and Uttr<193>rcik<193>. (Arcik<193> means a group of <216>ks.) The ç
P<220>rv<193>rcik<193> has several prap<193><219>hakas or chapters ç
containing a few da·atis (decads, though sometimes the number of <216>ks ç
is either more or less than ten). The da·atis, again, comprise of ç
<216>ks.
The Uttar<193>rcik<193> has nine prap<193>-<219>hakas. These are ç
divided into kha<207><195>as, each of which consists of a large number ç
of <216>ks.
In the P<220>rv<193>rcik<193>, the mantras taken from the <184>gveda ç
have been regrouped according to the devat<193> or the deity praised. ç
The first prap<193><219>haka contains mantras connected with Agni ç
and hence called °gneyak<193><207>da. Prap<193><219>hakas 2 to 4 ç
are known as Aindrak<193><207><195>a since they are devoted to Indra, ç
the king of gods. The fifth prap<193><219>haka contains mantras dedicated ç
to the god Soma-Pavam<193>na and hence called Pavam<193>naparva. ç
Most of these mantras have been taken from the ninth ma<207><195>ala ç
of the <184>gveda which itself is entirely devoted to that deity.
The <216>ks of these five prap<193><219>hakas are known as veyag<193>na ç
or gr<193>mag<193>na (or gr<193>me geya), because they are to be sung ç
in gr<193>mas or villages and towns. The other terms by which they ç
are known are: chand<193>rcik<193>, prak<216>ti, prak<216>tisa<221>hit<193>, ç
and <216>k.
These mantras are used more in brahmayaj<210>a (reciting and teaching ç
the Vedas), up<193>karma (See <MS>UP°KARMA.<D>) and certain other ç
rituals. Their use in Vedic sacrifices is limited.
The sixth prap<193><219>haka is called Ara<207>yak<193><207><195>a ç
or °ra<207>yakaparva. These mantras have to be chanted in an ara<207>ya ç
or forest, since they are conducive to contemplation.
The ten <216>ks appearing at the end of this section are known as ç
Mah<193>n<193>mn<200>. They are like an appendix to the P<220>rv<193>r-cik<193>. ç
Known also as <185>akvarya<199>†their deity is Indra†they are generally ç
used on the 5th day of the sacrifice.
Since these mantras are addressed to Indra as God, the mah<193>n (= ç
supreme or great), they have come to be known as Mah<193>n<193>mn<200>.
In the Uttar<193>rcik<193>, there are nine prap<193><219>hakas. ç
Each prap<193><219>haka has several kha<207><195>as (like the da·atis ç
of the P<220>rv<193>r-cik<193>) which contain the <216>ks.
The chanting or singing of these <216>ks is divided into two groups: ç
<220>hag<193>na and<220>hyag<193>na or rahasyag<193>na. The basic ç
models for these two are, respectively, the gr<193>mag<193>na and ç
the ara<207>yag<193>na.
@SPACE1 = 
There is a repetition of 267 mantras of the P<220>rv<193>rcik<193> ç
in this. The mantras of this section are used in stoma (a kind of ç
repetitive prayer) in yaj<210>as or sacrifices. (See also <MS>STOMA.<D>)
The following tables give an idea of the two arcik<193>s as extant ç
now:
@Z_TBL_BEG = COLUMNS(4), DIMENSION(IN), COLWIDTHS(.8725,E1,.5150,.3058), ç
HGUTTER(.0139), VGUTTER(.0153), VGRID(Z_SINGLE), KEEP(OFF), L1(R11C0..R11C4), ç
L1(R12C0..R12C4), L1(R2C0..R2C4), L1(R1C0..R1C4), L0(R11C1..R12C1)
@Z_TBL_BODY = TC1X, TABLE TEXT, TABLE TEXT, TABLE TEXT
<P9.5B>P<220>rv<193>rcik<193><P255MI>, +, +, +
@Z_TBL_BODY = TC2, TC2, TC2, TC2
Prap<193><219>haka, K<193><207><195>a, Da·ati, <184>ks
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, CEN, TABLE TEXT
<+><+><+><+><+>1, <|>°gneyak<193><207><195>a, 10, <+>96
<+><+><+><+><+>2, <|>Aindrak<193><207><195>a, 10, <+>97
<+><+><+><+><+>3, <|>Aindrak<193><207><195>a, 10, <+>99
<+><+><+><+><+>4, <|>Aindrak<193><207><195>a, 10, <+>98
<+><+><+><+><+>5, <|>Pavam<193>naparva, 10, <+>96
<+><+><+><+><+>6, <|>°ra<207>yakaparva, <+>9, <+>99
, <|>Ara<207>yak<193><207><195>a, <+>5, <+>55
, <|>Mah<193>n<193>mn<200>, -, <+>10
@Z_TBL_BODY = SPACE, SPACE, SPACE, SPACE
, , , 
@Z_TBL_BODY = TABLE TEXT, TC2, TC2, TC2
, <P9B>Total<P255D>, <P9B>64<P255D>, <P9B>650<P255D>
@Z_TBL_END = 
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(E1,E1,.7325), ABOVE(.1389), ç
VGUTTER(.0153), VGRID(Z_SINGLE), KEEP(OFF), L1(R1C0..R1C3), L1(R2C0..R2C3), ç
L1(R13C0..R13C3), L1(R12C0..R12C3), L0(R11C0..R11C3)
@Z_TBL_BODY = TC1X, TABLE TEXT, TABLE TEXT
<P9.5B>Uttar<193>rcik<193><P255D>, +, +
@Z_TBL_BODY = TC2, TC2, TC2
Prap<193><219>haka, K<193><207><195>a, <184>ks
@Z_TBL_BODY = CEN, CEN, CEN
1, 12, 124
2, 12, 111
3, 14, 145
4, 13, 144
5, 21, 172
6, 15, 182
7, 12, 128
8, 13, 144
9, <+>8, 111
@Z_TBL_BODY = SPACE, SPACE, SPACE
, , 
@Z_TBL_BODY = TC2, TC2, TC2
<P9B>Total, <P255>120<+>, <P9B>1261<P255D><|>
@Z_TBL_END = 
@SB = Methods of S<193>mag<193>na
As already stated, there are four groups of s<193>mas: gr<193>mageya, ç
<193>ra<207>yaka, <220>ha and <220>hya.
The first two are the prak<216>tis (basics) and the last two, the ç
vik<216>tis (derivatives).
Any mantra taken from the <184>gveda (a <216>k), when set to music ç
as per the system of svaras or notes of the S<193>maveda, becomes ç
a s<193>ma. This system has beenexplained in the famous work N<193>rad<200>ya·ik<218><193>. ç
According to this work there are 7 svaras (musical notes), 3 gr<193>mas ç
(scales of music †lower range, middle range and top range,respectively ç
called mandrasth<193>y<200>, madhyamasth<193>y<200> and t<193>rasth<193>y<200>), ç
21 m<220>rchanas (variation of the notes in an orderly manner) and ç
49 t<193>nas (protracted notes).
The seven notes of s<193>mag<193>na are the equivalents of the seven ç
notes of Indian music as shown in the following table:
@Z_TBL_BEG = COLUMNS(4), DIMENSION(IN), COLWIDTHS(.2083,1.4942,E1,.2917), ç
ABOVE(.0764), HGUTTER(.0778), VGUTTER(.0280), VGRID(Z_SINGLE), KEEP(OFF), ç
L1(R1C0..R1C4), L1(R0C0..R0C4), L1(R9C0..R9C4), L0(R8C0..R8C4), L0(R0C1..R1C1)
@Z_TBL_BODY = TABLE TEXT, TC2, TC2, TABLE TEXT
, S<193>masvara, Sa<209>g<200>ta-svara, +
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE TEXT
1., prathama, madhyama, ma
2., dvit<200>ya, g<193>ndh<193>ra, ga
3., t<216>t<200>ya, <216><218>abha, ri
4., caturtha, <218>a<195>ja, sa
5., pa<210>cama<|>or<|>atisv<193>rya, ni<218><193>da, ni
6., <218>a<218><219>ha<|>or<|>mandra, daivata, da
7., saptama<|>or<|>kru<218><219>a, pa<210>cama, pa
@Z_TBL_BODY = SPACE, SPACE, SPACE, SPACE
, , , 
@Z_TBL_END = 
While singing the <216>ks as s<193>ma (set to music), certain changes ç
are effected in the letters of the text to facilitate singing. They ç
are listed as follows:
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(.2083,.7358,E1), ç
ABOVE(.0472), BELOW(.0417), VGUTTER(.0278), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
1., <P8BI>vik<193>ra<P255D>, Changing the letter or the word; for ç
example `agne' becomes `ogn<193>yi'.
2., <P8BI>vi·le<218>a<207>a<P255D>, Separating a word; for example ç
`v<200>taye' is changed as `voyi toy<193> 2 yi'
3., <P8BI>vikar<218>a<207>a<P255D>, Lengthening and varying a note; ç
for instance,, `ye' is sung as `y<193> 23 yi'.
4., <P8BI>abhy<193>sa<P255D>, Repetition of a word,, as in `toy<193>yi' ç
which is sung twice.
5., <P8BI>vir<193>ma<P255D>, stopping near a word for slight rest,, ç
as for example in `g<216><207><193>no havyad<193>taye',, stopping ç
before `ha'.
6., <P8BI>stobha<P255D>, Certain letters used to embellish singing,, ç
like au,, hov<193> and h<193>vu.
@Z_TBL_END = 
The numbers like 2, 23 etc., indicate the m<193>tr<193>s or time-units ç
needed for chanting at that place.
There are five fundamental steps in the singing of every s<193>ma. ç
They are:
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), COLWIDTHS(.2083,.7358,E1), ç
ABOVE(.0417), BELOW(.0417), VGUTTER(.0111), KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT
1., <P8BI>prast<193>va<P255D>, This is the beginning of the mantra. ç
The prastot<216> priest begins with the sound `hum'.
2., <P8BI>udg<200>tha<P255D>, The main priest udg<193>t<216> sings ç
this,, beginning it with Om.
3., <P8BI>pratih<193>ra<P255D>, Sung by the priest prati-hart<216>,, ç
this part generally expresses a sense of dedi-cation to the deity ç
to whom it is addressed.
4., <P8BI>upadrava<P255D>, This is sung by the udg<193>t<216> priest ç
himself.
5., <P8BI>nidhana<P255D>, Comprising the last part of the mantra†sometimes ç
including the Om also†this is sung by all the three priests mentioned ç
above,, bringing it to a close.
@Z_TBL_END = 
Some more information may now be adduced here about the s<193>mas ç
for further elucidation.
The mantras of the Purv<193>rcik<193> are prak<216>tis or basic ç
role models. Each of the <216>ks generally has only one s<193>ma, ç
though there are exceptions where the number of s<193>mas can go up ç
to 18. All the s<193>mas on the <216>ks are already fixed by tradition. ç
Some <216>ks may not have any s<193>ma at all. Again, the <216>ks ç
sung as s<193>ma may be in any of the well-known metres like g<193>yatr<200>, ç
anu<218><219>ubh, tri<218><219>ubh, jagat<200> etc.
Sometimes, the same <216>k can be sung as a s<193>ma in all the four ç
groups beginning with veyag<193>na.
Some <216>ks like pun<193>na<199> soma dh<193>ray<193> (S<193>maveda ç
511) have as many as 61 s<193>mag<193>nas!
The s<193>mas (mantras of the S<193>maveda) have been grouped in ç
different ways  and  have  been  given  different nomenclatures.
The prak<216>ti (the first two sections of the p<220>rv<193>rcik<193>) ç
has seven types of g<193>nas.
They are: G<193>yatrag<193>na (based on the famous g<193>yatr<200>mantra); ç
°gneyag<193>na (containing <216>ks pertaining to Agni); Aindra-g<193>na ç
(with <216>ks on Indra in several metres); Pavam<193>nag<193>na (with ç
<216>ks on Soma- Pavam<193>na); Parvatrayag<193>na (containing <216>ks ç
on Arka [here, Agni], couplets called dvandva and vratas); <185>ukriyag<193>na ç
(with <216>ks on <185>ukra or sun)' and, Mah<193>n<193>mn<200> (explained ç
already).
The names of some of the other s<193>mas are: Am<216>tasa<221>hit<193>, ç
Ari<218><219>avarga, Pavitra-varga, Pit<216>sa<221>hit<193>, Skandasa<221>hit<193>, ç
Vain<193>yakasa<221>hit<193> and so on.
@NID = <+><+><+><|>B<216>hats<193>ma, Rathantaras<193>ma, Vair<193>ja- ç
s<193>ma, V<193>madevyas<193>ma†these are a few of the other s<193>mas ç
mentioned in works like the Upani<218>ads.
@SB = <184><218>is, Chandas and Devat<193>s
Anyone wishing to study the Vedic mantras, or even recite them, must ç
know three things about them. They are: <216><218>i (the sage to whom ç
it was revealed), chandas (the metre in which it is composed) and ç
devat<193> (the deity to whom it is addressed.)
Since the mantras of the S<193>maveda have been taken mostly from ç
the <184>gveda it can be presumed that the <216><218>i is the first ç
sage to whom the s<193>ma-pattern was originally revealed.
The following are some of the <216><218>is and the number of s<193>ma-mantras ç
revealed to them given in terms of da·atis: Bh<193>ra-dv<193>ja (29); ç
Gotama (20); Jamadagni (13); Ka<207>va (29); Medh<193>tithi (29); ç
Praska<207>va (13); Saubhari (18); <185>una··epha (17); V<193>madeva ç
(36); Vasi<218><219>ha (43); Vi·v<193>mitra (29).
Though chandas means the metre, etymologically speaking, it is interpreted ç
as something that covers and hence protects, as also gives joy. A ç
knowledge of the chandas is necessary for the knowledge of the padap<193><219>ha ç
(breaking the words of the sentences and the compound words) which ç
is very important in this Veda.
The following are the Vedic metres used here: anu<218><219>ubh; b<216>hat<200>; ç
jagat<200>; pa<209>kti; tri<218><219>ubh; u<218><207>ik.
The devat<193>s or the presiding deities of the various S<193>mavedic ç
mantras are: Agni, Indra, Praj<193>pati, Soma, Varu<207>a, Tva<218><219><193>, ç
A<209>girasa, P<220><218><193>, Sarasvat<200> and Indr<193>gn<200>.
@SB = Subsidiaries of the S<193>maveda
Apart from the Sa<221>hita, every Veda has three more parts: Br<193>hma<207>a, ç
°ra<207>yaka and Upani<218>ad.
To facilitate its study, the help of the Ved<193><209>gas is also ç
necessary.
A list of these, belonging to the S<193>maveda may now be given:
@S10 = Br<193>hma<207>as
@Z_TBL_BEG = COLUMNS(2), DIMENSION(IN), COLWIDTHS(.2500,E1), BELOW(.0417), ç
KEEP(OFF)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT
1., °r<218>eya Br<193>hma<207>a;
2., Devat<193>dhy<193>ya Br<193>hma<207>a;
3., Prau<195>ha Br<193>hma<207>a,, also known as <R>ç
T<193><207><195>ya Mah<193>br<193>hma<207>a and <R>ç
Pa<210>cavi<221>·a Br<193>hma<207>a;
4., <186>a<195>vi<221>·a Br<193>hma<207>a;
5., S<193>mavidh<193>na Br<193>hma<207>a;
6., Sa<221>hitopani<218>ad Br<193>hma<207>a;
7., Talavak<193>ra Br<193>hma<207>a;
8., Upani<218>ad Br<193>hma<207>a;
9., Va<221>·a Br<193>hma<207>a.
@Z_TBL_END = 
The T<193><207><195>ya Mah<193>br<193>hma<207>a is the most important ç
of these.
A  Jaimin<200>ya  Br<193>hma<207>a  is  also available but only ç
in parts. However it also is considered important.
@S10 = °ra<207>yakas
There is only one °ra<207>yaka available called Talavak<193>ra °ra<207>yaka. ç
It is a part of the Talavak<193>ra Br<193>hma<207>a.
@S10 = Upani<218>ads
The Ch<193>ndogya and the Kena or Talavak<193>ra Upani<218>ads ç
are the major Upani<218>ads of the S<193>maveda.
@NID = <+><+><+>Other Upani<218>ads†considered as minor ones†are: Aru<207>opani<218>ad; ç
J<193>b<193>ladar·a-nopani<218>ad; J<193>b<193>lyupani<218>ad; ç
Mahopani<218>ad; V<193>sudevopani<218>ad.
@S10 = Ved<193><209>gas
@NID = <+><+><+><|>The Ved<193><209>gas dealing exclusively with the S<193>maveda ç
can be listed as follows:
P<193><207>in<200>ya <185>ik·<193>; N<193>rad<200>ya <185>ik·<193>; ç
Gautama <185>ik·<193>; Loma·a <185>ik·<193>; Pu<218>pa-s<220>tras; ç
<184>ktantra.
Nid<193>nas<220>tra of Pata<210>jali and Anupadas<220>tra of G<193>rgya ç
deal with the chandas or metres of the S<193>mavedic mantras.
The <185>rautas<220>tras of S<193>maveda are: Dr<193>hy<193>ya<207>a ç
<185>rautas<220>tras; Jaimin<200>ya <185>rautas<220>tras; L<193><219>y<193>yana ç
<185>rautas<220>tras.
Gobhila G<216>hyas<220>tras and Jaimin<200>ya G<216>hyas<220>tras ç
belong to the g<216>hyas<220>tra group of the S<193>maveda.
As regards the dharmas<220>tras of the S<193>maveda, the Gautama ç
Dharmas<220>tras is the only ancient work that is extant now.
Quite  a  few  other  ancient  and medieval works dealing with the ç
subjects of the S<193>maveda are also available.
@SPACE = 
@S10N = THE PHILOSOPHY OF THE S°MAVEDA
@SPACE = 
Since the S<193>maveda contains only the mantras of the <184>gveda ç
set to music, it has no philosophy of its own, but that of the <184>gveda ç
itself. However, quite a fewof the s<193>mas bespeak a high kind ç
of bhakti or devotion. Some of these sentiments may be summarised ç
as follows:
God is brilliant light. May he lightup our hearts! (S<193>maveda, ç
°gneyak<193><207><195>a 1.1)
O God! Please accept the offerings of our good deeds. (ibid 1.2)
You are our dear friend, respected guest. You take us in the path ç
of blissand auspiciousness. I pray to you. (ibid 1.5)
O Lord! All speech, hymns of praise, hymns describing your greatness ç
will ultimately merge in your holy feet. (ibid 1.2.13)
May the spiritual aspirant think of the Supreme Lord, the Being of ç
Light, in his own heart, thereby gaining in faith and the strength ç
to do good deeds! (ibid 1.2.19)
God as Agni destroys our sins and ignorance and enlightens us. (ibid ç
1.4)
O God as Agni! The yogi realises your greatness through divine wisdom.
@SPACE1 = 
O singers of the s<193>mas! Praise the all-powerful God, the destroyer ç
of all sins! We too will eulogise him, the omniscient Lord, the dear ç
friend of all!
O Effulgent God! The ever youthful, the brilliant, the compassionate ç
one! Please shine in our hearts!
O Supreme Lord! You have two forms, one of brilliant splendour and ç
the other of great peace, fit for contemplation. You are the gracious ç
protector of the universe.
We have infinite faith in that creator of the world, who is the dispeller ç
of all sorrow, the best of leaders, the eternal, the all-pervading, ç
the giver of light and the great protector as also the omniscient.
None can vanquish that devotee of God who has surrendered himself ç
to him.
O God! Give us all that we need for our welfare here and destroy all ç
fear brought out by our wrong decisions.
May  the  all-knowing  God,  the destroyer of all our troubles, the ç
indweller in the hearts of all, the all-merciful one, lead us in the ç
straight path!
@SB = Epilogue
Though the S<193>maveda is, comparatively speaking, a smaller work ç
than the other Vedas, it has endeared itself to all by its sweet music, ç
high literary value (as excellent poetry) and noble sentiments of ç
devotion.
It is, undoubtedly, the origin of Indian classical music, though very ç
difficult to master.
It definitely needs more effective propagation and the s<193>magas†singers ç
of the s<193>mas†greater encouragement.
@SPACE = 
@NT = S<193>mavidh<193>na Br<193>hma<207>a
This is one of the nine Br<193>hma<207>as of the S<193>maveda available ç
now.
