It has three prap<193><219>hakas or prakara<207>as or chapters, known ç
respectively as K<216>cchra, Atik<216>cchra and K<216>cchr<193>tik<216>cchra.
The first two have eight anuv<193>kas (subsections) each and the last, ç
nine.
Unlike the other works of Vedic literature, this Br<193>hma<207>a ç
does not deal with sacrifices at all. For the benefit of those who ç
cannot perform Vedic sacrifices to get what they want, it prescribes ç
several k<216>cchras or rites of a magical nature, using the appropriate ç
s<193>mans as the mantras. Hence it looks like a fore-runner of several ç
topics dealt with in the later dharma·<193>stra and t<193>ntrik literature.
These topics may now be summarised briefly as follows:
@SPACE = 
@SB = K<216>cchra-prap<193><219>haka
@SPACE = 
Anuv<193>ka<+>1<|>: Creation of the world from Brahm<193>; in praise ç
of s<193>mans that can grant whatever we want; a brief account of ç
yaj<210>as in general.
Anuv<193>ka<+>2<|>: Description of the k<216>cchras of various types ç
along with the rules to be followed.
Anuv<193>ka<+>3<|>: Rules guiding Vedic studies; results of some sacrifices ç
like Pavam<193>ne<218><219>i.
Anuv<193>ka<+>4<|>: Rite spread over seven nights (saptar<193>trika); ç
the various s<193>mans to be used in getting the fruits of some sacrifices ç
like Agni<218><219>oma, Atir<193>tra and Sattray<193>gas; s<193>mans ç
to be recited to please the deities like Rudra, Vi<218><207>u, and ç
Vin<193>yaka as also for attaining mok<218>a.
Anuv<193>ka<+>5<|>: Some pr<193>ya·cittas or expiations including ç
the s<193>mans to be chanted.
Anuv<193>kas 6, 7 and 8<|>: Some more expiations for sins like accepting ç
prohi-bited gifts, killing a cow, selling things which should not ç
be sold, evil dreams and so on.
@SPACE = 
@SB = Atik<216>cchra Prap<193><219>haka
@SPACE = 
Anuv<193>ka 1<|>: S<193>mans to be employed for attaining long life; ç
purification of oneself; going to Brahmaloka after death; gaining ç
good health.
Anuv<193>kas 2 to 8<|>: These prescribe the japa of various s<193>mans ç
for the destruction of sins, for easy and safe delivery of babies, ç
for getting a good son, for eliminating the evil effects brought about ç
by malignant spirits, for removing the effects of poisons, for safe ç
pilgrimage, for attaining fame or any other desire and so on.
@SPACE = 
@SB = K<216>cchr<193>tik<216>cchra Prap<193><219>haka
@SPACE = 
All the nine anuv<193>kas deal with similar topics such as: s<193>mans ç
to be used for attaining wealth; how to perform v<193>stuhoma; how ç
to discover hidden wealth; means of getting a vision of any deity; ç
means of controlling the minds of others; and s<193>dhana for obtaining ç
mok<218>a or liberation.
The  work  traces  the  parampar<193> (tradition) of teaching thus: ç
Brahm<193> to B<216>haspati; B<216>haspati to N<193>rada; N<193>rada ç
to Vy<193>sa, and Vy<193>sa to Jaimini.
@SPACE = 
It has two commentaries:
@SPACE = 
@NO = 1.
@NOK = Ved<193>rthaprak<193>·a by S<193>ya<207>a (<MS>A.<|>D. <D>1315-1387).
@SPACE = 
@NO = 2.
@NOK = Pad<193>rtham<193>traviv<216>ti by <R>ç
Bharatasv<193>min (<MS>A.<|>D.<D> 1300).
@NT = Samay<193>c<193>ryas
@N1 = (`teachers of [<185>iva]<R>ç
tradition')
<185>aivism is a very ancient religion (or sect) of India. The sixty-three ç
N<193>yanm<193>rs (`servants of God') of Tamil Nadu as also the <185>iva·ara<207>as ç
of Karnataka are its prominent teachers.
The four most important <193>c<193>ryas or teachers of Tamil <185>aivism ç
are generally known as Samay<193>c<193>ryas (`teachers who knew the ç
samaya or tradition, best'). They are: Appar, J<210><193>nasambandhar, ç
Sundara-m<220>rti and M<193><207>ikkav<193>cagar.
(See under each name for details.)
@NT = Samayamata
This is another name for Samay<193>c<193>ra. See under <MS>TANTRAS<D>.
@NT = Sambandhar
See <MS>J<178>°NASAMBANDHAR.<D>
@NT = Sambandhav<193>rttika
@N1 = (`brief commentary on the relation')
Sure·vara (<MS>A.<|>D.<D> 800) was one of the four chief disciples ç
of <185>a<209>kara (<MS>A.<|>D.<D> 788-820). He has written two v<193>rttikas ç
or sub-commentaries on the bh<193><218>yas of <185>a<209>kara on the ç
B<216>had<193>ra<207>yaka Upani<218>ad and the Taittir<200>ya Upani<218>ad.
The first one is one of the longest works (spread over 11,151 verses) ç
in Indian philosophy. The introductory part of it consisting of 1135 ç
verses is known as Sambandhav<193>rttika. It tries to establish ç
the sambandha or relation between the Karmak<193><207><195>a portion ç
and the J<210><193>nak<193><207><195>a portion of the Veda (which ç
deal with rituals and knowledge respectively).
The work is highly polemical.
@NT = S<193>mbapur<193><207>a
This is an upapur<193><207>a (minor or secondary pur<193><207>a) belonging ç
to the Saura group (devoted to Sun-worship). It might have been composed ç
during the period <MS>A.D.<D> 500-800.
S<193>mba was the son of K<216><218><207>a from his wife J<193>mbavat<200>. ç
He is said to have established a temple for S<220>rya or Sun-god at ç
the city S<193>mbapura built by him. He brought eighteen families ç
of Magi priests from <185><193>kadv<200>pa and handed over the regular ç
worship of S<220>rya to them.
This work contains many interesting stories. Other details dealt with ç
are: creation;  the  solar  system;  eclipses; geography of the earth; ç
description of the deity S<220>rya and his attendants; on images of ç
these deities; some details about yoga; on mantras and their use; ç
customs and manners; certain rites and rituals; results of actions.
@NT = <185>ambar<193>sura
He was one of the four sons of Dak<218>a from his wife Danu (and hence ç
a d<193>nava or demon by nature) and lived in p<193>t<193>la (nether ç
world).
See <MS>PRADYUMNA<D> for more details.
@NT = ·<193>mbhav<200>mudr<193>
@N1 = (`mudr<193> related to<R>ç
<185>ambhu [<185>iva]')
It is fixing the gaze on the light of the <193>tman, in the space ç
between theeyebrows (vide Ghera<207><195>a Sa<221>hit<193> 3.64-67), ç
ultimately resulting in <193>tmaj<210><193>na. Such a yogi becomes ç
like °din<193>tha (Primeval Lord) or N<193>r<193>ya<207>a.
According to another definition it is aiming at Brahman inwardly though ç
the gaze of the eyes is fixed outside, but seeing nothing. This technique ç
learnt from a guru, through his grace, will lead to the realisation ç
of the <185>ambhutattva or <185>iva (Ha<219>hayogaprad<200>pik<193> ç
4.34-37).
The correct methods have to be learnt from a competent guru.
@NT = sa<221>h<193>ra
@N1 = (`withdrawal,' `destruction')
Hinduism posits a cyclic theory of creation. S<216><218><219>i (creation), ç
sthiti (sustenance) and sa<221>h<193>ra (withdrawal into the original ç
cause) take place eternally in that cyclic order.
In sa<221>h<193>ra, the process is the exact reverse of s<216><218><219>i.
The word is also used to indicate destruction or killing in general.
See also <MS>COSMOLOGY<D>, <MS>LAYA<D> and <MS>PRALAYA.<D>
@NT = Sa<221>hitopani<218>ad Br<193>hma<207>a
This is one of the Br<193>hma<207>as of the S<193>maveda available ç
now.
It is said to have the characteristics of a Sa<221>hit<193>, a Br<193>hma<207>a ç
and an Upani<218>ad. (See <MS>VEDAS.<D>) Hence the name.
It has five kha<207><195>as or sections. The following are the brief ç
contents:
@S10 = First Kha<207><195>a
This contains an exposition of three kinds of s<193>mag<193>na as ç
daiva, <193>sura and <193>r<218>a.
@S10 = Second Kha<207><195>a
In this section a number of technical terms like kar<218>a<207>a (prolonging ç
a syllable in a chant by inserting more tones), stobha (musical interjections ç
like h<193> u, h<193>i, hum) as also the characteristics of a yajam<193>na ç
(the sacrificer) and the udg<193>t<216> (main singer of the s<193>mans) ç
are explained.
@S10 = Third Kha<207><195>a
<188>has (See <MS>S°MAVEDA.<D>) to be sung in sacrifices are described ç
here. It is also stressed that the s<193>mans are to be taught only ç
to worthy candidates. Six rules concerning the teaching of the s<193>mans ç
are also described.
@S10 = Fourth and Fifth Kha<207><195>as
The subjects discussed here include the greatness of the guru (preceptor) ç
and the qualifications of a disciple, guru-dak<218>i<207><193> or ç
the fees to be paid to the teacher and how a mantra becomes a s<193>man.
Two commentaries†one by S<193>ya<207>a (<MS>A.<|>D.<D> 1315-1387) and ç
another by Dvijar<193>ja- bha<219><219>a†are available on this work.
@NT = ·am<200>
@N1 = (`that which brings peace')
The ·am<200> (Acacia suma) has been considered a holy tree since ç
ages. The Taittir<200>ya °ra<207>yaka (6.9.2) contains a prayer ç
addressed to the ·am<200> tree for the removal of sins and enmities. ç
The plant or even a branch is supposed to have the power to appease ç
the terrible and angry aspects of the deities (Vide Taittir<200>ya ç
Br<193>hma<207>a 1.1.3.11) like Agni.
When a k<218>attriya king intends to go on a victory expedition to ç
subdue or destroy sinners and evil persons, he is expected to worship ç
the ·am<200> tree before starting.
This is performed as a ritual also on the Vijayada·am<200> day (°·vayuja-·ukla-da·am<200>, ç
generally during October) by k<218>attriya kings even today.
Its leaves are sent to friends and relatives as a sign of goodwill ç
on the Vijayada·am<200> day.
The upper ara<207>i (See <MS>ARAØI.<D>) is usually prepared out of ç
·am<200> wood.
@NT = samidh
@N1 = (`that which burns brightly')
Offering fuel-sticks, generally called samidh, into a duly consecrated ç
fire is a part and parcel of many a Hindu rite.
Some of the trees from which these sticks could be procured are: a·vattha, ç
(Ficus religiosa), bilva (Aegle marmelos), candana (sandal-wood), ç
devad<193>ru (pine), khadira  (Acacia  catechu),  nyagrodha (Indian  fig-tree)  and  pal<193>·a  (Butea ç
frondosa).
Fuel-sticks of certain trees like bibh<200>-taka (Terminalia bellerica), ç
kapittha (wood-apple tree) and nimba (neem-tree) should not be used.
The sticks should not be thicker than the thumb, must have the bark ç
on them and should not be worm-eaten. The size is pr<193>de·a (one ç
span). There should be no branches.
@NT = s<193>midhen<200>
@N1 = (`related to samidh [or<R>ç
sacrificial fuel-stick]')
When the Dar·ap<220>r<207>am<193>sa sacrifice is being performed, ç
at a particular stage, eleven (or fifteen) mantras from the <184>gveda ç
are chanted to kindle the fire. These are known as the s<193>midhen<200> ç
verses.
They are: 3.27.1; 6.16.10-12; 3.27.13-15; 1.12.1; 3.27.4; 5.28.5-6.
Though these are eleven mantras, by repeating the first and the last ç
verses twice each, the total becomes fifteen.
All of them are addressed to the deityAgni requesting him to burn ç
more brilliantly and carry the offerings to the Vedic gods.
A samidh (fuel-stick) is offered into the fire after each mantra.
@NT = s<193>m<200>pya
@N1 = (`[living]' near')
See <MS>MOK<186>A.<D>
@NT = samiti
@N1 = (`assembly')
This is an ancient word used even in the <184>gveda (10.191.3) and ç
seems to mean a meeting or a meeting place. 
It might have been an ad hoc assembly of people attended by learned ç
men and others including the king.
Whether it was a regular national assembly of a whole people, as suggested ç
by some scholars, is a moot point.
The word sabh<193> also might have meant the same.
See <MS>SABH°<D>.
@NT = ·amit<216>
@N1 = (`one who silences [the animal victim]')
In the Somay<193>gas of the pa·ubandha type where an animal is sacrificed, ç
the person who kills the animal by suffocating or strangulating it ç
is called a ·amit<216>. He may be a trained butcher or even the adhvaryu ç
priest himself.
In the place†a previously arranged spot†where the severed limbs of ç
the victim are to be roasted, a new fire is to be lighted. It is called ç
·<193>mitra. This fire may be produced newly by attrition or by drawing ç
it from the <193>havan<200>ya fire itself.
@NT = Sa<221>j<210><193>
Sa<221>j<210><193> was the daughter of Vi·va-karma, the architect ç
of the Gods. She was also known as Sure<207>u.
Married to S<220>rya (the Sun-god) she bore him two sons (Vaivasvata ç
and Yama) and a daughter (Yamun<193>).
Unable to bear the brilliance of S<220>rya, she one day left him, ç
after leaving her shadow-goddess called Ch<193>y<193>dev<200> in her ç
place. Ch<193>y<193>dev<200> bore S<220>rya two sons †S<193>var<207>i-manu ç
and <185>anai·cara.
When S<220>rya discovered the truth he went in search of her and found ç
her roaming about as a mare.
The two A·vins were born to them by their union.
He brought her back after pacifying her. (vide Hariva<221>·a 1.9)
As a general word sa<221>j<210><193> means a symbol as also consciousness.
@NT = s<193><221>n<193>yya
@N1 = (`to put together')
It is a mixture of freshly boiled milk mixed with sour milk or curds ç
of the preceding night's milking, offered as obla-tion to Indra (or ç
Mahendra) in sacrifices like the Dar·a, by one who has performed Somay<193>ga.
Some authorities allow its offering even to those who have not performed ç
the Somay<193>ga.
@NT = Sa<221>ny<193>sa
@N1 = (`complete renunciation,' `the order of monks')
@SB = Introduction
Ancient and medieval Hindu scriptures describe four <193>·ramas or ç
stages of life. (See <MS>°<185>RAMA.<D>) The last of these is sa<221>ny<193>sa ç
or the life of a recluse or a monk. Anyone who has developed an intense ç
vair<193>gya or spirit of renunciation for the world and is eager ç
to attain mok<218>a or liberation, is fit for taking sa<221>ny<193>sa. ç
However, in practice, it was restricted only to the br<193>hma<207>as.
One who takes the formal vows of sa<221>ny<193>sa is called a sa<221>ny<193>sin.
There are four kinds of sa<221>ny<193>sins: ku<219><200>caka, bah<220>daka, ç
ha<221>sa and parama-ha<221>sa. (See <MS>PARAMAHA<189>SA<D> for details.) ç
The last is considered as the best.
@SB = Procedure for taking Sa<221>ny<193>sa
The Dharmasindhu of K<193>·<200>n<193>tha Up<193>dhye (<MS>A.<|>D.<D> ç
1790) sets out a procedure for taking sa<221>ny<193>sa which is followed ç
more or less even today.
Since sa<221>ny<193>sa was taken either from the g<193>rhasthya stage ç
(as a householder) or from the v<193>naprastha stage (as a forest ç
recluse), this factor should be kept in mind while studying the same ç
as given in the above-mentioned work.
Briefly stated, the procedure is as follows: seeking a competent sa<221>ny<193>sin- ç
teacher and living with him for at least three months; purification ç
of oneself through the japa of the G<193>yatr<200> mantra, Rudra ç
and performance of K<220><218>m<193><207><195>ahoma (vide Taittir<200>ya ç
°ra<207>yaka 2.7) to get ridof sins; sa<209>kalpa (religious resolve); ç
·r<193>ddha including to oneself; shaving, leaving the ·ikh<193> intact; ç
getting the things needed for the sa<221>ny<193>sin's life like ochre-cloth, ç
da<207><195>a (staff), kama<207><195>alu (water pot), kaup<200>na ç
(loincloth), p<193>duk<193>s (wooden sandals) and so on; worship of ç
Ga<207>e·a and performing °bhyudayika ·r<193>ddha (See <MS>°BHYUDAYIKA-<185>R°DDHA.<D>); ç
recital of certain Vedic texts; fasting; S<193>vitr<200>prave·a (withdrawing ç
the G<193>yatr<200> mantra into oneself since it will not be repeated ç
after sa<221>ny<193>sa); keeping vigil for the whole night; performance ç
ofViraj<193>homa; burning of all wooden sacrificial vessels; blessing ç
all the members of the family and leaving home; repeating the prai<218>amantra ç
(signifying total renunciation of hearth and home); offering of the ç
·ikh<193> (tuft of hair) and yaj<210>opav<200>ta (sacred thread) in ç
water (or the fire of Viraj<193>homa); removal of the old clothes ç
and accepting the ochre-clothes as well as other insignia of sa<221>ny<193>sa ç
from the guru; receiving the mah<193>v<193>kya (See <MS>MAH°V°KYAS.<D>) ç
from the guru as also a new name; taking the blessings of the guru ç
and the senior sa<221>ny<193>sins.
In some orders following non-advaitic tradition, the ·ikh<193> and ç
the yaj<210>opav<200>ta are kept intact and the japa of the G<193>yatr<200> ç
mantra is continued.
@SB = Code of Conduct
The sa<221>ny<193>sin, after formally taking the vows of monastic ç
life, has to lead a wandering life, not dwelling inside villages or ç
towns. His stay should be outside, under a tree or a temple or an ç
uninhabited house. He can enter the village or the town for alms, ç
only once in a day and that too after the smoke from the domestic ç
hearths has died down. He should ever be on the move, wandering alone, ç
never staying in the same place for more than three days, except during ç
the rainy season. (See <MS>C°TURM°SYA.<D>)
Observing strict celibacy and bathing thrice a day he must spend his ç
time in japa (repetition of the divine name), dhy<193>na (meditation), ç
sur<193>rcana (worship of  his  deity)  whenever  possible  and contemplation ç
on Ved<193>ntic and devotional scriptures.
He should be controlled in eating (taking food only once a day). Practising ç
ahi<221>s<193> (non-violence) and satya (truth), he should give abhaya ç
(freedom from fear) to all creatures. He should be equanimous under ç
all circumstances.
His possessions should be only those accepted during the taking of ç
the monastic vows and hence should never accumulate things out of ç
greed.
He should observe silence as much as possible and never practise astrology ç
or occult sciences.
The dharma·<193>stras are replete with many injunctions and prohibitions ç
which may not appear to be relevant in the modern context.
@SB = Other Related Topics
There is no unanimity in the dharma-·<193>stra whether sa<221>ny<193>sa ç
is allowed only to the br<193>hma<207>as or to other dvijas also.
An eccentric theory is sometimes put forward by the fanatical followers ç
of Vedic rituals that only those who are physically disabled†and hence ç
unable to perform the rituals†are fit for sa<221>ny<193>sa!
Though ·<220>dras were denied sa<221>ny<193>sa by the sm<216>tis and ç
the medieval digests, ·<220>dra-ascetics did exist. <185>aiva and ç
<185><193>kta cults permitted it to them also.
Based on the Mah<193>bh<193><218>ya of Pata<210>jali (200 <MS>B.<|>C.<D>) ç
one can surmise that women-ascetics too existed, even in ancient days.
Dvijas who were critically ill and about to pass away could mentally ç
utter the prai<218>amantra and die as sa<221>ny<193>sins. (See <MS>°TURASA<189>NY°SA.)<D>
After death, the body of a sa<221>ny<193>sin had to be buried.
Over the centuries, due to historical, sociological  and  civilisational  factors ç
several changes have been wrought in the institution of sa<221>ny<193>sa ç
though the old and orthodox orders continue to hold on to most of ç
the ancient traditions. Some of them are: changes in modes of dress ç
etc., like wearing stitched clothes and footwear; living in institutions ç
and engaging in public service activities; performance of certain ç
religious rites like p<220>j<193> and homa and so on.
Some orders of sa<221>ny<193>sins prefer cremation after death, to ç
burial.
@SB = Conclusion
If the Hindu society has given thehighest place of honour to the ç
sa<221>ny<193>sins, it has also prescribed the highest standards of ç
morality, ethics and spiritual values.
That the Hindu religion and the society are still vibrant and susceptible ç
to further spiritual development is not a littledue to these sa<221>ny<193>sins ç
and the institution of sa<221>ny<193>sa itself.
See also <MS>ASCETICS<D>, <MS>°<185>RAMA<D>, <MS>DA<185>A-N°M®S<D>, ç
<MS>MONASTICISM<D> and <MS>YATI.<D>
@NT = Sa<221>ny<193>sopani<218>ad
This is a minor Upani<218>ad belonging to the Atharvaveda. There ç
are two chapters. The first chapter consists of only one prose passage. ç
The second is a long one comprising 123 sections, mostly in anu<218><219>ubh   verses,   interspersed   with ç
passages in prose also.
@S10 = First Chapter
This describes how a householder who has successfully completed all ç
his duties should proceed to take sa<221>ny<193>sa. The various steps ç
are: taking the approval of wife and children for his sa<221>ny<193>sa; ç
performing Vai·v<193>nara sacrifice and gifting away his possessions; ç
withdrawing the Agnidevat<193> from the Vedic fires; giving up the ç
·ikh<193> (tuft of hair) and yaj<210>opav<200>ta (sacred thread), ç
going away either towards the east or towards the north.
He can accept bhik<218><193> (alms of cooked food) from all castes, ç
using the cupped hands as the bowl. He should not hanker for tasty ç
food nor live in any place for more than one to five days. During ç
the rainy season, however, he can stay in one place for two to four ç
months. He should manage with minimum possessions like a bowl for ç
alms, kaup<200>na (loin cloth), kanth<193> (wrapper), kama<207><195>alu ç
(water pot), pavitra (straining cloth), da<207><195>a (staff) and ç
p<193>duk<193> (sandals).
Acquiring spiritual wisdom and meditation on the <193>tman (or God) ç
should be his only concern.
@S10 = Second Chapter
This is a very long section. The subjects dealt with may be briefly ç
summarised as follows: persons who are fit and unfit for sa<221>ny<193>sa; ç
method of accepting sa<221>ny<193>sa by giving up the ·ikh<193> and ç
the yaj<210>opav<200>ta and taking the accessories like the da<207><195>a ç
and kama<207><195>alu; categories of sa<221>ny<193>sins like vair<193>gya ç
sa<221>ny<193>sins and j<210><193>na sa<221>ny<193>sins as also ku<219><200>caka ç
and bah<220>daka; method of meditating on the unity of one's <193>tman ç
with Brahman; praise of citi·akti or pure consciousness; experience ç
of the abheda-anubhava or the non-dual state; method of taking <193>tura-sa<221>ny<193>sa ç
or sa<221>ny<193>sa by a dying person; meditation on one's own true ç
nature as the only duty of a sa<221>ny<193>sin; code of conduct ç
including the methods of bhik<218><193> (begging  for  food);  prohibited  things, ç
behavior and actions; six kinds of sins like sleeping by day and acquiring ç
disciples; expiations like pr<193>n<193>y<193>ma for transgressions; ç
continuous japa of Om (12,000 times) leading to illumination.
The only commentary available now is that by Upani<218>ad-brahmendra-yogin.
There is another Sa<221>ny<193>sopani<218>ad which is much smaller, ç
comprising five sections in prose.
@SPACE = 
@NT = <185>amp<193>kag<200>t<193>
@N1 = (`didactic poem of<R>ç
<185>amp<193>ka')
@SPACE = 
The  celebrated  Bhagavadg<200>t<193>  has inspired the composition ç
of many more such g<200>t<193>s. They are found mostly in the Mah<193>bh<193>rata ç
itself as also the Bh<193>gavata. A few have been discovered to ç
be independent works.
The <185>amp<193>kag<200>t<193>, comprising just 22verses, is a ç
part of the Mah<193>bh<193>rata (<185><193>ntiparva 176).
Yudhi<218><219>hira poses a question to Bh<200><218>ma as to the fate ç
that overtakes a man, whether he is rich or poor. Bh<200><218>ma recounts ç
from his memory what he had heard once from <185>amp<193>ka, a br<193>hma<207>a ç
who was leading a life of ty<193>ga or vair<193>gya (renunciation).
None in this world is always happy or always suffering without experiencing ç
the other state.
To get true happiness and peace, it is not enough to give up desires. ç
One should strive for ·reyas, what is spiritually benefitting.
Duties and responsibilities of a king (or a ruler) weigh heavily on ç
the mind. That naturally disturbs the mind and makes it go out of ç
control.
Aki<210>canatva, not possessing anything, is the best way to peace ç
in life.
A man of total renunciation who does not keep any money or possessions, ç
has nothing to fear. He is fully free, whereas a rich man lives in ç
misery, being constantly overcome by anger, greed, delusion, pride ç
and arrogance. These make him transgress all norms of dharma and hence ç
a victim of the ruler's wrath.
Hence one should give up all kinds of worldly desires and find the ç
true remedy to dispel sorrows and sufferings through spiritual wisdom.
It is ty<193>ga (renunciation) and ty<193>ga alone that gives us fearlessness ç
and happiness, and takes to paramapada or the highest abode (liberation).
@SPACE = 
@NT = Samp<193>ti
@SPACE = 
Samp<193>ti and Ja<219><193>yu, the two great eagles mentioned in ç
the R<193>m<193>ya<207>a, were brothers and were the sons of Aru<207>a, ç
the charioteer of S<220>rya (the Sun-god).
@SPACE = 
@SPACE = 
@SPACE = 
@SPACE = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
Once both of them started flying towards the sun. As they flew nearer ç
the sun, the heat became so intense that it became unbearable. Samp<193>ti, ç
to protect his younger brother Ja<219><193>yu, spread his wings over ç
him thereby getting them burnt.
When the sage Candra heard his story, he told him that he would get ç
back his wings when, in future, he would reveal the place where S<200>t<193> ç
was kept, to the monkey army of R<193>ma. This he did and got back ç
his wings.
See also <MS>JA<187>°YU<D>.
@NT = samprad<193>ya
@N1 = (`that which is given or handed over [in succession]')
Samprad<193>ya or tradition, wherein a knowledge or a way of life ç
is handed over from a guru (teacher) to a disciple or a group of disciples ç
has a very important place in Hinduism.
Many a time, a guru does not impart all that he knows, to his disciples. ç
From among those who live with him and serve him, he may choose one ç
or two as the fittest to receive that knowledge he has kept back. ç
It is this that often matters, more than the open teaching or the ç
books. Because of this reason, samprad<193>ya is all important.
A peculiar trait of Hinduism is that all sciences and arts are often ç
traced to God Himself as the originator. Sometimes it may be a great ç
<216><218>i or sage also.
`Samprad<193>ya' may also mean the bodyof the founder-teachers and ç
their immediate disciples.
There are different samprad<193>yas in each of the sciences or arts ç
or fields of wisdom.
It is strongly believed that those mantras which are not handed down ç
through a samprad<193>ya, are useless and hence do not produce their ç
results.
Some works like the <185>aktisa<209>gama-tantra (1.8) give long ç
lists of samprad<193>yas such as Vaikh<193>na, R<193>dh<193>vallabh<200>, ç
P<193><210>ca-r<193>tra, V<200>ravai<218><207>ava, Bh<193>gavata, ç
Nimb<193>rka and V<216>nd<193>van<200>.
@SPACE1 = 
@NT = sampraj<210><193>ta
See <MS>ASAMPRAJ<178>°TA.
@SPACE1 = 
@NT = sa<221>s<193>ra
@N1 = (`roaming about [through births and rebirths]')
According to Hinduism, though the <193>tman (the soul or the Self) ç
is eternally free (nityamukta), it has somehow (inexplicably) got ç
itself entangled with avidy<193> (ignorance or nescience), which entanglement ç
is stated to be an<193>di or beginning-less, though it can be ended ç
(hence, s<193>nta). This avidy<193> leads to its perceiving dvaita ç
or duality, viz., the world and other beings as different from it. ç
This again creates k<193>ma or desire in its mind, to get what it ç
wants or get rid of what it does not want. To fulfil this k<193>ma ç
it has to take repeated births. It is this transmigration that is ç
called sa<221>s<193>ra.
@SPACE1 = 
@NT = sa<221>·aya
@N1 = (`that which sleeps [or remains in the mind]")
Sa<221>·aya or doubt is created when two kinds of knowledge, opposed ç
to each other, arise in the mind.
In the Yogas<220>tras (1.30) of Pata<210>jali (200 <MS>B.<|>C.<D>), ç
it is listed as one of the nine obstacles to yoga. It has to be overcome ç
by faith in the scripture and the teacher.
The Bhagavadg<200>t<193> (4.40) declares that a doubting person ç
loses this world and the next and ultimately destroys himself.
Some technical treatises classify sa<221>·aya into seven categories ç
such as·uddhasa<221>·aya (doubt in general), dharmasa<221>·aya (doubt ç
regarding dharma) and so on.
@SPACE1 = 
@NT = sa<221>sk<193>ras
@N1 = (`refinement', `sacraments')
The word sa<221>sk<193>ra, in a technical sense, means a ritualistic ç
act (accompanied by appropriate mantras) by which a person is rid ç
of his defects and limitations, and, made refined by adding some speciality.
Such sa<221>sk<193>ras as listed in the sm<216>tis and dharma·<193>stras ç
vary from 16 to 40. However, 16 sa<221>sk<193>ras†generally called ç
<218>o<195>a·a-sa<221>sk<193>ras†have been widely accepted.
See <MS><186>O£A<185>A-SA<189>SK°RAS<D> for details.
@SPACE1 = 
@NT = Sa<221>sk<216>ta
@N1 = (`the refined')
The word is generally used to indicate the Sanskrit language.
See <MS>SANSKRIT LANGUAGE<D> for details.
@SPACE1 = 
@NT = samudra
See <MS>S°GARA.
@SPACE1 = 
@NT = samudramathana
@N1-1 = (`churning of the ocean [of milk]')
Indra, the king of gods, lost his all to the demons, due to the disrespect ç
shown out of pride, to a great sage Durv<193>sas. Lord Vi<218><207>u ç
advised him to make up with his enemies (the demons) and with their ç
help, to churn the ocean of milk, out of which am<216>ta (ambrosia) ç
could be got. Bydrinking it, the gods could become immortal and regain ç
their lost sovereignty. Accordingly, the gods and the demons started ç
churning the ocean, making the Mandara mountain as the churning rod ç
and V<193>suki, the great serpent as the rope. Vi<218><207>u took ç
the form of a gigantic tortoise (K<220>rma) to support the mount Mandara ç
from sinking. The first product of this joint venture and adventure ç
was h<193>l<193>hala, the most deadly poison! <185>iva the auspicious ç
one, swallowed this, thus saving the worlds from sure destruction. ç
Then were produced K<193>madhenu (the wish-yielding cow), Uccai·ravas ç
(the white horse), Air<193>vata (the elephant), Kaustubhama<207>i ç
(the matchless jewel), Kalpav<216>k<218>a (the wish fulfilling tree), ç
Lak<218>m<200> (the goddess of fortune), Sur<193> or V<193>ru<207><200> ç
(the goddess of wine) and Dhanvantari (the physician of the gods) ç
bearing the vessel of am<216>ta (the ambrosia) in his hands. The <184><218>is ç
took away the cow K<193>madhenu, Bali (the king of demons) cast his ç
eye on the horse Uccai·ravas, Indra (the king of gods) accepted the ç
elephant Air<193>vata and got the tree Kalpav<216>k<218>a planted ç
in his garden in heaven. Vi<218><207>u chose to wear the jewel Kaustubha ç
on his chest whereas Lak<218>m<200> chose Vi<218><207>u's chest as ç
her dwelling. The gods chose Sur<193> who had been strangely enough, ç
rejected by the demons. Contravening the original agreement that the ç
am<216>ta should be shared by both the groups equally, the demons ç
forcibly snatched away the pot from Dhanvantari's hands to appropriate ç
the entire quantity for themselves. Selfishness and greed, however, ç
led to disagreement, discontent and conflict. Taking this opportunity ç
Vi<218><207>u took the form of Mohin<200>, the enchantress, lured ç
the vessel of ambrosia into his hands and cleverly managed to distribute ç
its contents among the gods only. Then the inevitable happened. Being ç
intoxicated by the new strength gained thus, the gods fell upon the ç
demons, vanquished them and regained their lost sovereignty.
@SPACE1 = 
This myth has great lessons for us. In order to get the greatest good ç
of the greatest number, the saner elements of the society should influence ç
the masses to bury their hatchet, sink all their petty differences ç
and make a coordinated and co-operative effort to achieve it. Since ç
the task is stupendous, the effort will have to be equally stupendous. ç
The early results of all such joint ventures need not always be good ç
or pleasant. Due to conflict of personalities and clash of interests ç
which naturally arise in the field of joint ventures, it is h<193>l<193>hala ç
that appears first and not am<216>ta! This deadly poison starts destroying ç
all the parties involved in the conflicts irrespective of who is right ç
or who is wrong! Hence out of sheer necessity, the entire society ç
should unite and appeal to the leaders to save it. Any true leader ç
of the society, worth the name, will, like <185>iva the auspicious ç
one, voluntarily and willingly come forward risking his life, to assimilate ç
this poison and save the society from sure destruction. Once these ç
conflicts are resolved and the efforts are redoubled, Lak<218>m<200> ç
signifying abhyudaya (well-being, fortune) and am<216>ta signifying ç
ni·sreyasa (moral and spiritual elevation ultimately leading to beatitude) ç
are bound to arise from the firmament of their joint adventure. But, ç
again, contrary to the covenant, if the selfish and belligerent groups ç
of the society try to appropriate to themselves all the fruits of ç
the common labours, God, the law-giver and justice personified, will ç
thwart their efforts. The good shall and will vanquish the evil.
@SPACE1 = 
This story can be interpreted at the subjective level also. Anyone ç
who is tired of the vicissitudes of life and is hankering for peace ç
and bliss should seek it only in the highest spiritual enlightenment. ç
Am<216>ta signifies just this enlightenment. To get this, an all-out ç
effort will have to be made. The sense-organs which usually pull the ç
mind down and create confusion, conflicts and  heart-burns,  should  be  tactfully ç
mobilised in this effort even as the demons were used by the gods. ç
Spiritual life is a long struggle. Meditation is actually mind-churning. ç
Hence, this process will inevitably throw up the deadly poison hidden ç
in the recesses of the mind as passions and prejudices, which try ç
to destroy every process of s<193>dhana (spiritual efforts). An intense ç
and earnest prayer to God, <185>iva, will save the situation by getting ç
it sublimated. The conquest of M<193>ra by the Buddha<|>or Satan by ç
Christ, can be understood in this light. Once the worst is over, the ç
spiritual aspirant will gradually start reaping the benefits of his ç
efforts in the form of Siddhis (powers), psychic or other-wise. K<193>madhenus ç
and Kalpav<216>k<218>as can mean such powers. This will be crowned ç
with success when he gets a vision of theall-pervading cosmic energy ç
(Lak<218>m<200>) resulting in immortal bliss (am<216>ta).
@NT = samudray<193>na
@N1 = (`travel by sea')
It is rather strange that some of the dharma·<193>stras prohibited ç
samudray<193>na (voyage by sea) for the dvijas in general and the ç
br<193>hma<207>as in particular, by including it in the long list ç
of what they call `kalivarjya' (that which should be prohibited in ç
the age of Kali, starting from 3100 <MS>B.<|>C.<D>) (Vide Baudh<193>yana ç
Dharma-s<220>tras 2.1.51; Manusm<216>ti 3.158 and 166, 167).
The fear of var<207>asa<209>kara (mixing up of castes) was, perhaps, ç
uppermost in their minds.
It is an undeniable fact that manysages and savants like Agastya ç
had travelled to foreign countries including the Middle East and the ç
Far East. They went out, sans the Sword and sans the Book, to spread ç
knowledge and the message of universal brotherhood.
Sea-voyage was quite flourishing evenin the pre-Christian era. Trade ç
and commerce contacts had been established with several countries ç
both in the east and in the west.
The Vijayanagar empire itself boasted of 300 ports!
@NT = sa<221>v<193>das<220>ktas
See <MS><184>GVEDA.<D>
@NT = Sa<221>vargavidy<193>
@N1 = (`science of sa<221>varga')
See <MS>CH°NDOGYA UPANI<186>AD<D> and <MS>VIDY°S.<D>
@NT = Sa<221>varta-sm<216>ti
Sa<221>varta-sm<216>ti seems to be a fairly ancient work. Sa<221>varta ç
is quoted by many authors of dharma·<193>stras like Apar<193>rka, ç
Haradatta, Medh<193>tithi, Vi·var<220>pa and others. As many as 200 ç
verses of his, have been given in their works.
There is a printed text which appears to be an epitome of a portion ç
of the original sm<216>ti of Sa<221>varta.
The sm<216>ti is in the form of Sa<221>varta's teachings to V<193>madeva ç
and others.
The  topics  dealt  with  may  be summarised as follows:
Rules of conduct for a brahmac<193>rin; pr<193>ya·cittas or expiations ç
for various kinds of sins; duties of a householder, a forest hermit ç
and a sa<221>ny<193>sin; special duties of a king; and a few minor ç
topics as the age of girls for marriage.
According to the Mah<193>bh<193>rata (°diparva 67) Sa<221>varta ç
was a son of A<210>giras. B<216>haspati and Ucathya were his brothers.
It is difficult to say whether this was the same Sa<221>varta who ç
authored this sm<216>ti.
@NT = sa<221>yama
@N1 = (`control')
Though the word is used in the general sense of control or self-control, ç
the Yogas<220>tras (3.4) of Pata<210>jali (200 <MS>B.<|>C.<D>) employs ç
it as a technical term.
When dh<193>ra<207><193> (fixing the mind on an object) and dhy<193>na ç
(meditation on the same) result in sam<193>dhi (superconscious experience), ç
the process (of practising these three together) is defined as sa<221>yama.
Pata<210>jali describes a number of siddhis (psychic powers) that ç
a yogi attains by practising sa<221>yama on various objects (3.5-55).
@NT = Sanaka, Sanandana, Sanatkum<193>ra and Sanatsuj<193>ta
See <MS>CATUS-SANA<D> for details.
@NT = San<193>tanadharma
@N1 = (`the eternal religion')
The word Hinduism for the religion it represents, is of very recent ç
origin.
This religion had no particular namesince the most ancient days, ç
because there existed no other religion from which it had to be distinguished.
Some scholars of present-day Hinduism like to call it `San<193>tanadharma.'
It is true that this word occurs in the Kh<193>n<193>pur plates of ç
M<193>dhavavarma (vide Epigraphia Indica vol. 27, p. 312) assigned ç
to the 6th century <MS>A.<|>D.<D> Other sources where it has been used ç
are: Matsyapur<193><207>a 143.30-32; Bh<193>gavata 7.11.2 and ç
Brahm<193><207><195>apur<193><207>a 2.33.37-38.
However, in both these places the word does not refer to any specific ç
religion, but, only to ancient practices of eternal value.
Yet, it is possible to apply this word to Hinduism since it reflects ç
the true spirit of Hinduism correctly.
The expression dharma (`that which supports') has three senses: God; ç
any spiritual discipline that leads to God; duty.
`San<193>tana' means the eternal.
Since the various s<193>dhanas or spiritual disciplines taught by ç
Hinduism have been proving their efficacy even today (as in the ancient ç
period)†hence san<193>tana oreternal†ultimately leading to God, theEternal ç
Truth, it fully deserves the appellation `San<193>tanadharma'.
@NT = San<193>tan Gosv<193>min
@N1 = (<MS>A.<|>D. <D>1481-1558)
@SPACE = 
San<193>tana Gosv<193>min and R<220>pa Gosv<193>min (<MS>A.<|>D.<D> ç
1493-1568) were brothers. Along with their nephew, J<200>va Gosv<193>min ç
(d. <MS>A.<|>D.<D> 1609) they formed the three pillarsof the Caitanya ç
Movement and the Acintyabhed<193>bheda School of philosophy propagated ç
by it.
San<193>tana was a high officer in the court of a Muslim nawab. Once ç
he was going to another place on some urgent work. When he was caught ç
in a hurricane, he accidentally heard the conversation between a lady ç
and her husband, who wanted to venture into the hurricane. This had ç
miraculous effect on his mind. He forthwith resigned from his job ç
and wanted to join Caitanya Mah<193>prabhu (<MS>A.<|>D.<D> 1485-1533). ç
Though he was jailed by his employer, he managed to escape and approached ç
Caitanya to be accepted as a disciple, which he did.
Towards the end of his life he started living in V<216>nd<193>ban, ç
the place closely associated with the boyhood of K<216><218><207>a.
His works are: G<200>t<193>val<200>, Vai<218><207>ava-to<218>i<207><200>, ç
Bh<193>gavat<193>m<216>ta and Siddh<193>ntas<193>ra. Rasamayakalik<193> ç
is another work but in Be<209>g<193>l<200>.
@SPACE = 
@NT = Sanatsuj<193>t<200>ya
@N1 = (`that which is related to [the sage] Sanatsuj<193>ta')
@SPACE = 
The Mah<193>bh<193>rata which has given us the great jewel of a ç
scripture called the Bhagavadg<200>t<193>, has also presented us ç
with several other treatises of deep philosophical content. One such ç
work, perhaps, next only to the Bhagavadg<200>t<193>, is the Sanatsuj<193>t<200>ya.
It forms a part of the Udyogaparva (chapters 42 to 46). The total ç
number of verses is 145 (in four chapters) according to one version ç
and 192 (in five chapters) according to another.
Being an important composition, it has drawn the attention of many ç
commentators like <185>a<209>kara (<MS>A.<|>D.<D> 788-820), N<200>la-ka<207><219>ha ç
(<MS>A.<|>D.<D> 1400), Sarvaj<210>a N<193>r<193>ya<207>a and V<193>dir<193>ja ç
(<MS>A.<|>D.<D> 1480-1600).
When Dh<216>tar<193><218><219>ra, the blind king, wants to listen ç
to higher philosophical truths from Vidura, the latter excuses himself ç
as unfit to impart the same. He then mentally prays to the great sage ç
Sanatsuj<193>ta who appears instantly before him. At his request the ç
sage gives a spiritual discourse to Dh<216>tar<193><218><219>ra. It ç
is this discourse that goes by the name Sanatsuj<193>t<200>ya.
Dh<216>tar<193><218><219>ra questions Sanatsuj<193>ta thus: ``I understand ç
that you declare that there is no death at all. On the other hand ç
I have heard that the devas (gods) and the asuras (demons) had approached ç
Praj<193>pati to know how to overcome death (vide Ch<193>ndogya Upani<218>ad ç
(Chapter 8.7-12). What then, is the truth?''
Sanatsuj<193>ta's reply is spread over four chapters. It may be summarised ç
as follows:
@SPACE = 
@S10N = First Chapter (43 verses)
It is pram<193>da that is the real m<216>tyu or death. Pram<193>da ç
means aj<210><193>na, ignorance of the real nature of the <193>tman, ç
the Self. This aj<210><193>na leads to aha<209>k<193>ra (egoism), ç
k<193>ma (desire), krodha (anger), am<193>rga (the wrong path), janma ç
(birth and rebirth) and du<199>kha (suffering). This is how pram<193>da ç
can be equated with death.
The only way to destroy this m<216>tyu is by apram<193>da or j<210><193>na ç
(knowledge).
It is m<193>y<193> which is an<193>di (beginning-less) that is responsible ç
for pram<193>da. Ni<218>k<193>makarma (desireless action) gradually ç
leads to j<210><193>na by purifying the mind.
The last part of this chapter is devoted to a description of the j<210><193>ni ç
or a man of realisation. His life is so pure that it is beyond all ç
pairs of opposites like fame or blame.
@S10N = Second Chapter (50 Verses)
Nature of j<210><193>na is discussed in this chapter. It is certainly ç
not intellectual scholarship of the Vedas or other scriptures, but ç
tapas or austerity that leads to the purification of the mind in which ç
j<210><193>na as realisation of the <193>tman (the true Self) arises.
Pure tapas has to be free from twelve do<218>as (defects) and seven ç
n<216>·a<221>sas (cruel deeds). It has to be endowed with twelve gu<207>as ç
(virtues).
Some<|> of<|> the<|> do<218>as<|> are: <|>krodha (anger), k<193>ma (lust), ç
lobha (greed), moha (delusion) and as<220>y<193> (jealousy).
The  n<216>·a<221>sas  include  harming others, putting up with great ç
disgrace for small gains, lack of wisdom and hatred of women.
The gu<207>as comprise the following: satya (truth), dama (self-control), ç
adhy<193>tma·<193>stra·rava<207>a (listening to the sacred scriptures), ç
titik<218><193> (forbearance), d<193>na (giving gifts), dh<216>ti ç
(fortitude) and ·ama (internal peace).
@S10N = Third Chapter (23 Verses)
This section is dedicated to a description of j<210><193>nayoga. Knowledge ç
of the Selfor
