The<|><185><193><209>kh<193>yana<|>G<216>hyas<220>tras belongs to ç
the <184>gveda. It is a fairly long work. There are 1075 s<220>tras ç
accommodated in 96 kha<207><195>as or sections, which again, are contained ç
in 6 adhy<193>yas or chapters.
The contents may be briefly summarised as follows:
Sacrifices like the p<193>kayaj<210>as and the Dar·ap<220>r<207>am<193>sa; ç
details of the sa<221>sk<193>ras or sacraments like viv<193>ha (marriage), ç
pu<221>savana, j<193>takarma and so on, including upanayana and up<193>karma; ç
duties of a sn<193>taka (one who has completed his Vedic education); ç
building a house and the rituals connected with entering it (called ç
g<216>haprave·a); ·r<193>ddhas (obsequial rites); pilgrimage and Vedic ç
sacrificial fire; consecration of wells, ponds, tanks and gardens; ç
pr<193>ya·cittas or expiations.
For details of these subjects, see under the respective titles.
@NT = S<193><209>khya Dar·ana
@SB = Introduction
After stating his views and defending them with the help of appropriate ç
quotations from the Upani<218>ads, B<193>dar<193>ya<207>a in his Brahmas<220>tras ç
starts his criticisms of other schools with the S<193><209>khya philosophy ç
(2.2.1). While commenting upon the s<220>tra 1.4.28, <185>a<209>kara ç
(<MS>A.<|>D.<D> 788-820) has given the reason as to why the S<193><209>khya ç
system was chosen first. The word he has used (`pradh<193>na-malla-nibarha<207>a-ny<193>yena,' ç
`by the maxim of overcoming the chief wrestler') is very significant. ç
If a well-known wrestler overcomes the chief wrestler of the opponents' ç
group first,it is as good as all the others also being vanquished, ç
even without fighting them! This shows how important a system S<193><209>khya ç
Dar·ana is.
As per the orthodox accounts, this system was founded by the sage ç
Kapila (vide Bh<193>gavata 3.25-33). The work that has come down ç
to us, as his, is the S<193><209>khyas<220>tras. It is obviously ç
a late work. It is in six chapters and contains 526 s<220>tras in ç
all. Vij<210><193>nabhik<218>u (16th century <MS>A.<|>D.<D>) has written ç
a commentary on the same, known as S<193><209>khya-pravacana-bh<193><218>ya.
The S<193><209>khyan tradition of philosophy was nourished and propagated ç
by Kapila's disciple °suri and his disciple Pa<210>ca·ikha. Some s<220>tras ç
of Pa<210>ca·ikha are found quoted in the Vy<193>sabh<193><218>ya ç
(<MS>A.<|>D.<D> 600) on the Yogas<220>tras of Pata<210>jali (200 ç
<MS>B.<|>C.<D>). The complete work as such has not yet been found.
By far, the earliest available (and reliable) work on the S<193><209>khya ç
is the S<193><209>khyak<193>rik<193>s of ®·varak<216><218><207>a ç
(5th century <MS>A.<|>D.<D>). It has 70 stanzas (in the <193>ry<193> ç
metre) and hence, sometimes, designated as S<193><209>khya-saptati ç
also.
It contains a brief but brilliant and lucid exposition of the doctrines.
This work has two well-known commentaries: S<193><209>khyak<193>rik<193>-bh<193><218>ya ç
of Gau<195>ap<193>da (<MS>A.<|>D.<D> 700) and the S<193><209>khya-tattva-kaumud<200> ç
of V<193>caspati (<MS>A.D.<D>840).
The S<193><209>khyas<193>ra of Vij<210><193>nabhik<218>u and the ç
S<193><209>khyapravacanas<220>trav<216>tti of Aniruddha (15th cent. ç
<MS>A.<|>D.<D>) are the other works of importance.
@SB8.5 = Significance of the Name
The origin of the word `S<193><209>khya' seems to have been an enigma. ç
Some thinkers derive it from sa<209>khy<193> (<W1%22>=<D%0>number) ç
and opine that it might have got this name since it enumerates the ç
ultimate principles in creation as 25. Others however think that since ç
it stresses j<210><193>na or knowledge as the only means of liberation ç
and since `sa<209>khy<193>' means j<210><193>na (samyak khy<193>yate), ç
the word fits in very well with the system.
@SB = The Pram<193><207>as or Methods of Knowledge
Unlike many other systems, the S<193><209>khya accepts only three ç
pram<193><207>as or valid sources of knowledge. They are pratyak<218>a ç
(direct perception), anum<193>na (inference) and ·abda (testimony).
Pratyak<218>a is the direct cognition of an object through its contact ç
with a sense-organ, like the eyes seeing a table or the ears hearing ç
the chirping of birds. The first contact may give a general knowledge. ç
This is called `nirvikalpaka' (indeterminate). When, on closer observation ç
and thinking, the perception gives a clearer idea, it is called `savikalpaka' ç
(determinate). On seeing a table, the first reaction is, `I am seeing ç
some object.' Then comes a clearer idea, `This is a wooden table with ç
a red cloth spread over it.' The first is nirvikalpaka-pratyak<218>a ç
and the second, savikalpaka-pratyak<218>a.
Anum<193>na or inference is the second source of knowledge. It is ç
gained by seeing some sign first and then inferring the reality behind ç
it. The stock example given by most of the philosophers is, coming ç
to the conclusion that there is fire on a distant hill, by seeing ç
smoke rising out of it. Since our previous experience through direct ç
perception has shown that wherever there is smoke, there is fire, ç
here also we conclude that there is fire, even though we do not see ç
it directly. An invariable concomitance between the object seen and ç
the unseen object inferred (here, the smoke and the fire) is a necessary ç
precondition.
<185>abda or testimony is the third and the last of the pram<193><207>as. ç
It is the testimony of a reliable person. This is called laukika-·abda ç
or <193>ptav<193>kya. The S<193><209>khya, however, does not recognise ç
this as a separate pram<193><207>a since it depends upon the perception ç
and inference of that reliable person. It is the testimony of the ç
<185>ruti or the Vedas that the S<193><209>khya philosophy admits ç
as the independent and last pram<193><207>a. The Vedas give us true ç
knowledge about the supersensuous realities, which cannot otherwise ç
be known, by pratyak<218>a or anum<193>na. The Vedas being apauru<218>eya ç
(not man-made but divine), are infallible. They embody the intuitions ç
of the great <216><218>is, the enlightened sages.
@SB = The Prameyas or the<R>ç
Objects to be Known
Adopting the principle of ``from the seen to the unseen or from the ç
known to the unknown,'' S<193><209>khyan metaphysics has reduced all ç
the realities in our experience to two fundamental and eternal substances: ç
the prak<216>ti (also called pradh<193>na and avyakta) (the insentient ç
nature, the matrix of all lifeless and unconscious objects); the puru<218>a ç
(the being, the conscious self or the soul).
The basic argument behind this conclusion is called `Satk<193>ryav<193>da,' ç
the principle that the effect (= k<193>rya) pre-existed (= sat) in ç
the cause (= k<193>ra<207>a), before manifestation. For instance, ç
when a pot is prepared out of clay, the pot already existed in the ç
clay, though in a potential form. The main logic behind this is that ç
something can never be produced out of nothing.
Applying this argument to the world of our experience where every ç
object is seen to possess three characters†pleasure, pain and indifference†the ç
S<193><209>khya comes to the conclusion that there must be three basic ç
subtle substances from which these three characters are derived. It ç
calls them as gu<207>as†sattvagu<207>a (producing pleasure or happiness), ç
rajogu<207>a (producing pain and suffering) and tamogu<207>a (producing ç
neither).
Each of these gu<207>as stands for a distinct aspect of physical reality. ç
Sattva signifies whatever is pure and fine, and, conduces to the production ç
of knowledge as also happiness. Rajas is ever active. It is also responsible ç
for desires and ambitions, to fulfil which one has to actively work. ç
Tamas is stolid and offers resistance. It tends to sleep and inactivity.
These three gu<207>as always exist together and can never get separated. ç
When these three†which are ever in turmoil as it were†are in a perfectly ç
balanced state, not interfering with one another, though ever active ç
or in perpetual motion within themselves, constitute the prak<216>ti ç
or pradh<193>na. In other words, prak<216>ti is none other than these ç
three gu<207>as in a state of perfect balance.
@SPACE1 = 
This prak<216>ti is the basic material, primal matter, from which ç
the universe evolves. It is `ja<195>a,' i.e., it has no consciousness.
The puru<218>a (the soul) on the other hand is a conscious entity; ç
nay, consciousness is his veryessence. He is eternal, ever pure, ç
ever detached (asa<209>ga) and all-pervading. There are innumerable ç
puru<218>as or souls, as many as the living beings.
@SB = Evolution of the World
The creation or evolution of the world has its starting point in the ç
sa<221>yoga or effective contact between the puru<218>a and the prak<216>ti. ç
The totality of the karmas (unseen deserts) of the puru<218>as disturbs ç
the balance of the gu<207>as in prak<216>ti and sets in motion the ç
process of evolution.
Since prak<216>ti is ja<195>a (lifeless and devoid ofconsciousness) ç
and the puru<218>a is asa<209>ga (absolutely unattached) how can they ç
ever co-operate in this process of creation? Such co-operation is ç
possible even as a blind man and a lame man can team together to come ç
out of a forest, the blind one carrying the lame person who can now ç
direct him on the right road!
Another  example  given  by  the S<193><209>khyas is that of the spontaneous ç
flow of milk from the udder of the mother cow when its calf is nearby.
The process of evolution from prak<216>ti is as follows: As a result ç
of the gu<207>as mixing with one another, the first evolute coming ç
out of the prak<216>ti is the mahat or the buddhi (the cosmic intellect). ç
From that emerges aha<209>k<193>ra (cosmic ego, the principle of individuation). ç
From the s<193>ttvik part of aha<209>k<193>ra evolve manas (cosmic  mind),  the  five  j<210><193>nendriyas ç
(cosmic organs of knowledge like the eyes and the ears) and the five ç
karmendriyas (cosmic organs of action like the hands and the feet). ç
From the t<193>masik part of aha<209>k<193>ra are produced the five ç
tanm<193>tras (subtle elements of earth, water etc.) and from them, ç
further, evolve the five mah<193>bh<220>tas or gross elements (of ç
earth, water, fire, air and ether).
In all, including the prak<216>ti, there will now be 24 cosmic principles ç
or elements. The rest of creation takes place by their permutation ç
and combination, each puru<218>a getting involved with a psycho-physical ç
complex (body) as per his karma.
@SB = Bondage and Liberation
It is interesting to note here that according to the S<193><209>khyan ç
metaphysics the very purpose of the evolution of the prak<216>ti into ç
this world is to give the puru<218>a one more chance for liberation. ç
Again, it is the same prak<216>ti and its evolute, the world, that ç
binds him once more!
The main cause of bondage of the puru<218>a and his consequent suffering ç
in the world is aviveka (ignorance, non- discrimination between himself ç
as pure consciousness and prak<216>ti which is ja<195>a, the unconscious ç
entity). It is this that is leading him from birth to death, or from ç
life to life ad infinitum.
The question as to how and when he got into this mess can never be ç
answered, except by stating that it is an<193>di (beginningless) but ç
s<193>nta (has an end).
Since aviveka or ignorance is responsible for this bondage, kaivalya ç
or liberation can come only from vivekakhy<193>ti or right knowledge. ç
`Khy<193>ti' means know-ledge (in the sense of direct experience) ç
and `viveka' means separating himself as the puru<218>a, the pure ç
conscious entity, from the prak<216>ti, the insentient matter. This ç
can be attained by following the eight steps of yoga wherein the puru<218>a ç
or the soul is the object of meditation.
The S<193><209>khya Dar·ana accepts two kinds of liberation: j<200>vanmukti ç
and videha-mukti. The former is attained even while living here, the ç
body continuing to live for some more time, till the pr<193>rabdha- ç
karma (the karma that was responsible for starting this life) is exhausted. ç
In this state, the perfect man continues to live in the world, though ç
not of the world.
The final liberation comes after the death of the body†that is why ç
it is called `videhamukti'†and the person will never come back to ç
this mundane world. He will attain the state perfectly free from all ç
pain and suffering, though there is no experience of bliss. However, ç
since caitanya or consciousness is his essence, he will ever remain ç
in his own state.
@NT = S<193><209>khyak<193>rik<193>
The S<193><209>khyadar·ana or the S<193><209>khya philosophy is one ç
of the six systems of Hindu philosophy. (See <MS>S°<177>KHYADAR<185>ANA<D> ç
for details.)
The S<193><209>khyak<193>rik<193> of ®·varak<216><218><207>a (circa ç
<MS>A.<|>D.<D> 350 to 450) is the most important and probably the earliest ç
basic work of this system.
It is in the form of verses, 71 (or 73) in number, all in the <193>ry<193> ç
metre.
There are several Sanskrit commentaries†10 in all†on it, among which ç
the following are more well-known:
@NID = S<193><209>khyak<193>rik<193>bh<193><218>ya by Gau<195>ap<193>da.
@NID = M<193><219>harav<216>tti or M<193><219>harabh<193>·ya.
@NID = Jayama<209>gal<193> by one <185>a<209>kara.
@NID = S<193><209>khyatattvakaumud<200> by<R>ç
            V<193>caspati Mi·ra (<MS>A.<|>D.<D> 850)
@NID = S<193><209>khyacandrik<193> by N<193>r<193>ya<207>a T<200>rtha.
All these commentaries consider theentire work as one unit running ç
continuously. However one commentary has divided it into prakara<207>as ç
and <193>hnikas as follows:
@SPACE = 
@Z_TBL_BEG = COLUMNS(3), DIMENSION(IN), KEEP(OFF), L0(R8C2..R8C3)
@Z_TBL_BODY = CEN, CEN, CEN
Prakara<207>as, °hnikas, K<193>rik<193>s
1, 3, 14
2, 2, 7
3, 3, 24
4, 3, 26
@Z_TBL_BODY = SPACE, SPACE, SPACE
, , 
@Z_TBL_BODY = CEN, CEN, CEN
<MO><+>4<+><D>, <MO><+>11<+><D>, <MO><+>71<+><D>
@Z_TBL_BODY = SPACE, SPACE, SPACE
, , 
@Z_TBL_END = 
A brief summary of the work may now be attempted:
The first k<193>rik<193> is introductory. The second stresses that ç
knowledge (vij<210><193>na) alone gives freedom from suffering.
K<193>rik<193>s 3 to 8 describe the means of getting apavarga (liberation).
K<193>rik<193>s 9 to 14 establish the satk<193>ryav<193>da (See <MS>ASATK°RYAV°DA<D> ç
and <MS>SATK°RYAV°DA<D>.) and describe the avyakta or the pradh<193>na, ç
the vyakta or the manifested products of the avyakta, the three gu<207>as ç
(sattva, rajas and tamas) and the puru<218>a (the soul).
K<193>rik<193>s 15 to 21 deal with the avyakta or prak<216>ti as the ç
original cause, its three gu<207>as as the constituents, multiplicity ç
of the puru<218>as or souls and thatcreation proceeds from their ç
mutual association.
The next group of k<193>rik<193>s, 22 to 45, deals with the evolution ç
of the prak<216>ti into this universe through the 23 cosmic principles ç
and their nature.
The last group, k<193>rik<193>s 46 to 71 (or 73) explain the various ç
pari<207><193>mas or changes of buddhi (intellect), types of creation ç
(which are threefold), the three worlds, role of prak<216>ti in creation ç
(which is only for helping thepuru<218>a or the soul to get liberated), ç
the nature of puru<218>a aseternally free (never subject to any bondage ç
in reality), the importance of tattv<193>bhy<193>sa (repeated study ç
of the funda-mental principles taught till now), liberation and the ç
j<200>vanmukta.
The treatise ends with the narration of the names of the great teachers ç
of this tradition.
See also <MS>®<185>VARAK<184><186>ØA.
@NT = s<193><209>khya-yoga
@N1 = (`yoga of s<193><209>khya [or<R>ç
knowledge]')
The second chapter of the Bhagavad-g<200>t<193> is called S<193><209>khyayoga ç
since it deals with s<193><209>khya (= j<210><193>na) or knowledge ç
of the <193>tman.
Elsewhere (5.5), the words s<193><209>khya and yoga have been used ç
to signify J<210><193>na- yoga and Karmayoga.
The Pr<193><207><193>gnihotra Upani<218>ad 1) uses the word to mean ç
intense thinking.
In the Muktikopani<218>ad (1.16) it means J<210><193>nayoga.
@NT = sa<209>kr<193>nti
See <MS>MAKARA SA<177>KR°NTI.<D>
@NT = Sa<209>k<218>epa-·<193>r<200>raka
@N1 = (`condensed version<R>ç
of Brahmas<220>tras')
Though <185>a<209>kara (<MS>A.<|>D.<D> 788-820) laid a firm foundation ç
of Advaita Ved<193>nta, his works do not deal with all aspects of ç
advaita in detail. This task was ably fulfilled by the post-<185>a<209>kara ç
advaitins, among whom Sarvaj<210><193>tmamuni (<MS>A.<|>D.<D> 900) ç
also was one. He is said to be a disciple of Sure·vara (<MS>A.<|>D.<D> ç
800). Nityabodh<193>c<193>rya seems to be his another name. Sa<209>k<218>epa-·<193>r<200>raka ç
is his magnum opus. Two other treatises†Pa<210>caprakriy<193> and ç
Pram<193><207>a-lak<218>a<207>a†are also attributed to him.
According to another version, he was a disciple of <185>a<209>kara ç
himself and adorned the K<193>mako<219>ip<200><219>ha (now at K<193><210>c<200>puram) ç
†a monastery of advaita tradition, said to have been established by ç
<185>a<209>kara†as its second pontiff.
The Sa<209>k<218>epa·<193>r<200>raka closely follows the  commentary  of  <185>a<209>kara  on  the ç
Brahmas<220>tras.
It is in four chapters, written in verses of different metres, as ç
follows:
@Z_TBL_BEG = COLUMNS(5), DIMENSION(IN), COLWIDTHS(.3333,E1,.2500,.8200,.1942), ç
ABOVE(.0305), BELOW(.0305), VGUTTER(.0278), KEEP(OFF), L1(R5C0..R5C4), ç
L1(R7C0..R7C4), L0(R5C0..R5C1), L0(R7C0..R7C1)
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE ç
TEXT
, First Chapter, †, 563 verses, 
, Second Chapter, †, 248 verses, 
, Third Chapter, †, 365 verses, 
, Fourth Chapter, †, <+>63 verses, 
@Z_TBL_BODY = SPACE, SPACE, SPACE, SPACE, SPACE
, , , , 
@Z_TBL_BODY = TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE TEXT, TABLE ç
TEXT
, Total, †, 1239 verses, 
@Z_TBL_BODY = SPACE, SPACE, SPACE, SPACE, SPACE
, , , , 
@Z_TBL_END = 
The first chapter describes Brahman as the pure and ultimate cause ç
of everything through aj<210><193>na (nescience). This aj<210><193>na ç
rests on the pure self, operates on it as its vi<218>aya or object, ç
covering its essential nature and creating delusory appearances. It ç
is in the su<218>upti or the deep-sleep state that pure bliss, untainted ç
by sorrow, is experienced.
The second chapter further elucidates the doctrines dealt with in ç
the first. There is also a refutation of other schools like S<193><209>khya ç
and Ny<193>ya.
The third chapter deals with the s<193>dhanas, or means of destroying ç
aj<210><193>na and prepare oneself for the knowledge of Brahman. The ç
last chapter describes the nature of emancipation.
There are eight commentaries on thiswork. Of them, the Tattvabodhin<200> ç
of N<216>si<221>h<193>·rama (<MS>A. D.<D> 1500) and the S<193>rasa<209>graha ç
of Madhus<220>dana Sarasvat<200> (<MS>A.<|>D.<D> 1490-1580) are more ç
well-known.
@NT = <186>a<207>mukha
@N1 = (`the six-faced one')
See <MS>SUBRAHMAØYA.
@NT = Sanskrit Language
@SB = Origin
How a language†any language for the  matter†could  attain  the  present ç
degree of sophistication and artistry, starting with a physical sign ç
language and inarticulate babble is a mystery. It is a mystery that ç
linguistics or phonetics or etymology or philology will never be able ç
to solve!
Hinduism, however, has easily `solved' the same by attributing the ç
origin of all languages and sciences to God Himself! An interesting ç
verse in an ancient work called Nandike·varak<193>rik<193> declares ç
that all the alphabets of the Sanskrit language (and hence its grammar) ç
have evolved out of the fourteen sounds made by Lord <185>iva through ç
his <195>amaru (a small drum held in hand for making sounds), at the ç
end of his cosmic dance.
@SB = Two Divisions
Though Sanskrit is called devabh<193><218><193> †the language of the ç
gods in heaven†in practice it is divided into two categories: the  vaidika  (Vedic)  and  the  laukika ç
(secular).
The Vedas, the Ved<193><209>gas, the Upavedas and allied literature ç
belong to the first group. All the other literature †from the itih<193>sas ç
and pur<193><207>as right up to the modern Sanskrit literature†falls ç
under the second group.
@SB = Vedic Literature
The earliest form of Sanskrit is that of the <184>gveda.
According to the orthodox Hindu tradition, the entire body of the ç
Vedic mantras (known as the Sa<221>hit<193>s) was, originally, one ç
mass. The sage K<216><218><207>a Dvaip<193>yana  collected  all  these  Vedic ç
mantras and divided them into four groups as per the needs of sacrificial ç
religion that was in vogue. Hence he was called Vedavy<193>sa or Vy<193>sa. ç
The four groups are: <184>k, Yajus, S<193>ma and Atharva.
In course of time three more sections were gradually added to each ç
of the four Vedas. They are: Br<193>hma<207>a, °ra<207>yaka and Upani<218>ad.
(For details see <MS>VEDAS.<D>)
Since the language of the Vedas was archaic and the concepts were ç
slowly becoming obsolescent, explanatory works became necessary. This ç
resulted in the production of the six Ved<193><209>gas (limbs orsubsidiary ç
works). They are: <185>ik<218><193> (phonetics);   Vy<193>kara<207>a   (grammar); ç
Chandas (prosody); Nirukta (etymology); Jyauti<218>a (astronomy); ç
and, Kalpa (practical method).
The four Upavedas (subsidiary Vedas) viz., °yurveda (health-sciences), ç
Dhanurveda (military science), G<193>ndharvaveda (science of music ç
and fine-arts) and Artha-·<193>stra (political science), are also ç
sometimes included under the Vedic literature.
Various anukrama<207><200>s (works similar to an index) by authors ç
such as <185>aunaka and K<193>ty<193>yana may also be classed under ç
the Vedic literature.
@SB = Itih<193>sas and Pur<193><207>as
The R<193>m<193>ya<207>a of V<193>lm<200>ki and the Mah<193>bh<193>rata ç
of Vy<193>sa are known as the itih<193>sas. They contain ancient history ç
as also plenty of religio-philosophical teachings. (See <MS>MAH°BH°RATA<D> ç
and <MS>R°M°YAØA<D> for details.)
The original basic material of the pur<193><207>as†known as the Pur<193><207>asa<221>hit<193>† ç
is as old as the Vedas. Over the centuries, it gradually took the ç
shape of the present pur<193><207>as and upapur<193><207>as (each ç
group containing eighteen works). (See <MS>PUR°ØAS.<D>) Of these, ç
the Vi<218><207>upur<193><207>a and the Bh<193>ga-vata are considered ç
important.
@SB = Classical Sanskrit Literature
There was a gradual evolution of the Sanskrit language from the archaic ç
form of the Sa<221>hit<193>s to the classical form, first through ç
the Br<193>hma<207>as and then through the epics. This vast and varied ç
literature† both in content and in methodology†may now be summarised ç
very briefly, as follows, arranging them in the English alphabetical ç
order for convenience:
@S10N = ALA<177>K°RAS°HITYA
It is the science of figure of speech. The N<193><219>ya·<193>stra ç
of Bharata (200 <MS>B.<|>C.<D>) seems to be the earliest attempt at ç
systematisation of poetics and dramaturgy. However, it is the well-known ç
authors like Bh<193>maha and Da<207><195>in (6th century <MS>A.<|>D.<D>), ç
°nandavardhana (9th century <MS>A.<|>D.<D>) and Mamma<219>a (11th century ç
<MS>A.<|>D.<D>) who have contributed much to the development of this ç
science. They were also responsible for the evolution of several samprad<193>yas ç
or schools. (See <MS>ALA<177>K°RA<185>°STRA.<D>)
@S10N = CAMP<188>S°HITYA
The camp<220> is a composition in which there is a balanced combination ç
of elegant prose and poetry, each embellishing the other. The Vedic ç
<193>khy<193>nas might have laid the foundation to the later camp<220>-literature.
The extant camp<220>k<193>vyas belong to a period later than the 9th ç
century <MS>A.<|>D.<D>
The following is a list of some of the more well-known works belonging ç
to the camp<220> literature:
Nalacamp<220> of Trivikramabha<219><219>a; Camp<220>r<193>m<193>ya<207>a ç
of Bhoja; Bh<193>gavatacamp<220> by Abhinava K<193>lid<193>sa; N<200>laka<207><219>ha-vijayacamp<220> ç
of N<200>laka<207><219>had<200>k<218>ita; Vi·va- gu<207><193>dar·acamp<220> ç
of Ve<209>ka<219><193>dhvarin.
@S10N = DAR<185>ANA<185>°STRAS
Philosophical schools are known as dar·anas. The three heterodox schools ç
(C<193>rv<193>ka, Jaina and Bauddha) and the six orthodox schools ç
(Ny<193>ya, Vai·e<218>ika, S<193><209>khya, Yoga, M<200>m<193><221>s<193> ç
and Ved<193>nta) as also several others have produced a voluminous ç
literature in the form of s<220>tras and commentaries as also independent ç
works.
It is the Brahmas<220>tras of B<193>dar<193>ya<207>a that has induced ç
the maximum number of works.
@S10N = GADYAS°HITYA
Earliest specimens of available prose go back to the era 3000 <MS>B.<|>C.<D>, ç
the age of the Br<193>hma<207>as. Some of the Upani<218>ads like the ç
Ch<193>ndogya and the B<216>had<193>-ra<207>yaka which are mostly ç
in prose, go back to the same or an even earlier period.
In the s<220>tra-period also we come across prose in the form of the ç
bh<193><218>yas or commentaries, some of which are quite elegant.
Literary prose must have been popular even in ancient times as mentioned ç
by Pata<210>jali in his Mah<193>bh<193>·ya on the A<218><219><193>dhy<193>y<200>. ç
They are the <193>khy<193>yik<193>s (stories)  connected  with  V<193>savadatta, ç
Sumanottara and others.
Depending on the style of writing, these prose works of the literary ç
or classical type are divided into three groups: romances; popular ç
tales; didactic fables.
The following works may be cited as examples of exquisite prose compositions: ç
Da·akum<193>racarita of Da<207><195>in; K<193>dambar<200> of  B<193><207>a;  V<193>savadatta ç
 of  Subandhu; Tilakama<210>jar<200> of Dhanap<193>la; Gadya-cint<193>ma<207><200> ç
of O<195>eyadeva.
@SPACE = 
@S10N = KATH°S°HITYA
@SPACE = 
Sanskrit literature did not lag behind in the creation and propagation ç
of stories. These stories were composed not only to reflect the nature ç
of the contemporary society but also keep some great ideals before ç
it.
Though  the  Vedic  literature  has stories in the form of <193>khy<193>nas, ç
a serious attempt to compile a single volume, only of stories, is ç
first found in the B<216>hatkath<193> in the Pai·<193>c<200> language ç
(a distorted version of Sanskrit). The Kath<193>sarits<193>gara ç
of Somadeva (11th century <MS>A.<|>D.<D>) is said to be a faithful ç
translation of the B<216>hatkath<193>, the original of which is ç
not available. The B<216>hatkath<193>ma<210>jar<200> of K<218>emendra ç
is an earlier attempt of the same type.
The other reputed works in this field are: Pa<210>catantra; Hitopade·a; ç
Vet<193>lapa<210>cavi<221>·ati; Vikramacarita and <185>uka-saptati.
@S10N = K°VYAS°HITYA
Sanskrit literature is replete with k<193>vy<193>s or poetical works ç
of the highest quality. Starting with the R<193>m<193>ya<207>a of ç
V<193>lm<200>ki as the earliest in the series† rightly called the ç
°dik<193>vya†there has been a galaxy of great poets and their works.
A very brief list of their names and some of their works may now be ç
given;
@SPACE1 = 
@SB8.5 = K°LID°SA<P8.5B> <P255M>(100 B.<|>C.)<D>
@NID = <+><+><|>His poetical works are:
@NID = <+><+><|>Kum<193>rasambhava; Meghad<220>ta; Raghu- va<221>·a; ç
<184>tusa<221>h<193>ra. Out of these, the Raghuva<221>·a has forty ç
commentaries, the Sa<210>j<200>vin<200> of Mallin<193>tha being ç
the best.
@SPACE1 = 
@SB8.5 = BH°RAVI<P8.5B> <P255M>(450 A.<|>D.)<D>
Kir<193>t<193>rjun<200>ya is his only work.
@SPACE1 = 
@SB8.5 = BHA<187><187>I<M> (5th century A.<|>D.)<D>
The Bha<219><219>ik<193>vya (also known as R<193>va<207>avadha) ç
is his only work. Along with beautiful poetry, this work tries to ç
make Sanskrit grammar easy for the students of that subject.
@SPACE1 = 
@SB8.5 = M°GHA<P8.5B> <P255M>(A.<|>D. 650)<D>
His magnum opus and the only workis the <185>i·up<193>lavadha. ç
It has eight commentaries out of which the Sandeha-vi<218>au<218>adhi ç
of Vallabha (<MS>A.<|>D.<D> 940) is the best.
@SPACE1 = 
@SB8.5 = K<186>EMENDRA <M>(birth A.<|>D. 1000)<D>
Though nineteen works have been authored by him, mention may be made ç
only of two poetical works: R<193>m<193>ya<207>a-ma<210>jar<200> ç
and Bh<193>ratama<210>jar<200>. These are brief works but elegant.
@SB8.5 = <185>R®HAR<186>A<P8.5B> <P255M>(12th century A.<|>D.)<D>
@SPACE1 = 
Out of his nine works, the Nai<218>a-dh<200>yacarita dealing with ç
the story of Nala and Damayant<200> is considered the best.
He also wrote a highly polemical work on Advaita Ved<193>nta called ç
Kha<207><195>ana-kha<207><195>a-kh<193>dya, which reflects his erudition ç
in that branch.
@SPACE = 
@SB8.5 = VED°NTA DE<185>IKA<P8.5B> <P255M>(A.<|>D. 1268-1369)
@SPACE1 = 
Though well-known as a prolific and scholarly writer on Vi·i<218><219><193>dvaita ç
Ved<193>nta, Ved<193>nta De·ika was also a great litterateur. Special ç
mention should be made of his two works: Y<193>dav<193>bhyudaya ç
and Ha<221>sasande·a. The former contains the story of K<216><218><207>a ç
whereas the latter deals with that of R<193>ma and S<200>t<193>, especially ç
the sorrow of their separation.
@SPACE = 
@S10N = N°<187>AKAS°HITYA
@SPACE1 = 
There is enough evidence†like the Sa<221>v<193>das<220>ktas of the ç
<184>gveda†to prove that n<193><219>akas or dramas have existed ç
since the most ancient times. The epics contain references to dances, ç
dramas and theatres.
Bharata's  Na<219>ya·<193>stra  was  the earliest treatise on dramaturgy.
Now, a list of well-known authors of n<193><219>akas and their works ç
may be given:
@SPACE = 
@SB8.5 = BH°SA
@SPACE1 = 
Earliest of the playwrights, Bh<193>sa might have lived during the ç
period 500 to 400 <MS>B.C.<D>
The dramas attributed to him are thirteen. Out of these mention may ç
be made of the following: Pratim<193>n<193><219>aka; Pratij<210><193>yaugandhar<193>ya<207>a ç
and Svapna-v<193>savadatta.
@SB8.5 = K°LID°SA<P8.5B> <P255M>(100 B.<|>C.)<D>
The three well-known dramas of K<193>lid<193>sa are: M<193>lavik<193>gnimitra; ç
Vikramorva·<200>ya and Abhij<210><193>na·<193>kuntala.
The last has been considered the very best of all Sanskrit dramas. ç
It is woven round the love between the king Du<218>yanta and the damsel ç
<185>akuntal<193> of divine beauty.
@SB8.5 = VI<185>°KHADATTA<P8.5B> <P255M>(7th century A.<|>D.)<D>
The Mudr<193>r<193>k<218>asa is his magnum opus though two more ç
dramas were composed by him.
How C<193><207>akya, the famous kingmaker and  prime-minister  of  Candragupta ç
Maurya won over R<193>k<218>asa, the loyal premier of the Nandas and ç
made him agree to be the prime-minister of Candragupta Maurya is the ç
main theme of this work.
@SB8.5 = <185><188>DRAKA<P8.5B> <P255M>(5th century A.<|>D.)<D>
<185><220>draka was perhaps a king. Hisonly work is the M<216>cchaka<219>ik<193> ç
(`the mud-cart'). It is in ten acts and concerns mainly with the story ç
of love between Vasantasen<193> (a prostitute of high culture) and ç
C<193>rudatta a decent br<193>hma<207>a of noble character.
The drama is replete with Pr<193>k<216>t words also.
@SB8.5 = <185>R®HAR<186>HA or HAR<186>AVARDHANA
The well-known emperor <185>r<200>har<218>a or Har<218>avardhana ruled ç
at Sth<193><207>e·vara from <MS>A.<|>D.<D> 606 to 647. He was not only ç
a great king but also an erudite author.
Ratn<193>val<200>, N<193>g<193>nanda and Priya-dar·ik<193> are ç
the three dramas authored by him.
@SB8.5 = BHA<187><187>AN°R°YAØA<P8.5B> <P255M>(7th century A.<|>D.)<D>
The Ve<207><200>sa<221>h<193>ra, a six-act play drawing its material ç
from the Mah<193>bh<193>rata, is his only work. Bh<200>ma's character  has  been  highlighted  and ç
represented ably.
@SB8.5 = BHAVABH<188>TI<P8.5B> <P255M>(8th century A.<|>D.)<D>
He is considered almost equal to K<193>lid<193>sa as to the qualities ç
of his dramas which are three: M<193>lat<200>m<193>dhava; Mah<193>v<200>racarita ç
and Uttarar<193>m<193>ya<207>a. He was also well-versed in the philosophical ç
lore.
It is the last, in seven acts, that is more famous. It draws the story ç
from the Uttarak<193><207><195>a of the R<193>m<193>ya<207>a making ç
some interesting changes in the original story to enhance the literary ç
grace of the work.
Apart from these, there have been a few more less-known playwrights ç
such as Mur<193>ri (8th century <MS>A.<|>D.<D>; Anarghya-r<193>ghava), ç
R<193>ja·ekhara (circa <MS>A.<|>D.<D> 900; B<193>lar<193>m<193>ya<207>a, ç
B<193>labh<193>rata and Karp<220>ra-ma<210>jar<200>), <185>aktibhadra ç
(9th century <MS>A.<|>D.<D>; °·caryac<220>d<193>ma<207><200>) and ç
Jayadeva (13th century <MS>A.<|>D.<D>; Prasannar<193>ghava).
@S10N = NIGHAØ<187>U
Nigha<207><219>u means a dictionary. The first ever dictionary in ç
Sanskrit is the Nigha<207><219>u, an ancient dictionary of Vedic ç
words by an unknown author. The Nirukta of Y<193>ska (800 <MS>B.<|>C.<D>) ç
is a commentary on this Nigha<207><219>u.
Till now 87 Sanskrit dictionaries have been traced and found to have ç
existed. Only, very few of them have been printed so far.
The N<193>mali<209>g<193>nu·<193>sanam of Amara Si<221>ha (<MS>A.<|>D.<D> ç
500), more popularly known as the Amarako·a, is the best of Sanskrit ç
dictionaries. It has 38 commentaries. (See <MS>AMARAKO<185>A<D> for ç
details.)
Some of the other dictionaries worth mentioning are: Li<209>g<193>nu·<193>sana ç
of Vy<193><195>i; Trik<193><207><195>ako·a of Bh<193>guri; <185>abd<193>r<207>ava ç
of V<193>caspati; H<193>r<193>val<200> of Puru<218>ottamadeva; Abhidh<193>naratnam<193>l<193> ç
or Hal<193>yudhako·a ofHal<193>yudha; N<193>n<193>rtha·abdako·a ç
or Medin<200>ko·a of Medin<200>kara; Kalpadruma-ko·a of Ke·ava; ç
<185>abdakalpadruma of R<193>dh<193>k<193>ntadeva; V<193>caspatya ç
of T<193>r<193>-n<193>tha-tarka-v<193>caspati and N<193>n<193>rth<193>r-<207>avasa<209>k<218>epa ç
of Ke·avasv<193>min.
@S10N = PUR°ØAS°HITYA
Starting with the <193>khy<193>yik<193>s or stories carried over from ç
the ancient (pre-Vedic) days, the pur<193><207>a literature has now ç
grown into a huge mass comprising the  eighteen  Mah<193>pur<193><207>as  and  the ç
eighteen (or even more) Upapur<193><207>as. (See <MS>PUR°ØAS<D> for ç
details.)
@S10N = STOTRAS°HITYA
The stotras<193>hitya or hymnal literature in Sanskrit is almost limitless. ç
Greatmystics and devotee-poets, in their moments of divine ecstasy ç
have burst forthinto innumerable hymns. These hymns are in various ç
poetical metres and contain a variety of feelings and descriptions. ç
They are addressed to the different deities of the Hindu pantheon ç
such as <185>iva, Dev<200>, Vi<218><207>u, Ga<207>apati, Subrahma<207>ya ç
and others.
Mention may now be made of a smallfraction of these hymns. They are:<185>ivamahimnastotra ç
of Pu<218>padanta; Saundaryalahar<200> of <185>a<209>kara; Mukunda-m<193>l<193> ç
of Kula·ekhara; Stotraratna of Y<193>muna; K<216><218><207>akar<207><193>m<216>ta ç
 of  L<200>l<193>·uka;  P<193>duk<193>sahasra  of  Ved<193>nta  De·ika;  Lak<218>m<200>sahasra ç
of Ve<209>ka<219><193>dhvari; N<193>r<193>ya-<207><200>yam of N<193>r<193>ya<207>a ç
Bha<219><219>atiri; Dv<193>da·a-stotra of Madhva; M<220>kapa<210>ca·at<200> ç
of M<220>kakavi; and, °nandas<193>garastava of N<200>laka<207><219>had<200>k<218>ita.
Apart from this, the epics and the pur<193><207>as too contain a legion ç
of exquisitely beautiful hymns, some of which like the Vi<218><207>usahasran<193>ma, ç
the Lalit<193>sahasra-n<193>ma, the °dityah<216>daya and the Durg<193>-sapta·at<200> ç
have acquired the status of potent  mantras.  They  are  extremely ç
popular even now.
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@SPACE1 = 
@S10N = S<188>KTIS°HITYA
@SPACE1 = 
A s<220>kti or a subh<193><218>ita (= good-saying; wise statement) ç
is like a popular maxim or proverb. It contains the quintessence of  the  experience  of  a  whole  race ç
over several generations. The Sanskrit language is full of such sayings. ç
They are found interspersed almost in every branch of the literature.
However, several scholars have made serious attempts to bring these ç
sayings together in an organised manner.
The following is the list of some of the better-known compilations: ç
Subh<193><218>ita-ratnako·a of Vidy<193>dhara; Subh<193><218>it<193>val<200> ç
ofVallabhadeva; Saduktikar<207><193>m<216>ta of <185>r<200>dharad<193>sa; ç
<185><193>r<209>gadharapaddhati of <185><193>r<209>gadhara; Subh<193><218>itaratnabh<193><207><195><193>g<193>ra ç
of K<193>·<200>n<193>tha·arma; Subh<193><218>itasudh<193>nidhi of ç
S<193>ya<207>a and, Subh<193><218>itan<200>v<200> by Ved<193>nta ç
De·ika.
@SPACE1 = 
@SPACE1 = 
@S10N = UPADE<185>AS°HITYA
@SPACE1 = 
 Seeing the abominable deterioration
