@NID = of the moral standards in the society of their times, quite ç
a few poets of the middle ages wrote works in a scintillating style ç
which not only described the things as they were, but also as they ç
should be. Such works may be classified as upade·as<193>hitya.
A few such works may be mentioned here: Ku<219><219>an<200>mata ç
of Damodaragupta; Kal<193>vil<193>sa  of  K<218>emendra;  D<216><218><219><193>nta- ç
kalik<193>·atakam  of  Kusumadeva;  Kali- vi<195>ambana of N<200>lakan<219>had<200>k<218>ita; ç
Anyokti-mukt<193>lat<193> of <185>ambhu; and, Bh<193>vavil<193>sa ç
of Rudrakavi.
@S10N = VY°KARAØS°HITYA
The earliest references to Sanskrit grammar are found in the Gopatha ç
Br<193>hma<207>a (1.24) and the Taittir<200>ya Sa<221>hit<193> ç
(6.4.7). Even though P<193><207>ini (500<MS>B.<|>C.<D>) was the most ç
brilliant of the grammarians and his A<218><219><193>dhy<193>y<200> ç
eclipsed the earlier works, he does refer to a number of his predecessors ç
such as °pi·ali, K<193>·yapa, G<193>rgya, G<193>lava, Bh<193>radv<193>ja, ç
<185><193>ka<219><193>yana and <185><193>kalya.
(See <MS>A<186><187>°DHY°Y®<D> and <MS>P°ØINI.<D>)
Many schools of grammar appeared in the post-P<193><207>inian period. ç
However, of the six such schools, the one based on the Sarasvat<200>ka<207><219>h<193>bhara<207>a ç
of the Param<193>ra king Bhoja (11th century <MS>A.<|>D.<D>) became ç
the most extensively used.
Mention may also be made of the following works: Sa<209>k<218>iptas<193>ra ç
of Krama-d<200>·vara;  Mugdhabodha  of  Bopadeva; Supadmavy<193>kara<207>a ç
of Padmanabha; and, S<193>rasvatavy<193>kara<207>a of Narendr<193>c<193>rya.
@SB = Conclusion
The Sanskrit language has been the repository of India's history, ç
culture, reli-gion, sciences and socio-political values for several ç
millennia. It is in the best interest of Indians to learn it, preserve ç
it and propagate it. It is highly gratifying to note that several ç
countries of the world†both in the east and in the west†are encouraging ç
a study and research of Sanskrit through their centres of learning. ç
It is but meet to declare that India, the motherland of Sanskrit, ç
should in no way lag behind!
@NT = ·<193>ntabh<193>va
@N1 = (`attitude of serenity')
See <MS>BHAKTI.<D>
@NT = Sant<193>nagop<193>la
After completing his Vedic studies under  his  teacher  S<193>nd<200>pani,  K<216><218><207>a ç
requested him to accept some gurudak<218>i<207>a. Then S<193>nd<200>pani, ç
knowing fully well of K<216><218><207>a's divinity, requested him ç
to bring back his dead son alive, who had been drowned at the Prabh<193>sa, ç
the famous pilgrimage centre on the sea-shore (in Gujarat near the ç
Soman<193>tha temple). K<216><218><207>a did it by killing the demon ç
Pa<210>cajana and bringing back the boy from the world of Yama, the ç
god of death.
This aspect of K<216><218><207>a is known as Sant<193>nagop<193>la.   Iconographical   works ç
describe him as four-armed, carrying ·a<209>kha (conch), cakra (discus), ç
gad<193> (mace) and padma (lotus), wearing yellow silken garments  and  adorned  with  peacock ç
feathers. He is surrounded by cows, calves and cowherds.
See also <MS>S°ND®PANI.<D>
@NT = s<193>ntapana
@N1 = (`[that which causes] great hardship')
Pr<193>ya·cittas or expiations for sins is a common feature of practical ç
Hinduism. One such is s<193>ntapana. It is prescribed for one who ç
commits a sin that makes him lose his caste (j<193>tibhra<221>·akara), ç
knowingly. It consists in subsisting on the pa<210>cagavya mixed with ç
water in which ku·a grass is soaked (See <MS>PA<178>CAGAVYA<D> for ç
details.) on the first day and fasting completely on the second day.
Two varieties of this expiation are also described: atis<193>ntapana ç
and mah<193>s<193>ntapana.
In the latter, the sinner has to subsist on the six items (cow's milk, ç
curds, ghee, urine and dung as also water of ku·a grass) individually ç
for each day for six days and fast on the seventh.
In atis<193>ntapana, the duration is trebled; i.e., milk for three ç
days and so on.
See also <MS>PR°YA<185>CITTA.<D>
@SPACE = 
@NT = ·<193>nt<193>t<200>ya-mantra
@SPACE = 
Several religious rites are performed while entering a newly-built ç
house. One such rite consists in making the house ·<193>nta (peaceful ç
to live in).
In a vessel of water a little rice, barley and a piece of gold are ç
deposited. The priest goes round the house three times from left to ç
right, sprinkling the water on the house with the ·<193>nt<193>t<200>ya ç
mantras.
These are the fifteen mantras of the <184>gveda (7.35.1-15). Since ç
the word ·am (peace) occurs several times in it, the mantra itself ç
is called ·<193>nt<193>t<200>ya. Several deities like Indra, Agni, ç
Varu<207>a, P<220><218>an, Bhaga, Aryam<193>, Dh<193>t<193>, Mitra, ç
Vasus, Rudra,  S<220>rya,  Aditi  and  others  are addressed to bestow ç
peace.
@NT = <185><193>ntiparva
This is the twelfth book of the Mah<193>bh<193>rata.
See <MS>MAH°BH°RATA.<D>
@SPACE = 
@NT = <185><193>ntis
@N1 = (`propitiatory rites')
@SB = Introduction
It is but natural for human beings to react with the fear of the unknown ç
when eerie unnatural incidents take place. Right from the most ancient ç
times they have also tried to forestall such happenings that might ç
follow, with appropriate propitiatory rites†called ·<193>ntis by the ç
Hindu scriptures†in advance. Derived from the root ·am (= to appease), ç
the word ·<193>nti means a rite that can offset or reduce the evil ç
effects prognosticated by bad omens.
Though this word has not been found in the <184>gveda in this sense, ç
it does find a prominent place in the Atharvaveda (19.9), the Taittir<200>ya ç
Sa<221>hit<193> (6.1.7.7-8) and the Aitareya Br<193>hma<207>a (13.10).
@SPACE = 
@SB = Literature on the <185><193>ntis
The literature on the ·<193>ntis is quite large.<|>A few of the works ç
may be mentioned here: Kau·ikas<220>tras; °pastamba G<216>hyas<220>tras; ç
Matsyapur<193><207>a; M<193>rka<207><195>eya-pur<193><207>a; Agnipur<193><207>a; ç
Vi<218><207>udharmottara-pur<193><207>a; B<216>hatsa<221>hit<193>; ç
Adbhutas<193>gara; and <185><193>ntikamal<193>kara.
These works have dealt with the ·<193>nti<W1%26>s<D%0>in all their ç
aspects quite extensively.
@SPACE = 
@SB = Adbhuta, Utp<193>ta and Nimitta
The treatises dealing with ·<193>ntis generally   use   three   words   that ç
prognosticate future events. They are: adbhuta, utp<193>ta and nimitta.
Adbhuta refers to any occurrence which has not happened before, or, ç
a total change coming over what has happened earlier.
The adbhutas are divided into seven groups relating to the deities ç
Indra, Varu<207>a, Yama, Agni, Kubera, Vi<218><207>u and V<193>yu. ç
When some adbhutas take place as related to these deities, certain ç
·<193>ntis are prescribed. For instance, when a rainbow is seen at ç
night, Indra is the god to be appeased. If there is smoke without ç
fire, the deity is Agni. The ·<193>nti consists inthejapa of certain ç
mantras of the Atharvaveda.
The word utp<193>ta refers to occurrences that portend evil to all. ç
It is the reverse of the usual natural order.
Nimitta, on the other hand, is a prognostic sign which may indicate ç
either an auspicious or an inauspicious event. Generally, it is restricted ç
to the throbbing of a person's limbs, though it may be used in a wider ç
sense (as utp<193>ta) also.
Examples of utp<193>tas and nimittas† usually unfavourable†occur plentifully ç
in the Mah<193>bh<193>rata.
@SPACE1 = 
The chief utp<193>tas and adbhutas foreboding evil are: terrible dreams; ç
falling of meteors; howling of jackals facing south; sand-showers; ç
earthquakes; solar eclipse at an unusual time. Vultures sitting on ç
temples; spontaneous fires; halos round the sun or the moon; rain ç
of bloodred water; sudden darkness in the sky; horses shedding tears; ç
rivers flowing in the reverse direction; throbbing of left eye or ç
arm (in men); images of gods trembling, dancing or weeping.
On the other hand, the auspicious signs are: clear and cloudless sky; ç
cool and pleasant wind; fire without smoke; shower of flowers; auspicious ç
birds like herons and peacocks chirping and so on.
Such omens and portents are generally described as occurring at certain ç
important times and events as on the eve of a battle or coronation ç
or exile of a king and so on.
@SB = <185><193>ntis<M> (general)<D>
The pur<193><207>as like the Matsya and the Agni prescribe different ç
·<193>ntis (of different names) for various purposes. Some of them ç
are: abhaya·<193>nti for a king who wants to conquer others or protect ç
himself against the machinations of the enemies; saumya-·<193>nti ç
for health; vai<218><207>av<200>·<193>nti to offset the effects of ç
an earthquake or famine; raudr<200>·<193>nti against epidemics or ç
ghosts; br<193>hm<200>·<193>nti against the spread of atheism; v<193>ru<207><200>·<193>nti ç
against drought; kaum<193>r<200>·<193>nti for the welfare of children; ç
<193>gney<200>·<193>nti to ward off the fear of fire-accidents; y<193>mya·<193>nti ç
when there is the fear of accidental death; kauber<200>·<193>nti when ç
wealth is lost and p<193>rthiv<200>·<193>nti when trees are affected ç
by abnormal conditions.
@SB = Some Special <185><193>ntis
@S10N = GAJA<185>°NTI
Gaja·<193>nti is of two types. The first one, with a simple procedure, ç
is done to restore a sick elephant to health.
The second one described in detail in the Agnipur<193><207>a (Chapter ç
291) is aimed at making the royal elephant strong, powerful and inspired ç
so that it protects the king in a battle.
@S10N = MAH°<185>°NTI
This is performed to offset the effects of mishaps indicated by such ç
occurrence as the falling of meteors or to facilitate the coronation ç
of a king or his victory in a battle and so on.
A yaj<210>a is performed on a raised platform using mostly mantras ç
from the <184>gveda. The yajam<193>na takes a ceremonial bath at ç
the end. Holy water used in the rite is sprinkled over him.
@S10N = NAVAGRAHA<185>°NTI
Navagraha·<193>nti, also called Navagrahamakha, is performed to the ç
images of the nine planets made out of nine different kinds of materials. ç
It is meant to offset the evil effects of the planets.
The ayutahoma, lak<218>ahoma and ko<219>ihoma are its three aspects.
The mantras used are those from the <184>gveda and the Yajurveda.
@S10N = PU<186>YASN°NA
Also known as pu<218>y<193>bhi<218>eka or b<193>rhaspatyasn<193>na, ç
this rite is reserved for the well-being of kings.
P<220>r<207>im<193> (full-moon day) associated with the Pu<218>ya ç
nak<218>atra is the best day for the performance of this ·<193>nti.
Some of the more important steps of this rite are as follows:
Selecting a suitable spot for the performance of this rite; drawing ç
a ma<207><195>ala (geometrical diagram of mystical significance); ç
keeping the various articles on it at appropriate places; homa with ç
special oblations into the fire; sprinkling clarified butter and holy ç
water on the king seated nearby, with mantras; release of prisoners ç
and animals meant for slaughter.
@S10N = <186>A<186><187>YABDAP<188>RTI<185>°NTI
Also called Ugraratha·<193>nti, it has to be performed by one who ç
has completed sixty years of age. Its aim is to ward off diseases ç
and death and make him live up to a hundred years.
It should be performed in the month of his birth and on the day associated ç
with the nak<218>atra of his birth.
Worship of a small golden image of M<216>tyu (= Death; Yama), japa ç
of certain Vedic mantras (eg., Taittir<200>ya Br<193>hma<207>a 3.7.14.4; ç
<184>gveda 7.59.12), oblations of cooked food with appropriate mantras ç
and sprinkling the yajam<193>na with holy water from the established ç
jars†these are some of the steps involved in the rite.
@S10N = TRIKAPRASAVA<185>°NTI
The birth of a girl after three successive births of boys or of a ç
boy afterthree successive births of girls, was supposed to indicate ç
harm to the family like a death or loss of wealth or some other catastrophe. ç
The Trikaprasava·<193>nti, to be performed at the earliest on an auspicious ç
day was aimed at offsetting the evil consequences. Worship to the ç
golden images of Brahm<193>, Vi<218><207>u, <185>iva and Indra and ç
homa with mantras from the <184>gveda (1.22.17) and the Taittir<200>ya ç
Sa<221>hit<193> (4.2.8.2) were recommended. Donating a cow apart ç
from the usual dak<218>i<207><193> to the chief priest was the last ç
part of the rite.
@S10N = UDAKA<185>°NTI
This is a comprehensive and popular rite which is practised even now. ç
It is performed for averting the consequences of many evil happenings ç
as also for securing good health and a happy life.
It is an elaborate ritual involving many Vedic mantras, both from ç
the Sa<221>hit<193>s and the Br<193>hma<207>as.
The date for the performance of the ·<193>nti is determined by the ç
nak<218>atra (star) of the yajam<193>na or the performer in his horoscope. ç
The chief priest is generally assisted by an even number of br<193>hma<207>as. ç
The ·<193>ntijala (propitiatory water) is prepared by him by dipping ç
two ku·a grass blades in the kumbha (pot of water) and chanting the ç
appropriate mantras. At the end, the sanctified water is sprinkled ç
over the performer and others (for whose sake it may have been performed).
@SPACE = 
@S10N = V°STU<185>°NTI
@SPACE = 
This ·<193>nti which is performed even in the modern days, has to ç
be done on the same day or the previous day of g<216>haprave·a (formal ç
entering into a newly-built house, by the yajam<193>na or owner). ç
The actual day has to be fixed as per the nak<218>atra (birth-star) ç
of the owner. Graha-makha (a rite for propitiating the nine grahas ç
or planets), and the usual rites of worship of Ga<207>e·a are part ç
of this ·<193>nti.
A ma<207><195>ala (mystical diagram) of 81 squares is drawn and 62 ç
deities are invoked to be present.
Sprinkling of water made holy by appropriate mantras, surrounding ç
the new building thrice with a thread to the accompaniment of suitable ç
mantras from the <184>gveda (4.4.1-15; 9.1.1-10), digging a pit ç
in the <193>gneya or the south-east corner and filling it with seven ç
sacred articles and the ceremonial entry into the house by the owner ç
along with his family†these are some of the items of this rite.
@SB = Epilogue
Though what cannot be cured will have to be endured, invoking the ç
grace of the Divine will definitely help in reducing, if not eliminating, ç
the effects of unforeseen mishaps. It is this spirit that is at the ç
back of the various ·<193>ntis prescribed by the Hindu scriptures. ç
That these rites are still being resorted to is proof enough for their ç
efficacy.
@NT = <185><193>ntis<220>ktas
@EMERGENCY = When some unnatural or supernatural phenomena take place, ç
foreboding some evil, remedial measures have to be undertaken. These ç
are generally termed ·<193>ntis. (See <MS><185>°NTIS<D> for details.)
@EMERGENCY = Even in some early Vedic mantras we find the idea of ç
counteracting the evil effects of bad dreams (vide <184>gveda 10.164.1-5; ç
8.47.16-18; 10.36.4; 10.37.4).
@EMERGENCY = The <185><193><209>kh<193>yana-g<216>hyas<220>tras ç
(5.6, 7,  10, 11) prescribes the <184>gvedic s<220>kta (1.114 with ç
11 verses) for curing a person suffering from any disease.
@EMERGENCY = In the Taittir<200>ya °ra<207>yaka (4.42) there are ç
37 mantras of ·<193>nti, of which 7 are from the <184>gveda.
@EMERGENCY = Several verses of the Atharvaveda (6.45.1; 6.46.1) ç
also are prescribed for similar purposes.
@EMERGENCY = The entire chapter 36 of the <185>ukla-yajurveda Sa<221>hit<193> ç
comprising 24 mantras is used as ·<193>nti during the Pravargya rite ç
(See <MS>PRAVARGYA<D>.).
@EMERGENCY = Such Vedic mantras are called <185><193>nti-s<220>ktas.
@NT = santo<218>a
@N1 = (`happiness', `contentment')
The Yogas<220>tras (2.32) of Pata<210>jali (200 <MS>B.<|>C.<D>) describes ç
santo<218>a as a part of the second step of yoga, viz., niyama. It ç
is defined as being contented with whatever one gets and not desiring ç
for more.
@NT = ·apatha
@N1 = (`special oath')
In the ancient days, when a king could not decide whether a person ç
brought before him as guilty was really guilty or not, due to lack ç
of direct or circumstantial evidence, he could take to two methods; ç
divya (divine proof through ordeals) and ·apatha (oath). (See <MS>DIVYA<D> ç
for its details.)
A ·apatha is actually an oath taken by the accused to prove his innocence. ç
Instances of ·apathas are found in the <184>gveda (7.104.15,<|>16), ç
the epics (Mah<193>-bh<193>rata, Anu·<193>sanaparva 95.13-35) ç
and the sm<216>tis.
For example, Vasi<218><219>ha when accused, declares in the <184>gveda ç
(7.104.15, 16), `If I am a y<193>tudh<193>na (sorcerer), may I die ç
this very day!' This is a ·apatha.
The king in such cases of ·apathas had to wait for a week or the stipulated ç
period, whichever is less, to know the result.
@NT = sapi<207><195>a
@N1 = (`of the same body')
The Hindu dharma·<193>stras have stipulated many conditions for the ç
marriage of a boy with a girl, both of marriageable age. One important ç
rule in this series is that they should not be sapi<207><195>a.
Sapi<207><195>a literally means having the same body-particles. For ç
instance, a father and a son or a daughter, are sapi<207><195>a since ç
the particles of the body of the father exist in the bodies of both.
This sapi<207><195>a relationship extends up to seven generations ç
in the lineage of the father and up to five generations in the lineage ç
of the mother. Marriage within this sapi<207><195>a relationship is ç
prohibited.
See also <MS>GOTRA<D> and <MS>SAGOTRA<D>.
@NT = sapi<207><195><200>kara<207>a
@N1 = (`grouping together')
Sapi<207><195><200>kara<207>a (or sapi<207><195>ana) is the reception ç
of the dead person's soul into the community of the pit<216>s or forefathers.
The process is actually a ·r<193>ddha (obsequial rite) and can be ç
done on any of the following days after death: 12th day; 4th month; ç
6th month; 11th month; or after a year.
The first seems to be more common.
The important steps are: invitation to the br<193>hma<207>as the previous ç
day; agnau- kara<207>a (See <MS>AGNAUKARAØA<D> for details.); recital ç
of Vedic texts when the br<193>hma<207>as are eating; keeping four ç
vessels of water with ku·a grass (one for the dead ancestor [called ç
preta now] and the other three for the pit<216>s) and mixing the water ç
of the first with the water of the other three with appropriate mantras. ç
This completes the process of merging the preta with the pit<216>s ç
of pit<216>loka.
@NT = saptabh<220>mik<193>s
@N1-1 = (`seven stages [of ascent'}
The tantras describe seven bh<220>mik<193>s or <193>c<193>ras†gradually ç
increasing stages or steps†by which a spiritual aspirant rises to ç
the highest level of spiritual illumination. They are: veda, vai<218><207>ava, ç
·aiva, dak<218>i<207>a, v<193>ma, siddh<193>nta and kaula. They are ç
also termed as ved<193>c<193>ra, vai<218><207>av<193>c<193>ra and ç
so on.
Veda is the daily practice of the religious rites prescribed by the ç
scriptures in accordance with the Vedas.
Vai<218><207>ava is the cultivation of devotion to God.
<185>aiva is adding j<210><193>na or knowledge also to the s<193>dhana ç
or spiritual practice.
Dak<218>i<207>a is the fourth stage wherein the gains of the first ç
three stages are consolidated by meditation on the three aspects of ç
<185>akti or the Divine Mother viz., Sarasvat<200>, Lak<218>m<200> ç
and P<193>rvat<200>.
V<193>ma, the fifth stage is that of niv<216>tti or renunciation.
Siddh<193>nta is the sixth stage in which the aspirant comes to definite ç
conclusions about the relative merits of the two paths of prav<216>tti ç
(activism, enjoyment) and niv<216>tti (withdrawal, renunciation), ç
and, decides to pursue the latter path.
Kaula, the last stage, is the state of realisation of Kula or Brahman.
@NT = saptadv<200>pas
@N1 = (`the seven islands')
The geography of this earth as described in the pur<193><207>as is†though ç
enigmatic†interesting.
Originally the whole earth was one landmass. The sun was traversing ç
always on one side of it leaving the other side eternally dark. So, ç
the great king Priya-vrata (considered an incarnation of Vi<218><207>u, ç
who established organised human dwellings for the first time) drove ç
his chariot round on earth, in seven concentric circles, thus creating ç
seven dv<200>pas or islands and seven samudras or oceans. The following ç
are the details:
@SB = 1.	Jamb<220>dv<200>pa
This is the first of the seven islands and is spread round the mountain ç
Meru which is the axis. It is surrounded by the lava<207>asamudra, ç
the ocean of salt-water.
°gn<200>dhra, the eldest son of Priyavrata was its first ruler.
He later on divided it into nine kha<207><195>as or parts or continents ç
and gave it to his nine sons. These came to be known as var<218>as ç
in their names such as Ajan<193>bhavar<218>a, Kimpuru<218>avar<218>a, ç
Harivar<218>a and so on.
@SB = 2.	Plak<218>adv<200>pa
Second of the seven islands, it is surrounded by the ik<218>usamudra, ç
the ocean of sugarcane juice.
Idhmajihva, the second son of Priya-vrata, was its first king.
@SB = 3.	<185><193>lmal<200>dv<200>pa
This is the third island, surrounded by sur<193>samudra, the ocean ç
of wine.
The first ruler was Yaj<210>ab<193>hu.
@SB = 4.	Ku·adv<200>pa
This is the fourth of the seven islands and is surrounded by gh<216>tasamudra, ç
the ocean of ghee. Hira<207>yaretas was its first monarch.
@SB = 5.	Krau<210>cadv<200>pa
This island, surrounded by the sea of curds, was ruled by Gh<216>tap<216><218><219>ha ç
the fifth son of Priyavrata.
@SB = 6.	<185><193>kadv<200>pa
Encircled by the sea of milk, <185><193>ka-dv<200>pa, the sixth island, ç
was administered by Medh<193>tithi.
@SB = 7.	Pu<218>karadv<200>pa
Surrounded by the ocean of pure water, this island had V<200>tihotra ç
as its first king.
These  seven  islands  have  been identified by Indologists as follows: ç
Jamb<220>dv<200>pa = Asia; Plak<218>adv<200>pa = South America; <185><193>lmal<200>dv<200>pa ç
= Australia; Ku·a-dv<200>pa = Oceania; Krau<210>cadv<200>pa = Africa; ç
<185><193>kadv<200>pa (not identified); Pu<218>karadv<200>pa= North ç
America.
@NT = saptaj<210><193>nabh<220>mik<193>
@N1-1 = (`seven preparatory stages for attaining knowledge')
The  Var<193>ha  Upani<218>ad  (4.2.1-17) describes seven bh<220>mik<193>s ç
or preparatory stages for obtaining knowledge. They are as follows:
@SPACE = 
@S10N = 1.	<185>ubhecch<193> (= sincere desire)
This is the sincere desire that arises in the mind of a seeker, as ç
a result of the study of the ·<193>stras (scriptures) and company ç
of the holy, to know his real nature.
@SPACE1 = 
@S10N = 2.	Vic<193>ra<207><193> (= enquiry)
The enquiry (born out of ·ubhecch<193>) that leads the seeker to be ç
inclined towards good conduct is vic<193>ra<207><193>.
@SPACE1 = 
@S10N = 3.	Tanum<193>nas<200> (=<|>attenuation of the mind)
The first two stages when practised well, make the mind (= m<193>nasa), ç
thin or attenuated (= tanu). Such a mind will not get attached to ç
sense-objects.
@SPACE1 = 
@S10N = 4.	Sattv<193>patti (= attaining sattva)
This is the state of being established †though indirectly†in the <193>tman ç
(the individual Self), who is sattva (the pure, the real). This is ç
attained as a result of practising the earlier three stages.
@SPACE1 = 
@S10N = 5.	Asa<221>sakti (= non-attachment)
In this state the s<193>dhaka is completely unattached to experiences ç
that come in life whether good or bad,
@S10N = 6.	Padarthabh<193>van<193> (= becoming aware of<R>ç
	objects [through others])
When the seeker reaches this state, he is not aware of pad<193>rthas ç
or objects (whether they are inside or outside himself) and has to ç
be made aware of them by others. The reason is that his mind is always ç
dwelling on his Self.
@S10N = 7.	Turyag<193> (= entering into the `fourth', <R>ç
                       i.e., the <193>tman)
In this final state, the seeker's consciousness transcends all duality ç
and is well-established in the <193>tman or the Self.
It should be noted that each stage leads to the next, if practised ç
properly.
@NT = Saptam<193>t<216>k<193>s
@N1 = (`seven goddesses')
According to the Durg<193>sapta·at<200>, one of the basic texts ç
on the Mother-cult, when Kau·ik<200> Durg<193> was fighting the demon ç
Raktab<200>ja†whose blood, if spilled, could produce demons similar ç
to him†she manifested out of herself seven emanations. These are usually ç
called the Saptam<193>t<216>kas or the `Seven little Mothers'. They ç
are Br<193>hm<200> (or Brahm<193><207><200>) M<193>he·var<200>, Kaum<193>r<200>, ç
Vai<218><207>av<200>, V<193>r<193>h<200>, N<193>rasi<221>h<200> and ç
Aindr<200> (or Indr<193><207><200>). As their very names indicate, ç
they are the <185>aktis of Brahm<193>, ®·vara, Kum<193>ra (Skanda), ç
Vi<218><207>u, Var<193>ha, Narasi<221>ha and Indra. Hence they have ç
the same forms, weapons and vehicles as their lords. Since the Dev<200>, ç
according tothe sam<%16>e<%0>work, was formed out of the combined ç
energies of all gods, this theory of the Saptam<193>t<216>kas becomes ç
intelligible to us.
Sometimes, N<193>rasi<221>h<200> is substituted by C<193>mu<207><195><193> ç
(or C<193>mu<207><195><200>). Along withthe original deity†called ç
Durg<193> Mah<193>lak<218>m<200> †they are counted as eight.
Sometimes, an esoteric interpretation is given by the followers of ç
Tantra·<193>stra, with regard to these seven m<193>t<216>k<193>s. ç
Br<193>hm<200>, according to them represents the primordial N<193>da, ç
the energy in which even the first throb has not yet appeared. This ç
is the unmanifest sound (logos), the origin of all creation. It is ç
the same as the substance or energy represented by the Pra<207>ava ç
(Om). When Br<193>hm<200> creates the universe, the power of Vai<218><207>av<200> ç
gives it a definite shape. The symmetry, beauty, organisation and ç
order in the universe are the work of Vai<218><207>av<200>. M<193>he·var<200> ç
stands for the power that gives individuality to the created beings. ç
She resides in the hearts of all and makes them play, like the dolls ç
mounted on a machine. Kaum<193>r<200>, the ever youthful deity, represents ç
the ever present force of aspiration of the evolving soul. She is ç
Guruguh<193> (Guruguha being one of the names of Kum<193>ra or Skanda ç
whose energy she is), the `guru' (guide, teacher) in the `guh<193>' ç
(the cave of the heart, the intellect). V<193>r<193>h<200> is the ç
all-consuming power of assimilation and enjoyment. Because of her, ç
the living beings get their food and all physical enjoyments. Aindr<200> ç
or Indr<193><207><200> symbolises the terrible power that destroys ç
all that opposes the cosmic law. C<193>mu<207><195><193> is the force ç
of concentrated awareness, the power of spiritual awakening in the ç
heart, that devours the ceaseless activity of the immature mind and ç
uplifts it to the highest level. Raktab<200>j<193>sura is actually ç
the mind, each wave of which gives rise to other waves. Killing of ç
this Raktab<200>j<193> by C<193>mu<207><195><193> means the destruction ç
of the mental modifications by the awakening of spiritual consciousness.
These deities are generally represented as red in colour and with ç
two hands, holding a skull and a lotus. However, since they are <185>aktis ç
of the above-mentioned gods, they are shown more often as female replicas ç
of the male deities.
Sometimes each deity is assigned a tree as specially sacred to it. ç
For instance: Udumbara (fig tree) for Kaum<193>r<200>, A·vattha (peepal ç
tree) for Vai<218><207>av<200> and the Kara<210>ja (Indian beech) ç
for V<193>r<193>h<200>.
They are usually grouped together with Ga<207>e·a and V<200>rabhadra ç
flanking on either side and shown on panels in the <185>iva temples. ç
Occasionally they have a separate shrine built for them. The order ç
or arrangement varies according to the effect desired. If the safety ç
of the village is desired Br<193>hm<200> is installed in the centre. ç
If increase in the population is the goal, C<193>mu<207><195><193> ç
occupies the central place.
@NT = saptapad<200>
@N1 = (`[the rite of taking] seven steps [together]')
See <MS>VIV°HA.<D>
@NT = Saptapur<200>
@N1 = (`the seven [sacred] cities')
The  following  seven  cities  were considered great places of pilgrimage: ç
Avant<200>, Ayodhy<193>, Dv<193>rak<193>, Haridv<193>ra, K<193><210>c<200>puram, ç
K<193>·<200> and Mathur<193>.
See under each title for details.
@NT = sapt<193>rcis
@N1 = (`seven flames')
In the ·r<193>ddha ceremonies, not only the Vedic but also the pur<193><207>ic ç
mantras are recited at the appropriate places. The sapt<193>rcis mantra ç
in which the devat<193>s (gods), pit<216>s (manes), great yogins, ç
the goddesses svadh<193> and sv<193>h<193> are adored, is to be recited ç
thrice at the beginning and the end of ·r<193>ddha as also at the ç
time of offering pi<207><195>as. As a result, the pit<216>s come quickly ç
and the goblins are supposed to run away.
This mantra occurs in the V<193>yupur<193><207>a (74.15, 16), the ç
Brahm<193><207><195>apur<193><207>a (3.11.17, 18), the Vi<218><207>udharmottarapur<193><207>a ç
(1.140.68) and a few other pur<193><207>as.
@NT = Saptar<218>is
@N1 = (`the seven sages')
The epics and the pur<193><207>as often mention the Saptar<218>is, ç
the seven sages, who are highly praised.
Generally two sets of Saptar<218>is are named, as belonging to two ç
different manvantaras (periods of Manu).
The sages of Vaivasvata-manvantara are: Atri, Bharadv<193>ja, Gautama, ç
Jamadagni, Ka·yapa, Vasi<218><219>ha and Vi·v<193>mitra.
The sages of Sv<193>yambhuvamanvantara are: A<209>girasa, Atri, Kratu, ç
Mar<200>ci, Pulaha, Pulastya and Vasi<218><219>ha.
Even now a group of seven bright stars of the constellation of Great ç
Bear is identified with them.
@NT = saptas<193>dhana
@N1 = (`sevenfold spiritual path')
The works on Ha<219>hayoga like the Ghera<207><195>a Sa<221>hit<193> ç
(1.9) describe seven exercises for purifying the body and themind, ç
and making it fit for yogic s<193>dhana.
They are: ·odhana (purification); d<216><195>hat<193> (strengthening); ç
sthairya (steadiness); dhairya (steadiness produced by the restraint ç
of the senses); l<193>ghava (lightness); pratyak<218>a (direct perception); ç
and, nirlipti (isolation).
@NT = saptasamudra
@N1 = (`seven seas or oceans')
See <MS>S°GARA.<D>
@NT = saptat<193>la
See <MS>MURTHI<185>ILPA<185>°STRA.<D>
@NT = ·arabha
@N1 = (`the killer')
In the Vi<218><207>usahasran<193>ma (356) the word as applied to ç
Vi<218><207>u is used in two senses: one who shines in the hearts ç
of embodied beings; one who destroys evil persons.
According to the legends recounted in the <185>aiv<193>gamas, ·arabha ç
is a mythical animal with eight legs and two heads, that attacks and ç
kills lions.
When N<216>si<221>ha, after killing the demon Hira<207>yaka·ipu, started ç
roaming about in the forest, striking terror in the hearts of all, ç
<185>iva assumed the form of a ·arabha and killed him! Being liberated ç
from the lion's body, Vi<218><207>u is said to have thanked <185>iva ç
and returned to his abode, the Vaiku<207><219>ha.
Obviously, this is a story invented by the followers of the cult of ç
<185>iva to deride the followers of the cult of Vi<218><207>u.
The <185>arabhopani<218>ad (27) describes Vi<218><207>u as <185>arabha ç
who shines in the hearts
