@NID = of the souls and bestows liberation upon them.
According to the Uttamak<193>mik<193>gama (54), a text belonging ç
to the <185>aiv<193>gama group, <185>arabha is a huge, monstrous form ç
of <185>iva, by appeasing whom, one can destroy one's enemies.
Iconographical works describe him as with a body which is partly animal, ç
partly a bird and with two heads wearing a big crown.
@NT = <185>arabha<209>ga
<185>arabha<209>ga was a sage belonging to the lineage of Gautama. ç
He had his hermitage on the bank of the river God<193>var<200>. He ç
was eagerly waiting to meet R<193>ma whom he knew as an incarnation ç
of Vi<218><207>u. When R<193>ma, S<200>t<193> and Lak<218>ma<207>a ç
arrived at his place, he honoured them with great devotion and then ç
gave up his old body in the Vedic fire. He ascended to heaven in a ç
divine form (vide R<193>m<193>ya<207>a of Valm<200>ki Ara<207>yak<193><207><195>a ç
5.).
@NT = S<193>rad<193>dev<200>, <185>r<200>
@N1 = (<MS>A.<|>D.<D> 1853-1920)
@SB = 1.	Introduction
Whether India has produced many great women or great women have made ç
India great, there is no gainsaying the fact that S<193>rad<193>dev<200>, ç
the immaculate spouse of the immaculate godman, R<193>mak<216><218><207>a, ç
was great in her own right. As a daughter, as a sister, as a wife, ç
as a mother and as a spiritual teacher, she has left an indelible ç
mark on the history of not only Indian women, but also on that of ç
the great women of the world. That an unlettered lady, born and brought ç
up in the rural setting of the India of the nineteenth century could ç
rise to the level of a goddess, adored by millions all overthe world, ç
speaks volumes of her greatness.
An earnest study of her life is as fascinating as it is educative, ç
of the ancientIndian values that have shaped its womanhood.
@SB = 2.	Angelic Visitations
In the history of the world, the advent of spiritual giants has often ç
been presaged by strange experiences to their parents. It happened ç
to the parents of K<216><218><207>a, Buddha and Jesus in the ancient ç
days. It happened to the parents of R<193>mak<216><218><207>a and ç
Vivek<193>nanda in the recent past. No wonder then that it happened ç
in the case of S<193>rad<193>dev<200>'s parents too.
R<193>macandra Mukherj<200> and <185>y<193>m<193>-sundar<200>-dev<200> ç
of the village of Jayar<193>mb<193><219><200> (situated about 100 ç
kms. or 60 miles to the west of Calcutta in West Bengal) were a pious ç
couple living happily within their meagre means of livelihood.
Once, when R<193>macandra was dozing off after lunch, he saw an exquisitely ç
beautiful girl of golden complexion replete with ornaments, in his ç
dream. She put her tiny hands round his neck and announced that she ç
was coming to his house.
A few days later, <185>y<193>m<193>sundar<200> while returning from ç
her native village Sihore on a hot afternoon, rested under a Bilva ç
tree. Suddenly she heard the jingling sound of small bells and saw ç
a dark little girl of great beauty descending from the tree and embracing ç
her. She lost her consciousness. When she awoke, she felt that she ç
had conceived.
These two supernatural experiences show that the child that would ç
be born to them later, was a goddess, the former representing Lak<218>m<200> ç
and the latter K<193>l<200>, both in one, since they are two aspects ç
of the same Divine Being.
This is further confirmed if it is noted that R<193>mak<216><218><207>a's ç
parents too had similar experiences, the father, of Vi<218><207>u ç
and the mother, of <185>iva!
@SB = 3.	The Advent
The divine girl-child was ushered into this world on the 22nd December ç
1853, as the eldest daughter of the family.
She was named `S<193>rad<193>ma<207>i,'* the astrological name†as ç
is usual in the Hindu household†chosen to ward off all evil and bring ç
prosperity, being `<187>h<193>k<220>r-ma<207>i' (`Jewel of a goddess').
The child S<193>rad<193> with her charming appearance and disarming ç
innocence, was the darling of the parents as also of the villagers.
Though she was a little reserved by nature, she liked the dolls of ç
Lak<218>m<200> and K<193>l<200>!
As she grew, she started helping her parents in the household chores ç
and also caring for the younger brothers. Often, she would act as ç
the judge in cases of quarrels and disputes among the children of ç
the village, because of her sagacity.
Collecting the grass for the cattle, helping in cooking were some ç
of the common duties assigned to her.
The mother instinct in her, which later on bloomed into universal ç
Motherhood, was clearly manifested during a terrible famine that once ç
raged in Jayar<193>mb<193><219><200> and the surrounding areas. The ç
little S<193>rad<193> would often be seen fanning the hot food served ç
to the hungry souls who used to swarm her house where her father had ç
organised a community kitchen.
@SB = 4.	The Little Bride and the<R>ç
	Great Groom
Hindu religion has placed before man two royal ways of life, each ç
of which, if followed sincerely, can lead to the same ultimate goal ç
of life, viz., mok<218>a or liberation. They are the prav<216>ttim<193>rga ç
(the path of activism, the householder's life)and the niv<216>ttim<193>rga ç
(the path of withdrawal, the sa<221>ny<193>sin's or the monk's<|>life).
During its long history, India has produced great spiritual leaders ç
who were either householders or monks. The solitary exception to this ç
is R<193>mak<216><218><207>a who realised God first and then married, ç
of his own accord, and yet led a life of utter renunciation and ç
total dedication to the service of the suffering souls. He was much ç
more than a householder and a monk, an ativar<207><193>·ramin (one ç
who has transcended all var<207>as and <193>·ramas), who could be ç
an ideal for both.
S<193>rad<193> was destined to be the divine consort of such a divine ç
soul.
When Candr<193>dev<200> and R<193>me·var (mother and elder brother ç
of R<193>mak<216><218><207>a) heard that their dear `Gad<193>i' (Gad<193>dhar, ç
the earlier name of R<193>mak<216><218><207>a) had gone stark mad, ç
they were naturally very much concerned. At their earnest entreaties, ç
R<193>mak<216><218><207>a returned to K<193>m<193>rpuk<220>r, his ç
native village. To their pleasant surprise they found him to be perfectly ç
normal, the same old affable self.
Even then, not prepared to take any risk, they secretly started searching ç
for a suitable bride, thinking that, that would prevent him from becoming ç
`mad' again. When they were utterly frustrated in their efforts, R<193>mak<216><218><207>a ç
himself asked them to go to R<193>macandra Mukherj<200>'s house at ç
Jayar<193>mb<193><219>i where there was a bride specially marked for ç
him!
@BT9 = [According to an oral tradition, the baby S<193>rad<193>, on ç
an earlier occasion, had pointed towards the boy Gad<193>dhar from ç
among the boys who had gathered, as her future husband, when jokingly ç
asked by the village women.]
The search did prove to be highly successful. Everything was found ç
to be not only right but also extremely auspicious, except that the ç
bride was hardly six years old whereas the groom was twenty-three!
The marriage went off (in May 1859) fairly smoothly.
R<193>mak<216><218><207>a then returned to Dak<218>i<207>e·var (a ç
suburb of Calcutta) to plunge once again into further spiritual adventures.
The little bride continued her life in the same old fashion at her ç
village house.
@SB = 5.	In Blissful Company
R<193>mak<216><218><207>a returned to K<193>m<193>rpuk<220>r again ç
in <MS>A.<|>D.<D> 1867 and stayed there for a few months. At this time, ç
he called S<193>rad<193> to live with him, specifically to train her ç
for her future life. Being fourteen, she was now old enough to understand ç
things.
R<193>mak<216><218><207>a taught her, not only how to call on God ç
(how to pray and meditate) but also about the ephemeral nature of ç
the world and worldly life. However, he also took care to train her ç
in the performance of all the domestic duties, including the way to ç
behave with various types of persons.
In later years, recalling this period of her life, S<193>rad<193>dev<200> ç
used to say that she had always felt as if a pitcher of ambrosia had ç
been kept in her heart. The bliss and the peace she then experienced ç
were beyond expression.
R<193>mak<216><218><207>a returned to Dak<218>i<207>e·var soon after.
@SB = 6.	Womanhood to Godhood
After the demise of R<193><207>i R<193>sama<207>i (<MS>A. D.<D> 1793-1861) ç
who built the Dak<218>i<207>e·var K<193>l<200> temple campus, Mathur ç
(Mathurn<193>th Bi·v<193>s [<MS>A.<|>D.<D> 1817-1871<%10>])<%0>, her ç
son-in-law and trusted lieutenant, had taken over the management of ç
the temple as also the guardianship of R<193>mak<216><218><207>a. ç
At his earnest entreaties, R<193>mak<216><218><207>a undertook a long ç
pilgrimage along with him.
Soon after this, Mathur passed away.
S<193>rad<193>dev<200> was now eighteen. She was spending her days ç
in the fond expectation of the call from Dak<218>i<207>e·var which, ç
however, never came. Unable to put up with the rampant rumour that ç
the village gossips bandied about regarding R<193>mak<216><218><207>a's ç
mental condition, she arrived at Dak<218>i<207>e·var unannounced, ç
one night, in March 1872, along with her father, trudging all the ç
way.
Contrary to her worries and fears, R<193>mak<216><218><207>a received ç
her with cordiality and warmth and even arranged immediately for her ç
treatment since she had fallen sick on the way.
She was now at peace.
Soon after her arrival, R<193>mak<216><218><207>a asked her one day ç
whether she had come to pull him down from spiritual heights to mundane ç
depths. Pat came the reply that her only purpose in her life was to ç
serve him and be of help in his spiritual endeavours.
Another day, while massaging his feet, S<193>rad<193> in her turn ç
asked him how he looked upon her. The spontaneous reply was that to ç
him, the Divine Mother in the temple, the earthly mother in the Nahabat ç
(the music tower where Candr<193>dev<200> was living) and she who ç
was serving him now, were all the same!!
Days passed by, with R<193>mak<216><218><207>a going frequently into ç
his ecstatic moods (called sam<193>dhi) and S<193>rad<193> serving ç
him and Candr<193>dev<200> devotedly and meticulously.
One day†known as the Phalah<193>ri<207><200> K<193>l<200>p<220>j<193> ç
day†R<193>mak<216><218><207>a made all the preparations for the worship ç
of <186>o<195>a·<200> (anexquisitely beautiful aspect of the Divine ç
Mother), installed S<193>rad<193>dev<200> on the consecrated wooden ç
seat meant for the goddess and worshipped her with all the ingredients ç
and ritualistic procedures.
@SPACE1 = 
Almost from the start of the worship she was in a superconscious state. ç
When at the end, R<193>mak<216><218><207>a offered his rosary at her ç
feet, symbolising the total surrender of all his spiritual attainments, ç
she was in deep sam<193>dhi, which lasted for quite a long time. After ç
coming down to the normal plane of consciousness, she walked out of ç
the room majestically with extreme grace.
This event, now well-known as the <186>o<195>a·<200>p<220>j<193> in ç
the annals of the Rama-krishna Order, marks a very significant stage ç
in her life.
Apart from the rousing of the universal motherly spirit in her, she ç
also, automatically, became the possessor of all the spiritual wealth ç
that her divine spouse had acquired over the years through superhuman ç
efforts. Thus, S<193>rad<193>dev<200>, the spouse of R<193>mak<216><218><207>a, ç
became the Holy Mother or just the Mother even as he came to be known ç
extensively as the Paramaha<221>sa.
@SB = 7.	Flow of Events
The Holy Mother, hereafter, lived more or less continuously for about ç
thirteen years at Dak<218>i<207>e·var with occasional short breaks ç
when she used to go to Jayar<193>mb<193><219><200>.
These years proved to be hectic in every sense of the term. Apart ç
from taking care of Candr<193>dev<200>†R<193>mak<216><218><207>a's ç
mother who lived with him till her death in <MS>A.<|>D.<D> 1876†she ç
had to do all the work of the household, including cooking food for ç
the ever-increasing number of devotees of her divine husband, now ç
popularly called <187>h<193>k<220>r or the Master.
It was during this period, in one of her sojourns to and from Jayar<193>mb<193><219><200> ç
†probably during her third visit in <MS>A.<|>D.<D> 1877†that she had ç
to encounter a robber and his wife in the forest area, since she had ç
got separated from the group and lost her way. Her great presence ç
of mind, fearlessness and universal love made her address them as ç
`Father' and `Mother' thereby melting even their stony hearts. On ç
learning of her predicament, the couple reciprocated her filial love ç
by taking care of her for the night and leading her to the group the ç
next day.
A severe bout of almost a fatal illness (dysentery) from which she ç
recovered due to the simple remedy suggested by the goddess Si<221>hav<193>hin<200> ç
of Jayar<193>mb<193><219><200> and the unceremonious exit of H<216>day ç
(a nephew of the Master who was also hispersonal attendant) due to ç
his rude behaviour towards her, are the other events worth mentioning ç
here.
@SB = 8.	The Master Departs
Just  as  R<193>mak<216><218><207>a,  the  Great Master, had predicted, ç
his departure from earthly existence was fast approaching. He  contracted  throat-cancer  around ç
September  1885  and  was  shifted  to Calcutta (now Kolkata), to ç
a garden-house at K<193>·<200>pur (spelt also as Cossipore), which ç
was quite spacious and airy.
The Holy Mother also shifted thereand took upon herself the duty ç
of preparing the diet and feeding him.
The  young  disciples  under  the leadership of Narendra (the future ç
Vivek<193>nanda) took charge of the nursing, round the clock.
One  of  these  days,  the  Master, intently looking at the Holy Mother, ç
commanded her†in spite of her protests† to continue his work of spiritual ç
ministration.
After choosing a day and time for his final departure, the Great Master ç
shuffled off the mortal coil. It was on the 16th August 1886 around ç
1:00 A.M.
Though some strange experiences had prepared her mind for this final ç
departure, she did feel intensely the sorrow of separation. However, ç
when the Master appeared before her in a vision and assured her that ç
he had only gone `from one room to another' she was consoled.
@SB = 9.	Maiden Pilgrimage
To assuage her feelings and divert her mind, a pilgrimage to V<216>nd<193>ban ç
(or B<216>nd<193>van, in Uttar Pradesh), a place intimately associated ç
with the life of Lord K<216><218><207>a, was arranged. Some women ç
disciples of the Master as also Yogen (later, Sv<193>mi Yog<193>nanda) ç
accompanied her.
During this pilgrimage, not only did she feel a sense of utter peace ç
and joy, but also experienced sam<193>dhi quite frequently.
It was here that she prayed intensely to the Lord to eradicate from ç
her mind, the tendency to find fault with others. Her later life has ç
proved amply how this prayer of hers had been answered.
Yogen received spiritual initiation from her here as her first disciple, ç
at the command of the Master himself to both of them.
After visiting a few other places she returned to Calcutta by August ç
1887.
@SB = 10.	Penury and Privation
Even God made himself a V<193>mana or a dwarf while begging from the ç
emperor Bali. So, begging from others makes one small in the eyes ç
of others. Citing this as an example, the Master had asked the Holy ç
Mother to live in his ancestral home at K<193>m<193>rpuk<220>r, after ç
his passing away, without being under anyone's obligation.
Soon after returning to Calcutta, the Mother shifted to K<193>m<193>rpuk<220>r ç
and started living there. Except for some paddy grown in the ancestral ç
property, there was nothing else to support her. Rice, without even ç
a pinch of salt, prepared after dehusking paddy and cooking, was the ç
only food she had.
Later on, she started growing a few vegetables in the backyard by ç
dint of her own physical labour.
Though she was contented and at peace, one thing that often distressed ç
her was that she could not bathe in the Ga<209>g<193> river. One day ç
she suddenly saw, with her eyes wide open, that the Master had come ç
there and suddenly the river Ga<209>g<193> sprang from his feet and ç
started flowing in torrents! This vision satiated her desire by showing ç
that the Master was everything.
It may be mentioned here that according to the Hindu scriptures, the ç
river Ga<209>g<193> originated from the feet of Lord Vi<218><207>u ç
in his incarnation as V<193>mana (the dwarf).
@SB = 11. 	Back to the Metropolis
Her extreme poverty and privation, however, did not last long. Very ç
soon, news of her miserable condition reached the devotees of the ç
Master at Calcutta and they made some arrangements for her comfortable ç
stay. At their earnest request she shifted there and started living ç
there till her final departure from this world.
@SB = 12.	Domestic Entanglements
Ever since the Master's departure, the pilgrimage to V<216>nd<193>ban ç
and the privations at K<193>m<193>rpuk<220>r, Holy Mother's mind was ç
frequently soaring to great spiritual heights and it was often difficult ç
to bring it down to the mundane plane. But a lot of work assigned ç
to her by the Great Master was yet to be accomplished. So, some worldly ç
peg or post was needed to fasten her mind to this plane and prevent ç
its flying away.
Through a couple of visions, the Master showed her a girl (whom he ç
called, `Yogam<193>y<193>') and asked her to fix her mind on her so ç
as to prevent it from flying too high or away.
This girl was R<193>dhu, the daughter of Abhaycara<207> (Holy Mother's ç
youngest brother) who died prematurely. His wife Surab<193>l<193> ç
was stark mad. Hence, the responsibility of bringing up that child ç
devolved on the Mother. Or, rather, the Mother voluntarily took up ç
that responsibility as directed by the Master. By pinning her affection ç
on this R<193>dhu, the Mother made it a prop for sustaining her life ç
in this world, for the good of the many.
Apart from the responsibility of R<193>dhu and her mad mother, the ç
Holy Mother often got involved in the family affairs of her brothers, ç
whose profanity knew no bounds.
Though  these  worldly  ties  and responsibilities kept her busy in ç
a way, her spiritual sublimity never diminished, even as the river ç
Ga<209>g<193> is never polluted by anything floating in it.
@SPACE1 = 
Special mention must be made here of an incident at Gay<193> to where ç
the Holy Mother had gone on a pilgrimage since the Master†who could ç
not go himself† had commanded her to do so. There she saw a well-established ç
Hindu monastery where the sa<221>ny<193>sins were provided with good ç
accommodation and food. The contrast between this and the poverty-stricken ç
wandering monks of the Great Master† whom she considered as her children† ç
affected her so much that she prayed to the Master intensely with ç
tears in her eyes to provide her children too with similar comforts. ç
Later developments which culminated in the establishment of the Ramakrishna ç
Math at Belur were in answer to her prayers.
@SB = 13.	Spiritual Ministrations
If compassion and mercy are divine qualities, the Divine Mother is ç
the very personification of the same. And, the Holy Mother was just ç
that!
The one who had refused to take the responsibility of continuing the ç
Master's work of saving the souls, later relented to such an extent ç
that even the vilest of sinners were not turned away at her gate. ç
Anyone who addressed her as `Mother!' would immediately find a place ç
at her feet and feel the warmth of the Mother's love and the security ç
of her protection. Monks, householders, children, fallen women, even ç
criminals, succeeded in finding spiritual shelter at her feet.
Her method of spiritual ministration was unique in that all formalities ç
weretranscended and infinite love alone triumphed. The disciples ç
would feel a sense of instant upliftment. Many a disciple who saw ç
her for the first time had felt and recognised her as having seen ç
her earlier in a dream or in some other mysterious way. Instances ç
are not wanting where she has herself called persons and initiated ç
them!
She had to pay a heavy price in the form of physical suffering for ç
her liberality. Her attendants and associates had found her doing ç
japa at dead of night for the benefit of those whom she had accepted ç
as disciples, but who had forgotten even the mantra given to them, ç
let alone practise repeating it!
The Great Master himself had taught her various mantras as well as ç
the modes of imparting them.
@SPACE = 
@SB = 14.	Pa<210>catapas and Visions
@SPACE = 
Another important incident of her life concerning her own austerities ç
needs to be mentioned here. When she was living in the garden-house ç
of N<200>l<193>mbar B<193>bu on the bank of the river Ga<209>g<193> ç
(near the present Belur Math, the Head Quarters of the Ramakrishna ç
Order) in <MS>A.<|>D.<D> 1893 she performed the Pa<210>catapas or the ç
`Austerity of the Five Fires', along with Yogin M<193>, a disciple ç
of the Master and a life-long companion of hers. On the roof of the ç
house, four blazing fires were prepared, with the fiercely burning ç
sun as the fifth fire. Both of them used to sit in the midst of these ç
five fires and performjapa (repetition of the divine name) till sunset. ç
This was done for sevenconsecutive days, a superhuman feat indeed!
It was again during this period of her stay here that she had a unique ç
vision of R<193>mak<216><218><207>a entering the river Ga<209>g<193> ç
and getting dissolved in it. Narendra (Vivek<193>nanda)  quickly  following  and ç
sprinkling that water on a large crowd that had gathered there, was ç
the next scene. It was after this vision that she gave permission ç
to Vivek<193>nanda to go to America.*
@SB = 15.	`Mother's House'
Ever since the Holy Mother arrived in Calcutta for a permanent stay, ç
and started living in the houses of the Master's devotees†and, sometimes, ç
in houses taken temporarily on rent†a great need was being felt by ç
Sv<193>mi S<193>rad<193>nanda, (a direct monastic disciple of the ç
Master) on whose shoulders the responsibility of taking care of her, ç
rested.
By raising funds including borrowals, he managed to build a spacious ç
and beautiful building in the Baghbazaar area of Calcutta. It was ç
here that he wrote hisimmortal work <185>r<200>r<193>mak<216><218><207>a ç
L<200>l<193>-prasa<209>ga (Sri Ramakrishna, The Great Master), ç
the sale proceeds of which were partly used in repaying the loans.
On the first floor was the shrine for the worship of R<193>mak<216><218><207>a ç
where itself the Holy Mother also lived. Her entourage also stayed ç
in the same floor.
She entered this new house on the 23rd May 1909 and lived there till ç
the end of her life.
The ground-floor of the building also housed the office of the Udbodhan, ç
the Be<209>g<193>l<200> monthly journal of the Rama-krishna Order ç
started by Vivek<193>nanda himself in <MS>A.<|>D.<D> 1899. Hence it ç
has also come to be known as the `Udbodhan House'.** The monks too ç
lived in the same ground floor.
@SB = 16.	Pilgrimage to R<193>me·varam
On Vivek<193>nanda's triumphant return from the West in 1897, his ç
old friends, associates and admirers at Madras (now Chennai) pressed ç
him to send a sa<221>ny<193>sin to continue his work of spreading ç
the message. Accordingly he sent Sv<193>mi R<193>mak<216><218><207><193>nanda ç
(known earlier as <185>a·ibh<220><218>an or <185>a·i) to Madras where ç
he started a centre, now well-known as the Sri Ramakrishna Math (at ç
Mylapore).
Towards the end of February 1911, R<193>mak<216><218><207><193>nanda ç
organised a trip for the Holy Mother to R<193>me·varam, the famous ç
place of pilgrimage.
The Mother stayed at Madras for a few days and also gave initiation. ç
It was surprising to discover that language was no barrier for her ç
communicating with the local people.
At R<193>me·varam she had the rare privilege of worshipping the <185>ivali<209>ga ç
in the temple with 108 golden bilva leaves (Aegle marmelos) with ç
her own hands.
She is also said to have remarked that it (the <185>ivali<209>ga) ç
was just as it had been established by her earlier (as S<200>t<193> ç
in the R<193>ma-incarnation?).
She also visited the Ramakrishna Ashrama (now Ramakrishna Math) at ç
Bangalore during the same period (March24 to 26, 1911) before returning ç
to Calcutta.
Later in 1912, she visited K<193>·<200> (V<193>r<193><207>as<200> ç
in Uttar Pradesh) for the third time. This was her last pilgrimage.
@SB = 17.	Mah<193>sam<193>dhi
Apart from aging factors, the ever-increasing domestic responsibilities, ç
physical strain of giving d<200>k<218><193> or initiation to a very ç
large number of seekers and the subtle taking over of the burdens ç
of their sins (even partially) told on her health adversely. As a ç
result, her body began to show signs of breaking down.
By the time the doctors discovered the nature of the disease known ç
as K<193>l<193>-az<193>r (black-water fever), it was too late.
A few days before her final departure, she was found to have completely ç
detached her mind from R<193>dhu and her baby, thereby indicating ç
the abandonment of the prop that had held her to sustain her physical ç
life here. Now, none could hold her back from returning to her Master ç
any more!
She gave up the physical frame on the 20th July 1920.
@SPACE1 = 
Her body was carried in a long procession and was cremated on the ç
bank of the river Ga<209>g<193> in the Belur Math Campus (Headquarters ç
of the Rama-krishna Order), where now stands a small temple.
@SB = 18.	Final Message
Five days before her demise, she addressed a grieving lady-devotee ç
of hers thus: `Why are you afraid? You have seen the Master... But ç
I tell you one thing: If you want peace of mind, do not find fault ç
with others. Rather, see your own faults. Learn to make the world ç
your own. No one is a stranger. The whole world is your own!'
This can be treated not only as her last message to the world but ç
also as a reflection of the quintessence of her life itself.
The first part gives a tremendous assurance to all those who have ç
seen R<193>mak<216><218><207>a, the Great Master, to be free of all ç
fear by that very act. In other words, all those who have chosen to ç
have him as their ideal and strive for perfection through the path ç
shown by him, will be freed from the fears and dangers of transmigratory ç
existence.
The second part gives us not only the method of attaining such fearlessness ç
but also the end-result of the same.
At the outset, it should be understood that this `finding fault' does ç
not apply to those cases where love is the driving force behind ç
it and correcting the person is the ultimate goal, as in the case ç
of parents or teachers chastising their wards.
It applies only to those cases where people find fault with others ç
out of hatred or jealousy or a `holier-than-thou' attitude.
@SPACE1 = 
By not finding fault with others† since `to err is human and to forgive, ç
divine'†we can keep good human relationship with them.
By discovering our own faults and foibles through calm self-introspection, ç
we will be able to make serious attempts to eliminate them, thereby ç
becoming more agreeable to others. Also, we will look upon others ç
with greater sympathy and understanding.
